### ISSUE TITLE
[BUG] CSI plugin pod keep crashing util the backup volume appears  when creation a backup via the CSI snapshotter

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#10008]
## Describe the bug

When creating a backup via the CSI snapshotter, the Lognhorn CSI plugin and CSI snapshotter pods will keep crashing util the backup volume is created.

## To Reproduce

1. Fresh install
2. Enable the CSI snapshotter by steps https://longhorn.io/docs/1.8.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support
3. Create a backup via the CSI snapshotter.
4. The Lognhorn CSI plugin and CSI snapshotter pods will keep crashing until the backup volume is created.

## Expected behavior

The Lognhorn CSI plugin and CSI snapshotter pods will not crash

## Environment

 - Longhorn version: 1.8.0-dev
 - Impacted volume (PV): 1 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s, v1.31.1+k3s1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: ubuntu 22.04
   - Kernel version: 5.15.0-91-generic
   - CPU per node: 4 
   - Memory per node: 4G
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 1
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 1

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-manager/commit/def8a3b392be7380a85ef74d688c86456c03c791) and v1.8.0-rc1(https://github.com/longhorn/longhorn-manager/commit/b59110d2488208f4f15ebc3bf3ce5e66eb344ffb)

1. .Fresh install
2. Enable the CSI snapshotter by steps https://longhorn.io/docs/1.8.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support
3. Dynamic provision PVC vol1 with and workload, write data to workload.
4. Create volume VolumeSnapshotClass longhorn-test
```
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn-test
driver: driver.longhorn.io
deletionPolicy: Delete
```
5. Create VolumeSnapshot vol1-volumesnapshot, the volumesnapshot and snapshot are ready to use. the backup creation is complete.
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: vol1-volumesnapshot
spec:
  volumeSnapshotClassName: longhorn-test
  source:
    persistentVolumeClaimName: vol1
```
6. Did not see CSI pligin pod crashing.

**Comment by derekbit** [comment]
Good catch @mantissahz
