### ISSUE TITLE
[BUG] The csi-attacher pod restarts suddenly, and the following error logs appear:

### ISSUE THREAD

**Issue by aljabertareq** [longhorn/longhorn#10003]
@Wael Al-Fawal

## Describe the bug
The csi-attacher pod restarts suddenly, and the following error logs appear:

csi_handler.go:234] Error processing "csi-95a724b68a8cbb6bf9ca42071d5fada6fe6857f6bcc7ab659dc4a9ae93dd4386": failed to attach: rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=unable to attach volume pvc-3adeeb3a-ad02-46dc-9e1f-e888f617bfaf to node2: node node2 is not ready, couldn't attach volume pvc-3adeeb3a-ad02-46dc-9e1f-e888f617bfaf to it, code=Internal Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes/pvc-3adeeb3a-ad02-46dc-9e1f-e888f617bfaf?action=attach]

## To Reproduce
without any manual intervention or configuration changes, the pod keep  restarting while logging attachment errors,  after a few seconds, it resumes normal operation.

## Expected behavior
The csi-attacher pod should not restart unexpectedly, and the volume attachment process should not fail repeatedly if the node is ready.

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by mantissahz** [comment]
track on ticket #10002
