### ISSUE TITLE
[TEST] Backing Image test cases failed

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#10017]
## What's the test to develop? Please describe

It seems the Backing Image test cases need to update:
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7836/console

**Comment by ChanYiLin** [comment]
It is due to the original test case tried to create a 16MB Volume with a 32MB BackingImage
This is disallowed in the v1.8.0


Fix the test case: https://github.com/longhorn/longhorn-tests/pull/2211

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-manager 1d87226) and v1.8.x-head (longhorn-manager 7f2cd62). Backing image related test cases passed.

master-head: https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/1135/testReport/tests/test_backing_image/
v1.8.x-head: https://ci.longhorn.io/job/public/job/v1.8.x/job/v1.8.x-longhorn-tests-sles-amd64/5/testReport/tests/test_backing_image/
