### ISSUE TITLE
[BUG] BackupBackingImage Create failed because it failed to get the BackingImage

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#10020]
## Describe the bug

BackupBackingImage Name is now not the same as the BackingImage due to multiple backupstore

## To Reproduce

test_backing_image.py e2e test failed.
 
## Expected behavior

test_backing_image.py e2e test passed.

**Comment by ChanYiLin** [comment]
PR: https://github.com/longhorn/longhorn-manager/pull/3367

**Comment by derekbit** [comment]
@ChanYiLin Merged.

**Comment by ChanYiLin** [comment]
thanks
the e2e test also passed.
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7862/

**Comment by ChanYiLin** [comment]
@derekbit 
I have moved to ready for testing.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-manager/commit/def8a3b392be7380a85ef74d688c86456c03c791), longhorn v1.8.0-rc1(https://github.com/longhorn/longhorn-manager/commit/b59110d2488208f4f15ebc3bf3ce5e66eb344ffb)

e2e `Test Backing Image Basic Operation` passed
- [master](https://ci.longhorn.io/job/private/job/longhorn-e2e-test/2240/)
- [v1.8.0-rc1](https://ci.longhorn.io/job/private/job/longhorn-e2e-test/2239/)


regression `test_backing_image.py` test cases all passed
- [master](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7865/)
- [v1.8.0-rc1](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7864/)
