### ISSUE TITLE
[BUG][v1.8.x] Unable to add block disk after node deleted and added back

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#10035]
## Describe the bug

In Longhorn v1.8.x-head (longhorn-manager ), unable to add block disk to node after node deleted and added back .

## To Reproduce

1. Install Longhorn with 1 control plane and 3 worker nodes
2. Enable `v2-data-engine`
3. Add block disk `/dev/xvdh` to all 3 worker nodes `node-0`, `node-1`, and `node-2` through Longhorn UI:
![add-disk-4](https://github.com/user-attachments/assets/f5571095-0bf2-4631-947b-ca322d7e4006)
4. Delete node `node-1` from k8s by executing the following command:
```
$ kubectl delete node `node-1`
```
5. Add `node-1` back by shutting it down and rebooting it
6. After `node-1` is added back, the previously added block disk `/dev/xvdh` is missing. Re-add this block disk back to `node-1` through Longhorn UI again:
![add-disk-4](https://github.com/user-attachments/assets/f5571095-0bf2-4631-947b-ca322d7e4006)
7. Block disk `/dev/xvdh` can be successfully added to `node-1`
8. Remove block disk `/dev/xvdh` from all 3 worker nodes  `node-0`, `node-1`, and `node-2` through Longhorn UI:
![add-disk-3](https://github.com/user-attachments/assets/9d96ac50-0718-4bbe-b97e-30101dcb0323)
9. Re-add block disk `/dev/xvdh` to all 3 worker nodes `node-0`, `node-1`, and `node-2` through Longhorn UI again. Adding block disk `/dev/xvdh` to `node-0` and `node-2` will fail with the following error:
```
admission webhook "validator.longhorn.io" denied the request: spec and status of disks on node ip-10-0-1-222 are being syncing and please retry later.
```
![add-disk-1](https://github.com/user-attachments/assets/b9dfcc0c-8341-421e-b3e9-236fa7a05478)
No matter how long I waited and how many time I retried, the attempt to add the block disk will not succeed.
10. Only previously deleted node `node-1`, can have the block disk `/dev/xvdh` successfully added back without problems.

OR

Run `longhorn-e2e-test` pipeline with `ROBOT_CUSTOM_OPTIONS` set to `-s \"node_delete\" -v LOOP_COUNT:1 -v RETRY_COUNT:259200`

## Support bundle for troubleshooting

[supportbundle_8d8b3771-67e6-4aa8-84d7-5d6a6769df84_2024-12-23T01-07-32Z.zip](https://github.com/user-attachments/files/18224137/supportbundle_8d8b3771-67e6-4aa8-84d7-5d6a6769df84_2024-12-23T01-07-32Z.zip)

## Environment

 - Longhorn version: v1.8.x-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.31.2+k3s1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: ubnutu 24.04 or sles 15-sp6
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
Mistakenly add `backport/v1.6.4` label.

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-manager 718b6b4) and v1.8.x-head (longhorn-manager e8b5292). Test suite `node_delete` passed.

master-head: https://ci.longhorn.io/job/private/job/longhorn-e2e-test/2297/
v1.8.x-head: https://ci.longhorn.io/job/private/job/longhorn-e2e-test/2296/
