### ISSUE TITLE
Tolerations setting not working as expected

### ISSUE THREAD

**Issue by akimsko** [longhorn/longhorn#1003]
I run a test RKE setup, using Rancher, consisting of 1 physical master (controlplane+etcd), and 2 physical workers, and am currently toying with running Longhorn.

I would like to have the master node run Longhorn replicas as well as the workers. I tried using the tolerations settings field, to allow scheduling on the master node, as it is tainted with the following:
 * node-role.kubernetes.io/controlplane=true:NoSchedule
 * node-role.kubernetes.io/etcd=true:NoExecute

However the unmarshaller, for the tolerations setting, will not accept this value:
"node-role.kubernetes.io/controlplane=true:NoSchedule; node-role.kubernetes.io/etcd=true:NoExecute"

After inspecting the unmarshal code, I managed to get it to partially work with the following value:
" :NoSchedule; :NoExecute"

It worked for all components except the longhorn-manager, as it does not get the correct tolerations set.

Inspecting longhorn-manager, I only see the following toleration:
```
tolerations:
      - effect: NoExecute
        operator: Exists
```

While inspecting other components, like csi-provisioner, gives me the expected tolerations:
```
tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
```

I understand the feature was intended for dedicated storage nodes with custom taints. But besides the fact that it seems broken for longhorn-manager, is there any reason to explicitly disallow `kubernetes.io` taints? To me, it seems a bit overly restrictive, and serves only to limit its practical use cases.

---
Version: `v0.7.0`

**Comment by shuo-wu** [comment]
1. There is no kubelet on non-worker nodes. Hence Longhorn components won't be launched on the non-worker nodes.
2. Since Longhorn is not supposed to modify the default settings, it needs to distinguish the Kubernetes default taints from the taints set by users. Then Longhorn simply considers the taint whose keys contain `kubernetes.io` as the Kubernetes default taints and will reject this kind of taint setting.

**Comment by akimsko** [comment]
Thanks for the reply. However it does not really address the issue. RKE does indeed run Kubelet on controlplane/etcd nodes, but that's a little bit off topic.

The issue is that there seems to be a problem setting tolerances correctly for longhorn-manager via settings.

**Comment by shuo-wu** [comment]
I just tried to set tolerations to ` :NoSchedule; :NoExecute`. Then all Longhorn components contained the following toleration only (except for the existing Kubernetes tolerations):
```
  - effect: NoExecute
    operator: Exists
```
And this toleration was not shown:
```
  - effect: NoSchedule
    operator: Exists
```

Actually, the effect `NoSchedule` is included in the effect `NoExecute`. You can check [the Kubernetes official doc](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/) for more details. Here are the explanations for these two effects:
```
if there is at least one un-ignored taint with effect NoSchedule then Kubernetes will not schedule the pod onto that node
if there is no un-ignored taint with effect NoSchedule but there is at least one un-ignored taint with effect PreferNoSchedule then Kubernetes will try to not schedule the pod onto the node
if there is at least one un-ignored taint with effect NoExecute then the pod will be evicted from the node (if it is already running on the node), and will not be scheduled onto the node (if it is not yet running on the node).
```

I don't know why `effect: NoSchedule` exists in your Longhorn components, it's weird...
