### ISSUE TITLE
[BUG] Unable to restore latest backup from backup page

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#10046]
## Describe the bug

We are unable to restore the latest backup from the backup page.
![Recording 2024-12-23 at 19 59 49](https://github.com/user-attachments/assets/eac21fd5-66c4-4368-9764-8da763d97d6a)

## To Reproduce

1. Navigate to the backup page.
2. Attempt to restore the latest backup.
3. Observe that the restoration process fails or does not initiate.

## Expected behavior

The latest backup should be successfully restored when selected from the backup page.

## Support bundle for troubleshooting

[supportbundle_7904f20b-1bf8-4f06-92ef-c69b71830e9c_2024-12-23T12-00-17Z.zip](https://github.com/user-attachments/files/18229286/supportbundle_7904f20b-1bf8-4f06-92ef-c69b71830e9c_2024-12-23T12-00-17Z.zip)

## Environment

 - Longhorn version: `v1.8.x-head`
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
@roger-ryao Can it work by kubectl?

**Comment by derekbit** [comment]
@mantissahz Please check the issue.

**Comment by mantissahz** [comment]
Hi @roger-ryao,

Can you check if it is still valid for v1.8.x-head because https://github.com/longhorn/longhorn-manager/pull/3393 just merged in 2 hours ago ?

**Comment by roger-ryao** [comment]
**Verified on master-head 20241224**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/7cd6412137171db36e06eeae82e97364558a877d
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/718b6b4d3db6e4b3a0a06e00d4053b915a2a9530


**Verified on v1.8.x-head 20241224**

- longhorn `v1.8.x-head` https://github.com/longhorn/longhorn/commit/ede8f46a75704352e33fbc45b01f14fa2770a827
- longhorn-manager `v1.8.x-head` https://github.com/longhorn/longhorn-manager/commit/e8b5292131205725745468c61d00200986107dbf


**The test steps**
https://github.com/longhorn/longhorn/issues/10046#issue-2755974865

**Result Passed**
