### ISSUE TITLE
[BUG] Unable to delete backing image backup through UI

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#10047]
## Describe the bug

In Longhorn master-head (longhorn-ui 21c4758), it's unable to delete backing image backup through UI:

![Peek 2024-12-23 21-35](https://github.com/user-attachments/assets/c274ef4f-d656-4bb7-922a-f0c065235c8b)

## Environment

 - Longhorn version: master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: ubnutu 24.04
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by yangchiu** [comment]
> @yangchiu deletable by kubectl?

Yes.

**Comment by houhoucoop** [comment]
I can't reproduce on my end, could you provide more details?

**Comment by yangchiu** [comment]
> I can't reproduce on my end, could you provide more details?

1. Install Longhorn master-head (longhorn-ui 21c4758)
2. Set up backupstore and default backup target 
3. Create backing image from url: `https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.qcow2`
4. Backup this backing image
5. Wait for this backing image backup state set to `Completed`
6. Delete the this backing image backup like https://github.com/longhorn/longhorn/issues/10047#issue-2756091407

**Comment by houhoucoop** [comment]
Confirm that this defect is specific to backing image names containing `v1`.

**Comment by houhoucoop** [comment]
@derekbit Does this require a backport to version `1.7.x`?

**Comment by derekbit** [comment]
> @derekbit Does this require a backport to version `1.7.x`?

Does it happen in v1.7.x as well?

**Comment by houhoucoop** [comment]
> > @derekbit Does this require a backport to version `1.7.x`?
> 
> Does it happen in v1.7.x as well?

Yes. 
Although `v1.6.x` doesn't include the backing image restore, the volume backup still has a UI issue. I think we should backport to `v1.6.x` as well.

https://github.com/user-attachments/assets/0d053b2c-3052-4dec-b402-74fcf15281ad

**Comment by derekbit** [comment]
Thank you @houhoucoop

**Comment by derekbit** [comment]
Let's backport to v1.7.x. 
We can create a new bug ticket for **volume backup** issue.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-ui/commit/f903b6a4b724a7e05cce1509d5465e48d98c6967), v1.8.x(https://github.com/longhorn/longhorn-ui/commit/47c97e0dc42f0431909e6992ccb42884332bd648) with test [steps](https://github.com/longhorn/longhorn/issues/10047#issuecomment-2560742353)
