### ISSUE TITLE
[BUG] Unable to update volume backup target in volume detail page

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#10045]
## Describe the bug

We are unable to update the volume backup target from the volume detail page.

![Recording 2024-12-23 at 20 16 50](https://github.com/user-attachments/assets/fa1600f2-eca4-4eeb-9ff1-e6a57fb92d5d)

## To Reproduce

1. Navigate to the volume detail page for a specific volume.
2. Attempt to update the backup target.
3. Observe that the update does not take effect.

## Expected behavior

The backup target should be successfully updated when changed in the volume detail page.

## Support bundle for troubleshooting

[supportbundle_7904f20b-1bf8-4f06-92ef-c69b71830e9c_2024-12-23T12-16-22Z.zip](https://github.com/user-attachments/files/18229241/supportbundle_7904f20b-1bf8-4f06-92ef-c69b71830e9c_2024-12-23T12-16-22Z.zip)

## Environment

 - Longhorn version: `v1.8.x-head`
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
cc @houhoucoop @mantissahz

**Comment by derekbit** [comment]
@a110605 
All PRs are merged. Please update the pre-check list and move to ready-for-testing. Thank you.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-ui/commit/f903b6a4b724a7e05cce1509d5465e48d98c6967), v1.8.x(https://github.com/longhorn/longhorn-ui/commit/47c97e0dc42f0431909e6992ccb42884332bd648) with test [steps](https://github.com/longhorn/longhorn/issues/10045#issue-2755957226)
