### ISSUE TITLE
Unable to delete volume - UI

### ISSUE THREAD

**Issue by awlleon** [longhorn/longhorn#1004]
I can not delete a volume.
![longhorn](https://user-images.githubusercontent.com/51808092/71875469-6129b980-315f-11ea-9be2-bb83041cb836.png)

but I can manually remove the volume from the backend use command
kubectl -n longhorn-system delete volumes.longhorn.io <volume-name> ,

**Comment by awlleon** [comment]
I find the longhornio/longhorn-engine:v0.7.0 state is Deploying.
![longhorn2](https://user-images.githubusercontent.com/51808092/72031434-6144c900-32c7-11ea-8cad-4fd6146ab38e.png)

- kubectl describe engineimage.longhorn.io ei-ec95b5a -n longhorn-system :

Name:         ei-ec95b5ad
Namespace:    longhorn-system
Labels:       <none>
Annotations:  <none>
API Version:  longhorn.io/v1beta1
Kind:         EngineImage
Metadata:
  Creation Timestamp:  2019-11-19T05:09:21Z
  Finalizers:
    longhorn.io
  Generation:        1
  Resource Version:  24826987
  Self Link:         /apis/longhorn.io/v1beta1/namespaces/longhorn-system/engineimages/ei-ec95b5ad
  UID:               1f1f4748-51ed-4d63-86ec-3905b64a2f60
Spec:
  Image:  longhornio/longhorn-engine:v0.7.0
Status:
  Build Date:                  2019-11-15T03:47:06+00:00
  Cli API Min Version:         2
  Cli API Version:             2
  Controller API Min Version:  2
  Controller API Version:      2
  Data Format Min Version:     1
  Data Format Version:         1
  Git Commit:                  0b3aa9c4e2976240a1dc5316a10c16f72b3580e9
  No Ref Since:                
  Owner ID:                    k8s-worker02
  Ref Count:                   6
  State:                       deploying
  Version:                     v0.7.0
Events:                        <none>

**Comment by yasker** [comment]
@awlleon Hi, have you figured out the reason?
