### ISSUE TITLE
[BUG] Missing `fromBackup` Parameter in API Request When Restoring Multiple Files from Backup List

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#10050]
## Describe the bug

When attempting to restore multiple files from the backup list, the create volume API request payload is missing the fromBackup parameter. Due to this issue, the restored volume size defaults to 2MB instead of the expected size based on the backup files.

Failed
![Screenshot_20241224_112751](https://github.com/user-attachments/assets/f943f08a-f634-4ca2-93e7-ab73a6c079d1)
Passed
![Screenshot_20241224_112741](https://github.com/user-attachments/assets/e39e893e-9569-492d-9856-73bd8ea108ae)

## To Reproduce

1. Navigate to the backup list.
2. Select multiple files to restore.
3. Initiate the restore process.
4. Check the created volume size.

## Expected behavior

The latest backup should be successfully restored when selected from the backup page.

## Environment

 - Longhorn version: `master-head`, `v1.8.x-head`, `v1.7.2`
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by mantissahz** [comment]
cc @a110605, @houhoucoop

**Comment by derekbit** [comment]
@roger-ryao Does v1.6.3 have the same issue?

**Comment by roger-ryao** [comment]
> @roger-ryao Does v1.6.3 have the same issue?

Yes, `v1.6.3` has the same issue.

**Comment by derekbit** [comment]
Thanks @roger-ryao.
Interesting. We haven't received any reports from users.

**Comment by a110605** [comment]
All backport merged.

**Comment by roger-ryao** [comment]
**Verified on master-head 20241226**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/7cd6412137171db36e06eeae82e97364558a877d
- longhorn-ui `master-head` https://github.com/longhorn/longhorn-ui/commit/f580a92bc884a80b58d25dd0155b9fa85985faa7


**Verified on v1.8.x-head 20241226**

- longhorn `v1.8.x-head` https://github.com/longhorn/longhorn/commit/ede8f46a75704352e33fbc45b01f14fa2770a827
- longhorn-ui `v1.8.x-head` https://github.com/longhorn/longhorn-ui/commit/628773e247d865d7bdc1770d22701271f3db37af


**The test steps**
https://github.com/longhorn/longhorn/issues/10050#issue-2757125332

**Result Passed**
