### ISSUE TITLE
[BUG] Webhook servers initialization blocks longhorn-manager from running

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#10054]
## Describe the bug

During Longhorn deployment, all `longhorn-manager` will race to update the `longhorn-system/longhorn-webhook-tls` secret simultaneously during the initialization of webhook servers.

On a cluster with a large number of worker nodes, this can cause a surge of conflicting secret updates, leading to endless retries that block the `longhorn-manager` from running.

**Symptoms:**
1. The longhorn-manager logs are flooded with error messages similar to:
    ```
    time="2024-12-20T21:24:47Z" level=error msg="Failed to save TLS secret for longhorn-system/longhorn-webhook-tls: Operation cannot be fulfilled on secrets \"longhorn-webhook-tls\": the object has been modified; please apply your changes to the latest version and try again" func="kubernetes.(*storage).Update.func1" file="controller.go:236"
    time="2024-12-20T21:24:47Z" level=error msg="Failed to save TLS secret for longhorn-system/longhorn-webhook-tls: Operation cannot be fulfilled on secrets \"longhorn-webhook-tls\": the object has been modified; please apply your changes to the latest version and try again" func="kubernetes.(*storage).Update.func1" file="controller.go:236"
    time="2024-12-20T21:24:47Z" level=error msg="Failed to save TLS secret for longhorn-system/longhorn-webhook-tls: Operation cannot be fulfilled on secrets \"longhorn-webhook-tls\": the object has been modified; please apply your changes to the latest version and try again" func="kubernetes.(*storage).Update.func1" file="controller.go:236"
    time="2024-12-20T21:24:47Z" level=error msg="Failed to save TLS secret for longhorn-system/longhorn-webhook-tls: Operation cannot be fulfilled on secrets \"longhorn-webhook-tls\": the object has been modified; please apply your changes to the latest version and try again" func="kubernetes.(*storage).Update.func1" file="controller.go:236"
    time="2024-12-20T21:24:47Z" level=error msg="Failed to save TLS secret for longhorn-system/longhorn-webhook-tls: Operation cannot be fulfilled on secrets \"longhorn-webhook-tls\": the object has been modified; please apply your changes to the latest version and try again" func="kubernetes.(*storage).Update.func1" file="controller.go:236"
    time="2024-12-20T21:24:47Z" level=error msg="Failed to save TLS secret for longhorn-system/longhorn-webhook-tls: Operation cannot be fulfilled on secrets \"longhorn-webhook-tls\": the object has been modified; please apply your changes to the latest version and try again" func="kubernetes.(*storage).Update.func1" file="controller.go:236"
    time="2024-12-20T21:24:47Z" level=info msg="Active TLS secret longhorn-system/longhorn-webhook-tls (ver=147367) (count 2): map[listener.cattle.io/cn-longhorn-admission-webhook.longhor-59584d:longhorn-admission-webhook.longhorn-system.svc listener.cattle.io/cn-longhorn-conversion-webhook.longho-6a0089:longhorn-conversion-webhook.longhorn-system.svc listener.cattle.io/fingerprint:SHA1=7106A5D92379A5EE8F621B9939CA0A6956B00B15]" func="memory.(*memory).Update" file="memory.go:42"
    time="2024-12-20T21:24:47Z" level=info msg="Updating TLS secret for longhorn-system/longhorn-webhook-tls (count: 2): map[listener.cattle.io/cn-longhorn-admission-webhook.longhor-59584d:longhorn-admission-webhook.longhorn-system.svc listener.cattle.io/cn-longhorn-conversion-webhook.longho-6a0089:longhorn-conversion-webhook.longhorn-system.svc listener.cattle.io/fingerprint:SHA1=E20D63C43B8F9D12449B936A1439B461A7FB017A]" func="kubernetes.(*storage).saveInK8s" file="controller.go:225"
    time="2024-12-20T21:24:47Z" level=info msg="Updating TLS secret for longhorn-system/longhorn-webhook-tls (count: 2): map[listener.cattle.io/cn-longhorn-admission-webhook.longhor-59584d:longhorn-admission-webhook.longhorn-system.svc listener.cattle.io/cn-longhorn-conversion-webhook.longho-6a0089:longhorn-conversion-webhook.longhorn-system.svc listener.cattle.io/fingerprint:SHA1=124F40269B453026A82679B795E894F757181C52]" func="kubernetes.(*storage).saveInK8s" file="controller.go:225"
    time="2024-12-20T21:24:47Z" level=info msg="Updating TLS secret for longhorn-system/longhorn-webhook-tls (count: 2): map[listener.cattle.io/cn-longhorn-admission-webhook.longhor-59584d:longhorn-admission-webhook.longhorn-system.svc listener.cattle.io/cn-longhorn-conversion-webhook.longho-6a0089:longhorn-conversion-webhook.longhorn-system.svc listener.cattle.io/fingerprint:SHA1=C828A05F97E2D9B2D909847D7DD8B2984491F67C]" func="kubernetes.(*storage).saveInK8s" file="controller.go:225"
    ```
1. The secret annotation `longhorn-system/longhorn-webhook-tls` flaps between couple of `listener.cattle.io/fingerprint:SHA1` values.

**Cause:**
1. storage.init(): https://github.com/rancher/dynamiclistener/blob/v0.6.1/storage/kubernetes/controller.go#L85
2. retry.OnError(): https://github.com/rancher/dynamiclistener/blob/v0.6.1/storage/kubernetes/controller.go#L248
3. s.secrets.Update(targetSecret): https://github.com/rancher/dynamiclistener/blob/v0.6.1/storage/kubernetes/controller.go#L225-L226

## To Reproduce

1. Deploy Longhorn on a cluster with 20+ worker nodes

## Expected behavior

Longhorn managers should eventually start running.

## Support bundle for troubleshooting

`None`

## Environment

 - Longhorn version: day-1 issue
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

https://github.com/longhorn/longhorn/issues/8433

**Comment by c3y1huang** [comment]
Proposed fix:
- Introduce leader election for initializing webhook servers.

**Comment by c3y1huang** [comment]
cc @derekbit for milestone planning.

**Comment by derekbit** [comment]
Let's put it in v1.9.0.

**Comment by derekbit** [comment]
BTW, do we have any workaround when hitting the issue?

**Comment by c3y1huang** [comment]
> BTW, do we have any workaround when hitting the issue?

```
kubectl delete secret -n longhorn-system longhorn-webhook-tls
kubectl rollout restart -n longhorn-system ds longhorn-manager
```

**Comment by derekbit** [comment]
> > BTW, do we have any workaround when hitting the issue?
> 
> ```
> kubectl delete secret -n longhorn-system longhorn-webhook-tls
> kubectl rollout restart -n longhorn-system ds longhorn-manager
> ```

Thanks @c3y1huang. Added labels `backport/v1.6.5` and `backport/v1.7.3`

**Comment by c3y1huang** [comment]
> > > BTW, do we have any workaround when hitting the issue?
> > 
> > 
> > ```
> > kubectl delete secret -n longhorn-system longhorn-webhook-tls
> > kubectl rollout restart -n longhorn-system ds longhorn-manager
> > ```
> 
> Thanks @c3y1huang. Added labels `backport/v1.6.5` and `backport/v1.7.3`

Depends on the size of the cluster. this might not always work. The user may need to allow the manager to start in a smaller batch.

**Comment by derekbit** [comment]
> > > > BTW, do we have any workaround when hitting the issue?
> > > 
> > > 
> > > ```
> > > kubectl delete secret -n longhorn-system longhorn-webhook-tls
> > > kubectl rollout restart -n longhorn-system ds longhorn-manager
> > > ```
> > 
> > 
> > Thanks @c3y1huang. Added labels `backport/v1.6.5` and `backport/v1.7.3`
> 
> Depends on the size of the cluster. this might not always work. The user may need to allow the manager to start in a smaller batch by condoning the nodes.

What is it releated to the cluster size?

**Comment by c3y1huang** [comment]
> Why is it releated to the cluster size?

The likelihood of encountering conflict error retries increases with the number of worker nodes for the daemonset pod in the cluster, as the manager pods are created simultaneously and updates are triggered in close proximity. Smaller clusters with fewer nodes are likely to get away with it.

**Comment by derekbit** [comment]
This is not a big change, so let's add it in v1.6.4. Then, we will have 1.6.4-rc2 next week.

**Comment by derekbit** [comment]
> This is not a big change, so let's add it in v1.6.4. Then, we will have 1.6.4-rc2 next week.

cc @innobead

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-manager/commit/b4418eb96b79f1705142cd56438a59c3bf1947b6), v1.8.x(https://github.com/longhorn/longhorn-manager/commit/5a95320e3b86e0818fab2a25d6eb2f2a9948db3a)

This issue can be reproduced at `v1.7.2` on a 20 nodes cluster, but not seen in `master` and `v1.8.x`

There are many `Failed to save TLS` appeared in longhorn-manager pod during deploy `v1.7.2`
![image](https://github.com/user-attachments/assets/df00c933-e316-48da-b968-45158e667478)
And many nodes not ready afret **5** minutes
![Screenshot from 2024-12-26 11-44-34](https://github.com/user-attachments/assets/bddb2603-6737-4422-8d8e-946ce2f6fe9f)
