### ISSUE TITLE
[BUG] Data Not Retained After Restoring System Backup

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#10058]
## Describe the bug

While testing https://github.com/longhorn/longhorn/issues/5411 regarding "[Create and Restore a System Backup,](https://github.com/longhorn/longhorn/pull/6630/files#diff-f66bf27d07bfda116e6936671071bf1ef0ce469653a32bdb0c1c3571f8a6c1b5R393-R401)" I observed that `volume A` and `volume B` do not retain the data written in `step 3` after restoring the system backup. Although the volumes have backups available, the system restore does not apply those backups.

## To Reproduce

1. Set up the `default` backup target and an extra backup target `nfs-ec2`.
2. Create `vol-a` using the `default backup target` and `vol-b` using the extra backup target name `nfs-ec2`.
3. Write 10MB of data to both `vol-a` and `vol-b`.
4. Create a system backup, which succeeds.
5. Delete backup target `nfs-ec2`.
6. Restore the system backup, which also succeeds.
7. Check the contents of volume A and volume B.

## Expected behavior

The restored volumes (A and B) should include the 10MB of data written in step 3, and backup target A should be restored. The system restore should apply the existing backups of the volumes.

## Support bundle for troubleshooting

[33.zip](https://github.com/user-attachments/files/18237802/33.zip)

## Environment

 - Longhorn version: `v1.8.x-head`
 - Impacted volume (PV): `vol-a``vol-0` `vol-b``vol-1`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
@roger-ryao Is the issue observed in v1.7.2 as well?

**Comment by roger-ryao** [comment]
> @roger-ryao Is the issue observed in v1.7.2 as well?
Hi @derekbit 
      v1.7.2 didn't have this issue

**Comment by mantissahz** [comment]
It may be as mentioned in https://github.com/longhorn/longhorn/issues/10057

@roger-ryao can you try to create the system backup after the field `lastBackup` of the volume is updated, then do the restoration to check if the data is correct?

**Comment by roger-ryao** [comment]
**Verified on master-head 20241227**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/4a0b65e8aa8902e30d9df9cff44054954f14c536
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/b4418eb96b79f1705142cd56438a59c3bf1947b6


**Verified on v1.8.x-head 20241227**

- longhorn `v1.8.x-head` https://github.com/longhorn/longhorn/commit/ede8f46a75704352e33fbc45b01f14fa2770a827
- longhorn-manager `v1.8.x-head` https://github.com/longhorn/longhorn-manager/commit/5a95320e3b86e0818fab2a25d6eb2f2a9948db3a

**The test steps**
https://github.com/longhorn/longhorn/issues/10058#issue-2757437662

**Result Passed**
