### ISSUE TITLE
[BUG] Error notification appears on the volume backup details page

### ISSUE THREAD

**Issue by houhoucoop** [longhorn/longhorn#10069]
## Describe the bug

When navigating to the details page of a volume backup named `v1`, a 404 error notification may appear unexpectedly.

https://github.com/user-attachments/assets/82d34006-93de-4b43-aeaa-0894e35f6a8e

## To Reproduce

- Create a volume named `v1` and back it up
- Navigate to the details page of the `v1` volume and observe the 404 error notifications appear

## Expected behavior

No error notification popups

## Environment

 - Longhorn version:  v1.7.x, v1.6.x

**Comment by derekbit** [comment]
Good finding!

**Comment by a110605** [comment]
Tested with Longhorn v1.6.3, there is no error notification in backup detail page. See below recording.

![image](https://github.com/user-attachments/assets/0b02d504-9114-46ee-ac6f-ba6acecce468)

@houhoucoop , from your recording seems you're using master-head longhorn-ui with which backend version?

**Comment by chriscchien** [comment]
Verified **pass** on longhorn v1.6.x (https://github.com/longhorn/longhorn-ui/commit/29f16e93e4ed042cc64b7cea57beaae1b881d2fd) with test [steps](https://github.com/longhorn/longhorn/issues/10069#issue-2758425386)
