### ISSUE TITLE
DR: Don't reject the activate command if the restoration is in progress

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1006]
We should wait for the restoration to complete automatically.

Volume might need a state to indicate it's restoring.

**Comment by shuo-wu** [comment]
Test step:
1. Launch a pod with a Longhorn volume, write data1 (e.g., 5Gi random data) into the volume then create backup1.
2. Write data2 (e.g., 2Gi data) into the volume.
3. Launch a DR volume (which will restore the backup1).
4. Create backup2 for data2 and make sure the creation of backup2 is faster than the DR volume restoration.
5. Activate the DR volume which is restoring the backup1. --> The `LastBackup` field should be updated to backup2.
6. Write data3(5Mi) and create backup3.
7. Click `Backup` column on Longhorn UI (to trigger `LastBackup` update) then see if the activating DR volume will update `LastBackup` field --> It shouldn't be updated.
8. Wait for restoration and activation complete then check the data in the activated volume. --> It should contain data1 and data2.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
