### ISSUE TITLE
[BUG] Volumes stuck in degraded state for a long time due to rebuild failures

### ISSUE THREAD

**Issue by Joker9944** [longhorn/longhorn#10078]
## Describe the bug

Larger PVCs (>5 Gi actual size) are stuck for a long time in degraded state. Rebuilding is attempted over and over again followed with the following error message. Eventually a rebuild will have a good run and complete. But in practice I have observed volumes of around 15 Gi rebuilding over 24 hours.

```
(combined from similar events): Failed rebuilding replica with Address 10.244.1.47:17989: proxyServer=10.244.3.231:8501 destination=10.244.3.231:10116: failed to add replica tcp://10.244.1.47:17989 for volume: rpc error: code = Unavailable desc = failed to sync files [{FromFileName:volume-snap-0e3f9dcb-ab03-47bd-a4ba-655e8343f00b.img ToFileName:volume-snap-0e3f9dcb-ab03-47bd-a4ba-655e8343f00b.img ActualSize:17845121024} {FromFileName:volume-snap-0e3f9dcb-ab03-47bd-a4ba-655e8343f00b.img.meta ToFileName:volume-snap-0e3f9dcb-ab03-47bd-a4ba-655e8343f00b.img.meta ActualSize:0} {FromFileName:volume-snap-d609c56f-9040-44f9-b65e-5e288f33345f.img ToFileName:volume-snap-d609c56f-9040-44f9-b65e-5e288f33345f.img ActualSize:45023232} {FromFileName:volume-snap-d609c56f-9040-44f9-b65e-5e288f33345f.img.meta ToFileName:volume-snap-d609c56f-9040-44f9-b65e-5e288f33345f.img.meta ActualSize:0}] from tcp://10.244.3.231:10106: rpc error: code = Unavailable desc = replica tcp://10.244.3.231:10106 failed to send file volume-snap-0e3f9dcb-ab03-47bd-a4ba-655e8343f00b.img to 10.244.1.47:17993: failed to send file volume-snap-0e3f9dcb-ab03-47bd-a4ba-655e8343f00b.img to 10.244.1.47:17993: rpc error: code = Unavailable desc = error reading from server: read tcp 10.244.1.47:48556->10.244.3.231:10108: read: connection reset by peer
```

The issue arises with all rebuilds but smaller volumes are less prone to failing since the issue comes up randomly so they have less chance to eventually fail.

## To Reproduce

- Create a reasonably sized volume
- Let the volume get degraded

## Expected behavior

- Clean rebuild

## Support bundle for troubleshooting

[supportbundle_08f979cf-c831-49cb-9603-2669f5d75d02_2024-12-26T14-07-51Z.zip](https://github.com/user-attachments/files/18253375/supportbundle_08f979cf-c831-49cb-9603-2669f5d75d02_2024-12-26T14-07-51Z.zip)

## Environment

 - Longhorn version: 
 - Impacted volume (PV):
   - pvc-21972ea3-6240-4d87-8841-e01520d76f26
   - pvc-8c04c698-0ca5-4864-a3bb-579109cf1477
   - pvc-d954c1df-8095-4139-b5d9-a7714c35f5b5
   - pvc-d988d350-d6fb-4170-9431-2dca10cf6797
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
   - https://github.com/Joker9944/k8s-config/tree/543bed9d5637291a9708f5a0e549e4258b734a75/infrastructure/longhorn-system
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Talos Linux v1.31.2
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 4 (control planes have scheduling enabled)
 - Node config
   - OS type and version: Talos Linux v1.8.2
   - Kernel version:
   - CPU per node: 6 cores
   - Memory per node: 3 x 32 Gi, 1x 16 Gi
   - Disk type (e.g. SSD/NVMe/HDD): 3 x NVMe, 1x HDD
   - Network bandwidth between the nodes (Gbps): 1
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

I suspect a network issue but my metrics show normal network usage and no packet loss. But I have a bandwith of only 1 Gbps. 

What I have tried so far:
- Reducing concurrent rebuilds per node to 1
- Put all timeouts to max

What I have not tried so far:
- Setup a dedicated storage network
- Upgrade to 2.5 Gbps
- Replace hardware

## Workaround and Mitigation

The problem will usually resolve itself after a few days when all rebuilds had a lucky break.

**Comment by derekbit** [comment]
This is more related to your network issue.

**Comment by Joker9944** [comment]
Thank you for the quick reply. I will investigate into that direction and close the ticket with some more info once I found the issue.

**Comment by Joker9944** [comment]
Okay I found the issue. After inspecting my hardware a bit closer I noticed that on my switch on some ports less lights were blinking. Turns out that some of my nodes were connected with 100 mbps instead of 1 gbps. The solution was to install the proper drivers on the affected nodes.

Now everything is running fine.

Sorry for taking up some of your time.
