### ISSUE TITLE
[TEST] Can not run v1.6.x 2 stage upgrade on private pipeline

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#10076]
## What's the test to develop? Please describe

Using private pipeline to run 2 stage upgrade with `longhornio/longhorn-manager-test:v1.6.x-head` the upgrade will fail due to the backport PR https://github.com/longhorn/longhorn-tests/pull/2098 conflict but closed directly

![image](https://github.com/user-attachments/assets/4d143fd7-9ab2-47e0-9956-6771f506af3e)

cc @yangchiu 

## Describe the tasks for the test

N/A

## Additional context

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7992/consoleFull

**Comment by derekbit** [comment]
@chriscchien 
Do we have any workaround or solution?

cc @innobead

**Comment by chriscchien** [comment]
I am trying to slove the conflict then test to see the result.

**Comment by chriscchien** [comment]
Close this ticket as `v1.6.x` 2 stage upgrade worked on private pipeline([amd64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8026/), [arm64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8027/)) and v1.6.x public upgrade pipeline worked well too([amd64](https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-upgrade-tests-sles-amd64/263) [arm64](https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-upgrade-tests-sles-arm64/275)) after https://github.com/longhorn/longhorn-tests/pull/2098 merged
