### ISSUE TITLE
[BUG] Test Case `test_setting` Randomly Fails

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#10077]
## Describe the bug

The test case `test_setting`  randomly fails with the following error:

```console
longhorn.ApiError: (ApiError(...), '500 : Operation cannot be fulfilled on settings.longhorn.io "backup-target-credential-secret": the object has been modified; please apply your changes to the latest version and try again\n{\'code\': 500, \'detail\': \'\', \'message\': \'Operation cannot be fulfilled on settings.longhorn.io "backup-target-credential-secret": the object has been modified; please apply your changes to the latest version and try again\', \'status\': 500}')

```

## To Reproduce

Rerun test case `test_setting` https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8025/

## Support bundle for troubleshooting

[longhorn-tests-regression-8025-bundle.zip](https://github.com/user-attachments/files/18252041/longhorn-tests-regression-8025-bundle.zip)

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
@mantissahz Can you help check it?

**Comment by derekbit** [comment]
@mantissahz 
We will remove the settings, so it might not be an issue.
You can check this ticket after finishing the removal of the backup target settings.

**Comment by mantissahz** [comment]
After removing the setting, https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8036/

**Comment by mantissahz** [comment]
Hi @roger-ryao,

Please review this ticket to check if it's still valid because we have removed the settings that failed the test case.

**Comment by roger-ryao** [comment]
**Verified on master-head 20241230**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/7da75642805760929883ff2100ee42c58f117d4c
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/1875421555b48dd71782afe8e70f45bcaf6441a2


**Verified on v1.8.0-rc2 20241230**

- longhorn `v1.8.0-rc2` https://github.com/longhorn/longhorn/commit/45d4e8029f686a0a5ffc8a1a68c42361b528dcae
- longhorn-manager `v1.8.0-rc2` https://github.com/longhorn/longhorn-manager/commit/37ad98fb5d33e8a907c4e1770933e95a862ab6d9


**The test steps**
https://github.com/longhorn/longhorn/issues/10077#issue-2759598389


**Result Passed**

- [x] master-head : https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8080/
- [x] v1.8.x-head : https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8081/
