### ISSUE TITLE
UI - Backup/Snapshot as a drop down menu option in scheduling

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#1008]
We believe backup schedules are used more than a snapshot schedule in our case. 

Clicking `+ New` might be helpful to show a drop down menu, to select either a `Backup` or `Snapshot` schedule. 

(Saves from having to move the mouse all the way to the other side of the screen)

![image](https://user-images.githubusercontent.com/28725423/72078798-c1d40600-32c7-11ea-9bfa-becd501175b1.png)

**Comment by yasker** [comment]
We can just make `Backup` as the default option instead. Updating `+ New` is not going to make big differences since the user need to update the schedule anyway.

@smallteeths Can we change the job type dropdown to use `Backup` as the default instead of `Snapshot`?

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI version: `wangsiye/longhorn-ui:81d49f5`

Steps to test:
  - Create a volume, attach it to a node.
  - In Volume Details page, in `Recurring Snapshot and Backup Schedule` section, click ` + New`
  - Backup should be the default option in drop down menu for creating a schedule. **(PASS)**
