### ISSUE TITLE
[FEATURE] Support Data Engine Option For Backing Image in CSI flow

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#10084]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

StorageClass should support Data Engine Option for Backing Image

## Describe the solution you'd like
BackingImage in the storageclass should follow the same data engine as volume
I propose that we don't need another option for backing image data engine but reuse the volume data engine.

## Describe alternatives you've considered
.

## Additional context
cc @derekbit @WebberHuang1118

**Comment by roger-ryao** [comment]
**Verified on master-head 20241231**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/7da75642805760929883ff2100ee42c58f117d4c
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/1875421555b48dd71782afe8e70f45bcaf6441a2


**Verified on v1.8.0-rc2 20241231**

- longhorn `v1.8.0-rc2` https://github.com/longhorn/longhorn/commit/45d4e8029f686a0a5ffc8a1a68c42361b528dcae
- longhorn-manager `v1.8.0-rc2` https://github.com/longhorn/longhorn-manager/commit/37ad98fb5d33e8a907c4e1770933e95a862ab6d9

**The test steps**
https://github.com/longhorn/longhorn/issues/10084#issuecomment-2563475774

**Result Passed**
