### ISSUE TITLE
[BUG][v1.6.x-head] Share manager pod kept restarting

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#10096]
## Describe the bug

`test_rwx.py` test case all failed in `v1.6.x-head`, the share manager pod kept restarting, this issue did not observe on `v1.6.4-rc1`
[](https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-tests-sles-amd64/331/#showFailuresLink)

![image](https://github.com/user-attachments/assets/660859ad-22c8-453d-9e28-21999c156912)

```
time="2024-12-30T02:03:40Z" level=error msg="NFS server exited with error" encrypted=false error="ganesha.nfsd failed with error: exit status 127, output: ganesha.nfsd: error while loading shared libraries: libjson-c.so.5: cannot open shared object file: No such file or directory\n" volume=pvc-c053d285-daff-42d3-a3ea-cbe46d3a8774
time="2024-12-30T02:03:40Z" level=debug msg="Device /dev/mapper/pvc-c053d285-daff-42d3-a3ea-cbe46d3a8774 is not an active LUKS device" func=crypto.DeviceEncryptionStatus file="crypto.go:89" error="failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/28142/ns/mnt --ipc=/host/proc/28142/ns/ipc cryptsetup status pvc-c053d285-daff-42d3-a3ea-cbe46d3a8774], output , stderr nsenter: failed to execute cryptsetup: No such file or directory\n: exit status 127"
```

## To Reproduce

1. Install v1.6.x-head
2. Dynamic provision a RWX volume.
3. The share manager pod kept restarting

## Expected behavior

RWX volume worked well

## Support bundle for troubleshooting

[supportbundle_b9dc1b4d-934d-48f9-802c-61b4ee2f0029_2024-12-30T02-05-40Z.zip](https://github.com/user-attachments/files/18271556/supportbundle_b9dc1b4d-934d-48f9-802c-61b4ee2f0029_2024-12-30T02-05-40Z.zip)

## Environment

 - Longhorn version: v1.6.x-head

## Additional context

N/A

## Workaround and Mitigation

N/A

**Comment by innobead** [comment]
> time="2024-12-30T02:03:40Z" level=error msg="NFS server exited with error" encrypted=false error="ganesha.nfsd failed with error: exit status 127, output: ganesha.nfsd: error while loading shared libraries: libjson-c.so.5: cannot open shared object file: No such file or directory\n" volume=pvc-c053d285-daff-42d3-a3ea-cbe46d3a8774

a host package issue in the share manager pod? @c3y1huang please take a look.

**Comment by c3y1huang** [comment]
**Cause**
Missing dependency and it's a regression introduced by https://github.com/longhorn/longhorn-share-manager/pull/417.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn v1.6.x(https://github.com/longhorn/longhorn-share-manager/commit/b272523abe4071da705145177e21829556f9a649)

`test_rwx.py` passed on below scenario:
- [amd64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8084/testReport/tests/test_rwx/)
- [arm64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8086/)
- [arm64 2 stage upgrade](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8087/), (`v1.5.5` to `v1.6.3` to `v1.6.x`)
