### ISSUE TITLE
[BUG][v1.6.1] Multiple CSI Components Restarted Due to Lost Connection to CSI Driver led to pod restart unexpectedly

### ISSUE THREAD

**Issue by abdulrahman1alabdullah** [longhorn/longhorn#10092]
## Describe the bug

Several CSI-related components (longhorn-csi-plugin, csi-resizer, csi-attacher) are restarting unexpectedly. The restarts are triggered by connection issues with the CSI driver, **led to pod restart unexpectedly**

1. csi-attacher Logs
I1219 22:30:21.542997       1 main.go:97] Version: v4.4.2
I1219 22:30:21.548994       1 common.go:138] Probing CSI driver for readiness
I1219 22:30:21.551339       1 main.go:154] CSI driver name: "driver.longhorn.io"
I1219 22:30:21.555464       1 main.go:230] CSI driver supports ControllerPublishUnpublish, using real CSI handler
I1219 22:30:21.556024       1 leaderelection.go:250] attempting to acquire leader lease longhorn-system/external-attacher-leader-driver-longhorn-io...
I1219 22:30:21.570329       1 leaderelection.go:260] successfully acquired lease longhorn-system/external-attacher-leader-driver-longhorn-io
I1219 22:30:21.570509       1 leader_election.go:178] became leader, starting
I1219 22:30:21.570537       1 controller.go:130] Starting CSI attacher
I1219 22:30:23.800773       1 csi_handler.go:581] Detached "csi-b89d4500db8655ee1..."
I1219 22:30:25.829724       1 csi_handler.go:289] Failed to save detach error to "csi-b89d4500db8655ee1...": volumeattachments.storage.k8s.io "csi-b89d4500..." not found
I1227 08:10:27.510706       1 csi_handler.go:282] Detaching "csi-b89d4500..."
E1227 08:10:27.521420       1 connection.go:142] Lost connection to unix:///csi/csi.sock.
F1227 08:10:27.521599       1 connection.go:97] Lost connection to CSI driver, exiting

 csi-resizer Logs
I1227 08:08:59.066550       1 main.go:93] Version : v1.9.2
I1227 08:08:59.066601       1 feature_gate.go:249] feature gates: &{map[]}
I1227 08:08:59.072314       1 common.go:138] Probing CSI driver for readiness
I1227 08:08:59.075283       1 main.go:141] CSI driver name: "driver.longhorn.io"
I1227 08:08:59.077416       1 leaderelection.go:250] attempting to acquire leader lease longhorn-system/external-resizer-driver-longhorn-io...
E1227 08:09:29.084689       1 leaderelection.go:332] error retrieving resource lock longhorn-system/external-resizer-driver-longhorn-io: Get "https://10.233.0.1:443/apis/coordination.k8s.io/v1/namespaces/longhorn-system/leases/external-resizer-driver-longhorn-io": dial tcp 10.233.0.1:443: i/o timeout
I1227 08:09:49.618996       1 leaderelection.go:260] successfully acquired lease longhorn-system/external-resizer-driver-longhorn-io
I1227 08:09:49.619227       1 leader_election.go:178] became leader, starting
I1227 08:09:49.619301       1 controller.go:255] Starting external resizer driver.longhorn.io
E1227 08:16:35.391712       1 leaderelection.go:332] error retrieving resource lock longhorn-system/external-resizer-driver-longhorn-io: Get "https://10.233.0.1:443/apis/coordination.k8s.io/v1/namespaces/longhorn-system/leases/external-resizer-driver-longhorn-io": context deadline exceeded
I1227 08:16:35.391751       1 leaderelection.go:285] failed to renew lease longhorn-system/external-resizer-driver-longhorn-io: timed out waiting for the condition
F1227 08:16:35.391784       1 leader_election.go:182] stopped leading

3. longhorn-csi-plugin Logs
Defaulted container "node-driver-registrar" out of: node-driver-registrar, longhorn-liveness-probe, longhorn-csi-plugin
I1205 03:07:16.119219   41115 main.go:135] Version: v2.9.2
I1205 03:07:16.119269   41115 main.go:136] Running node-driver-registrar in mode=
I1205 03:07:16.119276   41115 main.go:157] Attempting to open a gRPC connection with: "/csi/csi.sock"
W1205 03:07:26.120229   41115 connection.go:232] Still connecting to unix:///csi/csi.sock
W1205 03:07:36.120088   41115 connection.go:232] Still connecting to unix:///csi/csi.sock
W1205 03:07:46.119584   41115 connection.go:232] Still connecting to unix:///csi/csi.sock
E1205 03:07:46.119648   41115 main.go:160] error connecting to CSI driver: context deadline exceeded

## To Reproduce

without any manual intervention or configuration changes, the pod keep restarting , after a few seconds, it resumes normal operation.

## Expected behavior

All CSI components should maintain stable connections to the CSI driver without restarts, ensuring continuous operation of workloads.

## Environment

Longhorn version:
Impacted volume (PV):
Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: bearmetal k8s
Number of control plane nodes in the cluster: 1
Number of worker nodes in the cluster: 2
Node config
OS type and version: ubuntu 22.04
Kernel version: Linux node1 5.4.0-174-generic https://github.com/longhorn/longhorn/issues/193-Ubuntu SMP Thu Mar 7 14:29:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
CPU per node: 48
Memory per node:
Disk type (e.g. SSD/NVMe/HDD): SSD
Network bandwidth between the nodes (Gbps):
Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
Number of Longhorn volumes in the cluster: 64

**Comment by abdulrahman1alabdullah** [comment]
The support bundle here:

https://drive.google.com/file/d/1zxjiqCWxS-8aAiy-MPFPPhsqsr3dxEn2/view?usp=sharing

**Comment by aljabertareq** [comment]
@derekbit we have encountered the same issue twice - same crash. Is this an issue with the current Longhorn version? Please note that this happened on an SSD machine. cc: @abdulrahman1alabdullah @

**Comment by derekbit** [comment]
@ChanYiLin Can you help check this issue?

**Comment by derekbit** [comment]
cc @PhanLe1010

**Comment by derekbit** [comment]
@abdulrahman1alabdullah @aljabertareq 

It is a known issue. Please check https://github.com/longhorn/longhorn/issues/8427#issuecomment-2083759839.
Could you upgrade to v1.6.3?

**Comment by abdulrahman1alabdullah** [comment]
@derekbit  Thank you
Is the version v1.6.3 stable? what is the last stable version? is there anything we should consider while upgrading from 1..6.1 to any version ?

**Comment by derekbit** [comment]
1.6.3 is stable, but we are testing v1.6.4-rc2 and will release v1.6.4 that fixes some regression and known issues soon.  You can wait for a while.

取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________
寄件者: abdulrahman1alabdullah ***@***.***>
寄件日期: Tuesday, December 31, 2024 12:50:39 PM
收件者: longhorn/longhorn ***@***.***>
副本: Derek Su ***@***.***>; Mention ***@***.***>
主旨: Re: [longhorn/longhorn] [BUG][v1.6.1] Multiple CSI Components Restarted Due to Lost Connection to CSI Driver led to pod restart unexpectedly (Issue #10092)


@derekbit<https://github.com/derekbit> Thank you
Is the version v1.6.3 stable? what is the last stable version? is there anything we should consider while upgrading from 1..6.1 to any version ?
