### ISSUE TITLE
error: Too many snapshots created! UI not show snapshots.

### ISSUE THREAD

**Issue by Jawenba** [longhorn/longhorn#1010]
hello !  I created backup schedules in longhorn v0.6.2 , retain was  too big.now the schedule log is  " rpc error: code = Unknown desc = Too many snapshots created"  。on the manager UI, I can't delete the snapshots, now how can i delete the more snapshots to make the schedules work? thanks very much!
![image](https://user-images.githubusercontent.com/47962033/72134560-6422e500-33bf-11ea-953a-615c6587a14a.png)

**Comment by yasker** [comment]
@Jawenba 

You can find a script called `lhexec` in https://github.com/longhorn/longhorn/tree/master/scripts . It can be used to remedy the situation:

1. Find the volume name <volume-name>
2. Run `lhexec <volume-name> info`, make sure you can connect to the engine directly.
3. Run `lhexec <volume-name> snapshot ls`, to get the list of snapshots.
4. Delete a few of them using `lhexec <volume-name> snapshot rm <snapshot-name>`
5. Run `lhexec <volume-name> snapshot purge` to complete the deletion.
6. Now you should be able to see it in the UI and edit the backup schedule.

Let me know if you have any questions while executing the steps above.

**Comment by Jawenba** [comment]
@yasker thank you for your help! now,I remove  a few of snapshots remaining 23,less than 100. 
![image](https://user-images.githubusercontent.com/47962033/72307851-b3fef600-36b6-11ea-84ad-d196fb9147ea.png)
but the UI is not  well yet .when I take a  snapshot。I check it is work. 
![image](https://user-images.githubusercontent.com/47962033/72308561-b1e96700-36b7-11ea-8b02-f03921ab6421.png)
So ,how can i do ?

**Comment by yasker** [comment]
@Jawenba This sounds like a UI bug. UI gets the same information from the call you just made. Probably wait for a while and it will eventually show up. If not, can you start the web developer console to see if there is any errors?

**Comment by Jawenba** [comment]
yes,the web has errors :
![image](https://user-images.githubusercontent.com/47962033/72310543-f9bebd00-36bc-11ea-893d-5f8d827a007d.png)

**Comment by yasker** [comment]
@smallteeths can you check this issue? Looks like the UI failed to parse the snapshot tree somehow.

**Comment by Jawenba** [comment]
@smallteeths Now, this problem causes the volume to be unable to be backed up . Could you spare some of your precious time to help with the problem? Thank you very much!

**Comment by yasker** [comment]
@Jawenba I think the backup might still work despite UI cannot show it. If you click Backup button and click OK, would you able to see the new backup show up in the backup store after a while?

**Comment by Jawenba** [comment]
@yasker yes,I delete the old backup files of s3,then the backup is ok.thank you for your helps!

**Comment by yasker** [comment]
Fixed by https://github.com/longhorn/longhorn-ui/pull/236

**Comment by voarsh2** [comment]
I did this:
./lhexec pvc-ac60cf35-539a-4af2-87d3-54f21d20d54b snapshot rm $(./lhexec pvc-ac60cf35-539a-4af2-87d3-54f21d20d54b snapshot ls)

./lhexec pvc-ac60cf35-539a-4af2-87d3-54f21d20d54b snapshot purge

This however, didn't give me the result I expected, the snapshots remained.
