### ISSUE TITLE
Using NFS backup target with sec=krb5p and custom authentication

### ISSUE THREAD

**Issue by liogate** [longhorn/longhorn#1012]
Hi community :)

I'm trying to configure NFS target dir with specific configuration: `sec=krb5p` and authentication, but I didn't found any documentation on how to do that. Maybe a UI enhancement is needed ?

I'm using longhorn 7.0.

Thank you for your help !

**Comment by yasker** [comment]
@liogate I am afraid we don't support NFS authentication at the moment. I would recommend using S3 service over https instead, or MinIO.

**Comment by liogate** [comment]
Thank you ! I'll try MinIO :)
