### ISSUE TITLE
UI - Replica name links to Volume

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#1015]
Clicking a replica name should take you to the Volume it is a part of

![image](https://user-images.githubusercontent.com/28725423/72266141-c6602d80-35eb-11ea-9477-0b9a36a54e20.png)

**Comment by yasker** [comment]
@ainiml I am curious what's the usage case here? Some troubleshooting?

**Comment by ainiml** [comment]
> @ainiml I am curious what's the usage case here? Some troubleshooting?

I'm testing out s3backer as the longhorn backend for XFS, and the volumes are failing

I have to delete all the replicas from the path, before I can remove it (different from removing a node from Longhorn)

S3backer issue I'm troubleshooting: https://github.com/archiecobbs/s3backer/issues/122

**Comment by yasker** [comment]
@ainiml OK. Yeah, we can make clicking the name of the replica jumping to the related volume. That should make it easier.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI version: `wangsiye/longhorn-ui:81d49f5`

Steps to test:
  - Create multiple volumes, attach them to nodes
  - In Node page, on `Replicas` column, click on the number of replicas on a node, click on a replicas scheduled to that node.
  - Clicking on replica link should redirect to Volume Details page for related volume. **(PASS)**

**Comment by yasker** [comment]
Done
