### ISSUE TITLE
manager: Don't allow large number of retaining set for backup schedule

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1016]
The total number of snapshot/backup schedule's retain number shouldn't exceed 50, otherwise it can cause issues like #1010.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
- Create a volume, attach it to a node
- Create recurring snapshot/backup jobs where total number of retain jobs for all snapshots/backups **greater than 50**, won't to create recurring jobs (**PASSED**)

- Create recurring snapshot/backup jobs where total number of retain jobs for all snapshots/backups **less than or equal to  50**,  recurring jobs created successfully (**PASSED**)
