### ISSUE TITLE
UI - Clicking row selects it

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#1022]
Similar to how Rancher, you can select a row without strictly marking a check box 

And you can CTRL+Click, or SHIFT+Click for multi-selection

![image](https://user-images.githubusercontent.com/28725423/72689629-e8a2ff80-3b45-11ea-971f-43e6dc673abc.png)

**Comment by yasker** [comment]
Yeah, that makes sense.

**Comment by meldafrawi** [comment]
Validation: **Partially Failed**

Longhorn UI version: `wangsiye/longhorn-ui:0a30f0e`

Steps to test:
  - On Volume page, create multiple volumes
  - Click on a row, volume should be selected **(PASS)**
  - Hold CTRL  key and click on another volume, it should be selected with already selected volume. **(PASS)**
  - While holding CTRL key, click again on one of already selected volumes, it should be unselected **(FAILED)**

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn ui version: `wangsiye/longhorn-ui:39737a6`

**Comment by yasker** [comment]
Done
