### ISSUE TITLE
UI - Volumes without PV/PVC

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#1023]
It's uncertain which Volumes already have a PC/PVC, or doesn't have one

![image](https://user-images.githubusercontent.com/28725423/72689697-bcd44980-3b46-11ea-9829-cd2054a7b47c.png)

**Comment by yasker** [comment]
There is a `PV/PVC` column. Or you meant something else?

**Comment by ainiml** [comment]
> There is a `PV/PVC` column. Or you meant something else?

For example, in the main Dashboard, you could click on a different color which pertains to attached volumes without a PC/PVC

Since, after creating a volume manually, the next steps is Attaching, and then creating a PV/PVC

You can easily find the detached Volumes, because they're grey, but then you're doing a scavenger hunt for the volume to create a PC/PVC for.

**Comment by yasker** [comment]
@ainiml The volume page PV/PVC filter should be addressed by #937 . We should able to use the filter to find unbound volume in UI. @meldafrawi Can you check the latest UI to make sure it works?

PV/PVC can be created without attaching the volume though. The volume attaching will happen automatically when a pod start using the PV/PVC.

**Comment by ainiml** [comment]
> PV/PVC can be created without attaching the volume though. The volume attaching will happen automatically when a pod start using the PV/PVC.

We might have another idea

In the Volumes page, you could click `Bound` and it would be a shortcut to filter all volumes that are bound

And if there was an `Unbound` value, it could do the same, and filter out for all unbound volumes 

So the UI can be used more intuitively, without having to look through drop down menus

**Comment by yasker** [comment]
@ainiml This "click bound" behavior is inconsistent with other filters, which are located on the top right corner, so I am afraid it's not intuitive.

**Comment by meldafrawi** [comment]
Validation: `Partially Failed`

Longhorn ui version: `wangsiye/longhorn-ui:39737a6`

Steps to test:
- Create 4 volume `volume-1` `volume-2` `volume-3` `volume-4`
- leave `volume-1`without PV/PVC
- Create PV only for `volume-2`
- Create PV/PVC for `volume-3`
- Create PV/PVC for `volume-4`, then delete PVC using `kubectl delete pvc <PVC_NAME>`
- Filer volumes with `PV Status -> [None, Available, Bound, Released]`  (FAILED)
> I should be able to filer volumes `PV Status -> Released`
- Filter volumes using any filter, then Clear the filter using little `X mark`,
- Clearing the filter should reset the filer, all volumes should be visible **(FAILED)**
![image](https://user-images.githubusercontent.com/18232258/72935512-284c3000-3d6e-11ea-8ea0-ddb790eb26d2.png)

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI version: `wangsiye/longhorn-ui:4eb7843`
