### ISSUE TITLE
Sensitivity to faulting

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#1025]
The instance is running on Dremahost with a Volume direct-mounted to it.

Even the volumes mounted locally to `/var/lib/rancher/longhorn/` have faulted.

I have a suspicion the S3 volumes faulted, and caused all the other ones to fault as well. Need to do some more research.

![image](https://user-images.githubusercontent.com/28725423/72765896-4d7f5800-3c21-11ea-891a-ebc041188172.png)

**Comment by yasker** [comment]
Volume fault is normally caused by network issues, result in the engine failed to connect to the replicas.

**Comment by ainiml** [comment]
> Volume fault is normally caused by network issues, result in the engine failed to connect to the replicas.

This might also concern AWS EC2 instances, if their volumes are also over their network?
