### ISSUE TITLE
Custom sci driver registrar image issue

### ISSUE THREAD

**Issue by DariaVasilenko** [longhorn/longhorn#1026]
I tried to install longhorn on airgapped k8s cluster and I had to specify images from local registry in values.yaml. Everything worked well except sci driver registrar  - it was trying to pull default image instead of local. 

I fixed it by replacing CSI_DRIVER_REGISTRAR_IMAGE with CSI_NODE_DRIVER_REGISTRAR_IMAGE in deployment-driver.yaml

**Comment by yasker** [comment]
@DariaVasilenko Yeah that's those parameters designed for. We're tracking the effort of air gap installation using https://github.com/longhorn/longhorn/issues/812

**Comment by yasker** [comment]
Duplicate with #812
