### ISSUE TITLE
UI: Show when filter is applied

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#1028]
Currently user has no explicit indicator on the page to know if filter is applied.
In `Volume` & `Backup` pages, we need to show the user and indicator in case a filter is applied.

> **No filter applied, all volumes exist.**
![image](https://user-images.githubusercontent.com/18232258/72947629-4ffdc100-3d8b-11ea-90ba-01e500963771.png)

> **Name filter applied, only `v1` exist**
![image](https://user-images.githubusercontent.com/18232258/72947669-73287080-3d8b-11ea-9f44-eb3bf74c5aa2.png)

> **Clicked `x` mark in the filter, didn't click `Go`**
> In this case, No way to tell that a filter was applied, but to reload the page.
![image](https://user-images.githubusercontent.com/18232258/72947769-c8648200-3d8b-11ea-9829-016aa7ce58f4.png)

**Comment by yasker** [comment]
It seems we don't show what's the currently applied filters.

**Comment by meldafrawi** [comment]
**Longhorn UI version**: wangsiye/longhorn-ui:961752b

Validation: **PASSED**
