### ISSUE TITLE
Longhorn Network Failure and Recovery Scenrios

### ISSUE THREAD

**Issue by j4y4r** [longhorn/longhorn#1029]
I have the following setup,

* 4 nodes running RancherOS,(1.5.5)
* 1 node for rancher ui (2.3.4)
* 3 nodes as worker,etc,controlpane, these are also running longhorn(0.7.0).

Longhorn is installed via the Rancher Catalag inside a Cluster in Project context.
Longhorn configuration is pretty much default, besides i use only 2 Replicas for Volumes and i set Replica Soft Anti-Affinity to false because i do not want to put one node under heavly load because of replication.
Tried 2 Workloads
one is a statefulset, with 3 replicas , each has a pvc in longhorn via storage template.
After the Workload is running, 3 Volumes are visible in the Lonhorn UI.
another is a deployment with one replica wich uses a longhorn pvc.

Now i simulate a Network Failure with disconnecting the network Cable, on the node where no Replicas are running.

09:17 disconnect
09:20 node in loghorn-ui down, rancherui pod state unkown

[pvc-f962876c-dfc8-42f5-a436-9fd7c8a74001-r-720ed431] time="2020-01-23T09:19:43Z" level=error msg="Failed to read: read tcp 10.42.1.7:10001->10.42.2.31:48654: read: connection timed out"
[pvc-61292ec2-963d-4d82-ac64-093925639bae-r-13a45f47] time="2020-01-23T09:19:43Z" level=error msg="Failed to read: read tcp 10.42.1.7:10016->10.42.2.31:42182: read: connection timed out"

The volume itself is shown as healthy in the Longhorn UI.

09:34 reconnect the node

After i reconnect the node the volume health changes to faulted, the state changes to detached.
Node is still shown as Down in the Longhorn-UI

The pod is stuck in the status waiting, ContainerCreating
FailedMount	Unable to attach or mount volumes: unmounted volumes=[vol1], unattached volumes=[vol1 default-token-pjrvb]: timed out waiting for the condition	a few seconds ago

another statueful set with one replica and a longhorn mount looks similar

FailedAttachVolume     AttachVolume.Attach failed for volume "pvc-f962876c-dfc8-42f5-a436-9fd7c8a74001" : rpc error: code = Internal desc = Action [attach] not available on [&{pvc-f962876c-dfc8-42f5-a436-9fd7c8a74001 volume map[self:http://longhorn-backend:9500/v1/volumes/pvc-f962876c-dfc8-42f5-a436-9fd7c8a74001] map[salvage:http://longhorn-backend:9500/v1/volumes/pvc-f962876c-dfc8-42f5-a436-9fd7c8a74001?action=salvage]}]
FailedMount   Unable to attach or mount volumes: unmounted volumes=[blah], unattached volumes=[blah default-token-pjrvb]: timed out waiting for the condition

from the longhorn instance managers:

[instanz_manager_log.txt](https://github.com/longhorn/longhorn/files/4103568/instanz_manager_log.txt)

The volume of the pod whcih was running on the disconnected node ends up in failed state when the node is reconnected.
I had to scale down all relicas of the stateful set, salvage the replicas and then scale the replicas up again to be able to mouint the volume again.

I read 
https://github.com/longhorn/longhorn/blob/master/docs/recover-volume.md
and some issues
#851
#375
and other issues linked from those.

Then i added livenedd/readiness probe to the pods and started another test.
11:27 disconnect
12:05 reconnect

all the pods came back online, but the checks did not solve the issue, i still have to manually salvage the failed replicas for the pods to be able to mount the volume again.

So what would be the procedure to correctly handle such a case?

**Comment by yasker** [comment]
In the upcoming v0.8.0, we will include an `auto-salvage` feature to help users to deal with network issues caused faulted volume. https://github.com/longhorn/longhorn/issues/1046

**Comment by j4y4r** [comment]
Thank you for the information, i will try the fix as soon as 0.8.0 is available.

**Comment by yasker** [comment]
@j4y4r Let me know if v0.8.0 helps.

**Comment by j4y4r** [comment]
@yasker tried with v0.8.0, one workload, one volume(pvc)

network-disconnect-13:44:55
network-reconnect-13:55:19

volume changed to degraded state, the replica on the reconnected node went to failed, after a new one has been created, the volume went into healthy state.

a simple bash script wrote to the pvc several times per second the whole time and it still did after reconnecting.

i could not reproduce the issue, seems fixed!
Thank you :+1:
