### ISSUE TITLE
Replicas unavailable on master after reboot

### ISSUE THREAD

**Issue by jonfairbanks** [longhorn/longhorn#1033]
After restarting my master, any volumes replicated there will not come back online. 

Per Longhorn UI, multiple volumes are stuck in detaching state. If you click these volumes, you can see that 1 of 3 replicas are in a failed state. 

If I go to the bad replica and attempt to delete it, nothing happens. 

<img width="894" alt="Screenshot_7" src="https://user-images.githubusercontent.com/1957806/73133516-972fc000-3fde-11ea-80b5-54491ed5249e.png"> 

<img width="447" alt="Screenshot_8" src="https://user-images.githubusercontent.com/1957806/73133565-51272c00-3fdf-11ea-9940-fad0c66eb288.png">

How can I get these out of detaching state and back in a healthy state?

**Comment by cr0** [comment]
Please verify if the longhorn-master on kube-master is crashing in a similar way to #950. 
What is a workaround for me is: stop all deployments which use a stuck in detaching longhorn pvc. redeploy (delete and wait for) longhorn-manager on kube-master, verify that it does not crash anymore, verify that all replicas are fully detached, finally restart your deployments.

**Comment by jonfairbanks** [comment]
Thanks, will give this a shot.
