### ISSUE TITLE
Volume faulted after node reboot

### ISSUE THREAD

**Issue by shinebayar-g** [longhorn/longhorn#1035]
I was getting `node1 DiskPressure` warning from Rancher UI. I've 2 worker nodes that have 80GB disks. When I check node1's disk usage it had over 60GB usage and pods were failing. I decided to extend both nodes disk to 100GB and I wasn't able to do online resize. So I needed to reboot nodes to take effect. I think my mistake was I rebooted both nodes at the same time. Is this the reason I cannot get back my volumes? If nodes had to rebooted, at least 1 replica must be online at any time to persist longhorn volumes?
Volume data is getting saved at `/var/lib/rancher/longhorn` right? I'm seeing pvc named folders like
`pvc-764700bb-0f3c-4af8-b806-ee810c46e623-1372fe93` on worker nodes.

![image](https://user-images.githubusercontent.com/3091558/73298233-8cd61780-41d2-11ea-935d-4a06174e83dc.png)

Longhorn version: 0.7.0

Edit: Out of curiosity I clicked on salvage option and looks like it removes replicas that are not selected. Then I was able to attach the pvc and it's rebuilding its replicas now.. Volume data was safe. :relieved:

**Comment by yasker** [comment]
@shinebayar-g Yeah that's what `salvage` option designed to do.

Longhorn will declare volume `faulted` if the engine cannot reach any of the replicas. I think it was triggered during the process of rebooting both nodes. The safest way to reboot is to scale down the workload first if possible. And reboot node one by one is better than reboot all the nodes at the same time. But Longhorn is expected to keep the data safe in any case, just you might need to e.g. salvage the volume sometime, at least for now.

**Comment by zengzhengrong** [comment]
@yasker  I think it don't mark "Faulted" with red ,Shocked when I firstmeet that
