### ISSUE TITLE
Not able to delist node

### ISSUE THREAD

**Issue by saggiyogesh** [longhorn/longhorn#1042]
![image](https://user-images.githubusercontent.com/551509/73756655-eec3ed80-478d-11ea-9334-0fa32ee20893.png)

Following steps used to remove a node from Rancher
- Removed a node from Rancher, 
- Disable scheduling from Longhorn UI
- Tried Delete Node from Longhorn UI & getting above Error message. 
- Cleared all docker resources as per this link https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/

Pls, suggest what to do next.  

Version: `v0.7.0`

**Comment by saggiyogesh** [comment]
[longhorn-support-bundle_bcaf4d57-ffba-404c-bcbb-082c8dc4ebc5_2020-02-04T15-15-41Z.zip](https://github.com/longhorn/longhorn/files/4154218/longhorn-support-bundle_bcaf4d57-ffba-404c-bcbb-082c8dc4ebc5_2020-02-04T15-15-41Z.zip)

Attaching support bundle to, if it helps.

**Comment by shuo-wu** [comment]
As the very first step, all engines and replicas on that node need to be cleaned up. And according to the error message in the above screenshot, there is still **one running engine on the node** hence the node deletion gets failed.

Here are the conditions for node deletion:
1. Node condition is not Ready
2. Node scheduling is disabled
3. The Kubernetes node is gone or the longhorn manager pod is missing
4. No engine and replica on that node

**Comment by saggiyogesh** [comment]
@shuo-wu Thanks for reverting back.

I have deleted everything from VM (mongos1), restarted it but still, the node was not deleting and showing on UI.

So checked each and every PVC for any existence of any replica on mongos1 VM and deleted some replicas. 
Finally after some time able to remove the VM 🤘. 
But don't know what magic happened.

**Comment by shuo-wu** [comment]
The node in Longhorn is actually a CRD object. And Longhorn will consider this node as state `Lost` if you just removed the related VM but don't the object is not cleaned up in Longhorn. 

Since the node can be temporarily lost and will be back soon (e.g., reboot), Longhorn cannot arbitrarily remove this node from the system once the related VM is gone.
