### ISSUE TITLE
Add Longhorn into Helm Hub

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1043]
The official way for Helm repo is Helm Hub now.

**Comment by yasker** [comment]
Probably https://hub.cncf.io/ as well.

**Comment by yasker** [comment]
We need to investigate first on how those hubs work.

**Comment by yasker** [comment]
Let's host our own charts in the GitHub.

We have two choices: either we continue to use `longhorn/longhorn`, or we can create a new repo `longhorn/charts`. I am thinking we can still update the latest in `longhorn/longhorn`, but push the new charts to `longhorn/charts`.

**Comment by maggieliu** [comment]
Need a chart in the rancher dev-charts repo: https://github.com/rancher/dev-charts. Longhorn will be considered an upstream chart. Please follow the instructions for Rancher modified chart to package it in dev-chart.

**Comment by yasker** [comment]
Need to update the installation doc to include using helm repo.

**Comment by ttpcodes** [comment]
## Pre-merged Checklist
* [X] Does the PR include the explanation for the fix or the feature?

* [X] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The code is [here](https://github.com/longhorn/charts).

* [X] Is the reproduce steps/test steps documented?

* [X] Which areas/issues this PR might have potential impacts on?
Area: deployment
Issues: #1043

* [X] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?~~

* [X] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~

* [X] **if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at longhorn/website#164.

* [X] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?~~

* [X] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?~~

* [X] ~~**if labeled: require/manual-test-plan** Has the manual test plan been documented?~~

**Comment by ttpcodes** [comment]
The instructions for installing the chart from the repository available on the `staging` branch of longhorn/website.

The charts are now published on [Helm Hub](https://hub.helm.sh/charts/longhorn/longhorn) and [Artifact Hub](https://artifacthub.io/packages/helm/longhorn/longhorn/).

**Comment by yasker** [comment]
@ttpcodes need to update https://github.com/rancher/dev-charts as well for Rancher charts.

**Comment by PhanLe1010** [comment]
Should we update the file https://github.com/longhorn/charts/blob/master/charts/longhorn/templates/NOTES.txt so that Helm gives user more useful information after the installation. 

Currently, I got this message after install longhorn using the chart in longhorn repo on Helm hub.
<img width="889" alt="Screen Shot 2020-07-17 at 1 14 48 PM" src="https://user-images.githubusercontent.com/22139961/87827637-23090300-c830-11ea-99dd-18bb96be80cf.png">

**Comment by yasker** [comment]
@PhanLe1010 Yes. We can point them to the `docs.longhorn.io` for the documentation. That would be definitely more helpful.

**Comment by PhanLe1010** [comment]
@yasker  NVM, I see the updated note in the RC2 release. I am sorry

**Comment by yasker** [comment]
For the `dev-chart` part, we will track it on https://github.com/rancher/rancher/issues/27725. So we can move this to merged.

**Comment by meldafrawi** [comment]
Chart install validation **PASSED**
