### ISSUE TITLE
Automatic recovery from faulted volume due to the engine in the isolated network

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1046]
If a network split happens, the engine might declare all the replicas error thus volume faulted. In this case, we require user to perform `salvage` operation to repair the volume.

But once the network connection restored, we might able to help the user to recover the volume automatically.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

**Test case 1:**

1. A pod is running and using Longhorn volume.
2. Stop all the replicas of the longhorn volume at the SAME time.

> Expect result:  
  - Volume recovers by itself.  **(PASS)**
  - Pod recovers by itself. **(PASS)**


**Test case 2:**

1. A pod is running and using Longhorn volume.
2. Stop one replica.
3. Wait for 30 seconds.
4. Stop all the other replicas

> Expect result: Same as test case 1  **(PASS)**

**Test case 3:**

1. A pod is running and using Longhorn volume.
2. Stop one replica.
3. Wait for 2 minutes.
4. Stop all the other replicas
> Expect result: Same as test case 1: The first stopped replica should remain in the Error state.  **(PASS)**

**Test case 4**

1. A pod is running and using Longhorn volume.
2. Stop the node network connection to other nodes to simulate a network outage.
3. Resume network connection after 1 minute
>  Expect result: Same as test case 1.  **(PASS)**

**Comment by gittygoo** [comment]
@yasker I have recently installed 0.8.0 and noted that a fault seems to have been recovered well from the longhorn side however on the pod side i see that where the volume is mounted when i try to do an "ls" i get "ls: reading directory .: Input/output error".

This leads me to think that either something must be made on the pod to reattach the volume properly or the pod restarted. Is this known or a bug ?

**Comment by yasker** [comment]
@gittygoo you're right, pod needs to be restarted to use the reattached volume. You can setup liveness probe on pod for that. See https://longhorn.io/docs/users-guide/recover-volume/
