### ISSUE TITLE
Feature Request: backup name in Create Disaster Recovery Dialog

### ISSUE THREAD

**Issue by dmayle** [longhorn/longhorn#1048]
My backup screen is full of hash names that are very similar, which makes picking the correct volume very important.  After selecting 'Create Disaster Recovery Volume', the dialog requests a new name but doesn't show the old name.

It would greatly increase my confidence when using these dialogs to know that I had selected the correct volume.

**Comment by yasker** [comment]
Sure, we can add that.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI version:  `wangsiye/longhorn-ui:c97c05a`

Steps to test: 
- Create multiple volumes, attach them to nodes.
- Create volume backups
- In Backup page, select a backup and from right menu click on `Create Disaster Recovery Volume`
> `Create Disaster Recovery Volume` dialog should be populated with selected backup volume name. **(PASSED)**
