### ISSUE TITLE
feature: enforce across zone hard anti-affinity scheduling

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1052]
v0.8.0 only supports soft anti-affinity scheduling. #929

**Comment by boknowswiki** [comment]
Test skeleton for zone anti-affinity:

@pytest.mark.node  # NOQA
def test_replica_zone_anti_affinity(client):  # NOQA
    """
    Test replica scheduler with zone anti-affinity
 
    1. Set zone anti-affinity to hard, and replica count to 2.
    2. Create 2 nodes and add the same zone label to them
    3. Create a volume.
    4. Wait for volume condition `scheduled` to be false.
    5. Change the zone label to be different on one node.
    6. Create a volume.
    7. Wait for volume condition `scheduled` to be success. And clear the volume
    8. Set zone anti-affinity to soft.
    9. Change the zone labels to be the same on both nodes.
    10. Create a volume.
    11. Wait for volume condition `scheduled` to be success.
    12. Clean up the replica count, the zone labels and the volume.
    """

@meldafrawi , @yasker , please take a look.

**Comment by boknowswiki** [comment]
Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
* [ ] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [ ] ~~**if labeled: require-automation-engine** Has the engine integration test been merged?~~
* [ ] ~~**if labeled: require-doc** Has the necessary document PR submitted or merged?~~
