### ISSUE TITLE
two replicas on the same node

### ISSUE THREAD

**Issue by runningman84** [longhorn/longhorn#1060]
I have a three node k3s cluster. If I reboot any of the them the longhorn replicas are rebuild on the remaining nodes. Which means that one of the node has two replicas of the same volume while the other has only one replica. Once the third node is online again the replica of the third node is displayed in a stopped stayed. Which means I have 4 replicas.

I think this behavior could be optimized:
1) do not create two replicas of the same volume in the same node
2) keep the volume in a degraded state until the third node comes up again
3) automatically resume replication once the third node is online again

The current behavior could also lead to full disks if you just reboot machine often enough.

**Comment by yasker** [comment]
@runningman84 The first two behavior can be achieved by disabling [`soft anti-affinity`](https://github.com/longhorn/longhorn/blob/master/docs/settings.md#replica-soft-anti-affinity) setting. Though we're not reusing the replicas at this moment.

**Comment by runningman84** [comment]
Ok I will try the soft anti affinity option.

Please add an option for auto recovery which could be disabled by default.

**Comment by yasker** [comment]
@runningman84 Which "auto recovery" you're talking about?

**Comment by runningman84** [comment]
> @runningman84 Which "auto recovery" you're talking about?

automatically resume replication once the third node is online again

**Comment by yasker** [comment]
@runningman84 If you disable the `soft anti-affinity`, then the replication will only perform on the different nodes. So it will resume replication when the third back online. It will not reuse the old replica on the node at the moment.

**Comment by runningman84** [comment]
In this case we need auto cleanup feature. Otherwise the disk will fill up if you reboot too many times....

**Comment by yasker** [comment]
@runningman84 yeah Longhorn will cleanup faulted replica automatically after `staleReplicaTimeout` which is 48 hours (2880 minutes) .
