### ISSUE TITLE
security improvement webui should be cluster ip by default

### ISSUE THREAD

**Issue by runningman84** [longhorn/longhorn#1065]
The webui should not be exposed as a loabalancer by default. This creates a security issue because most users would assume they have to setup an ingress with some kind of http auth...

Exposing it additionally using a Loadbalancer creates unnecessary costs and risks.

**Comment by yasker** [comment]
Make sense. @meldafrawi Can you work on this? Be careful around the upgrade case.

**Comment by yasker** [comment]
@runningman84 I think `NodePort` makes more sense. `ClusterIP` will require the user to manually configure the service. `NodePort` only expose the service on the internal node's port, which should be a good compromise.

**Comment by runningman84** [comment]
@yasker no user would have to manually configure the service because it is common to use an ingress for just about anything. An ingress offers options like basic auth, ip auth and so on.

If your users deploy longhorn to a cheap vps provider with no firewall (which is normally the default) they expose the longhorn storage to the internet. In this case an attacker just enters a new backup target and can download all volume data from there.

This would also expose it to search engines like https://www.shodan.io/ which just scans for open ports and their content...

**Comment by runningman84** [comment]
Why do you want to go the same route as mongodb and elasticsearch which had a lot of data leaked due to insecure default configs?

**Comment by yasker** [comment]
I have to say the name `mongodb` and `elasticsearch` works, lol.

OK, let's do the secure way by default. 

@meldafrawi Let's use ClusterIP.
 
The user needs to be aware of this change. We need to update the document with some examples too.

**Comment by runningman84** [comment]
The examples for the ingress should also include some http basic auth or ip filter... otherwise you just move the problem to a different part of the system...

**Comment by yasker** [comment]
@runningman84 suggestions are welcome! PRs on documents are even better. :smirk:
