### ISSUE TITLE
Longhorn in default setup likely to cause DiskPressure resulting in unreachable volume replicas and cascading cluster issues

### ISSUE THREAD

**Issue by manuel-koch** [longhorn/longhorn#1068]
We have a small cluster setup with some nodes ( running longhorn 0.7.0 ) that have rather small disk resources and no dedicated disks for longhorn-volume-replicas, i.e. just the root filesystem.

The default longhorn setting for `StorageMinimalAvailablePercentage` is 10%.
It seems the default trigger for a k8s node `DiskPressure` signal is 15%.

Thus in the default setup it is likely that longhorn exhausts disk space of a node ( because there is still more than 10% of disk space avail ) and triggers `DiskPressure` because node now has less than 15% of disk space avail.

Shouldn’t longhorn take into account the current level of free disk space that would trigger a `DiskPressure` too to avoid longhorn getting evicted from current node ?
In such a scenario the replicated volumes get re-scheduled to other nodes, that again may trigger the `DiskPressure` problem.

This topic has been published on rancher-forum too: https://forums.rancher.com/t/dealing-with-diskpressure/16666

**Comment by yasker** [comment]
Make sense. We can set 20% as default for StorageMinimalAvailablePercentage.

**Comment by yasker** [comment]
We need to update the Rancher chart as well.

**Comment by yasker** [comment]
Done
