### ISSUE TITLE
Additional disk(s) path must be the real mount path ( not a symlink from root-fs into mounted disk )

### ISSUE THREAD

**Issue by manuel-koch** [longhorn/longhorn#1069]
Using Longhorn 0.7.0.

I have the following setup on one of my k8s nodes :
- root fs: "/var/lib/rancher/longhorn" is dedicated to longhorn
- mounted disk: "/mnt/HC_Volume_4412115"
- symlinked directory "/var/lib/rancher/longhorn2" pointing to "/mnt/HC_Volume_4412115/longhorn"

Longhorn configured on that node to use disk with paths:
- /var/lib/rancher/longhorn
- /var/lib/rancher/longhorn2

It appears that attempts to schedule longhorn replicas/volumes on that node fail for some reason.
The PV/PVC never gets provisioned properly and related PODs therefore are stuck in `Creating`.

I fixed the issue by changing the longhorn configuration on that node to use disks with paths:
- /var/lib/rancher/longhorn
- /mnt/HC_Volume_4412115

Thus my question is why does it fail in the first scenario but succeeds in the later scenario ?

The docs of longhorn-node-configuration-page related to disk-path is not very clear to me, i.e. whether the given path _must_ be the real (root) path to the mounted disk instead of any symlinked path that eventually resolves to a directory on a mounted disk.
The description in longhorn-ui on the disk-path just states "Path mounted by the disk, e.g. /mnt/disk1".

Maybe ui ( hence configuration of node disks ) could be improved to check that the given path is really root ( or sub- ) directory of a mounted disk.

**Comment by yasker** [comment]
The reason is Longhorn components are running inside the pods, but the soft link won't work when we bind mount the path into the pod for accessing.

You can use `mount --bind` instead of the soft link.

**Comment by yasker** [comment]
I've updated the documentation for the topic https://github.com/longhorn/longhorn/blob/master/docs/multidisk.md#use-an-alternative-path-for-disk-on-the-node .
