### ISSUE TITLE
Longhorn volume stuck in deleting even though the underlying PV/PVC has already been deleted

### ISSUE THREAD

**Issue by manuel-koch** [longhorn/longhorn#1071]
Using Longhorn 0.7.0.

I have a longhorn volume in “deleting” state shown in UI.
Repeated attempts to delete it don’t remove it and it is stuck in this state.
I have already removed the corresponding PV/PVC from k8s but still that Longhorn Volume is listed as “deleting” in UI.

Background info regarding this volume:

- Initially the volume was a valid PV/PVC following the standard naming convention “pvc-*”
- At some point we had DiskPressure issues on a node ( causing POD eviction incl Longhorn PODs ), rendering that volume broken because re-scheduling the longhorn replicas failed due to insufficient resources on other nodes.
- Restored the broken volume from a backup using longhorn UI - but using a different volume-name, not like “pvc-*”. 
Afterwards that re-created longhorn volume (PV/PVC) was usable on the corresponding POD again.
- The DiskPressure issue reappeared, again longhorn volume got broken due the resulting POD eviction.
- Afterwards that longhorn volume was shown in UI as “Detached” even though the rescheduled POD successfully accessed PV/PVC
- Downscaled corresponding deployment, manually removed PV/PVC. During removal of PV/PVC it was necessary to force removal by editing/removing the "metadata.finalizers" section within configuration of PV/PVC.
- Any attempt to remove the volume via longhorn UI failed, leaving it in “deleting” state.

The logs of longhorn-manager start with this snippet and the last errors are repeated over and over again:
Name of the stuck longhorn volume is “sfpl-prod-file-service”.
The mentioned “instance-manager-r-af5c615a” POD does not run anymore, I guess it was evicted when DiskPressure happened.

```
time="2020-02-24T16:16:55Z" level=info msg="Start overwriting built-in settings with customized values"
time="2020-02-24T16:16:55Z" level=debug msg="Engine image longhornio/longhorn-engine:v0.7.0 is ready"
time="2020-02-24T16:16:55Z" level=info msg="Listening on 10.42.4.140:9500"
time="2020-02-24T16:16:55Z" level=info msg="Start Longhorn node controller"
time="2020-02-24T16:16:55Z" level=info msg="Start Longhorn replica controller"
time="2020-02-24T16:16:55Z" level=info msg="Start Longhorn engine controller"
time="2020-02-24T16:16:55Z" level=info msg="Start Longhorn websocket controller"
time="2020-02-24T16:16:55Z" level=info msg="Start Longhorn volume controller"
time="2020-02-24T16:16:55Z" level=info msg="Start Longhorn Engine Image controller"
time="2020-02-24T16:16:55Z" level=info msg="Starting Longhorn instance manager controller"
time="2020-02-24T16:16:55Z" level=info msg="Start Longhorn Setting controller"
time="2020-02-24T16:16:55Z" level=info msg="Start kubernetes controller"
time="2020-02-24T16:16:56Z" level=debug msg="Start monitoring pvc-1a6b2d60-2c86-437f-bad4-6c3e01abab4b-e-38079260"
time="2020-02-24T16:16:56Z" level=debug msg="Start monitoring instance manager instance-manager-r-33fd6639"
time="2020-02-24T16:16:56Z" level=warning msg="Error syncing Longhorn replica longhorn-system/sfpl-prod-file-service-r-720aa022: fail to sync replica for longhorn-system/sfpl-prod-file-service-r-720aa022: failed to cleanup the related replica process before deleting replica sfpl-prod-file-service-r-720aa022: instancemanager.longhorn.io \"instance-manager-r-af5c615a\" not found"
time="2020-02-24T16:16:56Z" level=debug msg="Start monitoring pvc-e580989d-01e3-4b58-bf8b-6fee72b63762-e-15b99770"
time="2020-02-24T16:16:56Z" level=debug msg="Start backup store monitoring for s3://longhorn-backup@us-east-1/"
time="2020-02-24T16:16:56Z" level=debug msg="Start monitoring instance manager instance-manager-e-5f078c81"
time="2020-02-24T16:16:56Z" level=warning msg="Error syncing Longhorn replica longhorn-system/sfpl-prod-file-service-r-720aa022: fail to sync replica for longhorn-system/sfpl-prod-file-service-r-720aa022: failed to cleanup the related replica process before deleting replica sfpl-prod-file-service-r-720aa022: instancemanager.longhorn.io \"instance-manager-r-af5c615a\" not found"
E0224 16:16:56.073734       1 replica_controller.go:178] fail to sync replica for longhorn-system/sfpl-prod-file-service-r-720aa022: failed to cleanup the related replica process before deleting replica sfpl-prod-file-service-r-720aa022: instancemanager.longhorn.io "instance-manager-r-af5c615a" not found
time="2020-02-24T16:16:56Z" level=warning msg="Dropping Longhorn replica longhorn-system/sfpl-prod-file-service-r-720aa022 out of the queue: fail to sync replica for longhorn-system/sfpl-prod-file-service-r-720aa022: failed to cleanup the related replica process before deleting replica sfpl-prod-file-service-r-720aa022: instancemanager.longhorn.io \"instance-manager-r-af5c615a\" not found"
time="2020-02-24T16:17:25Z" level=warning msg="Error syncing Longhorn replica longhorn-system/sfpl-prod-file-service-r-720aa022: fail to sync replica for longhorn-system/sfpl-prod-file-service-r-720aa022: failed to cleanup the related replica process before deleting replica sfpl-prod-file-service-r-720aa022: instancemanager.longhorn.io \"instance-manager-r-af5c615a\" not found"
time="2020-02-24T16:17:25Z" level=warning msg="Error syncing Longhorn replica longhorn-system/sfpl-prod-file-service-r-720aa022: fail to sync replica for longhorn-system/sfpl-prod-file-service-r-720aa022: failed to cleanup the related replica process before deleting replica sfpl-prod-file-service-r-720aa022: instancemanager.longhorn.io \"instance-manager-r-af5c615a\" not found"
E0224 16:17:25.795593       1 replica_controller.go:178] fail to sync replica for longhorn-system/sfpl-prod-file-service-r-720aa022: failed to cleanup the related replica process before deleting replica sfpl-prod-file-service-r-720aa022: instancemanager.longhorn.io "instance-manager-r-af5c615a" not found
time="2020-02-24T16:17:25Z" level=warning msg="Dropping Longhorn replica longhorn-system/sfpl-prod-file-service-r-720aa022 out of the queue: fail to sync replica for longhorn-system/sfpl-prod-file-service-r-720aa022: failed to cleanup the related replica process before deleting replica sfpl-prod-file-service-r-720aa022: instancemanager.longhorn.io \"instance-manager-r-af5c615a\" not found"
.....
E0225 07:23:56.705452       1 replica_controller.go:178] fail to sync replica for longhorn-system/sfpl-prod-file-service-r-720aa022: failed to cleanup the related replica process before deleting replica sfpl-prod-file-service-r-720aa022: instancemanager.longhorn.io "instance-manager-r-af5c615a" not found
time="2020-02-25T07:23:56Z" level=warning msg="Dropping Longhorn replica longhorn-system/sfpl-prod-file-service-r-720aa022 out of the queue: fail to sync replica for longhorn-system/sfpl-prod-file-service-r-720aa022: failed to cleanup the related replica process before deleting replica sfpl-prod-file-service-r-720aa022: instancemanager.longhorn.io \"instance-manager-r-af5c615a\" not found"
```

**Comment by manuel-koch** [comment]
I have created a support-bundle via Longhorn-UI - to whom can I sent this ? I don't want to place it here for public inspection.

**Comment by meldafrawi** [comment]
@manuel-koch please send the support-bundle to longhorn-support-bundle@rancher.com

**Comment by manuel-koch** [comment]
I've sent an email, let me know if you've received it and if the content is helpful.

**Comment by yasker** [comment]
@manuel-koch yeah we've received the support bundle and looking into it.

**Comment by meldafrawi** [comment]
@manuel-koch 
1. Can you check if `VolumeAttachment` object 
`csi-593cfb6ff42d2784246853b745263d5c4c1bff82362146ae3bc0c36a86c28b7b` exists

2. Can you elaborate more why you it  `was necessary to force removal by editing/removing the "metadata.finalizers" section within configuration of PV/PVC.`

**Comment by manuel-koch** [comment]
Regarding the `VolumeAttachment` object, there is no such object with given id listed by kubectl - I can see 10 objects of type `volumeattachment.storage.k8s.io` that corresponds to the number of 10 active volumes displayed by longhorn-ui and there is additionally one stuck volume in `Deleting` within longhorn-ui.

I guess I had to force deleting by removing the finalizers because otherwise I could not restore the very PV/PVC from my longhorn-backup.

- node got `DiskPressure`, kicking out PODs incl. longhorn PODs
- I observed several longhorn-volumes in unhealthy state
- I tried to delete a broken volume via longhorn-ui which was not possible
- I used plain kubectl commands to delete corresponding PV/PVC, but they were afterwards stuck in `Terminating` - I guess because the longhorn finalizer was unable to do its job likely because of the sudden POD evictions ( and the `instance-manager-r-af5c615a` not existing anymore ) or any follow-up problem that arose due to errors when moving volume-replicas to a new node that somehow failed because of too few disk space on other nodes.
- I removed PV/PVC finalizers to allow kubectl to delete them and they were removed afterwards
- restored PV/PVC from longhorn backup using original names successfully

**Comment by manuel-koch** [comment]
Any update on this issue regarding my stuck volume ?
Anything I can do to advance my broken volume from its stuck state ?
I would like to upgrade to latest longhorn version but I fear getting into troubles with such an unhealthy volume stuck in deleting within my cluster.

**Comment by yasker** [comment]
@manuel-koch You can remove the finalizer from replica `sfpl-prod-file-service-r-720aa022` to skip the cleanup process and continue with volume deletion.

e.g. 
```
kubectl -n longhorn-system patch replicas.longhorn.io sfpl-prod-file-service-r-720aa022 -p '{"metadata":{"finalizers": []}}' --type=merge
```

I've also filed #1118 to track missing instance pod cause the replica to stuck issue.

**Comment by manuel-koch** [comment]
That broken volume vanished from longhorn-ui, after applying your suggested `kubectl` command.
Thanks !
