### ISSUE TITLE
[BUG] All volumes with replicas go into faulted state

### ISSUE THREAD

**Issue by aandrushchenko** [longhorn/longhorn#1074]
**Describe the bug**
I have 3 Volumes over 3 Nodes each having 3 replicas. Suddenly all of them are in Fault state.

**To Reproduce**
This does not have any precise steps to reproduce

**Expected behavior**
Volumes are healthy.

**Log**
│ time="2020-02-27T16:16:04Z" level=debug msg="Prepare to delete instance pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3"                                                                                    │
│ time="2020-02-27T16:16:04Z" level=warning msg="Instance pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3 is state error, error message: exit status 1"                                                       │
│ time="2020-02-27T16:16:04Z" level=debug msg="Instance handler updated instance pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3 state, old state running, new state error"                                   │
│ time="2020-02-27T16:16:04Z" level=warning msg="Instance pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3 crashed on Instance Manager instance-manager-r-6edaf9ec at node3, try to get log"                   │
│ time="2020-02-27T16:16:04Z" level=info msg="Event(v1.ObjectReference{Kind:\"Replica\", Namespace:\"longhorn-system\", Name:\"pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3\", UID:\"e370b12d-c70b-4af7-a5 │
│ 76-624e3b5e9a29\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"7933485\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3"                  │
│ time="2020-02-27T16:16:04Z" level=error msg="failed to receive log for instance pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3: rpc error: code = NotFound desc = cannot find process pvc-95cf9142-f70e-49 │
│ 76-ad63-d26849a77e2d-r-49f9dbb3"                                                                                                                                                                                │
│ time="2020-02-27T16:16:04Z" level=warning msg="cannot get crash log for instance pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3 on Instance Manager instance-manager-r-6edaf9ec at node3, error rpc error: │
│  code = NotFound desc = cannot find process pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3"                                                                                                                │
│ time="2020-02-27T16:16:04Z" level=debug msg="Prepare to delete instance pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3"                                                                                    │
│ time="2020-02-27T16:16:04Z" level=warning msg="Instance pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3 is state error, error message: exit status 1"                                                       │
│ time="2020-02-27T16:16:04Z" level=warning msg="Instance pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3 crashed on Instance Manager instance-manager-r-6edaf9ec at node3, try to get log"                   │
│ time="2020-02-27T16:16:04Z" level=info msg="Event(v1.ObjectReference{Kind:\"Replica\", Namespace:\"longhorn-system\", Name:\"pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3\", UID:\"e370b12d-c70b-4af7-a5 │
│ 76-624e3b5e9a29\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"7933490\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3"                  │
│ time="2020-02-27T16:16:04Z" level=error msg="failed to receive log for instance pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3: rpc error: code = NotFound desc = cannot find process pvc-95cf9142-f70e-49 │
│ 76-ad63-d26849a77e2d-r-49f9dbb3"                                                                                                                                                                                │
│ time="2020-02-27T16:16:04Z" level=warning msg="cannot get crash log for instance pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3 on Instance Manager instance-manager-r-6edaf9ec at node3, error rpc error: │
│  code = NotFound desc = cannot find process pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3"                                                                                                                │
│ time="2020-02-27T16:16:05Z" level=warning msg="Try to get requested log for pvc-6a56380d-b657-4d36-a6a1-684a9ae10c3f-r-b0edfe70 on node node3"                                                                  │
│ time="2020-02-27T16:16:05Z" level=warning msg="cannot get requested log for instance pvc-6a56380d-b657-4d36-a6a1-684a9ae10c3f-r-b0edfe70 on node node3, error cannot find Instance Manager "                    │
│ time="2020-02-27T16:16:05Z" level=debug msg="Instance handler updated instance pvc-95cf9142-f70e-4976-ad63-d26849a77e2d-r-49f9dbb3 state, old state error, new state stopped"

**Environment:**
 - Longhorn version: 0.7.0
 - Kubernetes version: 1.17.2
 - Node OS type and version: CentOS Linux release 7.3.1611 (Core)

**Additional context**
Rancher v.2.3.5

**Comment by yasker** [comment]
@aandrushchenko Sounds like a network interruption. In v0.7.0 you can use `salvage` option to recover the volume and there shouldn't be data corruption.

We've introduced #1046 to help with the situation in v0.8.0.

**Comment by aandrushchenko** [comment]
@yasker thanks for the prompt reply, unfortunately i have removed volumes, so can't try salvage option for this exact case. i am recreating the same setup now, do you have any hint on how can i simulate the same failure?

**Comment by j4y4r** [comment]
you can simulate the failure by removing the network cable of one worker and reconnect it again, i have described my findings in issue #1029 .
