### ISSUE TITLE
[BUG][v0.8.0-rc1] Node Readiness column need redesign

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1077]
After merged #880 , Node `Readiness` column doesn't show useful information.

@shuo-wu Can you work with @smallteeths on a new design that makes sense with Live Upgrade v2?

**Comment by shuo-wu** [comment]
We will set the column`node.Readiness = Ready`when all the following 4 conditions are satisfied:
1. `node.conditions.Ready.status` is True;
2. The default EngineImage `currentState` is `Running`;
  2.1. How to find the default EngineImage? List all EngineImages and check if `ei.image == setting.default-engine.image.value`
3. The default EngineManger `currentState` is `Running`;
  3.1. How to find the default EngineManager for each node? List all InstanceManagers and check if `im.image == setting.default-instance-manager.image.value && im.managerType == engine && im.nodeID = node.id`
4. The default ReplicaManger `currentState` is `Running` **when `node.disks` is not empty**;
  4.1. If `node.disks` is empty, ignore ReplicaManager and mark it as `N/A`
  4.2.  If `node.disks` is not empty, follow the similar method mentioned in 3.1 to find the corresponding default ReplicaManager

**Comment by yasker** [comment]
@shuo-wu When the user clicked the `Ready`, they will see a list of instance managers etc. That dialog also needs to be updated.

**Comment by shuo-wu** [comment]
@yasker I have updated the design for the diagram.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
