### ISSUE TITLE
[Question] Hi how can I set csi-resizer to be deployed from proivate registry.

### ISSUE THREAD

**Issue by martinounap** [longhorn/longhorn#1096]
We have used longhorn-driver-deployer command , can we still use this pattern:

           - --csi-attacher-image
           -  {PRIVATE_REGISTRY}/quay.io/k8scsi/csi-attacher:v2.0.0
           - --csi-provisioner-image
           - {PRIVATE_REGISTRY}/quay.io/k8scsi/csi-provisioner:v1.4.0
           - --csi-node-driver-registrar-image
           - {PRIVATE_REGISTRY}/quay.io/k8scsi/csi-node-driver-registrar:v1.2.0

**Comment by shuo-wu** [comment]
Yes. As long as the images are correct and do exist in your private registry, the image namespace/name/tag is not important.

BTW, you can also specify these images if you choose Rancher App to launch Longhorn.

**Comment by martinounap** [comment]
Hi

Could you please guide me, how we can set it in yamls for csi-resizer component.

**Comment by shuo-wu** [comment]
Add 2 lines [here](https://github.com/longhorn/longhorn/blob/008ba3d7f70a580c38590d6e4a80b52837c6b652/deploy/longhorn.yaml#L402):
```
- --csi-resizer-image
- <The image in your private registry>
```

**Comment by yasker** [comment]
@shuo-wu Those should be in the example yaml, and the chart.

**Comment by yasker** [comment]
Will be covered by https://github.com/longhorn/longhorn/issues/812
