### ISSUE TITLE
[BUG] Default data directory in the `default-settings` is still `/var/lib/rancher/longhorn`

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1102]
We've updated it to `/var/lib/longhorn` already in the code.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps:
  - Deploy Longhorn
  - in Settings page, `Default Data Path` should be set to `/var/lib/longhorn/`
  - Create a volume, attach it to a node, 
  - Verify replica path is prefixed to `/var/lib/longhorn/` for all nodes
