### ISSUE TITLE
[Question] relationship with local-path-provisioner?

### ISSUE THREAD

**Issue by y2kenny** [longhorn/longhorn#1104]
What is the relationship between longhorn and [local-path-provisioner](https://github.com/rancher/local-path-provisioner)?  Is it fair to say that a longhorn storageclass with only 1 replica is pretty much equivalent to local-path-provisioner?  (in terms of both features and performance?)

**Comment by yasker** [comment]
@y2kenny There is no relationship between the two except for I wrote the most part of both...

Local Path Provisioner provides only the local disks directly for pods to consume. It doesn't have features like HA across the cluster, snapshot, backup etc. It uses a Kubernetes scheduling feature to make sure pod always schedule to the storage. But it has no way to deal with node down. The node down case will be up to the workload itself to figure out.

Longhorn is an enterprise-grade storage system, providing high availability persistent storage to the Kubernetes cluster. It provides HA and features like snapshot/backup/disaster recovery, but that means there are more layers between the disk and pod, resulting in the performance cost. Though most workload requires a storage system that is capable of HA to run in production, and that's Longhorn's target.

**Comment by y2kenny** [comment]
@yasker Thanks for the clarification.  What I am trying to understand, is whether I need both or if longhorn can also cover the use case of local path provisioner.  I understand longhorn is very feature rich and flexible, but let say I dump most of the HA functionalities by reducing replica to 1 is the performance roughly the same as local path?

**Comment by yasker** [comment]
@y2kenny It won't be the same since all the mechanisms are already built-in. But Longhorn's performance is sufficient for almost all the workloads. It shouldn't be a concern in most cases.

**Comment by y2kenny** [comment]
ok.  Thanks.
