### ISSUE TITLE
[BUG] driver-deployer incorrect logging - Node is not support mount propagation

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#1106]
**Describe the bug**
longhorn-driver-deployer log  `Node xxx is not support mount propagation` when the instance-manager image is not deployed.

**To Reproduce**
1. Deploy Longhorn in airgab install,
2. use long  registry prefix such that `registry prefix + instance manager image name`  number of characters is greater than 63 characters.
2. check longhorn-driver-deployer logs 

**Expected behavior**
longhorn-driver-deployer should log the correct reason for failure.

**Log**
```
time="2020-03-13T22:49:22Z" level=warning msg="Got an error when checking MountPropagation with node status, Node XXX is not support mount propagation"
time="2020-03-13T22:49:22Z" level=fatal msg="Error deploying driver: CSI cannot be deployed because MountPropagation is not set: Node XXX is not support mount propagation"
```

**Environment:**
 - Longhorn version: v0.8.0
 - Kubernetes version: v1.17
 - Node OS type and version: Ubuntu 18.04

**Additional context**
Longhorn Airgap installation - longhorn/longhorn#819

**Comment by tibers** [comment]
Just to add a note here - I was told to fix the `longhorn-engine` container line so it was less than 63 chars and I brought it down to 59 chars with some creative tagging. However, I still get this error and I believe all the other containers probably suffer from the same problem.

**Comment by meldafrawi** [comment]
Checking longhorn manager logs, user should be able to see the following logs:

> "Dropping Longhorn node longhorn-system/**NODE_NAME** out of the queue: fail to sync node for longhorn-system/**NODE_NAME**: InstanceManager.longhorn.io \"instance-manager-e-605e9473\" is invalid: metadata.labels: Invalid value:
 \"**PRIVATE_REGISTRY_URL**-**PREFIX**-longhorn-instance-manager-v1_20200301\": **must be no more than 63 characters**"

**Comment by louiscpalma** [comment]
I am having a very similar issue, but **not** using a private registry. 

Have been working on deploying to an on-premise cluster using tainted nodes. I have something else going on with the installation causing all my nodes to be marked down. 

Trying to troubleshoot through the issues I noticed `driver-deployer` pod logs only show the same `Node is not support MountPropagation`.

MountPropagation has been set up on the nodes prior to installation, and the [environment_check.sh](https://github.com/longhorn/longhorn/blob/master/scripts/environment_check.sh) was successful with `MountPropagation is enabled` message. Host disk also was populated with longhorn engine-image binaries so containers are seemingly mounting properly. 

It would seem my issues are unrelated to `MountPropagation` but it is still what I'm seeing in `driver-deployer` logs. Clearly I have something else going on with my installation, but seems relevant to this issue.

**Comment by yasker** [comment]
@louiscpalma can you check the `longhorn-manager`'s log? There might be some clues.
