### ISSUE TITLE
[Question] Permission denied for workloads

### ISSUE THREAD

**Issue by timmy59100** [longhorn/longhorn#1114]
Similiar to #355 after deploying a workload, I get the error "permission denied" when trying to write to the volume. Is there something missing in the configuration?

**Comment by timmy59100** [comment]
I had to set the security context with the right user/group in the deployment. Works now.

**Comment by drewhemm** [comment]
Hi @timmy59100, please could you share the `securityContext` you used to enable writing to the LH volumes?

**Comment by yasker** [comment]
@drewhemm It depends on what does your workload need, but in general it looks like this (from https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod )

```
securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
```
