### ISSUE TITLE
[BUG]unable to create longhorn engine pods

### ISSUE THREAD

**Issue by HKMglicks** [longhorn/longhorn#1122]
**Describe the bug**
unable to create longhorn engine pods; kubernetes cannot create overlay, thus the environment which being deployed on doesn't have internet connection. 

**To Reproduce**
1. Go to kubernetes manager
2. Deploy longhorn yaml
3. kubectl describe -n longhorn-system the engine pod

**Expected behavior**
the engine pod will have the following response CreateContainerError

**Log**
this is the logs which belong to the longhorn engine:
Error: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/7320279a22646429ee6511fb8214e8c6544adf5e5b9bdcded658afc348f52e07-init/merged: no such file or directory

  Warning  Failed     23m                  kubelet, worker06  Error: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/9267c223f9275a5d960e3373937b911cb282c2e0434cfeb80017fd4aab026dd5-init/merged: no such file or directory

  Warning  Failed     23m                  kubelet, worker06  Error: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/1a6813d8cc04707d05d843a52eeefc38837c9dcd3ca9d8cc05c536fd0f7040b8-init/merged: no such file or directory

  Warning  Failed     23m                  kubelet, worker06  Error: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/f9cc69f3c2b4c0522276decef39cc42a40e2fa79c079e6106306ab5f32a528ee-init/merged: no such file or directory

  Warning  Failed     22m                  kubelet, worker06  Error: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/60ca10464107bdb7ae8a7a3bc3f93ebdbb85796cc22956e8b99ec627d3e53625-init/merged: no such file or directory

  Warning  Failed     22m                  kubelet, worker06  Error: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/4d4a1d421136b73cdb5ddac311a578834b71bd7b42a8dcd037b846087ca8d2e5-init/merged: no such file or directory

  Warning  Failed     22m                  kubelet, worker06  Error: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/1bbc14cf2ce4859cb8dc341180b7bff9c80012a847390d2df42fdf2a8633ebbf-init/merged: no such file or directory

  Normal   Pulled     22m (x8 over 23m)    kubelet, worker06  Successfully pulled image "registry/longhorn-engine:v0.8.0"
  Warning  Failed     22m                  kubelet, worker06  Error: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/20a413c40f0681547d1ee84928afde795a73db856010ec63e38ff70295e7a6f1-init/merged: no such file or directory
  Normal   Pulling    3m4s (x95 over 23m)  kubelet, worker06  Pulling image "registry/longhorn-engine:v0.8.0"
---------------
this is the log which belongs to the instance manager:
tgtd: iser_ib_init(3431) Failed to initialize RDMA; load kernel modules?
tgtd: work_timer_start(146) use timer_fd based scheduler
tgtd: bs_init(387) use signalfd notification
time="2020-03-19T04:58:21Z" level=info msg="Storing process logs at path: /var/log/instances"
[longhorn-instance-manager] time="2020-03-19T04:58:21Z" level=info msg="Instance Manager listening to 0.0.0.0:8500"
[longhorn-instance-manager] time="2020-03-19T05:00:15Z" level=debug msg="started new process manager update watch"
[longhorn-instance-manager] time="2020-03-19T05:05:39Z" level=debug msg="started new process manager update watch"
[longhorn-instance-manager] time="2020-03-19T05:13:35Z" level=debug msg="started new process manager update watch"
----------------
this is the log which belongs to the Longhorn manager:
time="2020-03-19T05:15:14Z" level=info msg="Start overwriting built-in settings with customized values"
time="2020-03-19T05:15:14Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: Failed to execute: nsenter [--mount=/host/proc/135725/ns/mnt --net=/host/proc/135725/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/*': No such file or directory\n, error exit status 2"
time="2020-03-19T05:15:14Z" level=info msg="New upgrade leader elected: worker06"
time="2020-03-19T05:15:36Z" level=info msg="Start the APIVersion upgrade process"
time="2020-03-19T05:15:36Z" level=info msg="No upgrade is needed"
time="2020-03-19T05:15:36Z" level=info msg="Upgrade APIVersion completed"
time="2020-03-19T05:15:36Z" level=info msg="Start the instance managers upgrade process"
time="2020-03-19T05:15:36Z" level=info msg="Upgrade instance managers completed"
E0319 05:15:36.829610       1 leaderelection.go:282] Failed to release lock: Lease.coordination.k8s.io "longhorn-manager-upgrade-lock" is invalid: spec.leaseDurationSeconds: Invalid value: 0: must be greater than 0
time="2020-03-19T05:15:36Z" level=info msg="Upgrade leader lost: worker03"
time="2020-03-19T05:15:36Z" level=info msg="Start Longhorn engine controller"
time="2020-03-19T05:15:36Z" level=info msg="Start Longhorn node controller"
time="2020-03-19T05:15:36Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:15:36Z" level=info msg="Start Longhorn Setting controller"
time="2020-03-19T05:15:36Z" level=info msg="Start Longhorn volume controller"
time="2020-03-19T05:15:36Z" level=info msg="Start Longhorn websocket controller"
time="2020-03-19T05:15:36Z" level=info msg="Starting Longhorn instance manager controller"
time="2020-03-19T05:15:36Z" level=info msg="Start kubernetes controller"
time="2020-03-19T05:15:36Z" level=info msg="Start Longhorn Engine Image controller"
time="2020-03-19T05:15:36Z" level=info msg="Start Longhorn replica controller"
time="2020-03-19T05:15:37Z" level=debug msg="Start monitoring instance manager instance-manager-r-b5b78ee7"
time="2020-03-19T05:15:37Z" level=debug msg="Start monitoring instance manager instance-manager-e-2fc198a1"
time="2020-03-19T05:15:42Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:15:44Z" level=debug msg="Failed to check for the latest upgrade: Post https://longhorn-upgrade-responder.rancher.io/v1/checkupgrade: dial tcp: lookup longhorn-upgrade-responder.rancher.io on 10.96.0.10:53: read udp 192.168.232.121:39357->10.96.0.10:53: i/o timeout"
time="2020-03-19T05:15:48Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:15:54Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:16:00Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:16:06Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:16:12Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:16:18Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:16:24Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:16:30Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:16:36Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:16:42Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:16:48Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:16:54Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:17:00Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:17:06Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:17:12Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:17:18Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:17:24Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:17:30Z" level=debug msg="Waiting for engine image registry/longhorn-engine:v0.8.0 to be ready"
time="2020-03-19T05:17:36Z" level=fatal msg="Error starting manager: failed to wait for engine image registry/longhorn-engine:v0.8.0: Wait for engine image registry/longhorn-engine:v0.8.0 timed out"

**Environment:**
 - Longhorn version: 0.8
 - Kubernetes version: 1.16.2
 - Node OS type and version: ubuntu 16.0.4
 - Docker verison: 18.09.1
**Additional context**

**Comment by yasker** [comment]
@HKMglicks This looks like a Docker issue, e.g. https://github.com/docker/for-mac/issues/1396 . Did you hit this on all the nodes?

**Comment by HKMglicks** [comment]
@yasker yes we encountered this issue on all nodes when deploying the longhorn engine only within a none internet environment

**Comment by HKMglicks** [comment]
we have tested to create an overlay with other application; they been working fine expect for longhorn engine @yasker

**Comment by yasker** [comment]
I noticed you're using a private registry.

Can you try `longhornio/longhorn-engine:v0.8.0` instead?

Also, might see if
```
docker run -it longhornio/longhorn-engine:v0.8.0 bash
```
And 
```
docker run -it registry/longhorn-engine:v0.8.0 bash
```
works.

**Comment by HKMglicks** [comment]
@yasker i tried to both commands and the problem which is occurring is the same
error response from daemon: error creating overlay mount to  "/var/lib/docker/overlay2/1bbc14cf2ce4859cb8dc341180b7bff9c80012a847390d2df42fdf2a8633ebbf-init/merged: no such file or directory"

**Comment by yasker** [comment]
There is either something wrong with your docker or your private images. The command should work since it's just a normal Docker image.

**Comment by HKMglicks** [comment]
after bringing down and deleting the images and upgrading the images again in the private repository the overlay is created thanks for your help @yasker
