### ISSUE TITLE
The time zone of pods and nodes  are different,the backup jobs  can not be running at really times ！

### ISSUE THREAD

**Issue by Jawenba** [longhorn/longhorn#1125]
**Describe the bug**
![image](https://user-images.githubusercontent.com/47962033/77135216-6da68880-6aa5-11ea-886d-991514011bd6.png)
Hello, the longhorn pods date is not the same to the nodes ,so the running time is not the time we needed when we create a backup job 。Can the longhorn update the pods used the ENV like follow these:
env:
     - name: LANG
        value: "en_US.UTF-8"
     - name: TZ
       value: "Asia/Shanghai"
Thank you !

**To Reproduce**
1. install longhorn,check the pods used  UTC time,no  the CST+8
2. create a backup job,check the backup running time.

**Expected behavior**
the pods timezone ENV can be defined by users at installing  longhorn from Apps catalog.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

![image](https://user-images.githubusercontent.com/47962033/77137337-6a60cc00-6aa8-11ea-8f81-0488f7dd3053.png)

**Environment:**
 - Longhorn version:v0.6.2
 - Kubernetes version: v1.15.5
 - Node OS type and version: rancheros v1.5.4

**Comment by yasker** [comment]
@Jawenba Longhorn internally is using UTC across the system so we can make sure the timestamps of different logs are in the same timezone so it can be easily cross-checked.

Longhorn uses Kubernetes [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) to schedule backups. According to the Kubernetes document:
>All CronJob schedule: times are based on the timezone of the kube-controller-manager.
>
>If your control plane runs the kube-controller-manager in Pods or bare containers, the timezone set for the kube-controller-manager container determines the timezone that the cron job controller uses.

So the fact Longhorn is using UTC timestamp in the log doesn't impact the running time of the recurring backup jobs.

**Comment by Jawenba** [comment]
@yasker ok,thank you!

**Comment by oomgomgxx** [comment]
你有解决这个问题不？按照他说CronJob用的是UTC，但事实上在业务层面是在时区下操作的，这要怎么处理，设置时区变量吗
