### ISSUE TITLE
[Question] predefine multiple disk?

### ISSUE THREAD

**Issue by y2kenny** [longhorn/longhorn#1126]
Is it possible to predefine multiple disk layout (i.e. having 5 nodes, 3 disk each.  Predefine a config in such a way that the disks show up automatically once longhorn is installed.)

I understand that there's the "Customized Default Setting", is that the way to do it or is there other config objects that I can use to prepopulate the disk/path?

**Comment by yasker** [comment]
@y2kenny We're working on it right now and it will be in v0.8.1 release. You can find the design at https://github.com/longhorn/longhorn/blob/master/enhancements/20200319-default-disks-and-node-configuration.md and the original issue at #1053

**Comment by y2kenny** [comment]
That's great!  Thanks!
