### ISSUE TITLE
[Question] More explanation about the usage of fromBackup parameter in the StorageClass

### ISSUE THREAD

**Issue by anouarchattouna** [longhorn/longhorn#1127]
Hello,

Could you provide some explanations and samples (`nfs` and `s3`) about the usage of `fromBackup` parameter please ?
https://github.com/longhorn/longhorn/blob/dc89143faa4cfbad7e62c161ac57db022282d2c7/chart/templates/storageclass.yaml#L16
Today we can not use some value for that parameter in the chart installation step !

Regards.

**Comment by yasker** [comment]
You can get URL from Longhorn UI -> Backup page -> Backup -> GetURL dropdown.

It will look like
>s3://bucket@us-east-1/backupstore?backup=backup-6ece719d075540a1&volume=pvc-8ec99071-4f91-11ea-9e3d-f23c91575520

**Comment by anouarchattouna** [comment]
And what it does actually. Create all new volumes from that backup ?

**Comment by yasker** [comment]
@anouarchattouna yes. PVC itself doesn't provide a way to specify parameters per volume. Though in the future after we implement https://github.com/longhorn/longhorn/issues/304

**Comment by anouarchattouna** [comment]
Thank you
