### ISSUE TITLE
[Doc] Migrate document from `longhorn/longhorn` to `longhorn/website`

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1131]
We need to migrate docs for v0.8.0 from this repo to `longhorn/website` repo.

For any future releases, we should update the document in `longhorn/website` instead. Docs section in https://github.com/longhorn/website should be the source of truth of documentation for Longhorn.

**Comment by JasonvanBrackel** [comment]
@yasker I don't have access to assign myself.  Please assign me to that.  There are currently 23 docs in the website. Here's the process I'll use.

1. Find the analogous document in the website docs
2. Diff the docs
3. Add information to the website docs assuming the docs in the longhorn repository are currently more up to date. 

There will be two PRs with this.  One in this repository and one in the websites repository.

I'll start the migration today.  Should be done before end of next week, given my current other commitments.

**Comment by yasker** [comment]
Sounds good, assigned, thanks @JasonvanBrackel

**Comment by yasker** [comment]
Done.
