### ISSUE TITLE
[BUG] fsck errors even after reverting to snapshot

### ISSUE THREAD

**Issue by paleozogt** [longhorn/longhorn#1145]
**Describe the bug**

An app started having I/O errors so we brought the pod down.  When we brought it back up, we started seeing 

```
'fsck' found errors on device /dev/longhorn/pvc-6288f5ea-5eea-4524-a84f-afa14b85780d but could not correct them.
```

We went into longhorn's web gui and reverted the volume to a snapshot from before the problem started happening:

![snapshot](https://user-images.githubusercontent.com/310894/77693479-089fd680-6f6e-11ea-86cb-5d37886dcc83.png)

Then we brought the pod back up, but we're still seeing the `fsck` error.  Are snapshots expected to work?

**To Reproduce**

I don't know how to reproduce this error.  We had a volume failure and now we're trying to salvage it with a snapshot, but it isn't working.

**Expected behavior**
Volumes shouldn't be able to go bad like this.  At the very least, we should be able to depend on snapshots to get us out of this problem when volumes go bad.

**Log**

`longhorn-manager`:
```
time="2020-03-26T20:14:47Z" level=debug msg="Prepare to create instance pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-r-2cf41d42"
time="2020-03-26T20:14:47Z" level=info msg="Event(v1.ObjectReference{Kind:\"Replica\", Namespace:\"longhorn-system\", Name:\"pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-r-2cf41d42\", UID:\"789891e1-2118-4119-81cc-016f2d6098e6\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"20190663\", FieldPath:\"\"}): type: 'Normal' reason: 'Start' Starts pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-r-2cf41d42"
time="2020-03-26T20:14:47Z" level=debug msg="Instance pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-r-2cf41d42 starts running, IP 10.42.3.120"
time="2020-03-26T20:14:47Z" level=debug msg="Instance pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-r-2cf41d42 starts running, Port 10030"
time="2020-03-26T20:14:47Z" level=debug msg="Instance handler updated instance pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-r-2cf41d42 state, old state stopped, new state running"
time="2020-03-26T20:14:47Z" level=debug msg="Prepare to create instance pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-e-f763bf66"
time="2020-03-26T20:14:47Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-e-f763bf66\", UID:\"f991a821-73fe-4d2a-9b91-d4cbc370288e\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"20190677\", FieldPath:\"\"}): type: 'Normal' reason: 'Start' Starts pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-e-f763bf66"
time="2020-03-26T20:14:48Z" level=debug msg="Instance process pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-e-f763bf66 had been created, need to wait for instance manager update"
time="2020-03-26T20:14:48Z" level=debug msg="Instance handler updated instance pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-e-f763bf66 state, old state stopped, new state starting"
time="2020-03-26T20:14:50Z" level=debug msg="Instance pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-e-f763bf66 starts running, IP 10.42.3.119"
time="2020-03-26T20:14:50Z" level=debug msg="Instance pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-e-f763bf66 starts running, Port 10000"
time="2020-03-26T20:14:50Z" level=debug msg="Instance handler updated instance pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-e-f763bf66 state, old state starting, new state running"
time="2020-03-26T20:14:50Z" level=debug msg="Start monitoring pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-e-f763bf66"
time="2020-03-26T20:14:50Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"pvc-6288f5ea-5eea-4524-a84f-afa14b85780d\", UID:\"efe26cac-5b8e-4192-abf7-41dcbb73933f\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"20190668\", FieldPath:\"\"}): type: 'Normal' reason: 'Attached' volume pvc-6288f5ea-5eea-4524-a84f-afa14b85780d has been attached to cloud-3"
```

`pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-c-z0m1gb-c`:

```
time="2020-03-24T01:59:38Z" level=debug msg="Cleaned up snapshot c-z0m1gb-f71f01a7 for pvc-6288f5ea-5eea-4524-a84f-afa14b85780d"
time="2020-03-24T01:59:38Z" level=debug msg="Volume pvc-6288f5ea-5eea-4524-a84f-afa14b85780d snapshot purge started"
```

**Environment:**
 - Longhorn version: v0.8.0
 - Kubernetes version: Rancher v2.3.3
 - Node OS type and version: CentOS Linux release 7.4.1708

**Additional context**

We've had a rough time with apps running on longhorn volumes (postgress db's, etc)-- they seem to fail after about a week of usage.  Last time this happened we kicked ourselves for not having snapshots in place.  However, this time around we had snapshtos-- but they don't work!

**Comment by yasker** [comment]
IO issue can be caused by the corrupted data or bad network connection.
1. If it's the corrupted data, can you revert back further to see if it helps?
2. If it's a bad network connection, you should able to see some errors in the `dmesg`.
3. Also, it can be one of replica has gone bad further in the chain, or more likely, the disk one replica is running on has gone bad. In this case, you can try to see if any replica is good using instruction from https://github.com/longhorn/longhorn/issues/469#issuecomment-480963593 to create the block device from other replicas.

**Comment by paleozogt** [comment]
I tried your three approaches:

1. I reverted the volume back a whole week:
![snapshot2](https://user-images.githubusercontent.com/310894/77698288-fb86e580-6f75-11ea-95c9-ac20ad710bc8.png)
Sadly bringing up the pod still has `fsck` errors.
1. I watched dmesg while bringing up the pod but nothing seems wrong:
	```
	[7002957.654694] scsi host94: iSCSI Initiator over TCP/IP
	[7002957.668756] scsi 94:0:0:0: RAID              IET      Controller       0001 PQ: 0 ANSI: 5
	[7002957.688051] scsi 94:0:0:0: Attached scsi generic sg5 type 12
	[7002957.688611] scsi 94:0:0:1: Direct-Access     IET      VIRTUAL-DISK     0001 PQ: 0 ANSI: 5
	[7002957.716179] sd 94:0:0:1: Attached scsi generic sg6 type 0
	[7002957.716221] sd 94:0:0:1: [sdc] 314572800 512-byte logical blocks: (161 GB/150 GiB)
	[7002957.716533] sd 94:0:0:1: [sdc] Write Protect is off
	[7002957.716538] sd 94:0:0:1: [sdc] Mode Sense: 69 00 10 08
	[7002957.726798] sd 94:0:0:1: [sdc] Write cache: enabled, read cache: enabled, supports DPO and FUA
	[7002957.731778] sd 94:0:0:1: [sdc] Attached SCSI disk
	```
1. I tried your clever `launch-simple-longhorn` test on each node of our cluster but got the same result.  Here's a sample from one node:
	```
	$ docker run -it -v /dev:/host/dev -v /proc:/host/proc -v /var/lib/rancher/longhorn/replicas/pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-bf1882fc:/volume --privileged rancher/longhorn-engine:v0.4.1 launch-simple-longhorn test 20g

	...

	$ sudo ./e2fsck -n /dev/longhorn/test
	e2fsck 1.43.1 (08-Jun-2016)
	The filesystem size (according to the superblock) is 39321600 blocks
	The physical size of the device is 5242880 blocks
	Either the superblock or the partition table is likely to be corrupt!
	Abort? no

	/dev/longhorn/test contains a file system with errors, check forced.
	Pass 1: Checking inodes, blocks, and sizes
	Error reading block 11010080 (Invalid argument) while getting next inode from scan.  Ignore error? no

	Error while scanning inodes (11): Can't read next inode
	e2fsck: aborted
	```

It sure seems like whatever's broken about the volume has been replicated to all the nodes.  :(

**Comment by yasker** [comment]
This is weird. The snapshot will be read-only after it's taken.

I noticed the e2fcsk complains about the filesystem size, have you used volume expansion feature recently? Also, I assume the filesystem is ext4.

**Comment by yasker** [comment]
Also, does the app only runs fsck at the beginning or it's always running? The issue might already be there for a long time if the app only runs fsck at the beginning and it continues running for a while.

**Comment by paleozogt** [comment]
I've not done any volume expansion, or any fiddling with the volume.  We created the pod and PVC and just let it run.

I'm not sure what is running `fsck`.  It's not the app inside the pod.  My impression is that `fsck` is running when the volume is attached and that its an automatic thing that kubernetes does.  (For example see [here](https://www.beginswithdata.com/2017/06/23/2017-06-23-fsck-k8s/).)

I don't see anything pop up in `dmesg` when I run `fsck`.

If you mean the file system of the host, it isn't ext4:

```
$ stat --file-system --format=%T /var/lib/rancher/longhorn/
xfs
```

**Comment by yasker** [comment]
Is the disk mountable? Is it possible to revert back to the last time the workload was running?

The superblock reports the disk size is 314572800 block * 4k = 1,258,291,200 which is 1200GiB, but the physical size is 5242880 * 4k = 20GiB (which is specified by the docker run command line). `dmesg` reports 150 GiB . What's the size of the disk?

**Comment by paleozogt** [comment]
Oops you're right I just blindly copied that part of the command over.

Here's the command with 150g:
```
$ sudo docker run -it -v /dev:/host/dev -v /proc:/host/proc -v /var/lib/rancher/longhorn/replicas/pvc-6288f5ea-5eea-4524-a84f-afa14b85780d-bf1882fc:/volume --privileged rancher/longhorn-engine:v0.4.1 launch-simple-longhorn test 150g
+ set -e
+ mount --rbind /host/dev /dev
+ volume=test
+ size=150g
+ frontend=
+ '[' -z test ']'
+ '[' -z 150g ']'
+ '[' -z ']'
+ echo Use default frontend TGT block device
Use default frontend TGT block device
+ frontend=tgt-blockdev
+ launcher='longhorn controller'
+ extra_opts=
+ [[ tgt-blockdev == \t\g\t\-* ]]
+ launcher='longhorn-engine-launcher start'
+ extra_opts='--size 150g'
+ sleep 1
+ longhorn replica --size 150g --listen 0.0.0.0:9502 /volume/
INFO[0000] Listening on data 0.0.0.0:9503
INFO[0000] Listening on sync agent 0.0.0.0:9504
INFO[0000] Listening on control 0.0.0.0:9502
INFO[0000] Listening on sync 0.0.0.0:9504
+ exec longhorn-engine-launcher start --listen 0.0.0.0:9501 --frontend tgt-blockdev --replica tcp://0.0.0.0:9502 --size 150g test
INFO[0000] launcher: controller 64752064-070f-4f15-b38b-9acafe34757b started
INFO[0000] Starting with replicas ["tcp://0.0.0.0:9502"]
INFO[0000] Connecting to remote: 0.0.0.0:9502
INFO[0000] Opening: 0.0.0.0:9502
INFO[0001] New connection from: 127.0.0.1:34268
INFO[0001] Opening volume /volume/, size 161061273600/512
127.0.0.1 - - [26/Mar/2020:23:09:57 +0000] "POST /v1/replicas/1?action=open HTTP/1.1" 200 9598 "" "Go-http-client/1.1"
INFO[0000] Adding backend: tcp://0.0.0.0:9502
INFO[0000] Set replica tcp://0.0.0.0:9502 to mode RW
INFO[0000] Start monitoring tcp://0.0.0.0:9502
INFO[0000] Get backend tcp://0.0.0.0:9502 revision counter 13669772
WARN[0001] Failed to find dockerd in the process ancestors, fall back to use pid 1: Failed to find the ancestor process: dockerd
WARN[0001] Failed to find dockerd in the process ancestors, fall back to use pid 1: Failed to find the ancestor process: dockerd
tgtd: iser_ib_init(3431) Failed to initialize RDMA; load kernel modules?
tgtd: work_timer_start(146) use timer_fd based scheduler
tgtd: bs_init(387) use signalfd notification
tgtd: device_mgmt(246) sz:74 params:path=/var/run/longhorn-test.sock,bstype=longhorn,bsopts=size=161061273600
tgtd: bs_thread_open(409) 16
INFO[0002] New data socket connnection established
INFO[0002] Creating device /dev/longhorn/test 8:32
INFO[0002] launcher: Device /dev/longhorn/test is ready
INFO[0002] launcher: SCSI device /dev/sdc created
INFO[0002] Listening on 0.0.0.0:9501
```

Oddly that doesn't seem to have changed the fsck results (!):

```
$ sudo ./e2fsck -n /dev/longhorn/test
e2fsck 1.43.1 (08-Jun-2016)
The filesystem size (according to the superblock) is 39321600 blocks
The physical size of the device is 5242880 blocks
Either the superblock or the partition table is likely to be corrupt!
Abort? no

/dev/longhorn/test contains a file system with errors, check forced.
Pass 1: Checking inodes, blocks, and sizes
Error reading block 11010080 (Invalid argument) while getting next inode from scan.  Ignore error? no

Error while scanning inodes (11): Can't read next inode
e2fsck: aborted
```

**Comment by yasker** [comment]
`The physical size of the device is 5242880 blocks` indicates the size is still wrong. You should able to see the size in the `dmesg` when running the `docker run` command. It's maybe a side effect of last time `docker run` command.

You can make a copy of three replicas' data, and experimenting on the copy instead, to keep the original data safe. Use `longhorn snapshot info` and `longhorn snapshot revert` in the docker container running with the copy of the data (e.g. `docker exec xxx -it bash`) will get you direct command line access to the volume. You should able to revert to the newer snapshot in the command line then. Revert to another snapshot should eliminate the side effect of the last `docker run` command.

**Comment by paleozogt** [comment]
I did `longhorn snapshot revert` in the container like you suggested.  No matter which snapshot I go to I see errors:

```
$ sudo ./e2fsck -n /dev/longhorn/test
e2fsck 1.43.1 (08-Jun-2016)
/dev/longhorn/test was not cleanly unmounted, check forced.
Resize inode not valid.  Recreate? no

Pass 1: Checking inodes, blocks, and sizes
Inode 7, i_blocks is 122888, should be 8.  Fix? no

HTREE directory inode 2752840 has an invalid root node.
Clear HTree index? no

Inode 2754055 has an invalid extent node (blk 11042901, lblk 0)
Clear? no

Inode 2754055 extent tree (at level 1) could be shorter.  Fix? no

Inode 2754055, i_blocks is 136, should be 0.  Fix? no

Inode 2754107 has an invalid extent node (blk 11049459, lblk 0)
Clear? no
```

**Comment by yasker** [comment]
Sounds like the disk was corrupted about one week ago. Is it possible to fix it using fsck?

**Comment by paleozogt** [comment]
`fsck` can "fix" it, in that the mounting errors go away.  But it leaves a ton of unreadable/unwritable paths behind (only some of which are in `lost+found`).  So while its technically repaired from fsck's point-of-view, its unusable.

**Comment by yasker** [comment]
Understand. Snapshots and backups are still needed to keep the data safe.

**Comment by paleozogt** [comment]
But that's exactly my point.  I *did* make snapshots, but all of them are broken.  The application worked fine for weeks and then died.  Even when I go back to snapshots from when the app was working the fsck problem is still there.

**Comment by yasker** [comment]
@paleozogt Sorry to take so long to get back to you.
 
I am keeping think how can we help users to systematically identify and recover the issue like this. I've written some documentation for that.

In your case, I think it's possible that one of your replicas went bad (due to disk or something else). So if you take a look at the instruction [here](https://github.com/yasker/longhorn/wiki/Troubleshooting-the-data-corruption-%5BDRAFT%5D) , you might able to figure out if it's one of the replicas went bad, result in the error.

I know it has been so long and not sure if it's still helpful to you. But it will be great if you can take a look and let me know what do you think.
