### ISSUE TITLE
[Question] Rancher Retain the volume for manual cleanup

### ISSUE THREAD

**Issue by yl-yue** [longhorn/longhorn#1148]
![image](https://user-images.githubusercontent.com/39790401/77894358-bf21f500-72a7-11ea-9c0e-14ebf5da5fc9.png)

**Comment by yasker** [comment]
It's the default Storage Class who supports this option. It cannot be updated once created.

You can create another storage class with the customized options to use, instead of using the default one.

**Comment by yl-yue** [comment]
> It's the default Storage Class who supports this option. It cannot be updated once created.
> 
> You can create another storage class with the customized options to use, instead of using the default one.

Thank you for lifting my doubts, thank you!
