### ISSUE TITLE
[FEATURE] Scale down Longhorn nodes with Kubernetes

### ISSUE THREAD

**Issue by dkeightley** [longhorn/longhorn#1151]
**Is your feature request related to a problem? Please describe.** Deleting a node from Longhorn outside of the UI involves a number of unique steps

**Describe the solution you'd like** Simplified process for deleting node during a rolling update of nodes in the cluster, when using kubectl to self-drain the node and delete itself from the cluster, having the ability to delete the node via it's CRD object would provide a universal approach

**Describe alternatives you've considered** API calls to the Longhorn API

**Comment by yasker** [comment]
I am thinking we can add a setting to allow automatically delete the node if it's deleted from Kubernetes.

**Comment by yasker** [comment]
Need to consider the design with #1269

**Comment by yasker** [comment]
Move out to v1.1.0 due to we need to redesign the feature due to the user may want to retain the disk on the new nodes, e.g. extra EBS volume. See #1269

**Comment by yasker** [comment]
Retain metadata of disk or not can be implemented as a flag for each disk, with a global default setting.

**Comment by yasker** [comment]
In order to implement this feature, we will need to promote disk to the first-class object.

**Comment by yasker** [comment]
The automatic removal of the node feature has been implemented in Longhorn v1.1.0.
