### ISSUE TITLE
[BUG] The failure of auto-remounting volume will block the process of volume reconciliation 

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1156]
**Describe the bug**
According to the log, failed to auto-remount the disk blocking the process of volume reconciliation
https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go#L981 

**To Reproduce**
Potential steps to reproduce the behavior:
1. Create a new pod with Longhorn volume, setup volume recovery according to https://github.com/longhorn/longhorn/blob/master/docs/recover-volume.md
2. Intentionally corrupt the filesystem of the disk then detach the volume.
3. Observe the log
4. Delete a replica to trigger the rebuild process. Rebuild cannot complete due to volume controller was blocked

**Expected behavior**
Even when the volume cannot be auto-remount, it shouldn't stop the whole volume reconciliation process from working.

**Log**
```
2020-04-01T15:57:33.786971919Z time="2020-04-01T15:57:33Z" level=warning msg="Dropping Longhorn volume longhorn-system/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d out of the queue: fail to sync longhorn-system/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d: fail to reconcile volume state for pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d: Failed to execute: nsenter [--mount=
/host/proc/1/ns/mnt --net=/host/proc/1/ns/net mount /dev/longhorn/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d /var/lib/kubelet/pods/239c6198-06d1-4d1b-8d36-9d2f17b1c687/volumes/kubernetes.io~csi/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d/mount], output mount: /dev/longhorn/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d: can't read superblock\n, error exit status 32"
2020-04-01T15:57:50.34471315Z time="2020-04-01T15:57:50Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d: fail to sync longhorn-system/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d: fail to reconcile volume state for pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d: Failed to execute: nsenter [--mount=/host/proc/1/
ns/mnt --net=/host/proc/1/ns/net mount /dev/longhorn/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d /var/lib/kubelet/pods/239c6198-06d1-4d1b-8d36-9d2f17b1c687/volumes/kubernetes.io~csi/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d/mount], output mount: /dev/longhorn/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d: can't read superblock\n, error exit status 32"
2020-04-01T15:57:53.757445771Z time="2020-04-01T15:57:53Z" level=debug msg="Skip rebuilding for volume pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d because there is rebuilding in process"
2020-04-01T15:58:06.619540991Z E0401 15:58:06.619376       1 volume_controller.go:206] fail to sync longhorn-system/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d: fail to reconcile volume state for pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net mount /dev/longhorn/pvc-88d5b731-9af8-432d-99
ff-df08e9c62c4d /var/lib/kubelet/pods/239c6198-06d1-4d1b-8d36-9d2f17b1c687/volumes/kubernetes.io~csi/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d/mount], output mount: /dev/longhorn/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d: can't read superblock
```

**Environment:**
 - Longhorn version: v0.8.0
 - Kubernetes version: v1.17.4
 - Node OS type and version: Unknown

**Comment by yasker** [comment]
Test steps:
1. Use https://github.com/longhorn/longhorn/blob/master/examples/deployment.yaml to create a pod and volume.
2. Corrupt the disk using following command on the attached node
```
dd if=/dev/zero of=/dev/longhorn/<vol-name> bs=1 seek=1108 count=4
```
(See https://ext4.wiki.kernel.org/index.php/Ext4_Disk_Layout#The_Super_Block `0x54`)
The above command makes sure the `blkid` command still recognizes the filesystem but mount command will fail.
3. Delete the engine process using `kill` in the instance-manager-e-xxxx. This will trigger remount process.

#### Before the fix:
Log reports error like 
> 2020-04-01T15:57:50.34471315Z time="2020-04-01T15:57:50Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d: fail to sync longhorn-system/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d: fail to reconcile volume state for pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d: Failed to execute: nsenter [--mount=/host/proc/1/
ns/mnt --net=/host/proc/1/ns/net mount /dev/longhorn/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d /var/lib/kubelet/pods/239c6198-06d1-4d1b-8d36-9d2f17b1c687/volumes/kubernetes.io~csi/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d/mount], output mount: /dev/longhorn/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d: cannot mount; probably corrupted filesystem /dev/longhorn/pvc-ecfe61b4-4d4b-47f7-8066-e5221f219d09\n, error exit status 32"

and

>2020-04-01T15:57:33.786971919Z time="2020-04-01T15:57:33Z" level=warning msg="Dropping Longhorn volume longhorn-system/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d out of the queue: fail to sync longhorn-system/pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d: fail to reconcile volume state for pvc-88d5b731-9af8-432d-99ff-df08e9c62c4d:

And volume cannot be detached.

#### After the fix:
Error message:
>[longhorn-manager-5jjv4] time="2020-04-06T21:36:02Z" level=info msg="Event(v1.ObjectReference{Kind:"Volume", Namespace:"longhorn-system", Name:"pvc-ecfe61b4-4d4b-47f7-8066-e5221f219d09", UID:"4e6d6179-75ab-427c-8f65-e7c4b19b434a", APIVersion:"longhorn.io/v1beta1", ResourceVersion:"73684576", FieldPath:""}): type: 'Warning' reason: 'Remount' cannot proceed to remount pvc-ecfe61b4-4d4b-47f7-8066-e5221f219d09 on yasker-longhorn-dev-2: Failed to execute: nsenter [--mount=/host/proc/617/ns/mnt --net=/host/proc/617/ns/net mount /dev/longhorn/pvc-ecfe61b4-4d4b-47f7-8066-e5221f219d09 /var/lib/kubelet/pods/fda729c5-da99-4f72-b03c-80bd8e11b16f/volumes/kubernetes.io~csi/pvc-ecfe61b4-4d4b-47f7-8066-e5221f219d09/mount], output , stderr, mount: /var/lib/kubelet/pods/fda729c5-da99-4f72-b03c-80bd8e11b16f/volumes/kubernetes.io~csi/pvc-ecfe61b4-4d4b-47f7-8066-e5221f219d09/mount: cannot mount; probably corrupted filesystem on /dev/longhorn/pvc-ecfe61b4-4d4b-47f7-8066-e5221f219d09.n, error exit status 32

Only the first error message is shown. There isn't message to drop volume reconiliation.
And volume can be detached.

#### Follow up:

If run `fsck` on the block device exposed by the volume, it can be fixed and the log should show remount complete. The workload should recover shortly (after the retry period passed).

**Comment by meldafrawi** [comment]
Validation: **FAILED after upgrade**

Steps to test:
- Install Longhorn v0.7.0
- Upgrade to Longhorn `master`
- Use https://github.com/longhorn/longhorn/blob/master/examples/deployment.yaml to create a pod and volume.
- Corrupt the disk using following command on the attached node
`dd if=/dev/zero of=/dev/longhorn/<vol-name> bs=1 seek=1108 count=4`
- Delete the engine process using kill in the instance-manager-e-xxxx. This will trigger remount process.

Result: 
Volume goes to detaching/attaching Loop.

**Comment by yasker** [comment]
@meldafrawi I cannot reproduce the issue following the steps. Can you provide logs?

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test (1/2):
- Install Longhorn v0.7.0
- Upgrade to Longhorn `master`
- Use https://github.com/longhorn/longhorn/blob/master/examples/deployment.yaml to create a pod and volume.
- Write data to pod and compute it's checksum.
- Corrupt the disk using following command on the attached node
`dd if=/dev/zero of=/dev/longhorn/<vol-name> bs=1 seek=1108 count=4`
- Use SIGINT to kill engine process
- Volume will be attached, but deployment pod failed to start due to filesystem corruption.
- Use fsck to fix volume filesystem
- Deployment pod should start volume data should be accessible and checksum should match. (**PASSED**)

Steps to test (2/2):
- Install Longhorn using  `master` images
- Use https://github.com/longhorn/longhorn/blob/master/examples/deployment.yaml to create a pod and volume.
- Write data to pod and compute it's checksum.
- Corrupt the disk using following command on the attached node
`dd if=/dev/zero of=/dev/longhorn/<vol-name> bs=1 seek=1108 count=4`
- Use SIGINT to kill engine process
- Volume will be attached, but deployment pod failed to start due to filesystem corruption.
- Use fsck to fix volume filesystem
- Deployment pod should start,  volume data should be accessible and checksum should match (**PASSED**)
