### ISSUE TITLE
[Doc] Best practice guide

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1159]
Need the best practice guide for Longhorn. 

Recommended settings. Replica count, what's the underlying disk structure, recurring snapshot/backup etc

**Comment by yasker** [comment]
Available at https://github.com/yasker/longhorn/wiki/Best-practices-for-deploying-Longhorn-in-production for now. Will move to the doc later.

**Comment by yasker** [comment]
@catherineluse Can you help to move the guide at https://github.com/yasker/longhorn/wiki/Best-practices-for-deploying-Longhorn-in-production to the website?

**Comment by catherineluse** [comment]
The best practices guide has been added to the staging branch of the Longhorn website. https://github.com/longhorn/website/pull/102

**Comment by yasker** [comment]
Done.

**Comment by yasker** [comment]
I cannot find the merged PR https://github.com/longhorn/website/pull/102

**Comment by catherineluse** [comment]
I think we can close this issue because it's in staging now. https://staging.longhorn.io/docs/0.8.1/best-practices/
