### ISSUE TITLE
[FEATURE] Add replica name to the backup status

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1166]
Make it easier to find which replica is doing the backup.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

- Create a pod using Longhorn volume
- write some data to the volume
- Create a snapshot
- Create a backup, snapshot should be created, and backup progress should be visible in percentage 
- In Volume Details page, Snapshots section, hovering over snapshot will show replica name that is used to create the snapshot. (PASS)
