### ISSUE TITLE
Add FromReplica for the RebuildStatus

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1167]
Then we can identify the replica that is sending the data over.

**Comment by shuo-wu** [comment]
Test step:
1. Launch a workload with Longhorn volume. Write 1Gi random data to the volume.
2. Delete a replica, then check `rebuildStatus` in the Longhorn API page:
`<Longhorn URL>/v1/volumes/<volume name>`
3. Find and delete`rebuildStatus.fromReplica` during the rebuilding. The rebuilding replica will be directly removed, too. And volume will restart rebuilding 2 replicas. 
4. After the rebuilding, check the volume content.

**Comment by yasker** [comment]
Need more details for UI.

**Comment by yasker** [comment]
And now we can improve this test case: https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_ha.py#L697

**Comment by shuo-wu** [comment]
If `volume.rebuildStatus[index].state == "in_progress"`, UI needs to present `volume.rebuildStatus[index].fromReplica` in a new field `FromReplica` for the rebuilding replica.

Add UI need to add a hover to explain the newly introduced field `FromReplica`:
```
The replica that is sending the data to this rebuilding replica.
``` 

The example for the updated `rebuildStatus`:
```
"rebuildStatus": [
  {
    "actions": null,
    "error": "",
    "fromReplica": "pvc-1775bb1b-bf25-4c07-8089-e226235a0a01-r-b049bfc0",
    "isRebuilding": true,
    "links": null,
    "progress": 6,
    "replica": "pvc-1775bb1b-bf25-4c07-8089-e226235a0a01-r-1b336fa3",
    "state": "in_progress",
  },
],
```

**Comment by yasker** [comment]
Seems we have some bugs in the backend if the replicas are all on the same node

I've also seen the progress bar show up in the source replica instead of target replica, when replicas are on the same node.

From @ly5156

![image (10)](https://user-images.githubusercontent.com/3344618/79597015-5fdd2680-8096-11ea-956e-6c9af03fd3ab.png)

**Comment by yasker** [comment]
@shuo-wu UI is merged. To reproduce the single node replica rebuild issue:

1. Create a volume. Add some data to it. Reduce replica count to 2.
2. Delete one replica to trigger rebuild. It will show it's rebuilding from itself.

**Comment by shuo-wu** [comment]
The above bug is tracked by #1220

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
- Create a volume, and attach it to a node
- Delete a replica, a new replica should start to rebuild.
- Hover over replica, a tooltip state `Synchronizing from Replica: <REPLICA_NAME>`
