### ISSUE TITLE
[Question] Remove backup manually

### ISSUE THREAD

**Issue by scottrobertson** [longhorn/longhorn#1170]
We had to delete the volume backup files manually on the disk during an incident that required us to need disk space very urgently. 

This has resulted in Longhorn backups being stuck, with no option to remove them. When we try via the UI, this happens:

```
fail to delete snapshot: error deleting snapshot 'backup-92130cae': Failed to execute: /var/lib/rancher/longhorn/engine-binaries/longhornio-longhorn-engine-v0.7.0/longhorn [--url 10.42.6.76:10001 snapshot rm backup-92130cae], output , stderr, Failed to delete backup-92130cae: failed to mark disk backup-92130cae as removed for replica 10.42.8.165:10030: rpc error: code = Unknown desc = Fail to mark disk volume-snap-backup-92130cae.img as removed: Cannot find disk file volume-snap-backup-92130cae.img time="2020-04-09T16:16:53Z" level=fatal msg="Error running rm snapshot command: failed to mark disk backup-92130cae as removed for replica 10.42.8.165:10030: rpc error: code = Unknown desc = Fail to mark disk volume-snap-backup-92130cae.img as removed: Cannot find disk file volume-snap-backup-92130cae.img" , error exit status 1
```

How can we manually remove them from Longhorn?

**Comment by yasker** [comment]
What have you deleted exactly? The files in the replica directories are not backups. It contains the current volume data.

**Comment by scottrobertson** [comment]
@yasker the `volume-snap-*` files basically. 

I have removed the volumes and started again anyway, so don't worry too much about that data.

Just need a way to remove the old backups from the Longhorn UI/System.

**Comment by scottrobertson** [comment]
Just to explain what happened.

Backups were misconfigured and were stacking up way too much. Noticed too late, and k8s started to kill pods (including longhorn) due to disk pressure. This meant I could not remove backups via the UI, so I had to do something, and removing those files manually helped. Things ran fine but I removed the volumes entirely and started again just in case.

**Comment by yasker** [comment]
@scottrobertson those are the volume data, so if you remove them, I will not expect volume to be functional.

There is a difference between snapshots and backups in Longhorn. Snapshots are stored as a part of volume data inside the cluster, while the backups are the extra copies of data stored somewhere else, e.g. S3 server. Sound like you're talking about snapshots.

If you want to remove snapshots without UI, you can follow the instruction at https://github.com/longhorn/longhorn/issues/1010#issuecomment-573899942 (we should document it)

**Comment by scottrobertson** [comment]
@yasker thanks. Unfortunately, they do the same. The commands run, but nothing happens:

```
lhexec pvc-7cd1a662-a85f-42ed-89ef-4b5e5cfef66a snapshot ls
ID
520e6731-e937-49b1-aed8-c0b6c67f5fa3
backup-92130cae
backup-6165d3a4

lhexec pvc-a008f4bf-ee9d-40a2-82e7-62c8c6cb95f0 snapshot rm backup-92130cae
lhexec pvc-a008f4bf-ee9d-40a2-82e7-62c8c6cb95f0 snapshot rm backup-6165d3a4
lhexec pvc-7cd1a662-a85f-42ed-89ef-4b5e5cfef66a snapshot ls

ID
520e6731-e937-49b1-aed8-c0b6c67f5fa3
backup-92130cae
backup-6165d3a4
```

Plus, for the volumes I have removed, I cannot delete via this method as it just returns that the volume is not found.

**Comment by scottrobertson** [comment]
@yasker thank you.

Unfortunately doing via CLI fails too:

```
lh pvc-7cd1a662-a85f-42ed-89ef-4b5e5cfef66a snapshot rm backup-92130cae

Failed to delete backup-92130cae: failed to mark disk backup-92130cae as removed for replica 10.42.8.165:10030: rpc error: code = Unknown desc = Fail to mark disk volume-snap-backup-92130cae.img as removed: Cannot find disk file volume-snap-backup-92130cae.img
FATA[0000] Error running rm snapshot command: failed to mark disk backup-92130cae as removed for replica 10.42.8.165:10030: rpc error: code = Unknown desc = Fail to mark disk volume-snap-backup-92130cae.img as removed: Cannot find disk file volume-snap-backup-92130cae.img
command terminated with exit code 1
```

**Comment by dberardo-com** [comment]
i have some backups that are empty, why are they still showing in the table inside the ui ? is it possible to remove them completely ?

**Comment by derekbit** [comment]
> i have some backups that are empty, why are they still showing in the table inside the ui ? is it possible to remove them completely ?

@dberardo-com 
Can you create a new ticket with the required information? Thanks.

**Comment by mantissahz** [comment]
Hi @dberardo-com,

Could you elaborate on the steps that delete the backups and provide the pic that `they are still showing in the table inside the ui`?
Which Longhorn version do you use now, and could you provide the information about your environment?

>i have some backups that are empty,

What do you mean that backups are empty?
Could you show the result using this command?
```shell
kubectl -n longhorn-system get backups,snapshots
```

**Comment by dberardo-com** [comment]
i am using v1.9.2 here one example:

a backup that contains no backups (i.e. i have deleted them all one by one manually, as "delete all backups" was doing nothing): 

<img width="1863" height="221" alt="Image" src="https://github.com/user-attachments/assets/be12fe38-d9b1-45b7-9cfb-97a87e3d1cdc" />

but the backup still shows in the table and i dont know how to get rid of it:

<img width="1353" height="291" alt="Image" src="https://github.com/user-attachments/assets/e7629cdc-ba1d-4815-8be6-ce470758562e" />

also i have pressed multiple times the £sync all backups" volume and nothing has changed

**Comment by mantissahz** [comment]
It's a backup volume.
When you create a backup of a volume, a `backup volume` named as the volume is created on the backup target where the backup is stored. The following backups of the volume will be listed in this backup volume.
If the backups in this backup volume are all deleted, you can delete this backup volume directly on the `Backup` page.

https://longhorn.io/docs/1.9.2/snapshots-and-backups/backup-and-restore/synchronize_backup_volumes_manually/

**Comment by dberardo-com** [comment]
i am sorry but i dont see any option to delete the backup volume manually:

<img width="2855" height="1346" alt="Image" src="https://github.com/user-attachments/assets/b268f437-0084-43b2-8d1e-04ccdbf8bde3" />

i did try click on Sync backup volume but the bVolume is still there after sync. should i remove the folder in the s3 bucket containing the backups manually and then try to resync from the longhorn GUI ? i am a bit lost.

EXTRA INFO: might this have to do with the fact that i see some backup as 15days old in this section, even though from within the volume page itself i can see a more recent timestamp?  As in, is it possible there is some caching issue somewhere ? 

<img width="1441" height="529" alt="Image" src="https://github.com/user-attachments/assets/ce117f92-35bb-4ac3-acb2-54e4e5f00363" />

<img width="1782" height="1104" alt="Image" src="https://github.com/user-attachments/assets/906c0a0a-75d9-47e5-9535-d6ea8cb1fa6d" />
