### ISSUE TITLE
[FEATURE]UI: Add `Activate Disaster Recovery Volume` button to the batch operation

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1171]
We need to have it similar to other actions.

Only works if the volumes selected are DR volumes (same condition as the separate action)

And after created the DR volume in the backup volume page, don't jump to the volume list page.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

- Create a pod using Longhorn volume
- Write some data to volume, compute its checksum (checksum#2)
- Create a backup (backup#1)
- Create multiple disaster recovery volumes from (backup#1)
- Write some more data to volume and compute its checksum (checksum#2)
- Create a backup (backup#2)
- DR volumes should start restoring from (backup#2)
- Select both DR volumes, activate them at one, volumes continue restoring latest backup (backup#2), then get detached
- Attach volume to nodes and check it's checksum, checksum should match (checksum#2) **(PASSED)**
