### ISSUE TITLE
[BUG] backupstore: NFS mount point is reused incorrectly, result in NFS client hang

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1177]
The backupstore code only checked if the directory was mounted before reuse it.

https://github.com/longhorn/backupstore/blob/master/nfs/nfs.go#L81

Higher version of NFS specified which client IP can be used to connect to the NFS server, result in NFS backupstore returns no response if the manager pod was recreated and assigned a different IP.

To reproduce:
1. Start NFS server using https://github.com/longhorn/longhorn/blob/master/deploy/backupstores/nfs-backupstore.yaml
2. Use the NFS server as the backup target
3. Use UI to access the backup page.
4. Delete the manager pods and let it recreate.
5. Try to access the backup page again.

Result:
Timeout.

Expect result:
Should be accessible.

Log:
Manager log:
>[longhorn-manager-pj775] time="2020-04-10T22:39:19Z" level=warning msg="backup store monitor: failed to list backup volumes in nfs://longhorn-test-nfs-svc.default:/opt/backupstore: error listing backup volumes: Timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master/longhorn [backup ls --volume-only nfs://longhorn-test-nfs-svc.default:/opt/backupstore], output , stderr, , error <nil>"

Workaround:
After the pod restarted, umount the NFS mount on the node using `umount --force`

**Comment by yasker** [comment]
It's a by-product of moving Longhorn directory to `/var/lib/longhorn`. The default mount directory is `/var/lib/longhorn/mounts`, which accidentally results in mount propagation to the host directory and shared across different Longhorn managers.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
1. Start NFS server using https://github.com/longhorn/longhorn/blob/master/deploy/backupstores/nfs-backupstore.yaml
2. Use the NFS server as the backup target
3. Use UI to access the backup page.
4. Delete the manager pods and let it recreate.
5. Try to access the backup page again. (backup page is accessible.)
