### ISSUE TITLE
[BUG] Persistence Volume can not be released after hard server crash

### ISSUE THREAD

**Issue by rsoika** [longhorn/longhorn#1179]
I am running longhorn 0.8.0 on a self managed kubernetes cluster with one master node and 3 worker nodes. I observe the following behavior:

**To Reproduce**
I have deployed a pod bound to a longhorn volume. The volume is replicated 3 times, one replica on each worker node. For example my service (postgresdb) runs on worker-node-2. Also the volume 'dbdata' is attached to worker-node-2.

1. Now I do a hard shutdown on worker-node-2 (power off)
2. Longhorn is recognizing the missing node and states "limited node redundancy". 
3. after 5 minutes (default) kubernetes terminates the pod on worker-node-2  and tries to reschedule it on worker node 3.

But this failed with the following warning:

```
Warning  FailedAttachVolume  70s
        attachdetach-controller  Multi-Attach error for volume "demo-dbdata-pv" 
        Volume is already used bypod(s) db-698f854874-7cp5f
```

Now the pod db-698f854874-7cp5f on worker-node-2 is permanent in terminating status and the new pod on worker-node-3 hangs for ever and did not start. 

When I finally (after 3 more minutes) kill the pod which is in terminating status:

4. longhorn detached the volume, 
5. creates a new (2nd) replica on node 3.
6. and finally the pod is starting again. 

**Expected behavior**
I would expect, that the old pod will complete terminating and the volume can be detached

**Environment:**
 - Longhorn version: 0.8.0
 - Kubernetes version: 1.17.3
 - Node OS type and version: Debian buster

I am not sure if this is already known as I found similar issues like 1169 , 1156

Please let me know if I can provide some more information or if I should test a nightly build.

**Comment by yasker** [comment]
@rsoika This is a current limitation of the system caused by Kubernetes. See https://github.com/longhorn/longhorn/blob/master/docs/node-failure.md for details.

We're trying to develop a better way for user to use it without deleting the pod manually. We're tracking the effort at https://github.com/longhorn/longhorn/issues/1105

**Comment by rsoika** [comment]
ok thanks.
