### ISSUE TITLE
[Doc] Add NFS-on-Longhorn documentation

### ISSUE THREAD

**Issue by bgulla** [longhorn/longhorn#1183]
As a user of Longhorn, I would like to know how I can help support the applications I deploy that require RWX. It has been brought to my attention that running an NFS layer atop longhorn will facilitate that type of use case. Can we add supporting documentation to help walk through users in the setup of this approach?

**Comment by yasker** [comment]
Depends on the result of https://github.com/longhorn/longhorn/issues/1105

**Comment by yasker** [comment]
We need a test plan for NFS. Ideally, we should test it end to end for the workload cases.

**Comment by joshimoo** [comment]
## Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged?
The PR is at

* [ ] Is the reproduce steps/test steps documented?

* [ ] **If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at

* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at

* [ ] **if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at 

* [ ] **If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at

* [ ] **if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at

* [ ] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at

**Comment by yasker** [comment]
One additional thing to consider is when after we implement #1470 , it should be easy for the user to upgrade. My biggest concern is if the user can use the same StorageClass name `longhorn-nfs` in the later version and seamlessly migrate to the new solution.

**Comment by khushboo-rancher** [comment]
Validation - **Passed**

Followed the docs https://staging.longhorn.io/docs/1.0.0/advanced-resources/rwx-workloads/ example workloads are coming up healthy properly.
The links of yamls are broken currently but will be fixed with https://github.com/longhorn/website/pull/159/files

RWX functionality is working fine.
Test cases executed from https://rancher.atlassian.net/wiki/spaces/LON/pages/515376490/RWX+Volumes

**Comment by jaredkipe** [comment]
This is great! Except that I've now spent a lot of time extracting the state out of some apps into s3/minio (+redis for some things) and you suddenly give me an easier way.

FWIW, I did try NFS provisioner on-top of a longhorn volume, and I had some inconsistent results.  e.g. I STILL have a stuck pod on a production cluster that cannot be removed for some reason and it was part of that experiment. 

I will try the longhorn built in when ready.

**Comment by joshimoo** [comment]
@jaredkipe Did you try the longhorn provided nfs provisioner deployment?

> FWIW, I did try NFS provisioner on-top of a longhorn volume, and I had some inconsistent results. e.g. I STILL have a stuck pod on a production cluster that cannot be removed for some reason and it was part of that experiment.

@jaredkipe Was this using the longhorn provided nfs-provisioner deployments that will be released with 1.0.1?

**Comment by jaredkipe** [comment]
@joshimoo No, I mean like a year ago on one cluster and 6 months ago on another.

**Comment by joshimoo** [comment]
@khushboo-rancher added a tracking issue for the e2e integration tests #1606 can you close this issue?
