### ISSUE TITLE
[BUG] Longhorn should not be allowed to be deployed more than once in a cluster

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1189]
**Describe the bug**
Longhorn should not be allowed to be deployed more than once in a cluster

**To Reproduce**

1. From Rancher, deploy Longhorn app - **longhorn1**
2. Longhorn is deployed successfully
3. Redeploy longhorn app - **longhorn2**
4. No workloads in longhorn2 will be deployed but the app is seen Active
5. Delete **longhorn2**
6. Longhorn1 app's workloads get deleted. 

**Expected behavior**
Longhorn should not be allowed to deploy/install multiple times in a cluster. It should be deployed only once.

**Environment:**
 - Longhorn version: 0.8.0
 - Kubernetes version: 1.17.4
 - Node OS type and version: RKE DO cluster

**Comment by yasker** [comment]
Tracking at Rancher using https://github.com/rancher/rancher/issues/26627

**Comment by sowmyav27** [comment]
Trying to deploy longhorn through kubectl in a cluster, which already has Longhorn installed gives:
```
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
namespace/longhorn-system unchanged
serviceaccount/longhorn-service-account unchanged
clusterrole.rbac.authorization.k8s.io/longhorn-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/longhorn-bind unchanged
customresourcedefinition.apiextensions.k8s.io/engines.longhorn.io unchanged
customresourcedefinition.apiextensions.k8s.io/replicas.longhorn.io unchanged
customresourcedefinition.apiextensions.k8s.io/settings.longhorn.io unchanged
customresourcedefinition.apiextensions.k8s.io/volumes.longhorn.io unchanged
customresourcedefinition.apiextensions.k8s.io/engineimages.longhorn.io unchanged
customresourcedefinition.apiextensions.k8s.io/nodes.longhorn.io unchanged
customresourcedefinition.apiextensions.k8s.io/instancemanagers.longhorn.io unchanged
configmap/longhorn-default-setting unchanged
daemonset.apps/longhorn-manager unchanged
service/longhorn-backend unchanged
deployment.apps/longhorn-ui unchanged
service/longhorn-frontend configured
deployment.apps/longhorn-driver-deployer unchanged
storageclass.storage.k8s.io/longhorn unchanged
```

**Comment by yasker** [comment]
It seems was fixed in Rancher.

**Comment by yasker** [comment]
@sowmyav27 Can we close this bug?

**Comment by sowmyav27** [comment]
Fixed in rancher - https://github.com/rancher/rancher/issues/26627
