### ISSUE TITLE
[BUG] "Longhorn Static StorageClass Name" is not a Required field in the settings page

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1191]
**Describe the bug**
"Longhorn Static StorageClass Name" is not a Required field in the settings page

**To Reproduce**

- In the settings page in Longhorn UI, Leave the "Longhorn Static StorageClass Name" - blank (no value) and Save
- Create a volume and Create PV and PVC.
- Error is seen while creating PV/PVC
`unable to create PV for volume new-4: failed to get longhorn static storage class name for PV new-4 creation: setting default-longhorn-static-storage-class is empty`

**Expected behavior**
"Longhorn Static StorageClass Name" should be a Required field in the settings page

**Environment:**
 - Longhorn version: 0.8.0
 - Kubernetes version: 1.17.4
 - Node OS type and version: RKE DO

**Comment by meldafrawi** [comment]
Validation: **PASSED**
