### ISSUE TITLE
[BUG] Issues in the Backup page in the Longhorn UI

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1192]
**Describe the bug**
Issues in the Backup page in the Longhorn UI

**To Reproduce**
**Issue#1**

- Navigate to Backups page
- Sorting of backups for volumes does NOT work for "Last Backup At" and "Created At" columns
- Click on any volume
- Sorting of backups by snapshot name/ ID or any column — Does not work

**Expected behavior**
Sorting of columns should work

**Issue#2**

- Navigate to Backups page
- Click on any volume
- Click on one of the Workload/Pod for one of the backups
- In the Workload/Pod pop up window — the module can be formatted to occupy whole window rather than just the left part.

**Expected behavior**
In the Workload/Pod pop up window — the module can be formatted to occupy whole window rather than just the left part.
<img width="1045" alt="Screen Shot 2020-04-14 at 3 29 52 PM" src="https://user-images.githubusercontent.com/26032343/79280264-ced33900-7e64-11ea-9fbf-d8c710acaf10.png">

**Issue#3**

- Navigate to Backups page
- Click on any volume v1
- Click on one of the Volume v1 for one of the backups
- "Copyed" Text is seen on the UI.

**Expected behavior**
The text can be replaced by "Copied".

**Environment:**
 - Longhorn version: master
 - Kubernetes version: 1.17.4
 - Node OS type and version: RKE DO

**Comment by yasker** [comment]
@sowmyav27 Do you have a screenshot for issue 2?

@ly5156 Can you take a look at those issues?

**Comment by sowmyav27** [comment]
@yasker Attached snapshot in the original issue ^^^

**Comment by yasker** [comment]
@sowmyav27 issue #2. There are can be multiple pods using the same volume, so it's a list of cards that can scroll to the right.

**Comment by yasker** [comment]
@sowmyav27 Issue 1. It works for me though.

**Comment by sowmyav27** [comment]
@yasker 

- Have about 4-5 entries in the page
- and click on the column headers 3 times. 
- The columns do not get sorted.

**Comment by yasker** [comment]
@sowmyav27 oh, that's expected. The sorted button works like this: one-click for ascending, one-click for descending, then one-click to default order. Unlike Rancher, you can cancel sorting in this way.

**Comment by meldafrawi** [comment]
Validation: **Partially Failed**

**Browser:** `Firefox 75.0`

Steps to test:
- Create a deployment using https://raw.githubusercontent.com/longhorn/longhorn/master/examples/deployment.yaml
- Create a backup
- In backup details page, click on `Workload/Pod` 

![Peek 2020-04-21 03-50](https://user-images.githubusercontent.com/18232258/79816476-a1feb480-8383-11ea-87b4-717c4a7fbba7.gif)

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI versio: wangsiye/longhorn-ui:82eb981
