### ISSUE TITLE
[BUG] Error message displayed is long 

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1193]
**Describe the bug**
Error message displayed to be simplified on the UI

**To Reproduce**
- Create a backup b1 for vol v2
- restore from b1. Give the name of volume as v2
- Error: `unable to create volume: unable to create volume v2: &{Size:0 Frontend:blockdev FromBackup:s3://<bucket>/?backup=backup-fe7a231726264336&volume=v2 NumberOfReplicas:3 StaleReplicaTimeout:20 NodeID: EngineImage: RecurringJobs:[] BaseImage: Standby:false DiskSelector:[] NodeSelector:[] DisableFrontend:false}: volumes.longhorn.io "v2" already exists`

**Expected behavior**
A simpler error message - `"v2" already exists` can be displayed 

**Environment:**
 - Longhorn version: master
 - Kubernetes version: 1.17.4
 - Node OS type and version: rke DO

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
- Create a backup b1 for vol v2
- Restore from b1. Give the name of volume as v2
- A message indicating  `unable to create volume: unable to create volume <VOL_NAME>: volumes.longhorn.io "<VOL_NAME>" already exists`
