### ISSUE TITLE
[BUG] Pod status under Workload/Pod and Labels seems like its live status of pods in Backup List Page

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1194]
**Describe the bug**
Pod status under Workload/Pod and Labels seems like its live status of pods in Backup List Page

**To Reproduce**

- Navigate to Backup Page
- Click on a volume name and go to Backup List page
- Click on Labels

<img width="907" alt="Screen Shot 2020-04-14 at 3 31 06 PM" src="https://user-images.githubusercontent.com/26032343/79282613-8159ca80-7e6a-11ea-90d5-9cdd26067161.png">

- Click on Workload/Pod for a backup
<img width="1045" alt="Screen Shot 2020-04-14 at 3 29 52 PM" src="https://user-images.githubusercontent.com/26032343/79282626-8880d880-7e6a-11ea-9869-6a876d6f1e2e.png">

The pod status is seen Running. But this is not live data

**Expected behavior**
A timestamp can be added to the status, showing when this information was saved.

**Environment:**
 - Longhorn version: master
 - Kubernetes version: 1.17.4
 - Node OS type and version: RKE DO cluster - Linux

**Comment by sowmyav27** [comment]
**Verified with UI image: `wangsiye/longhorn-ui:492c389`**

- Create a volume in longhorn and attach it to a workload `wk01`.
- The Pod Status on the UI in the volume page - shows the correct status of the pod - Pending/Running.

<img width="699" alt="Screen Shot 2020-05-11 at 2 09 17 PM" src="https://user-images.githubusercontent.com/26032343/81612089-192ad580-9391-11ea-8b32-2348d17d9422.png">

- Delete workload `wk01`. 
- The Pod Status is not available anymore.
- But another field `Last time used by Pod` is seen on the UI

<img width="564" alt="Screen Shot 2020-05-11 at 1 56 42 PM" src="https://user-images.githubusercontent.com/26032343/81612163-3c558500-9391-11ea-9439-331dca3eaf48.png">

- The spacing between the field `Last time used by Pod` and other fields in the pop up is not the same - logged issue to track this - https://github.com/longhorn/longhorn/issues/1316
- Take a backup for the volume, navigate to Backup Page -->.Labels
- A new field `Create Time` has been added. The field can be renamed to "Created time" instead. logged issue - https://github.com/longhorn/longhorn/issues/1317

<img width="819" alt="Screen Shot 2020-05-11 at 2 01 59 PM" src="https://user-images.githubusercontent.com/26032343/81612417-a2420c80-9391-11ea-8c0d-f30653d2ea7b.png">

- But the Pod Status still shows as `Pending` here. This workload related to this volume has been deleted. This volume is in detached mode.

**Expected:** Pod status - should NOT show pending, as the workload has been deleted.

Reopening the issue because of this ^^^

**Comment by yasker** [comment]
@sowmyav27 The backup metadata only concerned about the state that pod was in when the snapshot was created. So it won't reflect the live data. So we won't expect the backup status updated when the workload has been deleted.

**Comment by sowmyav27** [comment]
@yasker Do we need the `Pod status` under workload status here in this case? It might just give an incorrect impression to the user about the pod.

**Comment by yasker** [comment]
@sowmyav27 We need it. It's an piece of important information for the user to identity the volume. We can rephrase the UI to e.g. `Workload Status When Created`

**Comment by sowmyav27** [comment]
Yes I think this `Workload Status When Created` would make more sense to the "Pod status" now. Thanks @yasker

**Comment by yasker** [comment]
@smallteeths Can you update the UI with the comment of https://github.com/longhorn/longhorn/issues/1194#issuecomment-628231474 ? Thanks.

**Comment by sowmyav27** [comment]
**Verified on master - ui tag: `wangsiye/longhorn-ui:8de351f`**

Validation: **`PASSED`**

- Navigate to Backup --> Backup list --> Labels
- `Kubernetes Status When Backup Created` is seen

<img width="794" alt="Screen Shot 2020-05-14 at 10 35 30 AM" src="https://user-images.githubusercontent.com/26032343/81966719-bde62680-95ce-11ea-90ae-f97e46ef26bd.png">

**Comment by sowmyav27** [comment]
**Validated on master - 05/18/2020**

- Create a volume in longhorn and attach it to a workload wk01.
- The Pod Status on the UI in the volume page - shows the correct status of the pod - Pending/Running.

<img width="555" alt="Screen Shot 2020-05-18 at 2 53 27 PM" src="https://user-images.githubusercontent.com/26032343/82263274-62da6980-9917-11ea-9f1c-ca6f422cebc3.png">

- Delete workload wk01.
- The Pod Status is not available anymore.
- But another field Last time used by Pod is seen on the UI

<img width="648" alt="Screen Shot 2020-05-18 at 2 53 39 PM" src="https://user-images.githubusercontent.com/26032343/82263285-67068700-9917-11ea-9a12-e52f5f0e8930.png">

- Navigate to Backup --> Backup list --> Labels
- Kubernetes Status When Backup Created is seen
<img width="815" alt="Screen Shot 2020-05-18 at 2 47 59 PM" src="https://user-images.githubusercontent.com/26032343/82263339-82719200-9917-11ea-84bd-b85d4441901d.png">
