### ISSUE TITLE
[BUG] Correct the variable naming issue for gRPC proto files for engine

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1197]
**Describe the bug**
The naming convention of gRPC is using underscore rather than camel case:
https://developers.google.com/protocol-buffers/docs/style#message-and-field-names
https://cloud.google.com/apis/design/naming_convention

**Comment by yasker** [comment]
Better deploy a script to check the naming convention for protobuf too.

**Comment by yasker** [comment]
Let's fix the internal API first. We shouldn't introduce any change might cause API version bump.

**Comment by shuo-wu** [comment]
Do we need to test anything manually before closing this issue? IMO, the issue can be closed as long as all integration tests get passed.

**Comment by yasker** [comment]
It's fine. Since it's a refactoring on engine API level, if something went wrong we will know.

Mark as fixed and close the issue.
