### ISSUE TITLE
[BUG] Issues in Dashboard UI

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1198]
**Describe the bug**
Issues in Dashboard UI

**To Reproduce**
**Issue#1**

- Navigate to Dashboard page
- SubObject column is available and is blank
<img width="1626" alt="Screen Shot 2020-04-15 at 7 51 00 AM" src="https://user-images.githubusercontent.com/26032343/79351972-249ff380-7eee-11ea-9cf8-d297f04386ab.png">

**Expected behavior**
SubObject column should not be present

**Issue#2**
- Navigate to Dashboard page
- Hover over the filter in the "Source" column.
<img width="1634" alt="Screen Shot 2020-04-15 at 7 53 42 AM" src="https://user-images.githubusercontent.com/26032343/79352269-7779ab00-7eee-11ea-84bc-04214c10f3ff.png">

**Expected behavior**
- Column header should be highlighted like it does for other column headers

**Issue#3**
- Navigate to Dashboard page
- Sort option is not available for "Source" column

**Expected behavior**
Sort option should be available for "Source" column

**Issue#4**
- Navigate to Dashboard page
- Sort option on any column does not sort it correctly

**Expected behavior**
Sorting of columns should work correctly.

**Issue#5**
- Navigate to Dashboard page
- Filter for `Name` and `Source` columns have “Search” and “Reset” options whereas the filters for `Kind` and `Type` have “Ok” and “Reset” options. 
<img width="1621" alt="Screen Shot 2020-04-15 at 8 04 08 AM" src="https://user-images.githubusercontent.com/26032343/79353291-b6f4c700-7eef-11ea-94ec-6b7cd94d3473.png">
<img width="1635" alt="Screen Shot 2020-04-15 at 8 04 13 AM" src="https://user-images.githubusercontent.com/26032343/79353293-b825f400-7eef-11ea-94e3-dfafc9a7793d.png">

**Expected behavior**
Options Should be the same across all filters.

**Issue#6**
- Navigate to Dashboard page
- Click on filter, filter text box opens.
- now scroll up in the window, the filter window scrolls up with the Dashboard window. 
<img width="1667" alt="Screen Shot 2020-04-15 at 8 04 54 AM" src="https://user-images.githubusercontent.com/26032343/79353507-fcb18f80-7eef-11ea-9efe-3a1133448031.png">

**Expected behavior**
the filter window Should not scroll up with the Dashboard window. 

**Environment:**
 - Longhorn version: master
 - Kubernetes version: 1.17.4
 - Node OS type and version: RKE DO Linux cluster

**Comment by smallteeths** [comment]
Due to the need to update the antd version, `Issue#6` has not been modified temporarily, I will file an issue for issues # 6 separately.  For `Issue#4`,I don’t know where the sorting is wrong @sowmyav27

**Comment by sowmyav27** [comment]
@smallteeths The sort option currently sorts it as - Ascending, descending and original. Do we need "Original" sorting here ?

**Comment by yasker** [comment]
@sowmyav27 Yeah that's what the sorting do normally in Longhorn UI.

**Comment by sowmyav27** [comment]
**Validated on master, ui tag: `wangsiye/longhorn-ui:79c09d9`**

Validation: **`PASSED`**

**Issue#1 Validation**
In Dashboard --> SubObject column is not present
<img width="1867" alt="Screen Shot 2020-05-13 at 3 02 12 PM" src="https://user-images.githubusercontent.com/26032343/81870503-ce44c580-952a-11ea-8619-d18e9805f0f1.png">

**Issue#2 Validation**
Column header is highlighted like it does for other column headers
<img width="1859" alt="Screen Shot 2020-05-13 at 3 03 09 PM" src="https://user-images.githubusercontent.com/26032343/81870540-e7e60d00-952a-11ea-84a8-0179d8713f58.png">

**Issue#3 Validation**
Sort option is available for "Source" column
<img width="1846" alt="Screen Shot 2020-05-13 at 3 14 17 PM" src="https://user-images.githubusercontent.com/26032343/81871426-9dfe2680-952c-11ea-8066-859d86aaea06.png">

**Issue#5 Validation**
Options are the same across all filters.
But the color of the `OK` button is different - logged a separate issue for this - https://github.com/longhorn/longhorn/issues/1338

**Comment by sowmyav27** [comment]
**Validated on master - 05/18/2020**

**Issue#1 Validation**
In Dashboard --> SubObject column is not present
<img width="1881" alt="Screen Shot 2020-05-18 at 3 05 56 PM" src="https://user-images.githubusercontent.com/26032343/82264108-2576db80-9919-11ea-9fed-9c8687009269.png">


**Issue#2 Validation**
Column header is highlighted like it does for other column headers
<img width="1881" alt="Screen Shot 2020-05-18 at 3 05 56 PM" src="https://user-images.githubusercontent.com/26032343/82264118-290a6280-9919-11ea-9806-639aa83bac7f.png">

**Issue#3 Validation**
Sort option is available for "Source" column
<img width="706" alt="Screen Shot 2020-05-18 at 3 07 19 PM" src="https://user-images.githubusercontent.com/26032343/82264191-49d2b800-9919-11ea-8ca1-15dafb9a39af.png">

**Issue#5 Validation**
Options are the same across all filters.
