### ISSUE TITLE
[BUG] Error message when a volume is not fetched from backupstore is not seen on the UI

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1199]
**Describe the bug**

**To Reproduce**

- Create a backup for a volume v1
- Navigate to the backupstore in S3.
- Go to Volume v1 and rename volume.cfg to volume.cfg.tmp
- On the Longhorn UI, navigate to Backup Page.
- Error seen in Response of the call made to fetch the backupvolumes:

```
"messages": {
        "error": "cannot find backupstore/volumes/00/a4/v2/volume.cfg in backupstore"
      },
```
Ui shows no error:
<img width="1641" alt="Screen Shot 2020-04-14 at 10 14 29 AM" src="https://user-images.githubusercontent.com/26032343/79375561-a94e3a00-7f0d-11ea-814a-85fb74fab986.png">

**Expected behavior**
Error should be seen on the UI for the users to understand that the volume backup has been corrupted/invalid/failed to fetch the backup

**Environment:**
 - Longhorn version: master (04/14/2020)
 - Kubernetes version: 1.17.4 
 - Node OS type and version: RKE DO Linux

**Comment by sowmyav27** [comment]
**Verified using UI image: `wangsiye/longhorn-ui:c45d726`**

**Steps:**

- Create a backup for a volume v1
- Navigate to the backupstore in S3.
- Go to Volume v1 and rename volume.cfg to volume.cfg.tmp
- On the Longhorn UI, navigate to Backup Page.
- Error seen on the UI - `cannot find backupstore/volumes/68/88/vol-2/volume.cfg in backupstore`

<img width="946" alt="Screen Shot 2020-05-08 at 12 23 49 PM" src="https://user-images.githubusercontent.com/26032343/81441642-fc8b6500-9126-11ea-9b04-1098b50dc9d8.png">

- Error seen in Response of the call made to fetch the backupvolumes:
```
"messages": {
        "error": "cannot find backupstore/volumes/68/88/vol-2/volume.cfg in backupstore"
      },
```

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI: `master`
