### ISSUE TITLE
[BUG] Node tag and disk tag are not available in to enter while 'Activate Disaster Recovery Volume.'

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1200]
**Describe the bug**
Node tag and disk tag are not available while activating a disaster recovery volume.

**To Reproduce**
1. Take a volume backup.
2. Go to backup page and click 'Create disaster recovery volume'.
3. Go to volume page and click 'Activate Disaster recovery volume'.
4. A form opens and allow user to enter Frontend
<img width="566" alt="Screen Shot 2020-04-15 at 11 46 49 AM" src="https://user-images.githubusercontent.com/60111667/79377710-f7b10800-7f10-11ea-8fc5-2afe86902067.png">

**Expected behavior**
There should be option to enter ```Node tag``` and ```Disk tag```

**Environment:**
 - Longhorn version: master

**Comment by yasker** [comment]
When DR volume was created, the scheduler is already get involved and the scheduling decision (include disk/node tag) has been made. So when you activate the volume, there won't be an option for disk/node tag.

But I found creating DR volume doesn't provide the input option for disk/node tag in the latest UI. That's a bug there.

**Comment by yasker** [comment]
Filed https://github.com/longhorn/longhorn/issues/1567 for DR volume with disk/node tag option.
