### ISSUE TITLE
[BUG] Storage fields for a disk on a node seem like they are editable but cannot be edited

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1201]
**Describe the bug**
Storage fields for a disk on a node seem like they are editable but cannot be edited

**To Reproduce**

- In the Longhorn UI, navigate to Node page
- Click on Operations --> Edit Node and Disks
- In the default disk modal, the fields - `Storage Available`, `Storage Max` and `Storage Scheduled` are input text boxes but are disabled, but not clearly disabled.

**Expected behavior**
These fields - `Storage Available`, `Storage Max` and `Storage Scheduled` - just provide info to the User, and can be redesigned to show information and NOT as text boxes that are disabled.

<img width="855" alt="Screen Shot 2020-04-15 at 1 00 53 PM" src="https://user-images.githubusercontent.com/26032343/79382955-38ad1a80-7f19-11ea-9ecf-5d0788afa2cb.png">

**Environment:**
 - Longhorn version: master
 - Kubernetes version: 1.17.4
 - Node OS type and version: rke DO Linux

**Comment by sowmyav27** [comment]
**Verified using ui tag:wangsiye/longhorn-ui:187f116**

Validation: **`PASSED`**

**Steps:**
- Navigate to Node page --> Operation --> Edit Node and Disk
- `Storage Available`, `Storage Max` and `Storage Scheduled` fields are not input textboxes anymore. There are displayed as User info
<img width="857" alt="Screen Shot 2020-05-11 at 3 44 25 PM" src="https://user-images.githubusercontent.com/26032343/81619437-77aa8080-939e-11ea-9ced-d5ee1294fa03.png">

**Comment by meldafrawi** [comment]
Validation **PASSED** on `longhornio/longhorn-ui:master`
