### ISSUE TITLE
[BUG] "Operation" column header is missing in Node page 

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1204]
**Describe the bug**
"Operation" column header missing in Node page 

**To Reproduce**

- Navigate to Node page in longhorn UI

<img width="2519" alt="Screen Shot 2020-04-15 at 3 29 20 PM" src="https://user-images.githubusercontent.com/26032343/79395397-6486cb00-7f2e-11ea-8486-7974af36dff1.png">

- Navigate to Volume page
<img width="2530" alt="Screen Shot 2020-04-15 at 3 29 26 PM" src="https://user-images.githubusercontent.com/26032343/79395562-c0515400-7f2e-11ea-9c17-d167e8a52dcd.png">

- Navigate to Backup Page
<img width="2502" alt="Screen Shot 2020-04-15 at 3 29 33 PM" src="https://user-images.githubusercontent.com/26032343/79395564-c21b1780-7f2e-11ea-8568-401fe01267e1.png">

**Expected behavior**
Operations column header should be available in the Node page.

**Environment:**
 - Longhorn version: master
 - Kubernetes version: 1.17.4
 - Node OS type and version: RKE DO Linux

**Comment by meldafrawi** [comment]
Validation: **PASSED**
