### ISSUE TITLE
[BUG ]Error when mounting ext4 by longhorn on SLES 12 SP3

### ISSUE THREAD

**Issue by gytxmu** [longhorn/longhorn#1208]
- Describe the bug:

create volume by longhorn UI and create pv and pvc also by longhornUI.
create a deployment of busybox by RancherUI using the pvc created by the longhornUI.
but the pvc cannot mount on Pod.
create pv/pvc by example yaml got the same problem.

- Log:

- the log of Rancher UI or describe pod：

MountVolume.SetUp failed for volume "pvc-73a45b97-3b7e-4966-a1e2-23080eb3a9cd" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = mount failed: exit status 32 Mounting command: mount Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-73a45b97-3b7e-4966-a1e2-23080eb3a9cd /var/lib/kubelet/pods/9c75a3f9-1663-4384-a220-28207144b40b/volumes/kubernetes.iocsi/pvc-73a45b97-3b7e-4966-a1e2-23080eb3a9cd/mount: wrong fs type, bad option, bad superblock on /dev/longhorn/pvc-73a45b97-3b7e-4966-a1e2-23080eb3a9cd, missing codepage or helper program, or other error.

- the log of dmesg:

#dmesg|tail
[ 4133.324354] sd 3:0:0:1: [sde] Write cache: enabled, read cache: enabled, supports DPO and FUA
[ 4133.363342] sd 3:0:0:1: [sde] Attached SCSI disk
[ 4138.962559] EXT4-fs (sde): Couldn't mount RDWR because of SUSE-unsupported optional feature METADATA_CSUM. Load module with allow_unsupported=1.
[ 4139.704904] EXT4-fs (sde): Couldn't mount RDWR because of SUSE-unsupported optional feature METADATA_CSUM. Load module with allow_unsupported=1.

- Enviroment:

Rancher Version 2.3.5
K8S Version 1.17.2
Docker Version 18.9.1
OS:Suse12SP3
kernel:4.4.180-94.107-default
longhorn version:v0.8.0

- yaml for pv/pvc:

apiVersion: v1
kind: PersistentVolume
metadata:
name: longhorn-volext4-pv
spec:
capacity:
storage: 2Gi
volumeMode: Filesystem
accessModes:
- ReadWriteOnce
persistentVolumeReclaimPolicy: Delete
storageClassName: longhorn
csi:
driver: driver.longhorn.io
fsType: ext4
volumeAttributes:
numberOfReplicas: '1'
staleReplicaTimeout: '2880'
volumeHandle: ext4testvolume1
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: longhorn-volext4-pvc
spec:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 2Gi
volumeName: longhorn-volext4-pv
storageClassName: longhorn

**Comment by gytxmu** [comment]
Rancher Version 2.3.5
K8S Version 1.17.2
Docker Version 18.9.1
the K8S is installed by rancher

**Comment by gytxmu** [comment]
create pv/pvc by yaml and create a volume on longhorn UI named ext4testvolume1.
I got the sanm error . the state of ext4testvolume1 is healthy.
pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: longhorn-volext4-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '1'
      staleReplicaTimeout: '2880'
    volumeHandle: ext4testvolume1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volext4-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: longhorn-volext4-pv
  storageClassName: longhorn

**Comment by yasker** [comment]
Seems like a version mismatch between the `mkfs.ext4` and `mount` used to format and mount the disk.

**Comment by gytxmu** [comment]
> Seems like a version mismatch between the `mkfs.ext4` and `mount` used to format and mount the disk.

Thanks a lot.
We will try to upgrade relative packages or upgrade the OS Version and check if it is work.

**Comment by gytxmu** [comment]
> Seems like a version mismatch between the `mkfs.ext4` and `mount` used to format and mount the disk.

We had upgrade the OS to SuSE12SP5,
the kenel version is 
Linux tgdfhk8snode08 4.12.14-120-default #1 SMP Thu Nov 7 16:39:09 UTC 2019 (fd9dc36) x86_64 x86_64 x86_64 GNU/Linux
the e2fsprogs version is e2fsprogs-1.43.8-3.8.1.x86_64.
 this package provide the `mkfs.ext4` commond by default.
I checked the docs , the version of e2fsprogs-1.43.8-3.8.1.x86_64 have the feature of METADATA_CSUM.this feature is since e2fsprogs-1.43.1

but still got the same error.
Could you tell me,which package longhorn used when longhorn created ext4 filesystems. I can try to get the same package and check if it it work well on my cluster.
Thank you very much.

**Comment by shuo-wu** [comment]
Longhorn is using the default packages of Ubuntu 18.04:
```
~ mkfs -V
mkfs from util-linux 2.31.1

~ mkfs.ext4 -V
mke2fs 1.44.1 (24-Mar-2018)
	Using EXT2FS Library version 1.44.1

~ mount -V
mount from util-linux 2.31.1 (libmount 2.31.1: selinux, btrfs, assert, debug)
```

Here are the links:
http://manpages.ubuntu.com/manpages/bionic/man8/mkfs.8.html
http://manpages.ubuntu.com/manpages/bionic/en/man8/mkfs.ext4.8.html
http://manpages.ubuntu.com/manpages/bionic/man8/mount.8.html

**Comment by joshimoo** [comment]
Just leaving some notes below.

More information about the metadata checksumming feature can be found [here](https://ext4.wiki.kernel.org/index.php/Ext4_Metadata_Checksums)

[Suse12SP3 ](https://www.suse.com/releasenotes/x86_64/SUSE-SLES/12-SP3/#fate-325367) does not support the ext4 metadata checksumming (METADATA_CSUM, 400)

[Suse12SP5](https://www.suse.com/releasenotes/x86_64/SUSE-SLES/12-SP5/#allArch-filesystems) seems to support the METADATA_CSUM feature, also there is no mention in the release notes that the feature is unsupported. Did a quick test to verify, that it works, `dumpe2fs` can be used to identify used features on a filesystem.

**Comment by khushboo-rancher** [comment]
We're able to reproduce this issue with SUSE-SLE12Sp2
NAME="SLES"
VERSION="12-SP2"
VERSION_ID="12.2"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP2"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp2"

**Comment by yasker** [comment]
@khushboo-rancher Can we test on SLES 15 as well?

**Comment by khushboo-rancher** [comment]
Tested on SUSE SLE 15 SP1, It works fine.
```
NAME="SLES"
VERSION="15-SP1"
VERSION_ID="15.1"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp1"
```

**Comment by joshimoo** [comment]
Verified that volume is correctly mounted EXT4 RW as well as that metadata_csum feature is enabled.

**Comment by yasker** [comment]
@joshimoo We need to give the user a choice to use it in SLES 12 SP3.

**Comment by joshimoo** [comment]
Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
* [ ] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [ ] **if labeled: require-automation-engine** Has the engine integration test been merged?
* [ ] **if labeled: require-doc** Has the necessary document PR submitted or merged?

**Comment by yasker** [comment]
We will need document for this option. Also, the test plan needs to be added to https://github.com/longhorn/longhorn-tests/wiki/Manual-Test-Plan

**Comment by joshimoo** [comment]
# Test Setup
- create a SLES12SP3 cluster
- keep all 3 deployments around till the end of the test

## Testing ext4 without custom fs params
- create a volume + pv + pvc with filesystem `ext4` named `ext-ck-fail`
- create a deployment that uses `ext-ck-fail`
- verify `MountVolume.SetUp failed for volume "ext4-ck-fails"` is part of the pod events
- verify that the pod does not enter running state

## Testing ext4 with custom fs params
- create a volume + pv + pvc with filesystem `ext4` named `ext4-no-ck`
- create a deployment that uses `ext4-no-ck`
- verify that the pod enters running state and the volume is accessible

## Testing xfs with custom fs params
- create a volume + pv + pvc with filesystem `xfs` named `xfs-ignores`
- create a deployment that uses `xfs-ignores`
- verify that the pod enters running state and the volume is accessible

**Comment by joshimoo** [comment]
Manual [test scenarios](https://github.com/longhorn/longhorn-tests/wiki/Test-Scenarios-for-Suse-SLES12SP3---custom-filesystem-paramters) created and added to the [manual test plan](https://github.com/longhorn/longhorn-tests/wiki/Manual-Test-Plan)

**Comment by khushboo-rancher** [comment]
Verified on master- 05-19-2020

mounting ext4 on SLES SP3 works fine with parameter - ```-O ^64bit,^metadata_csum``` or ```-O ^metadata_csum```

Scenario tested:
1. XFS filesystem with and without setting ```mkfs.ext4 parameters```.
2. ext4 filesystem with stateful set with parameter ```-O ^64bit,^metadata_csum```. - Volume got mounted successfully and user is able to read/write data on volume. 
3. ext4 filesystem with stateful set with parameter ```-O ^metadata_csum``` - Volume got mounted successfully and user is able to read/write data on volume. 
4. ext4 filesystem with wrong or empty parameter - Failed to mount
