### ISSUE TITLE
[BUG] An Invalid backup file in S3, throws an error in while listing the backups in backup list page

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1212]
**Describe the bug**
An Invalid backup file in S3, throws an error in while listing the backups in backup list page

**To Reproduce**

- In S3, edit the backup file - make it an invalid json data - (removed "}}" from the file in the end)
- Save the file and upload it back to S3.
- Go to Vol - Backup list page
- An error is seen while fetching the backups

Error:
`error listing backups for volume 'vol': error listing backups: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master/longhorn [backup ls --volume vol s3://<S3>/], output unexpected EOF , stderr, time="2020-04-16T19:40:41Z" level=error msg="unexpected EOF" , error exit status 1`

**Expected behavior**
User should not see the "unexpected EOF" error

**Environment:**
 - Longhorn version: master-latest - (04/16/2020)
 - Kubernetes version: 1.17.4 
 - Node OS type and version: LINUX rke DO

**Comment by yasker** [comment]
The error shouldn't block the whole listing of the backup. Other backups should still show up.

**Comment by yasker** [comment]
I don't think we have a way to manipulate S3 or NFS in the end-to-end test. Remove the `require-automation-e2e` for now.

**Comment by joshimoo** [comment]
BackupInfo (used by backupvolumes api) now contains a messages field that can be used to pass error messages to the client. This way we also display Backup infos for corrupt or missing backup configs.
For now we just pass the underlying error through.

**Comment by sowmyav27** [comment]
**Verified on master - 05/11/2020**

**Steps:**

- In S3, edit a backup file - make it an invalid json data - (removed "}}" from the file in the end)
- Save the file and upload it back to S3.
- Go to Backup --> Backup list page
- Error seen in backupList view

```
"messages": {
        "error": "unexpected EOF"
      },
```
- NO error is seen on the UI
<img width="1639" alt="Screen Shot 2020-05-11 at 8 30 21 PM" src="https://user-images.githubusercontent.com/26032343/81635573-58274e00-93c6-11ea-9bd1-2ed7bfe9f10e.png">

- On a restore, error seen on the U:
`unable to create volume: unable to create volume r1: cannot get backup s3://<>/?backup=backup-6810f998b8904b6e&volume=v2: error getting backup: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master/longhorn [backup inspect s3://<>/?backup=backup-6810f998b8904b6e&volume=v2], output unexpected EOF , stderr, time="2020-05-12T03:30:27Z" level=info msg="Failed to load backup in backupstore" backup=backup-6810f998b8904b6e event=list object=backup pkg=backupstore reason=fallback volume=v2 time="2020-05-12T03:30:27Z" level=error msg="unexpected EOF" , error exit status 1`

- When the user tried to delete the backup, the backupDelete response gives a 200 status. But the logs in the longhorn-manager throw error: `time="2020-05-12T03:32:21Z" level=error msg="error deleting backup s3://<>/?backup=backup-6810f998b8904b6e&volume=v2: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master/longhorn [backup rm s3://<>/?backup=backup-6810f998b8904b6e&volume=v2], output unexpected EOF\n, stderr, time=\"2020-05-12T03:32:21Z\" level=error msg=\"unexpected EOF\"\n, error exit status 1"`

**Expected:**

- User should be shown an error on the UI
- User should not be allowed to restore from this backup.
- User should be allowed to delete a corrupt backup from Longhorn UI from the backup List page

**Question:**
@yasker @joshimoo Do we expect to see `"error": "unexpected EOF"` when trying to fetch a corrupt backup file?

**Comment by joshimoo** [comment]
@sowmyav27 can this be closed?

**Comment by yasker** [comment]
@meldafrawi can you check if the automation passed for this issue?

**Comment by meldafrawi** [comment]
Passed for three times in a row
