### ISSUE TITLE
[BUG] Create Backup from a snapshot does not have option to add labels

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1216]
**Describe the bug**
Create Backup from a snapshot does not have option to add labels

**To Reproduce**

- Create a volume, PV/PVC/ attach to a workload. Write some data into the volume
- Go to volume details page
- Take a snapshot
- Click on the snapshot
- User is presented with Options - Revert/Backup/Delete
- Click on Backup
- User is not presented with an option to add labels. Backup gets created with NO labels

**Expected behavior**
User should be presented with an option to add labels on the backup

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

**Environment:**
 - Longhorn version: master - 04/16/2020 
 - Kubernetes version: 1.17.4
 - Node OS type and version: rke do Linux

**Comment by meldafrawi** [comment]
Validation: PASSED

Longhorn UI: wangsiye/longhorn-ui:9211206

Steps to test:
- Create a volume, PV/PVC/ attach to a workload. Write some data into the volume
- Go to volume details page
- Take a snapshot
- Click on the snapshot
- User is presented with Options - Revert/Backup/Delete
- Click on Backup
- User should be asked to add backup labels
- Create a backup with few labels
- Verify backup created with specified labels.
