### ISSUE TITLE
[BUG] No error message is seen on the UI when the user tries to restore from latest backup which has been deleted

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1217]
**Describe the bug**
No error message is seen on the UI when the user tries to restore from latest backup which has been deleted

**To Reproduce**

- Create a volume, PV/PVC/ attach to a workload. Write some data into the volume
- Enable recurring backups for this volume for every minute
- Wait for a couple of recurring backups happen
- Go to Backup list page and delete the latest backup
- Go back to backup page

**Issue#1**: When user comes to Backup page, Last Backup At column is blank for that backup v1
<img width="1255" alt="Screen Shot 2020-04-17 at 4 03 41 PM" src="https://user-images.githubusercontent.com/26032343/79620548-11934c00-80c5-11ea-8bc8-254c8687f16a.png">

**Issue#2**: When user tries to do restore latest backup, he sees error in console.
```
main.97987796.async.js?11ce8446a12da3cabdc2:40 Uncaught (in promise) TypeError: Cannot read property 'volumeName' of null
    at main.97987796.async.js?11ce8446a12da3cabdc2:40
    at Array.forEach (<anonymous>)
    at main.97987796.async.js?11ce8446a12da3cabdc2:40
    at s (main.97987796.async.js?11ce8446a12da3cabdc2:21)
    at Generator._invoke (main.97987796.async.js?11ce8446a12da3cabdc2:21)
    at Generator.forEach.e.<computed> [as next] (main.97987796.async.js?11ce8446a12da3cabdc2:21)
    at H (main.97987796.async.js?11ce8446a12da3cabdc2:26)
    at s (main.97987796.async.js?11ce8446a12da3cabdc2:26)
    at main.97987796.async.js?11ce8446a12da3cabdc2:26
    at o (main.97987796.async.js?11ce8446a12da3cabdc2:16)
```

**Expected behavior**
In both the issues, user should see an error message on the UI that the latest backup is not found

**Environment:**
 - Longhorn version: master - 04/16/2020
 - Kubernetes version: 1.17.4
 - Node OS type and version: rke DO Linux

**Comment by smallteeths** [comment]
![Jietu20200429-141638](https://user-images.githubusercontent.com/27733391/80568785-36bf7d00-8a2a-11ea-818a-9f14ee066c53.jpg)
![Jietu20200429-143731](https://user-images.githubusercontent.com/27733391/80568797-417a1200-8a2a-11ea-96e0-e9f5c31f8d56.jpg)

Backup data returned without `lastBackupName` @yasker

**Comment by yasker** [comment]
When a new backup was created, the lastBackup should be updated. So it's ok to disable the option temporarily since it's uncommon to remove the last backup.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI: `wangsiye/longhorn-ui:9211206`

Steps to test:
- Create a volume, PV/PVC/ attach to a workload. Write some data into the volume, compute it's checksum (checksum#1)
- Enable recurring backups for this volume for every 2 minutes
- Wait for a couple of recurring backups happen
- Go to Backup list page and delete the latest backup
- Go back to backup page
- When user comes to Backup page, Last Backup At column is blank for that backup v1 **(PASSED)**
- On Backup page, on `Operation` menu `Restore Latest Backup` should be **disabled** while no new backup has been created.
- write some more data to the volume, and compute it's checksum (checksum#2)
- Wait for a new backup to be created.
- Click on `Backup` for `Last Backup At`value to be updated.
-  On Backup page, on `Operation` menu `Restore Latest Backup` should be **enabled**
- Restore latest backup, verify volume data, and verify it's checksum (checksum#1& checksum#2)
