### ISSUE TITLE
[BUG] Opening Backup page on a new Tab/new window does not list the backups for volumes in the backup page

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1218]
**Describe the bug**
Opening Backup page on a new Tab/new window does not list the backups for volumes in the backup page

**To Reproduce**
**Pre condition:** - Have a few volumes and respective backups for the volumes create 

- Navigate to volume detail page
- Right click on backup page
- open the page in new tab
- backups are NOT being listed

**Expected behavior**
backups should be listed

**Note:**
Hard Refresh the page
Backups will be listed

**Environment:**
 - Longhorn version: master - 04/16/2020
 - Kubernetes version: 1.17.4
 - Node OS type and version: RKE DO linux

**Comment by meldafrawi** [comment]
Validation: PASSED

Longhorn UI: wangsiye/longhorn-ui:9211206

Steps to test:
- Navigate to volume detail page
- Right click on backup page
- open the page in new tab
- backups are NOT being listed
