### ISSUE TITLE
test: Add test case for duplicate disk names in the node default disk config annotation

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1219]
Need to use Longhorn to create the extra disk with a valid path to test the duplicate disk name case.

**Comment by boknowswiki** [comment]
Verified the longhorn-manager log has the correct error message
[longhorn-manager-b559j] time="2020-05-02T06:43:55Z" level=warning msg="Kubernetes node: invalid annotation node.longhorn.io/default-disks-config: config: the disk name same-name has duplicated"

**Comment by meldafrawi** [comment]
`test_node_config_annotation_invalid` passed for two consecutive runs `longhorn-tests/421` & `longhorn-tests/422`
