### ISSUE TITLE
[BUG]Volume async operation (rebuild/restore/...) status cannot show the correct replica 

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1220]
**Describe the bug**
When a volume starts an async operation, the replica in the reported status is not correct. e.g., for the rebuilding status, if the from-replica and the rebuilding replica are on the same node, the `fromReplica` field is the same as `replica` field in the reported status.

**To Reproduce**
Reproduce case 1:
1. Make sure the setting `Replica Soft Anti-Affinity` is enabled.
2. Disable scheduling for all nodes except for one.
3. Launch a volume with 3 replicas, write some data
4. Delete a replica and wait for rebuilding
5. Check the rebuild status, the field `fromReplica` is the same as the field `replica`.

Reproduce case 2:
1. Make sure the setting `Replica Soft Anti-Affinity` is enabled.
2. Disable scheduling for all nodes except for one.
3. Prepare a backup containing some data.
4. Restore a volume with 3 replicas from the backup.
5. Check the restore status, the field `replica` in all restore status entries are the same.

There should be similar issues for `backupStatus` and `purgeStatus`

**Expected behavior**
1. For rebuild status, the field `fromReplica` should not be the same as the field `replica`.
2. For other kinds of async status, the field `replica` in all entries should not be identical.

**Environment:**
 - Longhorn version: v0.8.0
 - Kubernetes version: v.1.17
 - Node OS type and version: Ubuntu 18.04

**Additional context**
The async status in engine object looks fine, hence there should be a bug in longhorn manager API level

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
Reproduce case 1:
1. Make sure the setting `Replica Soft Anti-Affinity` is enabled.
2. Disable scheduling for all nodes except for one.
3. Launch a volume with 3 replicas, write some data
4. Delete a replica and wait for rebuilding
5. Check the rebuild status, the field `fromReplica` is the same as the field `replica`.
6. The field `fromReplica` should not be the same as the field `replica`. (**PASS**)


Reproduce case 2:
1. Make sure the setting `Replica Soft Anti-Affinity` is enabled.
2. Disable scheduling for all nodes except for one.
3. Prepare a backup containing some data.
4. Restore a volume with 3 replicas from the backup.
5. Check the restore status, the field `replica` in all restore status entries are the same.
6. The field `replica` in all entries should not be identical. (**PASS**)

Reproduce case 3:
1. Make sure the setting `Replica Soft Anti-Affinity` is enabled.
2. Disable scheduling for all nodes except for one.
3. Create multiple snapshots.
4. Delete snapshots ans trigger snapshot purge.
5. Check the purge status, the field `replica` in all purge status entries are the same.
6. The field `replica` in all entries should not be identical. (**PASS**)
