### ISSUE TITLE
[BUG] Bug in EC2 iscsi initiator (open-iscsi) result in Longhorn pick up the wrong block device in Amazon Linux 2

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1223]
**Describe the bug**
EC2 ISCSI initiator (open-iscsi) reports the wrong device for operation on Amazon Linux 2, result in Longhorn pick up the wrong block device and result in mount failure.

**To Reproduce**
1. Start an EKS cluster in Rancher.
1. Install open-iscsi on the node using `sudo yum install iscsi-initiator-utils -y`
1. Install Longhorn on it.
1. Attach a new EBS volume to the EC2 instance in AWS console, specify `sdb` as the name
1. Create two new volumes in Longhorn and attach it to the same node.
1. Check the major:minor number of the volumes in `/dev/longhorn` using `ls -l /dev/longhorn`, one of them has the same major:minor number as the EBS volume.

**Expected behavior**

Both volumes should be created using iscsiadm, none of them should be the same as EBS volume.

**Log**
When this issue happens on the root disk, user might get error message like:
> Warning FailedMount MountVolume.SetUp failed for volume "pvc-5c6a2441-6bd8-11ea-bab2-025876296c71" : rpc error: code = Internal desc = failed to mount the volume as "ext4", it already contains unknown data, probably partitions. Mount error: mount failed: exit status 32 Mounting command: mount Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-5c6a2441-6bd8-11ea-bab2-025876296c71 /var/lib/kubelet/pods/5c6bc885-6bd8-11ea-bab2-025876296c71/volumes/kubernetes.io~csi/pvc-5c6a2441-6bd8-11ea-bab2-025876296c71/mount Output: mount: /var/lib/kubelet/pods/5c6bc885-6bd8-11ea-bab2-025876296c71/volumes/kubernetes.io~csi/pvc-5c6a2441-6bd8-11ea-bab2-025876296c71/mount: /dev/longhorn/pvc-5c6a2441-6bd8-11ea-bab2-025876296c71 **already mounted or mount point busy.**

An example of the issue when happened on the root disk `/dev/sda` (instead of the additional attached EBS as shown in the reproduce steps above. TO BE UPDATED):

```
iscsiadm -m session -P 3
```

Return
```
Target: iqn.2019-10.io.longhorn:pvc-faf086e9-7f83-11ea-8455-0e25b9fc2cb3 (non-flash)

....

                        Attached scsi disk sda          State: running

```
That's how Longhorn decides the iscsi device should be `/dev/sda`.

But `ls -l` shows

```
lrwxrwxrwx 1 root root           4 Apr 15 00:49 sda -> xvda

lrwxrwxrwx 1 root root           5 Apr 15 00:49 sda1 -> xvda1

...

brw-rw---- 1 root disk    202,   0 Apr 15 00:49 xvda

brw-rw---- 1 root disk    202,   1 Apr 15 00:49 xvda1
```

means on this node, `/dev/sda` has been used as an alias(link) of `/dev/xvda`, which is likely the root disk of the OS. And somehow iscsi initiator cannot override it and use `/dev/sda`. That's why Longhorn uses the wrong disk by mistake. It was looking for `/dev/sda`, end up with `/dev/xvda`.

And 
```
$ ls -l /dev/disk/by-path

total 0

lrwxrwxrwx 1 root root 9 Apr 16 01:46 ip-10.44.136.4:3260-iscsi-iqn.2019-10.io.longhorn:pvc-06ff6479-7f84-11ea-8455-0e25b9fc2cb3-lun-1 -> ../../sdb
```

So it's missing sda.

**Environment:**
 - Longhorn version: v0.8.0
 - Kubernetes version: v1.15
 - Node OS type and version: Amazon Linux 2 with `open-iscsi` installed

**Additional context**
The reason is there is a presumed bug in the iscsi initiator, result in the both iscsi and AWS EBS used the same device name.

Based on my experiment, even though iscsi initiator unable to create the device with the correct major:minor number, if we can guess the right major:minor number, we still can create the correct Longhorn device at `/dev/longhorn/` using `mknod` command, e.g. `mknod /dev/longhorn/test b <major> <minor>`

But `iscsiadm -m session -P 3` will indicate the wrong disk, and `/dev/disk/path` won't exist for the overridden disk. So we need to find another way to figure out major:minor number.

**Workaround**
If the volume is attached as an additional EBS volume, user can use other device names e.g. `xvdx` e.g. `xvda` for EBS volume to avoid conflict with iscsi's default `sdx` e.g. `sda`.

But if it's the root disk, the user won't be able to workaround this issue currently.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
1. Start an EKS cluster in Rancher.
2. Install open-iscsi on the node using `sudo yum install iscsi-initiator-utils -y`
3. Install Longhorn on it.
4. Attach a new EBS volume to the EC2 instance in AWS console, specify `sdb` as the name
5. Create multiple volumes  in Longhorn and attach it to the same node.
6. Check the `major:minor` number of the volumes in `/dev/longhorn` using `ls -l /dev/longhorn`, make sure Longhorn volume `major:minor` numbers are different of EBS
7. Write data to Longhorn volumes, compute it's checksum
8. Detach the volumes, attach them again to different nodes, and check data checksum.
