### ISSUE TITLE
[BUG]Volume endpoint becomes empty after live upgrade

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1225]
**Describe the bug**
When the volume engine is upgraded from v0.8.0 to v0.8.1-rc1, the endpoint will become empty. Then the engine monitor will keep sending FrontendStart() calls, which leads to continuously reload/reconnect the device. The volume is actually unavailable in this case.

**To Reproduce**
1. Deploy Longhorn v0.8.0
2. Create a volume then attach it.
3. Upgrade Longhorn to v0.8.1-rc1
4. Live upgrade the volume engine to v0.8.1-rc1

**Expected behavior**
The endpoint should keep unchanged during/after the upgrade

**Log**
After the live upgrade, the engine info is like:
```
root@instance-manager-e-1a2e316c:/# /engine-binaries/longhornio-longhorn-engine-master/longhorn --url localhost:10001 info
{
	"name": "v1",
	"size": 2147483648,
	"replicaCount": 3,
	"endpoint": "",
	"frontend": "tgt-blockdev",
	"frontendState": "up",
	"isExpanding": false,
	"lastExpansionError": "",
	"lastExpansionFailedAt": ""
}
```

**Environment:**
 - Longhorn version: v0.8.1-rc1

**Additional context**
Should set endpoint in FinishUpgrade():
https://github.com/longhorn/go-iscsi-helper/blob/ab9932015591ecf0c05ac6b8827606a1d7060f98/longhorndev/dev.go#L241

**Comment by yasker** [comment]
Somehow live upgrade end to end test didn't catch this. We need to fix it too.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:

1. Deploy Longhorn v0.8.0
2. Create a volume then attach it., use `lhexec` command check volume info
https://github.com/longhorn/longhorn-manager/blob/master/deploy/scripts/lhexec

`./lhexec VOLUME_NAME info`

3. Upgrade Longhorn to v0.8.1-rc3
4. Live upgrade the volume engine to v0.8.1-rc3
5. Use `lhexec` command check volume info
https://github.com/longhorn/longhorn-manager/blob/master/deploy/scripts/lhexec

Frontend should stay the same before and after upgrade.
