### ISSUE TITLE
[BUG] Tool tip for Backup action in volume details page is incorrect

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1227]
**Describe the bug**
Tool tip for Backup action in volume details page is incorrect

**To Reproduce**
1. Create a volume
2. Go to the volume details page
3. The tool tip is incorrect
<img width="447" alt="Screen Shot 2020-04-21 at 10 18 37 AM" src="https://user-images.githubusercontent.com/26032343/79903346-bfee0880-83c7-11ea-894f-56deabca28a9.png">

**Expected behavior**
the tool tip should display appropriate message for Backup Action

**Environment:**
 - Longhorn version: master - 04/21/2020 
 - Kubernetes version: 1.17.4
 - Node OS type and version: DO rke Linux

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI versio: wangsiye/longhorn-ui:82eb981
