### ISSUE TITLE
[BUG] When a backup fails for a volume, the backup progress is still seen in Volume details page

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1228]
**Describe the bug**
When a backup fails for a volume, the backup progress is still seen in Volume details page

**To Reproduce**

1. Create a volume, attach to a workload. write something to the volume
2. Take a backup
3. While the backup is in progress, reboot the node, in which the replica responsible for backup is running
4. The backup fails
5. But the Backup is still seen in Progress

<img width="1644" alt="Screen Shot 2020-04-21 at 11 47 30 AM" src="https://user-images.githubusercontent.com/26032343/79903653-4acf0300-83c8-11ea-9953-d77e9c90d675.png">

**Expected behavior**
it should contain an error message, which should say that the backup has erred out

**API response for volumes**

```
"backupStatus": [
        {
          "actions": null,
          "backupURL": "<url>",
          "error": "",
          "id": "backup-2a94fe21aa114a17",
          "links": null,
          "progress": 100,
          "replica": "<>",
          "snapshot": "a3c33815-4df9-4848-b3da-3f2638b23123",
          "state": "complete"
        },
        {
          "actions": null,
          "backupURL": "",
          "error": "",
          "id": "backup-7c58966e80464aed",
          "links": null,
          "progress": 30,
          "replica": "<>",
          "snapshot": "87402373-be6b-4947-bb88-eeb7b4f63979",
          "state": "in_progress"
        },
        {
          "actions": null,
          "backupURL": "<url>",
          "error": "",
          "id": "backup-9ce76b47470946ba",
          "links": null,
          "progress": 100,
          "replica": "<>",
          "snapshot": "373138b7-8ce9-4809-8f4e-5e8e030699bd",
          "state": "complete"
        }
      ],
```

**Environment:**
 - Longhorn version: master - 04/21/2020
 - Kubernetes version: 1.17.4
 - Node OS type and version: rke DO Linux

**Comment by joshimoo** [comment]
@sowmyav27 could you retest this with the latest master, after my fixes for #1230 
Once we no longer know the replica (getting cleaned up) the backup status should turn into error
and then the status should get removed.

**Comment by yasker** [comment]
Fix for #1230 merged.

**Comment by joshimoo** [comment]
Verified my fix in #1230 addresses this issue.
I did the below, repro steps:

1) create volume p1228 with 20GB
2) attach volume p1228 to node1
3) ssh into node1
4) run: `dd if=/dev/urandom of=/dev/longhorn/p1228 status=progress`
5) wait for around 1GB of data
6) start backup, ssh into backup replica X
7) enable magic commands: `echo 1 > /proc/sys/kernel/sysrq`
8) hard reboot **(can kill the machine/filesystem)**: `echo b > /proc/sysrq-trigger`

**Comment by joshimoo** [comment]
You should be able to do the same with a soft reboot via: `reboot`

**Comment by sowmyav27** [comment]
**Verified on master - 05/08/2020**

**Steps:**

- Create a volume, attach to a workload. write something to the volume
- Take a backup
- While the backup is in progress, reboot the node, in which the replica responsible for backup is running
- The backup fails
- It is not see in "In Progress" anymore
<img width="803" alt="Screen Shot 2020-05-08 at 11 16 11 AM" src="https://user-images.githubusercontent.com/26032343/81436643-aadedc80-911e-11ea-8eb9-a73ed71c59ea.png">

- But the failed backup status for that backup is not available anymore in the volumes API -
```
"backupStatus": [
        {
          "actions": null,
          "backupURL": "",
          "error": "",
          "id": "backup-c81d0fa474284d64",
          "links": null,
          "progress": 3,
          "replica": "vol-2-r-47bd8d7f",
          "snapshot": "f202c984-ed6b-4b94-935a-7663d7d57ff0",
          "state": "in_progress"
        },
        {
          "actions": null,
          "backupURL": "",
          "error": "",
          "id": "backup-e4a396f0495f4c1e",
          "links": null,
          "progress": 15,
          "replica": "vol-2-r-47bd8d7f",
          "snapshot": "b6c68e0e-de47-468b-807c-f9f84f581878",
          "state": "in_progress"
        }
      ],
```
Logged an issue - to track this - https://github.com/longhorn/longhorn/issues/1311

Closing this issue.
