### ISSUE TITLE
[BUG] Fix link to Longhorn chart in the Rancher UI

### ISSUE THREAD

**Issue by catherineluse** [longhorn/longhorn#1229]
The "Chart documentation" link in the Rancher UI doesn't work.
This is the link https://github.com/longhorn/longhorn/blob/master/docs/chart.md
<img width="1455" alt="Screen Shot 2020-04-21 at 1 24 03 PM" src="https://user-images.githubusercontent.com/20599230/79910532-bff40580-83d3-11ea-8309-05e2dc73964e.png">

**Comment by yasker** [comment]
Do we have an equivalent link in longhorn.io/docs ?

**Comment by yasker** [comment]
It is the link to https://github.com/longhorn/longhorn/blob/master/chart/README.md .

**Comment by yasker** [comment]
Done
