### ISSUE TITLE
[BUG] Backups are not being listed with the snapshot in volumes detail page

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1230]
**Describe the bug**
Backups are not being listed with the snapshot in volumes detail page

**To Reproduce**

Number of replicas - 3, number of worker nodes in cluster - 4

1. Create a volume, attach to a workload
2. Write data to the volume
3. Create a backup
4. Reboot a node
5. Replica gets rebuilt
6. Navigate to volume details page
7. Create a backup
8. The backups fail to get seen in the snapshot created in the volume details page.
9. The volume API - does not show the backups

**Note:**
Backup creation succeeds and is listed in the "Backup List" page

**Volume API:**
```
"backupStatus": [
        {
          "actions": null,
          "backupURL": "",
          "error": "Failed to get backup status on <> for backup-90a5c69161514c1b: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp <>: i/o timeout\"",
          "id": "backup-90a5c69161514c1b",
          "links": null,
          "progress": 0,
          "replica": "",
          "snapshot": "",
          "state": ""
        },
        {
          "actions": null,
          "backupURL": "",
          "error": "Failed to get backup status on <> for backup-ecdb0fc619544da4: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp <>: i/o timeout\"",
          "id": "backup-ecdb0fc619544da4",
          "links": null,
          "progress": 0,
          "replica": "",
          "snapshot": "",
          "state": ""
        }
      ],
```

**Actual Backups:**
<img width="1638" alt="Screen Shot 2020-04-21 at 2 06 54 PM" src="https://user-images.githubusercontent.com/26032343/79914013-6098f400-83d9-11ea-9f3e-bbef6c4c00d9.png">

**Logs:**
```

/engine-binaries/longhornio-longhorn-engine-master/longhorn --url localhost:10000 backup status
{
	"backup-0c4046e964d141e6": {
		"progress": 100,
		"backupURL": "<URL>",
		"snapshotName": "52d393ac-e8f8-4f92-a23f-0e4ef8b97e65",
		"state": "complete",
		"replicaAddress": "tcp://10.42.2.28:10000"
	},
	"backup-2a94fe21aa114a17": {
		"progress": 0,
		"error": "Failed to get backup status on tcp://10.42.3.6:10000 for backup-2a94fe21aa114a17: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.42.3.6:10002: i/o timeout\"",
		"snapshotName": "",
		"state": "",
		"replicaAddress": ""
	},
	"backup-551639a073334b8c": {
		"progress": 100,
		"backupURL": "<URL>",
		"snapshotName": "9ab7bd9a-3a93-49a5-94ca-bdfc473b633e",
		"state": "complete",
		"replicaAddress": "tcp://10.42.2.28:10000"
	},
	"backup-7c58966e80464aed": {
		"progress": 0,
		"error": "Failed to get backup status on tcp://10.42.3.6:10000 for backup-7c58966e80464aed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.42.3.6:10002: i/o timeout\"",
		"snapshotName": "",
		"state": "",
		"replicaAddress": ""
	},
	"backup-809c1d4521ea494e": {
		"progress": 100,
		"backupURL": "<URL>",
		"snapshotName": "125501f2-12de-4b5a-9d67-b70e9b6f0a3f",
		"state": "complete",
		"replicaAddress": "tcp://10.42.2.28:10000"
	},
	"backup-9ce76b47470946ba": {
		"progress": 0,
		"error": "Failed to get backup status on tcp://10.42.3.6:10000 for backup-9ce76b47470946ba: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.42.3.6:10002: i/o timeout\"",
		"snapshotName": "",
		"state": "",
		"replicaAddress": ""
	},
	"backup-c20e945c617c4cbc": {
		"progress": 100,
		"backupURL": "<URL>",
		"snapshotName": "a478a34e-0105-4c29-8ea0-208aabe18b0c",
		"state": "complete",
		"replicaAddress": "tcp://10.42.2.28:10000"
	},
	"backup-facc10ed11de4c18": {
		"progress": 100,
		"backupURL": "<URL>",
		"snapshotName": "719566a4-5f6b-4cba-bf98-6797cc694bd3",
		"state": "complete",
		"replicaAddress": "tcp://10.42.2.28:10000"
	}
}
```
**Expected behavior**
All the backups should be listed

**Environment:**
 - Longhorn version: master - 04/21/2020
 - Kubernetes version: 1.17.4
 - Node OS type and version: rke DO linux

**Comment by yasker** [comment]
It seems the disconnected replica is still being reached by the controller's `backup status` command.

We should add a test case for this: test delete the replica doing the backup, check the backup status, and check the backup after.

**Comment by joshimoo** [comment]
The real issue is that we run into a io timeout while trying to get the backup status information from the previously deleted replica.
Since we can potentially reuse the replica address (ip/port) for the rebuilt replica, we would end up waiting on a response while the rebuild is in progress.
If this happens for multiple backup status the whole backup status call will fail to return in time and therefore we would no longer see new backup statuses.

Below are some synthetic repoduction steps to emulate the core issue.
The fix will be to no longer try to communicate with a replica that is no longer known.

reproduction steps:
- create volume 3 replicas
- create backups
- check volumes api (backup status looks good)
- note down the replica (A) for backups
- disable scheduling on the Node of that replica (A)
- delete replica (A)
- check volumes api (backup error is connect: connection refused)

**Comment by khushboo-rancher** [comment]
Verified on Master - 05-08-2020
Verification - **Reopened**

Volume API just have last backup detail. 

```
https://rancher-server/k8s/clusters/c-gzz89/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/v1/volumes? 

"backupStatus": [{
			"actions": null,
			"backupURL": "",
			"error": "",
			"id": "backup-2852fd7373ba4dfd",
			"links": null,
			"progress": 100,
			"replica": "volume-longhorn-1-r-cc910d50",
			"snapshot": "f12aefb1-a369-452e-83ef-0290a85a46e2",
			"state": "complete"
		}],
```
Volume has 3 backups
<img width="1527" alt="Screen Shot 2020-05-08 at 4 45 02 PM" src="https://user-images.githubusercontent.com/60111667/81457525-4b4af600-914b-11ea-9d82-3d0a5a7354cd.png">
