### ISSUE TITLE
[BUG] Nodes deleted from cluster and re created with the same node name are seen as Unschedulable

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1232]
**Describe the bug**
Nodes deleted from cluster and re created with the same node name are seen as Unschedulable

**To Reproduce**

1. Create an RKE DO cluster from Rancher - 1 etcd, 1 control plane and 4 worker nodes
2. Enable/Deploy Longhorn in the cluster
3. Delete a worker node from Rancher.
4. The worker node is recreated (node pool) with the same node name
5. Navigate to Node page in Longhorn.
6. The node is seen in `Unschedulable` state 

**Expected behavior**
The node should NOT be in "Unschedulable" but be in `Schedulable` state. Longhorn should delete data about nodes which have been deleted from the cluster

**Note:**

- Currently user has to disable scheduling on the disk and delete the disk.
- Add a new disk on the node and enable scheduling for the node to come in `Schedulable` state.

**Environment:**
 - Longhorn version: master - 04/21/2020
 - Kubernetes version: 1.17.4
 - Node OS type and version: rke DO linux

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master - 10/21/2020

Validation - **Pass**

The corresponding Kubernetes node object gets deleted on the deletion of the nodes and adding another node with the same name works fine. Validated the case of schedulable/down/disabled and multiple nodes getting deleted.
