### ISSUE TITLE
[BUG]Data writing during the live upgrade leads to replica error

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1235]
**Describe the bug**
If users keep writing data to the Longhorn volume during the live upgrade, some new replicas will fail immediately when the new engine is launching.

**To Reproduce**
1. Create a volume using v0.8.0 engine image
2. Attach the volume then keep writing data into the volume
3. Live upgrade the volume to the latest engine image
4. Some newly launched upgraded replicas will fail

**Expected behavior**
Not replica fail

**Log**
```
[instance-manager-e-a6c5685f] [longhorn-instance-manager] time="2020-04-22T10:24:36Z" level=info msg="Process Manager: prepare to replace process pvc-cab0b8a0-54a7-4071-b01c-4bc21c0824c7-e-5ba4c270"
[instance-manager-e-a6c5685f] [longhorn-instance-manager] time="2020-04-22T10:24:36Z" level=info msg="Process Manager: started replace process pvc-cab0b8a0-54a7-4071-b01c-4bc21c0824c7-e-5ba4c270"
[instance-manager-e-a6c5685f] [longhorn-instance-manager] time="2020-04-22T10:24:36Z" level=debug msg="Process Manager: waiting for the replace process pvc-cab0b8a0-54a7-4071-b01c-4bc21c0824c7-e-5ba4c270 to start"
[instance-manager-e-a6c5685f] [pvc-cab0b8a0-54a7-4071-b01c-4bc21c0824c7-e-5ba4c270] time="2020-04-22T10:24:36Z" level=info msg="Starting with replicas [\"tcp://10.42.2.50:10015\" \"tcp://10.42.1.46:10015\" \"tcp://10.42.0.43:10015\"]"
[instance-manager-e-a6c5685f] time="2020-04-22T10:24:36Z" level=info msg="Connecting to remote: 10.42.2.50:10015"
[instance-manager-e-a6c5685f] [pvc-cab0b8a0-54a7-4071-b01c-4bc21c0824c7-e-5ba4c270] time="2020-04-22T10:24:36Z" level=info msg="Opening: 10.42.2.50:10015"
[instance-manager-e-a6c5685f] [pvc-cab0b8a0-54a7-4071-b01c-4bc21c0824c7-e-5ba4c270] time="2020-04-22T10:24:36Z" level=info msg="Adding backend: tcp://10.42.2.50:10015"
[instance-manager-e-a6c5685f] time="2020-04-22T10:24:36Z" level=info msg="Set replica tcp://10.42.2.50:10015 to mode RW"
[instance-manager-e-a6c5685f] time="2020-04-22T10:24:36Z" level=info msg="Connecting to remote: 10.42.1.46:10015"
[instance-manager-e-a6c5685f] time="2020-04-22T10:24:36Z" level=info msg="Start monitoring tcp://10.42.2.50:10015"
[instance-manager-e-a6c5685f] [pvc-cab0b8a0-54a7-4071-b01c-4bc21c0824c7-e-5ba4c270] time="2020-04-22T10:24:36Z" level=info msg="Opening: 10.42.1.46:10015"
[instance-manager-e-a6c5685f] [pvc-cab0b8a0-54a7-4071-b01c-4bc21c0824c7-e-5ba4c270] time="2020-04-22T10:24:36Z" level=info msg="Adding backend: tcp://10.42.1.46:10015"
[instance-manager-e-a6c5685f] [pvc-cab0b8a0-54a7-4071-b01c-4bc21c0824c7-e-5ba4c270] time="2020-04-22T10:24:36Z" level=info msg="Set replica tcp://10.42.1.46:10015 to mode RW"
[instance-manager-e-a6c5685f] time="2020-04-22T10:24:36Z" level=info msg="Connecting to remote: 10.42.0.43:10015"
[instance-manager-e-a6c5685f] [pvc-cab0b8a0-54a7-4071-b01c-4bc21c0824c7-e-5ba4c270] time="2020-04-22T10:24:36Z" level=info msg="Start monitoring tcp://10.42.1.46:10015"
[instance-manager-e-a6c5685f] [pvc-cab0b8a0-54a7-4071-b01c-4bc21c0824c7-e-5ba4c270] time="2020-04-22T10:24:36Z" level=info msg="Opening: 10.42.0.43:10015"
[instance-manager-e-a6c5685f] [pvc-cab0b8a0-54a7-4071-b01c-4bc21c0824c7-e-5ba4c270] time="2020-04-22T10:24:36Z" level=info msg="Adding backend: tcp://10.42.0.43:10015"
[instance-manager-e-a6c5685f] [pvc-cab0b8a0-54a7-4071-b01c-4bc21c0824c7-e-5ba4c270] time="2020-04-22T10:24:36Z" level=info msg="Set replica tcp://10.42.0.43:10015 to mode RW"
[instance-manager-e-a6c5685f] [pvc-cab0b8a0-54a7-4071-b01c-4bc21c0824c7-e-5ba4c270] time="2020-04-22T10:24:36Z" level=info msg="Start monitoring tcp://10.42.0.43:10015"
[instance-manager-e-a6c5685f] [pvc-cab0b8a0-54a7-4071-b01c-4bc21c0824c7-e-5ba4c270] time="2020-04-22T10:24:36Z" level=info msg="Get backend tcp://10.42.2.50:10015 revision counter 551"
[instance-manager-e-a6c5685f] [pvc-cab0b8a0-54a7-4071-b01c-4bc21c0824c7-e-5ba4c270] time="2020-04-22T10:24:36Z" level=info msg="Get backend tcp://10.42.1.46:10015 revision counter 553"
[instance-manager-e-a6c5685f] [pvc-cab0b8a0-54a7-4071-b01c-4bc21c0824c7-e-5ba4c270] time="2020-04-22T10:24:36Z" level=info msg="Get backend tcp://10.42.0.43:10015 revision counter 539"
[instance-manager-e-a6c5685f] time="2020-04-22T10:24:36Z" level=error msg="Revision conflict detected! Expect 553, got 551 in replica tcp://10.42.2.50:10015. Mark as ERR"
[instance-manager-e-a6c5685f] time="2020-04-22T10:24:36Z" level=info msg="Set replica tcp://10.42.2.50:10015 to mode ERR"
[instance-manager-e-a6c5685f] time="2020-04-22T10:24:36Z" level=error msg="Revision conflict detected! Expect 553, got 539 in replica tcp://10.42.0.43:10015. Mark as ERR"
[instance-manager-e-a6c5685f] time="2020-04-22T10:24:36Z" level=info msg="Set replica tcp://10.42.0.43:10015 to mode ERR"
[instance-manager-e-a6c5685f] time="2020-04-22T10:24:36Z" level=info msg="Upgrading frontend"
```

**Environment:**
 - Longhorn version: v0.8.1-rc2

**Additional context**
The cause may be the followings, not sure if it's correct:
1. Live upgrade starts
2. Longhorn launches new replicas with the current `RevisionCounter` for the new engine image.
3. New data is written to the volume via old replicas, which leads to the `RevisionCounter` file update. and the field `RevisionCounter` in new replicas becomes out of sync
4. The new engine process starts with those new replicas, then it finds the inconsistency and marks those replicas as ERROR.

**Comment by yasker** [comment]
I think the reason is different.

When we start the new engine image, it will connect to the replicas immediately. There is no locking mechanism to make sure when this happens, the replicas are at the same revision version. And it's in fact impossible to guarantee that since the engine writing to the data is totally in another process, and we don't want inter-process dependency here. 

The point to ensure the flawless transition from the old engine to the new engine is in the tgt target. Only at that point we can guarantee the revision counter are the same on all the replicas, but it's not detectable from the engine's perspective currently.

Ideally, we should verify the revision counter after the switch was made, before the first write command to the new engine, but we need to move things around for that. For now, as long as we tested the data integrity carefully, we can skip the revision counter check when engine started with `--upgrade`.

**Comment by shuo-wu** [comment]
There is a field named `revisionCache` in replica struct. When the volume starts to use the new engine to write data, the `revisionCache` that holds a smaller revision counter value will be recorded into the revision counter file. Hence the replicas will be still marked as ERROR if the volume is reattached.
https://github.com/longhorn/longhorn-engine/blob/21572ccd3c25bb83b766692877dc055a9959b710/pkg/replica/revision_counter.go#L123

We plan to check and reload the revision counter when handling the first write command. When this reload is done, the revision counter on all the replicas should keep in sync again.

**Comment by shuo-wu** [comment]
Test steps:
1. Deloy Longhorn v0.8.0.
2. Launch a pod with Longhorn volume.
3. Write data to a tmp file in the pod and get the md5sum. e.g.:
```
dd if=/dev/urandom of=/tmp/t1 bs=1M count=3000
md5sum /tmp/t1
```
4. Upgrade Longhorn to the latest version and wait for the upgrade complete
5. Copy the data from the tmp file to the volume. e.g.:
```
dd if=/tmp/t1 of=/data/t1 bs=1M count=3000
```
6. Do not wait for the copy complete. Immediately live upgrade the volume.
7. Wait for the copy complete and live upgrade complete
8. Check the data in the volume then write more data
9. Delete the pod and wait for the volume detached.
10. Recreate the pod and wait for the volume `attached`. Notice that the replicas shouldn't become ERROR or the volume shouldn't become state `degraded` when the volume is attached.
11. Check the data.

**Comment by yasker** [comment]
Note on verify: repeat the test at least 5 times to make sure it's done correctly.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps tried multiple times.
