### ISSUE TITLE
[BUG] Snapshot creation failed when one of the node out of three was rebooting.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1239]
**Describe the bug**
Snapshot creation failed when one of the node was rebooting.
The below API to create snapshot call returned 503 - service unavailable
```
https://rancher-server/k8s/clusters/c-xxxx/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/v1/volumes/longhorn-vol1?action=snapshotCreate
``` 
<img width="1026" alt="Screen Shot 2020-04-22 at 11 00 04 AM" src="https://user-images.githubusercontent.com/60111667/80017700-d8bef280-8489-11ea-9acc-5575815ce29c.png">

After the above failure, snapshot list call failed as well.
```
https://rancher-server/k8s/clusters/c-xxxx/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/v1/volumes/longhorn-vol1?action=snapshotList
```

**To Reproduce**
1. Create a volume 3 replicas on three nodes and attach to one workload
2. Write to volume and take a snapshot. (Repeat this 2 times)
3. Go to volume details page.
4. Reboot one node where replica exists and immediately take a snapshot.

**Expected behavior**
Snapshot should be created even when one of the node is rebooting.

**Log**
logs - 
[longhorn-support-bundle_snapshot.zip](https://github.com/longhorn/longhorn/files/4518163/longhorn-support-bundle_snapshot.zip)

**Environment:**
 - Longhorn version:
 - Kubernetes version:
 - Node OS type and version:

**Additional context**

**Comment by yasker** [comment]
@khushboo-rancher If one replica is trying to create snapshot but was rebooted, the snapshot creation can be either success (when the replica somehow manage to finish snapshot creation before cut off) or failure (when the replica failed to finish snapshot creation before cut off). The expected result is:
1. After this incident, engine should cut off the rebooted snapshot
2. snapshot operations like list or creation should still be fine
3. All the remaining replicas should have the same snapshots

**Comment by khushboo-rancher** [comment]
Thanks @yasker It makes sense.  I tried above scenario multiple times, what I found are below.
1. If somehow snapshot creation API call fails, the subsequent calls to list snapshot keeps failing until volume detail page is refreshed.
2. If the attached node to volume is rebooted, replica doesn't rebuild.

**Comment by yasker** [comment]
1. This is may due to the routing of the UI. Should be a UI bug.
2. You meant the reboot the node that volume attached to? That should result in workload migrate to other nodes and Longhorn volume attach to that node again. Rebuild should happen later. What are the steps to reproduce this issue?

**Comment by khushboo-rancher** [comment]
To reproduce the 2nd issue, steps are
1. Create a volume with 3-replicas 3-node, attach to a pod to the volume. Lets' say pod is running on Node1.
2. Write data to volume.
3. Trigger a reboot on Node1 and immediately take snapshot. 
4. Snapshot fails and replica doesn't get rebuilt.

In above case, workload didn't migrate to other node but stayed in unavailable state for a while and become active on same node once the node was up.

**Comment by yasker** [comment]
@khushboo-rancher That's expected, at least at this moment.

Longhorn will only rebuild when the engine is attached and communicating with Longhorn Manager. On that attached node, since it's down, Longhorn engine is already down with it. The UI you saw for that volume is in fact only the metadata. We didn't indicate that in the UI currently though. There isn't anything you can do for that volume at the moment (probably except detach it).

**Comment by khushboo-rancher** [comment]
OKay, So should we solve the UI issue only then?
```
If somehow snapshot creation API call fails, the subsequent calls to list snapshot keeps failing until volume detail page is refreshed.
```

**Comment by yasker** [comment]
@khushboo-rancher yes, we should see if we can solve this.
