### ISSUE TITLE
[BUG] Option to create PVC should be grayed out for Longhorn volume bound to PVC

### ISSUE THREAD

**Issue by catherineluse** [longhorn/longhorn#1254]
**Describe the bug**
The option to create a PVC is grayed out in one place but not another. This applies to a volume that already has a PV/PVC created in the Longhorn UI.

**To Reproduce**
1. Create a Longhorn volume
2. From the Longhorn UI, create PV/PVC
3. Select the volume using the check box in the left column
4. Click the hamburger menu > Create PV/PVC
5. See the error message "unable to create PVC for volume newvolume: volume already had PVC newvolume"

**Expected behavior**
After a PVC is bound to a volume, it should not look like it's possible to create another PV/PVC for the same volume.
<img width="746" alt="Screen Shot 2020-04-27 at 12 38 29 PM" src="https://user-images.githubusercontent.com/20599230/80413721-c3c8d180-8884-11ea-8aeb-3e0cc1860fd9.png">
<img width="201" alt="Screen Shot 2020-04-27 at 12 32 28 PM" src="https://user-images.githubusercontent.com/20599230/80413725-c4f9fe80-8884-11ea-98ca-8a6dd3a3ac43.png">
<img width="669" alt="Screen Shot 2020-04-27 at 12 32 18 PM" src="https://user-images.githubusercontent.com/20599230/80413728-c62b2b80-8884-11ea-83df-41cebd05675b.png">

**Comment by meldafrawi** [comment]
Validation: PASSED

Longhorn UI: wangsiye/longhorn-ui:9211206

Steps to test (1/2)
- Create a volume,
- On Volume Page, In `Operation` menu, `Create PV/PVC` option should be enabled **(PASSED)**
- Click on `Create PV/PVC`, Uncheck Create PVC, and create only PV for volume
- PV should be created for volume **(PASSED)**
- On Volume Page, In `Operation` menu, `Create PV/PVC` option should still be enabled **(PASSED)**
- Click on `Create PV/PVC`, Check Create PVC, and create PVC for volume
- PVC should be created for volume **(PASSED)**
- On Volume Page, In `Operation` menu, `Create PV/PVC` disabled enabled **(PASSED)**
- Delete PVC, PV/PVC status should be `Released`
- On Volume Page, In `Operation` menu, `Create PV/PVC` option should be enabled again **(PASSED)**


Steps to test (2/2):
- Create 3 volumes, select 2 of them
- On Volume Page, batch `Create PV/PVC` option should be enabled **(PASSED)**
- Click on batch `Create PV/PVC`, Uncheck Create PVC, and create only PV for both volumes
- PV should be created for both volumes **(PASSED)**
- On Volume Page, batch `Create PV/PVC` option should still be enabled **(PASSED)**
- Click on batch `Create PV/PVC`, Check Create PVC, and create PVC for both volumes
- PVC should be created for both volumes **(PASSED)**
- On Volume Page, batch `Create PV/PVC` should be disabled  **(PASSED)**
- Select all 3 volumes, batch `Create PV/PVC` should be disabled  **(PASSED)**
- Select only the 3rd volume, batch `Create PV/PVC` should be enabled  **(PASSED)**
- Select both 1st and 2nd volumes
- Delete PVC for both selected volumes, PV/PVC status should be `Released` for both volumes.
- On Volume Page, batch `Create PV/PVC` option should be enabled again **(PASSED)**
- Select all 3 volumes, batch `Create PV/PVC` should be enabled  **(PASSED)**
