### ISSUE TITLE
[DOC] Add more examples to docs

### ISSUE THREAD

**Issue by catherineluse** [longhorn/longhorn#1256]
Suggested examples:

- In configuration reference (`/docs/0.8.0/advanced-resources/settings/`), if applicable, each default value should be included in addition to the example values.
- In settings, add a full example YAML file of a longhorn deployment configuration
- Multiple disk support: Configuration section should have an example YAML
- The example setup in "recovery volume after unexpected detachment" should be in the best practices and in the settings/configuration reference
- Multiple disk support: Need to make sure configuration information is in the settings/configuration reference
- In "Create NGINX ingress controller with basic authentication" It says "It’s important the file generated is named auth (actually - that the secret has a key data.auth), otherwise the ingress-controller returns a 503" I think it would help to provide an example YAML of the auth secret
- Need to make sure volume expansion configuration information/example yaml is in the settings/configuration reference.

**Comment by aureq** [comment]
Yes, it would be great to have an improved documentation. I'm trying to figure out how to create a YAML configuration for multiple disks but so far I've failed.

@catherineluse Have you been able to find anything? Do you mind to share what you may have if you don't mind?

**Comment by yasker** [comment]
@aureq You meant https://longhorn.io/docs/0.8.1/advanced-resources/default-disk-and-node-config/ ? Notice the node annotation only applies if there is no disk on the node yet.

**Comment by shuo-wu** [comment]
- [ ] Add default values in `references/settings.md`
- [ ] Provide a full example YAML file/Update the YAML file in `advanced-resources/deploy/customizing-default-settings.md`
- [ ] Add multi-disk instructions  in `advanced-resources/deploy/customizing-default-settings.md` and put the related references in `references/settings.md`.
- [ ] Add a reference of `high-availability/recover-volume.md` in `best-practices.md`.
- [ ] Add more details in `deploy/accessing-the-ui/longhorn-ingress.md`

**Comment by yasker** [comment]
Merged.
