### ISSUE TITLE
[DOC] New content for docs

### ISSUE THREAD

**Issue by catherineluse** [longhorn/longhorn#1257]
I'm raising this issue to make it easier to track the work that needs to be done with regard to adding some new content to the Longhorn docs.

- **Add doc page "Best Practice Configuration" (DONE)** https://github.com/longhorn/website/issues/68, which is being drafted here https://github.com/yasker/longhorn/wiki/Best-practices-for-deploying-Longhorn-in-production
- **Document the minimum hardware requirements (DONE)** https://github.com/longhorn/website/issues/49
- **Add maintenance doc (DONE)** https://github.com/longhorn/website/issues/71 https://github.com/longhorn/website/pull/108
- **Add doc "Recover from a Longhorn replica without system installed" (DONE)** https://github.com/longhorn/website/issues/70

**Comment by yasker** [comment]
https://github.com/longhorn/website/issues/63 should be addressed by https://github.com/longhorn/website/commit/38a5f9939f25efcf327641ba3aa03c44a35f1524 already?

**Comment by catherineluse** [comment]
You're right. I edited this issue and closed it on longhorn/website

**Comment by catherineluse** [comment]
Closing this issue because all items are done
