### ISSUE TITLE
[DOC] Staging website/Forwarding docs.longhorn.io/xxx to longhorn.io/docs/xxx

### ISSUE THREAD

**Issue by catherineluse** [longhorn/longhorn#1258]
I'm opening this issue to make it easier to track some UI-related work for the longhorn/website repo.

- **Build the staging website** https://github.com/longhorn/website/issues/75
- **Forwarding `docs.longhorn.io/xxx` to `longhorn.io/docs/xxx`** https://github.com/longhorn/website/issues/65

**Comment by yasker** [comment]
Both issues are fixed.
