### ISSUE TITLE
[BUG] Deleting a snapshot shows > 100% progress on the replica in the volume details page

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1261]
**Describe the bug**
Deleting a snapshot shows > 100% progress on the replica in the volume details page

**To Reproduce**

- Create a volume and attach it to a workload.
- Go to volume details page 
- Create few snapshots
- Delete snapshots
- Hover over the progress bar of a replica
- It shows Deleting Snapshot 115%
- Snapshot Section shows Deleting 100%

<img width="1655" alt="Screen Shot 2020-04-27 at 1 13 07 PM" src="https://user-images.githubusercontent.com/26032343/80424997-ac471400-8897-11ea-9e4c-adc514a9d9f0.png">

**Expected behavior**
Deletion progress on the replica should match the % in the snapshot section.

**Environment:**
 - Longhorn version: master-04/27/2020
 - Kubernetes version: 1.17.4
 - Node OS type and version: RKE Linux DO cluster

**Comment by smallteeths** [comment]
![Jietu20200428-194203](https://user-images.githubusercontent.com/27733391/80483332-7cc40480-8988-11ea-97f3-a544a07a2a54.jpg)
![Jietu20200428-192203](https://user-images.githubusercontent.com/27733391/80483346-82214f00-8988-11ea-8d5a-c0f2b05cbfec.jpg)


The returned data may be the cause of this bug @yasker @sowmyav27

**Comment by yasker** [comment]
looks like an issue in the backend calculation.

**Comment by boknowswiki** [comment]
For the 4th reproduce step, need to delete the snapshot not in the creating order. Means delete the snapshots in the middle.

**Comment by sowmyav27** [comment]
**verified on master - 05/08/2020**

**Steps:**

- Create a volume and attach it to a workload.
- Go to volume details page
- Create few snapshots - 4 snapshots while writing data between taking snapshots
- Delete snapshots (not the latest)
- The progress bar on the replicas show > 100% deletion

<img width="1789" alt="Screen Shot 2020-05-08 at 1 01 29 PM" src="https://user-images.githubusercontent.com/26032343/81445069-13cd5100-912d-11ea-993f-32a5eaaa8a80.png">
<img width="1276" alt="Screen Shot 2020-05-08 at 1 06 38 PM" src="https://user-images.githubusercontent.com/26032343/81445075-17f96e80-912d-11ea-9f91-e8f676b9bfa6.png">

**Comment by boknowswiki** [comment]
@sowmyav27 ,

I just try the latest master image, and i don't see this issue.

Could you check if you are using the latest image with the following steps?

1. login to any engine-image-ei-xxx with cmd:
`kubectl -n longhorn-system exec -it engine-image-ei-605a0f3e-cbgcq bash`
2. check longhorn version with cmd:
`root@engine-image-ei-605a0f3e-cbgcq:/# longhorn --version
longhorn version a76acd6`

If you see the version is different than "a76acd6", this means it's not the latest one, and could you try to upgrade to the latest one by deleting them with kubectl delete pod <name>?

If you are using the latest one and still seeing this issue, please let me know.

Thanks,
Bo

**Comment by yasker** [comment]
Note: `kubectl -n longhorn-system delete daemonset engine-image-ei-xxxx` is more convenient.

**Comment by sowmyav27** [comment]
**Verified on master - latest - 05/12 (`5b9f05c` on UI)**

Validation: **`PASSED`**

- Create a volume and attach it to a workload.
- Go to volume details page
- Create few snapshots - 4 snapshots while writing data between taking snapshots
- Delete snapshots (not the latest)
- Deletion progress is NOT seen > 100%. It matches the progress in the snapshot section

**Comment by meldafrawi** [comment]
Validation: **PASSED**
