### ISSUE TITLE
[BUG] Error message displayed when a backup restore fails can be modified

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1262]
**Describe the bug**
Error message displayed when a backup restore fails can be modified to reflect the actual failure

**To Reproduce**

- Create a volume, attached to a workload, write some data.
- Create a backup
- Restore from this back
- While the restoration is in process, delete the actual backup from Backup page in Longhorn
- The restoration fails with error message: `AWS Error: NoSuchKey The specified key does not exist. <nil> 404 B527C26523A29EA8`
<img width="1657" alt="Screen Shot 2020-04-27 at 1 08 58 PM" src="https://user-images.githubusercontent.com/26032343/80425631-e5cc4f00-8898-11ea-9192-62f5d1bb6a89.png">

**Expected behavior**
Error message can be modified to reflect that the restore process has failed.

**Environment:**
 - Longhorn version: master- 04/27/2020
 - Kubernetes version: 1.17.5
 - Node OS type and version: RKE Linux - DO cluster

**Comment by yasker** [comment]
We need a way to indicate the restoration failure in general.

Related to https://github.com/longhorn/longhorn/issues/1260

**Comment by sowmyav27** [comment]
Another use case which requires a better display/handling of the error message displayed - 

- Create a volume, attached to a workload, write some data.
- External backupstore is configured on minio server
- Create a backup
- Restore from this back
- While the restoration is in process, disconnect Minio by deleting the pod where minio is running
- restoration fails with error - 
`AWS Error: Forbidden Forbidden <nil> 403`

**Expected Result:**
A better error message can be displayed to indicate the failure

**Comment by ryantiger658** [comment]
Hey all! I am getting this error trying to do a DR recovery. Where can I go to get more accurate information to debug the issue?

**Comment by innobead** [comment]
We should have a lock for the remote backup during restore to avoid deletion? 

@yangchiu Is this still valid? Could you help quickly check? Thanks.

cc @longhorn/qa

**Comment by innobead** [comment]
Duplicated of https://github.com/longhorn/longhorn/issues/1867
