### ISSUE TITLE
[BUG] Leftover data in backupstore from an interrupted backup deletion process is not deleted in subsequent delete backup calls

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1263]
**Describe the bug**
Leftover data in backupstore from an interrupted backup deletion process is not deleted in subsequent delete backup calls

**To Reproduce**

1. Create a volume
2. Write about 800M of data in it in file1.
3. Take a backup b1. The block space in backupstore will be of size 800M
4. Overwrite file1 with 800M of data.
5. Take another backup b2. The block space in backupstore will be of size 800M *2 
6. Delete b1
7. Interrupt the deletion process by deleting the monghorn manager pod handling the backup deletion process
8. The backup file gets deleted from Longhorn UI and the backup store.
9. But the block size still is approx 800*2 M
10. Delete b2 
11. The block space in backupstore will be of size 800M

**Expected behavior**
The block space in backupstore should be 0 

**Environment:**
 - Longhorn version: master - 04/27/2020
 - Kubernetes version: 1.17.5
 - Node OS type and version: RKE DO Linux

**Comment by joshimoo** [comment]
covered by longhorn/longhorn#1435

**Comment by joshimoo** [comment]
## Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged?
The PR is at

* [ ] Is the reproduce steps/test steps documented?

* [ ] **If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at

* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at

* [ ] **if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at 

* [ ] **If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at

* [ ] **if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at

* [ ] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at

**Comment by khushboo-rancher** [comment]
Verified on master - 06-10-2020

Verification - **Passed**

**Steps followed:**
1. Create a volume
2. Write about 800M of data in it in file1.
3. Take a backup b1. The block space in backupstore will be of size 800M
4. Overwrite file1 with 800M of data.
5. Take another backup b2. The block space in backupstore will be of size 800M *2 
6. Delete b1
7. Interrupt the deletion process by deleting the monghorn manager pod handling the backup deletion process
8. The backup file gets deleted from Longhorn UI and the backup store but the block size still is approx 800*2 M
9. Delete b2 
10. All blocks got deleted.

**Comment by meldafrawi** [comment]
E2E Automation test is covered by https://github.com/longhorn/longhorn-tests/pull/352
