### ISSUE TITLE
[BUG] Manual and recurring backups are not being triggered

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1266]
**Describe the bug**
Manual and recurring backups are not being triggered

**To Reproduce**

- Create a volume, attach to workload, write data and take some backups.
- Schedule recurring backups - every minute
- Delete all the backups by clicking on "Delete all backups"
- All the backups are deleted on S3
- Manual backups and scheduled backups happen correctly after this
- they are seen uploaded in S3
- few recurring backups get taken
- Delete all backups now
- Delete a replica, wait for it to rebuild
- Now manual backups do not happen
- recurring backups do not happen

**Expected behavior**
Manual and recurring backups should happen

**Note:**
The above set of steps do not always reproduce the issue

**Log**
[longhorn-support-bundle_134e1861-4794-4b3c-94df-53d762c82e3c_2020-04-28T18-02-18Z.zip](https://github.com/longhorn/longhorn/files/4547939/longhorn-support-bundle_134e1861-4794-4b3c-94df-53d762c82e3c_2020-04-28T18-02-18Z.zip)

**Environment:**
 - Longhorn version: master- 04/27/2020
 - Kubernetes version: 1.17.5 
 - Node OS type and version: rke DO linux cluster

**Comment by joshimoo** [comment]
Can you confirm that the backups are not getting created on S3?

Below is an issue I had, that looked similar to this one, and might just be a UI issue?

Repro:
- create backups
- delete replica associated with backups
- ui /backup no longer shows the backups (also does not call backupvolumes api)
- create new backup
- ui /backup still blank (and no call to backupvolumes api)

Verification:
- call via post request: /v1/backupvolumes/manual-test?action=backupList shows all backups (past, new one)
- call to /v1/volumes/manual-test backupStatus has the newly created backup after replica rebuild.
- s3 has the backup file (test-minio)

**Comment by sowmyav27** [comment]
Verified on master (05/07/2020)

**Steps to reproduce this issue on 0.8.1 version of longhorn:**

1. Create a volume, write data into the volume `vol-1`.
2. Take backup - b1, b2 for `vol-1`.
3. Go to the backup store - S3. Verify the last backup in `volume.cfg` is b2. Delete b2 from S3
4. Take backup - b3 for `vol-1`.
5. Manual backups are NOT created anymore.
6. Enable recurring backups for `vol-1`.
7. Recurring backups are NOT created anymore.

On master - steps:

1. Create a volume, write data into the volume `vol-1`.
2. Take backup - b1, b2 for `vol-1`.
3. Go to the backup store - S3. Verify the last backup in `volume.cfg` is b2. Delete b2 from S3
4. Take backup - b3 for `vol-1`.
5. b3 is created successfully.
6. Delete b3 from S3
7. Enable Recurring backups, recurring backups are created successfully.
