### ISSUE TITLE
[BUG] Update architecture docs

### ISSUE THREAD

**Issue by catherineluse** [longhorn/longhorn#1274]
This doc update comes from [feedback in Slack](https://rancher-users.slack.com/archives/CC2UQM49Y/p1588178476080200):

> i guess that this example is no more true
> 
> > For example, in a large-scale deployment with 100,000 Docker volumes each with two replicas, there will be 100,000 controller containers and 200,000 replica containers. In order to schedule, monitor, coordinate, and repair all these controllers and replicas a storage orchestration system is needed.
> 
> https://longhorn.io/docs/0.8.1/architecture/
> as when creating new volumes no more longhorn pods are created and all replicas of different volumes in the same worker are using the same instance-manager pod

Anywhere in the docs that it says there is a dedicated longhorn pod for each replica, we should update it to say that replicas are sharing the same instance-manager pod.

**Comment by yasker** [comment]
Created https://github.com/longhorn/website/pull/117

**Comment by catherineluse** [comment]
I think this issue can be closed because I merged the doc into staging.
