### ISSUE TITLE
[BUG] Pods using xfs filesystem fails with health check

### ISSUE THREAD

**Issue by ShylajaDevadiga** [longhorn/longhorn#1276]
**Describe the bug**
Pods using Storage class with fstype: xfs fails CrashLoopBackOff

**To Reproduce**
Create Storage class with fstype: xfs
Create pvc
Create pod to use the pvc

**Expected behavior**
Pods should be in running state and mountpoint should be accessible

**Log**
```
Events:
  Type     Reason                  Age                     From                      Message
  ----     ------                  ----                    ----                      -------
  Warning  FailedScheduling        <unknown>               default-scheduler         running "VolumeBinding" filter plugin for pod "mysql-868cbbc584-2m22v": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling        <unknown>               default-scheduler         running "VolumeBinding" filter plugin for pod "mysql-868cbbc584-2m22v": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled               <unknown>               default-scheduler         Successfully assigned default/mysql-868cbbc584-2m22v to ip-172-31-3-136
  Normal   SuccessfulAttachVolume  3m56s                   attachdetach-controller   AttachVolume.Attach succeeded for volume "pvc-7b0baf16-778e-46a9-a14a-2fc3a2e94b8b"
  Normal   Killing                 2m52s (x3 over 3m32s)   kubelet, ip-172-31-3-136  Container mysql failed liveness probe, will be restarted
  Normal   Pulled                  2m50s (x4 over 3m51s)   kubelet, ip-172-31-3-136  Container image "mysql:5.6" already present on machine
  Normal   Created                 2m50s (x4 over 3m51s)   kubelet, ip-172-31-3-136  Created container mysql
  Normal   Started                 2m50s (x4 over 3m51s)   kubelet, ip-172-31-3-136  Started container mysql
  Warning  Unhealthy               2m42s (x10 over 3m42s)  kubelet, ip-172-31-3-136  Liveness probe failed: ls: cannot access '/var/lib/mysql/lost+found': No such file or directory
```
**Environment:**
 - Longhorn version: 0.8.1
 - Kubernetes version: 1.18.2, k3s v1.18.2-rc2+k3s1
 - Node OS type and version: Ubuntu 18.04

**Additional context**
Liveness:       exec [ls /var/lib/mysql/lost+found]

**Comment by yasker** [comment]
We need to find a way to check XFS's availability since it doesn't have `lost+found`.

Also, let's check if `ls /<data-dir>` works.

**Comment by boknowswiki** [comment]
@ShylajaDevadiga thanks for providing the information about reproducing this issue.

After discuss with @yasker, since we don't support xfs filesystem auto re-mount in Longhorn. So we don't need the livenessprobe to trigger pod restarting and trigger longhorn to re-mount the volume.

Please refer to this document:
https://longhorn.io/docs/0.8.1/high-availability/recover-volume/

Thanks,
Bo
