### ISSUE TITLE
[BUG] UI does not show backups for Volume when accessed via the link (Click here for completed backups)

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#1277]
**Describe the bug**
After creating a backup then clicking on the link: "Click here for completed backups."
the backup details page for that volume will not show the backups instead it will show select a volume first. The reason seems to be it's missing the state=true/false param, when added the page correctly loads the backups for the specified volume. Please see attached screenshots for an example of this.

**To Reproduce**
1. Create a backup on volume (X) via the snapshot timeline
2. Click on 'Click here for completed backups'
3. See 'select a volume first'

**Expected behavior**
Show the backups for Volume (X)

**Environment:**
 - Longhorn version: 0.8.1
 - Node OS type and version: Linux Ubuntu (linode)

**Additional context**
![image](https://user-images.githubusercontent.com/1287163/80665353-17d2e200-8a4e-11ea-978c-d327634b960d.png)
![image](https://user-images.githubusercontent.com/1287163/80665335-0984c600-8a4e-11ea-915b-ad9d0109d95b.png)

**Comment by jenting** [comment]
I think this issue is no more valid.
