### ISSUE TITLE
[BUG]Rebuild doesn't work for the restoring volume or DR volume

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1279]
**Describe the bug**
When a replica of a restoring volume fails, Longhorn should directly restore the data to a new replica during the rebuild progress, rather than syncing data from the restoring replicas.

Right now Longhorn just simply disables the rebuild for restore volumes and DR volumes.

See the 1st part of #1270 for details.

**Additional context**
Need to consider:
1. How to restore data rather than syncing files for the rebuilding replica.
2. How to make sure the restoring/rebuild state still works fine.
3. DR volume can continue to do incremental restoration after the rebuild.
4. Restoring volumes will be still detached automatically after rebuilding and restoration.

**Comment by shuo-wu** [comment]
Analysis and design(Draft): https://docs.google.com/document/d/1XTKV-27n8qvBesFJdPjMlNyINiK65b9FRfNPnswNDsc/edit

**Comment by yasker** [comment]
This is way more complicated than we expected. We need a LEP for this.

**Comment by shuo-wu** [comment]
May need to change the color for rebuilding restore/DR volume
![Screen Shot 2020-08-14 at 1 57 22 PM](https://user-images.githubusercontent.com/47542419/90218367-33fc6280-de36-11ea-89ca-d70d315b4ab7.png)

**Comment by yasker** [comment]
This issue has been in Review for 12 days. What's blocking this issue to be moved to Merged?

**Comment by shuo-wu** [comment]
1. UI modification is required.
2. The engine image incompatibility test failure is not checked. And the backup & restore tests seem to become slower. Not sure if we need to track these issues separately.

**Comment by khushboo-rancher** [comment]
Verified on longhorn Master - 09/03/2020

Validation - **Pass**

**Tested below scenarios:**
1. Restore of a volume having one or more backups.
2. Rebuilding interrupted during the restoration by deleting the replica on the attached node and other nodes. - A new replica rebuilt during the process of restoration. 
3. The attached node power down and rebooted while the restoration was in progress. - Volume in the restoration process detached and attached to a new node and rebuild completed.
4. The replica node power down and rebooted while the restoration was in progress. - A new replica rebuilt during the process of restoration.
5. The attached node power down and rebooted while the DR volume restore was in progress. - DR Volume detached and attached to a new node and rebuild completed.
6. The replica node power down and rebooted while the DR volume restore was in progress. - A new replica rebuilt during the process of restoration.
7. The attached Node rebooted while incremental rebuild for DR volume was in progress. - DR Volume detached and attached to a new node and rebuild completed.
8. The replica Node rebooted while incremental rebuild for DR volume was in progress. - A new replica rebuilt during the process of restoration.
9. Volume Expansion
10. Live upgrade and verified the data.
11. Tested ```Backup restore operations test cases``` from https://rancher.atlassian.net/wiki/spaces/LON/pages/368640004/Backup
