### ISSUE TITLE
Set hard anti-affinity by default

### ISSUE THREAD

**Issue by aspettl** [longhorn/longhorn#1282]
I'm interested in the rationale for the current default of a soft anti-affinity for replicas. I was surprised and it's the first option I change.
As https://github.com/longhorn/longhorn/issues/586 says where the hard anti-affinity was announced, in most cases scheduling two replicas on the same node makes no sense. I agree. For clusters with only 3 nodes, it's important to me that when the third one comes back, the replicas are restored there. And for clusters with 4 nodes or more, there should not really be much difference in practice anyway.

Am I missing something? Or could we aim to change the default in an upcoming (major) release?

**Comment by yasker** [comment]
Previously we don't want to change the behavior suddenly to confuse the user, also the new feature wasn't tested enough. We can change it to hard anti-affinity by default in the next release.

**Comment by boknowswiki** [comment]
Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [ ] ~~Is the reproduce steps/test steps documented?~~
* [ ] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~
* [ ] ~~**If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?~~
* [ ] ~~**if labeled: require-automation-engine** Has the engine integration test been merged?~~
* [ ] ~~**if labeled: require-doc** Has the necessary document PR submitted or merged?~~

**Comment by yasker** [comment]
@meldafrawi I suspect the default change for soft anti-affinity might cause issues in the integration test case. Can you run the full integration tests using the latest merged code?

**Comment by sowmyav27** [comment]
**Validated on master - 05/18/2020**

- In longhorn settings page - 
`Replica Zone Level Soft Anti-Affinity:` : True
`Replica Node Level Soft Anti-Affinity:` : False

**Comment by yasker** [comment]
Integration test now runs with hard anti-affinity by default.
