### ISSUE TITLE
test: Add test case for multiple paths on the same filesystem in the node default disk config annotation

### ISSUE THREAD

**Issue by boknowswiki** [longhorn/longhorn#1293]
This test case is for if there are two or more disk paths in the default disk config annotation cat not in the same filesystem in the node.

The test is for this issue:
https://github.com/longhorn/longhorn/issues/1285

Test steps:
1. Make a clean condition: no disk, no tag, no default disk related annotation.
2. Create default disk annotation with two disks different paths, but in the same filesystem.
3. Enable "Setting/General/Create Default Disk on Labeled Nodes".
4. Wait for node update, and check there should be no disk and no tag created.
5. Cleanup test environment: remove default disk related annotation

Expected error message from longhorn-manager:
[longhorn-manager-t87z5] time="2020-05-05T01:56:25Z" level=warning msg="Kubernetes node: invalid annotation node.longhorn.io/default-disks-config: config: the disk /var/lib/longhorn/ is the samefile system with /root, fsid 58fe937c58377e45"

**Comment by boknowswiki** [comment]
Verified the test case, the got the expected error message:

[longhorn-manager-t87z5] time="2020-05-05T01:56:25Z" level=warning msg=" [{\"path\":\"/root\",\"allowScheduling\":false,\"storageReserved\":1024,\"name\":\"root-name\"},{\"path\":\"/var/lib/longhorn/\",\"allowScheduling\":false,\"storageReserved\": 1024,\"name\":\"default-name\"}]" 
[longhorn-manager-t87z5] time="2020-05-05T01:56:25Z" level=warning msg="Kubernetes node: invalid annotation node.longhorn.io/default-disks-config: config: the disk /var/lib/longhorn/ is the samefile system with /root, fsid 58fe937c58377e45"

**Comment by boknowswiki** [comment]
Verified with local build longhorn-manager:

[longhorn-manager-t87z5] time="2020-05-05T16:56:21Z" level=warning msg="[{\"path\":\"/root\",\"allowScheduling\":false,\"storageReserved\":1024,\"name\":\"root-name\"},{\"path\":\"/var/lib/longhorn/\",\"allowScheduling\":false,\"storageReserved\": 1024,\"name\":\"default-name\"}]" 
[longhorn-manager-t87z5] time="2020-05-05T16:56:21Z" level=warning msg="Kubernetes node: invalid annotation node.longhorn.io/default-disks-config: config: the disk /var/lib/longhorn/ is the samefile system with /root, fsid 58fe937c58377e45"

**Comment by meldafrawi** [comment]
`test_node_config_annotation_invalid` passed for two consecutive runs. `longhorn-tests/421` & `longhorn-tests/422`
