### ISSUE TITLE
[BUG] Corrupting one of the snapshot in the chain from one of the replicas results in loss of data.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1298]
**Describe the bug**
If a snapshot data in one of the replica is corrupted, The data get lost.

**To Reproduce**
1. Create a volume (3 replicas, 3 nodes), attach it to a pod.
2. Write data to volume and take snapshot( repeat this for 3 snapshots). S1, S2 and S3
3. Go to the one of the node and delete/modify the content of a snapshot S2. volume-snap----.img
4. Revert to snapshot S2 or any snapshot taken after S2.
5. Check the data in volume. 
6. The data after snapshot S2 will be gone.

**Expected behavior**
A replica should have rebuilt and data should get replaced with other correct replica.

**Environment:**
 - Longhorn version: Master- 05-04-2020
 - Kubernetes version: v1.17.5 rancher1-3
 - Node OS type and version: ubuntu 18.04 do node

**Comment by yasker** [comment]
This is not fixable currently in Longhorn since we don't have ECC or similar mechanism.

We can provide a workaround to identify and delete the corrupted replica.

**Comment by sangeethah** [comment]
@khushboo-rancher  Can you confirm the following:
1. We will see the sane problem reported even when you revert to S3 which is 1 snapshot ahead of the corrupted snapshot ? Basically we will see this problem when reverting to any snapshot that has the corrupted snapshot in its chain ?
2. Also in the scenario mentioned , 
Instead of these steps (after S2 is corrupted),
```
Revert to snapshot S2.
Check the data in volume.
```
If we try to just read/write to the volume , is there a possibility that we will we also encounter the same issue ?

**Comment by sowmyav27** [comment]
Tested the following scenarios

**Scenario#1**

- attach volume to a node
- Write Data to file1 -->S1
- Write Data to file2 --> S2 
- Write Data to file3 --> S3
- Corrupt S2 data on one replica
- Write more data to volume - create file4
- Take a new Snapshot -> S4
- Revert to S3 
- Volume has file1 ONLY. 

**Expected:**
Data should NOT be lost.
Volume should have file1, file2, file3

**Scenario#2**

Volume has only ONE replica 

- attach volume to a node
- Write Data to file1 -->S1
- Write Data to file2 --> S2 
- Write Data to file3 --> S3
- Corrupt S2 data on the replica
- detach the volume, attach the volume

Trying to access the volume on the node gives the below error
```
mount vol-new-2 /mnt/new2/
mount: /mnt/new2: wrong fs type, bad option, bad superblock on /dev/longhorn/vol-new-2, missing codepage or helper program, or other error.
```

**Note:**
Without detaching and reattaching the volume, no issue is seen while writing/reading from the data.

**Comment by khushboo-rancher** [comment]
With reference to https://github.com/longhorn/longhorn/issues/1298#issuecomment-624863479
Yes, we will see the problem when reverting to any snapshot after the corrupted snapshot. I've updated the steps to reproduce.

**Comment by yasker** [comment]
As we discussed, any snapshot after the corrupted one has no guarantee to be right. But the one before corruption should be fine.

I am planning to address how to figure out which replica is bad in https://github.com/longhorn/longhorn/issues/60 , so user can delete it and workaround the issue.

**Comment by yasker** [comment]
Documentation ready at https://github.com/yasker/longhorn/wiki/Data-recovery-%5BDRAFT%5D . Will be moved to the website soon.

Regarding this issue, it's https://github.com/yasker/longhorn/wiki/Identify-the-corrupted-replica-%5BDRAFT%5D

**Comment by catherineluse** [comment]
I think this issue can be closed because the docs are merged

**Comment by yasker** [comment]
@khushboo-rancher Can you try the instruction on https://staging.longhorn.io/docs/0.8.1/advanced-resources/data-recovery/corrupted-replica/

**Comment by khushboo-rancher** [comment]
Instructions are clear and work, but do we really have to scale down the workload?
If it is precautionary measure and user should do it, should we add a last point something like below?
 ```scale up the workload and you will see error is gone and data is intact```

**Comment by yasker** [comment]
@khushboo-rancher It's better to scale down the workload otherwise any write on the fly will cause the checksum to be different.

I've added the last line in the PR at https://github.com/longhorn/website/pull/133

**Comment by yasker** [comment]
@khushboo-rancher document updated at https://staging.longhorn.io/docs/1.0.0/advanced-resources/data-recovery/corrupted-replica/

**Comment by khushboo-rancher** [comment]
https://staging.longhorn.io/docs/1.0.0/advanced-resources/data-recovery/corrupted-replica/ looks good.
