### ISSUE TITLE
[BUG] Nightly Upgrade test: offline node test is failing and causing all following tests to fail.

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#1303]
**Describe the bug**
Failed offline node test will cause all it's following tests to fail, since Node will not start up after test is done.

**To Reproduce**
1. Install Longhorn v0.8.1
2. Upgrade to Longhorn master
3. Run offline node test

**Expected behavior**
On teardown, test should wait for instance to startup after being shutdown, an report ready state to API server.

**Log**
```
Error Message
test teardown failure
Stacktrace
def finalizer():
        node_worker_label = 'node-role.kubernetes.io/worker'
    
        k8s_api_client = get_core_api_client()
        longhorn_api_client = get_longhorn_api_client()
        cloudprovider = detect_cloudprovider()
    
        for node_item in k8s_api_client.list_node().items:
            if node_worker_label in node_item.metadata.labels and \
                    node_item.metadata.labels[node_worker_label] == 'true':
                node_name = node_item.metadata.name
    
                if is_node_ready_k8s(node_name, k8s_api_client) is False:
                    node = cloudprovider.node_id(node_name)
    
                    cloudprovider.node_start(node)
    
                    node_up_k8s = wait_for_node_up_k8s(node_name,
                                                       k8s_api_client)
    
>                   assert node_up_k8s
E                   assert False

test_infra.py:140: AssertionError
```

**Environment:**
 - Longhorn version: master
 - Kubernetes version: 1.17 
 - Node OS type and version: Ubuntu 18.04

**Additional context**

**Comment by meldafrawi** [comment]
Observations:
- node shutdown command reported failure each time after instance been deployed, however the instance will be powered off.
- if instance is restarted, test will pass.

**Comment by yasker** [comment]
We will disable the node offline integration test by default for now. Move the issue to the next release.

**Comment by meldafrawi** [comment]
Affected by: https://github.com/longhorn/longhorn-tests/pull/538

We have moved nightly tests to use aws, so we need a new implementation for communicating with AWS APIs.

**Comment by yasker** [comment]
Considering increase the priority of the issue. Offline node test is critical for the stateful workload.

**Comment by innobead** [comment]
@meldafrawi Please summarize the status as we discussed. Thanks.

**Comment by meldafrawi** [comment]
Update: 
- I was able to move offline node tests from DO to AWS, but still some changes has to be made to integrate the test to our nightly tests framework.
- we've some changes in node failure handling, so `test_offline_node_with_attached_volume_and_pod` will not reflect the current system behavior, so I will remove it

**Comment by meldafrawi** [comment]
Update: 

- PR is ready for Review
- test_infra result (local): 

```
<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="0" hostname="longhorn-test" name="pytest" skipped="0" tests="1" time="378.484" timestamp="2021-07-12T21:45:25.504118"><testcase classname="tests.test_infra" file="tests/test_infra.py" line="130" name="test_offline_node" time="378.067"></testcase></testsuite></testsuites>bash-5.1# 

```

**Comment by innobead** [comment]
@meldafrawi close this if the test passes later. Thank you.

**Comment by meldafrawi** [comment]
Test is passing on amd64, but failing on arm64 arch, since k3s is not setting `kubernetes.io/worker=true` label, so we need to adjust for running on k3s, ans possibly RKE2 in the future.

**Comment by yangchiu** [comment]
Fixed in https://github.com/longhorn/longhorn/issues/7463.
