### ISSUE TITLE
[FEATURE] Rebuild using existing replica data

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1304]
Using a new replica every time for rebuild will waste lots of network bandwidth and disk space. We should try to rebuild using existing replica's data.

Require #1269

**Comment by yasker** [comment]
The PR is missing an explanation for how the feature works.

Also, more detailed test steps are needed, especially around the scheduling part.

**Comment by shuo-wu** [comment]
More explanations are added as the implementation comments.
And one more test skeleton is introduced for the replica reuse with scheduling case.

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master - 10/27/2020

Validation - **Fail**

Scenarios 3 and 4 failed. When a node is rebooted, the replica on it got deleted and recreated. The ```Replica Replenishment Wait Interval``` setting was set to 600 sec.

Validated with a cluster up of 1 etcd/control plane, 3 worker nodes.
Scenarios tested:
1. Failed one replica by crashing the replica instance manager. - Replica went into rebuilding state for a while and becomes healthy, data validated.
2. Deleted volume-head data in a replica - The same replica rebuilt and become healthy.
3. Had volume with 2 replicas and rebooted one of the replica node - A new replica rebuilt on an available node.
4. Had volume with 3 replicas and rebooted one of the replica node - A new replica rebuilt on an available node.

[longhorn-support-bundle_7a2a3332-a6b3-4eae-84f4-c267b2844b59_2020-10-28T00-49-06Z.zip](https://github.com/longhorn/longhorn/files/5448859/longhorn-support-bundle_7a2a3332-a6b3-4eae-84f4-c267b2844b59_2020-10-28T00-49-06Z.zip)
Volume name - pvc-68411985-ea3b-4b4f-8d0b-55f8f5e436b2
Node- khushboo-test-lh-wk2 rebooted
Replica before reboot - pvc-68411985-ea3b-4b4f-8d0b-55f8f5e436b2-6841b31a
Replica after reboot - pvc-68411985-ea3b-4b4f-8d0b-55f8f5e436b2-f19caabb
Time  - ~00:43:40

**Comment by shuo-wu** [comment]
The reason of the above test failure:
When the node is rebooted, the node ready condition hasn't been updated. Then Longhorn immediately and continuously retries reusing the failed replica on the node for 3 times, which reaches the max retry count. Then Longhorn considers the failed replica as no longer available. 
Solution:
Add backoff interval for the retry.

**Comment by shuo-wu** [comment]
2 more manual tests are needed for https://github.com/longhorn/longhorn-manager/pull/753

Test 1:
1. Deploy Longhorn v1.0.2.
2. Create and attach a volume.
3. Disable scheduling for 1 node.
4. Crash the replica on the node.
5. Upgrade Longhorn to the latest. The volume keeps robustness `Degraded`.
6. Enable scheduling for the node. Verify the failed replica of the existing degraded volume will be reused.

Test2:
1. Deploy the latest Longhorn.
2. Create and attach a volume.
3. Update `Replica Replenishment Wait Interval` to 60s.
4. Crash a replica: removing the volume head file and creating a directory with the volume head file name. Then the replica reuse will continuously fail. e.g., `rm volume-head-001.img && mkdir volume-head-001.img`
5. Verify:
    1. There is a backoff interval for the failed replica reuse
    2. A new replica will be created after (around) 60s despite the failed replica reuse is in backoff.

**Comment by shuo-wu** [comment]
It seems that the existing data reusage doesn't speed up the rebuilding progress. 
Here is the performance test:
1. Create and attach a volume.
2. Write 25Gi~30Gi data to the volume.
3. Crash one replica to trigger failed replica reusage. According to the instance manager log, this rebuilding takes 9 minutes.
4. Directly delete one replica to trigger new replica replenishment. The new replica rebuilding takes 10 minutes.

**Comment by yasker** [comment]
Then I guess the majority of the time is used on calculating the checksum. So https://github.com/longhorn/longhorn/issues/1948 should help a lot.

Or maybe, if the rewriting of the data is much faster, we can rewrite the data without calculating the checksum. Though it might unnecessarily increase the disk wear though.

**Comment by shuo-wu** [comment]
I will check how long the data writing part will take compared with the whole file syncing progress. If the checksum calculating part is the majority of the file syncing, we may be able to directly remove it.

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master - 11/10/2020

Validation - **Pass**

Scenarios tested:
1. Failed one of the replicas by killing instance manager replica - The replica went in failed state and then the same replica got rebuilt.
2. Failed one replica by killing IM-r and reduce the replica count to 1. After 5 minutes, updated the replica count to 3. - The failed replica got rebuilt.
3. Failed the replica by rebooting the node. - The failed replica got rebuilt.
4. Removed the volume.head.img file from replica to fail a replica. - The failed replica got rebuilt and the volume-head.img file recreated.
5. Shut down a node for just less than the ```Replica Replenishment Wait Interval```. - The failed replica got rebuilt.
6. Reduce ```Replica Replenishment Wait Interval``` to 60 sec, shut down the node having a replica for more than 60 sec. - A new got rebuilt.
7. Enable ```Disable Replica Rebuild```, fail one replica and delete the failed replica. - A new replica got created before the replenishment wait.
8. Corrupt replica data by removing volume-head.img and creating a directory volume-head.img. - Longhorn tried to use the failed replica till the replenishment wait interval, then a new replica got created.
9. Volume failed in longhornv1.0.2 and upgrade longhorn to master. - The failed replica got rebuilt.

Covered all the manual test cases written https://github.com/longhorn/longhorn/blob/master/enhancements/20200821-rebuild-replica-with-existing-data.md#test-plan

@shuo-wu Scenario mentioned https://github.com/longhorn/longhorn/blob/master/enhancements/20200821-rebuild-replica-with-existing-data.md#reuse-failed-replicas-for-an-old-degraded-volume-after-live-upgrade will not work as mentioned.
>> Reuse failed replicas for an old degraded volume after live upgrade:
Deploy Longhorn v1.0.2.
Create and attach a volume. Write data to the volume.
Disable scheduling for 1 node.
Crash the replica on the node.
Upgrade Longhorn to the latest. Verify the volume robustness Degraded.
Enable scheduling for the node. Verify the failed replica of the existing degraded volume will be reused.
Verify the data content, and the volume r/w still works fine.

When a replica is crashed after disabling scheduling for 1 node, longhorn stills tries to create a new replica in v1.0.2 which couldn't get scheduled and once set up is upgrade and node is made schedulable, the new replica will rebuild.

**Comment by shuo-wu** [comment]
@khushboo-rancher Oh, sorry. I delete the new (scheduling failed) replica after the upgrade. But I forget to mention this step.
Here is the updated test step:
1. Deploy Longhorn v1.0.2.
2. Create and attach a volume. Write data to the volume.
3. Disable scheduling for 1 node.
4. Crash the replica on the node.
5. Upgrade Longhorn to the latest. Verify the volume robustness Degraded.
6. Delete the new (scheduling failed) replica. Verify new replicas won't be replenished immediately now. 
7. Enable scheduling for the node. Verify the failed replica of the existing degraded volume will be reused.
8. Verify the data content, and the volume r/w still works fine.

**Comment by yasker** [comment]
@PhanLe1010 Can you work on the integration test for this one?

**Comment by PhanLe1010** [comment]
Sure

**Comment by khushboo-rancher** [comment]
The tests are passing the integration test run.
