### ISSUE TITLE
[FEATURE] Hide the customized default setting by default in Rancher chart

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1308]
It was mistakenly used for configuring the existing Longhorn system. We should make it clear to the user it only works if there is no Longhorn installed before.

**Comment by sowmyav27** [comment]
Verified by applying the latest fixes to a private repo. 

Launch Longhorn app in a project --> Apps in Rancher
"Customize Default Setting" is available.

<img width="1363" alt="Screen Shot 2020-05-14 at 12 20 44 PM" src="https://user-images.githubusercontent.com/26032343/81976633-afebd200-95dd-11ea-9a88-df52027bec4c.png">

When select "true" and enter different values for replicas, etc. Launch the app
App is seen to be deployed with the customized settings.

@meldafrawi Could we change the text to `Customize Default Settings` (with an "s" in settings) instead?

**Comment by sowmyav27** [comment]
Verified the change
<img width="849" alt="Screen Shot 2020-05-18 at 9 48 26 AM" src="https://user-images.githubusercontent.com/26032343/82238862-c9965d80-98ec-11ea-9341-0ab58bb79795.png">
