### ISSUE TITLE
[FEATURE] Backups to Azure Blob Storage

### ISSUE THREAD

**Issue by cloudnautique** [longhorn/longhorn#1309]
**Is your feature request related to a problem? Please describe.**
Azure Blob storage does not provide an S3 compatible API. 

**Describe the solution you'd like**
Backup directly to Azure blob storage solution.

**Describe alternatives you've considered**
Could backup to shared storage but Azure only allows 2 volumes per core to be attached to a node. Users would like to use those for workloads vs. backup storage.

**Comment by eNettMattD** [comment]
+1 for this. It's a significant blocker for us, as we don't want to rely on minio.

**Comment by obsjmartin** [comment]
surprised this keeps getting pushed back. Azure blob storage would be great for backups.

**Comment by johnwc** [comment]
We also need this for backing up to our cloud. Minio seems to [no longer support](https://blog.min.io/deprecation-of-the-minio-gateway/) gateway.

**Comment by innobead** [comment]
ref: https://github.com/rclone/rclone

**Comment by FlorisFeddema** [comment]
Is there any chance this will be added in 1.5? It keeps beeing pushed backs and we would really like to move away from our Minio solution.

**Comment by TBurda** [comment]
#5387

**Comment by johnwc** [comment]
Any movement on this?

**Comment by mantissahz** [comment]
Planned to be added at v1.5.0.
I plan to start the feature recently.
Any suggestion is welcome.

**Comment by johnwc** [comment]
For us, we just need to be able to utilize Azure blob storage to push/pull backups to/from. Being able to set the storage tier during the upload. Hot/Cool/Archive

**Comment by innobead** [comment]
> For us, we just need to be able to utilize Azure blob storage to push/pull backups to/from. Being able to set the storage tier during the upload. Hot/Cool/Archive
> 
> When is the ETA for v1.5.0?

@johnwc 

We are targeting it to the end of June/Q2, but there would be some shifts. BTW, are you running Longhorn on Azure like AKS? Why use Azure blob in your case except for different tiers?

**Comment by johnwc** [comment]
We are running Rancher+Longhorn on-prem. 

Why allow for selecting what tier to push it to blob storage as? Because there are different costs for each tier, and the archive tier also comes with "thaw" time that you have to wait for it to be available to access it. End user needs to be able to tell Longhorn what they need it to be stored as that aligns with their company's policy.

**Comment by innobead** [comment]
Thanks for sharing. Sounds like #5411 is also required for your case.

**Comment by chriscchien** [comment]
Verified **pass** in longhorn master (longhorn-engine `4f6770`, longhorn-manager `705e77`, longhorn-instance-manager `23af7f`, backupstore `228beb`)

Follow [instrucitons](https://longhorn.io/docs/1.5.0/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-azure-blob-storage-backupstore) setup Azure blob storage backupstore and setup 2 clusters using this blob storage backupstore, I can :

- Create multiple backup to blob storage backupstore
- Restore each backup to volume has succeeded, data intact.
- Restore each backup to the other cluster has succeeded, data intact.
- Create disaster recovery volume in the other cluster has succeeded, after active the disaster volume, data is the newest data.

**Comment by innobead** [comment]
@chriscchien do we need any test case for that? I just re-added `require/auto-e2e-test`.  If needed, please reopen, then @mantissahz can help with the test case skeleton. Thanks. 

cc @longhorn/qa

**Comment by chriscchien** [comment]
I am not sure if this is doable but if we can support blob storage in [set_random_backupstore](https://github.com/longhorn/longhorn-tests/blob/b16b1b4f67a42daeff7a6f6a727578f1f65036f4/manager/integration/tests/backupstore.py#L50) then all backup related test cases will be tested on daily regression with this kind of backupstore.

cc @innobead @mantissahz
