### ISSUE TITLE
[FEATURE] Named Installation (multiple per cluster)

### ISSUE THREAD

**Issue by dmayle** [longhorn/longhorn#1314]
**Is your feature request related to a problem? Please describe.**
It would be useful in a production cluster to have multiple longhorn deployments (e.g. blue/green deployments).  This would allow for things like upgrading when there is no live upgrade process, or experimenting on the storage layer itself.

**Describe the solution you'd like**
I'd like to see a way to add a name to the installation such that all paths are separated on disk (e.g. `/var/lib/longhorn/blue` and `/var/lib/longhorn/green`.  It should then be possible to reference the different installations in PersistentVolume yaml.  (I'm not sure whether it makes more sense to use two different driver names, or to have a special volumeAttribute for the installation name)

**Describe alternatives you've considered**
The only way to currently handle this is with unique kubernetes clusters, which is much harder to manage for live traffic.

**Comment by yasker** [comment]
@dmayle Can you elaborate your use case for more than one Longhorn app per cluster? I don't feel blue/green deployment makes much sense for Longhorn since it's more of infrastructure-level software. And not sure how it can help with the live upgrade process as well, because they will likely have the same storage driver name.

You can have more than one StorageClass, which includes different parameters for different PVCs. There is no way to define parameters in the PVC itself in Kubernetes, at least for now.

**Comment by dmayle** [comment]
@yasker the first time I wanted this was during the 0.7.0 to 0.8.0 upgrade, which was not live.  I had to take the cluster completely offline in order to perform the upgrade.

The main reason I'd like this is to allow upgrades without disrupting production traffice.  This way, I could migrate a deployment or statefulset to an already upgraded deployment without having to worry that a failed upgrade will put me into an inconsistent state.

**Comment by yasker** [comment]
Hmm? The volume will form either the new version of Longhorn or the old version? I am not sure why it can help with smoothing the upgrade process.

**Comment by dmayle** [comment]
@yasker by allowing me to avoid it completely.  I would have created a new 0.8.0 installation and migrated my workloads from one installation to the other, one job at a time.

On the other hand, I just went through my second 0.7.0 to 0.8.0 upgrade, and this time it went smooth as silk.

**Comment by yasker** [comment]
@dmayle Can you elaborate how you plan to migrate your workload from one Longhorn version to another without downtime? I still don't understand. It seems would involve downtime anyway.

**Comment by dmayle** [comment]
@yasker for example, minio is 4 replicas.  I take it down to 3, and bring up 1 replica on the second installation.  Wait for it to recover, and repeat.  For postgres, I bring up a replica on the new deployment, promote to master, and start bringing up machines on the new storage installation.  This only works for my services that support high availability, but that's why I use kubernetes in the first place.

**Comment by yasker** [comment]
@dmayle I am not sure how would you able to bring up one on the second installation. By changing the StorageClass name?

For Longhorn upgrade, manager part is separated from engine part. You can upgrade the manager, and even when managers are upgraded, we will make sure the existing attached volume on the old engine version won't be affected (except for the rebuild/snapshot etc functions). Then you can detach volume one by one to upgrade the engine if engine offline upgrade is required. I am not sure if Kubernetes StatefulSet allows you to bring down e.g. the second pod but let the others running though.

**Comment by dmayle** [comment]
@yasker That wasn't clear to me from the docs.  The docs specify that for an offline upgrade you need to detach *all* workloads and use the batch upgrade procedure.  If you can still perform than one-by-ony, it does make this much less of an issue.

As to how I would bring them up on a second installation, I wouldn't use Kubernetes concepts, I would use HA concepts from each deployment.  For example, with Minio, I would bring up a second StatefulSet and add join the new hosts to the old StatefulSet.
