### ISSUE TITLE
[FEATURE] Improve functionality of Guaranteed Engine CPU setting

### ISSUE THREAD

**Issue by catherineluse** [longhorn/longhorn#1318]
Currently, we expose the parameter Guaranteed Engine CPU in the Longhorn settings, and the workflow is:

1. Change the parameter
2. Manually restart the instance manager

It would be better with the following improvements:

- Longhorn should restart the instance manager automatically if the Guaranteed Engine CPU changes.
- ~~Longhorn should stop you from changing this parameter if you have a volume attached to a node.~~ Currently, we don't have a way to stop the user from doing this. We will introduce a `Danger Zone` section of settings instead.

**Comment by yasker** [comment]
Move to v1.0.1.

Note: it's better if we can merge this change with taint tolerance change resulted in the recreate of instance managers etc.

**Comment by yasker** [comment]
Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
* [ ] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [ ] **if labeled: require-automation-engine** Has the engine integration test been merged?
* [ ] **if labeled: require-doc** Has the necessary document PR submitted or merged?

**Comment by yasker** [comment]
Check the automation test case for the test steps.

**Comment by yasker** [comment]
We've added a setting section called `Danger Zone`. UI can show a red frame (instead of grey) for the `Danger Zone` settings.

**Comment by smallteeths** [comment]
Modify as shown
![Jietu20200518-165919](https://user-images.githubusercontent.com/27733391/82194268-18fa7f00-9929-11ea-8967-5bb4c5b35eaa.jpg)

**Comment by sowmyav27** [comment]
**Verified on latest master - 05/18/2020 and UI tag: `wangsiye/longhorn-ui:941d022`**

- Verified with the following Guaranteed Engine CPU setting values

- - 0.2 -  instance manager pods are seen with 200m CPU requests on all nodes
- - 0.1 -  instance manager pods are seen with 100m CPU requests on all nodes
- - 200m - instance manager pods are seen with 200m CPU requests on all nodes
- - 10 - The instance manager pods DO NOT come up.

**Comment by sowmyav27** [comment]
**Validated on master - 05/18/2020 22:00 PDT**

Validation: **`PASSED`**

**Steps:**
- Ui shows Guaranteed Engine CPU under Danger Zone
<img width="1444" alt="Screen Shot 2020-05-18 at 10 33 28 PM" src="https://user-images.githubusercontent.com/26032343/82290301-6f80b100-995b-11ea-9e20-0166661b1480.png">

**Comment by boknowswiki** [comment]
@meldafrawi , just checking with you, if you are not working on the test case for this issue. I can work on the test case. Thanks.

**Comment by meldafrawi** [comment]
@boknowswiki, sure, Thanks.
