### ISSUE TITLE
[BUG] No error message displayed on UI when there is Invalid backup file in S3

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1320]
**Describe the bug**
No error message displayed on UI when there is Invalid backup file in S3

**To Reproduce**
- In S3, edit a backup file - make it an invalid json data - (removed "}}" from the file in the end)
- Save the file and upload it back to S3.
- Go to Backup --> Backup list page
- Error seen in backupList view - API

```
"messages": {
        "error": "unexpected EOF"
      },
```
- NO error is seen on the UI
<img width="1639" alt="Screen Shot 2020-05-11 at 8 30 21 PM" src="https://user-images.githubusercontent.com/26032343/81635573-58274e00-93c6-11ea-9bd1-2ed7bfe9f10e.png">

**Expected behavior**
A error should be visible to the users on the UI for the backup file which is corrupt.

**Environment:**
 - Longhorn version: master - 05/11/2020

**Comment by smallteeths** [comment]
I followed your steps to test, the situation is not the same as yours, as shown
![Jietu20200512-164107](https://user-images.githubusercontent.com/27733391/81663944-ab0a0f80-9471-11ea-9816-9444e0ccc286.jpg)

**Comment by joshimoo** [comment]
@smallteeths have you updated to the newest longhorn-manager/engine@master?

**Comment by sowmyav27** [comment]
**Verified on master, ui image: `wangsiye/longhorn-ui:79c09d9`**

Validation: **`PASSED`**

- In S3, edit a backup file - make it an invalid json data - (removed "}}" from the file in the end)
- Save the file and upload it back to S3.
- Go to Backup --> Backup list page
- Error is seen on the UI.
<img width="1869" alt="Screen Shot 2020-05-13 at 3 42 23 PM" src="https://user-images.githubusercontent.com/26032343/81873996-c76d8100-9531-11ea-8b03-e9fa9451296b.png">

**Comment by sowmyav27** [comment]
**Verified on master - 05/18/2020**

Steps:
In S3, edit a backup file - make it an invalid json data - (removed "}}" from the file in the end)
Save the file and upload it back to S3.
Go to Backup --> Backup list page
Error is seen on the UI.
<img width="724" alt="Screen Shot 2020-05-18 at 2 45 37 PM" src="https://user-images.githubusercontent.com/26032343/82262727-4b4eb100-9916-11ea-8f47-b1413e020676.png">
