### ISSUE TITLE
The dropDown box does not scroll with the page

### ISSUE THREAD

**Issue by smallteeths** [longhorn/longhorn#1329]
The dropDown box does not scroll with the page

**To Reproduce**
1. Navigate to Dashboard page
2. Click on filter, filter text box opens.
3. now scroll up in the window, the filter window scrolls up with the Dashboard window.

<img width="1667" alt="79353507-fcb18f80-7eef-11ea-9efe-3a1133448031" src="https://user-images.githubusercontent.com/27733391/81763143-1cdd6a00-9501-11ea-9d99-55665e2e0d65.png">

**Expected behavior**
the filter window Should not scroll up with the Dashboard window.

**Environment:**
 - Longhorn version:master
 - Kubernetes version: 1.17.4
 - Node OS type and version:RKE DO Linux cluster

**Comment by khushboo-rancher** [comment]
On the latest master as of 06-12-2020, I still see the filter text box scroll with the page.
Both name and source filter have same behavior.

**Comment by khushboo-rancher** [comment]
Verified on master -07-02-2020

Validation - **Passed**

The filters text box for name and source are scrolling with the page.
