### ISSUE TITLE
[BUG] Documentation required for "Guaranteed Engine CPU" setting

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1332]
**Describe the bug**
Documentation required for "Guaranteed Engine CPU" setting

Currently the Longhorn UI displays info - 
`Required. (EXPERIMENTAL FEATURE) Allow Longhorn Engine to have guaranteed CPU allocation. The value is how many CPUs should be reserved for each Engine/Replica Manager Pod created by Longhorn. For example, 0.1 means one-tenth of a CPU. This will help maintain engine stability during high node workload. It only applies to the Engine/Replica Manager Pods created after the setting took effect. WARNING: Attaching of the volume may fail or stuck while using this feature due to the resource constraint. Disabled ("0") by default.`

Default value should be changed - logged issue - https://github.com/longhorn/longhorn/issues/1345 -  to track it separately
and the docs have to be updated

**Comment by yasker** [comment]
Also, remember to add to the best practice guide.

**Comment by yasker** [comment]
I cannot find the best practice guide on the website right now.

The documentation for the `GuaranteedEngineCPU` is now at https://github.com/yasker/longhorn/wiki/Guaranteed-Engine-CPU-%5BDRAFT%5D . We can put this in to the setting reference.

**Comment by catherineluse** [comment]
Closing this issue because this PR was merged https://github.com/longhorn/website/pull/120
