### ISSUE TITLE
[BUG] Update docs on scheduling policy based on available volume

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1334]
**Describe the bug**
Update docs on scheduling policy based on available volume

Currently `Storage Minimal Available Percentage` , `Storage Over Provisioning Percentage`, `Storage Available`, `Storage Maximum`, `Storage Reserved` and `storage scheduled` are taken into account while deciding on the scheduling policy.

Docs have to be updated with this info

**Comment by yasker** [comment]
We can add a new page under `Volume and Nodes` called `Scheduling` to document how Longhorn scheduling decision was made.

**Comment by catherineluse** [comment]
I think this issue can be closed because https://github.com/longhorn/website/pull/121 was merged
