### ISSUE TITLE
[BUG] Longhorn-manager high CPU usage

### ISSUE THREAD

**Issue by dmayle** [longhorn/longhorn#1335]
**Describe the bug**
I have a small (5 worker node) cluster that is mostly idle (no user load) right now, and I'm trying to figure out why my CPU usage is so high.  I've been pulling CPU usage on the worker nodes, and with the exception of one of my nodes (which runs argocd with no persistent volumes), the top CPU consumer on every node is longhorn consuming 30% of the CPU (dual-core machines).

When examining the longhorn-manager logs, there is nothing happening right now (literally nothing, no log lines in the last two hours).

I exec'ed into each container to check the logs in /tmp, and none of them has any entries from today.

The most I can find is that processes are being continually created: 
```
/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v0.8.0/longhorn --url 10.244.10.177:10000 info
```

Digging into that, I see that the engine monitor polling the engine binary every 5 seconds, though I'm measuring at least 50 new processes per second.  I've also been able to capture:
```
/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v0.8.0/longhorn --url 10.244.10.177:10000 snapshot purge-status
```
That runs both as part of the monitor, but also in its own loop that goes every five seconds

Now I've just caught:
```
/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v0.8.0/longhorn --url 10.244.10.177:10000 backup status
/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v0.8.0/longhorn --url 10.244.10.177:10001 backup restore-status
/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v0.8.0/longhorn --url 10.244.10.177:10001 replica-rebuild-status
```

Digging further, the engine monitor launches many, many processes per second (though given the 250 processes launched in each monitor interval (50 per second * 5 seconds), I doubt that the majority of those are coming from the monitor process.

On the one hand, maybe there should be a comprehensive "stats" command in the engine binary that dumps all of the related info so that the monitor process can perform that once per monitor run and then split out the data, on the other, I'm not sure what else is calling that binary.

**Log**
```
prod03:~# join --header -t $'\t' -j 1 -o 1.5 2.2 2.3 2.4 <(crictl ps | sed -e 's@  \+@\t@g' | awk 'NR<2{print $0;next}{print $0| "sort"}') <(crictl stats | sed -e 's@CPU %@CPU%@' -e 's@  \+@\t@g' | awk 'NR<2{print $0;next}{print $0| "sort"}') | column -t | awk 'NR<2{print $0;next}{print $0 | "sort -k2 -n -r"}'

NAME                              CPU%   MEM      DISK
longhorn-manager                  26.04  62.01MB  16.81MB
engine-manager                    6.17   47.62MB  94.45kB
replica-manager                   6.11   161.8MB  317.9kB
node-driver-registrar             0.00   6.275MB  36.86kB
longhorn-csi-plugin               0.00   15.47MB  91.64kB
engine-image-ei-e10d6bf5          0.00   6.033MB  24.58kB
compatible-node-driver-registrar  0.00   5.714MB  49.15kB
compatible-longhorn-csi-plugin    0.00   9.212MB  65.54kB
```

**Environment:**
 - Longhorn version: v0.8.0
 - Kubernetes version: 1.16.4
 - Node OS type and version: Alpine 3.10

**Comment by yasker** [comment]
@dmayle We are going to replace the communication mechanism between manager and engine using GRPC https://github.com/longhorn/longhorn/issues/677 in the next major release, to alleviate this problem.

**Comment by innobead** [comment]
remove stale due to the incorrect exempt label
