### ISSUE TITLE
[BUG] Backup creation on NFS backup store failed when there was already a backup creation in progress

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1341]
**Describe the bug**
Backup creation failed when it was triggered before completion of previous backup creation.

**To Reproduce**
1. Create a volume (3 replicas) and attach it to a node.
2. Configure an NFS backup store.
3. Enable a recurring backup for the volume.
4. Write data to the volume 1 Gi.
5. Take a backup of the volume when one recurring backup creation is already in progress.

**Note:**
Issue doesn't seem to happen with S3 backup store.

<img width="748" alt="Screen Shot 2020-05-13 at 3 17 09 PM" src="https://user-images.githubusercontent.com/60111667/81877986-811d1f80-953b-11ea-9d33-f8a5f9d3919a.png">

**Expected behavior**
Taking a backup when another backup is in progress should not be allowed.

**Logs**
```
"backupStatus": [{
			"actions": null,
			"backupURL": "nfs://x.x.x.x:/nfs?backup=backup-fc216dc8424a41ca&volume=volume-3-new",
			"error": "",
			"id": "backup-fc216dc8424a41ca",
			"links": null,
			"progress": 100,
			"replica": "volume-3-new-r-72cf0333",
			"snapshot": "c-x4w5jz-7547b110",
			"state": "complete"
		}, {
			"actions": null,
			"backupURL": "",
			"error": "rename /var/lib/longhorn-backupstore-mounts/x.x.x.x/nfs/backupstore/volumes/5a/57/volume-3-new/blocks/63/8d/638d2e023feaa45eb4d584d10b68c3d9da9b162a52b37369550b8e16e24fb8da.blk.tmp /var/lib/longhorn-backupstore-mounts/3_15_150_98/nfs/backupstore/volumes/5a/57/volume-3-new/blocks/63/8d/638d2e023feaa45eb4d584d10b68c3d9da9b162a52b37369550b8e16e24fb8da.blk: no such file or directory",
			"id": "backup-d4e5e89d1229447f",
			"links": null,
			"progress": 30,
			"replica": "volume-3-new-r-72cf0333",
			"snapshot": "2405f558-8a13-4fbd-94e0-88cd09194547",
			"state": "error"
		}, {
			"actions": null,
			"backupURL": "nfs://x.x.x.x:/nfs?backup=backup-e17e29dd1fa84d42&volume=volume-3-new",
			"error": "",
			"id": "backup-e17e29dd1fa84d42",
			"links": null,
			"progress": 100,
			"replica": "volume-3-new-r-72cf0333",
			"snapshot": "c-x4w5jz-3ada6878",
			"state": "complete"
		}
```
[longhorn-support-bundle_e8d217c6-3283-4664-9018-a84ee301ee96_2020-05-13T22-30-20Z.zip](https://github.com/longhorn/longhorn/files/4625296/longhorn-support-bundle_e8d217c6-3283-4664-9018-a84ee301ee96_2020-05-13T22-30-20Z.zip)

**Environment:**
 - Longhorn version: Master
 - Kubernetes version: v1.17.5
 - Node OS type and version: Ubuntu 18.04

**Comment by khushboo-rancher** [comment]
On the above setup, I'm able to create more backups but later restoring from the backups after the faulted backup doesn't work.
```
time="2020-05-14T00:38:34Z" level=warning msg="Try to get requested log for pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4 on node khush-test-wk1"
time="2020-05-14T00:38:34Z" level=warning msg="pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4: time=\"2020-05-14T00:32:58Z\" level=info msg=\"Creating volume /host/var/lib/longhorn/replicas/pvc-97c4b861-41f3-4a60-9969-885fc15514c7-138956fa, size 21474836480/512\""
time="2020-05-14T00:38:34Z" level=warning msg="pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4: time=\"2020-05-14T00:32:59Z\" level=info msg=\"Listening on data server 0.0.0.0:10016\""
time="2020-05-14T00:38:34Z" level=warning msg="pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4: time=\"2020-05-14T00:32:59Z\" level=info msg=\"Listening on sync agent server 0.0.0.0:10017\""
time="2020-05-14T00:38:34Z" level=warning msg="pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4: time=\"2020-05-14T00:32:59Z\" level=info msg=\"Listening on gRPC Replica server 0.0.0.0:10015\""
time="2020-05-14T00:38:34Z" level=warning msg="pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4: time=\"2020-05-14T00:32:59Z\" level=info msg=\"Listening on sync 0.0.0.0:10017\""
time="2020-05-14T00:38:34Z" level=warning msg="pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4: time=\"2020-05-14T00:33:01Z\" level=info msg=\"New connection from: 10.42.0.9:51980\""
time="2020-05-14T00:38:34Z" level=warning msg="pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4: time=\"2020-05-14T00:33:01Z\" level=info msg=\"Opening volume /host/var/lib/longhorn/replicas/pvc-97c4b861-41f3-4a60-9969-885fc15514c7-138956fa, size 21474836480/512\""
time="2020-05-14T00:38:34Z" level=warning msg="pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4: time=\"2020-05-14T00:33:05Z\" level=info msg=\"Successfully initiated restore for nfs://3.15.150.98:/nfs?backup=backup-e6c13f36e1a747e9&volume=volume-3-new to [volume-snap-efda8b51-faed-4cb2-be54-1bbeb9b51a8e.img]\""
time="2020-05-14T00:38:34Z" level=warning msg="pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4: time=\"2020-05-14T00:38:33Z\" level=error msg=\"Backup Restore Error Found in Server[open /var/lib/longhorn-backupstore-mounts/3_15_150_98/nfs/backupstore/volumes/5a/57/volume-3-new/blocks/63/8d/638d2e023feaa45eb4d584d10b68c3d9da9b162a52b37369550b8e16e24fb8da.blk: no such file or directory]\""
time="2020-05-14T00:38:34Z" level=warning msg="pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4: time=\"2020-05-14T00:38:33Z\" level=error msg=\"failed to restore: open /var/lib/longhorn-backupstore-mounts/3_15_150_98/nfs/backupstore/volumes/5a/57/volume-3-new/blocks/63/8d/638d2e023feaa45eb4d584d10b68c3d9da9b162a52b37369550b8e16e24fb8da.blk: no such file or directory\""
time="2020-05-14T00:38:34Z" level=debug msg="Prepare to delete instance pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4"
time="2020-05-14T00:38:34Z" level=info msg="Event(v1.ObjectReference{Kind:\"Replica\", Namespace:\"longhorn-system\", Name:\"pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4\", UID:\"1a43f08c-14e5-47b0-8b55-acbb824d28f6\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"647876\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4"
time="2020-05-14T00:38:34Z" level=debug msg="Prepare to delete instance pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4"
time="2020-05-14T00:38:34Z" level=info msg="Event(v1.ObjectReference{Kind:\"Replica\", Namespace:\"longhorn-system\", Name:\"pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4\", UID:\"1a43f08c-14e5-47b0-8b55-acbb824d28f6\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"647877\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4"
time="2020-05-14T00:38:34Z" level=debug msg="Instance handler updated instance pvc-97c4b861-41f3-4a60-9969-885fc15514c7-r-e70fc6d4 state, old state running, new state stopped"
time="2020-05-14T00:39:21Z" level=debug msg="Forwarding request to 10.42.0.7:9500"
67.148.61.56 - - [14/May/2020:00:39:21 +0000] "POST /v1/volumes/pvc-97c4b861-41f3-4a60-9969-885fc15514c7?action=snapshotList HTTP/1.1" 200 407 "https://74.207.244.11/k8s/clusters/c-mjp57/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/volume/pvc-97c4b861-41f3-4a60-9969-885fc15514c7" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
time="2020-05-14T00:39:42Z" level=debug msg="Forwarding request to 10.42.0.7:9500"
67.148.61.56 - - [14/May/2020:00:39:42 +0000] "POST /v1/volumes/pvc-97c4b861-41f3-4a60-9969-885fc15514c7?action=snapshotList HTTP/1.1" 500 298 "https://74.207.244.11/k8s/clusters/c-mjp57/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/volume/pvc-97c4b861-41f3-4a60-9969-885fc15514c7" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
time="2020-05-14T00:39:42Z" level=debug msg="Forwarding request to 10.42.0.7:9500"
67.148.61.56 - - [14/May/2020:00:39:42 +0000] "POST /v1/volumes/pvc-97c4b861-41f3-4a60-9969-885fc15514c7?action=snapshotList HTTP/1.1" 500 298 "https://74.207.244.11/k8s/clusters/c-mjp57/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/volume/pvc-97c4b861-41f3-4a60-9969-885fc15514c7" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
```

**Comment by yasker** [comment]
This is maybe related to #612 ..

**Comment by khushboo-rancher** [comment]
I tried concurrent backup creation with S3 backup store couple of times, didn't see the issue with that.

**Comment by yasker** [comment]
@khushboo-rancher Thanks. Can you update the bug title and first comment as well to point out it's not an issue with S3?

**Comment by joshimoo** [comment]
@khushboo-rancher  can you test this issues with the below custom images.
This issue is related to #1326 

Here are the test images, only the engine should be necessary but I like to have them in sync for testing.
Also by having the manager with the default engine deployed, it allows me to run the manager integration tests.
engine: `joshimoo/longhorn-engine:1341-test`
manager: `joshimoo/longhorn-manager:1341-test`

**Comment by khushboo-rancher** [comment]
Verified with below images
engine: joshimoo/longhorn-engine:1341-qa
manager: joshimoo/longhorn-manager:1341-qa

No backup failure is seen during concurrent backups of same volume and different volume.

**Comment by khushboo-rancher** [comment]
@joshimoo There is a system created backup between two concurrent backups. Why was that created?
Also, it appears different from the other system snapshot created when I deleted one replica as per below image.
<img width="1433" alt="Screen Shot 2020-05-22 at 2 56 39 PM" src="https://user-images.githubusercontent.com/60111667/82712490-ed370c00-9c3c-11ea-9c2b-37e68c85310e.png">

**Comment by yasker** [comment]
The one in the circle is not a system created snapshot. it’s a removed snapshot. System created ones are yellow, like the latest one.

**Comment by joshimoo** [comment]
Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [ ] **If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
* [ ] **if labeled: require-doc** Has the necessary document PR submitted or merged?
* [ ] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [ ] **if labeled: require-automation-engine** Has the engine integration test been merged?
* [ ] **if labeled: require-manual-test-plan-doc** Has the manual test plan been documented?

**Comment by joshimoo** [comment]
Added section for Backup & Restore Test Scenarios to the [manual test plan](https://github.com/longhorn/longhorn-tests/wiki/Test-Scenarios-for-Backups-&-Restore).

**Comment by khushboo-rancher** [comment]
Verified on master - 05-23-2020

Verification : **Passed**

Concurrent backups got successfully created. Tested with concurrent backups within same volume and with two different volumes. 

**Steps**
1. Create volume and attach to a pod.
2. Write into the volume.
3. Set up NFS backup store.
4. Create two parallel backups.
5. When backup creation is in progress, write some more data to the volume.
6. Create backup again.
7. Repeat above steps multiple times.
8. Restore the backups and verify the data.
