### ISSUE TITLE
[BUG] Default value for Guaranteed Engine CPU setting is 0

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1345]
**Describe the bug**
Default value for Guaranteed Engine CPU setting is 0

**To Reproduce**
Currently the default value is 0.

**Expected behavior**
Should not be zero. 

**Environment:**
 - Longhorn version: master (05/13/2020)

**Comment by yasker** [comment]
This value has a few implications, but I think you're right. It shouldn't be zero by default.

**Comment by yasker** [comment]
Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [ ] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~
* [ ] ~~**If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?~~
* [ ] ~~**if labeled: require-automation-engine** Has the engine integration test been merged?~~
* [ ] ~~**if labeled: require-doc** Has the necessary document PR submitted or merged?~~

**Comment by yasker** [comment]
To check, deploy a new Longhorn cluster using yaml from Longhorn manager. The default setting of GuaranteedEngineCPU should be 0.25.

The instance managers should have guaranteed 250M CPU set in the pod spec.

**Comment by sowmyav27** [comment]
**Verified on latest master - 05/15/2020**

Validation: **`PASSED`**


- `Guaranteed Engine CPU` is seen set as 0.25 on the Longhorn UI --> Settings page
- instance managers have 250M CPU
```
 kubectl get pods -n longhorn-system instance-manager-e-b3a85efb -o yaml | grep -i cpu
        cpu: 250m
> kubectl get pods -n longhorn-system instance-manager-e-c60d9763 -o yaml | grep -i cpu
        cpu: 250m
> kubectl get pods -n longhorn-system instance-manager-e-cf25ba6b -o yaml | grep -i cpu 
        cpu: 250m
....
```
- kubectl describe node lists with 250M CPU set for each instance manager pod.
```
 longhorn-system            instance-manager-e-312faa22            250m (12%)    0 (0%)      0 (0%)           0 (0%)         45s
  longhorn-system            instance-manager-r-be0fb343            250m (12%)    0 (0%)      0 (0%)           0 (0%)         45s
```
