### ISSUE TITLE
[BUG] Backups - mount.nfs4: rpc.statd is not running but is required for remote locking

### ISSUE THREAD

**Issue by garrmark** [longhorn/longhorn#1346]
**Describe the bug**
I have set up a remote nfs share to send backups to, but when I try and run a backup, the replica-manager.log has the following error:

2020-05-14T20:21:51.904487922Z [pvc-8375a62c-4265-42db-9416-57d42dcea128-r-dff401ae] time="2020-05-14T20:21:51Z" level=error msg="Error creating backup: Cannot mount nfs mynas:/backup/longhorn-backup/test-kube: Failed to execute: mount [-t nfs4 mynas:/backup/longhorn-backup/test-kube /var/lib/longhorn-backupstore-mounts/mynas/backup/longhorn-backup/test-kube], output mount.nfs4: rpc.statd is not running but is required for remote locking.\nmount.nfs4: Either use '-o nolock' to keep locks local, or start statd.\n, error exit status 32"

**To Reproduce**
1. Go to longhorn settings and enter into "Backup Target" the nfs entry:
nfs://mynas:/backup/longhorn-backup/test-kube
2. Go into a volume and select "Create Backup"
3. See error in replica-manager.log

**Expected behavior**
A backup will be created on the nfs share

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

**Environment:**
 - Longhorn version: v0.8.1
 - Kubernetes version: v1.17.4+k3s1
 - Node OS type and version: Ubuntu 18.04.4 LTS

**Additional context**

**Comment by yasker** [comment]
@garrmark Can you try to install `nfs-common` on your host?

**Comment by joshimoo** [comment]
@garrmark From the logs, it looks like you are missing `nfs-common` on your ubuntu nodes.
ref: [nfs-common](https://packages.ubuntu.com/bionic/nfs-common)
ref: [rpc.statd](https://manpages.ubuntu.com/manpages/precise/man8/rpc.statd.8.html)

**Comment by garrmark** [comment]
Thanks for the suggestion, but nfs-common is installed on all of my hosts:
```
sudo apt install -y nfs-common
Reading package lists... Done
Building dependency tree
Reading state information... Done
nfs-common is already the newest version (1:1.3.4-2.1ubuntu5.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by garrmark** [comment]
I can also nfs mount the shares directly to the nodes.

**Comment by yasker** [comment]
@garrmark which version of NFS server you're using? We only support NFSv4+.

**Comment by garrmark** [comment]
@yasker I'm using a server that also supports v4 and can mount v4 directly to the linux nodes

**Comment by joshimoo** [comment]
It's hard to diagnose remotely, but the issue seems that your stat.d isn't auto started.

There is a [workaround ](https://bugs.launchpad.net/ubuntu/+source/nfs-utils/+bug/1624715/comments/5) posted here for Ubuntu 16.04.04 which would make sure that `rpc-statd` gets autostarted. Which I suggest you might want to try.

There are also mentions of missing directories, etc [here](https://unix.stackexchange.com/questions/184338/nfs-no-longer-mounts-rpc-statd-fails-to-start)
You might see that when doing the `systemctl restart rpc-statd.service`

Also verify that the installed rpcbind version is >= rpcbind - 0.2.3-0.4

Can you try the below to reenable stat.d & rpcbind on your hosts.
```
# check status on rpcbind.service
systemctl status rpcbind.service
systemctl reenable rpcbind.service
systemctl restart rpcbind.service

# check status on rpc-statd.service
systemctl status rpc-statd.service
systemctl reenable rpc-statd.service
systemctl restart rpc-statd.service
```

**Comment by yasker** [comment]
@garrmark Can it be the NFS fall back to v3 automatically? Can you check `mount|grep nfs` to see if `vers=4` or `vers=3` when you mounted volume manually on the node?

**Comment by garrmark** [comment]
@yasker  yes, that mount works perfectly locally, but not in the container
```
root@exgvsrv061:~# mount -t nfs4 pspnas01:/backup/longhorn-backup/test-kube /mnt/backup
root@exgvsrv061:~# mount | grep backup
pspnas01:/backup/longhorn-backup/test-kube on /mnt/backup type nfs (rw,relatime,vers=3,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.2.10.94,mountvers=3,mountport=58635,mountproto=udp,local_lock=none,addr=10.2.10.94)
```
