### ISSUE TITLE
[BUG] "Attached To" column is inconsistent for a volume attached to a node vs volume attached to a workload

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1350]
**Describe the bug**
"Attached To" column is inconsistent for a volume attached to a node vs volume attached to a workload

**To Reproduce**
Volume - vol1
Workloads - W1, W2
Hosts - h1,h2,h3

1. Deploy a vol1 and attach to W1
2. As seen on Volumes page - State: "Healthy" Vol1  Attached to: W1 on h1 (white background)
3. Delete W1 (detach from W1)
4. As seen on Volumes page - State: Detached Vol1  Attached to: W1(yellow background) 
5. Attach Vol1 to W2 
6. As seen on Volumes page - State: Healthy Attached to: Vol1  W2 on h2(white background)
7. Delete W2 ( vol1 detached)
8. As seen on Volumes page - State: Detached  Attached to: Vol1  W2(yellow background)
9. Attach to h3

**Expected:**
As seen on Volumes page - State: Healthy  Attached to: Vol1  on h3(white background)

**Actual**
As seen on Volumes page - State: Healthy  Attached to: w2 on h3(yellow background)

**Environment:**
 - Longhorn version: master - 05/14/2020

**Comment by yasker** [comment]
White background is current status. Yellow background means it was used but it wasn't now. The tooltip or click the `Attached To` label should give you an explanation.

**Comment by sowmyav27** [comment]
@yasker 

After Step 9 from above, 

The volume is actually attached on H3 only

But in the `Attached to` section - the whole of test - W2 on H3 in a yellow background gives an incorrect impression to the user that the volume was previously attached to W2 on H3. Whereas the volume is currently ONLY attach to H3 (which should be represented with a white background)

**Comment by yasker** [comment]
@sowmyav27 Until another workload starts to use it, it doesn't make sense to remove the previous workload information just because the volume was attached to a different node, because the user can perform some maintenance work or inspect the volume manually. That's why the history information is only related to the workload, not the attached node. If we remove the history information just because the volume was attached somewhere else but not used, then user won't know about which workload used this volume after it's been attached for maintenance. Does this make sense?

**Comment by sowmyav27** [comment]
@yasker it makes sense, thank you. However, when the the text that says it is currently "on a host h1" is also in a yellow background, that gives an incorrect impression to the user that that part is also history.

**Comment by yasker** [comment]
@smallteeths Can you make the background different for the attached node and history Kubernetes status information in this case?

**Comment by smallteeths** [comment]
The attached node is always up to date, so no yellow background is needed. 
Am i getting it right @yasker @sowmyav27 
![Jietu20200518-113416](https://user-images.githubusercontent.com/27733391/82172030-97d8c300-98fb-11ea-93d3-522ab1a0542f.jpg)

**Comment by yasker** [comment]
@smallteeths Yes, this screenshot looks right.

**Comment by sowmyav27** [comment]
**Verified on master using UI image: `wangsiye/longhorn-ui:941d022`**

Validation: **`PASSED`**

- History has workload in a yellow background and the current node the volume is attached to is in white background.
<img width="1600" alt="Screen Shot 2020-05-18 at 10 01 26 AM" src="https://user-images.githubusercontent.com/26032343/82240534-6e199f00-98ef-11ea-8afa-6959c3427ccf.png">

**Comment by sowmyav27** [comment]
**Verified on master - 05/18/2020 - 22:00 PDT**
- History has workload in a yellow background and the current node the volume is attached to is in white background.
<img width="1654" alt="Screen Shot 2020-05-18 at 10 47 24 PM" src="https://user-images.githubusercontent.com/26032343/82289406-9807ab80-9959-11ea-8121-a44a0528f875.png">
