### ISSUE TITLE
[DOC] Review doc about Longhorn on K3s and update if necessary

### ISSUE THREAD

**Issue by catherineluse** [longhorn/longhorn#1352]
We have some specific steps for installing Longhorn on a K3s cluster. This page https://longhorn.io/docs/0.8.1/advanced-resources/os-distro-specific/csi-on-k3s/ should be reviewed to make sure the custom setup is still necessary, because there have been some fixes since the document was written.

**Comment by yasker** [comment]
Check https://staging.longhorn.io/docs/0.8.1/ instead since it will become the next v1.0.0.

**Comment by shuo-wu** [comment]
Validations:
- [x] The lastest Longhorn doesn't work on k3s of which the version is **lower than v0.10.0** without extra configs.
- [x] The lastest Longhorn works fine on k3s of which the version is **lower than v0.10.0** with the configs mentioned in the doc.
- [ ] The lastest Longhorn works fine on k3s of which the version is **v0.10.0 or higher** without extra configs.

Here, `works fine` means I can launch pods with Longhorn volumes via the storageClass.

@yasker Do we still need to check the compatibility for Longhorn v0.7 with k3s?

**Comment by yasker** [comment]
@shuo-wu Sounds good. And no, we don't need to check v0.7.0.
