### ISSUE TITLE
[BUG] Replicas stuck in Restoring mode when the node where restore volume attached to is powered down

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1355]
**Describe the bug**
Replicas stuck in Restoring mode when the node where restore volume attached to is powered down

**To Reproduce**
**Scenario-1**
- Restore from a backup to vol-1
- while the restore is in progress, **power down a worker node**.
- A replica fails and gets deleted (when seen from UI)
- The other two replica are seen in "restoring" state since long. In the API failed replica still exists and is not removed.

```
"restoreStatus": [
        {
          "actions": null,
          "backupURL": "<>",
          "error": "",
          "filename": "volume-snap-1b5e3063-b2da-463e-b5a5-230e73fec6db.img",
          "isRestoring": true,
          "lastRestored": "",
          "links": null,
          "progress": 12,
          "replica": "tcp://10.42.3.11:10015",
          "state": "in_progress"
        },
        {
          "actions": null,
          "backupURL": "<>",
          "error": "",
          "filename": "volume-snap-1b5e3063-b2da-463e-b5a5-230e73fec6db.img",
          "isRestoring": true,
          "lastRestored": "",
          "links": null,
          "progress": 12,
          "replica": "restore-1-r-b5e91be7",
          "state": "in_progress"
        },
        {
          "actions": null,
          "backupURL": "<>",
          "error": "",
          "filename": "volume-snap-1b5e3063-b2da-463e-b5a5-230e73fec6db.img",
          "isRestoring": true,
          "lastRestored": "",
          "links": null,
          "progress": 12,
          "replica": "restore-1-r-75585701",
          "state": "in_progress"
        }
      ],
```
<img width="1660" alt="Screen Shot 2020-05-11 at 6 50 01 PM" src="https://user-images.githubusercontent.com/26032343/81629545-4048cd80-93b8-11ea-8929-39dca9349c9c.png">

**Scenario-2**
- Restore from a backup.
- When restore is in progress, **delete the attached node**.
- Volume stays in healthy state and shows 'restore in progress' forever.

**Logs:** 
[longhorn-support-bundle_eed6ec20-4ae2-4c37-91ae-a01fa2b3605b_2020-05-13T01-31-18Z.zip](https://github.com/longhorn/longhorn/files/4619297/longhorn-support-bundle_eed6ec20-4ae2-4c37-91ae-a01fa2b3605b_2020-05-13T01-31-18Z.zip)

**Expected behavior**
Replicas should finish restoring and volume should be in detached state

**Environment:**
 - Longhorn version: master - 05/15/2020
 - Kubernetes version: 1.17.5

**Comment by sowmyav27** [comment]
Related info:
- https://github.com/longhorn/longhorn/issues/1270#issuecomment-627963519
- https://github.com/longhorn/longhorn/issues/1270#issuecomment-628565848

**Comment by shuo-wu** [comment]
The manual test:
1. Create a backup.
2. Create a restore volume from the backup.
3. Power off the volume attached node during the restoring.
4. Wait for the Longhorn node down.
5. Wait for the restore volume being reattached and starting restoring volume with state `Degraded`.
6. Wait for the restore complete.
7. Attach the volume and verify the restored data.
8. Verify the volume works fine.

**Comment by shuo-wu** [comment]
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged?
The PR is at https://github.com/longhorn/longhorn-manager/pull/598

* [x] Is the reproduce steps/test steps documented?

* [x] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~~

* [x] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at~~

* [x] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at~~

* [x] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~~

* [ ] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at

**Comment by khushboo-rancher** [comment]
Verified on master- 06-05-2020

Verification - **Passed**

**Steps followed to test:**
**Scenario 1**
1. Create a volume, attach to a pod and write into it.
2. Take a backup.
3. Restore the backup.
4. While restore is in progress, power down the attached node.
5. Restore completed with degraded status.
6. Verified the data.

**Scenario 2**
1. Create a volume, attach to a pod and write into it.
2. Take a backup.
3. Restore the backup.
4. While restore is in progress, Delete the attached node.
5. Restore completed with degraded status.
6. Verified the data.

**Scenario 3**
1. Create a volume, attach to a pod and write into it.
2. Take a backup.
3. Restore the backup.
4. While restore is in progress, power down one of the replica node.
5. Restore completed with degraded status.
6. Verified the data.

[longhorn-support-bundle_f2aa2fe1-51c4-451d-b639-b042a1b1b21a_2020-06-05T23-44-54Z.zip](https://github.com/longhorn/longhorn/files/4739026/longhorn-support-bundle_f2aa2fe1-51c4-451d-b639-b042a1b1b21a_2020-06-05T23-44-54Z.zip)
