### ISSUE TITLE
[BUG] User is not presented with any warning when user detaches a volume currently used by a workload

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1357]
**Describe the bug**
User is not presented with any warning when user detaches a volume currently used by a workload

**To Reproduce**
Currently user is able to detach a volume in use by a workload and is attached to node1. But this will corrupt the mount point of the workload on node1. And when the user attaches it back on a node, the volume will still not be useful. 

**Expected behavior**
User should be presented a warning message when "Detaching" a volume - which is currently used by a workload and attached to node1

**Environment:**
 - Longhorn version: master - 5/15/2020
 - Kubernetes version: 1.17.5

**Comment by yasker** [comment]
Design:
1. If the volume isn't currently related to a Kubernetes pod (check Kubernetes status), change nothing.
2. If the volume is currently related to a Kubernetes pod, show below when user try to detach the volume:
```
Warning

Detach a Volume while used by a running Kubernetes Pod would result in the Pod crash and possible data loss. And the Volume won't be able to used by the Kubernetes again until the original Pod is deleted.

Are you sure you want to detach the volume?

- [ ] Yes I understand the risk and I want to detach the volume now.
```

The last line is a checkbox. Before the user checks the checkbox, the `OK` button should be greyed out.

**Comment by sowmyav27** [comment]
Verified on `wangsiye/longhorn-ui:941d022`

The warning message is available when a user tries to detach a volume currently attached to a workload.
<img width="788" alt="Screen Shot 2020-05-18 at 10 29 50 AM" src="https://user-images.githubusercontent.com/26032343/82242475-c00ff400-98f2-11ea-8182-6c88af05c4a0.png">

But can we change the text to this:
```
Detaching a Volume when it is being used by a running Kubernetes Pod will result in crashing of the Pod and possible loss of data. The Volume cannot be used by the Kubernetes again until the original Pod is deleted. Are you sure you want to detach the volume?
```

**Comment by yasker** [comment]
@sowmyav27 I am fine with it.

**Comment by sowmyav27** [comment]
**Verified on u tag: `wangsiye/longhorn-ui:9871b3c`**

Validation: **`PASSED`**

- Warning text is now
```
Detaching a Volume when it is being used by a running Kubernetes Pod will result in crashing of the Pod and possible loss of data. The Volume cannot be used by the Kubernetes again until the original Pod is deleted. Are you sure you want to detach the volume?

[] Yes I understand the risk and I want to detach the volume now.
```

**Comment by sowmyav27** [comment]
**Verified on master - 05/18/2020 - 22:00 PDT**

Warning text is as expected
<img width="881" alt="Screen Shot 2020-05-18 at 10 45 27 PM" src="https://user-images.githubusercontent.com/26032343/82289339-6b539400-9959-11ea-9692-84f8a2a8f44c.png">
