### ISSUE TITLE
[BUG] Restore is successful even when there is "Replica Scheduling Failure" during a backup restore of volume

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1361]
**Describe the bug**
Restore is successful even when there is "Replica Scheduling Failure" during a backup restore of volume

**To Reproduce**

- Number of worker nodes - 4
- Cordon a worker node. Node is marked "Unschedulable"
- Restore from a backup with replicas - 4.
- The volume is seen in `Replica Scheduling Failure` state. But the restoring happens on the remaining healthy replicas.

**Expected behavior**
Restoring from backup should FAIL when this issue - "Replica Scheduling Failure" is hit

**Environment:**
 - Longhorn version: master - 05/18/2020 - ui tag: `wangsiye/longhorn-ui:941d022 `

**Comment by sowmyav27** [comment]
This is the case for a DRV volume also

**Comment by shuo-wu** [comment]
The manual test step is the same as the reproducing step. And the final result should be:
The restore/DR volume will keep detached and won't start restoration after the creation and scheduling failure.

**Comment by shuo-wu** [comment]
Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [x] Is the reproduce steps/test steps documented?
* ~~[x] **If labeled: area/ui** Has the UI issue filed or ready to be merged?~~
* ~~[x] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?~~
* [x] ~~**if labeled: require-automation-engine** Has the engine integration test been merged?~~
* [x] ~~**if labeled: require-doc** Has the necessary document PR submitted or merged?~~
* [x] **if labeled: require-manual-test-plan-doc** Has the manual test plan been documented?

**Comment by sowmyav27** [comment]
**Verified on master - latest - 05/22/2020**

- Number of worker nodes - 4
- Cordon a worker node. Node is marked "Unschedulable"
- Restore from a backup with replicas - 4.
- The volume is seen in Replica Scheduling Failure state. 
- All the replicas are in "Stopped" status
- Navigate to volume details page. The condition says - `Reason: RestoreInProgress`. 
<img width="1062" alt="Screen Shot 2020-05-22 at 10 10 29 AM" src="https://user-images.githubusercontent.com/26032343/82692773-25c2ef80-9c15-11ea-9dad-5d7de8e6fef3.png">

@yasker Is this condition correct here? Should it not say "restore failure" in Red color?

**Comment by yasker** [comment]
@sowmyav27 what if we restore the node? Will the restore continue? The restore was in fact `in progress`, but it's blocked by scheduling failure. Once the volume is scheduled, we should be able to continue the restoration.

**Comment by sowmyav27** [comment]
@yasker 
When the node is uncordoned, yes the restore continues. The volume gets restored correctly.

**Comment by yasker** [comment]
@sowmyav27 Sounds like we're good then.

**Comment by sowmyav27** [comment]
Validation: **`PASSED`**
