### ISSUE TITLE
Remount Failure is not correctly signaled

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#1362]
**Describe the bug**
There are cases in which we fail a remount but aren't returning error.
Now the system thinks the device has been remounted, one of these cases is unable to detect filesystem.

**Expected behavior**
System should signal Remount failure if a Remount is required.

**Log**
```
[longhorn-manager-p9grl] time="2020-05-18T23:19:23Z" level=warning msg="Failed to detect the filesystem for volume terminate-immediatly, will skip remounting it.....
[longhorn-manager-p9grl] time="2020-05-18T23:19:23Z" level=info msg="Volume terminate-immediatly has been remounted on node rancher-dev3" 
```

**Environment:**
 - Longhorn version: 0.8.1

**Additional context**
[Expects Error](https://github.com/longhorn/longhorn-manager/blob/3a876614edd80379b4995ea0d2932fb1f65333d1/controller/volume_controller.go#L1078)

[Fails to return Error](https://github.com/longhorn/longhorn-manager/blob/3ec9c1f53b86016416c3ea1528f1bf9442d5bd4b/util/util.go#L706)

**Comment by PhanLe1010** [comment]
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [x] ~~Is the backend code merged?
The PR is at~~

* [x] Is the reproduce steps/test steps documented?

* [ ] Which areas/issues this PR might have potential impacts on?
Area: Auto attach volume

* [x] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~~

* [x] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at~~ 

* [x] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at~~

* [x] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~~

* [x] ~~**if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at~~

**Comment by PhanLe1010** [comment]
Steps to reproduce bug:

1. Create a volume of size 1GB, say `terminate-immediatly` volume.
2. Create PV/PVC from the volume `terminate-immediatly`
3. Create a deployment of 1 pod with image `ubuntu:xenial` and the PVC `terminate-immediatly` in default namespace
4. Find the node on which the pod is scheduled to. Let's say the node is `Node-1`
5. ssh into `Node-1`
6. destroy the filesystem of `terminate-immediatly` by running command  `dd if=/dev/zero of=/dev/longhorn/terminate-immediatly`
7. Find and kill the engine instance manager in `Node-X`. Longhorn manager will detect that the instance manager is down and try to bring up a new instance manager e for `Node-X`.
8. After bringing up the instance manager e, Longhorn manager will try to remount the volume `terminate-immediatly`. The remounting should fail bc we already destroy the filesystem of the volume.
9. We should see this log message
```
[longhorn-manager-xv5th] time="2020-06-23T18:13:15Z" level=warning msg="Failed to detect the filesystem for volume terminate-immediatly, will skip remounting it: cannot get the filesystem type by using the command blkid /dev/longhorn/terminate-immediatly | sed 's/.*TYPE=//g'" 
[longhorn-manager-xv5th] time="2020-06-23T18:13:15Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"terminate-immediatly\", UID:\"de6ae587-fc7c-40bd-b513-47175ddddf97\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"4088981\", FieldPath:\"\"}): type: 'Warning' reason: 'Remount' cannot proceed to remount terminate-immediatly on phan-cluster-v3-worker1: cannot get the filesystem type by using the command blkid /dev/longhorn/terminate-immediatly | sed 's/.*TYPE=//g'" 
```
instead of the one on the issue description.

**Comment by khushboo-rancher** [comment]
Verified on Master- 07-01-2020

The scenario mentioned https://github.com/longhorn/longhorn/issues/1362#issuecomment-648362867 works fine.
Logs:
```
[longhorn-manager-ntrft] time="2020-07-01T22:09:22Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"vol-1\", UID:\"daae9c04-fc38-465b-8e84-bdee67ddb37e\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"64861\", FieldPath:\"\"}): type: 'Warning' reason: 'Remount' cannot proceed to remount vol-1 on khush-test-wk1: failed to detect the filesystem for volume vol-1 before the remount, will skip remounting it: cannot get the filesystem type by using the command blkid /dev/longhorn/vol-1 | sed 's/.*TYPE=//g'"
```

The scenario where the filesystem is proper and the engine-instance-manager is crashed.  I can see ```remount succeed``` logs:
Steps:
1. Create a volume and attach to a pod
2. Delete the ```engine-instance-manager``` on the attached node

```
[longhorn-manager-25tdg] time="2020-07-01T22:22:57Z" level=debug msg="Succeed to handle the remount request for volume vol-2 on host path /var/lib/kubelet/pods/c0eb752c-5183-4bd7-936b-cf69c11ad443/volumes/kubernetes.io~csi/vol-2/mount" 
[longhorn-manager-25tdg] time="2020-07-01T22:22:57Z" level=info msg="Volume vol-2 has been remounted on node khush-test-wk3" 
[longhorn-manager-25tdg] time="2020-07-01T22:22:57Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"vol-2\", UID:\"1b2721bd-49d9-45c9-9b3f-d8034e399d2b\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"68018\", FieldPath:\"\"}): type: 'Normal' reason: 'Remount' Volume vol-2 has been remounted on node khush-test-wk3" 
```
@PhanLe1010 Is this expected or should we see ```skip the remount of volume``` logs?

**Comment by PhanLe1010** [comment]
LGTM
