### ISSUE TITLE
[BUG] Tool tip on a degraded volume suggests incorrectly that "one healthy replica is running at the same node as another" when Replica Node Level hard anti affinity is set

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1364]
**Describe the bug**
Tool tip on a degraded volume suggests incorrectly that "one healthy replica is running at the same node as another" when Replica Node Level hard anti affinity is set

**To Reproduce**

- Create a volume - 3 replicas
- Drain one node - force=true
- The volume will be in  degraded state, with one replica in failed state
- Hover of the state of the volume
- The tool tip shows message "Limited node redundancy: at least one healthy replica is running at the same node as another"

<img width="1618" alt="Screen Shot 2020-05-19 at 12 33 09 PM" src="https://user-images.githubusercontent.com/26032343/82370220-0b96d080-99cd-11ea-9af9-d70f240175e6.png">

**Expected behavior**
Tool tip should NOT say "one healthy replica is running at the same node as another" when hard anti affinity is set

**Environment:**
 - Longhorn version: master - 05/19/2020

**Comment by yasker** [comment]
@smallteeths 
An easier way to reproduce:
1. Set replica soft node anti-affinity to false
2. Create a volume with three replicas and attach it to the node.
3. Disable scheduling for one node.
4. Delete the replica on the node that disabled scheduling.

Then this shows:

<img width="1105" alt="Screen Shot 2020-05-20 at 4 08 41 PM" src="https://user-images.githubusercontent.com/3344618/82506343-5c352900-9ab4-11ea-9a71-5cb013957953.png">

As you can see, two replicas are on two different nodes, but `limited redundancy` was shown.

**Comment by sowmyav27** [comment]
**Verified with ui tag: `wangsiye/longhorn-ui:af54fa9`**

**Steps:**

- Set replica soft node anti-affinity to false
- Create a volume with three replicas and attach it to the node.
- Disable scheduling for one node n1.
- Delete the replica on the node that disabled scheduling.
- The degraded state does not have a tool tip now
- Now enable scheduling for the node n1.
- The replica will rebuild.
- The tooltip on the degraded state shows text

<img width="957" alt="Screen Shot 2020-05-21 at 5 27 17 PM" src="https://user-images.githubusercontent.com/26032343/82618772-dafb9600-9b88-11ea-9e8c-b30686f37b87.png">

No two replicas are running on the same node. so this tool tip should not be present.

**Comment by yasker** [comment]
@smallteeths ^^

**Comment by sowmyav27** [comment]
**Verified with ui tag: `wangsiye/longhorn-ui:afa7e56`**

Validation: **FAILED**

**Steps:**

- Create a volume - 3 replicas
- Drain one node - force=true
- The volume will be in degraded state, with one replica in failed state
- Hover of the state of the volume
- The tool tip shows message "Limited node redundancy: at least one healthy replica is running at the same node as another"

<img width="1664" alt="Screen Shot 2020-05-21 at 9 18 48 PM" src="https://user-images.githubusercontent.com/26032343/82630827-bb746580-9ba8-11ea-8840-784369481147.png">

**Comment by sowmyav27** [comment]
**validated using UI tag: `wangsiye/longhorn-ui:ff585c6`**

Validation: **`PASSED`**

**Steps:**

**Scenario#1**

- Create a volume - 3 replicas
- Drain one node - force=true
- The volume will be in degraded state, with one replica in failed state
- Hover of the state of the volume
- The tool tip on the "degraded" state does NOT show any message.

<img width="661" alt="Screen Shot 2020-05-22 at 10 51 05 AM" src="https://user-images.githubusercontent.com/26032343/82695913-daabdb00-9c1a-11ea-8680-7130f3852ecb.png">

**Scenario#2**

- Number of worker nodes 5
- Create a volume with 4 replicas. Attach it to a node. rpelicas will be in running state.
- Soft Affinity node level - is set to True
- Update replica count to 7
- The state of volume is Degraded
- The tool tip shows message "Limited node redundancy: at least one healthy replica is running at the same node as another", which is expected

<img width="646" alt="Screen Shot 2020-05-22 at 10 52 43 AM" src="https://user-images.githubusercontent.com/26032343/82695892-d4b5fa00-9c1a-11ea-9069-305bb4d6ca3e.png">

**Comment by sowmyav27** [comment]
**validated longhorn master - 12:00 PDT 05/22/2020 **

Validation: **`PASSED`**

**Steps:**

**Scenario#1**

- Create a volume - 3 replicas
- Drain one node - force=true
- The volume will be in degraded state, with one replica in failed state
- Hover of the state of the volume
- The tool tip on the "degraded" state does NOT show any message.

<img width="652" alt="Screen Shot 2020-05-22 at 12 05 58 PM" src="https://user-images.githubusercontent.com/26032343/82701366-ec927b80-9c24-11ea-930e-45d48512dba5.png">

**Scenario#2**

- Number of worker nodes 4
- Create a volume with 3 replicas. Attach it to a node. rpelicas will be in running state.
- Soft Affinity node level - is set to True
- Update replica count to 6
- The state of volume is Degraded
- The tool tip shows message "Limited node redundancy: at least one healthy replica is running at the same node as another", which is expected

<img width="622" alt="Screen Shot 2020-05-22 at 12 06 33 PM" src="https://user-images.githubusercontent.com/26032343/82701396-f9af6a80-9c24-11ea-8d97-393285f63d61.png">
