### ISSUE TITLE
task: remove compatible CSI deployment

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1365]
We no longer support it for v1.0.0 GA.

Steps to verify compatible CSI deployment got removed:
1. Set up a storage class with `provisioner: io.rancher.longhorn`.
2. Create a PVC using this storage class.
3. PVC creation should fail. Since we don't support it now.

Steps to verify current CSI deployment works:
1. Set up a storage class with `provisioner: driver.longhorn.io`.
2. Create a PVC using this storage class.
3. PVC creation should success.

**Comment by boknowswiki** [comment]
* [ ] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [ ] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~
* [ ] ~~**If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?~~
* [ ] ~~**if labeled: require-automation-engine** Has the engine integration test been merged?~~
* [ ] **if labeled: require-doc** Has the necessary document PR submitted or merged?

**Comment by yasker** [comment]
Remember to file a separate issue with the label `release/obsolete-compatibility` to remove the cleanup code for `compatible-csi-attacher`.

**Comment by boknowswiki** [comment]
@yasker , Do you mean a new bug or feature to tracking the deletion of this code?

**Comment by yasker** [comment]
@boknowswiki it should be an enhancement rather than a bug.

**Comment by sowmyav27** [comment]
**Validated on master - 05/22/2020**

- Set up a storage class with provisioner: `io.rancher.longhorn`
- Create a PVC using this storage class.
- PVC creation fails.

current CSI deployment:
- Set up a storage class with provisioner: `driver.longhorn.io`
- Create a PVC using this storage class.
- PVC creation succeeds
