### ISSUE TITLE
[BUG] DR volume is stuck in restoring if the attached node is power downwhile restoring was in progress

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1366]
**Describe the bug**
DR volume is stuck in restoring if the attached node is power down while restoring was in progress.

**To Reproduce**
1. Set up a NFS backup store.
2. Create a volume (3 replicas), attach this to pod.
3. Write into the volume and take backup.
4. In another cluster, create DR volume of the backup
5. While restoring is in progress of DR volume, **power down the attached node**
6.  Volume is stuck in restoring state. 

Also, If for a healthy DR volume attached node is powered down, it remain in healthy state and doesn't change the status.

**Log**
[longhorn-support-bundle_53cb4e1f-66b3-4863-81e2-9474d31a306f_2020-05-19T23-07-18Z.zip](https://github.com/longhorn/longhorn/files/4653739/longhorn-support-bundle_53cb4e1f-66b3-4863-81e2-9474d31a306f_2020-05-19T23-07-18Z.zip)

**Environment:**
 - Longhorn version: master - 05-15-2020
 - Kubernetes version:v1.17.5
 - Node OS type and version: Ubuntu 18.04

**Comment by shuo-wu** [comment]
This result is what we expect. 
When a node becomes unresponsive, we don't know what happens and what status the related volumes are. e.g., the master node may be suddenly disconnected with all worker nodes or the worker node is down. Then we cannot blindly mark the volumes as `Faulted` state. Hence Longhorn won't operate the volumes and the volumes get stuck there until the node is back.

Of course, we can apply some enhancements for the restoring volumes or the DR volume. Since the volumes always require re-initializing restoration after the node is back, and Longhorn doesn't care which node the volumes are attached to, then we can re-initialize restoration in advance / without waiting for node back.

**Comment by yasker** [comment]
On a more general side, we can also consider handle it a similar way to Kubernetes. For example, when a node is down, we can mark the attached volume on that node as `unknown`. That would require some extra work on the controller to detect that though.

**Comment by shuo-wu** [comment]
@yasker 
Do we need to do anything else besides marking the robustness as `unknown` for restoring/DR volumes?

**Comment by yasker** [comment]
@shuo-wu Mark as the volume as unknown is not enough. Mark the volume state as unknown should be a separate issue in fact. But it can be used as the foundation of the fix.

For the DR volume and restoring case, we should be able to detect the issue (and knowing that the engine is unknown for a while, probably configurable) and then reattach the volume to another node to continue/restart the restoring process as you mentioned.

**Comment by shuo-wu** [comment]
Manual test 1:
1. Create a pod with Longhorn volume.
2. Write data to the volume and get the md5sum.
3. Create the 1st backup for the volume.
4. Create a DR volume from the backup.
5. Wait for the DR volume starting the initial restore. Then power off the DR volume attached node immediately.
6. Wait for the DR volume detached then reattached.
7. Wait for the DR volume restore complete after the reattachment.
8. Activate the DR volume and check the data md5sum.

Manual test 2:
1. Create a pod with Longhorn volume.
2. Write data to the volume and get the md5sum.
3. Create the 1st backup for the volume.
4. Create a DR volume from the backup.
5. Wait for the DR volume to complete the initial restore. 
6. Write more data to the original volume and get the md5sum.
7. Create the 2nd backup for the volume.
8. Wait for the DR volume incremental restore getting triggered. Then power off the DR volume attached node immediately.
9. Wait for the DR volume detached then reattached.
10. Wait for the DR volume restore complete after the reattachment.
11. Activate the DR volume and check the data md5sum.

The tests are similar to that of #1328. And notice that the tests in #1328 not recorded into the manual test plan.

**Comment by shuo-wu** [comment]
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged?
The PR is at https://github.com/longhorn/longhorn-manager/pull/598

* [x] Is the reproduce steps/test steps documented?

* [x] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~~

* [x] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at~~

* [x] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at~~

* [x] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~~

* [ ] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at

In addition:
* [ ] **prevent regression** Retest #1328

**Comment by khushboo-rancher** [comment]
Verified in master - 06-05-2020

Verification - **Failed**

**Scenarios**
1. When first restore is in progress and attached node is powered off - Passed
2. When incremental restore is in progress and attached node is powered off - Failed.

<img width="1720" alt="Screen Shot 2020-06-05 at 3 50 02 PM" src="https://user-images.githubusercontent.com/60111667/83928321-3eb6bf00-a744-11ea-9a83-bcf7d60e76ff.png">


**Steps to reproduce**
1. Create a volume, attach to a pod and write into it.
2. Take backup b1.
3. Create a DR volume in another cluster.
4. Let the initial restore be completed.
5. Write again in volume and take backup b2.
6. Wait for incremental restore process in DR volume to start.
7. While this incremental restore is in progress, power down the attached node.
8. Volume is stuck in detached state.
[longhorn-support-bundle_aec39354-df91-4fa4-b49d-00ef9008a0b2_2020-06-05T22-42-56Z.zip](https://github.com/longhorn/longhorn/files/4738809/longhorn-support-bundle_aec39354-df91-4fa4-b49d-00ef9008a0b2_2020-06-05T22-42-56Z.zip)

**Comment by yasker** [comment]
https://github.com/longhorn/longhorn-manager/pull/601 merged, move back to `Merged`

**Comment by khushboo-rancher** [comment]
Verified on master - 06-08-2020

Verification - **Passed**

**Scenarios tested:**
1. Power down the attached node when DR volume restore is in progress.
2. Power down the attached node when DR volume incremental restore is in progress.
3. Power down a replica node when DR volume restore is in progress.
4. Power down a replica node when DR volume incremental restore is in progress.
5. Reboot the attached node when DR restore is in progress.
6. Reboot the attached node when DR volume incremental restore is in progress.
7. Reboot a replica node when DR restore is in progress.
8. Reboot a replica node when DR volume incremental restore is in progress.
