### ISSUE TITLE
UI: add drop down list support

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#1368]
For #820 I added a optional string Choices array to the SettingsDefinition schema.
See the following [commit](https://github.com/longhorn/longhorn-manager/pull/571/commits/dc593e7628ab1848266a8e9c73e096af05078349) for details.

It would be nice, if we can add a generic drop down component that is rendered anytime there is a Choices array present in the retrieved SettingsDefinition. We intend to use the dropdown in this case for the `VolumeAttachmentRecoveryPolicy`

Let me know if you would like additional backend changes.

**Comment by sowmyav27** [comment]
**Validated on master ui tag, longhorn - 1.0.0-rc1 - 05/21/2020**

- `Volume Attachment Recovery Policy` is seen as dropdown in settings page
<img width="1848" alt="Screen Shot 2020-05-21 at 4 06 58 PM" src="https://user-images.githubusercontent.com/26032343/82614703-5e16ef00-9b7d-11ea-9c32-6c83e9e2336d.png">

- Value is saved when you select one any option from dropdown.
- checked in `v1/settings/volume-attachment-recovery-policy`
