### ISSUE TITLE
Add volumeattachment to the support bundle

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1369]
We want to collect volume attachment for the support bundle.

Steps to verify this fix:
1. On UI click `Generate Support Bundle` on the left bottom.
2. Fill the URL and description for this support bundle.
3. The support bundler will be downloaded once it's done. And check yamls/kubernetes directory, there should be a volumeattachment yaml file if there is a volumeattachment object in the cluster.

**Comment by boknowswiki** [comment]
@yasker , do we have any document about support bundle and volumeattachment? I am trying to understand the issue. Thanks.

**Comment by yasker** [comment]
See https://github.com/longhorn/longhorn-manager/blob/master/manager/misc.go

It's a downloadable zip file that collects the log and yaml files in the `longhorn-system` namespace and others (e.g. volumeattachment object will be globally available). You can find it using the footer `Generate support bundle` link on the UI.

**Comment by boknowswiki** [comment]
* [ ] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [ ] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~
* [ ] ~~**If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?~~
* [ ] ~~**if labeled: require-automation-engine** Has the engine integration test been merged?~~
* [ ] ~~**if labeled: require-doc** Has the necessary document PR submitted or merged?~~

**Comment by sowmyav27** [comment]
**Verified on master - 05/22/2020**

Validation: **`PASSED`**

**Steps:**

- Deployed two volumes, attached it to workloads - 2 .
- kubectl get volumeattachment showed

```
> kubectl get volumeattachment
NAME                                                                   ATTACHER             PV         NODE                           ATTACHED   AGE
csi-14262e9b3cc68ec1a394a01220f7e7478d241f27b5b8dd0afafc8e4a1e9119cb   driver.longhorn.io   volume-2   sowmya-longhorn-new-worker-1   true       6m55s
csi-c7515e19c5d1e05a50cf69032cf82c8699a1272ea6d2a45d2e8e28bc46dcda58   driver.longhorn.io   volume-1   sowmya-longhorn-new-1          true       61m
```

- On UI click Generate Support Bundle on the left bottom.
- Fill the URL and description for this support bundle.
- The support bundler will be downloaded once it's done. And check yamls/kubernetes directory, 
- The folder had a `volumeattachments.yaml` which included details about the above 2 volume attachments
