### ISSUE TITLE
[BUG]Volume expansion will succeed even if the volume scheduling fails

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1373]
**Describe the bug**
This issue is similar to #1361

**To Reproduce**
1. Create a volume with (N+1) replicas in the N-node Longhorn cluster.
2. Expand the volume for multiple times

**Expected behavior**
The API call should be disabled or should fail.

**Environment:**
 - Longhorn version: v1.0.0-rc1

**Comment by shuo-wu** [comment]
Manual test 1:
1. Create a volume with (N+1) replicas in the N-node Longhorn cluster.
2. Verify the volume scheduling failure.
3. Try to expand the volume and get an error.

Manual test 2:
1. Create a volume with N replicas in the N-node Longhorn cluster.
2. Attach the volume and write some data.
3. Disable scheduling for one node and delete the related replica of the volume.
4. Verify the volume scheduling failure.
5. Detach the volume.
6. Verify that the failed replica is removed and volume scheduling failure is gone.
7. Try to expand the volume and wait for expansion success.
8. Attach the volume and verify the existing data.
9. Write more data to the volume.
10. Enable the scheduling for the node.
11. Repeat step 3 ~ 10

**Comment by yasker** [comment]
Note: we should require the volume to be healthy before it can be resized.

Hmm? If the volume is detached then we allow resizing? I am confused.

**Comment by shuo-wu** [comment]
After step 5 of test 2, the volume **contains healthy replicas only** hence the expansion is fine. 

If there is still scheduling failed replica after the detachment, the volume cannot be reattached/reused again, that would be a bug.

**Comment by yasker** [comment]
That means when we attach the volume, the rebuild progress will also start along with volume expansion?

**Comment by shuo-wu** [comment]
No. The rebuild is disabled for auto attached volumes. (Restoring volume, expanding volume, DR volume). See the fix for #1270

**Comment by shuo-wu** [comment]
Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [x] Is the reproduce steps/test steps documented?
* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~
* [ ] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [x] ~~**if labeled: require-automation-engine** Has the engine integration test been merged?~~
* [x] ~~**if labeled: require-doc** Has the necessary document PR submitted or merged?~~

**Comment by shuo-wu** [comment]
The fix of UI part:
Gray out the button `Expand Volume` when `volume.conditions[scheduled].status == false && v. state == "detached"`

**Comment by sowmyav27** [comment]
**Reproduced issue on 1.0.0-rc1**

**Steps:**

- Create a volume with (N+1) replicas in the N-node Longhorn cluster with volume size 20G
- Expand the volume to 25G
- Replicas are seen running and when they come in detached mode, only N replicas are available and `Ready for workload:Ready`

**Validated on the latest master - 05/22/2020 - Ui tag: `9ab6368` and at 12:00 PDT**

- Create a volume with (N+1) replicas in the N-node Longhorn cluster with volume size 20G
- Expand the volume to 25G
- Error is seen, volume does not expand. `unable to expand volume test-issue-2: cannot expand volume before replica scheduling success`
- Volume is seen in 
```
Scheduling Failure
Replica Scheduling Failure
```

**Comment by yasker** [comment]
@sowmyav27 The PR was merged after rc1, can you retry with the master?

**Comment by sowmyav27** [comment]
**Validated on latest master -05/22/2020, ui tag: `8307588`**

**Steps:**

- Create a volume with (N+1) replicas in the N-node Longhorn cluster with volume size 20G when node soft affinity: False
- the volume will be in detached state with message:
```
Scheduling Failure
Replica Scheduling Failure
```
- `Expand Volume` option is not enabled in the UI
- When trying to expand volume from API `v1/volumes/<volume-name>`
- Error seen
```
{
"actions": { },
"code": "Server Error",
"detail": "",
"links": {
"self": "…/v1/volumes/test-2",
},
"message": "unable to expand volume test-2: cannot expand volume before replica scheduling success",
"status": 500,
"type": "error",
}
```
