### ISSUE TITLE
[BUG] Info text for "Volume Attachment Recovery Policy" in settings page can be formatted

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1374]
**Describe the bug**
Info text for "Volume Attachment Recovery Policy" in settings page can be better formatted

**To Reproduce**
Currently the UI displays the text as 
```
  Required. Defines the Longhorn action when a Volume is stuck with a Deployment Pod on a failed node. `wait` leads to the deletion of the volume attachment as soon as the pods deletion time has passed.`never` is the default Kubernetes behavior of never deleting volume attachments on terminating pods.`immediate` leads to the deletion of the volume attachment as soon as all workload pods are pending.
```
<img width="1791" alt="Screen Shot 2020-05-20 at 10 10 31 AM" src="https://user-images.githubusercontent.com/26032343/82476154-75bd7d00-9a82-11ea-8675-8ed769280b73.png">

**Expected behavior**
Its a little hard to read and understand. It can be better formatted (text/font)

**Environment:**
 - Longhorn version: v1.0.0-rc1

**Comment by yasker** [comment]
We currently cannot change the text or font of the setting. The detail of the setting description can be read at https://longhorn.io/docs/0.8.1/references/settings/ once it's done.

**Comment by yasker** [comment]
@smallteeths Can we support a richer format in the setting description? E.g. multi-lines, quote, link.

**Comment by smallteeths** [comment]
It cannot be formatted temporarily. The data is now the back end of the direct read. If you need to change the format, you may need the back-end returned data to conform to a specific structure  @yasker

**Comment by yasker** [comment]
@smallteeths how about markdown format? Can we support that in the UI?

**Comment by yasker** [comment]
The UI has changed the setting to use markdown style. The only except is to use `\n\n` for line change instead of `\n`.

**Comment by yasker** [comment]
@joshimoo The frontend markdown schema change has been merged. Can you update the description for the settings?

**Comment by joshimoo** [comment]
Will format the settings.

**Comment by khushboo-rancher** [comment]
Verified in Master - 06-11-2020

Can we make space between line little less, it is occupying a considerable space on UI.

<img width="1608" alt="Screen Shot 2020-06-11 at 1 16 48 PM" src="https://user-images.githubusercontent.com/60111667/84435074-fe44be80-abe5-11ea-8fe1-10d6fae75cee.png">

**Comment by joshimoo** [comment]
@khushboo-rancher open a ui issue, and link to this. @smallteeths needs to create css styling for this.

**Comment by khushboo-rancher** [comment]
Created https://github.com/longhorn/longhorn/issues/1484, this issue can be closed once https://github.com/longhorn/longhorn/issues/1484 is fixed.

**Comment by khushboo-rancher** [comment]
Verified on master - 06-12-2020, This is good to close.
<img width="1097" alt="Screen Shot 2020-06-12 at 4 35 38 PM" src="https://user-images.githubusercontent.com/60111667/84554330-30305080-accc-11ea-8d83-d7e16833be33.png">
