### ISSUE TITLE
[BUG] UI: Sometimes UI doesn't allow to delete replica from the node page

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1377]
<img width="802" alt="Screen Shot 2020-05-20 at 4 06 49 PM" src="https://user-images.githubusercontent.com/3344618/82506463-b8984880-9ab4-11ea-8294-b62558477e2f.png">

On the page above, when the mouse cursor moved to the checkbox of replica, it's disabled.

It happened with node showing as schedulable or down.

It prevents the node from being removed.

**Comment by sowmyav27** [comment]
**Verified on ui tag: `wangsiye/longhorn-ui:af54fa9`**

Validation: **`PASSED`**

- Delete option - checkboxes for the replicas work.
- User is able to select and delete the replicas.

<img width="798" alt="Screen Shot 2020-05-21 at 5 38 03 PM" src="https://user-images.githubusercontent.com/26032343/82619701-7db51400-9b8b-11ea-96e6-81594876700c.png">

**Comment by yasker** [comment]
Hold on on this one.

**Comment by yasker** [comment]
I also cannot reproduce this issue now.

**Comment by sowmyav27** [comment]
**Verified on master - ui tag: `e789737`**

**Steps:**

- Delete option - checkboxes for the replicas work.
- User is able to select and delete the replicas.
- Verified on nodes which are `Schedulable` and `Down`
