### ISSUE TITLE
[BUG]UI: Without backuptarget set, backup target error is shown on every page

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1382]
<img width="414" alt="Screen Shot 2020-05-21 at 11 02 51 AM" src="https://user-images.githubusercontent.com/3344618/82590528-b4226d00-9b52-11ea-9e2c-f428915e319d.png">

The above information is shown on every page when there is no backup target. It should be shown only on the backup page.

**Comment by sowmyav27** [comment]
**Verified with ui tag: wangsiye/longhorn-ui:afa7e56**

Validation: **`PASSED`**

- `error listing backups: setting backup-target is empty` message is shown when the target is empty only in the backup page

**Comment by sowmyav27** [comment]
**Verified with master - 05/22/2020 - 12:00 PDT**

**Validation: `PASSED`**

- `error listing backups: setting backup-target is empty` message is shown when the target is empty only in the backup page
