### ISSUE TITLE
[BUG] ui: Error in the console when user tries to save recurring backup/snapshot in a detached volume

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1383]
**Describe the bug**
[BUG] Error in the console when user tries to save recurring backup/snapshot in a detached volume

**To Reproduce**

- Create a volume in Longhorn.
- Volume will be in detached state.
- Click on recurring Snapshot and backup
- Enter backup/snapshot and click on Save.
- There is an error in the console. And the changes are NOT saved

```
Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at main.57489847.async.js?9dec21b8a6e1c16d51e5:280
    at O (main.57489847.async.js?9dec21b8a6e1c16d51e5:280)
    at main.57489847.async.js?9dec21b8a6e1c16d51e5:286
    at s (main.57489847.async.js?9dec21b8a6e1c16d51e5:147)
    at Generator._invoke (main.57489847.async.js?9dec21b8a6e1c16d51e5:147)
    at Generator.forEach.e.<computed> [as next] (main.57489847.async.js?9dec21b8a6e1c16d51e5:147)
    at a (main.57489847.async.js?9dec21b8a6e1c16d51e5:7)
    at c (main.57489847.async.js?9dec21b8a6e1c16d51e5:7)
    at main.57489847.async.js?9dec21b8a6e1c16d51e5:7
    at new Promise (<anonymous>)
```
<img width="1913" alt="Screen Shot 2020-05-21 at 12 15 49 PM" src="https://user-images.githubusercontent.com/26032343/82597017-2c8e2b80-9b5d-11ea-9adf-d06e854309ac.png">

**Expected behavior**
User should be able to save the data

**Environment:**
 - Longhorn version: 1.0.0-rc1
 - Kubernetes version: 1.17.5
 - Node OS type and version: rke do linux 18.04

**Comment by sowmyav27** [comment]
**Verified with ui tag: wangsiye/longhorn-ui:afa7e56**

Validation: **`PASSED`**

- Create a volume in Longhorn.
- Volume will be in detached state.
- Click on recurring Snapshot and backup
- Enter backup/snapshot and click on Save.
- No error is seen in console.
- Changes are saved.

**Comment by sowmyav27** [comment]
**Verified on master - 05/22/2020 - ui tag: `9ab6368`**

Validation: **`FAILED`**

**Steps:**

- Create a volume in Longhorn.
- Volume will be in detached state.
- Click on recurring Snapshot and backup
- Enter backup/snapshot and click on Save.
- There is an error in the console. And the changes are NOT saved

<img width="1859" alt="Screen Shot 2020-05-22 at 12 04 00 PM" src="https://user-images.githubusercontent.com/26032343/82701134-6f670680-9c24-11ea-8abf-654a76ab86a2.png">

**Comment by yasker** [comment]
@sowmyav27 @smallteeths This is weird... This is the same error message as before.

**Comment by sowmyav27** [comment]
**Verified on master - ui tag: `ca99642` on longhorn - 1.0.0-rc1** 

Validation: **`PASSED`**

**Steps:**

- Create a volume in Longhorn.
- Volume will be in detached state.
- Click on recurring Snapshot and backup
- Enter backup/snapshot and click on Save.
- There is no error on the console and the changes made are saved.

**Comment by yasker** [comment]
@sowmyav27 Thanks. I've moved the issue to merged column.
