### ISSUE TITLE
[BUG] Longhorn instance managers wrongly terminated during upgrade process from v.0.8.1 to v1.0.0-rc1 

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#1384]
**Describe the bug**

**To Reproduce**
1. Install Longhorn v0.8.1
2. Create a StatefulSet using Longhorn volumes,
3. Scale StatefulSet pods to 10
4. Upgrade to Longhorn v1.0.0-rc1
5. Check Longhorn volumes 

**Observed**
Volumes **detached** and **reattached** again, and some of them kept **stuck at Attaching state**

Instance manager from the old version get recreated

**Expected behavior**
Volumes should be **left in Attached** state, rather than detached and then reattached.

Instance manager from the old version should still exist and running fine after the upgrade until the engine image upgraded for the volumes.

**Log**
```
level=warning msg="Cannot find the instance status in instance manager instance-manager-r-a49c0462 for the running instance pvc-61c5bad6-2ace-4d46-9f2f-477185585d1b-r-0aae2c2e, will mark the instance as state ERROR"
```

This following log indicates that the old instance manager was mistakenly stopped.
```
[longhorn-manager-2vw9b] time="2020-05-21T23:59:08Z" level=warning msg="Starts to clean up then recreates pod for instance manager instance-manager-r-cd542990 with state stopped
```

**Environment:**
 - Longhorn version: v1.0.0-rc1
 - Kubernetes version: v1.16
 - Node OS type and version: Ubuntu 18.04

**Additional context**

- Support Bundle
[longhorn-support-bundle_e7c01230-dcee-43c4-9e25-f37fecce7f4a_2020-05-21T20-40-54Z.zip](https://github.com/longhorn/longhorn/files/4664958/longhorn-support-bundle_e7c01230-dcee-43c4-9e25-f37fecce7f4a_2020-05-21T20-40-54Z.zip)

**Comment by yasker** [comment]
A few things regarding why we didn't catch this in the automation upgrade test:
1. `Auto salvage` should be false during the upgrade phase.
2. We should use pod without `liveness` check for the validation, instead of volume directly. So anything went wrong we will catch it.
3. We need more volumes in the test_upgrade.

@meldafrawi can you make the change to the `longhorn-tests` to cover this?

In this case, all the old instance managers were deleted automatically even when there are running engine/replicas. Then our auto attachment mechanism kicked in and save the day for the most volumes. But if the pod is not created with liveness check, it will go bad.

**Comment by yasker** [comment]
Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
* [ ] **if labeled: require-doc** Has the necessary document PR submitted or merged?
* [ ] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [ ] **if labeled: require-automation-engine** Has the engine integration test been merged?
* [ ] **if labeled: require-manual-test-plan-doc** Has the manual test plan been documented?

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn version: `master`

Steps to test:
1. Install Longhorn v0.8.1
2. Create a StatefulSet using Longhorn volumes,
3. Scale StatefulSet pods to 10
4. Upgrade to Longhorn v1.0.0-rc1
5. Check Longhorn volumes 

> Volumes kept in attached state, and pod restarts = 0

**Comment by yasker** [comment]
Filed https://github.com/longhorn/longhorn/issues/1391 for automation test.

**Comment by yasker** [comment]
Updated https://github.com/longhorn/longhorn-tests/wiki/Manual-Test-Plan#longhorn-upgrade-test
