### ISSUE TITLE
Remove the cleanup code for compatible-csi-attacher

### ISSUE THREAD

**Issue by boknowswiki** [longhorn/longhorn#1390]
This issue is to tracking removing the cleanup code for compatible-csi-attacher.

Link to the code to be removed:

https://github.com/longhorn/longhorn-manager/blob/044462f5cf901138be3559f1fd7440ad8b53650e/app/driver.go#L248-L266

And it's introduced by:

https://github.com/longhorn/longhorn/issues/1365

**Comment by yasker** [comment]
As long as there isn't any side effect showing in our test, this is considered done.
