### ISSUE TITLE
[BUG] Volume is seen in faulted state when navigating to backup page after the last backup has been deleted and before the Backupstore Poll Interval interval has passed

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1392]
**Describe the bug**
Volume is seen in faulted state when navigating to backup page after the last backup has been deleted and before the Backupstore Poll Interval interval has passed

**To Reproduce**
- Create a volume vol1, attach to workload in Cluster A
- Write data
- Set `Backupstore Poll Interval` as 6000 (a large value)
- Take a backup b1
- Create a DRV volume test in Cluster A from vol1 b1
- Write data and take a backup b2
- Before the Backupstore Poll Interval interval has passed and restore of b2 happens on DRV, Delete latest backup - b2
- The DRV volume goes into restoring state
- The DRV volume is in `Faulted` state now.
- Longhorn Manager logs
```
time="2020-05-22T22:07:49Z" level=warning msg="volume-new-2-r-de5a0267: time=\"2020-05-22T22:07:23Z\" level=info msg=\"Successfully initiated incremental restore for s3://sowmya-rc1-longhorn@us-east-2/?backup=backup-65ea78e187714e6e&volume=volume-new to volume-delta-backup-72fff603be5e4f37.img\""
time="2020-05-22T22:07:49Z" level=warning msg="volume-new-2-r-de5a0267: time=\"2020-05-22T22:07:45Z\" level=error msg=\"Backup Restore Error Found in Server[failed to get object: backupstore/volumes/74/e0/volume-new/blocks/41/6f/416f7cb65b6623d6af031a8bd7eeb53b3d418cb8238386af144d61f1849b444c.blk response: {\\n  Body: <nil>,\\n  ContentType: \\\"application/xml\\\"\\n} error: AWS Error:  NoSuchKey The specified key does not exist. <nil>\\n404 D50075AA4AE49B56\\n]\""
time="2020-05-22T22:07:49Z" level=warning msg="volume-new-2-r-de5a0267: time=\"2020-05-22T22:07:45Z\" level=error msg=\"failed to incremental restore: failed to get object: backupstore/volumes/74/e0/volume-new/blocks/41/6f/416f7cb65b6623d6af031a8bd7eeb53b3d418cb8238386af144d61f1849b444c.blk response: {\\n  Body: <nil>,\\n  ContentType: \\\"application/xml\\\"\\n} error: AWS Error:  NoSuchKey The specified key does not exist. <nil>\\n404 D50075AA4AE49B56\\n\""
time="2020-05-22T22:07:49Z" level=debug msg="Prepare to delete instance volume-new-2-r-de5a0267"
```
`backup-65ea78e187714e6e` --> is the last backup
[longhorn-support-bundle_ff0f2e60-8253-4ca8-a162-72109efca3a7_2020-05-22T22-11-18Z.zip](https://github.com/longhorn/longhorn/files/4670604/longhorn-support-bundle_ff0f2e60-8253-4ca8-a162-72109efca3a7_2020-05-22T22-11-18Z.zip)

**Expected behavior**
Volume should not be in faulted state

**Environment:**
 - Longhorn version: master - 05/22/2020
 - Kubernetes version: 1.17.5
 - Node OS type and version: linus 18.04

**Comment by yasker** [comment]
Check again once https://github.com/longhorn/longhorn/issues/1393 is done.

**Comment by khushboo-rancher** [comment]
Verified on Master - 07-10-2020

Validation - **Passed**

Followed the repro steps from https://github.com/longhorn/longhorn/issues/1392#issue-623561580, the DR volume stayed healthy didn't go to ```Faulted``` state. 
Also, taking another backup in the same volume resulted in smooth incremental restore next time.

**Comment by khushboo-rancher** [comment]
Manual test steps are updated https://github.com/longhorn/longhorn-tests/wiki/Manual-Test-Plan#dr-volume-related-latest-backup-deletion-test
