### ISSUE TITLE
[FEATURE] Don't allow backup deletion when in use for restoration

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1393]
We need to find a way to stop the user from deleting a backup when it's being used for restoration.

Root cause of: https://github.com/longhorn/longhorn/issues/1392

**Comment by joshimoo** [comment]
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The PR is at

* [x] Is the reproduce steps/test steps documented?

* [x] Which areas/issues this PR might have potential impacts on?
Area: Backup
Issues: longhorn/longhorn#612

* [x] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~~

* [x] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at~~

* [ ] **If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at

* [ ] **if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at

* [x] ~~**if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at~~

**Comment by yasker** [comment]
Move to v1.0.2 due to build failure and engine integration test failure.

**Comment by yasker** [comment]
@joshimoo Can you update the backupstore for manager and engine to get this issue to Merged?

**Comment by meldafrawi** [comment]
Steps to test:

1. Create a volume, create a PV/PVC, and attach it to a workload
2. Write 3 data files of the following sizes respectively (512MB, 1GB, 2 GB) to the volume, create backups after each data write operations.
3. Restore a volume using any created backup, while restore process is running, try to delete any backup or the backupvolume.
4. > you will NOT be able to delete any backup, or the backupVolume. 
5. After all 3 backups completed, write another data file with size 4GB, while backup4 is created, try to delete any backup or the backupvolume.
6. > you will NOT be able  to delete any backup or the backupVolume
7. while backup4 is created, restore any backup to a volume, try to delete any backup or the backupvolume.
8. > you will NOT be able to delete any backup or the backupVolume

**Comment by meldafrawi** [comment]
Manual Validation **PASSED**

- Created backups will not be deleted in case of restoring, or another backup is being created, 
- Still Waiting for UI changes.
