### ISSUE TITLE
[BUG] On creating backup in S3/NFS backup store, an additional backups folder appears with error

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1399]
**Describe the bug**
On creating backup in NFS backup store, an additional backups folder appears with no data in backup page.

**To Reproduce**
1. Set up a S3/NFS backup store.
2. Create a backup of a volume.
3. An additional backup starts appearing in backup page with error.
<img width="1697" alt="Screen Shot 2020-05-23 at 1 29 32 PM" src="https://user-images.githubusercontent.com/60111667/82740173-2766e300-9cfb-11ea-8686-9ef238a40e30.png">
<img width="1704" alt="Screen Shot 2020-05-23 at 1 35 56 PM" src="https://user-images.githubusercontent.com/60111667/82740178-2f268780-9cfb-11ea-834f-7405858a1cef.png">

**Expected behavior**
Only the backup created of volume should be appeared in backup page.

**Logs**
[longhorn-support-bundle_970bcbca-602f-4813-ac1c-4741240f545b_2020-05-23T20-41-28Z.zip](https://github.com/longhorn/longhorn/files/4672486/longhorn-support-bundle_970bcbca-602f-4813-ac1c-4741240f545b_2020-05-23T20-41-28Z.zip)

**Environment:**
 - Longhorn version: master-05-22-2020
 - Kubernetes version: v1.17.5
 - Node OS type and version: Ubuntu 18.04

**Comment by joshimoo** [comment]
This happened because when creating the placeholder in progress backup.cfg, the volume name was not set. Which lead to the saveBackup placing the backup in the path before the volume.

I added a check in saveBackup to verify that a volume is always set, this prevents this error from happening again in the future.

**Comment by joshimoo** [comment]
Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [x] Is the reproduce steps/test steps documented?
* [x] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?~~
* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~
* [x] ~~**if labeled: require-doc** Has the necessary document PR submitted or merged?~~
* [x] ~~**If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?~~
* [x] ~~**if labeled: require-automation-engine** Has the engine integration test been merged?~~
* [x] ~~**if labeled: require-manual-test-plan-doc** Has the manual test plan been documented?~~

**Comment by khushboo-rancher** [comment]
Verified on master - 05-23-2020

Backup is not showing the additional backup folder with error reported in the issue. Only created backups are available in backup page.

Scenarios verified:
1. Volume created and backup taken in S3 backup store.
1. Volume created and backup taken in NFS backup store.
