### ISSUE TITLE
[BUG] "Delete All Backups" does not delete the backup volume folder

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1401]
**Describe the bug**
"Delete All Backups" does not delete the backup volume folder

**To Reproduce**

- Create a volume - `vol-1`, attach to a node, write data, take backups b1 and b2 for the volume. 
- Navigate to Backup Page.
- From operations select "Delete All Backups" for the backup volume
- All the backups get deleted but the  backup volume folder is still available on the UI

**Expected behavior**
On doing a "Delete All Backups" for the backup volume, the backup volume folder should also be removed along with all the backups related to that volume.

**Note:**
`v1/backupvolumes` lists. `vol-1`

**Environment:**
 - Longhorn version: master(05/24/2020) - ui tag - `e789737`(latest)

**Comment by aimbot31** [comment]
I'm so glad someone opened this issue.. I'm facing an issue that may be related.
I'm using Google Cloud Storage for the backups and when i try to delete a single backup, nothing happens (no warning, errors etc..) The backup seems to be still there (in the bucket and ui).
When i'm trying to delete all the backups, i got an error :/ 

```
error deleting backup volume pvc-2971047b-9be9-4ed2-a127-48d1a57e0080: error deleting backup volume: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v0.8.1/longhorn [backup rm --volume pvc-2971047b-9be9-4ed2-a127-48d1a57e0080 s3://k8s_dev_bucket@europe-west4/longhorn], output failed to remove all the backups for volume pvc-2971047b-9be9-4ed2-a127-48d1a57e0080: failed to remove objects with param { Bucket: "k8s_dev_bucket", Delete: { Objects: [{ Key: "longhorn/backupstore/volumes/1c/36/pvc-2971047b-9be9-4ed2-a127-48d1a57e0080/backups/backup_backup-90b6a98a2839486b.cfg" },{ Key: "longhorn/backupstore/volumes/1c/36/pvc-2971047b-9be9-4ed2-a127-48d1a57e0080/backups/backup_backup-d169fb81f7c043ff.cfg" }], Quiet: true } }: AWS Error: InvalidArgument Invalid argument. <nil> 400 , stderr, time="2020-05-25T16:35:33Z" level=error msg="{\n\n}" pkg=s3 time="2020-05-25T16:35:33Z" level=error msg="failed to remove all the backups for volume pvc-2971047b-9be9-4ed2-a127-48d1a57e0080: failed to remove objects with param {\n Bucket: \"k8s_dev_bucket\",\n Delete: {\n Objects: [{\n Key: \"longhorn/backupstore/volumes/1c/36/pvc-2971047b-9be9-4ed2-a127-48d1a57e0080/backups/backup_backup-90b6a98a2839486b.cfg\"\n },{\n Key: \"longhorn/backupstore/volumes/1c/36/pvc-2971047b-9be9-4ed2-a127-48d1a57e0080/backups/backup_backup-d169fb81f7c043ff.cfg\"\n }],\n Quiet: true\n }\n}: AWS Error: InvalidArgument Invalid argument. <nil>\n400 \n" , error exit status 1
```

I hope my problem is related to this issue

**Comment by yasker** [comment]
Hi @aimbot31 ,

I think the original issue might not be related since it's likely a regression introduced by one of the recent changes after v0.8.1 release. Your issue looks different. Can you file another issue for it? We will look into it.

**Comment by yasker** [comment]
@sowmyav27 I assume it's always reproducible, right?

**Comment by joshimoo** [comment]
@sowmyav27 can you attach a support bundle, also do you have recurring backups setup for that volume?

**Comment by sowmyav27** [comment]
@yasker Yes I am able to reproduce this always.
@joshimoo Attached the support bundle
[longhorn-support-bundle_1c9b022b-fa90-4793-92a1-253180b6f315_2020-05-26T16-58-10Z.zip](https://github.com/longhorn/longhorn/files/4683750/longhorn-support-bundle_1c9b022b-fa90-4793-92a1-253180b6f315_2020-05-26T16-58-10Z.zip)

**Comment by sowmyav27** [comment]
Not able to reproduce this issue on the latest master - 05/26/2020 ui tag: `e789737`

**Comment by sowmyav27** [comment]
Closing the issue. Will reopen if this issue is hit again.
