### ISSUE TITLE
[BUG] Cannot modify "Longhorn Static StorageClass Name" or other fields

### ISSUE THREAD

**Issue by awlleon** [longhorn/longhorn#1407]
**Describe the bug**
From UI cannot modify "Longhorn Static StorageClass Name", so is the field "Backup Target" .

**To Reproduce**
1. In the settings page in Longhorn UI, set the "Longhorn Static StorageClass Name" - "longhorn" and Save.
2. Reopen  settings page , "Longhorn Static StorageClass Name"  is still "longhorn-static".
4. Error is seen in chrome Console tab "PUT http://xxxx/v1/settings/default-longhorn-static-storage-class net::ERR_CONNECTION_RESET"

**Environment:**
 - Longhorn version: 0.8.0
 - Kubernetes version: 1.16.2
 - Node OS type and version: CentOS Linux release 7.7.1908

![longhorn-bug](https://user-images.githubusercontent.com/51808092/82966183-cee65d00-9ffc-11ea-96f9-c89322e882d3.png)

**Comment by awlleon** [comment]
[](url)

**Comment by yasker** [comment]
It looks like you have some network issues for the UI to reach the backend API server.

**Comment by awlleon** [comment]
> It looks like you have some network issues for the UI to reach the backend API server.

Yes, I found that it seems to be related to nginx-ingress.

When I use curl -X PUT 'http: // longhorn-service-ip /v1/ settings/default-longhorn-static-storage-class' on a worker node, it is ok.
Use curl -X PUT 'http: // longhorn-domain-name /v1/ settings/default-longhorn-static-storage-class' on worker node, longhorn-domain-name points to nginx-ingress, which is also ok .
But on computers other than the cluster, always return: curl: (56) Recv failure: Connection reset by peer.
curl -X GET is always no problem

**Comment by yasker** [comment]
Hi @awlleon , have you figured out what's wrong?

**Comment by awlleon** [comment]
Finally I found out that this was caused by WAF deployed before k8s cluster. The WAF administrator has configured a strategy to disable PUT and DELET methods.
