### ISSUE TITLE
[BUG] Fix ticker leakage

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#1408]
I noticed that we are leaking Tickers, this is a tracking issue for the pull requests on all of the longhorn projects to fix the leakage.

**Comment by yasker** [comment]
This change is a bit bigger than I expected. Especially if `go-iscsi-helper` is changed, that means we need to change the engine too. We can merge this after the GA.

**Comment by yasker** [comment]
@joshimoo PR merged, will need a PR for the engine. Btw, is there anything we can test for this?

**Comment by joshimoo** [comment]
Will submit pr's for the updated go-iscsi dependency.
To identify these leaked resources in the future we could look into setting up profiling on one of our test clusters. 

In terms of integration tests, the csi ticker fix should be covered by all regular csi operations. The manager ticker fix should be covered by normal usage as well (ratelimiter)

I don't see how we could create a specific test for this specific issue.

**Comment by joshimoo** [comment]
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [x] Is the backend code merged?
The PR is at [32](https://github.com/longhorn/go-iscsi-helper/pull/32) [593](https://github.com/longhorn/longhorn-manager/pull/593)

* [x] ~~Is the reproduce steps/test steps documented?~~

* [x] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~~

* [x] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at ~~

* [x] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at~~

* [x] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~~

* [x] ~~**if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at~~

**Comment by yasker** [comment]
It's refactoring, so I don't think we have a specific way to test this now.

#538 might be related to this. I will see if we can test that.

**Comment by khushboo-rancher** [comment]
I've set up a cluster of it, we can check CPU utilization after few days.

**Comment by joshimoo** [comment]
@khushboo-rancher can you also keep track of memory usage?

**Comment by yasker** [comment]
@joshimoo the monitoring is enabled on the cluster, so memory usage will be tracked as well.

**Comment by khushboo-rancher** [comment]
We observed gradual increment in memory/cpu utilization but not sudden spike in the trend.
Closing this issue now. This will be more analyzed in https://github.com/longhorn/longhorn/issues/1463
<img width="1343" alt="Screen Shot 2020-07-02 at 2 01 14 PM" src="https://user-images.githubusercontent.com/60111667/86408850-a4776780-bc6c-11ea-8ddc-09c661431616.png">
