### ISSUE TITLE
[BUG] Backup List issue when failing to retrieve backup names for backup volume

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#1410]
**Describe the bug**
When trying to List all Backup Volumes and there is an error to retrieve the backupnames via `getBackupNamesForVolume` for a volume, we currently return an error back to the caller instead of setting the error as part of the VolumeInfo object. This blocks the ui/api from showing all available backup volumes.

**To Reproduce**
This is just one of many possible failure cases, but this one is easy to reproduce

Setup:
- create vol `bak1`, `bak2`, `bak3` and attach to nodes
- write some data to all volumes
- take a backup of each volume

Repro:
- create a file named: `backup_1234@failure.cfg` inside of the backups folder for volume `bak2`
- now list backup volumes will fail and you should no longer see backup volumes
- you should still be able to see backups for `bak1`, `bak3` if manually requested via the api

**Expected behavior**
Show available backup volumes and backups even if a single backup volume has issues.

**Comment by joshimoo** [comment]
## Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged?
The PR is at

* [ ] Is the reproduce steps/test steps documented?

* [ ] **If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at

* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at

* [ ] **if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at 

* [ ] **If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at

* [ ] **if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at

* [ ] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at

**Comment by joshimoo** [comment]
After discussing with @khushboo-rancher we decided to address the general case here and just ignore & log invalid named files instead of erroring out.

**Comment by khushboo-rancher** [comment]
On current master, if a faulted backup file exists for volume v1, other backups of v1 are not being shown on UI but backups related to other volumes(having no faulted backup.cfg) are shown on backup page.

There are two scenarios here:
1. If a backup.cfg file is faulted in backup store for volume v1, other backups of same volume v1 should be retrieved properly. 
2. If a backup.cfg file is faulted in backup store for volume v1, - v2, v3 etc other volumes backups should be retrieved properly.

**Comment by khushboo-rancher** [comment]
Verified on Master - 06-15-2020, if one config is corrupted in a backup store, others appear properly on backup page in longhorn.

Validation - **Passed**

**Scenario tested**
1. Backup store having below backup config files
 a. Config file created with symbol in its name. 
 b. Config file having invalid Json.
 c. Empty config file
 d. Config file having missing tags
 e. Config file having dummy values in few tags.
2. With above files in backup store, Longhorn list all the good backups of same volumes and different volumes.
3. Restore from latest backup and restore individual backup work fine.
4. User is able to create new backups.

**Comment by meldafrawi** [comment]
test `test_backup_volume_list` Pass
