### ISSUE TITLE
[BUG] UI: Disable Update Replica Count button for DR volumes

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#1414]
**Describe the bug**

**To Reproduce**
1. Create a volume attach it to a node, write some data to it and create a backup
2. Create DR volume from created backup.
3. Try to Update replica count for DR volume

ERR: `unable to update replica count for volume volume-test-1-dr: invalid volume state to update replica countattached`

![image](https://user-images.githubusercontent.com/18232258/83063173-0a664300-a060-11ea-8ff8-34b1f83d0f9d.png)

![image](https://user-images.githubusercontent.com/18232258/83063463-7ba5f600-a060-11ea-9cc4-ed4b4069da12.png)

**Expected behavior**
Update Replica Count button for DR volumes should be disabled

**Log**
N/A

**Environment:**
 - Longhorn version: `master`
 - Kubernetes version: 1.17
 - Node OS type and version: Ubuntu 18.04

**Additional context**
N/A

**Comment by yasker** [comment]
It's too close to the GA. Let's do this in v1.0.1 instead.

**Comment by yasker** [comment]
The change seems very small. We can merge it for v1.0.0.

**Comment by sowmyav27** [comment]
**Validated on master ui tag: `23c813d` longhorn: `v1.0.0-rc3`**

` Update replica count` for DR volume is disabled
<img width="1651" alt="Screen Shot 2020-05-29 at 12 27 20 PM" src="https://user-images.githubusercontent.com/26032343/83297656-cc743680-a1a7-11ea-8aa4-968a5109583c.png">
<img width="1642" alt="Screen Shot 2020-05-29 at 12 27 56 PM" src="https://user-images.githubusercontent.com/26032343/83297678-d85ff880-a1a7-11ea-9ba1-df6e9dc6d7b1.png">
