### ISSUE TITLE
[BUG] Volume is shown in healthy state when attached node is deleted when restore is in progress

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1415]
**Describe the bug**
Volume shows healthy even if attached node is deleted when restore was in progress.
Similar to https://github.com/longhorn/longhorn/issues/1355 and https://github.com/longhorn/longhorn/issues/1366

**To Reproduce**
1. Restore from a backup.
2. When restore is in progress, delete the attached node.
3. Volume stays in healthy state and shows 'restore in progress' forever.

**Expected behavior**
Volume should get faulted if attached node is deleted.

**Environment:**
 - Longhorn version: master-05-27-2020
 - Kubernetes version: v1.17.5
 - Node OS type and version: Ubuntu 18.04

**Comment by shuo-wu** [comment]
Are there any differences between this issue and #1355? If NO, I think we can close this one.

**Comment by khushboo-rancher** [comment]
This is similar case, here the change is only deletion of node. In #1355 node is powered down and in this one node is deleted. 
This issue is created to track deletion case separately. If we want to close this, we can add this scenario in #1355 and close it.

**Comment by shuo-wu** [comment]
I think node down and kube node deletion are the same for Longhorn. We can track this scenario in #1355 if you want to double-check it.

**Comment by yasker** [comment]
@khushboo-rancher can you add this case to #1355 ? As @shuo-wu said, power down and not coming back is very similar to removing a node in Longhorn's perspective. We can treat them as the same for now unless we found anything more later.

**Comment by khushboo-rancher** [comment]
Closing this issue as this scenario is added in #1355
