### ISSUE TITLE
[FEATURE] Aggregate the necessary Docker images

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1419]
quay.io has an outage today, which is blocking the deployment and development of Longhorn.

We should figure out the necessary images for Longhorn deployment, re-tag/re-publish them to `longhorn` in Docker Hub. This has two advantages:
1. Remove the extra dependency on different container image registry.
2. The users can easily pull all the necessary images to their air-gap environment.

Of course, Docker Hub is still the single point of failure. We might want to set up some way to mitigate that later, e.g. mirroring images to other registries.

Some examples from Rancher:
https://github.com/rancher/rancher/releases/download/v2.2.12/rancher-images.txt
https://github.com/rancher/rancher/releases/download/v2.2.12/rancher-save-images.sh
https://github.com/rancher/rancher/releases/download/v2.2.12/rancher-load-images.sh

**Comment by PhanLe1010** [comment]
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The PR is at [longhorn](https://github.com/longhorn/longhorn/pull/1579) , [manager]()

* [ ] ~Is the reproduce steps/test steps documented?~

* [x] Which areas/issues this PR might have potential impacts on?
Area: Longhorn installation using private registry, air-gap installation.

* [ ] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [ ] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~~

* [ ] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at ~~

* [ ] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at~~

* [ ] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~~

* [ ] ~~**if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at~~

**Comment by PhanLe1010** [comment]
**Reproduce/Testing:**

1. run script `scripts/longhorn-save-images.sh` in `longhorn` repo to pull and export images to a `tar` file
2. run script `scripts/longhorn-load-images.sh` in `longhorn` repo to load image from the `tar` file and push it to private registry
3. Install Longhorn using the private registry
4. Expected: successfully install.

**Comment by yasker** [comment]
We need to add a document for the end-user.

**Comment by yasker** [comment]
@PhanLe1010 I've tweaked the name and images of the list a bit. See https://github.com/longhorn/longhorn/pull/1592 . Can you update the document and test steps? Remember to include the option to not save the images to a tar.gz file.

Btw, I found if I run the script like this:
```
./scripts/load-images.sh test
```

It will just hang there without error out. We should fix this.

**Comment by PhanLe1010** [comment]
I got it. Fixing them

**Comment by meldafrawi** [comment]
Validation: **PASSED**
