### ISSUE TITLE
[BUG] Backup and Backup list pages take longer to load when backupstore is configured in google cloud

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1423]
**Describe the bug**
Backup and Backup list pages take longer to load when backupstore is configured in google cloud

**To Reproduce**

- Configure backupstore to be in google cloud
- Create some backups for volumes.
- Navigate to Backup page and Backup List page.
- There is a distinct delay in loading the contents when compared to when the backupstore is configured on S3

**Environment:**
 - Longhorn version: master - 05/27/2020
 - Kubernetes version: 1.17.5
 - Node OS type and version: 18.04

**Comment by yasker** [comment]
Not sure if there is anything we can do about it. Worth looking.

**Comment by ishankhare07** [comment]
May I know how we can set GCS as the backup target?

**Comment by innobead** [comment]
This will be tackled in #1761 and marked as duplicated.
