### ISSUE TITLE
[BUG] "Recurring Snapshot and Backup Schedule" section is big volume details page

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1426]
**Describe the bug**
"Recurring Snapshot and Backup Schedule" section is big volume details page

**To Reproduce**

- Create a volume, attach it to a node, and navigate to Volume detail page
- Scroll down to "Recurring Snapshot and Backup Schedule" section
- The section seems real big and when you scroll towards the real end , user can add new schedules
<img width="1653" alt="Screen Shot 2020-05-28 at 5 38 08 PM" src="https://user-images.githubusercontent.com/26032343/83208368-553c9500-a10a-11ea-90f2-b82faee44f9a.png">

**Expected behavior**
It should be smaller 

**Environment:**
 - Longhorn version: 1.0.0-rc3

**Comment by yasker** [comment]
@sowmyav27 This is more like a UI design issue. For example, one question is, if we make it smaller, what are we going to put in the empty space.

**Comment by sowmyav27** [comment]
**validated with ui tag: `wangsiye/longhorn-ui:af45a6d`**
Validation: **`PASSED`**

The "Recurring Snapshot and Backup Schedule" section is smaller and is as expected
<img width="1657" alt="Screen Shot 2020-05-28 at 8 31 23 PM" src="https://user-images.githubusercontent.com/26032343/83218252-950f7680-a122-11ea-9efb-f1f920b4f7ec.png">

**Comment by sowmyav27** [comment]
**Validated on latest master ui version : `23c813d` longhorn: `v1.0.0-rc3`**

Validation: **`PASSED`**

- The "Recurring Snapshot and Backup Schedule" section is smaller and is as expected
<img width="1670" alt="Screen Shot 2020-05-29 at 12 36 08 PM" src="https://user-images.githubusercontent.com/26032343/83298320-0db91600-a1a9-11ea-882b-d5abbe1f5bd7.png">
