### ISSUE TITLE
[BUG] Greyed "Revert" option on a snapshot is not disabled

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1427]
**Describe the bug**
Greyed "Revert" option on a snapshot is not disabled

**To Reproduce**

- Create a volume, attach it on the node.
- Go to the volume details page
- Click on `Create Snapshot`
- A snapshot gets created. Click on the snapshot. Revert option is `Greyed`.
- Click on revert.
- The below pop up is displayed

<img width="927" alt="Screen Shot 2020-05-28 at 6 42 32 PM" src="https://user-images.githubusercontent.com/26032343/83219765-07ce2100-a126-11ea-9b48-f896379bca17.png">

- Click on Okay.  Revert call is sent, and an error is seen on the UI
<img width="1330" alt="Screen Shot 2020-05-28 at 6 42 35 PM" src="https://user-images.githubusercontent.com/26032343/83219769-0ac91180-a126-11ea-9ff4-0f8bd4343ff6.png">

**Expected behavior**
The "Revert" is greyed, the option should NOT be clickable

**Environment:**
 - Longhorn version: 1.0.0-rc3

**Comment by smallteeths** [comment]
Now the design is changed to be clickable, but the pop-up window becomes as shown in the figure. Clicking ok will not request and will only close the pop-up window. @yasker @sowmyav27 
![Jietu20200529-133406](https://user-images.githubusercontent.com/27733391/83225109-989e0e80-a1b1-11ea-89e5-818a3c4b0a29.jpg)

**Comment by sowmyav27** [comment]
@yasker @smallteeths Do we need `Revert` option to be enabled? Because the tool tip on `Revert` shows this message. 
Do we need an additional message on pop up ? 
<img width="801" alt="Screen Shot 2020-05-28 at 11 07 23 PM" src="https://user-images.githubusercontent.com/26032343/83227044-21786400-a138-11ea-994f-7feb541d1aae.png">

**Comment by smallteeths** [comment]
The image has been updated to `wangsiye/longhorn-ui:6771633` . @sowmyav27 @yasker .
Modify to only disable without pop-up window.

**Comment by sowmyav27** [comment]
**Validated using UI tag: `wangsiye/longhorn-ui:6771633`**

Validation: **`PASSED`**

- Revert is Greyed out.
- No pop up seen or no requests are made when clicked on Revert

<img width="738" alt="Screen Shot 2020-05-29 at 7 03 51 AM" src="https://user-images.githubusercontent.com/26032343/83268538-a1272280-a17a-11ea-8bec-aa0b256e16dd.png">

**Comment by sowmyav27** [comment]
**Validated on latest master ui version : `23c813d` longhorn: `v1.0.0-rc3`**

Validation: **`PASSED`**

- Revert is Greyed out.
- No pop up seen or no requests are made when clicked on Revert
<img width="765" alt="Screen Shot 2020-05-29 at 12 31 14 PM" src="https://user-images.githubusercontent.com/26032343/83297902-502e2300-a1a8-11ea-9a5b-a935507eeb35.png">
