### ISSUE TITLE
[BUG] Scroll bar in the Snapshots section can be placed towards the end

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1428]
**Describe the bug**
Scroll bar in the Snapshots section can be placed towards the end

**To Reproduce**

- Create a volume, attach to a node (maintenance mode)
- Go to volume details section 
- Click on `Create Snapshot`
- Snapshot is created. Create a few more.
- Revert to a snapshot.
- The scroll bar in this section will be clearly visible. 

<img width="1646" alt="Screen Shot 2020-05-28 at 9 19 48 PM" src="https://user-images.githubusercontent.com/26032343/83221627-27b41380-a12b-11ea-8a03-15aef926654a.png">

**Expected behavior**
The scroll bar on the right can be placed on the right end.
<img width="1646" alt="Screen Shot 2020-05-28 at 9 19 48 PM" src="https://user-images.githubusercontent.com/26032343/83221696-5500c180-a12b-11ea-9a3e-6ecd8289cd6e.png">

**Environment:**
 - Longhorn version: 1.0.0-rc3

**Comment by khushboo-rancher** [comment]
Verified on master - 07-02-2020

Validation - **Passed**

The scroll bar is appearing towards the right of the page.
<img width="1515" alt="Screen Shot 2020-07-02 at 4 40 55 PM" src="https://user-images.githubusercontent.com/60111667/86417835-1b1f5f80-bc83-11ea-909d-94d0784dcade.png">
