### ISSUE TITLE
[doc] Add 'live upgrade not supported for iSCI volume' documentation.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1429]
Live upgrade is not supported for iSCSI volume' should be included in documentation.

**Comment by yasker** [comment]
Check https://staging.longhorn.io/docs/1.0.0/references/examples/#storageclass

**Comment by khushboo-rancher** [comment]
Looks good, should we close this id ?

**Comment by yasker** [comment]
@khushboo-rancher Yes you can close this.
