### ISSUE TITLE
[Question] Roadmap / release cycle

### ISSUE THREAD

**Issue by jeanluclariviere** [longhorn/longhorn#1430]
Hi Folks,
Very interested in the longhorn project - wondering what sort of release cycles you're working with, and when the roadmap for 1.0 GA and production level workloads is anticipated?

**Comment by jeanluclariviere** [comment]
That's fantastic, thanks! When can we expect 1.0 to be released, roughly?

**Comment by yasker** [comment]
We've just released v1.0.0. Give it a try. :)
