### ISSUE TITLE
Add Engine Integration test for backup block deletion

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#1433]
We need an engine integration test, that verifies the correct deletion of the backup blocks.

longhorn/longhorn#1431

**Comment by joshimoo** [comment]
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [x] Is the backend code merged?
The PR is at [here](https://github.com/longhorn/backupstore/pull/41)

* [x] Is the reproduce steps/test steps documented?

* [x] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~~

* [x] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at~~

* [x] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at~~

* [x] **if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is [here](https://github.com/longhorn/longhorn-engine/pull/498)

* [x] ~~**if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at~~

**Comment by yasker** [comment]
PR merged. Done.
