### ISSUE TITLE
Add e2e integration test for backup block deletion

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#1434]
We need an e2e integration test, that verifies the correct deletion of the backup blocks.
Have a look at the [manual test scenario](https://github.com/longhorn/longhorn-tests/wiki/Test-Scenarios-for-Backups-&-Restore#1326-backup-block-deletion-test) for an idea of what that should look like.

longhorn/longhorn#1431

Test skeleton is [here](https://github.com/longhorn/longhorn-tests/pull/348)

**Comment by yasker** [comment]
Assign to @joshimoo for now, until we have the test skeleton approved.

**Comment by joshimoo** [comment]
@yasker test skeleton merged https://github.com/longhorn/longhorn-tests/pull/348

**Comment by PhanLe1010** [comment]
Already implemented by Mohamed!
The original issue is longhorn/longhorn#1435
