### ISSUE TITLE
[FEATURE] Recurring backups and snapshots can be named different for easier identification

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1436]
**Is your feature request related to a problem? Please describe.**
The recurring backups and snapshots can be tagged with a better `name`/`id`/ `label` to identify them easier

Currently on `v1.0.0-rc3`
Backups have a label
<img width="799" alt="Screen Shot 2020-05-29 at 7 30 17 PM" src="https://user-images.githubusercontent.com/26032343/83317627-e3844a00-a1e2-11ea-90dd-2d94d7a150b4.png">

And the related snapshots have names:
<img width="1620" alt="Screen Shot 2020-05-29 at 7 30 52 PM" src="https://user-images.githubusercontent.com/26032343/83317640-ef700c00-a1e2-11ea-92df-c3bee6cae509.png">

We could name them better to identify that they are `recurring backups`

**Comment by innobead** [comment]
remove stale due to the incorrect exempt label
