### ISSUE TITLE
[BUG] wiki links are out of date

### ISSUE THREAD

**Issue by tedder** [longhorn/longhorn#1439]
**Describe the bug**
The links on the wiki point to longhorn/blob/master/docs/, which doesn't exist anymore.

For instance, this wiki page: https://github.com/longhorn/longhorn/wiki/Settings
Has many links to here, which is invalid: https://github.com/longhorn/longhorn/blob/master/docs/snapshot-backup.md

In reality, this is the proper link on github: https://github.com/longhorn/website/blob/master/content/docs/1.0.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
and on longhorn.io: https://longhorn.io/docs/1.0.0/snapshots-and-backups/backup-and-restore/set-backup-target/

The wiki isn't editable, even for PRs, as far as I know.

As a metaissue, there's no way to link to "latest" instead of "1.0.0".

**To Reproduce**
n/a

**Expected behavior**
n/a

**Log**
n/a

**Environment:**
n/a

**Additional context**
n/a

**Comment by yasker** [comment]
Thank you @tedder to point those out. A part of wiki's functionality has been replaced by https://longhorn.io/docs , so we no longer need to keep documentation in the wiki.

I've repurposed the wiki to be more developer orientation and cleaned up the obsolete contents. Let me know what do you think.

**Comment by tedder** [comment]
Looks great- thanks. Definitely good to have basic pointers in there now, and should keep other users from stumbling across old documentation.
