### ISSUE TITLE
UI: Live upgrade should be disabled for v1.0.0

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1441]
We should disable the upgrade button when the volume is attached for v1.0.0, to let the user know that only offline upgrade is supported.

**Comment by yasker** [comment]
We will retag `longhornio/longhorn-ui:v1.0.0` for this change

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI: `image: wangsiye/longhorn-ui:f661000`

Steps to test:
- Install Longhorn v0.8.1
- Create multiple volumes used by workload.
- Write data to volumes, and compute its checksum  **checksum#1**
- Upgrade Longhorn to v1.0.0
- While volume is in not in Detached state, `Upgrade Engine` button should be disabled, in both Volume page and Volume Details page (**PASSED**)
- While volume is in not in Detached state, `Upgrade Engine` batch operation button should be disabled.  (**PASSED**)
- Scale down the workload, volumes should be detached (**PASSED**)
- Upgrade Engine for volumes, in Volume Details page, `Engine Image` should be upgraded to `longhornio/longhorn-engine:v1.0.0`
- Scale up the workload back, volume should be `Attached`  (**PASSED**)
- Workload pods should be able do I/O operations to the directory volume is mounted to, and data checksum should match **checksum#1**  (**PASSED**)

**Comment by yasker** [comment]
Done
