### ISSUE TITLE
designating specific worker nodes as replicas

### ISSUE THREAD

**Issue by mshack70** [longhorn/longhorn#1444]
hello.

I am a little confused on how to properly designate certain worker nodes out of a pool to be used as longhorn replica nodes.

Reading the documentation, it refers to 'taint' worker nodes you want to use as replicas, then assign toleration to the Longhorn deployment so that it can run the instance manager pods on them (I think these are what manages replica state, could be wrong). 

For an example, if you have 6 worker nodes, but want 3 of them dedicated as replicas.  If you taint 3 of the 6, and assign the toleration, Longhorn still deploys to all 6 from what I see. (i'm using v0.8.1).  Is this how it is supposed to happen?  Also isn NoPrefer an allowable taint for this, or does it need to be NoSchedule or NoExecute?

It would be neat if I could instead label nodes with a tag such as 'longhorn-replica', and then the deployment would only allow the pods which manage the replicas to run on those nodes.  In my case I have a separate filesystem for /var/lib/longhorn on these worker nodes, and would still like to allow general workloads to be able to target them (or at least have that option).

**Comment by yasker** [comment]
@mshack70 Longhorn will still deploy to all of them since Longhorn engine needs to be run at other nodes to make sure the workload pod can access the volume.

You can disable the scheduling for the nodes that you don't want to have replicas, and remove any disks from them.

**Comment by mshack70** [comment]
@yasker thx, I see that options in Longhorn UI now edit->node , didnt see those options in 0.8.1.  Whats the difference , when editing a node in longhorn UI, of disable node scheduling option at top, vs at bottom there is an Enable/Disable scheduling?

**Comment by yasker** [comment]
One is node level, the other one is disk level (since Longhorn supports multiple disks per node).

**Comment by mshack70** [comment]
Ok, that makes sense, I only have 1 disk per node for longhorn so it wasnt obvious to me.  Thanks much.
