### ISSUE TITLE
About offline upgrade

### ISSUE THREAD

**Issue by mshack70** [longhorn/longhorn#1445]
I'm looking at the upgrade instructions for 0.8.1 to 1.0.0, and as a pre-req it looks to require detaching all longhorn volumes in use prior to the upgrade.  This is very disruptive imo, but since this is moving from a beta version to GA maybe this is a one time requirement.  Just to be sure though, are there plans in future upgrades post 1.0 to allow for upgrading without the need to detach or affect any longhorn volumes in use?

**Comment by yasker** [comment]
Hi @mshack70 

Our goal is the future upgrade shouldn't involve offline upgrade. We're still stabilizing the live upgrade framework, so it might change during the major releases (e.g. v1.0.0 to v1.1.0), but it should be good for patch version upgrade (e.g. v1.0.0 to v1.0.1). We will definitely try not to disrupt the live upgrade path even for the major releases.

**Comment by mshack70** [comment]
Ok thanks, yeah I think it would be hard to use this for production if we have to detach PV's from applications for upgrades.  Hopefully this should be a high priority goal for future releases.  Thanks for the response.

**Comment by yasker** [comment]
In fact it's already a top priority item. The design guarantees that no function changes should be made to the live upgrade framework, it's hard to predict if there will be anymore bugs.
