### ISSUE TITLE
allow to edit multiple nodes

### ISSUE THREAD

**Issue by mshack70** [longhorn/longhorn#1447]
**Describe the solution you'd like**
Currently in v1.0.0 you can select multiple nodes, but only make edit changes on one at at time.  It would be a nice feature to allow one to checkmark multiple nodes, and make the same Edit change on all selected nodes.

**Comment by smallteeths** [comment]
Does this need to be discussed, and which ones can be modified uniformly? Now some editable content, such as tags, are not very good for unified modification. @yasker

**Comment by yasker** [comment]
@smallteeths We can start with enable/disable scheduling. We indeed need to think about the node tags. @mshack70 did you refer to the enable/disable scheduling or you refer to the node tags as well?

**Comment by mshack70** [comment]
I was initially just thinking that node scheduling, or disk scheduling.  But it might also be nice to allow for labels to be set on all, or even the disk path to be set to all (if doing something other than the standard location), vs. having to click on each one.

**Comment by yasker** [comment]
@mshack70 it will quite some redesign to handle the disk level objects because a node can have multiple disks. Current set node level scheduling is straightforward, but tags are different because there can be existing tags on the node, should we expect to replace them or just add new tags? How about deletion? This will require some thoughts.

**Comment by yasker** [comment]
After more communication with @mshack70 , we think allow batch operation to enable/disable node scheduling is a good first step.

**Comment by khushboo-rancher** [comment]
Verified on master - ```97a869e``` - 07-09-2020

Validation - **Failed**

The option ```node scheduling enable/disable``` are always highlighted. We Should disable the radio button when it is not applicable on the selection.
Examples:
1. Select all the disabled nodes - ```Disable radio button``` should be disabled.
2. Select all the enabled nodes - ```Enable radio button``` should be disabled.
3. Select combination of disable and enable nodes - ```Edit button``` should be disabled

**Comment by khushboo-rancher** [comment]
Validated on Master - 07-13-2020

Validation - **Passed**

**Scenarios Tested**:
1. Select all nodes - enable nodes
2. Select all nodes - disabled nodes
3. Select combination of enabled and disabled nodes.
4. Select combination of enabled and down nodes.
5. Select combination of down and disabled nodes.
