### ISSUE TITLE
[BUG]Volume should be Unknown if the attached node is down

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1451]
**Describe the bug**
As we discussed in #1355 and #1366, it's better to mark the volume as `Unknown` if the attached node is down.

**To Reproduce**
1. Create and attach a volume.
2. Power off the related VM of the attached node.
3. Wait for the Longhorn node down
4. Check the volume health state, it's still `Healthy`

**Expected behavior**
The volume should be `Unknown` after the node down

**Environment:**
 - Longhorn version: v1.0.0
 - Kubernetes version: v1.17

**Additional context**

**Comment by shuo-wu** [comment]
We may need a special icon for the volumes on the down nodes.

The basic idea/draft design for the UI part (this part may get updated  later):
1. Add an icon for the volume if the `volume.state == attached && volume.robustness == unknown`
2. Add hover for the icon to inform the users: `The volume attached node may be down.`

**Comment by shuo-wu** [comment]
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged?
The PR is at https://github.com/longhorn/longhorn-manager/pull/595

* [x] Is the reproduce steps/test steps documented?
The test steps are the same as the reproduce steps.

* [x] ~~**If the fix introduces the code for backward compatibility** Has a separate issue been filed with the label `release/obsolete-compatibility`?~~

* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at

* [x] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?~~

* [x] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?~~

* [x] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?~~

* [x]~~ **if labeled: require/manual-test-plan** Has the manual test plan been documented?~~

##Additional Checklist:
* [ ] **check regression** Need to check the node down cases for regular volumes. (We can check DR volumes in #1366 and restore volumes in #1355)
* [ ] **check negative test plan** May need to check the node down tests.

**Comment by shuo-wu** [comment]
@yasker Can you check what we need to do for the UI part?

**Comment by yasker** [comment]
@shuo-wu what's your opinion?

**Comment by shuo-wu** [comment]
I had put my idea in the above comment. I am not sure if we need to so many special icons for volumes.

**Comment by yasker** [comment]
> I had put my idea in the above comment. I am not sure if we need to so many special icons for volumes.

Sorry, missed that part.

In fact we should know almost for sure if the attached node is down or not? Can we reflect that information in the UI as well? We can either have UI retrieve the node information or add it as a condition etc in the volume to indicate problem with the attached node.

**Comment by shuo-wu** [comment]
Yeah. We can check the attached node if the volume becomes `Unknown`. 
But what if the node is running and the volume is `Unknown`? (Maybe temporarily `Unknown`. I am not sure if there is such a weird case.) How about showing the message `Longhorn is updating the volume` for this case?

**Comment by yasker** [comment]
Regarding `Add an icon for the volume if the volume.state == attached && volume.robustness == unknown`, it can happen in the normal procedure. When the volume is just attached and the engine wasn't updated yet, this condition will be satisfied as well. So we need to use the node condition as well.

`Longhorn is updating the volume` is too generic. Previous if the volume is attached but robustness unknown, I think we will just show the volume as `attached`.

I am still debating if we should add a condition to the volume to show the attached node condition. Maybe we can do that later. For now, we can use the combination of the node condition and the volume robustness `unknown` as well as `attached` to decide when to show the warning sign.

**Comment by shuo-wu** [comment]
OK. I have updated the UI design.

**Comment by shuo-wu** [comment]
The UI fix LGTM except for the volume detail page. 
I think we can show the same icon and tooltips in the volume detail page. @smallteeths 

The tests for the UI part:

Test1:
1. Create and attach a volume.
2. Power off the attached node.
3. Wait for the UI showing the icon then check the tooltips.
4. Power on the node. 
5. Wait for the icon disappearing and the volume reattaching.

Test2:
1. Create and attach a volume.
2. Delete the related instance manager pod.
3. There is no `node down` icon and the tooltips for the volume.
4. Wait for the volume reattaching. Then the volume becomes `Healthy`.

**Comment by khushboo-rancher** [comment]
Verified on master - 07-01-2020

UI shows the icon that node is down.
<img width="1298" alt="Screen Shot 2020-07-01 at 11 59 06 AM" src="https://user-images.githubusercontent.com/60111667/86284676-28abeb00-bb98-11ea-8c93-56ef6f1ea588.png">

But I observed issue regarding volume getting stuck in attaching/detaching state.

Steps to repro:
1. Create a volume and attach to a pod. (In my set up ```vol-2``` got attached to ```khush-test-wk1```)
2. Restore a backup. (```vol-restore-4``` restore started on ```khush-test-wk2```)
3. While restore was in progress, disconnect the network of the attached node for 100. (In my set up I disconnected ```khush-test-wk2 and khush-test-wk3``` using script 
[network_down.sh.zip](https://github.com/longhorn/longhorn/files/4860137/network_down.sh.zip))
4. Volume from step 1 got stuck in detaching state and step 2 got stuck in attaching state.
<img width="1490" alt="Screen Shot 2020-07-01 at 12 47 12 PM" src="https://user-images.githubusercontent.com/60111667/86285263-239b6b80-bb99-11ea-8a2f-f16dc0aa2bc2.png">

5. Create a new volume ```vol-3```. (All the nodes are up at this point of time)

6. ```vol-3``` also got stuck in detaching state.

**logs:**
[longhorn-support-bundle_63d5b4f2-ebc5-4af5-a71e-b2251f7684f1_2020-07-01T19-36-16Z.zip](https://github.com/longhorn/longhorn/files/4860135/longhorn-support-bundle_63d5b4f2-ebc5-4af5-a71e-b2251f7684f1_2020-07-01T19-36-16Z.zip)

**Note**:
Timing of all these activity is of around UTC 19:25:00 onwards.

**Comment by yasker** [comment]
@khushboo-rancher You meant the validation failed? Can you add the validation result in bold font at the beginning of the comment?

**Comment by yasker** [comment]
The issue of the reopen is due to #1545

**Comment by khushboo-rancher** [comment]
Verified on Master - 07-10-2020

Validation - **Passed**

The attached node goes shows ```The attached Node is down``` when the node is powered off/disconnected. 
Once the node is powered on, the state becomes healthy.
