### ISSUE TITLE
Longhorn helm chart is not included in the Rancher repo

### ISSUE THREAD

**Issue by jackivanov** [longhorn/longhorn#1453]
Hello,

Can you publish the helm chart to the rancher (or any other) repo as suggested in #445

```bash
$ helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
"rancher-stable" has been added to your repositories
$ helm search repo rancher
NAME                  	CHART VERSION	APP VERSION	DESCRIPTION
rancher-stable/rancher	2.4.4        	v2.4.4     	Install Rancher Server to manage Kubernetes clu...
$ helm search repo longhorn
No results found
```

**Comment by yasker** [comment]
@jackivanov we're working on adding Longhorn into the standard helm hub #1043 .

**Comment by jackivanov** [comment]
@yasker It's been quite a while. Any progress on this? Is there anything I can help you with?

**Comment by yasker** [comment]
Thanks for the offering of help @jackivanov ! we just started working on it after GA. It should be done soon.

**Comment by yasker** [comment]
@jackivanov Forgot to update you. Now Longhorn chart is available at https://charts.longhorn.io/ as a Helm Repo.
