### ISSUE TITLE
[BUG] Update README in Longhorn Rancher chart to warn users against the downgrade

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1454]
https://github.com/rancher/rancher/issues/27423

Rancher UI cannot prevent user from downgrading Longhorn from e.g. v1.0.0 to v0.8.1. We should update the README in `rancher/charts` to warn user against it.

**Comment by yasker** [comment]
Hold on for this one. We're discussing what's the right thing to do.

**Comment by khushboo-rancher** [comment]
We should make the change in v0.1.0/README.md too.

**Comment by yasker** [comment]
> We should make the change in v0.1.0/README.md too.

Hmm, I am not sure why.

**Comment by khushboo-rancher** [comment]
Change in v0.1.0/README.md is not required - https://github.com/rancher/rancher/issues/27423#issuecomment-639166740
Verified https://github.com/rancher/rancher/issues/27423 on master-3145-head. Warning appears for v1.0.0 as below. 
<img width="1362" alt="Screen Shot 2020-06-04 at 3 34 00 PM" src="https://user-images.githubusercontent.com/60111667/83820166-bf13ec00-a680-11ea-8d50-9146e17e90b1.png">
