### ISSUE TITLE
[FEATURE] Backup/Restore Longhorn System

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1455]
Rancher has introduced ETCD snapshot/restore, but [we found that](#1969) it doesn't work well with Longhorn. More importantly, there is currently no recommended way to backup the Longhorn system itself. It can be useful for the following scenarios:
1. Rollback in the case of an upgrade failure.
2. Recreate/replicate the cluster

In general, we can dump the related CRDs and rollback to them if something went wrong.

It requires some designs to offer the best experience to the end user.

REF: https://github.com/longhorn/longhorn/pull/1648

**Comment by innobead** [comment]
This is what we have now for backup/restore longhorn.
- https://longhorn.io/docs/1.3.0/advanced-resources/cluster-restore/restore-to-a-cluster-contains-data-using-rancher-snapshot/
- https://longhorn.io/docs/1.3.0/advanced-resources/cluster-restore/restore-to-a-new-cluster-using-velero/

**Comment by c3y1huang** [comment]
Note: @FrankYang0529 is currently working on backing image backup and restore.
1. Add backup cmd to the backing image manager to upload to the backup targets.
2. Add fields `lastBackingImage`... to the related CR

For this issue, we can leverage the field `lastBackingImage` for restoring the rollout.

Relate issue https://github.com/harvester/harvester/issues/2237

**Comment by c3y1huang** [comment]
Backing image backup/restore, ref https://github.com/longhorn/longhorn/pull/4385.

**Comment by khushboo-rancher** [comment]
Testing in progress, will update the result here.
