### ISSUE TITLE
[BUG] zombie processes 

### ISSUE THREAD

**Issue by wopl** [longhorn/longhorn#1457]
**Describe the bug**
Longhorn manager does create a lot of zombie processes (200 or more per day)

**To Reproduce**
1. Installed version 1.0.0 (but also occurs on 0.8.1)

**Expected behavior**
no zombie processes - of course

**Log**
`2020-06-04T21:07:57.716716931+02:00 time="2020-06-04T19:07:57Z" level=debug msg="Failed to check for the latest upgrade: Post \"https://longhorn-upgrade-responder.rancher.io/v1/checkupgrade\": dial tcp: lookup longhorn-upgrade-responder.rancher.io on 10.43.0.10:53: server misbehaving"
2020-06-04T21:08:23.69727142+02:00 time="2020-06-04T19:08:23Z" level=debug msg="Skip rebuilding for volume pvc-fc1a6e3e-dfe8-45e7-8ef1-805a400d3f25 because there is rebuilding in process"
2020-06-04T21:08:23.757795868+02:00 time="2020-06-04T19:08:23Z" level=debug msg="Skip rebuilding for volume pvc-fc1a6e3e-dfe8-45e7-8ef1-805a400d3f25 because there is rebuilding in process"
2020-06-04T21:08:53.697197025+02:00 time="2020-06-04T19:08:53Z" level=debug msg="Skip rebuilding for volume pvc-fc1a6e3e-dfe8-45e7-8ef1-805a400d3f25 because there is rebuilding in process"
2020-06-04T21:08:53.758270386+02:00 time="2020-06-04T19:08:53Z" level=debug msg="Skip rebuilding for volume pvc-fc1a6e3e-dfe8-45e7-8ef1-805a400d3f25 because there is rebuilding in process"
2020-06-04T21:08:57.716166046+02:00 time="2020-06-04T19:08:57Z" level=warning msg="backup store monitor: failed to list backup volumes in nfs://5.35.255.242:/aryalonghorn: error listing backup volumes: Timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.0.0/longhorn [backup ls --volume-only nfs://5.35.255.242:/aryalonghorn], output , stderr, , error <nil>"
2020-06-04T21:09:23.698234644+02:00 time="2020-06-04T19:09:23Z" level=debug msg="Skip rebuilding for volume pvc-fc1a6e3e-dfe8-45e7-8ef1-805a400d3f25 because there is rebuilding in process"`

**Environment:**
 - Longhorn version: 1.0.0 (also saw on 0.8.1)
 - Kubernetes version: v1.18.2+k3s1
 - Node OS type and version: Ubuntu 18.04.4 LTS

**Additional context**
I do have another problem with web-socket protocol (discussed on separate issue report) #1442. Not sure there is any coincidence.

Remark to the logfile above: yes, there is some rebuilding going on. But not my main-topic here.

**Comment by yasker** [comment]
Sounds like longhorn manager is leaving zombie processes. We should be able to use `tini` to properly reap them.

**Comment by wopl** [comment]
There seems to be a coincidence to the issue #1442 filed by me as well.
Not sure yet, but I did have a lot of zombies, as long as the websocket problem was not solved (solved now by Ingress adding a Header). At this point I am struggling with NFS backup targets and as long as the target is not reachable, I see Zombies again. In both cases (websocket, backup) we ran into communication timeouts. Could those timeouts be a reason for dropping Zombie processes?

**Comment by ttpcodes** [comment]
I've reproduced the other bug you filed regarding the `WebSocket` problem, and while I did encounter the connection issues you described in the other issue, I did not see zombies produced as a result of the issue.

Do you know specifically what process is having zombies created of it? Is it `rpc.statd` like what I encountered above, or something else?

**Comment by makdmi** [comment]
On a node with 2 healthy and attached volumes i get this output from `ps axu --forest`

root      8194  0.0  0.0 109108  8092 ?        Sl   Jun08  14:09  \_ containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/27d2165c96775a4bea62d3771ae408804ac2a45f58778c0e73e5f7f704dde37d -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
root      8236  0.0  0.0   4520   764 ?        Ss   Jun08   0:30  |   \_ /tini -- engine-manager --debug daemon --listen 0.0.0.0:8500
root      8283  0.3  0.0 1527036 15436 ?       Sl   Jun08  79:47  |       \_ longhorn-instance-manager --debug daemon --listen 0.0.0.0:8500
root      8288  0.0  0.0 2356244 9424 ?        Sl   Jun08   1:37  |           \_ tgtd -f
root      8289  0.0  0.0   4536   768 ?        S    Jun08   0:00  |           \_ tee /var/log/tgtd.log
root      2301  0.2  0.3 1229224 54856 ?       Sl   Jun11  49:48  |           \_ /engine-binaries/longhornio-longhorn-engine-v1.0.0/longhorn controller pvc-1329de66-21e7-48c6-9d6c-4e5c0f5e5437 --frontend tgt-blockdev --replica tcp://10.42.0.154:10000 --replica tcp://10.42.1.11:10000 --replica tcp://10.42.2.121:10000 --listen 0.0.0.0:10000
root      2318  0.0  0.0      0     0 ?        Z    Jun11   0:00  |           |   \_ [sleep] <defunct>
root      2393  0.0  0.0      0     0 ?        Z    Jun11   0:00  |           |   \_ [sleep] <defunct>
root     30486  0.2  0.1 1081760 19652 ?       Sl   11:16   0:01  |           \_ /engine-binaries/longhornio-longhorn-engine-v1.0.0/longhorn controller pvc-a7d1952e-c28a-4e63-b1ae-ee5ee9d2fbb8 --frontend tgt-blockdev --replica tcp://10.42.0.154:10015 --replica tcp://10.42.1.11:10015 --replica tcp://10.42.2.121:10015 --listen 0.0.0.0:10001
root     30520  0.0  0.0      0     0 ?        Z    11:16   0:00  |               \_ [sleep] <defunct>
root     30648  0.0  0.0      0     0 ?        Z    11:16   0:00  |               \_ [sleep] <defunct>

2 zombie processe for each volumen.

I think not this is desired behavior.

**Comment by ttpcodes** [comment]
The `rpc.statd` zombies that result from NFSv3 fallback should no longer appear, as longhorn/backupstore#44 and longhorn/backupstore#47 should prevent usage of NFSv3 backup stores.

The zombies being created on startup of the `longhorn-engine` should no longer appear as a result of longhorn/nsfilelock#1. This change should be introduced into `longhorn-engine` as a result of `vendor/` being updated in longhorn/longhorn-engine#520.

**Comment by steffeneichler** [comment]
Hi,
when will the problem in longhorn-engine be fixed? It's still present in v1.0.2 .

`Zombie-PID = 29034
Zombies Parent PID = 28858
root     28858 12252  0 Oct15 ?        00:05:43 /engine-binaries/longhornio-longhorn-engine-v1.0.2/longhorn controller pvc-be7f6740-3765-4171-b20b-f72adda8f8b5 --frontend tgt-blockdev --replica tcp://10.42.12.26:10030 --replica tcp://10.42.14.30:10045 --replica tcp://10.42.10.66:10030 --listen 0.0.0.0:10001
root     28899 28858  0 Oct15 ?        00:00:00 [sleep] <defunct>
root     29034 28858  0 Oct15 ?        00:00:00 [sleep] <defunct>`

**Comment by yfoelling** [comment]
Is there any news on this issue? 

Im affected too on 1.0.201 installed via Rancher Apps

**Comment by yfoelling** [comment]
It even persisists after reboot

```
root       8011  0.1  0.0 110132  6696 ?        Sl   08:30   0:00  \_ containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/0d8dd7f29b64223631
root       8038  0.0  0.0   4520   816 ?        Ss   08:30   0:00  |   \_ /tini -- engine-manager --debug daemon --listen 0.0.0.0:8500
root       8061  0.4  0.0 1970196 16376 ?       Sl   08:30   0:02  |       \_ longhorn-instance-manager --debug daemon --listen 0.0.0.0:8500
root       8067  0.6  0.0 4009124 7852 ?        Sl   08:30   0:03  |           \_ tgtd -f
root       8068  0.0  0.0   4536   772 ?        S    08:30   0:00  |           \_ tee /var/log/tgtd.log
root      10441  1.7  0.0 1672460 26484 ?       Sl   08:32   0:08  |           \_ /engine-binaries/rancher-longhornio-longhorn-engine-v1.0.2/longhorn controller pvc-a6930df6-bdd1-4842-8
root      10457  0.0  0.0      0     0 ?        Z    08:32   0:00  |           |   \_ [sleep] <defunct>
root      10590  0.0  0.0      0     0 ?        Z    08:32   0:00  |           |   \_ [sleep] <defunct>
root      10688  1.7  0.0 1672716 21288 ?       Sl   08:32   0:08  |           \_ /engine-binaries/rancher-longhornio-longhorn-engine-v1.0.2/longhorn controller pvc-2bca077d-7843-4953-9
root      10712  0.0  0.0      0     0 ?        Z    08:32   0:00  |           |   \_ [sleep] <defunct>
root      10824  0.0  0.0      0     0 ?        Z    08:32   0:00  |           |   \_ [sleep] <defunct>
root      10730  0.6  0.0 1598728 18080 ?       Sl   08:32   0:03  |           \_ /engine-binaries/rancher-longhornio-longhorn-engine-v1.0.2/longhorn controller pvc-25ece132-d814-4d71-8
root      10754  0.0  0.0      0     0 ?        Z    08:32   0:00  |               \_ [sleep] <defunct>
root      10893  0.0  0.0      0     0 ?        Z    08:32   0:00  |               \_ [sleep] <defunct>

```

**Comment by yasker** [comment]
@meldafrawi can you try if you can reproduce this issue in v1.0.2? Also in v1.1.0 as well.

**Comment by meldafrawi** [comment]
I was able to reproduce it on `v1.0.2`, however not on `v1.1.0`

Environment:
- Longhorn version: 1.0.2  && 
- Kubernetes version: v1.18.2+k3s1
- Node OS type and version: Ubuntu 18.04.4 LTS

Reproduce steps:
1- Install Longhorn v1.0.2
2- Create statefulset using https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml
3- Scale up the satefulset to `10`
4- Wait for all volumes to be in attached state
5- Scale down the statefulset to `0`
6- Scale up the satefulset to `10` again
7- `ssh` to worker nodes, and look for zombie processes using `$ ps aux | grep -i defunc | grep -v grep`

**Comment by yasker** [comment]
@yfoelling @steffeneichler @makdmi Do you still have issues with Longhorn v1.1.0?

**Comment by makdmi** [comment]
I upgraded to 1.1.0 yesterday from 1.0.2 on the same setup as earlier and no Zombie processes. Thanks

**Comment by yfoelling** [comment]
i upgraded over a week ago and no issues so far!
It seems to be fixed. Thanks for your fast fix. :-)

**Comment by yasker** [comment]
Since we cannot reproduce the issue now in v1.1.0, consider it fixed.
