### ISSUE TITLE
longhorn volume recovery issue?

### ISSUE THREAD

**Issue by mshack70** [longhorn/longhorn#1458]
**Describe the bug**
I'm doing some simple testing with 1.0.  I have designated 3 worker nodes as replicas, remaining worker nodes for normal workloads.  After creating a volume, and installing an application using this volume, did some disaster type test.  

-  I stopped docker on the 1st replica worker, app still had access to volume as expected (degraded)
- I stopped docker on 2nd replica worker, app has access to volume still (degraded)
- Finally stop docker on 3rd replica worker, app looses access to volume as expected.

Waited for the pvc in longhorn UI to show all nodes are failed.  Then start docker backup on
one of the replicas.

The PV though still says all replica's are stopped when the node goes from failed to normal 'schedulable' state.

**Expected behavior**
Is  it expected that Longhorn should be able to autorecover for this?

What is the normal recovery option if not?

**Environment:**
 - Longhorn version: 1.0.0
 - Kubernetes version: 1.17
 - Node OS type and version: centos 7.7

**Additional context**

**Comment by mshack70** [comment]
I started docker back on the other 2 nodes, and the volume started to recover.

Since I was staggering the docker stop's on these nodes, the primary replica owner changed.  It seems that only one of these 3 nodes was considered to be a true owner of the replica.

I'm a bit concerned on what to do if all 3 replica nodes crash at same time, or lets say only 2 of the 3 come back and the one which is down was considered to be the last known replica (even though the other 2 may have near full state of the volume).

I'm still getting an understanding of failure modes here and what to expect so any insight appreciated.

**Comment by yasker** [comment]
Where is the volume attached to? Once you get the docker on the attached node up, Longhorn should automatically start rebuilding (if it's allowed). Longhorn treats all replicas equally. The workload doesn't need to be in the same node that has a replica. But the workload needs to be up for Longhorn volume to be attached, then start the rebuild process.

Also, the failed replica will be automatically removed after `staleReplicaTimeout`.

**Comment by mshack70** [comment]
hi Sheng.  So in my case, the replicas were on nodes 1,2,3 , my pod which was mounting the pv was on node4.  only node1,2,3 are allowed to have replicas in my test.  Docker was never restarted on node4, only on node1,2,3.

**Comment by joshimoo** [comment]
> When all 3 nodes are back up, all 3 replicas are on one of the 3 longhorn nodes.

If I understood correctly you are saying all 3 replicas ended up on node x?
Could you share what your [replica-node-level-soft-anti-affinity](https://longhorn.io/docs/1.0.0/references/settings/#replica-node-level-soft-anti-affinity) setting is set to?

**Comment by yasker** [comment]
@mshack70 When all the replica are down, Longhorn will try to auto salvage and re-attach the volume. See https://longhorn.io/docs/1.0.0/high-availability/recover-volume/ . After you bring back the docker on the first node, did you see the volume start to reattach in the Longhorn UI? It might take a moment but if the auto-salvage option is enabled, that should happen.

**Comment by mshack70** [comment]
Yes when all 3 replica nodes were back up, only one of the 3 nodes had all 3 replicas.

 replica-node-level-soft-anti-affinity was enabled

When bringing up docker on the 1st replica node, I waited over a minute and the volume did not attach or recover..., not until the the other 2 nodes docker start did the volume recover, and all replicas were on node2.

**Comment by yasker** [comment]
What happened is, Longhorn assumes the last replica you've shut down contains the latest data of the volume, so unless the last replica is somehow able to be started (e.g. enable docker on the node), the volume won't be recovered since we cannot expect the user to write some data into the volume but lost the data when volume comes back (since other two replicas might not contain stale data).

Also, on v1.0.0, we've disabled node level anti-affinity by default, so the replicas wouldn't end up on the same node.

**Comment by mshack70** [comment]
What would happen if all the replica nodes lost network connectivity at same time, and then recovered later?

**Comment by yasker** [comment]
if all the replica lost the network at the same time, auto salvage will bring them back and trying to attach the volume to the last known node.

For the best practice, `node level soft anti-affinity` should be disabled. It's the default value in v1.0.0.
