### ISSUE TITLE
test: move manual test from longhorn-test wiki to the longhorn-test code

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1460]
The manual test before the release is currently documented at https://github.com/longhorn/longhorn-tests/wiki . But the wiki is hard for the outside contributors. We want to move it to https://github.com/longhorn/longhorn-tests code base, ideally, also generate the website along with [automation test cases](https://longhorn.github.io/longhorn-tests/) to make it easier to read.

**Comment by ttpcodes** [comment]
## Pre-merged Checklist
* [X] Does the PR include the explanation for the fix or the feature?

* [X] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The PR is at longhorn/longhorn-tests#367.

* [X] Is the reproduce steps/test steps documented?

* [X] Which areas/issues this PR might have potential impacts on?
Areas: pm
Issues: #1460

* [X] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?~~

* [X] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~

* [X] **if labeled: require/doc** Has the necessary document PR submitted or merged?~~

* [X] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?~~

* [X] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?~~

* [X] ~~**if labeled: require/manual-test-plan** Has the manual test plan been documented?~~

**Comment by ttpcodes** [comment]
The new website for hosting the integration test and manual test documentation can be viewed [here](https://longhorn.github.io/longhorn-tests).

**Comment by yasker** [comment]
Done
