### ISSUE TITLE
discuss: should we code live upgrade logic in the backend or not

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1461]
It's more of a release decision.

Also, live upgrade works even for the version that we don't claim to support live upgrade (e.g. v0.8.1 to v1.0.0), as long as the API is compatible. The only problem is the extra engine instance managers that might get left over. Should we allow it or not? It will still reduce the workload downtime, even user need to have some old version of instance manager running from time to time. 

@shuo-wu ?

**Comment by runningman84** [comment]
I have updated everything using helm upgrades for quite some time without big problems. After the helm release was updated I updated the engine for each volume in the gui.

**Comment by shuo-wu** [comment]
1. IMO, the live upgrade should be supported by default if we don’t claim the disabling.
2. I think you are concerning the issue `an extra set of (old) engine instance manager running after the live upgrade`. Actually we already make [a decision](https://github.com/longhorn/longhorn-manager/pull/499) for it: When we refactor the live upgrade, I want to support live upgrade as long as it’s possible and we don’t want to retain too many instance manager pods. Then we decide to add the instance-manager auto cleanup feature as the compromise. Hence this result should be what we expect and what we can accept.

**Comment by yasker** [comment]
@shuo-wu sounds good. We shouldn't explicitly disable it then.

And thanks for the input @runningman84 . We will support live upgrade as much as we can in the future releases.
