### ISSUE TITLE
[Question] get issue error: listing backups: setting backup-target is empty

### ISSUE THREAD

**Issue by tscswcn** [longhorn/longhorn#1468]
[Question] get issue error: listing backups: setting backup-target is empty

how to fix

**Comment by yasker** [comment]
Do you see it on all the pages or just `Backup` page? The later is expected since without `backup target` there is no backup to be seen.

**Comment by joshimoo** [comment]
If you are trying to setup a backup target have a look at the documentation [here](https://longhorn.io/docs/0.8.1/snapshots-and-backups/backup-and-restore/set-backup-target/)
