### ISSUE TITLE
[BUG]Set up recurring jobs backup

### ISSUE THREAD

**Issue by modogo2000** [longhorn/longhorn#1469]
**Describe the bug**
I try to initialise the recurring backup and snapshot and I have this message error when edit the storage class:

storageclasses.storage.k8s.io "longhorn" was not valid:
 parameters: Forbidden: updates to parameters are forbidden.

this is the edit of the storageclass : 

allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2020-06-07T06:06:45Z"
  labels:
    io.cattle.field/appId: longhorn-system
  name: longhorn
  resourceVersion: "314741"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/longhorn
  uid: f0d4471b-44b7-478c-8919-1aa230f14172
parameters:
  baseImage: ""
  fromBackup: ""
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  recurringJobs: '[{"name":"snap", "task":"snapshot", "cron":"*/1 * * * *", "retain":1},{"name":"backup", "task":"backup", "cron":"*/2 * * * *", "retain":1}]'
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate

**To Reproduce**
1. kubectl edit storageclass longhorn
2. add the settings 
recurringJobs: '[{"name":"snap", "task":"snapshot", "cron":"*/1 * * * *", "retain":1},
                   {"name":"backup", "task":"backup", "cron":"*/2 * * * *", "retain":1}]'
3. try to save

**Expected behavior**
Add the parameters for the recurring backup

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

**Environment:**
 - Longhorn version: v1.0
 - Kubernetes version: v1.17.6
 - Node OS type and version: Ubuntu 18.04.4 LTS

**Comment by khushboo-rancher** [comment]
@modogo2000 Kubernetes doesn't allow editing of parameters of Storage Class, you can always create a new one with required parameters.

**Comment by modogo2000** [comment]
Hi,

Thank you for the information. I recreate the storage class the issue is solved.

May be add a comment or give an option in the catalog to activate the recurring backup will be interressting.
