### ISSUE TITLE
[FEATURE]Native RWX with Longhorn volume

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1470]
We want to support RWX on Longhorn. Probably using NFS protocol in someway.

**Comment by SoutisV** [comment]
With the current nfs-provisioner it takes around 90sec for the failover. Would be supported in v1.1.0 a HA setup for RWX?

**Comment by yasker** [comment]
@SoutisV Unfortunately it's not going to be HA RWX. It's very hard to do zero downtime HA RWX with Longhorn which is designed to be a distributed block storage system instead of a distributed filesystem.

**Comment by zbialik** [comment]
Is there really no plan to make the longhorn-nfs-provisioner available in a HA setup? Having a single point of failure for a shared persistent volume for my RWX workloads is not ideal. A 90 second fail over is a deal breaker. 

If its the longhorn storage-class that is limiting the longhorn-nfs-provisioner from replicating the storage quick enough for zero downtime, could another storage-class be leveraged? I know that the Service ClusterIP gets hardcoded and the docs say it must be linked to a single pod, but is there any reason why this Service ClusterIP couldn't front 2 or 3 pods?

**Comment by yasker** [comment]
@zbialik It's complicated to get a HA NFS working for a block storage system like Longhorn. The cluster IP can front multiple Pods, but those Pods must have the same data to keep it consistent across the board. Also, each NFS server has an internal state machine that needs to keep consistent across the whole setup. And in the case of losing one NFS server, we need to handle the traffic on the fly as well to prevent data corruption.

We've spent a large amount of effort to try to piece together everything, but unfortunately, we still face technical difficulties to get it right in this release. We will investigate more after the v1.1.0 release.

**Comment by zbialik** [comment]
Thanks for the explanation!

**Comment by khushboo-rancher** [comment]
Verified the RWX feature with Longhorn v1.1.0-rc1

Validation - **Pass**

Executed test cases from longhorn/longhorn-tests#496.

**Comment by khushboo-rancher** [comment]
Closing this as the validation is completed.

**Comment by taxilian** [comment]
The documentation is still pointing to old information; I'm currently trying to figure out how to do this, hoping the lack of docs means to just use the flag?

**Comment by yardenshoham** [comment]
@taxilian it looks updated to me. https://longhorn.io/docs/1.1.0/advanced-resources/rwx-workloads/

**Comment by taxilian** [comment]
Huh; maybe I was looking at an old version of the docs and didn't realize
it. Thanks for the link!

Richard
