### ISSUE TITLE
[BUG] There is a delay in deleting backup.cfg on backup store.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1471]
**Describe the bug**
There is a delay in deleting individual backup on backup store. On clicking delete backup from backup page in longhorn, it still continues to show backup available to perform action on it.

**To Reproduce**
**Scenario 1**
1. Create a volume and attach to a pod. Write data into the volume(500 mib).
2. Set up an s3/nfs backup store.
3. Take a backup.
4. Go to backup page and click delete the backup.(Individual delete operation)
5. It takes considerable amount of time to delete the backup.cfg in back end and UI continues to show the backup.

**Scenario 2**
1. Set up a recurring backup job with small interval say 2 mins with 3 retain count.
2. Backup some times shows more than 3 backups in backup page as there is delay in deletion.
3. After it ran for 10-15 mins, disable the recurring backup job.
4. There is one extra backup in backup page.

**Environment:**
 - Longhorn version: Master- 06-08-202
 - Kubernetes version: v17.6
 - Node OS type and version: Ubuntu 18.04

**Comment by yasker** [comment]
Sounds like a duplicate of https://github.com/longhorn/longhorn/issues/1423

**Comment by khushboo-rancher** [comment]
I observed this issue is with all kinds of backup store not just google backup store.
A dummy config file of 500 B which doesn't have any checksum mapping to blocks took almost 3 minutes to get deleted. 
UI kept showing it and I had to refresh UI to see the backup gone.

**Comment by smallteeths** [comment]
In the current version, backuplist obtains data through ajax and does not support ws, So when deleting the backup, only the data returned by this request will be obtained. If The returned data contains the data being deleted will also be displayed. Should we change this to a rotation request or support WS?

**Comment by joshimoo** [comment]
@PhanLe1010 can you investigate switching the backup delete call to be blocking.
See [comment](https://github.com/longhorn/longhorn/issues/1472#issuecomment-651318688)

**Comment by PhanLe1010** [comment]
@joshimoo Sure. Thank you

**Comment by PhanLe1010** [comment]
@khushboo-rancher I tried to reproduce the bug and observed as below:

**Scenario 1**
At step 5, I see that UI continues to show the backup but the backend already deleted the backup.cfg

**Scenario 2**
Could not reproduce this bug. I always see exactly 3 backups in the backup store.

Could you please verify it again? The master branch might have already fixed the issue on the backend side. If this is true then we only have a problem with UI not properly display the backup list. In this case, the issue becomes exactly the same as the issue [1472](https://github.com/longhorn/longhorn/issues/1472). We can close this one and I will work on #1472

**Comment by khushboo-rancher** [comment]
Discussed with @PhanLe1010, The deletion of backup on master is taking considerable amount in comparison with v1.0.0 release.
We tried the scenario with S3 backup store in AWS.

**Comment by PhanLe1010** [comment]
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The PR is at [backupstore](https://github.com/longhorn/backupstore/pull/46), [manager](https://github.com/longhorn/longhorn-manager/pull/616), [engine](https://github.com/longhorn/longhorn-engine/pull/505)

* [x] Is the reproduce steps/test steps documented?

* [x] Which areas/issues this PR might have potential impacts on?
Area: backup deletion, backup restoration. 
Issue: #612 

* [x] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at

* [x] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at~~

* [x] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at~~

* [x] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~~

* [x] ~~**if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at~~

**Comment by khushboo-rancher** [comment]
Verified in the latest master- 97a869e, the delay in deletion is gone.

Validation : **Passed**

Scenarios verified:
1. Deletion of single backup - Check the S3 bucket to ensure backup file and blocks are getting deleted.
2. deletion of all backups - Check the S3 bucket to ensure backup file and blocks are getting deleted.
