### ISSUE TITLE
[BUG] UI: Backup continues to appear in longhorn UI after deletion till page is refreshed.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1472]
**Describe the bug**
On clicking delete backup from backup page in longhorn, it still continues to show backup available to perform action on it till a considerable time.

**To Reproduce**
1. Create a volume and attach to a pod. Write data into the volume(500 mib).
2. Set up a s3 backup store.
3. Take a backup.
4. Go to backup page and click delete the backup.(Individual delete operation)
5. UI continues to show the backup and allows user to perform action on it.
6. Page needs to be refreshed to see it gone.

**Environment:**
 - Longhorn version: master- 06-08-2020
 - Kubernetes version: v17.6
 - Node OS type and version: Ubuntu 18.04

**Comment by joshimoo** [comment]
related to #1423

**Comment by yasker** [comment]
Might be related to #1471 .

**Comment by smallteeths** [comment]
In the current version, backuplist obtains data through ajax and does not support ws, So when deleting the backup, only the data returned by this request will be obtained. If The returned data contains the data being deleted will also be displayed. Should we change this to a rotation request or support WS? @yasker

**Comment by yasker** [comment]
From the backend's perspective, the deletion is in progress, and we don't have WebSocket for the backup mechanism. Maybe the better way is in the backend we can wait until the backup is gone (e.g. polling in the backend instead of frontend) before returning? CC @joshimoo

**Comment by joshimoo** [comment]
@yasker @smallteeths I spent some time thinking about this and looking at the code.
I see no reason why we shouldn't do the backup deletion in a [blocking fashion](https://github.com/longhorn/longhorn-manager/blob/af38fa53450e369c89928cdf15299f87e7adf5a2/manager/engine.go#L299-L298) particularly in combination with the new change [#613](https://github.com/longhorn/longhorn-manager/pull/613/files#diff-b452fd95a0bc1117f4f57c5d4621eaa5R99-R104) that now is supposed to return a BackupVolume after deletion, which currently might still include the deleted backup (since the deletion is run on a different go routine)

**Comment by yasker** [comment]
@joshimoo Is GC part of backup deletion done asynchronized now?? I think UI may timeout when waiting for a backup to be deleted.

**Comment by joshimoo** [comment]
@yasker block deletion (gc) is done synchronous, we can make the actual block deletion async.
But for longhorn/longhorn#612 since we are implementing locks, the ui needs to be able to wait for the operation to complete, since a delete might be waiting for a restore to finish.

**Comment by yasker** [comment]
It's OK for the backend to wait, but I don't think it's reasonable to expect the UI to wait potentially hours for the deletion to be completed.

**Comment by yasker** [comment]
We can separate the backup deletion into two parts: backup delete and GC.

The first part can be a blocking operation and once the API returns, the backup should be gone from the backupstore.

The second part (GC) can be started asynchronously after the blocking call of backup deletion. If there is a GC process already in progress for the volume, the call will return immediately or wait after the first GC process is done. We can discuss which way is better. But GC shouldn't block UI from responding.

For the UI part, after the BackupDelete call returns, we can issue another BackupList call to refresh the UI. It should show the backup is gone. Polling the backupstore will result in more than necessary API calls, which might also incur a higher cost for the AWS S3 users.

**Comment by PhanLe1010** [comment]
Thanks @yasker for the thought!

**Comment by joshimoo** [comment]
Changing the cleanup into an async routine depends on having file locks #612 via longhorn/backupstore#45.

**Comment by PhanLe1010** [comment]
The reason that it takes considerable amount of time to delete the backup.cfg in back end and UI continues to show the backup is because [the deletion of backup.cfg file](https://github.com/longhorn/backupstore/blob/2458fbe4269704cbe0351b63c3bf83f3be8e2f81/deltablock.go#L726) is happening after the function call [getBlockInfoMap()](https://github.com/longhorn/backupstore/blob/2458fbe4269704cbe0351b63c3bf83f3be8e2f81/deltablock.go#L719). Function `getBlockInfoMap()` takes a long time because it is reading every block from from datastore. As the result, we experienced the above delay.

Regard to the UI part, I see that the UI already had this feature 
> after the BackupDelete call returns, we can issue another BackupList call to refresh the UI.
Therefore, we don't need to change UI to for this issue.

@smallteeths May I have a question about the requests which UI send to the backend when user click delete a single backup in backup volume? I see that right after the delete request:

request#1
```
[longhorn-manager-p8wr4] 24.6.169.176 - - [06/Jul/2020:01:04:03 +0000] "POST /v1/backupvolumes/testvol12?action=backupDelete HTTP/1.1" 200 716 "http://longhorn.longhorn-system.173.255.248.116.xip.io/backup/testvol12?field=volumeName&keyword=testvol12&state=true" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36" 
```
is sent. UI makes 2 more requests:

request#2
```
[longhorn-manager-p8wr4] 24.6.169.176 - - [06/Jul/2020:01:04:04 +0000] "GET /v1/backupvolumes?volumeName=testvol12&name=backup-439a0562041f440c&field=volumeName&keyword=testvol12&state=true HTTP/1.1" 200 1503 "http://longhorn.longhorn-system.173.255.248.116.xip.io/backup/testvol12?field=volumeName&keyword=testvol12&state=true" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36" 
```
and 

request#3
```
[longhorn-manager-p8wr4] 24.6.169.176 - - [06/Jul/2020:01:04:05 +0000] "POST /v1/backupvolumes/testvol12?action=backupList HTTP/1.1" 200 157 "http://longhorn.longhorn-system.173.255.248.116.xip.io/backup/testvol12?field=volumeName&keyword=testvol12&state=true" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36" 
```

**Comment by PhanLe1010** [comment]
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The PR is at [backupstore](https://github.com/longhorn/backupstore/pull/46), [manager](https://github.com/longhorn/longhorn-manager/pull/616), [engine](https://github.com/longhorn/longhorn-engine/pull/505)

* [x] Is the reproduce steps/test steps documented?

* [x] Which areas/issues this PR might have potential impacts on?
Area: backup deletion, backup restoration. 
Issue: #612 

* [x] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at

* [x] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at~~

* [x] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at~~

* [x] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~~

* [x] ~~**if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at~~

**Comment by khushboo-rancher** [comment]
Verified in the latest master- 97a869e, the deleted backup get disappeared without refreshing the page.

Validation : **Passed**

Scenarios verified:
1. Deletion of single backup - Page shows the spinning icon and on completion of it doesn't show the deleted backup
2. deletion of all backups - Page shows the spinning icon and on completion of it doesn't show the deleted backup
