### ISSUE TITLE
[BUG]Add `additionalPrinterColumn` to CRDs

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1480]
Check https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#additional-printer-columns

As the first step, we need to define what fields should be exposed.

It might impact the upgrade, depends on if CRDs allow editing.

**Comment by joshimoo** [comment]
links seems to be no longer valid:

below might contain additional information about the `additionalPrinterColumns` for the crd spec.
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#customresourcedefinitionspec-v1beta1-apiextensions-k8s-io
https://kubernetes.io/docs/reference/using-api/api-concepts/#receiving-resources-as-tables

**Comment by yasker** [comment]
Thanks @joshimoo , link updated.

**Comment by PhanLe1010** [comment]
**reproduce steps/test steps:**

 For each of the case below: 

1. Fresh installation of Longhorn.
1. Upgrade from older version

Run:

```
kubectl get <LONGHORN-CRD> -n longhorn-system
```

Verify that the output contains information as specify in the `additionalPrinerColumns` at [here](https://github.com/longhorn/longhorn-manager/blob/df9191b824f19a0e00f055c16df1771ccbe5c4b1/deploy/install/01-prerequisite/03-crd.yaml)

**Comment by PhanLe1010** [comment]
[leave a note for later]: we may consider automating the generation of CRDs yaml files as in https://book.kubebuilder.io/reference/generating-crd.html

**Comment by khushboo-rancher** [comment]
Verified with longhorn master - 10/01/2020

Validation - **Pass**

The 'AdditionalPrinterColumn' are appearing for crds from https://book.kubebuilder.io/reference/generating-crd.html

e.g.
<img width="1156" alt="Screen Shot 2020-10-01 at 3 50 54 PM" src="https://user-images.githubusercontent.com/60111667/94874908-1a27d680-0408-11eb-9ed0-6224e6ce9194.png">
