### ISSUE TITLE
[BUG] longhorn started failed for iscsi support in minikube

### ISSUE THREAD

**Issue by lshmouse** [longhorn/longhorn#1493]
**Describe the bug**
longhorn started failed for iscsi support in minikube
```
$ minikube start
$kubectl apply  -f https://raw.githubusercontent.com/rancher/longhorn/master/deploy/longhorn.yml
$ kubectl get pods --namespace longhorn-system
NAME                                       READY   STATUS             RESTARTS   AGE
longhorn-driver-deployer-cd74cb75b-wxclg   0/1     Init:0/1           0          5h54m
longhorn-manager-ghl2l                     0/1     CrashLoopBackOff   73         5h54m
longhorn-ui-8486987944-c5g4m               1/1     Running            0          5h54m
$ kubectl logs longhorn-manager-ghl2l  -n longhorn-system 
time="2020-06-15T07:26:55Z" level=error msg="Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host"
time="2020-06-15T07:26:55Z" level=fatal msg="Error starting manager: Environment check failed: Failed to execute: nsenter [--mount=/host/proc/483/ns/mnt --net=/host/proc/483/ns/net iscsiadm --version], output , stderr, nsenter: failed to execute iscsiadm: No such file or directory\n, error exit status 1"
```

**To Reproduce**
1.  minikube start
2.  kubectl apply  -f https://raw.githubusercontent.com/rancher/longhorn/master/deploy/longhorn.yml
3.  kubectl get pods --namespace longhorn-system
4.   kubectl logs longhorn-manager-ghl2l  -n longhorn-system 

**Expected behavior**
longhorn is deployed success on minikube 

**Log**
```
time="2020-06-15T09:05:52Z" level=error msg="Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host"
time="2020-06-15T09:05:52Z" level=fatal msg="Error starting manager: Environment check failed: Failed to execute: nsenter [--mount=/host/proc/483/ns/mnt --net=/host/proc/483/ns/net iscsiadm --version], output , stderr, nsenter: failed to execute iscsiadm: No such file or directory\n, error exit status 1"
```

**Environment:**
 - Longhorn version: v1.0.0
 - Kubernetes version:  minikube v1.9.2 on Ubuntu 18.04 Kubernetes v1.18.0 on Docker 19.03.2
 - Node OS type and version:
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```
**Additional context**
See issue reported in minikube https://github.com/kubernetes/minikube/issues/2846

**Comment by lshmouse** [comment]
The reason is that minikube run in docker and there is no open-iscsi package in the minikube container.  So just install the open-iscsi in the minikube docker container will solve this issue, eg:
```
minikube ssh "sudo apt-get update;sudo apt-get install -y open-iscsi"
```

**Comment by tristanlins** [comment]
That does not work, because Minikube VM ist **not** debian based and **not** designed to be modified! :-(

**Comment by ArcaneDiver** [comment]
It worked for me...

**Comment by rajasaur** [comment]
I have built minikube iso with support for iscsi [here](https://github.com/rajasaur/minikube) on the iscsi_support branch. If it can be pulled it, I will raise a pull request for the same. I have tested once by building an updated ISO and running longhorn with it and its been successful. I am rebuilding now with the patch just to verify and can raise a PR .
