### ISSUE TITLE
[Question] How to transfer volumes to another node?

### ISSUE THREAD

**Issue by JLueke** [longhorn/longhorn#1496]
If I want to remove a node in kubernetes, how can I transfer the volume to another node?

Example:
I have three node (Node 1, Node 2, Node 3). Node 3 holds the data of a volume with 50Gi.
Now I want to remove Node 3 from the cluster. How can I transfer the volume (data) to on of the remaining nodes.

`kubectl drain <node-id>` seems to only remove the pods on that node.

**Comment by joshimoo** [comment]
@JLueke for 1.0 the default settings create 3 replicas for a volume, with hard anti affinity. So each replica would end up on it's own node. In that case the data should be available on one of the other replicas. In the case where you only have a single replica, the best approach would probably be a backup & restore. cc @shuo-wu to get his input on this.

**Comment by shuo-wu** [comment]
As Joshua said, there are 3 replicas for each volume by default. Hence removing a node typically won't corrupt the volume. 

For safety or for the case that there is a single replica for the volume, you can check whether there is at least one replica on the nodes that won't be removed later via UI. 
If YES, it's fine to remove the node. 
If NO, you can:
1.  disable the scheduling for the node that will be removed later.
2. increase the replica count to trigger replica rebuild on new nodes.
3. decrease the replica count
Then you can remove the node without affecting the volume

**Comment by JLueke** [comment]
Thank you.

**Comment by colegatron** [comment]
I'm trying to do the same
In step 3, how can you be sure the volume replica going to be decreased/deleted is the one in the node you want to delete?

I mean; Lets say you have 3 nodes and need to delete node2 and the volume data is in node1(data) and node2(single replica).
When you increase the new replica will go to node3.
Then you say to decrease the number of replicas from 3 to 2; How do you specify the replica in node2 when decreasing to ensure node2 remains free of data after the replica decrease? Is that possible?

**Comment by shuo-wu** [comment]
@colegatron Updating the replica count (from a higher number to a lower number) won't lead to Longhorn deleting any replicas. Instead, you can/need to delete a replica by yourself.
You can have a quick try/test with an empty volume via UI.

**Comment by ammirator-administrator** [comment]
@shuo-wu 
If deleting lets say 1 replica from 2.. the pods using this volume wont automatically start on the one remaining is that true?
What we have to do is to scale down the pods to 0 and then scale back to whatever nr is that right?

**Comment by ammirator-administrator** [comment]
Ok after some testing I came up with a working solution.
You can have just 1 replica this is more than enough, and is no need to restore from backup.

```
- Put your application in maintenance mode.
- Create a backup of the volume. (It wont be possible after) Should not be needed but just in case.
- Scale down dependent deployments for example if you need to move a postgres volume scale down the api whoch connects to postgres.
- Scale down all pods of the statefulset of that volume, for example all postgres pods.
   ! Note that you cant use drain since it will schedule pods to other node. And that is not what we want. Better use the scale down method.
- After that the volume will detach from pod but not from node. So we need to detach it from the node. On that volume in the Longhorn UI in the Volumes tab should be a Actions button hover on it and a popup will appear and inside it should have a Detach item and click on it and the ok.
- After that on the same popup should be a Attach item and click on it and select the node where you want to attach the volume and ok.
- Even tho it may transit quickly in Healthy state do not trust that. Better click on the volume and see more details and there may be shown some additional info about the volume and the process of attaching it to the new node.
Once it is finished you can continue with the next steps.
- Put a restriction on the old node to not schedule any new statefulset pods on it. This can be done with NoSchedule constraints or any other depending on your app.
- Scale up the pods of the services you scaled down and use the original count to scale them to same count. 
The statefull services now should be scheduled on the new node where the volume is attached.
- Once you are sure that the services are running fine on the new node you can disable the maintenance mode from your app (if you even have such feature)
```

**Comment by shuo-wu** [comment]
Volumes and the corresponding workload pod can go anywhere no matter if there is a replica on that node.
More replica means higher availability. Volumes should work fine as long as there is one healthy replica.

**Comment by jvincze84** [comment]
Hi
Maybe the following steps work fine:
1. Create node label which matches the old node and the new node, as well.
2. Change the Volume
2a. nodeSelector to the new label
2b. numberOfReplicas to 2
3. Wait for the new replica, and the volume to be healthy
4. Change the Volume manifest. 
4a. Set nodeSelector to the new node
4b. Set numberOfReplicas back to 1,
