### ISSUE TITLE
[Question] How to transfer backup from one longhorn to another?

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1499]
How to transfer backup from one longhorn to another?

**Comment by shuo-wu** [comment]
I am not sure what is `transfer backup from one Longhorn to another`. A backup target can be shared by multiple Longhorn clusters. 

And Longhorn can rely on a shared backup target to achieve some disaster recovery mechanisms, See the doc for details:
https://longhorn.io/docs/1.0.0/concepts/#disaster-recovery-volumes

**Comment by hillbun** [comment]
@shuo-wu 

For example, I have 5 longhorn separated instances in different cloud providers.

I need to just share some of backups, how to do?

**Comment by shuo-wu** [comment]
Set the same backup target (and secret if necessary) on the `Setting` page.
https://longhorn.io/docs/1.0.0/snapshots-and-backups/backup-and-restore/set-backup-target/

**Comment by ShadowJonathan** [comment]
Partially unrelated, but right now i've already imagined a way to quickly export/import longhorn volumes:
1. Detatch volume from pods
2. Attach to node
3. `dd` the raw device (under `/dev/longhorn`) into an `iso` file
4. Carry `iso` file to the target cluster
5. Create PVC with equal size, or create `longhorn-static` volume
6. Attach volume to node
7. `dd` the `iso` file into the raw device
8. Detach and start pods

I know the correct way to do it is via backups, but this can be a simple-n-quick way to transfer big volumes (>1TB) over large distances, or between air-gapped solutions, without needing to bisect the blocks out of the backup target that're required for this volume.

(note: I've only learned of `dd` just a while back about how useful it is, please read up on it before attempting to do this, and also *always* please make a snapshot/backup before attempting to do this)

**Comment by shuo-wu** [comment]
@ShadowJonathan Your solution sounds practical. 
But I don't follow `without needing to bisect the blocks out of the backup target that're required for this volume`. The backup means uploading/copying the volume data to somewhere. The restore means downloading/fetching data from somewhere to a new volume. I think your solution is pretty similar to backup & restore.

**Comment by ShadowJonathan** [comment]
Iirc (and please correct me if im wrong), if multiple volumes have the same backup target, their blocks arent seperated by sub-directory/path, and instead all mingle while metadata files can annotate the blocks needed for that specific backup target, and refer to them by their hashes.

So either all of those hashed blocks are non-seperated by volume, or seperated by volume, I thought it was the former one, but if it's the latter one, a backup target can be viable.

My solution is more a "folder of (iso) disks" for "classic" cold storage, and/or for a more simple-and-quick migration.

**Comment by shuo-wu** [comment]
Each backup volume holds its own directory and the data blocks. **The data blocks of all backup (all history backup and the latest backup) of this volume** are mingled. But the metadata file of each backup can indicate the data blocks it consists of.

**Comment by ShadowJonathan** [comment]
Yeah, my note specifically was that putting it on an `iso` would make it more straightforward than resolving all relevant blocks from a latest backup on that service (if you dont/cant connect to that service from your destination cluster) and copy-pasting them in the same structure on the end side.

Maybe something interesting like "download ISO" of a snapshot/backup could be done from the UI, which'd handle all of this for you, but from/for a specific snapshot so forensics/diagnostics can be applied on it.

**Comment by shuo-wu** [comment]
Do you mean this? It's not via UI. Since Longhorn is all about `volume`, it can't suddenly create a file somewhere and it doesn't know where it stores the file.
https://longhorn.io/docs/1.0.0/references/examples/#restore-to-file

**Comment by ShadowJonathan** [comment]
No, I'm not referring to that, I'm referring to ssh-ing into the host node, and then attaching the disk to it so it's visible from `/dev/longhorn/`, then you get the raw device, not a mounted file system, which could be a critical difference.

With a raw device you can get a byte-by-byte perfect copy, but with mounting on a filesystem you'd get a subdirectory copy.

**Comment by shuo-wu** [comment]
Yeah. If an iso(right now we are using raw or qcow format) file can be download from UI based on a backup or a snapshot, that's more straightforward. We need to check if it's possible first.
