### ISSUE TITLE
[FEATURE/BUG] Add resource requests/limits to default deployment/controller rollouts.

### ISSUE THREAD

**Issue by ShadowJonathan** [longhorn/longhorn#1502]
**Is your feature request related to a problem? Please describe.**
I've ran longhorn for a little while now in my cluster, and nearly all pods run in a `BestEffort` QoS, which means they're likely to get killed first in an event of OOM.

Considering that these pods are crucial to pods (storage), isn't it required that they're given a QoS of "Guaranteed" (requests/limits set) so that pods may keep working if system starts the oomkiller? This way those pods (engine/attacher) won't get killed randomly under high load, and corruption/uninterruptable sleep/cascading failure wont happen.

**Describe the solution you'd like**
Research on the memory/cpu requirements of each of the pods that longhorn deploys (either in daemonset, instancemanager, or other resources), and add these requests/limits to `deploy/longhorn.yaml`, the helm chart (with configurable values), and to the rancher catalog app.

**Describe alternatives you've considered**
Manually defining resources on the deployments, but I quickly realised this one propagate to all of longhorn in my cluster, as most of the pods come from CRDs which dont have a resources KV in their spec.

**Additional context**
#1021 is probably sorta related to this

**Comment by shuo-wu** [comment]
I guess this may be an alternative solution. You can check it first to see if it matches your requirement:
https://github.com/longhorn/longhorn/issues/1487

**Comment by ShadowJonathan** [comment]
That'd definitely take care of the critical requirement, but I'd also like for this to exist because of how this skews resource usage vs resource requests in my cluster, but that's more a personal nagging.

**Comment by yasker** [comment]
@ShadowJonathan For most of the components, the PriorityClass should be good enough to ensure the stability of the system. For some of the key components (Instance Manager), we have also [`Guaranteed Engine CPU`](https://longhorn.io/docs/1.0.0/references/settings/#guaranteed-engine-cpu) setting which will reserve certain CPU cycles for the instance manager pods (which runs Longhorn engine processes and are critical to the data path). I think with the combination of both mechanisms, we should have protected the Longhorn system well enough.
