### ISSUE TITLE
[FEATURE] Straightforward volume export via "download volume" in longhorn UI

### ISSUE THREAD

**Issue by ShadowJonathan** [longhorn/longhorn#1504]
**Is your feature request related to a problem? Please describe.**
https://github.com/longhorn/longhorn/issues/1499#issuecomment-645374689

Exporting/inspecting a volume can be more straightforward by allowing users to download ISO copies of the disk from a snapshot/backup, it enables on-the-fly diagnostics or forensics, and can allow simple import (via the `dd` command on a node attachment) in case of airgapping.

**Describe the solution you'd like**
A dropdown menu item in the longhorn UI which creates and downloads a `iso` copy of the snapshot at that time.

**Describe alternatives you've considered**
Doing this manually by shutting down workload pods, attaching a volume to a node, and applying the `dd` command to it to generate an `iso` file locally, and then transfer it elsewhere.

However, this doesnt allow snapshot downloads, and disrupts workloads.

**Comment by ShadowJonathan** [comment]
By suggestion of @shuo-wu, i also think that `raw` or `qcow` formats could work for this, albeit maybe not compatible with `dd` (afaik, i would need to research that)

**Comment by yasker** [comment]
I am afraid it's not very feasible. Longhorn volumes can be gigabytes to terabytes, download it from the UI (especially though the public internet) can take forever.

But you can create a backup for the volume, then use https://longhorn.io/docs/1.0.0/advanced-resources/data-recovery/recover-without-system/ to restore it to your local node.
