### ISSUE TITLE
[Question] How to define backup schedule of volume in pvc yalm?

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1507]
How to define backup schedule of volume in pvc yalm?  but not via UI.

**Comment by shuo-wu** [comment]
You can do it via StorageClass rather than PVC. Here is the doc:
https://longhorn.io/docs/1.0.0/snapshots-and-backups/scheduling-backups-and-snapshots/#set-up-recurring-jobs-using-a-storageclass
