### ISSUE TITLE
[Question] what accessModes is allow?

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1510]
Only ReadWriteOnce?

How about ReadOnlyMany  and ReadWriteMany ?

**Comment by shuo-wu** [comment]
`ReadWriteOnce` Only. Since longhorn is a **block** storage system and longhorn volumes act like block devices.

If you want RWX, an NFS server on top of a Longhorn volume may be a choice. Actually we are preparing the guideline for it: #1183

**Comment by hillbun** [comment]
what will happen if I mount it with deployment with 3 replicas if mode is ReadWriteOnce.

**Comment by shuo-wu** [comment]
Deployment won’t work well with them if you have **more than one Pod running with persistent data**. In this case, I would recommend StatefulSet.

Here is the related explanation: https://rancher.com/blog/2018/2018-10-11-unexpected-kubernetes-part-2/

**Comment by esakarya** [comment]
i created one statefullsets but still no luck there.

Multi-Attach error for volume "pvc-0d942c05-42b0-4937-8ca4-d08cd5b903e0" Volume is already used by pod(s) postgress-server-0
