### ISSUE TITLE
[Question] Why do I need to manually run resize2fs

### ISSUE THREAD

**Issue by StoneCut** [longhorn/longhorn#1511]
I use Longhorn 1.0 on Rancher 2.4.3.

I have to resize a volume as follows otherwise it doesn't work:
1. Detach the volume using via Longhorn UI
2. Edit PVC spec.resources.requests.storage to reflect the new size
3. Re-attach the volume using Longhorn UI
4. Run resize2fs on the respective /dev/longhorn/* device on the node I attached the volume to
5. Redeploy the pod consuming the volume

According to the documentation I shouldn't need to do step #4.
What could be the problem? What am I doing wrong?

**Comment by shuo-wu** [comment]
You need to wait for the volume auto attachment and auto detachment complete after step2.

The correct steps:
1. Scale down the workload and wait for the volume detachment.
2. Edit PVC spec.resources.requests.storage
3. Wait for the volume automatic attachment then detachment.
4. Re-launch the workload.

**Comment by StoneCut** [comment]
Thank you very much! That method worked nicely. Maybe it could be outlined in the documentation as I was unsure how to handle the case. 

Thanks again.
