### ISSUE TITLE
[FEATURE] Allow users to directly activate a restoring/DR volume as long as there is one ready replica.

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1512]
**Is your feature request related to a problem? Please describe.**
Some replicas may get stuck in the restoring process then the restore volume is no longer useable. We can provide an API to forcibly activate the volume as long as there is a ready replica.

**Describe the solution you'd like**
1. Marking all replicas that are still in the restore progress as failed.
2. Disable rebuild.
3. Indicate the volume is usable now and do auto detachment.

**Comment by shuo-wu** [comment]
Design Doc(draft): https://docs.google.com/document/d/1k3vYA68ej09F9h5qaoLhdO0wuWm7kNAsIDNyVPH2u-A/edit?usp=sharing

**Comment by yasker** [comment]
Moved with #1279 to v1.1.0.

**Comment by innobead** [comment]
https://github.com/longhorn/longhorn/issues/3069

**Comment by weizhe0422** [comment]
1. Create a volume and write some data
   ![image](https://github.com/longhorn/longhorn/assets/17548901/8a6540a9-2eee-4031-ac5b-6deae80a11ea)
2. Create a backup
   ![image](https://github.com/longhorn/longhorn/assets/17548901/886143c9-d24e-42f2-8943-9147bb8cefde)
3. Create a DR volume
   ![image](https://github.com/longhorn/longhorn/assets/17548901/ee400a86-f95a-4391-8268-aeea40cbaf96)
4. Disable rebuilding by setting concurrent-replica-rebuild-per-node-limit to be 0
   ![image](https://github.com/longhorn/longhorn/assets/17548901/c266b8d6-79ee-4fbb-8d81-8083607f120d)
5. Failed a replica
   ![image](https://github.com/longhorn/longhorn/assets/17548901/36712847-96d5-4e0b-ac07-5530abc084f4)
6. Forcibly activate the DR volume and volume could be activated
   ![image](https://github.com/longhorn/longhorn/assets/17548901/0684aaea-b164-4e4d-95a3-b92f8a5a457f)
7. Volume could be attached again and data is correct
   ![image](https://github.com/longhorn/longhorn/assets/17548901/1b5f3bd7-501a-406f-9b45-8c49cddd76ac)
   ![image](https://github.com/longhorn/longhorn/assets/17548901/52fae09e-484c-4034-a977-2afcd866ff10)
