### ISSUE TITLE
[BUG] AttachVolume.Attach failed for volume "pvc-0239c039-3d8b-4035-825d-620b16b88ab7" : rpc error: code = Aborted desc = The volume pvc-0239c039-3d8b-4035-825d-620b16b88ab7 is attaching"

### ISSUE THREAD

**Issue by ReinitiaIized** [longhorn/longhorn#1513]
**Describe the bug**
After successfully deploying Longhorn, any attempt to deploy an app using Rancher will result in the pod being stuck in "CreatingContainer", followed with repeated messages of " 	AttachVolume.Attach failed for volume "pvc-0239c039-3d8b-4035-825d-620b16b88ab7" : rpc error: code = Aborted desc = The volume pvc-0239c039-3d8b-4035-825d-620b16b88ab7 is attaching"

**To Reproduce**
1. Choose an app to deploy through the Catalog (doesn't matter which project/namespace)
2. Deploy app
3. Check on pod status (complains about "Deployment does not have minimum availability.", followed with "AttachVolume.Attach failed for volume "pvc-0239c039-3d8b-4035-825d-620b16b88ab7" : rpc error: code = Aborted desc = The volume pvc-0239c039-3d8b-4035-825d-620b16b88ab7 is attaching"

**Expected behavior**
The volume attaches cleanly and the pod is deployed

**Log**
[longhorn-support-bundle_7f3128f0-006d-4a57-afa6-589bdc35f606_2020-06-22T13-23-24Z.zip](https://github.com/longhorn/longhorn/files/4813418/longhorn-support-bundle_7f3128f0-006d-4a57-afa6-589bdc35f606_2020-06-22T13-23-24Z.zip)

**Environment:**
 - Longhorn version: 1.0.0
 - Kubernetes version: k3s v1.18.4+k3s1
 - Node OS type and version: CentOS 8.1 Minimal Install (SELinux disabled)

**Comment by shuo-wu** [comment]
Can you check if the ISCSI is enabled on your cluster nodes? There are tons of following error messages in the support bundle:
```
2020-06-22T08:19:01.884241272-05:00 [pvc-0239c039-3d8b-4035-825d-620b16b88ab7-e-2503eaeb] time="2020-06-22T13:19:01Z" level=warning msg="FAIL to discover due to Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm -m discovery -t sendtargets -p 10.42.0.47], output , stderr, Failed to connect to bus: No data available\niscsiadm: can not connect to iSCSI daemon (111)!\nFailed to connect to bus: No data available\niscsiadm: can not connect to iSCSI daemon (111)!\niscsiadm: Cannot perform discovery. Initiatorname required.\niscsiadm: Could not perform SendTargets discovery: could not connect to iscsid\n, error exit status 20"
```

**Comment by ReinitiaIized** [comment]
My apologies, I forgot to respond this. Yes, that was definitely the issue, and has since been working well. I appreciate the time investigating it.

**Comment by martiinezz** [comment]
Do you need to have ISCSI on all nodes (masters+workers?) or just workers?
