### ISSUE TITLE
[BUG] Add helm's standard labels 

### ISSUE THREAD

**Issue by jiaqiluo** [longhorn/longhorn#1514]
Improvement

Helm recommends having some standard labels as the best practices: https://helm.sh/docs/chart_best_practices/labels/#standard-labels

It will be great if Longhorn can add those labels to its deployments, at least add this label `helm.sh/chart: NAME-VERSION`

**Comment by ttpcodes** [comment]
## Pre-merged Checklist
* [X] Does the PR include the explanation for the fix or the feature?

* [X] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The PR is at #1558.

* [X] Is the reproduce steps/test steps documented?

* [X] Which areas/issues this PR might have potential impacts on?
Area: deployment
Issues: #1514

* [X] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?~~

* [X] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~

* [X] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?~~

* [X] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?~~

* [X] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?~~

* [X] ~~**if labeled: require/manual-test-plan** Has the manual test plan been documented?~~

**Comment by ttpcodes** [comment]
To test, simply get the latest version of `longhorn/longhorn` and follow the instructions on the `Longhorn` website to install with `Helm`. You should observe that all components that are deployed with `Helm` (so this would exclude the `Engine Image Pods`, the `CSI Attacher Pods`, etc.) contain `Labels` similar to the following:
```
app.kubernetes.io/name: longhorn
helm.sh/chart: longhorn-1.0.0
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/instance: longhorn
app.kubernetes.io/version: v1.0.0
```

**Comment by khushboo-rancher** [comment]
Verified on Master - 07-09-2020

Validation - **Passed**

Components ```longhorn-driver-deployer, longhorn-manager and longhorn-ui``` of longhorn have the helm's standard labels:
```
"app.kubernetes.io/instance": "longhorn",
"app.kubernetes.io/managed-by": "Helm",
"app.kubernetes.io/name": "longhorn",
"app.kubernetes.io/version": "v1.0.0",
"helm.sh/chart": "longhorn-1.0.0"
```

**Comment by khushboo-rancher** [comment]
@ttpcodes Before closing this I just want to confirm, for components other than ```longhorn-driver-deployer, longhorn-manager and longhorn-UI``` we can't provide labels?

**Comment by khushboo-rancher** [comment]
Discussed with @ttpcodes, Labels are only applied to the resources that Helm creates.
