### ISSUE TITLE
[BUG] failed to attach volume

### ISSUE THREAD

**Issue by yujunz** [longhorn/longhorn#1516]
**Describe the bug**

Volume attach error after deleting workload and re-create.

**To Reproduce**

1. Create deployment and all volumes mounted to pods successfully despite the replica is on different node of the pod (as expected)
2. Cordon the node, delete the pod to force reschedule to another node. The volumes enters a dead loop of detaching/attaching (something wrong?)
3. Delete the deployment and wait for several minutes, the volumes becomes detached (as expected)
4. Create the deployment again, pod stuck at  AttachVolume.Attach failed for volume "pvc-c6ae8ffe-b467-11ea-91e6-ac1f6bbd2c5c" : volume attachment is being deleted (something wrong?)

**Expected behavior**

Volume is re-attached

**Log**

longhorn-manager

```
time="2020-06-23T06:58:57Z" level=error msg="failed to receive log for instance pvc-c6ae8ffe-b467-11ea-91e6-ac1f6bbd2c5c-e-4db5bb53: rpc error: code = NotFound desc = cannot find process pvc-c6ae8ffe-b467-11ea-91e6-ac1f6bbd2c5c-e-4db5bb53"
time="2020-06-23T06:58:57Z" level=warning msg="cannot get crash log for instance pvc-c6ae8ffe-b467-11ea-91e6-ac1f6bbd2c5c-e-4db5bb53 on Instance Manager instance-manager-e-0afe27e7 at dgx01, error rpc error: code = NotFound desc = cannot find process pvc-c6ae8ffe-b467-11ea-91e6-ac1f6bbd2c5c-e-4db5bb53"
```

instance-manager

```
[pvc-c6ae9492-b467-11ea-91e6-ac1f6bbd2c5c-e-7c34d223 time="2020-06-23T06:55:30Z" level=warning msg="FAIL to discover due to Failed to execute: nsenter [--mount=/host/proc/2238/ns/mnt --net=/host/proc/2238/ns/net iscsiadm -m discovery -t sendtargets -p 10.233.83.98], output , stderr, Bus n/a: changing state UNSET → OPENING\nBus n/a: changing state OPENING → AUTHENTICATING\nFailed to connect to bus: No data available\niscsiadm: can not connect to iSCSI daemon (111)!\nBus n/a: changing state UNSET → OPENING\nBus n/a: changing state OPENING → AUTHENTICATING\nFailed to connect to bus: No data available\niscsiadm: can not connect to iSCSI daemon (111)!\niscsiadm: Cannot perform discovery. Initiatorname required.\niscsiadm: Could not perform SendTargets discovery: could not connect to iscsid\n, error exit status 20"
```

**Environment:**
 - Longhorn version: v1.0.0
 - Kubernetes version: v1.14.3
 - Node OS type and version: Ubuntu Xenial

**Additional context**

The steps to reproduce is from a rough memory.

**Comment by yasker** [comment]
@khushboo-rancher Can you check if you can reproduce this issue?

**Comment by yasker** [comment]
@yujunz Just rechecked the log again

> [pvc-c6ae9492-b467-11ea-91e6-ac1f6bbd2c5c-e-7c34d223 time="2020-06-23T06:55:30Z" level=warning msg="FAIL to discover due to Failed to execute: nsenter [--mount=/host/proc/2238/ns/mnt --net=/host/proc/2238/ns/net iscsiadm -m discovery -t sendtargets -p 10.233.83.98], output , stderr, Bus n/a: changing state UNSET → OPENING\nBus n/a: changing state OPENING → AUTHENTICATING\nFailed to connect to bus: No data available\niscsiadm: can not connect to iSCSI daemon (111)!\nBus n/a: changing state UNSET → OPENING\nBus n/a: changing state OPENING → AUTHENTICATING\nFailed to connect to bus: No data available\niscsiadm: can not connect to iSCSI daemon (111)!\niscsiadm: Cannot perform discovery. Initiatorname required.\niscsiadm: Could not perform SendTargets discovery: could not connect to iscsid\n, error exit status 20

It seems the iscsid is not configured correctly on the host. Especially the initiator name is not set.

**Comment by yujunz** [comment]
> It seems the iscsid is not configured correctly on the host. Especially the initiator name is not set.

Thanks for the diagnose. We do have two different types of nodes in the clusters. Let me recheck to see if it is related to iscsid configuration.

**Comment by AlexDias95** [comment]
Any news about this? I have the same problem :/

**Comment by shuo-wu** [comment]
> Any news about this? I have the same problem :/

Can you file a new issue and provide more error info as well as the environment?
