### ISSUE TITLE
[BUG]Node diagram in the Dashboard is not correct when there are disabled nodes

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1518]
**Describe the bug**
When Longhorn workloads cannot be launched on some nodes, the `Unschedulable` and `Disabled` will count the nodes separately and be **presented on the diagram separately**.

**To Reproduce**
1. Deploy Longhorn in a 3-node cluster.
2. Go to Node Page.
3. Disable the **disk scheduling** of one node.
4. Back to DashBoard Page. Check the Node diagram.
5. `Unschedulable` and `Disabled` are shown separately in the diagram. The result is like: there are 4 nodes in total for the Longhorn system, 1 is Unschedulable, 1 is Disabled, 2 are `Schedulable`.

**Expected behavior**
The Unschedulable part and the Disabled part should overlap in the diagram.

**Environment:**
 - Longhorn version: v1.0.0

**Additional context**
The original issue: #1503

**Comment by smallteeths** [comment]
1. Node is only disabled and only unscheduled. This situation exists (now it will be displayed according to the original)
2. Node is disabled and unscheduled now the logic is to only display disabled on the chart
3. Node is down and unscheduled Now the logic is to show only down on the chart
4. When I tested, I didn't encounter the status of down and disabled, as long as the node is down, it will not be judged as disabled.

**Comment by khushboo-rancher** [comment]
Verified on master - 06-29-2020

Verification: **Passed**

Reported issue is resolved. In case of 1 disabled node, node page show 2 ```Schedulable``` 1 ```disabled```
<img width="1737" alt="Screen Shot 2020-06-29 at 3 17 24 PM" src="https://user-images.githubusercontent.com/60111667/86062406-7bad6300-ba1d-11ea-9098-28ddc4318ae4.png">

**Scenarios tested:**
1. Node disabled.
2. Node Unscheduled. (Reached over the minimum available disk space).
3. Node down.
4. Node disabled then went down. (Status shows down)
5. Node unschedulable then went down. (Status shows down)
