### ISSUE TITLE
[FEATURE]Provide the doc to explain node/volume size info

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1519]
**Is your feature request related to a problem? Please describe.**
Right now some users are confused of the size info in Longhorn UI.
e.g., What's `Schedulable`, `Reserved`, `Used`, and `Disabled` in the Dashboard page? What's `Allocated`, `Used`, `Size` in the Node page?

**Describe the solution you'd like**
A doc to explain these "Terms".

**Describe alternatives you've considered**
Have a better design for the size-related info presentation, which is hard to lead misunderstanding/confusion.

**Additional context**

**Comment by shuo-wu** [comment]
Besides, we need one more doc to explain the volume size related concepts since some users feel confused about that part.

**Comment by yasker** [comment]
Done.
