### ISSUE TITLE
[IMPROVEMENT] Change the script into a docker run command mentioned in 'recovery from longhorn backup without system installed' doc

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1521]
**Describe the bug**
Need to change yaml https://github.com/longhorn/longhorn/blob/master/examples/restore_to_file.yaml.template in the 'recovery from longhorn backup without system installed' doc https://longhorn.io/docs/1.0.0/advanced-resources/data-recovery/recover-without-system/ to a docker run command.

Change the script into a docker run instead of YAML file  - To recover backup without having cluster.

**Comment by chriscchien** [comment]
Verified in longhorn manager(`259cf1`) with test [steps](https://github.com/longhorn/longhorn/issues/1521#issuecomment-1266535014)
Result Pass

As below picture shown I can get `volume.raw` without cluster.
Then deploy cluster and Longhorn, upload `volume.raw` as backing image, verify data by volume create from backing image.
The data were correct and volume working properly
![Screenshot from 2022-11-04 11-18-05](https://user-images.githubusercontent.com/73337386/199877698-f9c2ee47-6db6-4a32-893b-ec016d069fa6.png)
