### ISSUE TITLE
[BUG] Prevent upgrade failure due to changed StorageClass

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1527]
When using Helm, the upgrade may fail due to Kubernetes cannot change StorageClass's certain parameters. It is inconvenient to the users. We need to figure out a way to deal with it automatically. Some ideas:
1. Should we make Helm chart replace the `longhorn` storageclass without complaining?
2. Should we compare the current `longhorn` storageclass with our record of latest `longhorn` storageclass and stop the upgrade process if there is a problem?
3. Should we move the StorageClass creation to the code instead of YAML?
4. What's the workaround for users with StorageClass upgrade failure?

Currently, we don't recommend modifying the StorageClass (https://longhorn.io/docs/1.0.0/best-practices/#storageclass ). But a predictable upgrade failure always sounds bad.

**Comment by yasker** [comment]
@khushboo-rancher Can you help to try the following scenario and see if the steps we provide at https://longhorn.io/docs/0.8.1/deploy/upgrade/longhorn-manager/#error-longhorn-is-invalid-provisioner-forbidden-updates-to-provisioner-are-forbidden still works for v0.8.1 to v1.0.0?

1. Install Longhorn v0.8.1 using Rancher.
2. Modify the StorageClass `longhorn`, e.g. change replica count from 3 to 2.
3. Upgrade to v1.0.0.
    1. Observe the upgrade error
4. Try if https://longhorn.io/docs/0.8.1/deploy/upgrade/longhorn-manager/#error-longhorn-is-invalid-provisioner-forbidden-updates-to-provisioner-are-forbidden works to fix the upgrade.

**Comment by PhanLe1010** [comment]
## Upgrading using Rancher from v0.8.1 to v1.0.0
1. Install Longhorn v.0.8.1 using Rancher
1. Delete `longhorn` storageclass. Create `longhorn` storageclass with new parameter `numberOfReplicas: 2`
1. Upgrade to Longhorn v.1.0.0 using Rancher
Upgrading succeed. 

## Upgrading using `kubectl apply -f` from v1.0.0 to v1.0.2
1. Install Longhorn v1.0.0 using:
   ```
   kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.0.0/deploy/longhorn.yaml
   ```
1. Delete `longhorn` storageclass. Create `longhorn` storageclass with new parameter `numberOfReplicas: 2`
1. Install Longhorn v1.0.2 using:
   ```
   kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.0.2/deploy/longhorn.yaml
   ```
1. Upgrade to Longhorn v.1.0.0 using Rancher

Upgrading succeed but output the error:
```
The StorageClass "longhorn" is invalid: parameters: Forbidden: updates to parameters are forbidden.
```

## Upgrading using `kubectl apply -f` from v1.0.2 to master
Upgrading succeed but output the error:
```
The StorageClass "longhorn" is invalid: parameters: Forbidden: updates to parameters are forbidden.
```

**Comment by PhanLe1010** [comment]
### Helm installation
1. Simulate the user's action which is deleting and create new storageclass under the name `longhorn` with new parameter `numberOfReplicas:  2`.
1. Add longhorn helm chart repo: `helm repo add longhorn https://charts.longhorn.io`
1. Update `helm repo update`
1. Install Longhorn `helm install longhorn-is-the-best longhorn/longhorn`
1. Installation failed. See error:
   ```
   Error: rendered manifests contain a resource that already exists. Unable to continue with install: StorageClass "longhorn" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "longhorn-daika"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"
   ```

### Conclusion
This problem is **not** ok since it will prevent users from install/upgrading Longhorn.

**Comment by PhanLe1010** [comment]
### Propose solution:
1. Move the StorageClass creation to the code instead of YAML
1. Inside Longhorn [upgrade code](https://github.com/longhorn/longhorn-manager/blob/master/upgrade/upgrade.go), we check to see if `longhorn` storage class already exists. If yes, we skip creating the storageclass. If no, we create it.

**Comment by yasker** [comment]
How would we know what parameter we should use for the storage class?

**Comment by PhanLe1010** [comment]
I am thinking putting those parameters into `default-setting.yaml`. Longhorn manager can then read that information and build up the manifest for the storageclass.

**Comment by PhanLe1010** [comment]
Because the issue only occurs when install/upgrade using Helm, another approach is that we can d[etect the existing longhorn storageclass inside the Helm](https://github.com/longhorn/longhorn/pull/1902) template and react accordingly.

**Comment by PhanLe1010** [comment]
**Test steps:**

**storageclass-form-1**
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
  fromBackup: ""
```
**storageclass-form-2**
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
provisioner: rancher.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
  fromBackup: ""
```

### New Helm installation:
1. create a `storageclass-form-1`
1. Install Longhorn using Helm and longhorn chart in longhorn repo.
1. Verify that no error occurs, the installation succeeds.
1. Create a volume using `longhorn` storageclass. Verify that the volume has 2 replicas.
1. Delete Longhorn: `helm uninstall longhorn -n longhorn-system`
1. Delete all CRDs created by Longhorn and the `storageclass-form-1`

1. create a `storageclass-form-2`
1. Install Longhorn using Helm and longhorn chart in longhorn repo.
1. Verify that error occurs, the installation fails:
   ```
   template: longhorn/templates/storageclass.yaml:24:4: executing "longhorn/templates/storageclass.yaml" at <fail "the existing longhorn storageclass doesn't have provisioner as driver.longhorn.io">: error calling fail: the existing longhorn storageclass doesn't have provisioner as driver.longhorn.io
   ```
1. Delete Longhorn: `helm uninstall longhorn -n longhorn-system`
1. Delete all CRDs created by Longhorn and the `storageclass-form-2`

### Helm upgrade:
1. Follow this document to install longhorn v1.0.2 https://longhorn.io/docs/1.0.2/deploy/install/install-with-helm/#installing-longhorn
1. Upgrade Longhorn using Helm and longhorn chart in longhorn repo.
   ```
    helm upgrade longhorn chart/ -n longhorn-system
   ```
1. Upgrade succeeds
1. Delete the existing `longhorn` storageclass. Create **storageclass-form-1**. This simulates user action of modifying the default `longhorn` storageclass
1. Upgrade Longhorn using the old chart
   ```
   helm upgrade longhorn longhorn/longhorn --namespace longhorn-system
   ```
1. See error:
   ```
   Error: UPGRADE FAILED: cannot patch "longhorn" with kind StorageClass: StorageClass.storage.k8s.io "longhorn" is invalid: parameters: Forbidden: updates to parameters are forbidden.
   ```
1. Upgrade Longhorn using Helm and longhorn chart in longhorn repo.
   ```
    helm upgrade longhorn chart/ -n longhorn-system
   ```
1. Upgrade succeeds
1. Delete `longhorn` storageclass. Create **storageclass-form-2**
1. Upgrade Longhorn using Helm and longhorn chart in longhorn repo.
   ```
    helm upgrade longhorn chart/ -n longhorn-system
   ```
1. See error:
   ```
   Error: UPGRADE FAILED: template: longhorn/templates/storageclass.yaml:24:4: executing "longhorn/templates/storageclass.yaml" at <fail "the existing longhorn storageclass doesn't have provisioner as driver.longhorn.io">: error calling fail: the existing longhorn storageclass doesn't have provisioner as driver.longhorn.io
   ```

**Comment by PhanLe1010** [comment]
## Test steps

### Kubectl apply -f
1. Install Longhorn v1.0.2
   ```
   kubectl apply -f https://github.com/longhorn/longhorn/blob/v1.0.2/deploy/longhorn.yaml
   ```
1. Create a statefulset using `longhorn` storageclass for PVCs. Set the scale to 1.
1. Observe that there is a workload pod (`pod-1`) is using 1 volume (`vol-1`) with 3 replicas.
1. In Longhorn manager repo, on `master` branch. Modify `numberOfReplicas: "1"` in `./deploy/install/01-prerequisite/06-storageclass`. Upgrade Longhorn to master by running
   ```
   kubectl apply -f deploy/install/ -R
   ```
1. Verify that `longhorn` storageclass now has the field `numberOfReplicas: 1`.
1. Scale up the deployment to 2. Verify that:
   * `pod-1` is using volume `vol-1` with 3 replicas.
   * `pod-2` is using volume `vol-2` with 1 replica.
1. Scale up the deployment to 0 then back to 2. Verify that:
   * `pod-1` is using volume `vol-1` with 3 replicas.
   * `pod-2` is using volume `vol-2` with 1 replica.

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master 10/29/2020

Validated the upgrade with kubectl, it is working fine. I'll update the result of the helm and rancher UI once validated.
