### ISSUE TITLE
[BUG] Deleting longhorn stuck in removing longhorn-system namespace

### ISSUE THREAD

**Issue by hendra-2020** [longhorn/longhorn#1529]
**Describe the bug**
I've installed longhorn in rke-based cluster through kubectl as described in https://longhorn.io/docs/1.0.0/deploy/install/install-with-kubectl/ with no issues. However, deleting through "kubectl delete -f longhorn.yaml" is always stuck at the very last step of deleting longhorn-system namespace. This makes it impossible to reinstall longhorn without reinstalling the cluster because longhorn-system namespace already exists.

**To Reproduce**
1. Get config file: curl -O -L https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
2. Edit longhorn.yaml's default-setting.yaml section: default-replica-count: "2"
3. Run: kubectl apply -f longhorn.yaml
4. Wait till "kubectl get pods -n longhorn-system" shows all pods running
5. Run: kubectl delete -f longhorn.yaml

**Expected behavior**
kubectl delete should complete successfully.

**Log**
There're no pods left in the namespace:
$ kubectl -n longhorn-system get pod
No resources found in longhorn-system namespace.

The longhorn-system namespace description shows terminating status:
$ kubectl describe ns longhorn-system
Name:         longhorn-system
Labels:       cattle.io/creator=norman
              field.cattle.io/projectId=p-cjkvg
Annotations:  cattle.io/status:
                {"Conditions":[{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2020-06-27T03:48:32Z"},{"Type":"ResourceQuot...
              field.cattle.io/creatorId: user-zzz2v
              field.cattle.io/projectId: c-hbtk8:p-cjkvg
              lifecycle.cattle.io/create.namespace-auth: true
Status:       Terminating

No resource quota.

No LimitRange resource.

**Environment:**
 - Longhorn version: 1.0.0
 - Kubernetes version: 1.18.3
 - Node OS type and version: Ubuntu 20.04

**Additional context**
Cluster is provisioned using RKE v1.1.3 on baremetal servers.

**Comment by hendra-2020** [comment]
I just realized a bug which is probably the same was just filed in rancher issue tracker: https://github.com/rancher/rancher/issues/27758.

**Comment by yasker** [comment]
You need to use app->uninstall instead of deleting the project/namespace directly. Longhorn has used finalizers to clean up the resources.

Because the resources cannot be cleaned up properly due to finalizers wasn't removed. See https://longhorn.io/docs/1.0.0/deploy/uninstall/

See https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#finalizers as well.

**Comment by hendra-2020** [comment]
Thank you for the clarification. Sorry I got used to just running kubectl delete and wasn't reading the docs completely.
