### ISSUE TITLE
[BUG]Failed to upgrade Longhorn in air-gapped network environment

### ISSUE THREAD

**Issue by HKMglicks** [longhorn/longhorn#1530]
**Describe the bug**
we were trying to upgrade longhorn from 0.8.0 to 0.8.1 then we were going to upgrade 0.8.1 to version 1 then we faced certain issue saying " Error starting manager: create not allowed while custom resource definition is terminating" please note that our environment is closed network which we don't have any access to the internet what so ever. However we can provide images to our system in another way.

**To Reproduce**
1. We added the .yaml file for 0.8.1 to the manager and we added the images to our Docker repository and we changed the images to pull from our Docker Repo. then we applied the yaml.
2. the manager pods keep on CrashLoopBackOff status and longhorn-driver-deployer is on init:0/1.
3. then we checked the pods using describe it started saying the following "readiness probe failed dial tcp connect connection refused"
4. when u enter the logs you will see the following " Error starting manager: create not allowed while custom resource definition is terminating"

**Expected behavior**
the manager pods will keep on CrashLoopBackOff and produce the following error in the log " Error starting manager: create not allowed while custom resource definition is terminating"

**Log**
kubectl logs -n longhorn longhorn-manager-ctf5l
time="2020-06-28T04:21:19Z" level=info msg="Start overwriting built-in settings with customized values"
time="2020-06-28T04:21:19Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: Failed to execute: nsenter [--mount=/host/proc/194797/ns/mnt --net=/host/proc/194797/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr, ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/*': No such file or directory\n, error exit status 2"
time="2020-06-28T04:21:19Z" level=info msg="New upgrade leader elected: ssdworker08"
time="2020-06-28T04:21:26Z" level=info msg="New upgrade leader elected: ssdworker03"
time="2020-06-28T04:21:47Z" level=info msg="Start upgrading"
time="2020-06-28T04:21:47Z" level=info msg="No API version upgrade is needed"
time="2020-06-28T04:21:47Z" level=info msg="Finish upgrading"
E0628 04:21:47.965636       1 leaderelection.go:282] Failed to release lock: Lease.coordination.k8s.io "longhorn-manager-upgrade-lock" is invalid: spec.leaseDurationSeconds: Invalid value: 0: must be greater than 0
time="2020-06-28T04:21:47Z" level=info msg="Upgrade leader lost: ssdworker01"
E0628 04:21:47.982995       1 kubernetes_node_controller.go:244] Couldn't get nodes ssdworker01: node "ssdworker01" not found 
E0628 04:21:47.984506       1 node_controller.go:526] Couldn't get node ssdworker01 for replica db-data-r-ee1d990d: node.longhorn.io "ssdworker01" not found 
time="2020-06-28T04:21:48Z" level=info msg="Start Longhorn Engine Image controller"
time="2020-06-28T04:21:48Z" level=info msg="Start kubernetes controller"
time="2020-06-28T04:21:48Z" level=info msg="Start Longhorn volume controller"
time="2020-06-28T04:21:48Z" level=info msg="Start Longhorn Kubernetes node controller"
time="2020-06-28T04:21:48Z" level=info msg="Start Longhorn node controller"
time="2020-06-28T04:21:48Z" level=info msg="Start Longhorn websocket controller"
time="2020-06-28T04:21:48Z" level=info msg="Start Longhorn replica controller"
time="2020-06-28T04:21:48Z" level=info msg="Start Longhorn engine controller"
time="2020-06-28T04:21:48Z" level=info msg="Starting Longhorn instance manager controller"
time="2020-06-28T04:21:48Z" level=info msg="Start Longhorn Setting controller"
time="2020-06-28T04:21:48Z" level=fatal msg="Error starting manager: create not allowed while custom resource definition is terminating"

kubectl -n longhorn describe po  longhorn-manager-ctf5l
Name:         longhorn-manager-ctf5l
Namespace:    longhorn
Priority:     0
Node:         ssdworker01/10.200.6.18
Start Time:   Sun, 28 Jun 2020 08:12:28 +0400
Labels:       app=longhorn-manager
              controller-revision-hash=765d55c979
              pod-template-generation=1
Annotations:  cni.projectcalico.org/podIP: 192.168.39.235/32
Status:       Running
IP:           192.168.39.235
IPs:
  IP:           192.168.39.235
Controlled By:  DaemonSet/longhorn-manager
Containers:
  longhorn-manager:
    Container ID:  docker://8ce0a11ead53711bcf5a17386d65d4ea3613d9c4f80f21fb7c2b0401bc00e9be
    Image:         10.200.6.10:5000/longhornio/longhorn-manager:v1.0.0
    Image ID:      docker-pullable://10.200.6.10:5000/longhornio/longhorn-manager@sha256:7e8dcfb5120828ef4379822ce13d751bf8575ea4f5df1b1404ba1c98994e723c
    Port:          9500/TCP
    Host Port:     0/TCP
    Command:
      longhorn-manager
      -d
      daemon
      --engine-image
      longhornio/longhorn-engine:v1.0.0
      --instance-manager-image
      longhornio/longhorn-instance-manager:v1_20200514
      --manager-image
      longhornio/longhorn-manager:v1.0.0
      --service-account
      longhorn-service-account
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sun, 28 Jun 2020 08:38:09 +0400
      Finished:     Sun, 28 Jun 2020 08:38:38 +0400
    Ready:          False
    Restart Count:  7
    Readiness:      tcp-socket :9500 delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAMESPACE:         longhorn (v1:metadata.namespace)
      POD_IP:                 (v1:status.podIP)
      NODE_NAME:              (v1:spec.nodeName)
      DEFAULT_SETTING_PATH:  /var/lib/longhorn-setting/default-setting.yaml
    Mounts:
      /host/dev/ from dev (rw)
      /host/proc/ from proc (rw)
      /var/lib/longhorn-setting/ from longhorn-default-setting (rw)
      /var/lib/longhorn/ from longhorn (rw)
      /var/run/ from varrun (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from longhorn-service-account-token-v7bb6 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/
    HostPathType:  
  proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc/
    HostPathType:  
  varrun:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/
    HostPathType:  
  longhorn:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/longhorn/
    HostPathType:  
  longhorn-default-setting:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      longhorn-default-setting
    Optional:  false
  longhorn-service-account-token-v7bb6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  longhorn-service-account-token-v7bb6
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason     Age                   From                  Message
  ----     ------     ----                  ----                  -------
  Normal   Scheduled  <unknown>             default-scheduler     Successfully assigned longhorn/longhorn-manager-ctf5l to ssdworker01
  Normal   Pulling    26m (x3 over 28m)     kubelet, ssdworker01  Pulling image "10.200.6.10:5000/longhornio/longhorn-manager:v1.0.0"
  Normal   Pulled     26m (x3 over 28m)     kubelet, ssdworker01  Successfully pulled image "10.200.6.10:5000/longhornio/longhorn-manager:v1.0.0"
  Normal   Started    26m (x3 over 28m)     kubelet, ssdworker01  Started container longhorn-manager
  Normal   Created    23m (x4 over 28m)     kubelet, ssdworker01  Created container longhorn-manager
  Warning  Unhealthy  8m58s (x67 over 28m)  kubelet, ssdworker01  Readiness probe failed: dial tcp 192.168.39.235:9500: connect: connection refused
  Warning  BackOff    3m58s (x50 over 26m)  kubelet, ssdworker01  Back-off restarting failed container
**Environment:**
 - Longhorn version: 0.8.1
 - Kubernetes version: 1.16.2
 - Node OS type and version: Ubuntu 16.0.4

**Additional context**
Please note we have closed networked which doesn't have access to the internet. Can you provide the best practice to deploy Longhorn on our Environment. if there proper to upgrade the system in an air-gapped  network.

**Comment by shuo-wu** [comment]
The manager pod crashing is caused by the lacking of engine image:
```
time="2020-06-28T04:21:19Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: Failed to execute: nsenter [--mount=/host/proc/194797/ns/mnt --net=/host/proc/194797/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/], output , stderr, ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/': No such file or directory\n, error exit status 2"
```

1. Actually all the following images will be used in Longhorn v0.8.1. Since some of the Longhorn workloads are provisioned dynamically,  you won't see the related images in the YAML files:
    1. longhornio/longhorn-manager:v0.8.1
    2. longhornio/longhorn-engine:v0.8.1
    3. longhornio/longhorn-ui:v0.8.1
    4. longhornio/longhorn-instance-manager:v1_20200301
    5. quay.io/k8scsi/csi-attacher:v2.0.0
    6. quay.io/k8scsi/csi-provisioner:v1.4.0
    7. quay.io/k8scsi/csi-resizer:v0.3.0
    8. quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
You can follow this doc to do air gap installation: https://longhorn.io/docs/0.8.1/advanced-resources/deploy/airgap/

2. Do not upgrade to the newer version if the v0.8.1 upgrade is not done.

**Comment by HKMglicks** [comment]
Hello Shuo

we are facing the same problem can provide us a way to remove longhorn so we can start installing it fresh from the start

Thanks 
Regards
Majid

**Comment by shuo-wu** [comment]
You can follow the uninstallation guide to remove Longhorn:
https://longhorn.io/docs/1.0.0/deploy/uninstall/#uninstalling-longhorn-using-kubectl

**If the namespace `longhorn-system` gets stuck in `Terminating` state** but there is nothing in that namespace after the uninstallation, you can try following commands  to clean up the leftovers:
```
curl -s https://raw.githubusercontent.com/longhorn/longhorn/v0.8.1/scripts/cleanup.sh |bash -s v062
curl -s https://raw.githubusercontent.com/longhorn/longhorn/v0.8.1/scripts/cleanup.sh |bash -s v070
```

**Comment by HKMglicks** [comment]
we finished cleaning up the system using Cleanup.sh 
however when running kubectl apply -f uninstall.yaml it is stuck on 0/1
Thanks
Regards
Majid

**Comment by shuo-wu** [comment]
If the namespace `longhorn-system` is gone, it means you have successfully cleaned up Longhorn then it's fine to directly remove the uninstall job.

**Comment by HKMglicks** [comment]
hello Shuo

the longhorn-system is stuck on terminating and saying the following:
"Error from server (Conflict): Operation cannot be fulfilled on namespaces "longhorn-system": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system."

thanks 

regards

**Comment by shuo-wu** [comment]
It seems that something still retains in the namespace. You can use `kubectl -n longhorn-system get pods` to check the possible Longhorn workloads first.
And I don't know why the uninstaller doesn't work for you. Is there any error info when the uninstaller gets stuck there?

**Comment by HKMglicks** [comment]
Hello shuo

this is what the job uninstaller is showing 
root@ssdmanager02:~/longhorn-master/uninstall# kubectl logs  job/longhorn-uninstall   
Error from server (BadRequest): container "longhorn-uninstall" in pod "longhorn-uninstall-5k5xm" is waiting to start: image can't be pulled
root@ssdmanager02:~/longhorn-master/uninstall# kubectl get job/longhorn-uninstall -w
NAME                 COMPLETIONS   DURATION   AGE
longhorn-uninstall   0/1           102s       102s
^Croot@ssdmanager02:~/longhorn-master/uninstall# kubectl describe job longhorn-uninstall
Name:                     longhorn-uninstall
Namespace:                default
Selector:                 controller-uid=966f4a28-5e8f-476e-8299-ebf1eb7c2aba
Labels:                   controller-uid=966f4a28-5e8f-476e-8299-ebf1eb7c2aba
                          job-name=longhorn-uninstall
Annotations:              kubectl.kubernetes.io/last-applied-configuration:
                            {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{},"name":"longhorn-uninstall","namespace":"default"},"spec":{"activeDeadl...
Parallelism:              1
Completions:              1
Start Time:               Thu, 02 Jul 2020 07:24:22 +0400
Active Deadline Seconds:  900s
Pods Statuses:            1 Running / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           controller-uid=966f4a28-5e8f-476e-8299-ebf1eb7c2aba
                    job-name=longhorn-uninstall
  Service Account:  longhorn-uninstall-service-account
  Containers:
   longhorn-uninstall:
    Image:      longhornio/longhorn-manager:v1.0.0
    Port:       <none>
    Host Port:  <none>
    Command:
      longhorn-manager
      uninstall
      --force
    Environment:
      LONGHORN_NAMESPACE:  longhorn-system
    Mounts:                <none>
  Volumes:                 <none>
Events:
  Type    Reason            Age   From            Message
  ----    ------            ----  ----            -------
  Normal  SuccessfulCreate  105s  job-controller  Created pod: longhorn-uninstall-5k5xm


Thanks hope we fix this issue
regards
Majid

**Comment by shuo-wu** [comment]
It seems that the job has created one pod to clean up the Longhorn system. How about the pod status?

**Comment by HKMglicks** [comment]
it is still 0/1 @shuo-wu and not making any progress

**Comment by shuo-wu** [comment]
All right... Since the longhorn workloads are almost gone, it's impossible to generate the support bundle for this uninstallation issue. Then I am not sure what's the root cause right now. The only thing I can do is helping you find a way to force removing Longhorn:
1. Run the command to see if there are still some CRDs containing the suffix `longhorn.io`:
```
kubectl get crd
```
e.g.,
```
# kubectl get crd
NAME                                          CREATED AT
......
engineimages.longhorn.io                      2020-07-08T08:52:25Z
engines.longhorn.io                           2020-07-08T08:52:23Z
......
```
If YES, please try/retry the following commands to clean up those CRDs:
```
curl -s https://raw.githubusercontent.com/longhorn/longhorn/v0.8.1/scripts/cleanup.sh |bash -s v062
curl -s https://raw.githubusercontent.com/longhorn/longhorn/v0.8.1/scripts/cleanup.sh |bash -s v070
```
2. Run the commands to delete the longhorn workloads directly:
```
kubectl delete -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
kubectl delete -f https://raw.githubusercontent.com/longhorn/longhorn/master/uninstall/uninstall.yaml
```
3. Wait and check if the namespace `longhorn-system` is removed.
```
kubectl get ns
```

**Comment by HKMglicks** [comment]
when running the cleanup.sh saying line 1 to 12 error command not found and yes CRD is there

Thanks

**Comment by shuo-wu** [comment]
Can you try to remove it manually?
1. For **each** CRD with suffix `longhorn.io`, list its objects:
```
kubectl -n longhorn-system get <CRD>
```
2. For **each listed** objects, remove the finalizer and directly delete it:
```
kubectl -n longhorn-system delete <CRD> <CRD object name>
kubectl -n longhorn-system patch -p '{"metadata":{"finalizers": []}}' --type=merge <CRD> <CRD object name>
```

**Comment by HKMglicks** [comment]
@shuo-wu thanks that was the answer and that was way to remove the stuck terminating namespace

**Comment by jonmahoney15** [comment]
> Can you try to remove it manually?
> 
> 1. For **each** CRD with suffix `longhorn.io`, list its objects:
> 
> ```
> kubectl -n longhorn-system get <CRD>
> ```
> 
> 2. For **each listed** objects, remove the finalizer and directly delete it:
> 
> ```
> kubectl -n longhorn-system delete <CRD> <CRD object name>
> kubectl -n longhorn-system patch -p '{"metadata":{"finalizers": []}}' --type=merge <CRD> <CRD object name>
> ```

Hi I am trying this same deletion technique for a volume that won't delete but I get this respone every time:

```
kubectl -n longhorn-system patch -p '{"metadata":{"finalizers": []}}' --type=merge volumes pvc-86b1884b-2a6f-443d-9930-ede9b6587a9e
Error from server (InternalError): Internal error occurred: failed calling webhook "validator.longhorn.io": failed to call webhook: Post "https://longhorn-admission-webhook.longhorn-system.svc:9443/v1/webhook/validaton?timeout=10s": service "longhorn-admission-webhook" not found

```

any suggestions would be greatly appreciated?
