### ISSUE TITLE
[BUG] High CPU usage when instance-manager-engine tries to shut down frontend device

### ISSUE THREAD

**Issue by Wykiki** [longhorn/longhorn#1533]
**Describe the bug**
Using Longhorn (have a 200 Gb volume via a storage class with 2 replicas), the `instance-manager-e-xxxx` pod on the main node tries to shut down frontend device, but fail, and it looks like it creates CPU Hog (`instance-manaeger-engine` reaching constant 2 CPU usage on a 4 CPUs instance).
But the volume keeps working.

**To Reproduce**
1. Fresh install of Longhorn
2. Have 3 Longhorn dedicated nodes to handle Longhorn volumes
3. Label nodes with tags `storage` and `slow`, then disks with tag `slow`
4. Create a new StorageClass (see below for details)
5. Provision a volume
6. Wait

**Expected behavior**
Have a low CPU usage from pod `instance-manager-e-xxxx` (lower than consuming 2 CPU)

**Log**
```
[longhorn-instance-manager] time="2020-06-29T06:49:51Z" level=info msg="wait for process pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78-e-bbfedf07 to shutdown"

[longhorn-instance-manager] time="2020-06-29T06:49:51Z" level=debug msg="Process Manager: wait for process pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78-e-bbfedf07 to shutdown before unregistering process"

[longhorn-instance-manager] time="2020-06-29T06:49:51Z" level=debug msg="Process Manager: wait for process pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78-e-bbfedf07 to shutdown before unregistering process"

[longhorn-instance-manager] time="2020-06-29T06:49:51Z" level=debug msg="Process Manager: wait for process pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78-e-bbfedf07 to shutdown before unregistering process"

[longhorn-instance-manager] time="2020-06-29T06:49:51Z" level=debug msg="Process Manager: wait for process pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78-e-bbfedf07 to shutdown before unregistering process"

[longhorn-instance-manager] time="2020-06-29T06:49:51Z" level=debug msg="Process Manager: wait for process pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78-e-bbfedf07 to shutdown before unregistering process"

[pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78-e-bbfedf07] time="2020-06-29T06:49:51Z" level=error msg="Error when shutting down frontend:device pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78: fail to stop SCSI device: Fail to logout target: Failed to execute: nsenter [--mount=/host/proc/1889/ns/mnt --net=/host/proc/1889/ns/net iscsiadm -m node -o delete -p 10.42.11.30 -T iqn.2019-10.io.longhorn:pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78], output , stderr, iscsiadm: This command will remove the record [iface: default, target: iqn.2019-10.io.longhorn:pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78, portal: 10.42.11.30,3260], but a session is using it. Logout session then rerun command to remove record.\niscsiadm: Could not execute operation on all records: session exists\n, error exit status 15"

time="2020-06-29T06:49:51Z" level=info msg="Closing: 10.42.9.32:10015"

[longhorn-instance-manager] time="2020-06-29T06:49:51Z" level=debug msg="Process Manager: wait for process pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78-e-bbfedf07 to shutdown before unregistering process"

[pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78-e-bbfedf07] time="2020-06-29T06:49:51Z" level=info msg="Closing: 10.42.10.27:10000"

[pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78-e-bbfedf07] time="2020-06-29T06:49:51Z" level=warning msg="Failed to execute hook github.com/longhorn/longhorn-engine/app/cmd.startController.func1: errors when shutting down controller: frontend: device pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78: fail to stop SCSI device: Fail to logout target: Failed to execute: nsenter [--mount=/host/proc/1889/ns/mnt --net=/host/proc/1889/ns/net iscsiadm -m node -o delete -p 10.42.11.30 -T iqn.2019-10.io.longhorn:pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78], output , stderr, iscsiadm: This command will remove the record [iface: default, target: iqn.2019-10.io.longhorn:pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78, portal: 10.42.11.30,3260], but a session is using it. Logout session then rerun command to remove record.\niscsiadm: Could not execute operation on all records: session exists\n, error exit status 15 backend: <nil>"

[longhorn-instance-manager] time="2020-06-29T06:49:51Z" level=info msg="wait for process pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78-e-bbfedf07 to shutdown"

[longhorn-instance-manager] time="2020-06-29T06:49:51Z" level=debug msg="Process Manager: wait for process pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78-e-bbfedf07 to shutdown before unregistering process"

[longhorn-instance-manager] time="2020-06-29T06:49:51Z" level=info msg="Process Manager: process pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78-e-bbfedf07 error out, error msg: exit status 1"

[longhorn-instance-manager] time="2020-06-29T06:49:51Z" level=debug msg="Process update: pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78-e-bbfedf07: state error: Error: exit status 1"

[longhorn-instance-manager] time="2020-06-29T06:49:51Z" level=info msg="Process Manager: successfully unregistered process pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78-e-bbfedf07"

[longhorn-instance-manager] time="2020-06-29T06:49:51Z" level=debug msg="Process update: pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78-e-bbfedf07: state error: Error: exit status 1"
```

**Environment:**
 - Longhorn version: 1.0.0
 - Kubernetes version: 1.14.6
 - Node OS type and version: RancherOS 1.5.4, with Ubuntu console

**Additional context**

## Storage Class

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  creationTimestamp: "2020-06-27T21:08:13Z"
  name: longhorn-slow
  resourceVersion: "184546402"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/longhorn-slow
  uid: 501789a2-b8ba-11ea-a8a5-06aa83693c38
allowVolumeExpansion: true
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  baseImage: ""
  diskSelector: slow
  fromBackup: ""
  nodeSelector: storage,slow
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
```

**Comment by shuo-wu** [comment]
There is something wrong with the ISCSI. Then the engine manager pod fails to create launch the volume and keeps trying to do ISCSI cleanup, which leads to the unexpected high CPU usage. 
```
[pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78-e-bbfedf07] time="2020-06-29T06:49:51Z" level=error msg="Error when shutting down frontend:device pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78: fail to stop SCSI device: Fail to logout target: Failed to execute: nsenter [--mount=/host/proc/1889/ns/mnt --net=/host/proc/1889/ns/net iscsiadm -m node -o delete -p 10.42.11.30 -T iqn.2019-10.io.longhorn:pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78], output , stderr, iscsiadm: This command will remove the record [iface: default, target: iqn.2019-10.io.longhorn:pvc-4b94793f-b98e-11ea-a3d9-06bcb1d17c78, portal: 10.42.11.30,3260], but a session is using it. Logout session then rerun command to remove record.\niscsiadm: Could not execute operation on all records: session exists\n, error exit status 15"
```

Since the reproducing step you provided above looks fine, we may need to verify if Longhorn still works fine on RancherOS 1.5.4 Unbuntu console + Kubernetes 1.14. 

You can directly send the support bundle to us if possible.

**Comment by Wykiki** [comment]
As I understand we should avoid RancherOS now as it's only receiving security fixes.
And follow recommended OSes from [Longhorn's best practices page](https://longhorn.io/docs/1.0.0/best-practices/).

I have another bug similar to this but I guess I'll wait for an update here before opening an issue.

Where should we send the support bundle ?

Thanks for your fast answer !

**Comment by shuo-wu** [comment]
You can send it to longhorn-support-bundle@rancher.com

**Comment by Wykiki** [comment]
UPDATE : In the same cluster, I uninstalled Longhorn to install it on Ubuntu nodes. And it seems to behave correctly.
No more High CPU usage when running Workload and Longhorn Volumes on Ubuntu nodes.

Details (not sure if helpful or clear enough) :

I have `worker` and `storage` nodes.
`worker` are Kubernetes worker nodes that only run pods and co.
`storage` are Kubernetes worker nodes that hosts Longhorn disks, and where the volumes are provisioned. It is possible to schedule Workload on those nodes if they meet tolerations, affinity...

With RancherOS on `worker` and `storage` nodes, I was able to provision Longhorn Volumes for Workloads when workload was scheduled on `storage` nodes only.

With RancherOS on `worker` and Ubuntu on `storage`, I was able to provision Longhorn Volumes for Workloads when workloads was scheduled on `storage` nodes only.

With Ubuntu on `worker` and `storage` nodes, I was able to provision Longhorn Volume for Workloads when workloads was scheduled on both `storage` and `worker` nodes.

**Comment by Wykiki** [comment]
This issue still occurs when having mixed nodes.

I was able to reproduce it with Ubuntu nodes only, it happened cause the node on which I tried to schedule the volume had taints, so it was not able to schedule on it.

But even after removing the volume, the instance-manager was still consuming a lot of CPUs, and needed a restart to stop the hog.

**Comment by yasker** [comment]
@Wykiki RancherOS is not officially supported by Longhorn.

Can you elaborate on how you reproduce it on the Ubuntu nodes? It would be great if you can provide a reproduce steps, so we can follow up and fix it in the upcoming release.

**Comment by Wykiki** [comment]
NOTE : I hit another problem, not the same as described above, but may be linked.

As it was hard giving all the steps to meet the initial cluster configuration, I started with new cluster :
- Rancher 2.4.5
- Kubernetes 1.18
- Longhorn 1.0.2
- OS Ubuntu 18.04

Cluster setup :
- 1 master node (etcd, controlplane) => `master-00`
- 2 storage nodes
  - => `sto-00` : no taints
  - => `sto-01` : tainted `longhorn=enabled:NoSchedule`
- 1 worker node with taint `os=ubuntu:NoSchedule` => `wrk-00`

Reproduction steps : 
- Create Longhorn project
- Install Longhorn
  - Default storage replica count : `2`
  - Kubernetes Taint Toleration : `longhorn=enabled:NoSchedule`
  - Everything else default
- Create a workload with no tolerations and a Longhron volume
  - It correctly schedule and able to access the volume
- Create another workload with tolerations `os=ubuntu:NoSchedule`
  - Got event `AttachVolume.Attach failed for volume "pvc-7a30b5b5-74b9-4f4d-b3fd-6ebd47ab8074" : node "ip-172-31-10-204" has no NodeID annotation`, node name corresponding to `wrk-00`

I can see that there is no `engine-image` on the `wrk-00` node. Could that be the problem ?

My goal here is to provision disk space only on `sto-00` and `sto-01`, but being able to schedule workload that need volume on other nodes that may have **taints**.

If I change Longhorn `Kubernetes Taint Toleration` to include the taint `os=ubuntu:NoSchedule`, I'm afraid that it may try to allocate space on nodes with that taint too.

I think that I could try to match the configuration mentionned in previous comments, but I will need a bit more time for this.

Thanks for reading !

**Comment by timmy59100** [comment]
You have change Longhorn `Kubernetes Taint Toleration` to include the taint `os=ubuntu:NoSchedule`. If you don't want to have volumes scheduled on the other node, you have to use Storage Tags:
https://longhorn.io/docs/1.0.2/volumes-and-nodes/storage-tags/

**Comment by Wykiki** [comment]
Ok thanks !

Anyway, I didn't succeed to reproduce the same bug as mentionned in the thread, so I guess this issue can be closed, I'll reopen one if I encounter this problem.

About RancherOS, I think that might be nice to mention that Longhorn does not work correctly on this OS, maybe on this page ? https://longhorn.io/docs/1.0.2/best-practices/
Even if you already mention Ubuntu and CentOS as recommended OS, the fact that Rancher supports RancherOS and Longhorn, and the Longhorn documentation not stating explicitly that RancherOS is not supported, make this kind of issue appear.

**Comment by yasker** [comment]
@Wykiki Thanks for the suggestion. Now we've added a section to call out unsupported OS in the doc: https://longhorn.io/docs/1.0.2/best-practices/#oses-arent-supported-by-longhorn .

**Comment by devthejo** [comment]
Is it okay to have Ubuntu console on RancherOS, or I have to switch to entirely to Ubuntu and leave RancherOS ?
(That would be very sad, because I worked hard on setup so many things with RancherOS and because I like it so much...)

**Comment by Wykiki** [comment]
Hello, I tried without Ubuntu console first and didn't work, then used Ubuntu console and still didn't work.

It's worth noting that Rancher seems to focus more on k3os instead of RancherOS, the latter only receiving security patch.

After all those problems with RancherOS (Longhorn one being one of a kind), we've decided to change to a more common Linux distribution (one of those mentioned in Longhorn doc)

**Comment by devthejo** [comment]
@Wykiki OK, thanks for your feedback.
RancherOS seems so exciting to me, I hope the project is not totally dead. I will take a look on k3os.

**Comment by devthejo** [comment]
It's not dead but I will be reassured when there will be more public reactiviy:
https://github.com/rancher/os/issues/3025
https://github.com/rancher/os/issues/3000

**Comment by HonakerM** [comment]
I'm having this same issue with the following setup:

Longhorn version: 1.2.3
Kubernetes version: 1.23.1
OS: Ubuntu 20.04

When I look at the node with high cpu I see a `tgtd` process utilizing 100% with errors very similar to those found here: https://github.com/longhorn/longhorn/issues/1533#issuecomment-651522821

**Comment by vavallee** [comment]
Same here, same versions.

**Comment by HonakerM** [comment]
@yasker could we reopen this issue or should I create a new one? I'm seeing the exact same errors as https://github.com/longhorn/longhorn/issues/1533#issuecomment-651522821

**Comment by shuo-wu** [comment]
> @yasker could we reopen this issue or should I create a new one? I'm seeing the exact same errors as [#1533 (comment)](https://github.com/longhorn/longhorn/issues/1533#issuecomment-651522821)

You can create a new GitHub issue with the logs (& the support bundle if possible) to track it.

**Comment by cod-r** [comment]
I have the same issue with 100% CPU usage by `tgtd` process.

Longhorn version: 1.2.3
Kubernetes version: 1.21.8
OS: Ubuntu 20.04.3

**Comment by innobead** [comment]
> 

cc @keithalucas @derekbit

**Comment by innobead** [comment]
> I have the same issue with 100% CPU usage by `tgtd` process.
> 
> Longhorn version: 1.2.3 Kubernetes version: 1.21.8 OS: Ubuntu 20.04.3

cc @keithalucas @derekbit

**Comment by HonakerM** [comment]
The cluster I was seeing this on actually had some unrelated critical failures so I lost the logs. @cod-r or @vavallee would one of you mind creating a new issue re: https://github.com/longhorn/longhorn/issues/1533#issuecomment-1038601469

**Comment by cod-r** [comment]
For me it happened on a freshly installed RKE cluster. 

I solved it by SIGKILL the `tgtd` processes on all nodes. One node had 3 `tgtd` processes.
After SIGKILL I had to delete and recreate the volumes because I was receiving `filesystem is readonly' messages.

If the problem appears again I'll open an issue

**Comment by HonakerM** [comment]
@shuo-wu I've created a new issue https://github.com/longhorn/longhorn/issues/3636#issue-1141651746 to track this
