### ISSUE TITLE
[BUG] Not able to access volume after reverting longhorn-nfs-provisioner volume 

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1535]
**Describe the bug**
1. User is not able to access volume in a pod if longhorn-nfs-provisioner volume is reverted to a snapshot before the pod was created.
2. Pod is not coming up healthy if longhorn-nfs-provisioner volume is reverted to a snapshot before pod creation.

**To Reproduce**
**Steps to reproduce the behavior:**
**Scenario 1:**
1. Set up longhorn-nfs-provisioner in longhorn.
2. Deploy a stateful set with ```longhorn-nfs``` storage class and write data to it.
3. Take a snapshot s1
4. Deploy another stateful set with ```longhorn-nfs``` storage class and write data to it.
5. Revert ```longhorn-nfs-provisioner``` volume to s1.
6. Enter into shell of 2nd pod, **volume is not accessible**.
```
root@wk-2-66894f94db-l7rb9:/# cd vol
bash: cd: vol: Stale file handle
```
**Scenario 2:**
1. Set up longhorn-nfs-provisioner in longhorn.
2. Deploy a stateful set with ```longhorn-nfs``` storage class and write data to it.
3. Take a snapshot s1
4. Deploy wordpress app with ```longhorn-nfs``` storage class.
5. Revert ```longhorn-nfs-provisioner``` volume to s1.
6. Wordpress workload fails to come up healthy and **stuck in ```CreateContainerConfigError```**. 
```
CreateContainerConfigError: failed to prepare subPath for volumeMount "wordpress-data" of container "wordpress"
```

**Log**
[longhorn-support-bundle_9cfa9e9d-07c3-43d7-8971-b319534d5e10_2020-06-30T06-54-50Z.zip](https://github.com/longhorn/longhorn/files/4849927/longhorn-support-bundle_9cfa9e9d-07c3-43d7-8971-b319534d5e10_2020-06-30T06-54-50Z.zip)

**Environment:**
 - Longhorn version: Master - 06-29-202
 - Kubernetes version: v1.18.3 
 - Node OS type and version: Ubuntu 18.04

**Comment by joshimoo** [comment]
This is to be expected, since the volume does not exist at the point in time when the backup S1 was taken.

**Comment by khushboo-rancher** [comment]
@joshimoo Will this be documented because user might create volumes after creating snapshot and later revert back to it ? They might wonder why the pods are not coming up healthy as PV/PVC will still there in system.

**Comment by yasker** [comment]
@khushboo-rancher It's a bit weird to document it since it's similar to say: if you revert back to a previous snapshot, you won't have the data written after the snapshot. This is an invalid case.

**Comment by khushboo-rancher** [comment]
@yasker Okay. 
In that case, we can close this issue.
