### ISSUE TITLE
[BUG] Longhorn-nfs-provisioner volume stuck in detaching state when attached node's connectivity is interrupted.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1536]
**Describe the bug**
Longhorn-nfs-provisioner volume stuck in detaching state when attached node's connectivity is interrupted.

**To Reproduce**
1. Set up nfs for rwx volume.
2. Interrupt the connectivity for 100 sec for the **attached node**. 
3. Longhorn-nfs-provisioner volume is stuck in **detaching state**.

**Expected behavior**
Volume should get attached to another node and become healthy.

**Log**
[longhorn-support-bundle_1afadc46-0939-4550-a23a-4723349159ce_2020-06-30T18-03-41Z.zip](https://github.com/longhorn/longhorn/files/4853692/longhorn-support-bundle_1afadc46-0939-4550-a23a-4723349159ce_2020-06-30T18-03-41Z.zip)

**Environment:**
 - Longhorn version: Master- 06-30-2020
 - Kubernetes version: v1.18.3 
 - Node OS type and version: Ubuntu 18.04

**Additional context**
The script used to interrupt the connectivity of the node. 
[network_down.sh.zip](https://github.com/longhorn/longhorn/files/4853693/network_down.sh.zip)

**Comment by joshimoo** [comment]
@shuo-wu this is unrelated to the nfs-provisioner, can you have a look?

**Comment by shuo-wu** [comment]
Which node do you disconnect? The node that the Longhorn volume attached to? Or the rwx volumes provisioned by the NFS provisioner? 
If it's the node that the Longhorn volume attached, does the related NFS provisioner get recreated after the disconnection?

**Comment by khushboo-rancher** [comment]
@shuo-wu The node attached to longhorn-nfs-provisioner volume was disconnected. The deployment longhorn-nfs-provisioner moved to other node but failed with volume attachment error
```
Unable to attach or mount volumes: unmounted volumes=[export-volume], unattached volumes=[export-volume longhorn-nfs-provisioner-token-4jrfq]: timed out waiting for the condition
```
The longhorn-nfs-provisioner volume name - pvc-7c266f88-40e3-4acd-9b72-1eceb1d31f84

**Comment by yasker** [comment]
Duplicate of #1545

**Comment by khushboo-rancher** [comment]
Verified on Master - 07-10-2020

Validation - **Passed**

On disconnecting the node for 100 secs, the ```longhorn-nfs-provisioner``` volume shows ```attached node down``` symbol then comes back healthy once the node is available.
