### ISSUE TITLE
[Question] How to setup maximal backup quantity for each pvc?

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1538]
How to setup maximal backup quantity for each pvc?

**Comment by joshimoo** [comment]
Currently we only support limiting the backup count for recurring backup jobs, the job will cleanup it's own oldest backups once the backup count is reached. Have a look at the documentation [here](https://longhorn.io/docs/1.0.0/snapshots-and-backups/scheduling-backups-and-snapshots/) on how to setup a recurring backup job.

**Comment by hillbun** [comment]
@joshimoo 

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  recurringJobs: '[
    { 
      "name":"snap", 
      "task":"snapshot", 
      "cron":"*/1 * * * *", 
      "retain":1
    },
    {
      "name":"backup", 
      "task":"backup", 
      "cron":"*/2 * * * *", 
      "retain":1
    }
  ]'
```

this is to setup for all pvc with longhorn storageclass?

how to setup for a specified pvc?

**Comment by hillbun** [comment]
@joshimoo 

it is possible to config recurringJobs to pvc?

I get errors

error: error validating "pvc.yaml": error validating data: ValidationError(PersistentVolumeClaim.spec): unknown field "recurringJobs" in io.k8s.api.core.v1.PersistentVolumeClaimSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by yasker** [comment]
@hillbun Kubernetes doesn't allow you to update parameters for separate PVCs, that's why this needs to be done at StorageClass level.

**Comment by joshimoo** [comment]
@hillbun see my message above, you can setup a recurring backup job for a longhorn volume via the longhorn UI.
https://longhorn.io/docs/1.0.0/snapshots-and-backups/scheduling-backups-and-snapshots/

For 1.1 we are also adding csi-snapshot support, so you could add your own cron job that would trigger and delete backups based on the csi `VolumeSnapshots` if you need to do all of this programmatically?

ref longhorn/longhorn#304
