### ISSUE TITLE
[FEATURE] PVC or Workload name visible in backup list section of Dashboard

### ISSUE THREAD

**Issue by HubbeKing** [longhorn/longhorn#1539]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to restore backups, as backups are primarily named according to the k8s PV - which have dynamically generated UUID-based names.

Currently, in order to restore a backup of a specific PVC, one has to either go through the volume section to find the volume in question, or if the volume no longer exists (i.e. if the volume has been accidentally deleted, or a new cluster is being spun up from backups) manually check each backup set to find the volume (or volumes) one wants to restore.

**Describe the solution you'd like**
Ideally, the "Backups" tab of the Longhorn UI Dashboard should display the PVC name or Workload name at time of last backup, so that one can identify backups at a glance. Both would provide useful information, as PVC names are typically automatically generated and can be a bit confusing unless Deployment/StatefulSet names have been chosen carefully.

If adding both the PVC name and Workload name to the Backups UI would clutter the UI too much, functionality to hide columns in the UI could be added to mitigate this.

Lastly, it should also be possible to sort the Backups listing according to PVC or Workload name.

**Describe alternatives you've considered**
As the primary means of interacting with Longhorn backups is the Longhorn UI Dashboard, I have not been able to come up with alternative solutions.

**Comment by yasker** [comment]
@smallteeths can you look into this to see if it's doable from UI side? Or if you need any help from the backend part.

**Comment by smallteeths** [comment]
Now the data returned by the /v1/backupvolumes interface does not contain the lastbackup pvc name and workloadname. If modify this issue without changing the backend, the frontend can only enter the backup page and send multiple requests to get the lastbackup pvc related information. The number of requests is the same as the number of volumes. This does not feel very reasonable. Can you directly return the information about pvc and workload on the /v1/backupvolumes @yasker

**Comment by yasker** [comment]
We can return the last backup's PVC/namespace/workload information in the backend API.

**Comment by joshimoo** [comment]
linking the backup refactor issue https://github.com/longhorn/longhorn/issues/1761
linking the application aware backup feature https://github.com/longhorn/longhorn/issues/2128

**Comment by jenting** [comment]
@smallteeths I added the Label `KubernetesStatus` to the  `/v1/backupvolumes` API, you could get the PVC, namespace, Workload/Pod name from it.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn master - `03/03/2021`

Validation - **Fail**

The PVC and workload is not appearing on the backup page, the titles are present but the values are always null.

<img width="1281" alt="Screen Shot 2021-03-04 at 11 02 10 PM" src="https://user-images.githubusercontent.com/60111667/110004856-e433a900-7d3d-11eb-93e8-396a5120d986.png">

The `backupvolumes` API doesn't have the status.
```
{
	"data": [{
		"actions": {
			"backupDelete": "https://rancher-server/v1/backupvolumes/volume-test-1?action=backupDelete",
			"backupGet": "https://rancher-server/v1/backupvolumes/volume-test-1?action=backupGet",
			"backupList": "https://rancher-server/v1/backupvolumes/volume-test-1?action=backupList"
		},
		"backingImageName": "",
		"backingImageURL": "",
		"backups": null,
		"baseImage": "",
		"created": "2021-03-01T13:57:17Z",
		"dataStored": "543162368",
		"id": "volume-test-1",
		"labels": null,
		"lastBackupAt": "2021-03-01T13:57:17Z",
		"lastBackupName": "backup-53a6c62b6573459e",
		"links": {
			"self": "https://rancher-server/v1/backupvolumes/volume-test-1"
		},
		"messages": {},
		"name": "volume-test-1",
		"size": "2147483648",
		"type": "backupVolume"
	}, {
		"actions": {
			"backupDelete": "https://rancher-server/v1/backupvolumes/volume-test-2?action=backupDelete",
			"backupGet": "https://rancher-server/v1/backupvolumes/volume-test-2?action=backupGet",
			"backupList": "https://rancher-server/v1/backupvolumes/volume-test-2?action=backupList"
		},
		"backingImageName": "",
		"backingImageURL": "",
		"backups": null,
		"baseImage": "",
		"created": "2021-03-01T13:57:51Z",
		"dataStored": "551550976",
		"id": "volume-test-2",
		"labels": null,
		"lastBackupAt": "2021-03-01T13:57:51Z",
		"lastBackupName": "backup-ded130a7fd21457f",
		"links": {
			"self": "https://rancher-server/v1/backupvolumes/volume-test-2"
		},
		"messages": {},
		"name": "volume-test-2",
		"size": "2147483648",
		"type": "backupVolume"
	}, {
		"actions": {
			"backupDelete": "https://rancher-server/v1/backupvolumes/volume-test-3?action=backupDelete",
			"backupGet": "https://rancher-server/v1/backupvolumes/volume-test-3?action=backupGet",
			"backupList": "https://rancher-server/v1/backupvolumes/volume-test-3?action=backupList"
		},
		"backingImageName": "",
		"backingImageURL": "",
		"backups": null,
		"baseImage": "",
		"created": "2021-03-04T15:41:37Z",
		"dataStored": "123731968",
		"id": "volume-test-3",
		"labels": null,
		"lastBackupAt": "2021-03-04T15:41:37Z",
		"lastBackupName": "backup-eb88b8d44d2d485e",
		"links": {
			"self": "https://rancher-server/v1/backupvolumes/volume-test-3"
		},
		"messages": {},
		"name": "volume-test-3",
		"size": "2147483648",
		"type": "backupVolume"
	}, {
		"actions": {
			"backupDelete": "https://rancher-server/v1/backupvolumes/volume-test-4?action=backupDelete",
			"backupGet": "https://rancher-server/v1/backupvolumes/volume-test-4?action=backupGet",
			"backupList": "https://rancher-server/v1/backupvolumes/volume-test-4?action=backupList"
		},
		"backingImageName": "",
		"backingImageURL": "",
		"backups": null,
		"baseImage": "",
		"created": "2021-03-04T15:42:36Z",
		"dataStored": "121634816",
		"id": "volume-test-4",
		"labels": null,
		"lastBackupAt": "2021-03-04T15:42:36Z",
		"lastBackupName": "backup-ee1760424c3f4c40",
		"links": {
			"self": "https://rancher-server/v1/backupvolumes/volume-test-4"
		},
		"messages": {},
		"name": "volume-test-4",
		"size": "1073741824",
		"type": "backupVolume"
	}],
	"links": {
		"self": "https://rancher-server/v1/backupvolumes"
	},
	"resourceType": "backupVolume",
	"type": "collection"
}
```

Steps I took:
1. Deploy Longhorn - master
2. Create a volume.
3. Set up S3 backupstore.
3. Take backup and check the backup list page.

**Comment by jenting** [comment]
> In the PVC column do we expect the PVC name or just the status as bound etc?

Display the `bound etc`, when mouse over, the PV/PVC information displayed, like this.
![image](https://user-images.githubusercontent.com/49380831/110053222-f04a5580-7d93-11eb-970a-5f0c9455a2ca.png)

**Comment by khushboo-rancher** [comment]
After discussing with @jenting we found that scenario of https://github.com/longhorn/longhorn/issues/1539#issuecomment-790797948 is upgrade case where the volumes were created with Longhorn v1.1.0.

Validation - **Pass** with Lognhorn-master

The PV/PVC and workloads are appearing on the backup page if the backup is taken with Longhorn-master.
<img width="1529" alt="Screen Shot 2021-03-05 at 9 50 39 AM" src="https://user-images.githubusercontent.com/60111667/110066780-45886600-7d98-11eb-8cea-ced6a4268d75.png">

For volumes and backups created with Longhorn prior versions, the PV/PVC and workload will appear only if a backup is taken with Longhorn - master.

To show PV/PVC and workload details for backups created with Longhorn prior versions, a S3 API call will be required which we think we should avoid at this moment. 
^^ @innobead @yasker

**Comment by yasker** [comment]
@khushboo-rancher it's fine if it only works for new backups, as long as  when user took a new backup for existing volumes they will see the additional information.

**Comment by khushboo-rancher** [comment]
Closing in favour of test `test_backup_kubernetes_status` has been passing in integration test nightly run.
