### ISSUE TITLE
Scan Longhorn related images automatically

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1542]
We should ensure the security of Longhorn's related docker images.

We can use tools like https://github.com/aquasecurity/trivy . We should notify the team about any high severity issues.

Thinking about if we want to do it using Jenkins, Drone, or GitHub Action.

**Comment by yasker** [comment]
We need to filter the HIGH severity issues.

**Comment by meldafrawi** [comment]
We can now filter scan results based on severity of the reported vulnerability.
![image](https://user-images.githubusercontent.com/18232258/89591010-66f89200-d849-11ea-95a9-d2f6f03cb1c6.png)

**Comment by yasker** [comment]
Done.
