### ISSUE TITLE
[BUG]Sometimes unexpected behaviors after node is recovered from the disconnection

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1545]
**Describe the bug**
When the node is back from the network disconnections **within a short period**(5~6mins), all pods on the node won't be evicted. Then some unexpected issues will be triggered. 
Scenario 1 (reproduce/always): 
The attached volume will become faulted, then get salvaged and reattached if the setting `auto-salvage` is enabled. 
Scenario 2 (reproduce/often): 
The volume engines on the recovered node won't be updated. This means the volumes on the node cannot be attached/detached/deleted successfully and get stuck there.

**To Reproduce**
Steps for Scenario 1:
1. Launch a Longhorn system.
2. Disable the setting `auto-salvage`.
3. Create and attach a volume.
4. Disconnect the node that volume attaches to for 100 seconds.
5. Wait for the node back.
6. All replicas become failed and the volume will become `Faulted`.

Steps for Scenario 2:
1. Launch a Longhorn system.
2. Create a volume.
3. Attach the volume then disconnect the node that volume attaches to for 100 seconds.
4. Wait for the node back and the volume update.
5. Repeat step 2~4 until the volume gets stuck in `Attached` or `Attaching` state rather than becoming `Healthy`. 
6. Create and attach more volumes to the recovered node. All volumes get stuck in `Attaching` state.
(If the result in step 5 is not shown after multiple retries (3 times for example), maybe you can remove the current Longhorn and redo the reproducing steps from the very beginning. I haven't found a way to always reproduce it)

**Expected behavior**
For Scenario 1:
The volume should be detached and reattached automatically and the replicas on the running nodes should be fine.
For Scenario 2:
The volumes on the recovered node should work fine.

**Environment:**
 - Longhorn version: v1.0.0
 - Kubernetes version: v1.17
 - Node OS type and version: Ubuntu 18.04

**Additional context**
1. The script used to disconnect a node: 
[network_down.sh.zip](https://github.com/longhorn/longhorn/files/4864127/network_down.sh.zip)

2. When the node is disconnected, the related engine manager will wrongly mark all replicas for all running engine processes as ERR due to the Ping-timeout error. After the engine manager pod is back, longhorn managers will get those wrong engine processes status then lead to the volumes becoming `Faulted`.

3. Scenario 2 may be the cause of the unexpected validation failures mentioned in #1327, #1536, #1451

**Comment by shuo-wu** [comment]
For Scenario 1, we can directly delete the related pod if the instance manager object becomes `Unknown`. Then longhorn manager pods won't accept wrong engine/replica info from the instance manager pod on the back node.

**Comment by shuo-wu** [comment]
Scenario 2 is caused by the **unexpected dead lock** in the engine controller after the node is back:
https://github.com/longhorn/longhorn-manager/blob/3879d122665f08841979516bfeb5ada6bcdaec14/controller/engine_controller.go#L313

Finally, the engine objects controlled by the back nodes won't be updated any more. And the volumes will get stuck in `Attaching` or `Detaching` state.

**Comment by joshimoo** [comment]
@shuo-wu great analysis :)

**Comment by yasker** [comment]
```
Steps for Scenario 1:

1. Launch a Longhorn system.
2. Disable the setting `auto-salvage`.
3. Create and attach a volume.
4. Disconnect the node that volume attaches to for 100 seconds.
5. Wait for the node back.
6. All replicas become failed and the volume will become `Faulted`.
```

This is might be expected? What caused the issue?

**Comment by shuo-wu** [comment]
> ```
> Steps for Scenario 1:
> 
> 1. Launch a Longhorn system.
> 2. Disable the setting `auto-salvage`.
> 3. Create and attach a volume.
> 4. Disconnect the node that volume attaches to for 100 seconds.
> 5. Wait for the node back.
> 6. All replicas become failed and the volume will become `Faulted`.
> ```
> 
> This is might be expected? What caused the issue?

This is the observation. The expectation for the result of step 6 is that the replicas on other nodes should still work fine without the auto salvage if there is no data writing during the disconnection.

**Comment by shuo-wu** [comment]
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [x] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The PR is at
https://github.com/longhorn/longhorn-manager/pull/617
https://github.com/longhorn/longhorn-manager/pull/619

* [x] Is the reproduce steps/test steps documented?

* [x] Which areas/issues this PR might have potential impacts on?
Area: manager
Issues: attachment/detachment stuck

* [x] ~~**If the fix introduces the code for backward compatibility** Has a separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~~

* [x] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at~~

* [x] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at~~

* [x] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~~

* [ ] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at

**Comment by khushboo-rancher** [comment]
Verified on Master - 07-10-2020

Validation - **Passed**

**Scenarios:**
1. **Disconnect the node for 100 secs** while restore is in progress. - Restoring volume got connected to other healthy node and completed the restore.
2. **Disconnect the node for 5 secs** while restore is in progress. - Restoring volume got connected to other healthy node and completed the restore.
3. **Reboot the node** while restore is in progress. - Restoring volume got connected to other healthy node and completed the restore.
4. **Poweroff the node** while restore is in progress. - Restoring volume got connected to other healthy node and completed the restore.
5. Scenario 2 from https://github.com/longhorn/longhorn/issues/1545#issue-649882585 - Volume didn't stuck in attaching state.
