### ISSUE TITLE
[FEATURE] Node/Disk tags and restoring backups

### ISSUE THREAD

**Issue by dragon2611** [longhorn/longhorn#1564]
Can you please make it possible to specify the node to attach the volume to when restoring from the backup, or use one of the tagged nodes during restore?

I have a small test K3s cluster where the nodes are in different DC's (Cheap VPSs) with currently between 5 and 20ms between them, they are connected via wireguard.

Originally I just let Longhorn schedule the volume where it liked but this isn't great performance wise due to the storage latency, so I decided to use node tags to pin the volumes to the node the pod will run on, in order to make this changed I backed up the volumes to backblaze b2 and then restored them (since you can't add tags to an existing volume).

When restoring the volume it attached it on a node 20ms from the one hosting the disk, ideally I would have liked it to attach it to the one with the disk in.

**Comment by yasker** [comment]
@dragon2611 which version you're using? In v1.0.0 we've supported restore with user-specified node/disk tags. Check the `restore` option in the UI.

**Comment by dragon2611** [comment]
@yasker Running1.0 and whilst restoring with a node label will place the data on the correct nodes it doesn't appear to control the node the volume gets mounted on (attached) to execute the restore job.

Ideally where possible one of the nodes that matches the node selector should also be the one that attaches the volume and pulls down the backup from the nfs/s3 location.

**Comment by yasker** [comment]
@dragon2611 If that's the case, don't worry about the attached node. The data doesn't flow from the attached node to the nodes that's running replicas when the restoring is happening. The controller on the attached node only issues commands for restore. The downloading from the backupstore is happening on the node you've selected for the volume via tags (a.k.a replicas).
