### ISSUE TITLE
AttachVolume.Attach failed for volume pvc  rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error][Question]

### ISSUE THREAD

**Issue by Ckopitc** [longhorn/longhorn#1565]
hello, 

i have deploy pv and pvc using longhorn, but when deploy pod mysql and wordpress error, i see error using ```kubestl describe pod (name pod)```, i have add new disk with ```/dev/sdb```
please help fixing this error 

this is the message given from pod added 

```Events:
  Type     Reason              Age                   From                       Message
  ----     ------              ----                  ----                       -------
  Normal   Scheduled           26m                   default-scheduler          Successfully assigned default/mysql-86b59656b7-wspkp to k8s-worker-node1
  Warning  FailedAttachVolume  8m21s                 attachdetach-controller    AttachVolume.Attach failed for volume "pvc-01c32834-8a89-46d3-a8b6-a60671e57a09" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [detail=, message=unable to attach volume pvc-01c32834-8a89-46d3-a8b6-a60671e57a09 to k8s-worker-node1: volume pvc-01c32834-8a89-46d3-a8b6-a60671e57a09 not scheduled, code=Server Error] from [http://longhorn-backend:9500/v1/volumes/pvc-01c32834-8a89-46d3-a8b6-a60671e57a09?action=attach]
  Warning  FailedAttachVolume  2m15s (x11 over 26m)  attachdetach-controller    AttachVolume.Attach failed for volume "pvc-01c32834-8a89-46d3-a8b6-a60671e57a09" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to attach volume pvc-01c32834-8a89-46d3-a8b6-a60671e57a09 to k8s-worker-node1: volume pvc-01c32834-8a89-46d3-a8b6-a60671e57a09 not scheduled] from [http://longhorn-backend:9500/v1/volumes/pvc-01c32834-8a89-46d3-a8b6-a60671e57a09?action=attach]```
--------------------------------------------------------------------------------
```apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi```
---------------------------------------------------------------------------------
```kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi```
---------------------------------------------------------------------------------
```NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                        STORAGECLASS   REASON   AGE
persistentvolume/pvc-01c32834-8a89-46d3-a8b6-a60671e57a09   10Gi       RWO            Delete           Bound    default/longhorn-volv-pvc    longhorn                53m
persistentvolume/pvc-7dfc64a3-a787-444d-b95f-a5bf9ebbe728   10Gi       RWO            Delete           Bound    default/longhorn-volv-pvc2   longhorn                53m

NAME                                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/longhorn-volv-pvc    Bound    pvc-01c32834-8a89-46d3-a8b6-a60671e57a09   10Gi       RWO            longhorn       54m
persistentvolumeclaim/longhorn-volv-pvc2   Bound    pvc-7dfc64a3-a787-444d-b95f-a5bf9ebbe728   10Gi       RWO            longhorn       53m```
----------------------------------------------------------------------------------
for all pod succes running, only pod mysql and wordpress cannot running

```NAMESPACE         NAME                                                  READY   STATUS              RESTARTS   AGE
default           my-release-ingress-nginx-controller-fb6674cf9-h7lgv   1/1     Running             1          6h37m
default           mysql-86b59656b7-wspkp                                0/1     ContainerCreating   0          49m
default           wordpress-59b8785cdd-5jbrh                            0/1     ContainerCreating   0          47m
kube-system       coredns-66bff467f8-cg97q                              1/1     Running             1          7h11m
kube-system       coredns-66bff467f8-l9gm5                              1/1     Running             1          7h11m
kube-system       etcd-k8s-master                                       1/1     Running             5          7h12m
kube-system       kube-apiserver-k8s-master                             1/1     Running             4          7h12m
kube-system       kube-controller-manager-k8s-master                    1/1     Running             2          7h12m
kube-system       kube-flannel-ds-amd64-mdz54                           1/1     Running             1          7h8m
kube-system       kube-flannel-ds-amd64-rk29s                           1/1     Running             2          7h6m
kube-system       kube-flannel-ds-amd64-tl6x8                           1/1     Running             2          7h6m
kube-system       kube-proxy-7vpz9                                      1/1     Running             1          7h6m
kube-system       kube-proxy-dww4z                                      1/1     Running             1          7h11m
kube-system       kube-proxy-jq9r6                                      1/1     Running             1          7h6m
kube-system       kube-scheduler-k8s-master                             1/1     Running             2          7h12m
longhorn-system   csi-attacher-5cc849c8dd-7gnhz                         1/1     Running             0          50m
longhorn-system   csi-attacher-5cc849c8dd-q7vd7                         1/1     Running             0          50m
longhorn-system   csi-attacher-5cc849c8dd-swts2                         1/1     Running             0          50m
longhorn-system   csi-provisioner-74557755-64h44                        1/1     Running             0          50m
longhorn-system   csi-provisioner-74557755-8dxnm                        1/1     Running             0          50m
longhorn-system   csi-provisioner-74557755-xdp2d                        1/1     Running             0          50m
longhorn-system   csi-resizer-686bd4b6d7-2w9lv                          1/1     Running             0          50m
longhorn-system   csi-resizer-686bd4b6d7-k76hp                          1/1     Running             0          50m
longhorn-system   csi-resizer-686bd4b6d7-srnfp                          1/1     Running             0          50m
longhorn-system   engine-image-ei-eee5f438-8n8gq                        1/1     Running             0          50m
longhorn-system   engine-image-ei-eee5f438-xj78w                        1/1     Running             0          50m
longhorn-system   instance-manager-e-2ca7231b                           1/1     Running             0          50m
longhorn-system   instance-manager-e-b2b0e324                           1/1     Running             0          50m
longhorn-system   instance-manager-r-4f2d3616                           1/1     Running             0          50m
longhorn-system   instance-manager-r-c1cc9f0a                           1/1     Running             0          50m
longhorn-system   longhorn-csi-plugin-88pxn                             2/2     Running             0          50m
longhorn-system   longhorn-csi-plugin-skklf                             2/2     Running             0          50m
longhorn-system   longhorn-driver-deployer-cd74cb75b-2lbrx              1/1     Running             0          51m
longhorn-system   longhorn-manager-ctd68                                1/1     Running             0          51m
longhorn-system   longhorn-manager-fgrpp                                1/1     Running             0          51m
longhorn-system   longhorn-ui-8486987944-wpwpg                          1/1     Running             0          51m
metallb-system    controller-57f648cb96-lwlh2                           1/1     Running             1          6h45m
metallb-system    speaker-b9w4d                                         1/1     Running             1          6h45m
metallb-system    speaker-lk5fm                                         1/1     Running             2          6h45m
metallb-system    speaker-wfwrv                                         1/1     Running             1          6h45m
```
thankyou
please help fixing this error

**Comment by Ckopitc** [comment]
for service success running 

```kubernetes                                      ClusterIP      10.96.0.1       <none>            443/TCP                      7h23m
my-release-ingress-nginx-controller             LoadBalancer   10.98.215.176   192.168.100.240   80:31468/TCP,443:31470/TCP   6h48m
my-release-ingress-nginx-controller-admission   ClusterIP      10.111.39.139   <none>            443/TCP                      6h48m
mysql                                           ClusterIP      10.98.3.112     <none>            3306/TCP                     57m
wordpress                                       LoadBalancer   10.103.66.0     192.168.100.241   80:31992/TCP                 57m
```

**Comment by Ckopitc** [comment]
this version 
```Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by mseewooth** [comment]
Hi , 

Same error here , lets hope someone can save us .

**Comment by Kamaroth92** [comment]
Are you running in a single node cluster? If so change the default replica count in the longhorn storageclass to one replica and try create the volume/pvc again. You can also confirm this in the Longhorn UI by going to Volume --> Your bound volume, and checking if it's failing due to the replicas.

**Comment by shuo-wu** [comment]
@Kamaroth92 Nice response!

It seems that there are only 2 worker nodes for the Longhorn system. 

You can choose one of the following solutions to fix this issue:
1. Enable the setting `Replica Node Level Soft Anti-Affinity`.
2. Create one more StorageClass by copying the default StorageClass but decreasing the parameter `numberOfReplicas` value. 
    - The parameters of the existing StrogeClass are immutable after the deployment hence you cannot directly modify the default StorageClass.
    -  The parameter `numberOfReplicas` cannot be greater than the worker node number when the setting `Replica Node Level Soft Anti-Affinity` is disabled

BTW, I could recommend checking the [doc]((https://longhorn.io/docs/1.0.0/references/settings/#replica-node-level-soft-anti-affinity)) of the setting `Replica Node Level Soft Anti-Affinity` before applying the solution. It would help you understand why this issue gets triggered.

**Comment by boknowswiki** [comment]
@Ckopitc  and @mseewooth,

Just an add-on @shuo-wu 's comment:
From the log: `volume pvc-01c32834-8a89-46d3-a8b6-a60671e57a09 not scheduled` means the scheduler failed to find the correct node for this volume, and usually it may because of the capacity and the Node or Zone Affinity settings, I put the scheduling document [Longhorn scheduling doc](https://longhorn.io/docs/1.0.0/volumes-and-nodes/scheduling/) please take a look.

**Comment by silhouette** [comment]
Same error here with 3 worker nodes for Longhorn system. I deployed the examle "pod with pvc":

# kubectl apply -f pod_with_pvc.yaml
persistentvolumeclaim/longhorn-volv-pvc created
pod/volume-test created

This is what I get from the logs:

# kubectl describe pod volume-test
Name:         volume-test
Namespace:    default
Priority:     0
Node:         dev-kube05/10.8.0.155
Start Time:   Thu, 16 Jul 2020 12:13:33 +0200
Labels:       <none>
Annotations:  kubernetes.io/psp: default-psp
Status:       Pending
IP:
IPs:          <none>
Containers:
  volume-test:
    Container ID:
    Image:          nginx:stable-alpine
    Image ID:
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Liveness:       exec [ls /data/lost+found] delay=5s timeout=1s period=5s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /data from volv (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-7g4kf (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  volv:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  longhorn-volv-pvc
    ReadOnly:   false
  default-token-7g4kf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-7g4kf
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason              Age                  From                     Message
  ----     ------              ----                 ----                     -------
  Warning  FailedScheduling    <unknown>            default-scheduler        running "VolumeBinding" filter plugin for pod "volume-test": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling    <unknown>            default-scheduler        running "VolumeBinding" filter plugin for pod "volume-test": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled           <unknown>            default-scheduler        Successfully assigned default/volume-test to dev-kube05
  Warning  FailedAttachVolume  2m33s                attachdetach-controller  AttachVolume.Attach failed for volume "pvc-0c4492bd-ba65-47df-affb-150577ec6502" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount         46s                  kubelet, dev-kube05      Unable to attach or mount volumes: unmounted volumes=[volv], unattached volumes=[volv default-token-7g4kf]: timed out waiting for the condition
  Warning  FailedAttachVolume  26s (x8 over 2m33s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-0c4492bd-ba65-47df-affb-150577ec6502" : rpc error: code = Aborted desc = The volume pvc-0c4492bd-ba65-47df-affb-150577ec6502 is attaching


Support-Bundle is attached.

[longhorn-support-bundle_979abc5c-bddf-4f44-9649-8003876c43be_2020-07-16T10-26-02Z.zip](https://github.com/longhorn/longhorn/files/4930869/longhorn-support-bundle_979abc5c-bddf-4f44-9649-8003876c43be_2020-07-16T10-26-02Z.zip)

**Comment by yasker** [comment]
@silhouette What are your node OS?

**Comment by silhouette** [comment]
@yasker Ubuntu 18.04.4. Filesystem is ext4.

**Comment by yasker** [comment]
@silhouette can you ping me in the slack channel when you have time? we want to take a deep look into this case.

**Comment by silhouette** [comment]
The problem could be solved in my case, /var/lib/longhorn was a symlink and this symlink caused problems. Solved it with the help of @yasker by removing the symlink and reinstalling the longhorn app.

**Comment by ashish-somani-c3ai** [comment]
> The problem could be solved in my case, /var/lib/longhorn was a symlink and this symlink caused problems. Solved it with the help of @yasker by removing the symlink and reinstalling the longhorn app.

How did you resolve this?? I am facing a symlink issue.
