### ISSUE TITLE
[BUG] Cannot attached a Longhorn volume on a Pod running on DigitalOcean managed cluster

### ISSUE THREAD

**Issue by lucj** [longhorn/longhorn#1566]
**Describe the bug**

Longhorn volume cannot be attached to a pod running on DigitalOcean.

**To Reproduce**

1. Create a DigitalOcean managed cluster

2. Install longhorn

````
$ kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
````

3. Create a PVC using "longhorn" storageclass

````
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-block
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
````

4. Create a mongo deployment

````
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo:4
        name: db
        volumeMounts:
        - mountPath: /data/db
          name: db
      restartPolicy: Always
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: mongo-block
````

5. PVC / PV correctly created

````
k get pvc,pv
NAME                                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/mongo-block   Bound    pvc-0229c406-1f27-48ae-b039-eb00d14ba0a1   5Gi        RWO            longhorn       44m

NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                 STORAGECLASS   REASON   AGE
persistentvolume/pvc-0229c406-1f27-48ae-b039-eb00d14ba0a1   5Gi        RWO            Delete           Bound    default/mongo-block   longhorn                43m
````

6. Mongo pod cannot be deployed

````
$ kubectl get pods | grep mongo
mongo-674675df9d-8p2n6          0/1     ContainerCreating   0          39m
````

7. Volume cannot be mounted / attached

````
 Warning  FailedMount         2m32s (x4 over 38m)  kubelet, pool-imr5owcga-3oa3q  Unable to attach or mount volumes: unmounted volumes=[db], unattached volumes=[default-token-ffzwq db]: timed out waiting for the condition
  Warning  FailedAttachVolume  118s (x19 over 40m)  attachdetach-controller        AttachVolume.Attach failed for volume "pvc-0229c406-1f27-48ae-b039-eb00d14ba0a1" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to attach volume pvc-0229c406-1f27-48ae-b039-eb00d14ba0a1 to pool-imr5owcga-3oa3q: volume pvc-0229c406-1f27-48ae-b039-eb00d14ba0a1 not scheduled] from [http://longhorn-backend:9500/v1/volumes/pvc-0229c406-1f27-48ae-b039-eb00d14ba0a1?action=attach]
  Warning  FailedMount         17s (x14 over 36m)   kubelet, pool-imr5owcga-3oa3q  Unable to attach or mount volumes: unmounted volumes=[db], unattached volumes=[db default-token-ffzwq]: timed out waiting for the condition
````

**Expected behavior**

Longhorn volume mounted on the Mongo Pod

**Environment:**
 - Longhorn version: 1.0.0
 - Kubernetes version: 1.18.3
 - Node OS type and version: DigitalOcean Managed Kubernetes

**Comment by shuo-wu** [comment]
How many worker nodes in your cluster that running longhorn? If the node number is **less than 3** and the **setting `Replica Node Level Soft Anti-Affinity` is disabled**, you cannot attach the volume created by the default StorageClass `longhorn`.

If that's the reason, you can choose one of the following solutions to fix this issue:
1. Enable the setting `Replica Node Level Soft Anti-Affinity`. (You can refer to [this doc](https://longhorn.io/docs/1.0.0/references/settings/#replica-node-level-soft-anti-affinity) for more details)
2. Create one more StorageClass by copying the default StorageClass but decreasing the parameter `numberOfReplicas` value. 
    - The parameters of the existing StrogeClass are immutable after the deployment hence you cannot directly modify the default StorageClass.
    -  The parameter `numberOfReplicas` cannot be greater than the worker node number when the setting `Replica Node Level Soft Anti-Affinity` is disabled

**Comment by boknowswiki** [comment]
Just an add-on @shuo-wu 's comment:
From the log: `volume pvc-0229c406-1f27-48ae-b039-eb00d14ba0a1 not scheduled` means the scheduler failed to find the correct node for this volume, and usually it may because of the capacity and the Node or Zone Affinity settings, I put the scheduling document [Longhorn scheduling doc](https://longhorn.io/docs/1.0.0/volumes-and-nodes/scheduling/) please take a look.

**Comment by lucj** [comment]
@shuo-wu @boknowswiki thanks a lot for those information. You’re right, my cluster only has 2 worker nodes. I’m sorry, I should have figured out the replicas number vs number of nodes. 

Just out of curiosity... I remember deploying Longhorn (pre GA though) on a single node K3s without having this error message. Was that possible before the GA release?

Thanks a lot for your help.

**Comment by boknowswiki** [comment]
@lucj ,

No worries. And yes it's possible, since before GA release, we enable the soft node level anti-affinity as default, but in GA(v1.0.0) we changed it.

[v1.0.0 node level default setting](https://longhorn.io/docs/1.0.0/references/settings/#replica-node-level-soft-anti-affinity)
[v0.8.1 node level default setting](https://longhorn.io/docs/0.8.1/references/settings/#replica-soft-anti-affinity)

**Comment by lucj** [comment]
Changing number of worker from 2 to 3 and it works like a charm :)
Thanks @boknowswiki @shuo-wu
