### ISSUE TITLE
[FEATURE] Support node/disk tag selection for DR volume

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1567]
It should be only a UI change since DR volume creation is the same as restore/new volume creation.

**Comment by khushboo-rancher** [comment]
Verified on longhorn master ```db932ec``` - 07-14-2020

Validation - **Passed**

Node/disk tags selection is available on clicking create DR volume either from the button or the dropdown option in the rows of backups.

Tested the functionality of node/disk tag with and without anti soft affinity setting .
