### ISSUE TITLE
Does longhorn has capability to identify all secondary disk attached to nodes and format them

### ISSUE THREAD

**Issue by asmi10** [longhorn/longhorn#1568]
Is there a way if longhorn can identify secondary disks attached to the node and based on the disk name mentioned in disks configuration create a filesystem on top of it and then mount it to dir mentioned in disks configuration?

**Comment by yasker** [comment]
No.

Also, automatic format based on the disk name is risky because there is no guarantee after the node reboots, the disk name (I guess what you meant is `/dev/sdxx`) will remain the same.
