### ISSUE TITLE
[BUG] UI: Backup list page is blank on latest master

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#1571]
**Describe the bug**
Backup list page is blank on latest master  `commit: db932ec`

**To Reproduce**
1. Create a volume attach it to a node, create a backup
2. In Backup page, click on volume backup name.
3. Backup list page is blank

**Expected behavior**
Backup list page should list backups for the volume 

**Log**
N/A

**Environment:**
 - Longhorn version: master
 - Kubernetes version: 1.18.3
 - Node OS type and version: Ubuntu 18.04

**Additional context**
N/A

**Comment by khushboo-rancher** [comment]
Till commit id ```5aad1c5```, the backup page is working fine.
Commit id ```db932ec``` might be be the reason of the failure.

**Comment by khushboo-rancher** [comment]
Verified on Master - ```34346ef```

Validation - **Passed**

Backup page is listing the backups.
