### ISSUE TITLE
tests: Fix longhorn night test failure on 'test_dr_volume_with_last_backup_deletion' test case

### ISSUE THREAD

**Issue by boknowswiki** [longhorn/longhorn#1572]
This issue is for tracking fix for test case 'test_dr_volume_with_last_backup_deletion'

**Comment by joshimoo** [comment]
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [x] ~~Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The PR is at~~

* [x] ~~Is the reproduce steps/test steps documented?~~

* [x] ~~Which areas/issues this PR might have potential impacts on?
Area
Issues~~

* [x] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~~

* [x] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at~~

* [x] **If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is this one itself.

* [x] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~~

* [x] ~~**if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at~~

**Comment by meldafrawi** [comment]
test `test_dr_volume_with_last_backup_deletion` Pass
