### ISSUE TITLE
[FEATURE] show pvc name in UI

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1578]
PVC Name:miop-zs-dev-elasticsearch-data-volv-pvc
PV Name:pvc-18545714-5d23-40ba-9efc-f7a99e53fcf3

it only show PV Name, no  PVC Name currently.

**Comment by shuo-wu** [comment]
The PVC name, Workload info, and the namespace of the volume are already shown in the UI volume detail page as long as they are using the volume.

**Comment by hillbun** [comment]
@shuo-wu 

But show PVC name in list view page is more convenient to users.

thanks

**Comment by shuo-wu** [comment]
There is a tooltip/hover presenting both PV and PVC name in the volume list page.
![Screen Shot 2020-07-16 at 12 41 22 PM](https://user-images.githubusercontent.com/47542419/87627688-d7882380-c761-11ea-8300-c42230d38ed0.png)

@yasker Do we still need to add one more column to explicitly present the info in the volume list page?

**Comment by yasker** [comment]
The reason we're using tooltip is that there are too many columns in the list already. Maybe in the future we can show the PVC name separately if we completely let user define what fields they want to see in the list. But it will be hard for us to show it in the list page directly now - especially PVC names are tend to be very long.
