### ISSUE TITLE
[Question] is it possible to initialize pvc without lost+found directory?

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1580]
I create pvc for mysql data storage, but get error

[ERROR] --initialize specified but the data directory has files in it. Aborting.

is it possible to initialize pvc without lost+found directory?

**Comment by shuo-wu** [comment]
You can refer to #913
Now Longhorn supports filesystem `xfs`. You can choose `xfs` to avoid this directory.

**Comment by afeiszli** [comment]
Just encountered this issue as well....how do we choose xfs? I don't see that in the docs.

**Comment by boknowswiki** [comment]
Based on [longhorn example storageclass.yaml](https://raw.githubusercontent.com/longhorn/longhorn/master/examples/storageclass.yaml), you can add `parameters` `fstype: xfs`. Like this
`kind: StorageClass                                                              
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  fstype: xfs 
  numberOfReplicas: "3" 
  staleReplicaTimeout: "3000"`

And the mount point you got from the pod should be `xfs` type. Please let us know if there is any problem. Thanks.

**Comment by hillbun** [comment]
what's difference between xfs and ext4?

**Comment by shuo-wu** [comment]
> @shuo-wu Just encountered this issue as well....how do we choose xfs? I don't see that in the docs.

Besides the StorageClass modification mentioned above, you can 
1. Choose `XFS` when you use Longhorn UI to create PV/PVC for a Longhorn volume. Then later the pod using the PV/PVC will mount the Longhorn volume with `xfs` filesystem.
![Screen Shot 2020-08-13 at 2 07 42 PM](https://user-images.githubusercontent.com/47542419/90100071-79555d00-dd6e-11ea-878a-d39b7adbdf1d.png)
![Screen Shot 2020-08-13 at 2 07 56 PM](https://user-images.githubusercontent.com/47542419/90100080-7e1a1100-dd6e-11ea-8d1d-3cae290e05b5.png)
2. Or you can modify [this field](https://github.com/longhorn/longhorn-manager/blob/03afb06da814659c4a9a6682fbbf5a74be7554d5/examples/csi/example_pv.yaml#L15) to `xfs` if you prefer to create PV/PVC for Longhorn volumes by yourself.

**Comment by shuo-wu** [comment]
> what's difference between xfs and ext4?

For this issue, the filesystem `xfs` doesn't contain any directory/file after formatting. If some users prefer a clean mount point/directory after the mounting, they can choose `xfs`.
If you want to know the feature or performance differences between these 2 filesystems, you can directly google it. There are a lot of articles or comments about this topic.

**Comment by boknowswiki** [comment]
Also one more thing, Longhorn supports auto remount for ext4 filesystem, but xfs filesystem doesn't have this support. [Here remount doc](https://longhorn.io/docs/0.8.1/high-availability/recover-volume/#remount) has more details. Thanks.

**Comment by lknite** [comment]
```
# storageclasses.storage.k8s.io "longhorn" was not valid:
# * parameters: Forbidden: updates to parameters are forbidden.
```

**Comment by derekbit** [comment]
> When attempting to add 'fstype: xfs' to parameters of storage class:
> 
> ```
> # storageclasses.storage.k8s.io "longhorn" was not valid:
> # * parameters: Forbidden: updates to parameters are forbidden.
> ```
> 
> v1.3.0

Can you create a new storageclass with `fstype: xfs` rather than update a existing one?

**Comment by lknite** [comment]
Confirmed, using 'fstype: xfs' has worked for me to resolve this issue.
