### ISSUE TITLE
[BUG] longhorn-manager - exec user process caused "permission denied"

### ISSUE THREAD

**Issue by destanyinside** [longhorn/longhorn#1586]
**Describe the bug**
longhorn helm chart
Error when pod with longhorn-manager start:
standard_init_linux.go:211: exec user process caused "permission denied"

**To Reproduce**
1. Edit values.yaml - change image.longhorn by my local registry. defaultSettings.registrySecret and privateRegistry
2. run - helm install longhorn ./longhorn --debug --namespace longhorn-system
3. In longhorn-manager pod logs:
standard_init_linux.go:211: exec user process caused "permission denied"

**Expected behavior**
Start pod

**Log**
standard_init_linux.go:211: exec user process caused "permission denied"

**Environment:**
 - Longhorn version: v1.0.0
 - Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:31:31Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
 - Node OS type and version: Red Hat Enterprise Linux Server release 7.7 (Maipo)
   Kernel: Linux 3.10.0-1062.9.1.el7.x86_64 #1 SMP Mon Dec 2 08:31:54 EST 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by shuo-wu** [comment]
@ttpcodes Is this also related to #608?

**Comment by yasker** [comment]
It doesn't look like a Longhorn specific problem. Have you enabled SELinux so maybe it imposed some policies? Search for `standard_init_linux.go:211: exec user process caused "permission denied"` yields lots of information on the topic but my bet is on SELinux for now.

**Comment by destanyinside** [comment]
@yasker SELinux in permissive mode

**Comment by destanyinside** [comment]
Sorry? it's my error.
Mount /var/lib/docker in /ets/fstab, was created with noexec option. After delete and remount -"mount -o remount /var/lib/docker" and restart docker daemon, it's works!
