### ISSUE TITLE
test: CI integration for website and automation test doc

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1588]
So we can update https://longhorn.github.io/longhorn-tests/ automatically.

**Comment by ttpcodes** [comment]
## Pre-merged Checklist
* [X] Does the PR include the explanation for the fix or the feature?

* [X] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The PRs are at longhorn/longhorn-tests#371 and longhorn/longhorn-tests#373.

* [X] Is the reproduce steps/test steps documented?

* [X] Which areas/issues this PR might have potential impacts on?
Areas: pm
Issues: #1588

* [X] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?~~

* [X] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~

* [X] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?~~

* [X] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?~~

* [X] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?~~

* [X] ~~**if labeled: require/manual-test-plan** Has the manual test plan been documented?~~

**Comment by ttpcodes** [comment]
On all merges into longhorn-tests, any changes made to the tests that would either result in a change in the generated integration test docs or a change in the manual test pages will result in a new version of the Hugo site being built, committed to `gh-pages`, and made public [here](https://longhorn.github.io/longhorn-tests).

**Comment by khushboo-rancher** [comment]
Validation - **Passed**

https://longhorn.github.io/longhorn-tests/ integration and manual tests are getting updated on merge.
