### ISSUE TITLE
[BUG] Can not list mounted directory

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1595]
```
df -h |grep data
/dev/longhorn/pvc-0d84e661-14f1-428c-8ce7-02357e910fe5  9.8G   37M  9.8G   1% /data
```

```
ls /data
ls: reading directory /data: Input/output error
```

any advice?

**Comment by joshimoo** [comment]
@hillbun Do you have a liveness probe on this pod that checks `ls /data`?
This might have happened in the case where no liveness probe is setup and the longhorn-engine responsible for that volume crashed.
Then the mount might no longer be valid after reattachment of the longhorn volume.
In that case a (restart, recreation, scale down/scale up) of the pod should fix the issue?

Hard to diagnose with this amount of information.

**Comment by hillbun** [comment]
@joshimoo 

restart solved this problem.

How to get pvc attached stablely?   if pvc attached crashed, pod auto restart?

**Comment by joshimoo** [comment]
@hillbun In the case of a liveness probe failure, the pod will be restarted. You you add a liveness probe to the workload pod, that will evaluate whether the volume is available and working. You can find an example in the documentation [here](https://longhorn.io/docs/1.0.0/high-availability/recover-volume/#automatically-remount-volumes-and-restart-workloads)

**Comment by hillbun** [comment]
@joshimoo 

How to setup multiple livenessProbe if I mount 2 pvc with a pod?

**Comment by joshimoo** [comment]
@hillbun kubernetes allows for 1 liveness probe per container, a pod can have multiple containers.
Now in the case where you have a single pod = single container with multiple pvc's mounted.
The most simplest liveness probe example could be implemented like this:
`ls /mnt/vol1 && ls /mnt/vol2`

[Here](https://stackoverflow.com/questions/49172671/multiple-liveness-probes-in-kuberenetes) is a thread on stackoverflow with some additional details and approaches (dedicated script, dedicated side car container, etc)
