### ISSUE TITLE
[BUG] Name of PVC overlaps on Firefox

### ISSUE THREAD

**Issue by dnoland1** [longhorn/longhorn#1598]
**Describe the bug**
The name of the PVC overlaps with the size column. Screen from Firefox. Looks okay on Chrome.

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/468462/87740649-8dba3000-c797-11ea-8af7-7083488ac611.png">

**To Reproduce**
Go to Volume menu on Firefox 78.0.1 (Mac OS 10.15.5)

**Expected behavior**
PVC name should wrap.

**Log**
N/A

**Environment:**
 - Longhorn version:
1.0.0
 - Kubernetes version:
k3s 1.18.4
 - Node OS type and version:
Ubuntu 20.04

**Comment by smallteeths** [comment]
I use the same version of Firefox as you, But failed to reproduce. I'm confused, Why does your first row and second row display differently. I tried to modify the style and don’t know if it works. You can replace the image `wangsiye/longhorn-ui:0827dca`. If you have time, would you please check this and give a feedback. thanks @dnoland1

**Comment by dnoland1** [comment]
This is a production environment, so a little hesitant to deploy a test image. Anything I can do to further troubleshoot? Do these captures help at all:
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/468462/88337759-1848e500-ccec-11ea-9993-a651246434f7.png">
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/468462/88337833-39113a80-ccec-11ea-9e55-0874af55d3bf.png">
Note, I have around 10 other clusters with longhorn and this is the only one I seeing this wrapping issue.

**Comment by dnoland1** [comment]
I think it's related to the PVC string. If I paste the same PVC name `pvc-08921768-6e31-4f87-94c9-9508441aa0fd` into the second row, it has the same issue:
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/468462/88338187-d9675f00-ccec-11ea-9ce7-8240ddba4ebc.png">

**Comment by smallteeths** [comment]
Thank you for your reply @dnoland1 . This error will be fixed in the next version.

**Comment by cchien816** [comment]
**Validate on master head 20220504
Result Pass**

After create a volume with long PVC name (40 characters)
1. Using openSUSE Leap 15.3 and Firefox 100.0 browser, the PVC name will warp correctly
2. Using Windows 11 and Firefox 100.0 browser, the PVC name will warp correctly
