### ISSUE TITLE
[BUG] pvc status pending

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1601]
pvc.yaml 

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: miop-dev
  name: test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
```

```
kubectl get pvc -n miop-dev
NAME                                   STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
test-pvc                               Pending                                      longhorn       2m37s
```

```
kubectl describe pvc test-pvc -n miop-dev                                                 
Name:          test-pvc
Namespace:     miop-dev
StorageClass:  longhorn
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"test-pvc","namespace":"miop-dev"},"spec":{"accessMo...
               volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type     Reason                Age                    From                                                                                      Message
  ----     ------                ----                   ----                                                                                      -------
  Warning  ProvisioningFailed    3m23s                  driver.longhorn.io_csi-provisioner-6c978457f7-h2pv2_25ab5ea7-b6c9-4138-b2ac-0a55c9f5b3e0  failed to provision volume with StorageClass "longhorn": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=unable to create volume: unable to create volume pvc-fedd0ce5-54ed-4de7-922a-7331eee60559: cannot create volume with image longhornio/longhorn-engine:v1.0.0: engine image ei-eee5f438 (longhornio/longhorn-engine:v1.0.0) is not ready, it's deploying, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes]
  Warning  ProvisioningFailed    2m35s (x4 over 3m38s)  driver.longhorn.io_csi-provisioner-6c978457f7-h2pv2_25ab5ea7-b6c9-4138-b2ac-0a55c9f5b3e0  failed to provision volume with StorageClass "longhorn": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to create volume: unable to create volume pvc-fedd0ce5-54ed-4de7-922a-7331eee60559: cannot create volume with image longhornio/longhorn-engine:v1.0.0: engine image ei-eee5f438 (longhornio/longhorn-engine:v1.0.0) is not ready, it's deploying] from [http://longhorn-backend:9500/v1/volumes]
  Normal   Provisioning          91s (x8 over 3m38s)    driver.longhorn.io_csi-provisioner-6c978457f7-h2pv2_25ab5ea7-b6c9-4138-b2ac-0a55c9f5b3e0  External provisioner is provisioning volume for claim "miop-dev/test-pvc"
  Warning  ProvisioningFailed    91s (x3 over 3m31s)    driver.longhorn.io_csi-provisioner-6c978457f7-h2pv2_25ab5ea7-b6c9-4138-b2ac-0a55c9f5b3e0  failed to provision volume with StorageClass "longhorn": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [detail=, message=unable to create volume: unable to create volume pvc-fedd0ce5-54ed-4de7-922a-7331eee60559: cannot create volume with image longhornio/longhorn-engine:v1.0.0: engine image ei-eee5f438 (longhornio/longhorn-engine:v1.0.0) is not ready, it's deploying, code=Server Error] from [http://longhorn-backend:9500/v1/volumes]
  Normal   ExternalProvisioning  3s (x17 over 3m38s)    persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator

```

**Comment by hillbun** [comment]
kubectl get pods -n longhorn-system
NAME                                      READY   STATUS    RESTARTS   AGE
csi-attacher-58fb5bdbf6-bvjpb             1/1     Running   3          17d
csi-attacher-58fb5bdbf6-m4mvx             1/1     Running   0          17d
csi-attacher-58fb5bdbf6-zsvww             1/1     Running   1          17d
csi-provisioner-6c978457f7-h2pv2          1/1     Running   0          17d
csi-provisioner-6c978457f7-hlfnt          1/1     Running   0          17d
csi-provisioner-6c978457f7-jdw9s          1/1     Running   0          17d
engine-image-ei-eee5f438-2568x            1/1     Running   0          17d
engine-image-ei-eee5f438-cmvgn            1/1     Running   0          17d
engine-image-ei-eee5f438-dfvmv            1/1     Running   0          17d
engine-image-ei-eee5f438-gjv2k            1/1     Running   0          17d
engine-image-ei-eee5f438-j8zlf            1/1     Running   1          17d
engine-image-ei-eee5f438-k2xrm            1/1     Running   2          17d
engine-image-ei-eee5f438-r4lht            1/1     Running   0          17d
engine-image-ei-eee5f438-r9ghb            1/1     Running   1          17d
engine-image-ei-eee5f438-s2527            1/1     Running   1          17d
engine-image-ei-eee5f438-slh77            1/1     Running   0          17d
engine-image-ei-eee5f438-vl6d5            1/1     Running   0          17d
engine-image-ei-eee5f438-x724j            1/1     Running   0          17d
instance-manager-e-0b3b4989               1/1     Running   0          17d
instance-manager-e-14077a1d               1/1     Running   0          17d
instance-manager-e-310b1337               1/1     Running   0          16d
instance-manager-e-5a282ebb               1/1     Running   0          17d
instance-manager-e-5cda53f1               1/1     Running   0          16d
instance-manager-e-644139b6               1/1     Running   0          17d
instance-manager-e-7a735d15               1/1     Running   0          17d
instance-manager-e-8eb86713               1/1     Running   0          17d
instance-manager-e-a4941c6f               1/1     Running   0          17d
instance-manager-e-c0b08bf3               1/1     Running   0          16d
instance-manager-e-cd4e30ec               1/1     Running   0          17d
instance-manager-e-ce4a06b0               1/1     Running   0          17d
instance-manager-r-01784a7d               1/1     Running   0          17d
instance-manager-r-33b3e776               1/1     Running   0          17d
instance-manager-r-3576b823               1/1     Running   0          17d
instance-manager-r-415cbef5               1/1     Running   0          17d
instance-manager-r-4a2d9e59               1/1     Running   0          16d
instance-manager-r-4fbcbc23               1/1     Running   0          17d
instance-manager-r-5e8a1d24               1/1     Running   0          16d
instance-manager-r-6668855e               1/1     Running   0          17d
instance-manager-r-6b99cc16               1/1     Running   0          17d
instance-manager-r-72d48892               1/1     Running   0          17d
instance-manager-r-74fbfd43               1/1     Running   0          17d
instance-manager-r-c68c78eb               1/1     Running   0          16d
longhorn-csi-plugin-2wggb                 2/2     Running   3          17d
longhorn-csi-plugin-bmztn                 2/2     Running   0          17d
longhorn-csi-plugin-dd6cp                 2/2     Running   0          17d
longhorn-csi-plugin-gtwdt                 2/2     Running   0          17d
longhorn-csi-plugin-mdcvm                 2/2     Running   5          17d
longhorn-csi-plugin-n2f9m                 2/2     Running   0          17d
longhorn-csi-plugin-ndhj2                 2/2     Running   0          17d
longhorn-csi-plugin-rkv6d                 2/2     Running   0          17d
longhorn-csi-plugin-spgqh                 2/2     Running   0          17d
longhorn-csi-plugin-t5jz2                 2/2     Running   0          17d
longhorn-csi-plugin-tb99k                 2/2     Running   2          17d
longhorn-csi-plugin-tv2rq                 2/2     Running   2          17d
longhorn-driver-deployer-fd95d454-4ghdw   1/1     Running   1          17d
longhorn-manager-6lqhq                    1/1     Running   0          17d
longhorn-manager-7dmm7                    1/1     Running   1          17d
longhorn-manager-88tqq                    1/1     Running   0          17d
longhorn-manager-cp78b                    1/1     Running   0          17d
longhorn-manager-dbvsc                    1/1     Running   2          17d
longhorn-manager-lh9lv                    1/1     Running   1          17d
longhorn-manager-lstb6                    1/1     Running   0          17d
longhorn-manager-nnm7d                    1/1     Running   0          17d
longhorn-manager-nqt5c                    1/1     Running   0          17d
longhorn-manager-t9766                    1/1     Running   1          17d
longhorn-manager-tjxrq                    1/1     Running   0          29m
longhorn-manager-w2x2z                    1/1     Running   0          17d
longhorn-ui-849fb7ccdd-d4njs              1/1     Running   0          17d

**Comment by yasker** [comment]
Can you check
```
kubectl -n longhorn-system get engineimages.longhorn.io -o yaml
```

There should some reasons why the engine image is not ready.

**Comment by hillbun** [comment]
@yasker 

```
apiVersion: v1
items:
- apiVersion: longhorn.io/v1beta1
  kind: EngineImage
  metadata:
    creationTimestamp: "2020-06-30T08:26:29Z"
    finalizers:
    - longhorn.io
    generation: 1
    name: ei-eee5f438
    namespace: longhorn-system
    resourceVersion: "48822984"
    selfLink: /apis/longhorn.io/v1beta1/namespaces/longhorn-system/engineimages/ei-eee5f438
    uid: defeaf94-442a-41ee-a4b4-dc9f27fda101
  spec:
    image: longhornio/longhorn-engine:v1.0.0
  status:
    buildDate: "2020-05-30T15:55:26+00:00"
    cliAPIMinVersion: 3
    cliAPIVersion: 3
    conditions:
      ready:
        lastProbeTime: ""
        lastTransitionTime: "2020-07-17T08:23:31Z"
        message: 'no enough pods are ready: 11 vs 12'
        reason: daemonSet
        status: "False"
        type: ready
    controllerAPIMinVersion: 3
    controllerAPIVersion: 3
    dataFormatMinVersion: 1
    dataFormatVersion: 1
    gitCommit: f99be10aaaffb9b41fa7782a27e61513b2ab8c52
    noRefSince: ""
    ownerID: node2
    refCount: 4
    state: deploying
    version: v1.0.0
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by yasker** [comment]
Weird, Kubernetes reports only 11 pods are ready, not 12. So one of the `engine-image-ei-eee5f438` pod is not right. But as you see, all 12 of them are indeed in the running state.

Can you check `kubectl -n longhorn-system get daemonset engine-image-ei-eee5f438 -o yaml`?

**Comment by hillbun** [comment]
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: "2020-06-30T08:26:30Z"
  generation: 1
  labels:
    longhorn.io/component: engine-image
    longhorn.io/engine-image: ei-eee5f438
  name: engine-image-ei-eee5f438
  namespace: longhorn-system
  ownerReferences:
  - apiVersion: longhorn.io/v1beta1
    blockOwnerDeletion: true
    kind: EngineImage
    name: ei-eee5f438
    uid: defeaf94-442a-41ee-a4b4-dc9f27fda101
  resourceVersion: "48783926"
  selfLink: /apis/extensions/v1beta1/namespaces/longhorn-system/daemonsets/engine-image-ei-eee5f438
  uid: 9567edd8-dd75-4d04-b93d-3c672155fd90
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      longhorn.io/component: engine-image
      longhorn.io/engine-image: ei-eee5f438
  template:
    metadata:
      creationTimestamp: null
      labels:
        longhorn.io/component: engine-image
        longhorn.io/engine-image: ei-eee5f438
      name: engine-image-ei-eee5f438
      ownerReferences:
      - apiVersion: longhorn.io/v1beta1
        blockOwnerDeletion: true
        kind: EngineImage
        name: ei-eee5f438
        uid: defeaf94-442a-41ee-a4b4-dc9f27fda101
    spec:
      containers:
      - args:
        - -c
        - diff /usr/local/bin/longhorn /data/longhorn > /dev/null 2>&1; if [ $? -ne
          0 ]; then cp -p /usr/local/bin/longhorn /data/ && echo installed; fi &&
          trap 'rm /data/longhorn* && echo cleaned up' EXIT && sleep infinity
        command:
        - /bin/bash
        image: longhornio/longhorn-engine:v1.0.0
        imagePullPolicy: Always
        name: engine-image-ei-eee5f438
        readinessProbe:
          exec:
            command:
            - ls
            - /data/longhorn
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: longhorn-service-account
      serviceAccountName: longhorn-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.0.0
          type: ""
        name: data
  templateGeneration: 1
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100%
    type: RollingUpdate
status:
  currentNumberScheduled: 12
  desiredNumberScheduled: 12
  numberAvailable: 11
  numberMisscheduled: 0
  numberReady: 11
  numberUnavailable: 1
  observedGeneration: 1
  updatedNumberScheduled: 12
```

**Comment by hillbun** [comment]
@yasker 

Any advise?

**Comment by yasker** [comment]
```
  numberAvailable: 11
  numberMisscheduled: 0
  numberReady: 11
  numberUnavailable: 1
  observedGeneration: 1
```

There is 1 daemonset pod is `unavailable`. You would need to look into the daemonset pod to know why.

Or if you don't have any attached volumes, try to delete engine-image-ei-eee5f438 daemonset . It will be recreated and may solve the problem. Only do it when all the volumes are attached and workloads are stopped.

**Comment by hillbun** [comment]
@yasker 

I delete engine-image-ei-eee5f438 daemonset, and issue fixed.

what do you mean by "Only do it when all the volumes are attached and workloads are stopped."

when I delete engine-image-ei-eee5f438 daemonset, I have pvc attached to pods.
