### ISSUE TITLE
[BUG]Test: 'backupstore_cleanup' method causing failures for some integration tests.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1605]
**Describe the bug**
Tests 'test_single_replica_restore_failure' and 'test_backup_block_deletion' fail intermittently as method 'backupstore_cleanup' fails to delete backups from backup store.

**To Reproduce**
1. Set up the minio backup store and create a backup of 2 GB
2. Run the test 'test_single_replica_restore_failure' and 'test_backup_block_deletion'.
3. The tests will fail with below error:
```
>       backupstore_cleanup(client)

test_ha.py:1216: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

client = <longhorn.Client object at 0x7fed1b0dfb50>

    def backupstore_cleanup(client):
        backup_volumes = client.list_backup_volume()
    
        for backup_volume in backup_volumes:
            backups = backup_volume.backupList()
    
            for backup in backups:
                backup_name = backup.name
                backup_volume.backupDelete(name=backup_name)
                wait_for_backup_volume_delete(client, backup_name)
    
            client.delete(backup_volume)
    
        backup_volumes = client.list_backup_volume()
>       assert backup_volumes.data == []
E       AssertionError

backupstore.py:36: AssertionError
```

**Expected behavior**
These tests should delete the backups from backup store and start test steps.

**Environment:**
 - Longhorn version: v1.0.1-rc2
 - Kubernetes version: 1.17
 - Node OS type and version: Ubuntu 18.04

**Comment by joshimoo** [comment]
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [x] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The PR is at longhorn/longhorn-tests#372 
longhorn/backupstore#53 
longhorn/longhorn-manager#632
longhorn/longhorn-engine#517

* [x] Is the reproduce steps/test steps documented?

* [x] Which areas/issues this PR might have potential impacts on?
Area backup tests
Issues #710 #1604 #1603 

* [x] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~~

* [x] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at~~

* [x] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at~~

* [x] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~~

* [x] ~~**if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at~~

**Comment by khushboo-rancher** [comment]
Validation - **Passed**

```test_single_replica_restore_failure' and 'test_backup_block_deletion``` are not failing for deletion of backup reason anymore in integration test.
