### ISSUE TITLE
[Question] NFS backup question

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1610]
I have config backup target :
nfs://192.168.100.72:/data/nfsdata

but there is no backup list in backup menu when backup pvc manually.

How to debug?

**Comment by yasker** [comment]
Check the `longhorn-manager`'s log. The most common issue is the NFS server is not v4.

**Comment by hillbun** [comment]
@yasker 

`error listing backups: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.0.0/longhorn [backup ls --volume-only nfs://192.168.100.216:/data/nfsdata], output Cannot mount nfs 192.168.100.216:/data/nfsdata: Failed to execute: mount [-t nfs4 192.168.100.216:/data/nfsdata /var/lib/longhorn-backupstore-mounts/192_168_100_216/data/nfsdata], output mount.nfs4: access denied by server while mounting 192.168.100.216:/data/nfsdata , error exit status 32 , stderr, time="2020-07-21T03:22:54Z" level=error msg="Cannot mount nfs 192.168.100.216:/data/nfsdata: Failed to execute: mount [-t nfs4 192.168.100.216:/data/nfsdata /var/lib/longhorn-backupstore-mounts/192_168_100_216/data/nfsdata], output mount.nfs4: access denied by server while mounting 192.168.100.216:/data/nfsdata\n, error exit status 32" , error exit status 1`

When I click backup menu, I see this error.   what's problem?

**Comment by hillbun** [comment]
nfs server side /etc/exports config error.
fixed
