### ISSUE TITLE
[BUG]Longhorn replica doesn't get rebuild when the replica files are removed/crashed

### ISSUE THREAD

**Issue by boknowswiki** [longhorn/longhorn#1615]
**Describe the bug**
Longhorn replica doesn't get rebuild when the replica files are removed/crashed

**To Reproduce**
1. Use https://github.com/longhorn/longhorn/blob/master/examples/pod_with_pvc.yaml to create a pod and longhorn volume.
2.  login to pod to write data at /data/data, and get md5sum of the data file.
3. login to a node and delete one replica file. I don't see the rebuild got triggerred.

**Expected behavior**
Rebuild for this crashed replica should be triggered.

`[instance-manager-r-4af2d125] [pvc-7cd4e5da-8d0e-4749-b56c-9e3486266c92-r-2a847a6d] time="2020-07-20T21:50:05Z" level=error msg="Fail to get size of file /host/var/lib/longhorn/replicas/pvc-7cd4e5da-8d0e-4749-b56c-9e3486266c92-f46e48df/volume-head-000.img" `

**Environment:**
 - Longhorn version: v1.0.1-rc3
 - Kubernetes version: 

`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`

 - Node OS type and version:

Ubuntu 18.04 LTS

**Comment by boknowswiki** [comment]
@yasker  and @shuo-wu ,

Proposal:
Add a new field in replica info struct `Error bool`, this will reflect any error detected by replica itself. And In replica server status function, we return the error state to the pingResponse function, which failed the ping, and then triggers the replica rebuild. This is the same way as the replica directory is missing, how we handle it right now.

One thing I notices during the rebuild, the faulted replica doesn't get removed after rebuild, not only in this case, but also with the case replica write failed, and and the rebuild got triggered, but the faulted replica is left there. I think this might be a separate issue for rebuild and clean-up.

Please let me know what do you think?

Thanks,
Bo

**Comment by yasker** [comment]
Why the error `Fail to get size of file` is triggered but the replica continues working?

**Comment by boknowswiki** [comment]
> Why the error `Fail to get size of file` is triggered but the replica continues working?

It's not `working`, it doesn't trigger rebuild, since there is no writing to the replica. If there is any writing to the replica, it will trigger rebuild automatically. And the reason for this doesn't trigger a rebuild is because we don't report the error all the way back.

**Comment by boknowswiki** [comment]
## Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The PR is at

* [ ] Is the reproduce steps/test steps documented?

* [ ] ~~Which areas/issues this PR might have potential impacts on?
Area
Issues~~

* ~~[ ] **If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* ~~[ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~~

* ~~[ ] **if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at~~

* [ ] **If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at

* ~~[ ] **if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~~

* ~~[ ] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at~~

**Comment by khushboo-rancher** [comment]
Validated on longhorn-master - 08-04-2020

Validation - **Failed**

Steps followed:
1. Created a volume with 3 replicas.
2. Deleted volume-head from one of the replica. It didn't trigger the rebuild.

**Comment by boknowswiki** [comment]
@khushboo-rancher , I think the longhorn-engine image is out of date. I just checked docker hub [longhorn-engine](https://hub.docker.com/r/longhornio/longhorn-engine), it was updated 11 days ago. And from the git log, my fix was merged 7 days ago. So the image we are using doesn't have my fix. And that also explained why my local build works. I also found a typo in the error message. Let me submit a PR to fix this typo and hopefully it will trigger longhorn-engine to be rebuilt and re-published.

**Comment by khushboo-rancher** [comment]
@boknowswiki I don't see the fix in the latest master as of 08-06-2020
Moving back to implement bucket for now.

**Comment by yasker** [comment]
We have a drone issues on engine image building at the moment. Let's move it to merged once the drone issue fixed.

**Comment by khushboo-rancher** [comment]
Verified on master - 08-10-2020

Validation - **Passed**

**Scenarios tested**
1. Deletion of the replica folder from the node. - Triggers a rebuild
2. Deletion of a data file like volume-head.img or volume-snap.img - Triggers a rebuild
3. Deletion of a metafile like volume-snap.img - Doesn't trigger a rebuild
4. Modification of a data file - Doesn't trigger a rebuild
5. Addition of a file in replica folder - Doesn't trigger a rebuild

**Comment by meldafrawi** [comment]
test  passed in nightly tests.
