### ISSUE TITLE
Update chart README.md for Helm Hub

### ISSUE THREAD

**Issue by ttpcodes** [longhorn/longhorn#1617]
Currently, the chart's `README.md` is currently targeted towards users who are installing Longhorn using Rancher, which doesn't make sense now that we've put the Helm chart on Helm Hub and Artifact Hub. We should update the `README.md` so it reflects installation instructions for Helm users and instead either refer to Rancher as a side note or create a separate version of `README.md` with Rancher installation instructions that we can use for the Rancher charts.

**Comment by anthr76** [comment]
Can this be considered closed or is more information needed?

**Comment by boknowswiki** [comment]
@anthr76 , we need QA team to close it after verification. Is there anything you are looking for? Thanks.

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master - 10/26/2020

Validation - **Pass**

The ```README.md``` is updated for helm user - https://github.com/longhorn/longhorn/tree/master/chart

**Comment by anthr76** [comment]
Just looking to help out in any way. Cheers
