### ISSUE TITLE
[Question] what's difference between snapshot and backup?

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1618]
what's difference between snapshot and backup?

**Comment by joshimoo** [comment]
@hillbun I will try to answer that, please feel free to ask for clarifications.

(System)
Longhorn uses snapshots for locally stored revisions of data (these snapshots are deltas of the prior snapshot).
Longhorn also uses Snapshots to rebuild a failed replica for example.

(User)
Backups are a complete set of data based on snapshot XYZ stored externally (s3, nfs).
Anytime you request a brand new backup, longhorn  will create a snapshot first then create the backup based on that snapshot.
This way new data can be written while we are still in the process of backing up the data.

**Comment by shuo-wu** [comment]
Snapshots can store historical data for the volume. They are a part of Longhorn volumes, which means they will be deleted if the volume is gone.

Backups are the data stored in external storage like S3 or NFS. When the volume somehow is crashed/gone, you will use the backups to restore data to a new volume.

**Comment by joshimoo** [comment]
Please reopen if you require further assistance.
