### ISSUE TITLE
[Question] How to get pvc storage usage alert?

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1623]
How to get pvc storage usage alert?

**Comment by shuo-wu** [comment]
Right now Longhorn has no alert/notification mechanism for storage usage.
@yasker Are there any plans for the feature?

**Comment by hillbun** [comment]
any general solutions on k8s about pvc storage usage alert?

**Comment by shuo-wu** [comment]
It seems Kubernetes has no alert for PVC/PV. Actually the space usage status relies on the implementation of the underlying storage vendor, Longhorn for example. And Kubernetes has no idea about it.

But Kubernetes does monitor the disk usage of each node and reflects the info in `node.Status.Conditions`:
https://kubernetes.io/docs/concepts/architecture/nodes/#condition

**Comment by hillbun** [comment]
I suggest longhorn add feather about this.

like exporter.  I can use prometheus and send to alertmanager.

**Comment by yasker** [comment]
The alert/metrics feature is tracking at #1180 and #928 . Can you add your requirement to them as well so we can easily track them?
