### ISSUE TITLE
[Question] Volume expansion on Rancher workload

### ISSUE THREAD

**Issue by mrcdb** [longhorn/longhorn#1636]
Hi! 

I am having some issues at expanding volumes that are automatically created on Longhorn via Rancher (e.g. when I deploy an app from the catalogue or create a Deployment).

From the docs, I read that the required steps are:

1. detach the volume from Longhorn UI
2. expand the PVC/PV by  updating the YAML spec and applying it via Kubectl (I don't see how to expand the PVC on Rancher UI)
3. redeploy the pod (e.g. by running the "Redeploy" command from Rancher UI)

Now, what I get is a failing pod that cannot attach to the volume at all. And the volume itself stays "detached" from the Longhorn UI. Once I remove the deployment the PVC is released as well, so it is not a solution.

How is it done ? Thanks!

**Comment by yasker** [comment]
@mrcdb In fact you need to scale down the workload to detach the volume, instead of detaching the volume from Longhorn UI. Can you point out the place that said the user need to detach the volume from Longhorn UI? We need to fix that.

**Comment by mrcdb** [comment]
Hi @yasker! I read about volume detaching in this page (https://longhorn.io/docs/1.0.0/volumes-and-nodes/expansion/) and I mistakingly though that it was bound to be done via Longhorn UI.

Actually, I see that the documentation mentions the workload scale down here (https://longhorn.io/docs/1.0.0/volumes-and-nodes/detaching-volumes/). I think it would be beneficial to add some Rancher-specific documentation so that to clarify how these two products interact with each other.
