### ISSUE TITLE
Performance and scalability report

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1637]
We need performance and scalability report

**Comment by yasker** [comment]
Related to https://github.com/longhorn/longhorn/issues/1463

**Comment by joshimoo** [comment]
The goal is to start work on this once we have reached the feature freeze for 1.1.0.

- We want to be able to provide guidance for the system requirements for X volumes / Y nodes
- We want to test system interaction with a 100 nodes - 1000 volumes cluster and make sure that we at worst scale linearly with the amount of volumes/nodes.

We should look into adding prometheus metrics to the different longhorn components, we can then utilize grafana for the visualisation of the performance metrics. These same metrics can then be used in the future by the users for alerts / notifications for abnormal system operations.

**Comment by joshimoo** [comment]
install / upgrade scalability issue for longhorn-manager: longhorn/longhorn#1379

**Comment by joshimoo** [comment]
# scale-test results
[scale-test-results.zip](https://github.com/longhorn/longhorn/files/5004451/scale-test-results.zip)

# logs + support bundle

**Comment by boknowswiki** [comment]
[Performance Test Plan and Results](https://rancher.atlassian.net/wiki/spaces/LON/pages/608141542/Performance+Test+Plan)

**Comment by boknowswiki** [comment]
Uploaded a Longhorn Dbench [Here](https://github.com/boknowswiki/dbench/tree/dbench_for_longhorn_blk_dev). Hit a permission issue, this issue may impact the performance test results. And if I set `privileged` to true, the bind mount point is not correct. Need to look into this issue later.

**Comment by yasker** [comment]
Waiting for the proofread.

**Comment by yasker** [comment]
The blog is up at https://longhorn.io/blog/performance-scalability-report-aug-2020/
