### ISSUE TITLE
[BUG]An error occurred while upgrading Longhorn from 1.0.0 to 1.0.1 through Rancher UI

### ISSUE THREAD

**Issue by xfrogcn** [longhorn/longhorn#1640]
**Describe the bug**
An error occurred while upgrading Longhorn from 1.0.0 to 1.0.1 through Rancher UI，the error message is：
Failed to install app longhorn-system. Error: UPGRADE FAILED: the server has asked for the client to provide credentials (get configmaps)

**To Reproduce**
1. Go to Rancher Apps Page
2. Click "longhorn-system" app menu，select “upgrade”，enter detail page
3. goto “Template Version”  dropdown， select "1.0.1"
4. Click "Upgrade" button

**Log**
Failed to install app longhorn-system. Error: UPGRADE FAILED: the server has asked for the client to provide credentials (get configmaps)

**Environment:**
 - Longhorn version: 1.0.0
 - Kubernetes version: v1.17.4
 - Node OS type and version: CentOS 7.6

**Comment by yasker** [comment]
@xfrogcn This is the most common upgrade path. Is there any change regarding the owner of the project? It seems related to the permission of Kubernetes. E.g. https://github.com/rancher/rancher/issues/18787
