### ISSUE TITLE
[BUG] Longhorn Air Gap installation from private repo

### ISSUE THREAD

**Issue by xiaoluhong** [longhorn/longhorn#1641]
**Chart_version**: v1.0.1

**Describe the bug**

Based on the current Charts, Although the Private Registry URL was set in the Rancher Apps UI before deploying Longhorn, but the images were still pulled from the dockerhub during the deployment action. 

![image](https://user-images.githubusercontent.com/20707603/88774234-c1dd1a00-d1b5-11ea-84f6-718e9e2bd62d.png)

![image](https://user-images.githubusercontent.com/20707603/88774217-bd186600-d1b5-11ea-9cd4-8055aee1c4b8.png)

Therefore, I modified the Charts and added the registryUrl prefix for the image parameter. As long as the user has configured the Private Registry URL (user name and password are optional), the images will be pulled from the private image registry.

PR: https://github.com/longhorn/charts/pull/6

**Related issue**

For the first installation of Longhorn and configuring the **Private Registry URL**, it has been tested. 
However, if you are updating the Chart and configuring the Private Registry URL in an existing environment, there are currently some issues.

issue: https://github.com/longhorn/longhorn/issues/1642

**Comment by yasker** [comment]
What's the difference between this one and #1642 ?

**Comment by PhanLe1010** [comment]
@xiaoluhong In Longhorn installation using Rancher UI, if user wants to use private registry, setting up a private registry (URL, user, password) is the first step out of three steps. As you has noticed, just setting up a private registry does not make Longhorn pull images from the private registry. There are 2 other steps here https://longhorn.io/docs/1.0.1/advanced-resources/deploy/airgap/#using-rancher-app . 

Specifically, we need to select `false` for the section `Use Default Images` and specify the full image image `<REGISTRY_URL>/<Longhorn-component>` for manager, engine, ui, instance manager, csi attacher, csi provisioner, CSI Driver registrar, CSI Driver resizer.

I think that the reason Longhorn is designed this way is so that user can use both public and private registry (Not locked into the private registry once it is setup in the cluster)

**Comment by xiaoluhong** [comment]
Hi All,

@yasker  The expected effect of adding environment variables in updated Longhorn-Driver-Deployer workload should automatically update the image of the csi-attacher, csi-provisioner, csi-resizer, longhorn-csi-plugin workload, but the actual effect is not updated. A look at the Longhorn-Driver-Deployer Workload log seems to indicate that the Workload already exists and the update is skipped. 

@PhanLe1010 
For the user usage that has been collected so far, the pull image is either done through DockerHub or private repo, with no other usage scenarios.

Users habitually use the default configuration, so if there is no custom image <<REGISTRY_URL>/< longhorn-component > > will pull the image from dockerhub by default. In my opinion, on the basis of following users' habits, users only need to fill in the private Registry to pull images from the specified image repo, and do not need to modify too much image configuration, which is better for the use experience of offline deployment scenarios.

Thanks.

**Comment by PhanLe1010** [comment]
> For the user usage that has been collected so far, the pull image is either done through DockerHub or private repo, with no other usage scenarios.

@xiaoluhong Yeah, you have a great point. Thank you! 

Should we change the logic @yasker ?

**Comment by yasker** [comment]
@xiaoluhong It makes sense, thanks for the explanation. I am going to assign this issue to you too since you already have a PR ready for it.

**Comment by xiaoluhong** [comment]
Hi @yasker ,

I submitted the new PR https://github.com/longhorn/longhorn/pull/1650.
Thank you.

**Comment by yasker** [comment]
@xiaoluhong the chart PR is merged. Can you help to check the doc to see if we need to update it? See https://longhorn.io/docs/1.0.1/advanced-resources/deploy/airgap/ . The doc repo is at https://github.com/longhorn/website

**Comment by xiaoluhong** [comment]
@yasker 
Yes, the doc needs to be updated. I will submit a PR.

**Comment by yasker** [comment]
@PhanLe1010 Can you help to check and update the doc for this issue?

**Comment by PhanLe1010** [comment]
@yasker Sure

**Comment by meldafrawi** [comment]
Validation: **PASSED**
Longhorn Version: `v1.0.2-rc1`

**Comment by meldafrawi** [comment]
Waiting for docs to be updated

**Comment by yasker** [comment]
Updated doc merged to `staging` branch.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
