### ISSUE TITLE
[BUG]  CSI related plugins does not automatically update the image after the chart is updated

### ISSUE THREAD

**Issue by xiaoluhong** [longhorn/longhorn#1642]
## csi-attacher, csi-provisioner, csi-resizer, longhorn-csi-plugin workload

**To Reproduce**
1. Updating **Longhorn-Driver-Deployer** workload adds the environment variables,
![image](https://user-images.githubusercontent.com/20707603/88776880-2483e500-d1b9-11ea-87ac-5a61a77bf64f.png)

2. The **csi-attacher, csi-provisioner, csi-resizer, longhorn-csi-plugin** workload is not automatically updated. 
![image](https://user-images.githubusercontent.com/20707603/88776946-3feef000-d1b9-11ea-95d7-e73212ab6636.png)

3. Delete the **csi-attacher, csi-provisioner, csi-resizer, longhorn-csi-plugin** workload,
4. Choose to redeploy the Longhorn-Driver-Deployer Workload ,
5. **csi-attacher, csi-provisioner, csi-resizer, longhorn-csi-plugin** will be deployed again using the new image.
![image](https://user-images.githubusercontent.com/20707603/88777445-ce637180-d1b9-11ea-9836-11816ec603d1.png)

## engine-Image workload

The engine-Image workload image is not automatically updated
![image](https://user-images.githubusercontent.com/20707603/88778643-59913700-d1bb-11ea-998a-7646dd098c24.png)

I checked the Entrypoint command for the Longhorn-Manager workload and the engine-Image has been updated
![image](https://user-images.githubusercontent.com/20707603/88779224-1be0de00-d1bc-11ea-8c55-66d9c6d5c754.png)

**Comment by yasker** [comment]
The old engine image is fine since once you stop using it, it will be cleaned up automatically.

The CSI components should be updated automatically though.

**Comment by xiaoluhong** [comment]
@yasker  

Hi ,

This is a completely new environment that I used for testing, and no pod use PV. 
I tried to delete the engine-Image-ei-3bd16bdf pod, but the automatically created pod still use the old engine Image.

**Comment by PhanLe1010** [comment]
@xiaoluhong 
We cannot manually delete the `engine-Image-ei-3bd16bdf` daemonset. The reason is because Longhorn `EngineImageController` is monitoring all `engineimages` CRDs. The `EngineImageController` will create a new `engine-Image-ei-3bd16bdf` daemonset with the same old spec when it detect that engine-Image-ei-3bd16bdf` daemonset is downed but the corresponding `engineimages` CRD still exists. 

So like @yasker said, we just wait and the engine image will be cleaned up automatically. It doesn't hurt anything. 

If you really want to delete the `engine-Image-ei-3bd16bdf` daemonset immediately, you can try out:
```
kubectl delete engineimages ei-3bd16bdf -n longhorn-system
```

**Comment by PhanLe1010** [comment]
We still need to fix this though
> The CSI components should be updated automatically though.

**Comment by xiaoluhong** [comment]
Hi @PhanLe1010 , 

I deleted the engine-Image-ei-3bd16bdf  pod through rancher UI, and it will automatically create the  after deleting it. 
I don't see the definition of image in the two crds（ engineimages.longhorn.io and engineimages.longhorn.rancher.io), So I don't know what file to change.

**Comment by yasker** [comment]
@xiaoluhong It's because `engine-Image-ei-3bd16bdf` is the engine image provided by the Docker Hub. The Docker Hub URL is encoded into it already. You need to delete it in the `Setting -> Engine Images` once there is no volume using it.

**Comment by xiaoluhong** [comment]
Hi @yasker , 

Since this is a brand new environment, there is no volume in use. In the longhorn UI,  I looked at the **setting-> Engine Images**, which are already the new images version. So I am a little confused why **engine-Image-ei-3bd16bdf** does not automatically update

**Comment by PhanLe1010** [comment]
Hi @xiaoluhong!
I am not quite understand this 
> I don't see the definition of image in the two crds（ engineimages.longhorn.io and engineimages.longhorn.rancher.io), So I don't know what file to change.

About this 
> I deleted the engine-Image-ei-3bd16bdf pod through rancher UI, and it will automatically create the after deleting it.

Yes, it will not go away. Try this instead:
```
kubectl delete engineimages ei-3bd16bdf -n longhorn-system
```

**Comment by xiaoluhong** [comment]
Hi @PhanLe1010 

I see. Thank you.

**Comment by PhanLe1010** [comment]
**Manual test:**
1. Install Longhorn
1. Change the `longhorn-driver-deployer` at https://github.com/longhorn/longhorn-manager/blob/c2ceb9f3f991810f811601d8c41c09b67fb50746/deploy/install/02-components/04-driver.yaml#L50 to use the new images for CSI components
1. `Kubectl apply -f` it
1. Verify that CSI components use new images

**Comment by yasker** [comment]
Need to test the negative case as well, e.g. redeploy without changing the image.

**Comment by PhanLe1010** [comment]
Thank you. Done

**Comment by meldafrawi** [comment]
Validation: **PASSED**

validated with yaml manifest, and helm chart using https://github.com/longhorn/longhorn/pull/1971
