### ISSUE TITLE
Failing to upgrade due to conflict

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#1646]
**Describe the bug**
On a large cluster, the delay of leader election and conflicts when updating CRDs blocked Longhorn upgrading

**To Reproduce**
New installation:
1. create a large cluster of many nodes (about 30 nodes)
1. Install Longhorn to v1.0.1
1. The upgrading is blocked after about 17-20 managers are up.

Upgrading from old version:
1. create a large cluster of many nodes (about 30 nodes)
1. Install Longhorn v1.0.0
1. Upgrade Longhorn to v1.0.1
1. The upgrading is blocked after about 17-20 managers are up.

**Additional context**
more detail about the logs and discussions are at https://github.com/longhorn/longhorn/issues/1379#issuecomment-665804479

**Comment by yasker** [comment]
It's probably blocked instead of being very slow.

**Comment by yasker** [comment]
Need to backport to v1.0.2

**Comment by PhanLe1010** [comment]
After the fix, it takes ~16 mins for 30-node cluster. Still ~ 30s per node. It seems like ` the delay of leader election` still persists.

**Comment by shuo-wu** [comment]
> After the fix, it takes ~15 mins for 30-node cluster. Still ~ 30s per node. It seems like ` the delay of leader election` still persists.

It seems that each manager will loop in retry until it becomes the leader

**Comment by PhanLe1010** [comment]
@shuo-wu 
Manager enters the `retry loop`. Then goes into `upgrade()`. Then goes into `leaderelection.RunorDie()`. It is sleeping inside `leaderelection.RunorDie()`, wakes up every 2 seconds try to vote to become leader. When it becomes leader, it does the upgrade. If it gets into an error while upgrading it will back out to the `retry loop`, sleep 3 seconds and try `upgrade()` again. 

So, manager will sleep/wakeup in `leaderelection.RunorDie()` until it become leader. 

I am guessing that the bug inside `leaderelection.RunorDie()` prevents the manager to give up the leadership even when it successfully finish upgrading . So, it is forced to give up its leadership after 20s `LeaseDuration`. https://github.com/longhorn/longhorn-manager/blob/0ad9564e091ad3ce87989e8b022fe72241f637f5/upgrade/upgrade.go#L98 

How do you think?

**Comment by shuo-wu** [comment]
1. I just double check the arg `LeaseDuration` and here is the explanation:
```
LeaseDuration is the duration that non-leader candidates will wait to force acquire leadership. This is measured against time of last observed ack.
```
I am not sure what `force acquire leadership` is, and if this is the culprit of the 30s delay.
2. We may need to verify how the error is triggered. Then I can find a correct way to release the lock in advance.

**Comment by yasker** [comment]
@shuo-wu Phan was referring to https://github.com/longhorn/longhorn/issues/1379

**Comment by khushboo-rancher** [comment]
@PhanLe1010 Could you please add manual test cases 
https://github.com/longhorn/longhorn-tests/tree/master/docs/content/manual

We maintain our manual test cases [here](https://longhorn.github.io/longhorn-tests/manual/release-specific/v1.0.2/.)

**Comment by PhanLe1010** [comment]
@khushboo-rancher 
Does it mean that I will have to create a PR into the `longhorn-tests` repo?

**Comment by khushboo-rancher** [comment]
@PhanLe1010 Yes, like this one - https://github.com/longhorn/longhorn-tests/pull/383

**Comment by PhanLe1010** [comment]
Thanks @khushboo-rancher. Added

**Comment by khushboo-rancher** [comment]
Verified on longhorn-master - 08-05-2020

Validation - **Passed**

Tested with 32 nodes multiple times, Installation and upgrade from v1.0.0 to master worked fine.
