### ISSUE TITLE
[Question]  incorrectly displays the capacity of the volum

### ISSUE THREAD

**Issue by arturmon** [longhorn/longhorn#1652]
checked on two volumes, incorrectly displays the used place. or is it an unused place? then what does the `Actual Size` field mean?

![photo_2020-07-31_12-00-45 (2)](https://user-images.githubusercontent.com/7686999/89019748-772edf80-d326-11ea-9cb5-ea27953a3e34.jpg)
![photo_2020-07-31_12-00-45 (3)](https://user-images.githubusercontent.com/7686999/89019750-77c77600-d326-11ea-94ed-cb6a3e807935.jpg)
![photo_2020-07-31_12-00-45](https://user-images.githubusercontent.com/7686999/89019751-77c77600-d326-11ea-8479-da1e7de2c33e.jpg)
![photo_2020-07-31_12-00-54](https://user-images.githubusercontent.com/7686999/89019753-78600c80-d326-11ea-8d23-481287a59419.jpg)
![Screenshot_20200731_115736](https://user-images.githubusercontent.com/7686999/89019754-78f8a300-d326-11ea-8c36-10b57027c498.png)
![Screenshot_20200731_115907](https://user-images.githubusercontent.com/7686999/89019755-78f8a300-d326-11ea-9b68-19dd6ac03f8d.png)
![Screenshot_20200731_120851](https://user-images.githubusercontent.com/7686999/89019867-a8a7ab00-d326-11ea-8ccf-d1d547324b0a.png)

**Comment by yasker** [comment]
You can refer to https://longhorn.io/docs/1.0.1/volumes-and-nodes/volume-size/ .

Also, Longhorn doesn't detect the volume usage from the filesystem's perspective at this moment. We're planning to address it with https://github.com/longhorn/longhorn/issues/925
