### ISSUE TITLE
[BUG] Longhorn volume random detachment from the workload in Rancher

### ISSUE THREAD

**Issue by mrcdb** [longhorn/longhorn#1657]
I am experiencing random malfunctions to Longhorn volumes with the pods of my Rancher environment. 

They are seen as attached to a pod from Longhorn UI, but I cannot access their data from inside the container. In particular, I see I/O errors from the logs or when accessing the mounted directories via shell. If I run `mount` from inside the container I can still see the mount point from the PVC to the local directory, but it's not accessible anymore.

It is sufficient to scale down and then up again the workload to re-connect the volume.

**To Reproduce**
1. From Rancher, create a new workload and create a new PVC by leveraging the Longhorn storage driver.
2. After some time (this is random to me) try to access the workload and `cd` to the volume dir
3. Receive I/O errors and malfunctions from the container
4. Scale down the workload from Rancher UI by reducing Config Scale from 1 to 0
5. Scale up the workload again from Rancher UI by incrementing Config Scale from 0 to 1
6. Try to access the workload and `cd` to the volume dir
7. You don't receive I/O errors anymore and can see the contents

**Expected behavior**
I expect the Longhorn volume to not detach from the container at any given time, as it can make the workload fail unexpectedly (e.g. if a volume is used to persist a private Docker registry).

**Log**
N/A.

**Environment:**
 - Longhorn version: 1.0.0
 - Kubernetes version: 1.17.5 (RKE)
 - Node OS type and version: Ubuntu Linux Server 18.04.4 LTS
 - Rancher version: 2.4.3

**Comment by joshimoo** [comment]
@mrcdb a volume detachment can happen for example when the volumes engine process crashes or there are resource exhaustions (network, cpu, etc). To mitigate this you should setup a liveness probe on your workload deployments, see example in the docs here: https://longhorn.io/docs/1.0.2/high-availability/recover-volume/ 

This will make sure that your workloads are automatically restarted in the case of a volume failure, which will then lead to a correct volume attachment/mount.

**Comment by mrcdb** [comment]
Hi @joshimoo , thanks for the suggestion. I have enabled liveness probes on the volume-equipped workloads as you proposed. I think this issue can be closed now.

**Comment by PhanLe1010** [comment]
@mrcdb 
FYI, in the incoming version (v1.1.0), we have changed the logic to handle the situation when Longhorn volume is detached unexpectedly. Basically, you will not have to do any extra setup. See more at:

Implementation: https://github.com/longhorn/longhorn-manager/pull/722

Docs: https://github.com/longhorn/website/pull/211

**Comment by mrcdb** [comment]
@PhanLe1010 this looks pretty good! I'm glad Longhorn will be able to automate the pod deletion if a volume detachment happens.
