### ISSUE TITLE
[Question] How to run longhorn on specific nodes

### ISSUE THREAD

**Issue by longlnk** [longhorn/longhorn#1658]
Hello,

- I have 6 nodes worker with named A, B, C, D, E, F. I run longhorn installed via Rancher catalog on our cluster and default longhorn will run on all nodes

- How to run all longhorn workloads on 3 node A, B, C?

- Because I use firewall between App (node D, E, F) and Backend (node A, B, C). So I need run all longhorn workloads on 3 node A, B, C
- Can you provide firewall port?
Please help me.

**Comment by shuo-wu** [comment]
You can refer to the comments in this issue:
https://github.com/longhorn/longhorn/issues/1633
