### ISSUE TITLE
[FEATURE] Context route support for Longhorn UI for reverse proxies

### ISSUE THREAD

**Issue by just1689** [longhorn/longhorn#1660]
**Is your feature request related to a problem? Please describe.**
The problem is that we need to host Longhorn-UI behind a reverse proxy on a context like /longhorn/
I could not find if this was supported in the docs or by Googling it. If it is supported this issue will help future engineers see that it is supported. Otherwise this issue could host the conversation around the possibility of supporting this feature.

**Describe the solution you'd like**
Support for an environment variable like HTTP_CONTEXT which can be left empty for no context or populated with a value like /longhorn to allow reverse proxies to route based on that context.

**Describe alternatives you've considered**
The alternative is to give longhorn it's own domain / subdomain. This is not an option for my organization and will look bad for our evaluation of the product.

**Additional context**
NA

**Comment by yasker** [comment]
@smallteeths Can you investigate if this is possible?

**Comment by smallteeths** [comment]
We can refactor our routing to distinguish front-end and back-end routing. Let front-end routing not depend on back-end routing. Because the structure of the routing is like this since 0.4.0, I need some time to self-test after the reconstruction. @yasker

**Comment by khushboo-rancher** [comment]
Verified on master - 08-11-2020
Longhorn UI is accessible through the reverse proxy. Tested by creating Nginx reverse proxy to the exposed service on node port.

Validation - **Passed**

Steps followed
1. Create a cluster (3 worker nodes and 1 etcd/control plane) in rancher.
2. Deploy the longhorn app with longhorn-frontend service as NodePort type.
3. Install Nginx in the local system.
4. Set the proxy_pass of http://node-ip:32282 where ```32282``` is the node port in ngnix.conf file. (My config looked like below)
```
events { worker_connections 1024; }
http {
  server {
    gzip on;
    gzip_min_length 1k;
    gzip_comp_level 2;
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png image/svg+xml;
    gzip_vary on;
    gzip_disable "MSIE [1-6]\.";
    listen 8223;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_redirect   off;
    proxy_set_header  Host       $http_host;
    proxy_set_header  X-Real-IP    $remote_addr;
    proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
    proxy_max_temp_file_size 0;
    proxy_connect_timeout   90;
    proxy_send_timeout     90;
    proxy_read_timeout     90;
    proxy_buffer_size     1024k;
    proxy_buffers       8 1024k;
    proxy_busy_buffers_size  1024k;
    proxy_temp_file_write_size 1024k;
    location / {
      proxy_pass "http://node-ip:32282/";
    }
  }
}
```
5. Start Nginx.
6. Access the port given in listen parameter from nginx.conf. ex - //localhost:8223

**Comment by just1689** [comment]
Morning

Just to confirm - this would would with a context route right? For example:
```
location /longhorn/ {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass http://node-ip:32282/;
}
```

**Comment by smallteeths** [comment]
It can be set arbitrarily, as long as the service can be found, now the front and back routes have been separated. @just1689
