### ISSUE TITLE
[BUG] UI: The volume details page shows blank page on refresh

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1666]
**Describe the bug**
The volume details page shows blank page on refresh

**To Reproduce**
1. Go to longhorn UI using rancher proxy, create a volume.
2. Click on volume. It takes the user to the volume detail page.
3. Refresh the page.
4. The page becomes blank.

**Expected behavior**
The page shouldn't become blank

**Log**
```
Refused to apply style from 'https://rancher-server/k8s/clusters/c-aaaaa/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/volume/styles.css?2d499130a89bfab9a0f0' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```
<img width="520" alt="Screen Shot 2020-08-04 at 11 10 55 AM" src="https://user-images.githubusercontent.com/60111667/89341314-f63d5400-d655-11ea-8a86-dbc1dd6a6951.png">

**Environment:**
 - Longhorn version: Longhorn master - f36388b
 - Kubernetes version: 18.6
 - Node OS type and version: Ubuntu 18.04

**Comment by smallteeths** [comment]
@khushboo-rancher  I did not reproduce this issues after updating the longhorn routing。[https://github.com/longhorn/longhorn/issues/1660](url)

**Comment by yasker** [comment]
@khushboo-rancher can you verify if this issue still exists?

**Comment by khushboo-rancher** [comment]
This is not reproducible anymore on the master.
Closing the issue.
