### ISSUE TITLE
[BUG] Backup is successful (as indicated on the UI) but the backup job/pod never stops running for a specific volume

### ISSUE THREAD

**Issue by onedr0p** [longhorn/longhorn#1667]
**Describe the bug**
Very odd behavior on one of my volumes, the rest seem to back up fine and the backup job/pod finishes.

Still running:

![image](https://user-images.githubusercontent.com/213795/89346538-38c35880-d677-11ea-953a-c0f527142cf9.png)

Trying to find logs in that pod:

```
$ k logs pod/pvc-b58ad35f-9b80-4778-a703-315e96e9e0a9-c-m9w1pw-c-159651n6wzc -n longhorn-system
<nothing>
```

UI says everything is fine:

![image (1)](https://user-images.githubusercontent.com/213795/89346575-4c6ebf00-d677-11ea-9aec-af1518448911.png)

More context in Slack

https://rancher-users.slack.com/archives/CC2UQM49Y/p1596468622360500

**To Reproduce**
Hard to tell seems pretty specific... 

**Expected behavior**
The backup job/pod to complete.

**Log**

Creating backups on the UI yields these errors for this volume:

```
Failed to backup snapshot b62520bb-be98-4dd4-afd5-20dc59f686ad with label map[KubernetesStatus:{\"pvName\":\"pvc-b58ad35f-9b80-4778-a703-315e96e9e0a9\",\"pvStatus\":\"Bound\",\"namespace\":\"default\",\"pvcName\":\"plex-config\",\"lastPVCRefAt\":\"\",\"workloadsStatus\":[{\"podName\":\"plex-64b86f76df-qw5cp\",\"podStatus\":\"Running\",\"workloadName\":\"plex-64b86f76df\",\"workloadType\":\"ReplicaSet\"}],\"lastPodRefAt\":\"\"}] for volume pvc-b58ad35f-9b80-4778-a703-315e96e9e0a9: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.0.1/longhorn [--url 10.42.5.218:10002 backup create --dest s3://longhorn@192.168.1.39/backups --label KubernetesStatus={\"pvName\":\"pvc-b58ad35f-9b80-4778-a703-315e96e9e0a9\",\"pvStatus\":\"Bound\",\"namespace\":\"default\",\"pvcName\":\"plex-config\",\"lastPVCRefAt\":\"\",\"workloadsStatus\":[{\"podName\":\"plex-64b86f76df-qw5cp\",\"podStatus\":\"Running\",\"workloadName\":\"plex-64b86f76df\",\"workloadType\":\"ReplicaSet\"}],\"lastPodRefAt\":\"\"} b62520bb-be98-4dd4-afd5-20dc59f686ad], output , stderr, time=\"2020-08-03T18:26:36Z\" level=info msg=\"Backing up b62520bb-be98-4dd4-afd5-20dc59f686ad on tcp://10.42.2.32:10135, to s3://longhorn@192.168.1.39/backups\
```

```
\"workloadsStatus\":[{\"podName\":\"plex-64b86f76df-qw5cp\",\"podStatus\":\"Running\",\"workloadName\":\"plex-64b86f76df\",\"workloadType\":\"ReplicaSet\"}],\"lastPodRefAt\":\"\"} c-m9w1pw-577f58cd], output , stderr, time=\"2020-08-03T17:42:21Z\" level=info msg=\"Backing up c-m9w1pw-577f58cd on tcp://10.42.2.32:10135, to s3://longhorn@192.168.1.39/backups\"\ntime=\"2020-08-03T17:43:21Z\" level=fatal msg=\"Error running create backup command: failed to create backup to s3://longhorn@192.168.1.39/backups for volume pvc-b58ad35f-9b80-4778-a703-315e96e9e0a9: rpc error: code = DeadlineExceeded desc = context deadline exceeded\"\n, error exit status 1"
```

**Environment:**
 - Longhorn version: 1.0.1
 - Kubernetes version: 1.18.3-k3s1
 - Node OS type and version: Ubuntu 20.04.1

The drives Longhorn are all using nvme and my nodes are connected via a single 10Gb link.

**Additional context**

I'll try to capture logs on the next schedule run.

**Comment by aspettl** [comment]
I have the same or a similar problem, on two different clusters (rarely on my private one, where Longhorn volumes are <2G and content is pretty static, every day on a bigger one with volumes up to 500G and up to almost 200G turnover per day on a single volume). So both very small snapshots and big snapshots seem to be affected. I use MinIO for backup storage.

On both clusters, I see a log message "Cleaned up snapshot" in the pod, nothing else, only that one line.
On my private cluster, I also saw the UI reporting the backup as done.
On the big cluster, the UI does not list the backup.

When I delete the backup pod, it is recreated and then, usually it works. But sometimes it gets stuck again.

**Comment by onedr0p** [comment]
I am still encountering this issue. I have noticed this is only for large volumes as well. Another thing I noticed is my backup retention is set to 7 days, however the backups for this volume do not get deleted. Maybe there is some timeout happening on trying to remove the old backups?

**Comment by aspettl** [comment]
I also have it. Every day, most of the time for 2 volumes.
When I delete the jobs and go to the UI, I see that Longhorn needs quite some time to merge snapshots.

It is not only about size, my guess would be that many changes over the day are more likely for larger volumes - and these many changes cause issues with cleaning up old stuff / merging old snapshots.

**Comment by onedr0p** [comment]
Everyday for me too, I get a notification from Prometheus Operator that a job is still running, so I have to manually delete it.

@yasker any thoughts on what is happening here?

**Comment by yasker** [comment]
@onedr0p I think you're right. Somehow the backup cleanup process or snapshot purge process cannot be completed successfully. So the backup has been recreated repeatedly. It shouldn't take extra space in the storage (S3 or NFS), but we do want to figure out what can be the reason for the cleanup to fail. Maybe for the bigger volume, backup deletion timed out.

**Comment by skolkmann** [comment]
I don't know whether this helps, but I do have the same issue as @aspettl. Multiple times a day, Longhorn CronJobs in Cluster1 get stuck in running with the the only line being

`time="2020-11-05T08:20:08Z" level=debug msg="Cleaned up snapshot c-sktm7m-4dc33a35 for pvc-b10c11f2-eafc-49a1-bcb6-bc935a9d50ad"`

This happens for all volumes in Cluster1. I use MinIO + Longhorn in Cluster2 to store the backups of Cluster1. Both clusters are currently running on single nodes, but don't even get close to 50% CPU or RAM (but could spike higher for seconds). Whether this is independent or separate, MinIO just as regularly stops working properly and logs the following Errors:

This one is no problem - MinIO keeps running and working
`API: SYSTEM()
04/11/2020 10:33:13 Time: 09:33:13 UTC 11/04/2020
04/11/2020 10:33:13 DeploymentID: cfe660d9-34df-41d2-a3db-a78ed71d7fa0
04/11/2020 10:33:13 Error: unexpected EOF
04/11/2020 10:33:13        3: cmd/data-usage-cache.go:452:cmd.(*dataUsageCache).load()
04/11/2020 10:33:13        2: cmd/fs-v1.go:267:cmd.(*FSObjects).CrawlAndGetDataUsage()
04/11/2020 10:33:13        1: cmd/data-crawler.go:108:cmd.runDataCrawler()`

These two mean problems - backups can neither be created nor read anymore
`API: PutObject(bucket=application-backups, object=backupstore/volumes/f8/e2/pvc-b10c11f2-eafc-49a1-bcb6-bc935a9d50ad/backups/backup_backup-fb4d2a32b08a43b9.cfg)
05/11/2020 09:25:45 Time: 08:25:20 UTC 11/05/2020
05/11/2020 09:25:45 DeploymentID: cfe660d9-34df-41d2-a3db-a78ed71d7fa0
05/11/2020 09:25:45 RequestID: 16448F19C9EEA207
05/11/2020 09:25:45 RemoteHost: 10.42.0.1
05/11/2020 09:25:45 Host: s3-backup-1.xxx.cloud
05/11/2020 09:25:45 UserAgent: aws-sdk-go/1.25.16 (go1.13.3; linux; amd64)
05/11/2020 09:25:45 Error: write /export/.minio.sys/buckets/application-backups/backupstore/volumes/f8/e2/pvc-b10c11f2-eafc-49a1-bcb6-bc935a9d50ad/backups/backup_backup-fb4d2a32b08a43b9.cfg/fs.json: input/output error
05/11/2020 09:25:45        4: cmd/api-errors.go:1979:cmd.toAPIErrorCode()
05/11/2020 09:25:45        3: cmd/api-errors.go:2004:cmd.toAPIError()
05/11/2020 09:25:45        2: cmd/object-handlers.go:1551:cmd.objectAPIHandlers.PutObjectHandler()
05/11/2020 09:25:45        1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()

API: ListObjectsV1(bucket=application-backups)
05/11/2020 09:26:02 Time: 08:26:02 UTC 11/05/2020
05/11/2020 09:26:02 DeploymentID: cfe660d9-34df-41d2-a3db-a78ed71d7fa0
05/11/2020 09:26:02 RequestID: 16448F26830773E4
05/11/2020 09:26:02 RemoteHost: 10.42.0.1
05/11/2020 09:26:02 Host: s3-backup-1.xxx.cloud
05/11/2020 09:26:02 UserAgent: aws-sdk-go/1.25.16 (go1.13.3; linux; amd64)
05/11/2020 09:26:02 Error: stat /export/application-backups: input/output error
05/11/2020 09:26:02        4: cmd/api-errors.go:1979:cmd.toAPIErrorCode()
05/11/2020 09:26:02        3: cmd/api-errors.go:2004:cmd.toAPIError()
05/11/2020 09:26:02        2: cmd/bucket-listobjects-handlers.go:407:cmd.objectAPIHandlers.ListObjectsV1Handler()
05/11/2020 09:26:02        1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()`

However, the MinIO pod does keep running all the time, no restarts, and logs these errors whenever something wants to read or write. The recurring backup problem, as well as the MinIO problem can be temporarily corrected by just deleting the corresponding pods (Longhorn CronJob pod that's stuck running and the MinIO pod).

Both clusters are running k3s v1.19.3+k3s1 on Ubuntu 20.04.1 LTS and use Longhorn 1.0.2.

**Comment by yasker** [comment]
@skolkmann Your issue might be a little different. Since you mentioned you're running Longhorn + MinIO on a single node cluster (and I assume Longhorn is making backup to the MinIO too), you don't need to have three replicas for the MinIO.

Also, are you using a spinning disk or SSD? It might be Longhorn experienced write latency on the physical disk level, which results in errors on the block level.

**Comment by skolkmann** [comment]
Cluster1 (VPS) runs workloads using Longhorn as StorageClass. That Longhorn instance uses Cluster2 (RS with SSD) - running MinIO + Longhorn - as backup target. Since Cluster2 is used for backups by other clusters, it does not itself store backups of the backups anywhere.

**Comment by yasker** [comment]
So the problem is with the Cluster2. You mentioned `but could spike higher for seconds`, which concerns me. The disconnection may happen when the spike happens. How many replicas you have with Cluster2 Longhorn setup?

Can you file another issue? Btw, what's `RS` you mentioned?

**Comment by skolkmann** [comment]
Everything is default, so Cluster2 Longhorn uses 3 replicas on the same node. By RS I mean Root Server (bare metal) and you could have already been right: it uses spinning disk (SAS) hard drive - not SSD as I said. Should have double-checked that, I'm sorry. Maybe 3 replicas on spinning disk is just too much for the system to handle? However I filed another issue #1968.

**Comment by innobead** [comment]
remove stale due to the incorrect exempt label

**Comment by yasker** [comment]
Now looking at this issue, the main issue might be caused by https://github.com/longhorn/longhorn/issues/2278 . Also https://github.com/longhorn/longhorn/issues/2507 might have a play too.

Both issues I mentioned here will be fixed in the upcoming v1.1.2 release.

**Comment by shuo-wu** [comment]
Besides, there are fixes for this kind of backup creation timeout issue in #2218 as well.

**Comment by onedr0p** [comment]
I am going to go ahead and close this issue too, looks like v1.2.0 might solve these problems. I will open a new bug report if there's any other issues. Thanks all!
