### ISSUE TITLE
[FEATURE] Clean up system generated snapshot automatically

### ISSUE THREAD

**Issue by Yomanz** [longhorn/longhorn#1669]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to clear out some hidden snapshots, they take a while to remove.

**Describe the solution you'd like**
A way to select mulitple volumes and delete them in one go

**Describe alternatives you've considered**
Deleting them individually and having incredible patience.

**Additional context**
![image](https://user-images.githubusercontent.com/5119107/89450932-4cdc8800-d753-11ea-8d14-e913b10f9e80.png)

**Comment by yasker** [comment]
One thing to work around this is, if you set up recurring snapshot or backup, those will get cleaned up automatically.

**Comment by Yomanz** [comment]
> One thing to work around this is, if you set up recurring snapshot or backup, those will get cleaned up automatically.

Maybe a way to cleanup hidden system ones automatically would be a better way then.

**Comment by yasker** [comment]
Yes, it's better for this to be done automatically.

We can provide a setting to run a cleanup job at a certain schedule. The cleanup job can go through all the volumes one by one and run `snapshot purge`. We don't want to run this on all the volumes at the same time, which will likely cause disk IO pressure.

If the user has already set a recurring schedule on the volume, then that volume can be skipped.

The input should a corn expression which can be validated. Leave it empty will disable the job. By default, it will be run at 1AM GMT.

The setting can be called `System generated snapshot cleanup schedule`.

**Comment by yasker** [comment]
There is another way to do this.

We can check and call `snapshot purge` after the rebuild is done, which will not coalesce the latest snapshot but if there is any snapshot before it, that should be dealt with automatically. Though there might be a performance impact during the time.

**Comment by boknowswiki** [comment]
Test case:

1. Create a volume and attached to a node.
2. Write some data to the volume.
3. Keep deleting the replicas, and trigger a system generated snapshots.
4. And make sure only the latest snapshot is left, and no more than one system generated snapshots.

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master 10/22/2020

Validation - **Pass**

Validated the below scenarios.
1. By default the setting ```Automatically Cleanup System Generated Snapshot``` is enabled.

With ```Automatically Cleanup System Generated Snapshot``` enabled
1. Deletion of the system created snapshot(one or multiple) on rebuild completion in a volume.
1. Deletion of the system created snapshot in a restored volume. - Initially, when a volume is restored and there is only one system created snapshot, it doesn't get deleted. Later if there is a rebuild, longhorn deletes the older snapshot and retains one latest snapshot.
1. Deletion of the system created snapshot in a DR volume - On incremental restore, the older system created snapshots get deleted.

With ```Automatically Cleanup System Generated Snapshot``` disabled
1. No deletion of system created snapshot observed.

**Comment by khushboo-rancher** [comment]
Integration test is 'test_cleanup_system_generated_snapshots' running fine. This is good to close now.
https://ci.longhorn.io/job/public/job/longhorn-tests/142/testReport/tests/test_basic/test_cleanup_system_generated_snapshots/
