### ISSUE TITLE
[BUG]The image cannot be pulled from the private image repository due to lack of secret if not customize setting

### ISSUE THREAD

**Issue by xiaoluhong** [longhorn/longhorn#1670]
**Describe the bug**
Even if the privateRegistry parameter is configured correctly, the image cannot be pulled from the private image repository when using Default Settings

**To Reproduce**
1. Set Longhorn's image repo to private mode(You need to be logged in to pull the image)
2. Run the Longhorn Catalog in the Rancher UI and configure the `PRIVATE REGISTRY URL, username, and password` in the PRIVATE REGISTRY SETTINGS
3. Set Customize Default Settings to False
4. Leave the default values for the other parameters
5. need to delete the Longhorn image already on the host （`docker images | grep longhornio | awk '{print $3}' | xargs docker rmi -f`）
6. Finally, click Launch

**results**

1. Unable to pull the image
![image](https://user-images.githubusercontent.com/20707603/89676205-dc359700-d91d-11ea-86c0-d66ef0fb1b2b.png)
2. ImagePullSecrets are not in the Pod YAML file

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 10.60.0.75/32
    cni.projectcalico.org/podIPs: 10.60.0.75/32
  creationTimestamp: "2020-08-07T18:18:40Z"
  generateName: longhorn-manager-
  labels:
    app: longhorn-manager
    app.kubernetes.io/instance: longhorn-system
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.0.1
    controller-revision-hash: ff5464f98
    helm.sh/chart: longhorn-1.0.1
    io.cattle.field/appId: longhorn-system
    pod-template-generation: "1"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:controller-revision-hash: {}
          f:helm.sh/chart: {}
          f:io.cattle.field/appId: {}
          f:pod-template-generation: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"66a30ba2-c59e-4a3e-8a75-bb682f00d46d"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:affinity:
          .: {}
          f:nodeAffinity:
            .: {}
            f:requiredDuringSchedulingIgnoredDuringExecution:
              .: {}
              f:nodeSelectorTerms: {}
        f:containers:
          k:{"name":"longhorn-manager"}:
            .: {}
            f:command: {}
            f:env:
              .: {}
              k:{"name":"DEFAULT_SETTING_PATH"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"NODE_NAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef:
                    .: {}
                    f:apiVersion: {}
                    f:fieldPath: {}
              k:{"name":"POD_IP"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef:
                    .: {}
                    f:apiVersion: {}
                    f:fieldPath: {}
              k:{"name":"POD_NAMESPACE"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef:
                    .: {}
                    f:apiVersion: {}
                    f:fieldPath: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":9500,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:readinessProbe:
              .: {}
              f:failureThreshold: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:tcpSocket:
                .: {}
                f:port: {}
              f:timeoutSeconds: {}
            f:resources: {}
            f:securityContext:
              .: {}
              f:privileged: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/host/dev/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/host/proc/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/lib/longhorn-setting/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/lib/longhorn/"}:
                .: {}
                f:mountPath: {}
                f:mountPropagation: {}
                f:name: {}
              k:{"mountPath":"/var/run/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:terminationGracePeriodSeconds: {}
        f:tolerations: {}
        f:volumes:
          .: {}
          k:{"name":"dev"}:
            .: {}
            f:hostPath:
              .: {}
              f:path: {}
              f:type: {}
            f:name: {}
          k:{"name":"longhorn"}:
            .: {}
            f:hostPath:
              .: {}
              f:path: {}
              f:type: {}
            f:name: {}
          k:{"name":"longhorn-default-setting"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
            f:name: {}
          k:{"name":"proc"}:
            .: {}
            f:hostPath:
              .: {}
              f:path: {}
              f:type: {}
            f:name: {}
          k:{"name":"varrun"}:
            .: {}
            f:hostPath:
              .: {}
              f:path: {}
              f:type: {}
            f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-08-07T18:18:40Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:cni.projectcalico.org/podIP: {}
          f:cni.projectcalico.org/podIPs: {}
    manager: calico
    operation: Update
    time: "2020-08-07T18:18:44Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.60.0.75"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2020-08-07T18:22:18Z"
  name: longhorn-manager-6858r
  namespace: longhorn-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: longhorn-manager
    uid: 66a30ba2-c59e-4a3e-8a75-bb682f00d46d
  resourceVersion: "219042"
  selfLink: /api/v1/namespaces/longhorn-system/pods/longhorn-manager-6858r
  uid: 19258ff3-8703-4161-9cae-41d46c428c09
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - xie-node001
  containers:
  - command:
    - longhorn-manager
    - -d
    - daemon
    - --engine-image
    - registry.cn-hangzhou.aliyuncs.com/longhornio/longhorn-engine:v1.0.1
    - --instance-manager-image
    - registry.cn-hangzhou.aliyuncs.com/longhornio/longhorn-instance-manager:v1_20200514
    - --manager-image
    - registry.cn-hangzhou.aliyuncs.com/longhornio/longhorn-manager:v1.0.1
    - --service-account
    - longhorn-service-account
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: DEFAULT_SETTING_PATH
      value: /var/lib/longhorn-setting/default-setting.yaml
    image: registry.cn-hangzhou.aliyuncs.com/longhornio/longhorn-manager:v1.0.1
    imagePullPolicy: IfNotPresent
    name: longhorn-manager
    ports:
    - containerPort: 9500
      name: manager
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 9500
      timeoutSeconds: 1
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host/dev/
      name: dev
    - mountPath: /host/proc/
      name: proc
    - mountPath: /var/run/
      name: varrun
    - mountPath: /var/lib/longhorn/
      mountPropagation: Bidirectional
      name: longhorn
    - mountPath: /var/lib/longhorn-setting/
      name: longhorn-default-setting
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: longhorn-service-account-token-l47hl
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: xie-node001
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: longhorn-service-account
  serviceAccountName: longhorn-service-account
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  volumes:
  - hostPath:
      path: /dev/
      type: ""
    name: dev
  - hostPath:
      path: /proc/
      type: ""
    name: proc
  - hostPath:
      path: /var/run/
      type: ""
    name: varrun
  - hostPath:
      path: /var/lib/longhorn/
      type: ""
    name: longhorn
  - configMap:
      defaultMode: 420
      name: longhorn-default-setting
    name: longhorn-default-setting
  - name: longhorn-service-account-token-l47hl
    secret:
      defaultMode: 420
      secretName: longhorn-service-account-token-l47hl
```

**Analysis**
Setting Customize Default Settings to False is equivalent to using the Default Settings configuration parameter.

The default value of the registrySecret in Values.yaml is empty, the configuration of ImagePullSecrets is skipped when passed to the backend.

![image](https://user-images.githubusercontent.com/20707603/89636667-8cce7700-d8db-11ea-8a17-b0c615d09afa.png)
![image](https://user-images.githubusercontent.com/20707603/89636618-7aecd400-d8db-11ea-9843-999e0adccec4.png)

https://github.com/xiaoluhong/longhorn/blob/5738f47bf9d776c8357d031182dc01fdc22aeb0b/chart/values.yaml#L57
https://github.com/xiaoluhong/longhorn/blob/5738f47bf9d776c8357d031182dc01fdc22aeb0b/chart/templates/deployment-driver.yaml#L109

**Feature Suggestions**
We should make a judgment：

1. only privateRegistry is configured and no registrySecret is configured, 

In this scenario, the user might know the account and password for the mirror repository, but not have the authority to create the registrySecret. we should automatically generate an imagePullSecrets based on privateRegistry. 

2. Only registrySecret is configured without privateRegistry
In this scenario, the user does not know the account and password of the image repository, but there is already a registrySecret created by the administrator that we can reuse directly.

3. PrivateRegistry and registrySecret are configured simultaneously
Combine the first two scenarios

**Comment by yasker** [comment]
@xiaoluhong The default value will be overridden by user settings. What's the step to reproduce the issue?

**Comment by yasker** [comment]
@meldafrawi @PhanLe1010 In the current process, how would the user add the secret for the private registry? It seems we require the user to add both the plain text username/password, as well as the secret to install Longhorn correctly.

**Comment by PhanLe1010** [comment]
@yasker 
In the current process, to use private registry:

## Using Rancher UI:
User need to add url/username/password and **specify a name for registry secret**. Longhorn will automatically create a secret with the name and encoding the url/username/password into it.

<img width="1455" alt="Screen Shot 2020-08-07 at 2 35 31 PM" src="https://user-images.githubusercontent.com/22139961/89690586-baa3c380-d8bb-11ea-8b87-908d1959b71b.png">

**Comment by yasker** [comment]
This makes sense. Though `Private Registry Secret` is in the default setting section, which might be the reason of confusion for the user. Is there a better way to avoid confusion?

**Comment by PhanLe1010** [comment]
Should we move the setting `Private Registry Secret` to section `Private Registry Setting` to avoid the confusion?

**Comment by PhanLe1010** [comment]
Also, Can we remove the `Generate` button next to `Private registry password` ? It confused me the first time bc I don't know whether I should click `Generate` or not. I had to try both to see which way work.

**Comment by yasker** [comment]
> Should we move the setting `Private Registry Secret` to section `Private Registry Setting` to avoid the confusion?

We can, but it also means we need to automatically enable `Customize default settings`. Also, what if the user is updating the Longhorn deployment? then the `Private registry secret` won't be applied. Need to think about that as well.

Regarding the `Generate` button, I think it's a limitation from Rancher. It should be gone in v2.5.

**Comment by PhanLe1010** [comment]
@yasker 

Yes, I will think more about this. Can you assign priority for this issue? If it is not top priority, I will work on other issues first.

**Comment by xiaoluhong** [comment]
A similar problem was found today. 
I want to specified nodes to deploy Longhorn, but the **default Settings** I use. it's collapsed, so I don't see the corresponding configuration items. Finally I found this configuration option in the documentation: https://longhorn.io/docs/1.0.2/references/settings/#create-default-disk-on-labeled-nodes. 
So I feel like this option shouldn't be a setting parameter for Longhorn, it should be a scheduling function setting.

**Comment by yasker** [comment]
@xiaoluhong It's not designed to be a setting parameter. It's designed to use Kubernetes labels/annotations to make it easy for the user to customize it in Kubernetes in a per-node basis.

**Comment by yasker** [comment]
Longhorn is bundled with Rancher 2.5 airgap installation. Let's check again once v2.5 is made available.

**Comment by PhanLe1010** [comment]
**Test Steps:**
1. Import new Longhorn chart at the branch v1.1.0 of the repo longhorn/longhorn
1. Copy all Longhorn require images to your private registry

New installation with the correct password :
1. Install Longhorn using the new chart. Specify `registry`, `username`, `password`, `registry secret name` in `private registry section`
1. Verify that Longhorn installation succeeds

New installation with the wrong password :
1. Clean all Longhorn images in your worker nodes.
1. Install Longhorn using the new chart. Specify `registry`, `username`, `password`, `registry secret name` in `private registry section`. Make sure that the `password` is incorrect
1. Verify that the Longhorn installation is stuck. 
1. Upgrade the failed instance to use the correct password. Verify the installation succeeds

Upgrade with the correct password :
1. Clean all Longhorn images in your worker nodes.
1. Update the existing Longhorn deployment. Using the new name for `registry secret` and the correct password
1. Verify the upgrade succeeds

Upgrade with the correct password :
1. Clean all Longhorn images in your worker nodes.
1. Update the existing Longhorn deployment. Using the new name for `registry secret` and the wrong password
1. Verify that the Longhorn upgrade is stuck.
1. Wait for the upgrade to fail because of timeout (5-6 mins) 
1. Upgrade the failed instance to use the correct password. Verify the upgrade succeeds

Repeat the above steps in the new `cluster explorer` UI in Rancher 2.5

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Rancher (**Cluster Manager UI**):
- New installation with the correct password: **(PASSED)**
- New installation with the wrong password : **(PASSED)**
- Upgrade with the correct password: **(PASSED)**
- Upgrade with the wrong password: **(PASSED)**
- Upgrade from older Longhorn version: **(PASSED)** 

Rancher (**Cluster Explorer UI**):
- New installation with the correct password: **(PASSED)**
- New installation with the wrong password : **(PASSED)**
- Upgrade with the correct password: **(PASSED)**
- Upgrade with the wrong password: **(PASSED)**
- Upgrade from older Longhorn version: **(PASSED)**
