### ISSUE TITLE
backport: Pod Security Policy Should be used instead of privileged 

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1671]
https://github.com/longhorn/longhorn/issues/608

**Comment by khushboo-rancher** [comment]
Verified on longhorn-v1.0.2-rc1

Validation - **Passed**
PSP gets installed along with longhorn other deployments.
```
kubectl get psp
NAME               PRIV   CAPS        SELINUX    RUNASUSER   FSGROUP    SUPGROUP   READONLYROOTFS   VOLUMES
longhorn-psp       true   SYS_ADMIN   RunAsAny   RunAsAny    RunAsAny   RunAsAny   false            configMap,downwardAPI,emptyDir,secret,projected,hostPath
```

**Scenarios tested:**
1. Longhorn deployed on a cluster where PSP is enabled as ```restricted```.
2. Longhorn deployed on a cluster where PSP is enabled as ```unrestricted```.
3. Longhorn deployed on a cluster where PSP is disabled.
4. Upgrade longhorn on a cluster PSP enabled/disabled.
