### ISSUE TITLE
[FEATURE] Online volume expansion

### ISSUE THREAD

**Issue by oscni** [longhorn/longhorn#1674]
**Is your feature request related to a problem? Please describe.**
Running out of space inside containers causes all kind of bad problems

**Describe the solution you'd like**
Online expansion of volumes

**Describe alternatives you've considered**
Space reclaim would probably be the best alternative but since it does not seem to work we can't oversize the volumes as they will just grow forever if you have an application which both deletes and writes data. But with online expansion it would at least be possible to auto expand volumes, can of course be done prettier if longhorn knows the real usage inside the container.

**Comment by huskar-t** [comment]
@yasker Is this feature progress?

**Comment by jabbermouth** [comment]
The ideal solution for me would be to update the PVC that created a volume and the volume will resize to match the new PVC without needing to detach the volume first.

**Comment by iTaybb** [comment]
Very relevant for us.

**Comment by Martin-Weiss** [comment]
+1

**Comment by m3nax** [comment]
> This feature is mandatory to allow "no downtime" for applications in case of a resize of data area in case of statefull sets with > replica >1.

Like sql databases.

Any update?

**Comment by iosifnicolae2** [comment]
> > This feature is mandatory to allow "no downtime" for applications in case of a resize of data area in case of statefull sets with replica >1.
> 
> Like sql databases.
> 
> Any update?

@m3nax you can deploy a HA database with two pods( 1 master, 1 slave) using [Crunchy Operator](https://github.com/CrunchyData/postgres-operator) for PostgreSQL. 
When the master pod is down, the slave pod will be promoted automatically.

**Comment by PierreF** [comment]
Either I'm missing something, or the resize is difficult to use if you want to minimize downtime. My use case is any replicated stateful store (etcd, Cassandra, ...). For example, I've one statefulset with replicas=3 and I want to grow disk without downtime. I'm fine stopping them one by one... but I can't:
* Re-scaling to 2 replicas will only stop the same last replica (so this one is easy to grow)
* Deleting a pod (kubectl delete cassandra-1) don't let longhorn the time to do resize

My only hack today is to:
* edit the statefulset, change updateStrategy to OnDelete and add a nodeSelector "schedule_me: no_where"
* delete one pod, which will stay in Pending due to the nodeSelector
* Wait for resize
* Remove the nodeSelector & re-delete the pod that stay in pending
* Repeat all those steps for all other PODs

Could it be doable for longhorn to intercept mount/unmount request and do the resize at that time ? Or marking a volume as to be put in maintenance and disable the ability for Kubernetes to re-mount this volume until maintenance is completed ?

**Comment by bmalynovytch** [comment]
> My only hack today is to:
> 
> * edit the statefulset, change updateStrategy to OnDelete and add a nodeSelector "schedule_me: no_where"
> * delete one pod, which will stay in Pending due to the nodeSelector
> * Wait for resize
> * Remove the nodeSelector & re-delete the pod that stay in pending
> * Repeat all those steps for all other PODs

You may also cordon all nodes when starting the resize, delete the pod you wish to resize, wait for it to be resized, uncordon,  start over for the other pods. 
Still way too complicated though ...

**Comment by shuo-wu** [comment]
Need to avoid the issue we found before when implementing this feature: https://github.com/longhorn/longhorn/issues/1040

**Comment by chriscchien** [comment]
Verified in longhorn master-head images and v1.4.x head images with [steps](https://github.com/shuo-wu/longhorn-tests/blob/online-expansion/docs/content/manual/release-specific/v1.4.0/test-online-expansion.md)
Result **Pass**

- Precondition
   - 5Gi file and md5sum calculated (/mnt/data)
   - Create volume and attached to node
1. Execute `dd if=/mnt/data of=/dev/longhorn/<volume> bs=1M `, do volume expansion while file copying, volume expansion succeed, volume md5sum correct and no I/O error log observed in instance-manager pods
2. Execute `dd if=/dev/longhorn/<volume> bs=1M count=5000 status=none | md5sum`  do volume expansion while command executing, volume expansion succeed, volume md5sum correct and no I/O error log observed in instance-manager pods
3. Upgrade from v1.3.2  to master-head and v1.4.x-head
   - Volume with old engine image + old instance manager, expansion get stuck and the expansion can be cancelled
   - Volume with new engine image + old instance manager, expansion get stuck and the expansion  can be cancelled
   - Volume with old engine image + new instance manager, expansion get stuck and the expansion  can be cancelled
   - Volume with new engine image + new instance manager, expansion succeed and md5sum were correct.

**Comment by innobead** [comment]
Reopening this first, because the doc update is not ready yet. cc @shuo-wu 

Also, as discussed, we need to test dynamically provisioned volume with the managed workload like statefulset/deployment, and see if it works as expected. cc @longhorn/qa

**Comment by chriscchien** [comment]
Also verified in longhorn master-head images and v1.4.x head images by using workloads and edit PVC to do volume expansion
Result **Pass**

0. Precondition
   - 5Gi file and md5sum calculated (/mnt/data)
   - Deploy [statefulset](https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml) (storage: 6Gi)
1. Execute `kubectl cp /mnt/data web-0:/usr/share/nginx/html/data` do volume expansion by edit pvc while file copying, volume expansion succeed, volume md5sum correct and no I/O error log observed in instance-manager pods
2. Upgrade from v1.3.2 to master-head and v1.4.x-head,  do volume expansion by edit PVC
   - Volume with old engine image + old instance manager, expansion get stuck and the expansion can be cancelled
   - Volume with new engine image + old instance manager, expansion get stuck and the expansion can be cancelled
   - Volume with old engine image + new instance manager, expansion get stuck and the expansion can be cancelled
   - Volume with new engine image + new instance manager, expansion succeed and md5sum were correct.

**Comment by khushboo-rancher** [comment]
@chriscchien Let's do some more negative testing like below scenarios:
1. Attached node reboot/network disconnect/deletion during the expansion.
2. Trigger some operation like replica deletion/eviction during the online expansion. (Not sure if that's allowed using the GUI)
3. Triggering expansion when rebuilding/restoration is in progress. (Covered in [automation](https://github.com/longhorn/longhorn-tests/pull/1223), pending to merge)

**Comment by innobead** [comment]
> 1. Attached node reboot/network disconnect/deletion during the expansion.

@shuo-wu @derekbit will this one be a concern? I remember we will do the size correction when starting the controller (volume engine).

**Comment by shuo-wu** [comment]
Yes, this is a valid concern but I haven't tested it. Ideally, the size correction should work.

**Comment by innobead** [comment]
This has been improved in https://github.com/longhorn/longhorn/issues/3601 by @derekbit , so if the size is not matched, the downstream replica will be discarded. 

https://github.com/longhorn/longhorn-engine/blob/a32136397a0d5044cd2744080d4129c6943d738d/pkg/controller/control.go#L764-L767

**Comment by chriscchien** [comment]
Verified in v1.4.x-head images, below were test result

0. Dynamic provision volume by [statefulset](https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml) (1 pod replica)
1. Attached node reboot/network disconnect/deletion during the expansion.
   - reboot - pass
   - network disconnect - pass
   - node deletion - volume attached to down node, so the expansion stuck
2. Trigger some operation like replica deletion/node eviction during the online expansion - pass
3. Triggering expansion when replica rebuilding/ volume restoration is in progress - pass

**Comment by innobead** [comment]
> Verified in v1.4.x-head images, below were test result
> 
> 0. Dynamic provision volume by [statefulset](https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml) (1 pod replica)
>    * node deletion - volume attached to down node, so the expansion stuck

As discussed, this should be related to the volume attachment and it is not deleted by Kubernetes somehow. What's the result after deleting the VA? (I assumed you delete the SS pod to make it failover, correct?)

**Comment by chriscchien** [comment]
After delete the volumeattachment, when new pod created there will be a new VA created and `nodeName` pointed to up, node, but when `execute kubectl get volume <volume> -n longhorn-system` in status, the `nodeID` pointed to the down node

**Comment by innobead** [comment]
> After delete the volumeattachment, when new pod created there will be a new VA created and `nodeName` pointed to up node, but when `execute kubectl get volume <volume> -n longhorn-system` , in the status field, the `nodeID` pointed to the down node

This is more about the pod failover. @shuo-wu any idea?

**Comment by shuo-wu** [comment]
This is unrelated to the online expansion. No, I have not checked this VA-related issue for a long time. If the volume & the pod get stuck on a down node, IIRC, typically we will try to forcibly delete the pod (rather than directly deleting VA). Does the volume get detached after deleting the VA?

**Comment by innobead** [comment]
> This is unrelated to the online expansion. No, I have not checked this VA-related issue for a long time. If the volume & the pod get stuck on a down node, IIRC, typically we will try to forcibly delete the pod (rather than directly deleting VA). Does the volume get detached after deleting the VA?

Yeah, this is what @chriscchien has done, but it seems the volume is still not detached. @derekbit is also checking. 

Even though this is not yet online expansion, it's good to know what cause it is and see if this is a regression or a day 1 issue.

**Comment by innobead** [comment]
The fix to that has been built to the latest 1.4.x-head image, so please re-validate the below issues again. Thanks!

> 0. Dynamic provision volume by [statefulset](https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml) (1 pod replica)
> 1. Attached node reboot/network disconnect/deletion during the expansion.
>    
>    * reboot - pass
>    * network disconnect 100sec - pass
>    * node deletion - volume attached to down node, so the expansion stuck

**Comment by chriscchien** [comment]
Did many times of node reboot/network disconnect while volume expansion, after node up/reconnect, there had chance pod won't come up and logged https://github.com/longhorn/longhorn/issues/5171 for tracking

**Comment by chriscchien** [comment]
For test item **node deletion - volume attached to down node**, verified in latest v1.4.x image, worked well, volume will attach to another node and pod become running/data kept consistent
