### ISSUE TITLE
[BUG]Need to clean failed to scheduled extra replica if there is no eviction.

### ISSUE THREAD

**Issue by boknowswiki** [longhorn/longhorn#1679]
**Describe the bug**
After increase the replica count number and decrease it back, the extra failed to scheduled replica stays in longhorn. We need to clean it up.

**To Reproduce**
1. Deploy a longhorn with 3 nodes in k8s cluster.
2. Create a volume with 3 replicas, everything should be done correctly.
3. Increase the replica number on this volume to 4. There should be a failed scheduled replica.
4. Decrease the replica number to 3, the extra failed scheduled replica stays there.

**Expected behavior**
The extra failed scheduled replica should be cleaned up. If there is no eviction on the disks or nodes.

**Log**
```
[longhorn-manager-5m4wj] time="2020-08-13T00:22:25Z" level=error msg="There's no available disk for replica test-r-cae0f985, size 21474836480" 
[longhorn-manager-5m4wj] time="2020-08-13T00:22:25Z" level=error msg="unable to schedule replica test-r-cae0f985 of volume test" 
[longhorn-manager-5m4wj] time="2020-08-13T00:22:25Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"test\", UID:\"e30f8fa2-2ec8-464e-9310-a83ed1d1c25f\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"12395182\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedEviction' Can not find resource for scheduling replica test-r-cae0f985." 
[longhorn-manager-566fn] time="2020-08-13T00:22:25Z" level=debug msg="Updated volume test replica count from 4 to 3" 
```

**Environment:**
 - Longhorn version:v1.0.1
 - Kubernetes version:v1.17.5
 - Node OS type and version:Ubuntu18.04

**Additional context**
The cleanup should be happen when there is no eviction, meaning the eviction has been cancelled if there is a previous one.
This is also related to [298](https://github.com/longhorn/longhorn/issues/298) for auto-cleanup.

https://github.com/longhorn/longhorn/issues/298

**Comment by khushboo-rancher** [comment]
Verified on Longhorn master - 09/10/2020

Validation - **Pass**

The failed replica is getting clean up.

**Steps followed:**
1. Deploy a longhorn with 3 nodes in the k8s cluster.
2. Create a volume with 3 replicas.
3. Increase the replica number on this volume to 4. There should be a failed scheduled replica.
4. Decrease the replica number to 3, the extra failed scheduled replica stays there.
