### ISSUE TITLE
[Question] each replica is a container ?

### ISSUE THREAD

**Issue by xuyinhao** [longhorn/longhorn#1682]
https://longhorn.io/docs/1.0.0/concepts/

In the figure below,
Each Longhorn volume has two replicas, and **each replica is a container**.

I just find  all  replicas in a container named  k8s_**replica-manager_instance-manager-r-**62ac0296_longhorn-system_df7e1d0c-db09-420a-98a8-c275ee574b72_0.

thx

[root@node221 ~]# docker exec -it 877b502e916c sh 
# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 Aug11 ?        00:00:07 /tini -- longhorn-instance-manager --debug daemon --listen 0.0.0.0:8500
root         6     1  1 Aug11 ?        01:18:46 longhorn-instance-manager --debug daemon --listen 0.0.0.0:8500
root      9477     6  0 Aug13 ?        00:00:54 /host/var/lib/longhorn/engine-binaries/abcsys.cn-5000-longhornio-longhorn-engine-v1.0.1/longhorn replica /host/var/lib/longhorn/replicas/lhqd-1-3g-iscsi-c0ed56fd
root      9485  9477  0 Aug13 ?        00:01:19 /host/var/lib/longhorn/engine-binaries/abcsys.cn-5000-longhornio-longhorn-engine-v1.0.1/longhorn sync-agent --listen 0.0.0.0:10017 --replica 0.0.0.0:10015 --list
root     21391     6  0 00:50 ?        00:00:01 /host/var/lib/longhorn/engine-binaries/abcsys.cn-5000-longhornio-longhorn-engine-v1.0.1/longhorn replica /host/var/lib/longhorn/replicas/blk1-f0a3022c --size 107
root     21397     6  0 00:50 ?        00:00:01 /host/var/lib/longhorn/engine-binaries/abcsys.cn-5000-longhornio-longhorn-engine-v1.0.1/longhorn replica /host/var/lib/longhorn/replicas/pvc-b2f25ebe-17a4-4156-a
root     21403 21391  0 00:50 ?        00:00:00 /host/var/lib/longhorn/engine-binaries/abcsys.cn-5000-longhornio-longhorn-engine-v1.0.1/longhorn sync-agent --listen 0.0.0.0:10002 --replica 0.0.0.0:10000 --list
root     21411 21397  0 00:50 ?        00:00:00 /host/var/lib/longhorn/engine-binaries/abcsys.cn-5000-longhornio-longhorn-engine-v1.0.1/longhorn sync-agent --listen 0.0.0.0:10032 --replica 0.0.0.0:10030 --list
root     21417     6  0 00:50 ?        00:00:00 /host/var/lib/longhorn/engine-binaries/abcsys.cn-5000-longhornio-longhorn-engine-v1.0.1/longhorn replica /host/home/replicas/mytest2-98c874d0 --size 21474836480 
root     21424 21417  0 00:50 ?        00:00:00 /host/var/lib/longhorn/engine-binaries/abcsys.cn-5000-longhornio-longhorn-engine-v1.0.1/longhorn sync-agent --listen 0.0.0.0:10047 --replica 0.0.0.0:10045 --list
root     22835     0  0 Aug13 pts/0    00:00:00 sh
root     24709     0  0 01:09 pts/1    00:00:00 sh
root     24727 24709  0 01:09 pts/1    00:00:00 ps -ef

**Comment by yasker** [comment]
@xuyinhao it's a doc bug. It's no longer a container since v0.6.0. It's a process now. We will fix the doc.
