### ISSUE TITLE
[BUG]InvalidArgument desc = There is no block device frontend for volume vi01

### ISSUE THREAD

**Issue by xuyinhao** [longhorn/longhorn#1683]
I used longhorn UI create volumn and  Create PV/PVC,then used https://longhorn.io/docs/1.0.1/references/examples/#simple-pod to create pod .

Pod status :  ContainerCreating

Block type volume no this issue

[root@master220 home]# kubectl  get pvc 
NAME   STATUS   VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS      AGE
vb01   Bound    vb01     2Gi        RWO            longhorn-static   53m
vi01   Bound    vi01     3Gi        RWO            longhorn-static   53m

**[root@master220 home]# kubectl  describe  pod  longhorn-simple-pod-iscsi**
Name:         longhorn-simple-pod-iscsi
...
Volumes:
  volv:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  vi01
    ReadOnly:   false
  default-token-qkflr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-qkflr
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                  From                         Message
  ----     ------                  ----                 ----                         -------
  Normal   Scheduled               <unknown>            default-scheduler            Successfully assigned default/longhorn-simple-pod-iscsi to node222.bocloud.cn
  Normal   SuccessfulAttachVolume  43m                  attachdetach-controller      AttachVolume.Attach succeeded for volume "vi01"
  Warning  FailedMount             12m (x23 over 43m)   kubelet, node222.bocloud.cn  MountVolume.SetUp failed for volume "vi01" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = InvalidArgument desc = There is no block device frontend for volume vi01
  Warning  FailedMount             7m35s (x3 over 30m)  kubelet, node222.bocloud.cn  Unable to attach or mount volumes: unmounted volumes=[volv], unattached volumes=[default-token-qkflr volv]: timed out waiting for the condition
  Warning  FailedMount             3m1s (x15 over 41m)  kubelet, node222.bocloud.cn  Unable to attach or mount volumes: unmounted volumes=[volv], unattached volumes=[volv default-token-qkflr]: timed out waiting for the condition

**UI status**
State: Attached
Health: Healthy
Ready for workload:Ready
Conditions:
restore
scheduled
Frontend:iSCSI
Attached Node & Endpoint:
node222.bocloud.cn
iscsi://10.10.36.225:3260/iqn.2019-10.io.longhorn:vi01/1
Size:
3 Gi
Actual Size:0 Bi
Base Image:
Engine Image:abcsys.cn:5000/longhornio/longhorn-engine:v1.0.1
Created:an hour ago
Node Tags:
Disk Tags:
Last Backup:
Last Backup At:
Instance Manager:
instance-manager-e-2b8f0fb4
Namespace:default
PVC Name:vi01
PV Name:vi01
PV Status:Bound
Pod Name:longhorn-simple-pod-iscsi
Pod Status:Pending
Workload Name:
Workload Type:

**[root@node221 /]# service iscsid status**
Redirecting to /bin/systemctl status iscsid.service
● iscsid.service - Open-iSCSI
   Loaded: loaded (/usr/lib/systemd/system/iscsid.service; disabled; vendor preset: disabled)
   Active: active (running) since 五 2020-08-14 10:04:08 CST; 29min ago
     Docs: man:iscsid(8)
           man:iscsiuio(8)
           man:iscsiadm(8)

**Comment by shuo-wu** [comment]
Notice that you are using the frontend `iSCSI`, hence the pod cannot find a block device file then mount it automatically after the attachment. 
You can check this [doc](https://longhorn.io/docs/1.0.1/advanced-resources/iscsi/) to see how to use Longhorn volume with frontend `iSCSI`.

**Comment by xuyinhao** [comment]
thx
The Longhorn CSI driver doesn’t support iSCSI mode.

Attached Node & Endpoint:
node222.bocloud.cn
iscsi://10.10.36.225:3260/iqn.2019-10.io.longhorn:vi01/1

The above information can be used to connect to the iSCSI target provided by Longhorn using an iSCSI client.
