### ISSUE TITLE
[BUG] Too many logs for ''Remount' failure.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1684]
**Describe the bug**
Below logs is appearing lots of times when the attached node is rebooted.
```
[longhorn-manager-7tdc9] time="2020-08-14T03:36:21Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"restore-vol-1\", UID:\"f11079c0-94fb-4bdc-99b9-c9c0b0a36559\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"6426\", FieldPath:\"\"}): type: 'Warning' reason: 'Remount' cannot proceed to remount restore-vol-1 on khush-test-logs-wk1: there is not any available mount point for volume restore-vol-1" 
```

**To Reproduce**
1. Restore a volume
2. Attach to a node
3. Reboot the node
4. Check the longhorn-manager logs

**Expected behavior**
Logs should not get generated for infinite times.

**Log**
```
[longhorn-manager-bmj9k] time="2020-08-13T22:27:14Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"restore-test-2\", UID:\"e16af0f5-d83c-49cb-817f-c081d7e03e0e\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"47935\", FieldPath:\"\"}): type: 'Normal' reason: 'Attached' volume restore-test-2 has been attached to khush-test-lh-wk1" 
[longhorn-manager-bmj9k] time="2020-08-13T22:27:16Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"restore-test-2\", UID:\"e16af0f5-d83c-49cb-817f-c081d7e03e0e\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"48043\", FieldPath:\"\"}): type: 'Warning' reason: 'Remount' cannot proceed to remount restore-test-2 on khush-test-lh-wk1: there is not any available mount point for volume restore-test-2" 
[longhorn-manager-bmj9k] time="2020-08-13T22:27:16Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"restore-test-2\", UID:\"e16af0f5-d83c-49cb-817f-c081d7e03e0e\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"48043\", FieldPath:\"\"}): type: 'Warning' reason: 'Remount' cannot proceed to remount restore-test-2 on khush-test-lh-wk1: there is not any available mount point for volume restore-test-2" 
```

**Environment:**
 - Longhorn version: v1.0.1
 - Kubernetes version: 18.6
 - Node OS type and version: Ubuntu 18.04

**Comment by shuo-wu** [comment]
Found a better way to reproduce it:
1. Restore a volume
2. Attach to a node
3. Format `ext4` for the volume but do not mount it
4. Reboot the node
5. Check the longhorn-manager logs

But I am not sure if you have formatted/mounted the volume when you succeed to reproduce this issue.

The cause of this issue:
The [function](https://github.com/longhorn/longhorn-manager/blob/a0c87e1796fee22da47955adb682ab158ac2a2b1/util/util.go#L784) wrongly errors out when there is no mount point for the formatted Longhorn volumes after the node reboot.

**Comment by yasker** [comment]
We are evaluating if we should delete the POD instead of doing remount. https://github.com/longhorn/longhorn/issues/1719

**Comment by yasker** [comment]
Close due to now we delete the workload pod instead of a remount. So the error message won't be there anymore.

Feel free to reopen if saw this again in v1.1.0.
