### ISSUE TITLE
[FEATURE]: Visual difference between Snapshot and Backup

### ISSUE THREAD

**Issue by tuxpeople** [longhorn/longhorn#1686]
I have the following PV. I'm always confused with this timeline. Because it mixes up snapshots and backups. I even thought initially, that the retain for snapshots isn't working because of this. It adds even more confusion that the title of the timline is "Snapshots" even it also contains backups. I suggest to

a) make a difference between snapshots and backups by either name or icon (or both)
b) maybe two timelines 
c) Change the title to "Snapshots & Bakup"

For b) it may be worth to think about a "git-like" timeline like this:

<pre>
o----[Snapshot1]--------------------[Snapshot2]----[Snapshot3]--------------------[Snapshot4]----[Volume Head]
                  \__[Backup1]___/                              \__[Backup2]___/
</pre>

![Bildschirmfoto 2020-08-14 um 09 24 07](https://user-images.githubusercontent.com/1506076/90224996-dbff3500-de10-11ea-9a0b-69a8b9a58d32.png)

**Comment by joshimoo** [comment]
@tuxpeople The timeline only contains snapshots, since a backup is always based on a snapshot.
Your scheduled backup will end up creating a snapshot first (instant operation) then backup that snapshot (upload to s3).

**Comment by tuxpeople** [comment]
Okay, I understand the concept here. But I find it confusing when I set that I want to keep 5 snapshots, but see 10 of them on the timeline. At first I even thought that deleting the old snapshots would not work.

Is there any way to graphically distinguish between snapshots and snapshots that were created for backup? You could also call the latter "backup", even if they are technically snapshots. But then it would be clearer and less confusing in my opinion.

**Comment by joshimoo** [comment]
@tuxpeople Thank you for the feedback, just to clarify a recurring job only cleans up it's own created snapshots / backups.
The reason for this is that assuming you would want to set up an additional recurring backup for weekly/monthly with it's own retention time, you wouldn't want the daily backups to nuke your weeklies/monthlies. Link to a common [backup rotation scheme](https://en.wikipedia.org/wiki/Backup_rotation_scheme#Grandfather-father-son)

I marked the picture above, with what is going on, you can see that based on the naming of the snapshots.
![snapshot - backups_LI](https://user-images.githubusercontent.com/1287163/90617261-c160fd80-e20e-11ea-9d34-8a16bb90a351.jpg)


@yasker  We might want to further discuss the below:
- We probably don't need to retain more then the latest snapshot for the backup schedule. (for easy delta comparison)
- We might want to visually distinguish (color code the recurring job / snapshots)

**Comment by tuxpeople** [comment]
@joshimoo Yes I understand the concept. But without a visually difference, it's hard to understand it by just looking at the timeline. I think it could be a small change: two different colors for the circles and maybe a different symbol in it.

**Comment by yasker** [comment]
Both snapshots and backups are a point in the past, also the snapshots are needed for backup creation.

I think the original question is not due to the difference between snapshot and backup. It's more likely due to we didn't differentiate different scheduling items. They normally can be differentiated by name but the name we set for each snapshot/backup schedule is implicit. That's what caused the confusion.

We can show more of each snapshot name, which indicates they're a part of a certain schedule. We also need to show the schedule name in the `Recurring` section. It won't be as straightforward as using the color code (which we might need to generate one color code per schedule?) though. But generating/customizing color code will result in storing more information in the backend, which I would want to avoid if possible - since the scheduler's name is already a good indication of who is who.

**Comment by tuxpeople** [comment]
@yasker Showing the name of the schedule would be a good solution, from my point of view.

Please consider also to change the title of the timeline section from "Snapshots" to "Snapshots and backups", even if both are technically snapshots. Would help as well to avoid confusion and would match the title of the scheduler section.

**Comment by yasker** [comment]
@tuxpeople yeah, make sense.

@smallteeths Can we update those in the UI?
1. Change `Snapshots` to `Snapshots and Backups`
2. Show the hidden recurring schedule name in the UI
3. Show more of the snapshot name so the user can identify which snapshot is created by which recurring schedule.

**Comment by khushboo-rancher** [comment]
Verified on Master - 08-26-2020

Validation - **Passed**

1. The title in the volume details page is changed to ```Snapshots and Backups```.
2. The name of recurring backups and snapshots are now visible on the UI.
3. The name of snapshots and backups appear as same as they appear in ```Recurring Snapshot and Backup Schedule```

<img width="1767" alt="Screen Shot 2020-08-26 at 10 41 11 AM" src="https://user-images.githubusercontent.com/60111667/91338900-7f920300-e78a-11ea-87fd-f8362c82be50.png">
