### ISSUE TITLE
WORM: Write-Once, Read-Many

### ISSUE THREAD

**Issue by lomori** [longhorn/longhorn#1687]
Does Longhorn support WORM: Write-Once, Read-Many? If not, any plans to add it?

Regards,
Luiz

**Comment by yasker** [comment]
Normally Kubernetes calls it ReadOnlyMany (ROX) https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

Longhorn doesn't support it yet. Currently, it's not on the roadmap. We need to see the demand for the feature before adding it.

What's your use case?

**Comment by lomori** [comment]
Our use case is that we have only one data producer (fetch and process data from a DB) but in order to keep up with the client demand, need more than one pod instance to server our clients (REST APIs). Client requests only need to access the data stored, i.e., won't trigger the writer. We can handle the synchronization, i.e., readers pause while data is being written. Data is not written frequently. Although possible, it would be a waste to have to replicate the data.
    On Friday, August 14, 2020, 12:39:24 PM EDT, Sheng Yang <notifications@github.com> wrote:  
 
 


Normally Kubernetes calls it ReadOnlyMany (ROX) https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

Longhorn doesn't support it yet. Currently, it's not on the roadmap. We need to see the demand for the feature before adding it.

What's your use case?

**Comment by yasker** [comment]
We might able to implement this as a by-product as #1470 , but there is a problem for this approach: Kubernetes doesn't support WORM, it only supports ROM natively, which means you will need to use RWX. So probably RWX solution as in #1470 is your best bet at the moment.

**Comment by hyprnick** [comment]
Our use case is also similar.  We have data writers and we have many readers. We want the data to be highly available.  Also, replication would handle if a local node died, all writers and readers would move to the same node.  

This seems to work with ReadWriteOnce and the reader simply mount the PVC in read-only mode. The only time this causes a problem is when the scheduler places the pod on a different node than where the drive is mounted.  It isn't taking this into account.

**Comment by PhilipMay** [comment]
@yasker this is confusing. The Kubernetes doc sais ([see](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes)):

> the volume can be mounted as read-write by a single node. ReadWriteOnce access mode still can allow multiple pods to access the volume when the pods are running on the same node.

So why suggest ReadOnlyMany? The question is: If I have a pod mounted with ReadWriteOnce is it possible (under which conditions is it possible) to mount this volume as readonly with additional pods with Longhorn?
