### ISSUE TITLE
[Question] internal deployment replicas, it is safe to reduce for small cluster?

### ISSUE THREAD

**Issue by WhitePhoera** [longhorn/longhorn#1692]
I have simple cluster, 1 master + 1 worker(for now).
i reduced storage class replicas to 1, since i have one worker yet.

But i looked into longhorn namespace and found out that csi-attacher, csi-provisioner, csi-resizer deployments also have several replicas.
Can i safely reduce that amount to 1 replica per deployment? and then increase back with increasing cluster size?

**Comment by joshimoo** [comment]
For non production clusters (evaluation, learning, testing, etc), it's safe to reduce the replica count for the kubernetes CSI components.

**Comment by WhitePhoera** [comment]
i start with small cluster, at first, later will add more workers to it.
so i just will need to add replicas back, right?

**Comment by joshimoo** [comment]
For the kubernetes CSI components that will work.

**Comment by WhitePhoera** [comment]
thank you.

**Comment by akhfa** [comment]
thank you
