### ISSUE TITLE
No backups are created (Minio)

### ISSUE THREAD

**Issue by dennybritz** [longhorn/longhorn#1694]
Version 1.0.2 installed via Helm on k3s.

When I click on "Create Backup" or "Take Snapshot" in the UI, nothing happens. I don't see any error messages, and I don't see anything useful in the pod logs, though maybe I'm looking at the wrong place. There is a brief loading animation in the UI, but nothing happens. No messages, no errors, no files written to Minio.

I initially thought it's a Minio connection issue, but Longhorn seems to connect fine. I don't see any errors when I navigate to the backup page, which is an empty list. If I change the bucket or keys to something invalid, I start getting errors, so the credentials seem to work.

Also, sometimes "Create Backup" is grayed out, but sometimes it is not after refreshing the page, which may be related?

![image](https://user-images.githubusercontent.com/403133/90394142-64403d00-e092-11ea-8638-171e5294942d.png)

![image](https://user-images.githubusercontent.com/403133/90394194-7fab4800-e092-11ea-86d4-b8a919b61433.png)

**Comment by shuo-wu** [comment]
That's weird. As long as the volume is attached, The button `Take Snapshot` and `Create Backup` shouldn't gray out.

To check if the MinIO works fine in Longhorn, you can see if there are any errors when you click the Backup page.

**Comment by joshimoo** [comment]
@dennybritz can you check if you are getting a js error in the console F12?
If your minio connection is in error, the page should display an error message when visiting the backup page.
As well as when trying to create a backup.

If you cannot see an error message in the browser console, please attach a support bundle and we will have a look.
