### ISSUE TITLE
[FEATURE]Longhorn UI redirect replica name on `Node` page to the corresponding volume page

### ISSUE THREAD

**Issue by boknowswiki** [longhorn/longhorn#1697]
**Describe the solution you'd like**
Once click on the replica name on the `Node` page, Longhorn UI can redirect to volume page which has this replica.
This is related to
https://github.com/longhorn/longhorn/issues/298

**Additional context**
First on the Longhorn UI `Node` page:
![Screen Shot 2020-08-17 at 5.30.11 PM.png](https://images.zenhubusercontent.com/5ea86ddb41903e5d4e29e34f/dd986e0b-59b3-4706-8e8d-46ab529112be)

Select the `Replicas` column:
![Screen Shot 2020-08-17 at 5.31.17 PM.png](https://images.zenhubusercontent.com/5ea86ddb41903e5d4e29e34f/8134f17b-ce18-4a4c-8d0f-c53b19348bd9)

And in the `Name` column, once click on the replica name, it can redirect to the volume page which has this replica:
![Screen Shot 2020-08-17 at 5.33.02 PM.png](https://images.zenhubusercontent.com/5ea86ddb41903e5d4e29e34f/e2226bf6-ab9e-4877-af05-f70797398f65)

**Comment by boknowswiki** [comment]
@smallteeths , I just submitted this new feature about UI, please let me know if you have any question about it. Thanks.

**Comment by khushboo-rancher** [comment]
Verified on Master - 08-24-2020

Validation - **Passed**

On clicking the replicas on the node page, the page is redirected to respective volumes.

Verified with the combination of replicas in ```Healthy, Unknown, Stooped, Failed and Rebuilding``` state and nodes in ```Schedulable, Disabled and Down``` state.
