### ISSUE TITLE
[FEATURE]Add instructions or provide tools to help users migrate data from other storage vendors

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1703]
**Describe the solution you'd like**
Add a migration example in the doc. Right now a simple way to do migration is that:
1. Launch a simple pod with 2 volumes, one is Longhorn volume another one is the volume users want to migrate from.
2. Do copy or `dd` between the 2 volumes.
3. Shutdown the pod but retain the volumes.

**Comment by yasker** [comment]
Duplicate of https://github.com/longhorn/longhorn/issues/1181 . Will track it there.
