### ISSUE TITLE
[FEATURE]Add eviction support for detached volume

### ISSUE THREAD

**Issue by boknowswiki** [longhorn/longhorn#1704]
**Is your feature request related to a problem? Please describe.**
Relates to https://github.com/longhorn/longhorn/issues/298.

**Describe the solution you'd like**
Support disks and nodes eviction when the volume is detached.

**Comment by boknowswiki** [comment]
The document update has been submitted on [the same PR as 298 document PR](https://github.com/longhorn/website/pull/186)

**Comment by khushboo-rancher** [comment]
Verified on Longhorn Master - 09/8/2020

Validation - **Pass**

Test cases executed from https://rancher.atlassian.net/wiki/spaces/LON/pages/721092760/Replica+eviction+from+node+and+disk

**Comment by khushboo-rancher** [comment]
The tests `test_node_eviction`, `test_node_eviction_multiple_volume`, `test_node_eviction_no_schedulable_node`, `test_node_eviction_soft_anti_affinity` have been passing since more than 5 nightly test run.
