### ISSUE TITLE
[FEATURE] Configure successfulJobsHistoryLimit of CronJobs

### ISSUE THREAD

**Issue by excieve** [longhorn/longhorn#1711]
**Is your feature request related to a problem? Please describe.**
With many volumes having recurring snapshotting and backups configured the number of `Succeeded` pods remaining after the corresponding `CronJob`s have been successfully executed can be in hundreds and even thousands because the default `successfulJobsHistoryLimit` is `3`. So e.g. 100 volumes with a backup and snapshot schedules would leave 600 "history" pods at all times. This makes the k8s namespace view rather difficult to manage and the information is not very useful since the related processes are available as Longhorn engine CRD anyway.

**Describe the solution you'd like**
A configurable option on the storage class and maybe a global setting (with a default of `0` due to usefulness considerations above). Same for `failedJobsHistoryLimit` (which is less of a nuisance as k8s default is `1` and it can actually be useful).

**Describe alternatives you've considered**
There aren't alternatives AFAIK.

**Additional context**
This also currently causes issues with certain CNIs (like Cilium) where the "historic" pod IP gets utilised in IP caching and then collisions happen with running pod IPs. But this, of course, has nothing to do with Loghorn.

**Comment by weizhe0422** [comment]
In current version, the default value of `successfulJobsHistoryLimit` in Longhorn will be `1` .

So I think we can make the parameter configurable.

![image](https://user-images.githubusercontent.com/17548901/191757044-c0e76ff5-d221-45f4-9a51-6b16ddd01a3b.png)

**Comment by chriscchien** [comment]
**Verified with longhorn master-head `97cb12`
Result pass**

Test [steps](https://github.com/longhorn/longhorn/issues/1711#issuecomment-1257845740)
Set `recurring-successful-jobs-history-limit: 4` and have 2 recurring jobs,  each job will keep 4 success history. 2 jobs will make history number to 8 as below
```
c-cps1my-27757859   1/1           7s         3m28s
c-7wl7hn-27757859   1/1           26s        3m28s
c-cps1my-27757860   1/1           5s         2m28s
c-7wl7hn-27757860   1/1           26s        2m28s
c-cps1my-27757861   1/1           8s         88s
c-7wl7hn-27757861   1/1           30s        88s
c-cps1my-27757862   1/1           9s         28s
c-7wl7hn-27757862   1/1           27s        28s
```
