### ISSUE TITLE
[Question] unable to resize PV

### ISSUE THREAD

**Issue by tuxpeople** [longhorn/longhorn#1714]
**Describe the bug**
PV does not resize.

**To Reproduce**
1. Create deployment including a PVC
2. change pvc requested size using kubectl edit pvc <name> -n <namespace>

**Expected behavior**
PVC gets expanded. New size viewable in Longhorn and Rancher UI's

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: 1.18.6
 - Node OS type and version: Ubuntu 20.04.1 LTS

**Additional context**
All I get is "Type resizing"

Original PVC
<pre>
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: podsync
  name: podsync-data
  namespace: podsync
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50G
</pre>

PVC in Rancher after edit:
<pre>
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"podsync"},"name":"podsync-data","namespace":"podsync"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"50G"}}}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2020-08-24T06:17:17Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: podsync
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:pv.kubernetes.io/bind-completed: {}
          f:pv.kubernetes.io/bound-by-controller: {}
          f:volume.beta.kubernetes.io/storage-provisioner: {}
      f:spec:
        f:volumeName: {}
      f:status:
        f:accessModes: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-08-24T06:17:21Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:accessModes: {}
        f:resources:
          f:requests:
            .: {}
            f:storage: {}
        f:volumeMode: {}
    manager: kubectl
    operation: Update
    time: "2020-08-24T06:31:11Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"Resizing"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
    manager: csi-resizer
    operation: Update
    time: "2020-08-24T06:39:10Z"
  name: podsync-data
  namespace: podsync
  resourceVersion: "21387"
  selfLink: /api/v1/namespaces/podsync/persistentvolumeclaims/podsync-data
  uid: fdb8f8ef-b439-41b2-b74f-319329cb156f
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 55G
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-fdb8f8ef-b439-41b2-b74f-319329cb156f
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 47Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-08-24T06:39:10Z"
    status: "True"
    type: Resizing
  phase: Bound
</pre>

**Comment by joshimoo** [comment]
@tuxpeople we currently only support offline [volume expansion](https://longhorn.io/docs/1.0.2/volumes-and-nodes/expansion/), is your volume detached?

**Comment by tuxpeople** [comment]
No, it wasn't. Thanks for pointing out.

It is now, should expansion then start immediately?

**Comment by tuxpeople** [comment]
Works. Sorry

**Comment by tuxpeople** [comment]
Volume is now enlarged, but can't be used anymore...

<pre>
MountVolume.SetUp failed for volume "pvc-fdb8f8ef-b439-41b2-b74f-319329cb156f" : rpc error: code = InvalidArgument desc = There is no block device frontend for volume pvc-fdb8f8ef-b439-41b2-b74f-319329cb156f
</pre>

**Comment by joshimoo** [comment]
@tuxpeople you should be able to ignore that error, it's a transitive error from the first mount call. The following mount calls should succeed?

We are aware of the issue of the transitive error.

**Comment by tuxpeople** [comment]
Unfortunately no. It's going to be attached and shortly getting dettached again.
![Bildschirmfoto 2020-08-24 um 10 11 16](https://user-images.githubusercontent.com/1506076/91020063-44f56280-e5f2-11ea-9502-35d54f676bab.png)

It's like a loop... attaching, dettaching, attaching, dettaching...

In Longhorn UI, it's changing between faulty (all red) and ready. But the health is always "unknown". 
![Bildschirmfoto 2020-08-24 um 10 11 38](https://user-images.githubusercontent.com/1506076/91020161-69e9d580-e5f2-11ea-83b9-e81a739cc30e.png)

I rebooted all nodes, didn't helped.

**Comment by joshimoo** [comment]
- Did you reboot all nodes simultaneously? if so the volume now requires salvaging, by default [auto salvage](https://longhorn.io/docs/1.0.2/references/settings/#automatic-salvage) is enabled.

- Is `/var/lib/longhorn` on stable storage on these nodes?
- Start by scaling down the workload deployments that are using this volume to 0

CC @shuo-wu Can you provide guidance on how to best proceed from this situation?

**Comment by tuxpeople** [comment]
The issue already existed before rebooting the nodes. `/var/lib/longhorn` is on local M2SSD storage. 

While I already tried (also before rebooting the nodes), I scaled the workload again down to 0. No pod is currently running.

However, the Longhorn UI sill shows attaching -> attached -> faulty -> detaching loop

Could the root cause of this be, that I've edited the PVC while the PV was bound? I've scaled down afterwards and shortly Longhorn began to resize the PV

**Comment by tuxpeople** [comment]
This is what I see in Longhorn UI (screen recording with Quicktime):

[screencapture-longhorn.zip](https://github.com/longhorn/longhorn/files/5116734/screencapture-longhorn.zip)

**Comment by joshimoo** [comment]
Thank you for the elaboration, can you attach a support bundle?

**Comment by tuxpeople** [comment]
Well, it's to big to upload it here. But feel free to get it there: https://www.dropbox.com/s/rrsqdjva7oz0yat/longhorn-support-bundle_f8c9ff66-436f-4093-add6-7f177152ceb1_2020-08-24T09-58-21Z.zip?dl=0

**Comment by tuxpeople** [comment]
I tried to resize it a bit further. That stopped the attach-loop and the volume got "healthy". However, it's still "resizing". Logs telling me this:

`time="2020-08-24T18:18:50Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"pvc-fdb8f8ef-b439-41b2-b74f-319329cb156f\", UID:\"99edf0cf-0761-453e-aec7-e7b5e98805d6\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"545611\", FieldPath:\"\"}): type: 'Warning' reason: 'Remount' cannot proceed to remount pvc-fdb8f8ef-b439-41b2-b74f-319329cb156f on nuc2: failed to detect the filesystem for volume pvc-fdb8f8ef-b439-41b2-b74f-319329cb156f before the remount, will skip remounting it: cannot get the filesystem type by using the command blkid /dev/longhorn/pvc-fdb8f8ef-b439-41b2-b74f-319329cb156f | sed 's/.*TYPE=//g'"
24.8.2020 20:18:50`

Mots probably, I screwed it up completely. I'm now going to delete it and make a new one.

**Comment by shuo-wu** [comment]
I suspect that all replicas somehow become inconsistent (size is not updated correctly) when the expansion is not processed correctly. When the volume loops in attach-fault-detach state. To find the cause, we need the support bundle.

**Comment by shuo-wu** [comment]
1. Due to the misoperation, it seems that all the underlying files in the volume replicas are not expanded successfully. Then the volume will get crashed as long as there are I/Os:
```
2020-08-24T07:59:11.241560616Z time="2020-08-24T07:59:11Z" level=warning msg="pvc-fdb8f8ef-b439-41b2-b74f-319329cb156f-e-104a9d0f: time=\"2020-08-24T07:58:38Z\" level=error msg=\"Replicator.ReadAt:0 unexpected EOF\""
2020-08-24T07:59:11.241569246Z time="2020-08-24T07:59:11Z" level=warning msg="pvc-fdb8f8ef-b439-41b2-b74f-319329cb156f-e-104a9d0f: time=\"2020-08-24T07:58:38Z\" level=error msg=\"Replicator.ReadAt:1 unexpected EOF\""
2020-08-24T07:59:11.241574121Z time="2020-08-24T07:59:11Z" level=warning msg="pvc-fdb8f8ef-b439-41b2-b74f-319329cb156f-e-104a9d0f: time=\"2020-08-24T07:58:38Z\" level=error msg=\"Replicator.ReadAt:2 unexpected EOF\""
2020-08-24T07:59:11.241578809Z time="2020-08-24T07:59:11Z" level=warning msg="pvc-fdb8f8ef-b439-41b2-b74f-319329cb156f-e-104a9d0f: time=\"2020-08-24T07:58:38Z\" level=error msg=\"Setting replica tcp://10.42.2.26:10000 to ERR due to: unexpected EOF\""
2020-08-24T07:59:11.241583490Z time="2020-08-24T07:59:11Z" level=warning msg="pvc-fdb8f8ef-b439-41b2-b74f-319329cb156f-e-104a9d0f: time=\"2020-08-24T07:58:38Z\" level=info msg=\"Set replica tcp://10.42.2.26:10000 to mode ERR\""
2020-08-24T07:59:11.241588116Z time="2020-08-24T07:59:11Z" level=warning msg="pvc-fdb8f8ef-b439-41b2-b74f-319329cb156f-e-104a9d0f: time=\"2020-08-24T07:58:38Z\" level=error msg=\"Setting replica tcp://10.42.0.29:10000 to ERR due to: unexpected EOF\""
2020-08-24T07:59:11.241592824Z time="2020-08-24T07:59:11Z" level=warning msg="pvc-fdb8f8ef-b439-41b2-b74f-319329cb156f-e-104a9d0f: time=\"2020-08-24T07:58:38Z\" level=info msg=\"Set replica tcp://10.42.0.29:10000 to mode ERR\""
2020-08-24T07:59:11.241598058Z time="2020-08-24T07:59:11Z" level=warning msg="pvc-fdb8f8ef-b439-41b2-b74f-319329cb156f-e-104a9d0f: time=\"2020-08-24T07:58:38Z\" level=error msg=\"Setting replica tcp://10.42.1.25:10000 to ERR due to: unexpected EOF\""
2020-08-24T07:59:11.241602831Z time="2020-08-24T07:59:11Z" level=warning msg="pvc-fdb8f8ef-b439-41b2-b74f-319329cb156f-e-104a9d0f: time=\"2020-08-24T07:58:38Z\" level=info msg=\"Set replica tcp://10.42.1.25:10000 to mode ERR\""
2020-08-24T07:59:11.241607407Z time="2020-08-24T07:59:11Z" level=warning msg="pvc-fdb8f8ef-b439-41b2-b74f-319329cb156f-e-104a9d0f: time=\"2020-08-24T07:58:38Z\" level=error msg=\"I/O error: tcp://10.42.2.26:10000: unexpected EOF; tcp://10.42.0.29:10000: unexpected EOF; tcp://10.42.1.25:10000: unexpected EOF\""
```
2. Since Longhorn now just blindly salvages/reuses replicas when all replicas are crashed, the volume will be detached then reattached. --> Back to statement 1 --> Infinite loop. This salvage issue will be improved after #1340

Since right now the invalid replicas will be marked as ERROR immediately, I think we don't need to add some rigorous checks for the file size in the replica starting stage. And it may be complicated. What do you think about it? @yasker

**Comment by tuxpeople** [comment]
thanks!
