### ISSUE TITLE
[FEATURE] Include "Update Replica Count" as Multi-edit

### ISSUE THREAD

**Issue by timmy59100** [longhorn/longhorn#1715]
**Is your feature request related to a problem? Please describe.**
Sometimes I want all my volumes to have more or less replicas. At the moment I have to set this manually for each volume.

**Describe the solution you'd like**
Include "Update Replica Count" as Multiedit in UI

**Describe alternatives you've considered**
Maybe one could update the replica count in the storage class. Would that update the replica count of the volume?

**Comment by khushboo-rancher** [comment]
Verified on Longhorn Master - commit id - ```a6f0773```

Validation - **Fail**

The below scenario failed.
1. Create two volumes with the replica count 3.
2. Select both of them and click ```Update replicas count```.
3. Do not change the replica count and click OK.

The API calls throw 500 error.
```
[longhorn-manager-mvjl6] time="2020-09-02T22:31:40Z" level=warning msg="HTTP handling error error reading recurringInput: json: cannot unmarshal string into Go struct field UpdateReplicaCountInput.replicaCount of type int" 
[longhorn-manager-pfd7z] time="2020-09-02T22:31:40Z" level=error msg="Error in request: error reading recurringInput: json: cannot unmarshal string into Go struct field UpdateReplicaCountInput.replicaCount of type int"
```

**Comment by khushboo-rancher** [comment]
Verified on longhorn Master commit id - ```08cf35a```

Validation - **Pass**

Update replica count option is provided for batch operation.

<img width="816" alt="Screen Shot 2020-09-03 at 5 24 20 PM" src="https://user-images.githubusercontent.com/60111667/92186060-6cc2a280-ee0a-11ea-8704-f1784833acbb.png">
