### ISSUE TITLE
[FEATURE] columns management in volumes overview

### ISSUE THREAD

**Issue by tuxpeople** [longhorn/longhorn#1716]
Is it possible to add a function to managed the columns in volumes overview? I'd love to have an additional column to see the value of "actual size".

**Comment by yasker** [comment]
@smallteeths can you check if it's possible for the user to customize the columns in the volume overview page?

**Comment by smallteeths** [comment]
This is a little complicated to implement. Do we need to specify some fixed display columns, and then summarize the columns that users can customize the display.@yasker

**Comment by yasker** [comment]
Yeah, we can do that.

Fixed columns:
1. State
2. Name
3. Size
4. Attached To
5. Operations

The user can customize others.

**Comment by smallteeths** [comment]
Now the way to get the actual size is by requesting a snapshotList from the volume detail page. If we want to get the actual size on the volume list page, then we must send a request for each volume. This doesn't make sense. So I would like to be able to return the actual size directly in the volume list api.

**Comment by yasker** [comment]
@smallteeths Now the upstream manager has the `actualSize` field in the volume->controller object response.

**Comment by khushboo-rancher** [comment]
Varified on longhorn Master commit id - ```a6f0773```

Validation - **Pass**

The ```Actual Size``` column is now available on the volume overview page and there is a ```Custom column``` button provided on the page to enable and disable the display of the optional columns.
By default, all the columns will appear on the page.

<img width="1776" alt="Screen Shot 2020-09-02 at 3 22 34 PM" src="https://user-images.githubusercontent.com/60111667/92043265-9c9d7780-ed30-11ea-88e0-775934d65b38.png">

Custom column form
<img width="555" alt="Screen Shot 2020-09-02 at 3 26 29 PM" src="https://user-images.githubusercontent.com/60111667/92043330-b939af80-ed30-11ea-977b-37bcd1e8c554.png">
