### ISSUE TITLE
[FEATURE]: See over-provisioning in Dashboard

### ISSUE THREAD

**Issue by tuxpeople** [longhorn/longhorn#1717]
As far as I understand, I can provision more space in Longhorn than I actually have. But I'm not aware of a way to see how much I have compared to what I provisioned and what's actual used. Maybe, that information could be added to the dashboard somewhere?

**Comment by yasker** [comment]
@tuxpeople you can see it in the node pages for each node. `Scheduled` is what's the volume size we've been scheduled for the node/disk.
