### ISSUE TITLE
[FEATURE] Filters in Overview

### ISSUE THREAD

**Issue by tuxpeople** [longhorn/longhorn#1720]
If one has many volumes, a way to filter volumes in the overview could be very useful, eg. for bulk changes (eg. delete, backup etc)

Either allow filtering for all columns (eg. name containing "X" , or predefine some useful predefined filters like all the possible states or all the namespaces in which volumes do exist.

**Comment by yasker** [comment]
We currently allow filtering in both node and volume pages for certain fields. Check the top right box.

**Comment by tuxpeople** [comment]
My bad, sorry!
