### ISSUE TITLE
Unschedulable volume

### ISSUE THREAD

**Issue by te4336** [longhorn/longhorn#1722]
[longhorn-support-bundle_90aacc4d-8541-4696-b13f-8cdaeb4c3031_2020-08-26T06-30-42Z.zip](https://github.com/longhorn/longhorn/files/5127992/longhorn-support-bundle_90aacc4d-8541-4696-b13f-8cdaeb4c3031_2020-08-26T06-30-42Z.zip)
When dynamically creating a PV/PVC the new storage shows as being unschedulable and can't even be manually attached to a node. Please let me know what you need other than the support bundle to look in to why this is happening.

---
Version: `v1.0.2`

**Comment by boknowswiki** [comment]
Found the following error message from `longhorn-manager-stq76`:

`2020-08-26T06:28:08.947501942Z time="2020-08-26T06:28:08Z" level=error msg="There's no available disk for replica pv-victoriametrics-storage-r-e7dcece1, size 107374182400"
2020-08-26T06:28:08.947565666Z time="2020-08-26T06:28:08Z" level=error msg="unable to schedule replica pv-victoriametrics-storage-r-e7dcece1 of volume pv-victoriametrics-storage"`

With [this node level soft anti-affinity](https://longhorn.io/docs/1.0.2/references/settings/#replica-node-level-soft-anti-affinity) default is false, and default 3 replicas, longhorn needs 3 nodes to schedule the 3 replicas.

You can either change the replica number smaller or enable the node level soft anti-affinity.
Please let us know if there is any other problem.

**Comment by te4336** [comment]
Activating that setting resolved the issue. Thanks!
