### ISSUE TITLE
Unable to replicate large volume

### ISSUE THREAD

**Issue by dcplaya** [longhorn/longhorn#1738]
Whenever I try and increase my replica count to more than 1 on a specific volume (300GB), it ALWAYS fails. When it fails, it takes seems to also force a bunch of other volumes to degrade too. The error is below

>Failed rebuilding replica with Address 10.42.196.168:10135: failed to add replica address='tcp://10.42.196.168:10135' to controller 'config': failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.0.2/longhorn [--url 10.42.103.174:10020 add tcp://10.42.196.168:10135], output , stderr, time="2020-08-27T12:13:55Z" level=info msg="Adding replica tcp://10.42.196.168:10135 in WO mode" time="2020-08-27T12:13:55Z" level=info msg="Using replica tcp://10.42.140.80:10210 as the source for rebuild " time="2020-08-27T12:13:55Z" level=info msg="Using replica tcp://10.42.196.168:10135 as the target for rebuild " time="2020-08-27T12:18:43Z" level=fatal msg="Error running add replica command: failed to sync files [{FromFileName:volume-snap-f5b9da76-4681-44d7-b87e-6ee559f7bb93.img ToFileName:volume-snap-f5b9da76-4681-44d7-b87e-6ee559f7bb93.img ActualSize:4557012992} {FromFileName:volume-snap-f5b9da76-4681-44d7-b87e-6ee559f7bb93.img.meta ToFileName:volume-snap-f5b9da76-4681-44d7-b87e-6ee559f7bb93.img.meta ActualSize:0} {FromFileName:volume-snap-c2d58325-7a28-48c2-b34b-b500053039f4.img ToFileName:volume-snap-c2d58325-7a28-48c2-b34b-b500053039f4.img ActualSize:2938630144} {FromFileName:volume-snap-c2d58325-7a28-48c2-b34b-b500053039f4.img.meta ToFileName:volume-snap-c2d58325-7a28-48c2-b34b-b500053039f4.img.meta ActualSize:0} {FromFileName:volume-snap-874ab800-afdb-474a-9d24-adceb6e00d44.img ToFileName:volume-snap-874ab800-afdb-474a-9d24-adceb6e00d44.img ActualSize:4096} {FromFileName:volume-snap-874ab800-afdb-474a-9d24-adceb6e00d44.img.meta ToFileName:volume-snap-874ab800-afdb-474a-9d24-adceb6e00d44.img.meta ActualSize:0} {FromFileName:volume-snap-5c389519-87e4-40d4-8026-46cade4787e1.img ToFileName:volume-snap-5c389519-87e4-40d4-8026-46cade4787e1.img ActualSize:6479872} {FromFileName:volume-snap-5c389519-87e4-40d4-8026-46cade4787e1.img.meta ToFileName:volume-snap-5c389519-87e4-40d4-8026-46cade4787e1.img.meta ActualSize:0} {FromFileName:volume-snap-18caaa7e-76c3-4e1a-987a-d7d99aff0359.img ToFileName:volume-snap-18caaa7e-76c3-4e1a-987a-d7d99aff0359.img ActualSize:219591733248} {FromFileName:volume-snap-18caaa7e-76c3-4e1a-987a-d7d99aff0359.img.meta ToFileName:volume-snap-18caaa7e-76c3-4e1a-987a-d7d99aff0359.img.meta ActualSize:0} {FromFileName:volume-snap-c-0tuqai-f04a4986.img ToFileName:volume-snap-c-0tuqai-f04a4986.img ActualSize:852246528} {FromFileName:volume-snap-c-0tuqai-f04a4986.img.meta ToFileName:volume-snap-c-0tuqai-f04a4986.img.meta ActualSize:0} {FromFileName:volume-snap-9e0ac17f-8bcf-4b19-9799-1cf267e4db09.img ToFileName:volume-snap-9e0ac17f-8bcf-4b19-9799-1cf267e4db09.img ActualSize:110153728} {FromFileName:volume-snap-9e0ac17f-8bcf-4b19-9799-1cf267e4db09.img.meta ToFileName:volume-snap-9e0ac17f-8bcf-4b19-9799-1cf267e4db09.img.meta ActualSize:0} {FromFileName:volume-snap-2e5423c0-c729-4bc6-8674-8302e8f7b925.img ToFileName:volume-snap-2e5423c0-c729-4bc6-8674-8302e8f7b925.img ActualSize:131072} {FromFileName:volume-snap-2e5423c0-c729-4bc6-8674-8302e8f7b925.img.meta ToFileName:volume-snap-2e5423c0-c729-4bc6-8674-8302e8f7b925.img.meta ActualSize:0} {FromFileName:volume-snap-c-0tuqai-856ac446.img ToFileName:volume-snap-c-0tuqai-856ac446.img ActualSize:19666141184} {FromFileName:volume-snap-c-0tuqai-856ac446.img.meta ToFileName:volume-snap-c-0tuqai-856ac446.img.meta ActualSize:0} {FromFileName:volume-snap-c-0tuqai-9c55bec7.img ToFileName:volume-snap-c-0tuqai-9c55bec7.img ActualSize:360448} {FromFileName:volume-snap-c-0tuqai-9c55bec7.img.meta ToFileName:volume-snap-c-0tuqai-9c55bec7.img.meta ActualSize:0} {FromFileName:volume-snap-c-0tuqai-3162cbf0.img ToFileName:volume-snap-c-0tuqai-3162cbf0.img ActualSize:7260487680} {FromFileName:volume-snap-c-0tuqai-3162cbf0.img.meta ToFileName:volume-snap-c-0tuqai-3162cbf0.img.meta ActualSize:0} {FromFileName:volume-snap-c-0tuqai-d59f0e0b.img ToFileName:volume-snap-c-0tuqai-d59f0e0b.img ActualSize:19115970560} {FromFileName:volume-snap-c-0tuqai-d59f0e0b.img.meta ToFileName:volume-snap-c-0tuqai-d59f0e0b.img.meta ActualSize:0}] from tcp://10.42.140.80:10210: rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil" , error exit status 1

---
Version: `v1.0.2`

**Comment by yasker** [comment]
@dcplaya The error message doesn't give much information here since it's a parsing error. Though it seems unrelated to the volume size. Increase the replica count of one volume shouldn't impact any other volumes unless we don't have enough space for the rebuild. Can you check the actual size of the volume and the remaining space of your disk to make sure the new node for the replica has enough space?

**Comment by dcplaya** [comment]
The parsing error explains why I had absolutely no clue what is causing this! Been scratching my head for days.

The actual size as reported by Longhorn
```
Size: 300 Gi
Actual Size: 258 Gi
```

Below are all my node's allocated and used space. The single replica is currently only on 1 worker (2nd from the top)
![image](https://user-images.githubusercontent.com/1105320/91499005-94979080-e875-11ea-8776-ce14a7360ecb.png)


I will have to get back to you on the CPU usage (going on a vacation for a few days). Do you want CPU load of the worker the replica is getting written to or the CPU load of the worker the replica is being read from? 

Also, not sure if this is related, but this volume also has issues successfully completing a backup. I set up daily backups but the last successful one according to Longhorn was 3 days ago (if this is not related, I will open a separate ticket, just thought it could be helpful info)

**Comment by yasker** [comment]
Thanks @dcplaya . After you come back, can you send a support bundle (see the generate button at the footer of the UI) to us at longhorn-support-bundle@rancher.com ? We want to take a deeper look at this issue.

**Comment by dcplaya** [comment]
Support bundle sent. This time, I wasn't trying to replicate, I was actually trying to copy the data out of Longhorn so I could get these logs and not risk data. It so happens, the same error popped up when doing this! It seems like high IO load (not large files, but large number of files) seems to cause Longhorn cause all of this to happen.

**Comment by yasker** [comment]
@dcplaya It seems you are having network or CPU resource issues on the nodes.

The issue of ` proto: Marshal called with nil` due to in one piece of Longhorn code, [it returns `nil, nil` for the GRPC response](https://github.com/longhorn/longhorn-engine/blob/95a3722e5b78c316540843e8124d1395948b4ab2/pkg/controller/rpc/server.go#L227), which caused the issue for the GRPC.

But this piece of code should return an error instead of `nil` in this case, so it's not the root cause for the issue.

After looking deeper into the log, I found:
```
2020-08-30T20:49:10.283294877-07:00 time="2020-08-31T03:49:10Z" level=info msg="Engine pvc-b98b8ab3-8737-4203-a0e8-e1af4982e307-e-72fe2e05 is still in backoff for replica pvc-b98b8ab3-8737-4203-a0e8-e1af4982e307-r-4b25c6e8 rebuild failure"
2020-08-30T20:49:16.587880780-07:00 E0831 03:49:16.587659       1 volume_controller.go:204] fail to sync longhorn-system/pvc-abda5db5-26ec-45d7-b0c2-3b8f78d38478: fail to update recurring jobs for pvc-abda5db5-26ec-45d7-b0c2-3b8f78d38478: Put "https://10.43.0.1:443/apis/batch/v1beta1/namespaces/longhorn-system/cronjobs/pvc-abda5db5-26ec-45d7-b0c2-3b8f78d38478-
c-0tuqai-c": read tcp 10.42.186.209:33778->10.43.0.1:443: read: connection reset by peer
2020-08-30T20:49:16.587931657-07:00 time="2020-08-31T03:49:16Z" level=warning msg="Dropping Longhorn volume longhorn-system/pvc-abda5db5-26ec-45d7-b0c2-3b8f78d38478 out of the queue: fail to sync longhorn-system/pvc-abda5db5-26ec-45d7-b0c2-3b8f78d38478: fail to update recurring jobs for pvc-abda5db5-26ec-45d7-b0c2-3b8f78d38478: Put \"https://10.43.0.1:443/apis
/batch/v1beta1/namespaces/longhorn-system/cronjobs/pvc-abda5db5-26ec-45d7-b0c2-3b8f78d38478-c-0tuqai-c\": read tcp 10.42.186.209:33778->10.43.0.1:443: read: connection reset by peer"
2020-08-30T20:49:16.588007030-07:00 E0831 03:49:16.587955       1 volume_controller.go:204] fail to sync longhorn-system/pvc-0d5963c2-2dca-4c6b-b528-3a5d7c91aada: fail to update recurring jobs for pvc-0d5963c2-2dca-4c6b-b528-3a5d7c91aada: Put "https://10.43.0.1:443/apis/batch/v1beta1/namespaces/longhorn-system/cronjobs/pvc-0d5963c2-2dca-4c6b-b528-3a5d7c91aada-
c-0tuqai-c": read tcp 10.42.186.209:34108->10.43.0.1:443: read: connection reset by peer
```

`10.43.0.1:443` is the Kubernetes API server, which also stores the Longhorn metadata. So those means Longhorn cannot communicate with the Kubernetes API server to get the metadata.

And there are some logs like below:
```
logs/instance-manager-e-4fb16fea/engine-manager.log:2020-08-30T19:24:52.474784334-07:00 [pvc-b98b8ab3-8737-4203-a0e8-e1af4982e307-e-72fe2e05] time="2020-08-31T02:24:52Z" level=error msg="Write timeout on replica 10.42.140.92:10016 seq= 194193 size= 8 (kB)"
logs/instance-manager-e-4fb16fea/engine-manager.log:2020-08-30T19:24:56.469469811-07:00 [pvc-b98b8ab3-8737-4203-a0e8-e1af4982e307-e-72fe2e05] time="2020-08-31T02:24:56Z" level=error msg="Write timeout on replica 10.42.140.92:10016 seq= 194196 size= 8 (kB)"
logs/instance-manager-e-4fb16fea/engine-manager.log:2020-08-30T19:25:00.491773558-07:00 [pvc-b98b8ab3-8737-4203-a0e8-e1af4982e307-e-72fe2e05] time="2020-08-31T02:25:00Z" level=error msg="Write timeout on replica 10.42.140.92:10016 seq= 194199 size= 8 (kB)"
logs/instance-manager-e-4fb16fea/engine-manager.log:2020-08-30T19:25:00.500442633-07:00 Aug 31 02:22:31.600325: ->10.42.14[pvc-b98b8ab3-8737-4203-a0e8-e1af4982e307-e-72fe2e05] 0.92:10016 W[  4kB]      419us
logs/instance-manager-e-4fb16fea/engine-manager.log:2020-08-30T19:25:00.506513054-07:00 [pvc-b98b8ab3-8737-4203-a0e8-e1af4982e307-e-72fe2e05] Aug 31 02:24:53.192895: ->10.42.140.92:10016 P[  0kB]      597us
logs/instance-manager-e-4fb16fea/engine-manager.log:2020-08-30T19:25:31.246878082-07:00 [pvc-b98b8ab3-8737-4203-a0e8-e1af4982e307-e-72fe2e05] time="2020-08-31T02:25:31Z" level=error msg="Error reading from wire: EOF"
```

Read/write timeout on the engine level indicates CPU or network issues. That's probably also why you have so many snapshots automatically created for the volume, since Longhorn is always trying to recover automatically from the issue.

Can you check your CPU usage level as well as the network bandwidth? I guess CPU resource is more likely the issue here.

**Comment by boknowswiki** [comment]
`connection reset by peer` usually means the connection has been dropped.

**Comment by dcplaya** [comment]
I think I found part of my issues (I hope). Ubuntu 20.04 with a USB3 driver (UAS I believe it is called) is apparently not very good when under heavy stress. I have a node (node02 in my logs if they show up) that has an external NVME attached to it. I guess, under heavy loads, Ubuntu will basically mark the USB as RO which causes Longhorn to loose its mind!

I followed the posts located [here](https://unix.stackexchange.com/questions/239782/connection-problem-with-usb3-external-storage-on-linux-uas-driver-problem) and [here](https://ubuntuforums.org/showthread.php?t=2307662) by basically blacklisting the UAS driver for that particular USB device (below, the `357d:7788` is the device ID in question, not my specific ID though)

```
echo options usb-storage quirks=357d:7788:u | sudo tee /etc/modprobe.d/blacklist_uas_357d.conf
sudo update-initramfs -u
sudo reboot
```

Since doing this, it seems much more stable! I was able to successfully complete a backup. The real test is when I up my replica count to 2 WHILE loading the application (Plex in this case) with some requests, basically a little stress test.

Last night, I thought I had done this and saw it fail, but I want to do it again to make sure it wasn't something else that caused the replica to `umount`. I was a bit sleep deprived, so there is no telling what I actually did!

I can easily see this drive getting marked RO would cause Longhorn to think it lost connection and other weird stuff happening.

@yasker If I can still replicate this issue, what CPU usage would you like to see? The worker nodes that the replica is being read/written to or my master node?

**Comment by yasker** [comment]
The underlying hardware issue can explain the write timeout etc. In the log, I saw the write timeout indeed happens on `node02`. So that part has been explained.

If you still can reproduce the issues, I'd like to see the CPU utilization of both worker and master node, as well as load average (e.g. `uptime)`, and how many CPUs are there for each node.

Btw, you might want to clean up the system generated snapshots. You can set up a recurring snapshot e.g. every day, which will also clean up system generated snapshots automatically. It's the result of losing replicas, likely due to your previous external harddrive issue.

**Comment by dcplaya** [comment]
Does a daily reoccurring backup NOT delete the system generated snapshots? Only a reoccurring snapshot deletes those system snapshots automatically?

**Comment by yasker** [comment]
@dcplaya recurring backup will clean up the system generated snapshots as well. So that would be fine.

**Comment by dcplaya** [comment]
So I think I have narrowed down what is actually causing the issues. I disabled k3s (which in turn disabled Longhorn) temporarily on the one specific node. I then enabled only NFS server and the crash still happens! For some reason NFS under load causes Ubuntu 20.04 to crash, haven't figured out exactly why yet though. But this rules out Longhorn being any part of the issue!

**Comment by dcplaya** [comment]
I'm going to go ahead and close this. I haven't had any issues with replication after I took the failing node out of my cluster (no idea what was causing the node to randomly reboot but it has nothing to do with Longhorn).
