### ISSUE TITLE
no block device frontend for volume error

### ISSUE THREAD

**Issue by te4336** [longhorn/longhorn#1739]
[longhorn-support-bundle_90aacc4d-8541-4696-b13f-8cdaeb4c3031_2020-08-27T15-44-38Z.zip](https://github.com/longhorn/longhorn/files/5137412/longhorn-support-bundle_90aacc4d-8541-4696-b13f-8cdaeb4c3031_2020-08-27T15-44-38Z.zip)
When I go to deploy my helm chart thePV/PVC is created in Longhorn however I keep getting a Frontend device error when it tries to attach it to the pod.

Warning | FailedMount | MountVolume.SetUp failed for volume "vm-victoria-metrics-cluster-vmselect-0" : rpc error: code = Internal desc = exit status 1 | a few seconds ago
Warning | FailedMount | MountVolume.SetUp failed for volume "vm-victoria-metrics-cluster-vmselect-0" : rpc error: code = InvalidArgument desc = There is no block device frontend for volume vm-victoria-metrics-cluster-vmselect-0 | a minute ago
Normal | SuccessfulAttachVolume | AttachVolume.Attach succeeded for volume "vm-victoria-metrics-cluster-vmselect-0" | a minute ago
Normal | Scheduled | Successfully assigned insight-vicmetrics/vm-victoria-metrics-cluster-vmselect-7698c96d9f-gh87n to cernehtxkubw205 | a minute ago
Warning | FailedScheduling | persistentvolumeclaim "vm-victoria-metrics-cluster-vmselect" not found | a minute ago

Support Bundle is attached. This is really holding us up from using Longhorn and if we can't get this resolved soon we'll have to move to something else like OpenESB.

---
Version: `v1.0.2`

**Comment by yasker** [comment]
```
logs/longhorn-csi-plugin-sk78j/longhorn-csi-plugin.log:2020-08-27T15:40:01.235835146Z time="2020-08-27T15:40:01Z" level=info msg="NodeServer NodePublishVolume req: volume_id:\"vm-victoria-metrics-cluster-vmselect-0\" target_path:\"/var/lib/kubelet/pods/c8568e62-9876-4dc2-a2c8-5ffa1e1a3338/volumes/kubernetes.io~csi/vm-victoria-metrics-cluster-vmselect-0/mount\" volume_capability:<mount:<fs_type:\"xfs\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"diskSelector\" value:\"\" > volume_context:<key:\"nodeSelector\" value:\"\" > volume_context:<key:\"numberOfReplicas\" value:\"2\" > volume_context:<key:\"staleReplicaTimeout\" value:\"20\" > "
logs/longhorn-csi-plugin-sk78j/longhorn-csi-plugin.log:2020-08-27T15:40:01.249040994Z Mounting arguments: -t xfs -o defaults /dev/longhorn/vm-victoria-metrics-cluster-vmselect-0 /var/lib/kubelet/pods/c8568e62-9876-4dc2-a2c8-5ffa1e1a3338/volumes/kubernetes.io~csi/vm-victoria-metrics-cluster-vmselect-0/mount
logs/longhorn-csi-plugin-sk78j/longhorn-csi-plugin.log:2020-08-27T15:40:01.249046393Z Output: mount: /var/lib/kubelet/pods/c8568e62-9876-4dc2-a2c8-5ffa1e1a3338/volumes/kubernetes.io~csi/vm-victoria-metrics-cluster-vmselect-0/mount: /dev/longhorn/vm-victoria-metrics-cluster-vmselect-0 already mounted or mount point busy.
```

> Output: mount: /var/lib/kubelet/pods/c8568e62-9876-4dc2-a2c8-5ffa1e1a3338/volumes/kubernetes.io~csi/vm-victoria-metrics-cluster-vmselect-0/mount: /dev/longhorn/vm-victoria-metrics-cluster-vmselect-0 already mounted or mount point busy.

That means the block device created by Longhorn has been automatically used by some other processes.

The last time we saw the issue, it's due to multipath process running on the node automatically add the Longhorn disk to the multipath pool. You can take a look at https://github.com/longhorn/longhorn/issues/1210 on how to find the root cause of the issue in your setup.

**Comment by yasker** [comment]
Btw, `There is no block device frontend for volume vm-victoria-metrics-cluster-vmselect-0 ` is not a real error. The error message is misleading. We will fix that in https://github.com/longhorn/longhorn/issues/1712

**Comment by danielefranceschi** [comment]
I have another kind of error:
```
E1020 13:49:37.651822       1 mount_linux.go:143] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-476eaef4-bde5-4ffa-99ec-abbebccd0fea /var/lib/kubelet/pods/9dcc6c9b-b89d-4fd8-80a6-b644d4030aa8/volumes/kubernetes.io~csi/pvc-476eaef4-bde5-4ffa-99ec-abbebccd0fea/mount
Output: mount: /var/lib/kubelet/pods/9dcc6c9b-b89d-4fd8-80a6-b644d4030aa8/volumes/kubernetes.io~csi/pvc-476eaef4-bde5-4ffa-99ec-abbebccd0fea/mount: wrong fs type, bad option, bad superblock on /dev/longhorn/pvc-476eaef4-bde5-4ffa-99ec-abbebccd0fea, missing codepage or helper program, or other error.
```

k3s 1.18.9, 4 nodes, all with single partition
longhorn 1.0.2
error occurs only on master node

**Comment by yasker** [comment]
@danielefranceschi You have a different issue here. It seems the data was corrupted on the device. Is there anything that happened to the disk/cluster? You can attach the volume manually on a node then run fsck against it to see if it can be fixed. You can also check if https://longhorn.io/docs/1.0.2/advanced-resources/data-recovery/data-error/ can help.
