### ISSUE TITLE
[BUG]UI-Provide multiple-choice dropdown for settings 'Pod Deletion Policy When Node is Down' and 'Default Data Locality'

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1743]
**Describe the bug**
'Pod Deletion Policy When Node is Down' and 'Default Data Locality' settings in longhorn take input as text. There should be a dropdown providing multiple-choice rather than text input

**To Reproduce**
1. Install Longhorn
2. Go to the setting page.
3. Check the settings 'Pod Deletion Policy When Node is Down' and 'Default Data Locality'
4. Both the settings take text as input.

**Expected behavior**
We should have a dropdown to select options from.
1. Pod Deletion Policy When Node is Down setting should have below options in dropdown
a. do-nothing
b. delete-statefulset-pod
c. delete-deployment-pod 
d. delete-both-statefulset-and-deployment-pod
2. Default Data Locality setting should have below options in dropdown
a. disabled
b. best-effort.

**Environment:**
 - Longhorn version: Master - 08/28/2020
 - Kubernetes version: 18.6
 - Node OS type and version: Ubuntu 18.04

**Additional context:**
The options are hardcoded and not coming from the settings https://github.com/longhorn/longhorn-ui/pull/274/commits/adb17893c6ababac08d64e11b0c3debfe09a8ad9

**Comment by yasker** [comment]
@smallteeths We should dynamically generate the options, instead of hard code them in the UI. If it needs more backend work, let me know.

**Comment by smallteeths** [comment]
https://github.com/longhorn/longhorn-ui/pull/274#discussion_r428977246

**Comment by khushboo-rancher** [comment]
Verified on Longhorn-master - commit id - ```a6f0773```

Validation - **Pass**

The settings 'Pod Deletion Policy When Node is Down' and 'Default Data Locality' have the drop-down to select the available options.
<img width="1440" alt="Screen Shot 2020-09-02 at 3 13 25 PM" src="https://user-images.githubusercontent.com/60111667/92042551-4da31280-ed2f-11ea-9f5e-a405497e281b.png">
<img width="1439" alt="Screen Shot 2020-09-02 at 3 13 42 PM" src="https://user-images.githubusercontent.com/60111667/92042558-4ed43f80-ed2f-11ea-858b-d7243cb96612.png">
