### ISSUE TITLE
[FEATURE] UI part for Data Locality feature

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#1744]
We need to modify UI to support the Data Locality feature.

1. On volume creation [Form](https://github.com/longhorn/longhorn-ui/blob/2d7874cf8db38e8c159fc44c954e94aebdb2f76d/src/routes/volume/CreateVolume.js#L53), add a `FormItem` for `dataLocality`. There are 2 `dataLocality` modes: `disabled` and `best-effort`.
1. On volume detail page:
   * On the right [volume info panel](https://github.com/longhorn/longhorn-ui/blob/2d7874cf8db38e8c159fc44c954e94aebdb2f76d/src/routes/volume/detail/VolumeInfo.js#L150):
      * Add a `<div>` to display `selectedVolume.dataLocality`
      * In the `Health` row, add a warning icon for data locality status. Specifically, if  `selectedVolume .dataLocality=best-effort` but there is not a healthy local replica on the same node as the engine, then display a warning icon with `Tooltip` saying that `Volume does not have data locality! There is no healthy replica on the same node as the engine`. This is similar to the replica node redundancy warning [here](https://github.com/longhorn/longhorn-ui/blob/0a52c1f0bef172d8ececdf4e1e953bfe78c86f29/src/routes/volume/detail/VolumeInfo.js#L47).
   * In the volume's [actions dropdown](https://github.com/longhorn/longhorn-ui/blob/master/src/routes/volume/VolumeActions.js):
      * Add a new action to update `dataLocality`. The API to update the `dataLocality` is `/v1/volumes/<VOLUME_NAME>?action=updateDataLocality`. This API expects the request's body to have the form `{dataLocality:<DATA_LOCALITY_MODE>}`.

**Additional context**
This is the UI part of the issue longhorn/longhorn#1045.

**Comment by joshimoo** [comment]
In regard to 1. the options on the volume form, should be dynamically generated based on the settings.
Having a generic drop down component that gets feed via a choices array, would be a good idea.
https://github.com/longhorn/longhorn-ui/pull/274#discussion_r428977246

**Comment by yasker** [comment]
@khushboo-rancher anything wrong with the validation? I didn't remember why this is moved from merged.

**Comment by khushboo-rancher** [comment]
This is good to close now. When I moved it from the merged column, the PR was not merged.
