### ISSUE TITLE
Can't mount longhorn pv

### ISSUE THREAD

**Issue by denissabramovs** [longhorn/longhorn#1746]
related thread in kubernetes issues:
https://github.com/kubernetes/kubernetes/issues/94336

**Comment by shuo-wu** [comment]
According to this log, all volumes on that node cannot be attached. Can you check what your node's current status/condition is?
```
E0830 12:42:45.750826   22250 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/driver.longhorn.io^pvc-den1vh podName: nodeName:}" failed. No retries permitted until 2020-08-30 12:44:47.750783453 +0000 UTC m=+4261.792536867 (durationBeforeRetry 2m2s). Error: "Volume not attached **according to node status** for volume \"den-longhorn-pv\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-den1vh\") pod \"mongodb-replicaset-0\" (UID: \"f2567891-b015-4ca2-b89e-9728d3234fec\") "

```

**Comment by yasker** [comment]
@denissabramovs Can you check if there is any error messages in your `longhorn-manager` logs? It might be some pre-requirement that wasn't satisfied, e.g. open-iscsi on the node.

**Comment by denissabramovs** [comment]
Sure, will do, i'm trying now another setup, but i think the problem stays the same.

**Comment by denissabramovs** [comment]
Ok it was my bad, it seems rancher haven't auto provisioned longhorn at all. Don't know why it was in the options if it is not installed...
Will test when longhorn system will be deployed next time.
