### ISSUE TITLE
[FEATURE] Provide multiarch image for the RWX nfs-provisioner [RWX] [NFS] [arm64] [multiarch]

### ISSUE THREAD

**Issue by Trackhe** [longhorn/longhorn#1752]
[Question]
Possible to use another nfs-provisioner as quay.io/kubernetes_incubator/nfs-provisioner because missing arm64 support?

I found https://longhorn.io/docs/1.0.2/advanced-resources/rwx-workloads/ and i want to use it for NFS with longhorn what sounds like a dream. But i cant use it on my raspberry cluster because the image[https://quay.io/repository/kubernetes_incubator/nfs-provisioner] in https://github.com/longhorn/longhorn/blob/master/examples/rwx/02-longhorn-nfs-provisioner.yaml is not available for arm64. So i search for the repo to build it for arm but i cant find it. is perhaps also because the lib is depricated. https://github.com/kubernetes/community/blob/master/incubator.md

Best regards M.N.(Trackhe)

**Comment by Trackhe** [comment]
https://hub.docker.com/repository/docker/trackhe/nfs-provisioner-arm

**Comment by innobead** [comment]
remove stale due to the incorrect exempt label

**Comment by innobead** [comment]
`nfs-provisioner` is deprecated. Longhorn has officially supported RWX via the latest solution (longhorn-share-manager, nfs inside), so please use it instead.
