### ISSUE TITLE
does longhorn supports ReadOnlyMany Volumes

### ISSUE THREAD

**Issue by Nemer-Naamneh** [longhorn/longhorn#1758]
i need to create a volume that will contain time zone files
where pods will read the custom time from this directory all the time
does LongHorn supports this type of volumes?
and how it can be  done since there is no info about this type in the documentation.

Thanks alot

**Comment by joshimoo** [comment]
We currently support Read Write Many (RWX) via a [NFS provisioner](https://longhorn.io/docs/1.0.2/advanced-resources/rwx-workloads/#enabling-rwx-support) which is currently the easiest to accomplish Read Only Many (ROX).

It doesn't sound like your timezone files will be changing much?
So a different setup, could be to prep a regular volume, then take a backup of the volume.
Now you can use the [fromBackup parameter](https://github.com/longhorn/longhorn/issues/1127) in a custom storage class, to create new volumes based on that backup.
In the next release we implement the csi snapshot support #304  so you don't need to go via a custom storage class anymore.

Lastly you could also use an init container to pull the timezone files from object storage or a server.
example: `wget timezones.tar.gz` with a following `tar xvzf timezones.tar.gz` should do the trick.

**Comment by joshimoo** [comment]
@Nemer-Naamneh Not sure if you saw my reply?

**Comment by swqmaven** [comment]
> @Nemer-Naamneh Not sure if you saw my reply?

i have a question. used [NFS provisioner](https://longhorn.io/docs/1.0.2/advanced-resources/rwx-workloads/#enabling-rwx-support) it just set alone longhorn-nfs-provisioner. if this pod dead. need some time to recover. it's less than high availability.
Is there any solution for this ?

**Comment by joshimoo** [comment]
@u2bo it should take around 90s for the failover with the current nfs-provisioner, we are working on a HA setup in https://github.com/longhorn/longhorn/issues/1470

**Comment by u2bo** [comment]
> @u2bo it should take around 90s for the failover with the current nfs-provisioner, we are working on a HA setup. #1470

ok thx. this feature release on v1.1.0 ?

**Comment by esakarya** [comment]
it doesnt work error:


MountVolume.SetUp failed for volume "pvc-5f7e11e8-c7c4-4cdb-8836-a5e6eb748263" : mount failed: exit status 32 Mounting command: mount Mounting arguments: -t nfs -o noresvport,vers=4.1 10.43.111.111:/export/pvc-5f7e11e8-c7c4-4cdb-8836-a5e6eb748263 /var/lib/kubelet/pods/8c95f1cf-42c0-4a8c-ba4e-661d003e469d/volumes/kubernetes.io~nfs/pvc-5f7e11e8-c7c4-4cdb-8836-a5e6eb748263 Output: mount: /var/lib/kubelet/pods/8c95f1cf-42c0-4a8c-ba4e-661d003e469d/volumes/kubernetes.io~nfs/pvc-5f7e11e8-c7c4-4cdb-8836-a5e6eb748263: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
