### ISSUE TITLE
[FEATURE] Suggestions for the snapshot pane of Volume

### ISSUE THREAD

**Issue by lomori** [longhorn/longhorn#1762]
**Is your feature request related to a problem? Please describe.**
It's a bit frustrating sometimes to apply Revert to a snapshot. See attached picture of a very simple scenario. I could not select Revert for snapshot 689ce as it was covered by 32891.

Also, having different icons or colors for snapshots with and without backups would improve a little bit UI. This way the user doesn't even have to hover of the icon to figure it out. For a NOOB like me with Longhorn, it takes a few minutes to figure out those minor things.

**Describe the solution you'd like**
Allow use to move/reposition icons in the snapshot view.

**Describe alternatives you've considered**
An alternative could be to have a drop down element on the top-right of that view with the options to revert, etc, relative to a selected snapshot icon.

**Additional context**
![Screenshot from 2020-09-04 14-45-42](https://user-images.githubusercontent.com/11261704/92278971-4b25f180-eec4-11ea-83f2-d1bfe9dc399e.png)

**Comment by yasker** [comment]
If you cannot select revert for `689ce` while `32891` exists, it's definitely a UI bug.

We can show the backed-up snapshot with a different color. It's not the first time we heard this request, though last time it's more related to the recurring snapshot/backup. But if it's just for snapshot with/without backup, we can do that. Maybe show the backed up snapshot as green.

**Comment by smallteeths** [comment]
Sorry for introducing this error.This style error was introduced mainly when resolving the dropdown menu not scrolling with the page. Our tree component really can't assign z-index to each element so I had to revert back to the original code. Although this will result in the snapshot dropdown not scrolling with the page bug, this bug is less serious. Subsequent ui framework upgrades should be able to solve this problem.  @yasker

**Comment by smallteeths** [comment]
Interim solutions:

1. The temporary solution is to adjust the corresponding element z-index: -1

![Jietu20200907-113555](https://user-images.githubusercontent.com/27733391/92346177-89a6f080-f0fe-11ea-87cb-87447a8ccc50.jpg)

2. This image `wangsiye/longhorn-ui:2fe580d `can be used to temporarily replace the longhorn-ui image.  This image has been fixed according to v1.0.2 release.

**Comment by khushboo-rancher** [comment]
Verified with wangsiye/longhorn-ui:2fe580d

Validation - **Pass**

WIth image ```wangsiye/longhorn-ui:2fe580d```, the revert option is available to click.

But with this image snapshot dropdown menu does not scroll with the page.

**Comment by khushboo-rancher** [comment]
Verified with longhorn master - commit id 45630f4

Validation - Pass

The dropdown menu is appearing over the other 
<img width="789" alt="Screen Shot 2020-09-09 at 5 25 27 PM" src="https://user-images.githubusercontent.com/60111667/92667811-d38c0400-f2c1-11ea-8cb7-c7350a30a411.png">
snapshot.

The snapshot dropdown menu not scrolling with the page issue is tracked https://github.com/longhorn/longhorn/issues/1780
