### ISSUE TITLE
[BUG] Fail to Upgrade Longhorn from version 0.8.0 to version 0.8.1

### ISSUE THREAD

**Issue by ldipaolaIT** [longhorn/longhorn#1763]
**Describe the bug**
When upgrading longhorn-system through Rancher (v2.4.3) from version 0.8.0 to version 0.8.1, we are seeing below error in longhorn-manager pods and upgrade fails:

time="2020-09-05T19:38:57Z" level=error msg="Upgrade failed: upgrade CRD failed: upgrade from v0.7.0 to v0.8.0: upgrade instance manager failed: upgrade from v0.7.0 to v0.8.0: cannot to find node tsk8s-w01 for instance manager instance-manager-e-3e1e0862 during the instance manager upgrade"

The weird thing here, is that the node "tsk8s-w01", is a node that is not part of the cluster any more (it was some time ago).

We previously successfully performed the upgrade processes from versions 0.6.2 to version 0.8.0 (v0.6.2 --> v0.7.0 --> v0.8.0). 

**To Reproduce**
3. Perform '....'

**Expected behavior**
Upgrade longhorn-system version from version 0.8.0 to version 0.8.1

**Log**
Added above

**Environment:**
 - Longhorn version: 0.8.0
 - Kubernetes version: 1.16.9
 - Node OS type and version: CentOS Linux release 7.8.2003

**Additional context**

**Comment by shuo-wu** [comment]
I guess the instance manager somehow is cleaned up successfully when you upgrade Longhorn. 
You can try the following command to directly delete the redundant instance manager since the related node is already gone. But please make sure there is no volume on the gone node:
```
kubectl -n longhorn-manager patch -p '{"metadata":{"finalizers": []}}' --type=merge instancemanagers instance-manager-e-3e1e0862
kubectl -n longhorn-manager delete instancemanagers instance-manager-e-3e1e0862
```

**Comment by ldipaolaIT** [comment]
Thank you @shuo-wu, That worked!
