### ISSUE TITLE
[BUG] longhorn manager can not start due to the engine image not ready

### ISSUE THREAD

**Issue by little-guy-lxr** [longhorn/longhorn#1764]
**Describe the bug**
longhorn manager can not start , crashloopbackk

**Expected behavior**
manager can start successfully

**Log**
time="2020-09-07T03:45:13Z" level=info msg="Start upgrading"
time="2020-09-07T03:45:13Z" level=info msg="No API version upgrade is needed"
time="2020-09-07T03:45:13Z" level=info msg="Finish upgrading"
time="2020-09-07T03:45:13Z" level=info msg="Upgrade leader lost: 192.168.16.228"
E0907 03:45:13.283776       1 kubernetes_node_controller.go:256] Couldn't get nodes 192.168.16.228: node "192.168.16.228" not found
time="2020-09-07T03:45:13Z" level=info msg="Start Longhorn Engine Image controller"
time="2020-09-07T03:45:13Z" level=info msg="Start Longhorn Kubernetes node controller"
time="2020-09-07T03:45:13Z" level=info msg="Start Longhorn engine controller"
time="2020-09-07T03:45:13Z" level=info msg="Start Longhorn Setting controller"
time="2020-09-07T03:45:13Z" level=info msg="Start Longhorn volume controller"
time="2020-09-07T03:45:13Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:45:13Z" level=info msg="Start Longhorn node controller"
time="2020-09-07T03:45:13Z" level=info msg="Start Longhorn websocket controller"
time="2020-09-07T03:45:13Z" level=info msg="Start Longhorn replica controller"
time="2020-09-07T03:45:13Z" level=info msg="Starting Longhorn instance manager controller"
time="2020-09-07T03:45:13Z" level=info msg="Start kubernetes controller"
time="2020-09-07T03:45:13Z" level=debug msg="Start monitoring instance manager instance-manager-r-8ddd8800"
time="2020-09-07T03:45:13Z" level=debug msg="Start monitoring instance manager instance-manager-e-be0a917f"
time="2020-09-07T03:45:19Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:45:25Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:45:31Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:45:37Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:45:43Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:45:49Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:45:55Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:46:01Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:46:07Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:46:13Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:46:19Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:46:25Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:46:31Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:46:37Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:46:43Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:46:49Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:46:55Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:47:01Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:47:07Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:v1.0.2 to be ready"
time="2020-09-07T03:47:13Z" level=fatal msg="Error starting manager: failed to wait for engine image longhornio/longhorn-engine:v1.0.2: Wait for engine image longhornio/longhorn-engine:v1.0.2 timed out"

**Environment:**
 - Longhorn version:
 - Kubernetes version:
 - Node OS type and version:

**Additional context**

**Comment by shuo-wu** [comment]
Can you check the log of pods `engine-image-ei-xxxxxx-xxxx` and the engine image object info? e.g.,
```
kubectl -n longhorn-system logs engine-image-ei-xxxxxx-xxxx
kubectl -n longhorn-system get engineimages.longhorn.io -o yaml
```
