### ISSUE TITLE
[BUG] Volume expands exponentially

### ISSUE THREAD

**Issue by timmy59100** [longhorn/longhorn#1765]
**Describe the bug**
On friday afternoon a volume started to expand exponentially and filled the disk wit 800 GB data till full. Presumably  while merging a snapshot. After shutting down the deployment with the volume, the space got freed up.

**To Reproduce**
-

**Expected behavior**
Volume should not grow endlessly.

**Log**
Sent support bundle.

**Environment:**
 - Longhorn version: 1.0.0
 - Kubernetes version: 1.18.3
 - Node OS type and version: CentOS 7.8.2003

**Additional context**

**Comment by shuo-wu** [comment]
Snapshot merging won't consume extra space. Can you check the volume snapshot info (including the hidden snapshots) when the issue is triggered?

**Comment by timmy59100** [comment]
I don't know if the merging is the cause. This happened the first time so I can't reproduce it. But there where huge amounts of logs generated from longhorn over this issue.

**Comment by timmy59100** [comment]
After our investigation, it looks like longhorn is not responsible for the data increase.
