### ISSUE TITLE
[Question] Snapshots and writes

### ISSUE THREAD

**Issue by lomori** [longhorn/longhorn#1767]
Let's say I have an application that frequently opens a file in a PVC provisioned by Longhorn, writes a large binary, and closes the file. What happens if a scheduled snapshot+backup occurs in the middle of a write operation? Will Longhorn wait for the write operation to complete? If yes, what about the other way around, when a snapshot+backup operation started and the application decides to write to a file before the snapshot is completed. Will Longhorn somehow block writes while the snapshot operation is happening?
This is fundamentally a question about the serialization (mutual exclusion) or not of PVC writes and snapshot operations.

**Comment by shuo-wu** [comment]
1. Longhorn is a block-level storage system and **doesn't know the file writing happened at the filesystem-level**. This file writing will be simply considered as **a bunch of data block writing** in Longhorn. 
2. When the longhorn volume tries to create a snapshot, **the data block writing will be paused by the lock**, and a snapshot + a new volume head will be created immediately. Then Longhorn will continue writing data blocks to the new volume head after the snapshot creation. 
3. As for backup creation, Longhorn will create a snapshot immediately then upload the snapshot data to the backupstore after the snapshot creation.

**Comment by yasker** [comment]
Basically Longhorn did snapshot the way as AWS EBS do: it only cares about the content at the time of the snapshot, doesn't have the knowledge regarding the workload at the moment. So Longhorn snapshots are crash-consistent at the moment, not application-consistent.

We will work on the application-consistent support for Longhorn in the v1.2, which will provide a way for the application to finish whatever work before Longhorn take the snapshot, to make sure the snapshot has captured a valid state of the application.
