### ISSUE TITLE
[BUG] Unable to extend volume

### ISSUE THREAD

**Issue by ppiccolo** [longhorn/longhorn#1775]
**Describe the bug**
when I try to expand a volume via PVC resize (from rancher UI) I'm getting this error :
 
> MountVolume.Setup failed while expanding volume for volume "pvc-4b813376-b6ce-4e7d-b43b-abad2914ef45" : MountVolume.NodeExpandVolume failed : Expander.NodeExpand failed to expand the volume : rpc error: code = Unimplemented desc = 

**To Reproduce**
1. Deploy a simple workload (alpine) with a PVC 
2. Wait for workload up & running
3. Go to rancher UI -> Cluster-> Storage -> Persistent Storage -> Edit -> increase volume size
4. Scale down workload deployment 
5. Wait for workload scale down
6. Scale up workload deployment

**Expected behavior**
Workload up & running with increased volume attached to it

**Environment:**
 - Longhorn version: v1.0.2
 - Kubernetes version:  v1.18.3
 - Node OS type and version: 5x Ubuntu 18.0.4 
 - Rancher: v2.4.5

**Comment by yasker** [comment]
@ppiccolo Online volume expansion is not supported currently. You can check the instruction on https://longhorn.io/docs/1.0.2/volumes-and-nodes/expansion/ for more details.

**Comment by ppiccolo** [comment]
Just checked ... same issue also if I scale down the workload before and then resize

**Comment by ppiccolo** [comment]
after some other test I suppose that this is a bug in rancher, because manually editing the PVC and applying it, correctly resize the volume.

**Comment by Orion7r** [comment]
so...do you have any good  solutions?
