### ISSUE TITLE
 "longhorn-psp" already exists in the cluster and wasn't defined in the previous release.[Question]

### ISSUE THREAD

**Issue by gravitionium** [longhorn/longhorn#1784]
i got an error when upgrade to v1.0.2. like this:

Failed to install app longhorn-system. Error: UPGRADE FAILED: kind PodSecurityPolicy with the name "longhorn-psp" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart

where can i delete longhorn-psp?

**Comment by shuo-wu** [comment]
Try
```
kubectl -n longhorn-system delete psp longhorn-psp
```

BTW, had you rollback/downgrade from v1.0.2 before? If everything works fine, there should not be this error.
