### ISSUE TITLE
task: validate SLES 15 SP1/SP2, SLES 12 SP5 and add to the supported OS list

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1785]
We want to make sure we can support SLES 15 for the upcoming v1.1 release.

**Comment by c3y1huang** [comment]
Not sure how this would be validated but I've been hand-on sles-15-sp2 and so far I've not seen noticeable issues :) . Please let me know if you need any help.

**Comment by yasker** [comment]
Thanks @c3y1huang . We will run a full suite of integration tests (https://github.com/longhorn/longhorn-tests/tree/master/manager/integration ) before the release to make sure every feature is working as expected.

**Comment by abonillabeeche** [comment]
I currently run Longhorn on CaaSP 4.5 (SLES15 SP2) without any issues.

**Comment by yasker** [comment]
Found a potential issue with SLES 15 SP2 https://github.com/longhorn/longhorn/issues/2088 . Having trouble connecting to the Kubernetes services inside the manager pod. It impacts NFS backupstore.

**Comment by khushboo-rancher** [comment]
Ran integration tests On SLES 15 SP1/SP2 and SLES 12 SP5, Integration tests passed on the set up.
Validated the RWX feature also, The basic functionality of RWX is working fine.
