### ISSUE TITLE
[BUG] Longhorn with S3 backup NoCredentialProviders error

### ISSUE THREAD

**Issue by laci84** [longhorn/longhorn#1786]
**Describe the bug**
Getting error when opening the Backup tab:
error listing backups: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.0.2/longhorn [backup ls --volume-only s3://xx@xxx/], output failed to list objects with param: { Bucket: "xx", Delimiter: "/", Prefix: "/" } response: { } error: AWS Error: NoCredentialProviders no valid providers in chain. Deprecated. For verbose messaging see aws.Config.CredentialsChainVerboseErrors <nil> , stderr, time="2020-09-14T09:04:06Z" level=error msg="Fail to list s3: failed to list objects with param: {\n Bucket: \"xx\",\n Delimiter: \"/\",\n Prefix: \"/\"\n} response: {\n\n} error: AWS Error: NoCredentialProviders no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors <nil>\n" pkg=s3 time="2020-09-14T09:04:06Z" level=error msg="failed to list objects with param: {\n Bucket: \"xx\",\n Delimiter: \"/\",\n Prefix: \"/\"\n} response: {\n\n} error: AWS Error: NoCredentialProviders no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors <nil>\n" , error exit status 1

**To Reproduce**
1. Go to Rancher/Apps
2. Click on /index.html, Backup
3. Perform k3s + Rancher

**Expected behavior**
List empty dir

**Environment:**
 - Longhorn version: v1.0.2
 - Kubernetes version: 1.19
 - Node OS type and version: Ubuntu 20

**Comment by c3y1huang** [comment]
Have you setup a backup target like [this](https://longhorn.io/docs/1.0.2/snapshots-and-backups/backup-and-restore/set-backup-target/)?

**Comment by jamesharr** [comment]
This is probably a place where a better error message is needed.

**Comment by laci84** [comment]
> Have you setup a backup target like [this](https://longhorn.io/docs/1.0.2/snapshots-and-backups/backup-and-restore/set-backup-target/)?

Yes:
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-s3
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: xx
  AWS_SECRET_ACCESS_xx

On Setting tab:
Backup Target: s3://xx@eu-central-1/
Backup Target Credential Secret: longhorn-s3

**Comment by c3y1huang** [comment]
> > Have you setup a backup target like [this](https://longhorn.io/docs/1.0.2/snapshots-and-backups/backup-and-restore/set-backup-target/)?
> 
> Yes:
> apiVersion: v1
> kind: Secret
> metadata:
> name: longhorn-s3
> namespace: longhorn-system
> type: Opaque
> data:
> AWS_ACCESS_KEY_ID: xx
> AWS_SECRET_ACCESS_xx
> 
> On Setting tab:
> Backup Target: s3://xx@eu-central-1/
> Backup Target Credential Secret: longhorn-s3

This is missing `AWS_ENDPOINTS`.

**Comment by laci84** [comment]
> > > Have you setup a backup target like [this](https://longhorn.io/docs/1.0.2/snapshots-and-backups/backup-and-restore/set-backup-target/)?
> > 
> > 
> > Yes:
> > apiVersion: v1
> > kind: Secret
> > metadata:
> > name: longhorn-s3
> > namespace: longhorn-system
> > type: Opaque
> > data:
> > AWS_ACCESS_KEY_ID: xx
> > AWS_SECRET_ACCESS_xx
> > On Setting tab:
> > Backup Target: s3://xx@eu-central-1/
> > Backup Target Credential Secret: longhorn-s3
> 
> This is missing `AWS_ENDPOINTS`.

Should set AWS_ENDPOINTS for AWS S3 too? Docs saying just for custom storage, like minio.

**Comment by c3y1huang** [comment]
> > > > Have you setup a backup target like [this](https://longhorn.io/docs/1.0.2/snapshots-and-backups/backup-and-restore/set-backup-target/)?
> > > 
> > > 
> > > Yes:
> > > apiVersion: v1
> > > kind: Secret
> > > metadata:
> > > name: longhorn-s3
> > > namespace: longhorn-system
> > > type: Opaque
> > > data:
> > > AWS_ACCESS_KEY_ID: xx
> > > AWS_SECRET_ACCESS_xx
> > > On Setting tab:
> > > Backup Target: s3://xx@eu-central-1/
> > > Backup Target Credential Secret: longhorn-s3
> > 
> > 
> > This is missing `AWS_ENDPOINTS`.
> 
> Should set AWS_ENDPOINTS for AWS S3 too? Docs saying just for custom storage, like minio.

sorry, it's my mistake. You are right, doesn't look like its a mandatory field.

**Comment by c3y1huang** [comment]
> apiVersion: v1
> kind: Secret
> metadata:
> name: longhorn-s3
> namespace: longhorn-system
> type: Opaque
> data:
> AWS_ACCESS_KEY_ID: xx
> AWS_SECRET_ACCESS_xx

I assume AWS_SECRET_ACCESS_xx is just a typo here, it should be AWS_SECRET_ACCESS_KEY: xx. Maybe also check the IAM user permissions.

**Comment by klodnickik** [comment]
Hi, I have the same error.

**Environment:**

    Longhorn version: v1.0.2
    Kubernetes version: 1.19, microk8s
    Node OS type and version: Ubuntu 18

apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: x
  AWS_SECRET_ACCESS_KEY: x

Backup Target:: s3://xx@eu-central-1/
Backup Target Credential Secret: aws-secret

I am able to upload files to the s3 with the access key. Addtionnaly, in AWS Console there is information that the access key was used (Last Activity in IAM user list). Both confirm that access and credentals are correct.

**Extract from logs**
time="2020-11-11T18:31:29Z" level=warning msg="backup store monitor: failed to list backup volumes in s3://xx@eu-central-1/backup/: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.0.2/longhorn [backup ls --volume-only s3://xx@eu-central-1/backup/], output failed to list objects with param: {\n  Bucket: \"xx\",\n  Delimiter: \"/\",\n  Prefix: \"backup/\"\n} response: {\n\n} error: AWS Error:  NoCredentialProviders no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors <nil>\n\n, stderr, time=\"2020-11-11T18:31:29Z\" level=error msg=\"Fail to list s3: failed to list objects with param: {\\n  Bucket: \\\"xx\\\",\\n  Delimiter: \\\"/\\\",\\n  Prefix: \\\"backup/\\\"\\n} response: {\\n\\n} error: AWS Error:  NoCredentialProviders no valid providers in chain. Deprecated.\\n\\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors <nil>\\n\" pkg=s3\ntime=\"2020-11-11T18:31:29Z\" level=error msg=\"failed to list objects with param: {\\n  Bucket: \\\"xx\\\",\\n  Delimiter: \\\"/\\\",\\n  Prefix: \\\"backup/\\\"\\n} response: {\\n\\n} error: AWS Error:  NoCredentialProviders no valid providers in chain. Deprecated.\\n\\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors <nil>\\n\"\n, error exit status 1"

Regards,
Krzysiek

**Comment by yasker** [comment]
Make sure to use `echo -n` when generating the base64 encoding for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, otherwise a new line will be added at the end of the string and it will cause an error when accessing the S3.

**Comment by klodnickik** [comment]
Thank you @yasker , it solves the problem. AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY were incorrecly encrypted with base64. After adding echo -n, it is working fine now.
