### ISSUE TITLE
[BUG] Error on deploying longhorn master - unable to recognize snapshotclass.yaml

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1788]
**Describe the bug**
Error on installing longhorn Master ```error: unable to recognize "specs/classes/snapshotclass.yaml": no matches for kind "VolumeSnapshotClass" in version "snapshot.storage.k8s.io/v1beta1"``` in absence of crds https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd in the cluster.

**To Reproduce**
1. Set up a cluster with 3 worker nodes
2. Deploy longhorn from https://github.com/longhorn/longhorn-manager/tree/master/deploy/install
3. Error appears as ```error: unable to recognize "specs/classes/snapshotclass.yaml": no matches for kind "VolumeSnapshotClass" in version "snapshot.storage.k8s.io/v1beta1"```

**Expected behavior**

Expected behavior could be one of the following:
1. Longhorn should deploy the crds https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crds too along with it.
2. ```VolumeSnapshotClass``` should not be the part of the longhorn deployment and the deployment of it could be a prerequisite to use https://github.com/longhorn/longhorn/issues/304 feature.

**Log**
```error: unable to recognize "specs/classes/snapshotclass.yaml": no matches for kind "VolumeSnapshotClass" in version "snapshot.storage.k8s.io/v1beta1"```

**Environment:**
 - Longhorn version: Longhorn Master - 09/14/2020
 - Kubernetes version: v18.8
 - Node OS type and version: Ubuntu 18.04

**Comment by joshimoo** [comment]
Good point, since we cannot guarantee existance of the crds and we still want to support older kubernetes versions.
The simplest approach for now is just to require a user creates a snapshotclass, I will move the snapshotclass.yaml into the examples area with all the other snapshot example yamls.

**Comment by joshimoo** [comment]
Done moved to examples will update the documentation.

**Comment by khushboo-rancher** [comment]
Verified on longhorn master - 09/21/2020

Validation - **Passed**

The installation of longhorn doesn't show any error.

The LEP should also get updated https://github.com/longhorn/longhorn/blob/master/enhancements/20200904-csi-snapshot-support.md. @joshimoo Is it also being taken care of?

**Comment by joshimoo** [comment]
@khushboo-rancher updated LEP: https://github.com/longhorn/longhorn/pull/1809
updated Documentation PR: https://github.com/longhorn/website/pull/193
