### ISSUE TITLE
[BUG] Volume stuck in "Attaching" state

### ISSUE THREAD

**Issue by g574** [longhorn/longhorn#1789]
**Describe the bug**

**To Reproduce**
- Install k3s
- install iscsi-initiator-utils
- install longhorn using kubectl with following changes to the template on longhorn.io:
```
    default-data-path: "/data/longhorn"
    replica-soft-anti-affinity: true
```
- install ingress
- take example config https://longhorn.io/docs/1.0.2/references/examples/#block-volume
- created volume shows as "attaching" in the UI and stays in this state

**Expected behavior**
The volume should be attached.

**Log**

Log from longhorn-manager (this looks irrelevant to me):
```
...level=warning msg="HTTP handling error websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header"
...level=error msg="Error in request: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header"
```

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: v1.18.8+k3s1
 - Node OS type and version: CentOS 8

**Comment by joshimoo** [comment]
Check the csi-plugin logs, via `kubetail -n longhorn-system csi-plugin`.
You can also attach a support bundle, it will include the csi-plugin logs.

**Comment by obeyler** [comment]
Same Issue on K8S 18.3

**Comment by joshimoo** [comment]
@g574 @obeyler is this issue still relevant?
