### ISSUE TITLE
[QUESTION] creating a volume with 3 replica -> automatically detach the volume after creation

### ISSUE THREAD

**Issue by dhrn** [longhorn/longhorn#1791]
**Describe the bug**
volumes are automatically detached the after creation if we put replica - 3

**To Reproduce**
1. create RKE cluster in suse linux
2. launch longhorn using rancher catalog
3. launch the efk stack  from the catalog by selecting the longhorn storage class
4. open longhorn uis and check the volume and check elastic master node logs

![image](https://user-images.githubusercontent.com/14145706/93248459-7c000380-f7ad-11ea-88f2-570b3d9507f4.png)

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

**Environment:**
 - Longhorn version:
 - Kubernetes version:
 - Node OS type and version:

**Additional context**

**Comment by joshimoo** [comment]
How many nodes do you have?
The default replica count for the longhorn storage class is 3.

**Comment by dhrn** [comment]
I tested with one node

**Comment by shuo-wu** [comment]
Then you need to create a new storgeClass with `numberOfReplicas: "1"`, Or enable the setting `replica-node-level-soft-anti-affinity`: https://longhorn.io/docs/1.0.2/references/settings/#replica-node-level-soft-anti-affinity

**Comment by dhrn** [comment]
@shuo-wu thanks you are correct. 
I managed to get it running. 

Still, I couldn't add more replica to the volume that created.

**Comment by joshimoo** [comment]
By default we use hard anti affinity starting with 1.0.
You need to enable soft anti affinity if you have less then nodes then the required replicas, in 1.1 we will change the default back to soft anti affinity.
https://github.com/longhorn/longhorn/issues/1701

**Comment by joshimoo** [comment]
I closed the issue, please reopen it if you require further assistance.
