### ISSUE TITLE
[BUG] helm uninstall don't work

### ISSUE THREAD

**Issue by obeyler** [longhorn/longhorn#1792]
**Describe the bug**
unable to uninstall with helm 3

**To Reproduce**
longhorn is installed by helm 
```
helm -n longhorn-system delete longhorn 
Error: warning: Hook pre-delete longhorn/templates/uninstall-job.yaml failed: jobs.batch "longhorn-uninstall" already exists

```

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: 1.18
 - Node OS type and version: ubuntu

**Comment by obeyler** [comment]
note that if I delete the job and retry the helm delete. The process goes on time out
```
helm -n longhorn-system delete longhorn 

Error: timed out waiting for the condition

```

**Comment by shuo-wu** [comment]
Can you check the log of pod `longhorn-uninstaller-xxxxxx` in namespace `longhorn-manager` if the pod still exists?

One workaround for this case may be directly deleting the job and rerun helm uninstall:
```
kubectl -n longhorn-system delete jobs longhorn-uninstall
```
