### ISSUE TITLE
[ENHANCEMENT] Backup/snapshotting jobs don't scale

### ISSUE THREAD

**Issue by excieve** [longhorn/longhorn#1796]
**Describe the bug**
Current implementation of backups/snapshots creates a `CronJob` for each volume and type of operation. Pods of these jobs are scheduled strictly to the nodes, where their respective volumes are attached. With enough volumes on a node it's easy to exhaust the pod limit and having job pods never execute due to the only node they can be scheduled to is `OutOfPods`.

This is especially visible on EKS, where pod limit is guided by ENI limits the instance type has, so something like `c5.xlarge` gets 58 pods max as each pod gets a VPC IP. But regardless of pod limit on the node it will eventually be exhausted by actual workloads.

**To Reproduce**
1. Use a `c5.xlarge` AWS EKS k8s node
2. Create a `StorageClass` with recurring snapshots and backups configured
2. Launch 40 pods or so with Longhorn volumes on the node using this SC
3. Wait a little until jobs start executing
4. Observe most of them failing to be scheduled with `OutOfPods`

**Expected behavior**
Backup and snapshots can handle large number of volumes on the same node. For example, the engine could be performing it directly by picking up the schedule from CRD instead of being triggered with a job's pod. Since the engine pod is always on the node it won't cause these issues.

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: 1.17.9-eks-4c6976
 - Node OS type and version: EKS-optimised Amazon Linux 2

**Additional context**
As I understand there's no way to reserve pod quota for the jobs to avoid scheduling more workloads with volumes, which means the only workaround is disabling snapshots and backups.

**Comment by excieve** [comment]
This seems to have more impact than just missing snapshots/backups. We've experienced a node failing today due to docker daemon exhausting file descriptors. It seems this happens when kubelet gets too many pods scheduled to a node that can't launch and causes it to spawn lots of docker socket connections, which it doesn't seem to close. We're only seeing increased file descriptor usage with docker daemon and kubelet on nodes with many volumes, where jobs are failing due to the pod limit. This doesn't happen at all on nodes without Longhorn volumes.

It seems we have to either significantly over-provision the nodes vertically (which makes dynamic horizontal node scaling more expensive) or completely disable snapshots and backups (which is highly undesirable of course).

**Comment by yasker** [comment]
The cronjob pod is not confined to run as the same node as the volume. It's more of a trigger for the backup/snapshot operations, which indeed happened in the engine.

Sounds like the problem may caused by the cronjob retain certain pods for jobs after it's done?

**Comment by excieve** [comment]
@yasker Here's an example of a `CronJob` resource we see created for the backups (removed snapshot schedule for now to mitigate the issue at least partially):
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: "2020-09-21T09:00:59Z"
  labels:
    longhornvolume: pvc-0073724f-f675-406d-a65f-625ae9cb4065
  name: pvc-0073724f-f675-406d-a65f-625ae9cb4065-backup-c
  namespace: longhorn-system
  ownerReferences:
  - apiVersion: longhorn.io/v1beta1
    kind: Volume
    name: pvc-0073724f-f675-406d-a65f-625ae9cb4065
    uid: 0820bf6b-ea49-4c96-bd88-03e338780cc1
  resourceVersion: "29111056"
  selfLink: /apis/batch/v1beta1/namespaces/longhorn-system/cronjobs/pvc-0073724f-f675-406d-a65f-625ae9cb4065-backup-c
  uid: 6c9b90da-b0aa-4686-8f0b-bd7bf7dc51f6
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      backoffLimit: 3
      template:
        metadata:
          creationTimestamp: null
          name: pvc-0073724f-f675-406d-a65f-625ae9cb4065-backup-c
        spec:
          containers:
          - command:
            - longhorn-manager
            - -d
            - snapshot
            - pvc-0073724f-f675-406d-a65f-625ae9cb4065
            - --manager-url
            - http://longhorn-backend:9500/v1
            - --snapshot-name
            - backup
            - --labels
            - RecurringJob=backup
            - --retain
            - "2"
            - --backup
            env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            image: longhornio/longhorn-manager:v1.0.2
            imagePullPolicy: IfNotPresent
            name: pvc-0073724f-f675-406d-a65f-625ae9cb4065-backup-c
            resources: {}
            securityContext:
              privileged: true
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/lib/longhorn/engine-binaries/
              name: engine-binaries
          dnsPolicy: ClusterFirst
          nodeName: ip-10-2-215-189.ap-southeast-1.compute.internal
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: longhorn-service-account
          serviceAccountName: longhorn-service-account
          terminationGracePeriodSeconds: 30
          volumes:
          - hostPath:
              path: /var/lib/longhorn/engine-binaries/
              type: ""
            name: engine-binaries
  schedule: 10 */12 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  active:
  - apiVersion: batch/v1
    kind: Job
    name: pvc-0073724f-f675-406d-a65f-625ae9cb4065-backup-c-1601381400
    namespace: longhorn-system
    resourceVersion: "29111055"
    uid: 0906ca75-5f05-4116-a658-fc16d6b3dc6a
  lastScheduleTime: "2020-09-29T12:10:00Z"
```

See `nodeName: ip-10-2-215-189.ap-southeast-1.compute.internal` in the spec, which [means](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename) pods this job creates will be scheduled exclusively to the node `ip-10-2-215-189.ap-southeast-1.compute.internal`, which is where the related volume is attached.

Even though the pod just triggers the engine, the pod still needs to be scheduled to a node and a container executed on it. This is subject to pod limits on the nodes and grows linearly with the number of volumes attached to the node.

**Comment by yasker** [comment]
You're right. I found the code https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go#L1905

We were using a different mechanism for the cronjob before v1.0.0, which requires the pod for the job to be on the same node. But now we've switched to use the external API for the corn job, which no longer has the limitation. We will remove the node binding in the next release.

How many volumes you've attached on that failed node? I want to make sure if we no longer have the node binding, it can solve your problem. Or do we need to check the completed job pods as well?

**Comment by PhanLe1010** [comment]
We can also change [.spec.successfulJobsHistoryLimit](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#jobs-history-limits) to 1 (or even 0) to reduce number of laying around pods  after the jobs finish. The default value is 3.

Since it doesn't seem to make sense to have 2 backups at the same time, I think that set [.spec.concurrencyPolicy](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#concurrency-policy) to `Forbid ` also helps to reduce the number of concurrently running cronjob's pods. 

Adding a [.spec.startingDeadlineSeconds](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#starting-deadline) also helps to reduce the number of retries in case there are many missed schedules.

**Comment by PhanLe1010** [comment]
From the information provided by @excieve 
> c5.xlarge gets 58 pods max
With the current Longhorn implementation, I can see that the problem might occur when there is around 11 Longhorn volumes on the node.

|pod type| count|
|---|---|
|Longhorn components|10|
|workload|11|
|cronJob|33|
|total|54|

**Comment by yasker** [comment]
@PhanLe1010 Good idea to reduce the `successfulJobsHistoryLimit`. We can reduce it to 1.

The `concurrencyPolicy` should be fine since it's possible a backup took a very long time so the data changed a lot in the next backup.

I don't quite understand how `startingDeadlineSeconds` would help here though.

**Comment by PhanLe1010** [comment]
@yasker 
I was thinking in the case there are 10 missed schedules in the last 2 hours (e.g. due to network), cronJob would start 10 jobs at the same time when the network is up. If we set `startingDeadlineSeconds=15mins`, cronJob only starts the job that was missed in the last 15 mins. 

However, I am not 100% sure about this behavior. The K8s doc doesn't say it explicitly. I would need to test it out to confirm.

**Comment by excieve** [comment]
@yasker @PhanLe1010 I don't think job history limit value matters in this issue (I've opened [another one](https://github.com/longhorn/longhorn/issues/1711) about job history) as completed pods aren't subject to node pod limits. As [pod lifecycle tells us](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase), pods in `Succeeded` phase are terminated and aren't going to be scheduled again. We're not seeing this relation on our nodes either.

As to numbers at which this is visible for us, we've recently upgraded our nodes that have lots of volumes attached to `c5a.4xlarge`, which allow a maximum of 234 pods. One of these nodes where the issue is happening has 157 pods, each with one Longhorn volume attached and 47 pods without any volumes. This is well below the total limit, but this currently produces 831 backup job pods (including historic) for the volumes and it's growing presumably because old job pods can't execute due to reaching the pod limit.

> We were using a different mechanism for the cronjob before v1.0.0, which requires the pod for the job to be on the same node. But now we've switched to use the external API for the corn job, which no longer has the limitation. We will remove the node binding in the next release.

Does it mean that we could manually remove the binding in the `CronJob`s and it would still work even on v1.0.2? It would definitely help us as our node groups are auto-scaled, so we could rely on dynamic scheduling for these jobs.

By the way, one thing I'd suggest is perhaps respecting the configured tolerations in these job specs once `nodeName` is removed to allow them to be scheduled everywhere Longhorn instance managers are allowed to.

**Comment by yasker** [comment]
@excieve Unfortunately you cannot manually remove the binding. Since we're monitoring the volume and cronjob, once you remove the binding, then it will be automatically updated by Longhorn soon. We will remove the `nodeName` field in the v1.1.0.

Currently there is no taint toleration set for the cronjob. Did you mean it should tolerate the taint set by the Longhorn setting as well? I think it makes sense.

**Comment by excieve** [comment]
@yasker Thanks! We'll be waiting for v1.1.0 then.

Yes, I meant that the job pods should tolerate the taints as set through the Longhorn settings.

Also, maybe not for this iteration, but please consider removing the k8s cron jobs for backups and snapshots completely, instead triggering them directly from the engine. Imagine having 1000 volumes, then just to do backups you'll need free capacity in the cluster for a burst of 1000 pods at a single moment when the cron job schedule creates the job pods. This capacity then becomes unneeded until the next burst. Adding regular snapshots will further increase this requirement.

This adds operational and cost burden to either always overprovision to prepare for this burst or have robust node auto-scaling in place (which could have other issues, like time to scale up).

Also note that the schedule triggers all the pods at the same time. It might ease the burst if it was possible to randomise the schedule (e.g. execute backup jobs twice a day, but at different time for each volume). Then the cluster wouldn't require a lot of extra capacity at the same time.

**Comment by yasker** [comment]
@excieve your argument against the k8s cronjob makes sense. It can become a bottleneck to the scalability of Longhorn once we have a big number of volumes per node. We can move the functionality to the Longhorn manager or some components run as a daemonset. Can you file a feature request for it? Thanks.

**Comment by PhanLe1010** [comment]
**test steps:**
1. Create a volume, attach to `node-1`, write some data to it.
1. Create a recurring job that runs every minute. 
1. Verify that sometimes that recurring job pod is scheduled to a node != `node-1`

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master ```11/19/2020```

Validation - **Passed**

The recurring job gets triggered on different nodes randomly.
