### ISSUE TITLE
[FEATURE] Include a NetworkPolicy to secure communication inside of Longhorn

### ISSUE THREAD

**Issue by jamesharr** [longhorn/longhorn#1805]
**Is your feature request related to a problem? Please describe.**
When longhorn-UI is deployed, it is easily accessible from inside the cluster without authentication. This poses a security risk if 1) not every application within the cluster is trusted 2) if there is a security breach within the kubernetes cluster in some way.

Additionally, hardening other components is probably worth-while.

**Describe the solution you'd like**
Include a built-in NetworkPolicy in Longhorn.

**Describe alternatives you've considered**
I don't know many other ways to secure a longhorn-ui deployment from internal components.

**Additional context**
Not all Kubernetes distributions support NetworkPolicy, so I think a few good checks and balancers are worth-while
- The default deployment of longhorn should not break (fail to run, or fail to install completely).
- If NetworkPolicy has no effect in any common Kubernetes distributions, it should be mentioned in the docs at very least.
- Policies should not make use of any features outside of the standard kubernetes distribution (IE: from Calico)

**Comment by dahrens** [comment]
I started writing calico specific network policies - not just for the UI, but for all components.
To achieve this it would be extremely useful to have the necessary connections documented somehow - this issue looks like a good place to start.
I currently have a working setup that allows / restricts the following.

Summarized based on a default deny all setup:

egress:

* allow egress traffic from all pods in `longhorn-system` to any destination (would be nice to be more precise)

ingress:

* allow pods that belong to my ingress controller on port `8000` to pods labeled with `app: longhorn-ui`
* allow all pods in `longhorn-system` on port `9500` to pods labeled with `app: longhorn-manager`
* allow all pods in `longhorn-system` on port `8500` to pods labeled with `longhorn.io/component: "instance-manager"`
* allow all pods in labeled with `longhorn.io/component: instance-manager` or `app: longhorn-manager` to access ports in range `10000:12000` to pods labeled with `longhorn.io/component: instance-manager`

Especially the last rule looks fragile to me - I noticed that there were connection on port `10000` - afterwards on `10001` - on `10015`...  therefore I decided to pick that range.

**Comment by innobead** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Main-Board-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/1805?planning-poker) with ZenHub @jenting @PhanLe1010 @shuo-wu @joshimoo

**Comment by PhanLe1010** [comment]
Test steps:
1. Deploy Longhorn
2. Deploy the network policies examples: https://github.com/longhorn/longhorn-manager/tree/master/examples/network-policy
3. Make sure all Longhorn functionalities are not broken by the network policies. 
4. Try to ping/curl Longhorn pods from unauthorized pods specified in the network policy. Verify that the access is blocked.

**Comment by kaxing** [comment]
Validating in progress, testing with master branch.

The example NetworkPolicies does its job by blocking access not defined in the rules.
Creating and deleting volumes via kubectl after policies applied does not have problem.
But I am still looking at the way to make UI work through the ingress and rancher proxy.

---

Attaching some error messages for later discussion:
With the ingress, it gives a `504 Gateway Time-out`
With the example via Rancher UI, will sees 500 error,
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "error trying to reach service: dial tcp 10.42.3.4:8000: i/o timeout",
  "code": 500
}
```

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested the examples configuration files with following combination, pods outside of the rule will not able to access longhorn-manager resources and the basic operations are working fine with the policies:
- Longhorn: master (20211109)
- Kubernetes: RKE1,  v1.20.12
  - CNI: Canal

Things to be noticed:
- Longhorn UI via Rancher proxy won't go through, additional policies is needed to allow the traffic
- For RKE2 will require different Network Policy configurations

--
Thanks @PhanLe1010 for the discussion on my ingress set up.
