### ISSUE TITLE
[BUG] Data mismatch after restoring a backup.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1806]
**Describe the bug**
There is a md5sum mismatch between the data restored from a backup.
https://ci.longhorn.io/job/public/job/longhorn-tests/99/testReport/tests/test_ha/test_engine_crash_for_restore_volume

**Log**
```
def test_engine_crash_for_restore_volume(
            client, core_api, volume_name, csi_pv, pvc, pod_make):  # NOQA
...
res_md5sum = get_pod_data_md5sum(core_api, res_pod_name, data_path)
>       assert md5sum == res_md5sum
E       AssertionError: assert '4f9e50b4f5ba...05c8f8f4a48\n' == '8a15b5cf2ae4...139c8aca44a\n'
E         - 4f9e50b4f5ba8397a959305c8f8f4a48
E         + 8a15b5cf2ae45e5a57c4d139c8aca44a
```   

**Environment:**
 - Longhorn version: Longhorn-master - 09/21/2020
 - Kubernetes version: 18.6
 - Node OS type and version: Ubuntu 18.04

**Comment by khushboo-rancher** [comment]
After merging the fix for https://github.com/longhorn/longhorn/issues/1807, we have not seen failure for ```test_engine_crash_for_restore_volume``` test in nightly test run.

**Comment by yasker** [comment]
Close this for now. If have the issue again, we can open another issue.
