### ISSUE TITLE
[BUG] ERROR 1146 (42S02) at line 1: Table 'wordpress.wp_options' doesn't exist

### ISSUE THREAD

**Issue by mohjam2004** [longhorn/longhorn#1811]
**Describe the bug**

I have an imported 3 nodes cluster in rancher dashboard. when I deploy wordpress with PV (in my case longhorn) the wordpress deployment has problem but when I deploy wordpress without PV, the deployment has no problem.

![image](https://user-images.githubusercontent.com/59224403/93988329-70a46d80-fd95-11ea-851b-391627ca71c1.png)

**To Reproduce**
1. I deploy longhorn from rancher dashboard to imported cluster (version 1.0.2)

![image](https://user-images.githubusercontent.com/59224403/93988378-7e59f300-fd95-11ea-8380-83d90ab9bc62.png)

2. I deploy wordpress from rancher dashboard to imported cluster (version 9.3.11). I choose longhorn as storage both for wordpress app and mariadb.

![image](https://user-images.githubusercontent.com/59224403/93988429-8ca80f00-fd95-11ea-9daa-0582aa556fbe.png)

**Expected behavior**

The wordpress pod also should be up and running (active) like mariadb pod.

**Log**
The mariadb pod become up and running and has no error. but wordpress pod has an error.

![image](https://user-images.githubusercontent.com/59224403/93988556-b8c39000-fd95-11ea-9b06-5000277b2f69.png)

The pod error of wordpress pod is:

![image](https://user-images.githubusercontent.com/59224403/93988575-bf520780-fd95-11ea-9ff9-cfcacb0555bc.png)

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: 1.17.11
 - Node OS type and version: debian 10 buster

**Comment by yasker** [comment]
It seems you only have two nodes available for Longhorn but the default Longhorn replica count is 3. Is it possible the volume wasn't created successfully at all? Anything in the Longhorn UI?

**Comment by mohjam2004** [comment]
Hi,
I have 3 nodes cluster and I set replica count to 1. there is no problem with volume creation in longhorn. when is use PV the wordpress pod get this error: "table wordpress.wp_options not exist".

**Comment by mohjam2004** [comment]
Hi,
I found another issue in my cluster and that is: only longhorn v 1.0.2 (the last version) can be installed in my cluster successfully, prior versions can't be installed.

**Comment by mohjam2004** [comment]
This issue is closed.

https://github.com/bitnami/bitnami-docker-wordpress/issues/267

**Comment by yasker** [comment]
Btw, I saw you've only provided the persistent storage to Wordpress. Normally you should provide the persistent storage to both Wordpress and MariaDB, otherwise you cannot retain all your stateful data for the wordpress.

**Comment by mohjam2004** [comment]
hi @yasker 
That was only a test which one one the bitnami/wordpress members asked me to do. I had error even if I used PV both for wordpress and mariadb.
any way I have no problem now.
regards
