### ISSUE TITLE
[Question] HowTo fix unstable volumes

### ISSUE THREAD

**Issue by DarianAnjuhal** [longhorn/longhorn#1812]
Hi,

we are currently migrating our whole infrastructure and services from rancher 1.x to rancher 2.x. At the beginning we felt in love with longhorn.
Unfortunately volumes are stuck in degraded mode or become read-only. If the read-only issue happens some services (for instance gitlab postgres) crashs and we have to restart the workload manually.

Switching "Replica Node Level Soft Anti-Affinity" to enable feels like the "volume stuck degraded" issue become better.
If the "volume stuck degraded" issue happens deleting the lastest snapshot triggers a correct rebuild and the volume become healthy again. But I have to do it manually.

To resolve the "volume read-only" issue I have to restart the workload manually. I know I could build a workaround using readiness but I try to figure out how to make the environment more stable at all.

Before we migrate production services for our customer we want to make sure the environment is stable.

**Environment:**
 - Longhorn version: v1.0.2
 - Kubernetes version:  v1.18.8+k3s1
 - Rancher version: v2.4.5
 - Node OS type and version: Debian GNU/Linux 10
- 3 Nodes

**Questions:**

- I downloaded a "Support bundle" after the gitlab postgresql crash occured. The bundle contains informations like private urls thats why I didn't add it here. What can I do with the bundle?

- How can I verify its not a hardware Network or Disk I/O issue?

- Is it normal that a new snapshot almost each hour is made?

- What else can I do to get a stable environment? Hints?

Let me know if you need more specific logs or informations:

thank you in advance
Darian

**Comment by yasker** [comment]
@DarianAnjuhal You can send the support bundle to longhorn-support-bundle@rancher.com and we can take a look.

**Comment by DarianAnjuhal** [comment]
Thanks for the info, I sent the bundle already.

Yes the high amount of snapshots worried me as well. If its a CPU or network issue hopefully there is a solution without changing the whole hardware/infrastructure.

**Comment by meldafrawi** [comment]
@yasker 

Couldn't reproduce the issue.

Steps to test:

1. Install k3s v1.18.8+k3s1
2. Install Longhorn v1.0.2
3. Create volumes attached to nodes, and other volumes consumed by pods
4. Write random data to volumes, and compute it's checksum.
5. Upgrade k3s to v1.19.2+k3s1
6. Check data checksum
7. Detach and attach the volumes, and compute data checksum
8. Write more data to volumes and verify data can be Read/Write
9. Create new volumes on the upgraded cluster

Volumes, are healthy, and usable in all situations

**Comment by yasker** [comment]
Hi @DarianAnjuhal 

I've checked the support bundle. The problem looks like caused by disconnecting replicas.

How many CPUs you have for each node? What's the level of CPU utilization on your node? And what's the network bandwidth/latency between the nodes?

Regarding the CPU, the result of `kubectl top nodes` and `kubectl -n longhorn-system top pod` should be helpful.

Also, there are definitely too many system generated snapshots in our setup. Every time when a replica disconnected, a snapshot will be generated as a part of rebuilding process. You can delete them manually by `show hidden snapshots` then delete any one of them. You can also clean them up automatically by creating a recurring snapshot e.g. for every day. The system generated snapshots will be cleaned up as a side effect of recurring snapshot or backup.

Once we know the level of CPU utilization and CPU usage of instance managers, we can see if we can raise the `GuaranteeEngineCPU` level to help with your use case.

**Comment by DarianAnjuhal** [comment]
Hi @yasker thank for your input.

Regarding the disconnection and the snapshot issue: That is exactly what I was thinking about.

I hope the following infos can help:
```
kubectl top nodes
NAME      CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
node1   2085m        20%    19264Mi         39%       
node2   1278m        21%    17723Mi         55%       
node3   1639m        27%    14423Mi         59%
```

```
kubectl -n longhorn-system top pod
NAME                                       CPU(cores)   MEMORY(bytes)   
csi-attacher-5b4745c5f7-fpb95              1m           10Mi            
csi-attacher-5b4745c5f7-g7vkt              1m           6Mi             
csi-attacher-5b4745c5f7-rgrth              1m           8Mi             
csi-provisioner-57d6dbf5f4-5bw2t           1m           7Mi             
csi-provisioner-57d6dbf5f4-8zw57           1m           7Mi             
csi-provisioner-57d6dbf5f4-b9ls5           2m           15Mi            
csi-resizer-75ff56bc48-2v2xj               1m           6Mi             
csi-resizer-75ff56bc48-5xt5d               1m           6Mi             
csi-resizer-75ff56bc48-vq5tw               1m           15Mi            
engine-image-ei-ee18f965-292z5             5m           19Mi            
engine-image-ei-ee18f965-2bc9m             5m           21Mi            
engine-image-ei-ee18f965-vm2h9             8m           20Mi            
instance-manager-e-0c94fe16                110m         144Mi           
instance-manager-e-5630b783                76m          186Mi           
instance-manager-e-67361da4                40m          72Mi            
instance-manager-r-75c20703                121m         390Mi           
instance-manager-r-853cfebd                383m         386Mi           
instance-manager-r-b1e1d024                365m         421Mi           
longhorn-csi-plugin-27g6q                  1m           21Mi            
longhorn-csi-plugin-4pfvn                  1m           18Mi            
longhorn-csi-plugin-mwvc8                  1m           19Mi            
longhorn-driver-deployer-7fc4667b6-g4m2g   1m           9Mi             
longhorn-manager-b6hd6                     343m         297Mi           
longhorn-manager-lvpmv                     464m         172Mi           
longhorn-manager-n7h2z                     97m          225Mi           
longhorn-ui-6fcc8fcb7c-sf6w5               0m           4Mi
```

More infos about the nodes and the vCPUs:

```
node1:
RAM 	51539 MB
CPU 	10

node2:
RAM 	34359 MB
CPU 	6

node3:
RAM 	25769 MB
CPU 	6
```

I used iperf3 and tested the bandwith between the three nodes and  is like 800-950 Mbits/sec.

```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  1.10 GBytes   948 Mbits/sec  1881             sender
[  5]   0.00-10.04  sec  1.10 GBytes   941 Mbits/sec                  receiver
```

If you need more information, let me know.

Thank you for your help

**Comment by yasker** [comment]
CPU utilization looks fine. Though you still can try to raise the `GuaranteedEngineCPU` to `750m` or `1000m` to see if it helps. It means 1.5 to 2 CPUs (750m * 2) per node will be reserved for Longhorn.

However, I think the issue may be due to the network. It's a 1Gb network, which converts to 800Mbits = 100MBytes per second, which is pretty small, considering you have 60 replicas (20 volumes * 3) in the cluster. I am wondering if it's because of network traffic, the latency increased a lot.

You can decrease the replica count to 2 to see if it helps.

Also, in v1.1.0 we will provide a way to clean up system generated snapshot automatically.

**Comment by DarianAnjuhal** [comment]
Thanks for your hint. 

I changed the default replica count to 2 and changed each volume manually to replica count 2 as well.
GuaranteedEngineCPU is still 0,25 because I have to detach each volume before I change this value. I can do that later.

There was the read-only issue today, so I had to restart the minio container manually. Hopefully the new version will solve some issues for me. I am looking forward.

**Comment by DarianAnjuhal** [comment]
@yasker Thanks, I have changed GuaranteedEngineCPU to 0.75 as you mentioned.
I will see if its getting better. If not you maybe wanna see a new support bundle.
I am looking forward to get a new version.

**Comment by DarianAnjuhal** [comment]
dmesg on node3 shows: 
EXT4-fs error (device sde): ext4_find_entry:1456: inode #2: comm SimpleAsyncTask: reading directory lblock 0

Maybe this information helps
Is this an longhorn issue?

**Comment by yasker** [comment]
@DarianAnjuhal Do you see the number of incidents reduced once you switch to the guaranteed engine CPU to 0.75?

Also, is it possible to set up a 10G network between the node?

Btw, for v1.1.0 release, we will start to delete the workload pod if the underlying volume experience issues, to allow Kubernetes to recreate the pod and reattach the volume. No need for the liveness probe anymore. #1719

**Comment by DarianAnjuhal** [comment]
@yasker Thanks for your input.

I guess changing the guaranteed engine CPU to 0,75 doesn't change anything. There are still a lot of read-only issues and the pods (especially mongodb or postgresql) crashes instantly.

In this case its not so easy change the network to 10G but I figure it out.

We are currently using rancher with activated monitoring (prometheus) But I still don't know how to get the informations we need. :-)

I am looking forward for the new version. When can I give it a try? What do you think?

**Comment by yasker** [comment]
When you encountered e.g. read-only issue on one node, you should have some logs with timestamp in the dmesg.

Then you can check in Rancher/Grafana about the CPU utilization on that node (potentially also the nodes that replica is running), to see if there is any spike of CPU utilization to e.g. 80% above. If that happens, then we know it's likely the CPU. 

Can you send us another support bundle along with the `dmesg -T` collected from every node? We can check if there is anything else might be in play.

**Comment by yasker** [comment]
Hi @DarianAnjuhal 

There is OOM showing in your dmesg
```
[Thu Oct 22 17:07:23 2020] prometheus invoked oom-killer: gfp_mask=0x6000c0(GFP_KERNEL), nodemask=(null), order=0, oom_score_adj=985
[Thu Oct 22 17:07:23 2020] prometheus cpuset=26d08f5914482eed4eb5837b64e0945b5a549df244d6b8acd1d86a7a9c09ec73 mems_allowed=0
[Thu Oct 22 17:07:23 2020] CPU: 1 PID: 12769 Comm: prometheus Tainted: G           OE     4.19.0-9-amd64 #1 Debian 4.19.118-2+deb10u1
[Thu Oct 22 17:07:23 2020] Hardware name: netcup KVM Server, BIOS RS 4000 SAS G8 xRAM 11/23/2018
[Thu Oct 22 17:07:23 2020] Call Trace:
[Thu Oct 22 17:07:23 2020]  dump_stack+0x66/0x90
[Thu Oct 22 17:07:23 2020]  dump_header+0x6b/0x283
[Thu Oct 22 17:07:23 2020]  oom_kill_process.cold.30+0xb/0x1cf
[Thu Oct 22 17:07:23 2020]  out_of_memory+0x1a5/0x450
[Thu Oct 22 17:07:23 2020]  mem_cgroup_out_of_memory+0xbe/0xd0
[Thu Oct 22 17:07:23 2020]  try_charge+0x707/0x780
[Thu Oct 22 17:07:23 2020]  ? __alloc_pages_nodemask+0x112/0x2b0
[Thu Oct 22 17:07:23 2020]  mem_cgroup_try_charge+0x86/0x190
[Thu Oct 22 17:07:23 2020]  mem_cgroup_try_charge_delay+0x1c/0x40
[Thu Oct 22 17:07:23 2020]  wp_page_copy+0x11b/0x700
[Thu Oct 22 17:07:23 2020]  ? mem_cgroup_commit_charge+0x7a/0x560
[Thu Oct 22 17:07:23 2020]  do_wp_page+0x8e/0x5f0
[Thu Oct 22 17:07:23 2020]  __handle_mm_fault+0xb8b/0x1270
[Thu Oct 22 17:07:23 2020]  handle_mm_fault+0xd6/0x200
[Thu Oct 22 17:07:23 2020]  __do_page_fault+0x249/0x4f0
[Thu Oct 22 17:07:23 2020]  ? async_page_fault+0x8/0x30
[Thu Oct 22 17:07:23 2020]  async_page_fault+0x1e/0x30
[Thu Oct 22 17:07:23 2020] RIP: 0033:0x426062
[Thu Oct 22 17:07:23 2020] Code: 40 00 0f 83 84 00 00 00 49 89 f0 48 c1 ee 0d 48 8b 1c c3 4c 8b 4c 24 30 4c 8b 54 24 38 31 c0 eb 16 84 03 49 81 e3 ff 1f 00 00 <4e> 89 94 db 00 00 20 00 49 8d 44 24 01 4c 39 c8 73 3c 4c 8d 1c 06
[Thu Oct 22 17:07:23 2020] RSP: 002b:000000c000fb7e20 EFLAGS: 00010206
[Thu Oct 22 17:07:23 2020] RAX: 0000000000000000 RBX: 00007f6b58729000 RCX: 0000000000000001
[Thu Oct 22 17:07:23 2020] RDX: 00000000040c7e80 RSI: 000000000602d400 RDI: 0000800000000000
[Thu Oct 22 17:07:23 2020] RBP: 000000c000fb7e30 R08: 000000c05a800000 R09: 0000000000000001
[Thu Oct 22 17:07:23 2020] R10: 00007f6b58698938 R11: 0000000000001400 R12: 0000000000000000
[Thu Oct 22 17:07:23 2020] R13: 0000000000000040 R14: 0000000002d6398a R15: 0000000000000000
[Thu Oct 22 17:07:23 2020] Task in /kubepods/burstable/pod3d119d81-b7a2-409b-9644-53b2d14fe566/26d08f5914482eed4eb5837b64e0945b5a549df244d6b8acd1d86a7a9c09ec73 killed as a result of limit of /kubepods/burstable/pod3d119d81-b7a2-409b-9644-53b2d14fe566/26d08f5914482eed4eb5837b64e0945b5a549df244d6b8acd1d86a7a9c09ec73
[Thu Oct 22 17:07:23 2020] memory: usage 1536000kB, limit 1536000kB, failcnt 75651
[Thu Oct 22 17:07:23 2020] memory+swap: usage 0kB, limit 9007199254740988kB, failcnt 0
[Thu Oct 22 17:07:23 2020] kmem: usage 9916kB, limit 9007199254740988kB, failcnt 0
[Thu Oct 22 17:07:23 2020] Memory cgroup stats for /kubepods/burstable/pod3d119d81-b7a2-409b-9644-53b2d14fe566/26d08f5914482eed4eb5837b64e0945b5a549df244d6b8acd1d86a7a9c09ec73: cache:496KB rss:1525432KB rss_huge:0KB shmem:0KB mapped_file:132KB dirty:264KB writeback:0KB inactive_anon:0KB active_anon:1525948KB inactive_file:68KB active_file:68KB unevictable:0KB
[Thu Oct 22 17:07:23 2020] Tasks state (memory values in pages):
```

It's weird since you have tons of memory available. It seems you've set the Prometheus memory limitation to around 1.5Gb and it was killed due to exceeding that limit.

Also, from the latest support bundle, you have 18 volumes. Since your network bandwidth is 1Gbps = 128MiB, so each volume may have about 7MiB per second bandwidth, which is pretty low. So I still think the network is the cause of frequent disconnection here.

Longhorn v1.1.0 is targeting middle November so it's about half a month from now.

**Comment by yasker** [comment]
@DarianAnjuhal has reached out to me in slack, mentioned his issue still exists. 

One KB article might help: https://longhorn.io/kb/troubleshooting-volume-readonly-or-io-error/

@DarianAnjuhal Can you also fill in the questionnaire below again:

**Environment:**
 - Longhorn version:
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of volumes in the system:

**Comment by mattcg** [comment]
This problem disappeared once we moved from HDDs to SSDs, however that required spending a lot of money and losing time.

**Comment by yasker** [comment]
@mattcg @DarianAnjuhal Longhorn isn't designed for HDD though. The IOPS of HDD can provide is below what Longhorn requires, so it's hard to provide a stable system in that way. See https://longhorn.io/docs/1.1.0/best-practices/#minimum-recommended-hardware

**Comment by mattcg** [comment]
All SSD k8s is a pretty big ask. In my opinion software should be designed around the needs of organisations, and not vice versa...

**Comment by yasker** [comment]
@mattcg Sorry to hear that. Supporting the spinning disk is not the design goal of Longhorn. Since the random IOPS is too low with a spinning disk, the software needs to be much more complex just to handle it properly. I suggest looking at other storage solutions that support spinning disk well, to better support your use case.

**Comment by DarianAnjuhal** [comment]
Okay thank you. We are using HDD as well so thats probably why we have issues.
