### ISSUE TITLE
How to get rid of old snapshots without opening every volume and click delete snapshot potencially hundred of times..

### ISSUE THREAD

**Issue by IJOL** [longhorn/longhorn#1826]

**Comment by IJOL** [comment]
We have discovered the lhctl tool  from https://github.com/utilitywarehouse/lhctl and this helped a lot with stopped replicas that pollute almost every day our volumes, but to get rid of all snapshots automatically generated by a bad cron config are almost ionly eraseable by ui.. its overwhelming in some case we have, that has literally for a volume of 10Gb , almost 100GB in snapshots, by the thousands

**Comment by yasker** [comment]
@IJOL You can setup a recurring snapshot/backup which will automatically clean up system generated snapshot as a side effect. See https://longhorn.io/docs/1.0.2/best-practices/#volume-maintenance

**Comment by yasker** [comment]
Bad cron config? Can you elaborate?

**Comment by courcelm** [comment]
Even with recurring snapshots, snapshots sometime accumulate for a unknow reason. It would be convenient that the UI provide a way to delete multiple or all snapshot at once.

**Comment by IJOL** [comment]
This happens to us all the time, hence the need for continuous clean up, so
maybe I just reporting a bug, we found that very frequently, and if this
add to an unstable node that keeps asking every now and then for a new
replica, the storage disappear before our eyes..  getting rid of stale
replicas is a need why lh needs to keep replicas stopped after another one
is created, and this, in turn, creates continuous cascades of hidden system
snapshots.. so the cleanup.


Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega

**Comment by yasker** [comment]
Regarding the automatically cleanup system generated snapshot, we're planning to include a feature in v1.1.0 to help. #1669 

Regarding saving the space for replica rebuilding, we're working #1304 which is also targeting for v1.1.0.

**Comment by yasker** [comment]
@courcelm Can you elaborate your case of accumulating snapshot? What does it look like? Is it system generated (for rebuild) or not?

**Comment by courcelm** [comment]
@yasker In my case it was scheduled snapshots that were not cleaning correctly for a particular volume. At some point it prevents creation of a new replicate on another node.

Great to hear about #1304 . I would be nice for node reboot.

**Comment by yasker** [comment]
@courcelm I am trying to see if we have the report for your issue before, but cannot find it (https://github.com/longhorn/longhorn/issues/478#issuecomment-497078560 looks similar but that's long time ago). If the snapshot cannot coalesce then there will be a problem for the replica rebuild in the future.

**Comment by innobead** [comment]
remove stale due to the incorrect exempt label

**Comment by jehof** [comment]
yes we are experincing the same. Especially with the volume for prometheus pf the rancher-monitoring-stack that uses a 50 GB pvc. We have disabled recurring snapshots, but the (system) snapshots keep comming. Now we have again a 43 GB snapshot that is marked as removed, but is still there. 

And the actual size gets increasing and we are manually cleaning up and alert manager fires "_The actual space used by Longhorn volume pvc-0e062f2d-6151-4e34-8597-23de1afd7189 on worker-3 is at 101.47991180419922% capacity for more than 5"_

The used data of prometheus on the volume itself is only 7.3 GB.

/dev/longhorn/pvc-0e062f2d-6151-4e34-8597-23de1afd7189
                         49.0G      7.3G     41.6G  15% /prometheus

**Comment by cod-r** [comment]
> yes we are experincing the same. Especially with the volume for prometheus pf the rancher-monitoring-stack that uses a 50 GB pvc. We have disabled recurring snapshots, but the (system) snapshots keep comming. Now we have again a 43 GB snapshot that is marked as removed, but is still there.
> 
> And the actual size gets increasing and we are manually cleaning up and alert manager fires "_The actual space used by Longhorn volume pvc-0e062f2d-6151-4e34-8597-23de1afd7189 on worker-3 is at 101.47991180419922% capacity for more than 5"_
> 
> The used data of prometheus on the volume itself is only 7.3 GB. I have no clue why we get such big snapshots.
> 
> ```
> /dev/longhorn/pvc-0e062f2d-6151-4e34-8597-23de1afd7189
>                          49.0G      7.3G     41.6G  15% /prometheus
> ```
> 
> _Automatically Cleanup System Generated Snapshot_ is enabled

I have the same problem with prometheus pvc as @jehof 
How do we solve this? It looks like it will just grow forever with the system snapshots

**Comment by innobead** [comment]
cc @shuo-wu @PhanLe1010

**Comment by cod-r** [comment]
> yes we are experincing the same. Especially with the volume for prometheus pf the rancher-monitoring-stack that uses a 50 GB pvc. We have disabled recurring snapshots, but the (system) snapshots keep comming. Now we have again a 43 GB snapshot that is marked as removed, but is still there.
> 
> And the actual size gets increasing and we are manually cleaning up and alert manager fires "_The actual space used by Longhorn volume pvc-0e062f2d-6151-4e34-8597-23de1afd7189 on worker-3 is at 101.47991180419922% capacity for more than 5"_
> 
> The used data of prometheus on the volume itself is only 7.3 GB. I have no clue why we get such big snapshots.
> 
> ```
> /dev/longhorn/pvc-0e062f2d-6151-4e34-8597-23de1afd7189
>                          49.0G      7.3G     41.6G  15% /prometheus
> ```
> 
> _Automatically Cleanup System Generated Snapshot_ is enabled

Anyone found a workaround for this?

**Comment by krishnakc1** [comment]
I still have a problem but as @yasker suggested. I enabled auto snapshot backups so that it gets rid of other snapshots automatically. I will check this and update tomorrow.

**Comment by bagdus** [comment]
This problem appears (at least) also for Elasticsearch + kibana. The indexes are deleted and the logs themselves take up < 10% of volume, but there seems like the system created snapshot is never cleaned up properly even if it says "Removed" in the UI. So disk storage is 100% used.

**Comment by PhanLe1010** [comment]
There seems to be 2 different topics in this issues:
1. Why the size viewed inside the filesystem is much smaller than the actual size of the volume? 
2. Why the system snapshots are not cleaned up?

The 1st topic is expected and is explained here This is expected and explained here https://longhorn.io/docs/1.2.3/volumes-and-nodes/volume-size/

The 2nd topic needs to be investigated. @bagdus Can you provide the support bundle to `longhorn-support-bundle@suse.com`?

**Comment by krishnakc1** [comment]
Few more details in the hope it helps in troubleshooting this. Please see the screenshots. I have called out for the snapshots to retain only a single snapshot. Yet, it does not follow that leaving the old ones out there while creating new ones causing more filling up.
![image](https://user-images.githubusercontent.com/26587125/150135423-a8c37d32-dd7e-4b5d-83ad-36a6dd4e9ae9.png)
hidden snapshots:
![image](https://user-images.githubusercontent.com/26587125/150135509-8ba05034-7d81-47ce-96fd-b4020bd9f594.png)

I am giving a chance for the longhorn to clean these old snapshots but it does not clean. Can I just force clean these from the disk? With disk filling up, for me the important is to clean this old data from the disk rather than leaving them to be used by PVs. This is going on three nodes where the elastic search data is being stored.

**Comment by PhanLe1010** [comment]
@krishnakc1 

Please don't remove the data on the host directly. It will mess up Longhorn volume.

Can you send us a support bundle to `longhorn-support-bundle@suse.com` for a closer look? And ping me afterward?

**Comment by bagdus** [comment]
> There seems to be 2 different topics in this issues:
> 
>     1. Why the size viewed inside the filesystem is much smaller than the actual size of the volume?
> 
>     2. Why the system snapshots are not cleaned up?
> 
> 
> The 1st topic is expected and is explained here This is expected and explained here https://longhorn.io/docs/1.2.3/volumes-and-nodes/volume-size/
> 
> The 2nd topic needs to be investigated. @bagdus Can you provide the support bundle to `longhorn-support-bundle@suse.com`?

I did activate a cron job to create 2 snapshots a day, and the system snapshot was removed after some time, so it seems that is not the issue. However the data retained in that snapshot never seems to be subtracted from the following snapshots. I always have around ~11 Gb data on the longhorn volume, but the snapshot stays at a hefty 90 Gb even after numerous re-creations. Should not the deleted data eventually be subtracted from the snapshot size? That's what i understand from the explanation of volume size and snapshots.

I'll gladly send a support bundle if needed!

![image](https://user-images.githubusercontent.com/88330717/150485156-273d82ee-9e6c-4bbb-b6f8-985a8056ef4e.png)

**Comment by iosifnicolae2** [comment]
Any solution for this problem?

Longhorn v1.2.3
![image](https://user-images.githubusercontent.com/7108834/150990224-e1166d63-7e4b-46d3-9499-68184b73c26d.png)

![image](https://user-images.githubusercontent.com/7108834/150989927-fcaed28f-dcb6-4006-9790-43a675bc30e5.png)

**Comment by shuo-wu** [comment]
@iosifnicolae2 

Volume `pvc-61defda0-969a-4404-a076-1ce0de63b791` starts the snapshot surge(actual cleanup) but there are replica eviction and volume detachment happening simultaneously around `2022-01-24T20:40:21Z`

  Detachment log:
  ```
  2022-01-24T21:40:25.164278827+01:00 time="2022-01-24T20:40:25Z" level=debug msg="Volume pvc-61defda0-969a-4404-a076-1ce0de63b791 unpublished from dedicated-worker-1"
  ```

  Snapshot purge and replica eviction log
  ```
  2022-01-24T21:40:21.420372052+01:00 time="2022-01-24T20:40:21Z" level=debug msg="Volume pvc-61defda0-969a-4404-a076-1ce0de63b791 snapshot purge started"
  2022-01-24T21:40:21.420383934+01:00 time="2022-01-24T20:40:21Z" level=debug msg="Started snapshot purge for volume pvc-61defda0-969a-4404-a076-1ce0de63b791 after rebuild is done"
  
  2022-01-24T21:40:24.878766485+01:00 time="2022-01-24T20:40:24Z" level=debug msg="Evicted replica pvc-61defda0-969a-4404-a076-1ce0de63b791-r-b1184278"
  2022-01-24T21:40:25.041941584+01:00 time="2022-01-24T20:40:25Z" level=debug msg="Cleanup replica completed" controller=longhorn-replica dataPath= node=dedicated-worker-1 nodeID=dedicated-worker-1 ownerID=dedicated-worker-1 replica=pvc-61defda0-969a-4404-a076-1ce0de63b791-r-b1184278
  ```

Besides, there is a pending expansion request for this volume and it can be handled only after the volume is detached:
```
2022-01-24T21:40:20.792727513+01:00 time="2022-01-24T20:40:20Z" level=error msg="ControllerExpandVolume: err: rpc error: code = FailedPrecondition desc = volume pvc-61defda0-969a-4404-a076-1ce0de63b791 invalid state attached for expansion"
2022-01-24T21:40:21.162987945+01:00 time="2022-01-24T20:40:21Z" level=debug msg="Polling volume pvc-61defda0-969a-4404-a076-1ce0de63b791 state for volume unpublished at 2022-01-24 20:40:21.162845277 +0000 UTC m=+43843.766672829"
``` 

In general, the operations for this volume are messy at that moment... Can you re-trigger the snapshot purge by deleting one snapshot manually via GUI?

---

Besides, there is one confusing scenario. Some snapshots of the volume should be purged by all replicas before the detachment and they still exist after the reattachment...
```

2022-01-24T21:40:21.421874579+01:00 [pvc-61defda0-969a-4404-a076-1ce0de63b791-r-e9b756ce] time="2022-01-24T20:40:21Z" level=info msg="Prepare removing disk: 5a72b31c-b7ab-406c-9774-15d3deb517f2"
2022-01-24T21:40:21.422030837+01:00 [pvc-61defda0-969a-4404-a076-1ce0de63b791-r-e9b756ce] time="2022-01-24T20:40:21Z" level=info msg="Coalescing volume-snap-9e9ef020-4598-4a77-a815-2483fe2eeb02.img to volume-snap-5a72b31c-b7ab-406c-9774-15d3deb517f2.img"
2022-01-24T21:40:22.243033926+01:00 [pvc-61defda0-969a-4404-a076-1ce0de63b791-r-e9b756ce] time="2022-01-24T20:40:22Z" level=info msg="Replace volume-snap-9e9ef020-4598-4a77-a815-2483fe2eeb02.img with volume-snap-5a72b31c-b7ab-406c-9774-15d3deb517f2.img"
2022-01-24T21:40:22.243518870+01:00 [pvc-61defda0-969a-4404-a076-1ce0de63b791-r-e9b756ce] time="2022-01-24T20:40:22Z" level=info msg="Replacing disk volume-snap-5a72b31c-b7ab-406c-9774-15d3deb517f2.img with volume-snap-9e9ef020-4598-4a77-a815-2483fe2eeb02.img"
2022-01-24T21:40:22.243684907+01:00 [pvc-61defda0-969a-4404-a076-1ce0de63b791-r-e9b756ce] time="2022-01-24T20:40:22Z" level=info msg="Old file volume-snap-9e9ef020-4598-4a77-a815-2483fe2eeb02.img exists, deleting"
2022-01-24T21:40:22.595527252+01:00 [pvc-61defda0-969a-4404-a076-1ce0de63b791-r-e9b756ce] time="2022-01-24T20:40:22Z" level=info msg="Done replacing volume-snap-9e9ef020-4598-4a77-a815-2483fe2eeb02.img with volume-snap-5a72b31c-b7ab-406c-9774-15d3deb517f2.img"
2022-01-24T21:40:22.596293586+01:00 [pvc-61defda0-969a-4404-a076-1ce0de63b791-r-e9b756ce] time="2022-01-24T20:40:22Z" level=info msg="Prepare removing disk: expand-3221225472000"
2022-01-24T21:40:22.596449884+01:00 [pvc-61defda0-969a-4404-a076-1ce0de63b791-r-e9b756ce] time="2022-01-24T20:40:22Z" level=info msg="Coalescing volume-snap-9e9ef020-4598-4a77-a815-2483fe2eeb02.img to volume-snap-expand-3221225472000.img"
```
```
2022-01-24T21:40:21.420862142+01:00 [pvc-61defda0-969a-4404-a076-1ce0de63b791-r-b1184278] time="2022-01-24T20:40:21Z" level=info msg="Marking disk 9e9ef020-4598-4a77-a815-2483fe2eeb02 as removed"
2022-01-24T21:40:21.421715094+01:00 [pvc-61defda0-969a-4404-a076-1ce0de63b791-r-b1184278] time="2022-01-24T20:40:21Z" level=info msg="Prepare removing disk: 9e9ef020-4598-4a77-a815-2483fe2eeb02"
2022-01-24T21:40:21.421820420+01:00 [pvc-61defda0-969a-4404-a076-1ce0de63b791-r-b1184278] time="2022-01-24T20:40:21Z" level=info msg="Currently snapshot volume-snap-9e9ef020-4598-4a77-a815-2483fe2eeb02.img doesn't meet criteria to be removed, skip it for now"
2022-01-24T21:40:21.422057530+01:00 [pvc-61defda0-969a-4404-a076-1ce0de63b791-r-b1184278] time="2022-01-24T20:40:21Z" level=info msg="Prepare removing disk: 5a72b31c-b7ab-406c-9774-15d3deb517f2"
2022-01-24T21:40:21.422169788+01:00 [pvc-61defda0-969a-4404-a076-1ce0de63b791-r-b1184278] time="2022-01-24T20:40:21Z" level=info msg="Coalescing volume-snap-9e9ef020-4598-4a77-a815-2483fe2eeb02.img to volume-snap-5a72b31c-b7ab-406c-9774-15d3deb517f2.img"
2022-01-24T21:40:21.949228053+01:00 [pvc-61defda0-969a-4404-a076-1ce0de63b791-r-b1184278] time="2022-01-24T20:40:21Z" level=info msg="Replace volume-snap-9e9ef020-4598-4a77-a815-2483fe2eeb02.img with volume-snap-5a72b31c-b7ab-406c-9774-15d3deb517f2.img"
2022-01-24T21:40:21.949750693+01:00 [pvc-61defda0-969a-4404-a076-1ce0de63b791-r-b1184278] time="2022-01-24T20:40:21Z" level=info msg="Replacing disk volume-snap-5a72b31c-b7ab-406c-9774-15d3deb517f2.img with volume-snap-9e9ef020-4598-4a77-a815-2483fe2eeb02.img"
2022-01-24T21:40:21.949905190+01:00 [pvc-61defda0-969a-4404-a076-1ce0de63b791-r-b1184278] time="2022-01-24T20:40:21Z" level=info msg="Old file volume-snap-9e9ef020-4598-4a77-a815-2483fe2eeb02.img exists, deleting"
2022-01-24T21:40:22.322941770+01:00 [pvc-61defda0-969a-4404-a076-1ce0de63b791-r-b1184278] time="2022-01-24T20:40:22Z" level=info msg="Done replacing volume-snap-9e9ef020-4598-4a77-a815-2483fe2eeb02.img with volume-snap-5a72b31c-b7ab-406c-9774-15d3deb517f2.img"
```

**Comment by shuo-wu** [comment]
@bagdus No. Longhorn is a block-level storage system hence it does not understand the filesystem. This is the key point for your question. In your/filesystem perspective, the space will be released after the file removal from the filesystem. But in Longhorn perspective, the sectors of the block device are already used and the filesystem currently has no way to inform the block device to release the sectors. In the doc explanation, the actual size of the volume can be reduced only when the overlapping part(the sectors are used in both snapshot files) is released by the snapshot purge.

**Comment by iosifnicolae2** [comment]
@shuo-wu I don't find the option to delete a system snapshot..

**Comment by shuo-wu** [comment]
@iosifnicolae2 Deleting any snapshots will trigger system snapshot cleanup.

**Comment by iosifnicolae2** [comment]
@shuo-wu I've deleted the latest snapshot created manually, but I still have a system snapshot on my disk even though on Longhorn UI it says that it was deleted..
![image](https://user-images.githubusercontent.com/7108834/151663164-57dd9eed-6299-4bcc-a2a0-95e717427f1c.png)
![image](https://user-images.githubusercontent.com/7108834/151663174-aa1bd3dc-5e48-4a91-aa0f-f6815273628e.png)

**Comment by bagdus** [comment]
> @bagdus No. Longhorn is a block-level storage system hence it does not understand the filesystem. This is the key point for your question. In your/filesystem perspective, the space will be released after the file removal from the filesystem. But in Longhorn perspective, the sectors of the block device are already used and the filesystem currently has no way to inform the block device to release the sectors. In the doc explanation, the actual size of the volume can be reduced only when the overlapping part(the sectors are used in both snapshot files) is released by the snapshot purge.

I thought i understood this, but i apparently do not properly understand it.
I have a snapshot containing much data which has not existed on the storage device for a long time. But Longhorn cannot know if it exists or not, since it only compares the data in Volume Head with the snapshot and adds it to the snapshot, it does not remove the files that are not existing in either snapshot or volume head.

So currently my situation looks like this after trying to delete a few snapshots through the UI. How can i ever fix the displayed storage to be correct?

![image](https://user-images.githubusercontent.com/88330717/151755035-9f327b42-43ba-4e8f-8945-ffa590b8ade6.png)

**Comment by iosifnicolae2** [comment]
Currently, the same problem is happening with volumes on other nodes too.. 

Does anyone happen to know a workaround or how to fix this problem?

Thanks!

**Comment by shuo-wu** [comment]
> @shuo-wu I've deleted the latest snapshot created manually, but I still have a system snapshot on my disk even though on Longhorn UI it says that it was deleted.. ![image](https://user-images.githubusercontent.com/7108834/151663164-57dd9eed-6299-4bcc-a2a0-95e717427f1c.png) ![image](https://user-images.githubusercontent.com/7108834/151663174-aa1bd3dc-5e48-4a91-aa0f-f6815273628e.png)
> 
> Is it safe to delete the snapshot from disk manually?

NO. Please do not operate the files in replica directories manually.
The snapshot that directly stands behind the volume head cannot be removed. This is not an issue. You can ignore it.

**Comment by shuo-wu** [comment]
> Thank you for the reply @shuo-wu I thought i understood this, but i apparently do not properly understand it. I have a snapshot with a very large indicated size, but the reality of the device usage hasn't been this for a long time (it has been about 16 GB while the snapshot keeps growing). So i understand Longhorn cannot know if the old data exists or not, since it only compares the data in Volume Head with the snapshot and adds it to the snapshot, it does not remove the files that are not existing in either snapshot or volume head.
> 
> So currently my situation looks like this after trying to delete a few snapshots through the UI. How can i ever fix the displayed storage to be correct? This all started with a node crash and subsequent rebuild which created a system snapshot

More accurately, Longhorn will compare then merge the sector usage for 2 snapshots during snapshot deletion

The actual size of the volume shown in UI is correct. Since there are more than 1 snapshot/volume head in the volume and **each** of them would consume 100Gi **at max**.

**Comment by iosifnicolae2** [comment]
@shuo-wu If I create a volume with 100Gi and the space inside the volume is used 100%, what will be the normal actual size of the volume on disk, is it 100Gi + a few KB for storing some metadata, right?

Right now, I have the actual size much bigger than the actual volume, even though I've triggered snapshot deletion for it.

**Comment by shuo-wu** [comment]
> @shuo-wu If I create a volume with 100Gi and the space inside the volume is used 100%, what will be the normal actual size of the volume on disk, is it 100Gi + a few KB for storing some metadata, right?
> 
> Right now, I have the actual size much bigger than the actual volume, even though I've triggered snapshot deletion for it.

No. The data of a volume is stored in **a bunch of sparse** files. And **each** sparse file can eat up to 100Gi space. This is why the actual size of a volume can be greater than the spec size. Removing/purging a snapshot actually means squashing the non-expired data of the related sparse file into another sparse file then deletes the file.

**Comment by shuo-wu** [comment]
Maybe https://github.com/longhorn/longhorn/issues/3836 would help resolve this issue

**Comment by usma0118** [comment]
+1 facing same issue.

**Comment by PhanLe1010** [comment]
In Longhorn v1.3.0, you can find all snapshots of the volumes using `kubectl get snapshots.longhorn.io -n longhorn-system -l longhornvolume=<VOLUME-NAME>` and delete those snapshots using `kubectl delete snapshots.longhorn.io <SNAPSHOT-NAME>  -n longhorn-system`

**Comment by innobead** [comment]
> In Longhorn v1.3.0, you can find all snapshots of the volumes using `kubectl get snapshots.longhorn.io -n longhorn-system -l longhornvolume=<VOLUME-NAME>` and delete those snapshots using `kubectl delete snapshots.longhorn.io <SNAPSHOT-NAME> -n longhorn-system`
> 
> Note: the snapshot next to volume-head will not be able to be deleted immediately.

The solution has been supported by longhorn snapshot CR.
