### ISSUE TITLE
lhexec aka longhorn cli, documentation where?

### ISSUE THREAD

**Issue by IJOL** [longhorn/longhorn#1828]
Just discovered lhexec and tried to use it, listed replicas, and something more, snapshots, and so on, but tried to list backups and not found how to use it.. any help..

**Comment by yasker** [comment]
In fact, `lhexec` wasn't designed to te the `Longhorn CLI`. It's more like a dev tool and provides the access to a single volume engine when it's attached. We are planning to have an official `Longhorn CLI` in v1.2.0.

`backup` commands are a bit more complicated. We don't have documentation about it at the moment. What's your use case?

**Comment by IJOL** [comment]
Sorry for be so late, i expressed my use case at slackware channel, but to clear, i need smething along the lines of

lhexec backup --pvc ns/pvc  
in a source cluster 
lhexec restore --pvc ns/pvc --latest 
in a target one

**Comment by yasker** [comment]
@IJOL We will publish a python client reference (https://github.com/longhorn/longhorn/issues/1976) to help with backup/restore commands.

Close this in favor of #1976
