### ISSUE TITLE
[BUG] Modify the README uninstallation section in the chart available for rancher v2.5

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1829]
**Describe the bug**
The chart's README uninstallation section should be modified in the chart https://git.rancher.io/charts branch - dev 2.5 as it says ```From Rancher UI, navigate to Catalog Apps tab and delete Longhorn app.```

https://github.com/rancher/charts/blob/dev-v2.5/charts/longhorn/README.md

The above chart is used in the rancher Dashboard where there is no catalog apps tab present and README says to delete the app from the catalog apps tab.

**Comment by meldafrawi** [comment]
Validation: **PASSED**


![image](https://user-images.githubusercontent.com/18232258/102524150-3cdd9900-40a1-11eb-84ee-1d22dbf38a94.png)
