### ISSUE TITLE
[FEATURE] OKD/Openshift support

### ISSUE THREAD

**Issue by ghost** [longhorn/longhorn#1831]
Is it possible to deploy Longhorn on top of OKD (4.5)? Can someone share the correct SecurityContextConstraints & Longhorn settings in order to successfully deploy it in Fedora Coreos  / OKD cluster.

Thank you

**Comment by yasker** [comment]
I've heard people running Longhorn on top of OKD, but we haven't got time to experiment with it ourselves. It should be the same as a normal Kubernetes cluster? We can give it a try to see how it works.

Are there any specific constrains OKD have?

**Comment by Born2Bake** [comment]
> I've heard people running Longhorn on top of OKD, but we haven't got time to experiment with it ourselves. It should be the same as a normal Kubernetes cluster? We can give it a try to see how it works.
> 
> Are there any specific constrains OKD have?

I am struggling to deploy it. Firstly, I ve used ssc from here https://rook.io/docs/rook/v1.4/ceph-openshift.html so longhorn-manager ds could start running. However, they are still failing with error:
‘’’
is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
‘’’

**Comment by Born2Bake** [comment]
[longhorn-manager-fvllp-longhorn-manager.log](https://github.com/longhorn/longhorn/files/5299484/longhorn-manager-fvllp-longhorn-manager.log)
[longhorn-manager-8rjbj-longhorn-manager.log](https://github.com/longhorn/longhorn/files/5299485/longhorn-manager-8rjbj-longhorn-manager.log)
[longhorn-manager-fvqcr-longhorn-manager.log](https://github.com/longhorn/longhorn/files/5299486/longhorn-manager-fvqcr-longhorn-manager.log)

I have addded 3 log files from workers. Is there anyone who can assist with that error?

**Comment by yasker** [comment]
We can refer to https://github.com/longhorn/longhorn/issues/1757 for some informations.

Also, need to check if we can get rid of bindmount `/var/run` in the manager. See https://github.com/longhorn/longhorn/issues/1757 for details.

**Comment by tvanderka** [comment]
Some notes I made when deploying to OKD 4.5:

1. Openshift uses SCC instead of PSP, give longhorn some privileges
```
oc adm policy add-scc-to-user anyuid -z default -n longhorn-system
oc adm policy add-scc-to-user privileged -z longhorn-service-account -n longhorn-system
```
2. Add permissions on node+engineimages/finalizers to longhorn-role
```
 - verbs:
      - '*'
    apiGroups:
      - longhorn.io
    resources:
      - engineimages/finalizers
      - nodes/finalizers
      ...
```
3. Enable iscsid.service on nodes
4. Fix selinux label on /var/lib/kubelet/obsoleted-longhorn-plugins (not sure why I did it like this)
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 50-set-selinux-for-longhorn
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=Set SELinux for longhorn csi
            Before=kubelet.service

            [Service]
            ExecStart=/usr/bin/chcon -Rt container_file_t /var/lib/kubelet/obsoleted-longhorn-plugins 

            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: longhorn-hostpath-provisioner-selinux.service
```

There are some issues with node draining and rolling upgrades, see #1631

**Comment by jwklijnsma** [comment]
Hi is this fix in version 1.1.0 are 1.1.1 ?

**Comment by chrisu001** [comment]
> Some notes I made when deploying to OKD 4.5:

@tvanderka many thanks for your notes
I can confirm that longhorn 1.1.0 is running on OKD4.6

additionally:

1. as a workaround for the usage of ``` /var/lib/kubelet/obsoleted-longhorn-plugins```, I created a machine-config with a oneshot service
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 51-set-longhorn-worker
  labels:
    {{- include "project.labels" . | nindent 4 }}
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=Set SELinux chcon for longhorn
            Before=kubelet.service

            [Service]
            Type=oneshot
            RemainAfterExit=true
            ExecStartPre=/usr/bin/mkdir -p  /var/lib/kubelet/obsoleted-longhorn-plugins
            ExecStart=-/usr/bin/chcon -Rt container_file_t /var/lib/kubelet/obsoleted-longhorn-plugins

            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: longhorn-provisioner.service
        - name: iscsid.service
          enabled: true
          state: "started"
```

2. removed ```/var/run``` from deployment.yaml 
3. added oauth-proxy to the longhorn-ui.yaml
 
4. Rolling Updates
> There are some issues with node draining and rolling upgrades, see #1631

as a quickfix (hopefully, only until  version 1.1.1/2) I wrote a litle bash-hack to go with rolling updates
```
#!/bin/bash

set -e
currentActive=""

while : ; do

  currentActive=$(oc get nodes | fgrep "worker " |awk '/SchedulingDisabled/ {print $1 }')
  [[ -z "${currentActive}" ]] && sleep 5 && continue

  echo_info "volume evict ${currentActive}"
  oc patch -n longhorn nodes.longhorn.io ${currentActive} -p '{"spec":{"allowScheduling": false,"evictionRequested": true}}' --type=merge

  while : ; do
   check=$(oc get nodes ${currentActive} | fgrep "worker " | fgrep SchedulingDisabled)
   [[ -n ${check} ]] || break
   echo -n "."
   sleep 5
  done

  echo ""
  echo_info "enable volumes ${currentActive}"
  oc patch -n longhorn nodes.longhorn.io ${currentActive} -p '{"spec":{"allowScheduling": true,"evictionRequested": false}}' --type=merge
done
```

**Comment by jwklijnsma** [comment]
@chrisu001 do your have for 2 maybe more information ?

**Comment by chrisu001** [comment]
> @chrisu001 do your have for 2 maybe more information ?

simple remove the deprecated mount point from: https://github.com/longhorn/longhorn/blob/0fd0c33e06d7c998dee0f9a43056e4a0030638d9/chart/templates/daemonset-sa.yaml#L48

**Comment by jwklijnsma** [comment]
And 3 you add the oauth-proxy to the longhorn-ui.yaml is that safe ?

**Comment by jwklijnsma** [comment]
@chrisu001 is your machine set config correct i test on okd 4.6 but getting this error error: error parsing fix-longhorn.yaml: error converting YAML to JSON: yaml: line 6: did not find expected node content

**Comment by chrisu001** [comment]
> @chrisu001 is your machine set config correct i test on okd 4.6 but getting this error error: error parsing fix-longhorn.yaml: error converting YAML to JSON: yaml: line 6: did not find expected node content
@jwklijnsma  remove the line
```
 {{- include "project.labels" . | nindent 4 }}
```
this is an extension of my helm chart toolkit template

Adding an oauth-proxy as a sidecar container is possible and safe, yes. Pls refer to the documentation of OKD. Maybe I'll find the time to write some gists

**Comment by Born2Bake** [comment]
How do you guys add disks to the nodes though? via MachineConfig?

**Comment by sadoMasupilami** [comment]
is it still planed to support okd/openshift?

**Comment by jwklijnsma** [comment]
it is still open mr for the project https://github.com/longhorn/longhorn/pull/2909

**Comment by mujeebishaque** [comment]
I got an error related to nfs-utils installation on CoreOS. Now, I logged in to my CoreOS node and checked for the already installed packages. It turns out that CoreOS already has a different version of `nfs-utils` named `nfs-utils-coreos`. 

I don't know what's the problem. Would appreciate any help.

**Comment by mantissahz** [comment]
@mujeebishaque maybe you could try `rpm-ostree override remove nfs-utils-coreos --install nfs-utils` from this https://github.com/coreos/fedora-coreos-tracker/issues/572#issuecomment-658918470

**Comment by ArthurVardevanyan** [comment]
Updated PR: https://github.com/longhorn/longhorn/pull/5004

**Comment by dsuth1** [comment]
> 1. Openshift uses SCC instead of PSP, give longhorn needed privileges
> 
> ```
> oc adm policy add-scc-to-user anyuid -z default -n longhorn-system
> oc adm policy add-scc-to-user privileged -z longhorn-service-account -n longhorn-system
> ```
> 
> 2. Add permissions on node+engineimages/finalizers to longhorn-role. Required by OwnerReferencesPermissionEnforcement admission controller (not openshift specific, I hit this on different k8s cluster).
> 
> ```
>  - verbs:
>       - '*'
>     apiGroups:
>       - longhorn.io
>     resources:
>       - engineimages/finalizers
>       - nodes/finalizers
>       ...
> ```

For those that are curious, confirm Longhorn 1.42 will deploy to OpenShift 4.12 using Steps 1 and 2 here

**Comment by roger-ryao** [comment]
**Verified on master-head 20230907**

- longhorn master-head https://github.com/longhorn/longhorn/commit/9948983b15f7d82af44a45917c270313668c3b2c


**The test steps**
https://github.com/longhorn/longhorn/issues/1831#issuecomment-1352487615

**Result Passed**

- [x] OKD cluster new installed.
- [x] Follow the steps in [longhorn/chart/ocp-readme.md](https://github.com/longhorn/longhorn/blob/master/chart/ocp-readme.md)
- [x] Functionalities of Longhorn work well.
    1.   Fresh install 
    2.   Create a statefulset and write data
    3.   Scale down/up workload
    4.   Trigger replica rebuilding
    5.   Create volume backup and restored
    6.   Verify volume data
    7.   Uninstall
- [x] require/doc : Checked documentation in https://github.com/longhorn/website/pull/765
