### ISSUE TITLE
Provide Prometheus metrics for node/disk 

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#1832]
Longhorn should provide the following metrics:

1. longhorn_disk_capacity_bytes
1. longhorn_disk_usage_bytes
1. longhorn_node_capacity_bytes
1. longhorn_node_usage_bytes

Users can use those metrics for monitor and alert when node/disk used spaces are approaching capacities. 

**Additional context**
This issue is related to the issue https://github.com/longhorn/longhorn/issues/1180

**Comment by PhanLe1010** [comment]
**test steps:**

Follow the setup at https://github.com/longhorn/longhorn-tests/blob/master/docs/content/manual/release-specific/v1.1.0/prometheus_support.md

Verify data expose by the following metrics:
1. longhorn_node_storage_capacity_bytes
2. longhorn_node_storage_usage_bytes
3. longhorn_node_storage_reservation_bytes
4. longhorn_disk_capacity_bytes
5. longhorn_disk_usage_bytes
6. longhorn_disk_reservation_bytes

Also, verify that we get appropriate alerts when going above thread sold

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master - 11/18/2020

Validation - **Pass**

The below metrics are available and shows correct data:
1. longhorn_node_storage_capacity_bytes
2. longhorn_node_storage_usage_bytes
3. longhorn_node_storage_reservation_bytes
4. longhorn_disk_capacity_bytes
5. longhorn_disk_usage_bytes
6. longhorn_disk_reservation_bytes

However, the ```longhorn_disk_reservation_bytes``` and ```longhorn_node_reservation_bytes``` 's graphs are not present on Grafana as they are constant stats.
