### ISSUE TITLE
Add 'Disable Revision Counter' option at 'Create Volume' page.

### ISSUE THREAD

**Issue by boknowswiki** [longhorn/longhorn#1839]
Related to https://github.com/longhorn/longhorn/issues/508, we need to add an option for user to enable or disable revision counter per volume.

**Comment by boknowswiki** [comment]
@smallteeths , please let me know if there is any question. Thanks.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI image: `wangsiye/longhorn-ui:a53da78`
