### ISSUE TITLE
[BUG] Buffer I/O error on dev sda, logical block 1081344, lost sync page write

### ISSUE THREAD

**Issue by LinXiaoJian** [longhorn/longhorn#1843]
**Describe the bug**
sda, sdb, sdc is persistent storage for Kafka and ZooKeeper mounted by Longhorn
After a k3S node loses a connection to another node，I found this error in the /var/log/syslog. I'm not sure if this problem caused the node disconnect.Has anyone ever seen this happen？

**To Reproduce**
I don't really know how to reproduce it.

**Expected behavior**

**Log**
`Oct  2 12:00:24 tideswing-shanghai-rancher-04-gpu kernel: [603386.041067] print_req_error: I/O error, dev sda, sector 0

Oct  2 12:00:24 tideswing-shanghai-rancher-04-gpu kernel: [603386.046617] sd 2:0:0:1: [sda] Synchronizing SCSI cache`

`Oct  2 12:00:24 tideswing-shanghai-rancher-04-gpu kernel: [603386.223194] EXT4-fs error (device sda): ext4_wait_block_bitmap:532: comm SyncThread:1: Cannot read block bitmap - block_group = 1, block_bitmap = 1028

Oct  2 12:00:24 tideswing-shanghai-rancher-04-gpu kernel: [603386.225992] EXT4-fs error (device sda): ext4_discard_preallocations:4129: comm SyncThread:1: Error -5 reading block bitmap for 1

Oct  2 12:00:24 tideswing-shanghai-rancher-04-gpu kernel: [603386.228743] EXT4-fs error (device sda): ext4_wait_block_bitmap:532: comm SyncThread:1: Cannot read block bitmap - block_group = 1, block_bitmap = 1028

Oct  2 12:00:24 tideswing-shanghai-rancher-04-gpu kernel: [603386.232028] EXT4-fs error (device sda): ext4_discard_preallocations:4129: comm SyncThread:1: Error -5 reading block bitmap for 1`

`Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.462931] Buffer I/O error on dev sdc, logical block 1081344, lost sync page write

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.463052] Buffer I/O error on dev sda, logical block 1081344, lost sync page write

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.465460] JBD2: Error -5 detected when updating journal superblock for sdc-8.

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.467918] JBD2: Error -5 detected when updating journal superblock for sda-8.

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.470255] Aborting journal on device sdc-8.

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.472609] Aborting journal on device sda-8.

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.472630] Buffer I/O error on dev sda, logical block 1081344, lost sync page write

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.474847] Buffer I/O error on dev sdc, logical block 1081344, lost sync page write

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.477104] JBD2: Error -5 detected when updating journal superblock for sda-8.

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.479339] JBD2: Error -5 detected when updating journal superblock for sdc-8.`

`Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.462931] Buffer I/O error on dev sdc, logical block 1081344, lost sync page write

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.463052] Buffer I/O error on dev sda, logical block 1081344, lost sync page write

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.465460] JBD2: Error -5 detected when updating journal superblock for sdc-8.

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.467918] JBD2: Error -5 detected when updating journal superblock for sda-8.

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.470255] Aborting journal on device sdc-8.

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.472609] Aborting journal on device sda-8.

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.472630] Buffer I/O error on dev sda, logical block 1081344, lost sync page write

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.474847] Buffer I/O error on dev sdc, logical block 1081344, lost sync page write

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.477104] JBD2: Error -5 detected when updating journal superblock for sda-8.

Oct  2 12:00:31 tideswing-shanghai-rancher-04-gpu kernel: [603393.479339] JBD2: Error -5 detected when updating journal superblock for sdc-8.`

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: v1.18.4+k3s1
 - Node OS type and version:

**Additional context**

**Comment by yasker** [comment]
What you saw here is likely caused by the node disconnection. 

How many replicas does the volume have? Is there a replica local to the node?

**Comment by LinXiaoJian** [comment]
I set up four replicas because I had four servers @yasker

**Comment by yasker** [comment]
Can you send us a support bundle at longhorn-support-bundle@rancher.com ? Ideally this log shouldn't happen. This is an indication that some writes timed out on the block level and but the retry seems succeed. We want to check the log to make sure it works according to the design.

**Comment by LinXiaoJian** [comment]
what is support bundle ? I'm not sure what I'm going to offer @yasker

**Comment by yasker** [comment]
Check the UI footer, there is a link to `Generate Support Bundle`.

**Comment by LinXiaoJian** [comment]
I have sent the document to Longhorn-support-bundle@rancher.com. In addition, I found the problem in the GPU server, I don't know if it is related to the server type. @yasker

**Comment by yasker** [comment]
From the log, server `rancher-04-gpu` was disconnected when the error happened. So this error is likely due to the engine disconnected from replicas instead of replica failures. In the case of the engine failure, it would be restarted soon but there might be error in the dmesg. It shouldn't impact the data integrity though.

From the log, I also saw lots of replica failures, as well as some call trace seems due to Kubernetes or kernel decide to kill the processes. It has put lots of stress on the Longhorn system. Can you check if you have enough CPU and bandwidth in the system? It's better if you can keep the CPU utilization on the node always below 80%, otherwise, it can impact Longhorn and Kubernetes.

**Comment by LinXiaoJian** [comment]
In general, I will guarantee that the server's CPU is under 50%.  Thank you for your answer. I'll  thinking about whether something else is causing the problem.

**Comment by derekyle** [comment]
I am getting this same error. I just sent my support bundle to Longhorn-support-bundle@rancher.com as well.

**Comment by jriosRedStripe** [comment]
@LinXiaoJian we have the same proble, How do you fixed?

**Comment by derekyle** [comment]
No, I ended up migrating off longhorn completely and started using local
disk. I'm my case, I didn't need most of the longhorn functionality since
I'm running a single node.

**Comment by derekbit** [comment]
> @LinXiaoJian we have the same proble, How do you fixed?

Can you provide
- support bundle
- kuberenetes version
- longhorn version
- dmesg of each worker node
- steps to reproduce if possible
for further investigation? Thank you.
