### ISSUE TITLE
[BUG] UI - Display the error message on the volume page for backup creation failure.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1846]
**Describe the bug**
There is no error message on the volume page if backup creation fails because of the backup deletion is in progress.

**To Reproduce**
1. Create a volume in longhorn and write some data around 300 MB into it.
2. Take a backup of the volume, say b1
3. Write more data into the volume 100 MB.
4. Delete the already created backup b1 and immediately create a new backup.
5. The screen shows no error.

**Expected behavior**
The volume screen should show the error message ```Unable to create the backup as a backup deletion on the same volume is in progress.```

**Environment:**
 - Longhorn version: Longhon Master - 10/02/2020
 - Kubernetes version: v18.8
 - Node OS type and version: Ubuntu 18.04

**Additional context:**
Once https://github.com/longhorn/longhorn/issues/1845 is resolved, The API response info can be used to implement this.

**Comment by yasker** [comment]
Assign the backend part of change to @joshimoo

**Comment by khushboo-rancher** [comment]
After the 500 API response, The UI automatically handled the error and displayed the error message. So closing this now. We're tracking the enhancement of error messages on the volume details page. https://github.com/longhorn/longhorn/issues/1386

<img width="1168" alt="Screen Shot 2020-10-06 at 12 12 15 PM" src="https://user-images.githubusercontent.com/60111667/95793636-e2881c80-0c9a-11eb-8926-09d660ac65e3.png">
