### ISSUE TITLE
[FEATURE] View RWX Volumes on Dashboard.

### ISSUE THREAD

**Issue by Trackhe** [longhorn/longhorn#1849]
I use https://longhorn.io/docs/1.0.2/advanced-resources/rwx-workloads/#enabling-rwx-support for RWX volumes. But i cant see the Volumes in Longhorn Dashboard. I guess the problem is that the nfs.longhorn.io driver dosnt do it.

**Comment by yasker** [comment]
Currently the RWX volume is not shown directly in the UI, since they're using the same volume across the board.

In the upcoming v1.1.0, we will provide an enhanced experience that can create volumes as RWX and manage it through the Longhorn UI.

**Comment by joshimoo** [comment]
related longhorn/longhorn#1470

**Comment by joshimoo** [comment]
leaving a note here.
For we added an accessMode field to the volume api object
https://github.com/longhorn/longhorn/issues/2048

which can be used by the frontend to differentiate between rwo/rwx volumes

**Comment by khushboo-rancher** [comment]
@Trackhe This feature has been released as part of Longhorn v1.1.0. You can refer https://longhorn.io/docs/1.1.0/advanced-resources/rwx-workloads/ to try it out and you should be able to view RWX volumes on Longhorn UI.

**Comment by Trackhe** [comment]
i saw this. thank you all.
