### ISSUE TITLE
Need to fix ticker leaking in instance manager

### ISSUE THREAD

**Issue by boknowswiki** [longhorn/longhorn#1854]
Missing defer ticker.Stop()  here:
https://github.com/longhorn/longhorn-instancemanager/blob/2695cf9b07a72df0168e62b35ac5c909ba8374e7/pkg/process/healthchecker.go#L22-L24

**Comment by yasker** [comment]
Done. We will need to release an instance manager during RC1.

**Comment by yasker** [comment]
Keep this open until we release the new IM.

**Comment by yasker** [comment]
`longhornio/longhorn-instance-manager:v1_20201021` is now available.

cc @boknowswiki

**Comment by yasker** [comment]
Instance manager `v1_20201021` has been released and updated across the repos.
