### ISSUE TITLE
[FEATURE] nodeSelector on Helm Chart

### ISSUE THREAD

**Issue by mfbrj** [longhorn/longhorn#1855]
**Is your feature request related to a problem? Please describe.**
Currently is not possible to configure nodeSelector on Longhorn Helm Chart.

**Describe the solution you'd like**
User could select a simple configuration such as `nodeSelector: key=value` in values.yml or form. Then the configuration would be applied to non-daemonset workloads (`csi-attacher` , `csi-provisioner` , `csi-resizer` , `longhorn-ui`, etc).

**Describe alternatives you've considered**

**Additional context**

**Comment by jenting** [comment]
We support the nodeSelector on issue #2199 already, start from Longhorn v1.1.1 https://longhorn.io/docs/1.1.1/advanced-resources/deploy/node-selector/

For user deployed components (e.g, Manager, Driver Deployer, UI), the user could configure https://github.com/longhorn/charts/blob/longhorn-1.1.1/charts/longhorn/values.yaml#L120, https://github.com/longhorn/charts/blob/longhorn-1.1.1/charts/longhorn/values.yaml#L135, and https://github.com/longhorn/charts/blob/longhorn-1.1.1/charts/longhorn/values.yaml#L150

For system-managed components (e.g, Instance Manager, Engine Image, CSI Driver, etc.), the user could configure https://github.com/longhorn/charts/blob/longhorn-1.1.1/charts/longhorn/values.yaml#L85

cc @innobead
