### ISSUE TITLE
Recurring jobs should only take backup/snapshot when volume has new data since the last backup/snapshot

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#1858]
**Is your feature request related to a problem? Please describe.**
In the current implementation, when doing recurring jobs (snapshot/backup), Longhorn doesn't check whether volume has new data before doing the job.
This might overwrite the old backups/snapshots with identical backups/many empty snapshots when the volume doesn't new data for a long time.

**Describe the solution you'd like**
Recurring jobs should only take backup/snapshot when the volume has new data since the last backup/snapshot

**Additional context**
related to issues:
longhorn/longhorn#1509
longhorn/longhorn#1354

**Comment by PhanLe1010** [comment]
**Test steps:**

1. Create a new volume and manually attach it to a node using Longhorn UI
1. Create a recurring backup job that runs every minute
1. Verify that no backup/snapshot is created because the volume is empty
1. Manually take a snapshot
1. Verify that the next time the recurring job run, it creates a new backup (because the last snapshot is not backuped yet)
1. Wait for 3 minutes, verify that no more backup is created
1. Write some data to the volume
1. Verify that the next time the recurring job run, it creates a new backup (because the volume-head has new data)
1. Wait for 3 minutes, verify that no more backup is created

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master - 10/12/2020

Validation - **Failed**

The recurring backup job starts taking the snapshot in below scenario.
1. Create a volume, attach it to a pod.
2. Enable recurring backup per minute and recurring snapshot per 2 minutes with retain count as 20.
3. The recurring backup is generating snapshots even though there is no data in the volume.

**Logs**
[longhorn-support-bundle_e36d4e37-35bf-44bf-aacd-5ad846580354_2020-10-13T00-01-31Z.zip](https://github.com/longhorn/longhorn/files/5368157/longhorn-support-bundle_e36d4e37-35bf-44bf-aacd-5ad846580354_2020-10-13T00-01-31Z.zip)

**Comment by khushboo-rancher** [comment]
Verified with longhorn master - 10/13/2020

Validation - **Pass**

The recurring jobs for snapshot only get triggers if there is a modification in the volume data (addition/deletion/modification).
The recurring jobs for backup get triggers if there is a modification in the volume data (addition/deletion/modification) from the last snapshot whose backup was taken.

Validated with below scenarios:
1. The volume has initially no data after attaching the to pod. - One backup gets created by the recurring job.
2. Take a snapshot manually before the recurring job of snapshot or backup is triggered - Backup gets created but no snapshot is created by the recurring job.
3. Validated the reverting to a previous snapshot.
4. Validated with detached volume - no snapshot/backup is taken.
5. Validated with multiple recurring jobs of backups. - If recurring job are scheduled at same time, two parallel backup gets created.
