### ISSUE TITLE
[FEATURE] PV Encryption

### ISSUE THREAD

**Issue by braghettos** [longhorn/longhorn#1859]
**Is your feature request related to a problem? Please describe.**
I would like to understand if on Longhorn roadmap the persistent volume encryption will be provided. 

**Describe the solution you'd like**
Possibility to decide when a persistent volume should be encrypted.

**Describe alternatives you've considered**
Other alternatives are Portworx: https://docs.portworx.com/key-management/kubernetes-secrets/pvc-encryption-using-storageclass/

**Additional context**
Same as previous: https://docs.portworx.com/key-management/kubernetes-secrets/pvc-encryption-using-storageclass/

**Comment by yasker** [comment]
Once we implemented this, backup encryption should be covered as well.

**Comment by innobead** [comment]
@joshimoo moving to `analsysis`, it seems you are starting working on it at the design phase.

**Comment by yasker** [comment]
@joshimoo do we plan any UI for this? E.g. does volume has a new field indicate it's encrypted? We won't want to format an encrypted volume by accident.

**Comment by joshimoo** [comment]
@yasker @innobead @smallteeths The volume has a boolean flag of Secure which can be used to differentiate between encrypted / not encrypted volumes. I am envisioning a Lock Icon on the volume details page.

We also need the addition of a `Secure` toggle and an input box to specify the secret for creation of a PVC/PV combination for restored or manually created volumes. An alternative to this is to allow for specifying a storage class instead. Then we can retrieve the values from the specified storage class instead.
![image](https://user-images.githubusercontent.com/1287163/127825113-a71aff74-5682-4c9b-a614-1bb9f0b02d96.png)

**Comment by joshimoo** [comment]
I am working on the RWX support for encrypted volumes as well as the above mentioned change to PVC/PV creation to allow for restoration of an encrypted volume.

**Comment by yasker** [comment]
Should we call it `Encrypted` instead of `Secure`? The word `secure` has many meanings. It can be encrypted or access-controlled or virus scanned.

**Comment by yasker** [comment]
And if we need UI, don't cross out the `UI` part in the checklist.

**Comment by noahsbwilliams** [comment]
I agree with @yasker on the terminology, `Encrypted` is unambiguous and objective.

**Comment by joshimoo** [comment]
@yasker I had crossed out the UI since area/ui wasn't marked by reflex :)
I am fine with using `Encrypted` I think portworx used Secure so I figured might be easier for users if we use similiar nomenclature.
But I also preferred the Encrypted verbiage and went back and forth on it.

**Comment by yasker** [comment]
Sounds good. Let's use `Encrypted` then.

**Comment by joshimoo** [comment]
@longhorn/qa wait with testing for https://github.com/longhorn/longhorn-manager/pull/976 being merged, since we change the field name to `Encrypted`.

**Comment by younesehb** [comment]
Hi guys, thanks for the hard work. Is encryption with Luks an existing feature now ? It's quite urgent for a client in the banking field.

**Comment by joshimoo** [comment]
@younesehb yes it will be available when v1.2 is released

**Comment by meldafrawi** [comment]
Validation: **In Progress**

Setup:
1. Create a kubernetes cluster with 3 worker nodes, and 1 controller node.
2. Deploy Longhorn (master branch)
3. Create a secret to be used for encryption: Ref: [secret-crypto-global.yaml](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml)

Test(1): Deploy workload using Encrypted PV with **ext4** filesystem. **(PASSED)**
1. Create a Longhorn volume, and mark check `Encrypted`: true
2. Create a PV/PVC, and set `Secret Namespace` and `Secret Name` values as specified in [secret-crypto-global.yaml](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml) and check `File System`: ext4
3. Deploy a workload using the created PVC.
4. Check read/write operation into the volume.
5. write some data and compute it's checksum

Test(2/1): ext4: Create and restore a backup from Encrypted volume   **(PASSED)**
> Set Encrypted: false in restore options

1. Create a backup from volume created in Test(1), and wait for backup to complete.
2. Restore the created backup, set `Encrypted`: False
3. Attach the restored volume to a node.
4. Decrypt the volume using `cryptsetup luksOpen /dev/longhorn/<VOLUME_NAME> <DEVICE_MAPPER_NAME>` 
5. Mount the the volume to a directory using 
`mount /dev/mapper/<DEVICE_MAPPER_NAME> <MOUNT_DIR>`
6. Check data checksum

Test(2/2): ext4: Create and restore a backup from Encrypted volume   **(PASSED)**
> Set Encrypted: true in restore options
1. Create a backup from volume created in Test(1), and wait for backup to complete.
2. Restore the created backup, set `Encrypted`: False
3. Create PV/PVC and set `Secret Namespace` and `Secret Name` values as specified in [secret-crypto-global.yaml](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml) and check `File System`: ext4
3. Deploy a workload that consume the created PVC
6. Check data checksum

Test(3/1): ext4: Create DR volume from an Encrypted volume  **(PASSED)**
> Attach the activate DR volume directly to a node

1. Create a DR volume from the backup created in Test(1).
2. Write some more data to the volume and create another backup.
3. Activate DR volume.
4. Attach the activated DR volume to a node.
5. Decrypt the volume using `cryptsetup luksOpen /dev/longhorn/<VOLUME_NAME> <DEVICE_MAPPER_NAME>` 
6. Mount the the volume to a directory using 
`mount /dev/mapper/<DEVICE_MAPPER_NAME> <MOUNT_DIR>`
7. Check data checksum


Test(3/2): ext4: Create DR volume from an Encrypted volume  **(FAILED)**
> Attach the activate DR volume to a workload.

1. Create another DR volume from the backup created in Test(1).
2. Write some more data to the volume and create another backup.
3. Activate DR volume.
4. Create PV/PVC, `Filesystem`: ext4
3. Deploy a workload that consume the created PVC
>   Warning  FailedMount             1s (x4 over 5s)  kubelet                  MountVolume.MountDevice failed for volume "new-volume-01-dr-02" : rpc error: code = Internal desc = failed to mount the volume as "ext4", it already contains crypto_LUKS. Mount error: mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/longhorn/new-volume-01-dr-02 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/new-volume-01-dr-02/globalmount
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/new-volume-01-dr-02/globalmount: wrong fs type, bad option, bad superblock on /dev/longhorn/new-volume-01-dr-02, missing codepage or helper program, or other error.

6. Check data checksum

Test(4): Deploy workload using Encrypted PV with **xfs** filesystem. **(PASSED)**
1. Create a Longhorn volume, and mark check `Encrypted`: true
2. Create a PV/PVC, and set `Secret Namespace` and `Secret Name` values as specified in [secret-crypto-global.yaml](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml) and check `File System`: xfs
3. Deploy a workload using the created PVC.
4. Check read/write operation into the volume.
5. write some data and compute it's checksum

Test(5/1): xfs: Create and restore a backup from Encrypted volume   **(FAILED)**
> Set Encrypted: false in restore options

1. Create a backup from volume created in Test(2), and wait for backup to complete.
2. Restore the created backup, set `Encrypted`: False
3. Attach the restored volume to a node.
4. Decrypt the volume using `cryptsetup luksOpen /dev/longhorn/<VOLUME_NAME> <DEVICE_MAPPER_NAME>` 
5. Mount the the volume to a directory using 
`mount /dev/mapper/<DEVICE_MAPPER_NAME> <MOUNT_DIR>`
> mount: /mnt: wrong fs type, bad option, bad superblock on /dev/mapper/new-volume-02-restore-01, missing codepage or helper program, or other error.
6. Check data checksum

Test(5/2): xfs: Create and restore a backup from Encrypted volume **(FAILED)**
> Set Encrypted: true in restore options
1. Create a backup from volume created in Test(4), and wait for backup to complete.
2. Restore the created backup, set `Encrypted`: False
3. Create PV/PVC and set `Secret Namespace` and `Secret Name` values as specified in [secret-crypto-global.yaml](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml) and check `File System`: ext4
3. Deploy a workload that consume the create PVC
6. Check data checksum

Test(6/1): xfs: Create DR volume from an Encrypted volume  **(FAILED)**
> Attach the activate DR volume directly to a node

1. Create a DR volume from the backup created in Test(4).
2. Write some more data to the volume and create another backup.
3. Activate DR volume.
4. Attach the activated DR volume to a node.
5. Decrypt the volume using `cryptsetup luksOpen /dev/longhorn/<VOLUME_NAME> <DEVICE_MAPPER_NAME>` 
6. Mount the the volume to a directory using 
`mount /dev/mapper/<DEVICE_MAPPER_NAME> <MOUNT_DIR>`
> mount: /mnt: wrong fs type, bad option, bad superblock on /dev/mapper/new-volume-02-dr-01, missing codepage or helper program, or other error.

7. Check data checksum


Test(3/2): xfs: Create DR volume from an Encrypted volume  **(FAILED)**
> Attach the activate DR volume to a workload.

1. Create another DR volume from the backup created in Test(4).
2. Write some more data to the volume and create another backup.
3. Activate DR volume.
4. Create PV/PVC, `Filesystem`: xfs
3. Deploy a workload that consume the created PVC
>    Warning  FailedMount             99s                  kubelet                  Unable to attach or mount volumes: unmounted volumes=[vol1], unattached volumes=[vol1 default-token-vmpff]: timed out waiting for the condition
  Warning  FailedMount             78s (x9 over 3m27s)  kubelet                  MountVolume.MountDevice failed for volume "new-volume-02-dr-02" : rpc error: code = Internal desc = failed to mount the volume as "xfs", it already contains crypto_LUKS. Mount error: mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t xfs -o defaults /dev/longhorn/new-volume-02-dr-02 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/new-volume-02-dr-02/globalmount
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/new-volume-02-dr-02/globalmount: wrong fs type, bad option, bad superblock on /dev/longhorn/new-volume-02-dr-02, missing codepage or helper program, or other error.

6. Check data checksum

**Comment by meldafrawi** [comment]
**Validation Tests (cont.)** 

Test(7): Provision a volume though creating a PVC from a storage class that support PV encryption

1. Create a storage class that support PV encryption. Ref: [crypto secret](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml) 
[storage class](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/storageclass-crypto-global.yaml)

2. use the following manifest to create a PVC and provision a volume.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-01
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-crypto-global
  volumeMode: Filesystem
```
3. Deploy a workload to consume the PVC
4. make sure you can read/write into the volume.

Test(8): Expand volume in Test(7)
1. Scale down the workload, wait for volume to be detached
2. Expand the volume one more time to 10 GB.
3. Wait for Expansion to complete.
4. Scale up the workload, and check volume size, and make sure you can write 10 GB into the volume.

**Comment by meldafrawi** [comment]
Update: Test(6/1): xfs: Create DR volume from an Encrypted volume **(PASSED)**, Ref: https://github.com/longhorn/longhorn/issues/2906

**Comment by meldafrawi** [comment]
Expansion Validation **PASSED**, Thanks @joshimoo

**Comment by meldafrawi** [comment]
**LGTM**
