### ISSUE TITLE
[QUESTION] Backup S3 - DigitalOcean - Spaces

### ISSUE THREAD

**Issue by bemanuel** [longhorn/longhorn#1869]
Trying to use Backup over S3 on Space, after put endpoint, secret and etc... on the Backup tab gives an error, for some reason the system is complementing with AWS address.
I put an address s3://bucket@nyc3.digitaloceanspaces.com/node/longhorn/store
And On log error print e.g:
**"https://bucket.s3.nyc3.digitaloceanspaces.com.amazonaws.com/"**
After tried 3 times, because I thought that was a typo error, the system caused overhead on the cluster.

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: 1.18.9
 - Node OS type and version: k3s+Ubuntu 20.04 - v1.18.9+k3s1

**Additional context**

**Comment by joshimoo** [comment]
@bemanuel could you attach a support bundle? What do you mean with the system caused overhead on the cluster?

**Comment by yasker** [comment]
@bemanuel The setting seems wrong. Have you checked https://longhorn.io/docs/1.0.2/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-a-local-testing-backupstore ?

**Comment by bemanuel** [comment]
> @bemanuel could you attach a support bundle? What do you mean with the system caused overhead on the cluster?

I think that was a coincidence. The process didn't happen again.

**Comment by bemanuel** [comment]
> @bemanuel The setting seems wrong. Have you checked https://longhorn.io/docs/1.0.2/snapshots-and-backups/backup-and-restore/set-backup-target, especially https://longhorn.io/docs/1.0.2/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-a-local-testing-backupstore ? Setup a third party backupstore is similar to that, so it's unlikely you can use `s3://bucket@nyc3.digitaloceanspaces.com`. The URL needs to be set in the AWS_ENDPOINTS instead.
I changed according to it.
Secret:
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: <base64key>
  AWS_ENDPOINTS: <base64key-end> # nyc3.digitaloceanspaces.com
  AWS_SECRET_ACCESS_KEY: <base64key-ack>
kind: Secret
  name: s3-secret
  namespace: longhorn-system

On Backup Setttings:
Backup Target: s3://bucket@nyc3/
Backup Target Credential Secret: s3-secret

Error:
error listing backups: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.0.2/longhorn [backup ls --volume-only s3://bucket@nyc3/], output failed to list objects with param: { Bucket: "bucket", Delimiter: "/", Prefix: "/" } response: { } error: AWS Error: RequestError send request failed Get https://<endpoint_enc64>/bucket?delimiter=%!F(MISSING)&prefix=%!F(MISSING): dial tcp: lookup <endpoint_enc64> on 10.43.0.10:53: no such host , stderr, time="2020-10-09T19:43:50Z" level=error msg="Fail to list s3: failed to list objects with param: {\n Bucket: \"bucket\",\n Delimiter: \"/\",\n Prefix: \"/\"\n} response: {\n\n} error: AWS Error: RequestError send request failed Get https://<endpoint_enc64>/bucket?delimiter=%!F

**Comment by yasker** [comment]
According to https://www.digitalocean.com/docs/spaces/resources/s3-sdk-examples/ , you need to set the region to `us-east-1`, e.g. `s3://bucket@us-east-1/`

**Comment by virus2016** [comment]
I have Digitalocean spaces working perfectly in my Longhorn instance.

In my secret I have 'minio-secret'

AWS_ENDPOINTS: [REGION].digitaloceanspaces.com
AWS_ACCESS_KEY_ID: xxxxx
AWS_SECRET_ACCESS_KEY: xxxxx

Longhorn settings:

Backup Target: s3://[DO-SPACENAME]@[REGION]/longhorn-backup
Backup Target Credential Secret: minio-secret

Hope this helps

**Comment by bemanuel** [comment]
I had used endpoint and keys over base64 according to https://longhorn.io/docs/1.0.2/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-a-local-testing-backupstore after switch to clear text the backup works

**Comment by joshimoo** [comment]
@bemanuel thanks for the update, I am closing the issue as solved then.
