### ISSUE TITLE
[FEATURE]: Volume list view should display volume actual size

### ISSUE THREAD

**Issue by courcelm** [longhorn/longhorn#1870]
**Is your feature request related to a problem? Please describe.**
Volumes can occupy considerably more disk space then expected because of snapshots and unexpected large data writes. We currently need to check individual volume to spot excessive disk usage.

**Describe the solution you'd like**
Add volume actual size in the volume list view.

**Comment by yasker** [comment]
We've added this feature for the upcoming v1.1.0 release https://github.com/longhorn/longhorn/issues/1716 .

See https://github.com/longhorn/longhorn/issues/1716#issuecomment-686061520

**Comment by courcelm** [comment]
Great!
