### ISSUE TITLE
[Question] daemonset.apps/longhorn-manager can't start

### ISSUE THREAD

**Issue by xlliu** [longhorn/longhorn#1872]
Name:           longhorn-manager
Selector:       app=longhorn-manager
Node-Selector:  <none>
Labels:         app=longhorn-manager
                app.kubernetes.io/instance=longhorn
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=longhorn
                app.kubernetes.io/version=v1.0.2
                helm.sh/chart=longhorn-1.0.2
Annotations:    deprecated.daemonset.template.generation: 1
                meta.helm.sh/release-name: longhorn
                meta.helm.sh/release-namespace: longhorn-system
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=longhorn-manager
                    app.kubernetes.io/instance=longhorn
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=longhorn
                    app.kubernetes.io/version=v1.0.2
                    helm.sh/chart=longhorn-1.0.2
  Service Account:  longhorn-service-account
  Containers:
   longhorn-manager:
    Image:      longhornio/longhorn-manager:v1.0.2
    Port:       9500/TCP
    Host Port:  0/TCP
    Command:
      longhorn-manager
      -d
      daemon
      --engine-image
      longhornio/longhorn-engine:v1.0.2
      --instance-manager-image
      longhornio/longhorn-instance-manager:v1_20200514
      --manager-image
      longhornio/longhorn-manager:v1.0.2
      --service-account
      longhorn-service-account
    Readiness:  tcp-socket :9500 delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAMESPACE:          (v1:metadata.namespace)
      POD_IP:                 (v1:status.podIP)
      NODE_NAME:              (v1:spec.nodeName)
      DEFAULT_SETTING_PATH:  /var/lib/longhorn-setting/default-setting.yaml
    Mounts:
      /host/dev/ from dev (rw)
      /host/proc/ from proc (rw)
      /var/lib/longhorn-setting/ from longhorn-default-setting (rw)
      /var/lib/longhorn/ from longhorn (rw)
      /var/run/ from varrun (rw)
  Volumes:
   dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/
    HostPathType:
   proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc/
    HostPathType:
   varrun:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/
    HostPathType:
   longhorn:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/longhorn/
    HostPathType:
   longhorn-default-setting:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      longhorn-default-setting
    Optional:  false
Events:        <none>

**Comment by xlliu** [comment]
I delete all pod from namespace of longhorn-system, i find manage pod of daemonset can't created. find some things, longhorn can't work

**Comment by yasker** [comment]
@xlliu I am not sure what's the reproduce steps or your environment involved above. If you're trying to uninstall Longhorn, you can follow the instruction [here](https://longhorn.io/docs/1.0.2/deploy/uninstall/) instead of removing all the pods manually in the `longhorn-system` namespace.

Also, once you reinstalled the system, check `longhorn-manager`'s log might help to find out the error behind longhorn-manager cannot start.
