### ISSUE TITLE
[Question] volume status shows degraded

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1873]
volume status shows degraded

how to fix it?

State: attached
Health: degraded
Ready for workload:Ready
Conditions:
restore
scheduled
Frontend:Block Device
Attached Node & Endpoint:
node4
/dev/longhorn/pvc-00a54279-a491-4c7f-a59d-daa8edbb7c42
Size:
50 Gi
Actual Size:42.3 Gi
Base Image:
Engine Image:longhornio/longhorn-engine:v1.0.2
Created:2 months ago
Node Tags:
Disk Tags:
Last Backup:backup-2668bfd991174783

**Comment by yasker** [comment]
It should be fixed automatically by Longhorn if your cluster has enough space to create another replica for the volume. Otherwise, you would see a `scheduling failure` error which means Longhorn cannot find enough space.
