### ISSUE TITLE
[BUG] Some taint tolerations can not be set, but Longhorn should run on all nodes

### ISSUE THREAD

**Issue by aspettl** [longhorn/longhorn#1874]
**Describe the bug**
It is not possible to set all possible taint tolerations. Note that tools like RKE set taints, e.g. `node-role.kubernetes.io/etcd=true:NoExecute` or `node-role.kubernetes.io/controlplane=true:NoSchedule`.
The description in the Longhorn UI says

> Because kubernetes.io is used as the key of all Kubernetes default tolerations, it should not be used in the toleration settings.

This suggests that such tolerations can be set - but in fact, it is not allowed at all. And my understanding from other bug reports is that Longhorn should be deployed on all nodes (see e.g. https://github.com/longhorn/longhorn/issues/1633#issuecomment-702967887) because a pod using a Longhorn volume could be deployed anywhere (and have special tolerations). Imho this is contradictory.

**To Reproduce**
1. Go to the Longhorn UI
2. Set a toleration like `node-role.kubernetes.io/controlplane=true:NoSchedule`, try to save changes
3. Validation fails with
> fail to set settings with invalid taint-toleration: value node-role.kubernetes.io/controlplane=true:NoSchedule of settings taint-toleration is invalid: the value of taint-toleration is invalid: the key of Longhorn toleration setting cannot contain "kubernetes.io" since this substring is considered as the key of Kubernetes default tolerations

**Expected behavior**
* allow taint toleration for all taints that can exist
* also allow wildcard tolerations - see https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#concepts ("There are two special cases" box)
* (potentially) improve description in Longhorn UI

**Log**

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: 1.18.9
 - Node OS type and version: Ubuntu 18.04

**Additional context**
See https://github.com/longhorn/longhorn-manager/blob/55c8453c22b0f47da54bb6922e0ac97c37154b75/upgrade/v1alpha1/types/setting.go#L439 (validation rule and code for parsing)

**Comment by yasker** [comment]
cc @shuo-wu

**Comment by shuo-wu** [comment]
OK. It seems that all tolerations should be allowed in Longhorn. But we need to be careful of removing the tolerations.

**Comment by yasker** [comment]
In fact, the workload shouldn't be deployed when `node-role.kubernetes.io/controlplane=true:NoSchedule` is set. Only the worker nodes which can run workload needs to install Longhorn. We don't need to install Longhorn on control/etcd nodes. So we don't expect the user to set those taint tolerations.

**Comment by aspettl** [comment]
Just because it is not normal to run a workload there, does not mean that there is no use-case for it ;-)
So I'm for giving the user the possibility to do it. A warning in the tolerations description is sufficient imho.

(Context why I even looked at this, a bit off-topic: I had the problem twice that even a local volume bind (!) with a local-storage storage class did not work on a node with a taint. In the kubelet logs of this node I found an error that no connection to longhorn was possible. That's why I wanted to add this node to Longhorn. But this is fairly recent, I did not see this problem before. And even when I had the problem, it magically disappeared after a few hours... Maybe it is connected to an k8s upgrade (1.18.9). I need to observe and investigate and create an extra bug for this if necessary.)

**Comment by yasker** [comment]
I remember we set the limitation due to we have some potential issues with removing taint like `kubernetes.io` but I cannot recall the detail now. @shuo-wu might remember more about the topic.

**Comment by lbogdan** [comment]
My use-case: in a `kubeadm` bootstrapped dev cluster, I want to use control plane nodes as storage nodes, too.

Current workaround: add `node-role.kubernetes.io/master=:NoSchedule` to `longhorn-manager` DaemonSet **and**, after things are started, add the same toleration to the `engine-image-ei-abcd1234` DaemonSet, which I guess is created by `longhorn-manager`.

**Comment by yasker** [comment]
Ping @shuo-wu . What's the reason we didn't allow taint with suffix like `kubernetes.io`?

**Comment by shuo-wu** [comment]
@yasker 
In the current implementation, there is no way to identify which tolerations of Longhorn workloads are added by Longhorn. Then we just consider all tolerations are set the Longhorn. But Kubernetes will add some tolerations (containing `kubernetes.io` ) by default, hence these kind of tolerations are considered as exceptions.

**Comment by yasker** [comment]
OK, it seems we can partly solve this problem by adding one more annotation regarding which toleration is added by Longhorn. Though if both Longhorn and Kubernetes add the same toleration, then we might still accidentally remove it. I guess that would be fine for now.

**Comment by aspettl** [comment]
Sounds good. And I would even call that intended behavior that it is possible to override/change a default toleration.

**Comment by PhanLe1010** [comment]
**Test Steps:**
1. Go to the Longhorn UI
1. Set a toleration like `node-role.kubernetes.io/controlplane=true:NoSchedule`, try to save changes
1. Verify that Longhorn applies the toleration to components. 
1. Manually add `test.kubernetes.io/test=true:NoSchedule` to any deployment/daemonset in Longhorn system.
1. Go to the Longhorn UI
1. Set a toleration like `key1:val1=true:NoSchedule`, try to save changes
1. Verify that Longhorn applies `key1:val1=true:NoSchedule` and removes `node-role.kubernetes.io/controlplane=true:NoSchedule` toleration to/from components. 
1. Verify that Longhorn does not remove `test.kubernetes.io/test=true:NoSchedule` toleration
1. Try adding invalid toleration  `key1=val1:Effect` in Longhorn UI
1. Verify that cannot update the setting 
1. Try adding special toleration  `:` in Longhorn UI
1. Verify that daemonsets in the Longhorn system are deployed on every node (including controller/etcd nodes)

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master `11/26/2020`

Validation - **Passed**

Validated the test cases from https://github.com/longhorn/longhorn/issues/1874#issuecomment-729242290 and additional test cases for deletion of toleration with same key and different value.

**Comment by khushboo-rancher** [comment]
@PhanLe1010 @yasker While upgrading the longhorn (having toleration) from v1.0.2 to master, the below intermittent issue is observed.

The longhorn manager pods initially fail with error crashloop and then recover after sometime. Is it something that we can overlook?
```
time="2020-11-28T07:39:24Z" level=info msg="Start overwriting built-in settings with customized values"
W1128 07:39:24.948114       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2020-11-28T07:39:24Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: Failed to execute: nsenter [--mount=/host/proc/19196/ns/mnt --net=/host/proc/19196/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr, ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/*': No such file or directory\n, error exit status 2"
I1128 07:39:24.964600       1 leaderelection.go:241] attempting to acquire leader lease  longhorn-system/longhorn-manager-upgrade-lock...
I1128 07:39:24.992407       1 leaderelection.go:251] successfully acquired lease longhorn-system/longhorn-manager-upgrade-lock
time="2020-11-28T07:39:24Z" level=info msg="Start upgrading"
time="2020-11-28T07:39:25Z" level=info msg="No API version upgrade is needed"
time="2020-11-28T07:39:25Z" level=error msg="Upgrade failed: upgrade Pods failed: upgrade from v1.0.2 to v1.1.0: upgrade instance manager pods failed: failed to update toleration annotation for instance manager pod instance-manager-r-f0a4823d: Operation cannot be fulfilled on pods \"instance-manager-r-f0a4823d\": the object has been modified; please apply your changes to the latest version and try again"
time="2020-11-28T07:39:25Z" level=info msg="Upgrade leader lost: khush-test-lh-wk2"
time="2020-11-28T07:39:25Z" level=fatal msg="Error starting manager: upgrade Pods failed: upgrade from v1.0.2 to v1.1.0: upgrade instance manager pods failed: failed to update toleration annotation for instance manager pod instance-manager-r-f0a4823d: Operation cannot be fulfilled on pods \"instance-manager-r-f0a4823d\": the object has been modified; please apply your changes to the latest version and try again"
```

**Comment by yasker** [comment]
@PhanLe1010 Not sure why the upgrade process can fail due to conflict (since there should be only one manager at the time of upgrade). Can you look into it?
