### ISSUE TITLE
[BUG] Recurring backup job stuck if interrupted by powering down the node

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1882]
**Describe the bug**
The job for backup stuck forever if the attached node to the volume is power down for sometimes.

**To Reproduce**
1. Create a volume, attach to a pod.
2. Enable recurring backup job for every 5 mins.
3. Write 1 GB to the data.
4. Scale down the pod.
5. When the scheduled recurring job attaches the volume to a node (Auto attach to node). Power down the node where the volume is attached.
6. Once the longhorn UI start showing the 'power down' icon for volume. Power it on.
7. The job stuck in running state forever and volume continues to be attached to the node.

**Expected behavior**
There should retry to complete the backup or time out for the failure.

**Log**
```
time="2020-10-14T22:10:57Z" level=info msg="Automatically attach volume volume-test-2 to node khush-test-lh-wk2"
time="2020-10-14T22:11:00Z" level=info msg="Volume volume-test-2 is in state attached"
time="2020-10-14T22:11:00Z" level=info msg="Running recurring backup for volume volume-test-2"
time="2020-10-14T22:11:08Z" level=debug msg="Creating backup , current progress 1"
time="2020-10-14T22:11:13Z" level=debug msg="Creating backup , current progress 1"
```
[longhorn-support-bundle_500d104c-4b30-4a34-9d25-cd191662eb8e_2020-10-14T22-30-21Z.zip](https://github.com/longhorn/longhorn/files/5381377/longhorn-support-bundle_500d104c-4b30-4a34-9d25-cd191662eb8e_2020-10-14T22-30-21Z.zip)
Volume name - volume-test-2
Time - "2020-10-14T22:15:13Z 

**Environment:**
 - Longhorn version: longhorn-master 10/13/2020
 - Kubernetes version: 1.18.9
 - Node OS type and version: ubuntu 18.04

**Additional Context**
If only the job is triggered on another node from the volume is attached to, this issue is reproducible.

**Comment by yasker** [comment]
@khushboo-rancher can you check if it's the same if the volume is already attached and working, then the node down happens during recurring backup in progress?

**Comment by khushboo-rancher** [comment]
In the case of the volume attached to a pod, I observed the recurring job always got scheduled on the same node as the volume attached to. So when the node went down, the job became an unknown state and then failed. The next backup worked fine if the pod moved to another node or after I powered on the node.

I tried node scheduling in rancher for the recurring job, seems like it didn't work.

**Comment by yasker** [comment]
In fact we're removing the associated node ID for the pod #1796 . So it will be a problem once we removed the node limitation.

**Comment by PhanLe1010** [comment]
### Reproduce:

**Case 1: Volume is using by workload pod**

1. Write 1GB to the volume 
1. Create a recurring backup job that runs every 3 mins
1. Wait until the recurring backup job start (check its log), kill engine manager pod of the volume's engine.
1. The recurring backup job stuck running start forever. No future recurring job is run in the future.

**Case 1: Volume is in detached state**
1. Write 1GB to the volume 
1. Detach the volume
1. Create a recurring backup job that runs every 3 mins
1. Wait until the recurring backup job start (check its log), kill the engine manager pod of the volume's engine.
1. The recurring backup job stuck running start forever **and** volume remains to attach to the wrong node which prevents any workload from using it.

**Comment by PhanLe1010** [comment]
### Manual Test Steps:

**Case 1: Volume is using by workload pod**

1. Write 1GB to the volume 
1. Create a recurring backup job that runs every 3 mins
1. Wait until the recurring backup job start (check its log), kill the engine manager pod of the volume's engine.
1. Verify the recurring backup job is canceled and the next time it runs, everything goes back to normal. 

**Case 1: Volume is in detached state**
1. Write 1GB to the volume 
1. Detach the volume
1. Create a recurring backup job that runs every 3 mins
1. Wait until the recurring backup job start (check its log), kill the engine manager pod of the volume's engine.
1. Verify the recurring backup job is canceled **but** the volume remains to attach to the wrong node which prevents any workload from using it.

**Comment by PhanLe1010** [comment]
We created a sperate issue (https://github.com/longhorn/longhorn/issues/1922) for the auto reattachment problem mentioned in **case 2** in [the manual test plan](https://github.com/longhorn/longhorn/issues/1882#issuecomment-718288354)

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master 11/02/2020

Validation - Scenario 1 worked. In case of scenarios 2 and 3, the cron job stuck.

Below scenarios are tested.
**Sceanrio-1** - Node is powered down and powered on later.
1. Enable ```Allow Recurring Job While Volume Is Detached```. 
2. Attach a volume to pod of a statefulSet, write data into it and set a recurring backup.
3. Detach from the pod by scaling down the statefulSet.
4. The attached node to volume is power down when the recurring job backup was in progress.
5. The recurring job remains in running state.
6. The node is switched on.
7. The corn job becomes unavailable and a new job got created which completes the backup successfully.
8. Verified the data by restoring the backup.

**Sceanrio-2** - Node is powered down and remains powered down.
1. Enable ```Allow Recurring Job While Volume Is Detached```
2. Attach a volume to pod of a statefulSet, write data into it and set a recurring backup.
3. Detach from the pod by scaling down the statefulSet.
4. The attached node to volume is power down when the recurring job backup was in progress.
5. **The recurring job stucks in running state with the same progress.**

**Sceanrio-2** - Node is powered down and volume detached manually.
1. Enable ```Allow Recurring Job While Volume Is Detached```
2. Attach a volume to pod of a statefulSet, write data into it and set a recurring backup.
3. Detach from the pod by scaling down the statefulSet.
4. The attached node to volume is power down when the recurring job backup was in progress.
5. The volume is manually detached.
6. **The recurring job stucks in running state with the same progress.**

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master - 11/06/2020

Validation - **Pass**

The below scenarios are tested.
**Scenario 1**- ```Allow Recurring Job While Volume Is Detached``` disabled, pod detached, node powered down.
1. Create a volume, attach to a pod, and write 800 Mi data into it.
2. Set a recurring job. Scale down the pod to 0.
3. **No auto attachment is observed**

**Scenario 2**- ```Allow Recurring Job While Volume Is Detached``` disabled, pod attached, node powered down.
1. Create a volume, attach to a pod, and write 800 Mi data into it.
2. Set a recurring job.
3. While the recurring job is in progress, scale down the pod to 0
4. Volume first detached and cron job gets completed saying unable to complete the backup.
5. **Volume again gets auto attached to another node and cron job gets recreated.**
6. After backup completion, the volume gets detached.

**Scenario 3**- ```Allow Recurring Job While Volume Is Detached``` enabled, pod attached, node powered down.
1. Enable ```Allow Recurring Job While Volume Is Detached```
1. Create a volume, attach to a pod, and write 800 Mi data into it.
2. Set a recurring job.
3. While the recurring job is in progress, scale down the pod to 0
4. Volume first detached and cron job gets completed saying unable to complete the backup.
5. **Volume again gets auto attached to another node and cron job gets recreated.**
6. After backup completion, the volume gets detached.

**Sceanrio-4** - Cron job and volume attached to same node, Node is powered down and volume detached manually.
1. Enable ```Allow Recurring Job While Volume Is Detached```
2. Attach a volume to pod of a statefulSet, write data into it and set a recurring backup.
3. Detach from the pod by scaling down the statefulSet.
4. The attached node to volume is power down when the recurring job backup was in progress.
5. The volume is manually detached while the cron job remains in unknown state.
6. **The cron remains in unknown state for about 7 mins and then another pod gets created**
7. Volume get attached to another node and once the job is completed, volume gets detached.

**Sceanrio-5** - Cron job and volume attached to different node, Node is powered down. **(Reported scenario)**
1. Enable ```Allow Recurring Job While Volume Is Detached```
2. Attach a volume to pod of a statefulSet, write data into it and set a recurring backup.
3. Detach from the pod by scaling down the statefulSet.
4. The attached node to volume is power down when the recurring job backup was in progress.
5. **Another cron job pod gets created with logs in the previous pod as below**
```
time="2020-11-09T07:39:10Z" level=info msg="Automatically attach volume volume-test-2 to node node-1"
time="2020-11-09T07:39:12Z" level=info msg="Volume volume-test-2 is in state attached"
time="2020-11-09T07:39:12Z" level=info msg="Running recurring backup for volume volume-test-2"
time="2020-11-09T07:39:22Z" level=debug msg="Creating backup , current progress 0"
time="2020-11-09T07:39:27Z" level=debug msg="Creating backup , current progress 4"
time="2020-11-09T07:39:32Z" level=debug msg="Creating backup , current progress 6"
time="2020-11-09T07:39:37Z" level=debug msg="Creating backup , current progress 8"
time="2020-11-09T07:39:42Z" level=debug msg="Creating backup , current progress 10"
time="2020-11-09T07:39:47Z" level=debug msg="Creating backup , current progress 11"
time="2020-11-09T07:39:52Z" level=debug msg="Creating backup , current progress 11"
time="2020-11-09T07:39:57Z" level=debug msg="Creating backup , current progress 11"
time="2020-11-09T07:40:02Z" level=debug msg="Creating backup , current progress 11"
time="2020-11-09T07:40:07Z" level=debug msg="Creating backup , current progress 11"
time="2020-11-09T07:40:12Z" level=debug msg="Creating backup , current progress 11"
time="2020-11-09T07:40:17Z" level=debug msg="Creating backup , current progress 11"
time="2020-11-09T07:40:22Z" level=debug msg="Creating backup , current progress 11"
time="2020-11-09T07:40:27Z" level=debug msg="Creating backup , current progress 11"
time="2020-11-09T07:40:32Z" level=debug msg="Creating backup , current progress 11"
time="2020-11-09T07:40:37Z" level=debug msg="Creating backup , current progress 11"
time="2020-11-09T07:40:42Z" level=info msg="Automatically detach the volume volume-test-2"
```
6. Volume get attached to another node and once the job is completed, volume gets detached.
