### ISSUE TITLE
Increase Longhorn's requirement for Kubernetes to version v1.16+

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#1883]
In Longhorn v1.1.0, we use Pod Disruption Budgets feature which is in beta since Kubernetes v1.15+. 

Therefore, we need to update Longhorn's document to increase Longhorn's requirement for Kubernetes to version v1.15+.

**Comment by yasker** [comment]
We need to increase it to v1.16 since we're using appextension v1 instead of v1beta API for CRDs.

**Comment by yasker** [comment]
Release note and chart minimal version have been updated to v1.16.
