### ISSUE TITLE
[BUG] Error in uninstall job logs

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1884]
**Describe the bug**
There is an error in longhorn-uninstall job logs

**To Reproduce**
1. Deploy longhorn master on a cluster(1etcd/control plane, 3 workers)
2. Uninstall longhorn using kubectl command
3. Check the uninstall logs.
```
E1016 00:13:51.662332 1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:default:longhorn-uninstall-service-account" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
E1016 00:13:52.672968 1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:default:longhorn-uninstall-service-account" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
```

**Environment:**
 - Longhorn version: Longhorn-master - 10/15/2020
 - Kubernetes version: v1.18.9
 - Node OS type and version: ubuntu 18.04

**Comment by PhanLe1010** [comment]
Thanks @khushboo-rancher 

will push PR in a moment

**Comment by khushboo-rancher** [comment]
Verified with the master - 10/16/2020

Validation - **Pass**

There is no error observed in the logs of uninstallation job.
