### ISSUE TITLE
task: Create a repo to generate multi-arch MinIO image

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1887]
MinIO already built images for different architectures like ARM64, but it doesn't publish it as a multi-arch image.

We can track and build multi-arch images for MinIO, and publish it as `longhorn/minio`, since we need MinIO in our testing.

We would want to keep the same tag as the original release tag.

Background: https://github.com/minio/minio/issues/9546#issuecomment-710713041

Code repo: https://github.com/longhorn/minio-multiarch-image

MinIO docker images: https://hub.docker.com/r/minio/minio/tags

**Comment by yasker** [comment]
Done.

**Comment by harshavardhana** [comment]
> Background: [minio/minio#9546 (comment)](https://github.com/minio/minio/issues/9546#issuecomment-710713041)

The latest release now has support for multiarch manifests

**Comment by yasker** [comment]
Thanks @harshavardhana . That's a great update.

@meldafrawi Can we switch to use the official MinIO images? Once we verify it works well, we can mark https://github.com/longhorn/minio-multiarch-image as obsolete.
