### ISSUE TITLE
[BUG] Error starting manager: failed to wait for engine image

### ISSUE THREAD

**Issue by wanyaoqi** [longhorn/longhorn#1888]
**Describe the bug**
Restart one of node, longhorn-manger start failed. 
engine image already running, kubectl log engine-image no output.

And if delete all of the pod in longhorn-system, longhorn-manager can start success

**To Reproduce**
Restart one of node

**Expected behavior**
longhorn manager start success

**Log**
If applicable, add the Longhorn managers' log when the issue happens.
![image](https://user-images.githubusercontent.com/18528551/96399043-f209e700-11ff-11eb-8ed5-cc23ed6e1592.png)

**Environment:**
 - Longhorn version: 1.0
 - Kubernetes version: v1.15.9
 - Node OS type and version: centos7 

**Additional context**

**Comment by wanyaoqi** [comment]
Ref: https://github.com/longhorn/longhorn/issues/1764
@shuo-wu Do you have any ideas

**Comment by shuo-wu** [comment]
Is the related `engineimages.longhorn.io` object ready? 

You can check:
    1. If the binary file `/data/longhorn` exists in engine image pods.
    2. Use `kubectl -n longhorn-system get engineimages.longhorn.io` to check if the engine image object is state ready.

If NO, then you need to check why the command of engine image pods is not executed successfully.

**Comment by yasker** [comment]
Hi @wanyaoqi 

Any update? I saw you close the issue.

**Comment by wanyaoqi** [comment]
@yasker 
No, I have not met this problem again. 
I will reopen this issue if I run into this problem again. 
Thanks
