### ISSUE TITLE
[Question] Setting the reclaim policy to 'retain' and reusing the persistent volume using longhorn

### ISSUE THREAD

**Issue by sankarshvittal** [longhorn/longhorn#1892]
Hello,

My use case involves:

- Installing longhorn using the helm chart and changing the default values in the values.yaml file as needed

- On deleting a pod and the corresponding pvc, and later recreating it, I would want the pod to be attached to the same PV as before created by longhorn.

So, in the helm chart values.yaml file I cannot see an option to change the reclaim policy to 'retain' from its default value of delete. Is there a way to accomplish this?

Is there an approach using longhorn to accomplish reusing of the same PV as created before?

**Comment by yasker** [comment]
There is a PR for that https://github.com/longhorn/longhorn/pull/1827 and we will release it with v1.1.0.

Also, you can try to create another storage class with the reclaim policy `Retain`.

**Comment by sankarshvittal** [comment]
Hi @yasker, thanks for sharing the information!
