### ISSUE TITLE
[Question] Migrate k8s nodes with Longhorn on a different network

### ISSUE THREAD

**Issue by mrcdb** [longhorn/longhorn#1897]
Hi guys, I have a question regarding migration of k8s nodes among different subnets in a VPC. Some of the workloads in the nodes include Longhorn volumes (with variable replica count, from no replica at all to 3).

I've read from best practices that is better to deploy k8s nodes on the new subnet, attach them to the cluster and later drain the previous ones in the old subnet so that you don't need to change names / IP addresses of the existing nodes at all. That's fine to me, but what about Longhorn volumes? Are they going to be migrated alongside with the workloads once I start draining existing nodes?

Thanks!

**Comment by yasker** [comment]
Sounds like you are decommissioning the old nodes. For v1.0.x, it will take a few steps to move replicas from the node to another node. You can follow the steps at https://github.com/longhorn/longhorn/issues/1400#issuecomment-633723863 to move the replicas to your new nodes.

In the upcoming v1.1.0 release, we will have #298 feature ready which can help to evict the replicas from a disk or node.

**Comment by mrcdb** [comment]
Hi @yasker, thanks for the clarification. Will I be able to leverage the eviction feature if I update my longhorn engine once the 1.1.0 release is available?

**Comment by yasker** [comment]
Yes. Eviction will be available in v1.1.0 release.
