### ISSUE TITLE
[QUESTION] Unable to use storage from my custom storageclass

### ISSUE THREAD

**Issue by windowsrefund** [longhorn/longhorn#1898]
I've applied the following against my clean 4 node K3S system and am attaching a support bundle.

https://paste.ubuntu.com/p/pqZ9M2xrXh/

**Expected behavior**
I expect the longhorn-simple-pod pod to mount a 1G volume on /data

**Log**
`Warning  FailedAttachVolume  80s (x21 over 38m)    attachdetach-controller  AttachVolume.Attach failed for volume "pvc-4afdbf3e-18b1-4af5-aaeb-1a905d4f4f95" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to attach volume pvc-4afdbf3e-18b1-4af5-aaeb-1a905d4f4f95 to k3s-node3: volume pvc-4afdbf3e-18b1-4af5-aaeb-1a905d4f4f95 not scheduled] from [http://longhorn-backend:9500/v1/volumes/pvc-4afdbf3e-18b1-4af5-aaeb-1a905d4f4f95?action=attach]

**Environment:**
 - Longhorn version: 1.02
 - Kubernetes version: 1.18.9+k3s1
 - Node OS type and version: CentOS 7.7 with all updates applied

**Additional context**
3 worker nodes: k3s-node1, k3s-node2, and k3s-node3
Only node1 and node2 have an extra disk attached. These nodes have a node label of "media" and the added disk has a disk label of "data" (added through the UI). These 2 disks are the basis for the longhorn-media storageclass

[longhorn-support-bundle_ad6ad0e5-a489-47a0-b5c7-095bcce1e170_2020-10-21T13-23-52Z.zip](https://github.com/longhorn/longhorn/files/5416351/longhorn-support-bundle_ad6ad0e5-a489-47a0-b5c7-095bcce1e170_2020-10-21T13-23-52Z.zip)

**Comment by joshimoo** [comment]
Worked with the user in slack, the issue is that his added disks were not enabled for scheduling.
