### ISSUE TITLE
[BUG] Missed deletion events crash the longhorn-manager

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#1900]
**Describe the bug**
If an informer misses a deletion event, the final state of the object
will be unknown and instead the event will be a marker object of type 
`cache.DeletedFinalStateUnknown` with a sub Obj that contains the last 
cached state.

Previously we didn't handle the cache.DeletedFinalStateUnkown object and instead always used a [type assertion](https://golang.org/ref/spec#Type_assertions) for the corresponding longhorn object.

related: https://github.com/longhorn/longhorn/issues/1877

**Comment by yasker** [comment]
Done.

Close the issue since there isn't a good way for us to validate this. If there is any side effects, we should know it from the log.
