### ISSUE TITLE
[BUG] Delete node is not required on longhorn UI

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1901]
**Describe the bug**
The option delete node/remove node is not required on the longhorn node page after https://github.com/longhorn/longhorn-manager/pull/692

**To Reproduce**
1. Go to the Longhorn node page, the delete node button and remove node option should be removed.
<img width="810" alt="Screen Shot 2020-10-21 at 2 53 04 PM" src="https://user-images.githubusercontent.com/60111667/96793437-41dbe000-13b1-11eb-9a54-a8b7d0ebd235.png">
<img width="1756" alt="Screen Shot 2020-10-21 at 2 53 18 PM" src="https://user-images.githubusercontent.com/60111667/96793441-430d0d00-13b1-11eb-915a-47e0abdd4eb9.png">

**Environment:**
 - Longhorn version: Longhorn-master

**Comment by shuo-wu** [comment]
Agree. It seems the manual node deletion is meaningless now.

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master - bb53c5f

Validation - **Pass**

The delete node button is not present on the node page.
