### ISSUE TITLE
Update Helm chart templates for Longhorn v1.1.0

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#1906]
We need to update Helm chart templates for Longhorn v1.1.0

**Comment by meldafrawi** [comment]
@PhanLe1010 
Chart version is still not updated

https://github.com/longhorn/longhorn/blob/v1.1.0/chart/Chart.yaml#L3

**Comment by meldafrawi** [comment]
LGTM, except for Chart version update

**Comment by yasker** [comment]
The chart version will be updated during the release process, so it's fine to leave it there.
