### ISSUE TITLE
[BUG] RWX PVC from NFS-provisioned SC is mounted with incorrect capacity

### ISSUE THREAD

**Issue by maxweisspoker** [longhorn/longhorn#1908]
**Describe the bug**
RWX PVC's created from the NFS provisioner are incorrectly mounted with the capacity of the underlying RWO PVC which the NFS provisioner uses as its underlying storage. (As opposed to the capacity requested in the RWX PVC.) This is wrong in its own right, but also allows a bug where attempting to write more than the available RWO PVC storage causes an unkown deadlock until the NFS StorageClass, the RWO PVC, and any NFS-PVC-backed resources are all deleted. Presumably this would not happen in the RWX-PVC was mounted with the correct capacity and thus blocked from writing more than that.

**To Reproduce**
1. Install Longhorn on K8s.
2. Install the *01-security.yaml* and *02-longhorn-nfs-provisioner.yaml* examples from [this guide](https://longhorn.io/docs/1.0.2/advanced-resources/rwx-workloads/) on getting RWX pvc's using NFS. The second-to-last object in the *02-longhorn-nfs-provisioner.yaml* is a PVC which serves as the (RWO) backing storage for the StorageClass which is the last item in the file.
3. Next, create a new RWX PVC using the aforementioned StorageClass and set the PVC requested capacity to some fraction of the available storage.
4. Then create a pod (or multiple pods) which mount that new RWX PVC. Then exec into the pod(s) and run "df -h" to see the various storages, and you'll see that the NFS-attached storage mount provided by the new PVC has a "Size" of the original RWO-backing PVC, rather than the capacity of the new PVC.
5. Example:  I make a PVC utilizing the StorageClass "longhorn-nfs" and set its capacity to 10Gi. When mounted in a pod, the size shown by "df -h" is 20Gi, which is the size of the PVC named "longhorn-nfs-provisioner" (in the 02-longhorn-nfs-provisioner.yaml file). I can write 15Gi worth of data without error, even though the capacity should be 10Gi. If I write more than 20Gi of data, the mount becomes read-only on all pods, the Longhorn nfs-provisioner pod goes into a crash loop, and the 20Gi backing PVC shows in the web UI as continually being detached and reattached. If I attempt to delete the pods using the NFS PVC, or the RWX PVC itself, those resources get stuck in a terminating state. Only when I delete the StorageClass and 20Gi PVC do the other resources finalize and terminate cleanly. (Also worth noting, I deleted the PVC by deleting the volume in the web UI because kubectl hung when I tried to delete the PVC, and I was unable to diagnose what was causing the deadlock. But when I deleted the volume in the web UI, everything else finally terminated.)

**Expected behavior**
The NFS-SC-backed PVC should be mounted with the capacity listed in the PVC.

**Log**
I'm sorry I closed my terminal on accident and lost all the logs. If nobody can reproduce my error, I will happily re-create it and get any requested log files.

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: 1.19.3
 - Node OS type and version: Arch Linux (1 master and 5 worker nodes) provisioned via Vagrant on a local VirtualBox. Longhorn disks are separate block devices from secondary vmdk disks, formatted to ext4 and mounted on boot at /var/lib/longhorn, but the Arch OS filesystem is btrfs. Master and workers all provisioned with kubeadm + Docker.

**Additional context**
I believe I have provided all necessary context. But if anybody wants more specific information, let me know and I will provide it.

**Comment by yasker** [comment]
@maxweisspoker Thanks for the reporting. We're currently on the native RWX support (see #1470) and will support create the exact amount of space specified for RWX in the v1.1.0 release.

**Comment by maxweisspoker** [comment]
Closing this issue because it sounds like this is resolved in 1.1.0.  Thanks for the help!
