### ISSUE TITLE
Single replica failure, some I/O error show from the app which used longhron 

### ISSUE THREAD

**Issue by keanlee** [longhorn/longhorn#1910]
hello, I facing some `Caused by: java.nio.file.FileSystemException: /bitnami/elasticsearch/data/nodes/0/indices: Input/output error` and `Caused by: java.nio.file.FileSystemException: /bitnami/elasticsearch/data/nodes/0/_state: Read-only file system` from some application which used longhorn. Nothing error found form the longhorn UI.
![image](https://user-images.githubusercontent.com/17561861/97154835-623fdc00-17af-11eb-9d02-c38104a70902.png)error from longhorn manger pods

**Comment by keanlee** [comment]
I didn't found the pvc block in the target host by command `lsblk` 
![image](https://user-images.githubusercontent.com/17561861/97155099-ccf11780-17af-11eb-84e4-9a396bccafec.png)

**Comment by joshimoo** [comment]
Please attach a support bundle, from the screenshot it looks like your single replica failed.

**Comment by joshimoo** [comment]
Support bundle here: https://slack-files.com/T3AU9F5MG-F01D437MV9U-61880a356b

**Comment by yasker** [comment]
@keanlee Does scale down and back up the workload help?

**Comment by yasker** [comment]
@keanlee which volume is having the problem? I saw different volumes name in the issue and I can not find `pvc-315dc813-xxx` anymore.

Regarding the block device, you should able to see the block device exposed by Longhorn in the UI.

**Comment by keanlee** [comment]
@yasker   Thanks for your reply.  We disable the PVC and create it again. so it's disappeared. our rancher monitor and elk both has some I/O error when use longhorn.  after destroy and create it again. we didn't reproduce it again. so I guess we need to keep watching for the issue.

**Comment by keanlee** [comment]
![image](https://user-images.githubusercontent.com/17561861/98666088-7c6ce300-2387-11eb-9305-53d13cc6978a.png)
update some system logs

**Comment by keanlee** [comment]
`time="2020-11-10T09:34:34Z" level=debug msg="Requeue longhorn-system/rancher-box-ops-02 due to conflict: Operation cannot be fulfilled on nodes.longhorn.io \"rancher-box-ops-02\": the object has been modified; please apply your changes to the latest version and try again`

**Comment by keanlee** [comment]
https://rancher-users.slack.com/files/U017H5GKQQ0/F01EL2JGVT6/longhorn-support-bundle_15bccd1d-1e5b-40cc-a387-51aaa85bd28d_2020-11-10t11-09-02z.zip @joshimoo

**Comment by yasker** [comment]
@keanlee In the log, I saw the volume `pvc-8c7c2ef7-7c0f-4be4-aea9-b9e8ab70f57b-e-1999d77b` failed due to unable to connect to the replica on `10.42.10.136:10000`. However, I cannot find the instance manager running on that address, at least at the time of support bundle generation. For now, you can scale down and scale back the workload to workaround it. The disconnection can be caused by Longhorn from being CPU starved or lost connection to the replica. You might want to monitor your CPU and network.

**Comment by keanlee** [comment]
`stance-manager] time="2020-11-12T02:08:08Z" level=info msg="wait for process pvc-4d69656f-ce6b-423e-aab3-59ba1a8a0c41-e-0695d377 to shutdown"

[pvc-4d69656f-ce6b-423e-aab3-59ba1a8a0c41-e-0695d377] time="2020-11-12T02:08:08Z" level=info msg="Shutdown SCSI target iqn.2019-10.io.longhorn:pvc-4d69656f-ce6b-423e-aab3-59ba1a8a0c41"

[longhorn-instance-manager] time="2020-11-12T02:08:08Z" level=debug msg="Process Manager: wait for process pvc-4d69656f-ce6b-423e-aab3-59ba1a8a0c41-e-0695d377 to shutdown before unregistering process"

lh_client_close_conn: Closing connection

lh_client_close_conn: Connection close complete

[pvc-4d69656f-ce6b-423e-aab3-59ba1a8a0c41-e-0695d377] time="2020-11-12T02:08:08Z" level=warning msg="Socket server connection closed"

time="2020-11-12T02:08:08Z" level=info msg="device pvc-4d69656f-ce6b-423e-aab3-59ba1a8a0c41: SCSI device /dev/longhorn/pvc-4d69656f-ce6b-423e-aab3-59ba1a8a0c41 shutdown"

time="2020-11-12T02:08:08Z" level=info msg="Closing: 10.42.3.54:10060"

[longhorn-instance-manager] time="2020-11-12T02:08:08Z" level=info msg="Process Manager: process pvc-4d69656f-ce6b-423e-aab3-59ba1a8a0c41-e-0695d377 stopped"

[longhorn-instance-manager] time="2020-11-12T02:08:08Z" level=info msg="Process Manager: successfully unregistered process pvc-4d69656f-ce6b-423e-aab3-59ba1a8a0c41-e-0695d377"`
