### ISSUE TITLE
[FEATURE] Create a backup automatically on CSI snapshot creation

### ISSUE THREAD

**Issue by mamiu** [longhorn/longhorn#1913]
**Is your feature request related to a problem? Please describe.**
Since CSI snapshot support is coming soon (https://github.com/longhorn/longhorn/issues/304#issuecomment-688977090) and third party Kubernetes backup tools like [Velero](https://github.com/vmware-tanzu/velero) do already [support](https://velero.io/docs/v1.5/csi/) CSI snapshots, it would be nice to have an additional option to create a backup on CSI snapshots creation in addition to the [recurring jobs](https://longhorn.io/docs/1.0.0/snapshots-and-backups/scheduling-backups-and-snapshots/#set-up-recurring-jobs-using-a-storageclass) option.

**Describe the solution you'd like**
Add a `backupOnCSISnapshot` option to let third party tools like Velero not just create snapshots but backups as well. Thus the entire backup process is managed from a single tool and the backed up Kubernetes resources are in sync with the PV storage backups.

**Describe alternatives you've considered**
The alternative would be to have the same cron expression for [Velero](https://velero.io/docs/v1.5/api-types/schedule/#definition) and [longhorn](https://longhorn.io/docs/1.0.0/snapshots-and-backups/scheduling-backups-and-snapshots/#set-up-recurring-jobs-using-a-storageclass) but this could lead to out of sync backups anyway.

**Comment by yasker** [comment]
CSI Snapshot is Longhorn's backup, not Longhorn snapshot. So it's already done. See design doc at https://github.com/longhorn/longhorn/blob/master/enhancements/20200904-csi-snapshot-support.md

**Comment by mamiu** [comment]
Thanks @yasker! Didn't know that. Looking forward to the upcoming release. 😊
