### ISSUE TITLE
[Question] Unable to attach volumes after upgrading Kubernetes cluster from 1.16 to 1.17

### ISSUE THREAD

**Issue by kevinsulatra** [longhorn/longhorn#1915]
After upgrading the Kubernetes cluster from 1.16 to 1.17, workloads are unable to attached thier Longhorn volumes. 

Example error
```
Events:
  Type     Reason              Age                From                     Message
  ----     ------              ----               ----                     -------
  Normal   Scheduled           34s                default-scheduler        Successfully assigned monitoring/elasticsearch-master-0 to ip-x.x.x.x
  Warning  FailedAttachVolume  30s (x2 over 33s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-218c9328-4421-4683-ac9f-04f18a3297db" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=unable to attach volume pvc-218c9328-4421-4683-ac9f-04f18a3297db to ip-x.x.x.x: Node to be attached ip-x.x.x.x is different from previous spec ip-x.x.x.x, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes/pvc-218c9328-4421-4683-ac9f-04f18a3297db?action=attach]
  Warning  FailedAttachVolume  2s (x4 over 34s)   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-218c9328-4421-4683-ac9f-04f18a3297db" : rpc error: code = Internal desc = Action [attach] not available on [&{pvc-218c9328-4421-4683-ac9f-04f18a3297db volume map[self:http://longhorn-backend:9500/v1/volumes/pvc-218c9328-4421-4683-ac9f-04f18a3297db] map[salvage:http://longhorn-backend:9500/v1/volumes/pvc-218c9328-4421-4683-ac9f-04f18a3297db?action=salvage]}]
```

Longhorn Version
`v1.0.2`

Actions taken

- Scale down statefulset to 0
- Upgrade k8s to 1.17
- Scale up the statefulset so that volumes will attach again

**Comment by yasker** [comment]
@kevinsulatra Can you check the `longhorn-manager` log on the attaching node? If the statefulset was scaled down before the upgrade, I am not sure why the multi-attach error happened.

**Comment by kevinsulatra** [comment]
Example logs from the `longhorn-manager` from the attaching node. 

```
time="2020-10-28T08:53:08Z" level=error msg="Error in request: unable to attach volume pvc-4fde9502-9506-47c0-b1a7-5ed94ad68d8c to ip-x.x.x.x: Node to be attached ip-x.x.x.x is different from previous spec ip-x.x.x.x"
100.71.131.20 - - [28/Oct/2020:08:53:08 +0000] "POST /v1/volumes/pvc-4fde9502-9506-47c0-b1a7-5ed94ad68d8c?action=attach HTTP/1.1" 500 442 "" "Go-http-client/1.1"
100.71.131.20 - - [28/Oct/2020:08:54:12 +0000] "GET /v1/volumes/pvc-4fde9502-9506-47c0-b1a7-5ed94ad68d8c HTTP/1.1" 200 3206 "" "Go-http-client/1.1"
100.71.131.20 - - [28/Oct/2020:08:54:12 +0000] "GET /v1/nodes/ip-x.x.x.x HTTP/1.1" 200 996 "" "Go-http-client/1.1"
100.71.131.20 - - [28/Oct/2020:08:56:20 +0000] "GET /v1/volumes/pvc-4fde9502-9506-47c0-b1a7-5ed94ad68d8c HTTP/1.1" 200 3206 "" "Go-http-client/1.1"
100.71.131.20 - - [28/Oct/2020:08:56:20 +0000] "GET /v1/nodes/ip-x.x.x.x HTTP/1.1" 200 996 "" "Go-http-client/1.1"
```

I also added a step before upgrading the cluster:

- Scale down statefulset to 0
- Cordon Longhorn nodes
- Upgrade k8s to 1.17
- Scale up the statefulset to 1

**Comment by yasker** [comment]
@kevinsulatra somehow this volume was specified to attach to node `ip-x.x.x.x` (`previous spec` one). I don't know if there is a node name change or something else, but can you try:
1. scale down the statefulset to 0
2. check Longhorn UI, make sure the volume is detached.
3. Scale up the statefulset to 1.

**Comment by drewhemm** [comment]
Hi @yasker, we tried the scale down and up to no avail. We are able to migrate volumes to other nodes just fine where there is not a Kubernetes version change, but as soon as we upgrade the cluster, we start to get this error.

**Comment by yasker** [comment]
@drewhemm After you scale down the deployment, make sure to check the Longhorn UI to ensure the volume is `detached`.

If it still doesn't work, I suspect some environment variables have changed. Try to redeploy the CSI driver as below:

1. Scale down the `driver deployer`
    ```
    kubectl -n longhorn-system scale --replicas 0 deployment/longhorn-driver-deployer
    ```
2. Remove the existing deployments in the `longhorn-system` namespace that including the word with `csi`, e.g `csi-attacher`, `csi-provisioner`, `csi-resizer` and `longhorn-csi-plugins`. Make sure they're gone before continue.
    ```
    kubectl -n longhorn-system delete deployment csi-attacher csi-provisioner csi-resizer
    kubectl -n longhorn-system delete daemonset longhorn-csi-plugins
    ```
3. Scale back `driver-deployer` to 1
    ```
    kubectl -n longhorn-system scale --replicas 0 deployment/longhorn-driver-deployer
    ```
