### ISSUE TITLE
Longhorn startup status

### ISSUE THREAD

**Issue by ws-way** [longhorn/longhorn#1919]
Hello,

Is there a way to check if Longhorn is completely up and running after an install with Helm?

Thanks!

**Comment by ws-way** [comment]
Found a script at https://raw.githubusercontent.com/rancher/longhorn/master/scripts/environment_check.sh

**Comment by yasker** [comment]
@ws-way The environment check is used for checking the environment dependencies. You can tell if Longhorn is up and running by looking at pods inside `longhorn-system`. It should look like how it's shown in our document, e.g. with Helm https://longhorn.io/docs/1.0.2/deploy/install/install-with-helm/

**Comment by ws-way** [comment]
> @ws-way The environment check is used for checking the environment dependencies. You can tell if Longhorn is up and running by looking at pods inside `longhorn-system`. It should look like how it's shown in our document, e.g. with Helm https://longhorn.io/docs/1.0.2/deploy/install/install-with-helm/

Thanks for the answer, but in the shell script there is also code to check if Longhorn is ready.
