### ISSUE TITLE
Volume remains to attach to the wrong node when recurring backup job fails during the auto attachment 

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#1922]
**Describe the bug**
While the volume is auto-attached to a node by a recurring backup job, if the volume is crashed unexpectedly, the recurring job is stopped. However, the recurring job will fail to detach the volume. After that, Longhorn automatically re-attaches the volume onto the `wrong` node and the volume remains attaching to the `wrong` node forever. This prevent the workload from using the volume and user would have to manually detach the volume.

**To Reproduce:**
1. Create a volume, attach to a pod of a deployment.
1. Write 1GB to the volume 
1. Scale down the deployment. The volume is detached.
1. Turn on `Allow Recurring Job While Volume Is Detached` in UI setting
1. Create a recurring backup job that runs every 3 mins
1. Wait until the recurring backup job start (check its log), kill the engine manager pod of the volume's engine.
1. Verify the recurring backup job is canceled **but** the volume remains to attach to the wrong node which prevents any workload from using it.

**Expected behavior**
Volume should stay in detached state and ready for workload

**Additional context**
Always reproducible

**Comment by meldafrawi** [comment]
Validation: **PASSED**

**Comment by yasker** [comment]
It's unlikely we have time for writing the automation test for this issue in v1.1.0. Let's do a regression test and then punt it to v1.1.1 release.

**Comment by meldafrawi** [comment]
integration test passed
