### ISSUE TITLE
[BUG] Error logs in longhorn-uninstall job

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1925]
**Describe the bug**
There are error logs appearing in longhorn-uninstall job.

**To Reproduce**
1. Deploy longhorn-master in a cluster of 3 worker nodes.
2. Once the deployment is successful, uninstall the longhorn using https://github.com/longhorn/longhorn-manager/blob/master/deploy/uninstall/uninstall.yaml
3. The longhorn-uninstall job gets created.
4. Check the logs, there are errors.

**Expected behavior**
There should not be any error logs in uninstall job.

**Log**
```
E1029 07:15:31.442278       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:default:longhorn-uninstall-service-account" cannot list resource "configmaps" in API group "" at the cluster scope
E1029 07:15:32.444893       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:default:longhorn-uninstall-service-account" cannot list resource "configmaps" in API group "" at the cluster scope
```

**Environment:**
 - Longhorn version: Longhorn-master - 10/29/2020

**Comment by PhanLe1010** [comment]
this is my bad. Will push the fix asap

**Comment by khushboo-rancher** [comment]
Validated with longhorn-master - 10/29/2020

Validation - **Pass**

There is no error observed now in the longhorn-uninstall job
