### ISSUE TITLE
[Question] csi-attacher, csi-provisioner and csi-resizer not running on all nodes

### ISSUE THREAD

**Issue by rsoika** [longhorn/longhorn#1928]
I have a Kubernetes cluster consisting of 4 worker nodes running longhorn 1.0.2

all longhorn components are distributed to every of my 4 worker nodes exept the 

 - csi-attacher
 - csi-provisioner
 - csi-resizer 

These containers are missing of one of the nodes. Maybe the node was installed later but I assumed that longhorn will detect new nodes automatically. In the Longhorn UI Dashbord all nodes are listed with status 'Ready' and everything seems working fine so far.

Why is this happen? Can I do something so that the csi-containers are started manually on the 4th node?

**Comment by yasker** [comment]
CSI components are running in the leader election mode. They don't need to run as a daemonset. So as long as there is one pod of those exists, it will be fine.

Also, any node down for those Pods will prompt Kubernetes to create another pod to replace it, so this shouldn't be an issue.

**Comment by rsoika** [comment]
ok thanks a lot for quick answer!
