### ISSUE TITLE
[BUG] The rebuild progress doesn't work when the failed replica is being reused

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1936]
**Describe the bug**
the rebuild progress is always 0 when the failed replica is being reused

**To Reproduce**
1. Create and attach a volume
2. Write data
3. Crash a replica
4. The rebuilding replica mode is `WO` but the rebuild progress is always 0.

**Expected behavior**
the rebuild progress should keep changing.

**Environment:**
 - Longhorn version: master
 - Kubernetes version: v1.18
 - Node OS type and version: Ubuntu 18.04

**Additional context**
The rebuild progress will be updated only when there is actual data writing. We may need to somehow update the progress during the checksum getting call:
https://github.com/longhorn/sparse-tools/blob/e548e37f91af9a7a53149b433d37d68bd7a051d7/sparse/rest/handlers.go#L190

**Comment by shuo-wu** [comment]
Do we need an extra manual test plan? I think the current failed replica reuse tests are enough. @yasker

**Comment by yasker** [comment]
@shuo-wu Yes, we don't need an extra manual test. Just make sure the progress check is there with `failed replica reuse` test. Btw, where is the manual test case for that?

**Comment by yasker** [comment]
OK, I see. Since we don't have the manual test for failed replica reuse case, we should add one and include the progress check there. It should be in the pre-release test.

**Comment by khushboo-rancher** [comment]
Verified with the longhorn master - 11/09/2020

Validation - **Pass**

The progress in case of the rebuilding using a failed replica can be seen now.
<img width="890" alt="Screen Shot 2020-11-09 at 10 49 39 PM" src="https://user-images.githubusercontent.com/60111667/98638890-92729900-22de-11eb-9a65-6b1c467484c0.png">
