### ISSUE TITLE
Upgrade K8s dependencies to  v.1.16+

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#1938]
Because we raise the minimum requirement for Longhorn v1.1.0 to Kubernetes v.1.16+, we should update K8s dependencies (client-go, Kubernetes, metric-client, etc..) to  v.1.16+.

**Comment by PhanLe1010** [comment]
**Test Steps:*
Make sure Longhorn installation and upgrade are ok.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

k8s version: v1.16

Test steps:
- Install Longhorn from master
- Install Longhorn v1.0.2, then upgrade to master.
