### ISSUE TITLE
[FEATURE] Bulk update replica count of volumes

### ISSUE THREAD

**Issue by japsu** [longhorn/longhorn#1939]
**Is your feature request related to a problem? Please describe.**

When doing node maintenance, it would be helpful to be able to reduce or increase the replica count of all volumes en masse instead of doing it manually volume by volume.

**Describe the solution you'd like**

In Longhorn UI, under Volumes, select all volumes, select "Update replica count" from toolbar, enter desired replica count.

**Describe alternatives you've considered**

Doing this via CLI is OK as well if it's clearly documented somewhere.

**Comment by yasker** [comment]
This also will be in the upcoming v1.1.0 release. See https://github.com/longhorn/longhorn/issues/1715

**Comment by yasker** [comment]
This is fixed in v1.1.0. Close the issue.
