### ISSUE TITLE
[FEATURE] When a node reboots, restore replicas on it without a full rebuild

### ISSUE THREAD

**Issue by japsu** [longhorn/longhorn#1940]
**Is your feature request related to a problem? Please describe.**

We run a K3s cluster with three nodes, each running co-located Longhorn storage with 13 volumes (going to increase in the near future to 30-40) with 3 replicas each. So each node has 13 replicas. Total data payload is in single-digit gigabytes so far, with roughly 40 gigabytes allocated (this too will increase in the near future).

If a node reboots, all 13 replicas on it get marked as "Failed". When the node is operational again, new replicas will automatically created on it for each of the 13 volumes. Soon the node will have 13 healthy replicas and 13 failed ones. Now I need to manually remove the failed replicas.

This is a traditional data center with static Ubuntu 20.04 virtual machines running on Hyper-V. Reboot of a node may take up to 10 minutes due to unknown reasons (being investigated, we want to bring the reboot time down to 1-2 min max).

**Describe the solution you'd like**

Could the failed replicas be restored incrementally, ie. without copying over all data from healthy replicas? Only copying changed data? Perhaps using snapshots?

**Describe alternatives you've considered**

We're nowhere near the storage limits of the cluster and full rebuild only takes mere minutes, so for now automatically deleting the failed replicas once new replicas are healthy would be fine, too.

**Comment by yasker** [comment]
Yes, it will be supported in the upcoming v1.1.0 release.

See #1304

**Comment by japsu** [comment]
Great, let's close this
