### ISSUE TITLE
[Question] What to expect in a network split?

### ISSUE THREAD

**Issue by japsu** [longhorn/longhorn#1941]
I'd like the documentation to provide some insight on what to expect if there is a network split, ie. some of the nodes in the cluster get isolated from the others network-wise and can continue communicating with each other but not the other partition.

Example cases:

1. A cluster of 3 nodes splits into partitions of 2 (A) and 1 (B) nodes. Partition A still has quorum so I'd expect it to continue working in degraded mode, but what happens in partition B? What happens when the split is healed and partition B joins partition A?

2. A cluster of 5 nodes splits into partitions of 2 (A), 1 (B) and 2 (C) nodes. None of the partitions have quorum. What happens during and after the split?

**Comment by yasker** [comment]
Longhorn is not running as a quorum system. So the network split is not a problem.

Longhorn engine only concerns about which replica it can talk to. Once the replica disconnected, Longhorn will treat the replica as `stale` and rebuild it based on the current connected replica once the disconnected replica connects back.

You can take a look at https://longhorn.io/docs/1.0.2/concepts/ or my video explaining how Longhorn works at https://www.youtube.com/watch?v=zJY2uxLtwUk
