### ISSUE TITLE
RemountRequestedAt sometimes is not set when all replicas fail

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#1942]
**Describe the bug**
`v.Status.RemountRequestedAt` sometimes is not set when all replicas fail

**To Reproduce**
1. Run this integration test case: https://github.com/longhorn/longhorn-tests/pull/464
1. While the test is running, run `kubectl get volumes -n longhorn-system -w`
1. Observe that `v.Status.RemountRequestedAt` sometimes is not set when all replicas fail

**Expected behavior**
`v.Status.RemountRequestedAt` must be set when all replicas fail. if `v.Status.RemountRequestedAt` is not set when all replicas fail, the workload pod is never restarted and the volume never gets remounted.  

**Environment:**
 - Longhorn manager version: https://github.com/longhorn/longhorn-manager/commit/57fe09ba118d7adb0200d5db83da238c262e4b67

**Additional context**
This is related to the issue https://github.com/longhorn/longhorn/issues/1914

**Comment by PhanLe1010** [comment]
### Root Cause:

1. When we kill all replica processes, Longhorn does auto salvage replicas and set `v.Status.RemountRequestedAt` at [here](https://github.com/longhorn/longhorn-manager/blob/d98dc6f7a662e125e7c9866c1e73ec192017788c/controller/volume_controller.go#L959) . 
1. At the end of the reconciliation loop, we update replica, engine, volume CRs in etcd [here](https://github.com/longhorn/longhorn-manager/blob/d98dc6f7a662e125e7c9866c1e73ec192017788c/controller/volume_controller.go#L332). However, sometimes it is possible that we successfully update all replicas CRs but fail to update engine or volume CRs. The result is that all replicas is salvaged but `v.Status.RemountRequestedAt` is not set. 
1. The next time, ``v.Status.RemountRequestedAt`()` run, it doesn't see any faulty replica neither error engine, therefore it skips the [salvage](https://github.com/longhorn/longhorn-manager/blob/d98dc6f7a662e125e7c9866c1e73ec192017788c/controller/volume_controller.go#L897).
1. The end result is that `v.Status.RemountRequestedAt` is never set, the workload pod is never restarted, and the volume never gets remounted.

### Why doesn't this problem happen before when we still have [the auto-remount logic](https://github.com/longhorn/longhorn-manager/blob/ba4ca64ad03911194c8586932e9f529e19c884a4/controller/volume_controller.go#L875) ?
It is because we recently introduced the modification to engine CR [here](https://github.com/longhorn/longhorn-manager/blob/d98dc6f7a662e125e7c9866c1e73ec192017788c/controller/volume_controller.go#L955). The modification to the engine CR creates more chance to have conflicts when updating engine CR at the end of the reconciliation loop. At the end of the reconciliation loop, when we update replica, then engine, then volume CRs, it is more likely that there are conflicts when updating engine CR. This creates the above problem when we successfully updated replica CRs but failed to update engine and volume CRs.

### Solution space:

#### Transactional operation
This problem is a typical example of a transactional operation in which a group of operations must be executed automatically together or abort altogether. The idea is that updating replica, engine, and volume CRs must all succeeded or must be aborted altogether. If we can make updating replica, engine, and volume CRs to be a transactional operation, the problem will be solved.  

`etcd` supports transactional operation [here](https://etcd.io/docs/v3.4.0/learning/api/). Unfortunately, [client-go](https://github.com/kubernetes/client-go/issues/630) and [Kubernetes](https://kubernetes.io/docs/reference/using-api/api-concepts/#single-resource-api) don't. 

#### Use workload pod's annotation instead of using `v.Status.RemountRequestedAt`
The idea is that we will make sure that the workload pod's annotation `longhorn.io/remountRequestedAt` is successfully persisted in `etcd` before we enter [the loop](https://github.com/longhorn/longhorn-manager/blob/d98dc6f7a662e125e7c9866c1e73ec192017788c/controller/volume_controller.go#L960) and salvage all replicas.

This method works but adding more stuff into the users' workload pod doesn't seem a clean method.

#### Allways set `v.Status.RemountRequestedAt` when the volume was faulty and there are usable healthy replicas. 

By doing this we make sure that the RemountRequestedAt is never missed. 

I think that this method is the best for this issue.

**Comment by PhanLe1010** [comment]
**Test step:**
Run the test [test_salvage_auto_crash_all_replicas](https://github.com/longhorn/longhorn-tests/blob/f8d1cebba1102a2bab365b784cfe8b5ba43b0e04/manager/integration/tests/test_ha.py#L503) and [test_volume_reattach_after_engine_sigkill](https://github.com/longhorn/longhorn-tests/blob/f8d1cebba1102a2bab365b784cfe8b5ba43b0e04/manager/integration/tests/test_ha.py#L1844) 10 times.
Verify that they always pass.

**Comment by khushboo-rancher** [comment]
Ran the tests ```test_salvage_auto_crash_all_replicas``` and ```test_volume_reattach_after_engine_sigkill``` multiple times on longhorn master, works fine. Moving to E2E merged to track results in a few nightly test run.

**Comment by PhanLe1010** [comment]
I think that we can close this issue. 
The test `test_salvage_auto_crash_all_replicas ` now fail because of a different reason that is tracked at https://github.com/longhorn/longhorn/issues/1974
