### ISSUE TITLE
[BUG]  poddisruptionbudget of non-existing IM pods are not cleaned up when Longhorn is updated

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#1944]
**Describe the bug**
We should clean up `poddisruptionbudget` to match the existing IM pods, but we didn't do that.

**To Reproduce**
1. Install Longhorn
1. Update Longhorn, change `--instance-manager-image` to a different image version
1. Observe that there are double number of `poddisruptionbudget` by running `kubectl get poddisruptionbudget -n longhorn-system`

**Expected behavior**
We should clean up `poddisruptionbudget` to match the existing IM pods

**Comment by PhanLe1010** [comment]
**Manual Tests: **
Follow the reproduce steps at https://github.com/longhorn/longhorn/issues/1944#issue-734945428
Make sure that there is no poddisruptionbudget of non-existing instance manager pod.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
