### ISSUE TITLE
[BUG] upon installation, longhorn-manager is unable to aquire longhorn-manager-upgrade-lock

### ISSUE THREAD

**Issue by uluzox** [longhorn/longhorn#1945]
**Describe the bug**
I am running on Rancher 2.4.5. Upon cluster wide installation of Longhorn 1.0.2 via the Rancher catalogue, I run in the following error. The longhorn-manager in Unavailable stating that he is unable to retrieve the longhorn-manager-upgrade-lock.

**To Reproduce**
1. Go to Catalog App
2. Install Longhorn Cluster wide and for a Project with the cluster admin with role owner as Member
3. See Logs

**Expected behavior**
Installation succeeds

**Log**
[container.log](https://github.com/longhorn/longhorn/files/5479690/container.log)

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: k3s 1.18.3
 - Node OS type and version: Ubuntu 18.04.5 LTS (Bionic Beaver)

**Additional context**
I am unable to create a Longhorn Support Bundle.

**Comment by yasker** [comment]
The error message is
```
E1103 07:11:51.608057       1 leaderelection.go:307] error retrieving resource lock longhorn-system-p-7p2nz/longhorn-manager-upgrade-lock: leases.coordination.k8s.io "longhorn-manager-upgrade-lock" is forbidden: User "system:serviceaccount:longhorn-system-p-7p2nz:longhorn-service-account" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "longhorn-system-p-7p2nz" 
```

It seems the service account doesn't have the permission to access `leases.coordination.k8s.io` resource, which is weird since the permission should be added during Longhorn installation. There is something wrong with the Kubernetes RBAC.

Can you try the following command? It will reapply the RBAC needed for Longhorn.
```
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn-manager/v1.0.2/deploy/install/01-prerequisite/02-serviceaccount.yaml
```

**Comment by uluzox** [comment]
> The error message is
> 
> ```
> E1103 07:11:51.608057       1 leaderelection.go:307] error retrieving resource lock longhorn-system-p-7p2nz/longhorn-manager-upgrade-lock: leases.coordination.k8s.io "longhorn-manager-upgrade-lock" is forbidden: User "system:serviceaccount:longhorn-system-p-7p2nz:longhorn-service-account" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "longhorn-system-p-7p2nz" 
> ```
> 
> It seems the service account doesn't have the permission to access `leases.coordination.k8s.io` resource, which is weird since the permission should be added during Longhorn installation. There is something wrong with the Kubernetes RBAC.
> 
> Can you try the following command? It will reapply the RBAC needed for Longhorn.
> 
> ```
> kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn-manager/v1.0.2/deploy/install/01-prerequisite/02-serviceaccount.yaml
> ```

This worked like a charm. Since I installed it for a certain project. My namespace is not "longhorn-system" but "longhorn-system-p-7p2nz". Thus, I had to change the namespace in the 02-serviceaccount.yaml

**Comment by yasker** [comment]
Just a note, it's not recommended to install Longhorn in other namespaces. It's might be a potential issue.

**Comment by uluzox** [comment]
I know that. However, it happens automatically when installing Longhorn cluster wide as a Catalogue App from the Rancher UI. "longhorn-system-p-7p2nz" is the namespace of the Longhorn installation for one particular project.

Are you familiar with Ranchers Catalogue App installation?

**Comment by yasker** [comment]
It must be installed as a multi-cluster app... If you install Longhorn inside the cluster, this can be worked around.

The multicluster app feature has been deprecated by Rancher and will be replaced by Fleet GitOps.
