### ISSUE TITLE
[BUG] Node & DiskStatus deepcopy functions are incorrect

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#1950]
While reviewing https://github.com/longhorn/longhorn-manager/pull/758 I noticed these two issues.

Doing the node deepcopy should call the deepcopy function for the diskStatus here:
https://github.com/longhorn/longhorn-manager/blob/master/types/deepcopy.go#L134

The `DiskStatus` deep copy does not copy the `ScheduledReplica` map.
https://github.com/longhorn/longhorn-manager/blob/master/types/resource.go#L339
https://github.com/longhorn/longhorn-manager/blob/master/types/deepcopy.go#L145

**Comment by yasker** [comment]
Those issues were to be added as a part of disk CRD. But now we're not going that way. So we should address them now.

**Comment by shuo-wu** [comment]
Not sure how to test this bug...

**Comment by yasker** [comment]
@shuo-wu Let's fine. It's more of a code bug fix. I can close it when it's merged.
