### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by lucernae** [longhorn/longhorn#1952]
Hi, I have some question about how the backup/restore works.

If I have two different cluster and longhorn in those two cluster uses the same s3 endpoint, is it possible to migrate volumes from one cluster to the other via the s3 backup?

**Comment by c3y1huang** [comment]
You can create a new longhorn volume from the backup. [Set the Backup Target](https://longhorn.io/docs/1.0.2/snapshots-and-backups/backup-and-restore/set-backup-target/) on your second cluster and [Restore from a Backup](https://longhorn.io/docs/1.0.2/snapshots-and-backups/backup-and-restore/restore-from-a-backup/).

**Comment by yasker** [comment]
You can also create a disaster recovery volume to keep it in sync with your volume in the master cluster, in case the main cluster went down. The volume in the backup cluster won't be usable until it's activated manually in the event that the main cluster is down. See https://longhorn.io/docs/1.0.2/snapshots-and-backups/setup-disaster-recovery-volumes/ and a demo of DR volume at https://www.youtube.com/watch?v=zJY2uxLtwUk

**Comment by lucernae** [comment]
Thanks for all the answers. I tried these instructions and it works really well!

The main point missing from my earlier attempt is because I need to configure the same bucket as the backup target. Since it's not possible for me to do that, I copy the backup folder into the target bucket and Longhorn can recognize that.

I also really like how painless it is to restore. A couple of click to choose the backup. Then there's option to generate the same PV/PVC using the same backup. After that, I just use the same k8s manifest to generate the service and it works straight away.

We can close the issue then.
