### ISSUE TITLE
[BUG] longhorn csi using wrong folder

### ISSUE THREAD

**Issue by ekristen** [longhorn/longhorn#1956]
**Describe the bug**

My cluster was predominately RancherOS but I started deploying some Ubuntu to it. The Longhorn CSI (I think it was the CSI) kept looking for /opt/rke when deployed to the Ubuntu systems but of course found it on the RancherOS systems.

**To Reproduce**

In my case, have RancherOS nodes and Ubuntu Nodes. It appears Longhorn auto-detects incorrectly on the Ubuntu nodes when Rancher OS is being used as well? Not really sure.

**Expected behavior**

I would expect it to detect the correct path.

**Environment:**
 - Longhorn version: Latest
 - Kubernetes version: 1.16.10
 - Node OS type and version: Ubuntu 20.04

**Additional context**

**Comment by yasker** [comment]
RancherOS is not supported by Longhorn, due to it being deprecated/replaced. And we do saw some issues with RancherOS.

Though in your case, I am not sure if that's the reason. Can you show us the error message? I don't think we have hard-coded `/opt/rke` anywhere in the code.

**Comment by ekristen** [comment]
I realize RancherOS is not supported, this was a Ubuntu system and it was trying to mount /opt/rke/var/lib/kublet instead of /var/lib/kubelet.

I unfortunately had to take the nodes offline, I'll try and bring them back tomorrow and test this again and capture more logs.

**Comment by yasker** [comment]
Have you set `KUBELET_ROOT_DIR`? By latest Longhorn, you meant v1.0.2 right?
