### ISSUE TITLE
e.Spec.SalvageRequested sometimes is not set when all replicas fail

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#1957]
**To Reproduce**
1. Create a volume of one replica. Attach the volume to a node.
1. Find the node of the replica. Let's say `node-1`
1. Exec into the replica instance manager on `node-1`
1. Find the replica process of the volume by `ps aux`
1. kill the replica process by `kill <REPLICA-PID>`
1. On another terminal, run `kubectl get engines -n longhorn-system -o yaml -w | grep salvage`
1. Repeate the above process many times, observer that `e.Spec.SalvageRequested` sometimes is not set:
  ```
   salvageRequested: false
   salvageExecuted: false
   salvageRequested: false
   salvageExecuted: false
   salvageRequested: false
   salvageExecuted: false
   ...
  ```

**Expected behavior:**

`e.Spec.SalvageRequested` should always be set when all replicas fail
   ```
   salvageRequested: false
   salvageExecuted: false
   salvageRequested: false
   salvageExecuted: false
   salvageRequested: true
   salvageExecuted: false
   salvageRequested: true
   salvageExecuted: false
   salvageRequested: true
   salvageExecuted: true
   salvageRequested: false
   salvageExecuted: true
   salvageRequested: false
   salvageExecuted: false
   salvageRequested: false
   salvageExecuted: false
   ```

**Additional context**
This issue impacts https://github.com/longhorn/longhorn/issues/508
The root cause is similar to https://github.com/longhorn/longhorn/issues/1942 but the solution may not be the same.

**Comment by PhanLe1010** [comment]
**Test Steps:**
Follow the reproduce step https://github.com/longhorn/longhorn/issues/1957#issue-737344777
Verify that we always get the `Expected behavior`
Create a volume of 1 replica. Create deployment of 1 pod using the volume. Write some data to the volume. Set `Disable Revision Counter` to true. Find the replica instance manager of the volume's replica. Kill the replica process of the volume. Wait for the pod to restart. Verify that we still see the previous data.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master - `12/1/2020`

Validation - **Pass**

Killed the replica process ~20 times with `Revision Counter` enabled and disabled. The field `salvageRequested` becomes True and once `salvageExecuted` is set True, the `salvageRequested` becomes False.

Output of `kubectl get engines -n longhorn-system -o yaml -w | grep salvage` is as below
```
  salvageRequested: false
  salvageExecuted: false
        f:salvageRequested: {}
        f:salvageExecuted: {}
  salvageRequested: true
  salvageExecuted: false
        f:salvageRequested: {}
        f:salvageExecuted: {}
  salvageRequested: true
  salvageExecuted: false
        f:salvageRequested: {}
        f:salvageExecuted: {}
  salvageRequested: true
  salvageExecuted: false
        f:salvageRequested: {}
        f:salvageExecuted: {}
  salvageRequested: true
  salvageExecuted: false
        f:salvageRequested: {}
        f:salvageExecuted: {}
  salvageRequested: true
  salvageExecuted: false
        f:salvageRequested: {}
        f:salvageExecuted: {}
  salvageRequested: true
  salvageExecuted: true
        f:salvageRequested: {}
        f:salvageExecuted: {}
  salvageRequested: false
  salvageExecuted: true
        f:salvageRequested: {}
        f:salvageExecuted: {}
  salvageRequested: false
  salvageExecuted: false
```
