### ISSUE TITLE
[Question] How to gracefully reboot a node without creating failed replicas

### ISSUE THREAD

**Issue by benalexau** [longhorn/longhorn#1958]
The [Volumes and Nodes Maintenance 1.0.2 documentation](https://longhorn.io/docs/1.0.2/volumes-and-nodes/maintenance/) states:

> Currently, it’s recommended to shut down the workloads with Longhorn volume before performing the node maintenance. 

Because workloads and their associated Longhorn volumes are transparently scheduled across many nodes, are you aware of an operator or other similar tool that can iterate over every workload and shut it down before planned maintenance (I had a look for an operator that does this but couldn't find one)?

The documentation indicated that an alternative is to cordon and drain a node before reboot. To test this I selected a node holding 2 volumes, both of which had a replica count of 1. I used [kured](https://github.com/weaveworks/kured) to cordon and drain the node.

During the cordon and drain process I noticed that several 3 replica volumes physically present on other nodes in the cluster (which were **not** being rebooted) unexpectedly switched into "degraded" state. These volumes were attached to workloads on the node that was being drained (and as such the Longhorn Engine for those volumes was also on the node being drained). These volumes generally returned to "Healthy" state a short time later (depending on volume size) but the transient degraded state resulted in creation of "failed" replicas on each node. For example:

![image](https://user-images.githubusercontent.com/718596/98322875-98e1e600-203c-11eb-9e03-05fe4050b6f9.png)

Unfortunately failed replicas do not automatically delete and require manual intervention. This is problematic when a large number of volumes are impacted. A pragmatic workaround would be fewer, larger volumes via NFS, but this seems risky given the space failed replicas would consume and the overhead (I/O, network, CPU) that recovery from a degraded state requires.

Questions:

* Is there a better way to handle planned node reboots?
* Is there an automated way to delete "failed" replicas?
* Is there advice / recommendations  for larger volumes (1 TB+) with mostly static / unchanging data?

**Comment by yasker** [comment]
1. The failed replica will be removed automatically after `staleReplicaTimeout` which is normally set to either 20 minutes or two days.
2. In the upcoming v1.1.0 release, we will have the following features helping with the node maintenance:
    1. Rebuild on an existing replica, so a failed replica can be used instead of creating a new replica every time. #1304 
    2. Support for drain operation #1631 . This improvement will help to guarantee the engine will be gracefully moved from the drain node to other nodes (as Kubernetes specified). This will help your unexpected degraded volumes case.
    3. Also, if you decide to decommission a node, #298 will help to ensure the graceful migration of replicas to a new node/disk.
3. If you have enough disk space (since Longhorn volume cannot exceed the physical size of one disk), Longhorn should work fine. Otherwise you can take a look at object stores e.g. MinIO.
