### ISSUE TITLE
[TASK] automatically build necessary engine images for test

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1961]
There are a few engine images by name e.g. `longhornio/longhorn-test:version-test.4-3.3-3.1-1` and `longhornio/longhorn-test:upgrade-test.4-3.3-3.1-1` are used by Longhorn integration test, e.g. [here](https://github.com/longhorn/longhorn-tests/blob/2129e3860e22d9627af4823abf54062a35d8e8d4/manager/integration/tests/test_engine_upgrade.py#L404) and [here](https://github.com/longhorn/longhorn-tests/blob/2129e3860e22d9627af4823abf54062a35d8e8d4/manager/integration/tests/test_engine_upgrade.py#L609) . So far those images are manually built using scripts at https://github.com/longhorn/longhorn-tests/tree/master/manager/test_containers .

The compatibility test images are built using https://github.com/longhorn/longhorn-tests/blob/master/manager/test_containers/compatibility/generate_version_image.sh .

The upgrade test image is a bit more complicated. It requires a manually tagged engine image (https://github.com/longhorn/longhorn-tests/blob/master/manager/test_containers/upgrade/generate_live_upgrade_image.sh#L4 ) to act as the base. And this manual tagged engine image cannot have the same Git commit ID as an existing engine image. So normally what we did is:
1. Clone the latest Longhorn engine
2. Add one more commit to it.
3. Build it locally.
4. Tag the image to e.g. `longhornio/longhorn-engine:live-upgrade-4-3-1` then run the build script.

Currently, we also need to update the version number by hand. For example, the current vanilla engine version output is something like:  
```
$ ./bin/longhorn version --client-only
{
	"clientVersion": {
		"version": "dbe126f",
		"gitCommit": "dbe126f4ad5cd7aa2277537ed2aec64827523573",
		"buildDate": "2020-09-21T21:44:36+00:00",
		"cliAPIVersion": 4,
		"cliAPIMinVersion": 3,
		"controllerAPIVersion": 3,
		"controllerAPIMinVersion": 3,
		"dataFormatVersion": 1,
		"dataFormatMinVersion": 1
	},
	"serverVersion": null
}
```

We should be able to update the version automatically based on the output of the current version.

So ideally, we should able to generate the correct build of engine test images by providing the engine repo to it, so the script can:
1. Pull the repo
2. Add a commit to generate a different Git commit
3. Compile (simply build & package is enough. we can skip the test since it's upstream engine)
4. Use the version output to generate the correct compatible test engine image names as well as the upgrade test engine image, for both AMD64 and ARM64.

And those can be done on the basis of necessity.

I am thinking probably we can use a Jenkins job to do it manually, instead of relying on Drone. It's possible to do it through Drone if it detects the version change, but there can be incompatible changes in the same release cycle, so it's better if we can trigger the build manually.

**Comment by chanow816** [comment]
I would like to join this feature's implement and below are my current plan to try to achieve the goal :

- Use terraform create an arch amd64 machine 

> On that machine, pull latest longhorn-engine, add minor change and commit
> Build docker image, push to https://hub.docker.com/r/longhornio/longhorn-test

- Use terraform create an arch arm64 machine

> On that machine, pull latest longhorn-engine, add minor change and commit
> Build docker image, push to https://hub.docker.com/r/longhornio/longhorn-test
> 

- Use docker manifest combine two different arch engine test images with correct tag

- Merge above steps/scripts into longhorn-engine build pipeline, make this feature automate

> ( need know more about longhorn build process)

cc @innobead , @khushboo-rancher , @meldafrawi

**Comment by chanow816** [comment]
Update local test result:

With environment variable `docker_repo=chanow/longhorn-engine` set, 
Script will generate below 2 test images auto tagged and push into docker hub as below result

- chanow/longhorn-engine:version-test.5-3.3-3.1-1
- chanow/longhorn-engine:upgrade-test.5-3.3-3.1-1

![Screenshot from 2022-01-26 10-10-20](https://user-images.githubusercontent.com/73337386/151094047-080ea2ee-19bb-453a-8553-967517873981.png)

cc @innobead , @khushboo-rancher , @meldafrawi, @shuo-wu

**Comment by cchien816** [comment]
Close this ticket because now we have private pipeline to build necessary arm64/amd64 test engine images.
Arm64 pipeline have no failure related to engine upgrade test

- Build [181](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/181/) : 5 failures
- Build [182](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/182/) : 8 failures
