### ISSUE TITLE
[Question] Can longhorn support 0 replicas?

### ISSUE THREAD

**Issue by BeardyC** [longhorn/longhorn#1962]
Hi,
Does longhorn support 0 replicas on the storageclass? We're trying to use it to replace the default local-path provisioner which does not support capacity limiting. 
I've created my own longhorn storageclass with both 1 and 0 replicas, 1 seems to work but with 0 it defaults back to 3 replicas. 
Are you able to clarify if this is doable?

**Comment by yasker** [comment]
I think you meant 1 instead of 0? 1 replica means no replication, the data only stored once.

**Comment by BeardyC** [comment]
My mistake. Misread when I had 1 replica, thought I had seen 2 replicas on 2 nodes. Thanks for getting back to me.
