### ISSUE TITLE
How to recover a failed disk?

### ISSUE THREAD

**Issue by venomone** [longhorn/longhorn#1963]
Hey folks, I already searched the web but with no luck so far.
I just deleted (for testing proposes)  the content of my longhorn disk including the disk config file.
Now I uncordoned the node again but its not able to get up again and stays in unschedulable state, actually I would expect some magic at this point as just 1/3 nodes have a failed disk now ... Why Is the system not recovering itself? What do I have to do in order to make my node with the deleted disk work again?

Kind regards

**Comment by yasker** [comment]
Can you post the reproduce steps?
