### ISSUE TITLE
[FEATURE] - Healthcheck type to rattle longhorn

### ISSUE THREAD

**Issue by jdunhamvrtx** [longhorn/longhorn#1966]
**Is your feature request related to a problem? Please describe.**
Frequently I experience read-only mounts for my longhorn storage. LH does not present any errors even though the workloads frequently flap.

**Describe the solution you'd like**
I'd like a special healthcheck option in the volume config that is a drop down menu of some options, Option 1 : ' Write a file to this store on a schedule', Option 2: 'Use a container script to perform storage healthcheck'. If a negative response is found then trigger a detach / reattach of the workload volumes.

**Describe alternatives you've considered**
Overloading a readiness script. This won't cycle the pod in a way that shakes the storage mount however.

**Comment by michaelpearce-gain** [comment]
Sounds like this is an underlying bug, surely it be better to fix that than create some sticky plaster of detach/reattach?

**Comment by jdunhamvrtx** [comment]
I agree to it being a bug ... but it's in the spirit of what HealthChecks are meant to do. For classical (non-container) deployments storage isn't really dynamic, you just use the disk/vol so the chances of it not being there are slim. Longhorn as a dynamic and flexible storage orchestrator is now closing the gap on the level of flexibility as the app it's facilitating storage for ... and even these have two healthchecks.

Detach / reattach is not really my request. Just ability to recognize and respond appropriately to a foundational pod resource not being available.

**Comment by shuo-wu** [comment]
`read-only mounts` in Longhorn typically means something is wrong with the filesystem mounted on a Longhorn volume. Since Longhorn is a block-level storage system, it doesn't understand too much about the filesystem level.  Besides, the filesystem on Longhorn volume varies. We haven't found a graceful way to handle this kind of mount issue. For now, you can set [a liveness probe](https://github.com/longhorn/longhorn/blob/2e14a1c09e8f43a6fcb5d81feaf085adc7b3601f/examples/pod_with_pvc.yaml#L24) to check if the filesystem (write) works fine.

**Comment by joshimoo** [comment]
@jdunhamvrtx on detecting an engine failure, we now kill the workload pods which will lead to kubernetes restarting the pods (reattach & remount)

**Comment by jdunhamvrtx** [comment]
@joshimoo : Do you know which version will have this new behavior (sounds great).

**Comment by joshimoo** [comment]
@jdunhamvrtx we implemented this feature in v1.1 and it's enabled by default
https://longhorn.io/docs/1.1.0/references/settings/#automatically-delete-workload-pod-when-the-volume-is-detached-unexpectedly

**Comment by joshimoo** [comment]
Since we implemented the feature in v1.1, I am closing this issue.
If you have additional questions feel free to reopen or file a new issue.

**Comment by verbunk** [comment]
Not sure if I should re-open this ... 1.1 does not completely refresh the pod in a way that LH recognizes. I literally had a support session yesterday (for a different reason) that we had to manually juggle the pods for the reason above.

**Comment by shuo-wu** [comment]
> Not sure if I should re-open this ... 1.1 does not completely refresh the pod in a way that LH recognizes. I literally had a support session yesterday (for a different reason) that we had to manually juggle the pods for the reason above.

The new setting is designed for workload pods that are managed by a controller. In other words, it doesn't work for single pods. Currently, you may need to delete and recreate this kind of pods manually with the old PVCs/PVs resued. If that's not the case, feel free to reopen the issue or recreate a new issue to report the details.

**Comment by jdunhamvrtx** [comment]
Hey @shuo-wu ,

Good distinction. My original post was not focused on controller managed workloads so I'd prefer to keep this issue open and maybe open a different one to track the cases that were solved.

I don't think this is an edge case; if I use RMC and deploy a single pod workload and it 'loses' the volume in some way I would prefer a series of escalating level of roughness until the workload is viable.

**Comment by shuo-wu** [comment]
Then you can file a new post as a feature request: Recover Longhorn volumes for single pods, or Add alarms in this case.
