### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by skolkmann** [longhorn/longhorn#1968]
Multiple times a day, Longhorn CronJobs in Cluster1 get stuck in running with the the only line being

`time="2020-11-05T08:20:08Z" level=debug msg="Cleaned up snapshot c-sktm7m-4dc33a35 for pvc-b10c11f2-eafc-49a1-bcb6-bc935a9d50ad"`

This happens for all volumes in Cluster1. I use MinIO + Longhorn in Cluster2 to store the backups of Cluster1. Both clusters are currently running on a single node each, but don't even get close to 50% CPU or RAM (but could spike higher for seconds). Whether this is independent or separate, MinIO just as regularly stops working properly and logs the following Errors:

This one is no problem - MinIO keeps running and working
`API: SYSTEM()
04/11/2020 10:33:13 Time: 09:33:13 UTC 11/04/2020
04/11/2020 10:33:13 DeploymentID: cfe660d9-34df-41d2-a3db-a78ed71d7fa0
04/11/2020 10:33:13 Error: unexpected EOF
04/11/2020 10:33:13        3: cmd/data-usage-cache.go:452:cmd.(*dataUsageCache).load()
04/11/2020 10:33:13        2: cmd/fs-v1.go:267:cmd.(*FSObjects).CrawlAndGetDataUsage()
04/11/2020 10:33:13        1: cmd/data-crawler.go:108:cmd.runDataCrawler()`

These two mean problems - backups can neither be created nor read anymore
`API: PutObject(bucket=application-backups, object=backupstore/volumes/f8/e2/pvc-b10c11f2-eafc-49a1-bcb6-bc935a9d50ad/backups/backup_backup-fb4d2a32b08a43b9.cfg)
05/11/2020 09:25:45 Time: 08:25:20 UTC 11/05/2020
05/11/2020 09:25:45 DeploymentID: cfe660d9-34df-41d2-a3db-a78ed71d7fa0
05/11/2020 09:25:45 RequestID: 16448F19C9EEA207
05/11/2020 09:25:45 RemoteHost: 10.42.0.1
05/11/2020 09:25:45 Host: s3-backup-1.xxx.cloud
05/11/2020 09:25:45 UserAgent: aws-sdk-go/1.25.16 (go1.13.3; linux; amd64)
05/11/2020 09:25:45 Error: write /export/.minio.sys/buckets/application-backups/backupstore/volumes/f8/e2/pvc-b10c11f2-eafc-49a1-bcb6-bc935a9d50ad/backups/backup_backup-fb4d2a32b08a43b9.cfg/fs.json: input/output error
05/11/2020 09:25:45        4: cmd/api-errors.go:1979:cmd.toAPIErrorCode()
05/11/2020 09:25:45        3: cmd/api-errors.go:2004:cmd.toAPIError()
05/11/2020 09:25:45        2: cmd/object-handlers.go:1551:cmd.objectAPIHandlers.PutObjectHandler()
05/11/2020 09:25:45        1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()`

`API: ListObjectsV1(bucket=application-backups)
05/11/2020 09:26:02 Time: 08:26:02 UTC 11/05/2020
05/11/2020 09:26:02 DeploymentID: cfe660d9-34df-41d2-a3db-a78ed71d7fa0
05/11/2020 09:26:02 RequestID: 16448F26830773E4
05/11/2020 09:26:02 RemoteHost: 10.42.0.1
05/11/2020 09:26:02 Host: s3-backup-1.xxx.cloud
05/11/2020 09:26:02 UserAgent: aws-sdk-go/1.25.16 (go1.13.3; linux; amd64)
05/11/2020 09:26:02 Error: stat /export/application-backups: input/output error
05/11/2020 09:26:02        4: cmd/api-errors.go:1979:cmd.toAPIErrorCode()
05/11/2020 09:26:02        3: cmd/api-errors.go:2004:cmd.toAPIError()
05/11/2020 09:26:02        2: cmd/bucket-listobjects-handlers.go:407:cmd.objectAPIHandlers.ListObjectsV1Handler()
05/11/2020 09:26:02        1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()`

**To Reproduce**
Install Rancher 2.5.1 and then Longhorn 1.0.2 from the Cluster Explorer.
On Cluster1 install any workload that uses Longhorn as StorageClass and on Cluster2 install MinIO as helm chart. Use MinIO as the backup target for Longhorn in Cluster1.

**Expected behavior**
No errors and working recurring backups, without Longhorn CronJobs getting stuck in 'running'

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: k3s v1.19.3+k3s1
 - Node OS type and version: Ubuntu 20.04.1 LTS

**Comment by yasker** [comment]
@skolkmann  The next step after `Cleaned up snapshot c-sktm7m-4dc33a35 for pvc-b10c11f2-eafc-49a1-bcb6-bc935a9d50ad` should be backup creation and clean up.

It seems the backup cannot be successfully created, which matches the issue you saw on cluster 2.

As you mentioned in https://github.com/longhorn/longhorn/issues/1667#issuecomment-724636882, cluster 2 is using spinning disks, which is likely the reason why MinIO lost connection to the volume sometimes. It's likely the spinning disk cannot handle the IO from Longhorn, delayed response, and result in volume disconnection. 

Maybe you can try to add a liveness check (e.g. https://longhorn.io/docs/1.0.2/high-availability/recover-volume/ ) to see if it helps. Though Longhorn has only designed for and tested with SSD or NVMe.

**Comment by skolkmann** [comment]
Alright, as you mentioned, Longhorn is built for SSD or NVMe, I setup Cluster2 on SSD and everything works as expected - no disconnects or crashes, so I guess spinning disk was the root of the problem. Thank you for your help @yasker! Going to close this issue.
