### ISSUE TITLE
[FEATURE] Volume online expansion

### ISSUE THREAD

**Issue by alpha01** [longhorn/longhorn#1973]
Has there been any discussion regarding volume expansion while it's online? 

Since Longhorn's storage is thin-provisioned, for our critical systems we essentially will have to start with a big allocation to mitigate this. Rather than starting small and expand as needed without any downtime. 

Coming from a Portworx environment, one of the biggest benefits is the ability to expand volumes while they're online. I feel this approach provides us the most control on managing our storage.

**Comment by yasker** [comment]
Thanks for reporting @alpha01 . It's a duplicate of #1674 . We've added the feature into our plan.
