### ISSUE TITLE
[BUG] Auto Salvage feature is broken

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#1974]
**Describe the bug**
Auto Salvage feature is broken

**To Reproduce**
1. Create a volume of 1 replica. Attach to a node.
2. Find the instance manager of the replica. Kill the replica process of the replica
3. Observe that the volume stays in the faulty state forever. 

**Expected behavior**
Volume should be auto salvaged

**Additional context**
This issue causes the following e2e tests fail:
1. `test_ha_salvage`
2. `test_salvage_auto_crash_all_replicas` at https://github.com/longhorn/longhorn/issues/1742 and https://github.com/longhorn/longhorn/issues/1942

**Comment by yasker** [comment]
@PhanLe1010 can you figure out which commit is broken?

**Comment by PhanLe1010** [comment]
@yasker 

A potential root cause:

We change this field `replica.Spec.DiskID = disk.DiskUUID` in this PR https://github.com/longhorn/longhorn-manager/pull/759/commits/612a92b9204c56a81fa30ce745b97d91c6831dcc#diff-2e79416f364ea8aa941b4c89c1ec487f88d9f0ebac76408d685e279edb04575fR319

The corresponding field in the `node.Status.DiskStatus` must be changed to be the same value

cc @shuo-wu

**Comment by meldafrawi** [comment]
Validation: **PASSED**
tests  `test_ha_salvage` & `test_salvage_auto_crash_all_replicas` are passing for the past 5 nightly test runs
