### ISSUE TITLE
[BUG] Live upgrade fails for volume if replica instance manager pod was deleted and recreated before longhorn upgrade.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1975]
**Describe the bug**
Live upgrade from longhorn v1.0.2 to the master fails for a volume if the replica instance manager was deleted and recreated before longhorn upgrade.

**To Reproduce**
1. Deploy longhorn v1.0.2 in a set up of 4 nodes (1 etcd/control plane, 3 workers)
2. Create a volume with 3 replicas. Write some data into it.
3. Delete instance-manager-r pod from node 1. This will cause the replica on node 1 fails and once instance-manager-r pod is recreated, Another replica will get created.
3. Upgrade longhorn to master.
4. Do the live upgrade of the volume.
5. Upgrade fails. The replica created with the new instance-manger doesn't come up healthy.

<img width="1762" alt="Screen Shot 2020-11-11 at 5 43 46 PM" src="https://user-images.githubusercontent.com/60111667/98884919-f06dc080-2445-11eb-8dc6-cb0f32c5acbc.png">

**Expected behavior**
The upgrade should succeed.

**Log**
[longhorn-support-bundle_56d2ae1f-daa6-4286-a8c0-0cd186f88b37_2020-11-12T01-01-50Z.zip](https://github.com/longhorn/longhorn/files/5527630/longhorn-support-bundle_56d2ae1f-daa6-4286-a8c0-0cd186f88b37_2020-11-12T01-01-50Z.zip)
```
[longhorn-manager-5bnpc] time="2020-11-12T01:12:57Z" level=debug msg="Volume healthy replica counts doesn't match" controller=longhorn-volume frontend=blockdev node=khush-test-upgrade-wk2 owner=khush-test-upgrade-wk2 state=attached volume=pvc-cc231536-2402-4b87-96ea-47c4d8748852 
[longhorn-manager-5bnpc] time="2020-11-12T01:12:57Z" level=debug msg="Volume healthy replica counts doesn't match" controller=longhorn-volume frontend=blockdev node=khush-test-upgrade-wk2 owner=khush-test-upgrade-wk2 state=attached volume=pvc-cc231536-2402-4b87-96ea-47c4d8748852 
```

**Environment:**
 - Longhorn version: longhorn-master - 11/11/2020
 - Kubernetes version: v1.18.10
 - Node OS type and version: 18.04

**Additional context**
Initially longhorn was installed using the rancher app and upgraded it using kubectl command.

**Comment by shuo-wu** [comment]
The root cause of this issue:
1. When the old instance manger pod is deleted and Longhorn hasn't relaunch instances in the corresponding new instance manager pod, Longhorn system is updated. 
2. At this moment, the old instance manager CR will be cleaned up due to no instances running in it. Then the rebuilding replica will get stuck there.
```
2020-11-12T00:52:25.907870266Z time="2020-11-12T00:52:25Z" level=warning msg="Error syncing Longhorn replica longhorn-system/pvc-cc231536-2402-4b87-96ea-47c4d8748852-r-196cc646: fail to sync replica for longhorn-system/pvc-cc231536-2402-4b87-96ea-47c4d8748852-r-196cc646: failed to get instance manager for instance pvc-cc231536-2402-4b87-96ea-47c4d8748852-r-196cc646: can not find the only available instance manager for instance pvc-cc231536-2402-4b87-96ea-47c4d8748852-r-196cc646, node khush-test-upgrade-wk1, instance manager image longhornio/longhorn-instance-manager:v1_20201021, type replica"
2020-11-12T00:52:25.908024773Z time="2020-11-12T00:52:25Z" level=warning msg="Error syncing Longhorn replica longhorn-system/pvc-53bc19b8-1c5a-4403-b785-2b9ad5a40083-r-6fce8fa2: fail to sync replica for longhorn-system/pvc-53bc19b8-1c5a-4403-b785-2b9ad5a40083-r-6fce8fa2: failed to get instance manager for instance pvc-53bc19b8-1c5a-4403-b785-2b9ad5a40083-r-6fce8fa2: can not find the only available instance manager for instance pvc-53bc19b8-1c5a-4403-b785-2b9ad5a40083-r-6fce8fa2, node khush-test-upgrade-wk1, instance manager image longhornio/longhorn-instance-manager:v1_20201021, type replica"
```
3. Since there is [an old replica get stuck in rebuilding state](https://github.com/longhorn/longhorn-manager/blob/92b89fc045150caa8e51c39070a1148582629e18/controller/volume_controller.go#L1198), the live upgrade will keep error out.
```
2020-11-12T00:55:14.112419317Z time="2020-11-12T00:55:14Z" level=debug msg="Volume healthy replica counts doesn't match" controller=longhorn-volume frontend=blockdev node=khush-test-upgrade-wk2 owner=khush-test-upgrade-wk2 state=attached volume=pvc-cc231536-2402-4b87-96ea-47c4d8748852
```

**Comment by shuo-wu** [comment]
Test steps:
1. Deploy Longhorn v1.0.2
2. Create and attach a volume
3. Upgrade Longhorn to master
4. Delete one replica manager pod. And do live upgrade for the volume **before** the new replica is created.
5. Check if Longhorn can reuse the failed replicas and complete the live upgrade

**Comment by yasker** [comment]
Hmm? Is the fix for #1118 a pre-requirement for this fix? But you also suggested that we don't need to add more fix to #1118. I am confused.

**Comment by yasker** [comment]
The upgrade is by design disabled during the rebuild process. It should allow the user to finish the rebuild first, then complete the upgrade process. Is it OK to create a new replica instance manager (new version) for this rebuild? or we have to create a replica instance manager with the old version.

**Comment by shuo-wu** [comment]
@khushboo-rancher Can you check if you can reproduce the case you provide? More accurately, how do you guarantee:
1. there is 1 stopped old replica + 2 running old replicas
2. the live upgrade is blocked even if the volume is healthy without error replica.

**Comment by khushboo-rancher** [comment]
I tried reproducing the case which I've mentioned but couldn't reproduce because of the merged code I think. I was seeing the issue on upgrading Longhorn v1.0.2 to longhorn Master dated `11/11/2020` with a set up of 4 Nodes (1 etcd/control plane and 3 worker)

However, to have 1 stopped old replica + 2 running old replicas before upgrade, we can follow the below steps.
1. Have a set up of Longhorn v1.0.2 and a volume created.
2. Delete instance-r-manager on a node which is not attached to the volume.
3. On deletion of the instance-r-manager the replica will go to stopped state and a new replica will be rebuilt.
4. Reduce the replica count to 2 and delete the newly created replica.
5. Upgrade the set up.


>>The live upgrade is blocked even if the volume is healthy without error replica.

I didn't see any problem in upgrade in case of healthy replica.

@shuo-wu Does the above answer your question?

**Comment by shuo-wu** [comment]
Yes. There will be a stopped replica (with `spec.FailedAt` set) based on the steps you provide. But the error `failed to get instance manager for instance` is not triggered. Let's ignore #1118 unless we can find a way to reproduce it in the future.

**Comment by khushboo-rancher** [comment]
Verified with longhorn master `12/10/2020`

Validation - **Pass**

The live upgrade worked fine in case the instance-manager-r was deleted and recreated before longhorn upgrade. Tried it 3 times.
