### ISSUE TITLE
[BUG] Multiple tolerations with the same key cannot be applied

### ISSUE THREAD

**Issue by takuhiro** [longhorn/longhorn#1977]
**Describe the bug**
When I set multiple tolerations such as `example.com/foobar:NoExecute;example.com/foobar:NoSchedule` [via Longhorn UI](https://longhorn.io/docs/0.8.1/advanced-resources/deploy/taint-toleration/#after-longhorn-has-been-installed), only the last toleration is applied to DaemonSets and others are ignored.

**To Reproduce**
1. Go to 'Longhorn UI'
2. Setting -> General -> Kubernetes Taint Toleration
3. Set `example.com/foobar:NoExecute;example.com/foobar:NoSchedule`
4. Run `kubectl get daemonset -n longhorn-system longhorn-csi-plugin -o jsonpath='{.spec.template.spec.tolerations}'` and will get only the last toleration `[map[effect:NoSchedule key:example.com/foobar operator:Exists]]`
5. However, `settings.longhorn.io/taint-toleration` is set properly
```
kubectl get settings.longhorn.io -n longhorn-system taint-toleration -o jsonpath='{.value}'
example.com/foobar:NoExecute;example.com/foobar:NoSchedule
```

**Expected behavior**
I expect that the multiple tolerations are set in Daemonsets as well as `settings.longhorn.io/taint-toleration`

**Log**
```
time="2020-11-12T08:29:34Z" level=debug msg="Updated setting taint-toleration to example.com/foobar:NoExecute;example.com/foobar:NoSchedule"
```

**Environment:**
 - Longhorn version: v1.0.2
 - Kubernetes version: v1.19.3
 - Node OS type and version: Ubuntu 18.04.5 LTS

**Additional context**
This code looks to overwrite the existing toleration key.
https://github.com/longhorn/longhorn-manager/blob/00f8d97faccf54518b8cd90f09260aaf695447f6/util/util.go#L707

**Comment by mklokocka** [comment]
I have the same problem. Both `engine-image-ei-...` and `longhorn-csi-plugin` DaemonSets have both key:effect pairs (`dedicate:NoSchedule` and `dedicate:NoExecute` in my case) but `longhorn-manager` DaemonSet only has the `dedicate:NoExecute` toleration.

I have set up both tolerations in the default settings configmap during deployment. (v1.0.2 as well).

**Comment by takuhiro** [comment]
@mklokocka The same problem was reproduced in our environment as well, so I changed the issue title.
When I set multiple tolerations in default-setting.yaml, longhorn-manager daemonsets has only one toleration, but other daemonsets have the specified multiple tolerations.

**Comment by PhanLe1010** [comment]
Thanks @takuhiro ! You are right!
> This code looks to overwrite the existing toleration key.
https://github.com/longhorn/longhorn-manager/blob/00f8d97faccf54518b8cd90f09260aaf695447f6/util/util.go#L707

We are fixing this bug.
Thank you for reporting.

**Comment by PhanLe1010** [comment]
**Test Steps:**
Follow the reproduce step at https://github.com/longhorn/longhorn/issues/1977#issue-741403375
Verify that there are 2 tolerations `example.com/foobar:NoExecute;example.com/foobar:NoSchedule` in every Longhorn components.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master - 11/24/2020

Validation - **Partially Passed**

**Scenarios**
1. Setting multiple tolerations on a set up of 4 nodes (1 etcd/control plane, 3 workers) - **Passed**
2. Setting multiple tolerations with combination of effect and empty effect. - One case failed explained below

When two same toleration `example.com=foobar:NoExecute;example.com=foobar:NoExecute; persistence=true:NoExecute` are provided in `Kubernetes Taint Toleration` setting, all the pods have it once but instance-manager pods have them twice.

instance-manager-pod:
```
"tolerations": [
    {
      "effect": "NoExecute",
      "key": "example.com",
      "operator": "Equal",
      "value": "foobar"
    },
    {
      "effect": "NoExecute",
      "key": "example.com",
      "operator": "Equal",
      "value": "foobar"
    },
    {
      "effect": "NoExecute",
      "key": "persistence",
      "operator": "Equal",
      "value": "true"
    },
    {
      "effect": "NoExecute",
      "key": "node.kubernetes.io/not-ready",
      "operator": "Exists",
      "tolerationSeconds": 300
    },
    {
      "effect": "NoExecute",
      "key": "node.kubernetes.io/unreachable",
      "operator": "Exists",
      "tolerationSeconds": 300
    }
  ],
```

longhorn-manager pod:
```
"tolerations": [
    {
      "effect": "NoExecute",
      "key": "persistence",
      "operator": "Equal",
      "value": "true"
    },
    {
      "effect": "NoExecute",
      "key": "example.com",
      "operator": "Equal",
      "value": "foobar"
    },
    {
      "effect": "NoExecute",
      "key": "node.kubernetes.io/not-ready",
      "operator": "Exists"
    },
    {
      "effect": "NoExecute",
      "key": "node.kubernetes.io/unreachable",
      "operator": "Exists"
    },
    {
      "effect": "NoSchedule",
      "key": "node.kubernetes.io/disk-pressure",
      "operator": "Exists"
    },
    {
      "effect": "NoSchedule",
      "key": "node.kubernetes.io/memory-pressure",
      "operator": "Exists"
    },
    {
      "effect": "NoSchedule",
      "key": "node.kubernetes.io/pid-pressure",
      "operator": "Exists"
    },
    {
      "effect": "NoSchedule",
      "key": "node.kubernetes.io/unschedulable",
      "operator": "Exists"
    }
  ],
```

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master - `11/25/2020`

Validation - **Pass**

Instance manager pods are no longer have duplicate tolerations.

**Comment by yasker** [comment]
`test_setting_toleration_extra` passed for [188](https://ci.longhorn.io/job/public/job/longhorn-tests/188/), [189](https://ci.longhorn.io/job/public/job/longhorn-tests/189/), [190](https://ci.longhorn.io/job/public/job/longhorn-tests/190/)
