### ISSUE TITLE
[BUG]StorageClass cannot be created when reccurring job is set

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1980]
**Describe the bug**
The recurring job in the ConfigMap used to create longhorn StorageClass is an escaped string, which will fail the StorageClass YAML decoding.

**To Reproduce**
1. Uncomment [the recurring job field](https://github.com/longhorn/longhorn/blob/36ad2daf0b8cee1ce64782ca00870f418b764d4e/examples/storageclass.yaml#L13)
2. Deploy/Update the ConfigMap
3. The corresponding StorageClass cannot be created

**Expected behavior**
The corresponding StorageClass should be created

**Log**
```
[longhorn-manager-pwc8v] time="2020-11-13T13:21:22Z" level=debug msg="storageclassYAML: kind: StorageClass\napiVersion: storage.k8s.io/v1\nmetadata:\n  name: longhorn\nprovisioner: driver.longhorn.io\nallowVolumeExpansion: true\nreclaimPolicy: Delete\nvolumeBindingMode: Immediate\nparameters:\n  numberOfReplicas: \"3\"\n  staleReplicaTimeout: \"2880\"\n  fromBackup: \"\"\n  diskSelector: \"ssd,fast\"\n  recurringJobs: \"[{\"name\":\"backup\", \"task\":\"backup\", \"cron\":\"*/2 * * * *\", \"retain\":1}]\"\n"
[longhorn-manager-pwc8v] time="2020-11-13T13:21:22Z" level=warning msg="Dropping ConfigMap longhorn-system/longhorn-storageclass out of the queue" controller=longhorn-kubernetes-configmap-controller error="longhorn-kubernetes-configmap-controller: fail to sync longhorn-system/longhorn-storageclass: error while decoding YAML string: yaml: line 13: did not find expected key" node=shuo-cluster-1-worker-3
[longhorn-manager-pwc8v] E1113 13:21:22.321106       1 kubernetes_configmap_controller.go:131] longhorn-kubernetes-configmap-controller: fail to sync longhorn-system/longhorn-storageclass: error while decoding YAML string: yaml: line 13: did not find expected key
```

**Environment:**
 - Longhorn version: master - 11/13/2020
 - Kubernetes version: v1.18.10
 - Node OS type and version: Ubuntu v18.04

**Additional context**

**Comment by PhanLe1010** [comment]
@shuo-wu 
In the [reproducing steps](https://github.com/longhorn/longhorn/issues/1980#issue-742453052). In the step 1,  I think that we cannot directly  use the [storageclass yaml](https://github.com/longhorn/longhorn/blob/36ad2daf0b8cee1ce64782ca00870f418b764d4e/examples/storageclass.yaml). We need to use [storageclass configmap yaml](https://github.com/longhorn/longhorn-manager/blob/8af120dd7c109d81d86118e482f88a26ddf7650f/deploy/install/01-prerequisite/06-storageclass.yaml). May be this is the reason that causes this issue?

I couldn't reproduce the problem with the following steps:
1.  Uncomment [the recurring job field](https://github.com/longhorn/longhorn-manager/blob/8af120dd7c109d81d86118e482f88a26ddf7650f/deploy/install/01-prerequisite/06-storageclass.yaml#L22)
1. Deploy/Update the ConfigMap
1. Create a deployment using the `longhorn` storageclass.
1. I observe that there is no error. The recurring jobs work as expected.

**Comment by shuo-wu** [comment]
You are right. I may somehow mess up the StorageClass with StorageClass ConfigMap.
