### ISSUE TITLE
[BUG] longhorn-backend is not reachable for some nodes after running for a while

### ISSUE THREAD

**Issue by ElisaMeng** [longhorn/longhorn#1981]
**Describe the bug**

I have longhorn deployed, all looks good at the beginning. However, after running for a while, just some hours. Some start to lost connectivity to longhorn backend service. 

```
 kubectl -n longhorn-system get service 
NAME                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
csi-attacher        ClusterIP   10.43.75.4      <none>        12345/TCP   171m
csi-provisioner     ClusterIP   10.43.199.236   <none>        12345/TCP   171m
csi-resizer         ClusterIP   10.43.80.13     <none>        12345/TCP   171m
longhorn-backend    ClusterIP   10.43.197.171   <none>        9500/TCP    20d
longhorn-frontend   ClusterIP   10.43.30.52     <none>        80/TCP      66d
```
Get into a pod that running on the trouble node, and run debug cmd:
```
nc -w 3  -v -z 10.43.197.171 9500 
nc: 10.43.197.171 (10.43.197.171:9500): Operation timed out

```
**To Reproduce**

This has been consistent issue in my test. 
- Create longhorn cluster 
- let it run for a while, Some node soon has this problem. 

**Expected behavior**
longhorn as a storage system, should be reliable running. 

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

**Environment:**
 - Longhorn version:
v1.0.2
 - Kubernetes version:
v1.19.3
 - Node OS type and version:
k3os

**Additional context**

**Comment by yasker** [comment]
@ElisaMeng If you can reach every Longhorn manager's individual IPs (see `kubectl -n longhorn-system get pods -o wide`, check `longhorn-manager-xxxx`) but not the service IP, that indicates a problem in the Kubernetes networking.

In that case, you can check with k3os team to determine what can be the problem.

If you find there are some Longhorn manager you cannot connect to, please attach the manager's log here.

**Comment by ElisaMeng** [comment]
@yasker Thanks a lot for the quick response! Yes, it seems a networking issue in k3os, at least in my nodes.  I will close this one for now and look for help in k3os forum. In case, i can problem solved there but I still have issue, I will come back to you. :D
