### ISSUE TITLE
[Question] PV created, but not attaching to Pod

### ISSUE THREAD

**Issue by sankarshvittal** [longhorn/longhorn#1987]
Hello,

I am having this problem wherein, the PV is being created, but the attachment to the pod is not successful on using longhorn, has anybody else encountered this problem before. Please Suggest, Thanks!

I am using, one master two worker node setup, I am getting the same error on having longhorn replica counts set as 1 or 2.

![image](https://user-images.githubusercontent.com/31777036/99263999-e9500500-27ed-11eb-9f10-13d0baf7af9f.png)

![image](https://user-images.githubusercontent.com/31777036/99264189-21efde80-27ee-11eb-88c2-791b498e3f30.png)

![image](https://user-images.githubusercontent.com/31777036/99264332-4fd52300-27ee-11eb-8887-6cd0d2457685.png)

![image](https://user-images.githubusercontent.com/31777036/99264410-6b402e00-27ee-11eb-931d-7b433fc1bdcf.png)

**Comment by yasker** [comment]
Can you check the log of `longhorn-manager` on the node? Search for the PV name should give you some error messages and clues why it failed.

**Comment by sankarshvittal** [comment]
@yasker Thanks a lot for the suggestion. Found through the longhorn-manager logs that the problem was with the iscsi-initiator-utils package. Uninstalling and then installing the package back on the nodes did the trick for me. It's working fine now. Thanks!
