### ISSUE TITLE
[TASK] Fix integration test for ARM64

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1990]
The current integration test results in quite a few errors:

~https://ci.longhorn.io/job/public/job/longhorn-tests-arm64/12/~

New CI URI: https://ci.longhorn.io/job/public/job/ubuntu/job/arm64/job/longhorn-tests-ubuntu-arm64/

**Comment by bradwood** [comment]
Probably also needs a specific test to create a PV bigger than 2GB to prove #1847 can be closed...

**Comment by yasker** [comment]
I've commented on #1847. I think it should due to ARMv7(32 bits) rather than ARM. We will verify it in ARM64.

**Comment by innobead** [comment]
@meldafrawi is this still valid? I thought the daily auto regression on ARM64 is quite stable.

**Comment by yasker** [comment]
This is done. The latest test result shows 22 test failures out of 232 tests. https://ci.longhorn.io/job/public/job/ubuntu/job/arm64/job/longhorn-tests-ubuntu-arm64/197/

Will track other test failures separately.
