### ISSUE TITLE
[BUG] Few services don't get deleted on uninstalling longhorn using rancher app

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2004]
**Describe the bug**
Few services don't get deleted on uninstalling longhorn using rancher app

**To Reproduce**
1. Deploy longhorn v1.0.2 in a cluster using rancher v2.4.9
2. Uninstall longhorn by removing the app.
3. Check the service in longhorn-system namespace

```
kubectl get service -n longhorn-system
NAME              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
csi-attacher      ClusterIP   10.43.246.59    <none>        12345/TCP   4m19s
csi-provisioner   ClusterIP   10.43.35.254    <none>        12345/TCP   4m18s
csi-resizer       ClusterIP   10.43.183.130   <none>        12345/TCP   4m18s
```

**Expected behavior**
All the components should be deleted.

**Environment:**
 - Longhorn version: v1.0.2
 - Kubernetes version: v1.18
 - Node OS type and version: ubuntu 18.04

**Comment by PhanLe1010** [comment]
We also need to delete all lease objects of CSI components

**Comment by innobead** [comment]
Closing, because it's duplicated of https://github.com/longhorn/longhorn/issues/2035.
