### ISSUE TITLE
[Question] What if I allocate more space at a PVC than a single node has?

### ISSUE THREAD

**Issue by venomone** [longhorn/longhorn#2005]
Hey Folks,

can smb. tell me if its possible to allocate more space at a pvc than a single node of my long-horn cluster has?
For example, i got 3 nodes, each with a 200gb block devices for long-horn to store Data. Now I have a container where my PVC claim is 450GB which would not fit onto a single node as each node has as already mentioned just 200GB of Storage available. Does such a scenario work with longhorn or do I have to enlarge the block-device itself?

Kind regards

**Comment by shuo-wu** [comment]
It's possible. As long as you set `Storage Over Provisioning Percentage` to an appropriate value and don't actually use up all storage, Longhorn volume should work fine. You can check this doc for more details: https://longhorn.io/docs/1.0.2/references/settings/#storage-over-provisioning-percentage

**Comment by venomone** [comment]
Okay, but I guess this still does not solve the question... I guess, maybe I miss understood you.
Where is my Data placed, given the following scenario:

- 3x Nodes with 200gb Block Device (XFS)
- 1x PVC with a size of 450GB

If I now really write 450GB into that volume where is my Data located then?

**Comment by yasker** [comment]
@venomone No, you cannot write 450GB into the volume. One Longhorn replica can only reside in one disk, so the maximum volume size (real size) cannot exceed the disk size.

What @shuo-wu mentioned above is over-provisioning, which means you can create a volume bigger than your disk, as long as you don't use it to the full size.

**Comment by miraculixx** [comment]
> you can create a volume bigger than your disk, as long as you don't use it to the full size.

what is the rationale behind this feature? it seems somewhat odd that you can define a volume larger than a node disk, but then once you start filling the volume the storage system breaks (been there, done that). 

Ideally, longhorn could split the block storage across nodes, say

* 1 PV of size 450GB
* 3x nodes with 400gb node disk (=600GB)

=> longhorn distributes its blocks across these three nodes such that each node holds say 150GB + the same amount replicated from another node, e.g.

* node 1: 0-150GB of PV, plus replica for node 2
* node 2: 150-300GB of PV, plus replica for node 1
* node 3: 300-450GB of PV, plus replica for node 3

This is just for illustration. Longhorn could choose a better strategy to distribute actual storage use, e.g. by consistently sharding blocks across the three nodes.

**Comment by yasker** [comment]
@miraculixx We indeed have a `sharding` mechanism in the roadmap https://github.com/longhorn/longhorn/wiki/Roadmap#future which is similar to what you've described here. Though at the moment our main focus is still on a single replica on a single disk use case.

Overprovisioning is a feature for those users who don't use up all the spaces they requested. You can disable the feature by setting the overprovisioning percentage to 100%, which won't allow overprovisioning to happen. https://longhorn.io/docs/1.0.2/references/settings/#storage-over-provisioning-percentage
