### ISSUE TITLE
[FEATURE] Enable backing image feature in Longhorn

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2006]
Longhorn Engine has the ability to use a qcow2 file as the backing image for the Longhorn volume. It was designed for VM but the feature was never implemented in Longhorn manager nor UI. We need to enable this feature for Harvester to use Longhorn with existing root images.

Btw, the field was called `base image` but it's better to rename everything into `backing image` because `base image` has become a standard Docker term.

Ref:
https://github.com/longhorn/longhorn/issues/1989#issuecomment-731458474
https://github.com/rancher/harvester/issues/227

**Comment by yasker** [comment]
Move to Icebox. Pending merge of https://github.com/longhorn/longhorn/issues/2295

**Comment by innobead** [comment]
The new version of backing image implementation is actually be based on #2295 . To avoid confusing QA for these similar tickets, close this and move focus on #2295.
