### ISSUE TITLE
[Question] How to update StorageClass snapshot retain quantity？

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#2008]
I update

  recurringJobs: '[
    {
      "name":"snap", 
      "task":"snapshot", 
      "cron":"0 * * * *",  
      "retain":10
    }
  ]'

from 10 to 5.

But get error

The StorageClass "longhorn" is invalid: parameters: Forbidden: updates to parameters are forbidden.

**Comment by PhanLe1010** [comment]
Updating StorageClass is forbidden by Kubernetes, [link](https://kubernetes.io/docs/concepts/storage/storage-classes/#the-storageclass-resource). 
If you want to change `retain` for existing volumes, you can do it in Longhorn UI. e.g. go to the volume details page and change the recurring backup job. 
If you want to change `retain` for future volumes, please create a new StorageClass with `retain=5` and use it for the new volumes.

**Comment by joshimoo** [comment]
@PhanLe1010 Is updating the snapshot retain quantity possible now that we are using a config map to generate the storage class?

**Comment by PhanLe1010** [comment]
Yes, it is possible to modify the default storageclass config map
```
kubectl edit configmap longhorn-storageclass -n longhorn-system
```
However, it is not recommended to do so. We recommend creating a new storageclass with the new parameter and use it instead.

**Comment by joshimoo** [comment]
Closing, please feel free to reopen if you require further guidance.
