### ISSUE TITLE
Need to add csi-snapshotter and share manager to airgap installation document

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2010]
We need to add `csi-snapshotter` and `share-manager` to the airgap document at ~~https://longhorn.io/docs/1.0.2/advanced-resources/deploy/airgap/~~ https://github.com/longhorn/website/blob/v1.1.0/content/docs/1.1.0/advanced-resources/deploy/airgap.md

**Additional context**
Ref
https://github.com/longhorn/longhorn/issues/304

**Comment by yasker** [comment]
1.0.2? We don't support it in 1.0.2. You meant v1.1.0?

**Comment by PhanLe1010** [comment]
Yes, I mean v1.1.0

**Comment by yasker** [comment]
We will validate the steps as a part of air gap installation pre-release test.
