### ISSUE TITLE
[Question] How to set k8s-api-server address

### ISSUE THREAD

**Issue by casek14** [longhorn/longhorn#2013]
Hi,
when running longhorn-manager I need to set the k8s api address which should manager use.
Manager uses the the env variables `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` .
But I need to point the manager to different endpoint, otherwise for internal api address I will get following error:
```
E1125  leaderelection.go:306] error retrieving resource lock longhorn-system/longhorn-manager-upgrade-lock: 
Get "https://10.96.0.1:443/apis/coordination.k8s.io/v1/namespaces/longhorn-system/leases/longhorn-manager-upgrade-lock": 
x509: cannot validate certificate for 10.96.0.1 because it doesn't contain any IP SANs
```

Is there a possibility to set the k8s api address ??
thanks in advance

**Comment by yasker** [comment]
How do you do it for other Kubernetes controllers? I thought updating `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` is the way to change the API server endpoint.

**Comment by PhanLe1010** [comment]
@casek14 
Is it correct the you are using the in cluster config so it uses `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` to get the API Server endpoint. https://github.com/longhorn/longhorn-manager/blob/c97e0d81791884cc12ca6b09ba48d7e75706c503/vendor/k8s.io/client-go/rest/config.go#L410

I haven't tried yet but I am thinking whether we set the `--kube-config=<KUBE_CONFIG_PATH>`at [here](https://github.com/longhorn/longhorn-manager/blob/c97e0d81791884cc12ca6b09ba48d7e75706c503/deploy/install/02-components/01-manager.yaml#L23) so that Longhorn uses the provide config file to get the api server endpoint at [here](https://github.com/longhorn/longhorn-manager/blob/c97e0d81791884cc12ca6b09ba48d7e75706c503/app/daemon.go#L55)

**Comment by casek14** [comment]
Thank you for replies.
The k8s provider I am using use api endpoint in format `https://{cluster-id}.{zone}.exo.io:6443` , and as you can see when I use in cluster config, the api ip is not included in the cert so the manager cannot validate it.
For example cilium has option in config `k8s-api-server` to change the api endpoint, so I wanted to know, if longhorn has something similar.
I will try the --kube-config option and let you know.

**Comment by PhanLe1010** [comment]
Thanks! Looking forward to the result from you. If there is problem with the approach, I will dig deeper into the issue.

**Comment by casek14** [comment]
I was able to figure it out, at least for manager and driver deployer.
I just overwritten the `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT`
```
env:
  - name: KUBERNETES_SERVICE_HOST                                                                                                                  
    value: "{cluster-id}.{zone}.exo.io"                                                                              
  - name: KUBERNETES_SERVICE_PORT                                                                                                                  
    value: "6443"   
```

Pods are running except `csi-provisioner`:
```
NAME                                       READY   STATUS             RESTARTS   AGE
csi-attacher-5b4745c5f7-6v7dz              1/1     Running            0          4m28s
csi-attacher-5b4745c5f7-cdvmw              1/1     Running            0          4m28s
csi-attacher-5b4745c5f7-xp97r              1/1     Running            0          4m28s
csi-provisioner-57d6dbf5f4-85qpf           0/1     CrashLoopBackOff   5          4m28s
csi-provisioner-57d6dbf5f4-9nxvl           0/1     CrashLoopBackOff   5          4m27s
csi-provisioner-57d6dbf5f4-j2fmd           0/1     CrashLoopBackOff   5          4m27s
csi-resizer-75ff56bc48-cx7lf               1/1     Running            0          4m26s
csi-resizer-75ff56bc48-q8db6               1/1     Running            0          4m26s
csi-resizer-75ff56bc48-z5r6q               1/1     Running            0          4m26s
engine-image-ei-3bd16bdf-6nbdx             1/1     Running            0          4m48s
engine-image-ei-3bd16bdf-c7pzn             1/1     Running            0          4m48s
engine-image-ei-3bd16bdf-dpvlz             1/1     Running            0          4m48s
instance-manager-e-2afe77cf                1/1     Running            0          4m34s
instance-manager-e-a8d8f6a8                1/1     Running            0          4m48s
instance-manager-e-e3fc8973                1/1     Running            0          4m10s
instance-manager-r-268c22dc                1/1     Running            0          4m8s
instance-manager-r-8490a0b5                1/1     Running            0          4m47s
instance-manager-r-f7b205d4                1/1     Running            0          4m34s
longhorn-csi-plugin-jqzrj                  2/2     Running            0          4m26s
longhorn-csi-plugin-sb266                  2/2     Running            0          4m26s
longhorn-csi-plugin-sjhlh                  2/2     Running            0          4m27s
longhorn-driver-deployer-bbf8bd457-xn8j2   1/1     Running            0          5m
longhorn-manager-2ltbl                     1/1     Running            0          5m1s
longhorn-manager-cqq86                     1/1     Running            0          5m1s
longhorn-manager-zfbb5                     1/1     Running            0          5m1s
longhorn-ui-787bd98565-cgfbs               1/1     Running            0          5m1s
```
The csi-provisioner log:
```
❯ kubectl --kubeconfig kubeconfig -n longhorn-system logs csi-provisioner-57d6dbf5f4-85qpf
I1126 11:36:52.824771       1 feature_gate.go:216] feature gates: &{map[]}
I1126 11:36:52.824837       1 csi-provisioner.go:98] Version: v1.4.0-0-g1d9bad3
I1126 11:36:52.824864       1 csi-provisioner.go:112] Building kube configs for running in cluster...
F1126 11:36:52.836633       1 csi-provisioner.go:132] Error getting server version: Get https://10.96.0.1:443/version?timeout=32s: x509: cannot validate certificate for 10.96.0.1 because it doesn't contain any IP SANs
```

I find out that csi-provisioner deployment is created by the manager here: https://github.com/longhorn/longhorn-manager/blob/master/csi/deployment.go#L122

And in this deployment is not configurable to set the env variable: https://github.com/longhorn/longhorn-manager/blob/c97e0d81791884cc12ca6b09ba48d7e75706c503/csi/deployment_util.go#L57
So when the csi-provisioner container starts it gets the info from in cluster config which is from api address in my case.

Do you have any ideas how to fix this ? 
I will test with kubeconfig.
Thanks for reply

**Comment by casek14** [comment]
Update test with kubeconfig mounted into manager and driver deployer.
Result is same as with use of env variables overwrite.
csi-provisioner is still failing.

**Comment by PhanLe1010** [comment]
Thanks for the update! Yeah, I think you found the root cause of the issue. Since this fix require modification to Longhorn manager source code, there is no workaround at the moment. We will fix this in the v1.1.0 release which is scheduled to release on Dec 15th.

**Comment by casek14** [comment]
Thx that`s fine.
@PhanLe1010 @yasker can you please point me to some document how to build longhorn docker images ? I would like to try workaround it in code and build images and test before, it`s merged.

**Comment by PhanLe1010** [comment]
Hi @casek14 

Sure! Here is the document [Getting started with Longhorn Development](https://github.com/longhorn/longhorn/wiki/Getting-started-with-Longhorn-Development) . 

There are a few Longhorn components. However, you only need to build [Longhorn manager](https://github.com/longhorn/longhorn-manager) for this fix. 

After you built the new `Longhorn manager` image. You can replace the `longhornio/longhorn-manager:master` by your new manager image in [this folder](https://github.com/longhorn/longhorn-manager/tree/master/deploy/install). deploy Longhorn by `kubectl apply -f` those components

Please let me know if you have any questions. Also, please don't use this Longhorn installation on production.

**Comment by casek14** [comment]
Thank you, this works

**Comment by yasker** [comment]
@casek14 due to the time constraint, we are unable to get this in v1.1.0. We will revisit it in v1.1.1.

**Comment by casek14** [comment]
Ok thank you, and when is the v1.1.1 version planned to be released ?

**Comment by yasker** [comment]
@casek14 It will be a few weeks after v1.1.0 release, likely in Jan 2021.

**Comment by PhanLe1010** [comment]
@casek14 

In the meantime, you can manually edit the `csi-provisioner` yaml file to set KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT.
