### ISSUE TITLE
[BUG] Volume It is always in the state of deletion。

### ISSUE THREAD

**Issue by LinXiaoJian** [longhorn/longhorn#2018]
**Describe the bug**
I installed Longhorn on the server cluster，It was discovered yesterday that Longhorn on one of the mainframes had been in an abnormal condition。PVC on this mainframe is in detaching state。Then I removed all the PVC from Longhorn-Manager。The PVC on this machine has been in a Deleting state。

`
E1201 06:27:38.559308       1 replica_controller.go:177] fail to sync replica for longhorn-system/pvc-330aa7e2-a336-457f-a940-562fe1e4d581-r-45e3b245: failed to cleanup the related replica process before deleting replica pvc-330aa7e2-a336-457f-a940-562fe1e4d581-r-45e3b245: failed to delete process pvc-330aa7e2-a336-457f-a940-562fe1e4d581-r-45e3b245: rpc error: code = DeadlineExceeded desc = context deadline exceeded

time="2020-12-01T06:27:38Z" level=warning msg="Dropping Longhorn replica longhorn-system/pvc-330aa7e2-a336-457f-a940-562fe1e4d581-r-45e3b245 out of the queue: fail to sync replica for longhorn-system/pvc-330aa7e2-a336-457f-a940-562fe1e4d581-r-45e3b245: failed to cleanup the related replica process before deleting replica pvc-330aa7e2-a336-457f-a940-562fe1e4d581-r-45e3b245: failed to delete process pvc-330aa7e2-a336-457f-a940-562fe1e4d581-r-45e3b245: rpc error: code = DeadlineExceeded desc = context deadline exceeded"

time="2020-12-01T06:28:35Z" level=error msg="failed to poll instance info to update instance manager instance-manager-r-4e30e133: failed to list processes: rpc error: code = DeadlineExceeded desc = context deadline exceeded"`

This is a screenshot from Longhorn-Manager。The state is always in the DELETE state。
![image](https://user-images.githubusercontent.com/11407854/100705360-0a197c80-33e2-11eb-8262-2033c9f80262.png)
![image](https://user-images.githubusercontent.com/11407854/100705575-6381ab80-33e2-11eb-9610-785e74d9eed0.png)

**To Reproduce**
I don't know how it happened

**Expected behavior**
I wonder how Can I get back to normal now

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

**Environment:**
 - Longhorn version: 1.0.0
 - Kubernetes version: 1.18.4
 - Node config
   - OS type and version: ubuntu  18.04
   - CPU per node:  4vcpu
   - Memory per node:  32 men
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**

**Comment by yasker** [comment]
Can you try to find the pod ` instance-manager-r-4e30e133` and delete it? There was a bug in v1.0.0 that might cause the instance manager to lock up if the specified data directory doesn't exist. Not sure if you've triggered that.

**Comment by LinXiaoJian** [comment]
Thank you very much for your reply. I've removed instance-manager-r-4e30e133. Longhorn is back to normal. I am now upgrading Longhorn to version 1.0.2. Will this version have similar problems

**Comment by yasker** [comment]
If it's the issue with the data directory, it's https://github.com/longhorn/longhorn/issues/1599 and will be fixed in the upcoming v1.1.0 release.

**Comment by LinXiaoJian** [comment]
ok ,Thank you very much for your reply.
