### ISSUE TITLE
[FEATURE]Update docs and descriptions based on the CPU & Network requirement investigation result

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2020]
**Is your feature request related to a problem? Please describe.**
Need to update Longhorn docs and the description of setting `Guaranteed Engine CPU` based on the result in #1691

**Comment by yasker** [comment]
Volume count in the cluster?

Also, I am thinking if we should ask the user to reserve 1/8 of the total CPU count then tell them how many volumes/engine/replicas can be used per node. Since it would be hard for the user to adjust the value later.

**Comment by yasker** [comment]
Done. The doc has been updated, and the setting description.
