### ISSUE TITLE
[Question] Excuse me, I want to install longhorn without docker and k8s, what should  I do?

### ISSUE THREAD

**Issue by gmle** [longhorn/longhorn#2022]

**Comment by yasker** [comment]
Longhorn is built on top of K8s. Without Kubernetes, you might able to use the Longhorn engine separately, but you will need to do the orchestration yourselves.

**Comment by gmle** [comment]
> Longhorn is built on top of K8s. Without Kubernetes, you might able to use the Longhorn engine separately, but you will need to do the orchestration yourselves.

Thank u for your reply, Am compiling these modules.
