### ISSUE TITLE
[BUG] UI does not resize correctly validate volume resizes under 1Gi

### ISSUE THREAD

**Issue by dbaker-rh** [longhorn/longhorn#2025]
**Describe the bug**

Recently, a change went into the code to permit volume support under 1Gi in size.  The corresponding changes in the UI to support resizing these volumes was not recognized to be needed.

Resizing a volume of, e.g., 256**Mi** will prompt for a minimum resize of 256**Gi** in the UI.

Bug exists in the master branch.  Does not exist in current 1.0.2 release.

**To Reproduce**

kubectl create .... to create a 256Mi volume.

In the longhorn ui, try to "Expand Volume". The Size gets prefilled as "256" with units fixed as Gi.

If I attempt to resize to "0.5" Gi, an error shows, "Size should be larger than 256Gi".

TLDR - I created a 256**Meg** volume.  The UI seems to believe it is 256**Gig** and requires the new size to be greater than this value, not it's actual size.

**Expected behavior**

UI resizes should respect that volumes can exist under 1Gi in size, and offer appropriate resize options.

**Log**

n/a - UI only

**Environment:**

 - Longhorn version: master
 - Kubernetes version: k3s v1.19.4+k3s1
 - Node config
   - OS type and version: k3os
   - CPU per node: amd64 / arm64
   - Memory per node: n/a
   - Disk type: n/a
   - Network bandwidth and latency between the nodes: gigabit ethernet
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): bare metal

**Additional context**

Resizing via kubectl edit pvc/... works as expected. The issue only appears to be in the web ui.

**Comment by khushboo-rancher** [comment]
Validated with the UI image `wangsiye/longhorn-ui:ee5ab96`

The volume size is converted in Gi and shown. If a volume is created with `10` Mi then it is shown as `0.00976563` Gi on the longhorn UI.
However the frontend should round up the size provided to expand the volume to multiples of 512 to make sure volume get expanded successfully.

**Comment by khushboo-rancher** [comment]
Validated with longhorn-UI `bad9258`

Validation - **Fail**

1. The scenario of expanding the size lower than 1 Gi - Pass

The below scenario fails
1. User is able to create less than 10 Mi Volume from Longhorn UI. As per https://github.com/longhorn/longhorn/issues/357, the minimum size to create a volume in 10 Mi

**Comment by khushboo-rancher** [comment]
Verified with longhorn-ui `773e09b`

Validation - **Pass**

1. The creation of volume in MI/GI from Longhorn UI works fine.
2. Expanding of the volume in MI/GI from Longhorn UI works fine.
