### ISSUE TITLE
[BUG] Update CSI Driver details in the longhorn docs.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2027]
**Describe the bug**
Update CSI Driver details in the longhorn doc page https://longhorn.io/docs/1.0.2/concepts/#13-csi-driver

**Comment by yasker** [comment]
CSI driver part (https://v1-1-0.longhorn.io/docs/1.1.0/concepts/#13-csi-driver) has been updated to refer to https://v1-1-0.longhorn.io/docs/1.1.0/advanced-resources/deploy/airgap/ , which contains the latest information regarding the airgap installation.
