### ISSUE TITLE
Optimize websocket

### ISSUE THREAD

**Issue by smallteeths** [longhorn/longhorn#2028]
The current version of the websocket pushes frequently, and the front-end cannot tell if the data is updated or not, and the page is re-rendered every time it is pushed.

Can longhorn refer to the way Rancher websocket is implemented. Returning an empty object when there is no data change

**Comment by yasker** [comment]
Depends on #791

**Comment by innobead** [comment]
@smallteeths Is this still a valid issue after several WS improvements in the previous releases?

**Comment by smallteeths** [comment]
> @smallteeths Is this still a valid issue after several WS improvements in the previous releases?

I will close this issue, Ws has been optimized.
