### ISSUE TITLE
[FEATURE] Help user to install dependencies when installing Longhorn

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2033]
If we decide to install open-iscsi dependency, we need to do more investigation to ensure we have a way to workaround the potential Helm chart installation failure due to initContainer failed to install open-iscsi package.

For RWX volumes, we also require NFS client on the node. We can include it here as well.

Ref: https://github.com/longhorn/longhorn/issues/1741#issuecomment-724183156

**Comment by yasker** [comment]
I am still concerned about automated installation for dependencies. I don't want Helm installation to fail unnecessarily. For the first step, let's update the [yaml](https://github.com/longhorn/longhorn/tree/master/deploy/iscsi) to install `nfs-common`(NFS client) as well. Need to update the doc as well.

**Comment by cclhsu** [comment]
Have update/add manifest for iscsi/nfs (#2210, #2211).  I am currently exploring using helm installation.

**Comment by yasker** [comment]
@cclhsu Can you file out the checklist before moving the issue to Merged? Thanks.

**Comment by khushboo-rancher** [comment]
The Yaml files for `iscsi` and `nfs` installation are validated with https://github.com/longhorn/longhorn/issues/2058 and https://github.com/longhorn/longhorn/issues/1741.

We should be good to close this.
@yasker @cclhsu anything specifically needs to be validated with this one?
