### ISSUE TITLE
[BUG] Uninstall Job should remove all Longhorn resources (CRDs, PodSecurityPolicies, ClusterRoles, and ClusterRolebindings)

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#2035]
**Describe the bug**
see title

**To Reproduce**
1. install Longhorn using Helm Chart
2. uninstall Longhorn

**Expected behavior**
All Longhorn related resources should be deleted

**Log**
N/A

**Environment:**
 - Longhorn version: `master` & `1.0.2`
 - Kubernetes version: 1.18
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**
- Longhorn `v1.0.2`: CRDs, PodSecurityPolicies, ClusterRoles, and ClusterRolebindings are not deleted
- Longhorn `master`: CRDs are not deleted

**Comment by yasker** [comment]
I am not sure if CRDs should be cleaned up though. Rancher chart (2.5) seems deals with it differently. CC @shuo-wu

**Comment by shuo-wu** [comment]
This CRD not-clean-up issue is caused by the annotation `helm.sh/resource-policy: keep` introduced in #1818.

After adding this annotation, the CRD will be retained not only during the upgrade but also during the deletion. And I found there is a similar case in the Helm github community: https://github.com/helm/helm/issues/7839#issuecomment-606044441

I will investigate if we can fix this issue via a hook. And maybe we need to put this issue in v1.1.0 first so that users won't be affected. 

---

As for Longhorn installation/uninstallation in Rancher Cluster Explorer, the CRD creation and deletion is handled by a separate sub-project hence we don't need to worry about it.

**Comment by yasker** [comment]
If we cannot delete it automatically (since we don't really know who is installing/uninstalling), we can call it out in the uninstallation doc.

**Comment by joshimoo** [comment]
related for installations outside of the longhorn-system namespace:
https://github.com/longhorn/longhorn/issues/2034

**Comment by shuo-wu** [comment]
> related for installations outside of the longhorn-system namespace:
> #2034

As I mentioned in that issue, Helm 3 won't clean up the namespace during the uninstallation. I am not sure if the cleanup failure of the resource except for CRD is related to this namespace setting issue.

**Comment by shuo-wu** [comment]
Now all resources including CRDs will be cleaned up successfully via `helm` or Rancher Cluster Manager App for `v1.0.x` and `master`. I cannot reproduce the case that `PodSecurityPolicies, ClusterRoles, and ClusterRolebindings are not deleted in Longhorn v1.0.2`

My test step:
1. Install Longhorn via `helm install` or Rancher Cluster Manager App 
2. Wait for Longhorn running.
3. Uninstall Longhorn via `helm uninstall` or Rancher Cluster Manager App 
4. Verify all kinds resources are removed.

**Comment by yasker** [comment]
@meldafrawi can you confirm this is the case?

**Comment by meldafrawi** [comment]
I can confirm that all resources are removed, except for CSI services along with longhorn-namespace

```
longhorn-system   service/csi-attacher           ClusterIP   10.43.49.79     <none>        12345/TCP                9m33s
longhorn-system   service/csi-provisioner        ClusterIP   10.43.200.170   <none>        12345/TCP                9m32s
longhorn-system   service/csi-resizer            ClusterIP   10.43.205.40    <none>        12345/TCP                9m32s
longhorn-system   service/csi-snapshotter        ClusterIP   10.43.219.54    <none>        12345/TCP                9m31s
```


Steps to reproduce:
1. Clone git@github.com:longhorn/longhorn.git
2. Create longhorn-system namespace
3. Install Longhorn using Helm: `helm install longhorn ./chart --namespace longhorn-system`
4. Wait for Longhorn to be running
5. Uninstall Longhorn `helm install longhorn  --namespace longhorn-system`
6. Check all resources in all namespaces and filter using longhorn: `kubectl get all --all-namespaces  | grep -i longhorn`

- Also services will not be deleted in case of installing Longhorn using Rancher App

**Comment by PhanLe1010** [comment]
`longhorn-namespace` cannot be deleted because it is not created by Longhorn
I will make a PR to delete all services.

**Comment by yasker** [comment]
Thanks @PhanLe1010 . Yes, services should be removed as a part of uninstallation.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn version: v1.1.0-RC3
