### ISSUE TITLE
[BUG] [Rancher 2.5 Cluster Explorer UI] Longhorn Uninstall get stuck, Longhorn UI deployment will not be removed.

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#2039]
**Describe the bug**
see title

**To Reproduce**
1. Create new chart repository using Longhorn chart from v1.1.0 branch -> Rancher 2.5 Cluster Explorer UI
2. Deploy Longhorn app
3. Try to uninstall Longhorn 

**Expected behavior**
Longhorn UI Deployment should be removed, and uninstall job should finish uninstalling Longhorn app.

**Log**
![image](https://user-images.githubusercontent.com/18232258/101216147-afa14a00-3687-11eb-8861-b0e2c2d2b4d2.png)

**Environment:**
 - Longhorn version: master
 - Kubernetes version: 1.19
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**
Using Rancher 2.5 Cluster Explorer UI

**Comment by yasker** [comment]
Rancher 2.5 requires a different format of Helm packaging.

**Comment by yasker** [comment]
In fact, @shuo-wu can do document the changes we need to make to make Rancher 2.5 works? It seems wrong that anyone has to maintain two Helm charts. I am wondering if we can solve it on the Rancher side.

**Comment by meldafrawi** [comment]
Can't reproduce again

**Comment by yasker** [comment]
@PhanLe1010 Wrong issue?

**Comment by PhanLe1010** [comment]
Oops. I am sorry
