### ISSUE TITLE
[FEATURE] Include more non-default columns in web ui volume list

### ISSUE THREAD

**Issue by dbaker-rh** [longhorn/longhorn#2040]
**Is your feature request related to a problem? Please describe.**

There is data available in the per-volume information page which is not visible in the main volume listing, even as a non default column.

The two that come immediately to mind are number of replicas and data locality.

**Describe the solution you'd like**

More columns to be available in the volume list, corresponding to all data that can be viewed when examining an individual volume.

**Describe alternatives you've considered**

My alternative is to not use the UI at all.  For example:

kubectl -n longhorn-system get volumes.longhorn.io -o json | jq '.items[] | { "name": .metadata.name, "replicas": .spec.numberOfReplicas, "pvcName": ( .status.kubernetesStatus.namespace + ": " + .status.kubernetesStatus.pvcName) }'

**Additional context**

I think this will have little benefit to a stable, installed cluster.  However, for new cluster installs especially by users who are new to longhorn, I think it may greatly reduce the learning curve required to get familiar with the product.

**Comment by yasker** [comment]
For v1.1.0 we've added the support for custom columns, but we do miss a few fields like the number of replicas and data locality.

@PhanLe1010 Can you follow up and see what other fields we can add to the volume overview page?

**Comment by PhanLe1010** [comment]
How about `revisionCounterDisabled`, `recurringJobs`, and `share` (`RWX`) ?

cc @yasker @shuo-wu

**Comment by yasker** [comment]
`share` should be there. `Recurring Jobs` is already in the `Scheduled` column. We don't need `revisionCounter` disabled since it's more of an implementation detail.

**Comment by shuo-wu** [comment]
And it seems that the field `frontend` is not there. We may need to add it for custom columns.

**Comment by PhanLe1010** [comment]
So the list is: 
1. number of replicas
1. data locality
1. share
1. frontend

**Comment by yasker** [comment]
The endpoint implies what is the front end, since blockdev and iscsi havr different formats for front end.

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master `12/11/2020`

Validation - **Pass**

Option to select the column Replicas, Data Locality and Access Mode is available in `Custom Column`.
<img width="1779" alt="Screen Shot 2020-12-11 at 5 45 38 PM" src="https://user-images.githubusercontent.com/60111667/101969491-701fb400-3bd9-11eb-8f2d-a03d91a244d4.png">
