### ISSUE TITLE
[Question] K3os/RKE2 auto-deploy manifests?

### ISSUE THREAD

**Issue by gnoejuan** [longhorn/longhorn#2042]
Which files are needed to autodeploy in RKE2 and/or K3os? I see longhorn/chart/[chart.yaml | questions.yaml | values.yaml] and longhorn/deploy/[longhorn.yaml | backupstores/minio-backupstore.yaml | backupstores/nfs-backupstores.yaml | iscsi/longhorn-iscsi-installation.yaml]. Would it be possible to improve the documention since the products are from the same company?

**Comment by yasker** [comment]
You can install it as a regular Helm chart or yaml following the instruction at https://longhorn.io/docs/1.0.2/deploy/install/ .

**Comment by gnoejuan** [comment]
I suppose this means I need to understand Helm more than I currently do. Thanks!
