### ISSUE TITLE
Why does the system always have degraded volumes？

### ISSUE THREAD

**Issue by hangnu** [longhorn/longhorn#2047]
We deployed longhorn v1.0.2 successfully，but there always are some volumes degrading in the system.

Never the volumes are all healthy；

When we reboot pods, there will even more volumes go to downgrade, like 30%, and system has to rebuild replicas crazy

**Comment by PhanLe1010** [comment]
There are several reasons that lead to degraded volumes. The most common reason is the cluster doesn't meet the minimum resource requirement. You can take a look at this report, https://github.com/longhorn/longhorn/issues/1691#issuecomment-729633995 , to see if your cluster experiences this issue. 

> When we reboot pods, there will even more volumes go to downgrade, like 30%, and system has to rebuild replicas crazy

Do you mean that you reboot the nodes? If you reboot a node, Longhorn will see that the replica on the node is failed and try to rebuild a new one on other nodes. Longhorn has to do that to make sure your volumes are HA. If your application already handles replication and you don't need Longhorn volume to be HA, you can set the number of replica for Longhorn volume to be 1. Be aware that you will lose the volume's data in case the only replica gets corrupted.
