### ISSUE TITLE
Option of creating RWX volume from the Longhorn UI

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2048]
There should be an option of creating RWX volume from Longhorn UI. As of RWX feature in v1.1.0, Longhorn supports the RWX volume creation if created using storage class

**Is your feature request related to a problem? Please describe.**
If a volume is created using Longhorn UI and PV/PVC (with RWX enabled) are created later, the volume fails to attach to the pod.
```
AttachVolume.Attach failed for volume "pv-rwx-test1" : rpc error: code = FailedPrecondition desc = requested multi node use for non shared volume volume-test-1
```

**Comment by joshimoo** [comment]
I added an `accessMode` field to the volume api object, as well as an updateAccessMode api endpoint.
The valid values for the accessMode are 
- `rwo` for the label `ReadWriteOnce` 
- `rwx` for the label `ReadWriteMany`

All volume creation needs to expose dropdown fields (restore, create volume to specify  this access mode, the field should be below the data locality field. Example screenshots below.

**Comment by joshimoo** [comment]
![create-volume](https://user-images.githubusercontent.com/1287163/101835526-36e53680-3b3c-11eb-98b1-e359a9c9ac15.png)
![restore-volume](https://user-images.githubusercontent.com/1287163/101835530-377dcd00-3b3c-11eb-8624-760b345d63ca.png)

**Comment by joshimoo** [comment]
@smallteeths For the labels you can also use rwo/rwx depending on what looks better from a ui standpoint.

**Comment by joshimoo** [comment]
There should be 3 places where this ui modification is necessary:
- create volume
- restore volume
- creation of a dr volume

**Comment by khushboo-rancher** [comment]
We should also handle the PV/PVC creation with RWX/RWO form longhorn UI.

**Comment by joshimoo** [comment]
I will create the pv/pvc based on the volumes access mode.

**Comment by joshimoo** [comment]
- add the ability to change the access mode
- display the access mode when creating pvc

**Comment by khushboo-rancher** [comment]
Verified with Longhorn master - `12/13/2020`

Validation - **Pass**

The option to select AccessMode is available for creation of volume, restoration volume (with single and multiple volumes) and creation of DR volume.
<img width="705" alt="Screen Shot 2020-12-13 at 10 24 52 PM" src="https://user-images.githubusercontent.com/60111667/102047399-10b8d400-3d92-11eb-95cc-c1185d8db2bb.png">
<img width="619" alt="Screen Shot 2020-12-13 at 10 25 49 PM" src="https://user-images.githubusercontent.com/60111667/102047489-2e863900-3d92-11eb-95a0-a84ab39556e7.png">
<img width="541" alt="Screen Shot 2020-12-13 at 10 26 21 PM" src="https://user-images.githubusercontent.com/60111667/102047529-4067dc00-3d92-11eb-9a70-7801cb875d6d.png">


The option to switch the AccessMode is also available with single and multiple volume action. The Access Mode is available on the volume page details.
<img width="542" alt="Screen Shot 2020-12-13 at 10 27 00 PM" src="https://user-images.githubusercontent.com/60111667/102047582-5a092380-3d92-11eb-9d08-0e0a15e23501.png">

**Comment by yasker** [comment]
Punt the e2e test part into v1.1.1.

**Comment by yasker** [comment]
@khushboo-rancher Does this issue have an end-to-end test that needed to be added?

**Comment by khushboo-rancher** [comment]
I think https://github.com/longhorn/longhorn/issues/2110 will cover the integration test cases for RWX feature. Let's close this and track the automation test with https://github.com/longhorn/longhorn/issues/2110
