### ISSUE TITLE
[Question] performance and stability of longhorn?

### ISSUE THREAD

**Issue by nicktming** [longhorn/longhorn#2050]
**Question**
what about the performance and stability of longhorn ? what is the maximum nodes of single kubernetes cluster do longhorn support ?

**Environment:**
 - Longhorn version:
 - Kubernetes version:
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**

**Comment by yasker** [comment]
You can find our performance and scalability report at https://longhorn.io/blog/performance-scalability-report-aug-2020/ .

So far in our lab, we've tried scaling up to 100 nodes and 900 volumes. You can find more details in the report.
