### ISSUE TITLE
Can replica rebuilding be throttled in any way?

### ISSUE THREAD

**Issue by IJOL** [longhorn/longhorn#2053]
We found replica rebuilding a little slow given our hardware environment ( a private Gbit ethernet connection in between nodes) and all using only SSD drives, a 15 Gb replica rebuild, lasts for about 6 minutes.. an equivalent operation between the nodes using SCP  lasts in  2:45 minutes  a 50% increase in speed, so I wonder if there is any way to throttle replica, I understand that there will be some overhead by the inner mechanics, but a loss of that much bandwidth seems at least something we need to research further

**Comment by joshimoo** [comment]
@IJOL Do I understand correctly that you are asking whether the replica rebuild can be speed up?
Are you having many instances where a replica rebuild is required?

One reason the replica rebuild is slower than a direct copy, is that we have a verification pass.
We are working on the below issues, to speed up the replica rebuild speed.
- https://github.com/longhorn/longhorn/issues/1948 (improves the verification pass)
- https://github.com/longhorn/longhorn/issues/1304 (reuse existing replica data)
