### ISSUE TITLE
[BUG] Nightly tests failed because the priority class setting was not cleaned up

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2055]
When the priority class test fails, we don't ensure that the custom set priority class setting gets cleared.
But we do have a finalizer on the actual priority class which will remove the priority class from kubernetes.
So all future following tests will fail, since the longhorn components fail to come up.

**Comment by khushboo-rancher** [comment]
Closing this one as the priority clean up is in place now.
Logged https://github.com/longhorn/longhorn/issues/2113 to track the rare integration failure.
