### ISSUE TITLE
[BUG] Volume Attachment Recovery Policy feature conflicts with Pod Deletion Policy

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2060]
We already have the deleting mechanism(https://github.com/longhorn/longhorn/issues/1105). So, we need to consider whether we can safely remove the feature Volume Attachment Recovery Policy which deletes volume attachments on terminating pods on a failed node.

**Comment by innobead** [comment]
cc @joshimoo

**Comment by joshimoo** [comment]
@innobead Thanks, I had missed this, while creating the new issue :)

**Comment by innobead** [comment]
Need to tackle this in 1.1.2 as well, this should be regarded as a bug than an enhancement due to the function conflicting with the pod deletion policy.

**Comment by khushboo-rancher** [comment]
Moving this to implement column as the mount clean up is broken and the fix is being revisited.

**Comment by innobead** [comment]
@khushboo-rancher Please help coordinate the verification and close if this is verified by the latest build. Thanks.

cc @kaxing @meldafrawi

**Comment by joshimoo** [comment]
@khushboo-rancher
VA removal is already present, but for the csi fixes on master https://github.com/longhorn/longhorn-manager/pull/945 need to merged. Everything is already merged for v1.1.2

**Comment by joshimoo** [comment]
@khushboo-rancher https://github.com/longhorn/longhorn-manager/pull/945 has been merged, so the fixes are now also available to test on master.

**Comment by khushboo-rancher** [comment]
Verified with v1.1.2-rc1 and Longhorn-master `07/28/2021`

Validation : **Partially Pass**

The volume attachments are not getting deleted when the node goes down irrespective to the VA setting `wait, never, immediate`.


@joshimoo I'm not sure why the VA setting is still on the Longhorn UI

**Comment by innobead** [comment]
@smallteeths Please help remove this setting from UI. Thanks.

**Comment by PhanLe1010** [comment]
I think the setting is not controlled by the UI. It is returned values from backend. I remembered that Joshua had a reason not to remove it but I couldn't remember the detail.

**Comment by innobead** [comment]
> I think the setting is not controlled by the UI. It is returned values from backend. I remembered that Joshua had a reason not to remove it but I couldn't remember the detail.

@joshimoo only fixed in the backend only to dismiss the setting in 1.1.2, but the user is still able to update the value from UI setting page even though it does not take effect.

We should have a note in the release note and also update the documentation. Removing the rest of things from 1.2.0 at the end.

**Comment by smallteeths** [comment]
Set `setting.definition.type` to `deprecated`, and the front end will hide this setting. This can be changed from the back end. 
@innobead.
