### ISSUE TITLE
task: Longhorn v1.1.0 release chart

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2061]
Need to update Rancher charts for Longhorn v1.1.0 release.

**Comment by shuo-wu** [comment]
The test Chart for Cluster Manager: `https://github.com/shuo-wu/charts/` branch `master`
The test Chart for Cluster Explorer: `https://github.com/shuo-wu/charts/` branch `dev-v2.5`

**Comment by meldafrawi** [comment]
Validated Using the Provided charts: **LGTM**
