### ISSUE TITLE
[BUG] The feature Pod Deletion Policy When Node is Down doesn't work on Kubernetes >= v1.19.0

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2062]
When a node goes down, Kubernetes v1.18 or older versions set the taint `node.kubernetes.io/unreachable:NoExecute` to the failed node. As the result, the pods of StatefulSet and Deployment will have DeletetionTimestamp after 300s (300s because by default Kubernetes automatically adds toleration for `node.kubernetes.io/not-ready` and `node.kubernetes.io/unreachable` with `tolerationSeconds=300` to every pod). Longhorn uses DeletetionTimestamp as an indication to force delete workload pod.

However, Kubernetes v1.19+ does not set the taint `node.kubernetes.io/unreachable:NoExecute` to the failed node. So workload pod doesn't have DeletetionTimestamp after 300s and Longhorn never forces delete it. This breaks the feature Pod Deletion Policy When Node is Down on Kubernetes v1.19+

**To Reproduce**
1. Install Longhorn on a Kubernetes v1.19+ cluster
1. Set `Pod Deletion Policy When Node is Down` to  `delete-both-statefulset-and-deployment-pod`
1. Delepoy a statefulset of 1 pod using Longhorn volume
2. Power down the node of the statefulset pod
3. Wait 1 min, see that K8s only sets this taint on the failed node: `node.kubernetes.io/unreachable:NoSchedule`
4. Wait 10 mins Longhorn never deletes the workload pod

**Expected behavior**
Longhorn should delete the workload pod after 6-7 mins so K8s can restart the workload on a different node

**Additional context**
We need to see if we can wait for upstream K8s to fix the bug or we have to do it ourselves

Some Refs 
https://github.com/kubernetes/kubernetes/issues/97100
https://github.com/kubernetes/kubernetes/pull/89059/commits/b3637c967044460bcf766205e37563d3572d8ac5)
https://github.com/kubernetes/kubernetes/pull/96876

**Comment by yasker** [comment]
This issue is for tracking the Kubernetes v1.19 fix.

**Comment by PhanLe1010** [comment]
Seems that the fix was merged to K8s master

**Comment by yasker** [comment]
@PhanLe1010 Let's wait for the next patch release and test again.

**Comment by Xenwar** [comment]
> @PhanLe1010 Let's wait for the next patch release and test again.

@yasker Any update on this ?

**Comment by PhanLe1010** [comment]
The [Pr](https://github.com/kubernetes/kubernetes/pull/96876) has been merged into Kubernetes v1.21 but v1.21 is not out yet

There are 2 cherry-pick PRs fix for Kubernetes [v1.19](https://github.com/kubernetes/kubernetes/pull/98140) and [v1.20](https://github.com/kubernetes/kubernetes/pull/98168) but they haven't been merged yet.

**Comment by yasker** [comment]
Both PRs fix for Kubernetes [v1.19](https://github.com/kubernetes/kubernetes/pull/98140) and [v1.20](https://github.com/kubernetes/kubernetes/pull/98168) has been merged in. But need to check which release will include those fixes.

**Comment by HubbeKing** [comment]
Looks like the latest set of releases have the fix:
v1.18.16 [Changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#changelog-since-v11816)
v1.19.9 [Changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#changelog-since-v1198)
v1.20.5 [Changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1204)

These all list the bugfix for the NoExecute taint for failed nodes.

**Comment by innobead** [comment]
Closing, because the issue was already fixed at upstream and upstream releases out as well.

**Comment by innobead** [comment]
@PhanLe1010 To make sure the fix does resolve the feature impact. Please help reverify again by using the latest K8s upstream release to see if this issue has been fixed correctly. Thanks.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn v1.1.1-rc1

Validation - **Pass**

Validated with K8s v1.20.5, if the setting `Pod Deletion Policy When Node is Down` is set to `delete-both-statefulset-and-deployment-pod`, on power down the node the pod moves to another node.
