### ISSUE TITLE
[BUG] failed to launch pod using longhorn v1.1.0-rc1 on k3os

### ISSUE THREAD

**Issue by guangbochen** [longhorn/longhorn#2063]
**Describe the bug**
failed to lauch pod using longhorn v1.1.0-rc1 on k3os with v0.19.4-dev.5

**To Reproduce**
install the longhorn using 
1. `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.1.0/deploy/longhorn.yaml`
1. create pod and VM following the https://rancher.com/docs/k3s/latest/en/storage/ example

**Expected behavior**
the pod should be running successfully with mounted PVC 

**Log**
```
Warning  FailedMount  26s   kubelet            MountVolume.SetUp failed for volume "pvc-d3a022c9-86d0-48d6-bd4e-0fe155c572cb" : rpc error: code = Internal desc = Failed to create nsenter executor, err: rpc error: code = Internal desc = Failed to create nsenter executor, err: unable to find sh
```

**Environment:**
 - Longhorn version:
 - Kubernetes version:
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**
as per the error message `Failed to create nsenter executor, err: unable to find sh`, this is because the k3os is using a symlink of `sh` from `/bin/busybox`, and when the sh path is mounted to the `longhorn-csi-plugin` container it will be failed to find the correct path within in container's rootfs.
```
k3os-7mh22 [~]# which sh
/usr/bin/sh
k3os-7mh22 [~]# ls -la /usr/bin/sh
lrwxrwxrwx 1 root root 12 Oct 21 09:23 /usr/bin/sh -> /bin/busybox
```
link to k3os issue https://github.com/rancher/k3os/issues/628

**Comment by yasker** [comment]
@guangbochen can you help to validate the issue? It should be fixed in the longhorn master branch now.

**Comment by guangbochen** [comment]
verified using k3os-v0.19.4-dev5 and it works as expected.
```
NAME                                 READY   STATUS    RESTARTS   AGE
harvester-network-controller-2zpj6   1/1     Running   0          66m
virt-operator-7b99b7bbdb-fwtxg       1/1     Running   0          66m
virt-api-59bf84667c-flw5q            1/1     Running   0          65m
virt-api-59bf84667c-2pqvv            1/1     Running   0          65m
minio-1                              1/1     Running   0          63m
minio-2                              1/1     Running   0          63m
minio-3                              1/1     Running   0          63m
minio-0                              1/1     Running   0          63m
virt-handler-z2pzr                   1/1     Running   0          64m
cdi-operator-6c7bd7b867-9b8fp        1/1     Running   0          66m
virt-controller-7bfcdc8bb9-bvfq2     1/1     Running   1          64m
virt-controller-7bfcdc8bb9-9jxnt     1/1     Running   1          64m
cdi-apiserver-5d7db448bf-zl4wr       1/1     Running   0          51m
cdi-uploadproxy-5864bf9794-k6pmn     1/1     Running   0          50m
cdi-deployment-78985784-jm5gr        1/1     Running   0          50m
harvester-86bdcf9df7-sjfnr           1/1     Running   0          2m44s
svclb-harvester-g4b7h                1/1     Running   0          2m21s
```

**Comment by yasker** [comment]
Close according to https://github.com/longhorn/longhorn/issues/2063#issuecomment-743958684
