### ISSUE TITLE
[BUG] ShareManager pod doesn't restart on terminating the node when both sharemanager and workload pod is on the same node

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2066]
**Describe the bug**
ShareManager pod doesn't restart on terminating the node when both ShareManager and workload pod is on the same node.

**To Reproduce**
1. Deploy Longhorn v1.1.0-rc1 on a K3s cluster of 3 nodes.
2. Create a StatefulSet (1 pod) with RWX volume. Make sure both the shareManager pod and the workload is attached to the same node.
3. Power down the attached node.
4. The ShareManager doesn't get restarted and the workload pod stuck in `terminating` state.

**Logs:**
[longhorn-support-bundle_432fcb24-4f12-4d8c-a037-f3caf95d528a_2020-12-09T07-08-14Z.zip](https://github.com/longhorn/longhorn/files/5664227/longhorn-support-bundle_432fcb24-4f12-4d8c-a037-f3caf95d528a_2020-12-09T07-08-14Z.zip)
Time of error : ~ 2020-12-09 6:55:00 UTC
Volume name - pvc-852ea68c-340a-4fc1-a0d0-75e67508f4ac
Workload name - wk-1

**Environment:**
 - Longhorn version: v1.1.0-rc1
 - Kubernetes version: v1.19.4+k3s2
 - Node config
   - OS type and version: ubuntu 18.04
   - CPU per node: 2 vcpu
   - Memory per node: 4 GB
   - Disk type: EBS
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS

**Comment by khushboo-rancher** [comment]
This could be because of the setting `Pod Deletion Policy When Node is Down`. The setting `Pod Deletion Policy When Node is Down` was `do-nothing` in this cluster, so the workload stuck in terminating state.

**Comment by joshimoo** [comment]
From the logs it looks like this is not a bug, there was no longer an active workload.
Which meant that the kubernetes_pv_controller set the lastPodRef, here: 
https://github.com/longhorn/longhorn-manager/blob/master/controller/kubernetes_pv_controller.go#L490

This means that there is no need for the share manager any longer and the share manger went into the stopped state and detached the volume. Can be seen in the logs shareState=stopped, @khushboo-rancher can you file an issue to include the sharemanager resources during support bundle generation?

**Comment by joshimoo** [comment]
@khushboo-rancher once you scale the workload up or create a new workload, new deployment refering the same pvc, the share manager should be coming up again, correct?

**Comment by joshimoo** [comment]
From the pods.yaml the sharemanager pod: pvc-852ea68c-340a-4fc1-a0d0-75e67508f4ac also no longer shows up so it correctly got force deleted as well.

**Comment by khushboo-rancher** [comment]
@joshimoo Yes, on scaling up the workload, the ShareManager came up. I think, we can close this.

**Comment by khushboo-rancher** [comment]
Closing this. Not a bug.
