### ISSUE TITLE
 [BUG] Unable to take snapshots/backups

### ISSUE THREAD

**Issue by hijak** [longhorn/longhorn#2068]
**Describe the bug**
I am unable to take snapshots due to connection to engine timeout

**To Reproduce**
1. Go to longhorn ui
2. Click on take snapshot
3. Perform a snapshot
```
fail to create snapshot: error creating snapshot '': Timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.0.2/longhorn [--url 10.42.0.171:10004 snapshot create ], output , stderr, , error <nil>
```
**Expected behavior**
snapshot suceeds

**Log**
fail to create snapshot: error creating snapshot '': Timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.0.2/longhorn [--url 10.42.0.171:10004 snapshot create ], output , stderr, , error <nil>

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: k3s 

 - Underlying Infrastructure: Baremetal

**Additional context**
was working find until 6 days ago no major changes inbetween

**Comment by yasker** [comment]
Hi @hijak 

Can you provide a support bundle? You can find the button to generate one at the bottom of the UI. Once generated, you can attach it to the issue, or send us to `longhorn-support-bundle@rancher.com`.

**Comment by hijak** [comment]
@yasker thank you i have sent the support bundle to the email
