### ISSUE TITLE
task: CSI Sanity check

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2076]
Use this issue to track the fix for CSI sanity check.

Ref: https://github.com/longhorn/longhorn/issues/1978

**Comment by c3y1huang** [comment]
Ok not sure if this should be moved to review since [this PR](https://github.com/longhorn/longhorn-manager/pull/825) skipped 5 tests.

**Comment by c3y1huang** [comment]
Move this to the review stage for https://github.com/longhorn/longhorn-manager/pull/825 to make the current issue status less confusing.

@joshimoo feel free to change the stage back to implement if you think we should implement the 5 skipped tests.

**Comment by c3y1huang** [comment]
The success of csi-sanity test is dependent on https://github.com/longhorn/longhorn/issues/2270

**Comment by meldafrawi** [comment]
will track the testing in https://github.com/longhorn/longhorn/issues/2270#issuecomment-812095144
