### ISSUE TITLE
[BUG] ShareManager pod fails to come up if the node is deleted

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2079]
**Describe the bug**
If the node where the share-manager pod exists is deleted from the cluster and the workload pod is on another node, the nfs-server fails to come up.

**To Reproduce**
1. Deploy longhorn v1.1.0-master on a K8s cluster ( 1 etcd/control plane, 3 worker)
2. Create an RWX volume. Make sure the workload and share-manager are on different nodes.
3. Delete the share-manager node from the cluster.
4. The share-manager moves to another node but fails to come up.

**Log**
```
time="2020-12-11T02:08:16Z" level=info msg="starting RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
time="2020-12-11T02:08:16Z" level=info msg="ending RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
time="2020-12-11T02:08:16Z" level=warning msg="waiting with nfs server start, volume is not attached" volume=pvc-a8218dc5-1fc2-442c-b3b7-756110e63cc8
time="2020-12-11T02:08:21Z" level=warning msg="waiting with nfs server start, volume is not attached" volume=pvc-a8218dc5-1fc2-442c-b3b7-756110e63cc8
```
[longhorn-support-bundle_0ed3aabf-8cae-4814-a65c-a86904b7411e_2020-12-11T02-19-23Z.zip](https://github.com/longhorn/longhorn/files/5676745/longhorn-support-bundle_0ed3aabf-8cae-4814-a65c-a86904b7411e_2020-12-11T02-19-23Z.zip)
Share-manager pod - pvc-a8218dc5-1fc2-442c-b3b7-756110e63cc8

**Environment:**
 - Longhorn version: v1.1.0-master
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
 - Node config
   - OS type and version: ubuntu 18.04
   - CPU per node: 2 vcpus
   - Memory per node: 4 GB
   - Disk type(e.g. SSD/NVMe): SSD

**Additional context**
Other rwx volumes are successfully created in the same cluster.

**Comment by khushboo-rancher** [comment]
This one is observed with longhorn-master. I'm not sure if it is reproducible all the time or it depends on the fact that the share-manager and workload pods are on different nodes.

**Comment by joshimoo** [comment]
This is caused by the volume controller not being able to handle it's own detach/attach flow if a different node is requested.
I will make this more robust in the share manager for now, 

@yasker For 1.2 we really should refactor the volume controller so it can handle it's own detach/attach when a different node is specified in the spec. It doesn't make sense that the client needs to manage the detach/attach statemachine.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn v1.1.0-rc2

Validation - **Pass**

**Scenario 1** - ShareManager pod deleted, `Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly` enabled
1. I had workload on node-1 and shareManager on node-2.
2. Deleted the node-2.
3. The shareManager pod moved to node-3, started the nfs-server once the volume was attached.
4. The workload pod got recreated because of the `Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly` setting.
5. The shareManager pod recreated on the same node again because the workload pod was recreated.
6. Validated the data in the workload pod.

**Scenario 2** - ShareManager pod deleted, `Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly` disabled
1. I had workload on node-1 and shareManager on node-2.
2. Deleted the node-2.
3. The shareManager pod moved to node-3, started the nfs-server once the volume was attached.
4. Validated the data in the workload pod.

**Scenario 1** - ShareManager pod and workload pod on the same node and node deleted
1. I had workload and shareManager on node-1.
2. Deleted the node-1.
3. Workload pod moved to node-2 and shareManager pod got recreated.
4. Validated the data in the workload pod.
