### ISSUE TITLE
 [BUG] Service account secret mount spam as a result of longhorn-manager restarts caused by missing iscsi pre-req

### ISSUE THREAD

**Issue by axeal** [longhorn/longhorn#2083]
**Describe the bug**

As a result of `mountPropagation: Bidirectional` on the `/var/run` hostPath mount for `longhorn-manager`, introduced in `v1.0.2` there are growing number of `/var/run/secrets/kubernetes.io/serviceaccount` mounts on nodes upon `longhorn-manager` Pod restarts. Continued restarts will increase System CPU usage until the Docker runtime becomes unresponsive and the nodes down in k8s. This will occur if the `open-iscsi` pre-req is missing on cluster nodes, meaning any user who installs longhorn into a cluster without fulfilling this pre-req will bring down their cluster after a short period.

**To Reproduce**
Steps to reproduce the behaviour:
1. Deploy longhorn on a cluster with missing `open-iscsi` pre-req. I tested in RancherOS v1.5.5 and Ubuntu 18.04 (after running `apt uninstall -y open-iscsi` on cluster nodes).
2. Observe `longhorn-manager` Pods in Crashloopbackoff due to failing environment check.
3. Execute `df` on cluster nodes and observe duplicate `/var/run/secrets/kubernetes.io/serviceaccount` mounts. As the `longhorn-manager` repeatedly restarts the duplicate mounts will grow, and eventually System CPU usage as observed with `top` will grow until the Docker runtime becomes unresponsive and `kubelet` cannot communicate with the runtime.

**Expected behavior**
Deploying longhorn with missing pre-req does not freeze nodes in the cluster. 

**Log**

As expected in the event of missing open-iscsi pre-req, `longhorn-manager` logs show:

```
time="2020-12-08T09:59:38Z" level=error msg="Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host"
time="2020-12-08T09:59:38Z" level=fatal msg="Error starting manager: Environment check failed: Failed to execute: nsenter [--mount=/host/proc/1621/ns/mnt --net=/host/proc/1621/ns/net iscsiadm --version], output , stderr, nsenter: failed to execute iscsiadm: No such file or directory\n, error exit status 1"
```

**Environment:**
 - Longhorn version: v1.0.2
 - Kubernetes version: v1.17.14 and v1.19.4
 - Node config
   - OS type and version RancherOS v1.5.5/Ubuntu 18.04.5
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): vSphere/Digital Ocean

**Additional context**

Same behaviour, different trigger of longhorn-manager restarts as https://github.com/longhorn/longhorn/issues/1877

Behaviour is not shown when removing `mountPropagation: Bidirectional` on the `/var/run` hostPath.

**Comment by joshimoo** [comment]
Thank you for reporting this, for 1.1 we try to install iscsid on the host via an init container.
We still want to investigate the secret mount spam.

**Comment by PhanLe1010** [comment]
Thanks @axeal for reporting. We removed https://github.com/longhorn/longhorn-manager/pull/801 in v1.1.0 release

**Comment by yasker** [comment]
Close this since the bind mount of `/var/run` has been removed in the v1.1.0 release.

Feel free to reopen if you experience the same issue again in v1.1.0 release.
