### ISSUE TITLE
[BUG] The share-manager pod stuck in terminating state if the workload is deleted or scaled down

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2087]
**Describe the bug**
The share-manager pod stuck in terminating state if the workload is deleted

**To Reproduce**
1. Deploy Longhorn on a K8s cluster.
2. Create a PVC with `rwx` option.
3. Create a daemonSet using the PVC created in step 2.
4. Once all the pods of the daemonSet is up, delete the daemonSet.
5. The share-manager pod stuck in `terminating` state.

**Log**
[longhorn-support-bundle_07d9aad3-6b29-48e9-9113-8600d4705818_2020-12-12T00-24-17Z.zip](https://github.com/longhorn/longhorn/files/5682204/longhorn-support-bundle_07d9aad3-6b29-48e9-9113-8600d4705818_2020-12-12T00-24-17Z.zip)

**Environment:**
 - Longhorn version: Longhorn-master `12/11/2020`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
 - Node config
   - OS type and version: Ubuntu

**Additional Context**
The workaround is to delete the share-manager pod manually.

**Comment by khushboo-rancher** [comment]
Happening with scaling down also, raising the priority.

**Comment by joshimoo** [comment]
Thanks for reporting, 
I broke this as part of https://github.com/longhorn/longhorn/issues/2086
I forgot to change the delete call to use the new share-manager prefix for the pod.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn v1.1.0-rc2

Validation - **Pass**

On deletion or scaling down the workload, the ShareManager pod is terminating successfully.
