### ISSUE TITLE
[BUG] Cannot list backups from a in-cluster NFS service url in SLES 15 SP2

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2088]
**Describe the bug**
On SLES 15 SP2 + RKE setup, Longhorn cannot list backups if the backup target is an NFS server exposed by an in-cluster service and the URL of the service is set in Longhorn UI

**To Reproduce**
1. Create a cluster with SLES 15 SP2 + RKE
2. Deploy a NFS server and create a service to expose it by: 
   ```
   kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/backupstores/nfs-backupstore.yaml
   ```
3. Set backup target to `nfs://longhorn-test-nfs-svc.default:/opt/backupstore` in Longhon UI
4. Go to backup store, see error in UI and manager pod:
   ```
   [longhorn-manager-nqsw7] time="2020-12-12T01:38:04Z" level=warning msg="backup store monitor: failed to list backup volumes in nfs://longhorn-test-nfs-svc.default:/opt/backupstore: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master/longhorn [backup ls --volume-only nfs://longhorn-test-nfs-svc.default:/opt/backupstore], output Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mount.nfs4: Failed to resolve server longhorn-test-nfs-svc.default: Name or service not known\n, error exit status 32\n, stderr, time=\"2020-12-12T01:38:04Z\" level=error msg=\"Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mount.nfs4: Failed to resolve server longhorn-test-nfs-svc.default: Name or service not known\\n, error exit status 32\"\n, error exit status 1" 

   ```

**Expected behavior**
Longhorn is able to list the backups

**Environment:**
 - Longhorn version: master 12/11/2020
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE 2.0, K8s v1.19.4
 - Node config
   - OS type and version: SUSE Linux Enterprise Server 15 SP2
   - CPU per node: 2
   - Memory per node: 4GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth and latency between the nodes: NA
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS

**Additional context**
It seems that Longhorn manager cannot find the in-cluster NFS service by its URL:

Running these commands inside Longhorn manager pods:
```
ping longhorn-test-nfs-svc.default
ping: longhorn-test-nfs-svc.default: Name or service not known

root@longhorn-manager-nqsw7:/# mount -t nfs4 -o nfsvers=4.2 longhorn-test-nfs-svc.default:/opt/backupstore /tmp/test
mount.nfs4: Failed to resolve server longhorn-test-nfs-svc.default: Name or service not known
```

But  nslookup works:
```
root@longhorn-manager-nqsw7:/# nslookup longhorn-test-nfs-svc.default
Server:         10.43.0.10
Address:        10.43.0.10#53

Name:   longhorn-test-nfs-svc.default.svc.cluster.local
Address: 10.42.2.36
```

**Comment by yasker** [comment]
All the services DNS endpoint cannot be found in the Longhorn manager pod.

**Comment by yasker** [comment]
It caused by Longhorn manager Pod has bind-mounted `/var/run` directory on the host, which result in `/var/run/nscd/` leaking into the pod, and caused the DNS search failure.

I cannot recall why we need `/var/run`. Running integration test to verify that we can remove it.

**Comment by khushboo-rancher** [comment]
Validated with Longhorn-Master `12/14/2020`

Validation - **Pass**

Longhorn is able to list the backups from NFS backup server.

Ran the integration tests on the SLES 15- SP2, All tests passed.

**Comment by Bwvolleyball** [comment]
I'm on Longhorn v1.1.0, Baremetal, k3s, but I'm still getting this exact error.

```
Failed to resolve server nfs-service: Name or service not known\n, error exit status 32\n, stderr, time=\"2020-12-24T06:51:23Z\" level=error msg=\"Cannot mount nfs nfs-service:/mnt/toshiba/nfshare: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 nfs-service:/mnt/nfshare /var/lib/longhorn-backupstore-mounts/nfs-service/mnt/nfshare], output mount.nfs4: Failed to resolve server nfs-service: Name or service not known\\n, error exit status 32\"\n, error exit status 1"
```

This backup worked exactly once for me, and now it can't find the service for my NFS server anymore.

**Comment by PhanLe1010** [comment]
@Bwvolleyball 

Can you check to make sure that you can access the `nfs-service` from a different pod in the cluster. e.g `ping` the `nfs-service` enpoint from a different pod in a different namespace. If you cannot ping the `nfs-service`, it is something wrong with the `nfs-service`. If you can ping the `nfs-service`, can you check the `Backup Target` setting in Longhorn UI. It should has a format similar to this `nfs://longhorn-test-nfs-svc.default:/opt/backupstore`

If all of the above things are not the reason. Can you file a new issue? This issue is tracking a problem with  SLES 15 SP2 and it is not related to k3s

**Comment by jenting** [comment]
> I'm on Longhorn v1.1.0, Baremetal, k3s, but I'm still getting this exact error.
> 
> ```
> Failed to resolve server nfs-service: Name or service not known\n, error exit status 32\n, stderr, time=\"2020-12-24T06:51:23Z\" level=error msg=\"Cannot mount nfs nfs-service:/mnt/toshiba/nfshare: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 nfs-service:/mnt/nfshare /var/lib/longhorn-backupstore-mounts/nfs-service/mnt/nfshare], output mount.nfs4: Failed to resolve server nfs-service: Name or service not known\\n, error exit status 32\"\n, error exit status 1"
> ```
> 
> This backup worked exactly once for me, and now it can't find the service for my NFS server anymore.

@Bwvolleyball,
I tried to reproduce your case.

I'm using k3s + Longhorn v1.1.0 on SLES 15 SP2.
I deploy longhorn at namespace longhorn-system and deploy minio at namespace default.
At each longhorn-manager pod, I could access my minio server S3 URL by curl command.

Have you fixed your problem? If not, could you please provide more information on this issue, thank you.

**Comment by yasker** [comment]
@jenting The issue likely only happens for Helm chart deployment, e.g. installing using helm chart, installing using Rancher chart, due to the `/var/run` bind-mount still exists in the chart (but was removed in the deployment yaml): https://github.com/longhorn/longhorn/blob/master/chart/templates/daemonset-sa.yaml#L48 .

**Comment by Bwvolleyball** [comment]
I guess where my setup differs is that I'm running a tiny external NFS server on a raspberry pi.  I can correctly get my service to resolve to my NFS server outside of the longhorn pods. My ultimate workaround was to use the ip address assigned to my NFS server since the service resolution wasn't working for longhorn.

**Comment by yasker** [comment]
@Bwvolleyball Longhorn depends on Kubernetes's DNS to resolve the DNS name. Can you check if you can resolve the NFS DNS name in other Kubernetes pods?

**Comment by Bwvolleyball** [comment]
Yes, I am able to resolve that DNS name / service in other pods.

**Comment by yasker** [comment]
@Bwvolleyball That's weird. What does `nslookup` say inside the pod? does it return the same result as ping?
