### ISSUE TITLE
[BUG] RWX volume fails to attach to a pod on RHEL 7.8 SELinux enabled

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2093]
**Describe the bug**
RWX volume fails to attach to a pod on RHEL 7.8 SELinux enabled

**To Reproduce**
1. Create a K8s cluster on RHEL 7.8 nodes (1 etcd, 1 control plane and 3 worker)
2. Deploy Longhorn
3. Create a PVC with RWX using longhorn storage class.
4. Attach the PVC to a pod.
5. Pod fails to attach to the volume.
```
(combined from similar events): MountVolume.SetUp failed for volume "pvc-2da9c637-d09c-451f-82ee-e14adf284f96" : rpc error: code = Internal desc = mount failed: exit status 32 Mounting command: /bin/systemd-run Mounting arguments: [--description=Kubernetes transient mount for /var/lib/kubelet/pods/81fde443-406c-4d6a-b6d7-ded3c73b3a4c/volumes/kubernetes.io~csi/pvc-2da9c637-d09c-451f-82ee-e14adf284f96/mount --scope -- /bin/mount -t nfs -o vers=4.1,noresvport,soft,sync,intr,timeo=7,retrans=3 10.43.240.29:/pvc-2da9c637-d09c-451f-82ee-e14adf284f96 /var/lib/kubelet/pods/81fde443-406c-4d6a-b6d7-ded3c73b3a4c/volumes/kubernetes.io~csi/pvc-2da9c637-d09c-451f-82ee-e14adf284f96/mount] Output: Running scope as unit run-3942.scope. mount: wrong fs type, bad option, bad superblock on 10.43.240.29:/pvc-2da9c637-d09c-451f-82ee-e14adf284f96, missing codepage or helper program, or other error (for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program) In some cases useful info is found in syslog - try dmesg | tail or so.
```

**Log**
[longhorn-support-bundle_79459e4c-9492-45ff-9e64-9f7453b6edc9_2020-12-14T04-07-16Z.zip](https://github.com/longhorn/longhorn/files/5686382/longhorn-support-bundle_79459e4c-9492-45ff-9e64-9f7453b6edc9_2020-12-14T04-07-16Z.zip)

**Environment:**
 - Longhorn version: Longhorn- master `12/13/2020`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
 - Node config
   - OS type and version: RHEL 7.8
   - CPU per node: 2
   - Memory per node: 4 GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth and latency between the nodes: upto 5 GI
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS

**Additional context**
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.8 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
```
```
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31
```
<img width="1412" alt="Screen Shot 2020-12-13 at 8 07 59 PM" src="https://user-images.githubusercontent.com/60111667/102039565-178a1b80-3d7f-11eb-811d-fe84e8523c25.png">

**Comment by yasker** [comment]
Is `nfs-common` or equivalent installed?

**Comment by khushboo-rancher** [comment]
My bad. I forgot to install nfs-common.

RWX feature is working fine on RHEL 7.8.
