### ISSUE TITLE
[BUG]Longhorn node is not cleaned up automatically when the kube node is removed in v1.0.x and the Longhorn is upgraded to v1.1.0

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2100]
**Describe the bug**
See the title.

**To Reproduce**
It's the same as [the test Longhorn upgrade with node down and removal](https://longhorn.github.io/longhorn-tests/manual/release-specific/v1.1.0/reusing-failed-replica-for-rebuilding/)

**Expected behavior**
At step 6, Longhorn node related to the removed node should be cleaned up automatically after upgrade

**Environment:**
 - Longhorn version: v1.0.2 -> v1.1.0-rc2
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.19
 - Node config
   - OS type and version: Ubuntu 18.04
   - CPU per node: 2v
   - Memory per node: 4G
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth and latency between the nodes: 23Gb/sec; < 0.1ms
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Digital Ocean

**Additional context**

**Comment by khushboo-rancher** [comment]
Verified with Longhorn master - `01/04/2021`

Validation - **Pass**

Deleted the node from the set up of Longhorn v1.0.2 and upgraded to master. The Deleted node got cleaned up on upgrading the set up. Added back new nodes (one of them with same name), nodes got added automatically in the Longhorn master.

Validated the scenario of the reusing of same replica, it worked fine.
