### ISSUE TITLE
[BUG] NodeDownPodDeletionPolicy not working on K8s v1.19.4

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2104]
**Describe the bug**
The feature `Pod Deletion Policy When Node is Down` is not working with K8s v1.19.4

**To Reproduce**
1. Deploy Longhorn v1.1.0-rc2 on a K8s cluster of 4 nodes (1 etcd/control plane, 3 worker)
2. Create a deployment and attach to a volume.
3. Set `Pod Deletion Policy When Node is Down` to `delete-both-statefulset-and-deployment-pod` and `Volume Attachment Recovery Policy` to `wait`
4. Power down the node which has the deployment.
5. The pod doesn't get deleted.

**Expected behavior**
The pod should get deleted and a new one should get created.

**Log**

**Environment:**
 - Longhorn version: v1.1.0-rc2
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
 - Node config
   - OS type and version: ubuntu 18.04
   - CPU per node: 2 vcpus
   - Memory per node: 4 GB
   - Disk type(e.g. SSD/NVMe): SSD

**Comment by PhanLe1010** [comment]
Nice catch. It seems similar to https://github.com/longhorn/longhorn/issues/2062

**Comment by khushboo-rancher** [comment]
Closing this bug as this is duplicate of #2062
