### ISSUE TITLE
[BUG] Recurring backup job stuck on K8s 1.19.4 if volume is attached to the same node and powered down

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2106]
**Describe the bug**
On 

**To Reproduce**
1. Deploy Longhorn v1.1.0-rc2 on a 1.19.4 K8s cluster of 4 nodes (1 etcd/control plane, 3 worker)
2. Create a volume and attach to a deployment.
3. Enable `Allow Recurring Job While Volume Is Detached`.
4. Set recurring backup job for every 2 mins.
5. Write some data into the volume and scale down the deployment.
6. Make sure the cron job and the volume is attached to same node. (If not keep deleting the cron job, it will eventually schedule on the same node.)
7. While the recurring job is in progress, power down the node where the cron job is running.
8. The cron job pod stuck in unknown status and doesn't move to another node.

**Note:** With K8s v1.18.2, the cron job moves to another node and completes the recurring job.

**Expected behavior**
The cron job should move to another node and complete the recurring job.

**Environment:**
 - Longhorn version: v1.1.0-rc2
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE - v1.19.4 K8s
 - Node config
   - OS type and version: ubuntu 18.04
   - CPU per node: 2 vcpu
   - Memory per node: 4 GB
   - Disk type(e.g. SSD/NVMe): SSD
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): DO

**Additional context**
This issue might be similar to https://github.com/longhorn/longhorn/issues/2062

**Comment by yasker** [comment]
Move to Icebox due to we're waiting for the upstream Kubernetes fix for #2062

**Comment by innobead** [comment]
@khushboo-rancher please revisit this after verifying #2062
