### ISSUE TITLE
volume size display does not conform to the actual situation

### ISSUE THREAD

**Issue by 2690522020** [longhorn/longhorn#2109]
**Question**
volume size display does not conform to the actual situation
**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version:1.18.8
 - Node config
   - OS type and version
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):Baremetal

**Additional context**
I ran Kafka and used Longhorn storage
![Inked1608111654(1)_LI](https://user-images.githubusercontent.com/26107727/102333207-0e3fbf80-3fc8-11eb-85ee-bf35f0d47d04.jpg)

This is what the kuboard shows

![1608111597(1)](https://user-images.githubusercontent.com/26107727/102332104-a177f580-3fc6-11eb-935d-79dbedb67c41.png)

**Comment by joshimoo** [comment]
The actual size includes snapshots as well as data that might have existed on the filesystem but has now been deleted. Since Longhorn operates on the block level and not the filesystem level. 

More information [here](https://longhorn.io/docs/1.0.2/volumes-and-nodes/volume-size/#volume-actual-size).

**Comment by 2690522020** [comment]
But will baremetal use more and more storage space?

**Comment by shuo-wu** [comment]
Longhorn volumes use [sparse files](https://wiki.archlinux.org/index.php/sparse_file#:~:text=Creating%20sparse%20files,-The%20truncate%20utility&text=As%20you%20can%20see%2C%20although,required%20to%20store%20its%20contents.) to store data. You can log into the node host, access the data directory of the replica on the node (the directory path is already shown on the UI), check the apparent size and actual size of the volume. e.g.:
```
root@shuo-cluster-0-worker-1:/var/lib/longhorn/replicas/vol-837f28f3# ls -alh
total 101M
drwx------ 2 root root 4.0K Dec 17 12:22 .
drwxr-xr-x 3 root root 4.0K Dec 17 12:22 ..
-rw------- 1 root root 4.0K Dec 17 12:26 revision.counter
-rw-r--r-- 1 root root 2.0G Dec 17 12:26 volume-head-002.img
-rw-r--r-- 1 root root  178 Dec 17 12:22 volume-head-002.img.meta
-rw-r--r-- 1 root root  194 Dec 17 12:22 volume.meta
-rw-r--r-- 1 root root 2.0G Dec 17 12:22 volume-snap-2aeee8a5-9abd-4a04-9eaf-4830a30386a9.img
-rw-r--r-- 1 root root  125 Dec 17 12:22 volume-snap-2aeee8a5-9abd-4a04-9eaf-4830a30386a9.img.meta
-rw-r--r-- 1 root root 2.0G Dec 17 12:22 volume-snap-d463e434-000f-48fb-b08d-ac889de98619.img
-rw-r--r-- 1 root root  177 Dec 17 12:22 volume-snap-d463e434-000f-48fb-b08d-ac889de98619.img.meta
root@shuo-cluster-0-worker-1:/var/lib/longhorn/replicas/vol-837f28f3# du -h
101M	.
root@shuo-cluster-0-worker-1:/var/lib/longhorn/replicas/vol-837f28f3# du -h --apparent-size
6.1G	.
```

Can you follow the above instructions to check the size manually? If the actual size shown in Longhorn UI is wrong, we can dig deep into that then.

**Comment by yasker** [comment]
@2690522020 Longhorn volume itself will use to the maximum size of the allocated volume size. It might use more due to the snapshot which contains historical data. You can always delete the snapshots to release the extra space taken by it.

Once a block is been written, it will be recorded, no matter if the filesystem thinks it's free or not. Filesystem might write a block then mark it as free later, but it looks the same from the block level since it has been written. That's why you saw the difference between the space reported by the filesystem and the space reported by Longhorn.

**Comment by 2690522020** [comment]
What happens when the actual used size of the volume reaches the allocated size? Can't write? However, when the file system doesn't use that much space

**Comment by 2690522020** [comment]
> Longhorn volumes use [sparse files](https://wiki.archlinux.org/index.php/sparse_file#:~:text=Creating%20sparse%20files,-The%20truncate%20utility&text=As%20you%20can%20see%2C%20although,required%20to%20store%20its%20contents.) to store data. You can log into the node host, access the data directory of the replica on the node (the directory path is already shown on the UI), check the apparent size and actual size of the volume. e.g.:
> 
> ```
> root@shuo-cluster-0-worker-1:/var/lib/longhorn/replicas/vol-837f28f3# ls -alh
> total 101M
> drwx------ 2 root root 4.0K Dec 17 12:22 .
> drwxr-xr-x 3 root root 4.0K Dec 17 12:22 ..
> -rw------- 1 root root 4.0K Dec 17 12:26 revision.counter
> -rw-r--r-- 1 root root 2.0G Dec 17 12:26 volume-head-002.img
> -rw-r--r-- 1 root root  178 Dec 17 12:22 volume-head-002.img.meta
> -rw-r--r-- 1 root root  194 Dec 17 12:22 volume.meta
> -rw-r--r-- 1 root root 2.0G Dec 17 12:22 volume-snap-2aeee8a5-9abd-4a04-9eaf-4830a30386a9.img
> -rw-r--r-- 1 root root  125 Dec 17 12:22 volume-snap-2aeee8a5-9abd-4a04-9eaf-4830a30386a9.img.meta
> -rw-r--r-- 1 root root 2.0G Dec 17 12:22 volume-snap-d463e434-000f-48fb-b08d-ac889de98619.img
> -rw-r--r-- 1 root root  177 Dec 17 12:22 volume-snap-d463e434-000f-48fb-b08d-ac889de98619.img.meta
> root@shuo-cluster-0-worker-1:/var/lib/longhorn/replicas/vol-837f28f3# du -h
> 101M	.
> root@shuo-cluster-0-worker-1:/var/lib/longhorn/replicas/vol-837f28f3# du -h --apparent-size
> 6.1G	.
> ```
> 
> Can you follow the above instructions to check the size manually? If the actual size shown in Longhorn UI is wrong, we can dig deep into that then.

My situation seems to be the same as what you described, but I'm worried that the file system will not be able to write in the future when there is still space in the file system

**Comment by PhanLe1010** [comment]
If the actual used size of the volume reaches the allocated size but the file system doesn't use that much space, the application using the file system can still read/write as normal.

**Comment by 2690522020** [comment]
> If the actual used size of the volume reaches the allocated size but the file system doesn't use that much space, the application using the file system can still read/write as normal.

So I can use it with ease

**Comment by auricom** [comment]
> @2690522020
> Once a block is been written, it will be recorded, no matter if the filesystem thinks it's free or not. Filesystem might write a block then mark it as free later, but it looks the same from the block level since it has been written. That's why you saw the difference between the space reported by the filesystem and the space reported by Longhorn.

Thanks for the explanation. So there is no way to "recalculate" blocks to reclaim space on a longhorn node ?
The only solution I see now is to manually recreate a volume from scratch.

**Comment by yasker** [comment]
@auricom Since the user has created the volume size of xxxGB, Longhorn would expect to use that much of space eventually.  There were some discussions about implementing `trim` e.g. https://github.com/longhorn/longhorn/issues/836 but in the end, it's very tricky to implement and we decide to put it on hold.
