### ISSUE TITLE
task: switch the image base for Longhorn share manager to ubuntu

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2111]
Trivy doesn't support scanning Fedora for vulnerabilities

**Comment by joshimoo** [comment]
Need to test arm images.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master `01/21/2021`

Validation - **Fail**

With image `longhornio/longhorn-share-manager:v1_20210106`, on deploying https://raw.githubusercontent.com/longhorn/longhorn-manager/master/examples/rwx/rwx-nginx-deployment.yaml, the deployment doesn't come up and stuck with the below error.
```
7m47s       Warning   FailedMount              pod/rwx-test-5d98bd9fff-sg9xw   MountVolume.SetUp failed for volume "pvc-3d9bd71e-e7ab-4420-bffa-b158e7de9186" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: /usr/bin/systemd-run
Mounting arguments: [--description=Kubernetes transient mount for /var/lib/kubelet/pods/17a30a9f-0b82-4500-91bb-211b8b2345b9/volumes/kubernetes.io~csi/pvc-3d9bd71e-e7ab-4420-bffa-b158e7de9186/mount --scope -- /bin/mount -t nfs -o vers=4.1,noresvport,soft,sync,intr,timeo=7,retrans=3 10.43.228.161:/pvc-3d9bd71e-e7ab-4420-bffa-b158e7de9186 /var/lib/kubelet/pods/17a30a9f-0b82-4500-91bb-211b8b2345b9/volumes/kubernetes.io~csi/pvc-3d9bd71e-e7ab-4420-bffa-b158e7de9186/mount]
Output: Running scope as unit: run-ra89ae0577d5f4d7f86e12343de582104.scope
mount.nfs: mounting 10.43.228.161:/pvc-3d9bd71e-e7ab-4420-bffa-b158e7de9186 failed, reason given by server: No such file or directory
```

**Comment by joshimoo** [comment]
Leaving a note here, when testing the new image on arm ubuntu 20.04 host.
It looks /etc/mtab is not available when starting ganesha so it's unable to find all mounted filesystems.
You can investigate this easily by deploying a share-manager image, but replacing the start command with /bin/bash then manually start `./longhorn-share-manager` with an attached volume.

This will try to start ganesha and you can investigate the ganesha.log in /tmp/ganesha.log.
You can find the start args here: https://github.com/longhorn/longhorn-manager/blob/c76362e8421ffae7872d30988be8a56dba6a96b0/controller/share_manager_controller.go#L723

**Comment by yasker** [comment]
Waiting for the share manager image update. cc @joshimoo

**Comment by khushboo-rancher** [comment]
Verified with Longhorn master - `03/09/2021` and share-manager image `longhornio/longhorn-share-manager:v1_20210302`

Validation - **Pass**

RWX feature works on ubuntu arm and amd64 set up.

**Steps taken**
1. Deployed Longhorn Master and verified the RWX feature on Ubuntu arm64.
2. Deployed Longhorn Master and verified the RWX feature on Ubuntu amd64.
3. Upgraded Longhorn v1.1.0 to master with set up having RWX volumes on Ubuntu amd64.
4. Upgraded Longhorn v1.1.0 to master with set up having RWX volumes on Ubuntu arm64.
