### ISSUE TITLE
Failover for mariadb stateful set pvc isn't working

### ISSUE THREAD

**Issue by ssirag** [longhorn/longhorn#2122]
**Failover for mariadb stateful set pvc isn't working**

I have a basic bitnami/wordpress configuration installed via helm on my rancher/longhorn kubernetes cluster.  I turn off a node to simulate node failure, expecting the pvc will be rescheduled to a remaining node.

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: 1.19.4
 - Node config
   - OS type and version Ubuntu 18.04
   - CPU per node: 4
   - Memory per node: 16 GB
   - Disk type: SSD-assisted HDD array
   - Network bandwidth and latency between the nodes: 10 Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Hyper-V/RKE

**Additional context**
- Volume Attachment Recovery Policy: immediate
- PVC State: Attached (still attached to down node)
- PVC Health: Unknown
- PVC Ready for workload: Ready
- PVC replicas: available on other nodes
- Warning in volume events (17 minutes ago): volume pvc-58367392-17e0-4581-959c-233f6ccfabc4 is unknown

**Comment by joshimoo** [comment]
Kubernetes will not delete pods when a node fails, since the kubelet on the node is no longer running.
For **non stateful sets** we added the https://longhorn.io/docs/1.1.0/references/settings/#volume-attachment-recovery-policy

For 1.1 we added a new setting that allows us to cleanup **stateful sets** as well, by default this option is turned off.
https://longhorn.io/docs/1.1.0/references/settings/#pod-deletion-policy-when-node-is-down

**Comment by khushboo-rancher** [comment]
This seems related to https://github.com/longhorn/longhorn/issues/2062

**Comment by PhanLe1010** [comment]
Yeah, indeed it is related to #2062. It is an upstream Kubernetes bug and we are expecting that they will fix that soon.

**Comment by ssirag** [comment]
Update: 1.1.0 doesn't fix this issue, and it also affects deployments as well as stateful sets.

**Comment by PhanLe1010** [comment]
@ssirag 

Yes, This is a [bug](https://github.com/longhorn/longhorn/issues/2062) in Kubernetes v1.19+ versions that breaks Longhorn's `Pod Deletion Policy When Node is Down` feature. We are waiting for the upstream Kubernetes to fix it.

**Comment by c3y1huang** [comment]
Looks like this have been fixed in v1.1.1. Closing and feel free to re-open if the issue persists after the upgrade.
