### ISSUE TITLE
[BUG] When I use longhron NFS storage as volume for InfluxDB the disk i/o increases unusually

### ISSUE THREAD

**Issue by mohjam2004** [longhorn/longhorn#2126]
**Describe the bug**
When I use longhron nfs storage as volume for InfluxDB and use it as remote stoarge for prometheus, the DISK I/O increase unusually and the node on which the longhorn nfs volume is running become too slow.

**To Reproduce**
1. deploy longhorn in rancher
2. deploy longhorn nfs provisioner in rancher.
3. deploy influxdb and use longhorn nfs storage as volume
4. use influxdb as remote storage for prometheus.
5. unusual disk i/o occurs and the node on which longhorn nfs volume is running become too slow.

**Expected behavior**
The disk I/O when I use longhorn nfs storage with influxdb (as remote stoarge for prometheus) should not increase unusually and should work the same when I use longhorn basic stoarge.

**Log**
The disk i/o when I use longhorn storage with influxdb and use it as remote storage for prometheus: (disk i/o is normal)

![image](https://user-images.githubusercontent.com/59224403/102743915-bd381e80-436d-11eb-984e-a31a9e350d9a.png)

![image](https://user-images.githubusercontent.com/59224403/102743927-c2956900-436d-11eb-8164-58413e3c7303.png)

The disk i/o when I use longhorn nfs storage with influxdb and use it as remote storage for prometheus: (disk i/o is unusual) 

![image](https://user-images.githubusercontent.com/59224403/102743986-e6f14580-436d-11eb-9ac9-f3d00a551873.png)

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
 - Node config
   - OS type and version: Debian 10
   - Disk type(e.g. SSD/NVMe): VMware virtual disk and Ceph. 
 
I tested this scenario on both vmware virtual disk and ceph storage and in both situation the disk i/o increased unsually.

**Comment by shuo-wu** [comment]
Since the data written into Longhorn volumes is exactly what users/workloads write. There are 2 possibilities for this case:
1. There is a filesystem formatting for the Longhorn volume near the peak.
2. The caches held by the NFS client/server (or the influxdb) are flushed into the Longhorn volume.

Right now it seems that the i/o peak is tolerable as long as there is no r/w timeout. Or is there any other concern/potential impact for the peak?

**Comment by mohjam2004** [comment]
What is written to longhorn nfs storage is the same what is written to longhorn basic storage.
I want to know  why, when the data is written to nfs storage (remote storage for prometheus) the disk i/o increases suddenly?
I haven't seen this problem with other pods when using longhorn nfs storage.
My guess is that the longhorn nfs storage has a problem with influxdb when the read and write data constantly and at the same time.

**Comment by joshimoo** [comment]
@mohjam2004 you really shouldn't run a database on top of nfs storage.

**Comment by mohjam2004** [comment]
hello @joshimoo 
Why should not I use database on top of longhorn nfs storage?
I need a 'read and write many" storage and longhorn support it only through nfs.

**Comment by joshimoo** [comment]
@mohjam2004 have a look at the prometheus documentation here, about the nfs warning :)
https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects

**Comment by mohjam2004** [comment]
Hi, @joshimoo 
Thanks alot.
