### ISSUE TITLE
[FEATURE] Live migration support for KubeVirt

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2127]
**Is your feature request related to a problem? Please describe.**
Harvester is using Longhorn as the underlying storage. However, live migration in Harvester requests Longhorn volume to be simultaneously accessible from two different nodes, when the VM is migrating from one node to another.

**Describe the solution you'd like**
We need to support KubeVirt live migration in someway to enable the feature in Harvester.

**Describe alternatives you've considered**
N/A

**Additional context**
This was implemented for RancherVM (https://github.com/longhorn/longhorn/issues/87) but we removed the feature later.
Also, this depends on https://github.com/longhorn/longhorn/issues/2006 since normally VM requires a backing file for the root device, and Longhorn should be able to do live migration with the backing file.

**Comment by yasker** [comment]
Remove `require/doc` due to this feature is not directly user-facing.

**Comment by khushboo-rancher** [comment]
@joshimoo I tried the below scenario,
```
1. Creates a new RWX migratable volume.
2. Attach to test node to write some test data on it.
3. Detach from test node.
4. Get set of nodes excluding the test node
5. Attach volume to node 1 (initial node)
6. Attach volume to node 2 (migration target)
7. Wait for migration ready (engine running on node 2)
8. Detach volume from node 1
```
 I'm using Longhorn UI to detach the volume and it get stuck at step 8.
```
[longhorn-manager-rvcqb] E0329 17:03:47.721072       1 volume_controller.go:202] fail to sync longhorn-system/pvc-85f358c1-f683-458f-a1a8-e33692d25153: BUG: multiple engines detected when volume pvc-85f358c1-f683-458f-a1a8-e33692d25153 is detached 
[longhorn-manager-rvcqb] time="2021-03-29T17:03:47Z" level=warning msg="Dropping Longhorn volume longhorn-system/pvc-85f358c1-f683-458f-a1a8-e33692d25153 out of the queue" controller=longhorn-volume error="fail to sync longhorn-system/pvc-85f358c1-f683-458f-a1a8-e33692d25153: BUG: multiple engines detected when volume pvc-85f358c1-f683-458f-a1a8-e33692d25153 is detached" node=khush-test-lh-wk1 
[longhorn-manager-rvcqb] E0329 17:03:47.726771       1 volume_controller.go:202] fail to sync longhorn-system/pvc-85f358c1-f683-458f-a1a8-e33692d25153: BUG: multiple engines detected when volume pvc-85f358c1-f683-458f-a1a8-e33692d25153 is detached 
[longhorn-manager-rvcqb] time="2021-03-29T17:03:47Z" level=warning msg="Dropping Longhorn volume longhorn-system/pvc-85f358c1-f683-458f-a1a8-e33692d25153 out of the queue" controller=longhorn-volume error="fail to sync longhorn-system/pvc-85f358c1-f683-458f-a1a8-e33692d25153: BUG: multiple engines detected when volume pvc-85f358c1-f683-458f-a1a8-e33692d25153 is detached" node=khush-test-lh-wk1 
```
As in Longhorn UI there is no selection of node available in case of detach, how can test this?

I see the integrated test `test_migration` has been passing in nightly runs. Can we rely on those tests for validation of the feature?

I think the best way to validate this is by using Harvester?

**Comment by joshimoo** [comment]
@khushboo-rancher yeah the e2e tests the migration correctly and can be relied on.

For the manual test: 
- create pvc with Block VolumeMode, see https://longhorn.io/docs/1.1.0/references/examples/#block-volume
- spawn first pod wait for running
- spawn a second pod, wait for running

Case migration success
- terminate pod 1 (migration success)

Case migration rollback
- terminate pod 2 (migration rollback)


If you want to test with harvester you can follow the instructions in the LEP https://github.com/longhorn/longhorn/blob/master/enhancements/20210216-volume-live-migration.md#creating-a-migratable-storage-class

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master `03/31/2021`

Validation - **Pass**

Validated the cases from https://github.com/longhorn/longhorn/issues/2127#issuecomment-809585801, the migration and rollback work fine on Longhorn-master and Longhorn-master upgraded set up.
