### ISSUE TITLE
Cant able to use RWX

### ISSUE THREAD

**Issue by himanshusharma-git** [longhorn/longhorn#2132]
i need to deploy a RKE cluster with longhorn but now when see the documentation where it ask us to deploy few yaml to enable rwx i coudn't find them.
Kindly suggest me how to move forward now . i have already deployed longhorn with rancher but now when i try to increaset the replicas of wordpress application it gives me multi attach volume error. 

![image](https://user-images.githubusercontent.com/40313710/102995876-f7f5ae80-4547-11eb-9584-e4abd3d2c2b7.png)

Thanks

**Comment by PhanLe1010** [comment]
Hi @himanshusharma-git 

Which Longhorn version are you using?

If you are using v1.1.0, RWX is supported natively and you don't have to do any additional setup, [see docs](https://longhorn.io/docs/1.1.0/advanced-resources/rwx-workloads/)

If you want to use Longhorn v1.0.2, you need to do additional setups as you mentioned above. It is a bug that some of the links in the Longhorn v1.0.2 document are broken as you mentioned. You can find the yaml files on Longhorn v1.0.2 branch in this folder https://github.com/longhorn/longhorn/tree/v1.0.2/examples/rwx
We will fix the Longhorn v1.0.2 document to update those links.

**Comment by joshimoo** [comment]
@himanshusharma-git in 1.1 rwx support is natively available, you need to have the RWX access mode defined for the pvc.
If I remember correctly  the rancher wordpress app deploys with a RWO pvc instead of an RWX pvc.

**Comment by khushboo-rancher** [comment]
Closing this as broken links are fixed for doc v1.0.2 and doc for v1.1.0 and v1.1.1 are updated.
