### ISSUE TITLE
[BUG] Can't reset default storage class "longhorn"

### ISSUE THREAD

**Issue by timmy59100** [longhorn/longhorn#2135]
**Describe the bug**
After upgrading to longhorn 1.1 the standard default class "longhorn" keeps resetting as default storage class when I click reset default.

**To Reproduce**
1. Go to storage classes
2. Click on 'longhorn storage class'
3. Perform 'reset default'
4. longhorn storage class is default again.

**Expected behavior**
Not resetting itself to default storage class.
**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.1

**Comment by joshimoo** [comment]
@PhanLe1010 Do we mark the storage class as default in the config map?
Is there documentation for the user on how to change the config map, that is used for the storage class?

**Comment by PhanLe1010** [comment]
This issue is similar to https://github.com/longhorn/longhorn/issues/2119

**Comment by shuo-wu** [comment]
You can try modifying the annotation `storageclass.kubernetes.io/is-default-class` in the configmap `longhorn-system/longhorn-storageclass` data to `"false"`
```
kubectl -n longhorn-system edit configmap longhorn-storageclass
```

**Comment by timmy59100** [comment]
> You can try modifying the annotation `storageclass.kubernetes.io/is-default-class` in the configmap `longhorn-system/longhorn-storageclass` data to `"false"`
> 
> ```
> kubectl -n longhorn-system edit configmap longhorn-storageclass
> ```

This works. I think the previous behaviour was better: Have it as default, but it is resettable.

**Comment by shuo-wu** [comment]
Yeah. It is better to allow users to reset/unset it via Helm/Rancher App. We will check it then.

**Comment by timmy59100** [comment]
> 
> 
> You can try modifying the annotation `storageclass.kubernetes.io/is-default-class` in the configmap `longhorn-system/longhorn-storageclass` data to `"false"`
> 
> ```
> kubectl -n longhorn-system edit configmap longhorn-storageclass
> ```

@shuo-wu This does not work anymore for me on longhorn 1.2.2.

It keeps reseting itself to the "longhorn" storageclass.

**Comment by PhanLe1010** [comment]
> It keeps reseting itself to the "longhorn" storageclass.

What do you mean by `resetting itself to the "longhorn" storageclass`? @shuo-wu instruction is to change the `loghorn` storageclass no on-default

**Comment by shuo-wu** [comment]
Do you mean you can not set `longhorn` as non-default StorageClass? I just retried this. It works fine... 
By deleting the annotation `storageclass.kubernetes.io/is-default-class: "true"` or modifying its value to `"false"`, you can still set StorageClass `longhorn` as the non-default one in v1.2.2.

**Comment by timmy59100** [comment]
@timmy59100 Ok, I set it to false `storageclass.kubernetes.io/is-default-class: "true"` and a few seconds later it's true again.

**Comment by PhanLe1010** [comment]
@timmy59100 which command you use to set it?

**Comment by timmy59100** [comment]
@PhanLe1010 Ah i see. I edited the storageclass directly and not the configmap. Sorry used the wrong command.

**Comment by shuo-wu** [comment]
Yeah. We use the ConfigMap to control the special StorageClass 'longhorn'. 
If the issue is resolved, can we close this ticket?

**Comment by timmy59100** [comment]
It seems that we have to edit the configmap after every upgrade. Is this correct?

**Comment by shuo-wu** [comment]
To set `longhorn` as non-default StorageClass? Not exactly, you can do that via modifying the Helm value or Rancher UI as well:
https://github.com/longhorn/longhorn/blob/fb40e1b540ae73dd53169351b515bc2bfb518724/chart/values.yaml#L55

**Comment by timmy59100** [comment]
Ok, that should help. Thank you.
