### ISSUE TITLE
[BUG] longhorn-ui should not require IPv6

### ISSUE THREAD

**Issue by dhoard** [longhorn/longhorn#2136]
**Describe the bug**
Longhorn-ui fails when installed on a node that has IPv6 disabled.

**To Reproduce**
1. Setup a Vanilla K8s cluster (or other distribution) on nodes that have IPv6 disabled
2. Install Longhorn
3. Longhorn-ui fails to start due to a requirement for IPv6 in the nginx configuration.

**Expected behavior**
Longhorn-ui should be able to work with IPv4 only and should not **require** IPv6. This should be configurable.

**Notes**
It appears that the commit...

https://github.com/longhorn/longhorn-ui/commit/d8b7914a09a3cb1ec3cb14a23f1a2415ab48c69d#diff-1dcb5b9ed71275adb832be39501fbd6063add71b90a70533c722558330ae827f

...is what is causing the issue.

Specifically the nginx conf value `listen [::]:8000;`

**Comment by yasker** [comment]
The related PR is at https://github.com/longhorn/longhorn-ui/pull/320.

Since IPv6 is not tested, we can revert this PR and put it in the next release.

**Comment by vassilvk** [comment]
Is there a workaround for this issue?

**Comment by dhoard** [comment]
> Is there a workaround for this issue?

I reverted the change and built my own container. https://hub.docker.com/r/dhoard/longhorn-ui

Until it's released, I suspect that's the only option.

**Comment by yasker** [comment]
@vassilvk @dhoard 

We've deployed a new patched `longhornio/longhorn-ui:v1.1.0` outside of the normal release process. Can you try again? Also make sure you've pulled down the new image for `longhornio/longhorn-ui:v1.1.0` (e.g. set the image pull policy to always).

**Comment by dhoard** [comment]
@yasker New version works for me. Thanks!

**Comment by vassilvk** [comment]
@yasker
Beautiful 😄 
Works as expected now - thanks for the quick response!

**Comment by khushboo-rancher** [comment]
I tried reproducing the problem but couldn't reproduce it.
Verified with `longhorn-ui:v1.1.0-rc3`.

Steps to reproduce the issue.
1. Create a cluster `k8s-v1.19.7` of 4 nodes (1 etcd/control plane, 3 worker).
2. Disable IPv6 on all the nodes
```
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1
```
3. Deploy Longhorn v1.1.0-rc3, Longhorn-ui with nodeport.
4. Set up an external nginx server and access UI.

@dhoard @vassilvk Could you please let us know what I'm missing here?
Also, Could you provide the below details
1. How did you disable IPv6 on the nodes?
2. What's the OS of the nodes.
3. How are you accessing the Longhorn UI (e.g. nodeport, ingress)?

**Comment by dhoard** [comment]
@khushboo-rancher answers...

1. IPv6 disable via editing /etc/default/grub...

`GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1"`

... and then...

`update-grub`

2. Ubuntu 20.04.1 LTS

3. ingress using Nginx

**Comment by joshimoo** [comment]
Same root cause as the ganesha issue here https://github.com/longhorn/longhorn/issues/2197
This is only an issue when ipv6 support is disabled via the bootloader.

**Comment by anupama2501** [comment]
Able to reproduce the issue with above mentioned steps. 

- Brought up the cluster with 3 worker nodes [all Ubuntu 20.04.1 LTS], 1 etcd and 1 control plane
- Once the nodes are up, from /etc/default/grub — edited the line as follows to disable the ipv6 and then gave update-grub on all the worker nodes.
- Now installed the long horn app installing from the rancher UI[longhorn UI version to longhorn-ui:v1.1.0-rc3].
Seeing this error for the UI 
![Screen Shot 2021-02-05 at 1 08 25 PM](https://user-images.githubusercontent.com/38144301/107089870-31127700-67b4-11eb-929e-cd605796dc74.png)

**Comment by anupama2501** [comment]
Verified the same issue on the rancher UI by upgrading the version of longhorn UI to v1.1.0.
Added an external ingress and was able to launch UI without any issue 
![Screen Shot 2021-02-05 at 1 17 13 PM](https://user-images.githubusercontent.com/38144301/107090050-7b93f380-67b4-11eb-9af7-fa1c13e9877b.png)

Verified on master:
Once all the worker nodes are up, disabled the IPV6 from grub. 
Launched longhorn with kubectl. 
Setup an external ingress and verified the UI launched without any issue
