### ISSUE TITLE
[FEATURE] Use semantic versioning for longhorn-instance-manager docker image.

### ISSUE THREAD

**Issue by davidsbond** [longhorn/longhorn#2140]
**Is your feature request related to a problem? Please describe.**

All the longhorn images follow a semantic versioning format, and are generally all released at the same time with an exception for the `instance-manager` image. Recently I did an upgrade to 1.1.0 and found that rather than having an image tag of `v1.1.0` the instance-manager has an image tag of `v1_20201216`. This initially caused my things to enter `ImagePullBackOff` because I didn't expect the versioning to be different.

If there's a good reason for the difference in versioning strategy then fair enough, but it did catch me off guard when upgrading. As I'd initially had things pinned to `master`.

**Describe the solution you'd like**

Deploy `longhorn-instance-manager` with the same tagging format as all the other images.

**Comment by yasker** [comment]
Hi @davidsbond,

At this moment, we'd decided not to tie instance-manager to the semantic version of Longhorn release. The reason is they can remain the same version with the new Longhorn releases. The instance manager is designed to be stable across different versions. We only fix critical bugs in them. And every time instance managers are being upgraded, there will be some extra resources required and we want to reduce the upgrade for those components as much as possible.

**Comment by davidsbond** [comment]
Hey @yasker, thanks for the reply.

That makes sense, perhaps then in longhorn, it might be useful to have both `Latest Longhorn Version` and `Latest Instance Manager Version` displayed in the UI?

I'm using my own kustomize set up to deploy longhorn, so I don't just apply the latest hosted manifest you offer in the repository. So having a way to see when the version of the instance manager has changed would be helpful

**Comment by davidsbond** [comment]
Alternatively, I can just always use `master` for the instance manager image, is that the preferred way?

**Comment by PhanLe1010** [comment]
@davidsbond 

I am not quite sure what you want to achieve here:
```
I'm using my own kustomize set up to deploy longhorn, so I don't just apply the latest hosted manifest you offer in the repository. So having a way to see when the version of the instance manager has changed would be helpful
```
Is it correct that you want to know which version of `instance manager` goes with which version of Longhorn? If so, you can track that info by looking at the chart https://github.com/longhorn/longhorn/blob/57a454e9f635a7fe1a67317233a17b70f3359313/chart/values.yaml#L21

```
Alternatively, I can just always use master for the instance manager image, is that the preferred way?
``` 
The master tag includes in-developing features that are not stable yet. Not sure if that is what you want.

**Comment by davidsbond** [comment]
I'll just keep an eye on the chart to know when that changes. Thanks for the replies!
