### ISSUE TITLE
[BUG] After upgrade to 1.1.0 some old managers still running

### ISSUE THREAD

**Issue by dbpolito** [longhorn/longhorn#2144]
Not sure it's a bug but i noticed that after upgrading to 1.1.0 and removing old engine from UI, it seems it will has some managers running on my cluster:

```bash
❯ kubectl -n longhorn-system get pod
NAME                                        READY   STATUS    RESTARTS   AGE
csi-attacher-74db7cf6d9-5t82f               1/1     Running   1          22m
csi-attacher-74db7cf6d9-fkgrh               1/1     Running   1          22m
csi-attacher-74db7cf6d9-kkbjb               1/1     Running   1          22m
csi-provisioner-d444fb7c9-h86lp             1/1     Running   1          22m
csi-provisioner-d444fb7c9-pzdnr             1/1     Running   1          22m
csi-provisioner-d444fb7c9-tvmvt             1/1     Running   1          22m
csi-resizer-58458969c9-5jghw                1/1     Running   0          22m
csi-resizer-58458969c9-qsg72                1/1     Running   0          22m
csi-resizer-58458969c9-x9dg2                1/1     Running   0          22m
csi-snapshotter-6d856448d-5mrvt             1/1     Running   0          22m
csi-snapshotter-6d856448d-kqn8v             1/1     Running   0          22m
csi-snapshotter-6d856448d-sjvrs             1/1     Running   0          22m
engine-image-ei-cf743f9c-4szpr              1/1     Running   0          23m
engine-image-ei-cf743f9c-ckh6m              1/1     Running   0          23m
engine-image-ei-cf743f9c-hq9nm              1/1     Running   0          23m
instance-manager-e-1d8f9e20                 1/1     Running   0          29d
instance-manager-e-518eb4db                 1/1     Running   0          29d
instance-manager-e-6e51742e                 1/1     Running   0          22m
instance-manager-e-7afada48                 1/1     Running   0          22m
instance-manager-e-91a86d4a                 1/1     Running   0          22m
instance-manager-e-cd19ea8f                 1/1     Running   0          36h
instance-manager-r-675ef2b2                 1/1     Running   0          22m
instance-manager-r-8188c0ba                 1/1     Running   0          22m
instance-manager-r-909a2a77                 1/1     Running   0          22m
longhorn-csi-plugin-fbblr                   2/2     Running   0          21m
longhorn-csi-plugin-rkg9w                   2/2     Running   0          21m
longhorn-csi-plugin-tsglr                   2/2     Running   0          21m
longhorn-driver-deployer-76c8fd69fb-5xq9l   1/1     Running   0          25m
longhorn-manager-k9sl4                      1/1     Running   1          24m
longhorn-manager-vnfv2                      1/1     Running   2          24m
longhorn-manager-wx77t                      1/1     Running   1          24m
longhorn-ui-78547884d8-psw66                1/1     Running   0          25m
```

I have 3 nodes, when i deleted the old engine 3 pods of manager `r` were terminated but the `e` ones are still there.

Everything seems to be working fine...

**Comment by shuo-wu** [comment]
This is what Longhorn expected rather than a bug. For the Longhorn volume live upgrade, the engine cannot be switched to another/new engine manager pods without interrupt the i/o. Hence, the new engine of upgraded volumes should be launched by the old engine manager pods.
Once you detach the upgraded volumes, these engine manager pods will be removed automatically.

**Comment by dbpolito** [comment]
Well i looked at all volumes through the UI on details page and they are all pointing to the new engine and pointing to `instance-r` managers on the nodes... it doesn't seem any `instance-e` is being used... 🤔 

Well if they are still using somehow the old manager that means the new stuff like `Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly` isn't enabled yet?

When you mean detached is just restart all my pods? like scaling my deployments to 0 then back to what it was?

Maybe worth adding notes about it on the Docs, or maybe it's there and i didn't see it.

Btw thank you for all your work on this project, love it. ❤️

**Comment by shuo-wu** [comment]
1. For the engine manager (instance-manager-e) using the latest/default instance manager image, it will be retained even if there is no volume engine pointing to it. But if an engine manager is using the old instance manager image, it will be cleaned up automatically once there is no engine in it. You can verify this by checking which image the engine manager that contains volume engines is using. If there is no volume engine pointing to an old engine manager but this engine manager still exists, there is something wrong with Longhorn.
2. Whether using the latest instance manager won't affect the functionality of the setting `Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly`. Typically, the instance manager upgrade means the bug fix. And most of the new features can be still applied with the old instance managers.
3. If you wish your volume engines can be handled by the latest engine manager, then YES, you can restart the related pods by scaling down and up your deployment/statefulset.

**Comment by dbpolito** [comment]
@shuo-wu 

Thank you for your answers, that makes sense... Last one i promise as it's yet not clear and i think it may be good for Knowledge Base for the project:

On the Longhorn UI everything is already pointing to the new managers, so how can i now which pods are still using the old one and holding it?

**Comment by dbpolito** [comment]
Hello guys, the new page is looking great, but now after upgrading from `1.1.1` to `1.2.2` i'm facing the same issue, i will have 5 old instance managers...

The docs are clear, but i think the current approach isn't very friendly for when you have lots of volumes.

Currently the only way for seeing which pods are using these instance managers is going to the detail page, which in my case, which i have 100+ volumes, can be very difficult.

Would be great to make it filterable or displayable in the table, would already help a lot.

**Comment by innobead** [comment]
> Hello guys, the new page is looking great, but now after upgrading from `1.1.1` to `1.2.2` i'm facing the same issue, i still have 5 old instance managers...
> 
> The docs are clear, but i think the current approach isn't very friendly for when you have lots of volumes.
> 
> Currently the only way for seeing which pods are using these instance managers is going to the detail page, which in my case, which i have 100+ volumes, can be very difficult.
> 
> Would be great to make it filterable or displayable in the table, would already help a lot.

@smallteeths @shuo-wu could we have a way to improve a bit on the UI part? like showing show which volumes still using a non-default/latest image from the volume list table.

**Comment by shuo-wu** [comment]
> @smallteeths @shuo-wu could we have a way to improve a bit on the UI part? like showing show which volumes still using a non-default/latest image from the volume list table.

I think YES. The volume and its engine will record which instance manager they are using. And UI is capable of fetching the instance manager info via REST API as well as the default instance manager image from the setting.
Let's open a separate ticket to track it if we decide to do so.
