### ISSUE TITLE
[FEATURE] Upgrade longhorn engine automatically

### ISSUE THREAD

**Issue by gitlawr** [longhorn/longhorn#2152]
**Is your feature request related to a problem? Please describe.**
Currently, users need to upgrade the engine image manually in the UI after the longhorn manager is updated.

**Describe the solution you'd like**
Be able to upgrade engines without UI interactions. For example, provide an option. When it is enabled, upgrade engine images once the longhorn manager is updated.

**Describe alternatives you've considered**
Call the API to upgrade engines for automation.

**Comment by PhanLe1010** [comment]
**Manual test plan:**
1. Install Longhorn using `longhorn-manager:master`
1. Turn on the setting `Automatically upgrade engine for volumes after upgrading Longhorn`
1. Create a volume attached to a pod write some data. Create a DR volume. Create volume and leave it in detached state.
1. For each test scenario below, try to upgrade Longhorn with longhorn engine image from `From` column to `To` column

   Test scenarios:

   |  From | To  | Expected  |  
   |---|---|---|
   | lower valid lower semantic version (`longhorn-engine/v1.0.2`)|  higher valid semantic version (`longhorn-engine/v1.1.0`)| Auto upgrade  |
   | higher valid semantic version (`longhorn-engine/v1.1.0`)  | lower valid lower semantic version (`longhorn-engine/v1.0.2`)  | Don't upgrade  |
   | valid semantic version (`longhorn-engine/v1.0.2`)  | invalid semantic version (`longhorn-engine/dev-01`) | Don't upgrade  |
   | invalid semantic version (`longhorn-engine/dev-01`) | valid semantic version (`longhorn-engine/v1.1.0`)| Don't upgrade |
   | invalid semantic version (`longhorn-engine/dev-01`) |  invalid semantic version (`longhorn-engine/dev-02`)| Don't upgrade |
   | valid semantic version (`longhorn-engine/v1.1.0`) | master (`longhorn-engine/master`) | Auto upgrade |

// Test concurrent upgrade

// Test deploy new image using Longhorn UI

// Test DR volume with healthy/unhealthy state

// Test expanding volume

**Comment by yasker** [comment]
Remember to update the chart too. The automation bot has been updated to contain the questionnaire regarding the chart and yaml update.

**Comment by PhanLe1010** [comment]
Updated the chart at https://github.com/longhorn/longhorn/pull/2220

**Comment by anupama2501** [comment]
Test scenarios verified:

1. Deploy a workload with rwx scale 10 and verify the volumes created can be used for all of them. Once the workloads are created, upgraded the image version of longhorn. Set the concurrent value to 2, verified all the volumes are upgraded in sets of 2[concurrent value].
2. While the concurrent is set to 3, and upgrade is happening , change the value to 4 - This action have no impact on the current upgrade process happening. Any future upgrades will have volumes upgraded by the count of 4.
3. Take backup for a volume when upgrade hasn't started - 
Verified two scenarios: 
> The number of volumes is more than 20. In this case, if the upgrade hasn't started on a volume, the back is initiated first and then the volume is upgrades.
> The number of volumes is less than 10 and the concurrent value is set to 1. In this case, the volume is upgraded and the backup action has to be performed once the volume is upgraded.
4. Create 10 volumes and set concurrent upgrade limit to 2. When the upgrade starts, delete all the volumes. When this action is performed, the volumes were deleted and the longhorn is not corrupted.
5. While upgrade has started, detach the nodes from the volume and verified the detached volume is upgraded. 
6. Verify that Longhorn doesn't upgrade engine image for degraded volume -- Created a volume and increased the replica count to 3 when there were 2 working nodes. This makes the volume go in degraded state. Now upgraded the longhorn image and verified the degraded volume is not upgraded, even though the concurrent value has been set to 1.
7. Verify that Longhorn doesn't upgrade engine image for DR volume - Created a DR from the existing backup that were taken. Verified when the longhorn image is upgraded and the concurrent value is set, the DR volume hasn't been upgraded.
8. Verify that Longhorn doesn't upgrade engine image for volume which is expanding -- Created a volume with huge chunk of data written to the volume. While the volume is being created, upgraded the longhorn image and verified the volume is not upgraded when the volume is expanding and the upgrading happened once the volume is created.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn master - `03/01/2021`

Validation - **Pass**

Below scenarios passed:
1. **Node failure cases**
    a. When there are volumes in the queue to be upgraded and the node is rebooted. - Once the node is back online the remaining nodes get auto upgraded.
       ```
       [longhorn-manager-qnlkv] time="2021-03-01T16:59:30Z" level=debug msg="Instance handler updated instance volume-test-3-r-98d76b15 state, old state stopped, new state running" 
[longhorn-manager-665pq] time="2021-03-01T16:59:31Z" level=error msg="error receiving next item in engine watch: rpc error: code = Unavailable desc = transport is closing" 
[longhorn-manager-665pq] time="2021-03-01T16:59:31Z" level=info msg="Receive terminated to exit"```
    b. When upgrade is in progress for a volume and the node is rebooted. - Once the node is back online the failing upgrade process successfully gets finished.

2. **Upgrade retry cases**
     a. While auto upgrade in progress keep interrupting the upgrade by node down/reboot - Longhorn keep trying to upgrade the engine until it successfully update the engine.

3. **Delete the engine image Daemon set** - Longhorn waits for engine pods to restart and then successfully upgrade the engine.

4. **Delete the instance engine manager** - Eventually, Longhorn upgrade the engine. Volumes detach and attach again and Longhorn upgrade the engine once the volume is healthy and attached.

**Comment by meldafrawi** [comment]
Closing, will track integration test implementation in a separate issue https://github.com/longhorn/longhorn/issues/2479
