### ISSUE TITLE
[FEATURE]Add new setting descriptions in the doc

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2153]
**Is your feature request related to a problem? Please describe.**
For example, the description for setting `replica-replenishment-wait-interval` is missed in the v1.1.0 doc.

**Comment by yasker** [comment]
Add `urgent` tag due to inconsistency between the product and documentation.

**Comment by khushboo-rancher** [comment]
Verified the latest doc https://longhorn.io/docs/1.1.0/references/settings/, there are few minor points as below.

1. The setting **Default Share Manager Image** is missing.

2. The setting `Automatically Cleanup System Generated Snapshot` is appearing as `Auto Cleanup System Generated Snapshot` and default value should be `True`.

3. The default value for **Default Engine Image** is appearing as below, do we want to change it something like `longhornio/longhorn-engine:v1.x.x for Longhorn v1.x.x` ?
<img width="724" alt="Screen Shot 2021-01-14 at 2 46 41 PM" src="https://user-images.githubusercontent.com/60111667/104658436-a2f51600-5677-11eb-9f4d-bf2d86afbc2b.png">

4. The Default value of **Default Instance Manager Image**, **Latest Longhorn Version** similar to above mentioned **Default Engine Image**.

5. It is good to have the settings arranged in alphabetic order on the docs like it is available on the Longhorn UI.

**Comment by yasker** [comment]
For settings like `Default Engine Image, Default Share Manage Image, Default Instance Manager Image, Latest Longhorn version`, we can remove the `Default` value part since it depends on the version - and we probably don't want to update it every time when we have a new release.

And the alphabetic order is a good idea.

**Comment by yasker** [comment]
Downgrade the priority since the previous missing settings have been added.

**Comment by anupama2501** [comment]
Verified https://v1-1-1.longhorn.io/docs/1.1.1/references/settings

All the pointers mentioned above have been addressed:
All the settings are arranged in alphabetical order and the "Auto Cleanup System Generated Snapshot" is set to true
The Default value of Default Instance Manager Image, Latest Longhorn Version similar to above mentioned Default Engine Image were removed.

**Following two points were observed:**
1. System Managed Pod Image Pull Policy and System Pods Image Pull Policy have similar descriptions. We can remove System Pods Image Pull Policy as it is not present on the longhornUI and we have System Managed Pod Image Pull Policy on the longhorn UI 
2. Auto Cleanup System Generated Snapshot can be changed to "Automatically" Cleanup which is present as on the longhornUI

**Comment by yasker** [comment]
@cclhsu Can you help to update the doc according to @anupama2501 's finding?

**Comment by khushboo-rancher** [comment]
Verified with the latest changes, the https://github.com/longhorn/longhorn/issues/2153#issuecomment-780311175 are incorported in the docs.
