### ISSUE TITLE
[BUG] Docs search tool only partially working

### ISSUE THREAD

**Issue by pulberg** [longhorn/longhorn#2155]
**Describe the bug**
Search docs for words that obviously exist, search shows no results.

**To Reproduce**
1. Go to docs, search for various words
2. See no results pulled up even though the words exist

**Expected behavior**
Search function shows correct results

![Screen Shot 2021-01-05 at 1 14 49 PM](https://user-images.githubusercontent.com/11069351/103690754-cd99ed00-4f5a-11eb-910a-960f87ce3d4b.png)

![Screen Shot 2021-01-05 at 1 14 29 PM](https://user-images.githubusercontent.com/11069351/103690772-d5599180-4f5a-11eb-98ef-8513adc7ee1b.png)

**Comment by yasker** [comment]
Thanks for @pulberg . We're working on a fix.

**Comment by yasker** [comment]
cc @jrcreative

**Comment by innobead** [comment]
@jrecreative any update?

**Comment by jenting** [comment]
Related issue https://github.com/longhorn/website/issues/200

**Comment by jenting** [comment]
Algolia Longhorn [config.json](https://github.com/algolia/docsearch-configs/blob/master/configs/longhorn.json).

**Comment by jenting** [comment]
> Algolia [Longhorn config.json](https://github.com/algolia/docsearch-configs/blob/master/configs/longhorn.json).

If we should change the `.docs-content` to `.container` https://github.com/longhorn/website/blob/1e36b7ebe4dec230dbb13fc856d934dcbd032188/layouts/partials/content.html#L3, the search `nb_hits` result increase from 31 to 15649.

But it'll miss the title, we should add a new div class in HTML to include the tile + content.

Note, I use https://docsearch.algolia.com/docs/run-your-own for the Algolia search test locally.

**Comment by jenting** [comment]
The Algolia search updated the index already. I've tried, it works.

**Comment by khushboo-rancher** [comment]
Checked with Random keyword search with one and multiple words, searched title and content. The search looks good and clicking on the search result is taking user to the respective page.

Validation - **Pass**
