### ISSUE TITLE
[QUESTION] Slow mount time on very large volumes

### ISSUE THREAD

**Issue by mikeccuk2005** [longhorn/longhorn#2168]
Slow mount time on very large disks

I have gitlab pods that are very large:
minio - 946Gi/1.4Tb ( takes around 30 mins to mount )
gitaly - 25.2Gi/500Gi ( takes around 15 mins to mount )

I later disable replication due to very long rebuild time, which keeps rebuilding every hour that never finishes.
The errors goes like this:
```

  Warning  FailedMount             9m46s (x3 over 23m)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[export], unattached volumes=[minio-server-config defa
ult-token-zb2sx export podinfo minio-configuration]: timed out waiting for the condition
  Warning  FailedMount             5m12s (x4 over 32m)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[export], unattached volumes=[podinfo minio-configurat
ion minio-server-config default-token-zb2sx export]: timed out waiting for the condition
  Warning  FailedMount             2m54s (x4 over **30m**)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[export], unattached volumes=[minio-configuration mini
o-server-config default-token-zb2sx export podinfo]: timed out waiting for the condition
  Normal   Pulled                  84s                  kubelet                  Container image "busybox:latest" already present on machine
  Normal   Created                 83s                  kubelet                  Created container configure
  Normal   Started                 83s                  kubelet                  Started container configure
  Normal   Pulling                 82s                  kubelet                  Pulling image "minio/minio:RELEASE.2017-12-28T01-21-00Z"
  Normal   Pulled                  79s                  kubelet                  Successfully pulled image "minio/minio:RELEASE.2017-12-28T01-21-00Z" in 3.288101427s
  Normal   Created                 79s                  kubelet                  Created container minio
  Normal   Started                 78s                  kubelet                  Started container minio

```

---

Environment:
ubuntu 18.04 LTS
k3s **1.19.4**

1 master 1 slave node with 2 TB ssds
disk used is 2080.18 / 3022.78 Gi

Storage class: set as 2 replicas default

---
Version: `v1.1.0`

**Comment by joshimoo** [comment]
@mikeccuk2005 I am guessing this has to do with kubernetes doing a chown on the filesystem, is your workload using a security context and running as non root?
https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/
https://github.com/kubernetes/kubernetes/issues/69699

related #2131

**Comment by mikeccuk2005** [comment]
On my minio pod I found my SecurityContext as:
```
  securityContext:                           
    fsGroup: 1000         
    runAsUser: 1000
```

**Comment by mikeccuk2005** [comment]
Update:
I update my k3s to 1.20.0 and added 
`fsGroupChangePolicy: "OnRootMismatch"`
The volume mounted less than a few minutes, very useful for statefulsets.
I wonder if this option can be made default? Since most the volume don't have use case that use different owners or application

**Comment by PhanLe1010** [comment]
Thanks @mikeccuk2005 
I will investigate the option together with the issue https://github.com/longhorn/longhorn/issues/2131

**Comment by PhanLe1010** [comment]
Hi @mikeccuk2005 

For the question:

> I wonder if this option can be made default?

No. The setting is on the pod's spec so Longhorn cannot set it. Users will have to modify that workload deployment to add fsGroupChangePolicy: "OnRootMismatch" if they want to speed up the Kubernetes mounting process for a volume with many files and with `fsGroup` set.

See https://github.com/longhorn/longhorn/issues/2131#issuecomment-778897129 for more details about some of the tests we performed.

**Comment by xiaopengcn** [comment]
> 

I had same problem, but I cannot upgrade my k8s from 1.18 to 1.20, here's my SecurityContext:
```
securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
```
and what can i do to take the same effect? Thx a lot!

**Comment by xiaopengcn** [comment]
@PhanLe1010

**Comment by PhanLe1010** [comment]
@xiaopengcn Unfortunately there is no workaround for Kubernetes 1.18 https://github.com/longhorn/longhorn/issues/2131#:~:text=The%20bad%20news%20is%20that%20there%20is%20no%20workaround%20for%20this%20problem%20in%20K8s%20version%20v1.19%20and%20before.

**Comment by kwenzh** [comment]
> @xiaopengcn Unfortunately there is no workaround for Kubernetes 1.18 as far as I know: [The bad news is that there is no workaround for this problem in K8s version v1.19 and before. The good news is that K8s v1.20 provides 2 options to solve this problem as discussed in the following sections.](https://github.com/longhorn/longhorn/issues/2131#issuecomment-778897129)

in 1.18.19  `fsGroupChangePolicy` is alpha , need enable kube-apiserver、kube-controller-manager 、kubelet `--feature-gates=ConfigurableFSGroupPolicy=true`
