### ISSUE TITLE
[QUESTION] RWX volume fails to attach to a pod on ubuntu

### ISSUE THREAD

**Issue by huang12zheng** [longhorn/longhorn#2170]
**Describe the bug**
RWX volume fails to attach to a pod on ubuntu

maybe like https://github.com/longhorn/longhorn/issues/2093
but I really install nfs-common

```sh
sudo apt install nfs-common
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nfs-common is already the newest version (1:1.3.4-2.1ubuntu5.3).
0 upgraded, 0 newly installed, 0 to remove and 244 not upgraded.
```
**To Reproduce**
* PVC, attached to  a pod (traefik),with RWX using longhorn storage class. 

```
MountVolume.SetUp failed for volume "pvc-d97abca5-0034-403d-a619-e27dc44dca18" : rpc error: code = Internal desc = mount failed: exit status 32 Mounting command: /usr/bin/systemd-run Mounting arguments: [--description=Kubernetes transient mount for /var/lib/kubelet/pods/e968399b-fad2-4811-8afd-72187a9a4341/volumes/kubernetes.io~csi/pvc-d97abca5-0034-403d-a619-e27dc44dca18/mount --scope -- /bin/mount -t nfs -o vers=4.1,noresvport,soft,sync,intr,timeo=7,retrans=3 172.16.253.0:/pvc-d97abca5-0034-403d-a619-e27dc44dca18 /var/lib/kubelet/pods/e968399b-fad2-4811-8afd-72187a9a4341/volumes/kubernetes.io~csi/pvc-d97abca5-0034-403d-a619-e27dc44dca18/mount] Output: Running scope as unit: run-r409c75cc2fb249fab1c1d95e51ff4591.scope mount.nfs: an incorrect mount option was specified
```
```
Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data tmp traefik-token-dpzss]: timed out waiting for the condition
```

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.1.0 (from helm)
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: TKE
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version: ubuntu
   - CPU per node: 2
   - Memory per node: 4GB
   - Disk type(e.g. SSD/NVMe): VD
   - Network bandwidth between the nodes: 3m
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): TKE

**Comment by joshimoo** [comment]
@huang12zheng can you run the below command on the host? 
`/bin/mount -t nfs -o vers=4.1,noresvport,soft,sync,intr,timeo=7,retrans=3 172.16.253.0:/pvc-d97abca5-0034-403d-a619-e27dc44dca18 \tmp\nfs-mount`

**Comment by huang12zheng** [comment]
```
sudo /bin/mount -t nfs -o vers=4.1,noresvport,soft,sync,intr,timeo=7,retrans=3 172.16.255.192:/pvc-d682e4d7-9c70-4c51-9347-f0bd0cb2f943 \tmp\nfs-mount

mount.nfs: mount point tmpnfs-mount does not exist
```

**Comment by joshimoo** [comment]
Does the below mount command work?
`sudo /bin/mount -t nfs -o vers=4.1 172.16.255.192:/pvc-d682e4d7-9c70-4c51-9347-f0bd0cb2f943 \tmp\nfs-mount`

This uses the default mount options, if the above does not work, then nfs4 is not available on the node.

**Comment by huang12zheng** [comment]
```
sudo /bin/mount -t nfs -o vers=4.1 172.16.255.192:/pvc-d682e4d7-9c70-4c51-9347-f0bd0cb2f943 /tmp/nfs-mount

mount.nfs: an incorrect mount option was specified
```
```
sudo /bin/mount -t nfs -o 172.16.255.192:/pvc-d682e4d7-9c70-4c51-9347-f0bd0cb2f943 /tmp/nfs-mount

mount: /tmp/nfs-mount: can't find in /etc/fstab.
```

**Comment by joshimoo** [comment]
if you try to mount in nfs3 it will not work, but the command would be the below, withhout the -o
`sudo /bin/mount -t nfs -o 172.16.255.192:/pvc-d682e4d7-9c70-4c51-9347-f0bd0cb2f943 /tmp/nfs-mount`

**Comment by huang12zheng** [comment]
```
lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```
```
sudo /bin/mount -t nfs 172.16.255.192:/pvc-d682e4d7-9c70-4c51-9347-f0bd0cb2f943 /tmp/nfs-mount

mount.nfs: Connection timed out
```
 TKE  is "tencent kubernetes engine"
```
kubectl version

Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.4-tke.6", GitCommit:"194201819cf1e5cf45d38f72ce1aac9efca4c7ff", GitTreeState:"clean", BuildDate:"2020-12-25T06:58:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.4-tke.3", GitCommit:"f8797eb035aca9c928af02ea9a74d232cfd41bc6", GitTreeState:"clean", BuildDate:"2020-10-12T03:32:01Z", GoVersion:"go1.14.8", Compiler:"gc", Platform:"linux/amd64"}
```
Runtime: 	containerd 
Service CIDR   172.16.252.0/22
Kube-proxy: 	iptables
Number of nodes  1
Network mode   cni

It is Standard managed cluster in TKE,  which means I don't know the information on Master&ETCD

**Comment by joshimoo** [comment]
link to https://github.com/longhorn/longhorn/issues/2033 to ensure installation of nfs client.

**Comment by huang12zheng** [comment]
Sorry for not replying
I have get it. thank you.
I would close it and sub #2033
