### ISSUE TITLE
[BUG] UI fails to deploy when only IPv4 is enabled on nodes

### ISSUE THREAD

**Issue by nikkelma** [longhorn/longhorn#2174]
**Describe the bug**
Longhorn UI does not come up healthy when cluster nodes only support IPv4

**To Reproduce**
1. Disable IPv6 on nodes
2. Build RKE cluster
3. Install Longhorn 1.1.0
4. See error `Address family not supported by protocol` in `longhorn-ui` deployment

**Expected behavior**
Longhorn UI comes up successfully.

**Log**

**Environment:**
 - Longhorn version: v1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE 1.18
   - Number of management node in the cluster:
   - Number of worker node in the cluster
 - Node config
   - OS type and version: RHEL 7
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): vSphere

**Comment by nikkelma** [comment]
Known workaround exists - providing in edit to this comment

**Comment by nikkelma** [comment]
Known workaround provided above, and as mentioned a fix has been put into the UI already. Closing as this was created mainly for future reference.

**Comment by yasker** [comment]
The retagged `longhornio/longhorn-ui:v1.1.0` should have the fix now.
