### ISSUE TITLE
[FEATURE] Provide multiarch image for longhorn-ui

### ISSUE THREAD

**Issue by FlexibleToast** [longhorn/longhorn#2175]
**Is your feature request related to a problem? Please describe.**
When deploying Longhorn on arm64 everything deploys without issue with the exception of longhorn-ui. I edited the deployment to change the container image to be longhornio/longhorn-ui:v1.1.0-arm64 and it deployed just fine.

**Describe the solution you'd like**
If a multiarch image is provided it will "just work"

**Describe alternatives you've considered**
Manually editing the deployment for longhorn-ui to point to arm image.

**Comment by yasker** [comment]
@FlexibleToast `longhornio/longhorn-ui:v1.1.0` should work for ARM64 now. Can you retry? Remember to set image pull policy to always.

**Comment by FlexibleToast** [comment]
I changed the image back to longhornio/longhorn-ui:v1.1.0 and changed the image pull policy. I can confirm it is working my arm64 cluster.

**Comment by yasker** [comment]
Thanks @FlexibleToast for confirmation. I will close the issue then.
