### ISSUE TITLE
[Question] Different sizes reported for PVC 

### ISSUE THREAD

**Issue by nsmith5** [longhorn/longhorn#2176]
**Question**

I've found a curious discrepancy in sizes reported for a longhorn PVC. I've likely missed something obvious so I've posted as a question, but I'm happy to change this as a bug report if I haven't made a mistake

I have a PVC in longhorn:

```
$ kubectl get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
minio   Bound    pvc-b6693e98-5557-4042-b5d4-fdd75a93660a   350Gi      RWO            rust           14d
```

The storage class is replication factor 3 and sits on some spinning disk hard drives (hence the storage class name). The longhorn UI reports 42Gi size of the volume and this is corroborated by SSHing on to the host and looking at the size of a replica:

```
alpha [/mnt/longhorn/replicas]$ sudo du -h ./pvc-b6693e98-5557-4042-b5d4-fdd75a93660a-d2984418
42G     ./pvc-b6693e98-5557-4042-b5d4-fdd75a93660a-d2984418
``` 

The odd thing is that if I `exec` onto the pod (a minio instance) and take a look at the size there it only reports 11.8Gi used:

```
# Inside minio pod, PVC mounted on /export
/ $ df -h /export
Filesystem                Size      Used Available Use% Mounted on
/dev/longhorn/pvc-b6693e98-5557-4042-b5d4-fdd75a93660a
                        343.5G     11.8G    331.7G   3% /export
```

**Environment:**
 - Longhorn version: v1.1.0
 - Kubernetes version: k3s 1.19.5-k3s1
 - Node config
   - OS type and version: k3os v0.19.5-rc1
   - CPU per node: 2
   - Memory per node: 8Gi
   - Disk type: crappy laptop hard drive
   - Network bandwidth and latency between the nodes: 1 GBit ethernet
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Comment by PhanLe1010** [comment]
@nsmith5 

1. It is not recommended to use Longhorn with spinning disks. You should use SSD instead. It might cause IO timeout and constantly rebuilding which degrade Longhorn system.

2. There are 2 different sizes concept here:
   * The size of Longhorn block device: 
   > The storage class is replication factor 3 and sits on some spinning disk hard drives (hence the storage class name). The longhorn UI reports 42Gi size of the volume and this is corroborated by SSHing on to the host and looking at the size of a replica:

   * The size of filesystem on top of Longhorn block device:
   > The odd thing is that if I exec onto the pod (a minio instance) and take a look at the size there it only reports 11.8Gi used:

   The size of the filesystem reflects the space occupied by existing files. The actual size of the Longhorn block device reflects the space occupied by all blocks that were ever written to the Longhorn volume. For example, you create a filesystem on top of a Longhorn block device. you create 2 files in the filesystem: file1 of size 0.5GM, and file2 of size 1.5GB. Now the size of the filesystem and the actual size of the Longhorn block device are both 2GB. Now, you delete file2 from the filesystem. The size of the filesystem goes down to 0.5GB but the actual size of the Longhorn block device remains as 2GB.

Related to https://github.com/longhorn/longhorn/issues/2165#issuecomment-759205621

**Comment by nsmith5** [comment]
Ahha! I missed that section of the manual in the docs. Thanks so much!
