### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by piaohai** [longhorn/longhorn#218]
great job, i'm very interesting in this block project, i want to find some block storage for mysql storage system

it some performance about IOPS compare with ceph? @yasker  thanks.

**Comment by yasker** [comment]
We haven't done much performance test recently. And we haven't start tuning performance at all. Our previous preliminary benchmark shows a decent performance (at least to our satisfaction) without tuning, with a decent speed network and SSD.

**Comment by AmreeshTyagi** [comment]
I tried to test performance of MySQL db using longhorn storageclass & observed huge performance issue then running a MySQL instance inside plain docker container or running it on my local machine.

I didn't want to spend so much time on this, so just created one simple table & stored proc to insert some test data.

**CREATE TABLE `student` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `student` varchar(50) DEFAULT NULL,
  `age` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12501 DEFAULT CHARSET=latin1;**


**DELIMITER $$
CREATE PROCEDURE `populate`(in num int)
begin
declare i int default 0;
while i < num do
insert into student (student,age) values (concat('student',i),20);
set i = i + 1;
end while;
end$$
DELIMITER ;**

Query executed from phpmyadmin on all 3 instances:
`call populate (500);`

1.  For local & docker instance with both bind volume & without bind volume option:

**Time taken to execute query: Avg - 0.750 sec**

2. For MySQL instance installed on Rancher Kubernetes cluster from Helm chart without any PV (not useful at all on production):

**Time taken to execute query: Avg -0.840 sec**

3. For MySQL instance installed on Rancher Kubernetes cluster from Helm chart using longhorn volume:

**Time taken to execute query: Avg -18.939 sec**

I am still trying to solve this problem using `local-storage` as I see no impact of running database on Kubernetes (confirmed from 2nd test). Just for now, I can live without managing database volumes using longhorn & will setup some cron jobs to take regular backups of local volumes to NFS.

Please let me know, if I am doing something wrong with longhorn. Have you ever faced such issue or tried something similar?

**Comment by yasker** [comment]
@AmreeshTyagi Thanks for the report.

I think your test case is IOPS intensive, which we are aware that there is plenty of room for improvement.

With Longhorn, you need to have a decent network connecting the nodes, which can be a bottleneck. I've just tried your case in Digital Ocean and GKE, both give me around 4.7s.

With the Longhorn become more feature complete and better in the usability, we're starting to shift our focus to the performance.

**Comment by Moumouls** [comment]
Hi everyone,
I'just made a bench test with `bonnie++` between `Longhorn`, `OpenEBS Jiva`, `Without Volume`
Here are stats, i hope that will help people that search performance results.

```
Without Volume
Data 4GB
Write: 191 473 KB/sec
ReadWriteDelete: 166 443 KB/s
Read: 2 976 754 KB/s

Longhorn (3 replica)
Data: 4GB
Write: 5 728 KB/sec
ReadWriteDelete: 5 745 KB/s
Read: 2 820 495 KB/s

OpenEBS Jiva (3 replica)
Data: 4GB
Write: 4 929 KB/sec
ReadWriteDelete: 3 688 KB/s
Read: 3 024 698 KB/s

Context: 3 Node (2 VCPU, 80SSD and 7GB RAM each), same datacenter, OVH
```
@yasker write performance is low, for you it seems correct ? (bonnie is IOPS intensive i guess)

**Comment by yasker** [comment]
@Moumouls This result is a bit weird. On the one side, read performance is way too high, 3G/per second is unlikely real, I suspect there is a cache; on the other side, the write performance is way too low, I suspect the CPU is the bottombeck. If it's IOPS intense, it's better if we can know the block size, and IOPS per second. Also, it's interesting to see what's the result of Ceph. 

Also, we haven't spent much effort on tuning Longhorn's performance. We normally use FIO for block device benchmark, with a few different block sizes, and make sure the data is written in direct IO mode. You may want to give FIO a try.

**Comment by Moumouls** [comment]
@yasker thanks for the tips. I'have updated my comment.
I just made a test of a full init of an app (Axelor) with volumes mapped to data (tomcat files) and database directory (postgres)

```
Axelor init time HostPath: 7min
Axelor init time Longhorn: 10min
Context: 3 Node (2 VCPU, 80SSD and 7GB RAM each), same datacenter, OVH
```

In real use case performance seems now ok !
I'm going to make complementary tests with FIO

**Comment by h0lk** [comment]
Hi @yasker,

We are currently evaluating, if we can switch to a distributed storage solution for our Rancher vSphere clusters to replace the native vsphere storage (currently using in-tree as vsphere is < v7), which - at times - is quite flunky.

Some of the deployments we have are unfortunately very I/O sensitive, so I am trying to figure out how much of a decline in performance we will have. This is why I am running some performance tests comparing local-path/vsphere (which have pretty much identical performance) with longhorn v1.2 and rook-ceph v1.7.2.

To be honest, I don't understand the results I am getting, as they are very bad on the distributed storage side (for both longhorn and ceph), so maybe I am doing something wrong?

For benchmarking I mostly relied on the https://github.com/yasker/kbench test, but also did some general iperf / dd steps to establish a baseline.

BASELINE:

iperf over 60s:
~ 5 GBit (best-case, for communication between two nodes on the same physical host)
~ 900 MBit (worst-case, for communication between two nodes on different physical hosts)

dd if=/dev/zero of=here bs=1G count=1 oflag=direct
`1073741824 bytes (1.1 GB, 1.0 GiB) copied, 4.20552 s, 255 MB/s`

From those results I presumed, that the default 30GB PVC of kbench should be more than sufficient to avoid cache (5 GBit * 25 = ~15.6 GB)

kbench standalone results for local-path / vsphere in-tree kbench (average of 5 runs) are as follows:
```
IOPS (Read/Write)
  Random:   1204 / 22010
  Sequential: 7960 / 22099
  CPU Idleness: 70%

Bandwidth in KiB/sec (Read/Write)
  Random: 144,463 / 495,160
  Sequential: 722,922 / 636,442
  CPU Idleness: 75%

Latency in ns (Read/Write)
  Random: 14,326,507 / 397,082
  Sequential: 1,289,344 / 377,331
  CPU Idleness: 74%
```

I then compared vsphere/longhorn vsphere/ceph and longhorn/ceph, where both distributed system were configured to keep 3 replicas spread over multiple physical hosts (worst BW scenario):
```
================================
FIO Benchmark Comparsion Summary
For: vsphere vs Longhorn
SIZE: 30G
QUICK MODE: DISABLED
================================
                              vsphere      vs                 Longhorn    :              Change
IOPS (Read/Write)
        Random:           1,467 / 24,981   vs              811 / 1,443    :   -44.72% / -94.22%
    Sequential:          10,556 / 25,520   vs            3,811 / 2,795    :   -63.90% / -89.05%
  CPU Idleness:                      72%   vs                      48%    :                -24%

Bandwidth in KiB/sec (Read/Write)
        Random:        142,946 / 483,583   vs          69,222 / 27,082    :   -51.57% / -94.40%
    Sequential:        717,757 / 646,241   vs         100,296 / 30,402    :   -86.03% / -95.30%
  CPU Idleness:                      78%   vs                      45%    :                -33%

Latency in ns (Read/Write)
        Random:     17,399,691 / 318,467   vs   16,328,140 / 4,767,117    :   -6.16% / 1396.90%
    Sequential:      1,590,285 / 321,547   vs    3,744,054 / 4,509,962    :  135.43% / 1302.58%
  CPU Idleness:                      78%   vs                      66%    :                -12%

================================
FIO Benchmark Comparsion Summary
For: vsphere vs ceph
SIZE: 30G
QUICK MODE: DISABLED
================================
                                 vsphere   vs                     ceph    :              Change
IOPS (Read/Write)
        Random:             967 / 21,653   vs                777 / 886    :   -19.65% / -95.91%
    Sequential:           8,520 / 20,253   vs                702 / 763    :   -91.76% / -96.23%
  CPU Idleness:                      69%   vs                      62%    :                 -7%

Bandwidth in KiB/sec (Read/Write)
        Random:        148,331 / 477,384   vs          79,271 / 36,099    :   -46.56% / -92.44%
    Sequential:        763,028 / 567,657   vs         113,277 / 30,039    :   -85.15% / -94.71%
  CPU Idleness:                      64%   vs                      63%    :                 -1%

Latency in ns (Read/Write)
        Random:     11,390,927 / 421,355   vs 24,575,176 / 348,190,854    : 115.74% / 82535.98%
    Sequential:      1,153,712 / 411,457   vs   7,540,324 / 33,412,297    :  553.57% / 8020.48%
  CPU Idleness:                      74%   vs                      67%    :                 -7%


================================
FIO Benchmark Comparsion Summary
For: longhorn vs ceph
SIZE: 30G
QUICK MODE: DISABLED
================================
                                longhorn   vs                     ceph    :              Change
IOPS (Read/Write)
        Random:                507 / 801   vs              799 / 1,113    :     57.59% / 38.95%
    Sequential:            2,170 / 1,551   vs                868 / 924    :   -60.00% / -40.43%
  CPU Idleness:                      47%   vs                      67%    :                 20%

Bandwidth in KiB/sec (Read/Write)
        Random:          74,736 / 29,953   vs          80,697 / 21,504    :     7.98% / -28.21%
    Sequential:         140,356 / 43,907   vs         108,995 / 27,622    :   -22.34% / -37.09%
  CPU Idleness:                      36%   vs                      69%    :                 33%

Latency in ns (Read/Write)
        Random:   17,468,093 / 6,125,374   vs 20,407,513 / 323,664,604    :   16.83% / 5184.00%
    Sequential:    3,726,745 / 5,531,482   vs   6,282,552 / 92,793,978    :   68.58% / 1577.56%
  CPU Idleness:                      56%   vs                      84%    :                 28%
```

I also did some standalone kbench tests for each, but they more or less confirmed the results above.
Trying to rule out BW as my bottleneck, I configured a separate longhorn storageclass to keep only a single replica and did another comparison:
```
================================
FIO Benchmark Comparsion Summary
For: longhorn-single vs longhorn
SIZE: 30G
QUICK MODE: DISABLED
================================
                         longhorn-single   vs                 longhorn    :              Change
IOPS (Read/Write)
        Random:              764 / 2,017   vs                755 / 896    :    -1.18% / -55.58%
    Sequential:            3,766 / 3,348   vs            3,189 / 1,505    :   -15.32% / -55.05%
  CPU Idleness:                      42%   vs                      42%    :                  0%

Bandwidth in KiB/sec (Read/Write)
        Random:          54,010 / 75,360   vs          75,282 / 33,579    :    39.39% / -55.44%
    Sequential:         104,818 / 68,571   vs         140,474 / 47,664    :    34.02% / -30.49%
  CPU Idleness:                      42%   vs                      36%    :                 -6%

Latency in ns (Read/Write)
        Random:   21,460,384 / 2,744,107   vs   17,864,406 / 6,888,851    :   -16.76% / 151.04%
    Sequential:    3,580,601 / 3,675,651   vs    3,800,925 / 7,019,119    :      6.15% / 90.96%
  CPU Idleness:                      59%   vs                      51%    :                 -8%
```

I am somewhat baffeld by these results. Shouldn't performance drastically increase if I take away the distribution part? Obviously write performance improved a little, but it is nowhere near local-path / vsphere BW.

As I'm no expert on storage, I didn't try optimizing anything in the longhorn / ceph setups and just went with the defaults. So maybe it's simply a configuration issue, but I wouldn't know where to begin.

If anyone can provide input on what to try or do differently, I would greatly appreciate it.
