### ISSUE TITLE
[Question] RWX CSI volume path not created

### ISSUE THREAD

**Issue by dgiebert** [longhorn/longhorn#2180]
**Question**

Very glad to see Longhorn adding RWX Volumes in v1.1.0 !
While trying to setup an RWX Volume and attaching it to a Pod the following things happen:
1. `share-manager-pvc-19de584c-bb96-4de7-9f4c-77c571208a72` is created
2. Volume is marked as healthy and ready by Kubernetes `AttachVolume.Attach succeeded`

The next step of mounting the volume on the host fails with:
```
MountVolume.SetUp failed for volume "pvc-19de584c-bb96-4de7-9f4c-77c571208a72" : rpc error: code = Internal desc = mount failed: exit status 1 Mounting command: /bin/mount Mounting arguments: [-t nfs -o vers=4.1,noresvport,soft,sync,intr,timeo=7,retrans=3 10.43.84.168:/pvc-19de584c-bb96-4de7-9f4c-77c571208a72 /opt/rke/var/lib/kubelet/pods/531771c8-9fe8-4d68-9e8d-fa87f5c91684/volumes/kubernetes.io~csi/pvc-19de584c-bb96-4de7-9f4c-77c571208a72/mount] Output: nsenter: failed to execute /bin/mount: No such file or directory
```
Verified and the location does not exist on the host, using the mount command manually to e.g. `/tmp/mount` works, also other  Longhorn volumes work on the same nodes.

```
ls -al /opt/rke/var/lib/kubelet/pods/531771c8-9fe8-4d68-9e8d-fa87f5c91684/volumes/kubernetes.io~csi
total 8
drwxr-x--- 2 root root 4096 Jan 13 14:24 .
drwxr-x--- 4 root root 4096 Jan 13 14:05 ..
```

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version: 1.18.8
 - Node config
   - OS type and version: RancherOS 
   - CPU per node: 16
   - Memory per node: 128G
   - Disk type: NVMe SSD
 - Underlying Infrastructure: Baremetal

**Comment by joshimoo** [comment]
Is `/bin/mount` and `/bin/mount.nfs` available on the node?

**Comment by dgiebert** [comment]
`/bin/mount.nfs` does not exist

```
whereis mount.nfs
mount: /bin/mount /sbin/mount.nfs /sbin/mount.nfs4
```

**Comment by joshimoo** [comment]
@dgiebert did you run the last command above on the physical node or inside of a pod?
We create the mount folder as part of the csi attach call in the case where it's absent.

**Comment by dgiebert** [comment]
I ran the last command on the physical node to test connectivity to the nfs pod.

**Comment by joshimoo** [comment]
It seems you are using rancher os which we don't support since it's end of life, are you able to use a regular os (ubuntu, rhel, sles, k3os, etc)

**Comment by joshimoo** [comment]
Does this happen for each rwx volume that you are trying to use?

**Comment by joshimoo** [comment]
@khushboo-rancher are we able to replicate this on one of our supported environments?

**Comment by dgiebert** [comment]
Happens to all RWX volumes I tried to attach.

Is there a way I can debug this ?

**Comment by joshimoo** [comment]
@dgiebert you can exec into the csi plugin container that is running on the node where the volume is supposed to get mounted then run the below nsenter command to get a shell on the host where the actual mount will be executed.

You can get the shell to the longhorn container via rancher ui or kubectl exec

```
root@longhorn-csi-plugin-t9zpr:/# nsenter --mount=/proc/1/ns/mnt --net=/proc/1/ns/net --uts=/proc/1/ns/uts -- /bin/bash
root@longhorn-demo-work1:/
```

Once you are having a shell that is operating in the same namespaces as the actual mount that the plugin is trying to do, you can run the failed mount command above and then go from there.

`/bin/mount -t nfs -o vers=4.1,noresvport,soft,sync,intr,timeo=7,retrans=3 10.43.84.168:/pvc-19de584c-bb96-4de7-9f4c-77c571208a72 /opt/rke/var/lib/kubelet/pods/531771c8-9fe8-4d68-9e8d-fa87f5c91684/volumes/kubernetes.io~csi/pvc-19de584c-bb96-4de7-9f4c-77c571208a72/mount`

**Comment by khushboo-rancher** [comment]
@joshimoo We have not seen this issue on the environments which we use for test which are as below.

Below OS with K8s v18.x/v19.x and K3s v19.x
1. Ubuntu 20.04/18.04
2. Linux2(aws)
3. SLES 15 SP1 / SLES 12 SP2 / SLES 12 SP5
4. RHEL 7.8
5. Cent OS

**Comment by dgiebert** [comment]
Will k3os be supported in the future and be in tested, as you suggested the usage above ?

Thank you @joshimoo, this pointed me to the reason for it and can be sumarized by the following:
Namespace 1 on RancherOS is the system-docker that starts the other containers which does not contain anything.

Maybe the namespace to use is configurable, can you point me to the code, I can have a look and close this question ?

**Comment by joshimoo** [comment]
Sure thing, the longhorn-csi-plugin is running with hostPid = true which means we should be seeing the world from the host perspective.

The relevant lines to change are here:
https://github.com/longhorn/longhorn-manager/blob/master/csi/nfs/nsenter.go#L16-L38

**Comment by joshimoo** [comment]
@dgiebert If you want to try you should be able to run longhorn on k3os successfully.

**Comment by joshimoo** [comment]
Closing, please feel free to open if you have this issue with a supported os configuration.
