### ISSUE TITLE
[Question] How to enable metrics?

### ISSUE THREAD

**Issue by Patralos** [longhorn/longhorn#2182]
Hi, 
According to the release notes longhorn 1.1 shoud support prometheus metrics, but there is no information available on how to enable them.

I just found some information in the feature ticket about it: 
```
Basic verifying/testing steps for QA:

Create a Prometheus-Alermanager-Garafa system using the Prometheus Operator.

Nagivate to Prometheus server's web UI. Verify that Prometheus successfully dicorvers all longhorn manager targets.

Verify Longhorn correctly exposes the above metrics

Deploy workloads that use Longhorn volumes into the cluster. Verify that there is no abnormal data. e.g: volume capacity is 0, CPU usage is over 4000 milicpu, etc..

Attach a volume. Detach the volume. Verify that the volume's information is reported by at most 1 longhorn-manager at any time.
```

But there is no Longhorn manager target added automatically.

**Comment by joshimoo** [comment]
@Patralos does the following documentation help?
https://longhorn.io/docs/1.1.0/monitoring/prometheus_and_grafana_setup/

@PhanLe1010 can you elaborate on this.

**Comment by Patralos** [comment]
> @Patralos does the following documentation help?
> https://longhorn.io/docs/1.1.0/monitoring/prometheus_and_grafana_setup/

Yes this helps, I wasnt able to find it before. I will try it out tomorrow and report back.

**Comment by PhanLe1010** [comment]
Longhorn metrics are enabled by default on pods in `longhorn-backend` service.

The [doc](https://longhorn.io/docs/1.1.0/monitoring/prometheus_and_grafana_setup/) presents how to set up Prometheus and set it up to scrape Longhorn metrics.

Other alternative ways to setup Prometheus are [rancher monitoring project](https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/) or [prometheus-operator/kube-prometheus-stack](https://github.com/prometheus-operator/kube-prometheus)

**Comment by Patralos** [comment]
Using the docs I was able to configure it into our prometheus operator setup.

Sadly the current available metrics are still rather useless for us, as monitoring volume usage with them is still not possible. longhorn_volume_actual_size_bytes is heavily affected by snapshots and there is no other variable to monitor the actual usage.

Thx for your help anyways!

**Comment by PhanLe1010** [comment]
@Patralos 

I believe you are referring to the usage of a filesystem inside the Longhorn volume. We do support those metrics. See https://longhorn.io/docs/1.1.0/monitoring/kubelet-volume-metrics/ .

**Comment by Patralos** [comment]
Great thanks, that helped a lot!
