### ISSUE TITLE
[DOC] Improve monitoring feature documentation

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2188]
The [document](https://longhorn.io/docs/1.1.0/monitoring/kubelet-volume-metrics/) for `kubelet_volume_*` metrics is not clear about how the users can find those metrics in Rancher monitoring V2

Also, need to update the document so specify that Rancher monitoring V1 is deprecated and we only support V2

For the page https://longhorn.io/docs/1.1.0/monitoring/prometheus_and_grafana_setup/ , we should mention that if the user is using Rancher or other monitoring solutions based on Prometheus operator, those steps might be skipped and refer them to the Rancher page instead.

**Comment by innobead** [comment]
Closing first, because the doc has been updated.
