### ISSUE TITLE
[Question] Incremental backups and maximum retains?

### ISSUE THREAD

**Issue by MrDienns** [longhorn/longhorn#2191]
**Question**

I had a question about the way Longhorn manages backups. This likely applies to other storage solutions, but considering I'm using Longhorn, I hope it's okay to ask here.

I'm slightly confused about how incremental backups work in relation to Longhorns retain quantity. If I understand correctly, Longhorn makes backups incremental, which means the backup only contains the data which has been changed compared to the previous backup (also incremental).

However, if I create a backup every day, and have a maximum retain quantity configured of 30, how will my backup work after the 31st day? The backup of day 1 would be deleted on the 31st day. Will any of the backups that came after the 1st day still work if the 1st day backup was deleted automatically?

As a side note: is it possible to make full backups instead of incremental?

**Environment:**
 - Longhorn version: v1.1.0
 - Kubernetes version: v1.19.5-k3s2
 - Node config
   - OS type and version: Debian 10
   - CPU per node: 4c/8t
   - Memory per node: 32 GB
   - Disk type: SSD
   - Network bandwidth and latency between the nodes: 2 Gbit/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**

**Comment by shuo-wu** [comment]
Longhorn will track the data blocks (the basic unit of the Longhorn backup) for each backup. As a result, Longhorn will remove the data blocked that used by the backup only when users decide to delete the backup. In your example, if a data block is used by the backup on 1st day and the backups after the 1st day, it won't be removed with the 1st backup on the 31st day.

**Comment by MrDienns** [comment]
Alright, so I do not have to worry about backups suddenly not working anymore after an x period of time. That would've been weird if that was the case anyway, but I wanted to make sure. Thank you.
