### ISSUE TITLE
[QUESTION] Can longhorn be used across clusters？

### ISSUE THREAD

**Issue by FranEva** [longhorn/longhorn#2192]
Can it be used across clusters instead of restoring data through backup？
Also, when one of my workloads applied for a PV, I found that the pod could only be fixed on the node with data, and could not be dynamically scheduled to other nodes in the cluster.
![image](https://user-images.githubusercontent.com/4972269/104982090-dacbd700-5a44-11eb-8191-27bad82b5bc9.png)

---
Version: `v1.1.0`

**Comment by joshimoo** [comment]
@FranEva You can use the iscsi frontend to use the volumes across clusters.
https://longhorn.io/docs/1.1.0/advanced-resources/iscsi/
But it's much nicer and better to use longhorn in the same cluster as the workloads.

The pods can be dynamically scheduled, but kubernetes can decide to schedule the pod to the same node :)
On the other hand if you try to use an RWO volume from 2 different nodes at the same time, you will get a multi attach error.

**Comment by michaelandrepearce** [comment]
Sounds like a nice idea though to be able to pool all your disks from host across different clusters so you have a global storage pool than can then be taken from so that you get better disk utilisation.

**Comment by yasker** [comment]
Longhorn is designed to work within the cluster, so it would be hard to identify the disks outside the cluster. Also, we need to make sure the connection between the nodes is good enough for data transfer, which will also be a problem.

**Comment by joshimoo** [comment]
Closing, feel free to reopen if you require further clarifications.
