### ISSUE TITLE
[BUG] Wrong ui size sorting

### ISSUE THREAD

**Issue by viceice** [longhorn/longhorn#2193]
**Describe the bug**
A picture say's more that thousands words 😉 

![image](https://user-images.githubusercontent.com/1798109/104992573-a4309500-5a21-11eb-8657-eb2e2f5a225f.png)

**To Reproduce**
1. Create volumes of diffentent sizes
2. Click on volume size order
3. See wrong ordering

**Expected behavior**
As the json values from server are all in same magnitude, the uui should use that values for size sorting

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: v1.1.0 (Helm)
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s (not relevant)
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster 1
 - Node config (not relevant)
   - OS type and version: ubuntu 20.04
   - CPU per node: 4-8
   - Memory per node: 4 manager / 8 worker
   - Disk type(e.g. SSD/NVMe): HDD / SSD
   - Network bandwidth between the nodes: 2x10GBit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Additional context**
I can send a pr

**Comment by viceice** [comment]
Looks like `size` is returned as string, so fo the browser will sort it as string [here](https://github.com/longhorn/longhorn-ui/blob/f61d662f3623bc990c36c4afb39f412ad137c868/src/routes/volume/VolumeList.js#L171)


Also `actualSize` sorting is wrong [here](https://github.com/longhorn/longhorn-ui/blob/f61d662f3623bc990c36c4afb39f412ad137c868/src/routes/volume/VolumeList.js#L198]. It's sorted by `size` and has wrong order too.

**Comment by viceice** [comment]
State should sort by robustness, if volume is attached [here](https://github.com/longhorn/longhorn-ui/blob/f61d662f3623bc990c36c4afb39f412ad137c868/src/routes/volume/VolumeList.js#L97)

**Comment by khushboo-rancher** [comment]
Validate with longhorn-ui:master `01/25/2021`

Validation : **Pass**

The sorting based on the size is working fine.
