### ISSUE TITLE
[QUESTION] The snapshot created by longhorn-ui page cannot be found in k8s

### ISSUE THREAD

**Issue by yyt6200** [longhorn/longhorn#2194]
I'm not sure what the specific problem is. I successfully created a snapshot in Longhorn's management interface, but I couldn't find the created snapshot through kubectl get volumessnapshot -- all-namespaces. The k8s version is 1.18.8. The version of Longhorn is V1_ 20201216-arm64。

**Comment by yyt6200** [comment]
![image](https://user-images.githubusercontent.com/44914868/104993758-44a4aa80-5a5e-11eb-8da0-c86707a0b433.png)
![image](https://user-images.githubusercontent.com/44914868/104993807-5d14c500-5a5e-11eb-8e59-a19c62bfacb3.png)

**Comment by yyt6200** [comment]
Create a snapshot through k8s. You can see that the log of csi-snapshot is as follows. The creation failed.

I0119 07:20:51.689831 1 snapshotter.go:56] CSI CreateSnapshot: snapshot-82ad5bb8-13f5-42a2-b655-aab727bc5eed

I0119 07:20:51.689841 1 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginInfo

I0119 07:20:51.689846 1 connection.go:183] GRPC request: {}

I0119 07:20:51.692442 1 connection.go:185] GRPC response: {"name":"driver.longhorn.io","vendor_version":"f2003482"}

I0119 07:20:51.692898 1 connection.go:186] GRPC error:

I0119 07:20:51.692904 1 connection.go:182] GRPC call: /csi.v1.Controller/CreateSnapshot

I0119 07:20:51.692909 1 connection.go:183] GRPC request: {"name":"snapshot-82ad5bb8-13f5-42a2-b655-aab727bc5eed","source_volume_id":"pvc-48aaa899-00cd-46fc-9e2b-06e91e496f2d"}

I0119 07:20:51.695072 1 connection.go:185] GRPC response: {}

I0119 07:20:51.695558 1 connection.go:186] GRPC error: rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=error get backup volume 'pvc-48aaa899-00cd-46fc-9e2b-06e91e496f2d': setting backup-target is empty, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/backupvolumes/pvc-48aaa899-00cd-46fc-9e2b-06e91e496f2d]

I0119 07:20:51.695574 1 snapshot_controller.go:329] createSnapshotWrapper: CreateSnapshot for content snapcontent-82ad5bb8-13f5-42a2-b655-aab727bc5eed returned error: rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=error get backup volume 'pvc-48aaa899-00cd-46fc-9e2b-06e91e496f2d': setting backup-target is empty, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/backupvolumes/pvc-48aaa899-00cd-46fc-9e2b-06e91e496f2d]

I0119 07:20:51.703358 1 snapshot_controller_base.go:144] enqueued "snapcontent-82ad5bb8-13f5-42a2-b655-aab727bc5eed" for sync

I0119 07:20:51.703383 1 snapshot_controller_base.go:159] contentWorker[snapcontent-82ad5bb8-13f5-42a2-b655-aab727bc5eed]

I0119 07:20:51.703397 1 util.go:169] storeObjectUpdate updating content "snapcontent-82ad5bb8-13f5-42a2-b655-aab727bc5eed" with version 4279063

I0119 07:20:51.703412 1 snapshot_controller.go:58] synchronizing VolumeSnapshotContent[snapcontent-82ad5bb8-13f5-42a2-b655-aab727bc5eed]

I0119 07:20:51.703417 1 snapshot_controller.go:569] Check if VolumeSnapshotContent[snapcontent-82ad5bb8-13f5-42a2-b655-aab727bc5eed] should be deleted.

I0119 07:20:51.703422 1 snapshot_controller.go:78] syncContent: Call CreateSnapshot for content snapcontent-82ad5bb8-13f5-42a2-b655-aab727bc5eed

I0119 07:20:51.703427 1 snapshot_controller.go:133] createSnapshot for content [snapcontent-82ad5bb8-13f5-42a2-b655-aab727bc5eed]: started

I0119 07:20:51.703433 1 snapshot_controller.go:112] scheduleOperation[create-snapcontent-82ad5bb8-13f5-42a2-b655-aab727bc5eed]

I0119 07:20:51.703441 1 snapshot_controller.go:118] operation "create-snapcontent-82ad5bb8-13f5-42a2-b655-aab727bc5eed" is already running, skipping

I0119 07:20:51.705013 1 snapshot_controller.go:643] Removed VolumeSnapshotBeingCreated annotation from volume snapshot content snapcontent-82ad5bb8-13f5-42a2-b655-aab727bc5eed

I0119 07:20:51.705034 1 util.go:169] storeObjectUpdate updating content "snapcontent-82ad5bb8-13f5-42a2-b655-aab727bc5eed" with version 4279063

I0119 07:20:51.705047 1 snapshot_controller.go:179] updateContentStatusWithEvent[snapcontent-82ad5bb8-13f5-42a2-b655-aab727bc5eed]

I0119 07:20:51.709725 1 snapshot_controller.go:200] updating VolumeSnapshotContent[snapcontent-82ad5bb8-13f5-42a2-b655-aab727bc5eed] error status failed Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io "snapcontent-82ad5bb8-13f5-42a2-b655-aab727bc5eed": the object has been modified; please apply your changes to the latest version and try again

E0119 07:20:51.709742 1 snapshot_controller.go:139] createSnapshot [create-snapcontent-82ad5bb8-13f5-42a2-b655-aab727bc5eed]: error occurred in createSnapshotWrapper: failed to take snapshot of the volume, pvc-48aaa899-00cd-46fc-9e2b-06e91e496f2d: %!q()

E0119 07:20:51.709767 1 goroutinemap.go:150] Operation for "create-snapcontent-82ad5bb8-13f5-42a2-b655-aab727bc5eed" failed. No retries permitted until 2021-01-19 07:20:59.709748318 +0000 UTC m=+351172.132045681 (durationBeforeRetry 8s). Error: "failed to take snapshot of the volume, pvc-48aaa899-00cd-46fc-9e2b-06e91e496f2d: %!q()"

**Comment by joshimoo** [comment]
@yyt6200 you need to setup a backup target `setting backup-target is empty`
https://longhorn.io/docs/1.1.0/snapshots-and-backups/backup-and-restore/set-backup-target/
longhorn snapshots are only local, a volume snapshot in the sense of kubernetes represents a longhorn backup.

**Comment by yyt6200** [comment]
@joshimoo do you mean that if I use kubernetes to create a snapshot, I need to create a backup first? Thank you for your reply

**Comment by joshimoo** [comment]
@yyt6200 no you can use csi snapshots which will automatically create a longhorn snapshot + backup. To do this you need to setup a backup target https://longhorn.io/docs/1.1.0/snapshots-and-backups/backup-and-restore/set-backup-target/
So longhorn knows where to store/retrieve the backups.

This is why your operation is failing.

**Comment by joshimoo** [comment]
Closing this issue, please feel free to reopen if you require further assistance.
