### ISSUE TITLE
[QUESTION] Why sometimes my volume stucks ?

### ISSUE THREAD

**Issue by necipakca** [longhorn/longhorn#2195]
**Question**
I am newbie of longhorn.
Sometimes one of my volume stuck and I am fixing issue with fsck. how can I get more detail data or trace why it happens ?

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version: 1.19.14
 - Node config
   - Debian 4.19.160-2  
   - CPU per node: 8
   - Memory per node: 8GB
   - Disk type : MultiTier
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):  Baremetal

**Additional context**

  Warning  FailedMount  8m34s                 kubelet            MountVolume.SetUp failed for volume "pvc-b85a9eb1-147c-4b43-be94-8095372c1632" : rpc error: code = InvalidArgument desc = There is no block device frontend for volume pvc-b85a9eb1-147c-4b43-be94-8095372c1632
  Warning  FailedMount  6m31s (x10 over 26m)  kubelet            MountVolume.SetUp failed for volume "pvc-b85a9eb1-147c-4b43-be94-8095372c1632" : rpc error: code = Internal desc = 'fsck' found errors on device /dev/longhorn/pvc-b85a9eb1-147c-4b43-be94-8095372c1632 but could not correct them: fsck from util-linux 2.31.1
ext2fs_check_if_mount: Can't check if filesystem is mounted due to missing mtab file while determining whether /dev/longhorn/pvc-b85a9eb1-147c-4b43-be94-8095372c1632 is mounted.
/dev/longhorn/pvc-b85a9eb1-147c-4b43-be94-8095372c1632 contains a file system with errors, check forced.
/dev/longhorn/pvc-b85a9eb1-147c-4b43-be94-8095372c1632: Inodes that were part of a corrupted orphan linked list found.

**Comment by incedo** [comment]
I have the same question, where is the answer - I see the issue is closed

**Comment by joshimoo** [comment]
@incedo can you open an issue that describes your problem with all the necessary environmental details + support bundle attached?

**Comment by bdsoha** [comment]
Me too
