### ISSUE TITLE
[BUG] ganesha in the share-manager pod requires on IPv6 on the host

### ISSUE THREAD

**Issue by bentastic27** [longhorn/longhorn#2197]
There are some users that disable IPv6 on their nodes via kernel flags (`sysctl -w net.ipv6.conf.all.disable_ipv6=1`). When users try to create an RWX volume genesha in the share-manager pod fails with this error:

```
level=error msg=“nfs server exited with error” error=“ganesha.nfsd failed with error: exit status 2, output: VFS module failed to unregister”
```

**Comment by joshimoo** [comment]
Just an additional note, this is only a problem when ipv6 is disable via the bootloader.
GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1"

Dynamically disabling it via sysctl will allow for the system to operate correctly.

**Comment by c3y1huang** [comment]
Seem it is required to have host ipv6 enabled because the nfs-ganesha used in share-manager automatically binds to tcp6 socket unless on FreeBSD.

When ipv6 is disabled using sysctl, the change does not pass through to Kubernetes pods hence share-manager manages to survives.
```
# Execute in pod:

/ # cat /sys/module/ipv6/parameters/disable
0

/ # sysctl -a 2>/dev/null | grep disable_ipv
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.eth0.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0

/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
3: eth0@if34: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue
    link/ether b2:df:ab:8d:aa:3d brd ff:ff:ff:ff:ff:ff
    inet 10.42.0.87/24 brd 10.42.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::b0df:abff:fe8d:aa3d/64 scope link
       valid_lft forever preferred_lft forever
```
And when using kernel boot entries, the changes take effects, and ganesha exits due to unable to find to tcp6 socket and crashes share-manager.
```
# Execute in pod:

/ # cat /sys/module/ipv6/parameters/disable
1
/ # sysctl -a 2>/dev/null | grep disable_ipv
/ #
```

**Comment by c3y1huang** [comment]
@joshimoo correct me if I'm wrong, but this seems like a no fix, and we should add to requirement in doc.

**Comment by joshimoo** [comment]
@c3y1huang good analysis, generally it would be okay for us to force ganesha to use ipv4 only, since we currently don't support ipv6 only clusters.

I think one can force ganesha to use IP4 only but I cannot find the documentation for the flag might be miss remembering. We can forcefully disable ipv6 in the source code since we are building from source, Besides that I think there is a bug in the ganesha code around this checking, (i.e. udp disabled, tcp will fatal out) I will submit a pr for this to the ganesha upstream.

There is also a newer ganesha version 3.5 released we are on 3.3 so that's a good time to update the version.
I will have a look at this tomorrow and create a build with a forced ip4 mind testing that build for me?

**Comment by c3y1huang** [comment]
> @c3y1huang good analysis, generally it would be okay for us to force ganesha to use ipv4 only, since we currently don't support ipv6 only clusters.
> 
> I think one can force ganesha to use IP4 only but I cannot find the documentation for the flag might be miss remembering. We can forcefully disable ipv6 in the source code since we are building from source, Besides that I think there is a bug in the ganesha code around this checking, (i.e. udp disabled, tcp will fatal out) I will submit a pr for this to the ganesha upstream.
> 
> There is also a newer ganesha version 3.5 released we are on 3.3 so that's a good time to update the version.
> I will have a look at this tomorrow and create a build with a forced ip4 mind testing that build for me?

Thanks @joshimoo , as discussed, we will try to either enforce disable ipv6 in the source code or apply your pr patch to adopt tcp ipv4 fallback. The full regression seems to be dependent on https://github.com/longhorn/longhorn/issues/2111, I will take a look at it first.

**Comment by joshimoo** [comment]
The new share-manager image `longhornio/longhorn-share-manager:v1_20210302`  has been released
The build pipeline pushes the new images to dockerhub, link here: https://hub.docker.com/r/longhornio/longhorn-share-manager/tags

@c3y1huang After testing the updated image, you can submit pr's to:
longhorn - to update the chart. Example here: https://github.com/longhorn/longhorn/pull/2173/files
longhorn-manager - to update the deployment yamls. Example here: https://github.com/longhorn/longhorn-manager/pull/816/files

**Comment by c3y1huang** [comment]
Test v1_20210302
```
root@ubuntu-Standard-PC-Q35-ICH9-2009:~# kubectl -n longhorn-system get pod | grep share
# Verify share-manager created and running
share-manager-pvc-fa894600-7c7c-4832-a9d0-71accb75685b   1/1     Running   0          8m8s

# Verify IPv6 disabled
root@ubuntu-Standard-PC-Q35-ICH9-2009:~# kubectl -n longhorn-system exec -it share-manager-pvc-fa894600-7c7c-4832-a9d0-71accb75685b -- cat /sys/module/ipv6/parameters/disable
1

# Verify volume created
root@ubuntu-Standard-PC-Q35-ICH9-2009:~# kubectl -n longhorn-system get volume
NAME                                       STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE                               AGE
pvc-fa894600-7c7c-4832-a9d0-71accb75685b   attached   degraded     False       2147483648   ubuntu-standard-pc-q35-ich9-2009   9m25s

# Verify deployment pod created and running
root@ubuntu-Standard-PC-Q35-ICH9-2009:~# kubectl get pod | grep my-deploy
NAME                             READY   STATUS    RESTARTS   AGE
my-deployment-569f7d5c9c-xgss4   1/1     Running   0          6m36s

# PVC directory created
root@ubuntu-Standard-PC-Q35-ICH9-2009:~# kubectl -n longhorn-system exec -it share-manager-pvc-fa894600-7c7c-4832-a9d0-71accb75685b -- ls /export
pvc-fa894600-7c7c-4832-a9d0-71accb75685b

# Verify data input
root@ubuntu-Standard-PC-Q35-ICH9-2009:~# kubectl exec -it pod/my-deployment-569f7d5c9c-xgss4 -- sh -c "echo world > /data/hello"
root@ubuntu-Standard-PC-Q35-ICH9-2009:~# kubectl -n longhorn-system exec -it share-manager-pvc-fa894600-7c7c-4832-a9d0-71accb75685b -- cat /export/pvc-fa894600-7c7c-4832-a9d0-71accb75685b/hello
world
```

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master `03/25/2021`

Validation - **Pass**

The share-manager pod for rwx volume is coming up healthy successfully. Validated basic scenarios of RWX volumes.
