### ISSUE TITLE
[BUG] Shouldn't bind mount /var/run/ in Helm chart

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2200]
We need to remove the mount [/var/run](https://github.com/longhorn/longhorn/blob/0fd0c33e06d7c998dee0f9a43056e4a0030638d9/chart/templates/daemonset-sa.yaml#L48) in Helm chart

Related to https://github.com/longhorn/longhorn/issues/2088

Ref: https://github.com/longhorn/longhorn/blob/7533ae2fe22ab6a0f578633541eb8a88eccf6c9d/chart/templates/daemonset-sa.yaml#L48

**Comment by yasker** [comment]
@jenting The chart PR should be made against `longhorn/longhorn` for the upcoming release branch, which is `v1.1.1` at the moment.

Ref: https://github.com/longhorn/longhorn/wiki/Repositories-for-contribution-guideline

**Comment by jenting** [comment]
Thank you for the explanation.

If I guess correctly, the `v1.1.1` branch will be merged into the master branch after release, right?
Or should I create separate another PR for the master branch?

**Comment by yasker** [comment]
Yes, `v1.1.1` branch will be merged into `master` branch once it's released. No need to create another PR for `master` branch.

**Comment by khushboo-rancher** [comment]
Verified with the chart on the branch v1.1.1

Validation - **Pass**

From Longhorn-manager, ping and ns lookup to longhorn-test-nfs-svc.default are working.

Verified with SLES15 SP2 and ubuntu, Longhorn is able to list the backups from nfs backupstore.
