### ISSUE TITLE
[BUG] rwx integration tests failing on arm64 set up

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2201]
**Describe the bug**
rwx integration tests failing on arm64 set up in nightly test run with longhorm master image.
https://ci.longhorn.io/job/public/job/longhorn-tests-arm64/71/

**Comment by khushboo-rancher** [comment]
This is impacted by https://github.com/longhorn/longhorn/issues/2111.

**Comment by odidev** [comment]
@khushboo-rancher , We would also like to see this issue fixed, Is it within your scope of next release?

**Comment by khushboo-rancher** [comment]
@odidev Yes, it is in the scope for v1.1.1 (next release)

**Comment by khushboo-rancher** [comment]
This issue is fixed and we don't observe this issue in our nightly test https://ci.longhorn.io/job/public/job/ubuntu/job/arm64/job/longhorn-tests-ubuntu-arm64/173/testReport/tests/test_rwx/
