### ISSUE TITLE
[Question]  csinode.storage.k8s.io not found

### ISSUE THREAD

**Issue by QLeelulu** [longhorn/longhorn#2202]
pod is running in k8s `master node`, but can't attach volume:

```
AttachVolume.Attach failed for volume "pvc-25ccdde5-dcf2-4a39-97ce-0514183caf03" : csinode.storage.k8s.io "master1.test.com" not found
```

it worked if pod is running in k8s `worker node`.

**Comment by joshimoo** [comment]
@QLeelulu if you user a dedicated master (etcd, controlplane) then no workload is expected to be running on this.
No deamonset will be deployed to it, so you will not have the longhorn-csi node plugin available on that node.
Workloads are not supposed to be running on dedicated master nodes (controlplane, etcd) if you want to use that node for workloads as well, add the worker role to it. But it's much better to have dedicated master (controlplane, etcd) nodes.

**Comment by QLeelulu** [comment]
@joshimoo thanks
