### ISSUE TITLE
[FEATURE] UI: Only allow to upgrade to the default engine image when the setting `automatically upgrade volumes' engine to default version` is enable 

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2205]
If the setting `Concurrent Automatic Engine Upgrade Per Node Limit` is bigger than 0, only allow the user to upgrade to the default engine image. Even if there are other engine images available, we don't allow users to upgrade to a different engine image other than the default one. 

More specifically, if the setting `Concurrent Automatic Engine Upgrade Per Node Limit` > 0,  filter the dropdown selection for `upgrade engine` to only include the default engine image. If the volume already has the default engine image, the dropdown selection should be empty thus the `upgrade engine` action is disabled

**Comment by yasker** [comment]
Notice the backend hasn't been merged yet. PR at https://github.com/longhorn/longhorn-manager/pull/818

**Comment by yasker** [comment]
The backend has been merged at https://github.com/longhorn/longhorn-manager/pull/818

**Comment by yasker** [comment]
@PhanLe1010 Can you confirm this UI change is ready to be validated?

**Comment by PhanLe1010** [comment]
@yasker Yes, It is ready to be validated. 

Should I move it to merged column?

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master `02/24/2021`

Validation - **Pass**

1. **With the auto engine upgrade disabled** - It is allowed to upgrade the engine to a engine image which is not default.
2. **With the auto engine upgrade Enabled** - Upgrade to only default engine image is allowed using UI. The dropdown doesn't show engine image other than the default one.
