### ISSUE TITLE
[FEATURE] Enhanced resource reservation mechanism

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2207]
**Is your feature request related to a problem? Please describe.**
To make sure users have a stable storage system, we need to be more specific on reserving resources for Longhorn, as well as make it clear in the case that the reserved resources might not be enough for Longhorn to function when there are too many engines/replicas running on the node.

**Describe the solution you'd like**
Make the Guaranteed Engine CPU to be node-specific. We can give the user two options to choose how many CPUs to reserve by default for engine instance manager, and replica instance manager. Both will be set to 1/8 of the total available CPU number on the node.

Be careful since this might result in instance manager fail to start during installation or upgrade. For upgrade, we might require double the resource due the upgrade of the instance managers.

**Describe alternatives you've considered**
As we currently do, ask user to use GuaranteedEngineCPU manually as a global option, but it's not good enough compared to the solution above.

**Additional context**
The other part of this problem is to warn user about CPU starving, which will be covered by https://github.com/longhorn/longhorn/issues/1930

https://github.com/longhorn/longhorn/issues/1691 has more information regarding the resource requirement.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn master - `04/01/2021`

@shuo-wu Can you confirm the below results are fine.
For below config node the default cpu request with 12 in the setting `Guaranteed Engine Manager CPU` and `Guaranteed Replica Manager CPU` -  The request doesn't fit with the formula -  `total cpu * Guaranteed Manager CPU%`

RAM | CPU Request
--- |---
32 GB | 960m
8 GB | 480m
4 GB | 240m

Also, have we explicitly mentioned in the doc anywhere that for Longhorn previous version upgraded to v1.1.1, one has to set the existing cpu request to 0 to have this setting applicable?

**Comment by shuo-wu** [comment]
The requests in the table fit the formula. e.g., 8 CPU * 12% = 0.96 CPU = 960 mCPU. It's not related to RAM...

In the setting description, there is one related note `This global setting will be ignored for a node if the field "ReplicaManagerCPURequest" on the node is set`. But we didn't mention that the node fields will be set when upgrading from old versions. We may need to mention that somewhere.

**Comment by khushboo-rancher** [comment]
Validation - **Pass**

Test cases from https://github.com/longhorn/longhorn-tests/pull/532 are passing.

**Comment by shuo-wu** [comment]
The upgrade note PR related to this enhancement: https://github.com/longhorn/website/pull/281

**Comment by khushboo-rancher** [comment]
The test `test_instance_manager_cpu_reservation` has been passing the integration test run.
