### ISSUE TITLE
[BUG] All longhorn-manager pods crushloopbackoff

### ISSUE THREAD

**Issue by necipakca** [longhorn/longhorn#2208]
**Describe the bug**
I tried to add disk to existing node. All longhorn-managers are crushloopbackoff now.
How can I get my volumes back without loosing data ?

**To Reproduce**
1. Go to node and edit node which is disabled but ready.
2. Click add disk and set schedule to true.Best-effort was open so it tried to replicate probably.
3. Perform save.

**Expected behavior**

**Log**
E0123 12:15:17.256329       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 105 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x18238e0, 0x2a87900)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x18238e0, 0x2a87900)
        /usr/local/go/src/runtime/panic.go:967 +0x166
github.com/longhorn/longhorn-manager/controller.(*ReplicaController).enqueueNodeChange(0xc0001a0d90, 0x1a236e0, 0xc0002ba880)
        /go/src/github.com/longhorn/longhorn-manager/controller/replica_controller.go:588 +0x338
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/controller.go:198
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x1f4, 0x0, 0x0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:658 +0x120
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc000a43e18, 0x188fb80, 0xc0006a6e01)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0006a6f60)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a43f60, 0xdf8475800, 0x0, 0x1, 0xc00069e6c0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0005d5900)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0001a05a0, 0xc0003364a0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
E0123 12:15:17.256385       1 kubernetes_node_controller.go:260] couldn't get kubernetes node k8s5: node "k8s5" not found
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x15ba5a8]

goroutine 105 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x18238e0, 0x2a87900)
        /usr/local/go/src/runtime/panic.go:967 +0x166
github.com/longhorn/longhorn-manager/controller.(*ReplicaController).enqueueNodeChange(0xc0001a0d90, 0x1a236e0, 0xc0002ba880)
        /go/src/github.com/longhorn/longhorn-manager/controller/replica_controller.go:588 +0x338
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/controller.go:198
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x1f4, 0x0, 0x0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:658 +0x120
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc000853e18, 0x188fb80, 0xc0006a6e01)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0006a6f60)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000853f60, 0xdf8475800, 0x0, 0x1, 0xc00069e6c0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0005d5900)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0001a05a0, 0xc0003364a0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62

UI Not Accessible. 502 status code error.

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes distro (Kubespray) and version:
   - Number of management node in the cluster: 2
   - Number of worker node in the cluster: 5
 - Node config
   - OS type and version: Debian 10
   - CPU per node: 8
   - Memory per node: 8
   - Disk type(e.g. SSD/NVMe): isci
   - Network bandwidth between the nodes:
 - Underlying Infrastructure ( VMWare):
 - Number of Longhorn volumes in the cluster: 3

**Comment by shuo-wu** [comment]
The simplest reproducing step: 
- Add a random disk (even if the data path is invalid) with `Eviction Requested = True` and `Scheduling = False`. 

This is a Longhorn bug, we will fix it in the next release.

The current workaround of this issue:
1. Set the `spec.evictionRequested` to false for the newly added disk on the Longhorn node:
```
kubectl -n longhorn-system edit nodes.longhorn.io <The node you are editing>
```
2. Directly delete all longhorn manager pods that are in state `crushloopbackoff`. Then Kubernetes will recreate the pods automatically

**Comment by khushboo-rancher** [comment]
Validated with the Longhorn-master `03/02/2021`

Validation - **Pass**

Added a random disk with `eviction requested` True and `scheduling` as False, there is no error and Longhorn-manager pods don't stuck in crashloop and work fine.
