### ISSUE TITLE
[Question] Restoring from multiple replicas?

### ISSUE THREAD

**Issue by rbq** [longhorn/longhorn#2212]
Hi, I have 5 leftover replicas on disk that belong to a volume that was deleted accidentally. Those replicas are results of hosts being rebooted and Longhorn not cleaning up after they came back online. One of the replicas can be mounted following the single-replica recovery instructions, but the data is quite outdated. The other replicas time out or produce errors.

My question: Is there any other other recovery method that processes multiple replica directories on disk and tries to reconcile them into something useful?

**Comment by PhanLe1010** [comment]
@rbq 

> The other replicas time out or produce errors.

Did you try to use `fsck` command to try to repair those replicas

> My question: Is there any other other recovery method that processes multiple replica directories on disk and tries to reconcile them into something useful?

Unfortunately, there isn't

Btw, you can use the [Longhorn's backup feature](https://longhorn.io/docs/1.1.0/snapshots-and-backups/backup-and-restore/set-backup-target/) so you can easily get your data back if this problem happens in the future.

**Comment by rbq** [comment]
> Did you try to use fsck command to try to repair those replicas

Is that something I can do at rest, if the container running `launch-simple-longhorn` won't even create a device?

**Comment by shuo-wu** [comment]
What's the error result when you running `launch-simple-longhorn` with one data directory? 

In theory, Longhorn doesn't care about the data inside the replica. And a volume can be created as long as the directory/file organization and the metafiles are correct inside the data directory. Can you check if the files inside the data directory you are using are similar to the following?
```
root@shuo-cluster-0-worker-1:/var/lib/longhorn/replicas# ls
test-volume-4b862240
root@shuo-cluster-0-worker-1:/var/lib/longhorn/replicas# find test-volume-4b862240/
test-volume-4b862240/
test-volume-4b862240/volume-snap-9c1477ac-1597-46eb-b786-1522b82594ce.img
test-volume-4b862240/volume-head-004.img
test-volume-4b862240/volume-snap-c6fce6ed-38ca-4475-b9de-05f3a93d2dcd.img.meta
test-volume-4b862240/volume-snap-141f476a-1c90-4814-96ef-c3fedc15de24.img
test-volume-4b862240/volume-snap-9c1477ac-1597-46eb-b786-1522b82594ce.img.meta
test-volume-4b862240/volume-snap-a4c35265-adbe-448d-9e8c-0980dd8041cf.img
test-volume-4b862240/volume.meta
test-volume-4b862240/volume-snap-a4c35265-adbe-448d-9e8c-0980dd8041cf.img.meta
test-volume-4b862240/volume-head-004.img.meta
test-volume-4b862240/revision.counter
test-volume-4b862240/volume-snap-c6fce6ed-38ca-4475-b9de-05f3a93d2dcd.img
test-volume-4b862240/volume-snap-141f476a-1c90-4814-96ef-c3fedc15de24.img.meta
```
```
root@shuo-cluster-0-worker-1:/var/lib/longhorn/replicas# cat test-volume-4b862240/volume-head-004.img.meta
{"Name":"volume-head-004.img","Parent":"volume-snap-a4c35265-adbe-448d-9e8c-0980dd8041cf.img","Removed":false,"UserCreated":false,"Created":"2021-01-29T02:55:29Z","Labels":null}

root@shuo-cluster-0-worker-1:/var/lib/longhorn/replicas# cat test-volume-4b862240/volume-snap-a4c35265-adbe-448d-9e8c-0980dd8041cf.img.meta
{"Name":"volume-head-003.img","Parent":"volume-snap-141f476a-1c90-4814-96ef-c3fedc15de24.img","Removed":false,"UserCreated":true,"Created":"2021-01-29T02:55:29Z","Labels":null}
```

Notice:
1. The data directory of a replica here is `/var/lib/longhorn/replicas/test-volume-4b862240`
2. The files inside the directory is organized as a chain/linked list: the metadata of each image/head file records the parent, which is another image file.

**Comment by PhanLe1010** [comment]
@rbq 
Any update?

**Comment by ralf-berger** [comment]
Sorry, had to give up, please close the issue.
