### ISSUE TITLE
Kasten-io and Longhorn CSI, snapshotting not working.

### ISSUE THREAD

**Issue by ajjo-tech** [longhorn/longhorn#2217]
**Describe the bug**
Im using the Kasten-io backup software in order to backup my apps. However when it comes to a app with an pvc connected to it the backup doesnt finish. I can see that Kasten creates a Volumesnapshot per pvc in the app.
But after that nothings happends and the backup keeps going until i stop it by deleting the namespace.
So my question is there anything with Longhorn creating the issue or is it Kasten-io ?

**To Reproduce**
1. Install Kasten-io
2. Install a app with pvc's
3. create a backup policy

**Expected behavior**
Finished backup

**Logs**
Support bundle has been sent to email instead. The bundle was to big.

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE 1.19.7
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubunut 2004 LTS
   - CPU per node: 4 for management 8 for worker
   - Memory per node: 4 for management 8 for worker
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 10Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 10

**Additional context**

**Comment by ajjo-tech** [comment]
Sent an link with the support bundle to the longhorn-support-bundle@rancher.com.

**Comment by bathina2** [comment]
@ajjo-tech could you send us the Kasten debug logs as well? We could take a look. https://docs.kasten.io/latest/operating/support.html#gathering-debugging-information

**Comment by PhanLe1010** [comment]
@ajjo-tech 

Can you try 2 things:

1. Go go longhorn Ui and take a backup manually. If it fails, we need to check the backup store
2. Follow the steps in the [docs](https://longhorn.io/docs/1.1.0/snapshots-and-backups/csi-snapshot-support/create-a-backup-via-csi/), to manually create a snapshot using kubectl. If it fails we need to check CSI snapshot components

If both of the above are ok, then it is probably not a Longhorn's issue.

**Comment by ajjo-tech** [comment]
@bathina2 
Sure thing here is the Kasten Debug logs.
[k10_debug_logs.txt.gz](https://github.com/longhorn/longhorn/files/5892895/k10_debug_logs.txt.gz)

@PhanLe1010 
1. backup and snapshotting in the Ui seem to work, but running kubectl get volumesnapshot --all-namespaces gets me no resources.
Might be mistaken here but shouldnt that snapshot or backup show?
2. creating snaps with kubectl works like it should.
![image](https://user-images.githubusercontent.com/62011862/106259668-d4e1ad00-621f-11eb-9a06-833812f18df1.png)

**Comment by PhanLe1010** [comment]
@ajjo-tech 

> backup and snapshotting in the Ui seem to work, but running kubectl get volumesnapshot --all-namespaces gets me no resources.

Yes, it is expected by design, snapshot/backup taken in UI will not have the corresponding volumesnapshot CR in Kubernetes

> creating snaps with kubectl works like it should.
![image](https://user-images.githubusercontent.com/62011862/106259668-d4e1ad00-621f-11eb-9a06-833812f18df1.png)

No, this picture doesn't look good. You can see that `READYTOUSE`, `SNAPSHOTCONTENT` are empty . Did you make sure that the require components are installed as documented at https://longhorn.io/docs/1.1.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/ ? RKE doesn't come with them by default

**Comment by ajjo-tech** [comment]
@PhanLe1010 
I corrected the crds and whoopy now the backup and with snapshots is working.
The documentation was a little bit abigious, i changed originally all crds to be in the kube-system namespace.
Recreated them in the default namespace and now its all good.

Thanks a bundle for the input and the insights.

**Comment by PhanLe1010** [comment]
> The documentation was a little bit abigious, i changed originally all crds to be in the kube-system namespace.

Can you explain a bit more so we can improve the document? Which part of the document is ambiguous?

**Comment by ajjo-tech** [comment]
@PhanLe1010 
There was a comment of where to put the crds and the snapshot controller.
But going back now and reading it again i read in much clearer light and stand corrected.
No need to change the documentation, if i had read it all ive would have had a clearer picture.

Thanks again for the support!

**Comment by NarayanPooja** [comment]
> @PhanLe1010 I corrected the crds and whoopy now the backup and with snapshots is working. The documentation was a little bit abigious, i changed originally all crds to be in the kube-system namespace. Recreated them in the default namespace and now its all good.
> 
> Thanks a bundle for the input and the insights.

**Comment by NarayanPooja** [comment]
Can I get the steps through which you installed longhorn and Kasten along with the annotations specified 

![image](https://user-images.githubusercontent.com/90742840/163595053-632e7934-36ce-4f0a-9da8-6f728318c8fe.png)

I am getting this error and not able to rectify

**Comment by zucatti** [comment]
got the same error with longhorn and k10

**Comment by NarayanPooja** [comment]
> got the same error with longhorn and k10

I installed open-icsi as a prereq before installing longhorn and was able to rectify the error

https://longhorn.io/docs/1.2.4/deploy/install/#installing-open-iscsi

You can refer this link

**Comment by NarayanPooja** [comment]
I have made a small note on installing Kasten with longhorn Please refer if you find it useful


Install Longhorn 

kubectl get no -o wide 

ssh into all nodes

run the below commands in all the nodes

yum --setopt=tsflags=noscripts install iscsi-initiator-utils
systemctl enable iscsid
systemctl start iscsid
yum install nfs-utils


docker login



docker pull busybox

curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.2.4/scripts/environment_check.sh | bash


duplicate Masternode terminal


go and edit DaemonSet to IfNotPresent



Installing Helm

curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
chmod 700 get_helm.sh
 ./get_helm.sh


helm repo add longhorn https://charts.longhorn.io

 helm repo update

helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace


kubectl -n longhorn-system get po 

make sure all pods are running

install minio with the below command

kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/v1.2.4/deploy/backupstores/minio-backupstore.yaml


add location and secret on Longhorn db


******************************************************************

Kasten Installation

curl https://docs.kasten.io/tools/k10_primer.sh | bash

kubectl annotate volumesnapshotclass longhorn    k10.kasten.io/is-snapshot-class=true

kubectl annotate storageclass longhorn   k10.kasten.io/volume-snapshot-class=longhorn


helm repo add kasten https://charts.kasten.io/

kubectl create namespace kasten-io

helm install k10 kasten/k10   --namespace=kasten-io      --set auth.tokenAuth.enable=true     --set metering.mode=airgap

**Comment by zucatti** [comment]
thanks for your reply. you're awesome ! 
This "bug" almost drove me crazy. I have finally found what it happened... 
The longhorn S3 configs seems not working with scaleway S3 object storage which is the reason of the k10 snapshot failed. Scaleway S3 is working with k10... I have just replaced scaleway S3 config within longhorn by AWS and even my own minio S3, all the two methods are working fine with k10 and longhorn... I don't know why it is buggy with scaleway ;-)

**Comment by NarayanPooja** [comment]
It would be best if you didn't use your own minio instead use the below link

https://longhorn.io/docs/1.2.4/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-a-local-testing-backupstore

in order to set this, you have to change the longhorn-fontend service to nodeport. Then you will be able to access longhorn UI there you have to perform step 3,4 under Set up AWS S3 Backupstore

then perform Set up a Local Testing Backupstore step and then you will be ready to go
