### ISSUE TITLE
[Question] sharding between the different disks

### ISSUE THREAD

**Issue by benqwu** [longhorn/longhorn#2223]
**Question**
Currently longhorn recommends using lvm to use multiple disks inside the node, but there is a problem. As long as any one of the disks is damaged, all data on the node will be invalid.
I saw a feature that is "Sharding across different disks." mentioned in the longhorn roadmap. I am very interested in this. 
1. Relying on this feature, if any disk fails, can it not affect the data on other disks? To transfer data back from other nodes, only the part of the failed disk needs to be transferred, and the existing failed replica is used for reconstruction, which will greatly shorten the time for data reconstruction.
2. Does this feature refer to sharding a replica's data to different disks in the node? 
3. Is there a plan to support slicing a volume, and then distributing N copies of the slice to different disks in the entire cluster, like ceph?

@yasker 

Thank you.

**Comment by joshimoo** [comment]
Currently a replica is a full copy of the volume. The default installation has a replica count of 3 so each volume is backed by 3 replicas. Which will be scheduled on different nodes/disks in the cluster.

In this scenario if a replica fails (node/disk failure) the replica can be rebuild on a new node/disks based on the state of the 2 other healthy replicas.

**Comment by benqwu** [comment]
> Currently a replica is a full copy of the volume. The default installation has a replica count of 3 so each volume is backed by 3 replicas. Which will be scheduled on different nodes/disks in the cluster.
> 
> In this scenario if a replica fails (node/disk failure) the replica can be rebuild on a new node/disks based on the state of the 2 other healthy replicas.

Thank you for your reply. Regarding the feature of "Sharding across different disks.", can you introduce it in detail?

**Comment by joshimoo** [comment]
We currently don't shard the data, each replica is a full representation of the data.
Example: you write 1 file of 800 blocks of data to the volume, now each replica contains the same 800 blocks.

**Comment by benqwu** [comment]
> We currently don't shard the data, each replica is a full representation of the data.
> Example: you write 1 file of 800 blocks of data to the volume, now each replica contains the same 800 blocks.

https://github.com/longhorn/longhorn/wiki/Roadmap
In the above page we can see that future features will include “Sharding across different disks.”. Regarding this feature, are there any design considerations at present? Does this feature refer to sharding one replica's data to different disks in the same node?

**Comment by yasker** [comment]
@benqwu That's a feature we're considering. It's tracked by https://github.com/longhorn/longhorn/issues/1061 . Also, it means sharding across the different disks on the same or different nodes.
