### ISSUE TITLE
[Question] Auto attach volume to another node when the current attached node disappears or gets destroyed ?

### ISSUE THREAD

**Issue by iangregsondev** [longhorn/longhorn#2224]
**Question**

Hi, I am using DigitalOcean and the nodes can be recycled or rebuilt at any time. I tested this yesterday evening but didn't get the results I was hoping. I am probably doing it wrong.

In longhorn ui it still states that it is attached to a node that has been destroyed..

![image](https://user-images.githubusercontent.com/2370364/106265419-4c670a80-6227-11eb-8fe8-8bc2b5671599.png)

The node ending in 39ke7 was destroyed and a new one was built. I also notice that the replicas are not complete

For example the node ending in 39kl5 was the one that replaced the 39ke7, its there but its not automatically added as a replica. I think this is because the attached node no longer exists

![image](https://user-images.githubusercontent.com/2370364/106265605-92bc6980-6227-11eb-87e1-2fa2e3b0403b.png)

I did set this setting in the settings, I was hoping for the attached node to recover by being attached on a different node.

![image](https://user-images.githubusercontent.com/2370364/106265748-c39c9e80-6227-11eb-8d20-39e943ae6713.png)

Can somebody help ?

I came over from glusterfs and the experience has been great but I can't get the volume to attach to a new node

Any ideas ?

Thanks.

**Comment by joshimoo** [comment]
Can you attach a support bundle, you can create this via the longhorn ui.
Was the old node removed from kubernetes `kubectl get nodes`

**Comment by iangregsondev** [comment]
Hi, thanks for the quick response. Yes the node was removed from kubectl, it was destroyed and another recreated in its place

NAME                     STATUS   ROLES    AGE    VERSION
pool-rndlabs-old-39kgm   Ready    <none>   119m   v1.19.3
pool-rndlabs-old-39kl5   Ready    <none>   69m    v1.19.3
pool-rndlabs-old-39krt   Ready    <none>   141m   v1.19.3

attached is the support bundle. ( I zipped it - I hope that's ok)

[longhorn-support-bundle_f3f85f0c-acfd-479f-9a4d-6476fc282372_2021-01-29T11-43-39Z.zip](https://github.com/longhorn/longhorn/files/5893624/longhorn-support-bundle_f3f85f0c-acfd-479f-9a4d-6476fc282372_2021-01-29T11-43-39Z.zip)

**Comment by iangregsondev** [comment]
I did another quick test, same as before, but I detached the volume as it says it was attached to a node that no longer exists.

I re-attached it to a good node, and then all the replicas started up and everything was working again, healthy, 3 nodes - all good.

So now to repeat the process ( I am trying to feel certain that the volume re-attached to another node - because this test I am doing is a real world situation that can happy as DigitalOcean can destroy nodes)


I now took the new node where the volume was attached and recycled it (which effectively means destroying it and replacing it with another).

And the same thing happens, the new node is created but in longhorn it has 0 replicas.

And the volume is still set to be attached to the destroyed node.

Hope that helps, although it was the same process as before.

I supposed the support under has far more info than what I offered anyway..

Cheers.

**Comment by joshimoo** [comment]
@yasker This is most likely a bug on our end, I didn't have time to do a deep dive just yet.
But the manager keeps spamming the log with the below, which makes me think that we are failing to cleanup some resources/relationships.

```
2021-01-29T11:37:21.480435238Z time="2021-01-29T11:37:21Z" level=warning msg="The related node pool-rndlabs-old-39ke7 of instance test-e-92895343 is down or deleted, will mark the instance as state UNKNOWN"
2021-01-29T11:37:51.480389921Z time="2021-01-29T11:37:51Z" level=debug msg="cannot find instance manager instance-manager-e-2435c3ae"
```

**Comment by PhanLe1010** [comment]
@iangregsondev 

We checked the support bundle and see that the volume isn't used by any workload pod. Did you attach the volume to node using Longhorn UI? In this case, Longhorn doesn't move the volume to a new node because there is no need to do so (i.e., no workload is using it)

Can use try to deploy a workload ([example](https://longhorn.io/docs/1.1.0/references/examples/#statefulset)) then shutdown, delete, create the node where the workload is running on? You should see that workload move to new node, volume attach to new node, Longhorn rebuild replica on the new node.

By the way, if you want to do node maintenance (you control when to delete/remove/add the node), you can follow [our document](https://longhorn.io/docs/1.1.0/volumes-and-nodes/maintenance/) to properly tear down everything.

**Comment by iangregsondev** [comment]
Thank you, everyone, I knew it had to be me. I have tested it now and all seems well by creating a storageClass.

Thanks for all your help, excellent support!

I will close this.
