### ISSUE TITLE
[FEATURE] Record recurring schedule in the backups and allow user choose to use it for the restored volume

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2227]
**Is your feature request related to a problem? Please describe.**
Users need to reset the recurring schedule for the volumes that restored from the backups.

**Describe the solution you'd like**
We can support reuse the recurring schedule of the volume from the backup. So if the user lost the previous recurring schedule, it can be easily re-setup using the information from the backup. 

**Describe alternatives you've considered**
Other than manually reset the recurring schedule one by one, there is no alternatives.

**Additional context**
NA

**Comment by WisdomWolf** [comment]
You could create storage classes with the recurring backups schedule so that they don't have to be stored relative to the backup, right?

**Comment by pulberg** [comment]
@WisdomWolf The current storage class contains the recurring backup schedule.  When a backup is restored, it doesn't inherit the existing recurring backup schedule.  It would be great to be able to either inherit the existing backup schedule or be able to pick which schedule to use if there are multiple storage classes and backup schedules.

**Comment by joshimoo** [comment]
Some thoughts on this:
- we should move the recurring schedule out of the volume crd into it's own crd
- potentially just using the [kubernetes cronjob crd](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) with labels for volume etc.
- for backups we should just serialize the new crd and store it separately from the volume
- right now if a user has a mistake in their recurring definition, the volume/manager will fail to work correctly see https://github.com/longhorn/longhorn/issues/2423

**Comment by innobead** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Main-Board-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/2227?planning-poker) with ZenHub @jenting @PhanLe1010 @shuo-wu @joshimoo

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager ) with [the test steps](https://github.com/longhorn/longhorn/issues/2227#issuecomment-1301714960), and [the automated test case](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/328/testReport/tests/test_recurring_job/test_recurring_job_restored_from_backup_target_nfs_/) can pass, too.

**Comment by mantissahz** [comment]
Still need documents for this issue.

**Comment by mantissahz** [comment]
Document merged.
