### ISSUE TITLE
[FEATURE] automatic sucessful backups should only retain the last snapshot

### ISSUE THREAD

**Issue by ElZakariyae** [longhorn/longhorn#2231]
Hello,

we are using the longhorn backup solution to keep a copy of the volumes externally and then we realised that the snapshots created by the backup are stored locally the thing that made the nodes volume more and more bigger and that's our main problem.

our question is:

is there a way to self remove the snapshots after the backup succeeded? or maybe have a shorter retention period for the snapshots kept on disk than the backups stored externally?

any suggestions are highly appreciated.

thanks.

Environment:

    Longhorn version: v1.1.0
    Kubernetes version: v1.18.6
    Underlying Infrastructure: Rancher v2.4.8

**Comment by PhanLe1010** [comment]
@ElZakariyae 

Thank you for reporting. We will fix this in a future release.
Unfortunately, I don't see an easy workaround at the moment. 

Some of the initial ideas with our team:
1. Automatically delete the snapshot and only keep 1 or 2 snapshots for a recurring backup job. If users want to retain snapshots they can create a recurring snapshot instead.
1. Allow users to create a global setting that specifies the number of snapshots Longhorn will keep for every recurring backup jobs.

**Comment by PhanLe1010** [comment]
Manual test steps:
1. Create a recurring backup job
2. Verify that the number of snapshots created by the recurring backup job is capped at 2 (the snapshot of the last backup and the snapshot of the current backup)

**Comment by innobead** [comment]
@PhanLe1010 moving the current sprint because you are working on it.

**Comment by shuo-wu** [comment]
After introducing this feature, field `retain` in the recurring backup jobs can not determine the retained snapshot number anymore. But the related nightly tests are still checking the snapshot count based on the backup job `ratain` field. e.g., https://github.com/longhorn/longhorn-tests/blob/3c8c1e841cb44cef9cf5cb512ccb37a41d1e8404/manager/integration/tests/test_recurring_job.py#L350-L354

Do we need to update the tests as well?

**Comment by innobead** [comment]
As per the discussion, we need to keep one snapshot left after the backup. cc @PhanLe1010 @khushboo-rancher

**Comment by kaxing** [comment]
Validation - **Passed**

Tested on,
Longhorn 1.1.2-rc1
Kubernetes 1.21.6 (1 control + 3 worker nodes)
Rancher v2.5.8

With,
> Manual test steps:
> 
> 1. Create a recurring backup job
> 2. Verify that the number of snapshots created by the recurring backup job is capped at 2 (the snapshot of the last backup and the snapshot of the current backup)
> 3. Verify the number of backups match the retain count of the job
> 4. Create a recurring snapshot job
> 5. Verify the number of snapshots match the retain count of the job
> 6. Check the Allow Recurring Job While Volume Is Detached feature

By setting `Retain` to 1, 2 then 3, I am observing both snapshots and backups for the testing volume will match the `Retain` count setting.

Additional test: Reducing `Retain` count from 3 to 1, will also reflecting the retaining snapshot and backup numbers based on the schedule.
