### ISSUE TITLE
[BUG] Chart/Values.yml:defaultDataPath not utilized/respected

### ISSUE THREAD

**Issue by doug62** [longhorn/longhorn#2232]
Please note:

Values.yml:  defaultDataPath: "<a new value>"

Is not implemented in chart:longhorn/daemonset-sa.yaml

      - name: longhorn
        hostPath:
          path: /var/lib/longhorn/

**Comment by PhanLe1010** [comment]
The `/var/lib/longhorn` path in chart:longhorn/daemonset-sa.yaml is where Longhorn store engine-binaries and it is harder coded into the manage daemonset.

the `Values.yml: defaultDataPath` is where Longhorn store volumes' replica and it is configurable by users. 

So, they are 2 different concepts.
