### ISSUE TITLE
[FEATURE] Delete replicas when a node is deleted

### ISSUE THREAD

**Issue by tksm** [longhorn/longhorn#2235]
**Is your feature request related to a problem? Please describe.**

[`allow-node-drain-with-last-healthy-replica: false`](https://longhorn.io/docs/1.1.0/references/settings/#allow-node-drain-with-the-last-healthy-replica) feature which was introduced in v1.1.0 is great, but we still need to [evict replicas on the node manually](https://longhorn.io/docs/1.1.0/volumes-and-nodes/disks-or-nodes-eviction/) on Longhorn UI when we want to remove a Kubernetes node.

In our operation, when we remove a node from a cluster, we execute `kubectl drain` first, then execute `kubectl delete node`. If Longhorn was able to delete its replicas when a node is deleted, new replicas would be automatically created, so we would not need to evict replicas manually.

I understand that Longhorn keeps failed replicas for [rebuilding with existing data](https://github.com/longhorn/longhorn/blob/master/enhancements/20200821-rebuild-replica-with-existing-data.md). But when a node is deleted, the replicas on the node will be orphaned, so I believe we can safely delete these replicas.

**Describe the solution you'd like**

Longhorn to delete its replicas when a node is deleted so new replicas will be automatically created.

**Additional context**

If the volume is attached, replicas on a deleted node will be marked as `failed` and new replica will be created after `replica-replenishment-wait-interval`. We set `replica-replenishment-wait-interval` to `0` for an immediate replenishment. But if the volume is detached, the replica on the deleted node is still `healthy`, so under [`allow-node-drain-with-last-healthy-replica: false`](https://longhorn.io/docs/1.1.0/references/settings/#allow-node-drain-with-the-last-healthy-replica) the last replica will be deleted.

**Comment by shuo-wu** [comment]
1. Which Longhorn version are you using? In v1.1.0, Longhorn removes the node deletion API from the UI. The node object in Longhorn will be cleaned up automatically only if the Kubernetes node is deleted from the cluster. But when you run `kubectl -n longhorn-system delete nodes.longhorn.io <Node Name>`, it will directly remove the node regardless of the replicas.
2. Longhorn should not count a stopped replica in a removed disk/node as a healthy replica for setting `allow-node-drain-with-last-healthy-replica: false`. This is definitely a bug. Thank you for pointing it out! We are using a separate issue to track it: https://github.com/longhorn/longhorn/issues/2237
3. Actually Longhorn supports eviction for detached volumes: https://github.com/longhorn/longhorn/issues/1704. If you can evict the node before removing it, the case in `Additional context` won't be a problem.
4. We add a new setting that allows Longhorn to evict replicas automatically when a node is drained.
5. The reason why we won't remove the related replicas on a gone node is that the cluster may be updated and the node will be added back later. If the replicas are removed, then there is no way to reuse the replicas and it may cause data loss.

**Comment by tksm** [comment]
Thank you for your quick reply!

> Which Longhorn version are you using? In v1.1.0, Longhorn removes the node deletion API from the UI. The node object in Longhorn will be cleaned up automatically only if the Kubernetes node is deleted from the cluster. But when you run kubectl -n longhorn-system delete  [nodes.longhorn.io](http://nodes.longhorn.io/)  <Node Name>, it will directly remove the node regardless of the replicas.

We use Longhorn v1.1.0. Currently we only delete a Kubernetes node object.

> We add a new setting that allows Longhorn to evict replicas automatically when a node is drained.

With https://github.com/longhorn/longhorn/issues/2237 , this is the perfect solution for us :+1:

> The reason why we won't remove the related replicas on a gone node is that the cluster may be updated and the node will be added back later. If the replicas are removed, then there is no way to reuse the replicas and it may cause data loss.

Now I understand. Thank you for your explanation.

**Comment by innobead** [comment]
Let's track at https://github.com/longhorn/longhorn/issues/2237
