### ISSUE TITLE
[Question] unable to mount NFS backup

### ISSUE THREAD

**Issue by rsoika** [longhorn/longhorn#2242]
**Question**

I have a strange behaviour with a NFS Backup Store. I have two different kubernetes clusters. From the one I can backup volumes and list the backups on my nsf storage. 
But on the other cluster backup failes and also when I try to list the backups from the Lonhorn UI I got the following error displayed: 

`error listing backups: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn [backup ls --volume-only nfs://foo.com:/var/backups/nfs], output Cannot create mount directory /var/lib/longhorn-backupstore-mounts/foo_com/var/backups/nfs for NFS server , stderr, time="2021-02-07T21:24:35Z" level=error msg="Cannot create mount directory /var/lib/longhorn-backupstore-mounts/foo_com/var/backups/nfs for NFS server" , error exit status 1`

I tried it now for several hours but I can not figure out what is going wrong. I shut down the firewall, grant the directories with 777 but no success. I don't have the slightest idea where I could look. 

What does the message above tell me? On which server is the problem? On my nfs server or on my kubernetes node?

When I try to create a backup, then the following error message is shown:

`fail to backup snapshot: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn [--url 10.244.4.137:10007 backup create --dest nfs://foo.com:/var/backups/nfs --label KubernetesStatus={"pvName":"pvc-360b2857-c0b1-4c61-b511-e948ff0258f3","pvStatus":"Bound","namespace":"myvolume-test","pvcName":"index","lastPVCRefAt":"","workloadsStatus":[{"podName":"imixs-office-workflow-7bffb6d598-v75lk","podStatus":"Running","workloadName":"imixs-office-workflow-7bffb6d598","workloadType":"ReplicaSet"}],"lastPodRefAt":""} 68430f1d-7de5-496a-ac34-ddaf10b3660b], output , stderr, time="2021-02-07T21:40:47Z" level=info msg="Backing up 68430f1d-7de5-496a-ac34-ddaf10b3660b on tcp://10.244.4.138:10150, to nfs://foo.com:/var/backups/nfs" time="2021-02-07T21:40:47Z" level=fatal msg="Error running create backup command: failed to create backup to nfs://foo.com:/var/backups/nfs for volume pvc-360b2857-c0b1-4c61-b511-e948ff0258f3: rpc error: code = Unknown desc = Cannot create mount directory /var/lib/longhorn-backupstore-mounts/foo_com/var/backups/nfs for NFS server" , error exit status 1`

From the /etc/exports file on my NFS Server I added all the IP Adresses form my kubernetes nodes. All IPs are public IPs.

The very strange thing is, that even on the cluster on which I have the problems there are some volumes that can be backuped. But some other volumes can not. 

On the cluster I have 5 nodes. Each volume has 3 replicas. It looks that volumes attached to some of my nodes having the problem, and other volumes not. 

It all sounds pretty stupid, but I can't describe it any better at the moment. 

I am thankful for any kind of hint. 

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version: 1.19.3
 - Node config
   - OS type and version debian
 - Underlying Infrastructure (Baremetal):

**Comment by rsoika** [comment]
Finally I narrowed the problem down to only one of my nodes in the cluster. And I decided to drain and remove the node. Backup on the other nodes worked fine. 
We have also this discussion thread in parallel: https://forums.rancher.com/t/nfs-backup-cannot-create-mount-directory/19436/4

I think we can close this issue if you not have any thoughts about this. I am now unable to provide more information because the node is decommissioned.

**Comment by PhanLe1010** [comment]
The error is not on the NFS server side. It is either because of Longhorn or the cluster node.
When listing backups, one of Longhorn managers (one of the pod `longhorn-manager-xxxxx`) tries to create a directory (the directory `/var/lib/longhorn-backupstore-mounts/foo_com/var/backups/nfs` in this post) inside the its container 
When taking a backup, one of Longhorn replica instance manager pod (one of the pod `instance-manager-r-xxxxxxxx`) tries to create a directory (the directory `/var/lib/longhorn-backupstore-mounts/foo_com/var/backups/nfs` in this post) inside the its container.

The error in this issue comes from [this line of code ](https://github.com/longhorn/backupstore/blob/e3b5c5a6d3ae70c1ca33d42aa1d882bc8eb5a051/nfs/nfs.go#L67), Longhorn manager/replica instance manager pods are complaining that it cannot create a directory inside its container. This is just a simple `mkdir ` operation. Unfortunately, we don't print out the err which explains why Longhorn cannot make the directory. So, I am not sure what is the root cause. 

Can you please send us a support bundle so we can take a look at the Longhorn deployment configuration? Can you also fill out the below template so we have more info about your cluster?

**Environment:**
 - Longhorn version:
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by rsoika** [comment]
@PhanLe1010  what did you mean with a 'support bundle'? How do I generate this?

**Comment by rsoika** [comment]
**My Environment:**

    Longhorn version: 1.1.0
    Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: self hosted kubernetes - kubelet 1.19.3, Docker Version 19.3.13, Linux Kernel 4.19.0-12-amd64 
        Number of management node in the cluster: 1
        Number of worker node in the cluster: 3
    Node config
        OS type and version: debian
        CPU per node: 4
        Memory per node: 16Gi
        Disk type(e.g. SSD/NVMe): SSD 160Gi
        Network bandwidth between the nodes: 10 GBit 
    Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): http://hetzner.de    - cloud servers
    Number of Longhorn volumes in the cluster: 70

**Comment by joshimoo** [comment]
We want to improve the error messages for this failure case, so that we get additional details of why the mkdir doesn't work.

**Comment by rsoika** [comment]
Yes, this would help. The strange thing is, that the NFS backup works on some nodes in my cluster and on others not. Restarting pods seems not to help. But as long as I know which node is working, I can attach a volume to such a node and backup it. So for the moment I can help myself. But sure, it would be better to understand the root of the problem. 

If I do a ssh on a pod, which I know is not working, maybe I can try some kind of command to provide you with more information? I would like to support you. Also because I still fear that I made a so-called stupid mistake somewhere else in my environment... 

One addition background information: I have connected two clusters to the same NFS storage. This is because I use the backup feature from longhorn to move productive volumes from one cluster into another. Can this be an issue?

**Comment by PhanLe1010** [comment]
@rsoika 
You can use Longhorn UI to generate a support bundle. The link on the bottom
<img width="573" alt="Screen Shot 2021-02-11 at 4 19 12 PM" src="https://user-images.githubusercontent.com/22139961/107715927-1b55f380-6c85-11eb-83ba-0fd5501c2e5d.png">
 in the below picture:

**Comment by PhanLe1010** [comment]
> One addition background information: I have connected two clusters to the same NFS storage. This is because I use the backup feature from longhorn to move productive volumes from one cluster into another. Can this be an issue?

I don't think it is an issue since this is how [DR volumes](https://longhorn.io/docs/1.1.0/snapshots-and-backups/setup-disaster-recovery-volumes/) work across the different clusters.

@joshimoo Do you see any problem?

**Comment by PhanLe1010** [comment]
> If I do a ssh on a pod, which I know is not working, maybe I can try some kind of command to provide you with more information? 

Can you exec into the pod which you know is not working and try to `mkdir -p -m 700 /var/lib/longhorn-backupstore-mounts/foo_com/var/backups/nfs` to see if it is ok.

**Comment by joshimoo** [comment]
Don't see any problem with using the same longhorn backup target (nfs storage) for multiple clusters.

@rsoika If you want test you can kubectl exec into the longhorn-manager pod where the backup fails and try to run the failing mkdir command manually. edit see above suggestion by @PhanLe1010 :)

**Comment by rsoika** [comment]
I generated a support bundle but it has a size of 67MB and I can  upload only files smaller than 10MB. The bundle contains very large log files... I deleted some of them
[longhorn-support-bundle_d583a0b5-9d5f-457e-ae59-1a6152d002b6_2021-02-12T09-27-17Z (Kopie).zip](https://github.com/longhorn/longhorn/files/5970782/longhorn-support-bundle_d583a0b5-9d5f-457e-ae59-1a6152d002b6_2021-02-12T09-27-17Z.Kopie.zip)

**Comment by rsoika** [comment]
for example the csi-snapshotter.log files contain thousands of messages like this:

```2021-02-11T12:26:27.656790699Z I0211 12:26:27.656646       1 reflector.go:188] Listing and watching 
*v1beta1.VolumeSnapshotContent from pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108
2021-02-11T12:26:27.661492441Z E0211 12:26:27.661290       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1beta1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
```

**Comment by rsoika** [comment]
I did a ssh on the replica-manager on node worker-4 which is affected from the issue:
```

ls: cannot access '/var/lib/longhorn-backupstore-mounts/foo_com/var/backups/nfs': No such file or directory
root@instance-manager-r-b250cb74:/# mkdir -p -m 700 /var/lib/longhorn-backupstore-mounts/foo_com/var/backups/nfs
root@instance-manager-r-b250cb74:/# 
```

**Comment by rsoika** [comment]
The csi-provisioner log files are flooded with messages like this:

```
2021-01-25T11:34:17.284554018Z I0125 11:34:17.284256       1 leaderelection.go:247] failed to acquire lease longhorn-system/driver-longhorn-io
2021-01-25T11:34:23.209199956Z I0125 11:34:23.208919       1 leaderelection.go:352] lock is held by csi-provisioner-d444fb7c9-kd7zt and has not yet expired
2021-01-25T11:34:23.209279355Z I0125 11:34:23.208962       1 leaderelection.go:247] failed to acquire lease longhorn-system/driver-longhorn-io
2021-01-25T11:34:30.813444322Z I0125 11:34:30.813247       1 leaderelection.go:352] lock is held by csi-provisioner-d444fb7c9-kd7zt and has not yet expired
```

**Comment by rsoika** [comment]
...and the csi-attacher.log files are flooded with messages like this :

```
2021-02-02T14:33:15.962557432Z I0202 14:33:15.962442       1 leaderelection.go:352] lock is held by csi-attacher-74db7cf6d9-ncfwt and has not yet expired
2021-02-02T14:33:15.962590833Z I0202 14:33:15.962463       1 leaderelection.go:247] failed to acquire lease longhorn-system/external-attacher-leader-driver-longhorn-io
2021-02-02T14:33:20.995401609Z I0202 14:33:20.994819       1 leaderelection.go:352] lock is held by csi-attacher-74db7cf6d9-ncfwt and has not yet expired
```

maybe the NFS is not the root problem...?

**Comment by joshimoo** [comment]
The leader election logs are debug logs you can ignore them as long as the mentioned pods `csi-attacher-74db7cf6d9-ncfwt` and `csi-provisioner-d444fb7c9-kd7zt` are active you should be able to see the current operations in it.

For the snapshotter you need to install the crds if you want to use csi snapshot support, more info here:
https://longhorn.io/docs/1.1.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master - `03/29/2021`

Validation - **Pass**

The error message is logged as below in case the `var/lib/longhorn-backupstore-mounts` is deleted and a file with same name is created in the longhorn-manager pods.

```
[longhorn-manager-bjnf7] time="2021-03-23T06:34:33Z" level=error msg="Error in request: error listing backups: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master/longhorn [backup ls --volume-only nfs://3.138.138.33:/nfs], output Cannot create mount directory /var/lib/longhorn-backupstore-mounts/3_138_138_33/nfs for NFS server: mkdir /var/lib/longhorn-backupstore-mounts: not a directory\n, stderr, time=\"2021-03-23T06:34:33Z\" level=error msg=\"Cannot create mount directory /var/lib/longhorn-backupstore-mounts/3_138_138_33/nfs for NFS server: mkdir /var/lib/longhorn-backupstore-mounts: not a directory\"\n, error exit status 1" 
```
