### ISSUE TITLE
[BUG] Nodes and volumes not listed in UI after longhorn-manager update

### ISSUE THREAD

**Issue by gsacre** [longhorn/longhorn#2243]
**Describe the bug**
I cannot see anything (nodes, volumes...) in the UI after longhorn-engine update from v1.0.x to v1.1.0

**To Reproduce**
1. `wget https://raw.githubusercontent.com/longhorn/longhorn/v1.1.0/deploy/longhorn.yaml`
2. Edit `longhorn.yaml` to set default data path
3. `kubectl apply -f longhorn.yaml`
4. Wait for containers to be updated / (re-)created
5. Go to UI and refresh

**Expected behavior**
All resources are available in the UI.

**Log**
```shell
$ kubectl get pods --namespace longhorn-system
NAME                                       READY   STATUS    RESTARTS   AGE
csi-attacher-5dcdcd5984-924xp              1/1     Running   1          14m
csi-attacher-5dcdcd5984-gzlcp              1/1     Running   1          14m
csi-attacher-5dcdcd5984-xjh74              1/1     Running   1          14m
csi-provisioner-5c9dfb6446-646tk           1/1     Running   0          14m
csi-provisioner-5c9dfb6446-pfsln           1/1     Running   0          14m
csi-provisioner-5c9dfb6446-rpzh6           1/1     Running   0          14m
csi-resizer-54d484bf8-lvz69                1/1     Running   0          14m
csi-resizer-54d484bf8-nzdkk                1/1     Running   0          14m
csi-resizer-54d484bf8-vcq75                1/1     Running   0          14m
csi-snapshotter-96bfff7c9-6xmwf            1/1     Running   0          14m
csi-snapshotter-96bfff7c9-dzfzn            1/1     Running   0          14m
csi-snapshotter-96bfff7c9-hzpdx            1/1     Running   0          14m
engine-image-ei-cf743f9c-mnn4b             1/1     Running   0          16m
engine-image-ei-cf743f9c-nhf4d             1/1     Running   0          16m
engine-image-ei-cf743f9c-qzrj8             1/1     Running   0          16m
engine-image-ei-ee18f965-5rxs8             1/1     Running   8          66d
engine-image-ei-ee18f965-nmv22             1/1     Running   8          66d
engine-image-ei-ee18f965-zc4zc             1/1     Running   8          66d
instance-manager-e-48b51d13                1/1     Running   0          3d1h
instance-manager-e-7d5a792b                1/1     Running   0          16m
instance-manager-e-93134506                1/1     Running   0          3d1h
instance-manager-e-c1bd5cbb                1/1     Running   0          16m
instance-manager-e-e6d5b5c9                1/1     Running   0          16m
instance-manager-r-0b7fd4d4                1/1     Running   0          16m
instance-manager-r-12124a9a                1/1     Running   0          3d1h
instance-manager-r-34954b99                1/1     Running   0          3d
instance-manager-r-7a068535                1/1     Running   0          16m
instance-manager-r-9ee77ee3                1/1     Running   0          3d1h
instance-manager-r-b3ee68f2                1/1     Running   0          16m
longhorn-csi-plugin-9bjw9                  2/2     Running   0          9m49s
longhorn-csi-plugin-9rl9k                  2/2     Running   0          14m
longhorn-csi-plugin-zzfsv                  2/2     Running   0          14m
longhorn-driver-deployer-cdb7464c6-5gjr6   1/1     Running   0          17m
longhorn-manager-jt278                     1/1     Running   0          17m
longhorn-manager-k9nx9                     1/1     Running   0          17m
longhorn-manager-p5d5j                     1/1     Running   0          17m
longhorn-ui-849c455d79-tp8j7               1/1     Running   0          17m
```

![image](https://user-images.githubusercontent.com/656009/107227291-7f757f00-6a1b-11eb-8f08-d4ae66db9f00.png)

**Environment:**
 - Longhorn version: v1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: on premise install
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 2 (managers) and 4 (workers)
   - Memory per node: 2GB (managers) and 16GB (nodes)
   - Disk type(e.g. SSD/NVMe): 
   - Network bandwidth between the nodes: Gigabit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 2 (still testing it out)

**Additional context**
Although the UI is empty, it doesn't give any error.
The Engine Image page is empty (it wasn't before the update) and I don't know what should I have there.
The services using the volumes are still working fine.
I followed the upgrade instructions on the website using kubectl.

EDIT: added screenshot

**Comment by joshimoo** [comment]
@gsacre @smallteeths I don't remember exactly, but I think after the v1.1 update the user needs to close the browser, is that correct?

**Comment by gsacre** [comment]
> 
> 
> @gsacre @smallteeths I don't remember exactly, but I think after the v1.1 update the user needs to close the browser, is that correct?

I checked again the docs because I wasn't sure, but nothing is written.

I've closed my browser (Firefox) and just to be sure, I opened another one (Chrome), but still nothing.

**Comment by timmy59100** [comment]
After 1.1 the path is slightly different. If you have bookmarked it you have to open it new from the apps page.

**Comment by gsacre** [comment]
> 
> 
> @gsacre @smallteeths I don't remember exactly, but I think after the v1.1 update the user needs to close the browser, is that correct?

I checked again the docs because I wasn't sure, but nothing is written.

I've closed my browser (Firefox) and just to be sure, I opened another one (Chrome), but still nothing.
