### ISSUE TITLE
[TASK] Test Longhorn on high spec nodes

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2246]
**Is your feature request related to a problem? Please describe.**
There may be some unexpected issues when Longhorn creates snapshots/backups on high spec nodes:
https://github.com/longhorn/longhorn/issues/1675
https://github.com/longhorn/longhorn/issues/2029

**Comment by yasker** [comment]
This should be included in #2598 .

**Comment by yasker** [comment]
Considering merging with #2598 because it should be included there.

**Comment by innobead** [comment]
Closing, let's tracking  #2598.
