### ISSUE TITLE
[BUG] Sort functionality for size on longhorn UI for nodes is not working 

### ISSUE THREAD

**Issue by anupama2501** [longhorn/longhorn#2247]
**To Reproduce**
1. Install the longhorn app
2. From the longhorn UI in the nodes tab, click on the sort button for size.
3. We can see that sort action is not working

<img width="1016" alt="Screen Shot 2021-02-10 at 2 38 28 PM" src="https://user-images.githubusercontent.com/38144301/107582187-022e4380-6bae-11eb-81ae-4ad444633e0e.png">

**Expected behavior**
After clicking on the sort button, the sizes should've been sorted numerically

Longhorn Version:
v1.1.0

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master - `5d83fc4` - `02/23/2021`

Validation - Pass

The sorting for columns `Status`, `Name`, `Replicas`, `Allocated`, `Used`, `Size` are working fine.
