### ISSUE TITLE
[Question] programmatically changing longhorn settings

### ISSUE THREAD

**Issue by antonum** [longhorn/longhorn#2252]
**Question**

How do I programmatically read the current state and change individual settings in Longhorn? For example DefaultDataPath, PodDeletionPolicyWhenNodeisDown?

Ideally via kubectl. I'm aware of https://longhorn.io/docs/1.1.0/advanced-resources/deploy/customizing-default-settings/#using-the-longhorn-deployment-yaml-file but it's more "all or nothing" approach and still doesn't let me read the current values. 

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version: 1.18.9/EKS

**Comment by joshimoo** [comment]
@antonum you can access and edit all settings via `kubectl get settings.longhorn.io -n longhorn-system`

**Comment by PhanLe1010** [comment]
To echo what @joshimoo mentioned about the Longhorn API. We have document about how build a Python script to control Longhorn system https://longhorn.io/docs/1.1.0/references/longhorn-client-python/

Longhorn CLI is also on the roadmap.

**Comment by antonum** [comment]
Excellent! Thank you! Feel free to close the issue.
