### ISSUE TITLE
[FEATURE] Type of the "Concurrent Automatic Engine Upgrade Per Node Limit" to be integer

### ISSUE THREAD

**Issue by anupama2501** [longhorn/longhorn#2253]
**Is your feature request related to a problem? Please describe.**
**Describe the bug**
Type of the "Concurrent Automatic Engine Upgrade Per Node Limit" to be integer. The field right now is a LabeledInput

**To Reproduce**
From the longhorn UI, go to settings -- General
In the concurrent Automatic Engine Upgrade Per Node Limit, if we put in any value eg., string, special characters, etc., the text box takes in the value. Verification is done when we save the config and it wont let the user.

**Describe the solution you'd like**
Request to add in a verification the frontend itself and not let users input any value other than integer.

**Describe alternatives you've considered**
A description can be given showing only range 0-20 is allowed and also only integers allowed.
Users can be displayed with a warning or not allowed to input anything when they input values other than provided in the description

**Additional context**
Below screenshot shows, the user can input any string.
![Screen Shot 2021-02-12 at 5 27 47 PM](https://user-images.githubusercontent.com/38144301/107837912-17df6c80-6d58-11eb-8728-0608fdfd877c.png)
![Screen Shot 2021-02-12 at 5 27 19 PM](https://user-images.githubusercontent.com/38144301/107837915-19a93000-6d58-11eb-9ca0-4c22bbe5780a.png)

**Comment by yasker** [comment]
@smallteeths can you check if this is something can be enforced in UI?

**Comment by khushboo-rancher** [comment]
After discussing with @yasker we decided to show error from frontend for all below fields that take only integer as an input to have consistency across the settings.

1. Concurrent Automatic Engine Upgrade Per Node Limit
2. Default Replica Count
3. Replica Replenishment Wait Interval
4. Backupstore Poll Interval
5. Storage Minimal Available Percentage
6. Storage Over Provisioning Percentage

**Comment by yasker** [comment]
As a note: the information of acceptable data type should be sent to the frontend already, so we shouldn't need to hard-code the name of the field for the validation.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master `02/24/2021`

Validation - **Pass**

The below fields in the setting only accept the integer value and on leaving it blank shows the error.
1. Concurrent Automatic Engine Upgrade Per Node Limit
2. Default Replica Count
3. Replica Replenishment Wait Interval
4. Backupstore Poll Interval
5. Storage Minimal Available Percentage
6. Storage Over Provisioning Percentage

<img width="692" alt="Screen Shot 2021-02-24 at 8 24 01 PM" src="https://user-images.githubusercontent.com/60111667/109018638-4ce7a980-76de-11eb-85fd-e0c31cad9ee7.png">
