### ISSUE TITLE
[BUG] Some longhorn volumes stuck detaching after SAN problems which made the virtual machines reboot/pause

### ISSUE THREAD

**Issue by vikstlu** [longhorn/longhorn#2254]
**Describe the bug**
We had an outage in our datacenter where there were some problems with the SAN/network causing oVirt to restart/pause all virtual machines. After the virtual machines have restarted and the cluster is up again (took around 2 hours before we unpaused some virtual machines) some volumes in longhorn are stuck in detaching. I tested to manually mount one of the replicas (using docs here: https://longhorn.io/docs/1.1.0/advanced-resources/data-recovery/export-from-replica/) and that worked. I copied out files that I need already.

**To Reproduce**

**Expected behavior**
After the nodes are up again detaching the volumes to be able to restore failed replicas or just start up again.

**Log**
[longhorn-support-bundle_d0bcbd78-f60b-425a-b849-a4e727dd24b1_2021-02-14T04-48-49Z.zip](https://github.com/longhorn/longhorn/files/5977029/longhorn-support-bundle_d0bcbd78-f60b-425a-b849-a4e727dd24b1_2021-02-14T04-48-49Z.zip)

**Environment:**
 - Longhorn version: v1.0.2
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RancherUI provisioned rke on virtual machines with docker
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 14
 - Node config
   - OS type and version: CentOS 7
   - CPU per node: 6
   - Memory per node: 16GB
   - Disk type(e.g. SSD/NVMe): SAN (tegile intelliflash)
   - Network bandwidth between the nodes: 10Gb/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): oVirt (kvm)
 - Number of Longhorn volumes in the cluster: 8

**Additional context**

**Comment by joshimoo** [comment]
Thanks for reporting.
We solved a few problems related to volume attach/detach state changes in v.1.1
Would you be able to update to this new version?

**Comment by vikstlu** [comment]
Hi, sorry about this bug request. You can close it. Had forgotten about it when we had similar problems with the SAN next night again.

This was due oVirt pausing some of the kubernetes nodes during the SAN LUN problems. Those virtual machines that just continued to run after 2-3 hours paused had their clocks running 2-3 hours wrong. Chrony started correcting the clocks by speeding them up on the virtual machines for them to catch up, and after a some hours the clocks were in sync again and longhorn resolved itself.
Thank you for responding to this. I'll now upgrade to v 1.1. when we finally have the SAN issues resolved.

**Comment by joshimoo** [comment]
@vikstlu Thanks for responding, will close the issue, please feel free to reach out if you have another issue in the future.
