### ISSUE TITLE
[ENHANCEMENT] Manage cloud provider storage via storage class then schedule longhorn replicas on the cloud provider attached volumes

### ISSUE THREAD

**Issue by iangregsondev** [longhorn/longhorn#2255]
**Question**

Hi, 

I would like to add a persistent volume to my digitalocean cluster, this is supported (see links below) by using a do-block-storage storage class but I am unsure how to get longhorn to use this volume ?

https://www.digitalocean.com/docs/kubernetes/how-to/add-volumes/

Does anybody have any experience with this, is there a small HOW TO on longhorn ?

Maybe I am reading into it too deep, but the volume is already attached using the above storage class so how can longhorn manage this ?

**Comment by joshimoo** [comment]
You need to ensure, the do volume is attached to the node then you can make longhorn use the volume to create new replicas on it.

**Comment by iangregsondev** [comment]
Ok Thanks @joshimoo .

I will close this now.
