### ISSUE TITLE
[FEATURE] Upgrade engine image other options to be greyed out while the upgrade is going on

### ISSUE THREAD

**Issue by anupama2501** [longhorn/longhorn#2260]
**Is your feature request related to a problem? Please describe.**
When the concurrent value is set and when the upgrade starts, if we try any other options such as update replica count or delete or detach, we don't see the option we just clicked on working. Even after the engine upgrade is finished, we don't see the volume deleted or replica count increased/decreased.

**Describe the solution you'd like**
Please grey out the other options, when the upgrade starts as when we try to delete/update replica/ take backup doesn't work. Once the volume is upgraded, then the options work.

**Additional context**
The options mentioned here can be greyed out:
<img width="347" alt="Screen Shot 2021-02-16 at 7 38 33 AM" src="https://user-images.githubusercontent.com/38144301/108085266-003f0700-702a-11eb-9631-386372ed07cc.png">

**Comment by yasker** [comment]
@PhanLe1010 Can you check to see which options should be disabled during engine upgrade?

**Comment by PhanLe1010** [comment]
I think we should disable:
* Update replica count (we shouldn't disrupt the upgrading replicas)
* Update data locality (we shouldn't disrupt the upgrading replicas)
* Backups (we shouldn't disrupt the upgrading engine)

I think `Delete` and `Detach` action should work from the code perspective. I also tested them on a cluster. Can you verify it @anupama2501 ?

**Comment by PhanLe1010** [comment]
Btw, I think UI can determine whether the volume is upgrading engine image by comparing `curretnImage` and `engineImage` in the volume resource returned by API `v1/volumes`

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master UI `03/03/2021` - `a8ebc99`

Validation - **PASS**

The options replica count, data locality and backups, snapshot operations are greyed out.
