### ISSUE TITLE
[TASK] Verify the changes in rancher charts are in sync with the Longhorn chart.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2262]
**Description**
Before the release v1.1.1, make sure the changes made in the Longhorn chart are available in the Rancher charts.
Also, compare the charts with the Longhorn Yaml file before the release.

**Additional Context**
https://github.com/longhorn/longhorn/issues/2200

**Comment by innobead** [comment]
QA has verified the chart PRs in https://github.com/longhorn/longhorn/issues/2523#issuecomment-827840783. The rest of works will be followed in #2523 .
