### ISSUE TITLE
How can I resize the longhorn volume? The new size should be shown in both rancher&longhorn UI

### ISSUE THREAD

**Issue by mohjam2004** [longhorn/longhorn#2263]
**Question**
I only can resize longhorn volume through longhorn ui and the new size is not shown in rancher ui (the old value is shown).
In this way when I start the pod everything is fine and pod starts successfully. (but in rancher ui the volume size is old)
If I use another way to change the volume size and  edit the PV yaml file, the pod can't start and get failed log (in this way the volume size is not updated in rancher ui).

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version: 1.17.14
 - Node config
   - OS type and version: debian 10 buster
   - CPU per node: 4 cores
   - Memory per node: 4GB
   - Disk type: VM Disk
   - Network bandwidth and latency between the nodes: 1Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare

**Additional context**

this is the process that I take:

I stopped the pod, edited the PVC yaml file and increase the capacity. but my pod failed to start because of this error:
MountVolume.Setup failed while expanding volume for volume "pvc-d1503cd0-2eda-40ba-8336-1a6d114af841" : MountVolume.NodeExpandVolume failed : Expander.NodeExpand failed to expand the volume : rpc error: code = Unimplemented desc =
These are my PVs:
![image](https://user-images.githubusercontent.com/59224403/108196992-08349f00-712f-11eb-80ef-737c159a8f91.png)

This is my PV before change:
![image](https://user-images.githubusercontent.com/59224403/108197208-4cc03a80-712f-11eb-8f72-f63274f40251.png)

I change the storage: 8Gi to 10Gi
![image](https://user-images.githubusercontent.com/59224403/108197314-75483480-712f-11eb-9a85-8cc56ab63ecd.png)

then start the pod, this is my failed log:
![image](https://user-images.githubusercontent.com/59224403/108197477-ade80e00-712f-11eb-8304-c51641a15a2a.png)

This is my storage class config: (expansion is enabled)
![image](https://user-images.githubusercontent.com/59224403/108197580-cf48fa00-712f-11eb-9b51-c4116cc200e4.png)

After the size change in PV yaml file, the volume size is still old (8G) and it is not the new value(10G):
![image](https://user-images.githubusercontent.com/59224403/108198501-ed632a00-7130-11eb-8eb9-039a8f0976da.png)

**Comment by PhanLe1010** [comment]
@mohjam2004 

To see the change inside Kubernetes (through Rancher ), you need to edit the PVC instead. See more instruction at https://longhorn.io/docs/1.1.0/volumes-and-nodes/expansion/#via-pvc

**Comment by mohjam2004** [comment]
Hi @PhanLe1010 
AS I explained in my 1st post, I have edited the Persistent volume yaml file. But I don't have the parameter: spec.resources.requests.storage as the longhorn document explain.

longhorn doc:
![image](https://user-images.githubusercontent.com/59224403/108584770-24b41f80-7359-11eb-8724-20dd4c938254.png)

what I see when I edit my persistent volume:
![image](https://user-images.githubusercontent.com/59224403/108584799-5d53f900-7359-11eb-995b-1965395b49c5.png)

When I change "storage" parameter, the change is not shown in rancher ui and I can't start my pod which use this PV.

**Comment by PhanLe1010** [comment]
@mohjam2004 

You need to edit Persistence Volume Claim, not the Persistent Volume. When you edit PVC, Kubernetes will automatically try to expand the PV by asking Longhorn CSI to expand the underlying Longhorn volume. 

The Longhorn document shows how to edit a PVC.

**Comment by PhanLe1010** [comment]
To find the PVC, you can try:
kubectl get pvc -n <NAMESPACE-OF-PROMETHEUS>

**Comment by mohjam2004** [comment]
Hello @PhanLe1010 
Thanx a lot for the help.
1st I stopped the pod then I edited the PVC claim.
Now the changes is shown both in rancher and longhorn ui.

**Comment by hextrim** [comment]
I think that long story short, the volume have to be detached to allow for expansion.
You can edit PVC and update the size, but this wont happen until you eventually remove the workload and detach volume.

The are two options here:
1. edit PVC and update the size, when you stop the workload and CSI detach the volume, expansion will start.
2. stop the workload the CSI will detach the volume, then expand the volume via GUI.

**Comment by Conspir3D** [comment]
both options not working for me.
trying 1: edited PVC stopped workload, expasion didn't start
trying 2: stopped workload, try to expand via GUI but withour error the expansion didn't start, no matter how often i try

In general i feel the GUI ist quite laggy/buggy regading changes to volumes. i often had to do changes several times until the will be executed an shown in the UI. this is with replica count, locallity, expansion ...
am i alone with this experience, maybe i have somthing misconfigured ?

**Comment by Exagram** [comment]
@hextrim Is this what you mean?
1. edit pvc and update size. Makes sense. i.e. `kubectl apply -f pvc-with-bigger-disk-space.yml`
2. Stop the workload. Do you mean `kubectl scale deployment/blah --replicas=0`?
3. What do you mean by detach the volume?

**Comment by edantes-1845** [comment]
For expanding a Longhorn volume I do:
1. Stop workload with this volume
2. Longhorn UI: this volume has to have detached status
3. Delete PVC
4. Delete PV
5. Longhorn UI: expand volume
6. Longhorn UI: create PV/PVC
7. Start workload

**Comment by PhanLe1010** [comment]
>For expanding a Longhorn volume I do:
Stop workload with this volume
Longhorn UI: this volume has to have detached status
Delete PVC
Delete PV
Longhorn UI: expand volume
Longhorn UI: create PV/PVC
Start workload

If you delete PVC and PV, you might lose the Longhorn volume. 

Please refer to the document for the instruction https://longhorn.io/docs/1.2.4/volumes-and-nodes/expansion/#expand-a-longhorn-volume

**Comment by edantes-1845** [comment]
> > For expanding a Longhorn volume I do:
> > Stop workload with this volume
> > Longhorn UI: this volume has to have detached status
> > Delete PVC
> > Delete PV
> > Longhorn UI: expand volume
> > Longhorn UI: create PV/PVC
> > Start workload
> 
> If you delete PVC and PV, you might lose the Longhorn volume.
> 
> Please refer to the document for the instruction https://longhorn.io/docs/1.2.4/volumes-and-nodes/expansion/#expand-a-longhorn-volume

Yes you are right, but if your volume has **detached** state, you can delete PVC/PV safely
![image](https://user-images.githubusercontent.com/60153776/166699467-9baabdc7-a102-416f-ba55-bb7d40b10920.png)

After all manipulations with this volume, you can re-create PV/PVC through Longhorn UI 
![image](https://user-images.githubusercontent.com/60153776/166700468-b711b803-7058-4edd-a7d7-e877d70ff57a.png)

**Comment by blackbass64** [comment]
> For expanding a Longhorn volume I do:
> 
> 1. Stop workload with this volume
> 2. Longhorn UI: this volume has to have detached status
> 3. Delete PVC
> 4. Delete PV
> 5. Longhorn UI: expand volume
> 6. Longhorn UI: create PV/PVC
> 7. Start workload

No need to delete the PVC to expand Longhorn volumes. Just stop the workloads, which will make the PV in a `Detached` state, then resize the volume via PVC, and restart the workloads. This keeps the process simpler and safer without risking data loss :)
