### ISSUE TITLE
[BUG] Error during WebSocket handshake for Longhorn UI

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2264]
**Describe the bug**
The Longhorn UI shows 404 error for some request on refreshing the page or while navigating to different tabs but the operations on the page work fine.

**To Reproduce**
1. Deploy Longhorn Master on a cluster of 4 nodes (1 etcd/control plane, 3 worker)
2. Navigate to Longhorn UI using rancher proxy on google chrome.
3. Open console on the dev tool. See the below error.
```
WebSocket connection to 'wss://khushlh.qa.rancher.space/k8s/clusters/c-t45qn/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/v1/ws/1s/backingimages' failed: Error during WebSocket handshake: Unexpected response code: 404
w @ index.js:123
```

<img width="702" alt="Screen Shot 2021-02-19 at 12 27 08 PM" src="https://user-images.githubusercontent.com/60111667/108469228-e1e93d80-72ad-11eb-89b9-40fb26f0ec99.png">

**Expected behavior**
There shouldn't be any error on the console.

**Environment:**
 - Longhorn version: Longhorn master - `02/19/2021`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE K8s v1.20.2
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu
 - Number of Longhorn volumes in the cluster: 0

**Comment by khushboo-rancher** [comment]
This could be because of the Backing image feature is not fully merged.

**Comment by yasker** [comment]
Let's check it again once the backing image backend is merged.

**Comment by innobead** [comment]
@khushboo-rancher could you help do the regression again to see if this fixed? thanks.

**Comment by khushboo-rancher** [comment]
This error is not seen with Longhorn-master `03/19/2021`, good to close this.

Validation - **Pass**
