### ISSUE TITLE
[BUG] Node Unschedulable do not have storage

### ISSUE THREAD

**Issue by wenerme** [longhorn/longhorn#2269]
**Describe the bug**

Third row allocated is __-40G__

![image](https://user-images.githubusercontent.com/1777211/108896509-fcc20600-764f-11eb-90c8-ed6ec795fb63.png)

The node is been __replaced__ before(using same node name, but redeployed k3s), then upgrade longhorn from 1.0.2 to 1.1.0

**To Reproduce**

**Expected behavior**
Correct node storage

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version:
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster: 2
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version: alpinelinux 3.13
   - CPU per node: 2,4,8
   - Memory per node: 2,16,32
   - Disk type(e.g. SSD/NVMe): SSD - Virtual
   - Network bandwidth between the nodes: 50M, 1GbE, 1GbE
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): libvirtd
 - Number of Longhorn volumes in the cluster: 1

**Additional context**

**Comment by shuo-wu** [comment]
Is the disk of the replaced node the same as that of the removed node? If NO, you can try to delete the disk and recreate it.

**Comment by wenerme** [comment]
@shuo-wu Recreated before, seems the dir not exists, changed to /var/lib/longhorn, now works, thanks
