### ISSUE TITLE
[FEATURE] Changing the size of a partition on the host OS does not get reflected in Longhorn.

### ISSUE THREAD

**Issue by strigona-worksight** [longhorn/longhorn#2274]
**Is your feature request related to a problem? Please describe.**
Changing the size of a partition on the host OS does not get reflected in Longhorn.

**Describe the solution you'd like**
Monitor the filesystem for a change in size and update metadata accordingly.

**Describe alternatives you've considered**
In hindsight, allocating the additional space as a new partition and adding that disk in manually would have been a workaround.

**Additional context**
In my specific case, ubuntu did not allocate the entire disk by default (roughly 200GB out of a 1TB drive) and Longhorn was upset that it was running out of space. I expanded the partition and was unable to get Longhorn to acknowledge the additional space.

My current work-in-progress work around is to evict all replicas from the disk that needs to "grow", then I'll delete the disk and re-add it.

**Comment by joshimoo** [comment]
@shuo-wu is this something we already monitor?

**Comment by strigona-worksight** [comment]
I poked around the code base before posting and I only saw these values being referenced when creating new disks - either the default disk or a new one:
https://github.com/longhorn/longhorn-manager/blob/7babd5de9189aef792f8c13f4d92274a3944ceed/util/util.go#L368
https://github.com/longhorn/longhorn-manager/blob/7babd5de9189aef792f8c13f4d92274a3944ceed/types/types.go#L428
https://github.com/longhorn/longhorn-manager/blob/7babd5de9189aef792f8c13f4d92274a3944ceed/types/types.go#L513

Now, I certainly could have missed something, but I hope that at least helps a little bit.

**Comment by joshimoo** [comment]
@strigona-worksight this also gets called here indirectly.
https://github.com/longhorn/longhorn-manager/blob/7babd5de9189aef792f8c13f4d92274a3944ceed/controller/node_controller.go#L619

Then gets read here to update the disk status, from a cursory look this looks like it should update the size.
https://github.com/longhorn/longhorn-manager/blob/7babd5de9189aef792f8c13f4d92274a3944ceed/controller/node_controller.go#L704-L707

**Comment by strigona-worksight** [comment]
Ok, after further digging, the issue is purely me not fully understanding LVM. I had increased the size of the volume, but not the file system. As soon as I properly resized the file system Longhorn immediately acknowledged the change.

Sorry for any confusion.
