### ISSUE TITLE
[BUG] Longhorn UI Node dashboard - denominator in allocated column is double actual

### ISSUE THREAD

**Issue by satwell** [longhorn/longhorn#2275]
**Describe the bug**
In the longhorn-ui node dashboard, the denominator values reported in the "Allocated" column are twice the actual values.  The numerator is correct, and the "Used" and "Size" columns appear to be correct.  See example screenshot below.  These nodes both have 30G disks, but the Allocated column is reporting that it can go up to 39.85Gi (twice the "Size" column).

<img width="929" alt="Screen Shot 2021-02-25 at 9 40 46 PM" src="https://user-images.githubusercontent.com/15184483/109260941-edf46400-77b3-11eb-8558-dc5431f9ca1d.png">

**To Reproduce**
1. Go to Longhorn UI
2. Click on Node
3. Observe that Allocated column is incorrect

**Expected behavior**
The denominator for allocated should match the size column

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.20.4+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version:  Debian Buster
   - CPU per node:  varies
   - Memory per node:  2-4G
   - Disk type(e.g. SSD/NVMe):  varies
   - Network bandwidth between the nodes:  1G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):  Bare metal
 - Number of Longhorn volumes in the cluster: 5

**Comment by shuo-wu** [comment]
Due to [the setting `Storage Over Provisioning Percentage`](https://longhorn.io/docs/1.1.0/references/settings/#storage-over-provisioning-percentage), the allocatable space is greater than `Size`, which is the actual available size of the node. You can check [this doc](https://longhorn.io/docs/1.1.0/volumes-and-nodes/node-space-usage/) for more details.
