### ISSUE TITLE
[BUG] rpc error: code = InvalidArgument

### ISSUE THREAD

**Issue by ambis** [longhorn/longhorn#2276]
**Describe the bug**
I have a k3s `v1.20.4+k3s1` cluster running three Hetzner Cloud VPS nodes (cx41 (Intel) and cpx41 (EPYC) tested) running Debian-10 and Longhorn 1.1.0.

Not running any production workloads yet. I experienced this issue before, and decided to recrate the whole cluster from scratch (new vps).

After about a day running anything using volumes, I end up having this error randomly:

```
Type     Reason        Age                 From                Message
----     ------        ----                ----                -------
Warning  NodeNotReady  56m                 node-controller     Node is not ready
Warning  FailedMount   54m (x8 over 55m)   kubelet, master-12  MountVolume.SetUp failed for volume "pvc-ace9952c-3c2e-44b7-a75f-515dd83d8871" : rpc error: code = InvalidArgument desc = Volume pvc-ace9952c-3c2e-44b7-a75f-515dd83d8871 hasn't been attached yet
Warning  FailedMount   54m                 kubelet, master-12  Unable to attach or mount volumes: unmounted volumes=[storage], unattached volumes=[sc-datasources-volume sc-dashboard-volume sc-dashboard-provider storage grafana-token-ttvnq
config[]: timed out waiting for the condition
Normal   Killing       54m                 kubelet, master-12  Stopping container grafana-sc-dashboard
Normal   Killing       54m                 kubelet, master-12  Stopping container grafana
Warning  FailedMount   49m (x3 over 53m)   kubelet, master-12  MountVolume.SetUp failed for volume "pvc-ace9952c-3c2e-44b7-a75f-515dd83d8871" : applyFSGroup failed for vol pvc-ace9952c-3c2e-44b7-a75f-515dd83d8871: readdirent: input/output
error
Warning  FailedMount   49s (x24 over 47m)  kubelet, master-12  MountVolume.WaitForAttach failed for volume "pvc-ace9952c-3c2e-44b7-a75f-515dd83d8871" : volume pvc-ace9952c-3c2e-44b7-a75f-515dd83d8871 has GET error for volume attachment cs
i-64aae4b59d37ec53ff3b86cc7eb85cacea37235c55043e4084922e22699e1934: volumeattachments.storage.k8s.io "csi-64aae4b59d37ec53ff3b86cc7eb85cacea37235c55043e4084922e22699e1934" is forbidden: User "system:node:master-12" cannot get resource "volu
meattachments" in API group "storage.k8s.io" at the cluster scope: no relationship found between node 'master-12' and this object
```
The last error log `...no relationship found between node...` apperas minutes after the pod has been stuck in Terminating state.

This exact thing happens to any pod using Longhorn volumes at random times. I'm running Longhorn out-of-the-box without any modifications.

I first thought this was a k3s bug (https://github.com/k3s-io/k3s/issues/2966), but it seems it is probably LH problem.

**To Reproduce**
Create Hetzner Debian-10 VPS, run `v1.20.4+k3s1`, install Longhorn 1.1.0

**Expected behavior**
Volumes should just stay up and not end up in stuck Terminating status with above messages.

**Log**
```
 time="2021-02-26T10:03:50Z" level=info msg="Deleted pod grafana-0 so that Kubernetes will handle remounting volume pvc-ace9952c-3c2e-44b7-a75f-515dd83d8871" controller=longhorn-kubernetes-pod node=master-12
 time="2021-02-26T10:03:50Z" level=info msg="Deleted pod mariadb-galera-1 so that Kubernetes will handle remounting volume pvc-2b3b7767-4f0b-4e93-a13f-88ace1797a7a" controller=longhorn-kubernetes-pod node=master-12
 time="2021-02-26T10:04:20Z" level=info msg="Deleted pod mariadb-galera-1 so that Kubernetes will handle remounting volume pvc-2b3b7767-4f0b-4e93-a13f-88ace1797a7a" controller=longhorn-kubernetes-pod node=master-12
 time="2021-02-26T10:04:20Z" level=info msg="Deleted pod grafana-0 so that Kubernetes will handle remounting volume pvc-ace9952c-3c2e-44b7-a75f-515dd83d8871" controller=longhorn-kubernetes-pod node=master-12
```

Support bundle:
[longhorn-support-bundle_4808c386-56c9-4f58-b5a3-fae834d1f55e_2021-02-26T10-14-50Z.zip](https://github.com/longhorn/longhorn/files/6048899/longhorn-support-bundle_4808c386-56c9-4f58-b5a3-fae834d1f55e_2021-02-26T10-14-50Z.zip)

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.20.4+k3s1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 0
 - Node config
   - OS type and version: Latest Debian-10 with nothing to update
   - CPU per node: Both 4 and 8 tested
   - Memory per node: 16Gb
   - Disk type(e.g. SSD/NVMe): Local NVMe
   - Network bandwidth between the nodes: Can't say for sure, Hetzner VPS Private network in same DC
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Hetzner Cloud VPS (Baremetal)
 - Number of Longhorn volumes in the cluster: 8

**Comment by bdsoha** [comment]
Same issue here, however I'm running `v1.19.7+k3s1`.

**Comment by joshimoo** [comment]
There is definitely something wrong with your kubernetes cluster.
The below error indicates that kubelet on the node is unable to evaluate the volume attachment status.
Try fixing that and then reporting back if you are still having this issue.

```
volumeattachments.storage.k8s.io "csi-64aae4b59d37ec53ff3b86cc7eb85cacea37235c55043e4084922e22699e1934" is forbidden: User "system:node:master-12" cannot get resource "volu
meattachments" in API group "storage.k8s.io" at the cluster scope: no relationship found between node 'master-12' and this object
```

**Comment by ambis** [comment]
I have observed myself that it takes a some time for that "no relationship" error to appear. If I interpret the log messages and their "timestamps" correctly, there is about 6 minutes gap before the "no relationship" error appears and that coincides well with my own observation. 

It is difficult to see that it would be the cause for this? Maybe that error is generated after the VolumeAttachment is already "broken"? (Sorry I don't know the internals of CSI.)

**Comment by joshimoo** [comment]
@ambis 
```
Warning  FailedMount   49s (x24 over 47m)  kubelet, master-12  MountVolume.WaitForAttach failed for volume "pvc-ace9952c-3c2e-44b7-a75f-515dd83d8871" : volume pvc-ace9952c-3c2e-44b7-a75f-515dd83d8871 has GET error for volume attachment cs
i-64aae4b59d37ec53ff3b86cc7eb85cacea37235c55043e4084922e22699e1934: volumeattachments.storage.k8s.io "csi-64aae4b59d37ec53ff3b86cc7eb85cacea37235c55043e4084922e22699e1934" is forbidden: User "system:node:master-12" cannot get resource "volu
meattachments" in API group "storage.k8s.io" at the cluster scope: no relationship found between node 'master-12' and this object```
Is a permission error that kubelet cannot access that resource group on the api server.

**Comment by shuo-wu** [comment]
If you still have any questions after fixing your cluster, feel free to reopen it.
