### ISSUE TITLE
[Question] How to restore a backup after I use backup-to-file and get .qcow2/.raw file

### ISSUE THREAD

**Issue by LuizBuffa25** [longhorn/longhorn#2277]
**Question**
How I restore a volume after I use [backup-to-file.yaml](https://github.com/longhorn/longhorn/blob/master/examples/restore_to_file.yaml.template) and get mybackup.qcow2 or mybackup.raw, must be **without** using UI? What I need is to know how I restore a volume backup and make it available.
Thanks!

* Using S3 to store backups.

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version: 1.20.

**Additional context**

**Comment by joshimoo** [comment]
Check the documentation: https://longhorn.io/docs/1.1.0/advanced-resources/data-recovery/recover-without-system/

Any reason you don't use the normal backup & restore with longhorn installed?
https://longhorn.io/docs/1.1.0/snapshots-and-backups/backup-and-restore/create-a-backup/

Or the CSI integration to create longhorn backups?
https://longhorn.io/docs/1.1.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/

**Comment by LuizBuffa25** [comment]
> Check the documentation: https://longhorn.io/docs/1.1.0/advanced-resources/data-recovery/recover-without-system/
> 
> Any reason you don't use the normal backup & restore with longhorn installed?
> https://longhorn.io/docs/1.1.0/snapshots-and-backups/backup-and-restore/create-a-backup/
> 
> Or the CSI integration to create longhorn backups?
> https://longhorn.io/docs/1.1.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/

Thanks for answer,
I need to perform a backup and restore 100% without UI. I know the CLI is in development, until it releases I needed some work around, I will study your links.

You may close this issue.
