### ISSUE TITLE
[BUG] Show indication on the UI that the automatic upgrade is in progress

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2281]
**Describe the bug**
This is related to https://github.com/longhorn/longhorn/issues/2152, while the automatic upgrade is in the progress, UI should show some message that the automatic upgrade is in progress.

**To Reproduce**
1. Deploy Longhorn v1.1.0 on a K8s cluster.
2. Create some volumes and attach them to pods.
3. Upgrade Longhorn to Master and enable automatic upgrade engine by providing value of `Concurrent Automatic Engine Upgrade Per Node Limit` to any number greater than 0.

**Expected behavior**
It would be nice to show a message at the top of the Longhorn UI so that users can get the attention and avoid doing any operations during upgrade.

**Environment:**
 - Longhorn version: Longhorn - master 

**Additional context**
Currently, users can see the upgrade icon next to volume or check the volume details page to see the engine image version.

**Comment by PhanLe1010** [comment]
We can show upgrade in progress for each volumes by comparing `curretnImage` and `engineImage` in the volume resource returned by API `v1/volumes`

Though, we cannot determine whether auto-upgrade is happening or it is a manual upgrade since auto-upgrade is basically same as manual upgrade after it is trigged

**Comment by khushboo-rancher** [comment]
Sounds good to me. Just to confirm does it mean if the `concurrent-automatic-engine-upgrade-per-node-limit` setting is greater than `0` and there is at least 1 volume (except DR volume/degraded volume) which is still with old `engineImage`, we will show the message?

**Comment by khushboo-rancher** [comment]
Waiting for https://github.com/longhorn/longhorn/issues/2315

**Comment by khushboo-rancher** [comment]
The upgrade symbol looks good but there is a problem with the number of upgrade happening with the setting `Concurrent Automatic Engine Upgrade Per Node Limit`. Logged https://github.com/longhorn/longhorn/issues/2328 to track.
Once https://github.com/longhorn/longhorn/issues/2328 is fixed, this should be good to close.

**Comment by khushboo-rancher** [comment]
Closing this in favor of https://github.com/longhorn/longhorn/issues/2328
