### ISSUE TITLE
[FEATURE] Longhorn should support multi-network K8s clusters (storage network)

### ISSUE THREAD

**Issue by janeczku** [longhorn/longhorn#2285]
**Is your feature request related to a problem? Please describe.**

A typical bare-metal server/network architecture involves servers being attached to multiple networks, including a dedicated storage fabric that provides accelerated throughput and IO separation from the data plane.

Longhorn does not support segregate networks and uses the default CNI network for all the storage traffic. That makes it impossible to guarantee network resources available for storage operations because the same network is shared with all in-cluster application traffic.

**Describe the solution you'd like**

![Multi-Network-Storage](https://user-images.githubusercontent.com/3813921/109638614-80975900-7b4e-11eb-9c2e-71a874910e4a.png)

The canonical approach to provide multi-network capabilities in a K8s cluster is using a CNI multiplexer such as Multus which provides the means to attach pods to different underlay networks.

Longhorn should have an integration with Multus.
That may be implemented by exposing a global setting allowing the admin to specify the Multus network that should be used for any storage-related traffic (e.g. engine -> replica). Longhorn would then configure the pods with the Multus specific annotations, e.g. `k8s.v1.cni.cncf.io/networks: storage-net`.

The setup and configuration of the Multus network (e.g. creation of `NetworkAttachmentDefinition`) would be out of the scope of Longhorn.

**Describe alternatives you've considered**
N/A

**Comment by yasker** [comment]
Considering moving this back to v1.2.0.

**Comment by yasker** [comment]
Move out to v1.3.0.

**Comment by innobead** [comment]
cc @jenting

**Comment by jenting** [comment]
Interested.

As I know, Harvester uses Multus, it'd benefit the Harvester project.

Also, make sure the Longhorn engine <-> replica network throughput would not be affected by other applications.

**Comment by innobead** [comment]
Doing the evaluation in 1.2.0 to see if we could come out with experimental support in 1.2.0. Otherwise, 1.3.0 instead.

**Comment by innobead** [comment]
@jenting as we discussed, please sum up where we are and what original ideas you plan to do for the evaluation.

**Comment by jenting** [comment]
For the longhorn-engine replica part, the data server and sync-agent server are the data plane.
Having the setting allows the user to specify which network interface is the data plane.
At the longhorn engine, it gets the network interface IPs from the Pod and creates the data and sync-agent server with that interface IP address. (Need a way to report error if the network interface not found)
Change the setting need to restart the longhorn-engine Pods to recreate the data and sync-agent server (need to consider should the volume need to be detached or not)

**Comment by innobead** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Main-Board-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/2285?planning-poker) with ZenHub @jenting @PhanLe1010 @shuo-wu @joshimoo

**Comment by c3y1huang** [comment]
> For the longhorn-engine replica part, the data server and sync-agent server are the data plane. Having the setting allows the user to specify which network interface is the data plane. At the longhorn engine, it gets the network interface IPs from the Pod and creates the data and sync-agent server with that interface IP address. (Need a way to report error if the network interface not found) Change the setting need to restart the longhorn-engine Pods to recreate the data and sync-agent server (need to consider should the volume need to be detached or not)

The components that get affected are the replica process, engine process, and iscsiadm. Currently, the challenge is how to overcome that Multus CNI is not visible on the host network to be used by iscsiadm.

**Comment by innobead** [comment]
> > For the longhorn-engine replica part, the data server and sync-agent server are the data plane. Having the setting allows the user to specify which network interface is the data plane. At the longhorn engine, it gets the network interface IPs from the Pod and creates the data and sync-agent server with that interface IP address. (Need a way to report error if the network interface not found) Change the setting need to restart the longhorn-engine Pods to recreate the data and sync-agent server (need to consider should the volume need to be detached or not)
> 
> The components that get affected are the replica process, engine process, and iscsiadm. Currently, the challenge is how to overcome that Multus CNI is not visible on the host network to be used by iscsiadm.

@joshimoo @keithalucas any concerns for what @c3y1huang described? I don't think we need to deal with the communication between iscsi client and server (longhorn engine) over the storage network, but what we do care about are actually below:
- data traffic between engine and replicas
- data traffic between replicas

**Comment by shuo-wu** [comment]
> The iscsid to tgt communication is local to that node and shouldn't be transported over the network at all

Sorry I didn't follow this statement. If I understand correctly, the client and the server are always on the same node but in different network namespaces. And the connection is always a TCP connection. If we need to switch to using the storage network interface totally depends on how we consider the storage network. Is the storage network for data transmission only? Or it's for the whole storage **system**. There is no extra overhead for the switching.

After checking the LEP, I would consider that the network is for the whole storage system. Then I prefer to use the storage network IP only in the engine (including launching tgt target). Otherwise, which IP we should use when invoking the APIs in the engine process would be a confusing part.

**Comment by c3y1huang** [comment]
Moved this backlog to work on the dependent issue https://github.com/longhorn/longhorn/issues/2821.

**Comment by c3y1huang** [comment]
Backlog this for now.
https://github.com/longhorn/longhorn/issues/3546#issuecomment-1063670512

**Comment by innobead** [comment]
cc @smallteeths

**Comment by yangchiu** [comment]
verified passed on v1.3.0-rc2 by following the [manual test plan](https://github.com/longhorn/longhorn-tests/blob/9f19673653dd158ddcae24cb8563b47d4a6c69d0/docs/content/manual/release-specific/v1.3.0/test-storage-network.md).

created eth0 (10.0.1.0/24) and eth1 (10.0.2.0/24) for each instance, and let pods communicated with each other on eth1 using multus.
remember to stop `source/destination check` else the volume replicas would keep fail.
