### ISSUE TITLE
[FEATURE] Enhance the backing image feature

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2295]
**Is your feature request related to a problem? Please describe.**
Right now when a backing image is requested, Longhorn will fetch the backing image file from the remote for each node. In other words, if a backing image is required for N nodes, each node will take bandwidth to pull the data and total bandwidth consumed is N * backing image size.

To save the bandwidth as well as make some fancy features possible, we need to refactor the backing image feature. 

**Describe the solution you'd like**
One possible solution is that Longhorn would launch a backing image manager for each node/disk. So that one backing image manager is responsible for pull the backing image from the remote first, then other backing image managers can fetching the data from the 1st backing image manager.

**Describe alternatives you've considered**
N/A

**Comment by shuo-wu** [comment]
Will add drone and unit tests during or after the review.

**Comment by khushboo-rancher** [comment]
Validated with Longhorn- master v1.1.1-rc1

Validation - **Pass**

The below test cases have been validated.
1. Backing image with RWO
2. Backing image with RWX
3. Deletion of backing image.
4. Creation of volume with backing image using storage class.
5. Create backup of a volume with backing image
6. Restore backup of a volume with backing image
7. DR volume with a volume with backing image
8. Expansion of volume with backing image.
8. Evict disk with backing image
9. Backing image feature on PSP enabled cluster

Thank you @shuo-wu for helping me with upgrade scenarios testing, this is can be closed once @shuo-wu confirms the upgrade scenarios.

**Comment by shuo-wu** [comment]
The upgrade tests are passed:
1. system upgrade with compatible backing image manager
2. system upgrade with incompatible backing image manager
