### ISSUE TITLE
[Question] How to change volume mount location from /dev/longhorn/<vol name>

### ISSUE THREAD

**Issue by LuizBuffa25** [longhorn/longhorn#2298]
**Question**
I read the documentation that says how to [customize defaults settings](https://longhorn.io/docs/1.1.0/advanced-resources/deploy/customizing-default-settings/), notice that is possible to change (default-data-path: /var/lib/longhorn-example/) but not mounting point (/dev/longhorn/<vol name>

There is a way to change that? (not using UI).

Other questions, I notice that when I write data on some volume with only 1 replica, only /var/lib/longhorn/replicas/<vol pv name - hash> is growing in size, which means that 1 replica is the only source that store my data?
**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version: 1.20
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**

**Comment by joshimoo** [comment]
The device file location is not configurable `/dev/longhorn/<volume_name>` is not the mount point, it's a block device node.
The /dev/longhorn/<volume_name> will be dynamically added an removed when you attach/detach a volume from a node.

When configuring a volume with only 1 replica, then you will only have 1 replica.
So if you lose that disk the data is lost. 

You can setup recurring backups, to store a backup of the volume data outside of the replica.
https://longhorn.io/docs/1.1.0/snapshots-and-backups/scheduling-backups-and-snapshots/

**Comment by LuizBuffa25** [comment]
Thanks, you may close this issue!
