### ISSUE TITLE
Longhorn 1.1.0 volume is detached for test on K3S 1.20.4.

### ISSUE THREAD

**Issue by ddfiberglass** [longhorn/longhorn#2299]
**Describe the bug**
I have 3 nodes, one server from Aliyun Hangzhou, China [**as Master**, 2cpu-4G ], one server from Aliyun, US [ agent, 1cpu-2G ], one server from Baidu Guangzhou, China [bce, 2cpu-2G].

I have install longhorn 1.1.0 on K3S: 1.20.4-k3s1, the linux system is Ubuntu 20.04. 

I use the test volume: https://raw.githubusercontent.com/longhorn/longhorn/v1.1.0/examples/pod_with_pvc.yaml.

but it the pod didnot work out. It says:

Events:
  Type     Reason              Age                   From                     Message
  ----     ------              ----                  ----                     -------
  Warning  FailedScheduling    7m36s                 default-scheduler        0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling    7m36s                 default-scheduler        0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled           7m30s                 default-scheduler        Successfully assigned default/volume-test to bce
  Warning  FailedMount         3m9s                  kubelet                  Unable to attach or mount volumes: unmounted volumes=[volv], unattached volumes=[default-token-f5rlt volv]: timed out waiting for the condition
  Warning  FailedAttachVolume  77s (x11 over 7m30s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-2844abb9-a341-42c9-9d4f-4b855d686044" : CSINode bce does not contain driver driver.longhorn.io
  Warning  FailedMount         53s (x2 over 5m27s)   kubelet                  Unable to attach or mount volumes: unmounted volumes=[volv], unattached volumes=[volv default-token-f5rlt]: timed out waiting for the condition

The volume in longhorn UI shows detached. Even I attache it to the node. the pod is still not up and running.

**To Reproduce**
1. curl -sfL http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn INSTALL_K3S_VERSION=v1.20.4+k3s1 sh -s server  --advertise-address=47.98.1**.*** --node-ip=47.98.1**.***  --flannel-backend=wireguard  --no-deploy traefik 

But it won't work. And it works as follow:

2. curl -sfL http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -s server --advertise-address="PUBLIC IP OF SERVER"

3. I changed some settings, no traefik, 
vim /etc/systemd/system/k3s.service

ExecStart=/usr/local/bin/k3s \
    server \
        '--advertise-address=47.98.1**.***' \
        '--node-ip=47.98.1**.***' \
        '--flannel-backend=wireguard' \
        '--no-deploy' \
        'traefik' \

and I delete the  daemonset and service of traefik.

kubectl delete daemonset.apps/svclb-traefik -n kube-system
kubectl delete   service/traefik -n kube-system

something else I installed are 
helm install ingress bitnami/nginx-ingress-controller
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.1.1/cert-manager.crds.yaml

kubectl annotate nodes server flannel.alpha.coreos.com/public-ip-overwrite=47.98.1**.***
kubectl annotate   nodes agent flannel.alpha.coreos.com/public-ip-overwrite=47.251.*.***
kubectl annotate nodes bce   flannel.alpha.coreos.com/public-ip-overwrite=182.61.**.**

**Comment by PhanLe1010** [comment]
Seems that some Longhorn components are missing on node `bce`: 

> Warning FailedAttachVolume 77s (x11 over 7m30s) attachdetach-controller AttachVolume.Attach failed for volume "pvc-2844abb9-a341-42c9-9d4f-4b855d686044" : CSINode bce does not contain driver driver.longhorn.io

A support bundle would give us more data. Can you use the link on the bottom of the Longhorn UI page to generate a support bundle and send it to `longhorn-support-bundle@rancher.com`?

**Comment by ddfiberglass** [comment]
I have reinstalled everything from a new start. And it is working now. Thanks, Everyone.
