### ISSUE TITLE
[BUG] e2e longhorn upgrade fails

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2300]
**Describe the bug**
Running e2e `test_upgrade` fails.

**To Reproduce**
Run e2e `test_upgrade`.

**Expected behavior**
Should pass.

**Log**
`n/a`

**Environment:**
`n/a`

**Additional context**
`none`

**Comment by meldafrawi** [comment]
Fixed: https://ci.longhorn.io/job/public/job/ubuntu/job/amd64/job/longhorn-upgrade-tests-ubuntu-amd64/308/
