### ISSUE TITLE
[Question] yaml equivalent of docs

### ISSUE THREAD

**Issue by ukd1** [longhorn/longhorn#2302]
**Question**
Having good docs and a web interface is nice, but I want to do as much as I can with yaml and config. I've not found a way to set the backup target in [the docs](https://longhorn.io/docs/0.8.1/snapshots-and-backups/backup-and-restore/set-backup-target/), but I'd really like to.

Questions:
- how to set backup target in yaml
- how to select the secret to use in yaml

Thanks!

**Comment by joshimoo** [comment]
`kubectl get settings.longhorn.io backup-target -o yaml -n longhorn-system`
```yaml
apiVersion: longhorn.io/v1beta1
kind: Setting
metadata:
  creationTimestamp: "2021-03-05T20:39:06Z"
  generation: 1
  managedFields:
  - apiVersion: longhorn.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:value: {}
    manager: longhorn-manager
    operation: Update
    time: "2021-03-05T20:39:06Z"
  name: backup-target
  namespace: longhorn-system
  resourceVersion: "311580"
  selfLink: /apis/longhorn.io/v1beta1/namespaces/longhorn-system/settings/backup-target
  uid: 182af078-6500-451d-bebd-b5d94727eafd
value: ""
```

`kubectl get settings.longhorn.io backup-target-credential-secret -o yaml -n longhorn-system`
```yaml
apiVersion: longhorn.io/v1beta1
kind: Setting
metadata:
  creationTimestamp: "2021-03-05T20:39:06Z"
  generation: 1
  managedFields:
  - apiVersion: longhorn.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:value: {}
    manager: longhorn-manager
    operation: Update
    time: "2021-03-05T20:39:06Z"
  name: backup-target-credential-secret
  namespace: longhorn-system
  resourceVersion: "311582"
  selfLink: /apis/longhorn.io/v1beta1/namespaces/longhorn-system/settings/backup-target-credential-secret
  uid: c9c282ad-4f51-4972-81ef-f8874f3c0ceb
value: ""
```

I stripped them down to the bare minimum, that should work for `kubectl apply -f`
```
apiVersion: longhorn.io/v1beta1
kind: Setting
metadata:
  name: backup-target
  namespace: longhorn-system
value: "" # backup target here
----
apiVersion: longhorn.io/v1beta1
kind: Setting
metadata:
  name: backup-target-credential-secret
  namespace: longhorn-system
value: "" # backup secret name here
```

@ukd1 You can give this a try and report back, I didn't test this but should work :)

**Comment by ukd1** [comment]
@joshimoo magic, thanks. Is this something that could be put in the docs?

**Comment by PhanLe1010** [comment]
Btw, if you want to build automation script to control Longhorn, we have some docs at https://longhorn.io/docs/1.1.0/references/longhorn-client-python/

**Comment by joshimoo** [comment]
@ukd1 documentation pull request are very much welcome https://github.com/longhorn/website#contributing-to-docs

The reason we don't publish things like this is that it bypasses the backends validation layer, since we currently don't run a kubernetes validation webhook for the crds and instead expect the settings to be set via the backend api.
