### ISSUE TITLE
[BUG] UI - 'Enable scheduling' option appears for 'down' node on the Longhorn UI

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2308]
**Describe the bug**
The menu option `Enable Scheduling` becomes available once the node goes down on the Longhorn UI.

**To Reproduce**
1. Deploy Longhorn - master on a cluster of 4 nodes (1 control plane/etcd, 3 worker)
2. Add taint to a node.
3. That node becomes `down` on the Longhorn UI.
4. Check the menu available for the node, there is an option `Enable Scheduling` starts appearing for it which doesn't work.

**Expected behavior**
`Enable Scheduling` option is not required for the down node.

<img width="1458" alt="Screen Shot 2021-03-08 at 2 13 58 PM" src="https://user-images.githubusercontent.com/60111667/110306116-76c89680-8023-11eb-9a77-7e90c2d4b449.png">

<img width="1464" alt="Screen Shot 2021-03-08 at 2 14 52 PM" src="https://user-images.githubusercontent.com/60111667/110306282-ab3c5280-8023-11eb-9533-a633035c55df.png">

**Environment:**
 - Longhorn version: Longhorn master - `03/08/2021`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 2
   - Memory per node: 4 GB

**Comment by innobead** [comment]
@khushboo-rancher you can close it if no extra issues. Thanks.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master - `03/29/2021`

Validation - **Pass**
