### ISSUE TITLE
[BUG] Timeout in listing backup for NFS server on RHEL 8.2

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2310]
**Describe the bug**
Backup page doesn't list the backups for backup store configured as NFS server.

**To Reproduce**
1. Deploy Longhorn v1.1.0 using kubectl command.
2. Configure backup store as NFS `nfs://nfs-server:/opt/backupstore`
3. Take backup
4. Backups are getting created on the server but Longhorn UI is unable to list the backups.

**Expected behavior**
Longhorn UI should list the backups

**Log**
```
time="2021-03-08T12:21:13Z" level=warning msg="HTTP handling error error get backup volume 'pvc-b5e8b93e-c5a5-4b9c-8324-fcef55734f84': error getting backup volume: Timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn [backup ls --volume pvc-b5e8b93e-c5a5-4b9c-8324-fcef55734f84 --volume-only nfs://52.157.199.137:/opt/backupstore], output , stderr, , error <nil>"
time="2021-03-08T12:21:13Z" level=error msg="Error in request: error get backup volume 'pvc-b5e8b93e-c5a5-4b9c-8324-fcef55734f84': error getting backup volume: Timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn [backup ls --volume pvc-b5e8b93e-c5a5-4b9c-8324-fcef55734f84 --volume-only nfs://52.157.199.137:/opt/backupstore], output , stderr, , error <nil>"
```
[longhorn-support-bundle_3049c0b8-c641-442e-ad2e-dabf64cc0263_2021-03-08T12-47-17Z.zip](https://github.com/longhorn/longhorn/files/6101815/longhorn-support-bundle_3049c0b8-c641-442e-ad2e-dabf64cc0263_2021-03-08T12-47-17Z.zip)

**From NFS server**
```
[sfadmin@sf-nfs-vm-adeep ~]$ sudo ls /opt/backupstore/backupstore/volumes/41/
8f
[sfadmin@sf-nfs-vm-adeep ~]$ sudo ls /opt/backupstore/backupstore/volumes/
41  8f  c1
[sfadmin@sf-nfs-vm-adeep ~]$ sudo ls /opt/backupstore/backupstore/volumes/41
8f
[sfadmin@sf-nfs-vm-adeep ~]$ sudo ls /opt/backupstore/backupstore/volumes/41/8f
pvc-b12d2081-e558-4ae7-9370-726886e05756
[sfadmin@sf-nfs-vm-adeep ~]$ sudo ls /opt/backupstore/backupstore/volumes/8f
80
[sfadmin@sf-nfs-vm-adeep ~]$ sudo ls /opt/backupstore/backupstore/volumes/8f/80
pvc-37d7816b-494a-4cc5-a6a1-b88fb10b62a8
[sfadmin@sf-nfs-vm-adeep ~]$ sudo ls /opt/backupstore/backupstore/volumes/c1
97
[sfadmin@sf-nfs-vm-adeep ~]$ sudo ls /opt/backupstore/backupstore/volumes/c1/97
pvc-b5e8b93e-c5a5-4b9c-8324-fcef55734f84
```

**Environment:**
 - Longhorn version: v1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version: RHEL 8.2
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Additional context**
In the logs, there are `permission denied` logs which user solved by below commands.
```
mkdir /var/lib/longhorn-backupstore-mounts/
mkdir /var/lib/longhorn-backupstore-mounts/52_157_199_137/opt/backupstore/backupstore: permission denied\"\n, error exit status 1"
chmod -R 777 /var/lib/longhorn-backupstore-mounts
chown -R nobody: /var/lib/longhorn-backupstore-mounts
```

**Comment by yasker** [comment]
Linked to the slack thread: https://rancher-users.slack.com/archives/CC2UQM49Y/p1615206503012800

We've seen this in a few different cases.

**Comment by jenting** [comment]
Similar to #1955.

**Comment by khushboo-rancher** [comment]
Closing this in favor of https://github.com/longhorn/longhorn/issues/1955
