### ISSUE TITLE
[UI] Change engine image state from `ready` to `deployed`

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2311]
**Is your feature request related to a problem? Please describe.**
Since we changed the logic for handling the readiness of engine image ([see more details](https://github.com/longhorn/longhorn/issues/2081#issuecomment-780964823)), UI needs to change:
1. Display blue color for `status` when the state if the engine image is `deployed` (I guess by adding the class `.deployed` to [classes.less](https://github.com/longhorn/longhorn-ui/blob/6a29524d2d066ee2e799b17f0c4e1d5d95ddbf3f/src/assets/styles/classes.less#L10)?)
    <img width="1042" alt="Screen Shot 2021-03-08 at 11 09 26 AM" src="https://user-images.githubusercontent.com/22139961/110369195-e710f100-7ffe-11eb-8d29-2bd70bc05527.png">
1. Now that we don't need the engine image to be fully deployed on all nodes, removed the check for engine image in:
   * Remove `engineImage.state === 'ready'` in https://github.com/longhorn/longhorn-ui/blob/6a29524d2d066ee2e799b17f0c4e1d5d95ddbf3f/src/routes/volume/EngineUpgrade.js#L57
   * Remove `engineImage.state === 'ready'` in https://github.com/longhorn/longhorn-ui/blob/6a29524d2d066ee2e799b17f0c4e1d5d95ddbf3f/src/routes/volume/VolumeActions.js#L165
1. In the engine image detail page, add the `nodeDeploymentMap` which show the deployment status of the engine image on each node. You can get the  `nodeDeploymentMap` info from the API `v1/engineimages`
<img width="809" alt="Screen Shot 2021-03-09 at 10 12 05 PM" src="https://user-images.githubusercontent.com/22139961/110584986-f5f1c380-8124-11eb-94ee-2da452ae5c65.png">

**Comment by yasker** [comment]
Are we showing the engine image readiness on the node?

**Comment by PhanLe1010** [comment]
Yes, we display the engine image readiness when users click on the Readiness field of the node. But everything is plain text (there is no blue highlight in v1.1.0 when engine image readiness is `ready`) so I think we don't need to highlight `deployed` state neither

<img width="1309" alt="Screen Shot 2021-03-08 at 12 00 47 PM" src="https://user-images.githubusercontent.com/22139961/110375154-6bb33d80-8006-11eb-8b80-59dedf364d70.png">


<img width="1057" alt="Screen Shot 2021-03-08 at 12 00 59 PM" src="https://user-images.githubusercontent.com/22139961/110375077-53dbb980-8006-11eb-8466-0b335b30fb2f.png">

**Comment by khushboo-rancher** [comment]
Can we move this to merged column or are we waiting for something?

**Comment by PhanLe1010** [comment]
Moved to merge. Thanks Khushboo

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master `03/12/2021`

Validation - **Pass**

The state of the engine is changed to `deployed` in all the below places.

<img width="1780" alt="Screen Shot 2021-03-12 at 12 05 26 AM" src="https://user-images.githubusercontent.com/60111667/110975647-03f24f00-8386-11eb-8d88-6eb96468c2a6.png">
<img width="1011" alt="Screen Shot 2021-03-12 at 12 06 02 AM" src="https://user-images.githubusercontent.com/60111667/110975660-06ed3f80-8386-11eb-8704-3866889b9d1b.png">
<img width="476" alt="Screen Shot 2021-03-12 at 12 07 18 AM" src="https://user-images.githubusercontent.com/60111667/110975664-081e6c80-8386-11eb-873e-9bc6c8ef0529.png">
