### ISSUE TITLE
[BUG] UI - Upgrade menu option is not enabled on Longhorn UI.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2315]
**Describe the bug**
Upgrade option is not enabled on Longhorn UI on upgrade.

**To Reproduce**
1. Deploy Longhorn v1.1.0 using kubectl command in a cluster of 4 nodes (1 etcd/control plane, 3 worker)
2. Create some volumes and attach them to pods.
3. Upgrade Longhorn to master.
4. Neither live upgrade nor offline upgrade option is not available on the Longhorn UI.

<img width="1772" alt="Screen Shot 2021-03-09 at 11 10 21 PM" src="https://user-images.githubusercontent.com/60111667/110515652-9c8e9200-812e-11eb-975f-27443a991899.png">

**Environment:**
 - Longhorn version: Longhorn - master `03/09/2021`

**Note**
`Concurrent Automatic Engine Upgrade Per Node Limit` is set to 0.

**Comment by PhanLe1010** [comment]
It is because of https://github.com/longhorn/longhorn/issues/2311

**Comment by PhanLe1010** [comment]
We can close this one in favor of https://github.com/longhorn/longhorn/issues/2311
