### ISSUE TITLE
[FEATURE] Support for multiple backup locations

### ISSUE THREAD

**Issue by MrDienns** [longhorn/longhorn#2317]
**Is your feature request related to a problem? Please describe.**
While Longhorn supports replication across servers, it does not support adding multiple backup locations. With some hosts, one S3 compatible endpoint for instance equals one datacenter. In order to support off-site backups for these hosts, being able to configure two (or more) backup locations could tackle this. Perhaps you're simply using multiple hosts for backups.

**Describe the solution you'd like**
I'd like to be able to configure a list of backup locations, and have backups we created at every location. When restoring from a backup, you could potentially choose where you want the backup to be loaded from.

**Describe alternatives you've considered**
I haven't found an alternate solution.

**Additional context**
No additional context.

**Comment by joshimoo** [comment]
Leaving a note here, related #1761

**Comment by joshimoo** [comment]
Currently longhorn only supports a single backup target.
In the future we want to refactor the backup mechanism, to allow for multiple backup targets.
That refactor is not scheduled yet, see #1761.

**Comment by mstrent** [comment]
The backup refactor is out there for 1.2. The Backuptarget CRD is a thing now. Are we able to specify multiple Backuptarget CRDs with different names?

**Comment by mstrent** [comment]
Answering my own question: https://github.com/longhorn/longhorn-manager/blob/dd8e20c76dcd740db4301f3e37cb314e15a01b5e/controller/backup_target_controller.go#L120

**Comment by innobead** [comment]
Let's follow up https://github.com/longhorn/longhorn/issues/5411 instead.
