### ISSUE TITLE
[BUG] Configuration file `/etc/iscsi/initiatorname.iscsi` does not exist iscsi using `longhorn-iscsi-installation.yaml`.

### ISSUE THREAD

**Issue by cclhsu** [longhorn/longhorn#2319]
**Describe the bug**

Configuration file `/etc/iscsi/initiatorname.iscsi` does not exist iscsi using `longhorn-iscsi-installation.yaml`.

After configuration created with following:

```
echo "InitiatorName=$(/sbin/iscsi-iname)" > /etc/iscsi/initiatorname.iscsi
systemctl restart iscsid
```
Pod is able to mount and create successfully.

**To Reproduce**

1. Deploy POD in Centos with following:

```
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn-manager/master/deploy/prerequisite/longhorn-iscsi-installation.yaml
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn-manager/master/examples/simple_pvc.yaml
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn-manager/master/examples/simple_pod.yaml
```

**Expected behavior**

Pod is able to mount and create successfully.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

Encounter following errors

```
# kubectl describe pod
Warning  FailedAttachVolume  4m5s                 attachdetach-controller  AttachVolume.Attach failed for volume "pvc-261ca391-6be3-4137-a9a2-02c8fdfe818d" : attachdetachment timeout for volume pvc-261ca391-6be3-4137-a9a2-02c8fdfe818d
Warning  FailedAttachVolume  3m33s                attachdetach-controller  AttachVolume.Attach failed for volume "pvc-261ca391-6be3-4137-a9a2-02c8fdfe818d" : rpc error: code = Aborted desc = The volume pvc-261ca391-6be3-4137-a9a2-02c8fdfe818d is detaching
Warning  FailedAttachVolume  117s (x7 over 4m4s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-261ca391-6be3-4137-a9a2-02c8fdfe818d" : rpc error: code = Aborted desc = The volume pvc-261ca391-6be3-4137-a9a2-02c8fdfe818d is attaching
```

```
> systemctl status iscsid
● iscsid.service - Open-iSCSI
   Loaded: loaded (/usr/lib/systemd/system/iscsid.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2021-03-10 12:32:59 UTC; 6s ago
     Docs: man:iscsid(8)
           man:iscsiuio(8)
           man:iscsiadm(8)
 Main PID: 15821 (iscsid)
   Status: "Ready to process requests"
    Tasks: 1
   Memory: 1.9M
   CGroup: /system.slice/iscsid.service
           └─15821 /sbin/iscsid -f

Mar 10 12:32:59 centos-worker-0 systemd[1]: Starting Open-iSCSI...
Mar 10 12:32:59 centos-worker-0 iscsid[15821]: iscsid: can't open InitiatorName configuration file /etc/iscsi/initiatorname.iscsi
Mar 10 12:32:59 centos-worker-0 iscsid[15821]: iscsid: Warning: InitiatorName file /etc/iscsi/initiatorname.iscsi does not exist or does not contain a properly formatted InitiatorName. If using software iscsi (iscsi_tcp or ib_iser) or ...
Mar 10 12:32:59 centos-worker-0 iscsid[15821]: Example: InitiatorName=iqn.2001-04.com.redhat:fc6.
Mar 10 12:32:59 centos-worker-0 iscsid[15821]: If using hardware iscsi like qla4xxx this message can be ignored.
Mar 10 12:32:59 centos-worker-0 iscsid[15821]: iscsid: can't open InitiatorAlias configuration file /etc/iscsi/initiatorname.iscsi
Mar 10 12:32:59 centos-worker-0 systemd[1]: Started Open-iSCSI.
Mar 10 12:33:01 centos-worker-0 iscsid[15821]: iscsid: connection1:0 is operational after recovery (1 attempts)
Hint: Some lines were ellipsized, use -l to show in full.
```

```
> iscsiadm -m discovery -t sendtargets -p 10.42.3.7
iscsiadm: Cannot perform discovery. Invalid Initiatorname.
iscsiadm: Could not perform SendTargets discovery: invalid parameter
```

Log for instant-manager-e

```
[pvc-3abd2032-b8f9-4913-856a-50be5dcd93c7-e-072e2d60] time="2021-03-12T10:01:44Z" level=warning msg="FAIL to discover due to Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm -m discovery -t sendtargets -p 10.42.1.8], output , stderr, iscsiadm: Cannot perform discovery. Invalid Initiatorname.\niscsiadm: Could not perform SendTargets discovery: invalid parameter\n, error exit status 7"
[pvc-3abd2032-b8f9-4913-856a-50be5dcd93c7-e-072e2d60] time="2021-03-12T10:01:47Z" level=error msg="Failed to startup frontend: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm -m node -T iqn.2019-10.io.longhorn:pvc-3abd2032-b8f9-4913-856a-50be5dcd93c7 -p 10.42.1.8 --login], output , stderr, iscsiadm: No records found\n, error exit status 21"
2021/03/12 10:01:47 failed to start up frontend: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm -m node -T iqn.2019-10.io.longhorn:pvc-3abd2032-b8f9-4913-856a-50be5dcd93c7 -p 10.42.1.8 --login], output , stderr, iscsiadm: No records found
```

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.10
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version: Centos
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Additional context**

**Comment by innobead** [comment]
@khushboo-rancher I assumed QA verified this before, did you encounter this issue? https://github.com/longhorn/longhorn/issues/1741#issuecomment-781750824

**Comment by khushboo-rancher** [comment]
Validation of this should be covered with https://github.com/longhorn/longhorn/issues/1741, but I'll revalidate this once on Centos and confirm.

**Comment by khushboo-rancher** [comment]
@cclhsu Can you please confirm that you're using https://raw.githubusercontent.com/longhorn/longhorn-manager/master/deploy/prerequisite/longhorn-iscsi-installation.yaml file to deploy iscsi-installer and what's the version of the CentOS you're using?

1. With CentOS 7 the https://raw.githubusercontent.com/longhorn/longhorn-manager/master/deploy/prerequisite/longhorn-iscsi-installation.yaml is working fine and the `Iscsi` is getting properly installed on the nodes. After installing `iscsi`, I'm able to deploy the Longhorn successfully.

2. With CentOS 8, I see a problem. The iscsi installer fails with error `yum makecache: error: argument timer: invalid choice: 'fast' (choose from 'timer'). iscsi install failed error code 1` as `makecache fast` is not supported on CentOS 8. 
@innobead We'll need to modify the yaml file to support CentOS 8.

**Comment by cclhsu** [comment]
> @cclhsu Can you please confirm that you're using https://raw.githubusercontent.com/longhorn/longhorn-manager/master/deploy/prerequisite/longhorn-iscsi-installation.yaml file to deploy iscsi-installer and what's the version of the CentOS you're using?
> 
> 1. With CentOS 7 the https://raw.githubusercontent.com/longhorn/longhorn-manager/master/deploy/prerequisite/longhorn-iscsi-installation.yaml is working fine and the `Iscsi` is getting properly installed on the nodes. After installing `iscsi`, I'm able to deploy the Longhorn successfully.
> 2. With CentOS 8, I see a problem. The iscsi installer fails with error `yum makecache: error: argument timer: invalid choice: 'fast' (choose from 'timer'). iscsi install failed error code 1` as `makecache fast` is not supported on CentOS 8.
>    @innobead We'll need to modify the yaml file to support CentOS 8.

Yes, the issues are addressed in https://github.com/longhorn/longhorn-manager/pull/840

**Comment by khushboo-rancher** [comment]
Verified with https://raw.githubusercontent.com/longhorn/longhorn-manager/master/deploy/prerequisite/longhorn-iscsi-installation.yaml.

The iscsi is getting installed on RHEL7 and RHEL8 and installation with other OS is validated with https://github.com/longhorn/longhorn/issues/1741

**Comment by mantissahz** [comment]
Note: https://cloud-native.slack.com/archives/CNVPEL9U3/p1657732662397739
