### ISSUE TITLE
[BUG] Slack Channel is closed to specific emails

### ISSUE THREAD

**Issue by dbpolito** [longhorn/longhorn#2320]
I would like to join `longhorn-dev` slack and get involved but it seems closed to specific emails:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/347400/110650361-3d199c00-8199-11eb-8cdd-29521e960424.png">

Is this email required intentional? Or it should be public?

I had a problem on one of my public slacks that got this lock and i had to change the config:

<img width="931" alt="image" src="https://user-images.githubusercontent.com/347400/110650602-75b97580-8199-11eb-95a5-e5f0d74b94c2.png">

**Comment by joshimoo** [comment]
Are you already on the rancher-users slack?
You should be able to get an invite at the below link.
https://slack.rancher.io/

**Comment by dbpolito** [comment]
Awesome, maybe worth adding to https://github.com/longhorn/longhorn/blob/master/CONTRIBUTING.md that you have to go through this page, tried to find myself before opening this issue but no luck.

Thank you!
