### ISSUE TITLE
[FEATURE][infra] display test logs in Jenkins console output while tests are running

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2331]
**Is your feature request related to a problem? Please describe.**
Currently, we can only see very little info about the testing status during test runs, and to discover issues we need to wait for the test run to complete.
```
Longhorn tests still running ... rechecking in 5m
...
Recording test results
```
Should consider having the test logs output to Jenkins console output so we could discover issues and progress with fixes at an earlier stage.

**Describe the solution you'd like**
have test logs displayed in Jenkins console output while tests are running.

**Describe alternatives you've considered**
`none`

**Additional context**
`none`

**Comment by innobead** [comment]
cc @meldafrawi

**Comment by c3y1huang** [comment]
Close in favor of https://github.com/longhorn/longhorn/issues/7490.
