### ISSUE TITLE
[BUG][infra] junit-report.xml failed to read

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2333]
**Describe the bug**
Noticed currently the junit-report.xml report gets created from [kubectl logs](https://github.com/longhorn/longhorn-tests/blob/master/test_framework/scripts/longhorn-setup.sh#L210), and when py.test hits an error will break the junit-report.xml.

The [error](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/62/testReport/junit/longhorn-test-junit-report/xml/_failed_to_read_/) in the test result is not really helpful, we should probably consider using `kubectl cp` instead.

**To Reproduce**
1. Create an invalid test file in [/manager/integration/tests](https://github.com/longhorn/longhorn-tests/tree/master/manager/integration/tests) and build the image.
2. Run [regression](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/) with the image.

**Expected behavior**
* Should create valid junit-report.xml.
* Should see the result from the junit-report with some sort of error indicating where it's faulty. For example,
```
<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="1" failures="0" hostname="longhorn-test" name="pytest" skipped="0" tests="1" time="0.508" timestamp="2021-03-12T04:52:30.737996"><testcase classname="" file="tests/test_node_c3y1.py" name="tests.test_node_c3y1" time="0.000"><error message="collection failure">/usr/local/lib/python3.9/site-packages/_pytest/python.py:492: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/local/lib/python3.9/site-packages/py/_path/local.py:704: in pyimport
    __import__(modname)
&lt;frozen importlib._bootstrap&gt;:1007: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:986: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:680: in _load_unlocked
    ???
/usr/local/lib/python3.9/site-packages/_pytest/assertion/rewrite.py:134: in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
/usr/local/lib/python3.9/site-packages/_pytest/assertion/rewrite.py:317: in _rewrite_test
    tree = ast.parse(source, filename=fn)
/usr/local/lib/python3.9/ast.py:50: in parse
    return compile(source, filename, mode, flags,
E     File &quot;/integration/tests/test_node_c3y1.py&quot;, line 1
E       cleanup_node_disks, wait_for_disk_storage_available, \
E   IndentationError: unexpected indent</error></testcase></testsuite></testsuites>
```

**Log**
`n/a`

**Environment:**
`n/a`

**Additional context**
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/43/#showFailuresLink

**Comment by innobead** [comment]
cc @meldafrawi

**Comment by innobead** [comment]
@meldafrawi please help with this. Thanks!

**Comment by c3y1huang** [comment]
Also happens when timeout on regression deployment.

**Comment by meldafrawi** [comment]
Failed to read test report file: https://ci.longhorn.io/job/public/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/301/
