### ISSUE TITLE
[BUG][infra] regression job get stuck

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2334]
**Describe the bug**
Sometimes [regression](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/) get stuck with,
```
null_resource.wait_for_docker_start_worker[1]: Still creating... [1h22m30s elapsed]
null_resource.wait_for_docker_start_worker[2]: Still creating... [1h22m30s elapsed]
null_resource.wait_for_docker_start_worker[0]: Still creating... [1h22m30s elapsed]
```

**To Reproduce**
Not exactly sure, but could try to start two jobs at the same time with the same parameters.

**Expected behavior**
Should run and finish.

**Log**
`none`

**Environment:**
`none`

**Additional context**
[Build #70](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/70/console)

**Comment by c3y1huang** [comment]
Seems like it could be caused by resource exhaust in the deployed zone. Might need to add some timeout or error.

**Comment by innobead** [comment]
@meldafrawi can we think about dynamically selecting a different zone when running the test cases if the resource is not enough?
