### ISSUE TITLE
[FEATURE] Advanced Scheduling for Share Manager

### ISSUE THREAD

**Issue by awelsman** [longhorn/longhorn#2335]
I have a cluster with a number of nodes (EC2 instances) which, under considerable load, can die and be cycled back into the cluster by RKE. I want to run Longhorn on both those nodes and a few other, much more reliable ones. I have three nodes dedicated to Longhorn, one in each availability zone, and am storing my RWX volume replicas there. I can attach my volume to one of these dedicated nodes, but the moment I mount the volume to a deployment by using a PVC, the volume attaches to any random node Longhorn is installed on, not necessarily the one I selected through the UI.

It would be ideal if I could reliably schedule the Share Manager pod to a given dedicated node. I realize the drawbacks with high availability and NFS, but would like to avoid running the pod on any of my more unreliable nodes.

**Comment by PhanLe1010** [comment]
Original discussion at https://forums.rancher.com/t/advanced-scheduling-for-share-manager/19717

**Comment by awelsman** [comment]
Any updates on this?

**Comment by joshimoo** [comment]
@awelsman this is definitly a good use case, to have more control over the scheduling of the internal longhorn components (share-manager, etc). Thanks for opening the enhancement, no commitment yet, but it's something to keep in mind next time we do some refactoring around the share-manager #2096

**Comment by james-munson** [comment]
It seems like this is asking much the same thing as #4863
I would be happy to take this and combine them.

**Comment by ChanYiLin** [comment]
Yes I just found these two issues might be the same.
I also haven't started working on this one.
cc @innobead

**Comment by ChanYiLin** [comment]
Hi @james-munson 
I have transferred the ticket to you.
You can combined all related issues together.

**Comment by innobead** [comment]
@derekbit is this same as what you have done for SM location scheduling? If yes, let's close this with the duplicated label. 

cc @PhanLe1010

**Comment by derekbit** [comment]
Yes. It is same as https://github.com/longhorn/longhorn/issues/7872.
Let's close the ticket.
