### ISSUE TITLE
[BUG] Cycling pods regularly results in fsck errors

### ISSUE THREAD

**Issue by MikaelSmith** [longhorn/longhorn#2336]
**Describe the bug**
Stopping and starting pods in an application with 13 PVCs results in at least one showing up with
```
  Warning  FailedMount  64s (x39 over 76m)    kubelet  MountVolume.SetUp failed for volume "pvc-8ca2553a-0d63-42d4-93ce-4a1c47085dff" : rpc error: code = Internal desc = 'fsck' found errors on device /dev/longhorn/pvc-8ca2553a-0d63-42d4-93ce-4a1c47085dff but could not correct them: fsck from util-linux 2.31.1
ext2fs_check_if_mount: Can't check if filesystem is mounted due to missing mtab file while determining whether /dev/longhorn/pvc-8ca2553a-0d63-42d4-93ce-4a1c47085dff is mounted.
/dev/longhorn/pvc-8ca2553a-0d63-42d4-93ce-4a1c47085dff: One or more block group descriptor checksums are invalid.  FIXED.
/dev/longhorn/pvc-8ca2553a-0d63-42d4-93ce-4a1c47085dff: Group descriptor 64 checksum is 0x0000, should be 0x4a22.

/dev/longhorn/pvc-8ca2553a-0d63-42d4-93ce-4a1c47085dff: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY.
  (i.e., without -a or -p options)
```

**To Reproduce**
1. Run a 3-node cluster (1 control-plane, 2 workers) with Longhorn using all 3 nodes
2. Run a large application. Mine has 13 PVCs, writing log updates pretty much continuously (every couple seconds) and with 6 postgres instances.
3. Cycle pods
    ```
    kubectl scale deploy --all --replicas 0
    kubectl scale sts --all --replicas 0
    sleep 10
    kubectl scale sts --all --replicas 1
    kubectl scale deploy --all --replicas 1
    ```
4. Usually at least 1 pod will be unable to mount a volume due to fsck errors.

**Expected behavior**
Pods should mount successfully.

**Log**
[longhorn-support-bundle_ee48a964-d6ec-4141-af7a-84f62c5cea44_2021-03-11T23-34-35Z.zip](https://github.com/longhorn/longhorn/files/6132512/longhorn-support-bundle_ee48a964-d6ec-4141-af7a-84f62c5cea44_2021-03-11T23-34-35Z.zip)

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: https://kurl.sh with experimental Longhorn support
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: CentOS 7.9.2009
   - CPU per node: 4
   - Memory per node: 8 GB
   - Disk type(e.g. SSD/NVMe): Tintri storage array, not sure on actual hardware. Latency is definitely in ms rather than us.
   - Network bandwidth between the nodes: Maybe 1Gbps?
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Platform9 managed Openstack
 - Number of Longhorn volumes in the cluster: 24 (running a few other applications in other namespaces with less intense data profiles)

**Additional context**
I've been able to recover this in one case by deleting the currently attached replica ("connect-b" in that case) and letting others recover. Some details I noted while comparing replicas across nodes
- revision.counter was the same across all replicas
- the "connect" replica was at volume-head-005.img, where as others were at volume-head-004.img. However the content of volume-head-*.img across all 3 replicas matched.
- the "connect-b" replica, despite having volume-head-004.img, referenced volume-head-005.img in volume-head-004.img.meta. This seemed like a warning sign that maybe a process failed midway through. The other volume-head-*.img.meta differed, but only because "connect" was on 5 while "connect-a" was on 4.
- "connect" and "connect-a" had matching snapshots (.img and .img.meta). "connect-b" had the same metadata and .img name, but the .img contents differed from the other two.

I have a current incident I plan to dig into and see if it shares any similarities with the prior failure; I'll update once I dig into it. Disk latency may be a factor; I can check with the service provider on whether there are any health warnings on the disk array, but I would expect that to be monitored.

**Comment by MikaelSmith** [comment]
The new incident, trying to mount to "connect-a" (sha1sums)
```
# connect
$ cd /var/lib/longhorn/replicas/pvc-8ca2553a-0d63-42d4-93ce-4a1c47085dff-e35ae057; sha1sum *
23604d3a8bef8b913791eb1fb8a6b62b6fc734a1  revision.counter
0834657d77542f5b45e8e2c2752b62c60df81328  volume-head-004.img
cd81192671f484e51928caab4b6958c0d38b9f3d  volume-head-004.img.meta
6470514de79c005017c7c9ce5b1c720b24607983  volume.meta
796fb19b129f5cca658dced1e633df221303686d  volume-snap-b405c3ea-40e1-462e-8492-0d2a8a36f55e.img
2ce2cbf505fd3c5b556a3df96e90c76e39511a12  volume-snap-b405c3ea-40e1-462e-8492-0d2a8a36f55e.img.meta
$ cat volume-head-004.img.meta
{"Name":"volume-head-003.img","Parent":"volume-snap-b405c3ea-40e1-462e-8492-0d2a8a36f55e.img","Removed":false,"UserCreated":false,"Created":"2021-03-12T17:40:52Z","Labels":null}
$ cat volume.meta
{"Size":9663676416,"Head":"volume-head-004.img","Dirty":true,"Rebuilding":false,"Error":"","Parent":"volume-snap-b405c3ea-40e1-462e-8492-0d2a8a36f55e.img","SectorSize":512,"BackingFileName":""}

# connect-a
$ cd /var/lib/longhorn/replicas/pvc-8ca2553a-0d63-42d4-93ce-4a1c47085dff-8362dd08; sha1sum *
23604d3a8bef8b913791eb1fb8a6b62b6fc734a1  revision.counter
0834657d77542f5b45e8e2c2752b62c60df81328  volume-head-004.img
9eb3ba14a6bcc85fec50aa452e170f757aaf0eea  volume-head-004.img.meta
6470514de79c005017c7c9ce5b1c720b24607983  volume.meta
81a9d3cd9086b21d882696e904740a6c28b6b86f  volume-snap-b405c3ea-40e1-462e-8492-0d2a8a36f55e.img
2ce2cbf505fd3c5b556a3df96e90c76e39511a12  volume-snap-b405c3ea-40e1-462e-8492-0d2a8a36f55e.img.meta
$ cat volume-head-004.img.meta
{"Name":"volume-head-004.img","Parent":"volume-snap-b405c3ea-40e1-462e-8492-0d2a8a36f55e.img","Removed":false,"UserCreated":false,"Created":"2021-03-12T17:40:52Z","Labels":null}
$ cat volume.meta
{"Size":9663676416,"Head":"volume-head-004.img","Dirty":true,"Rebuilding":false,"Error":"","Parent":"volume-snap-b405c3ea-40e1-462e-8492-0d2a8a36f55e.img","SectorSize":512,"BackingFileName":""}

# connect-b
$ cd /var/lib/longhorn/replicas/pvc-8ca2553a-0d63-42d4-93ce-4a1c47085dff-bfed78a5; sha1sum *
23604d3a8bef8b913791eb1fb8a6b62b6fc734a1  revision.counter
0834657d77542f5b45e8e2c2752b62c60df81328  volume-head-003.img
cd81192671f484e51928caab4b6958c0d38b9f3d  volume-head-003.img.meta
a8401475cd7dbce614897c86f9f75b4422e07571  volume.meta
81a9d3cd9086b21d882696e904740a6c28b6b86f  volume-snap-b405c3ea-40e1-462e-8492-0d2a8a36f55e.img
2ce2cbf505fd3c5b556a3df96e90c76e39511a12  volume-snap-b405c3ea-40e1-462e-8492-0d2a8a36f55e.img.meta
$ cat volume-head-003.img.meta
{"Name":"volume-head-003.img","Parent":"volume-snap-b405c3ea-40e1-462e-8492-0d2a8a36f55e.img","Removed":false,"UserCreated":false,"Created":"2021-03-12T17:40:52Z","Labels":null}
$ cat volume.meta
{"Size":9663676416,"Head":"volume-head-003.img","Dirty":true,"Rebuilding":false,"Error":"","Parent":"volume-snap-b405c3ea-40e1-462e-8492-0d2a8a36f55e.img","SectorSize":512,"BackingFileName":""}
```

"connect-a" seems to be the faulty replica, but I'm also suspicious of the replica on "connect" due to the volume-head number mismatch.

**Comment by joshimoo** [comment]
@MikaelSmith thanks for the update, can you attach a new support bundle.
And post the context information, time of incident, which volumes, relevant nodes, etc.

**Comment by MikaelSmith** [comment]
[longhorn-support-bundle_ee48a964-d6ec-4141-af7a-84f62c5cea44_2021-03-12T21-35-45Z.zip](https://github.com/longhorn/longhorn/files/6133109/longhorn-support-bundle_ee48a964-d6ec-4141-af7a-84f62c5cea44_2021-03-12T21-35-45Z.zip)

Failure was March 12 (today) sometime between 17:39-18:00 UTC, on "connect-a", pvc-8ca2553a-0d63-42d4-93ce-4a1c47085dff. Not a production system.

Happened when rolling out new images to 4 different pods, including the affected pod.

**Comment by jenting** [comment]
- Is the fsck error volume all happens on the same node? If yes, could you please check the HW with S.M.A.R.T. tool?
- could you please check each replica content is fine or not? https://longhorn.io/docs/1.1.0/advanced-resources/data-recovery/export-from-replica/ (we'd like to find out the health replica)

**Comment by MikaelSmith** [comment]
The "hardware" is block storage from a Tintri storage array, which is not reporting errors.

I don't have these setup anymore. The last failure I ran through, I checked and all replicas had fsck errors.

Also, running through "export-from-replica" is challenging when using containerd rather than Docker.

**Comment by jenting** [comment]
> Also, running through "export-from-replica" is challenging when using containerd rather than Docker.

The documentation should be updated to provided commands if the Kubernetes cluster using `containerd`.

**Comment by MikaelSmith** [comment]
To clarify, I didn't figure out how to run a container with a mounted volume with containerd. I instead tried deleting and recreating each replica, and was not able to get a working one. It's possible that ended up polluting all of the replicas somehow.

**Comment by jenting** [comment]
Sorry for the late reply.

1. Could you please check which replica is the healthy one? You could consider installing `docker` on the host and follows https://longhorn.io/docs/1.1.0/advanced-resources/data-recovery/export-from-replica/ to mount the block device to access the data to check which replica is the healthy one.
2. Try to fix the block device by run `fsck` check and repair unhealthy replicas.
2. Removes the unhealthy replicas, Longhorn will rebuild replicas from the existing healthy ones.

You could also reference this https://longhorn.io/docs/1.1.0/advanced-resources/data-recovery/data-error/

**Comment by MikaelSmith** [comment]
This cluster no longer exists. I may be able to set up another to test sometime in the next week or two.

Given how frequently this occurred, my concern was more that it was a recurring issue, not recovering from that specific failure.

**Comment by jenting** [comment]
Is this issue still exist on a new cluster?
Have you upgraded the Longhorn to v1.1.1?

**Comment by MikaelSmith** [comment]
I'll give 1.1.1 a try in the next few weeks.

**Comment by MikaelSmith** [comment]
So far 1.1.1 does seem more stable overall. I'm now testing with GCP instances using their balanced disks, and haven't run into any issues.

**Comment by jenting** [comment]
Good to know, thank's for your effort @MikaelSmith :smile:
