### ISSUE TITLE
[BUG] Deleting a backup causes longhorn-manager memory to spike for 30 minutes

### ISSUE THREAD

**Issue by tyzbit** [longhorn/longhorn#2339]
**Describe the bug**
After deleting a backup, longhorn-manager's memory usage spikes to >1GB.  It comes back down after 30 minutes.  If multiple backups are deleted in quick succession, it compounds so much so that it crashes and causes that node to desync and all volumes become degraded.

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/3319104/111080500-22b32b80-84d5-11eb-8b96-f22686501a09.png">

**To Reproduce**
1. Create a backup to S3 of a volume
2. Delete the backup

**Expected behavior**
longhorn-manager should not use that much memory just to delete a backup.

**Log**
N/A

**Environment:**
 - Longhorn version: v1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: kubeadm, v1.19.7
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 6 total, 3 with replicas
 - Node config
   - OS type and version: Ubuntu 20.04.1 LTS
   - CPU per node: 8
   - Memory per node: 16GB
   - Disk type(e.g. SSD/NVMe): NVMe (Samsung 970 Evo Plus)
   - Network bandwidth between the nodes: 1Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 14 active

## Logs
<details><summary>Longhorn-manager logs</summary>
<pre>

time="2021-03-14T18:55:29Z" level=debug msg="websocket: open" id=6250582626737297316 type=settings
time="2021-03-14T18:55:29Z" level=debug msg="websocket: open" id=2196107726852687710 type=nodes
time="2021-03-14T18:55:30Z" level=debug msg="websocket: open" id=8160435571402399714 type=volumes
time="2021-03-14T18:55:30Z" level=debug msg="websocket: open" id=812737792642688048 type=engineimages
time="2021-03-14T18:55:30Z" level=debug msg="websocket: open" id=2000082780510160816 type=events
192.168.1.49 - - [14/Mar/2021:18:55:30 +0000] "GET /v1/ws/1s/volumes HTTP/1.1" 200 0 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:86.0) Gecko/20100101 Firefox/86.0"
time="2021-03-14T18:56:58Z" level=debug msg="websocket: close 1001 (going away)" id=8160435571402399714 type=volumes
time="2021-03-14T18:56:58Z" level=debug msg="websocket: close 1001 (going away)" id=812737792642688048 type=engineimages
192.168.1.49 - - [14/Mar/2021:18:55:30 +0000] "GET /v1/ws/1s/engineimages HTTP/1.1" 200 0 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:86.0) Gecko/20100101 Firefox/86.0"
time="2021-03-14T18:56:58Z" level=debug msg="websocket: close 1001 (going away)" id=2196107726852687710 type=nodes
192.168.1.49 - - [14/Mar/2021:18:55:29 +0000] "GET /v1/ws/1s/nodes HTTP/1.1" 200 0 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:86.0) Gecko/20100101 Firefox/86.0"
192.168.1.49 - - [14/Mar/2021:18:55:30 +0000] "GET /v1/ws/1s/events HTTP/1.1" 200 0 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:86.0) Gecko/20100101 Firefox/86.0"
time="2021-03-14T18:56:58Z" level=debug msg="websocket: close 1001 (going away)" id=2000082780510160816 type=events
time="2021-03-14T18:56:58Z" level=debug msg="websocket: close 1001 (going away)" id=6250582626737297316 type=settings
192.168.1.49 - - [14/Mar/2021:18:55:29 +0000] "GET /v1/ws/1s/settings HTTP/1.1" 200 0 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:86.0) Gecko/20100101 Firefox/86.0"
192.168.1.49 - - [14/Mar/2021:18:57:02 +0000] "POST /v1/backupvolumes/pvc-77903a7e-7c93-4522-8f72-6e9c5c8dff7e?action=backupDelete HTTP/1.1" 200 802 "https://longhorn.qtosw.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:86.0) Gecko/20100101 Firefox/86.0"
time="2021-03-14T18:57:02Z" level=debug msg="Removed backup backup-9604761d3ff14f04 of volume pvc-77903a7e-7c93-4522-8f72-6e9c5c8dff7e"
time="2021-03-14T18:57:02Z" level=info msg="Start Deleting backup s3://takeout-backups@us-east-1/?backup=backup-9604761d3ff14f04&volume=pvc-77903a7e-7c93-4522-8f72-6e9c5c8dff7e"
192.168.1.49 - - [14/Mar/2021:18:57:02 +0000] "GET /v1/backupvolumes?volumeName=pvc-77903a7e-7c93-4522-8f72-6e9c5c8dff7e&name=backup-9604761d3ff14f04&field=volumeName&keyword=pvc-77903a7e-7c93-4522-8f72-6e9c5c8dff7e HTTP/1.1" 200 6509 "https://longhorn.qtosw.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:86.0) Gecko/20100101 Firefox/86.0"
192.168.1.49 - - [14/Mar/2021:18:57:04 +0000] "POST /v1/backupvolumes/pvc-77903a7e-7c93-4522-8f72-6e9c5c8dff7e?action=backupList HTTP/1.1" 200 59134 "https://longhorn.qtosw.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:86.0) Gecko/20100101 Firefox/86.0"
time="2021-03-14T19:24:55Z" level=info msg="Complete deleting backup s3://takeout-backups@us-east-1/?backup=backup-9604761d3ff14f04&volume=pvc-77903a7e-7c93-4522-8f72-6e9c5c8dff7e"
</pre>
</details>

**Comment by PhanLe1010** [comment]
@tyzbit Thank you for reporting

First, can we request more info about your environment? 
1. Can you send us a support bundle to `longhorn-support-bundle@rancher.com` ?
2. How big is your backup in the s3


From the code perspective, in the current implementation I can see that deleting backup might consume significant amount of memory. [Longhorn is doing incremental backups](https://longhorn.io/docs/1.1.0/concepts/#31-how-backups-work). Multiple backups can point to the same block in S3 target. So, when users delete a backup, Longhorn need to find out which block is only associated with the backup that is being deleted. In order to do so, Longhorn is downloading the metadata of all blocks and backups into memory. Assume that the volume has size of 1TB. The number of blocks in s3 can be `1TB/2MB = 524288` blocks. If the meta data of each block is `64*3` bytes. This would mean `524288*64*3 = 100MB` of memory. The metadata of blocks can be kept repeatedly in [multiple backups](https://github.com/longhorn/backupstore/blob/51dcc71901ed7f377a80df143196933096605cf4/deltablock.go#L840). In sum, it can take a few hundreds of MB. 

@joshimoo How do you think?

**Comment by tyzbit** [comment]
1. Sent
2. This particular backup is 240Gi total, 191Gi used.

That explanation makes sense.  If that memory usage is inevitable then I suggest at least some sort of informational notification to the user warning them of the increased memory usage, or queuing the deletion of backups (if possible) when a user wishes to delete many backups at once.  I'm sure other users will come across scenarios like mine where they need to delete pages of backups at once.

**Comment by joshimoo** [comment]
@tyzbit if you want to delete all backups for a volume one can use this function, that way we don't need to do in use detection of backup blocks.
![image](https://user-images.githubusercontent.com/1287163/111791308-620dbd80-88c3-11eb-8214-db1aa92b86e0.png)

**Comment by joshimoo** [comment]
@PhanLe1010 this is a fun one to fix :)

- retrieve the blockMap per backup then merge into the blockMap
- keep track of the lastBackup while evaluating the backups
- this way we don't need to retain all the backup information in memory, this will still spike but the gc can cleanup

here is a patch, finish the mergeMap and it should be good to go, also verify the empty lastBackupName/time for the dr volume. https://github.com/longhorn/backupstore/blob/51dcc71901ed7f377a80df143196933096605cf4/deltablock.go#L824

```go
	getBackupInfo := func(name string) (valid bool, snapshotCreatedAt string, blockMap map[string]*BlockInfo) {
		backup, err := loadBackup(name, volumeName, bsDriver)
		if err != nil {
			log.Warnf("skipping block deletion because we failed to load backup %v for volume %v error %v",
				name, volumeName, err)
			return false, "", nil
		}

		if isBackupInProgress(backup) {
			log.Infof("skipping block deletion because of in progress backup %v for volume %v",
				backup.Name, volumeName)
			return false, "", nil
		}

		// TODO: retrieve block map for this backup
		backupMap, err := getBlockInfoMap(backup, volumeName, bsDriver)
		if err != nil {
			log.Warnf("skipping block deletion because we failed to get block infos for volume %v error %v",
				volumeName, err)
			return false, "", nil
		}

		return true, backup.SnapshotCreatedAt, backupMap
	}

	var lastBackupName string
	var lastBackupAt string
	blockMap := make(map[string]*BlockInfo)
	for _, name := range backupNames {
		valid, snapshotCreatedAt, blockMap := getBackupInfo(name)
		deleteBlocks = deleteBlocks && valid
		if !deleteBlocks {
			break
		}

		if lastBackupName == "" || lastBackupAt == "" {
			lastBackupName = name
			lastBackupAt = snapshotCreatedAt
		}

		lastBackupTime, err1 := time.Parse(time.RFC3339, lastBackupAt)
		backupTime, err2 := time.Parse(time.RFC3339, snapshotCreatedAt)
		if err1 != nil || err2 != nil {
			log.Warnf("skipping block deletion because we failed to parse backup %v time %v due to error %v",
				name, volumeName, err)
			deleteBlocks = false
			break
		}

		if backupTime.After(lastBackupTime) {
			lastBackupName = name
			lastBackupAt = snapshotCreatedAt
		}

		// TODO: merge this backup map into the block map
		blockMap = merge(blockMap, backupMap)
	}

	// update the volume
	v, err := loadVolume(volumeName, bsDriver)
	if err != nil {
		return fmt.Errorf("Cannot find volume %v in backupstore due to: %v", volumeName, err)
	}

	if backupToBeDeleted.Name == v.LastBackupName {
		v.LastBackupName = ""
		v.LastBackupAt = ""

		// TODO: I think it's better to only set the latestBackup to one of the existing ones
		// 	if we where able to correctly load everything, setting it blank should lead to a full evaluation of the
		//  snapshot chain on the next backup, verify if the dr volume can deal with unset lastBackup
		if deleteBlocks {
			v.LastBackupName = lastBackupName
			v.LastBackupAt = lastBackupAt
		}

		if err := saveVolume(v, bsDriver); err != nil {
			return err
		}
	}
```

**Comment by joshimoo** [comment]
@innobead we should include this fix in v1.1.1 if we have time.

**Comment by PhanLe1010** [comment]
Thank @joshimoo for the suggestion
Sure! I would like to take this one after finish other pending issues

**Comment by joshimoo** [comment]
@innobead @yasker We should really consider including this in v1.1.1 since It can have a big impact on customer cluster stability.
Let me summarize the issue, memory consumption during deletion depends on the amount of backups and the amount of blocks a volume has stored and can skyrocket since we load and maintain all backup information for a volume in memory for the duration of the deletion processing. 

This can get worse in the case where the user has overlapping recurring backup schedules, because now they would be potentially running the block gc concurrently for multiple volumes.

**This can lead to failed backups in the case where the node runs out of memory, but also worse to memory pressure which will potentially make other pods fail/get evicted.**

I provided a change of behavior in this comment https://github.com/longhorn/longhorn/issues/2339#issuecomment-802891137
That would make this processing iterative, which would allow the GC to reclaim the previously loaded backup space.

**Comment by yasker** [comment]
I've put it tentatively in v1.1.1. Let's discuss it in the next meeting. cc @innobead

**Comment by PhanLe1010** [comment]
Validation: **Pass**

## Case 1: Delete 1 backups
### Longhorn v1.1.0
1. Create a volume of 50 GB. Write 40GB data to the volume
1. Take a backup
1. Write 50MB data to the volume. Take a new backup. 
1. Repeat step 3 ten times
1. Delete the latest backup
1. The node where Longhorn manager consumes about 81MB more memory during the deletion
    <img width="1211" alt="Screen Shot 2021-04-22 at 2 27 05 PM" src="https://user-images.githubusercontent.com/22139961/115787436-09748900-a377-11eb-9081-4bdc317c9468.png">

### Longhorn v1.1.1-rc2
1. Repeat the above steps in the v1.1.0 case, we have the node where Longhorn manager consumes about 24MB more memory during the deletion
    <img width="1228" alt="Screen Shot 2021-04-22 at 2 35 13 PM" src="https://user-images.githubusercontent.com/22139961/115788171-2067ab00-a378-11eb-8bd0-c2a55fed4fbe.png">

## Case 2: Delete multiple backups

### Longhorn v1.1.0
1. Create a volume of 50 GB. Write 40GB data to the volume
1. Take a backup
1. Write 50MB data to the volume. Take a new backup. 
1. Repeat step 3 ten times
1. Delete the 10 latest backups as quick as possible 
1. The Longhorn manager that is doing the deletion uses about 80MB more memory during the deletion:
    <img width="1865" alt="Screen Shot 2021-04-22 at 10 41 41 AM" src="https://user-images.githubusercontent.com/22139961/115788702-cddabe80-a378-11eb-9c59-c1c7b8af182b.png">


### Longhorn v1.1.1-rc2
1. Repeat the above steps in the v1.1.0 case, the Longhorn manager that is doing the deletion uses about 300MB more memory during the deletion:
    <img width="1869" alt="Screen Shot 2021-04-22 at 11 03 42 AM" src="https://user-images.githubusercontent.com/22139961/115788758-eb0f8d00-a378-11eb-87b5-47dfebe0c383.png">
