### ISSUE TITLE
[BUG] The volume <pvcid> is attaching

### ISSUE THREAD

**Issue by crackerjam** [longhorn/longhorn#2340]
**Describe the bug**
I'm trying to create a simple pod with an attached longhorn volume, but the pod startup fails with a cryptic error:
` AttachVolume.Attach failed for volume "pvc-c5c541a0-82f3-44fd-8e7e-88f95d3d6f83" : rpc error: code = Aborted desc = The volume pvc-c5c541a0-82f3-44fd-8e7e-88f95d3d6f83 is attaching `

The volume in the Longhorn UI sits in state "Attaching" indefinitely.

**To Reproduce**
1. Create a PVC in rancher, using the longhorn storage class and all of the other settings default.
2. Create a deployment in rancher with the following settings:
Container image: ubuntu
Command: /bin/bash
Stdin: yes
TTY: checked
Storage: Select the PVC created in step 1, set mount point to /mnt/longhorn
All other settings default
3. The pod will fail to start successfully, seeming to be stuck on attaching the longhorn volume, and will show the error above.

**Expected behavior**
At step 3, I would expect the pod to start successfully and see a mount at /mnt/longhorn with the longhorn volume inside of the pod container OS.

**Log**
[longhorn-support-bundle_331977bb-ca15-4f3a-8383-3ca98227ac5c_2021-03-14T19-44-33Z.zip](https://github.com/longhorn/longhorn/files/6137458/longhorn-support-bundle_331977bb-ca15-4f3a-8383-3ca98227ac5c_2021-03-14T19-44-33Z.zip)

**Environment:**
 - Longhorn version: **1.1.0**
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: **RKE, v1.20.4**
   - Number of management node in the cluster: **3**
   - Number of worker node in the cluster: **3**
 - Node config
   - OS type and version: **Ubuntu 21.10**
   - CPU per node: **4**
   - Memory per node: **8GB**
   - Disk type(e.g. SSD/NVMe): **SSD**
   - Network bandwidth between the nodes: **Local (same hypervisor)**
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): **VMware**
 - Number of Longhorn volumes in the cluster: **1**

**Additional context**
Nothing I can think of.

**Comment by cclhsu** [comment]
Hi! Can you provide output of command `sudo systemctl status iscsid` for the nodes?

**Comment by crackerjam** [comment]
You bet, thanks for the reply.

```
● iscsid.service - iSCSI initiator daemon (iscsid)
     Loaded: loaded (/lib/systemd/system/iscsid.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-03-15 16:22:12 UTC; 2h 26min ago
TriggeredBy: ● iscsid.socket
       Docs: man:iscsid(8)
    Process: 832 ExecStartPre=/lib/open-iscsi/startup-checks.sh (code=exited, status=0/SUCCESS)
    Process: 865 ExecStart=/sbin/iscsid (code=exited, status=0/SUCCESS)
   Main PID: 878 (iscsid)
      Tasks: 2 (limit: 9441)
     Memory: 4.1M
     CGroup: /system.slice/iscsid.service
             ├─877 /sbin/iscsid
             └─878 /sbin/iscsid

Mar 15 16:22:12 rancher-work01 systemd[1]: Starting iSCSI initiator daemon (iscsid)...
Mar 15 16:22:12 rancher-work01 iscsid[865]: iSCSI logger with pid=877 started!
Mar 15 16:22:12 rancher-work01 systemd[1]: Started iSCSI initiator daemon (iscsid).
Mar 15 16:22:12 rancher-work01 iscsid[877]: iSCSI daemon with pid=878 started!
```

Other nodes are similar, just with different pid values.

**Comment by crackerjam** [comment]
I did find one thing, re-reading the documentation, I discovered the environment_check.sh script, and see some errors, but I'm not entirely sure what's causing them.

```
rancher-work01# curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.1.0/scripts/environment_check.sh | bash
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
all pods ready (/)
The connection to the server localhost:8080 was refused - did you specify the right host or port?
node : MountPropagation DISABLED

  MountPropagation is disabled on at least one node.
  As a result, CSI driver and Base image cannot be supported.

cleaning up...
error: unable to recognize "/tmp/tmp.56LQAZXbKt/environment_check.yaml": Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
clean up complete
```

I have `MountFlags=shared` in `/lib/systemd/system/docker.service`, so as far as I know it should work fine. Based on the content of the script it looks like the kubectl commands aren't able to connect to something. Not sure if that's related to my problem or not.

Either way, running the mentioned a few packages I didn't have installed. I've installed them and have a new support bundle here: [longhorn-support-bundle_331977bb-ca15-4f3a-8383-3ca98227ac5c_2021-03-15T22-27-29Z.zip](https://github.com/longhorn/longhorn/files/6144858/longhorn-support-bundle_331977bb-ca15-4f3a-8383-3ca98227ac5c_2021-03-15T22-27-29Z.zip)

**Comment by cclhsu** [comment]
did you run this command on the master or an external with kubeconfig?  Seems like you run in one of worker node.

**Comment by crackerjam** [comment]
All 3 of the nodes in my cluster have all of the roles, so they each have etcd, control plane, and worker status. They were all created through a docker command like this:

`sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run  rancher/rancher-agent:v2.5.6 --server https://rancherurl:8443 --token token --ca-checksum checksum --etcd --controlplane --worker`

Kubectl wasn't actually present on the servers after they were deployed with that, I had to install the package directly.

**Comment by cclhsu** [comment]
For RKE cluster, please follow the guide (https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cluster-access/kubectl/) to setup on kubeconfig.

**Comment by crackerjam** [comment]
Thanks for that, that resolved my problems with the environment check script at least.

```
rancher-work01# curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.1.0/scripts/environment_check.sh | bash
daemonset.apps/longhorn-environment-check created
waiting for pods to become ready (0/3)
waiting for pods to become ready (0/3)
all pods ready (3/3)

  MountPropagation is enabled!

cleaning up...
daemonset.apps "longhorn-environment-check" deleted
clean up complete
```

That's odd, I don't see any pods that include "instance" in the name, in any namespace. Is "longhorn-manager" the same thing, or is my deployment missing something somehow?

**Comment by cclhsu** [comment]
There should be one instance-manager-e and one instance-manager-r in each of the worker node.  If the worker nodes lack of resources, these pods might either fail to startup or get killed.  Try to increase resource allocation (CPU/Memory) for the worker nodes.

**Comment by crackerjam** [comment]
I don't believe that's the problem here, there's a good amount of free resources, and the pods simply don't exist, they don't appear to be in a creation loop or something like that. For example,

```
> kubectl get pods --all-namespaces 
NAMESPACE         NAME                                       READY   STATUS              RESTARTS   AGE
cattle-system     cattle-cluster-agent-6b8857d56c-7t6p6      1/1     Running             12         7d17h
cattle-system     cattle-node-agent-jlswp                    1/1     Running             11         7d17h
cattle-system     cattle-node-agent-pkntt                    1/1     Running             12         7d17h
cattle-system     cattle-node-agent-rmt4v                    1/1     Running             11         7d17h
cattle-system     dashboard-shell-ztxq9                      2/2     Running             0          23s
cattle-system     kube-api-auth-2z4w7                        1/1     Running             8          7d17h
cattle-system     kube-api-auth-2zxn7                        1/1     Running             7          7d17h
cattle-system     kube-api-auth-f7h5g                        1/1     Running             7          7d17h
default           nginx-test-6f94bccb44-46dkt                1/1     Running             7          8d
default           nginx-test-6f94bccb44-49rnz                1/1     Running             7          8d
default           nginx-test-6f94bccb44-4mhf7                1/1     Running             7          8d
default           nginx-test-6f94bccb44-69mkl                1/1     Running             7          8d
default           nginx-test-6f94bccb44-c2ntw                1/1     Running             7          8d
default           nginx-test-6f94bccb44-clnjp                1/1     Running             7          8d
default           nginx-test-6f94bccb44-dqxjv                1/1     Running             7          8d
default           nginx-test-6f94bccb44-qql8s                1/1     Running             7          8d
default           nginx-test-6f94bccb44-v99rq                1/1     Running             7          8d
default           nginx-test-6f94bccb44-xfvnd                1/1     Running             7          8d
default           ubuntutest-8f86d865f-vd4zb                 0/1     ContainerCreating   0          40h
fleet-system      fleet-agent-55bfc495bd-l8bp9               1/1     Running             7          8d
ingress-nginx     nginx-ingress-controller-k4whr             1/1     Running             11         12d
ingress-nginx     nginx-ingress-controller-k59ln             1/1     Running             8          12d
ingress-nginx     nginx-ingress-controller-m8h4j             1/1     Running             10         12d
kube-system       calico-kube-controllers-6c8ddcb6cd-bpcvk   1/1     Running             8          8d
kube-system       canal-9m4qt                                2/2     Running             21         12d
kube-system       canal-gqbjp                                2/2     Running             16         12d
kube-system       canal-v8wbv                                2/2     Running             18         12d
kube-system       coredns-669b8675c5-29zd7                   1/1     Running             7          8d
kube-system       coredns-669b8675c5-6k84t                   1/1     Running             7          7d17h
kube-system       coredns-autoscaler-79599b9dc6-p9wdg        1/1     Running             7          8d
kube-system       metrics-server-6cc9c79d8c-65xwc            1/1     Running             7          8d
longhorn-system   csi-attacher-85976fc6f-4kwkf               1/1     Running             1          40h
longhorn-system   csi-attacher-85976fc6f-kcnqq               1/1     Running             1          40h
longhorn-system   csi-attacher-85976fc6f-shcwl               1/1     Running             1          40h
longhorn-system   csi-provisioner-848fd784dc-5d5jl           1/1     Running             1          40h
longhorn-system   csi-provisioner-848fd784dc-6pdts           1/1     Running             1          40h
longhorn-system   csi-provisioner-848fd784dc-k24px           1/1     Running             1          40h
longhorn-system   csi-resizer-5fb779f55f-7jxvg               1/1     Running             1          40h
longhorn-system   csi-resizer-5fb779f55f-8j7k7               1/1     Running             1          40h
longhorn-system   csi-resizer-5fb779f55f-t7gbj               1/1     Running             1          40h
longhorn-system   csi-snapshotter-5f6d68fffd-5cztg           1/1     Running             1          40h
longhorn-system   csi-snapshotter-5f6d68fffd-c9twp           1/1     Running             1          40h
longhorn-system   csi-snapshotter-5f6d68fffd-hv62z           1/1     Running             1          40h
longhorn-system   engine-image-ei-deb8b464-6lkhp             1/1     Running             1          40h
longhorn-system   engine-image-ei-deb8b464-hhx6s             1/1     Running             1          40h
longhorn-system   engine-image-ei-deb8b464-rc5m8             1/1     Running             1          40h
longhorn-system   longhorn-csi-plugin-5z2wm                  2/2     Running             4          40h
longhorn-system   longhorn-csi-plugin-8mgbz                  2/2     Running             2          40h
longhorn-system   longhorn-csi-plugin-8prq9                  2/2     Running             3          40h
longhorn-system   longhorn-driver-deployer-cb89ffd76-tr6sx   1/1     Running             1          40h
longhorn-system   longhorn-manager-8n5vf                     1/1     Running             2          40h
longhorn-system   longhorn-manager-xh2jj                     1/1     Running             2          40h
longhorn-system   longhorn-manager-zl2hv                     1/1     Running             2          40h
longhorn-system   longhorn-ui-858447dc84-cr6pm               1/1     Running             2          40h
```

I've also run `kubectl describe nodes` just to show the resource usage on my nodes, there's really not much going on with them.

[kubectl describe nodes.txt](https://github.com/longhorn/longhorn/files/6157458/kubectl.describe.nodes.txt)

**Comment by cclhsu** [comment]
From the logs `longhorn-manger.log` you have attached, we see that 

```
2021-03-15T22:27:24.901940251Z E0315 22:27:24.901740       1 instance_manager_controller.go:245] fail to sync instance manager for longhorn-system/instance-manager-e-c7956211: failed to create pod for instance manager instance-manager-e-c7956211: Pod "instance-manager-e-c7956211" is invalid: spec.containers[0].resources.requests: Invalid value: "250m": must be less than or equal to cpu limit
2021-03-15T22:27:24.901984464Z time="2021-03-15T22:27:24Z" level=warning msg="Dropping Longhorn instance manager longhorn-system/instance-manager-e-c7956211 out of the queue: fail to sync instance manager for longhorn-system/instance-manager-e-c7956211: failed to create pod for instance manager instance-manager-e-c7956211: Pod \"instance-manager-e-c7956211\" is invalid: spec.containers[0].resources.requests: Invalid value: \"250m\": must be less than or equal to cpu limit"
2021-03-15T22:27:24.901997635Z E0315 22:27:24.901741       1 instance_manager_controller.go:245] fail to sync instance manager for longhorn-system/instance-manager-r-a9a767c1: failed to create pod for instance manager instance-manager-r-a9a767c1: Pod "instance-manager-r-a9a767c1" is invalid: spec.containers[0].resources.requests: Invalid value: "250m": must be less than or equal to cpu limit
2021-03-15T22:27:24.904973046Z time="2021-03-15T22:27:24Z" level=warning msg="Dropping Longhorn instance manager longhorn-system/instance-manager-r-a9a767c1 out of the queue: fail to sync instance manager for longhorn-system/instance-manager-r-a9a767c1: failed to create pod for instance manager instance-manager-r-a9a767c1: Pod \"instance-manager-r-a9a767c1\" is invalid: spec.containers[0].resources.requests: Invalid value: \"250m\": must be less than or equal to cpu limit"
```

Seems like lacks of CPU Resources.

**Comment by crackerjam** [comment]
So, I think I may have figured out the problem. 

The README for the chart, at least in Rancher says "Important: Please install Longhorn chart in longhorn-system namespace only."

Seeing this, I had gone ahead and created a longhorn-system namespace manually, inside of the "System" project. _Something_ with this configuration was applying a CPU limit, causing those instance-manager pods to be unable to start.

The fix was to delete longhorn, remove the longhorn-system namespace, and then install longhorn again, letting it create the namespace itself.

Thanks so much for the guidance through this. While I don't think this is a bug anymore, it may be wise to adjust that line in the README to note that the namespace will be created automatically.

**Comment by innobead** [comment]
> So, I think I may have figured out the problem.
> 
> The README for the chart, at least in Rancher says "Important: Please install Longhorn chart in longhorn-system namespace only."
> 
> Seeing this, I had gone ahead and created a longhorn-system namespace manually, inside of the "System" project. _Something_ with this configuration was applying a CPU limit, causing those instance-manager pods to be unable to start.
> 
> The fix was to delete longhorn, remove the longhorn-system namespace, and then install longhorn again, letting it create the namespace itself.
> 
> Thanks so much for the guidance through this. While I don't think this is a bug anymore, it may be wise to adjust that line in the README to note that the namespace will be created automatically.

longhorn chart installation does not handle `namespace` creation which depends on the helm version. In the readme, we mentioned the namespace usage in different versions of the helm, so we can't make sure how the namespace managed before the helm chart installation. 

```
3. Install Longhorn chart.
- With Helm 2, the following command will create the `longhorn-system` namespace and install the Longhorn chart together.
```
helm install longhorn/longhorn --name longhorn --namespace longhorn-system
``` 
- With Helm 3, the following commands will create the `longhorn-system` namespace first, then install the Longhorn chart.
```

But, it's good to know you already figured out, and thanks for the feedback :+1:
