### ISSUE TITLE
[BUG] csi-resizer encounter error 

### ISSUE THREAD

**Issue by cclhsu** [longhorn/longhorn#2347]
**Describe the bug**

csi-resizer  encounters following errors: 

```
Warning  BackOff    94s (x48 over 11m)  kubelet            Back-off restarting failed container"
```

```
> kubectl logs  pod/csi-resizer-85b4c7f9f5-h6569 -n longhorn-system
flag provided but not defined: -timeout
Usage of /csi-resizer:
```

**To Reproduce**

Use the latest code from master

```
cd ${HOME}/src/github.com/longhorn/longhorn-manager/
kubectl create -Rf deploy/install
```

suspect related new timeout setting in https://github.com/longhorn/longhorn-manager/commit/c1376723fe87e5d3852069f7816b5f80878dea2b

**Expected behavior**
csi-resizer to deploy successfully.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version:
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Additional context**

**Comment by khushboo-rancher** [comment]
csi-resizer `longhornio/csi-resizer:v0.5.1-lh1` is getting deployed and running properly with Longhorn-master `03/24/2021`

**Comment by AlaaAttya** [comment]
i have faced the same issue and worked by downgrading to `longhornio/csi-resizer:v0.5.1-lh1`
