### ISSUE TITLE
[BUG] RWX mount share ownership is being reset to user nobody

### ISSUE THREAD

**Issue by hendra-2020** [longhorn/longhorn#2357]
**Describe the bug**
I created a few RWX share volumes and mounted them on pods with the following securityContext:

        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: "OnRootMismatch"

The first time pod is created, the share volume has correct ownership of root:root. After around 30min, the ownership of share and all files within it changed to nobody:4294967294. This always happens to all my RWX share across several pods. There's no extra error log in share-manager log.

**To Reproduce**
1. Create RWX volume
2. Mount on pod with root fsgroup
3. Wait around 30min
4. All ownership changed to nobody

**Expected behavior**
Ownership of share and all files within in should not changed to nobody.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.
[ganesha.log](https://github.com/longhorn/longhorn/files/6148830/ganesha.log)

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.
[longhorn-support-bundle_799133ef-1954-4bd5-a1c5-bd40d5c61c5f_2021-03-16T12-24-29Z.zip](https://github.com/longhorn/longhorn/files/6148883/longhorn-support-bundle_799133ef-1954-4bd5-a1c5-bd40d5c61c5f_2021-03-16T12-24-29Z.zip)

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2 1.20.4+rke2r1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version: Ubuntu 20.04.2
   - CPU per node: 32
   - Memory per node: 252GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 10Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 11

**Additional context**

**Comment by cclhsu** [comment]
Currently, Longhorn workload do not change the mount share ownership   Is possible that you have workload in cluster done it?  Can you share the manifests used to mount RWX volume?

**Comment by joshimoo** [comment]
We currently do not squash any permissions see https://github.com/longhorn/longhorn-share-manager/blob/master/pkg/server/nfs/export.go#L159

As such when the pod runs as root it should have the correct permissions, it seems interesting that this happens after 30 minutes, anything that could be the cause of this? i.e. security software, application workloads?

**Comment by hendra-2020** [comment]
I have initcontainer which sets volume ownership to root [slurm-dp.txt](https://github.com/longhorn/longhorn/files/6155333/slurm-dp.txt). However it baffles me why after some time the ownership goes back to nobody. This happens across multiple RWX shares running different workloads, so almost for certain not the workloads causing this. The OS is also basic ubuntu 20.04.2 with no security software installed.

If I don't use initcontainer, the volume is mounted with ownership nobody. I expect fsGroupChangePolicy: "OnRootMismatch" with fsGroup: 0 would set the ownership, but I guess this doesn't happen for RWX volume. When I manually run 'chown -R root.root' on the volume, still around 30m later, ownership changes back to nobody 
![Screenshot_2021-03-17_14-13-57](https://user-images.githubusercontent.com/64948832/111451849-4e2f5380-872b-11eb-9dee-f9d5be6a1076.png)

I'm also running kernel nfs server on the host, but don't expect this would cause issues.

**Comment by joshimoo** [comment]
@hendra-2020 that baffles me as well, are all your pods that use this volume running as root?
Can you check the ownership + permissions inside of the share-manager-<volume-name> pod.
`ls -l /export/<volume-name>`

**Comment by hendra-2020** [comment]
My other pods are using other RWX volumes, but they all exhibit this behaviour. In the share-manager-pod, ownership are all root:

bash-5.0# ls -l /export/pvc-623485af-9a5c-4269-b42d-3a7de4602c02/
total 25
-r--r--r-- 1 root root   101 Mar  3 09:55 acct_gather.conf
-r--r--r-- 1 root root   262 Mar  3 09:55 cgroup.conf
-r--r--r-- 1 root root    90 Mar  3 09:55 cgroup_allowed_devices_file.conf
-r--r--r-- 1 root root    16 Mar  9 15:43 gres.conf
-rw-r--r-- 1 root root  1975 Mar  9 12:38 job_submit.lua
lrwxrwxrwx 1 root root    40 Mar 17 09:35 job_submit.lua.example -> /CM/opt/slurm/etc/job_submit.lua.example
drwx------ 2 root root 12288 Mar  3 09:54 lost+found
-r--r--r-- 1 root root   572 Mar 12 10:46 nodes.conf
-r--r--r-- 1 root root   638 Mar  3 09:55 nodes.conf.example
-r--r--r-- 1 root root  3734 Mar  9 15:49 slurm.conf
lrwxrwxrwx 1 root root    31 Mar 17 09:35 slurmdbd.conf -> /CM/opt/slurm/etc/slurmdbd.conf
-r--r--r-- 1 root root    42 Mar 10 06:23 topology.conf
bash-5.0#

**Comment by PhanLe1010** [comment]
@hendra-2020  You are correct that the `fsGroup` setting doesn't work for RWX volume. From Kubernetes source code: https://github.com/kubernetes/kubernetes/blob/e87da0bd6e03ec3fea7933c4b5263d151aafd07c/pkg/volume/csi/csi_mounter.go#L435

**Comment by innobead** [comment]
It seems related to https://github.com/nfs-ganesha/nfs-ganesha/issues/695#issuecomment-800300339.

The suggestion we probably can take, https://github.com/nfs-ganesha/nfs-ganesha/issues/514

**Comment by joshimoo** [comment]
@innobead using only numeric id's is a good change, can you assign someone to make the update this way they get to go through the whole share-manager update process, since I am currently the only one that has done that.
If the person has any questions, I will help :)

This can be added to the NFSV4 block here:
https://github.com/longhorn/longhorn-share-manager/blob/master/pkg/server/nfs/nfs_server.go#L37-L44

```
NFSV4
{
    Only_Numeric_Owners = true;
}
```

**Comment by hendra-2020** [comment]
@innobead This will likely help. I have the following logs (appearing around every 10m) in the server where my workload pods are running:

Mar 19 11:01:07 slave-sys1 nfsidmap[2607242]: nss_getpwnam: name 'root@localdomain' does not map into domain 'lan'
Mar 19 11:11:47 slave-sys1 nfsidmap[2668880]: nss_getpwnam: name 'root@localdomain' does not map into domain 'lan'
Mar 19 11:22:47 slave-sys1 nfsidmap[2732160]: nss_getpwnam: name 'root@localdomain' does not map into domain 'lan'

So, I tried to set domain to localdomain in the server and started rpc.idmapd. All the files which had user nobody across all RWX shares in all workload pods running on that server automatically switched back to user root.

**Comment by innobead** [comment]
> @innobead This will likely help. I have the following logs (appearing around every 10m) in the server where my workload pods are running:
> 
> Mar 19 11:01:07 slave-sys1 nfsidmap[2607242]: nss_getpwnam: name 'root@localdomain' does not map into domain 'lan'
> Mar 19 11:11:47 slave-sys1 nfsidmap[2668880]: nss_getpwnam: name 'root@localdomain' does not map into domain 'lan'
> Mar 19 11:22:47 slave-sys1 nfsidmap[2732160]: nss_getpwnam: name 'root@localdomain' does not map into domain 'lan'
> 
> So, I tried to set domain to localdomain in the server's /etc/idmapd.conf and started rpc.idmapd. All the files which had user nobody across all RWX shares in all workload pods running on that server automatically switched back to user root.

@hendra-2020 thanks for the confirmation :+1: 

This should be tackled, otherwise, the consumer container needs to have the correct user ID mapping.

**Comment by c3y1huang** [comment]
Looking at the previous discussion it seems this issue is caused by a mismatch of the Domain in /etc/idmapd.conf between client and server.  In share-manager NFSv4 domain is set to `localdomain` by default which is included as part of the lookup string. A mismatch between `Domain = localdomain` and `Domain = lan` caused mapping incomplete and hence file permissions to fall back to use `nobody:nogroup`.
```
Nobody-User = nobody
Nobody-Group = nogroup
```

Since Longhorn is not responsible for the host etc/idmapd.conf and as @hendra-2020 confirmed, by `set domain to localdomain in the server's /etc/idmapd.conf` already resolved this issue.

**Comment by c3y1huang** [comment]
Also from the discussion, noticed that the shared directory seems not rw accessible when the consumer pod is running as none-root user. This could be related to the suggested fix in https://github.com/longhorn/longhorn/issues/2357#issuecomment-802718167. I will create a new issue for that.

**Comment by c3y1huang** [comment]
@hendra-2020 thank you for the info about the cluster domain. We will look more into this.

**Comment by c3y1huang** [comment]
@hendra-2020 could you provide the server's /etc/idmapd.conf before you updated it?

**Comment by hendra-2020** [comment]
@c3y1huang The pod uses the standard volumeMounts using longhorn RWX through PVC accessMode ReadWriteMany. When the pod is started and share is just mounted, the ownership is corrent (root:root). However, as the host log shows, there is a background process nfsidmap (in the pod/host) for nfs4 mounts which regularly every 10m trying to check ownership (this happens even if rpc.idmapd is not running; this is what I meant by automatic) and reset the ownership after 30m.

The following is the stock /etc/idmapd.conf which comes with ubuntu 20.04:

[General]

Verbosity = 0
Pipefs-Directory = /run/rpc_pipefs
# set your own domain here, if it differs from FQDN minus hostname
# Domain = localdomain

[Mapping]

Nobody-User = nobody
Nobody-Group = nogroup

**Comment by c3y1huang** [comment]
The /etc/idmapd.conf looks good. 
Another scenario is when the domain name is resolving to the loopback.
```
root@ip-172-30-0-78:~# hostname -f
ip-172-30-0-78.lan

root@ip-172-30-0-78:~# cat /etc/hosts
#127.0.0.1 localhost
127.0.0.1 ip-172-30-0-78.lan ip-172-30-0-78

/ # ls -l /data
total 16
-rw-r--r--    1 nobody   42949672         0 Mar 30 00:45 123
drwx------    2 nobody   42949672     16384 Mar 30 00:42 lost+found
```
Could you check if this is your case?

**Comment by hendra-2020** [comment]
@c3y1huang This is not my case, the server is resolving to its own proper IP, not localhost.

**Comment by c3y1huang** [comment]
According to the idmapd, the Domain needs to be the FQDN minus hostname.
Could you confirm `hostname --fqdn` returned something like `xxx.lan`?

**Comment by hendra-2020** [comment]
Yes, this is correct, the name returned is xxx.lan.

**Comment by c3y1huang** [comment]
Thank you for confirming @hendra-2020 .

To Reproduce:
1. Setup cluster hosts FQDN in /etc/hosts
```
root@ip-172-30-0-139:/home/ubuntu# cat /etc/hosts
127.0.0.1 localhost
54.255.224.72 ip-172-30-0-139.lan ip-172-30-0-139

root@ip-172-30-0-139:/home/ubuntu# hostname
ip-172-30-0-139

root@ip-172-30-0-139:/home/ubuntu# hostname -f
ip-172-30-0-139.lan
```
2. Deploy pod with rwx pvc.
```
root@ip-172-30-0-139:/home/ubuntu# kubectl exec -it rwx-test-2pml2 -- ls -l /data
total 16
drwx------    2 nobody   42949672     16384 Mar 31 04:16 lost+found
```

To Resolve:
1. Uncomment or add `Domain = localdomain` in /etc/idmapd.conf on all cluster hosts.
```
root@ip-172-30-0-139:~# cat /etc/idmapd.conf 
[General]

Verbosity = 0
Pipefs-Directory = /run/rpc_pipefs
# set your own domain here, if it differs from FQDN minus hostname
Domain = localdomain

[Mapping]

Nobody-User = nobody
Nobody-Group = nogroup
```
2. Delete, and re-create rwx resource stack (pvc + pod).
```
root@ip-172-30-0-139:/home/ubuntu# kubectl exec -it volume-test -- ls -l /data
total 16
drwx------    2 root     root         16384 Mar 31 04:42 lost+found
```

**Comment by joshimoo** [comment]
@innobead is it okay if @c3y1huang does the share manager update for the only numeric id fix for v1.1.1
There is also a community PR to chmod the export folder, here https://github.com/longhorn/longhorn-share-manager/pull/9
Not sure if that actually will help since we still create the per volume pvc folder as root.

**Comment by c3y1huang** [comment]
Waiting for the share manager image update. /cc @joshimoo

**Comment by khushboo-rancher** [comment]
Verified with Longhorn v1.1.1-rc1

Validation - **Pass**

I was able to reproduce the problem with Longhorn v1.1.1-preview1. Followed the manual test steps to validate it, it worked fine with Longhorn v1.1.1-rc1. 
Validated this with upgraded and newly installed Longhorn v1.1.1-rc1. The RWO/RWX volume ownership doesn't get reset.
