### ISSUE TITLE
[Question] There is a way to fix problem (waiting with nfs server start)?

### ISSUE THREAD

**Issue by LuizBuffa25** [longhorn/longhorn#2366]
**Question**
Created a volume, a pv/pvc and run a POD.
Normally the POD attaches the volume successfully, but sometimes (after reboot or on new installations) the volume stuck on attaching... 
Check the share-manager-my-volume logs and see this spawn message:
time="2021-03-16T20:11:26Z" level=warning msg="waiting with nfs server start, volume is not attached" volume=my-volume
time="2021-03-16T20:11:31Z" level=warning msg="waiting with nfs server start, volume is not attached" volume=my-volume

there is a way to fix it?

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version:
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**

**Comment by cclhsu** [comment]
HI! Can you provide Environment information and attach the support bundle for us to investigate? Thanks!

**Comment by LuizBuffa25** [comment]
I found the problem, it is on my NFS, you can close this issue.
Thanks!

**Comment by joshimoo** [comment]
@LuizBuffa25 mind sharing what the problem was, so if someone else encounters this issue they would find this thread :)

**Comment by LuizBuffa25** [comment]
Only saw the message now, sorry.
I was testing in a new VM with no NFS install. If I am not mistaken, I install nfs-common and everything works.
