### ISSUE TITLE
[UI] Update the github issue link

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2373]
**Is your feature request related to a problem? Please describe.**
The [issue template](https://github.com/longhorn/longhorn/issues/new?title=*Summarize%20your%20issue%20here*&body=*Describe%20your%20issue%20here*%0A%0A---%0AVersion%3A%20`v1.1.0`)  when a user opens the GitHub issue from Longhorn UI currently doesn't contain the evn info.

<img width="400" alt="Screen Shot 2021-03-17 at 12 08 15 PM" src="https://user-images.githubusercontent.com/22139961/111549010-bfc1ce80-8738-11eb-8b93-6c0f6e577f3d.png">

**Describe the solution you'd like**
Just point the user to the selecting issue template page by replacing [this line](https://github.com/longhorn/longhorn-ui/blob/b8b765a832614e2d26c4a6480be17be36a2912fb/src/components/Layout/Footer.js#L17) by 
```
const issueHref = `https://github.com/longhorn/longhorn/issues/new/choose`
```

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master `3638eb7`

Validation - **Pass**
