### ISSUE TITLE
[BUG] UI issue: Save button is not working when we set a label "node.longhorn.io/create-default-disk=true" to a node in the Longhorn UI

### ISSUE THREAD

**Issue by corend** [longhorn/longhorn#2376]
**Describe the bug**
In the UI of Longhorn, when we select a node configuration and add a Label "node.longhorn.io/create-default-disk=true" to be able to deploy Longhorn on this new node (https://longhorn.io/docs/1.1.0/references/settings/#create-default-disk-on-labeled-nodes) this is not possible to save the data: when you click on save, nothing happens.

**To Reproduce**
1. Go to 'Longhorn UI admin panel'
2. Click on 'a new node and edit the configuration'
3. Perform 'add label "node.longhorn.io/create-default-disk=true"' and click on Save button
4. Nothing happens: no save and no redirection, whatever is the browser (I tried with the last version of Chrome (macos and Windows), Firefox, Vivaldi, Edge...)

**Expected behavior**
Should be able to save the new configuration by just adding a label to a node.

**Log**
No logs.

**Environment:**
 - Longhorn version: latest
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Public Cloud
   - Number of management node in the cluster: 2
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: Ubuntu
   - CPU per node: 16 cores (4Ghz)
   - Memory per node: 64 Go
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 10Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Public cloud
 - Number of Longhorn volumes in the cluster: 1

**Comment by khushboo-rancher** [comment]
@corend I'm not sure if I understood the reproduction steps here, are you trying to add `Node Tag` to the node using Longhorn UI?

**Comment by PhanLe1010** [comment]
For more details please see https://longhorn.io/docs/1.1.0/advanced-resources/default-disk-and-node-config/

**Comment by corend** [comment]
Oh god... I was tired when I did that... sorry indeed we can close this... this is a node annotation I tried to add in the UI of Longhorn via the tag/label field of the node. This is indeed confusing or I didn't understand the goal of this in this UI, anyway this is directly on the node that I have to add this annotation... Tired period, sorry :)
