### ISSUE TITLE
[FEATURE][infra] allow pytest to run test repeatedly

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2379]
**Is your feature request related to a problem? Please describe.**
Consider the ability to run specified tests repeatedly in a single build. Useful for verifying not always reproducible (unstable) cases. 

**Describe the solution you'd like**
Add pytest option.

**Describe alternatives you've considered**
`none`

**Additional context**
`none`

**Comment by innobead** [comment]
cc @meldafrawi
