### ISSUE TITLE
[Question] why getting too many snapshots

### ISSUE THREAD

**Issue by ElisaMeng** [longhorn/longhorn#2383]
**Question**

I have a volume running for about a week, and I have recurrent snap job on as below: 

```
apiVersion: longhorn.io/v1beta1
kind: Volume
metadata:
  creationTimestamp: "2021-03-11T13:18:06Z"
  finalizers:
  - longhorn.io
  generation: 6
  labels:
    longhornvolume: pvc-f7d90583-fddb-4f66-a7c3-b0bd67f7d36e
  name: pvc-f7d90583-fddb-4f66-a7c3-b0bd67f7d36e
  namespace: longhorn-system
  resourceVersion: "387248973"
  selfLink: /apis/longhorn.io/v1beta1/namespaces/longhorn-system/volumes/pvc-f7d90583-fddb-4f66-a7c3-b0bd67f7d36e
  uid: 0ed1ee75-55fc-45a8-b9f2-1d294e3e68f5
spec:
  Standby: false
  accessMode: rwo
  baseImage: ""
  dataLocality: disabled
  disableFrontend: false
  diskSelector: null
  engineImage: longhornio/longhorn-engine:v1.1.0
  fromBackup: ""
  frontend: blockdev
  lastAttachedBy: ""
  nodeID: stornode1
  nodeSelector: null
  numberOfReplicas: 3
  recurringJobs:
  - cron: 0 3 * * 6
    labels: null
    name: snap
    retain: 3
    task: snapshot
  revisionCounterDisabled: false
  size: "200007483392"
  staleReplicaTimeout: 2880
status:
  actualSize: 4799197184
  conditions:
    restore:
      lastProbeTime: ""
      lastTransitionTime: "2021-03-11T13:18:07Z"
      message: ""
      reason: ""
      status: "False"
      type: restore
    scheduled:
      lastProbeTime: ""
      lastTransitionTime: "2021-03-11T13:18:07Z"
      message: ""
      reason: ""
      status: "True"
      type: scheduled
    toomanysnapshots:
      lastProbeTime: ""
      lastTransitionTime: "2021-03-17T06:19:41Z"
      message: Snapshots count is 249 over the warning threshold 100
      reason: TooManySnapshots
      status: "True"
      type: toomanysnapshots
  currentImage: longhornio/longhorn-engine:v1.1.0
  currentNodeID: stornode1
  expansionRequired: false
  frontendDisabled: false
  isStandby: false
  kubernetesStatus:
    lastPVCRefAt: ""
    lastPodRefAt: ""
    namespace: test2
    pvName: pvc-f7d90583-fddb-4f66-a7c3-b0bd67f7d36e
    pvStatus: Bound
    pvcName: pvc-longhorn-1615468664-0-d0
    workloadsStatus:
    - podName: 1615468664-0
      podStatus: Running
      workloadName: ""
      workloadType: ""
  lastBackup: ""
  lastBackupAt: ""
  lastDegradedAt: "2021-03-16T21:17:02Z"
  ownerID: stornode1
  pendingNodeID: ""
  remountRequestedAt: ""
  restoreInitiated: false
  restoreRequired: false
  robustness: degraded
  shareEndpoint: ""
  shareState: ""
  state: attached

```

Question, why I have so many snapshots? why it was not pure via recurrent job?

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version: 1.19
 - Node config
   - OS type and version: k3os
   - CPU per node: 24
   - Memory per node: 128G
   - Disk type: ssd
   - Network bandwidth and latency between the nodes: 10G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal 

**Additional context**

**Comment by c3y1huang** [comment]
@ElisaMeng thanks for reporting. 

Longhorn only keeps the retained number and cleans up the snapshots with the same label. From the manifest, `labels: null` is set in recurringJobs, therefore in your situation, I think Longhorn received an empty list of snapshots and doesn't know what to clean up.

https://github.com/longhorn/longhorn-manager/blob/master/app/volume.go#L419-L422

**Comment by ElisaMeng** [comment]
@c3y1huang thanks. Good to know. But as you see, the volume only created for a week. The job runs weekly, the volume already have more 249 snapshots. What else is missing?

**Comment by c3y1huang** [comment]
@ElisaMeng sorry missed that part, that does look weird. Could you provide a support bundle?

**Comment by ElisaMeng** [comment]
it seems not telling that much. 

```
kubectl -n longhorn-system get  cronjob | grep d36e
pvc-f7d90583-fddb-4f66-a7c3-b0bd67f7d36e-snap-c       0 3 * * 6    False     0        6d19h           8d


kubectl -n longhorn-system describe cronjob pvc-f7d90583-fddb-4f66-a7c3-b0bd67f7d36e-snap-c
Name:                          pvc-f7d90583-fddb-4f66-a7c3-b0bd67f7d36e-snap-c
Namespace:                     longhorn-system
Labels:                        longhornvolume=pvc-f7d90583-fddb-4f66-a7c3-b0bd67f7d36e
Annotations:                   longhorn.io/last-applied-cronjob-spec:
                                 {"metadata":{"name":"pvc-f7d90583-fddb-4f66-a7c3-b0bd67f7d36e-snap-c","namespace":"longhorn-system","creationTimestamp":null,"ownerReferen...
Schedule:                      0 3 * * 6
Concurrency Policy:            Forbid
Suspend:                       False
Successful Job History Limit:  1
Failed Job History Limit:      1
Starting Deadline Seconds:     <unset>
Selector:                      <unset>
Parallelism:                   <unset>
Completions:                   <unset>
Pod Template:
  Labels:           <none>
  Service Account:  longhorn-service-account
  Containers:
   pvc-f7d90583-fddb-4f66-a7c3-b0bd67f7d36e-snap-c:
    Image:      longhornio/longhorn-manager:v1.1.0
    Port:       <none>
    Host Port:  <none>
    Command:
      longhorn-manager
      -d
      snapshot
      pvc-f7d90583-fddb-4f66-a7c3-b0bd67f7d36e
      --manager-url
      http://longhorn-backend:9500/v1
      --snapshot-name
      snap
      --labels
      RecurringJob=snap
      --retain
      3
    Environment:
      POD_NAMESPACE:   (v1:metadata.namespace)
    Mounts:
      /var/lib/longhorn/engine-binaries/ from engine-binaries (rw)
  Volumes:
   engine-binaries:
    Type:            HostPath (bare host directory volume)
    Path:            /var/lib/longhorn/engine-binaries/
    HostPathType:    
Last Schedule Time:  Sat, 13 Mar 2021 03:00:00 +0800
Active Jobs:         <none>
Events:              <none>

```

**Comment by c3y1huang** [comment]
@ElisaMeng, thanks,  was just confirming the last recurring job schedule time.
Can you see when did the flooding of snapshots started? Did it happen before or after the recurring job got scheduled?

Would be good if you can provide the support bundle so we get more info and logs.

**Comment by ElisaMeng** [comment]
It is hundreds MBs of support bundle. :( May you instruct me how to collect relevant logs instead?

**Comment by ElisaMeng** [comment]
BTW, I don't see how to set a label for snapshot in UI. it seems not possible, but possible for backup, do you know why?

**Comment by c3y1huang** [comment]
> It is hundreds MBs of support bundle. :( May you instruct me how to collect relevant logs instead?

You look for and collect logs on:
1. The manager logs.
2. Anything triggered the unexpected snapshot to start?


> BTW, I don't see how to set a label for snapshot in UI. it seems not possible, but possible for backup, do you know why?

Sorry, I think I've drowned to conclusions too quickly without fully understanding your context. AFAIK If you are using UI then the label should automatically applied,
```
kubectl -n longhorn-system get engine -o="jsonpath={.items[*].status.snapshots}"
```

**Comment by ElisaMeng** [comment]
@c3y1huang i probably find the root cause. I have a disk is full 100% used. For some reason, longhorn believe there is still space on the disk. It keep trying to rebuild replica on it, and failed with "No space left on the device", and the ends up in a lot of snaps.  

I delete some failed replica on the disk, it then back to function again.

**Comment by c3y1huang** [comment]
Possible also relate to https://github.com/longhorn/longhorn/issues/2029

**Comment by jenting** [comment]
Could you please provide the longhorm-manager and instance-manager Pods log, we'd like to see did Longhorn detects the disk is full 100% used and skips rebuilding replica on it?

**Comment by ElisaMeng** [comment]
sorry, i did not see this. i think everything was being erased since i have re-installed longhorn.

**Comment by jenting** [comment]
> @c3y1huang i probably find the root cause. I have a disk is full 100% used. For some reason, longhorn believe there is still space on the disk. It keep trying to rebuild replica on it, and failed with "No space left on the device", and the ends up in a lot of snaps.
> 
> I delete some failed replica on the disk, it then back to function again.

I'd prefer to close the issue because the function back again after the CPU resource is enough.
