### ISSUE TITLE
[Question] Single node cluster, node drain/reboot issue.

### ISSUE THREAD

**Issue by LuizBuffa25** [longhorn/longhorn#2385]
**Question**
Only have 1 node with 2 volumes and 1 replica for each.
When I reboot, the machine gets stuck on reboot process and block my SSH access because of that.
I found a similar issue https://github.com/longhorn/longhorn/issues/1024
 Check my machine log when it get stuck:
 4459.424724] sd 3:0:0:1: [sdb] tag#49 timing out command, waited 360s
[ 4459.426076] blk_update_request: I/O error, dev sdb, sector 367011201 op 0x1:(WRITE) flags 0x21800 phys_seg 2 prio class 0
[ 4459.428170] XFS (sdb): log I/O error -5
[ 4459.430287] XFS (sdb): Log I/O Error Detected. Shutting down filesystem
[ 4459.432377] XFS (sdb): Please unmount the filesystem and rectify the problem(s)
[ 4459.434396] sd 3:0:0:1: [sdb] tag#51 timing out command, waited 180s
[ 4459.436177] blk_update_request: I/O error, dev sdb, sector 204672 op 0x1:(WRITE) flags 0x1000 phys_seg 4 prio class 0
[ 4459.480058] sd 3:0:0:1: [sdb] tag#54 timing out command, waited 180s
[ 4459.481621] blk_update_request: I/O error, dev sdb, sector 183500896 op 0x1:(WRITE) flags 0x1000 phys_seg 4 prio class 0
 M[K[    [0;31m*[0;1;31m*[0m] A stop job is running for Monitorinï¿½ï¿½ï¿½ss polling (10min 46s / 10min 47s)
M[K[     [0;31m*[0m] A stop job is running for Monitorinï¿½ï¿½ï¿½ss polling (10min 46s / 10min 47s)
M[K[    [0;31m*[0;1;31m*[0m] A stop job is running for Monitorinï¿½ï¿½ï¿½ss polling (10min 47s / 10min 47s)
M[K[   [0;31m*[0;1;31m*[0m[0;31m*[0m] A stop job is running for Monitorinï¿½ï¿½ï¿½ss polling (10min 47s / 10min 47s)
M[K[[0;32m  OK  [0m] Stopped [0;1;39mMonitoring of LVM2ï¿½ï¿½ï¿½ dmeventd or progress polling[0m.
[K[[0;32m  OK  [0m] Reached target [0;1;39mShutdown[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mFinal Step[0m.
[[0;32m  OK  [0m] Finished [0;1;39mReboot[0m.
[[0;32m  OK  [0m] Reached target [0;1;39mReboot[0m.
[ 4769.902836] systemd-shutdown[1]: Syncing filesystems and block devices - timed out, issuing SIGKILL to PID 262475.
[ 4779.913939] systemd-shutdown[1]: Waiting for process: umount, mysqld, (sd-sync), lvm
[ 4819.572123] sd 3:0:0:1: [sdb] tag#46 timing out command, waited 360s
[ 4819.574579] blk_update_request: I/O error, dev sdb, sector 0 op 0x1:(WRITE) flags 0x800 phys_seg 0 prio class 0
[ 4869.914424] systemd-shutdown[1]: Waiting for process: mysqld, (sd-sync), lvm
[ 4980.087300] shutdown[1]: Syncing filesystems and block devices - timed out, issuing SIGKILL to PID 262487.
[ 4990.106233] shutdown[1]: Waiting for process: lvm, mysqld, (sd-sync), (sd-sync)
[ 5080.109601] shutdown[1]: Waiting for process: lvm, mysqld, (sd-sync), (sd-sync)
[ 5160.154916] sd-umoun[262530]: Failed to unmount /oldroot/run/lock: Device or resource busy
[ 5160.158099] sd-remou[262531]: Failed to remount '/oldroot' read-only: Device or resource busy
[ 5160.161240] sd-umoun[262532]: Failed to unmount /oldroot: Device or resource busy
[ 5160.165708] sd-umoun[262533]: Failed to unmount /oldroot/run: Device or resource busy
[ 5160.169060] sd-umoun[262534]: Failed to unmount /oldroot/dev: Device or resource busy
[ 5160.182087] shutdown[1]: Failed to finalize  file systems, ignoring
[ 5190.183399] shutdown[1]: Syncing filesystems and block devices - timed out, issuing SIGKILL to PID 262541.
 

Log stop there /\
My machine is in running status but SSH access is not allowed

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version:
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**

**Comment by LuizBuffa25** [comment]
Update:
The problem happens after a backup was taken.

If I just reboot the machine it works, but if I perform a backup, wait until it finished, and then reboot, I got the error above.

**Comment by LuizBuffa25** [comment]
Fixed.
Just add: 
allow-node-drain-with-last-healthy-replica          true

Since I have only one replica, I need to set this variable to true.

You may close this issue, thanks.

**Comment by LuizBuffa25** [comment]
Actually, After I change allow-node-drain-with-last-healthy-replica to true, another bug appears on longhorn-csi-plugin:

time="2021-03-19T19:04:00Z" level=info msg="CSI Driver: driver.longhorn.io csiVersion: 0.3.0, manager URL http://longhorn-backend:9500/v1"
time="2021-03-19T19:04:10Z" level=fatal msg="Error starting CSI manager: Failed to initialize Longhorn API client: Get \"http://longhorn-backend:9500/v1\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

**Comment by jenting** [comment]
> Actually, After I changed allow-node-drain-with-last-healthy-replica to true, another bug appears after reboot node, this time on longhorn-csi-plugin:
> 
> time="2021-03-19T19:04:00Z" level=info msg="CSI Driver: driver.longhorn.io csiVersion: 0.3.0, manager URL http://longhorn-backend:9500/v1"
> time="2021-03-19T19:04:10Z" level=fatal msg="Error starting CSI manager: Failed to initialize Longhorn API client: Get "[http://longhorn-backend:9500/v1\](http://longhorn-backend:9500/v1%5C)": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

Since you're using a single node, after reboot, it has to wait for Longhorn-system to become ready so the endpoint `longhorn-backend` is available from Kubernetes service to longhorn-manager Pod.
- Is this issue keeps happening after a period of time?
- Is the longhorn-manager comes back successfully? 
- Could you please run `kubectl exec -it <longhorn-ui-pod> -n longhorn-system -- /bin/bash` and run `curl -XGET http://longhorn-backend:9500/v1` is reachable?

**Comment by LuizBuffa25** [comment]
After I waited for longhorn-backend and manager, everything is working.

You may close this issue, thank you.
