### ISSUE TITLE
[BUG] Engineimage stuck in deploying state

### ISSUE THREAD

**Issue by npawelek** [longhorn/longhorn#2386]
**Describe the bug**
I recently replaced the control plane nodes by deleting and re-joining via `kubeadm join`. These are Raspberry Pi nodes on eMMC storage, so the join process is a bit slow. I also noted a delay waiting for etcd steps to fully complete. While the etcd steps were pending, the nodes were added to longhorn before the `NoSchedule` taints were applied to nodes. This delay caused the daemonset to deploy pods to these nodes. Subsequently, there appears to be some logic with the manager/engineimage that if the number doesn't match, the engineimage drops to a deploying state. In turn, this prevents any volume detach/attach.

The Kubernetes daemonset construct doesn't appear to de-schedule workloads that are tainted with `node-role.kubernetes.io/master:NoSchedule`. However, the issue wasn't immediately understood, just that the longhorn-manager daemonset numbers didn't match the actual deployed numbers, and I was unable to detach and attach volumes.

**To Reproduce**
1. Delete and re-bootstrap control plane node.
2. Insert delay before taint is applied (or un-taint and re-taint), effectively mimicking the behavior.
3. EngineImage drops to a deploying state.

**Expected behavior**
EngineImage properly reflects nodes in Longhorn.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: v1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Kubernetes 1.20.1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 7
 - Node config (mixed architecture of RPi and NUC; only storage node specs included)
   - OS type and version: Ubuntu 20.04.2 LTS
   - CPU per node: 4
   - Memory per node: 32GB
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 1GbE
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 19

**Additional context**
Once I realized what was happening, I resolved the issue by deleting the pod workloads from the control plane nodes and deleting the node from `nodes.longhorn.io`. It would be nice to have some documentation/troubleshooting steps around how this process works.

**Comment by joshimoo** [comment]
cc @PhanLe1010 can you link to your issue which we fixed in v1.1.1

**Comment by PhanLe1010** [comment]
Yeah, we have fixed this problem at https://github.com/longhorn/longhorn/issues/2081
The fix will be available in the next release, Longhorn v1.1.1

**Comment by npawelek** [comment]
Perfect. Thanks for confirming!
