### ISSUE TITLE
[ENHANCEMENT] update CSI components to newest versions

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2388]
Since the snapshotter is GA, we can look into where the distributions are at now.
There are also changes on the resizer, we should look into and update this one especially.
A good time for this update of all CSI components would probably be 1.2/1.3 since we are running some pretty old components targetting csi 1.1 we can update to target csi 1.2 and remove some of the old code that checks for kubernetes versions that are no longer supported, our current kubernetes minVersion is >= 1.16

**Comment by jenting** [comment]
I think this issue could be closed. cc @innobead
