### ISSUE TITLE
[Question] There is a way to perform a full backup (not a incremental)? What happens when reach retain number?

### ISSUE THREAD

**Issue by LuizBuffa25** [longhorn/longhorn#2393]
**Question**

I have 2 scenarios:
Scenario 1)  
A bucket on s3 that store daily backups from my volumes with retain=30, that backups are executed every day at 00:00H;
Q1: When longhorn performs the 31st backup, what happens with the others?

Scenario 2)
Another bucket on s3 that store a backup that is executed only one  time per month on Sundays;
Q2: I want to know if there is a way to have infinite retain for this backup;
Q3: I Would like that specific backup don't perform an incremental backup, but a full one. For example, My MySQL has 10GB of data, by the end of the year, I would like to have 12 Full backups each one with 10GB.

Thanks!

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version:
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**

**Comment by c3y1huang** [comment]
> Q1: When longhorn performs the 31st backup, what happens with the others?

https://github.com/longhorn/longhorn/issues/2191 might help to answer this question.

> Scenario 2)
> Another bucket on s3 that store a backup that is executed only one time per month on Sundays;
> Q2: I want to know if there is a way to have infinite retain for this backup;

Currently, longhorn restricts the MaxRecurringJobRetain to 50.
https://github.com/longhorn/longhorn/issues/1016

> Q3: I Would like that specific backup don't perform an incremental backup, but a full one. For example, My MySQL has 10GB of data, by the end of the year, I would like to have 12 Full backups each one with 10GB.

Longhorn only supports incremental for snapshots and backups. Do you mind you share the reason why incremental backup doesn't work for you? Would [Disaster Recovery Volumes](https://longhorn.io/docs/1.1.0/snapshots-and-backups/setup-disaster-recovery-volumes/ ) works better for your case?

**Comment by LuizBuffa25** [comment]
Thanks! 
Answering your question: With your explication, incremental backup works for me now. 
You may close this issue.
