### ISSUE TITLE
[BUG] ErrImagePull after install

### ISSUE THREAD

**Issue by mbwmbw1337** [longhorn/longhorn#2395]
**Describe the bug**
k3s (v1.20.4+k3s1) installation on arm raspberry pi 

After installing the error pulling the image. Tried clearing everything and installing it several times
```
k3s kubectl logs -n longhorn-system longhorn-manager-dhv6m
Error from server (BadRequest): container "longhorn-manager" in pod "longhorn-manager-dhv6m" is waiting to start: image can't be pulled

longhorn-system        pod/longhorn-driver-deployer-666c84fbb7-kw5p2    0/1     Init:ErrImagePull   0          51s
longhorn-system        pod/longhorn-manager-2dnxb                       0/1     ImagePullBackOff    0          52s
longhorn-system        pod/longhorn-manager-2wb4j                       0/1     ErrImagePull        0          47s
longhorn-system        pod/longhorn-manager-7pzhf                       0/1     ErrImagePull        0          47s
longhorn-system        pod/longhorn-manager-7wrd4                       0/1     ImagePullBackOff    0          50s
longhorn-system        pod/longhorn-manager-7x5vd                       0/1     ErrImagePull        0          51s
longhorn-system        pod/longhorn-manager-88swq                       0/1     ImagePullBackOff    0          47s
longhorn-system        pod/longhorn-manager-9j8gn                       0/1     ErrImagePull        0          49s
longhorn-system        pod/longhorn-manager-9mrhx                       0/1     ErrImagePull        0          47s
longhorn-system        pod/longhorn-manager-b6f6x                       0/1     ErrImagePull        0          47s
longhorn-system        pod/longhorn-manager-dhv6m                       0/1     ErrImagePull        0          47s
longhorn-system        pod/longhorn-manager-dtlst                       0/1     ErrImagePull        0          47s
longhorn-system        pod/longhorn-manager-g8q7g                       0/1     ImagePullBackOff    0          51s
longhorn-system        pod/longhorn-manager-jxpzm                       0/1     ErrImagePull        0          49s
longhorn-system        pod/longhorn-manager-jz78x                       0/1     ErrImagePull        0          47s
longhorn-system        pod/longhorn-manager-jzgrj                       0/1     ErrImagePull        0          49s
longhorn-system        pod/longhorn-manager-k6qfj                       0/1     ErrImagePull        0          49s
longhorn-system        pod/longhorn-manager-kkpl7                       0/1     ImagePullBackOff    0          49s
longhorn-system        pod/longhorn-manager-m2wcd                       0/1     ErrImagePull        0          47s
longhorn-system        pod/longhorn-manager-nn6m4                       0/1     ErrImagePull        0          47s
longhorn-system        pod/longhorn-manager-pcdqb                       0/1     ErrImagePull        0          49s
longhorn-system        pod/longhorn-manager-q546p                       0/1     ErrImagePull        0          50s
longhorn-system        pod/longhorn-manager-qtcbf                       0/1     ErrImagePull        0          50s
longhorn-system        pod/longhorn-manager-r8n6h                       0/1     ImagePullBackOff    0          50s
longhorn-system        pod/longhorn-manager-s2k48                       0/1     ErrImagePull        0          47s
longhorn-system        pod/longhorn-manager-t8llc                       0/1     ErrImagePull        0          49s
longhorn-system        pod/longhorn-manager-x5kbh                       0/1     ErrImagePull        0          49s
longhorn-system        pod/longhorn-ui-5576b69d6d-dkjqx                 0/1     ErrImagePull        0          51s
```

**Comment by c3y1huang** [comment]
Seems like the cluster is having issues getting access to the images.

How are you deploying Longhorn and which version?
Could you do a describe of one of the resources that is having issues with image pulling?
```
kubectl -n longhorn-system get daemonset/longhorn-manager -o json | grep '"image"'
```

**Comment by mbwmbw1337** [comment]
I tried deploying via helm and `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v0.8.0/deploy/longhorn.yaml`

Both resulted in the same issue.

Results of command:
# kubectl -n longhorn-system get daemonset/longhorn-manager -o json | grep '"image"'
                        "image": "longhornio/longhorn-manager:v1.1.0",

**Comment by mbwmbw1337** [comment]
I am running **HypriotOS/armv7** possible I need to manually specify an ARM architecture for the image pull during the installation? How would I do that? I am adding some more logs below.

kubectl api-resources --verbs=list --namespaced -o name \
>    | xargs -n 1 kubectl get --show-kind --ignore-not-found -n longhorn-system

92m         Normal    Pulling             pod/longhorn-uninstall-2mtr6        Pulling image "longhornio/longhorn-manager:v1.1.0"
92m         Warning   Failed              pod/longhorn-uninstall-2mtr6        Failed to pull image "longhornio/longhorn-manager:v1.1.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/longhornio/longhorn-manager:v1.1.0": no match for platform in manifest: not found
92m         Warning   Failed              pod/longhorn-uninstall-2mtr6        Error: ErrImagePull
75m         Normal    Scheduled           pod/longhorn-uninstall-2rvzx        Successfully assigned longhorn-system/longhorn-uninstall-2rvzx to glexia-rpi-c1n23
75m         Normal    Pulling             pod/longhorn-uninstall-2rvzx        Pulling image "longhornio/longhorn-manager:v1.1.0"
75m         Warning   Failed              pod/longhorn-uninstall-2rvzx        Failed to pull image "longhornio/longhorn-manager:v1.1.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/longhornio/longhorn-manager:v1.1.0": no match for platform in manifest: not found
75m         Warning   Failed              pod/longhorn-uninstall-2rvzx        Error: ErrImagePull
116m        Normal    Scheduled           pod/longhorn-uninstall-77hsz        Successfully assigned longhorn-system/longhorn-uninstall-77hsz to glexia-rpi-c1n10
114m        Normal    Pulling             pod/longhorn-uninstall-77hsz        Pulling image "longhornio/longhorn-manager:v1.1.0"
114m        Warning   Failed              pod/longhorn-uninstall-77hsz        Failed to pull image "longhornio/longhorn-manager:v1.1.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/longhornio/longhorn-manager:v1.1.0": no match for platform in manifest: not found
114m        Warning   Failed              pod/longhorn-uninstall-77hsz        Error: ErrImagePull
113m        Normal    BackOff             pod/longhorn-uninstall-77hsz        Back-off pulling image "longhornio/longhorn-manager:v1.1.0"
114m        Warning   Failed              pod/longhorn-uninstall-77hsz        Error: ImagePullBackOff
76m         Normal    Scheduled           pod/longhorn-uninstall-ff5gm        Successfully assigned longhorn-system/longhorn-uninstall-ff5gm to glexia-rpi-c1n24
75m         Normal    Pulling             pod/longhorn-uninstall-ff5gm        Pulling image "longhornio/longhorn-manager:v1.1.0"
75m         Warning   Failed              pod/longhorn-uninstall-ff5gm        Failed to pull image "longhornio/longhorn-manager:v1.1.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/longhornio/longhorn-manager:v1.1.0": no match for platform in manifest: not found
75m         Warning   Failed              pod/longhorn-uninstall-ff5gm        Error: ErrImagePull
76m         Normal    BackOff             pod/longhorn-uninstall-ff5gm        Back-off pulling image "longhornio/longhorn-manager:v1.1.0"
76m         Warning   Failed              pod/longhorn-uninstall-ff5gm        Error: ImagePullBackOff
93m         Normal    Scheduled           pod/longhorn-uninstall-ftzxs        Successfully assigned longhorn-system/longhorn-uninstall-ftzxs to glexia-rpi-c1n13
93m         Normal    Pulling             pod/longhorn-uninstall-ftzxs        Pulling image "longhornio/longhorn-manager:v1.1.0"
92m         Warning   Failed              pod/longhorn-uninstall-ftzxs        Failed to pull image "longhornio/longhorn-manager:v1.1.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/longhornio/longhorn-manager:v1.1.0": no match for platform in manifest: not found
92m         Warning   Failed              pod/longhorn-uninstall-ftzxs        Error: ErrImagePull
93m         Normal    BackOff             pod/longhorn-uninstall-ftzxs        Back-off pulling image "longhornio/longhorn-manager:v1.1.0"
93m         Warning   Failed              pod/longhorn-uninstall-ftzxs        Error: ImagePullBackOff
113m        Normal    Scheduled           pod/longhorn-uninstall-jf9bc        Successfully assigned longhorn-system/longhorn-uninstall-jf9bc to glexia-rpi-c1n9
113m        Normal    Pulling             pod/longhorn-uninstall-jf9bc        Pulling image "longhornio/longhorn-manager:v1.1.0"
113m        Warning   Failed              pod/longhorn-uninstall-jf9bc        Failed to pull image "longhornio/longhorn-manager:v1.1.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/longhornio/longhorn-manager:v1.1.0": no match for platform in manifest: not found
113m        Warning   Failed              pod/longhorn-uninstall-jf9bc        Error: ErrImagePull
113m        Normal    BackOff             pod/longhorn-uninstall-jf9bc        Back-off pulling image "longhornio/longhorn-manager:v1.1.0"
113m        Warning   Failed              pod/longhorn-uninstall-jf9bc        Error: ImagePullBackOff
117m        Normal    Scheduled           pod/longhorn-uninstall-pg8j8        Successfully assigned longhorn-system/longhorn-uninstall-pg8j8 to glexia-rpi-c1n9
117m        Normal    Pulling             pod/longhorn-uninstall-pg8j8        Pulling image "longhornio/longhorn-manager:v1.1.0"
116m        Warning   Failed              pod/longhorn-uninstall-pg8j8        Failed to pull image "longhornio/longhorn-manager:v1.1.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/longhornio/longhorn-manager:v1.1.0": no match for platform in manifest: not found
116m        Warning   Failed              pod/longhorn-uninstall-pg8j8        Error: ErrImagePull
116m        Normal    BackOff             pod/longhorn-uninstall-pg8j8        Back-off pulling image "longhornio/longhorn-manager:v1.1.0"
116m        Warning   Failed              pod/longhorn-uninstall-pg8j8        Error: ImagePullBackOff
92m         Normal    Scheduled           pod/longhorn-uninstall-t5fn7        Successfully assigned longhorn-system/longhorn-uninstall-t5fn7 to glexia-rpi-c1n2
92m         Normal    Pulling             pod/longhorn-uninstall-t5fn7        Pulling image "longhornio/longhorn-manager:v1.1.0"
91m         Warning   Failed              pod/longhorn-uninstall-t5fn7        Failed to pull image "longhornio/longhorn-manager:v1.1.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/longhornio/longhorn-manager:v1.1.0": no match for platform in manifest: not found
91m         Warning   Failed              pod/longhorn-uninstall-t5fn7        Error: ErrImagePull
91m         Normal    BackOff             pod/longhorn-uninstall-t5fn7        Back-off pulling image "longhornio/longhorn-manager:v1.1.0"
91m         Warning   Failed              pod/longhorn-uninstall-t5fn7        Error: ImagePullBackOff
91m         Normal    Scheduled           pod/longhorn-uninstall-xfxht        Successfully assigned longhorn-system/longhorn-uninstall-xfxht to glexia-rpi-c1n9
91m         Normal    Pulling             pod/longhorn-uninstall-xfxht        Pulling image "longhornio/longhorn-manager:v1.1.0"
91m         Warning   Failed              pod/longhorn-uninstall-xfxht        Failed to pull image "longhornio/longhorn-manager:v1.1.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/longhornio/longhorn-manager:v1.1.0": no match for platform in manifest: not found
91m         Warning   Failed              pod/longhorn-uninstall-xfxht        Error: ErrImagePull

**Comment by jenting** [comment]
Currently, we only support amd64 and arm64, there is a feature request #1997 for the armv7 already.

**Comment by mbwmbw1337** [comment]
Thank you. That resolves the issue.

**Comment by Kamforka** [comment]
@jenting I'm also having this issue on raspberry os 2021-03-04 with k3s v1.20.6+k3s1 when installing longhorn v1.1.1

Is there a workaround to to make the longhorn installation successful and functional while the armv7 feature request is not there yet?

**Comment by joshimoo** [comment]
@Kamforka we currently only support ARM64 if you are able you can use an arm64 os like ubuntu for the nodes then longhorn will work correctly. We don't ship armv7 images.
