### ISSUE TITLE
[QUESTION] Volume never become attached

### ISSUE THREAD

**Issue by abennani31** [longhorn/longhorn#2398]
Volume never becomes attached. It still in Attaching/detaching state.

---
[longhorn-support-bundle_9e873963-d075-49ce-b96a-a4bf657b7564_2021-03-23T16-36-51Z.zip](https://github.com/longhorn/longhorn/files/6191407/longhorn-support-bundle_9e873963-d075-49ce-b96a-a4bf657b7564_2021-03-23T16-36-51Z.zip)

Version: `v1.1.0`

**Comment by abennani31** [comment]
Kubernetes bare metal installation. 
Vm: centos 8 stream

**Comment by jenting** [comment]
I saw this error on the volume `pvc-3ca3d243-9e72-49b4-a0c2-93746ff3898e-e-b6a79411`
```
FAIL to discover due to Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm -m discovery -t sendtargets -p 10.24       4.3.5], output , stderr, Failed to connect to bus: No data available\\niscsiadm: can not connect to iSCSI daemon (111)!\\nFailed to connect to bus: No data available\       \niscsiadm: can not connect to iSCSI daemon (111)!\\niscsiadm: Cannot perform discovery. Initiatorname required.\\niscsiadm: Could not perform SendTargets discovery:        could not connect to iscsid\\n, error exit status 20\
```

Could you check the `iscsid` daemon is running on all the nodes?  Ref to https://longhorn.io/docs/1.1.0/deploy/install/#installation-requirements

Also, could you please provide the specific time period and volume name that is in attaching/detaching state?

Thank u.

**Comment by abennani31** [comment]
HI,
I've not started daemon in worker indeed!  In the documentation a saw onlu instructions with yum install and nothing about starting a service.
Thanks for your replay i'ts good now.
Regards
