### ISSUE TITLE
[FEATURE] Add tabular display of the visual snapshots, backups and volume head summary

### ISSUE THREAD

**Issue by immanuelfodor** [longhorn/longhorn#2400]
**Is your feature request related to a problem? Please describe.**
The current display of snapshots & backups & volume head state is very visual but lacks in UX in multiple cases:
- As I searched the issues, I observed that users need to screenshot multiple tooltips when reporting issues to show their current volume state. Examples for snapshot + head state:
  - https://github.com/longhorn/longhorn/issues/478#issuecomment-497078560 + the request for each one: https://github.com/longhorn/longhorn/issues/478#issuecomment-497076378
  - https://github.com/longhorn/longhorn/issues/836#issuecomment-805163562
- I needed to use the dashboard from mobile once and viewing experience there is subpar as hover on touch devices are not supported. You might be lucky and get the info on multiple tap or trying long taps but you might not, the results are inconsistent and not reliable. 

**Describe the solution you'd like**
All the data displayed in the tooltips could be presented in a table below the "linked list" graph display. 

**Describe alternatives you've considered**
The table could be collapsed by default (like the Event Log) to don't take up too much space but can be opened upon click/tap to see all the info. It could also be used for easy screenshotting when reporting issues even with lots of snapshots.

**Additional context**
![image](https://user-images.githubusercontent.com/21174107/112210453-fdcc6000-8c1a-11eb-9dc7-d56ab0daa790.png)

**Comment by jenting** [comment]
@smallteeths any comments or suggestions on it?

**Comment by smallteeths** [comment]
![Jietu20210324-163832](https://user-images.githubusercontent.com/27733391/112280171-afbd6800-8cbf-11eb-9fd6-7c53c6d37c97.jpg)
Can we do this by clicking on the backup icon and adding an options `show info` . pop-up window to display a table with backup/snapshot information?

**Comment by smallteeths** [comment]
Another option is to display it as a Popconfirm component. This way the UI can display multiple backup/snapshot information at the same time as shown in the figure

![Jietu20210324-170009](https://user-images.githubusercontent.com/27733391/112283490-290a8a00-8cc3-11eb-9560-3de756001bea.jpg)

**Comment by immanuelfodor** [comment]
The click on the backup/snapshot icon to show the menu can work on mobile as click=tap. 

What would be great is to not only display the individual snapshot info in the popconfirm but from all the existing ones in one table in the next step. It could highlight the corresponding row of the clicked element to let the user know which is that particular one from where they came. 

Displaying only one item's info doesn't solve all the problems at once, that's why I aim for a unified table view no matter where it's presented (in a popconfirm, below the graph, etc). 

However, the table-in-popconfirm solution seems to be capped by the items that could be displayed at once, or the popconfirm should be huge and/or scrollable, which is also not that great for an overview. In this case the collapsible table-below-graph solution is better than the popconfirm.

**Comment by smallteeths** [comment]
![Jietu20210325-161035](https://user-images.githubusercontent.com/27733391/112440181-f32dda00-8d84-11eb-9ee9-00c2cd483ca7.jpg)

Is it okay to design this way? Would you please check this. @immanuelfodor thanks

**Comment by immanuelfodor** [comment]
This is an absolutely love-able design for the table, thank you!

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master `03/31/2021`

The `Name` column and `ID` columns are same. We can remove repeated info from the table I believe.
<img width="1765" alt="Screen Shot 2021-03-31 at 2 30 11 AM" src="https://user-images.githubusercontent.com/60111667/113056441-6e4e2080-91c9-11eb-882d-66a6690f31d4.png">

**Comment by innobead** [comment]
> Verified with Longhorn-master `03/31/2021`
> 
> The data in the table is shown correct.
> 
> @smallteeths However, the `Name` column and `ID` columns are same. We can remove repeated info from the table I believe.
> <img alt="Screen Shot 2021-03-31 at 2 30 11 AM" width="1765" src="https://user-images.githubusercontent.com/60111667/113056441-6e4e2080-91c9-11eb-882d-66a6690f31d4.png">

Agree, thanks @khushboo-rancher :+1:

**Comment by smallteeths** [comment]
Because the data is the structure of the tree. So I kept the id for the user to compare the parentid. If only name is left, is it semantically worse? @innobead i

**Comment by innobead** [comment]
> Because the data is the structure of the tree. So I kept the id for the user to compare the parentid. If only name is left, is it semantically worse? @innobead i

It's fair from the semantic point of view. Let's keep it for now until a strong reason to remove it. Thanks for the explanation. :+1:

**Comment by immanuelfodor** [comment]
This was a really quick implementation, thank you everyone! :)
