### ISSUE TITLE
[QUESTION] longhorn-manager pod error when creating container 

### ISSUE THREAD

**Issue by jogaleins** [longhorn/longhorn#2402]
I created a K3S cluster in LXC ubuntu containers. when doing install via helm chart by running the following command. I'm getting the following errors in the pod.  Can you help advise what is causing the error. My LXC containers are mounted using LVM on /dev/sdb. 

Install Steps:
git clone https://github.com/longhorn/longhorn.git
kubectl create namespace longhorn-system
helm install longhorn ./longhorn/chart/ --namespace longhorn-system --set defaultSettings.defaultDataPath="/storage"

Result:
longhorn-manager-hd45d                      0/1     CreateContainerError   0          2m49s
longhorn-manager-krr9m                      0/1     CreateContainerError   0          2m57s

Pod Desc:
➜  chart git:(master) ✗ kubectl describe po longhorn-manager-hd45d -n longhorn-system
Name:         longhorn-manager-hd45d
Namespace:    longhorn-system
Priority:     0
Node:         worker2/10.167.132.226
Start Time:   Thu, 25 Mar 2021 04:34:54 +0000
Labels:       app=longhorn-manager
              app.kubernetes.io/instance=longhorn
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=longhorn
              app.kubernetes.io/version=v1.1.0
              controller-revision-hash=6cf5748b6d
              helm.sh/chart=longhorn-1.1.0
              pod-template-generation=1
Annotations:  <none>
Status:       Pending
IP:           10.42.3.5
IPs:
  IP:           10.42.3.5
Controlled By:  DaemonSet/longhorn-manager
Containers:
  longhorn-manager:
    Container ID:
    Image:         longhornio/longhorn-manager:v1.1.0
    Image ID:
    Port:          9500/TCP
    Host Port:     0/TCP
    Command:
      longhorn-manager
      -d
      daemon
      --engine-image
      longhornio/longhorn-engine:v1.1.0
      --instance-manager-image
      longhornio/longhorn-instance-manager:v1_20201216
      --share-manager-image
      longhornio/longhorn-share-manager:v1_20201204
      --manager-image
      longhornio/longhorn-manager:v1.1.0
      --service-account
      longhorn-service-account
    State:          Waiting
      Reason:       CreateContainerError
    Ready:          False
    Restart Count:  0
    Readiness:      tcp-socket :9500 delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAMESPACE:         longhorn-system (v1:metadata.namespace)
      POD_IP:                 (v1:status.podIP)
      NODE_NAME:              (v1:spec.nodeName)
      DEFAULT_SETTING_PATH:  /var/lib/longhorn-setting/default-setting.yaml
    Mounts:
      /host/dev/ from dev (rw)
      /host/proc/ from proc (rw)
      /var/lib/longhorn-setting/ from longhorn-default-setting (rw)
      /var/lib/longhorn/ from longhorn (rw)
      /var/run/ from varrun (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from longhorn-service-account-token-d4j7m (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/
    HostPathType:
  proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc/
    HostPathType:
  varrun:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/
    HostPathType:
  longhorn:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/longhorn/
    HostPathType:
  longhorn-default-setting:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      longhorn-default-setting
    Optional:  false
  longhorn-service-account-token-d4j7m:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  longhorn-service-account-token-d4j7m
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  48s               default-scheduler  Successfully assigned longhorn-system/longhorn-manager-hd45d to worker2
  Warning  Failed     48s               kubelet            Error: failed to generate container "e9abce9f4b1d8c7bcb289efc0accda7734d7426472f0832a47446c1a4b4a5662" spec: failed to generate spec: path "/var/run/" is mounted on "/" but it is not a shared mount
  Warning  Failed     48s               kubelet            Error: failed to generate container "efc3a3c3a1a5e25bd2b4f573d96794b1b82013bd266fa0b0460bea5c3c49649b" spec: failed to generate spec: path "/var/run/" is mounted on "/" but it is not a shared mount
  Warning  Failed     33s               kubelet            Error: failed to generate container "b540137b937bc9983ace51f5e0e2d8080af644a9d88e6933aa9fb39b444f8691" spec: failed to generate spec: path "/var/run/" is mounted on "/" but it is not a shared mount
  Warning  Failed     20s               kubelet            Error: failed to generate container "f595727d26977b0e2e3f6c34588b94913085f9aa3bfb7de49452766956716b79" spec: failed to generate spec: path "/var/run/" is mounted on "/" but it is not a shared mount
  Normal   Pulled     9s (x5 over 48s)  kubelet            Container image "longhornio/longhorn-manager:v1.1.0" already present on machine
  Warning  Failed     9s                kubelet            Error: failed to generate container "fe8ec92e99c9f41028b927ffee74bbbf297469c2b9ee580cfc772b1fb89664ab" spec: failed to generate spec: path "/var/run/" is mounted on "/" but it is not a shared mount

---
Version: `latest:1.1.0 as of writing`

**Comment by cclhsu** [comment]
I saw you create namespace `kubectl create namespace longhorn-system` instead of create namespace using helm:

```
        helm install ${RELEASE} "${CHART_PATH}" \
            --create-namespace \
            --namespace=${NAMESPACE} \
            --wait \
            --timeout=10m \
            -f "${CHART_PATH}/values.yaml" 
```

I am not sure if the namespace `longhorn-system` has proper permissions.  Can you try to uninstall following the guide https://longhorn.io/docs/0.8.0/install/uninstall-longhorn/ and redeploy using helm command provides?  Please provide the support-bundle if you continue to have the error.

**Comment by c3y1huang** [comment]
I think this could be related to how LXC container is mounted. If you check the directory, it's likely in private propagation.
```
findmnt -o TARGET,PROPAGATION /var/run
```

However, we've removed /var/run bind-mount in https://github.com/longhorn/longhorn-manager/commit/d9ac050ef7f5a828cd32422ac568f4648dfe1958#diff-f0046f268c88ac5f6d64449ad5a84d8292f898ba582da43f8e0948aed5d7f4ea and think we forgot to remove it in the chart :-/

@jogaleins could you try to install via kubectl to see if the issue still persists?
```
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.1.0/deploy/longhorn.yaml
```
And I also suggest to [check](https://longhorn.io/docs/1.1.0/deploy/install/#using-the-environment-check-script) if mount propagation is enabled.
```
https://longhorn.io/docs/1.1.0/deploy/install/#using-the-environment-check-script
```

**Comment by jogaleins** [comment]
Yes you're right it's mounted as private instead of shared.

root@worker1:~# findmnt -o TARGET,PROPAGATION /var/run
TARGET PROPAGATION
/run   private
root@worker1:~#

 I tried installing it using this kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.1.0/deploy/longhorn.yaml

Result is: 
➜  ~ kubectl get all  -n longhorn-system
NAME                                           READY   STATUS                 RESTARTS   AGE
pod/longhorn-ui-849c455d79-q5rsf               1/1     Running                0          4h21m
pod/longhorn-driver-deployer-cdb7464c6-fdgw4   0/1     Init:0/1               0          4h21m
pod/longhorn-manager-mplbl                     0/1     CreateContainerError   0          4h21m
pod/longhorn-manager-l9hjs                     0/1     CreateContainerError   0          4h21m
➜  ~ kubectl describe po longhorn-manager-l9hjs -n longhorn-system
Name:         longhorn-manager-l9hjs
Namespace:    longhorn-system
Priority:     0
Node:         worker2/10.167.132.226
Start Time:   Thu, 25 Mar 2021 06:07:12 +0000
Labels:       app=longhorn-manager
              controller-revision-hash=7854fd55b9
              pod-template-generation=1
Annotations:  <none>
Status:       Pending
IP:           10.42.3.8
IPs:
  IP:           10.42.3.8
Controlled By:  DaemonSet/longhorn-manager
Containers:
  longhorn-manager:
    Container ID:
    Image:         longhornio/longhorn-manager:v1.1.0
    Image ID:
    Port:          9500/TCP
    Host Port:     0/TCP
    Command:
      longhorn-manager
      -d
      daemon
      --engine-image
      longhornio/longhorn-engine:v1.1.0
      --instance-manager-image
      longhornio/longhorn-instance-manager:v1_20201216
      --share-manager-image
      longhornio/longhorn-share-manager:v1_20201204
      --manager-image
      longhornio/longhorn-manager:v1.1.0
      --service-account
      longhorn-service-account
    State:          Waiting
      Reason:       CreateContainerError
    Ready:          False
    Restart Count:  0
    Readiness:      tcp-socket :9500 delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAMESPACE:         longhorn-system (v1:metadata.namespace)
      POD_IP:                 (v1:status.podIP)
      NODE_NAME:              (v1:spec.nodeName)
      DEFAULT_SETTING_PATH:  /var/lib/longhorn-setting/default-setting.yaml
    Mounts:
      /host/dev/ from dev (rw)
      /host/proc/ from proc (rw)
      /var/lib/longhorn-setting/ from longhorn-default-setting (rw)
      /var/lib/longhorn/ from longhorn (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from longhorn-service-account-token-28lmn (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/
    HostPathType:
  proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc/
    HostPathType:
  longhorn:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/longhorn/
    HostPathType:
  longhorn-default-setting:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      longhorn-default-setting
    Optional:  false
  longhorn-service-account-token-28lmn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  longhorn-service-account-token-28lmn
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type    Reason  Age                       From     Message
  ----    ------  ----                      ----     -------
  Normal  Pulled  2m56s (x1199 over 4h22m)  kubelet  Container image "longhornio/longhorn-manager:v1.1.0" already present on machine.

I'll try to recreate the cluster again and  install open-iscsi if that would make a difference.

Thanks!

**Comment by jogaleins** [comment]
After re-creating the cluster from scratch. I'm still getting this. and the PROPAGATION is still private.

  Warning  Failed     3m32s                  kubelet            Error: failed to generate container "fe34a5e795f2976c4c625ea7d6c6024d9fe974542e0449affac7f8433c5dece4" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     3m18s                  kubelet            Error: failed to generate container "20e5adba511f011eac9f45cfe393736bc35a024a992ec5ae630d21382bcba210" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     3m4s                   kubelet            Error: failed to generate container "378296f042a097d52044cb2cd0afe5078236a4fc22533f8d1b84e9559281894c" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     2m52s                  kubelet            Error: failed to generate container "95f68d0f3df7dd01fbb16e64dcab843065343640910104bc4608e70acce4fa6c" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     2m39s                  kubelet            Error: failed to generate container "85377f2eea51ff5cdaf9a1a1cc03a3303e505430c7659aa3ba389a63743847f4" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     2m25s                  kubelet            Error: failed to generate container "111f8150d69782758d5b9de3fcfa0963583d1dc4dbf77e6af1722e8d48690b47" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Normal   Pulled     103s (x11 over 3m57s)  kubelet            Container image "longhornio/longhorn-manager:v1.1.0" already present on machine
  Warning  Failed     103s (x3 over 2m13s)   kubelet            (combined from similar events): Error: failed to generate container "938fda622efa8b59d1883f31b91a69299b42a8e90238b9a0174525bf08d2c236" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount

**Comment by c3y1huang** [comment]
Longhorn doesn't handle the propagation, it needs to be enabled before the install.

I am not too familiar with enabling mount propagation in LXC-container. But [this](https://www.claudiokuenzler.com/blog/955/rancher2-kubernetes-cluster-provisioning-fails-error-response-not-a-shared-mount) might help.

**Comment by jogaleins** [comment]
Thanks c3y1huang. That did the trick.
