### ISSUE TITLE
[FEATURE] Backing image upload

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2404]
Currently, Longhorn can only retrieve backing image from somewhere outside of the Longhorn system. But since Longhorn already stores copies of the backing image, we should allow users to upload the backing image if the user wants to do so locally.

**Comment by kaxing** [comment]
Validating in progress with Longhorn v1.2.0-preview1

Found a minor bug, when upload got interrupted, the checksum status will be shown as 'Verified'
![image](https://user-images.githubusercontent.com/602540/129181279-8398dd01-1e81-4706-b394-96720326d037.png)

**Comment by shuo-wu** [comment]
@smallteeths ^^ Can you take a look at this bug?

**Comment by kaxing** [comment]
Validation - **Passed**

Verified with master images (0819, ui: 69ebf61) and following combinations:
- File uploading with different file size, including 0m, 1mb to 6gb.
  - With or without checksum
  - Wait until finished or interrupt the upload process

A few memos for the future reference:
- Empty checksum got displayed as Verified now in now fixed
- Upload From Local with interruption will display as Failed in Status column: ![image](https://user-images.githubusercontent.com/602540/130060955-a202688c-d2df-49ac-9d54-3c8e927c4929.png)
- Current default pagination is 10 backing images per page

Progress of this issue :)
![image](https://user-images.githubusercontent.com/602540/130060327-c87b9b16-7797-4dc1-b18b-badae72ee52c.png)
