### ISSUE TITLE
[FEATURE] Volume download support

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2405]
We want to provide an option for the user to directly download the volume from the UI or CLI.

It might be a prerequisite for https://github.com/longhorn/longhorn/issues/2403

**Comment by yasker** [comment]
Considering push out of v1.2.0 release since it's not a high priority item.

**Comment by innobead** [comment]
This can be achieved by https://github.com/longhorn/longhorn/issues/3155 indirectly.
