### ISSUE TITLE
[FEATURE] Document Snapshot Best Practices

### ISSUE THREAD

**Issue by Rancheroo** [longhorn/longhorn#2410]
**Is your feature request related to a problem? Please describe.**
The Longhorn documents don't really cover the best practices when it comes to snapshot accumulation risks and best practices.

After using VMware snapshots they are a HUGE risk profile for leaving snapshots in place on a VM to do with delta files and recoverability. For example

> Do not use a single snapshot for more than 72 hours.
https://kb.vmware.com/s/article/1025279

**Describe the solution you'd like**
It would be beneficial to have clear Best practices when utilising snapshot in Longhorn and the advantages and disadvantages.
Also some information for users coming from VMware who are snapshot paranoid. 
A snapshot section in here would be ideal.
https://longhorn.io/docs/1.1.0/best-practices/

**Describe alternatives you've considered**
No alternatives

**Additional context**
- I have mentioned to @yasker and he has advised raising an Issue for the attention of @innobead 
- https://longhorn.io/docs/1.1.1/concepts/#24-snapshots

**Comment by innobead** [comment]
ref: #3754 

Let's track at https://github.com/longhorn/longhorn/issues/3627
