### ISSUE TITLE
[BUG] longhorn-manager fails to start on Docker for Mac ("... is not a shared mount")

### ISSUE THREAD

**Issue by codeclown** [longhorn/longhorn#2412]
**Describe the bug**
longhorn-manager pod fails to start on Kubernetes managed by Docker for Mac, due to bidirectional mount issue.

Most likely caused by an issue in Docker for Mac (see Additional context below).

**To Reproduce**
1. Reset the cluster from Docker for Mac Preferences (cluster is now empty, doesn't contain user-installed resources)
2. Install Longhorn via helm 3:

```bash
helm install test-longhorn longhorn/longhorn --namespace test-longhorn --create-namespace
```

2. Wait for a few minutes just to allow time for setup.
3. `longhorn-manager` has failed to launch (CrashLoopBackOff):

```shell
$ kubectl -n test-longhorn get pod
NAME                                        READY   STATUS             RESTARTS   AGE
longhorn-driver-deployer-7865f997b6-f5xfh   0/1     Init:0/1           0          4m29s
longhorn-manager-4bckx                      0/1     CrashLoopBackOff   5          4m29s
longhorn-ui-5797bdb78f-5gqfl                1/1     Running            0          4m29s
```

```shell
$ kubectl -n test-longhorn describe pod longhorn-manager-4bckx
[...]
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  4m48s                   default-scheduler  Successfully assigned test-longhorn/longhorn-manager-4bckx to docker-desktop
  Normal   Pulled     3m18s (x5 over 4m46s)   kubelet            Container image "longhornio/longhorn-manager:v1.1.0" already present on machine
  Normal   Created    3m18s (x5 over 4m46s)   kubelet            Created container longhorn-manager
  Warning  Failed     3m18s (x5 over 4m45s)   kubelet            Error: failed to start container "longhorn-manager": Error response from daemon: path /var/run is mounted on / but it is not a shared mount
  Warning  BackOff    2m29s (x10 over 4m17s)  kubelet            Back-off restarting failed container
```

Error message extracted from above output:

```
Error response from daemon: path /var/run is mounted on / but it is not a shared mount
```

**Expected behavior**
All Longhorn pods should start without issue.

**Log**
None

**Environment:**
 - Longhorn version: 1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm 3
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Docker for Mac 3.2.2 / Kubernetes 1.19.7
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Additional context**
Most likely caused by an issue in Docker for Mac: https://github.com/docker/for-mac/issues/3431

Filing this issue because unsure if something can be done on Longhorn's side, or if there's a configuration option in Longhorn that would resolve this. Also just in case someone lands here from Google and it's helpful.

**Comment by cclhsu** [comment]
Hi! Longhorn currently do not officially support "Docker-on-Mac".  It is required for Longhorn to deploy on file-system supporting shared mounted.  HFS+ seems not support it.

**Comment by codeclown** [comment]
Thank you for the quick response! Understood, just wanted to check to make sure it's not behind a config or something. Closing.
