### ISSUE TITLE
[BUG] after deleting all backups, the backup blocks do not be cleaned up

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#2417]
**Describe the bug**

After deleting the used VolumeSnapshots, even the backup was deleted but the referenced backup blocks did not get cleaned up. 

ref: https://github.com/rancher/harvester/issues/385

**To Reproduce**

Please refer to the discussion thread. https://github.com/rancher/harvester/issues/385. 

**Expected behavior**

The unused backup blocks should be cleaned up.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Additional context**
- http://github.com/longhorn/longhorn-engine/blob/master/vendor/github.com/longhorn/backupstore/deltablock.go#L778-L778

**Comment by jenting** [comment]
I create a Longhorn cluster with version v1.1.0 and v1.1.1-preview1 respectively and deploy an Elasticsearch cluster (StatefulSet) on it. However, I can't reproduce the issue.

Delete VolumeSnapshot would delete backups in S3 or NFS. If all the volume's VolumeSnapshot deleted, the folder `backups/` and `blocks/` would be deleted also.

Note: The only remaining is the `volume.cfg` if all volume's VolumeSnapshot got deleted, the `Last Backup At` are empty.
![image](https://user-images.githubusercontent.com/49380831/112939115-7ec8b180-915d-11eb-84a1-5cadd7680e74.png)
