### ISSUE TITLE
[BUG] Unable to attach RWX to a node using Longhorn UI

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2420]
**Describe the bug**
RWX volume doesn't attach to a node when attach request is sent by Longhorn UI.

**To Reproduce**
1. Create a RWX volume using Longhorn UI.
2. Create PV/PVC for that volume.
3. Click attach and select a node.
4. The volume doesn't get attached to the node.

**Expected behavior**
The volume should get attached to the node.

**Log**
I don't see Longhorn-manager logs after the attach request. `[longhorn-manager-hntrh] 122.171.150.151 - - [29/Mar/2021:17:10:20 +0000] "POST /v1/volumes/volume-test-1?action=attach HTTP/1.1" 200 2581 "https://khushlh.qa.rancher.space/k8s/clusters/c-55pdb/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"` for a rwx volume.
[longhorn-support-bundle_8b98a2bd-3a47-4227-b8d0-850802e78cf2_2021-03-29T17-11-48Z.zip](https://github.com/longhorn/longhorn/files/6223395/longhorn-support-bundle_8b98a2bd-3a47-4227-b8d0-850802e78cf2_2021-03-29T17-11-48Z.zip)

Volume name - volume-test-1, pvc-Dd90b31b-81e0-4985-835b-90afe7cbd02f

**Environment:**
 - Longhorn version: Longhorn master - 03/29/2021

**Additional context**
Attachment through the Longhorn UI for RWO volumes is working fine.

**Comment by joshimoo** [comment]
RWX volumes can only be manually attached in maintenance mode, otherwise they are controlled by the share-manager.

**Comment by khushboo-rancher** [comment]
@joshimoo Thanks for clarifying this behavior change from v1.1.0 to master. Do you think we should show a message on the Longhorn UI in this case?

**Comment by innobead** [comment]
cc @smallteeths

**Comment by smallteeths** [comment]
The ui can be modified in this way. Selected by default and disabled `Maintenance` radio When manually attaching rwx volume.

![Jietu20210401-102047](https://user-images.githubusercontent.com/27733391/113234599-31bb1b80-92d4-11eb-8e8e-4a911d6c566c.jpg)

Is this okay? @innobead @joshimoo @khushboo-rancher

**Comment by innobead** [comment]
> The ui can be modified in this way. Selected by default and disabled `Maintenance` radio When manually attaching rwx volume.
> 
> ![Jietu20210401-102047](https://user-images.githubusercontent.com/27733391/113234599-31bb1b80-92d4-11eb-8e8e-4a911d6c566c.jpg)
> 
> Is this okay? @innobead @joshimoo @khushboo-rancher

It sounds good to me. Do we have any tip style for this kind of enforced behavior like disabled by default? like some message next to the check.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master -`04/03/2021`

Validation - **Pass**

User can attach RWX only in `maintenance mode`. UI shows the message on clicking the attach button. Validated the single and multiple volume attach scenarios.

<img width="1071" alt="Screen Shot 2021-04-03 at 12 44 57 AM" src="https://user-images.githubusercontent.com/60111667/113446680-eb6dd580-9415-11eb-83d8-099fbdba32fb.png">
