### ISSUE TITLE
[BUG] Volume starts with uppercase in the volume details page

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2424]
**Describe the bug**
Volume name in the volume detail page is appearing with first letter as uppercase.

**To Reproduce**
1. Create a volume using Longhorn UI named `volume-test-2`
2. Click on the volume to go to the volume detail page.
3. See the name appearing as `Volume-Test-2`
<img width="844" alt="Screen Shot 2021-03-30 at 2 59 33 PM" src="https://user-images.githubusercontent.com/60111667/112977169-5f3c8380-9173-11eb-9f3c-ab440a9139a5.png">

**Expected behavior**
The volume name should appear as it is.

**Environment:**
 - Longhorn version: Longhorn Master - `03/30/2021`

**Comment by jenting** [comment]
It also happens at LH v1.1.1-preview1 version.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master `03/31/2021`

Validation - **Pass**

<img width="833" alt="Screen Shot 2021-03-31 at 10 48 32 PM" src="https://user-images.githubusercontent.com/60111667/113184807-47e4bf80-9273-11eb-89a2-e36518ed77e1.png">
