### ISSUE TITLE
[BUG] longhorn-manager breaks after deleting disk (invalid memory address or nil pointer dereference)

### ISSUE THREAD

**Issue by mtfsc** [longhorn/longhorn#2430]
**Describe the bug**
After Deleting a Disk from UI, longhorn-manager gooes into CrashLoopBackOff state. We are unable to recover from this point and have to uninstall longhorn completely to get it working again.

**To Reproduce**
1. Fresh Install of Longhorn with kubectl (like described in documentation)
2. Goto UI
3. Click on Nodes, Edit Node & Disk, click on Schedul = False, Evict = True on Node and disk, click the basket (remove), Click save

**Expected behavior**
Disk is no longer listed in Longhorn UI (at least, nothing crashes)

**What happened**
k -n longhorn-system get pods |grep -v Running
NAME                                       READY   STATUS             RESTARTS   AGE
longhorn-manager-8bkzw                     0/1     CrashLoopBackOff   10         33m
longhorn-manager-h59ns                     0/1     CrashLoopBackOff   9          33m
longhorn-manager-ncszk                     0/1     CrashLoopBackOff   8          33m
longhorn-manager-pcz28                     0/1     CrashLoopBackOff   9          33m

We're unable to recover from here, have to delete everthing.

**Log**
time="2021-03-31T14:36:19Z" level=info msg="Start overwriting built-in settings with customized values"
W0331 14:36:19.769611       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-03-31T14:36:19Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr, ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/*': No such file or directory\n, error exit status 2"
I0331 14:36:19.776353       1 leaderelection.go:241] attempting to acquire leader lease  longhorn-system/longhorn-manager-upgrade-lock...
I0331 14:36:19.787395       1 leaderelection.go:251] successfully acquired lease longhorn-system/longhorn-manager-upgrade-lock
time="2021-03-31T14:36:19Z" level=info msg="Start upgrading"
time="2021-03-31T14:36:19Z" level=info msg="No API version upgrade is needed"
time="2021-03-31T14:36:19Z" level=info msg="Finish upgrading"
time="2021-03-31T14:36:19Z" level=info msg="Upgrade leader lost: 89780-customer-node4"
W0331 14:36:19.877462       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0331 14:36:19.880446       1 shared_informer.go:197] Waiting for caches to sync for longhorn datastore
E0331 14:36:19.887352       1 kubernetes_node_controller.go:232] couldn't get kubernetes node 89780-customer-node4: node "89780-customer-node4" not found 
E0331 14:36:19.914780       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 313 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x18238e0, 0x2a87900)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x18238e0, 0x2a87900)
	/usr/local/go/src/runtime/panic.go:967 +0x166
github.com/longhorn/longhorn-manager/controller.(*ReplicaController).enqueueNodeChange(0xc00054b6c0, 0x1a236e0, 0xc000b72000)
	/go/src/github.com/longhorn/longhorn-manager/controller/replica_controller.go:588 +0x338
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/controller.go:198
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x1f4, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:658 +0x120
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc0008fee18, 0x188fb80, 0xc0007f2601)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0007f2760)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0008fef60, 0xdf8475800, 0x0, 0x1, 0xc00007d080)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0005ee280)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00054aed0, 0xc000664340)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x15ba5a8]

goroutine 313 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x18238e0, 0x2a87900)
	/usr/local/go/src/runtime/panic.go:967 +0x166
github.com/longhorn/longhorn-manager/controller.(*ReplicaController).enqueueNodeChange(0xc00054b6c0, 0x1a236e0, 0xc000b72000)
	/go/src/github.com/longhorn/longhorn-manager/controller/replica_controller.go:588 +0x338
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/controller.go:198
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x1f4, 0x0, 0x0)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:658 +0x120
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc000ab9e18, 0x188fb80, 0xc0007f2601)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0007f2760)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000ab9f60, 0xdf8475800, 0x0, 0x1, 0xc00007d080)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0005ee280)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00054aed0, 0xc000664340)
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62

**Environment:**
 - Longhorn version: 1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE 2.5.7, Kubernetes: 1.20.4
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: Debian 10.8
   - CPU per node: 2
   - Memory per node: 8
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 25G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMware
 - Number of Longhorn volumes in the cluster: 0

**Comment by ElisaMeng** [comment]
This is very bad from architecture perspective, see also #2423

**Comment by mtfsc** [comment]
Used yaml for deployment (Basically its this one: https://github.com/longhorn/longhorn/blob/957bb72c8ab8c3c7d7b5d0fd50a18910eab82e7d/deploy/longhorn.yaml, with some adjustments in the longhorn-default-setting ConfigMap Section)

[longhorn.yaml.txt](https://github.com/longhorn/longhorn/files/6241444/longhorn.yaml.txt)

**Comment by joshimoo** [comment]
Thank you for reporting, this specific issue was addressed as part of the below issue and the fix will be available once v1.1.1 is released.
https://github.com/longhorn/longhorn/issues/2208
https://github.com/longhorn/longhorn-manager/pull/830
