### ISSUE TITLE
[BUG] Backup Target - NFS - the k8s node supports only 4.0 - an incorrect mount option was specified

### ISSUE THREAD

**Issue by tmorin** [longhorn/longhorn#2438]
Hi,

I've the following error from the front-end `#/backup` when I configure Longhorn to use a NFS "Backup Target".

```
error listing backups: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn [backup ls --volume-only nfs://dnas-share-rb-c1-n1.dnas:/backup/rb-c1], output Cannot mount nfs dnas-share-rb-c1-n1.dnas:/backup/rb-c1: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 dnas-share-rb-c1-n1.dnas:/backup/rb-c1 /var/lib/longhorn-backupstore-mounts/dnas-share-rb-c1-n1_dnas/backup/rb-c1], output mount.nfs4: an incorrect mount option was specified , error exit status 32 , stderr, time="2021-04-01T15:05:29Z" level=error msg="Cannot mount nfs dnas-share-rb-c1-n1.dnas:/backup/rb-c1: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 dnas-share-rb-c1-n1.dnas:/backup/rb-c1 /var/lib/longhorn-backupstore-mounts/dnas-share-rb-c1-n1_dnas/backup/rb-c1], output mount.nfs4: an incorrect mount option was specified\n, error exit status 32" , error exit status 1
```

From my understanding, the error is raised by [util.Execute] when called in [nfs.mount].

[util.Execute] https://github.com/longhorn/backupstore/blob/51dcc71901ed7f377a80df143196933096605cf4/util/util.go#L152
[nfs.mount] https://github.com/longhorn/backupstore/blob/51dcc71901ed7f377a80df143196933096605cf4/nfs/nfs.go#L99

**Environment:**

 - Longhorn version: 1.1.0
 - Kubernetes version: v1.20.4+k3s1
 - Node config
   - Linux 4.4.213-rockchip64 SMP aarch64
   - CPU per node: 4CPU
   - Memory per node: 4Gi
   - Disk type: emmc + sdcard
   - Network bandwidth and latency between the nodes: local network
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal, 3 nodes

**Analysis:**

In fact, the k8s node (Debian Buster Linux 4.4.213-rockchip64 SMP aarch64) is not able to mount the NFS share with the option `nfsvers=4.2`. However, it is possible to mount the NFS share with `nfsvers=4.0`.

```
XXXXX:~$ sudo mount -t nfs4 -v -o nfsvers=4.2 192.168.0.11:/backup /tmp/dnas
mount.nfs4: timeout set for Thu Apr  1 15:10:43 2021
mount.nfs4: trying text-based options 'nfsvers=4.2,addr=192.168.0.11,clientaddr=192.168.0.11'
mount.nfs4: mount(2): Invalid argument
mount.nfs4: an incorrect mount option was specified
XXXXX:~$ sudo mount -t nfs4 -v -o nfsvers=4.1 192.168.0.11:/backup /tmp/dnas
mount.nfs4: timeout set for Thu Apr  1 15:10:46 2021
mount.nfs4: trying text-based options 'nfsvers=4.1,addr=192.168.0.11,clientaddr=192.168.0.11'
mount.nfs4: mount(2): Invalid argument
mount.nfs4: an incorrect mount option was specified
XXXXX:~$ sudo mount -t nfs4 -v -o nfsvers=4.0 192.168.0.11:/backup /tmp/dnas
mount.nfs4: timeout set for Thu Apr  1 15:10:50 2021
mount.nfs4: trying text-based options 'nfsvers=4.0,addr=192.168.0.11,clientaddr=192.168.0.11'
XXXXX:~$ sudo umount /tmp/dnas
/tmp/dnas: nfs4 mount point detected
/tmp/dnas: umounted
```

FYI it works when I mount the NFS share from another computer (Linux 5.8.0-48-generic SMP  x86_64).

```
XXXXX:~$ sudo mount.nfs -v -o nfsvers=4.2 192.168.0.10:/backup /tmp/dnas
mount.nfs: timeout set for Thu Apr  1 17:21:12 2021
mount.nfs: trying text-based options 'nfsvers=4.2,addr=192.168.0.10,clientaddr=192.168.0.216'
XXXXX:~$ sudo umount /tmp/dnas
/tmp/dnas: nfs4 mount point detected
/tmp/dnas: umounted
```

So, from my understanding, even if the server support NFS 4.0, 4.1 and 4.2, the k8s node supports only NFS 4.0.

**Question:**

According to [nfs.MinorVersions], the version 4.0 should be supported.

[nfs.MinorVersions] https://github.com/longhorn/backupstore/blob/51dcc71901ed7f377a80df143196933096605cf4/nfs/nfs.go#L19

I'm not a Go developer so I'm wondering if there is something to do in the [loop] in order to iterate from 4.2 to 4.0 each time the client raised an error of type `an incorrect mount option was specified`.

[loop] https://github.com/longhorn/backupstore/blob/51dcc71901ed7f377a80df143196933096605cf4/nfs/nfs.go#L97

Thank you for the support!

Best regards

**Comment by joshimoo** [comment]
Leaving a note here, this happens because the error message does not contain: "Protocol not supported"
So once the first mount fails, the other versions won't be even attempted.

The fix should probably be to try all mount versions in the error case instead of parsing the error message.
Since if all of them fail the last error will be returned, which is the baseline v4.0

See:
- https://github.com/longhorn/backupstore/blob/51dcc71901ed7f377a80df143196933096605cf4/nfs/nfs.go#L100
- https://github.com/longhorn/backupstore/blob/51dcc71901ed7f377a80df143196933096605cf4/nfs/nfs.go#L71

**Comment by joshimoo** [comment]
cc @innobead this issue should be easy to fix see my comment here: https://github.com/longhorn/longhorn/issues/2438#issuecomment-812011216

Currently the client needs to support nfs v4.2 otherwise the mount for the backupstore will fail.
Since there is a bug in the way it's tested. The solution for this is to just try from 4.2, 4.1, 4.0
And only return the final error if the last try 4.0 fails to mount.

That way we don't need to do any evaluation of the error messages or other such stuff.

**Comment by derekbit** [comment]
PR V3:
longhorn/longhorn-engine#671
https://github.com/longhorn/backupstore/pull/86

**Comment by kaxing** [comment]
Validating in progress,

Testing master image set with nfsv3-only worker nodes,

In Scenario 2., when trying to use the NFS as backup target user will now see this error notification:
![image](https://user-images.githubusercontent.com/602540/141906636-b843f563-d630-42f0-b529-9809105eb6e4.png)
```
error listing backup volume names: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn [backup ls --volume-only nfs://longhorn-test-nfs-svc.default:/opt/backupstore], output Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: vers=4.0: Failed to execute: mount [-t nfs4 -o nfsvers=4.0 -o actimeo=1 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mount.nfs4: No such device , error exit status 32: vers=4.1: Failed to execute: mount [-t nfs4 -o nfsvers=4.1 -o actimeo=1 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mount.nfs4: No such device , error exit status 32: vers=4.2: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 -o actimeo=1 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mount.nfs4: No such device , error exit status 32: Cannot mount using NFSv4 , stderr, time="2021-11-16T02:57:27Z" level=error msg="Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: vers=4.0: Failed to execute: mount [-t nfs4 -o nfsvers=4.0 -o actimeo=1 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mount.nfs4: No such device\n, error exit status 32: vers=4.1: Failed to execute: mount [-t nfs4 -o nfsvers=4.1 -o actimeo=1 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mount.nfs4: No such device\n, error exit status 32: vers=4.2: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 -o actimeo=1 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mount.nfs4: No such device\n, error exit status 32: Cannot mount using NFSv4" , error exit status 1
```

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with master images.

On cluster with with NFSv3-only kernel installed,
The message will be shown as mentioned in above message.
And the Backup Target won't work.

On cluster with with NFSv4-only kernel installed,
There won't be info or error messages.
And the Backup Target can set to the NFSv4 server.

**Comment by tmorin** [comment]
Thank you!!! :rocket:

**Comment by infestdead** [comment]
Having this issue on Longhorn 1.5.1.
Our current storage (Isilon OneFS supports only NFS 4.0) and the error I get is:

`error listing backup volume names: timeout executing: /var/lib/longhorn/engine-binaries/rancher-mirrored-longhornio-longhorn-engine-v1.5.1/longhorn [backup ls --volume-only nfs://172.16.10.199:/ifs/data/kubernetes/longhorn], output , stderr, time="2023-10-17T14:52:00Z" level=warning msg="Trying reading mount point /var/lib/longhorn-backupstore-mounts/172_16_10_199/ifs/data/kubernetes/longhorn to make sure it is healthy" pkg=nfs time="2023-10-17T14:52:00Z" level=info msg="Attempting mount for nfs path 172.16.10.199:/ifs/data/kubernetes/longhorn with nfsvers 4.2" pkg=nfs time="2023-10-17T14:52:00Z" level=info msg="Mounting NFS share nfs://172.16.10.199:/ifs/data/kubernetes/longhorn on mount point /var/lib/longhorn-backupstore-mounts/172_16_10_199/ifs/data/kubernetes/longhorn with options [nfsvers=4.2 actimeo=1 soft timeo=300 retry=2]" pkg=nfs , error <nil>`

There's no retry to 4.1, 4.0 etc. I can mount manually from the node by specifying -o vers=4.0. Any ideas? 

Thanks
