### ISSUE TITLE
[BUG] Longhorn setting page toggles with blank page.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2439]
**Describe the bug**
The setting page of longhorn is going blank in interval of about 21 seconds.

**To Reproduce**
1. Deploy Longhorn UI - master `3c287b3`
2. Go to setting page.
3. The page is blank initially and periodically shows the settings.

https://user-images.githubusercontent.com/60111667/113332448-d07c6200-933e-11eb-81ab-ea1e24274f2a.mov

**Log**
WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.
[longhorn-support-bundle_a0e5c5da-f57e-4dec-a9ce-a12809944031_2021-04-01T17-31-04Z.zip](https://github.com/longhorn/longhorn/files/6245406/longhorn-support-bundle_a0e5c5da-f57e-4dec-a9ce-a12809944031_2021-04-01T17-31-04Z.zip)

**Environment:**
 - Longhorn version: Longhorn-master `04/01/2021`

**Comment by smallteeths** [comment]
Because the websocket has been updated on the back end, the ui has been updated in line with the changes on the back end. The reason for the bug is that the ui version is not up to date.

https://github.com/longhorn/longhorn/issues/2372
