### ISSUE TITLE
[BUG] failed to renew lease longhorn-system/external-attacher-leader-driver-longhorn-io: failed to tryAcquireOrRenew context deadline exceeded

### ISSUE THREAD

**Issue by bitvilag** [longhorn/longhorn#2440]
**Describe the bug**

I have installed a brand new microk8s with two nodes. I have then installed longhorn using helm3 without any modification to it.
No issue found so far

I have added the third node using the built in tools of microk8s. Longhorn took quite a time until service was back -> lot of uknown status pods, but then when it came back I left it running with one attached volume for a night.

This morning I notice the pods are crashlooping 

longhorn-system      csi-snapshotter-76c6f569f9-l2cfw             0/1     CrashLoopBackOff   193        46h
longhorn-system      csi-provisioner-547dfff5dd-xxdvw             0/1     CrashLoopBackOff   193        46h
longhorn-system      csi-attacher-5df5c79d4b-l4nzl                0/1     CrashLoopBackOff   199        46h
longhorn-system      csi-provisioner-547dfff5dd-glkj9             0/1     CrashLoopBackOff   196        46h
longhorn-system      csi-provisioner-547dfff5dd-rm5bm             0/1     CrashLoopBackOff   194        46h
longhorn-system      csi-attacher-5df5c79d4b-66djj                0/1     CrashLoopBackOff   198        46h
longhorn-system      csi-resizer-654bc8c8dd-svdxr                 0/1     CrashLoopBackOff   196        46h
longhorn-system      csi-attacher-5df5c79d4b-9mmgg                1/1     Running            197        46h
longhorn-system      csi-snapshotter-76c6f569f9-rvtdr             1/1     Running            193        46h
longhorn-system      csi-resizer-654bc8c8dd-tqhsk                 0/1     CrashLoopBackOff   199        46h
longhorn-system      csi-resizer-654bc8c8dd-56t2t                 1/1     Running            200        46h
longhorn-system      csi-snapshotter-76c6f569f9-zvtlk             0/1     CrashLoopBackOff   197        46h

Now I am uncertain whether I misconfigured anything (though I only added a volume) or what is the reason for it.

**To Reproduce**
1. helm3 basic install on 2 nodes (microk8s)
2. add 3. node to cluster

**Expected behavior**
Longhorn pod do not restart with CrashLoopBackOff . Even if it states running it will not be in same state for long.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.
The errors in longhorn pods state:
`I0401 06:59:54.840688       1 reflector.go:188] Listing and watching *v1beta1.VolumeSnapshotContent from pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108
I0401 06:59:54.843289       1 reflector.go:188] Listing and watching *v1beta1.VolumeSnapshotClass from pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108
E0401 06:59:54.846719       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1beta1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)
E0401 06:59:54.848233       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1beta1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
I0401 06:59:55.814593       1 leaderelection.go:288] failed to renew lease longhorn-system/external-snapshotter-leader-driver-longhorn-io: failed to tryAcquireOrRenew context deadline exceeded
F0401 06:59:55.814725       1 leader_election.go:169] stopped leading`

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: v1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm 3
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Mikrok8s
   - Number of management node in the cluster: Included
   - Number of worker node in the cluster: 3 nodes (2 nodes no issue)
 - Node config
   - OS type and version: Ubuntu 2004
   - CPU per node: 2
   - Memory per node: 8GB
   - Disk type(e.g. SSD/NVMe): Sata
   - Network bandwidth between the nodes: virtio
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM/proxmox
 - Number of Longhorn volumes in the cluster: 1

**Additional context**

**Comment by PhanLe1010** [comment]
It seems that something is wrong with the `etcd` so the `csi` deployments cannot do the leader election:
```
leaderelection.go:288] failed to renew lease longhorn-system/external-snapshotter-leader-driver-longhorn-io: failed to tryAcquireOrRenew context deadline exceeded F0401 06:59:55.814725 1 leader_election.go:169] stopped leading
```
and they enter a crashloop.

You can start by checking the health of `etcd`. This issues seems similar to the issue https://github.com/longhorn/longhorn/issues/2287

**Comment by Larry1123** [comment]
microk8s does not use etcd it uses https://dqlite.io/ I am having the same error with a two node microk8s setup there is no real election as it does not support HA until there are at least 3 node.

**Comment by Larry1123** [comment]
[longhorn-support-bundle_6e5d0c74-393b-4f86-bbdc-1c98af21b112_2021-05-30T21-34-27Z.zip](https://github.com/longhorn/longhorn/files/6566940/longhorn-support-bundle_6e5d0c74-393b-4f86-bbdc-1c98af21b112_2021-05-30T21-34-27Z.zip)
I attached the support bundle from my cluster as I am destroying it today and rebuilding in hopes of avoiding this issue.

**Comment by PhanLe1010** [comment]
Thanks @Larry1123 
We will look into this issue

**Comment by jenting** [comment]
Lots of Kubernetes controllers rely on the leader election mechanism, at Longhorn, we use the leader election on Longhorn upgrade to make sure only one node would perform the longhorn-system-wide upgrade process.

Does microk8s suggest leader election mechanism only works with more than 3 nodes?

**Comment by liangyuanpeng** [comment]
Same problem, I just have 1 k3s server and 1 k3s agent, the csi pod of longhorn  always `CrashLoopBackOff and Running and Error and ...`. It confused to me.

**Comment by jenting** [comment]
> Same problem, I just have 1 k3s server and 1 k3s agent, the csi pod of longhorn always `CrashLoopBackOff and Running and Error and ...`. It confused to me.

@liangyuanpeng 
Could you provide the CSI pod crash log?

**Comment by bitvilag** [comment]
I am going to run another try. I did notice I had storage write speed issues which I managed to resolve on hardware level. Not sure if that affects this. I will come back in a week with results.

**Comment by bitvilag** [comment]
I did not have the time to confirm or report. I moved away from this solution
