### ISSUE TITLE
[BUG] Priority class not getting set for recurring jobs

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2444]
**Describe the bug**
Priority set using Longhorn UI is not reflecting for recurring job.

**To Reproduce**
1. Deploy Longhorn master on a cluster.
2. Set priority class in the setting page of Longhorn UI.
3. Create a volume and configure recurring snapshot/backup job for it.
4. Check the yaml for recurring job, there is no priority class.

**Environment:**
 - Longhorn version: Longhorn -master `04/06/2021`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE - K8s v1.20.4
   - Number of management node in the cluster:  1
   - Number of worker node in the cluster: 4

**Comment by PhanLe1010** [comment]
Not sure if we want to add `priority class` to the recurring jobs since the recurring jobs are not critical for Longhorn basic functionalities. On the other hand, adding `priority class` to the recurring jobs would make Kubernetes evicts other lower priority workloads in cluster when there is resource contention. 
How do you think? @shuo-wu , @innobead

**Comment by innobead** [comment]
> Not sure if we want to add `priority class` to the recurring jobs since the recurring jobs are not critical for Longhorn basic functionalities. On the other hand, adding `priority class` to the recurring jobs would make Kubernetes evicts other lower priority workloads in cluster when there is resource contention.
> How do you think? @shuo-wu , @innobead

Thanks for raising this concern/question. I am OK with this adaptive definition but probably need some documentation somewhere (self-explanatory in UI setting or chart) to let people know recurring jobs not under this enforcement.

**Comment by shuo-wu** [comment]
I am fine with both as well. Or we can add PriorityClass as a new field of the recurring job.

**Comment by PhanLe1010** [comment]
Since the team is ok with either ways and to keep the convention consistent, I set priority class for recurring job

**Comment by khushboo-rancher** [comment]
@innobead @PhanLe1010 I see the label `backport-needed` but don't see the merge for v1.1.2

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master `05/17/2021`

Validation - Pass

The PriorityClassName is getting set for the recurring jobs as well now.

**Comment by PhanLe1010** [comment]
Need to create PR into v1.1.2

**Comment by khushboo-rancher** [comment]
@PhanLe1010 This is already present in the branch v1.1.2, Verified with the longhorn-v1.1.2-head `05/25/2021` image

Validation - **Pass**
