### ISSUE TITLE
[BUG] FailedAttachVolume - cannot be attached to the node A since it is already attached to the node B

### ISSUE THREAD

**Issue by rsoika** [longhorn/longhorn#2445]
I want to report a problem I have with Longhorn from the early beginning and even I have build up complete new Kuberntes clusters I get not rid of the problem.

**The situation:**

 - running a cluster with 3 worker nodes and 1 master
 - running a POD with a durable longhorn volume 
 - Now one of my nodes failed (e.g. a network problem)
 - after 5 minutes kubernetes restarts the POD on a different node
 - the new pod gets stuck in ContainerCreating state

I am running Longhorn 1.1.0 with the extra settings: 

 - Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly = TRUE
 - Volume Attachment Recovery Policy = immediate

From the [official documentation](https://longhorn.io/docs/1.1.0/high-availability/node-failure/) I would expect that the pod and the volume will be rescheduled. But this did nto work. I have permanently the error message:

```
 Warning  FailedAttachVolume  117s (x16 over 32m)  attachdetach-controller  AttachVolume.Attach failed for volume "my-index" : rpc error: code = FailedPrecondition desc = The volume my-index cannot be attached to the node worker-5 since it is already attached to the node worker-6                                                                              │
 Warning  FailedMount         78s (x10 over 30m)   kubelet, worker-5  Unable to attach or mount volumes: unmounted volumes=[index], unattached volumes=[index default-token-cntp8]: timed out waiting for the condition  
```

Even if I try to kill the POD it will not solve the probem. 

When I delete my complete deployment (`$ kubectl delete ....`) the affected volume is still attached. 

The command "`kubectl get pv`" did no longer list the volume. But in the Longhorn UI I can still see the volume (as it is durable) and I can see that it is attached (!) with the following status details:

```
State: attached
Health: healthy
Ready for workload:Ready
Conditions:
restore
scheduled
Frontend:Block Device
Attached Node & Endpoint:
tikal-worker-6
/dev/longhorn/my-index
Size:
1 Gi
Actual Size:49.1 Mi
Data Locality:disabled
Access Mode:ReadWriteOnce
Base Image:
Engine Image:longhornio/longhorn-engine:v1.1.0
Created:2 months ago
Node Tags:
Disk Tags:
Last Backup:
Last Backup At:
Instance Manager:
instance-manager-e-fc27e69c
Last time bound with PVC:5 minutes ago
Last time used by Pod:5 minutes ago
Last Namespace:xxxxx
Last Bounded PVC Name:index
PV Name:
PV Status:
Revision Counter:False
Last Pod Name:imixs-office-workflow-c8dcc469f-5jn9r
Last Workload Name:imixs-office-workflow-c8dcc469f
Last Workload Type:ReplicaSet
```

When I try to recreate my deployment with kubectl apply.....  I am still running into the same situation.

The only solution for me is to:

 - delete the POD manauell (kubectl delete ....) 
 - go into the Longhonr UI and detach the volume manually
 - redeploy the pod manually (kubectl apply ...)

Now longhorn will re-attach the volume and the POD starts and everything works fine again.

But my question is: Why I am running permanently into this awful situation? What could be the reason? What would be the expected behaviour?

The only part I found in my setup which is not official documented by Longhorn is my Storage Class I use:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-durable    
provisioner: driver.longhorn.io
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
```

Is there something wrong with this storage class?

**Comment by rsoika** [comment]
Is it possible that this is related to the flag:

    Replica Node Level Soft Anti-Affinity=false (default)

Do you think it makes sense to set this to 'true' for a situation I described here?

**Comment by joshimoo** [comment]
@rsoika The above error message makes me believe that the csi driver did not call detach on the volume, but returned success to kubernetes, this means that the longhorn volume still has v.spec.NodeID set while kubernetes thinks the volume is available again.

I fixed a bug in this regard that we now always call attach/detach from the csi driver.
https://github.com/longhorn/longhorn-manager/pull/859

This will be available in v1.1.1 if you want to give this a try on a test cluster, feel free to grab the master longhorn-manager image. And let us know whether this solves your problem or not :)

As a workaround you can unset v.spec.NodeID field or use the detach button from the longhorn-ui for the moment.

**Comment by rsoika** [comment]
Thanks a lot for the feedback! For now I can not test v1.1.1 because this is my productive cluster. But as soon as 1.1.1 is released, I will upgrade my longhorn version. And I will give you my feedback on this issue.
You can close the issue if it bothers you.

**Comment by joshimoo** [comment]
@rsoika not a problem, thanks for reporting this issue, I will leave it open and please let us know if v1.1.1 fixes the behavior :)

**Comment by PhanLe1010** [comment]
@rsoika 

V1.1.1 is out. Please let us know if this issue is resolved

**Comment by rsoika** [comment]
Yes I will do so, but I need a view more days....

**Comment by rsoika** [comment]
I have now upgraded from 1.1.0 to 1.1.1. 
I am using the origin longhorn.yaml file from [here](https://raw.githubusercontent.com/longhorn/longhorn/v1.1.1/deploy/longhorn.yaml).

Everything worked smoothly. I upgrated also all engines to 1.1.1 in the Frontend. No problems occurred. 
I will see if I run again the problem describe here and will report it.

But I still see a kind of error message in the longhorn-manager PODs I can not understand. The message looks like this one and repeats every few seconds:

```
time="2021-05-06T17:21:19Z" level=warning msg="longhorn-kubernetes-pod-controller: Error syncing Longhorn kubernetes pod monitoring/grafana-75948bb6fd-6tbs5: longhorn-kubernetes-pod-controller: fail to sync monitoring/grafana-75948bb6fd-6tbs5: volume.longhorn.io \"grafana-data\" not found" 
...
time="2021-05-06T17:11:49Z" level=warning msg="longhorn-kubernetes-pod-controller: Dropping Longhorn kubernetes pod monitoring/grafana-75948bb6fd-6tbs5 out of the queue: longhorn-kubernetes-pod-controller: fail to sync monitoring/grafana-75948bb6fd-6tbs5: volume.longhorn.io \"grafana-data\" not found"   
E0506 17:11:49.453724       1 kubernetes_pod_controller.go:144] longhorn-kubernetes-pod-controller: fail to sync monitoring/grafana-75948bb6fd-6tbs5: volume.longhorn.io "grafana-data" not found 
....
```
I have 43 volumes and the message occurs for 5 volumes only. 

I hoped that also this kind of message will go away with the update. What did you think about this kind of message? Should I reopen a separate issue?

**Comment by joshimoo** [comment]
The message means that this longhorn volume is no longer available.
For example if you delete a longhorn volume while a user workload that uses that pvc is still running, the workload will continue running even though the volume is gone and the pod controller will fail to sync the status.

The message itself is harmless, and if you kill the workload pods that are using the no longer existing volume the message should disappear.

cc @PhanLe1010 probably a quick solution is to nuke the pod if the volume is no longer available, same as in the remount requested case, this way the user has visibility since their rescheduled pod will fail to come up, because of the volume no longer existing. What do you think?

See here https://github.com/longhorn/longhorn/issues/2256#issuecomment-780728524

**Comment by joshimoo** [comment]
@rsoika just to check, can you make sure whether the `grafana-data` volume actually exists:
`kubectl get volumes.longhorn.io -n longhorn-system`

**Comment by rsoika** [comment]
...this is the strange thing. The volumes exists:

```
$ kubectl get volumes.longhorn.io -n longhorn-system
NAME                                       STATE      ROBUSTNESS   SCHEDULED   SIZE           NODE             AGE
.....
............
monitoring-grafana-data                    attached   healthy      True        1073741824     tikal-worker-3   117d
.....
```

And the Grafana POD is up and running - and all the data handled by longhorn for this POD/Volume are fine. 

```
$ kubectl get pods -n monitoring
NAME                                  READY   STATUS    RESTARTS   AGE
grafana-75948bb6fd-vr2wr              1/1     Running   0          3h53m
....
```

And this is why the message is confusing:

`longhorn-kubernetes-pod-controller: Dropping Longhorn kubernetes pod monitoring/grafana-75948bb6fd-vr2wr out of the queue: longhorn-kubernetes-pod-controller: fail to sync monitoring/grafana-75948bb6fd-vr2wr: volume.longhorn.io \"grafana-data\" not found"`

The POD 'grafana-75948bb6fd-vr2wr' is up and running

And on the worker node I can see the following longhorn directories:

```
xxx@worker-3:/var/lib/longhorn/replicas$ ls -la
total 180
drwxr-xr-x 45 root root 4096 May  6 18:38 .
drwxr-xr-x  4 root root 4096 Apr 14 23:25 ..
....
drwx------  2 root root 4096 May  6 19:11 monitoring-grafana-data-16be3ef6
.....
```

Could I do anything else to provide better insights?

**Comment by rsoika** [comment]
And also from the Longhorn Web UI everything looks fine:

![image](https://user-images.githubusercontent.com/1339124/117367853-032bf400-aec3-11eb-99d5-ec61b1dbfde9.png)

also the pod with the correct ID is listed

**Comment by rsoika** [comment]
I continued testing - it is really strange.

When I delete the pod with 'kubectl delete ....' than the messages are gone - of course ;-)

Than I restarted my pod with "kubectl apply ....', a new POD is starting - and again the Message is there - now with the new POD ID:

`longhorn-kubernetes-pod-controller: Error syncing Longhorn kubernetes pod monitoring/grafana-75948bb6fd-twv4l: longhorn-kubernetes-pod-controller: fail to sync monitoring/grafana-75948bb6fd-twv4l: volume.longhorn.io \"grafana-data\" not found"  `   

But again within the POD all is fine. My data is there.

This is really strange - isn't it?

**Comment by rsoika** [comment]
Should I reopen a separate Issue for this  `Error syncing Longhorn kubernetes pod` ? I don't think it is related to the initialize topic which should be fixed with the 1.1.1 release.

Thinking more about the problem, I come to the conclusion that it may have be related to network topology within my cluster. The volumes affected from the message are relatively old. In the mean time I replaced some worker nodes with complete new hardware. Also IP addresses have changed. Maybe longhorn tries some outdated hostnames/IPs?

I have the guess that if I backup the volume, delete it and recover it form the backup the issue may disappear. What do you think?

**Comment by joshimoo** [comment]
@rsoika looks like a bug on our end, please do open a new issue. 
It looks like the pvc/pv name is `grafana-data` while the longhorn volume is called `monitoring-grafana-data` 

For the bug report please add the following information.
`kubectl get pv grafana-data -o yaml`
`kubectl get pvc grafana-data -o yaml -n monitoring`
`kubectl get volumes.longhorn.io monitoring-grafana-data -o yaml -n longhorn-system`

cc @PhanLe1010 The code here uses the pv name as volume name which in this case is wrong.
https://github.com/longhorn/longhorn-manager/blob/31c34aa2c7fdfe4a8813afef531f003ae9c7db43/controller/kubernetes_pod_controller.go#L386

I am guessing we can rely on the pv "volumeHandle" but I haven't seen the out of sync case here before, so let's have a look :)

**Comment by rsoika** [comment]
I created a separate issue - so you may close this one.

**Comment by voarsh2** [comment]
I am getting an issue where Kubernetes thinks a PVC is attached to a node, but Longhorn shows as not attached. And the PVC has no running POD for the PVC.....

```
AttachVolume.Attach failed for volume "pvc-479f87b3-105d-43ac-bd33-15f51eb61987" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to attach volume pvc-479f87b3-105d-43ac-bd33-15f51eb61987 to worker2: non migratable volume pvc-479f87b3-105d-43ac-bd33-15f51eb61987 cannot attach to node worker2 is already attached to node worker3] from [http://longhorn-backend:9500/v1/volumes/pvc-479f87b3-105d-43ac-bd33-15f51eb61987?action=attach]
```

**Comment by PhanLe1010** [comment]
@voarsh2 

Next time it happens, can you upload a Longhorn support bundle? I want to double-check if it is the same as the known issue https://github.com/longhorn/longhorn/issues/2527#issuecomment-966597537

**Comment by zhanglt** [comment]
The same as 
time="2022-04-10T08:28:54Z" level=warning msg="Dropping Longhorn volume longhorn-system/pvc-7421f837-2ae7-499d-9bd0-a3adfc69cd28 out of the queue" controller=longhorn-volume error="fail to sync longhorn-system/pvc-7421f837-2ae7-499d-9bd0-a3adfc69cd28: fail to reconcile volume state for pvc-7421f837-2ae7-499d-9bd0-a3adfc69cd28: volume pvc-7421f837-2ae7-499d-9bd0-a3adfc69cd28 has already attached to node node2, but asked to attach to node master" node=master
![image](https://user-images.githubusercontent.com/3722170/162609872-aafb9514-a24a-4a1f-9b51-2dfabbe26a81.png)
