### ISSUE TITLE
[BUG] Configures Kubernetes Taint Toleration sometimes not work 

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#2455]
**Describe the bug**

Configures Kubernetes Taint Toleration sometimes not work.

**To Reproduce**
1. Add taint to the control plane node
    ```shell
   kubectl taint nodes <control-plane-node> control-plane:NoSchedule
   ```
2. Go to Setting > General >  Kubernetes Taint Toleration
    ```
   control-plane:NoSchedule
   ```
3. Get the pods on the control plane node
   ```shell
    kubectl get pod -o wide --field-selector spec.nodeName=<control-plane-node>
   ```
4. The instance-manager-r, instance-manager-e, longhorn-csi-plugin, and engine-image-ei still exist
   ```
   $ kubectl get pod --field-selector spec.nodeName=jenting-k3s-master-0
   NAME                             READY   STATUS    RESTARTS   AGE
   engine-image-ei-d25fa25d-wx4p9   1/1     Running   0          55s
   instance-manager-e-c89307be      1/1     Running   0          85s
   instance-manager-r-f0ddd730      1/1     Running   0          85s
   longhorn-csi-plugin-sngg9        2/2     Running   0          79s
   longhorn-manager-7gkqd           1/1     Running   0          4m48s
   ```

**Expected behavior**

The pods of system-managed components (e.g, instance manager, engine image, CSI driver, etc.) should be deleted at all.

**Log**

**Environment:**
 - Longhorn version: v1.1.1-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s v1.20.4+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: SLES15 SP2
   - CPU per node: 4
   - Memory per node: 8G
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 0

**Additional context**

**Comment by PhanLe1010** [comment]
@jenting 
What is the observed behavior?

**Comment by jenting** [comment]
Mostly, the instance-manager-r and instance-manager-e won't be deleted. If I manually delete the Pods, it work.
Not sure is the problem comes that longhorn-manager got deleted before other system components.

**Comment by PhanLe1010** [comment]
In v1.1.1 Longhorn manager, driver, ui pods should not be deleted.

**Comment by PhanLe1010** [comment]
@jenting 

The expected behavior should be:
1. The pod of Longhorn manager, driver, ui pods should not be deleted.
2. The pods of system-managed components should be deleted and recreated immediately. Because those components have the same toleration as the taint on the node, they should exist.

From what you reported:
```
$ kubectl get pod --field-selector spec.nodeName=jenting-k3s-master-0
NAME                             READY   STATUS    RESTARTS   AGE
engine-image-ei-d25fa25d-wx4p9   1/1     Running   0          55s
instance-manager-e-c89307be      1/1     Running   0          85s
instance-manager-r-f0ddd730      1/1     Running   0          85s
longhorn-csi-plugin-sngg9        2/2     Running   0          79s
longhorn-manager-7gkqd           1/1     Running   0          4m48s
```
and what I just tested following the same reproduce steps, it seems that Longhorn is working as expected. We can see that the engine image, instance manager, csi, ... are just recreated (~85s) while the manager has the age 4m48s.

Can you double-check to see if this is still an issue?

**Comment by jenting** [comment]
After discuss with @PhanLe1010, it's not an issue.

If we want to limit Longhorn deployed on worker nodes only, we could add taint to the control plane node
```shell
kubectl taint nodes <control-plane-node> node-role.kubernetes.io/controlplane=true:NoSchedule
```
then, no need to configure the Kubernetes Taint Toleration setting.
