### ISSUE TITLE
[TASK] Add the way of generating support bundle into the doc

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2458]
Thanks to @joshimoo , we have figured out a way to get support bundle in case UI isn't available.

We should put it in the official doc Troubleshooting section, so we can find it when needed.

https://gist.github.com/joshimoo/cdf2995e5c517a74b588bab59dbf3a1f

**Comment by innobead** [comment]
@khushboo-rancher as I mentioned, please help verify the script again then close it. Thanks.

**Comment by khushboo-rancher** [comment]
Verified the script with Longhorn v1.1.1-rc1, this is working fine.
Validation -**Pass**
