### ISSUE TITLE
[BUG] Unlimited volume replica rebuilding causes system unstable like latency of etcd access

### ISSUE THREAD

**Issue by guangbochen** [longhorn/longhorn#2460]
**Is your feature request related to a problem? Please describe.**
after a node reboot, the longhorn volume will trigger the volumes rebuilding upon the checksum validation, however, when the node has a lot of volumes that needs to rebuild it will result in a very high disk I/O and may even kill the k3s cluster due to high latency of ETCD check.

**Describe the solution you'd like**
Add a queue to only performing a limited number of volume rebuilding at the same time, e.g 5 volumes simultaneously.

**Describe alternatives you've considered**
In the Harvester environment, a single bare-metal node may contain more than 100 VMs so the rebuilding mechanism is critical to its disk I/O performance.

**Additional context**
![image](https://user-images.githubusercontent.com/4569037/114121024-3610b580-9920-11eb-9982-e608588ada09.png)

**Comment by liyimeng** [comment]
This is something need to consider. I have similar concern when discussing with shuo-wu in https://github.com/longhorn/longhorn/issues/2303 

I wanna ask again: is it possible to take a  snapshot before node reboot, then rebuild only catch up from that point in time, but not going through entire volume? when the volume is hundred GBs, this is disaster for the node.

**Comment by yasker** [comment]
Considering increase the priority of this issue.

**Comment by yasker** [comment]
It is similar to https://github.com/longhorn/longhorn/issues/588 , though we've decided to do pause instead of limit instead in the end.

We still need to consider the bandwidth/IO needed for rebuilding, may also need to consider the source/target replica's disk/node for bandwidth/IO consumption.

**Comment by joshimoo** [comment]
Also need to consider CPU consumption, since rebuilds are expensive.
- extent retrieval syscall
- checksum calculation server/client

**Comment by yasker** [comment]
Raise the priority since it has a high impact on node reboot case if we cannot throttle the rebuilding work.

**Comment by yasker** [comment]
Lower the priority to P2. We can fix this in v1.2.1.

**Comment by shuo-wu** [comment]
> It is similar to #588 , though we've decided to do pause instead of limit instead in the end.

What's the final solution for this issue? Do pause or throttle the concurrent rebuilding count?

**Comment by innobead** [comment]
> > It is similar to #588 , though we've decided to do pause instead of limit instead in the end.
> 
> What's the final solution for this issue? Do pause or throttle the concurrent rebuilding count?

https://github.com/longhorn/longhorn/issues/307 was introduced for pausing the rebuilding. In this issue, probably need to continue some efforts from https://github.com/longhorn/longhorn/issues/307#issuecomment-630630237.

**Comment by shuo-wu** [comment]
> #307 was introduced for pausing the rebuilding. In this issue, probably need to continue some efforts from [#307 (comment)](https://github.com/longhorn/longhorn/issues/307#issuecomment-630630237).

OK. Then we still need a setting to control the concurrent count. There are 2 sub-questions here:
1. If this concurrent count is a per-node restriction or the cluster level setting.
2. If this concurrent count is a per-node setting, we may need to count the sender replicas as well.

**Comment by innobead** [comment]
> > #307 was introduced for pausing the rebuilding. In this issue, probably need to continue some efforts from [#307 (comment)](https://github.com/longhorn/longhorn/issues/307#issuecomment-630630237).
> 
> OK. Then we still need a setting to control the concurrent count. There are 2 sub-questions here:
> 
> 1. If this concurrent count is a per-node restriction or the cluster level setting.
> 2. If this concurrent count is a per-node setting, we may need to count the sender replicas as well.

If the existing replica scheduler is balance-driven across the cluster, the cluster-level setting is good enough. WDYT? @shuo-wu @yasker

**Comment by shuo-wu** [comment]
> If the current replica scheduler is node/zone balance-driven across the cluster, the cluster-level setting is good enough. WDYT? @shuo-wu @yasker

The feature replica auto-balance is for long-term HA while this concurrent rebuilding is for the performance issue. There is no need to make this concurrent rebuilding limit similar to that setting. Personally, I prefer the 2nd option. Since adding locks and avoiding racing (mentioned in [the comment](https://github.com/longhorn/longhorn/issues/307#issuecomment-630630237)) in node level is much easier. But to finish it in v1.2.1 release, we cannot consider the sender replica at the beginning.

**Comment by yasker** [comment]
I am fine with the node level approach since it's more scalable (e.g. how many replicas can we rebuild at the same time per node). There are two replicas involves in the rebuilding process: sender (healthy replica) and receiver (the replica that's being rebuilt). Ideally we should consider both but it's hard to finish so in v1.2.1 timeline. I am fine with just count the receiver replica for this feature for now.

**Comment by khushboo-rancher** [comment]
Validated with v1.2.x-head

Validation - **Fail**

I changed the setting multiple times and when the setting was 1, I observed there were 3 replicas building together.

<img width="1477" alt="Screen Shot 2021-09-23 at 9 58 04 PM" src="https://user-images.githubusercontent.com/60111667/134620835-7a3949f6-17f1-4129-955b-4bf4d8244caa.png">

[longhorn-support-bundle_79c75abc-1f59-424d-8fe4-4d80f5ed712f_2021-09-24T04-59-54Z.zip](https://github.com/longhorn/longhorn/files/7222966/longhorn-support-bundle_79c75abc-1f59-424d-8fe4-4d80f5ed712f_2021-09-24T04-59-54Z.zip)

**Comment by khushboo-rancher** [comment]
Validated with longhorn-master `09/24/2021`

Validation - **Failed**

For the setting `concurrent replica rebuilding per node limit` 1, the volumes are getting rebuild only one at a time irrespective of nodes.

As per my understanding, if I have 3 nodes, node-1, node-2, node-3 and the setting is 1 then 1 volume attached to node-1, 1 volume attached to node-2, 1 volume attached to node-3 should rebuild together?
