### ISSUE TITLE
[BUG] Node can't be removed from Longhorn UI if scheduling not disabled before removing Longhorn components from the node

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2462]
**Describe the bug**
Node can't be removed from Longhorn UI if scheduling not disabled before removing Longhorn components from the node.

**To Reproduce**
1. Deploy Longhorn v1.1.1-rc1 on 4 worker nodes K8s/k3s cluster.
2. Add taint to a node 'key=val:NoSchedule;key=val:NoExecute'
3. On the Longhorn UI, the node is becomes `Down` with Readiness as `NotReady`
4. Try to remove the node, below error is shown as the node was not disabled before adding the taint. Also, the `Disable node` option is not available now once the node is down.
<img width="1763" alt="Screen Shot 2021-04-10 at 12 57 40 AM" src="https://user-images.githubusercontent.com/60111667/114233198-9e03e200-999a-11eb-9220-53b2133708cc.png">

**Expected behavior**
Allow user to disable node and remove the node or ignore the `schedulable true` condition when user is trying to delete node and there is no replica on the node.

**Environment:**
 - Longhorn version: Longhorn v1.1.1-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

**Comment by innobead** [comment]
cc @c3y1huang @smallteeths

**Comment by khushboo-rancher** [comment]
There is difference between behavior of the delete button at the top and the remove node option in the menu.
<img width="1768" alt="Screen Shot 2021-04-12 at 11 46 05 AM" src="https://user-images.githubusercontent.com/60111667/114349209-3b226e80-9b85-11eb-9e3b-3b9c8d3b5084.png">

1. The `Delete` button at the top is enabled even when there is a replica running on the node.
2. The reported problem occurs when `Remove Node` option is used to remove the node only.
   - On clicking the `Delete` button, two api request is sent to the backend
      a. **PUT request** - `https://rancher-proxy/k8s/clusters/c-xxxx/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/v1/nodes/ip`
           **Request payload** - 
```
{"actions":{"diskUpdate":"https://khushlh.qa.rancher.space/v1/nodes/ip?action=diskUpdate"},"address":"","allowScheduling":false,"conditions":{"MountPropagation":{"lastProbeTime":"","lastTransitionTime":"2021-04-12T06:06:23Z","message":"","reason":"","status":"True","type":"MountPropagation"},"Ready":{"lastProbeTime":"","lastTransitionTime":"2021-04-12T06:06:50Z","message":"manager pod missing: node ip- has no manager pod running on it","reason":"ManagerPodMissing","status":"False","type":"Ready"},"Schedulable":{"lastProbeTime":"","lastTransitionTime":"2021-04-12T06:06:22Z","message":"","reason":"","status":"True","type":"Schedulable"}},"disks":{"default-disk-1030300000000":{"allowScheduling":true,"conditions":{"Ready":{"lastProbeTime":"","lastTransitionTime":"2021-04-12T06:06:23Z","message":"Disk default-disk-1030300000000(/var/lib/longhorn/) on node ip is ready","reason":"","status":"True","type":"Ready"},"Schedulable":{"lastProbeTime":"","lastTransitionTime":"2021-04-12T06:06:23Z","message":"Disk default-disk-1030300000000(/var/lib/longhorn/) on node ip is schedulable","reason":"","status":"True","type":"Schedulable"}},"diskUUID":"a8e2ecec-3f43-4362-81e1-ffdcad5f4d49","evictionRequested":false,"path":"/var/lib/longhorn/","scheduledReplica":{},"storageAvailable":45447028736,"storageMaximum":53652467712,"storageReserved":16095740313,"storageScheduled":0,"tags":null,"replicas":[]}},"engineManagerCPURequest":0,"evictionRequested":false,"id":"ip-","links":{"self":"https://khushlh.qa.rancher.space/v1/nodes/ip-"},"name":"ip","region":"","replicaManagerCPURequest":0,"tags":null,"type":"node","zone":"","replicas":[],"status":{"key":"down","name":"Down"}}
```
b. **DELETE request** - `https://rancher-proxy/k8s/clusters/c-xxxx/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/v1/nodes/ip`
  - On clicking `Remove node` option from the menu, only one request is sent to the backend.
     a. **DELETE request** - `https://rancher-proxy/k8s/clusters/c-xxxx/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/v1/nodes/ip`

**Comment by innobead** [comment]
@smallteeths please help with that to make the behavior consistent. thanks.

**Comment by smallteeths** [comment]
Ok

**Comment by khushboo-rancher** [comment]
@smallteeths Can we add the alert message `Are you sure you want to remove the --- node?` to the `Remove Node` option too. 
<img width="1235" alt="Screen Shot 2021-04-12 at 3 23 12 PM" src="https://user-images.githubusercontent.com/60111667/114436178-a64e5e00-9be2-11eb-8319-94dee25bd1e4.png">

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master `9ced10b`

Validation - **Pass**

The `remove node` and `Delete` are consistent in behavior and deletes the node from Longhorn if satisfy the condition `node ready condition = False`, `node schedulable = False`, `0 replica` and `0 engine`
The `remove node` and `delete` deletes the replica on the node first (if it is not the only one or not detached) and then make node `unschedulable` and deletes the node.

Validated the bulk operation also, only the node which satisfy the conditions.
