### ISSUE TITLE
[BUG] RWX doesn't work with Degraded Availability

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2463]
**Describe the bug**
Pod attached to RWX volume fails to come up if there are insufficient nodes available.

**To Reproduce**
1. Deploy Longhorn v1.1.1-rc1 on a 3 worker nodes cluster.
2. Power down a node and make sure `Allow Volume Creation with Degraded Availability` is enabled.
3. Create deployment with RWX PVC.
4. Deployment pod fails to come up with below error. Share-manager pod comes up properly.
```
AttachVolume.Attach failed for volume "pvc-8ab59862-17af-40f8-a925-c8f0912e5845" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [detail=, message=unable to attach volume pvc-8ab59862-17af-40f8-a925-c8f0912e5845 to khush-test-rc1-wk1: volume pvc-8ab59862-17af-40f8-a925-c8f0912e5845 cannot be scheduled due to lack of nodes or disks satisfied the space requirement, code=Server Error] from [http://longhorn-backend:9500/v1/volumes/pvc-8ab59862-17af-40f8-a925-c8f0912e5845?action=attach]
```
<img width="1377" alt="Screen Shot 2021-04-10 at 2 45 46 AM" src="https://user-images.githubusercontent.com/60111667/114243443-335aa280-99aa-11eb-8042-42d25453bc00.png">

**Expected behavior**
The pod should come up and should get attached to the volume in degraded state.

**Log**
[longhorn-support-bundle_a09388b8-1f8e-47b5-824f-2e0c0468d4fb_2021-04-09T21-30-00Z.zip](https://github.com/longhorn/longhorn/files/6288623/longhorn-support-bundle_a09388b8-1f8e-47b5-824f-2e0c0468d4fb_2021-04-09T21-30-00Z.zip)

Volume name - pvc-8ab59862-17af-40f8-a925-c8f0912e5845
Deployment name - wk-many-3
Time - ~ 2021-04-09 21:25:00 UTC

**Environment:**
 - Longhorn version: v1.1.1-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE - K8s v1.20.5
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: ubuntu 20.04
   - CPU per node: 2
   - Memory per node: 4 GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 5 GB
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): DO
 - Number of Longhorn volumes in the cluster: 5

**Comment by joshimoo** [comment]
@khushboo-rancher does this happen for RWO volumes as well?


The message is related to this scheduling check done during the attach call, since this happens for all volume attachments I am assuming this happens for RWO volumes as well?
https://github.com/longhorn/longhorn-manager/blob/08c89c2d5e36f5585df7939bbbdb94fe47562f45/manager/volume.go#L325-L328

**Comment by khushboo-rancher** [comment]
@joshimoo No, the error is not seen with RWO volumes.

**Comment by innobead** [comment]
@khushboo-rancher will check if this is a regression or a new issue.

**Comment by khushboo-rancher** [comment]
This is a regression, Working fine with Longhorn v1.1.0
