### ISSUE TITLE
[BUG] In case upgrading from v1.0.1 to v1.1.1-rc1, instance manager will not recreated in case of  changing Guaranteed Engine Manager CPU and Guaranteed Replica Manager CPU values.

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#2464]
**Describe the bug**
see title

**To Reproduce**
1. Install Longhorn v1.0.0
2. Upgrade to Longhorn v1.1.1-rc1
3. Update `Guaranteed Engine Manager CPU`  and `Guaranteed Replica Manager CPU` to different values.
4. Wait for instance manager recreation.

**Expected behavior**
Instance manager pods should be recreated using the new limits.

**Log**
N/A

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.1.1-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: 18.04
   - CPU per node: 2
   - Memory per node: 4GB
   - Disk type(e.g. SSD/NVMe): 80 GB
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster: None

**Additional context**
N/A

**Comment by innobead** [comment]
cc @shuo-wu

**Comment by khushboo-rancher** [comment]
There is a note on the setting page that `This global setting will be ignored for a node if the field "ReplicaManagerCPURequest" on the node is set`. To make the `Guaranteed Engine Manager CPU`  and `Guaranteed Replica Manager CPU` effective user has to remove the `ReplicaManagerCPURequest` from the yaml.

Reference:
https://github.com/longhorn/longhorn/issues/2207#issuecomment-812108580
Point 5 - https://longhorn.github.io/longhorn-tests/manual/release-specific/v1.1.1/system-upgrade-with-deprecated-cpu-setting/

**Comment by innobead** [comment]
@meldafrawi please help close this w/ `wontfix` if this is the expected as per @shuo-wu and @khushboo-rancher info. Thanks.

**Comment by shuo-wu** [comment]
And here is the explanation doc: https://github.com/longhorn/website/pull/281

**Comment by meldafrawi** [comment]
Validated, Thanks @innobead @shuo-wu @khushboo-rancher
