### ISSUE TITLE
[QUESTION]  Detached volume - can't delete through UI - doesn't seem to do anything - support bundle attached, ui bug ?

### ISSUE THREAD

**Issue by iangregsondev** [longhorn/longhorn#2467]
Hi,

Can anyone help ?

I have 6 detached volumes, they are old volumes with no PVC. In the UI - I can see them, but I just want to delete them. But when I use the UI and try to delete, nothing seems to happen, the 6 detached volumes remain,.

Am I doing something wrong ?

I will attached a support file.

**Comment by iangregsondev** [comment]
[longhorn-support-bundle_7f81eb7b-b909-44d7-ba2e-4902983e6fc3_2021-04-11T08-05-38Z.zip](https://github.com/longhorn/longhorn/files/6291366/longhorn-support-bundle_7f81eb7b-b909-44d7-ba2e-4902983e6fc3_2021-04-11T08-05-38Z.zip)

Its probably me :-( But I thought it would be as simple as just deleting them. They are not in use.

You can probably see I have 10 volumes, 6 of which are detached, these detached volumes are not needed anymore.

Can anyone help ?

Thanks.

**Comment by iangregsondev** [comment]
The way I am deleting it, which I believe is correct ? Is by doing the following, but it just disappears and I don't see any events being launched..

![image](https://user-images.githubusercontent.com/2370364/114296957-4bb3e580-9aae-11eb-9493-cc250eec9d1a.png)

**Comment by iangregsondev** [comment]
Ok weird, is this a bug ? I managed to remove them via the UI. Basically the context menu on the right (Operation - indicated by the red arrow below) - it never worked via that, but if I highlight the Volumes (detached ones only) and then click the big Delete button (indicated by the green arrow below) - then it seems to work. Confused :-)

Here is an example (it shows a healthy volume - but it's only for demonstration purposes as all my detached volumes have now disappeared.

![image](https://user-images.githubusercontent.com/2370364/114297367-7bfc8380-9ab0-11eb-9337-95fb48a37d5f.png)

Trying to find out if I was doing something wrong or if it's a bug, any ideas?

Maybe it was pure chance that it got removed and worked - maybe there was some delay - I am unsure..

**Comment by innobead** [comment]
cc @khushboo-rancher @meldafrawi @smallteeths  is this a regression?

**Comment by smallteeths** [comment]
I haven't revised the related issues recently.

For the front-end, the api request are the same for both bulk and individual delete operations.  I'm not sure that the reason volume didn't delete successfully is that the conditions for deletion were not met on the back end.
![Jietu20210412-110151](https://user-images.githubusercontent.com/27733391/114335460-63a76a00-9b7f-11eb-8259-fc2d5cc8150a.jpg)

One more thing weird. longhorn will prompt you when deleting a volume with an associated pvc as shown here
![Jietu20210412-103707](https://user-images.githubusercontent.com/27733391/114335625-bf71f300-9b7f-11eb-8d58-09d7f662f1db.jpg)

@innobead

**Comment by iangregsondev** [comment]
Hi, I can confirm that the reason it didn't prompt to delete a volume with an associated pvc in my example was that I removed the pvc manually in k8s.

Although I have managed to do reproduce it a few times - so this isn't related to the issue..

I tried deleting a new volume in the UI with the pvc in tact and sometimes it works and other times it doesn't.

The way to fix this is to click around the screens and eventually, I can delete them.

**Comment by iangregsondev** [comment]
Not sure if this is the right place - but I thought I would also tag onto this...

I noticed another UI issue. So I was adding S3 backup stuff, went into Settings, added the backup fields for s3... clicked Save - I 100% clicked save :-)

Went to backup, told me it was missing....

So tried it again, seems like if I click save 3 / 4 times, then I can guarantee that it saves..

Went to the backup, and now sure enough the data has been saved.

**Comment by jenting** [comment]
> Not sure if this is the right place - but I thought I would also tag onto this...
> 
> I noticed another UI issue. So I was adding S3 backup stuff, went into Settings, added the backup fields for s3... clicked Save - I 100% clicked save :-)
> 
> Went to backup, told me it was missing....
> 
> So tried it again, seems like if I click save 3 / 4 times, then I can guarantee that it saves..
> 
> Went to the backup, and now sure enough the data has been saved.

@iangregsondev 
I'd prefer to open another issue to report this, thank you.

**Comment by jenting** [comment]
Could you please explain how you address the issue eventually? Attach the screenshot would help us to understand, thank you.

> Hi, I can confirm that the reason it didn't prompt to delete a volume with an associated pvc in my example was that I removed the pvc manually in k8s.
> 
> Although I have managed to do reproduce it a few times - so this isn't related to the issue..
> 
> I tried deleting a new volume in the UI with the pvc in tact and sometimes it works and other times it doesn't.
> 
> The way to fix this is to click around the screens and eventually, I can delete them.

**Comment by iangregsondev** [comment]
Hi @jenting , adding screenshots isn't going to help in this case BUT I can explain it quite easily and I am able to reproduce it.

I will give you an example, I just want into the UI and saw I had a number of volumes in a detached state, tried remove one by one using the context menu to the right - that didn't work.

Even tried highlighting all (left options) and clicking Delete - and still it just sits there..

Refresh the browser and I was able to delete them.

It's very weird, I can for sure reproduce it - so I didn't really fix it - I sort of workaround it.

Hence, if it doesn't work, refresh and try again.

**Comment by iangregsondev** [comment]
> > Not sure if this is the right place - but I thought I would also tag onto this...
> > I noticed another UI issue. So I was adding S3 backup stuff, went into Settings, added the backup fields for s3... clicked Save - I 100% clicked save :-)
> > Went to backup, told me it was missing....
> > So tried it again, seems like if I click save 3 / 4 times, then I can guarantee that it saves..
> > Went to the backup, and now sure enough the data has been saved.
> 
> @iangregsondev
> I'd prefer to open another issue to report this, thank you.

Do you want me to open an issue with this as well then? Or are you going to do It?

Again, I don't think screenshots will happen in this case either, but it's easy to reproduce, using the steps that I outlined.

Let me know.

**Comment by jenting** [comment]
> 
> Do you want me to open an issue with this as well then? Or are you going to do It?

Please help open an issue for this one, thank you.

**Comment by jenting** [comment]
@iangregsondev
For you longhorn cluster, did you fresh install it? Or did you upgrade it from v1.0.x to v1.1.0?

**Comment by iangregsondev** [comment]
@jenting yes it was a fresh install using Helm.

The install is quite new, I think less than 1 month.

**Comment by iangregsondev** [comment]
@jenting I opened up an issue for the settings UI issue, sorry for the delay.

**Comment by joshimoo** [comment]
ref created UI issue: https://github.com/longhorn/longhorn/issues/2493

**Comment by jenting** [comment]
> Ok weird, is this a bug ? I managed to remove them via the UI. Basically the context menu on the right (Operation - indicated by the red arrow below) - it never worked via that, but if I highlight the Volumes (detached ones only) and then click the big Delete button (indicated by the green arrow below) - then it seems to work. Confused :-)
> 
> Here is an example (it shows a healthy volume - but it's only for demonstration purposes as all my detached volumes have now disappeared.
> 
> ![image](https://user-images.githubusercontent.com/2370364/114297367-7bfc8380-9ab0-11eb-9337-95fb48a37d5f.png)
> 
> Trying to find out if I was doing something wrong or if it's a bug, any ideas?
> 
> Maybe it was pure chance that it got removed and worked - maybe there was some delay - I am unsure..
> 
> The original support file I attached above - is when I wasn't able to detach them, so its still valid for giving it a debug - I suppose.

I can't reproduce it. Are you using Traefik 2.x?

**Comment by iangregsondev** [comment]
Yes I am using Traefik 2.x, I saw your reply to my other message.

I am about to try that fix for the other message..

So I presume that it might effect this too ?

**Comment by iangregsondev** [comment]
I think this is also fixed :-) I will re-open this if I get more problems.
