### ISSUE TITLE
[BUG] After adding taint to a node, volume cannot be attached to any other node

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2475]
**Describe the bug**
Volume stuck in attaching after setting taint for a one of it replicas' node

**To Reproduce**
1. Create a cluster of 3 Longhorn nodes. 
2. Create a volume of 3 replicas
3. Set taint `f:b=NoExecute` for a node
4. Wait for Kubernetes to evict workloads from tainted node
5. Attach the volume. Observe that the volume stuck in attaching state

**Expected behavior**
Longhorn should skip the replica on the tainted node and finish attaching volume

**Environment:**
 - Longhorn version: Longhorn master  version - 04/12/21

**Additional context**
The replica controller always set the state of the replica: [status.CurrentState = types.InstanceStateStopped](https://github.com/longhorn/longhorn-manager/blob/08c89c2d5e36f5585df7939bbbdb94fe47562f45/controller/instance_handler.go#L73) when the corresponding instance manager is in error state. On the other hand, the volume controller insists on [waiting until all replicas to be in running state](https://github.com/longhorn/longhorn-manager/blob/08c89c2d5e36f5585df7939bbbdb94fe47562f45/controller/volume_controller.go#L1298) before finishing attaching the volume

**Comment by PhanLe1010** [comment]
Proposal: when the instance manager is in `error` or `unknown` state. We should mark the related replica/engine as `unknown` instead of `stopped`. Then in the volume controller, don't wait for the unknown replica to be running.

**Comment by innobead** [comment]
This is not a regression and it's a day 1 issue.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
