### ISSUE TITLE
[TASK] Update the longhorn rancher chart v1.1.1

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#2487]
### Goals
After v1.1.1 ready, we need to update the rancher chart.

### Definition of Done
- [ ] have a PR to update the rancher chart
- [ ] verify the chart installation and upgrade work as expected

### References
- https://github.com/longhorn/longhorn/issues/2262
- https://github.com/longhorn/longhorn/issues/2061

cc @khushboo-rancher @meldafrawi

**Comment by andruwa13** [comment]
update please chart

**Comment by innobead** [comment]
Closing because it's part of #2529
