### ISSUE TITLE
[QUESTION] Deploying longhorn instance-manager in rke cluster failed.

### ISSUE THREAD

**Issue by XiaoMuYi** [longhorn/longhorn#2488]
**Question**

**Environment:**
 - Longhorn version: v1.1.1-rc1
 - Kubernetes version: v1.18.12
 - Node config
   - OS type and version: 
      CentOS Linux release 7.9.2009
      Kernel 3.10.0-1160.el7.x86_64
   - CPU per node: 24U
   - Memory per node: 64G
   - Disk type: HDD
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Dell Server

**Additional context**
Support for taint has been added to the longhorn.yml file, But the deployment of the master node on the rke cluster still fails. As shown below：
![image](https://user-images.githubusercontent.com/34268642/114650741-5a500600-9d15-11eb-9171-a4051b8b6f4d.png)

The rke cluster master node tag information is as follows：
![image](https://user-images.githubusercontent.com/34268642/114650861-879cb400-9d15-11eb-904c-0160eab46e87.png)

The error message for the longhorn-manager service on the master node looks like this.
```
time="2021-04-14T03:37:25Z" level=warning msg="Error syncing Longhorn engine" controller=longhorn-engine engine=longhorn-system/pvc-f282070f-10ff-4dd0-be6c-f6d0ddc7fb9a-e-1de0ff6f error="fail to sync engine for longhorn-system/pvc-f282070f-10ff-4dd0-be6c-f6d0ddc7fb9a-e-1de0ff6f: invalid Instance Manager instance-manager-e-c5a44306, state: error, IP: " node=master-01
E0414 03:37:25.625918       1 engine_controller.go:196] fail to sync engine for longhorn-system/pvc-f282070f-10ff-4dd0-be6c-f6d0ddc7fb9a-e-1de0ff6f: invalid Instance Manager instance-manager-e-c5a44306, state: error, IP:
time="2021-04-14T03:37:25Z" level=warning msg="Dropping Longhorn engine out of the queue" controller=longhorn-engine engine=longhorn-system/pvc-f282070f-10ff-4dd0-be6c-f6d0ddc7fb9a-e-1de0ff6f error="fail to sync engine for longhorn-system/pvc-f282070f-10ff-4dd0-be6c-f6d0ddc7fb9a-e-1de0ff6f: invalid Instance Manager instance-manager-e-c5a44306, state: error, IP: " node=master-01
time="2021-04-14T03:37:27Z" level=info msg="Created instance manager pod instance-manager-r-ef131bdb for instance manager instance-manager-r-ef131bdb"
```

Can anyone help ?

**Comment by cclhsu** [comment]
Likely related to https://github.com/longhorn/longhorn/issues/2475, masters are set as `node-role.kubernetes.io/etcd=true:NoExecute` long-manager pods is being terminated.

**Comment by jenting** [comment]
Would you please provide the support bundle to us?
You could attach the support bundle in this Github issue or mail it to longhorn-support-bundle@suse.com
Thank you.

**Comment by cclhsu** [comment]
Hi! Can you provide more information on the changes which you make to `longhorn.yml` or steps to reproduce the issue?  When masters label as NoExecute/NoSchdule, Instant-Manager-* are not supposed to be created.  I could not reproduce with issue with similar log provided.

**Comment by XiaoMuYi** [comment]
> Would you please provide the support bundle to us?
> You could attach the support bundle in this Github issue or mail it to [longhorn-support-bundle@suse.com](mailto:longhorn-support-bundle@suse.com)
> Thank you.

Resolved, rolled back to version 1.1.0

**Comment by XiaoMuYi** [comment]
> Hi! Can you provide more information on the changes which you make to `longhorn.yml` or steps to reproduce the issue? When masters label as NoExecute/NoSchdule, Instant-Manager-* are not supposed to be created. I could not reproduce with issue with similar log provided.

Not many changes were made, and the deployment was done via helm. Tested and found that v1.1.1 is not compatible with the tainted configuration. Fallback to 1.1.0 solved the problem

**Comment by jenting** [comment]
Not sure what's your use cases for.
But if you don't want Longhorn cluster running on the control plane node(s), you don't have to add the taint setting to the longhorn.yml.

**Comment by XiaoMuYi** [comment]
Resolved
