### ISSUE TITLE
[BUG] Going to settings and updating things (specifically s3 settings) and clicking save "once" doesn't work.

### ISSUE THREAD

**Issue by iangregsondev** [longhorn/longhorn#2493]
**Describe the bug**

I noticed a UI issue. 

So I was adding S3 backup stuff, went into Settings, added the backup fields for s3... clicked Save - I 100% clicked save :-)

Went to backup, told me it was missing....

So tried it again, seems like if I click save 3 / 4 times, then I can guarantee that it saves..

Went to the backup, and now sure enough the data has been saved.

I am able to reproduce this.. I can work around it so its not major for me, but I thought I would let you know.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s

**Comment by innobead** [comment]
cc @smallteeths @khushboo-rancher

**Comment by jenting** [comment]
@iangregsondev Could you provide the support bundle for this also? We'd like to check if the frontend requests *all* reach the longhorn-manager backend. Thank you.

**Comment by iangregsondev** [comment]
@jenting 

Sure, Actually did some screenshots, you will notice the first one, gives a CORS error, then the second one too, and finally the 3rd one seems to be ok

What I did was go in and attempt to change the backup-targer and just click save and then I liked save again for 2 more times until I saw the backup-target give a 200

Does that help ?

I have created a support bundle, is it safe to paste here ? There are some credentials for the my s3 store ???

![image](https://user-images.githubusercontent.com/2370364/114977515-0fa2cb00-9e88-11eb-834d-2a5f48a5853c.png)

![image](https://user-images.githubusercontent.com/2370364/114977527-16314280-9e88-11eb-94df-e66029d6a576.png)

**Comment by iangregsondev** [comment]
I am using k8s with traefik, its hosted on a domain but locked down to only work on local Ips, I suppose I can open it up for you but you will need to contact me privately.

If that helps.

**Comment by jenting** [comment]
> I am using k8s with traefik, its hosted on a domain but locked down to only work on local Ips, I suppose I can open it up for you but you will need to contact me privately.
> 
> If that helps.

Not sure which Traefik version you are using?
If you are using Traefik 2.x, there was an issue with Traefik (CORS), that issue has a workaround.
Can you try the workaround (middleware) mentioned here:
https://github.com/longhorn/longhorn/issues/1442#issuecomment-639761799

**Comment by iangregsondev** [comment]
This works, it seems :-)

Thank you.

I have tried updating the backup target and it doesn't seem to get any CORS issues and it seems to update the first time.

I think you can close this issue now ?

**Comment by jenting** [comment]
Thanks for the update.
