### ISSUE TITLE
[BUG] instance-manager disappeared

### ISSUE THREAD

**Issue by benqwu** [longhorn/longhorn#2498]
**Describe the bug**
Longhorn was running normally before, until today I found that instance-manager disappeared, and I found that longhorn-manager output that:
```
time="2021-04-15T02:18:54Z" level=warning msg="Error syncing Longhorn setting longhorn-system/guaranteed-engine-cpu" controller=longhorn-setting error="fail to sync setting for longhorn-system/guaranteed-engine-cpu: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'" node=localhost

time="2021-04-15T06:43:58Z" level=warning msg="Error syncing Longhorn instance manager longhorn-system/instance-manager-r-662c0689: fail to sync instance manager for longhorn-system/instance-manager-r-662c0689: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"
```

And I found that:
![image](https://user-images.githubusercontent.com/38280874/114827409-3b2ba400-9dfb-11eb-80fa-c24a68d2cbd1.png)
![image](https://user-images.githubusercontent.com/38280874/114828684-c8232d00-9dfc-11eb-8240-25aaad12b824.png)

longhorn UI general settings shows that:
![image](https://user-images.githubusercontent.com/38280874/114827358-294a0100-9dfb-11eb-82fa-594a166d70fe.png)

**To Reproduce**
3. Perform '....'

**Expected behavior**

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: v1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog APP
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.20.5
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Additional context**

**Comment by innobead** [comment]
cc @khushboo-rancher @meldafrawi 

@shuo-wu is it possible for any wrong config causing the instance manager pods recreated failed? do we have any validation around?

**Comment by shuo-wu** [comment]
1. Did anyone manually update this setting via UI or some tools like `kubectl`? Can you provide the reproducing step if possible? 
2. I am not sure if the UI is still using the cache. Please try to refresh the UI.

Besides, you can upload the support bundle then we can take a deep look.

**Comment by benqwu** [comment]
> 1. Did anyone manually update this setting via UI or some tools like `kubectl`? Can you provide the reproducing step if possible?
> 2. I am not sure if the UI is still using the cache. Please try to refresh the UI.
> 
> Besides, you can upload the support bundle then we can take a deep look.
I did not manually modify its value using kubectl. And I don't know how to reproduce this problem, I have not done anything in my memory.
In addition, where can I get the support bundle you mentioned?

**Comment by benqwu** [comment]
> 1. Did anyone manually update this setting via UI or some tools like `kubectl`? Can you provide the reproducing step if possible?
> 2. I am not sure if the UI is still using the cache. Please try to refresh the UI.
> 
> Besides, you can upload the support bundle then we can take a deep look.

I did not manually modify its value using kubectl. And I don't know how to reproduce this problem, I have not done anything in my memory.
In addition, where can I get the support bundle you mentioned?

**Comment by joshimoo** [comment]
@benqwu you can generate a support bundle via the UI
![image](https://user-images.githubusercontent.com/1287163/114998010-c7dc6d80-9ea0-11eb-9237-8accdfd0b92c.png)

**Comment by benqwu** [comment]
> @benqwu you can generate a support bundle via the UI
> ![image](https://user-images.githubusercontent.com/1287163/114998010-c7dc6d80-9ea0-11eb-9237-8accdfd0b92c.png)

Thank you.
longhornversion shows "dirty" because I added some code to output the log in order to find out where it is causing "quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"

[longhorn-support-bundle_5fa47742-84f5-4dd5-a2e7-d8e1b2271b14_2021-04-16T08-55-40Z.zip](https://github.com/longhorn/longhorn/files/6323771/longhorn-support-bundle_5fa47742-84f5-4dd5-a2e7-d8e1b2271b14_2021-04-16T08-55-40Z.zip)

**Comment by jenting** [comment]
The user installs Longhorn on 1 node only with Longhorn version v1.1.0.

Some logs, I can't find it the longhorn-manager v1.1.0 branch, strange 🤔 
```shell
2021-04-16T08:54:23.696826280Z time="2021-04-16T08:54:23Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"localhost\", UID:\"10059ff5-bd16-43d4-b421-4ae61ed5134b\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"2877789\", FieldPath:\"\"}): type: 'Warning' reason: 'Ready' Node localhost is down: the manager pod longhorn-manager-w6xhw is not running"
2021-04-16T08:54:23.848007895Z time="2021-04-16T08:54:23Z" level=warning msg="GetPod instance-manager-e-a2c08f70: <nil>"
2021-04-16T08:54:23.848034557Z time="2021-04-16T08:54:23Z" level=warning msg="DeletePod instance-manager-e-a2c08f70"
2021-04-16T08:54:23.848037935Z time="2021-04-16T08:54:23Z" level=warning msg="Starts to create pod for instance manager instance-manager-e-a2c08f70"
2021-04-16T08:54:23.848040347Z time="2021-04-16T08:54:23Z" level=info msg="instance manager instance-manager-e-a2c08f70"
2021-04-16T08:54:23.848042678Z time="2021-04-16T08:54:23Z" level=warning msg="Marshal []: <nil>"
2021-04-16T08:54:23.848044962Z time="2021-04-16T08:54:23Z" level=warning msg="GetSetting priority-class: <nil>"
2021-04-16T08:54:23.848047303Z time="2021-04-16T08:54:23Z" level=warning msg="GetSettingImagePullPolicy: <nil>"
2021-04-16T08:54:23.848049645Z time="2021-04-16T08:54:23Z" level=warning msg="GetGuaranteedResourceRequirement: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"
2021-04-16T08:54:23.848062514Z time="2021-04-16T08:54:23Z" level=info msg="createEngineManagerPodSpec instance-manager-e-a2c08f70: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"
2021-04-16T08:54:23.848065372Z time="2021-04-16T08:54:23Z" level=warning msg="Error syncing Longhorn instance manager longhorn-system/instance-manager-e-a2c08f70: fail to sync instance manager for longhorn-system/instance-manager-e-a2c08f70: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"```

**Comment by benqwu** [comment]
> The user installs Longhorn on 1 node only with Longhorn version v1.1.0.
> 
> Some logs, I can't find it the longhorn-manager v1.1.0 branch, strange 🤔
> 
> ```shell
> 2021-04-16T08:54:23.696826280Z time="2021-04-16T08:54:23Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"localhost\", UID:\"10059ff5-bd16-43d4-b421-4ae61ed5134b\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"2877789\", FieldPath:\"\"}): type: 'Warning' reason: 'Ready' Node localhost is down: the manager pod longhorn-manager-w6xhw is not running"
> 2021-04-16T08:54:23.848007895Z time="2021-04-16T08:54:23Z" level=warning msg="GetPod instance-manager-e-a2c08f70: <nil>"
> 2021-04-16T08:54:23.848034557Z time="2021-04-16T08:54:23Z" level=warning msg="DeletePod instance-manager-e-a2c08f70"
> 2021-04-16T08:54:23.848037935Z time="2021-04-16T08:54:23Z" level=warning msg="Starts to create pod for instance manager instance-manager-e-a2c08f70"
> 2021-04-16T08:54:23.848040347Z time="2021-04-16T08:54:23Z" level=info msg="instance manager instance-manager-e-a2c08f70"
> 2021-04-16T08:54:23.848042678Z time="2021-04-16T08:54:23Z" level=warning msg="Marshal []: <nil>"
> 2021-04-16T08:54:23.848044962Z time="2021-04-16T08:54:23Z" level=warning msg="GetSetting priority-class: <nil>"
> 2021-04-16T08:54:23.848047303Z time="2021-04-16T08:54:23Z" level=warning msg="GetSettingImagePullPolicy: <nil>"
> 2021-04-16T08:54:23.848049645Z time="2021-04-16T08:54:23Z" level=warning msg="GetGuaranteedResourceRequirement: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"
> 2021-04-16T08:54:23.848062514Z time="2021-04-16T08:54:23Z" level=info msg="createEngineManagerPodSpec instance-manager-e-a2c08f70: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"
> 2021-04-16T08:54:23.848065372Z time="2021-04-16T08:54:23Z" level=warning msg="Error syncing Longhorn instance manager longhorn-system/instance-manager-e-a2c08f70: fail to sync instance manager for longhorn-system/instance-manager-e-a2c08f70: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"```
> ```

Sorry, I added some code to output the log in order to find out where it is causing "quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP][-+]?[0-9])$'"，but I did not modify the logic of longhorn-manager.

**Comment by shuo-wu** [comment]
Somehow the setting `guaranteed-engine-cpu` becomes empty in your Longhorn system. I am not sure if this setting is modified by other applications. Longhorn won't update it without receiving a request from users.

To recover instance managers, you need to set a float value for the setting. You can set it via UI or `kubectl -n longhorn-system edit settings guaranteed-engine-cpu`

**Comment by benqwu** [comment]
> Somehow the setting `guaranteed-engine-cpu` becomes empty in your Longhorn system. I am not sure if this setting is modified by other applications. Longhorn won't update it without receiving a request from users.
> 
> To recover instance managers, you need to set a float value for the setting. You can set it via UI or `kubectl -n longhorn-system edit settings guaranteed-engine-cpu`

Thanks, I will see if it will appear again next time.
