### ISSUE TITLE
[TASK] Add document for how to install Longhorn in Rancher Windows Cluster

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2501]
Longhorn allows user to set toleration and recently allow the users to set [node selector](https://github.com/longhorn/longhorn/issues/2199). This enables the users to install Longhorn in a Rancher Windows cluster. 

We need to create some document to guide the user through the installation process

**Comment by innobead** [comment]
Closing because https://longhorn.io/docs/1.1.1/advanced-resources/deploy/rancher_windows_cluster/ already finished in 1.1.1.
