### ISSUE TITLE
[BUG] The bulk delete for backing image button doesn't work if there are few images don't satisfy deletion condition.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2506]
**Describe the bug**
If there are 3 backing image on a 3 nodes where 2 backing images can't be deleted as replicas are running on them and only 1  image can be deleted the delete button doesn't work.
<img width="801" alt="Screen Shot 2021-04-18 at 2 03 28 AM" src="https://user-images.githubusercontent.com/60111667/115126269-64ab2200-9feb-11eb-9074-51a2e888e3a7.png">
<img width="1781" alt="Screen Shot 2021-04-18 at 1 58 53 AM" src="https://user-images.githubusercontent.com/60111667/115126293-9a500b00-9feb-11eb-970c-57c15da5747d.png">

**To Reproduce**
1. Deploy Longhorn-master on a K8s cluster with 3 worker nodes.
2. Create a backing image.
3. Create a volume with 3 replicas. Attach the volume to a node.
4. Check the details in the backing image page, 3 images will be shown on 3 disks.
5. Update replica of volume to 2 and delete a replica on 3rd node.
6. Now select all the images and delete them.
7. Error is shown on the page that `cannot delete the image as at least a replica is running` for all the disks and it doesn't delete the image form 3rd node.
**Note:** If the delete option is used from drop down menu of node 3, it successfully deleted the image.
8. The error message is not proper and says `Are you sure to delete the disks .. ?`

**Expected behavior**
1. Only the disk where replica is using the backing image should not be deleted. The one with no replica running should get deleted.
2. The error message should say `Are you sure to delete the images from the disks .. .. ?`

**Environment:**
 - Longhorn version: Longhorn-master -`04/18/2021`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

**Comment by innobead** [comment]
We don't need to fix this right now, but we need to make sure all bulk operations behavior consistent.

The bulk operation can't be partially successful, and if users want to delete some of them instead, just choose the right items to delete.

**Comment by innobead** [comment]
@khushboo-rancher please help check if this was fixed w/ the consistent behavior with other bulk operations.

```
The bulk operation can't be partially successful, and if users want to delete some of them instead, just choose the right items to delete.
```

**Comment by khushboo-rancher** [comment]
> The bulk operation can't be partially successful, and if users want to delete some of them instead, just choose the right items to delete.
On choosing right one, it is working fine.

There is a typo on the alert message, `Are you sure to delete images image file from the disk`. It should be `Are you sure to delete image file from the disk`.
<img width="655" alt="Screen Shot 2021-05-03 at 4 44 53 PM" src="https://user-images.githubusercontent.com/60111667/116946611-71588880-ac2f-11eb-93be-e319c7d8817e.png">

**Comment by innobead** [comment]
@khushboo-rancher is this still a valid issue?

**Comment by khushboo-rancher** [comment]
The typo is fixed already. Closing the issue.
