### ISSUE TITLE
[BUG] Changing the replica count doesn't reduce them in some cases

### ISSUE THREAD

**Issue by iangregsondev** [longhorn/longhorn#2508]
**Describe the bug**

I recently took all my volumes and made then have a replica count of 2,( previously it was 3).

Most of the volumes have gone back to 2 but there are some that have not.  Is this right ?

Here is a screenshot to explain the issue, these were changed to 2 replicas a while ago, over a week. As I say most volumes are displaying just 2 replicas but there are some with the 3 replicas still

![image](https://user-images.githubusercontent.com/2370364/115147457-58f74400-a05b-11eb-825b-023a1f2892df.png)

**To Reproduce**

Using the UI, I just updated the replica count.

**Environment:**
 - Longhorn version:.1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3

**Comment by iangregsondev** [comment]
I have some more info here, p.s. I am using the workaround with traefik but its still the same..

for example, I have a volume that displays 3 replicas (previously I set this to 2 a number of times) - I automatically set it to 1 - but the 3 replicas remain. This is the outgoing call

![image](https://user-images.githubusercontent.com/2370364/115182875-0a898a00-a0db-11eb-8cd6-94c76459a8e7.png)

I don't see anything happening on the UI logs for longhorn

Next - I thought I would delete a replica manually - ensuring I don't delete the replica that is currently set as "Attached Node & Endpoint"

And I got this, so it removed it :-) But it appears it doesn't know what it was. I confirm now that there are 2 replicas - but this is still kind of wrong - as for testing, I set It to 1.

![image](https://user-images.githubusercontent.com/2370364/115183176-94395780-a0db-11eb-88ea-f61a69a193bb.png)

![image](https://user-images.githubusercontent.com/2370364/115183232-aadfae80-a0db-11eb-8aab-d8bf6e474fab.png)


When removing the replica i see this

```
Removed unknown replica tcp://10.42.2.85:10015 from engine
```

and also

```
Detected replica UNKNOWN-tcp://10.42.2.85:10015 (10.42.2.85:10015) has been rebuilded
```

**Comment by iangregsondev** [comment]
Anything I can do to fix it ??

Can it be rebuilt of something ?

Maybe the replicas are not being removed because it doesn't recognise them ? Not sure..

As I say, this error continues even with the Traefik workaround added for CORS but...

Maybe it was originally caused by this error and something become unsynced ?


Guessing :-) AHHAHA

**Comment by jenting** [comment]
@iangregsondev 
The number of healthy replica count is more than the specified replica count, Longhorn will do nothing.
Ref to https://longhorn.io/docs/1.1.0/concepts/#23-replicas

**Comment by iangregsondev** [comment]
Ah great, my bad, I didn't realise. All done :-) I have deleted the extra replicas manually and I noticed they don't get redeployed.

So I will close this, thanks for all your help.

**Comment by jenting** [comment]
No worries 😃
