### ISSUE TITLE
[BUG] Takes a long time to attache volume large than 16T

### ISSUE THREAD

**Issue by ruruiye** [longhorn/longhorn#2509]
**Describe the bug**
We have deployed longhorn in a 3 nodes system with 200 TB at each node. and created a pvc volume at 64 TB size. Then we try to attach the pvc into a pod, but after a long time (more than half hour), the status is still attaching.

**To Reproduce**
3. Perform '....'

**Expected behavior**

The attach should finished without problem

**Log**
time="2021-04-19T03:16:29Z" level=warning msg="Instance pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-r-529e4cea crashed on Instance Manager instance-manager-r-4f257c58 at master02, try to get log"
time="2021-04-19T03:16:29Z" level=warning msg="pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-r-529e4cea: time=\"2021-04-19T02:48:26Z\" level=info msg=\"Creating volume /host/var/lib/longhorn/replicas/pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-348a51ec, size 70368744177664/512\""
time="2021-04-19T03:16:29Z" level=warning msg="pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-r-529e4cea: time=\"2021-04-19T02:48:26Z\" level=fatal msg=\"Error running start replica command: error: code = FunctionFailedRollbackSucceeded, message = file too large\""
time="2021-04-19T03:16:29Z" level=warning msg="pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-r-529e4cea: time=\"2021-04-19T03:09:07Z\" level=info msg=\"Creating volume /host/var/lib/longhorn/replicas/pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-348a51ec, size 70368744177664/512\""
time="2021-04-19T03:16:29Z" level=warning msg="pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-r-529e4cea: time=\"2021-04-19T03:09:07Z\" level=fatal msg=\"Error running start replica command: error: code = FunctionFailedRollbackSucceeded, message = file too large\""
time="2021-04-19T03:16:29Z" level=warning msg="Instance pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-r-529e4cea is state error, error message: exit status 1"
time="2021-04-19T03:16:29Z" level=warning msg="Instance pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-r-529e4cea crashed on Instance Manager instance-manager-r-4f257c58 at master02, try to get log"
time="2021-04-19T03:16:29Z" level=warning msg="pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-r-529e4cea: time=\"2021-04-19T02:48:26Z\" level=info msg=\"Creating volume /host/var/lib/longhorn/replicas/pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-348a51ec, size 70368744177664/512\""
time="2021-04-19T03:16:29Z" level=warning msg="pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-r-529e4cea: time=\"2021-04-19T02:48:26Z\" level=fatal msg=\"Error running start replica command: error: code = FunctionFailedRollbackSucceeded, message = file too large\""
time="2021-04-19T03:16:29Z" level=warning msg="pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-r-529e4cea: time=\"2021-04-19T03:09:07Z\" level=info msg=\"Creating volume /host/var/lib/longhorn/replicas/pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-348a51ec, size 70368744177664/512\""
time="2021-04-19T03:16:29Z" level=warning msg="pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-r-529e4cea: time=\"2021-04-19T03:09:07Z\" level=fatal msg=\"Error running start replica command: error: code = FunctionFailedRollbackSucceeded, message = file too large\""
time="2021-04-19T03:16:59Z" level=warning msg="Instance pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-r-529e4cea is state error, error message: exit status 1"
time="2021-04-19T03:16:59Z" level=warning msg="Instance pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-r-529e4cea crashed on Instance Manager instance-manager-r-4f257c58 at master02, try to get log"
time="2021-04-19T03:16:59Z" level=warning msg="pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-r-529e4cea: time=\"2021-04-19T02:48:26Z\" level=info msg=\"Creating volume /host/var/lib/longhorn/replicas/pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-348a51ec, size 70368744177664/512\""
time="2021-04-19T03:16:59Z" level=warning msg="pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-r-529e4cea: time=\"2021-04-19T02:48:26Z\" level=fatal msg=\"Error running start replica command: error: code = FunctionFailedRollbackSucceeded, message = file too large\""
time="2021-04-19T03:16:59Z" level=warning msg="pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-r-529e4cea: time=\"2021-04-19T03:09:07Z\" level=info msg=\"Creating volume /host/var/lib/longhorn/replicas/pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-348a51ec, size 70368744177664/512\""
time="2021-04-19T03:16:59Z" level=warning msg="pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df-r-529e4cea: time=\"2021-04-19T03:09:07Z\" level=fatal msg=\"Error running start replica command: error: code = FunctionFailedRollbackSucceeded, message = file too large\""

attacher log
I0419 03:14:11.052727       1 leaderelection.go:283] successfully renewed lease longhorn-system/external-attacher-leader-driver-longhorn-io
I0419 03:14:16.102007       1 leaderelection.go:283] successfully renewed lease longhorn-system/external-attacher-leader-driver-longhorn-io
I0419 03:14:21.133407       1 leaderelection.go:283] successfully renewed lease longhorn-system/external-attacher-leader-driver-longhorn-io
I0419 03:14:26.162015       1 leaderelection.go:283] successfully renewed lease longhorn-system/external-attacher-leader-driver-longhorn-io
I0419 03:14:31.185175       1 leaderelection.go:283] successfully renewed lease longhorn-system/external-attacher-leader-driver-longhorn-io
I0419 03:14:36.222757       1 leaderelection.go:283] successfully renewed lease longhorn-system/external-attacher-leader-driver-longhorn-io
I0419 03:14:41.239679       1 leaderelection.go:283] successfully renewed lease longhorn-system/external-attacher-leader-driver-longhorn-io
I0419 03:14:46.280863       1 leaderelection.go:283] successfully renewed lease longhorn-system/external-attacher-leader-driver-longhorn-io
I0419 03:14:51.306330       1 leaderelection.go:283] successfully renewed lease longhorn-system/external-attacher-leader-driver-longhorn-io
I0419 03:14:56.332871       1 leaderelection.go:283] successfully renewed lease longhorn-system/external-attacher-leader-driver-longhorn-io
I0419 03:15:01.362448       1 leaderelection.go:283] successfully renewed lease longhorn-system/external-attacher-leader-driver-longhorn-io
I0419 03:15:06.390593       1 leaderelection.go:283] successfully renewed lease longhorn-system/external-attacher-leader-driver-longhorn-io
I0419 03:15:11.400008       1 leaderelection.go:283] successfully renewed lease longhorn-system/external-attacher-leader-driver-longhorn-io
I0419 03:15:16.440936       1 leaderelection.go:283] successfully renewed lease longhorn-system/external-attacher-leader-driver-longhorn-io
I0419 03:15:20.256504       1 controller.go:198] Started VA processing "csi-53073d89bdfa2925d34daff041376de1dc5d57672e76fcc2d278ab7b04da9e19"
I0419 03:15:20.256560       1 csi_handler.go:209] CSIHandler: processing VA "csi-53073d89bdfa2925d34daff041376de1dc5d57672e76fcc2d278ab7b04da9e19"
I0419 03:15:20.256574       1 csi_handler.go:236] Attaching "csi-53073d89bdfa2925d34daff041376de1dc5d57672e76fcc2d278ab7b04da9e19"
I0419 03:15:20.256588       1 csi_handler.go:396] Starting attach operation for "csi-53073d89bdfa2925d34daff041376de1dc5d57672e76fcc2d278ab7b04da9e19"
I0419 03:15:20.256707       1 csi_handler.go:329] PV finalizer is already set on "pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df"
I0419 03:15:20.256733       1 csi_handler.go:689] Found NodeID master01 in CSINode master01
I0419 03:15:20.256758       1 csi_handler.go:289] VA finalizer is already set on "csi-53073d89bdfa2925d34daff041376de1dc5d57672e76fcc2d278ab7b04da9e19"
I0419 03:15:20.256772       1 csi_handler.go:303] NodeID annotation is already set on "csi-53073d89bdfa2925d34daff041376de1dc5d57672e76fcc2d278ab7b04da9e19"
I0419 03:15:20.256795       1 connection.go:182] GRPC call: /csi.v1.Controller/ControllerPublishVolume
I0419 03:15:20.256805       1 connection.go:183] GRPC request: {"node_id":"master01","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"baseImage":"","fromBackup":"","numberOfReplicas":"3","staleReplicaTimeout":"30","storage.kubernetes.io/csiProvisionerIdentity":"1618643986760-8081-driver.longhorn.io"},"volume_id":"pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df"}
I0419 03:15:20.269012       1 connection.go:185] GRPC response: {}
I0419 03:15:20.269904       1 connection.go:186] GRPC error: rpc error: code = Aborted desc = The volume pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df is attaching
I0419 03:15:20.269930       1 csi_handler.go:559] Saving attach error to "csi-53073d89bdfa2925d34daff041376de1dc5d57672e76fcc2d278ab7b04da9e19"
I0419 03:15:20.291929       1 csi_handler.go:570] Saved attach error to "csi-53073d89bdfa2925d34daff041376de1dc5d57672e76fcc2d278ab7b04da9e19"
I0419 03:15:20.291965       1 csi_handler.go:219] Error processing "csi-53073d89bdfa2925d34daff041376de1dc5d57672e76fcc2d278ab7b04da9e19": failed to attach: rpc error: code = Aborted desc = The volume pvc-3b36ab80-cc96-4cef-b01d-ca2d39f756df is attaching
I0419 03:15:20.292312       1 controller.go:158] Ignoring VolumeAttachment "csi-53073d89bdfa2925d34daff041376de1dc5d57672e76fcc2d278ab7b04da9e19" change

**Environment:**
 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version: Ubuntu 18.04
   - CPU per node: 2 CPU
   - Memory per node: 256GB
   - Disk type(e.g. SSD/NVMe): HDD
   - Network bandwidth between the nodes: 10Gbi
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Additional context**

**Comment by ruruiye** [comment]
seems this is the limitation of ext4 file system, it has a largest file size limit to 16TB. how can we support large volume then?

**Comment by cclhsu** [comment]
XFS supposes to support volume greater than 16T.  You could create a new storage class with `fsType: xfs` and use the new storage class for PVC.

**Comment by ruruiye** [comment]
The problem fixed after move to use XFS in the host file system. Thanks @cclhsu
