### ISSUE TITLE
UI: Backup or restore, increase success prompt

### ISSUE THREAD

**Issue by rootwuj** [longhorn/longhorn#251]
**Environment:**
Using rke to deploy kubernetes v1.11.1
Longhorn version: v0.3-rc5

**Steps to Reproduce:**
1/ Perform a backup or restore operation.

**Results:**
The page has no success message.
Suggest to add a  success message, or jump to the corresponding page.

**Comment by yasker** [comment]
This needs to be a part of v0.4, Backup progress report.

**Comment by yasker** [comment]
Should be naturally solved by #45 and #49
