### ISSUE TITLE
[BUG] Increase the size of the create backing image form on the Longhorn UI

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2516]
**Describe the bug**
The bigger form of create backing image will look good as it has text box URL
<img width="1769" alt="Screen Shot 2021-04-20 at 10 06 20 PM" src="https://user-images.githubusercontent.com/60111667/115434084-e7b7bc80-a225-11eb-95dc-85e0bd199293.png">

Example screen:
<img width="1765" alt="Screen Shot 2021-04-20 at 10 16 19 PM" src="https://user-images.githubusercontent.com/60111667/115434202-10d84d00-a226-11eb-97f5-788849b504ce.png">

**Environment:**
 - Longhorn version: v1.1.1-rc1

**Comment by jenting** [comment]
Validation the commit `a7a7e7e`: **Pass**

![image](https://user-images.githubusercontent.com/49380831/115657889-42f2c780-a36a-11eb-9051-0f2a65dac4d7.png)
