### ISSUE TITLE
[BUG] csi-attacher is attempting to perform actions on PVC's that no longer exist

### ISSUE THREAD

**Issue by ca-wvestjens** [longhorn/longhorn#2519]
**Describe the bug**
The elected-leader csi-attacher pod is attempting to perform work on PVC's that no longer exist.

**To Reproduce**
Unknown

**Expected behavior**
When a PVC is removed, the csi-attacher no longer tries to perform actions on the PVC.

**Log**
Longhorn support bundle will be sent to the support e-mail due to confidentiality concerns.

**Environment:**
 - Longhorn version: 1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): RKE / Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE v1.2.3, v1.18.12-rancher1-1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 6x2000Mhz
   - Memory per node: 8G
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: Gigabit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Hyporvised
 - Number of Longhorn volumes in the cluster: 3

**Additional context**
We've had some issues with volumes we had to recover in the past, so the PVC's the csi-attacher is trying to perform actions on no longer exists.

**Comment by jenting** [comment]
Support bundle received.

**Comment by cclhsu** [comment]
Hi! It seems that "persistentvolume "pvc-79c871e7-8039-402a-xxxxxxxxxxx" not found", but in `volumeattachments.yaml`, `csi-5b6fb23ca6c977397beeaf4dfab6f034b05ed6xxxxxxxxxxxxxxxxxxx` still existed.  Can you try to manually remove the volume attachment and finalizer to see if the issue is  resolved?

**Comment by ca-wvestjens** [comment]
Thank you for your help so far. I've removed them, but they seem to be stuck in removing state. I believe this is due to the `external-attacher/driver-longhorn-io` finalizer not releasing them. Please advise.

**Comment by shuo-wu** [comment]
You can directly unset the finalizer for the stuck VolumeAttachments. Since they are meaningless in the cluster, it's fine to directly remove them:
```
kubectl patch -p '{"metadata":{"finalizers": null}}' volumeattachment <stuck VolumeAttachment list>
```

**Comment by ca-wvestjens** [comment]
Thank you, that fixed the issue.
