### ISSUE TITLE
[BUG] DR volume inconsistent data on SUSE Linux Enterprise Server 15 SP2

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#2520]
**What's the test? Please describe.**
Activated DR volume have inconsistent data

OS: SUSE Linux Enterprise Server 15 SP2
Longhorn Version: v1.1.1-rc2

Tests to reproduce:
1. Install Longhorn v1.1.1-rc2 on a k8s cluster (1 controlplane node, 3 worker nodes)
2. Create a volume, attach it to a node, write some data (data1), and compute it's checksum.
3. run `sync` command
4. write some more data (data2), and compute it's checksum.
5. create a backup (bkp1), wait for it to complete/
6. Create a DR from the created backup (bkp1).
7. wait for restore to complete.
8. Activate DR volume. attach it to a node, mount it to a directory, and check the created data files.
> data checksum didn't match **FAILED**
9. create a backup (bkp2), wait for it to complete/
10. Create a DR from the created backup (bkp2).
11. wait for restore to complete.
12. Activate DR volume. attach it to a node, mount it to a directory, and check the created data files.
> data checksum didn't match   **FAILED**

**Describe the items of the test (DoD, definition of done) you'd like.**
- [ ] DR volume data should be consistent with created backup

**Additional context**
Add any other context or screenshots about the test request here.

**Comment by innobead** [comment]
related to https://github.com/longhorn/longhorn/issues/2503 

cc @c3y1huang

**Comment by innobead** [comment]
This should be fixed by https://github.com/longhorn/longhorn/issues/2503
