### ISSUE TITLE
There is no need to check old backing image managers

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2521]
**Describe the bug**
since all old backing image managers will be cleaned up directly after the system upgrade, there is no need to check the info in the old managers. The redundancy is in the backing image controller & backing image manager controller. It won’t affect any functionality & performance

**Comment by innobead** [comment]
@shuo-wu is this still valid?

**Comment by shuo-wu** [comment]
No. Let me close it.
