### ISSUE TITLE
[TASK] release v1.1.1

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#2523]
**What's the task? Please describe.**

Action items for releasing v1.1.1

**Describe the items of the task (DoD, definition of done) you'd like.**
  - [x] verify and close the last pending issue https://github.com/longhorn/longhorn/issues/2339 - @PhanLe1010 
  - [x] make sure sanity check finished w/o release blockers - @meldafrawi 
  - [x] release v1.1.1 GA draft w/ all images built, repo tags, chart PR - @innobead 
  - [x] verify v1.1.1 GA draft 
    - [x] run automatic e2e regression @meldafrawi 
    - [x] some mandatory manual regression: longhorn/chart PR install, upgrade) - @meldafrawi @c3y1huang @shuo-wu @jenting 
  - [x] release v1.1.1 (longhorn/longhorn, longhorn/chart, longhorn/website) and make sure doc links correctly in the release note - @innobead 
  - [x] merge v1.1.1 to master (longhorn/longhorn, longhorn/website) - @innobead 
  - [x] have rancher chart PR and image mirror
    - [x] rancher/image-mirror update - @cclhsu @jenting https://github.com/rancher/image-mirror/pull/95
    - [x] rancher/charts master branch for cluster manager - @cclhsu @jenting https://github.com/rancher/charts/pull/1143
    - [x] rancher/charts dev-*-source branches for cluster explore - @cclhsu @jenting https://github.com/rancher/charts/pull/1144
    - [x] verify the chart being able to install & upgrade (#2262 ) - @meldafrawi  @jenting @cclhsu https://github.com/cclhsu/charts/tree/Longhorn_v1.1.1_dev_2.5

**Additional context**
N/A

cc @khushboo-rancher

**Comment by jenting** [comment]
longhorn/charts
- helm install: :white_check_mark:
- helm upgrade (v1.1.0 -> v1.1.1): :white_check_mark:
- Rancher install: :white_check_mark:
- Rancher upgrade (v1.1.0 -> v1.1.1): :white_check_mark:

**Comment by innobead** [comment]
The last item to finish is Rancher charts.

**Comment by jenting** [comment]
I think it deserve to add the v1.1.1 release to the longhorn blog https://longhorn.io/blog/.

**Comment by cclhsu** [comment]
Test Branch:

# Cluster-Explorer
repo: https://github.com/cclhsu/charts
branch: dev-v2.5
edit yaml: change `rancher/mirrored-longhornio-` to `longhornio/`

# Cluster-Mananger
repo: https://github.com/cclhsu/charts
branch: Longhorn_v1.1.0_master

**Comment by khushboo-rancher** [comment]
Validation Pass for cluster-explorer (Done by @meldafrawi ) and cluster-manager with the repo https://github.com/cclhsu/charts

**Comment by cclhsu** [comment]
QA have validated that 
- rancher/charts master branch for cluster manager: Pass
- rancher/charts dev-*-source branches for cluster explore: Pass
  - And Phan has tested that removed [annotation of Linux](https://github.com/rancher/charts/pull/1144/commits/0647c5f67192fe459dfa2fe13ca69a6bbea55f5f) work on mix cluster of LInux and Windows and should be confirmed by QA.
Otherwise, we are waiting maintainer review to merge the charts.

**Comment by PhanLe1010** [comment]
@cclhsu 
We will wait to see if it is ok to remove the linux annotation. If we decide to remove the linux annotation in rancher/charts dev-*-source to allow Longhorn installation in a mixed cluster of Windows and Linux, we want to add some node to the readme.md patch file so user know that they have to add toleration and node selector for mixed clusters.

**Comment by innobead** [comment]
Done.
