### ISSUE TITLE
Support reverse dns on backups

### ISSUE THREAD

**Issue by n0rad** [longhorn/longhorn#2525]
Hi,

NFS is not very secured and one mechanism to limit access is by filtering who can connect using reverse DNS resolution. 
If the NFS server is using the Kubernetes DNS server, access can be filtered by `namespace` or `service`.

```bash
# cat /etc/exports
/nfsshare *.longhorn-backend.longhorn-system.svc.cluster.local(rw,fsid=0,sync)
```
This allows managers to connect to NFS but does not allow backups to do so. `*.longhorn-system.svc.cluster.local` will not work either because backups pod are not on any service and so have no reverse DNS resolution.

Can you please add backups pod to service so they can be identified as `endpoints` and have reverse DNS resolution?
If not can you at least add a fixed label to those pods so the service can be declared outside of longhorn?

**Comment by cclhsu** [comment]
Thanks for suggestion!  we do plan to add "mananged-by: longhorn" for these pods in future release.

**Comment by PhanLe1010** [comment]
@n0rad 
Just to confirm, https://github.com/longhorn/longhorn/issues/2525#issuecomment-827228651 is what you are looking for right?

**Comment by n0rad** [comment]
This look like an annotation and not like a label, but if it's a label, this should be enough to allow external service creation out of it.

**Comment by jenting** [comment]
If I remember correctly, the backup happens in longhorn-manager Pod.
We did have an enhancement on add annotation to longhorn-manager Pod thru. longhorn-manager DaemonSet.
From your use case, we need to add an enhancement on add labels to longhorn-manager Pod thru. longhorn-manager DaemonSet. Is this meet your requirement @n0rad?

**Comment by joshimoo** [comment]
@n0rad can you see if creation of a service against the label `longhorn.io/component=instance-manager` works for you?
This will match all instance-manager pods for replicas + engine, since replicas/engines are just processes inside of these pods all of the instances/replicas would be covered. 

The recurring jobs just trigger api calls against the longhorn-backend, so as long as the backend + replica/engines have access to the nfs server that should be fine.

**Comment by n0rad** [comment]
Hum ok, I was not aware that jobs was not those accessing the NFS.

it's working.

By adding a service on `longhorn.io/component`, `replica` and `engines` are enlist.

Managers still need to be able to access the NFS to list available backups so `longhorn-backend` service also have to be allowed on nfs config.
