### ISSUE TITLE
[EPIC] techdebt, refactoring, improvements, design changes

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2526]
This epic is intended to collect tech debt, refactoring, improvements as well as design changes.
That are not necessarily user focused.

Items that are good candidates for this epic, are: 
- refactorings that help simplify the code (clean up)
- design changes that help make the code/software more robust (resilience/reliability)
- tech debt that when addressed makes it easier for the developers to reason about the code as well as extend it (reduction of risk, speed of development)

**Comment by innobead** [comment]
Let's just use `kind/refactoring` or `kind/tech-debt` to track all refactoring issues.
