### ISSUE TITLE
[BUG] degraded RWX performance on RHEL 7.9

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2528]
**Describe the bug**
Customer noticed degraded RWX performance on the new native integration.
There are some differences between the 2 implementations.

provisioner | native
------------ | -------------
hard mount | soft mount
timeo 600 | timeo 7
TCP/UDP support | TCP only
min nfs version 3 | min nfs version 4.1

**Environment:**
- Longhorn version: 1.1.0
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
- Number of management node in the cluster: 3
- Number of worker node in the cluster: 3
- Node config
- OS type and version: RHEL 7.9
- CPU per node: 8
- Memory per node: 16G
- Disk type(e.g. SSD/NVMe): VMware vmdk (netapp datastore)
- Network bandwidth between the nodes: 40000 Mb, Full Duplex
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare/KVM
- Number of Longhorn volumes in the cluster: 9

**Additional context**
support issue: 15790
The customer cluster, consists of 3 nodes that share worker/master responsibility
After looking into the cluster, I am guessing that the io is running into the timeo which is a bad sign in itself since it really shouldn't take 700ms round trip, since we didn't see any final failures instead mostly 2/3 timeout messages in dmesg.
It seems that the io makes it before the final timeout, so with 3 retrans that would mean a single io has a max runtime of 0.7 +1.4 + 2.1

For the full HA NFS solution #2394 we would want to switch back to hard mode anyway, at which point we can also consider enabling UDP support as well.

**Comment by joshimoo** [comment]
Making the NFS mount options user configurable can be considered after we implemented the HA solution. Since there will be some changes as part of that.

**Comment by meldafrawi** [comment]
RWX integration tests passed
