### ISSUE TITLE
[BUG] Upgrade from 1.1.0 to 1.1.1 fails

### ISSUE THREAD

**Issue by pschmitt** [longhorn/longhorn#2532]
**Describe the bug**
I tried upgrading to 1.1.1 from 1.1.0 using the helm chart. The upgrade never completes and the manager does not come online.

Here's what I ended up with before reverting to 1.1.0:

```
$ kubectl get pod -n longhorn-system | grep -vE "Completed|Running"
NAME                                                              READY   STATUS             RESTARTS   AGE
longhorn-driver-deployer-599f8dd6b9-48hfj                         0/1     Init:0/1           0          88s
longhorn-manager-l9p5r                                            0/1     CrashLoopBackOff   3          75s
longhorn-manager-q52z7                                            0/1     CrashLoopBackOff   3          79s
longhorn-manager-wbj9t                                            0/1     CrashLoopBackOff   3          83s
```

**To Reproduce**
1. Install 1.1.0 using the helm chart
2. Upgrade to 1.1.1: `cd longhorn.git; git checkout v1.1.1; helm -n longhorn-system upgrade longhorn chart/`

**Expected behavior**
A successful update and an up to date manager.

**Log**

In the manager logs I have the following:

```
Incorrect Usage: flag provided but not defined: -backing-image-manager-image

NAME:
longhorn-manager daemon -

USAGE:
longhorn-manager daemon [command options] [arguments...]

OPTIONS:
--engine-image value            Specify Longhorn engine image
--instance-manager-image value  Specify Longhorn instance manager image
--share-manager-image value     Specify Longhorn share manager image
--manager-image value           Specify Longhorn manager image
--service-account value         Specify service account for manager
--kube-config value             Specify path to kube config (optional)

time="2021-04-23T13:12:49Z" level=fatal msg="Critical error: flag provided but not defined: -backing-image-manager-image"
```

**Environment:**
 - Longhorn version: 1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s 1.20.6
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Fedora 34
   - CPU per node: 4
   - Memory per node: 32GB
   - Disk type(e.g. SSD/NVMe): SATA SSD (dedicated)
   - Network bandwidth between the nodes: 1G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 3

**Additional context**

**Comment by jenting** [comment]
1. Where is the git repo source? the github.com/longhorn/charts.git?
2. Did the git checkout really checkout the remote v1.1.1 tag?

**Comment by pschmitt** [comment]
> 1. Where is the git repo source? the github.com/longhorn/charts.git?

No, it's actually the repo here. ie github.com/longhorn/longhorn
Should I be using longhorn/charts instead?

> 2. Did the git checkout really checkout the remote v1.1.1 tag?

Yes:
 
```shell
git -C longhorn.git rev-parse HEAD
000a124d0feb2a8616b2fe59266e3cc0a9e0b042
```

000a124d0feb2a8616b2fe59266e3cc0a9e0b042

**Comment by jenting** [comment]
Could you please check the longhorn-manager Pod container image tag points to `v1.1.1`?

**Comment by pschmitt** [comment]
Sure. It clearly isn't using the right tag:

```shell
$ kubectl get pod longhorn-manager-dl4s5 -o yaml |grep v1.1                                                                                                              app.kubernetes.io/version: v1.1.1                       - longhornio/longhorn-engine:v1.1.0                     - longhornio/longhorn-manager:v1.1.0                    image: longhornio/longhorn-manager:v1.1.0               image: docker.io/longhornio/longhorn-manager:v1.1.0
```

**Comment by innobead** [comment]
> Sure. It clearly isn't using the right tag:
> 
> ```shell
> $ kubectl get pod longhorn-manager-dl4s5 -o yaml |grep v1.1        
>                                                                                                       app.kubernetes.io/version: v1.1.1                       - longhornio/longhorn-engine:v1.1.0                     - longhornio/longhorn-manager:v1.1.0                    image: longhornio/longhorn-manager:v1.1.0               image: docker.io/longhornio/longhorn-manager:v1.1.0
> ```

Your chart info and template seem correct, but it looks like your values incorrect. Could you dump your values info here? Also, you can double check if a wrong values.yaml got loaded (ref: https://helm.sh/docs/chart_template_guide/values_files/).

```console
helm get values longhorn -n longhorn-system -a
```

**Comment by pschmitt** [comment]
Arf crap. I had v1.1.0 set in my values.yaml. Sorry for that guys. It was 100% user-error. My bad.
Nothing is wrong with the upgrade procedure.
Sorry for wasting your time.
