### ISSUE TITLE
[BUG] Changing the replica count in Longhorn CSI Driver Settings does not update the deployments

### ISSUE THREAD

**Issue by Blackclaws** [longhorn/longhorn#2539]
**Describe the bug**
When changing the csi driver settings replica count in the longhorn catalog application in rancher the longhorn-driver-deployer does not update the replica count on the deployments.

**To Reproduce**
1. In Rancher install longhorn
2. After successful install, update the settings for the installed apps changing the csi replica counts
3. See the upgrade succeed but replica counts not update
4. longhorn-driver-deployer log shows:
```
time="2021-04-26T08:58:43Z" level=debug msg="Detected deployment csi-snapshotter CSI version v1.1.0 Kubernetes version v1.20.5 has already been deployed" 
time="2021-04-26T08:58:43Z" level=debug msg="Detected daemon set longhorn-csi-plugin CSI version v1.1.0 Kubernetes version v1.20.5 has already been deployed" 
```
etc.

**Expected behavior**
The replica count is updated on the deployments.

**Additional context**
This might be an issue not directly related to longhorn but to the rancher catalog app, I'm not sure if this is managed by this.

**Comment by shuo-wu** [comment]
Do you mean modifying the default settings during the Longhorn upgrade? Any default settings won't be applied during the upgrade. They work for the installation stage only.
