### ISSUE TITLE
[QUESTION] Configure retain for backup/snapshot.

### ISSUE THREAD

**Issue by LuizBuffa25** [longhorn/longhorn#2540]
**Question**

I have 2 volumes: 
longhorn-vol-mongo
longhorn-vol-mysql

I need to backup these two volumes every day at 00:00 (using S3);

Question: What is the correct configuration for recurring jobs, current I am using:
![image](https://user-images.githubusercontent.com/78387849/116153828-5087b480-a6be-11eb-8068-7cdeecdb7c7f.png)

*Each volume has this configuration (ignore Schedule time).

Is that correct? Do I need to have a specific snapshot in order to restore a specific backup?

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version: 1.20.5

**Additional context**

**Comment by c3y1huang** [comment]
We don't need to have snapshots to restore the backup. [Here](https://github.com/longhorn/longhorn/issues/1618) are some explanations of the difference between snapshot and backup.

**Comment by LuizBuffa25** [comment]
Thanks for answering.
So if I use s3 to store my backup there is no need to have retain < 1 for my snapshot? 
Is it still allowed to have a "retain" of a maximum of 50? 
This number is for each volume or I can have N volumes with 50 retains each storing data in the same s3 bucket for example?

thanks!

**Comment by c3y1huang** [comment]
> Thanks for answering.
> So if I use s3 to store my backup there is no need to have retain < 1 for my snapshot?

Restoring a backup will create a new volume. Longhorn does not rely on the snapshot of the original volume for backup restore. You can set the to retain snapshot to any number, this does not affect the backup and its restore. And when a backup is restored, the new volume will not contain the original volume snapshots.

> Is it still allowed to have a "retain" of a maximum of 50?

Not sure if I understand the question, but I will try to answer. Yes, you can set different numbers for recurring snapshots and recurring backups.

> This number is for each volume or I can have N volumes with 50 retains each storing data in the same s3 bucket for example?

If using the UI, the recurring job is created per volume. You can also [Set up Recurring Jobs using a StorageClass](https://longhorn.io/docs/1.1.1/snapshots-and-backups/scheduling-backups-and-snapshots/#set-up-recurring-jobs-using-a-storageclass)
```
Any future volumes created using this StorageClass will have those recurring jobs automatically set up.
```

> thanks!

**Comment by LuizBuffa25** [comment]
Thanks again, you may close this issue.
