### ISSUE TITLE
[QUESTION] All Workloads with volumes crashed.

### ISSUE THREAD

**Issue by timmy59100** [longhorn/longhorn#2541]
**Question**
This night at about 00:10 UTC all workloads with a longhorn volume crashed. It would be great if you could look at the support bundle what's the reason for that.

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version: 1.20.4
 - Node config
   - OS type and version: CentOS Linux release 7.4.1708
   - CPU per node: 8
   - Memory per node: 16GB
   - Disk type: SSD
   - Network bandwidth and latency between the nodes: 10Gi
 - Underlying Infrastructure (Xen):

I will send the support bundle per email.

**Comment by shuo-wu** [comment]
If a volume is crashed unexpectedly and the related workload is deployments or daemonsets, Longhorn will automatically restart all workloads so that the volume can be reattached and remounted. Typically volume crash is caused by the related engine instance manager pod crash or all replicas crashing simultaneously. Besides, for RWX volumes, the related share manager pod crash will lead to the same issue.

Can you check if the volume becomes Faulted or the related share manager pod is crashed?

**Comment by timmy59100** [comment]
@shuo-wu One instance-manager was created/recreated at the time of the incident.

**Comment by shuo-wu** [comment]
I think this manager is responsible for launching the volume engine. Once the pod is crashed, the volume won't work. To recover the volume, the related workload may be killed if the setting is true:
https://longhorn.io/docs/1.1.1/references/settings/#automatically-delete-workload-pod-when-the-volume-is-detached-unexpectedly

**Comment by timmy59100** [comment]
How do I know why the manager crashed?

**Comment by shuo-wu** [comment]
Detecting why a pod gets crashed is out of Longhorn's capability. Do you enable some kinds of monitoring tools in your cluster? Typically a pod crash can be caused by resource (CPU) exhaust, or some other apps/users may delete the pod by mistake.

**Comment by PhanLe1010** [comment]
Looking into the support bundle you sent, I see that instance manager pods are crashed, share manager pods are crashed, volumes are crashed, `remountRequested` is set for all volumes. The settings `automatically-delete-workload-pod-when-the-volume-is-detached-unexpectedly` is enabled so Longhorn automatically restarted the workload. 
Eventually, all volumes became healthy. Can you confirm that your workloads are back to running state?

For the reason why the manager pods crashed? It is likely as @shuo-wu mentioned your cluster doesn't have enough CPU resources. I see that you are having 25 volumes with many recurring jobs and share manager pods. The cluster is a 2 node cluster.  

Ref https://dwdraju.medium.com/a-pod-restarts-so-whats-going-on-fa12bb8a57ea

**Comment by timmy59100** [comment]
increased cpu and nodes: stable atm.
