### ISSUE TITLE
[QUESTION] Update replicaCount on already attached volumes without UI

### ISSUE THREAD

**Issue by aalcaraz97** [longhorn/longhorn#2542]
**Question**
Is there any possibility to increase/decrease the number or replicas on an already attached Longhorn volume without using the Longhorn UI?

I have a single-node Kubernetes cluster installed using K3S and etcd (allowing to have a cluster with HA in the control-plane).

After deploying the cluster, I install Longhorn using the Helm Chart (currently using v1.1.0, but I'm planning to move to v1.1.1 soon). I have configured the Longhorn deployment with the following fields in the values.yaml file (as I'm currently working on a single-node cluster, I set all the "replicaCount" values to 1):
```yaml
persistence:
  defaultClassReplicaCount: 1

csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

defaultSettings:
  replicaSoftAntiAffinity: true
  defaultReplicaCount: 1
  replicaZoneSoftAntiAffinity: true
```
When I want to add a new control-plane node to the cluster, I want to automatically increase the number of replicaCount for all the previous values. I was trying to use the following "helm upgrade" command to do that (after installing K3S in the new control-plane node):
```bash
# Get current Longhorn replicas
LONGHORN_CURRENT_REPLICAS=$(kubectl get configmap --namespace longhorn-system longhorn-default-setting \
	-o jsonpath='{.data.default-setting\.yaml}' | grep "default-replica-count" | awk '{print $2}')
# Update the current number of replicas on the Longhorn Helm Chart
LONGHORN_NEW_REPLICAS=$((LONGHORN_CURRENT_REPLICAS + 1))
# Upgrade the Longhorn Helm Chart
helm upgrade longhorn --namespace longhorn-system <path-to-longhorn-helm-chart> \
	--set persistence.defaultClassReplicaCount="$LONGHORN_NEW_REPLICAS" \
	--set csi.attacherReplicaCount="$LONGHORN_NEW_REPLICAS" \
	--set csi.provisionerReplicaCount="$LONGHORN_NEW_REPLICAS" \
	--set csi.resizerReplicaCount="$LONGHORN_NEW_REPLICAS" \
	--set csi.snapshotterReplicaCount="$LONGHORN_NEW_REPLICAS" \
	--set defaultSettings.defaultReplicaCount="$LONGHORN_NEW_REPLICAS"
```
After executing the "helm upgrade" command, the changes on the configuration are successfully applied (the Longhorn StorageClass, and the configmaps with the default settings and the storageclass config are updated with the new replicaCount), but the number of CSI pods in the cluster is still one (excepting the longhorn-csi-plugin pod, which belongs to a DaemonSet and it's automatically created when adding the new node), and the number of Longhorn replicas per Longhorn volume is still one.

I was going to try to restart the Longhorn Kubernetes objects that manage the replicas and the CSI pods to see if that results in the new replicas being created, but I'm not sure if it's the best solution.

Is there any way to increase/decrease the number of replicas for a Longhorn volume without the Longhorn UI?

**Environment:**
 - Longhorn version: v1.1.0
 - Kubernetes version: v1.20.4
 - Node config
   - OS type and version: CentOS Linux release 7.9.2009 (Core)
   - CPU per node: 4 vCPU
   - Memory per node: 8 GB
   - Disk type: Hard Disk
   - Network bandwidth and latency between the nodes: -
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare vSphere

**Additional context**
I actually have the Longhorn UI disabled (not deployed in the cluster as part of the Helm Chart), so I'm looking for a solution without using the Longhorn UI (if it's possible).

**Comment by aalcaraz97** [comment]
I also discovered that the "default-replica-count" Longhorn Settings object **is not updated** after executing the "helm upgrade" command:
```bash
kubectl get settings -n longhorn-system default-replica-count
NAME                    VALUE   AGE
default-replica-count   1       18h
```
But all the configmap data is being updated with the new value:
```bash
kubectl get configmap --namespace longhorn-system longhorn-default-setting -o jsonpath='{.data.default-setting\.yaml}'
[...]
default-replica-count: 2
```
```bash
kubectl get configmap --namespace longhorn-system longhorn-storageclass -o jsonpath='{.data.storageclass\.yaml}'
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
[...]
parameters:
  numberOfReplicas: "2"
```
And the spec of the longhorn-driver-deployer pod is also updated:
```
kubectl describe pod --namespace longhorn-system longhorn-driver-deployer-655f48bbf7-nxkvb
[...]
Containers:
  longhorn-driver-deployer:
    [...]
    Environment:
      POD_NAMESPACE:                    longhorn-system (v1:metadata.namespace)
      NODE_NAME:                         (v1:spec.nodeName)
      SERVICE_ACCOUNT:                   (v1:spec.serviceAccountName)
      CSI_ATTACHER_IMAGE:               longhornio/csi-attacher:v2.2.1-lh1
      CSI_PROVISIONER_IMAGE:            longhornio/csi-provisioner:v1.6.0-lh1
      CSI_NODE_DRIVER_REGISTRAR_IMAGE:  longhornio/csi-node-driver-registrar:v1.2.0-lh1
      CSI_RESIZER_IMAGE:                longhornio/csi-resizer:v0.5.1-lh1
      CSI_SNAPSHOTTER_IMAGE:            longhornio/csi-snapshotter:v2.1.1-lh1
      CSI_ATTACHER_REPLICA_COUNT:       2
      CSI_PROVISIONER_REPLICA_COUNT:    2
      CSI_RESIZER_REPLICA_COUNT:        2
      CSI_SNAPSHOTTER_REPLICA_COUNT:    2
```

**Comment by PhanLe1010** [comment]
There are multiple questions here.
1. Regarding to
   > I also discovered that the "default-replica-count" Longhorn Settings object is not updated after executing the "helm upgrade" command

   The Longhorn settings cannot be updated by changing `defaultSettings` during Helm upgrades. `defaultSettings` is only used to create Longhorn settings in the initial installation. If you want to change Longhorn settings after the initial installation, you can change the setting in UI or `kubectl edit settings <SETTING-NAME> -n longhorn-system`
   
1. Regarding to
   > Is there any possibility to increase/decrease the number or replicas on an already attached Longhorn volume without using the Longhorn UI?

   You can run `kubectl edit volumes <VOLUME-NAME> -n longhorn-system` and change the `numberOfReplicas:`


**WARNING:** only use `kubectl ` when you know what you are doing since it will bypass Longhorn back-end validation. It is dangerous. Therefore, we recommend using Longhorn UI when possible. In the future, we are having a plan to make a Longhorn CLI https://github.com/longhorn/longhorn/issues/613 so that users have another option to safely control Longhorn besides Longhorn UI

**Comment by aalcaraz97** [comment]
Thanks @PhanLe1010 for the answer!

I tried the approach that you pointed out in my cluster. I ended up using "kubectl patch" commands instead of "kubectl edit", as I wanted to automate those steps in some shell scripts:

```bash
# Get all the Longhorn volumes in the cluster
mapfile -t LONGHORN_VOLUME_NAMES < <(kubectl get volumes --namespace longhorn-system -o name | sed 's@volume.longhorn.io/@@g')

# Iterate over all the Longhorn volumes, and update their numberOfReplicas field with the new replica count
for vol in "${LONGHORN_VOLUME_NAMES[@]}"; do
  kubectl patch --namespace longhorn-system volumes/"$vol" --type=merge \
    -p '"spec" : { "numberOfReplicas": '"$LONGHORN_NEW_REPLICAS"'}'
done
```

This was the number of replicas in the cluster **before** applying the "patch" command:
```bash
kubectl get replicas --namespace longhorn-system | tail -n +2 | wc -l
5
```
This is the number of replicas in the cluster **after** applying the "patch" command:
```bash
kubectl get replicas --namespace longhorn-system | tail -n +2 | wc -l
10
```
New Longhorn replicas are successfully replicated when adding a second node.
Regarding to:

> In the future, we are having a plan to make a Longhorn CLI #613 so that users have another option to safely control Longhorn besides Longhorn UI

That sounds very promising! Looking forward to hear more from that CLI, it would make the Longhorn deployment management much easier for me.

**Comment by innobead** [comment]
Closing, because the answer works and this will be tackled by #613 .
