### ISSUE TITLE
[BUG] Failed to list backups after upgrade from v1.1.0 to v1.1.1

### ISSUE THREAD

**Issue by LuizBuffa25** [longhorn/longhorn#2543]
**Describe the bug**
When listing backups after upgrade to 1.1.1: 

error listing backups for volume 'longhorn-vol-pv-mongo': error listing backups: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.1/longhorn [backup ls --volume longhorn-vol-pv-mongo s3://<my bucket name>@< my region >/], output context deadline exceeded , stderr, time="2021-04-27T11:37:05Z" level=error msg="context deadline exceeded" , error exit status 1

I test the same command on the terminal and got the same error:
context deadline exceeded" , error exit status 1

When I try the same command but using old version 1.1.0 ( /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn ) works fine.

* I have 2 volumes:
One with 10Gi total size, I can list backups for that.  
Another one with 150Gi that I have the problem mentioned in this issue.

**To Reproduce**
1. Upgrade from v1.1.0 to v1.1.1
2. List backups for volumes with 150Gi+ size
3. See error

**Expected behavior**
Should list backups.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.1.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

**Additional context**

**Comment by innobead** [comment]
cc @jenting

**Comment by jenting** [comment]
@LuizBuffa25 Thanks for your reporting.
1. Which S3 provider you're using? AWS _or_ GCP _or_ others?
2. Could you please check inside the 150Gi+ volume's folder in the S3 bucket, are there any other folders that are not related to these volumes?

**Comment by LuizBuffa25** [comment]
@jenting Thanks for answering.
1) I will confirm but I think it is AWS;
2) There is only volumes related folder inside it;

I think is something related to timeout:
- Using v1.1.0: $ /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn 
   takes between 60-90 seconds to command return all my available backups;

- Using v1.1.1: $ /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn 
  After 30 seconds I receive the errors message: 
  ERRO[0030] context deadline exceeded

**Comment by jenting** [comment]
Thanks for the information, I think the problem comes with we assign a [default 30 seconds](https://github.com/longhorn/backupstore/blob/eb790e3/list.go#L120) to the job on the query each S3 folder.

At v1.1.0, LH configures a default timeout to 1 min to list all available backups.
At v1.1.1, LH configures a default timeout to 1 min to list all available backups _plus_ 30 secs default timeout when listing each S3 folder.

From the information you provided:
- At v1.1.0: there should be a chance that lists of available backups would fail if the time takes over 60 seconds, could you please verify it?
- The query latency from your LH cluster to your AWS S3 is a bit slow, are you able to check the ping latency?

We'll extend the default query job timeout value.

**Comment by LuizBuffa25** [comment]
> Thanks for the information, I think the problem comes with we assign a [default 30 seconds](https://github.com/longhorn/backupstore/blob/eb790e3/list.go#L120) to the job on the query each S3 folder.
> 
> At v1.1.0, LH configures a default timeout to 1 min to list all available backups.
> At v1.1.1, LH configures a default timeout to 1 min to list all available backups _plus_ 30 secs default timeout when listing/reading each S3 folder.
> 
> From the information you provided:
> 
> * At v1.1.0: there should be a chance that lists of available backups would fail _sometimes_ if the time takes over 60 seconds by GUI list backups, could you please verify that?
> * The query latency from your LH cluster to your AWS S3 is a bit slow, are you able to check the latency? Ref to [#1955 (comment)](https://github.com/longhorn/longhorn/issues/1955#issuecomment-770533993)
> 
> We'll extend the default query job timeout value, probably set to 1 min.

1) I barely use GUI, but I made a test and it takes the same time to list my backups (between 60s-90s).
2) I have 2 clusters in the same region:

real	0m0.852s
user	0m0.422s
sys	0m0.115s

real	0m0.839s
user	0m0.421s
sys	0m0.076s

There is a way to make a workaround until the new release? I Want to update my version to fix some other problems, but I can't do it with the problem listing backups.

Thanks!

**Comment by jenting** [comment]
What's the 150Gi volume backup retention?

The current workaround I could think of is to delete some of the older backups in the S3 bucket and then decrease the backup retention.

**Comment by LuizBuffa25** [comment]
30 retantions, but it is mandatory for my client.

**Comment by jenting** [comment]
Could you please check in the S3 bucket, how man *.cfg under `backups` folder for the 150Gi volume? (the path is like `backupbucket/backupstore/volumes/XX/YY/pvc-*******/backups)
I assume is 30.

**Comment by LuizBuffa25** [comment]
10GI: 9 *.cfg files
150Gi: 107 .cfg files (and a lot of them are duplicated because of some problem with the backup process that triggers a retry, I think this is an old issue).

**Comment by jenting** [comment]
Could you please removes the duplicated ones and makes the number of *.cfg equals to the 30 retentions? This is the current workaround I could think of.

**Comment by LuizBuffa25** [comment]
Ok, I  think the problem of multiple retries is fixed on v1.1.1.
After that, I will clean the duplicated .cfg and test it again, I will let you know when I made those tests.

Thanks!

**Comment by jenting** [comment]
@LuizBuffa25 Were you able to make list backups on 150Gi volume works after clean the duplicated .cfg?

**Comment by LuizBuffa25** [comment]
I will test it in the next 24 hours and give you feedback.

**Comment by LuizBuffa25** [comment]
@jenting I am testing it right now.
I download all 96 .cgf files, how do I know what files I need to delete? Also, I have 8 buckets with this problem (a lot of duplicated .cfg files), there is an easy way to remove these files?

Thanks!

**Comment by jenting** [comment]
I'd suggest keeping the latest 30.cfg files and remove the rest.
The .cfg is the metadata, the real data is under `blocks/` folder.

Sorry, no, the only workaround way is _manually_ to delete it for all the buckets.

**Comment by LuizBuffa25** [comment]
I made a test this weekend to check if duplicate .cfg files are fixed. I create a recurring job to perform one backup at 00:00 every day, today when I checked it, there are duplicated .cfg files (after upgrade to v1.1.1).

I will remove the duplicated .cfg to test the backup list, but even if I clean manually, at some point the error will appear because of the duplicated .cfg.
This problem was not supposed to be solved in the release v1.1.1?

![image](https://user-images.githubusercontent.com/78387849/117645247-c2e9a180-b160-11eb-8629-3fa405b1f47f.png)

Also, I checked my .cfg files and there is no one with an empty "CreatedTime"
An example of the last tree duplicated files:
"CreatedTime":"2021-05-10T00:07:01Z"
"CreatedTime":"2021-05-10T00:06:27Z"
"CreatedTime":"2021-05-10T00:06:25Z"

**Comment by jenting** [comment]
> I will remove the duplicated .cfg to test the backup list, but even if I clean manually, at some point the error will appear because of the duplicated .cfg.
> This problem was not supposed to be solved in the release v1.1.1?

It is similar to #2278

**Comment by LuizBuffa25** [comment]
I deleted a lot of duplicated .cfg files;
Now I have 22 files and I am able to list the available backups.

* I tried to list with 50 .cfg files but it failed, as the maximum retention is 50 I think longhorn should support this scenario.
Maybe adding more time-out limits fix this problem.

I will need to wait to upgrade longhorn from v1.1.0 because of this problem and because of the issue mentioned above (#2278)?

Thanks.

**Comment by khushboo-rancher** [comment]
We have tested the scenarios listing more than 1000 backups https://github.com/longhorn/longhorn/issues/1904#issuecomment-781471341 in release v1.1.1.
I'll give this another try and add more test cases for this scenario.

**Comment by innobead** [comment]
@jenting the related fixes need to backport.

**Comment by jenting** [comment]
> @jenting the related fixes need to backport.

I could backport this.

However, I worried that since the longhorn/backstore does not have v1.2.x and v1.1.y branch.
If there is an enhancement in longhorn/backstore, and does not need to backport to v1.1.y branch.
Somehow, a bug fix needed in longhorn/backstore but the commit is after the enhancement, and the bug needs to backport to v1.1.y branch.
In current go.mod design, both the enhancement and bug fix will be included in v1.1.y branch.

**Comment by innobead** [comment]
> > @jenting the related fixes need to backport.
> 
> I could backport this.
> 
> However, I worried that since the longhorn/backstore does not have v1.2.x and v1.1.y branch.
> If there is an enhancement in longhorn/backstore, and does not need to backport to v1.1.y branch.
> Somehow, a bug fix needed in longhorn/backstore but the commit is after the enhancement, and the bug needs to backport to v1.1.y branch.
> In current go.mod design, both the enhancement and bug fix will be included in v1.1.y branch.

This is not a problem for now as we discussed, because we should regard `longhorn/backstore` as an internal 3rd-party library and make sure it's backward compatible.

**Comment by innobead** [comment]
Let's use #1761 as an enhancement item to track async backup operation implementation instead of using this bug directly because #1761 actually tackles more areas than this issue.

**Comment by innobead** [comment]
Closing as duplicated and fixed in https://github.com/longhorn/longhorn/issues/1761.
