### ISSUE TITLE
[QUESTION] - New longhorn release is not available in rancher 2.5.5

### ISSUE THREAD

**Issue by thiagosantosleite** [longhorn/longhorn#2546]
**Question**
New longhorn release 1.1.1 is not available in rancher 2.5.5.
When it should be available?  I already run a refresh in catalogs, but it does not worked.
- https://git.rancher.io/partner-charts
- https://git.rancher.io/charts

**Environment:**
 - Longhorn version:
1.1.0

 - Kubernetes version:
1.19.6

 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - aws / rke

Rancher | v2.5.5
User Interface | v2.5.4
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49

**Comment by cclhsu** [comment]
Longhorn Chart v1.1.1 for Rancher is undergoing the final stage of QA and review.  I will be available next couple day.

**Comment by jenting** [comment]
Rancher v2.5.8 includes Longhorn chart v1.1.1.
Close it.
