### ISSUE TITLE
[FEATURE] Resize of attached volumes

### ISSUE THREAD

**Issue by jabbermouth** [longhorn/longhorn#2547]
**Is your feature request related to a problem? Please describe.**
Increasing the size of a persistent storage volume is painful due to needing to detach the volume first.

**Describe the solution you'd like**
Update the PVC that created a volume and the volume will resize to match the new PVC without needing to detach the volume first.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by c3y1huang** [comment]
@jabbermouth thanks you for reporting. This looks like a duplicate of https://github.com/longhorn/longhorn/issues/1674.

**Comment by jabbermouth** [comment]
@c3y1huang I agree.  I searched for resizing rather than expanding, hence missed it.  I'll close this issue.
