### ISSUE TITLE
[QUESTION] How to fix this (get volumesnapshotclasses.snapshot.storage.k8s.io) problem?

### ISSUE THREAD

**Issue by LuizBuffa25** [longhorn/longhorn#2551]
**Question**
I am facing the same error message mentioned here ( https://github.com/longhorn/longhorn/issues/2459)

How can I fix it? How do I install snapshot crds?

Message on my journalctl:
 1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1beta1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)

Thanks!

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version: 1.20.5
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**

**Comment by jenting** [comment]
Could you please check the CRDs have created and have create a VolumeSnapshotClass CR?

https://longhorn.io/docs/1.1.1/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/

**Comment by PhanLe1010** [comment]
One more note, if you don't want to use Kubernetes CSI snapshot feature, you can ignore the errors and don't have to install snapshot crds.

**Comment by LuizBuffa25** [comment]
Thanks for answering!

I have a lot of messages about that in my journal, ignoring these messages is not possible, maybe. After install crds the message was gone.

Do you know any tricks to don't print it in my journal?

**Comment by PhanLe1010** [comment]
I see the problem. In this case, we can either install the crds or just delete the `csi-snapshotter` deployment inside longhorn-system. I think the former is better since you might want to use csi snapshot in the future.

**Comment by jenting** [comment]
> I see the problem. In this case, we can either install the crds or just delete the `csi-snapshotter` deployment inside longhorn-system. I think the former is better since you might want to use csi snapshot in the future.

Let's wait user reply first to see install CRDs would decrease the messages on the journal log.

After that, we could decide which way to proceed:
1. Add a knowledge base to install VolumeSnapshot* CRDs by users?
2. Deploy `csi-snapshotter` deployment once the VolumeSnapshot* CRDs detected
3. Install VolumeSnapshot* CRDs at the beginning.

**Comment by LuizBuffa25** [comment]
Install CRDs decreased the message on my journal.

2- Deploy csi-snapshotter deployment once the VolumeSnapshot* CRDs detected
That sounds good!

Thanks!

**Comment by jenting** [comment]
The error log is not flooding, right?

After discuss internally, we preferred not to fix it but use documentation to explain it.

**Comment by XtremeOwnageDotCom** [comment]
WELL... since this one is still here....

![image](https://user-images.githubusercontent.com/5262735/214993645-4436cdef-8529-4d9e-beec-5363f0249974.png)

```
backups           0s          Normal    SnapshotCreated          volumesnapshot/kubestr-snapshot-20230127015007                 Snapshot backups/kubestr-snapshot-20230127015007 was successfully created by the CSI driver.
backups           0s          Normal    SnapshotReady            volumesnapshot/kubestr-snapshot-20230127015007                 Snapshot backups/kubestr-snapshot-20230127015007 is ready to use.
backups           0s          Normal    SnapshotCreated          volumesnapshot/kubestr-clone-kubestr-snapshot-20230127015007   Snapshot backups/kubestr-clone-kubestr-snapshot-20230127015007 was successfully created by the CSI driver.
backups           0s          Normal    SnapshotReady            volumesnapshot/kubestr-clone-kubestr-snapshot-20230127015007   Snapshot backups/kubestr-clone-kubestr-snapshot-20230127015007 is ready to use.
backups           0s          Warning   FailedScheduling         pod/kubestr-csi-cloned-podrm4ss                                0/4 nodes are available: 4 persistentvolumeclaim "kubestr-csi-cloned-pvcpthq5" not found. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
backups           0s          Normal    ExternalProvisioning     persistentvolumeclaim/kubestr-csi-cloned-pvcpthq5              waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
backups           0s          Normal    ExternalProvisioning     persistentvolumeclaim/kubestr-csi-cloned-pvcpthq5              waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
backups           0s          Normal    Provisioning             persistentvolumeclaim/kubestr-csi-cloned-pvcpthq5              External provisioner is provisioning volume for claim "backups/kubestr-csi-cloned-pvcpthq5"
backups           0s          Warning   ProvisioningFailed       persistentvolumeclaim/kubestr-csi-cloned-pvcpthq5              failed to provision volume with StorageClass "longhorn": error getting handle for DataSource Type VolumeSnapshot by Name kubestr-snapshot-20230127015007: error getting snapshot kubestr-snapshot-20230127015007 from api server: the server could not find the requested resource (get volumesnapshots.snapshot.storage.k8s.io kubestr-snapshot-20230127015007)
backups           0s          Normal    Provisioning             persistentvolumeclaim/kubestr-csi-cloned-pvcpthq5              External provisioner is provisioning volume for claim "backups/kubestr-csi-cloned-pvcpthq5"
backups           0s          Warning   ProvisioningFailed       persistentvolumeclaim/kubestr-csi-cloned-pvcpthq5              failed to provision volume with StorageClass "longhorn": error getting handle for DataSource Type VolumeSnapshot by Name kubestr-snapshot-20230127015007: error getting snapshot kubestr-snapshot-20230127015007 from api server: the server could not find the requested resource (get volumesnapshots.snapshot.storage.k8s.io kubestr-snapshot-20230127015007)
backups           0s          Warning   FailedScheduling         pod/kubestr-csi-cloned-podrm4ss                                0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
backups           0s          Normal    Provisioning             persistentvolumeclaim/kubestr-csi-cloned-pvcpthq5              External provisioner is provisioning volume for claim "backups/kubestr-csi-cloned-pvcpthq5"
backups           0s          Warning   ProvisioningFailed       persistentvolumeclaim/kubestr-csi-cloned-pvcpthq5              failed to provision volume with StorageClass "longhorn": error getting handle for DataSource Type VolumeSnapshot by Name kubestr-snapshot-20230127015007: error getting snapshot kubestr-snapshot-20230127015007 from api server: the server could not find the requested resource (get volumesnapshots.snapshot.storage.k8s.io kubestr-snapshot-20230127015007)
backups           0s          Normal    Provisioning             persistentvolumeclaim/kubestr-csi-cloned-pvcpthq5              External provisioner is provisioning volume for claim "backups/kubestr-csi-cloned-pvcpthq5"
backups           0s          Warning   ProvisioningFailed       persistentvolumeclaim/kubestr-csi-cloned-pvcpthq5              failed to provision volume with StorageClass "longhorn": error getting handle for DataSource Type VolumeSnapshot by Name kubestr-snapshot-20230127015007: error getting snapshot kubestr-snapshot-20230127015007 from api server: the server could not find the requested resource (get volumesnapshots.snapshot.storage.k8s.io kubestr-snapshot-20230127015007)
backups           1s          Normal    ExternalProvisioning     persistentvolumeclaim/kubestr-csi-cloned-pvcpthq5              waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
backups           0s          Normal    Provisioning             persistentvolumeclaim/kubestr-csi-cloned-pvcpthq5              External provisioner is provisioning volume for claim "backups/kubestr-csi-cloned-pvcpthq5"
backups           0s          Warning   ProvisioningFailed       persistentvolumeclaim/kubestr-csi-cloned-pvcpthq5              failed to provision volume with StorageClass "longhorn": error getting handle for DataSource Type VolumeSnapshot by Name kubestr-snapshot-20230127015007: error getting snapshot kubestr-snapshot-20230127015007 from api server: the server could not find the requested resource (get volumesnapshots.snapshot.storage.k8s.io kubestr-snapshot-20230127015007)
```

```
root@kube01:~/Kubernetes/namespaces/longhorn# kubectl get volumesnapshot -n backups kubestr-snapshot-20230127015007
NAME                              READYTOUSE   SOURCEPVC                       SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS         SNAPSHOTCONTENT                                    CREATIONTIME   AGE
kubestr-snapshot-20230127015007   true         kubestr-csi-original-pvcw6wm7                           1Gi           longhorn-backup-vsc   snapcontent-a393caee-ca70-41eb-9bfc-8cd82e174539   71s            72s
```

**Comment by ChristianCiach** [comment]
I would still prefer Longhorn to handle these missing CRD more gracefully. The logs may not be "flooding", but it is still an annoying warning every few seconds.

Some (many?) Kubernetes distributions do not come with a bundled snapshot controller. Notably K3s has no intention to do so: https://github.com/k3s-io/k3s/pull/6459#issuecomment-1334178033 . Manually installing the controller is cumbersome and also useless if you don't intent to use the snapshotting functionality of Longhorn.

We are using https://github.com/longhorn/longhorn-manager/ to deploy Longhorn. Maybe the Longhorn-Manager could be made a bit smarter about this, for example by only deploying the CSI-snapshotter if the required CRDs are actually available?

**Comment by velvetzhero** [comment]
Well it depends what you call `not flooding` ...
It's about 150 msgs/h in our case

**Comment by Dunge** [comment]
I agree it's confusing. You install Longhorn via Helm and these errors comes every few minutes out of the box. Either you install everything (including the CRD), or you don't install the feature trying to use them, but don't install half of it.

**Comment by mrclrchtr** [comment]
I found this out today. It's kind of confusing. 

But do I understand correctly that I can just set `snapshotterReplicaCount` to 0 in the helm chart if I don't want to use snapshots?

**Comment by didlawowo** [comment]
there is still a issue here, could we disable the csi snapshottoer ?

**Comment by fmunteanu** [comment]
@derekbit what is the status on this feature? Is it planned to disable the snapshotter with a condition, into Helm chart?

**Comment by thedarkside** [comment]
@derekbit please reopen, as this is clearly an issue in the longhorn-manager. We have no way to opt out of installing the csi-snapshotter as the longhorn-manager deploys it as indicated by the label `longhorn.io/managed-by : longhorn-manager`

**Comment by derekbit** [comment]
> [@derekbit](https://github.com/derekbit) please reopen, as this is clearly an issue in the longhorn-manager. We have no way to opt out of installing the csi-snapshotter as the longhorn-manager deploys it as indicated by the label `longhorn.io/managed-by : longhorn-manager`

@thedarkside 
I would like to clarify the issue before reopening it. Don't you need CSI snapshot functionality?

**Comment by thedarkside** [comment]
> [@thedarkside](https://github.com/thedarkside) I would like to clarify the issue before reopening it. Don't you need CSI snapshot functionality?

My predecessors outlined it pretty well already but surely i can put it in my own words!

Iam using k3s which does not come with the mentioned CRDs and k3s wont be adding it. As my setup is pretty lightweight i also do not plan to add snapshotting. Iam fine with my backups created with velero.

Meanwhile my logs are flooded with warnings/errors which i want to get rid of.

As far as i can see, there is no way to do so. The longhorn-manager spins up the snapshotter without checking if the required crds are available at all on the cluster. 

The two solution paths were also mentioned already:

1. longhorn-manager could check for the requirements (crds) and deploy the snapshotter only in case they are present. It should also handle the case when someone installs those crds at some later point in time. 
2. deploy snappshotter in all cases (this is the current state) but silence those repeated errors. This can also be configurable maybe.
3. provide some configuration option in the helm chart for disabling snapshotter deployment as this is a decision the admin should be able to do.

If i could choose i would pick the first option as this seems the most robust one.
