### ISSUE TITLE
[BUG] pvc image are not deleted.

### ISSUE THREAD

**Issue by StefanSa** [longhorn/longhorn#2552]
**Describe the bug**
Backups were created via the Longhorn UI, which were later also deleted via the UI.
Now the images are no longer visible in the UI, but still exist on the host / node.
The question also arises why there is such a large delta between `Size: 106 Gi` and` Actual Size: 142 Gi`.
We have some such cases where the image is still available on the nodes and the delta between `Size \ Actaul Size` is quite large.

longhorn UI:
![Ohne Titel 9](https://user-images.githubusercontent.com/6105075/116719190-13336780-a9db-11eb-8840-8778c31ca429.png)

node local pvc:
```
k-node02:/mnt/san/longhorn/replicas/pvc-348647c0-47e3-4202-942d-38c6839cfdaa-83d00da9 # ls -lh
overall 142G
-rw------- 1 root root 4,0K 30. Apr 17:40 revision.counter
-rw-r--r-- 1 root root 200G 30. Apr 17:40 volume-head-004.img
-rw-r--r-- 1 root root  178 28. Apr 17:05 volume-head-004.img.meta
-rw-r--r-- 1 root root  196 30. Apr 17:34 volume.meta
-rw-r--r-- 1 root root 200G 28. Apr 17:45 volume-snap-377bc584-f8cc-452c-b368-53a8df615ede.img
-rw-r--r-- 1 root root  209 28. Apr 17:45 volume-snap-377bc584-f8cc-452c-b368-53a8df615ede.img.meta
-rw-r--r-- 1 root root 200G 27. Apr 13:35 volume-snap-fbfc33a1-b86a-49cb-87a4-bf67676bd723.img
-rw-r--r-- 1 root root  157 28. Apr 17:45 volume-snap-fbfc33a1-b86a-49cb-87a4-bf67676bd723.img.meta
```

inside pod df -h:
```
I have no name!@zabbix-postgresql-0:/$ df -h
Filesystem                                              Size  Used Avail Use% Mounted on
overlay                                                 2.2T  496G  1.7T  23% /
tmpfs                                                    64M     0   64M   0% /dev
tmpfs                                                    71G     0   71G   0% /sys/fs/cgroup
/dev/mapper/36782bcb022e89d0021f33f3e09cd528b-part4     2.2T  496G  1.7T  23% /etc/hosts
/dev/longhorn/pvc-348647c0-47e3-4202-942d-38c6839cfdaa  196G  106G   91G  54% /bitnami/postgresql
shm                                                      64M  392K   64M   1% /dev/shm
tmpfs                                                    71G   12K   71G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                    71G     0   71G   0% /proc/acpi
tmpfs                                                    71G     0   71G   0% /proc/scsi
tmpfs                                                    71G     0   71G   0% /sys/firmware
I have no name!@zabbix-postgresql-0:/$ 
```

**To Reproduce**
1. Create a backup, delete it and the image for it.

**Expected behavior**
If you create a backup and delete it including the images, these should also be deleted on the node / host. It is also important to clarify why the `actual size` differs `significantly` from the `size actually used`.

**Environment:**
 - Longhorn version: 1.1.0
 - Installation method: Rancher Catalog
 - Kubernetes distro: RKE 2.5.7
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure: Baremetal:
 - Number of Longhorn volumes in the cluster:

**Comment by jenting** [comment]
> Backups were created via the Longhorn UI, which were later also deleted via the UI.

I _guess the backups here mean the external backup? Delete external backup won't affect local volume snapshot.
I see your current volume did not have a snapshot, is this volume recreated from a backup _or_ a newly create volume from GUI _or_ kubectl?
![image](https://user-images.githubusercontent.com/49380831/116956897-fe9beb80-acc8-11eb-9c48-bbdf9dbc13c6.png)

> Now the images are no longer visible in the UI, but still exist on the host / node.

Has this node ever going down before? If yes, currently longhorn would be lost the information on the volume snapshot once the node ever going down. We have a backlog for this to scan all data under `/var/lib/longhorn/replicas/pvc-*` to cleanup the orphan replicas, it will be enhanced in the near future.

> The question also arises why there is such a large delta between Size: 106 Gi and Actual Size: 142 Gi.
> We have some such cases where the image is still available on the nodes and the delta between Size \ Actual Size is quite large.

Please refer to the [doc](https://longhorn.io/docs/1.1.1/concepts/#21-thin-provisioning-and-volume-size).

**Comment by StefanSa** [comment]
> I _guess the backups here mean the external backup? Delete external backup won't affect local volume snapshot.
> I see your current volume did not have a snapshot, is this volume recreated from a backup _or_ a newly create volume from GUI _or_ kubectl?
> ![image](https://user-images.githubusercontent.com/49380831/116956897-fe9beb80-acc8-11eb-9c48-bbdf9dbc13c6.png)

What do you mean by `external backup` ?, i ran it from this menu item `Create Backup`.
![Ohne Titel 9](https://user-images.githubusercontent.com/6105075/116972835-e96c9000-acbb-11eb-8751-38611021e7d0.png)


> Has this node ever going down before? If yes, currently longhorn would be lost the information on the volume snapshot once the node ever going down. We have a backlog for this to scan all data under `/var/lib/longhorn/replicas/pvc-*` to cleanup the orphan replicas, it will be enhanced in the near future.

No, the node was not down during this time.
We did the following:

1) Backup created with `Create Backup` to an NFS volume.
2) Then deleted the backup `and` the associated `snapshots`

Question about the `orphaned snapshots` that are not displayed in the UI, but `still physically exist` and `unnecessarily take up storage space`.
I am not really sure whether you can delete this manually if i look at the associated * .meta.

```
{"Size":8589934592,"Head":"volume-head-002.img","Dirty":true,"Rebuilding":false,"Error":"","Parent":"volume-snap-cfd30624-bac1-46ac-9a64-1b8e591034bf.img","SectorSize":512,"BackingFileName":""}
```

```
k-node02:/mnt/san/longhorn/replicas/pvc-9a916d99-2f4b-4d3b-b6b5-45c92202eee7-cacd01b5 # ls -lh
insgesamt 13G
-rw------- 1 root root 4,0K  4. Mai 09:47 revision.counter
-rw-r--r-- 1 root root 8,0G  4. Mai 09:47 volume-head-002.img
-rw-r--r-- 1 root root  178 28. Apr 16:51 volume-head-002.img.meta
-rw-r--r-- 1 root root  194 29. Apr 08:26 volume.meta
-rw-r--r-- 1 root root 8,0G 29. Apr 08:45 volume-snap-cfd30624-bac1-46ac-9a64-1b8e591034bf.img
-rw-r--r-- 1 root root  157 29. Apr 08:45 volume-snap-cfd30624-bac1-46ac-9a64-1b8e591034bf.img.meta
```

We see this problem of `orphaned snapshots` on `all nodes` where the backup and the snapshots generated for it were previously deleted.
The general question is, `how can you avoid something like that` and how can you `safely delete these orphaned snaphosts`?

**Comment by jenting** [comment]
> What do you mean by `external backup` ?, i ran it from this menu item `Create Backup`.
> ![Ohne Titel 9](https://user-images.githubusercontent.com/6105075/116972835-e96c9000-acbb-11eb-8751-38611021e7d0.png)

Create Backup is create a backup to S3/NFS which I called external backup (backup snapshots)

> Question about the `orphaned snapshots` that are not displayed in the UI, but `still physically exist` and `unnecessarily take up storage space`.

In Longhorn, the latest snapshot cannot be deleted. This is because whenever a snapshot is deleted, Longhorn will conflate its content with the next snapshot, so that the next and later snapshot retains the correct content.
But Longhorn cannot do that for the latest snapshot since there is no more recent snapshot to be conflated with the deleted snapshot. The next “snapshot” of the latest snapshot is the live volume (volume-head), which is being read/written by the user at the moment, so the conflation process cannot happen.

Ref to https://longhorn.io/docs/1.1.1/concepts/#243-deleting-snapshots

Also, Longhorn is a thin-provisioned storage system. The actual size is not 8.G for each snapshot image in your case.
You could run `du -sh /mnt/san/longhorn/replicas/pvc-9a916d99-2f4b-4d3b-b6b5-45c92202eee7-cacd01b5` to see the actual size.

**Comment by StefanSa** [comment]
@jenting 
OK, thanks for the detailed clarification.
i think that the ticket can now be closed.

thank you for your help.
