### ISSUE TITLE
[BUG] Volume head is always dirty after taking new snapshots

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2555]
After taking a new snapshot and the application doesn't write new data to volume, the volume head is supposed to be clean. However, the volume head always has some data after taking new snapshots. 

As a result, the recurring snapshot/backup job always taking a new snapshot/backup, and it overrides the important snapshots/backups. 

This problem occurs in Longhorn v1.1.1 but not in v1.1.0

**To Reproduce**
1. Install Longhorn v1.1.1
2. Create a pod using a Longhorn volume
3. Wait for the actual size of the volume to stop increasing.
4. Take a snapshot. See that the volume head has a weird 4kb of data.
5. Repeat step 4 a few times.

**Environment:**
 - Longhorn version: v1.1.1

**Comment by joshimoo** [comment]
Just wondering does your test pod have a liveness probe or anything else that does a read operation on the filesystem? Does this happen when the volume is just attached i.e. not mounted?

**Comment by PhanLe1010** [comment]
> Just wondering does your test pod have a liveness probe or anything else that does a read operation on the filesystem?

<details>
<summary>I think no. The yaml file for my workload pod</summary>
<br>
<pre>
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-xvgl2
  creationTimestamp: "2021-04-30T21:13:09Z"
  generation: 3
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-shell
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
          f:workload.user.cattle.io/workloadselector: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:annotations:
              .: {}
              f:cattle.io/timestamp: {}
            f:labels:
              .: {}
              f:workload.user.cattle.io/workloadselector: {}
          f:spec:
            f:containers:
              k:{"name":"shell"}:
                .: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:securityContext:
                  .: {}
                  f:allowPrivilegeEscalation: {}
                  f:capabilities: {}
                  f:privileged: {}
                  f:readOnlyRootFilesystem: {}
                  f:runAsNonRoot: {}
                f:stdin: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:tty: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/mnt/"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"pvc"}:
                .: {}
                f:name: {}
                f:persistentVolumeClaim:
                  .: {}
                  f:claimName: {}
    manager: rancher
    operation: Update
    time: "2021-04-30T21:13:09Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-05-03T17:03:48Z"
  name: shell
  namespace: default
  resourceVersion: "873303"
  uid: c134f983-84f4-44c3-bc10-46f454b7601d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-shell
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-04-30T21:13:08Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-shell
    spec:
      containers:
      - image: ubuntu:xenial
        imagePullPolicy: Always
        name: shell
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /mnt/
          name: pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-04-30T21:13:09Z"
    lastUpdateTime: "2021-04-30T21:13:47Z"
    message: ReplicaSet "shell-6df994f6b9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-05-03T17:03:48Z"
    lastUpdateTime: "2021-05-03T17:03:48Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
</pre>
</details>

> Does this happen when the volume is just attached i.e. not mounted?

I haven't tried attach only yet. I will do more investigation and report here.

**Comment by PhanLe1010** [comment]
It only happens when the volume is mounted. Possible the side effect of the `fsfreeze -u` command that we recently added https://github.com/longhorn/longhorn-engine/blob/3cc56fd7c02269718bbe276f78fe7257e46c6c1a/pkg/controller/control.go#L183. After taking snapshot, we unfreeze filesystem

**Comment by PhanLe1010** [comment]
The problem disappears after removing the `fsfreeze -f` and `fsfreeze -u` logic

**Comment by PhanLe1010** [comment]
After discussing in the team meeting, we decided not to fix this problem. We want to keep the `fsfreeze` logic because the filesystem's integrity is more important than the duplicated backups.

**Comment by innobead** [comment]
closing as per the discussion.
