### ISSUE TITLE
[TEST] Modify test 'test_recurring_job' to make sure recurring job doesn't take backup for a volume with no change.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2557]
**What's the test to develop? Please describe.**
Test will insure that if a volume is not modified and has no change, recurring job should not take backup.

**Describe the items of the test development (DoD, definition of done) you'd like.**
- Create a recurring backup job for a volume. (every 1 min)
-  Write into the volume.
- Recurring backup should take a backup in coming 1 min.
- Wait for another 1 min, and verify recurring job doesn't take the backup.

**Additional context**
https://github.com/longhorn/longhorn/issues/2555

**Comment by khushboo-rancher** [comment]
This is not valid as after fs_freeze implement, every snapshot is dirty and recurring backup will trigger the backups.

**Comment by innobead** [comment]
cc @chanow816
