### ISSUE TITLE
[BUG] Resizing a RWX volume leaves the volume in "unknown" state

### ISSUE THREAD

**Issue by aalcaraz97** [longhorn/longhorn#2558]
**Describe the bug**
I have a K3S cluster up (single-node cluster), where I want to deploy a Kubernetes DaemonSet configured with a Longhorn Persistent Volume with RWX (ReadWriteMany) AccessMode. 
When I deploy the DaemonSet + PVC, the new pod and the PVC (and the associated Longhorn volume) are deployed successfully.

However, when I want to increase the size of that PVC (whose original size is 5GB) to 6GB, I encounter some issues.
These are the steps I execute to perform the resizing of the PVC:
1. Scale down the DaemonSet to 0 replicas: all pods will be terminated, in order to perform the volume resize:
```bash
kubectl patch -n <namespace> ds/<daemonsetName> -p '{"spec": {"template": {"spec": {"nodeSelector": {"non-existing": "true"}}}}}'
```
2. When the daemonset pod associated with the PVC is terminated, patch the PVC object with the new size:
```bash
kubectl patch -n <namespace> pvc/<claimName> --type merge -p '"spec": { "resources": { "requests": { "storage": "6Gi" } } }'
```
3. When the PVC is successfully resized, scale up again the DaemonSet:
```bash
kubectl patch -n <namespace> ds/<daemonsetName> --type json -p='[{"op": "remove", "path": "/spec/template/spec/nodeSelector/non-existing"}]'
```

In this last step, the new created pod remains in ContainerCreating state:
```bash
kubectl describe pod -n <namespace> <daemonset-pod-name>
[...]
Events:
  Type     Reason              Age                  From                     Message
  ----     ------              ----                 ----                     -------
   Warning  FailedAttachVolume  2s (x19 over 22m)    attachdetach-controller  AttachVolume.Attach failed for volume "<volume-name>" : rpc error: code = Aborted desc = The volume <volume-name> is not ready for workloads
```

The resized volume is not ready for workloads. If I check the PVC logs for the volume, it is successfully resized to 6Gi:
```bash
kubectl describe pvc -n <namespace> <claimName>
[...]
StorageClass:  longhorn
Status:        Bound
[...]
Capacity:      6Gi
Access Modes:  RWX
[...]
Events:
  Type     Reason                  Age   From                                 Message
  ----     ------                  ----  ----                                 -------
  Normal   Resizing                25m   external-resizer driver.longhorn.io  External resizer is resizing volume <volume-name>
  Normal   VolumeResizeSuccessful  25m   external-resizer driver.longhorn.io  Resize volume succeeded
```

After checking the logs of the csi-resizer pod, the process of resizing seems successful too:
```bash
kubectl logs -n longhorn-system <csi-resizer-pod>
[...]
I0503 11:40:46.751080       1 controller.go:364] Resize volume succeeded for volume "<volume-name>", start to update PV's capacity
I0503 11:40:46.793334       1 controller.go:370] Update capacity of PV "<volume-name>" to 6Gi succeeded
I0503 11:40:46.806041       1 controller.go:399] Resize PVC "<claimName>" finished
```

But after checking the csi-attacher pod logs, I see some errors while trying to attach the resized volume:
```bash
kubectl logs -n longhorn-system <csi-attacher-pod>
[...]
I0503 12:09:46.012717       1 connection.go:186] GRPC error: rpc error: code = Aborted desc = The volume <volume-name> is not ready for workloads
I0503 12:09:46.018720       1 csi_handler.go:219] Error processing "<csi-id>": failed to attach: rpc error: code = Aborted desc = The volume <volume-name> is not ready for workloads
```

Also, if I check the Longhorn volume object in Kubernetes, it is in "unknown" state, and the events comment something about a DR volume:
```bash
kubectl describe volume -n longhorn-system <volume-name>
[...]
Spec:
  Access Mode:                rwx
  Last Attached By:
  Number Of Replicas:         1
  Size:                       6442450944
[...]
Robustness:            unknown
  Share Endpoint:
  Share State:           stopped
  State:                 detached
Events:
  Type    Reason              Age                From                        Message
  ----    ------              ----               ----                        -------
  Normal  Attached            26m (x2 over 67m)  longhorn-volume-controller  volume <volume-name> has been attached to <node-name>
  Normal  SucceededExpansion  26m (x4 over 26m)  longhorn-volume-controller  Succeeds to expand the volume <volume-name> to size 6442450944, will automatically detach it if it's not DR volume
  Normal  Detached            26m (x3 over 67m)  longhorn-volume-controller  volume <volume-name> has been detached
```
Is this the expected behavior of the RWX volumes? Do I need to configure something else in Longhorn for the RWX volumes so they can be resized, something related with DR volumes?

FYI: I have tried to perform the same steps in a DaemonSet that was using a RWO (ReadWriteOnce) volume, and the process is working as expected.

This is the configuration that I'm using to deploy Longhorn in the cluster (Longhorn deployed using Helm Chart):
```yaml
persistence:
  defaultClass: false
  defaultClassReplicaCount: 1
  reclaimPolicy: Delete
  recurringJobs:
    enable: false
    jobList: []

csi:
  kubeletRootDir: ~
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

defaultSettings:
  replicaSoftAntiAffinity: true
  upgradeChecker: false
  defaultReplicaCount: 1
  guaranteedEngineCPU: 0.5
  autoDeletePodWhenVolumeDetachedUnexpectedly: true
  disableSchedulingOnCordonedNode: true
  replicaZoneSoftAntiAffinity: true
```
All the other configuration fields are set as the default values.

**Expected behavior**
The RWX volume of the DaemonSet is successfully resized to 6Gi, and the new volume is successfully attached to the new pod of the DaemonSet

**Log**
Logs of the pods/volumes are described above

**Environment:**
 - Longhorn version: v1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm Chart
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3S v1.20.4+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 0
 - Node config
   - OS type and version: CentOS Linux release 7.9.2009 (Core)
   - CPU per node: 4 
   - Memory per node: 8 
   - Disk type(e.g. SSD/NVMe): Hard Disk
   - Network bandwidth between the nodes: -
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare vSphere
 - Number of Longhorn volumes in the cluster: 5

**Additional context**

**Comment by joshimoo** [comment]
This issue should be fixed in v1.1.1, are you able to upgrade to it?
As a workaround you can:
- manually attach the rwx volume via the longhorn ui to a node, afterwards the share-manager should take over and detach and attach it again
- patch the volumes.longhorn.io volume object and unset the spec.disableFrontend flag.

**Comment by aalcaraz97** [comment]
Thanks for the quick response! @joshimoo 

I upgraded the Longhorn Helm Chart to v1.1.1 and repeated the whole process for resizing the Persistent Volume. Now it is working successfully!

**Comment by khushboo-rancher** [comment]
@aalcaraz97 Good to know that it worked. Closing this, feel free to reopen if you find issue happening again.
