### ISSUE TITLE
[BUG] Drop down for create backing image is not proper.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2568]
**Describe the bug**
The dropdown is not of similar size of the text box, which is appearing little odd.

<img width="1318" alt="Screen Shot 2021-05-04 at 1 41 59 PM" src="https://user-images.githubusercontent.com/60111667/117067172-893b1580-acde-11eb-8456-f7311c736893.png">

**Environment:**
 - Longhorn version: v1.1.1

**Comment by smallteeths** [comment]
This `autocomplete` feature has no control over its style on the front-end now, this is a feature that comes with the browser. The only way to do this now is to disable `autocomplete`. Do we want to disable it? @khushboo-rancher

**Comment by khushboo-rancher** [comment]
No, let the `autocomplete` be enabled. I can close this issue for now.
