### ISSUE TITLE
[FEATURE] Use config map rather than annotations to customize the node tags and default disks

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2569]
**Is your feature request related to a problem? Please describe.**
Right now the user experience of the node tags and default disks customization is not good:
1. Users may encounter the escaping issue when setting labels or annotations for the Kubernetes node. Especially when users cannot directly setting them via `kubectl edit node`
2. The customization requires lots of steps. And users need to be careful about the sequence of the steps. 

**Describe the solution you'd like**
We can use a config map to store the default disk/node tag config instead.

**Additional context**
The current instruction doc: https://longhorn.io/docs/1.1.1/advanced-resources/default-disk-and-node-config/#customizing-default-disks-for-new-nodes

**Comment by joshimoo** [comment]
I discussed with shuo to get a better understanding of the current flow, below is my though experiment, leaving this here for me to later reference :)

So if I wanted scale my cluster with custom config right from the beginning:
- enable setting `Create Default Disk on Labeled Nodes` as part of the default longhorn installation
- label node X with `node.longhorn.io/create-default-disk: true` (default disk)
- node X gets the default disk
- label node Y,Z with `node.longhorn.io/create-default-disk: config` (annotation mode)
- node Y,Z waits for annotation
- add annotation to node Y -> disks get created
- add annotation to node Z -> disks get created
- add node A no labels -> no disks get created

**Comment by joshimoo** [comment]
One issue that has been identified is that it's hard to get the encoding of the annotation / label correct.
