### ISSUE TITLE
How do I set up a local s3 backup target in Longhorn?

### ISSUE THREAD

**Issue by TheLazyIt** [longhorn/longhorn#2572]
Noob question here. Sorry if I missed the answer in the documentation. I've set up Minio on a TrueNAS for testing. I'd like to use this as the backup target for Longhorn and have configured Rancher with the Access Key and Secret Key. If I were going to AWS, I know that I would enter s3://bucket-name@aws-region/ but I'm confused how this would work for a bucket that is on my local network. I've tried a few different things such as s3://bucket-name@IP/ without any success. Any help is appreciated. Thanks.

![image](https://user-images.githubusercontent.com/61567276/117142746-ad960100-ad75-11eb-90a6-73350dd4298d.png)

**Comment by jenting** [comment]
It depends on the `AWS_ENDPOINTS` env variable in Secret, ref to https://longhorn.io/docs/1.1.1/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-a-local-testing-backupstore.

**Comment by TheLazyIt** [comment]
This helps a lot. Thank you!!
