### ISSUE TITLE
[QUESTION] Bash required?

### ISSUE THREAD

**Issue by dragon2611** [longhorn/longhorn#2573]
**Question**

**Environment:**
v1.1.1
 v1.20.6+k3s1
 - Node config
   - Alpine  (2x worker)
   - Ubuntu 20.04 (Worker/master)
  

Does Longhorn Require Bash?

Reason I ask is because I'd installed the following and remounted / as shared and whilst longhorn was running I couldn't get anything to mount if the pod was scheduled to the alpine node, longhorn would be showing attaching/detaching constantly.

open-iscsi
nfs-utils
util-linux 

Then I installed bash on one of the workers to run the pre-check script in https://github.com/longhorn/website/blob/b06f9b278cc75435672c2ffba7560f12d78d25ff/content/docs/0.8.1/deploy/install/_index.md (which btw reported an error about mount propagation but I doubt it was correct as it was failing at connecting to localhost:8080 anyway)

Anyway I noticed that the pods had managed to mount their disks after a while.

I then moved onto the 2nd node and checking it's packages/config against the first one the only thing I could find different was it didn't have bash, it seems after I ran apk add bash longhorn was suddenly able to mount the volumes on that node as well.

**Comment by jenting** [comment]
Could you please check the `lsblk` in installed? Ref to https://github.com/longhorn/longhorn/issues/1289#issuecomment-625761494
Please make sure the installation requirement are fulfilled https://longhorn.io/docs/1.1.1/deploy/install/#installation-requirements

**Comment by dragon2611** [comment]
@jenting It's in util-linux and is present on the system, on both nodes longhorn didn't start working until I installed bash, on the 2nd one it was the last thing I did to the node.

That's why I was worndering if there's any shell scripting happening that isn't happy in ash.

**Comment by jenting** [comment]
I think the answer is _yes_, Longhorn need *bash*, for example, the code snippet is to detect file system.
https://github.com/longhorn/longhorn-manager/blob/v1.1.1/util/util.go#L755

**Comment by PhanLe1010** [comment]
Thanks @dragon2611 
We have a new document link at https://longhorn.io/docs/1.1.1/deploy/install/#installation-requirements. This document is missing `bash` though. We should update it to include `bash`

**Comment by jenting** [comment]
Chart README should be updated also https://github.com/longhorn/longhorn/tree/v1.1.1/chart#prerequisites

**Comment by innobead** [comment]
> Chart README should be updated also https://github.com/longhorn/longhorn/tree/v1.1.1/chart#prerequisites

@c3y1huang could u help with this? Thanks.

**Comment by joshimoo** [comment]
I am guessing it's possible to replace the bash specific calls/features with more general shell commands/features.
Whether we want to put in that effort to identify all the relevant changes and do the necessary modifications seems low priority.
But a great place for a community PR contribution, so I am marking this as good first issue, since it doesn't necessary require longhorn specific knowledge and could be a good first contribution with some help from our side.
