### ISSUE TITLE
[QUESTION] engine image pods trying to be deployed on no longer existing nodes

### ISSUE THREAD

**Issue by golgotow** [longhorn/longhorn#2578]
Hello,

From where we can check why longhorn trying to create pods on non existing nodes ?
We get some crash on cluster, broken nodes was removed, but longhorn still trying to use them.
From web manager this nodes are mising now.

$ kubectl get nodes
NAME           STATUS   ROLES                  AGE     VERSION
brixone        Ready    control-plane,master   29d     v1.20.5+k3s1
kube1-worker   Ready    <none>                 4h53m   v1.20.6+k3s1
kube2-worker   Ready    <none>                 4h48m   v1.20.6+k3s1
corosync       Ready    control-plane,master   29d     v1.20.5+k3s1
msi55          Ready    control-plane,master   29h     v1.20.6+k3s1
$ kubectl -n longhorn-system get pods -o wide|grep prox
engine-image-ei-deb8b464-wj75x              0/1     Pending    0          3m12s   <none>        prox2          <none>           <none>
engine-image-ei-deb8b464-tmrr4              0/1     Pending    0          3m12s   <none>        prox3          <none>           <none>
engine-image-ei-817782be-5dltx              0/1     Pending    0          3m12s   <none>        prox2          <none>           <none>
engine-image-ei-817782be-7t5s6              0/1     Pending    0          3m12s   <none>        prox3          <none>           <none>

Best regards

**Environment:**
 - Longhorn version: 1.1.100
 - Kubernetes version: 1.20.5
 - Node config
   - OS type and version Debian 10
   - CPU per node: 4
   - Memory per node: 4G
   - Disk type - ssd
   - Network bandwidth and latency between the nodes: 1G 
 - Underlying Infrastructure KVM / baremetal

**Additional context**

**Comment by joshimoo** [comment]
Can you run the following commands and post their output
`kubectl get nodes.longhorn.io -n longhorn-system`
`kubectl get engineimages.longhorn.io ei-817782be -o yaml -n longhorn-system`
`kubectl get engineimages.longhorn.io ei-deb8b464 -o yaml -n longhorn-system`

**Comment by golgotow** [comment]
Hello,

in those engine those old nodes are still listed.

psobota@msiapache2ssd ~ $  kubectl get nodes.longhorn.io -n longhorn-system
NAME           READY   ALLOWSCHEDULING   SCHEDULABLE   AGE
msi55          True    true              True          29d
brixone        True    true              True          29d
corosync       True    true              True          29d
kube2-worker   True    false             True          171m
kube1-worker   True    false             True          172m
psobota@msiapache2ssd ~ $  kubectl get engineimages.longhorn.io ei-817782be -o yaml -n longhorn-system
apiVersion: longhorn.io/v1beta1
kind: EngineImage
metadata:
  creationTimestamp: "2021-05-07T08:55:20Z"
  finalizers:
  - longhorn.io
  generation: 1
  labels:
    longhorn.io/component: engine-image
    longhorn.io/engine-image: ei-817782be
    longhorn.io/managed-by: longhorn-manager
  managedFields:
  - apiVersion: longhorn.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"longhorn.io": {}
        f:labels:
          .: {}
          f:longhorn.io/component: {}
          f:longhorn.io/engine-image: {}
          f:longhorn.io/managed-by: {}
      f:spec: {}
      f:status: {}
    manager: longhorn-manager
    operation: Update
    time: "2021-05-07T08:55:20Z"
  name: ei-817782be
  namespace: longhorn-system
  resourceVersion: "42657095"
  uid: e16ac97b-d1a0-4f99-9ced-3c31c31284e1
spec:
  image: rancher/mirrored-longhornio-longhorn-engine:v1.1.1
status:
  buildDate: "2021-04-23T02:29:18+00:00"
  cliAPIMinVersion: 3
  cliAPIVersion: 4
  conditions:
    ready:
      lastProbeTime: ""
      lastTransitionTime: "2021-05-07T09:32:19Z"
      message: Engine image ei-817782be (rancher/mirrored-longhornio-longhorn-engine:v1.1.1)
        is fully deployed on all ready nodes
      reason: ""
      status: "True"
      type: ready
  controllerAPIMinVersion: 3
  controllerAPIVersion: 3
  dataFormatMinVersion: 1
  dataFormatVersion: 1
  gitCommit: 3cc56fd7c02269718bbe276f78fe7257e46c6c1a
  noRefSince: "2021-05-07T08:55:22Z"
  nodeDeploymentMap:
    brixone: true
    corosync: true
    kube1-worker: true
    kube2-worker: true
    msi55: true
    prox2: true
    prox3: true
  ownerID: brixone
  refCount: 0
  state: deployed
  version: v1.1.1
psobota@msiapache2ssd ~ $  kubectl get engineimages.longhorn.io ei-deb8b464 -o yaml -n longhorn-system
apiVersion: longhorn.io/v1beta1
kind: EngineImage
metadata:
  creationTimestamp: "2021-04-08T08:58:33Z"
  finalizers:
  - longhorn.io
  generation: 1
  labels:
    longhorn.io/component: engine-image
    longhorn.io/engine-image: ei-deb8b464
    longhorn.io/managed-by: longhorn-manager
  managedFields:
  - apiVersion: longhorn.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"longhorn.io": {}
        f:labels:
          .: {}
          f:longhorn.io/component: {}
          f:longhorn.io/engine-image: {}
          f:longhorn.io/managed-by: {}
      f:spec: {}
      f:status: {}
    manager: longhorn-manager
    operation: Update
    time: "2021-05-07T08:55:09Z"
  name: ei-deb8b464
  namespace: longhorn-system
  resourceVersion: "42697016"
  uid: 34167443-b637-4385-b44a-80c2fa11c7ee
spec:
  image: rancher/mirrored-longhornio-longhorn-engine:v1.1.0
status:
  buildDate: "2020-12-18T00:38:19+00:00"
  cliAPIMinVersion: 3
  cliAPIVersion: 4
  conditions:
    ready:
      lastProbeTime: ""
      lastTransitionTime: "2021-05-07T10:04:17Z"
      message: Engine image ei-deb8b464 (rancher/mirrored-longhornio-longhorn-engine:v1.1.0)
        is fully deployed on all ready nodes
      reason: ""
      status: "True"
      type: ready
  controllerAPIMinVersion: 3
  controllerAPIVersion: 3
  dataFormatMinVersion: 1
  dataFormatVersion: 1
  gitCommit: b9e072eb19cfcc27894e10a8e60794c66ca918f8
  noRefSince: ""
  nodeDeploymentMap:
    brixone: true
    corosync: false
    kube1-worker: true
    kube2-worker: true
    msi55: true
    prox1: false
    prox2: true
    prox3: true
  ownerID: msi55
  refCount: 9
  state: deployed
  version: v1.1.0

**Comment by joshimoo** [comment]
cc @PhanLe1010 looks like we are not removing deleted nodes from the engine-image deployment maps.

**Comment by golgotow** [comment]
any possiblity to edit it manualy to get rid of it on working cluster?

**Comment by golgotow** [comment]
is any way to fix it now, or shall we re-install and lost some data ?

**Comment by joshimoo** [comment]
@golgotow a reinstall should not be necessary, is the system currently not working?

**Comment by golgotow** [comment]
@joshimoo system works in strange way, looks works but backup cannot be takend from web portal, and update of engine is not possible and crashing on daemonset , as this still trying to start pods on non existing nodes

**Comment by golgotow** [comment]
this act very strange, after 2 days of investigation, engine drop those non existing nodes and start to works as expected. Closing
