### ISSUE TITLE
FailedAttachVolume: can't find driver driver.longhorn.io

### ISSUE THREAD

**Issue by sirpeanut** [longhorn/longhorn#2580]
I'm trying to set up a fresh installation of Longhorn v1.1.1 on microk8s 1.21. Installation goes fine, with no errors, and I can access the web UI, but whenever I try to start a pod that uses a Longhorn PVC, I get:

  Warning  FailedAttachVolume  1s (x6 over 19s)  attachdetach-controller  AttachVolume.Attach failed for volume "volume-name" : CSINode node-name does not contain driver driver.longhorn.io

This is true regardless of whether I first create the volume, PV and PVC via the web UI, or if I just use a StorageClass in a YAML config file.

All of the Longhorn pods are up and running on that node:

longhorn-ui-5b864949c4-smq75               1/1     Running   0          36m   10.1.208.11   node-name          <none>           <none>
instance-manager-r-0d1ad1ab                1/1     Running   0          35m   10.1.208.15   node-name          <none>           <none>
instance-manager-e-c899ab86                1/1     Running   0          35m   10.1.208.14   node-name          <none>           <none>
longhorn-manager-2lgh8                     1/1     Running   1          36m   10.1.208.12   node-name          <none>           <none>
engine-image-ei-611d1496-9vjbv             1/1     Running   0          35m   10.1.208.13   node-name          <none>           <none>
csi-attacher-5dcdcd5984-9g8kj              1/1     Running   0          35m   10.1.208.16   node-name          <none>           <none>
csi-provisioner-5c9dfb6446-8zgbh           1/1     Running   0          35m   10.1.208.17   node-name          <none>           <none>
csi-provisioner-5c9dfb6446-gtzv4           1/1     Running   0          35m   10.1.208.18   node-name          <none>           <none>
csi-resizer-6696d857b6-tkq7h               1/1     Running   0          35m   10.1.208.19   node-name          <none>           <none>
longhorn-csi-plugin-kqtfr                  2/2     Running   0          35m   10.1.208.20   node-name          <none>           <none>

I also don't see any errors in the logs for longhorn-csi-plugin:

$ kubectl -n longhorn-system logs longhorn-csi-plugin-kqtfr node-driver-registrar

I0507 22:58:47.433019   15004 main.go:110] Version: v1.2.0-lh1-0-g03d523f9
I0507 22:58:47.433106   15004 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0507 22:58:47.433125   15004 connection.go:151] Connecting to unix:///csi/csi.sock
I0507 22:58:48.433814   15004 main.go:127] Calling CSI driver to discover driver name
I0507 22:58:48.433853   15004 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I0507 22:58:48.433863   15004 connection.go:181] GRPC request: {}
I0507 22:58:48.437420   15004 connection.go:183] GRPC response: {"name":"driver.longhorn.io","vendor_version":"v1.1.1"}
I0507 22:58:48.437875   15004 connection.go:184] GRPC error: <nil>
I0507 22:58:48.437883   15004 main.go:137] CSI driver name: "driver.longhorn.io"
I0507 22:58:48.469790   15004 node_register.go:58] Starting Registration Server at: /registration/driver.longhorn.io-reg.sock
I0507 22:58:48.469969   15004 node_register.go:67] Registration Server started at: /registration/driver.longhorn.io-reg.sock

$ I0507 22:58:47.433019   15004 main.go:110] Version: v1.2.0-lh1-0-g03d523f9
I0507 22:58:47.433106   15004 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0507 22:58:47.433125   15004 connection.go:151] Connecting to unix:///csi/csi.sock
I0507 22:58:48.433814   15004 main.go:127] Calling CSI driver to discover driver name
I0507 22:58:48.433853   15004 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I0507 22:58:48.433863   15004 connection.go:181] GRPC request: {}
I0507 22:58:48.437420   15004 connection.go:183] GRPC response: {"name":"driver.longhorn.io","vendor_version":"v1.1.1"}
I0507 22:58:48.437875   15004 connection.go:184] GRPC error: <nil>
I0507 22:58:48.437883   15004 main.go:137] CSI driver name: "driver.longhorn.io"
I0507 22:58:48.469790   15004 node_register.go:58] Starting Registration Server at: /registration/driver.longhorn.io-reg.sock
I0507 22:58:48.469969   15004 node_register.go:67] Registration Server started at: /registration/driver.longhorn.io-reg.sock
nthomas-macbookpro4% kubectl -n longhorn-system logs longhorn-csi-plugin-kqtfr longhorn-csi-plugin
2021/05/07 22:58:47 proto: duplicate proto type registered: VersionResponse
time="2021-05-07T22:58:47Z" level=info msg="CSI Driver: driver.longhorn.io csiVersion: 0.3.0, manager URL http://longhorn-backend:9500/v1"
time="2021-05-07T22:58:47Z" level=info msg="Enabling node service capability: GET_VOLUME_STATS"
time="2021-05-07T22:58:47Z" level=info msg="Enabling controller service capability: CREATE_DELETE_VOLUME"
time="2021-05-07T22:58:47Z" level=info msg="Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME"
time="2021-05-07T22:58:47Z" level=info msg="Enabling controller service capability: EXPAND_VOLUME"
time="2021-05-07T22:58:47Z" level=info msg="Enabling controller service capability: CREATE_DELETE_SNAPSHOT"
time="2021-05-07T22:58:47Z" level=info msg="Enabling volume access mode: SINGLE_NODE_WRITER"
time="2021-05-07T22:58:47Z" level=info msg="Enabling volume access mode: MULTI_NODE_MULTI_WRITER"
time="2021-05-07T22:58:47Z" level=info msg="Listening for connections on address: &net.UnixAddr{Name:\"//csi/csi.sock\", Net:\"unix\"}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Identity/Probe request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Identity/GetPluginInfo request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {\"name\":\"driver.longhorn.io\",\"vendor_version\":\"v1.1.1\"}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Identity/GetPluginCapabilities request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {\"capabilities\":[{\"Type\":{\"Service\":{\"type\":1}}},{\"Type\":{\"VolumeExpansion\":{\"type\":2}}}]}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Controller/ControllerGetCapabilities request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {\"capabilities\":[{\"Type\":{\"Rpc\":{\"type\":1}}},{\"Type\":{\"Rpc\":{\"type\":2}}},{\"Type\":{\"Rpc\":{\"type\":9}}},{\"Type\":{\"Rpc\":{\"type\":5}}}]}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Controller/ControllerGetCapabilities request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {\"capabilities\":[{\"Type\":{\"Rpc\":{\"type\":1}}},{\"Type\":{\"Rpc\":{\"type\":2}}},{\"Type\":{\"Rpc\":{\"type\":9}}},{\"Type\":{\"Rpc\":{\"type\":5}}}]}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Identity/Probe request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Identity/Probe request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Identity/GetPluginInfo request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {\"name\":\"driver.longhorn.io\",\"vendor_version\":\"v1.1.1\"}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Identity/GetPluginInfo request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {\"name\":\"driver.longhorn.io\",\"vendor_version\":\"v1.1.1\"}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Identity/GetPluginCapabilities request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {\"capabilities\":[{\"Type\":{\"Service\":{\"type\":1}}},{\"Type\":{\"VolumeExpansion\":{\"type\":2}}}]}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Identity/GetPluginCapabilities request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {\"capabilities\":[{\"Type\":{\"Service\":{\"type\":1}}},{\"Type\":{\"VolumeExpansion\":{\"type\":2}}}]}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Controller/ControllerGetCapabilities request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {\"capabilities\":[{\"Type\":{\"Rpc\":{\"type\":1}}},{\"Type\":{\"Rpc\":{\"type\":2}}},{\"Type\":{\"Rpc\":{\"type\":9}}},{\"Type\":{\"Rpc\":{\"type\":5}}}]}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Controller/ControllerGetCapabilities request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {\"capabilities\":[{\"Type\":{\"Rpc\":{\"type\":1}}},{\"Type\":{\"Rpc\":{\"type\":2}}},{\"Type\":{\"Rpc\":{\"type\":9}}},{\"Type\":{\"Rpc\":{\"type\":5}}}]}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Identity/GetPluginInfo request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {\"name\":\"driver.longhorn.io\",\"vendor_version\":\"v1.1.1\"}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Identity/Probe request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Identity/GetPluginInfo request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {\"name\":\"driver.longhorn.io\",\"vendor_version\":\"v1.1.1\"}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Identity/GetPluginCapabilities request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {\"capabilities\":[{\"Type\":{\"Service\":{\"type\":1}}},{\"Type\":{\"VolumeExpansion\":{\"type\":2}}}]}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC call: /csi.v1.Controller/ControllerGetCapabilities request: {}"
time="2021-05-07T22:58:48Z" level=info msg="GRPC response: {\"capabilities\":[{\"Type\":{\"Rpc\":{\"type\":1}}},{\"Type\":{\"Rpc\":{\"type\":2}}},{\"Type\":{\"Rpc\":{\"type\":9}}},{\"Type\":{\"Rpc\":{\"type\":5}}}]}"

**Comment by sirpeanut** [comment]
I fixed this. I think the problem may be that microk8s 1.21 runs a process called kubelite, rather than kubelet, so the script Longhorn uses to try to figure out the KUBELET_ROOT_DIR fails. I fixed this by manually setting KUBELET_ROOT_DIR to /var/snap/microk8s/common/var/lib/kubelet.

I wonder if maybe microk8s only recently changed to kubelite, and if the Longhorn install script needs to be updated?

**Comment by cclhsu** [comment]
Thanks for the update.  Different OS/Distro might have different configuration for kubelet root path. In [OS/Distro Specific Configuration](https://longhorn.io/docs/1.1.1/advanced-resources/os-distro-specific/), Longhorn has provided a few guide for user to troubleshoot and set the KUBELET_ROOT_DIR.

**Comment by PhanLe1010** [comment]
Close because the issue is resolved
