### ISSUE TITLE
[QUESTION] Pods with RWX are stuck at mount volume on specific node/nodes

### ISSUE THREAD

**Issue by surenraju-zz** [longhorn/longhorn#2583]
**Question**

I got into some unexpected behavior for RWX workloads with longhorn. When I added additional nodes to existing Rancher cluster, I noticed that the application pod with RWX volume  scheduled on a specific node/nodes which are newly added, the volumes are not getting mounted.

Following are the events for the application pod.

```
FailedMount (44)	8 secs ago	Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[persistent-storage default-token-5nw2t]: timed out waiting for the condition
FailedMount (13)	25 mins ago	Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[default-token-5nw2t persistent-storage]: timed out waiting for the condition
FailedMount (30)	31 mins ago	MountVolume.SetUp failed for volume "pvc-39958a19-a45f-4bb2-a27d-e8f76d8b4cb8" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

However, if a pod with same configuration is deployed in other node/nodes, it is working as expected.

For example,

```
busybox-n5 - worker5 - Waiting on volume
busybox-n7 - worker7 - Running
```

When I was inspecting the `longhorn-csi-plugin` logs, I noticed the time taken between the logs messages after mount related log, the time difference was huge on `worker5` comparing the log statements from `worker7`.
To understand more, I `'sh' `into both the `longhorn-csi-plugin` containers from `worker5 `and `worker7 `and entered worker's bash using `nsenter ` command.

**Inside longhorn-csi-plugin container from worker5**

```
kubectl exec -n longhorn-system -i -t longhorn-csi-plugin-4hkxx --container longhorn-csi-plugin -- /bin/bash
nsenter --mount=/proc/1/ns/mnt --net=/proc/1/ns/net --uts=/proc/1/ns/uts -- /bin/bash

/bin/mount -t nfs -o vers=4.1,noresvport,soft,sync,intr,timeo=7,retrans=3 10.43.145.149:/pvc-39958a19-a45f-4bb2-a27d-e8f76d8b4cb8 /var/lib/kubelet-test/pods/20b35a34-b7bb-4fb7-9715-fd62d8e44b55/volumes/kubernetes.io~csi/pvc-39958a19-a45f-4bb2-a27d-e8f76d8b4cb8/mount

#kubelet-test dir was created for testing purpose
#The above command was stuck forever
```

**Inside longhorn-csi-plugin container from worker7**

```
kubectl exec -n longhorn-system -i -t  longhorn-csi-plugin-hqx79 --container longhorn-csi-plugin -- /bin/bash
nsenter --mount=/proc/1/ns/mnt --net=/proc/1/ns/net --uts=/proc/1/ns/uts -- /bin/bash

/bin/mount -t nfs -o vers=4.1,noresvport,soft,sync,intr,timeo=7,retrans=3 10.43.145.149:/pvc-39958a19-a45f-4bb2-a27d-e8f76d8b4cb8 /var/lib/kubelet-test/pods/20b35a34-b7bb-4fb7-9715-fd62d8e44b55/volumes/kubernetes.io~csi/pvc-39958a19-a45f-4bb2-a27d-e8f76d8b4cb8/mount

#The above command mounted the folder to respective directory and exited
```

Please help me understand the problem with nfs mount command on `worker5`. I have tried unintall and install of NFS client but the issue is not resolved.

I am attaching the `longhorn-csi-plugin` logs from both [worker5 ](https://raw.githubusercontent.com/surenraju/longhorn-logs/master/nfs_mount_timeout_worker5.txt)and [worker7](https://raw.githubusercontent.com/surenraju/longhorn-logs/master/nfs_mount_normal_worker7.txt)  for your reference.

Kindly help. Many thanks in advance. 

**Environment:**
 - Longhorn version: longhorn:1.1.000
 - Kubernetes version: v1.20.6
 - Node config
   - OS type and version Ubuntu 16.04.4 LTS 4.4.0-1052-aws
   - CPU per node: 4 Reserved
   - Memory per node: 15.6 GiB Reserved
 - Architecture | amd64
 - Docker Version | 20.10.6
 - Kernel Version | 4.4.0-1052-aws
 - Kubelet Version | v1.20.6
 - Kube Proxy Version | v1.20.6
 - Operating System Image | Ubuntu 16.04.4 LTS
 - Operating System | linux
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS

**Comment by surenraju** [comment]
Often I notice this issue. On random node/nodes, CSI plugin is stuck on mount command. I also noticed that after restarting `longhorn-csi-plugin-____` for that problematic node, issue is getting resolved. But issue appears in another node after few days. 

Could this be related to amount of data the RWX volume holds? We are using RWX volumes with argo workflows. 100's of pods are launched with that specific RWX volumes.  There pods run to complete some steps and new pods will be launched. All those 100's of the pods will consume same RWX volume.

**Comment by cclhsu** [comment]
HI! Can you provide support bundle when the problem occurred before restart the longhorn-csi-plugiwn? 

Also, in slack channel https://cloud-native.slack.com/archives/CNVPEL9U3/p1620804509124300?thread_ts=1620705660.119100&cid=CNVPEL9U3, the log has `no space left on device`.  Can provide storage spec and currently used in problem work nodes?

**Comment by sinoon** [comment]
I have same error and restart all longhorn-csi-plugin_ can resolve this error.

**Comment by jenting** [comment]
It's probably related to the https://github.com/longhorn/longhorn/issues/2465#issuecomment-867504252
