### ISSUE TITLE
[TASK] Add test cases for backup listing related to scalability and stress

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2586]
**What's the task? Please describe.**
Add manual test cases for backup listing related to scalability and stress

**Additional context**
https://github.com/longhorn/longhorn/issues/2543
https://github.com/longhorn/longhorn/issues/1904

**Comment by jenting** [comment]
Generally, the test case PR focus on a pretty good network.
For issues #1955 and #2543, both LH cluster to S3/NFS bucket network latency is pretty high 700ms-800ms.

Maybe we should add a test case for this. But before that, we have to define criteria on what's the maximum network latency from LH cluster to S3/NFS bucket, and what's the maximum volumes and backups per volume we allowed for the user to perform list operation.

**Comment by khushboo-rancher** [comment]
@jenting Good point. I'll test the backup listing with different network latency and try to come up for min max of preferable network speed.

**Comment by khushboo-rancher** [comment]
Below is the observation regarding the timeout for different latency.
<img width="767" alt="Screen Shot 2021-05-16 at 11 49 11 PM" src="https://user-images.githubusercontent.com/60111667/118443987-6d058400-b6a1-11eb-9f57-beac2172a8b3.png">

I'm planning to test with different numbers of volumes.

**Comment by khushboo-rancher** [comment]
Waiting for https://github.com/longhorn/longhorn/issues/2543 and @jenting to come up with the optimized latency Longhorn can tolerate and will update the test cases accordingly.

**Comment by innobead** [comment]
I don't think we need this anymore after 1.2.0 with #2623 introduced. 

Closing first, then see if we need afterward.
