### ISSUE TITLE
[BUG] Installation on clusters with windows nodes fails...

### ISSUE THREAD

**Issue by ernani** [longhorn/longhorn#2588]
**Describe the bug**
Installation in a kubernetes cluster that has windows nodes fails.

**To Reproduce**
Create a windows nodepool in AKS for instance and try to install the yaml file from docs.

**Expected behavior**
It should filter for kubernetes.io/os: linux as a nodeSelector

**Environment:**
 - Longhorn version: 0.8.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 1.19.9
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 9
 - Node config
   - OS type and version: windows and linux nodes
   - CPU per node: 2
   - Memory per node: 8gb
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: unknown
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Azure/AKS
 - Number of Longhorn volumes in the cluster: 0

**Comment by jenting** [comment]
The Longhorn v0.8.0 is pretty old, and we had an improvement on the mixed cluster (Linux+Windows) in Longhorn v1.1.1.
@PhanLe1010 could provide more detail on this.

**Comment by cclhsu** [comment]
This is the document to set up mixed cluster in Longhorn v1.1.1: https://longhorn.io/docs/1.1.1/advanced-resources/deploy/rancher_windows_cluster/

**Comment by ernani** [comment]
Thanks for the brevity and help. I am not sure why I got redirected to installing v0.8.0, restarting with v1.1.1 now. Closing the issue.
