### ISSUE TITLE
[BUG] full data over WS at per 30/seconds interval seems useless

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2591]
**Describe the bug**
All websockets periodically sending full data every 30 seconds.
![Screenshot-2021-05-13-16:55:30](https://user-images.githubusercontent.com/22583541/118104434-b9d12c80-b40d-11eb-88d8-5927aece2338.png)

**To Reproduce**
`n/a`

**Expected behavior**
Sends data at resource update only.

**Log**
`n/a`

**Environment:**
`n/a`

**Additional context**
https://github.com/longhorn/longhorn/issues/2372

**Comment by c3y1huang** [comment]
Added to 1.2.0. /cc @innobead

**Comment by khushboo-rancher** [comment]
Validated with Longhorn v1.1.2-head and master-head `06/01/2021`

Validation - **Pass**

The full data over WS is not observed every 30 seconds.
