### ISSUE TITLE
batch update schedule ui is not starting empty

### ISSUE THREAD

**Issue by n0rad** [longhorn/longhorn#2596]
I create volumes by hand in the UI to be resilient to PV/PVC lose in the cluster, or even cluster lose.
So I often have to update schedule by hand to add back or apply same schedule to most volumes.

That would be great to have the UI filled up with any of the first volume having schedule, so there is not that much to set up before applying.

**Comment by innobead** [comment]
Closing, because this is related to #467 which is planned in 1.2.0.
