### ISSUE TITLE
[QUESTION] Until backups are refactored, how should I delete snapshots created through CSI

### ISSUE THREAD

**Issue by jf647** [longhorn/longhorn#2597]
**Question**

First, I want to make sure I'm interpreting the problem correctly; forgive the verbosity.

I'm using https://github.com/FairwindsOps/gemini to backup my longhorn volumes through the CSI snapshotter interface.  In terms of the touchpoints, all that matters is that the Gemini controller periodically creates a VolumeSnapshot for a given PVC.  It also handles removing of those objects.  For example, given this `SnapshotGroup` config (the Gemini CRD):

```yaml
---
apiVersion: gemini.fairwinds.com/v1beta1
kind: SnapshotGroup
metadata:
  name: my-pvc-name
spec:
  persistentVolumeClaim:
    claimName: my-pvc-name
  schedule:
    - every: hour
      keep: 5
    - every: day
      keep: 7
    - every: week
      keep: 2
    - every: month
      keep: 1
```

If I look for `VolumeSnapshots` for that PVC, I currently have 13 (the oldest is 5d old as I've only recently started using Gemini).

If I go and look at the Longhorn UI, I see a warning about `toomanysnapshots`, saying that I have 115 snapshots which is over the limit of 100:

![image](https://user-images.githubusercontent.com/41579/118408967-ff277100-b63c-11eb-936b-5fe8c81c9148.png)

The oldest snapshot icon I can see is blue (so just a snapshot), and I can't even see the right side of the snapshot graph because there's no vertical scroll and as I scroll to the right, the icons climb up (signifying later times) and quickly are outside the viewable area:

![image](https://user-images.githubusercontent.com/41579/118408993-254d1100-b63d-11eb-9c43-f37ead2fabe7.png)

If I look at a more recently created volume, I can see that only the snapshots retained by Gemini (i.e. the ones that still have an active `VolumeSnapshot` object) are marked as green while the others are blue:

![image](https://user-images.githubusercontent.com/41579/118409050-74934180-b63d-11eb-85da-ae4c42f6e01e.png)

My first question is: am I interpreting correctly that the Longhorn snapshots are not deleted when the K8S `VolumeSnapshot` that created them is removed?  The `VolumeSnapshotClass` in question does have the deletion policy set to `Delete`, but I think this describes the backups to S3, right?

Assuming the answer to the first question is yes, am I also correct in that the long-term fix for this lies somewhere in the backup refactoring described in #1761?

And finally, assuming that the answer to the second question is also yes, what is recommended in the short term?  These snapshots created by Longhorn don't have associated k8s objects, so it's not a simple matter to query for them via the K8s API server.

I can see that in the Longhorn engine docker image that the longhorn binary has a `snapshot ls` command, but running it from inside a running engine image, I haven't been able to get a connection to the backend:

```shell
$ longhorn --url http://longhorn-backend:9500 snapshot ls
FATA[0000] Error running ls snapshot command: failed to list replicas for volume longhorn-backend:9500: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection closed
$ longhorn info --url http://longhorn-backend:9500
Incorrect Usage: flag provided but not defined: -url
```

(which actually seems to suggest the flag parsing doesn't match the help, as I'm telling it to go to the host longhorn-backend, not asking about a volume called longhorn-backend).

I'm comfortable developing against the gRPC interface of the manager if that's the best way to go; I just wanted to check if there was an easier way first.

**Environment:**
 - Longhorn version: v1.1.1
 - Kubernetes version: v1.20.5
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): RKE on Alpine running in VMs on Proxmox.

**Comment by joshimoo** [comment]
This is a fair question, you are correct that with out the refactoring this is a bit more complex to accomplish.
We have a python client that we use in the integration tests, the client uses the web backend api instead of the direct grpc calls against the engine/replicas.

If you are familiar with python, that's probably the easiest approach for now.
There is a snapshot list endpoint that you can call for a currently attached volume.
https://github.com/longhorn/longhorn-manager/blob/master/api/snapshot.go#L47

Python client reference, more example in https://github.com/longhorn/longhorn-tests/tree/master/manager/integration
Reference: https://longhorn.io/docs/1.1.1/references/longhorn-client-python/

**Comment by jf647** [comment]
Thanks for clarifying.  I can work with the HTTP API just as easily.  I'll need to dust off the Python skills, but that shouldn't be too hard.  Or I might just write something quick and dirty in Go, as the lifetime of the tool will (hopefully) be limited.
