### ISSUE TITLE
[BUG] Impossible to delete a backup after direct file deletion

### ISSUE THREAD

**Issue by PPCM** [longhorn/longhorn#2612]
Describe the bug
After a maintenance issue (see #2536) some files have been deleted from ```backups``` folder, now it is impossible to remove the backup in UI and all deleted files are shown in UI with error (for exemple ```cannot find backupstore/volumes/de/4b/backup_backup-009bc093ff7b4af9.cfg/volume.cfg in backupstore```) and it is impossible to delete them

To Reproduce

Remove a file in ```backups``` folder of a backup
Wait one or two Poll Interval
Go back the UI, the deleted file is shown as an error and it is impossible to delete the backup
See log file in attachment for details
[backup.log](https://github.com/longhorn/longhorn/files/6520481/backup.log)

Environment:

Longhorn version: 1.1.1
Installation method: Longhorn Catalog in Rancher
Kubernetes distro: K3s v1.20.5+k3s1
Number of management node in the cluster: 3
Number of worker node in the cluster: 4
Node config
OS type and version: Ubuntu 64bits
CPU: ARM on Raspberry Pi 4B
Memory per node: 8Go
Disk type(e.g. SSD/NVMe): SSD
Network bandwidth between the nodes: 1Gb
Number of Longhorn volumes in the cluster: 7

**Comment by jenting** [comment]
Thank you. We'll reproduce in our side first to see how to improve it.

**Comment by PPCM** [comment]
I had to restart all my nodes of the cluster and the problem was resolved
Sorry, I can't give you more information. But now it works fine.

**Comment by cclhsu** [comment]
Great to hear that!  I will close the ticket for now.  Please update us with more information if the issue reoccurred.
