### ISSUE TITLE
[QUESTION]Longhorn csi plugin reports errors

### ISSUE THREAD

**Issue by Geek-sky** [longhorn/longhorn#2619]
**Question**
Longhorn csi plugin cyclically reports errors
**Environment:**
 - Longhorn version: v1.1.1
 - Kubernetes version: v1.20.7+k3s1
 - Node config
   - OS type and version ubuntu 20.04
   - CPU per node: master01=16C master02=16C  master03=16C 
   - Memory per node: master01= 32G ,  master02= 33G, master03= 64G
   - Disk type :master01 = ssd , master02 = sata, master03= sata
   - Network bandwidth and latency between the nodes:  master01 ->master02  2ms     master01 ->master03  0.545ms  master02 ->master01  2ms  master02 ->master03 1ms  master03 ->master01  0.553ms   master03 ->master02  2ms 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):  kvm 

**Additional context**
![image](https://user-images.githubusercontent.com/64129256/119321736-8d3fcf00-bcaf-11eb-9acb-ac578d07359a.png)
**root@k3s-master01:~# kubectl logs -n longhorn-system longhorn-csi-plugin-hgstc longhorn-csi-plugin**
2021/05/24 08:42:27 proto: duplicate proto type registered: VersionResponse
time="2021-05-24T08:42:27Z" level=info msg="CSI Driver: driver.longhorn.io csiVersion: 0.3.0, manager URL http://longhorn-backend:9500/v1"
time="2021-05-24T08:42:37Z" level=fatal msg="Error starting CSI manager: Failed to initialize Longhorn API client: Get \"http://longhorn-backend:9500/v1\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

**Comment by Geek-sky** [comment]
![image](https://user-images.githubusercontent.com/64129256/119322234-0808ea00-bcb0-11eb-9a3d-c70843440b09.png)

**Comment by Geek-sky** [comment]
I just saw a similar issue https://github.com/longhorn/longhorn/issues/1478 I think I have enough memory to run longhorn , can anyboby help me to resolv it?

**Comment by cclhsu** [comment]
Hi! Can you check if longhorn-manager is running on each node? Error message `exceed dateline` mean there are some issue to reach it.  Are others Longhorn process properly running? Can you also provide support-bundle?

**Comment by Geek-sky** [comment]
Hi , cclhsu , I am pretty sure  that other longhorn pod are all running and the status are healthy 
![image](https://user-images.githubusercontent.com/64129256/119431793-c9257380-bd45-11eb-93a2-7268904e6587.png)

**Comment by Geek-sky** [comment]
I just redeployed longhorn , seems that longhorn-ui pod has same problem too 

> Hi! Can you check if longhorn-manager is running on each node? Error message `exceed dateline` mean there are some issue to reach it. Are others Longhorn process properly running? Can you also provide support-bundle?

Hi , cclhsu , I am pretty sure that other longhorn pod are all running and the status are healthy

**Comment by cclhsu** [comment]
Please help us by creating an issue in https://github.com/longhorn/longhorn/issues and provide us with a support bundle either attach it to the ticket or send it to longhorn-support-bundle@rancher.com.  We will take a look! Thanks!
![image](https://user-images.githubusercontent.com/1287163/107722545-6ac90d80-6cdf-11eb-88b2-d4df7c4002a5.png)

**Comment by Geek-sky** [comment]
> Please help us by creating an issue in https://github.com/longhorn/longhorn/issues and provide us with a support bundle either attach it to the ticket or send it to [longhorn-support-bundle@rancher.com](mailto:longhorn-support-bundle@rancher.com). We will take a look! Thanks!
> ![image](https://user-images.githubusercontent.com/1287163/107722545-6ac90d80-6cdf-11eb-88b2-d4df7c4002a5.png)

Sorry to trouble you, I just re-deployed longhorn again, but this csi problem no longer appeared, and I didn't do anything during this period. The problem cannot be reproduced, I will raise the issue again when there is a problem next time . Thank you very much
