### ISSUE TITLE
[QUESTION] replica data is not cleaned up on a node

### ISSUE THREAD

**Issue by tulanian** [longhorn/longhorn#2620]
**Question**
I seem to have a lot of replicas that aren't referenced in the Longhorn GUI. e.g. the GUI lists zero replicas for a node, but I see eight subdirs under .../replicas, all with modtimes several weeks old. Is there a cleanup routine in Longhorn that's not running, or do I need to clean this up manually?

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes version: 1.17.17
 - Node config
   - OS type and version: CentOS 7.9
   - CPU per node: 96 cores
   - Memory per node: 756 GB
   - Disk type: SAN SSD
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Additional context**

**Comment by jenting** [comment]
No, there is a feature request issue #685 for this. If the node ever went offline for a long time, the replica data would not be clean up.
Currently, the only way is to manually delete it and we'll enhance it in the future.
