### ISSUE TITLE
[BUG] Unable to attach claimed volume - no error given

### ISSUE THREAD

**Issue by AlexGustafsson** [longhorn/longhorn#2625]
**Describe the bug**
When deploying a persistent volume, a persistent volume claim and a pod using the claim, everything works as expected. If the pod is stopped, the claim persists. In this stopped state, however, it's not possible to attach to the volume by using the UI. The option to attach is there, but it doesn't do anything. When the claim is removed, however, the attachment works as expected.

To me, this seems to be expected behavior. The bug here is that A: the attach option is available when it perhaps shouldn't be and B: there's no error, log or notification to show the user that this is a problem.

To solve, either disable the option to attach via the UI when a volume is claimed, or notify the user that it cannot be done. 

**To Reproduce**
1. Create a persistent volume, persistent volume claim and pod using the claim
2. Delete the pod
3. Via the UI, try to attach the volume to a node
4. See that nothing happens
5. Delete the persistent volume claim
6. Via the UI, try to attach the volume to a node
7. See that it works as expected

**Expected behavior**
Either the option to attach should not be given, or a notification should be shown to let the user know it's not possible to attach to a claimed volume.

**Environment:**
 - Longhorn version: v1.1.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: microk8s, v1.21

**Comment by AlexGustafsson** [comment]
If I've understood things correctly and this is indeed expected behavior, I'd like to ask a related question as well.

Postgres will not start in a directory which is not empty. If I deploy a volume and claim alongside Postgres, mkfs will leave the `lost+found` directory in the volume. One would think that by stopping the container, attaching the volume to a node and then cleaning it up prior to deploy the pod could work. But since it's not possible to attach a claimed volume, that seems like a no go. If I remove the claim to attach to the volume, I cannot reuse the volume. I suppose I could create a backup image of an empty volume and restore from it when I deploy Postgres. This, however, seems like a bit of a workaround. Another workaround would be running `rm -rf lost+found` before starting Postgres, but that seems as a bit of an hack as well.

What is the recommended approach here? I'd like to make the approach as code-defined as possible, meaning I'd rather not first create the volume and claim using the UI.

**Comment by cclhsu** [comment]
- Longhorn does not manage how application from workload write directory/file to storage.  For `lost+found` that create by file system, it should be able to manage in the deployment manifest lifecycle: pre/post.
- For PV to be reused after manually removed PVC, it is required to clean up ClaimRef of PV. Otherwise, the existing PV cannot be reused.
- For `PGDATA`, it needs to change deployment manifest to appropriate path where data is stored. e.g.,
```
          volumeMounts:
            - name: pgdata
              mountPath: /postgres
```

**Comment by cclhsu** [comment]
@AlexGustafsson Are you able to resolve the issue?  Perhaps we can close it the ticket?

**Comment by AlexGustafsson** [comment]
@cclhsu I’ll go ahead and close it. Thank you for the help.
