### ISSUE TITLE
[TASK] Update longhorn client to be compatible with newer client-go and code generation

### ISSUE THREAD

**Issue by areed** [longhorn/longhorn#2626]
**What's the task? Please describe.**
Regenerate the longhorn client to be compatible with recent versions of client-go.

It's not possible to import `github.com/longhorn/longhorn-manager/k8s/pkg/client/clientset/versioned/typed/longhorn/v1beta1` in a project using client-go 0.18+ because the longhorn generated client does not include context. There are numerous build errors like this:

```
k8s/pkg/client/clientset/versioned/typed/longhorn/v1beta1/backingimage.go:74:5: not enough arguments in call to c.client.Get().Namespace(c.ns).Resource("backingimages").Name(name).VersionedParams(&options, scheme.ParameterCodec).Do
        have ()
        want (context.Context)
```

This makes it difficult to interact with longhorn CRDs programmatically.

**Describe the items of the task (DoD, definition of done) you'd like.**
- [ ] Get latest binaries from https://github.com/kubernetes/code-generator/releases and run https://github.com/longhorn/longhorn-manager/blob/master/k8s/generate_code.sh

**Additional context**
Add any other context or screenshots about the task request here.

**Comment by joshimoo** [comment]
While working on this, we should update the code generation setup as well as clean it up a bit.

- We should update to a newer client-go version, now that our min supported kubernetes version is 1.16
- We should evaluate whether we want to move the Spec/Status definitions into the `k8s/pkg/apis/longhorn/v1beta1/` next to the rest of the definition of the CRD, this should allow for deep copy generation of the status/spec
- We need to benchmark the performance difference between the auto generated and hand crafted deepcopy implementations. 
- If a deepcopy implementation is present deepcopy-gen will skip auto generation for it.

This is a nice to have for v1.2 and probably a latest for v1.3

**Comment by jenting** [comment]
We have bump up the client-go to version `v0.18.19` along with Longhorn v1.2.0.

**Comment by PhanLe1010** [comment]
There are some tasks mentioned by @joshimoo [here](https://github.com/longhorn/longhorn/issues/2626#issuecomment-850255817) Should create a new issue to track them?

**Comment by jenting** [comment]
> There are some tasks mentioned by @joshimoo [here](https://github.com/longhorn/longhorn/issues/2626#issuecomment-850255817) Should create a new issue to track them?

I move them to #2637

**Comment by PhanLe1010** [comment]
Cool. Thank you!
