### ISSUE TITLE
[TASK] Add ability to run nightly regression nightly tests using customize baking image manager image 

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#2628]
**What's the task? Please describe.**
same as issue title 
**Describe the items of the task (DoD, definition of done) you'd like.**
- [ ] <use check box for each item>

**Additional context**
Add any other context or screenshots about the task request here.

**Comment by innobead** [comment]
@meldafrawi I think we should backport to longhorn-test/1.1.2?
