### ISSUE TITLE
[BUG] Fix missed deepcopy cases for Volume.Status.KubernetesStatus and EngineStatus.Snapshots.Snapshot

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2631]
While looking into #2629 I found some missed deepcopy cases:
- Fix deep copy for VolumeStatus not copying KubernetesStatus.WorkloadsStatus
- Fix deep copy for EngineStatus inner Snapshot maps (children, label)

**Comment by yasker** [comment]
Change the milestone to v1.2.0 with `backport-needed`, so we will backport the fix for v1.1.2.

**Comment by joshimoo** [comment]
Cannot be tested on the QA side, for previous code issues like this we used a dev approval cc @innobead
