### ISSUE TITLE
[BUG] Normalize pod order for v.status.KubernetesStatus updates

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2632]
I noticed, that the pod list is not normalized, since the iteration of this is used to populate the workloadStatus
Different syncs could lead to a different processing order and therefore different workloadStatus.
Which would then leads to unnecessary volume.Status updates.

You might have seen this on the longhorn UI before on an RWX volume where the pods in the LastAttachedBy keep changing position, even though the set of pods is stable.

**Comment by joshimoo** [comment]
Can be tested by using an RWX volume with 10 pods for example, then seeing the UI last attached by keep changing order.
Can also compare the ws/api output for a single RWX volume over time, and see the kubernetes status entries keep changing order. The above UI test is sufficient though :)

**Comment by khushboo-rancher** [comment]
Verified with Longhorn master-head and v1.1.2-head `06/07/2021`

Validation - **Pass**

The order of the attached pods appear correct and doesn't seem changing when the pods are stable.
