### ISSUE TITLE
[BUG] Fix AnnotateAWSIAMRoleArn modifying lister returned pod instances directly

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2633]
The AWS Iam sync code added for #1526 modifies the pods returned by the lister directly, cached objects should never be modified directly.
https://github.com/longhorn/longhorn-manager/blob/779149f6f3a8556abff08e12feec6ec0646c3831/datastore/longhorn.go#L247

**Comment by joshimoo** [comment]
Requires the same test that was done for the initial IAM implementation https://github.com/longhorn/longhorn/issues/1526

**Comment by khushboo-rancher** [comment]
Verified with Longhorn v1.1.2-head and v1.1.1, https://github.com/longhorn/longhorn/issues/1526 seems broken.

Validation - **Fail**

Reopening the original issue and will revalidate this once the original issue is fixed.
