### ISSUE TITLE
[FEATURE] Remove the VA cleanup feature. Better to use the pod deletion approach

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2635]
Since we have now implemented the pod deletion approach for statefulsets + remounts.
It's better if we utilize only one approach for failure handling of the volume, instead of having different code paths that might now also compete with each other.

As a result of that and an internally discussion we should remove the VA cleanup feature.

**Comment by innobead** [comment]
This is duplicated of https://github.com/longhorn/longhorn/issues/2060 we can tackle from there.
