### ISSUE TITLE
[REFACTOR] Remove the keyword register of deepcopy-gen

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#2637]
**What's the task? Please describe.**

According to https://www.openshift.com/blog/kubernetes-deep-dive-code-generation-customresources `GLOBAL TAGS` section

> Note: The register keyword in the value of the upper example will enable the registration of deepcopy methods into the scheme. This will completely go away in Kubernetes 1.9 because the scheme won’t be responsible anymore to do deepcopies of runtime.Objects. Instead just call yourobject.DeepCopy() or yourobject.DeepCopyObject(). You can and you should do that already today in 1.8-based projects as it is faster and less error-prone. Moreover, you will be prepared for 1.9 which will require this pattern.

Since the current Longhorn min supported Kubernetes is 1.16, so we could remove the keyword `register` in
- https://github.com/longhorn/longhorn-manager/blob/d901b23/k8s/pkg/apis/longhorn/v1beta1/doc.go#L1
- https://github.com/longhorn/longhorn-manager/blob/edc9374/upgrade_asset/v1alpha1/k8s/pkg/apis/longhorn/v1alpha1/doc.go#L1

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] Remove the keyword `register`
- [x] We should evaluate whether we want to move the Spec/Status definitions into the `k8s/pkg/apis/longhorn/v1beta1/` next to the rest of the definition of the CRD, this should allow for deep copy generation of the status/spec
- [x] We need to benchmark the performance difference between the auto generated and hand crafted deepcopy implementations. 
- [x] ~If a deepcopy implementation is present deepcopy-gen will skip auto generation for it.~

**Additional context**
Add any other context or screenshots about the task request here.

**Comment by joshimoo** [comment]
Related to #2626

**Comment by jenting** [comment]
> Related to #2626

Moving the rest of the items mentioned [here](https://github.com/longhorn/longhorn/issues/2626#issuecomment-850255817) to this issue.

**Comment by jenting** [comment]
> We need to benchmark the performance difference between the auto generated and hand crafted deepcopy implementations

I choose the most complicated struct [EngineStatus](https://github.com/longhorn/longhorn-manager/blob/v1.2.2/types/resource.go#L263-L280) which contains 8 maps and 2 sub-maps under struct [Snapshot](https://github.com/longhorn/longhorn-manager/blob/v1.2.2/types/resource.go#L282-L291).

The go benchmark test result, I put to my repo https://github.com/jenting/deepcopy-bench

Generally, the auto-generated performance is a bit worse than the hand-craft `DeepCopyInto` function.
One operation took for auto-generated is `18672 ns (0.018672 ms)` and the hand-craft is `17680 ns (0.01768 ms)`.

**Comment by jenting** [comment]
> > Probably we can't move to auto-gen now until we move the type `time.Time` to `metav1.Time` _or_ we should keep the manual way (but add a unit test to check the DeepCopy function works correctly #2634).
> 
> I'd like to go with #2634 to have a unit test to test the hand-craft DeepCopy function. WDYT? @joshimoo @shuo-wu

@yasker mentioned in today's meeting that probably we could consider changing the CRD data struct to match the Kubernetes convention.

**Comment by joshimoo** [comment]
I think we should go with meta.time as well, since it's whole purpose for existence is the correct marshaling :)
And it can be used more or less like a regular time.time since it's embedded.

I think I mentioned this as part of the backup refactor.
**Can you investigate & analyse the scope of the necessary changes?**

Potentially also consider changing some of the string time instances, to meta.time but we can make that decision after identify the scope of the changes.

**Comment by joshimoo** [comment]
Same testing procedure as in https://github.com/longhorn/longhorn/issues/2671#issuecomment-947922659
crud operations and e2e tests. Since this impacts all resources issues should become apparent rather quickly.

**Comment by khushboo-rancher** [comment]
Validation - **Pass**

The e2e test on ubuntu looks good https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/478/# and also performed some manual steps for crashing IM for volume and basic operations.
