### ISSUE TITLE
[BUG] Problem when draining node

### ISSUE THREAD

**Issue by LuizBuffa25** [longhorn/longhorn#2639]
**Describe the bug**
I was trying to upgrade my cluster with some configuration (using Rancher).
One of my nodes stuck on "Draining" status;
Log into machine and executed: $ kubectl drain node-name --ignore-daemonsets --force --grace-period=0 

And I receive this output:

evicting pod longhorn-system/instance-manager-r-20361032
evicting pod longhorn-system/instance-manager-e-f83af0e5
error when evicting pods/"instance-manager-r-20361032" -n "longhorn-system" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
error when evicting pods/"instance-manager-e-f83af0e5" -n "longhorn-system" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.

And the same output repeats over and over with a 5-secs delay.

**Expected behavior**
Drain the node successfully 

**Environment:**
 - Longhorn version: 1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher k8s 1.20.6

**Comment by m4r1u2** [comment]
We use Rancher v2.5.8, Longhorn v1.1.1 and [Kured](https://github.com/weaveworks/kured).
We face the same issue as @LuizBuffa25 describes above, and it holds nodes from draining (and kured to drain/reboot a node)

I can see from the [instance_manager_controller.go](https://github.com/longhorn/longhorn-manager/blob/master/controller/instance_manager_controller.go#L642) its hard-coded MinAvailable = 1. This is not a good idea if only one replicas is running on a node.

In our environment we end end up with disruptionsAllowed: 0

```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: "2021-05-24T04:09:26Z"
  generation: 1
  managedFields:
  - apiVersion: policy/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:currentHealthy: {}
        f:desiredHealthy: {}
        f:expectedPods: {}
        f:observedGeneration: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-05-24T04:09:26Z"
  - apiVersion: policy/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:minAvailable: {}
        f:selector: {}
    manager: longhorn-manager
    operation: Update
    time: "2021-05-24T04:09:26Z"
  name: instance-manager-e-c638a41c
  namespace: longhorn-system
  resourceVersion: "82672672"
  uid: 2ac482c5-1164-41d5-9bff-e7c3f27a7ece
spec:
  minAvailable: 1
  selector:
    matchLabels:
      longhorn.io/component: instance-manager
      longhorn.io/instance-manager-image: imi-c4c3ddb4
      longhorn.io/instance-manager-type: engine
      longhorn.io/managed-by: longhorn-manager
      longhorn.io/node: xxxxxx
status:
  currentHealthy: 1
  desiredHealthy: 1
  disruptionsAllowed: 0
  expectedPods: 1
  observedGeneration: 1
```

**Comment by cclhsu** [comment]
As described in document [Updating the Node OS or Container Runtime](https://longhorn.io/docs/1.1.1/volumes-and-nodes/maintenance/#updating-the-node-os-or-container-runtime), before drain a node, it needs to cordoned

```
Cordon the node. Longhorn will automatically disable the node scheduling when a Kubernetes node is cordoned.
``` 

Otherwise, draining the `instance-manager-r` and `instance-manager-e` will cause the error.

**Comment by m4r1u2** [comment]
In our case, the node was already cordoned by kured, but longhorn have not cleared the pdb for instance-manager-r on the same node.

Not sure if its relevant, but I see some errors in longhorn-manager-qhrp8
```
E0603 13:32:17.540220       1 engine_controller.go:693] failed to update status for engine pvc-bb3e52f4-9253-413d-a08a-70952e7cc673-e-dea18b14: failed to list replicas from controller 'pvc-bb3e52f4-9253-413d-a08a-70952e7cc673': Failed to execute: /var/lib/longhorn/engine-binaries/rancher-mirrored-longhornio-longhorn-engine-v1.1.1/longhorn [--url 10.42.11.239:10000 ls], output , stderr, time="2021-06-03T13:32:17Z" level=fatal msg="Error running ls command: failed to list replicas for volume 10.42.11.239:10000: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.42.11.239:10000: i/o timeout\""
, error exit status 1
time="2021-06-03T13:32:18Z" level=warning msg="Try to get requested log for pvc-a05fd0c6-01de-4597-852c-12f38a310a81-r-2358b5e9 on node xxx-worker1"
time="2021-06-03T13:32:18Z" level=warning msg="cannot get requested log for instance pvc-a05fd0c6-01de-4597-852c-12f38a310a81-r-2358b5e9 on node xxx-worker1, error instancemanager.longhorn.io \"\" not found"
time="2021-06-03T13:32:19Z" level=warning msg="Try to get requested log for pvc-a05fd0c6-01de-4597-852c-12f38a310a81-r-2358b5e9 on node xxx-worker1"
```

**Comment by cclhsu** [comment]
> In our case, the node was already cordoned by kured, but longhorn have not cleared the pdb for instance-manager-r on the same node.
> 
> Not sure if its relevant, but I see some errors in longhorn-manager-qhrp8
> 
> ```
> E0603 13:32:17.540220       1 engine_controller.go:693] failed to update status for engine pvc-bb3e52f4-9253-413d-a08a-70952e7cc673-e-dea18b14: failed to list replicas from controller 'pvc-bb3e52f4-9253-413d-a08a-70952e7cc673': Failed to execute: /var/lib/longhorn/engine-binaries/rancher-mirrored-longhornio-longhorn-engine-v1.1.1/longhorn [--url 10.42.11.239:10000 ls], output , stderr, time="2021-06-03T13:32:17Z" level=fatal msg="Error running ls command: failed to list replicas for volume 10.42.11.239:10000: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.42.11.239:10000: i/o timeout\""
> , error exit status 1
> time="2021-06-03T13:32:18Z" level=warning msg="Try to get requested log for pvc-a05fd0c6-01de-4597-852c-12f38a310a81-r-2358b5e9 on node xxx-worker1"
> time="2021-06-03T13:32:18Z" level=warning msg="cannot get requested log for instance pvc-a05fd0c6-01de-4597-852c-12f38a310a81-r-2358b5e9 on node xxx-worker1, error instancemanager.longhorn.io \"\" not found"
> time="2021-06-03T13:32:19Z" level=warning msg="Try to get requested log for pvc-a05fd0c6-01de-4597-852c-12f38a310a81-r-2358b5e9 on node xxx-worker1"
> ```

This error provides seems to relate to the issue https://github.com/longhorn/longhorn/issues/2648 which was recently resolved.  The error message should already there before draining.  I am not sure if this will lead to drain issue, since instance manager is not working properly before draining.

**Comment by cclhsu** [comment]
When encounter "Cannot evict pod as it would violate the pod's disruption budget", it is most likely due to that one of volume only healthy replica is on the node.

To Recover:

1. first uncordon the node: `kubectl uncordon`
2. make sure that volume replica is transferred to another node. If the volume replica number is one, need to increase volume replica number to 2, so replica is transferring is possible.
3. drain node `kubectl drain --force --ignore-daemonsets --delete-emptydir-data --grace-period=10 ${NODE}`

**Comment by m4r1u2** [comment]
Thanks for clarification. I think some underlying issues in our cluster made the longhorn release not work after the cordon process was made by kured. I think the issue can be closed from our point of view.

**Comment by cclhsu** [comment]
Thanks. I will close the issue.  Feel free to reopen the issue if you have further questions.

**Comment by jenting** [comment]
Related to #2673
