### ISSUE TITLE
[BUG] Longhorn faills to provisoin on microk8s 1.21

### ISSUE THREAD

**Issue by Larry1123** [longhorn/longhorn#2645]
**Describe the bug**
Longhorn fails to provision.

**To Reproduce**
I'm starting with a fresh Ubuntu 20.04 install on an OVH ADVANCE-2 Bare Metal Server.
```
sudo apt update
sudo apt upgrade
sudo apt install htop ncdu jq atop vlan nfs-common
sudo snap install microk8s --classic --channel=1.21
sudo usermod -a -G microk8s ubuntu
# reconnect to server
sudo snap install kubectl --classic
mkdir .kube
microk8s config > ./.kube/config

microk8s enable dns
microk8s enable storage
microk8s enable dashboard

kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.1.1/deploy/longhorn.yaml
```
`longhorn-driver-deployer ` sits just spamming waiting in it's init
I did not have a lot of time to dig into all of the longs at the time but the one failing pod I did look at was referencing k3s.

**Expected behavior**
Longhorn installs as expected

**Log**
If I have time I will set this up again and get what logs I can however I did not have the time to do that just yet.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.
No support bundle could be made as longhorn UI is not starting.

**Environment:**
 - Longhorn version: 1.1.x (tested both 1.1.0 and 1.1.1)
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: [Microk8s](https://microk8s.io/)
   - Number of management node in the cluster: 2 (all nodes act as both)
   - Number of worker node in the cluster: 2 (all nodes act as both)
 - Node config
   - OS type and version: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-73-generic x86_64)
   - CPU per node: 6c/12t
   - Memory per node: 32 GB
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 100 mb/s (but it has seen seen to go reach 1-2 gb/s)
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 0

**Additional context**
I was running well on the same hardware and OS with microk8s 1.20 until the datastore master node suffered an unknown error that corrupted the dqlite storage and lead to longhorn crash looping. microk8s 1.21 includes "Major stability and performance dqlite fixes" which is why I was attempting to upgrade to 1.21 however it seems that longhorn thinks that is running on an k3s cluster when it is not and fails to provision.

I would be willing to provider more info once I have a working cluster again. 
As far as I know no special handing should be needed for longhorn to run on microk8s as it supports all features of upstream k8s if that is not the case it would likely be a bug on microk8s side.
microk8s with 1.21 now uses a single binary for all Kubernetes services which may be why longhorn showing up with k3s (idk atm it's nearly 4am)

**Comment by c3y1huang** [comment]
Can you try to deploy again with [KUBELET_ROOT_DIR](https://github.com/longhorn/longhorn/blob/v1.1.1/deploy/longhorn.yaml#L900-L901) uncomment and set to `/var/snap/microk8s/common/var/lib/kubelet`?

**Comment by quasarchimaere** [comment]
could it be possible that your replica count exceeds the amount of (worker)nodes available?

**Comment by Larry1123** [comment]
> could it be possible that your replica count exceeds the amount of (worker)nodes available?

It is not even starting the longhorn services so no volumes or replicas are even attempted.
It worked on the same node count with a storage class set to two replica before on micrkok8s 1.20 so I'm quite sure that this would not be an issue once it it does install right.



> Have you tried deploy Longhorn with [KUBELET_ROOT_DIR](https://github.com/longhorn/longhorn/blob/v1.1.1/deploy/longhorn.yaml#L900-L901) uncomment and set to `/var/snap/microk8s/common/var/lib/kubelet`?

I will test this once I can.

**Comment by Larry1123** [comment]
> Have you tried deploy Longhorn with [KUBELET_ROOT_DIR](https://github.com/longhorn/longhorn/blob/v1.1.1/deploy/longhorn.yaml#L900-L901) uncomment and set to `/var/snap/microk8s/common/var/lib/kubelet`?

I have been able to confirm that this does infact work. the install docs don't go over the extra configs too well. Wish I had time to better understand longhorn's workings.

**Comment by jenting** [comment]
I think it's resolved, close it.
