### ISSUE TITLE
[BUG] List order caused full data transfer when no resource updated.

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2646]
**Describe the bug**
The order of the list caused the volume data to be different, this costed the data transfer when there are no resource updates.

![Screenshot-2021-05-31-16:26:09](https://user-images.githubusercontent.com/22583541/120166505-38600380-c22f-11eb-944b-4242b4381558.png)

**To Reproduce**
1. Create PVC and Pod.
2. Inspect Network and payload with browser inspect tool.

**Expected behavior**
Data in payload should mostly be an empty list. 
```
{"data":[],"links":{"self":"http://54.151.190.215:30864/v1/ws/1s/volumes"},"type":"collection"}
```

**Log**
`n/a`

**Environment:**
`n/a`

**Additional context**
https://github.com/longhorn/longhorn/issues/2372

**Comment by khushboo-rancher** [comment]
Validated with Longhorn v1.1.2-head and master-head `06/01/2021`

Validation - **Pass**

The full data over WS is not observed every 30 seconds.
