### ISSUE TITLE
[BUG] Change storage size to use quantity instead of int64

### ISSUE THREAD

**Issue by cclhsu** [longhorn/longhorn#2648]
**Describe the bug**
Should consider change size to use Kubernetes Quantity or block size check.  Otherwise, the current implementation will incorrectly compare '2G' and '2Gi' as equal.
 
**To Reproduce**
1. Apply Command:
```
PVC=test
kubectl patch -p '{"spec":{"resources": {"requests": {"storage": "2G"}}}}' persistentvolumeclaim ${PVC}
```

2. Since patch is not a block size of 4Kb, this will cause error.

```
E0603 04:22:49.047869       1 engine_controller.go:693] failed to update status for engine test-e-821ce098: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn [--url 10.42.0.10:10000 backup restore-status], output , stderr, time="2021-06-03T04:22:49Z" level=fatal msg="Error running restore backup command: failed to list replicas for volume 10.42.0.10:10000: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.42.0.10:10000: connect: connection refused\""
, error exit status 1
time="2021-06-03T04:22:49Z" level=info msg="All replicas are failed, set engine salvageRequested to true" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=centos-master-0 owner=centos-master-0 state=detaching volume=test
```

3. Apply command
```
PVC=test
kubectl patch -p '{"spec":{"resources": {"requests": {"storage": "2Gi"}}}}' persistentvolumeclaim ${PVC}
```

```
time="2021-06-03T03:58:15Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"test\", UID:\"61670bda-95df-4aee-b8b0-28651fbc2f5f\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"7961\", FieldPath:\"\"}): type: 'Normal' reason: 'SucceededExpansion' Succeeds to expand the volume test to size 2000000000, will automatically detach it if it's not DR volume"
time="2021-06-03T03:58:19Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"test-e-bab1fe3e\", UID:\"57a15169-0890-4dbd-9b93-249e893da80e\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"7962\", FieldPath:\"\"}): type: 'Warning' reason: 'Faulted' Detected replica test-r-081e6bf3 (10.42.4.7:10000) in error"
time="2021-06-03T03:58:19Z" level=info msg="All replicas are failed, set engine salvageRequested to true" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=centos-worker-2 owner=centos-worker-2 state=attached volume=test
```

**Expected behavior**
expect size will increase from 2000000000 to 2147483648

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: v.1.1.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Additional context**
Currently, when this happens, the user needs to increase size to 3Gi to return normal state.

**Comment by PhanLe1010** [comment]
I notice that Longhorn stuck in the expanding loop whenever the user changes PVC size in the format `nG`. From a quick look at the code, I am not sure why yet. Need more investigation.

**Comment by cclhsu** [comment]
Seem related to https://github.com/longhorn/longhorn-manager/blob/master/csi/controller_server.go#L675.  Will fix with https://github.com/longhorn/longhorn-manager/pull/888 by remove `equestedSize > existingSize`.

**Comment by cclhsu** [comment]
Issue resolved along with https://github.com/longhorn/longhorn-manager/pull/888
