### ISSUE TITLE
[IMPROVEMENT] Change the lifecycle management of the instance-manager pods.

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2650]
**Is your feature request related to a problem? Please describe.**
Currently when kubelet on a node is restarted, the node will be marked as not ready.
This will lead to us terminating the instance-manager pods.

**Describe the solution you'd like**
- Consider whether we can let kubernetes manage the lifecycle of the pods, via toleration seconds (i.e. specify X seconds of toleration for NodeNotReady)

- Consider relying on the ability of network communication with the existing instance-manager pods, since if we can still communicate with them via GRPC, there shouldn't be a need to terminate them.

**Additional context**
https://github.com/longhorn/longhorn/issues/2629
https://rancher.slack.com/archives/CJ4GPBTLG/p1622228939069400?thread_ts=1622225195.053900&cid=CJ4GPBTLG

**Comment by shuo-wu** [comment]
As I mentioned in the slack discussion, Longhorn does not need to actively delete the instance manager pods when a node is NotReady. Instead, Kubernetes will determine it via [pod-eviction-timeout](https://kubernetes.io/docs/concepts/architecture/nodes/#condition). 

If the node is back soon (eviction timeout is not reached) and the instance manager pods on the node are not actually down, Longhorn can simply mark the related instance manager CR state from `unknown` to `running` without restarting the pods.

If the node is not ready for a while and the pod eviction is triggered, relying on the connection with the pod doesn't make sense. In this case, when the node is back to ready, the pods are eventually restarted by Kubernetes and there is no way to avoid it.

**Comment by joshimoo** [comment]
This Is also part of the solution for https://github.com/longhorn/longhorn/issues/2629
To ensure that volumes remain available during kubelet restarts.

**Comment by joshimoo** [comment]
This cannot be done for v1.1.2 I updated the estimate to 5 since there is many parts involved.
That currently rely on node isReady status for evaluation of node down.

Some things that come to mind:
- ownership handling of resources
- im determination of status (cleanup)
- instance determination
- engine image (potentially)

**Comment by joshimoo** [comment]
I updated the estimate to the next bigger number 10, since there are a lot of components and logic that relies on Node Ready status as a determination. So additional time is required to investigate/analyse and change the behavior.

**Comment by innobead** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Main-Board-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/2650?planning-poker) with ZenHub @jenting @PhanLe1010 @shuo-wu @joshimoo

**Comment by MrDienns** [comment]
Hi all,

Good to see an issue being created for this. I see this was initially scheduled for v1.2.0, so it's honestly a bit disappointing to see this being pushed back to v1.3.0. Is there any way we can get this as a fix on v1.2.x instead? I've experienced numerous production outages, for example because we had to update our network plugin (see https://github.com/cilium/cilium/issues/16669), had to update k3s or just a small connectivity loss between nodes as part of a host outage. We experience these issues being amplified by longhorn, as because of the restart, replication repairs on almost all volumes will occur and this will cause us to not be able to attach those volumes yet (with best-effort at least).

If the above concerns could be addressed through some setting tweaks, I would love to try those. But could this not be seen as a bug instead of a feature? Zero downtime production maintenance is currently not possible because of this.

**Comment by innobead** [comment]
@MrDienns this will be backported to 1.2.x.

**Comment by shuo-wu** [comment]
Test plan:

| Case | Result |
| :---- | :----: |
| kubelet restart([doc](https://github.com/longhorn/longhorn-tests/blob/master/docs/content/manual/pre-release/node/kubelet-restart-on-a-node.md)) | the same as the result described in the updated doc |
| node disconnection([doc](https://github.com/longhorn/longhorn-tests/blob/master/docs/content/manual/pre-release/node/node-disconnection.md)) | the same as the result described in the updated doc |
| node reboot | instance manager will be restarted after the node back and ready |

**Comment by innobead** [comment]
@shuo-wu let’s backport to 1.2.4 n 1.1.4.

**Comment by kaxing** [comment]
Validating in progress.

Testing simple workload: pod with pvc, nginx statefulset example,
with the following scenarios on master-head images(and  v1.21.8+rke2r2):
- Restart the kublet agent service
- Stop the kublet agent service
  - Start the kubelet agent from failed status
- Reboot the worker node instance
- Shutdown the worker node instance
  - Start worker node instance from stopped state

When kubelet down more than 5mins instance manager pods will recreate the container, and posting Warning with following example, and meanwhile all the volume will remain attached with degraded state if resources are on down nodes,
```
Events:
  Type     Reason        Age                  From             Message
  ----     ------        ----                 ----             -------
  Normal   Pulled        17m                  kubelet          Container image "longhornio/longhorn-instance-manager:v1_20210731" already present on machine
  Normal   Created       17m                  kubelet          Created container engine-manager
  Normal   Started       17m                  kubelet          Started container engine-manager
  Warning  NodeNotReady  6m21s (x2 over 13m)  node-controller  Node is not ready

```

**Comment by kaxing** [comment]
Validating progress update:

Adding 2 different tests into the same set of scenarios in my previous comment:
- rwx volume
- volume expanding

Also include 2 more scenarios:
- Reboot all worker nodes at once
- 1-Node disconnection

Observation:
- All working volumes remain attached but in degraded status and will be recovering back to healthy state once the nodes return online.
- Instance-manager pods will remain with a "NodeNotReady" warning until the 5mins tolerance.

One thing requires an extended test:
After multiple runs of rebooting and restarting kubelet service, the rwx share-manager pod stuck in pending and failed to bring up the container, initial look doesn't have any useful findings.

**Comment by kaxing** [comment]
For the doubt on sharing-manager pod, I created an issue for tracking: #3612

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with master-head images on 1+3 nodes rke2 cluster with following scenarios:
- 1-kubelet restart
  - All-worker kubelet restart
- Worker node power down
  - All-worker node power down
- Worker node network down test
- Delete all IM pods at once
- With RWX volume
- When Volume Expanding

Please reference details from comments above.
