### ISSUE TITLE
[BUG] UI multiple selections should be released after performing action on the backup page

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2652]
**Describe the bug**
The multiple selections should get released after the action completion on the backup list page

**To Reproduce**
1. Go to the backup page on the Longhorn UI
2. Select multiple backups and perform any action like restoring backup
3. The selections don't get released after the action is completed.
<img width="1748" alt="Screen Shot 2021-06-02 at 3 06 13 PM" src="https://user-images.githubusercontent.com/60111667/120558573-87837100-c3b4-11eb-839c-ac80d02ee68a.png">

**Expected behavior**
The selections should be released after the action completion.

**Environment:**
 - Longhorn version: v1.1.1

**Additional context**
https://github.com/longhorn/longhorn/issues/2595

**Comment by kaxing** [comment]
Checking with **v1.1.2-head(b790278)** image, now the selection will be cleanup after action finished.
![longhorn-backup-restore-selection-cleanup-v1 1 2-head](https://user-images.githubusercontent.com/602540/121152554-e2670d80-c877-11eb-8422-377552d80a15.gif)

**Comment by khushboo-rancher** [comment]
@kaxing Can you please do a quick check of this on the master as well, then close the issue if everything works fine.

**Comment by kaxing** [comment]
Verified on longhorn master image: 556db1285e54 (2010-06-09), with longhorn/longhorn-ui@136e787 

The behavior is as expect.
