### ISSUE TITLE
[BUG] Longhorn document is pointing to the wrong version of CSI snapshot CRDs

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2653]
**Describe the bug**
Longhorn is using Snapshot Beta CRDs but the [Longhorn document](https://longhorn.io/docs/1.1.1/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/) is pointing to the GA version. 

**Expected behavior**
 The document should point to the Snapshot Beta CRDs 

**Additional context**
backport is needed for Longhorn v1.1.0

**Comment by khushboo-rancher** [comment]
Verified the Longhorn docs https://longhorn.io/docs/1.1.1/ and https://longhorn.io/docs/1.1.0/ have the changes.

The doc is now pointing towards the below links
* https://github.com/kubernetes-csi/external-snapshotter/tree/release-4.0/client/config/crd
* https://github.com/kubernetes-csi/external-snapshotter/tree/release-4.0/deploy/kubernetes/snapshot-controller
