### ISSUE TITLE
[TASK] Remove Setting Volume Attachment Recovery Policy

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2661]
After removing the VA cleanup feature
https://github.com/longhorn/longhorn/issues/2060

We no longer act on the setting so it can be removed
https://github.com/longhorn/longhorn-manager/pull/911

Currently it's not so easy to remove a preexisting setting.
So we should look into this for v1.2

**Comment by innobead** [comment]
Already fixed in 1.1.2 #2060
