### ISSUE TITLE
[BUG] Cannot use NFS with NFS server supporting nfsvers 4 only

### ISSUE THREAD

**Issue by oliverdawid** [longhorn/longhorn#2662]
**Describe the bug**
Using an Huawei OcenStor storage providing NFS volumes, we are not able to use it as a backup volume - see log below. I am able to mount the NFS volume by hand though within the Debian machine as well as within the manager container using "-o nfsvers=4"

We can use /etc/nfsmount.conf to set this option but it there is no config in longhorn-manager pods. I tried to set this file in Engine- and Manager-Containers but neither worked (seems like backup is done in a different pod or does not read /etc/nfsmount.conf)

$ cat /etc/nfsmount.conf 
[NFSMount_Global_Options]
nfsvers=4

**To Reproduce**
1. Add NFS path to Backup Target configuration. In our case: nfs://172.19.50.250:/backup
2. Click on Menu - Backup
3. An error occurs telling that mounting NFS volume failed (see below)

This only works with a NFS server supporting vers4 only. Could not figure out though how to tweak linux NFS server to reproduce without Huawei OceanStor

**Expected behavior**
Get access to backup volume

**Log**
error listing backups: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.1/longhorn [backup ls --volume-only nfs://172.19.50.250:/backup], output Cannot mount nfs 172.19.50.250:/backup: nfsv4 mount failed but nfsv3 mount succeeded, may be due to server only supporting nfsv3: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 172.19.50.250:/backup /var/lib/longhorn-backupstore-mounts/172_19_50_250/backup], output mount.nfs4: access denied by server while mounting 172.19.50.250:/backup , error exit status 32 , stderr, time="2021-06-03T06:58:16Z" level=error msg="Cannot mount nfs 172.19.50.250:/backup: nfsv4 mount failed but nfsv3 mount succeeded, may be due to server only supporting nfsv3: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 172.19.50.250:/backup /var/lib/longhorn-backupstore-mounts/172_19_50_250/backup], output mount.nfs4: access denied by server while mounting 172.19.50.250:/backup\n, error exit status 32" , error exit status 1

**Environment:**
 - Longhorn version: 1.1.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 1.20.7
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Debian Version 10.9
   - CPU per node: 8
   - Memory per node: 16GB
   - Disk type(e.g. SSD/NVMe): iSCSI
   - Network bandwidth between the nodes: 10GB
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: ~10

**Comment by joshimoo** [comment]
related https://github.com/longhorn/longhorn/issues/2438#issuecomment-812011216

**Comment by jenting** [comment]
Let's discuss it in the GitHub issue to help track it.

Let me recap first.
@oliverdawid  you mean the Longhorn-manager Pod is able to mount the NFS server with the setting `nfsvers=4`?

**Comment by oliverdawid** [comment]
Yes correct.

**Comment by joshimoo** [comment]
@jenting the issue comes from here, please have a look it's simple to fix:
https://github.com/longhorn/longhorn/issues/2438#issuecomment-812011216

**Comment by oliverdawid** [comment]
> @jenting the issue comes from here, please have a look it's simple to fix:
> 
> https://github.com/longhorn/longhorn/issues/2438#issuecomment-812011216

Simple to fix for the developer or for the user? IMHO as I am not able to set any option, this needs to be fixed within code.

**Comment by jenting** [comment]
for the developer 😉

**Comment by jenting** [comment]
Use #2438 to track it, close this one.

**Comment by oliverdawid** [comment]
I wonder if you also consider testing with a server which only supports lower nfs versions as this is the case in #2438

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: JenTing Hsiao ***@***.***>
Gesendet: Wednesday, November 17, 2021 7:41:37 AM
An: longhorn/longhorn ***@***.***>
Cc: Oliver Dawid ***@***.***>; Mention ***@***.***>
Betreff: Re: [longhorn/longhorn] [BUG] Cannot use NFS with NFS server supporting nfsvers 4 only (#2662)


Closed #2662<https://github.com/longhorn/longhorn/issues/2662>.

**Comment by jenting** [comment]
@oliverdawid you could check the test result https://github.com/longhorn/longhorn/issues/2438#issuecomment-970077110
If anything missing, feel free to tell us, thank u.
