### ISSUE TITLE
[BUG] Infinite "Attaching" Issue

### ISSUE THREAD

**Issue by davDevOps** [longhorn/longhorn#2663]
[Description]
Cannot make a single claim against any workload I try to spin up.  Not once have I been successful at getting Longhorn to do anything.

**To Reproduce**
Install Docker
Install Rancher
Install Longhorn
Configure Nodes with a /mnt/dataset , hosted over NFS on a TrueNAS Server.

**Expected behavior**
A Persistent Volume is suppose to be attached.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.1.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):  Rancher
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 1.20.6
   - Number of management node in the cluster: 5
   - Number of worker node in the cluster: 5
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 4
   - Memory per node:  4GB
   - Disk type(e.g. SSD/NVMe):  SSD for OS (HDD over NFS for /mnt/dataset points)
   - Network bandwidth between the nodes: 1GB
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):  Proxmox / Truenas
 - Number of Longhorn volumes in the cluster: 0

**Additional context**

**Comment by davDevOps** [comment]
[longhorn-support-bundle_86e816d7-5ac7-4dec-9b0a-11d28f6e4894_2021-06-08T19-31-10Z.zip](https://github.com/longhorn/longhorn/files/6619123/longhorn-support-bundle_86e816d7-5ac7-4dec-9b0a-11d28f6e4894_2021-06-08T19-31-10Z.zip)

**Comment by cclhsu** [comment]
- From the log, it seems like the cluster is a mix of Windows and Linux nodes.  Please follow the guide [Rancher Windows Cluster](https://longhorn.io/docs/1.1.1/advanced-resources/deploy/rancher_windows_cluster/) to taint the nodes.  
- For Ubuntu nodes, please also check if [Installation Requirements](https://longhorn.io/docs/1.1.1/deploy/install/) is fulfilled.  From node, I do not see any message `go-iscsi-helper: tgtd is already running`.  I suspect that ISCSI is not installed.

**Comment by cclhsu** [comment]
hi! Are you able to resolve the issue?  Perhaps provides us with some updates?

**Comment by jenting** [comment]
Please check your environment meets the installation requirements.

Since this issue is out of activity, I'll close the issue.
Feel free to reopen it if you have further questions.
