### ISSUE TITLE
[QUESTION] share manager pod automatically restarts every 90 seconds when kill all the replicas 

### ISSUE THREAD

**Issue by haley05-cloud** [longhorn/longhorn#2670]
**Question**
Hi， 
I'm doing a breakdown test, and the test steps are as follows
1. download https://github.com/longhorn/longhorn/blob/master/examples/rwx/rwx-nginx-deployment.yaml
2. change replicas to 1
3. kubectl apply -f rwx-nginx-deployment.yaml 
4. Then exec:  docker exec -ti  instance-manager-r-XXX ， kill all the replicas of the volume which used by rwx-nginx

Expect result ： rwx-nginx/share manager pod only restart once 
Actual result： share manager pod automatically restarts every 90 seconds when kill all the replicas 。This phenomenon will take a long time to be normal。
   Sometimes will take one or more than one hour。 

Why the share manager pod/rwx-nginx pod restart many times ? Is it normal ?

**Environment:**
 - Longhorn version: v1.1.1
 - Kubernetes version: v1.17.9
 - Node config
   - OS type and version  Centos7.2  core: 4.18
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**

**Comment by shuo-wu** [comment]
There was the similar report: https://github.com/longhorn/longhorn/issues/2015#issuecomment-761623687

**Comment by haley05-cloud** [comment]
Thanks。
BTW,  may be this caused by the time is different between the two nodes 。
I cannot reproduce it after synchronized the time of the two nodes。

**Comment by jenting** [comment]
> Thanks。
> BTW, may be this caused by the time is different between the two nodes 。
> I cannot reproduce it after synchronized the time of the two nodes。

So after you enable the NTP sync, the issue no longer existed?

**Comment by haley05-cloud** [comment]
Yes。
And the pod restart interval is the same as the time difference between the two nodes。

**Comment by jenting** [comment]
Thank you, interested. cc @joshimoo

**Comment by joshimoo** [comment]
Independent from longhorn on a kubernetes cluster it's expected that the node times are more or less in sync.
So you should run ntp on each node, otherwise you going to end up with funky network issues as well :)

**Comment by jenting** [comment]
I think we can't further improve it on the Longhorn side, close it.
