### ISSUE TITLE
[BUG] List order caused full backup image data transfer when no resource updated.

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2672]
**Describe the bug**
Similar to https://github.com/longhorn/longhorn/issues/2646.

**To Reproduce**
1. Create 10 Backup Images.
2. Inspect Network and payload with browser inspect tool.

**Expected behavior**
Should not have data sent over WS if no update.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

**Environment:**
`n/a`

**Additional context**
https://github.com/longhorn/longhorn/issues/2372

**Comment by kaxing** [comment]
Validation - **Passed**

Verified with v1.1.2-head(0616) images, with more than 10+ backup imaging.
While the image is being downloading the `backignimages` connection will constantly gets update, once it's done there is no WS data flow observed.

**Comment by khushboo-rancher** [comment]
This is was reopened by mistake. Closed it now.
