### ISSUE TITLE
[TASK] Fix Longhorn CSI images with CVE issues

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#2675]
**What's the task? Please describe.**

Update the longhorn CSI images to fix the vulnerability issues (ref: https://github.com/rancherlabs/image-scanning/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+%22longhornio-csi%22)

**Describe the items of the task (DoD, definition of done) you'd like.**

- [x] update the longhorn CSI images w/ the same tag + updated digest
- [ ] run the integrity check or sanity check to see no regression 

**Additional context**
Add any other context or screenshots about the task request here.

cc @meldafrawi @khushboo-rancher @kaxing

**Comment by innobead** [comment]
@meldafrawi reminder: please remember to change the status of the pipeline when you are working on the items. Thanks!

**Comment by joshimoo** [comment]
We should consider doing the CSI component update for 1.2
That way we can move to kubernetes min v >= 1.17
https://github.com/longhorn/longhorn/issues/2388

**Comment by innobead** [comment]
1.1.2 released w/ updated CSI images.
