### ISSUE TITLE
[TASK] [UI] Implement Replica Auto Balance Settings

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2676]
**What's the task? Please describe.**
Support Replica Auto Balance feature.

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] In `Setting/General` page:
      Add `Replica Auto Balance` for `replicaAutoBalance`, and have the [setting definition](https://github.com/longhorn/longhorn-manager/blob/master/types/setting.go#L325-L329) for the option, there should be:
     - disabled (default)
     - least-effort
     - best-effort
- [x] In volume - `CreateVolume` form:
      Add `Replica Auto Balance` for `replicaAutoBalance`, and have [**`ignored` +** the setting definition](https://github.com/longhorn/longhorn-manager/blob/master/types/resource.go#L34-L37) for the option, there should be:
     - ignored (default)
     - disabled
     - least-effort
     - best-effort
- [x] In each volume - `VolumeDetails`: 
     - show selectedVolume.replicaAutoBalance setting.
- [x] In each volume `action dropdown`:
     - add action to update replicaAutoBalance options . The API to update the replicaAutoBalance is /v1/volumes/<VOLUME_NAME>?action=updateReplicaAutoBalance. This API expects the request's body to have the form {updateReplicaAutoBalance:<`ignored`/`disabled`/`least-effort`/`best-effort`>}.

**Additional context**
https://github.com/longhorn/longhorn/issues/587

**Comment by khushboo-rancher** [comment]
I believe this is validated with https://github.com/longhorn/longhorn/issues/587.
@kaxing Can please confirm and close this.

**Comment by kaxing** [comment]
Validation - **Passed**

@khushboo-rancher yes, they are, thank you!

Attaching screenshots for the reference:

- Settings > General > Replica Auto Balance section: ![image](https://user-images.githubusercontent.com/602540/126780678-a17470ad-be5d-48a1-b4d0-f5dc5e4bec10.png)

- Volumes > Create Volume > Field: Replica Auto Balance: ![image](https://user-images.githubusercontent.com/602540/126780801-66287718-83dc-4d10-b042-4cf9ff0cb576.png)

- Click into volume detail > On left pane: 
![image](https://user-images.githubusercontent.com/602540/126781225-bc564ca0-d5c3-41fc-81a8-a44c5c186f0e.png)

- Click into volume detail > top-right dropdown menu: 
![image](https://user-images.githubusercontent.com/602540/126781201-6c07fb66-c4f3-4e51-8c5a-5c328e3985a2.png)

- Volumes > Batch Update dropdown menu: 
![image](https://user-images.githubusercontent.com/602540/126781360-002d907e-565e-4758-a76c-d36856f90738.png)
  - and the option pop-up: 
![image](https://user-images.githubusercontent.com/602540/126781405-fcf89b45-0605-4fac-b57b-67b3b77ffe77.png)

**Comment by joshimoo** [comment]
@kaxing good idea adding the screenshots, it helps when referencing back to this issue in the future.
