### ISSUE TITLE
[BUG] liveness probe failed always occurs

### ISSUE THREAD

**Issue by vincetai** [longhorn/longhorn#2678]
Hi,

I found "liveness probe failed" always occurs w/ the instance managers & "readiness probe failed" w/ the engine images.

environment: rancher v3
longhorn 1.1.1
esxi dvswitch mtu = 9000
network: canal

things done so far: -
apt-get update
apt-get upgrade
moved to a faster vmware datastore
the situation improved, otherwise the pods of longhorn would rebuild even more frequently.
tried to modify the mtu from 1500 to 9000, the result was even worse, so i changed back.
however, my underlying mtu should be 9000.
tried to reserve more cpu & memory for longhorn namespace on rancher, it didn't help much.
i found there are io errors on the rancher's nodes intermittently.

![image](https://user-images.githubusercontent.com/70743517/121791504-f9618300-cc1c-11eb-9728-1a64901ccc30.png)

thanks so much

VT
[longhorn-support-bundle_cfe98578-0d31-44e1-88fa-7657b52c61d0_2021-06-12T06-44-41Z.zip](https://github.com/longhorn/longhorn/files/6641788/longhorn-support-bundle_cfe98578-0d31-44e1-88fa-7657b52c61d0_2021-06-12T06-44-41Z.zip)

**Comment by joshimoo** [comment]
potentially related https://github.com/longhorn/longhorn/issues/2699

**Comment by jenting** [comment]
Since you're using Kubernetes v1.20.6, and we known there is an issue at Kubenretes 1.20+ with Longhorn #2699.
We'll fix this soon.

**Comment by joshimoo** [comment]
@innobead This should be covered by the fixes for #2699
