### ISSUE TITLE
[QUESTION] Is that exist a API Document ?

### ISSUE THREAD

**Issue by sinoon** [longhorn/longhorn#2679]
I want to use api to create backup and create pvc from a backup.But I only find a Python Client without any HTTP api document.So I want to know is that exist a API Document ?

**Comment by joshimoo** [comment]
@sinoon consider scripting around the kubernetes csi snapshot process.
Here is an example from one of our users. https://community.intersystems.com/post/amazon-eks-and-iris-high-availability-and-backup

This way you also have application consistent backups.
