### ISSUE TITLE
[QUESTION] Node is listed as unschedulable

### ISSUE THREAD

**Issue by jehof** [longhorn/longhorn#2682]
**Question**
We need to understand why our node 4 is listed as unschedulable. We are turning our head up and down. But we do not find a solution.

The node was listed as unschedulable before and we changed the configuration value of StorageMinimalAvailablePercentage from 30% to 10% expecting that the node will be schedulable again. But it is still listed as unschedulable.

I have added a screenshot with more details of the node and disk

Disk Size is 245 Gi
Allocated Size (Scheduled) is 249 Gi
Storage Available is 100 Gi
Used is 145,06 Gi
Storage Over Provisioning Percentage is set to 150%

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes version: 1.19.10
 - Node config
   - OS type and version Ubuntu 20.04
   - CPU per node: 8
   - Memory per node: 32GB
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**
![Screenshot from 2021-06-14 14-06-02](https://user-images.githubusercontent.com/1583129/121889743-e4b6e500-cd19-11eb-8ab7-26c5b256e47a.png)

**Comment by jenting** [comment]
If I remember correctly, you could move the mouse on the `!`, there should be a tip to describe why it's not schedulable.
Or you could get the nodes CR, it will show the reason. `kubectl get nodes.longhorn.io <node-name> -o yaml`
Related code https://github.com/longhorn/longhorn-manager/blob/f76bacb/controller/node_controller.go#L787-L792

**Comment by jenting** [comment]
You can also reference the GitHub discussion https://github.com/longhorn/longhorn/discussions/2685

**Comment by jehof** [comment]
The informational message why its not schedulable was 

> Last Transition Time: 2 hours ago
> Message: the disk default-disk-57b5cc37592fb5c1(/longhorn) on the node worker-4 has 108267552768 available, but requires reserved 0, minimal 10% to schedule more replicas
> Reason: DiskPressure
> Status: False

**Comment by jenting** [comment]
The node 4 total replica volume size is larger than `(StorageMaximum-StorageReserved) * OverProvisioningPercentage` which is (245.08Gi - 0Gi)*1.5=367.62Gi in your case.

**Comment by jenting** [comment]
Close it since the question has been replied to.
Feel free to create a new question if you have one.
