### ISSUE TITLE
[BUG] volume creation with an invalid FromBackup should fail

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2686]
Currently if the FromBackup specified backup cannot be found in the backup store, the volume create call will succeed which signals that the volume can be created. This will then lead to a npe in the controller.

**Comment by joshimoo** [comment]
e2e test is tracked at https://github.com/longhorn/longhorn/issues/2687

**Comment by joshimoo** [comment]
There are 2 ways you can test this:

this one is a little quicker, but less likely to be used by a user.
via a storage class that specifies an invalid from backup
https://longhorn.io/docs/1.1.1/references/examples/#storageclass


This one requires setting up the csi snapshot stuff, if you haven't done this before, have a look at the documentation here:
https://longhorn.io/docs/1.1.1/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/

via a volume snapshot that specifies an invalid from backup:
https://longhorn.io/docs/1.1.1/snapshots-and-backups/csi-snapshot-support/restore-a-backup-via-csi/#restore-a-backup-that-has-no-associated-volumesnapshot

**Comment by kaxing** [comment]
Still validating, a short testing update on v1.1.2-rc1,

When referencing snapshot content (snapshotHandle) to a non-existed backup location,
```
kubectl get persistentvolumeclaim
NAME                           STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
test-restore-existing-backup   Pending                                                                        longhorn          5m30s
```

With the correct bs:// uri, the pvc can be created from VolumeSnapshot(Content), however I had to delete both VolumeSnapshot and VolumeSnapshotContent resources then re-apply the correct ones. Modifying the path doesn't seems to reflect the change directly, need to check again.

**Comment by kaxing** [comment]
Validation - In progress

Test steps:
1. Create a `VolumeSnapshotContent` with source from a none-exist Longhorn backupstore:
```yaml
source:
    snapshotHandle: bs://test-vol/backup-not-there
```
2. Create a `VolumeSnapshot` referencing volumeSnapshotContentName just created:
```yaml
  source:
    volumeSnapshotContentName: test-existing-backup
```
3. Create a `PersistentClaimVolume` restore from `VolumeSnapshot`
```yaml
  dataSource:
    name: test-snapshot-existing-backup
    kind: VolumeSnapshot
```

And monitoring the log of longhron-manager, I can see relevant error messages from both csi-provisioner and longhorn-manager:
```console
[longhorn-csi-plugin-7d4ns longhorn-csi-plugin] time="2021-06-30T09:12:37Z" level=error msg="CreateVolume: err: rpc error: code = NotFound desc = cannot restore csi snapshot bs://test-vol/backup-not-there backup backup-not-there unavailable"
[longhorn-manager-fqdds] time="2021-06-30T09:12:37Z" level=warning msg="cannot find backup backup-not-there of volume test-vol"
[csi-provisioner-7dcbc6f5bc-rtwc7] I0630 09:12:37.882395       1 connection.go:186] GRPC error: rpc error: code = NotFound desc = cannot restore csi snapshot bs://test-vol/backup-not-there backup backup-not-there unavailable
[csi-provisioner-7dcbc6f5bc-rtwc7] I0630 09:12:37.882427       1 controller.go:634] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = NotFound desc = cannot restore csi snapshot bs://test-vol/backup-not-there backup backup-not-there unavailable
[csi-provisioner-7dcbc6f5bc-rtwc7] E0630 09:12:37.882502       1 controller.go:939] error syncing claim "0818b5f3-395b-4b66-b29d-bd94b8c554ad": failed to provision volume with StorageClass "longhorn": rpc error: code = NotFound desc = cannot restore csi snapshot bs://test-vol/backup-not-there backup backup-not-there unavailable
[csi-provisioner-7dcbc6f5bc-rtwc7] I0630 09:12:37.883656       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test-restore-existing-backup", UID:"0818b5f3-395b-4b66-b29d-bd94b8c554ad", APIVersion:"v1", ResourceVersion:"317977", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "longhorn": rpc error: code = NotFound desc = cannot restore csi snapshot bs://test-vol/backup-not-there backup backup-not-there unavailable
```

Also, as mentioned in previous comment the pending volume won't be showed up in Longhorn UI, as result, user will need to check on resource itself or on Rancher UI go to Resources > Workloads > Volumes, then click into the Events to see error.

**Comment by joshimoo** [comment]
Since the provisioning of the volume failed, there is no longhorn volume and no associated PV getting created. So the PVC will remain unbound. This is outside of Longhorn therefore we don't need to show anything since there is no pending 'volume'.

**Comment by kaxing** [comment]
@joshimoo thank you for clarifying this for me.

Validation - **Passed**
Tested on both 1.1.2-rc1 and master-image(longhorn-manager: 27c93ca9)

[testing steps](2686#issuecomment-871242963)
[csi-snapshot setup](2686#issuecomment-867502824)
