### ISSUE TITLE
[UI] 'Bulk Update Recurring Snapshot and Backup' dialog says 'No Data'

### ISSUE THREAD

**Issue by kaxing** [longhorn/longhorn#2691]
**Describe the bug**
When selected **one volume** with previously set up with recurring backup, the `Bulk Update Recurring Snapshot and Backup` will still give user 'No Data'.

**To Reproduce**

Prerequire: volume with CronJob
0. Open Longhorn
1. Go to 'Volumes'
2. Select the volume
3. Click on dropdown menu ≡ next to Create Backup button
4. Click on 'Update Schedule'
![ bulk-action-with-single-volume](https://user-images.githubusercontent.com/602540/122052760-9d634e00-ce18-11eb-9410-61203a3040dc.gif)

**Expected behavior**
Previous created CronJob should be presented under `Bulk Update Recurring Snapshot and Backup` 
In contrast, open `Recurring Snapshot and Backup` dialog from the Schedule column all CronJobs will be presented.

**Log**
No log

**Environment:**
 - Longhorn version: v1.1.2-head(06/15), longhorn-ui: fa1e588

**Additional context**
No

**Comment by innobead** [comment]
cc @khushboo-rancher

**Comment by meldafrawi** [comment]
Ref: https://github.com/longhorn/longhorn/issues/946

**Comment by kaxing** [comment]
Thank you Mohamed.

So, it appears worked as design, but maybe we can change the `No Data` message into Selected Count, for example: `1 Volume Selected` to help user recognize this a UI for batch creating(update) schedules.

Also I did a quick check no documents needed to be updated in this changed. ([ref.](https://github.com/longhorn/website/search?q=%22No+Data%22&type=code))

**Comment by kaxing** [comment]
Validation - **Passed**

Verified with v1.1.2-head(ui: 7fb9440)
For demonstration, when selecting more than 100 volumes it will display as follow:
![image](https://user-images.githubusercontent.com/602540/122703011-3a900d80-d283-11eb-9ac2-2d7e0a025127.png)

Thank you @smallteeths !
