### ISSUE TITLE
[IMPROVEMENT] Consider changing the over provisioning default/recommendation to 100% percentage (no over provisioning)

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2694]
Context:
Currently we set the default overprovisioning percentage to 200%  
https://longhorn.io/docs/1.1.1/references/settings/#storage-over-provisioning-percentage

We also mentiond this as part of our best practices 
https://longhorn.io/docs/1.1.1/best-practices/

Opinion:
I feel that this is a risky recommendation/default. Since we cannot influence the file system -> block device locations. 
On non read only volumes, you are guaranteed in the long run to eventually end up using up the full volume, 
if there are files being created/deleted etc.

If we implement FS trim #836  which is hard to do with the snapshot support/guarantees than we could consider using a higher over provisioning percentage but at the moment, I don't think it's a good idea.

Proposition:
I recommend changing this to 100% as part of the default settings as well as best practices.
- For the best practices you want to allows be able to guarantee that your workloads can use the allocated space.
- For the default settings it's probably a good idea to do the same.

**Comment by agaldemas** [comment]
We have probably faced this issue....
Thanks for noticing it and change the default configuration to 100%, else it is very dangerous....

**Comment by innobead** [comment]
cc @derekbit @shuo-wu any concerns about this change? I agreed with this change.

**Comment by derekbit** [comment]
Agree with 100% by default as well. I don't see any concern for this change.

**Comment by shuo-wu** [comment]
Same. Increasing this setting value is easy after applying a smaller default value. But decreasing it typically needs more effort (for replica balancing/rescheduling)

**Comment by innobead** [comment]
This new change is not required to backport to prevent unexpected results, since this is related to space usage.

**Comment by chriscchien** [comment]
Verified **pass** in longhorn master(longhorn-manager `9cc40a`)

Setting value `storage-over-provisioning-percentage` changed to 100 by default 
After this fix merged, master-head pipeline did not see cascading error related to disk 
- Build [486](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/486/)
- Build [487](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/487/)
