### ISSUE TITLE
[QUESTION] Add disk hang and get EOF

### ISSUE THREAD

**Issue by sinoon** [longhorn/longhorn#2695]
**Question**

**Environment:**
 - Longhorn version: v1.1.1
 - Kubernetes version: 1.21
 - Node config
   - OS type and version  linux (amd64) / Debian GNU/Linux 9 (stretch)  /  4.14.81.bm.15-amd64
   - CPU per node: 
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**

Add a exist path of disk and page loading hang, get EOF in the end

![image](https://user-images.githubusercontent.com/6065488/122211784-b08a2280-ced9-11eb-8511-c06b6b0583c9.png)

**Comment by jenting** [comment]
> Add a exist path of disk and page loading hang, get EOF in the end

- Is it a fresh install disk?
- What the Default Data Path on the Setting page? At Longhorn, we use `/var/lib/longhorn/` by default.
- Could you please check the default data path on the disk is available and is accessible?

**Comment by jenting** [comment]
ping @sinoon

**Comment by innobead** [comment]
Closing due to no feedback, but feel free to reopen if you still have any questions.
