### ISSUE TITLE
[BUG] Volume operations take long time during automatic upgrading the engines in a big cluster

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2697]
**Describe the bug**
Volume operations (create new PVC/ attach/ detach) take long time during automatic upgrading the engines in a big cluster(400+ volume). This seems to come out of the scale as we couldn't reproduce it on a much smaller scale staging clusters. It doesn't seem to be related to the available resources as no OOM, throttling, iowaiting happens. The issue seems to temporarily resolve after rolling the longhorn-manager DaemonSet in the cluster. It even persists after stopping the engine upgrade. After the upgrade is complete it seems to work fine.

**Recollect the event chain:**
* At about 9pm UTC yesterday we upgraded the chart to 1.1.1 without issues and started the automatic upgrade with concurrency set to 1
* Within an hour or so it started exhibiting the issues we had earlier on another cluster — new volumes were stuck due to time outs
* The upgrade slowed down too
* Throughout the nigh we tried values of 1 and 2 for concurrency
* Eventually by today's noon we had about 80 volumes left unupgraded and it almost stopped moving down while all the attach/detach operations in the system were very slow
* Soon we found out that upgrades were completely stuck on one node
* After trying several things (restarts of some LH deployments) we stopped the auto upgrade, cordoned it and restarted the instance manager on it
* This caused forced re-scheduling of all the pods with attached volumes to different nodes
* In several hours (as attach/detach was still taking too much time) all but one pod were successfully running on other nodes and all stuck volumes were upgraded
* The node was still showing issues communicating with the instance manager even after this, so we just drained and terminated it
* Then we decided to upgrade the remaining 50 or so volumes manually in batches
* This was mostly fast (5-6m per volume), except one node once again (this time a different one) — it's the one that's currently stuck with 13 volumes

**Expected behavior**
Automatic engine upgrade should finish and should not slow down volume operations

**Log**
Support bundles is sent to email `longhorn-support-bundle@rancher.com`

**Environment:**
 - Longhorn version: 1.1.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: EKS 1.17
   - Number of management node in the cluster: unknown
   - Number of worker node in the cluster: 25
 - Node config
   - OS type and version: EKS-optimized Amazon Linux 2
   - CPU per node: varies
   - Memory per node: varies
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: varies
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 400+

**Additional context**
* Created on behalf of @excieve
* More information is on slack: https://cloud-native.slack.com/archives/CNVPEL9U3/p1621918309019000

**Comment by PhanLe1010** [comment]
**Some Update:**

1. It doesn't seem to related to the automatic engine upgrade feature since the problem also occurs when users manually upgrade the engine for multiple volumes at the same time:

    > Then we decided to upgrade the remaining 50 or so volumes manually in batches
    This was mostly fast (5-6m per volume), except one node once again (this time a different one) — it's the one that's currently stuck with 13 volumes

1. Looking at the support bundle `longhorn-support-bundle_0fddaa0b-bab5-47fc-b2c7-e6b7b82397c3_2021-06-16T17-48-07Z` sent over email. The problematic node in this cluster is the node `ip-10-4-201-138.eu-central-1.compute.internal` with the manager pod `longhorn-manager-9swq5` and the instance manager pod `instance-manager-e-f386c595`. By manually running some grpc calls:
    ```
    # Install grpcurl
    apt-get update
    apt-get install -y wget
    wget https://github.com/fullstorydev/grpcurl/releases/download/v1.8.0/grpcurl_1.8.0_linux_x86_64.tar.gz
    tar -zxvf grpcurl_1.8.0_linux_x86_64.tar.gz
    mv grpcurl /usr/local/bin/
    # Call instance manager gRPC APIs
    wget https://raw.githubusercontent.com/longhorn/longhorn-instance-manager/master/pkg/rpc/rpc.proto
    wget https://raw.githubusercontent.com/grpc/grpc/master/src/proto/grpc/health/v1/health.proto
    # check the health of grpc server on the instance manager instance-manager-e-f386c595
    grpcurl -d '' -plaintext -import-path ./ -proto health.proto 10.4.233.0:8500 grpc.health.v1.Health/Check
    # Server returns "status": "SERVING"
    grpcurl -d '' -plaintext -import-path ./ -proto rpc.proto 10.4.233.0:8500 ProcessManagerService/ProcessList
    # Server never returns response
    ```
    We found out that the instance manager `instance-manager-e-f386c595` doesn't return the process list when the manager pod asks for it. This prevents the manager from updating the IM CR with the correct list of processes. As the result, the engine CR is out of date and still pointing to the old port:
    ```
    # From the instance manager pod (note that the port of the new engine is 10143)
    time="2021-06-16T14:08:25Z" level=info msg="Reloaded completed for device /dev/longhorn/pvc-5c4fa764-4e40-4736-b9f3-47a544f37378"
    time="2021-06-16T14:08:25Z" level=info msg="engine: Finish upgrading for pvc-5c4fa764-4e40-4736-b9f3-47a544f37378"
    time="2021-06-16T14:08:25Z" level=info msg="Listening on gRPC Controller server: 0.0.0.0:10143"
    # From the manager pod (note that the manager is still see the old port 10119)
    │ time="2021-06-16T16:08:49Z" level=error msg="cannot live upgrade image for pvc-5c4fa764-4e40-4736-b9f3-47a544f37378-e-ea8e26cb: cannot get volume version: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.1/longhorn [--url 10.4.233.0:10119 version], output , stderr, time=\"2021-06 │
    │ -16T16:08:49Z\" level=fatal msg=\"Error running info command: failed to get version detail: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \\\"transport: Error while dialing dial tcp 10.4.233.0:10119: connect: connection refused\\\"\"\n,  │
    │ error exit status 1" controller=longhorn-engine engine=pvc-5c4fa764-4e40-4736-b9f3-47a544f37378-e-ea8e26cb node=ip-10-4-201-138.eu-central-1.compute.internal 
    ```

3. By further investigation, I have strong felling that there is deadlock inside the instance manager `instance-manager-e-f386c595` . The operations that requires acquiring the [Process manager lock](https://github.com/longhorn/longhorn-instance-manager/blob/80ba2c0a3411e176ee9176d1cc1320a664adf70a/pkg/process/process_manager.go#L36) are hang. For example:
    * [Create new engine process](https://github.com/longhorn/longhorn-instance-manager/blob/80ba2c0a3411e176ee9176d1cc1320a664adf70a/pkg/process/process_manager.go#L178) (attach volume)
    ```
    # From Longhorn manager longhorn-manager-9swq5
    2021-06-16T17:06:04.543048538Z time="2021-06-16T17:06:04Z" level=error msg="cannot live upgrade image for pvc-5567ddd6-6897-4567-bdee-6c8ad6ecb1e0-e-146149f0: failed to start process: rpc error: code = DeadlineExceeded desc = context deadline exceeded" controller=longhorn-engine 
    ```
    * [Delete engine process](https://github.com/longhorn/longhorn-instance-manager/blob/80ba2c0a3411e176ee9176d1cc1320a664adf70a/pkg/process/process_manager.go#L197) (detach volume)
    * [List engine processes](https://github.com/longhorn/longhorn-instance-manager/blob/80ba2c0a3411e176ee9176d1cc1320a664adf70a/pkg/process/process_manager.go#L261)
    ```
    # From Longhorn manager longhorn-manager-9swq5
    2021-06-16T17:07:04.496098110Z E0616 17:07:04.495676       1 instance_manager_controller.go:1153] failed to poll instance info to update instance manager instance-manager-e-f386c595: failed to list processes: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    ```
    * [Init process replace](https://github.com/longhorn/longhorn-instance-manager/blob/80ba2c0a3411e176ee9176d1cc1320a664adf70a/pkg/process/process_manager.go#L457)
    ```
    # From the engine instance manager instance-manager-e-f386c595
    2021-06-16T22:50:18.618291650Z [longhorn-instance-manager] time="2021-06-16T22:50:18Z" level=info msg="Process Manager: prepare to replace process pvc-ac32f6b8-eaa2-46ea-9e90-788d37895ea6-e-55d8349c"
    2021-06-16T22:50:48.243108085Z [longhorn-instance-manager] time="2021-06-16T22:50:48Z" level=info msg="Process Manager: prepare to replace process pvc-fa30a640-87b4-4ea5-a648-ec5c53347c54-e-a385ca3d"
    2021-06-16T22:52:37.814458954Z [longhorn-instance-manager] time="2021-06-16T22:52:37Z" level=info msg="Process Manager: prepare to replace process pvc-de3ed7c1-0691-4fc8-aaac-499bcba356a7-e-f8e7c1e0"
    (there are ton of log message like this)
    ```
4. The next step would be to find out how there possibly a deadlock inside the instance manager.

**Comment by yasker** [comment]
Move to `Team Review Required` due to it sounds like a ticking bomb we don't understand yet.

**Comment by excieve** [comment]
We had this reoccur without an upgrade on the same cluster today. The reason was — the instance manager crashed (seems the node's systemd suddenly started leaking memory real bad and OOM killing the instance manager, so this particular cause might be unrelated). With 100+ pods and their volumes being rescheduled, at some point it eventually got stuck detaching/attaching the volumes for hours. We've rolled the `longhorn-manager` and `longhorn-csi-plugin` DaemonSets, as well as the `csi-attacher` Deployment as we weren't sure where did it get stuck — this helped and the detach/attach process went through after this.

So it seems the deadlock theory is right. One more point of interest — this never happened with LH v1.1.0 (not sure if something's in v1.1.1 or just by chance).

That said, this incident left us with a number of volumes with corrupted files (application writing while the instance manager was killed most likely) and some volumes not detaching at all even when deleting a pod.

**Comment by yasker** [comment]
@excieve Sorry to hear that... We've identified a deadlock and fixing it. Though it won't solve your corrupted file problem. I feel we should add reserved memory to the instance managers in the future, to potentially prevent a similar issue from happening. Though it might be hard in your specific case since I think the systemd likely still has a higher priority than the instance manager.

**Comment by excieve** [comment]
@yasker Yeah, I mean the problem is this deadlock appears to be happening even if there's no on-going engine upgrade.

**Comment by PhanLe1010** [comment]
@excieve 
It seems that you experience a different problem than the problem we indentify in this issue. In this issue @joshimoo  identified deadlocks inside `instance-manager` and the deadlock should be resolved by restarting `instance-manager-e` pod instead of restarting `longhorn-manager` pod. 

Should we create a new issue for that?

cc @joshimoo @yasker

**Comment by PhanLe1010** [comment]
I have tested Joshua [PR](https://github.com/longhorn/longhorn-instance-manager/pull/89) with the following steps:
1. Create a cluster of 3 worker nodes
2. Create 90 volumes. Attach 30 volumes to each worker node
3. Deploy v1.1.1 engine image
4. Select all 90 volumes and try to upgrade engine at the same time
5. While the upgrade is happing try to detach, attach some volumes. Create a few new volumes
6. Verify that the upgrades finish within 30 min
7. Set `Concurrent Automatic Engine Upgrade Per Node Limit` to 3
8. wait for automatic engine upgrade to start
9. While the upgrade is happing try to detach, attach  some volumes. Create a few new volumes
10. Verify that the upgrades finish within 30 min
11. Repeat the whole test a few times. 

Thanks @joshimoo for fixing the bug!

**Comment by excieve** [comment]
@PhanLe1010 Thanks for the update! No idea if it's the same issue or a different one, but in both cases restarting the `longhorn-manager` had some temporary effect when detaching/attaching the volumes.

Also, if the issue is in the `instance-manager`, does it mean we'll need to redeploy the instance manager pods when this fix is out (therefore causing all the volumes in the cluster to detach) or would there be a safer way to upgrade?

**Comment by PhanLe1010** [comment]
@excieve 
When this fix (v1.1.2) is out and you upgrade to v1.1.2, there will be 2 different `instance-manager` versions running side by side in your cluster (1 pod for the old version and 1 new pod for the new version). The engine/replica processes will continue to live inside the old `instance-manager` pod.  Now, if for some reason the volumes are detached (because you scale down the workload or because you rolling out the workload), Longhorn will clean stop the engine/replica processes in the old pod and start them on the new `instance-manager` pod when the volumes are reattached. After all volumes' engine/replica processes move to the new `instance-manager` pod, Longhorn will delete the old `instance-manager` pod. Then, you can start upgrading engine image to v1.1.2 as usual.

**Comment by PhanLe1010** [comment]
@excieve Could you please let us know the result when you upgrade to v1.1.2?

**Comment by PhanLe1010** [comment]
The workaround once this problem happens:
1. Stop upgrading any other volumes
1. Scale down all workload pods that are using Longhorn volumes on the node of the affected instance manager. All volumes on the node will be stuck in detaching state.
1. Then we kill the instance manager
1. Scale up the workload pods

**Comment by Devway21** [comment]
I upgraded the longhorn-manager and now it run tow instance-manager but both of them are v1_20210621. I am stuck with the PVs that are still under the V.1.1.0 which had not been updated. There is no instance-manager running them so all V.1.1.0 PV engines are stopped and can not be attached because of that. 
All the three versions engine-image pods are running normally. 

The need is to run the old PVs either by enforcing the upgrade or any other way to let the new instance-manager run both old and new ones as kind of supporting old versioned PVs. Could you please advice me on how to resolve this issue.

**Comment by PhanLe1010** [comment]
@Devway21 The new instance-manager version `v1_20210621` should be able to run both old and new engine image (v1.1.0 and v1.1.2) 

Are you saying that when you start the workload pods that use the PVs associated with Longhorn volumes with v1.1.0 engine image, the volumes cannot be attached? If so, it doesn't sound right. 

What is the output of the command `kubectl get engineimages -n longhorn-system -o yaml`?
What is the logs of `longhorn-manager-xxx` pod when you try to start workload and therefore attach the old PVs?

**Comment by Devway21** [comment]
> Are you saying that when you start the workload pods that use the PVs associated with Longhorn volumes with v1.1.0 engine image, the volumes cannot be attached? If so, it doesn't sound right.

Yes exactly and the volumes cannot be attached.

Please have a look at  :

kubectl get engineimages -n longhorn-system -o yaml
apiVersion: v1
items:
- apiVersion: longhorn.io/v1beta1
  kind: EngineImage
  metadata:
    creationTimestamp: "2021-05-29T16:36:33Z"
    finalizers:
    - longhorn.io
    generation: 1
    labels:
      longhorn.io/component: engine-image
      longhorn.io/engine-image: ei-611d1496
      longhorn.io/managed-by: longhorn-manager
    managedFields:
    - apiVersion: longhorn.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"longhorn.io": {}
          f:labels:
            .: {}
            f:longhorn.io/component: {}
            f:longhorn.io/engine-image: {}
            f:longhorn.io/managed-by: {}
        f:spec: {}
        f:status: {}
      manager: longhorn-manager
      operation: Update
      time: "2021-05-29T16:36:33Z"
    name: ei-611d1496
    namespace: longhorn-system
    resourceVersion: "90166693"
    uid: 8c9beeae-0e32-45af-9cd1-fc9d6a353794
  spec:
    image: longhornio/longhorn-engine:v1.1.1
  status:
    buildDate: "2021-04-23T02:29:18+00:00"
    cliAPIMinVersion: 3
    cliAPIVersion: 4
    conditions:
      ready:
        lastProbeTime: ""
        lastTransitionTime: "2021-07-15T16:55:26Z"
        message: Engine image ei-611d1496 (longhornio/longhorn-engine:v1.1.1) is fully
          deployed on all ready nodes
        reason: ""
        status: "True"
        type: ready
    controllerAPIMinVersion: 3
    controllerAPIVersion: 3
    dataFormatMinVersion: 1
    dataFormatVersion: 1
    gitCommit: 3cc56fd7c02269718bbe276f78fe7257e46c6c1a
    noRefSince: ""
    nodeDeploymentMap:
      vmi275931.contaboserver.net: true
    ownerID: vmi275931.contaboserver.net
    refCount: 1
    state: deployed
    version: v1.1.1
- apiVersion: longhorn.io/v1beta1
  kind: EngineImage
  metadata:
    creationTimestamp: "2021-07-14T11:16:39Z"
    finalizers:
    - longhorn.io
    generation: 1
    labels:
      longhorn.io/component: engine-image
      longhorn.io/engine-image: ei-a5a44787
      longhorn.io/managed-by: longhorn-manager
    managedFields:
    - apiVersion: longhorn.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"longhorn.io": {}
          f:labels:
            .: {}
            f:longhorn.io/component: {}
            f:longhorn.io/engine-image: {}
            f:longhorn.io/managed-by: {}
        f:spec: {}
        f:status: {}
      manager: longhorn-manager
      operation: Update
      time: "2021-07-14T11:16:39Z"
    name: ei-a5a44787
    namespace: longhorn-system
    resourceVersion: "90166944"
    uid: 909425ed-a1b9-43d2-9b09-5f8d3cc49202
  spec:
    image: longhornio/longhorn-engine:v1.1.2
  status:
    buildDate: "2021-07-06T23:03:12+00:00"
    cliAPIMinVersion: 3
    cliAPIVersion: 4
    conditions:
      ready:
        lastProbeTime: ""
        lastTransitionTime: "2021-07-15T16:55:26Z"
        message: Engine image ei-a5a44787 (longhornio/longhorn-engine:v1.1.2) is fully
          deployed on all ready nodes
        reason: ""
        status: "True"
        type: ready
    controllerAPIMinVersion: 3
    controllerAPIVersion: 3
    dataFormatMinVersion: 1
    dataFormatVersion: 1
    gitCommit: ad0aabcfa65d9aaecfac97ae1bf30cbb70afddb8
    noRefSince: "2021-07-14T11:16:39Z"
    nodeDeploymentMap:
      vmi275931.contaboserver.net: true
    ownerID: vmi275931.contaboserver.net
    refCount: 0
    state: deployed
    version: v1.1.2
- apiVersion: longhorn.io/v1beta1
  kind: EngineImage
  metadata:
    creationTimestamp: "2021-01-15T10:40:23Z"
    finalizers:
    - longhorn.io
    generation: 1
    labels:
      longhorn.io/component: engine-image
      longhorn.io/engine-image: ei-cf743f9c
      longhorn.io/managed-by: longhorn-manager
    managedFields:
    - apiVersion: longhorn.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"longhorn.io": {}
          f:labels:
            .: {}
            f:longhorn.io/component: {}
            f:longhorn.io/engine-image: {}
            f:longhorn.io/managed-by: {}
        f:spec: {}
        f:status: {}
      manager: longhorn-manager
      operation: Update
      time: "2021-05-25T11:43:20Z"
    name: ei-cf743f9c
    namespace: longhorn-system
    resourceVersion: "90249679"
    uid: 5d98d27f-1049-49f1-87c1-82c090b988a0
  spec:
    image: longhornio/longhorn-engine:v1.1.0
  status:
    buildDate: "2020-12-18T00:38:19+00:00"
    cliAPIMinVersion: 3
    cliAPIVersion: 4
    conditions:
      ready:
        lastProbeTime: ""
        lastTransitionTime: "2021-07-15T20:26:36Z"
        message: Engine image ei-cf743f9c (longhornio/longhorn-engine:v1.1.0) is fully
          deployed on all ready nodes
        reason: ""
        status: "True"
        type: ready
    controllerAPIMinVersion: 3
    controllerAPIVersion: 3
    dataFormatMinVersion: 1
    dataFormatVersion: 1
    gitCommit: b9e072eb19cfcc27894e10a8e60794c66ca918f8
    noRefSince: ""
    nodeDeploymentMap:
      vmi275931.contaboserver.net: true
    ownerID: vmi275931.contaboserver.net
    refCount: 2
    state: deployed
    version: v1.1.0
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

The failure in two workloads PODs each with a volume which failed to be attached 
One of the workload event log is:
Warning 	FailedMount 	MountVolume.SetUp failed for volume "pvc-1dda7b81-db08-450e-88f9-8f9296763ca1" : rpc error: code = InvalidArgument desc = volume pvc-1dda7b81-db08-450e-88f9-8f9296763ca1 hasn't been attached yet 	2 minutes ago

The log of longhorn-manager-xxx : 

E0716 07:06:52.548955       1 volume_controller.go:202] fail to sync longhorn-system/pvc-1dda7b81-db08-450e-88f9-8f9296763ca1: fail to reconcile volume state for pvc-1dda7b81-db08-450e-88f9-8f9296763ca1: no healthy or scheduled replica for starting 
time="2021-07-16T07:06:52Z" level=warning msg="Dropping Longhorn volume longhorn-system/pvc-1dda7b81-db08-450e-88f9-8f9296763ca1 out of the queue" controller=longhorn-volume error="fail to sync longhorn-system/pvc-1dda7b81-db08-450e-88f9-8f9296763ca1: fail to reconcile volume state for pvc-1dda7b81-db08-450e-88f9-8f9296763ca1: no healthy or scheduled replica for starting" node=vmi275931.contaboserver.net 
E0716 07:06:52.549319       1 volume_controller.go:202] fail to sync longhorn-system/pvc-2db1552a-cf07-441d-8d7d-544f28b1d3a6: fail to reconcile volume state for pvc-2db1552a-cf07-441d-8d7d-544f28b1d3a6: no healthy or scheduled replica for starting 
time="2021-07-16T07:06:52Z" level=warning msg="Dropping Longhorn volume longhorn-system/pvc-2db1552a-cf07-441d-8d7d-544f28b1d3a6 out of the queue" controller=longhorn-volume error="fail to sync longhorn-system/pvc-2db1552a-cf07-441d-8d7d-544f28b1d3a6: fail to reconcile volume state for pvc-2db1552a-cf07-441d-8d7d-544f28b1d3a6: no healthy or scheduled replica for starting" node=vmi275931.contaboserver.net 
time="2021-07-16T07:06:54Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-1dda7b81-db08-450e-88f9-8f9296763ca1" controller=longhorn-volume error="fail to sync longhorn-system/pvc-1dda7b81-db08-450e-88f9-8f9296763ca1: fail to reconcile volume state for pvc-1dda7b81-db08-450e-88f9-8f9296763ca1: no healthy or scheduled replica for starting" node=vmi275931.contaboserver.net 
time="2021-07-16T07:06:54Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-2db1552a-cf07-441d-8d7d-544f28b1d3a6" controller=longhorn-volume error="fail to sync longhorn-system/pvc-2db1552a-cf07-441d-8d7d-544f28b1d3a6: fail to reconcile volume state for pvc-2db1552a-cf07-441d-8d7d-544f28b1d3a6: no healthy or scheduled replica for starting" node=vmi275931.contaboserver.net 
time="2021-07-16T07:06:54Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-1dda7b81-db08-450e-88f9-8f9296763ca1" controller=longhorn-volume error="fail to sync longhorn-system/pvc-1dda7b81-db08-450e-88f9-8f9296763ca1: fail to reconcile volume state for pvc-1dda7b81-db08-450e-88f9-8f9296763ca1: no healthy or scheduled replica for starting" node=vmi275931.contaboserver.net 
time="2021-07-16T07:06:54Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-2db1552a-cf07-441d-8d7d-544f28b1d3a6" controller=longhorn-volume error="fail to sync longhorn-system/pvc-2db1552a-cf07-441d-8d7d-544f28b1d3a6: fail to reconcile volume state for pvc-2db1552a-cf07-441d-8d7d-544f28b1d3a6: no healthy or scheduled replica for starting" node=vmi275931.contaboserver.net 
E0716 07:06:55.004637       1 volume_controller.go:202] fail to sync longhorn-system/pvc-1dda7b81-db08-450e-88f9-8f9296763ca1: fail to reconcile volume state for pvc-1dda7b81-db08-450e-88f9-8f9296763ca1: no healthy or scheduled replica for starting 
time="2021-07-16T07:06:55Z" level=warning msg="Dropping Longhorn volume longhorn-system/pvc-1dda7b81-db08-450e-88f9-8f9296763ca1 out of the queue" controller=longhorn-volume error="fail to sync longhorn-system/pvc-1dda7b81-db08-450e-88f9-8f9296763ca1: fail to reconcile volume state for pvc-1dda7b81-db08-450e-88f9-8f9296763ca1: no healthy or scheduled replica for starting" node=vmi275931.contaboserver.net 
E0716 07:06:55.004994       1 volume_controller.go:202] fail to sync longhorn-system/pvc-2db1552a-cf07-441d-8d7d-544f28b1d3a6: fail to reconcile volume state for pvc-2db1552a-cf07-441d-8d7d-544f28b1d3a6: no healthy or scheduled replica for starting 
time="2021-07-16T07:06:55Z" level=warning msg="Dropping Longhorn volume longhorn-system/pvc-2db1552a-cf07-441d-8d7d-544f28b1d3a6 out of the queue" controller=longhorn-volume error="fail to sync longhorn-system/pvc-2db1552a-cf07-441d-8d7d-544f28b1d3a6: fail to reconcile volume state for pvc-2db1552a-cf07-441d-8d7d-544f28b1d3a6: no healthy or scheduled replica for starting" node=vmi275931.contaboserver.net 
10.42.0.33 - - [16/Jul/2021:07:07:15 +0000] "GET /v1/volumes/pvc-1dda7b81-db08-450e-88f9-8f9296763ca1 HTTP/1.1" 200 2896 "" "Go-http-client/1.1" 
10.42.0.33 - - [16/Jul/2021:07:07:15 +0000] "GET /v1/settings/mkfs-ext4-parameters HTTP/1.1" 200 545 "" "Go-http-client/1.1" 
10.42.0.33 - - [16/Jul/2021:07:07:15 +0000] "GET /v1/volumes/pvc-2db1552a-cf07-441d-8d7d-544f28b1d3a6 HTTP/1.1" 200 2896 "" "Go-http-client/1.1" 
10.42.0.33 - - [16/Jul/2021:07:07:15 +0000] "GET /v1/settings/mkfs-ext4-parameters HTTP/1.1" 200 545 "" "Go-http-client/1.1"

**Comment by Devway21** [comment]
Also in the log of both pods of the longhorn-instance-manager:v1_20210621 there is no any mentioning of the PVs which had the problem, so there is no instant manager running them and that will cause no logical existence and no way to access them. then the failure to be attached is normal result.

**Comment by PhanLe1010** [comment]
Since you create an issue at https://github.com/longhorn/longhorn/issues/2801, we can continue to discuss over there

**Comment by excieve** [comment]
> @excieve Could you please let us know the result when you upgrade to v1.1.2?

Sure thing, but we're not clear on the timeline yet since our current mix of v1.1.1 and v1.1.0 is fairly stable at the moment.

**Comment by kaxing** [comment]
Validating in progress with v1.2.1-rc1,

with steps mention [in this comment above](#issuecomment-865703677),
running tests on a small cluster with 3 worker nodes (2cpus + 8gb ram).

Does not bump into any problem upgrading from v1.1.1 to v1.2.1-rc1 for 90 Volumes(creating by StatefulSet), however it won't finish within 30mins.

![image](https://user-images.githubusercontent.com/602540/134339578-236b28c5-9685-4bb2-9ed8-a014752f63fe.png)

**Comment by kaxing** [comment]
Validation: **PASSED**

Re-tested with v1.2.1-rc1 and master-head(20210927-3pm), upgrading 90 volumes from v1.2.0 engine and set the `Concurrent Automatic Engine Upgrade Per Node Limit` to 3. The live upgrade can be finished around 15mins.
