### ISSUE TITLE
[BUG] Liveness/Readiness Probe timeoutSeconds at Kubernetes v1.20+

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#2699]
**Describe the bug**

I encounter an issue on Kubernetes v1.21.0, the kubelet with log:
```shell
2021-05-12T05:03:40.341728+00:00 jenting-longhorn-master-0 k3s[17498]: E0512 05:03:40.341637   17498 remote_runtime.go:394] "ExecSync cmd from runtime service failed" err="rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 1s exceeded: context deadline exceeded" containerID="2772def98866331ae76c100ab412ce1961a1e35e19bf4f9f9345077a0d733f9b" cmd=[sh -c ls /data/longhorn && /data/longhorn version --client-only]
```

The workaround to fix it is to increase the `readinessProbe.timeoutSeconds` on engine-image-ei-xxx DaemonSet from 1 sec to 3 secs. According to the https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes, start from Kubernetes 1.20, the `timeoutSeconds` behavior got fixed. Therefore, if the user's Kubernetes cluster that the `readinesssProbe` is over than 1 sec, the Pod can't mount value successfully.  The only way to know the root cause is to dump the kubelet log.
![image](https://user-images.githubusercontent.com/49380831/122930159-4d4b3500-d39e-11eb-9a75-6f85ecae32ac.png)

**To Reproduce**

It's not easy to reproduce, I could only reproduce it on my local desktop and creates 8 nodes (2 master nodes + 6 worker nodes)
and install Longhorn on top of it.

**Expected behavior**

All Longhorn Pods should run successfully and also Pods are able to mount the volume.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: v1.1.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.21.0
   - Number of management node in the cluster: 2
   - Number of worker node in the cluster: 6
 - Node config
   - OS type and version: 
   - CPU per node: 
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster: 0

**Additional context**

**Comment by innobead** [comment]
@khushboo-rancher Please help coordinate the verification and close if this is verified by the latest build. Thanks.

cc @kaxing @meldafrawi

**Comment by kaxing** [comment]
Validating the Health Check settings with following steps:

0. Tested on Kubernetes version + longhorn master-head(ui: d8c28eb)
0. Log into the worker node and watch the kubelet logs
0. Execute into engine-image-ei-* container which attached to the worker node
0. Inside the engine pod container, using following commands to force longhorn command to pause 4 seconds:
```console
$ cd /data && mv longhorn onghorn-bin && echo -e '#!/bin/bash\nsleep 4 && /data/longhorn-bin $@' > longhorn; chmod +x longhorn
```

Will able to see following errors from the worker node's kubelet log,
```
{"log":"E0622 05:17:53.815455    7323 remote_runtime.go:392] ExecSync a4c44cf6b3e613ac288065ba19afc082665cbea4726a5f332cd075615cf6cce2 'sh -c ls /data/longhorn \u0026\u0026 /data/longhorn version --client-only' from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n","stream":"stderr","time":"2021-06-22T05:17:53.815663411Z"}
{"log":"E0622 05:17:58.815485    7323 remote_runtime.go:392] ExecSync a4c44cf6b3e613ac288065ba19afc082665cbea4726a5f332cd075615cf6cce2 'sh -c ls /data/longhorn \u0026\u0026 /data/longhorn version --client-only' from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n","stream":"stderr","time":"2021-06-22T05:17:58.815666829Z"}
{"log":"E0622 05:18:03.815285    7323 remote_runtime.go:392] ExecSync a4c44cf6b3e613ac288065ba19afc082665cbea4726a5f332cd075615cf6cce2 'sh -c ls /data/longhorn \u0026\u0026 /data/longhorn version --client-only' from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n","stream":"stderr","time":"2021-06-22T05:18:03.81544451Z"}
{"log":"E0622 05:18:08.815262    7323 remote_runtime.go:392] ExecSync a4c44cf6b3e613ac288065ba19afc082665cbea4726a5f332cd075615cf6cce2 'sh -c ls /data/longhorn \u0026\u0026 /data/longhorn version --client-only' from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n","stream":"stderr","time":"2021-06-22T05:18:08.815482939Z"}
{"log":"E0622 05:18:13.815348    7323 remote_runtime.go:392] ExecSync a4c44cf6b3e613ac288065ba19afc082665cbea4726a5f332cd075615cf6cce2 'sh -c ls /data/longhorn \u0026\u0026 /data/longhorn version --client-only' from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n","stream":"stderr","time":"2021-06-22T05:18:13.815458219Z"}
{"log":"E0622 05:18:18.815209    7323 remote_runtime.go:392] ExecSync a4c44cf6b3e613ac288065ba19afc082665cbea4726a5f332cd075615cf6cce2 'sh -c ls /data/longhorn \u0026\u0026 /data/longhorn version --client-only' from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n","stream":"stderr","time":"2021-06-22T05:18:18.815345281Z"}
{"log":"E0622 05:18:23.815143    7323 remote_runtime.go:392] ExecSync a4c44cf6b3e613ac288065ba19afc082665cbea4726a5f332cd075615cf6cce2 'sh -c ls /data/longhorn \u0026\u0026 /data/longhorn version --client-only' from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n","stream":"stderr","time":"2021-06-22T05:18:23.815273219Z"}
{"log":"E0622 05:18:28.815038    7323 remote_runtime.go:392] ExecSync a4c44cf6b3e613ac288065ba19afc082665cbea4726a5f332cd075615cf6cce2 'sh -c ls /data/longhorn \u0026\u0026 /data/longhorn version --client-only' from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded\n","stream":"stderr","time":"2021-06-22T05:18:28.815181112Z"}
```

**Comment by kaxing** [comment]
Testing status update:

With the same [testing steps above](#issuecomment-865615283), by changing the sleep command to an empty one inside each engine-image-ei-* containers, the engine-image-ei-* DaemonSet will back to normal,
```console
cp /bin/sleep /; echo "echo nosleep" > /bin/sleep; chmod +x /bin/sleep
```
It is a bit hacky way to verify this issue, but I am thinking to test the behavior without touching the configuration. But please leave comment if there are any concerns.

Still verifying the behavior on Kubernetes server v1.19.*.

**Comment by jenting** [comment]
Upstream [PR](https://github.com/kubernetes/kubernetes/pull/94115) for reference.

**Comment by kaxing** [comment]
Validation - **Passed**

Sum up my testing and study result:
By adjusting the Health Check (readinessProbe) timeout to 4 seconds which will only be effective on Kubernetes server version after 1.20+, as mentioned in [previous comment](#issuecomment-865615283).
Using Longhorn version 1.1.2 or later on Kubernetes version older than 1.20 will still not able to use the `timeoutSeconds` setting.

Additional note on verifying the `readinessProbe.timeoutSeconds` defect itself on elder K8s releases:
Tested by upgrading the node versions in following order, and here is the result,
```
Longhorn v1.1.1 on Node with version:
RKE v1.18.20, timeout setting doesn’t work and no DeadlineExceeded errorin kubelet log
RKE v1.19.12, timeout setting doesn’t work and no DeadlineExceeded error in kubelet log
RKE v1.20.8, timeout setting will be respected, and there is DeadlineExceeded errors in kubelet log
```
*the cluster is deploying from Rancher Server 2.8.5


Thank you @jenting !
