### ISSUE TITLE
[QUESTION] Specifying numberOfReplicas for a specific deployment/pvc ?

### ISSUE THREAD

**Issue by iangregsondev** [longhorn/longhorn#2710]
**Question**

Hi, I am using a statefulset (and actually a deployment in another) and my default numberOfReplicas for the storageClass is set to 2.

I would like to be able to specify that a deployment/statefulset has a number different to the default. For example, in my case, I would like to drop the numberOfReplicas to 1 for the PVC/PV.

I tried searching the docs but I could only find how to set the default which I already did. I set it to 2.. Which is the case on most statefulsets/deployments.

Can I control at deploy time that a statefulset or deployment will use a certain numberOfReplicas instead of the default 2 replicas of a disk.

Thanks in advance.

**Additional context**

**Comment by joshimoo** [comment]
You can create different storage classes with different replica settings (fast single non ha storage class, default ha storage class, etc)
So each PVC can use a storage class type that aligns with the consumers requirement.

**Comment by iangregsondev** [comment]
Wow! Thats great. I think this is what I will do.

I didn't realise that.

I thought there was a setting on the PV / PVC that I didn't know about. Didn't realise about create new classes.

**Comment by w3blogfr** [comment]
Hello, 
perfect solution to duplicate storage classe that match my need.

Just one point, does anybody know why the default "longhorn" storage class is reset as a default all the time?
![image](https://user-images.githubusercontent.com/2735852/222170312-72e73fb3-6ea7-4117-96ae-61e18142d1f9.png)

30 seconds after.
![image](https://user-images.githubusercontent.com/2735852/222170225-55bcab92-5d55-4762-bc5d-54d1cfbe41ed.png)

Regards.
