### ISSUE TITLE
[FEATURE] Enable pprof endpoints in longhorn manager for troubleshooting

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#2715]
**Is your feature request related to a problem? Please describe.**

This is the first part of #2696, but it will be fully implemented in #2696.

**Describe the solution you'd like**

- [x] Enabling pprof by default in longhorn manager only.

ref: https://github.com/longhorn/longhorn/issues/2715#issue-925745823

**Describe alternatives you've considered**

ref: https://github.com/longhorn/longhorn/issues/2696#issue-922786940

**Additional context**

ref: https://github.com/longhorn/longhorn/issues/2696#issue-922786940

**Comment by joshimoo** [comment]
Testing instructions:

This listens only on the localhost of the pod on a dedicated http server on port 6060. And can be accessed by:
- kubectl port-forward <longhorn-manager-pod> -n longhorn-system 6060:6060
- open browser http://localhost:6060/debug/pprof
- go tool pprof http://localhost:6060/debug/pprof/profile

**Comment by kaxing** [comment]
Validation - **Passed**

Tested with Longhorn **v1.1.2-rc1**.

After exposing service port to localhost, I can:

Use the pprof cli,
```
$ go tool pprof http://localhost:6060/debug/pprof/profile
Fetching profile over HTTP from http://localhost:6060/debug/pprof/profile
Saved profile in /Users/user/pprof/pprof.longhorn-manager.samples.cpu.002.pb.gz
File: longhorn-manager
Type: cpu
Time: Jun 23, 2021 at 9:07pm (CST)
Duration: 30s, Total samples = 330ms ( 1.10%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof)
```

And see the pprof debug web page:
![image](https://user-images.githubusercontent.com/602540/123101928-1ab93f00-d467-11eb-92a3-61acfc73b5c0.png)

**Comment by khushboo-rancher** [comment]
@kaxing Can you please check this on Master as well?

**Comment by kaxing** [comment]
Validated again on master-head images(longhorn-manager: efb52ba3)
pprof service works as expected.
