### ISSUE TITLE
[TEST] replica_auto_balance tests are unstable

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2716]
**What's the test to develop? Please describe.**
Fix the unstable replica_auto_balance tests caused at the case setup.

**Describe the items of the test development (DoD, definition of done) you'd like.**
- [x] pass tests in CI with `--count 5`

**Additional context**
https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/390/#showFailuresLink

**Comment by innobead** [comment]
Adding to the current sprint.
