### ISSUE TITLE
[BUG] Longhorn GUI not showing the real time operation status

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2720]
**Describe the bug**
The pages like volume, volume detail are not showing the real time status of operations like volume upgrade, rebuilding.

**To Reproduce**
**Scenario -1**
1. Upgrade the Longhorn from v1.1.1 to `v1.1.2-head`
2. Go to the volume page.
3. Select a volume and click upgrade.
4. The upgrade symbol keeps showing the `upgrading` icon until user refreshes the page.

**Scenario -2**
1. Create a volume and write 1 GB data into it.
2. Go to the volume details page and delete a replica.
3. The rebuilding of replica will start, but the UI will not show the progress

**Expected behavior**
The UI should show the real time status of upgrade and rebuilding.

**Environment:**
 - Longhorn version: v1.1.2-head

**Comment by khushboo-rancher** [comment]
If I'll observe this more often, I'll increase the severity.

**Comment by innobead** [comment]
@smallteeths  @c3y1huang probably it seems related to the change of filtered WS sockets.

**Comment by khushboo-rancher** [comment]
I observed this again while upgrading my set up from v1.1.2-rc1 to master.

Steps:
1. Create a Longhorn set up v1.1.2-rc1
2. Create few volumes.
3. Upgrade to Master.
4. Refresh the Longhorn UI.
5. Observe the WS sockets are not active.
<img width="1766" alt="Screen Shot 2021-06-28 at 12 12 39 PM" src="https://user-images.githubusercontent.com/60111667/123691279-442cee80-d80a-11eb-83c3-98cebd00bd12.png">

Note: Even though I refresh the page, the icons shown in the screenshot remained greyed out. Only after I close and open this in a new tab, it started working.

**Comment by smallteeths** [comment]
Sorry I haven't reproduced this bug. The steps I reproduced were to directly change the image of longhorn-manager. Then check the page to see if ws is disconnected.

I suspect that the status code returned by ws is 1008 or 1011, because only these two status codes will prevent ws from reconnecting.  Did you pay attention to the status code of ws when this bug appeared @khushboo-rancher ?

**Comment by khushboo-rancher** [comment]
I've not observed this from long time. We can close this for now. If I observe this again, I will reopen this.
