### ISSUE TITLE
[TASK] Release v1.1.2

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#2724]
**What's the task? Please describe.**

Action items for releasing v1.1.2

**Describe the items of the task (DoD, definition of done) you'd like.**
  - [x] release GA draft w/ all images built, repo tags, chart PR - @innobead 
  - [x] verify GA draft 
    - [x] run automatic e2e regression @meldafrawi 
    - [x] some mandatory manual regression: longhorn/chart PR install, upgrade) - @khushboo-rancher 
  - [x] release (longhorn/longhorn, longhorn/chart, longhorn/website) and make sure doc links correctly in the release note - @innobead 
  - [x] merge the release branch to master (longhorn/longhorn, longhorn/website) - @innobead  
  - [x] have rancher chart PRs (cluster explorer 2.5, 2.6, and cluster manager) and image mirror @shuo-wu  
    - [x] rancher/image-mirrors update - @shuo-wu  (ex: https://github.com/rancher/image-mirror/pull/95)
    - [x] rancher/charts master branch for cluster manager - @shuo-wu (ex: https://github.com/rancher/charts/pull/1143)
    - [x] rancher/charts dev-* branches for cluster explorer - @shuo-wu   (ex: https://github.com/rancher/charts/pull/1144)
    - [x] verify the chart being able to install & upgrade - @khushboo-rancher 

**Additional context**
N/A

cc @khushboo-rancher @meldafrawi @kaxing

**Comment by innobead** [comment]
To make sure the draft chart ready before release, we need to do a quick sanity check for auto and manual.

- @meldafrawi please help run the core test for https://github.com/longhorn/longhorn/tree/v1.1.2 (using v1.1.2). 
- @khushboo-rancher please help do the manual regression (sanity test) against https://github.com/longhorn/charts/pull/14 to see if the installation and upgrade working fine. 

After finishing, please :heavy_check_mark:  the checkbox in the ticket description. Thanks.

cc @kaxing

**Comment by innobead** [comment]
@shuo-wu Please help rancher/charts and image mirrors tasks after 1.1.2 release out.

**Comment by innobead** [comment]
All PRs ready, just wait for merging.

**Comment by cocampbe** [comment]
Do you have an estimate of wehn this will make it to v2.5 for use via clsuter explorer? I am itching to use 1.1.2.

**Comment by innobead** [comment]
> Do you have an estimate of wehn this will make it to v2.5 for use via clsuter explorer? I am itching to use 1.1.2.

ref: https://github.com/rancher/charts/issues/1352#issuecomment-887999551

For the chart released in cluster explorer, as per the reference, it will be released together with the next release of Rancher. It should be 2.6.0 and 2.5.10 soon or later.

**Comment by cocampbe** [comment]
@innobead Thank you. I was wondering how the charts mapped to rancher releases. That is very helpful to know.
