### ISSUE TITLE
[TEST] test_node_umount_disk and test_node_disk_update fail in nightly tests

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#2730]
**What's the test to develop? Please describe.**
it seems that both test_node_umount_disk and test_node_disk_update fail for the same reason

```
>               wait_for_disk_storage_available(client, lht_hostId, name,
                                                disk_path1)

test_node.py:1264: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

client = <longhorn.Client object at 0x7f72bf465760>
node_name = 'longhorn-tests-ubuntu-amd64-worker-2', disk_name = 'disk1'
disk_path = '/tmp/longhorn-test/vol-disk-1'

    def wait_for_disk_storage_available(client, node_name, disk_name, disk_path):
        for i in range(RETRY_COUNTS):
            node = client.by_id_node(node_name)
            disks = node.disks
            if len(disks) > 0 and disk_name in disks:
                free, _ = get_host_disk_size(disk_path)
                if disks[disk_name]["storageAvailable"] == free:
                    break
            time.sleep(RETRY_INTERVAL)
        assert len(disks) != 0
        assert disk_name in disks
>       assert disks[disk_name]["storageAvailable"] == free
E       AssertionError

common.py:2267: AssertionError
```

**Describe the items of the test development (DoD, definition of done) you'd like.**
- [x] fix test_node_umount_disk
- [x] fix test_node_disk_update

**Additional context**
- https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/394/testReport/junit/tests/test_node/test_node_umount_disk/

- https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/394/testReport/junit/tests/test_node/test_node_disk_update/

**Comment by khushboo-rancher** [comment]
With the PR  https://github.com/longhorn/longhorn-tests/pull/653, test `test_node_controller_sync_storage_available` will also get fixed.

**Comment by innobead** [comment]
Please close it if the daily run pass. Thank you.

**Comment by khushboo-rancher** [comment]
The nightly test is passing, good to close this issue.
