### ISSUE TITLE
[QUESTION] Problem with longhornio/longhorn-engine:v1.0.2 , its deploying   too much time !!

### ISSUE THREAD

**Issue by Pedrocho** [longhorn/longhorn#2731]
Hi EveryOne,

i need help with my longhorn -> The state is ->unable to create volume: unable to create volume registry-docker-250g: cannot create volume with image longhornio/longhorn-engine:v1.0.2: engine image ei-ee99999 (longhornio/longhorn-engine:v1.0.2) is not ready, it's deploying

how can I solve that? stays in that state for a long time ...

Please help me....

Many many thanks

**Comment by jenting** [comment]
Could you please follow the [question template](https://github.com/longhorn/longhorn/issues/new?assignees=&labels=kind%2Fquestion&template=question.md&title=%5BQUESTION%5D), at least we need the longhorn version related information. Thank you.

**Comment by Pedrocho** [comment]
hi jenting ,

 longhorn.io/v1beta1
 longhornio/longhorn-engine:v1.0.2

regards,

**Comment by jenting** [comment]
Could you please check the `engine-image` Pods running correctly and its log.
Also if possible, please attach the support bundle or email it longhorn-support-bundle@suse.com?

**Comment by Pedrocho** [comment]
hi jenting,

the pods its running but the state of engineimage is Deploying . The big question is -> If I delete the image of longhornio / longhorn-engine: v1.0.2 from the longhorm dashboard, do I break anything? I mean I could delete that image from the console and then be able to deploy it again, with this action I would get the image back to ready?

thanks.

**Comment by jenting** [comment]
If there is any volumes reference to the engine image, you can't delete it. Otherwise, it okay to delete and recreate it.

**Comment by Pedrocho** [comment]
I have 2 questions:

How do I know if there is any reference of volumes to the image of the engine?
So if I can't delete it, what can I do to get it back to the ready state?

**Comment by jenting** [comment]
I did not have Longhorn v1.1.1 at hand.
You should be available at Setting -> Engine Image (Reference Count).

**Comment by Pedrocho** [comment]
ohh sorry , i watch  this dates ,
Enging Image Detail :
Image:longhornio/longhorn-engine:v1.0.2
Status:Deploying
RefCount: 6

Regards

**Comment by cclhsu** [comment]
Hi! Could you try to get the daemonset and check if `engine-image-ei-xxxxx` are all running properly

```
kubectl get daemonset.apps -n longhorn-system -o wide
kubectl get pod -l longhorn.io/component=engine-image -n longhorn-system -o wide
```

Please check their describe, log, and event to see if there is any error.

**Comment by jenting** [comment]
@Pedrocho Is this issue still existed? If not, I'd prefer to close this issue.

**Comment by innobead** [comment]
Closing, feel free to reopen if this's still an issue.
