### ISSUE TITLE
[FEATURE] Automatically purge old unused snapshots

### ISSUE THREAD

**Issue by SvenC56** [longhorn/longhorn#2732]
**Question**

Hey, I am using Longhorn together with Kasten to provision PVCs (Longhorn) and do backups (Kasten). Kasten creates csi snapshots which result in a huge load of snapshots in Longhorn over time. After a week I could not create any more backups and in Longhorn I am presented with this warning:

```
Name: toomanysnapshots
Last Transition Time: 12 days ago
Message: Snapshots count is 249 over the warning threshold 100
Reason: TooManySnapshots
Status: True
```

Is there a possibility to automatically purge old unused snapshots? They are sent to S3 anyways, right? Otherwise they will bloat the filesystem over time.

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes version: 20.10.3
 - Node config
   - OS type and version Ubuntu 20.04 LTS
   - CPU per node: 32
   - Memory per node: 252GiB
   - Disk type: HDD
   - Network bandwidth and latency between the nodes: n/a
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Additional context**
n/a

**Comment by jenting** [comment]
Thanks for the feedback. Will Kasten delete the old CSI snapshots after the backup finished?

Currently, Longhorn would not automatically purge old unused snapshots through the CSI snapshot mechanism.
We could discuss it internally to check if it's doable.

**Comment by jenting** [comment]
cc @joshimoo any feedback?

**Comment by SvenC56** [comment]
> Thanks for the feedback. Will Kasten delete the old CSI snapshots after the backup finished?

This is what I found (https://docs.kasten.io/latest/install/storage.html#csi-snapshot-configuration):

> Setting deletionPolicy to Delete isn't sufficient either as some storage systems will force snapshot deletion if the associated volume is deleted (snapshot lifecycle is not independent of the volume). Similarly, it might be possible to force-delete snapshots through the storage array's native management interface. Enabling backups together with volume snapshots is therefore required for a durable backup.

> K10 creates a clone of the original VolumeSnapshotClass with the DeletionPolicy set to 'Retain'. When restoring a CSI VolumeSnapshot, an independent replica is created using this cloned class to avoid any accidental deletions of the underlying VolumeSnapshotContent.

> Currently, Longhorn would not automatically purge old unused snapshots through the CSI snapshot mechanism.
> We could discuss it internally to check if it's doable.

What is the normal way to delete multible snapshots at once? Using `lhexec` I can only delte one at a time?

**Comment by kompetenzlandkarte** [comment]
Hey I receive the same error. Is there a possibility to purge old **user generated** snapshots? I saw there is a cronjob for system generated ones.

How do I delete all snapshots via `lhexec`? Is there a handy script? `lhexec pvc-name snapshot purge` does not seem to work for me.

**Comment by joshimoo** [comment]
@kompetenzlandkarte You can write a script around there might be some user scripts on github/slack for this already.
If you do write a script around this, please feel free to share it :)
```
lhexec <volume> snapshot ls
lhexec <volume> snapshot rm <snapshot-id>
```

**Comment by kompetenzlandkarte** [comment]
I am no script pro but I am trying this

`delete-snapshots.sh`

```bash
#!/bin/bash
./lhexec $1 snapshot ls | grep "snapshot" -A1 | while read -r line; do ./lhexec $1 snapshot rm $(echo $line); done
```

Is failing with `Unable to use a TTY - input is not a terminal or the right kind of file`. Any idea how to fix this?

**Comment by joshimoo** [comment]
@kompetenzlandkarte you can also build something around the Python client, we use the same client for our e2e tests.
https://longhorn.io/docs/1.1.2/references/longhorn-client-python/
https://github.com/longhorn/longhorn-tests/tree/master/manager/integration

@yasker @innobead unfortunatly the lhexec script is setup to use an interactive tty for the exec command.
https://github.com/longhorn/longhorn/blob/85ab7c8d9d80e244aa2f78ef1e5a1ec83b909374/scripts/lhexec#L48
https://trstringer.com/kubectl-tty-issues/

@kompetenzlandkarte you can remove the`-it` from the kubectl exec in the lhexec.sh script that should allow for usage from a shell script. Feel free to open up a PR with your changes :)

**Comment by kompetenzlandkarte** [comment]
> @kompetenzlandkarte you can remove the-it from the kubectl exec in the lhexec.sh script

This was the issue. Thank you for the tip!

This is my bash script now:

```bash
#!/bin/bash
echo "delete snapshots for pvc $1"

./lhexec $1 snapshot ls | grep "snapshot" -A1 | while read -r line; do echo "delete snapshot $line" && ./lhexec $1 snapshot rm $line; done

echo "now purging the snapshots for pvc $1"

./lhexec $1 snapshot purge
```

However this script is pretty slow due to iterating every snapshot at a time (~2-5s per snapshot).

**Comment by ikaruswill** [comment]
Hey guys, I've been running into the same problem with everyone here since longhorn 1.0.0-beta and honestly I'm really glad that there's a Python client in the works now.

Nonetheless, I just wrote a script an hour back to take care of all the 'stale' and 'orphaned' snapshots that were not longer tracked by any retention policy (perhaps due to having set a new backup schedule in bulk). 

It's worked out great for me. Figured I'd share it here as well.


```python
# Cleanup Longhorn snapshots script by ikaruswill
# ==============
#
# Definitions:
# - Orphaned snapshots: Snapshots created by backup schedules that no longer exist.
# - Stale snapshots: Snapshots that are over n days old
#
# Variables:
# - delete_strings: Delete snapshots that contain any of the strings
#                   To locate orphaned snapshots.
#                   Set to your old backup schedule names
# - delete_age_days: Delete snapshots that are above the specified age in days
#                    To locate stale snapshots. 
#                    Set to your oldest possible snapshot (i.e. I have a weekly backup, with Retain = 4, so the oldest snapshot should be 28 days)
#
# Usage:
# 1. Run `kubectl port-forward -n longhorn-system services/longhorn-frontend 8080:http`
# 2. python cleanup-snapshots.py
#
# Prerequisites:
# 1. longhorn.py from: https://raw.githubusercontent.com/longhorn/longhorn-tests/master/manager/integration/tests/longhorn.py
# 2. requests library from: `pip install requests`

import longhorn
import datetime


# Constants
date_format = '%Y-%m-%dT%H:%M:%SZ'
mib_conversion_factor = 1 / 1024 / 1024
current_date = datetime.datetime.now()

longhorn_url = 'http://localhost:8080/v1'

# Variables; change according to your needs
delete_strings = ['c-6fffho', 'c-b8sdpg']
delete_age_days = 30

def delete_snapshot(volume, snapshot, reason):
    print('Deleting {reason} snapshot {name} created on {created} with size {size:.1f} MiB'.format(
                name=snapshot.name, 
                reason=reason,
                created=datetime.datetime.strptime(snapshot.created, date_format).strftime('%Y-%m-%d'),
                size=int(snapshot.size) * mib_conversion_factor
            ))
    try:
        volume.snapshotDelete(name=snapshot.name)
    except longhorn.ApiError as e:
        print('Failed to delete snapshot due to API error: {}'.format(e))
        


def process_snapshot(volume, snapshot):
    for delete_string in delete_strings:
        if delete_string in snapshot.name:
            delete_snapshot(volume, snapshot, 'orphaned')
            return True
    snapshot_date = datetime.datetime.strptime(snapshot.created, date_format)
    if (current_date - snapshot_date).days > 30:
        delete_snapshot(volume, snapshot, 'stale')
        return True
    print('Ignoring snapshot: {}'.format(snapshot.name))
    return False


def process_volume(volume):
    print('Processing volume: {}'.format(volume.name))
    try:
        snapshots = volume.snapshotList()
    except AttributeError as e:
        print('Ignoring volume due to AttributeError: {}'.format(e))
        return
    print('Number of snapshots: {}'.format(len(snapshots)))
    deleted_count = 0
    for snapshot in snapshots:
        snapshot_is_deleted = process_snapshot(volume, snapshot)
        if snapshot_is_deleted:
            deleted_count += 1
            
    if deleted_count > 0:    
        print('Purging snapshots...')
        volume.snapshotPurge()

    print('Finished processing volume {}'.format(volume.name))
    print('Deleted {} snapshots'.format(deleted_count))
    volume = client.by_id_volume(id=volume.id)
    print('---')


def process_cluster(client):
    volumes = client.list_volume()
    print('Starting volume snapshot cleanup')
    print('Number of volumes: {}'.format(len(volumes)))

    for i, volume in enumerate(volumes):
        print('Progress: {:.1f}% ({}/{})'.format(
          i / len(volumes) * 100,
          i,
          len(volumes),
        ))
        process_volume(volume)
    
    print('Finished volume snapshot cleanup')


if __name__ == '__main__':
    client = longhorn.Client(url=longhorn_url)
    process_cluster(client)
```

**Comment by innobead** [comment]
I do think we can just leverage recurring jobs here to clean snapshots regularly. cc @PhanLe1010

**Comment by PhanLe1010** [comment]
@innobead The recurring jobs only clean up the snapshot they created as well as the doing the system snapshot purge. If the snapshot is created by something else (i.e user, volume clone, csi snapshot, etc, ...) the snapshot won't be cleaned by the recurring jobs. 

I think [the script](https://github.com/longhorn/longhorn/issues/2732#issuecomment-896205929) provided by @ikaruswill is the current workaround. I am thinking if we should add one more API to cleanup snapshot for a volume then the user can just click it

**Comment by larssb** [comment]
Is there any progress in this one. It's a rather major challenge at times. We can have Longhorn committed storage space issues quite fast. As space fills up over time. So we kinda need a cleanup mechanism where we can set the lifetime of snapshots.

Status is still ... use that script ( https://github.com/longhorn/longhorn/issues/2732#issuecomment-896205929 ) ??

**Comment by innobead** [comment]
This is related to #3836
