### ISSUE TITLE
[BUG] RWX volume attached in maintenance mode to do a backup, not option to detach.

### ISSUE THREAD

**Issue by cocampbe** [longhorn/longhorn#2733]
**Describe the bug**
RWX volume attached in maintenance mode to do a backup, not option to detach.

**To Reproduce**
1. Create a RWX volume
2. Use it
3. Scale down your deployment/sts so the volume detaches
4. Go to the longhorn UI, click attach, choose a node, check maintance. 
5. Take a backup (optional).
6. Try to detach. ( Option is grayed out.)

**Expected behavior**
Step 6 above should work.

**Environment:**
 - Longhorn version: 1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 3 
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: OL7.9
   - CPU per node: 8
   - Memory per node: 32
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: n/a
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 19

**Comment by cocampbe** [comment]
I know RWX are experimental.

**Comment by khushboo-rancher** [comment]
@cocampbe This issue is fixed in version v1.1.1

**Comment by cocampbe** [comment]
> v1.1.1

I had a feeling. I just could not remember. Thanks!

**Comment by khushboo-rancher** [comment]
I'm closing this issue for now, feel free to reopen this if you see problem again.
Thank you @cocampbe
