### ISSUE TITLE
[FEATURE]  WebSocket to support updating BackupVolume and Backup changes

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#2740]
**Is your feature request related to a problem? Please describe.**

After #1761 is finished, add WebSocket to support updating BackupVolume and Backup changes.
This makes the GUI user experience more intuitive, and the operation of creating backup _or_ deleting backup will be displayed immediately without refreshing the page. Therefore, the user does not need to refresh the browser anymore.

**Describe the solution you'd like**

Add WebSocket notification BackupVolume and Backup changes.

**Describe alternatives you've considered**

The user manually refreshes the browser to get up-to-date information.

**Additional context**

**Comment by innobead** [comment]
cc @c3y1huang

**Comment by jenting** [comment]
cc @smallteeths

**Comment by jenting** [comment]
Add WebSocket support on
- Setting page, display the BackupTarget is unavailable if `spec.backupTargetURL=="" && status.available=false`.
- Backup page:
  - display the BackupTarget is unavailable if  `spec.backupTargetURL=="" && status.available=false`.
  - updates the BackupVolume when there is a change on `metadata.name` and `status fields`.
  - updates the Backups when there is a change on `metadata.name` and `status fields` of specific BackupVolume.

**Comment by jenting** [comment]
Link issue https://github.com/longhorn/longhorn/issues/2887 which supports the reason of _why_ the backup target is unavailable at the moment.

**Comment by jenting** [comment]
After discussion with @smallteeths, prefer to use the HTTP endpoint to fetch the BackupTarget status.
So this issue focus only on the WebSocket changes on BackupVolume and Backup which isn't a **must** item in v1.2.0 cc @innobead

**Comment by jenting** [comment]
1. Created a new backup, make sure the backup volume and backup got created/updated.
2. Delete a single backup, make sure the backup be removed.
3. Delete all backups, make sure all the backups and this backup volume be removed.
4. Make sure all the icons of the backup works correctly (Delete/Restore/Get URL)
5. Make sure all the icons of the backup volume works correctly (Restore the latest backup/Restore DR volume/Delete all backups/Get backing image info)

**Comment by kaxing** [comment]
Validating in progress, testing with master-head images(2021-08-30)

Using volume name: backup-test for testing,

- UI under `backup/backup-test?field=volumeName&keyword=backup-test` will now reflect the delete action within the page shortly without refresh.
  - Also using Create Backup button or backup create from volume detail page `#/volume/backup-test` the newly created backups will update to the backup detail page without refresh as well.

Under checking items:
- Deleting backups from `#/volume/backup-test` won't update in backup detail page
- On each backup volume detail page they will query all backups from all volumes as observing `v1/ws/1s/backups`

**Comment by jenting** [comment]
> * On each backup volume detail page they will query all backups from all volumes as observing `v1/ws/1s/backups`

This is the current design of WebSocket endpoint. We haven't found a way to parse the volume name from the websocket endpoint

**Comment by kaxing** [comment]
Validation: **PASSED**
with master-head images(20210803, ui:b0aff7a)

This new changed allows Backup Page and the Backup Detail for ech volume update backup status withotu refresh the page. Additionally deleting via kubectl command will also reflect to the Backup detail page via WebSocket Update. Commands for future reference:
```
$kubectl delete backups.longhorn.io/backup-bad85a99254545c3 -n longhorn-system
```
@jenting Thanks for clarify my questions and the test steps.
