### ISSUE TITLE
[BUG] [v1.1.2-rc1] Physical node down: deployment pod will not created after exceeding terminationGracePeriodSeconds

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#2743]
**Describe the bug**
same as issue title

**To Reproduce**
Volume Attachment Recovery Policy: Immediate:

1. Have a workload deployed using longhorn volume.
2. change the terminationGracePeriodSeconds: 480 in the yaml of the workload.
3. Power down the node where the pod is attached on.
4. After 15 min, old deployment pod is still in running state, and new pods is not created
5. the volume is able to attach/mount and workload come up in about 30 seconds.
6. data is accessible after the pod comes up active.

Ref: https://longhorn.github.io/longhorn-tests/manual/pre-release/node/auto-detach/deployment/

**Expected behavior**
In step 4: The replacement pod is created after 5 minutes from when the original pod goes into Terminating state. And this replacement pod is in ContainerCreating state.
**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: v1.1.2-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): yaml
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: Ubuntu 18.04
   - CPU per node: 4
   - Memory per node: 8 GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): DO
 - Number of Longhorn volumes in the cluster: 1

**Additional context**

**Comment by innobead** [comment]
https://github.com/longhorn/longhorn/issues/2060 was introduced in 1.1.2, so the related test cases should be adjusted/removed accordingly. 

ref: https://longhorn.github.io/longhorn-tests/manual/pre-release/node/auto-detach
