### ISSUE TITLE
[BUG] Failed to mount pods when a customized kubelet root directory is set

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2746]
**Describe the bug**
When using a customized kubelet root directory, Longhorn cannot mount volumes for pods.

**To Reproduce**
1. Launch a cluster with a customized kubelet root directory. e.g., k3s
2. Deploy Longhorn with the customized kubelet root directory
3. Launch a pod and the PVC using StorageClass. ==> The volume is attached but it cannot be mounted to the pod

**Expected behavior**
Mount should succeed and the pod should be running

**Log**

**Environment:**
 - Longhorn version: v1.1.1

**Additional context**
- This issue is caused by the wrong volume mounting in the CSI plugin deployment. This in-container directory should be the same as the host path rather than the fix value /var/lib/kubelet/plugins/kubernetes.io/csi: https://github.com/longhorn/longhorn-manager/blob/ac065a8deb96193ffec142bcc7e7345615b57b8d/csi/deployment.go#L437
- This bug is already fixed by https://github.com/longhorn/longhorn-manager/pull/927.

**Comment by innobead** [comment]
ref: 
- https://longhorn.io/kb/troubleshooting-none-standard-kubelet-dir/
- https://github.com/longhorn/longhorn/issues/2537

**Comment by shuo-wu** [comment]
@innobead We need to add a pre-release manual test for this issue.

**Comment by innobead** [comment]
@kaxing Please help verify. Thanks.

**Comment by kaxing** [comment]
Validation: **PASSED**

With master-head image (20210831, post rc2), tested on local environment with k3s by passing additional kubelet parameter : `--kubelet-arg "--root-dir=/var/lib/longhorn-test` And environment variable for `longhorn-driver-deployer`:
```
kind: Deployment
metadata:
...
  name: longhorn-driver-deployer
          - name: KUBELET_ROOT_DIR
            value: /var/lib/longhorn-test
 ...
 ```
