### ISSUE TITLE
[TEST] fix rwx test case unstable issue

### ISSUE THREAD

**Issue by cclhsu** [longhorn/longhorn#2748]
**What's the test to develop? Please describe.**
Fix RWX test case unstable issue as in

- https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/399/#showFailuresLink
- https://ci.longhorn.io/job/public/job/v1.1.2/job/v1.1.2-longhorn-tests-ubuntu-amd64/43/#showFailuresLink

```
tests.test_rwx.test_rwx_with_statefulset_multi_pods
tests.test_rwx.test_rwx_with_statefulset_multi_pods
tests.test_rwx.test_rwx_multi_statefulset_with_same_pvc
tests.test_rwx.test_rwx_multi_statefulset_with_same_pvc
tests.test_rwx.test_rwx_parallel_writing
tests.test_rwx.test_rwx_statefulset_scale_down_up
tests.test_rwx.test_rwx_statefulset_scale_down_up
tests.test_rwx.test_rwx_delete_share_manager_pod
tests.test_rwx.test_rwx_deployment_with_multi_pods
tests.test_rwx.test_restore_rwo_volume_to_rwx[s3]
tests.test_rwx.test_restore_rwo_volume_to_rwx[nfs]
```

**Describe the items of the test development (DoD, definition of done) you'd like.**
- [ ] <use check box for each item>

**Additional context**
Add any other context or screenshots about the test request here.

**Comment by innobead** [comment]
cc @khushboo-rancher @meldafrawi @kaxing

**Comment by innobead** [comment]
Let's watch the CI results before closing this.

**Comment by innobead** [comment]
Reopening, because this flaky problem still exists even after #3193 is fixed. @chanow816 will work on it.

**Comment by chanow816** [comment]
Not happened in recent build  
https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/496/
https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/497/
