### ISSUE TITLE
[BUG] After changing snapshot CronJob "retain" flag, old snapshots are not deleted

### ISSUE THREAD

**Issue by michael-sayapin** [longhorn/longhorn#2751]
**Describe the bug**
I mistakenly provisioned a StorageClass with retain: 30. After changing it to retain: 3 and going over all PV's CronJobs manually changing retain to 3, I still see 30 snapshots in `ls -lah /path/to/longhorn/replicas/pvc-xxx/`.

**To Reproduce**
1. Create StorageClass with cron specs with retain: 30
2. Provision a bunch of PVC/PVs
3. Delete and recreate StorageClass with retain: 3
4. Manually change every CronJob to 3

**Expected behavior**
Unnecessary snapshots are cleaned up.

**Environment:**
 - Longhorn version: 1.1.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s 1.22.1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 8
   - Memory per node: 32G
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 7 Gbps
 - Underlying Infrastructure: k3s on Tencent Cloud
 - Number of Longhorn volumes in the cluster: 200+

**Comment by c3y1huang** [comment]
If I understand correctly, you've updated the retain flag in `kubectl -n longhorn-system edit cronjob/pvc-xxx` ? If that is the case, then the Longhorn manager volume controller doesn't get notified of the changes. Can you try to update the retain value via the UI volume page to see if that makes a difference?

**Comment by michael-sayapin** [comment]
Thank you @c3y1huang ! Yes, it seems so. However, and maybe I should file it as a separate bug, recurringJobs added via a StorageClass do not show up in Longhorn UI.

**Comment by c3y1huang** [comment]
Not sure if I understand your case,
1. Updated recurring jobs not reflecting existing volume: The recurring job is only used during volume creation.
2. Creating volume via UI does not contain Storage Class recurring job: [Here](https://github.com/longhorn/longhorn/issues/919#issuecomment-560558487) are some explanations about the recurring job with storage class and volume that might help to clarify. 

If they do not cover your case then do file a separate bug.

**Comment by jenting** [comment]
> manually changing retain to 3, I still see 30 snapshots in `ls -lah /path/to/longhorn/replicas/pvc-xxx/.`

Had you waited a while to check the recurring job start to run and finished?

**Comment by jenting** [comment]
Out of activity, and we had changed the design of the recurring job starting from Longhorn v1.2.0.
Please refer to the longhorn doc to see what's changed.

Close this issue, feel free to reopen a new discussion _or_ issue once you encounter any further question/issue, thank you.
