### ISSUE TITLE
[BUG] Backup page goes blank after restore form is accepted

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2754]
**Describe the bug**
The backup --> volume page goes blank if user select a backup and accept the form.

**To Reproduce**
1. Go to the backup page.
2. Click on a volume name listed there.
3. The page will display the backups.
4. Click on the menu and select the restore backup.
5. Fill out the details and accept the form.
6. The page reloads and becomes blank.

<img width="1781" alt="Screen Shot 2021-06-30 at 1 50 10 PM" src="https://user-images.githubusercontent.com/60111667/124030472-1337ef80-d9ab-11eb-875b-bfe2ef1e3f92.png">

**Expected behavior**
The page should display the backups.

**Environment:**
 - Longhorn version: v1.1.2-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

**Comment by kaxing** [comment]
The same situation will happen when "Create Disaster Recovery Volume" within the backup page from the dropdown menu.

**Comment by kaxing** [comment]
Validation - **Passed**

Testing against to master-head(0701) + wangsiye/longhorn-ui:5dc0448 and v1.1.2-rc1 +wangsiye/longhorn-ui:5dc0448

Both restoring backup and creating Disaster Backup Volume from each volume backup page won't return blank page.

**Comment by khushboo-rancher** [comment]
@kaxing Thank you for validating this with dev image. 

We should validate this with v1.1.2-head (once the pr is merged) before closing this.
