### ISSUE TITLE
[TASK] Raise minimal Longhorn supported Kubernetes version for v1.2.0

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2755]
**What's the task? Please describe.**
For every minor release, we need to reevaluate the supported Kubernetes version.

According to https://kubernetes.io/releases/version-skew-policy/ , we might able to raise the minimal requirement for Longhorn v1.2.0 to Kubernetes v1.18, which was released on Apr 23rd, 2020.

**Comment by innobead** [comment]
ref: https://github.com/longhorn/longhorn/issues/2757

**Comment by innobead** [comment]
Closing, let's tackle this in #2757.
