### ISSUE TITLE
[FEATURE] Support bundle enhancement

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2759]
We will replace the Longhorn support bundle mechanism with a general-purpose support bundle kit (WIP https://github.com/rancher/support-bundle-kit) which will support:
1. Gather YAML and logs (including previous pod log) from specified namespaces in the Kubernetes cluster
    * including automatically collect all known CRs in the namespace
2. Generate the support bundle either using binary or as a service to integrate with existing applications.
3. Gather system log on each node in the support bundle.
4. Make it easier for the user to analyze the support bundle by start a mocked Kubernetes API server with imported YAMLs and logs.

**Comment by innobead** [comment]
@keithalucas will not work on this item for now.

**Comment by yasker** [comment]
Move to v1.2.1 since the code change is too big for v1.2.0 after RC.

**Comment by yasker** [comment]
Update on this: https://github.com/rancher/support-bundle-kit now features `simulator` command to mock a Kubernetes cluster, making it extremely easy to look into the k8s environment for troubleshooting.

**Comment by innobead** [comment]
Assigned to @joshimoo who is working on the support bundle related tasks.

**Comment by innobead** [comment]
@chriscchien because support-bundle-kit didn't be verified on arm64 before, so needs to ensure the tests run well on arm64 as well because arm64 is GA in 1.4.0. 

P.S. @c3y1huang has implemented e2e test cases as well, so you can verify them too. 

cc @longhorn/qa

**Comment by chriscchien** [comment]
Hi @c3y1huang ,

I tried to download support bundle from ARM64 ubuntu20.04 machine, but the support bundle manager faced CrashLoopBackOff state, below are information for your reference, thank you.

```
root@ip-172-31-29-108:/home/ubuntu# cat /proc/version
Linux version 5.15.0-1019-aws (buildd@bos02-arm64-025) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #23~20.04.1-Ubuntu SMP Thu Aug 18 03:23:03 UTC 2022
root@ip-172-31-29-108:/home/ubuntu# 
root@ip-172-31-29-108:/home/ubuntu# k get pods | grep support
longhorn-support-bundle-manager-support-bundle-2022-11-30tnn79g   0/1     CrashLoopBackOff   6 (2m46s ago)   8m34s
```
```
root@ip-172-31-29-108:/home/ubuntu# k logs longhorn-support-bundle-manager-support-bundle-2022-11-30tnn79g
+ exec tini -- /usr/bin/support-bundle-kit manager
/usr/bin/entrypoint.sh: line 4: /usr/bin/tini: cannot execute binary file: Exec format error
/usr/bin/entrypoint.sh: line 4: /usr/bin/tini: Success
```

<details>
  <summary>pod description</summary>

```
root@ip-172-31-29-108:/home/ubuntu# k describe pod longhorn-support-bundle-manager-support-bundle-2022-11-30tnn79g
Name:             longhorn-support-bundle-manager-support-bundle-2022-11-30tnn79g
Namespace:        longhorn-system
Priority:         0
Service Account:  longhorn-support-bundle
Node:             ip-172-31-24-189/172.31.24.189
Start Time:       Wed, 30 Nov 2022 07:31:56 +0000
Labels:           app=support-bundle-manager
                  pod-template-hash=64b49fc4fb
                  rancher/supportbundle=support-bundle-2022-11-30t07-31-56z
Annotations:      <none>
Status:           Running
IP:               10.42.1.13
IPs:
  IP:           10.42.1.13
Controlled By:  ReplicaSet/longhorn-support-bundle-manager-support-bundle-2022-11-30t07-31-56z-64b49fc4fb
Containers:
  manager:
    Container ID:  containerd://98864b01d33d8d66a1c7b1f01302838c277ab28045c9b2e7f973670a4e21cdff
    Image:         longhornio/support-bundle-kit:v0.0.14
    Image ID:      docker.io/longhornio/support-bundle-kit@sha256:de5bd938e03b6838b0c79356205f82b52a4190b2d2339dd12e6cf71c80f47588
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      /usr/bin/support-bundle-kit
      manager
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 30 Nov 2022 07:37:44 +0000
      Finished:     Wed, 30 Nov 2022 07:37:44 +0000
    Ready:          False
    Restart Count:  6
    Environment:
      POD_NAMESPACE:                     longhorn-system (v1:metadata.namespace)
      SUPPORT_BUNDLE_TARGET_NAMESPACES:  longhorn-system
      SUPPORT_BUNDLE_NAME:               support-bundle-2022-11-30t07-31-56z
      SUPPORT_BUNDLE_DEBUG:              true
      SUPPORT_BUNDLE_MANAGER_POD_IP:      (v1:status.podIP)
      SUPPORT_BUNDLE_IMAGE:              longhornio/support-bundle-kit:v0.0.14
      SUPPORT_BUNDLE_IMAGE_PULL_POLICY:  Always
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-j52pl (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-j52pl:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  10m                  default-scheduler  Successfully assigned longhorn-system/longhorn-support-bundle-manager-support-bundle-2022-11-30tnn79g to ip-172-31-24-189
  Normal   Pulled     10m                  kubelet            Successfully pulled image "longhornio/support-bundle-kit:v0.0.14" in 5.548233861s
  Normal   Pulled     10m                  kubelet            Successfully pulled image "longhornio/support-bundle-kit:v0.0.14" in 129.27153ms
  Normal   Pulled     10m                  kubelet            Successfully pulled image "longhornio/support-bundle-kit:v0.0.14" in 102.403204ms
  Normal   Pulled     9m43s                kubelet            Successfully pulled image "longhornio/support-bundle-kit:v0.0.14" in 151.074989ms
  Normal   Created    9m43s (x4 over 10m)  kubelet            Created container manager
  Normal   Started    9m43s (x4 over 10m)  kubelet            Started container manager
  Normal   Pulling    9m1s (x5 over 10m)   kubelet            Pulling image "longhornio/support-bundle-kit:v0.0.14"
  Normal   Pulled     9m1s                 kubelet            Successfully pulled image "longhornio/support-bundle-kit:v0.0.14" in 144.892805ms
  Warning  BackOff    36s (x48 over 10m)   kubelet            Back-off restarting failed container
```
</details>

**Comment by c3y1huang** [comment]
@chriscchien , arm64 needs to wait for https://github.com/longhorn/longhorn/pull/4972.

**Comment by c3y1huang** [comment]
@chriscchien arm64 is ready for testing.

**Comment by chriscchien** [comment]
Verified in longhorn master `0e56cd` on both amd64 and arm64 cluster with ubuntu20.04 installed
Result **Pass**

Tested by test [steps](https://github.com/longhorn/longhorn/blob/master/enhancements/20221109-support-bundle-enhancement.md), all steps passed logged below

1. Test support bundle generation should be successful
     - Support budle can download successfully then extract correctly  from amd64/arm64 cluster, 

2. Test support bundle should be cleaned up after download.
   - Support bundle deployment cleaned after download complete
3. Test support bundle should retain when generation failed.
   -  Delete support bundle manager pod while generating support bundle will cause support bundle in `"state": "Error"`, the new replaced support bundle manager pod will remain in cluster.
4. Test support bundle should generate when the cluster has an existing SupportBundle in an error state.
   - If failed support bundle number not reach setting `SupportBundle Failed History Limit`,  new support bundle can download successsfully.
   - Otherwise support bundle can not download.
 ```
failed to create SupportBundle: admission webhook "validator.longhorn.io" denied the request: exceeded support-bundle-failed-history-limit setting value 1, please increase the limit or remove some failed SupportBundles. You can also set the limit to 0 to automatically clean up all the failed SupportBundles
```

5. Test support bundle should purge when support bundle failed history limit is set to 0.
   - Pod remain in test item 3 all cleaned up after set failed history limit set to 0.

6. Test support bundle cluster simulation.
   -  Support bundle can load successfully by[ support bundle kit](https://github.com/rancher/support-bundle-kit/blob/master/docs/quickstart.md)
 
![Screenshot from 2022-12-02 11-31-09](https://user-images.githubusercontent.com/73337386/205208955-37e3ce7e-e17c-4063-bf03-9a9cfdeaeb3e.png)
