### ISSUE TITLE
[BUG] Replica rebuild fail with context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by alkmim** [longhorn/longhorn#2762]
**Question** 

I created a 100GB volume with 3 replicas. Right after creation, I added 20GB of data to it. For some reason, I have only 1 healthy replica. Looking at the longhorn UI, it always shows a replica doing rebuild, but it always fails in the middle. Below are some logs that might be helpful. I also have a 2GB volume with 3 replicas and it is working fine. 

- Replica  (source/healthy)
```
# kubectl logs -f instance-manager-r-92cd6def -n longhorn-system
[...]
[volume-r-ec113baa] time="2021-07-02T05:44:03Z" level=info msg="Sending file volume-snap-f0beb2fc-2f13-4021-bc6a-2f2f4aabb0c9.img to 10.233.108.7:10006"
time="2021-07-02T05:44:03Z" level=info msg="source file size: 107374182400, setting up directIO: true"
[volume-r-ec113baa] time="2021-07-02T05:54:12Z" level=error msg="writeData for batchInterval: [ 4668128: 4668160]( 32) failed, err: writeData failed, err: Post \"http://10.233.108.7:10006/v1-ssync/writeData?begin=19120652288&end=19120783360\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time="2021-07-02T05:54:12Z" level=error msg="syncFileContent failed: syncDataInterval [ 4651008: 4673536](22528) failed, err: writeData failed, err: Post \"http://10.233.108.7:10006/v1-ssync/writeData?begin=19120652288&end=19120783360\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

- Replica  (destination/rebuilding)

```
# kubectl logs -f instance-manager-r-192f695e -n longhorn-system
[...]
[volume-r-cb38f33c] time="2021-07-02T05:44:05Z" level=info msg="Running ssync server for file volume-snap-f0beb2fc-2f13-4021-bc6a-2f2f4aabb0c9.img at port 10006"
time="2021-07-02T05:44:05Z" level=info msg="Creating Ssync service"
[volume-r-cb38f33c] time="2021-07-02T05:44:05Z" level=info msg="open: receiving fileSize: 107374182400, setting up directIO: true"
[volume-r-cb38f33c] time="2021-07-02T05:44:05Z" level=info msg="Ssync server opened and ready"
[volume-r-cb38f33c] time="2021-07-02T05:44:05Z" level=info msg="Closing ssync server"
[volume-r-cb38f33c] time="2021-07-02T05:44:05Z" level=info msg="Done running ssync server for file volume-snap-be46f111-c1b4-451b-9a6f-7124cb4656e6.img.meta at port 10005"
[volume-r-cb38f33c] time="2021-07-02T05:54:14Z" level=info msg="Closing ssync server"
[volume-r-cb38f33c] time="2021-07-02T05:54:14Z" level=info msg="Done running ssync server for file volume-snap-f0beb2fc-2f13-4021-bc6a-2f2f4aabb0c9.img at port 10006"
time="2021-07-02T05:54:14Z" level=error msg="Sync agent gRPC server failed to rebuild replica/sync files: replica tcp://10.233.95.9:10000 failed to send file volume-snap-f0beb2fc-2f13-4021-bc6a-2f2f4aabb0c9.img to 10.233.108.7:10006: failed to send file volume-snap-f0beb2fc-2f13-4021-bc6a-2f2f4aabb0c9.img to 10.233.108.7:10006: rpc error: code = Unknown desc = syncDataInterval [ 4651008: 4673536](22528) failed, err: writeData failed, err: Post \"http://10.233.108.7:10006/v1-ssync/writeData?begin=19120652288&end=19120783360\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
ERROR: 2021/07/02 05:54:14 grpc: server failed to encode response:  rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil
[volume-r-cb38f33c] time="2021-07-02T05:54:14Z" level=info msg="Closing volume"
```

- Instance Manager

```
# kubectl logs -f -n longhorn-system  instance-manager-e-3882fa60
[...]
[volume-e-ba6f199c] time="2021-07-02T05:43:34Z" level=info msg="Set revision counter of 10.233.108.7:10000 to : 0"
[volume-e-ba6f199c] time="2021-07-02T05:43:34Z" level=info msg="Set backend tcp://10.233.108.7:10000 revision counter to 0"
[volume-e-ba6f199c] time="2021-07-02T05:43:34Z" level=info msg="Synchronizing volume-head-003.img.meta to volume-head-001.img.meta@10.233.108.7:10003"
[volume-e-ba6f199c] time="2021-07-02T05:43:34Z" level=info msg="Done synchronizing volume-head-003.img.meta to volume-head-001.img.meta@10.233.108.7:10003"
[volume-e-ba6f199c] time="2021-07-02T05:54:12Z" level=info msg="Removing backend: tcp://10.233.108.7:10000"
[volume-e-ba6f199c] time="2021-07-02T05:54:12Z" level=info msg="Closing: 10.233.108.7:10000"
[volume-e-ba6f199c] time="2021-07-02T05:54:13Z" level=error msg="Error reading from wire: EOF"
[volume-e-ba6f199c] time="2021-07-02T05:54:14Z" level=error msg="Backend tcp://10.233.108.7:10000 monitoring failed, mark as ERR: EOF"
time="2021-07-02T05:54:14Z" level=info msg="Monitoring stopped tcp://10.233.108.7:10000"
[volume-e-ba6f199c] time="2021-07-02T05:54:15Z" level=info msg="Connecting to remote: 10.233.105.5:10000"
[volume-e-ba6f199c] time="2021-07-02T05:54:15Z" level=info msg="Opening: 10.233.105.5:10000"
[volume-e-ba6f199c] time="2021-07-02T05:54:15Z" level=info msg="Starting to snapshot: 10.233.95.9:10000 41f30916-84d5-4ee7-bd83-8cd6bea18749 UserCreated false Created at 2021-07-02T05:54:15Z, Labels map[]"
[volume-e-ba6f199c] time="2021-07-02T05:54:15Z" level=info msg="Finished to snapshot: 10.233.95.9:10000 41f30916-84d5-4ee7-bd83-8cd6bea18749 UserCreated false Created at 2021-07-02T05:54:15Z, Labels map[]"
[volume-e-ba6f199c] time="2021-07-02T05:54:15Z" level=info msg="Starting to snapshot: 10.233.105.5:10000 41f30916-84d5-4ee7-bd83-8cd6bea18749 UserCreated false Created at 2021-07-02T05:54:15Z, Labels map[]"
[volume-e-ba6f199c] time="2021-07-02T05:54:15Z" level=info msg="Finished to snapshot: 10.233.105.5:10000 41f30916-84d5-4ee7-bd83-8cd6bea18749 UserCreated false Created at 2021-07-02T05:54:15Z, Labels map[]"
time="2021-07-02T05:54:15Z" level=info msg="Adding backend: tcp://10.233.105.5:10000"
time="2021-07-02T05:54:15Z" level=info msg="Start monitoring tcp://10.233.105.5:10000"
[volume-e-ba6f199c] time="2021-07-02T05:54:15Z" level=info msg="Set revision counter of 10.233.105.5:10000 to : 0"
[volume-e-ba6f199c] time="2021-07-02T05:54:15Z" level=info msg="Set backend tcp://10.233.105.5:10000 revision counter to 0"
[volume-e-ba6f199c] time="2021-07-02T05:54:15Z" level=info msg="Synchronizing volume-head-004.img.meta to volume-head-001.img.meta@10.233.105.5:10003"
[volume-e-ba6f199c] time="2021-07-02T05:54:15Z" level=info msg="Done synchronizing volume-head-004.img.meta to volume-head-001.img.meta@10.233.105.5:10003"
```

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes version: 1.21
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Can you please provide me some direction on how to investigate this kind of issue?**

Thanks!

**Comment by c3y1huang** [comment]
> Can you please provide me some direction on how to investigate this kind of issue?

@alkmim there are some discussions in https://github.com/longhorn/longhorn/issues/2070 , do they look similar to your case? And also [Minimal Resource requirements](https://longhorn.io/blog/longhorn-v1.1.0/#minimal-resource-requirements) might be useful.

Another option is to provide us more info about your cluster environment and support bundle so we can do more investigation.
```
**Environment:**
 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
```
You can attach the support bundle here or send it to longhorn-support-bundle@Suse.com with the issue number.

**Comment by PhanLe1010** [comment]
Received support bundle over mail

**Comment by alkmim** [comment]
Hello @PhanLe1010 

Sorry for taking long to response. So, given the timeout issue, I believe that could be caused by some congestion in the network. My question now is, is there a way to increase the timeout or add a retry for the failed sync? Whenever a sync failed, it could retry instead of restarting the replication process again.

**Comment by PhanLe1010** [comment]
@alkmim 

Can you send us a support bundle to `longhorn-support-bundle@rancher.com` ? You can generate a support bundle by going to Longhorn UI and click on the link at the bottom of the page. We want to verify the root cause of the issue before putting the fix for this issue to the plan

**Comment by alkmim** [comment]
Hello @PhanLe1010 . I am sorry, but I cannot since I do not know what kind of information will be included in the bundle. I cannot have all the details of the system. But considering my setup, it makes sense that some operations can have a higher latency and timeout. That being said, is there a way to increase the timeout or add a retry for the failed sync?

**Comment by jenting** [comment]
@alkmim 
Generally, it contains the information managed by Longhorn only. (Longhorn pods log and Longhorn CRDs).
It'd be helpful for us to analyze it. Thank you.

**Comment by alkmim** [comment]
Is there a way I can analyze the logs before they are sent to Longhorn?

**Comment by joshimoo** [comment]
@alkmim yes, just create the support bundle then you can extract the .zip archive, to look at all the files that are included as well as their content.
![image](https://user-images.githubusercontent.com/1287163/127843828-047d6968-b109-4f03-8b15-1cd8b039fd27.png)

**Comment by jenting** [comment]
We did some improvement on the slow disk/network from v1.2.0, you could consider upgrading the Longhorn to the latest version to see if the replica rebuilding still failed in your case.

**Comment by alkmim** [comment]
Hi @jenting . 

Thanks a lot for the update on this. I actually migrated to use drbd, but I am happy to try again longhorn since it is much easier to set up and maintain. 

Do you know the improvements made on the slow disk or have a list describing them?

**Comment by jenting** [comment]
You could check it in detail #2206 and #2882

**Comment by alkmim** [comment]
Interesting. This could actually solve my issues. I am using spinning disks and the network/disk can get overloaded sometimes.

**Comment by alkmim** [comment]
Was there any change in the replica/engine/volume object specs in kubernetes?

**Comment by alkmim** [comment]
@jenting Unfortunately it is still failing for me. Basically I always have 1 replica running and 1 replica rebuilding. 

I did  a test run with a volume  of 100GB. I added a large file using dd. I created the volume using the UI, using the default configuration. One important information is that the longhorn hard drives are being attached through iSCSI. 

I attached the UI screenshot and the logs of one instance-manager where I saw the failure. Let me know if you want more logs. Sadly, the support-bundles collects too much information from my system, so I cannot add it here, but I am happy to give you some specific log lines or files. 

I am attaching the intance-manager logs of one instance where I noticed the error happening and a screenshot of the longhorn-ui.

![Screenshot from 2021-11-07 00-02-50](https://user-images.githubusercontent.com/4255504/140635820-4386e860-0fdd-4c5a-a225-c087a7af7477.png)
[replica-manager.log](https://github.com/longhorn/longhorn/files/7491876/replica-manager.log)

**Comment by alkmim** [comment]
@jenting Were my logs useful somehow?

**Comment by jenting** [comment]
> One important information is that the longhorn hard drives are being attached through iSCSI.

So, the hard drives are external iSCSI storage, right?

>  is there a way to increase the timeout or add a retry for the failed sync?

Since Longhorn currently rely on stable and fast underlying network infrastructure, and we did not create an option to let the user control the timeout value.

But we did notice this kind of networking issue across nodes, we'll try our best to fix it.

**Comment by alkmim** [comment]
> So, the hard drives are external iSCSI storage, right?

Yes, exactly. 

> But we did notice this kind of networking issue across nodes, we'll try our best to fix it.

Thanks! One think that could be useful is an option specifying how outdated a replica needs before it gets discarded. When the connection is back online, longhorn will just update the replica instead of recreating a new one from scratch. 

AFAIK, this is usually how other systems works. The replication do not start from scratch when the disk is outdated. It will just sync what is not synced. 

Let me know if you guys want some help.

**Comment by alkmim** [comment]
@jenting are you going to consider this as an issue or as working by design?
