### ISSUE TITLE
[IMPROVEMENT] Improve rebuilding is canceled if it takes longer than 24 hours

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2765]
We have a limit for rebuilding. It is capped at 24 hours [here](https://github.com/longhorn/longhorn-engine/blob/c101e7a2388ca41e84bfc0cad33366f9e22b279c/pkg/replica/client/client.go#L20).

Some ideas from @yasker :

Those long timeout are not good, as we should use progress instead of timeout to decide if the operation is still going on. like Backup or other operations. Though here we're only dealing with a single GRPC call. A few ways to solve this:
* Increase the timeout and document it. Warning user in the worst case scenario, a rebuild lasting more than xx hours might fail. (Not ideal due to we still going to timeout)
* Remove the timeout on this level and depends on GRPC for network detection, and depends on the upper layer or lower layer timeout (I vaguely remembered there is one? or it's after the GRPC call) for whole process timeout (Need to check if the upper/lower layer can catch it correctly)
* Divide one GRPC into multiple GRPC calls with ability to determine the progress (Can be complex to implement)

**Additional context:**
The rebuilding time is a function of: the size of snapshot + the number of holes in the snapshot

**Comment by mattmattox** [comment]
@PhanLe1010 Could we make this a tunable setting under the "Danger Zone" section? Because there could be events where rebuilds are very slow.

For example, a cluster that has a large amount of data and has a power outage event. This event triggers a rebuild of most of its data which can put a heavy load on the longhorn storage servers. In this event, larger volumes could timeout cause additional load as another rebuild has to be started IE rebuilding the same data multiple times. But if we had a tunable setting, this timeout could be increased temporarily until all data has been rebuilt then changed back to default.

**Comment by innobead** [comment]
@derekbit 

Should we make the timeout configurable?

Some causes make the rebuilding slow
disk starvation: many applications are consuming disk ios, slow disks
network issue: starvation, small bandwidth, high resend rate/packet loss...
cpu bound

Two ideas
Make the timeout configuration
Or, if the rebuilding is in progress, can we make it  adaptive and automatically increase the timeout?

@shuo-wu 
Replica rebuilding is a sync call hence the timeout & disk performance determines the max capacity Longhorn can rebuilding, which then determines the max volume size

Maybe we need to make the call async first, which is already mentioned in the SPDK rebuilding PR

@PhanLe1010 
This is not restricted by the underlying filesystem. It is from a testing with 1.2.0 that a typical system of 6CPU, 16GB RAM, SSD, 7gbps can handle rebuilding of replica of 2TB before hitting timeout
If the system is more powerful, it can handle rebuilding of bigger volume

async + eventual rebuild

**Comment by pwurbs** [comment]
As mentioned in #6034, a cancelled rebuild should resume the data transfer within a new connection and not starting from scratch.

**Comment by PhanLe1010** [comment]
I was investigated 2 appoarches
###  Make the timeout configurable
The first approach is simple but the user will have to try and error the first time to figure out the appropriate value 

### Make the rebuilding call async
This approach will require significant refactoring that I think outweighs its benefits. This is the flow when Longhorn manager trigger a replica rebuild:
![image](https://github.com/longhorn/longhorn/assets/22139961/65d00d38-2b86-40d2-a730-e5bf93e08a9e)

As we can see there are 3 long timeout gRPC all we would have to convert to async.

My current understanding of async design is that:
1. The client makes the call to the server
1. The server does some quick work to set up the operation then returns OK to the client immediately.
1. The server keeps track of the state of the operation while performing it in the background
1. The client periodically queries the server by another API/gRPC call to ask about the status of the operation. The client needs to send an id to identify the operation

The challenge here is the gPRC call between longhorn-manager (client) and instance-manager proxy (server). The instance-manager has no memory/state about pending rebuilding/replica add operation. It also doesn't make sense to add these information into instance-manager proxy 

And other smaller challenge is that the gGRPC call between rebuilding replica (`(c *ReplicaClient) SendFile()`) and source replica (`(s *SyncAgentServer) FileSend()`), the sync agent on the target replica also doesn't have have state about the current pending file transfer. Though, this would be easier to refactor because it makes sense to add this state into the source replica.  


**Therefore, I think we should go with the first approach _Make the timeout configurable_**

**Comment by derekbit** [comment]
> Therefore, I think we should go with the first approach Make the timeout configurable

Agree with the configurable timeout as well.

**Comment by PhanLe1010** [comment]
> > Therefore, I think we should go with the first approach Make the timeout configurable
> 
> Agree with the configurable timeout as well. I think we can increase the default timeout to a bigger value. Any concern for it?

I feel that 24h is big enough for default value since 1 day rebuilding feel quite slow already. WDYT?

**Comment by pwurbs** [comment]
24h is the current value anyway. So it's a good default value.

**Comment by PhanLe1010** [comment]
@pwurbs 

btw, the ticket to resume rebuilding from last data transfer completion instead of rebuilding from scratch is tracked at https://github.com/longhorn/longhorn/issues/8737 . This ticket only concern with the 24h rebuilding timeout limitation

**Comment by pwurbs** [comment]
I know

**Comment by derekbit** [comment]
> > > Therefore, I think we should go with the first approach Make the timeout configurable
> > 
> > 
> > Agree with the configurable timeout as well. I think we can increase the default timeout to a bigger value. Any concern for it?
> 
> I feel that 24h is big enough for default value since 1 day rebuilding feel quite slow already. WDYT?

Sounds good to me. Users can change the value according to the env.

**Comment by PhanLe1010** [comment]
### Test Plan:

Case 1: Simple test case:
1. Install Longhorn
2. Make sure that it can rebuild 10G volume with full data
3. Change `long-grpc-timeout` setting to 10s
4. Verify the rebuilding is always timeouted 

Case 2: Real-world Very Long Rebuilding 
1. Create a cluster of 2 worker node and 1 controller plane node and EBS disk like the config in this scalability test https://github.com/longhorn/longhorn/blob/master/scalability/reference-setup-performance-scalability-and-sizing-guidelines/public-cloud/medium-node-spec.md#case-2-volume-with-data-pattern-4k_data-4k_hole-4k_data-4k_hole-
1. Increase the long-grpc-timeout to 48 hours
1. Make sure that we can rebuild a replica of 900G using this testing plan https://github.com/longhorn/longhorn/blob/master/scalability/reference-setup-performance-scalability-and-sizing-guidelines/public-cloud/medium-node-spec.md#case-2-volume-with-data-pattern-4k_data-4k_hole-4k_data-4k_hole-

Case 3: Helm
Make sure that setting the helm value reflects in the change in actual Longhorn setting

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-engine `aa844e`, longhorn-instance-manager `855d6c`, longhorn-manager `638560`) with test [steps](https://github.com/longhorn/longhorn/issues/2765#issuecomment-2185449821)

- Set `long-grpc-timeout setting` to 10s, 10G volume replica rebuilding will never finished.
- Set `long-grpc-timeout setting` to `172800`s, replica rebuilding(700Gi generated by fio) completed in more than 24 hours without any problems.
- Helm value `longGRPCTimeOut` reflects in the change in actual Longhorn setting.
