### ISSUE TITLE
[BUG]longhorn 1.1.1， can't click the detach button in the volume column PVC

### ISSUE THREAD

**Issue by kevindwei** [longhorn/longhorn#2770]
long1.1.1 can't click the detach button in the volume column PVC

![image](https://user-images.githubusercontent.com/20273599/124556179-8ee1e280-de6a-11eb-9681-bae2a27e892a.png)

**Comment by c3y1huang** [comment]
cc @smallteeths

**Comment by c3y1huang** [comment]
Seems this is already fixed in [v1.1.2](https://github.com/longhorn/longhorn-ui/commit/b9f4b3f4cf40a7fd46962f946f8a6c63f618d26d) and [master](https://github.com/longhorn/longhorn-ui/commit/9ab234fdf04127fe9aa4eac0584fd730d759ac4b).
