### ISSUE TITLE
[DOC] Add document about how to deal with filesystem corruption

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2779]
Sometimes the filesystem inside a Longhorn volume is corrupted because of an external reason. In this case, Longhorn cannot remount the volume and the workload that uses the volume cannot restart. Longhorn cannot solve this problem automatically. We require user to manually fix the filesystem.

We should provide the users a document about how to manually fix the filesystem corruption: instructions on how to attach the volume to a node and how to identify the device and mount it, and that they then need to a filesystem check against the device.

**Comment by meldafrawi** [comment]
Documents validated: **LGTM**
