### ISSUE TITLE
how to boot from base_image with kvm ?

### ISSUE THREAD

**Issue by piaohai** [longhorn/longhorn#278]
![img20180905_232901](https://user-images.githubusercontent.com/1393745/45104031-b87eda80-b163-11e8-9024-932fd69161ea.png)

i have create two block device,  the first from base image Base Image:rancher/vm-ubuntu:16.04.4-server-amd64, when i run kvm with KVM_BLK_OPTS,
export KVM_BLK_OPTS="-drive file=/dev/sdd,if=none,id=drive-disk0,format=raw -device virtio-blk-pci,scsi=off,drive=drive-disk0,id=virtio-disk0,bootindex=1" 

but kvm can't boot into ubuntu system, so how to set that opts? @yasker  tks,

**Comment by yasker** [comment]
@LLParse ^^

**Comment by piaohai** [comment]
vnc display   /dev/mapper/rancher--vg--root  not exists, how to how to mount ?

**Comment by LLParse** [comment]
Hi @piaohai - It seems your goal is to boot a KVM instance using a Longhorn volume created with a base image. If that is the case, this can be achieved like so:

1. Create Longhorn volume with base image. *The volume size must match the base image size, which must be known ahead of time.* This is a current limitation that will be investigated in the future. The `rancher/vm-ubuntu:16.04.4-server-amd64` base image is of size `8 GiB`, which is analagous to the default root volume size in AWS. https://i.imgur.com/XuHeZ7l.png
2. Attach Longhorn volume, wait until healthy. Note the iSCSI Endpoint. In my environment it is `iscsi://10.42.0.21:3260/iqn.2014-09.com.rancher:test/1`
3. Start the KVM instance. My environemtn is configured for bridge networking and this works: `qemu-system-x86_64 -enable-kvm -m size=512 -smp cpus=1 -cdrom /cidata.iso -vnc 0.0.0.0:0 -netdev bridge,br=br0,id=net0 -device virtio-net-pci,netdev=net0,mac=06:fe:26:ac:64:8c -drive file=iscsi://10.42.0.21:3260/iqn.2014-09.com.rancher:test/1`
4. Connect to the virtual machine with your favorite VNC client. The VNC server endpoint in my environment is `192.168.100.134:5900`, your IP address will be different.

I don't remember exactly how to do this with the block device frontend, but it should be fairly straightforward. Just make note that the `rancher/vm-ubuntu:16.04.4-server-amd64` base image has a partition table with three partitions. Creating the Longhorn volume with wrong size, as you have seen, will result in corrupted/unreadable partitions.

**Comment by piaohai** [comment]
![img20180907_105922](https://user-images.githubusercontent.com/1393745/45196391-874ef900-b28e-11e8-8110-211a9b006419.png)


![img20180907_103149](https://user-images.githubusercontent.com/1393745/45195956-946ae880-b28c-11e8-844a-760707832d61.png)

first case i created block device with 20G.

second created 20G with iscsi,  after boot system all can't not login into system, error message the same as above.  

@LLParse

**Comment by piaohai** [comment]
![img20180908_074337](https://user-images.githubusercontent.com/1393745/45247555-fb46db00-b33a-11e8-97b2-301de246f954.png)

i have try to with 8G, it not work for me also, error like above initramfs, so i think may be is remote disk volume not ok ?

longhorn version 0.3.0 (RUN on the vmware virtula machine)
vm v0.1.0

**Comment by yasker** [comment]
@piaohai Can you see if you can use open-iscsi to connect to this endpoint? Or use block device to verify the content of volume is correct.
