### ISSUE TITLE
[QUESTION]  Volume Health: Degraded

### ISSUE THREAD

**Issue by elton557** [longhorn/longhorn#2782]
- Longhorn version: 1.1.1

Hi, I have a pvc that is only in this degraded state, it's been there for days so what can it be?

<img width="1439" alt="Screen Shot 2021-07-08 at 11 24 25" src="https://user-images.githubusercontent.com/52458645/124939471-819a3480-dfdf-11eb-955f-be775a2a2182.png">

**Comment by c3y1huang** [comment]
It seems the cluster is having issues trying to schedule the replicas. Have you got sufficient nodes number and resources for the cluster?

For a quick fix, you can try either,
- Reduce the number of volume replicas with `Update Replica Count` on [this page](https://user-images.githubusercontent.com/52458645/124939471-819a3480-dfdf-11eb-955f-be775a2a2182.png) then remove problematic replicas.
- Set [Replica Node Level Soft Anti-Affinity](https://longhorn.io/docs/1.1.1/references/settings/#replica-node-level-soft-anti-affinity) to true

**Comment by elton557** [comment]
@c3y1huang Hi, I made these adjustments, but when I put replica 2 my volume gets degraded and doesn't come out of it, can you help me?

<img width="1438" alt="Screen Shot 2021-07-20 at 11 08 59" src="https://user-images.githubusercontent.com/52458645/126338851-bd3ae16c-9608-41e0-95dd-d29e41df7e4b.png">
<img width="1412" alt="Screen Shot 2021-07-20 at 11 08 51" src="https://user-images.githubusercontent.com/52458645/126338869-203b1dd5-c9ad-4b4b-89ab-55bad79b1669.png">

**Comment by PhanLe1010** [comment]
When Longhorn starts rebuilding a replica, it will take a snapshot of the volume first. From the picture you sent, it seems that the volume has too many snapshots (the read icon in the picture) and cannot take a new snapshot. This might be the reason the rebuilding fails.

To verify this, can you send us the support bundle to `longhorn-support-bundle@rancher.com`? You can generate a support bundle from the link on the bottom of Longhorn UI

**Comment by elton557** [comment]
<img width="1440" alt="Screen Shot 2021-07-22 at 23 19 14" src="https://user-images.githubusercontent.com/52458645/126730517-27f4551c-ab95-4203-9445-923b45077e81.png">

Hello, @PhanLe1010  this volume really has a lot of snapshots, can I delete it? what action can I take to resolve my issue? I emailed my support package

**Comment by elton557** [comment]
I don't know how to delete this bunch of snapshots

**Comment by elton557** [comment]
thanks @PhanLe1010 , solved my problem. it really was because there were a lot of snapshots, I removed some and it solved, volume returned to its state

**Comment by kompetenzlandkarte** [comment]
> I don't know how to delete this bunch of snapshots

@elton557 how did you delete all snapshots?
