### ISSUE TITLE
[TASK] Verify upgrade from 1.0.2 to 1.1.2

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#2786]
**What's the task? Please describe.**

We would like to see if 1.0.2 where some users still running is able to upgrade to 1.1.2 w/o issues.

**Describe the items of the task (DoD, definition of done) you'd like.**

- [x] Verify upgrading from 1.0.2 to 1.1.2

**Additional context**

Right now, longhorn upgrade implementation does not strictly limit the upgrade path, so we can probably upgrade from 1.0.2 to 1.1.2 directly.

cc @longhorn/qa

**Comment by kaxing** [comment]
Validating in progress,

A simple upgrade test as follow:
1. Fresh install Longhorn v1.0.2 on 4GB RAM 1+3 cluster (on Rancher v2.8.5, Kubernetes v1.20.8)
2. Launch WordPress app and create a few posts
3. Upgrade Longhorn to v1.1.2 using kubectl apply and keep on using the site
4. Updating the engine image while using the site

No obvious problem found.

cc @khushboo-rancher let me know if this looks good to you as well!

**Comment by innobead** [comment]
> Validating in progress,
> 
> A simple upgrade test as follow:
> 
> 1. Fresh install Longhorn v1.0.2 on 4GB RAM 1+3 cluster (on Rancher v2.8.5, Kubernetes v1.20.8)
> 2. Launch WordPress app and create a few posts
> 3. Upgrade Longhorn to v1.1.2 using kubectl apply and keep on using the site
> 4. Updating the engine image while using the site
> 
> No obvious problem found.
> 
> cc @khushboo-rancher let me know if this looks good to you as well!

Please also run automation testing on that to ensure no critical issues.

**Comment by kaxing** [comment]
Validating test_upgrade.py by running the test alone, the test case itself took 10 mins and passed.

**Comment by khushboo-rancher** [comment]
Integration test results looks good on the upgraded set up from v1.02 to v1.1.2
