### ISSUE TITLE
[QUESTION] Backup strategy for volumes on AKS.

### ISSUE THREAD

**Issue by tbertenshaw** [longhorn/longhorn#2787]
**Question**
Are there any examples of backup/architecture for a RWX volume on AKS? I have deployed moodle using helm (which uses a RWX volume shared between replicas) .

I can see its created a PVC using local node storage (initially i expected/hoped it would create/add a AzureDisk or AzureFile which it would use as the source of truth that it used for the node volumes it created.

I now want to ensure that the volume is backed up to another storage device in the event that something went wrong with the local storage replicas on the nodes.

Is there an example of creating a external storage target using azure storage? And is this the recommended strategy?

**Environment:**
 - Longhorn version: 1.11
 - Kubernetes version: 1.21.1
 - Node config
   - OS type and version: ubuntu 18.04.5 LTS
   - CPU per node: 2
   - Memory per node: 8Gb
   - Disk type: Premium SSD
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AKS

**Additional context**

**Comment by PhanLe1010** [comment]
@tbertenshaw 

Longhorn allows backing up volumes' data to an external backup target (NFS or S3). See more at https://longhorn.io/docs/1.1.2/snapshots-and-backups/backup-and-restore/set-backup-target/

I am not familiar with azure storage but from a quick search, it seems not S3-compatible. We only support S3-compatible or NFS

**Comment by tbertenshaw** [comment]
https://docs.microsoft.com/en-us/azure/storage/blobs/network-file-system-protocol-support
https://docs.microsoft.com/en-us/azure/storage/blobs/network-file-system-protocol-known-issues

Is there anything in the known issues link that looks incompatable?  Would be a bit of a blocker for me if there wasnt an azure solution for this.  

Could a manual backup be done by creating an nfs volume and using something like [rsync](https://linux.die.net/man/1/rsync)?

**Comment by PhanLe1010** [comment]
I see. You want to add something on top of Azure Blob Storage to make it NFS or S3-Compatible. From the link you provided, I see that  Azure Blob Storage already has NFS 3.0 support so it might work! Can you give it a try?

From a quick search, I see that it is also possible to make Azure Blob Storage S3-compatible by deploying Minio on top of it https://min.io/solutions/azure-s3-api-integration

**Comment by jenting** [comment]
@tbertenshaw Do you have further questions of this one?

**Comment by innobead** [comment]
It seems stale. Closing but feel free to reopen if you still have any questions.

**Comment by tbertenshaw** [comment]
see this is actually been consider in #1309
