### ISSUE TITLE
[BUG] UI under volumes constantly displaying Deleting but they never delete

### ISSUE THREAD

**Issue by iangregsondev** [longhorn/longhorn#2788]
**Describe the bug**

Can't delete the volumes, they just say deleting.... for ever..

I wonder if you could help me, doing a kubectl get pv / pvc - they are not there, but in the UI - they constantly display deleting..

i have tried resetting the UI pod .. but still the same..

I am attaching a support file

[longhorn-support-bundle_adddf238-e3ed-421b-bc9a-0a4a9bc63be2_2021-07-09T21-22-02Z.zip](https://github.com/longhorn/longhorn/files/6793991/longhorn-support-bundle_adddf238-e3ed-421b-bc9a-0a4a9bc63be2_2021-07-09T21-22-02Z.zip)

**Comment by iangregsondev** [comment]
I have also done get pods on the longhorn system..

There are five instance managers. is this correct? I tried removing them but they get re-created..

I have a 3 node system

```
❯ kubectl -n longhorn-system get pods
NAME                                        READY   STATUS    RESTARTS   AGE
csi-attacher-54c7586574-77498               1/1     Running   0          5h5m
csi-attacher-54c7586574-8wqmk               1/1     Running   0          5h5m
csi-attacher-54c7586574-mskpt               1/1     Running   0          5h5m
csi-provisioner-5ff5bd6b88-bvdjh            1/1     Running   0          5h5m
csi-provisioner-5ff5bd6b88-g9ztq            1/1     Running   0          5h5m
csi-provisioner-5ff5bd6b88-vnxt5            1/1     Running   0          5h5m
csi-resizer-7699cdfc4-44889                 1/1     Running   0          5h5m
csi-resizer-7699cdfc4-cdpcw                 1/1     Running   0          5h5m
csi-resizer-7699cdfc4-zdr7n                 1/1     Running   0          5h5m
csi-snapshotter-8f58f46b4-9zgdv             1/1     Running   0          5h5m
csi-snapshotter-8f58f46b4-xlz2c             1/1     Running   0          5h5m
csi-snapshotter-8f58f46b4-zdbd6             1/1     Running   0          5h5m
engine-image-ei-a5a44787-4jdwv              1/1     Running   0          5h5m
engine-image-ei-a5a44787-g5wf2              1/1     Running   0          5h5m
engine-image-ei-a5a44787-xn9tc              1/1     Running   0          5h5m
instance-manager-e-0ea9e5eb                 1/1     Running   0          5h5m
instance-manager-e-22ba516e                 1/1     Running   0          5h5m
instance-manager-e-ab16a26a                 1/1     Running   0          5h5m
instance-manager-r-52c99bb2                 1/1     Running   0          5h5m
instance-manager-r-c6196eff                 1/1     Running   0          5h5m
instance-manager-r-d50e410f                 1/1     Running   0          5h5m
longhorn-csi-plugin-87pvc                   2/2     Running   0          5h5m
longhorn-csi-plugin-96rbg                   2/2     Running   0          5h5m
longhorn-csi-plugin-rtznt                   2/2     Running   0          5h5m
longhorn-driver-deployer-68cdff85c7-qnz67   1/1     Running   0          5h6m
longhorn-manager-dj62j                      1/1     Running   1          5h6m
longhorn-manager-hv68t                      1/1     Running   2          5h6m
longhorn-manager-njxqx                      1/1     Running   1          5h6m
longhorn-ui-56db5bbb9d-ggpgj                1/1     Running   0          8m10s
```

**Comment by PhanLe1010** [comment]
Please don't delete components in `longhorn-system` namespace if you are not sure what it is doing.
 From the logs, I see a lot of error message `2021-07-09T23:21:51.309619910+02:00 time="2021-07-09T21:21:51Z" level=warning msg="Dropping Longhorn replica longhorn-system/pvc-b3a2f88d-7bb4-4d2a-b538-7ac7605cbb8e-r-ec21a539 out of the queue" controller=longhorn-replica error="fail to sync replica for longhorn-system/pvc-b3a2f88d-7bb4-4d2a-b538-7ac7605cbb8e-r-ec21a539: failed to cleanup the related replica process before deleting replica pvc-b3a2f88d-7bb4-4d2a-b538-7ac7605cbb8e-r-ec21a539: failed to get engine image object based on image name longhornio/longhorn-engine:v1.1.1: engineimage.longhorn.io \"ei-611d1496\" not found" node=onechain-lab2
` which indicate that the engine image `longhornio/longhorn-engine:v1.1.1` is no longer exist. Therefore, Longhor cannot clean up the replicas because all replicas is still using `longhornio/longhorn-engine:v1.1.1` image.

Workaround, go to Longhorn UI -> setting -> engine image -> deploy engine image `longhornio/longhorn-engine:v1.1.1` . Check to see if Longhorn is able to delete your volumes

**Comment by PhanLe1010** [comment]
I see that you have updated control plane to Longhorn v1.1.2. After fixing the deleting issue, you can upgrade engine for volume to v1.1.2 by following the instruction https://longhorn.io/docs/1.1.2/deploy/upgrade/. Once all volumes are using `longhornio/longhorn-engine:v1.1.2` engine image, Longhorn will clean up `longhornio/longhorn-engine:v1.1.1` engine image for you

**Comment by iangregsondev** [comment]
Thanks for the support. I tried doing what you said but got an error

![image](https://user-images.githubusercontent.com/2370364/125368400-69793b00-e37a-11eb-8b11-ddaf5ebf2d39.png)

![image](https://user-images.githubusercontent.com/2370364/125368413-6ed68580-e37a-11eb-873e-fe556b9b361d.png)

**Comment by PhanLe1010** [comment]
Can you give us the output of `kubectl get engineimages -n longhorn-system `?

**Comment by iangregsondev** [comment]
Ok kind of good news, its looking healthier now, there was no engine before and I added the engine.. now I have

```
❯ kubectl get engineimages -n longhorn-system
NAME          STATE      IMAGE                               REFCOUNT   BUILDDATE   AGE
ei-a5a44787   deployed   longhornio/longhorn-engine:v1.1.2   7          6d1h        3d8h
```

![image](https://user-images.githubusercontent.com/2370364/125370925-e955d400-e37f-11eb-9c8f-c526281f5ee5.png)


But the disks are still sat there deleting, I tried to delete them by marking them in the UI - but no go. These volumes don't even exist anymore..

![image](https://user-images.githubusercontent.com/2370364/125371004-1c986300-e380-11eb-9d6f-d5dc04e2edc2.png)

![image](https://user-images.githubusercontent.com/2370364/125371014-21f5ad80-e380-11eb-9304-5864b3f195e9.png)

**Comment by iangregsondev** [comment]
Does that help ?

**Comment by PhanLe1010** [comment]
Can you try to deploy engine image `longhornio/longhorn-engine:v1.1.1` again? Longhorn need that one to delete the volumes since all volume is using that one

**Comment by iangregsondev** [comment]
Nice!!! That was it. -they all disappeared!! :-)

One small issue - I tried removing the engine 1.1.1 - as I assume I don't need it anymore but the UI just ignores me :-)

![image](https://user-images.githubusercontent.com/2370364/125372176-beb94a80-e382-11eb-8ec2-5be4db6dc5f6.png)


Is there a way to delete it from the command line using kubectl ? maybe ?

I suppose it doesn't matter they are both there ? I notice a start against the 1.1.2 

I think all this problem came about as I upgrade longhorn using fluxcd using a helm install.. Something went weird along the way. My previous version was 1.1.1 and then using fluxcd and helmrelease - I used 1.1.2

**Comment by iangregsondev** [comment]
Wait! Impatient I am :-) Its deleted and gone... just left with the 1.1.2 now

**Comment by iangregsondev** [comment]
A big thanks - I have learned quite a bit here. I hope I don't ever get the problem again but I know now that the engine version is pegged to the volumes.

Thanks once again! Great support.

**Comment by PhanLe1010** [comment]
Do you mean that you didn't delete the resources but the fluxcd did? 
To be honest I am not sure if there is anything else that was broken in you cluster. Lmao. Proceed with caution. May be  backing up volumes and a Longhorn reinstallation just to be safe.

**Comment by iangregsondev** [comment]
yep :-) This is just my home lab and not production.  I will keep my eye on it.

I get this big idea of managing all my k8s deploys via fluxcd - everything seemed to work ok :-)

Going to close it now. Cheers again.
