### ISSUE TITLE
[QUESTION] Are Longhorn instance managers supposed to restart after restarting k3s or my network plugin?

### ISSUE THREAD

**Issue by clrxbl** [longhorn/longhorn#2790]
**Question**
I'm currently dealing with an issue for quite some time where Longhorn restarts it's instance managers whenever I restart the Cilium (network plugin) daemonset, which is supposed to be able to restart without any network downtime just fine, just like restarting k3s.  Is Longhorn supposed to restart/terminate it's instance managers whenever I do this or is this a bug? All of this results into my volumes going read-only and half of my cluster crashing when it should be fine.

**Environment:**
 - Longhorn version: 1.1.2
 - Kubernetes version: 1.21.2+k3s1
 - Node config
   - OS type and version: Ubuntu 20.04.2 LTS (also happens on Debian 10, seems OS-independent)
   - CPU per node: E2288G, 16 threads
   - Memory per node: 64GB RAM
   - Disk type: 1TB NVMe
   - Network bandwidth and latency between the nodes: 10Gbit, <1ms latency
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal, Cilium as network plugin

**Additional context**
https://github.com/cilium/cilium/issues/16669 I reported an issue on Cilium's GitHub containing a bit more info.

**Comment by jenting** [comment]
I could handle this if no volunteers.

**Comment by joshimoo** [comment]
We rely on the node ready status to determine, when to kill the instance-managers. ref #2650 
A restart of kubelet will mark the node as not ready before getting back to ready.
I am unfamiliar with cilium I am not sure what the expectation is, if the network drops we end up losing volume connectivity.

**Comment by clrxbl** [comment]
> We rely on the node ready status to determine, when to kill the instance-managers. ref #2650
> A restart of kubelet will mark the node as not ready before getting back to ready.
> I am unfamiliar with cilium I am not sure what the expectation is, if the network drops we end up losing volume connectivity.

Cilium uses an eBPF datapath, it retains all network connectivity when the cilium-agent isn't available. Would it be possible to have Longhorn not terminate when the node isn't ready?

**Comment by jenting** [comment]
I make a quick test on restart the cilium DaemonSet, the node become `NotReady` status temporarily.

**Comment by jenting** [comment]
To improve this, we need #2650 as Joshua's comment.

**Comment by jenting** [comment]
Close it since the question be resolved, and we'll tackle and track it with #2650.
