### ISSUE TITLE
[FEATURE] move filesystem expansion into the csi driver

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2794]
**Is your feature request related to a problem? Please describe.**
Currently we do file system expansion via the longhorn-manager as part of the volume-controller.
https://github.com/longhorn/longhorn-manager/blob/a56ca0f299b90a33690ee2cb1169977b17fd28f2/controller/volume_controller.go#L1438-L1470

This should be done as part of the **csi driver** on the node where the volume is being used.
Since the file system stuff is the responsibility of the PVC which should be dealt with as part of the csi kubernetes integration.
While longhorn operates on the block level.

**Describe the solution you'd like**
- this can be done as part of NodeServer.NodeExpandVolume
- as well as potentially during NodeServer.NodeStageVolume

**Additional context**
This should be targeted for v1.2 but if we run out of time, we can move to v1.2.1
This is required to support file system expansion for encrypted volumes ref #1859

**Comment by innobead** [comment]
Thanks, @joshimoo  updated this to me and agreed that let's put it to 1.2 first.

**Comment by khushboo-rancher** [comment]
Validated the expansion of RWO and RWX volumes, they are working fine. 

@joshimoo Any other area needs to be tested to close the validation for this issue?

**Comment by joshimoo** [comment]
@khushboo-rancher only expansion, did you test with encrypted volumes? see related issue https://github.com/longhorn/longhorn/issues/2868

**Comment by khushboo-rancher** [comment]
I see https://github.com/longhorn/longhorn/issues/2868 in the ready for test state. I will test the encrypted volume with #2868 ticket. Closing this one.

Couldn't find the ticket for backport so created https://github.com/longhorn/longhorn/issues/3227 for the backport to v1.2.x.
