### ISSUE TITLE
[BUG] longhorn-engine image no longer contains longhorn-instance manager

### ISSUE THREAD

**Issue by keithalucas** [longhorn/longhorn#2796]
**Describe the bug**
https://github.com/longhorn/longhorn-engine/commit/0224acb52d5f31eca87904c87c29a5a5182b22f6 removed `longhorn-instance-manager` from the longhorn-engine image.  longhorn-instance-manager is used by the `launch-simple-file` and `launch-simple-longhorn` scripts in `/usr/local/bin`.

**To Reproduce**
1. `docker image pull longhornio/longhorn-engine:v1.1.2`
2. `docker run -it longhornio/longhorn-engine:v1.1.2 ls /usr/local/bin/`
3.  See that `longhorn-instance-manager` isn't in the output.

**Expected behavior**
`longhorn-instance-manager` should be in `/usr/local/bin` in order for `launch-simple-file` and `launch-simple-longhorn`  to work.

**Log**
N/A

**Environment:**
 - Longhorn version: v1.1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): N/A
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: N/A
   - Number of management node in the cluster: N/A
   - Number of worker node in the cluster: N/A
 - Node config
   - OS type and version: N/A
   - CPU per node: N/A
   - Memory per node: N/A
   - Disk type(e.g. SSD/NVMe): N/A
   - Network bandwidth between the nodes: N/A
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): N/A
 - Number of Longhorn volumes in the cluster: N/A

**Additional context**

**Comment by yasker** [comment]
Also, https://longhorn.io/docs/1.1.2/advanced-resources/data-recovery/export-from-replica/ won't work for v1.1.2 due to `launch-simple-longhorn` won't work.

**Comment by khushboo-rancher** [comment]
Verified with master-head `07/27/2021` and v1.1.3-head `07/27/2021`

Validation - **Pass**

Validated with `launch-simple-longhorn`, It worked with master-head and v1.1.3-head

```
> docker run -it longhornio/longhorn-engine:master-head ls /usr/local/bin/
engine-manager	   launch-simple-file	   longhorn
grpc_health_probe  launch-simple-longhorn  longhorn-instance-manager

> docker run -it longhornio/longhorn-engine:v1.1.3-head ls /usr/local/bin/
engine-manager	   launch-simple-file	   longhorn
grpc_health_probe  launch-simple-longhorn  longhorn-instance-manager
```
