### ISSUE TITLE
[QUESTION] Could Longhorn deployment disable the previous default sc?

### ISSUE THREAD

**Issue by peteingithub** [longhorn/longhorn#2797]
**Question**
Deploying Longhorn with Rancher leads 2 default storage classes and other deployments fail.

**Environment:**
 - Longhorn version: 100.0.0+up1.1.1 
 - Kubernetes version: 1.21.2-x
 - Node config
   - OS type and version: SLES15sp3
   - CPU per node: 2
   - Memory per node: 4GB
   - Disk type: NVME
   - Network bandwidth and latency between the nodes: Local VMs
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM

**Additional context**
2 default SCs is not "right".

**Comment by PhanLe1010** [comment]
The version `100.0.0+up1.1.1` is weird, I never saw this one. What is the output of `kubectl get sc` and `kubectl get pods -n longhorn-system -o jsonpath="{..image}"` ?

* If you want Longhorn to mark `longhorn` SC as default, you should mark the other SC as non-default.
* If you don't want Longhorn to mark `longhorn` SC as default, depending on how you deployed Longhorn, you can:
    * With Helm, change `defaultClass` to `false` [here](https://github.com/longhorn/longhorn/blob/06ec6424af91f4fc8e0957b7178d7d4547db840e/chart/values.yaml#L55)
    * With Kubectl, by default `longhorn` SC is not a default SC. If not, you can edit the `longhorn-storageclass` configmap by `kubectl edit configmap longhorn-storageclass -n longhorn-system`

**Comment by peteingithub** [comment]
Thanks for the reply.

It's Rancher provided chart, hence the version I guess.

I forgot to paste this:
```NAME                   PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  145m
longhorn (default)     driver.longhorn.io      Delete          Immediate              true                   4m30s```

I would like to have lonhorn sc set as default, which the chart does, but the problem being that then there are 2 defaults. Easy fix, but I'm wondering if the existing default could be changed to not be default. (This might be more a k8s question than Longhorn.)

**Comment by PhanLe1010** [comment]
@peteingithub 

I see. If you want to mark the local-path SC as non-default, I guess you unset it here https://github.com/k3s-io/k3s/blob/3e1693bc97c3002e6939b3ceb8ca06f2678a3b05/manifests/local-storage.yaml#L91

**Comment by peteingithub** [comment]
Changing it later is not a problem. I'm wondering if a chart setting the new storage class to default would also be able to check if there already is a default sc configured, and change the existing as non-default, because you can not have two defaults the same time.

**Comment by PhanLe1010** [comment]
I think overwriting other stuff in users' evn that is not managed by Longhorn would be too aggressive

**Comment by peteingithub** [comment]
True that. :)
