### ISSUE TITLE
[TASK] Implement test case for test_autosalvage_with_data_locality_enabled

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2800]
**What's the task? Please describe.**
Implement the test case for `test_autosalvage_with_data_locality_enabled`
https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_ha.py#L2585

**Describe the items of the task (DoD, definition of done) you'd like.**
- [ ] Implementation of the test
- [ ] Watch the integration test passing consistently.

**Additional context**
https://github.com/longhorn/longhorn/issues/2778

**Comment by meldafrawi** [comment]
Note: we need to change the workload type in test steps to be a `Deployment`

**Comment by yangchiu** [comment]
This has been implemented and become a flaky test case for a long time.

Use https://github.com/longhorn/longhorn/issues/4814 and https://github.com/longhorn/longhorn/issues/5801 to track the related issue.
