### ISSUE TITLE
[BUG] Volume attachment not updating

### ISSUE THREAD

**Issue by ahedderich** [longhorn/longhorn#2802]
Since a few days i have a problem with volumes not mounting an pods. I recently upgraded longhorn from Version 1.1.1 to 1.1.2. Not sure if that is related.
The Problem is as follows:
New Pods get stuck on ContainerCreating with 
`Unable to attach or mount volumes: unmounted volumes=[test-de-db], unattached volumes=[test-de-db default-token-ctwfr]: timed out waiting for the condition`
The volume exists but in case of a newly created one no VolumeAttachment record is created.
With existing Volumes that should reattach the corresponding VolumeAttachment doesn't change. it even assumes the volume is sill attached on a different node.
In the Longhorn UI the Volumes state is displayed correctly. attaching/detaching a volume on any node works fine.
Manually creating a VolumeAttachment object also prompts the longhorn attacher side car to attach the volume on the given node.
The Problem seems to be that the management of VolumeAttachment objects and subsequent mounting of the Volume in the corresponding Pod is not working or im some cases works but with hours of delay.
I've tried to find errors in logs of csi-attacher, instance-manager, longhorn-csi-plugin but came up empty so far.
the attacher is going through the VolumeAttachment objects roughly every 10 minutes but doesn't update the state of the objects.

Is there any other place i could look for error messages that can point me in the right direction?

How does the process of the attachment work in longhorn? 

**Environment:**
 - Longhorn version: 1.1.2
 - Kubernetes version: 1.17.17
 - Node config
   - Ubuntu 20.20
   - CPU per node: 4
   - Memory per node: 16G
   - Disk type: SSD
   - Network bandwidth and latency between the nodes: x
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Comment by ahedderich** [comment]
problem was as it seems with kubernetes itself.

**Comment by c3y1huang** [comment]
@ahedderich glad you've managed to figure things out. 

Can you share how you've solved this? It would be helpful if others find themself in the same situation.

**Comment by ahedderich** [comment]
I'm still not super sure. uprading the kubernetes core resulted in a restart of all kubernetes component pods. 
which solved the problem, but investigation is still ongoing.
i might have to except that "did you turn it off and on again" will be the answer for me in the end.

**Comment by kailam2lot** [comment]
I encountered a situation where I restarted the k3s server, and found that the pvc above kept reporting similar errors, the pod could not mount the volume, and the server itself reported an error of rpc error. I tried many methods, such as manually on the host. Mounting or modifying deployment replicas does not work, and finally I restarted the entire k3s cluster.

Another curious situation is that after the k3s cluster is restarted, a volume remains unmounted. The solution is to find the host where the volume is mounted, manually mount the volume to a random directory on it, and then the pod is Successfully mounted.

BTW, mine is k3s v1.20 + longhorn v 1.1.1

**Comment by shuo-wu** [comment]
> I encountered a situation where I restarted the k3s server, and found that the pvc above kept reporting similar errors, the pod could not mount the volume, and the server itself reported an error of rpc error. I tried many methods, such as manually on the host. Mounting or modifying deployment replicas does not work, and finally I restarted the entire k3s cluster.

After the k3s server/agent restarts, the volumes attached to the node should be reattached **automatically**. Then if setting `auto-delete-pod-when-volume-detached-unexpectedly` is set, Longhorn will kill the deployment/statefulsets pods using the reattachment volumes to trigger pod restart with remount. I am not sure what happens in your case? I need to check what the error message is and what your use case is. Can you provide the support bundle?
