### ISSUE TITLE
[BUG] allow volume migration when volume is degraded (harvester vm)

### ISSUE THREAD

**Issue by guangbochen** [longhorn/longhorn#2805]
**Is your feature request related to a problem? Please describe.**
during the Harvester VM live migration(consist of 2 nodes), all LH volumes are degraded, given that the Longhorn replica is equal to 3, so the pod is failed to start correclty.

`unable to attach volume pvc-83b575fa-4229-46be-a6a0-186561a903cc to bm-harv2: volume must be healthy to start migration, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes/pvc-83b575fa-4229-46be-a6a0-186561a903cc?action=attach`

```
NAME                                     READY   STATUS              RESTARTS   AGE
virt-launcher-lawr-1-j75dc               1/1     Running             0          116m
virt-launcher-lawr-1-tcxvq               0/1     ContainerCreating   0          8m47s


Warning  FailedAttachVolume  3s (x3 over 9s)    attachdetach-controller  AttachVolume.Attach failed for volume "pvc-83b575fa-4229-46be-a6a0-186561a903cc" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=unable to attach volume pvc-83b575fa-4229-46be-a6a0-186561a903cc to bm-harv2: volume must be healthy to start migration, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes/pvc-83b575fa-4229-46be-a6a0-186561a903cc?action=attach]
```

**Describe the solution you'd like**
need a feasible way to relax the restriction on VM migration when the volume is degraded.

**Describe alternatives you've considered**

**Additional context**
https://github.com/harvester/harvester/issues/798

**Comment by yasker** [comment]
Raise the priority due to it has a high impact in case the user only has 3 nodes and lost one node.

**Comment by yasker** [comment]
We can fix this to v1.2.1.

**Comment by shuo-wu** [comment]
The live upgrade feature doesn't work correctly. Will have a PR fixing this regression later.

**Comment by shuo-wu** [comment]
The regression is fixed. Please verify it during testing.

**Comment by khushboo-rancher** [comment]
Validated with v1.2.1-rc1 and Longhorn-master -09/21/2021

Validation - **Pass**

Validated below scenarios with a Harvester setup with upgraded Longhorn. 
1. The migration works with degraded volume.
2. Migration with rebuilding is in progress - First rebuilding completes and then only the migration starts and complete.
3. Migration with failed replica - Only healthy replicas get created first for the migration.

Note: Observed the live upgrade failure on the set up as mentioned https://github.com/longhorn/longhorn/issues/2805#issuecomment-920833641. @shuo-wu Do we have any issue to track it?

**Comment by khushboo-rancher** [comment]
Created https://github.com/longhorn/longhorn/issues/3052 for upgrade problem
Observed another problem https://github.com/longhorn/longhorn/issues/3053
