### ISSUE TITLE
[FEATURE]  ui show exact time, not only "xx days ago"

### ISSUE THREAD

**Issue by fanlix** [longhorn/longhorn#2808]
**Is your feature request related to a problem? Please describe.**
From-now relative time is not enough when multi snapshot/backups need a match.
For example some app need 3 backup volumes at same time: db-disk, cache-disk, config-disk

**Describe the solution you'd like**
show time in exact format,  "xxxx-xx-xx hh:mm:ss"
* show it when mouse hover "xx days ago" text
* offer an option to disable from-now time, or another custom column
* show in Volume/backup detail page

**Describe alternatives you've considered**

**Additional context**
for current version, the exact time can only be seen in ui: 
* Volume - Snapshots and Backups, when mouse hover icons

**Comment by PhanLe1010** [comment]
Just to confirm. You are referring to the time in this UI page, right? 
<img width="662" alt="Screen Shot 2021-07-19 at 4 19 14 PM" src="https://user-images.githubusercontent.com/22139961/126239439-1b4ce406-caa4-4e48-8869-e17f8008a8a4.png">

**Comment by yasker** [comment]
We can show the exact date/time as a tooltip.

**Comment by smallteeths** [comment]
Do we want to support a setting item to allow the user to choose the format of the time display. For example type 1 xx ago type 2 xxxx.xxx.xxx. @yasker

**Comment by yasker** [comment]
@smallteeths Don't need to. I think a tooltip would be enough.

**Comment by kaxing** [comment]
Validating with latest longhorn mater-head images(longhorn-ui: 6cbf796)

With the new design, now moving mouse cursor over the human-readable time it will show full datetime as tooltips:
![datetime-tooltips](https://user-images.githubusercontent.com/602540/128165339-83facbbc-5f08-42a0-8887-e89ccf36e620.gif)

**Comment by kaxing** [comment]
Validation - **Passed** (master images 2021-08-06)

Any columns with the X time ago will had the datetime tooltips:
![image](https://user-images.githubusercontent.com/602540/128483392-ceb3015c-e194-4073-b5eb-778ecbba0b3d.png)
