### ISSUE TITLE
[BUG] Relax S3 client retry intervals, for throttled requests

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2810]
**Describe the bug**
The default S3 retry behavior settings are not sufficient for a cluster with many concurrent backups in progress

**To Reproduce**
1. create a storage class with recurring job specification running 2x per day 12h apart
2. create > 100 volumes of X size fill them with data
3. we will run into amazon s3 request limits

4. the throttled request will be retried 3 times internally before being exposed as a backup failure
5. the failed backup job will be retried 3x times in total per volume

**Expected behavior**
We should relax the retry amounts for throttled requests so that the requests can be retried with a bigger backoff, which should allow the request to eventually succeed and no backup failure as a result is necessary.

**Environment:**
- Longhorn version: v1.1.1
- Number of worker node in the cluster: 48
- Number of Longhorn volumes in the cluster: 400

**Additional context**
The failed backups will be retained in the engine backup status map, which will lead to many connections during longhorn-manager sync ref #2818

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn `07a87d`)

1. Create 120 volumes with size = 1G, write 500 MB data into each volume.
2. Set S3 as bcakup target.
3. Create a backup recurring job, `CONCURRENCY` number = 120, group=`default`, start 5 minutes later
4. Wait for the recurring backup start, observe all the backups
5. All backup `Completed`

![image](https://github.com/longhorn/longhorn/assets/73337386/839c7c98-6d93-4258-853f-8cc035f7ac03)
