### ISSUE TITLE
[TASK] Create a performance and scalability report against 1.2.0

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#2811]
**What's the task? Please describe.**

We did a report for 1.0 (https://longhorn.io/blog/performance-scalability-report-aug-2020/), but it was quite a long time ago before 1.1 and 1.2 releases. During this period, we have some improvements like replica rebuilding, legacy harddisks via timeout changes, etc, so we would like to see the updated report to reflect the current status.

**Describe the items of the task (DoD, definition of done) you'd like.**

- [ ] As per the same testing architecture, create the report in terms of IOPS, latency and throughput

**Additional context**

We also need to consider the reporting automated after the report is created. (cc @meldafrawi )

cc @longhorn/qa

**Comment by yasker** [comment]
FYI: I've started a new benchmark project at https://github.com/yasker/benchmark, with the intention of moving it to Longhorn later. I haven't got much time to work on it yet. In general, we should depreciate https://github.com/longhorn/dbench/ and containerize https://github.com/yasker/benchmark to provide a generalized benchmark framework for Kubernetes workloads. The goal is to replace `dbench` with `longhorn/benchmark` as the de-facto standard benchmark for Kubernetes storage.

At least it should be:
1. Able to deploy via Kubernetes
2. Able to test raw block storage as well as a file system (on top of block device or not, thinking NFS).

**Comment by yasker** [comment]
OK, the new benchmark tool is up at https://github.com/longhorn/benchmark .

**Comment by innobead** [comment]
We can do this after 1.2.0 out.

**Comment by innobead** [comment]
Closing because of a duplicated https://github.com/longhorn/longhorn/issues/2986
