### ISSUE TITLE
[BUG] Update the doc best practice

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#2812]
**Describe the bug**

No SUSE SLES described in the best practice, we should correct the OSes Longhorn supported.
https://longhorn.io/docs/1.1.2/best-practices/#software
https://longhorn.io/docs/1.1.2/best-practices/#oses-arent-supported-by-longhorn

**Comment by joshimoo** [comment]
@jenting feel free to remove the other elements from the issue templates that don't apply when opening an issue :)

**Comment by joshimoo** [comment]
Also ref #2694 change of recommended over provisioning percentage in the best practices guide, this needs discussion/approval from @innobead @yasker left some information + reasoning in the issue.

**Comment by yasker** [comment]
Thanks for the head up @joshimoo . I've concerns over change the default overprovisioning percentage. Let's talk about it when we have time.

**Comment by jenting** [comment]
The [PR](https://github.com/longhorn/website/pull/438) addressed it, close this issue.
