### ISSUE TITLE
[FEATURE] Support XFS for RWX volumes

### ISSUE THREAD

**Issue by edjmao** [longhorn/longhorn#2814]
**Is your feature request related to a problem? Please describe.**
It appears that the longhorn-share-manager only supports ext4 filesystems. When I create an RWX volume and then create the PV via the Longhorn UI, I select xfs as the filesystem type. However, after mounting the volume, I notice that longhorn-share-manager formats it as ext4. I can create the the volume as an RWO with XFS, and when I change the access type to RWX, the share manager fails to mount the volume because it's trying to mount it as an ext4 filesystem.

**Describe the solution you'd like**
I took a look through the longhorn-share-manager code, and it looks like, indeed, ext4 is hardcoded into the mount code. XFS is not mentioned anywhere in the codebase. I would like to see XFS support built into share-manager.

**Describe alternatives you've considered**
I have tried using ext4 volumes, but with the use case I have (personal file storage, up to 1TB, with large files such as videos), the volume seems to want to rebuild every time a large batch of incoming files is uploaded.
I have also tried running XFS in RWO, and it seems to be stable. However, I have a use case where I want to scale the availability of the application heads, and I want to support an out-of-band backup, which requires an RWX volume.

**Comment by joshimoo** [comment]
This can be done together with 
https://github.com/longhorn/longhorn/issues/2096#issuecomment-857225036 and https://github.com/longhorn/longhorn/issues/2659#issuecomment-857219535

I want to add the ability to configure the nfs-server / share-manager via a config map.
Then the user can make the appropriate changes or we can derive the fs type for the share-manager used volume as part of pvc/pv volume attributes lookup.

**Comment by PhanLe1010** [comment]
> I have tried using ext4 volumes, but with the use case I have (personal file storage, up to 1TB, with large files such as videos), the volume seems to want to rebuild every time a large batch of incoming files is uploaded.

What is the underlying disk? Is it an HDD?

**Comment by edjmao** [comment]
For this volume, it is an HDD. I had problems in the past with all workloads running on HDDs. After reading the hardware guide (my mistake for not reading that section first), I did switch the smaller volumes to SSDs and saw improvements, but getting SSDs sized for this particular workload isn't practical for the budget. I am thinking that, if HDDs continue to be problematic, I may have to just set up the HDDs as a different storage solution, perhaps something like Ceph.

**Comment by joshimoo** [comment]
@edjmao we made some addition to better support spinning disks ref#https://github.com/longhorn/longhorn/issues/2206
They will be available in v1.2 as well as v1.1.3 if you want to provide early feedback you can deploy the master for testing on a separate cluster that utilizes hdds :)

**Comment by edjmao** [comment]
That's awesome! I see that in the 1.2 release notes. I'll see if I can spin something up on a test bench I have using `kind`.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Test steps: https://github.com/longhorn/longhorn/issues/2867#issuecomment-904204920
