### ISSUE TITLE
[BUG] Volume can not be attached to the 3rd node when volume is a RWX type and is migratable

### ISSUE THREAD

**Issue by joy717** [longhorn/longhorn#2815]
**Describe the bug**
When attach a RWX volume (and migratable) to the 3rd node,  will get an error
"unable to migrate volume XXXX from Node-1 to Node-3 since it's already migrating to Node-2"

Maybe this error is because of this line:
https://github.com/longhorn/longhorn-manager/blob/3bba35765633fd2e4e71f4e6d3b74c6d8a8edb46/manager/volume.go#L356

Maybe a RWX and migratable volume should not go through the "migration" process? 
https://github.com/longhorn/longhorn-manager/blob/3bba35765633fd2e4e71f4e6d3b74c6d8a8edb46/manager/volume.go#L367

 
**To Reproduce**
1. creating a RWX and migratable volume: XXXX
2. attaching a volume to Node-1
3. attaching a volume to Node-2
4. attaching a volume to Node-3
5. got an error 

**Expected behavior**
RWX volumes should can be attached to multiply nodes.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Additional context**

**Comment by joshimoo** [comment]
@joy717 what is your use case for the migratable volume? Also how do you know about their existence, is there public documentation that points to them if so we probably want to remove that. 

Migratable volumes where added for virtual machine migration for project harvester 
#2127 
https://github.com/harvester/harvester/issues/384

**Comment by joy717** [comment]
> @joy717 what is your use case for the migratable volume? Also how do you know about their existence, is there public documentation that points to them if so we probably want to remove that.
> 
> Migratable volumes where added for virtual machine migration for project harvester
> #2127
> [harvester/harvester#384](https://github.com/harvester/harvester/issues/384)

@joshimoo 
Hi, joshimoo.
Yes, I found this issue when I using harvester.
I find the code in longhorn-manager project. but can't open issue there. so I create this issue here.
Should I open an issue to harvester?

Step to reproduce:
1. Create a VM vm-1 and attach a volume volume-1. (the "migrationNodeID" of volumes.longhorn.io is empty now)
2. Attach volume-1 to a new VM vm-2. (migrationNodeID now is "vm-2")
3. Try to attach volume-1 to a new VM vm-3. (error now)

**Comment by joshimoo** [comment]
@joy717 thanks for replying when you say: vm-1, vm-2, vm-3 are you doing live vm migrations of vm-1?

It sounds like you want to share a data volume across multiple volumes? In that case you would need to use a traditional RWX volume, which longhorn supports by internally exposing that volume via nfs-endpoint.

You should be able to have multiple storage-classes then specify the type you would want to have, RWX (migratable volumes) are technically RWO volumes with a hack to allow for migration from Node X to Node Y but it has specific requirements. They are faster then a regular RWX volume and do to the RWX access mode requirement from KubeVirt for live migration, we implemented the Migratable volumes. 

Yes please open an issue on the harvester project and link to this.

**Comment by joy717** [comment]
> @joy717 thanks for replying when you say: vm-1, vm-2, vm-3 are you doing live vm migrations of vm-1?
> 
> It sounds like you want to share a data volume across multiple volumes? In that case you would need to use a traditional RWX volume, which longhorn supports by internally exposing that volume via nfs-endpoint.
> 
> You should be able to have multiple storage-classes then specify the type you would want to have, RWX (migratable volumes) are technically RWO volumes with a hack to allow for migration from Node X to Node Y but it has specific requirements. They are faster then a regular RWX volume and do to the RWX access mode requirement from KubeVirt for live migration, we implemented the Migratable volumes.
> 
> Yes please open an issue on the harvester project and link to this.

@joshimoo 
Hi joshimoo. Thanks for replying.

> vm-1, vm-2, vm-3 are you doing live vm migrations of vm-1?

No,  vm-1, vm-2, vm-3 are standalone vms.  I wanna share a volume to 3 vms.
I created a vm-1 with volume volume-1, then attach `volume-1` to vm-2 and vm-3 via Harvester-UI.

Thanks again, I will open an issue on harvester project.
