### ISSUE TITLE
[BUG] Longhorn-csi-plugin pods restart because the Longhorn client 10 secs timeout

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#2816]
**Describe the bug**

Somehow, my developer cluster hits the Longhorn client timeout when I look at the longhorn-csi-plugin Pods log.
```
level=fatal msg="Error starting CSI manager: Failed to initialize Longhorn API client: Get \"http://longhorn-backend:9500/v1\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**To Reproduce**
3. Perform '....'

**Expected behavior**

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: SLES15 SP2
   - CPU per node: 4
   - Memory per node: 8
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 0

**Additional context**

**Comment by jenting** [comment]
This is a way to prevent the longhorn-csi-plugin restarting due to 10 secs timeout of the Longhorn HTTP client.
And the fix is to minimize the probability of the longhorn-csi-plugin Pods restarting.
Should we need the QA to test against it? @innobead

**Comment by innobead** [comment]
> This is a way to prevent the longhorn-csi-plugin restarting due to 10 secs timeout of the Longhorn HTTP client.
> And the fix is to minimize the probability of the longhorn-csi-plugin Pods restarting.
> Should we need the QA to test against it? @innobead

Testing this kind of timeout tunning, it's optional to verify by QA because it's quite straightforward, my 2 cents. But, if you can provide the reproduce steps, QA can help verify for sure.

**Comment by jenting** [comment]
I'd prefer to close it because I can't think of a way to reproduce it.
