### ISSUE TITLE
[BUG] High CPU utilization for Longhorn manager and replica instance manager sometimes due to overwhelming of number of backupstatus in engine

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2818]
**Describe the bug**
Longhorn stores the status of backups inside engine CR. Longhorn manager repeatedly fetches the backups' status by making gRPC calls to the sync agent of the corresponding replica. If there are many engines per node (e.g., 50) and many backup per engine CR (e.g., 100), Longhorn manager pod makes thousands of gRPC called to replica instance manager and opening thousands of socket connections. For each opened socket connection, it stays in TIME-WAIT state for 4 minutes after the Longhorn manager pod closed socket connection on its side, [link](https://superuser.com/questions/173535/what-are-close-wait-and-time-wait-states). Moreover, Longhorn manager repeats this backup status fetching cyle every [5 seconds](https://github.com/longhorn/longhorn-manager/blob/ac065a8deb96193ffec142bcc7e7345615b57b8d/controller/engine_controller.go#L45). This lead to socket connection exhaustion and therefore high CPU and RAM utilization in Longhorn manager and replica instance manager.

**To Reproduce**
Steps to reproduce the behavior (not tested):
1. created 50 volumes and attach them to the same node
1. Wait for the attaching to be done
1. Create 100 backups for each volume
1. Wait for all backup creations to be done
1. Check the CPU of Longhorn manager on the same node and CPU of all replica instance manager pods
2. Check the socket connection on Longhorn manager pod on the same node and CPU of all replica instance manager pods by running `ss -a -n | wc -l`

**Expected behavior**
Longhorn should not exhaust the number of socket connections

**Environment:**
 - Longhorn version: v1.1.1
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: EKS
 - Number of Longhorn volumes in the cluster: 400+

**Additional context**
- This issues is created from the discussion at https://cloud-native.slack.com/archives/CNVPEL9U3/p1626337626223600
- More details from the code level is at https://cloud-native.slack.com/archives/CNVPEL9U3/p1626481421231800?thread_ts=1626337626.223600&cid=CNVPEL9U3

**Comment by joshimoo** [comment]
There is sort of a workaround by deploying and live upgrading to a different engine image.
But it's really ugly and it's hard for the user to detect this case to beginn with, this case can also potentially lead to failures of other components.

**Comment by joshimoo** [comment]
I https://github.com/longhorn/longhorn-engine/pull/644 I reduced the connections required for the BackupStatus retrieval from O(N) where N is the amount of backups to O(1) (engine + replicas)

Further communication improvements will be tracked in this epic https://github.com/longhorn/longhorn/issues/2821

**Comment by yasker** [comment]
After discussion with @joshimoo , this appears to be a severe issue that can be easily triggered by having lots of backups. And the workaround cannot last for long time. Add backporting to v1.1.3 for now.

**Comment by joshimoo** [comment]
For testing I used the below approach:
- create a storage class with recurring backup schedule of 1 minute (just to quickly fill up the backup status)
- create a stateful set with a volume claim template that utilizes that new storage class
- scale up the stateful set to 50.
- run `ss -na | wc -l` inside of the longhorn-manager / instance-managers
- this will show a massive amount of sockets, once the 50 backups per volume have been created
- after this fix you will still have a big amount of sockets (thousands but not tens of thousands) in the longhorn-manager but a very small amount of sockets in comparison in the instance-managers.

Napkin math calculation for orientation uses 75 volumes:
```
turn 75v * 50b = 3750 connections per retrieval into 75v * (1e + 3r) = 300 connections per retrieval.
turn (60/5) * 75v * 50b = 45 000 connections per minute into (60 / 5) * 75v * (1e + 3r) = 3600 connections per minute
This will reduce to v * (1e + 3r) in the future once we have time to refactor the longhorn-manager side of things.
```


Below is the Storage class that I use:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-recurring-backup
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  recurringJobs: '[
  {
     "name":"backup",
     "task":"backup",
     "cron":"*/1 * * * *",
     "retain":50,
     "labels": { "interval":"1m" }
   }
  ]'
```

**Comment by khushboo-rancher** [comment]
Validation - **Failed**

**Set up details:**
3 workers and 1 control plane
CPUs: 4 vcpus
RAM: 8 GB
Volumes : 50
Backups per volumes: 50
All volumes are running on same node

--------------------------------
**With v1.1.2**
1. root@longhorn-manager-4gtxn:/# ss -na | wc -l
    11076
2. root@instance-manager-e-398456ef:/# ss -na | wc -l
     476
3. root@instance-manager-r-96cc98a0:/# ss -na | wc -l
     249

**With upgraded set up from v1.1.2 to master-head** - No reduction in the socket connection numbers, increment has been observed.
1. root@longhorn-manager-g964v:/# ss -na | wc -l
    10581
2. root@instance-manager-e-398456ef:/# ss -na | wc -l
    921
3. root@instance-manager-r-96cc98a0:/# ss -na | wc -l
    863

**With Master-head**
1. root@longhorn-manager-8x2wx:/# ss -na | wc -l
    9555
2. root@instance-manager-r-93dc6a54:/# ss -na | wc -l
    719
3. root@instance-manager-e-a160eb4a:/# ss -na | wc -l
    797

**Comment by joshimoo** [comment]
Below are some of the commands I use to track the socket usage:
```
# just count the time-wait connections
kubectl exec -it longhorn-manager-5rj88 -n longhorn-system -- watch -n 0.5 "ss -ant state time-wait | wc -l"
kubectl exec -it instance-manager-r-41328a3c -n longhorn-system -- watch -n 0.5 "ss -ant state time-wait | wc -l"
kubectl exec -it instance-manager-e-26171a3f -n longhorn-system -- watch -n 0.5 "ss -ant state time-wait | wc -l"


# include summary (-s) + timers (-o)
kubectl exec -it longhorn-manager-5rj88 -n longhorn-system -- watch -n 0.5 "ss -ant -o -s state time-wait"
kubectl exec -it instance-manager-r-41328a3c -n longhorn-system -- watch -n 0.5 "ss -ant -o -s state time-wait"
kubectl exec -it instance-manager-e-26171a3f -n longhorn-system -- watch -n 0.5 "ss -ant -o -s state time-wait"

# check backup status for all engines
kubectl get engines.longhorn.io -n longhorn-system -o name | sed -e 's/.*\///g' | xargs -I {} kubectl get -n longhorn-system engines.longhorn.io {} -o "jsonpath={.status.backupStatus}"
```

We only keep 5 completed backups per replica but an infinite amount of failed backups
https://github.com/longhorn/longhorn-engine/blob/42283ca52d02838dfea437fa0552a2e2ee95447d/pkg/sync/rpc/server.go#L40

So before the fix if their was 50 failed backups on a volume, that would have required 50 connections, now only 1 connection per replica is needed. To test failed backups, probably configuring the minio rate limit would simulate the below issue quite nicely. https://github.com/longhorn/longhorn/issues/2810 


There is some test script I use for volume/backup creation here:
https://github.com/longhorn/longhorn-tests/pull/661

**Comment by khushboo-rancher** [comment]
Verified on Master-head `08/02/2021`

Validation - **Pass**

Verified by creating 20 failed backups and 50 successful backups for 50 volumes each, the socket connections has reduced from previously observed numbers.
```
root@longhorn-manager-dw9t7:/# ss -na | wc -l
7743
```
```
root@instance-manager-e-0ab6a31d:/# ss -na | wc -l
697
```
```
root@instance-manager-r-2aa7b7f0:/# ss -ns | wc -l
10
```

@joshimoo 1 doubt: I can see the difference when created the workload and backups on a master-head cluster but if I have a v1.1.2 set up with 50 volumes and 50 backups each which has lots of socket connections doesn't reduce on upgrading it to master-head

**Comment by joshimoo** [comment]
@khushboo-rancher did you do an engine upgrade for the volumes? Or are they still using the v1.1.2 engine?
Since the fixes are on the engine client side, which we use from the engine-binary. If the volumes are still using the old engine image, they will still be executing the old engine binary.

Also since time-wait connections stick around for 60s the new connection count should be stable again after a maximum wait time of 120s assuming the engine image for the volume has been upgraded to master.

**Comment by khushboo-rancher** [comment]
Okay, I revalidated the upgrade scenario and found that after sometime (~10 mins) I was able to see the reduction in socket connections.

With v1.1.2 I observed the socket connections for 50 volumes with 50 backups each upto ~19000 whereas on v1.1.3-head and master-head, I saw it goes upto ~8000.
