### ISSUE TITLE
[EPIC] Improve communication between components (GRPC)

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2821]
We need to improve the overall communication handling between components.

For the GRPC handling there are currently issues like:
- one shot connections, we end up opening/closing a new connection for a single action (costly)
- reuse connections and rely on the grpc multiplexer to bypass connection establishment (reduces latency)
- better error handling and retry mechanisms

For longhorn-manager <-> engine is using binary invocations as part of the controller reconcile loop.
- the binary invocations should be replaced with grpc communication
- the monitoring should run Independent from the the controller reconcile loop

**Comment by joshimoo** [comment]
Basically one refactor at a time will get us there slowly :)
I layed the ground work for grpc connection reuse here:
https://github.com/longhorn/longhorn-engine/pull/644

This also has an example on replacing the task methods.
The goal should be to eventually turn all task methods into free functions where the consumer passes the client in.

**Comment by innobead** [comment]
See if need to have a LEP for this. Assigned to @c3y1huang.

**Comment by innobead** [comment]
Assigned back to @joshimoo who is working on this.
