### ISSUE TITLE
[QUESTION] How can we ensure volumes from statefulsets with numberofReplicas=1 are scheduled on different nodes in a dedicated storage node scenario ?

### ISSUE THREAD

**Issue by Turb0Fly** [longhorn/longhorn#2823]
Hi, 
I have a question regarding statefulsets when Longhorn with a numberofReplicas = 1 set in the storageclass on dedicated storage nodes .
The cluster has a certain amount of worker nodes but 3 of them are configured as dedicated storage nodes for Longhorn.  We have enabled taints and toleration per https://longhorn.io/docs/1.1.2/advanced-resources/deploy/taint-toleration/ so that only Longhorn workloads can run on those. 

We have 2 Longhorn storage classes, the default one with numberofReplicas=3 and another one with numberofReplicas=1.  We use that last one for applications where the data replication is done at the application level ( e.g. kafka )
When using numberofReplicas=3 all PVs are scheduled accordingly on different nodes, but when deploying a statefulset with 3 replicas with the storage class set at numberofReplicas=1 , we often end up with 1 PV on 1 storage node and 2 other PVs on another storage node.

How can we ensure volumes from statefulsets with numberofReplicas=1 are scheduled on different nodes in such a scenario ?

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version: 1.19.12
 - Node config
   - Ubuntu 18.04 LTS
   - CPU per node: 8
   - Memory per node: 16
   - Disk type : SSD
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMware

**Additional context**

**Comment by joshimoo** [comment]
Just leaving a reference for future csi volume group support.
https://github.com/kubernetes/enhancements/blob/9ab31c34cded378a8ad722c481162ed8999d0cbb/keps/sig-storage/20200212-volume-group.md

**Comment by jenting** [comment]
You want the StatefulSet Pods to spread to different nodes, you could refer to https://medium.com/@johnjjung/building-a-kubernetes-daemonstatefulset-30ad0592d8cb.

**Comment by Turb0Fly** [comment]
Hi @jenting . The pods themselves are deployed to different nodes. It's the volumes that are not.  They are when we do not taint the Longhorn nodes, but as soon as we do ( to have dedicated storage nodes ) , we end up with volumes from the statefulset not being scheduled on different nodes, it could but there is no guarantee.

**Comment by jenting** [comment]
> Hi @jenting . The pods themselves are deployed to different nodes. It's the volumes that are not. They are when we do not taint the Longhorn nodes, but as soon as we do ( to have dedicated storage nodes ) , we end up with volumes from the statefulset not being scheduled on different nodes, it could but there is no guarantee.

From my understanding, I think you want to make the Longhorn volume and replica on the same node.
If yes, you could consider changing the `Default Data Locality` to `best-effort`.
You could set the data locality global-level/storage-class-level/volume-level https://longhorn.io/docs/1.1.2/high-availability/data-locality/#data-locality-settings

**Comment by jenting** [comment]
I'd prefer to close this because it is resolved, feel free to reopen a new question if you have more.
