### ISSUE TITLE
[BUG] fix instance manager grpc connection leak (VersionGet, ProcessLog, ProcessWatch)

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2824]
**Describe the bug**
Fix grpc connection leaks (VersionGet, ProcessLog, ProcessWatch)

- the VersionGet grpc connection is always leaked
- the streaming grpc connections are leaked in the call error case

**To Reproduce**
- call VersionGet a lot of times?
- provocate a init failure of the streaming grpc calls?

**Expected behavior**
instance manager should not leak connections

**Environment:**
 - Longhorn version: 1.1.2

**Comment by joshimoo** [comment]
Can be tested with #2818

**Comment by khushboo-rancher** [comment]
Closing this after validation https://github.com/longhorn/longhorn/issues/2818
