### ISSUE TITLE
[BUG] Datastore::GetEngine returns raw cached object which is then modified

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2827]
**Describe the bug**
The returned engine object is then modified during the sync as well as the monitor
refresh cycles. This in itself is really bad but even worse since the sync
and monitoring routine run concurrently.

**Expected behavior**
Datastore::GetResource functions should always return deep copy objects that are safe to modify.

**Environment:**
 - Longhorn version: 1.2

**Comment by joshimoo** [comment]
Test as part of #2818

**Comment by khushboo-rancher** [comment]
Closing this as the integration tests with branch v1.1.3 and master look okay. The failures are tested on local system, they seemed fine. The failure tests are not due to product failure and are being investigated.
