### ISSUE TITLE
[BUG] v1.1.2 UI "Take Snapshot" & "Create Backup" buttons disabled

### ISSUE THREAD

**Issue by cslauritsen** [longhorn/longhorn#2834]
In previous versions I was able to take snapshots and create backups using the UI buttons. It appears now I can create these resources by creating a cronjob, but not manually, as the buttons are disabled. Is this a bug or intentional. If intentional I would like to understand why. 

# To Reproduce
## 1. Install Longhorn v1.1.2
```bash
#!/bin/bash

set -e

cd $(dirname $0)
echo running $0 from $PWD

# These default configs need to exist before installing longhorn
# they are not referenced after longhorn is installed and running
# and would need to be tweaking using the longhorn ui
kubectl apply -f - <<%
apiVersion: v1
kind: Namespace
metadata: 
 name: longhorn-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-setting.yaml: |-
    backup-target: nfs://192.168.1.5:/docker-data/nfs-share/longhorn-backups/
    create-default-disk-labeled-nodes: false
    default-data-path: /var/lib/longhorn/
    replica-soft-anti-affinity: false
    storage-over-provisioning-percentage: 600
    storage-minimal-available-percentage: 15
    upgrade-checker: false
    default-replica-count: 3
    guaranteed-engine-cpu:
    default-longhorn-static-storage-class: longhorn-static
    backupstore-poll-interval: 500
    taint-toleration: key1=value1:NoSchedule; key2:NoExecute
%

# Workaround from https://github.com/longhorn/longhorn/issues/1861
#curl -L https://raw.githubusercontent.com/longhorn/longhorn/v1.0.1/deploy/longhorn.yaml \

curl -L https://raw.githubusercontent.com/longhorn/longhorn/v1.1.2/deploy/longhorn.yaml \
 | sed \
 -e 's/#- name: KUBELET_ROOT_DIR/- name: KUBELET_ROOT_DIR/g' \
 -e 's$#  value: /var/lib/rancher/k3s/agent/kubelet$  value: /var/lib/kubelet$g' \
 | kubectl apply -f -
```
## 4. Note disabled buttons
Both the static buttons in the upper right of the "Snapshots and Backups" pane are disabled, as well as the "Take Snapshot" context menu item when clicking on "Volume Head"
<img width="1879" alt="image" src="https://user-images.githubusercontent.com/4185468/128035457-0c71dca2-0092-4b35-ba8c-741145fbfe32.png">

**Expected behavior**
The "Take Snapshot" & "Create Backup" buttons would be clickable, and would do as their names intend.

**Environment:**
 - Longhorn version: 1.1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s, v1.21.3+k3s1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 0 (masters are workers)
 - Node config
   - OS type and version: oracle linux 8.3
   - CPU per node: 6 @Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
   - Memory per node: 16Gi
   - Disk type(e.g. SSD/NVMe): nvme
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal
 - Number of Longhorn volumes in the cluster: 6

**Additional context**

**Comment by jenting** [comment]
Are all the volume occurs the same problem?
There're some scenarios that the button be disabled
- It's a DR volume
- The volume is taking the snapshot
- The volume is upgrading the engine image
- The volume CR current image (`status.currentImage`) not equals o the engine image (`spec.engineImage`)

cc @smallteeths to have more input on this.

**Comment by smallteeths** [comment]
The condition for the front-end judgment button to be disabled is

1. volume.actions.snapshotCreate do not exists
2. It's a DR volume (volume.standby==true)
3. The engine is being upgraded (volume.currentImage !== volume.engineImage)
4. volume is Restoring (volume.restoreStatus != isRestoring)

cc @jenting 

Can you post the volume detail data for me to check @cslauritsen  ? thanks

**Comment by cslauritsen** [comment]
Sure. Also, the ui doesn't show any snapshots in the timeline. Maybe they don't exist even when the scheduled job runs? 

```yaml
apiVersion: longhorn.io/v1beta1
kind: Volume
metadata:
  creationTimestamp: "2021-08-02T18:24:33Z"
  finalizers:
  - longhorn.io
  generation: 2
  labels:
    longhornvolume: poscdb-pv
  name: poscdb-pv
  namespace: longhorn-system
  resourceVersion: "4108504"
  uid: 1044f645-5cef-4201-b38b-7d18e29c73b2
spec:
  Standby: false
  accessMode: rwo
  backingImage: ""
  baseImage: ""
  dataLocality: disabled
  disableFrontend: false
  diskSelector: []
  engineImage: longhornio/longhorn-engine:v1.1.2
  fromBackup: nfs://192.168.1.5:/docker-data/nfs-share/longhorn-backups/?backup=backup-1c1d9d1253e3450a&volume=pvc-b2714970-22d6-4af5-b73b-fcf0f92935bd
  frontend: blockdev
  lastAttachedBy: ""
  migratable: false
  migrationNodeID: ""
  nodeID: master-c.site.local
  nodeSelector: []
  numberOfReplicas: 3
  recurringJobs: null
  revisionCounterDisabled: false
  size: "53687091200"
  staleReplicaTimeout: 20
status:
  actualSize: 89219645440
  conditions:
    restore:
      lastProbeTime: ""
      lastTransitionTime: "2021-08-02T19:06:11Z"
      message: ""
      reason: ""
      status: "False"
      type: restore
    scheduled:
      lastProbeTime: ""
      lastTransitionTime: "2021-08-02T18:24:34Z"
      message: ""
      reason: ""
      status: "True"
      type: scheduled
    toomanysnapshots:
      lastProbeTime: ""
      lastTransitionTime: "2021-08-02T18:24:34Z"
      message: ""
      reason: ""
      status: "False"
      type: toomanysnapshots
  currentImage: longhornio/longhorn-engine:v1.1.2
  currentNodeID: master-c.site.local
  expansionRequired: false
  frontendDisabled: false
  isStandby: false
  kubernetesStatus:
    lastPVCRefAt: ""
    lastPodRefAt: ""
    namespace: xstore-db
    pvName: poscdb-vol-0
    pvStatus: Bound
    pvcName: data-poscdb-0
    workloadsStatus:
    - podName: poscdb-0
      podStatus: Running
      workloadName: poscdb
      workloadType: StatefulSet
  lastBackup: ""
  lastBackupAt: ""
  lastDegradedAt: ""
  ownerID: master-c.site.local
  pendingNodeID: ""
  remountRequestedAt: ""
  restoreInitiated: true
  restoreRequired: false
  robustness: healthy
  shareEndpoint: ""
  shareState: ""
  state: attached
```

**Comment by jenting** [comment]
Have you configure traefik as ingress controller?

Could you please add browser developer mode to see if there is any error HTTP status when you accessing the Longhorn GUI?

**Comment by cslauritsen** [comment]
Yes, I am using traefik for ingress. Indeed there are some errors:

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/4185468/128170852-277d05b0-d51d-4812-97b5-77a3ff389729.png">

**Comment by jenting** [comment]
Since k3s now uses Traefik 2.x by default.
Please check the [knowledge base](https://longhorn.io/kb/troubleshooting-traefik-2.x-as-ingress-controller/)

**Comment by cslauritsen** [comment]
If I load the page with HTTP (instead of HTTPS), the buttons are available to click, but if I click "Take Snapshot", the console shows the same error again (slightly different).
# Reload page, before click:
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/4185468/128171258-f9bfcced-15fa-4972-9f64-c65a0c0182bc.png">

# After click
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/4185468/128171343-34900610-ddb0-4907-b2a5-b04b10b46771.png">

**Comment by cslauritsen** [comment]
At @jenting's urging, [this kb article](https://longhorn.io/kb/troubleshooting-traefik-2.x-as-ingress-controller/) fixed this issue which is specific to traefik 2.x. 

Thanks, @jenting & @smallteeths. Closing the issue.
