### ISSUE TITLE
[TASK] integrate security scanning into Longhorn CI pipeline.

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#2839]
**What's the task? Please describe.**
integrate FOSSA security scanning into CI pipeline

**Describe the items of the task (DoD, definition of done) you'd like.**
- [ ] integrate FOSSA security scanning into our CI pipeline

**Additional context**
Add any other context or screenshots about the task request here.

**Comment by innobead** [comment]
Closing due to the integration is ready in each component repos and it will be periodically scanned and reported in the fossa dashboard.

cc @jenting
