### ISSUE TITLE
[FEATURE] UI support encrypted volumes

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2841]
**Is your feature request related to a problem? Please describe.**
We want to have UI support for encrypted volumes: 
- volume display operations need to be able to show that a volume is `Encrypted`
- volume creation operations need to allow the user to specify the boolean`Encrypted` field. 
- PV creation operations need to allow the user to specify the `secretNamespace` and `secretName` parameters.

**Describe the solution you'd like**
- display Encryption Status for volumes (if volume `Encrypted` == true, maybe some kind of lock icon?)
- create encrypted volumes via the UI (allow setting parameter `Encrypted` on Volume to true (checkbox))
- restore encrypted volumes (allow setting parameter `Encrypted` on Volume to true (checkbox))
- create PV with secret reference (allow setting parameters `secretNamespace` and `secretName` as part of the PVCreate request (text input), in case the Volumes `Encrypted` parameter == true)

**Additional context**
https://github.com/longhorn/longhorn/issues/1859

**Comment by joshimoo** [comment]
The encrypted field is available after https://github.com/longhorn/longhorn-manager/pull/976 is merged.
I manually tested the backend via manual posts against the backed PV creation endpoint.

**Comment by joshimoo** [comment]
@smallteeths @meldafrawi The DR volume creation also needs the check box for Encrypted as well as any other operation that creates a volume. REF: https://github.com/longhorn/longhorn/issues/1859#issuecomment-900759320

In the future we can store that information as part of the volume.cfg in the backupstore, but for this release it's okay if the user manually specifies it.

**Comment by innobead** [comment]
> @smallteeths @meldafrawi The DR volume creation also needs the check box for Encrypted as well as any other operation that creates a volume. REF: [#1859 (comment)](https://github.com/longhorn/longhorn/issues/1859#issuecomment-900759320)
> 
> In the future we can store that information as part of the volume.cfg in the backupstore, but for this release it's okay if the user manually specifies it.

@joshimoo please help create an issue for this, then we follow up in the future. Thanks.

**Comment by meldafrawi** [comment]
Validation effort will be tracked as part of  https://github.com/longhorn/longhorn/issues/1859 validation.
