### ISSUE TITLE
[TASK] backport base image updates to v1.1.3 images

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#2842]
**What's the task? Please describe.**
we need to backport base image and dependencies updates to v1.1.3 images

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] longhorn-manager
- [x] longhorn-engine
- [x] ~longhorn-intance-manager~ (https://github.com/longhorn/longhorn-instance-manager/pull/94)
- [x] ~longhorn-share-manager~ (https://github.com/longhorn/longhorn-share-manager/pull/15)
- [x] ~backing-image-manager~ (https://github.com/longhorn/backing-image-manager/pull/21)
- [x] longhorn-ui 

**Additional context**
Add any other context or screenshots about the task request here.

**Comment by innobead** [comment]
@meldafrawi is this still valid? If yes, please update the ticket description to describe what the source of PRs needs to backport?
