### ISSUE TITLE
[BUG] Failed AKS upgrade leaves sharemanager pvc pod erroring.

### ISSUE THREAD

**Issue by tbertenshaw** [longhorn/longhorn#2844]
I have a moodle deployment on a 3 node `AKS `1.21.1 cluster with the moodle pvc being `RWX `and with 3 replicas of the pvc.
Longhorn is version `1.1.1`

Stupidly i thought upgrading AKS 1.21.1 =>1.21.2 would be handled seamlessly but this failed as it couldnt drain the first node it cordoned.  So i have uncordoned that node.

So im trying to salvage the workload. The pods are failing on container creating with
` The volume pvc-42c8de58-REDACTED share should be available before the mount`

I can see the longhorn pod `share-manager-pvc-42c8de58-REDACTED` is erroring with

time="2021-08-05T09:21:07Z" level=warning msg="waiting with nfs server start, volume is not attached" volume=pvc-42c8de58-REDACTED

This pod is running on `node 2` and `node 1` was originally cordoned (uncordoned now) but when i look at the volume in the longhorn UI i can see that it is attached to `node 1`. And that it is healthy.

So I'm thinking that the share-manager-pvc pod was originally running on `node 1` and then when `node 1` was cordoned it got recreated on `node 2` (Where the share doesnt exist).  

So I have a few questions.

- how can i restore the pvc share and thus moodle deployment?
- How can i (manually if possible #2787 ) backup the data in this volume so i can recopy it onto a new pvc volume if i need to.
- What strategy should i use if i ever want to upgrade the node aks version in the future?

**Comment by joshimoo** [comment]
Multiple ways to work around this, scale down the moodle deployment = 0. should end up terminating the share-manager pod.

Then check the longhorn UI to see if the volume gets detached from node1, if not detached after everything is scaled down. Manually invoke the detach option from the UI.

I am guessing you are running into an attach/detach issue we made some fixes in v1.1.2 for this.

**Comment by tbertenshaw** [comment]
Would you recommend upgrading to 1.1.2? Could this have issues with existing workload/volumes?

Also i would like to manually copy the data for backup before is there a process for this?

**Comment by joshimoo** [comment]
@tbertenshaw since the volume is currently attached to node1 you can just mount the volume into a directory to take a backup of the filesystem data. You can also do a `dd if=/dev/longhorn/<volume> of=/path-to-backup-storage/<volume-name>` if you want to do a block by block backup of the full block device.

**Comment by tbertenshaw** [comment]
Ok @joshimoo i backed up the volume as suggested.

I scaled the rs to 0 from 3 which seems to have recreated the share manager which is now on node 2 again.  I Cannot see any erroring pods. However the longhorn UI is showing the volume as degraded and the replica on node 2 as Failed and stopped.

My moodle pods are responding however.

**Comment by tbertenshaw** [comment]
Whoops scrap that. Some minutes later I can see the the node 2 replica is running/ then rebuilding and now its running.

Ok so I'm guessing i need to upgrade to 1.1.2 in order to allow AKS to upgrade safely.

**Comment by jenting** [comment]
Good to see if you could upgrade to Longhorn `v1.1.2`.

**Comment by innobead** [comment]
Closing because the volume attache/detach issue was resolved in 1.1.2. Feel free to reopen if still encounter the same issue.
