### ISSUE TITLE
[BUG] Replica rebuilding fails and eventually pass after few attempts

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2849]
**Describe the bug**
Replica rebuilding fails first and after try few times, it successfully completes.

**To Reproduce**
1. Create a volume with 3 replicas and attach it to a pod.
2. Delete one of the replica.
3. Observe the replica initially fails and then after few tries it successfully completes.  

**Expected behavior**
The replica rebuilding should successfully completes in 1st attempt.

**Log**
Master- head
[longhorn-support-bundle_3b25eb63-af9c-4b91-8266-e8b3df23529e_2021-08-06T19-40-29Z.zip](https://github.com/longhorn/longhorn/files/6947790/longhorn-support-bundle_3b25eb63-af9c-4b91-8266-e8b3df23529e_2021-08-06T19-40-29Z.zip)

v1.1.2 - where it worked fine
[v1.1.2.log](https://github.com/longhorn/longhorn/files/6947834/v1.1.2.log)

**Environment:**
 - Longhorn version: master-head `08/06/2021`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl 
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.20.9 RKE
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3

**Additional context**
Works fine with v1.1.2

**Comment by PhanLe1010** [comment]
I have identify one root cause mentioned in the PR https://github.com/longhorn/longhorn-manager/pull/977

There is one thing I don't understand yet that is why this rebuilding racing problem doesn't happen with v1.1.2. Is there recent change that make this racing problem more likely to happen? Need more investigation about this.

**Comment by PhanLe1010** [comment]
This problem also happens in v1.1.3 as observed by @khushboo-rancher

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master `08/10/2021` and v1.1.3-head

Validation - **Pass**

The rebuilding is successfully completing in 1st attempt.
