### ISSUE TITLE
[QUESTION] Longhorn and Kubernetes-Support V1.22.0?

### ISSUE THREAD

**Issue by CoreTechnologyAG** [longhorn/longhorn#2852]
Does Longhorn Support the latest kubernetes-Release v1.22.0?
- Kubernetes V1.21.3: If we upgrade the kubernetes-Cluster to v1.21.3 longhorn runs normal. 
- Kubernetes V1.22.0: If we upgrade to v1.22.0 we got log-Messages "Failed to list *v1beta1.CSIDriver: the server could not find the requested resource"

Actually we have a problem on all longhorn-manager-instances after the upgrade to V1.22.
In the Log is written:
E0806 16:46:33.820272       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.CSIDriver: the server could not find the requested resource

And  longhorn doesn't run anymore.

We used the yaml-File: https://github.com/longhorn/longhorn/blob/master/deploy/longhorn.yaml with some small changes like backup-target, default-data-path etc.

**Environment:**
 - Longhorn version: V1.1.2
 - Kubernetes version: v1.22.0
 - Node config
   - OS type and version: Ubuntu 20.04.2 LTS
   - CPU per node: 8 to 12
   - Memory per node: 32 to 64
   - Disk type: ssd
   - Network bandwidth and latency between the nodes: 1GB
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal (Prod) / VM )(Test)

kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:57:25Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

kubelet --version
Kubernetes v1.22.0

kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:02:08Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

## Infrastructure
kubectl get nodes
NAME           STATUS   ROLES                  AGE    VERSION
xxx241   Ready    control-plane,master   220d   v1.22.0
xxx242   Ready    control-plane,master   220d   v1.22.0
xxx271   Ready    <none>                 220d   v1.22.0
xxx272   Ready    <none>                 220d   v1.22.0
xxx273   Ready    <none>                 220d   v1.22.0

## api-resources
kubectl api-resources | grep storage
csidrivers                                                                 storage.k8s.io/v1                      false        CSIDriver
csinodes                                                                   storage.k8s.io/v1                      false        CSINode
csistoragecapacities                                                       storage.k8s.io/v1beta1                 true         CSIStorageCapacity
storageclasses                      sc                                     storage.k8s.io/v1                      false        StorageClass
volumeattachments                                                          storage.k8s.io/v1                      false        VolumeAttachment

kubectl api-resources | grep -Ii csi
csidrivers                                                                 storage.k8s.io/v1                      false        CSIDriver
csinodes                                                                   storage.k8s.io/v1                      false        CSINode
csistoragecapacities                                                       storage.k8s.io/v1beta1                 true         CSIStorageCapacity

Thanks for the feedback.
Ritzo

**Comment by innobead** [comment]
ref: https://github.com/longhorn/longhorn/issues/2851 

The next minor release (v1.2.0) will support K8s v1.22.

**Comment by kalavt** [comment]
> ref: #2851
> 
> The next minor release (v1.2.0) will support K8s v1.22.

I don't see it in v1.2.0 preview version.
