### ISSUE TITLE
[BUG] VolumeAttachments.storage.k8s.io is not found for the primary node of statefulset cluster on node restart

### ISSUE THREAD

**Issue by Premfer** [longhorn/longhorn#2855]
Longhorn version 1.1.1 , Rancher 2.5.9 whenever a node restarts or the Rancher itself , the statefulsets goes to in progress state and the primary node of the cluster (eg mongdb-0 pod of mongodb) is in terminating state with error VolumeAttachments.storage.k8s.io csi- not found . Kindly let know how to investigate this issue

**Comment by innobead** [comment]
ref: https://github.com/longhorn/longhorn/issues/2629 

This seems an already resolved issue in 1.1.2. cc @joshimoo

**Comment by Premfer** [comment]
Thanks @innobead for the very quick response. I am using Rancher to upgrade longhorn, when will this version 1.1.2 be available in the marketplace or shall I upgrade the longhorn manually. will this have any consequences?

**Comment by innobead** [comment]
The answer you should be able to find from rancher https://github.com/rancher/charts/issues/1352. I believe it should be soon or later in the following minor (2.6.0) or patch (2.5.10) release.
