### ISSUE TITLE
[FEATURE] HA backing image

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2856]
**Is your feature request related to a problem? Please describe.**
After download/upload/exporting from volumes, backing images need to be stored across different nodes immediately in case the node stores data unavailable.

**Additional context**
This is a feature that hasn't been done in #2530

**Comment by bk201** [comment]
Found some behavior in Harvester, hope this will be improved together.

For a backing image that has no volumes derived from it:
- Evicting the Longhorn disk containing it doesn't evict the backing image to other disks.
- Draining the node containing the backing image doesn't move the image data either.

The backing image seems not to consider scheduling:
- Disable scheduling for all disks.
- Create a new backing image; the backing image is saved to one of them.

**Comment by innobead** [comment]
> Found some behavior in Harvester, hope this will be improved together.
> 
> For a backing image that has no volumes derived from it:
> 
> * Evicting the Longhorn disk containing it doesn't evict the backing image to other disks.
> * Draining the node containing the backing image doesn't move the image data either.
> 
> The backing image seems not to consider scheduling:
> 
> * Disable scheduling for all disks.
> * Create a new backing image; the backing image is saved to one of them.

:point_up: this is good info. Basically, we should treat backing image as volume replica, so the behavior related to resilience and availability should be similar.

**Comment by yangchiu** [comment]
@chriscchien Please help check if [test case `test_setting_backing_image_auto_cleanup`](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/896/testReport/tests/test_settings/test_setting_backing_image_auto_cleanup/) can pass after https://github.com/longhorn/longhorn-tests/pull/1877 merged. Many thanks.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `0a1d3a`) with test [steps](https://github.com/longhorn/longhorn/issues/2856#issuecomment-2089737102)

Waiting https://github.com/longhorn/longhorn/issues/2856#issuecomment-2208181883 to beresolved first, if no new issues are found, I will close this ticket, thanks.

**Comment by chriscchien** [comment]
Found issue when multiple `nodeSelector`  or `diskSelector` were set to backing image, need to verify again after https://github.com/longhorn/longhorn/issues/6526#issuecomment-2209904516

**Comment by ChanYiLin** [comment]
Hi @chriscchien 
The test PR: https://github.com/longhorn/longhorn-tests/pull/1877 was merged
And the `multiple nodeSelector or diskSelector` issue was clarified
please take a look again, thanks!

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `81d46a2`)

- test steps verified [here](https://github.com/longhorn/longhorn/issues/2856#issuecomment-2208303625) without any problems
- Backing image related pytest test cases all [passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7206/)
    - [test_backup_failed_disable_auto_cleanup](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/969/testReport/tests/test_basic/test_backup_failed_disable_auto_cleanup_nfs_/) passed as well
