### ISSUE TITLE
[QUESTION] Can I run pod with longhorn volume on node without longhorn running

### ISSUE THREAD

**Issue by MatanAmoyal** [longhorn/longhorn#2858]
**Question**

**Environment:**
 - Longhorn version: 1.1.2
 - Kubernetes version:  v1.16.15 
 - Node config
   - OS type and version CentOS 7
   - CPU per node: 16
   - Memory per node: 100+
   - Disk type 1T
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): on-premise k8s

**Additional context**

Hello,
I have k8s cluster with several nodes. one of the nodes don't have disk with high size. so i prevent from longhorn components to run on this node (using NodeSelector).
Do I have any option to run pod with longhorn volume on this node? because this node have high number of cpu and ram memory and I want to use it :)

**Comment by shuo-wu** [comment]
You can use node selectors to make sure the replicas of a volume are scheduled to the node that contains large disks. Then this volume can be attached to the node you want to run applications on. Notice that the volume being attached to a node doesn't mean the volume data will be stored on this node. The replicas of volumes hold all volume data. Hence, the volume can fit your requirement **as long as its replicas are not on the nodes don't have disk with high size**.

**Comment by MatanAmoyal** [comment]
Thanks for your answer @shuo-wu 

Right now, if i run a pod with longhorn volume on node that not running the longhorn components, i get the following error:
AttachVolume.Attach failed for volume "pvc-4a408225-3014-4398-92be-fc192ab8f6a2" : csinode.storage.k8s.io "server04" not found

Can you tell what exactly longhorn components i need to run on "server04" - the one with low disk size?
I guess it is one or more of the following deamonsets:
engine-image-ei
longhorn-csi-plugin
longhorn-manager

**Comment by shuo-wu** [comment]
There should pods `longhorn-manager`, `engine-image-ei`, and `instance-manager-e` for each node. Otherwise, you cannot run a pod with Longhorn volumes on the node.

**Comment by MatanAmoyal** [comment]
ok, but how I can prevent from the data to be saved on the node with low disk? what is the longhorn specific component that i need to set  NodeSelector?

**Comment by shuo-wu** [comment]
There are 2 ways to avoid Longhorn using low disks:
  1. Directly disable the scheduling for these disks.
  2. Add tags for the disks that contain enough space. Then set the corresponding node/disk selectors during the volume creation/scaling up.

**Comment by jenting** [comment]
The question has been addressed, close this issue/question.
Feel free to open a new issue _or_ question if you have further ones.
