### ISSUE TITLE
[TASK] DOC: Make sure user understand the default installation process is not for production usage

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2859]
**What's the task? Please describe.**
We need to update the installation document e.g. items under https://longhorn.io/docs/1.1.2/deploy/install/ to make sure users understand it's not for production. 

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] Update the installation documentation

**Additional context**
This is one thing we discovered as somehow confusion during the Longhorn incubation DD process.

**Comment by innobead** [comment]
Done and the doc updated.
