### ISSUE TITLE
[BUG] Volume creation from Longhorn GUI fails 

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2860]
**Describe the bug**
Volume creation fails from Longhorn GUI

**To Reproduce**
1. Go to Longhorn UI.
2. Click `Create Volume`
3. Enter Volume name and click ok.
4. Volume doesn't get created and call returns 504 error. `504 Gateway Time-out`

Volume Api request:
```
{"name":"volume-test-1","size":"20Gi","numberOfReplicas":3,"frontend":"blockdev","dataLocality":"disabled","accessMode":"rwo","backingImage":"","replicaAutoBalance":"ignored","revisionCounterDisabled":false,"encrypted":false,"nodeSelector":[],"diskSelector":[],"staleReplicaTimeout":20,"fromBackup":""}
```

**Expected behavior**
Volume should be successfully created.

**Environment:**
 - Longhorn version: Longhorn - master `c09ac49`

**Comment by khushboo-rancher** [comment]
This could be because the volume encryption enhancement UI is merged but the backend is not fully merged.

**Comment by jenting** [comment]
Same as https://github.com/longhorn/longhorn/issues/2861#issuecomment-896438860

**Comment by shuo-wu** [comment]
The root cause analysis and the fix are in https://github.com/longhorn/longhorn/issues/2869

**Comment by khushboo-rancher** [comment]
Closing after the validation of https://github.com/longhorn/longhorn/issues/2869
