### ISSUE TITLE
[QUESTION] Is there timer that can be set to speed up the multi attach error to allow quicker failover during dead node situation?

### ISSUE THREAD

**Issue by bodleytunes** [longhorn/longhorn#2863]
**Question**

**Environment:**
 - Longhorn version: Stable / Most recent
 - Kubernetes version: k3s 1.2.x stable + Rancher
 - Node config: 3 nodes
   - OS type and version: debian 10
   - CPU per node: 2vcpu
   - Memory per node:  8gb
   - Disk type: ext4 volumes and glusterFS
   - Network bandwidth and latency between the nodes:  ~400mbits private overlay
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):  Hetzner Cloud

Hi All,
Just a quick query really.  I was testing pulling the power on a node and I see Kubernetes tries to spin up the pods on a new node within 20 or 30 seconds but then I get the multi attach error for 5 to 7 minutes before something times out and finally I'm able to attach the storage again.

I was wondering if there is a timer somewhere where I can reduce this somehow?

Multi-Attach error for volume "pvc-5ee8a40e-1902-40b8-a25b-ddd63aaff2dc" Volume is already used by pod(s) plex-7574bd5cf8-7cpqz

Is this a timer I can set in longhorn or is it something native to kubernetes/k3s?

Many thanks,

Jon.

[UPDATE/CORRECTION]

Just to say the time is actually 10 mins before a failover happens
![image](https://user-images.githubusercontent.com/619239/128940610-5ff87433-d1c9-4249-8a40-f4e5f323f1d0.png)

**Comment by shuo-wu** [comment]
I am curious that why the pod will try to use volumes that are already attached by others? The ultimate way for this issue is to guarantee the volume detachments before starting pod using them. 

As for the question you ask, I am not sure if manually deleting the resource `VolumeAttachment` for the volumes can help speed up the retry. Longhorn cannot control this backoff/failover interval.

**Comment by bodleytunes** [comment]
It's just one stateful pod, I can't run multiple as plex doesn't work that way, so its a one 2 one mapping between the pod and its volume. 

So when a node dies, rather than let a load balancer forward traffic to another pod, this pod needs to be killed and respawn, I guess similar to a VM would be.

It would be nice to run mutiple plex pods and failover be seemless but the way the app is written its stateful.  There is a kubeplex   repo but its been disowned last I looked.

So back to the original point was I just thought there maybe  timer I can look at to spped up this 10 min failover by forcinng the volume to be released when a node is down.

All the other timers I've tweaked to get a new pod to spin up in 10 to 20 seconds but it can't finish loading as the storage volume is stuck.

Should I post in kubernetes, it might be something more fundamental to kubernetes rather than longhorn im thinking, or maybe K3S ?

Cheers!
Jon.

**Comment by shuo-wu** [comment]
Maybe you can check or directly post a question on the Kubernetes side.

But based on your use case, I think Longhorn setting `Pod Deletion Policy When Node is Down` may help. You can check if this setting works before asking the question on the Kubernetes side.

**Comment by bodleytunes** [comment]
Ok thanks will give it a look in later.

**Comment by joshimoo** [comment]
@bodleytunes you probably want to configure the default eviction settings. Or per pod eviction tolerations that get added by kubernetes. 

```
Kubernetes automatically adds a toleration for node.kubernetes.io/not-ready and node.kubernetes.io/unreachable with tolerationSeconds=300, unless you, or a controller, set those tolerations explicitly.

These automatically-added tolerations mean that Pods remain bound to Nodes for 5 minutes after one of these problems is detected.
```
https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

`--pod-eviction-timeout `: 
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

**Comment by bodleytunes** [comment]
I'm using the following:
it seems to try to fail over pods to the working nodes quickly, but they
can't start due to the volume not being able to be attached to the new pod

 --kubelet-arg node-status-update-frequency=4s
--kube-controller-manager-arg node-monitor-period=2s
--kube-controller-manager-arg node-monitor-grace-period=16s
--kube-apiserver-arg default-not-ready-toleration-seconds=10
--kube-apiserver-arg default-unreachable-toleration-seconds=10

**Comment by bodleytunes** [comment]
Will try the pod eviction timeout and report back.

**Comment by jenting** [comment]
Any feedback @bodleytunes?
Otherwise, I'd prefer to close this issue.

**Comment by bodleytunes** [comment]
Got it sorted with timeouts, in the end, you can close the ticket :-)

**Comment by bodleytunes** [comment]
Hey I thought I had this fixed but it seems after building my clusters again with what I think were the right settings, I'm still having issues where the new pod wont start

![image](https://user-images.githubusercontent.com/619239/141466864-67ef577e-cdbc-433c-b6b7-47494f8000bd.png)

![image](https://user-images.githubusercontent.com/619239/141466889-bc8dee2f-7f25-4c66-a712-e0c00a623af1.png)

I'm not sure why it is doing this, the old pod has been terminated.

**Comment by bodleytunes** [comment]
```
Events:
  Type     Reason                  Age                 From                     Message
  ----     ------                  ----                ----                     -------
  Normal   Scheduled               12m                 default-scheduler        Successfully assigned default/plex-556f7f5c7b-p759x to rancher1
  Warning  FailedAttachVolume      12m                 attachdetach-controller  Multi-Attach error for volume "pvc-eafbeed8-2ceb-4500-af79-4e6ffef40d78" Volume is already used by pod(s) plex-556f7f5c7b-mfmvt
  Warning  FailedMount             6m4s (x3 over 10m)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[plexconfig], unattached volumes=[plexconfig kube-api-access-7h7jh]: timed out waiting for the condition
  Warning  FailedMount             3m50s               kubelet                  Unable to attach or mount volumes: unmounted volumes=[plexconfig], unattached volumes=[kube-api-access-7h7jh plexconfig]: timed out waiting for the condition
  Normal   SuccessfulAttachVolume  3m45s               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-eafbeed8-2ceb-4500-af79-4e6ffef40d78"
  Normal   Pulling                 2m17s               kubelet                  Pulling image "linuxserver/plex"
  Warning  FailedMount             27s (x2 over 31s)   kubelet                  MountVolume.MountDevice failed for volume "pvc-eafbeed8-2ceb-4500-af79-4e6ffef40d78" : rpc error: code = InvalidArgument desc = volume pvc-eafbeed8-2ceb-4500-af79-4e6ffef40d78 hasn't been attached yet
```

**Comment by bodleytunes** [comment]
OK seemed to finally mount the volume but must have taken 12+ minutes ! :(  Not sure if this is because of a setting I have or whether its some change in the newer versions of k3s or whatever?

**Comment by shuo-wu** [comment]
When did your volume get **attached**? In the 1st step, we need to check which step takes such a long time.

BTW, notice that you are using v1.2.0, which is affected by a critic bug https://github.com/longhorn/longhorn/issues/2964. I would suggest you upgrade to v1.2.2 to avoid it.

**Comment by abrondijk** [comment]
@bodleytunes Did you ever solve this issue?
I'm facing the exact same issue, when the node goes offline, the scheduler waits the default eviction time before terminating the original pod. The new pod cannot be spun up though, because the volume is still attached to the offline node.
Around 8 minutes after the new pod was created (but not started), the volume does end up detaching from the offline node and the pod will start up fine.

This seems to be another setting/timeout that can be changed, but I'm struggling to find what that might be. Anyone have any ideas?

**Comment by shuo-wu** [comment]
@abrondijk Are you talking about this issue https://github.com/longhorn/longhorn/issues/3584? For this issue, Longhorn cannot help a lot...

**Comment by abrondijk** [comment]
@shuo-wu Ah I found that issue shortly after I replied here.
I was hoping I wasn't referring to that but it seems as though I was.
Thanks for your quick response anyway!

**Comment by innobead** [comment]
https://github.com/longhorn/longhorn/issues/2947 can help with this issue. cc @PhanLe1010

**Comment by PhanLe1010** [comment]
User can set this setting if they want Kubernetes to quickly evicting the pod from down nodes: https://github.com/longhorn/longhorn/issues/3584#issuecomment-1032163442. Longhorn cannot make it faster than 7-8 minutes with the default Kubernetes value
