### ISSUE TITLE
[TASK] Remove deprecated volume spec recurringJobs and storageClass recurringJobs field

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2865]
**What's the task? Please describe.**
Deprecate the volume spec recurringJobs and storageClass recurringJobs field. This is replaced by https://github.com/longhorn/longhorn/issues/467.

**Describe the items of the task (DoD, definition of done) you'd like.**
- [ ] Deprecate the volume spec recurringJobs and storageClass recurringJobs field.

**Additional context**
https://github.com/longhorn/longhorn/pull/2737#discussion_r686103306
https://github.com/longhorn/longhorn/issues/467
https://github.com/longhorn/longhorn/issues/2866

**Comment by shuo-wu** [comment]
We need to check `RecurringJobSpec` as well. e.g., the field `RecurringJobSpec.Name` should be removed.

**Comment by c3y1huang** [comment]
I've got a couple of places with reminder notes like this.
```
// TODO: this is for the recurringJobs in volume spec and recurringJobs in
// storageClass. Should be removed when recurringJobs gets removed from
// storageClass parameters.
```

**Comment by derekbit** [comment]
@

> I've got a couple of places with reminder notes like this.
> 
> ```
> // TODO: this is for the recurringJobs in volume spec and recurringJobs in
> // storageClass. Should be removed when recurringJobs gets removed from
> // storageClass parameters.
> ```

@c3y1huang Thanks for the hints. 👍

**Comment by derekbit** [comment]
After quick investigation, we cannot remove `volume.spec.VolumeRecurringJobSpec` now, because the upgrade from v1.1.0 to v1.2.0 still needs it.
https://github.com/longhorn/longhorn-manager/blob/master/upgrade/v110to120/upgrade.go#L298

**Comment by innobead** [comment]
> After quick investigation, we cannot remove `volume.spec.VolumeRecurringJobSpec` now, because the upgrade from v1.1.0 to v1.2.0 still needs it. [https://github.com/longhorn/longhorn-manager/blob/master/upgrade/v110to120/upgrade.go#L298](https://github.com/longhorn/longhorn-manager/blob/master/upgrade/v110to120/upgrade.go?rgh-link-date=2022-06-06T07%3A34%3A42Z#L298)
> 
> cc @c3y1huang @innobead

Thanks, @derekbit , then we need to enforce the upgrade path instead of all paths included instead. Let's do it in 1.4.

**Comment by weizhe0422** [comment]
I think there are a few places that need to be removed including:
 - API resource, e.g., `VolumeRecurringJobSpec` in `k8s/pkg/apis/longhorn/v1beta2/volume.go`
   - using `generate_code.sh` to re-generate, and the related `DeepCopy` function should be removed
   - `volumes.longhorn.io/spec/recurringJobs` in `k8s/crds.yaml` should be removed
   - https://github.com/longhorn/longhorn-manager/blob/fe05edbb43151d0540a870c8f5d2f4625c4fac6a/k8s/pkg/apis/longhorn/v1beta2/volume.go#L135-L150
 - upgrade from v1.1.0 to V1.2.0: `volume.Spec.RecurringJobs`
   - https://github.com/longhorn/longhorn-manager/blob/fe05edbb43151d0540a870c8f5d2f4625c4fac6a/upgrade/v110to120/upgrade.go#L296-L321
 - volume mutating function 
   - https://github.com/longhorn/longhorn-manager/blob/fe05edbb43151d0540a870c8f5d2f4625c4fac6a/webhook/resources/volume/mutator.go#L69-L80
   - https://github.com/longhorn/longhorn-manager/blob/fe05edbb43151d0540a870c8f5d2f4625c4fac6a/webhook/resources/volume/mutator.go#L235-L245

**Comment by chriscchien** [comment]
Verified **pass** in longhorn master(longhorn `7b3b23`, longhorn-manager `023dd3`)

- In v1.5.0-dev fresh install, volume spec does not have key recurringJobs.
- Create volume in v1.4.2 then upgrade to v1.5.0-dev, the recurringJobs in volume.spec removed after upgrade.
- In daily regression, no outstanding error related to volume and recurring job
   - [mater branch regression](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/501/)
   - [upgrade test](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/481/#showFailuresLink)
   - [2 stage upgrade test](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-2-stage-upgrade-tests-sles-amd64/190/)
