### ISSUE TITLE
[TASK] Deprecate notice for volume spec recurringJob and storageClass recurringJob field.

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2866]
**What's the task? Please describe.**
Need a deprecation notice for the volume spec recurringJob and storageClass recurringJobs field.

**Describe the items of the task (DoD, definition of done) you'd like.**
- [ ] deprecation notice.

**Additional context**
https://github.com/longhorn/longhorn/pull/2737#discussion_r686103306
https://github.com/longhorn/longhorn/issues/467

**Comment by yasker** [comment]
This issue can be merged into the release note of https://github.com/longhorn/longhorn/issues/467 . Though feel free to use this issue as an reminder for the release.

**Comment by c3y1huang** [comment]
Even though the feature is still functional but with different behavior (auto-convert to label). I think the deprecation notice should be for v1.2.0 since existing `recurringJobs` will be empty after the upgrade. The complete removal should be done in v1.3.0. What do you think?

**Comment by innobead** [comment]
Let's make the deprecation note in 1.2.0.

**Comment by innobead** [comment]
The note was already made in https://v1-2-0--longhornio.netlify.app/.
