### ISSUE TITLE
[FEATURE] Support Filesystem expansion for encrypted volumes

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2868]
**Is your feature request related to a problem? Please describe.**
We currently utilize the longhorn-manager to expand the filesystem on the block device.
This should be moved into the csi driver + share-manager for rwx volumes.

**Additional context**
PV encryption is implemented in https://github.com/longhorn/longhorn/issues/1859
csi expansion is tracked at https://github.com/longhorn/longhorn/issues/2794

**Comment by innobead** [comment]
@joshimoo We need to backport this to 1.2.x. Please help create the backport issue and related PRs. Thanks.

**Comment by joshimoo** [comment]
We will also need to backport https://github.com/longhorn/longhorn/issues/2794
as well to have encryption expansion support.

@innobead Will make the necessary backports, we currently don't have a branch for v1.2.3 on the longhorn repro yet, so I waited with the chart PR to not modify the master head. Can you create the appropriate release branch on longhorn/longhorn

**Comment by innobead** [comment]
> We will also need to backport #2794 as well to have encryption expansion support.
> 
> @innobead Will make the necessary backports, we currently don't have a branch for v1.2.3 on the longhorn repro yet, so I waited with the chart PR to not modify the master head. Can you create the appropriate release branch on longhorn/longhorn

Just created :)

**Comment by innobead** [comment]
@joshimoo Please help backport to 1.2.x then we can move this to `ready for testing`. Thanks.

**Comment by khushboo-rancher** [comment]
Created https://github.com/longhorn/longhorn/issues/3240 for backport.

Validation - **Pass** on master-head `11/11/2021`

Validated the expansion with below scenarios
1. RWO encrypted volume created using Longhorn UI.
2. RWX encrypted volume created using Longhorn UI.
3. RWO and RWX encrypted volume created using storage class.
4. Restored encrypted volume expansion.

Logs: 
[csi.log](https://github.com/longhorn/longhorn/files/7523838/csi.log)
