### ISSUE TITLE
[BUG] The forwarder/proxy doesn't work for HTTPs requests

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2869]
**Describe the bug**
When a request is using schema `https`, e.g., sent by Rancher proxy, the refactored forwarder cannot handle it correctly.

**To Reproduce**
1. Deploy the Longhorn whose latest commit is `f271ef470f706e58cbd0d30948e1f1189b028d8d`.
2. Access the Longhorn system via the Proxy provided automatically generated by Rancher Cluster Explorer.
3. Try to create a volume.
4. See the UI getting stuck, and there are flooded logs `Forwarding request to xxxxxx` in the manager pods.

**Expected behavior**
The requests should succeed.

**Log**
```
[longhorn-manager-7jsmc] time="2021-08-11T12:42:28Z" level=debug msg="Forwarding request to 10.42.2.170:9500"
......
```

**Environment:**
 - Longhorn version: master - manager commit `f271ef470f706e58cbd0d30948e1f1189b028d8d`

**Additional context**
- In both versions of the forwarders, the rewriting for HTTPS requests are invalid. The **rewritten** requests **re-received by the longhorn manager pods** are like the following. Notice that the URL host becomes empty.
```
Host: 23.239.11.106
URL: https:///v1/volumes/vol?action=snapshotList, 
Header: map[Accept:[application/json] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-US,en;q=0.9,zh-TW;q=0.8,zh;q=0.7] Content-Length:[0] Cookie:[R_USERNAME=admin; CSRF=02f301cd19; R_SESS=token-2l9nv:dtvtsl74lttlv9b4cr4x9kwhwqcsvxb7ztw62stkx6vcsshxh5x7tm; R_PCS=light; R_LOCALE=en-us] Origin:[https://23.239.11.106] Referer:[https://23.239.11.106/k8s/clusters/c-72rsr/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/] Sec-Ch-Ua:[\"Chromium\";v=\"92\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"92\"] Sec-Ch-Ua-Mobile:[?0] Sec-Fetch-Dest:[empty] Sec-Fetch-Mode:[cors] Sec-Fetch-Site:[same-origin] User-Agent:[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36] X-Forwarded-For:[58.152.81.218, 10.42.0.5, 10.42.0.0] X-Forwarded-Host:[23.239.11.106] X-Forwarded-Proto:[https] X-Forwarded-Uri:[/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/v1/volumes/vol] X-Real-Ip:[10.42.0.0]]
```
- In the old forwarder, Longhorn will check if the request node ID matches that of the current manager pod first. If the node ID doesn't match, Longhorn will continue comparing the address in the URL with the current manager pod IP. Here, Hence with the node ID verification, the old forwarder can skip checking the invalid address and avoid forwarding.
- But in the new forwarder, Longhorn will blindly compare the address in the URL with the current manager pod IP. Since the URL addresses for HTTPS requests are not valid, the comparison always leads to forwarding.
- The reason of URL becoming invalid is that the forwarder always sets the request schema to `http`. It contradicts the entries `X-Forwarded-Proto` and `X-Forwarded-Host` in the Header. By removing or modifying these 2 entries, the issue gets resolved.

**Comment by shuo-wu** [comment]
Test plan:
1. Deploy the Longhorn contains the fix
2. Access Longhorn UI via NodePort, Ingress, and Rancher proxy
3. Create a volume via UI

**Comment by khushboo-rancher** [comment]
Verified with `v1.2.0-preview1`

Validation - **Pass**

Validated volume creation and actual size from Longhorn UI accessed by Rancher proxy, ingress and nodePort.
