### ISSUE TITLE
[BUG] Remove the backingImage/backingImageChecksum in Backup CR

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#2871]
**Describe the bug**

The backup_controller is responsible to perform snapshot backup according to the Backup CR spec.
After https://github.com/longhorn/longhorn-manager/pull/952 merged, the Backup CR contains the backingImage/backingImageChecksum information.

We could remove it from the CR spec and directly refer to the Volume and BackingImage CR spec/status.

**Expected behavior**

In backup_controller, when performing a snapshot backup
- get the backup's volume (vol-A) from Backup CR label
- get Volume (vol-A) CR spec.backingImage
- get BackupVolume (vol-A) CR `status.backingImageName` as well as `status.backingImageChecksum`
- do checksum validation `if bv != nil && bv.status.backingImageChecksum != "" && bi.status.checksum != "" && bv.backingImageChecksum != bi.status.checkSum, return backup creation failure`

**Environment:**
 - Longhorn version: `v1.2.0-preview1`

**Comment by yasker** [comment]
What if the backing image no longer exists in the system?

**Comment by jenting** [comment]
The integration tests passed, the backingImage/backingImageChecksum no more needed in Backup CR
- test_backup_with_backing_image :heavy_check_mark:
- test_ha_backup_deletion_recovery :heavy_check_mark:
- test_engine_offline_upgrade_with_backing_image :heavy_check_mark:
- test_engine_live_upgrade_with_backing_image :heavy_check_mark:
- test_csi_backup_with_backing_image :heavy_check_mark:

Close it.
