### ISSUE TITLE
[QUESTION] Is Longhorn compatible with Nomad orchestrator

### ISSUE THREAD

**Issue by josephlim75** [longhorn/longhorn#2873]
**Question**

Would like to know if Longhorn compatible with Nomad orchestrator since Nomad 1.1.3 does support CSI.  Does anyone from Longhorn community able to help how to setup Longhorn CSI in Hashicorp Nomad ?

**Comment by shuo-wu** [comment]
Unfortunately No. Longhorn workloads are launched as Kubernetes pods and replies on Kubernetes APIs. It cannot work correctly without Kubernetes...

**Comment by josephlim75** [comment]
Hi @shuo-wu , thanks for confirmation.
