### ISSUE TITLE
[TASK] Add Slack channel on the top right of longhorn.io website

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2875]
We can use it to make it easy for the users to connect with the community.

**Comment by jenting** [comment]
PR merged, close it.

**Comment by migs35323** [comment]
tried to reach on slack however:

You can use any account with the domain:
rafay.co
huawei.com
Don’t have an email address from one of those domains?
Contact the workspace administrator at Cloud Native Computing Foundation for an invitation.

**Comment by yasker** [comment]
FYI: This is the official CNCF Slack channel. You can get the invitation at https://slack.cncf.io/

**Comment by jonizen** [comment]
Ahh, that was not super clear :D Maybe put that somewhere? :)
