### ISSUE TITLE
Deployment pod longhorn-driver-deployer stuck in init status due to DaemonSet longhorn manager not coming in ready status

### ISSUE THREAD

**Issue by avi1512** [longhorn/longhorn#2883]
I tested kubernetes v1.21 version with longhorn storage is working fine but when I tried to tested with Kubernetes v1.22.0 is not come up. it's stuck in Deployment pod longhorn-driver-deployer due to DaemonSet longhorn manager not come up in ready status.. 
 
 **Environment: VMware**
 
 
![image](https://user-images.githubusercontent.com/78405243/129439999-17d0d699-2663-4d25-a407-d76245d25ca8.png)

**Longhorn version:**

![image](https://user-images.githubusercontent.com/78405243/129440023-c68fa428-7f36-44a0-b746-d9039ea5e8c4.png)

**Kubernetes version:**
 
 **Master**

![image](https://user-images.githubusercontent.com/78405243/129440051-7fdfd2e7-313b-4268-b159-9ccf44181972.png)

**Worker1**

![image](https://user-images.githubusercontent.com/78405243/129440070-a51e35a9-2952-4fc6-a3c3-e082a394dfff.png)

**Worker2**

![image](https://user-images.githubusercontent.com/78405243/129440082-4c1f8860-b728-4176-bc76-726fdb232f7a.png)

**Longhorn-Storage Namespace**

![image](https://user-images.githubusercontent.com/78405243/129440106-84ec8f72-c837-45cd-983e-62f3f878636b.png)

**DaemonSet Logs**

![image](https://user-images.githubusercontent.com/78405243/129440169-2f89e225-0b8e-4497-a7ce-71984732d6a8.png)

**Comment by khushboo-rancher** [comment]
Due to a few API group depreciation changes, the current Longhorn releases (including the latest v1.1.2) don’t support Kubernetes v1.22. The upcoming Longhorn v1.2.0 and v1.1.3 will support Kubernetes v1.22. If you’re planning to upgrade Kubernetes to v1.22, please wait for the upcoming v1.2.0 (later August) and v1.1.3 (mid September) releases.

**Comment by avi1512** [comment]
Thank you very much for the information. Sure we will wait for next release Longhorn v1.2.0
