### ISSUE TITLE
Cannot attach example pvc 

### ISSUE THREAD

**Issue by parisni** [longhorn/longhorn#2886]
**Describe the bug**
I try to run the tutorial on a fresh single node k3s install. 

**To Reproduce**

1. install k3s on ubuntu 18.04 (only one node)
2. install iscsi from kubectl `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.1.2/deploy/prerequisite/longhorn-iscsi-installation.yaml`
3. install longhorn from kubectl `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.1.2/deploy/longhorn.yaml`
4. create a pvc together with a pod `kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/v1.1.2/examples/pod_with_pvc.yaml`

**Expected behavior**
The pod should be running

**Log**

volume-test logs:

```
 Warning  FailedAttachVolume  117s (x10 over 6m12s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-65c838c5-0494-4a28-87ad-5d5883f28c4e" : rpc error: code = Aborted desc = volume pvc-65c838c5-0494-4a28-87ad-5d5883f28c4e in state detached is not ready for workloads                                            
```

In the UI, when click on attach the volume :

```
unable to attach volume pvc-65c838c5-0494-4a28-87ad-5d5883f28c4e to hostname: cannot attach volume pvc-65c838c5-0494-4a28-87ad-5d5883f28c4e because the engine image longhornio/longhorn-engine:v1.1.2 is not deployed on at least one of the the replicas' nodes or the node that the volume is going to attach to
```

**Environment:**
 - Longhorn version: 1.1.2

**Comment by kaxing** [comment]
Looks like the longhorn deployment is not ready, also I would log into the worker node system to check if the open-iscsi package is being installed correctly.
If you are using docker container there are still some [limitations](https://github.com/kubernetes/minikube/pull/11458), you might want to use Virtual Machines like KVM or VirtualBox instead.

**Comment by parisni** [comment]
> If you are using docker container there are still some limitations

I am using k3s with containerd.

> Looks like the longhorn deployment is not ready

The deployment looks fine:

```
23:52 $ curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.1.2/scripts/environment_check.sh | sudo bash
[sudo] password for nparis:
daemonset.apps/longhorn-environment-check created
waiting for pods to become ready (0/1)
waiting for pods to become ready (0/1)
all pods ready (1/1)

  MountPropagation is enabled!
```

Also everything is running except the `volume-test` explained above:

```
NAMESPACE↑       NAME                                       PF READY RESTARTS STATUS            
default          longhorn-iscsi-installation-6lfxg          ●  1/1          0 Running           
default          volume-test                                ●  0/1          0 ContainerCreating 
longhorn-system  csi-attacher-54c7586574-4tcwz              ●  1/1          0 Running           
longhorn-system  csi-attacher-54c7586574-lpht7              ●  1/1          0 Running           
longhorn-system  csi-attacher-54c7586574-s89jg              ●  1/1          0 Running           
longhorn-system  csi-provisioner-5ff5bd6b88-4p9ng           ●  1/1          0 Running           
longhorn-system  csi-provisioner-5ff5bd6b88-7t2m7           ●  1/1          0 Running           
longhorn-system  csi-provisioner-5ff5bd6b88-mq8fq           ●  1/1          0 Running           
longhorn-system  csi-resizer-7699cdfc4-7srnh                ●  1/1          0 Running           
longhorn-system  csi-resizer-7699cdfc4-q4764                ●  1/1          0 Running           
longhorn-system  csi-resizer-7699cdfc4-vwz5z                ●  1/1          0 Running           
longhorn-system  csi-snapshotter-8f58f46b4-4n8nx            ●  1/1          0 Running           
longhorn-system  csi-snapshotter-8f58f46b4-798r7            ●  1/1          0 Running           
longhorn-system  csi-snapshotter-8f58f46b4-kkf89            ●  1/1          0 Running           
longhorn-system  engine-image-ei-a5a44787-s5cdh             ●  1/1          0 Running           
longhorn-system  instance-manager-e-423fe308                ●  1/1          0 Running           
longhorn-system  instance-manager-r-cb20431f                ●  1/1          0 Running           
longhorn-system  longhorn-csi-plugin-8r5jg                  ●  2/2          0 Running           
longhorn-system  longhorn-driver-deployer-5479f45d86-7cwnp  ●  1/1          0 Running           
longhorn-system  longhorn-manager-fj2hf                     ●  1/1          0 Running           
longhorn-system  longhorn-ui-79f8976fbf-zptvn               ●  1/1          0 Running           
```

**Comment by kaxing** [comment]
> time="2021-08-16T11:55:16Z" level=error msg="There's no available disk for replica pvc-65c838c5-0494-4a28-87ad-5d5883f28c4e-r-cb0d2be0, size 1073741824"

The volume is not ready for the pod, because of there is no disk for Longhorn volume to create replica, you can quickly check the disk status via the [Longhorn UI](https://longhorn.io/docs/1.1.2/deploy/accessing-the-ui/).

And just to be sure can you still attaching the event logs from `kubectl describe pod/volume-test`

Once you resolve the disk problem, you will still see the volume status as degraded, since you only had 1 worker node in this setup. By default, the number of volume replica is set to 3, for testing purpose, you can lower the number or set `Replica Node Level Soft Anti-Affinity` to true under the setting, to have a healthy state volume.

**Comment by parisni** [comment]
The ui says:
```
Scheduling Failure
Replica Scheduling Failure
```

And the volume-test pod has this logs:
```
  Type     Reason              Age                    From                     Message
  ----     ------              ----                   ----                     -------
  Warning  FailedMount         22h (x29 over 47h)     kubelet                  Unable to attach or mount volumes: unmounted volumes=[volv], unattached volumes=[kube-api-access-bgv9l volv]: timed out waiting for the condition
  Warning  FailedAttachVolume  22h (x190 over 47h)    attachdetach-controller  AttachVolume.Attach failed for volume "pvc-65c838c5-0494-4a28-87ad-5d5883f28c4e" : rpc error: code = Aborted desc = volume pvc-65c838c5-0494-4a28-87ad-5d5883f28c4e in state detached is not ready for workloads
  Warning  FailedMount         2m27s (x134 over 47h)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[volv], unattached volumes=[volv kube-api-access-bgv9l]: timed out waiting for the condition
```

>  you can lower the number or set Replica Node Level Soft Anti-Affinity to true under the setting, to have a healthy state volume.

Yeah, I already did this.

**Comment by kaxing** [comment]
Hi @parisni can you 'Generate Support Bundle', there is a link on the bottom of the UI, upload here or send it over to longhorn-support-bundle@suse.com

![image](https://user-images.githubusercontent.com/602540/129846938-4647806c-df2c-42df-9a6d-75dca21c3451.png)

Thank you!

**Comment by kaxing** [comment]
Hey @parisni 

From you support bundle logs, longhorn-manager says "unable to schedule replica"
Also, the disk status **Schedulable** is false due to **DiskPressure**
```
Schedulable:
  type: Schedulable
  status: "False"
  lastprobetime: ""
  lasttransitiontime: "T10:40:52Z"
  reason: DiskPressure
  message: the disk default-disk-xxx(/var/lib/longhorn/) on
    the node gnubuntu has --- available, but requires reserved
    ---, minimal 25% to schedule more replicas
    storageavailable: ---
```

Can you check your Disk setting under Node page from Longhorn UI, see if you can enable or lower the Storage Reserved temporary increase space for volume replicas?

| step 1 | step 2 (click to enlarge) |
| :- | :- |
| ![image](https://user-images.githubusercontent.com/602540/130423753-b25dff1e-c035-4a26-9671-4a64d4c2e939.png) | ![image](https://user-images.githubusercontent.com/602540/130424997-b0a2dcff-dfee-42e9-a412-85d23eb53345.png) |

**Comment by kaxing** [comment]
Hello @parisni
I am able to use the pod_with_pvc example yaml files with latest v1.2.0 release on my local k3s cluster with 3 VMs(hyperkit).
Will close this issue for now. Please feel free to reopen it if you still bump into the same problem.
