### ISSUE TITLE
Where is my disk space gone?

### ISSUE THREAD

**Issue by RHuehne** [longhorn/longhorn#2889]
**Question**
We are wondering why Longhorn "eats" so much Disk-Space:
![image](https://user-images.githubusercontent.com/13745200/129545429-ddd7af56-10b6-429e-9a67-f896183f38af.png)
This results in a Sum of ~35G (usage data). Volume size does not affect the space used on disk, am I right?
Replica-Count is set to 1 for all  volumes. So how come, that the dashboard looks like this:
![image](https://user-images.githubusercontent.com/13745200/129545655-1f6384d7-0b02-47aa-850b-d8a400bb9b5d.png)
I would expect 70G maximum to be in use?

I cannot see any longhorn snapshots present on all the volumes (even system snapshots, also checked over lhexec). So, what claims this space??

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes version: 1.20.9
 - Node config
   - OS type and version Ubuntu 20.04
   - CPU per node: 4
   - Memory per node: 10G
   - Disk type LVM-Disk (VMWARE)
   - Network bandwidth and latency between the nodes: 10G (Host-Internal VMWARE)
 - Underlying Infrastructure (Ubuntu-VMs on VMWARE):

**Additional context**

**Comment by bmalynovytch** [comment]
@RHuehne reported used space on the dashboard also includes space used by your node's OS.

Also bear in mind that volumes hold their own filesystem, which means that once space is used, it will never be reclaimable by the node again. This means that if you run applications with lots of write operations, allocated block may be randomly placed on previously unused zones, even though space was released on the volume's FS.

**Comment by RHuehne** [comment]
ah, ok, I see - so replication is also done on block level, and therefore, once allocated, all blocks will be replicated even if the data they are holding inside the container has been deleted. Thanks!
