### ISSUE TITLE
Create multiple storage classes

### ISSUE THREAD

**Issue by tomsozolins** [longhorn/longhorn#2891]
Hello! I have searched the longhorn documentation, but did not find examples of how do you configure multiple storage classes.
I want to use default storage class for regular workloads and another storage class with less replicas for elasticsearch.

Can someone please provide an example yaml ?

Longhorn version: v1.1.2

**Comment by shuo-wu** [comment]
You can check this example: https://github.com/longhorn/longhorn-manager/blob/master/examples/storageclass.yaml

**Comment by tomsozolins** [comment]
Thank you!
