### ISSUE TITLE
[BUG] engine integration test: test_snapshot_tree_basic fails on ARM64

### ISSUE THREAD

**Issue by keithalucas** [longhorn/longhorn#2892]
**Describe the bug**
`test_snapshot_tree_basic` occasionally fails on ARM64.  The line of the test that fails is https://github.com/longhorn/longhorn-engine/blob/870f06d50ece703aed65eb4db617c013bbdf3cd0/integration/common/core.py#L303.  This seems to indicate that the purge progress is over 100%.  I think the problem is that we are running commands to remove snapshots then purge snapshots.  The commands construct gRPC calls to remove snapshots and the last remove snapshot command might not finish before the snapshot purge.  We could add a sanity check to make sure this line (https://github.com/longhorn/longhorn-engine/blob/870f06d50ece703aed65eb4db617c013bbdf3cd0/pkg/sync/rpc/server.go#L1114 doesn't set the progress to over 100 or make the function that sets the progress be able to handle rm snapshots while it is executing.

**To Reproduce**
1. Perform build on ARM64
2. See that `test_snapshot_tree_basic` fails.

**Expected behavior**
`test_snapshot_tree_basic` should pass.

**Log**

=================================== FAILURES ===================================
4031s
25292	___________________________ test_snapshot_tree_basic ___________________________
4031s
25293	
4031s
25294	grpc_controller = <rpc.controller.controller_client.ControllerClient object at 0xffffb2cbff10>
4031s
25295	grpc_replica1 = <rpc.replica.replica_client.ReplicaClient object at 0xffffb2cd2b50>
4031s
25296	grpc_replica2 = <rpc.replica.replica_client.ReplicaClient object at 0xffffb2bd5760>
4031s
25297	
4031s
25298	    def test_snapshot_tree_basic(grpc_controller,  # NOQA
4031s
25299	                                 grpc_replica1, grpc_replica2):  # NOQA
4031s
25300	        address = grpc_controller.address
4031s
25301	    
4031s
25302	        dev = get_dev(grpc_replica1, grpc_replica2, grpc_controller)
4031s
25303	    
4031s
25304	        offset = 0
4031s
25305	        length = 128
4031s
25306	    
4031s
25307	        snap, data = snapshot_tree_build(dev, address, ENGINE_NAME,
4031s
25308	                                         offset, length)
4031s
25309	    
4031s
25310	        snapshot_revert_with_frontend(address, ENGINE_NAME, snap["1b"])
4031s
25311	        cmd.snapshot_rm(address, snap["0a"])
4031s
25312	        cmd.snapshot_rm(address, snap["0b"])
4031s
25313	        cmd.snapshot_rm(address, snap["1c"])
4031s
25314	        cmd.snapshot_rm(address, snap["2a"])
4031s
25315	        cmd.snapshot_rm(address, snap["2b"])
4031s
25316	        cmd.snapshot_rm(address, snap["2c"])
4031s
25317	        cmd.snapshot_rm(address, snap["3a"])
4031s
25318	        cmd.snapshot_rm(address, snap["3b"])
4031s
25319	        cmd.snapshot_rm(address, snap["3c"])
4031s
25320	        cmd.snapshot_purge(address)
4031s
25321	>       wait_for_purge_completion(address)
4031s
25322	
4031s
25323	data/test_snapshot.py:240: 
4031s
25324	_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
4031s
25325	
4031s
25326	url = 'localhost:30001'
4031s
25327	
4031s
25328	    def wait_for_purge_completion(url):
4031s
25329	        completed = 0
4031s
25330	        purge_status = {}
4031s
25331	        for x in range(RETRY_COUNTS):
4031s
25332	            completed = 0
4031s
25333	            purge_status = cmd.snapshot_purge_status(url)
4031s
25334	            for status in purge_status.values():
4031s
25335	>               assert status['progress'] <= 100
4031s
25336	E               AssertionError
4031s
25337	
4031s
25338	common/core.py:303: AssertionError

**Environment:**
- https://drone-pr.longhorn.io/

**Additional context**
https://drone-publish.longhorn.io/longhorn/longhorn-engine/235
https://drone-pr.longhorn.io/longhorn/longhorn-engine/486

**Comment by yasker** [comment]
Raise the priority due to the failure shows up in the master now.

**Comment by innobead** [comment]
Closing because the test failed not shown up anymore.
