### ISSUE TITLE
[FEATURE] podAntiAffinity for csi-attacher/csi-provisioner/csi-resizer/csi-snapshotter

### ISSUE THREAD

**Issue by bkupidura** [longhorn/longhorn#2894]
**Is your feature request related to a problem? Please describe.**
Longhorn deployed from helm chart (chart version 1.1.2).

Currently csi-(attacher|provisioner|resizer|snapshotter) are not using podAntiAffinity, which can lead to running all PODs on single host.

Currently running 3 node k3s deployment, and most of PODs are running on single host.
```
$ kubectl get pod -n longhorn-system -o json|jq -r '.items[] | .metadata.name + " "+ .spec.nodeName'
csi-attacher-54c7586574-2j5sb k3s-delta
csi-attacher-54c7586574-6wdzr k3s-delta
csi-attacher-54c7586574-tbslm k3s-delta
csi-provisioner-5ff5bd6b88-5qlvz k3s-delta
csi-provisioner-5ff5bd6b88-fgpf4 k3s-charlie
csi-provisioner-5ff5bd6b88-qnmgs k3s-delta
csi-resizer-7699cdfc4-4k8ll k3s-charlie
csi-resizer-7699cdfc4-4mvws k3s-delta
csi-resizer-7699cdfc4-sf428 k3s-delta
csi-snapshotter-8f58f46b4-s2hp7 k3s-delta
csi-snapshotter-8f58f46b4-tg64f k3s-delta
csi-snapshotter-8f58f46b4-zczt4 k3s-charlie
[...]
```

**Describe the solution you'd like**
Even if Longhorn can handle node failure internally (and choose master), it would be nice to use `preferredDuringSchedulingIgnoredDuringExecution` podAntiAffinity rule.

This way k8s scheduler will try to spread workload. Even if this will not be possible, worst case scenario is current behavior.

**Comment by PhanLe1010** [comment]
The workaround at the moment is users can manually set pod anti-affinity for csi-attacher, csi-provisioner, csi-resizer, csi-snapshotter deployments

**Comment by derekbit** [comment]
PR: https://github.com/longhorn/longhorn-manager/pull/1117

**Comment by khushboo-rancher** [comment]
@derekbit Could you please help with the test steps?

**Comment by derekbit** [comment]
> @derekbit Could you please help with the test steps?
@khushboo-rancher I've updated the steps in Pre Ready-For-Testing Checklist.

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with latest v1.2.x-head image set (20211105).

**csi-attacher pods** now will now spreading to different worker nodes.

A small notice, in a extreme case, if constantly deleting all csi-attacher pods all at the once, there is a chance one or two pods will be allocated on the same worker node.

// @derekbit thanks for the test steps!
