### ISSUE TITLE
[BUG] Longhorn v1.2.0-preview1 not compatible with old engine image v1.1.2 on backup creation

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#2897]
**Describe the bug**

The Longhorn v1.2.0-preview1 is not compatible with the old engine image v1.1.2 on backup creation action.
This is because we add a new flag `--backup-name` in v1.2.0 which is not supported in the previous version.

**To Reproduce**
1. Deploy Longhorn v1.2.0-preview1
2. Deploy volume with engine image v1.1.2
3. Create backup, it failed

**Expected behavior**

The new longhorn manager should be compatible with the old engine image since Longhorn by default did not force upgrade the engine image.

**Environment:**
 - Longhorn version: `v1.2.0-preview1`

**Comment by jenting** [comment]
The current behavior of 1.2.0 longhorn manager + 1.1.2 longhorn engine after bug fix:
- Create Backup CR with longhorn manager generated name (backup-01)
- The longhorn engine create snapshot backup with another generated name (backup-02) and saves it to the remote backup target
- The backup_volume_controller pulls the backup-02 into cluster CR and delete the backup-01 from cluster CR (because the backup-01 state is `Completed` and backup-01 does not exist at the remote backup target)

Add doc label to upgrade note about the intermediate Backup CR state.
Add manual-test-plan label to the upgrade tests in the manual test plan.

**Comment by innobead** [comment]
> The current behavior of 1.2.0 longhorn manager + 1.1.2 longhorn engine after bug fix:
> 
> - Create Backup CR with longhorn manager generated name (backup-01)
> 
> - The longhorn engine create snapshot backup with another generated name (backup-02) and saves it to the remote backup target
> 
> - The backup_volume_controller pulls the backup-02 into cluster CR and delete the backup-01 from cluster CR (because the backup-01 state is `Completed` and backup-01 does not exist at the remote backup target)
> 
> 
> 
> Add doc label to upgrade note about the intermediate Backup CR state.
> 
> Add manual-test-plan label to the upgrade tests in the manual test plan.

Yes. We need a upgrade doc note for this in transition state until users update the engine image but there should be nothing hurt for back operations.

**Comment by kaxing** [comment]
Validation: **PASSED**

Tested on local cluster with Longhorn v1.2.0-rc2 upgrade from v1.1.2, tested with following steps:
1. Install Longhorn v1.1.2 and setup nfs backupstore
2. Create and attach a simple longhorn volume(name with vol-old-engine)
3. Upgrade Longhorn to v1.2.0-rc2 via kubectl
4. Watch `backups.longhorn.io` (command shown in logs)
5. Create backup
Observe logs as following:
```shell
$ kubectl get backups.longhorn.io -l backup-volume=vol-old-engine -n longhorn-system -w 
NAME                      SNAPSHOTNAME   SNAPSHOTSIZE   SNAPSHOTCREATEDAT   STATE   LASTSYNCEDAT
backup-ee85fcd22a814f5d
backup-ee85fcd22a814f5d                                                             <no value>
backup-ee85fcd22a814f5d                                                     InProgress   <no value>
backup-ee85fcd22a814f5d                                                     Completed    <no value>
backup-ea080bd674a942ff
backup-ea080bd674a942ff                                                                  <no value>
backup-ee85fcd22a814f5d                                                     Completed    <no value>
backup-ea080bd674a942ff   5711f1b3-2e4b-4cb8-88f8-6fbe2a8b048b   0              2021-08-30T08:58:38Z   Ready        2021-08-30T08:58:42Z
backup-ea080bd674a942ff   5711f1b3-2e4b-4cb8-88f8-6fbe2a8b048b   0              2021-08-30T08:58:38Z   Ready        2021-08-30T08:58:42Z
backup-ee85fcd22a814f5d                                                                                Completed    <no value>
^C
$ kubectl get backups.longhorn.io -l backup-volume=vol-old-engine -n longhorn-system
NAME                      SNAPSHOTNAME                           SNAPSHOTSIZE   SNAPSHOTCREATEDAT      STATE   LASTSYNCEDAT
backup-ea080bd674a942ff   5711f1b3-2e4b-4cb8-88f8-6fbe2a8b048b   0              2021-08-30T08:58:38Z   Ready   2021-08-30T08:58:42Z
```

Reference test case: https://longhorn.github.io/longhorn-tests/manual/release-specific/v1.2.0/backup-creation-with-old-engine-image/
