### ISSUE TITLE
[BUG] Longhorn CSI does not validate existing backing images with the fields in StorageClass during volume creation

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2899]
**Describe the bug**
Longhorn won't validate if the backing image parameters in StorageClass matches the existing backing image during CSI volume creation

**To Reproduce**
1. Create a backing image via UI
2. Create a StorageClass with the same backing image name but different data source type/parameters
3. Create a PVC & a longhorn volume via CSI
4. The volume is launched with the backing image created in step1

**Expected behavior**
The volume creation should fail. And there should be error logs in longhorn-csi-plugin pods

**Environment:**
 - Longhorn version: v1.2.0-preview1

**Comment by kaxing** [comment]
Latest usage is updated in documentation for v1.2.0: https://github.com/shuo-wu/website/blob/3ed503b202a94774da828b4a4b81bcfb31aeced0/content/docs/1.2.0/advanced-resources/backing-image.md
