### ISSUE TITLE
[FEATURE] Replica writing should work with low CPU limit

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2904]
**Describe the bug**
3 replica work with at least 60m-75m CPU

**To Reproduce**
1. Use image `shuowu/longhorn-manager:resource-test-v2` to deploy Longhorn, which can set CPU limits for engine manager pods or replica manager pods.
2. Attach and mount volume.
3. Run below command to write in the volume.
```
while true; do dd if=/dev/urandom of=/mnt/data/t1 bs=512 count=10000000 && rm /mnt/data/t1; done &
while true; do dd if=/dev/urandom of=/mnt/data/t2 bs=1M count=10000 && rm /mnt/data/t2; done &
```
4. Check manager log. And monitor CPU usage via `kubectl -n longhorn-system top pods`

### Test results:
```
               20m        25m        30m         40m         60m         75m
1 replica       x          ✓                                                
2 replicas                             x           ✓                        
3 replicas                                         x           x           ✓ 
```

**Expected behavior**
Replica should work with less CPU

**Environment:**
 - Longhorn version: Longhorn-manager - `08/19/2021`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE, K8s v1.21.4
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 4
   - Memory per node: 8
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: Upto 10 Gi
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): DO
 - Number of Longhorn volumes in the cluster: 1

**Additional context**
https://github.com/longhorn/longhorn/issues/1691

**Comment by innobead** [comment]
This is an outdated issue. Let's create another one if needed.
