### ISSUE TITLE
[BUG] DR volume failed to be mounted after activation when the original volume is encrypted.  

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#2905]
**Describe the bug**
same as title.

**To Reproduce**
1. Create an encrypted volume, 
2. Create PV/PVC and set Secret Namespace and Secret Name values as specified in [secret-crypto-global.yaml](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml)
3. Attach it to a workload, and write some data.
4. Create a backup, wait for backup to complete.
5. Create a DR volume from the created backup
6. Write some more data and create another backup.
7. Wait for backup to complete and  restore operation to complete on the DR volume.
8. Activate the DR volume.
9. Create PV/PVC for the DR volume, and set Secret Namespace and Secret Name values as specified in [secret-crypto-global.yaml](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml)
10. Deplpy a workload that consume the DR PVC, and check volume data.

**Expected behavior**
Activated DR volume should be consumed by the workload, and data should be accessible.

**Log**
```
Warning FailedMount 1s (x4 over 5s) kubelet MountVolume.MountDevice failed for volume "new-volume-01-dr-02" : rpc error: code = Internal desc = failed to mount the volume as "ext4", it already contains crypto_LUKS. Mount error: mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/longhorn/new-volume-01-dr-02 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/new-volume-01-dr-02/globalmount
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/new-volume-01-dr-02/globalmount: wrong fs type, bad option, bad superblock on /dev/longhorn/new-volume-01-dr-02, missing codepage or helper program, or other error.


```
You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 4
   - Memory per node: 8 GB
   - Disk type(e.g. SSD/NVMe): 100
   - Network bandwidth between the nodes: 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Additional context**
Ref: https://github.com/longhorn/longhorn/issues/1859

**Comment by innobead** [comment]
@joshimoo is this also related to the UI part?

cc @smallteeths

**Comment by innobead** [comment]
@meldafrawi is this issue still valid? this should be related to https://github.com/longhorn/longhorn/issues/2906#issuecomment-902556765.

**Comment by joshimoo** [comment]
@meldafrawi now that the UI part is available for DR creation I am assuming this should work correctly now, as long as the DR volume is marked as encrypted.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI version: 90e7236
