### ISSUE TITLE
[BUG] Failed to mount restored backup when original volume is encrypted, and PV filesystem is xfs

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#2906]
**Describe the bug**

**To Reproduce**
. Create an encrypted volume, 
2. Create PV/PVC and set Secret Namespace and Secret Name values as specified in [secret-crypto-global.yaml](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml), and set `Filesystem: xfs`
3. Attach it to a workload, and write some data.
4. Create a backup, wait for backup to complete.
5. Create a DR volume from the created backup
6. Write some more data and create another backup.
7. Wait for backup to complete and  restore operation to complete on the DR volume.
8. Activate the DR volume.
9. Create PV/PVC for the DR volume, and set Secret Namespace and Secret Name values as specified in [secret-crypto-global.yaml](https://github.com/longhorn/longhorn-manager/blob/master/examples/crypto/secret-crypto-global.yaml)
10. Deplpy a workload that consume the DR PVC, and check volume data.

**Expected behavior**

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 4
   - Memory per node: 8 GB
   - Disk type(e.g. SSD/NVMe): 100
   - Network bandwidth between the nodes: 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Additional context**
Ref: https://github.com/longhorn/longhorn/issues/1859

**Comment by joshimoo** [comment]
This is because the DR volume creation is missing the `encrypted` checkbox on the UI.
https://github.com/longhorn/longhorn/issues/2841#issuecomment-901140283
@smallteeths

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn Version: master-head
Longhorn UI Version: `90e7236`
