### ISSUE TITLE
[FEATURE] Volume cloning enhancement

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2907]
**Address some limitations of the current volume cloning feature:**
- [ ] Support volume cloning using UI. Currently, users can only clone a volume using CSI https://github.com/longhorn/longhorn/issues/1815 
- [ ] ~~Rebuild all replicas of volume before marking the clone as completed. Currently, we only build 1 replica for the new volume and we start rebuilding other replicas after the new volume is attached to the workload pod~~
- [ ] Implement the retry logic for volume cloning. Currently, if the clone failed, Longhorn doesn't auto-retry. The user currently has to delete the new PVC and reapply the PVC to restart the clone
- [ ] Problems mounting XFS volume clones / restored snapshots: https://github.com/container-storage-interface/spec/issues/482

**Additional context:**
Related to https://github.com/longhorn/longhorn/issues/1815

**Comment by PhanLe1010** [comment]
Also need to consider the problem that each cloning creates a new snapshot in the source volume. This is problematic since we may flush the source volume with many snapshot

**Comment by PhanLe1010** [comment]
Another conner case when cloning a volume:
1. First, we create a new snapshot inside the source volume [link](https://github.com/longhorn/longhorn-manager/blob/5f5fdc12adf9cf0467ed76fdb23676c2ca15f4f5/controller/volume_controller.go#L2457-L2464). 
2. Then, we update the volume CR as clone initiated


If we fail at the 2nd step, we retry the whole process and create a different snapshot. This is not ok. TODO: need to remember the snapshot and skip snapshot creating when retry the sync loop

**Comment by netwarex** [comment]
Is there any workaround for the xfs uuid issue mentioned here for Longhorn?

Either passing mount options, or re-generate uuid on clone automatically would be okay.

**Comment by lucatr** [comment]
Any plans on implementing a fix for the xfs duplicate uuid mount issue? Currently trying to use the [Velero Snapshot Datamovement](https://velero.io/docs/v1.12/csi-snapshot-data-movement/) feature, which creates a new volume from a snapshot and attempts to mount it to a data-mover pod in order to copy data to an object storage. Mounting currently fails due to this issue.

Or are there any other workarounds than setting `mountOptions` with nouuid on the `StorageClass`?

**Comment by PhanLe1010** [comment]
Update:
- `Support volume cloning using UI` is handled at https://github.com/longhorn/longhorn/issues/8741
- We will not do this `Rebuild all replicas of volume before marking the clone as completed. Currently, we only build 1 replica for the new volume and we start rebuilding other replicas after the new volume is attached to the workload pod` as issued in US sync meeting, there are downside of forcefully the workload to wait for the volume to rebuild all replicas. It might take to long and sometime it might not be able to fully rebuild all replica then workload would have to wait forever
- `Implement the retry logic for volume cloning. Currently, if the clone failed, Longhorn doesn't auto-retry. The user currently has to delete the new PVC and reapply the PVC to restart the clone`, PR is created https://github.com/longhorn/longhorn-manager/pull/2895
- `Problems mounting XFS volume clones / restored snapshot` is handled at https://github.com/longhorn/longhorn/issues/8796

**Comment by ejweber** [comment]
> Another conner case when cloning a volume:
> 
> 1. First, we create a new snapshot inside the source volume [link](https://github.com/longhorn/longhorn-manager/blob/5f5fdc12adf9cf0467ed76fdb23676c2ca15f4f5/controller/volume_controller.go#L2457-L2464).
> 2. Then, we update the volume CR as clone initiated
> 
> If we fail at the 2nd step, we retry the whole process and create a different snapshot. This is not ok. TODO: need to remember the snapshot and skip snapshot creating when retry the sync loop

@PhanLe1010, do we still need to deal with this one? Do you think it was unintentionally resolved by https://github.com/longhorn/longhorn-manager/pull/1942?

**Comment by PhanLe1010** [comment]
> @PhanLe1010, do we still need to deal with this one? Do you think it was unintentionally resolved by [longhorn/longhorn-manager#1942](https://github.com/longhorn/longhorn-manager/pull/1942)?

Yeah, the commit https://github.com/longhorn/longhorn-manager/pull/1942 resolved the duplicated snapshot concern. 

And this concern is resolved by having a recurring snapshot delete job:

> Also need to consider the problem that each cloning creates a new snapshot in the source volume. This is problematic since we may flush the source volume with many snapshot

**Comment by PhanLe1010** [comment]
# Test plan:

Case 1: Clone retry

1. Create PVC a volume of 5G with 1 replica
1. Attach the volume. Write 4G data into it. Calculate the checksum of the data
1. Deploy a pod with a PVC with datasource pointing to the source PVC
1. While cloning is happening, kill the replica process of the source PVC
1. Verify that Longhorn should fail the clone. Then retry. Then the clone should eventually succeeded 

Case 2: XFS duplicated UUD

This should be handled at https://github.com/longhorn/longhorn/issues/8796


Case 3: Clone using Longhorn UI

This should be handled at https://github.com/longhorn/longhorn/issues/8741

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 369be1a) following [the case 1 of the test plan](https://github.com/longhorn/longhorn/issues/2907#issuecomment-2204026385):

1. Create storage class with `replica count = 1`:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test-sc
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
```
2. Create source pvc:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: test-sc
  resources:
    requests:
      storage: 5Gi
```
3. Create a pod using the volume:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: sleep
      image: busybox
      imagePullPolicy: IfNotPresent
      args: ["/bin/sh", "-c", "while true;do date;sleep 5; done"]
      volumeMounts:
        - name: pod-data
          mountPath: /data
  volumes:
    - name: pod-data
      persistentVolumeClaim:
        claimName: test-pvc
``` 
4. Write 4GB data to the volume and calculate the checksum.
5. Clone the source pvc:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloned-pvc
spec:
  storageClassName: test-sc
  dataSource:
    name: test-pvc
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```
6. While volume cloning is in progress, delete the instance manager on the same node of the source pvc replica.
7. Check longhorn manager logs and find the volume cloning failed and restarted again.
```
$ kubectl logs longhorn-manager-fv589 -c longhorn-manager -n longhorn-system | grep clone
time="2024-07-03T06:06:12Z" level=info msg="Starting Longhorn volume clone controller" func="controller.(*VolumeCloneController).Run" file="volume_clone_controller.go:126" controller=longhorn-volume-clone node=ip-10-0-1-79
I0703 06:06:12.328065       1 shared_informer.go:313] Waiting for caches to sync for longhorn-volume-clone
I0703 06:06:12.328266       1 shared_informer.go:320] Caches are synced for longhorn-volume-clone
time="2024-07-03T06:20:18Z" level=info msg="Volume pvc-63093577-bb32-4b58-978b-f2af47fe6e19 is selected to attach to node ip-10-0-1-79, ticket +&{volume-clone-controller-pvc-63093577-bb32-4b58-978b-f2af47fe6e19 volume-clone-controller ip-10-0-1-79 map[disableFrontend:true] 0}" func="controller.(*VolumeAttachmentController).handleVolumeAttachment" file="volume_attachment_controller.go:662" controller=longhorn-volume-attachment longhornVolumeAttachment=pvc-63093577-bb32-4b58-978b-f2af47fe6e19 node=ip-10-0-1-79
time="2024-07-03T06:20:30Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"pvc-63093577-bb32-4b58-978b-f2af47fe6e19\", UID:\"4152f175-b4ec-45b8-9ccc-c68ef1be2e4a\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"15292\", FieldPath:\"\"}): type: 'Warning' reason: 'VolumeCloneFailed' failed to clone snapshot 55df66ca-e0db-5c8f-9081-d1c1d4b81dca from source volume pvc-cd74ce7f-ade5-42a4-b47d-1c6031af1306: failed to export snapshot 55df66ca-e0db-5c8f-9081-d1c1d4b81dca from replica tcp://10.42.2.9:10000 to 10.42.1.10:10004: failed to export snapshot 55df66ca-e0db-5c8f-9081-d1c1d4b81dca to 10.42.1.10:10004: rpc error: code = Unavailable desc = error reading from server: EOF" func="record.(*eventBroadcasterImpl).StartLogging.func1" file="event.go:377"
time="2024-07-03T06:21:10Z" level=info msg="Volume pvc-63093577-bb32-4b58-978b-f2af47fe6e19 is selected to attach to node ip-10-0-1-79, ticket +&{volume-clone-controller-pvc-63093577-bb32-4b58-978b-f2af47fe6e19 volume-clone-controller ip-10-0-1-79 map[disableFrontend:true] 0}" func="controller.(*VolumeAttachmentController).handleVolumeAttachment" file="volume_attachment_controller.go:662" controller=longhorn-volume-attachment longhornVolumeAttachment=pvc-63093577-bb32-4b58-978b-f2af47fe6e19 node=ip-10-0-1-79
```
8. After the volume cloning is complete, check the cloned volume data.

**Comment by innobead** [comment]
@PhanLe1010 do we have the corresponding doc update?

cc @derekbit
