### ISSUE TITLE
[QUESTION] Speed difference between Longhorn and Local Path Provisioner

### ISSUE THREAD

**Issue by rgulden** [longhorn/longhorn#2911]
**Question**
Hey Longhorn community, quick question-- 
Ive noticed a speed difference between Longhorn and Local Path Provisioner and i am just looking for an answer to this. I noticed it specifically when I deployed a Wordpress site using Local-Path pvc and one using Longhorn. The local path's pages loaded way quicker.

Is this because longhorn relies on iscsiadm to provide persistent volumes to k8s? Is this just natively slower than host mounts? 

Thanks!!

**Environment:**
 - Longhorn version: v1.1.2
 - Kubernetes version: v1.18.20
 - Node config
   - OS type and version: Linux Ubuntu 20.04
   - CPU per node: 24
   - Memory per node: 80gb
   - Disk type: HDD (RAID 0 15K SAS)
   - Network bandwidth and latency between the nodes: 50-100mbps between nodes
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal (Dell R710)

**Additional context**

**Comment by c3y1huang** [comment]
@rgulden check out this [comment](https://github.com/longhorn/longhorn/issues/1104#issuecomment-598826969).
