### ISSUE TITLE
[BUG] Backup should immediately stop showing the backups on setting backup target blank

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2913]
**Describe the bug**
Backup should immediately stop showing the backups on setting backup target blank.

**To Reproduce**
1. Set backup target which has 50 plus volume backups
2. Wait for the backups to get listed.
3. Once all the backups are listed, set the backup target blank.
4. Check the backup page, still the backup page lists the backups for sometime.

**Expected behavior**
Based on the condition that the backup target is empty, don't show the backups

**Environment:**
 - Longhorn version: v1.2.0-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl

**Comment by jenting** [comment]
I think the problem is the same as https://github.com/longhorn/longhorn/issues/2915#issuecomment-905111637
@khushboo-rancher could you please double verify this one as well? Thank you.

**Comment by khushboo-rancher** [comment]
Validation - **Pass**

Verified with Longhorm-master `08/30/2021`

The behavior is as soon as all the `backupvolumes` are deleted in the cluster on removing the backup target, the backup page stops showing the backups. 
I'm okay with the behavior for this release.
cc: @innobead
