### ISSUE TITLE
[BUG] volume stuck detaching

### ISSUE THREAD

**Issue by timmy59100** [longhorn/longhorn#2922]
**Describe the bug**
A volume is stuck in detaching mode.

**To Reproduce**
?

**Expected behavior**
Volume should detach.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.
```
[longhorn-instance-manager] time="2021-08-24T11:51:02Z" level=debug msg="Process Manager: wait for process pvc-d1840f34-c890-4a5d-9ce9-354b4a3bd596-e-05efba0b to shutdown before unregistering process"
[longhorn-instance-manager] time="2021-08-24T11:51:02Z" level=debug msg="Process Manager: wait for process pvc-d1840f34-c890-4a5d-9ce9-354b4a3bd596-e-05efba0b to shutdown before unregistering process"
[longhorn-instance-manager] time="2021-08-24T11:51:02Z" level=debug msg="Process Manager: prepare to delete process pvc-d1840f34-c890-4a5d-9ce9-354b4a3bd596-e-05efba0b"
[longhorn-instance-manager] time="2021-08-24T11:51:02Z" level=debug msg="Process Manager: deleted process pvc-d1840f34-c890-4a5d-9ce9-354b4a3bd596-e-05efba0b"
[longhorn-instance-manager] time="2021-08-24T11:51:02Z" level=debug msg="Process Manager: wait for process pvc-d1840f34-c890-4a5d-9ce9-354b4a3bd596-e-05efba0b to shutdown before unregistering process""
```

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.
Sent per email.

**Environment:**
 - Longhorn version: 1.1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Rancher RKE
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 5
 - Node config
   - OS type and version: Ubuntu 20.4
   - CPU per node: 8
   - Memory per node: 32GB
   - Disk type(e.g. SSD/NVMe): 
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Xen
 - Number of Longhorn volumes in the cluster: 70

**Additional context**

**Comment by shuo-wu** [comment]
The new address longhorn-support-bundle@suse.com is not an authorized account hence I cannot access the secure message you sent.

**Comment by c3y1huang** [comment]
@timmy59100 we are unable to access the secure message. Are you able to send it as a normal attachment?

**Comment by timmy59100** [comment]
I tried but it was to big for the mail server.

**Comment by timmy59100** [comment]
closing for now, till it happens again.
