### ISSUE TITLE
[BUG] Longhorn manager find_kubelet_cmdline causing 100 % CPU Usage

### ISSUE THREAD

**Issue by TrAnn3l** [longhorn/longhorn#2923]
**Describe the bug**
I currently have high CPU usage on one node of my cluster. The CPU usage seems to be caused by the call to the find_kubelet_cmdline function in [longhorn-manager](https://github.com/longhorn/longhorn-manager/blob/132ff0c31ecf08c1d25056801ebd9d2472ae25e5/app/get_proc_arg.go#L33).
The issue arised after i upgraded from K3S 21.1.3 to 21.1.4

**To Reproduce**
Don't really know what causes the issue.
A reboot didn't solved it.
![Screenshot](https://user-images.githubusercontent.com/10076675/130679727-bb628ea6-1e3e-4d80-88b4-299f8fa3519f.jpg)

**Expected behavior**
No high cpu usage.

**Log**
Didn't find anything useful in the longhorn-manager log.

[longhorn-support-bundle_4e91f477-6e47-4da1-9d1b-0b295235e9ca_2021-08-24T19-39-28Z.zip](https://github.com/longhorn/longhorn/files/7041713/longhorn-support-bundle_4e91f477-6e47-4da1-9d1b-0b295235e9ca_2021-08-24T19-39-28Z.zip)

**Environment:**
 - Longhorn version: 1.1.2

 - Installation method: Helm
 - Kubernetes distro: K3S 1.21.4
   - Number of management node in the cluster: 2
   - Number of worker node in the cluster: 0
 - Node config
   - OS: Ubuntu Server 21.04
   - CPU per node: 4
   - Memory per node: 4GB
   - Disk type: USB (64GB OS & 256GB Longhorn)
   - Network bandwidth between the nodes: 1GBit
 - Underlying Infrastructure: Baremetal Raspberry Pi 4
 - Number of Longhorn volumes in the cluster: 8

**Additional Context:**

lsof of the running process:
```
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
bash    69511 root  cwd    DIR  0,289     4096 2102851 /
bash    69511 root  rtd    DIR  0,289     4096 2102851 /
bash    69511 root  txt    REG  0,289  1046904 2636050 /bin/bash
bash    69511 root  mem    REG  0,289          2637342 /lib/aarch64-linux-gnu/libnss_files-2.27.so (stat: No such file or directory)
bash    69511 root  mem    REG  0,289          2637336 /lib/aarch64-linux-gnu/libnsl-2.27.so (stat: No such file or directory)
bash    69511 root  mem    REG  0,289          2637346 /lib/aarch64-linux-gnu/libnss_nis-2.27.so (stat: No such file or directory)
bash    69511 root  mem    REG  0,289          2637338 /lib/aarch64-linux-gnu/libnss_compat-2.27.so (stat: No such file or directory)
bash    69511 root  mem    REG  0,289          2637302 /lib/aarch64-linux-gnu/libc-2.27.so (stat: No such file or directory)
bash    69511 root  mem    REG  0,289          2637312 /lib/aarch64-linux-gnu/libdl-2.27.so (stat: No such file or directory)
bash    69511 root  mem    REG  0,289          2637380 /lib/aarch64-linux-gnu/libtinfo.so.5.9 (stat: No such file or directory)
bash    69511 root  mem    REG  0,289          2637284 /lib/aarch64-linux-gnu/ld-2.27.so (stat: No such file or directory)
bash    69511 root    0u   CHR    1,3      0t0     313 /dev/null
bash    69511 root    1w  FIFO   0,12      0t0  249564 pipe
bash    69511 root    2w  FIFO   0,12      0t0  248284 pipe
bash    69511 root    3r  FIFO   0,12      0t0  251999 pipe
bash    69511 root    4r  FIFO   0,12      0t0  251998 pipe
bash    69511 root    5w  FIFO   0,12      0t0  251999 pipe
```
strace doesn't return anything.

**Comment by TrAnn3l** [comment]
After deleting the pod, the pod got stuck in terminating. After rebooting the node, the problem seems to be resolved.

**Comment by c3y1huang** [comment]
I will close this for now, please feel free to re-open if you are able to reproduce or encounter the issue again.
