### ISSUE TITLE
[BUG] NFS driver: creates multiple 1st volume backup and immediately list backup volume names sometimes fails

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#2926]
**Describe the bug**

Create multiple 1st backups for volumes and immediately lists backup volume names, sometimes it fails.

When implementing the https://github.com/longhorn/longhorn-manager/pull/985.
The backup_controller is responsible perform the snapshot backup. After the backup is completed, it triggers the backup_target_controller to immediately pull the remote backup target of the new backup volume.
Sometimes, lists the backup volume names https://github.com/longhorn/longhorn-manager/blob/v1.2.0-rc1/engineapi/backups.go#L113 fails with reason can't find the backup volume config in messages field https://github.com/longhorn/longhorn-manager/blob/5aea6ff/engineapi/backups.go#L129-L130.

We did watch the backup volume config is there when the list backup volume names API calls.
Also, for the 1st backup, the backup volume config is generated and then the backup config is generated.

**NOTE THAT: it'll impact the time to display the newly created BackupVolume in the Backup page because the backup_target_controller can't get the remote backup volume names at the moment.**

**To Reproduce**
1. Create 3 volumes
2. Create a backup of 3 volumes simultaneously
3. After the 1st volume backup creation is completed, list backup volume names sometimes fail
(I think the problem is that another write operation is performing so listing operation fail)

**Expected behavior**

List backup volume names should always work

**Environment:**
 - Longhorn version: `v1.2.0-rc1`

**Comment by kaxing** [comment]
Validation: **PASSED**

Tested with latest image set, both master and v1.2.x lognhorn-manager branch points to `master-head`,
```
        - --engine-image
        - longhornio/longhorn-engine:master-head
```
contains longhorn/longhorn-engine@77e2743 ( included longhorn/backupstore@43c9d3298665680dd2b62bae9f806bd42cbb4cba )

The volume name will now be shown even when the status is in-progress:
| v1.2.0-rc1 | latest branch with fix |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/602540/133067297-5d841583-8e11-4601-bbde-26bf3d514ebf.png) | ![image](https://user-images.githubusercontent.com/602540/133066677-1fafd35a-0439-410b-929b-bf4283ffac19.png) |
