### ISSUE TITLE
[QUESTION] why consul(Stateful Set) can't automatic recovery when longhorn became readonly

### ISSUE THREAD

**Issue by yudoutingle** [longhorn/longhorn#2931]
**Question**
I have an issue which I am facing since I  deployed consul (Stateful Set) on longhorn,   I am not sure if it is associate with longhorn.  
The volume in longhorn will be readonly sometimes,  and then consul became unavailable because the pod cant write data into volume. 
but I found some strange phenomena：the longhorn can remount the volume automatically , but the consul pod cant  automatic recovery, it always logs "write /consul/data/raft/raft.db: readonly file system", which really confused me. I have to delete consul pods  every time to recovery consul.
So, i want to know that,  is there any other way to solve this problem? 
Thanks!

**Environment:**
 - Longhorn version:  v1.1.1
 - Kubernetes version:  v1.18.9-6+3d5bea383c722a
 - Node config
   - OS type and version
   - CPU per node: 8c
   - Memory per node: 32g
   - Disk type
   - Network bandwidth and latency between the nodes: 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**

**Comment by jenting** [comment]
Could you check the Consul Pod's `Age` time?
In order to see if the Longhorn helps to restart the Consul Pods once the Longhorn detects the volume is detached unexpectedly.
