### ISSUE TITLE
[FEATURE] Introduce SUSE BCI based component images

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#2939]
**Is your feature request related to a problem? Please describe.**
For now, the component images are based on any OS distro image, so need to chase resolving vulnerability issues along the time n potential security issues exposure.

**Describe the solution you'd like**
Evaluate and see if it's possible to update images based on the (distroless image)[https://github.com/GoogleContainerTools/distroless] to only include application artifacts and runtime dependencies.

**Describe alternatives you've considered**
SLES BCI

**Additional context**
N/A

cc @meldafrawi @joshimoo

**Comment by yasker** [comment]
@innobead An alternative can be the SLE BCI, as it's supported by SUSE.

**Comment by innobead** [comment]
> @innobead An alternative can be the SLE BCI, as it's supported by SUSE.

Can be part of evaluation.

**Comment by innobead** [comment]
Done.
