### ISSUE TITLE
[FEATURE] Prometheus metrics for backups

### ISSUE THREAD

**Issue by andlinger** [longhorn/longhorn#2940]
The [feature request](https://github.com/longhorn/longhorn/issues/1180#issuecomment-693003131) for Prometheus Metrics support already mentions metrics for backups. It would also be great if there were metrics for the size of the backups too. So something like longhorn_backup_actual_size.

**Comment by chickeaterbanana** [comment]
the backups are based on snapshots if I understand the documentation correctly. So it would be cool to have both snapshot and backup metrics. The snapshots are incremental so here the size is also a matter. Some use cases:

If the snapshot size(incremental) is for x-time 0 bytes, than you could say this volume isn't used. For some systems like databases and so on, which are in use, this could signal a bug or misbehavior in the software.

If we know the successful backup timestamp plus the recurring time window we could calculate n-times of recurring time window are allowed to fail until alert.

**Comment by innobead** [comment]
@jenting Please help describe the test cases here for QA reference. Thank you!
