### ISSUE TITLE
[BUG] Error message not getting cleaned up on switching the backupstore

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2944]
**Describe the bug**
The scenario where the backup target initially set to invalid but later set to a valid target, the error doesn't go off from frontend. 

**To Reproduce**
1. Deploy Longhorn on a kubernetes cluster.
2. Set an invalid NFS backup target.
3. Go to backup page, it shows the error regarding NFS backupstore.
4. Change the backup target to valid NFS server.
5. Go to backup page, it still shows the previous error.

**Note:** After doing multiple refresh also, I was seeing the problem.

**Expected behavior**
The error should not appear for valid backup target.

**Environment:**
 - Longhorn version: v1.2.0-rc2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

**Comment by jenting** [comment]
Do you have lots of existing backups on the NFS server when you switching the backupstore?

**Comment by jenting** [comment]
Another problem causes by this would be the backup_target_controller is still working on syncing the BackupVolumes from the remote backup target to in-cluster CRs if there're lots of backup volumes in the remote backup target. Therefore, the backup_target_controller hasn't updating the `status.available` from `false` to `true`.

**Comment by khushboo-rancher** [comment]
Another scenario where the error message shows up is the first time the backup target and secret are set. The error message `Could not access the S3 without secret` appears but the backups are shown on the backup page.

**Comment by jenting** [comment]
Summary, two cases I met for this issue:
1. There's a lot of backup volume in the remote backup target, the backup_target_controller updates the available from false to true once all the backup volume names are pulled and the corresponding BackupVolume CRs be created. So, the error message is cleaned up after the step is finished. I've to think if there is a better way to enhance the backup_target_controller.
2. The backend has to change the backup target available from false to true. But since the frontend keeps the old error message for 3 seconds, even the user re-clicks the Backup page. @smallteeths has a PR to address this issue already.

**Comment by innobead** [comment]
> Summary, two cases I met for this issue:
> 
> 1. There's a lot of backup volume in the remote backup target, the backup_target_controller updates the available from false to true once all the backup volume names are pulled and the corresponding BackupVolume CRs be created. So, the error message is cleaned up after the step is finished. I've to think if there is a better way to enhance the backup_target_controller.
> 2. The backend has to change the backup target available from false to true. But since the frontend keeps the old error message for 3 seconds, even the user re-clicks the Backup page. @smallteeths has a PR to address this issue already. [fix(backup) Clear the error message when backup target is available longhorn-ui#434](https://github.com/longhorn/longhorn-ui/pull/434) (this was backported to 1.2.1)

Because we only have a partial fix (UI) for this issue, let's move to 1.2.2 to finish the complete fix.

**Comment by jenting** [comment]
Now, I'm trying to moving the backup-related setting from Setting CR to BackupTarget CR.

Because if the user configures more than one backup-related setting change at once, the UI sends multiple events to the setting_controller within a short time. This would cause the intermediate error message shown when handling the 1st event comes into the setting_controller.

**Comment by mantissahz** [comment]
@khushboo-rancher, @longhorn/qa please check if I did something wrong.

I did some testings on master-head([f2c474e](https://github.com/longhorn/longhorn/commit/f2c474e636d6d3e41fd22e436541d2f7409f6e67)), v1.4.x([1e7eb3e](https://github.com/longhorn/longhorn/commit/1e7eb3e93737ca33d16ed3198230dd5906c0fe79)) and v1.3.x([3dc9d49](https://github.com/longhorn/longhorn/commit/3dc9d49fb8e67a152ebc023332a8124314c40ee2))

The error message would be cleaned up on switching the backupstore with 50 backups in valid remote backup-target, here are steps:

1. Install Longhorn and all pods are ready and stable
2. Set an invalid backup target
3. Click `Backup` page on UI several times and you can see the several errors according to clicks
4. Switch to a valid backup target with 50 backups
5. Click `Backup` page again and error messages are cleaned up

**Comment by khushboo-rancher** [comment]
I checked on v1.5.1, looks like this is fixed in terms of S3 backup but now for invalid NFS, there is no error message on backup page. Is this a design change and expected behavior?

**Comment by mantissahz** [comment]
I could see that it will try to mount the NFS server until mounting timeouts or API client timeouts.
I am not sure is it related to this PR https://github.com/longhorn/backupstore/pull/112
@derekbit do you know that?

**Comment by derekbit** [comment]
@mantissahz 
What's the error message?

**Comment by mantissahz** [comment]
@derekbit here it is, so it might wait 1 minute at least to know if the mount point is invalid.
cc @khushboo-rancher 

```txt
time="2023-07-20T01:34:26Z" level=error msg="Failed to list backup volumes from backup target" controller=longhorn-backup-target cred= error="error listing backup volume names: timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn [backup ls --volume-only nfs://192.168.121.200:/opt/nfs-server/], output , stderr, time=\"2023-07-20T01:33:26Z\" level=info msg=\"Attempting mount for nfs path 192.168.121.200:/opt/nfs-server/ with nfsvers 4.2\" pkg=nfs\ntime=\"2023-07-20T01:33:26Z\" level=info msg=\"Mounting NFS share nfs://192.168.121.200:/opt/nfs-server/ on mount point /var/lib/longhorn-backupstore-mounts/192_168_121_200/opt/nfs-server with options [nfsvers=4.2 actimeo=1 soft timeo=300 retry=2]\" pkg=nfs\n, error <nil>" interval=5m0s node=rancher70-worker2 url="nfs://192.168.121.200:/opt/nfs-server/"
time="2023-07-20T01:35:38Z" level=error msg="Failed to list backup volumes from backup target" controller=longhorn-backup-target cred= error="error listing backup volume names: timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn [backup ls --volume-only nfs://192.168.121.200:/opt/nfs-server/], output , stderr, time=\"2023-07-20T01:34:38Z\" level=warning msg=\"Trying reading mount point /var/lib/longhorn-backupstore-mounts/192_168_121_200/opt/nfs-server to make sure it is healthy\" pkg=nfs\ntime=\"2023-07-20T01:34:38Z\" level=info msg=\"Attempting mount for nfs path 192.168.121.200:/opt/nfs-server/ with nfsvers 4.2\" pkg=nfs\ntime=\"2023-07-20T01:34:38Z\" level=info msg=\"Mounting NFS share nfs://192.168.121.200:/opt/nfs-server/ on mount point /var/lib/longhorn-backupstore-mounts/192_168_121_200/opt/nfs-server with options [nfsvers=4.2 actimeo=1 soft timeo=300 retry=2]\" pkg=nfs\n, error <nil>" interval=5m0s node=rancher70-worker2 url="nfs://192.168.121.200:/opt/nfs-server/"
time="2023-07-20T01:36:46Z" level=error msg="Failed to list backup volumes from backup target" controller=longhorn-backup-target cred= error="error listing backup volume names: timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn [backup ls --volume-only nfs://192.168.121.200:/opt/nfs-server/], output , stderr, time=\"2023-07-20T01:35:46Z\" level=warning msg=\"Trying reading mount point /var/lib/longhorn-backupstore-mounts/192_168_121_200/opt/nfs-server to make sure it is healthy\" pkg=nfs\ntime=\"2023-07-20T01:35:46Z\" level=info msg=\"Attempting mount for nfs path 192.168.121.200:/opt/nfs-server/ with nfsvers 4.2\" pkg=nfs\ntime=\"2023-07-20T01:35:46Z\" level=info msg=\"Mounting NFS share nfs://192.168.121.200:/opt/nfs-server/ on mount point /var/lib/longhorn-backupstore-mounts/192_168_121_200/opt/nfs-server with options [nfsvers=4.2 actimeo=1 soft timeo=300 retry=2]\" pkg=nfs\n, error <nil>" interval=5m0s node=rancher70-worker2 url="nfs://192.168.121.200:/opt/nfs-server/"
```

**Comment by derekbit** [comment]
@mantissahz 
Looks expected, right?

**Comment by mantissahz** [comment]
@derekbit Yes, it is. And I will start to look into why error message is still there
Thank you.

**Comment by mantissahz** [comment]
@khushboo-rancher 
I tested master-head for nfs backup target, and waited for errors with an invalid backup target then changed backup target to a valid one, the error message on UI would be clear. 
Could you please help me check that?

**Comment by khushboo-rancher** [comment]
I think it is okay to close this issue as the reported bug doesn't exist anymore and behavior of NFS is based on current design.
