### ISSUE TITLE
[BUG] Backup CR state changes from Ready back to Completed

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#2949]
**Describe the bug**

The Backup CR state changes from `Ready` back to `Completed`.

**To Reproduce**
1. Create a new backup from volume.
2. Get the backup from the Backup page.
3. Sometimes the backup state changes from `Ready` to `Completed`.

**Expected behavior**

The final backup state should be `Ready`.

**Environment:**
 - Longhorn version: `v1.2.0-rc2`

**Additional context**

Because we have two goroutines updating the backup state, one in backup creation and the other one in pull from the remote backup target.

In general, the backup creation is finished, and then pull the backup config from the remote backup target, so the state will be `Completed` to `Ready`. But sometimes pull the backup config from the remote backup target before the backup creation, this makes the state changes from `Ready` back to `Completed`.

**Comment by jenting** [comment]
Revert to without the `Ready` state. This makes two goroutines final states are `Completed` state.

**Comment by innobead** [comment]
Closing with WON'T FIX
