### ISSUE TITLE
[BUG]Backup restore failed due to the size of the BackupVolume is empty

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2950]
**Describe the bug**
When the BackupTargetController just creates the BackupVolume CR and the BackupVolumeController has not synced it with the remote backup target, the size in the CR status can be empty then [the pre-restore check based on this BackupVolume](https://github.com/longhorn/longhorn-manager/blob/19af158e456f5609315a35b028c209ebff4510d1/controller/engine_controller.go#L1050) will fail the volume.

This may be a race issue. Not sure if the below reproducing step works.

**To Reproduce**
1. Create the 1st backup for a volume
2. Send a restore command based on the backup once the Backup is complete. (It's better to do this via a script or via an integration test)
3. Check the volume and the manager log.
    => The volume becomes Faulted. The manager will report the error log below.

**Expected behavior**
The restore works fine

**Log**
```
[longhorn-manager-9mcdr] E0830 10:09:17.704286       1 engine_controller.go:695] failed to update status for engine pvc-212d3f39-0142-457f-9a6d-4d98291d30cd-e-3a3b0f47: failed pre-restore check for engine pvc-212d3f39-0142-457f-9a6d-4d98291d30cd-e-3a3b0f47: strconv.ParseInt: parsing "": invalid syntax
[longhorn-manager-9mcdr] time="2021-08-30T10:09:17Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"pvc-212d3f39-0142-457f-9a6d-4d98291d30cd\", UID:\"579d687b-4f92-4f41-83b7-dea623589149\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"2065404\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedRestore' replica pvc-212d3f39-0142-457f-9a6d-4d98291d30cd-r-b88ed04d failed the restore: failed pre-restore check for engine pvc-212d3f39-0142-457f-9a6d-4d98291d30cd-e-3a3b0f47: strconv.ParseInt: parsing \"\": invalid syntax"
[longhorn-manager-9mcdr] time="2021-08-30T10:09:17Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"pvc-212d3f39-0142-457f-9a6d-4d98291d30cd\", UID:\"579d687b-4f92-4f41-83b7-dea623589149\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"2065404\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedRestore' replica pvc-212d3f39-0142-457f-9a6d-4d98291d30cd-r-e2f89e62 failed the restore: failed pre-restore check for engine pvc-212d3f39-0142-457f-9a6d-4d98291d30cd-e-3a3b0f47: strconv.ParseInt: parsing \"\": invalid syntax"
[longhorn-manager-9mcdr] time="2021-08-30T10:09:17Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"pvc-212d3f39-0142-457f-9a6d-4d98291d30cd\", UID:\"579d687b-4f92-4f41-83b7-dea623589149\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"2065404\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedRestore' replica pvc-212d3f39-0142-457f-9a6d-4d98291d30cd-r-f3778c81 failed the restore: failed pre-restore check for engine pvc-212d3f39-0142-457f-9a6d-4d98291d30cd-e-3a3b0f47: strconv.ParseInt: parsing \"\": invalid syntax"
```

**Environment:**
 - Longhorn version: master(08/30/2021)
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.20.9

**Comment by innobead** [comment]
cc @jenting

**Comment by PhanLe1010** [comment]
**Verification**: Passed

**Longhorn version**: master-head 08/30/2021 PDT

**Steps**:
[This integration test](https://github.com/longhorn/longhorn-tests/blob/f20bd301b44c05c54eddc73bb3b0fe78d61ea6d2/manager/integration/tests/test_basic.py#L1203) is doing the steps described in the issue description.
I run the integration test 5 times. They all passed.
