### ISSUE TITLE
[BUG] Over-provisioning doesn't work properly with values smaller than 200%

### ISSUE THREAD

**Issue by artur9010** [longhorn/longhorn#2952]
**Describe the bug**
Over-provisioning dosen't work properly with values smaller than 200%

**To Reproduce**
1. Set over-provisioning to 150%
2. Create volume larger than available volume size
3. "Replica Scheduling Failure"
4. Delete volume
5. Change over-provisioning to 200%
6. Repeat
7. Works properly

**Expected behavior**
Volume should be scheduled

**Log**
```
time="2021-08-30T11:49:30Z" level=error msg="There's no available disk for replica testowyxd-r-bef22a18, size 214748364800"
time="2021-08-30T11:49:30Z" level=error msg="unable to schedule replica" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=k8s01n03 owner=k8s01n03 replica=testowyxd-r-bef22a18 state=detached volume=testowyxd
```

**Environment:**
 - Longhorn version: v1.1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE v1.19.10
   - Number of management node in the cluster: 2
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: Ubuntu 20.04 
   - CPU per node: 8-64
   - Memory per node: 64-128GB
   - Disk type(e.g. SSD/NVMe): HDD on node where I requested a volume
   - Network bandwidth between the nodes: Gbit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 25

150%
![image](https://user-images.githubusercontent.com/4835677/131336224-9379163c-c95b-46f6-8a02-d34d3070fe9a.png)
![image](https://user-images.githubusercontent.com/4835677/131336277-ef5090f1-128e-49de-affd-5992f5f71a62.png)

200% - volume schedules properly
![image](https://user-images.githubusercontent.com/4835677/131336404-36bbbc9f-efd6-437e-8fc5-f4dbfdc2d336.png)
![image](https://user-images.githubusercontent.com/4835677/131336437-3940c785-348c-4e8b-bc17-9222dc941f6f.png)

**Comment by c3y1huang** [comment]
Could be caused by the [Storage Minimal Available Percentage](https://longhorn.io/docs/1.1.2/references/settings/#storage-minimal-available-percentage).
Similar to https://github.com/longhorn/longhorn/discussions/2685.

**Comment by artur9010** [comment]
> Could be caused by the [Storage Minimal Available Percentage](https://longhorn.io/docs/1.1.2/references/settings/#storage-minimal-available-percentage). You can check if lower the percentage helps.
> Similar to #2685.

I set overprovisioning to 150% and minimal available percentage to 0 and problem still occurs.

**Comment by PhanLe1010** [comment]
By the way, I notice that you are using HDD for Longhorn. Longhorn v1.1.2 doesn't work well with HDD and could cause a lot of rebuilding. Newer Longhorn version support HDD. See https://github.com/longhorn/longhorn/issues/2206

**Comment by PhanLe1010** [comment]
This problem is reproducible in lab.

Steps:
1. Set `Storage Over Provisioning Percentage` to a value smaller than 200 (180 in the example setup below) 
2. Create a volume with a size bigger than the `actual maximum disk space - storage reserved space` (55GB in the example setup below)
3. Observe that the replica scheduling failed. 

<img width="1913" alt="Screen Shot 2021-09-13 at 11 51 22 AM" src="https://user-images.githubusercontent.com/22139961/133140185-3bfefe74-c9b1-4088-8dad-90eafa780b74.png">

**Comment by PhanLe1010** [comment]
Possible root cause: 

This int64 division is rounded to nearest interger https://github.com/longhorn/longhorn-manager/blob/5da6ccfbba0c4ae441c6b5101ace541c42271f81/scheduler/replica_scheduler.go#L549. E.g., 180 `Storage Over Provisioning Percentage` is the same as 100

**Comment by PhanLe1010** [comment]
Can you please help assign the milestone @innobead
