### ISSUE TITLE
Node Scheduling Enable/Disable - Is there problem with it?? Not working reliably from the Longhorn UI 

### ISSUE THREAD

**Issue by damienbutt** [longhorn/longhorn#2953]
Hi all,

I have added 4x nodes that are dedicated to storage. They are all set up and running in my cluster. Within Longhorn I now want to disable node scheduling on my worker nodes. It doesn't seem to be working reliably. Even that or I am doing something wrong. I am bringing up the node options and selecting "Disable" on the node scheduling option at the top. One of them disabled initially. The rest did not and no matter how many times I reselected the disable option, it wouldn't disable the other 3 nodes. Then randomly it did another one after trying. Either I am doing something wrong or this seems a bit buggy? Is there a way I can try setting this from the command line instead?

Thanks,

D

**Environment: K3S and Rancher

Longhorn version: 1.1.1
Kubernetes version: 1.21.3+k3s1
Node config: 2x master/control-plane nodes running behind 1x NGINX load balancer, 4x worker nodes, 4x storage nodes, 1x MYSQL external database.
OS type and version: Ubuntu Server 20.04 LTS
CPU per node: 8
Memory per node: 16GB
Disk type: SCSI
Network bandwidth and latency between the nodes: 10G-Base-T
Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox/KVM

**Comment by damienbutt** [comment]
Managed to disable another one. I just keep trying. Just seems random when it decides to work or not.

**Comment by c3y1huang** [comment]
Could be hitting the issue with Traefik v2 in K3s.
You could check if [Troubleshooting: Use Traefik 2.x as ingress controller](https://longhorn.io/kb/troubleshooting-traefik-2.x-as-ingress-controller/) fits your case.

**Comment by jenting** [comment]
I think you hit the Trafik v2 issue. Please check the knowledge base to fix this issue.

Close this issue, feel free to reopen it if the knowledge base doc doesn't work for you.
