### ISSUE TITLE
[TASK] Update document to reflect on Volume Attachment Recovery Policy feature deprecation

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2954]
**What's the task? Please describe.**
Update document to reflect on Volume Attachment Recovery Policy feature deprecation.

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] documentation updated

**Additional context**
https://github.com/longhorn/longhorn/issues/2060
https://longhorn.io/docs/1.1.2/high-availability/node-failure/#volume-attachment-recovery-policy

**Comment by jenting** [comment]
Close it since it's a doc change only.
