### ISSUE TITLE
[FEATURE] Match type of status.conditions of nodes.longhorn.io to other k8s objects

### ISSUE THREAD

**Issue by HubbeKing** [longhorn/longhorn#2955]
**Is your feature request related to a problem? Please describe.**
I currently have an ansible-playbook that I use in order to automate maintenance tasks.
As part of that playbook, I have a step that waits for longhorn to be ready before continuing.
However, because the nodes.longhorn.io object contains the node conditions under status.conditions as a map of condition name to condition information, rather than as a list of conditions, I cannot use `kubectl wait --for=condition=Ready=True` like I can for standard kubernetes objects.

If one tries to do so, i.e. `kubectl -n longhorn-system wait --for=condition=Ready nodes.longhorn.io atlantia`, kubectl returns the following error message:
`error: .status.conditions accessor error: map[MountPropagation:map[lastProbeTime: lastTransitionTime:2021-08-13T13:32:04Z message: reason: status:True type:MountPropagation] Ready:map[lastProbeTime: lastTransitionTime:2021-08-21T18:59:02Z message:Node atlantia is ready reason: status:True type:Ready] Schedulable:map[lastProbeTime: lastTransitionTime:2021-08-21T18:58:20Z message: reason: status:True type:Schedulable]] is of the type map[string]interface {}, expected []interface{}`

This means that waiting for a longhorn node to be ready requires a manual check and parse
(Currently I'm doing `kubectl -n longhorn-system get nodes.longhorn.io {{ host }} -o json|jq .status.conditions.Ready.status` and grepping for `True`)

**Describe the solution you'd like**
Ideally, I'd prefer for the nodes.longhorn.io object to support the same kubectl operations that the standard kubernetes nodes object does. However, as this would require drastically altering the CRD for the object, it may be unwise to do without proper warning ahead of time - I imagine more people than me have written scripts that parse through the nodes.longhorn.io object looking for things.

**Describe alternatives you've considered**
An alternative would be to look into extending kubectl with a plugin that has proper support for the Longhorn CRD objects, so one could more easily automate operations on them without having to restort to jq shenanigans.

**Additional context**
Standard kubernetes node status.conditions: (this is essentially how every native kubernetes object represents conditions - see also pods, jobs, etc)
```
"conditions": [
    {
        "lastHeartbeatTime": "2021-08-31T07:20:53Z",
        "lastTransitionTime": "2021-08-21T18:58:18Z",
        "message": "kubelet is posting ready status. AppArmor enabled",
        "reason": "KubeletReady",
        "status": "True",
        "type": "Ready"
    }
]
```

nodes.longhorn.io status.conditions:
```
"conditions": {
    "Ready": {
        "lastProbeTime": "",
        "lastTransitionTime": "2021-08-21T18:59:02Z",
        "message": "Node atlantia is ready",
        "reason": "",
        "status": "True",
        "type": "Ready"
    }
}
```

**Comment by yasker** [comment]
@HubbeKing Thanks for the reporting. Yes, we should refactor to follow the Kubernetes pattern.

**Comment by innobead** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Main-Board-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/2955?planning-poker) with ZenHub @jenting @PhanLe1010 @shuo-wu @joshimoo

**Comment by innobead** [comment]
The following changes possibly impact e2e. cc @longhorn/qa

**Comment by derekbit** [comment]
I've  replaced status.Conditions's `map` datatype with `slice` to follow the k8s status.conditions, and also refactored the related codes.
e.g.
```
type NodeStatus struct {
-	Conditions map[string]Condition   `json:"conditions"`
+	Conditions []Condition            `json:"conditions"`
	DiskStatus map[string]*DiskStatus `json:"diskStatus"`
	Region     string                 `json:"region"`
	Zone       string                 `json:"zone"`
```
https://github.com/derekbit/longhorn-manager/commit/09f38141b9b67222c61a19c9fefe456417dc82ef


But while upgrading from v1.2.2 to the patched version, I encountered the datatype mismatching error.
Does anyone have idea about this issue? Or, to upgrade the api version to `v1beta2`?

```
time="2021-11-15T03:13:49Z" level=error msg="Upgrade failed: upgrade CRD failed: upgrade from v0.7.0 to v0.8.0: 
upgrade instance manager failed: upgrade from v0.7.0 to v0.8.0: failed to list all nodes during the instance managers 
upgrade: v1beta1.NodeList.Items: []v1beta1.Node: v1beta1.Node.Status: v1beta1.NodeStatus.Conditions: 
[]v1beta1.Condition: decode slice: expect [ or n, but found {, error found in #10 byte of ...|ditions\":{\"MountProp|..., bigger 
context ...|rCPURequest\":0,\"tags\":[]},\"status\":{\"conditions\":{\"MountPropagation\":
{\"lastProbeTime\":\"\",\"lastTransi|..."
```

**Comment by jenting** [comment]
We'll bump the longhorn CRD API version from v1beta1 to v1beta2, so the new v1beta2 API version `status.conditions` will match the k8s object `slice`, but the v1beta1 API version `status.conditions` still use the data struct `map`.

**Comment by khushboo-rancher** [comment]
Validated on master-head `01/21/2022`

Validation - **Pass**

Validated the volume, engineimage, backuptarget and node CRs, they are slice now in master-head. Tested this on fresh installed set up and upgraded (v1.2.3 -> master) set up.

Changes needed in the Integration test has been merged - https://github.com/longhorn/longhorn/issues/3462

-----------
**Backuptarget - master-head**
```
"conditions": [
            {
                "lastProbeTime": "",
                "lastTransitionTime": "2022-01-21T23:48:38Z",
                "message": "",
                "reason": "",
                "status": "False",
                "type": "Unavailable"
            }
        ],
```
**BackupTarget - v1.2.3**
```
"conditions": {
            "Unavailable": {
                "lastProbeTime": "",
                "lastTransitionTime": "2022-01-23T02:47:11Z",
                "message": "",
                "reason": "",
                "status": "False",
                "type": "Unavailable"
            }
        },
```
---------------
**Engine image - Master-head**
```
"conditions": [
            {
                "lastProbeTime": "",
                "lastTransitionTime": "2022-01-21T23:46:36Z",
                "message": "Engine image ei-b907910b (longhornio/longhorn-engine:master-head) is fully deployed on all ready nodes",
                "reason": "",
                "status": "True",
                "type": "ready"
            }
        ],
```
**Engine image - v1.2.3**
```
"conditions": {
            "ready": {
                "lastProbeTime": "",
                "lastTransitionTime": "2022-01-23T02:45:49Z",
                "message": "Engine image ei-d4c780c6 (longhornio/longhorn-engine:v1.2.3) is fully deployed on all ready nodes",
                "reason": "",
                "status": "True",
                "type": "ready"
            }
        },
```
-----------
**Volume - master-head**
```
"conditions": [
            {
                "lastProbeTime": "",
                "lastTransitionTime": "2022-01-21T23:47:27Z",
                "message": "",
                "reason": "",
                "status": "False",
                "type": "toomanysnapshots"
            },
            {
                "lastProbeTime": "",
                "lastTransitionTime": "2022-01-21T23:47:27Z",
                "message": "",
                "reason": "",
                "status": "True",
                "type": "scheduled"
            },
            {
                "lastProbeTime": "",
                "lastTransitionTime": "2022-01-21T23:47:27Z",
                "message": "",
                "reason": "",
                "status": "False",
                "type": "restore"
            }
        ]
```
**Volume - v1.2.3**
```
"conditions": {
            "restore": {
                "lastProbeTime": "",
                "lastTransitionTime": "2022-01-23T02:46:18Z",
                "message": "",
                "reason": "",
                "status": "False",
                "type": "restore"
            },
            "scheduled": {
                "lastProbeTime": "",
                "lastTransitionTime": "2022-01-23T02:46:18Z",
                "message": "",
                "reason": "",
                "status": "True",
                "type": "scheduled"
            },
            "toomanysnapshots": {
                "lastProbeTime": "",
                "lastTransitionTime": "2022-01-23T02:46:18Z",
                "message": "",
                "reason": "",
                "status": "False",
                "type": "toomanysnapshots"
            }
        },
```
-----------
**Node - master-head**
```
"conditions": [
                    {
                        "lastProbeTime": "",
                        "lastTransitionTime": "2022-01-21T23:46:34Z",
                        "message": "Disk default-disk-3bbd8bd3fc547de3(/var/lib/longhorn/) on node 18.116.67.198 is ready",
                        "reason": "",
                        "status": "True",
                        "type": "Ready"
                    },
                    {
                        "lastProbeTime": "",
                        "lastTransitionTime": "2022-01-21T23:46:34Z",
                        "message": "Disk default-disk-3bbd8bd3fc547de3(/var/lib/longhorn/) on node 18.116.67.198 is schedulable",
                        "reason": "",
                        "status": "True",
                        "type": "Schedulable"
                    }
                ]
```
**Node - v1.2.3**
```
"conditions": {
                    "Ready": {
                        "lastProbeTime": "",
                        "lastTransitionTime": "2022-01-23T02:45:24Z",
                        "message": "Disk default-disk-2d0b13cabed097d5(/var/lib/longhorn/) on node khush-test-wk1 is ready",
                        "reason": "",
                        "status": "True",
                        "type": "Ready"
                    },
                    "Schedulable": {
                        "lastProbeTime": "",
                        "lastTransitionTime": "2022-01-23T02:45:24Z",
                        "message": "Disk default-disk-2d0b13cabed097d5(/var/lib/longhorn/) on node khush-test-wk1 is schedulable",
                        "reason": "",
                        "status": "True",
                        "type": "Schedulable"
                    }
                }
```
