### ISSUE TITLE
[BUG] Wrongly restart downloading for backing images after Longhorn upgrade

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2957]
**Describe the bug**
After the upgrade, Longhorn will wrongly restart the backing image data source pods to restart downloading for backing images that already contain ready files. This is a race issue.

**To Reproduce**
1. Launch Longhorn
2. Create a backing image with data source type `download`
3. Launch some volumes using the backing image.
4. Upgrade Longhorn system with the same backing image manage image.
5. After upgrade, one ready disk file of the backing image **may** become `pending`/`in-progress`.

May need to repeat the step 1 to 4 until this race issue happens.

**Expected behavior**
All ready disk files of backing images should directly be updated from ``/`unknown` to `ready`.

**Log**

**Environment:**
 - Longhorn version: v1.2.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): 
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Kubernetes v1.20.9

**Comment by shuo-wu** [comment]
The root cause:
1. When all manager pods get restarted and the nodes have not been updated to `Ready`, the status of all files of a backing image may be `unknown`. Then the backing image controller considers [no file available then restart the download](https://github.com/longhorn/longhorn-manager/blob/5021be21e51ce49b1df6ec96a723408210baa31d/controller/backing_image_controller.go#L489-L493).

**Comment by kaxing** [comment]
Validation: **PASSED**

Prepare three set of manifest files for installation:
- v1.2.0-rc2
- v1.2.0 (GA)
- v1.2.x (branch v1.2.x)
- The first two versions had the same backing-mager-manager image tag

To reproduce:
1. Create two volumes with Backing Image (with image size around 2GB to see the downloading progress)
2. `kubectly apply` in between first two image set
3. watch the detail of the backing image (under ui/#/backingImage)
4. the backing image will be re-download

To validate with latest v1.2.x branch:
1. Repeat steps above
2. Upgrade to the v1.2.x master-head: `kubectl apply -Rf path-to-longhorn-manager-v1.2.x/deploy/install`

Screenshot for reference:
| backing image status while upgrading between rc2 and ga | backing image status while upgrading to latest backport |
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/602540/132669064-a1238766-80ee-43c0-bd34-cb7593d73da7.png)  | ![image](https://user-images.githubusercontent.com/602540/132669668-7a25fc7e-548e-4a64-bcb3-5c6e7882da8d.png) |
