### ISSUE TITLE
[QUESTION] No Upgrade available from 1.1.1 to 1.1.2

### ISSUE THREAD

**Issue by DerFels** [longhorn/longhorn#2958]
**Question**
Why can't I upgrade to Longhorn 1.1.2 through the UI? The upgrade-checker is enabled:
![grafik](https://user-images.githubusercontent.com/12964649/131516738-b52196f9-5483-4671-beb3-acdbc400b9cf.png)

However there is no "Upgrade" button anywhere to be found :(
And the 1.1.2 Version also does not show up in the drop down:
![grafik](https://user-images.githubusercontent.com/12964649/131516904-3b7586e0-bfcd-446a-ba0f-da9120434cf8.png)

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes version: 1.20.8
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**

**Comment by timmy59100** [comment]
Apparently you have to upgrade your rancher installation to see the update in cluster explorer.

**Comment by DerFels** [comment]
So this works only with Rancher 2.6.0 and upwards?

**Comment by timmy59100** [comment]
Also with the next release like 2.5.10

https://github.com/longhorn/longhorn/issues/2724#issuecomment-903849802

**Comment by DerFels** [comment]
Ok, thank you very much!
