### ISSUE TITLE
[BUG] Backups don't work after upgrading 1.1.2 to 1.2.0

### ISSUE THREAD

**Issue by timoschwarzer** [longhorn/longhorn#2960]
**Describe the bug**
I'm using the Longhorn Helm chart and updated from version 1.1.2 to 1.2.0. The new engine image got deployed and all volumes successfully updated to the new one.

I cannot create or list backups anymore, all buttons for creating backups are disabled and show this error:

![Screenshot from 2021-08-31 23-23-05](https://user-images.githubusercontent.com/8849554/131577926-9c6d3527-637a-4f68-91f2-1812007635ee.png)

**To Reproduce**
1. Upgrade from 1.1.2 to 1.2.0
2. Try to create or list backups

**Expected behavior**
I should be able to create/list backups.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.2.0
 - Installation method: Helm
 - Kubernetes distro and version: K3s 1.21.4+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Debian 10
   - CPU per node: 4
   - Memory per node: 8GB
   - Disk type: NVMe
   - Network bandwidth between the nodes: 10GBit/s
 - Underlying Infrastructure: KVM
 - Number of Longhorn volumes in the cluster: 33

**Comment by PhanLe1010** [comment]
@timoschwarzer  Can you provide us a support bundle to `longhorn-support-bundle@suse.com` ?

The error is complaining that engine image v1.2.0 is not deployed on the node that is managing the volume.

**Comment by timoschwarzer** [comment]
@PhanLe1010 thanks, sent! :)

**Comment by PhanLe1010** [comment]
Thanks @timoschwarzer! Checking

**Comment by PhanLe1010** [comment]
@timoschwarzer I couldn't open the file you sent. Can you send it in unencrypted form?

**Comment by timoschwarzer** [comment]
@PhanLe1010 The message is not encrypted, only signed. I've sent an unsigned message.

**Comment by timoschwarzer** [comment]
@PhanLe1010 Hmm, RWX volumes seem to be the culprit. After the engine upgrade, RWX volumes didn't contain any data anymore. Luckily, after shutting down the workloads and detaching the RWX volumes manually, the data was back. After I reattached all RWX volumes by hand, the backup create buttons came back and I could list backups again

**Comment by PhanLe1010** [comment]
It seems like a temporary problem with Longhorn UI not being refreshed. From the support bundle I see that engine image `v1.2.0` is deployed on all nodes but the above picture is still complaining the engine image doesn't  exist on the node.

**Comment by timoschwarzer** [comment]
@PhanLe1010 yep. The UI showed version 1.2.0 in the bottom left at the time backups didn't work though.

**Comment by PhanLe1010** [comment]
>  After the engine upgrade, RWX volumes didn't contain any data anymore (they were just empty for the workloads they were attached to)

This should be a different problem. I see in the support bundle that all volumes has the field `remountrequestedat` set which indicate somehow they are crash unexpectedly. For example, 
```
2021-08-31T23:33:04.607966627+02:00 time="2021-08-31T21:33:04Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"pvc-8fa72453-4d17-4524-9ea7-7d35587996e2\", UID:\"56971b2b-32d7-411d-bb22-1e87b29ff069\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"79432469\", FieldPath:\"\"}): type: 'Warning' reason: 'DetachedUnexpectly' Engine of volume pvc-8fa72453-4d17-4524-9ea7-7d35587996e2 dead unexpectedly, reattach the volume"
```
Were there any kind of node reboot or something?


By design, Longhorn should restart the workloads that use those volumes. However, if the volume is RWX and the workload that use the volume has only 1 pod, you may hit this known issue https://github.com/longhorn/longhorn/issues/2946. e.g, the workload pod cannot comeback. Can you confirm that one of such volume is `pushgate-pv` ?

**Comment by PhanLe1010** [comment]
> The UI showed version 1.2.0 in the bottom left at the time backups didn't work though.

Still possible that Longhorn UI is temporary lagging behide after the upgrade.

**Comment by timoschwarzer** [comment]
@PhanLe1010 I've checked and there was no node reboot or crash. Also, the volume pushgate-pv is expected to have no workload as it's scaled down currently.

**Comment by timoschwarzer** [comment]
Two out of the three longhorn-manager pods restarted 2 and 5 times respectively at the beginning. Could that be related?

**Comment by PhanLe1010** [comment]
No, Longhorn manager pods restarting shouldn't cause volume to crash.

**Comment by jenting** [comment]
> @PhanLe1010 yep. The UI showed version 1.2.0 in the bottom left at the time backups didn't work though.

Have you refreshed the page at that time? If the backup target is available,  the button change the status _only_ when you refresh the page.

**Comment by timoschwarzer** [comment]
@jenting Yep, I refreshed the page several times. I even restarted the ui pod, without success.

**Comment by jenting** [comment]
> @jenting Yep, I refreshed the page several times. I even restarted the ui pod, without success.

Another possibility is that even the default engine image is ready, however, the backup_target_controller still waits for the poll interval to reconcile the backup target. Ref to:
- https://github.com/longhorn/longhorn-manager/blob/v1.2.0/controller/backup_target_controller.go#L288-L296
- https://github.com/longhorn/longhorn-manager/blob/v1.2.0/controller/backup_target_controller.go#L244-L253
- https://github.com/longhorn/longhorn-manager/blob/v1.2.0/controller/backup_target_controller.go#L235-L238

**Comment by timoschwarzer** [comment]
@jenting I disabled polling by setting the interval to 0

**Comment by jenting** [comment]
> @jenting I disabled polling by setting the interval to 0 as it says right below the setting

Okay, thank you. I think we should only check the backup target available or not based on the backup target configuration _only_.

**Comment by jenting** [comment]
The current workaround for you is to re-configure one of the backup target settings, either backup target URL, backup target credential secret, or poll interval to re-trigger the backup_target_controller run the reconcile loop, to make the BackupTarget CR `status.available` changes from `false` to `true`.

**Comment by dgrechka** [comment]
> 
> 
> The current workaround for you is to re-configure one of the backup target settings, either backup target URL, backup target credential secret, or poll interval to re-trigger the backup_target_controller run the reconcile loop, to make the BackupTarget CR `status.available` changes from `false` to `true`.

I had the same issue.
Changing the backup poll interval worked for me to workaround it.

**Comment by chanow816** [comment]
Validation: **PASSED**

---
Prepare Longhorn 1.2.x, S3, NFS
When engine image scale down, backup become inactive
When engine image scale up, backup become active

**Test Steps:**
1 
> Scale down engine image
> Configure backup target to S3, poll interval  0
> Scale up engine image, backup become active

2
> Scale down engine image
> Configure backup target to S3, poll interval  300
> Scale up engine image, backup become active

3
> Scale down engine image
> Configure backup target to NFS, poll interval  0
> Scale up engine image, backup become active

4
> Scale down engine image
> Configure backup target to NFS, poll interval  3000
> Scale up engine image, backup become active

**Comment by chanow816** [comment]
Tested on master as well, and the validation result was passed
