### ISSUE TITLE
[BUG] Error when upgrading from 1.1.2 to 1.2.0 - Operation cannot be fulfilled on volumes.longhorn.io \"pvc-edf41777-589d-4806-baca-b91d0a6c0d3c\": the object has been modified; please apply your changes to the latest version and try again

### ISSUE THREAD

**Issue by tyzbit** [longhorn/longhorn#2961]
**Describe the bug**
When upgrading from 1.1.2 to 1.2.0 with preexisting volumes using Helm, I receive this error in the manager pod:

```
time="2021-08-31T22:26:19Z" level=error msg="Upgrade failed: upgrade CRD failed: upgrade from v1.1.0 to v1.2.0: upgrade recurring jobs failed: upgrade from v1.1.0 to v1.2.0: translate volume recurringJobs to volume labels failed: failed to update pvc-edf41777-589d-4806-baca-b91d0a6c0d3c volume: Operation cannot be fulfilled on volumes.longhorn.io \"pvc-edf41777-589d-4806-baca-b91d0a6c0d3c\": the object has been modified; please apply your changes to the latest version and try again"
time="2021-08-31T22:26:19Z" level=info msg="Upgrade leader lost: showman"
time="2021-08-31T22:26:19Z" level=fatal msg="Error starting manager: upgrade CRD failed: upgrade from v1.1.0 to v1.2.0: upgrade recurring jobs failed: upgrade from v1.1.0 to v1.2.0: translate volume recurringJobs to volume labels failed: failed to update pvc-edf41777-589d-4806-baca-b91d0a6c0d3c volume: Operation cannot be fulfilled on volumes.longhorn.io \"pvc-edf41777-589d-4806-baca-b91d0a6c0d3c\": the object has been modified; please apply your changes to the latest version and try again"
```

It seems this is localized to a single node in the cluster (showman). Most of the volumes have migrated engines already.

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/3319104/131586563-16a28a9e-30e2-4fb0-a2a3-1d8d63e7f70a.png">

I have tried deleting the offending manager pod, but have not taken any other troubleshooting steps.

**To Reproduce**
1. Create a Longhorn cluster via Helm
2. Create PVs
3. (assumed) Create backup and snapshot tasks for the PVs
4. Upgrade to 1.2.0
5. Observe the error on one of the nodes during/after upgrading

**Expected behavior**
Upgrading from 1.1.2 to 1.2.0 when using Helm should result in backup jobs being created successfully for all volumes.

**Log**

[longhorn-support-bundle_5be709ef-a54d-46ea-971f-a9f7c4fb4b26_2021-08-31T22-55-49Z.zip](https://github.com/longhorn/longhorn/files/7087171/longhorn-support-bundle_5be709ef-a54d-46ea-971f-a9f7c4fb4b26_2021-08-31T22-55-49Z.zip)

**Environment:**

    Longhorn version: 1.2.0 (partial upgrade from 1.1.2)
    Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
    Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: kubeadm
        Kubernetes version: 1.19.9
        Number of management node in the cluster: 3
        Number of worker node in the cluster: 4
    Node config
        OS type and version: Ubuntu 20.04.1 LTS
        CPU per node: 8
        Memory per node: 16GB
        Disk type(e.g. SSD/NVMe): NVMe
        Network bandwidth between the nodes: 2.5Gbit
    Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
    Number of Longhorn volumes in the cluster: 23

**Comment by PhanLe1010** [comment]
> I have tried deleting the offending manager pod, but have not taken any other troubleshooting steps.

@tyzbit Does the manager pod eventually come up?

**Comment by PhanLe1010** [comment]
It seems that we are doing unnecessary volume CR update [here](https://github.com/longhorn/longhorn-manager/blob/5021be21e51ce49b1df6ec96a723408210baa31d/upgrade/v110to120/upgrade.go#L244-L274). More specifically, it seems that we still update the volume even if it already has correct label. As a result, we increase the chance of hitting the error `the object has been modified; please apply your changes to the latest version and try again`

cc @c3y1huang

**Comment by PhanLe1010** [comment]
Thanks @tyzbit 
So the upgrade issue is gone after some retries as expected.
Now the problem is `instance manager` pod cannot start due not enough CPU resource. Will wait for your next update

**Comment by tyzbit** [comment]
Some of my volumes had 2 replicas for the concerned node, one failed and one nominal. Deleting the failed replica resulted in some of the engine images showing as updated. Proceeding to delete all failed replicas manually resulted in most of the volumes recovering. It looks like one volume has not recovered:

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/3319104/131598121-5d33fdc4-cbcb-4584-b9aa-2e0d46b05224.png">

This volume had 2 `weatherman` replicas. I manually deleted the older replica and it was stuck in this state. I rolled the pod consuming this storage and it started rebuilding (albeit missing a replica from `anchorman`).

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/3319104/131598365-c6ca9daf-9783-4ba7-a4ed-f5ab55bf35dc.png">

One thing that might be important to note is I do mount this volume multiple times; I have a app container running and a CronJob that sticks to the same node hosting the volume that performs periodic tasks on the storage. I've seen errors regarding fsck on this volume in the logs before, but I didn't open a ticket.

**Comment by PhanLe1010** [comment]
@tyzbit 

I think we should wait for all instance manager pod to come back online first before doing volume operation. Have they come up yet?

**Comment by tyzbit** [comment]
@PhanLe1010 I didn't mention it, but before I did any volume operations all instance managers were running. I didn't notice but it looks like some of them are old:
```
~|⇒ (⎈ |takeout:longhorn-system) kgp | grep instance-manager                                                                                                                     [463ms] [2021/08/31|21:58]
instance-manager-e-127c0bc8                1/1     Running   0          152d
instance-manager-e-288a886d                1/1     Running   0          55d
instance-manager-e-6fb7ee43                1/1     Running   0          3h26m
instance-manager-e-738d800c                1/1     Running   0          28d
instance-manager-e-7bf7e1ab                1/1     Running   0          44d
instance-manager-e-921a5840                1/1     Running   0          3h38m
instance-manager-e-e0ac9587                1/1     Running   0          3h37m
instance-manager-e-ecc8579c                1/1     Running   0          3h38m
instance-manager-e-f198837d                1/1     Running   0          55d
instance-manager-r-217578c5                1/1     Running   0          38m
instance-manager-r-5688cd8f                1/1     Running   0          3h38m
instance-manager-r-e0ddf2a4                1/1     Running   0          3h37m
instance-manager-r-f4d59242                1/1     Running   0          3h38m
```

**Comment by PhanLe1010** [comment]
It make senses. Once all engines and replicas are moved to the newest instance manager. Longhorn will delete the old instance manager. In order for the engines and replicas to move to new instance manager pods, you need to rollout the workload.

**Comment by PhanLe1010** [comment]
Look like the last volume is recovering

**Comment by tyzbit** [comment]
Yes, I'm going to watch to confirm it gets restored to the right number of replicas but it looks like everything's nominal now.

**Comment by tyzbit** [comment]
One last thing, it looks like the recurring backups didn't get transferred over to recurring jobs

<img width="675" alt="image" src="https://user-images.githubusercontent.com/3319104/131600630-90960922-f795-43b3-a04f-028c3cda2777.png">

Not a big deal, let me know if you want me to open another issue.

**Comment by PhanLe1010** [comment]
We can keep it this issue for now.

**Comment by c3y1huang** [comment]
> One last thing, it looks like the recurring backups didn't get transferred over to recurring jobs

From the support-bundle the volume seems to be labeled correctly but CRs didn't get created. I am not able to reproduce this one, still investigating.
```
2021-08-31T22:20:02.933334349Z time="2021-08-31T22:20:02Z" level=debug msg="Found 0 recurring job needs to be converted to CR" namespace=longhorn-system upgrade=translate-volume-recurringJobs-to-recurringJob-CRs
```
To resolve the warning you need to create the recurring jobs manually.

**Comment by HubbeKing** [comment]
I've been running into this issue a lot as well - interestingly even long after the actual upgrade to 1.2.0 - it seems the longhorn-manager *always* runs through the upgrade procedure on startup, even though it has already been done many times. 

Upgrading the longhorn-manager daemonset to use the `v1.2.x-head` image tag helps, but it still occasionally happens. 

So far, I've been having some luck scaling down workloads whenever longhorn-manager restarts - it seems the bug doesn't show up if the volumes in questions aren't mounted anywhere.

**Comment by tyzbit** [comment]
This error returned after I rebooted node 2 out of 4 for OS upgrades. @HubbeKing's suggestion of scaling down workloads allowed me to bring instance-manager up on the affected node.

**Comment by luhahn** [comment]
Also hitting this error on the first try the longhorn-manager was able to start eventually. However, after rebooting the Node it is not able to start up even after running for more than 3 hours.

**Comment by kaxing** [comment]
Validation in progress,

Tested with fresh local k3s cluster, upgrading from v1.1.1 to v1.2.x branch(longhorn/longhorn-manager@9d099bee97db50f9e5da3659861390eff6763fcf)

The existing recurring jobs will be upgraded to the `RecurringJob` CRDs.

I would like to check again with v1.1.1 to current 1.2.0 GA release to see if I can constantly reproduce this on my local environment.

**Comment by kaxing** [comment]
Validation: **PASSED**

Upgrading from v1.1.1, v1.1.2 to latest branch included the fix the RecurringJob CRDs will be created.

---
Please be noted, I can only reproduce the recurring jobs CRD upgrading problem as below,
- Set up k3s version v1.19.14+k3s1 cluster with following spec.:
- 1 control node
  - cpus 2
  - mem 4096M
  - disk 16G 
- 3 worker node
  - cpus 1
  - 3072M
  - disk 25G
- Install Longhorn release v1.1.1 or v1.1.2
- Create a few volumes and set up recurring jobs for backup and snapshot
- Upgrading Longhorn with latest manifest files from latest master branch
<details>
  <summary> 
    Recurring Job does not exist Screenshot for the reference
  </summary>

![image](https://user-images.githubusercontent.com/602540/132843640-4b5f9f57-d32b-43b3-bb80-9e4682a402f1.png)

</details>

**Comment by docbobo** [comment]
Is there a particular reason this got removed from 1.2.1, @yasker? Right now, it takes several hours for my cluster to become fully functional again whenever I have to restart some of its nodes. And I haven't seen any workaround being mentioned.

**Comment by PhanLe1010** [comment]
@docbobo 
This fix will go into `v1.2.1` as it has the label `backport-needed/1.2.1`

**Comment by elton557** [comment]
Hi, after updating my longhorn, I restarted 1 node and longhorn-manager keeps giving me this error:
time="2021-09-24T12:32:50Z" level=error msg="Upgrade failed: upgrade CRD failed: upgrade from v1.1.0 to v1.2.0: upgrade recurring jobs failed: upgrade from v1.1.0 to v1.2.0 : translate volume recurringJobs to volume labels failed: failed to update pvc-74f64132-507b-495f-9031-6ffc8c684b6e volume: Operation cannot be fulfilled on volumes.longhorn.io \"pvc-74f64132-507b-495f-9031-6ffc8c684b6e\" : the object has been modified; please apply your changes to the latest version and try again"
time="2021-09-24T12:32:50Z" level=info msg="Upgrade leader lost: rancher-k8s-dc-node05"
time="2021-09-24T12:32:50Z" level=fatal msg="Error starting manager: CRD upgrade failed: upgrade from v1.1.0 to v1.2.0: upgrade recurring jobs failed: upgrade from v1.1.0 to v1. 2.0: translate volume recurringJobs to volume labels failed: failed to update pvc-74f64132-507b-495f-9031-6ffc8c684b6e volume: Operation cannot be fulfilled on volumes.longhorn.io \"pvc-74f64132-507b-495f-9031-6ffc8c684b6e\ ": the object has been modified; please apply your changes to the latest version and try again"

**Comment by mattmattox** [comment]
I was able to work around this issue by removing the backup job from the volume. Then let the longhorn-manager start and re-add it.

**Comment by timoschwarzer** [comment]
I currently have this problem, too, after rebooting one node. Unfortunately it does not resolve by deleting all recurring job schedules, it still complains about not being able to upgrade a volume CR despite the volume not having any recurring jobs.

```
time="2021-10-03T10:35:45Z" level=fatal msg="Error starting manager: upgrade CRD failed: upgrade from v1.1.0 to v1.2.0: upgrade recurring jobs failed: upgrade from v1.1.0 to v1.2.0: translate volume recurringJobs to volume labels failed: failed to update pvc-ea380c21-e5e0-445b-8656-f530aa36867d volume: Operation cannot be fulfilled on volumes.longhorn.io \"pvc-ea380c21-e5e0-445b-8656-f530aa36867d\": the object has been modified; please apply your changes to the latest version and try again"
```

![image](https://user-images.githubusercontent.com/8849554/135749947-4f3101d9-9204-433b-8455-c72667534a2f.png)

**Comment by timoschwarzer** [comment]
Edit: The only workaround that worked for me was draining all worker nodes in the cluster, waiting for the failing manager to get back up and then uncordon everything.
