### ISSUE TITLE
[BUG] Helm chart kubeVersion requirement doesn't support complex SemVer

### ISSUE THREAD

**Issue by chasestech** [longhorn/longhorn#2963]
**Describe the bug**
When using the Helm chart to upgrade from version 1.1.2 to 1.2.0, I received: `Error: chart requires kubeVersion: >=v1.18.0 which is incompatible with Kubernetes v1.21.3-3+90fd5f3d2aea0a`

The previous version of the Helm chart allowed for complex Kubernetes semantic versions, but the new version of the chart does not. Changing the constraint to `kubeVersion: >=1.18.0-r0` succeeded in my local testing on both a complex and non-complex semver Kubernetes distro.

**To Reproduce**
1. Using a Kubernetes distribution that has a complex semver, such as MicroK8s, attempt to install or upgrade to Helm Chart version 1.2.0. Install/upgrade will fail.

**Expected behavior**
New version of Helm chart should support Kubernetes versions that use complex semver format.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: MicroK8s v1.21.3-3+90fd5f3d2aea0a
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 12
   - Memory per node: 64
   - Disk type(e.g. SSD/NVMe): HDD
   - Network bandwidth between the nodes: NA
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 8

**Additional context**
NA

**Comment by jenting** [comment]
Thank you @chasestech We'll fix it
cc @PhanLe1010

**Comment by innobead** [comment]
cc @PhanLe1010

**Comment by shuo-wu** [comment]
Should we modify it to `"kubeVersion: >=1.18.0-0"` rather than `"kubeVersion: >=1.18.0-r0"`? To allow prereleases, typically the constraints suffix `-0` will be used. And I am not sure if we can still use the suffix `-r0`:
https://github.com/rancher/rancher/issues/34588

**Comment by jenting** [comment]
Looking at the https://github.com/helm/helm/issues/9371#issuecomment-780062820 again, using `-0` seems to be a better way.

Besides that, I found that the error message of https://github.com/rancher/rancher/issues/34588 is because we adding the prefix `v`.
This check failed https://github.com/rancher/rancher/blob/release/v2.5.9/pkg/catalog/manager/manager.go#L218-L221 if we adding the prefix `v`.
However, currently, I can't reproduce this error with Rancher v2.5.9 with Cluster Manager to install Longhorn v1.1.2.

**Comment by innobead** [comment]
see https://github.com/Masterminds/semver/blame/master/README.md#L153-L157

**Comment by kaxing** [comment]
Validating in progress,

Tested with chart from master branch beyond longhorn/charts@1d469af8ba1deec0a53fbb92eaf753e6e894ae1a
- kubernetes version:
  - microk8s v1.21.3
    - Client Version: v1.21.1
    - Server Version: v1.21.3-3+90fd5f3d2aea0a
- helm via microk8 version:
  - `version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}`

Additional note,
I had to install and upgrade with specific kubelet root dir as following, wondering if @chasestech also encounter this? 
```
$ microk8s helm3 upgrade longhorn longhorn/longhorn --version 1.1.2 --namespace longhorn-system --set csi.kubeletRootDir=/var/lib/kubelet
$ microk8s helm3 upgrade longhorn local-chartmuseum/longhorn --version 1.2.0 --namespace longhorn-system --set csi.kubeletRootDir=/var/lib/kubelet
```

Reference:
- Setting up chartmuseum for testing: https://chartmuseum.com/

**Comment by kaxing** [comment]
Validation: **PASSED**

Also tested on,
- rke2
  - Client Version: v1.21.1
  - Server Version: v1.21.4+rke2r2
- k3s
  - Client Version: v1.21.1
  - Server Version: v1.19.14+k3s1
 
---

Test steps overview:
1. Prepare 3 VMs
2. Install k8s distro, release version naming contains SemVer
3. Set up chartmuseum on localhost
4. Upload latest longhorn chart package
5. Helm install v1.1.2
6. Helm upgrade to the latest v1.2.0(master via local chart museum)

Expecting Longhorn deployment will be finished

**Comment by chasestech** [comment]
> I had to install and upgrade with specific kubelet root dir as following, wondering if @chasestech also encounter this?

Yes, I also had to set the csi.kubeletRootDir on my microk8s environment. 

Thank you all for your work on this!

**Comment by yasker** [comment]
> Should we modify it to `"kubeVersion: >=1.18.0-0"` rather than `"kubeVersion: >=1.18.0-r0"`? To allow prereleases, typically the constraints suffix `-0` will be used. And I am not sure if we can still use the suffix `-r0`:
> [rancher/rancher#34588](https://github.com/rancher/rancher/issues/34588)

I thought that issue is because of the prefix`v`, not suffix `-r`. And why are we allowing the prereleases?

**Comment by shuo-wu** [comment]
> I thought that issue is because of the prefix`v`, not suffix `-r`. And why are we allowing the prereleases? maybe for testing purposes?

You mean blocking the Longhorn installation if the cluster is not using an official Kubernetes release?

**Comment by yasker** [comment]
@shuo-wu No, I was wondering why we want to change the behavior to allow prereleases. What's the difference (doc) between `-r0` vs `-0`?

**Comment by shuo-wu** [comment]
> @shuo-wu No, I was wondering why we want to change the behavior to allow prereleases. What's the difference (doc) between `-r0` vs `-0`?

Unfortunately, I didn't figure out the difference by google `-r0`  last time...

**Comment by PhanLe1010** [comment]
From [the comment](https://github.com/helm/helm/issues/9371#issuecomment-780062820) that @jenting mentioned above :
> `0` is used because SemVer uses ASCII (see the spec) and `0` is the lowest ASCII character used in SemVer.
