### ISSUE TITLE
[BUG] lots of zombie processes

### ISSUE THREAD

**Issue by joy717** [longhorn/longhorn#2965]
**Describe the bug**
longhorn-manager creates a lot of zomebie processes.

```
[root@k8s-m-01 logs]# ps -A -ostat,ppid,pid,cmd | grep -e '^[Zz]'| awk '{print $2}'|sort | uniq -c
      1 16110
  27957 41799
```
here longhorn-manager creates 27957 zombie processes. and it's keep growing.

```
[root@k8s-m-01 logs]# ps aux | grep 41799
root     41799  1.7  0.0 823364 125764 ?       Ssl  Aug30  58:04 longhorn-manager -d daemon --engine-image x.x.x.x:7071/handyops/longhornio/longhorn-engine:v1.1.2 --instance-manager-image x.x.x.x:7071/handyops/longhornio/longhorn-instance-manager:v1_20210621 --share-manager-image x.x.x.x:7071/handyops/longhornio/longhorn-share-manager:v1_20210416 --backing-image-manager-image x.x.x.x:7071/handyops/longhornio/backing-image-manager:v1_20210422 --manager-image x.x.x.x:7071/handyops/longhornio/longhorn-manager:v1.1.2 --service-account longhorn-service-account
```

zombie process:
```
[root@k8s-m-01 logs]#  ps -A -ostat,ppid,pid,cmd | grep -e '^[Zz]' | tail -n 5
Z    41799 49145 [mount] <defunct>
Z    41799 49147 [mount] <defunct>
Z    41799 49148 [mount] <defunct>
Z    41799 49150 [mount] <defunct>
Z    41799 49151 [mount] <defunct>
```

**To Reproduce**
don't know how to reproduce.

**Expected behavior**
no zombie processes.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm (Harvester)
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:  1.18.14 (k8s original)
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3(masters are also workers)
 - Node config
   - OS type and version: CentOS-7
   - CPU per node: 48 processor
   - Memory per node:  256G
   - Disk type(e.g. SSD/NVMe): HHD
   - Network bandwidth between the nodes: 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 28

**Additional context**

**Comment by joy717** [comment]
find something interesting, but don't know if it is related with zombie processes :
instance-manager keep trying to write data to replicates, but with a wrong port:
```
time="2021-09-02T06:25:45Z" level=error msg="Retry  1 on replica 10.233.71.46:10001 seq= 46296 size= 4 (kB)"
[pvc-adeb862a-6dbe-49fe-abf5-f262a5039a67-e-cb511d6c] time="2021-09-02T06:25:45Z" level=error msg="Write timeout on replica 10.233.71.46:10001 seq= 46297 size= 580 (kB)"
time="2021-09-02T06:25:45Z" level=error msg="Retry  1 on replica 10.233.71.46:10001 seq= 46297 size= 580 (kB)"
[pvc-adeb862a-6dbe-49fe-abf5-f262a5039a67-e-cb511d6c] time="2021-09-02T06:25:45Z" level=error msg="Write timeout on replica 10.233.71.46:10001 seq= 46298 size= 24 (kB)"
time="2021-09-02T06:25:45Z" level=error msg="Retry  1 on replica 10.233.71.46:10001 seq= 46298 size= 24 (kB)"
```

in the 10.233.71.46(pod instance-manager-r-xxxxx), I found the pvc-adeb862a-6dbe-49fe-abf5-f262a5039a67-e-cb511d6c is listening on 10000
```
root@instance-manager-r-bf1b1c20:/tmp# ps aux > ps.log
root@instance-manager-r-bf1b1c20:/tmp# cat ps.log | grep pvc-adeb862a-6dbe-49fe-abf5-f262a5039a67
root      9671  0.1  0.0 3012692 58596 ?       Sl   03:17   0:12 /host/var/lib/longhorn/engine-binaries/180.101.34.33-7071-handyops-longhornio-longhorn-engine-v1.1.2/longhorn replica /host/var/lib/longhorn/replicas/pvc-adeb862a-6dbe-49fe-abf5-f262a5039a67-5a28d9f3 --size 53687091200 --backing-file /host/var/lib/longhorn/backing-images/image-tg576-b0fb91e1/backing --listen 0.0.0.0:10000
```

and the instancemanagers.longhorn.io resource show me :
```
...
    pvc-adeb862a-6dbe-49fe-abf5-f262a5039a67-e-cb511d6c:
      spec:
        name: pvc-adeb862a-6dbe-49fe-abf5-f262a5039a67-e-cb511d6c
      status:
        endpoint: ""
        errorMsg: ""
        listen: ""
        portEnd: 10000
        portStart: 10000
        resourceVersion: 0
        state: running
        type: ""
...
```

**Comment by joy717** [comment]
Another issue:
Sometimes, the pvc can't be umount, because the loopback device is still there.

here is the log from kubelet:
```
Sep 02 13:59:50 k8s-m-01 kubelet[33245]: W0902 13:59:50.748417   33245 volume_path_handler_linux.go:61] couldn't find loopback device which takes file descriptor lock. Skip detaching device. device path
: "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-7ae474e6-79b7-426a-863b-337a7ef8f5a2/dev/acf0b5d4-5155-471b-9ea9-55b9b6e52b91"
Sep 02 13:59:50 k8s-m-01 kubelet[33245]: W0902 13:59:50.748449   33245 volume_path_handler.go:219] Warning: Unmap skipped because symlink does not exist on the path: /var/lib/kubelet/pods/acf0b5d4-5155-
471b-9ea9-55b9b6e52b91/volumeDevices/kubernetes.io~csi/pvc-7ae474e6-79b7-426a-863b-337a7ef8f5a2
```


k8s will check the loopback device, and detach the device.
but `losetup` show me like this: 
```
 /dev/loop1: [0006]:342761277 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-7ae474e6-79b7-426a-863b-337a7ef8f5a2/dev/acf0b5d4-5155-471b-9ea9-55b9b6e52b91(deleted))
```
https://github.com/kubernetes/kubernetes/blob/c96aede7b5205121079932896c4ad89bb93260af/pkg/volume/util/volumepathhandler/volume_path_handler_linux.go#L146
volume_path_handler can not match the path, because the path has a suffix `(deleted)`
so volumePathHandler won't call `losetup -d /dev/loop1`, 
then longhorn will try to remount volume again and again...

Here is my confusion:
Is the volume path with a suffix `(deleted)` expected?

If yes, this is a bug of volumePathHandler of k8s.
if not, does the zombie processes make '(deleted)' happened?

**Comment by joy717** [comment]
I've deleted all volumes.longhorn.io,  and restart longhorn-manager, but zombie processes still present.

**Comment by shuo-wu** [comment]
> find something interesting, but don't know if it is related with zombie processes :
> instance-manager keep trying to write data to replicates, but with a wrong port:

This part seems to work as expected:
1. There is no doubt that the volume engine process can listen on port 10000 inside a pod (pod `instance-manager-e-xxxx` in namespace `longhorn-system`) and it controls and communicate with all replicas of this volumes.
2. Each volume replica process **consumes 15 ports**. The process uses the first 3 ports to talk with the engine processes or longhorn managers. The rest ports are retained for file syncing during replica rebuilding. If you check the replica instance manager, which manages the lifecycle of replica processes, the status should be like:
  ```
  $ kubectl -n longhorn-sytem get lhim instance-manager-r-51fb2c8a -o yaml
  apiVersion: longhorn.io/v1beta1
  kind: InstanceManager
  metadata:
    creationTimestamp: "2021-09-01T08:18:48Z"
    generation: 1
    labels:
      longhorn.io/component: instance-manager
      longhorn.io/instance-manager-image: imi-95c270a2
      longhorn.io/instance-manager-type: replica
      longhorn.io/managed-by: longhorn-manager
      longhorn.io/node: shuo-cluster-worker-1
    name: instance-manager-r-51fb2c8a
    namespace: longhorn-system
    ownerReferences:
    - apiVersion: longhorn.io/v1beta1
      blockOwnerDeletion: true
      kind: Node
      name: shuo-cluster-worker-1
      uid: 84aa1c57-fc1e-40f5-8300-826605db5228
    resourceVersion: "648740"
    uid: 26b9b3c6-cb67-40d5-a54c-6e507d52fd17
  spec:
    engineImage: ""
    image: longhornio/longhorn-instance-manager:v1_20210731
    nodeID: shuo-cluster-worker-1
    type: replica
  status:
    apiMinVersion: 1
    apiVersion: 1
    currentState: running
    instances:
      vol-r-171bade1:
        spec:
          name: vol-r-171bade1
        status:
          endpoint: ""
          errorMsg: ""
          listen: ""
          portEnd: 10014
          portStart: 10000
          resourceVersion: 0
          state: running
          type: ""
  ```
  Notice that the `portStart` is 10000 whereas `portEnd` is `10014`

**Comment by joy717** [comment]
Thanks for replying, shuo-wu
I've deleted all volumes. so I can't get any replicas.  so sad...

But  there are lots of error log, and port 10001 is not existed..
Don't know whether this is expected.  /cry..

**Comment by joy717** [comment]
for zombie process:

here are processes in the longhorn-manager pod:
```
root@longhorn-manager-82968:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  1.3  0.0 818980 96256 ?        Ssl  10:08   0:01 longhorn-manager -d daemon --engine-image 180.101.34.33:7071/handyops/longhornio/longhorn-engine:v1.1.2 --instance-manager-image 180.101.
root        27  0.0  0.0      0     0 ?        Z    10:08   0:00 [mount] <defunct>
root        57  0.0  0.0      0     0 ?        Z    10:08   0:00 [mount] <defunct>
root       115  0.0  0.0      0     0 ?        Z    10:08   0:00 [mount] <defunct>
root       148  0.0  0.0      0     0 ?        Z    10:08   0:00 [mount] <defunct>
root       174  0.0  0.0      0     0 ?        Z    10:09   0:00 [mount] <defunct>
root       200  0.0  0.0      0     0 ?        Z    10:09   0:00 [mount] <defunct>
root       226  0.0  0.0      0     0 ?        Z    10:09   0:00 [mount] <defunct>
root       258  0.0  0.0      0     0 ?        Z    10:09   0:00 [mount] <defunct>
root       290  0.0  0.0      0     0 ?        Z    10:09   0:00 [mount] <defunct>
root       316  0.0  0.0      0     0 ?        Z    10:09   0:00 [mount] <defunct>
root       343  0.0  0.0      0     0 ?        Z    10:09   0:00 [mount] <defunct>
root       369  0.0  0.0      0     0 ?        Z    10:09   0:00 [mount] <defunct>
root       401  0.0  0.0      0     0 ?        Z    10:09   0:00 [mount] <defunct>
root       433  0.0  0.0      0     0 ?        Z    10:09   0:00 [mount] <defunct>
root       459  0.0  0.0      0     0 ?        Z    10:10   0:00 [mount] <defunct>
root       485  0.0  0.0      0     0 ?        Z    10:10   0:00 [mount] <defunct>
root       517  0.0  0.0      0     0 ?        Z    10:10   0:00 [mount] <defunct>
root       549  0.0  0.0      0     0 ?        Z    10:10   0:00 [mount] <defunct>
root       575  0.0  0.0      0     0 ?        Z    10:10   0:00 [mount] <defunct>
root       586  0.0  0.0  18516  3352 pts/0    Ss   10:10   0:00 bash
root       610  0.0  0.0  11704   252 ?        S    10:10   0:00 /bin/sh /usr/local/bin/mount
root       612  0.0  0.0   4376   692 ?        S    10:10   0:00 sleep 5
root       621  0.0  0.0  34416  2748 pts/0    R+   10:10   0:00 ps aux
```

seems that the '/bin/sh /usr/local/bin/mount'  process create zombie processes.
every 5s(or 10s) a 'mount' zombie process.

**Comment by shuo-wu** [comment]
I don't know how to reproduce it. IIRC, typically there won't be mount operation in the longhorn manager pods.

**Comment by joy717** [comment]
> I don't know how to reproduce it. IIRC, typically there won't be mount operation in the longhorn manager pods.

thanks again, shuo-wu

the code calling "mount" is from here:
https://github.com/longhorn/longhorn-manager/blob/3bba35765633fd2e4e71f4e6d3b74c6d8a8edb46/vendor/github.com/longhorn/go-iscsi-helper/util/util.go#L91

After a few days digging, 
The zombie processes are caused by a customized "mount" executable script. 
Longhorn-manager will call 'mount', then leave the zombie processes.
But this issue is **NOT** related with Longhorn,  is this issue can be closed?
@shuo-wu
