### ISSUE TITLE
[Question] Node volume storage reserved: default too high? ability to set default?

### ISSUE THREAD

**Issue by mstrent** [longhorn/longhorn#2966]
The default amount of reserved storage for a 100GB volume comes out to almost 30GB. This seems high.

The documentation doesn't talk much about this, but suggests it's space reserved for external operating system level use and whatnot. 

If that assessment is true, when you're using a separate, non-root volume, a more sensible default might be 10% or something?

**Describe the solution you'd like**
I'd like to better understand the implications of lowering this value.

I'd also like to be able to set a different default, rather than having to edit each Node in the GUI. Looking through the docs and source code, I'm not seeing a current way to do this.

Thanks!!

**Comment by shuo-wu** [comment]
The restore storage of a Longhorn node mainly affects the schedulable storage size of the volume:
schedulable storage size = (total size - reserved size) * overprovisioning percentage.

And IIRC, the volume IO won't be blocked even if the volume replicas on this node are trying to use the reserved storage.

Right now there is no way to customize the value. By default, it reserved space is 30% of the total disk size. But you can adjust the overprovisioning percentage as a workaround.

**Comment by jenting** [comment]
I think you could change the value on the GUI by changing the value of `Edit Node and Disks` -> `Storage Reserved`.

**Comment by shuo-wu** [comment]
Yes. Users can modify it in GUI. But the **default** value is always 30% of the total space when Longhorn **automatically creates default disks** for the node.

**Comment by jenting** [comment]
Closing this issue since the question is addressed.
