### ISSUE TITLE
[TEST] Add test case in e2e integration test for fsgroup support

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2967]
**What's the test to develop? Please describe.**
Add test cases where pod attached to volume is running as non-root. It should have the permission to access.

**Describe the items of the test development (DoD, definition of done) you'd like.**
- [x] Create the skeleton of test cases as per https://github.com/longhorn/longhorn/issues/2131#issuecomment-778897129
- [x] Implement the test cases.

**Additional context**
https://github.com/longhorn/longhorn/issues/2131

**Comment by khushboo-rancher** [comment]
The test passed on our nightly integration test run https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/459/testReport/tests/test_basic/test_workload_with_fsgroup/

**Comment by innobead** [comment]
cc @chanow816 @kaxing this is an example when u work on e2e test cases impl.
