### ISSUE TITLE
[BUG] Kubernetes 1.22 is not supported by 1.1.x

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#2971]
https://github.com/longhorn/longhorn/issues/2757 for v1.1.3. Only focus on supporting 1.22.

cc @longhorn/qa

**Comment by PhanLe1010** [comment]
Update: some of the CSI sidecar components doesn't work with Kubernetes v1.22 (e.g., the csi-attacher). 
So, we also need to update the csi sidecar components not just the k8s dependency

**Comment by PhanLe1010** [comment]
Note: We need to add to v1.1.3 release note that this version only runs on Kubernetes >= v1.18

**Comment by PhanLe1010** [comment]
Test steps: 

* Follow the manual test steps at https://github.com/longhorn/longhorn-tests/pull/676/files but for Longhorn v1.1.3 version
* Check the following items:
    - Raise K8s version in Helm chart
    - Raise K8s version in Doc, Release note
    - Check the fsGroup permission issue https://github.com/longhorn/longhorn/issues/2964#issuecomment-911993644
    - Check the RWX feature feature
    - Check uninstallation using Helm/Kubectl

**Comment by PhanLe1010** [comment]
@kaxing 
Please pause on testing this issue. We are planing to revert the commits of this issue because we don't want to drop support for Kubernetes v1.16 and v1.17 in Longhorn v1.1.3 
cc @innobead

**Comment by innobead** [comment]
As per @PhanLe1010 investigation, it's unable to support K8s 1.22 in the coming 1.1.3 w/o updating CSI sidecars because the current sidecars use the deprecated storage storage.k8s.io/v1beta1) APIs which was deprecated and removed from 1.22 already. Also updating sidecars will also require users to have 1.18 minimum version cluster first before upgrading to 1.1.3.

For a patch release, we should focus on bug fixes instead of having another assumption (ex: need to upgrade to K8s 1.18+ first) to avoid users upgrading to it.

So, 1.1.3 will not support 1.22, but if users would like to use longhorn on 1.22, we will suggest using 1.2 instead. (1.2.3 will be a stable release)

**Comment by davidmateos** [comment]
> As per @PhanLe1010 investigation, it's unable to support K8s 1.22 in the coming 1.1.3 w/o updating CSI sidecars because the current sidecars use the deprecated storage storage.k8s.io/v1beta1) APIs which was deprecated and removed from 1.22 already. Also updating sidecars will also require users to have a 1.18 minimum version cluster first before upgrading to 1.1.3.
> 
> For a patch release, we should focus on bug fixes instead of having another assumption (ex: need to upgrade to K8s 1.18+ first) to avoid users upgrading to it.
> 
> So, 1.1.3 will not support 1.22, but if users would like to use longhorn on 1.22, we will suggest using 1.2 instead. (1.2.3 will be a stable release)
> 
> cc @jenting @khushboo-rancher @kaxing

@innobead, apart from the Longhorn UI, where can I find information about which Longhorn versions are (or will be) stable releases?
