### ISSUE TITLE
[BUG] snapshot-controller 4.0 is not able to read VolumeSnapshotClass 

### ISSUE THREAD

**Issue by cocampbe** [longhorn/longhorn#2973]
Similar to the issue #2431 

**Describe the bug**
create a volumesnapshot using the CSI is not working. I get this Error from the snapshot-controller.

> E0902 15:48:55.025040       1 reflector.go:138] github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/factory.go:117: Failed to watch *v1.VolumeSnapshot: failed to list *v1.VolumeSnapshot: the server could not find the requested resource (get volumesnapshots.snapshot.storage.k8s.io)
I0902 15:49:13.085748       1 reflector.go:255] Listing and watching *v1.VolumeSnapshotContent from github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/factory.go:117
E0902 15:49:13.087262       1 reflector.go:138] github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/factory.go:117: Failed to watch *v1.VolumeSnapshotContent: failed to list *v1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
I0902 15:49:19.716646       1 reflector.go:255] Listing and watching *v1.VolumeSnapshotClass from github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/factory.go:117
E0902 15:49:19.717937       1 reflector.go:138] github.com/kubernetes-csi/external-snapshotter/client/v4/informers/externalversions/factory.go:117: Failed to watch *v1.VolumeSnapshotClass: failed to list *v1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)

**To Reproduce**
1. Follow the direction on this page: https://longhorn.io/docs/1.1.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/
2. Try to take a snapshot via CSI snapshot
4. No visual snapshot in longhorn UI

**Expected behavior**
volumesnapshot created and visible snapshot seen in the longhorn UI.

**Log**
See above

**Environment:**
 - Longhorn version: 1.1.0
 - Installation method: Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE v1.19.10
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 6
 - Node config
   - OS type and version: OL7.9
   - CPU per node: 16
   - Memory per node: 128
   - Disk type(e.g. SSD/NVMe): Vdisk on SSD
   - Network bandwidth between the nodes: 10Gb
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 19

**Additional context**
Snapshotting works if I use this image: quay.io/k8scsi/snapshot-controller:v2.0.0-rc4

I also tried 4.2 for grins and it actually goes into a crashloop. It fails about 5 seconds after starting.  I started to think it was related to RBAC. But now, I am not sure. We are using v1beta1 of the snapshot CRDs, as the longhorn docs suggest.

**Comment by c3y1huang** [comment]
Relate to https://github.com/longhorn/longhorn/issues/2534.

**Comment by c3y1huang** [comment]
Could you provide the output of `kubectl get crd` ?

**Comment by cocampbe** [comment]
> Could you provide the output of `kubectl get crd` ?

```text
alertmanagers.monitoring.coreos.com
apps.catalog.cattle.io
backups.velero.io
backupstoragelocations.velero.io
bgpconfigurations.crd.projectcalico.org
bgppeers.crd.projectcalico.org
blockaffinities.crd.projectcalico.org
clusterauthtokens.cluster.cattle.io
clusterinformations.crd.projectcalico.org
clusterrepos.catalog.cattle.io
clusters.management.cattle.io
clusteruserattributes.cluster.cattle.io
csidrivers.csi.storage.k8s.io
csinodeinfos.csi.storage.k8s.io
deletebackuprequests.velero.io
downloadrequests.velero.io
engineimages.longhorn.io
engines.longhorn.io
features.management.cattle.io
felixconfigurations.crd.projectcalico.org
globalnetworkpolicies.crd.projectcalico.org
globalnetworksets.crd.projectcalico.org
helmreleases.helm.fluxcd.io
hostendpoints.crd.projectcalico.org
instancemanagers.longhorn.io
ipamblocks.crd.projectcalico.org
ipamconfigs.crd.projectcalico.org
ipamhandles.crd.projectcalico.org
ippools.crd.projectcalico.org
kubecontrollersconfigurations.crd.projectcalico.org
networkpolicies.crd.projectcalico.org
networksets.crd.projectcalico.org
nodes.longhorn.io
operations.catalog.cattle.io
podmonitors.monitoring.coreos.com
podvolumebackups.velero.io
podvolumerestores.velero.io
preferences.management.cattle.io
prometheuses.monitoring.coreos.com
prometheusrules.monitoring.coreos.com
replicas.longhorn.io
resticrepositories.velero.io
restores.velero.io
scheduledsparkapplications.sparkoperator.k8s.io
schedules.velero.io
serverstatusrequests.velero.io
servicemonitors.monitoring.coreos.com
settings.longhorn.io
settings.management.cattle.io
sharemanagers.longhorn.io
thanosrulers.monitoring.coreos.com
volumes.longhorn.io
volumesnapshotclasses.snapshot.storage.k8s.io
volumesnapshotcontents.snapshot.storage.k8s.io
volumesnapshotlocations.velero.io
volumesnapshots.snapshot.storage.k8s.io
```

**Comment by jenting** [comment]
@cocampbe would you mind filing a PR to https://github.com/longhorn/website to update the doc wording? That'd be great to help us improve the doc, thank you.

**Comment by xenuser** [comment]
A quick question for my own understanding: When deploying Longhorn and adding all the CRDs, the controllers etc. **afterwards**, is Longhorn expected to "see" those changes and are CSI snapshots expected to work with Longhorn? Or is it required to remove Longhorn, add all CRDs etc. that can be added, then deploy Longhorn and then create the VolumeSnapshotClass?

I am asking because I followed the docs, still a snapshot will not become ready:

`kubectl describe volumesnapshot/pvc-1645026603
[..]
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
  [..]
  Managed Fields:
    [..]
    Manager:      snapshot-controller
    Operation:    Update
    Time:         2022-02-16T15:50:04Z
    API Version:  snapshot.storage.k8s.io/v1beta1
    [..]
    Manager:         stash
    Operation:       Update
   [..]
Spec:
  Source:
    Persistent Volume Claim Name:  replaced_this_value
  Volume Snapshot Class Name:      
Status:
  Error:
    Message:  Failed to get snapshot class with error volumesnapshotclass.snapshot.storage.k8s.io "" not found
    Time:     2022-02-16T15:50:04Z
Events:
  Type     Reason                  Age    From                 Message
  ----     ------                  ----   ----                 -------
  Warning  GetSnapshotClassFailed  2m12s  snapshot-controller  Failed to get snapshot class with error volumesnapshotclass.snapshot.storage.k8s.io "" not found
`

In my setup, Stash is trying to create this snapshot. Or could this be an issue with Stash?

Kubernetes: 1.19.16
Longhorn: 1.2.3

The more I think about it, the more I assume that this could be an issue of Stash and not Longhorn. But still, it would be great to have a reply on my initial question whether it is required to add all the CRDs and the controllers BEFORE deploying Longhorn.

**Comment by innobead** [comment]
I don't think the order matters, because the snapshot CRDs are actually required by snapshot controller instead, then interact with Longhorn CSI controller vis CSI spec. 

This seems like the CRDs are not installed well to be recognized.

**Comment by innobead** [comment]
Let's update the current doc if needed.

**Comment by xenuser** [comment]
Thank you for your reply @innobead  ! I guess it doesn't matter in what namespace the CRDs will be deployed to?

**Comment by jenting** [comment]
> My suggestion would be to update the longhorn docs to intentionally say you need to use the 4.0 crds. The prereqs on the page make it seem like you just need to have the v1beta1 crds.

We add the sentence to inform the user to deploy the same release version of snapshot CRDs and snapshot controller.

Close this issue.

**Comment by iosifnicolae2** [comment]
Does longhorn support VolumeSnapshotClass API version v1? Wouldn't be good to support both versions?

We're getting the following errors because we're using v1:
```
E1220 21:21:26.693784 1 reflector.go:127] github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotClass: failed to list *v1beta1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)
--
Tue, Dec 20 2022 11:21:26 pm | E1220 21:21:26.693838 1 reflector.go:127] github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotContent: failed to list *v1beta1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
Tue, Dec 20 2022 11:21:27 pm | E1220 21:21:27.835549 1 reflector.go:127] github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotContent: failed to list *v1beta1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
Tue, Dec 20 2022 11:21:27 pm | E1220 21:21:27.844773 1 reflector.go:127] github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotClass: failed to list *v1beta1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)
```

**Comment by innobead** [comment]
@iosifnicolae2 the upcoming longhorn 1.4.0 will upgrade to 5.0.1 snapshoter controller. Does it fix the issue as well?

**Comment by iosifnicolae2** [comment]
Yes, upgrading to v6.0.1 csi snapshoter fixed the issue.
