### ISSUE TITLE
[BUG] After upgrade to 1.2.0, longhorn-manager fails to start properly after reboot

### ISSUE THREAD

**Issue by docbobo** [longhorn/longhorn#2978]
**Describe the bug**
After upgrading from `1.1.2` to `1.2.0` via Helm Chart, I had to reboot a few of the worker nodes today. Afterwards, the `longhorn-manager` did not come up properly and seem to be stuck in a CrashLoop.

Logs show the following:

```
time="2021-09-03T10:30:11Z" level=error msg="Upgrade failed: upgrade CRD failed: upgrade from v1.1.0 to v1.2.0: upgrade recurring jobs failed: upgrade from v1.1.0 to v1.2.0: translate volume recurringJobs to volume labels failed: failed to update mariadb-0 volume: Operation cannot be fulfilled on volumes.longhorn.io \"mariadb-0\": the object has been modified; please apply your changes to the latest version and try again"
time="2021-09-03T10:30:11Z" level=info msg="Upgrade leader lost: k3os-agent-pve01-amd64-e6cda727"
time="2021-09-03T10:30:11Z" level=fatal msg="Error starting manager: upgrade CRD failed: upgrade from v1.1.0 to v1.2.0: upgrade recurring jobs failed: upgrade from v1.1.0 to v1.2.0: translate volume recurringJobs to volume labels failed: failed to update mariadb-0 volume: Operation cannot be fulfilled on volumes.longhorn.io \"mariadb-0\": the object has been modified; please apply your changes to the latest version and try again"
```

**To Reproduce**
Sorry, no idea.

**Expected behavior**
Longhorn comes up properly.

**Log**
n/a

**Environment:**
 - Longhorn version: 1.2.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm 
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s 1.21.4
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 6
 - Node config
   - OS type and version: k3os
   - CPU per node: 4
   - Memory per node: 8192
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 1gb
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetak
 - Number of Longhorn volumes in the cluster: 25

**Additional context**

**Comment by c3y1huang** [comment]
Same as https://github.com/longhorn/longhorn/issues/2961.

**Comment by docbobo** [comment]
Guess I didn't find it because the error message was saying 1.1.2 -> 1.2.0 instead. Thanks.

**Comment by docbobo** [comment]
Is there anything I can do until we get v1.2.1? I need to move some hardware pretty soon and suspect that the cluster won't come up with this problem afterwards,
