### ISSUE TITLE
[QUESTION] How to delete first system snapshot

### ISSUE THREAD

**Issue by MittWillson** [longhorn/longhorn#2979]
**Question**

How to delete the first system snapshot

**Environment:**
 - Longhorn version: 1.1.2
 - Kubernetes version: 1.21.4
 - Node config
   - OS type and version: Debian11
   - CPU per node: 12
   - Memory per node: 64
   - Disk type: SSD
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): RKE2

**Additional context**

I want totally remove the snapshots for this Volume, it takes more than the allocated size because snapshot, i only want keep the head img

![image](https://user-images.githubusercontent.com/10653144/132133067-3cf1e889-7da0-4408-a29a-9899515cc86a.png)

**Comment by jenting** [comment]
You should be able to click the blue button, there is a `Delete` button to delete the snapshot.

![Screenshot from 2021-09-07 14-40-32](https://user-images.githubusercontent.com/49380831/132296626-f27473a6-f408-4256-aa6d-25061f18bcf2.png)

**Comment by MittWillson** [comment]
@jenting Yes I did, and then the snapshot became a system hide, you can check that screenshot, the status Removed is True, but even detach and reboot, that snapshot always exists, and new data writing to Volume Head

**Comment by shuo-wu** [comment]
The snapshot directly behind the volume head cannot be purged. But it can be removed once there is a newer snapshot.

**Comment by MittWillson** [comment]
@shuo-wu Can we just get the data without any snapshots, it is useless for me and keeps growing and takes the double space

**Comment by shuo-wu** [comment]
It's hard to avoid snapshotting now. Even if users won't create snapshots via UI or recurring jobs, Longhorn needs to create system snapshots when rebuilding or volume expansion is triggered.

BTW, if a snapshot takes extra space depends on how much historical data it stores. By periodically cleaning up the snapshot (via recurring jobs), you can avoid the system being overwhelmed by snapshots. But there is no guarantee that volume actual size won't exceed the spec size. Here is an example that would help understand the data format of a Longhorn volume: https://longhorn.io/docs/1.2.0/volumes-and-nodes/volume-size/#an-example-that-helps-understand-volume-size-and-volume-actual-size

**Comment by MittWillson** [comment]
@shuo-wu Thanks for your reply, it's so hard to accept it, I have been using it for instead of local-path-provider, but the snapshot is kind of annoying

**Comment by shuo-wu** [comment]
Yes. The space usage management here is not perfect. We will see if we can improve it but this issue maybe not in the top priority now.
