### ISSUE TITLE
Manager: Add replica eviction support for node and disk

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#298]
https://github.com/rancher/longhorn/issues/292

Overview:
Eviction mode would give users the ability to work on scheduled maintenance without impact the volumes.

Pre-requirement:
1. The eviction can only be called if the scheduling was disabled.
2. During the eviction process, the scheduling cannot be re-enabled.

Description:
The eviction would result in all the replicas on the node or disk being moved to other nodes/disks.

Design:
1. If the volume is not in the healthy state, the detection of evicting would be skipped.
2. The volume of the replica which being moved will temporarily increase replica count by one. The rebuilding process should be triggered then, and the new replica will be automatically scheduled to another suitable place.
2.1. There can be multiple volumes in the replica moving process at the same time, but only one replica for each volume can be moved at any given time, even there are multiple disk/nodes are being evicted.
3. If there is no space on other nodes/disks to fit the new replica, the volume will report `unable to schedule` error, but keep functioning. The user can choose to stop evicting for the nodes/disks at this point or clean up more spaces for the replicas.
4. If the user chooses to stop evicting when one volume is `unable to schedule`, the evicting for that volume would be canceled, and the replica would remain at the disk, and the replica count for the volume would be automatically restored back to the original setting.
5. If the new replica has been successfully rebuilt, the volume would have `replica count + 1` healthy replicas. After the new replica has been confirmed by Longhorn engine, the controller would restore the replica count to the original setting, then destroy the replica on the node/disk that being evicted. The controller will make sure that at any given time, the healthy replica counts won't be below the original replica count.
7. After one replica has been successfully moved, the controller would repeat this process for the other replicas of the volume. Until there is no replica needs to be moved.

Additional requirement:
Make sure to cover the case of disk replacement/node replacement.

**Comment by boknowswiki** [comment]
I think we need @smallteeths to help adding buttons for `Eviction` and `Cancel Eviction` for disks and nodes from UI.

**Comment by yasker** [comment]
This issue has been in Review for 13 days. What's blocking this issue moving to Merged?

**Comment by boknowswiki** [comment]
> This issue has been in Review for 13 days. What's blocking this issue moving to Merged?

I think it's because of [this part](https://github.com/longhorn/longhorn-manager/pull/651#discussion_r474952588). I will sync with @shuo-wu about it later today.

**Comment by boknowswiki** [comment]
@smallteeths , could you help to update the UI part, which adding 'Eviction Requested' 'true' or 'false' options next to the 'Scheduling' on the 'Node' page? Thanks.

**Comment by boknowswiki** [comment]
From the UI, we just found it doesn't return the error message to the UI. I will move this to implement to fix this part.

**Comment by khushboo-rancher** [comment]
With the fix available on Longhorn master, the scenario from https://github.com/longhorn/longhorn/issues/1400 doesn't get address if the setting ```Soft anti-affinity``` is disabled. (Which is disabled by default).

**Comment by khushboo-rancher** [comment]
Verified on Longhorn Master - 09/8/2020

Validation - **Pass**

Test cases executed from https://rancher.atlassian.net/wiki/spaces/LON/pages/721092760/Replica+eviction+from+node+and+disk

**Comment by khushboo-rancher** [comment]
The tests `test_node_eviction`, `test_node_eviction_multiple_volume`, `test_node_eviction_no_schedulable_node`, `test_node_eviction_soft_anti_affinity` have been passing since more than 5 nightly test run.
