### ISSUE TITLE
[BUG] Volume does not attach to pod "rpc error: code = Internal desc = format of disk"

### ISSUE THREAD

**Issue by Timeraa** [longhorn/longhorn#2983]
**Describe the bug**

**To Reproduce**
1. Create a volume
2. Create a PVC
3. Create a pod with the volume

**Expected behavior**
Successfully attaching the volume and running the pod

**Log**
Log of the pod that has the volume attached
![image](https://user-images.githubusercontent.com/29104008/132198789-a63c2ece-fc62-4fbf-aa8b-59cfd39b8c35.png)

**Environment:**
 - Longhorn version: 1.20
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE 21.04
   - Number of management node in the cluster: 2
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 4 - 10
   - Memory per node: 8GB - 64GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 2,5 Gbit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 1 test volume, fresh installation

**Additional context**
I have been using longhorn since a few months now and never had any issues but after I was doing some node maintenance including completely wiping longhorn and then reinstalling it I've been having issues that once I want to use a pod with a volume attached to it it never binds the volume.

**Comment by shuo-wu** [comment]
Does the system or some applications do anything for this newly attached (Longhorn) block device? e.g., creating partitions.
The symptom here is similar to https://serverfault.com/questions/935116/getting-dev-sdb-is-apparently-in-use-by-the-system-after-adding-an-independen

**Comment by obeyler** [comment]
I think I've got the same pb  after update to 1.2.0
I update longhorn from 1.1.0 to 1.2.0 everything seems good but
when I try to delete openldap  ns who contained a PVC a recreate it
The PVC is well created, the PV seems ok too but when the pod try to use it :

MountVolume.MountDevice failed for volume "pvc-13e03f5a-7e85-4247-934a-e49448a1f0c7" : rpc error: code = Internal desc = format of disk "/dev/longhorn/pvc-13e03f5a-7e85-4247-934a-e49448a1f0c7" failed: type:("ext4") target:("/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-13e03f5a-7e85-4247-934a-e49448a1f0c7/globalmount") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.45.5 (07-Jan-2020) /dev/longhorn/pvc-13e03f5a-7e85-4247-934a-e49448a1f0c7 is apparently in use by the system; will not make a filesystem here! )

**Comment by joshimoo** [comment]
Strange haven't encountered that error before, might also be the target service as mentioned here: https://serverfault.com/a/934774

**Comment by PhanLe1010** [comment]
Related slack discussion https://cloud-native.slack.com/archives/CNVPEL9U3/p1631104997044800

**Comment by PhanLe1010** [comment]
> /dev/longhorn/pvc-13e03f5a-7e85-4247-934a-e49448a1f0c7 is apparently in use by the system;

Looks like something is hijacking the Longhorn block device. Can you try these steps to find out who is using the block device? https://github.com/longhorn/longhorn/issues/1210#issuecomment-671591451

Also, have you recently upgrade the OS on nodes?

**Comment by Timeraa** [comment]
> > /dev/longhorn/pvc-13e03f5a-7e85-4247-934a-e49448a1f0c7 is apparently in use by the system;
> 
> @obeyler @Timeraa Looks like something is hijacking the Longhorn block device. Can you try these steps to find out who is using the block device? [#1210 (comment)](https://github.com/longhorn/longhorn/issues/1210#issuecomment-671591451)
> 
> Also, have you recently upgrade the OS on nodes?

I followed the most liked comment on the issue you mentioned, that seemed to help and yes it seems like it was hijacked because it was still being used.

And no I haven't upgraded the OS on any node, only security updates at most.

**Comment by PhanLe1010** [comment]
Do you mean this comment https://github.com/longhorn/longhorn/issues/1210#issuecomment-671689746? 

If so, This is the multipath problem

**Comment by Timeraa** [comment]
I first tried the comment above which didn't work but the the one you commented worked out in the end. I suppose this issue can be closed now?

**Comment by PhanLe1010** [comment]
Sure. We have identified the root cause. So it is good to close

**Comment by Timeraa** [comment]
Yep. Thanks for the help! 🍻🎉
