### ISSUE TITLE
[TASK] Performance and scalability report for Longhorn

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2986]
**What's the task? Please describe.**
Need to update the performance and scalability report.

**Describe the items of the task (DoD, definition of done) you'd like.**
- [ ] Performance of raw block device
- [ ] Performance of fs on top of raw block devices (ext4 and xfs)
- [ ] Performance of encrypted volume (might depends on the fs)
- [ ] Performance of RWX
- [ ] Scalability report.

**Additional context**
1. For performance, we can use https://github.com/yasker/kbench 
2. For OS, let's stick with RKE2 + openSUSE.

**Comment by mstrent** [comment]
A bonus might be to benchmark with and without the revision counter enabled as well.

https://longhorn.io/docs/1.2.0/advanced-resources/deploy/revision_counter/

**Comment by PhanLe1010** [comment]
### Update (in-progress)

### Native

#### 1. Raw block device
```
=====================
FIO Benchmark Summary
For: /root/fio-results/native/raw-block-v2
SIZE: 50g
QUICK MODE: DISABLED
=====================
IOPS (Read/Write)
        Random:          80,060 / 37,036
    Sequential:          80,063 / 37,065
  CPU Idleness:                      87%

Bandwidth in KiB/sec (Read/Write)
        Random:        362,551 / 167,116
    Sequential:        362,548 / 167,084
  CPU Idleness:                      96%

Latency in ns (Read/Write)
        Random:         54,049 / 107,172
    Sequential:         93,820 / 107,398
  CPU Idleness:                      89%
```

#### 1. ext4

#### 1. xfs

**Comment by PhanLe1010** [comment]
### Scalability tests (in-progress)

**Comment by PhanLe1010** [comment]
### Scalability tests (in-progress)

### Test evn:
```
* Kubernetes: RKE1 v1.18.20; 3 master nodes; 100 worker nodes
* Longhorn: v1.2.0

* OS: Ubuntu 18.04
* EC2 `m5.2xlarge` instance: 8 vCPUs 32 GB Memory
```

#### Longhorn installation time
<img width="886" alt="Screen Shot 2021-09-28 at 6 37 27 PM" src="https://user-images.githubusercontent.com/22139961/135188361-a9a56de0-1a44-497a-a7ee-28f09eae2bf9.png">
 
#### Workloads with Longhorn volumes deploying time
pending

**Comment by innobead** [comment]
We will move this to the next patch 1.2.4 instead until figuring out the scaling test results.

**Comment by PhanLe1010** [comment]
This ticket is handled at https://github.com/longhorn/longhorn/issues/2598
