### ISSUE TITLE
[BUG] Tool tip on Snapshots and Backups List on UI are displayed inconsistently

### ISSUE THREAD

**Issue by mfbrj** [longhorn/longhorn#2994]
**Describe the bug**
Tool tip on Snapshots and Backups List on UI are displayed inconsistently. The tooltip on  Snapshots and Backups List seems to be at local timezone, in AM/PM format. See screenshots below.

**To Reproduce**
1. Create a backup or snapshot on a volume.
2. Verify the tool tip on a backup or snapshot and compare them like the screeenshots below.

**Expected behavior**
The same timestamp on both tooltips.

**Environment:**
 - Longhorn version:  1.2.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE v1.20.9
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 8
 - Node config
   - OS type and version: Ubuntu 20.04.3 LTS   kernel 5.4.0-84-generic
   - CPU per node: 4
   - Memory per node: 16 GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 23

**Additional context**
Right display:
![image](https://user-images.githubusercontent.com/835834/132932603-6145cb89-fb23-447c-90da-9a4f2613386a.png)

Wrong display:
![image](https://user-images.githubusercontent.com/835834/132932631-1859ffb6-d13a-499f-8f61-6151a5cd71f3.png)

**Comment by jenting** [comment]
cc @smallteeths

**Comment by PhanLe1010** [comment]
@smallteeths Do you know if the snapshot chain graph and the table of the snapshots are getting data from the same source? We are wondering if this problem is because of UI parsing the timestamp differently or if we need to fix it from the backend.

**Comment by mfbrj** [comment]
@PhanLe1010 I think this is not about the source. It's about the timezone in display.

As I said on the issue description, the 2 timestamps pointed by the arrows are the same, but in different timezones.

The first one is at **UTC** 2021-09-11T01:00:08Z and the second is at **browser local time GMT-3**, but in AM/PM 12h format, since it's displayed as 2021-09-10T**10**:00:08. In 24h display, the second timestamp should be displayed as 2021-09-10T**22**:00:08, the right moment that snapshot was done at local time.

Why not display everything in UTC?

**Comment by PhanLe1010** [comment]
@mfbrj Thank you for the analysis! Yeah, I agree that we should display everything in UTC.

Honestly, I am not familiar with UI code. Our UI developer, @smallteeths,  will look into it.

**Comment by smallteeths** [comment]
The Snapshots icon shows the data returned directly from the backend. The times in the table are displayed in the tooltip using the `new Date()` method. `new Date()` converts the UTC time to local time. When I did this, I was only thinking about converting the UTC time to local time, but not about displaying the time in a consistent format. This seems to have caused confusion. Should we convert all the displayed times to UTC format. Instead of changing the time to local time.
@PhanLe1010

**Comment by jenting** [comment]
I think all items displayed in UTC format are better and consistent.

cc @innobead

**Comment by innobead** [comment]
@smallteeths Let's just use UTC time, this can make the display consistent and good for the following troubleshooting.

**Comment by jenting** [comment]
One more thing, I found that the tooltip on `Backup` page did not use UTC time also.

**Comment by mfbrj** [comment]
> One more thing, I found that the tooltip on `Backup` page did not use UTC time also.

@jenting yes, I forgot to mention that when I opened the issue. Pehaps all tooltips on other places have the same issue, if all use the same `new Date()` method, as @smallteeths explained.

**Comment by chanow816** [comment]
Validation: **Failed**

In v1.2.1-rc1, only tooltip in Snapshots and Backups use UTC time, others are still using local time

---
**Environment:**

- Longhorn version: 1.2.1-rc1
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE v1.21.5
- Number of management node in the cluster: 1
- Number of worker node in the cluster: 3

**Steps:**

- Create volume
- Attach volume to pod
- Take backup and snapshot on volume and observe tooltip display time

**Expected result:**

- All time format in tooltip should use UTC format

False result
<img width="1522" alt="Screen Shot 2021-09-23 at 11 11 26 AM" src="https://user-images.githubusercontent.com/73337386/134450253-1ec73bc4-7b95-43f0-b020-0b568e9369ef.png">

Correct result
<img width="1524" alt="Screen Shot 2021-09-23 at 11 13 18 AM" src="https://user-images.githubusercontent.com/73337386/134450273-df28d016-5996-42f8-9f41-ce82b9f5dc78.png">

cc @innobead

**Comment by innobead** [comment]
> Validation: **Failed**
> 
> In v1.2.1-rc1, only tooltip in Snapshots and Backups use UTC time, others are still using local time
> 
> **Environment:**
> 
> * Longhorn version: 1.2.1-rc1
> * Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
> * Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE v1.21.5
> * Number of management node in the cluster: 1
> * Number of worker node in the cluster: 3
> 
> **Steps:**
> 
> * Create volume
> * Attach volume to pod
> * Take backup and snapshot on volume and observe tooltip display time
> 
> **Expected result:**
> 
> * All time format in tooltip should use UTC format
> 
> False result
> <img alt="Screen Shot 2021-09-23 at 11 11 26 AM" width="1522" src="https://user-images.githubusercontent.com/73337386/134450253-1ec73bc4-7b95-43f0-b020-0b568e9369ef.png">
> 
> Correct result
> <img alt="Screen Shot 2021-09-23 at 11 13 18 AM" width="1524" src="https://user-images.githubusercontent.com/73337386/134450273-df28d016-5996-42f8-9f41-ce82b9f5dc78.png">
> 
> cc @innobead

The fix is fixed after 1.2.1-rc1, so please check master-head and 1.2.x build instead.

**Comment by chanow816** [comment]
**Validation: Passed**

In v1.2.x, tooltips use UTC time correctly

---

**Environment:**

- Longhorn version: 1.2.x
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE v1.21.5
- Number of management node in the cluster: 1
- Number of worker node in the cluster: 3

**Steps:**

- Create volume
- Attach volume to pod
- Take backup and snapshot on volume and observe tooltip display time

**Expected result:**

- All time format in tooltip should use UTC format

**Actual result:**

- All tooltips use UTC time format

<img width="1536" alt="Screen Shot 2021-09-23 at 1 02 41 PM" src="https://user-images.githubusercontent.com/73337386/134457118-b47fd5dc-b4e8-4cf9-b450-49b75f42a321.png">


cc @innobead
