### ISSUE TITLE
[BUG] Disk eviction not doing anything

### ISSUE THREAD

**Issue by vinid223** [longhorn/longhorn#2995]
**Describe the bug**
I added disks to a cluster to each of my nodes to replace the existing disks as the main storage.

For each node, I went into the disk settings and disabled the scheduling for the old disks and enabled eviction. The new disks are activated for scheduling.

It's been hours and not a single replicat have been moved. I can't see any logs in the longhorn ui. The disks works when I force delete a replicat and it rebuilt fine in the other disks.

**To Reproduce**
1. Add disk to node
2. Setup disk in longhorn with scheduled enable
3. Setup old disk in longhorn to disable scheduling and enable eviction
4. Wait and watch for nothing happening

**Expected behavior**
Replicat are being moved. If not, show logs or information in the volume page info or node info or main page.

**Log**
If needed, I can generate a support bundle

**Environment:**
 - Longhorn version: 1.1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s 1.21.4
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster:3 (the management node is also a worker, so 4 nodes)
 - Node config
   - OS type and version: Raspbian 10 (Buster)
   - CPU per node: 4
   - Memory per node: 8gb
   - Disk type(e.g. SSD/NVMe): SD Card for main OS, external USB HDD 1TB (node 2, 3 and 4)
   - Network bandwidth between the nodes: 1GB
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):Baremetal
 - Number of Longhorn volumes in the cluster: 11

**Additional context**
N/A

**Comment by vinid223** [comment]
I tried something different this morning, I disabled scheduling on a node and enable eviction request and the node started to remove the replicas.

I could do my migration that way, but it would be nice to have the feature on disk to work

**Comment by shuo-wu** [comment]
Workaround:
1. Manually Scale up the replica count for all volumes that contain replicas in the evicting disk
2. Wait for the rebuilding finish.
3. Re-scale down the replica count for those volumes
4. Delete the replicas using the evicting disks

**Comment by shuo-wu** [comment]
After the fix, the nightly tests should pass. And the case mentioned in the reproducing step should work as expected.

**Comment by kaxing** [comment]
Validation: **PASSED**

Tested with v1.2.1-rc1 and master-head (20210924-3pm) on local k3s cluster.
I can see the volume replicas begin removing when the node/disk `Eviction Requested` set to True.
![Longhorn-v1 2 1-rc1-Node-Eviction webm](https://user-images.githubusercontent.com/602540/134696254-5bf30fb7-abe1-41ef-82a0-97e6d9825b16.gif)

**Comment by vinid223** [comment]
> Validation: **PASSED**
> 
> Tested with v1.2.1-rc1 and master-head (20210924-3pm) on local k3s cluster.
> I can see the volume replicas begin removing when the node/disk `Eviction Requested` set to True.
> ![Longhorn-v1 2 1-rc1-Node-Eviction webm](https://user-images.githubusercontent.com/602540/134696254-5bf30fb7-abe1-41ef-82a0-97e6d9825b16.gif)

The issue I had was not on the eviction of node, but on the disk only of a node while having an other schedulable disk on the node

**Comment by kaxing** [comment]
Hey @vinid223 thanks for commenting back to my test result!

I've setup a new test environment and retest it with v1.2.1.-rc2, result as following gif:
![longhorn-v1 2 1-rc2-node-disks-eviction webm](https://user-images.githubusercontent.com/602540/134852842-a8feba9a-da3a-48bd-968a-4c11e640e613.gif)

Steps:
1. Create a cluster on EC2
2. Install and configure the Longhorn
3. Create and mount the 2 new disks, one slower gp2 and one faster gp3, for the worker node instance that is going to swap the disk
4. Setup new disks in Longhorn Node management UI
5. Set `Scheduling: Fals` and `Eviction Requested: True` to the disk want to be retired

The replicas will start migrating themselves to the disk that is available for use. To narrow down the issue, I have also turn off other two nodes in this cluster, so only one node is running in this test.

**Comment by vinid223** [comment]
@kaxing This looks good to me. Thank you.

**Comment by shuo-wu** [comment]
@vinid223 BTW, we do found a corner case https://github.com/longhorn/longhorn/issues/3076 but it's not related to the eviction bug. The case gonna be tracked in that new ticket.
