### ISSUE TITLE
[BUG] Recurring jobs showing incorrectly

### ISSUE THREAD

**Issue by corbosman** [longhorn/longhorn#2996]
**Describe the bug**

I installed Longhorn 1.2.0 and created some volumes. I can make backups of these volumes using NFS just fine. If I set up a recurring job the icon keeps telling me there are no recurring jobs. The job does actually run.

**To Reproduce**

1. Go to UI, select volumes
2. Click on Schedule icon and create a schedule
3. Schedule seems to work but the icon does not change.

**Expected behavior**

I expect the icon to change and the schedule to be set.

**Log**
```
192.168.6.22 - - [11/Sep/2021:14:13:37 +0000] "POST /v1/volumes/redis?action=recurringJobList HTTP/1.1" 200 447 "http://192.168.6.200/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0"
```

**Environment:**
 - Longhorn version: 1.2.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: kubeadm, 1.22
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: Ubuntu 20.04.3
   - CPU per node: 4
   - Memory per node: 8gb
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 1gbit/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox/KVM
 - Number of Longhorn volumes in the cluster: 5

**Additional context**

I upgraded Kubernetes from 1.21 to 1.22, and ran into problems with Longhorn to the point where I decided to just wipe longhorn (helm uninstall, delete namespace), and reinstall the latest version 1.2.0.  (was 1.1.2). 

Got everything back up and running through backups and now I cant visually configure recurring jobs. 

```
NAME                                           READY   STATUS      RESTARTS        AGE
pod/backups-27189520--1-4drcn                  0/1     Completed   0               3m45s
pod/csi-attacher-75588bff58-bvgtk              1/1     Running     0               3h53m
pod/csi-attacher-75588bff58-dnqcf              1/1     Running     0               3h53m
pod/csi-attacher-75588bff58-tn6zl              1/1     Running     0               3h53m
pod/csi-provisioner-6968cf94f9-h4qrc           1/1     Running     0               3h53m
pod/csi-provisioner-6968cf94f9-sxnws           1/1     Running     0               3h53m
pod/csi-provisioner-6968cf94f9-tqlfv           1/1     Running     0               3h53m
pod/csi-resizer-5c88bfd4cf-dtc29               1/1     Running     0               3h53m
pod/csi-resizer-5c88bfd4cf-gj9hs               1/1     Running     0               3h53m
pod/csi-resizer-5c88bfd4cf-knmsg               1/1     Running     0               3h53m
pod/csi-snapshotter-69f8bc8dcf-gzq5g           1/1     Running     0               3h53m
pod/csi-snapshotter-69f8bc8dcf-kj6db           1/1     Running     0               3h53m
pod/csi-snapshotter-69f8bc8dcf-lsghw           1/1     Running     0               3h53m
pod/engine-image-ei-0f7c4304-865dp             1/1     Running     0               3h53m
pod/engine-image-ei-0f7c4304-z2r2d             1/1     Running     0               3h53m
pod/instance-manager-e-43e30e4f                1/1     Running     0               3h53m
pod/instance-manager-e-fc2e9658                1/1     Running     0               3h53m
pod/instance-manager-r-1873890c                1/1     Running     0               3h32m
pod/instance-manager-r-4e86c1d2                1/1     Running     0               3h32m
pod/longhorn-csi-plugin-cklsr                  2/2     Running     0               3h53m
pod/longhorn-csi-plugin-w24jm                  2/2     Running     0               3h53m
pod/longhorn-driver-deployer-5f47f8c9c-g8dcx   1/1     Running     0               3h53m
pod/longhorn-manager-h9dpp                     1/1     Running     1 (3h53m ago)   3h53m
pod/longhorn-manager-xzlzt                     1/1     Running     0               3h53m
pod/longhorn-ui-7545689d69-n28kb               1/1     Running     0               3h53m

NAME                        TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)        AGE
service/csi-attacher        ClusterIP      10.101.22.92     <none>          12345/TCP      3h53m
service/csi-provisioner     ClusterIP      10.97.13.34      <none>          12345/TCP      3h53m
service/csi-resizer         ClusterIP      10.103.158.227   <none>          12345/TCP      3h53m
service/csi-snapshotter     ClusterIP      10.111.106.187   <none>          12345/TCP      3h53m
service/longhorn-backend    ClusterIP      10.103.129.47    <none>          9500/TCP       3h53m
service/longhorn-frontend   LoadBalancer   10.104.251.76    192.168.6.200   80:31147/TCP   3h53m

NAME                                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/engine-image-ei-0f7c4304   2         2         2       2            2           <none>          3h53m
daemonset.apps/longhorn-csi-plugin        2         2         2       2            2           <none>          3h53m
daemonset.apps/longhorn-manager           2         2         2       2            2           <none>          3h53m

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/csi-attacher               3/3     3            3           3h53m
deployment.apps/csi-provisioner            3/3     3            3           3h53m
deployment.apps/csi-resizer                3/3     3            3           3h53m
deployment.apps/csi-snapshotter            3/3     3            3           3h53m
deployment.apps/longhorn-driver-deployer   1/1     1            1           3h53m
deployment.apps/longhorn-ui                1/1     1            1           3h53m

NAME                                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/csi-attacher-75588bff58              3         3         3       3h53m
replicaset.apps/csi-provisioner-6968cf94f9           3         3         3       3h53m
replicaset.apps/csi-resizer-5c88bfd4cf               3         3         3       3h53m
replicaset.apps/csi-snapshotter-69f8bc8dcf           3         3         3       3h53m
replicaset.apps/longhorn-driver-deployer-5f47f8c9c   1         1         1       3h53m
replicaset.apps/longhorn-ui-7545689d69               1         1         1       3h53m

NAME                    SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
cronjob.batch/backups   */5 * * * *   False     0        3m45s           38m

NAME                         COMPLETIONS   DURATION   AGE
job.batch/backups-27189520   1/1           27s        3m45s
```

The image below shows no schedule set, even though the backup job ran recently. 

![Screenshot 2021-09-11 at 16 41 37](https://user-images.githubusercontent.com/1389007/132951607-49ed98d2-c856-4031-9a4d-4a5a3bea71bf.png)

**Comment by corbosman** [comment]
I had a quick look in the javascript debugger and noticed this from longhorn-ui:

```js
    {
      title: 'Schedule',
      key: 'recurringJobs',
      width: 100,
      render: (text, record) => {
        let title = text.recurringJobs && text.recurringJobs.length ? 'Only recurring snapshot scheduled' : 'No recurring backup scheduled'
        let fill = text.recurringJobs && text.recurringJobs.length ? 'rgb(241, 196, 15)' : 'rgba(0, 0, 0, 0.25)'
        if (text.recurringJobs && text.recurringJobs.length) {
          text.recurringJobs.forEach((ele) => {
            if (ele.task === 'backup') {
              fill = '#00C1DE'
              title = 'Recurring backup scheduled'
            }
          })
        }
        return (
          <Tooltip placement="top" title={title}>
            <div onClick={() => { showRecurringJobModal(record) }} style={{ width: '100%', cursor: 'pointer' }}>
              <IconBackup fill={fill} width={30} height={30} />
            </div>
          </Tooltip>
        )
      },
    },
```

The text object passed never contains a recurringJobs array. This is probably related to the new recurringJobSelector instead of recurringJobs.  

I am running v1.2.0 longhorn-ui

```
deployment.apps/longhorn-ui                1/1     1            1           7h42m   longhorn-ui                longhornio/longhorn-ui:v1.2.0                   app=longhorn-ui

```

**Comment by smallteeths** [comment]
This pr also fixes a bug that caused errors in loading Recurring Jobs requests when a volume error occurred.
1. create volume a1 and attach to host ip-172-31-7-169
2. Shut down node ip-172-31-7-169
3. The status of the volume should be Faulted (check its data as shown in the figure)
![Jietu20210915-175646](https://user-images.githubusercontent.com/27733391/133412996-48211685-0408-4550-8e36-167f62e19613.jpg)
<img width="418" alt="截屏2021-09-15 下午5 42 18" src="https://user-images.githubusercontent.com/27733391/133413032-761f904c-5faf-478e-b57c-e0e3d61a4de3.png">
4. The current actions of the volume do not have the recurringJobList connection requested. The ui page will pop up with an error message.

This pr changed the logic to disable List/add recurringjob related oprions when a volume error occurs.

**Comment by kaxing** [comment]
Validating in progress, testing with v1.2.x branch.

Here is the walkthrough with latest fix:

On v1.1.2, volume with recurring jobs will display in Goldfinger(closer to #ecb911) color,
![image](https://user-images.githubusercontent.com/602540/134316523-92c480d2-ed7a-4552-96a4-38237447a174.png)

With v1.2.0, all displayed in grey and the tooltips are not reflecting the correct status,
![image](https://user-images.githubusercontent.com/602540/134316561-a9584e14-c723-45f3-9b9b-21da3e4bb3fb.png)

The same cluster upgrading to v1.2.1-rc1, the recurring job icon will all be in Goldefinger color and no tooltips, and act as a shortcut to open the RecurringJobs popup dailog,
![image](https://user-images.githubusercontent.com/602540/134318263-4bd29899-f2b2-4f5a-b582-bdf8503e8313.png)
<Details> 

<Summary> the popup screenshot for reference </Summary>

![image](https://user-images.githubusercontent.com/602540/134318599-3f51d984-2c6f-4537-a9b0-f5f59022ecc0.png)

</Details>


For the extended node down displaying problem, it will be displayed as detached and with a tooltips hinting the node is down regardless with or without recurringjobs, also there is no problem to manage existed or add new jobs,
![image](https://user-images.githubusercontent.com/602540/134319041-66314fa7-9bf6-419b-a02d-0ece8b776299.png)

Further discussion on how can we improve will be tracking in this issue: #3051

**Comment by kaxing** [comment]
Validation: **PASSED** 

Both in v1.2.1-rc1 and master branch(20210923 ~3PM) the Schedule Icons are working as a shortcut to open the new `Recurring Jobs Schedule` dialog.

And cc @corbosman I will close this issue for now as it is a feature change in v1.2.0 and leave the discussion for improvement in issue 3051.
