### ISSUE TITLE
[BUG] Volume UI displays only the last backup when using the recurring job

### ISSUE THREAD

**Issue by mfbrj** [longhorn/longhorn#2997]
**Describe the bug**
Volume UI is displaying only the last backup

**To Reproduce**
1. Create a backup recurring job with retain >= 2, and a group
2. Associate this recurring job group to some volume
3. Wait for 2 or 3 backups be performed
4. See that volume UI displays only the last backup. Screenshots below.

**Expected behavior**
Volume UI displays 2 or more backups, within retain range.

**Log**

**Environment:**
 - Longhorn version:  1.2.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE v1.20.9
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 8
 - Node config
   - OS type and version: Ubuntu 20.04.3 LTS   kernel 5.4.0-84-generic
   - CPU per node: 4
   - Memory per node: 16 GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 23

**Additional context**
Wrong behaviour:
![image](https://user-images.githubusercontent.com/835834/133016894-b9005c4b-910f-44e1-8d2a-23e6a29658c0.png)

Wrong behaviour:
![image](https://user-images.githubusercontent.com/835834/133017271-0bab5436-c258-4fd0-9b86-c9f86261d3d7.png)

Right behaviour:
![image](https://user-images.githubusercontent.com/835834/133017487-292d7b78-4052-4d0b-b0fb-edf4e6f41938.png)

**Comment by PhanLe1010** [comment]
@smallteeths Do you know if the snapshot chain graph and the table of the snapshot are getting data from the same source? We are wondering if this problem is because of UI parsing the timestamp differently or if we need to fix from backend.

**Comment by mfbrj** [comment]
@PhanLe1010 as far I can tell, there is only one source, because I have only one minio backup server configured on Longhorn settings.

**Comment by PhanLe1010** [comment]
Thanks @mfbrj ! Sorry! My bad! the above comment was supposed for this issue https://github.com/longhorn/longhorn/issues/2994 😂

For this issue, we will try to see if we can reproduce it in lab first

**Comment by mfbrj** [comment]
@PhanLe1010 ok. I was suspicious that it was about the other issue, because of mention of the timestamp.

**Comment by shuo-wu** [comment]
For each recurring backup job, Longhorn will retain the last snapshot created by this job after each backup creation is complete:
https://github.com/longhorn/longhorn-manager/blob/e4be7bebf46ce43e06e3d5ca882f6fda21588afd/app/recurring_job.go#L535-L543

This may work as expected. @PhanLe1010 Can you double-check this feature?

**Comment by mfbrj** [comment]
@shuo-wu 
Why not to get the backup info from the same source of Backup tab? In the Backup tab, the info is consistent and correct.

**Comment by PhanLe1010** [comment]
Thanks @shuo-wu. I just tried the provided reproducing steps and look at the code. Yeah, this is working as expected. 
@mfbrj The snapshot chain in the volume details page show all existing snapshots of a volume (not all existing backups). If a snapshot has corresponding backup, the color of the snapshot changed to green. Users need to head to backup tap to see all existing backups.

**Comment by mfbrj** [comment]
Ok @PhanLe1010 but why the chain displays only the last backup, even if there are other snapshots with corresponding backup?

The chain should display all valid snapshots that have backups, to make easy the restore process in maintenance mode from UI.

**Comment by jenting** [comment]
Okay, after discuss internally, we should improve this to make the Snapshots and Backups list chain inside the Volume page consistent with the Backup page.

**Comment by jenting** [comment]
We'll fix it on the backend side.

**Comment by kaxing** [comment]
Validating in progress,
testing with 1.2.x-head images,

No problem when the snapshot is taking after a backup,
![image](https://user-images.githubusercontent.com/602540/144568737-294d336c-f5ba-4b0a-a5aa-3125bfdb234e.png)

**Comment by kaxing** [comment]
Validation - **Passed**

Verified with master-head images.

Behavior expectations:
- Backup creating from Volume page will be shown in the S/B(Snapshot and Backup) chain.
- Backup deleted in backup page will be removed from the S/B chain
- Snapshot taking in volume detail page will be display correctly.


Example of a volume with 4 backups:
- The S/B chain:
  - ![image](https://user-images.githubusercontent.com/602540/144572297-cd6766f0-1566-47ee-b766-9e0232455992.png)
- The S/B list:
  - ![image](https://user-images.githubusercontent.com/602540/144572489-d3ad1585-3cb6-4dd0-a636-d6429d7d986d.png)
- The backup volume page:
  - ![image](https://user-images.githubusercontent.com/602540/144572323-82d5a860-fd3a-47e4-b9af-a6c8442e7203.png)

**Comment by mfbrj** [comment]
@kaxing Did you also test the backups done by Recurring Jobs?

**Comment by kaxing** [comment]
Hey @mfbrj thanks for the reminder. I did a quick test and the full list of backup items didn't show up in the list.
Only the first and the last backup from the RecurringJobs were being display in the S/B list and the chain inside the volume detail page.

**Comment by kaxing** [comment]
Sorting out items and actions that can display in Snapshot and Backup chain:
- snapshot by button
- snapshot by recurring job → display as expected
- backup by button(in-volume)
- backup by button(volume ui)
- backup by recurring job ← Will not be consistent with Backup page or Backup CR

@jenting I am discussing with @smallteeths but so far there isn't a concrete direction yet, but by using recurringjobs for backup action with less than 5mins you can easily reproduce this.

cc @PhanLe1010 @shuo-wu

**Comment by smallteeths** [comment]
Looking at the data returned by the `/v1/volumes/empty1?action=snapshotList` from the backend, it does appear that the backup data is missing compared to `v1/backupvolumes/empty1?action=backupList`. I'm not sure what caused it. @jenting

<img width="945" alt="截屏2021-12-06 下午2 50 04" src="https://user-images.githubusercontent.com/27733391/144804558-26b429cc-2c59-451f-9cf8-da0d4ce589e8.png">

**Comment by jenting** [comment]
Not sure which endpoint UI used to display the Snapshot and Backup chain.
The
- `/v1/volumes/empty1?action=snapshotList` is for snapshot list
- `/v1/backupvolumes/empty1?action=backupList` is for backup list

**Comment by jenting** [comment]
@kaxing I think it's the expected behaviour according to Shou's comment https://github.com/longhorn/longhorn/issues/2997#issuecomment-922623824

I'm thinking how to make the user experience more better cc @PhanLe1010

**Comment by jenting** [comment]
I think we need to revisit the original issue #2231 that we should not remove the snapshot after the backup succeeded automatically, and consider adding a new setting on the recurring job that allows the user to set up delete snapshot after the backup succeeded.

After that, the snapshots created by the recurring job will all show in the snapshots and backups. This makes the UX better from my point of view.

**Comment by jenting** [comment]
Moving back to backlog since the PR does not fix this issue.

**Comment by kaxing** [comment]
Hey @mfbrj just give you an update from my discussion with devs, that the current behavior of Recurring Backup Jobs as mentioned a few times in the thread above, it will only keep last snapshot, therefore only last backup managed by the Recurring Jobs will be display in the S/B chain. The current change fixes the other issue you reported, I will check again on that one.

**Comment by innobead** [comment]
Can base on this suggestion, https://github.com/longhorn/longhorn/issues/2997#issuecomment-987716072 has a setting to allow users to enable/disable snapshot auto-deletion after recurring backup job and it will be enabled by default for backward compatibility.

**Comment by mantissahz** [comment]
just created it, https://github.com/longhorn/longhorn-manager/pull/1965

**Comment by innobead** [comment]
This has a new setting introduced and no immediate need to fix it in the maintained release branches, so decided to not backport this to 1.5.x and 1.4.x.

**Comment by roger-ryao** [comment]
**Verified on master-head 20231213**

- longhorn master-head https://github.com/longhorn/longhorn/commit/97e8c77229a77e19a1f832017d3b2c4006610224
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/27101bb1ad4c287d2957003b51189da6ffa74cff

**The test steps**

https://github.com/longhorn/longhorn/issues/2997#issuecomment-1582134564

1. Install Longhorn.
2. Disable the setting `auto-cleanup-recurring-job-backup-snapshot`.
![Screenshot_20231213_141401](https://github.com/longhorn/longhorn/assets/104337648/0564ceef-809b-49e4-9771-aa8911dc403d)


3. Create a volume with a recurring backup job that contains `3 retain` backups.
4. After the recurring job is completed, there are 3 snapshots for the `3 retain` backups, which can be obtained using the commands: `kubectl -n longhorn-system get backup` and `kubectl -n longhorn-system get snapshot`.
5. Enable the setting `auto-cleanup-recurring-job-backup-snapshot`.
6. After a new recurring job is completed, there is only one snapshot for the last backup retain.

**Result Passed**

1. Manual tests have been successfully
2. requir/doc : https://github.com/longhorn/website/pull/730
