### ISSUE TITLE
[FEATURE] Restore a backup or snapshot to a different existing volume

### ISSUE THREAD

**Issue by mamiu** [longhorn/longhorn#2998]
**Is your feature request related to a problem? Please describe.**
No, there's no problem. It's just not possible right now to restore a backup (or snapshot) from one volume to another already existing volume.

**Describe the solution you'd like**
An option in the UI to restore a backup (or snapshot - whatever is easier to implement) to a different existing volume that has at least the size of the backup/snapshot.

**Describe alternatives you've considered**
As @yasker pointed out in [this comment](https://github.com/longhorn/longhorn/issues/1815#issuecomment-698443314):

> You can create a new volume from a backup of an existing volume. You can restore it from the backup into a new volume in Longhorn, then create PV/PVC for the volume, and finally use the PVC with the workload.

But that's not what we're looking for. The feature I'm asking for should be a restore to an **existing** volume not to a new one.  
Or is there anything hindering the implementation of such a feature (which I'm not aware of)?

**Comment by PhanLe1010** [comment]
@mamiu 

Why restoring into a new volume is not good enough? Can you give us the benefits of having this feature from the users' perspective? I.e., can you convince us 😁 ?

**Comment by mamiu** [comment]
@PhanLe1010 Thanks for asking. I'll try to make my point:

Let's start at the very bottom:
Nowadays multi-environment setup / hosting is the de-facto standard for all serious projects (e.g. development → staging → production).
But most of the time handling the state of multiple environments is kinda tricky (e.g. cloning the current production version to staging or the other way around) and has to be done for each project separately / differently (e.g. WordPress, Magento, Discourse, Odoo, custom development projects, etc.). There are already existing third party options to manage multi-environment setups but all of them are either hard to manage (complicated setups, difficult to use for non-techies because of command-line tools, etc.) or they're expensive.

Multi-environment setups are based on the following two things:

1. Setup & hosting of the individual environments
2. State management of a multi-environment setup (e.g. cloning between the different environments or resetting an environment to a previous state of another environment)

The number 1 (setting up different environments) is already super easy thanks to Helm and Kubernetes.
For example (I'll use WordPress in this example but it also applies to all other type of projects):

```bash
helm repo add bitnami https://charts.bitnami.com/bitnami
# Setup production environment
helm install project-name-prod bitnami/wordpress
# Setup staging environment
helm install project-name-stg bitnami/wordpress
# Setup development environment
helm install project-name-dev bitnami/wordpress
```

> This is for sure a very simplified example, but as you know it's not much more complicated to get a multi-environment setup with Helm & Kubernetes.

But number 2 (state management of a multi-environment setup) is still based on third party tools or custom implementations (I already pointed out all the disadvantages of that above). So having the option to **restore a backup (or snapshot) from one volume to another already existing volume in longhorn** would eradicate that problem and complexity all together.

For sure there are many ways to improve the UX of such a feature, like

* adding an option to group different volumes to a single environment and to give it a custom name (e.g. to be able to group the app volume and the database volume of the prod environment together and give it a name - like "project-name-prod").
* Then adding a second grouping layer to group the different environments (in our example above: to group "project-name-prod", "project-name-stg" and "project-name-dev") into something like a "Project" and to give it a custom name (similar to what rancher offers with the grouping of namespaces into projects).
* Then having a separate UI to manage "projects", i.e. to create backups and/or snapshots per environment (which will backup or snapshot all volumes which are grouped into that environment) and to restore / clone / move (or whatever you wanna call it) from one environment to another environment in that project.

As you can see, there are many ways to gild this feature but my initial request of this issue was meant to be a kind of an MVP that would already solve the tricky part. 😉

**Comment by jenting** [comment]
What if the user manually deletes the PV/PVC by then self and then you're able to restore the volume from backup and creates corresponding PV/PVC?

There is an [issue](https://github.com/longhorn/longhorn/issues/2129) probably could benefit you.

Besides that, since restore from backup restores the block level. If we need to support restore to existing volume, it means we have to stop the volume to make sure there is no write operation on it. So, it's a dangerous operation than a filesystem-level restoration.

**Comment by mamiu** [comment]
@jenting Thanks a lot for the explanation.

I thought about this and also researched it in the past hours but I couldn't find a satisfying solution.

You're right that it's a dangerous operation to just "replace" the file system while running processes have access to it. I cannot come up with any solution that doesn't require the pods/containers to be stopped. And stopping / starting pods is definitely outside of longhorns responsibility.

So yes, as sad as it sounds longhorn is probably not the right place to implement a feature like this.

I'll have a look if I could achieve something like that with Velero.

Or do you have any other / better idea?

**Comment by jenting** [comment]
No for now.

But as I know, Velero also doesn't support overwrite existing volume.

**Comment by mamiu** [comment]
True, but with Velero I can backup an environment, delete it as soon as the backup is complete and then restore it with another volume. It's definitely not as perfect as if the feature from above would have been able to implement, but it's better than doing everything manually with `kubectl` commands.

Can I close this issue or do you want to keep it open?

**Comment by jenting** [comment]
Good to know Velero fits your requirement.

I'll leave it open because this feature is good to have but not our top priority at the moment.
