### ISSUE TITLE
The architecture

### ISSUE THREAD

**Issue by mhemrg** [longhorn/longhorn#300]
Hi,
Are there any resources to get a better understanding of `longhorn-manager` and it's architecture?
For example, I'm curious to know that how `longhorn-manager` communicates with volume drivers.

**Comment by yasker** [comment]
It's standard Kubernetes storage drivers. Codes are in Longhorn manager repo (`flexvolume`, `app`, and `csi` directories). You can find Longhorn overview at: https://rancher.com/microservices-block-storage/

If you want to know how to Kubernetes storage driver get involved, check https://github.com/kubernetes-incubator/external-storage (flexvolume) and https://github.com/kubernetes-csi (CSI)
