### ISSUE TITLE
Persistent volume in in attaching/detaching loop

### ISSUE THREAD

**Issue by martiinezz** [longhorn/longhorn#3004]
**Describe the bug**
Longhorn installed with some issues (like missing flock and stat binaries on worker nodes [RancherOS 1.5.8]) and open-iscsi not running. Now any attempt to deploy an app using Rancher will result in the pod being stuck in "CreatingContainer", followed with repeated messages of Attach, Detach of volume.

**To Reproduce**

Choose an app to deploy through the Catalog (doesn't matter which project/namespace)
Deploy app
Check on pod status and pvc-volume is attaching then detaching in a loop.

**Expected behavior**
The volume attaches cleanly and the pod is deployed

**Log**
There are iscsid running on all 3 worker nodes - open-iscsi is enabled - log seems to complain about iscsi.

[longhorn-support-bundle_35ab5e73-de20-4fd1-8185-1944a59fbd13_2021-09-13T13-26-46Z.zip](https://github.com/longhorn/longhorn/files/7161855/longhorn-support-bundle_35ab5e73-de20-4fd1-8185-1944a59fbd13_2021-09-13T13-26-46Z.zip)

**Environment**:
Longhorn version: 1.2.0
Kubernetes version: 1.20 
Rancher version: 2.5.9
Node OS type and version: RancherOS 1.5.8

**Comment by jenting** [comment]
From the [best practice doc](https://longhorn.io/docs/1.2.0/best-practices/#oses-arent-supported-by-longhorn)
I don't think we support RancherOS, not sure the doc is out of date _or_ we still do not support RancherOS at this moment.

**Comment by martiinezz** [comment]
So what is your advice? Reinstall workers with CentOS 8?

**Comment by PhanLe1010** [comment]
> So what is your advice? Reinstall workers with CentOS 8? 

Yeah. or `ubuntu 18.04`

**Comment by PhanLe1010** [comment]
Closing this issue since Longhorn doesn't support RancherOS. 
Feel free to reopen if you still have question @martiinezz
