### ISSUE TITLE
[TASK] Publish Longhorn stable releases

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#3014]
**What's the task? Please describe.**
When a new Longhorn release becomes available, we need to differentiate between `stable` release and the `latest` release.

The motivation is whenever a feature release is available (e.g. v1.2.0), since the code base has tons of changes, it's next to impossible to guarantee the stability of the project in a production environment. Even our best effort to cover all the knownt test cases in the [pre-release regression test](https://longhorn.github.io/longhorn-tests/manual/) and tens of hours of running hundreds of [automation test cases](https://longhorn.github.io/longhorn-tests/integration/) running every day, there can still be issues not discovered during the release testing process, like what happened with https://github.com/longhorn/longhorn/issues/2964 .

In order to guarantee a more stable environment for production workload, we will announce a stability level along with the release. Only the Longhorn releases that have been proven by time will be marked as **stable**.

For example, the latest **stable** release at this moment is v1.1.2. And the latest release of Longhorn is v1.2.0.

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] Allow user to choose `stable` vs `latest` release in the Longhorn manager upgrade checker. And only notify the user if a newer version with the same label was available.
- [ ] Add to Release Note section of whether this release is considered `stable` or not.

**Additional context**
Add any other context or screenshots about the task request here.

**Comment by innobead** [comment]
@PhanLe1010 Please help work on item 1 of DoD to have necessary changes in upgrade checker, longhorn-manager, and UI.

**Comment by PhanLe1010** [comment]
@yasker 

I am think if we can just show users both `latest stable` and `latest` version in UI instead of having an extra setting. They have all information at once. How do you think?

**Comment by innobead** [comment]
> @yasker
> 
> I am think if we can just show users both `latest stable` and `latest` version in UI instead of having an extra setting. They have all information at once. How do you think?

I am fine with that, but just remember right now we have more than one release line, so for stable releases, it will have 1.1.x and 1.2.x, so we need to show the correct info for users what stable version is suggested based on the longhorn version they have.

**Comment by PhanLe1010** [comment]
If the user has the `1.1.2` version and the stable releases are `1.1.3` and `1.2.2`, I think we should show version `1.2.2` because there is no breaking change from `1.1.x` to `1.2.x`. If we don't show `1.2.2` version, the users will never update to `v1.2.x` because he/she might think that `1.2.x` are unstable 

How do you think @innobead ?

**Comment by innobead** [comment]
> If the user has the `1.1.2` version and the stable releases are `1.1.3` and `1.2.2`, I think we should show version `1.2.2` because there is no breaking change from `1.1.x` to `1.2.x`. If we don't show `1.2.2` version, the users will never update to `v1.2.x` because he/she might think that `1.2.x` are unstable
> 
> How do you think @innobead ?

You make another good point and agree :) Actually, the change between 1.1 and 1.2 has a major change already because they are different feature releases. 

Let's just show stable versions for users to keep it simple as possible.

**Comment by PhanLe1010** [comment]
As discussed with @innobead, If the users have x.y.z version, we will show:
1. All stable versions that are greater than x.y.z
2. The latest version if it is greater than x.y.z

ping @yasker

**Comment by yasker** [comment]
All the stable versions might be a long list. How about the latest stable release for every minor release greater than the current release?

e.g. If the current version is at v1.0.0, we can show
```
stable: v1.0.2, v1.1.2
latest: v1.2.0
```
instead of
```
stable: v1.0.2, v1.0.3, v1.0.4, v1.1.1, v.1.1.2
latest: v1.2.0
```

It's just an example above. 

Maybe we can change the server side to only report the latest stable release for each minor release to achieve this.

**Comment by PhanLe1010** [comment]
Thanks @yasker It sounds good! I agree

**Comment by innobead** [comment]
Sounds good :)

**Comment by PhanLe1010** [comment]
Test steps:
Verify that Longhorn UI works as described in the issue https://github.com/longhorn/longhorn/issues/3032 description

**Comment by chanow816** [comment]
Validation: **Passed**

---

Verified on master-head and v1.2.x-head

However I only see "Newer Stable Versions" in bottom bar, can not see  "latest version" I guess it's because there are no version newer then testing version.

**Comment by chanow816** [comment]
Validation: *** Passed ***

Test Environment

Version: master-head and v1.2.x-head
1 controlplane, 3 worker nodes, AWS t2.large
Steps:

In bottom of longhorn UI display Newer Stable Versions, the display values are the same with "Stable Longhorn Versions" in Setting -> General page
When clicked Newer Stable Versions in bottom of Longhorn UI, Longhorn UI will pop up a window with a list of stable version.
On the top of popup window there is a hyperlink will open new page to Longhorn release page, which user can see all releases include newest release

**Comment by johnwc** [comment]
This is documented in the changelog as being a feature of v1.3.0 release, but I see it in my v1.2.4 install and not listed on the changelog for v1.2.4.
