### ISSUE TITLE
[BUG] Cannot upgrade 1.0.0 -> 1.1.0 helm error

### ISSUE THREAD

**Issue by dan-evolvere** [longhorn/longhorn#3015]
**Describe the bug**
Running upgrade through rancher catalog with no changes to values (just updated image tags which the chart itself does) we get the following error;
Wait helm template failed. panic: interface conversion: interface {} is string, not map[string]interface {} goroutine 1 [running]: k8s.io/helm/pkg/strvals.(*parser).key(0xc000341100, 0xc00035d680, 0xc000657438, 0x8) /go/src/k8s.io/helm/pkg/strvals/parser.go:211 +0xfde k8s.io/helm/pkg/strvals.(*parser).key(0xc000341100, 0xc00035d200, 0xc000657650, 0x5) /go/src/k8s.io/helm/pkg/strvals/parser.go:215 +0x1ad k8s.io/helm/pkg/strvals.(*parser).key(0xc000341100, 0xc00035c870, 0x0, 0x0) /go/src/k8s.io/helm/pkg/strvals/parser.go:215 +0x1ad k8s.io/helm/pkg/strvals.(*parser).parse(0xc000341100, 0xc00035c870, 0xf00) /go/src/k8s.io/helm/pkg/strvals/parser.go:133 +0x38 k8s.io/helm/pkg/strvals.ParseInto(0x7ffc3ec1c087, 0xf54, 0xc00035c870, 0xc000000180, 0x200000003) /go/src/k8s.io/helm/pkg/strvals/parser.go:85 +0xbf main.vals(0x0, 0x0, 0x0, 0xc00033cb80, 0x1, 0x1, 0x2e176f8, 0x0, 0x0, 0x2e176f8, ...) /go/src/k8s.io/helm/cmd/helm/install.go:420 +0x29d main.(*templateCmd).run(0xc0000c0240, 0xc000493180, 0xc00043c1c0, 0x1, 0x7, 0x0, 0x0) /go/src/k8s.io/helm/cmd/helm/template.go:139 +0x1dc k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc000493180, 0xc00043c150, 0x7, 0x7, 0xc000493180, 0xc00043c150) /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:826 +0x465 k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00067e280, 0x8, 0x8, 0xc00067e280) /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:914 +0x2fc k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(...) /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:864 main.main() /go/src/k8s.io/helm/cmd/helm/helm.go:270 +0x7a : exit status 2

**To Reproduce**
1. Install lh 1.0.0
2. Go to rancher catalog app
3. Click upgrade
4. Leave settings as is and click upgrade
5. See error

**Expected behavior**
Upgrade starts without error

**Log**
Wait helm template failed. panic: interface conversion: interface {} is string, not map[string]interface {} goroutine 1 [running]: k8s.io/helm/pkg/strvals.(*parser).key(0xc000341100, 0xc00035d680, 0xc000657438, 0x8) /go/src/k8s.io/helm/pkg/strvals/parser.go:211 +0xfde k8s.io/helm/pkg/strvals.(*parser).key(0xc000341100, 0xc00035d200, 0xc000657650, 0x5) /go/src/k8s.io/helm/pkg/strvals/parser.go:215 +0x1ad k8s.io/helm/pkg/strvals.(*parser).key(0xc000341100, 0xc00035c870, 0x0, 0x0) /go/src/k8s.io/helm/pkg/strvals/parser.go:215 +0x1ad k8s.io/helm/pkg/strvals.(*parser).parse(0xc000341100, 0xc00035c870, 0xf00) /go/src/k8s.io/helm/pkg/strvals/parser.go:133 +0x38 k8s.io/helm/pkg/strvals.ParseInto(0x7ffc3ec1c087, 0xf54, 0xc00035c870, 0xc000000180, 0x200000003) /go/src/k8s.io/helm/pkg/strvals/parser.go:85 +0xbf main.vals(0x0, 0x0, 0x0, 0xc00033cb80, 0x1, 0x1, 0x2e176f8, 0x0, 0x0, 0x2e176f8, ...) /go/src/k8s.io/helm/cmd/helm/install.go:420 +0x29d main.(*templateCmd).run(0xc0000c0240, 0xc000493180, 0xc00043c1c0, 0x1, 0x7, 0x0, 0x0) /go/src/k8s.io/helm/cmd/helm/template.go:139 +0x1dc k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc000493180, 0xc00043c150, 0x7, 0x7, 0xc000493180, 0xc00043c150) /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:826 +0x465 k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00067e280, 0x8, 0x8, 0xc00067e280) /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:914 +0x2fc k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(...) /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:864 main.main() /go/src/k8s.io/helm/cmd/helm/helm.go:270 +0x7a : exit status 2

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.0.0 upgrading to 1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher catalog
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE (1.17.5)
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: RHEL7
   - CPU per node: 48 cores
   - Memory per node: 128GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 10G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 24

**Additional context**
Answers from rancher UI;
csi.attacherImage		registry.example.com/docker-remote/longhornio/csi-attacher	 	
csi.attacherReplicaCount			 	
csi.driverRegistrarImage		registry.example.com/docker-remote/longhornio/driver-registrar	 	
csi.kubeletRootDir		/var/lib/kubelet	 	
csi.provisionerImage		registry.example.com/docker-remote/longhornio/csi-provisioner	 	
csi.provisionerReplicaCount			 	
csi.resizerImage		registry.example.com/docker-remote/longhornio/csi-resizer	 	
defaultSettings.autoSalvage		true	 	
defaultSettings.backupTarget			 	
defaultSettings.backupTargetCredentialSecret			 	
defaultSettings.backupstorePollInterval		300	 	
defaultSettings.createDefaultDiskLabeledNodes		false	 	
defaultSettings.defaultDataPath		/space/longhorn	 	
defaultSettings.defaultLonghornStaticStorageClass		longhorn-static	 	
defaultSettings.defaultReplicaCount		1	 	
defaultSettings.disableSchedulingOnCordonedNode		true	 	
defaultSettings.guaranteedEngineCPU		0	 	
defaultSettings.mkfsExt4Parameters			 	
defaultSettings.registrySecret			 	
defaultSettings.replicaSoftAntiAffinity		true	 	
defaultSettings.replicaZoneSoftAntiAffinity		true	 	
defaultSettings.storageMinimalAvailablePercentage		10	 	
defaultSettings.storageOverProvisioningPercentage		500	 	
defaultSettings.taintToleration			 	
defaultSettings.upgradeChecker		true	 	
defaultSettings.volumeAttachmentRecoveryPolicy		wait	 	
driver		csi	 	
image.defaultImage		false	 	
image.longhorn.engine		registry.example.com/docker-remote/longhornio/longhorn-engine	 	
image.longhorn.engineTag		v1.0.0	 	
image.longhorn.instanceManager		registry.example.com/lh/longhorn-imanager	 	
image.longhorn.instanceManagerTag		v1_20200514	 	
image.longhorn.manager		registry.example.com/docker-remote/longhornio/longhorn-manager	 	
image.longhorn.managerTag		v1.0.0	 	
image.longhorn.ui		registry.example.com/docker-remote/longhornio/longhorn-ui	 	
image.longhorn.uiTag		v1.0.0	 	
ingress.enabled		true	 	
ingress.host		longhorn.example.com	 	
longhorn.default_setting		true	 	
persistence.defaultClass		true	 	
persistence.defaultClassReplicaCount		1	 	
privateRegistry.registryPasswd		supersecretpassword	 	
privateRegistry.registryUrl		registry.example.com/docker-remote	 	
privateRegistry.registryUser		registryusername

**Comment by jenting** [comment]
Looks like it's related to #2121

**Comment by jenting** [comment]
As #2121 discussed, this can be not fixed at Longhorn side, closing.
