### ISSUE TITLE
[BUG] Error taking snapshot: failed to complete backupAndCleanup for prometheus-data: Bad response statusCode

### ISSUE THREAD

**Issue by qdupuy** [longhorn/longhorn#3016]
Hello,

On a volume, I deleted the snapshot jobs via the GUI.

During a backup of this volume, I find myself with errors 500 :

```
time="2021-09-14T09:31:38Z" level=fatal msg="Error taking snapshot: failed to complete backupAndCleanup for prometheus-data: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=fail to backup snapshot: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.2/longhorn [--url 10.42.0.9:10001 backup create --dest s3://backup-x-public@x/longhorn/x --label RecurringJob=c-iueq77 --label KubernetesStatus={\"pvName\":\"prometheus-data\",\"pvStatus\":\"Bound\",\"namespace\":\"monitoring\",\"pvcName\":\"prometheus-data\",\"lastPVCRefAt\":\"\",\"workloadsStatus\":[{\"podName\":\"prometheus-server-9d9559446-xmlv8\",\"podStatus\":\"Running\",\"workloadName\":\"prometheus-server-9d9559446\",\"workloadType\":\"ReplicaSet\"}],\"lastPodRefAt\":\"\"} c-iueq77-acd5147c], output , stderr, time=\"2021-09-14T09:31:28Z\" level=info msg=\"Backing up c-iueq77-acd5147c on tcp://10.42.2.18:10045, to s3://x-public@x/longhorn/x\"\ntime=\"2021-09-14T09:31:38Z\" level=fatal msg=\"Error running create backup command: failed to create backup to s3://x@x/longhorn/x for volume prometheus-data: rpc error: code = Unknown desc = failed lock backupstore/volumes/5e/4d/prometheus-data/locks/lock-3439f798bd374d2d.lck type 1 acquisition\"\n, error exit status 1] from [http://longhorn-backend:9500/v1/volumes/prometheus-data?action=snapshotBackup]"
```

With lhexec.sh script, I can delete the snapshots but it doesn’t do anything and others come back :

```
lhexec.sh prometheus-data snapshot ls
ID
c-iueq77-edc2257d
c-iueq77-acd5147c
```

lock-3439f798bd374d2d.lck  is empty

How can I avoid this type of problem?

Longhorn version : 1.1.2

**Comment by jenting** [comment]
Related Slack message https://rancher-users.slack.com/archives/CC2UQM49Y/p1631612327099700

**Comment by PhanLe1010** [comment]
@jenting I saw some of your analysis in slack about the possible root cause. Will assign this issue to you

**Comment by jenting** [comment]
From the longhorn-manager log, I see the backup deletion takes a very long time. For volume `prometheus-data`:

```
time="2021-09-29T06:23:09Z" level=info msg="Start Deleting backup s3://k8s-sky@eu-west-3/longhorn/skyloud-public?backup=backup-57830ab42dc744db&volume=prometheus-data"
time="2021-09-29T18:40:28Z" level=info msg="Complete deleting backup s3://k8s-sky@eu-west-3/longhorn/skyloud-public?backup=backup-0df224ee397f468a&volume=prometheus-data"

time="2021-09-30T06:23:22Z" level=info msg="Start Deleting backup s3://k8s-sky@eu-west-3/longhorn/skyloud-public?backup=backup-397c6ff8bf7c4981&volume=prometheus-data"
time="2021-09-30T06:38:20Z" level=info msg="Complete deleting backup s3://k8s-sky@eu-west-3/longhorn/skyloud-public?backup=backup-397c6ff8bf7c4981&volume=prometheus-data"

time="2021-09-30T06:53:46Z" level=info msg="Start Deleting backup s3://k8s-sky@eu-west-3/longhorn/skyloud-public?backup=backup-b8942d5e13f441e0&volume=prometheus-data"
time="2021-09-30T07:08:32Z" level=info msg="Complete deleting backup s3://k8s-sky@eu-west-3/longhorn/skyloud-public?backup=backup-b8942d5e13f441e0&volume=prometheus-data"
```
And during the backup deletion in progress, the backup creation request comes in, so you encounter the type 1 acquisition error.

From the [code](https://github.com/longhorn/longhorn-manager/blob/v1.1.2/app/volume.go#L489-L573), the backup job would wait for the backup creation finished and then perform the backup clean up.

I'm curious what's the CRON setting of the volume `prometheus-data`? Because I saw it will create a backup at 18:00 every day, but from the log, I don't know when will the backup creation finished (progress 100%). So I can't tell if there is a race condition inside the code now _or_ there are 2 backup jobs within 1 hour.

**Comment by qdupuy** [comment]
@jenting I sent you a private message with a screenshot about my settings

**Comment by qdupuy** [comment]
After purging and deleting recurring tasks to recreate them, I have no errors at the moment.

Wait & see

**Comment by jenting** [comment]
> After purging and deleting recurring tasks to recreate them, I have no errors at the moment.
> 
> Wait & see

After debugging with @qdupuy, we found that there're 2 jobs with the same snapshot.

The recurring job setting is:
![image](https://user-images.githubusercontent.com/49380831/135940955-51db0234-ca4f-4282-8c19-3592677a3476.png)

The Jobs output is:
```
prometheus-data-c-iueq77-c-manual-q723q                           1/1           126m       14d
prometheus-data-c-oik6zh-c-1633027200                             1/1           17m        13h
prometheus-data-c-oik6zh-c-manual-lpil5                           1/1           17m        14d
prometheus-data-c-zondst-c-1633070400                             1/1           15m        117m
prometheus-data-c-zondst-c-manual-wcb6k                           1/1           27s        14d
```

After requesting manual delete the duplicate and orphan job by kubectl
```
prometheus-data-c-iueq77-c-manual-q723q                           1/1           126m       14d
prometheus-data-c-oik6zh-c-manual-lpil5                           1/1           17m        14d
prometheus-data-c-zondst-c-manual-wcb6k                           1/1           27s        14d
```

The volume `prometheus-data` recurring backup works well.

**Comment by jenting** [comment]
Not sure _why_ there'll be a duplicated backup _or_ orphan job does not be clean up.

@qdupuy if everything goes well, plz help close this issue.

**Comment by qdupuy** [comment]
Everything is ok
