### ISSUE TITLE
[BUG] share-manager unable to mount volume

### ISSUE THREAD

**Issue by cocampbe** [longhorn/longhorn#3017]
**Describe the bug**
share-manager pod cannot mount a specific volume. I see this error in the logs of the share manager pod.

> "waiting with nfs server start, failed to mount volume" volume=pvc-7cc9fa38-2c37-4fd3-b7b4-7d9734641e94 

This volume has been working until recently.

**To Reproduce**
1. need RWX volume
2. create pods that use the RWX volume.

**Expected behavior**
share-manager attaches to volume and shares via NFS.

**Log**
> level=warning msg="waiting with nfs server start, failed to mount volume" volume=pvc-7cc9fa38-2c37-4fd3-b7b4-7d9734641e94

>Warning  FailedAttachVolume      47s (x11 over 9m)      attachdetach-controller  AttachVolume.Attach failed for volume "pvc-7cc9fa38-2c37-4fd3-b7b4-7d9734641e94" : rpc error: code = DeadlineExceeded desc = Failed to attach volume pvc-7cc9fa38-2c37-4fd3-b7b4-7d9734641e94 to node

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.1.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: OL7.9
   - CPU per node: 6
   - Memory per node: 12
   - Disk type(e.g. SSD/NVMe): Vdisk on top of SSD.
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 7

**Additional context**
We do not use multipathd, so that did not help in troubleshooting. Really strange issue.

**Comment by cocampbe** [comment]
I have stopped all pods that use the volume. I still see a lingering mount on one of the nodes at /tmp/mnt/pvc-7cc9fa38-2c37-4fd3-b7b4-7d9734641e94. I did attached it in maintenance mode at one point. It looks like that might be a mount for that. Looks like it did not get cleaned up.

**Comment by cocampbe** [comment]
I am starting to think that the volume is bad. But the longhorn UI shows as if everything is healthy.

**Comment by cocampbe** [comment]
I ran an fsck on the disk and it's workiing now.

**Comment by turbotorsten** [comment]
Had the same problem, running fsck fixed the volume for me too.
