### ISSUE TITLE
[TASK] Include disto with k3s and SELinux enabled in Longhorn integration tests

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3019]
**What's the task? Please describe.**
Include the distro with k3s with SELinux so that the integration tests can be run on it as a part of release testing.

**Describe the items of the task (DoD, definition of done) you'd like.**
- [ ] Create the Jenkins job config
- [ ] Run the demo and verify

**Additional context**
https://longhorn.github.io/longhorn-tests/manual/pre-release/environment/k3s-selinux-compatibility/

**Comment by yangchiu** [comment]
Related to https://github.com/longhorn/longhorn-tests/pull/1429, https://github.com/longhorn/longhorn-tests/pull/1426 and https://github.com/longhorn/longhorn-tests/pull/1442
