### ISSUE TITLE
[BUG] Snapshots and Backups chain displays backup that was previously deleted on Backup screen

### ISSUE THREAD

**Issue by mfbrj** [longhorn/longhorn#3033]
**Describe the bug**
UI Snapshots and Backups chain displays backup that was previously deleted on Backup screen

**To Reproduce**
1. Create a recurring backup job (`jobA`) and wait for 2 or more backup be performed on a volume
2. Create another backup job (`jobB`) and wait for 1 backup be performed on the same volume
3. Go to Backup screen and delete all backup related to first recurring backup job (`jobA`) on the same volume
![image](https://user-images.githubusercontent.com/835834/133873259-7fa8ebd9-05d4-4c0f-8851-73c9a2d12305.png)

4. Go to Volume screen and see that still there is a backup related to the `jobA` that was deleted on step 3.
![image](https://user-images.githubusercontent.com/835834/133873352-9c081816-18fc-4347-957f-f0ebb517b5ea.png)

**Expected behavior**
No previously deleted backup displayed.

**Environment:**
 - Longhorn version:  1.2.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE v1.20.9
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 8
 - Node config
   - OS type and version: Ubuntu 20.04.3 LTS   kernel 5.4.0-84-generic
   - CPU per node: 4
   - Memory per node: 16 GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 20

**Comment by shuo-wu** [comment]
The replica sync agent server will blindly record all backups they had done. [The backups recorded by the servers won't be cleaned up](https://github.com/shuo-wu/longhorn-engine/blob/master/pkg/sync/rpc/server.go#L528-L535) even if the related backups are already removed from the remote backup target. This is the root cause of this issue. 

To resolve it, we need to consider [this enhancement](https://github.com/longhorn/longhorn/issues/3035) first

**Comment by mfbrj** [comment]
@shuo-wu Is this related to #2997?

**Comment by shuo-wu** [comment]
No. It's different from the case you report. That ticket is mainly related to the recurring job behaviors. And as I just mentioned in that ticket, it may be not a bug.

For this issue, I think we can reproduce it without the recurring job:
1. Create and attach a random Longhorn volume.
2. Create some backups for the volumes.
3. Delete the backups on the Backup UI page.
4. Go back to the volume detail page. The info of removed backups still exists (in the snapshot tooltips).

**Comment by jenting** [comment]
Okay, after discuss internally, we should improve this to make the Snapshots and Backups list chain inside the Volume page consistent with the Backup page.

**Comment by jenting** [comment]
We'll fix it on the backend side.

**Comment by chanow816** [comment]
**Validation : Pass**

Verified on longhorn-manager master-head
Backup deleted in backup page will reflected in volume page's Snapshots and Backups chain
The item in chain will change from green(backup) to blue(snapshot) matched real situation
