### ISSUE TITLE
[BUG] Unable to add disk to node because UI does not show "edit disks" action

### ISSUE THREAD

**Issue by rseichter** [longhorn/longhorn#3034]
**Describe the bug**
The documentation for [adding a disk](https://longhorn.io/docs/1.2.0/volumes-and-nodes/multidisk/) to a node states: "To add a new disk for a node, head to the Node tab, select one of the nodes, and _select Edit Disks in the dropdown menu_."

However, the UI does not display an Edit Disks action anywhere I can see it. The only option is Edit Node (see attached screenshot), which opens a popup limited to enabling/disabling node scheduling and node eviction. I have tried adding a disk to a node in state "Ready" and also to a node where scheduling was disabled; the observed behaviour is the same.

**To Reproduce**
1. Install Longhorn 1.2.0 using kubectl as described [here](https://longhorn.io/docs/1.2.0/deploy/install/install-with-kubectl/).
2. Access web UI.
3. Click on "Node" in navigation bar.
4. Select any of the existing nodes in "ready" state using one of the checkboxes.
5. Try to locate the Edit Disks dropdown (or button, or link) which the documentation mentions, and fail doing so.

**Expected behavior**
UI should display a button, link, or dropdown entry to allow editing disks.

**Environment:**
 - Longhorn version: 1.2.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version: Raspberry Pi OS 10.10 64bit
   - CPU per node: 4 cores (BCM2835 CPU)
   - Memory per node: 8 GiB
   - Disk type(e.g. SSD/NVMe): eMMC and USB
   - Network bandwidth between the nodes: 1 GBit/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Raspberry Pi Compute Module 4
 - Number of Longhorn volumes in the cluster: Fresh installation, one per node (at /var/lib/longhorn).

**Comment by rseichter** [comment]
<img width="631" alt="screenshot" src="https://user-images.githubusercontent.com/30873939/133892861-bda1f8bd-e150-464d-bb32-a6008dc51243.png">

**Comment by mfbrj** [comment]
@rseichter
![image](https://user-images.githubusercontent.com/835834/133906207-a389eeab-d033-4340-b395-bed4cb851d83.png)

**Comment by rseichter** [comment]
@mfbrj Oh my, the pitfalls of using a small screen for Raspberry Pi... The three rightmost columns were not visible, and I did not even consider that there might be content to be found when scrolling to the right. 🤓 Thanks for pointing this out.

**Comment by mrwormhole** [comment]
hahahahaahahahahaahahahaha, this gotta be the most funny issue I have ever encountered on whole github, you were not alone king, had to scroll horizontally

**Comment by cianiandreadev** [comment]
Holy Moly the UI!
Thanks! Another fellow saved! 😆
