### ISSUE TITLE
[IMPROVEMENT] Simplify the way to record and fetch backup info after introducing Backup CRD

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3035]
**Is your feature request related to a problem? Please describe.**
After introducing Backup CRDs, I think Longhorn does not need to rely on [the replica sync agent server to record the backup list](https://github.com/shuo-wu/longhorn-engine/blob/a3f530faf29fa730e63dfdade3ce2e2f0fe29461/pkg/sync/rpc/server.go#L528-L535) and ask [the engine monitor to record them in the Engine CRs](https://github.com/longhorn/longhorn-manager/blob/e4be7bebf46ce43e06e3d5ca882f6fda21588afd/controller/engine_controller.go#L809-L814). Maybe we can simplify this logic and workflow.

**Describe the solution you'd like**
The replica sync agent server may need to record the current backup creation progress & status only. The backup-related controllers rather than the engine monitor in the longhorn manager side should directly request the backup status from the sync agent server. And it's enough to rely on Backup CRs to record all old backups.

**Comment by jenting** [comment]
TODO:
- check when backup creation is in progress, what's the behavior when the engine lost?
- add a new action button under the Snapshots and Backups to allow users to delete snapshot only _or_ delete snapshot & backup.

**Comment by jenting** [comment]
> Check when backup creation is in progress, what's the behavior when the engine is lost?

Did a quick test by deleting the corresponding engine instance manager Pod of that engine.
The Backup CR become `Error` state with the error message
```
failed to execute: /var/lib/longhorn/engine-binaries/quay.io-jenting-longhorn-engine-2cafc07/longhorn [--url 10.42.3.221:10000 backup status backup-93fcef357eac46af --replica tcp://10.42.1.15:10015], output , stderr, time="2021-11-02T01:12:39Z" level=fatal msg="Error querying backup status: Failed to get backup status on tcp://10.42.1.15:10015 for backup-93fcef357eac46af: unknown replica"
```

**Comment by khushboo-rancher** [comment]
@jenting Could you help with the testing steps/area here?

**Comment by jenting** [comment]
> @jenting Could you help with the testing steps/area here?

This enhances the longhorn engine internally, and we have an automation test in the longhorn engine already.

However, here are the test steps from longhorn manager point of view.
- Check the `backupStatus` moves from Engine CR to Backup CR, the Engine CR `backupStatus` data field is empty.
- Check the following fields containing data during backup in progress in the Backup CR.
  - replicaAddress
  - progress
  - state
  - error (if present)
- During the backup in progress, restart the longhorn manager DaemonSet, check the above fields containing data in the Backup CR.

**Comment by chanow816** [comment]
**Validation : Pass**  

Validated on Longhorn master-head(longhorn-manager master)


In Engine CR :
```
status:
    backupStatus: null
```
After restart longhorn-manager daemonset, in Backups CR : 

```
  status:
    backupCreatedAt: ""
    labels: null
    lastSyncedAt: null
    messages: null
    ownerID: controlplane
    progress: 54
    replicaAddress: tcp://10.42.1.34:10015
    size: ""
    snapshotCreatedAt: ""
    snapshotName: f8d42bc1-caec-405d-a004-9068a943ad3d
    state: InProgress
    url: ""
    volumeBackingImageName: ""
    volumeCreated: ""
    volumeName: ""
    volumeSize: ""
```

After created error situation, in Backups CR:
Scenario from https://github.com/longhorn/longhorn/issues/1268
```
status:
    backupCreatedAt: ""
    error: |
      failed to put object: backupstore/backupstore/volumes/17/22/bak/blocks/ee/87/ee87f4f6defbdbe3724bf999b56c8cf7281c0d18fc980754ea837f6d616fcea9.blk response: {

      } error: AWS Error:  XMinioStorageFull Storage backend has reached its minimum free disk threshold. Please delete a few objects to proceed. <nil>
      507 16C08E5AEBD4F82C
    labels: null
    lastSyncedAt: "2021-12-14T07:26:26Z"
    messages: null
    ownerID: worker1
    progress: 83
    replicaAddress: tcp://10.42.1.34:10015
    size: ""
    snapshotCreatedAt: ""
    snapshotName: 3d12cfca-f2a1-4b4e-b534-961c049fabec
    state: Error
    url: ""
    volumeBackingImageName: ""
    volumeCreated: ""
    volumeName: ""
    volumeSize: ""
```
