### ISSUE TITLE
s3 integration issue 

### ISSUE THREAD

**Issue by datthu119** [longhorn/longhorn#3036]
error :-fail to backup snapshot: failed to execute: /var/lib/longhorn/engine-binaries/rancher-mirrored-longhornio-longhorn-engine-v1.1.2/longhorn [--url 192.168.5.253:10000 backup create --dest s3:/longhorn-rancher-backups@ap-south-1/longhorn 3d70ca36-6cdd-46d0-8aa0-628d9dad34a6], output , stderr, , error fork/exec /var/lib/longhorn/engine-binaries/rancher-mirrored-longhornio-longhorn-engine-v1.1.2/longhorn: invalid argument

**Comment by khushboo-rancher** [comment]
@datthu119 Can you please check if the backup target is set properly? It should be in format `s3://<s3-bucket-name>@<region>/`

**Comment by jenting** [comment]
@datthu119 you probably missing two slash `//`.
You're using `s3:/longhorn-rancher-backups@ap-south-1/longhorn`, should be `s3://longhorn-rancher-backups@ap-south-1/longhorn`

**Comment by jenting** [comment]
Close it, feel free to reopen it if there is any issue/problem.
