### ISSUE TITLE
[QUESTION] How to configure disk for volumes for Longhorn?

### ISSUE THREAD

**Issue by mchudinov** [longhorn/longhorn#3039]
How to configure disk for volumes for Longhorn during installation using configuration options? Not in GUI please!

I have a couple of Kubernetes nodes with large disks. Disk is mounted at `/var/lib/data/`

How to configure Longhorn at installation to use this `/var/lib/data/` only?

I tried to use helm chart with `values.yml` like this. 
```yaml
defaultSettings:
  defaultDataPath: /var/lib/data/
```
It does not work as I expected, Volumes are placed at `/var/lib/longhorn/` and disk mounted at `/var/lib/data/` is not even shown in Longhorn GUI.

**Comment by joshimoo** [comment]
Default settings only apply to new installations not upgrades, was this a new installation?
There are additional ways of specifying custom disks for each node during installation more info here: https://longhorn.io/docs/1.2.0/advanced-resources/default-disk-and-node-config/#customizing-default-disks-for-new-nodes

But generally the simplest would be to use the default settings for a new installation in case where all nodes use the same storage path for your dedicated disks i.e `/var/lib/data` in your case.

**Comment by mchudinov** [comment]
This is a fresh new installation of Longhorn.

Thank you for the link to the relevant documentation! 
However the documentation is confusing. It is written there:
`Prerequisite: The Longhorn setting Create Default Disk on Labeled Nodes must be enabled.`
But how to enable setting Create Default Disk on Labeled Nodes? No example is given.

Then I am confused about Storage Tags https://longhorn.io/docs/1.2.0/volumes-and-nodes/storage-tags/
Do `Storage Tags` do the same job as `Default Disk on Labeled Nodes` but for a specific StorageClass ?

**Comment by mchudinov** [comment]
I need more assistance with configuration of a dedicated disk on a dedicated nodes for Longhorn for a fresh Longhorn installation.

My cluster has 3 dedicated worker storage-nodes with a big disk attached at `/var/lib/data/` and 3 other worker nodes.

This dedicated storage nodes have labels and annotations like this:
```
Labels:             
                    
                    longhorn=storage
                    node.longhorn.io/create-default-disk=config                    
Annotations:
                    node.longhorn.io/default-disks-config:
                      [{"path":"/var/lib/data/","allowScheduling":true,"tags":["storage"]},{"path":"/var/lib/longhorn/","allowScheduling":false}]
                    node.longhorn.io/default-node-tags: ["storage"]
```

longhorn `values.yaml`
```yaml
defaultSettings:
  create-default-disk-labeled-nodes: true
  systemManagedComponentsNodeSelector: "longhorn:storage"
  default-data-path: "/var/vcap/data/"
```
Longhorn is installed using Helm chart:
`helm install longhorn longhorn/longhorn --namespace longhorn-system --values longhorn/values.yml `

Problems:
1. Some of Longhorn `instance-manager` pods are unstable, being created and dropped with `Predicate MatchNodeSelector failed` message
2. A simple test creates a volumes at `/var/lib/longhorn/`, not at `/var/vcap/data/` as expected
3. Disks at `/var/vcap/data/` are not shown in Longhorn web GUI under nodes
4. Simple worker nodes are marked as "Schedulable" in Longhorn GUI, expected to be disabled.
5. Values `create-default-disk-labeled-nodes` and `default-data-path` in ConfigMap `longhorn-default-setting` are **NOT** set. However `system-managed-components-node-selector: longhorn:storage` is set. 

Any help with troubleshooting is very appreciated.

**Comment by jenting** [comment]
> This is a fresh new installation of Longhorn.
> 
> Thank you for the link to the relevant documentation!
> However the documentation is confusing. It is written there:
> `Prerequisite: The Longhorn setting Create Default Disk on Labeled Nodes must be enabled.`
> But how to enable this `setting Create Default Disk on Labeled Nodes`? No example is given.

It's on the Longhorn UI setting page `Create Default Disk on Labeled Nodes`.
_or_
The `defaultSettings.createDefaultDiskLabeledNodes` in the helm chart.

> 
> Then I am confused about Storage Tags https://longhorn.io/docs/1.2.0/volumes-and-nodes/storage-tags/
> Do `Storage Tags` do the same job as `Default Disk on Labeled Nodes` but for a specific StorageClass ?

Default disk is where is the folder path Longhorn stores the data/replicas on the host.

The storage tags are if you have different disk types like SSD/HDD on the hosts, you could set up different Storage Classes. One storage class for SSD, one storage class for HDD. Then, the application/PVC could choose which storage class to use.
