### ISSUE TITLE
Kubernetes snapshot support (csi-snapshotter)

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#304]
In Kubernetes 1.12, the snapshot support will be added. We will evaluate the feature and if it goes well, we will add the support for it.

The doc is at:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/csi-snapshot.md

The external snapshotter:
https://github.com/kubernetes-csi/external-snapshotter

**Comment by lomori** [comment]
Any estimates for when the CSI Volume Snapshot is going to be available?

**Comment by joshimoo** [comment]
@lomori csi snapshot support is going to be included in the longhorn 1.1 release which is targeting early November.
After this issue is closed, it will be available in the master branch and can be used for testing.

**Comment by joshimoo** [comment]
Document outlining the kubernetes snapshot support changes between the alpha and beta csi snapshot support.
https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/177-volume-snapshot#controller-split

**Comment by khushboo-rancher** [comment]
Verified on longhorn Master - 09/14/2020

Validation - **Pass**

Executed the test cases from https://rancher.atlassian.net/wiki/spaces/LON/pages/735379688/CSI+Snapshot+Support

Once https://github.com/longhorn/longhorn/issues/1788 is closed, we are good to close this feature.

**Comment by joshimoo** [comment]
@khushboo-rancher is this issue good to close?

**Comment by khushboo-rancher** [comment]
Functionality has been validated manually and right now the implementation of integration tests for this feature is in progress.
We can close this issue and create one for the integration test implementation if we want.

**Comment by joshimoo** [comment]
@khushboo-rancher no problem you can keep it open then, was just following up :)

**Comment by yasker** [comment]
It's unlikely we have time for writing the automation test for this issue in v1.1.0. Let's do a regression test and then punt it to v1.1.1 release.

**Comment by PhanLe1010** [comment]
Revalidated manually: Pass
