### ISSUE TITLE
[BUG] Fail to live upgrade to v1.2.x or v1.1.3

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3052]
**Describe the bug**
Live upgrade fails if upgraded from v1.2.0 to v1.2.1-rc1

**To Reproduce**
1. Install Longhorn v1.2.0.
2. Create some rwo and rwx volumes. (With parameter `migratable:true` and without the parameter.)
3. Upgrade to v1.2.1-rc1
4. Upgrade the volumes
5. Observe the upgrade stuck in progress

**Expected behavior**
Live upgrade should succeed.

**Log**
[longhorn-support-bundle_31ac3144-3ee9-4f59-86f5-3f9051e009b8_2021-09-22T18-48-07Z.zip](https://github.com/longhorn/longhorn/files/7213122/longhorn-support-bundle_31ac3144-3ee9-4f59-86f5-3f9051e009b8_2021-09-22T18-48-07Z.zip)

**Environment:**
 - Longhorn version: v1.2.x-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3

**Comment by khushboo-rancher** [comment]
As per @Shuo, the problem i not happening with master. So, may be the fix is not backported

**Comment by kaxing** [comment]
Encouter the same problem when upgrading from release v1.1.1.

Here are the exact steps that I can reproduce this:

Steps:
1. Deploy cluster with k3s ( 1 + 3 worker nodes, 1 act as control node )
2. Install v1.1.1
3. Create some volumes
4. Install v1.1.2
5. Create some volumes
6. Install v1.2.0
7. Create some volumes
8. Install v1.2.1-rc1
9. Create some volumes
10. Change concurrent engine image automatic upgrade to 3 (if set to 1 it will may had chance stuck with the one with problem)
11. Wait for the upgrading finish

Result:
volumes with v1.1.1 engine image will stuck with upgrading spinning circle and seeing this error message repeatly showing up:
```
level=warning msg="Error syncing Longhorn volume longhorn-system/v111" controller=longhorn-volume error="fail to sync longhorn-system/v111: no old replica for the volume" node=c1-worker1
```

Logs:
[longhorn-support-bundle_26cce7d8-8b4d-46a9-b97c-7fd543c5e000_2021-09-23T00-40-34Z.zip](https://github.com/longhorn/longhorn/files/7214601/longhorn-support-bundle_26cce7d8-8b4d-46a9-b97c-7fd543c5e000_2021-09-23T00-40-34Z.zip)

**Comment by kaxing** [comment]
If upgrading to longhorn-manager master branch(1d2093a8) from the situation in my last comment,
both engine image from v1.1.1(was not finish upgrading to v1.2.1-rc1 ei) and v1.2.1-rc1 will be stuck in upgrading.
![image](https://user-images.githubusercontent.com/602540/134451979-2427e0f6-2ea3-4585-9618-2214554736ce.png)

**Comment by innobead** [comment]
> If upgrading to longhorn-manager master branch(1d2093a8) from the situation in my last comment,
> both engine image from v1.1.1(was not finish upgrading to v1.2.1-rc1 ei) and v1.2.1-rc1 will be stuck in upgrading.
> ![image](https://user-images.githubusercontent.com/602540/134451979-2427e0f6-2ea3-4585-9618-2214554736ce.png)

As we discussed, I would not suggest continuous testing from an problematic situation, because this will cause some misunderstanding.

**Comment by shuo-wu** [comment]
The cause of this issue:
1. The volume live upgrade starts.
2. Longhorn creates and launches new replicas based on the old replicas.
3. Then Longhorn tries to activate the new replicas, clean up all old replicas, and ask the engine to switch to the new replicas
4. The activation and cleanup succeed. But the engine switch fails due to an update conflict.
5. Longhorn (volume controller) retries the switch. Since the old replica does not exist now, the sync loop will wrongly fail at [this check](https://github.com/longhorn/longhorn-manager/blob/99d85dd9bf9b92b4845d616004aebc3bbcc02915/controller/volume_controller.go#L2864-L2866).

That is why the error log like the following is printed:
```
level=warning msg="Error syncing Longhorn volume longhorn-system/v111" controller=longhorn-volume error="fail to sync longhorn-system/v111: no old replica for the volume" node=c1-worker1

```

**Comment by shuo-wu** [comment]
Need to re-test the live migration feature after merging the fix.

**Comment by khushboo-rancher** [comment]
Validated with v1.2.1-rc2

Validation - **In Progress**

On v1.2.1-rc2, things looked good. Continuing testing all the scenarios of upgrade.
