### ISSUE TITLE
[QUESTION] What does Size and Actual size really mean?

### ISSUE THREAD

**Issue by artur9010** [longhorn/longhorn#3054]
**Question** What does Size and Actual size really mean? I have 7Gi volume that have 20Gi actual size

**Environment:**
 - Longhorn version: 1.2.0
 
![image](https://user-images.githubusercontent.com/4835677/134429974-6b8b96b3-c56d-44af-a25f-6a3ec56c0621.png)

**Comment by PhanLe1010** [comment]
You can refer to this document https://longhorn.io/docs/1.2.0/volumes-and-nodes/volume-size/

**Comment by jenting** [comment]
Close it since the question is answered.
