### ISSUE TITLE
[TASK] Build a CI pipeline to mirror all CSI dependence images to longhornio DockerHub repo

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3056]
**What's the task? Please describe.**
When we update [CSI dependent components](https://kubernetes-csi.github.io/docs/sidecar-containers.html) to newer versions, we want to retag and publish those upstream images to `longhornio` DockerHub repo. 
Since we might need to do this every time we raise the version for those components, we want to build a Drone pipeline for this process. 

**Note:** The CSI dependent images are multi-arch so we need to make sure the retag images are also multi-arch including amd64, arm64 and s390x

**Comment by innobead** [comment]
@meldafrawi Please try to leverage this script if possible. https://github.com/rancher/image-mirror/blob/master/image-mirror.sh

**Comment by meldafrawi** [comment]
Update: I was able to use the script to mirror CSI images to my dockerhub repo.

**Comment by innobead** [comment]
We need to clone s390x CSI images from upstream as well to support #3425

**Comment by PhanLe1010** [comment]
Do we want to watch this [longhorn-images.txt](https://github.com/longhorn/longhorn-manager/blob/dd8e20c76dcd740db4301f3e37cb314e15a01b5e/deploy/longhorn-images.txt#L1-L5) file inside longhorn/longhorn-manager repo instead because it will be updated first before the file with the same name is updated inside longhorn/longhorn repo?

**Comment by innobead** [comment]
> Do we want to watch this [longhorn-images.txt](https://github.com/longhorn/longhorn-manager/blob/dd8e20c76dcd740db4301f3e37cb314e15a01b5e/deploy/longhorn-images.txt#L1-L5) file inside longhorn/longhorn-manager repo instead because it will be updated first before the file with the same name is updated inside longhorn/longhorn repo?

Good idea :+1: 

@yangchiu Let's enhance this later, but create another ticket to track. Thank you.

**Comment by yangchiu** [comment]
> > Do we want to watch this [longhorn-images.txt](https://github.com/longhorn/longhorn-manager/blob/dd8e20c76dcd740db4301f3e37cb314e15a01b5e/deploy/longhorn-images.txt#L1-L5) file inside longhorn/longhorn-manager repo instead because it will be updated first before the file with the same name is updated inside longhorn/longhorn repo?
> 
> Good idea +1
> 
> @yangchiu Let's enhance this later, but create another ticket to track. Thank you.

[#3914](https://github.com/longhorn/longhorn/issues/3914) has been created for this.

**Comment by yangchiu** [comment]
The jenkins pipeline has been implemented: https://ci.longhorn.io/job/private/job/mirror-csi-images/
