### ISSUE TITLE
[BUG] Helm installation with privateRegistry.registryUrl set doesn't work

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3057]
**Describe the bug**

Now that we add the `k8s.gcr.io registry` url into the image, [link](https://github.com/longhorn/longhorn/blob/84d2f4891204cd5fae32735482c9f65eaa49e3ad/chart/values.yaml#L30). When user set `privateRegistry.registryUrl=my_prevate_registry.com`, the rendered yaml for driver deployer [here](https://github.com/longhorn/longhorn/blob/84d2f4891204cd5fae32735482c9f65eaa49e3ad/chart/templates/deployment-driver.yaml#L52) will be `my_prevate_registry.com/k8s.gcr.io/sig-storage/csi-attacher` This is invalid.

**To Reproduce**
1. Publish Longhorn images to private registry, `my_prevate_registry.com` using the script https://github.com/longhorn/longhorn/blob/master/scripts/load-images.sh
2. Install Longhorn using Helm with `privateRegistry.registryUrl=my_prevate_registry.com`
3. Installation fails

**Environment:**
 - Longhorn version: v1.2.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm

**Comment by PhanLe1010** [comment]
**Workaround:**

Set the `csi.xxx.repository=longhornio/xxx` when install Longhorn using Helm. The rendered image path will be `my_prevate_registry.com/longhornio/xxx`

**Comment by innobead** [comment]
@PhanLe1010 you also need to update images info in manifests files in longhorn/longhorn, longhorn/longhorn-manager if needed.

**Comment by innobead** [comment]
@PhanLe1010 is this still an issue?

@chriscchien can you double check this? thanks.

cc @longhorn/qa

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn `963ccf`)

In longhorn v1.2.0, install longhorn by helm with private registry `ec2-3-238-79-244.compute-1.amazonaws.com：5000` , csi image download path will become `ec2-3-238-79-244.compute-1.amazonaws.com:5000/k8s.gcr.io/sig-storage/csi-resizer:v1.2.0` make the installation failed
```
  Normal   Scheduled  18s               default-scheduler  Successfully assigned longhorn-system/csi-resizer-866cd94fc5-pqgcj to ip-172-31-36-32
  Normal   BackOff    18s               kubelet            Back-off pulling image "ec2-3-238-79-244.compute-1.amazonaws.com:5000/k8s.gcr.io/sig-storage/csi-resizer:v1.2.0"
  Warning  Failed     18s               kubelet            Error: ImagePullBackOff
  Normal   Pulling    7s (x2 over 19s)  kubelet            Pulling image "ec2-3-238-79-244.compute-1.amazonaws.com:5000/k8s.gcr.io/sig-storage/csi-resizer:v1.2.0"
  Warning  Failed     7s (x2 over 19s)  kubelet            Failed to pull image "ec2-3-238-79-244.compute-1.amazonaws.com:5000/k8s.gcr.io/sig-storage/csi-resizer:v1.2.0": rpc error: code = NotFound desc = failed to pull and unpack image "ec2-3-238-79-244.compute-1.amazonaws.com:5000/k8s.gcr.io/sig-storage/csi-resizer:v1.2.0": failed to resolve reference "ec2-3-238-79-244.compute-1.amazonaws.com:5000/k8s.gcr.io/sig-storage/csi-resizer:v1.2.0": ec2-3-238-79-244.compute-1.amazonaws.com:5000/k8s.gcr.io/sig-storage/csi-resizer:v1.2.0: not found
  Warning  Failed     7s (x2 over 19s)  kubelet            Error: ErrImagePull
```
In longhorn master(v1.6.0-dev), use the same private registry, install longhorn by helm success.
