### ISSUE TITLE
node issues deleted /var/lib/longhorn [QUESTION]

### ISSUE THREAD

**Issue by dpstratascale** [longhorn/longhorn#3058]
**Question**

Hello, 

Our node memory was full and the node itself stopped working due to disk pressure.
In the end, the only way to fix it was to rm -rf the folder /var/lib/longhorn.
(before doing that all the pv and pvc were deleted) 
The problem now is that longhorn cannot schedule the node anymore.
The allocated amount is a negative number 0 / -42.32 Gi and the scheduled replicas are 0.

The other two nodes are healthy.

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes version: 1.20.6
 - Node config
   - OS type and version ubuntu 18.04
   - CPU per node: 40 
   - Memory per node: 109 Gb
   - Disk type ssd
   - Network bandwidth and latency between the nodes: N/A 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Additional context**

**Comment by dpstratascale** [comment]
I fixed the issue by cordoning-draining-deleting-restarting the node and when it was automatically added back the daemonset fixed the issue with the storage.

**Comment by jenting** [comment]
Since Longhorn storage some metadata inside the `/var/lib/longhorn`. Removes all the files would make the metadata missing either.
Deleting the node and restart would make Longhorn create the fresh new metadata back.
