### ISSUE TITLE
[BUG] The backing image file reuse will fail forever if there is an invalid file in the work directory 

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3061]
**Describe the bug**
If all nodes/backing image manager pods crash and the data in a backing image file somehow becomes corrupted, when this file is the 1st one that gets picked and reused, the backing image manager will loop in file reuse failure and retry. The backing image in this disk can never become ready.

**To Reproduce**
1. Create a backing image file.
2. Launch a volume using the backing image file so that there are 2 disk records for the backing image.
3. Modify one disk file for the backing image and make sure the file size is not changed. This will lead to data inconsistency/corruption later. e.g.,
```
root@shuo-cluster-worker-2:/# echo test > /var/lib/longhorn/backing-images/bi-test-5cea928b/backing 
root@shuo-cluster-worker-2:/# truncate -s 500M /var/lib/longhorn/backing-images/bi-test-5cea928b/backing
```
4. Remove another disk file then crash backing image manager processes for both files immediately.

**Expected behavior**
The backing image file should be resynced after pod restart.

**Log**
```
2021-09-23T08:31:48.870162525Z time="2021-09-23T08:31:48Z" level=warning msg="Dropping Longhorn backing image longhorn-system/image-cql6j out of the queue: fail to sync backing image for longhorn-system/image-cql6j: failed to sync backing image file state: BUG: backing image recorded checksum 1050a8ccbaa72d552b72660ed9c43460fb75dc198b1802d0332e5ee6eb5cfb37dce9ac75a7af9b8b06021aad6e383051027d071e2809aff4111f8779185972d7 doesn't match the file checksum 40d883b86625e48ce0bab91f7f70935cca6d2d7f73be0e0b804d1d384dab98f41a676a1d787e966d11ac00876db6b240fa996310794bfa0d4d378b050b7bc4a0 in disk 3af17a6d-c8ea-4b21-8da0-adeeb09e568d"
```

**Environment:**
 - Longhorn version: v1.2.2

**Comment by shuo-wu** [comment]
Workaround:
1. Figure out which backing image manager the invalid file is in
2. Enter into the backing image manager pod.
3. Remove the work directory of the backing image. The path should be `/data/backing-images/<backing image name>-<a random suffix, which is actually backing image UUID>`
4. Wait for backing image resync to happen in this backing image manager pod.

**Comment by kaxing** [comment]
Validation: **PASSED**

Testing with master image(20211103).

Now when backing image disk files is corrupted or with additional file under the same directory, backing image will not stuck in restarting itself.

Additionally, while cleaning up unuse backing image will also remove all those unwanted files.

Also, in an extreme case, if manually modified all backing-image disk files inside each backing-image-manager, will causing volume remain in degraded since the replica cannot be rebuild due to backing image mismatch the checksum.
```kubetail
[longhorn-manager-ljs42] E1103 09:12:14.202948       1 backing_image_controller.go:152] fail to sync backing image for longhorn-system/bi-test: failed to sync backing image file state: BUG: found mismatching size 805306368 reported by backing image manager backing-image-manager-c00e-c773 in disk c773948f-44e1-4770-aef8-50016c66e171, the size recorded in status is 2162688
[longhorn-manager-ljs42] time="2021-11-03T09:12:14Z" level=warning msg="Dropping Longhorn backing image longhorn-system/bi-test out of the queue: fail to sync backing image for longhorn-system/bi-test: failed to sync backing image file state: BUG: found mismatching size 805306368 reported by backing image manager backing-image-manager-c00e-c773 in disk c773948f-44e1-4770-aef8-50016c66e171, the size recorded in status is 2162688"
```

**Comment by shuo-wu** [comment]
> Also, in an extreme case, if manually modified all backing-image disk files inside each backing-image-manager, will causing volume remain in degraded since the replica cannot be rebuild due to backing image mismatch the checksum.
> 
> ```
> [longhorn-manager-ljs42] E1103 09:12:14.202948       1 backing_image_controller.go:152] fail to sync backing image for longhorn-system/bi-test: failed to sync backing image file state: BUG: found mismatching size 805306368 reported by backing image manager backing-image-manager-c00e-c773 in disk c773948f-44e1-4770-aef8-50016c66e171, the size recorded in status is 2162688
> [longhorn-manager-ljs42] time="2021-11-03T09:12:14Z" level=warning msg="Dropping Longhorn backing image longhorn-system/bi-test out of the queue: fail to sync backing image for longhorn-system/bi-test: failed to sync backing image file state: BUG: found mismatching size 805306368 reported by backing image manager backing-image-manager-c00e-c773 in disk c773948f-44e1-4770-aef8-50016c66e171, the size recorded in status is 2162688"
> ```

If all files of a downloaded backing image used by one volume are corrupted, Longhorn will re-start the downloading after `Backing Image Recovery Wait Interval` is passed. Then everything will be recovered automatically
