### ISSUE TITLE
[BUG] 'Upgrade Engine' still shows up in a specific situation when engine already upgraded

### ISSUE THREAD

**Issue by kaxing** [longhorn/longhorn#3063]
**Describe the bug**
Option to Upgrade Engine image will still shows up, cannot identify the exact situation but there is a particular volume is in degraded state.

**To Reproduce**

Following [test case: Upgrade Conflict Handling test](https://longhorn.github.io/longhorn-tests/manual/pre-release/upgrade/upgrade-conflict-handling/)
Then upgrade the Engine Image for each volume.

**Expected behavior**
Upgrade Engine option shouldn't display for volume with latest image version. 

**Log**
[longhorn-support-bundle_1157b1ba-ee5a-4670-a7ed-be84c63e9513_2021-09-24T09-39-14Z.zip](https://github.com/longhorn/longhorn/files/7224729/longhorn-support-bundle_1157b1ba-ee5a-4670-a7ed-be84c63e9513_2021-09-24T09-39-14Z.zip)

| Engine Image already upgrade to master-head | No Engine Image to choose from |
| - | - |
| ![image](https://user-images.githubusercontent.com/602540/134655754-498cfa8f-7ceb-4382-b0da-0643bb20ee3b.png) |  ![image](https://user-images.githubusercontent.com/602540/134655790-b2aab7da-13ba-4a68-819f-15b70be94a82.png) |

**Environment:**
 - Longhorn version: v1.2.1-rc1 to master-head (20210924-3pm)
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher 2.5
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 1.19.11
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 30
 - Node config
   - OS type and version: Ubuntu
   - CPU per node: 2
   - Memory per node: 8
   - Disk type(e.g. SSD/NVMe):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): EC2
 - Number of Longhorn volumes in the cluster: 100+ in total

**Additional context**
When Engine Image shows up from upgrade option there will be error shown:
```text
cannot upgrade engine for volume pvc-e155d5c1-3409-4911-a8d3-90575a6968fa using image longhornio/longhorn-engine:master-head: cannot upgrade engine image for volume pvc-e155d5c1-3409-4911-a8d3-90575a6968fa from image longhornio/longhorn-engine:v1.2.1-rc1 to image longhornio/longhorn-engine:master-head because the engine image longhornio/longhorn-engine:master-head is not deployed on the replicas' nodes or the node that the volume is attached to
```

**Comment by PhanLe1010** [comment]
@kaxing Do you still have the env? Can I see it?

**Comment by PhanLe1010** [comment]
I check the volume `pvc-971d9a77-fd09-4512-9807-2808d363c39a` in the support bundle, it seems that the volume finished engine upgrade. It could be UI is lagged behind. The `Engine Upgrade` option should be disable in the UI

**Comment by PhanLe1010** [comment]
This error is fine. It is the transient state
```
cannot upgrade engine for volume pvc-e155d5c1-3409-4911-a8d3-90575a6968fa using image longhornio/longhorn-engine:master-head: cannot upgrade engine image for volume pvc-e155d5c1-3409-4911-a8d3-90575a6968fa from image longhornio/longhorn-engine:v1.2.1-rc1 to image longhornio/longhorn-engine:master-head because the engine image longhornio/longhorn-engine:master-head is not deployed on the replicas' nodes or the node that the volume is attached to
```

**Comment by jleni** [comment]
I've had this problem in some nodes for several days... 
How can I force the image to be available?

**Comment by jleni** [comment]
Related question/issue https://github.com/longhorn/longhorn/issues/3072

**Comment by PhanLe1010** [comment]
Thanks @kaxing for reporting

This look like a minor UI issue. More specifically, UI should disable the `engine upgrade` is there is no option in the shown drop down. 

Do you observe this problem with Longhorn v1.2.0? @kaxing

**Comment by PhanLe1010** [comment]
@kaxing After the step 5, did you try to set `Concurrent Automatic Engine Upgrade Per Node Limit` to 2 or 3 ?

**Comment by kaxing** [comment]
@PhanLe1010 I keep all the settings in default until the version that I want to verify. In this case is v1.2.1-rc2.

**Comment by PhanLe1010** [comment]
I see. Yeah, we know that the problem exist in Longhorn v1.2.1-rc2. I would like to know if Longhorn 1.1.2 and Longhorn 1.2.0 has this problem. Can you try to:
1. Install Longhorn 1.1.1
1. Upgrade to Longhorn 1.1.2
1. Set `Concurrent Automatic Engine Upgrade Per Node Limit` to 2. Verify if the problem exist
1. Upgrade to Longhorn 1.2.0. Wait for auto engine upgrade to finish
1. Verify if the problem exist

**Comment by PhanLe1010** [comment]
Update: We see this problem in 1.2.0 also. Thanks @kaxing for helping with the test

**Comment by smallteeths** [comment]
The UI has a check that disables the "Upgrade Engine" operation when there is only one engine and it is the current engine of the volume. I'm not sure if it's an issue with the UI. @PhanLe1010 

<img width="1098" alt="截屏2023-05-15 上午9 59 03" src="https://github.com/longhorn/longhorn/assets/27733391/73c955a8-2f4a-4b05-ad94-73007f7187ef">

**Comment by PhanLe1010** [comment]
Update: I am retrying to reproduce to see if the issue still exists

**Comment by innobead** [comment]
Moved out from 1.5, since it's rare.

**Comment by PhanLe1010** [comment]
Update: This is easy to reproduce by:

1. Deploying Longhorn 1.5.0-rc1 (also works in other versions)
1. Create a volume and attach it. Set `Concurrent Automatic Engine Upgrade Per Node Limit` to 1
1. Use Longhorn UI to deploy an older engine image, e.g., `v1.4.1`
1. Go to the volume detail page and see that UI still allows show  option to upgrade engine even though there is no way to upgrade it
    ![Screenshot from 2023-06-02 11-52-46](https://github.com/longhorn/longhorn/assets/22139961/9b16bb20-84e2-41c5-ba4c-1a271bd20fbe)
1. The volume list page doesn't have this issue 
    ![Screenshot from 2023-06-02 11-54-02](https://github.com/longhorn/longhorn/assets/22139961/fb29861d-766a-43f2-8c1b-6f4d60b11e2a)

@smallteeths could you check the code of the volume detail page? I am highly confident that this is an UI problem

**Comment by weizhe0422** [comment]
## Environment
  - Longhorn version: v1.5.0 with master-branch (https://hub.docker.com/layers/longhornio/longhorn-manager/master-head/images/sha256-669e1fb30b9273c1bb2773cc6e444fd602606e3d590e305fb480376154fe2768?context=explore) 
<img width="442" alt="截圖 2023-06-08 上午10 44 57" src="https://github.com/longhorn/longhorn/assets/17548901/dd1fe01f-5c57-4332-bec3-96888c6d4354"><img width="1035" alt="截圖 2023-06-08 上午10 42 51" src="https://github.com/longhorn/longhorn/assets/17548901/836cfac0-3b4e-46b1-9d18-1c45045596f3">

  - cluster info
    - K8S version: v1.25.9 +rke2r1
    - master*1 + worker*3
      <img width="1358" alt="截圖 2023-06-08 上午10 46 27" src="https://github.com/longhorn/longhorn/assets/17548901/12a86217-a321-4eaa-94e0-805cb19ca52b">
 
 ## Test steps: PASS
 ### Scenario 1: Deploy old version engine image
 1. Install Longhorn with command: `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml`
 2. Create a attached volume
    <img width="1216" alt="截圖 2023-06-08 上午10 51 41" src="https://github.com/longhorn/longhorn/assets/17548901/b90cf799-e236-492e-baf2-f25efe1fa0bb">
 3. Deploy old version engine image: v1.5.0-rc1
    <img width="1211" alt="截圖 2023-06-08 上午10 50 18" src="https://github.com/longhorn/longhorn/assets/17548901/5d1300f8-1040-46c9-b90f-e47374ac2f08">
 4. Verify the "Upgrade Engine" option won't be enabled no matter either from volume list page or volume detail page.
    - volume list page
      <img width="1258" alt="截圖 2023-06-08 上午10 54 52" src="https://github.com/longhorn/longhorn/assets/17548901/a2cb3699-5a9f-416c-bbe8-875b7ad6e4c4">
    - volume detail page
      <img width="1245" alt="截圖 2023-06-08 上午10 55 37" src="https://github.com/longhorn/longhorn/assets/17548901/dd61183d-cf77-4b53-94e1-f8f60e9e84ed">

**Comment by innobead** [comment]
Thanks @weizhe0422 this is good.
