### ISSUE TITLE
[QUESTION] How to deal with volumes that point to the wrong head?

### ISSUE THREAD

**Issue by jaysonsantos** [longhorn/longhorn#3066]
**Question**
I have a node that stays at home and sometimes the internet get somewhat unstable to the point where longhorn gets a bit shaky. After a few rounds fixing a few volumes that I had to manually run fsck on the `.img` files, I got to a stable point, but only one of the modules are pointed to the wrong head.  Should I simply edit `volume.meta` to point to the right one?
If you check the following image, you see that the snapshot that starts with 4a91 is the right one and the others do not have anything that points to it.
![image](https://user-images.githubusercontent.com/51510/134704812-d1b5eaf6-5d07-4a53-bf92-50a28af189f5.png)

and on the UI the right one shows as deleted as you can see here (so close but so far)
![image](https://user-images.githubusercontent.com/51510/134704947-6950f01b-a32f-4445-964b-00031f0f3f32.png)

**Environment:**
 - Longhorn version: 1.2.0
 - Kubernetes version: k3s v1.22.2+k3s1
 - Node config
   - OS type and version: Ubuntu 20.04.3 LTS
   - CPU per node: 16
   - Memory per node: 24
   - Disk type: ReadWriteOnce Block Device
   - Network bandwidth and latency between the nodes: still figuring out mtu problems between home and main servers on the cloud
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): home is a baremetal and cloud a provider (contabo with a lot of cpu steal)

**Additional context**
Let me know and I can upload the pack encrypted to age to your public keys on github

**Comment by jenting** [comment]
Related to #685

**Comment by jenting** [comment]
I think it's the correct behavior.

You could check the files sequentially: volume.meta -> volume-head-003.img.meta -> volume-snap-5d4495a0-xxx.img.meta -> volume-snapshot-4a91f004-xxx.meta:
- the volume.meta Head is `volume-head-003.img`
- the volume-head-003.img.meta Name is `volume-head-003.img`, Parent is `volume-snap-5d4495a0-xxx.img`
- the volume-snap-5d4495a0-xxx.img.meta Name is `volume-head-002.img`, Parent is `volume-snapshot-4a91f004-xxx.img`
- the volume-snapshot-4a91f004-xxx.img.meta Name is `volume-head-001.img`, Parent is ``

The hidden snapshot `4a91f004` is the system-generated snapshot. During replica rebuilding, Longhorn will take a snapshot first. So the snapshot `4a91f004` should not have `Delete` button on the GUI. The Longhorn system will automatically if you did not disable the `Automatically Cleanup System Generated Snapshot` on the setting page.

**Comment by jenting** [comment]
I'm going to close this issue, feel free to reopen it if there is any other question, thank you.
