### ISSUE TITLE
[BUG] Longhorn helm deployment -- recurringJobSelector format

### ISSUE THREAD

**Issue by SQLJames** [longhorn/longhorn#3067]
**Describe the bug**
When trying to create a recurringJob on the loghorn deployment using helm, the format inserted is processed wrong, and inserts "recurringJobSelector: 'map[cron:*/2 * * * * name:backup retain:1 task:backup]'" where the string actually lists the map. 

**To Reproduce**
Deploy this inside the values
```persistence:
  defaultClassReplicaCount: 3
  recurringJobSelector:
    enable: true
    jobList: 
    - name: backup
      task: backup
      cron: '*/1 * * * *'
      retain: 14
```
**Expected behavior**
New recurring job is created.

**Log**
failed to provision volume with StorageClass "longhorn": rpc error: code = InvalidArgument desc = invalid json format of recurringJobSelector: invalid character 'm' looking for beginning of value

**Environment:**
 - Longhorn version:v1.2.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k8s
   - Number of management node in the cluster: 1 
   - Number of worker node in the cluster: 6 
 - Node config
   - OS type and version: ubuntu 20.004
   - CPU per node: 4 cores - 6 cores
   - Memory per node: minimum 8 max 48
   - Disk type(e.g. SSD/NVMe): SSD and Nvme
   - Network bandwidth between the nodes: 1G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 18

**Comment by jenting** [comment]
Thanks for the reporting, it's an issue for the helm chart rendering the recurring job.

**Comment by jenting** [comment]
Oops, I just realized you're using Longhorn v1.2.0.
Start from Longhorn v1.2.0, the recurring job format in StorgeClass is changed. Ref to [doc](https://longhorn.io/docs/1.2.0/snapshots-and-backups/scheduling-backups-and-snapshots/#recurring-jobs-assignment-using-a-storageclass).

So, in your case, the `values.yaml` should be updated as:
```
recurringJobSelector:
    enable: true
    jobList: jobList: '[{"name":"backup", "isGroup":false}]'
```

And you need setup the recurring job by UI _or_ by kubectl. You could ref to the [doc](https://longhorn.io/docs/1.2.0/snapshots-and-backups/scheduling-backups-and-snapshots/#recurring-jobs-assignment-using-a-storageclass).

**Comment by jenting** [comment]
Please check your recurrjobJobSelector format since it's different from v1.1.x.

I'm going to close this issue. Feel free to reopen it if you have further questions.
