### ISSUE TITLE
[BUG] Longhorn-manager fails to come up on the node if there was only one replica running and the node rebooted.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3068]
**Describe the bug**
If there is a volume running with one replica and the node where the replica is running is rebooted, the longhorn-manager fails to come up.

**To Reproduce**
1. Restore a volume with one replica and attach to a statefulSet pod.
2. Reboot the node where the replica is running.
3. Check the the longhorn node page, the node stay in down state.
4. The longhorn-manager fails to come on the node.
<img width="1752" alt="Screen Shot 2021-09-25 at 10 37 39 PM" src="https://user-images.githubusercontent.com/60111667/134795103-789fc6d3-8326-4e26-8d40-4a6967f7e17d.png">

**Expected behavior**
The longhorn-manager should come up on the node once the node is up.

**Log**
```
time="2021-09-26T05:26:47Z" level=fatal msg="Error starting manager: upgrade CRD failed: upgrade from v1.1.1 to v1.2.0: UpgradeCRs failed: upgrade volume failed: upgradeLabelsForVolume failed: failed to add label for volume restore-1 during upgrade: Operation cannot be fulfilled on volumes.longhorn.io \"restore-1\": the object has been modified; please apply your changes to the latest version and try again"
```

[longhorn-support-bundle_5d1760bd-e24c-4066-97fc-a703a9ded701_2021-09-26T05-29-11Z.zip](https://github.com/longhorn/longhorn/files/7230793/longhorn-support-bundle_5d1760bd-e24c-4066-97fc-a703a9ded701_2021-09-26T05-29-11Z.zip)

**Environment:**
 - Longhorn version: v1.2.1-rc2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

**Comment by khushboo-rancher** [comment]
After I deleted the problematic volume , the longhorn-manager was able to come up.

**Comment by shuo-wu** [comment]
Based on the error info and the implementations, this issue is caused by the blind update for restore/DR volumes during the upgrade. I tried to launch a restore volume with 1 replica. Then restarting the node the volume engine or the only replica is on can not trigger this bug in my private cluster. As a result, I cannot test the fix PR.

**Comment by innobead** [comment]
> Based on the error info and the implementations, this issue is caused by the blind update for restore/DR volumes during the upgrade. I tried to launch a restore volume with 1 replica. Then restarting the node the volume engine or the only replica is on can not trigger this bug in my private cluster. As a result, I cannot test the fix PR.
> 
> To get rid of this kind of upgrade failure caused by update conflicts, as I mentioned in #2582, we may need to re-design the upgrade path including version identification. We can track the enhancement in that ticket.

@khushboo-rancher could you always reproduce? maybe need you to verify the fix in the head to see if this issue is fixed.

**Comment by khushboo-rancher** [comment]
This is not reproducible all the time.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn v1.2.x-rc2 and longhorn-laster `09/27/2021`

Validation - **Pass**

I was able to reproduce the problem again in 1 out of 6 attempt. Ran the same steps for 11 times with the fix and observe no issue.
