### ISSUE TITLE
[BUG] DR volume even after activation remains in standby mode if there are one or more failed replicas.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3069]
**Describe the bug**
DR volume even after activation remains in standby mode if there are one or more failed replicas.

**To Reproduce**
1. Create a DR volume from a backup.
2. While DR is restoring, delete an instance-manager-r of one of the replica.
3. Wait for completion of the restore.
4. Now, DR volume has 1 failed replica and 3 healthy replicas.
5. Activate the DR volume.
6. Observe the DR volume state is not ready for workload.
7. Try to create PVC/PV using GUI, it fails saying `level=error msg="Error in request: cannot create PV for standby volume`

**Expected behavior**
On activation of the DR volume if the volume have one or more healthy replica, it should be ready for the workload.

**Environment:**
 - Longhorn version: v1.2.1-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

**Comment by shuo-wu** [comment]
Here, the volume gets stuck in activating state / activation can not be done due to [the error replica](https://github.com/longhorn/longhorn-manager/blob/73cd068491a48438ee75ca4f945faed170d051d4/controller/volume_controller.go#L2619-L2622).

**Comment by shuo-wu** [comment]
Workaround: Manually delete all failed replicas for DR volumes.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 705e770) by following steps:

1. Create volume, write some data and create backup.
2. Create DR volume from the backup.
3. During DR volume restoration, shut down a node, so there's a failed replica, but the restoration can still complete.
4. The DR volume can be activated and ready for workload even though there's a failed replica.
5. Create a workload to use this activated DR volume, the data is intact and able to read/write without problems.
