### ISSUE TITLE
[QUESTION] How to force an engine image to be accessible?

### ISSUE THREAD

**Issue by jleni** [longhorn/longhorn#3072]
After upgrading to longhorn 1.2.0 some of our nodes log the following:

```
CheckEngineImageReadiness: nodes [xxxxxx-infra1] don't have the engine image longhornio/longhorn-engine:v1.2.0"
```

When a pod is scheduled to these nodes, they cannot attach volumes, etc. All other nodes have upgraded correctly to 1.2.0

**Question**

**Environment:**
 - Longhorn version: 1.2.0
 - Kubernetes version: 1.20.11
 - Node config
   - OS type and version
   - CPU per node: 8
   - Memory per node: 16
   - Disk type NVMe
   - Network bandwidth and latency between the nodes: very low
 - Underlying Infrastructure (Rancher / RKE):

**Comment by PhanLe1010** [comment]
@jleni 

You can check the pod `engine-image-ei-xxx` on the node `[xxxxxx-infra1]` to see why it cannot become running. Is there any resource exhaustion or taint on the node?

**Comment by jenting** [comment]
Please check the engine image Pods are in a running state on these nodes.
You could first check the `engine-image-ei-xxx` DaemonSet under the longhorn-system namespace first.
And then check the corresponding `engine-image-ei-xxx-yyy` Pods.

**Comment by jenting** [comment]
Any updates on this one @jleni?

**Comment by jleni** [comment]
No, sorry, we just downgraded. There were other problems with v1.2.0 and we decided it was to risky at that point in time. 
We can probable close this issue.
Thanks!
