### ISSUE TITLE
[QUESTION] /var/lib/longhorn/replicas contains replicas  I  didn't expect

### ISSUE THREAD

**Issue by docbobo** [longhorn/longhorn#3074]
**Question**
Two of my nodes just went into `Unschedulable` state due to  insufficient disk space. Given that one of the nodes just contains 5 volumes, I was a little puzzled.  Add to that the fact that the allocated diskspace is 100GB less than the Used Space.

When looking at the content  of  `/var/lib/replicas`, I noticed the following two directories:

* mariadb-0-3e4f9a7b
* mariadb-0-f4a47086

The volume those replicas would belong to doesn't have any replica on the particular host though.  Is this as expected? If not, what's the best way to clean this up?

**Environment:**
 - Longhorn version: 1.2.0
 - Kubernetes version: 1.21
 - Underlying Infrastructure: Baremetal

**Comment by jenting** [comment]
I suspect that the mariadb do application replica also, right?
If yes, the second directory replica is created by Longhorn.

**Comment by jenting** [comment]
And could you please summarize the total size of these 5 volumes?
And what's the setting of `Storage Minimal Available Percentage` and `Storage Over Provisioning Percentage`?

**Comment by docbobo** [comment]
Yes, this totally sounds like #685 - So i'll refrain from adding additional information here.
