### ISSUE TITLE
[BUG] secret 'xxx' not found when backups ared being pulled from the target

### ISSUE THREAD

**Issue by kaxing** [longhorn/longhorn#3075]
**Describe the bug**
![image](https://user-images.githubusercontent.com/602540/134904616-cb3f4118-bee3-4074-a5d7-89974f95b504.png)

**To Reproduce**
// with an existing backup target had more than 100 volumes
1. Go to 'Settings'
2. Set up Backup Target to S3 and it's credential
3. Go to 'Backups'

**Expected behavior**
'secret xxx not found' warning shouldn't be showing even when the backups are being downloaded. 

**Log**
from `v1/backuptargets`,
```json
{
    "data":
    [
        {
            "actions":
            {},
            "available": false,
            "backupTargetURL": "s3://xxxx@xxx-x/",
            "credentialSecret": "xxx-secret",
            "id": "default",
            "links":
            {
                "self": "http://xx.xxx.xx.xxx/v1/backuptargets/default"
            },
            "message": "secret \"aws-secret\" not found",
            "pollInterval": "5m0s",
            "type": "backupTarget"
        }
    ],
    "links":
    {
        "self": "http://1xx.xxx.xx.xxx/v1/backuptargets"
    },
    "resourceType": "backupTarget",
    "type": "collection"
}
```

**Environment:**
 - Longhorn version: v1.2.1-rc1, v1.2.1-rc2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

**Comment by jenting** [comment]
Similiar to https://github.com/longhorn/longhorn/issues/2944#issuecomment-908569336

**Comment by innobead** [comment]
@cchien816 Could you help check if this is still a valid issue? Thanks.

**Comment by cchien816** [comment]
**Verified on longhorn-manager master-head `70203d`
Result : Can reproduce**

Steps
1. Deploy Longhorn and prepare backupstore with nfs and s3
2. Setup Longhorn backupstore to s3
3. Create more than 100 volumes
4.  Attach them and write some date to some volumes
5. Create backup and navigate to backup page
7. Switch longhorn backupstore to nfs and navigate to backup page then set  backupstore to s3
8. Navigate to backup page again
9. Can see 'secret xxx not found' message, but **immediately** backup list in s3 displayed on UI

Additional
If volume number are not huge,  can not reproduce this issue

**Comment by innobead** [comment]
@cchien816 Thanks 👍 . So, basically, in the end, the error message will be gone, and listing backups is working as well, correct?

**Comment by cchien816** [comment]
> @cchien816 Thanks +1 . So, basically, in the end, the error message will be gone, and listing backups is working as well, correct?

Yes the error message will be gone soon and backupsore still working properly

**Comment by innobead** [comment]
Thanks, then I don't think this is a problem anymore, but rather an effect/result caused by our asynchronous mechanism.
