### ISSUE TITLE
[BUG] Cannot migrate replicas in an evicting disk to a new disk on the same node when the node level hard affinity is applied.

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3076]
**Describe the bug**
This issue (adding a new disk then evicting the old disk on the same node) is similar to https://github.com/longhorn/longhorn/issues/1400 (migrate replicas to another disk of the same node) but they are not identical. 
For example, when the node level soft anti-affinity is disabled, the user just wants to evict an old disk but does not matter the migration destination / there is no enough space in the other disks of the node, some volume can migrate the replicas to other nodes as long as there is no peer replicas on those nodes. 

**To Reproduce**
1. Disable the setting `Replica Node Level Soft Anti-affinity`
2. Create some volumes. Make sure there is a replica on each worker node.
3. Add a new schedulable disk to a node.
4. Disable the scheduling then Enable eviction for the old disk on the same node.
5. All replicas will be not migrated to the new disk.

**Expected behavior**
All replicas should be migrated to the new disk.

**Log**

**Environment:**
 - Longhorn version: v1.2.1-rc2

**Comment by PhanLe1010** [comment]
Test Steps:

#### Case 1: Evicting disk
1. Disable the setting `Replica Node Level Soft Anti-affinity`
2. Create some volumes. Make sure there is a replica on each worker node.
3. Add a new schedulable disk to a node.
4. Disable the scheduling then Enable eviction for the old disk on the same node.
5. Verify that the replicas on the old disk move to the new disk

#### Case 2: Retest evicting node

#### Case 3: Since this PR refactor the replica scheduling logic, we need to double check the replica scheduling behavior in all cases:
| `Replica Node Level Soft Anti-Affinity`  | `Replica Zone Level Soft Anti-Affinity`  |
| --- | --- |
| ON | ON |
| ON | OFF |
| OFF | ON |
| OFF | OFF |

**Comment by innobead** [comment]
> Test Steps:
> 
> #### Case 1: Evicting disk
> 1. Disable the setting `Replica Node Level Soft Anti-affinity`
> 2. Create some volumes. Make sure there is a replica on each worker node.
> 3. Add a new schedulable disk to a node.
> 4. Disable the scheduling then Enable eviction for the old disk on the same node.
> 5. Verify that the replicas on the old disk move to the new disk
> 
> #### Case 2: Retest evicting node
> #### Case 3: Since this PR refactor the replica scheduling logic, we need to double check the replica scheduling behavior in all cases:
> `Replica Node Level Soft Anti-Affinity`	`Replica Zone Level Soft Anti-Affinity`
> ON	ON
> ON	OFF
> OFF	ON
> OFF	OFF

Also the test cases of `replica auto rebalance` needed to be covered in the regression.

**Comment by innobead** [comment]
ref: https://github.com/longhorn/longhorn/issues/2141

**Comment by innobead** [comment]
@PhanLe1010 please also come out the test skeleton for this new test case in longhorn/longhorn-tests. Thanks.

**Comment by meldafrawi** [comment]
Validation: **Partially Failed**

Longhorn version: v1.2.3-rc1

Case 1: Evicting disk

1. Disable the setting `Replica Node Level Soft Anti-affinity`
2. Create some volumes. Make sure there is a replica on each worker node.
3. Add a new schedulable disk to a node.
4. Disable the scheduling then Enable eviction for the old disk on the same node.
5. Verify that the replicas on the old disk move to the new disk

> Replica moved to the new disk, but volumes state changed from `attached` to `detached`.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn version: `master`  / 2021-12-03
