### ISSUE TITLE
[BUG] Update the default advertised CSI version to csi version 1.2

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#3079]
**Describe the bug**
[Kubernetes >= v1.17](https://kubernetes-csi.github.io/docs/kubernetes-changelog.html#breaking-changes-1) no longer supports csi version v0.3
We updated the components and the min kubernetes version but did not change the default advertised csi version

The relevant code needs to be changed here: https://github.com/longhorn/longhorn-manager/blob/0cf54c5c79dbc5b91a3bb31bad25fbd0ecd61b94/app/csi.go#L36

**Environment:**
 - Longhorn version: v1.1.3 and v1.2.x

**Additional context**
We should be safe to advertise at least https://github.com/container-storage-interface/spec/releases/tag/v1.2.0
There is some newer abilities in the newer versions that we are not yet taking advantage off.
We might want to implement ListVolumes which is used for attachment verification after the volume-controller refactor for v1.3

**Comment by joshimoo** [comment]
I would consider including this change in v1.1.3 as well.

**Comment by PhanLe1010** [comment]
Thanks @joshimoo for reporting 

I think this is not an issue in term of functionality. I think the version we see at [link](https://github.com/longhorn/longhorn-manager/blob/0cf54c5c79dbc5b91a3bb31bad25fbd0ecd61b94/app/csi.go#L36) is supposed to be the default  version of Longhorn CSI plugin (a.k.a same as Longhorn version). That variable is only used at this single [log command](https://github.com/longhorn/longhorn-manager/blob/0cf54c5c79dbc5b91a3bb31bad25fbd0ecd61b94/csi/manager.go#L23). It isn't used anywhere else.  We then use the the Longhorn version version to be the Longhorn CSI plugin version [here](https://github.com/longhorn/longhorn-manager/blob/0cf54c5c79dbc5b91a3bb31bad25fbd0ecd61b94/app/csi.go#L50) and [here](https://github.com/longhorn/longhorn-manager/blob/0cf54c5c79dbc5b91a3bb31bad25fbd0ecd61b94/csi/identity_server.go#L17)


In term of logging, yeah, this [log command](https://github.com/longhorn/longhorn-manager/blob/0cf54c5c79dbc5b91a3bb31bad25fbd0ecd61b94/csi/manager.go#L23) a bit confusing. We correct it to print out the correct Longhorn version.

I am not 100% sure but I think CSI Spec is just a [proto file ](https://github.com/container-storage-interface/spec/blob/master/csi.proto) and we don't advertise csi version. We instead advertise the CSI capabilities.

Regarding to `We might want to implement ListVolumes which is used for attachment verification after the volume-controller refactor for v1.3`, we can enable this feature by adding `ControllerServiceCapability_RPC_LIST_VOLUMES` to our controller server. I.e., 
```
func NewControllerServer(apiClient *longhornclient.RancherClient, nodeID string) *ControllerServer {
	return &ControllerServer{
		apiClient: apiClient,
		nodeID:    nodeID,
		caps: getControllerServiceCapabilities(
			[]csi.ControllerServiceCapability_RPC_Type{
				csi.ControllerServiceCapability_RPC_CREATE_DELETE_VOLUME,
				csi.ControllerServiceCapability_RPC_PUBLISH_UNPUBLISH_VOLUME,
				csi.ControllerServiceCapability_RPC_EXPAND_VOLUME,
				csi.ControllerServiceCapability_RPC_CREATE_DELETE_SNAPSHOT,
				csi.ControllerServiceCapability_RPC_CLONE_VOLUME,
				csi.ControllerServiceCapability_RPC_LIST_VOLUMES,
			}),
		accessModes: getVolumeCapabilityAccessModes(
			[]csi.VolumeCapability_AccessMode_Mode{
				csi.VolumeCapability_AccessMode_SINGLE_NODE_WRITER,
				csi.VolumeCapability_AccessMode_MULTI_NODE_MULTI_WRITER,
			}),
	}
}
```

**Comment by joshimoo** [comment]
@PhanLe1010 thanks for verifying that we don't actually use this field and therefore removing it :)

**Comment by PhanLe1010** [comment]
Test step:
Make sure Helm/Kubectl installation are ok

**Comment by khushboo-rancher** [comment]
Verified the kubectl installation - **LGTM**
