### ISSUE TITLE
[TASK] Check failed test cases in nightly automation build and fix

### ISSUE THREAD

**Issue by chanow816** [longhorn/longhorn#3081]
**What's the task? Please describe.**
Currently we have nightly build for automation test, including 275 test cases.
However there are some case fail need to analyze and fix

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] Analyze the root cause of each failed test case
- [x] Fix these failed automation case one by one

**Additional context**
Automation test result : https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-lh-tests-ubuntu-amd64/12/testReport/

**Status** 
- [x] tests.test_backing_image.test_recurring_job_labels_with_backing_image
[Root cause](https://github.com/longhorn/longhorn/issues/3081#issuecomment-933993830)
- [x] tests.test_basic.test_allow_volume_creation_with_degraded_availability
[Root cause](https://github.com/longhorn/longhorn/issues/3081#issuecomment-933077285)
- [x] tests.test_basic.test_allow_volume_creation_with_degraded_availability_restore
[Root cause](https://github.com/longhorn/longhorn/issues/3081#issuecomment-933077285)
- [x] tests.test_basic.test_workload_with_fsgroup
v1.2.2 resloved this issue
- [x] tests.test_basic.test_multiple_volumes_creation_with_degraded_availability
Can not reproduce on local environment
- [x] tests.test_node.test_node_config_annotation_missing
fixed in PR [736](https://github.com/longhorn/longhorn-tests/pull/736)
- [x] tests.test_node.test_node_eviction
fixed in PR [736](https://github.com/longhorn/longhorn-tests/pull/736)
- [x] tests.test_node.test_node_config_annotation
fixed in PR [736](https://github.com/longhorn/longhorn-tests/pull/736)
- [x] tests.test_recurring_job.test_recurring_jobs_allow_detached_volume
Filed bug #3163
- [x] tests.test_node.test_replica_scheduler_no_disks
fixed in PR [736](https://github.com/longhorn/longhorn-tests/pull/736)
- [x] tests.test_ha.test_inc_restoration_with_multiple_rebuild_and_expansion
Can not reproduce on local environment
- [x] tests.test_rwx.test_rwx_with_statefulset_multi_pods
Not happen in recent nightly build and on my test environment
- [x] tests.test_rwx.test_rwx_multi_statefulset_with_same_pvc
Not happen in recent nightly build and on my test environment
- [x] tests.test_rwx.test_rwx_delete_share_manager_pod
Not happen in recent nightly build and on my test environment
- [x] tests.test_rwx.test_rwx_statefulset_scale_down_up
fixed in PR [740](https://github.com/longhorn/longhorn-tests/pull/740)

cc @longhorn/qa

**Comment by chanow816** [comment]
Inprogress:

> test_allow_volume_creation_with_degraded_availability

**Comment by chanow816** [comment]
***Failed test case : test_backing_image.py::test_recurring_job_labels_with_backing_image [NFS and s3]***

**Comment by jenting** [comment]
Use the newly created issue to track, close this one.
