### ISSUE TITLE
[BUG] Scalability issue of volumes in Longhorn

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3083]
**Describe the bug**

According to [the scalability benchmark for Longhorn v1.0.1](https://longhorn.io/blog/performance-scalability-report-aug-2020/#scalability) and [the scalability benchmark for Longhorn v1.2.0 ](https://github.com/longhorn/longhorn/issues/2986#issuecomment-923556546), Longhorn `v1.2.0` has worse scalability performance than Longhorn `v1.0.1`. 

In Longhorn `v1.0.1` the graph looks linear util 900 volumes. However, in `v1.2.0` the graph looks linear for the first 410 volumes and shoot up.

**Additional context**
Support bundle and Kubectl top are provided in the comment https://github.com/longhorn/longhorn/issues/2986#issuecomment-929751211

**Comment by joshimoo** [comment]
The biggest scalability issue that is currently present is the engine binary invocation which leads to many socket opening/closings in a short time frame. #2778 https://github.com/longhorn/longhorn/issues/2818#issuecomment-887865452

**Comment by innobead** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Main-Board-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/3083?planning-poker) with ZenHub @jenting @PhanLe1010 @shuo-wu @joshimoo

**Comment by shuo-wu** [comment]
The Longhorn installation part will be improved when the new design for https://github.com/longhorn/longhorn/issues/2582 is introduced. I will write down the design as a LEP once I start to work on it. In brief, before each manager pod becomes running, it needs to acquire the leadership and walk through all upgrade paths. This behavior greatly slows down the installation.

Once both this and the issues mentioned by Joshua are fixed, we can re-visit the scalability.

**Comment by PhanLe1010** [comment]
When recapping the Longhorn scalability issues, @yasker  and @shuo-wu  realized that both the recent backing-image related issue and the previous issues are caused by the controller work queues. We are thinking if the culprit of the unsolved v1.2.x scalability issue is the work queue either.

From @innobead 
> not sure if any builtin metrics we can leverage like queue usage or something

**Comment by joshimoo** [comment]
Just leaving a note here: I previously discussed the workqueue issue with @PhanLe1010 and asked him to see if he can expose the metrics, that come with the work queue, that should allow us to identify the culprits and cases that lead to long queue times. I further asked him to start his testing with a long resync period since the resync period currently hides issues as well as could lead to issues if the calls are not idempotent or the processing of all the resources takes longer than the resync period eventually.

The binary invocations which we are addressing in #3546 as well as some resource monitoring refactorings we need to do remove the resource modifications and eval out of the controller workers ref #2441 should reduce the time per resource eval loop in the controllers since at the moment their might be some slow operations which need to be done outside of the controller and only synced against the states, we did part of this for the new backup monitoring routines.

**Comment by PhanLe1010** [comment]
**Test plan:**
* Run e2e tests. This PR touches many operations in Longhorn.
* Run the scalability test to verify the improvement. The script is at https://github.com/longhorn/longhorn-tests/tree/master/scalability_test. See https://confluence.suse.com/display/LON/Scalability+issue+in+Longhorn+manager for examples.

**Comment by kaxing** [comment]
Validation Status Update:

Testing with master-head with non_io test from scale_test.py on 3+10 rke2 cluster with following steps:
1. scale up to 80 replicas per node
2. scale up again to 90 replicas per node
3. scale down to 0 replica per node

Pod-Time chart:
![master-head-90to0](https://user-images.githubusercontent.com/602540/157178922-9104e275-91a3-4843-81db-02fafb98a889.png)

Total workload:
![image](https://user-images.githubusercontent.com/602540/157178849-5d8cf6a5-cab3-4fb6-8cc9-c084ca93add5.png)

**Comment by kaxing** [comment]
Validation Result Update: io_1 test

With the same cluster setup from previous comment.
Statefulset workload can be steady scale up to 70 replicas:

Pod-Node chart:
![master-head-io_1_700](https://user-images.githubusercontent.com/602540/157205441-ae39a865-7b9e-476c-842b-426abf4083c8.png)

Workqueue chart:
![image](https://user-images.githubusercontent.com/602540/157205424-e25d8d20-4379-47b6-95eb-1aa1a5623e84.png)

**Comment by PhanLe1010** [comment]
The numbers are looking good. We are able to handle thousands of volumes now.
After this issue, the future improvement could be:
* Reduce the CPU utilization of manager pods while still allowing Longhorn to handle thousands of volumes.
* Longhorn UI is slowdown significantly pass a 1k volume point

**Comment by innobead** [comment]
> The numbers are looking good. We are able to handle thousands of volumes now. After this issue, the future improvement could be:
> 
> * Reduce the CPU utilization of manager pods while still allowing Longhorn to handle thousands of volumes.
> * Longhorn UI is slowdown significantly pass 1k volume point  -> Longhorn UI becomes the bottleneck at this scale

Let's track these action items in another following ticket.

**Comment by kaxing** [comment]
Plan to re-rerun the test once the rc1 image for v1.3.0 is out.

**Comment by kaxing** [comment]
Plan to rerun the test once the rc1 image for v1.3.0 is out.

**Comment by innobead** [comment]
Let's do this testing until RC1 is released because RC1 will include #3546  and this will make the communication between manager and engine process has one more hop (manager -> proxy -> engine process).

cc @c3y1huang @shuo-wu

**Comment by kaxing** [comment]
Validating with v1.3.0-rc2, the volumes for statefulset replicas can slowly build up but there is issue causing longhorn-manger pods crashing: #4056

Early test result with 20 nodes seems better compared to v1.3.0-rc1 with 10 nodes, this is a testing in-progress chart for reference:*
![io_1_70](https://user-images.githubusercontent.com/602540/171179059-6712a576-92db-4fdf-b026-6d9759742bb9.png)

<sup>* The test should be rerun with 10 nodes instead. </sup>

**Comment by kaxing** [comment]
Rerun the test with master-head* with 3+10 nodes, volume build up is slightly faster (~3000secs vs 3500secs+) but using slightly more memory(per %),

![image](https://user-images.githubusercontent.com/602540/171369287-f472c184-6649-4a36-bb13-9e0b029ea438.png)
![image](https://user-images.githubusercontent.com/602540/171368766-4af42815-73d0-4c67-b3a3-6d0c86ce673d.png)
<sup>* based on commit after v1.3.0-rc2, docker.io/longhornio/longhorn-manager@sha256:ddeb1194ad8bb6b436e37ac1bce07c0f62e3284fe47e3f0956abb12e704ee265</sup>

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with v1.3.0-rc2 image , longhorn-manager no longer slows down after 500 volumes.

---
Notes for QAs,


Test workload:
- deploy with scale-test.py: io_1, and non_io for reference
- initial sts replicas: 70

Node spec:
- instance type: m5.2xlarge
- node nubmer: 3 control nodes, 10 worker nodes
- gp3 volume with size in 1200G, iops = 6000, throughput = 250

**Comment by PhanLe1010** [comment]
This block has related content https://blog.upbound.io/scaling-kubernetes-to-thousands-of-crds/
