### ISSUE TITLE
[BUG] Volume rebuilds and deletes snapshots at the same time for several weeks

### ISSUE THREAD

**Issue by fynrup** [longhorn/longhorn#3086]
**Describe the bug**
After recognizing that one longhorn volumes actual size was more than double the "size" I looked into it and saw that many hidden snapshots were made. I deleted the last I could delete and since then it all began tearing apart. 

A few days later I removed one node from longhorn due to too little disk space and rescheduled the disks. I guess that this made it worse as currently the volume looks like this: 

![image](https://user-images.githubusercontent.com/60324367/135220951-da8d1d9a-bb16-44bf-90e7-260ddaae2a71.png)

![image](https://user-images.githubusercontent.com/60324367/135221057-dd5b553c-702f-4dc0-bba0-37800c69f8a7.png)

The actual size (currently >460) gets bigger and bigger and I cannot delete any replica as it gives the error below. 

![image](https://user-images.githubusercontent.com/60324367/135221206-b69e8cb4-9b3b-44db-a7cf-729e6b7a4c71.png)

I guess the main problem is that the snapshot deleting is "stuck" for several weeks now... What can I do?  I just had a full disk recently and don't need that again in the near future...

Supportbundle does not generate right now. I will attach it once it's finished generating.

**Environment:**
 - Longhorn version: v.1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: Linux Ubuntu 20.04.2 LTS
   - CPU per node: 20
   - Memory per node: 32 Gb
   - Disk type(e.g. SSD/NVMe): HDD
   - Network bandwidth between the nodes: _I can submit later if needed_
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 9

**Comment by jenting** [comment]
> Supportbundle does not generate right now. I will attach it once it's finished generating.

Please try to provide it if possible.

**Comment by fynrup** [comment]
@jenting can I send it via E-Mail as it possibly contains corporate details?

**Comment by jenting** [comment]
> @jenting can I send it via E-Mail as it possibly contains corporate details?

sure, please send to longhorn-support-bundle@suse.com

**Comment by fynrup** [comment]
> > @jenting can I send it via E-Mail as it possibly contains corporate details?
> 
> sure, please send to [longhorn-support-bundle@suse.com](mailto:longhorn-support-bundle@suse.com)

Just sent the E-Mail 👍🏼 thanks for your help

**Comment by jenting** [comment]
Received.

**Comment by fynrup** [comment]
![image](https://user-images.githubusercontent.com/60324367/135805750-6c03355e-a249-464b-be1b-7fa4f5d6378c.png)

After I deleted one replica on friday in order to free up disk space on one node the replica began rebuilding on another node. Since then the actual size grew to 494 GB.

**Comment by shuo-wu** [comment]
There are really tons of logs in the support bundle. I cannot even open and search some large files... 
With a brief glance at the volume, I found there were a lot of rebuilding happens on the volume. Some of the rebuilding retries were caused by too many snapshots in the volumes. But some of them were caused by a weird timeout error during rebuilding starting. I am not sure if it can be caused by an in-progress snapshot purge. I will double-check this part later.
```
2021-09-09T06:33:37.557860999Z time="2021-09-09T06:33:37Z" level=error msg="Failed rebuilding of replica 10.251.26.163:10105" controller=longhorn-engine error="failed to add replica address='tcp://10.251.26.163:10105' to controller 'pvc-0a40bd48-8239-4065-ac49-171efc715769': failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn [--url 10.251.24.186:10000 add tcp://10.251.26.163:10105], output , stderr, time=\"2021-09-09T06:33:37Z\" level=info msg=\"Adding replica tcp://10.251.26.163:10105 in WO mode\"\ntime=\"2021-09-09T06:33:37Z\" level=fatal msg=\"Error running add replica command: failed to create replica tcp://10.251.26.163:10105 for volume 10.251.24.186:10000: rpc error: code = Unknown desc = Too many snapshots created\"\n, error exit status 1" node=cit-l2bigdmstp1 volume=pvc-0a40bd48-8239-4065-ac49-171efc715769
```
```
2021-09-09T06:34:07.590410061Z E0909 06:34:07.590283       1 engine_controller.go:196] fail to sync engine for longhorn-system/pvc-0a40bd48-8239-4065-ac49-171efc715769-e-1a32d450: fail to start rebuild for pvc-0a40bd48-8239-4065-ac49-171efc715769-r-1474b823 of pvc-0a40bd48-8239-4065-ac49-171efc715769-e-1a32d450: timed out waiting for the condition
```

Based on the current situation, there are several suggestions that can help stabilize your volumes:
1. Decrease the replica count and remove the rebuilding replicas for the volume. Warning: after decreasing, there will be only 1 replica for volume, which means the HA is unavailable.
2. Remove some small snapshots and wait for the snapshot purge complete. Make sure the total snapshot count is smaller than 250 since we need to create a new snapshot for backing up later.
3. Create a backup.
4. Continue removing the snapshot and wait for the purge done.
5. Increase the replica count and wait for the rebuilding.

Notice that you are using HDD disks with v1.1.0. I would recommend upgrading to v1.2.2 since the Longhorn made an improvement for the low spec (HHD disk, limit network bandwidth) environment. Otherwise, the replicas in HDD disks may encounter an unexpected sudden crash as long as there is intensive data r/w.

**Comment by fynrup** [comment]
Sorry for taking so long to answer, I was out of office for a long time.

We reduced the replica count to one and removed the snapshots. It took around 2 weeks to fully delete all snapshots, but now it works as intended and no additional snapshots are being created. 

Thanks for the help!

> There are really tons of logs in the support bundle. I cannot even open and search some large files... With a brief glance at the volume, I found there were a lot of rebuilding happens on the volume. Some of the rebuilding retries were caused by too many snapshots in the volumes. But some of them were caused by a weird timeout error during rebuilding starting. I am not sure if it can be caused by an in-progress snapshot purge. I will double-check this part later.
> 
> ```
> 2021-09-09T06:33:37.557860999Z time="2021-09-09T06:33:37Z" level=error msg="Failed rebuilding of replica 10.251.26.163:10105" controller=longhorn-engine error="failed to add replica address='tcp://10.251.26.163:10105' to controller 'pvc-0a40bd48-8239-4065-ac49-171efc715769': failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn [--url 10.251.24.186:10000 add tcp://10.251.26.163:10105], output , stderr, time=\"2021-09-09T06:33:37Z\" level=info msg=\"Adding replica tcp://10.251.26.163:10105 in WO mode\"\ntime=\"2021-09-09T06:33:37Z\" level=fatal msg=\"Error running add replica command: failed to create replica tcp://10.251.26.163:10105 for volume 10.251.24.186:10000: rpc error: code = Unknown desc = Too many snapshots created\"\n, error exit status 1" node=cit-l2bigdmstp1 volume=pvc-0a40bd48-8239-4065-ac49-171efc715769
> ```
> 
> ```
> 2021-09-09T06:34:07.590410061Z E0909 06:34:07.590283       1 engine_controller.go:196] fail to sync engine for longhorn-system/pvc-0a40bd48-8239-4065-ac49-171efc715769-e-1a32d450: fail to start rebuild for pvc-0a40bd48-8239-4065-ac49-171efc715769-r-1474b823 of pvc-0a40bd48-8239-4065-ac49-171efc715769-e-1a32d450: timed out waiting for the condition
> ```
> 
> Based on the current situation, there are several suggestions that can help stabilize your volumes:
> 
> 1. Decrease the replica count and remove the rebuilding replicas for the volume. Warning: after decreasing, there will be only 1 replica for volume, which means the HA is unavailable.
> 2. Remove some small snapshots and wait for the snapshot purge complete. Make sure the total snapshot count is smaller than 250 since we need to create a new snapshot for backing up later.
> 3. Create a backup.
> 4. Continue removing the snapshot and wait for the purge done.
> 5. Increase the replica count and wait for the rebuilding.
> 
> Notice that you are using HDD disks with v1.1.0. I would recommend upgrading to v1.2.2 since the Longhorn made an improvement for the low spec (HHD disk, limit network bandwidth) environment. Otherwise, the replicas in HDD disks may encounter an unexpected sudden crash as long as there is intensive data r/w.
