### ISSUE TITLE
[FEATURE] Support imagePullSecret

### ISSUE THREAD

**Issue by dp-42** [longhorn/longhorn#3102]
**Is your feature request related to a problem? Please describe.**
Longhorn users might want to use there own container registry. Thanks to the setting `global.cattle.systemDefaultRegistry` you can easily replace the CR with your own.

However, if your CR requires authentication (this will be required in most cases, I assume) you want to specify also an `imagePullSecret` that is added to all pods.

Therefore I would kindly as for `imagePullSecret` support in the Longhorn Helm Chart.

**Describe the solution you'd like**
Other Helm Charts usually have a setting like  `image.pullSecret` that enable you to add a list of secrets to use for image pulling.

Great example would be a Bitnami Chart like Redis see [Redis Image Parameters](https://github.com/bitnami/charts/tree/master/bitnami/redis#redis-image-parameters).

**Describe alternatives you've considered**
Currently, I use a patch for `kustomize` in order to add the `imagePullSecret` - of course, this only works when you use `kustomize` - if you do e.g. a `helm install`  you will have an issue.

**Comment by jenting** [comment]
We had a `registrySecret` setting https://github.com/longhorn/charts/blob/longhorn-1.2.0/charts/longhorn/values.yaml#L114 already, and this one could fulfill your requirement.

**Comment by dp-42** [comment]
Hi @jenting 

many thanks for your fast reply!

You are right, I totally missed that setting as I was to focused in `imagePullSecret` instead of checking the `registry` part of the `values.yaml`. This generally fits my purpose - many thanks!

However, I noticed 2 things:

First, when using this setting the chart automatically creates a secret for me. However, I already have the secret created beforehand (e.g. by a cluster admin), so I don´t need the creation of the secret. Other charts usually do not take care of creation of the secret, they just allow you to specify it - you need take care of creation yourself. 

Also from a security point you usually don´t want to specify passwords within a `values.yaml`.

The second, really small thing is that the created `registry-secret` file is the only `yml` file, all the others are `yaml` files - I will make a PR for this little inconsistency - however, of cause this does not affect any functionality of the Chart itself!

**Comment by PhanLe1010** [comment]
Thanks @dp-42 

Good point! We will discuss this with other team members

**Comment by PhanLe1010** [comment]
Need to double check the upgrade path. Will Helm remove the existing secret when users upgrade to the new version?

**Comment by innobead** [comment]
ref: https://github.com/longhorn/longhorn/issues/2157
