### ISSUE TITLE
[QUESTION] k3s bare-metal deployment - must be superuser to use mount

### ISSUE THREAD

**Issue by bym0** [longhorn/longhorn#3107]
**Question**

**Environment:**
 - Longhorn version: 1.2.0
 - Kubernetes version: v1.21.5+k3s1
 - Node config (5 Nodes)
   - OS type and version: Debian 11
   - CPU per node: 3x Intel i9 9900K
   - Memory per node: 20GB 
   - Disk type: 100GB NVME
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox LXC

**Additional context**
```
MountVolume.SetUp failed for volume "kube-api-access-sn8rl" : mount failed: exit status 32 Mounting command: mount Mounting arguments: -t tmpfs tmpfs /var/lib/kubelet/pods/5ff59454-8532-4b80-86a2-6179b6210276/volumes/kubernetes.io~projected/kube-api-access-sn8rl Output: mount: /var/lib/kubelet/pods/5ff59454-8532-4b80-86a2-6179b6210276/volumes/kubernetes.io~projected/kube-api-access-sn8rl: must be superuser to use mount.
```

Fresh 5 Node installation, installed open-iscsi on every node. Tell me if you need more information.

**Comment by joshimoo** [comment]
@bym0 projected volumes are only supported for `secret, downwardAPI, configMap, serviceAccountToken` and are handled by kubernetes not longhorn. 
ref: https://kubernetes.io/docs/concepts/storage/volumes/#projected
ref: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/all-in-one-volume.md
