### ISSUE TITLE
Feature request: support for storage pools

### ISSUE THREAD

**Issue by sebastiansirch** [longhorn/longhorn#311]
Currently, the disks of all nodes are added to a single storage pool. This implies that all disks have the same IO performance (otherwise, it becomes a random choice how fast the provided volume actually is).

In a setting with heterogeneous nodes (e.g. some have SSDs, some HDDs), the following features would be very helpful:
* assign disks to storage pools (e.g. "hdd-pool", "sdd-pool")
* create storage classes (e.g. "fast", "medium", "slow") referencing these storage pools such that PVCs can be automatically provisioned based on the resources from the given storage pool. this would allow developers to make a specific and reliable choice about the IO performance they request (and actually get)

**Comment by mmriis** [comment]
+1 would like to see this as we utilize bare-metal servers that have both HDD and SSD storage.

**Comment by yasker** [comment]
We can also add node level tags. The disks in each node will inherit that node tags then users can control which group of nodes can be used for storage.

**Comment by mmriis** [comment]
This would mean that some nodes should only have fast storage and some slow? So no mixing storage classes in nodes?

**Comment by yasker** [comment]
@mmriis No. The nodes tag are not overriding the disk tag.

For example, the node tag can be `storage_main` for node 1-5, `storage_backup` for node 6-10. The disk A tag for node 1 can be `fast`, disk B for node 1 can be `slow`. Internally, we will treat disk A on node 1 as both `fast` and `storage_main`, disk B on node 1 as `slow` and `storage_main`.

**Comment by fmax** [comment]
+1 that would be greate to have a SSD and HDD pool
:)

**Comment by yasker** [comment]
@smallteeths backend merged. We can start  UI development.

**Comment by yasker** [comment]
@ttpcodes can you write the API reference for the feature? @smallteeths needs it for UI

**Comment by smallteeths** [comment]
@ttpcodes There is no connection between node tags and disk tags. When I create volume, I select one of node tags and one of disk tags. However, this node does not contain the disk tag, which fails to create volume.It would be nice to add a parameter in the 'disktags' API to return the appropriate disktags

**Comment by meldafrawi** [comment]
Steps to test:
  - Create 4 nodes cluster, with each node have main disk A, and additional disk B
  - Deploy Longhorn, create longhorn StorageClass.
  - for each node, make sure you added the extra disks and scheduling is enabled on them.
  - for Nodes 1 & 2 : Create a node tag `main`
  - for Nodes 3 & 4 : Create a node tag `backup`
  - Create a disk tag `ssd-pool` for
      - Node 1 Disk A
      - Node 2 Disk A
      - Node 3 Disk A
      - Node 4 Disk A
  - Create a disk tag `hdd-pool` for
      - Node 1 Disk B
      - Node 2 Disk B
      - Node 3 Disk B
      - Node 4 Disk B
  1. Create a volume-1, and only set Node Tag to `main`
     _Expected result:_ volume replicas should be  scheduled on nodes 1 & 2

  2. Create a volume-2, and only set Node Tag to `backup`
     _Expected result_: volume replicas should be  scheduled on nodes 3 & 4

  3. Create a volume-3, and only set Disk Tag to `ssd-pool`
     _Expected result:_ volume replicas should be  scheduled on all nodes on A Disks

  4. Create a volume-4, and only set Disk Tag to `hdd-pool`
     _Expected result:_ volume replicas should be  scheduled on all nodes on B Disks

  5. Create a volume-5, set Node Tag to `main` , and Disk Tag to `ssd-pool`
     _Expected result:_ volume replicas should be  scheduled on nodes 1 & 2 on A Disks

  6. Create a volume-6, set Node Tag to `main` , and Disk Tag to `hdd-pool`
     _Expected result:_ volume replicas should be  scheduled on nodes 1 & 2 on B Disks

  7. Create a volume-7, set Node Tag to `backup` , and Disk Tag to `ssd-pool`
     _Expected result:_ volume replicas should be  scheduled on nodes 3 & 4 on A Disks

  8. Create a volume-8, set Node Tag to `backup` , and Disk Tag to `hdd-pool`
     _Expected result:_ volume replicas should be  scheduled on nodes 3 & 4 on B Disks

  - Stop scheduling on Node 1
  - Create a new node Node 5 with 2 disks A and B, make sure disks added and scheduling is enabled
  - Create Node Tag `main` on Node 5
  - Create Disk Tag `ssd-pool` on Node 5, Disk A
  - Create Disk Tag `hdd-pool` on Node 5, Disk B
  
  9. Delete some/all volume-1 replicas on Node 1
      _Expected result:_ replicas should start rebuilding on Node 5, on Both Disks A & B.

  10. Delete some/all volume-5 replicas on Node 1
      _Expected result:_ replicas should start rebuilding on Node 5, on Disk A

  11. Delete some/all volume-5 replicas on Node 1
      _Expected result:_ replicas should start rebuilding on Node 5, on Disk B

**Comment by iomari** [comment]
Greetings,
Any recent update on having storage pools? This is over 2 years later.

**Comment by joshimoo** [comment]
@iomari are you looking for across cluster sharding instead? https://github.com/longhorn/longhorn/issues/1061
