### ISSUE TITLE
[Task] Analyze the backup restore test cases and add necessary test cases

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3115]
**What's the task? Please describe.**
Backup restore test cases should be revisit and the missed out cases should be added.

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] Analyze the backup and restore test cases.
        - Restoring from 1st backup when there are multiple backups exist is missed out.
- [x] Create the test skeleton for test cases
- [x] Implement the test cases.
- [x] Run the cases and verify.

**Additional context**
https://github.com/longhorn/longhorn/issues/3111

**Comment by khushboo-rancher** [comment]
Passed in the nightly test run https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64-s3/11/testReport/tests/test_basic/test_restore_basic_s3_/

**Comment by innobead** [comment]
Good thanks @khushboo-rancher
