### ISSUE TITLE
[FEATURE] UI should inform users that backups created by a activated DR volume may reside in the original backup volume

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3121]
**Is your feature request related to a problem? Please describe.**
The issue will happen when a DR volume using the same name as the original/backup volume.

**Describe the solution you'd like**
Add a tip/warning when users try to create a DR volume with the same name as the backup volume.

**Additional context**
Right now Longhorn always uses the name rather than a UUID to match a volume with the backup volume. If most users prefer to have a separate backup volume for an activated DR volume regardless of the naming, we may need to refactor this part in the future.

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with master image set (ui: bdb3260)

When the backup volume and the disaster recovery volume with the same name on the same cluster, there will be popover showing the reason and hinting to use a different name.

![image](https://user-images.githubusercontent.com/602540/141278541-becf8028-4686-48cb-89b1-7e5cba014b92.png)
