### ISSUE TITLE
[BUG] fsfreeze race condition

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#3125]
**Describe the bug**
there is a race condition around the `fsfreeze`  between mount point evaluation of a device and the invocation of the fsfreeze if the device is unmounted from that mount point, the folder will now reference the original device that hosts the mount point folder. 

As a hotfix I am removing the fsfreeze invocation and replacing it with our previous behavior of calling sync.

**Additional context**
- We introduced the fsfreeze enhancement in https://github.com/longhorn/longhorn/issues/2187

**Comment by joshimoo** [comment]
@khushboo-rancher for regression testing, we need to double check snapshot / recurring jobs.
Since after this hotfix we rely on the previous behavior of system sync, this has the effect that the volume head is not automatically dirty again, so we will skip backups in case nothing has changed. Like we did previously REF: #2555

**Comment by derekbit** [comment]
> there is a race condition around the fsfreeze between mount point evaluation of a device and the invocation of the fsfreeze if the device is unmounted from that mount point, the folder will now reference the original device that hosts the mount point folder.

@joshimoo IIUC, the race condition happens only when the volume is umounted. Can we check the volume is mounted correctly before freezing the filesystem?
