### ISSUE TITLE
[TASK] Remove the feature that skip taking backup/snapshot when the volume head is empty in recurring backup jobs

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3128]
**What's the task? Please describe.**
Currently, inside recurring job, we have a feature that can skip taking backup/snapshot for volume if the volume head is empty:
* https://github.com/longhorn/longhorn-manager/blob/a38318e502e83452e0b6dc68ea5c4c26095b25f0/app/recurring_job.go#L700
* https://github.com/longhorn/longhorn-manager/blob/a38318e502e83452e0b6dc68ea5c4c26095b25f0/app/recurring_job.go#L465

This leads to confusion for users that sometimes they don't see backups/snapshots aren't taken at the scheduling time.

We should remove this feature.

**Comment by derekbit** [comment]
PR: https://github.com/longhorn/longhorn-manager/pull/1115

**Comment by innobead** [comment]
@derekbit Please create a backport issue then backport to 1.2.x. Thanks.

**Comment by khushboo-rancher** [comment]
Validated with the master - `11/09/2021`

Validation - **Fail**

The recurring backup is creating backup/snapshot with no change in the head now but found an issue in retain count of the backup.

For recurring backup job retain count -3, the backups in the backups in backupstore is (retain count + 1) i.e. 4
Details of the recurring job in screenshot:
<img width="1766" alt="Screen Shot 2021-11-09 at 3 38 47 PM" src="https://user-images.githubusercontent.com/60111667/141023324-275d37cf-b30c-4d46-8e57-76e987c56193.png">
<img width="1764" alt="Screen Shot 2021-11-09 at 3 38 31 PM" src="https://user-images.githubusercontent.com/60111667/141023341-d9a678c7-8350-427c-a0da-03e0abf71857.png">

[longhorn-support-bundle_301b7c0f-5a63-4eee-9837-740e72f9f4ad_2021-11-09T23-39-04Z.zip](https://github.com/longhorn/longhorn/files/7508667/longhorn-support-bundle_301b7c0f-5a63-4eee-9837-740e72f9f4ad_2021-11-09T23-39-04Z.zip)
Volume name - pvc-3963d063-765d-460f-8de1-40010e3836e2

**Comment by khushboo-rancher** [comment]
With further investigation, looks like the deletion happens really slow. It takes time and if the recurring job is frequent like (3 mins and 5 mins), the backups in the backupstore appear more than the retain count.

Initially I had recurring backup scheduled in every 5 mins and I was not writing any data in between the two backups. In this case I saw 4 backups.
However, when I increased the time interval to 10 mins. I observed that the retain count got right in the backup store.

Can we improve this?

**Comment by derekbit** [comment]
@khushboo-rancher 
Seems the delay of the deletion. Do you know how long is the delay?
Why does the retain count go to normal after increasing the interval?

**Comment by derekbit** [comment]
@khushboo-rancher 
After testing again, the deletion times are both 4 seconds averagely in my environment with in-cluster nfs and minio.
I guess the long deletion time in your test might be due to the network, underlying storage performance and so on. Could you please help to check it?
I also think it is not in the scope of this feature.

**Comment by innobead** [comment]
Agree with @derekbit . @khushboo-rancher let's create another issue to track inconsistent count? Thanks.

**Comment by khushboo-rancher** [comment]
Created an issue for the inconsistency in backup count https://github.com/longhorn/longhorn/issues/3231.

Validation - **Pass**

Validated the below scenarios:
1. The RWO and RWX volume with some data in between the snapshot/backup recurring job. 
        Jobs scheduled fine.
2. The RWO and RWX volume with no data in between the snapshot/backup recurring job. 
        Jobs scheduled fine. 
3. Crashing the replica IM while the backup jobs was in progress. 
         If the backup is triggered from the replica crashed, the backup process failed and in next schedule, it triggered the backup again. 
         If the another replica was crashed on impact on the backup.
4. Crashing the engine IM while the jobs was in progress. 
         Job failed and triggered again in the next schedule.
5. Validated the `Allow Recurring Job While Volume Is Detached` setting. 
6. Repeated the tests 3, 4 while volume was detached and `Allow Recurring Job While Volume Is Detached` was enabled.

**Note**: No change is required in automation test.
