### ISSUE TITLE
[FEATURE] Separate deploy/longhorn.yaml into multiple files?

### ISSUE THREAD

**Issue by budimanjojo** [longhorn/longhorn#3132]
Hello, current approach to install longhorn using kubectl is to use the yaml file in `deploy/longhorn.yaml`. It's okay to simplify all of the resources into single file, but I think a lot of people will love to at least separate `crds + namespace` and other resources, especially with current GitOps popular template, i.e: https://github.com/k8s-at-home/template-cluster-k3s

Having 2 separate yaml files are enough imo, but it will be better if we can have single yaml file for every kind of resource. My suggestion **is not abandoning the current single file yaml approach**, but to provide the other who need to have them.

Here's what I'm suggesting in the technical way:
- Have a new directory somewhere else, maybe in `root-dir/yamls` will do, just like you have `root-dir/charts` for helm chart. In that directory, there will be files: 
    ```
    namespace.yaml
    crds.yaml
    deployment.yaml
    storageclass.yaml
    configmap.yaml
    ```
- Pull requests and commits should modify those files inside `root-dir/yamls` instead of `root-dir/deploy/longhorn.yaml`. 
- Have a github action on changes to yamls directory to automatically update `root-dir/deploy/longhorn.yaml`

Thanks before.

**Comment by kaxing** [comment]
For testing needs, I do use yaml files from here: [longhorn-manager/deploy/install/](https://github.com/longhorn/longhorn-manager/tree/master/deploy/install)
To the point having separated manifests, maybe this is what you are looking for @budimanjojo ?

**Comment by budimanjojo** [comment]
I have created a simple repo for this, it will be automatically updated whenever there is a new version in upstream repository (longhorn/longhorn-manager). https://github.com/budimanjojo/longhorn-manifests
