### ISSUE TITLE
[BUG] Volume creating with Backing Image contains invalid checksum string will result in attaching problem

### ISSUE THREAD

**Issue by kaxing** [longhorn/longhorn#3133]
**Describe the bug**
When creating Backing Image with invalid format of checksum string (not incorrect), while using this problematic backing image to create a new volume, this volume will be having issue when attaching.

**To Reproduce**
1. Create a new Backing Image
2. Input invalid checksum, eg. begin with a white space or a line break character
3. Create a volume with this backing image
4. Attaching and reattaching this volume

**Expected behavior**
Ideally the invalid checksum shouldn't be allowed while creating Backing Image from the UI.

**Environment:**
  - Longhorn version: v1.2.1

**Additional context**
Examples of invalid checksum:
  - `checksum: ' 2798503c2c7b718799324122137bf30a562aad1bc04bbf343daad225a5fd0d1fd5d269843a01ab00d4f8d8c5ab34f8956065f9831ef7459e9c487e895099e956'`
  - `checksum: '                _ not a valid checksum _                   ...'`

**Comment by derekbit** [comment]
We can validate the checksum at ui codes or longhorn-manager.
The later solution seems more general.

After patching to longhorn-manager to validate the input checksum(SHA512), it works well.
I will submit a pull request if there is no other concern. :)

```
--- a/manager/backingimage.go
+++ b/manager/backingimage.go
@@ -68,6 +70,10 @@ func (m *VolumeManager) CreateBackingImage(name, checksum, sourceType string, pa
                return nil, fmt.Errorf("invalid name %v", name)
        }

+       if !util.ValidateChecksum(checksum) {
+               return nil, fmt.Errorf("invalid checksum %v", checksum)
+       }
+
```

```
diff --git a/util/util.go b/util/util.go
index 51760511..329ff89b 100644
--- a/util/util.go
+++ b/util/util.go
@@ -282,6 +282,11 @@ func ValidateName(name string) bool {
        return validName.MatchString(name)
 }

+func ValidateChecksum(checksum string) bool {
+       validChecksum := regexp.MustCompile(`^[a-f0-9]{128}$`)
+       return validChecksum.MatchString(checksum)
+}
+
```

**Comment by derekbit** [comment]
Send a PR v2 https://github.com/longhorn/longhorn-manager/pull/1086

**Comment by kaxing** [comment]
Close this issue as extended test issue open in here #3173
