### ISSUE TITLE
[TEST] Upgrade test in our jenkins pipeline is getting stuck.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3134]
**What's the test to develop? Please describe.**
https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-upgrade-tests-ubuntu-amd64/
The job for upgrade on Master-head is getting stuck.

**Describe the items of the test development (DoD, definition of done) you'd like.**
- [ ] Fix the pipeline for upgrade test on master-head

**Comment by meldafrawi** [comment]
We've updated our integration test, I've triggered a new build to check if the issue still exists
https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-upgrade-tests-ubuntu-amd64/566/

**Comment by yangchiu** [comment]
We don't have this issue now.
