### ISSUE TITLE
Unable to deploy Longhorn on RHEL with SELinux enabled

### ISSUE THREAD

**Issue by jgallucci32** [longhorn/longhorn#314]
I am currently unable to deploy longhorn into a Rancher Kubernetes cluster (deployed using custom RKE method) when using RHEL hosts with SELinux enabled.

Rancher Version: v2.1.0
Kubernetes Version: v1.11.3
Docker Version: v1.13.1
OS Version: RHEL 7.5
Longhorn Version: v0.3.1

The issue is the engine-image pod is unable to deploy and has an error message for being unable to copy data to `/data/longhorn` inside the container. The container `/data/` directory is mapped to the `/var/lib/rancher/longhorn/engine-binaries/rancher-longhorn-engine-v0.3.0` directory on the node. Here is the SELinux labeling for the directory:
```
# ll -lZd /var/lib/rancher/longhorn/engine-binaries/rancher-longhorn-engine-v0.3.0
drwxr-xr-x. root root system_u:object_r:container_var_lib_t:s0 /var/lib/rancher/longhorn/engine-binaries/rancher-longhorn-engine-v0.3.0
```

The following errors appear in `/var/log/audit/audit.log` on the Docker host (Kubernetes node) when deploying longhorn:
```
type=AVC msg=audit(1540336923.589:48693): avc:  denied  { create } for  pid=12684 comm="cp" name="longhorn" scontext=system_u:system_r:container_t:s0:c668,c909 tcontext=system_u:object_r:container_var_lib_t:s0 tclass=file
type=AVC msg=audit(1540336923.590:48694): avc:  denied  { create } for  pid=12684 comm="cp" name="longhorn-engine-launcher" scontext=system_u:system_r:container_t:s0:c668,c909 tcontext=system_u:object_r:container_var_lib_t:s0 tclass=file
```

Using `audit2allow` the following rule is recommended to be created:
```
module allowlonghorn 1.0;

require {
        type container_var_lib_t;
        type container_t;
        class file { create open write };
}

#============= container_t ==============
allow container_t container_var_lib_t:file { create open write };
```
As a workaround, I ran `setenforce 0` to allow longhorn to be deployed without having to create a custom SELinux policy.

**Comment by akhfa** [comment]
I'm also waiting for this. It will be good if we have documentation.
