### ISSUE TITLE
[BUG] Support bundle missed newly added Longhorn CRDs

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#3142]
**Describe the bug**

Dump the support bundle with Longhorn v1.2.2, the newly added CRDs from v1.2.0 are missed inside `./yamls/longhorn`.
Such as:
- backingimagedatasources.yaml
- backingimagemanagers.yaml
- backups.yaml
- backuptargets.yaml
- backupvolums.yaml

**Environment:**
 - Longhorn version: v1.2.2

**Comment by khushboo-rancher** [comment]
Verified with Master-head `10/19/2021`

Validation - Pass

Sample support bundle
[longhorn-support-bundle_4bdb9312-3de1-4eb4-937a-a9052d5301a9_2021-10-20T03-40-40Z.zip](https://github.com/longhorn/longhorn/files/7378213/longhorn-support-bundle_4bdb9312-3de1-4eb4-937a-a9052d5301a9_2021-10-20T03-40-40Z.zip)
