### ISSUE TITLE
[FEATURE] Longhorn should ensure reading data from local replica at first priority if there is any to lower the read latency

### ISSUE THREAD

**Issue by hizheng** [longhorn/longhorn#3143]
**Is your feature request related to a problem? Please describe.**
See the issue described in the title.

**Describe the solution you'd like**
For a volume, it has two more replicas and one is local, it should ensure reading data from local one at first. It can lower the read latency.

**Comment by hizheng** [comment]
Got it. If it does not impact the write process, the master + slave  mode is still to pick up the best replica to read. If we consider the fast disk, it is a little complicated for that case in which one replica is local + HDD, one replica is remote + SSD, how to know which one is the fast one. So I suggests we can focus on the locality case at Phase one, and in next phase, we can figure out the fast disk case?

**Comment by jenting** [comment]
cc @keithalucas

**Comment by shuo-wu** [comment]
In the previous discussion with @hizheng , we prefer to use the tag & selector mechanism for this feature. In a nutshell, tags will be dynamically generated based on the volume current status (if one replica is on the same node as the volume or if one replica is still in a SSD disk) during replica launching, and the selectors will be applied later for the engine launching based on users' read priority configuration (local replica first, or the replica in some specific disks first, or either). This design would fit more use cases as I mentioned before.

But there is one potential issue here. If there are multiple volumes that prioritize the read from the replicas in the same disk, will the disk be overwhelmed? In other words, without balancing the read requests, sometimes the read priority may degrade the performance/stability.

And in today's review meeting, @PhanLe1010 raise another idea: the engine can prioritize replicas in terms of reading based on the read latency. I would leave him to explain more about it.

**Comment by PhanLe1010** [comment]
Similar idea as @derekbit , I am thinking if we can keep track of the number of the in-flight read requests to each replica. Then we pick the replica with the smallest value to read from. By doing this we are picking replica based on their true capability, not by their fame. 

Pulling @keithalucas into the thread

**Comment by hizheng** [comment]
Taking load balance into consider, we can define some stragetegy for user to select, like rr(round robin), wrr(weighted round-robin), and lrf(local replica first). We can make wrr as the default. When user choose lrf, it is saying that the user values the read latency more than load balance. In another words, in this case, local replica will hold all read requests, whereas non-local replicas just act as backup.

**Comment by Bessonov** [comment]
Hey guys, is there any update? This discussion is awesome! I really like the idea behind wrr and lrf.

**Comment by innobead** [comment]
> * local-first: read from local replica (best effort). Reduce read latency but sacrifice IOPS/throughput.

I am thinking about what's the real use case for this mode. It's not just `local-first` but also `local-only`, right?

**Comment by derekbit** [comment]
> I am thinking about what's the real use case for this mode. 

Probably database?

> It's not just local-first but also local-only, right?

Local replica does not always exist. `local-first` is just for best-effort.

**Comment by derekbit** [comment]
Agreed. Let's postpone it and figure out the real use cases. Thank you.

**Comment by shuo-wu** [comment]
> The IO requests are distributed to different replicas at the same time in the current round-robin method. If the requests are only sent to low latency replica, the latency can be reduced but the thoughpu/IOPS are reduced significantly.

This round-robin method is the main reason why Longhorn read performance can be better than native disks. On the other hand, based on the previous benchmark result(see [the last 2 slides](https://docs.google.com/presentation/d/1Yic8B1BbKpS54opaPYI7Cv1_EhpK2hKJ/edit?usp=sharing&ouid=108339013651336965146&rtpof=true&sd=true)), the latency (controller to local replica) we can reduce at max is around 100ms. I am not sure if it's worth sacrificing it.

**Comment by derekbit** [comment]
> This round-robin method is the main reason why Longhorn read performance can be better than native disks. On the other hand, based on the previous benchmark result(see [the last 2 slides](https://docs.google.com/presentation/d/1Yic8B1BbKpS54opaPYI7Cv1_EhpK2hKJ/edit?usp=sharing&ouid=108339013651336965146&rtpof=true&sd=true)), the latency (controller to local replica) we can reduce at max is around 100ms. I am not sure if it's worth sacrificing it.

You're right. The latency is still high after sacrificing the IOPS/throughput. That's why I think sacrificing them for a little latency improvement is not worthwhile.

**Comment by derekbit** [comment]
The feature request is invalid.

For IOPS or throughput, multiple replicas can improve the two numbers. If we only rely on one low latency replica, the numbers will drop a lot. I'm thinking keeping the current implementation might be good enough for a better tradeoff.

To reduce latency, we can improve it by introducing iouring in v1.8.0 instead.

WDYT? @innobead @shuo-wu

**Comment by innobead** [comment]
Sounds good, so that means this feature is actually invalid as per the current design, right?

**Comment by derekbit** [comment]
> Sounds good, so that means this feature is actually invalid as per the current design, right?

Correct!
