### ISSUE TITLE
[BUG] confirmation dialog box doesn't appear sometimes for delete volume action.

### ISSUE THREAD

**Issue by rlex** [longhorn/longhorn#3151]
**Is your feature request related to a problem? Please describe.**
Noticed that volume deletion option does not have any kind of condirmation dialog, even for attached volumes

**Describe the solution you'd like**
Confirmation box when deleting volume. Maybe even aws-style s3 deletion box, where you need to copy/type volume name when deleting object

**Comment by rlex** [comment]
k3s, but with ingress-nginx behind oauth2-proxy

**Comment by jenting** [comment]
- Had you tried different browsers?
- Could you please open the browser's dev tool to check if there are any errors when you click `Delete` button?

**Comment by jenting** [comment]
I'd prefer to close this issue now.
Feel free to reopen it once you could reproduce it (please remember to check the browser console to see if there is any error).
