### ISSUE TITLE
[FEATURE] Allowing users to download backing images

### ISSUE THREAD

**Issue by guangbochen** [longhorn/longhorn#3155]
**Is your feature request related to a problem? Please describe.**
Allowing users to download the backing images from UI, so that those images can be shared accordingly.

**Comment by innobead** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Main-Board-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/3155?planning-poker) with ZenHub @jenting @PhanLe1010 @shuo-wu @joshimoo

**Comment by innobead** [comment]
@shuo-wu will you start this in this sprint? or move to the next sprint?

**Comment by innobead** [comment]
We only have a doc about creating volumes from backing images, but along with the completeness of backing image functions, it's time to add some other doc to introduce other functions like how to create a backing image from upload/remote download, create a backing image from a volume, download, etc.

**Comment by yangchiu** [comment]
verified pass on v1.3.0-rc3 by following [manual test steps](https://longhorn.github.io/longhorn-tests/manual/release-specific/v1.3.0/test-backing-image-download-to-local/)
