### ISSUE TITLE
[DOC] RWX support for NVIDIA JETSON Ubuntu 18.4LTS kernel requires enabling NFSV4.1

### ISSUE THREAD

**Issue by fmolinelli** [longhorn/longhorn#3157]
V1.2 RWX PV cannot be mounted by pods

Environment:

Longhorn version: 1.2.2
Kubernetes version: k3s version v1.21.3+k3s1 (1d1f220f) / go version go1.16.6
Node config
OS type and version:
NVIDIA Jetson AGX Xavier [16GB] (M), NVIDIA Jetson NX Xavier [8GB] (W), NVIDIA Jetson Nano [2GB] (W)
L4T 32.6.1 [ JetPack 4.6 ]
Ubuntu 18.04.6 LTS
Kernel Version: 4.9.253-tegra
CPU per node: 8, 6, 4
Memory per node: 16GB, 8GB, 2GB
Disk type NVMe 256GB , microSD 128GB, microSD 128GB
Network bandwidth and latency between the nodes: 1Gbps, same gigabit switch
Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
Launched RWX deployment test 'rwx-nginx-test.yaml' with embedded PVC and against a pre-existing LHorn PV:
Same result:
Each pod is pending:
(combined from similar events): MountVolume.MountDevice failed for volume "bluevol01" : rpc error: code = Internal desc = mount failed: exit status 32 Mounting command: /usr/bin/systemd-run Mounting arguments: [--description=Kubernetes transient mount for /var/lib/kubelet/plugins/kubernetes.io/csi/pv/bluevol01/globalmount --scope -- /bin/mount -t nfs -o vers=4.1,noresvport,soft,intr,timeo=30,retrans=3 10.43.35.133:/bluevol01 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/bluevol01/globalmount] Output: Running scope as unit: run-r1e3ab46bd21d425ebb976f30e6f589cd.scope mount.nfs: Protocol not supported

PVC are shown as 'bound':
fiber_manual_record bluevol01 - Bound bluevol01 20Gi ReadWriteMany longhorn-static
fiber_manual_record rwx-test - Bound pvc-015e3757-22bd-4516-8c6e-9562c418e1c3 1Gi ReadWriteMany longhorn

In Longhorm UI the volumes are shown as attached and healthy
The longhorn RWX share-manager is working

rpcbind service is running

here's rpcinfo on all 3 nodes:
blueadmin@BL-AGX01:~/wdir/k3s/longhorn$ rpcinfo
program version netid address service owner
100000 4 tcp6 ::.0.111 portmapper superuser
100000 3 tcp6 ::.0.111 portmapper superuser
100000 4 udp6 ::.0.111 portmapper superuser
100000 3 udp6 ::.0.111 portmapper superuser
100000 4 tcp 0.0.0.0.0.111 portmapper superuser
100000 3 tcp 0.0.0.0.0.111 portmapper superuser
100000 2 tcp 0.0.0.0.0.111 portmapper superuser
100000 4 udp 0.0.0.0.0.111 portmapper superuser
100000 3 udp 0.0.0.0.0.111 portmapper superuser
100000 2 udp 0.0.0.0.0.111 portmapper superuser
100000 4 local /run/rpcbind.sock portmapper superuser
100000 3 local /run/rpcbind.sock portmapper superuser

Please can you tell me how to get out of that?

**Comment by derekbit** [comment]
@fmolinelli 
Enable nfsv4.1 by CONFIG_NFS_V4_1=y.

**Comment by yangchiu** [comment]
@derekbit Using AWS Ubuntu image `ubuntu-focal-20.04-amd64-server-20221212 ` to run the `environment_check.sh` script, I get the following warning:
```
[WARN]  CONFIG_NFS_V4_2 kernel config is not enabled on nodes ip-10-0-1-170 ip-10-0-1-79 ip-10-0-1-239.
[WARN]  NFS client kernel support, CONFIG_NFS_V4_1 CONFIG_NFS_V4_2, is not enabled on Longhorn nodes. Please refer to https://longhorn.io/docs/1.4.0/deploy/install/#installing-nfsv4-client for more information.
```
Actually `CONFIG_NFS_V4_2` is already enabled in these machine, but there is another unset config named `CONFIG_NFS_V4_2_READ_PLUS` causes the check failed:
```
/# cat /boot/config-$(uname -r) | grep NFS_V4
CONFIG_NFS_V4=m
CONFIG_NFS_V4_1=y
CONFIG_NFS_V4_2=y
CONFIG_NFS_V4_1_IMPLEMENTATION_ID_DOMAIN="kernel.org"
CONFIG_NFS_V4_1_MIGRATION=y
CONFIG_NFS_V4_SECURITY_LABEL=y
# CONFIG_NFS_V4_2_READ_PLUS is not set
CONFIG_NFS_V4_2_SSC_HELPER=y
```
Do we need more precise checking or this warning is ok for now?

**Comment by innobead** [comment]
@yangchiu awesome!

**Comment by derekbit** [comment]
> @derekbit Using AWS Ubuntu image `ubuntu-focal-20.04-amd64-server-20221212 ` to run the `environment_check.sh` script, I get the following warning:
> 
> ```
> [WARN]  CONFIG_NFS_V4_2 kernel config is not enabled on nodes ip-10-0-1-170 ip-10-0-1-79 ip-10-0-1-239.
> [WARN]  NFS client kernel support, CONFIG_NFS_V4_1 CONFIG_NFS_V4_2, is not enabled on Longhorn nodes. Please refer to https://longhorn.io/docs/1.4.0/deploy/install/#installing-nfsv4-client for more information.
> ```
> 
> Actually `CONFIG_NFS_V4_2` is already enabled in these machine, but there is another unset config named `CONFIG_NFS_V4_2_READ_PLUS` causes the check failed:
> 
> ```
> /# cat /boot/config-$(uname -r) | grep NFS_V4
> CONFIG_NFS_V4=m
> CONFIG_NFS_V4_1=y
> CONFIG_NFS_V4_2=y
> CONFIG_NFS_V4_1_IMPLEMENTATION_ID_DOMAIN="kernel.org"
> CONFIG_NFS_V4_1_MIGRATION=y
> CONFIG_NFS_V4_SECURITY_LABEL=y
> # CONFIG_NFS_V4_2_READ_PLUS is not set
> CONFIG_NFS_V4_2_SSC_HELPER=y
> ```
> 
> Do we need more precise checking or this warning is ok for now?

Yeah, need a precise check. Will update it.

**Comment by derekbit** [comment]
Updated in https://github.com/longhorn/longhorn/pull/5144

cc @yangchiu

**Comment by yangchiu** [comment]
After PR https://github.com/longhorn/longhorn/pull/5144, running environment check script in AWS `ubuntu-focal-20.04-amd64-server-20221212`, it's able to check `CONFIG_NFS_V4_1`, `CONFIG_NFS_V4_2` is set or not.
