### ISSUE TITLE
[QUESTION] How to make master kubernetes nodes schedulable

### ISSUE THREAD

**Issue by lfdominguez** [longhorn/longhorn#3158]
**Question**
I have a 10 nodes kubernetes cluster and has 3 masters with 1T of disk, how i can make that Longhorn use that masters disk too to schedule, these masters are powerful servers and i don't want to waste infrastructure resources.

**Environment:**
 - Longhorn version: 1.2.2
 - Kubernetes version: v1.21.3+rke2r1
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 56
   - Memory per node: 128G
   - Disk type: FCoE
   - Network bandwidth and latency between the nodes: 0.197ms @ 10Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Additional context**

**Comment by miledhileli** [comment]
> @lfdominguez We don't recommend running Longhorn on controller plan (the master nodes) because Longhorn and Kubernetes API, ETCD will compete against each other for disk IO or CPU. It could affect the cluster stability.
> 
> If you really want to run Longhorn on the RKE2 master nodes. Consider removing the taint in those master nodes. Kubernetes will deploy Longhorn components on the master nodes. Again, this is not recommended for production.

In this case, if by mistake we are running longhorn in the controller plan, how can we prevent it from running?
