### ISSUE TITLE
[BUG] Changed node type from master to worker and longhorn not change node from unschedulable to schedulable

### ISSUE THREAD

**Issue by lfdominguez** [longhorn/longhorn#3159]
**Describe the bug**
Longhorn not recognize the change of new node type on change from master to worker.

**To Reproduce**
1. Delete node from cluster
2. Reinstall k8s
3. Join again to cluster (with same name)
4. Longhorn not schedule any disk to it (maybe has the old info of the cluster)

**Expected behavior**
Longhorn schedule disk to the new node

**Log**

**Environment:**
 - Longhorn version: 1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 5
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 56
   - Memory per node: 128G
   - Disk type(e.g. SSD/NVMe): FCoE
   - Network bandwidth between the nodes: 10gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: +20

**Additional context**
Using rke2

**Comment by PhanLe1010** [comment]
@lfdominguez 
How did you delete RKE2 node from cluster?
