### ISSUE TITLE
[BUG]  CSINode oc-master-03 does not contain driver driver.longhorn.io

### ISSUE THREAD

**Issue by novvoo** [longhorn/longhorn#3172]
```
Events:
  Type     Reason              Age   From                     Message
  ----     ------              ----  ----                     -------
  Normal   Scheduled           83s   default-scheduler        Successfully assigned monitoring/prometheus-prometheus-operator-prometheus-0 to oc-master-03
  Warning  FailedAttachVolume  1s    attachdetach-controller  AttachVolume.Attach failed for volume "pvc-f4d9fb89-8d75-4d93-9766-35b32470c307" : CSINode oc-master-03 does not contain driver driver.longhorn.io

```

```
kubectl get pod -n longhorn-system |grep csi
csi-attacher-7f8887b7bc-2mgmx               1/1     Running   0          14h
csi-attacher-7f8887b7bc-g62bs               1/1     Running   0          14h
csi-attacher-7f8887b7bc-nbvgc               1/1     Running   0          14h
csi-provisioner-6658b8bdd9-4h7wx            1/1     Running   0          14h
csi-provisioner-6658b8bdd9-jmtqn            1/1     Running   2          14h
csi-provisioner-6658b8bdd9-lxbmh            1/1     Running   0          14h
csi-resizer-848dc89769-8q8jw                1/1     Running   0          14h
csi-resizer-848dc89769-mzvhg                1/1     Running   0          14h
csi-resizer-848dc89769-wgbl6                1/1     Running   1          14h
csi-snapshotter-7b66db5b8d-6g8ks            1/1     Running   2          14h
csi-snapshotter-7b66db5b8d-gbrs2            1/1     Running   0          14h
csi-snapshotter-7b66db5b8d-j2pz7            1/1     Running   0          14h
longhorn-csi-plugin-c2pxp                   2/2     Running   24         30d
longhorn-csi-plugin-glts2                   2/2     Running   0          47m
longhorn-csi-plugin-qqt2b                   2/2     Running   0          13h
longhorn-csi-plugin-tssx9                   2/2     Running   20         30d
longhorn-csi-plugin-wdwvw                   2/2     Running   0          13h
longhorn-csi-plugin-xhvtg                   2/2     Running   19         30d

```

```
kubectl describe volumeattachments csi-a9acceab32b3fda7e237e6f559177fa0c351f4ea895ce5849cecf7c47652b71e 
Name:         csi-a9acceab32b3fda7e237e6f559177fa0c351f4ea895ce5849cecf7c47652b71e
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  storage.k8s.io/v1
Kind:         VolumeAttachment
Metadata:
  Creation Timestamp:  2021-10-21T05:35:47Z
  Managed Fields:
    API Version:  storage.k8s.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:attachError:
          .:
          f:message:
          f:time:
    Manager:      csi-attacher
    Operation:    Update
    Time:         2021-10-21T05:35:47Z
    API Version:  storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:attacher:
        f:nodeName:
        f:source:
          f:persistentVolumeName:
    Manager:         kube-controller-manager
    Operation:       Update
    Time:            2021-10-21T05:35:47Z
  Resource Version:  19340619
  UID:               cedb0f37-ec3c-4433-bab3-e91545cb48ff
Spec:
  Attacher:   driver.longhorn.io
  Node Name:  oc-master-03
  Source:
    Persistent Volume Name:  pvc-f4d9fb89-8d75-4d93-9766-35b32470c307
Status:
  Attach Error:
    Message:  CSINode oc-master-03 does not contain driver driver.longhorn.io
    Time:     2021-10-21T05:37:43Z
  Attached:   false
Events:       <none>

```

**Comment by armourshield** [comment]
I have the same issue, but the longhorn-csi-plugin are healthy. this is the support bundle. Upgraded from 1.2.3 to 1.2.4. Any idea what could have gone wrong. I am able to see the driver.longhorn.io/csi.sock in all the nodes

[longhorn-support-bundle_4ad3564f-4221-48d3-8204-a96433f1e4b4_2022-04-13T13-50-22Z.zip](https://github.com/longhorn/longhorn/files/8482153/longhorn-support-bundle_4ad3564f-4221-48d3-8204-a96433f1e4b4_2022-04-13T13-50-22Z.zip)

**Comment by zenhighzer** [comment]
- same here on raspberry pi 4 with Ubuntu 20.04.4 LTS and microk8s
- in longhorn.yaml I already adjusted KUBELET_ROOT_DIR  to /var/snap/microk8s/current/kubelet

**Comment by PhanLe1010** [comment]
It seems that the longhorn-csi-plugin hasn't been successfully registered to kubelet yet. 
@armourshield @zenhighzer Can you kill all pods ` longhorn-csi-plugin-xxx` to retry?

**Comment by PhanLe1010** [comment]
Todo: may be we should enhance Longhorn node driver registration to detect the failed case. ref https://github.com/kubernetes-csi/node-driver-registrar/pull/152

**Comment by anastazya** [comment]
> > It seems that the longhorn-csi-plugin hasn't been successfully registered to kubelet yet. The logs of the container `node-driver-registrar` in pods `longhorn-csi-plugin-xxx` pods does NOT have this messages:
> > ```
> > I0525 01:00:14.239318 70534 main.go:100] Received GetInfo call: &InfoRequest{}
> > --
> > Tue, May 24 2022 6:00:14 pm | I0525 01:00:14.240311 70534 main.go:107] "Kubelet registration probe created" path="/var/lib/kubelet/plugins/driver.longhorn.io/registration"
> > Tue, May 24 2022 6:00:14 pm | I0525 01:00:14.596851 70534 main.go:118] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @armourshield @zenhighzer Can you kill all pods ` longhorn-csi-plugin-xxx` to retry?
> 
> hi @PhanLe1010, i think i tried everything. in the end i completeley messed up the whole cluster. after creating a new microk8s-cluster longhorn works fine.. i dont know what i did wrong in my previous attempt.. but now i am sure that KUBELET_ROOT_DIR needs to be "/var/snap/microk8s/common/var/lib/kubelet"

thanks, you saved my mental sanity.

**Comment by armourshield** [comment]
> It seems that the longhorn-csi-plugin hasn't been successfully registered to kubelet yet. The logs of the container `node-driver-registrar` in pods `longhorn-csi-plugin-xxx` pods does NOT have this messages:
> 
> ```
> I0525 01:00:14.239318 70534 main.go:100] Received GetInfo call: &InfoRequest{}
> --
> Tue, May 24 2022 6:00:14 pm | I0525 01:00:14.240311 70534 main.go:107] "Kubelet registration probe created" path="/var/lib/kubelet/plugins/driver.longhorn.io/registration"
> Tue, May 24 2022 6:00:14 pm | I0525 01:00:14.596851 70534 main.go:118] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
> ```
> 
> @armourshield @zenhighzer Can you kill all pods ` longhorn-csi-plugin-xxx` to retry?

I had to restart the node remove and redeploy the csi-plugins, KUBELET_ROOT_DIR which in my case default should work, but I had to send it as ENV for the same path as I observed there was 2 paths in my system, don't know why it was there. There was no previous installation. But got it working after lot of csi-plugin fails and later had NFS register problem. Now it is working.
