### ISSUE TITLE
[BUG] The size of an uploaded or downloaded sparse file is the apparent file size

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3174]
**Describe the bug**
When uploading a sparse file as a backing image, the space it takes should be the actual size rather than the apparent size.

**To Reproduce**
1. Create a sparse file in local
```
~ touch bi-upload.raw
~ truncate -s 500M bi-upload.raw
~ mkfs.ext4 bi-upload.raw
mke2fs 1.46.1 (9-Feb-2021)
Creating filesystem with 512000 1k blocks and 128016 inodes
Filesystem UUID: fe6cfb58-134a-42b3-afab-59474d9515e0
Superblock backups stored on blocks:
	8193, 24577, 40961, 57345, 73729, 204801, 221185, 401409

Allocating group tables: done
Writing inode tables: done
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information: done
```
2. Upload the file as a backing image
3. Check the actual size of the uploaded backing image 
```
root@backing-image-manager-c00e-514f:/# cd data/backing-images/bi-upload-before-b79b91d0/
root@backing-image-manager-c00e-514f:/data/backing-images/bi-upload-before-b79b91d0# ls
backing  backing.cfg
root@backing-image-manager-c00e-514f:/data/backing-images/bi-upload-before-b79b91d0# ls -alh
total 501M
d-w---x--- 2 root root 4.0K Oct 21 13:08 .
drw-r--r-- 3 root root 4.0K Oct 21 13:08 ..
-rw-r--r-- 1 root root 500M Oct 21 13:08 backing
-rw-r--r-- 1 root root  361 Oct 21 13:08 backing.cfg
root@backing-image-manager-c00e-514f:/data/backing-images/bi-upload-before-b79b91d0# du -h backing
501M	backing
```

**Expected behavior**
The uploaded file should not take so much space

**Environment:**
 - Longhorn version: v1.2.2

**Comment by innobead** [comment]
> After the fix, the uploaded backing image in the above example is like:
> 
> ```
> root@backing-image-manager-c8b9-896f:/data/backing-images/bi-upload-after-52d8ce6b# ls -alh
> total 460K
> d-w---x--- 2 root root 4.0K Oct 21 13:21 .
> drw-r--r-- 3 root root 4.0K Oct 21 13:21 ..
> -rw-r--r-- 1 root root 500M Oct 21 13:20 backing
> -rw-r--r-- 1 root root  360 Oct 21 13:21 backing.cfg
> root@backing-image-manager-c8b9-896f:/data/backing-images/bi-upload-after-52d8ce6b# du -h backing
> 448K	backing
> ```
> 
> And the checksum of the uploaded file is the same as that of the local file.

@shuo-wu you probably need to update this example again as per your latest PR change for QA reference.

**Comment by shuo-wu** [comment]
> @shuo-wu you probably need to update this example again as per your latest PR change for QA reference.

This result should keep unchanged.

**Comment by shuo-wu** [comment]
There is no need to create another PR for the v1.2.x backport. All we should do is update the default backing image manager in the deployment file.

**Comment by khushboo-rancher** [comment]
@shuo-wu Is this merged for v1.2.x also? I can't find the merged PR of issue linked in this issue.

**Comment by shuo-wu** [comment]
> @shuo-wu Is this merged for v1.2.x also? I can't find the merged PR of issue linked in this issue.

The fix is in repo `backing-image-manager` and the latest version will be used in v1.2.x. Hence I don't think we need to do anything extra then.

**Comment by innobead** [comment]
Yes, the change in v2_20210820 is already and used in 1.2.3.

**Comment by kaxing** [comment]
Validating in progress,

Having problem with uploading the sparse files and receiving error notification:
```Timeout waiting for the upload service initialization, please delete then recreate Backing Image.```
![image](https://user-images.githubusercontent.com/602540/146006262-73d4025b-f000-43cf-863b-25c62abbee1d.png)

File generated with dd from /dev/urandom can be upload successfully.

However, the same set up and sparse file with v1.2.3-rc2 doesn't have this problem: https://github.com/longhorn/longhorn/issues/3409#issuecomment-993525224

No strange log from backing-image-manager or backing-image-ds pods.
Still look into the problem.

**Comment by shuo-wu** [comment]
I will check it when I am available. Is it possible that there are proxies intervening the big file upload?

**Comment by kaxing** [comment]
@shuo-wu I did a few more round of test, it appears more a connection problem, I will check with frontend.
However the smaller file size, like 32MB will be easier to reproduce but it is not happening every upload.

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with latest master-head images, spares file size will not change from local to the pod container.

---

The uploading timeout error won't able to consistently reproduce, will be opening another issue to track the problem.
