### ISSUE TITLE
[BUG] MountVolume.MountDevice failed for volume "pvc-28bcd383-4f7e-4f48-b8eb-1df00b3d8023" : rpc error: code = Internal desc = format of disk "/dev/longhorn/pvc-28bcd383-4f7e-4f48-b8eb-1df00b3d8023" failed: type:("ext4") target:("/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-28bcd383-4f7e-4f48-b8eb-1df00b3d8023/globalmount") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.45.5 (07-Jan-2020)     /dev/longhorn/pvc-28bcd383-4f7e-4f48-b8eb-1df00b3d8023 is apparently in use by the system; will not make a filesystem here!

### ISSUE THREAD

**Issue by CoreTechnologyAG** [longhorn/longhorn#3177]
**Describe the bug**

We have upgraded to V1.2.2 from V1.1.2. Now we have some problems, after deleting namespaces.
We are working in a developer infrastructure, to get the postgresql-helm-chart running. So we can try the chart with different parameters.
For this testing/developing we uninstall the helm chart and delete the namespaces div. times. In V1.1.2 it work perfect, in V1.2.2 we got the above mentioned error.

**To Reproduce**
1. Create namespace and use helm-chart from postgressql e.g.
2. First time it starts and pvc/pv is created
3. Delete helm-chart helm uninstall postgresql
4. delete namespaces
5. Create namespace again with the helm chart
6. kubectl get events -A and the  postgresql-pod won't start. It generates the above mentioned error. 

**Expected behavior**
Pod starts

Restarting of all longhorn pods (Daemonset/Deployments) should clear the situationn as well. But unfortunately is was not successfully. (We did it with: kubectl rollout restart)

**Log**
See attachment. I send you the kubectl get events 
You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: v1.2.2
 - Installation method kubectl:
 - Kubernetes distro K8S, Ubuntu 20.04 and version: Kubernetes v1.21.3
    - kubeadm version: &version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:03:28Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

   - Number of management node in the cluster: 2
   - Number of worker node in the cluster: 4

 - Node config
   - OS type and version: Ubuntu 20.04.3 LTS
   - CPU per node (Cores/Threads): 4/8 to 6/12
   - Memory per node: 64
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 1GB
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 30

**Additional context**

** work around **
Restart all longhorn nodes (4 nodes) and the volume is correct mounted afterwards.

[kubectlEvent.txt](https://github.com/longhorn/longhorn/files/7394538/kubectlEvent.txt)

**Comment by mimizone** [comment]
thanks for the link to the fix. I had the same problem on Ubuntu 22.04 / Microk8s. It seems to fix the problem indeed.
