### ISSUE TITLE
[BUG] cron setting won't persist

### ISSUE THREAD

**Issue by rlex** [longhorn/longhorn#3180]
**Describe the bug**
Can't save cron on recurring job, shows proper setting, but actually is 0 0 * * * 
Noticed that after checking my backups and seeing only midnight one.

**To Reproduce**
1. Go to 'recurring jobs'
2. Click on 'edit job'
3. Edit cron, save
4. See new cron but it's actually 0 0 * * *

**Expected behavior**
Cron should save

**Log**
Found no errors in logs, everything is 200. Noticed all websockets except recurringjob were closed but i guess that normal?

**Environment:**
 - Longhorn version: 1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.22
   - Number of management node in the cluster: 3 (schedulable with normal workloads)
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 4
   - Memory per node: 8gb
   - Disk type(e.g. SSD/NVMe): mix ssd / nvme
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal
 - Number of Longhorn volumes in the cluster: 2

**Additional context**

I recorded video about problem. Hope quality isn't too bad to see (github have some limitations) Inspector opened just in case:

https://user-images.githubusercontent.com/84462/138476928-affc3e15-1087-4e60-98e8-3c617cd591fe.mp4

**Comment by khushboo-rancher** [comment]
Validated with Longhorn master-head `1bd49df`

Validation - **Fail**

The cron job setting is persistent now but on changing the value multiple times, the value is not persistent.

https://user-images.githubusercontent.com/60111667/140214940-a80bb9b6-4d92-4400-a6b2-d479fdd8530f.mov

**Comment by khushboo-rancher** [comment]
Validated on Longhorn-v1.2.x-head `df6ad60`

Validation - **Fail**

From the recurring Job, it works fine, but the problem still exists in the volume details page.


https://user-images.githubusercontent.com/60111667/141872996-fb848fb3-ed96-40ab-95a0-e63a2420da2d.mov

**Comment by khushboo-rancher** [comment]
Validated with v1.2.x and master-head `11/18/2021`

Validation - **Pass**
