### ISSUE TITLE
[BUG] Restored volume show 'scheduled' with 2 replicas running and 1 unscheduled replica

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3183]
**To Reproduce**
1. Run the test `test_allow_volume_creation_with_degraded_availability_restore`, the test fails with below error
```
        create_and_wait_pod(core_api, pod)
        # check 2 replica scheduled successfully
        dst_vol = common.wait_for_replica_scheduled(client, dst_vol_name,
                                                    to_nodes=[node1.name,
                                                              node2.name],
                                                    expect_success=2,
                                                    expect_fail=1,
                                                    chk_vol_healthy=False,
                                                    chk_replica_running=False)
>       wait_for_volume_condition_scheduled(client, dst_vol_name,
                                            "status", "False")

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

client = <longhorn.Client object at 0x7f4ef75b00a0>, name = 'longhorn-testvol-n0isx4', key = 'status', value = 'False'

    def wait_for_volume_condition_scheduled(client, name, key, value):
        wait_for_volume_creation(client, name)
        for i in range(RETRY_COUNTS):
            volume = client.by_id_volume(name)
            print(volume)
            conditions = volume.conditions
            if conditions is not None and \
                    conditions != {} and \
                    conditions[VOLUME_CONDITION_SCHEDULED] and \
                    conditions[VOLUME_CONDITION_SCHEDULED][key] and \
                    conditions[VOLUME_CONDITION_SCHEDULED][key] == value:
                break
            time.sleep(RETRY_INTERVAL)
        conditions = volume.conditions
>       assert conditions[VOLUME_CONDITION_SCHEDULED][key] == value
E       AssertionError

common.py:2254: AssertionError
```
2. The test fails because the volume remains schedules=True even after it gets attached to a pod.

**Expected behavior**
Once the volume attached to a pod the schedule should become False.

**Log**
[longhorn-support-bundle_dfcf1034-331f-4b07-8b6c-c4ea403900b7_2021-10-23T01-05-43Z.zip](https://github.com/longhorn/longhorn/files/7402035/longhorn-support-bundle_dfcf1034-331f-4b07-8b6c-c4ea403900b7_2021-10-23T01-05-43Z.zip)

**Environment:**
 - Longhorn version: master-head
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3

**Additional context**
There is another problem in test which is fixed by https://github.com/longhorn/longhorn-tests/pull/756

**Comment by jenting** [comment]
> ref: [longhorn/longhorn-manager#1113](https://github.com/longhorn/longhorn-manager/pull/1113)

Probably #1113 is not the culprit.

**Comment by khushboo-rancher** [comment]
Yes, the test `test_allow_volume_creation_with_degraded_availability_restore` is still failing. https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64-s3/12/#showFailuresLink

**Comment by innobead** [comment]
Where we are?

**Comment by khushboo-rancher** [comment]
This is constantly failing on v1.2.x branch too. Can we fix this on priority before the v1.2.4 release?

cc: @innobead

**Comment by c3y1huang** [comment]
Test is blocked by replica-replenishment-wait-interval.
```
2021-10-23T00:13:50.390253487Z time="2021-10-23T00:13:50Z" level=debug msg="Replica replenishment is delayed until 2021-10-23 00:23:35 +0000 UTC"
```

**Comment by c3y1huang** [comment]
Test result
- https://ci.longhorn.io/job/private/job/longhorn-tests-regression/808/ (master)
- https://ci.longhorn.io/job/private/job/longhorn-tests-regression/809/ (v1.2.x)

**Comment by cchien816** [comment]
Verified in master-head 2022/04/01 on my local eovironment

Alsoin our Jenkins daily build was also [pass](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/78/testReport/tests/test_basic/test_allow_volume_creation_with_degraded_availability_restore_s3_/)

Close this issue
