### ISSUE TITLE
[FEATURE] Instruction of restoring Longhorn system from ETCD to a brand new cluster

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3188]
**Is your feature request related to a problem? Please describe.**
Longhorn provides a doc that guides the ETCD restore to a cluster containing existing volume data in #2228 : https://longhorn.io/docs/1.2.2/advanced-resources/rancher-cluster-restore/

We need a similar doc for the new cluster restore as well. Notice that the restored volumes here are meaningless. And the triggered backup recurring jobs of these volumes would override the existing backup volumes with empty data.

**Describe the solution you'd like**
Provide a doc with the necessary script that helps back up or restore a Longhorn system.

**Additional context**
- We can suspend the cron jobs before ETCD backup then the recurring jobs after the restore won't affect the backups.

**Comment by innobead** [comment]
We have https://longhorn.io/docs/1.3.0/advanced-resources/cluster-restore/restore-to-a-new-cluster-using-velero/ already. @shuo-wu do we still need this?
