### ISSUE TITLE
[BUG] Longhorn UI: XHR request URL sometimes wrong when UI is proxied

### ISSUE THREAD

**Issue by bashofmann** [longhorn/longhorn#3191]
**Describe the bug**
When the Longhorn UI is proxied through Rancher/Kubernetes API, the XHR request URLs on the volumes detail page sometimes do not contain the additional proxy path.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Rancher, tested with 2.6.2
2. Create a new cluster, tested with RKE2 on DigitalOcean, 3 nodes with all roles, each 2CPU, 4GB RAM, 80GB disk
![Bildschirmfoto 2021-10-27 um 09 48 39](https://user-images.githubusercontent.com/243056/139025853-7ab043fb-1cf9-4de6-befc-4e7e47904c6a.png)
3. Wait until the cluster is provisioned
4. Install Longhorn from the Rancher App Marketplace
![Bildschirmfoto 2021-10-27 um 09 58 37](https://user-images.githubusercontent.com/243056/139026465-2f1f33b1-8415-445c-b135-19ee7362cc24.png)
5. Wait until Longhorn is installed and all Longhorn Pods are started
6. Deploy a workload with a persistent volume
![Bildschirmfoto 2021-10-27 um 10 01 10](https://user-images.githubusercontent.com/243056/139026500-772ab51f-60c1-48da-a0a4-3ed46d8e14f2.png)
7. Go to the Longhorn UI
8. Open the Browser developer tools to easily see the failed requests
9. Go to the detail page of the volume

Sometimes the XHR requests to get more data about the volume fail because they go to `https://<rancher-domain>/v1/volumes/pvc-500739bb-ccad-4c34-8db3-4e1cf7adc5fe?action=snapshotList` instead of `https://<rancher-domain>/k8s/clusters/c-m-b8brxgtn/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/v1/volumes/pvc-500739bb-ccad-4c34-8db3-4e1cf7adc5fe?action=snapshotList`. This then breaks the page and all possible interactions like creating snapshots.
Sometimes they work correctly. You may need to refresh the page in the browser a couple of times to force this to happen.

This video shows the behaviour: https://www.dropbox.com/s/qpbyi9txnc4hg6g/longhorn-ui-proxying-bug.mov?dl=0

**Expected behaviour**
The request URLs are always correct and there are no UI erros.

**Log**

[longhorn-support-bundle_b7f95501-a032-48ac-994f-20c82a3c9287_2021-10-27T08-13-07Z.zip](https://github.com/longhorn/longhorn/files/7424354/longhorn-support-bundle_b7f95501-a032-48ac-994f-20c82a3c9287_2021-10-27T08-13-07Z.zip)

**Environment:**
 - Longhorn version: 1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog, Rancher 2.6.2
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2 v1.21.5
   - Number of combined management and worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 2
   - Memory per node: 4GB
   - Disk type(e.g. SSD/NVMe): 80GB at DigitalOcean
   - Network bandwidth between the nodes: unknown
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): DigitalOcean
 - Number of Longhorn volumes in the cluster: 1

**Additional context**
It seems that it happens less frequent if the cluster nodes have less load, but this is just a gut feeling.

**Comment by PhanLe1010** [comment]
Todo: need to evaluate to see if this is enough to fix from UI part or it also need to fix in backend

**Comment by kaxing** [comment]
Validating in progress, 

Testing with Rancher v2.6.2 + Longhorn master image set (ui: bdb3260), didn't see further XHR related error throughout the basic operations when accessing the UI via the proxy.

But current response will always return schema in http, checking further details on this.

**Comment by kaxing** [comment]
Validation - **PASSED**

tested again with master image set.

No more seeing the error with WSS.

---

The https problem with Rancher Proxy will not interfering the usability. Will track in a new issue once had more clues.

**Comment by jenting** [comment]
Ref issue #3245
