### ISSUE TITLE
[QUESTION] Backing up to MinIO on premise

### ISSUE THREAD

**Issue by MichaelShohat** [longhorn/longhorn#3192]
Hi,
I'm working on an air-gapped network with Longhorn installed on Rancher and our s3 endpoint is a MinIO server.
We have our own CA.
After adding AWS_CERT to my longhorn backup secret I'm getting the following error:
`error listing backups: error listing backup volumes: Failed to execute <the entire backup command> , output failed to append custom certificates: <my base64 certificate>,  error exit status 1`

I've tried setting AWS_CERT as the MinIO certificate, as the CA certificate and as the entire certificate chain.

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: 1.19
 - Node config
   - OS type and version: Ubuntu Server 20.04
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Rancher Kubernetes.

**Comment by PhanLe1010** [comment]
Can you check if the AWS_CERT is correctly encoded in base64 format and there are no trailing spaces?

Can you also try with an invalid AWS_CERT to see the error message is the same as this one?

**Comment by MichaelShohat** [comment]
The AWS_CERT is encoded in base64 format and there are no trailing spaces.

With an invalid value we get the same error, for example I used the value 'A' ('QQ==' in base 64)
and got back `error listing backups: error listing backup volumes: Failed to execute <the entire backup command> , output failed to append custom certificates: A, error exit status 1`

**Comment by jenting** [comment]
> I've tried setting AWS_CERT as the MinIO certificate, as the CA certificate and as the entire certificate chain.

May I say your AWS_CERT format is like this?
```
-----BEGIN CERTIFICATE-----
content of your domain certificate
-----END CERTIFICATE-----
...
-----BEGIN CERTIFICATE-----
content of any intermediate CA certificate
-----END CERTIFICATE-----
```

**Comment by MichaelShohat** [comment]
I've actually missed the fact it should be .PEM formated, thanks!
