### ISSUE TITLE
[BUG] rwx volume fail to attach

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3193]
**Describe the bug**
Deploy the https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml in a cluster having the nfs-common installed on the nodes.

**To Reproduce**
1. Deploy https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml or run the integration tests for rwx.
2. Pods fail to attach to the volume. No share-manager pod getting created has been observed.

**Expected behavior**
The rwx should be able to attach to the pod

**Log**
[longhorn-support-bundle_a19b2f6f-c04b-4374-b846-e9cbb2f6234d_2021-10-28T21-38-47Z.zip](https://github.com/longhorn/longhorn/files/7437496/longhorn-support-bundle_a19b2f6f-c04b-4374-b846-e9cbb2f6234d_2021-10-28T21-38-47Z.zip)
pod name - rwx-test
volume - pvc-dc8a5c4a-8044-4529-931e-3a41f30eaf23

**Environment:**
 - Longhorn version: master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
  
**Additional context**
https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64-nfs/12/

**Comment by innobead** [comment]
Need to move to `ready for testing.

**Comment by khushboo-rancher** [comment]
The rwx feature is working fine on master-head `11/04/2021` 
Validation - **Pass**

https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/478/
