### ISSUE TITLE
[BACKPORT] [REFACTOR] Remove the keyword register of deepcopy-gen

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#3194]
**What's the task? Please describe.**

According to https://www.openshift.com/blog/kubernetes-deep-dive-code-generation-customresources `GLOBAL TAGS` section

> Note: The register keyword in the value of the upper example will enable the registration of deepcopy methods into the scheme. This will completely go away in Kubernetes 1.9 because the scheme won’t be responsible anymore to do deepcopies of runtime.Objects. Instead just call yourobject.DeepCopy() or yourobject.DeepCopyObject(). You can and you should do that already today in 1.8-based projects as it is faster and less error-prone. Moreover, you will be prepared for 1.9 which will require this pattern.

Since the current Longhorn min supported Kubernetes is 1.16, so we could remove the keyword `register` in
- https://github.com/longhorn/longhorn-manager/blob/d901b23/k8s/pkg/apis/longhorn/v1beta1/doc.go#L1
- https://github.com/longhorn/longhorn-manager/blob/edc9374/upgrade_asset/v1alpha1/k8s/pkg/apis/longhorn/v1alpha1/doc.go#L1

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] Remove the keyword `register`
- [x] We should evaluate whether we want to move the Spec/Status definitions into the `k8s/pkg/apis/longhorn/v1beta1/` next to the rest of the definition of the CRD, this should allow for deep copy generation of the status/spec
- [x] We need to benchmark the performance difference between the auto generated and hand crafted deepcopy implementations. 
- [x] ~If a deepcopy implementation is present deepcopy-gen will skip auto generation for it.~

**Additional context**
Add any other context or screenshots about the task request here.

**Comment by jenting** [comment]
@joshimoo any idea/thought on how QA to verify it?

**Comment by khushboo-rancher** [comment]
Keeping this one open as we are analyzing the e2e test failures on branch v1.2.x.

**Comment by khushboo-rancher** [comment]
Validation - **Pass**

The e2e tests look good on v1.2.x https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-lh-tests-ubuntu-amd64/44/
The failed tests are either flaky or being tracked by other issues.

Also, the basic operation of Volume, backup, replica, engine is working fine.
