### ISSUE TITLE
[BACKPORT] [TASK] Remove the feature that skip taking backup/snapshot when the volume head is empty in recurring backup jobs

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#3203]
#3128

**Comment by derekbit** [comment]
PR: https://github.com/longhorn/longhorn-manager/pull/1116

**Comment by khushboo-rancher** [comment]
Reopening this as per testing comment https://github.com/longhorn/longhorn/issues/3128#issuecomment-964645102

**Comment by khushboo-rancher** [comment]
Validated on v1.2.x-head `11/10/2021`

Validation - **Pass**

Validated the upgrade case from v1.2.2 to v1.2.x  and fresh installation of v1.2.x, recurring job is getting triggered even though there is no change in the data.
Detailed testing is done on master as per https://github.com/longhorn/longhorn/issues/3128
