### ISSUE TITLE
[FEATURE] Longhorn UI - hard to find on which longhorn node replicas are running

### ISSUE THREAD

**Issue by mazycool** [longhorn/longhorn#3204]
I'm running kafka on k8s with longhorn as storage driver. I would like to spread replicas widely on all nodes, but by default when kafka pods are created many repilcas are place on the same node. Would be nice to have possibility to list where replicas of each volumes are running from Volume menu in UI. 

The view from node menu where all replicas are running on node are presented only with pv name - it is hard to guess to which pod this pv belongs. Maybe you could add also pvc name or pod name?

**Comment by jenting** [comment]
> but by default when kafka pods are created many repilcas are place on the same node

The replicas by default should be spread across nodes, what is your configuration of `Default Data Locality` (or `dataLocality` inside the StorageClass) and `Replica Node Level Soft Anti-Affinity`?

> Would be nice to have possibility to list where replicas of each volumes are running from Volume menu in UI.

Besides that, you could check which nodes the replicas locate inside the Volume -> PV page.

>  it is hard to guess to which pod this pv belongs. Maybe you could add also pvc name or pod name?

You could hover onto the Volume -> PV/PVC field, it will pop out the PVC name.

**Comment by mazycool** [comment]
> The replicas by default should be spread across nodes, what is your configuration of Default Data Locality (or dataLocality inside the StorageClass) and Replica Node Level Soft Anti-Affinity?

Default Data Locality -> disabled 
Replica Node Level Soft Anti-Affinity -> disabled
> Besides that, you could check which nodes the replicas locate inside the Volume -> PV page.
I would like to have an overview in one place.
Let me explain my issue:
One node is hitting border:
![image](https://user-images.githubusercontent.com/16590575/143017639-894a0f88-9e13-4103-8aa3-40dbfcb8130b.png)
I would like to check which volumes used by which application are running there and decide what I can migrate to another node. So I'm clicking on the "7" and I'm getting another window:
![image](https://user-images.githubusercontent.com/16590575/143017884-f68f5d5c-c28a-4eae-8b4b-85ddfa378616.png)


but I'm not getting information what I expect - I've to now check which PVC is assigned to which POD/APP. In that view would be nice to have more info like:

![image](https://user-images.githubusercontent.com/16590575/143018228-dafb4e12-be54-499a-9631-88e591004b84.png)
>You could hover onto the Volume -> PV/PVC field, it will pop out the PVC name.

Hover is not working for me on MS Edge:
Version 85.0.564.70 (Official build) (64-bit)

**Comment by jenting** [comment]
>> You could hover onto the Volume -> PV/PVC field, it will pop out the PVC name.

> Hover is not working for me on MS Edge:
Version 85.0.564.70 (Official build) (64-bit)

@mazycool It's under Volume page -> Column PV/PVC

@smallteeths could you help check this one for the hover not working on MS Edge?

**Comment by smallteeths** [comment]
The tooltip is displayed correctly in newer versions of the edge browser. We recommend that you update your browser or change to Google Chrome. thanks @mazycool cc @jenting 

<img width="847" alt="截屏2021-11-30 下午1 25 13" src="https://user-images.githubusercontent.com/27733391/143990952-cec240a5-c004-44b2-a519-765167591eea.png">
<img width="1218" alt="截屏2021-11-30 下午1 25 02" src="https://user-images.githubusercontent.com/27733391/143991610-31582a5d-b5a4-40df-9bec-939af431bf9d.png">
