### ISSUE TITLE
[BUG] Volume crash during migrating

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3206]
**Describe the bug**

There are 4 cases related to the volume crash. Some of them will lead to migrating volume hanging there:
1. The old engine crashes only: The migration confirmation works but the migration rollback gets stuck (in state `Healthy`).
2. The new engine crashes only: Both the migration rollback and confirmation get stuck (in state `Healthy`).
3. All old replicas crash: The migration confirmation works but the migration rollback gets stuck (in state `Healthy`).
4. All new replicas crash: The migration rollback works but the migration confirmation gets stuck (in state `Healthy`).

If all nodes/instance manager pods get crashed, the migration  rollback and confirmation get stuck, which is similar to case 2.

**To Reproduce**
1. Deploy StorageClass https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/storageclass-migratable.yaml
2. Deploy a RWX PVC with the above StorageClass
3. Attach the volume to a node
4. Start migration. (Send an attach request with `hodeId` setting to another node for the volume)
5. Enter into the instance manager pod then crash the processes. e.g.,
```
$ kubectl -n longhorn-system exec -it instance-manager-r-537c53aa -- bash
root@instance-manager-r-537c53aa:/# longhorn-instance-manager process ls
{
	"pvc-99743237-a487-4a5d-8ea5-4cf5cf857b1a-r-50a0e42e": {
		"name": "pvc-99743237-a487-4a5d-8ea5-4cf5cf857b1a-r-50a0e42e",
		"binary": "/host/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn",
		"args": [
			"replica",
			"/host/var/lib/longhorn/replicas/pvc-99743237-a487-4a5d-8ea5-4cf5cf857b1a-73aee4b4",
			"--size",
			"1073741824",
			"--listen",
			"0.0.0.0:10015"
		],
		"portCount": 15,
		"portArgs": [
			"--listen,0.0.0.0:"
		],
		"processStatus": {
			"state": "running",
			"errorMsg": "",
			"portStart": 10015,
			"portEnd": 10029
		},
		"deleted": false
	},
	"pvc-99743237-a487-4a5d-8ea5-4cf5cf857b1a-r-6b887a5c": {
		"name": "pvc-99743237-a487-4a5d-8ea5-4cf5cf857b1a-r-6b887a5c",
		"binary": "/host/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn",
		"args": [
			"replica",
			"/host/var/lib/longhorn/replicas/pvc-99743237-a487-4a5d-8ea5-4cf5cf857b1a-73aee4b4",
			"--size",
			"1073741824",
			"--listen",
			"0.0.0.0:10000"
		],
		"portCount": 15,
		"portArgs": [
			"--listen,0.0.0.0:"
		],
		"processStatus": {
			"state": "running",
			"errorMsg": "",
			"portStart": 10000,
			"portEnd": 10014
		},
		"deleted": false
	}
}
root@instance-manager-r-537c53aa:/# longhorn-instance-manager process delete --name pvc-99743237-a487-4a5d-8ea5-4cf5cf857b1a-r-50a0e42e
{
	"name": "pvc-99743237-a487-4a5d-8ea5-4cf5cf857b1a-r-50a0e42e",
	"binary": "/host/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn",
	"args": [
		"replica",
		"/host/var/lib/longhorn/replicas/pvc-99743237-a487-4a5d-8ea5-4cf5cf857b1a-73aee4b4",
		"--size",
		"1073741824",
		"--listen",
		"0.0.0.0:10015"
	],
	"portCount": 15,
	"portArgs": [
		"--listen,0.0.0.0:"
	],
	"processStatus": {
		"state": "stopping",
		"errorMsg": "",
		"portStart": 10015,
		"portEnd": 10029
	},
	"deleted": false
}
```
6. Do migration confirmation (send a detach request with `hostId` setting to the old node) or rollback (send a detach request with `hostId` setting to the new node).

**Expected behavior**
The migrating volume should be salvaged/recovered automatically if possible

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: v1.2.2.

**Additional context**
This issue is found in https://github.com/harvester/harvester/issues/1263. The above reproducing step cannot get the exact result reported in the ticket but the error message is the same.

**Comment by shuo-wu** [comment]
One possible solution in my mind now: The volume controller can do revert by deleting the migration engine & replicas when Longhorn encounters some of the above cases. Then it can handle salvage & auto-recovery as usual and re-create the migration engine & replicas.
cc @joshimoo

**Comment by shuo-wu** [comment]
If this one is not urgent, we can re-evaluate the solution after the volume refactoring https://github.com/longhorn/longhorn/issues/2527

**Comment by khushboo-rancher** [comment]
Validation - In progress

Validated the scenarios from https://longhorn.github.io/longhorn-tests/manual/pre-release/ha/ha-volume-migration/
1. New engine crash - **Pass**
2. Old engine crash - **Pass**
3. Degraded volume - **Fail** The migration of a degraded volume fails on the first attempt however it works fine in the second attempt.
[longhorn-support-bundle_f549513d-6c61-42e8-9854-e949a1bf5675_2021-12-12T04-41-49Z.zip](https://github.com/longhorn/longhorn/files/7698120/longhorn-support-bundle_f549513d-6c61-42e8-9854-e949a1bf5675_2021-12-12T04-41-49Z.zip)
Volume name - pvc-38e77f55-52eb-4a63-b8c2-cfe9f7563dad
Time stamp - around 2021-12-12 04:30:00

cc : @shuo-wu

**Comment by shuo-wu** [comment]
@khushboo-rancher 

It seems that the old engine of this degraded volume is crashed as well... How do you make this volume degraded? Here it's better to exec into the replica instance manager pod then use cmd `longhorn-instance-manager process delete --name <replica process name>` to crash one replica.
```
2021-12-12T04:26:26.619577227Z time="2021-12-12T04:26:26Z" level=warning msg="Cannot find the instance manager for the running instance pvc-38e77f55-52eb-4a63-b8c2-cfe9f7563dad-e-611026a4, will mark the instance as state ERROR"

......
2021-12-12T04:26:26.642946935Z time="2021-12-12T04:26:26Z" level=warning msg="Need to revert the migration since the current engine pvc-38e77f55-52eb-4a63-b8c2-cfe9f7563dad-e-611026a4 is state error" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true migrationNodeID=3.145.54.206 node=3.137.168.47 owner=3.137.168.47 shareEndpoint= shareState= state=attached volume=pvc-38e77f55-52eb-4a63-b8c2-cfe9f7563dad
2021-12-12T04:26:26.643060324Z time="2021-12-12T04:26:26Z" level=warning msg="The migration engine or all migration replicas crashed, will clean them up now" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true migrationNodeID=3.145.54.206 node=3.137.168.47 owner=3.137.168.47 shareEndpoint= shareState= state=attached volume=pvc-38e77f55-52eb-4a63-b8c2-cfe9f7563dad

......
2021-12-12T04:26:27.238392647Z time="2021-12-12T04:26:27Z" level=warning msg="Engine of volume dead unexpectedly, reattach the volume" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true node=3.137.168.47 owner=3.137.168.47 shareEndpoint= shareState= state=attached volume=pvc-38e77f55-52eb-4a63-b8c2-cfe9f7563dad
```

**Comment by khushboo-rancher** [comment]
I used the cmd `longhorn-instance-manager process delete --name <replica process name>` to crash one replica and observed the same behavior.

**Comment by khushboo-rancher** [comment]
I retest the scenario of degraded volume and found the below observation

1. I killed the process of 1 replica inside the IM.
2. Once the volume becomes degraded, immediately, I started the migration - **Failed**
3. If I wait for sometime once the volume becomes degraded and then triggers the migration - **Pass**

[longhorn-support-bundle_3075cb17-4f62-4d0e-8e47-dcd8931e0fdf_2021-12-13T04-08-06Z.zip](https://github.com/longhorn/longhorn/files/7700932/longhorn-support-bundle_3075cb17-4f62-4d0e-8e47-dcd8931e0fdf_2021-12-13T04-08-06Z.zip)

Is this expected?

**Comment by khushboo-rancher** [comment]
Updated the result of validation [here](https://github.com/longhorn/longhorn/issues/3206#issuecomment-991834156) as **Pass**

1. For migration rollback when the old engine node is powered down logged - https://github.com/longhorn/longhorn/issues/3401
2. For degraded volume as @shuo-wu  mentioned https://github.com/longhorn/longhorn/issues/3206#issuecomment-992466781, once the engine is up, the migration will succeed.
