### ISSUE TITLE
[QUESTION] Resize Node

### ISSUE THREAD

**Issue by flippy1345** [longhorn/longhorn#3211]
**Question**

I upgraded my Server/VM, which gave me more storage.
It shows in the UI only what I had.
Now the question is how can I let longhorn "know" there is more storage available to use.

**Environment:**
 - Longhorn version: 1.2.2
 - Kubernetes version:  v1.21.4+k3s1
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 4
   - Memory per node: 16GB
   - Disk type: HDD
   -  VM

**Comment by jenting** [comment]
Could you please check the size in the Node CR is expanded? Under the CR `.status.diskStatus.<disk-name>.storageMaximum`

```shell
kubectl get nodes.longhorn.io -n longhorn-system
```

Then, check the VM's block-level size is expanded also. Go to the VM and run

```shell
stat /var/lib/longhorn/ -fc '{"path":"%n","fsid":"%i","type":"%T","freeBlock":%f,"totalBlock":%b,"blockSize":%s}'
```

the size is calculated by `totalBlock` * `blockSize`.

The last you expanded the disk on the host, make sure the expansion level is on top of `/var/lib/longhorn` path.

**Comment by flippy1345** [comment]
Thx for the response I will check that.

**Comment by flippy1345** [comment]
Okay her a follow up on how I resized my directory:

1. Find out where longhorn is mounted
`df -h /var/lib/longhorn/`
2. Check current size
`df -h -T |grep vg`
3. Modify the partition
`lvresize -v -l +100%FREE /dev/mapper/ubuntu--vg-ubuntu--lv`
4. Extend the filesystem
`resize2fs -p /dev/mapper/ubuntu--vg-ubuntu--lv`
5. Check new size
`df -h -T |grep vg`
