### ISSUE TITLE
[BACKPORT][FEATURE] podAntiAffinity for csi-attacher/csi-provisioner/csi-resizer/csi-snapshotter

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#3213]
https://github.com/longhorn/longhorn/issues/2894

**Comment by derekbit** [comment]
PR: https://github.com/longhorn/longhorn-manager/pull/1120

**Comment by kaxing** [comment]
Validation - **PASSED**

Backport PR tested with latest v1.2.x-head image set (20211105).

Details in [issues/2894#issuecomment-961726544](https://github.com/longhorn/longhorn/issues/2894#issuecomment-961726544)
