### ISSUE TITLE
[BUG] - documentation link for alerts broken

### ISSUE THREAD

**Issue by Martin-Weiss** [longhorn/longhorn#3215]
**Describe the bug**
Check this URL https://longhorn.io/docs/1.2.2/monitoring/integrating-with-rancher-monitoring/ and click on "set up alerts"... in Rancher UI.

**To Reproduce**
See above

**Expected behavior**
Link should work

**Comment by Martin-Weiss** [comment]
Maybe the link should point to https://longhorn.io/docs/1.2.2/monitoring/alert-rules-example/ ?

**Comment by jenting** [comment]
The section https://longhorn.io/docs/1.2.2/monitoring/prometheus-and-grafana-setup/#install-and-configure-prometheus-server provides the link to https://longhorn.io/docs/1.2.2/monitoring/alert-rules-example already.

**Comment by jenting** [comment]
Close this issue since it's a doc change.
