### ISSUE TITLE
[IMPROVEMENT] Make GI as default value in volume expand screen

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3217]
**Description**
Can we make Gi as default value in volume expansion.

<img width="527" alt="Screen Shot 2021-10-29 at 3 53 49 PM" src="https://user-images.githubusercontent.com/60111667/140218605-4a2ae6cc-b0e8-4049-9cca-463a0210f970.png">

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with master image set (ui: bdb3260).

The default unit will be Gi instead of Mi, even when the volume is less than a Gi:
![image](https://user-images.githubusercontent.com/602540/141266185-178afe9d-8f98-4e1a-9707-889853cefa27.png)
