### ISSUE TITLE
[TASK] Fix flaky test case : test_node_eviction_soft_anti_affinity

### ISSUE THREAD

**Issue by chanow816** [longhorn/longhorn#3221]
**What's the task? Please describe.**
Flaky test case[ tests.test_node.test_node_eviction_soft_anti_affinity](https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64-nfs/12/testReport/junit/tests/test_node/test_node_eviction_soft_anti_affinity/) in nightly build. 

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x]  Find the root cause
- [x]  Fix it or file issue if it's product issue

**Additional context**
From observation and reproduce process, this is an automation script issue

**Comment by chanow816** [comment]
Root cause and PR for this issue at https://github.com/longhorn/longhorn-tests/pull/785

**Comment by chanow816** [comment]
PR merged, I'll close this issue.

**Comment by innobead** [comment]
@chanow816 let's close after the test case will pass in the next build.

**Comment by chanow816** [comment]
Passed in recent build
