### ISSUE TITLE
[BACKPORT] [BUG] Restored volume wrongly restarts restoration during migration 

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#3223]
#3210

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn Version: 1.2.x `Fri Nov 12 01:07:07 AM EET 2021`

Test steps: 
1. Prepare a Backup
2. Create a StorageClass with fields migratable and fromBackup set.
3. Use the StorageClass to create a PVC with the accessMode ReadWriteMany
4. Attach the volume.
5. Start the migration by sending an attach request with parameter hostId set to another node
6. Check if the restore is not wrongly restarted. (PASSED)
