### ISSUE TITLE
[QUESTION] Authentication issues using UI

### ISSUE THREAD

**Issue by 0x4c6565** [longhorn/longhorn#3225]
**Question**

**Environment:**
 - Longhorn version: v1.2.2
 - Kubernetes version: RKE v1.21
 - Node config
   - OS type and version: CentOS 7.9.2009
   - CPU per node: 4
   - Memory per node: 8GB
   - Disk type: Block device / SSD
   - Network bandwidth and latency between the nodes: 10Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMware

**Additional context**

After installing Longhorn into RKE cluster via Rancher UI as per documentation, browsing Longhorn UI shows the following auth errors:

```
userextras.authentication.k8s.io "admin" is forbidden: User "system:serviceaccount:cattle-impersonation-system:cattle-impersonation-user-7t885" cannot impersonate resource "userextras/username" in API group "authentication.k8s.io" at the cluster scope
```

```
userextras.authentication.k8s.io "local://user-7t885" is forbidden: User "system:serviceaccount:cattle-impersonation-system:cattle-impersonation-user-7t885" cannot impersonate resource "userextras/principalid" in API group "authentication.k8s.io" at the cluster scope
```

![image](https://user-images.githubusercontent.com/7476213/140949053-fb9b073b-019d-45b6-866f-aef0afae3910.png)
![image](https://user-images.githubusercontent.com/7476213/140949097-87bfe3ca-34d1-421c-b968-69eaf5bc0fe4.png)

Is Longhorn / Rancher misconfigured somehow?

**Comment by innobead** [comment]
cc @khushboo-rancher

**Comment by 0x4c6565** [comment]
Just to update - this issue appears to have resolved without any intervention, however was apparent for at least an hour post-installation. Odd!

I'll close this for now, and reopen with further details if it does reoccur

**Comment by khushboo-rancher** [comment]
Looks like you are accessing the Longhorn using Rancher proxy. I'm suspecting may be some pods/services in Rancher system was not up at this time. Next time if you encounter this can you please check the pods and services in the Rancher system?
