### ISSUE TITLE
[Backport] [FEATURE] move filesystem expansion into the csi driver

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3227]
Backport the feature https://github.com/longhorn/longhorn/issues/2794

**Comment by khushboo-rancher** [comment]
@joshimoo If this duplicated, please close this and point me to correct ticket.

**Comment by joshimoo** [comment]
related issue, they should be tested together than closed.
https://github.com/longhorn/longhorn/issues/3240

**Comment by khushboo-rancher** [comment]
Validation - **Pass**

Validated with v1.2.3-rc1
