### ISSUE TITLE
[BUG] Tooltip of a backup taken shows 0 size if a snapshot is taken just before it

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3228]
**Describe the bug**
Any backup taken just after a snapshot or a recurring backup without writing in interval shows 0 size in the tool tip. This is little confusing as the progress of the backup shows 100% (backup status) but the size shows 0 (snapshot size).
<img width="1124" alt="Screen Shot 2021-11-09 at 3 13 56 PM" src="https://user-images.githubusercontent.com/60111667/141021608-7b0127fc-ce8d-43ab-8913-5d06fa77bbf6.png">
<img width="1764" alt="Screen Shot 2021-11-09 at 3 14 29 PM" src="https://user-images.githubusercontent.com/60111667/141021632-c1deafa4-3f01-4b7e-95b0-ef9eac065bdd.png">
<img width="1773" alt="Screen Shot 2021-11-09 at 3 14 48 PM" src="https://user-images.githubusercontent.com/60111667/141021648-59c1f377-5ab0-4476-9ef3-3c34a4e33312.png">

**To Reproduce**
1. Write data to a volume. (200 MB)
2. Take a snapshot.
3. Just after the snapshot, take a backup
4. Scroll over the backup, it shows 0 size.

**Expected behavior**
Can we get the size of the backup as it gets little confusing or size of backup tag in tooltip?

**Environment:**
 - Longhorn version: Master-head `11/09/2021`

**Comment by smallteeths** [comment]
The data used on the front end is the `snapshotList` and the current `volume's backupStatus`. If we need to display the actual size of the backup, it is better to add the actualsize property to the `volume's backupStatus` via the back end .
@jenting. cc @innobead

<img width="740" alt="截屏2021-11-11 下午2 53 14" src="https://user-images.githubusercontent.com/27733391/141255066-ffe1d789-613a-4628-90e2-4a0374c61367.png">

<img width="899" alt="截屏2021-11-11 下午2 23 56" src="https://user-images.githubusercontent.com/27733391/141254959-1f23c885-272d-4cd4-a678-6194fcca48d6.png">

**Comment by kaxing** [comment]
A quick check with master branch, even when the last snapshot is 0 Bi the last backup will display in full size,
![image](https://user-images.githubusercontent.com/602540/147729795-8ba46a1e-f9ed-4e3d-b051-41f6ebc9be2e.png)

**Comment by kaxing** [comment]
Validation - **PASSED**

Check again with master-head image. Now that latest snapshot with backup will display in backup size instead of 0 Bi.

| Volume snapshot before backup | Volume snapshot with backup |
| :- | :- |
| ![image](https://user-images.githubusercontent.com/602540/148215318-0bd661b8-3e43-44d8-a04e-2b70f54aee18.png) | ![image](https://user-images.githubusercontent.com/602540/148215383-c5fb8da3-aa4a-4cb6-91c5-98d8eee1f800.png) |
