### ISSUE TITLE
[BUG] mount fail

### ISSUE THREAD

**Issue by liushifa** [longhorn/longhorn#3229]
Warning  FailedMount  12m  kubelet, k8s-106  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data default-token-bbvns]: timed out waiting for the condition
  Warning  FailedMount  10m  kubelet, k8s-106  MountVolume.MountDevice failed for volume "pvc-97b1f277-a0d4-434d-b243-3dd9c7e1a311" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: /bin/systemd-run
Mounting arguments: [--description=Kubernetes transient mount for /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-97b1f277-a0d4-434d-b243-3dd9c7e1a311/globalmount --scope -- /bin/mount -t nfs -o vers=4.1,noresvport,soft,intr,timeo=30,retrans=3 172.16.66.191:/pvc-97b1f277-a0d4-434d-b243-3dd9c7e1a311 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-97b1f277-a0d4-434d-b243-3dd9c7e1a311/globalmount]
Output: Running scope as unit run-25999.scope.
mount: wrong fs type, bad option, bad superblock on 172.16.66.191:/pvc-97b1f277-a0d4-434d-b243-3dd9c7e1a311,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
  Warning  FailedMount  2m41s (x4 over 8m48s)  kubelet, k8s-106  (combined from similar events): MountVolume.MountDevice failed for volume "pvc-97b1f277-a0d4-434d-b243-3dd9c7e1a311" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: /bin/systemd-run
Mounting arguments: [--description=Kubernetes transient mount for /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-97b1f277-a0d4-434d-b243-3dd9c7e1a311/globalmount --scope -- /bin/mount -t nfs -o vers=4.1,noresvport,soft,intr,timeo=30,retrans=3 172.16.66.191:/pvc-97b1f277-a0d4-434d-b243-3dd9c7e1a311 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-97b1f277-a0d4-434d-b243-3dd9c7e1a311/globalmount]
Output: Running scope as unit run-29649.scope.
mount: wrong fs type, bad option, bad superblock on 172.16.66.191:/pvc-97b1f277-a0d4-434d-b243-3dd9c7e1a311,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
  Warning  FailedMount  86s (x7 over 17m)  kubelet, k8s-106  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[default-token-bbvns data]: timed out waiting for the condition

**Comment by jenting** [comment]
Could you plz provide some basic env information to us? Is this volume RWO or RWX volume?

```
**Environment:**
 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
```

**Comment by jenting** [comment]
Besides that, it'd good to provide us with the support bundle, to help us see the CSI-related log.
You could attach it here or send it to longhorn-support-bundle@suse.com.

**Comment by hippopos** [comment]
i meet the same error. fix with install nfs-utils : yum install nfs-utils

**Comment by shuo-wu** [comment]
It seems that you are using RWX volume. Can you check if the requirements are satisfied first? If it does not work, you can then send the support bundle to us.

https://longhorn.io/docs/1.2.2/advanced-resources/rwx-workloads/#requirements
