### ISSUE TITLE
[BUG] longhorn-ui has a warning message in the browser's console

### ISSUE THREAD

**Issue by smallteeths** [longhorn/longhorn#3230]
**Describe the bug**
There is a warning message in the browser's console. as shown

<img width="641" alt="截屏2021-11-10 上午11 50 51" src="https://user-images.githubusercontent.com/27733391/141056757-2552efe6-14ae-4395-ba62-fdccb336c477.png">

**To Reproduce**
1. Create a volume
2. Check the browser console

**Expected behavior**
The time format returned by the back-end should be converted at the front-end to eliminate warning messages.

**Comment by khushboo-rancher** [comment]
Validated on Longhorn-v1.2.x-head `df6ad60` and Longhorn master-head - `d250d9c` - `11/15/2021`

Validation - **Pass**

No warning in observed on console. Validated on the Longhorn UI using ingress and Rancher proxy.

**Comment by innobead** [comment]
@smallteeths let's backport this to 1.1.3.

**Comment by innobead** [comment]
@khushboo-rancher 1.1.3 merged.

**Comment by khushboo-rancher** [comment]
Thanks, working on v1.1.3-head as well now.
