### ISSUE TITLE
[TEST] nightly build sometimes fails for recurring job cases

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#3233]
**What's the test to develop? Please describe.**
The tests sometimes fail, mostly caused by the snapshot/backup counter. Possibly a side-effect from https://github.com/longhorn/longhorn/issues/3203.

**Describe the items of the test development (DoD, definition of done) you'd like.**
- [x] Have consistent test results.

**Additional context**
https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-lh-upgrade-tests-ubuntu-amd64/51/testReport/junit/tests/test_recurring_job/

**Comment by c3y1huang** [comment]
@chanow816 can you take this one?

**Comment by chanow816** [comment]
Most failed case due to timing issue. I sent PR[#794](https://github.com/longhorn/longhorn-tests/pull/794) for review, thanks

**Comment by chanow816** [comment]
After PR#794 merged, most recurring job cases become more stable then before, except test_recurring_job.test_recurring_job will fail everytime. 
Need find time to verify.

**Comment by chanow816** [comment]
After PR https://github.com/longhorn/longhorn-tests/pull/838 merged, test_recurring_job.test_recurring_job not failed in recent e2e daily build.
For detached volume recurring job fail, it's product issue and logged in https://github.com/longhorn/longhorn/issues/3470.

If it's OK I think this task can be closed
