### ISSUE TITLE
[BUG] Volume size in Mi will be increased in the volume expanding dialog

### ISSUE THREAD

**Issue by kaxing** [longhorn/longhorn#3236]
**Describe the bug**
As in latest master, expanding volume size will default to Gi with the Expand Volume dialog.
If the volume is less than a Gi, it will be automatically converted into Gi, but the size will be increased.

**To Reproduce**
1. Create Volume with size in Mi, and make it less than a Gi, for example 111Mi(~=0.1083984375Gi)
2. Expand the volume from the volume dropdown menu on the left column
3. 111Mi will be shown as 0.109375Gi

**Expected behavior**
111Mi should be 0.108398Gi
The volume size number in the expanding prompt should consistent as in volume with Gi size

**Log**
![image](https://user-images.githubusercontent.com/602540/141275065-c8669122-ab96-471e-b305-f233509383d6.png)

**Environment:**
 - Longhorn version: master
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s

**Additional context**
Also, the decimal places are not the same in between the Create Volume and Expand Volume dialog the length is not the same.

**Comment by innobead** [comment]
It's a side effect for #3217 , but for a better experience, maybe we should adapt to the right unit of the current volume size.

**Comment by smallteeths** [comment]
The size returned by the backend is 117440512. 117440512 / 1024 / 1024 = 112Mi, and the frontend is showing the correct size. I'm not sure why I create a volume of 111 Mi and the backend returns 112 Mi. Is this because the block storage must meet some condition? @shuo-wu  cc @kaxing 

<img width="599" alt="截屏2021-11-12 下午2 18 24" src="https://user-
images.githubusercontent.com/27733391/141419869-bb358928-535b-4f50-9d93-f0e6517203d4.png">

**Comment by innobead** [comment]
ref: https://github.com/longhorn/longhorn/issues/2624 this is on purpose due to this fix to make sure the volume size is times of 2*1024*1024 B.

**Comment by kaxing** [comment]
Adding a note here about current size limit for the future traveler:

```markdown
- Create Volume
  - Create size in Gi
    - up two decimal places
  - Create size in Mi
    - only allow round number

- Expand Volume
  - Expand size in Gi
    - `Expansion volume size must be a multiple of Mi (1Gi = 1024Mi). e.g 1361.919921875`
      - The suggested number after e.g. is calculated based on input number
  - Expand size in Mi
    - only allow round number
```
