### ISSUE TITLE
[QUESTION] pod can not attach volume.

### ISSUE THREAD

**Issue by muqp** [longhorn/longhorn#3237]
**Question**
I have a k8s cluster with single node.The longhorn replicas is one.Pod can not attach the volume.The PV and PVC status is bound.Longhorn UI show the volume's state switches between attaching and detaching.
This is a screenshot:
![image](https://user-images.githubusercontent.com/52477868/141294962-496450ca-5e05-4f94-9f15-664d38c1aaf6.png)
![image](https://user-images.githubusercontent.com/52477868/141295386-3fe19b05-7454-42ce-b19a-828d75654a50.png)

**Environment:**
 - Longhorn version:1.0.0
 - Kubernetes version:1.16.3
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**

**Comment by jenting** [comment]
Would you please provide us with the support bundle? We'd like to see the CSI-related plugins log.
You could attach to here or send to longhorn-support-bundle@suse.com

**Comment by jenting** [comment]
@muqp 
Besides that, we notice that you're using Kubernetes 1.16.3, but start from Longhorn v1.2.0, the minimal supported Kubernetes version is 1.18.x. https://longhorn.io/docs/1.2.0/deploy/important-notes/#notes

**Comment by muqp** [comment]
> Would you please provide us with the support bundle? We'd like to see the CSI-related plugins log. You could attach to here or send to [longhorn-support-bundle@suse.com](mailto:longhorn-support-bundle@suse.com)

I have send the report to this email.My id is muqipeng@cetccloud.com.Wish your help.

**Comment by muqp** [comment]
> @muqp Besides that, we notice that you're using Kubernetes 1.16.3, but start from Longhorn v1.2.0, the minimal supported Kubernetes version is 1.18.x. https://longhorn.io/docs/1.2.0/deploy/important-notes/#notes

Sorry.It's my fault.My longhorn version is 1.0.0.

**Comment by jenting** [comment]
We did a lot of enhancement after 1.0.0, not sure what's the reason you're still using 1.0.0 version?

**Comment by muqp** [comment]
> We did a lot of enhancement after 1.0.0, not sure what's the reason you're still using 1.0.0 version?

Which version is appropriate with kubernetes 1.16.3.

**Comment by jenting** [comment]
> > We did a lot of enhancement after 1.0.0, not sure what's the reason you're still using 1.0.0 version?
> 
> Which version is appropriate with kubernetes 1.16.3.

Longhorn 1.1.2 https://longhorn.io/docs/1.1.2/deploy/install/#installation-requirements

**Comment by muqp** [comment]
> > > We did a lot of enhancement after 1.0.0, not sure what's the reason you're still using 1.0.0 version?
> > 
> > 
> > Which version is appropriate with kubernetes 1.16.3.
> 
> Longhorn 1.1.2 https://longhorn.io/docs/1.1.2/deploy/install/#installation-requirements

OK.I'll try.

**Comment by muqp** [comment]
> > > We did a lot of enhancement after 1.0.0, not sure what's the reason you're still using 1.0.0 version?
> > 
> > 
> > Which version is appropriate with kubernetes 1.16.3.
> 
> Longhorn 1.1.2 https://longhorn.io/docs/1.1.2/deploy/install/#installation-requirements

I got the log of instance manager which show "Backing-store longhorn is not supported".What does it mean?

**Comment by muqp** [comment]
I have resolved this problem with rebuild tgt.
