### ISSUE TITLE
[BUG] UI sometimes does not show snapshots

### ISSUE THREAD

**Issue by myoung34** [longhorn/longhorn#3238]
**Describe the bug**

I just set up longhorn via helmgenerator (helm chart 1.2.2)

Im trying to set up snapshots for a new volume

Sometimes the UI lets me attach the schedule, sometimes it doesnt
Sometimes the UI shows the schedule and ability to take snapshots, sometimes it doesnt.

**To Reproduce**
1. Go to a volume
2. Add an existing snapshot
3. Get angry and refresh a lot

**Expected behavior**

Consistent UI

**Log**

not sure where to find logs in this scenario

**Environment:**
 - Longhorn version: 1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm via kustomize in ArgoCD
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
```
$ k get nodes
NAME        STATUS   ROLES                  AGE   VERSION
cluster22   Ready    control-plane,master   21d   v1.21.5+k3s2
cluster14   Ready    control-plane,master   21d   v1.21.5+k3s2
cluster21   Ready    <none>                 21d   v1.21.5+k3s2
cluster24   Ready    <none>                 17d   v1.21.5+k3s2
cluster12   Ready    control-plane,master   21d   v1.21.5+k3s2
cluster13   Ready    <none>                 21d   v1.21.5+k3s2
cluster23   Ready    <none>                 21d   v1.21.5+k3s2
cluster11   Ready    <none>                 21d   v1.21.5+k3s2
```
 - Node config
   - OS type and version: ubuntu latest lts
   - CPU per node: 👓 
   - Memory per node: 👓 
   - Disk type(e.g. SSD/NVMe): 👓 
   - Network bandwidth between the nodes: 👓 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): my garage
 - Number of Longhorn volumes in the cluster: 1

**Additional context**

https://www.astronaut.ninja/rancher1.mp4
https://www.astronaut.ninja/rancher2.mp4

**Comment by myoung34** [comment]
```
10.42.0.0 - - [11/Nov/2021:18:00:40 +0000] "POST /v1/volumes/pvc-2d167094-b8b1-4be5-8510-5c53a05448cf?action=snapshotList HTTP/1.1" 200 808 "https://longhorn.marcyoung.us/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
time="2021-11-11T18:01:00Z" level=debug msg="Forwarding request to 10.42.3.52:9500"
10.42.0.0 - - [11/Nov/2021:18:01:00 +0000] "POST /v1/volumes/pvc-2d167094-b8b1-4be5-8510-5c53a05448cf?action=snapshotList HTTP/1.1" 200 808 "https://longhorn.marcyoung.us/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
time="2021-11-11T18:01:20Z" level=debug msg="Forwarding request to 10.42.3.52:9500"
10.42.0.0 - - [11/Nov/2021:18:01:20 +0000] "POST /v1/volumes/pvc-2d167094-b8b1-4be5-8510-5c53a05448cf?action=snapshotList HTTP/1.1" 200 808 "https://longhorn.marcyoung.us/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
```

**Comment by jenting** [comment]
Could you please open the browser developer mode to see if there is any error?
Besides that, if you are using Traefik 2.x, you need to check this [KB](https://longhorn.io/kb/troubleshooting-traefik-2.x-as-ingress-controller/).

**Comment by myoung34** [comment]
@jenting This did in fact solve it

Thanks!
