### ISSUE TITLE
[BUG] Volume attachment take long time, which may be caused by the replica controller queue being flooded by the backing image events

### ISSUE THREAD

**Issue by maxiloEmmmm** [longhorn/longhorn#3242]
**Question**
there is no problem when there are few resources
but very slow for attach detach on more backup and restore
pod 40+, some pod includes multi volume, exp: 10+
every pod has one volume base on backing storage class, backing file like os image, size 800M+ or 6G+
volume 250+
backup 40+
restore 40+
**Environment:**
 - Longhorn version: 1.2.2(upgrade from 1.1.2)
 - Kubernetes version: 1.18+
 - Node config * 4
   - OS type and version centos7.6
   - CPU per node: 32
   - Memory per node: 128G
   - Disk type longhorn default disk: hdd 512G
   - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Additional context**
Tried
if modify queue.AddRateLimited --> queue.Add on replicas、engine and volume controller's enqueue func(longhorn-manager)
example: 
https://github.com/longhorn/longhorn-manager/blob/b661af0c6315d0f910a3400b650b0e9fba2df577/controller/replica_controller.go#L377
the performance will be normal, look like good
why use queue.AddRateLimited?
Isn't it just on  because of failure?

**delay**
add log to record limit delay(just for `longhorn-replica` controller) and use go vendor mod build, find resource delay is very long time
log position: https://github.com/kubernetes/client-go/blob/e627be7959e730f91a38c18674c29b0256c4bb2e/util/workqueue/delaying_queue.go#L243
<img width="955" alt="time" src="https://user-images.githubusercontent.com/16779121/141677913-fe339c43-4a3c-4cc3-a2e4-55e62b893003.png">

**metrics**
![image](https://user-images.githubusercontent.com/16779121/141725590-b6cc2115-a9c3-4f27-87c6-4012d3d2347c.png)

**Comment by maxiloEmmmm** [comment]
this occurs in the second cluster

**Comment by shuo-wu** [comment]
If the rate-limited queues of the engine/replica/volume controllers are overwhelmed, the attachment/detachment does get delayed for a long time.
Notice that you mentioned `very slow for attach detach on more backup and restore`, do you mean the cluster works fine if there are not too many restored volumes or backups in the backup target? Or you are just not sure if that can be a cause.

**Comment by maxiloEmmmm** [comment]
@shuo-wu hi~
v1.1.2 
1. not use snapshot(csi snapshot)
2. no pod has mount too many volume

upgrade to v1.2.2 
1. use snapshot to restore pvc
2. some pod has mount too many volume
3. after suddenly slowing down, the volume can't be attached for nearly 6 hours, during this period, I tried to manually change the replica CRD field(like spec.logRequest), but the controller did not respond. I found that it had been delayed in the queue for nearly 3 hours
4. use queue either not rate limit queue, it looks normal, I also think this is not the core issue, but its impact, I found that reading and writing are still slow, so I'm not sure what the problem is. attached is very slow, which is just a phenomenon I observed, maybe there are some problems that haven't been observed

**Comment by shuo-wu** [comment]
OK, got it! If this issue is related to backup or restore is unclear. The statement is just describing your current env.

What's your replica count when this issue is triggered? 250+ * 3? You can check the replica count on each node via Longhorn UI - Node page.

Notice that the underlying disks of your cluster nodes are all HDD, which are shared by all replicas on each node. If there are too many replicas, the IO performance is definitely seriously degraded.

**Comment by maxiloEmmmm** [comment]
replica count = volume count * 3,  count is ok
![image](https://user-images.githubusercontent.com/16779121/142568562-7037771d-f202-43b7-93f2-0a964c96ccd5.png)
![image](https://user-images.githubusercontent.com/16779121/142568931-61e5b132-ea2c-49b4-afb8-496a465355a7.png)

each node 3.6T hdd 
![image](https://user-images.githubusercontent.com/16779121/142567997-1a978023-0719-4fba-995c-40140889eeff.png)

**Comment by shuo-wu** [comment]
OK. Just checked with @PhanLe1010. Some scalability issues are probably introduced in v1.2.x. The attachment will take a long time as well when there are 450+ volumes in a 100-node cluster. We will investigate and keep posting for it.
https://github.com/longhorn/longhorn/issues/2986#issuecomment-929751211

**Comment by maxiloEmmmm** [comment]
@shuo-wu
Hi, it's nice to meet you again!
I looked at the test and found that it was different from the environment here. There were a few things I was worried about
1. There is only a small amount of work in the environment here, and the master also carries the work of work, exp: 3 node, which causes replicas to be scattered on these nodes instead of other nodes
2. There should be cases where many volumes are mounted on some pods, so that multiple volumes can be mounted on one node at the same time
exp: 
volume0(base on backing file storage class) 20G volume1 11G volume2 12G ….. volume20 30G,
Because the total number of disks may only be one of the reasons for the problem, mounting many disks should also be considered? exp:cause queue by lock /var/run/longhorn-iscsi.lock to fetch target id on same node?(An example can ignore it)

**Comment by maxiloEmmmm** [comment]
@shuo-wu  hello，synchronize some information
I found that the replicas controller relies on backingimage
I counted up to 60W replicas enqueuereplica triggered by backingimage in more than an hour

In the figure, it is printed every five seconds
![image](https://user-images.githubusercontent.com/16779121/143561874-e19e8d82-e4c8-40d0-9933-cf74acfd52b0.png)

**Comment by shuo-wu** [comment]
@maxiloEmmmm Thank you for the info! This should be helpful! The replica controller being triggered by backing images for 600,000+ times is definitely abnormal. I will follow this.

**Comment by maxiloEmmmm** [comment]
@shuo-wu
This should be caused by 30s resync
Moreover, when a backingimage is associated with multiple disks (diskfilestatusmap)
It will be repeated and retransmitted. For example, three will be triggered three times
All associated replicas are triggered each time

**Comment by shuo-wu** [comment]
> @shuo-wu This should be caused by 30s resync Moreover, when a backingimage is associated with multiple disks (diskfilestatusmap) It will be repeated and retransmitted. For example, three will be triggered three times All associated replicas are triggered each time

Yes. 30s force resync interval for all controllers in Longhorn is a known issue. But I didn't realize that it would lead to this kind of flooded enqueuing when the replica controller handles backing image change. BTW, does every replica has a backing image in your cluster?

**Comment by shuo-wu** [comment]
I just checked the backing image enqueuing logic in the replica controller. It does enqueue too many irrelevant replicas for each backing image. Here is the patch. If possible, can you take a quick try and see if it works? Or I can create a PR then request QAs to help test it.
```
diff --git a/controller/replica_controller.go b/controller/replica_controller.go
index 21eeea91..30a95b00 100644
--- a/controller/replica_controller.go
+++ b/controller/replica_controller.go
@@ -778,14 +778,16 @@ func (rc *ReplicaController) enqueueBackingImageChange(obj interface{}) {
 		}
 	}

+	replicas, err := rc.ds.ListReplicasByNodeRO(rc.controllerID)
+	if err != nil {
+		utilruntime.HandleError(fmt.Errorf("failed to list replicas on node %v for backing image %v: %v", rc.controllerID, backingImage.Name, err))
+		return
+	}
 	for diskUUID := range backingImage.Status.DiskFileStatusMap {
-		replicas, err := rc.ds.ListReplicasByDiskUUID(diskUUID)
-		if err != nil {
-			utilruntime.HandleError(fmt.Errorf("failed to list replicas in disk %v for backing image %v: %v", diskUUID, backingImage.Name, err))
-			continue
-		}
 		for _, r := range replicas {
-			rc.enqueueReplica(r)
+			if r.Spec.DiskID == diskUUID && r.Spec.BackingImage == backingImage.Name {
+				rc.enqueueReplica(r)
+			}
 		}
 	}

```

**Comment by PhanLe1010** [comment]
Just leave a note here. QA can use my scale test script to standardize all the scalability tests. I will push it to longhorn-test repo

**Comment by maxiloEmmmm** [comment]
@shuo-wu thk u reply
this may be the information you need
![image](https://user-images.githubusercontent.com/16779121/143967180-970ecc1b-1b02-4470-aa98-347581c8a947.png)
![image](https://user-images.githubusercontent.com/16779121/143967348-782e5430-b517-417c-8ec2-2a944e9f5001.png)

**Comment by shuo-wu** [comment]
YES. That's what I am looking for.

It's acceptable for now if the enqueuing number is 2N * replica count for every 30s. 
Without the patch, **each** backing image would lead to all replicas being enqueued. After the patch, only the replicas that are using the backing image will be enqueued. This is the main improvement.

**Comment by maxiloEmmmm** [comment]
@shuo-wu ok
It feels pretty good. It's still being tested here. I'll give you feedback later

**Comment by shuo-wu** [comment]
I just tested the patch by:
1. Launch a 3-node cluster
2. Launch 10 backing images and 5 of the backing images are used by replicas
3. Launch 35 pods with 265 volumes in total. Each volume contains 3 replicas scheduled to different nodes. And each volume contains one backing image.

![Screen Shot 2021-12-02 at 4 36 44 PM](https://user-images.githubusercontent.com/47542419/144386729-a9da7172-43d2-43de-b17d-7d3d84e4c5a3.png)
![Screen Shot 2021-12-02 at 4 36 28 PM](https://user-images.githubusercontent.com/47542419/144386740-316078ec-af46-4301-8af1-0438c0af1def.png)


**After** all volumes become running, attaching a newly created volume with a backing image set takes around 12 seconds.
```
[longhorn-manager-bxrj4] 61.222.202.238 - - [02/Dec/2021:08:12:39 +0000] "POST /v1/volumes/vol-test?action=attach HTTP/1.1" 200 2785 "https://137.184.3.241/k8s/clusters/c-spnmq/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"
......
[longhorn-manager-f5hwn] time="2021-12-02T08:12:51Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"vol-test\", UID:\"5107211e-ec43-4ce0-b732-0e2e23c0c315\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"86710\", FieldPath:\"\"}): type: 'Normal' reason: 'Attached' volume vol-test has been attached to shuo-k8s-worker1"
```

As for the **1-hour** enqueuing count, **in the env mentioned above**, the backing-image-related enqueuing count is around one-tenth of the total count:
```
time="2021-12-02T07:12:02Z" level=debug msg="Replica controller BI-related enqueuing count 86146, total enqueuing count 731114"
......
time="2021-12-02T08:12:07Z" level=debug msg="Replica controller BI-related enqueuing count 117346, total enqueuing count 953114"
```

**Comment by PhanLe1010** [comment]
@shuo-wu I just push a draft PR for scalability test at https://github.com/longhorn/longhorn-tests/pull/834. Would you want to give this PR a try using the script? I haven't finished the instruction for how to use the script but it should be up soon.

**Comment by innobead** [comment]
@shuo-wu moving to the `ready for testing` state.

**Comment by kaxing** [comment]
Validating in progress,

Testing with master-head images.

With 1 control + 3 workers cluster(8G RAM each instances), the cluster can hold up at 300 volumes, with 5 backing images being used from 10 images. However if pushing slightly more volumes, the cluster will become unstable.

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with master-head images (backing-image-manger: v2_20210820, longhorn-manager: 3fb99ac1)

With baseline test environment describes in: [scalability-with-backing-image](https://github.com/longhorn/longhorn-tests/blob/master/docs/content/manual/release-specific/v1.2.3/test-scalability-with-backing-image.md)
- The workload finished in around 60mins.

Detail of the nodes spec.:
- 1 control node and 3 worker nodes
- m5.xlarge (8G RAM, all ebs gp2 volumes)
- Kubernetes version: RKE1 v1.20.12

---
Extended test: Migrating volumes and its replicas by adding a new node first
- Adding recurring snapshot job that backup every 5 minutes with 3 concurrencies (adding a bit more pressure to the cluster)
- The old node can be safely removed in about 5 hours
- Backing Image Manager(s) works as expected in between the volume migration.
