### ISSUE TITLE
[TASK] Make all pipelines running on K3s + SLES by default

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#3243]
**What's the task? Please describe.**

Right now, we are running test pipelines on RKE1 when the arch is amd6, but K3s for amd64. We should make the execution simple w/o any implicit design like this. 

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] All pipelines should run on K3s amd64/arm64
- [x] Use the latest SLES images by default instead of Ubuntu
- [ ] All pipelines can be run on other distros on demand (ex: rke2, rke1) and keep running on the latest stable versions instead of hard-coded version

**Additional context**
Add any other context or screenshots about the task request here.

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by jenting** [comment]
I think this issue should be addressed already.

**Comment by khushboo-rancher** [comment]
We are working on it. Currently our daily nightly integration for master runs on ubuntu.

**Comment by meldafrawi** [comment]
Implemented k3s, will continue tracking RKE2 effort in https://github.com/longhorn/longhorn/issues/3251
