### ISSUE TITLE
[TASK] Nightly tests: add support for k3s and RKE2 for amd64 architecture.

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#3251]
**What's the task? Please describe.**
Currently we're running nightly integration tests using RKE1 for amd64 arch, and k3s for arm64 arch.
We need to also add support for k3s and RKE2 for amd64 as well

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] add k3s support for amd64 and arm64 arch
- [x] add RKE2 support for amd64 and arm64 arch

**Additional context**
N/A

**Comment by meldafrawi** [comment]
k3s support added for both amd64 and arm64 architecture.

https://github.com/longhorn/longhorn/issues/3243

**Comment by innobead** [comment]
Expecting rke2 :)

**Comment by meldafrawi** [comment]
RKE2 support is added
