### ISSUE TITLE
[BUG] Instance process is still running when the corresponding engine/replica CR is gone

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3255]
**Describe the bug**
When a replica is created with desired state `running` then gets removed immediately, the following case may be triggered:
1. The controllers send the instance process creation requests to the instance manager
2. The instance manager pods launch a process for it. But the instance manager CR has not synced with the pod and updated the instance map.
3. The controllers find the deletion timestamp then try to do clean up for the engine/replica. At this moment, the engine/replica CR has no instance manager name hence the actual process deletion will be skipped. 

Finally, the process becomes an orphan process but it's capable of r/w replica data, which is dangerous.

This issue is found when testing the fix of #3206

**To Reproduce**
Follow the test in #3206: When crashing all replicas and sending migration confirmation/rollback requests simultaneously, we may find there are some orphan processes in some replica instance manager pods:
```
~ kubectl -n longhorn-system exec -it <replica instance manager pod name> -- bash
# longhorn-instance-manager process ls
```

**Expected behavior**
There should not be any orphan process.

**Log**
N/A

**Environment:**
 - Longhorn version: v1.2.2

**Comment by khushboo-rancher** [comment]
Validated on Master-head `12/02/2021`

Validated - **Pass**

I was able to reproduce it on v1.2.2. On master-head, no orphan process was observed.
