### ISSUE TITLE
[Backport] Cannot migrate replicas in an evicting disk to a new disk on the same node when the node level hard affinity is applied.

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3257]
https://github.com/longhorn/longhorn/issues/3076

**Comment by meldafrawi** [comment]
Validation: Partially Failed

Longhorn version: v1.2.3-rc1

Case 1: Evicting disk

1. Disable the setting Replica Node Level Soft Anti-affinity
2. Create some volumes. Make sure there is a replica on each worker node.
3. Add a new schedulable disk to a node.
4. Disable the scheduling then Enable eviction for the old disk on the same node.
5. Verify that the replicas on the old disk move to the new disk
> Replica moved to the new disk, but volumes state changed from `attached` to `detached`.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
