### ISSUE TITLE
[TASK] Change the CSI sidecar images from upstream repo to Longhorn repo

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3258]
Longhorn v1.2.0 - v1.2.2 use the CSI sidecar images  from upstream repo https://github.com/longhorn/longhorn/blob/b6b6e4824d1949da6d5a1774c97242b97d6a2cb6/chart/values.yaml#L30-L42
We want to change them to point to the mirrored images in our Docker hub Longhorn repo https://hub.docker.com/u/longhornio

**Comment by PhanLe1010** [comment]
Test steps:
* Verify that new installation using helm/kubectl is ok
* Verify that Upgrading from older version to this version is ok for both helm and kubectl
* Verify that that installation/upgrading by helm/kubectl are ok when using a private registry. See the [doc](https://longhorn.io/docs/1.2.2/advanced-resources/deploy/airgap/#using-a-manifest-file) for instruction about how to use private registry

**Comment by shuo-wu** [comment]
Just noticed this ticket, any reason why we want to switch back to use the mirrored images in our Longhorn Docker hub?

**Comment by innobead** [comment]
> Just noticed this ticket, any reason why we want to switch back to use the mirrored images in our Longhorn Docker hub?

IIRC it's related to an air gap issue when updating the registry in values.yams

cc @PhanLe1010 @meldafrawi

**Comment by shuo-wu** [comment]
> IIRC it's related to an air gap issue when updating the registry in values.yams

But if Longhorn is installed in an air-gapped env, users should customize the registries & images rather than using these default values.

**Comment by innobead** [comment]
> > IIRC it's related to an air gap issue when updating the registry in values.yams
> 
> But if Longhorn is installed in an air-gapped env, users should customize the registries & images rather than using these default values.

Right, I think @shuo-wu is also correct, but I believe what @PhanLe1010 raised is based on the existing documentation, so if we don't want to change back to the original behavior and need to adjust https://longhorn.io/docs/1.2.2/advanced-resources/deploy/airgap/ instead. 

From my view, either way is fine and it has pros and cons, but maintaining the cloned one also requires a pipeline to do that (@meldafrawi will work with that #3056 )

@PhanLe1010 @meldafrawi WDYT?

**Comment by khushboo-rancher** [comment]
Installation, upgrade using kubectl and Helm as a part of chart validation has already been covered. Also, Longhorn installation has been validated on air gapped set up.
This is good to close.
