### ISSUE TITLE
Can not read Store Data

### ISSUE THREAD

**Issue by xyjwsj** [longhorn/longhorn#326]
![image](https://user-images.githubusercontent.com/8518853/48171318-6199ab00-e336-11e8-8c5f-7ad884df7f89.png)
![image](https://user-images.githubusercontent.com/8518853/48171332-6bbba980-e336-11e8-8840-7905a01e5a39.png)

**Comment by yasker** [comment]
The node objects should be created when the longhorn manager started. How did you install Longhorn?

Also shows the full manager logs would help.

**Comment by xyjwsj** [comment]
My k8s cluster node has been created, I installed it in the store inside Rancher. The logs in the manager are all duplicates.

E1108 01:36:36.693040 1 node_controller.go:510] Couldn't get node k8s-node-2: node.longhorn.rancher.io "k8s-node-2" not found
E1108 01:36:36.693063 1 node_controller.go:510] Couldn't get node k8s-node-1: node.longhorn.rancher.io "k8s-node-1" not found
E1108 01:36:37.652907 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)
E1108 01:36:38.654059 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)
E1108 01:36:39.655441 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)
E1108 01:36:40.656683 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)
E1108 01:36:41.657752 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)
E1108 01:36:42.658832 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)
E1108 01:36:42.750874 1 node_controller.go:510] Couldn't get node k8s-node-2: node.longhorn.rancher.io "k8s-node-2" not found
E1108 01:36:43.659924 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)
E1108 01:36:44.661092 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)
E1108 01:36:45.446756 1 node_controller.go:510] Couldn't get node k8s-node-1: node.longhorn.rancher.io "k8s-node-1" not found
E1108 01:36:45.662199 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)
E1108 01:36:46.663292 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)
E1108 01:36:47.667223 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)
E1108 01:36:48.668281 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)
E1108 01:36:49.669325 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)
E1108 01:36:50.670424 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)
E1108 01:36:51.671511 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)
E1108 01:36:52.672590 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)
E1108 01:36:52.759425 1 node_controller.go:510] Couldn't get node k8s-node-2: node.longhorn.rancher.io "k8s-node-2" not found
E1108 01:36:53.673657 1 reflector.go:205] github.com/rancher/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1alpha1.Node: the server could not find the requested resource (get nodes.longhorn.rancher.io)

**Comment by yasker** [comment]
Your CRDs are missing. Don't know how that can happen automatically. Can you try to reinstall Longhorn?

**Comment by yasker** [comment]
And please follow this instruction for uninstall.

https://github.com/rancher/longhorn/blob/master/docs/chart.md#uninstallation

**Comment by xyjwsj** [comment]
It has been reinstalled many times, both in the test environment and online environment deployment. I will try again.

**Comment by xyjwsj** [comment]
There is a problem, I first installed Longhorn in the store, then deleted, engine-image is not deleted, I re-install Longhorn, engine-image will be deleted, Longhorn-ui Dashboard display will be normal, in short, there is engine-image It will display abnormally, if not, it will display normal.
