### ISSUE TITLE
[BUG] can't reset Backup Target Credential Secret 

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#3261]
**Describe the bug**
I can see that there is an error when setting Backup Target Credential Secret to empty value

**To Reproduce**
1. Install Longhorn
2. Deploy testing backupstore and it's secret using `https://raw.githubusercontent.com/longhorn/longhorn-tests/master/manager/integration/deploy/backupstores/minio-backupstore.yaml`
3. Set Backup Target to `s3://backupbucket@us-east-1/` and to `minio-secret` and click save, see that values have changed.

4. Open Browser console, Network tab and Try to set `Backup Target Credential Secret` to empty string and click save
> Longhorn API 500 Server error
![image](https://user-images.githubusercontent.com/18232258/142090355-afc86ccd-3da8-471e-908e-83118d5587be.png)

5. Reload the setting page, see that `Backup Target Credential Secret` still have `minio-secret` value.

**Expected behavior**
we should be able to reset `Backup Target Credential Secret` to empty value.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: master
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 4
   - Memory per node: 8 GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS EC2
 - Number of Longhorn volumes in the cluster: 0

**Additional context**
N/A

**Comment by jenting** [comment]
Related PR https://github.com/longhorn/longhorn-manager/pull/970

**Comment by khushboo-rancher** [comment]
As per the integration test run, Looks like it is working after the fix.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
