### ISSUE TITLE
[BACKPORT-v1.1.x][BUG] Validate S3 input to make sure they don't contain trailing newline or space

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#3267]
#811
#3261

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with v1.1.3-rc1.

There will be an error notification from the UI, while the encoded data contains incorrect format:
![image](https://user-images.githubusercontent.com/602540/142795467-d798ea18-2ef8-4775-a3c6-4a65d8fff75a.png)
```
fail to set the setting backup-target-credential-secret with invalid value minio-secret: there is space or new line in AWS_CERT
```
