### ISSUE TITLE
[BUG] old Daemonset/engine-image-ei exist during the longhorn upgrade from 1.1.1 to 1.2.0

### ISSUE THREAD

**Issue by udhayd** [longhorn/longhorn#3268]
**Describe the bug**
Hi Team,
We have upgraded longhorn version from 1.1.1 to 1.2.0 , though longhorn version got updated daemonset/engine-image-ei for "1.1.1" doesnt get removed . We were able to view two daemonset/engine-image-ci .

We have made attempt to delete the old daemonset/engine-image-ci for 1.1.1 version , it gets re-created.

NAME                                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
**daemonset.apps/engine-image-ei-415a9e9c   25        25        25      25           25          <none>          22h
daemonset.apps/engine-image-ei-c41c4f1d   25        25        25      25           25          <none>          34d**
daemonset.apps/longhorn-csi-plugin        25        25        25      25           25          <none>          22h
daemonset.apps/longhorn-manager           25        25        25      25           25          <none>          34d

**To Reproduce**
3. Perform '....'

**Expected behavior**
To have only one daemonset/engine-image-ci for version 1.2.0

**Log**
NAME                                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
**daemonset.apps/engine-image-ei-415a9e9c   25        25        25      25           25          <none>          22h
daemonset.apps/engine-image-ei-c41c4f1d   25        25        25      25           25          <none>          34d**
daemonset.apps/longhorn-csi-plugin        25        25        25      25           25          <none>          22h
daemonset.apps/longhorn-manager           25        25        25      25           25          <none>          34d

**Environment:**
 - Longhorn version: 1.2.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k8s 1.20
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Additional context**

**Comment by derekbit** [comment]
@udhayd
The old daemonset//engine-image-ei manages the v1.1.1 engine image.
After full upgrade to v1.2.0, you can delete the v1.1.1 engine image, and the daemonset//engine-image-ei will be deleted as well.

**Comment by udhayd** [comment]
@derekbit 

Thanks for your update , this fixes the issue.

We had a understanding the old daemonset/engine-image-ci gets removed automatically after successful upgrade.

I wish if this could be added in future releases it would be more helpful. 

Thanks for understanding and your support ! 😀

**Comment by innobead** [comment]
cc @PhanLe1010

**Comment by PhanLe1010** [comment]
@udhayd 

After all volume migrate to the new engine, the old engine image CR/demonset will be cleaned up automatically after 60 mins. ref https://github.com/longhorn/longhorn-manager/blob/5021be21e51ce49b1df6ec96a723408210baa31d/controller/engine_image_controller.go#L41

Btw, please use Longhorn v1.2.2 instead of v1.2.0. The v1.2.0 has critical bugs that we fixed in v1.2.2

**Comment by udhayd** [comment]
Thanks @PhanLe1010
