### ISSUE TITLE
[BUG] defaultDataPath option not working on versions higher than 1.1.0

### ISSUE THREAD

**Issue by christiangonre** [longhorn/longhorn#3269]
**Describe the bug**
I´m trying to configure in a new longhorn installation the option` defaultDataPath` to configure a custom path, but it´s not working as expected. I´m using helm to configure it, I tried using the longhorn chart version 1.2.2 and 1.1.2 but it does not works, however, using version 1.1.0 it works without any problem. I think that maybe there is a bug in versions after 1.1.0 that excluded this feature.

**To Reproduce**
1. Install Longhorn using version 1.2.2 with helm using this option:
```
defaultSettings:
   defaultDataPath: /mnt/disks/ssd0
```
2. Check in the UI that the configuration is not the provided, instead of this you see the default path: /var/lib/longhorn
3. Uninstall longhorn and reinstall it using this time the version 1.1.0, it will work as expected

**Expected behavior**
Use the option specified in the first installation.

**Environment:**
 - Longhorn version: 1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: GKE
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: COS
   - CPU per node: 4
   - Memory per node: 4GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 1GB
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): GCE
 - Number of Longhorn volumes in the cluster: 0

**Additional context**
Please if you need more info contact me, thanks in advance for your help!

**Comment by derekbit** [comment]
@christiangonre 
Follow the steps in https://longhorn.io/docs/1.2.2/advanced-resources/deploy/customizing-default-settings/ using helm3
- `curl -Lo values.yaml https://raw.githubusercontent.com/longhorn/charts/master/charts/longhorn/values.yaml`
- update the defaultDataPath

Work as expected on my environment.
Could you try the steps to see if it works for you?

**Comment by christiangonre** [comment]
HI @derekbit! Thanks for your help and sorry for the late answer, I tested your script and it´s working without any problem.
I analized all our yaml and it was a misconfiguration of one variable, we set it as true and it must be 1.

Regards!
