### ISSUE TITLE
[BUG] Can't deploy Helm chart to Arm64 cluster ; Uncertain why

### ISSUE THREAD

**Issue by Rojikku** [longhorn/longhorn#3284]
**Describe the bug**
[Arm64 Only Cluster.](https://pastebin.com/NBu0Zvv4)
[AMD64 Node In Cluster](https://pastebin.com/NBu0Zvv4)
When deploying the helm chart all my amd64 nodes enter into CrashLoop, as above.

**To Reproduce**
1. helm repo add longhorn https://charts.longhorn.io
2. helm repo update
3. helm install longhorn longhorn/longhorn --namespace longhorn-system

**Expected behavior**
I shouldn't have any containers CrashLooping

**Log**
If applicable, add the Longhorn managers' log when the issue happens
[longhorn-support-bundle_cb4274b6-f4a7-4c2c-9952-2c4507f51e3c_2021-11-20T01-05-37Z.zip](https://github.com/longhorn/longhorn/files/7573616/longhorn-support-bundle_cb4274b6-f4a7-4c2c-9952-2c4507f51e3c_2021-11-20T01-05-37Z.zip)
.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: v1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Raspbian Lite on RPis, ubuntu Server on amd64
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal, 3xRPi4, 1xAMD64 node
 - Number of Longhorn volumes in the cluster: None yet.

**Additional context**

**Comment by derekbit** [comment]
@Rojikku 
Could you please check if the open-iscsi is installed correctly on your arm64 nodes?

**Comment by Rojikku** [comment]
```
longhorn-manager-26554                      0/1     CrashLoopBackOff   182        15h
longhorn-manager-2k87w                      0/1     CrashLoopBackOff   186        15h
longhorn-manager-6rhbp                      1/1     Running            178        15h
longhorn-manager-snhwk                      1/1     Running            0          14h
```
@derekbit Beautiful.
Raspbian Lite did not come with open-iscsi, great call.

That's my bad for not reading the prerequisites, and assuming it said "You need helm and kubernetes."
All my nodes are working now, and it was as simple as installing the package and waiting a few moments.

Thanks a ton!
