### ISSUE TITLE
[DOC] Add information about encryption algorithm to documentation

### ISSUE THREAD

**Issue by bengray2** [longhorn/longhorn#3285]
**Is your feature request related to a problem? Please describe.**
The documentation page for volume encryption contains no information about the encryption algorithms & modes used for encryption in transit or at rest.   This information is often required by IT Security managers or compliance authorities.  
 
**Describe the solution you'd like**
Add a summary about what encryption algorithms are used for both encryption in transit & encryption at rest.   

Eg, "Encryption at rest uses AES256 bit in XYZ mode and encryption in transit uses AES256 bit in ABC mode."

**Describe alternatives you've considered**
I also looked in the longhorn/longhorn repo for this information but can't find what I'm looking for.

**Additional context**
The documentation page is https://longhorn.io/docs/1.2.2/advanced-resources/volume-encryption/.

Also, it's amazing that encryption was added, very much appreciated.

**Comment by derekbit** [comment]
@bengray2 
The volume encryption leverages dm-crypt LUKS and cryptsetup. The default encryption algorithm of cryptsetup is aes-xts-plain64 ( AES as cipher and XTS as mode of operation).

Ref:
- https://github.com/longhorn/longhorn/issues/1859
- (longhorn-manager/csi/crypto/luks.go](https://github.com/longhorn/longhorn-manager/blob/42f27d4013d8624c3f3b5c9e5f020550709fe120/csi/crypto/luks.go#L27)
- [cryptsetup(8) — Linux manual page](https://man7.org/linux/man-pages/man8/cryptsetup.8.html)

**Comment by innobead** [comment]
@mantissahz This should be part of #3353 , and we need to update the doc. You can update https://longhorn.io/docs/1.4.0/advanced-resources/security/volume-encryption/.
