### ISSUE TITLE
[TASK] Remove deprecated fields after CRD API version bump

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3289]
**What's the task? Please describe.**
After adding the migration logic (from old fields to the new fields), all deprecated fields like [these](https://github.com/longhorn/longhorn-manager/blob/a7f4a67f232aa4bd0a34e10cefad189276f5732e/k8s/pkg/apis/longhorn/v1beta1/volume.go#L152-L156) can be removed after the version bump.

Need to wait for https://github.com/longhorn/longhorn-manager/pull/1136 merge before starting on this.

**Comment by innobead** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Main-Board-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/3289?planning-poker) with ZenHub @c3y1huang @shuo-wu @joshimoo @jenting @derekbit @PhanLe1010 @keithalucas

**Comment by roger-ryao** [comment]
**Verified on master-head 20230531**

- longhorn master-head ([ffaa3d2](https://github.com/longhorn/longhorn/commit/ffaa3d2113c2a47008e790df5bccf572f28025a3))
- longhorn-manager master-head ([2a83384](https://github.com/longhorn/longhorn-manager/commit/2a83384208c88904bba67202c5d55b1d36dc6ea3))

**Result Passed**

- [x] doc: [PR #713](https://github.com/longhorn/website/pull/713)

The following deprecated custom resource fields have been removed.
- [x] Volume.spec.recurringJob
- [x] Volume.spec.baseImage
- [x] Replica.spec.baseImage
- [x] Replica.spec.dataPath
- [x] InstanceManager.spec.engineImage
- [x] BackingImage.spec.imageURL
- [x] BackingImage.status.diskDownloadProgressMap
- [x] BackingImage.status.diskDownloadStateMap
- [x] BackingImageManager.status.backingImageFileMap.directory
- [x] BackingImageManager.status.backingImageFileMap.downloadProgress
- [x] BackingImageManager.status.backingImageFileMap.url
