### ISSUE TITLE
[BUG] Suggest to provide more intuitive error message for backing image with unsupported file format   

### ISSUE THREAD

**Issue by TachunLin** [longhorn/longhorn#3294]
## Describe the bug
In Harvester, when user try to create image file by uploading unsupported file type like (e.g `.dmg`) 
User will get the error message response from Longhorn API call response
`Uploaded failed the upload file size should be a multiple of 512 bytes since Longhorn use directIO by default` 

Error message on Harvester UI
![image](https://user-images.githubusercontent.com/29251855/142886602-60f63085-9b1e-4bb8-961b-fa1379b39011.png)

Error message on Longhorn UI
![image](https://user-images.githubusercontent.com/29251855/142883229-3ed33b28-14e1-4ba6-a704-32617993bc12.png)

## Test data

- [googlechrome.dmg](https://mysuse-my.sharepoint.com/:u:/g/personal/david_lin_suse_com/EZAMUL8znq1FstRMyD13HS8BQ4TVL5xvfZBgXJU-OBc_4Q?e=0sSGkC) 

## To Reproduce

1. Access Harvester dashboard
2. Download dmg file to local drive 
3. Open Images
4. Create image by upload file 
5. Select the dmg file or any unsupported file format (except  .iso, .img, .qcow2 and .raw)

## Expected behavior
If user upload or backing image with unsupported file format. 
Suggest to provide more intuitive message to notify user they are using unsupported file format. 
This may help user better distinguish and replace with the correct file.

## Environment
 - Longhorn version: v1.2.2
 - Kubernetes distro and version: v1.21.5+rke2r1
 - Node config
   - OS type and version: cOS
   - CPU per node: 48 core
   - Memory per node: 128G 
   - Disk type(e.g. SSD/NVMe): SSD
   - Underlying Infrastructure: Bare metal on provo data center (RackD8 ClusterA)

## Additional context
Harvester upload image file support design: 

Support .iso, .img, .qcow2 and .raw file types, the .dmg is the same as .img on the chrome browser view. All the images require the size should be a multiple of 512 bytes since Longhorn uses directIO by default.

**Comment by ChanYiLin** [comment]
After discussed with @innobead, will improve the user experience from other perspective instead of this error message
