### ISSUE TITLE
[IMPROVEMENT] Use PDB to protect Longhorn components from unexpected drains

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#3304]
When using `kubectl drain` on a single node cluster there might be a case where it's impossible to correctly cleanup/detach a volume. Since the csi sidecars might end up evicted before the pod/va is cleaned up correctly. 

It would be useful to have PDB on the **csi-sidecars**, to prevent all sidecars from being unavailable.
We could consider removing the PDB once we have evaluated that all longhorn volumes are no longer in use.
But even as a first step just adding a PDB with a minAvailablity of 1 for the csi sidecars would be beneficial.

A similiar thing would be useful for the **share-manager**, since it's possible that the share-manager pod gets evicted before the nfs unmount happens in the csi-plugin which might stall the kubelet/csi-plugin. in single node clusters the nfs mount would get stuck since the share-manager would no longer come up, since the node is cordoned during the drain process.

--------------------------------

A separate idea is to look into providing a script to ignore the longhorn components/namespace as part of the drain.
Since if you drain all workloads that use the longhorn volumes on that node, there wouldn't be any active volumes left on that node.
This does not apply to replica and share-manager since they could be used by a different node in a multi node cluster.

Simliar to what kubevirt does in it's maintenace guide provide a selector that drains the appropriate components.
REF: https://kubevirt.io/user-guide/operations/node_maintenance/#evict-all-vms-from-a-node
REF: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#drain

**Comment by joshimoo** [comment]
potentially issues that are caused by this mismatch
https://github.com/longhorn/longhorn/issues/2933

**Comment by joshimoo** [comment]
I tested the label selector idea and it works well, as a current workaround, example below:
```
# not equal x (includes absent key)
kubectl drain --pod-selector='!longhorn.io/component' jmoody-lh-work3 --ignore-daemonsets

# not equal x and not equal y selector
kubectl drain --pod-selector='!longhorn.io/component,app!=csi-attacher,app!=csi-provisioner' jmoody-lh-work1 --ignore-daemonsets
```

**Comment by PhanLe1010** [comment]
Note from @innobead 
> So, I think this should be good enough for now, but probably we should also update our doc for upgrade part about the drain usage.
https://longhorn.io/docs/1.2.2/volumes-and-nodes/maintenance/#updating-the-node-os-or-container-runtime

**Comment by innobead** [comment]
@PhanLe1010 has done the doc, lowering the priority and removing this from the sprint.

**Comment by joshimoo** [comment]
Just leaving this note here for future reference.
If someone wants to do a shutdown of all volumes without having to modify the scale of the end user/application deployments in the cluster. As well as a zero rebuild maintenance.

How useful this is depends on the situation :)

- they can cordon each node first
- then run the below drain command on each node this will ignore all the instance-managers + webhooks
- this will only evict the workloads since each node is cordoned, the scheduler will be unable to place the workloads on any other node and therefore all volumes will be shutdown cleanly and all engine/replica processes will be shutdown cleanly.

`kubectl drain --pod-selector='app!=csi-attacher,app!=csi-provisioner,longhorn.io/component!=instance-manager,app!=longhorn-admission-webhook,app!=longhorn-conversion-webhook' <node> --ignore-daemonsets`

**Comment by wpwoodjr** [comment]
> Just leaving this note here for future reference. If someone wants to do a shutdown of all volumes without having to modify the scale of the end user/application deployments in the cluster. As well as a zero rebuild maintenance.
> 
> How useful this is depends on the situation :)
> 
>     * they can cordon each node first
> 
>     * then run the below drain command on each node this will ignore all the instance-managers + webhooks
> 
>     * this will only evict the workloads since each node is cordoned, the scheduler will be unable to place the workloads on any other node and therefore all volumes will be shutdown cleanly and all engine/replica processes will be shutdown cleanly.
> 
> 
> `kubectl drain --pod-selector='app!=csi-attacher,app!=csi-provisioner,longhorn.io/component!=instance-manager,app!=longhorn-admission-webhook,app!=longhorn-conversion-webhook' <node> --ignore-daemonsets`

Josh, as we discussed today on the GSK call, if we cordon all nodes, then drain and uncordon each node in turn with the above command...

That will not get rid of old versions of instance managers if they have replicas on another node, correct?

So we may have to cordon, then drain ALL nodes before uncordoning again, correct?

**Comment by PhanLe1010** [comment]
Assuming that the goal is `get rid of old versions of instance managers`, I have tested the following steps:
1. Stop the automatic engine upgrade
1. Cordon all nodes
1. For each node:
    1. drain by the command `kubectl drain --pod-selector='app!=csi-attacher,app!=csi-provisioner,[longhorn.io/component!=instance-manager,app!=longhorn-admission-webhook,app!=longhorn-conversion-webhook](http://longhorn.io/component!=instance-manager,app!=longhorn-admission-webhook,app!=longhorn-conversion-webhook)' <node> --ignore-daemonsets`
    1. uncordon the node
    1. wait for the workload of this node to fully comeback
    1. cordon this node again
    1. move to next node
1. Wait until all old instance managers are removed by Longhorn
1. Uncordon all nodes
1. Enable the automatic engine upgrade

**Comment by innobead** [comment]
@PhanLe1010 just noticed the doc has not updated with the latest excluded pod selector including webhook. Please help with that update. Thanks.

**Comment by innobead** [comment]
The goal is to prevent the volume-lifecycle managed pods from being drained by the drain operation, so basically having PDBs to protect the longhorn webhooks, CSI sidecars, and CSI deployer while there are volume engines still running on the node.

After all running volumes are evicted on the draining node, can delete those PBDs to make the drain operation continue. @PhanLe1010 WDYT?

**Comment by PhanLe1010** [comment]
## Test Plan

### 1 Basic unit tests

#### 1.1 Single node cluster
* Deploy Longhorn
* Verify that there is no PDB for `csi-attacher`, `csi-provisioner`, `longhorn-admission-webhook`, and `longhorn-conversion-webhook`
* Manually create a PVC (simulate the volume which has never been attached scenario)
* Verify that there is no PDB for `csi-attacher`, `csi-provisioner`, `longhorn-admission-webhook`, and `longhorn-conversion-webhook` because there is no active workload yet
* Create a deployment that uses one RW0 Longhorn volume. 
* Create another deployment that uses one RWO Longhorn volume. Scale down this deployment so that the volume is detached
* Drain the node by `kubectl drain <node-name> --ignore-daemonsets --delete-emptydir-data --force`
* Observe that the workload pods are evited first -> PDB of `csi-attacher`, `csi-provisioner`, `longhorn-admission-webhook`, and `longhorn-conversion-webhook` are removed -> `csi-attacher`, `csi-provisioner`, `longhorn-admission-webhook`, and `longhorn-conversion-webhook`, and instance-manager-e pods are evicted 
* Observe that instance-manager-r is NOT evicted. In the current design, if the node contains the only healthy replica of the volume, the instance-manager-r cannot be evicted. This issue will be addressed at the ticket https://github.com/longhorn/longhorn/issues/5549

**Comment by innobead** [comment]
After updating the doc including node maintenance and Kubernetes upgrade (we don't have this yet, so probably can create a specific page for it, but overall it's similar to node maintenance or we would like to combine them together), let's move this to ready-for-testing.

**Comment by innobead** [comment]
@khushboo-rancher @yangchiu let's add test cases as part of Rancher integration testing. 

cc @longhorn/qa

**Comment by khushboo-rancher** [comment]
Test cases https://github.com/longhorn/longhorn-tests/pull/1295 covers this improvement testing.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 79acd76) by the [test plan](https://github.com/longhorn/longhorn/issues/3304#issuecomment-1467174481). Drain and upgrade operations in each test case work as expected.
