### ISSUE TITLE
[BUG] Revision Counter is false by default?

### ISSUE THREAD

**Issue by dbpolito** [longhorn/longhorn#3308]
I installed longhorn using helm chart 1.2.2 (i originally installed 1.0 and keep upgrading).

I didn't change it on my helm chart, so it means it's `~`, nor on ui:

![image](https://user-images.githubusercontent.com/347400/143030672-eec58b0d-1bbe-47cf-908b-465d69a8a4a2.png)

But all my volumes has it disabled:

![image](https://user-images.githubusercontent.com/347400/143030722-934b68a5-bc6c-4eae-be7e-68e519673de6.png)

In docs it says it's enabled by default.

Just out of curiosity as i never used this, how much overhead does it add? 10%?

**Comment by derekbit** [comment]
Revision Counter is enabled by default.
It is an UI bug.
https://github.com/longhorn/longhorn-ui/blob/master/src/routes/volume/detail/VolumeInfo.js#L326

**Comment by jenting** [comment]
Could you please check the revision counter setting inside the Setting CR?
```shell
kubectl get settings.longhorn.io disable-revision-counter -n longhorn-system
```

**Comment by dbpolito** [comment]
Yup, seems false:

```
❯ kubectl get settings.longhorn.io disable-revision-counter -n longhorn-system
NAME                       VALUE   AGE
disable-revision-counter   false   327d
```

Cool, so it's just a confusing UI that needs improving. Probably just upgrading the label or inverting the if.

**Comment by khushboo-rancher** [comment]
Validated on master-head, v1.2.x-head and v1.1.3-head - `12/08/2021`

Validation - **Pass**

The label is changed to `Revision Counter Disabled`
<img width="489" alt="Screen Shot 2021-12-08 at 12 38 49 PM" src="https://user-images.githubusercontent.com/60111667/145281094-a2f98413-9cba-42ec-a070-4f6b9009af36.png">
