### ISSUE TITLE
[TASK]  Add Support for RHEL/CentOs having SELinux enabled in the Jenkins job

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3310]
## What's the task? Please describe

Add Support for RHEL/CentOs having SELinux enabled in the Jenkins job. Either we can add in the existing jobs or create a new job.

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [x] Add a new job or modify the existing one to enable SELinux on RHEL/CentOS
- [x] Run the job and verify the job is working fine.

**Comment by meldafrawi** [comment]
Ref:  https://ci.longhorn.io/job/public/job/master/job/centos/job/arm64
