### ISSUE TITLE
Failed auto installation of iscsi on Debian 11 bullseye

### ISSUE THREAD

**Issue by nathanael-h** [longhorn/longhorn#3313]
Hello, 
The auto installation failed on node running Debian 11. In the pod I had a "sudo yum not found" error. 

I saw that the "ID_LIKE" field does not exists in debian 11 /etc/os_release file, there is only ID=debian.
https://github.com/longhorn/longhorn/blob/184ad405847788a19642aa88a36033cf8c956cee/deploy/prerequisite/longhorn-iscsi-installation.yaml#L8

```
root@awtprdkubworker01:~ # cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
As per this manpage: https://manpages.debian.org/testing/systemd/os-release.5.en.html ID should be used first and if not recognized, fallback to ID_LIKE.

Ping @innobead

**Comment by derekbit** [comment]
On debian11 node, the ID_LIKE is not set
```
root@ku70-master:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Will fix it by following the spec
```
Build scripts and similar should check this variable if they need to identify the local operating system and the value of ID= is not recognized. Operating systems should be listed in order of how closely the local operating system relates to the listed ones, starting with the closest. This field is optional.
```

**Comment by derekbit** [comment]
PR: https://github.com/longhorn/longhorn/pull/3330

**Comment by innobead** [comment]
Verified by @longhorn/qa already
