### ISSUE TITLE
[BUG] Volume fails to upgrade inconsistency from v1.1.3-head to master-head

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3318]
## Describe the bug

Inconsistent issue with upgrading a volume with v1.1.3-head to master-head

## To Reproduce

1. Create a volume with v1.1.3-head
2. Attach it to a node.
3. Upgrade Longhorn to master-head
4. Volume is unable to upgrade.
5. Create a volume in the upgraded set up. Volume stuck in creation 

## Log or Support bundle
```
[longhorn-manager-pdsqv] time="2021-11-24T22:57:11Z" level=warning msg="Dropping Longhorn volume longhorn-system/volume-test-2 out of the queue" controller=longhorn-volume error="fail to sync longhorn-system/volume-test-2: fail to reconcile engine/replica state for volume-test-2: cannot find the current engine for the switching after iterating and cleaning up all engines for volume volume-test-2, all engines may be detached or in a transient state" node=<node-ip>
```

[longhorn-support-bundle_e8a4f4e0-3901-4221-8e14-a30463d1cbe7_2021-11-24T22-58-21Z.zip](https://github.com/longhorn/longhorn/files/7599128/longhorn-support-bundle_e8a4f4e0-3901-4221-8e14-a30463d1cbe7_2021-11-24T22-58-21Z.zip)

## Environment

 - Longhorn version: master-head

## Additional context

This was observed on a testing cluster where I did multiple of installation, uninstallation and upgrade, so it could be the environment issue.
Logging this issue for now, ll increase the severity if encountered in future.

**Comment by khushboo-rancher** [comment]
cc: @shuo-wu @innobead

**Comment by jenting** [comment]
The same log when I check the #3321.

**Comment by shuo-wu** [comment]
I cannot reproduce it with the reproducing step mentioned above. Everything except for the engine upgrade works fine. And the volume engine upgrade failure seems to be caused by this error:
```
2021-11-24T22:54:33.871530301Z time="2021-11-24T22:54:33Z" level=warning msg="HTTP handling error cannot upgrade engine for volume volume-test-1 using image longhornio/longhorn-engine:master-head: Volume.longhorn.io \"volume-test-1\" is invalid: spec.replicaAutoBalance: Unsupported value: \"\": supported values: \"ignored\", \"disabled\", \"least-effort\", \"best-effort\""
```

I don't know why `e.Spec.Active` is false after the upgrade in your support bundle. Maybe something is messed up.

**Comment by innobead** [comment]
> I cannot reproduce it with the reproducing step mentioned above. Everything except for the engine upgrade works fine. And the volume engine upgrade failure seems to be caused by this error:
> 
> ```
> 2021-11-24T22:54:33.871530301Z time="2021-11-24T22:54:33Z" level=warning msg="HTTP handling error cannot upgrade engine for volume volume-test-1 using image longhornio/longhorn-engine:master-head: Volume.longhorn.io \"volume-test-1\" is invalid: spec.replicaAutoBalance: Unsupported value: \"\": supported values: \"ignored\", \"disabled\", \"least-effort\", \"best-effort\""
> ```
> 
@jenting is this coincidentally related to the recent CRD validation introduced? if yes, probably this should be fixed in the following upgrade path refactoring to have replicaAutoBalance default value like `ignored`.

**Comment by jenting** [comment]
> > I cannot reproduce it with the reproducing step mentioned above. Everything except for the engine upgrade works fine. And the volume engine upgrade failure seems to be caused by this error:
> > ```
> > 2021-11-24T22:54:33.871530301Z time="2021-11-24T22:54:33Z" level=warning msg="HTTP handling error cannot upgrade engine for volume volume-test-1 using image longhornio/longhorn-engine:master-head: Volume.longhorn.io \"volume-test-1\" is invalid: spec.replicaAutoBalance: Unsupported value: \"\": supported values: \"ignored\", \"disabled\", \"least-effort\", \"best-effort\""
> > ```
> 
> @jenting is this coincidentally related to the recent CRD validation introduced? if yes, probably this should be fixed in the following upgrade path refactoring to have replicaAutoBalance default value like `ignored`.

Yes.

**Comment by khushboo-rancher** [comment]
Unable to reproduce it.
