### ISSUE TITLE
[BUG] Update engine image on ubuntu ARM64 failed

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#3322]
## Describe the bug

Update engine image on Ubuntu20.04 ARM64 failed

## To Reproduce

1. Deploy Longhorn master-head
2. Use `longhornio/longhorn-test:upgrade-test.5-3.3-3.1-1` update engine image daemonset
3. New engine image stuck at crashlookbackoff

## Expected behavior

New engine image should running and replace default

## Log or Support bundle

pod will show log `standard_init_linux.go:228: exec user process caused: exec format error`

## Environment

 - Longhorn version: master-head
 - Installation method: Kubectl
 - Kubernetes distro and version: k3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04 ARM64
 - Underlying Infrastructure : AWS
 - Number of Longhorn volumes in the cluster: 0

## Additional context

Not happened on Ubuntu AMD64

**Comment by chanow816** [comment]
This also happened on v1.1.3 and v1.2.x when OS type was Ubuntu 20.04 ARM64.

**Comment by derekbit** [comment]
@chanow816 
`longhornio/longhorn-test:upgrade-test.5-3.3-3.1-1` is amd64 image.
Could you try arm64 image?

https://hub.docker.com/layers/longhornio/longhorn-test/upgrade-test.5-3.3-3.1-1/images/sha256-0bac4b529810bdf9f586f305861a71ee0419b18793920e658985d9e36cb1f1e6?context=explore

**Comment by chanow816** [comment]
This issue related to https://github.com/longhorn/longhorn/issues/1961

The upper image of `longhornio/longhorn-test:upgrade-test.5-3.3-3.1-1` was `longhornio/longhorn-engine:live-upgrade-5-3-1` ( https://github.com/longhorn/longhorn-tests/blob/master/manager/test_containers/upgrade/generate_live_upgrade_image.sh#L4), which not contain arm64 arch and was build/push manually

There is a  workaround is to use docker manifest to contain both amd64 and arm64 arch of `longhornio/longhorn-test:upgrade-test.5-3.3-3.1-1`, **but it is not good for long term develop.**

So we should have a pipeline to build `longhornio/longhorn-engine:live-upgrade-x-x-x` automatically when longhorn-engine have change, and make sure the built image contain arm64 and amd64 arch

**Comment by innobead** [comment]
Closing, and track #1961
