### ISSUE TITLE
[BUG] S3 backup error with "AWS Error: NoSuchKey The specified key does not exist."

### ISSUE THREAD

**Issue by JuHyung-Son** [longhorn/longhorn#3333]
## Describe the bug

After setting backup Target, backup errors with "AWS Error: NoSuchKey The specified key does not exist."
there 's no backup before.
And there's nothing in S3 since it's first backup

## To Reproduce

set k8s secret with `stringData`
```
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  AWS_ENDPOINTS: 
```

## Log or Support bundle

```
error listing backup volume names: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.2/longhorn [backup ls --volume-only s3://aiplatform-prometheus-dev@ap-northeast-2/], output failed to list objects with param: { Bucket: "aiplatform-prometheus-dev", Delimiter: "/", Prefix: "/" } error: AWS Error: NoSuchKey The specified key does not exist. <nil> 404 YDNMPJZDN7YMAN80 , stderr, time="2021-11-26T14:42:23Z" level=error msg="Fail to list s3: failed to list objects with param: {\n Bucket: \"aiplatform-prometheus-dev\",\n Delimiter: \"/\",\n Prefix: \"/\"\n} error: AWS Error: NoSuchKey The specified key does not exist. <nil>\n404 YDNMPJZDN7YMAN80\n" pkg=s3 time="2021-11-26T14:42:23Z" level=error msg="failed to list objects with param: {\n Bucket: \"aiplatform-prometheus-dev\",\n Delimiter: \"/\",\n Prefix: \"/\"\n} error: AWS Error: NoSuchKey The specified key does not exist. <nil>\n404 YDNMPJZDN7YMAN80\n" , error exit status 1
```

## Environment

 - Longhorn version: 1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: bare metal k8s, 1.20.9
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 5
 - Node config
   - OS type and version: ubuntu 18.04
   - CPU per node: 64
   - Memory per node: 256G
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 2

**Comment by derekbit** [comment]
@JuHyung-Son 
Could you please check if the bucket is created by yourself on AWS S3?
You can refer to the doc
https://longhorn.io/docs/1.2.2/snapshots-and-backups/backup-and-restore/set-backup-target/

**Comment by JuHyung-Son** [comment]
@derekbit Yes I already created bucket.

>Set up AWS S3 Backupstore 1. Create a new bucket in AWS S3.

Set permissions for Longhorn. There are two options for setting up the credentials. The first is that you can set up a Kubernetes secret with the credentials of an AWS IAM user. The second is that you can use a third-party application to manage temporary AWS IAM permissions for a Pod via annotations rather than operating with AWS credentials.

**Comment by jenting** [comment]
I guess you choose to provide the credential of an AWS IAM user. Make sure you provide the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`. Not sure how you create the secret, by `kubectl create secret ...` _or_ apply the yaml manifest.

To prevent the trailing newline or space or base64 encode problem, you could use the following command directly
```shell
kubectl create secret generic <aws-secret> \
    --from-literal=AWS_ACCESS_KEY_ID=<your-aws-access-key-id> \
    --from-literal=AWS_SECRET_ACCESS_KEY=<your-aws-secret-access-key> \
    -n longhorn-system
```

**Comment by JuHyung-Son** [comment]
It is solved.
maybe there is newline problem in yaml

**Comment by jenting** [comment]
> It is solved. maybe there is newline problem in yaml

Cool, we have enhanced it recently #811.
