### ISSUE TITLE
[BUG] required packages docs are incomplete

### ISSUE THREAD

**Issue by tuesdaycodes** [longhorn/longhorn#3334]
## Describe the bug

install docs at https://longhorn.io/docs/1.2.2/deploy/install/ are not complete
installing on fedora 35 server minimal with listed packages the `longhorn-driver-deployer` never passes the init step and `longhorn-ui` gets stuck in a crash/restart loop due to dns issues

ui pod needs to have dns related errors so might be k3s related, but this bug is to ensure docs are complete for longhorn for verifications before installing. environment check script from github doesnt report issue with minimal installation but it has errors

## To Reproduce

1. install fedora 35 minimal from netinst iso
2. install listed packages from https://longhorn.io/docs/1.2.2/deploy/install/ and k3s/helm
3. install longhorn with helm chart
4. `k3s kubectl get pods -n longhorn-system`
5. observe crashing/non-running pods

## Expected behavior

all pods start and run normally after installation

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: fedora 35 server minimal
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

using fedora 35 server standard install works which likely means a package needs installed when using minimal version.

**Comment by derekbit** [comment]
@tuesdaycodes 
I created a k8s cluster and longhorn according to your os/configuration successfully. 
Not sure what errors did you encountered.  You can provide the error log for further investigation.

For k3s DNS issue, you may refer to
https://longhorn.io/kb/troubleshooting-dns-resolution-failed/

**Comment by tuesdaycodes** [comment]
@derekbit where is the env file referenced for k3s in your docs? does it mean the normal config file for k3s? i dont use the same config on standard and dns worked out of the box (except longhorn not actual persisting data).

**Comment by derekbit** [comment]
@tuesdaycodes 
You can check k3s official document https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/ .

**Comment by jenting** [comment]
Probably we could enhance the environment check script to check the `longhorn-backend:9500` is available.

**Comment by jenting** [comment]
> Probably we could enhance the environment check script to check the `longhorn-backend:9500` is available.

Let's use #3355 to enhance it. Close this one.
