### ISSUE TITLE
[TASK][BACKPORT][v1.2.x] The CSI resizer may not work when the Job pod status is Completed

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3339]
https://github.com/longhorn/longhorn/issues/3303

**Comment by kaxing** [comment]
Checking with v1.2.3-rc1 image set, with the same test step in this comment: https://github.com/longhorn/longhorn/issues/3303#issuecomment-984312255

If editing the size while job/pod still undergoing, the pvc will stuck at resizing:
```
  status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-12-02T07:07:00Z"
    status: "True"
    type: Resizing
  phase: Bound
```
And the event log:
```
    Normal   Resizing               14m                 external-resizer driver.longhorn.io                                                       External resizer is resizing volume pvc-4a9
0bbc9-f029-4d6e-b98b-89bafa3d3e70
  Warning  VolumeResizeFailed     14m                 external-resizer driver.longhorn.io                                                       resize volume "pvc-4a90bbc9-f029-4d6e-b98b-
89bafa3d3e70" by resizer "driver.longhorn.io" failed: rpc error: code = FailedPrecondition desc = volume pvc-4a90bbc9-f029-4d6e-b98b-89bafa3d3e70 invalid state attached for expansion
  Warning  VolumeResizeFailed     69s (x14 over 14m)  external-resizer driver.longhorn.io                                                       Unable to expand default/test-job-pvc becau
se CSI driver driver.longhorn.io only supports offline expansion and volume is currently in-use
```
However, I can still resize/expand the volume from Longhorn UI.

cc @shuo-wu @PhanLe1010 I will need some comment on the result expectation, it seems the flag works on master branch but not in v1.2.x.

**Comment by shuo-wu** [comment]
The backported fix PR is merged **after** v1.2.3-rc1 cut. You may need to build the latest v1.2.3 image first:
https://github.com/longhorn/longhorn-manager/commits/v1.2.x

**Comment by kaxing** [comment]
@shuo-wu thanks for clarifying this, now with v1.2.x-head images the resizing can be finished once the job/pod is complete.

**Comment by kaxing** [comment]
Validation - PASSED

Tested with v1.2.x-head image set, longhorn-manager version: f994a750

Testing details please refer to this comment: https://github.com/longhorn/longhorn/issues/3303#issuecomment-984312255
