### ISSUE TITLE
[QUESTION] NFS Volume for different namespaces.

### ISSUE THREAD

**Issue by Premfer** [longhorn/longhorn#3342]
## Question

Hi, I want to set up a volume that can be used by the pods across the cluster. On searching I found the suggestion to use **the native kubernetes NFS support with a self hosted NFS server either on local storage or on top of a Longhorn RWO volume.**  I am trying to implement this. Any example or steps to do this on top of a longhorn RWO volume. I am new to this k8s cluster and trying to implement this. Any example or help is appreciated. Thanks.

## Environment

 - Longhorn version: v1.1.1
 - Kubernetes version:
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Comment by derekbit** [comment]
@Premfer 
You can refer to Longhorn docs https://longhorn.io/docs/1.2.2 . There are some examples.
BTW, using Longhorn v1.2.2 is encouraged.

**Comment by Premfer** [comment]
Hi @derekbit Thanks for the reply, Actually we want a volume to be shared across the cluster ( different namespace) , but PVC is namespace scoped. so in an another issue it was suggested to use NFS. I am looking for a specific example for this. I am not clear on how to implement this.

**Comment by Premfer** [comment]
Also, Can this be used https://longhorn.io/docs/1.0.1/advanced-resources/rwx-workloads/ , However I am confused how to use this across namespaces.  Has anyone tried ?

**Comment by derekbit** [comment]
@Premfer 
No, rwx pvc is also namespace scoped.

You can try like this, but not recommend.
- Create a RWO longhorn volume
- Add NFS operator on the top of longhorn volume
- Create multiple kubernetes NFS PV+PVC pointing to the  NFS export
