### ISSUE TITLE
[IMPROVEMENT] longhorn protocol buffer namespace conflict

### ISSUE THREAD

**Issue by guangbochen** [longhorn/longhorn#3343]
## Describe the bug

1.  we are currently using the LH as a go mod dependency `go get github.com/longhorn/longhorn-manager v1.2.3-rc1`
2. run go with https://github.com/harvester/harvester build will encounter the following protocol buffer namespace conflict errors.

## Expected behavior
- Recommend that every `.proto` file have a package name that is deliberately chosen to be universally unique (e.g., prefixed with the name of a company). e.g `github.com/longhorn/longhorn-instance-manager/pkg/rpc/rpc.pb.go`

https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

Currently can be resolve by `go build -ldflags "-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn"`
But better to be fixed on the LH side with [How do I fix a protocol buffer namespace conflict?](https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict)
```
panic: proto: message VersionResponse is already registered
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict



goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1(0x35cbbf8, 0xc0009654f0, 0x356ac60, 0xc00095fec0, 0x31abca0)
        /Users/guangbochen/src/harvester/harvester/vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go:54 +0x25f
google.golang.org/protobuf/reflect/protoregistry.(*Types).register(0xc000247bf0, 0x3219016, 0x7, 0x35cbbf8, 0xc0009654f0, 0x31abca0, 0xc00039a2c0, 0x35e1ee8, 0x30b8f60)
        /Users/guangbochen/src/harvester/harvester/vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go:566 +0x32d
google.golang.org/protobuf/reflect/protoregistry.(*Types).RegisterMessage(0xc000247bf0, 0x35a19b0, 0xc00039a2c0, 0x0, 0x0)
        /Users/guangbochen/src/harvester/harvester/vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go:493 +0xe7
github.com/golang/protobuf/proto.RegisterType(0x35a0bd0, 0x0, 0x3225dfe, 0xf)
        /Users/guangbochen/src/harvester/harvester/vendor/github.com/golang/protobuf/proto/registry.go:181 +0x71
github.com/longhorn/longhorn-instance-manager/pkg/rpc.init.0()
        /Users/guangbochen/src/harvester/harvester/vendor/github.com/longhorn/longhorn-instance-manager/pkg/rpc/rpc.pb.go:613 +0x285

Process finished with the exit code 2
```

**Comment by joshimoo** [comment]
Our grpc/protobuf codegen could use some cleanup so it's nicer to use and generated/updated as part of the build.
At the same time, we could address some of the packaging and naming stuff.

**Comment by bk201** [comment]
The workaround works for me only when building Harvester with this linkflags
```
-X github.com/harvester/harvester/vendor/google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn
```

**Comment by guangbochen** [comment]
verified using the latest `longhorn-manager` with commit `1c261ca`, we are able to build our project successfully without set `google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn`, thanks for the fix.
more details of CI build please refer to: https://github.com/harvester/harvester/pull/2163/commits/543bb74c5ff5bcf4dd5f6616c663797c7238ebb5

**Comment by kaxing** [comment]
Validation - **PASSED** with master branch(v1.3.0-dev)

Thank you @guangbochen for verifying on this for us.
