### ISSUE TITLE
[FEATURE] Allow customization of the cipher used by cryptsetup in volume encryption

### ISSUE THREAD

**Issue by neilgoodman** [longhorn/longhorn#3353]
## Is your feature request related to a problem? Please describe

I am using a Raspberry Pi 4 and would like to use the `xchacha12,aes-adiantum-plain64` cipher for encrypted volumes, as I am following [this guidance](https://source.android.com/security/encryption/adiantum) from Android for enabling encryption on ARM devices that don't have encryption acceleration.

Outside of Longhorn, I can do this today by running `cryptsetup` with the following command:

```
cryptsetup luksFormat \
  --cipher xchacha12,aes-adiantum-plain64 \
  --hash sha256 \
  --type luks2 \
  --key-size 256 \
  --sector-size 4096 \
  --use-urandom <DEVICE>
```

I did some research and I found this [issue](https://github.com/longhorn/longhorn/issues/3285). In that issue, a link to the code that runs the `cryptsetup` command was shared [here](https://github.com/longhorn/longhorn-manager/blob/42f27d4013d8624c3f3b5c9e5f020550709fe120/csi/crypto/luks.go#L27). It looks like the defaults for the `luksFormat` action are being used, which results in the `aes-xts-plain64` cipher being applied.

## Describe the solution you'd like

I would like a configuration option to at least set the cipher being used on the `luksFormat` action when creating an encrypted volume. It would be nice to also be able to configure:

- hash algorithm
- key size

## Describe alternatives you've considered

Right now I can just encrypt my devices out-of-band from Longhorn, create an ext4 filesystem on the encrypted device, and then provide a mount to that filesystem in the node settings in the Longhorn UI. I have done this and it works, but it has the following drawbacks:

- Backups aren't encrypted
- Data is not encrypted in-flight between nodes ~~(this is an assumption I'm making based on reading the docs, I haven't had time to test and make sure)~~
  - I did some testing and confirmed that with a default install of k3s + Longhorn that traffic between nodes for replicas is not encrypted in-flight, I will have to enable IPSec or WireGuard in Flannel to get encryption in-flight

**Comment by derekbit** [comment]
May can be handled with #3026

**Comment by neilgoodman** [comment]
#3026 seems concerned with storing the key for an encrypted volume as an encrypted value instead of a plain text value in a Secret resource. I'm not sure it's helpful here, but please let me know if I'm not following.

This issue is about being able to configure the cryptsetup options when an encrypted volume is created. I'm interested in this because Adiantum is a much faster AES implementation for ARM CPUs that don't have AES hardware encryption, like the Raspberry Pi.

Here is a thread on the Raspberry Pi forums that provides some benchmarks on the performance of using Adiantum ciphers: https://forums.raspberrypi.com/viewtopic.php?t=252980

**Comment by derekbit** [comment]
@neilgoodman 
#3026 is just noted because we may can handled the two issues together, not really related to your issue.

The cryptsetup options is definitely configurable. Please follow up this ticket. :)

**Comment by innobead** [comment]
cc @joshimoo

**Comment by joshimoo** [comment]
@neilgoodman this is a good addition and can be added in the future via storage class parameters.
As a workaround for now: if you manually setup the initial encryption with the format that you want, the volume should be usable automatically afterwards.

**Comment by neilgoodman** [comment]
@joshimoo thanks! I'm not following 100% though for the workaround. How do I manually setup the initial encryption? Do you mean on the physical device itself? I have done that already, but data in-flight is sent in plain text and backups aren't encrypted.

**Comment by joshimoo** [comment]
@mantissahz I created a tracking issue for RWX support of the new parameters https://github.com/longhorn/longhorn/issues/4829 and addded you, let me know if you need any assistance with the share-manager side of this :)

**Comment by shuo-wu** [comment]
Need to update the related doc: https://longhorn.io/docs/1.4.0/advanced-resources/security/volume-encryption/

BTW, there is another ticket mentioned above that tracks the doc part:
https://github.com/longhorn/longhorn/issues/3285

**Comment by chriscchien** [comment]
**Verified in longhorn manager `732f3c` with test [steps](https://github.com/longhorn/longhorn/issues/3353#issuecomment-1301525065)
Result Pass**

Workload in encrypted volume was working properly in both `aes-xts-plain64` and `aes-cbc-essiv:sha256`
```
/dev/mapper/pvc-496ad8d8-2d1f-44c7-baee-1ff301d2c227 is active and is in use.
  type:    LUKS2
  cipher:  aes-xts-plain64
  keysize: 256 bits
  key location: keyring
  device:  /dev/sda
  sector size:  512
  offset:  32768 sectors
  size:    4161536 sectors
  mode:    read/write
```
```
/dev/mapper/pvc-c814c534-2dc1-41d4-98aa-aca8cc5bc770 is active and is in use.
  type:    LUKS2
  cipher:  aes-cbc-essiv:sha256
  keysize: 256 bits
  key location: keyring
  device:  /dev/sda
  sector size:  512
  offset:  32768 sectors
  size:    4161536 sectors
  mode:    read/write
```

Volume encrypted status also reflected on UI

![Screenshot from 2022-11-16 15-35-49](https://user-images.githubusercontent.com/73337386/202116640-80371eef-1151-4139-999b-fbe008845fcd.png)

**Comment by innobead** [comment]
@chriscchien @mantissahz will this change impact existing encrypted volume? Did we verify this?

**Comment by innobead** [comment]
@mantissahz this ticket has `require/doc` and for any new feature, we need to update the doc. https://longhorn.io/docs/1.4.0/advanced-resources/security/volume-encryption/

**Comment by mantissahz** [comment]
>will this change impact existing encrypted volume? Did we verify this?

@innobead I tested this - created encrypted volumes and workloads at 1.3.x and upgrade to master-head, then drained worker nodes one by one. Workloads look fine and volumes' data is the same (write some data by `dd` and keep checksume file created by `md5sum`)
So this feature should not impact existing encrypted volume
