### ISSUE TITLE
[IMPROVEMENT] Error handling of the upgrade to v1beta2 failure

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#3354]
## Is your improvement request related to a feature? Please describe
Error handling of the upgrade to v1beta2 failure.

- Add a label (longhorn.io/api-version=v1beta2) to the CRs after upgrade
- If the upgrade failed, only update the CRs without the label

Related to #2955

**Comment by khushboo-rancher** [comment]
We'll validate this with the fix of https://github.com/longhorn/longhorn/issues/3407

**Comment by jenting** [comment]
Need to reconsider this one because probably we don't have to upgrade the CRs from longhorn.io/v1beta1 to longhorn.io/v1beta2.

**Comment by innobead** [comment]
> We should reconsider this one because probably we don't have to upgrade the CRs from longhorn.io/v1beta1 to longhorn.io/v1beta2 after introducing the [longhorn/longhorn-manager#1189](https://github.com/longhorn/longhorn-manager/pull/1189)

As per this, @derekbit I just pull this back to implementation, so you can follow up, but actually, this should be ready again after https://github.com/longhorn/longhorn-manager/pull/1189 merged. Thanks @jenting 👍

**Comment by jenting** [comment]
I think we could remove adding the labels `longhorn.io/api-version=v1beta2` after upgrading the CRs.

**Comment by jenting** [comment]
We won't upgrade the old CR from longhorn.io/v1beta1 to longhorn.io/v1beta2 in the end, but rely on the conversion webhook to perform the longhorn.io/v1beta1 <-> longhorn.io/v1beta2 conversion logic.
Therefore, the label `longhorn.io/api-version=v1beta2` won't be added to the existing CRs.

Close this issue.
