### ISSUE TITLE
[BUG] V1 Chart install V1.1.3-rc2 fail

### ISSUE THREAD

**Issue by chanow816** [longhorn/longhorn#3356]
## Describe the bug

Install Longhorn v1.1.3-rc2 from Rancher legacy V1 chart fail

## To Reproduce

1. Deploy Rancher
2. Create Cluster by Rancher
3. Enable Rancher legacy flag to Activate in Rancher UI "Global Setting" -> "Feature Flags" 
4. Switch to project Default
5. Navigate to "Legacy" -> "Catalogs", click "Add Catalog"
5. Add repo `https://github.com/innobead/charts-1.git`, branch `longhorn-1.1.3-n-1.2.3` into catalog
6. Navigate to "Legacy" -> "Project" -> "Apps", click "Launch"
7. Install Longhorn v1.1.3-rc2
8. Installation progress stuck at "Installing"
## Expected behavior

Longhorn should deploy success

## Log or Support bundle

`Failed to install app longhorn-system. Error: Chart requires kubernetesVersion: >=v1.16.0-r0 <v1.22.0-r0 which is incompatible with Kubernetes v1.21.6`

## Environment

 - Longhorn version: v1.1.3-rc2
 - Installation method: Rancher Catalog App
 - Kubernetes distro and version: RKE, version v1.21.6
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.4 AMD
 - Underlying Infrastructure : AWS

## Additional context

Use the same method I can deploy Longhorn v1.2.3-rc1 success

**Comment by innobead** [comment]
@chanow816 what's the rancher version? cc @khushboo-rancher

**Comment by innobead** [comment]
`Failed to install app longhorn-system. Error: Chart requires kubernetesVersion: >=v1.16.0-r0 <v1.22.0-r0 which is incompatible with Kubernetes v1.21.6`

The version of the downstream cluster is incompatible for 1.1.3 which right now requires <1.22. cc @kaxing

**Comment by chanow816** [comment]
> @chanow816 what's the rancher version? cc @khushboo-rancher

Rancher version was 2.6.2

**Comment by chanow816** [comment]
Update logs :

kubectl get nodes
```
NAME            STATUS   ROLES               AGE     VERSION
controlplane1   Ready    controlplane,etcd   3h10m   v1.21.6
worker1         Ready    worker              3h8m    v1.21.6
worker2         Ready    worker              3h8m    v1.21.6
worker3         Ready    worker              3h8m    v1.21.6
```

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by innobead** [comment]
@PhanLe1010 could you check this? 

cc @jenting

**Comment by PhanLe1010** [comment]
From a quick check, I can see the issue is reproducible as the step mentioned by @chanow816 . 
After looking at the comment https://github.com/helm/helm/issues/9371#issuecomment-780650794, I try added a command between the 2 condition as in https://github.com/innobead/charts-1/blob/18e79733e68079d21c9a3d0412b2e3d5b55b3b5c/charts/longhorn/v1.1.3/Chart.yaml#L5, then the chart starts working.

Next steps: 
Investigate why the command solves the issue? 
Old rancher chart use Helm v2 and newer one use Helm v3, are helm v2 and helm v3 involved in this issue?

**Comment by PhanLe1010** [comment]
Yeah, it seems that we must use the comma (e.g., `">= v1.16.0-0, < v1.22.0-0"` ) so the chart can work in both helm2 and helm3.

**Comment by PhanLe1010** [comment]
Reproduce steps:

* Clone the chart repo at the branch v1.1.3 https://github.com/longhorn/longhorn/tree/v1.1.3
* cd into the cloned repo
* Install both helm 2 and helm 3 in you dev machine https://github.com/longhorn/longhorn/tree/v1.1.3
* Run `helm2 init` and follow this instruction to set RBAC for `tiller` https://github.com/fnproject/fn-helm/issues/21#issuecomment-414210748
* Install Longhorn using helm2 `helm2 install ./chart --name longhorn --namespace longhorn-system`. See the error `Error: Chart requires kubernetesVersion: >=v1.16.0-r0 <v1.22.0-r0 which is incompatible with Kubernetes v1.21.6`

Test steps: 
* After the fix, follow the above reproducing steps you should install Longhorn successfully using helm2
* Uninstall longhorn by `helm2 del longhorn` then `helm2 del longhorn --purge` then `kubectl delete ns longhorn-system`
* Install the chart using helm3: `helm3 install longhorn ./chart -n longhorn-system --create-namespace`
* You should install Longhorn successfully using helm3

**Comment by chanow816** [comment]
Validation - **Pass**

Validated on v1.1.3
Environment: k3s, Ubuntu 20.04
Helm version : v2.17.0, v3.7.1
Result: Install Longhorn v1.1.3-rc2 with helm2 and helm3 success
