### ISSUE TITLE
[BUG][BACKPORT][v1.2.x] Volume attachment take long time, which may be caused by the replica controller queue being flooded by the backing image events

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3362]
## Describe the bug
https://github.com/longhorn/longhorn/issues/3242

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with v1.2.3-rc2 images and conditions as in test case: [Test scalability with backing image](https://github.com/shuo-wu/longhorn-tests/blob/84848a02c1f6f9d3ad97a963016ba57bc38d8411/docs/content/manual/release-specific/v1.2.3/test-scalability-with-backing-image.md)

Cluster spec: 1 control node + 3 worker
- Instance type: m5.xlarge
- Kubernetes v1.20.12
- Backup target: in-cluster NFS
