### ISSUE TITLE
[TASK] IO performance measurement

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3377]
## What's the task? Please describe

To improve Longhorn volume IO performance, we need to measure if some steps/procedures will impact the IO.

## Describe the items of the task (DoD, definition of done) you'd like

- [x] [The RWLock in the controller](https://github.com/longhorn/longhorn-engine/blob/91caed269ff076dcc450123ab137e0288df344a0/pkg/controller/control.go#L681). The answer is probably No since most of the time the read lock is just an atomic operation.
- [x] [The metric & timing record](https://github.com/longhorn/longhorn-engine/blob/91caed269ff076dcc450123ab137e0288df344a0/pkg/controller/control.go#L688-L694)
- [ ] [The function `readModifyWrite` (mutex lock)](https://github.com/longhorn/longhorn-engine/blob/9da361685327bfb05cc745578fa578a14b5dfdc0/pkg/replica/diff_disk.go#L95) in the replica and [the alignment](https://github.com/longhorn/sparse-tools/blob/a0fb4226a960dfa0a77a843b052a44824a9d729a/sparse/file.go#L122).
    - We can test this part by controlling the block size and seek offset of `fio`. e.g, `bs=5k rw=write:3k` means there will be a full and an aligned 4k write op plus one unaligned write op for each write request.

**Comment by shuo-wu** [comment]
cc @joshimoo

**Comment by shuo-wu** [comment]
```
[instance-manager-e-04a94849] [vol-e-3f6a232d] time="2021-12-10T09:34:51Z" level=info msg="------------------- Write start at 526283 us --------------------"
[instance-manager-e-04a94849] time="2021-12-10T09:34:51Z" level=info msg="get start time and lock before replica write, then start replica write, time: 526359 us"

[instance-manager-e-04a94849] [vol-e-3f6a232d] time="2021-12-10T09:34:51Z" level=info msg="replica write end at 526916 us"
[instance-manager-e-04a94849] time="2021-12-10T09:34:51Z" level=info msg="replica write end at 526974 us"
[instance-manager-e-04a94849] time="2021-12-10T09:34:51Z" level=info msg="replica write end at 527139 us"

[instance-manager-e-04a94849] time="2021-12-10T09:34:51Z" level=info msg="before metrics, time: 527208 us"
[instance-manager-e-04a94849] time="2021-12-10T09:34:51Z" level=info msg="after metrics, time: 527215 us"

[instance-manager-e-04a94849] time="2021-12-10T09:34:51Z" level=info msg="------------------- Write end at 527221 us --------------------"
```

Based on the above debug logs in the write flow, we could know that:
- The time for the read locking and starting time fetching is about 70us. The impact of this part is minor.
- The metric recording time is about 7us. The impact of this part can be ignored.
- The most time-consuming part is definitely the replica writing. Writing to 3 replicas takes around 800us. The time between the 1st replica write completion and the last replica write completion is about 200us.

Notice:
- The log printing and the current time requesting **could increase the latency** between each part.
- The consumed time from the application write start to the tgt then to the engine is not measured.

**Comment by liyimeng** [comment]
@shuo-wu longhorn use logrus as logger today, can it be replaced with zap? And should longhorn consider this https://kubernetes.io/blog/2020/09/04/kubernetes-1-19-introducing-structured-logs/

It will significantly improve troubleshooting efficiency in longhorn, I guess. E.g. make it possible for trace log relative to a particular volume cross all longhorn component efficiently.

**Comment by shuo-wu** [comment]
Probably. This could help a lot.
@innobead @joshimoo Do we have a plan to switch to the structured logs for all Longhorn components?

**Comment by shuo-wu** [comment]
Leaving one more post about the IO performance analysis here:
The 2 TCP connects (iscsid & tgtd, controller & replica) probably increase too many latencies then become one bottleneck of the IO performance. For example, when the extra latency Longhorn introduced (due to the TCP connections) is around 300us, decreasing the disk latency from 60us to 20us (by using more powerful disks) would no longer improve the Longhorn volume IO too much.

**Comment by shuo-wu** [comment]
Actually, there are some benchmarking results in https://github.com/longhorn/longhorn/issues/3176

**Comment by shuo-wu** [comment]
There are overlappings between this ticket and https://github.com/longhorn/longhorn/issues/2598
@innobead Do we still need this ticket?

**Comment by innobead** [comment]
Let's use #3446 instead.
