### ISSUE TITLE
[BUG] Potential bugs inside Longhorn CSI related to the CSI snapshot flow

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3378]
There are a few potential and need to be address as the following:

1. Specify a timeout for `csi-snapshotter` deployment to be 1:50s as other csi sidecar components
1. Probably we could change to set the [SnapshotName](https://github.com/longhorn/longhorn-manager/blob/da8ab84da751e90f858b69b6f3a77dca1f80fab2/api/model.go#L1292) to `b.Spec.SnapshotName` if `b.Spec.SnapshotName != ""`. Otherwise, set the `SnapshotName` to `b.Status.SnapshotName`. This reduces the waiting time. As long as there is a backup CR, we can safely set the `snapshotHandle` for the `VolumeSnapshotContent`
1. With the new backup design in 1.2.x, having a backup CR doesn't mean that the backup has finished. So we need to check the status of the backup. This code path needs to be updated to be compatible with the new design:
https://github.com/longhorn/longhorn-manager/blob/da8ab84da751e90f858b69b6f3a77dca1f80fab2/csi/controller_server.go#L568-L573
Since there is no evaluation on the backupStatus, instead previously we could assume if the file exists on the BS that the backup was completed. Now we have a BackupCRD that we need to evaluate just like with the waiting poller.

## Environment

 - Longhorn version: v1.2.3-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2 1.21
 - Number of management node in the cluster: single node cluster
 - Number of worker node in the cluster: single node cluster
## Additional context

This is an example of a corner case:

Tracing through the logs:
* `csi-snapshotter` see the new `VolumeSnapshotContent` with empty `snapshotHandle` field, so it makes grpc calls to `longhorn-csi-plugin` to create a CSI snapshot: `2021-12-06T10:52:43.734018298Z I1206 10:52:43.733930       1 snapshot_controller.go:267] createSnapshotWrapper: Creating snapshot for content snapcontent-c4564cee-36f7-4243-956a-2369de525e6a through the plugin ...`
* `longhorn-csi-plugin` receive the call `2021-12-06T10:52:43.737722367Z time="2021-12-06T10:52:43Z" level=info msg="CreateSnapshot: req: {\"name\":\"snapshot-c4564cee-36f7-4243-956a-2369de525e6a\",\"source_volume_id\":\"pvc-16a50b0a-cc07-4a97-b9f8-181005c11a17\"}"` and see that the Longhorn snapshot already exist but not the backup. So it try to create the backup
* In the new backup mechanism, backup is created by calling the API which just do 1 thing: deploying the backup CR and return [link](https://github.com/longhorn/longhorn-manager/blob/da8ab84da751e90f858b69b6f3a77dca1f80fab2/manager/engine.go#L154-L174)
* Then the `longhorn-csi-plugin` go into a [waiting loop](https://github.com/longhorn/longhorn-manager/blob/da8ab84da751e90f858b69b6f3a77dca1f80fab2/csi/controller_server.go#L857-L885) which just wait for the backup CR  status to be [initialized in backup controller](https://github.com/longhorn/longhorn-manager/blob/da8ab84da751e90f858b69b6f3a77dca1f80fab2/engineapi/backup_monitor.go#L130) . But it always fail to wait with the error `2021-12-06T10:53:46.077052342Z time="2021-12-06T10:53:46Z" level=warning msg="waitForBackupInitiation: timeout while waiting for backup initiation for volume pvc-16a50b0a-cc07-4a97-b9f8-181005c11a17 for snapshot snapshot-c4564cee-36f7-4243-956a-2369de525e6a"` (I am not sure why it takes more than 60s for the backup controller and the engine to init the backup. I see the log inside replica IM that the backup is initialized after more than 60s `2021-12-06T10:53:44.089840646Z [pvc-16a50b0a-cc07-4a97-b9f8-181005c11a17-r-1f756a76] time="2021-12-06T10:53:44Z" level=info msg="Done initiating backup creation, received backupID: backup-738e454d4ad54e38"`). The timeout is 60s so the total time spend in `longhorn-csi-plugin` must be more than 60s.
* Because `longhorn-csi-plugin` doesn't finish the `waitForBackupInitiation` call, `longhorn-csi-plugin` doesn't set the `snapshotID` field in the returned response. So, `csi-snapshotter` doesn't set the `snapshotHandle` for the corresponding `VolumeSnapshotContent`
* Next, Because [we didn't set the timeout](https://github.com/longhorn/longhorn-manager/blob/da8ab84da751e90f858b69b6f3a77dca1f80fab2/csi/deployment.go#L262-L267) for the `csi-snapshoter` , by default it timeouted waiting for the longhorn-csi-plugin to return [after 60s](https://github.com/kubernetes-csi/external-snapshotter/blob/070312031adf3e9ae73536a17e9e94003960024d/cmd/csi-snapshotter/main.go#L55): `2021-12-06T10:53:43.735921447Z I1206 10:53:43.734324       1 snapshot_controller.go:291] createSnapshotWrapper: CreateSnapshot for content snapcontent-c4564cee-36f7-4243-956a-2369de525e6a returned error: rpc error: code = DeadlineExceeded desc = context deadline exceeded`
* Note that at this point the `VolumeSnapshotContent` doesn't have the `snapshotHandle` set yet. So, `csi-snapshoter` retry the flow at the first step.

Ref: [longhorn-support-bundle_bcfd766e-e9c5-4574-9d09-6e6fb1ebce7c_2021-12-06T23-39-48Z.zip](https://github.com/longhorn/longhorn/files/7672799/longhorn-support-bundle_bcfd766e-e9c5-4574-9d09-6e6fb1ebce7c_2021-12-06T23-39-48Z.zip)

**Comment by PhanLe1010** [comment]
I am not sure how to increase the backup initiation time to reproduce the issue.
However, we want to retest the CSI snapshot feature. Some possible test steps are:
1. Deploy Longhorn and [enable CSI snapshot](https://longhorn.io/docs/1.2.2/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/)
2. Create volume of 5GB. Create a PV/PVC for the volume. Write 500MB to the volume. 
3. Create a CSI snapshot for the volume. [See instruction](https://longhorn.io/docs/1.2.2/snapshots-and-backups/csi-snapshot-support/create-a-backup-via-csi/)
4. Wait for the CSI snapshot to have readyToUSe == true
5. Restore the volume from the CSI snapshot by following https://longhorn.io/docs/1.2.2/snapshots-and-backups/csi-snapshot-support/restore-a-backup-via-csi/
6. Verify the data in restored volume
7. Repeat step 2 -6 but with volume size of 100GB and write 50GB to the volume

**Comment by khushboo-rancher** [comment]
Validated volume snapshot with small and 50G volume as per https://github.com/longhorn/longhorn/issues/3378#issuecomment-989428846 on master-head `12/13/2021`

Validation - **Pass**
