### ISSUE TITLE
[QUESTION] Deployments of Longhorn storage class are gone, how can I restore them?

### ISSUE THREAD

**Issue by iamatsundere** [longhorn/longhorn#3380]
## Question

Hi, I had a problem with Longhorn Storage Class. The story is a little bit long. First one, I tried to attach the volume to my pod (it's about 1.5TB), the status kept `Attaching`  for days, when I check the log, here is the thing: 
![I tried to attach the volume, but when I check the log of instance-manager, I got this](https://user-images.githubusercontent.com/8433644/145226964-a319d08d-5823-4f86-bc43-778504e90cae.png)
Then, I asked one of my friend to fix this. I don't know what did he do but some of Deployments and Pods of Longhorn are disappeared. Here are the current state.
![Current pods](https://user-images.githubusercontent.com/8433644/145242255-d505b234-9a06-4642-ad72-d2da7d8192e1.png)
In Deployments tab, nothing.
![In the Daemon Sets tab, I got this one](https://user-images.githubusercontent.com/8433644/145242546-6a4c1bbd-d98a-4b3a-867f-9c9f27ccbff9.png)
I've tried to restart the k3s.service but nothing more. May should I restart the node of is there any other solution to fix that? 
Many thanks!

## Environment

 - Longhorn version: v1.2.0
 - Kubernetes version: k3s version v1.20.4+k3s1 (838a906a) go version go1.15.8
 - Node config
   - OS type and version: Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-89-generic x86_64)
   - CPU per node: 40
   - Memory per node: 94GB
   - Disk type: HDD
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): I am using Kube Lens to access k8s node.

## Additional context

I received this from one of my ex-teammate. I don't know why but there are 4 storage classes by Longhorn.
![image](https://user-images.githubusercontent.com/8433644/145227969-becb7231-a24e-4ee9-9a5e-50a79183bc3c.png)
I think the main reason that made my volume unattachable is the node can't find the correct storage class, but I will post it as an other question.

**Comment by derekbit** [comment]
> I tried to attach the volume to my pod (it's about 1.5TB), the status kept Attaching for days, when I check the log

Is it an empty volume or there are lots of files in it?

**Comment by c3y1huang** [comment]
Have you tried to re-apply the Longhorn install to see if you can get the missing components back?

**Comment by derekbit** [comment]
There are two issues here.
> First one, I tried to attach the volume to my pod (it's about 1.5TB), the status kept Attaching for days

Need to check the instance-manager logs to see if the longhorn-engine can't be started.
Did you create and mount the large volumes, like 1.5TB, successfully before?

> I've tried to restart the k3s.service but nothing more. May should I restart the node of is there any other solution to fix that?

The csi deployments and longhorn-ui are gone.

You can detach the volumes, but might fail because the csi deployments are gone.
If the data is not important, you can re-deploy LH as @c3y1huang 's comment.
Or, you can re-deploy the missing yaml manifests by `kubectl apply -f <the longhorn-driver-deployer yaml>`  and `kubectl apply -f <the longhorn-ui yaml>`

**Comment by iamatsundere** [comment]
Wow, thanks, I didn't think about that. I've tried this [link](https://longhorn.io/docs/1.2.2/deploy/install/install-with-kubectl/) and all the Pods and Deployments are online again. I will try to handle `Attaching issues`.

**Comment by iamatsundere** [comment]
![image](https://user-images.githubusercontent.com/8433644/145925205-ae194aec-9fe0-413d-addd-0d9a392b9dba.png)
Every services are up. But instance-manager still shows these logs. I've checked the system but there is no service running on 10000 and 10001 port.

**Comment by jenting** [comment]
@iamatsundere 
Have you addressed the issue? If not, could you please check the instance-manager-e-xxx and instance-manager-r-xxx Pod's log?

**Comment by iamatsundere** [comment]
No, I'm still panic about it, still don't know why :( 

Here are some shots of logging, from `instance-manager-e` 
![image](https://user-images.githubusercontent.com/8433644/147203601-f0f906b0-eab9-44b0-9f81-a7c5bf19d67c.png)

Here's from `instance-manager-r`
![image](https://user-images.githubusercontent.com/8433644/147203708-14126625-0db2-4b33-bc7c-810a5f1df062.png)

**Comment by jenting** [comment]
There is an error log in the `instance-manager-e` about `FAIL to discover due to Timeout executing ...`
Could you please check the full log on this?

To double confirm, had you installed the `open-iscsi` and enabled the `iscsid` daemon on the host?
