### ISSUE TITLE
[BUG] loadBalancerIP doesn't have any effect in Helm chart

### ISSUE THREAD

**Issue by Tha-Fox** [longhorn/longhorn#3384]
## Describe the bug

When I deploy longhorn 1.2.2 with Helm chart, loadBalancerIP is not having any effect.

## To Reproduce

1. Download the Helm chart values: `helm show values longhorn/longhorn > values.yml`
2. Edit the file values.yml to only contain the following: 

```
service:    
  ui: 
    type: LoadBalancer
    loadBalancerIP: "192.168.100.100"
```

3. Run Helm chart: `helm upgrade --values ./values.yaml longhorn longhorn/longhorn -n longhorn-system`
4. Observe, how MetalLB gives a random free address from the address pool to Longhorn UI. The type is LoadBalancer, so that is taken into account.

## Expected behavior

A requested loadBalancerIP should be given to Longhorn UI. Other deployments in the cluster work with the similar configuration.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.20.5+k3s1
   - Number of management node in the cluster: 3 (multi-master cluster)
   - Number of worker node in the cluster: -
 - Node config
   - OS type and version: Debian 10.11
   - CPU per node: 1 quad-core 1,5 GHz 64-bit ARM Cortex-A72
   - Memory per node: 8GB
   - Disk type(e.g. SSD/NVMe): 1 x USB-SATA SSD, 2 x USB-SATA HDD
   - Network bandwidth between the nodes: 1 Gb
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal Raspberry Pi 4 cluster
 - Number of Longhorn volumes in the cluster: 1

**Comment by derekbit** [comment]
The feature is not supported in Longhorn helm installation.
You can use Rancher to deploy the Longhorn with LoadBalancer.

**Comment by jenting** [comment]
Or you could file a PR to [here](https://github.com/longhorn/longhorn/tree/master/chart) to help the longhorn chart better.

**Comment by Tha-Fox** [comment]
Thank you for your quick replies! I will have a look at how the LoadBalancerIP is handled in another charts and try to create a PR to enhance the situation.
