### ISSUE TITLE
[BUG] [BACKPORT][v1.2.3]Potential bugs inside Longhorn CSI related to the CSI snapshot flow

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3389]
https://github.com/longhorn/longhorn/issues/3378

**Comment by khushboo-rancher** [comment]
Validated volume snapshot with small and 50G volume as per https://github.com/longhorn/longhorn/issues/3378#issuecomment-989428846 on v1.2.3-rc2

Validation - **Pass**
