### ISSUE TITLE
[BUG] Show snapshot in different color when backup fails

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3394]
## Describe the bug

Once the backup fails, the snapshot keeps showing the progress and doesn't indicate that backup fails. Only if user hover on the icon it shows the error.
For better user experience, we can change the color of the snapshot and stop showing the progress percentage.
<img width="1758" alt="Screen Shot 2021-12-10 at 12 26 09 PM" src="https://user-images.githubusercontent.com/60111667/145643154-8edcc168-c66a-4bfe-83b2-db3366f5040b.png">

## To Reproduce

1. Create a volume, write some data into it.
2. Take a backup, while the backup is in progress, delete the replica which is responsible for the backup.
3. The progress of backup will stuck, and UI will not indicate the backup has failed unless user hover mouse on the snapshot icon.

## Expected behavior

Change the color of the snapshot when backup fails.

## Environment

 - Longhorn version: v1.2.x-head/ master-head - `12/10/2021`

**Comment by smallteeths** [comment]
Modify as shown below

<img width="1485" alt="截屏2021-12-14 下午3 04 03" src="https://user-images.githubusercontent.com/27733391/145949709-f985e17c-1431-455f-a9a0-28207f02375b.png">

**Comment by khushboo-rancher** [comment]
Validated with master-head - `12/15/2021`

Validation - **Pass**

<img width="989" alt="Screen Shot 2021-12-15 at 12 18 40 PM" src="https://user-images.githubusercontent.com/60111667/146259307-81188cf9-a39f-4d99-bdef-b0faec24409c.png">
