### ISSUE TITLE
[BUG] Failure to detach persistent volumes leads to high cpu usage on node(s)

### ISSUE THREAD

**Issue by Michaelpalacce** [longhorn/longhorn#3396]
## Describe the bug

This is something that has been essentially plaguing my installation of longhorn for around half a year. I never managed to figure out what was the issue but finally found a correlation.

What happens is that the CPU usage of the node gets a sudden spike of around 10-20% at a time. From running top I see that the issue is with udisksd
~~~
  20691 root      20   0  396436   4524      4 R 100.0   0.1   1092:42 udisksd     
~~~
as you can see it's at one hundred percent. Mind you this doesn't happen cause of high workload.. only thing at that time that was happening were some log aggregation and monitoring which aren't the craziest.

I also found the following logs in loki:
~~~
2021-12-11 11:18:15 | I1211 09:18:15.502750       1 csi_handler.go:228] Error processing "csi-38680884821b4c05c56ba7667996dac369b866a01aa1aa409302391997f7fe30": failed to detach: persistentvolume "pvc-4380ebc9-2d6e-4210-be5a-6595b2d33d15" not found
-- | --
  |   | 2021-12-11 11:18:15 | I1211 09:18:15.405302       1 csi_handler.go:228] Error processing "csi-406ff657f7e74ca50f53b8c482f23d9511d4dd93013aa5376fdc033a3a73f4b3": failed to detach: persistentvolume "pvc-112a89b9-6def-4f01-9cd8-fba549af14b6" not found
  |   | 2021-12-11 11:18:15 | I1211 09:18:15.400294       1 csi_handler.go:228] Error processing "csi-5332f96fe97b35db19f3e676e4cb3ce326d3ac71dceaab98bcc46690b5defe84": failed to detach: persistentvolume "pvc-fac158ec-3386-4a04-8434-5f7afb50016d" not found
  |   | 2021-12-11 11:18:15 | I1211 09:18:15.399677       1 csi_handler.go:276] Detaching "csi-38680884821b4c05c56ba7667996dac369b866a01aa1aa409302391997f7fe30"
  |   | 2021-12-11 11:18:15 | I1211 09:18:15.387026       1 csi_handler.go:276] Detaching "csi-406ff657f7e74ca50f53b8c482f23d9511d4dd93013aa5376fdc033a3a73f4b3"
  |   | 2021-12-11 11:18:15 | I1211 09:18:15.367919       1 csi_handler.go:228] Error processing "csi-813d0603053e6846bee44fb8a6eec3ca49b6eefeb6f480eefc932f40f05b52c7": failed to detach: persistentvolume "pvc-e2a39f9c-bcd0-4b51-b9f0-205b8a8c106f" not found
  |   | 2021-12-11 11:18:15 | I1211 09:18:15.345239       1 csi_handler.go:276] Detaching "csi-5332f96fe97b35db19f3e676e4cb3ce326d3ac71dceaab98bcc46690b5defe84"
  |   | 2021-12-11 11:18:15 | I1211 09:18:15.334113       1 csi_handler.go:276] Detaching "csi-813d0603053e6846bee44fb8a6eec3ca49b6eefeb6f480eefc932f40f05b52c7"
  |   | 2021-12-11 11:18:15 | I1211 09:18:15.283684       1 csi_handler.go:228] Error processing "csi-5fd89cca526646a03df9795738baccbeea713fde042c3fa568c835726636d29f": failed to detach: persistentvolume "pgadmin-data-pvc" not found
  |   | 2021-12-11 11:18:15 | I1211 09:18:15.261435       1 csi_handler.go:276] Detaching "csi-5fd89cca526646a03df9795738baccbeea713fde042c3fa568c835726636d29f"
  |   | 2021-12-11 11:18:15 | I1211 09:18:15.261066       1 csi_handler.go:228] Error processing "csi-7c97874e716f3bdf20781f831d96678ad396c55191a26a9c16f832a909a54658": failed to detach: persistentvolume "serveremulator-config-volume" not found
  |   | 2021-12-11 11:18:15 | I1211 09:18:15.237014       1 csi_handler.go:276] Detaching "csi-7c97874e716f3bdf20781f831d96678ad396c55191a26a9c16f832a909a54658"
  |   | 2021-12-11 11:18:15 | I1211 09:18:15.214101       1 csi_handler.go:228] Error processing "csi-cc6283dd5eda42823f974b73c225258f6de282fe72a633d58219f55433bc5431": failed to detach: persistentvolume "pvc-1ab2ce69-a9dc-4b7c-829a-07e3f6e6fcc0" not found
  |   | 2021-12-11 11:18:15 | I1211 09:18:15.188112       1 csi_handler.go:276] Detaching "csi-cc6283dd5eda42823f974b73c225258f6de282fe72a633d58219f55433bc5431"
  |   | 2021-12-11 11:18:13 | I1211 09:18:13.612362       1 csi_handler.go:228] Error processing "csi-b650ff8947758094d1423e2334142b59eb7a6ee9a1faa92c5e3edef26edf634e": failed to detach: persistentvolume "pvc-059771a0-0d89-4084-9769-2de528061f36" not found
  |   | 2021-12-11 11:18:13 | I1211 09:18:13.458902       1 csi_handler.go:276] Detaching "csi-b650ff8947758094d1423e2334142b59eb7a6ee9a1faa92c5e3edef26edf634e"
  |   | 2021-12-11 11:18:13 | I1211 09:18:13.320235       1 csi_handler.go:228] Error processing "csi-a125c2b76d63411a37a3c02cfe3ad428f32741b915651f82282828301d063319": failed to detach: persistentvolume "pvc-b0de8d15-935a-423b-9d20-be81561d9e4d" not found
  |   | 2021-12-11 11:18:13 | I1211 09:18:13.295698       1 csi_handler.go:276] Detaching "csi-a125c2b76d63411a37a3c02cfe3ad428f32741b915651f82282828301d063319"
  |   | 2021-12-11 11:18:02 | E1211 09:18:02.803371       1 reflector.go:127] github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotClass: failed to list *v1beta1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)
  |   | 2021-12-11 11:17:58 | E1211 09:17:58.745379       1 reflector.go:127] github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotContent: failed to list *v1beta1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
~~~
which correlate to the exact second the spike was detected.

## To Reproduce

Nothing really special.. I have a basic installation of longhorn with some cpu limitations from the settings of the UI. I have limited the replica manager CPU down since I don't really have replicas.

## Expected behavior

No sudden spikes in CPU

## Log or Support bundle

[longhorn-support-bundle_e7029229-2c3e-47d4-8649-754a502363e3_2021-12-11T14-01-43Z.zip](https://github.com/longhorn/longhorn/files/7697175/longhorn-support-bundle_e7029229-2c3e-47d4-8649-754a502363e3_2021-12-11T14-01-43Z.zip)

## Environment

 - Longhorn version: v1.2.3-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s  v1.21.4+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: ubuntu 21.04 ARM based on raspberry pis
   - CPU per node: 4
   - Memory per node: 8GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: Gigabit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 19-20 depending

**Comment by Michaelpalacce** [comment]
![image](https://user-images.githubusercontent.com/17056014/145679378-cbcfd868-2c0a-44ac-97bc-752c0e82c78e.png)

Random spike time as mentioned in the bug

**Comment by Michaelpalacce** [comment]
![image](https://user-images.githubusercontent.com/17056014/145679414-01a6dc4c-26d0-4f3d-97a9-bca1a6fbe5a7.png)

These are all examples of this happening over the span of a day or two. Where you see the sudden drop, that is a restart of the cluster. Currently it's my only way to solve this.

**Comment by Michaelpalacce** [comment]
[longhorn-support-bundle_e7029229-2c3e-47d4-8649-754a502363e3_2021-12-11T14-01-43Z.zip](https://github.com/longhorn/longhorn/files/7697173/longhorn-support-bundle_e7029229-2c3e-47d4-8649-754a502363e3_2021-12-11T14-01-43Z.zip)

Support bundle

**Comment by Michaelpalacce** [comment]
Thank you for the reply.

* about the rc releases I wasn't aware, thank you for the clarification
* regarding the udisksd I don't really have anything else running on these machines... For it to be taking so much cpu I only assumed.
* great info about the replica. Figure that's why I have a bit of issues while first starting my cluster. Thanks!
* there shouldn't be anything wrong it's performing normally and there is no pressure from what I see. I do have workloads there yes but they amount to only half of the cpu usage and I've prevented Longhorn from scheduling on that node as to not take any resources.

**Comment by PhanLe1010** [comment]
Okay, thank you for the update!

We need to double-check the `udisksd` to see if it is related to Longhorn cc @keithalucas 

I am not sure if the spike of 10-20% is really abnormal? Are you using Prometheus to monitor the CPU usage which gets data from the Kube metric server? If so it could fluctuate in my experience. 

The `persistentvolume "xyz" not found Is` is definitely a problem. Here the CSI attached cannot query the PV objects which should always exist. Which node is the ETCD in the above monitoring graph? Do you have prometheus setup to monitor ETCD?

**Comment by keithalucas** [comment]
> Okay, thank you for the update!
> 
> We need to double-check the `udisksd` to see if it is related to Longhorn cc @keithalucas

 `udisksd` is not related it Longhorn.  It's a D-Bus service for disks.  https://freedesktop.org/wiki/Software/udisks/  It might be that when longhorn creates a block device, udisks detects that.   

> I am not sure if the spike of 10-20% is really abnormal? Are you using Prometheus to monitor the CPU usage which gets data from the Kube metric server? If so it could fluctuate in my experience.
> 
> The `persistentvolume "xyz" not found Is` is definitely a problem. Here the CSI attached cannot query the PV objects which should always exist. Which node is the ETCD in the above monitoring graph? Do you have prometheus setup to monitor ETCD?

**Comment by Michaelpalacce** [comment]
> Okay, thank you for the update!
> 
> We need to double-check the `udisksd` to see if it is related to Longhorn cc @keithalucas 
> 
> I am not sure if the spike of 10-20% is really abnormal? Are you using Prometheus to monitor the CPU usage which gets data from the Kube metric server? If so it could fluctuate in my experience. 
> 
> The `persistentvolume "xyz" not found Is` is definitely a problem. Here the CSI attached cannot query the PV objects which should always exist. Which node is the ETCD in the above monitoring graph? Do you have prometheus setup to monitor ETCD?
> 
> 

I understand. I do have prometheus monitoring and the etcd is on the green colored graph line.
Also prometheus isn't really monitoring etcd itself, best I can tell

**Comment by Michaelpalacce** [comment]
>  `udisksd` is not related it Longhorn.  It's a D-Bus service for disks.  https://freedesktop.org/wiki/Software/udisks/  It might be that when longhorn creates a block device, udisks detects that.   
> 

Is there a way / should I prevent udisks from detecting that. Even if it's a not part of Longhorn udisks should ship with all ubuntu isos... It'd be prudent to prevent this kind of cpu spike

**Comment by Michaelpalacce** [comment]
So I have stopped literally all my workloads on the cluster after the peak from before. Running kubectl top po -n longhorn-system shows me that the longhorn engine-image-ei is taking almost 1 whole cpu out of the 4 i have ( the only one that is not taking any cpu is the one that is scheduled on the master )

![image](https://user-images.githubusercontent.com/17056014/146760745-647c0fd6-19ad-4f9d-851e-10edc5a10093.png)


along with longhorn manager taking another 300m. the ONLY workloads here are grafana and prometheus and they are not even using longhorn to store data ( moved them to an NFS )

You can see the drop of resources used:

![image](https://user-images.githubusercontent.com/17056014/146760946-f1d44cd4-4225-470e-a9d9-37d092e8468c.png)

**Comment by Michaelpalacce** [comment]
This is what I have from metrics-server
![image](https://user-images.githubusercontent.com/17056014/146761227-8a8bcdb5-85b8-43f6-a7cf-1d033959a499.png)

**Comment by Michaelpalacce** [comment]
This is a ps from one of the nodes sorted by only highest cpu usage:

![image](https://user-images.githubusercontent.com/17056014/146761940-721c3abe-7825-46d0-b8a4-405d32c148cd.png)

**Comment by Michaelpalacce** [comment]
Seems like udisksd does detect something?

**Comment by Michaelpalacce** [comment]
![Screenshot_20211220-141830.jpg](https://user-images.githubusercontent.com/17056014/146766206-dd94023f-baaf-4d65-b625-c7857c416e1a.jpg)

![Screenshot_20211220-141824.jpg](https://user-images.githubusercontent.com/17056014/146766214-e488d799-e5db-438f-b0cf-0be9d2504936.jpg)

**Comment by Michaelpalacce** [comment]
I have also noticed that thud happens way faster with the new Longhorn engine image

**Comment by Michaelpalacce** [comment]
Currently testing out a script that is clearing any orphaned pods and am consistently clearing the pods from k3s in case there are any that are not running so to eliminate that as an issue. I drained one node while this issue was happening and i noticed that the CPU usage went down instantly. The udisks2 process as well as that longhorn one that is in an infinite sleep taking 80% or something like that of the CPU instantly went down. Going to verify this by stopping that process directly next time this issue happens. If this fixes it then the issue is there ( Check this out: https://user-images.githubusercontent.com/17056014/146761940-721c3abe-7825-46d0-b8a4-405d32c148cd.png ). If not I will kill the k3s service directly and see what that does.

Would also like to note that there is no IO wait when running iostat.

**Comment by Michaelpalacce** [comment]
Would like to say that nothing I tried helped me to narrow down the issue. I'm closing this as I reinstalled the os completely and recreated the cluster since then... This has been bothering me for 3 months now and I couldn't really debug this more.

**Comment by Michaelpalacce** [comment]
Even after reinstall bug is still there...

**Comment by PhanLe1010** [comment]
The `engine-image-ei-xxx` pods is just checking `ls /data/longhorn && /data/longhorn version --client-only` every 5s. In my cluster, they only take 5m. It is weird that they take a whole core in your cluster. Can you manually run the command and check the CPU usage? 

For the udisksd using too much CPU, I am wondering if the problem also happens with any storage solution. On a clean node with similar os outside of the cluster, can you try out manually creating a bunch of loop devices, mount to different directories. Then check the udisksd process

**Comment by Michaelpalacce** [comment]
So running the command many many times fast yielded nothing. I suspect that the issue is indeed with udisksd... I will try attaching many directories as suggested

**Comment by Michaelpalacce** [comment]
So I think I can safely say that I found the issue. The issue is not related to longhorn and I am not 100% certain where to post the bug but what I have found.

@PhanLe1010 gave me an idea with manually mounting to different directories. So essentially that is what happens. The livenessProbes and readinessprobes do exactly that. Everytime a  probe is ran then there is a mount to the pod ( according to my limited understanding of the core of k3s and systemd journal logs ). After a while there are so many of these mounts that I suppose leads to the high CPU usage.

I honestly am not 100% certain that this is the issue but removing most of my probes and making the ones left more sparse has led to my environment being stable for ~ 3 days now (usually the first day was an issue)

**Comment by olljanat** [comment]
> I suspect that the issue is indeed with udisksd...

@Michaelpalacce Thanks for tip. I noticed that udisks2 is by default installed in Ubuntu 20.04 but not anymore in Ubuntu 22.04.

Removing it from Ubuntu 20.04 looks also making quite big difference on CPU usage and afaiu Longhorn still works normally:
![image](https://user-images.githubusercontent.com/6213926/215447578-72394bb1-0a4f-4aac-a5e1-666853605de4.png)

**Comment by Michaelpalacce** [comment]
@olljanat that's a great find... This issue was the bane of my existence and I honestly thought the issue was related to arm partially...

I saw a big issue with probes and maybe it was indeed an issue with udisksd...

Coincidentally around the time I decided to migrate my servers to AMD architecture and I saw this issue is completely gone, however I also did update to latest version of Ubuntu ( at the time 22.04 ) so I'm my mind the issue was arm related to probes. I didn't take the fact that the update from 20 to 22 could have been the actual resolution.
