### ISSUE TITLE
[BUG] set `defaultClassReplicaCount` in Helm values seems to have no effect on UI

### ISSUE THREAD

**Issue by PhilipMay** [longhorn/longhorn#3398]
## Describe the bug

When I install longhorn with helm and add a value file to set the number of replicas (see below) it seems to have no effect on the GUI.

```text
persistence:
  defaultClassReplicaCount: 2
```

## To Reproduce

1. install longhorn with the value file above to change `defaultClassReplicaCount` from 3 (default) to 2
2. open the longhorn UI
3. go to settings
4. check value for replica count

The value should show 2 (which has been set) and not 3. But it shows 3.

## Expected behavior

UI should show the value of 2 for replica counts because we did set it at install time with helm.

## Environment

 - Longhorn version: 1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubeadm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: using debian 11 on "bare metal"
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version: debian 11

**Comment by jenting** [comment]
Duplicate to https://github.com/longhorn/longhorn/issues/2570

**Comment by PhanLe1010** [comment]
Those are 2 different settings:
* `Default Replica Count` setting in Longhorn UI is for volume created in Longhorn UI
* The `persistence.defaultClassReplicaCount` is for the default `longhorn` StorageClass. You can verify by `kubectl get sc longhorn -o yaml`

**Comment by jenting** [comment]
> Duplicate to #2570

Use #2570 to fix this issue, close it.

**Comment by PhilipMay** [comment]
> Those are 2 different settings:
> 
>     * `Default Replica Count` setting in Longhorn UI is for volume created in Longhorn UI
> 
>     * The `persistence.defaultClassReplicaCount` is for the default `longhorn` StorageClass. You can verify by `kubectl get sc longhorn -o yaml`

I do not understand this answer. You say it is not a bug but the issue is still labeled as a bug and @jenting sais:

> Use #2570 to fix this issue, close it.
