### ISSUE TITLE
[QUESTION] Inspecting Longhorn Image content

### ISSUE THREAD

**Issue by bakaibalazs** [longhorn/longhorn#3400]
Dear Longhorn Support!

I am curious about what is the preferred way to inspect (see the file content) of longhorn images?
I mean, I would like to copy files from the image to my host machine for example configs etc,....

Thanks.

**Comment by c3y1huang** [comment]
Just curious what are you looking for in Longhorn images?
You can find deployment settings in [here](https://github.com/longhorn/longhorn/tree/master/deploy) and examples [here](https://github.com/longhorn/longhorn/tree/master/examples). Or maybe with `kubectl cp <src> <dest>` can also achieve your goal.

**Comment by bakaibalazs** [comment]
Hi! I would like to see my files for example my uploaded excels, documents, pdfs video files so what my application saves in the longhorn persistent image (volume)

**Comment by jenting** [comment]
I see, so what you want is the one https://longhorn.io/docs/1.2.3/advanced-resources/data-recovery/export-from-replica/
