### ISSUE TITLE
[BUG] Error inspecting backup config

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3402]
## Describe the bug

There are lots of logs in the longhorn-manager like below
```
[longhorn-manager-h9zt6] time="2021-12-13T21:06:02Z" level=error msg="Error inspecting backup config" backup=backup-548f172e21624cf7 controller=longhorn-backup error="error getting backup config s3://longhorn-bucket@us-west2/?backup=backup-548f172e21624cf7&volume=restore-1: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.3-rc2/longhorn [backup inspect s3://longhorn-bucket@us-west2/?backup=backup-548f172e21624cf7&volume=restore-1], output backup backup-548f172e21624cf7 is still in progress\n, stderr, time=\"2021-12-13T21:06:02Z\" level=error msg=\"backup backup-548f172e21624cf7 is still in progress\"\n, error exit status 1" node=<node-ip>
```

## To Reproduce

Not sure, I was doing some volume migration HA test cases https://longhorn.github.io/longhorn-tests/manual/pre-release/ha/ha-volume-migration/ when I observed the issues. I did powered down a node where a restored volume was attached. At the time when I observed the issue,  no backup was in progress.

## Log or Support bundle
[longhorn-support-bundle_18518d69-4b44-41a3-a87f-dc4e6c7d0a2a_2021-12-13T21-05-43Z.zip](https://github.com/longhorn/longhorn/files/7707281/longhorn-support-bundle_18518d69-4b44-41a3-a87f-dc4e6c7d0a2a_2021-12-13T21-05-43Z.zip)

## Environment

 - Longhorn version: v1.2.3-rc2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.22.4 K8s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04

**Comment by khushboo-rancher** [comment]
cc: @jenting @innobead

**Comment by jenting** [comment]
Do you have 2 cluster points to the same backup store?
If yes, I think the problem is cluster A is perform snapshot backup and cluster B is syncing the backup from the remote backup store.

**Comment by khushboo-rancher** [comment]
Yes, I had 2 clusters pointing to same backup store.
Are these logs expected in this case?

**Comment by jenting** [comment]
> Yes, I had 2 clusters pointing to same backup store. Are these logs expected in this case?

Yes, I'll file a PR to fix it today.

**Comment by khushboo-rancher** [comment]
Validated on Master-head `12/15/2021`

Validation - **Pass**

No reported logs are observed.
