### ISSUE TITLE
[BUG] Live upgrade stuck if the same volume name backup exists in the backup store

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3403]
## Describe the bug

Live upgrade fails for a volume when the backup store has the same name backup with one failed replica.
<img width="1765" alt="Screen Shot 2021-12-13 at 4 44 35 PM" src="https://user-images.githubusercontent.com/60111667/145912203-4a0f8529-9ef4-40d4-92b9-9406af751853.png">

## To Reproduce

1. Set up v1.2.2. and create few volumes (name one of the volume as volume-1)
2. Configure a backup store where there is already a backup volume `volume-1`
3. set `Concurrent Automatic Engine Upgrade Per Node Limit` to 1
3. Upgrade the set up to v1.2.3-rc2
4. Observe the volume-1 stuck in upgrading.

## Expected behavior

Volume should be upgraded successfully.

## Log or Support bundle

[longhorn-support-bundle_141f3beb-85be-4e57-8cd0-42b59e40bb9a_2021-12-14T02-11-03Z.zip](https://github.com/longhorn/longhorn/files/7708153/longhorn-support-bundle_141f3beb-85be-4e57-8cd0-42b59e40bb9a_2021-12-14T02-11-03Z.zip)

## Environment

 - Longhorn version: v1.2.3-rc2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.21.7
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3

**Comment by jenting** [comment]
> set Concurrent Automatic Engine Upgrade Per Node Limit to 1

The `concurrent-automatic-engine-upgrade-per-node-limit` in the Setting CR is 0, not 1.

Also, I did not see the `volume-1` in the support bundle. I think this support bundle is incorrect?

**Comment by khushboo-rancher** [comment]
Oops.. must have attached wrong bundle.
Attaching the correct one.
[longhorn-support-bundle_141f3beb-85be-4e57-8cd0-42b59e40bb9a_2021-12-14T02-11-03Z.zip](https://github.com/longhorn/longhorn/files/7708149/longhorn-support-bundle_141f3beb-85be-4e57-8cd0-42b59e40bb9a_2021-12-14T02-11-03Z.zip)

**Comment by jenting** [comment]
May I say that before upgrade, there was an failed replica on there?

**Comment by jenting** [comment]
The failed replica `volume-test-1-r-1485d003` responsible engine image should be `volume-test-1-e-fb71653e`.
However the engine image `volume-test-1-e-fb71653e` no longer in the cluster.

After manually delete the failed replica `volume-test-1-r-1485d003`, the volume `volume-test-1` is back to Healthy state.

**Comment by jenting** [comment]
Found a weird log in the longhorn-manager log
```shell
2021-12-14T00:28:51.734084200Z time="2021-12-14T00:28:51Z" level=info msg=" volume-test-1-r-1485d003 from volume-test-1-r-4fa10fb8" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=3.145.89.77 owner=3.145.89.77 state=attached volume=volume-test-1
2021-12-14T00:28:51.742871733Z time="2021-12-14T00:28:51Z" level=info msg="Cloned a new matching replica volume-test-1-r-2a01a02c from volume-test-1-r-defadc08" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=3.145.89.77 owner=3.145.89.77 state=attached volume=volume-test-1
2021-12-14T00:28:51.849792292Z time="2021-12-14T00:28:51Z" level=info msg="Cloned a new matching replica volume-test-1-r-7a55dfc6 from volume-test-1-r-80ceac1f" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=3.145.89.77 owner=3.145.89.77 state=attached volume=volume-test-1
```

Not sure where the 1 line log comes from.

**Comment by khushboo-rancher** [comment]
> The failed replica volume-test-1-r-1485d003 responsible engine image should be volume-test-1-e-fb71653e.
However the engine image volume-test-1-e-fb71653e no longer in the cluster.

Does it mean while upgrading somehow the engine image got deleted?

**Comment by innobead** [comment]
> Related issues #2992
> 
> The failed replica `volume-test-1-r-1485d003` responsible engine image should be `volume-test-1-e-fb71653e`. However the engine image `volume-test-1-e-fb71653e` no longer in the cluster.
> 
> After manually delete the failed replica `volume-test-1-r-1485d003`, the volume `volume-test-1` is back to Healthy state.

Which we have a workaround for this by identifying the orphan replica, then deleting it to make a new one to recreate.

**Comment by innobead** [comment]
From the code, it's related to https://github.com/longhorn/longhorn-manager/pull/873 and fixed PR https://github.com/longhorn/longhorn-manager/pull/873

It seems the number of the replica instance manager is more than one at that moment. Maybe it's not related to backup. cc @PhanLe1010 @derekbit

**Comment by shuo-wu** [comment]
> Found a weird log in the longhorn-manager log
> 
> ```shell
> time="2021-12-14T00:28:51Z" level=info msg=" volume-test-1-r-1485d003 from volume-test-1-r-4fa10fb8" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=3.145.89.77 owner=3.145.89.77 state=attached volume=volume-test-1
> time="2021-12-14T00:28:51Z" level=info msg="Cloned a new matching replica volume-test-1-r-2a01a02c from volume-test-1-r-defadc08" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=3.145.89.77 owner=3.145.89.77 state=attached volume=volume-test-1
> time="2021-12-14T00:28:51Z" level=info msg="Cloned a new matching replica volume-test-1-r-7a55dfc6 from volume-test-1-r-80ceac1f" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=3.145.89.77 owner=3.145.89.77 state=attached volume=volume-test-1
> ```
> 
> Not sure where the 1st line log comes from, why some words missing 🤔
> 
> However, the original Pod's log is correct
> 
> ```shell
> time="2021-12-14T00:28:51Z" level=info msg="Cloned a new matching replica volume-test-1-r-1485d003 from volume-test-1-r-4fa10fb8" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=3.145.89.77 owner=3.145.89.77 state=attached volume=volume-test-1
> time="2021-12-14T00:28:51Z" level=info msg="Cloned a new matching replica volume-test-1-r-2a01a02c from volume-test-1-r-defadc08" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=3.145.89.77 owner=3.145.89.77 state=attached volume=volume-test-1
> time="2021-12-14T00:28:51Z" level=info msg="Cloned a new matching replica volume-test-1-r-7a55dfc6 from volume-test-1-r-80ceac1f" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=3.145.89.77 owner=3.145.89.77 state=attached volume=volume-test-1
> ```

These logs mean the volume controller is launching new replicas for live upgrade or migration. They are newly introduced debug logs.

**Comment by innobead** [comment]
> > The failed replica volume-test-1-r-1485d003 responsible engine image should be volume-test-1-e-fb71653e.
> > However the engine image volume-test-1-e-fb71653e no longer in the cluster.
> 
> Does it mean while upgrading somehow the engine image got deleted?

https://github.com/longhorn/longhorn/issues/4332 should help with this to ensure the image is still referenced if any engine/replica/volume still use it via spec/status. cc @derekbit

**Comment by innobead** [comment]
@chrisc1981 Please help check if this still exists in 1.3.x? You could try to upgrade from 1.2.2 to 1.3.1, because #4332 has been introduced in 1.3.1. 

cc @longhorn/qa

**Comment by ChanYiLin** [comment]
I found the mention link didn't work before
cc @chriscchien could you help to check if this still exists from 1.2.2 to 1.3.1
and maybe 1.4.2 to 1.5.0-rc3
Thanks!

**Comment by chriscchien** [comment]
This issue verified pass with below test steps

Precondition:
- Deploy Longhorn v1.2.2
- Create volume vol1 with workload, create backup to backup store
- Set `Concurrent Automatic Engine Upgrade Per Node` Limit to 1

Test steps
1. Upgrade Longhorn from v1.2.2 to v1.3.3 success.
2. Continue from previous step, upgrade Longhorn from v1.3.3 to v1.4.3-rc1 success.
3. Continue from previous step, upgrade Longhorn from v1.4.3-rc1 to v1.5.0-rc3 success.
