### ISSUE TITLE
[BUG] RHEL job on v1.2.x branch on Jenkins is not working 

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3404]
## Describe the bug

https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/ is failing

RHEL:
version - 8.4.0
arch - amd64

**Comment by meldafrawi** [comment]
we've updated our integration test framework, I've triggered a new job to check if the issue still exists.
https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/39/

**Comment by meldafrawi** [comment]
Testing on RHEL v 8.4.0

https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/41/
