### ISSUE TITLE
[BUG] e2e daily build not working properly on RockyLinux

### ISSUE THREAD

**Issue by chanow816** [longhorn/longhorn#3406]
## Describe the bug

End to end automation not suppport rockylinux when using `longhornio/longhorn-manager-test:v1.1.3-head`

## To Reproduce

1. Trigger e2e private build with `longhornio/longhorn-manager-test:v1.1.3-head`, distro rockylinux, version 8.4
2. Observe console output

## Expected behavior

Test going properly

## Log or Support bundle

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/611/console

**Comment by meldafrawi** [comment]
we've updated our integration test, triggered a new job to check if the issue still exists
https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/amd64/job/longhorn-tests-rockylinux-amd64/3/

**Comment by meldafrawi** [comment]
Tested on latest master: RockyLinux v8.4
https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/amd64/job/longhorn-tests-rockylinux-amd64/4/
