### ISSUE TITLE
[BUG] Uninstallation failed on master

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3410]
## Describe the bug

On an upgraded set up from v1.2.3-rc2 to master-head, the uninstallation failed with below error in the uninstallation job
```
E1214 20:26:15.546349 1 reflector.go:178] github.com/longhorn/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1beta1.Volume: v1beta1.VolumeList.Items: []v1beta1.Volume: v1beta1.Volume.Status: types.VolumeStatus.Conditions: ReadMapCB: expect { or n, but found [, error found in #10 byte of ...|ditions":[{},{},{}],|..., bigger context ...|t":"","sourceVolume":"","state":""},"conditions":[{},{},{}],"currentImage":"longhornio/longhorn-engi|...
```

## To Reproduce

1. Set up Longhorn prior version (e.g. v1.2.3-rc2)
2. Create some volume, backup using csi snapshotter
3. Upgrade to the master-head
4. Perform some operation like backup restore etc
5. Deploy uninstallation job https://raw.githubusercontent.com/longhorn/longhorn/master/uninstall/uninstall.yaml. Edit the image to master-head or v1.2.x-head as required before deploying the yaml.

## Expected behavior

The uninstallation job should uninstall the Longhorn. No error logs should be present.

## Log or Support bundle

Cluster support bundle - 
[longhorn-support-bundle_18518d69-4b44-41a3-a87f-dc4e6c7d0a2a_2021-12-14T20-29-44Z.zip](https://github.com/longhorn/longhorn/files/7714577/longhorn-support-bundle_18518d69-4b44-41a3-a87f-dc4e6c7d0a2a_2021-12-14T20-29-44Z.zip)
Log of longhorn-uninstall - 
[longhorn-uninstall--1-ndw9k_longhorn-uninstall.log](https://github.com/longhorn/longhorn/files/7714581/longhorn-uninstall--1-ndw9k_longhorn-uninstall.log)

## Environment

 - Longhorn version: master-head `12/14/2021`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.21.7 K8s

**Comment by joshimoo** [comment]
@derekbit is this related to the crd version updates?

**Comment by khushboo-rancher** [comment]
Observed this issue on v1.2.x also. Added the backport and priority.

**Comment by khushboo-rancher** [comment]
Looks like it was a problem with my cluster, I had wrong yamls deployed.

@derekbit If you have tried reproducing and couldn't, we can close it.

**Comment by derekbit** [comment]
@joshimoo 
yes, it's related to the v1beta2 and only happens on master-head branch. The failure does not happen on v1.2.x.

The kubernetes GC controller thinks the v1beta2 objects are v1beta1, so it leads to the deletion of engineImages fails.

**Comment by derekbit** [comment]
duplicate: https://github.com/longhorn/longhorn/issues/3407

**Comment by khushboo-rancher** [comment]
Validated on master-head `01/13/2022`

Validation - **Pass**
