### ISSUE TITLE
[QUESTION] failed to start up frontend: Backing-store longhorn is not supported

### ISSUE THREAD

**Issue by meilihao** [longhorn/longhorn#3413]
## Question
log
```bash
# longhorn controller --frontend tgt-blockdev --replica tcp://127.0.0.1:9502 vol-name
INFO[0000] Starting with replicas ["tcp://127.0.0.1:9502"] 
INFO[0000] Connecting to remote: 127.0.0.1:9502         
INFO[0000] Opening: 127.0.0.1:9502                      
INFO[0000] Adding backend: tcp://127.0.0.1:9502         
INFO[0000] Start monitoring tcp://127.0.0.1:9502        
INFO[0000] Get backend tcp://127.0.0.1:9502 revision counter 0 
INFO[0000] device vol-name: SCSI device /dev/longhorn/vol-name shutdown 
go-iscsi-helper: tgtd is already running
INFO[0001] go-iscsi-helper: found available target id 1 
ERRO[0001] Failed to startup frontend: Backing-store longhorn is not supported 
2021/12/13 18:08:04 failed to start up frontend: Backing-store longhorn is not supported
# tgtadm --lld iscsi --op show --mode system
System:
    State: ready
    debug: off
LLDs:
    iscsi: ready
    iser: error
Backing stores:
    sheepdog
    bsg
    sg
    null
    ssc
    smc (bsoflags sync:direct)
    mmc (bsoflags sync:direct)
    rdwr (bsoflags sync:direct)
    aio
Device types:
    disk
    cd/dvd
    osd
    controller
    changer
    tape
    passthrough
iSNS:
    iSNS=Off
    iSNSServerIP=
    iSNSServerPort=3205
    iSNSAccessControl=Off
```

## Environment

 - Longhorn version: 91caed269ff076dcc450123ab137e0288df344a0
 - Kubernetes version: no
 - Node config
   - OS type and version: deepin 20.3
   - CPU per node: 4
   - Memory per node:  8G
   - Disk type: ssd
   - Network bandwidth and latency between the nodes: no(one node)
 - Underlying Infrastructure: Baremetal

**Comment by meilihao** [comment]
see https://github.com/longhorn/longhorn/issues/3237 and [longhorn-engine/Dockerfile.dapper](https://github.com/longhorn/longhorn-engine/blob/master/Dockerfile.dapper) , need to use [rancher/tgt](https://github.com/rancher/tgt)

**Comment by joshimoo** [comment]
@meilihao if you are trying to build the engine outside of docker via `go build` make sure to check out the docker file (tgt, liblonghorn, etc)
If you just want a running engine-binary you can do `make build` and `make package` there is also a set of e2e tests, which are run when just invoking `make`
