### ISSUE TITLE
[QUESTION] nfs backup permission denied error during folder creation

### ISSUE THREAD

**Issue by rpelissi** [longhorn/longhorn#3416]
## Describe the bug

On rancher 2.5.9 with longhorn 1.2.2 installed from helm, I can't do backup to an NFS server with the error mesage:
`error running create backup command: failed to create backup to nfs://192.168.2.50:/mnt/vol1/backup/longhorn for volume pvc-6a4537c3-67fb-459e-8438-6633e074c42f: rpc error: code = Unknown desc = mkdir /var/lib/longhorn-backupstore-mounts/192_168_2_50/mnt/vol1/backup/longhorn/backupstore: permission denied" , error exit status 1`

## To Reproduce

1. Install rancher 2.5.9 on centos 7.9 on a k3s v1.20.6+k3s1 cluster then install longhorn 1.2.2, installed as vms on a proxmox 7.x server
2. Use a truenas server and make sur the mount is accessible from all the workers
3. Have a dedicated /var/lib/longhorn storage disk
4. Select an existing volume and create a backup

## Expected behavior
The backup should be created

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: centos 7.9
   - CPU per node: 4
   - Memory per node: 6G
   - Disk type(e.g. SSD/NVMe): vm disk on top of a proxmox raid10 array
   - Network bandwidth between the nodes: virtio on a 1G nic
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox VMs
 - Number of Longhorn volumes in the cluster: 1

## Additional context

- I have tried to manually create the /var/lib/longhorn-backupstore-mounts/192_168_2_50/mnt/vol1/backup/longhorn/backupstore and assign a 777 mask to it with no luck
- I also tried to disable selinux on the worker nodes, with no luck

**Comment by rpelissi** [comment]
[longhorn-support-bundle_657d1a8c-fc70-4c4a-b8ee-589f8f5d80bf_2021-12-15T15-10-56Z.zip](https://github.com/longhorn/longhorn/files/7720543/longhorn-support-bundle_657d1a8c-fc70-4c4a-b8ee-589f8f5d80bf_2021-12-15T15-10-56Z.zip)

**Comment by joshimoo** [comment]
Try manually mounting the nfs server export inside of the longhorn-manager or any other pod running as root.
Afterwards see if you can create folders, could be a miss configuration of the permissions on your NAS.
I.E root squash?

**Comment by rpelissi** [comment]
Hi,
Ok root cause is that the NFS mapped user and group was not correct for loghorn, Now all is good.
Thanks!
