### ISSUE TITLE
[BUG] Upgrade failed through Rancher (2.5.5) UI from 1.2.0 -> 1.2.2

### ISSUE THREAD

**Issue by KosrenDQ** [longhorn/longhorn#3424]
## Describe the bug

The upgrade of Longhorn from version 1.2.0 to 1.2.2 failed with the following error message
```
Failed to install app longhorn-system. Error: UPGRADE FAILED: kind CustomResourceDefinition with the name "backups.longhorn.io" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart
```

## To Reproduce

1. Go to Apps
2. Click on Longhorn Upgrade
3. Review settings and start
4. See error message above in the longhorn chart overview

## Expected behavior

Expected that all workloads from longhorn will be updated to version 1.2.2

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.2.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 7
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: Ubuntu Server 20.04
   - CPU per node: 4
   - Memory per node: 64
   - Disk type(e.g. SSD/NVMe): SSD/HDD/NVMe
   - Network bandwidth between the nodes: 10G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal/VM
 - Number of Longhorn volumes in the cluster: 26

**Comment by PhanLe1010** [comment]
Seems to be related to the issue https://github.com/longhorn/longhorn/issues/3166

There are 2 rancher UIs:
* the old one <img width="1068" alt="Screen Shot 2021-12-16 at 3 57 44 PM" src="https://user-images.githubusercontent.com/22139961/146466289-c5ea39c4-9558-4d3e-80f4-285d469d4e67.png">

* and the new one <img width="1078" alt="Screen Shot 2021-12-16 at 3 58 19 PM" src="https://user-images.githubusercontent.com/22139961/146466332-b148827d-05b8-4e10-855a-1bd6e611d138.png">


Please use the same UI that you installed Longhorn to upgrade Longhorn

**Comment by KosrenDQ** [comment]
Hi @PhanLe1010, thank you for your fast reply.
I am aware of this issue. I created the longhorn with the old catalog ui and also updated all versions with it, the last update was to version 1.2.0.
I do not use the new UI because there is no chart for the newer Longhorn Verions.
![grafik](https://user-images.githubusercontent.com/6208682/146504211-55a00f24-8bf9-434a-8f6b-ab41bc7b5455.png)

Is it safe to just delete the CRD? And try to rerun the update process?

**Comment by ajacques** [comment]
If you delete the CRDs, doesn't that mean you have to delete the K8s resources matching the CRDs too which would mean you lose PVCs? 

I wrote a blog post on how I upgraded it [here](https://www.technowizardry.net/2021/12/upgrading-longhorn-from-helm-2-in-rancher-2-6-the-hard-way/) without deleting any data. Ultimately, I used kubectl change the labels and annotations. Then used Helm to deploy over top of the existing resources and it worked. I think this should be the same fix for your case.

```
KUBE_CONTEXT=prod

kubectl --context=$KUBE_CONTEXT get crds -o name | grep longhorn | xargs -I % kubectl --context=$KUBE_CONTEXT label --overwrite -n longhorn-system % app.kubernetes.io/managed-by=Helm

kubectl --context=$KUBE_CONTEXT get crds -o name | grep longhorn | xargs -I % kubectl --context=$KUBE_CONTEXT annotate -n longhorn-system % meta.helm.sh/release-name=longhorn-crd

kubectl --context=$KUBE_CONTEXT get crds -o name | grep longhorn | xargs -I % kubectl --context=$KUBE_CONTEXT annotate -n longhorn-system % meta.helm.sh/release-namespace=longhorn-system

kubectl --context=$KUBE_CONTEXT get psp longhorn-psp -o name | xargs -I % kubectl --context=$KUBE_CONTEXT annotate % meta.helm.sh/release-name=longhorn

kubectl --context=$KUBE_CONTEXT get psp longhorn-psp -o name | xargs -I % kubectl --context=$KUBE_CONTEXT annotate % meta.helm.sh/release-namespace=longhorn-system

kubectl --context=$KUBE_CONTEXT -n longhorn-system get configMap,service,ds,deploy,serviceaccount,role,rolebinding -o name  | xargs -I % kubectl --context=$KUBE_CONTEXT label --overwrite -n longhorn-system % app.kubernetes.io/managed-by=Helm

kubectl --context=$KUBE_CONTEXT -n longhorn-system get configMap,service,ds,deploy,serviceaccount,role,rolebinding -o name  | xargs -I % kubectl --context=$KUBE_CONTEXT -n longhorn-system annotate % meta.helm.sh/release-name=longhorn

kubectl --context=$KUBE_CONTEXT -n longhorn-system get configMap,service,ds,deploy,serviceaccount,role,rolebinding -o name  | xargs -I % kubectl --context=$KUBE_CONTEXT -n longhorn-system annotate % meta.helm.sh/release-namespace=longhorn-system

kubectl --context=$KUBE_CONTEXT get clusterrole,clusterrolebinding -o name | grep longhorn   | xargs -I % kubectl --context=$KUBE_CONTEXT label --overwrite -n longhorn-system % app.kubernetes.io/managed-by=Helm

kubectl --context=$KUBE_CONTEXT get clusterrole,clusterrolebinding -o name | grep longhorn   | xargs -I % kubectl --context=$KUBE_CONTEXT annotate % meta.helm.sh/release-namespace=longhorn-system

kubectl --context=$KUBE_CONTEXT get clusterrole,clusterrolebinding -o name | grep longhorn   | xargs -I % kubectl --context=$KUBE_CONTEXT annotate % meta.helm.sh/release-name=longhorn
```

**Comment by jenting** [comment]
If you're using the old UI to manage, please keep using the old UI to manage it.
Also, please do not delete the CRDs otherwise all the Longhorn CRs would lost.

**Comment by KosrenDQ** [comment]
@ajacques Thank you, your post relates to Rancher 2.6, I still use the old version 2.5.5. Will your description also match for the old Rancher version 2.5.5?

@jenting As I wrote, I have created Longhorn with old UI and updated each time with old UI. I thought when I delete the CRD, the Helm Chart would recreate it during the update process??

**Comment by jenting** [comment]
Right, but it also means that the Longhorn CRs would be deleted as well. Then, the Longhorn cluster will broken.

**Comment by KosrenDQ** [comment]
ahh I see, thank you! Then this is not the way.

**Comment by ajacques** [comment]
> @ajacques Thank you, your post relates to Rancher 2.6, I still use the old version 2.5.5. Will your description also match for the old Rancher version 2.5.5?

It'll let you migrate to Helm 3 even if you're still using Rancher 2.5.x. I assumed this is the problem because this is the same error I got when I tried to switch my Helm 2 version of Longhorn to Helm 3.

> Right, but it also means that the Longhorn CRs would be deleted as well. Then, the Longhorn cluster will broken.

My proposed fix does not delete the CRDs. It modifies the CRDs so you can upgrade in place.

**Comment by innobead** [comment]
> > @ajacques Thank you, your post relates to Rancher 2.6, I still use the old version 2.5.5. Will your description also match for the old Rancher version 2.5.5?
> 
> This allows you to upgrade to Helm 3 (it's actually not related to Rancher 2.6 or Rancher 2.5, but I ended up doing this because Rancher 2.6 removed Helm 2, but ultimately it's a similar problem). I assumed this is your problem because this is the same error I got when I tried to switch my Helm 2 version of Longhorn to Helm 3.
> 
> > Right, but it also means that the Longhorn CRs would be deleted as well. Then, the Longhorn cluster will broken.
> 
> My proposed fix does not delete the CRDs. Note the commands do not delete any resources. It modifies the CRDs so you can upgrade in place. Following this, I was able to continue using Longhorn **without** deleting any volumes and after upgrading PVCs and restarting pods, it worked perfectly.

cc @shuo-wu

**Comment by KosrenDQ** [comment]
@ajacques 
Thank you for this explanation. I will try to update between the years and will report back in this issue.

**Comment by jenting** [comment]
> If you delete the CRDs, doesn't that mean you have to delete the K8s resources matching the CRDs too which would mean you lose PVCs?
> 
> Instead of deleting CRDs, I figured out a way to upgrade to Helm 3 in place and wrote a blog post on how I upgraded it [here](https://www.technowizardry.net/2021/12/upgrading-longhorn-from-helm-2-in-rancher-2-6-the-hard-way/) without deleting any data or CRDs. Ultimately, I used kubectl change the labels and annotations. Then used Helm to deploy over top of the existing resources and it worked. I think this should be the same fix for your case.
> 
> ```
> KUBE_CONTEXT=prod
> 
> kubectl --context=$KUBE_CONTEXT get crds -o name | grep longhorn | xargs -I % kubectl --context=$KUBE_CONTEXT label --overwrite -n longhorn-system % app.kubernetes.io/managed-by=Helm
> 
> kubectl --context=$KUBE_CONTEXT get crds -o name | grep longhorn | xargs -I % kubectl --context=$KUBE_CONTEXT annotate -n longhorn-system % meta.helm.sh/release-name=longhorn-crd
> 
> kubectl --context=$KUBE_CONTEXT get crds -o name | grep longhorn | xargs -I % kubectl --context=$KUBE_CONTEXT annotate -n longhorn-system % meta.helm.sh/release-namespace=longhorn-system
> 
> kubectl --context=$KUBE_CONTEXT get psp longhorn-psp -o name | xargs -I % kubectl --context=$KUBE_CONTEXT annotate % meta.helm.sh/release-name=longhorn
> 
> kubectl --context=$KUBE_CONTEXT get psp longhorn-psp -o name | xargs -I % kubectl --context=$KUBE_CONTEXT annotate % meta.helm.sh/release-namespace=longhorn-system
> 
> kubectl --context=$KUBE_CONTEXT -n longhorn-system get configMap,service,ds,deploy,serviceaccount,role,rolebinding -o name  | xargs -I % kubectl --context=$KUBE_CONTEXT label --overwrite -n longhorn-system % app.kubernetes.io/managed-by=Helm
> 
> kubectl --context=$KUBE_CONTEXT -n longhorn-system get configMap,service,ds,deploy,serviceaccount,role,rolebinding -o name  | xargs -I % kubectl --context=$KUBE_CONTEXT -n longhorn-system annotate % meta.helm.sh/release-name=longhorn
> 
> kubectl --context=$KUBE_CONTEXT -n longhorn-system get configMap,service,ds,deploy,serviceaccount,role,rolebinding -o name  | xargs -I % kubectl --context=$KUBE_CONTEXT -n longhorn-system annotate % meta.helm.sh/release-namespace=longhorn-system
> 
> kubectl --context=$KUBE_CONTEXT get clusterrole,clusterrolebinding -o name | grep longhorn   | xargs -I % kubectl --context=$KUBE_CONTEXT label --overwrite -n longhorn-system % app.kubernetes.io/managed-by=Helm
> 
> kubectl --context=$KUBE_CONTEXT get clusterrole,clusterrolebinding -o name | grep longhorn   | xargs -I % kubectl --context=$KUBE_CONTEXT annotate % meta.helm.sh/release-namespace=longhorn-system
> 
> kubectl --context=$KUBE_CONTEXT get clusterrole,clusterrolebinding -o name | grep longhorn   | xargs -I % kubectl --context=$KUBE_CONTEXT annotate % meta.helm.sh/release-name=longhorn
> ```

It looks fantastic and glad to see it's workable without having to reinstall the longhorn cluster so the Longhorn app is able to be managed by the new Rancher UI after migration. Thanks for the sharing.

**Comment by jenting** [comment]
@ajacques 
Would you mind contributing to the Longhorn [knowledge base](https://longhorn.io/kb/) according to your [blog post](https://www.technowizardry.net/2021/12/upgrading-longhorn-from-helm-2-in-rancher-2-6-the-hard-way/)?

If yes, please file the PR to the https://github.com/longhorn/website and we'll review it, thank you :pray:

**Comment by KosrenDQ** [comment]
Sorry for my late reply 😶‍

@ajacques 
I performed all the commands, after that I used the new Rancher UI to upgrade Longhorn to the newest version.
This failed with the following error message:
```
helm  upgrade --history-max=5 --install=true --namespace=longhorn-system  --timeout=10m0s  --values=/home/shell helm/values-longhorn-1.2.300-up1.2.3.yaml  --version=1.2.300+up1.2.3 --wait=true longhorn-system  /home/shell/helm/longhorn-1.2.300-up1.2.3.tgz
Release "longhorn-system" does not exist. Installing it now. 
Error: rendered manifests contain a resource that already exists. Unable to continue with install: PodSecurityPolicy "longhorn-psp" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: key "app.kubernetes.io/managed-by" must equal "Helm": current value is "Tiller"; annotation validation error: 
key "meta.helm.sh/release-name" must equal "longhorn-system": current value is "longhorn" 
```

In your blog post, you say "deploy the Longhorn application". Do you mean, that I need to redeploy the Chart from the marketplace instead of updating the old Longhorn App?

**Comment by ajacques** [comment]
> In your blog post, you say "deploy the Longhorn application". Do you mean, that I need to redeploy the Chart from the marketplace instead of updating the old Longhorn App?

Yes, you're going to deploy it from the Marketplace since that'll ensure it gets installed with Helm v3.

>  label validation error: key "app.kubernetes.io/managed-by" must equal "Helm": current value is "Tiller"

This can be fixed by running (and I've updated the doc):

```
kubectl --context=$KUBE_CONTEXT get psp longhorn-psp -o name | xargs -I % kubectl --context=$KUBE_CONTEXT label --overwrite -n longhorn-system % app.kubernetes.io/managed-by=Helm
```

> key "meta.helm.sh/release-name" must equal "longhorn-system": current value is "longhorn" 

However, this error is interesting. AFAIK, the release-name was supposed to be 'longhorn', not 'longhorn-system', as per [1](https://github.com/rancher/charts/blob/5c38276c16a451b7a5213faec70f13d76a764c2b/charts/longhorn/1.2.200%2Bup1.2.2/Chart.yaml#L9), [2](https://github.com/rancher/charts/blob/dev-v2.6/charts/longhorn/1.2.300%2Bup1.2.3/Chart.yaml#L10), and [3](https://github.com/longhorn/longhorn/blob/master/chart/README.md) Maybe somebody else knows why. It's easy to fix, but maybe somebody else knows if this is correct or not?

**Comment by KosrenDQ** [comment]
> However, this error is interesting. AFAIK, the release-name was supposed to be 'longhorn', not 'longhorn-system', as per [1](https://github.com/rancher/charts/blob/5c38276c16a451b7a5213faec70f13d76a764c2b/charts/longhorn/1.2.200%2Bup1.2.2/Chart.yaml#L9), [2](https://github.com/rancher/charts/blob/dev-v2.6/charts/longhorn/1.2.300%2Bup1.2.3/Chart.yaml#L10), and [3](https://github.com/longhorn/longhorn/blob/master/chart/README.md) It's easy to fix, but maybe somebody else knows if this is correct or not?

The app name comes from the old marketplace where I firstly install longhorn, is there a way that I can just rename the current App from `longhorn-system` to `longhorn`? I am not brave enough to just reinstall the newer version with a different name 😅

**Comment by shuo-wu** [comment]
I am not sure if it's possible and what the potential impact is. If you want to retain the Longhorn volumes in the old Longhorn, I would not recommend doing so. Does this naming matter?

**Comment by KosrenDQ** [comment]
> Does this naming matter?
I am not sure about that. As @ajacques mentioned in his post, I changed the labels and annotations. In his post, the name of the app is `longhorn`. Now, when I reinstall the App over the marketplace, but the old app has the name `longhorn-system`, I think this could lead to a double deployed application with different names. But I did not try this yet because the cluster is productive.

**Comment by ajacques** [comment]
> I am not sure about that. As @ajacques mentioned in his post, I changed the labels and annotations. In his post, the name of the app is `longhorn`. Now, when I reinstall the App over the marketplace, but the old app has the name `longhorn-system`, I think this could lead to a double deployed application with different names. But I did not try this yet because the cluster is productive.

If you run
> helm  list --namespace=longhorn-system

Does it show a release named longhorn-system and longhorn-crds? 

There's three options:
1. **The safe option** - Do nothing
2. Rename the Helm release from `longhorn-system` to `longhorn` using something like [this](https://engineering.salesforce.com/how-to-rename-a-helm-release-6fdcd7526ac7)
3. Continue using the `longhorn-system` release by changing the `annotate -n longhorn-system % meta.helm.sh/release-name=longhorn` parts in my script to `annotate -n longhorn-system % meta.helm.sh/release-name=longhorn-system`

On further reading of your GitHub issue it seems like your issue was that the CRDs were not created using Helm, but the Longhorn application itself was? If so, then option 3 can be used to undo the part that is currently broken and should permit upgrades to continue:

```
kubectl --context=$KUBE_CONTEXT get psp longhorn-psp -o name | xargs -I % kubectl --context=$KUBE_CONTEXT annotate % meta.helm.sh/release-name=longhorn-system
kubectl --context=$KUBE_CONTEXT -n longhorn-system get configMap,service,ds,deploy,serviceaccount,role,rolebinding -o name  | xargs -I % kubectl --context=$KUBE_CONTEXT -n longhorn-system annotate % meta.helm.sh/release-name=longhorn-system
kubectl --context=$KUBE_CONTEXT get clusterrole,clusterrolebinding -o name | grep longhorn   | xargs -I % kubectl --context=$KUBE_CONTEXT annotate % meta.helm.sh/release-name=longhorn-system
```

Changing the annotation doesn't do much other than tell Helm that yes it's okay to touch those resources.

**Comment by KosrenDQ** [comment]
@ajacques Thank you so much!!
With option 3 I was able to upgrade longhorn and after that successfully update rancher to the latest version and I can still manage everything correctly 🥳
