### ISSUE TITLE
[FEATURE] Support s390x IBM Z

### ISSUE THREAD

**Issue by agracey** [longhorn/longhorn#3425]
## Is your feature request related to a problem? Please describe

We are looking to use Longhorn as the storage layer on IBM Z. This would expand Rancher's ability to run a full solution on any infrastructure.

## Describe the solution you'd like

Add IBM Z runners to the build process and package the output into the airgap tarball. 

## Additional context

This is part of the larger push to build Rancher components on IBM Z.

**Comment by innobead** [comment]
cc @meldafrawi

**Comment by thehejik** [comment]
I've validated today's `master` build of Longhorn on s390x installed from locally checkouted helm chart stored on upstream lh master branch.

#### Environment description
* 1 server and 2 agent nodes deployed with RKE2 `v1.23.5+rke2r1` (without rancher mcm)
* using zVM hypervisor - each VM with 2 vCPU, 8GB RAM and 20GB btrfs as rootfs
* all nodes running on SLE15SP2 with `open-iscsi` and `nfs-client` installed
* Tested with Minio as S3 backend, `pytest -m coretest` executed

Longhorn installed by:
```
helm upgrade --install=true longhorn ./ --namespace=longhorn-system --create-namespace \
    --set image.longhorn.instanceManager.tag=master-head \
    --set image.longhorn.shareManager.tag=master-head \
    --set image.longhorn.backingImageManager.tag=master-head
```

####  Results
`= 7 failed, 45 passed, 6 skipped, 173 deselected, 1 error in 5289.67s (1:28:09)`
* pytest logs [here](https://github.com/longhorn/longhorn/files/8640346/220506-longhorn-master-test-results-minio-btrfs-coretest-test.log)
* support bundle [here](https://github.com/longhorn/longhorn/files/8640352/longhorn-support-bundle_bf4e6785-68f6-4c05-bb90-1d9a81050e7b_2022-05-06T13-18-24Z.zip)

All pods and other resources in `longhorn-system` seem to be healthy as well as webui.

I'm still using a bit outdated (rebased 24d ago) custom [fork](https://github.com/thehejik/longhorn-tests/tree/master-s390x) of longhorn-tests repository and also test image so some failures could be ralated to that.

I'd appreciate if someone from LH team could have a look at the results if these are ok, thanks.

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by innobead** [comment]
@thehejik Could you run again preview 1? I would expect we will have the result for each milestone here because we don't have s390x automation and it's better to have each update. Thank you.

**Comment by thehejik** [comment]
Results from testing `v1.3.0-preview1` build and longhorn-tests from the same tag, this time with nfs & minio:
`= 6 failed, 60 passed, 5 skipped, 220 deselected, 2 errors in 7678.35s (2:07:58)`

```
test_backing_image.py::test_backing_image_basic_operation FAILED
test_backing_image.py::test_engine_live_upgrade_with_backing_image FAILED
test_engine_upgrade.py::test_engine_offline_upgrade FAILED
test_engine_upgrade.py::test_engine_live_upgrade FAILED
test_engine_upgrade.py::test_engine_live_upgrade_with_intensive_data_writing FAILED
test_ha.py::test_ha_salvage FAILED
```

* pytest logs [here](https://github.com/longhorn/longhorn/files/8659073/220510-longhorn-v1.2.3-preview1-test-results-nfs%2Bminio-btrfs-coretest-test.log)
* support bundle [here](https://github.com/longhorn/longhorn/files/8659079/longhorn-support-bundle_7244094b-0de1-465f-b831-a3030faa83dc_2022-05-10T06-52-54Z.zip)

**Comment by thehejik** [comment]
Once I rebuilt `longhorn-engine` image for upgrade tests all the upgrade related tests from `-m coretest` started to PASS.

Results from `-m coretest` pytest run on `v1.3.0-preview1` on s390x and logs [here](https://github.com/longhorn/longhorn/files/8679151/220511-longhorn-v1.2.3-preview1-test-results-minio-btrfs-coretest-successful.log):
```
test_ha.py::test_ha_salvage FAILED
= 1 failed, 55 passed, 6 skipped, 173 deselected, 2 errors in 5818.04s (1:36:58) =
```

Results from `"full"` pytest run on `v1.3.0-preview1` on s390x and logs [here](https://github.com/longhorn/longhorn/files/8679156/220512-longhorn-v1.2.3-preview1-test-results-minio-btrfs-full-test.log):
```
test_backing_image.py::test_ha_salvage_with_backing_image FAILED         [  4%]
test_csi.py::test_allow_volume_creation_with_degraded_availability_csi FAILED [ 34%]
test_ha.py::test_ha_salvage FAILED                                       [ 42%]
test_ha.py::test_rebuild_with_restoration[s3] FAILED                     [ 45%]
test_migration.py::test_migration_confirm FAILED                         [ 57%]
test_node.py::test_node_default_disk_added_back_with_extra_disk_unmounted FAILED [ 65%]
test_node.py::test_node_config_annotation_invalid FAILED                 [ 67%]
test_node.py::test_node_config_annotation_missing FAILED                 [ 68%]
test_rwx.py::test_rwx_parallel_writing FAILED                            [ 82%]
test_infra.py::test_offline_node FAILED                                  [100%]
= 10 failed, 206 passed, 18 skipped, 7 errors in 30416.19s (8:26:56) =
```

**Comment by thehejik** [comment]
Results from `-m coretest` pytest run on `v1.3.0-rc1` on s390x and logs [here](https://github.com/longhorn/longhorn/files/8708330/longhorn-tests.log):
```
test_engine_upgrade.py::test_engine_live_upgrade_with_intensive_data_writing FAILED [ 76%]
test_ha.py::test_ha_salvage FAILED                                       [ 78%]
= 2 failed, 59 passed, 5 skipped, 220 deselected, 10 errors in 7476.00s (2:04:36) =
```
(used nfs and s3/minio as backup backends)

**Comment by thehejik** [comment]
Results from full pytest run on `v1.3.0-rc1` on s390x, logs [here](https://github.com/longhorn/longhorn/files/8726097/longhorn-test.log)

```
test_backing_image.py::test_ha_salvage_with_backing_image FAILED         [  4%]
test_basic.py::test_backup_lock_deletion_during_backup[s3] FAILED        [ 21%]
test_basic.py::test_allow_volume_creation_with_degraded_availability_dr[s3] FAILED [ 23%]
test_cloning.py::test_cloning_interrupted FAILED                         [ 29%]
test_engine_upgrade.py::test_engine_live_upgrade_with_intensive_data_writing FAILED [ 39%]
test_ha.py::test_ha_salvage FAILED                                       [ 40%]
test_ha.py::test_inc_restoration_with_multiple_rebuild_and_expansion[s3] FAILED [ 44%]
test_ha.py::test_inc_restoration_with_multiple_rebuild_and_expansion[s3] ERROR [ 44%]
test_ha.py::test_engine_crash_for_dr_volume[s3] FAILED                   [ 47%]
test_ha.py::test_engine_crash_for_dr_volume[s3] ERROR                    [ 47%]
test_node.py::test_disable_scheduling_on_cordoned_node FAILED            [ 58%]
test_node.py::test_replica_scheduler_too_large_volume_fit_any_disks FAILED [ 59%]
test_recurring_job.py::test_recurring_job_multiple_volumes[s3] FAILED    [ 80%]
test_rwx.py::test_rwx_parallel_writing FAILED                            [ 82%]
test_settings.py::test_instance_manager_cpu_reservation FAILED           [ 90%]
test_infra.py::test_offline_node FAILED                                  [100%]
test_infra.py::test_offline_node ERROR                                   [100%]
= 15 failed, 213 passed, 18 skipped, 1 warning, 3 errors in 33210.05s (9:13:30) =
```

**Comment by thehejik** [comment]
Results from full pytest run on `v1.3.0-rc2`, logs [here](https://github.com/longhorn/longhorn/files/8822058/longhorn-test-full.log)

```
test_backing_image.py::test_ha_salvage_with_backing_image FAILED         [  4%]
test_cloning.py::test_cloning_interrupted FAILED                         [ 29%]
test_csi.py::test_allow_volume_creation_with_degraded_availability_csi FAILED [ 33%]
test_ha.py::test_inc_restoration_with_multiple_rebuild_and_expansion[s3] FAILED [ 44%]
test_ha.py::test_dr_volume_with_restore_command_error[s3] FAILED         [ 46%]
test_ha.py::test_engine_crash_for_restore_volume[s3] FAILED              [ 46%]
test_ha.py::test_engine_crash_for_dr_volume[s3] FAILED                   [ 47%]
test_scheduling.py::test_data_locality_basic FAILED                      [ 89%]
test_settings.py::test_instance_manager_cpu_reservation FAILED           [ 90%]
test_settings.py::test_setting_backing_image_auto_cleanup FAILED         [ 91%]
test_infra.py::test_offline_node FAILED                                  [100%]
test_infra.py::test_offline_node ERROR                                   [100%]
= 11 failed, 216 passed, 19 skipped, 1 warning, 1 error in 34972.54s (9:42:52) =
```

**Comment by thehejik** [comment]
Results from `-m coretest` on `v1.3.0-rc3` running on three nodes `v1.23.7+rke2r1` SLE15SP3.s390x cluster with EXT4 rootfs, Minio as s3 backupstore. Logs [here](https://github.com/longhorn/longhorn/files/8862214/longhorn-test.log)

```
test_basic.py::test_allow_volume_creation_with_degraded_availability FAILED [ 53%]
test_csi.py::test_allow_volume_creation_with_degraded_availability_csi FAILED [ 67%]
= 2 failed, 54 passed, 6 skipped, 184 deselected, 1 warning in 6084.31s (1:41:24) =
```

**Comment by innobead** [comment]
@cchien816 Could you follow up on the test result to see if any difference compared with our amd64? then we will better understand the failure is actually because of still some flaky tests. Thank you.

cc @longhorn/qa

**Comment by thehejik** [comment]
Results from full pytest run on `v1.3.0-rc3`, logs [here](https://github.com/longhorn/longhorn/files/8868452/longhorn-test.log)

```
test_backing_image.py::test_ha_backup_deletion_recovery[s3] FAILED       [  4%]
test_basic.py::test_allow_volume_creation_with_degraded_availability FAILED [ 22%]
test_basic.py::test_multiple_volumes_creation_with_degraded_availability[s3] FAILED [ 23%]
test_cloning.py::test_cloning_interrupted FAILED                         [ 29%]
test_csi.py::test_csi_io FAILED                                          [ 30%]
test_csi.py::test_allow_volume_creation_with_degraded_availability_csi FAILED [ 33%]
test_ha.py::test_engine_crash_for_restore_volume[s3] FAILED              [ 46%]
test_ha.py::test_engine_crash_for_dr_volume[s3] FAILED                   [ 47%]
test_ha.py::test_autosalvage_with_data_locality_enabled FAILED           [ 51%]
test_scheduling.py::test_replica_rebuild_per_volume_limit FAILED         [ 87%]
test_scheduling.py::test_data_locality_basic FAILED                      [ 89%]
test_settings.py::test_instance_manager_cpu_reservation FAILED           [ 90%]
test_settings.py::test_setting_backing_image_auto_cleanup FAILED         [ 91%]
test_infra.py::test_offline_node FAILED                                  [100%]
test_infra.py::test_offline_node ERROR                                   [100%]
= 14 failed, 213 passed, 19 skipped, 1 warning, 1 error in 34455.86s (9:34:15) =
```

**Comment by innobead** [comment]
Mention in the 1.3.0 doc, https://github.com/longhorn/website/commit/87cd69f9bbc22bfd173e820ca9726e4614e99b49

**Comment by cchien816** [comment]
Compare IBM Z test result and SLES test ressult, there are few test results may need to keep tracking : 
- test_scheduling.py::test_data_locality_basic - not happen in SLES test [result](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/152/testReport/tests/test_scheduling/test_data_locality_basic/)
- test_settings.py::test_instance_manager_cpu_reservation - not happen in SLES test [result](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/152/testReport/tests/test_settings/test_instance_manager_cpu_reservation/)
- test_infra.py::test_offline_node - not happen in SLES test [result](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/152/testReport/tests/test_infra/test_offline_node/)

**Comment by innobead** [comment]
> Compare IBM Z test result and SLES test ressult, there are few test results may need to keep tracking :
> 
> * test_scheduling.py::test_data_locality_basic - not happen in SLES test [result](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/152/testReport/tests/test_scheduling/test_data_locality_basic/)
> * test_settings.py::test_instance_manager_cpu_reservation - not happen in SLES test [result](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/152/testReport/tests/test_settings/test_instance_manager_cpu_reservation/)
> * test_infra.py::test_offline_node - not happen in SLES test [result](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/152/testReport/tests/test_infra/test_offline_node/)

@thehejik Could you help manually verify these test cases or even run them to see if they will pass? Thanks.

**Comment by thehejik** [comment]
Just re-verified the failed tests by deploying a fresh RKE2.s390x cluster with more RAM (4->8GB), vCPUs (2->4) and storage (20->40GB).

* `test_scheduling.py::test_data_locality_basic` - PASSED when `RETRY_INTERVAL` is set to 2 instead of default 0.5 in `common.py`
* `test_settings.py::test_instance_manager_cpu_reservation` - PASSED no modification needed
* `test_infra.py::test_offline_node` - still FAILED most likely because it's intended for AWS infra only.

So I think the results are consistent with amd64/SLES.

**Comment by innobead** [comment]
Closing, because the integration is finished and all testings align with other supported arches.

**Comment by thehejik** [comment]
Results from `-m coretest` on `v1.3.0` running on three nodes `v1.24.1+rke2r2` SLE15SP3.s390x cluster with EXT4 rootfs, Minio as s3 backupstore. Logs [here](https://github.com/longhorn/longhorn/files/8919835/longhorn-test.log)

```
test_csi.py::test_allow_volume_creation_with_degraded_availability_csi FAILED [ 67%]
= 1 failed, 55 passed, 6 skipped, 185 deselected, 1 warning in 5603.23s (1:33:23) =
```

**Comment by thehejik** [comment]
Results from full pytest run on `v1.3.0`, logs [here](https://github.com/longhorn/longhorn/files/8920574/longhorn-test.log)

```
test_cloning.py::test_cloning_interrupted FAILED                         [ 29%]
test_csi.py::test_allow_volume_creation_with_degraded_availability_csi FAILED [ 33%]
test_ha.py::test_rebuild_with_restoration[s3] FAILED                     [ 43%]
test_ha.py::test_engine_crash_for_restore_volume[s3] FAILED              [ 46%]
test_ha.py::test_engine_crash_for_dr_volume[s3] FAILED                   [ 47%]
test_scheduling.py::test_data_locality_basic FAILED                      [ 89%]
test_infra.py::test_offline_node FAILED                                  [100%]
test_infra.py::test_offline_node ERROR                                   [100%]
= 7 failed, 220 passed, 20 skipped, 1 warning, 1 error in 32744.49s (9:05:44) ==
```
