### ISSUE TITLE
[QUESTION] How to solve server time difference when using private minio as backup?

### ISSUE THREAD

**Issue by Jenniferyingni** [longhorn/longhorn#3436]
## Environment

 - Longhorn version: 1.1.0
 - Kubernetes version: 1.17.2

## Additional context

I used my private minio as backup and got this error
```
AWS Error: RequestTimeTooSkewed The difference between the request time and the server's time is too large.
I guess the reason is my server time is different from the default us-east-1 region time.
```

I tried to change
```
s3://backupbucket@us-east-1/
```
to
```
 s3://backupbucket@cn-north-1/
```
but it didn't work.

related issue: https://github.com/longhorn/longhorn/issues/1477

**Comment by c3y1huang** [comment]
The error says that time is not matching on client and server. You could check if the system clocks are in sync.
