### ISSUE TITLE
[QUESTION] Can't find longhorn volume. How to troubleshoot?

### ISSUE THREAD

**Issue by stevek-pro** [longhorn/longhorn#3442]
## Question
> Suggest to use https://github.com/longhorn/longhorn/discussions to ask questions.

## Environment

 - Longhorn version: latest
 - Kubernetes version: 1.21
 - Node config
   - OS type and version Ubuntu
   - CPU per node: 4
   - Memory per node: 8
   - Disk type NVMe
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

## Additional context
Can't find longhorn volume. How to troubleshoot this?

This is my error:
```

  Type     Reason              Age                    From                         Message
  ----     ------              ----                   ----                         -------
  Warning  ProvisioningFailed  4m31s (x242 over 64m)  persistentvolume-controller  storageclass.storage.k8s.io "longhorn-volumes" not found
```

**Comment by jenting** [comment]
It seems like the StorageClass `longhorn-volumes` does not exist.
How do you deploy the Longhorn volume, via yaml right?

You could check some yaml examples [here](https://longhorn.io/docs/1.2.3/references/examples/).

Besides that, it'd be good if you could specific which Longhorn version you're using, not the `latest` :wink:

**Comment by stevek-pro** [comment]
@jenting Thanks. I solved the issue. It was not an issue of percona.

**Comment by shuo-wu** [comment]
The PVC and PV created via Longhorn GUI are using a non-existing StorageClass name. This name is controlled by setting `Default Longhorn Static StorageClass Name` and the default value is `longhorn-static`. Then if you want to directly use this PVC/PV in a workload, you need to:
1. either create a StorageClass with the name. In your case, the name should be `longhorn-volumes`.
2. or you can modify the setting to an existing Longhorn StroageClass name, then recreate the PVC and PV for the volume.

In general, Kubernetes relies on StorageClass to dynamically provision/delete or attach/detach a volume. If you are not familiar with StorageClass, you can refer to the related official docs first:
https://kubernetes.io/docs/concepts/storage/storage-classes/
