### ISSUE TITLE
[BUG] Expand volume error

### ISSUE THREAD

**Issue by 18133880978** [longhorn/longhorn#3450]
## Question
> Suggest to use https://github.com/longhorn/longhorn/discussions to ask questions.

## Environment

 - Longhorn version: v1.2.3
 - Kubernetes version: v1.18.9
 - Node config
   - OS type and version: centos7.7
   - CPU per node: 16core
   - Memory per node: 32G
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

## Additional context

I want to expand volume,but it's error.
longhorn-ui:
![图片](https://user-images.githubusercontent.com/31305873/147044920-28a6dd53-2704-456d-98f3-205e3346281f.png)

longhorn-manager:
![图片](https://user-images.githubusercontent.com/31305873/147045023-480ec3e9-3603-40be-bec5-04d7801b1ca2.png)

**Comment by c3y1huang** [comment]
Looks like the `storageClassName` is missing in the spec.
Can you output `kubectl -n longhorn-system get pv -o yaml`?
How did you create the Volume and the PV/PVC?

**Comment by 18133880978** [comment]
the yaml file that You can see the attachment.

I creaete the Volume with PersistentVolumeClaim.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "longhorn/longhorn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月22日(星期三) 下午2:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [longhorn/longhorn] [BUG] Expand volume error (Issue #3450)





 
Looks like the storageClassName is missing in the spec.
 Can you output kubectl -n longhorn-system get pv -o yaml?
 How did you create the Volume and the PV/PVC?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 18133880978** [comment]
I'm so sorry,it's my wrong.
I already know what the problem is。
thanks all.

**Comment by c3y1huang** [comment]
@18133880978 would you mind sharing the issue cause and how you've managed to fix this?
