### ISSUE TITLE
namespace longhorn-system stuck Terminating

### ISSUE THREAD

**Issue by shumintao** [longhorn/longhorn#3457]
## Describe the bug

- namespace 

```
[root@shumin-master longhorn]# kubectl get namespace longhorn-system -o json
         {
                "lastTransitionTime": "2021-12-23T06:16:37Z",
                "message": "Some resources are remaining: engineimages.longhorn.io has 1 resource instances, nodes.longhorn.io has 1 resource instances, replicas.longhorn.io has 9 resource instances",
                "reason": "SomeResourcesRemain",
                "status": "True",
                "type": "NamespaceContentRemaining"
            },
            {
                "lastTransitionTime": "2021-12-23T06:16:37Z",
                "message": "Some content in the namespace has finalizers remaining: longhorn.io in 11 resource instances",
                "reason": "SomeFinalizersRemain",
                "status": "True",
                "type": "NamespaceFinalizersRemaining"
            }
        ],
        "phase": "Terminating"
```

- delete replica.longhorn.io
```
[root@shumin-master ~]# kubectl -n longhorn-system delete  replica.longhorn.io --all
replica.longhorn.io "sc-test1-r-07001148" deleted
replica.longhorn.io "sc-test1-r-14c0f332" deleted
replica.longhorn.io "sc-test1-r-6a77f1aa" deleted
replica.longhorn.io "test1-r-a04bfba2" deleted
replica.longhorn.io "test1-r-d122b62d" deleted
replica.longhorn.io "test1-r-e744df82" deleted
replica.longhorn.io "test2-r-1a79ad9c" deleted
replica.longhorn.io "test2-r-9c02ea27" deleted
replica.longhorn.io "test2-r-f2c26b5b" deleted
```

- delete engineimage.longhorn.io

```
[root@shumin-master longhorn]# klh delete engineimages.longhorn.io --all
engineimage.longhorn.io "ei-fa2dfbf0" deleted
```

- ns

```
[root@shumin-master longhorn]# k get ns
NAME              STATUS        AGE
default           Active        41d
kube-node-lease   Active        41d
kube-public       Active        41d
kube-system       Active        41d
kubeedge          Active        9d
longhorn-system   Terminating   2d2h
```

```
[root@shumin-master longhorn]# k delete ns longhorn-system
namespace "longhorn-system" deleted
```

how to uninstall longhorn?

```
i use uninstall.yaml
also  use longhorn-manager uninstall 
but can't delete namespace longhorn-system
```

**Comment by jenting** [comment]
How did you install longhorn?
By helm? kubectl? Rancher App?

**Comment by shumintao** [comment]
> How did you install longhorn? By helm? kubectl? Rancher App?
> 
> And, how did you uninstall longhorn?

Use kubectl 
I have solve this issue 
I think this is k8s bug
kubectl edit replica.longhorn.io
And modify finalizers: []

**Comment by jenting** [comment]
> I think this is k8s bug

I think no, could you please dump the log of the uninstall Pod on the default namespace? And the log of the longhorn-manager Pods.

**Comment by jenting** [comment]
Please follow this [doc](https://longhorn.io/docs/1.2.3/deploy/uninstall/#uninstalling-longhorn-using-kubectl) to uninstall the longhorn.
Note that, since I don't know which Longhorn version you're running, so remember to switch to the correct doc version.

**Comment by shumintao** [comment]
I deleted it through this [document](https://longhorn.io/docs/1.2.3/deploy/uninstall/#uninstalling-longhorn-using-kubectl)), which may be caused by the order of deletion.
So far I've found the same problem in Kubernetes, this is problem [issus](https://github.com/kubernetes/kubernetes/issues/77086)

Before the repair：

![image](https://user-images.githubusercontent.com/26895243/147307235-b0994a1d-0b8f-468f-be06-e2e6a5fb2625.png)

After the repair：

```
apiVersion: longhorn.io/v1beta1
kind: Replica
metadata:
  creationTimestamp: "2021-12-23T10:12:49Z"
  finalizers: []
  generation: 1
```

**Comment by jenting** [comment]
Please make sure the uninstall job is finished then uninstall the longhorn components.
Otherwise, if the longhorn-manager Pod gone _or_ panic, the finalizer `longhorn.io` can't be removed by the longhorn-manager.

Remember that, the owner to remove the finalizer is the longhorn-manager.

**Comment by luke-zhu** [comment]
The significance of this issue is that if you delete the namespace, you can't use longhorn on that cluster anymore. The CRDs are stuck in terminating state, so you can't create any new longhorn resources.

It seems possible to clean things up by running commands like this after re-creating the CRDs and removing any validation webhooks:

kubectl get volumes.longhorn.io -n longhorn-system -o name | xargs kubectl -n longhorn-system patch -p '{"metadata": {"finalizers": null}}' --type=merge
