### ISSUE TITLE
[QUESTION] Error: failed to append custom certificate

### ISSUE THREAD

**Issue by vulndev** [longhorn/longhorn#3460]
## Question
How can I debug the following error:

`jWKwu9o=-----END CERTIFICATE----- , stderr, time="2021-12-23T11:25:53Z" level=error msg="failed to append custom certificates: -----BEGIN CERTIFICATE-----MIIFszCCA5u`

I try to add a minio S3 Backup Target which I had been working before rebuilding and updating my k3s cluster. I got this error within the UI in the Backup Tab after adding the URL and secret within the settings.

The secret looks like:
```yaml
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: WkFK...XXXX...WkdQUlI=
  AWS_CERT: LS0tLS1CRUdJTiBDRV... XXXX ....VORCBDRVJUSUZJQ0FURS0tLS0t
  AWS_ENDPOINTS: aHR0cHM6Ly9uYXMudnVsbi5sYW46OTAwMA==
  AWS_SECRET_ACCESS_KEY: eU5GYzN4....XXXX....QzI5WQ==
kind: Secret
metadata:
  creationTimestamp: "2021-12-23T11:25:53Z"
  name: minio-secret
  namespace: longhorn-system
  resourceVersion: "200263"
  uid: 1dc6a3b3-7cb4-4a0a-8e69-789519604465
type: Opaque
```

I tried to create the secret with different methods like from cli or via yaml. The keys are generated via (of course without the X's):
```console
echo -n https://nas.vuln.lan:9000 | base64
aHR0cHM6Ly9uYXMudnVsbi5sYW46OTAwMA==

echo -n ZAJA..XXX..GPRR | base64  # access key                  
WkFK...XXXX...WkdQUlI=

echo -n yNFc3...XXX...UC29Y | base64                    
eU5GYzN4....XXXX....QzI5WQ==  # secret key

# internal-ca in PEM format
cat ca.crt | base64 | tr -d "\n"
```
## Environment

 - Longhorn version: 1.2.3
 - Kubernetes version: v1.22.5+k3s1
 - Node config
   - OS type and version: Ubuntu 20.04.03
   - CPU per node: Quad Core
   - Memory per node: 8GB
   - Disk type: SSD
   - Network bandwidth and latency between the nodes: 1Gbit/s locally connected via Switch
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM and Baremetal

## Additional context

I had the configuration working under 1.2.2 before I rebuild my cluster. The S3 Minio runs on a TrueNAS and is still accessable via Browser and e.g. Mountain Duck with the same credentials.

**Comment by jenting** [comment]
If I understand correctly, the same secret works at Longhorn v1.2.2 but failed at v1.2.3?

**Comment by vulndev** [comment]
Yes until I reinstalled the k3s cluster longhorn with version 1.2.2 works fine, BUT I didn't check it the last two weeks, so I won't count on this 100%.

**Comment by vulndev** [comment]
So I tried all other ways to connect to the minio S3, even with curl everything works perfectly with the ca file. I have no idea how to track the problem within longhorn down because I can't find the UI errors or the corresponding backend errors. In which log files are they?

**Comment by jenting** [comment]
> 

The error message comes from UI, right?
```
`jWKwu9o=-----END CERTIFICATE----- , stderr, time="2021-12-23T11:25:53Z" level=error msg="failed to append custom certificates: -----BEGIN CERTIFICATE-----MIIFszCCA5u`
```

Could you please check the BackupTarget CR, there is a reason on the backup target unavailable reason.
```console
kubectl get backuptargets.longhorn.io -n longhorn-system -o yaml
```

**Comment by vulndev** [comment]
Ok at least we can see the complete output there (I shortened the certificate because of the mail address):

```yaml
apiVersion: v1
items:
- apiVersion: longhorn.io/v1beta1
  kind: BackupTarget
  metadata:
    creationTimestamp: "2021-12-22T23:04:19Z"
    generation: 308
    name: default
    namespace: longhorn-system
    resourceVersion: "358990"
    uid: adc49262-e0a3-4931-84f6-39212d33f42c
  spec:
    backupTargetURL: s3://longhorn@nas.vuln.lan:9000/
    credentialSecret: minio-secret
    pollInterval: 5m0s
    syncRequestedAt: "2021-12-23T23:21:36Z"
  status:
    available: false
    conditions:
      Unavailable:
        lastProbeTime: ""
        lastTransitionTime: "2021-12-23T23:21:36Z"
        message: |-
          error listing backup volume names: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.3/longhorn [backup ls --volume-only s3://longhorn@nas.vuln.lan:9000/], output failed to append custom certificates: -----BEGIN CERTIFICATE-----MIIFszCCA5ugAwIBAgIBADANBgkqhkiG9w0BAQ ...XXXX.... 2jaisK6BHDBp9Wfi22J8AmGRDV5/CvH8OtvZTsH0e2q9Ol6lobqqVxOJ6D1TqdveBNAIs+eV4KMJIGuLN42HWDVXwdMq7KMKNPrMRj7oMp1IWUCTKRNWhpcFVAbdEvIYVt1yZFkJn3Lbj0vf1ApyZMYrvkXf0910VGXxLz6W/CrXsGQQtgomsbyT2AmlvjYFlwQJoWMAWbvGkt6tvAWH/ECCa4oQpWLz9XKK2v49tnrAEQCm0Se5xRQp+QAotJXfXjeJzZFI++Ibdebp7g1LxGGrjpKCJCHrShk5kfMKnL/rN6hY2lRRpjODlHSdsEhXy935kfUHF2wQV0ePDK3vYrfSpCbwRyrScqpLtNGG35QS2WPfm0gJ/jPI/RIWuxajWKwu9o=-----END CERTIFICATE-----
          , stderr, time="2021-12-23T23:21:36Z" level=error msg="failed to append custom certificates: -----BEGIN CERTIFICATE-----MIIFszCCA5ugAwIBAgIBADANBgkqh...XXXX....kfMKnL/rN6hY2lRRpjODlHSdsEhXy935kfUHF2wQV0ePDK3vYrfSpCbwRyrScqpLtNGG35QS2WPfm0gJ/jPI/RIWuxajWKwu9o=-----END CERTIFICATE-----"
          , error exit status 1
        reason: Unavailable
        status: "True"
        type: Unavailable
    lastSyncedAt: "2021-12-23T23:21:36Z"
    ownerID: k3s-master03
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by jenting** [comment]
We did have a similar issue before, but the root cause is certificate format #3192 is incorrect.
However, you mentioned that it works at Longhorn v1.2.2, but we did not have this kind of change from v1.2.2 to v1.2.3 if I remember correctly.

Could you please double-check the certificate format? And could you please double-check it works at Longhorn v1.2.2?
Thank you.

**Comment by vulndev** [comment]
I double-checked the certificate format via: 
```console
openssl x509 -in vuln-ca.pem -text
```
an it displayed the certificate infos, which it wouldn't in DER without -inform der, if I am correct.

I also downgraded the Version to 1.2.2 and had the same issues. Of course it could be also a Problem with the TrueNAS minio Version `RELEASE.2021-10-23T03-28-24Z`, but I don't know how to troubleshoot this issue further because I have no problems to access the S3 via e.g. Mountain Duck.

**Comment by vulndev** [comment]
Ok maybe this should be mentioned within the documentation explicitly?

**Comment by jenting** [comment]
For access the remote backup target, the longhorn is the client, and the MinIO is the server.

In order to verify the remote server is the trust server, the client must provide the information that can recognize the remote server.

Provide CA certificate is not enough since a CA certificate could signs multiple certificates. Therefore, the client should provide the server certificate to 100% sure this is what we want to access the remote server.

But of course, we could add note to the doc. Are you willing to help us? If yes, please file the PR to the longhorn/website repo, thank you.
