### ISSUE TITLE
[BUG] Error Upgrade to 1.2.3

### ISSUE THREAD

**Issue by timmy59100** [longhorn/longhorn#3461]
## Describe the bug

When Upgrading from 1.22 to 1.23 the error appears:
`Failed to install app longhorn-system. Error: UPGRADE FAILED: kind CustomResourceDefinition with the name "backups.longhorn.io" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart`

I tried to remove the CRD but it didn't work. 

Now the following error appears in longhorn manager:

`E1223 12:25:22.345983       1 reflector.go:178] github.com/longhorn/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1beta1.Backup: the server could not find the requested resource (get backups.longhorn.io)`

**Comment by jenting** [comment]
Are you managed Longhorn by native helm or by Rancher server?

**Comment by timmy59100** [comment]
By rancher in old UI.

**Comment by innobead** [comment]
> By rancher in old UI.

Which rancher version? Did you upgrade rancher before upgrading longhorn? cc @khushboo-rancher @kaxing

**Comment by khushboo-rancher** [comment]
Also, can you try resetting the backup target and wait till the `Backupstore Poll Interval` passes to solve the longhorn-manager issue you are facing after deleting the CRD?
Just for info, we've have tested the upgrade from v1.2.2 to v1.2.3 using Rancher v2.6.3 (old UI)

**Comment by timmy59100** [comment]
@innobead I didnt upgrade rancher right before upgrading longhorn. Rancher version 2.5.10.

@khushboo-rancher Still th same after resetting backup target.

**Comment by jenting** [comment]
cc @khushboo-rancher @kaxing

**Comment by khushboo-rancher** [comment]
I tried the Longhorn upgrade from v1.2.2 to v1.2.3 with Rancher version v2.5.10 and it worked fine. I didn't observe any issue.

@timmy59100 Just to confirm, you had Longhorn v1.2.2 installed via Rancher old UI, then you tried to upgrade to v1.2.3?

**Comment by timmy59100** [comment]
@khushboo-rancher Yes exactly.

**Comment by timmy59100** [comment]
Anyway to recover longhorn? Because right now all longhorn managers are down.

**Comment by timmy59100** [comment]
With downgrade and upgrade again of the release the longhorn-managers came up again. But its still version 1.2.2 with the same error (different crd)

**Comment by timmy59100** [comment]
Is this releated?
https://github.com/longhorn/longhorn/blob/v0.7.0/docs/upgrade-from-v0.6.2-to-v0.7.0.md#error-kind-customresourcedefinition-with-the-name-xxx-already-exists-in-the-cluster-and-wasnt-defined-in-the-previous-release

**Comment by timmy59100** [comment]
migrated to new UI and upgrade was successful
