### ISSUE TITLE
[BUG] Nodes refusing to schedule, even with schedulable states

### ISSUE THREAD

**Issue by IceeMC** [longhorn/longhorn#3464]
## Describe the bug

On my three nodes, longhorn UI  shows disks as scheduable, but logs show otherwise.

## To Reproduce

1. K8s version is v1.22.5+k3s1
2. Attach a volume to a healthy node.
3. Watch as volumes become N/A when trying to schedule.

## Expected behavior

My volumes to schedule properly before upgrading to 1.2.3, from 1.2.2

## Log or Support bundle

```
time="2021-12-24T00:17:54Z" level=error msg="There's no available disk for replica pvc-ef8a9718-5b19-4ed5-8565-80adae06ad14-r-fdd107e8, size 53687091200"
time="2021-12-24T00:17:54Z" level=error msg="unable to schedule replica" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=us-dedi1 owner=us-dedi1 replica=pvc-ef8a9718-5b19-4ed5-8565-80adae06ad14-r-fdd107e8 state=attached volume=pvc-ef8a9718-5b19-4ed5-8565-80adae06ad14
time="2021-12-24T00:17:54Z" level=error msg="There's no available disk for replica pvc-ef8a9718-5b19-4ed5-8565-80adae06ad14-r-2e601bb9, size 53687091200"
time="2021-12-24T00:17:54Z" level=error msg="unable to schedule replica" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=us-dedi1 owner=us-dedi1 replica=pvc-ef8a9718-5b19-4ed5-8565-80adae06ad14-r-2e601bb9 state=attached volume=pvc-ef8a9718-5b19-4ed5-8565-80adae06ad14
time="2021-12-24T00:17:54Z" level=debug msg="Found 0 node has at least one schedulable disk" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=us-dedi1 owner=us-dedi1 state=attached volume=pvc-ef8a9718-5b19-4ed5-8565-80adae06ad14
time="2021-12-24T00:17:54Z" level=error msg="There's no available disk for replica pvc-ef8a9718-5b19-4ed5-8565-80adae06ad14-r-fdd107e8, size 53687091200"
time="2021-12-24T00:17:54Z" level=error msg="unable to schedule replica" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=us-dedi1 owner=us-dedi1 replica=pvc-ef8a9718-5b19-4ed5-8565-80adae06ad14-r-fdd107e8 state=attached volume=pvc-ef8a9718-5b19-4ed5-8565-80adae06ad14
time="2021-12-24T00:17:54Z" level=error msg="There's no available disk for replica pvc-ef8a9718-5b19-4ed5-8565-80adae06ad14-r-2e601bb9, size 53687091200"
time="2021-12-24T00:17:54Z" level=error msg="unable to schedule replica" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=us-dedi1 owner=us-dedi1 replica=pvc-ef8a9718-5b19-4ed5-8565-80adae06ad14-r-2e601bb9 state=attached volume=pvc-ef8a9718-5b19-4ed5-8565-80adae06ad14
```

But what I do not understand is that all disks show as scheduleable (refer to additional context)

## Environment
 - Longhorn version: v1.2.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 0
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 8 to 16
   - Memory per node: 64Gb
   - Disk type(e.g. SSD/NVMe): SSD/NVMe/HDD
   - Network bandwidth between the nodes: 1Gb/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 17

## Additional context

![Main UI](https://go.is-rocket.science/d3d9083803.png)

![Healthy nodes](https://go.is-rocket.science/367319fd29.png)

![Volume page](https://go.is-rocket.science/0010e458bc.png)

![Disks](https://go.is-rocket.science/8d05482d0d.png)

**Comment by jenting** [comment]
Could you please provide us with the support bundle? Email to longhorn-support-bundle@suse.com.

**Comment by IceeMC** [comment]
I have emailed you the support bundle accordingly.

**Comment by jenting** [comment]
Leaving a note here, the user configured the settings
- `replica-soft-anti-affinity: true`
- `replica-zone-soft-anti-affinity: false`

cc @PhanLe1010

**Comment by IceeMC** [comment]
Any update on this issue? it’s been a week.

**Comment by jenting** [comment]
> Any update on this issue? it’s been a week.

Sorry for the late reply, most of us are on vacation.

**Comment by PhanLe1010** [comment]
Thanks @jenting for the hint!

@IceeMC Please change the `replica-zone-soft-anti-affinity` setting to `true`. This allows the replica scheduling onto the node in the same zone. In the support bundle you sent, all of your nodes have empty zone (`zone: ""`) which mean they are treated as if they are in the same zone. 

![Uploading Screen Shot 2022-01-03 at 4.04.23 PM.png…]()

**Comment by IceeMC** [comment]
It appears that worked, was this feature added because this worked prior to upgrading.

**Comment by jenting** [comment]
> It appears that worked, was this feature added because this worked prior to upgrading.

I do remember we have a bug https://github.com/longhorn/longhorn/issues/3076 and we did a refactoring on the scheduling code. cc @PhanLe1010

**Comment by rpardini** [comment]
I think I'm bit by this as well, or something very similar. From-scratch deploy with 1.2.2 works, but 1.2.3 shows a lot of problems. Will investigate more later.
