### ISSUE TITLE
[BUG] Old replicas are not cleaned up

### ISSUE THREAD

**Issue by PhilipMay** [longhorn/longhorn#3468]
## Describe the bug

I have a 1 master 3 nodes cluster with a replica count of 2 (not 3). I created a volume that was put on node 1 and 2. 
Then I shut down node 2 and a replica was created on node 3. See picture below:

![image](https://user-images.githubusercontent.com/229382/147400794-dcaea5e7-9f19-496e-a75c-ed8274209ad7.png)

The problem is: If I start node 2 again and ssh into the node the replica is still there. Should it be auto deleted?

Now you might say: Just use the UI to delete the failed volume. But:
There is a 2nd volume that is on node 1 and 3 but a remnant is also still on node 2. And that is not shown on UI.

![image](https://user-images.githubusercontent.com/229382/147401188-92c1c056-2ba6-4880-9fd8-ec0232f50eb8.png)

![image](https://user-images.githubusercontent.com/229382/147402057-bd86cbd4-46d3-4e05-83f6-3e20e59b61b1.png)

![image](https://user-images.githubusercontent.com/229382/147401211-63892cec-6610-48de-8d33-d78cfe2ed482.png)

IMO this is a bug.

**The other question is:** How do I delete both replica sets on node 2? One can be deleted by UI - and the other?

## To Reproduce

see above

## Expected behavior

Old replica should be deleted to save disk space.

## Log or Support bundle

see my comment

## Environment

 - Longhorn version: 1.2.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubeadm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 1.23.1 with containerd 1.4.12
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version: Debian GNU/Linux 11 (bullseye)   5.10.0-10-amd64
   - CPU per node: 2
   - Memory per node: 2 GB
   - Disk type(e.g. SSD/NVMe): NVMe
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal / Hetzner Cloud
 - Number of Longhorn volumes in the cluster: 2

**Comment by PhilipMay** [comment]
Support bundle:
[longhorn-support-bundle_d7362504-3ef6-4991-94be-a618c85a7dd9_2021-12-26T06-33-19Z.zip](https://github.com/longhorn/longhorn/files/7776625/longhorn-support-bundle_d7362504-3ef6-4991-94be-a618c85a7dd9_2021-12-26T06-33-19Z.zip)

**Comment by PhilipMay** [comment]
More info

![image](https://user-images.githubusercontent.com/229382/147401860-ff981643-162d-4c64-947b-59e69e859719.png)

**Comment by PhilipMay** [comment]
Longhorn seems to know that there still is one volume on node 2 but somehow forgot about the other (see "ls" command above).

**Comment by jenting** [comment]
No, there is a feature request issue #685 for this. If the node ever went offline for a long time, the replica data would not be clean up.
Currently, the only way is to manually delete it and we'll enhance it in the future.

**Comment by PhilipMay** [comment]
Ok. Great! @jenting should I close this and / or link it from #685?

**Comment by jenting** [comment]
If possible, please help close this issue, and this issue is already link to #685, thank you.

**Comment by PhilipMay** [comment]
Ok. Closing.
