### ISSUE TITLE
driver: upgrade CSI version to v1.1.0

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#347]
To follow Kubernetes's v1.13 release.

**Comment by yasker** [comment]
Kubernetes v1.13 and CSI v1.0 broke the backward compatibility, again.

Kubernetes v1.12 and less are still using e.g. service csi.v0, though there is no v0 endpoint available in the CSI v1.0 package. And Kubernetes v1.13+ cannot use csi.v0.

Seems we don't have a choice but use separate code bases for two now.

Maybe from v0.4.0+, we only support Kubernetes v1.13+. In the meantime, continuing maintaining 0.3.x for Kubernetes v1.12 and below.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Test volume created by kubernetes on the old longhorn works on new longhorn, also you can create and use new volumes by kubernetes in new longhorn.
