### ISSUE TITLE
[BUG] Recurring backup not work on detached volume (master-head)

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#3470]
## Describe the bug

Recurring backup not work on detached volume (longhorn-manager master-head)

This issue reflected in e2e daily build and can be reproduced manually

https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/532/testReport/junit/tests/test_recurring_job/

## To Reproduce

1. Enable **Allow Recurring Job While Volume Is Detached** from UI
2. Setup backupstore
3. Create Volume, attach to node, write data into the volume
4. Detach the volume
5. Create recurring backup job in default group (scheduled every minute)
6. Wait for a moment, and there are none backup generated.

## Expected behavior

Backup should generated by recurring schedule in detached volume

## Environment

 - Longhorn version: longhorn-manager master-head
 - Installation method : kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.22.5
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure : VMware (multipass)
 - Number of Longhorn volumes in the cluster: 1

## Additional context

Recurring backup job in detached volume worked fine in Longhorn v1.2.3

**Comment by c3y1huang** [comment]
Seems to be side effects from https://github.com/c3y1huang/longhorn-manager/commit/01efa0ab9e12edbe9ea4f84df1186a6c3d9beadf
```
time="2022-02-18T04:14:00Z" level=error msg="failed to run job for volume" concurrent=1 error="cannot do auto attaching for volume t1: Failed to parse: {\"actions\":{},\"buildDate\":\"2021-12-29T18:48:19+00:00\",\"cliAPIMinVersion\":3,\"cliAPIVersion\":5,\"conditions\":[{\"lastProbeTime\":\"\",\"lastTransitionTime\":\"2022-02-16T15:33:36Z\",\"message\":\"Engine image ei-b907910b (longhornio/longhorn-engine:master-head) is fully deployed on all ready nodes\",\"reason\":\"\",\"status\":\"True\",\"type\":\"ready\"}],\"controllerAPIMinVersion\":3,\"controllerAPIVersion\":3,\"dataFormatMinVersion\":1,\"dataFormatVersion\":1,\"default\":true,\"gitCommit\":\"051ebde20b02cdeb11ff49588f5bf8e7d527c7eb\",\"id\":\"ei-b907910b\",\"image\":\"longhornio/longhorn-engine:master-head\",\"links\":{\"self\":\"http://longhorn-backend:9500/v1/engineimages/ei-b907910b\"},\"name\":\"ei-b907910b\",\"noRefSince\":\"\",\"nodeDeploymentMap\":{\"ip-172-30-0-131\":true,\"ip-172-30-0-140\":true,\"ip-172-30-0-98\":true},\"ownerID\":\"ip-172-30-0-131\",\"refCount\":1,\"state\":\"deployed\",\"type\":\"engineImage\",\"version\":\"051ebde\"}\n: json: cannot unmarshal array into Go struct field EngineImage.conditions of type map[string]interface {}" groups=default job=c-bp6bh0 labels="{\"RecurringJob\":\"c-bp6bh0\"}" retain=1 task=backup volume=t1

```

**Comment by innobead** [comment]
ref: #2955

**Comment by khushboo-rancher** [comment]
Validated on master-head `03/09/2022`

Validation - **Pass**

When the setting `Allow Recurring Job While Volume Is Detached` is enabled, Longhorn is able to take backups for the detached volumes. Tested with RWO and RWX volumes.

**Comment by khushboo-rancher** [comment]
Waiting for the nightly test result on master-head

**Comment by cchien816** [comment]
Verify on master-head 2022/03/23 fail, double verified on v1.2.4 was pass

Steps
1. Enable **Allow Recurring Job While Volume Is Detached** in setting page
2. Set up backupstore
3. Create volume with 1 Gi
4. Create recurring job each minute with group default
5. Observe backup page
6. In master head, no backup generated

Expect result
Backup generated like behavior in v.1.2.4

cc @c3y1huang , @kaxing

**Comment by cchien816** [comment]
**Validate Pass with master head 03/25 (eecabc0)**

Will close this ticket , thanks

cc @c3y1huang , @kaxing 

--
Hi @c3y1huang , 

Using fresh LH install , recurring job with detached volume working well. 
Not sure why the commit id at UI bottom are different between reused environment and fresh install
Previous fail result was environment issue, thank you
