### ISSUE TITLE
[QUESTION] replaced LH disk with empty on one node. It now sits in Unschedulable instead of recovering

### ISSUE THREAD

**Issue by martiinezz** [longhorn/longhorn#3477]
## Environment

 - Longhorn version: 1.2.2
 - Kubernetes version: 1.21.7
 - Node config
   - OS type and version CentOS 8
   - CPU per node: 12
   - Memory per node:  16GB
   - Disk type datastore
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMware

Is there a way to recreate longhorn-disk.cfg? My problem is that I have 3 node LH cluster - I wanted to expand LH dedicated disk on the worker but no space was awailable on the datastore. I decided to take worker down - remove LH dedicated disk and add new from different DS. Started worker with empty bigger drive and it stits as Unschedulable all the time since.
I don't see any rebuild kicking in. What's your proposal (procedure) to fix this? I was expecting this to happen automaticaly - like new diskUUID would be created and replicas copied from existing 2 nodes here.

Regards,
Martin

**Comment by jenting** [comment]
The `Unschedulable` means the Kubernetes node status _or_ the Longhorn node (`kubectl get nodes.longhorn.io -n longhorn-system`) status _or_ the Longhorn GUI reports status?

Could you please provide us with more information on this one like the screenshot _or_ the support bundle (send to longhorn-support-bundle@suse.com)?

**Comment by martiinezz** [comment]
I cannot provide any details now as I made volumes backup next day after asking this question- reinstalled longhorn and restored volumes from backup.
