### ISSUE TITLE
[BACKPORT-1.1.4][BUG] helm upgrade won't apply customize default setting

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#3487]
Backport #2570

**Comment by jenting** [comment]
Because Longhorn v1.1.x uses `longhorn.io/v1beta1` version.
It's impossible to change from ConfigMap to Setting CR directly because the `helm upgrade` would fail. Ref to https://github.com/longhorn/longhorn/issues/2570#issuecomment-981370847

The current way to achieve this is after `longhorn.io/v1beta2` is introduced/launched, we're able to change from ConfigMap to Setting CR.

Therefore, we can't address this issue at v1.1.x versions, close this issue.

**Comment by innobead** [comment]
The issue has been only fixed after 1.3.0 and backported to 1.2.5 already. #2570
