### ISSUE TITLE
[BACKPORT-1.2.x][BUG] helm upgrade won't apply customize default setting

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#3488]
Backport #2570

**Comment by jenting** [comment]
Because Longhorn v1.2.x uses `longhorn.io/v1beta1` version.
It's impossible to change from ConfigMap to Setting CR directly because the `helm upgrade` would fail. Ref to https://github.com/longhorn/longhorn/issues/2570#issuecomment-981370847

The current way to achieve this is after `longhorn.io/v1beta2` is introduced/launched, we're able to change from ConfigMap to Setting CR.

Therefore, we can't address this issue at v1.2.x versions, close this issue.

**Comment by derekbit** [comment]
Let us reopen this backport because the configmap design is doable in 1.2.x.

**Comment by cchien816** [comment]
Hi @derekbit 
I tested on longhorn v1.2.x head `0ed376c4cc3765f64e77cfad7f41f8a28d7baeca`, follow test step [here](https://github.com/longhorn/longhorn/issues/2570#issuecomment-1126938163)

1. Create customized-default-settings.yaml
2. Install Longhorn v1.2.x head with customized-default-settings.yaml
3. check default settings 
But the default setting not applied, could you have look on this? thank you.

**Comment by derekbit** [comment]
> v1.2.x head

Weird... workable in my env. I used the tag `tag: v1.2.x-head`.

**Comment by cchien816** [comment]
**Verified on v1.2.x-head `0ed376c4cc3765f64e77cfad7f41f8a28d7baeca`
Test [steps](https://github.com/longhorn/longhorn/issues/2570#issuecomment-1126938163)
Result Pass**

Test 1. Fresh installation v1.2.x
Check default setting value working properly at each step

- [ ]  Install Longhorn with customized-default-settings.yaml
- [ ]  Update default settings using kubectl
- [ ]  Upgrade longhorn-manager(different tag) without a new customized-default-settings.yaml
- [ ]  Upgrade longhorn-manager(different tag) with a new customized-default-settings.yaml
- [ ]  Delete longhorn-manager and wait for restart.
- [ ]  Update default settings using new-customized-default-settings2.yaml, new-customized-default-settings3.yaml

Test 2.1 Upgrade from v1.1.x to v1.2.x-head and without a new customized-default-settings.yaml
- [ ] Check default setting value working properly at each step
- [ ] Install Longhorn v1.1.x with customized-default-settings.yaml
- [ ]  Upgrade to v1.2.x-head
- [ ]  Upgrade longhorn-manager(different tag) without a new customized-default-settings.yaml
- [ ]  Upgrade longhorn-manager(different tag) with a new customized-default-settings.yaml
- [ ]  Delete longhorn-manager and wait for restart.
- [ ]  Update default settings using new-customized-default-settings2.yaml, new-customized-default-settings3.yaml

Test 3 Upgrade from v1.1.x to v1.2.x-head and with a new customized-default-settings.yaml
Check default setting value working properly at each step

- [ ]  Install Longhorn v1.1.x with customized-default-settings.yaml
- [ ]  Upgrade to v1.2.x-head
- [ ]  Update default settings using kubectl
- [ ]  Delete longhorn-manager and wait for restart.
