### ISSUE TITLE
[BUG] Test test_data_locality_basic is failing on master-head

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3492]
## Describe the bug

https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/539/testReport/tests/test_scheduling/test_data_locality_basic/

## To Reproduce

1. Run the test test_data_locality_basic on Master-head

## Expected behavior

The test should succeed on master-head

## Environment

 - Longhorn version: Master-head - `01/03/2021`

**Comment by chanow816** [comment]
Did some test on my local environment, however it's not easy to reproduce fail scenario, will continue track e2e daily test result.

**Comment by cchien816** [comment]
Close this issue 
In recently [build](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/110/testReport/tests/test_scheduling/test_data_locality_basic/), the fail situation was not seen
