### ISSUE TITLE
[BUG] LH does not delete backup files on S3 when backup is deleted

### ISSUE THREAD

**Issue by PhilipMay** [longhorn/longhorn#3503]
## Describe the bug

I use LH UI to create a backup of a volume.
In my concrete case to new and empty Backblaze bucket using the S3 interface.
Then I wait until the backup arrives at Backblaze and that I see the LH files in the GUI of Backblaze (S3).
Then I delete the backup in the LH UI.
_EDIT: Clarification: I am talking about the backup and NOT about the backup job here. I delete the backup with the "pulldown button" and then "Delete all Backups"._
After 30 min. the files are still available at S3 (Backblaze).

The files should be deleted at Backblaze (S3).
They should be deleted (on S3) when you use "Delete all Backups" and when you delete one of many Backups of the same volume.
Deleting them by hand is much to dangerous.

## Environment

 - Longhorn version: 1.2.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: kubeadm
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: none
 - Node config
   - OS type and version: Debian 11.01
   - CPU per node: 8 hyperthreads
   - Memory per node: 32 GB
   - Disk type(e.g. SSD/NVMe): mechanical
   - Network bandwidth between the nodes: none
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 3

**Comment by derekbit** [comment]
Hmm, I think keeping the backup data in the remote backup store after deleting the backup job makes sense, because the backup job may be mistakenly deleted or other unexpected behaviors.

**Comment by PhilipMay** [comment]
> Hmm, I think keeping the backup data in the remote backup store after deleting the backup job makes sense, because the backup job may be mistakenly deleted or other unexpected behaviors.

I am talking about the Backup and NOT about the job. See screenshot:

![image](https://user-images.githubusercontent.com/229382/148262956-237bb7ee-77e2-46ff-8471-36ac96f4ba07.png)

**Comment by jenting** [comment]
Could you please provide the longhorn manager logs?

**Comment by PhilipMay** [comment]
It was because of a misconfiguration of the bucket. I am sorry. Everything works fine!
Closing this.
