### ISSUE TITLE
[BUG] Inconsistent behavior when doing "Restore Latest Backup"

### ISSUE THREAD

**Issue by PhilipMay** [longhorn/longhorn#3504]
## Describe the bug

When I mark a backup and click the blue "Restore Latest Backup" button at the top:
-> A dialog appears where I can not change the name (see (1) below)

When I click the dropdown button behind a backup and click the "Restore Latest Backup" menu entry:
-> A dialog appears where I must enter the name (see (2) below)

This inconsistency is not correct...

(1):
![image](https://user-images.githubusercontent.com/229382/148257066-d7c56894-5e7e-4dfa-a406-4b49f74a3064.png)

(2):
![image](https://user-images.githubusercontent.com/229382/148257130-d2e8c7f6-b079-421a-b25d-178c70cf2c0a.png)

## Environment

 - Longhorn version: 1.2.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: kubeadm
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: none
 - Node config
   - OS type and version: Debian 11.01
   - CPU per node: 8 hyperthreads
   - Memory per node: 32 GB
   - Disk type(e.g. SSD/NVMe): mechanical
   - Network bandwidth between the nodes: none
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 3

**Comment by khushboo-rancher** [comment]
@PhilipMay This is as per design.

1. **Clicking the button on the top** - 
As you can select one or many volumes and click `Restore Latest Backup` button, you can restore multiple volume backups together and changing name is not allowed, all the restored volumes will have the same name as volumes which was backed up.

2. **Clicking `Restore Latest Backup` from the menu** - 
In this case only one backup can be restored and UI allows you to set the name for the restored volume.

**Comment by PhilipMay** [comment]
Ahh ok. That makes sence. Thanks @khushboo-rancher
