### ISSUE TITLE
[IMPROVEMENT] When restoring a backup LH should not have to ask if it is encrypted

### ISSUE THREAD

**Issue by PhilipMay** [longhorn/longhorn#3505]
## Describe the bug

When I restore a backup with LH UI it asks me if the volume is encrypted.
That question should not be asked because LH should know if the PV was encrypted or not.
This info should be stored with the backup meta infos...

See here:
![image](https://user-images.githubusercontent.com/229382/148257622-83c39ec4-04fb-4ee3-9100-da68551a19cd.png)

## Environment

 - Longhorn version: 1.2.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: kubeadm
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: none
 - Node config
   - OS type and version: Debian 11.01
   - CPU per node: 8 hyperthreads
   - Memory per node: 32 GB
   - Disk type(e.g. SSD/NVMe): mechanical
   - Network bandwidth between the nodes: none
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 3

**Comment by khushboo-rancher** [comment]
The UI is not asking about the already backed up volume but asking user if they want to restore volume as `encrypted` or not.

Closing this now, feel free to reopen you have any other doubt.

**Comment by PhilipMay** [comment]
> The UI is not asking about the already backed up volume but asking user if they want to restore volume as `encrypted` or not.

@ khushboo-rancher: When I have an encryped PV, then take a backup and later restore it. Why should I decide to restore it as unencryped? If that even possible? That does not make sense IMO.

> Closing this now, feel free to reopen you have any other doubt.

I can not reopen for some reason. Just comment.

**Comment by PhilipMay** [comment]
>  @khushboo-rancher khushboo-rancher reopened this 1 hour ago 

Thanks.

**Comment by khushboo-rancher** [comment]
If you are restoring an encrypted volume backup as a non-encrypted volume, you need to manually decrypt it and mount. Refer the test cases [here](https://github.com/longhorn/longhorn/issues/1859#issuecomment-900759320) scenario - Test(2/1)

This option is given to user so that they can choose to restore volume as encrypted or non-encrypted volume no matter the backup is encrypted or not.

@PhilipMay Does it answer your question?

**Comment by PhilipMay** [comment]
Yes. Many thanks for the explanation. I understand.
Closing this.
