### ISSUE TITLE
[BUG] RockyLinux/Centos PVC never gets Healthy

### ISSUE THREAD

**Issue by clemenko** [longhorn/longhorn#3507]
## Describe the bug

PVCs never reach healthy stage and cause pods to terminate and retry.

## To Reproduce

1. Deploy K3S on RockyLinux 8 or Centos 8.
2. Yaml install Longhorn from `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml`
3. Deploy PVC/Deployment
4. Watch the churn

## Expected behavior

It should  not churn. The exact same stack works on Ubuntu. I have double checked selinux if off. 

## Log or Support bundle

Not sure where to check other than the `longhorn-manager` pod. This stands out : 
```
time="2022-01-06T16:17:58Z" level=warning msg="pvc-0b3e0e06-32a9-4ef6-aa55-b308539d54cb-r-735b2083: time=\"2022-01-06T16:17:09Z\" level=info msg=\"Opening volume /host/var/lib/longhorn/replicas/pvc-0b3e0e06-32a9-4ef6-aa55-b308539d54cb-8dce51e1, size 104857600/512\""
time="2022-01-06T16:17:58Z" level=warning msg="pvc-0b3e0e06-32a9-4ef6-aa55-b308539d54cb-r-735b2083: time=\"2022-01-06T16:17:57Z\" level=info msg=\"Lost connection from: 10.42.2.6:33060\""
time="2022-01-06T16:18:00Z" level=debug msg="Prepare to delete instance pvc-0b3e0e06-32a9-4ef6-aa55-b308539d54cb-r-735b2083"
```

## Environment

 - Longhorn version: 1.2.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.22.5+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: Centos 8.6 - 4.18.0-240.1.1.el8_3.x86_64
   - CPU per node: 4
   - Memory per node: 8
   - Disk type(e.g. SSD/NVMe): CLOUD
   - Network bandwidth between the nodes: HUGELY
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VM - Digital Ocean
 - Number of Longhorn volumes in the cluster: 3

## Additional context

Odd since this works on Ubuntu.

here is what the GUI is doing.

![longhorn_not_health](https://user-images.githubusercontent.com/3177276/148414855-147013d0-ab94-4e43-9f68-ec4117962237.gif)

**Comment by PhilipMay** [comment]
@clemenko did you install the required packages?

Like open-iscsi and so on? At debian I have to do `apt-get install -y open-iscsi nfs-common` 

see https://longhorn.io/docs/1.2.3/deploy/install/#installation-requirements

**Comment by clemenko** [comment]
Yup `iscsi-initiator-utils.x86_64` is installed on all nodes. 
Even ran the check:
```
clempro:clemenko k3s ( 167.172.229.76:6443:longhorn-system ) $ curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.2.3/scripts/environment_check.sh | bash
daemonset.apps/longhorn-environment-check created
waiting for pods to become ready (0/3)
all pods ready (3/3)

  MountPropagation is enabled!

cleaning up...
daemonset.apps "longhorn-environment-check" deleted
clean up complete
```

**Comment by PhilipMay** [comment]
You have 2 worker nodes. The default number of replicas is 3. This might be the problem. Change the default number of replicas to 2 and try again - I would say.

**Comment by clemenko** [comment]
my master is also a worker. 
like I said this works perfectly on Ubuntu with the same k3s and longhorn versions.

**Comment by PhilipMay** [comment]
Well. Then I cant help. Sorry.
Maybe just use Debian. :-)

**Comment by clemenko** [comment]
Do they logs make sense to anyone?

```
---- instance-manager-e-9b797db9 ----
[pvc-1dcc513e-93e4-4f43-b0c2-a6f11a18b43a-e-9cc9b9a8] time="2022-01-06T18:26:56Z" level=warning msg="FAIL to discover due to Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm -m discovery -t sendtargets -p 10.42.2.5], output , stderr, Failed to connect to bus: No data available\niscsiadm: can not connect to iSCSI daemon (111)!\niscsiadm: Could not scan /sys/class/iscsi_transport.\nFailed to connect to bus: No data available\niscsiadm: can not connect to iSCSI daemon (111)!\niscsiadm: Cannot perform discovery. Initiatorname required.\niscsiadm: Could not perform SendTargets discovery: could not connect to iscsid\n, error exit status 20"
[pvc-1dcc513e-93e4-4f43-b0c2-a6f11a18b43a-e-9cc9b9a8] time="2022-01-06T18:27:01Z" level=warning msg="FAIL to discover due to Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm -m discovery -t sendtargets -p 10.42.2.5], output , stderr, Failed to connect to bus: No data available\niscsiadm: can not connect to iSCSI daemon (111)!\nFailed to connect to bus: No data available\niscsiadm: can not connect to iSCSI daemon (111)!\niscsiadm: Cannot perform discovery. Initiatorname required.\niscsiadm: Could not perform SendTargets discovery: could not connect to iscsid\n, error exit status 20"
```

**Comment by derekbit** [comment]
@clemenko 
Do you start the iSCSI daemon service?
You can try
```
systemctl restart iscsid.service
systemctl enable iscsid.service
```

**Comment by clemenko** [comment]
how did i miss that. Thanks @derekbit

**Comment by pengln** [comment]
in kind. iscsid say: "sendmsg: bug? ctrl_fd 5"
