### ISSUE TITLE
Volume cloning feature is broken due to CRDs schema in master-head 01/06/2022

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3508]
## Describe the bug

Volume cloning is broken due to CRDs schema in master-head 01/06/2022

## To Reproduce

Clone a volume ( [see the instruction](https://longhorn.io/docs/1.2.3/snapshots-and-backups/csi-volume-clone/) ). Observe that the cloning fails.

## Expected behavior

The cloning should success 

## Environment

 - Longhorn version: master-head 01/06/2022

## Additional context
We require the datasource field to be one of the string: `""`, `"backup`, `"snapshot"`, `"volume"`, [link](https://github.com/longhorn/longhorn-manager/blob/fff8e7b3e3bb11e6a795dca0e72009ae67f3cbe2/deploy/install/01-prerequisite/03-crd.yaml#L3398-L3404) . However, the field DataSource should be a string with full information about the source of volume. For example, `snap://vol-name/snapshot-name`

**Comment by PhanLe1010** [comment]
We can avoid this mistake by having e2e test case.

The e2e test case is tracked at https://github.com/longhorn/longhorn/issues/2941 with the test skeleton at https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_cloning.py

**Comment by khushboo-rancher** [comment]
Validated on master-head `01/13/2022`

Validation - **Pass**
Ran the test cases from https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_cloning.py manually.

@PhanLe1010  We will implement the test automation on priority for this. Thanks
