### ISSUE TITLE
[Doc] Update the doc with the info encrypted filesystem does NOT need manual expansion

### ISSUE THREAD

**Issue by PhilipMay** [longhorn/longhorn#3511]
Hi,

in your documentation you say:

> The encrypted filesystem needs manual expansion after regular expansion of the Longhorn block device. [... ]

see here: https://longhorn.io/docs/1.2.3/advanced-resources/volume-encryption/#filesystem-expansion

For me this does not seem to be true.

- I follow this guide to create a StorageClass for Longhorn encryption: https://longhorn.io/docs/1.2.3/advanced-resources/volume-encryption/
- I create a PVC that claims `100Mi` and uses the `longhorn-crypto-global` StorageClass
- I create a deployment to start a pod that connects and mounts the PV/PVC
- after everything is up and running I open a bash in the pod
- I use `dh -h` to check the sizes
- I scale down the deployment: `kubectl scale --replicas=0 [...]`
- I use the LH UI to expand the pv to double size (200Mi)
- I scale up the pod: `kubectl scale --replicas=1 [...]`
- after everything is up and running I open a bash in the pod
- I use `dh -h` to check the sizes
- I see that the size of the encrypted volume did increase without "manual expansion"

**Comment by khushboo-rancher** [comment]
There was an improvement in v1.2.3 to support expansion of encrypted volumes - https://github.com/longhorn/longhorn/issues/2868

We'll update the doc with the correct information.

**Comment by PhanLe1010** [comment]
cc @innobead 
Please add a milestone

**Comment by innobead** [comment]
Let’s put into the planning first and will revisit when planning the following milestones.

**Comment by innobead** [comment]
@khushboo-rancher see if u can help with this.

**Comment by khushboo-rancher** [comment]
https://longhorn.io/docs/1.2.3/advanced-resources/volume-encryption/#filesystem-expansion is updated.

<img width="961" alt="Screen Shot 2022-01-27 at 10 12 55 AM" src="https://user-images.githubusercontent.com/60111667/151418923-30958d26-b82b-4ca4-8e27-965a7d2ebb23.png">

**Comment by joshimoo** [comment]
We should remove the paragraph about the online FS expansion to not confuse the end user, since the underlying block dev still only supports offline expansion, same as in the non encrypted case. The FS can always be online expanded, but the block dev will always require offline expansion.

**Comment by khushboo-rancher** [comment]
Sounds good, I will create a PR to remove it.
Thanks @joshimoo
