### ISSUE TITLE
[IMPROVEMENT] Add network policy for longhorn webhook server

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#3513]
## Is your improvement request related to a feature? Please describe

Add the network policy for the longhorn webhook server for security reasons.

## Describe the solution you'd like

Add the examples and docs for the longhorn webhook server network policy.

## Additional context

Related to
- https://github.com/longhorn/longhorn/issues/3241
- https://github.com/longhorn/longhorn/issues/3265

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with master-head images in following comprehensive scenario:
- Fresh install v1.2.3
- Create volume, recurring job, backup
- Apply network policy examples
- Upgrade to master-head
Longhorn operates as expected with the network policies.
```console
$ kubectl get NetworkPolicy -n longhorn-system         1 ↵ check-kubelet-restart
NAME                        POD-SELECTOR                                      AGE
backing-image-data-source   longhorn.io/component=backing-image-data-source   63m
backing-image-manager       longhorn.io/component=backing-image-manager       63m
instance-manager            longhorn.io/component=instance-manager            63m
longhorn-manager            app=longhorn-manager                              63m
longhorn-ui                 app=longhorn-ui                                   63m
longhorn-webhook            app=longhorn-webhook                              63m
```
Cluster spec: 1 control, 3 worker nodes on local VMs with k3s v1.19
