### ISSUE TITLE
[BUG] Recurring Job delete not working correctly

### ISSUE THREAD

**Issue by PhilipMay** [longhorn/longhorn#3517]
- I open LH GUI
- open volume tab
- click a volume to open the details
- scroll down
- click add job
- click ok
- open recurring job tab
- delete the job there
- go back to volume tab
- open details of the volume again
- scroll down
- and see this:

![image](https://user-images.githubusercontent.com/229382/148642791-4e0e82a3-75a2-47a5-8a0c-e901aca20946.png)

I can delete this "crippled" job now but IMO it is a bug.

PS: The exclamation mark sais "Recurring Job doesn't exist".

## Environment

 - Longhorn version: 1.2.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: kubeadm
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: none
 - Node config
   - OS type and version: Debian 11.01
   - CPU per node: 8 hyperthreads
   - Memory per node: 32 GB
   - Disk type(e.g. SSD/NVMe): mechanical
   - Network bandwidth between the nodes: none
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 3

**Comment by kaxing** [comment]
Hello @PhilipMay can you still see those deleted Recurring Jobs as CRs? with kubectl command:
```
$ kubectl get recurringjobs.longhorn.io -n longhorn-system
NAME       GROUPS        TASK       CRON        RETAIN   CONCURRENCY   AGE   LABELS
c-2lyahm   ["default"]   backup     0 0 * * *   1        1             24s   
c-ei0v3r                 snapshot   0 0 * * *   1        1             30s 
```
And if possible can you describe the resource, for example:
```
$ kubectl describe recurringjobs.longhorn.io/c-2lyahm -n longhorn-system
```
There might be some clues.

**Comment by PhanLe1010** [comment]
This is expected. We don't auto-delete the recurring job from individual volume.

We can add a warning message before deleting a job though. Something like, if there are volumes that are using the job, there should be a warning message notifying the user about this.

**Comment by Martin-Weiss** [comment]
> This is expected. We don't auto-delete the recurring job from individual volume.
> 

Due to this bug we had to realize after some times that volumes have not been backed up anymore! 
Why is this expected?

Basically the use case is: change individual schedules to default schedules and here we create the default one and delete the old one.. so what is the usage of the "old" and "useless label" causing the default job not to be activated and not having a backup anymore?

> We can add a warning message before deleting a job though. Something like, if there are volumes that are using the job, there should be a warning message notifying the user about this.

I believe in case this is not automatic - we should add a option to delete the assignments of the jobs on the volumes automatically when deleting the job.

**Comment by PhanLe1010** [comment]
Thanks @Martin-Weiss for the feedback! If the other job of the volume is affected, it seems like a bug. To be more specific, could you re-summarize the reproducing steps? 

> Basically the use case is: change individual schedules to default schedules and here we create the default one and delete the old one.. so what is the usage of the "old" and "useless label" causing the default job not to be activated and not having a backup anymore?

cc @c3y1huang Could you please take a look at this behavior?

**Comment by Martin-Weiss** [comment]
We ran into the problem with using Longhorn backup schedules pre-"reccuring jobs" feature, then upgraded and then deleted the "old migrated jobs" and created new default jobs..

- install old longhorn version (without the recurring jobs feature) and use the schedules defined on the storage class
- create PVCs and get/use PVs in Longhorn
- see backup and snapshot happening
- do disaster recovery of some volumes (where you geht longhorn-static storage class)
- configure backup for the restored volumes
- upgrade longhorn to 1.2.2
- see the "migrated" jobs with "strange names"
- delete the "jobs with strange names"
- create new default jobs
- now realize that the volumes are not backed up because they have "old and invalid labels" and the default jobs are not used, because there are invalid labels on the volumes

**Comment by c3y1huang** [comment]
@Martin-Weiss, thank you for the feedback. We will look into it.

**Comment by innobead** [comment]
This is impacted by #2955 due to the rancher API client has not been updated for the possible backward compatibility purpose. 

cc @derekbit @jenting

**Comment by innobead** [comment]
@derekbit It seems we need to update https://github.com/longhorn/longhorn-manager/blob/436bda78a955bdaf4bd9a73bc5fd4613f84bcb24/client when the REST API interface updating, but it seems we don't do anything for this condition change for models.

Iff we keep conditions as a condition map for all models used by REST API, we probably need to do `sliceToMap(*node*.Status.Conditions)` for all models. WDYT?

**Comment by jenting** [comment]
I remember we intended not to update the REST API interface to minimize the effort on request longhorn-ui update.

**Comment by innobead** [comment]
> I remember we intended not to update the REST API interface to minimize the effort on request longhorn UI change/update.

Is it possible to cause some extra efforts to maintain the generated code if new resources are introduced?

**Comment by derekbit** [comment]
> > I remember we intended not to update the REST API interface to minimize the effort on request longhorn UI change/update.
> 
> Is it possible to cause some extra efforts to maintain the generated code if new resources are introduced? If yes, probably need to rethink a bit.
> 
> cc @smallteeths



> > I remember we intended not to update the REST API interface to minimize the effort on request longhorn UI change/update.
> 
> Is it possible to cause some extra efforts to maintain the generated code if new resources are introduced? If yes, probably need to rethink a bit.
> 
> cc @smallteeths

Yes. For a new resources introduced, need to implement the conversion if the conditions exist.

**Comment by khushboo-rancher** [comment]
Validated on master-head `03/09/2022`

Validation - **Pass**

When the last recurring job is deleted, the recurring job gets deleted from respective volumes as well. Longhorn shows the following warning message when user tries to delete the recurring job.
<img width="769" alt="Screen Shot 2022-03-09 at 2 53 18 PM" src="https://user-images.githubusercontent.com/60111667/157552616-2bb2556a-5f8c-45f9-b910-cdc9d412782f.png">

@c3y1huang I'm assuming the default group will not be deleted even if I created a recurring job in default group and later delete it. Could you please confirm the behavior?

**Comment by c3y1huang** [comment]
> @c3y1huang I'm assuming the default group will not be deleted even if I created a recurring job in default group and later delete it. Could you please confirm the behavior?

Correct, and this behavior is also included in the automation test  [here](https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_recurring_job.py#L1365-L1371)
