### ISSUE TITLE
[BUG] /usr/local/bin/launch-simple-longhorn: line 57: exec: longhorn-instance-manager: not found

### ISSUE THREAD

**Issue by TobiasDeBruijn** [longhorn/longhorn#3519]
## Describe the bug
When using launch-simple-longhorn to mount a volume for data recovery, it throws an error: `/usr/local/bin/launch-simple-longhorn: line 57: exec: longhorn-instance-manager: not found`, and the volume is not mounted as a block device

## To Reproduce

1. Install containerd
2. Launch the container:
```
ctr run --tty --rm --mount type=bind,src=/dev,dst=/host/dev,options=rbind --mount type=bind,src=/proc,dst=/host/proc,options=rbind --mount type=bind,src=/var/lib/longhorn/replicas/transmission-a3db8c88/,dst=/volume,options=rbind --privileged docker.io/longhornio/longhorn-engine:v1.1.2 longhorn launch-simple-longhorn transmission-a3db8c88 1073741824
```

## Expected behavior
The volume gets mounted a bock device

## Log or Support bundle
N.A.

## Environment

 - Longhorn version: 1.1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubeadm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K8s? 
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 6
 - Node config
   - OS type and version: Ubuntu 20.04 LTS
   - CPU per node: `Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz` (Note that all nodes run on the same physical server and thus share the CPU)
   - Memory per node: 6GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: Unknown, all VMs run on the same physical server
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal
 - Number of Longhorn volumes in the cluster: 6

## Additional context
N/A

**Comment by jenting** [comment]
Duplicate to #2796, please upgrade to v1.1.3.
