### ISSUE TITLE
[IMPROVEMENT] The longhorn manager should wait the longhorn webhook server ready

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#3523]
## Is your improvement request related to a feature? Please describe

The longhorn manager depends on the longhorn webhook server, therefore, we should have a way to let the longhorn manager delay start until the longhorn webhook server becomes available.

## Describe the solution you'd like

We could add `initContainers` in the longhorn manager Deployment to check the longhorn webhook server available _or_ write code inside the longhorn manager to wait for the longhorn webhook server available.

## Additional context

Ref to
- https://github.com/longhorn/longhorn-manager/blob/36b8d3e624d71cce5181c802248761a62d4c5595/deploy/install/02-components/04-driver.yaml#L16-L19
- https://github.com/harvester/harvester/blob/199b3b79e699b09110876590371b0bf282580de3/pkg/controller/admission/wait.go#L21-L45

**Comment by innobead** [comment]
Not sure if we should need this one because even we can make the longhorn-manager runs after the webhook is ready, but it's still possible that the webhook becomes not ready afterward. 

Should we just have a pre-condition to check that the webhook is ready or the longhorn-manager is ready to serve before running e2e test cases? or fail the test cases if the pre-condition fails? maybe this is good enough.

**Comment by jenting** [comment]
> Not sure if we should need this because even we can make the longhorn-manager runs after the webhook is ready, but it's still possible that the webhook becomes not ready afterward.
> 
> Should we just have a pre-condition (readiness check) to check that the webhook is ready or the longhorn-manager is ready to serve resources update before running e2e test cases? or fail the test cases if the pre-condition fails? maybe this is good enough.

The original idea is to minimize the longhorn-manager in the `CrashLoopBackOff` state during the longhorn upgrade from old version v1.1.x/v1.2.x to v1.3.x because during the longhorn manager upgrades path code, it will call the v1beta1 CRs List API and it needs to go through the CRD conversion logic in the longhorn-webhook server.

Once the longhorn-webhook server is not ready to be served, the longhorn-manager will be in `CrashLoopBaackupOff` state until the longhorn-webhook server is ready to be served.

WDYT?

**Comment by innobead** [comment]
Agreed, actually, I just thought about it.

**Comment by jenting** [comment]
An idea, once the longhorn webhook server finish registered the configuration, add an healthy endpoint.
Then, add longhorn manager DaemonSet, add initContainers to check the healthy endpoint HTTP status code is 200.

**Comment by innobead** [comment]
> An idea, once the longhorn webhook server finish registered the configuration, add an healthy endpoint. Then, add longhorn manager DaemonSet, add initContainers to check the healthy endpoint HTTP status code is 200.

discussed

**Comment by kaxing** [comment]
Validation - **PASSED**

Testing with master-head, longhorn-manager deployment will now wait for the webhook workload gets ready, example logs of longhorn-manager pod is waiting:
```
stream logs failed container "wait-longhorn-webhook" in pod "longhorn-manager-ndg6m" is waiting to start: PodInitializing for longhorn-system/longhorn-manager-ndg6m (wait-longhorn-webhook)
stream logs failed container "longhorn-manager" in pod "longhorn-manager-ndg6m" is waiting to 
```
And when the wait is over, user can see this in `wait-longhorn-webhook`:
```
│ Stream closed EOF for longhorn-system/longhorn-manager-5r9xt (wait-longhorn-webhook)                                                                                                                │
```
