### ISSUE TITLE
[TEST] Fix arm64 failed/flaky cases in E2E test cases

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#3527]
## What's the test to develop? Please describe

E2E daily build have some fail/falky cases when runing on arch arm64.
Some cases need modify code
Some might related to https://github.com/longhorn/longhorn/issues/1961

## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] Have consistent test results.

## Additional context

https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/arm64/job/longhorn-tests-ubuntu-arm64/423/#showFailuresLink

**Comment by chanow816** [comment]
### Current status

**PR Reviewing :**

- test_infra.test_offline_node

**Hard to reproduce :**

- test_backing_image.test_backing_image_basic_operation
- test_ha.test_salvage_auto_crash_all_replicas

**Product issue :** https://github.com/longhorn/longhorn/issues/3220

- test_basic.test_allow_volume_creation_with_degraded_availability_restore

**Product issue :** https://github.com/longhorn/longhorn/issues/3470

- test_recurring_job.test_recurring_jobs_allow_detached_volume
- test_recurring_job.test_recurring_jobs_when_volume_detached_unexpectedly

**Enhancement Task :** https://github.com/longhorn/longhorn/issues/1961

- test_backing_image.test_engine_live_upgrade_rollback_with_backing_image
- test_engine_upgrade.test_engine_image_incompatible
- test_engine_upgrade.test_engine_live_upgrade_rollback
- test_backing_image.test_engine_offline_upgrade_with_backing_image
- test_backing_image.test_engine_live_upgrade_with_backing_image
- test_engine_upgrade.test_engine_image
- test_engine_upgrade.test_engine_offline_upgrade
- test_engine_upgrade.test_engine_live_upgrade
- test_engine_upgrade.test_engine_live_upgrade_with_intensive_data_writing

**Fixed :**
None

**Comment by cchien816** [comment]
Close this issue since after resync time reverted all test cases in master branch become stable, if bunch number of failed cases happened will create another one for tracking
