### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by jerryTJ** [longhorn/longhorn#3532]
## Question
> Suggest to use https://github.com/longhorn/longhorn/discussions to ask questions.

## Environment

 - Longhorn version:1.2.3
 - Kubernetes version:1.20.0
 - Node config
   - OS type and version:Red Hat 4.8.5-36
   - CPU per node:4
   - Memory per node:16
   - Disk type:xfs
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
ERROR:
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/5989442/149463872-81d484fb-7982-491b-905b-c3dbae28babe.png">

My Longhorn Env
<img width="487" alt="image" src="https://user-images.githubusercontent.com/5989442/149463915-b5e74d20-461e-4f96-85ca-0dedae712c46.png">
Node1 status of  iscsid
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/5989442/149463923-25b778c1-be1d-483c-ab8a-443c896bb8ed.png">
Node 2 status of iscsid
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/5989442/149464030-add1b9a8-097d-448f-ac2f-af83d3abc013.png">
Node3 of status iscsid
<img width="850" alt="image" src="https://user-images.githubusercontent.com/5989442/149464074-5f225d30-96b0-447f-ae1e-50ace08727cc.png">

Log snippet：
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/5989442/149464315-4796354f-4a2c-45b6-aa7a-afe81a597a4f.png">

**Comment by PhanLe1010** [comment]
Is Longhorn running on the node w432pc04vm49?

Can you do a quick test: Go to Longhorn UI, create a simple ReadWriteOnce volume. Try to  attach the volume to node w432pc04vm49 ?

**Comment by jerryTJ** [comment]
I can attach the volume to node w432pc04vm49 from UI. 
if I need to config lVM plugin for Kubernetes?  
the directory of /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ is empty.

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/5989442/150116669-d8d0f357-e680-48ee-9d85-d31edc6fd235.png">

**Comment by PhanLe1010** [comment]
I dont think LVM plugin is related to Longhorn

**Comment by jerryTJ** [comment]
ok， thanks
