### ISSUE TITLE
[BUG][v1.2.4] longhorn-driver-deployer unable to gain ready state

### ISSUE THREAD

**Issue by kaxing** [longhorn/longhorn#3539]
## Describe the bug

Deploy v1.2.x-head(pre-v1.2.4) from longhorn-manager repo, with following images set:
        - longhornio/longhorn-engine:v1.2.x-head (7c336f9e00cb1b1f372f870cf631d2298ff94731c4870464c4b0f79dcd5acf9c)
        - longhornio/longhorn-instance-manager:v1_20211210
        - longhornio/longhorn-share-manager:v1_20211020
        - longhornio/backing-image-manager:v2_20210820
        - longhornio/longhorn-manager:v1.2.x-head

## To Reproduce

1. Launch a fresh cluster
2. Install v1.2.x-head
3. Watch the status of longhorn-driver-deployer 

## Expected behavior
All longhorn-system workload should be ready

## Log or Support bundle

There are two different error that might happen:

```
longhorn-driver-deployer 2022/01/17 09:59:26 proto: duplicate proto type registered: VersionResponse
longhorn-driver-deployer W0117 09:59:26.137282       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
longhorn-driver-deployer time="2022-01-17T09:59:26Z" level=debug msg="Deploying CSI driver"
longhorn-driver-deployer time="2022-01-17T09:59:26Z" level=fatal msg="Error deploying driver: failed to start CSI driver: the server could not find the requested resource (get settings.longhorn.io taint-toleration)"
Stream closed EOF for longhorn-system/longhorn-driver-deployer-79f57fd669-pnmtt (wait-longhorn-manager)
Stream closed EOF for longhorn-system/longhorn-driver-deployer-79f57fd669-pnmtt (longhorn-driver-deployer)
```

```
longhorn-driver-deployer-79f57fd669-mwhzm 2022/01/17 10:03:23 proto: duplicate proto type registered: VersionResponse
longhorn-driver-deployer-79f57fd669-mwhzm W0117 10:03:23.844780       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
longhorn-driver-deployer-79f57fd669-mwhzm time="2022-01-17T10:03:34Z" level=warning msg="Got an error when checking MountPropagation with node status, Get \"http://longhorn-backend:9500/v1/schemas\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
longhorn-driver-deployer-79f57fd669-mwhzm time="2022-01-17T10:03:34Z" level=fatal msg="Error deploying driver: CSI cannot be deployed because MountPropagation is not set: Get \"http://longhorn-backend:9500/v1/schemas\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
Stream closed EOF for longhorn-system/longhorn-driver-deployer-79f57fd669-mwhzm (longhorn-driver-deployer)
```

[longhorn-support-bundle_3d49e147-1dc9-4e6f-bdfa-cb7c3b549d3b_2022-01-17T10-09-47Z.zip](https://github.com/longhorn/longhorn/files/7880963/longhorn-support-bundle_3d49e147-1dc9-4e6f-bdfa-cb7c3b549d3b_2022-01-17T10-09-47Z.zip)

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: rke2 v1.21.7+rke2r2
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): DO
 - Number of Longhorn volumes in the cluster: n/a

## Additional context
None

**Comment by innobead** [comment]
@kaxing is this the case from the master/1.3.0 as well?

**Comment by kaxing** [comment]
@innobead Only see this with v1.2.x-head image.

**Comment by shuo-wu** [comment]
The image you are using in `longhorn-driver-deployer` is `longhornio/longhorn-manager:master-head`:
```
        containers:
        - name: longhorn-driver-deployer
          image: longhornio/longhorn-manager:master-head
          command:
          - longhorn-manager
          - -d
          - deploy-driver
          - --manager-image
          - longhornio/longhorn-manager:master-head
          - --manager-url
          - http://longhorn-backend:9500/v1
```

**Comment by kaxing** [comment]
Thanks @shuo-wu to check on my configuration.

Re-checking this issue with proper image tags.
It is not happening with v1.2.x-head images. cc @innobead 

Following changes need to be made in image tags in pre-release branch in order to deploy correctly :
```console
longhorn-manager/deploy/install/02-components$ grep "v1.2.x-head" *                                                    v1.2.x
01-manager.yaml:        image: longhornio/longhorn-manager:v1.2.x-head
01-manager.yaml:        - longhornio/longhorn-engine:v1.2.x-head
01-manager.yaml:        - longhornio/longhorn-manager:v1.2.x-head
03-ui.yaml:        image: longhornio/longhorn-ui:v1.2.x-head
04-driver.yaml:          image: longhornio/longhorn-manager:v1.2.x-head
04-driver.yaml:          image: longhornio/longhorn-manager:v1.2.x-head
04-driver.yaml:          - longhornio/longhorn-manager:v1.2.x-head
```
