### ISSUE TITLE
[TASK] Have a pipeline to run periodical benchmark testing for Longhorn performance

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#3540]
## What's the task? Please describe

Usually we will do the benchmark testing of Longhorn performance (IOPS, throughput, latency) manually for each feature release, but we should have a CI pipeline to set up the testbed, run the benchmark, even do further to compare with other solutions (optional).

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [x] Have a pipeline to run the benchmark via kbench to collect different IO patterns and metrics. 
- [x] Run that pipeline on demand 
- [x] Run the pipeline on a specific Longhorn version & K8s distro

## Additional context

N/A

cc @derekbit @joshimoo @longhorn/qa

**Comment by innobead** [comment]
@derekbit Please help provide the info about your manual setup steps or scripts, then @meldafrawi can leverage it. Thank you.

**Comment by derekbit** [comment]
@innobead Only for Longhorn, right?

**Comment by innobead** [comment]
> @innobead Only for Longhorn, right? Need comparisons with other storage solutions?

Yes. Do longhorn first.

**Comment by derekbit** [comment]
The performance measurement is documented. Additionally, the benchmarking took, kbench, is also patched.
https://confluence.suse.com/display/LON/Performance+Investigation+of+Longhorn+and+Ceph
https://github.com/yasker/kbench

**Comment by innobead** [comment]
@yangchiu Can you provide a screenshot in the comment to share what the result looks like after running a benchmark?

**Comment by yangchiu** [comment]
Currently there is no separate report would be generated after the test finished. The results of each benchmark test is printed in console output. To find the test results, you can search "Benchmark Summary" in console output, there would be 4 results, for local-path-provisioner, longhorn with 1, 2, 3 replica(s) respectively:

(1) local-path-provisioner
![051011](https://user-images.githubusercontent.com/5709208/167596290-18bae8f3-a31e-4c16-8c59-348fb048d6b6.png)
(2) longhorn with 1 replica 
![051012](https://user-images.githubusercontent.com/5709208/167596306-a0697921-fa57-4467-b03a-f7cdcdc3326e.png)
(3) longhorn with 2 replicas
![051013](https://user-images.githubusercontent.com/5709208/167596322-2f89524c-a5e5-40fb-a850-43ed83d6a79c.png)
(4) longhorn with 3 replicas
![051014](https://user-images.githubusercontent.com/5709208/167596331-f3588aba-0341-4bb5-a28e-448176c56e6d.png)
