### ISSUE TITLE
[IMPROVEMENT][BACKPORT][v1.2.4] Change the lifecycle management of the instance-manager pods

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3541]
https://github.com/longhorn/longhorn/issues/2650

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with Longhorn v1.2.x-head(pre v1.2.4) and cluster v1.21.9+rke2r1.

More details please refer to this comment: https://github.com/longhorn/longhorn/issues/2650#issuecomment-1035995894
