### ISSUE TITLE
[IMPROVEMENT][BACKPORT][v1.1.4] Change the lifecycle management of the instance-manager pods

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3543]
#2650

**Comment by kaxing** [comment]
Validating in progress.

With rwx example workload and v1.1.x-head image set.

After one of the nodes down more than 5 minutes I am having trouble recovering the rwx deployment, even deleting then deploying the example again.

```
Events:
  Type     Reason                  Age   From                     Message
  ----     ------                  ----  ----                     -------
  Normal   Scheduled               99s   default-scheduler        Successfully assigned default/rwx-test-5d98bd9fff-lwfxt to ip-10-33-0-187
  Normal   SuccessfulAttachVolume  86s   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-7bf1ef9a-e2a2-41a0-b485-afc5409dae97"
  Warning  FailedMount             83s   kubelet                  MountVolume.SetUp failed for volume "pvc-7bf1ef9a-e2a2-41a0-b485-afc5409dae97" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: /bin/systemd-run
Mounting arguments: [--description=Kubernetes transient mount for /var/lib/kubelet/pods/df01670e-26aa-4338-890d-fa8b06601e77/volumes/kubernetes.io~csi/pvc-7bf1ef9a-e2a2-41a0-b485-afc5409dae97/mount --scope -- /bin/mount -t nfs -o vers=4.1,noresvport,soft,intr,timeo=30,retrans=3 10.43.211.0:/pvc-7bf1ef9a-e2a2-41a0-b485-afc5409dae97 /var/lib/kubelet/pods/df01670e-26aa-4338-890d-fa8b06601e77/volumes/kubernetes.io~csi/pvc-7bf1ef9a-e2a2-41a0-b485-afc5409dae97/mount]
Output: Running scope as unit: run-r1d0b241430874ff4a48bc3f933137455.scope
mount: /var/lib/kubelet/pods/df01670e-26aa-4338-890d-fa8b06601e77/volumes/kubernetes.io~csi/pvc-7bf1ef9a-e2a2-41a0-b485-afc5409dae97/mount: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
  Warning  FailedMount  83s  kubelet  MountVolume.SetUp failed for volume "pvc-7bf1ef9a-e2a2-41a0-b485-afc5409dae97" : rpc error: code = Internal desc = mount failed: exit status 32
```

**Comment by shuo-wu** [comment]
Sure. And is there a separate ticket that tracks this kind of share manager issue?

**Comment by kaxing** [comment]
@shuo-wu the share-manager issue had been opened in here: https://github.com/longhorn/longhorn/issues/3612

For the problem I was looking at in this issue, [in previous comment](https://github.com/longhorn/longhorn/issues/3543#issuecomment-1046539060). it can be resolved by deploy the _longhorn-nfs-installation_, I am now entirely sure why nfs common need to be reinstall and it actually works when the workload first deploy.

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested the node reboot, node disconnected scenario on v1.1.x-head(pre v1.1.4), v1.21.9+rke2r1.
Volumes will stay attached and instance-manager will only be recreating when the nodes are down or disconnect over 5mins.

More details please refer to this comment: https://github.com/longhorn/longhorn/issues/2650#issuecomment-1035995894
