### ISSUE TITLE
[IMPROVEMENT] Implement gRPC proxy in IM to replace MGR engine binary invocation

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#3546]
## Is your improvement request related to a feature? Please describe

This is part of [Improve communication between components (GRPC)](https://github.com/longhorn/longhorn/issues/2821) and also groundwork for [Storage network support](https://github.com/longhorn/longhorn/issues/2285).

## Describe the solution you'd like

Add gRPC proxy in Longhorn Instance manager to replace Longhorn manager engine binary calls.

## Describe alternatives you've considered

- Keeping direct gRPC connection between Longhorn Manager and processes. Discussed in https://github.com/longhorn/longhorn/pull/3277#issuecomment-1006494055.

## Additional context

`None`

**Comment by innobead** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Main-Board-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/3546?planning-poker) with ZenHub @c3y1huang @shuo-wu

**Comment by c3y1huang** [comment]
This is dependent on the mTLS engine refactoring. Backlog this first.
