### ISSUE TITLE
[BUG] Create backup button is grayed out

### ISSUE THREAD

**Issue by baptistexaxa** [longhorn/longhorn#3547]
## Describe the bug

When creating a volume (with web ui, or with yaml manifest) i can see it on web ui, i can  take snapshot, i can run recuring backup job (recuring backup are working fine) but the button to take backup via webui is grayed out. 
I have to program each backup, i can't take one quicky by simply clock on take backup ( mouse pointer change to "forbidden" when it run over the button.

## To Reproduce

Create any volumes, go to web ui section volume, select any volume, drag the mouse over "take backup button," . Button stay gray, mouse pointer change to "forbidden".

## Expected behavior

Take backup button not beeing grayed out, take a backup when clicking on "take backup button"

## Log or Support bundle

There is no log as click is impossible, so ... no action

## Environment

 - Longhorn version: 1.2.3
 - Installation method: Kubectl:
 - Kubernetes distro and version: v1.20.6
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 10
 - Node config
   - OS type and version: centos7
   - CPU per node: 12
   - Memory per node: 64
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 10GBs
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Openstack
 - Number of Longhorn volumes in the cluster: 2

**Comment by chanow816** [comment]
Hello @baptistexaxa ,

Just want to confirm, did the volume attached to any node when you want to click create backup button?

**Comment by baptistexaxa** [comment]
hello @chanow816 

I have tried:
- a volume attached to a node used by a pod
- a volume detached 
- a volume attached in maintenance mode
- a volume attached to a node not used by a pod (a simple volume i create with web ui)
- a volume attached in maintenance mode to a node not used by a pod (a simple volume i create with web ui)

Same résult. The button "take backup" is grayed out and the mouse pointer change to "forbiden" if y try to click.

**Comment by chanow816** [comment]
Hello @baptistexaxa,

May I know which kind of backup store you are using? (nfs or s3)
Also, when mouse moved on create backup button, did UI show any tool tip message? thank you.

**Comment by jenting** [comment]
Make sure the backup target setting is correct.
Or you could check clicks Backup page, to see if the UI indicates any tips on it or not.

**Comment by baptistexaxa** [comment]
Backup target is OK.

When i program back with "job" (every 5 minutes for exemple), it work. I can see them appear on my S3 Bucket (and i can restore them)

i don't understant : "check clicks Backup page"

**Comment by PhanLe1010** [comment]
@baptistexaxa 

Can you open the browser console to see if there is any issue with the connection from Longhorn UI to Longhorn backend? It seems like some socket problem to me

**Comment by baptistexaxa** [comment]
I cant't see any errors on the console.

![image](https://user-images.githubusercontent.com/86730401/150074851-920b3a26-01a0-4717-8ca1-f334cd4e396a.png)

It's like if the "backup button" was "desactivated".

**Comment by innobead** [comment]
@smallteeths do you know what conditions control the button enablement?

**Comment by smallteeths** [comment]
There are many possible reasons why a backup may not be available.

1. volume.actions.snapshotCreate has a link
2. volume.standby is true or not
3. whether the volume isRestoring()
4. whether volume is upgradingEngine() 
5. whether backupTargetAvailable is available

cc @innobead 

@baptistexaxa Can you provide the data returned by the current volume?

**Comment by smallteeths** [comment]
What is the version of the ui image you are using. Is it v1.2.3 ? If you are using the head image of ui, please try replacing it with this image `wangsiye/longhorn-ui:7b271f3` @baptistexaxa  thanks

**Comment by baptistexaxa** [comment]
I'm going to check all this

**Comment by baptistexaxa** [comment]
@smallteeths 

can you tell me what you mean by "provide the data returned by the current volume"

**Comment by smallteeths** [comment]
<img width="1036" alt="截屏2022-01-19 下午5 20 36" src="https://user-images.githubusercontent.com/27733391/150101214-03cc8226-f4e7-4180-bc43-3ac854a76d59.png">

Can you copy the data returned by the volume api and paste it into the comment? @baptistexaxa thanks

**Comment by baptistexaxa** [comment]
the request is 

http://longhorn.caas-cnp-apps-lab.com.intraorange/v1/volumes?

returning 404.

but request  http://longhorn.caas-cnp-apps-lab.com.intraorange/v1/volumes  (without "?" at the end is returning )

```
{
"createTypes": {
"volume": "…/v1/volumes",
},
"data": [
{
"accessMode": "rwo",
"actions": {
"activate": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=activate",
"attach": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=attach",
"cancelExpansion": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=cancelExpansion",
"detach": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=detach",
"engineUpgrade": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=engineUpgrade",
"pvCreate": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=pvCreate",
"pvcCreate": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=pvcCreate",
"recurringJobAdd": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=recurringJobAdd",
"recurringJobDelete": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=recurringJobDelete",
"recurringJobList": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=recurringJobList",
"replicaRemove": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=replicaRemove",
"snapshotBackup": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=snapshotBackup",
"snapshotCreate": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=snapshotCreate",
"snapshotDelete": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=snapshotDelete",
"snapshotGet": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=snapshotGet",
"snapshotList": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=snapshotList",
"snapshotPurge": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=snapshotPurge",
"snapshotRevert": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=snapshotRevert",
"updateDataLocality": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=updateDataLocality",
"updateReplicaAutoBalance": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=updateReplicaAutoBalance",
"updateReplicaCount": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745?action=updateReplicaCount",
},
"backingImage": "",
"backupStatus": [ ],
"cloneStatus": {
"snapshot": "",
"sourceVolume": "",
"state": "",
},
"conditions": {
"restore": {
"lastProbeTime": "",
"lastTransitionTime": "2022-01-18T15:12:32Z",
"message": "",
"reason": "",
"status": "False",
"type": "restore",
},
"scheduled": {
"lastProbeTime": "",
"lastTransitionTime": "2022-01-18T15:12:32Z",
"message": "",
"reason": "",
"status": "True",
"type": "scheduled",
},
"toomanysnapshots": {
"lastProbeTime": "",
"lastTransitionTime": "2022-01-18T15:12:32Z",
"message": "",
"reason": "",
"status": "False",
"type": "toomanysnapshots",
},
},
"controllers": [
{
"actualSize": "51027968",
"address": "172.12.114.136",
"currentImage": "longhornio/longhorn-engine:v1.2.3",
"endpoint": "/dev/longhorn/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745",
"engineImage": "longhornio/longhorn-engine:v1.2.3",
"hostId": "klabnodeaz0b05",
"instanceManagerName": "instance-manager-e-abd3e8fd",
"isExpanding": false,
"lastExpansionError": "",
"lastExpansionFailedAt": "",
"lastRestoredBackup": "",
"name": "pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745-e-f41f3985",
"requestedBackupRestore": "",
"running": true,
"size": "1073741824",
},
],
"created": "2022-01-18 15:12:32 +0000 UTC",
"currentImage": "longhornio/longhorn-engine:v1.2.3",
"dataLocality": "disabled",
"dataSource": "",
"disableFrontend": false,
"diskSelector": null,
"encrypted": false,
"engineImage": "longhornio/longhorn-engine:v1.2.3",
"fromBackup": "",
"frontend": "blockdev",
"id": "pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745",
"kubernetesStatus": {
"lastPVCRefAt": "",
"lastPodRefAt": "",
"namespace": "taas-tech-auth",
"pvName": "pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745",
"pvStatus": "Bound",
"pvcName": "py-devops-store-adapter-data-claim",
"workloadsStatus": [
{
"podName": "py-devops-store-adapter-984898898-qwpkn",
"podStatus": "Running",
"workloadName": "py-devops-store-adapter-984898898",
"workloadType": "ReplicaSet",
},
],
},
"lastAttachedBy": "",
"lastBackup": "",
"lastBackupAt": "",
"links": {
"self": "…/v1/volumes/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745",
},
"migratable": false,
"name": "pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745",
"nodeSelector": null,
"numberOfReplicas": 1,
"purgeStatus": [
{
"actions": null,
"error": "",
"isPurging": false,
"links": null,
"progress": 0,
"replica": "pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745-r-64337fde",
"state": "",
},
],
"ready": true,
"rebuildStatus": [ ],
"recurringJobSelector": null,
"replicaAutoBalance": "ignored",
"replicas": [
{
"address": "172.12.88.20",
"currentImage": "longhornio/longhorn-engine:v1.2.3",
"dataPath": "/var/lib/longhorn/replicas/pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745-b47000ad",
"diskID": "2854f539-e304-4468-a935-58da3c4f6891",
"diskPath": "/var/lib/longhorn",
"engineImage": "longhornio/longhorn-engine:v1.2.3",
"failedAt": "",
"hostId": "klabnodelhaz0b01",
"instanceManagerName": "instance-manager-r-359c858f",
"mode": "RW",
"name": "pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745-r-64337fde",
"running": true,
},
],
"restoreRequired": false,
"restoreStatus": [
{
"actions": null,
"backupURL": "",
"error": "",
"filename": "",
"isRestoring": false,
"lastRestored": "",
"links": null,
"progress": 0,
"replica": "pvc-b8dfa6c4-da61-4a0b-9dae-d15d0eb8f745-r-64337fde",
"state": "",
},
],
"revisionCounterDisabled": false,
"robustness": "healthy",
"shareEndpoint": "",
"shareState": "",
"size": "1073741824",
"staleReplicaTimeout": 2880,
"standby": false,
"state": "attached",
"type": "volume",
},
],
"links": {
"self": "…/v1/volumes",
},
"resourceType": "volume",
"type": "collection",
}
```

**Comment by smallteeths** [comment]
The actions link is not returned correctly. What proxy server are you using `ingress or nginx`? longhorn-ui nginx is configured with `proxy_set_header Host $http_host`. The backend returns the action link based on this `Host`.  I now suspect that something is wrong with the ui proxy. Try accessing it directly with NodePort and see if this happens again. @baptistexaxa

**Comment by baptistexaxa** [comment]
I'm checking this

**Comment by baptistexaxa** [comment]
This is it ! 

I try to access UI without proxy and it work.  Now i have to find why my proxy eating headers

**Comment by baptistexaxa** [comment]
There is a squid behind me and my K8s cluster, this is the failure point.

Using squid i lost some header i suppose, 
Going direct path, there is no problem

**Comment by baptistexaxa** [comment]
Problem solved:

longterm  cache policy retention of squid3 was the root cause (Keep cached pages days and days ...) 

Problem is solved.

Thx a lot to everybody !!

/kiss :)

**Comment by baptistexaxa** [comment]
Issue solved
