### ISSUE TITLE
[IMPROVEMENT]  set default non-root user for all longhorn component images 

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#3549]
## Is your improvement request related to a feature? Please describe
Longhorn components Dockerfiles need to comply with best practices. 

we need to define non root user for all Longhorn component images.

## Additional context

Could be implemented with https://github.com/longhorn/longhorn/issues/2939 as combined effort.

**Comment by innobead** [comment]
Because most Longhorn components heavily rely on system resources manipulation w/ root and privileged permission, so adopting non-root containers should be a challenge for Longhorn for now, but we will have a further investigation later. 

ref: https://github.com/kubernetes/kubernetes/issues/92211

**Comment by innobead** [comment]
We need to document what functions we need for root and privileged permission to ensure users better understand Longhorn's design and requirements.

**Comment by jenting** [comment]
> We need to document what functions we need for root and privileged permission to ensure users better understand Longhorn's design and requirements.

Currently, Longhorn uses `Bidirectional` mount propagation, therefore it is allowed only in privileged containers.
Ref to https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation

**Comment by jenting** [comment]
Should I backport the document to all Longhorn versions? @innobead

**Comment by innobead** [comment]
> Should I backport the document to all Longhorn versions? @innobead

The current one is good enough.

**Comment by jenting** [comment]
Doc merged, close it.
