### ISSUE TITLE
[QUESTION] What's the longhorn backup path pattern?

### ISSUE THREAD

**Issue by PatrickHuetter** [longhorn/longhorn#3552]
Hi together,

i have some special backup case. We have external properitary storage engines that provide us a lot of disk space. These storage engines do not provide s3 or nfs support and aren't capable for small files. They are optimized to store single large files.

No problem at all since i created a backup system that works with longhorn.
Currently i'm letting longhorn backup to an internal minio s3. I configured all backup jobs to retain 1 backup of every volume.
Once a time in a week a third party service i created by myself is connecting to this minio s3 and collecting all data in a tar archive and moving this archive to the external properitary storage. This works fine since a year now so that we can use the external storage and disk space.

But there is one thing that might break and that's why i'm writing here. If longhorn is creating a backup of a large volume this might take some more time as previously calculated. In this case it might happen that my third party backup job is starting too early and creating the tar archive and moving it happens while longhorn is creating the backup into the minio s3. That ends in broken backups for the large volumes.

To prevent this i thought about refactoring the backup-system to use the longhorn APIs to obtain all current COMPLETED backups only and creating archives and moving them to the properitary storage. In this case i should have any broken backups anymore. Even if a large backup job takes more time. In this case this backup will be collected in the next backup system job run when it's state will be COMPLETED.

To build this i would like to know wether you could tell me how the backup paths in the s3 storage get build? It might be necessary for me to iterate over the directories and to know what and how i can backup. Maybe the backup state is also written into the s3 filesystem so that i don't need to use the longhorn APIs directly?

I also think about open sourcing this service with k8s-cronjob later on.

Thank you very much and best regards!

**Comment by shuo-wu** [comment]
The Longhorn backup store file structure:
```
<backup store work directory>/backupstore/volumes/
    <2 random characters>/<2 random characters>/<backup volume name>/
        volume.cfg
        backups/
            backup1.cfg
            backup2.cfg
            ......
        blocks/
            <2 random characters>/<2 random characters>/
                <backup data, 2MB block, the name is the checksum>.blk
            <2 random characters>/<2 random characters>/
                <backup data, 2MB block, the name is the checksum>.blk
            ......
```

One example:
```
[root@longhorn-test-nfs backupstore]# find backupstore/
backupstore/
backupstore/volumes
backupstore/volumes/94
backupstore/volumes/94/6b

backupstore/volumes/94/6b/pvc-2bd97565-bd12-42d9-aceb-ad2a6b976f17

backupstore/volumes/94/6b/pvc-2bd97565-bd12-42d9-aceb-ad2a6b976f17/blocks

backupstore/volumes/94/6b/pvc-2bd97565-bd12-42d9-aceb-ad2a6b976f17/blocks/ff
backupstore/volumes/94/6b/pvc-2bd97565-bd12-42d9-aceb-ad2a6b976f17/blocks/ff/b7
backupstore/volumes/94/6b/pvc-2bd97565-bd12-42d9-aceb-ad2a6b976f17/blocks/ff/b7/ffb7bdef0ee3b58d0db01b4c2f558301255273d3ab6974ae113d2b31b1cebfe9.blk

backupstore/volumes/94/6b/pvc-2bd97565-bd12-42d9-aceb-ad2a6b976f17/volume.cfg

backupstore/volumes/94/6b/pvc-2bd97565-bd12-42d9-aceb-ad2a6b976f17/backups
backupstore/volumes/94/6b/pvc-2bd97565-bd12-42d9-aceb-ad2a6b976f17/backups/backup_backup-022c59007dc24bc7.cfg
```

To avoid duplication, Longhorn applies incremental backup for each volume. Therefore, the data files in `blocks` are shared by all backups of this volume. It's trivial/complicated to figure out the blocks for completed backups then collect them.

Checking if the backup is in progress via the files in the backup store is difficult/tricky. Instead, you can verify if there are in-progress backups via `kubectl -n longhorn-system get lhb --selector backup-volume=<Backup Volume Name>`.
