### ISSUE TITLE
[BUG] Should not hard-coded the namespace `longhorn-system` in `longhorn-engine-manager` and `longhorn-replica-manager`

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3556]
We should not hard-coded the namespace `longhorn-system` in `longhorn-engine-manager` and `longhorn-replica-manager`  service https://github.com/longhorn/longhorn/blob/v1.2.3/chart/templates/services.yaml

Longhorn version 1.2.3

Related context https://cloud-native.slack.com/archives/CNVPEL9U3/p1642170345005800

**Comment by innobead** [comment]
duplicated to https://github.com/longhorn/longhorn/issues/3433

**Comment by PhanLe1010** [comment]
Thanks @innobead 
I am sorry about that
