### ISSUE TITLE
[TEST] Have support bundle when e2e test case fail

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#3557]
## What's the test to develop? Please describe

On e2e daily build, have support bundle generated when teat cases failed.
To provide a more convenient way to analyze fail scenario

## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] Have support bundle when e2e test case fail

## Additional context

The support bundle should be kept on Jenkins

**Comment by innobead** [comment]
cc @meldafrawi @khushboo-rancher

**Comment by cchien816** [comment]
Hi @meldafrawi ,

Currently the support bundle will generated in folder `/integration/tests/support_bundle` in longhorn-test pod
Need you help let the support to show on Jenkins results page, thank you.

**Comment by cchien816** [comment]
Close this ticket because duplicated from https://github.com/longhorn/longhorn/issues/3251
