### ISSUE TITLE
[TASK] Enable the nightly run of integration test run for v1.2.x and 1.1.x on Jenkins

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3559]
## What's the task? Please describe

Enable nightly run the integration test on v1.2.x and v1.1.x on jenkins

**Comment by meldafrawi** [comment]
Analysis:
After both of the following PRs are merged, tested:
  - https://github.com/longhorn/longhorn-tests/pull/853 
  - https://github.com/longhorn/infra/pull/76
we will need to backport framework changes to v1.1.x and v1.2.x for consistency.

cc: @khushboo-rancher @innobead

**Comment by meldafrawi** [comment]
Done:
- https://ci.longhorn.io/job/public/job/v1.1.x/
- https://ci.longhorn.io/job/public/job/v1.2.x/
