### ISSUE TITLE
[IMPROVEMENT][BACKPORT][v1.1.4] Loading http requests on demand

### ISSUE THREAD

**Issue by kaxing** [longhorn/longhorn#3560]
#3528

**Comment by innobead** [comment]
@kaxing Please help verify and close this. Thanks.

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with v1.1.x-head image set.

The XHR load time had been improved compared to v1.1.3.

| v1.1.3 | v1.1.x-head (pre v1.1.4) |
| :-: | :-: |
| <img width="398" alt="Screen Shot 2022-02-22 at 9 49 17 PM" src="https://user-images.githubusercontent.com/602540/155145449-34aeafd1-fe19-4576-baf2-749118f4b8b5.png"> | <img width="398" alt="Screen Shot 2022-02-22 at 9 49 23 PM" src="https://user-images.githubusercontent.com/602540/155145490-14732dfb-1dc2-46be-8495-802300533f59.png"> |

More detail please refer to this comment: https://github.com/longhorn/longhorn/issues/3528#issuecomment-1018309566
