### ISSUE TITLE
[IMPROVEMENT][BACKPORT][v1.2.4] Loading http requests on demand

### ISSUE THREAD

**Issue by kaxing** [longhorn/longhorn#3561]
#3528

**Comment by innobead** [comment]
@kaxing Please help verify and close this. Thanks.

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with v1.2.x-head image set.

The XHR load time had been improved compared to v1.2.3.

| v1.2.3 | v1.2.x-head (pre v1.2.4) |
| :-: | :-: |
| <img width="398" alt="Screen Shot 2022-02-22 at 9 49 28 PM" src="https://user-images.githubusercontent.com/602540/155145568-4ed97214-76a3-4324-88fb-423cac135ffe.png"> | <img width="398" alt="Screen Shot 2022-02-22 at 9 49 32 PM" src="https://user-images.githubusercontent.com/602540/155145597-de8b6456-425b-4852-88d3-ac5c69a5815b.png"> |

More detail please refer to this comment: https://github.com/longhorn/longhorn/issues/3528#issuecomment-1018309566
