### ISSUE TITLE
[FEATURE] Support operations on custom resources directly instead of Longhorn REST APIs only

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#3562]
## Is your feature request related to a problem? Please describe

The feature is to make sure users can do the operations on custom resources directly instead of only working via longhorn manager REST API.

To support editing CRD, we need to revisit longhorn-manger code and move the validation codes to the validating webhook.

## Additional context
https://github.com/longhorn/longhorn/issues/791

**Comment by derekbit** [comment]
The existing validation functions put the validation and mutation logics together. Thus, these validation functions cannot be move the validating webhook directly.

We need to reimplement the resource validation functions in the validating webhook and resource mutation functions in mutating webhook.

**Comment by derekbit** [comment]
I organized the validation and mutation logics in the API paths in https://docs.google.com/document/d/1no7ltt2DXAESPkMa0jtgfAvV39kdFPj9S2sgiQOy_jA/edit.

cc @jenting @innobead

**Comment by innobead** [comment]
cc @shuo-wu

**Comment by derekbit** [comment]
@shuo-wu @jenting @innobead 

For engineimage resources, the `CreateEngineImage` function in the API path gets the resource's `name` by converting from `image`.

For example:
user creates an engineimage via UI by giving the `image` `[longhornio/longhorn-engine:v1.2.2](http://10.20.90.50/#/engineimage/ei-d4c780c6)`, the engineimage's name is got from its checksum `ei-0ddbdfc0`.

Should we mutate the “name” in the mutating webhook by the same way or return an error when the given name does not match the calculated name? If we just mutate it silently, user may get an unexpected name. On the other hand, user does not know the naming rule if the validating function returns an error. WDYT?

**Comment by innobead** [comment]
> @shuo-wu @jenting @innobead
> 
> For engineimage resources, the `CreateEngineImage` function in the API path gets the resource's `name` by converting from `image`.
> 
> For example: user creates an engineimage via UI by giving the `image` `longhornio/longhorn-engine:v1.2.2`, and the engineimage's `name` is got from its checksum `ei-0ddbdfc0`.
> 
> Should we mutate the `name` in the mutating webhook by the same way or return an error when the given name does not match the calculated name? If we just mutate it silently, user may get a resource with an unexpected name. On the other hand, user does not know the naming rule if the validating function returns an error. I prefer the former solution, but we will need a detailed document for the resource operations for users. WDYT?

Because the name is automatically generated by our logic, I think we just need to mutate it directly as the current behavior. It seems we can't do the validation before the mutation, so it should be good enough to have a description for `name` property.

**Comment by shuo-wu** [comment]
Or we can return an error with the correct name mentioned in the error message. I am fine with either.

Besides, we can add one line `name` in UI for the engine image creation. This line is read-only and it will generate the engine image name in time based on the user's input.

**Comment by derekbit** [comment]
@jenting @shuo-wu @innobead 
One quick question
Can user update multiple Volume.Spec fields at the same time? Is there any risk for the volume controller?

**Comment by jenting** [comment]
> Can user update multiple Volume.Spec fields in a Volume CR at the same time?

Yes. I can't think of any risk for now. Any concerns?

**Comment by derekbit** [comment]
Just think about this while designing/implementing volume validation and mutation.

Additionally, I'd also like to make sure if the following design is reasonable.
If user changes the Spec.size to be larger, the validation function will be
```
func (v *volumeValidator) Update(request *admission.Request, oldObj runtime.Object, newObj runtime.Object) error {
	oldVolume := oldObj.(*longhorn.Volume)
	newVolume := newObj.(*longhorn.Volume)

	return v.validateVolumeOnUpdate(oldVolume, newVolume)
}

func (v *volumeValidator) validateVolumeOnUpdate(oldVolume, newVolume *longhorn.Volume) error {
	if newVolume.Spec.Size != oldVolume.Spec.Size {
		if err := v.expand(oldVolume, newVolume); err != nil {
			return err
		}
	}

        ....
}

func (v *volumeValidator) expand(oldVolume, newVolume *longhorn.Volume) error {
	if newVolume.Spec.Size < oldVolume.Spec.Size {
		return fmt.Errorf("cannot shrink volume %v from %v to %v", oldVolume.Name, oldVolume.Spec.Size, newVolume.Spec.Size)
	}

	manager := manager.NewVolumeManager(oldVolume.Status.OwnerID, v.ds)

	if oldVolume.Status.IsStandby {
		return fmt.Errorf("cannot manually expand standby volume %v", oldVolume.Name)
	}

	if _, err := manager.Expand(oldVolume.Name, newVolume.Spec.Size); err != nil {
		return err
	}

	return nil
}
```

Other checks and validation logics will be added into `validateVolumeOnUpdate`.
So, the `validateVolumeOnUpdate` will become
```
func (v *volumeValidator) validateVolumeOnUpdate(oldVolume, newVolume *longhorn.Volume) error {
	if newVolume.Spec.Size != oldVolume.Spec.Size {
		if err := v.expand(oldVolume, newVolume); err != nil {
			return err
		}
	}

        if VolumeActivateConditionIsTrue {
		if err := v.activate(oldVolume, newVolume); err != nil {
			return err
		}
       }

        ....
        ....
        ....

	if err := datastore.CheckVolume(newVolume); err != nil {
		return err
	}

	return nil
}
```

How about it?


Another question is how the user does `cancelExpansion` by updating the CR?

**Comment by derekbit** [comment]
> > Can user update multiple Volume.Spec fields in a Volume CR at the same time?
> 
> Yes. I can't think of any risk for now. Any concerns?

Hey @jenting, just think about this while designing/implementing volume validation and mutation.

Additionally, I'd also like to make sure if the following design is reasonable.
If user changes the Spec.size to be larger, the validation function will be
```
func (v *volumeValidator) Update(request *admission.Request, oldObj runtime.Object, newObj runtime.Object) error {
	oldVolume := oldObj.(*longhorn.Volume)
	newVolume := newObj.(*longhorn.Volume)

	return v.validateVolumeOnUpdate(oldVolume, newVolume)
}

func (v *volumeValidator) validateVolumeOnUpdate(oldVolume, newVolume *longhorn.Volume) error {
	if newVolume.Spec.Size != oldVolume.Spec.Size {
		if err := v.expand(oldVolume, newVolume); err != nil {
			return err
		}
	}

        ....
}

func (v *volumeValidator) expand(oldVolume, newVolume *longhorn.Volume) error {
	if newVolume.Spec.Size < oldVolume.Spec.Size {
		return fmt.Errorf("cannot shrink volume %v from %v to %v", oldVolume.Name, oldVolume.Spec.Size, newVolume.Spec.Size)
	}

	manager := manager.NewVolumeManager(oldVolume.Status.OwnerID, v.ds)

	if oldVolume.Status.IsStandby {
		return fmt.Errorf("cannot manually expand standby volume %v", oldVolume.Name)
	}

	if _, err := manager.Expand(oldVolume.Name, newVolume.Spec.Size); err != nil {
		return err
	}

	return nil
}
```

Other checks and validation logics will be added into `validateVolumeOnUpdate`.
So, the `validateVolumeOnUpdate` will become
```
func (v *volumeValidator) validateVolumeOnUpdate(oldVolume, newVolume *longhorn.Volume) error {
	if newVolume.Spec.Size != oldVolume.Spec.Size {
		if err := v.expand(oldVolume, newVolume); err != nil {
			return err
		}
	}

        if VolumeActivateConditionIsTrue {
		if err := v.activate(oldVolume, newVolume); err != nil {
			return err
		}
       }

        ....
        ....
        ....

	if err := datastore.CheckVolume(newVolume); err != nil {
		return err
	}

	return nil
}
```

How about it?


Another question is how the user does `cancelExpansion` by updating the CR directly? Changing Volume.spec.size to equal Engine.Status.Size seems to have a conflict with the expand operation.

**Comment by derekbit** [comment]
Leaving a note here
A resource is validated by object schema and then by the validating webhook.
Some asserts by error messages in longhorn-tests need modifications.

**Comment by innobead** [comment]
> Leaving a note here A resource was validated by the validation logic in the API call and then the object schema validation. Now, it is validated by object schema validation and then the validating webhook. Thus, some asserts replying on the error messages in longhorn-tests need modifications.

@longhorn/qa ☝️

**Comment by shuo-wu** [comment]
> Another question is how the user does cancelExpansion by updating the CR directly? Changing Volume.spec.size to equal Engine.Status.Size seems to have a conflict with the expand operation.

As long as volume.Spec.Size >= engine.Status.Size, there is no need to fail the validation. In other words, there is no need to consider if the spec modification is for expansion or expansion canceling in the validation webhook. The check input.Size >= volume.Spec.Size is for the specific HTTP API `volumeExpand` only.

**Comment by derekbit** [comment]
> > Another question is how the user does cancelExpansion by updating the CR directly? Changing Volume.spec.size to equal Engine.Status.Size seems to have a conflict with the expand operation.
> 
> As long as volume.Spec.Size >= engine.Status.Size, there is no need to fail the validation. In other words, the validation webhook does not need to consider if the spec modification is for expansion or expansion canceling. The check input.Size >= volume.Spec.Size is for the specific HTTP API `volumeExpand` only.

@shuo-wu  IIUC. You mean that most of checks should be still in the HTTP API functions. The validation webhook validate the general conditions, right?

On the other hand, should user check by himself if he'd like to do `expand`, `canccleExpand` and so on by editing the resources?

**Comment by innobead** [comment]
As discussed, the REST APIs are not possibly 1:1 mapping to things handled in admission webhooks especially different resources manipulation involved because the spec validation is not really compared with behavior validation, but instead we should focus on the single resource operation w/ validation and mutation, and it will be good enough.

**Comment by derekbit** [comment]
### Volume resources
#### Actions having cascaded resources update 

Action                 |  Resource Update    
---------------- | ---------------------------------------------------------
Salvage               | UpdateVolume -> UpdateReplica
VolumeExpand   | UpdatePersistentVolumeClaim -> UpdateVolume
PVCCreate          | UpdatePersistentVolume-> CreatePersistentVolumeClaim

#### Spec or Status Conflicts between Actions
Conflicts                                    |  Conflicts
------------------------------| ---------------------------------------------------------
v.Status.IsStandby                    | `Activate` needs `v.Status.IsStandby == true`, but `Activate`, `Detach` and `CancelExpansion` need `v.Status.IsStandby == false`
 v.Status.ExpansionRequired   | `CancelExpansion` needs `v.Status.ExpansionRequired==true`.
v.Spec.MigrationNodeID    | `EngineUpgrade` and `UpdateReplicaCount` need empty string

#### The validation in the actions can be moved to the validating webhook

Action                                                | Validation
---------------------------------- | ---------------------------------------
VolumeUpdateDataLocality              | types.ValidateDataLocality
VolumeUpdateAccessMode             | types.ValidateAccessMode
VolumeUpdateReplicaCount            | types.ValidateReplicaCount
VolumeUpdateReplicaAutoBalance | types.ValidateReplicaAutoBalance


#### After checking the actions and validations, there are some findings
1. Some actions have cascaded operations of multiple resources.
2. Some actions have conflict `status` and `spec` checks.
3. Checks of updating a resources, e.g. `Replicas`,  in the HTTP API call and controllers are different.
4. Unlike the specific checks in a HTTP API call, the mutating and the validating webhooks cannot know the action (purpose) of the resource update, so specific and correct checks are infeasible.

According to above findings, the general validations such as `types.ValidateDataLocality`, and mutations such as size = `util.RoundUpSize(size)` are suitable in the admission webhook, but the specific checks of actions still need to stay in the API call.

**Comment by khushboo-rancher** [comment]
From validation point of view, we need to validate each and every action available on Longhorn GUI plus the setting modifications carefully.
cc: @longhorn/qa

**Comment by kaxing** [comment]
Validation - **PASSED**

No unusual problem found with coretest on master-head and manual UI walkthrough.
And this change should be covered in the next cycle of release test.

<sup>// Node spec using for this test: v1.21.10+rke2r2 nodes (all-role) * 3</sup>
