### ISSUE TITLE
[IMPROVEMENT] longhorn backup alerts

### ISSUE THREAD

**Issue by ElZakariyae** [longhorn/longhorn#3564]
Hello,

We are having more and more Kubernetes clusters using longhorn as a storage and it becomes difficult to go into each cluster and check whether the backups are done properly, therefore i'm writing to you guys to ask if we can have some alerts as email notifications or so about the status of the backups for each volume within a cluster.

Thanks.

**Comment by innobead** [comment]
@jenting @PhanLe1010 do we have metrics for backup?

**Comment by jenting** [comment]
> @jenting @PhanLe1010 do we have metrics for backup?

No, but we have the same issue for backup metrics if I remember correctly.

**Comment by jenting** [comment]
Also, we have an community user provided the prometheus configuration on how to monitor the backup and send alerts.

**Comment by PhanLe1010** [comment]
> Also, we have an community user provided the prometheus configuration on how to monitor the backup and send alerts.
@jenting Can you link it here? 

We don't have prometheous metric for backup yet. But with the newly introduced backup CR, I think it is possible

**Comment by jenting** [comment]
> We don't have prometheous metric for backup yet. But with the newly introduced backup CR, I think it is possible

Related issue #2940
