### ISSUE TITLE
[FEATURE] longhorn backup alerts

### ISSUE THREAD

**Issue by ElZakariyae** [longhorn/longhorn#3565]
Hello,

We are having more and more Kubernetes clusters using longhorn as a storage and it becomes difficult to go into each cluster and check whether the backups are done properly, therefore i'm writing to you guys to ask if we can have some alerts as email notifications or so about the status of the backups for each volume within a cluster.

Thanks.

**Comment by joshimoo** [comment]
I feel like the the monitoring & alerting (email, etc) might be out of scope of longhorn. 
Then a simple cron/batch or prometheus service is all that would be needed and could be shared by the community.

What we can improve on though is make it easier to retrieve the status of a backup / job :)
We started doing so with the creation of the backup CRD's but some additional work on the reoccurring jobs might be necessary.
CC @innobead @c3y1huang @jenting

**Comment by ElZakariyae** [comment]
> I feel like the the monitoring & alerting (email, etc) might be out of scope of longhorn. Then a simple cron/batch or prometheus service is all that would be needed and could be shared by the community.
> 
> What we can improve on though is make it easier to retrieve the status of a backup / job :) We started doing so with the creation of the backup CRD's but some additional work on the reoccurring jobs might be necessary. CC @innobead @c3y1huang @jenting

Well, having some Prometheus metrics is also fine. 
One of your colleagues said that an community user provided the Prometheus configuration on how to monitor the backup and send alerts, can i have the link please?

**Comment by shuo-wu** [comment]
> Well, having some Prometheus metrics is also fine. One of your colleagues said that an community user provided the Prometheus configuration on how to monitor the backup and send alerts, can i have the link please?

cc @PhanLe1010

**Comment by PhanLe1010** [comment]
Related to the prometheus metrics for backups. Ref:
* https://github.com/longhorn/longhorn/issues/2940
* https://github.com/longhorn/longhorn/issues/1180#issuecomment-693003131

**Comment by innobead** [comment]
Closing this and follow up with #2940 instead.
