### ISSUE TITLE
[BUG] Capitalization on the website for the blog and KB should be consistent

### ISSUE THREAD

**Issue by rebeccazzzz** [longhorn/longhorn#3573]
## Describe the bug

On the Longhorn website, the title of the knowledge base is capitalized as "The Longhorn Knowledge Base" (https://longhorn.io/kb/) and the title of the blog is capitalized as "The Longhorn blog" (https://longhorn.io/blog/).

## Expected behavior

I think the capitalization of the titles of these two sections should be consistent. Specifically, I think the B in "The Longhorn blog" (https://longhorn.io/blog/) should be capitalized.

**Comment by kaxing** [comment]
Validation - **PASSED**

Command to verify the page title case:
```
$ curl -sSL https://longhorn.io/kb/|grep "<title>"|grep -q "The Longhorn Knowledge Base" && echo True || echo False
$ curl -sSL https://longhorn.io/blog/ |grep "<title>"|grep -q "The Longhorn Blog" && echo True || echo False 
```
