### ISSUE TITLE
[DOC] Document method to easily update Longhorn settings in scripted fashion/across multiple clusters

### ISSUE THREAD

**Issue by sirredbeard** [longhorn/longhorn#3578]
The use case is to update the Guaranteed Engine CPU for the deployed Longhorn chart in multiple clusters.

Whilst the default value for this can be set on initial chart deployment, it is not possible to update via the helm chart values ("This default setting is only for a Longhorn system that hasn't been deployed. It has no impact on an existing Longhorn system. The settings for any existing Longhorn system should be modified using the Longhorn UI.") So the user needs to update the longhorn settings custom resources directly via kubectl, we do mention this in the Longhorn Knowledge Base at https://longhorn.io/kb/troubleshooting-default-settings-do-not-persist/ but the user expects a documented method for updating outside of the UI within the Longhorn documentation, so the request here is to update the Longhorn settings docs to note this method if this is the recommended way.

**Comment by yasker** [comment]
We need the sizing guide #2598 before this, otherwise we might underestimate the workload and result in connectivity issues.

**Comment by axeal** [comment]
The specific user request in this instance was to update Guaranteed Engine CPU, but this applies more widely to any of the default settings, for which the only documented approach after initial chart deployment is to use the Rancher UI.

**Comment by innobead** [comment]
@jenting please help update the doc of current version as well.

**Comment by innobead** [comment]
@longhorn/qa Please double check this.

**Comment by yangchiu** [comment]
in the [preview website](https://v1-2-4--longhornio.netlify.app/docs/1.2.4/advanced-resources/deploy/customizing-default-settings/)
the newly added content shown as expected
