### ISSUE TITLE
[FEATURE] NVMe/TCP 

### ISSUE THREAD

**Issue by orboan** [longhorn/longhorn#3581]
## Is your feature request related to a problem? Please describe

iSCSI is a bottleneck when using nvme ssd volumes.

## Describe the solution you'd like

Make possible to use NVMe/TCP instead of open-iscsi

## Describe alternatives you've considered

Mayastor

**Comment by liyimeng** [comment]
@orboan  +1 According to #3377 and https://github.com/longhorn/longhorn/issues/3037#issuecomment-930651029. 
The bottleneck might be in communication. @yasker @innobead @shuo-wu @joshimoo  Maybe this should be done before #3202?

**Comment by liyimeng** [comment]
@keithalucas  you are right. Maya guys pointed out these concerns as the main reasons for them to  start Mayastor. As @yasker  pointed out early that it is too much work for longhorn go nvme style, hence had been so long way to come, it is about more than two years now, I believe. So I am wondering if there is a way to forward step wise.  Otherwise, it look like nothing happening, like in the past two years. :(

**Comment by innobead** [comment]
> @keithalucas you are right. Maya guys pointed out these concerns as the main reasons for them to start Mayastor. As @yasker pointed out early that it is too much work for longhorn go nvme style, hence had been so long way to come, it is about more than two years now, I believe. So I am wondering if there is a way to forward step wise. Otherwise, it look like nothing happening, like in the past two years. :(

We are evaluating engine/replica part feature parity right now so this is what @keithalucas is working on. It will come to the development phase after all ongoing evaluations are done. This is our priority because people are expecting and we hear.

**Comment by sbates130272** [comment]
@keithalucas do you have any performance numbers on your SPDK prototype versus the iSCSI that longhorn currently supports. I would be very interested in seeing that as a justification for why Longhorn should add native NVMe and NVMe-oF support. I am a huge fan of NVMe so I do like the idea of supporting it, but only if the performance numbers justify it.

**Comment by lyveng** [comment]
Attaching a whitepaper published by lightbitslabs comparing performance of iscsi and nvme/tcp on same hardware
[NVMe-vs-iSCSI.pdf](https://github.com/longhorn/longhorn/files/10496399/NVMe-vs-iSCSI.pdf)

Summarising it here
<img width="636" alt="image" src="https://user-images.githubusercontent.com/1996412/214486809-7b444fba-f3b5-40ae-ba8a-32586def79a9.png">
<img width="632" alt="image" src="https://user-images.githubusercontent.com/1996412/214486848-bffb2ea0-ddbc-4899-a6c6-a908cc20cfe0.png">

**Comment by kesavkolla** [comment]
Any movement on this?
