### ISSUE TITLE
[BUG] test_salvage_auto_crash_all_replicas failing on master

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3594]
## Describe the bug

https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/29/testReport/junit/tests/test_ha/test_salvage_auto_crash_all_replicas/

## To Reproduce

1. Run the test `test_salvage_auto_crash_all_replicas` with master-head on SLES nodes.

**Comment by khushboo-rancher** [comment]
@chanow816 Could you please check first if this is reproducible manually?

**Comment by cchien816** [comment]
I will close this because more detailed info logged in https://github.com/longhorn/longhorn/issues/3648
