### ISSUE TITLE
[BUG] 'client.list_node()' throwing error 'ValueError: too many values to unpack'

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3595]
## Describe the bug

Wherever the list_node() is used, the test is throwing error 'https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/29/testReport/junit/tests/test_zone/test_replica_auto_balance_zone_best_effort/

**Comment by khushboo-rancher** [comment]
Earlier output of `client.list_node()` was 3 in our test env but it's 3. That's why the all the tests with `client.list_node()` are failing.

**Comment by yangchiu** [comment]
Currently test case `test_replica_auto_balance_zone_best_effort` is stable and can be run without problems.
