### ISSUE TITLE
[FEATURE] CIFS Backup Store Support

### ISSUE THREAD

**Issue by cnaslain** [longhorn/longhorn#3599]
We have setup a k8s cluster running with longhorn. I'm now trying to figure out how to manage the backup of our longhorn volumes.

I saw we can add an NFS provisioner and configure longhorn `backupTarget` to an NFS share... but in our company, we don't have NFS servers but Windows Shares that can be mounted using CIFS.

Is there any plans to support CIFS as a backup target, like it already exists for NFS/S3 ?

**Comment by mstrent** [comment]
CIFS would be a very practical option to have.

**Comment by romainsuire** [comment]
should be great

**Comment by PatrickHuetter** [comment]
+1 Would be very useful since SMB/CIFS also supports authentication which NFS doesn't out of the box.

**Comment by bds-congnguyen** [comment]
+1 to get notification :D

**Comment by voarsh2** [comment]
I instead have used Minio to store backups, and minio has a CFIS share mounted, so I am in fact using CFIS through Minio. But "native" support for CFIS would be welcomed.

**Comment by chriscchien** [comment]
Verified in longhorn master `3f5e63`
Result **Pass**

Test steps
1. Create samba share server by instructions [here](https://ubuntu.com/tutorials/install-and-configure-samba#1-overview)
2. Deploy Longhorn master
3. Follow [steps](https://github.com/longhorn/longhorn/blob/master/enhancements/20230116-smb-cifs-backup-store-support.md) to setup SMB/CIFS backupstore in Longhorn
4. Create workload with volume, write data and create backup 1
5. Write big size data into mount point(10 GB), create backup 2
6. Restore backup 1, data was correct
7. Restore backup 2, data was correct
8. Switch to another backupstore then switch back to CIFS boakupsotre success
9. Delete backup success.
