### ISSUE TITLE
[TASK] Create golang API for mounting NVMeoF targets

### ISSUE THREAD

**Issue by keithalucas** [longhorn/longhorn#3602]
## What's the task? Please describe

Longhorn currently has https://github.com/longhorn/go-iscsi-helper to set up and configure iSCSI block devices.  It does this by executing `tgtadm` and `iscsiadm`.   `tgtadm` runs in the instance manager pod to communicate with `tgtd` to create a iSCSI target of the longhorn type that communicates with the longhorn-engine over a Unix domain socket.  `iscsiadm` is run with `nsenter` to communicate with the `iscsid` process running on the node; it configures `iscsid` to use the iSCSI target provided by `tgtd`.  `iscsid` uses a netlink socket to 

NVMeoF behaves differently than `iscsid`; it `read`s, `write`s, and uses the `ioctl` system call on files in `/sys/class/nvme-subsystem`, ` /sys/class/nvme/`, and `/dev`.   I have been using the `nvme` command but instead of wrapping the command in golang, it would be possible to perform what the command is doing directly or use a the nvme C library: 
https://github.com/linux-nvme/libnvme

Because of the way nvme is implemented in Linux, we can avoid using `nsenter` to for connecting to NVMeOF targets, provided the container bind mounts the `/sys` and `/dev` directories.  However, the node needs to have the `nvme_tcp` kernel module loaded.  We could either require the node to load it similarly to how the `iscsid` services need to be running on the node currently, or we can use `nsenter` to check if it is loaded and load it with `modprobe nvme_tcp`.

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists
- [x] Create API to connect to an NVMeOF target; determine the new block device created, and create a new block device file in `/dev/longhorn` with the same major/minor.
- [x] Create API to disconnect an NVMeOF target and remove the `/dev/longhorn` file.
- [x] Test running in a container with `/sys` and `/dev` bind mounted.

## Additional context

Add any other context or screenshots about the task request here.

**Comment by liyimeng** [comment]
@keithalucas Is it a step forward to have this feature request  https://github.com/longhorn/longhorn/issues/3581?

**Comment by keithalucas** [comment]
@liyimeng It's not.  It is for developing tests to test #3202.

**Comment by keithalucas** [comment]
A TCP NVMe-oF target can be registered with Linux by writing: `nqn=<nqn>,transport=tcp,traddr=<ip>,trvsid=<port>` to `/dev/nvme-fabrics\n`.  I tested writing `nqn=nqn.2021-12.io.longhorn.volume:test,transport=tcp,traddr=127.0.0.1,trsvcid=4420\n` to `/dev/nvme-fabrics`.   

Reading from `/dev/nvme-fabrics` after writing something valid to it, produces something like `instance=2,cntlid=3\n`.

The `instance` and `cntlid` corresponse to an `/sys/class/nvme/nvme<instance>/` directory (it's actually a link to a directory in `/sys/devices/virtual/nvme-fabrics/ctl/nvme<instance>` that contains the file `cntlid` with that value of `cntlid` read from `/dev/nvme-fabrics`.  There is also a `/sys/class/nvme-subsystem` directory containing `nvme-subsysX` subdirectories.  There should be a subdirectory with symbolic link name `nvme<instance>` to first `nvme<instance>` directory.  The 
`nvme<instance>` directory will also have a `subsysnqn` file with the `nqn` value written to `/dev/nvme-fabrics` and an `address` file with the `traddr` and `trsvcid`.

Within the `/sys/class/nvme-subsystem/nvme-subsysX` directory, there are one or more `nvmeXnY` subdirectories which correspond to the devices discovered by the nvme subsystem.  Devices files which the `nvmeXnY` name should be created in `/dev` via `udev`, with major/minor specified in the `dev` file of this directory.

By writing to `/dev/nvme-fabrics`, we can follow information on sysfs to get the major/minor for the block device and create it in `/dev/longhorn`.
