### ISSUE TITLE
[TEST] Combine build test engine image script into longhorn-engine build pipeline

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#3611]
## What's the test to develop? Please describe

In https://github.com/longhorn/longhorn-tests/pull/859, this script can auto generate below images and push into docker hub for our e2e test

- longhorn-engine:version-test.6-6.3-3.1-1
- longhorn-engine:version-test.2-2.3-3.1-1
- longhorn-engine:upgrade-test.5-3.3-3.1-1

But this script need manually run

Ideally this script should combine into longhorn-engine build-pipeline:
**Auto trigger the script after each longhorn-engine master release**

## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] Understand longhorn-engine build pipeline/script
- [ ] Have environment to test
- [ ] Combine https://github.com/longhorn/longhorn-tests/pull/859 into longhorn-engine build pipeline

**Comment by innobead** [comment]
@meldafrawi I remembered you tried this before, and do you remember any problem you encountered caused it to fail last time?

**Comment by cchien816** [comment]
After today's QA sync up meeting discussion,  we decide to trigger this script on demand.

Thanks @meldafrawi for the help
