### ISSUE TITLE
[IMPROVEMENT] Improve snapshot purge

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3613]
## Is your improvement request related to a feature? Please describe

Currently, snapshot purging is time-consuming and maybe space-consuming as well. I think we can re-visit then try to improve it.

There are 2 ideas maybe doable now:
- ~~Merge snapshots by chunk~~
- Punch holes in the overlapping part when deleting the snapshot directly behind the volume head.

**Comment by shuo-wu** [comment]
Ideas from @joshimoo:
> The way to improve this is a chunk based data format, then we can mark a historical snapshot as "partial/dirty" while iteratively coalescing the chunks for example.
> This way the theoretical maximum total required disk space for the coalescing operation isn't the nominal disks space.

> For the moment to make this easier we can write some tooling to do a multi merge of n snapshots + cleanup while the volume is offline for example.
> The multi merge can process all snapshots at the same time and coalesce the required information directly into the volume head file. While removing the data interval from the old files.
> This would also full fill another user request of freeing disks space.

**Comment by shuo-wu** [comment]
For the snapshot squashing into the volume head feature, I think Longhorn can do it for a volume under the maintenance mode.

**Comment by innobead** [comment]
We should have an LEP to record the design.

**Comment by shuo-wu** [comment]
After checking the code and testing, I found that chunk-based snapshot coalescing is not doable. 
Right now, coalescing is a 2-step or 3-step API:
  1. Copy data from the child snapshot (newer one) to the parent snapshot (older one, and it's also the snapshot being removed)
  2. Replace the parent snapshot with the child snapshot:
    1. Remove the child snapshot
    2. Rename the parent snapshot to the child snapshot name

Notice that the snapshot coalescing is handled in sync agent servers rather than replica servers and there is no locking for it. It means there is no way to update [the sector/location map](https://github.com/longhorn/longhorn-engine/blob/cda02873ef0789a56fcca9ffcdbc5bea76f09018/pkg/replica/diff_disk.go#L17-L19) when we punch holes to the child snapshot file (which is the most critical step of the improvement) at the end of step 1. Later on once the replica wrongly [pinpoints some data chunks to the child snapshot](https://github.com/longhorn/longhorn-engine/blob/cda02873ef0789a56fcca9ffcdbc5bea76f09018/pkg/replica/diff_disk.go#L249), it would read holes only. And the data is actually migrated to the parent snapshot, which cannot be reflected in the location map at that moment. 

---
If we really need this feature, there are the following possible solutions:
  1. Move the coalescing from the sync agent server to the replica server, then update the location maps each time before punching a hole to the child snapshot.
  2. Wait for the sharding feature https://github.com/longhorn/longhorn/issues/1061. This means that each snapshot consists of multiple chunks. Then the current coalescing operation suddenly becomes chunk-based coalescing and we don't need to anything.
  3. Coalescing the file with a reverse way: copying valid data from the child to the parent then removing the parent. Here we will scan the fiemap of the parent snapshots: copy data that exists only in the parent to the child and punch holes for the overlapping part to the parent.

Solution 1 is too complicated and not applicable now. 
Since we may need to tackle the sharding feature in v1.4.0, which is actually solution 2. We can revisit this improvement after that. 
Solution 3 may help further decrease the extra space usage even if solution 2 is applied.

**Comment by innobead** [comment]
@shuo-wu See if we need to update the pruning part in the volume size doc which @derekbit just updated.

**Comment by shuo-wu** [comment]
It seems that some doc updates for v1.2.4 (or branch `master`) are not backported to branch `v1.3.0`. I have to backport those first. Is there a separate ticket tracking that?

@derekbit Do the illustrations you drew still exist? I need to add one more step based on the example you provide.

**Comment by yangchiu** [comment]
verified passed on master-head
by manual test: [snapshot purge retry ](https://github.com/longhorn/longhorn-tests/blob/master/docs/content/manual/release-specific/v1.3.0/test-snapshot-purge-retry.md) and 
e2e test (-k test_snapshot_prune)
