### ISSUE TITLE
[BUG] Backup in error state can not be deleted

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#3620]
## Describe the bug

From e2e case [test_backup_status_for_unavailable_replicas](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/38/testReport/junit/tests/test_basic/test_backup_status_for_unavailable_replicas_nfs_/) 

When backup in error state, it can not be deleted, this behavior make e2e case fail.
Can be reproduce on Ubuntu and SLES

## To Reproduce

1. Create volume with 2 Gi storage and attached that volume to node
2. Write 500 Mi data into volume
3. From UI, create backup of volume
4. While backup in progress, delete volume replicas form UI
5. In backup page, backup will in error state 
6. Try delete the error backup from UI, no error message shown and the error state backup still exist

## Expected behavior

Backup in error state should can be deleted

## Environment

 - Longhorn version: longhorn-manager:master-head
 - Installation method : Kubectl
 - Kubernetes distro and version: K3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
 - Underlying Infrastructure : AWS
 - Number of Longhorn volumes in the cluster: 1

**Comment by innobead** [comment]
cc @jenting @kaxing

**Comment by cchien816** [comment]
Attach is log from longhorn-manage while I am testing [longhorn-manager-pzxq7_longhorn-manager.log](https://github.com/longhorn/longhorn/files/8059735/longhorn-manager-pzxq7_longhorn-manager.log)

But when I clicked delete Button to delete backup in error state, I think I can not find correspond message show up.

**Comment by derekbit** [comment]
@cchien816 
Do you have longhorn-admission-webhook and longhorn-conversion-webhook logs? I'd like to see if it is related to webhooks or caused by other issues.

**Comment by cchien816** [comment]
Hi @derekbit ,

Please see below logs :
[longhorn-admission-webhook-57c4747b5d-kktcc_longhorn-admission-webhook.log](https://github.com/longhorn/longhorn/files/8060431/longhorn-admission-webhook-57c4747b5d-kktcc_longhorn-admission-webhook.log)
[longhorn-admission-webhook-57c4747b5d-r4v52_longhorn-admission-webhook.log](https://github.com/longhorn/longhorn/files/8060432/longhorn-admission-webhook-57c4747b5d-r4v52_longhorn-admission-webhook.log)
[longhorn-conversion-webhook-686496f964-qpcfw_longhorn-conversion-webhook.log](https://github.com/longhorn/longhorn/files/8060433/longhorn-conversion-webhook-686496f964-qpcfw_longhorn-conversion-webhook.log)
[longhorn-conversion-webhook-686496f964-xdnwt_longhorn-conversion-webhook.log](https://github.com/longhorn/longhorn/files/8060434/longhorn-conversion-webhook-686496f964-xdnwt_longhorn-conversion-webhook.log)

**Comment by cchien816** [comment]
Update : This issue may related to scheduling. 
On my local environment. The error state backup disappeared (deleted) after a long time (more than hours)

**Comment by derekbit** [comment]
After reverting the scheduling commits in #3083, the deletion works as expected.
I will come back to check again after @PhanLe1010 fixes the scheduling issue.

**Comment by PhanLe1010** [comment]
I think this is not related to the scheduling issue https://github.com/longhorn/longhorn/issues/3626. So the PR for that issue doesn't fix this one.

I can see from logs that Longhorn UI set the deletion timestamp for the backup CR. Then backup controller tried to delete it from backup target but failed to do so with the error `failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-665c15f8463f4a06.lck type 2 acquisition`. After 4 failed attempts (which is bigger than the maxretries which is 3 times), the backup controller gave up and forget this event. 

Action item:
* Increasing resync help to surface a new hidden issue here: why the deleting backuo fail with this error `failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-665c15f8463f4a06.lck type 2 acquisition`? cc @jenting 

```
[longhorn-manager-rxqdv longhorn-manager] time="2022-02-15T22:32:36Z" level=info msg="Found 1 backups in the backup target that do not exist in the cluster and need to be pulled" backupVolume=testvol1 controller=longhorn-backup-volume node=phan-v117-worker-2
[longhorn-manager-rxqdv longhorn-manager] time="2022-02-15T22:32:36Z" level=error msg="Error deleting remote backup" backup=backup-e6aee84a44d24622 controller=longhorn-backup error="error deleting backup s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn [backup rm s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1], output failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-665c15f8463f4a06.lck type 2 acquisition\n, stderr, time=\"2022-02-15T22:32:36Z\" level=error msg=\"failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-665c15f8463f4a06.lck type 2 acquisition\"\n, error exit status 1" node=phan-v117-worker-2
[longhorn-manager-rxqdv longhorn-manager] time="2022-02-15T22:32:36Z" level=warning msg="Error syncing Longhorn backup longhorn-system/backup-e6aee84a44d24622" controller=longhorn-backup error="longhorn-backup: fail to sync backup longhorn-system/backup-e6aee84a44d24622: error deleting backup s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn [backup rm s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1], output failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-665c15f8463f4a06.lck type 2 acquisition\n, stderr, time=\"2022-02-15T22:32:36Z\" level=error msg=\"failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-665c15f8463f4a06.lck type 2 acquisition\"\n, error exit status 1" node=phan-v117-worker-2
[longhorn-manager-rxqdv longhorn-manager] time="2022-02-15T22:32:38Z" level=error msg="Error deleting remote backup" backup=backup-e6aee84a44d24622 controller=longhorn-backup error="error deleting backup s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn [backup rm s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1], output failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-316920feea8f4831.lck type 2 acquisition\n, stderr, time=\"2022-02-15T22:32:38Z\" level=error msg=\"failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-316920feea8f4831.lck type 2 acquisition\"\n, error exit status 1" node=phan-v117-worker-2
[longhorn-manager-rxqdv longhorn-manager] time="2022-02-15T22:32:38Z" level=warning msg="Error syncing Longhorn backup longhorn-system/backup-e6aee84a44d24622" controller=longhorn-backup error="longhorn-backup: fail to sync backup longhorn-system/backup-e6aee84a44d24622: error deleting backup s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn [backup rm s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1], output failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-316920feea8f4831.lck type 2 acquisition\n, stderr, time=\"2022-02-15T22:32:38Z\" level=error msg=\"failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-316920feea8f4831.lck type 2 acquisition\"\n, error exit status 1" node=phan-v117-worker-2
[longhorn-manager-rlvlb longhorn-manager] 10.42.3.57 - - [15/Feb/2022:22:32:38 +0000] "GET /metrics HTTP/1.1" 200 4807 "" "Prometheus/2.16.0"
[longhorn-manager-wcpzc longhorn-manager] 10.42.3.57 - - [15/Feb/2022:22:32:39 +0000] "GET /metrics HTTP/1.1" 200 4748 "" "Prometheus/2.16.0"
[longhorn-manager-rxqdv longhorn-manager] 10.42.3.57 - - [15/Feb/2022:22:32:40 +0000] "GET /metrics HTTP/1.1" 200 5008 "" "Prometheus/2.16.0"
[longhorn-manager-rxqdv longhorn-manager] time="2022-02-15T22:32:40Z" level=error msg="Error deleting remote backup" backup=backup-e6aee84a44d24622 controller=longhorn-backup error="error deleting backup s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn [backup rm s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1], output failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-59d0e333de734b27.lck type 2 acquisition\n, stderr, time=\"2022-02-15T22:32:40Z\" level=error msg=\"failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-59d0e333de734b27.lck type 2 acquisition\"\n, error exit status 1" node=phan-v117-worker-2
[longhorn-manager-rxqdv longhorn-manager] time="2022-02-15T22:32:40Z" level=warning msg="Error syncing Longhorn backup longhorn-system/backup-e6aee84a44d24622" controller=longhorn-backup error="longhorn-backup: fail to sync backup longhorn-system/backup-e6aee84a44d24622: error deleting backup s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn [backup rm s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1], output failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-59d0e333de734b27.lck type 2 acquisition\n, stderr, time=\"2022-02-15T22:32:40Z\" level=error msg=\"failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-59d0e333de734b27.lck type 2 acquisition\"\n, error exit status 1" node=phan-v117-worker-2
[longhorn-manager-wcpzc longhorn-manager] time="2022-02-15T22:32:41Z" level=debug msg="Trigger sync backup target" component=backup-store-timer controller=longhorn-setting interval=5s node=phan-v117-worker-1
[longhorn-manager-rxqdv longhorn-manager] time="2022-02-15T22:32:41Z" level=info msg="Found 1 backups in the backup target that do not exist in the cluster and need to be pulled" backupVolume=testvol1 controller=longhorn-backup-volume node=phan-v117-worker-2
[longhorn-manager-rxqdv longhorn-manager] time="2022-02-15T22:32:42Z" level=error msg="Error deleting remote backup" backup=backup-e6aee84a44d24622 controller=longhorn-backup error="error deleting backup s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn [backup rm s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1], output failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-1c6b8b3927194341.lck type 2 acquisition\n, stderr, time=\"2022-02-15T22:32:42Z\" level=error msg=\"failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-1c6b8b3927194341.lck type 2 acquisition\"\n, error exit status 1" node=phan-v117-worker-2
[longhorn-manager-rxqdv longhorn-manager] E0215 22:32:42.783506       1 backup_controller.go:151] longhorn-backup: fail to sync backup longhorn-system/backup-e6aee84a44d24622: error deleting backup s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn [backup rm s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1], output failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-1c6b8b3927194341.lck type 2 acquisition
[longhorn-manager-rxqdv longhorn-manager] , stderr, time="2022-02-15T22:32:42Z" level=error msg="failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-1c6b8b3927194341.lck type 2 acquisition"
[longhorn-manager-rxqdv longhorn-manager] , error exit status 1
[longhorn-manager-rxqdv longhorn-manager] time="2022-02-15T22:32:42Z" level=warning msg="Dropping Longhorn backup longhorn-system/backup-e6aee84a44d24622 out of the queue" controller=longhorn-backup error="longhorn-backup: fail to sync backup longhorn-system/backup-e6aee84a44d24622: error deleting backup s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn [backup rm s3://backupbucket@us-east-1/?backup=backup-e6aee84a44d24622&volume=testvol1], output failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-1c6b8b3927194341.lck type 2 acquisition\n, stderr, time=\"2022-02-15T22:32:42Z\" level=error msg=\"failed lock backupstore/volumes/c5/7e/testvol1/locks/lock-1c6b8b3927194341.lck type 2 acquisition\"\n, error exit status 1" node=phan-v117-worker-2
```

**Comment by jenting** [comment]
I _think_ it's because the backup is still in progress but be cancelled, the backup lock existed on the remote backup target.
After the deletion event comes in, longhorn-engine tries to acquire a lock but failed because the [condition](https://github.com/longhorn/backupstore/blob/56ddc538b85950b02c37432e4854e74f2647ca61/lock.go#L71) does not pass.

> We can only acquire a lock if there is no unexpired(1) lock of a different
type(2) that has priority(3).
> 1) Locks are self expiring, once the current time is after `lock.serverTime + LOCK_DURATION` we no longer need to consider
this lock as valid.
> 2) Backup & Restore Locks are mapped to compatible types while Delete Locks are mapped to a different type to be mutually exclusive with the others.
> 3) Priority is based on the comparison order, where locks are compared by `lock.Acquired` then by `lock.serverTime` followed by `lock.Name`. Where acquired locks are always sorted before non acquired locks.
> 
> After 2.5 minutes, the lock acquisition will timeout and the backup operation will pass through that error and fail.

Therefore, the cancel backup operation would release the lock after [2.5 minutes](https://github.com/longhorn/backupstore/blob/56ddc538b85950b02c37432e4854e74f2647ca61/lock.go#L20).
Changing rsync period back to 30 seconds makes the deletion operation is able to acquire the lock after 5 times resync.

**Comment by derekbit** [comment]
After discussing with @jenting , we need to investigate some points firstly
- Why was the backup job in error state after deleting the replicas?
- What does the error state show?

**Comment by PhanLe1010** [comment]
I am thinking if we should remove the maxretries limit entirely. If we fail to sync a CR, I think we should retry it until we succeed (with a backoff limit capped at 5 minutes). This is similar to when CSI attacher fail to make NodePublishVolume call, it will retry infidelity until it succeeds with maximum 5 minutes backoff limit

**Comment by shuo-wu** [comment]
I guess at the beginning Longhorn just follows the basic pattern of Kubernetes controllers, in which there is typically a max retry limit set.
Your consideration is fair. And some of Kubernetes controllers do not set max retry limit, either. But we need to consider if the removed CRs or problematic CRs can be handled correctly rather than staying in the queue forever.

**Comment by PhanLe1010** [comment]
For the removed CRs, they will be dropped out of the queue [link](https://github.com/longhorn/longhorn-manager/blob/12d0ec9890db068ba28e50aa50b96dcd33bf6730/controller/volume_controller.go#L252-L259)

problematic CRs should be divided into 2 categories:
* recover able error (api error, fail precondition, ...) this should go back to the queue with backoff limit
* None recover able error (non-existing snapshot/ naming format) this can be drop out of the queue immediately. I.e., print our the error message and drop it out of the queue 

How do you think? @shuo-wu

**Comment by shuo-wu** [comment]
Sounds good. But the problem is, it's hard to figure out non-recoverable errors for each controller.

**Comment by PhanLe1010** [comment]
Can we do a failed safe approach that assumes all errors are recoverable by default unless proved otherwise? 
btw, requeuing by calling AddRateLimited() is not expensive. the object will be reconsidered after every 5 minutes.

**Comment by PhanLe1010** [comment]
A similar approach is done in csi provisioned https://github.com/kubernetes-csi/external-provisioner/blob/32c27a57ce311cf7b0fedefd6cc850845a41e341/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go#L1329-L1333

**Comment by shuo-wu** [comment]
But there may be a retry threshold set in the CSI provisioner: https://github.com/kubernetes-csi/external-provisioner/blob/32c27a57ce311cf7b0fedefd6cc850845a41e341/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go#L932-L945

**Comment by PhanLe1010** [comment]
Good observing! But the threshold is set to 0 by default which means retrying forever: https://github.com/kubernetes-csi/external-provisioner/blob/32c27a57ce311cf7b0fedefd6cc850845a41e341/cmd/csi-provisioner/csi-provisioner.go#L359

**Comment by shuo-wu** [comment]
OK. Then I am fine with your idea.

**Comment by PhanLe1010** [comment]
cc @jenting How do you think about the above discussion?

**Comment by jenting** [comment]
I agree with the above approach.

I have a question, for non-recoverable error, it will be dropped out of queue immediately. Is that means this CR would be reconcile every resync period but it will be return inside the resync period? Also, how do we differentiate the Backup CR is non-recoverable or not? By what criteria?

**Comment by PhanLe1010** [comment]
> Is that means this CR would be reconcile every resync period but it will be return inside the resync period?

Yes, the CR will be touch again every resync period (1h or more)

> Also, how do we differentiate the Backup CR is non-recoverable or not? By what criteria?

Some idea on top of my head:
* By default, we consider errors are recoverable 
* Some obvious non-recoverable errors: source volume doesn't exist; backup target setting is empty; ...

**Comment by jenting** [comment]
Okay, looks like we need to define the different error codes (Like Kubernetes conditions data struct) in Backup CR to indicate it's a recoverable or non-recoverable error

**Comment by innobead** [comment]
Before having a way to define different types of errors. as per the above discussion, should we remove the max retry and just keep reading to the queue by assuming all errors are recoverable now?

**Comment by derekbit** [comment]
We may can increase the maxRetries number. The value is 3 and the corresponding time intervals are 5ms, 10ms and 20ms. They are pretty short.
 
How about increasing the value to make maximum interval to be 60 seconds? @PhanLe1010 @shuo-wu @innobead

**Comment by derekbit** [comment]
As discussion with @PhanLe1010 , keep it as is.

**Comment by cchien816** [comment]
Verified  pass on master-head 20220407

Backup in error state can be deleted 
Also on e2e test, result were [pass](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/84/testReport/tests/test_basic/test_backup_status_for_unavailable_replicas_nfs_/), close this ticket
