### ISSUE TITLE
[QUESTION] how to delete LH volume without PVC

### ISSUE THREAD

**Issue by orxibi** [longhorn/longhorn#3622]
## Question
Issues with kafka cluster 
## Environment

 - Longhorn version:1.2.3
 - Kubernetes version:v1.20.14

 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): On-prem

Hi we are having issues with our Kafka cluster in regards to volume.
We have volumes that are stuck in deleting state for more then a month due to disk pressure the cluster does not exist any more we it to create a new one. I was able to remove 1 of this volumes via rancher however the volume still appear in Longhorn.
The only solution we found online is to delete the longhorn cluster and start again, which is not a valid option for us. Is there any workaround for this case and any future cases of disk pressure?  

In addition, we recently face an out of memory issue with our test kafka cluster(was expected). However while expanding the volume size of each PVC . one pod was not able to start up and stuck in 'notReady' state till now. The other pods were restarted without any problem.

We will appreciate If there is a possibility to get someone from your team to help us understand better the behavior of Longhorn in regards to matters mentioned above.

**Comment by shuo-wu** [comment]
The discussion is in Slack: https://cloud-native.slack.com/archives/CNVPEL9U3/p1644849960108259
