### ISSUE TITLE
[TASK] Improve the doc for volume actual size and space usage

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3627]
## What's the task? Please describe

Right now some users are confused about why and when the volume actual size can be greater than the spec size. Then they may have no idea of how they can config Longhorn

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [x] The doc that **explicitly** mentions and explains the case that the volume actual size is greater than the spec size.
- [x] The doc that guides users on how they can evaluate the disk space requirement and how they can config the cluster correctly.

## Additional context
Why volume actual size will be greater than the spec size:
- Longhorn system is a **block-level** storage system and does not understand the **filesystem**. When the filesystem cannot reclaim/recycle the used sectors for the volume/block device when deleting one file. As a result, the actual size of Longhorn volumes cannot be shrunk in this case.
- Longhorn volumes support snapshots, which will record historical data. This kind of historical data means extra space consumption. Each snapshot (or the volume head, which stores the latest data of the volume) would eat the spec size space at most. That is another reason why the actual size is bigger than expected. Even if users do not take snapshots for volumes, there are some other operations like rebuilding, expansion, or backing up that would lead to the system creating system (hidden) snapshots. In general, snapshotting is unavoidable.

Configuration suggestion:
- Expand the node disks so that there is more buffer for Longhorn volume usages if the disk resources are limited.
- It’s better to set `Storage Over Provisioning Percentage` to be smaller than 100% if there are heavy writing tasks for the volumes. The heavy writing tasks would lead to the actual size of volumes probably being larger than the spec size. Over-provisioning is a bad choice in this case.
- Do not retain too many snapshots for the volumes. Cleaning up snapshots would help reclaim disk space sometimes. But one thing I should emphasize is that some extra space is required during the snapshot cleanup/merge(copy then delete). As for how we can clean up the snapshot including the system hidden ones created during rebuilding/expansion, there are 2 ways: Deleting them manually via UI, or setting a snapshot recurring job with retention 1 (this would clean up system snapshots automatically).

**Comment by innobead** [comment]
cc @joshimoo

**Comment by shuo-wu** [comment]
There may be some overlappings with https://github.com/longhorn/longhorn/issues/2313

**Comment by iosifnicolae2** [comment]
What should we do if the node got full because of these snapshots which haven't been deleted? - https://github.com/longhorn/longhorn/issues/2752#issuecomment-1087526860

**Comment by shuo-wu** [comment]
The current workaround is: periodically create a new snapshot then delete the old snapshot for the volumes. So that the old snapshot data will coalesce with the previous volume head(aka. the new snapshot). You can achieve this by setting a snapshot recurring job.

The long-term solutions will be the below 2 improvements:
  - Improve the snapshot space reclaim so that you don't need to periodically create and delete the snapshots: https://github.com/longhorn/longhorn/issues/3613
  - Reclaim the space when files are removed from the filesystem: https://github.com/longhorn/longhorn/issues/836

**Comment by iosifnicolae2** [comment]
It would be awesome to have a mechanism to reclaim the empty space.

**Comment by innobead** [comment]
Closing, because the doc has been reviewed and merged.
