### ISSUE TITLE
[DOC] Update RHEL instructions for open-iscsi

### ISSUE THREAD

**Issue by keithalucas** [longhorn/longhorn#3630]
The instructions for setting up open-iscsi for RHEL and related distributions say to just run `yum install iscsi-initiator-utils`.  https://github.com/longhorn/website/blame/master/content/docs/1.2.3/deploy/install/_index.md#L110

However, we also have an installation yaml file that installs it on RHEL with `yum --setopt=tsflags=noscripts install -q -y iscsi-initiator-utils && echo "InitiatorName=$(/sbin/iscsi-iname)" > /etc/iscsi/initiatorname.iscsi && sudo systemctl -q enable iscsid && sudo systemctl start iscsid`.  This only enables the iscsid systemd service from the RPM. 
 We have encountered problems with some users installing the `iscsi-initiator-utils` RPM because it includes an iscsi systemd service which attempts to login and scan all iSCSI targets in the /var/lib/iscsi/nodes directory. 
 https://github.com/longhorn/website/blame/master/content/docs/1.2.3/deploy/install/_index.md#L115

We could have instructions that are less automated script like:

```
yum --setopt=tsflags=noscripts install iscsi-initiator-utils
systemctl enable iscsid
systemctl start iscsid
```

And add an explanation about the iscsi service.

Also, it may be possible to use iSCSI targets other than those provided by longhorn.  We should provide some guidance on how to do this on a KB if it's possible.

**Comment by innobead** [comment]
Just need to update the current 1.2.3 doc, and it will be updated accordingly to 1.1.4, 1.2.4, and 1.3.0.

**Comment by Rancheroo** [comment]
I have a customer experiencing issues (volumes not attaching) when installing iscsid on RHEL8.5
using 
`yum --setopt=tsflags=noscripts install iscsi-initiator-utils
systemctl enable iscsid
systemctl start iscsid`
with better results 
`yum install iscsi-initiator-utils`

1. Was this tested on RHEL 8.5 and found to be working?
2. It seems there is more being done then just enabling and starting the service as there are issues when attaching volumes to nodes OR maybe i am not seeing something obvious here.

**Comment by mantissahz** [comment]
Hi @Rancheroo,
1. I think we only test on RHEL 7.9,8.3,8.4 now
2. Yes, from this YAML https://raw.githubusercontent.com/longhorn/longhorn/v1.3.1/deploy/prerequisite/longhorn-iscsi-installation.yaml, we actually do `echo "InitiatorName=$(/sbin/iscsi-iname)" > /etc/iscsi/initiatorname.iscsi` before enable iscsid.

**Comment by innobead** [comment]
This part was missed because, in the current doc, we align the installation with `longhorn-iscsi-installation.yaml` to skip script execution but it will require users to create `initiatorname.iscsi` as below link.  

ref: https://git.rockylinux.org/staging/rpms/iscsi-initiator-utils/-/blob/r8/SPECS/iscsi-initiator-utils.spec#L232-240

@mantissahz Could you help add this step in our current doc? thanks.
