### ISSUE TITLE
[BUG] Volume does not mount on KiND

### ISSUE THREAD

**Issue by kconde2** [longhorn/longhorn#3643]
Hello everyone,

I would like to know if anyone has used longhorn storage on kind (https://kind.sigs.k8s.io/).

When I create a volume it constantly switches between "attached" and "detached" and the volume never goes up.

Do you know if there are specific things to do with it to make it work?
  
## Environment

 - Longhorn version: 1.2.3
 - Kubernetes version: v1.22.5
 - Node config

I think have same problem as described here :

https://longhorn.io/kb/troubleshooting-volume-pvc-xxx-not-scheduled/

I already followed all the recommendations but it did not work.

Here is how I did to install longhorn

```shell
helm repo add longhorn https://charts.longhorn.io
helm repo update
helm install longhorn longhorn/longhorn \
  --namespace longhorn-system \
  --create-namespace \
  --set defaultSettings.replicaSoftAntiAffinity="true" \
  --set defaultSettings.allowVolumeCreationWithDegradedAvailability="true"
  ```
  
  Is it normal to have these as configmap values ?
  
![image](https://user-images.githubusercontent.com/43377621/154669571-ed722d6c-b853-4644-92fd-0a4a8a12f91d.png)

  
  I also built custom docker image to use with Kubernetes In Docker as worker node image
  
  ```shell
  FROM kindest/node:v1.22.5

RUN apt-get update && apt-get install -y open-iscsi nfs-common bash curl util-linux grep gawk
  ```
  
I created local cluster with KiND with the following command : 

```shell
kind create cluster --image kindest/node:v22.02.17 --config ./kind.config.yaml
```

With this config : 

```shell
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mine-cluster
nodes:
- role: worker
- role: worker
- role: worker
- role: worker
- role: control-plane
- role: control-plane
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
    - containerPort: 32080
      hostPort: 80
      protocol: TCP
    - containerPort: 32443
      hostPort: 443
      protocol: TCP
    - containerPort: 32090
      hostPort: 9000
      protocol: TCP
```

## Additionnal informations

Screenshots
![image](https://user-images.githubusercontent.com/43377621/154665910-3f2ecbdd-6179-418c-952d-4cc5db8ceea2.png)

![image](https://user-images.githubusercontent.com/43377621/154666004-22b7365b-5449-42c4-98cf-d3cd4bd0bbce.png)

Using k9s everything is ok with longhorn config
![image](https://user-images.githubusercontent.com/43377621/154666336-4626da3d-d7ff-4c1b-9c16-ef6d9a70ce1b.png)

Using the Environment Check Script everything is ok
![image](https://user-images.githubusercontent.com/43377621/154666542-a0bd3cb1-128e-4a41-8a7c-8aebc04f9da3.png)

Generated Support Bundle for UI
[longhorn-support-bundle_c9250228-5aeb-461f-b486-20c68ca9dd16_2022-02-18T10-47-53Z.zip](https://github.com/longhorn/longhorn/files/8096484/longhorn-support-bundle_c9250228-5aeb-461f-b486-20c68ca9dd16_2022-02-18T10-47-53Z.zip)

Thanks in advance for helping me

**Comment by kconde2** [comment]
Generated Support Bundle for UI
[longhorn-support-bundle_c9250228-5aeb-461f-b486-20c68ca9dd16_2022-02-18T10-47-53Z.zip](https://github.com/longhorn/longhorn/files/8096475/longhorn-support-bundle_c9250228-5aeb-461f-b486-20c68ca9dd16_2022-02-18T10-47-53Z.zip)

**Comment by derekbit** [comment]
@kconde2 You could please refer to https://github.com/longhorn/longhorn/discussions/2702).

**Comment by kconde2** [comment]
Thanks for your answer @derekbit 

I close this ticket then. If someone else have another solution to run this please feel free to reopen or comment.

Thanks in advance.

**Comment by kconde2** [comment]
I'm finally using multipass with k3s (https://multipass.run/) and it works well to test locally.
