### ISSUE TITLE
[BUG] Instance Manager Pods randomly restart triggering the restart of application pods.

### ISSUE THREAD

**Issue by linus365** [longhorn/longhorn#3644]
## Describe the bug

Instance Manager Pods randomly restart triggering the restart of application pods.

## To Reproduce

I did not find steps to reproduce the problem, it randomly happens around once a day.
I don't think that it can be a connectivity problem between the nodes, since they all are hosted on netcup.

## Expected behavior

My pods should not have downtime this often because of longhorn.

## Log or Support bundle

[longhorn-support-bundle_8c49d2da-3210-41e8-af29-1790dce92756_2022-02-19T13-30-49Z.zip](https://github.com/longhorn/longhorn/files/8102253/longhorn-support-bundle_8c49d2da-3210-41e8-af29-1790dce92756_2022-02-19T13-30-49Z.zip)

## Environment

 - Longhorn version: v1.2.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.22.5+rke2r1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3 (control plane is used for workloads)
 - Node config
   - OS type and version:  Ubuntu 20.04.3 LTS
   - CPU per node: 10
   - Memory per node: 64Gb
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 2.32 Gbits/sec (tested with iperf)
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM Netcup
 - Number of Longhorn volumes in the cluster: 28

## Additional context

I will investigate the logs further, but currently i have nothing to add.
Thanks for any help in advance :)

**Comment by derekbit** [comment]
Found the log messages in instance-manager-e.
The network looks sometimes disconnected.

```
2022-02-19T13:44:01.599902014+01:00 time="2022-02-19T12:44:00Z" level=info msg="Set replica tcp://10.42.0.54:10255 to mode ERR"
2022-02-19T13:44:01.599905771+01:00 time="2022-02-19T12:44:00Z" level=error msg="Ignoring error because tcp://10.42.2.180:10390 is mode RW: tcp://10.42.0.54:10255: r/w timeout"
2022-02-19T13:44:01.599909338+01:00 time="2022-02-19T12:44:00Z" level=error msg="Error reading from wire: read tcp 10.42.0.55:45536->10.42.0.54:10256: use of closed network connection"
2022-02-19T13:44:01.599912974+01:00 time="2022-02-19T12:44:00Z" level=error msg="Setting replica tcp://10.42.0.54:10255 to ERR due to: r/w timeout"
2022-02-19T13:44:01.599916691+01:00 time="2022-02-19T12:44:00Z" level=info msg="Ignore set replica tcp://10.42.0.54:10255 to mode ERR due to it's ERR"
2022-02-19T13:44:01.599919386+01:00 time="2022-02-19T12:44:00Z" level=info msg="Monitoring stopped tcp://10.42.0.54:10255"
2022-02-19T13:44:01.599922163+01:00 time="2022-02-19T12:44:00Z" level=error msg="Ignoring error because tcp://10.42.2.180:10390 is mode RW: tcp://10.42.0.54:10255: r/w timeout"
```

**Comment by innobead** [comment]
It looks like a cascading issue related to #2650 if the environment is not quite stable. Restarting an instance manager pod only when the node is not ready or even the node resource exhaustion. However, some improvements will be introduced from #2650 .

**Comment by linus365** [comment]
Thanks for the quick feedback. So this could be resolved with v1.2.4? Is it clear yet, how soon that will release?
Is there something i can do in the meantime to stabilize longhorn? I wanted to give it higher priority, but i did not find a good solution to temporarily detach all pods for changes like that. There are too many replicasets to scale them all down manually.
Thanks a lot! I felt lost with the issue and feel reassured now :)

**Comment by derekbit** [comment]
@linus365 
I saw many replicas encountered rw timeout, remove replica and then rebuild.
Can you provide the volume name and time point for my check?
Thank you.

**Comment by linus365** [comment]
Hey @derekbit. Thanks for your Feedback. Sorry for the late response, i did not see it earlier.
I create a new support bundle because the problem is still occurring frequently and i am hoping the new bundle might be able to provide new insights. Here we go:
[longhorn-support-bundle_8c49d2da-3210-41e8-af29-1790dce92756_2022-03-04T09-49-45Z.zip](https://github.com/longhorn/longhorn/files/8184775/longhorn-support-bundle_8c49d2da-3210-41e8-af29-1790dce92756_2022-03-04T09-49-45Z.zip)

To your question: 
The problem does not only effect a single Volume.
Once a new Instance Manager gets created it overtakes all the volumes from the last which seems to force pods to reattach to them. Can you specify your question for me, please?

**Comment by jenting** [comment]
> Also curious, right before i created the support bundle a bunch of volumes toggled to faulted and then rebuilded.
Did not effect any pods though, so only unused replicas seem to be effected.

Could you please check the rebuilded replica of all volumes are on the same node?

Since you mentioned that all volumes are effected. Not sure if you encounter the instance manager restart every hour issue, but please check the [knowledge base](https://longhorn.io/kb/troubleshooting-instance-manager-pods-are-restarted-every-hour/) to see if it's helpful to you.

**Comment by linus365** [comment]
@jenting 
Hey :) Is there an easy way to check on which nodes volumes have been rebuilded?
Otherwise not all volumes are affected at the same time and also it does not happen hourly.
So i think it sadly has nothing to do with the instance manager bug you mentioned. But thanks for the link :)

**Comment by linus365** [comment]
I just updated Longhorn to v1.2.4-rc1. I will watch it for a couple of days and report back if it fixes the problem. Thanks a lot for the help :)

**Comment by linus365** [comment]
Hey, the instance manager is now completely stable. Thanks so much!
Sadly pods still die sometimes, but that seems to be a different problem.
