### ISSUE TITLE
Error: rendered manifests contain a resource that already exists.

### ISSUE THREAD

**Issue by chen5041** [longhorn/longhorn#3645]
## Question
> Suggest to use https://github.com/longhorn/longhorn/discussions to ask questions.

## Environment

 - Longhorn version:
 - Kubernetes version:
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

## Additional context

[root@qilin-x86-001 longhorn]# helm upgrade --install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace -f custom-values.yaml

Release "longhorn" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "engines.longhorn.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "longhorn-system": current value is "longhorn"

**Comment by derekbit** [comment]
How did you install Longhorn previously? This is probably a compatibility issue of installation methods.

**Comment by derekbit** [comment]
Only the namespace "longhorn-system" is supported.
We will document it later.
