### ISSUE TITLE
[BUG] Create volume from backing image and attach that volume will easily stuck at attaching

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#3646]
## Describe the bug

From e2e cases 
[tests.test_backing_image.test_backing_image_basic_operation](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/45/testReport/junit/tests/test_backing_image/test_backing_image_basic_operation/)
[tests.test_backing_image.test_backup_with_backing_image[nfs]](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/45/testReport/junit/tests/test_backing_image/test_backup_with_backing_image_nfs_/)
[tests.test_backing_image.test_ha_backup_deletion_recovery[nfs]](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/45/testReport/junit/tests/test_backing_image/test_ha_backup_deletion_recovery_nfs_/)

This case is hard to reproduce by hand but can reproduced by script very easily because of timing issue
In test script, after add backing image, immediately create volume from backing image and immediately attach the volume to node will fail very easily, volume will stuck at attaching state because backing image replica build fail with error message `failed to process backing image`:

<img src="https://user-images.githubusercontent.com/73337386/154917741-64fd1cca-d36b-4d56-afc8-de03db3a4f66.png" width="600" >

## To Reproduce

1. Deploy Longhorn master-head on SLES machine
2. Deploy longhorn-tests pod
3. Perform `kubectl exec -it longhorn-test -- /bin/bash`
4. Perform `test_backing_image.py::test_backing_image_basic_operation`

## Expected behavior

Test result should pass since it's is hard reproduce by hand

## Log or Support bundle

[longhorn-support-bundle_backing_images_fail.zip](https://github.com/longhorn/longhorn/files/8107660/longhorn-support-bundle_backing_images_fail.zip)

## Environment

 - Longhorn version: master-head 0221
 - Installation method : Kubectl
 - Kubernetes distro and version: k3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: suse-sles-15-sp3-v20210622-hvm-ssd-x86_64 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 1

## Additional context

Using API quickly perform create volume from backing image and attach the volume will easily cause backing image replica fail, 
But if add sleep time between those steps, the scenario rarely happen, maybe this need developers dive into, thank you

**Comment by innobead** [comment]
@chriscchien is this still a valid issue?

cc @longhorn/qa

**Comment by chriscchien** [comment]
Sorry for the late reply, it is not a valid issue now, related test case worked well on pipeline now(master [AMD64](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/test_results_analyzer/), [ARM64](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/test_results_analyzer/))
