### ISSUE TITLE
[BUG] Statefulset pod get data input/output error after delete instance manager

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#3648]
## Describe the bug

From below HA e2e cases and can be easily reproduced  
[test_auto_remount_with_subpath](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/46/testReport/junit/tests/test_ha/test_auto_remount_with_subpath)
[test_volume_reattach_after_engine_sigkill](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/46/testReport/junit/tests/test_ha/test_volume_reattach_after_engine_sigkill)
[test_salvage_auto_crash_all_replicas](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/46/testReport/junit/tests/test_ha/test_salvage_auto_crash_all_replicas)

Statefulset pod will get data input/output error after delete instance manager of volume attached to

## To Reproduce

1. Deploy Longhorn
2. Create Volume and PVC
3. Create statefulset and use previous created PVC as storage
4. In statefulset pod, write data into mount point
5. Delete instance manager name of the volume
6. After instance manager restart ready, check data in pod
7. Simple command `ls` will get  `ls: reading directory '.': Input/output error`

## Expected behavior
For high availability, data should be kept

After instance manager deleted, pod should have state change like from `Pending` to `Running`
But the pod shows 'Running' during instance manager restart process

## Environment

 - Longhorn version: master head 0222
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: suse-sles-15-sp3-v20210622-hvm-ssd-x86_64 
   -Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 1

**Comment by innobead** [comment]
This seems related to #3083 and this should also happen to the share manager, RWX mode.

**Comment by cchien816** [comment]
Update,

Delete share manager pod will encounter the same situation if use RWX volume to statefulset pod

**Comment by PhanLe1010** [comment]
@innobead  Could you give some hints about why this one is related to https://github.com/longhorn/longhorn/issues/3083 ? Thank you

**Comment by innobead** [comment]
> @innobead Could you give some hints about why this one is related to #3083 ? Thank you

Sorry to miss this comment. Probably not related.

**Comment by innobead** [comment]
@cchien816 could you check it again on CI? I found those issues passed recently.

**Comment by cchien816** [comment]
**Validate Pass**

For test fail about below 3 test cases
[test_auto_remount_with_subpath](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/46/testReport/junit/tests/test_ha/test_auto_remount_with_subpath)
[test_volume_reattach_after_engine_sigkill](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/46/testReport/junit/tests/test_ha/test_volume_reattach_after_engine_sigkill)
[test_salvage_auto_crash_all_replicas](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/46/testReport/junit/tests/test_ha/test_salvage_auto_crash_all_replicas)


Those error not happened in recent CI build [113](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/113/testReport/tests/test_ha/), [111](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/111/testReport/tests/test_ha/), [110](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/110/testReport/tests/test_ha/), [109](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/109/testReport/tests/test_ha/).
Close this issue, if happen again will create another one for analyze
