### ISSUE TITLE
[BUG] Replica auto-balance tests fails in regression

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#3649]
## Describe the bug

Replica auto-balance doesn't work and fails in the nightly run. 

## To Reproduce

`./run.sh -s -k test_replica_auto_balance`

## Expected behavior

Should pass

## Log or Support bundle

`n/a`

## Environment

`n/a`

## Additional context

Side effect https://github.com/longhorn/longhorn/issues/3083

**Comment by c3y1huang** [comment]
Removing backport label. Ref https://github.com/longhorn/longhorn-manager/pull/1229#issuecomment-1048601847.

**Comment by cchien816** [comment]
**Validation Pass**

Validated on Longhorn master-head 0224 and longhorn-test [PR 892](https://github.com/longhorn/longhorn-tests/pull/892), test result as below
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/737/testReport/tests/

**Comment by kaxing** [comment]
Did an extended test out of curiosity.
`test_replica_auto_balance_zone_best_effort_with_uneven_node_in_zones` will pass on a 5-worker-nodes(v1.21.9+rke2r1) cluster. cc @c3y1huang @cchien816 
```
root@longhorn-test:/integration/tests# bash run.sh test_zone.py::test_replica_auto_balance_zone_best_effort_with_uneven_node_in_zones
+ flake8
./test_zone.py:715:1: E265 block comment should start with '# '
+ pytest -v test_zone.py::test_replica_auto_balance_zone_best_effort_with_uneven_node_in_zones
======================================================================================= test session starts =======================================================================================
platform linux -- Python 3.9.10, pytest-5.3.1, py-1.11.0, pluggy-0.13.1 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /integration, inifile: pytest.ini
plugins: repeat-0.9.1
collected 1 item

test_zone.py::test_replica_auto_balance_zone_best_effort_with_uneven_node_in_zones PASSED                                                                                                   [100%]

================================================================================== 1 passed in 77.64s (0:01:17) ===================================================================================
```
