### ISSUE TITLE
[FEATURE] Helm Chart make loglevel configurable

### ISSUE THREAD

**Issue by patsys** [longhorn/longhorn#3655]
## Is your feature request related to a problem? Please describe

The log level from Longhorn is not configurable in the Helm Chart and the debug flags are set.

## Describe the solution you'd like
In the Helm Chart Longhorn deploy with "--debug" flag this can be make configurable.

**Comment by derekbit** [comment]
@patsys 
Could you please elaborate more the reason and the purpose of the feature request?

**Comment by patsys** [comment]
In my environment the logs aggregate on a central service and I have seen logs like:
`Trace[1964877352]: "Reflector ListAndWatch" name:github.com/longhorn/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go`
`level=info msg="GetPluginInfo: rsp: {\"name\":\"driver.longhorn.io\",\"vendor_version\":\"v1.2.3\"}"`

This is not seen often but not need for the environment.

**Comment by derekbit** [comment]
The verbosities of longhorn-manager and the components dynamically deployed during start up are set to 2 now. The log level (2) is better choice for logging useful information and avoiding the log message flood.

**Comment by olljanat** [comment]
> The verbosities of longhorn-manager and the components dynamically deployed during start up are set to 2 now. The log level (2) is better choice for logging useful information and avoiding the log message flood.

@derekbit that is not true. Debug level logging is hardcoded in multiple places which why Longhorn floods logs with debug events:
https://github.com/longhorn/longhorn/blob/bfe44afdf880007c55bc6530f592e1b2562e7571/chart/templates/daemonset-sa.yaml#L33
https://github.com/longhorn/longhorn-manager/blob/ec91a689daef211cd0435f840d7fed2f4fb2ae51/controller/instance_manager_controller.go#L1097
https://github.com/longhorn/longhorn-manager/blob/ec91a689daef211cd0435f840d7fed2f4fb2ae51/controller/instance_manager_controller.go#L1172

**Comment by derekbit** [comment]
Yeah, it's typo. Thanks for the correctness. Current log level is debug. Some log messages should be set to `trace` to avoid the message flood.

**Comment by yardenshoham** [comment]
Resolved in #5953?

**Comment by mantissahz** [comment]
This feature should be implemented by https://github.com/longhorn/longhorn/issues/5888 and https://github.com/longhorn/longhorn/pull/5953
