### ISSUE TITLE
[BUG] longhorn-ui crashlooping when running RKE2 with cis-1.5 profile

### ISSUE THREAD

**Issue by mattmattox** [longhorn/longhorn#3658]
## Describe the bug

`longhorn-ui` requires `allowPrivilegeEscalation` equal to be true in order to start when running on an RKE2 cluster with the cis-1.5 profile.

## To Reproduce

1. Create RKE2 cluster using the step listed at https://docs.rke2.io/security/hardening_guide/
2. Install Longhorn using kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.2.3/deploy/longhorn.yaml
3. Watch pod for longhorn-ui as it will stuck in a crashloop with the following error.

Error
```
Thu, Feb 24 2022 2:57:23 am | 2022/02/24 08:57:23 [warn] 1#1: duplicate MIME type "text/html" in /etc/nginx/nginx.conf:7
Thu, Feb 24 2022 2:57:23 am | nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/nginx.conf:7
Thu, Feb 24 2022 2:57:23 am | 2022/02/24 08:57:23 [emerg] 1#1: chown("/var/cache/nginx/client_temp", 101) failed (1: Operation not permitted)
Thu, Feb 24 2022 2:57:23 am | nginx: [emerg] chown("/var/cache/nginx/client_temp", 101) failed (1: Operation not permitted)
```

## Expected behavior

Longhorn should work on a harden RKE2 cluster

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.2.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
   - Number of management node in the cluster: 5
   - Number of worker node in the cluster: 5
 - Node config
   - OS type and version: Ubuntu
   - CPU per node: 4
   - Memory per node: 8
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 2x10GB in Bond
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMware
 - Number of Longhorn volumes in the cluster: 1

## Workaround

Add unrestricted-psp to default serviceaccount in Longhorn-system and patch deployment to allowPrivilegeEscalation.

```
kubectl create clusterrolebinding --serviceaccount=longhorn-system:default --clusterrole=system-unrestricted-psp default-system-unrestricted-psp --dry-run -o yaml | kubectl apply -f -
kubectl -n longhorn-system patch deployments/longhorn-ui --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/securityContext/allowPrivilegeEscalation", "value":true}]'
```

**Comment by innobead** [comment]
cc @smallteeths

**Comment by mattmattox** [comment]
I created two PRs to fix this issue. TLDR; We need to move some tmp directories used by NGINX to an emptyDir and to set the securityContext.
https://github.com/longhorn/longhorn/pull/3659
https://github.com/longhorn/longhorn-ui/pull/495

**Comment by innobead** [comment]
https://github.com/longhorn/longhorn-ui/pull/498 (1.2.4)
https://github.com/longhorn/longhorn/pull/3687 (master)

**Comment by khushboo-rancher** [comment]
Validated with RKE2 v1.23.4+rke2r1 with cis-1.5 profile and Longhorn master-head `03/04/2022`

Validation - **Pass**

I was able to reproduce the problem with Longhorn v1.2.3 on the same cluster, on upgrading it to master-head. Problem got resolved.
Validated with fresh installation as well.
