### ISSUE TITLE
[QUESTION] Longhorn replica actual size and storageReserved config doubts

### ISSUE THREAD

**Issue by aalcaraz97** [longhorn/longhorn#3660]
## Question
I have a 3-node K3S cluster with Longhorn v1.1.3 installed. I have one replica per each Longhorn volume (so 3 replicas per volume in my cluster), and each replica is scheduled on a different node.

I also deploy Prometheus in my cluster:

- To store the metrics of the whole cluster, I create a Persistent Volume (using Longhorn StorageClass) with a capacity of 10Gi.
- To limit the metrics Persistent Volume to grow, I configure Prometheus metrics retention by time interval and size:
  - time interval: 14 days
  - size: 8 Gi

I don't configure any sort of backup for the Longhorn volume, as I handle the backup part externally to the Longhorn procedure.
I also don't configure any sort of automatic snapshot job or config, and I haven't created any snapshot for the metrics volume manually from the UI.

After a few days with the cluster installed, the metrics Persistent Volume usage has grown. 
This is the "du" output of the folder in the Prometheus pod where the volume is mounted:
```bash
$ sudo du -h -d 1 /var/lib/kubelet/pods/c914919d-a817-4f05-80de-630afae6c582/volumes/kubernetes.io~csi/pvc-e4dd2e05-72d0-45e3-b652-84384126c87a/mount

7.6G    /var/lib/kubelet/pods/c914919d-a817-4f05-80de-630afae6c582/volumes/kubernetes.io~csi/pvc-e4dd2e05-72d0-45e3-b652-84384126c87a/mount/prometheus-db
```
It says that 7.6Gi are being used. 
I have periodically checked the usage of the volume and the Prometheus logs, and the retention size configuration is deleting the old chunks. So, the metrics volume never achieves more than 8Gi.

However, this is the "du" output of the folder where Longhorn saves the replica:
```bash
$ sudo du -h -d 1 /var/lib/longhorn/replicas/pvc-e4dd2e05-72d0-45e3-b652-84384126c87a-26071f05

9.8G    /var/lib/longhorn/replicas/pvc-e4dd2e05-72d0-45e3-b652-84384126c87a-26071f05
```
It says that 9.8Gi are being used instead. The same value gets shown in the Longhorn UI in the Actual Size field of the Prometheus volume.

My first question is: what are these extra 2.2Gi (the difference on the size of the replica folder with the size of the pod volume folder)? Metadata of the replica/volume? The content of the volume/replica automatic snapshots or replica rebuilds that are automatically done by Longhorn?

I have also seen the following configuration on the node.io.longhorn CRD and also on the Nodes section in the Longhorn UI: the storageReserved field.

These are the node.io.longhorn CRD contents of one of my cluster nodes:
```json
{
    "apiVersion": "longhorn.io/v1beta1",
    "kind": "Node",
    "metadata": {
        [...]
        "name": "node1",
        "namespace": "longhorn-system",
        "resourceVersion": "11753876",
        "uid": "d15361f9-d5ab-4ed0-9e96-89b81ef45253"
    },
    "spec": {
        "allowScheduling": true,
        "disks": {
            "default-disk-fd0100000000": {
                "allowScheduling": true,
                "evictionRequested": false,
                "path": "/var/lib/longhorn/",
                "storageReserved": 20153421004,
                "tags": null
            }
        },
       [...]
    },
    "status": {
       [...]
        "diskStatus": {
            "default-disk-fd0100000000": {
              [...]
                "scheduledReplica": {
                    [...]
                    "pvc-e4dd2e05-72d0-45e3-b652-84384126c87a-r-5cee4239": 10737418240
                    [...]
                },
                "storageAvailable": 35337011200,
                "storageMaximum": 67178070016,
                "storageScheduled": 52613349376
            }
        },
        [...]
}
```

The storageRequested field is set to "20153421004", which is 18.8Gi in my case.
From various other issues and posts, I found that this value is calculated from the 30% of the total size of the disk where Longhorn is configured. In my case, the /var partition of my machine has a total size of almost 63Gi, so the calculation is correct.

The difference between the size of the replica folder and the size of the pod volume folder is somehow related with this configuration value? 
What happens if I set a storageRequested value of 500Mi instead? Would that mean that, if the change is applied, the difference between the size of the replica folder and the size of the pod volume folder will be no more than 500Mi (as there is no more additional space requested)?
Is there a way to configure this "storageRequested " parameter from the Longhorn configuration? I install Longhorn using the Helm Chart. The only way I found was to manually edit the node.io.longhorn CRD spec (using "kubectl edit" or "kubectl patch").

If the difference between the size of the replica folder and the size of the pod volume folder is not related with the storageRequested config, and its related to the own Longhorn replica snapshot/rebuild, is there a way to disable this process? Or if there is a way to know the real volume usage without looking at the mount folder?

## Environment

 - Longhorn version: v1.1.3
 - Kubernetes version: K3s v1.20.4+k3s1
 - Node config
   - OS type and version: CentOS Linux release 7.9.2009 (Core)
   - CPU per node: 4 vCPU
   - Memory per node: 8 GB
   - Disk type: Hard Disk
   - Network bandwidth and latency between the nodes: -
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare vSphere

**Comment by derekbit** [comment]
> My first question is: what are these extra 2.2Gi (the difference on the size of the replica folder with the size of the pod volume folder)? Metadata of the replica/volume? The content of the volume/replica automatic snapshots or replica rebuilds that are automatically done by Longhorn?

The volume is 10Gi. Although you set the retention size configuration in the application, the data from the application are not always written to the pre-allocated blocks (even though the files are deleted), and they are maybe written to the new blocks of the volume. Thus, you cannot control the growth of volume from the application level or filesystem level.

**Comment by derekbit** [comment]
> The storageRequested field is set to "20153421004", which is 18.8Gi in my case.
From various other issues and posts, I found that this value is calculated from the 30% of the total size of the disk where Longhorn is configured. In my case, the /var partition of my machine has a total size of almost 63Gi, so the calculation is correct.

> The difference between the size of the replica folder and the size of the pod volume folder is somehow related with this configuration value?

Do you mean `storageReserved`?
If yes, this value is set for avoiding the exhaustion of the disk space for longhorn data.
You can please refer to the space usage information https://longhorn.io/docs/1.2.3/volumes-and-nodes/node-space-usage/#whole-cluster-space-usage.

The volume's replica, snapshot and so on are stored in the disk space.

**Comment by derekbit** [comment]
> if there is a way to know the real volume usage without looking at the mount folder?

Kubelet exposes [kubelet_volume_stats_* metrics](https://github.com/kubernetes/kubernetes/blob/4b24dca228d61f4d13dcd57b46465b0df74571f6/pkg/kubelet/metrics/collectors/volume_stats.go#L27). The metrics measure PVC’s filesystem related information inside a Longhorn block device.

Ref: https://longhorn.io/docs/1.2.3/monitoring/kubelet-volume-metrics/#about-kubelet-volume-metrics
