### ISSUE TITLE
[BACKPORT-v1.2.x] Fix flaky test result for test_replica_auto_balance_zone_best_effort

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#3663]
Backport https://github.com/longhorn/longhorn-tests/pull/892

https://github.com/longhorn/longhorn/issues/3649

**Comment by cchien816** [comment]
Verifie on v.1.2x-head in local environment passed with command `pytest -k test_replica_auto_balance`

Will close this issue, thank you.
