### ISSUE TITLE
[TASK] RWX volume performance measurement and investigation

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#3665]
## What's the task? Please describe

Several issues reported the performance concerns of the RWX volumes, so this task is to measure and investigate the rwx volume performance and to see if there is any potential optimization.

**Comment by derekbit** [comment]
**m3.small.x86 Environment**

Cloud provider: Equinix
Machine: m3.small.x86
Kubernetes: v1.23.6+rke2r2
Nodes: 3 (each node is a master and also a worker)
OS: Ubuntu 22.04 / 5.15.0-33-generic
Storage: 1 SSD (Micron_5300_MTFD)
Network throughput between nodes (tested by iperf over 60 seconds): 15.0 Gbits/sec
Longhorn volume: RWX

![image](https://user-images.githubusercontent.com/12527233/173339690-ad3bc9f1-7599-4540-9035-8b1537a76ae3.png)

**Comment by innobead** [comment]
Just added it to https://github.com/longhorn/longhorn/wiki/Performance-Benchmark.
