### ISSUE TITLE
[BACKPORT][BUG][v1.2.4] Instance managers and Pods with attached volumes restarted every hour

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3671]
ref https://github.com/longhorn/longhorn/issues/2820

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn Version: `v1.2.4-rc1`

Steps to test:

https://github.com/longhorn/longhorn/issues/2820#issuecomment-1054558178
