### ISSUE TITLE
[BUG] Volume not become scheduling after change over provisioning form 0 to  100

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#3678]
## Describe the bug

From [e2e](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/53/testReport/junit/tests/test_node/test_replica_scheduler_update_over_provisioning/) and can manually reproduced

## To Reproduce

1. Set `Storage Over Provisioning Percentage` to 0
2. Create volume, volume can not be scheduled
3. Set `Storage Over Provisioning Percentage` to 100
4. Observe volume, still volume can not be scheduled

## Expected behavior

Volume should become `Schedulable`

## Log or Support bundle

N/A

## Environment

 - Longhorn version: master-head 0301
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster: 1 
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: suse-sles-15-sp3-v20210622-hvm-ssd-x86_64 
   - Disk type(e.g. SSD/NVMe): SSD
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 1

## Additional context

Might related to https://github.com/longhorn/longhorn/issues/3626 and

**Comment by joshimoo** [comment]
This should probably also be tackled as part of volume creation, left a comment about some ideas for this here: https://github.com/longhorn/longhorn/issues/3626#issuecomment-1043206989

**Comment by cchien816** [comment]
**Validate on master head 20220506
Result Pass**

1. Follow test steps in [description](https://github.com/longhorn/longhorn/issues/3678#issue-1154804712), volume will become schedulable after change `Storage Over Provisioning Percentage` from 0 to 100
2. e2e [passed](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/113/testReport/tests/test_node/test_replica_scheduler_update_over_provisioning/) in master branch
