### ISSUE TITLE
[BUG] Volume fails to schedule when set Eviction Requested from true to false on node which contains replica

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#3679]
## Describe the bug

From [e2e](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/53/testReport/junit/tests/test_node/test_node_eviction_no_schedulable_node/) 

Volume fails to schedule when set Eviction Requested from true to false on node which contains replica

Can reproduce by hand and not happen on V1.2.3

## To Reproduce

1. Disable scheduling on node 3.
2. Create pv, pvc, pod with volume of 2 replicas.
3. Write some data and get the checksum.
4. Disable scheduling and set 'Eviction Requested' to 'true' on node 1.
5. Volume should be failed to schedule new replica.
6. Set 'Eviction Requested' to 'false' to cancel node 1 eviction.
7. Volume still not scheduled

## Expected behavior

Volume should become scheduled

## Log or Support bundle

N/A

## Environment

 - Longhorn version: master-head 03/09/2022
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: suse-sles-15-sp3-v20210622-hvm-ssd-x86_64 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 1

## Additional context

Might related to https://github.com/longhorn/longhorn/issues/3626

**Comment by innobead** [comment]
@cchien816 Please remember to mention the version/branch. This should be the master/1.3.0.

**Comment by PhanLe1010** [comment]
This PR should also fix this issue https://github.com/longhorn/longhorn-manager/pull/1256

**Comment by PhanLe1010** [comment]
The root cause was we currently only enqueue replica when a node/disk have EvictionRequested is `true`: https://github.com/longhorn/longhorn-manager/blob/c04eac1c804597c78d5962c1758e8ed80d2abb37/controller/replica_controller.go#L727

We don't resync replica when a node/disk have EvictionRequested reset to `false`

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with master-head images (v1.3.0-dev, 20220407),  now volume schedule work as expected.

Worker node: 3
Volume Replica set to: 2
Node 3: disable scheduling
Volume under test(VUT): healthy

Node 1 setting change | Enable | Disable
:- | :-: | :-:
Node Scheduling | False | True 
Eviction Requested | False | True 
- Result: VUT remain healthy but Replica Scheduling Failure
Additionally, within 2 nodes disable schedule newly created volume(replica set to 2) will remain degraded and having warning unable to schedule)

Node 1 setting change | Enable | Disable
:- | :-: | :-:
Node Scheduling | False | True 
Eviction Requested | True | False
- Result: VUT health without warning
