### ISSUE TITLE
[BUG] Delete a uploading backing image, the corresponding LH temp file is not deleted

### ISSUE THREAD

**Issue by w13915984028** [longhorn/longhorn#3682]
## Describe the bug

When Harvester delete an uploading image, the corresponding LH temp file is not deleted

## To Reproduce

1. Create image (uploading from local file) in Harvester
![image](https://user-images.githubusercontent.com/31133476/156145912-2bd7066c-2b13-4191-8ae9-e67d4eea8af7.png)

2. An uploading image is created, a temp file is created

![image](https://user-images.githubusercontent.com/31133476/156145827-14c37e93-4a48-484c-98cc-9c1ff3dbe1d0.png)

![image](https://user-images.githubusercontent.com/31133476/156145781-51d5482f-0703-4e73-9636-425f68713c7e.png)

3. Delete the uploading
![image](https://user-images.githubusercontent.com/31133476/156146119-7fc0210d-a6d6-4294-9518-2434b4554363.png)

4. LH left the temp file uncleared
![image](https://user-images.githubusercontent.com/31133476/156146229-dd010cc6-f3d3-455e-824f-381c67cc890f.png)
![image](https://user-images.githubusercontent.com/31133476/156146285-fd66f29b-efcd-430b-a1e2-aa10d7b00d2d.png)

## Expected behavior

Temp file should be cleared asap and correctly.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment
Harvester v1.0.0 master-head with longhorn embedded.

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

### Issue Description
After the investigation, there are two possibility which could cause tmp files left on the host.
1. Delete the BackingImage CR when it is still in progress. This will delete every information and the data source pod immediately which make Longhorn have no chance to cleanup the tmp files. (This issue)
2. Data source pod is deleted during the uploading. Currently Longhorn only marks BackingImage failed with msg: `"the pod dedicated to prepare the first backing image file is being deleted"`. But there is no handle function for this case to cleanup the tmp files
 
### Fix Plan
- [] ~~Add finalizer for BackingImage to prevent it from being deleted when it is still in-progress~~ BackingImage has finalizer
- [] Controller should handle tmp file cleanup when deleting BackingImage
- [] Add handle function in controller to cleanup the tmp files if data source pod is deleted accidentally

### Implementation
- add `CleanUpOrphan` api in manager-server
- introduce a new state for BackingImageDataSource: `FailedAndCleanUp`

For Case 2: DS Pod is deleted in the progress
- invoke `CleanUpOrphan` when BackingImageManager find that
    - BackingImageDataSource CurrentState is failed and Transferred is false ([ref](https://github.com/longhorn/longhorn-manager/blob/master/controller/backing_image_manager_controller.go#L678))
    - change the BackingImageDataSource state to `FailedAndCleanUp`

For Case 1:  BackingImage is deleted in the progress
BackingImageController
- before removing the finalizer, update BackingImageDataSource status to `Failed`, this will trigger the above behavior to clean up the tmp files
- can remove the finalizer when BackingImageDataSource is `FailedAndCleanUp`

**Comment by w13915984028** [comment]
@shuo-wu as discussed in slack. I also re-tested in Harvester, it is reproduceable.

**Comment by w13915984028** [comment]
It seems, when `backing-image-ds-`  POD is deleted, the process does not get chance to execute the deferred function.


Doubt: for `backing-image-manager/ds-`, is `tini `working as expected?  @shuo-wu @innobead 

comparing `backing-image-` and `harvester`, `in harvester, tini is process 0, but in backing-image, tini is not there`, `backing-image-manager is process 0`

![image](https://user-images.githubusercontent.com/31133476/156245540-92e5ea39-9749-4fae-b627-4c6915076dce.png)


![image](https://user-images.githubusercontent.com/31133476/156244562-ed17fdd3-1c3e-448e-a4bc-0bda877b9718.png)

![image](https://user-images.githubusercontent.com/31133476/156244587-bacb5520-b431-40b2-8049-cddcf71175ce.png)



https://github.com/harvester/harvester/blob/master/package/Dockerfile

`ENTRYPOINT ["entrypoint.sh"]`
entrypoint.sh
```
#!/bin/bash
set -e
exec tini -- harvester "${@}"
```
![image](https://user-images.githubusercontent.com/31133476/156244977-bc6c8bb2-b694-42a5-9ef9-68f03da2ef04.png)

**Comment by w13915984028** [comment]
I force refreshing the webUI of Harvester, which causes the on-going uploading failed
![image](https://user-images.githubusercontent.com/31133476/156247249-49ee366e-36a1-492d-9c20-378fd1c03be7.png)

The `kubectl exec backing-image-ds-default-image-lgrk4 -n longhorn-system -it -- /bin/bash`, login in POD, showed: `command terminated with exit code 137`
root@backing-image-ds-default-image-lgrk4:/# ls /tini -alt
-rwx--x--x 1 root root 24064 Apr 21  2018 /tini
root@backing-image-ds-default-image-lgrk4:/# ` command terminated with exit code 137`
harv2:~ #

**Comment by ChanYiLin** [comment]
@w13915984028
you are right, the defer function was incorrect and not working before.
It is fixed by this PR [#58](https://github.com/longhorn/backing-image-manager/pull/58) now.

I have tested it in longhorn 1.4.0 by
1. upload a backing image
2. refresh the browser page to interrupt the upload process
3. get the following logs from data source pod 
```
jacklin@jacklin:~/Documents/suse/longhorn_example$ k logs -f po/backing-image-ds-large-break -n longhorn-system
time="2023-02-20T14:16:39Z" level=debug msg="Sync Service: initialized" component=sync-server listen="0.0.0.0:8001"
time="2023-02-20T14:16:39Z" level=info msg="Started sync server at 0.0.0.0:8001"
time="2023-02-20T14:16:40Z" level=debug msg="DataSource Service: initializing" component=data-source-service diskUUID=6f5d8094-9e8d-4daa-9d01-2787a190d113 expectedChecksum= filePath=/data/tmp/large-break-370dfff3 name=large-break parameters="map[]" sourceType=upload uuid=370dfff3
time="2023-02-20T14:16:40Z" level=debug msg="DataSource Service: initialized" component=data-source-service diskUUID=6f5d8094-9e8d-4daa-9d01-2787a190d113 expectedChecksum= filePath=/data/tmp/large-break-370dfff3 name=large-break parameters="map[]" sourceType=upload uuid=370dfff3
time="2023-02-20T14:16:40Z" level=info msg="Started data source server at 0.0.0.0:8000"
time="2023-02-20T14:16:41Z" level=debug msg="DataSource Service: datasource file is state pending, the processing is not begin yet" component=data-source-service diskUUID=6f5d8094-9e8d-4daa-9d01-2787a190d113 expectedChecksum= filePath=/data/tmp/large-break-370dfff3 name=large-break parameters="map[]" sourceType=upload uuid=370dfff3
time="2023-02-20T14:16:42Z" level=debug msg="DataSource Service: datasource file is state pending, the processing is not begin yet" component=data-source-service diskUUID=6f5d8094-9e8d-4daa-9d01-2787a190d113 expectedChecksum= filePath=/data/tmp/large-break-370dfff3 name=large-break parameters="map[]" sourceType=upload uuid=370dfff3
time="2023-02-20T14:16:43Z" level=debug msg="DataSource Service: datasource file is state pending, the processing is not begin yet" component=data-source-service diskUUID=6f5d8094-9e8d-4daa-9d01-2787a190d113 expectedChecksum= filePath=/data/tmp/large-break-370dfff3 name=large-break parameters="map[]" sourceType=upload uuid=370dfff3
time="2023-02-20T14:16:44Z" level=debug msg="DataSource Service: datasource file is state pending, the processing is not begin yet" component=data-source-service diskUUID=6f5d8094-9e8d-4daa-9d01-2787a190d113 expectedChecksum= filePath=/data/tmp/large-break-370dfff3 name=large-break parameters="map[]" sourceType=upload uuid=370dfff3
time="2023-02-20T14:16:45Z" level=debug msg="DataSource Service: datasource file is state pending, the processing is not begin yet" component=data-source-service diskUUID=6f5d8094-9e8d-4daa-9d01-2787a190d113 expectedChecksum= filePath=/data/tmp/large-break-370dfff3 name=large-break parameters="map[]" sourceType=upload uuid=370dfff3
time="2023-02-20T14:16:46Z" level=debug msg="DataSource Service: forwarding upload request to sync server http://0.0.0.0:8001/v1/files?action=upload&expected-checksum=&file-path=%2Fdata%2Ftmp%2Flarge-break-370dfff3&size=3864182784&uuid=370dfff3" component=data-source-service diskUUID=6f5d8094-9e8d-4daa-9d01-2787a190d113 expectedChecksum= filePath=/data/tmp/large-break-370dfff3 name=large-break parameters="map[]" sourceType=upload uuid=370dfff3
time="2023-02-20T14:16:46Z" level=debug msg="Sync Service: initializing sync file /data/tmp/large-break-370dfff3" component=sync-server listen="0.0.0.0:8001"
time="2023-02-20T14:16:46Z" level=info msg="Sync Service: start uploading file" component=sync-server listen="0.0.0.0:8001"
time="2023-02-20T14:16:46Z" level=info msg="SyncingFile: cannot to reuse the existing file, will clean it up then start processing: stat /data/tmp/large-break-370dfff3: no such file or directory" component=sync-file filePath=/data/tmp/large-break-370dfff3 uuid=370dfff3
time="2023-02-20T14:16:46Z" level=debug msg="DataSource Service: datasource file is state starting, the processing is not begin yet" component=data-source-service diskUUID=6f5d8094-9e8d-4daa-9d01-2787a190d113 expectedChecksum= filePath=/data/tmp/large-break-370dfff3 name=large-break parameters="map[]" sourceType=upload uuid=370dfff3
time="2023-02-20T14:16:47Z" level=info msg="SyncingFile: start to copy data to sync file" component=sync-file filePath=/data/tmp/large-break-370dfff3 uuid=370dfff3
2023/02/20 14:17:00 http: proxy error: context canceled
time="2023-02-20T14:17:00Z" level=error msg="SyncingFile: failed to process sync file: failed to copy the data with timeout: unexpected EOF" component=sync-file filePath=/data/tmp/large-break-370dfff3 uuid=370dfff3
```
The error was captured, the cleanup process was executed and the temp file was deleted.

Would you mind following the above instructions to see if this scenario works?

**Comment by ChanYiLin** [comment]
@w13915984028
Currently, the temp files are not cleaned up might because
1. data source pod is force deleted in the middle and has no chance to do the defer function 
2. data source process is effected and has no change to do the defer function (might be this case: [https://github.com/harvester/harvester/issues/3450#issuecomment-1431746258](https://github.com/harvester/harvester/issues/3450#issuecomment-1431744793) )

**Comment by ChanYiLin** [comment]
In Longhorn, when uploading the file, there will be a progress bar and the page will be lock to prevent other operations.
In Harverster doc, there is also a note about this.
https://docs.harvesterhci.io/v1.1/upload-image#upload-images-via-local-file

Can you help me to verify 
if it is still possible to delete image while it is in uploading state in current Harvester version?

**Comment by chriscchien** [comment]
Verified in longhorn master `15701b`
Result **Pass**

During back image uploading (temp file appeared in folder `/var/lib/longhorn/tmp`)
- Delete the backing image data source pod, pod delete success,  the file in `/var/lib/longhorn/tmp` deleted.
- Delete the CR `backingimage`, CR `backingimage` delete success, the file in `/var/lib/longhorn/tmp` deleted.
