### ISSUE TITLE
[BACKPORT][v1.2.4] Fix condition unmarshal failure & implement volume recurring job label clean up

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#3684]
https://github.com/longhorn/longhorn/issues/3517
https://github.com/longhorn/longhorn/issues/3470

**Comment by khushboo-rancher** [comment]
Regarding https://github.com/longhorn/longhorn/issues/3517

Validation : **Pass** on v1.2.4-rc1

When the last recurring job is deleted, the jobs are getting deleted from the respective volumes.

**Comment by khushboo-rancher** [comment]
Regarding https://github.com/longhorn/longhorn/issues/3470

Validation : Pass on v1.2.4-rc1

When the setting `Allow Recurring Job While Volume Is Detached` is enabled, recurring backup job is able to take backup of a detached volume.
Also, our nightly test `test_recurring_jobs_when_volume_detached_unexpectedly` has been passing
