### ISSUE TITLE
[BACKPORT][BUG][v1.2.4] longhorn-ui crashlooping when running RKE2 with cis-1.5 profile

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#3688]
#3658

**Comment by khushboo-rancher** [comment]
Validated with RKE2 v1.23.4+rke2r1 and Longhorn v1.2.x-head

Validation - **Pass**

I was able to reproduce the problem on the same cluster, on upgrading it to v1.2.x-head. Problem got resolved.
Validated with fresh installation as well.
