### ISSUE TITLE
[IMPROVEMENT][BACKPORT][v1.1.4] Upgrade path improvement

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3694]
https://github.com/longhorn/longhorn/issues/3087

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with v1.1.x-head image on 3 + 30 cluster.
Upgrade from v1.1.3, with rwx, statefulset examples running.
The upgrade can be finished without any problem.

Additional note: the RWX workload may require to scale down first but the volume itself remain healthy.
