### ISSUE TITLE
After an unplanned outage in 1 node, volumes stuck attaching detaching..

### ISSUE THREAD

**Issue by IJOL** [longhorn/longhorn#3695]
Attached support bundle..

---
Version: `v1.0.2`

**Comment by derekbit** [comment]
We've made lots of improvements and bug fixes in v1.2.3. Can you upgrade to 1.2.x?

**Comment by IJOL** [comment]
IO know i know, but for now i'm stuck with that version is a production
server, just know we are trying to do a blue/green upgrade of the entire
cluster.. but if we can repair the actual this cluster our upgrade will be
much more relaxed... just to say ..


Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega

**Comment by IJOL** [comment]
https://drive.google.com/file/d/14MSttmbfDaBasMLNkizAD-itA-JO6mZc/view?usp=sharing

**Comment by IJOL** [comment]
That last url is my support bundle..

**Comment by jenting** [comment]
Are you able to upgrade longhorn to at least v1.1.x version?
We had lots of enhancement/improvement related to the volume attaching/detaching issue.

**Comment by IJOL** [comment]
We installed a k8s 1.21 cluster with the latest from longhorn as asked and did the same thing, reboot a node, and volumes stuck attaching/detaching  attached the new support bundle..
[longhorn-support-bundle_5e7a556d-050b-4d39-83f7-0ba4dfe4eeb6_2022-03-14T16-19-23Z.zip](https://github.com/longhorn/longhorn/files/8246724/longhorn-support-bundle_5e7a556d-050b-4d39-83f7-0ba4dfe4eeb6_2022-03-14T16-19-23Z.zip)
.

**Comment by jenting** [comment]
Could you provide the volume name? Or all volume are in attaching/detaching state?
