### ISSUE TITLE
[BUG] Failed to attach "Block device" frontend volume

### ISSUE THREAD

**Issue by iamatulsingh** [longhorn/longhorn#3706]
## Describe the bug

I've installed longhorn my local minikube cluster (kubernetes version 1.21) with 5 nodes. I've installed open-iscsi on each node and iscsid is running fine on each node. 
The issue is: 
Whenever I'm creating a pvc for a pod, it's always using Block device as frontend and that too is not attaching to the pod. It's health is keep failing after every few seconds.
There are no options to use iscsi Frontend from pvc.
Also why Block device is not working? 

## To Reproduce

1. Go to longhorn ui
2. Click on "create volume"
3. Perform use Block device as frontend and attach a volume to any node.
4. See error unhealthy volume just after trying to attach.

## Expected behavior

It should be working with Block device as frontend.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.2.3
 - Installation method: helm
 - Kubernetes distro: minikube and k3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: ubuntu
   - CPU per node: 2
   - Memory per node: 500gGi
   - Disk type(e.g. SSD/NVMe): HDD
   - Network bandwidth between the nodes: 20Mbps
 - Underlying Infrastructure: Baremetal
 - Number of Longhorn volumes in the cluster: 3

**Comment by jenting** [comment]
Please check the discussion thread https://github.com/longhorn/longhorn/discussions/2702

**Comment by iamatulsingh** [comment]
Thanks for the response. I'll close this issue.
