### ISSUE TITLE
[BUG] CSI volume clone from existing volume stuck in degraded

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#3707]
## Describe the bug

Create CSI volume with existing volume as data source hangs in the degraded state.

This issue was raised in [csi-sanity test](https://github.com/longhorn/longhorn/issues/2271) and seems to be side effects from https://github.com/longhorn/longhorn-manager/pull/1210. It works if change the resync time back to 30 seconds.

## To Reproduce

1. Follow steps in [doc](https://longhorn.io/docs/1.2.3/snapshots-and-backups/csi-volume-clone/) to create source-pvc then cloned-pvc.
2. The cloned-pvc volume stuck in state degraded.

## Expected behavior
Finish volume clone then detaches volume.

## Log or Support bundle

`n/a`

## Environment

`n/a`

## Additional context

https://github.com/longhorn/longhorn/issues/3629

**Comment by c3y1huang** [comment]
cc @PhanLe1010

**Comment by PhanLe1010** [comment]
From my testing, it looks like this one is duplicated of https://github.com/longhorn/longhorn/issues/3692. There are 2 cases:
* If the source volume is attached at the time, the clone is ok
* If the source volume is detached at the time, the clone is failed. This is similar to https://github.com/longhorn/longhorn/issues/3692
Are you seeing the same thing @c3y1huang

**Comment by c3y1huang** [comment]
> Are you seeing the same thing @c3y1huang

Looks like is the same as https://github.com/longhorn/longhorn/issues/3692.
