### ISSUE TITLE
[BACKPORT][v1.2.4] High CPU usage by instance manager

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3709]
## Describe the bug

https://github.com/longhorn/longhorn/issues/3636

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn version: `v1.2.4-RC1`

Steps to test:

- Create a longhorn volume and attach it to a node.
- Go into the instance-manager-e- POD on the node that the volume is attached to.
- Run ps ax and find the PID of the /engine-binaries/longhornio-longhorn-engine-master-head/longhorn controller process.
- kill -9 the process.
- Run top and look at the CPU utilization of tgt. 

Note: longhorn can relaunch the engine process on this node and make that volume available on this node again.
 If that happens, the CPU utilization stop being 100%.

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with v1.2.4-rc1 image on v1.21.9+rke2r1 cluster.

More detail please reference to the main issue: https://github.com/longhorn/longhorn/issues/3636#issuecomment-1065933289

---
Additional note on testing:
When the system already had problem with high tgtd usage, there is chance it occupied the resource and resulting in worker node unable to work properly. A quick resolution will be ssh into the problematic node then: $ sudo pkill -9 -f tgtd
And potentially live upgrade the engine image to the latest version.
