### ISSUE TITLE
[BACKPORT][v1.1.4] High CPU usage by instance manager

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3710]
## Describe the bug

https://github.com/longhorn/longhorn/issues/3636

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn version: `v1.1.x-head`

Steps to test:

- Create a longhorn volume and attach it to a node.
- Go into the instance-manager-e- POD on the node that the volume is attached to.
- Run ps ax and find the PID of the /engine-binaries/longhornio-longhorn-engine-v1.1.x-head/longhorn controller process.
- kill -9 the process.
- Run top and look at the CPU utilization of tgt. 

Note: longhorn can relaunch the engine process on this node and make that volume available on this node again.
 If that happens, the CPU utilization stop being 100%.
