### ISSUE TITLE
[BUG][v1.2.4-rc1] An attached healthy volume unable to recovered from a disconnection node

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#3712]
## Describe the bug

This bug is related to longhorn manual test - [Node disconnection test case 1](https://longhorn.github.io/longhorn-tests/manual/pre-release/node/node-disconnection/)
When an attached volume encounters a node network disconnection, even though the network works again and the node recovers from "Down - NotReady" to "Schedulable - Ready", the volume still keeps in "Detached - Faulted"

## To Reproduce

1. Disable auto-salvage in setting
2. Create a new volume from UI
3. Create PV/PVC for this volume from UI
4. Create a pod with the PVC created in the previous step and use this pod to keep writing data into the volume
5. ssh into the volume-attached node, disconnect it's network for 100 seconds, using[ the script ](https://github.com/longhorn/longhorn/files/4864127/network_down.sh.zip) and this command: 
`sudo nohup ./network_down.sh 100`
6. Go back to longhorn UI, the node would become "Down - NotReady", and the volume would become "Attached - Unknown" and then "Detached - Faulted"
7. After 100 seconds, the network becomes normal again, and the node would recover to "Schedulable - Ready" again, but the volume remains in "Detached - Faulted".

## Expected behavior

The volume should automatically reattach and become healthy again.

## Log or Support bundle

[longhorn-support-bundle](https://github.com/longhorn/longhorn/files/8203937/longhorn-support-bundle_3c9f52ea-fd85-4129-b22e-b8711f73470d_2022-03-08T08-04-14Z.zip)

## Environment

 - Longhorn version: v1.2.4-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl 
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.23.1+k3s2
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: ubuntu 20.04
   - CPU per node: 4
   - Memory per node: 16G
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster: 1

**Comment by yangchiu** [comment]
[longhorn-support-bundle_3c9f52ea-fd85-4129-b22e-b8711f73470d_2022-03-08T08-04-14Z.zip](https://github.com/longhorn/longhorn/files/8203937/longhorn-support-bundle_3c9f52ea-fd85-4129-b22e-b8711f73470d_2022-03-08T08-04-14Z.zip)

**Comment by yangchiu** [comment]
After discussed with @PhanLe1010 , the behavior is expected because the user disabled the auto-salvage setting so Longhorn doesn't do auto-reattachment https://github.com/longhorn/longhorn-manager/blob/a535727173a2415b1ae0f268bffc12b041180fb0/controller/volume_controller.go#L1125

**Comment by innobead** [comment]
> After discussed with @PhanLe1010 , the behavior is expected because the user disabled the auto-salvage setting so Longhorn doesn't do auto-reattachment [longhorn/longhorn-manager@`a535727`/controller/volume_controller.go#L1125](https://github.com/longhorn/longhorn-manager/blob/a535727173a2415b1ae0f268bffc12b041180fb0/controller/volume_controller.go#L1125)

@yangchiu should we update the test cases correspondingly?

**Comment by yangchiu** [comment]
@innobead @khushboo-rancher I've created [PR #907](https://github.com/longhorn/longhorn-tests/pull/907) to refine and add new test case for this. Thank you!
