### ISSUE TITLE
[BUG] longhornio/longhorn-manager:master-head currently CrashLoopBackOff-ing

### ISSUE THREAD

**Issue by clemenko** [longhorn/longhorn#3716]
## Describe the bug

Latest Longhorn yaml install is generating a crashloopbackoff in the manager pod. 

```
clempro:clemenko rke2 ( 167.99.123.4:6443:longhorn-system ) $ kubectl logs longhorn-manager-8p8k8   -n longhorn-system
2022/03/08 15:59:28 proto: duplicate proto type registered: VersionResponse
W0308 15:59:28.065106       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-03-08T15:59:28Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr, ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/*': No such file or directory\n, error exit status 2"
I0308 15:59:28.113534       1 leaderelection.go:242] attempting to acquire leader lease  longhorn-system/longhorn-manager-upgrade-lock...
time="2022-03-08T15:59:28Z" level=info msg="New upgrade leader elected: k3s-80fe"
I0308 15:59:48.180404       1 leaderelection.go:252] successfully acquired lease longhorn-system/longhorn-manager-upgrade-lock
time="2022-03-08T15:59:48Z" level=info msg="Start upgrading"
time="2022-03-08T15:59:48Z" level=info msg="setting default-engine-image not found"
time="2022-03-08T15:59:48Z" level=error msg="Upgrade failed: upgrade API version failed: cannot create CRDAPIVersionSetting: the server could not find the requested resource (post settings.longhorn.io)"
time="2022-03-08T15:59:48Z" level=info msg="Upgrade leader lost: k3s-b469"
time="2022-03-08T15:59:48Z" level=fatal msg="Error starting manager: upgrade API version failed: cannot create CRDAPIVersionSetting: the server could not find the requested resource (post settings.longhorn.io)"
```

## To Reproduce

1. deploy longhorn with `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml`
2. watch pods `kubectl get pod -n longhorn-system |grep manager` 

## Expected behavior

expected to not crashloopbackoff

## Log or Support bundle

See error above. 

## Environment

 - Longhorn version: latest (1.2.3?)
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 1 - single
   - Number of worker node in the cluster: 1 - single
 - Node config
   - OS type and version: Rocky
   - CPU per node: 4
   - Memory per node: 8
   - Disk type(e.g. SSD/NVMe): "cloud"
   - Network bandwidth between the nodes: HUGE
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): DigitalOcean
 - Number of Longhorn volumes in the cluster: None

## Additional context

Installing 1.2.2 works just fine. This appears to be an issue within the image itself. 
Changing the image gets past the first crash, But there is more. 
STEPS:
```bash
# get logs
kubectl logs -n longhorn-system $(kubectl get pod -n longhorn-system |grep manager | awk '{print $1}')

# show image
kubectl get ds -n longhorn-system longhorn-manager -ojson | jq .spec.template.spec.containers[].image

# downrev to 1.2.2. 
kubectl set image -n longhorn-system ds/longhorn-manager longhorn-manager=longhornio/longhorn-manager:v1.2.2
```

**Comment by clemenko** [comment]
`https://raw.githubusercontent.com/longhorn/longhorn/v1.2.3/deploy/longhorn.yaml` is working. So it must be the image reference on the `https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml` file.

**Comment by clemenko** [comment]
Commit - https://github.com/longhorn/longhorn/commit/7be7109e65f82630fff6e45317b6984917e4747d broke it.

**Comment by jenting** [comment]
Thanks for the reporting.

You are using the master-head which is our current developer branch and also we change our branch policy these two days.
If you want to use a stable version, please use v1.2.3 instead of the master branch.

We'll check it.

**Comment by innobead** [comment]
The issue has been fixed in the master branch for development purpose.
