### ISSUE TITLE
[BACKPORT][1.1.x] Restored volume show 'scheduled' with 2 replicas running and 1 unscheduled replica 

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#3727]
https://github.com/longhorn/longhorn/issues/3183

**Comment by kaxing** [comment]
Still failing, will keep on eyes to the next test results. Ref.: https://ci.longhorn.io/job/public/job/v1.1.x/job/v1.1.x-longhorn-tests-sles-amd64/73/testReport/tests/test_basic/test_allow_volume_creation_with_degraded_availability_restore_s3_/

**Comment by kaxing** [comment]
Turns out  expect_fail=2 is missing in common.wait_for_replica_scheduled(...) under v1.1.x branch
PR: https://github.com/longhorn/longhorn-tests/pull/949

**Comment by kaxing** [comment]
Validation - **PASSED**

No more failing with _test_allow_volume_creation_with_degraded_availability_restore_ after the fix backport to v1.1.x-head image.
Reference test result: [here](https://ci.longhorn.io/job/public/job/v1.1.x/job/v1.1.x-longhorn-upgrade-tests-sles-amd64/85/testReport/tests/test_basic/)
