### ISSUE TITLE
[DOC] Alert LonghornNodeDown example in documentation doesn't work

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#3729]
@Turb0Fly commented on [Sat Sep 25 2021](https://github.com/longhorn/website/issues/382)

The prometheus alert LonghornNodeDown as seen on https://longhorn.io/docs/1.2.0/monitoring/alert-rules-example/ does not work.
`longhorn_node_total - (count(longhorn_node_status{condition="ready"}==1) OR on() vector(0))`

The metric **longhorn_node_total** does not exist. When querying the metrics , **longhorn_node_count_total** is there.  However, replacing the metric with the correct one in the expression does not work either.  When forcing a node down, the alert is never fired but querying the metric gets the correct value.

Using Longhorn 1.1.0
Rancher 2.5.8
Rancher Monitoring 14.5.100

We need an expression that will fire only when a node is not ready and not just on count, e.g. getting an alert when value is 0.

FWIW, I came up with something that works :
`(avg(longhorn_node_count_total) or on() vector(0)) - (count(longhorn_node_status{condition="ready"} == 1) or on() vector(0)) > 0`

**Comment by kaxing** [comment]
Validation - **PASSED**

PrometheusRule examples can be deployed on following combination:
- Longhorn v1.2.4 via Marketplace
- Prometheus within rancher-monitoring:100.1.2+up19.0.3 via Marketplace
- Rancher v2.6.3
On RKE1 v1.18.20 cluster (5 nodes)

There are still a few things to config to make the alerting system work, as mentioned in this doc: [here](https://longhorn.io/docs/1.2.4/monitoring/prometheus-and-grafana-setup/) Attached the Alerts page screenshot for the future reference: ![image](https://user-images.githubusercontent.com/602540/162872209-8dd77c2f-7f4e-4a3e-9f94-feefe95c196b.png)
