### ISSUE TITLE
[BUG] Unable to download qcow2 backing image when using EXT4 in s390x arch

### ISSUE THREAD

**Issue by thehejik** [longhorn/longhorn#3733]
## Describe the bug
On attempt to download qcow2 backing image (which is typically not divisible by 4K blocks) over Longhorn webUI the download is failing with following message visible in webUI:
![lh_backing](https://user-images.githubusercontent.com/12828077/157470549-2580023f-064d-4773-a0ff-0d0b82b5194b.png)

When doing the same on XFS or BTRFS there is no problem. Also no problem when downloading RAW image which has exactly 16MB.

This is the qcow2 image used https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.qcow2

Using custom Longhorn build and images close to v1.2.3 for s390x from https://raw.githubusercontent.com/raulcabello/longhornz/main/longhorn.yaml

## To Reproduce

1. Go to 'Setting/Backing Image'
2. Click on 'Create Backing Image', Fill in Name: testimage, URL: https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.qcow2, SHA512 checksum is not needed
3. Go to Backing Image overview page and click `testimage` name to see the failure

## Expected behavior

The image should be downloaded successfully as on others FS

## Log or Support bundle
[longhorn-support-bundle_58e20c46-1341-4220-b393-eff1dbccb1ce_2022-03-10T08-23-59Z.zip](https://github.com/longhorn/longhorn/files/8221530/longhorn-support-bundle_58e20c46-1341-4220-b393-eff1dbccb1ce_2022-03-10T08-23-59Z.zip)

## Environment

 - Longhorn version: close to v1.2.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2 v1.21.9+rke2r1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: SLE15 SP2 with kernel-default-5.3.18-24.96.1 and EXT4 rootfs
   - CPU per node: 2
   - Memory per node: 8
   - Disk type(e.g. SSD/NVMe): DASD
   - Network bandwidth between the nodes: 1gb
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): bm/zVM
 - Number of Longhorn volumes in the cluster: 1

## Additional context

So far I reproduced this issue only on `s390x` architecture. For some strange reason it works with EXT4 loopimage mounted on /var/lib/longhorn

Edit: I was unable to repro this issue on my custom ext4 jeos for x86_64 - it also has `journal_incompat_revoke` journal feature flag set.

**Comment by innobead** [comment]
cc @shuo-wu

**Comment by shuo-wu** [comment]
This feature works fine in my test cluster, which is using EXT4 filesystem and Longhorn v1.2.4-master-head. I don't think there is any difference for this feature since v1.2.3.
The error is from the checksum computing function. It seems this function cannot read data from the downloaded file: https://github.com/longhorn/backing-image-manager/blob/0103fcb66924708d0aa4ca3e64576711b3cced00/pkg/util/util.go#L51
Does your filesystem disable some features like extent (sparse file support)?

**Comment by derekbit** [comment]
Probably related to the direct IO alignment and a platform specific issue.
https://github.com/longhorn/backing-image-manager/blob/0103fcb66924708d0aa4ca3e64576711b3cced00/pkg/util/util.go#L40

Maybe we replace the direct io with buffer io for calculating checksum.

**Comment by shuo-wu** [comment]
We can provide a test cmd that wraps this function but with both kinds of IO processors for the test.

**Comment by jenting** [comment]
@thehejik 
Are you able to compile the below code on the s390x machine?
```go
package main

import (
	"crypto/sha512"
	"encoding/hex"
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/longhorn/sparse-tools/sparse"
)

func main() {
	flag.Parse()

	fmt.Printf("Calculate the %q checksum\n", flag.Arg(0))

	checksum, err := GetFileChecksum(flag.Arg(0))
	fmt.Printf("Checksum: %v, err %v\n", checksum, err)
}

func GetFileChecksum(filePath string) (string, error) {
	f, err := sparse.NewDirectFileIoProcessor(filePath, os.O_RDONLY, 0)
	if err != nil {
		return "", err
	}
	defer f.Close()

	// 4MB
	buf := make([]byte, 1<<22)
	h := sha512.New()

	for {
		nr, err := f.Read(buf)
		if err != nil {
			if err != io.EOF {
				return "", err
			}
			break
		}
		h.Write(buf[:nr])
	}

	return hex.EncodeToString(h.Sum(nil)), nil
}
```

You could save above to `main.go`, and compile it by `go build main.go` on the s390x machine.
After that, run `./main <path-to-the-backing-image-file> to see if we can get the result of the sha512 checksum.

Besides that, could you check the command `sha512sum` of the backing image file as well? `sha512sum <path-to-the-backing-image-file>`.

**Comment by thehejik** [comment]
> Are you able to compile the below code on the s390x machine?
```
./main ./parrot.qcow2 
Calculate the "./parrot.qcow2" checksum
Checksum: , err read ./parrot.qcow2: invalid argument
```
When doing the same on working btrfs I see valid `sha512sum` in the outptut.

> Besides that, could you check the command sha512sum of the backing image file as well? sha512sum <path-to-the-backing-image-file>.
```
sha512sum ./parrot.qcow2 
bd79ab9e6d45abf4f3f0adf552a868074dd235c4698ce7258d521160e0ad79ffe555b94e7d4007add6e1a25f4526885eb25c53ce38f7d344dd4925b9f2cb5d3b  ./parrot.qcow2
```

Note: before that I did:
```
cd /var/lib/longhorn # within ext4 rootfs
wget https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.qcow2
```

**Comment by thehejik** [comment]
Today we tried with Mike to mount an external SCSI/FC drive partitioned and formatted as EXT4 to `/var/lib/longhorn` (before deploying longhorn) on s390x machine and everything went ok and I was unable to reproduce this issue.

It was also working fine when I was doing something similar with EXT4 loopimage by `mount -oloop <custom-image.ext4> /var/lib/longhorn`.

**Comment by thehejik** [comment]
We just tried another attempt with attaching an extra /dev/dasdb1 partition formatted as EXT4 to `/var/lib/longhorn` and the **problem appeared again**.

So it looks like an issue with kernel and/or module for EXT4 filesystem when using DASD drives on s390x.

Using SLE15-SP2 with `kernel-default-5.3.18-24.96.1` on zVM hypervisor from SUSE R&D infra.

**Comment by thehejik** [comment]
I've migrated my Longhorn node from SLE15-SP3 to SLE15-SP4 by `zypper migration` and it started to work. There is newer `kernel-default-5.14.21-150400.12.2` rpm installed.

```bash
lh-node:/var/lib/longhorn # df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/dasdb1     9.8G   63M  9.3G   1% /var/lib/longhorn

lh-node:/var/lib/longhorn # mount | grep /var/lib/longhorn
/dev/dasdb1 on /var/lib/longhorn type ext4 (rw,relatime)

lh-node:/var/lib/longhorn # zypper se -s kernel-default | grep ^i
i+ | kernel-default  | package | 5.14.21-150400.12.2 | s390x  | SLE-Module-Basesystem15-SP4-Pool
```

**Comment by thehejik** [comment]
A new patched kernel for SLE15-SP2 and SP3 has been provided and tested - now we need just need to wait for next kernel maintainance update. I will close this issue once the kernel will roll out.

**Comment by thehejik** [comment]
Fixed kernel is available for SP3 already and the fix is working, closing.
