### ISSUE TITLE
[FEATURE] Expect LH has a lightweight solution for volume failure like "insufficient storage"

### ISSUE THREAD

**Issue by w13915984028** [longhorn/longhorn#3734]
## Is your feature request related to a problem? Please describe

When a PVC has a bigger size than capacity, LH volume will not be able to provision this PVC. But in current master-head implementation, the PVC still goes into "Bound" status, no clear error message is available. It is not user friendly.

For a workaround, Harvester tried a solution in bellow issue and PR.  The main drawback is that Harvester will have full set of LH volumes, and they are frequently updated, this will increase CPU and memory usage. And Harvester deeply couples with LH implementation.
https://github.com/harvester/harvester/issues/1695
https://github.com/harvester/harvester/pull/1923

LH issue:
https://github.com/longhorn/longhorn/issues/3529

## Describe the solution you'd like
Expect LH will update PVC annotation direclty.

When LH volume is in not usable status (e.g. insufficient storage), update PVC annotations
`annotations["harvesterhci.io/volume-status"] = "insufficient storage"` (and all other useful status description)

When LH volume is in ready state, update PVC annotations:
```
annotations["harvesterhci.io/volume-status"] = ""
or delete this annotation
```

After LH updates the PVC accordingly, Harvester will further update them to VM, and display in WebUI.  (as per https://github.com/harvester/harvester/pull/1923)

## Describe alternatives you've considered
PVC status reflects the real status directly.

## Additional context

Prefer to targeting it on the next LH v1.2.5 and Harvester v1.0.2 release

**Comment by jenting** [comment]
Link to the Slack discussion thread https://suse.slack.com/archives/C02DR3N5T24/p1646904584658299.

**Comment by derekbit** [comment]
Already implemented in https://github.com/longhorn/longhorn/issues/3529.
