### ISSUE TITLE
[BUG]Does not work when I changethe  default settings in in values.yml

### ISSUE THREAD

**Issue by refaelb** [longhorn/longhorn#3735]
## To Reproduce

1. Go to 'values.yaml'
2. Click on 'configure default settings'
3. Perform 'change ~ to /my-path '
4. its nut use with this path, its work with /var/lib/longhotn

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by jenting** [comment]
I _guess_ you're using helm upgrade. Then, you can check the [KB](https://longhorn.io/kb/troubleshooting-default-settings-do-not-persist/).

**Comment by refaelb** [comment]
> I _guess_ you're using helm upgrade. Then, you can check the [KB](https://longhorn.io/kb/troubleshooting-default-settings-do-not-persist/).

it exists in configmap but longhorn nut use with this changes

**Comment by jenting** [comment]
> > I _guess_ you're using helm upgrade. Then, you can check the [KB](https://longhorn.io/kb/troubleshooting-default-settings-do-not-persist/).
> 
> it exists in configmap but longhorn nut use with this changes

Yes. It's duplicated to #2570. It will be fixed with Longhorn v1.3, and we provide a workaround for v1.2.x and v1.1.x and older versions, please ref to issue #3578.

**Comment by jenting** [comment]
Close this issue first. feel free to reopen it.
