### ISSUE TITLE
[IMPROVEMENT] Set Backup Target programatically

### ISSUE THREAD

**Issue by emazzotta** [longhorn/longhorn#3737]
## Is your improvement request related to a feature? Please describe

As far as I know, there is currently no other way to set the "Backup Target" other than manually, in the Longhorn UI.

## Describe the solution you'd like

I'd like everything in my infrastructure to be fully automated and therefore would prefer if the "Backup Target" e.g. an s3 path could be set somehow via `kubectl` or some other way that I could easily integrate into Terraform. An obvious way to configure this to me would be a `ConfigMap`.

**Comment by jenting** [comment]
You could configure the Setting CR directly.
```shell
kubectl get settings.longhorn.io backup-target -n longhorn-system
kubectl get settings.longhorn.io backup-target-credential-secret -n longhorn-system
```

**Comment by emazzotta** [comment]
Ah, of course, that's perfect! Thank you.
