### ISSUE TITLE
[BUG] Longhorn does not recognize node's expanded disk size

### ISSUE THREAD

**Issue by rgutierrez2004** [longhorn/longhorn#3739]
I have a 3-node RKE2 cluster with Rancher 2.6.2 and Longhorn 1.2.2. Initially, the nodes root disk size was 99GB. At this point in time Longhorn was reporting 90GB of Storage Max capacity.

Then, I extended the root disk size in all nodes to 120GB. Everything is working ok, and the OS recognized the new size (extended partition and root XFS filesystem), however in Longhorn 1.2.2 UI, when clicking on Edit Node and Disk option, the Storage Max field still shows the old disk size 90GB?

Why Longhorn does not recognize the new disk size? I even re-start all cluster nodes but not luck still the same size in Longhorn UI.

**Comment by jenting** [comment]
The slack thread https://rancher-users.slack.com/archives/CC2UQM49Y/p1647201646194799

**Comment by jenting** [comment]
The function is periodically called by node_controller, the resync time is 30 seconds.

https://github.com/longhorn/longhorn-manager/blob/b661af0c6315d0f910a3400b650b0e9fba2df577/controller/node_controller.go#L51

**Comment by rgutierrez2004** [comment]
If the function is called every 30sec, so then Longhorn use this info to update the Storage Max field in the UI?

As per my previous comment:  clicking on Edit Node and Disk option, the Storage Max field still shows the old size 90GB?
Why this field does not show an increased value now that the disk size is 120GB in the node?

This is what kubelet reports on each node:
```
k describe nodes
...
Capacity:
  ephemeral-storage:  117215020Ki
...
Allocatable:
  ephemeral-storage:  115117868Ki
...
```

**Comment by rgutierrez2004** [comment]
Hi there, after some digging find out that my browser was pointing to a cloned instance while my terminal connected to the instance where I extended the disk.

After, pointing to the right instance, Lonhorn UI shows the updated disk space.

Apologies. Please proceed to close this issue.
