### ISSUE TITLE
[TASK] Improve longhorn-tests Jenkins console output

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#3740]
## What's the task? Please describe

The current console output of longhorn tests on Jenkins is not good enough.
Currently there is no useful information printed during the test but it just prints "Longhorn tests still running ... rechecking in 5m" like:
```
++ kubectl get pods longhorn-test --no-headers=true
++ awk '{print $3}'
++ grep -v Running
+ [[ -z '' ]]
+ echo 'Longhorn tests still running ... rechecking in 5m'
+ sleep 5m
```

## Describe the items of the task (DoD, definition of done) you'd like

Ideally the console output should print out any useful messages in **"real-time"** to let team members know the current situation of this test and give a prompt response to it instead of just waiting for it completed in vain.
For example, it should print:
(1) What test case is executing now
(2) The test steps have been successfully executed
(3) Any error messages
(4) Any variables name, parameter values or status that could be useful when debugging

PR: https://github.com/longhorn/longhorn-tests/pull/912

**Comment by innobead** [comment]
cc @meldafrawi

**Comment by yangchiu** [comment]
[#912](https://github.com/longhorn/longhorn-tests/pull/912)
[#921](https://github.com/longhorn/longhorn-tests/pull/921)
