### ISSUE TITLE
[BUG] If backing image downloading fails on one node, it doesn't try on other nodes.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3746]
## Describe the bug

If backing image downloading fails on one node, it doesn't try on other nodes.

## To Reproduce

1. Create a set up of 3 workers node and make the file `/data/longhorn-disk.cfg` not accessible.
2. Go to backing image page.
3. Download backing image from url `https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.qcow2`
4. The download of backing image fails with error `the pod dedicated to prepare the first backing image file failed: time="2022-03-16T00:58:58Z" level=fatal msg="Error running data-source command: cannot find disk config file /data/longhorn-disk.cfg: open /data/longhorn-disk.cfg: permission denied."`
5. Once a pod fails, the other pod doesn't try to download it, they stuck in `File processing is not started`

<img width="827" alt="Screen Shot 2022-03-15 at 5 58 52 PM" src="https://user-images.githubusercontent.com/60111667/158496746-afe962ed-f4f5-4ee8-acd6-1205f65e16a3.png">

## Expected behavior

If a pod fails to download the backing image, Longhorn should try to download it on other nodes.

## Log or Support bundle
```
[longhorn-manager-fn7hp] time="2022-03-16T01:06:38Z" level=error msg="Unexpected pod phase Failed, will update backing image manager to state error" backingImageManager=backing-image-manager-c00e-20e4 controller=longhorn-backing-image-manager diskUUID=20e4676a-ff1f-471b-8762-f1984d612a25 node=ip-172-31-42-245 nodeID=ip-172-31-42-245 
[longhorn-manager-fn7hp] time="2022-03-16T01:06:38Z" level=info msg="Event(v1.ObjectReference{Kind:\"BackingImageManager\", Namespace:\"longhorn-system\", Name:\"backing-image-manager-c00e-20e4\", UID:\"40f9fbc9-3cb5-48e2-9c7e-65a42ffb640c\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"666277\", FieldPath:\"\"}): type: 'Warning' reason: 'Update' Unexpected pod phase Failed, will update backing image manager to state error" 
[longhorn-manager-fn7hp] time="2022-03-16T01:06:38Z" level=info msg="Deleting pod before recreation" backingImageManager=backing-image-manager-c00e-20e4 controller=longhorn-backing-image-manager diskUUID=20e4676a-ff1f-471b-8762-f1984d612a25 node=ip-172-31-42-245 nodeID=ip-172-31-42-245 
[longhorn-manager-fn7hp] time="2022-03-16T01:06:38Z" level=error msg="No pod for backing image manager with state error, will update to state error" backingImageManager=backing-image-manager-c00e-20e4 controller=longhorn-backing-image-manager diskUUID=20e4676a-ff1f-471b-8762-f1984d612a25 node=ip-172-31-42-245 nodeID=ip-172-31-42-245 
[longhorn-manager-fn7hp] time="2022-03-16T01:06:38Z" level=info msg="Start to create backing image manager pod" backingImageManager=backing-image-manager-c00e-20e4 controller=longhorn-backing-image-manager diskUUID=20e4676a-ff1f-471b-8762-f1984d612a25 node=ip-172-31-42-245 nodeID=ip-172-31-42-245 
[longhorn-manager-fn7hp] time="2022-03-16T01:06:38Z" level=info msg="Event(v1.ObjectReference{Kind:\"BackingImageManager\", Namespace:\"longhorn-system\", Name:\"backing-image-manager-c00e-20e4\", UID:\"40f9fbc9-3cb5-48e2-9c7e-65a42ffb640c\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"666314\", FieldPath:\"\"}): type: 'Warning' reason: 'Update' No pod for backing image manager with state error, will update to state error" 
[longhorn-manager-fn7hp] time="2022-03-16T01:06:38Z" level=info msg="Created backing image manager pod" backingImageManager=backing-image-manager-c00e-20e4 controller=longhorn-backing-image-manager diskUUID=20e4676a-ff1f-471b-8762-f1984d612a25 node=ip-172-31-42-245 nodeID=ip-172-31-42-245 
[longhorn-manager-fn7hp] time="2022-03-16T01:06:38Z" level=info msg="Event(v1.ObjectReference{Kind:\"BackingImageManager\", Namespace:\"longhorn-system\", Name:\"backing-image-manager-c00e-20e4\", UID:\"40f9fbc9-3cb5-48e2-9c7e-65a42ffb640c\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"666314\", FieldPath:\"\"}): type: 'Normal' reason: 'Create' Creating backing image manager pod backing-image-manager-c00e-20e4 for disk 20e4676a-ff1f-471b-8762-f1984d612a25 on node ip-172-31-42-245. Backing image manager state will become starting" 
[longhorn-manager-xrz42] time="2022-03-16T01:06:39Z" level=error msg="No pod for backing image manager with state error, will update to state error" backingImageManager=backing-image-manager-c00e-7fc2 controller=longhorn-backing-image-manager diskUUID=7fc2ec1b-94c1-4206-a714-96d9fc05848a node=ip-172-31-39-14 nodeID=ip-172-31-39-14 
[longhorn-manager-xrz42] time="2022-03-16T01:06:39Z" level=info msg="Start to create backing image manager pod" backingImageManager=backing-image-manager-c00e-7fc2 controller=longhorn-backing-image-manager diskUUID=7fc2ec1b-94c1-4206-a714-96d9fc05848a node=ip-172-31-39-14 nodeID=ip-172-31-39-14 
[longhorn-manager-xrz42] time="2022-03-16T01:06:39Z" level=info msg="Event(v1.ObjectReference{Kind:\"BackingImageManager\", Namespace:\"longhorn-system\", Name:\"backing-image-manager-c00e-7fc2\", UID:\"facb32f7-a3b0-49ed-aa3a-b324aa0840a5\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"666311\", FieldPath:\"\"}): type: 'Warning' reason: 'Update' No pod for backing image manager with state error, will update to state error" 
[longhorn-manager-xrz42] time="2022-03-16T01:06:39Z" level=info msg="Created backing image manager pod" backingImageManager=backing-image-manager-c00e-7fc2 controller=longhorn-backing-image-manager diskUUID=7fc2ec1b-94c1-4206-a714-96d9fc05848a node=ip-172-31-39-14 nodeID=ip-172-31-39-14 
[longhorn-manager-xrz42] time="2022-03-16T01:06:39Z" level=info msg="Event(v1.ObjectReference{Kind:\"BackingImageManager\", Namespace:\"longhorn-system\", Name:\"backing-image-manager-c00e-7fc2\", UID:\"facb32f7-a3b0-49ed-aa3a-b324aa0840a5\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"666311\", FieldPath:\"\"}): type: 'Normal' reason: 'Create' Creating backing image manager pod backing-image-manager-c00e-7fc2 for disk 7fc2ec1b-94c1-4206-a714-96d9fc05848a on node ip-172-31-39-14. Backing image manager state will become starting
```

## Environment

 - Longhorn version: v1.2.4-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl

**Comment by shuo-wu** [comment]
The culprit is **SELinux**. After running `chcon -Rt svirt_sandbox_file_t /var/lib/longhorn` on the node host, the backing image manager pod can be launched without the privileged mode.

In this cluster, the default type of the data path is `container_var_lib_t`.

**Comment by kaxing** [comment]
I am able to reproduce this with v1.2.4 GA on a rke2 cluster install on centos 8.2 nodes with selinux default with enforcing.
![image](https://user-images.githubusercontent.com/602540/160131735-0aae846f-3607-4eb9-873c-980f0a4fe9ad.png)

Also, with the permission change mentioned above, the situation can be resolved:
```
Original permission:
# ls -dZ /var/lib/longhorn/
system_u:object_r:container_var_lib_t:s0 /var/lib/longhorn/

Workaround/Update permission:
# chcon -Rt svirt_sandbox_file_t /var/lib/longhorn
#  ls -dZ /var/lib/longhorn/
system_u:object_r:container_file_t:s0 /var/lib/longhorn
```

**Comment by ChanYiLin** [comment]
After discussion with @shuo-wu 

BackingImage has been refactored during 1.2.x -> 1.3.x 

For the current implementation, if  the `longhorn-disk.cfg`  file is locked on all the nodes in the cluster
BackingImage shouldn’t be able to create data source pod and start download the image
because controller can’t pick up a ready node at beginning

To test the retry scenario, one can try
1. Create a set up of 3 workers node and make the folder /var/lib/longhorn/tmp not accessible.
By `chattr +i /var/lib/longhorn/tmp`
2. Download backing image from url `https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.qcow2`
3. This failed the download process since it couldn't create download file in the tmp folder
4. the BackingImage became failed and then retry again 
    - longhorn-manager will show that the BackingImage is in retry window, and will be retried later

cc @khushboo-rancher

**Comment by innobead** [comment]
@ChanYiLin Do we have any e2e test cases for these behaviors? If not, please add these cases, then QA can help with implementation.

**Comment by ChanYiLin** [comment]
@innobead 
we have manual e2e test for this - **Backing image with an invalid URL schema**
https://longhorn.github.io/longhorn-tests/manual/pre-release/ha/backing-image-error-reporting-and-retry/

**Comment by innobead** [comment]
Perfect, then we don't need to do anything, because the manual test cases will be implemented later.

**Comment by innobead** [comment]
@khushboo-rancher as discussed, @ChanYiLin clarified the context, so let's close this if this is expected.

**Comment by khushboo-rancher** [comment]
Yeah, this is should be good to close now.
