### ISSUE TITLE
[IMPROVEMENT] Disable snapshot revert and Allow snapshot removal when the snapshot marked as Removed

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3748]
## Is your improvement request related to a feature? Please describe

Once the snapshots are marked as Removed, 

1. The corresponding files may be modified. e.g., Snapshot prune #3613  Hence, Longhorn should not allow reverting to this kind of snapshot.
2. Allows users to be able to delete the snapshots which have been marked as removed already

## Describe the solution you'd like

Check snapshots are marked as Removed or not before starting revert in the manager/engne/replica.

## Additional context

This is the prerequisite of #3613

**Comment by innobead** [comment]
@shuo-wu or @smallteeths Please help provide the testing steps for @longhorn/qa . Thanks.

**Comment by smallteeths** [comment]
My self-test steps are a little more cumbersome.
1. Use longhorn v1.2.x backend, access to volume detail page.
2. Create a recurringJob with Every minute.  Wait for the backup to be created.
3. Delete the backup, turn on the `Show System Hidden` At this time, the snapshot with removed as true will be displayed on the ui
4. Upgrade longhorn to the latest version. 
5. The snapshot marked as removed from the ui will have a delete action. Executing the delete action will successfully delete the snaoshot.

The step to generate The snapshot marked as removed is a little tedious.
@shuo-wu do you have a better way?

**Comment by shuo-wu** [comment]
I am thinking if we need separate tickets to track the UI improvement. I just realized that it's mainly related to removed snapshots rather than the snapshot revert...

As for the manual test, I just add a manual test doc in PR: https://github.com/longhorn/longhorn-tests/pull/908
PTAL

**Comment by innobead** [comment]
Actually, there are two parts in that PR, but it should be better to separate to 2 commits instead. 

1. About snapshot revert not allowed if the snapshot marked as removed, refer to https://github.com/longhorn/longhorn-ui/pull/500/files#diff-a0582eff58af741a5961513d74ba61d87411c56210796365ad1f04413f5dbe84. 
2. The second is about removing snapshots marked as removed. 

Let's just update this ticket for these changes instead of creating another new one.

**Comment by cchien816** [comment]
**Validated on master-head 20220427
Result Pass**

1. After snapshot marked as Removed and attach volume again in Maintenance mode, form volume detail page there not exist revert option on removed snapshot (enable Show System Hidden:).

    If use API to revert the marked as Removed snapshot , will get below message to refuse to revert.  
```
 {"actions":{},"code":"Server Error","detail":"","links":{"self":"http://10.42.0.9:9500/v1/volumes/vol1"},"message":"fail to revert snapshot: not revert to snapshot '287f34a1-8b65-47a3-83ee-7a252112d2ce' for volume 'vol1' since it's marked as Removed","status":500,"type":"error"}
```

2. After snapshot marked as Removed and volume not in Maintenance mode, form volume detail page there was an option to delete the snapshot which marked as Removed (enable Show System Hidden:).
 
   From API `http://<LH IP>/v1/volumes/<volume name>?action=snapshotList ` can see the deleted snapshot not appear in the list

3. Test **pass** with steps in https://github.com/longhorn/longhorn-tests/pull/908/files#diff-4e9d8bf0de6afe45555d97257f922cad10a0df9814767623b2688c4bf9d0ae93

4. e2e case [passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1117/)
