### ISSUE TITLE
[QUESTION] How to upgrade from Rancher Catalog (new version not shown)

### ISSUE THREAD

**Issue by voarsh2** [longhorn/longhorn#3757]
## Question
I have Longhorn and Longhorn CRD's installed from the Rancher repository.
However, I am seeing various versions to choose from on each app, but not the latest one:

![image](https://user-images.githubusercontent.com/60437695/159051826-35520878-f0ca-483b-89f1-4a41bc5df162.png)
![image](https://user-images.githubusercontent.com/60437695/159051911-f49b7986-750d-462d-870f-6f1884f54127.png)

![image](https://user-images.githubusercontent.com/60437695/159051968-ea1ebc17-c805-4b1b-b2dc-874306858c59.png)

Am I missing something?
FYI I also manually refreshed the repositories as well.

**Comment by jenting** [comment]
The last one you expected is v1.2.4? 

If yes, it's because these PRs have not been merge and release
- https://github.com/rancher/charts/pull/1793
- https://github.com/rancher/charts/pull/1794

**Comment by voarsh2** [comment]
> The last one you expected is v1.2.4?

Yep.
Hmm... my bad. I thought a release and the UI showing a release meant this was already done.

**Comment by jenting** [comment]
Well, Longhorn releases a new release but we need a couple of days to wait for the Rancher release the new chart.

**Comment by jenting** [comment]
The Longhorn v1.2.4 is in the Rancher catalog app already (for cluster management).
The Longhorn v1.2.4 in the Rancher marketplace needs to wait for Rancher to release v2.6.4 (for cluster explorer).

Close it.
