### ISSUE TITLE
AttachVolume.Attach failed for volume "[pvc-name]" : rpc error: code = NotFound desc = node [nodename] not found[QUESTION] 

### ISSUE THREAD

**Issue by Nedved-liao** [longhorn/longhorn#3758]
## Question1
> Pod cannot be created using volumeClaimTemplates configuration
## Question2
> My k8s cluster has 10 worker nodes，3 storage nodes. I need to deploy all those components on these three storage nodes？or deploy all those components on all these 13 nodes？

## Environment

 - Longhorn version: 1.2.4
 - Kubernetes version: v1.18.6
 - Node config
   - OS type and version redhat8

## Additional context
![image](https://user-images.githubusercontent.com/35453327/159115530-1eb2b4c7-3107-47cd-b690-eb67c3700f9a.png)

**Comment by Nedved-liao** [comment]
use helm deploy. only modified longhornManager. set nodeSelector on storage nodes
![image](https://user-images.githubusercontent.com/35453327/159115662-dda6c9d9-d64c-40b2-a339-9374ccaf2d3d.png)

the pod run status
[root@xlonghorn-lab ~]# kubectl get po -A|grep long
longhorn-system             csi-attacher-84d5cbc45c-jnmm9                1/1     Running            0          41h
longhorn-system             csi-attacher-84d5cbc45c-nnrl7                1/1     Running            0          41h
longhorn-system             csi-attacher-84d5cbc45c-qmxw8                1/1     Running            0          41h
longhorn-system             csi-provisioner-769b876f87-7pv2p             1/1     Running            0          41h
longhorn-system             csi-provisioner-769b876f87-8xmm8             1/1     Running            0          41h
longhorn-system             csi-provisioner-769b876f87-znpml             1/1     Running            0          41h
longhorn-system             csi-resizer-7974f5cfb9-cpsbl                 1/1     Running            0          41h
longhorn-system             csi-resizer-7974f5cfb9-rcsj6                 1/1     Running            0          41h
longhorn-system             csi-resizer-7974f5cfb9-zfv28                 1/1     Running            0          41h
longhorn-system             csi-snapshotter-77dfd9dcd9-5h5nm             1/1     Running            0          41h
longhorn-system             csi-snapshotter-77dfd9dcd9-9tbnw             1/1     Running            0          41h
longhorn-system             csi-snapshotter-77dfd9dcd9-d2dk9             1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-22nhw               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-42wlr               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-4fmzb               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-5jp89               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-5l6wz               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-5vmkx               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-6dlww               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-6fskt               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-7r8sn               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-9gb2f               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-ckk2f               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-d9dcn               1/1     Running            1          41h
longhorn-system             engine-image-ei-0fa63ad4-jhq2g               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-kfblt               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-kh2v9               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-ksfdc               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-kw64x               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-pn9qj               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-s2gdt               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-slbkc               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-slfjf               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-tcdgh               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-wkmzl               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-xcg2b               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-xf27t               1/1     Running            0          41h
longhorn-system             engine-image-ei-0fa63ad4-zh7tp               1/1     Running            0          41h
longhorn-system             instance-manager-e-47908b3d                  1/1     Running            0          3m21s
longhorn-system             instance-manager-e-4b8e933d                  1/1     Running            0          3m30s
longhorn-system             instance-manager-e-cb9dfeeb                  1/1     Running            0          3m24s
longhorn-system             instance-manager-r-590c5f2c                  1/1     Running            0          3m30s
longhorn-system             instance-manager-r-e3b2af45                  1/1     Running            0          3m24s
longhorn-system             instance-manager-r-f18ac451                  1/1     Running            0          3m21s
longhorn-system             longhorn-csi-plugin-2p679                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-47bqt                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-6vtrv                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-6xh62                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-725b2                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-77fpz                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-7zrrb                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-8725k                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-9zrvm                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-blzx9                    2/2     Running            3          41h
longhorn-system             longhorn-csi-plugin-bzbsc                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-ctds2                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-d2xtd                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-ds7hq                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-gmjct                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-kjfbf                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-lgnwl                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-mm6md                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-smtzt                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-srbqp                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-tj97b                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-tnc2s                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-vbzj2                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-wm7h8                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-xm4xj                    2/2     Running            0          41h
longhorn-system             longhorn-csi-plugin-xrtll                    2/2     Running            0          41h
longhorn-system             longhorn-driver-deployer-75b5696dd6-j75km    1/1     Running            0          41h
longhorn-system             longhorn-manager-4blj4                       1/1     Running            0          40h
longhorn-system             longhorn-manager-4k2kt                       1/1     Running            0          40h
longhorn-system             longhorn-manager-kxjtq                       1/1     Running            0          30h
longhorn-system             longhorn-ui-75b9bdbf8d-5zkb8                 1/1     Running            0          41h

**Comment by jenting** [comment]
Longhorn contains two categories components
- user deployed components (e.g: Manager, Driver Deployer, UI)
- system managed components (e.g: Instance Manager, Engine Image, CSI Driver, etc.)

For the system managed components, it needs to deploy on all the nodes which require the volume.
In your case, the instance manager and CSI attacher/provisioner/resizer/snapshotter doesn't deploy on all nodes.

You could refer the [doc](https://longhorn.io/docs/1.2.4/advanced-resources/deploy/taint-toleration/).

**Comment by Nedved-liao** [comment]
> Longhorn contains two categories components
> 
> * user deployed components (e.g: Manager, Driver Deployer, UI)
> * system managed components (e.g: Instance Manager, Engine Image, CSI Driver, etc.)
> 
> For the system managed components, it needs to deploy on all the nodes which require the volume. In your case, the instance manager and CSI attacher/provisioner/resizer/snapshotter doesn't deploy on all nodes.
> 
> You could refer the [doc](https://longhorn.io/docs/1.2.4/advanced-resources/deploy/taint-toleration/).

it work！ think
