### ISSUE TITLE
[BUG] [HELM-CHART] Resources in values.yaml are not used in templates

### ISSUE THREAD

**Issue by c-thiel** [longhorn/longhorn#3759]
## Describe the bug
Currently the resources in the values.yaml are not used in the template of the helm chart:
https://github.com/longhorn/charts/blob/94ebc926edb034bbb7b79d3528816982db37a890/charts/longhorn/values.yaml#L164
-> Search here for resources and find nothing:
https://github.com/longhorn/charts/blob/master/charts/longhorn/templates/daemonset-sa.yaml

I am not sure if this is the right place to put it - in longhorn/charts no issues can be opened.

**Comment by jenting** [comment]
Duplicate to #3186

**Comment by jenting** [comment]
> Duplicate to #3186

Let's use #3186 to track this issue, close this one.

Thank you for the reporting.
