### ISSUE TITLE
[IMPROVEMENT][BACKPORT][v1.1.4] Disable snapshot revert and Allow snapshot removal when the snapshot marked as Removed

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3764]
https://github.com/longhorn/longhorn/issues/3748

**Comment by cchien816** [comment]
**Validated on v1.1.x-head 20220504
Result Pass**

After snapshot marked as Removed and attach volume again in Maintenance mode, form volume detail page there not exist revert option on removed snapshot (enable Show System Hidden:).

1. If use API to revert the marked as Removed snapshot , will get below message to refuse to revert.

```
{"actions":{},"code":"Server Error","detail":"","links":{"self":"http://10.42.0.11:9500/v1/volumes/vol1"},"message":"fail to revert snapshot: not revert to snapshot '3416c31b-1158-45e6-8bb3-4dfb7c7dd2ea' for volume 'vol1' since it's marked as Removed","status":500,"type":"error"}
```

2. After snapshot marked as Removed and volume not in Maintenance mode, form volume detail page there was an option to delete the snapshot which marked as Removed (enable Show System Hidden:).

    From API `http://<LH IP>/v1/volumes/<volume name>?action=snapshotList` can see the deleted snapshot not appear in the list

3. Test pass with steps in https://github.com/longhorn/longhorn-tests/pull/908/files#diff-4e9d8bf0de6afe45555d97257f922cad10a0df9814767623b2688c4bf9d0ae93

4. No e2e test script on longhorn-test v1.1.x
