### ISSUE TITLE
[TASK] Collect and analyze reasons for unstable k8s cluster when running longhorn-tests on Jenkins

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#3770]
## What's the task? Please describe

It seems sometimes when we run longhorn-tests on Jenkins, the process of terraform generating k8s cluster for running the test is not stable, so sometimes the test is failed due to the cluster generating is failed, or sometimes the cluster is problematic so the test result based on this cluster is unexpected.

## Describe the items of the task (DoD, definition of done) you'd like

But what causes these cluster-related problems is still unclear.
If encounter any similar situations, **_record/collect the logs here_** so we can further analyze if there's anything we can do to prevent it happen again.

**Comment by yangchiu** [comment]
https://github.com/longhorn/longhorn/issues/3851

**Comment by innobead** [comment]
cc @cchien816 @kaxing

**Comment by yangchiu** [comment]
https://github.com/longhorn/longhorn/issues/3856

**Comment by yangchiu** [comment]
Error from server: Get "https://ip-10-0-2-202:10250/containerLogs/default/longhorn-test/longhorn-test?follow=true&sinceSeconds=10": dial tcp: lookup ip-10-0-2-202: no such host

only happened 2 times:
2022/04/17
https://ci.longhorn.io/job/public/job/v1.1.x/job/v1.1.x-longhorn-tests-sles-amd64/74/consoleFull
2022/02/26:
https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/51/consoleFull

Exception when delete node test disks {'address': '10.42.2.5', 'allowScheduling': True, 'conditions': {'MountPropagation': {'lastProbeTime': '', 'lastTransitionTime': '2022-04-17T04:58:28Z', 'message': '', 'reason': '', 'status': 'True'}, 'Ready': {'lastProbeTime': '', 'lastTransitionTime': '2022-04-17T04:58:27Z', 'message': 'Node ip-10-0-2-202 is ready', 'reason': '', 'status': 'True'}, 'Schedulable': {'lastProbeTime': '', 'lastTransitionTime': '2022-04-17T04:58:27Z', 'message': '', 'reason': '', 'status': 'True'}}, 'disks': {'default-disk': {'allowScheduling': False, 'conditions': {'Ready': {'lastProbeTime': '', 'lastTransitionTime': '2022-04-17T10:01:07Z', 'message': 'Disk default-disk(/var/lib/longhorn/) on node ip-10-0-2-202 is ready', 'reason': '', 'status': 'True'}, 'Schedulable': {'lastProbeTime': '', 'lastTransitionTime': '2022-04-17T10:01:07Z', 'message': 'Disk default-disk(/var/lib/longhorn/) on node ip-10-0-2-202 is schedulable', 'reason': '', 'status': 'True'}}, 'diskUUID': 'f00c0994-1347-439b-8ac7-35008f65ae94', 'evictionRequested': False, 'path': '/var/lib/longhorn/', 'scheduledReplica': {'vol-disk-r-4ca3e13f': 1073741824}, 'storageAvailable': 33135001600, 'storageMaximum': 42915049472, 'storageReserved': 12874514841, 'storageScheduled': 1073741824, 'tags': None}, 'extra-disk': {'allowScheduling': True, 'conditions': {'Ready': {'lastProbeTime': '', 'lastTransitionTime': '2022-04-17T10:03:42Z', 'message': 'Disk extra-disk(/tmp/longhorn-test/vol-disk) on node ip-10-0-2-202 is not ready: Get disk information error: cannot get disk info of directory /tmp/longhorn-test/vol-disk: Failed to execute: nsenter [--mount=/host/proc/1/ns//mnt stat -fc {"path":"%n","fsid":"%i","type":"%T","freeBlock":%f,"totalBlock":%b,"blockSize":%S} /tmp/longhorn-test/vol-disk], output , stderr, stat: cannot read file system information for \'/tmp/longhorn-test/vol-disk\': No such file or directory\n, error exit status 1', 'reason': 'NoDiskInfo', 'status': 'False'}, 'Schedulable': {'lastProbeTime': '', 'lastTransitionTime': '2022-04-17T10:03:42Z', 'message': 'the disk extra-disk(/tmp/longhorn-test/vol-disk) on the node ip-10-0-2-202 is not ready', 'reason': 'DiskNotReady', 'status': 'False'}}, 'diskUUID': 'a53a641d-db9b-4425-838b-e00ad7ecb401', 'evictionRequested': False, 'path': '/tmp/longhorn-test/vol-disk', 'scheduledReplica': {}, 'storageAvailable': 0, 'storageMaximum': 0, 'storageReserved': 0, 'storageScheduled': 0, 'tags': ['extra']}, 'migrated-disk': {'allowScheduling': False, 'conditions': {'Ready': {'lastProbeTime': '', 'lastTransitionTime': '2022-04-17T10:03:42Z', 'message': 'Disk migrated-disk(/tmp/longhorn-test/vol-disk-migrated) on node ip-10-0-2-202 is ready', 'reason': '', 'status': 'True'}, 'Schedulable': {'lastProbeTime': '', 'lastTransitionTime': '2022-04-17T10:03:42Z', 'message': 'Disk migrated-disk(/tmp/longhorn-test/vol-disk-migrated) on node ip-10-0-2-202 is schedulable', 'reason': '', 'status': 'True'}}, 'diskUUID': 'a53a641d-db9b-4425-838b-e00ad7ecb401', 'evictionRequested': False, 'path': '/tmp/longhorn-test/vol-disk-migrated', 'scheduledReplica': {}, 'storageAvailable': 943718400, 'storageMaximum': 1023303680, 'storageReserved': 0, 'storageScheduled': 0, 'tags': ['extra']}}, 'engineManagerCPURequest': 0, 'evictionRequested': False, 'name': 'ip-10-0-2-202', 'region': '', 'replicaManagerCPURequest': 0, 'tags': None, 'zone': ''}
(ApiError(...), "500 : Delete Disk on node default-disk error: Please disable the disk /var/lib/longhorn/ and remove all replicas first \n{'code': 500, 'detail': '', 'message': 'Delete Disk on node default-disk error: Please disable the disk /var/lib/longhorn/ and remove all replicas first ', 'status': 500}")

**Comment by yangchiu** [comment]
Fixed in https://github.com/longhorn/longhorn/issues/7463.
