### ISSUE TITLE
 [BUG] longhorn-admission-webhook failing

### ISSUE THREAD

**Issue by dough29** [longhorn/longhorn#3772]
## Describe the bug

On a fresh k3s cluster I try to deploy Longhorn from kubectl but longhorn-admission-webhook get stuck on restarting failing pods (see logs bellow).

## To Reproduce

1. Create a fresh (Debian 11) k3s cluster + install open-iscsi and nfs-common packages
2. kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml

## Expected behavior

Longhorn should install successfully.

## Log or Support bundle

`time="2022-03-22T15:55:34Z" level=info msg="Starting longhorn admission webhook server"`
`W0322 15:55:34.498614       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.`
`I0322 15:55:34.501795       1 shared_informer.go:223] Waiting for caches to sync for longhorn datastore`
`I0322 15:55:35.603396       1 shared_informer.go:230] Caches are synced for longhorn datastore `
`time="2022-03-22T15:55:35Z" level=fatal msg="Error starting longhorn admission webhook server: can't get required environment variable, env NODE_NAME wasn't set"`

## Environment

 - Longhorn version: v1.2.4
 - Installation method : Kubectl
 - Kubernetes distro and version: k3s v1.23.4
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Debian 11
   - CPU per node: 4
   - Memory per node: 4GB
   - Disk type: SSD
   - Network bandwidth between the nodes: 1Gbps
 - Underlying Infrastructure: KVM
 - Number of Longhorn volumes in the cluster: N/A

**Comment by jenting** [comment]
We change our branch policy recently, please install it via a specific branch
```shell
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.2.4/deploy/longhorn.yaml
```

**Comment by dough29** [comment]
Wahou thanks a lot @jenting that worked like a charm !

Have a nice day.

**Comment by innobead** [comment]
cc @derekbit

**Comment by derekbit** [comment]
Addressed in https://github.com/longhorn/longhorn/pull/3774
