### ISSUE TITLE
[TASK] command line for longhorn with SPDK

### ISSUE THREAD

**Issue by keithalucas** [longhorn/longhorn#3783]
## Create a command line interface for creating replicas and volumes with longhorn and SPDK

SPDK's primary user interface is JSON RPC over a Unix Domain Socket.  It provides a general python utility for executing commands.   This task is to create a command line interface similar to longhorn-engine's to facilitate quickly creating replicas and volumes for testing and provide something familiar.

One difference is that the commands will communicate with a running `spdk_tgt` instead.  Some of the longhorn-engine commands like replica and controller remain running.   The commands will send messages over JSON RPC over either the default Unix Domain socket or one specified by an environment variable or command line flag.
## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

-  Storage commands.  This isn't in the existing longhorn engine.  
- [ ] Command to add storage to SPDK.  This will take an optional name and path to a disk device.  For example, `longhorn-spdk storage create [ -l longhorn] /dev/sdb1`.  This will create a new logical volume store which the specified name on the specific device.  This may make all the previously created logical volumes available as replicas.
- [ ] Command to remove the logical volume from the device.
-  Replica commands.
- [x] Command to create a new replica.  For example, `longhorn-spdk replica create [-l longhorn] name -a listen-address -n nmvf-port -c comm-port`.  There is a listen address and a port for NVME over Fabrics and communication for coordinating rebuilding.
- [ ] Command to remove a replica.  For example, `longhorn-spdk replica delete [-l longhorn] name
-  Volume commands.  This is like the controller subcommand for the longhorn-engine. 
- [x] Command to create a volume, e.g. `longhorn-spdk volume create name --replica <format for replica1> --replica <format for replica2> --replica <format for replica3>`.   Each remote replica has logical volume store name, a remote address, a NVME over Fabrics port, and a communication port.  The local remote will just have the logical volume store name.   We need to determine a way to encode this information.
- [x] Command to add a replica to an existing volume.  `longhorn-spdk volume add name --replica <format>`
- [ ] Command to remove a replica from an existing volume.  `longhorn-spdk volume rm name --replica <format>`
- [ ] Command to delete a volume.  `longhorn-spdk volume delete name`.
- [ ] Command to snapshot a volume.  `longhorn-spdk volume snapshot name snapshot-name`.
- [ ] Command to list volumes and status.
- [ ] Command to list the individual replicas in a volume and their statuses.
## Additional context

Add any other context or screenshots about the task request here.

**Comment by innobead** [comment]
Closing, we will reorganize issues for SPDK.
