### ISSUE TITLE
[IMPROVEMENT] Remove all the hard-coded `longhorn-system` namespace on all repos

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3799]
## Is your improvement request related to a feature? Please describe

Remove all the hard-coded `longhorn-system` namespace on all repos (longhorn/longhorn, longhorn/longhorn-manager, longhorn/longhorn-test). 

The purpose of the issue to scan through all repos again. Also, modify test repo so that it can test Longhorn in a random namespace. E.g., each test run, we deploy Longhorn into a random namespace and give the namespace to the e2e test (via Jenkins pipelines I guess, I am not very familiar with this part but I think it could be done). This way our e2e test will ensure no hard-code namespace can pass.

**Comment by PhanLe1010** [comment]
Note from @yasker 

> Just to make sure we're doing it as a just in case, not a recommended option. I don't think it makes sense to suggest user to install it in other namespaces.
Also, be careful of user install Longhorn twice in a system.

**Comment by innobead** [comment]
Closing this first, because we will just stick to longhorn-system namespace for now.
