### ISSUE TITLE
[BUG] 405 status code show up twice when `Create PV/PVC` for new volume via Rancher Proxy

### ISSUE THREAD

**Issue by kaxing** [longhorn/longhorn#3807]
## Describe the bug

The status code will show up

## To Reproduce

The issue isn't show up every time but it can be reproduced with fairly high chance when accessing UI through Rancher dashboard

1. Open Longhorn UI via Rancher
2. Got to Volume page and create a new volume
3. Select the volume and click the dropdown menu
4. Click on "Create PV/PVC"

![image](https://user-images.githubusercontent.com/602540/161024964-ff6033cb-5070-487d-bbdd-c8c591b7fbe1.png)

## Expected behavior

No error or exception show.

## Log or Support bundle

N/A

## Environment

 - Longhorn version: v1.1.3, v1.2.4, v1.3.0-dev (master-head)
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: rke1 via rancher 2.6.3

## Additional context

Nope

**Comment by smallteeths** [comment]
The reason for the 405 error status code is that the `actions` of the PV/PVC are not ready while the volume is being created. So it causes the error.

The way to fix this is to disable PV/PVC creation when the volume is not ready. Wait for the volume to be created and then allow the PV/PVC creation.

**Comment by kaxing** [comment]
Validation - **PASSED**

No longer able to reproduce this with master-image(ui: 7c50483)
