### ISSUE TITLE
[Backup Job created by Recurring Job, but only 1 Backup of the latest results] 

### ISSUE THREAD

**Issue by cplinux** [longhorn/longhorn#3814]
## Question
> Suggest to use https://github.com/longhorn/longhorn/discussions to ask questions.

## Environment

 - Longhorn version: v1.2.4
 - Kubernetes version: v1.23.4
 - Node config
   - OS type and version: Ubuntu 20.04 LTS
   - CPU per node: 8C
   - Memory per node: 16G
   - Disk type: HDD
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare

## Additional context

I created a backup task by using a circular task. Although I saw the latest 3 backups in the backup task menu, I only saw one backup snapshot in the volume information, but my program was constantly writing data.

<img width="2016" alt="image" src="https://user-images.githubusercontent.com/91673303/161279044-341c6db7-6e76-4ecb-9bfe-63622cbf139c.png">

yaml file :

```yaml
root@master01:~# kubectl get RecurringJob -n longhorn-system myapp-backup-2m -o yaml
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  creationTimestamp: "2022-04-01T13:10:13Z"
  generation: 3
  name: myapp-backup-2m
  namespace: longhorn-system
  resourceVersion: "967689"
  uid: c0058d2a-248b-40d0-848b-da1e9b2f63a5
spec:
  concurrency: 1
  cron: '*/2 * * * *'
  groups:
  - default
  retain: 3
  task: backup
status:
  ownerID: node03
```

**Comment by shuo-wu** [comment]
The chain presented on the volume detail page is the snapshot chain. If there is a backup created from a snapshot, the snapshot icon will be green. But this does not mean that the backup will disappear when the related snapshot is removed. And deleting a backup won't affect the existence of the snapshot itself (Of course the icon will become blue if the snapshot still exists), either. The info in the snapshot chain is for convenience only.

Someone asked the same question before. But I don't remember the ticket number. Sorry for misleading anyway.
