### ISSUE TITLE
[BUG] longhorn-driver-deployer doesn't scale deployments on post-install change

### ISSUE THREAD

**Issue by jemand771** [longhorn/longhorn#3816]
## Describe the bug

When modifying the `longhorn-driver-deployer` Deployment's environment variables, the new (deployment) replica count doesn't get applied automatically. Affected variables:
* `CSI_ATTACHER_REPLICA_COUNT` (deployment `csi-attacher`)
* `CSI_PROVISIONER_REPLICA_COUNT` (deployment `csi-provisioner`)
* `CSI_RESIZER_REPLICA_COUNT` (deployment `csi-resizer`)
* `CSI_SNAPSHOTTER_REPLICA_COUNT` (deployment `csi-snapshotter`)

## To Reproduce

1. Install longhorn (I used the kubectl method)
2. modify and apply `longhorn-driver-deployer`, in my case
```yaml
          # Manually specify number of CSI attacher replicas
          - name: CSI_ATTACHER_REPLICA_COUNT
            value: "1"
          # Manually specify number of CSI provisioner replicas
          - name: CSI_PROVISIONER_REPLICA_COUNT
            value: "1"
          - name: CSI_RESIZER_REPLICA_COUNT
            value: "1"
          - name: CSI_SNAPSHOTTER_REPLICA_COUNT
            value: "1"
```
3. Observe the number of pods: it doesn't change

## Expected behavior

Changing the replica environment variables should update the k8s deployments to match the change.
(except if this behavour is intentional, I'm not too familiar with longhorn's internal workings)

## Log or Support bundle

logs of my `longhorn-driver-deployer` pod after changing the environment variables:
```
2022/04/01 16:56:05 proto: duplicate proto type registered: VersionResponse
W0401 16:56:05.409333       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-04-01T16:56:05Z" level=debug msg="Deploying CSI driver"
time="2022-04-01T16:56:05Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"
time="2022-04-01T16:56:06Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"
time="2022-04-01T16:56:07Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Running"
time="2022-04-01T16:56:08Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Running"
time="2022-04-01T16:56:09Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Running"
time="2022-04-01T16:56:10Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Running"
time="2022-04-01T16:56:11Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Running"
time="2022-04-01T16:56:12Z" level=warning msg="Proc not found: kubelet"
time="2022-04-01T16:56:12Z" level=debug msg="proc cmdline detection pod discover-proc-k3s-cmdline in phase: Pending"
time="2022-04-01T16:56:13Z" level=debug msg="proc cmdline detection pod discover-proc-k3s-cmdline in phase: Pending"
time="2022-04-01T16:56:14Z" level=debug msg="proc cmdline detection pod discover-proc-k3s-cmdline in phase: Running"
time="2022-04-01T16:56:15Z" level=info msg="Proc found: k3s"
time="2022-04-01T16:56:15Z" level=info msg="Detected root dir path: /var/lib/kubelet"
time="2022-04-01T16:56:15Z" level=info msg="Upgrading Longhorn related components for CSI v1.1.0"
time="2022-04-01T16:56:15Z" level=debug msg="Detected CSI Driver driver.longhorn.io CSI Git commit 79ce2cfde922a7e0966059f72b8aee5f05bff513 version v1.2.4 Kubernetes version v1.22.6+k3s1 has already been deployed"
time="2022-04-01T16:56:15Z" level=debug msg="Detected service csi-attacher CSI Git commit 79ce2cfde922a7e0966059f72b8aee5f05bff513 version v1.2.4 Kubernetes version v1.22.6+k3s1 has already been deployed"
time="2022-04-01T16:56:15Z" level=debug msg="Detected deployment csi-attacher CSI Git commit 79ce2cfde922a7e0966059f72b8aee5f05bff513 version v1.2.4 Kubernetes version v1.22.6+k3s1 has already been deployed"
time="2022-04-01T16:56:15Z" level=debug msg="Detected service csi-provisioner CSI Git commit 79ce2cfde922a7e0966059f72b8aee5f05bff513 version v1.2.4 Kubernetes version v1.22.6+k3s1 has already been deployed"
time="2022-04-01T16:56:15Z" level=debug msg="Detected deployment csi-provisioner CSI Git commit 79ce2cfde922a7e0966059f72b8aee5f05bff513 version v1.2.4 Kubernetes version v1.22.6+k3s1 has already been deployed"
time="2022-04-01T16:56:15Z" level=debug msg="Detected service csi-resizer CSI Git commit 79ce2cfde922a7e0966059f72b8aee5f05bff513 version v1.2.4 Kubernetes version v1.22.6+k3s1 has already been deployed"
time="2022-04-01T16:56:15Z" level=debug msg="Detected deployment csi-resizer CSI Git commit 79ce2cfde922a7e0966059f72b8aee5f05bff513 version v1.2.4 Kubernetes version v1.22.6+k3s1 has already been deployed"
time="2022-04-01T16:56:15Z" level=debug msg="Detected service csi-snapshotter CSI Git commit 79ce2cfde922a7e0966059f72b8aee5f05bff513 version v1.2.4 Kubernetes version v1.22.6+k3s1 has already been deployed"
time="2022-04-01T16:56:15Z" level=debug msg="Detected deployment csi-snapshotter CSI Git commit 79ce2cfde922a7e0966059f72b8aee5f05bff513 version v1.2.4 Kubernetes version v1.22.6+k3s1 has already been deployed"
time="2022-04-01T16:56:15Z" level=debug msg="Detected daemon set longhorn-csi-plugin CSI Git commit 79ce2cfde922a7e0966059f72b8aee5f05bff513 version v1.2.4 Kubernetes version v1.22.6+k3s1 has already been deployed"
time="2022-04-01T16:56:15Z" level=debug msg="CSI deployment done"
```
(it seems like it's only checking whether the deployment is present without comparing attributes like the replica count)

## Environment

 - Longhorn version: 1.2.4
 - Installation method kubectl
 - Kubernetes distro and version: k3s v1.22.6+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 0 (or technically 1, since the manager node is _also_ a worker)
 - Node config
   - OS type and version: Ubuntu 20.04.4 LTS
   - CPU per node: 10
   - Memory per node: 64gb
   - Disk type: SSD, not sure if sata/nvme/...
   - Network bandwidth between the nodes: n/a
 - Underlying Infrastructure: linux "vm" on kvm, (supposedly) dedicated cpu/memory. hosted on netcup.de
 - Number of Longhorn volumes in the cluster: 6

## Additional context

just as a general question: what's the recommendation on how many replicas (of the csi-* pods) to run? especially on single-node clusters like this one.
I encountered this while troubleshooting another issue ~(which I haven't collected enough info about to raise here yet), so it miiight be possible that something's wrong with my install. I doubt it, but it's worth considering~ resolved by https://longhorn.io/kb/troubleshooting-volume-with-multipath/

## Available workaround

For now, I just edited the environment variables (for good measure/keeping cluster and manifests in sync) and manually scaled down the deployments to 1. This doesn't seem to have any side effects.

**Comment by shuo-wu** [comment]
These env variables control the pod count of a fresh installation only. Once these CSI components are up and running, you can directly use `kubectl scale` to modify the counts.

For the single-node-cluster, launching one pod for each CSI component should be enough.

**Comment by jemand771** [comment]
Alright, I wasn't sure if that was intended. thanks!
