### ISSUE TITLE
[BUG] Volume can't detach when "Concurrent Replica Rebuild Per Node Limit = 0" and set node evicted from True to False

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#3820]
## Describe the bug

From e2e [test_disable_replica_rebuild](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/77/testReport/junit/tests/test_ha/test_disable_replica_rebuild/)
Not happen on v1.2.4

Create volume with 1 replica, attach volume to node where replica located,
Disable replica rebuild (Concurrent Replica Rebuild Per Node Limit = 0), attach volume 
Switch node eviction from false -> true -> false,
Detach volume, volume will stuck at healthy state

## To Reproduce

1. Disable replica rebuild (Concurrent Replica Rebuild Per Node Limit = 0)
2. Create volume with 1 replica, attach volume to node where replica located
3. Edit node volume attached to, switch node eviction from false -> true -> false
4. Detach volume, volume will stuck at healthy state
5. Volume will stuck at healthy state

## Expected behavior

Volume should detached

## Log or Support bundle
N/A

## Environment

 - Longhorn version: master-head 20220406
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version: Ubuntu
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 1

## Additional context
N/A

**Comment by innobead** [comment]
@PhanLe1010 Please help check this one.

**Comment by cchien816** [comment]
Close this ticket because after resync time reverted this issue not happened in recently maser e2e build ([145](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/145/testReport/tests/test_ha/test_disable_replica_rebuild/) , [144](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/144/testReport/tests/test_ha/test_disable_replica_rebuild/)) ..
