### ISSUE TITLE
[BUG] Longhorn default StorageClass is not always synced with the ConfigMap

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3821]
## Describe the bug

After increasing the controller force resync period for #3083, the default Longhorn StorageClass may be out of sync with the corresponding ConfigMap for a long time since the controller won't be triggered by StorageClass events now.

## To Reproduce
  1. Deploy Longhorn master
  2. Delete or modify the default Longhorn StorageClass `longhorn`
  3. The modified SC won't be reverted for a long time.

## Expected behavior

The SC will be synced with the ConfigMap immediately.

## Log or Support bundle

N/A

## Environment

 - Longhorn version: master - 04/06/2022

## Additional context

N/A

**Comment by innobead** [comment]
cc @PhanLe1010

**Comment by joshimoo** [comment]
@shuo-wu we are missing the wait for cache sync for the new storage class informer addition ref: https://github.com/longhorn/longhorn-manager/pull/1285/files#r847120327

**Comment by yangchiu** [comment]
verified on master-head
