### ISSUE TITLE
[TASK] Improve the doc for troubleshooting NFS backuptarget

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#3825]
## What's the task? Please describe

Some users encountered the backup failure while using the NFS backuptarget. We can summarize the troubleshooting tips and solutions for helping users configure the NFS server.

## Additional context
https://github.com/longhorn/longhorn/issues/3576
https://github.com/longhorn/longhorn/discussions/3805

**Comment by innobead** [comment]
@mantissahz Please help this one. You can check with @derekbit to understand the context and some other reported issues.

**Comment by innobead** [comment]
The doc merged, Closing.
