### ISSUE TITLE
[FEATURE] Longhorn UI supports orphan CRs management

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#3826]
## What's the task? Please describe

Longhorn UI supports orphan CRs
- List 
- Deletion
- Enable/disable global orphan-auto-deletion setting

## Additional context

Longhorn #685

**Comment by innobead** [comment]
@smallteeths this needs to wait https://github.com/longhorn/longhorn/issues/685

**Comment by innobead** [comment]
@derekbit @smallteeths this is nice to have in 1.3.0, so please help cooperate on this. Thanks.

**Comment by derekbit** [comment]
My idea is that we can add a `orphaned data` page.
![image](https://user-images.githubusercontent.com/12527233/166869737-e28ab616-b1f9-4c76-abe9-2a75d5ecb90a.png)


Then, in the page, the layout is like
![image](https://user-images.githubusercontent.com/12527233/166870609-aa3f04e9-f457-4d4e-a27b-494c2e638497.png)

- Name: resource.name
- Node: resource.spec.nodeID
- Disk: resource.spec.parameters["DiskPath"]
- Path: resource.spec.parameters["DataName"]

---

We also need to introduce a global `orphan-auto-deletion` setting in `Setting->General` page. The default value is `false`

cc. @smallteeths

**Comment by innobead** [comment]
Setting will be automatically created w/o any UI change :slightly_smiling_face:

**Comment by derekbit** [comment]
> Setting will be automatically created w/o any UI change 🙂

Cool!

**Comment by smallteeths** [comment]
Yes I am working on this page, I am going to put the nav link under the drop down menu in setting.

<img width="769" alt="截屏2022-05-05 下午2 19 17" src="https://user-images.githubusercontent.com/27733391/166871698-d816de48-ee36-436a-8e18-36c6a90027e7.png">

And something else I'm not so sure about

1. Is batch deletion also required? 
2. Do we need to add a filter by name component？

**Comment by derekbit** [comment]
`orphaned data` might be better because there are other different orphaned data types in the future.
 I'm not sure if putting `orphaned data` link in `Setting` is better. But it's fine for me with it.
 
 > Is batch deletion also required?
Yes, we need.

> Do we need to add a filter by name component？
No, the name is UUID and meaningless.
But we need a filter by node and disk

Thank you @smallteeths

**Comment by yangchiu** [comment]
verified passed on v1.3.0-preview1 by 
(1) checking there is Orphaned Data page and it has list and delete functionalities
(2) checking there is Orphan Auto-Deletion setting and it works
(3) running https://github.com/longhorn/longhorn-tests/pull/940 and checking the UI in the meantime
