### ISSUE TITLE
Kubernetes application storage in Longhorn

### ISSUE THREAD

**Issue by Naveen-Alien** [longhorn/longhorn#3827]
Hi 

I have installed longhorn on my kubernetes. I have installed iscsid and nfs-common on my worker nodes and master nodes then installed longhorn.

When I create pvc and deploy the application, I am getting an error like AttachVolume.Attach failed for volume "pvc-7173bdd9-03b3-4e3c-afc8-a0246cc827d0" : rpc error: code = Aborted desc = volume pvc-7173bdd9-03b3-4e3c-afc8-a0246cc827d0 is not ready for workloads

when I check the longhorn dashboard, I can see Not ready for workload. Volume Faulted error.

Can you please help to resolve the issue

Thanks
Naveen

**Comment by shuo-wu** [comment]
Volume Faulted state means all replicas are crashed. Can you provide the related logs in longhorn-manager or longhorn-instance-manager?

**Comment by Naveen-Alien** [comment]
[Longhorn Instance manager logs.txt](https://github.com/longhorn/longhorn/files/8448605/Longhorn.Instance.manager.logs.txt)
[Longhorn-Manager logs.txt](https://github.com/longhorn/longhorn/files/8448606/Longhorn-Manager.logs.txt)

@shuo-wu Thanks for your reply. I have attached the requested logs

Let me know if you need any details

Also I have attached the error screenshot for your ref.
<img width="1220" alt="Screenshot 2022-04-08 at 10 20 43 AM" src="https://user-images.githubusercontent.com/103174838/162367122-a8781778-dab8-4e1a-9e98-30f099fbcc7c.png">

**Comment by shuo-wu** [comment]
It seems that the TCP connections between the volume engine and volume replicas are blocked, which leads to the engine failure then volume Faulted:
```
time="2022-04-08T04:41:51Z" level=warning msg="pvc-b860abb7-3d3a-4f8e-89fb-c852d4d8c5e1-r-d82a2f23: time=\"2022-04-08T04:41:43Z\" level=error msg=\"10.1.100.226:50388 is not allowed to connect\""
```

BTW, next time when you want to send the log, you can click `Generate Support Bundle` in the bottom left of the UI to generate the full bundle.

**Comment by Naveen-Alien** [comment]
Sure, thanks @shuo-wu 

How can I fix this issue? do I need to login to longhorn manager to fix this or in my local host ?

**Comment by shuo-wu** [comment]
I have no idea of your cluster config. These TCP connections are between the processes of engine (instance) manager pods and those of replica (instance) manager pods. Will creating and attaching a random volume encounter the same error?

**Comment by AndreasChristianson** [comment]
Going to try this workaround, for any lurkers

https://scvalex.net/posts/49/
