### ISSUE TITLE
[BUG] Replica rebuilding failure with error "Replica must be closed, Can not add in state: open"

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3828]
## Describe the bug

Replica rebuilding may constantly fail with the error message mentioned in the title. 

Actually, the root cause is that [the too-many-snapshot check](https://github.com/longhorn/longhorn-engine/blob/cda02873ef0789a56fcca9ffcdbc5bea76f09018/pkg/controller/control.go#L321-L325) blocks and fails the rebuilding. Then [the replica **server** is not closed by the engine as usual](https://github.com/longhorn/longhorn-engine/blob/cda02873ef0789a56fcca9ffcdbc5bea76f09018/pkg/controller/control.go#L328), (and [the replica server close call here](https://github.com/longhorn/longhorn-manager/blob/01c0e8c3f278a26e104c8973ee3321bd7c3c3d73/controller/engine_controller.go#L1347) does not work). Besides, the replica **process itself** won't be stopped (by the longhorn manager). Next time when the longhorn manager asks the engine to retry the rebuilding, the engine will detect that [the replica server is in the invalid state `open`](https://github.com/longhorn/longhorn-engine/blob/cda02873ef0789a56fcca9ffcdbc5bea76f09018/pkg/backend/remote/remote.go#L263-L265) at [the beginning](https://github.com/longhorn/longhorn-engine/blob/cda02873ef0789a56fcca9ffcdbc5bea76f09018/pkg/controller/control.go#L144).

## To Reproduce

1. Create and attach a volume
2. Create 250 snapshots for the volume, this would trigger the too-many-snapshot error
3. Remove one replica
4. Wait and check the log in the longhorn managers

## Expected behavior

The replica server should be closed then the process should be removed after rebuilding failure

## Log or Support bundle
```
[longhorn-manager-n4xnc] time="2022-04-07T12:08:06Z" level=error msg="Failed rebuilding of replica 10.42.2.142:10000" controller=longhorn-engine error="failed to add replica address='tcp://10.42.2.142:10000' to controller 'vol': failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.2/longhorn [--url 10.42.4.123:10000 add tcp://10.42.2.142:10000], output , stderr, time=\"2022-04-07T12:08:06Z\" level=info msg=\"Adding replica tcp://10.42.2.142:10000 in WO mode\"\ntime=\"2022-04-07T12:08:06Z\" level=fatal msg=\"Error running add replica command: failed to create replica tcp://10.42.2.142:10000 for volume 10.42.4.123:10000: rpc error: code = Unknown desc = Too many snapshots created\"\n, error exit status 1" node=shuo-k8s-worker-1 volume=vol
[longhorn-manager-n4xnc] time="2022-04-07T12:08:06Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"vol-e-c2378df3\", UID:\"68e8592d-7fae-49cb-9229-f1d7f8e49106\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"2013755\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedRebuilding' Failed rebuilding replica with Address 10.42.2.142:10000: failed to add replica address='tcp://10.42.2.142:10000' to controller 'vol': failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.2/longhorn [--url 10.42.4.123:10000 add tcp://10.42.2.142:10000], output , stderr, time=\"2022-04-07T12:08:06Z\" level=info msg=\"Adding replica tcp://10.42.2.142:10000 in WO mode\"\ntime=\"2022-04-07T12:08:06Z\" level=fatal msg=\"Error running add replica command: failed to create replica tcp://10.42.2.142:10000 for volume 10.42.4.123:10000: rpc error: code = Unknown desc = Too many snapshots created\"\n, error exit status 1"
[longhorn-manager-n4xnc] time="2022-04-07T12:08:06Z" level=info msg="Removed failed rebuilding replica 10.42.2.142:10000" controller=longhorn-engine node=shuo-k8s-worker-1 volume=vol
[longhorn-manager-n4xnc] time="2022-04-07T12:08:06Z" level=info msg="Engine is still in backoff for replica vol-r-4541122b rebuild failure" controller=longhorn-engine node=shuo-k8s-worker-1 volume=vol


[longhorn-manager-n4xnc] time="2022-04-07T12:08:36Z" level=warning msg="Error syncing Longhorn engine" controller=longhorn-engine engine=longhorn-system/vol-e-c2378df3 error="fail to sync engine for longhorn-system/vol-e-c2378df3: fail to start rebuild for vol-r-4541122b of vol-e-c2378df3: timed out waiting for the condition" node=shuo-k8s-worker-1
[longhorn-manager-n4xnc] time="2022-04-07T12:08:36Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"vol-e-c2378df3\", UID:\"68e8592d-7fae-49cb-9229-f1d7f8e49106\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"2013755\", FieldPath:\"\"}): type: 'Normal' reason: 'Rebuilding' Start rebuilding replica vol-r-4541122b with Address 10.42.2.142:10000 for normal engine vol"
[longhorn-manager-n4xnc] time="2022-04-07T12:08:36Z" level=error msg="Failed rebuilding of replica 10.42.2.142:10000" controller=longhorn-engine error="failed to add replica address='tcp://10.42.2.142:10000' to controller 'vol': failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.2/longhorn [--url 10.42.4.123:10000 add tcp://10.42.2.142:10000], output , stderr, time=\"2022-04-07T12:08:36Z\" level=info msg=\"Adding replica tcp://10.42.2.142:10000 in WO mode\"\ntime=\"2022-04-07T12:08:36Z\" level=fatal msg=\"Error running add replica command: failed to create replica tcp://10.42.2.142:10000 for volume 10.42.4.123:10000: rpc error: code = Unknown desc = Replica must be closed, Can not add in state: open\"\n, error exit status 1" node=shuo-k8s-worker-1 volume=vol
[longhorn-manager-n4xnc] time="2022-04-07T12:08:36Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"vol-e-c2378df3\", UID:\"68e8592d-7fae-49cb-9229-f1d7f8e49106\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"2013755\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedRebuilding' Failed rebuilding replica with Address 10.42.2.142:10000: failed to add replica address='tcp://10.42.2.142:10000' to controller 'vol': failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.2/longhorn [--url 10.42.4.123:10000 add tcp://10.42.2.142:10000], output , stderr, time=\"2022-04-07T12:08:36Z\" level=info msg=\"Adding replica tcp://10.42.2.142:10000 in WO mode\"\ntime=\"2022-04-07T12:08:36Z\" level=fatal msg=\"Error running add replica command: failed to create replica tcp://10.42.2.142:10000 for volume 10.42.4.123:10000: rpc error: code = Unknown desc = Replica must be closed, Can not add in state: open\"\n, error exit status 1"
[longhorn-manager-n4xnc] time="2022-04-07T12:08:36Z" level=info msg="Removed failed rebuilding replica 10.42.2.142:10000" controller=longhorn-engine node=shuo-k8s-worker-1 volume=vol
[longhorn-manager-n4xnc] time="2022-04-07T12:08:36Z" level=info msg="Engine is still in backoff for replica vol-r-4541122b rebuild failure" controller=longhorn-engine node=shuo-k8s-worker-1 volume=vol
```

## Environment

 - Longhorn version: v1.2.2. (I think we can reproduce it in the master version as well)

## Additional context

N/A

**Comment by Daxiongmao87** [comment]
Any known workaround for this issue?

**Comment by mantissahz** [comment]
And maybe we need some limitation when creating a snapshot to prevent replica rebuilding failed.

**Comment by innobead** [comment]
> And maybe we need some limitations when creating a snapshot to prevent replica rebuilding failed.

ref: https://github.com/longhorn/longhorn/issues/2988#issuecomment-917783540

**Comment by roger-ryao** [comment]
**Verified on master-head 20221121**

- longhorn master-head ([7522275](https://github.com/longhorn/longhorn/commit/75222752d22abfd423f8c650f5ebf1e5c3f96ff7)) 
- longhorn-engine master-head ([acdfe5b](https://github.com/longhorn/longhorn-engine/commit/acdfe5be79f75acabb49a39105643752d601495f)) 


**The test steps**

[Ref #3828 (To Reproduce)](https://github.com/longhorn/longhorn/issues/3828#issuecomment-1313591818)

- 1. Create and attach a volume
- 2. Create 250 snapshots for the volume `pytest test_basic.py:snapshot_test`, 
       this would trigger the too-many-snapshot error

<details>
<summary>snapshot_test</summary>

    ```
    def snapshot_test(client, volume_name, backing_image):  # NOQA
        volume = create_and_check_volume(client, volume_name,
                                        backing_image=backing_image)

        lht_hostId = get_self_host_id()
        volume = volume.attach(hostId=lht_hostId)
        volume = common.wait_for_volume_healthy(client, volume_name)

        volume = client.by_id_volume(volume_name)
        positions = {}

        for i in range(250):
            print(i)
            create_snapshot(client, volume_name)
    ```

</details>

![Screenshot_20221121_141154](https://user-images.githubusercontent.com/104337648/202978259-742754ff-d46a-4d5d-9b01-4d4221c73c7a.png)
![Screenshot_20221121_141215](https://user-images.githubusercontent.com/104337648/202978350-27c2138d-26c5-4b4a-b522-7457aa13b279.png)



- 3. Remove one replica
- 4. Wait and check the log in the longhorn managers


**Result Passed**

1. The issue can be reproduced on v1.2.2
[longhorn-support-bundle_122.zip](https://github.com/longhorn/longhorn/files/10053880/longhorn-support-bundle_122.zip)

2. Follow the test steps in the comment and use longhorn:master-head longhorn-engine:master-head 
3. After deleted one replica, we didn’t find out the error log in the longhorn-managersr logs
[longhorn-support-bundle_master.zip](https://github.com/longhorn/longhorn/files/10053886/longhorn-support-bundle_master.zip)

**Comment by innobead** [comment]
@mantissahz We should backport this to 1.3.x.
