### ISSUE TITLE
[BUG] Cannot change backup bucket location

### ISSUE THREAD

**Issue by digiserg** [longhorn/longhorn#3830]
## Describe the bug

I install lonhorn from helm chart and I use the following configuration:

```yaml
defaultSettings:
  backupTarget: s3://my-backup-bucket@eu-central-2/longhorn
  backupTargetCredentialSecret: longhorn-backups
```
This is a new set up and I had the need to change the bucket location to a new bucket. I did that in helm config and ran an upgrade. The upgrade was completed successfully and I could see in the _configmap_ and secret the changes were applied successfully. 

But the longhorn-ui, browsing to the _Backup_ section reported an error and it was showing the old bucket location together with an access denied error (it was the wrong bucket initially):

```
[backup ls --volume-only s3://my-originalbackup-bucket@eu-central-2/longhorn]
```
Login to the manager pods, I could confirm the config was actually updated by checking the /var/lib/longhorn-settings directory. 

I tried all sorts to get to reload, I even restarted all pods to no avail.

In the end, because luckily this was a new set up, I uninstalled longhorn and installed it again. That resolved my problem but obviously, this is not doable if I had some production data.

## To Reproduce

Just change the bucket location/url and apply the new helm chart config.

Then try to create a backup or browse to _Backup_ section in the UI.

## Expected behavior

The new bucket config to take effect immediately and be able to create backups there.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.2.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.21.10
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - Disk type(e.g. SSD/NVMe): SSD
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: none at the time

**Comment by c3y1huang** [comment]
You can use Longhorn UI to update settings in Setting > General.
Ref https://longhorn.io/kb/troubleshooting-default-settings-do-not-persist/#background.

**Comment by digiserg** [comment]
> You can use Longhorn UI to update settings in Setting > General.

I didn't know that. But we're hands-off, we manage everything from terraform. We would prefer it to work from code.

Thanks

**Comment by shuo-wu** [comment]
Or you can directly modify them by `kubectl -n longhorn-system patch -p '{"value": "<New setting value>"}' --type=merge lhs backup-target` or `kubectl -n longhorn-system patch -p '{"value": "<New setting value>"}' --type=merge lhs backup-target-credential-secret`

**Comment by digiserg** [comment]
All good suggestions to get me out of a problem but as I said, we do hands-off deployments for the most part. It would be good if this was fixed by just updating the helm chart.
Thanks.

**Comment by innobead** [comment]
ref: #2570
