### ISSUE TITLE
[IMPROVEMENT] Adjust volume page UI to make better use of screen space

### ISSUE THREAD

**Issue by deosrc** [longhorn/longhorn#3832]
## Is your improvement request related to a feature? Please describe

There is a lot of wasted space in the UI, particularly in the header. I am on a 1920x1080 display and can only see 4 items in the volume list at a time which makes it somewhat difficult to use.

## Describe the solution you'd like

Some things I think improve this:

- Reduce height of navigation header
- Make full page scrollable with only the table header being sticky rather than only the items in the table scrolling
- Truncate volume and pod names if spanning multiple lines (with tooltip for full display), this would allow the table rows to be compacted
- Combine the two action toolbars (table and page) onto a single line (I'm not convinced by this one tbh, might be too cluttered)

## Describe alternatives you've considered

Stylus browser extension

## Additional context

![image](https://user-images.githubusercontent.com/50599779/162573974-5ccea923-5ce4-478c-8668-fd22027ea0ed.png)

**Comment by shuo-wu** [comment]
cc @innobead @smallteeths
