### ISSUE TITLE
Disable a node after enabling still creates volumes on disabled node

### ISSUE THREAD

**Issue by busyboy77** [longhorn/longhorn#3833]
## Describe the bug

Deploy Longhorn 
disable 1 node ( nodeX )  from the Nodes Menu option
create some volumes
and then 
enable the nodeX
create some volumes
disable the nodeX 
creation of volumes still creates the volumes on nodeX

## To Reproduce

see above

## Expected behavior

when a node is disabled, the volumes should not be created on it

## Environment

 - Longhorn version:  
 v1.2.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 Helm
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K8s v1.23.5
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 6
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:

```
root@K8s-215:~# kubectl get node -o wide
NAME            STATUS   ROLES                  AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
k8s-215         Ready    control-plane,master   24h   v1.23.5   192.168.2.215   <none>        Ubuntu 20.04.4 LTS   5.4.0-107-generic   docker://20.10.14
k8s-216         Ready    <none>                 24h   v1.23.5   192.168.2.216   <none>        Ubuntu 20.04.4 LTS   5.4.0-107-generic   docker://20.10.14
k8s-217         Ready    <none>                 24h   v1.23.5   192.168.2.217   <none>        Ubuntu 20.04.4 LTS   5.4.0-107-generic   docker://20.10.14
k8s-218         Ready    <none>                 24h   v1.23.5   192.168.2.218   <none>        Ubuntu 20.04.4 LTS   5.4.0-107-generic   docker://20.10.14
k8s-store-230   Ready    <none>                 24h   v1.23.5   192.168.2.230   <none>        Ubuntu 20.04.4 LTS   5.4.0-107-generic   docker://20.10.14
k8s-store-231   Ready    <none>                 24h   v1.23.5   192.168.2.231   <none>        Ubuntu 20.04.4 LTS   5.4.0-107-generic   docker://20.10.14
k8s-store-233   Ready    <none>                 24h   v1.23.5   192.168.2.233   <none>        Ubuntu 20.04.4 LTS   5.4.0-107-generic   docker://20.10.14
root@K8s-215:~#
```
 8 vCPUs each
10 GiB RAM
SATA Disk
Bandwidth is not concerned, as all VMs are on the same host.

 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
KVM

 - Number of Longhorn volumes in the cluster:

21

## Additional context

All my nodes except with name STORE in the nodename are disabled within in Longhorn, however in these screenshots you will see that the volumes are still created on disabled nodes.

Nodes List
![image](https://user-images.githubusercontent.com/19593617/162614937-528dc963-e323-4bec-ac18-dfb44f3abdfe.png)

Volumes List
![image](https://user-images.githubusercontent.com/19593617/162614956-2648d860-4ad0-43f5-a302-6285791b93e9.png)

**Comment by shuo-wu** [comment]
On the Longhorn node page, disabling nodes means disabling volume **replicas** being **scheduled** to the nodes rather than preventing the volumes from being attached to the nodes.
