### ISSUE TITLE
[BUG] Error while listing S3 backups

### ISSUE THREAD

**Issue by vojtechmares** [longhorn/longhorn#3834]
## Describe the bug

I've followed the documentation and added S3 backup target and Kubernetes secret (`aws-secret`). Unfortunately, in the UI I get the following error: `error listing backup volume names: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.4/longhorn [backup ls --volume-only s3://<REDACTED BUCKET NAME>@eu-central-1/], output , stderr, , error fork/exec /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.4/longhorn: invalid argument`

I investigated the issue further, running `kubectl exec ...` into the manager container and running the command myself manually, to see what subprocess error I get:
```
$ /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.4/longhorn backup ls --volume-only s3://<REDACTED BUCKET NAME>@eu-central-1/
ERRO[0020] Fail to list s3: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors  pkg=s3
ERRO[0020] NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

From what I have googled, this is an issue with AWS SDK.

## To Reproduce

1. Go to '<longhorn ui>/#/setting'
2. Add backup target S3 
3. Add backup target credential secret (secret is already in Kubernetes in right namespace)
4. Click Backup in main menu or on any volume
5. See error

## Expected behavior

I would get the backups listed and be able to manage PVC backups etc.

## Environment

 - Longhorn version: 1.2.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm & Argo CDk
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.22.8+rke2r1
   - Number of management node in the cluster: 3 (control-plane nodes are also workers, baremetal on Hetzner)
   - Number of worker node in the cluster: 0 
 - Node config
   - OS type and version: Linux, Ubuntu 20.04
   - CPU per node: 8 cores
   - Memory per node: 64Gi
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 1Gbps AFAIK
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal
 - Number of Longhorn volumes in the cluster: 3

**Comment by shuo-wu** [comment]
There are some similar issues reported before: https://github.com/longhorn/longhorn/issues/3137

Do you encode the env to base64? 

BTW, if you want to run the cmd manually inside the Longhorn pods, you need to set the envs manually:
https://github.com/longhorn/longhorn-engine/blob/cda02873ef0789a56fcca9ffcdbc5bea76f09018/pkg/sync/rpc/server.go#L669-L687

**Comment by tuhin37** [comment]
I have the exact same issue. I am running longhorn v1.2.4 on EKS. 
I have created an s3 bucket, created a secret in longhorn-system namespace, and updated the s3 URL and secret name on the setting page. Now every time I go to the backup tab I get this error


error listing backup volume names: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.4/longhorn [backup ls --volume-only s3://damensch-dev-longhorn-backupstore@ap-south-1/], output , stderr, , error fork/exec /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.4/longhorn: invalid argument
 
Has anyone fixed it yet?
Until this issue is fixed, my plan is to use EFS from AWS and mount it as NFS in longhorn (not sure if that's buggy as well)

**Comment by vojtechmares** [comment]
> There are some similar issues reported before: #3137
> 
> Do you encode the env to base64?
> 
> BTW, if you want to run the cmd manually inside the Longhorn pods, you need to set the envs manually: https://github.com/longhorn/longhorn-engine/blob/cda02873ef0789a56fcca9ffcdbc5bea76f09018/pkg/sync/rpc/server.go#L669-L687

Sorry for the really late reply. 

Indeed, the issue was with base64 encoding of the credentials.

**Comment by dfoulkes** [comment]
Hey all, after hitting the wall with this very issue today, I've created a blog article that covers the entire setup. 

https://blog.foulkes.cloud/devops/picluster/longhorn/aws/s3/2022/12/29/pi-cluster-longhorn-aws-s3-backup.html
