### ISSUE TITLE
Cannot pick up a reusable failed replicas

### ISSUE THREAD

**Issue by fanxin92** [longhorn/longhorn#3842]
### Discussed in https://github.com/longhorn/longhorn/discussions/3841

<div type='discussions-op-text'>

<sup>Originally posted by **fanxin92** April 12, 2022</sup>
I deployed RKE2 1.22.8 + Rancher 2.6.4 + Longhorn 1.2.4. The PV I created in rancher is not displayed in Longhorn UI, and there is no log. The PV created in Longhorn UI is not displayed in rancher, and there is a log. The PV created with kubectl is displayed in rancher and Longhorn UI. This is a log. I have 15G disk has been used and 24G disk is available.

[longhorn-support-bundle_1e77e3ae-7e36-4f41-8b4b-74ee812b81e9_2022-04-11T07-39-34Z.zip](https://github.com/longhorn/longhorn/files/8469705/longhorn-support-bundle_1e77e3ae-7e36-4f41-8b4b-74ee812b81e9_2022-04-11T07-39-34Z.zip)

</div>

**Comment by shuo-wu** [comment]
- The PV not found in Longhorn UI means it is not created and managed by UI.

- The reason why the replica cannot be reused varies. Maybe the corresponding node/disk is unavailable or unschedulable. Maybe the replica itself is corrupted. Hence Longhorn cannot tell the exact reason or details in the log. Based on the support bundle you provide, maybe the node or the disk the failed replica previously resides on is unavailable. But after retrying several times, Longhorn will clean it up then rebuild a new replica instead. The following rebuilding failure is pretty straightforward: the node anti-affinity is enabled and `There's no available disk` for the new replica.
