### ISSUE TITLE
[BUG] Creating 2 snapshots with the same name will corrupt the data of the volume

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3844]
## Describe the bug

Creating 2 snapshots with the same name will corrupt the data of the volume. There isn't seems to have a way to recover in this situation. 

## To Reproduce

1. Attach a volume to a node
2. Go to `<LONGHORN-FRONTEND-URL>/v1/volumes/<VOLUME-NAME>?action=snapshotCreate`
3. Click on the snapshotCreate action in the top right panel
    <img width="871" alt="Screen Shot 2022-04-12 at 5 56 20 PM" src="https://user-images.githubusercontent.com/22139961/163078062-a0aa66e3-4e7a-4889-92a5-c738a59a10f7.png">
4. Enter a name, say `snap001` and click send request
5. Repeat steps 3 and 4
6. Observe that the volume enters an endless attaching/detaching loop. The snapshot `snap001` file is deleted from the replica folder on the host

## Expected behavior

Snapshot creation should be an idempotent operation and the volume shouldn't be corrupted.

## Log or Support bundle

[longhorn-support-bundle_617f821e-5952-4d5e-acfa-62ddb223e5f5_2022-04-12T23-59-18Z.zip](https://github.com/longhorn/longhorn/files/8477426/longhorn-support-bundle_617f821e-5952-4d5e-acfa-62ddb223e5f5_2022-04-12T23-59-18Z.zip)
The volume name is `pvc-f9492b2f-a56f-4054-a994-0e8732c35e67`

## Environment

 - Longhorn version: v1.2.4

## Additional context

I think we should solve this problem at engine level:
1. Adding a snapshot lock to engine controller
2. When list snapshot: R lock -> get data from replica -> release the R lock
3. When creating snapshot: RW lock -> get data from replica -> do snapshot creation if needed -> release the RW lock
4. When delete snapshot: RW lock -> get data from replica -> do snapshot deletion if needed -> release the RW lock

We should do it at the engine level but not the manager API level because there are multiple managers that can do snapshot operations at the same time so we cannot do locking

**Comment by innobead** [comment]
@derekbit @PhanLe1010 adding validation will help? to ensure the snapshot name unique at least.

**Comment by PhanLe1010** [comment]
Adding validation in Longhorn API can reduce the risk but cannot be 100% guaranteed. I think adding a lock and validation to engine process is the complete solution

**Comment by derekbit** [comment]
Close and tracked in https://github.com/longhorn/longhorn/issues/4250.
