### ISSUE TITLE
[QUESTION] recover volumes from disk files only

### ISSUE THREAD

**Issue by StodaraHodan** [longhorn/longhorn#3850]
## Question
Suppose someone only has the files from the disk aka the /var/lib/longhorn directory, how would i try to recover the data on the volumes. there are some .img files from the volume head / snapshots in the replica subfolder so there must be some way to restore a proper block volume from this?

Background, after an upgrade from k3s 1.21 to 1.22 my longhorn 1.1.2 installation didn't work anymore because of some deprecated api version or something, backup didn't work because nfs couldn't mount (had this problem a lot, and frankly this is the reason i move away from longhorn), so i was stuck rescuing the files as far as i had still access, and then tried recovering by installing a newer longhorn version while keeping the data following this: https://github.com/longhorn/longhorn/issues/3166

now this didn't work and here i am with all this mess. nothing business critical just my cluster for private use but still, i was considering using longhorn at work but my numerous issues and reliability issues isn't inspiring much confidence in the project.
primarily backup was never working reliably for me.

**Comment by shuo-wu** [comment]
1. You can follow [this doc](https://longhorn.io/docs/1.2.4/advanced-resources/data-recovery/export-from-replica/) and see how to recover data from a replica directory.
2. Can you talk more about the NFS mount issue you encountered? Or is there already a ticket for that? We will try out best to fix these issues anyway.

**Comment by StodaraHodan** [comment]
1. thank you very much, i think i even stumbled across this document but didn't realize it was for the disk files itself
2. yeah, i didn't open any ticket yet because i wanted to try a newer version of longhorn first to see if these errors are gone. mainly the error messages had to do with mkdir commands on the internal mountpoint in longhorn that failed because the dir already exists or it was in a read-only state. sorry, i don't have the exact messages anymore. 
The last one i think i resolved by desperately changing the permissions on the nfs share to 777, that's also how i got a backup from two weeks ago to work, so the restore of the single replica isn't that important now, but i will still try to see if it works. 
I will watch longhorn and the closely the following weeks and see if the errors return, if they do i would create a ticket for that.
