### ISSUE TITLE
[TASK] Build dependent host libraries (liblonghorn & tgt) based on rpm for BCI adoption

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#3854]
## What's the task? Please describe

https://github.com/longhorn/longhorn-engine/pull/685#discussion_r851091951

## Describe the items of the task (DoD, definition of done) you'd like

- [ ] Update longhorn-engine dockerfile to build/use liblonghorn/tgt rpm installation

cc @derekbit  @yangchiu

**Comment by derekbit** [comment]
Any benefit for the rpm package?

**Comment by innobead** [comment]
It should be just a difference between prebuld and runtime build (source build). The benefit would be just a build time and unexpected runtime build failure.

**Comment by innobead** [comment]
My answer is wrong after checking the context again. iscsi tgt build is always runtime build no matter what build way is used. The only difference could be what things will be installed by `make install` compared with rpm build spec.

Let's close this issue unless this is really needed.
