### ISSUE TITLE
longhorn pgbench better than local persistent volume

### ISSUE THREAD

**Issue by gaow1423** [longhorn/longhorn#3857]
## Question
I have been doing pgbench for various storage options including longhorn. I also did that for local SSD as the baseline for reference. Surprisingly, the latency and TPS for longhorn are much better than that of local SSD which doesn't make sense. I wonder does longhorn have some really smart caching? I appreciate any insight and thought. here is the graph I got:

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/25094170/164615235-70dac201-afa5-4e51-b043-d0db5cb8528e.png">

cpu idle percentage and system cpu usage:
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/25094170/164615485-7948c7df-feac-4c2d-9038-c7b7854d63f4.png">

I have also run the iostat to check IOPS and write throughput on local SSD and longhorn nodes, I see that the write speed for longhorn is much higher than that of local SSD. With the same write request per second, the longhorn got higher write kb per second. it looks to me that somehow the packet written into longhorn volume is large than local SSD. Is there any buffer or optimization for longhorn to get the more data transfer for each write? here is the screenshot, the above one is local ssd, and the bottom one is longhorn.

i got this data with 1 replica longhorn
<img width="396" alt="image" src="https://user-images.githubusercontent.com/25094170/164616046-dbdf212f-bff3-4fca-a6bf-e2d75707b6d2.png">

## Environment

 - Longhorn version: 1.2.4(latest)
 - Kubernetes version: 1.20.15-gke.4100
 - Node config
   - OS type and version: unbuntu
   - CPU per node: 8
   - Memory per node: 64g
   - Disk type 4 * 375G ssd
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): GKE

## Additional context
I used pgbench from kubestone to do the benchmark. I even manually run pgbench directly on the postgres pod, but got the similar results. longhorn just outperformed all other options. The claim size for DB is the same.

**Comment by liyimeng** [comment]
what is the units of your number here? iops? bandwidth?

**Comment by derekbit** [comment]
@gaow1423 
Can you provide the information as @liyimeng mentioned?
Longhorn does not have cache design internally and only relies on the filesystem page cache.

I'm not familiar with the pgbench details, e.g. the io pattern, so I cannot conclude the results.
By the way, you can run [kbench](https://github.com/yasker/kbench) to see and compare the results. This will help understand the difference of the storage systems more.

**Comment by gaow1423** [comment]
> what is the units of your number here? iops? bandwidth?

post updated

**Comment by gaow1423** [comment]
> @gaow1423 Can you provide the information as @liyimeng mentioned? Longhorn does not have a cache design internally and only relies on the filesystem page cache. I'm not familiar with the pgbench details, e.g. the io pattern, so I cannot give a conclusion from the results. By the way, you can run [kbench](https://github.com/yasker/kbench) to see and compare the results. This will help understand between difference of the storage systems more.

@derekbit thank you for replying. I ran iostat on both pods. I see the speed of postgres writting into longhorn volume is much higher than that of local ssd, even roughly they have the same number of write per second (see the screenshot in the post). Somehow, for longhorn volume, it received more data per write. is there anything special for longhorn volume that cause this?

**Comment by gaow1423** [comment]
> Hello @gaow1423
> 
> > Somehow, for longhorn volume, it received more data per write. is there anything special for longhorn volume that cause this?
> 
> If the number of the replicas is 3, LH writes the data to each replica. Where did you measure the quantity of the received data? In the longhorn node or in the pod mounting the volume?

I test it with 1 replica only. I measure the metrics on postgres pod. Even with 3 replica, the number is still very high comparing to local persistent volume.

iostat metric sampled every 30 seconds(sdf is created by longhorn): 
![Screen Shot 2022-04-25 at 9 56 40 AM](https://user-images.githubusercontent.com/25094170/165138543-53b10365-c062-4fa3-85a6-7ac9ee93b321.png)
the write speed outperforms local persistent volume.

node top metrics:
<img width="905" alt="Screen Shot 2022-04-25 at 9 56 14 AM" src="https://user-images.githubusercontent.com/25094170/165138802-d6b11bb7-2dd6-46c0-ae91-97f64a0d4759.png">

htop on that working node, CPU is somehow very high
![Screen Shot 2022-04-25 at 9 57 11 AM](https://user-images.githubusercontent.com/25094170/165138899-d0bfa97b-ea73-415f-ac04-8cad0d1d1d43.png)
