### ISSUE TITLE
[BUG] longhorn-manager DeamonSet doesn't behave according to the taint tolaration

### ISSUE THREAD

**Issue by Socotoly** [longhorn/longhorn#3859]
## Describe the bug

The longhorn-manager DeamonSet doesn't get deployed to the tainted nodes, with appropriate toleration applied, but other components do like (engine, and csi-plugin).

## To Reproduce

1. Cluster with 2 dedicated longhorn nodes
2. Add taints "CriticalAddonsOnly=true:NoExecute" and "StorageOnly=true:NoExecute" to longhorn nodes
3. Add taint tolaration either in Longhorn UI or via yaml during installation
4. All longhorn components get deployed to the tanited nodes except longhorn-manager
5. longhorn nodes doesn't appear in longhorn UI or appear down if the toleration is added after installation via UI

## Expected behavior

longhorn-manager get deployed to the tainted nodes when applicable taint tolerence is present. 

## Environment

 - Longhorn version: 100.1.2+up1.2.4 
 - Installation method: Rancher Catalog App (Rancher v2.6.4)
 - Kubernetes distro: RKE2 v1.22.8+rke2r1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 4
   - Number of longhorn node in the cluster: 2
 
## Additional context

I checked the yaml for the longhorn-manager DeamonSet and I noticed the "toleration" section is messing, adding it will resault in successful deployment to tainted nodes

**Comment by derekbit** [comment]
Hello @Socotoly,
A little confused. Did you deploy the longhorn-manager on the nodes with taint toleration successfully in the end after updating the `tolerations:` in the yaml?

Related doc: https://longhorn.io/docs/1.2.4/advanced-resources/deploy/taint-toleration/#setting-up-taints-and-tolerations-during-installing-longhorn

**Comment by Socotoly** [comment]
Hi @derekbit 

Sorry my bad, I was following docs for v1.0.2 without noticing. The rancher [docs](https://rancher.com/docs/rancher/v2.6/en/longhorn/) redirects to the v1.0.2

The link you provided solved the issue.
Thanks.
