### ISSUE TITLE
[BACKPORT-v1.2.x][BUG] fatal error: concurrent map writes

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#3864]
backport https://github.com/longhorn/longhorn/issues/3077

**Comment by cchien816** [comment]
**Validate on v1.2.x-head 20220426
Result Pass**

Using below test steps can reproduce `fatal error: concurrent map writes` on v1.2.4, but not observed on v1.2.x head :

1.Create one node LH cluster
2. Trace the longhorn manager pod log by kubectl logs <longhorn manager pod name> -n longhorn-system -f
3. run shell script mentioned in https://github.com/longhorn/longhorn/issues/3077#issuecomment-1092544440 step 3

Result : On v1.2.x head, no `fatal error: concurrent map writes` happened on longhorn-manager, no restart happened on longhorn-manager
