### ISSUE TITLE
[TASK] Create golang testing for longhorn with SPDK

### ISSUE THREAD

**Issue by keithalucas** [longhorn/longhorn#3871]
## Integration testing for SPDK

As more functionality is added to SPDK, we need to have integration tests like those in the longhorn-engine.  

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] Create a golang based testing for SPDK that can perform SPDK operations like snapshots or adding new replicas while writing data to the volume.
- [ ] Create some initial tests.

**Comment by keithalucas** [comment]
In order to the this, the following functionality will be implemented:
- [ ] Create API to launch and stop a SPDK process.
- [ ] Create API to create an empty file of a certain size.
- [ ] Create API to register the empty file as a loopback device.
- [ ] A means to reset an instance of SPDK, i.e. remove all volumes, replicas, logical stores, and devices.   This is to return to a state to run another test without restarting the instance.   This will query the current state of SPDK and remove everything.
- [ ] Create API to create a slow device with `dmsetup` from a loopback device.  This is to make writes less likely to be completed at the same time such that when a snapshot or replica add occurs each replica may be in a different state.
- [ ] Create API to remove a slow device.
- [ ] Create API to remove a loopback device.

Some of the initial tests will be:
- [ ] Create a longhorn volume with one replica in one SPDK process.
- [ ] Create a longhorn volume with three replicas in one SPDK process.
- [ ] Create a longhorn volume with three replicas in three separate SPDK processes.
- [ ] Create a snapshot on longhorn volume with replicas on fast and slow disks.

Also, this will be done in longhorn-spdk and we will:
- [ ] Download and build SPDK in a container
- [ ] Run the tests in the build container

**Comment by innobead** [comment]
cc @DamiaSan

**Comment by innobead** [comment]
Closing, we will reorganize SPDK issues.
