### ISSUE TITLE
Adding existing volume as persistent volume

### ISSUE THREAD

**Issue by paulmorabito** [longhorn/longhorn#388]
Hi,

I'm using Rancher 2.1.6 on bare metal and I have installed Longhorn 0.3.3. I have restored some volumes from backups (as I had to wipe and rebuild my cluster). These volumes appear in Longhorn but I am unsure how to add the persistent volume to Rancher so I can create a PVC and link it to a workload.  

If I try to add persistent volume and select Longhorn, it asks for a name. Should this be the name of the existing volume? The settings seem to be more about defining a new volume. If not, where can I do this?

Thanks,

**Comment by yasker** [comment]
Hi @paulmorabito 

There are still a few changes we need to do to integrate with Rancher. Currently, we can workaround the problem using kubectl. You can take a look at https://www.youtube.com/watch?v=vRqvz-Ii49A&t=3328s which contains the demo on how to restore the volume to a workload.

I will keep this item open to track the effort.

**Comment by paulmorabito** [comment]
Thanks for the reply. This worked!
