### ISSUE TITLE
[IMPROVEMENT] Make storage parameter "migratable" available in the helm chart

### ISSUE THREAD

**Issue by ibrokethecloud** [longhorn/longhorn#3880]
## Is your improvement request related to a feature? Please describe
Currently harvester packaging for longhorn uses helm post-install and post-upgrade hooks to replace the longhorn-storageclass secret with a longhorn  storageclass override which introduces `migratable:true` in the storage class parameters.

Fleet is currently unable to handle post-install / post-ugprade hooks, and reports the longhorn-storageclass configmap as missing because this has been recreated by the post-install webhook.

This is possibly related to the issue: https://github.com/rancher/fleet/issues/257

## Describe the solution you'd like
We should expose the storage class parameter `migratable` in the helm chart for longhorn.

This will allow harvester to leverage this setting by just defining value overrides.

## Additional context

This should help us address:  https://github.com/harvester/harvester/issues/2088

**Comment by joshimoo** [comment]
This can be done, but I am not sure why harvester isn't creating it's own storage class with parameters purposefully built for harvester which then gives them control/update ability independent from longhorn's default parameter set.
REF: https://github.com/harvester/harvester/issues/2088#issuecomment-1107551647
REF: https://github.com/longhorn/longhorn/issues/2594#issuecomment-843950488

**Comment by ibrokethecloud** [comment]
@joshimoo would it be better in that case to make the storageclass definition configmap optional? with the default being true for backward compatibility? This we way we don't need to patch the default storage class created by the longhorn storage chart. I can create another PR for the same.

**Comment by innobead** [comment]
> @joshimoo would it be better in that case to make the storageclass definition configmap optional? with the default being true for backward compatibility? This we way we don't need to patch the default storage class created by the longhorn storage chart. I can create another PR for the same.

No, `migratable` is a very implicit function actually for migratable volumes used in virtual workloads, but the change here is actually fine to expose in our helm template and users are able to configure it via values.yaml, because that's the public interface Longhorn provides to users. 

For `migratable` or any unconfigured parameters in the default storage class, we should not make them with the default value false, that's not intended.

For any downstream callers like Harvester, ideally, there should be a specific storage class created by itself as @joshimoo mentioned.

**Comment by innobead** [comment]
@longhorn/qa For QA, we just need to verify if after the chart installation, the setting of migratable will take effect in the default storage class.

**Comment by kaxing** [comment]
Will begin test when chart file for v1.3.0 preview or rc come out https://github.com/longhorn/charts

**Comment by cchien816** [comment]
When I tried using install Longhorn by chart https://github.com/longhorn/longhorn/tree/master/chart , longhorn-admission-webhook pod will throw below error :
```
E0428 06:53:48.361080 1 reflector.go:178] [github.com/longhorn/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:117](http://github.com/longhorn/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:117): Failed to list *v1beta2.Orphan: [orphans.longhorn.io](http://orphans.longhorn.io/) is forbidden: User "system:serviceaccount:longhorn-system:longhorn-service-account" cannot list resource "orphans" in API group "[longhorn.io](http://longhorn.io/)" at the cluster scope
```
This error make longhorn installation stuck and did not generate default storageclass.
With out storageclass, this improvement can not verify now.

 I will wait this [PR](https://github.com/longhorn/longhorn/pull/3899) merged then test again ASAP, thank you

**Comment by cchien816** [comment]
**Validated on longhorn master-head 20220429
Result Failed**

After installed helm, clone longhorn repo and switched to longhorn/chart floder
1. Use default setting in values.yaml which `migratable: false`  and run command `helm install -n longhorn-system longhorn .` Longhorn can successfully installed but
2. If use `migratable: true` in  values.yaml and run command `helm install -n longhorn-system longhorn .`, longhorn-manager ```
will get err as below let Longhornstuck at installing
```
ime="2022-04-29T01:24:58Z" level=debug msg="Walking through the upgrade path v1.1.0 to v1.2.0"
time="2022-04-29T01:24:58Z" level=info msg="upgrade from v1.1.0 to v1.2.0: Starting storageClass recurring job translation" namespace=longhorn-system translate=storage-class-recurring-jobs
time="2022-04-29T01:24:58Z" level=error msg="Upgrade failed: upgrade resources failed: upgrade from v1.1.0 to v1.2.0: upgrade recurring jobs failed: upgrade from v1.1.0 to v1.2.0: translate storage class recurring jobs failed: failed to decoding YAML string: v1.StorageClass.Parameters: ReadString: expects \" or n, but found t, error found in #10 byte of ...|ratable\":true,\"numbe|..., bigger context ...|ed\",\"fromBackup\":\"\",\"fsType\":\"ext4\",\"migratable\":true,\"numberOfReplicas\":\"3\",\"staleReplicaTimeout\":\"|..."
time="2022-04-29T01:24:58Z" level=info msg="Upgrade leader lost: worker2"
time="2022-04-29T01:24:58Z" level=fatal msg="Error starting manager: upgrade resources failed: upgrade from v1.1.0 to v1.2.0: upgrade recurring jobs failed: upgrade from v1.1.0 to v1.2.0: translate storage class recurring jobs failed: failed to decoding YAML string: v1.StorageClass.Parameters: ReadString: expects \" or n, but found t, error found in #10 byte of ...|ratable\":true,\"numbe|..., bigger context ...|ed\",\"fromBackup\":\"\",\"fsType\":\"ext4\",\"migratable\":true,\"numberOfReplicas\":\"3\",\"staleReplicaTimeout\":\"|..."
```

This error blocked the validation of this improvement

**Comment by cchien816** [comment]
Using fresh environment with longhorn master head 20220504 cloned, After set `migratable: true` to install Longhorn by helm, I got error in longhorn-manager pod.

Test environment:

- HELM: 3.8.2
- Ubuntu 20.04
- Longhorn master head 20220504

Install method
1. Clone Longhorn repo
2. Switch into folder `chart`
3. Modify `migratable: true` in values.yaml
4. Run command `helm install -n longhorn-system longhorn .`

Error log from longhorn-manager pod
```
W0504 02:08:15.054566       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-05-04T02:08:15Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr, ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/*': No such file or directory\n, error exit status 2"
I0504 02:08:15.071398       1 leaderelection.go:242] attempting to acquire leader lease  longhorn-system/longhorn-manager-upgrade-lock...
I0504 02:08:15.074791       1 leaderelection.go:252] successfully acquired lease longhorn-system/longhorn-manager-upgrade-lock
time="2022-05-04T02:08:15Z" level=info msg="Start upgrading"
time="2022-05-04T02:08:15Z" level=info msg="No API version upgrade is needed"
time="2022-05-04T02:08:15Z" level=debug msg="Walking through the upgrade path v0.7.0 to v0.8.0"
time="2022-05-04T02:08:15Z" level=debug msg="Walking through the upgrade path v1.0.0 to v1.0.1"
time="2022-05-04T02:08:15Z" level=debug msg="Walking through the upgrade path v1.0.2 to v1.1.0"
time="2022-05-04T02:08:15Z" level=debug msg="Walking through the upgrade path v1.1.0 to v1.1.1"
time="2022-05-04T02:08:15Z" level=debug msg="Walking through the upgrade path v1.1.0 to v1.2.0"
time="2022-05-04T02:08:15Z" level=info msg="upgrade from v1.1.0 to v1.2.0: Starting storageClass recurring job translation" namespace=longhorn-system translate=storage-class-recurring-jobs
time="2022-05-04T02:08:15Z" level=error msg="Upgrade failed: upgrade resources failed: upgrade from v1.1.0 to v1.2.0: upgrade recurring jobs failed: upgrade from v1.1.0 to v1.2.0: translate storage class recurring jobs failed: failed to decoding YAML string: v1.StorageClass.Parameters: ReadString: expects \" or n, but found t, error found in #10 byte of ...|ratable\":true,\"numbe|..., bigger context ...|ed\",\"fromBackup\":\"\",\"fsType\":\"ext4\",\"migratable\":true,\"numberOfReplicas\":\"3\",\"staleReplicaTimeout\":\"|..."
time="2022-05-04T02:08:15Z" level=info msg="Upgrade leader lost: worker2"
time="2022-05-04T02:08:15Z" level=fatal msg="Error starting manager: upgrade resources failed: upgrade from v1.1.0 to v1.2.0: upgrade recurring jobs failed: upgrade from v1.1.0 to v1.2.0: translate storage class recurring jobs failed: failed to decoding YAML string: v1.StorageClass.Parameters: ReadString: expects \" or n, but found t, error found in #10 byte of ...|ratable\":true,\"numbe|..., bigger context ...|ed\",\"fromBackup\":\"\",\"fsType\":\"ext4\",\"migratable\":true,\"numberOfReplicas\":\"3\",\"staleReplicaTimeout\":\"|..."
```

cc @innobead, @kaxing, @ibrokethecloud

**Comment by cchien816** [comment]
**Validate on longhorn master-head 20220505
Result Pass**

After installed helm, clone longhorn repo and switched to longhorn/chart floder
1. Use default setting in values.yaml which is `migratable: false` and run command `helm install -n longhorn-system longhorn .` then observe default storageclass can not see `migratable` parameter
2. Set `migratable: true` in values.yaml and run command `helm install -n longhorn-system longhorn .` then observe default storageclass can see `"migratable": "true",` in parameters which affects the setting in values.yaml


**migratable: true**
```
{
    "allowVolumeExpansion": true,
    "apiVersion": "storage.k8s.io/v1",
    "kind": "StorageClass",
    "metadata": {
        "annotations": {
            "longhorn.io/last-applied-configmap": "kind: StorageClass\napiVersion: storage.k8s.io/v1\nmetadata:\n  name: longhorn\n  annotations:\n    storageclass.kubernetes.io/is-default-class: \"true\"\nprovisioner: driver.longhorn.io\nallowVolumeExpansion: true\nreclaimPolicy: \"Delete\"\nvolumeBindingMode: Immediate\nparameters:\n  numberOfReplicas: \"3\"\n  staleReplicaTimeout: \"30\"\n  fromBackup: \"\"\n  fsType: \"ext4\"\n  migratable: \"true\"\n  dataLocality: \"disabled\"\n",
            "storageclass.kubernetes.io/is-default-class": "true"
        },
        "creationTimestamp": "2022-05-05T09:06:17Z",
        "name": "longhorn",
        "resourceVersion": "1063",
        "uid": "d4083125-beb1-40f0-b07e-7d6c6c978524"
    },
    "parameters": {
        "dataLocality": "disabled",
        "fromBackup": "",
        "fsType": "ext4",
        "migratable": "true",
        "numberOfReplicas": "3",
        "staleReplicaTimeout": "30"
    },
    "provisioner": "driver.longhorn.io",
    "reclaimPolicy": "Delete",
    "volumeBindingMode": "Immediate"
}
```
**migratable: false**
```
{
    "allowVolumeExpansion": true,
    "apiVersion": "storage.k8s.io/v1",
    "kind": "StorageClass",
    "metadata": {
        "annotations": {
            "longhorn.io/last-applied-configmap": "kind: StorageClass\napiVersion: storage.k8s.io/v1\nmetadata:\n  name: longhorn\n  annotations:\n    storageclass.kubernetes.io/is-default-class: \"true\"\nprovisioner: driver.longhorn.io\nallowVolumeExpansion: true\nreclaimPolicy: \"Delete\"\nvolumeBindingMode: Immediate\nparameters:\n  numberOfReplicas: \"3\"\n  staleReplicaTimeout: \"30\"\n  fromBackup: \"\"\n  fsType: \"ext4\"\n  dataLocality: \"disabled\"\n",
            "storageclass.kubernetes.io/is-default-class": "true"
        },
        "creationTimestamp": "2022-05-05T09:08:45Z",
        "name": "longhorn",
        "resourceVersion": "1063",
        "uid": "a2ec66db-f01f-493c-822b-3138e8c8a76b"
    },
    "parameters": {
        "dataLocality": "disabled",
        "fromBackup": "",
        "fsType": "ext4",
        "numberOfReplicas": "3",
        "staleReplicaTimeout": "30"
    },
    "provisioner": "driver.longhorn.io",
    "reclaimPolicy": "Delete",
    "volumeBindingMode": "Immediate"
}
```
