### ISSUE TITLE
[BUG] A snapshot has a child that is no-longer exist in the snapshot chain

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3883]
## Describe the bug

In theory, it is not possible that a snapshot has multiple children if users don't perform snapshot reverting. However, I do see the following situation:
1. There is no snapshot reverting performed in this case. Just creating and deleting.
1. A snapshot has a child that is no-longer exist in the snapshot chain.
1. There are multiple volume heads

<img width="813" alt="Screen Shot 2022-04-20 at 4 43 12 PM" src="https://user-images.githubusercontent.com/22139961/164577390-028ab11c-84a0-432b-9dba-d4541818ceab.png">

## To Reproduce
I cannot reproduce this one by UI. But with the new feature [snapshot CRD](https://github.com/longhorn/longhorn/pull/3876), we can try to reproduce by repeatedly deleting snapshot and creating new snapshot CRs

## Log or Support bundle
[longhorn-support-bundle_ebbe707f-3065-40d9-a7b5-9a249d680b32_2022-04-21T23-28-39Z.zip](https://github.com/longhorn/longhorn/files/8536100/longhorn-support-bundle_ebbe707f-3065-40d9-a7b5-9a249d680b32_2022-04-21T23-28-39Z.zip)

## Environment

 - Longhorn version: master-head 04/21/2022

**Comment by PhanLe1010** [comment]
**Workaround**:
Detach and attach the volume will reload the snapshot chain and children map

**Comment by PhanLe1010** [comment]
Update. We can reliably reproduce this one by the following step:
1. create snapshot with name `snap1`
2. delete `snap1`
3. create `snap2`
4. delete `snap2`
5. create `snap1`

**Comment by PhanLe1010** [comment]
Ready for testing but please don't close as there is a low priority item about the unit test for this issue https://github.com/longhorn/longhorn-engine/pull/696#issuecomment-1108231312

**Comment by cchien816** [comment]
**Validate on master-head 20220506
Result Pass**

Test steps from [comment](https://github.com/longhorn/longhorn/issues/3883#issuecomment-1105938840)

1. Using engine image `chanow/longhorn-engine:issue3883`,  this image did not contain `delete(r.diskChildrenMap, name)` in `pkg/replica/replica.go` line 495 which means not include this [PR](https://github.com/longhorn/longhorn-engine/pull/696/files) to test. In volume detail page the snapshot chain can not display correctly (stuck at loading icon). Which reflect the  snapshot **messed up** situation.
![Screenshot from 2022-05-06 15-06-05](https://user-images.githubusercontent.com/73337386/167083995-3c7d760c-3ef0-46e7-9642-e03b96fc0d15.png)

2. Using master-head 20220506 with default engine-image, after perform test [steps](https://github.com/longhorn/longhorn/issues/3883#issuecomment-1105938840), the snapshot chain not messed up and in volume detail page snapshot chain can display correctly
