### ISSUE TITLE
Investigate: Reboot a node result in temporarily error of `engine is deploying` instead of ready

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#389]
```
list snapshot: cannot get client for volume testvol: cannot get engine client with image rancher/longhorn-engine:v0.3.3: engine image ei-6dd7ed5e (rancher/longhorn-engine:v0.3.3) is not ready, it's deploying
```

Need to investigate. As long as the engine exists on the node that the call is initiating, it should be allowed.

**Comment by yasker** [comment]
If one node is down or malfunction, cause engine image daemon to fail to get desired number of pods, the whole engine image would become `deploying` instead of `ready`, which prevents all the engine level operations like `snapshot` from taking place.

The engine image status needs to be more fine grain controlled. As long as the node issuing the command has engine image ready in place locally, it should be allowed.

**Comment by yasker** [comment]
Need to rethink once #677 in place.

**Comment by tedder** [comment]
Is this the cause of an error like this? If not I can open another issue.
```
  Warning  ProvisioningFailed    4m1s (x6 over 19m)    rancher.io/longhorn_csi-provisioner-..
  failed to provision volume with StorageClass "disk3": rpc error: code = Internal desc = Bad response statusCode [500].
  Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to create volume: unable to create volume pvc-3dab17fe-a284-4361-be4a-b8052db70572:
  &{OwnerID: Size:2147483648 Frontend:blockdev FromBackup: NumberOfReplicas:3 StaleReplicaTimeout:2880
  NodeID: MigrationNodeID: PendingNodeID: EngineImage: RecurringJobs:[] BaseImage: Standby:false
  InitialRestorationRequired:false DiskSelector:[ssd] NodeSelector:[] DisableFrontend:false}:
  cannot create volume with image longhornio/longhorn-engine:v0.6.2: engine image
  ei-3827e67c (longhornio/longhorn-engine:v0.6.2) is not ready, it's deploying] from
  [http://longhorn-backend:9500/v1/volumes]
```
I have that image running on all 5 relevant nodes.

**Comment by yasker** [comment]
@tedder It looks like a different one. The bug mentioned here is temporary and will resolve by itself moments later.

Can you check if your `engine-image-ei-xxx` daemonset is all ready and `instance-manager-e-xxx` and `instance-manager-r-xxx` running once per node? Also, manager's log would help.

**Comment by tedder** [comment]
@yasker I started creating the issue and I believe the problem is I had a node tainted, so the three daemonsets were running on N-1 nodes. I'll keep my partial text in case you want it but I don't want to submit if it isn't useful.

**Comment by yasker** [comment]
@tedder Yeah I think the taint is the issue. Longhorn currently supports to tolerant the taint, but a non-tolerated taint may result in Longhorn think the deployment is incomplete. There was an issue opened https://github.com/longhorn/longhorn/issues/805 but we didn't get responses from the original author.

**Comment by ThomasK33** [comment]
I just experienced the same error message as described here.

In my case the "instance-manager" pod was stuck on "creating" on the restarted node.
Deleting it, caused a "fresh" recreation that instantly started working and the error was gone.

**Comment by yasker** [comment]
@ThomasK33 Anything leads `instance-manager` stuck in `creating`?  Sounds like somehow Kubernetes failed to create the pod.

**Comment by yasker** [comment]
Haven't able to reproduce the issue recently. The issue is probably caused by the engine image controller doesn't transfer ownership before, but it should be fixed in https://github.com/longhorn/longhorn-manager/commit/2e4ece11856d030082a7c47cea01cb1924b5325b .

Close this issue for now. If it happens again, feel free to reopen.

**Comment by yasker** [comment]
Also, https://github.com/longhorn/longhorn/issues/961 should help with pinpoint the issue if it happens again.
