### ISSUE TITLE
[DOC] Update the volume size related doc after introducing the snapshot prune feature

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3894]
## What's the task? Please describe

The follow-up of issue https://github.com/longhorn/longhorn/issues/3613#issuecomment-1102362618

**Comment by innobead** [comment]
This can be after 1.3.0 out.

**Comment by shuo-wu** [comment]
Close this since the doc update is already tracked in https://github.com/longhorn/longhorn/issues/4158
