### ISSUE TITLE
[IMPROVEMENT] Support failed/obsolete orphaned backup cleanup

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#3898]
## Is your improvement request related to a feature? Please describe

In some cases, there will be some failed backups still staying in the system, so we should provide an option for users to clean them up automatically. After failed backups cleanup, users should be still able to check the previous audit events of failed backups as usual. 

cc @joshimoo

**Comment by innobead** [comment]
cc @PhanLe1010 @joshimoo @derekbit

**Comment by innobead** [comment]
@mantissahz A new setting was introduced, so you need to update manifests in longhorn/longhorn as well w/ question.yaml updated as well.

**Comment by chrisc1981** [comment]
**Verified on longhorn-manager master-head `76f0fb`
Result Pass**

Test steps or (https://github.com/longhorn/longhorn/issues/3898#issuecomment-1214773993):
1. Deploy Longhron and backupstore
2. Set `Failed Backup Time to Live ` to 5 (by default it's 14400 minutes)
3. Create a volume then attach to worker node and write some data
4. Create a backup to backup target then crash the instance-manager-r such as this command `kubectl delete pods -l longhorn.io/instance-manager-type=replica -n longhorn-system --wait`.
5. Then backup state should become Error in a few seconds.
6. Wait after `Failed Backup Time to Live ` passed
7. Verify failed backup had been deleted from UI and command `kubectl get backups.longhorn.io -n longhorn-system`
8. Test on both S3 and nfs type of backupstore
