### ISSUE TITLE
[IMPROVEMENT] Multiple Threads for S3 Backup

### ISSUE THREAD

**Issue by michaelkoetter** [longhorn/longhorn#3900]
## Is your improvement request related to a feature? Please describe

It seems the S3 backup uses a single thread to upload data. This will limit performance with some targets, for example minio (see below for benchmarks) or Backblaze B2.

## Describe the solution you'd like

Implement multi-threaded (concurrent) uploads in S3 backupstore, add an option (or environment var) to specify the number of threads.

## Describe alternatives you've considered

None

## Additional context

Simple benchmarks done with https://github.com/chinglinwen/s3-benchmark,
all speeds in MB/s

### SSD-backed minio

Standalone "minio server .." instance backed by an NvME SSD. The network is 1Gb.

|concurrency-size|uloadspeed|downloadspeed|
|--|--|--|
|100-2M|73.61|64.40|
|10-2M|107.88|105.19|
|1-2M|68.69|91.76|

The 10-thread test maxes out the link, while the 1-thread test is 30% slower.

### SMB-backed minio

Standalone "minio server .." instance backed by an SMB share. The network is 1Gb. Max write speed (dd test) for the SMB share is around 50 MB/s.

|concurrency-size|uloadspeed|downloadspeed|
|--|--|--|
|50-2M|37.44|81.41|
|10-2M|24.24|99.49|
|1-2M|4.68|64.49|

Here the difference is more dramatical. The 50-thread test comes a lot closer to the theoretical limit than the 1-thread, which is really slow in this case. 

Backup of an actual Longhorn Volume to this minio instance seems to align with the 1-2M test result, maybe even a tad slower (~16GiB took 53 minutes to backup).

**Comment by derekbit** [comment]
@michaelkoetter 
Thanks for the investigation. We have a [ticket](https://github.com/longhorn/longhorn/issues/1409) tracking the backup performance and will have improvements.

**Comment by derekbit** [comment]
Closed. Track in https://github.com/longhorn/longhorn/issues/5189.
