### ISSUE TITLE
[BUG] Many e2e case failed by FileNotFoundError

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#3905]
## Describe the bug

In e2e master build [107](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/107/) There were many cases failed by FileNotFoundError :
`FileNotFoundError: [Errno 2] No such file or directory: 'findmnt'`
`FileNotFoundError: [Errno 2] No such file or directory: 'mkfs.ext4'`

## To Reproduce

1. Observe e2e daily run result

## Expected behavior

Should not have this error as before

## Log or Support bundle

N/A

## Environment

 N/A

## Additional context

N/A

**Comment by innobead** [comment]
@cchien816 good to follow up 👍 

https://github.com/longhorn/longhorn-tests/pull/952 merged, so you can trigger another test to see if the problem is fixed.

**Comment by cchien816** [comment]
Close this issue because after code merged, those FileNotFoundError not happened on pipeline.
The result can refer to build [108](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/108/), [109](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/109/), [110](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/110/)
