### ISSUE TITLE
[IMPROVEMENT] liveness and readiness probes with longhorn csi plugin daemonset

### ISSUE THREAD

**Issue by sharanbabumg** [longhorn/longhorn#3907]
As of now after patching of our worker nodes are are rebooting every node after patching, but we ended up with pvc not able attach or mount issues and pods were stuck in container creating state only.

MountVolume.MountDevice failed for volume "pvc-d0af4c3e-355d-40db-88d5-cbec82fe3f00" : rpc error: code = Internal desc = Get "[http://longhorn-backend:9500/v1/volumes/pvc-d0af4c3e-355d-40db-88d5-cbec82fe3f00":](http://longhorn-backend:9500/v1/volumes/pvc-d0af4c3e-355d-40db-88d5-cbec82fe3f00%22:) dial tcp 172.26.151.93:9500: connect: no route to host

The above error keep on triggering and for csi plugin pods and pvc's. Can we get liveness and readiness probe configurations for longhorn-csi-plugin daemonsets so that whenever we face issue for these pods we can keep alerts for these pods and fix immediately.

driver name driver.longhorn.io not found in the list of registered csi drivers

Now the workaround we perform is restarting longhorn-cis-plugin pods.

**Comment by sharanbabumg** [comment]
@PhanLe1010  Kindly reopen the task and give some fix or work around this. As we have deployed longhorn in uat and production k8s clusters. After patching activity on worker nodes the nodes get rebooted and the kubelet restart happens and we are facing issue with longhorn-csi-plugin pods to be in crashloopbackoff state so we manually need to restart pods for now as work around to fix the application pods which are in container creating state. 

This would not be a permananet solution, as customer come to know the state of their pods via alerts triggered to their emails. So if this issue can be fixed permanently this would be great help for us otherwise will loose customers.

If possible kindly add readiness and liveness probe for longhorn-csi-plugin

Kindly treat this on priority and update us asap.

**Comment by innobead** [comment]
> We should also consider implementing the GRPC Probe for the csi plugin, to do an active health check.
> 
> * [https://github.com/container-storage-interface/spec/blob/master/spec.md#probe](https://github.com/container-storage-interface/spec/blob/master/spec.md?rgh-link-date=2022-07-12T01%3A20%3A35Z#probe)
> * [longhorn/longhorn-manager@`2cc3d24`/csi/identity_server.go#L29-L28](https://github.com/longhorn/longhorn-manager/blob/2cc3d24c50ffb19cab04f3a7a55155a7fd82006b/csi/identity_server.go#L29-L28)

https://github.com/kubernetes-csi/livenessprobe

**Comment by sharanbabumg** [comment]
@innobead @PhanLe1010  Can i get some update on this request? Or else may i know iscsi/nfs-client package only required or else nfs and iscsi service also need to be running and one more point iscsi installation and nfs installation daemonset pods should also be running on the cluster?

**Comment by PhanLe1010** [comment]
@sharanbabumg We have planned this ticket for Longhorn v1.4.0 and may be backported to v1.2.5 and v1.3.1. You can follow the release timeline for those releases

Btw, does this issue happen regularly in your cluster? It is expected to not be a regular issue

**Comment by c3y1huang** [comment]
Need to make the probe less verbose.
https://github.com/longhorn/longhorn-manager/pull/1570#discussion_r1034264740

**Comment by c3y1huang** [comment]
> Need to lower the verbosity level. [longhorn/longhorn-manager#1570 (comment)](https://github.com/longhorn/longhorn-manager/pull/1570#discussion_r1034264740)

https://github.com/longhorn/longhorn-manager/pull/1574

**Comment by roger-ryao** [comment]
**Verified on master-head 20221130**

- longhorn master-head ([066dde1](https://github.com/longhorn/longhorn/commit/066dde111000b6639ccc8e2cdbc6b8f6e0c1c4f1)) 
- longhorn-manager master-head ([b7afa36](https://github.com/longhorn/longhorn-manager/commit/b7afa36f6cfef80c4518d0c93f370884ac6eb6b6)) 

**The test steps**

https://longhorn.github.io/longhorn-tests/manual/release-specific/v1.4.0/test-csi-plugin-liveness-probe/


**Result Passed**
