### ISSUE TITLE
[BUG] [BACKPORT] [1.2.5] A snapshot has a child that is no-longer exist in the snapshot chain

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3911]
ref: https://github.com/longhorn/longhorn/issues/3883

**Comment by yangchiu** [comment]
verified passed on v1.2.x-head (longhorn-engine:232d53c)

following [the test steps](https://github.com/longhorn/longhorn/issues/3883#issuecomment-1105938840) and [the steps for snapshot purge](https://github.com/longhorn/longhorn-tests/blob/master/docs/content/manual/release-specific/v1.3.0/test-snapshot-purge-retry.md), the bug mentioned in the original issue cannot be reproduced.
