### ISSUE TITLE
[BUG] [BACKPORT] [1.1.4] A snapshot has a child that is no-longer exist in the snapshot chain

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3912]
ref: https://github.com/longhorn/longhorn/issues/3883

**Comment by cchien816** [comment]
**Validate on v1.1.x-head 20220506
Result Pass**

Test steps from https://github.com/longhorn/longhorn/issues/3883#issuecomment-1105938840

1. Using engine image chanow/longhorn-engine:issue3883-11x, this image did not contain delete(r.diskChildrenMap, name) in pkg/replica/replica.go line 471 which means not include this [PR](https://github.com/longhorn/longhorn-engine/pull/701/files) to test. In volume detail page the snapshot chain can not display correctly (stuck at loading icon). Which reflect the snapshot messed up situation.
![Screenshot from 2022-05-06 16-18-40](https://user-images.githubusercontent.com/73337386/167094505-9f075557-1556-456a-b818-5b1926770486.png)


2. Using v1.1.x-head 20220506 with default engine-image, after perform test https://github.com/longhorn/longhorn/issues/3883#issuecomment-1105938840, the snapshot chain not messed up and in volume detail page snapshot chain can display correctly
