### ISSUE TITLE
[TEST] Clean up unexpected long-running tests/instances

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#3913]
## What's the test to develop? Please describe

We need to remember to clean up any orphaned resources created in our testbed to avoid any resources running indefinitely. Could we help another weekly run pipeline to clean up long-running instances? 

https://github.com/longhorn/longhorn-tests/pull/939#discussion_r863877198

**Comment by yangchiu** [comment]
Related to https://github.com/longhorn/longhorn/issues/4072.
The issue described in https://github.com/longhorn/longhorn/issues/4072 would cause tests/instances running forever.

**Comment by yangchiu** [comment]
Need to ensure all testing resources having longhorn related tag to be identified first (https://github.com/longhorn/longhorn/issues/4395).

**Comment by yangchiu** [comment]
possibly use the following commands/scripts:

```
(0)

aws ec2 describe-instances --filters Name=tag:Name,Values=*longhorn-tests-*

aws ec2 terminate-instances --instance-ids i-00ea45d7d1c0ace46

(1)

aws ec2 describe-subnets --filters Name=tag:Name,Values=*owouqfg2*

aws ec2 delete-subnet --subnet-id subnet-00b078224bfce71a0

(2)

aws ec2 describe-route-tables --filters Name=tag:Name,Values=*owouqfg2*

aws ec2 delete-route-table --route-table-id rtb-00a59f5b1383190ea

(3)

aws ec2 describe-nat-gateways --filter Name=tag:Name,Values=*owouqfg2*

aws ec2 delete-nat-gateway --nat-gateway-id nat-030d3e11289814ef0

(4)

aws ec2 describe-internet-gateways --filters Name=tag:Name,Values=*owouqfg2*

aws ec2 detach-internet-gateway --internet-gateway-id igw-0cecffae27465788e --vpc-id vpc-0947c79a80d0d2129

aws ec2 delete-internet-gateway --internet-gateway-id igw-0cecffae27465788e

(5)

aws ec2 describe-security-groups --filters Name=tag:Name,Values=*owouqfg2*

aws ec2 delete-security-group --group-id sg-09838e7eadfdf7bba

(6)

aws ec2 describe-vpcs --filters Name=tag:Name,Values=*owouqfg2*

aws ec2 delete-vpc --vpc-id vpc-0947c79a80d0d2129

(7)

aws elbv2 describe-load-balancers | jq '.LoadBalancers[] | select(.LoadBalancerArn | contains("longhorn")).LoadBalancerArn'

aws elbv2 delete-load-balancer --load-balancer-arn arn:aws:elasticloadbalancing:us-east-1:125601231307:loadbalancer/net/longhorn-tests-lb-123456/6cc1e642a25a5ad4

(8)

aws elbv2 describe-target-groups | jq '.TargetGroups[] | select(.TargetGroupArn | contains("longhorn")).TargetGroupArn'

aws elbv2 delete-target-group --target-group-arn arn:aws:elasticloadbalancing:us-east-1:125601231307:targetgroup/longhorn-tests-lb-tg-443-123456/691d5e41be59c8bc

(9)

aws ec2 describe-addresses --filters "Name=tag:Name,Values=*owouqfg2*"

aws ec2 release-address --allocation-id eipalloc-03dfb821d37407bea
```

**Comment by yangchiu** [comment]
need to deal with dependencies between resources. e.g resource A needed to be deleted completely (need to wait the status being cleaned up / updated) then resource B can be deleted.

**Comment by innobead** [comment]
If they are going to delete, why the dependencies still matter?

**Comment by yangchiu** [comment]
> If they are going to delete, why the dependencies still matter?

If trying to perform a deletion operation on a resource which still has dependencies, the operation would return errors like https://aws.amazon.com/premiumsupport/knowledge-center/troubleshoot-dependency-error-delete-vpc/, and not just vpc, other resource types could have similar dependency issues needed to be solved before perform the deletion.

**Comment by innobead** [comment]
> > If they are going to delete, why the dependencies still matter?
> 
> If trying to perform a deletion operation on a resource which still has dependencies, the operation would return errors like [aws.amazon.com/premiumsupport/knowledge-center/troubleshoot-dependency-error-delete-vpc](https://aws.amazon.com/premiumsupport/knowledge-center/troubleshoot-dependency-error-delete-vpc/), and not just vpc, other resource types could have similar dependency issues needed to be solved before perform the deletion.

I see, but how about force deletion or actually this is not an option?

**Comment by yangchiu** [comment]
> > > If they are going to delete, why the dependencies still matter?
> > 
> > 
> > If trying to perform a deletion operation on a resource which still has dependencies, the operation would return errors like [aws.amazon.com/premiumsupport/knowledge-center/troubleshoot-dependency-error-delete-vpc](https://aws.amazon.com/premiumsupport/knowledge-center/troubleshoot-dependency-error-delete-vpc/), and not just vpc, other resource types could have similar dependency issues needed to be solved before perform the deletion.
> 
> I see, but how about force deletion or actually this is not an option?

I believe force deletion is not provided by [aws-cli](https://docs.aws.amazon.com/cli/latest/reference/ec2/delete-vpc.html), and there was a [request](https://github.com/aws/aws-cli/issues/1721#issuecomment-361341763) for cascading deleting all dependencies, but ended up it's not planned and closed.

**Comment by yangchiu** [comment]
The cleanup pipeline has been implemented.
