### ISSUE TITLE
[BUG] UI pop error if long volume name used (when > 40 characters)

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#3915]
## Describe the bug

Currently if create Volume from UI, UI will tell user volume name length can not greater than 63 characters
But if create volume with 41 characters (> 40 character), UI will pop up error message, and the volume name will be changed

## To Reproduce

1. Deploy Longhorn
2. Click `Create Volume` button from UI
3. Enter volume name with 41 characters eg `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1`
4. Click `OK`
5. UI pop up error and volume name will be modified become `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-8ebd31e0`

## Expected behavior

We should tell user real volume name restriction when create volume from UI
And no error message pop up when create volume with long volume name

## Log or Support bundle

```unable to create volume: unable to create volume aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1: unable to verify the existence of newly created volume aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1: volume.longhorn.io "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1" not found```

[longhorn-support-bundle_a36a8cb6-db16-4fa2-9cd1-6805f4dc93d2_2022-05-04T03-38-47Z.zip](https://github.com/longhorn/longhorn/files/8617744/longhorn-support-bundle_a36a8cb6-db16-4fa2-9cd1-6805f4dc93d2_2022-05-04T03-38-47Z.zip)

## Environment

 - Longhorn version: master-head 20220504
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWARE
 - Number of Longhorn volumes in the cluster: 1

## Additional context

N/A

**Comment by innobead** [comment]
cc @derekbit I feel this is related to validation?

**Comment by innobead** [comment]
This has been caused by the volume name changed by the mutator after the volume was created, but the following validation still used the old name. 

https://github.com/longhorn/longhorn-manager/blob/3839e03106a39c91660e40b017df56342f05eeb5/datastore/longhorn.go#L383

I would suggest mutation does not touch the identity value like `metadata.name` to avoid any following validation after creation still using the old identity. @derekbit WDYT?

https://github.com/longhorn/longhorn-manager/blob/751b99e45c755f8024745f873a79d61cd146b740/webhook/resources/volume/mutator.go#L50 -> Just move back to the API call path like datastore::CreateVolume

**Comment by derekbit** [comment]
> This has been caused by the volume name changed by the mutator after the volume was created, but the following validation still used the old name.
> 
> https://github.com/longhorn/longhorn-manager/blob/3839e03106a39c91660e40b017df56342f05eeb5/datastore/longhorn.go#L383
> 
> I would suggest mutation does not touch the identity value like `metadata.name` to avoid any following validation after creation still using the old identity. @derekbit WDYT?
> 
> https://github.com/longhorn/longhorn-manager/blob/751b99e45c755f8024745f873a79d61cd146b740/webhook/resources/volume/mutator.go#L50 -> Just move back to the API call path like datastore::CreateVolume

Because we mutate the name in mutator but not update `verifyCreation`, the `verifyCreation` use the old name.
Fixing it now. Some resources may have same bug.

**Comment by derekbit** [comment]
@cchien816 
`Currently if create Volume from UI, UI will tell user volume name length can not greater than 63 characters` is incorrect.`
Maximum name length is 40 in the backend. If the input length exceeds 40 chars, backend will correct it.

**Comment by cchien816** [comment]
For the volume name length in UI, I create https://github.com/longhorn/longhorn/issues/3917 for tracking

**Comment by cchien816** [comment]
**Verified on master-head 20220505
Result Pass**

Test Step

1. Deploy Longhorn
2. Click Create Volume button from UI
3. Enter volume name with 41 characters eg aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1
4. Click OK
5. UI **not** pop up error message
