### ISSUE TITLE
[TASK] add finalizer to resource in mutating webhook

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#3918]
## What's the task? Please describe

CreateXXX, e.g. CreateBackup, adds Longhorn finalizer to new created resource.
To make the behavior consistent between API and Resource operation using CLI, we can move the longhorn finalizer creation logic to the mutating webhook.

## Additional context

Add any other context or screenshots about the task request here.

**Comment by innobead** [comment]
Don't think we need to have any manual testing, but rather rely on the e2e instead. @derekbit WDYT?

**Comment by derekbit** [comment]
Yes, we rely on the e2e test rather than manual testing.

**Comment by innobead** [comment]
Closing cc @longhorn/qa
