### ISSUE TITLE
[BACKPORT][v1.2.x] Allow to add annotations on the serviceAccount managed by the helm chart 

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#3929]
I guess we forgot to backport [this](https://github.com/longhorn/longhorn/pull/3432).

https://cloud-native.slack.com/archives/CNVPEL9U3/p1651717419977589

**Comment by yangchiu** [comment]
verified passed on v1.2.x-head.

there are service account annotations settings in yaml files, and the annotation can be set to service account w/o problems.
