### ISSUE TITLE
[BUG] [BACKPORT] [v1.2.5] Volume created from cloned PVC will stuck at Not Ready status

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3932]
ref: longhorn/longhorn#3886

**Comment by cchien816** [comment]
**Verified on v1.2.x-head 20220509
Result Pass**

1. Follow test https://github.com/longhorn/longhorn/issues/3886#issue-1211934131, cloned PVC now can generated success fully
```
NAME         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
source-pvc   Bound    pvc-b71c94a0-812a-40dd-8fee-031f4f4b0587   3Gi        RWO            longhorn       2m3s
cloned-pvc   Bound    pvc-c1e990c6-3920-40a0-8496-6672d2b68724   3Gi        RWO            longhorn       22s
```
2. e2e on v1.2.x branch [passed](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/90/testReport/junit/tests/test_cloning/test_cloning_basic/)
