### ISSUE TITLE
[IMPROVEMENT] [BACKPORT] [v1.2.5] Prevent PVC provisioning if there is insufficent storage

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#3933]
## What's the test to develop? Please describe
https://github.com/longhorn/longhorn/issues/3529

## Additional context
Add any other context or screenshots about the test request here.

**Comment by innobead** [comment]
@mantissahz Please help verify this fix. Thank you.

**Comment by mantissahz** [comment]
Verified Passed on v1.2.x-head by:

1.a. Disable scheduling on all nodes
1.b. Create a volume on UI
1.c. Create PV/PVC for the volume
1.d. Check the PV annotation "longhorn.io/volume-scheduling-error: nodes are unavailable"

2.a. Disable all disks and on all nodes
2.b. Create a volume on UI
2.c. Create PV/PVC for the volume
2.d. Check the PV annotation "longhorn.io/volume-scheduling-error: disks are not available"

3.a. Create a volume on UI. The request size exceeds the disk available size.
3.b. Create PV/PVC for the volume
3.c. Check the PV annotation "longhorn.io/volume-scheduling-error: insufficient storage"

Create the volume by two methods:
1. https://github.com/longhorn/longhorn/blob/v1.2.x/examples/csi/example_pv.yaml
2. https://github.com/longhorn/longhorn/blob/v1.2.x/examples/pod_with_pvc.yaml
