### ISSUE TITLE
[IMPROVEMENT] [BACKPORT] [v1.1.4] Prevent PVC provisioning if there is insufficent storage 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#3934]
## What's the task? Please describe
https://github.com/longhorn/longhorn/issues/3529

## Additional context

Add any other context or screenshots about the task request here.

**Comment by innobead** [comment]
Thanks, @derekbit ! Just decided don't backport this to 1.1.4.

The basic ideas for backport: 
- For the recent minor (1.2), we will do bug & improvement backport. 
- For older supported minor (1.1), we will just do bug backport.
