### ISSUE TITLE
[BUG] Websocket's icon in footer is showing wrong

### ISSUE THREAD

**Issue by smallteeths** [longhorn/longhorn#3935]
## Describe the bug

Websocket's icon in footer is showing wrong. 

<img width="306" alt="截屏2022-05-06 下午3 32 00" src="https://user-images.githubusercontent.com/27733391/167087592-b6c788b4-b305-4448-9dc5-cbe80f6a4337.png">

## Expected behavior

The name of the websocket icon should be displayed correctly.

**Comment by cchien816** [comment]
**Verified on master-head 20220512
Result Pass**

All web socket icon display correctly :

- volume
- node
- setting
- engineImage
- event
- backingImage
- recurringJob
- BackupVolumes
- Backups

Those icon will switch between open/closed when browse different Longhorn page
Opened icon in each page :

- Dashboard : volume, node, event
- Node : volume, node, setting
- Volume : volume, node, setting, engineImage, backingImage, backingImage
- Recurring Job : recurringJob
- Backup : node, setting, backingImage, recurringJob
- Setting - General : setting
