### ISSUE TITLE
[TEST] Run e2e regression of 1.3.0

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#3949]
## What's the test to develop? Please describe

As titled, run the pipelines of fresh and upgrade of each milestone release, then analyze the results. (https://ci.longhorn.io/)

## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] Run fresh install tests and analyze the result
- [ ] Run upgrade tests and analyze the result

## Additional context

N/A

**Comment by yangchiu** [comment]
[v1.3.0-preview1 amd64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1172/): 16 failures 
[v1.3.0-preview1 amd64 upgrade](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1173/): 15 failures
[v1.3.0-preview1 arm64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1176/): 32 failures
[v1.3.0-preview1 arm64 upgrade](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1177/): 25 failures

rerun again after #3939 resolved

**Comment by yangchiu** [comment]
[v1.3.0-preview1 amd64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1186/): 9 failures
[v1.3.0-preview1 amd64 upgrade](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1187/): 5 failures
v1.3.0-preview1 arm64: in progress
[v1.3.0-preview1 arm64 upgrade](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1189/): 17 failures

**Comment by yangchiu** [comment]
[v1.3.0-rc1 amd64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1252/): 47 failures 
[v1.3.0-rc1 amd64 upgrade](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1253/): 44 failures
[v1.3.0-rc1 arm64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1254/): 54 failures
[v1.3.0-rc1 arm64 upgrade](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1255/): 52 failures

**Comment by yangchiu** [comment]
[v1.3.0-rc2 amd64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1428/): 13 failures 
v1.3.0-rc2 amd64 upgrade: in progress
[v1.3.0-rc2 arm64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1430/): 16 failures
[v1.3.0-rc2 arm64 upgrade](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1431/): 18 failures

**Comment by yangchiu** [comment]
[v1.3.0-rc3 amd64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1498/): 4 failures
v1.3.0-rc3 amd64 upgrade: in progress
[v1.3.0-rc3 arm64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1499/): 16 failures
v1.3.0-rc3 arm64 upgrade: in progress

**Comment by yangchiu** [comment]
[v1.3.0 amd64 coretest](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1568/): 1 failure
[v1.3.0 amd64 upgrade coretest](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1569/): no failures
[v1.3.0 arm64 coretest](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1570/): 5 failures
[v1.3.0 arm64 upgrade coretest](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1571/): 4 failures

**Comment by innobead** [comment]
Comments from @longhorn/qa 

[test_allow_volume_creation_with_degraded_availability_csi](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1568/testReport/junit/tests/test_csi/test_allow_volume_creation_with_degraded_availability_csi/) is flaky
Other arm64 failed cases related to engine_upgrade, we are not support yet
