### ISSUE TITLE
[TEST] Verify e2e failed cases (Listed in description)

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#3951]
## What's the test to develop? Please describe

Recently failed cases below
https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/test_results_analyzer/
https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/test_results_analyzer/

- test_ha_salvage_with_backing_image
- test_ha_salvage
- test_disk_migration
- test_node_config_annotation_invalid
- test_node_config_annotation_missing
- test_allow_volume_creation_with_degraded_availability
- test_allow_volume_creation_with_degraded_availability_csi

## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] Reproduce them, see it's issue or flaky

## Additional context

N/A

**Comment by cchien816** [comment]
Reproduced on local environment 

- test_ha_salvage_with_backing_image - In progress
- test_ha_salvage - In progress
- test_disk_migration - Flaky
- test_node_config_annotation_invalid - https://github.com/longhorn/longhorn/issues/3939
- test_node_config_annotation_missing - https://github.com/longhorn/longhorn/issues/3939
- test_allow_volume_creation_with_degraded_availability - Flaky
- test_allow_volume_creation_with_degraded_availability_csi - Flaky

**Comment by cchien816** [comment]
Close this ticket because most issues were fixed and fail casees not apper in [recent](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/124/) pipleline

Only https://github.com/longhorn/longhorn/issues/3220 need keep follow

**Comment by innobead** [comment]
@cchien816 Well done, this is a good pattern to track failed e2e test cases. 

cc @longhorn/qa
