### ISSUE TITLE
[FEATURE] Local volume for distributed data workloads

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#3957]
## Is your feature request related to a problem? Please describe

Longhorn is a highly available replica-based storage system, and it's good for fault tolerance, read performance, data protection, etc, but on the other side, it also needs some extra costs like requiring more disk paces for replication. 

In some cases, especially for distributed data workloads (SS) like databases (ex: Cassandra, Kafka, etc), they already have their own data replication, sharding, etc, so we should provide a better volume type for these use cases but also still support existing specific volume functionalities like snapshotting, backup/restore, etc. 

## Describe the solution you'd like

- Extend Data Locality with `strict` or `enforced` mode to require one replica should be local and next to the workload
- Connecting the local replica via a local socket file instead of a TCP connection

## Describe alternatives you've considered

N/A

## Additional context

https://github.com/longhorn/longhorn/issues/1965

**Comment by derekbit** [comment]
As the benchmarking result, if the volume and the single replica are on the same node, the latency and iops can improved significantly.

![image](https://user-images.githubusercontent.com/12527233/173726307-022c758d-ff75-41f9-af4b-987b0cbe1e5e.png)

In addition, the tcp can be replaced with unix domain socket to gain more performance in this case.

**Comment by derekbit** [comment]
Replace the tcp connection between the engine and the single replica with unix-domain-socket.
- The IOPS and Latency are improved.
- The bandwidth number is saturated, so the improvement is not seen here.

![image](https://user-images.githubusercontent.com/12527233/173792789-3a189f49-30f1-412a-8733-fde0bcc39510.png)

**Comment by joshimoo** [comment]
@derekbit good job on the evaluation :)

**Comment by innobead** [comment]
@derekbit as we discussed, let's add this to 1.4.0.

**Comment by Bessonov** [comment]
This is a great news! May I ask what brings IO down in comparison to the baseline?

**Comment by innobead** [comment]
> This is a great news! May I ask what brings IO down in comparison to the baseline?

It's more about the improvement of latency. Basically, there are 3 primary things:
- Data locality
- Data transfer over Unix socket instead of TCP stack
- No remote replication

**Comment by Bessonov** [comment]
> It's more about the improvement of latency. Basically, there are 3 primary things:
> 
> * Data locality
> * Data transfer over Unix socket instead of TCP stack
> * No remote replication

Thanks for your answer. Probably, my question was misleading. I've asked about difference between local-path-provisioner and longhorn with data locality, unix socket and without replication. The difference between 90,531 and 47,667, and also between 77,799 and 21,158 is still huge.

**Comment by innobead** [comment]
> Thanks for your answer. Probably, my question was misleading. I've asked about difference between local-path-provisioner and longhorn with data locality, unix socket and without replication. The difference between 90,531 and 47,667, and also between 77,799 and 21,158 is still huge.

I see. 

Longhorn local volume is not for achieving the similar performance of local-path-provisioner you mentioned, but rather still based on the existing data path w/ some changes above to ensure strict data locality between engine and replica to gain some IO performance if compared with volumes with best-effort or disabled locality.

**Comment by derekbit** [comment]
Performance update

![image](https://user-images.githubusercontent.com/12527233/203797514-938500ff-276a-4aa8-845b-00a054edb9be.png)

**Comment by michaelandrepearce** [comment]
Latency is still somewhat 500% local path

**Comment by derekbit** [comment]
@michaelandrepearce @Bessonov 

The local volume's data path is not changed a lot in this improvement in order to preserve the existing functionalities such as snapshotting, backup, restore, etc.

We will continue the improvement the local volume, e.g. [pass-througn](https://github.com/longhorn/longhorn/issues/4935) to squeeze more performance. However, the performance difference is still significant after these improvements because of the existing data path design.

**Comment by michaelandrepearce** [comment]
sure 150% or something is fine to get the overlay, but 500% is a bit too much i to buy, makes it unusable for localpath usecases which is where you want fast low latency disk access for systems that themselves take care of replication (cassandra, redpanda, postgres)

**Comment by michaelandrepearce** [comment]
what i raised and has been closed for this issue, https://github.com/longhorn/longhorn/issues/1965 the point here was to and i quote

"Using K8s native LocalPV's are useful as no network-based storage can keep up with baremetal in write IOPS/latency/throughput, when using NVME/Optane disks. Giving Direct I/O: Near-zero disk performance overhead"

**Comment by derekbit** [comment]
Need to update hte upgrade test version, because new options are added.
cc @longhorn/qa

**Comment by chriscchien** [comment]
Hi @derekbit

When I attached strict-local volume form one node to another node, volume will looped between attaching and detaching, the only active button was delete, is it on purpose? thank you.

**Comment by derekbit** [comment]
> volume will looped between attaching and detaching

This is expected, because the strict-local volume one replica  should satisfy
1. single replica
2. engine and replica are on the same

So, if you attach the volume to another node, the attach-detach loop should happe because of the lack of a replica.

**Comment by chriscchien** [comment]
Verified in longhorn master `400b8c` with test [steps](https://github.com/longhorn/longhorn/pull/4928/files?short_path=81c1c17#diff-81c1c17adfdd76ac015d96d7b77207a19f3837b1bc28c19c0caa92e91b049f14)
Result **Pass**

1. Can successfully create a local volume with numberOfReplicas=1 and dataLocality=strict-local
2. Webhook **rejected** the following cases when the volume is created or attached
   - Local volume with dataLocality=strict-local but numberOfReplicas>1
   - Update a attached local volume's numberOfReplicas to a value greater than one
   - Update a attached local volume's dataLocality to disabled or best-effort
3. Volume and restored volume can used by workload and data kept consistent (tested by deployment with `nodeName` set)

**Comment by innobead** [comment]
> > volume will looped between attaching and detaching
> 
> This is expected, because the strict-local volume one replica should satisfy
> 
> 1. single replica
> 2. engine and replica are on the same
> 
> So, if you attach the volume to another node, the attach-detach loop should happe because of the lack of a replica.

After discussing with @derekbit , see if we need to have a validation hook to avoid unnecessary intended reconsiling for this situation.

**Comment by innobead** [comment]
We also need to check if local volume supports auto/manual salvage. 

https://github.com/longhorn/longhorn-tests/blob/ee78127d9dd5c05dbf66f95ab3b5f6936b90b447/docs/content/manual/pre-release/ha/single-replica-node-down.md?plain=1#L23-L32

**Comment by chriscchien** [comment]
Verify test case  [Node restart/down scenario with `Pod Deletion Policy When Node is Down` set to `delete-both-statefulset-and-deployment-pod`](https://github.com/longhorn/longhorn-tests/blob/ee78127d9dd5c05dbf66f95ab3b5f6936b90b447/docs/content/manual/pre-release/ha/single-replica-node-down.md?plain=1#L23-L32) on longhorn master `066dde` with strict-local volume
Result **Pass**

With `Pod Deletion Policy When Node is Down` set to `delete-both-statefulset-and-deployment-pod`, after volume attached node power off for 10 minutes then power up that node, deployment pod will eventually recreated and attached to node which local volume attached to, and the data kept consistent.
