### ISSUE TITLE
Cannot attach drive to any of the AWS nodes

### ISSUE THREAD

**Issue by jhuynh08** [longhorn/longhorn#3965]
Hello,

I can't seem to attach one of my volumes to any of the nodes I have running in AWS. The error I'm receiving shown below.

```
AttachVolume.Attach failed for volume "pvc-e97e44a9-06ca-4b83-9c82-11681da9e505" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [detail=, message=unable to attach volume pvc-e97e44a9-06ca-4b83-9c82-11681da9e505 to ip-10-0-1-38.ec2.internal: cannot attach volume pvc-e97e44a9-06ca-4b83-9c82-11681da9e505 because the engine image longhornio/longhorn-engine:v1.2.4 is not deployed on at least one of the the replicas' nodes or the node that the volume is going to attach to, code=Server Error] from [http://longhorn-backend:9500/v1/volumes/pvc-e97e44a9-06ca-4b83-9c82-11681da9e505?action=attach]
```

The error states that the volume can't attach due to longhorn engine not deployed but that's not the case since this is deployed on all the nodes.

**Comment by jhuynh08** [comment]
Uploaded support bundle

**Comment by PhanLe1010** [comment]
From the support bundle, the nodes of the replicas for this volume are:
| Replica  | Node |
| ------------- | ------------- |
| pvc-e97e44a9-06ca-4b83-9c82-11681da9e505-r-387b9791  | ip-10-0-73-219.ec2.internal  |
| pvc-e97e44a9-06ca-4b83-9c82-11681da9e505-r-da72c9e0 | ip-10-0-22-150.ec2.internal  |
| pvc-e97e44a9-06ca-4b83-9c82-11681da9e505-r-aa77b042 | ip-10-0-5-191.ec2.internal |

None of the nodes exist in your cluster. Probably, the nodes are already removed. 

Some ideas on top of my head:
1. Delete the volume
2. If you have a backup for this volume in the backup target, restore it
3. If not, you would have to find one of the removed nodes and see if you can get data out
4. If none of the above is applied, your data is gone. You have to create a new volume

**Comment by hanxinhang** [comment]
I have the same problem
