### ISSUE TITLE
[BUG] Command longhorn-instance-manager process won't work without TLS key

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#3966]
## Describe the bug

From e2e
- test_ha_salvage_with_backing_image
- test_ha_salvage

By default longhorn installation, if we present command `longhorn-instance-manager process delete` in instance-manager-r pod will see below error  
```
time="2022-05-11T02:57:52Z" level=fatal msg="Error running process delete command: failed to initialize client: failed to load tls key pair from file: open /tls-files/tls.crt: no such file or directory."
```
## To Reproduce

1. Run e2e test_ha_salvage

or

1. Deploy Longhorn
2. Enter instance-manage-r pod
3. Exec command `longhorn-instance-manager process delete`
4. Will see error to deny execution

## Expected behavior

Since TLS are optional behavior, we should keep longhorn-instance-manager process working properly before TLS key uploaded.

## Log or Support bundle

Please see description

## Environment

 - Longhorn version: v1.3.0-preview1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 1

## Additional context

N/A

**Comment by cchien816** [comment]
Related to https://github.com/longhorn/longhorn/issues/3839

**Comment by joshimoo** [comment]
test image: `joshimoo/longhorn-instance-manager:3966-test`

**Comment by cchien816** [comment]
Validate [pass](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1206/testReport/tests/) with test image `joshimoo/longhorn-instance-manager:3966-test`, will test again in master head later

**Comment by innobead** [comment]
> Validate [pass](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1206/testReport/tests/) with test image `joshimoo/longhorn-instance-manager:3966-test`, will test again in master head later

After the merge, please also reverify mTLS features to ensure nothing broken. Thanks, @cchien816 .

**Comment by cchien816** [comment]
**Validate on master-head 20220513(73f1914b988daa121599f7ff2c4c9bbf59a40967)
Result Pass**

1. e2e [Passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1216/testReport/tests/)
2. Command `longhorn-instance-manager process delete` running properly in both instance-manage-r/e
3. Restset mTLs feature https://github.com/longhorn/longhorn/issues/3839 on master-head, test pass and detail steps/result logged [here](https://github.com/longhorn/longhorn/issues/3839#issuecomment-1125607825)

**Comment by innobead** [comment]
After #3546 merged, we need to revisit this issue. 

cc @c3y1huang
