### ISSUE TITLE
Is it possible to mount longhorn replica on Node 2 while longhorn volume is attached to Node1 

### ISSUE THREAD

**Issue by vidhut-singh** [longhorn/longhorn#3972]
Setup :
I have two node k3s setup and I have deployed longhorn on it.  I have created a volume with replica count 2. The volume is in a healthy state and replicated to Node2. 

Node 1 : 
I have attached the longhorn volume 

Node 2 
I am trying the mount the replica of the volume manually. For that, I am following this article 
https://www.bookstack.cn/read/longhorn-1.0.0-en/a4a31b895ca2573a.md
This article suggests that we shouldn't mount while the volume is attached to Node1

However, I have a scenario where I want to do r/w on volume and replica simultaneously. is it possible to do?

**Comment by c3y1huang** [comment]
Have you tried [ReadWriteMany](https://longhorn.io/docs/1.2.4/advanced-resources/rwx-workloads/)?

**Comment by vidhut-singh** [comment]
Thanks, I have already used ReadWriteMany and that doesn't solve my use case. Since it uses longhorn NFS provisioned and essentially points to the same volume. I have a use case to mount the replica in an Active-Active setup if possible but so far it doesn't look like it is possible if the volume is already in use on Node1.  Can you confirm if this is supported by Longhorn?

**Comment by PhanLe1010** [comment]
> I have a use case to mount the replica in an Active-Active setup if possible but so far it doesn't look like it is possible if the volume is already in use on Node1. Can you confirm if this is supported by Longhorn?

No, it is not supported.

If you mount the replica on node2 and start writing to it, it will break the data consistency between replica on node 1 and replica on node 2

**Comment by joshimoo** [comment]
To support an active/active configuration one needs a distributed filesystem, which the standard fs (ext4/xfs) are not.
Theoretically the raw block dev can be used in an active/active configuration, but without a distributed FS or specific software it is kinda pointless, so we don't expose that usage mode currently.

The only way for active/active at the moment would be to use the RWX mode which is implemented via NFS on a single attached lonhorn volume.
