### ISSUE TITLE
[IMPROVEMENT] Implement TLS to proxy client

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#3975]
https://github.com/longhorn/longhorn-instance-manager/pull/105#discussion_r871248489

https://github.com/longhorn/longhorn/issues/3546
https://github.com/longhorn/longhorn/issues/3978

**Comment by innobead** [comment]
cc @joshimoo

**Comment by innobead** [comment]
Already finished. @c3y1huang Please reopen this if this is still valid.
