### ISSUE TITLE
[IMPROVEMENT] Cache process clients in proxy server

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#3984]
Investigate if we can make process clients reusable by cache in the proxy server.

https://github.com/longhorn/longhorn-instance-manager/pull/105#discussion_r866492493
https://github.com/longhorn/longhorn-instance-manager/pull/105#discussion_r872395281

https://github.com/longhorn/longhorn/issues/3546

**Comment by innobead** [comment]
#7790 duplicated.
