### ISSUE TITLE
[BUG] 🐛 Longhorn Manager 1.2.4 fails to spin up properly on Vultr Kubernetes Engine (VKE)

### ISSUE THREAD

**Issue by pcgeek86** [longhorn/longhorn#3985]
## Describe the bug

1. When deploying Longhorn via `kubectl` onto the Vultr Kubernetes Engine (VKE), the Longhorn Manager component fails to start.
2. The `longhorn-driver-deployer` stays in `init` status

## To Reproduce

1. Deploy Vultr Kubernetes Engine (VKE) version 1.23.5
2. Deploy Longhorn to the VKE, using command below
3. Observe failed Pods in the `longhorn-system` namespace

```
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.2.4/deploy/longhorn.yaml
```

## Expected behavior

Longhorn successfully deploys to VKE.

#### Longhorn System Namespace

```
PS /> kubectl get all --namespace longhorn-system
NAME                                            READY   STATUS             RESTARTS        AGE
pod/longhorn-driver-deployer-7c85dc8c69-6d276   0/1     Init:0/1           0               14m
pod/longhorn-manager-48p72                      0/1     CrashLoopBackOff   7 (4m3s ago)    14m
pod/longhorn-manager-srjf8                      0/1     CrashLoopBackOff   7 (3m23s ago)   14m
pod/longhorn-ui-6dcd69998-lk2xd                 1/1     Running            0               14m

NAME                               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/longhorn-backend           ClusterIP   10.99.191.183   <none>        9500/TCP   14m
service/longhorn-engine-manager    ClusterIP   None            <none>        <none>     14m
service/longhorn-frontend          ClusterIP   10.102.56.226   <none>        80/TCP     14m
service/longhorn-replica-manager   ClusterIP   None            <none>        <none>     14m

NAME                              DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/longhorn-manager   2         2         0       2            0           <none>          14m

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/longhorn-driver-deployer   0/1     1            0           14m
deployment.apps/longhorn-ui                1/1     1            1           14m

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/longhorn-driver-deployer-7c85dc8c69   1         1         0       14m
replicaset.apps/longhorn-ui-6dcd69998                 1         1         1       14m
```

#### Longhorn Manager Pod

```
2022/05/15 02:08:47 proto: duplicate proto type registered: VersionResponse
time="2022-05-15T02:08:47Z" level=error msg="Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host"
time="2022-05-15T02:08:47Z" level=fatal msg="Error starting manager: Environment check failed: Failed to execute: nsenter [--mount=/host/proc/2710/ns/mnt --net=/host/proc/2710/ns/net iscsiadm --version], output , stderr, nsenter: failed to execute iscsiadm: No such file or directory\n, error exit status 127"
```

## Environment

 - Longhorn version: 1.2.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: VKE 1.23.5
   - Number of management node in the cluster: unknown
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: Unknown
   - CPU per node: 1
   - Memory per node: 2 GB
   - Disk type(e.g. SSD/NVMe): 55 GB SSD
   - Network bandwidth between the nodes: Unknown
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Vultr Cloud
 - Number of Longhorn volumes in the cluster: n/a

**Comment by derekbit** [comment]
Please check if the iscsi daemon is installed on your nodes.
https://longhorn.io/docs/1.2.4/deploy/install/#installing-open-iscsi

**Comment by pcgeek86** [comment]
I opened a support ticket with Vultr, saying the following:

> The Longhorn project for Kubernetes utilizes node storage to expose volumes to Kubernetes Pods. Unfortunately this doesn't work properly on VKE, whereas it works perfectly fine on Linode and Digital Ocean managed Kubernetes services. I've opened an issue on their GitHub project page, but Vultr will probably need to implement some changes to the default node configuration, in order to ensure that Longhorn works on VKE.

**Comment by pcgeek86** [comment]
- I created a Vultr Kubernetes Engine (VKE) cluster with 2 worker nodes
- I was able to SSH into one of the nodes and run `apt install open-iscsi`
- I attempted to deploy Longhorn with the `kubectl` approach
- The `longhorn-manager` successfully started on the single node that I manually fixed
- The secondary, unmodified worker node continued to fail to start `longhorn-manager`

I shared this information with the Vultr support team, in my ticket, so they can choose whether or not they want to pre-install the `open-iscsi` package onto their VKE worker nodes.

I did not experience this problem on Digital Ocean or Linode managed Kubernetes services, so they must pre-install the `open-iscsi` package.

**Comment by pcgeek86** [comment]
I received another reply from Vultr Support, indicating that they plan to add `open-iscsi` to their VKE worker node base image.

```
Hello Trevor,

It is great to hear you were able to identify the cause of the issue! We went ahead and created an internal ticket to add that package in our next sprint. We will get that package added and released in our next image build.

We appreciate you taking the time to let us know!
```

Hopefully this should be solved, and avoid the need for Longhorn users — running Kubernetes on VKE — to manually deploy the package to worker nodes.
