### ISSUE TITLE
[TEST] Support different types of install/upgrade e2e regression

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#3987]
## What's the test to develop? Please describe

Currently, we only support testing over longhorn-manager/deploy, but in real user cases, they will follow the guidance from https://longhorn.io/docs/latest/deploy/install/ and https://longhorn.io/docs/latest/deploy/upgrade/, so we need to ensure we have a way to choose what type to run our e2e regression.

## Describe the items of the test development (DoD, definition of done) you'd like

- [x] Support all supported ways to run install e2e regression
- [x] Support all supported ways to run upgrade e2e regression
- [x] Apply for all platform/architectures we support (amd64, arm64)

## Additional context
N/A

**Comment by yangchiu** [comment]
Implementing helm install/upgrade regression test pipeline now.

**Comment by yangchiu** [comment]
Created helm related PRs created: https://github.com/longhorn/longhorn-tests/pull/1474 https://github.com/longhorn/infra/pull/135

Investigating if it's possible to automate rancher chart upgrate test now.

**Comment by yangchiu** [comment]
For rancher pipeline, as discussed, make it an on-demand pipeline instead. when there is a PR, We can run the pipeline when there is a suitable PR like https://github.com/rancher/charts/pull/2797 that includes the already released Longhorn chart like `v1.4.2` and the unreleased Longhorn chart like `v1.5.1`, so use that PR to run the upgrade test from `v1.4.2` to `v1.5.1` and the fresh install test on `v1.5.1`.

**Comment by yangchiu** [comment]
Implementing rancher install/upgrade regression test pipeline now.

**Comment by yangchiu** [comment]
Created rancher chart related PRs created: https://github.com/longhorn/longhorn-tests/pull/1476 https://github.com/longhorn/infra/pull/136

Investigating if it's possible to automate gitops (flux) install/upgrade test now. Since we're not familiar with it and never use it before, the investigation could take more time.

**Comment by yangchiu** [comment]
Implementing flux install/upgrade regression test pipeline now.

Flux is based on released helm charts, we have to release the chart before we can test it. An unofficial released custom chart (like https://artifacthub.io/packages/helm/release-longhorn/longhorn) is needed to run the pipeline.

So again it's an on-demand pipeline like the rancher chart one.
