### ISSUE TITLE
[IMPROVEMENT] Support backing image with common compression formats.

### ISSUE THREAD

**Issue by weihanglo** [longhorn/longhorn#3988]
## Is your improvement request related to a feature? Please describe

Longhorn already supports qcow2 and raw iamge format, which is really great. However, some vendors ship their images with additional compression, for example, `https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2.xz`. If Longhorn supports some common compression formats, vendors can directly use those images without decompressing, and also save the storage space a bit.

## Describe the solution you'd like

Longhorn starts to recognize and handle compression formats for backing images. We can start from Gzip and XZ as they are most common ones.

## Describe alternatives you've considered

Not to support it.

**Comment by derekbit** [comment]
@weihanglo Do you mean that Longhorn reads the data from the compressed backing image (base image) in the run time?

**Comment by weihanglo** [comment]
> @weihanglo Do you mean that Longhorn reads the data from the compressed backing image (base image) in the runtime?
> 
> If YES, there are some considerations
> 
>     1. Find the blocks that store the compressed data for the IO. It usually reads more data than required if the compression rate of the image is poor.
> 
>     2. Decompressing data introduces significant performance drop.
> 
>     3. Both QCOW2 and Longhorn supports sparse files. As a result, storage space is already saved, and performance is not harmed.

These all make sense, especially performance drop. I'll re-consider if we really needs this feature for our situation. Thanks for the rapid reply.

**Comment by derekbit** [comment]
After discussing with @ChanYiLin, we don't need to implement the issue because of https://github.com/longhorn/longhorn/issues/3988#issuecomment-1130059940.

WDYT? @innobead

**Comment by Jackenmen** [comment]
Could you check if https://github.com/harvester/harvester/issues/6267 changes your mind about implementing this (assuming it's in scope of this issue as was suggested to me there)?

**Comment by derekbit** [comment]
> Could you check if [harvester/harvester#6267](https://github.com/harvester/harvester/issues/6267) changes your mind about implementing this (assuming it's in scope of this issue as was suggested to me there)?

@Jackenmen 
This is a different topic. This issue is for the compressed qcow2 image rather than qcow2 image with built-in zstd.

For sure, we will work on https://github.com/harvester/harvester/issues/6267 after libqcow supports zstd.

**Comment by derekbit** [comment]
@ChanYiLin Could you create an issue in longhorn/longhorn for https://github.com/harvester/harvester/issues/6267? Thanks.
