### ISSUE TITLE
[IMPROVEMENT] Allow customize CPU requests for `instance-manager`

### ISSUE THREAD

**Issue by fzyzcjy** [longhorn/longhorn#3993]
## Is your improvement request related to a feature? Please describe

Hi thanks for the wonderful library! I am using the helm chart deploying longhorn to kubernetes. However, the `instance-manager` has a fixed CPU request of 0.5 cores. For my own use case, I have very limited cpu and low workload, so want to lower this request, e.g. to 0.1 core. Seems that there is not existing config param for this? Thanks!

**Comment by joshimoo** [comment]
Have a look at this part of the doumentation:
https://longhorn.io/docs/1.2.4/references/settings/#guaranteed-engine-manager-cpu
https://longhorn.io/docs/1.2.4/references/settings/#guaranteed-replica-manager-cpu

These default percentage settings can also be overriden per node. A certain amount of CPU will be required for correct functionality of the engine/replicas.

**Comment by fzyzcjy** [comment]
Thank you!
