### ISSUE TITLE
[BACKPORT][V1.2.5][BUG] Upgrading from v1.2.x to v1.2.4 take a long time if there are many backup CRs in the system

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3996]
ref: https://github.com/longhorn/longhorn/issues/3980

**Comment by PhanLe1010** [comment]
## Test steps
1. Install Longhorn v1.2.0 or v1.2.1 or v1.2.2 or v1.2.3
2. Create 20k backups in the system (e.g., by using a recurring job)
3. Perform upgrade to Longhorn v1.2.x-head
4. Verify that it takes less than 15 mins for all Longhorn manger to come up

**Comment by mantissahz** [comment]
Validate on v1.2.x-head 20220602
Result Pass

Environment: v1.23.6+k3s1 with 3 control-plane nodes and 5 worker nodes
Created backups: 10062

It takes less than 3 mins for all Longhorn manager pods to come up when upgrading from v1.2.3 to v1.2.x-head

**Comment by innobead** [comment]
> Validate on v1.2.x-head 20220602 Result Pass
> 
> Environment: v1.23.6+k3s1 with 3 control-plane nodes and 5 worker nodes Created backups: 10062
> 
> It takes less than 3 mins for all Longhorn manager pods to come up when upgrading from v1.2.3 to v1.2.x-head

@mantissahz well done, thanks!
