### ISSUE TITLE
Mount the same volume in readonly mode on multiple machines

### ISSUE THREAD

**Issue by klokan** [longhorn/longhorn#4]
Can the read-only mount to multiple instances be done with longhorn?
Is it a planned feature?

**Comment by sheng-liang** [comment]
Yes that can be done. It is actually a little harder to do this in Longhorn than in a system with a centralized controller as we will need to change Longhorn engine and orchestration to support multiple read-only controllers attached to the same set of replicas. But it can be done if there's a need. Currently there's no plan to do it ourselves. As far as I know AWS does not support read-only mounts of EBS volumes, although GCE does.

**Comment by james-munson** [comment]
This issue has been superseded by https://github.com/longhorn/longhorn/5041
