### ISSUE TITLE
NFS backup failed with error 'file exists'

### ISSUE THREAD

**Issue by goodidea-kp** [longhorn/longhorn#4001]
## Question
> Suggest to use https://github.com/longhorn/longhorn/discussions to ask questions.

## Environment

 - Longhorn version:1.2.4
 - Kubernetes version:1.24
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal

## Additional context

Trying to debug..looks like folder for mounts was created, and failed with creation error.  Can I delete old one or say to longhorn use existing folder?

**Comment by derekbit** [comment]
> Trying to debug..looks like folder for mounts was created, and failed with creation error.

Do you mean the NFS mountpoint is already mounted on your longhorn node?

**Comment by PhanLe1010** [comment]
Can you try to create backup again and provide the logs of `longhorn-manager-xxx` pods inside the `longhorn-system` namespace?
