### ISSUE TITLE
[TASK] Performance benchmark of Longhorn v1.2.4 and v1.3.0 on Equinix

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4002]
## What's the task? Please describe

Performance benchmark of Longhorn v1.2.4 and v1.3.0 on Equinix

## Additional context

https://github.com/longhorn/longhorn/issues/2986
https://suse.slack.com/archives/C02DR3N5T24/p1652886159419279

**Comment by innobead** [comment]
cc @yangchiu

**Comment by innobead** [comment]
This can be done before or after 1.3.0 GA. cc @longhorn/qa

**Comment by derekbit** [comment]
**Environment**
- Cloud provider: Equinix
- Machine: m3.small.x86
- Kubernetes: v1.23.6+rke2r2
- Nodes: 3 (each node is master and also worker)
- OS: Ubuntu 22.04 / 5.15.0-33-generic
- Storage: 1 (SSD Micron_5300_MTFD)

![image](https://user-images.githubusercontent.com/12527233/172323920-6a0980e5-6cc2-4a80-b549-00d6f3d2b9c9.png)

The performance between v1.2.4 and v1.3.0-rc2 are very close.

**Comment by niusmallnan** [comment]
Hi @derekbit , I did a similar test on the Equinix platform, however, I was hovering over its local-path performance.
This caused me a little bit of trouble. I'm sharing it here, hope it helps with this test.

Unlike your environment, I was assigned a **Micron_5200** device. I am using Harvester-based OS, it should be from openSUSE leap 15.3.
```
hdparm -i /dev/sdb

/dev/sdb:

 Model=Micron_5200_MTFDDAK480TDN, FwRev=D1MU020, SerialNo=200325F2F117
 Config={ Fixed DTR>10Mbs }
 RawCHS=16383/16/63, TrkSize=0, SectSize=0, ECCbytes=0
 BuffType=unknown, BuffSize=unknown, MaxMultSect=16, MultSect=off
 (maybe): CurCHS=16383/16/63, CurSects=16514064, LBA=yes, LBAsects=937703088
 IORDY=on/off, tPIO={min:120,w/IORDY:120}, tDMA={min:120,rec:120}
 PIO modes:  pio0 pio3 pio4
 DMA modes:  mdma0 mdma1 mdma2
 UDMA modes: udma0 udma1 udma2 udma3 udma4 udma5 *udma6
 AdvancedPM=yes: unknown setting WriteCache=enabled
 Drive conforms to: unknown:  ATA/ATAPI-3,4,5,6,7
```

By using `yasker/kbench` image(numjobs=1 and randread=0):
```
=========================
FIO Benchmark Summary
For: test_device
CPU Idleness Profiling:
Size: 50G
Quick Mode: enabled
=========================
IOPS (Read/Write)
        Random:          81,502 / 76,186
    Sequential:          53,942 / 86,902

Bandwidth in KiB/sec (Read/Write)
        Random:        402,991 / 419,621
    Sequential:        451,803 / 424,311


Latency in ns (Read/Write)
        Random:         222,876 / 31,280
    Sequential:          56,243 / 49,119
```

By using my hacking image `niusmallnan/kbench:dev` (numjobs=4 and randread=1):
```
=========================
FIO Benchmark Summary
For: test_device
CPU Idleness Profiling:
Size: 50G
Quick Mode: enabled
=========================
IOPS (Read/Write)
        Random:          94,064 / 84,455
    Sequential:        114,297 / 105,270

Bandwidth in KiB/sec (Read/Write)
        Random:        412,630 / 451,597
    Sequential:        450,302 / 453,214


Latency in ns (Read/Write)
        Random:         161,643 / 47,750
    Sequential:         167,168 / 48,034
```

My conclusion:
1. We may need to enable `numjobs` to get real performance.
2. Not sure if SSD `WriteCache=enabled` attribute is the factor?

**Comment by derekbit** [comment]
Hello @niusmallnan,
Thanks for your results.
> 1. We may need to enable numjobs to get real performance.

Yes. We can increase the `numjobs` to squeeze the random I/O performance.
 *numjobs = 1* makes sense for sequential I/O, otherwise the result will introduce the random I/O effect.

> 2. Not sure if SSD WriteCache=enabled attribute is the factor?

SSD WriteCache is the write-back cache buffer on the SSD device, and it can improve the write performance.
In the case of disabling it, latency should increase significantly, similar to a `sync` mode.
