### ISSUE TITLE
[BUG][v1.3.0-rc1] faulted volume after engine upgraded

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#4004]
## Describe the bug

Upgrade longhorn from v1.2.4 to v1.3.0-rc1, and then upgrade longhorn engine to v1.3.0-rc1, a healthy volume becomes faulted.

## To Reproduce

1. install longhorn v1.2.4
`kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.2.4/deploy/longhorn.yaml`
2. access longhorn ui to disable `Auto Salvage`
3. create a deployment to use longhorn volume
`kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/deployment.yaml`
4. wait for pod running and volume becomes healthy
5. upgrade longhorn to v1.3.0-rc1
`kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml`
6. after upgraded, the volume is still healthy
7. upgrade longhorn engine for this volume to v1.3.0-rc1 through longhorn ui
8. after engine upgraded, the volume is healthy at the beginning, but the replicas become failed one by one, and finally the volume becomes faulted. 

## Expected behavior

volume still works properly after engine upgraded.

## Log or Support bundle

[longhorn-support-bundle_8e1ecdd1-4d26-4951-b5e5-52193397fb79_2022-05-19T02-23-43Z.zip](https://github.com/longhorn/longhorn/files/8723013/longhorn-support-bundle_8e1ecdd1-4d26-4951-b5e5-52193397fb79_2022-05-19T02-23-43Z.zip)

## Environment

 - Longhorn version: v1.2.4 -> v1.3.0-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.21.9+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: ubuntu 20.04
   - CPU per node: 
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): aws
 - Number of Longhorn volumes in the cluster: 1

## Additional context

Related to test case https://longhorn.github.io/longhorn-tests/manual/pre-release/upgrade/longhorn-upgrade-test/

**Comment by c3y1huang** [comment]
[longhorn-support-bundle_45e24b0b-93ee-4ed1-a032-1d4666f15225_2022-05-19T07-48-43Z.zip](https://github.com/longhorn/longhorn/files/8726931/longhorn-support-bundle_45e24b0b-93ee-4ed1-a032-1d4666f15225_2022-05-19T07-48-43Z.zip)

**Comment by c3y1huang** [comment]
https://github.com/longhorn/longhorn-manager/blob/master/controller/engine_controller.go#L1519-L1525

Weird, seems both `version.ClientVersion.GitCommit` and `version.ServerVersion.GitCommit` is using v1.2.4 ommit `3e1eadde16a4c5024dd397b8353d2c869e59c417`.

**Comment by cchien816** [comment]
**Verified on** 
- longhorn master-head (59f3c3b647d162dce483586faaec105ea50a9add)
- longhorn-manager master-head ( [f61745](https://github.com/longhorn/longhorn-manager/commit/f61745347089d4724d78df92c18817510b57c3a6))

**Result Pass**

1. Can reproduced on v1.3.0-rc1.

2. Follow test steps in [comment](https://github.com/longhorn/longhorn/issues/4004#issue-1241048070) and use `longhorn-manager:master-head` in `https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml` to do upgrade, after Longhorn upgrade from v1.2.4 to master-head completed, upgrade engine-image to master-head did not occur any problem
