### ISSUE TITLE
[BUG] [v1.3.0-rc1] set createSecret :true cause error when install Longhron from Rancher Chart 

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#4007]
## Describe the bug

Use Rancher Chart v1.3.0-rc1 install Longhorn from private registry 
If enable `Create Secret for Private Registry` Settings or set  `createSecret : true` in yaml
After longhron-crd complete, longhorn installation will strop by error `Error: secrets <secret name> already exists`

## To Reproduce

1. Set up air gap environment
2. Set up Rancher server v2.6
3. Import chart v1.3.0-rc1
4. Install Longhorn by Rancher chart and enable `Create Secret for Private Registry`  when input apply private registry credential
5. After longhorn-crd complete,  longhorn installation will strop by error

## Expected behavior

Longhorn should success

## Log or Support bundle

```
helm upgrade --install=true --namespace=longhorn-system --timeout=10m0s --values=/home/shell/helm/values-longhorn-crd-100.2.1-up1.3.0-rc1.yaml --version=100.2.1+up1.3.0-rc1 --wait=true longhorn-crd /home/shell/helm/longhorn-crd-100.2.1-up1.3.0-rc1.tgz
Release "longhorn-crd" does not exist. Installing it now.
creating 17 resource(s)
beginning wait for 17 resources with timeout of 10m0s
NAME: longhorn-crd
LAST DEPLOYED: Fri May 20 00:18:27 2022
NAMESPACE: longhorn-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
---------------------------------------------------------------------
SUCCESS: helm upgrade --install=true --namespace=longhorn-system --timeout=10m0s --values=/home/shell/helm/values-longhorn-crd-100.2.1-up1.3.0-rc1.yaml --version=100.2.1+up1.3.0-rc1 --wait=true longhorn-crd /home/shell/helm/longhorn-crd-100.2.1-up1.3.0-rc1.tgz
---------------------------------------------------------------------
helm upgrade --install=true --namespace=longhorn-system --timeout=10m0s --values=/home/shell/helm/values-longhorn-100.2.1-up1.3.0-rc1.yaml --version=100.2.1+up1.3.0-rc1 --wait=true longhorn /home/shell/helm/longhorn-100.2.1-up1.3.0-rc1.tgz
Release "longhorn" does not exist. Installing it now.
W0520 00:18:30.778632 46 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
creating 24 resource(s)
W0520 00:18:30.816704 46 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Error: secrets "chris-sec" already exists
```
## Environment

 - Longhorn version: v1.3.0-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VM
 - Number of Longhorn volumes in the cluster: 0

## Additional context

If not enable `Create Secret for Private Registry` and use exist secret of private registry, Longhorn install succussfully

**Comment by derekbit** [comment]
The error is because the duplicate `registry_secret.yml` in [rancher chart](https://github.com/innobead/charts-1/tree/longhorn-1.3.0-2.6/charts/longhorn/100.2.1%2Bup1.3.0-rc1/templates).

cc @innobead

**Comment by innobead** [comment]
> The error is because the duplicate `registry_secret.yml` in [rancher chart](https://github.com/innobead/charts-1/tree/longhorn-1.3.0-2.6/charts/longhorn/100.2.1%2Bup1.3.0-rc1/templates).
> 
> cc @innobead

It seems we have some external contribution, but forgot to remove that one in the Rancher chart :disappointed:  Let me fix this.

**Comment by innobead** [comment]
@cchien816 the chart PR is updated. Please help verify it again. Thank you.

https://github.com/rancher/charts/pull/1899

**Comment by cchien816** [comment]
**Verified on chart PR longhorn-1.3.0-2.6(d4711e948a004f9783383f6fcb3d697d508e38b5)
Result Pass**

Using Rancher chart to install Longhorn with private registry info apply 
Longhon 1.3.0-rc1 can both install success in below chart setting:
1. set `createSecret : true`
2. set `createSecret :` (empty)
