### ISSUE TITLE
[QUESTION] Replicating HEAD without snapshot to avoid 2x disk usage?

### ISSUE THREAD

**Issue by paul-grozav** [longhorn/longhorn#4011]
## Question
Hello, I'm running Longhorn on my cluster, and I have a PVC which holds prometheus data (let's say 100GiB). This volume has a replica count of 3. I wonder why does Longhorn need to create a snapshot of my data. Can't Longhorn be configured so that it only keeps the head, and replicate that on the other nodes? Apparently this is how it works until the first replica failure, when Longhorn automatically creates a system/hidden snapshot, which might use another 100 GiB and can not be deleted.

I understand that Longhorn has it's way of doing things, but I'm thinking about MySQL replication for example. If I have a 100GiB database replicated on 3 nodes, it only takes 100 GiB on each node, not 200 GiB on each node.

I'm not sure what am I missing, why Longhorn needs to keep a snapshot instead of just replicating the head. Sure, I understand that snapshots are required in some situations, but in my case(keeping historical data), I don't need snapshots - historical data will not change.

## Environment

 - Longhorn version: 1.2.3
 - Kubernetes version: 1.23.5
 - Underlying Infrastructure: Baremetal

Thank you !

**Comment by paul-grozav** [comment]
It seems I managed to better understand how this works, and I think I have a good enough answer to my question.

It seems that the HEAD is only holding "new" data, after the last snapshot. When there is no snapshot, all the data is in the HEAD. When a snapshot is created, all the data is moved from the HEAD into the snapshot, and the HEAD size drops to 0 bytes. The fact that HEAD size drops to 0 is an important aspect for me, because that means that I had a poor understanding / bad image in my head.

It seems that what I wanted (only store 1x the data, not 2x) can be achieved but not by removing the snapshot from the picture. But, by creating a snapshot more often. Because all "new data" accumulated in the last 5 minutes or so, will be applied to the last snapshot, and the HEAD will drop back to 0. Thus, staying (possibly) just a bit over 100% actual size. For example the actual size of a 100GiB volume, with a snapshot of 99.8 GiB and a HEAD of 2 GiB, might be ~102%, but it will drop back to ~100% as soon as I recreate (and merge) a snapshot.

So, when a snapshot is created, all the data is moved from the HEAD into a snapshot, and head is recreated from 0 bytes. Then this newly created snapshot will have exactly the same size as the HEAD. Be it 2GiB, to continue the previous example. But, when we merge this new snapshot with the old/previous snapshot(99.8GiB), the new, resulting snapshot will not be of size (99.8 + 2) GiB, but instead it will probably be 99.9 GiB or so. That is because a huge part of the data/sectors/bytes(not sure) from the new snapshot will overwrite part of the old snapshot. Thus, these will not increase the snapshot size, when applied on the old snapshot. And only a very tiny amount of data from the new snapshot will be appended, will increase the old(newly created by merge) snapshot. And it's important to notice that both the snapshot(s) and the HEAD are limited to your original allocation(100GiB in my case) - so neither can grow above that amount.

So, a recap. Even if I end up using 2x the disk space, 2 x 100GiB, once for the 100GiB snapshot and another piece of 100GiB for the HEAD, this whole 200GiB can easily be reduced to just 100GiB by creating a snapshot. A new snapshot(merged with the previous one) will result in a snapshot of 100GiB and a HEAD of ~0bytes(continuously increasing).

So, it's best to schedule snapshots often, to keep your actual disk usage as close as possible to the original allocated disk space. Also, keeping a retention of only 1 will make sure to merge your snapshots into only 1 instance. On the other hand you might want to avoid taking snapshots too often, as this might create a pressure on the CPU/disk/etc (not sure). I started with a snapshot every 10 minutes, but I'll adjust it as needed in time.

I thought I'd let "my" explanation here for the future, if someone else might be in my position and understand it.

Thank you!

**Comment by PhanLe1010** [comment]
Hi @paul-grozav 

The system snapshots are usually created when one of the replicas of the volume crash. Longhorn will take a system snapshot to rebuild the failed replica. Longhorn needs to take a system snapshot before rebuilding because it is not possible to copy the live volume head which is being written by the application layer. 

I do see your concern about space usage. Something you can do to mitigate this issue:
1. Create a snapshot recurring snapshot job that have retain count set 1 ([instruction](https://longhorn.io/docs/1.2.4/snapshots-and-backups/scheduling-backups-and-snapshots/)). This will periodically take/delete snapshots so that the volume has 2 snapshots. This mean that 100Gb volume may go up to 200Gb but not more than that.

We are also working on another feature that allows the users to collapse the volume head with its parent snapshot. This might further improve space usage. But it is not here yet
