### ISSUE TITLE
[BUG] Replicas fail to rebuild

### ISSUE THREAD

**Issue by lukaszraczylo** [longhorn/longhorn#4018]
## Describe the bug

Replicas fail to rebuild with 1.3.0-RC1

## To Reproduce

Steps to reproduce the behaviour:
Replica rebuild - not sure _why_ it went down in the first instance
The same failure ( context exceeded ) happens when backing volumes few gb big

## Expected behaviour

Replica rebuild successfully

## Log or Support bundle

[longhorn-support-bundle_bfd4b99e-7573-462c-95ec-588a671497f4_2022-05-23T08-09-58Z.zip](https://github.com/longhorn/longhorn/files/8752688/longhorn-support-bundle_bfd4b99e-7573-462c-95ec-588a671497f4_2022-05-23T08-09-58Z.zip)

## Environment

 - Longhorn version: 1.3.0-rc1
 - Installation method: kustomize on helm chart
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 11
 - Node config
   - OS type and version: RPI
   - CPU per node: 4
   - Memory per node: 4
   - Disk type(e.g. SSD/NVMe): nvmes 
   - Network bandwidth between the nodes: 1gbit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal
 - Number of Longhorn volumes in the cluster: 12

**Comment by innobead** [comment]
This is probably related to a known issue in RC1 about the communication between manager and instance manager. We will have RC2 in near future, so we can recheck this.

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by lukaszraczylo** [comment]
From the observations - I've noticed that it also knocked out the coredns (?) for some reason. Really awkward morning to wake up. Can't wait for the RC2 with fix :)

**Comment by lukaszraczylo** [comment]
On a side note - is there _anything_ that could be done right now to mitigate the issue?

**Comment by innobead** [comment]
Do you have any reproduce steps? I would suggest you just wait for RC2 because if for the known issue I mentioned, there is no mitigation.

**Comment by lukaszraczylo** [comment]
Create any 10gb volume, fill it up half way, restart the node to trigger rebuild process

**Comment by PhanLe1010** [comment]
By the way, `RC` releases are not recommended for the end users as it is being tested/verified by our QAs

**Comment by lukaszraczylo** [comment]
Thank you, I am fully aware, yet 1.2.4 caused even more issues so my thinking was "if it's already broken, can't get any worse"

**Comment by PhanLe1010** [comment]
>  1.2.4 caused even more issues 

Could you provide more details about the issues that you are facing with v1.2.4?

**Comment by lukaszraczylo** [comment]
It looks like rc2 fixed the context deadline exceeded issue - rebuilding 50G volumes at the moment. If you won't hear from me in next 24h - this bug report can be closed :)

**Comment by derekbit** [comment]
If you hit it again, feel free to open the ticket. Thank you.

**Comment by lukaszraczylo** [comment]
@derekbit definitely, thank you so much. To be fair RC2 is the most stable version of longhorn I've ran so far [ funnily enough, it's RC2 ]. Not even a single issue in 12 days. You're smashing it! :)
