### ISSUE TITLE
[TEST] Use a release version of external snapshotter in e2e pipelines

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4027]
## What's the test to develop? Please describe

The current e2e relies on the master branch of external snapshotter and the manifests applying are incorrect due to the wrong version of kustomize resource, so this will cause some unexpected results. 

![image](https://user-images.githubusercontent.com/899492/170071877-b599f5c6-92c1-4fe1-9b07-736e01999ba2.png)

## Describe the items of the test development (DoD, definition of done) you'd like
Apply below to all release pipelines (master/1.3.0, 1.2.x and 1.1.x)

- [x] Use https://github.com/kubernetes-csi/external-snapshotter/tree/release-4.0/client/config/crd
- [ ] Use https://github.com/kubernetes-csi/external-snapshotter/tree/release-4.0/deploy/kubernetes/snapshot-controller

## Additional context

[Add any other context or screenshots about the test request here.](https://kubernetes-csi.github.io/docs/snapshot-controller.html)

cc @longhorn/qa

**Comment by innobead** [comment]
@cchien816 I would suggest making this configurable later because each release of the external snapshotter actually has a different support matrix of K8s versions.

Please help create an issue, and add it to the QA board. Thanks.

**Comment by cchien816** [comment]
After the fix merged, the external snapshotter  and ,manifest apply error not happen in our e2e pipelne as below

- Master build [135](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/135/)
- v1.2.x build [109](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/109/)
- v1.1.x build [113](https://ci.longhorn.io/job/public/job/v1.1.x/job/v1.1.x-longhorn-tests-sles-amd64/113/#showFailuresLink)

Close this issue
