### ISSUE TITLE
[TEST] Add uninstall test case

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4031]
## What's the test to develop? Please describe

A clear and concise description of what the test you want to develop.

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

Add any other context or screenshots about the test request here.

**Comment by chriscchien** [comment]
This ticket implemented in https://github.com/longhorn/longhorn/issues/9222 with robot framework
