### ISSUE TITLE
[BUG] test_rwx_parallel_writing failed at missing awk

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4035]
## Describe the bug

https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/134/testReport/junit/tests/test_rwx/test_rwx_parallel_writing/

## To Reproduce

1. Run `test_rwx_parallel_writing`.

## Expected behavior

Not missing `awk`.

## Log or Support bundle

```
>       assert md5sum1 == share_manager_data1
E       AssertionError: assert 'd92d8d41dc54...e8f53af4518\n' == '/bin/sh: awk...d not found\n'
E         - d92d8d41dc545d1b8fde8e8f53af4518
E         + /bin/sh: awk: command not found
```

## Environment

`n/a`

## Additional context

`None`

**Comment by innobead** [comment]
cc @longhorn/qa @cchien816

**Comment by kaxing** [comment]
related issues/PRs:
https://github.com/longhorn/longhorn-tests/pull/950
https://github.com/longhorn/longhorn-tests/pull/952
https://github.com/longhorn/longhorn-tests/pull/953

just a note that `tar` is also not included in **bci/python**, if anyone wants to use `$ kubectl cp`

**Comment by innobead** [comment]
It seems the case still failed in a recent build https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1398/

**Comment by mantissahz** [comment]
longhorn-shared-manager:[v1_20220523](https://github.com/longhorn/longhorn-share-manager/releases/tag/v1_20220523) does not has the [commit](https://github.com/longhorn/longhorn-share-manager/pull/32/commits/2f3f366a9bdb9cc01a54351e36be96673810a196), so awk package is still not installed in.

**Comment by innobead** [comment]
@mantissahz Please close this after it passes in our daily run. Thanks

**Comment by derekbit** [comment]
test_rwx.py e2e
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1421/
