### ISSUE TITLE
[IMPROVEMENT] Add gRPC conn metrics between longhorn-manager and instance-manager

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4038]
## Is your improvement request related to a feature? Please describe

Having metrics of gRPC connections between the longhorn manager and instance manager will give us a better understanding of how much cost spent on the communication among components

## Describe the solution you'd like

Expose metrics of gRPC connections (process manager, proxy) via metrics endpoint. 

## Describe alternatives you've considered

N/A

## Additional context

#2821 
https://github.com/longhorn/longhorn-manager/pull/1338

**Comment by yangchiu** [comment]
Verified passed on master-head.
`longhorn_instance_manager_proxy_grpc_connection` can be found in REST endpoint `http://longhorn_manager_ip/:PORT/metrics`
