### ISSUE TITLE
[QUESTION] New StorageClass to point to a different volume on the host ?

### ISSUE THREAD

**Issue by iangregsondev** [longhorn/longhorn#4042]
## Question
Hi, 

Can anyone help ?

I have longhorn setup as normal and its working fine, but I needed to add a new storage device to the machine (node), I have set this to NOT schedule as its only for specific things. Its quite a slower disk.

Its mounted in the node itself  as /storage-box, so its accessible using "ls"

How do I create a new storage class that points to this disk ? I couldn't find a setting in the longhorn provisioned to change the path.

If I have a new storageclass that points to the new disk (path) then I can use this storageclass in certain helm/deployments that I am using.

Maybe I am doing it wrong, if anybody can help that would be great.

Here is the settings, as you can see I have added the disk until Longhorn UI and set it to NOT SCHEDULE so I assume the only part I am missing is the storgageclass to point to this new disk.

I would like only certain deployments to use this disk.

![image](https://user-images.githubusercontent.com/2370364/170654940-5afcb766-19a6-4069-bda5-ec491efdb059.png)

![image](https://user-images.githubusercontent.com/2370364/170655226-fd7c72bf-deba-416c-acbe-678edac18a7c.png)

Here are my existing storage classes

![image](https://user-images.githubusercontent.com/2370364/170655474-3206bfde-ad17-4900-b761-221f93209a5f.png)

## Environment

 - Longhorn version: latest
 - Kubernetes version: latest
 - Node config
   - OS type and version Linux 22.0
   - CPU per node: 8
   - Memory per node: 64GB
   - Disk type SSD main disk and NFS other disk

**Comment by PhanLe1010** [comment]
> I had to make it schedule: true, but from what I understand - although I am not sure, is that if a drive has a tag then the storage class MUST specify it to for it to be able to be used.

No, the PVC that use your default storageclass which doesn't specify any tag will try to use all node/disk.

**Comment by iangregsondev** [comment]
Oh, Thanks @PhanLe1010 , so, do mean i should apply a tag to my default disk and edit the default storage class to specify ONLY to use this new tag then ?

**Comment by PhanLe1010** [comment]
Yeah, I am thinking about that approach. However, there is a problem with the existing volumes that are already created by the old version of the storageclass. Those volume will have no tag, therefore, when Longhorn decide to rebuild a replica for those volume, Longhorn might reschedule the replicas on to the slow disk
