### ISSUE TITLE
[TEST] Verify e2e failed cases on master-head build 139

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#4047]
## What's the test to develop? Please describe

Recently failed cases below
https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/139/#showFailuresLink

test_ha.test_dr_volume_with_restore_command_error[s3]
test_basic.test_allow_volume_creation_with_degraded_availability
test_ha.test_ha_salvage
test_backing_image.test_ha_salvage_with_backing_image
test_basic.test_backuptarget_available_during_engine_image_not_ready
test_cloning.test_cloning_interrupted
test_rwx.test_rwx_parallel_writing

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] Reproduce them, see it's issue or flaky

## Additional context

N/A

**Comment by cchien816** [comment]
- test_ha.test_dr_volume_with_restore_command_error[s3]
- test_basic.test_allow_volume_creation_with_degraded_availability
- test_ha.test_ha_salvage
- test_backing_image.test_ha_salvage_with_backing_image
- test_basic.test_backuptarget_available_during_engine_image_not_ready
- test_cloning.test_cloning_interrupted
- test_rwx.test_rwx_parallel_writing - https://github.com/longhorn/longhorn/issues/4035

**Comment by cchien816** [comment]
Most of the failure not happen in master [build](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/156/testReport/) .

Remain
test_allow_volume_creation_with_degraded_availability_csi  https://github.com/longhorn/longhorn/issues/4121
test_cloning.test_cloning_interrupted https://github.com/longhorn/longhorn/issues/4045

**Comment by innobead** [comment]
This is awesome! @longhorn/qa

**Comment by cchien816** [comment]
Close this ticket and create new one to tracking test result after v1.3.0 release

**Comment by innobead** [comment]
Thanks @cchien816 👍
