### ISSUE TITLE
[TEST] Fix flaky ha_salvage_test

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#4051]
## What's the test to develop? Please describe

Function `ha_salvage_test` in `test_ha.py` is flaky.

Because it will try get specific volume state 'faulted' but in recent build, LH volume recover from faulted to detached state almost immediate,  `ha_salvage_test` hard to correct capture expected volume state

## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] Submit fix PR
- [ ] Verify on pipeline

## Additional context

Related test case

- test_backing_image.test_ha_salvage_with_backing_image 
- test_ha.test_ha_salvage

**Comment by c3y1huang** [comment]
https://github.com/longhorn/longhorn-tests/pull/977
https://github.com/longhorn/longhorn/issues/4045

cc @cchien816

**Comment by cchien816** [comment]
Close this issue since we already have issue for this issue

**Comment by innobead** [comment]
caused  a side effect: https://github.com/longhorn/longhorn-tests/pull/982#discussion_r887620154
