### ISSUE TITLE
[BUG] When downloading a backing image, the original file name w/ suffix should be reserved

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4052]
## Describe the bug

When downloading a backing image from UI, the image name will be a randomly generated name. 

```
file ~/Downloads/74e1eb99
/home/davidko/Downloads/74e1eb99: QEMU QCOW Image (v3), 33554432 bytes
```

## To Reproduce

1. Create a backing image
2. When it's ready, download it

## Expected behavior

The file name should be kept as the upload/download from the remote 

## Environment

 - Longhorn version: 1.3.0-rc2

**Comment by shuo-wu** [comment]
The downloaded file name is the backing image UUID.
In the current design, the sync server in the BackingImageManager does not understand what a backing image is hence it won't store the backing image **name**. Hence, I just use the UUID as the file name instead.

---

I think we can ask UI to present the UUID on the BackingImage page instead. Then users would know what the file name is.

**Comment by cchien816** [comment]
**Validate on longhorn manager master-head 20220607(e771821e32f2b3fdb274dfe703aac5a711e94956)
Result Pass**

Steps:
1. Create 2 backing images, 1 from URL, 1 from upload
2. After create complete, download both backing images
3. Observe download file name, the file name  kept as the upload/download file UUID displayed UI

**Comment by innobead** [comment]
@cchien816 Could you help retest this based on the new change from https://github.com/longhorn/longhorn-ui/pull/521? Thank you.

**Comment by cchien816** [comment]
**Retest with longhorn-ui cca2d09404045a0327f112bc0139b48f6f14f0ad
Result Pass**

Steps:

1. Create 2 backing images, 1 from URL, 1 from upload
2. After create complete, download both backing images
3. Observe download file name, the file name kept as the upload/download file UUID displayed UI
4. Backing image UUID display correctly in popup window
