### ISSUE TITLE
[BUG] Unexpected high memory usage of the backing image manager

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4055]
## Describe the bug

After downloading a large backing image to local (#3155) or syncing backing images between backing image managers, the pod memory usage may surge.

Once the backing image file is removed from the backing image manager, memory usage will decrease.

## To Reproduce

There are 2 ways of reproducing this.
1. Via Download API
    1. Launch a large backing image.
    2. Download it to local then check the backing image manager pod memory usage `kubectl -n longhorn-system top pod`
2. Via backing image syncing.
    1. Create some backing image files.
    2. Create some volumes with replicas on all nodes  using the backing images.
    3. Attach the volumes.

## Expected behavior

The memory usage should be small or decreased after the download complete.

## Environment

 - Longhorn version: v1.3.0-rc2

## Additional context
- The pprof service of backing image manager pods is on port `8001`. The pprof result indicates that the high memory is probably caused by the gRPC connection.
- It's unrelated to the streaming gRPC API `Watch`.

**Comment by innobead** [comment]
cc @derekbit @PhanLe1010

**Comment by shuo-wu** [comment]
The result shown in `pprof` seems to be caused by this issue: https://github.com/longhorn/backing-image-manager/pull/59

More investigation is needed.

**Comment by derekbit** [comment]
So, the memory usage (`WorkingSet`) from `kubectl top pod` includes the cache.

https://github.com/google/cadvisor/blob/master/info/v1/container.go#L394
https://github.com/google/cadvisor/blob/master/container/libcontainer/handler.go#L836

**Comment by shuo-wu** [comment]
With the fix, both @derekbit and me agree:
1. It's hard to trigger OOM
2. The cache will be cleaned up automatically after several hours, or will be dropped automatically if other pod needed more memory

We don't think we need to anything more for this.

**Comment by innobead** [comment]
Closing, and just follow up if any feedback in the future.

**Comment by innobead** [comment]
cc @longhorn/qa
