### ISSUE TITLE
[BUG] Error in little endian support in liblonghorn

### ISSUE THREAD

**Issue by keithalucas** [longhorn/longhorn#4059]
## Describe the bug

There is a logic error in
https://github.com/rancher/liblonghorn/blob/74f14b50895ac6b0faebc715c025a8a46a4333a1/src/longhorn_rpc_protocol.c#L146

This should be:

```Offset = le64toh(Offset);```

The PR for the little endian change for liblonghorn was merged already.

This is in `receive_msg` and liblonghorn doesn't actually use the value that is receives for the Offset for anything, but this bug will make the value of Offset in the message be 0.

**Comment by innobead** [comment]
Closing due to that attribute not actually being used by Longhorn. @longhorn/qa will follow up if any outstanding issues in e2e later on. 

cc @derekbit
