### ISSUE TITLE
[IMPROVEMENT] Restoring a backup to create a volume should keep the original storage class

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4063]
## Is your improvement request related to a feature? Please describe

Currently, when restoring a backup to create a volume will use the default storage class configured on the system. Usually, what users really expect is to keep the original storage class when creating a new PV/PVC. 

## Describe the solution you'd like

When creating a new volume/PV/PVC, we should keep using the original storage class name of the original volume

## Describe alternatives you've considered

N/A

## Additional context

N/A

cc @PhanLe1010 @derekbit

**Comment by innobead** [comment]
@mantissahz IIRC, this has been fixed by your in another issue?

**Comment by mantissahz** [comment]
>@mantissahz IIRC, this has been fixed by you in another issue?

No, not by me. And this issue https://github.com/longhorn/longhorn/issues/3506 is probably what you mentioned about. It is from @ChanYiLin.
It stores the storage class name in the `Status` of the `BackupVolume` CR.

**Comment by ChanYiLin** [comment]
@innobead Yes this feature has already been implemented and released in v1.5.0

**Comment by innobead** [comment]
Thanks @mantissahz and @ChanYiLin confirmation.
