### ISSUE TITLE
[BUG] longhorn-manager panic if UI deployment missing and updating CA settings

### ISSUE THREAD

**Issue by afarresg** [longhorn/longhorn#4065]
Hello,

We are developing a product on top of Kubernetes and Longhorn that sets up a cluster programmatically. We don't make use of the Longhorn UI to set up Longhorn. Would it be possible to disable the creation of the Longhorn UI pod without having to scale down its deployment? If not, are there any plans in the near future to support it?

Up until now, we patched the Helm Chart and disabled the deployment. Since the latest release, it's no longer possible, since the method [HasLocalStorageInDeployment](https://github.com/longhorn/longhorn-manager/blob/3704a5c43f4574efeb0a3e84091c2f008b48d0ea/controller/setting_controller.go#L585-L597) assumes that the UI deployment exists, which in our case doesn't, throwing a null pointer.

Thank you for your time

**Comment by c3y1huang** [comment]
Thank you @afarresg for reporting. This is a bug on our side. We will fix this and you should be able to patch the Helm Chart as usual.

**Comment by innobead** [comment]
@mantissahz Please help verify this. Thank you.

cc @longhorn/qa

**Comment by mantissahz** [comment]
Verified on v1.23.6+k3s1 cluster with master-head image 2022/06/13
Validation - PASSED

Steps:

1. helm install Longhorn
2. delete `deployment/longhorn-ui`
3. update `setting/kubernetes-cluster-autoscaler-enabled` to true or false
4. longhorn-manager pods still are `Running`
