### ISSUE TITLE
[TEST] cleanup volumes failed causes cascading error

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#4066]
## What's the test to develop? Please describe

Sometimes the tear down function `cleanup_all_volumes` could fail and cause volumes remained in longhorn, and cause following test cases failed in their setup function.

like:
https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-upgrade-tests-sles-arm64/129/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1407/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1429/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1436/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1437/

**Comment by chriscchien** [comment]
Close this ticket

Last time the cascading error logged [here](https://github.com/longhorn/longhorn/issues/4957) and resolved, we can create another one if cascading happen again
