### ISSUE TITLE
[QUESTION] Can I attach a PV as a Longhorn Disk

### ISSUE THREAD

**Issue by arontsang** [longhorn/longhorn#4071]
My kube is on some custom cluster setup.

My nodes are dynamically provisioned (node IDs aren't stable), and I have access to some statically provisioned RWO PVs (block storage).

I am trying to re-export the block storage through Longhorn so I can

 - Divide up the block storage between stateful sets
 - Export slices of the storage as NFS for RWX PVs
 - Replicate storage between the backing stores for HA

Is it possible to attach the block storage to some StatefulSets, and attach them to Longhorn through these pods?

**Comment by derekbit** [comment]
Can you mount the block storage on your worker node? If yes, you can mount it and them add it to the Longhorn work node's disk list.

**Comment by arontsang** [comment]
@derekbit The problem is that the worker nodes aren't stable (dynamically provisioned). Therefore, I have no control of when the nodes are added/removed, nor do I have control over the node-id.

Given that volumes in longhorn seem to be addressed by node-id, this seems to mean that when the block storage is attached, longhorn might not realize it is the same volume.

Additionally, if the storage is attached to a node that is then shutdown, there is nothing to reattach that block storage to an existing node. Long horn would also need to automagically register that block device as the existing volume....

If instead it were possible to attach storage from a pod (rather than a node), all my problems would go away.

**Comment by arontsang** [comment]
I noticed that Rook supports running Ceph with the Ceph OSD components in a Statefulset, rather than as a Daemon, which would solve my issue.

However, Ceph has rather steep requirements compared to Longhorn.

Is it possible to run the Longhorn storage backend as a StatefulSet rather than as a Daemon?

**Comment by arontsang** [comment]
Switched to kadalu instead. That supports attach to PV.
