### ISSUE TITLE
[BUG] Downloaded backing image state incorrect after restarting/upgrading the backing image manager

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4073]
## Describe the bug

After refactoring #3970, the downloaded backing image will be wrongly updated to `ready-for-transfer` and the backing image data source pod will be re-launched as well. This is not what we expected.

## To Reproduce

1. Create a backing image from a download URL
2. Wait for the backing image ready
3. Restarting the corresponding backing image manager pod or directly upgrade the backing image manager image
4. Check the backing image state

## Expected behavior

The backing image manager should become ready soon without re-laucnhing the backing image data source pod.

## Environment

 - Longhorn version: v1.3.0-rc2

**Comment by kaxing** [comment]
Validation - **PASSED**

Backing Image Manager won't launch DS pods even when force deleting the working bi working pods.

Testing with following image combination from master branch:
- longhorn-manager@sha256:be3d8fa02ec4a2d58b0265069fb01c29c57c977dfcb7ac9fc761d534eca17a91
- longhornio/backing-image-manager:v3_20220606 => backing-image-manager@sha256:96b89b83373cfa1a0860fef9cc9459935a60096d0786f6a06ec0fe7e5f0d8d25

Commands to force deleting the pods:
`kubectl delete pods -l longhorn.io/component=backing-image-manager -n longhorn-system`
