### ISSUE TITLE
[BUG] Backing image download or upload timeout does not work

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4074]
## Describe the bug

When the download URL suddenly becomes invalid or the upload is interrupted, the in-progress backing image should be marked as failed after a timeout.

## To Reproduce

1. Create a backing image from local file upload via UI
2. When the upload is started and in progress, refreshing the page
3. Wait a while => The backing image gets stuck in state `in-progress` forever

(I think we can test it with a downloading backing image. Then in step2, we need to somehow stop the file service during the downloading)

## Expected behavior

the in-progress backing image should be marked as failed after a timeout.

## Environment

 - Longhorn version: v1.3.0-rc2

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested with v1.3.0-rc3 plus bi-manager dev img.

With the latest change, now the backing image upload got interrupted will be showing failed state:
![image](https://user-images.githubusercontent.com/602540/172788195-4c78f2c0-a206-405f-98dc-8021720d50fb.png)

Additionally, if there are file size under the expectation there will be error message:
![image](https://user-images.githubusercontent.com/602540/172788586-db94d110-82f3-4990-bb18-add8d286525b.png)

**Comment by shuo-wu** [comment]
The file size check is expected behavior.
