### ISSUE TITLE
[IMPROVEMENT] Revert backup target related gRPC to binary calls

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4076]
https://github.com/longhorn/longhorn-manager/pull/1361#issuecomment-1147257498

**Comment by c3y1huang** [comment]
Testing:
- Full regression: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1476/

**Comment by innobead** [comment]
This is an internal change, so we can rather rely on the e2e, but QA can help with verifying some backup operations as well to see if it works as expected.

**Comment by c3y1huang** [comment]
> @c3y1huang Please help identify some backup cases needed to verify by QA if needed. Thanks.

For a single network cluster, we can rely on the full regression test result and the nightly runs.

I think QA can help verify the tests with the prefix `test_backup` on a dual network cluster (storage network).

**Comment by innobead** [comment]
@cchien816 Please check with @yangchiu who verified the storage network before.

**Comment by cchien816** [comment]
**Validate on master-head e771821e32f2b3fdb274dfe703aac5a711e94956
Result Pass**

1. Follow [manual test plan](https://github.com/longhorn/longhorn-tests/blob/9f19673653dd158ddcae24cb8563b47d4a6c69d0/docs/content/manual/release-specific/v1.3.0/test-storage-network.md), created eth0 (10.0.1.0/24) and eth1 (10.0.2.0/24) for each instance, after update storage network setting value to `kube-system/demo-192-168-0-0`, can observe each instance-manager pod have correct annotation and engine will have `storageIP: 192.168.x.x` 
2. Run test with prefix `test_backup`, test case were passed
