### ISSUE TITLE
i Have Master node a linux and worker nodes Windows i am not able to install longhorn 

### ISSUE THREAD

**Issue by prasadve0506** [longhorn/longhorn#4077]
## Question
> Suggest to use https://github.com/longhorn/longhorn/discussions to ask questions.

## Environment

 - Longhorn version:
 - Kubernetes version:
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Comment by derekbit** [comment]
Longhorn leverages the Linux features, tools and utilities, e.g. unix domain socket and open-iscsi, so it does not support Windows platform.
