### ISSUE TITLE
[BUG] CSI VolumeSnapshot failed to restore if the source PV/PVC gone

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#4083]
## Describe the bug

We want to restore the PVC from the CSI VolumeSnapshot. Everything works well if the source PV/PVC exists in the cluster.

However, if the source PV/PVC has gone, Longhorn could not restore the PVC with dataSource points to the existed VolumeSnapshot, the error message shows the Volume CR is not found.

## To Reproduce

1. Create source PVC and Pod
   ```yaml
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: longhorn-simple-pvc
   spec:
     accessModes:
       - ReadWriteOnce
     storageClassName: longhorn
     resources:
       requests:
         storage: 1Gi
   ---
   apiVersion: v1
   kind: Pod
   metadata:
     name: longhorn-simple-pod
   spec:
     restartPolicy: Always
     containers:
       - name: volume-test
         image: nginx:stable-alpine
         imagePullPolicy: IfNotPresent
         livenessProbe:
           exec:
             command:
               - ls
               - /data/lost+found
           initialDelaySeconds: 5
           periodSeconds: 5
         volumeMounts:
           - name: volv
             mountPath: /data
         ports:
           - containerPort: 80
     volumes:
       - name: volv
         persistentVolumeClaim:
           claimName: longhorn-simple-pvc
   ```
1. Exec into pod `longhorn-simple-pod` and create a new file under /data
   ```shell
   kubectl exec -it longhorn-simple-pod -- touch /data/1
   ```
1. Create the VolumeSnapshotClass and VolumeSnapshot
   ```yaml
   kind: VolumeSnapshotClass
   apiVersion: snapshot.storage.k8s.io/v1
   metadata:
     name: longhorn-snapshot-vsc
   driver: driver.longhorn.io
   deletionPolicy: Retain
   parameters:
     type: snap
   ---
   apiVersion: snapshot.storage.k8s.io/v1
   kind: VolumeSnapshot
   metadata:
     name: test-csi-volume-snapshot-longhorn-snapshot
   spec:
     volumeSnapshotClassName: longhorn-snapshot-vsc
     source:
       persistentVolumeClaimName: longhorn-simple-pvc
   ```
1. Waits the VolumeSnapshot and VolumeSnapshotContent become ready, we observe that the Snapshot CR is created as well
1. Delete the source PVC and source Pod
   ```shell
   kubectl delete pod longhorn-simple-pod
   kubectl delete pvc longhorn-simple-pvc
   ```
1. Create another PVC and Pod, the PVC data source points to the VolumeSnapshot
   ```yaml
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: test-restore-pvc
   spec:
     storageClassName: longhorn
     dataSource:
       name: test-csi-volume-snapshot-longhorn-snapshot
       kind: VolumeSnapshot
       apiGroup: snapshot.storage.k8s.io
     accessModes:
       - ReadWriteOnce
     resources:
       requests:
         storage: 1Gi
   ---
   apiVersion: v1
   kind: Pod
   metadata:
     name: longhorn-restore-simple-pod
   spec:
     restartPolicy: Always
     containers:
       - name: volume-test
         image: nginx:stable-alpine
         imagePullPolicy: IfNotPresent
         livenessProbe:
           exec:
             command:
               - ls
               - /data/lost+found
           initialDelaySeconds: 5
           periodSeconds: 5
         volumeMounts:
           - name: volv
             mountPath: /data
         ports:
           - containerPort: 80
     volumes:
       - name: volv
         persistentVolumeClaim:
           claimName: test-restore-pvc
   ```
1. Describe the PVC `test-restore-pvc`, it displays the Volume CR not found
   ```shell
   Events:
     Type     Reason                Age                From                                                                                      Message
     ----     ------                ----               ----                                                                                      -------
   Warning  ProvisioningFailed    21s (x2 over 34s)  driver.longhorn.io_csi-provisioner-869bdc4b79-kg6lh_e8afe020-d35b-434f-967d-c03b63e64b11  failed to provision volume with StorageClass "longhorn": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=unable to create volume: unable to create volume pvc-9e1e3b7b-ca73-4c05-98f3-6adda6cbb7b7: failed to verify data source: volume.longhorn.io "pvc-1864d300-3f91-4caf-902c-09e3ed724796" not found, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes]
   Normal   Provisioning          5s (x6 over 34s)   driver.longhorn.io_csi-provisioner-869bdc4b79-kg6lh_e8afe020-d35b-434f-967d-c03b63e64b11  External provisioner is provisioning volume for claim "longhorn-system/test-restore-pvc"
   Warning  ProvisioningFailed    5s (x4 over 34s)   driver.longhorn.io_csi-provisioner-869bdc4b79-kg6lh_e8afe020-d35b-434f-967d-c03b63e64b11  failed to provision volume with StorageClass "longhorn": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to create volume: unable to create volume pvc-9e1e3b7b-ca73-4c05-98f3-6adda6cbb7b7: failed to verify data source: volume.longhorn.io "pvc-1864d300-3f91-4caf-902c-09e3ed724796" not found] from [http://longhorn-backend:9500/v1/volumes]
   Normal   ExternalProvisioning  4s (x4 over 34s)   persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
   ``` 

## Expected behavior

The PVC should be restorable if the VolumeSnapshot and VolumeSnapshotContent existed, even the source PV/PVC was gone.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.3.0-rc2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.23.6+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 0
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

Even changing the `longhorn` StorageClass delete policy to `Retain`, it still does not work as expected.

**Comment by innobead** [comment]
This is the current limit because the lifecycle of a longhorn snapshot is bound to its owner volume. 

https://v1-3-0--longhornio.netlify.app/docs/1.3.0/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-snapshot/#current-limitation

cc @PhanLe1010

**Comment by innobead** [comment]
This is not a limitation but rather a design. Closing first but see if any feedback later.

**Comment by jelemux** [comment]
Is there any plan to reopen this? This functionality would be of great use to us.

**Comment by innobead** [comment]
> Is there any plan to reopen this? This functionality would be of great use to us.

May I understand more about your use case?

**Comment by jelemux** [comment]
We're trying to do backups with Velero. There we faced this issue when restoring Longhorn snapshots through Velero using CSI. Tbf even if this worked, we'd still face the issue that the Longhorn snapshots would be stored locally in the cluster and not in an object storage, but idk maybe that can be configured in Longhorn?

Anyway, we seem to have found a solution that uses `type: bak` in the `VolumeSnapshotClass` and leaves out the `velero.io/csi-volumesnapshot-class: "true"` label. With this we were able to configure Velero and Longhorn to write the backups to an external S3 object storage. This way, we'll have Longhorn backups instead of snapshots which are not as performant, but we're pretty desperate about finding a solution that works.

We're just not sure why it works, because it does not seem to be the intended way to do this 😅. We're currently investigating why and how this works. I'll post our findings once we know more.

**Comment by jelemux** [comment]
It also seems that #3715 addresses this issue, which would answer my first question.

**Comment by robinjanke** [comment]
Hey @jelemux , I just saw your blog entry and also found this issue. I still face the following issue:

`failed to provision volume with StorageClass "longhorn": rpc error: code = NotFound desc = failed to restore CSI snapshot bak://pvc-0a8bcd45-136c-4f9a-b892-1e8cc27cbb3a/backup-ebb193879dbb4975 backup backup-ebb193879dbb4975 unavailable`

Do you have any idea how to fix that, maybe? I also tried setting the type to bak, but sadly it does not work...
