### ISSUE TITLE
[BUG] Backing image manager does not release ports correctly after file syncing

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4086]
## To Reproduce

1. Create multiple backing images. It's better to make sure the file size is relatively large so that the syncing won't be done immediately.
2. Create and attach multiple volumes using these backing images.
3. Wait for the attachment complete.
4. Repeat the above step until one backing image file gets stuck in the port-already-in-use error

## Expected behavior

There should not be an error when syncing files between backing image managers

## Log or Support bundle

```
[backing-image-manager-88c0-25dd] time="2022-06-07T12:42:43Z" level=info msg="SyncingFile: start to launch a receiver" component=sync-file filePath=/data/backing-images/bi-test3-af03de7b/backing uuid=af03de7b
[backing-image-manager-88c0-25dd] time="2022-06-07T12:42:43Z" level=info msg="Creating Ssync service"
[backing-image-manager-88c0-25dd] time="2022-06-07T12:42:43Z" level=error msg="SyncingFile: failed to process sync file: listen tcp :30002: bind: address already in use" component=sync-file filePath=/data/backing-images/bi-test3-af03de7b/backing uuid=af03de7b
[backing-image-manager-88c0-25dd] time="2022-06-07T12:42:43Z" level=error msg="Sync Service: failed to receive sync file /data/backing-images/bi-test3-af03de7b/backing: listen tcp :30002: bind: address already in use" component=sync-server listen="0.0.0.0:8001"
```

![Screen Shot 2022-06-07 at 8 43 51 PM](https://user-images.githubusercontent.com/47542419/172381842-8e18c221-3e2f-480a-bf31-223b2946eef3.png)

## Environment

 - Longhorn version: v1.3.0-rc2

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by innobead** [comment]
@mantissahz Please help with that testing. Thanks.

**Comment by mantissahz** [comment]
Verified on v1.23.6+k3s1 cluster with master-head image 2022/06/13
Validation - PASSED

Steps:
1. Create six backing images with image sizes 958Mi, 683Mi and 501Mi. 
2. Create six multiple volumes using these backing images and attach them to the node.
3. Wait for the attachment complete.
4. repeat steps 1~3 for six rounds and it won't gets stuck in the port-already-in-use error.
