### ISSUE TITLE
[TEST] Unstable flaky engine test `test_snapshot_mounted_filesystem`

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4089]
## What's the test to develop? Please describe

<details>
<summary>failed test_snapshot_mounted_filesystem</summary>
================================== FAILURES ===================================
_______________________ test_snapshot_mounted_filesystem _______________________

grpc_controller = <rpc.controller.controller_client.ControllerClient object at 0x3ff87633e48>
grpc_replica1 = <rpc.replica.replica_client.ReplicaClient object at 0x3ff875fb470>
grpc_replica2 = <rpc.replica.replica_client.ReplicaClient object at 0x3ff875fb4a8>

    def test_snapshot_mounted_filesystem(grpc_controller,  # NOQA
                             grpc_replica1, grpc_replica2):  # NOQA
        """
        Test that the filesystem on a currently mounted volume
        will be frozen when a snapshot is requested and that
        this does not cause issues for the snapshot process.
    
        1. Create & attach a longhorn volume
        2. Create & mount an ext4 filesystem on that volume in host namespace
        3. Ensure volume mount point can be found in host namespace
        4. Take snapshot 1 (empty filesystem)
        5. Write test file on the filesystem
        6. Take snapshot 2 (test file included)
        7. Overwrite test file on the filesystem
        8. Take snapshot 3 (test file changed)
        9. Observe that logs of engine `Filesystem frozen / unfrozen`
        10. Validate snapshots are created
        11. Restore snapshot 1, validate test file missing
        12. Restore snapshot 2, validate test file original content
        13. Restore snapshot 3, validate test file changed content
        """
        address = grpc_controller.address
        dev = get_dev(grpc_replica1, grpc_replica2, grpc_controller)
>       snapshot_mounted_filesystem_test(VOLUME_NAME, dev, address, ENGINE_NAME)

data/test_snapshot.py:409: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
data/test_snapshot.py:429: in snapshot_mounted_filesystem_test
    subprocess.check_call(mount_cmd)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['nsenter', '--mount=/host/proc/1/ns/mnt', '--net=/host/proc/1/ns/net', '--', 'mount', '--make-shared', ...],)
kwargs = {}, retcode = 32
cmd = ['nsenter', '--mount=/host/proc/1/ns/mnt', '--net=/host/proc/1/ns/net', '--', 'mount', '--make-shared', ...]

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['nsenter', '--mount=/host/proc/1/ns/mnt', '--net=/host/proc/1/ns/net', '--', 'mount', '--make-shared', '/dev/longhorn/test-afcfff90-volume', '/tmp/mnt-test-afcfff90-volume']' returned non-zero exit status 32.

/usr/lib64/python3.6/subprocess.py:311: CalledProcessError
----------------------------- Captured stdout call -----------------------------
dev_path: /dev/longhorn/test-afcfff90-volume

mnt_path: /tmp/mnt-test-afcfff90-volume

Creating filesystem with 4096 1k blocks and 1024 inodes

Allocating group tables: 0/1   done                            
Writing inode tables: 0/1   done                            
Creating journal (1024 blocks): done
Writing superblocks and filesystem accounting information: 0/1   done

----------------------------- Captured stderr call -----------------------------
time="2022-06-07T13:45:03Z" level=info msg="Successfully reset sync agent server"
mke2fs 1.43.8 (1-Jan-2018)
mount: /tmp/mnt-test-afcfff90-volume: /dev/longhorn/test-afcfff90-volume already mounted or mount point busy.
</details>

## Describe the items of the test development (DoD, definition of done) you'd like

- [x] Fix flaky test_snapshot_mounted_filesystem

## Additional context

https://drone-publish.longhorn.io/longhorn/longhorn-engine/357/3/3

**Comment by innobead** [comment]
> Does this only happen on x390?

mostly on arm64 and s390x, randomly each recently. https://drone-publish.longhorn.io/longhorn/longhorn-engine

**Comment by keithalucas** [comment]
Adding `-t ext4` to the mount command also caused it to pass:  https://drone-pr.longhorn.io/longhorn/longhorn-engine/647/2/3

**Comment by derekbit** [comment]
After disabling the` multipathd` on arm64 machine, three `longhorn-engine`  integration tests passed.

**Comment by innobead** [comment]
Closing, see if the longhorn-engine PR testing will work well in the future.
