### ISSUE TITLE
Pods remaining after upgrade to 0.4.0

### ISSUE THREAD

**Issue by paulmorabito** [longhorn/longhorn#409]
Using Rancher 2.1.6 on baremetal and Longhorn 0.4.0. 

After upgrading from 0.3.3, I have a number of pods that are marked as completed as below:

pvc-4e775e3e30f511e9-c-dykwsm-c-1550707200-qfbgn   0/1     Completed   0          2d
pvc-4e775e3e30f511e9-c-dykwsm-c-1550793600-crdzx   0/1     Completed   0          1d
pvc-4e775e3e30f511e9-c-dykwsm-c-1550880000-t5pt9   0/1     Completed   0          10h
pvc-4e775e3e30f511e9-c-qy2n9e-c-1550664000-7xtpz   0/1     Completed   0          2d
pvc-4e775e3e30f511e9-c-qy2n9e-c-1550750400-2m7sr   0/1     Completed   0          1d
pvc-4e775e3e30f511e9-c-qy2n9e-c-1550836800-qj8vp   0/1     Completed   0          22h
pvc-4e775e3e30f511e9-e-4a89134a                    1/1     Running     0          10m
pvc-4e775e3e30f511e9-r-be7282ff                    1/1     Running     0          11m
pvc-4e775e3e30f511e9-r-bef2d045                    1/1     Running     0          11m
pvc-a268195e30be11e9-c-drfw5n-c-1550664000-987vd   0/1     Completed   0          2d
pvc-a268195e30be11e9-c-drfw5n-c-1550750400-n6mw9   0/1     Completed   0          1d
pvc-a268195e30be11e9-c-drfw5n-c-1550836800-ss7jv   0/1     Completed   0          22h
pvc-a268195e30be11e9-c-v49h5l-c-1550707200-qv2c5   0/1     Completed   0          2d
pvc-a268195e30be11e9-c-v49h5l-c-1550793600-bj4hw   0/1     Completed   0          1d
pvc-a268195e30be11e9-c-v49h5l-c-1550880000-7jcq4   0/1     Completed   0          10h
pvc-a268195e30be11e9-e-8c46fb76                    1/1     Running     0          12m
pvc-a268195e30be11e9-r-6f184702                    1/1     Running     0          13m
pvc-a268195e30be11e9-r-dc6be1e5                    1/1     Running     0          13m

In the Rancher UI, these are all using the Longhorn 0.3.3 image. Is it safe to remove these? Can they be auto removed on upgrade?

**Comment by yasker** [comment]
Those completed pods are for recurring snapshot/backups. There are jobs in Kubernetes. https://kubernetes.io/docs/tasks/job/#jobs-history-limits

By default, Kubernetes kept 3 of successful jobs for history log purpose. Yeah, those completed job pods are safe to delete.
