### ISSUE TITLE
[BUG] Delete and resync failed backing image files

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4090]
## Describe the bug

When there is one failed backing image file while others are still available, Longhorn should delete the failed one then do resync for it automatically.

## To Reproduce

1. Create a backing image.
2. Create and attach a volume using the backing image, so that the backing image will be synced to other nodes.
3. Directly remove one backing image file on one node
4. Check the file state on the node/in the disk => It gets stuck in failed forever.

## Expected behavior

The file should be recovered automatically

## Environment

 - Longhorn version: v1.3.0-rc3

**Comment by mantissahz** [comment]
Verified on v1.23.6+k3s1 cluster with master-head image `2022/06/09`
Validation - **PASSED** 

Steps:
 1. Create a backing image.
 2. Create and attach a 3-replica volume using the backing image.
 3. Wait for the attachment complete.
 4. Manually remove the backing image on the current node.
 5. Wait for the file state in the disk/on this node become failed.
 6. Wait for the file recovering automatically.
