### ISSUE TITLE
[BUG] kubectl drain node gets stuck forever

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#4103]
## Describe the bug

In case when drain the node by the command `kubectl drain`, it gets stuck forever with log

`error when evicting pods/"instance-manager-r-dac5b6e6" -n "longhorn-system" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget`

## To Reproduce

1. Setup the Kubernetes cluster and deploy the Longhorn system with v1.3.0-rc3.
2. Create a LHV and do nothing.
3. Use the command `kubectl cordon [worker node]` and then `kubectl drain --force --ignore-daemonsets --delete-emptydir-data --grace-period=10 [worker node]`.
4. And it gets stuck.

## Expected behavior

The drain could finish.

## Environment

 - Longhorn version: v1.3.0-rc3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.23.6+k3s1
   - Number of management node in the cluster: 1 control-plane
   - Number of worker node in the cluster: 3 workers
 - Node config
   - OS type and version: Ubuntu 20.04.4 LTS
   - CPU per node: 2
   - Memory per node: 4G
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 1

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by innobead** [comment]
@cchien816 Could you help verify this? because this was fixed by @mantissahz as well.

**Comment by impsik** [comment]
For me it's draining but it takes 5min or so with kubectl. About that `Cannot evict pod as it would violate the pod's disruption budget`
```
kubectl describe pdb instance-manager -n longhorn-system
Name:           instance-manager-e-4c4a2936
Namespace:      longhorn-system
Min available:  1
Selector:       longhorn.io/component=instance-manager,longhorn.io/instance-manager-image=imi-b6f5233f,longhorn.io/instance-manager-type=engine,longhorn.io/managed-by=longhorn-manager,longhorn.io/node=192.168.122.13
Status:
    Allowed disruptions:  0
    Current:              1
    Desired:              1
    Total:                1
Events:                   <none>
```
I have 3 workernodes. But sadly i'm not able to drain using Ansible (module: kubernetes.core.k8s_drain)
"msg": "Failed to delete pod POD NAME HERE due to: Too Many Requests"
I guess this module works over API.

**Comment by cchien816** [comment]
Tested on longhorn manager-head ec91a689daef211cd0435f840d7fed2f4fb2ae51

Scenarrio 1 - **Pass**
1. Setup the Kubernetes cluster and deploy the Longhorn system with master-head
2. Create a LHV and do nothing.
3. Use the command kubectl cordon [worker node] and then kubectl drain --force --ignore-daemonsets --delete-emptydir-data --grace-period=10 [worker node].
4. Drain work well

Scenarrio 2 - **Stucked**
1. Setup the Kubernetes cluster and deploy the Longhorn system with master-head
2. Create a LHV, PVC and deployment pod mount to PVC
3. Write data to deployment pod
4. Use the command kubectl cordon [worker node] and then kubectl drain --force --ignore-daemonsets --delete-emptydir-data --grace-period=10 [worker node].
5. Drain will stuck with log `Cannot evict pod as it would violate the pod's disruption budget.`

In scenario 2 , If run `kubectl delete poddisruptionbudgets -n longhorn-system --all` and drain node again, drain node will complete smoothly. And uncordon all nodes, can observe that pod data still keep consistency

cc @innobead , @c3y1huang , @mantissahz

**Comment by c3y1huang** [comment]
> Scenarrio 2 - **Stucked**
> 
> 1. Setup the Kubernetes cluster and deploy the Longhorn system with master-head
> 2. Create a LHV, PVC and deployment pod mount to PVC
> 3. Write data to deployment pod
> 4. Use the command kubectl cordon [worker node] and then kubectl drain --force --ignore-daemonsets --delete-emptydir-data --grace-period=10 [worker node].
> 5. Drain will stuck with log `Cannot evict pod as it would violate the pod's disruption budget.`

Is the volume still attached when draining node?

**Comment by cchien816** [comment]
After discussed with @c3y1huang , I understood that Longhorn not allowing drain while volume is still attached.
Update test result

**Tested on longhorn manager-head ec91a689daef211cd0435f840d7fed2f4fb2ae51
Result : Pass**

1. Setup the Kubernetes cluster and deploy the Longhorn system with master-head
2. Create a LHV and do nothing.
3. Use the command kubectl cordon [worker node] and then kubectl drain --force --ignore-daemonsets --delete-emptydir-data --grace-period=10 [worker node].
4. Drain work well

**Comment by cchien816** [comment]
> For me it's draining but it takes 5min or so with kubectl. About that `Cannot evict pod as it would violate the pod's disruption budget`
> 
> ```
> # kubectl describe pdb instance-manager -n longhorn-system
> Name:           instance-manager-e-4c4a2936
> Namespace:      longhorn-system
> Min available:  1
> Selector:       longhorn.io/component=instance-manager,longhorn.io/instance-manager-image=imi-b6f5233f,longhorn.io/instance-manager-type=engine,longhorn.io/managed-by=longhorn-manager,longhorn.io/node=192.168.122.13
> Status:
>     Allowed disruptions:  0
>     Current:              1
>     Desired:              1
>     Total:                1
> Events:                   <none>
> P.S there are more similar rows, i didn't copy all of them here.
> ```
> 
> I have 3 workernodes. But sadly i'm not able to drain using Ansible (module: kubernetes.core.k8s_drain) "msg": "Failed to delete pod POD NAME HERE due to: Too Many Requests" I guess this module works over API.

Hi @impsik ,

Would you mind create another ticket for tacking issue about unable to drain node when using Ansible? thank you

**Comment by c3y1huang** [comment]
@cchien816 , sorry I've misled you. Going through [Updating the Node OS or Container Runtime](https://longhorn.io/docs/1.2.4/volumes-and-nodes/maintenance/#updating-the-node-os-or-container-runtime) and seems we are expecting the engine process to migrate during drain.

https://github.com/longhorn/longhorn/issues/1631#issuecomment-708842694

**Comment by cchien816** [comment]
Update test result

**Tested on longhorn manager-head ec91a689daef211cd0435f840d7fed2f4fb2ae51
Result : Pass**

Scenario 1
1. Setup the Kubernetes cluster and deploy the Longhorn system with master-head
2. Create a LHV and do nothing.
3. Use the command `kubectl cordon [worker node]` and then `kubectl drain --force --ignore-daemonsets --delete-emptydir-data --grace-period=10 [worker node].`
4. Drain work well

Scenario 2
1. Setup the Kubernetes cluster and deploy the Longhorn system with master-head
2. Create a LHV, PVC and deployment pod mount to PVC
3. Use the command `kubectl cordon [worker node] `and then `kubectl drain --force --ignore-daemonsets --delete-emptydir-data --grace-period=10 [worker node]`, `kubectl uncordon  [worker node]` sequentially on each. We need at least 1 schedulable node for migrate.
4. In step 3 can observe deployment pod will migrate to schedulable node during node draining
5. After all node drain and uncordoned, can observe that deployment pod's data still keep consistent
