### ISSUE TITLE
[BUG] gRPC proxy connection leak when failed to get backup target client

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4109]
## Describe the bug

Found when testing for https://github.com/longhorn/longhorn-manager/pull/1379.
![Screenshot-2022-06-13-22:38:41](https://user-images.githubusercontent.com/22583541/173381426-4709ebc4-bd83-494d-8375-962d80c71877.png)

## To Reproduce

1. Deploy Longhorn with https://github.com/longhorn/longhorn-manager/pull/1379 code base.
2. Setup monitoring stack for Longhorn.
3. Run `test_basic.py::test_backup`.
4. Monitor `longhorn_instance_manager_proxy_grpc_connection`.

## Expected behavior

The connection should return to 0 when the test completes.

## Log or Support bundle

'N/A'

## Environment

`N/A`

## Additional context

https://github.com/longhorn/longhorn/issues/4038

**Comment by innobead** [comment]
cc @longhorn/qa @shuo-wu @derekbit

**Comment by cchien816** [comment]
**Verified on https://github.com/longhorn/longhorn-manager/pull/1379
Result Pass**

Test [steps](https://github.com/longhorn/longhorn/issues/4109#issue-1269567402)
After deploy with Longhorn with PR code and setup monitoring stack, can observe during`test_basic.py::test_backup` executing, the connection number greater than 0 and after test complete, the connection number returned to 0 as expected
 
![Screenshot from 2022-06-14 13-33-20](https://user-images.githubusercontent.com/73337386/173501277-09bd189a-33a6-4688-837f-4b2de0189363.png)
