### ISSUE TITLE
Deleting unhealthy Replica has deleted all data

### ISSUE THREAD

**Issue by phal0r** [longhorn/longhorn#411]
Hello guys,

I was facing an error while creating a snapshot, so I decided to delete this replica as a manual failover. My expectation was, that longhorn will generate a new replica and everything runs fine again, but actually all data including all snapshots were deleted. The volume recovered and created new healthy replicas, but the data is still gone. Unfortunately the last backup is one month old. Is there any other folder or mount, where this data got stored (temporarily). Any help is appreciated.

Additional information: The volume staid in Degraded State for some time and didn't recover.

**Comment by yasker** [comment]
How many other replicas except this "unhealthy" replica exists? Longhorn should rebuild successfully if there is at least one. Can you send me the support bundle and the volume name?

Is there any bad replicas still around? Have you detached the volume when data are gone? If there are bad replicas around we may able to recover.

Btw, what do you mean by "unhealthy" replica? If it's yellow, then it's a replica during rebuilding.

**Comment by phal0r** [comment]
I have attached a screenshot, how the unhealthy replica (the grey one) looks like on another volume with the same strange situation.

Unfortunately this was our preparation work to update to 0.4.0. Since we cannot perform backups, we cannot upgrade and so I am unable to generate a support bundle via UI.

The exact steps I took:
- delete the grey (unhealthy) replica
- the other replica got deleted aswell
- volume was detached
- reattaching the volume leaded to 2 new repiclas being created
- volume could be mounted
- all data was gone

![image](https://user-images.githubusercontent.com/3658211/53360442-d587af80-3935-11e9-9811-956f3aa7edbf.png)

**Comment by yasker** [comment]
@phal0r 

Sorry, I think the data is gone with the other (healthy) replica. We should put restraint in place that prevents anyone from deleting the last replica... I've filed #415 for this.

Can you send me the log of all the managers? I'd like to check what cause the healthy replica to be deleted.

**Comment by de-robat** [comment]
hi @yasker any chance that we can somehow inspect the .img file on the replicas. the data is pretty valuable to me and i would be willing to go the distance to get it back. basically all we did was hitting delete on the greyed out replica. everyhting else was afterwards done by longhorn. So before giving up on the replicas i would love to be 100% certain that the data is really gone :/

**Comment by yasker** [comment]
@de-robat 

Can you send me the logs for all the managers? Also, the log for the related replicas, like the one you shows in the screenshot.

If you use the path listed in the volume detail page, you should able to find the raw files stored by the replica. Check the real size of them using `du`. And you can send me the directory file names and all the metadata.

You may want to use some tools in Linux to recover deleted files on the nodes that replicas was running.

**Comment by de-robat** [comment]
sure, i just had to extract it from all involved 3 nodes. As always i added you all the logs into the zip, as well as a screenshot that describes the setup of the volume we encountered the error on. the on @phal0r posted above is not the one that has the problem (yet). because we stopped upgrading yesterday when discovering the error. So to make some sense of the logs i thought it might be a good idea to include the structure of the longhorn volumes too.

the error had occured for us somwhere around 11am yesterday (February the 25th). Which should be 10am UTC.

I'll provide you with the password and the link in slack as ususal.

**Comment by yasker** [comment]
@de-robat I've identified follow issues from the log you sent me:

#415 Prohibit user from deleting the last replica that contains data
#417 manager: enhance failed replica preserve policy
#420 engine: more information should be returned to the caller for "500 Internal Server Error"
#424 engine: tgtd sometime crashed, result in engine crash

And two other issues (#418 and #421) for additional logs.

#415 should prevent this situation from ever happen again. And we're also going to fix #412 which should be the reason that replica failed to complete the rebuilding process.

And #424 looks like the reason you've experienced periodically engine crash.

**Comment by de-robat** [comment]
Thanks for investigating! Well, i consider this issue closed as it is going to be tackeld by the once you linked. Or do you have anything else to add @phal0r ?
