### ISSUE TITLE
[BUG] The last backing image file may not be cleaned up before the backing image manager shutdown

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4111]
## Describe the bug

When the last backing image file is no longer needed, the backing image manager (BIM) will be stopped as well. In this case, the BIM pod may be stopped before the file is successfully cleaned up.

## To Reproduce
Run integration test `test_setting_backing_image_auto_cleanup`

## Expected behavior

There is no leftover in this case.

## Log or Support bundle

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1543/testReport/junit/tests/test_settings/test_setting_backing_image_auto_cleanup/

## Environment

 - Longhorn version: v1.3.0-rc3

**Comment by innobead** [comment]
@mantissahz Please help with this verification. Thanks.

cc @longhorn/qa

**Comment by mantissahz** [comment]
Verified `2022/06/14` with master-head image on 
1. v1.23.6+k3s1 local building cluster
2. Jenkins Integration Test.

Validation - PASSED

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1559
