### ISSUE TITLE
[BUG] a connection not closed in full regression

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4113]
## Describe the bug

We need to figure out why there is a connection remaining in the Prometheus metric after full regression.

## To Reproduce

1. Setup monitoring stack
2. Monitor `longhorn_instance_manager_proxy_grpc_connection` in Grafana panel.
3. Run full regression

## Expected behavior

All connections should return to 0 after the tests are finished.

## Log or Support bundle

`N/A`

## Environment

`N/A`

## Additional context

https://github.com/longhorn/longhorn-manager/pull/1379#issuecomment-1155956950

**Comment by c3y1huang** [comment]
Note: This is likely to be caused by a goroutine leak in the backup monitor when backup CR gets deleted before erroring out or complete.

**Comment by cchien816** [comment]
**Verified on longhorn-manager `8e7d94`
Result Pass**

Steps

- Setup [Prometheus and Grafana](https://longhorn.io/docs/1.3.0/monitoring/prometheus-and-grafana-setup/)
- Import Longhorn Example v1.1.0(13032) in Grafana
- Add metrics `longhorn_instance_manager_proxy_grpc_connection` in Grafna
- Run test_recurring_job.py
- Observe grpc connection after test compleme and verufy value = 0

![Screenshot_20220715_135014](https://user-images.githubusercontent.com/73337386/179159577-daeadb6c-4518-469b-a997-259cbc69e3ec.png)
