### ISSUE TITLE
[TEST] Show longhorn version information for each regression test build

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#4124]
## What's the test to develop? Please describe

For each regression test build, `the version (commit id)` of `longhorn-manager` and `longhorn-engine` should be recorded and shown on somewhere for reference.

**Comment by innobead** [comment]
@yangchiu Please remember to add to the DevOps project next time :slightly_smiling_face: 

![image](https://user-images.githubusercontent.com/899492/174017212-3c8deaab-107a-481c-b190-5eb9f1959c4a.png)

**Comment by yangchiu** [comment]
same as https://github.com/longhorn/longhorn/issues/4204
close for duplicated
