### ISSUE TITLE
[Question] Specifying bytes-per-inodes ration in mkfs.ext4 options

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4129]
The default inodes number when mkfs.ext4 is done by longhorn is not matching with my needs. I have a lot of small files in my filesystem.

The documentation is talking about the mkfs-ext4-parameters (-O ) but not about the block size (-b ) or the bytes-per-inodes ratio (-i )

https://forums.rancher.com/t/specifying-bytes-per-inodes-ration-in-mkfs-ext4-options/38052

**Comment by joshimoo** [comment]
One should be able to specify arbitrary params, for the mkfs,ext4 binary invocation.
See the below code excerpts for additional information, 

REF: 
- https://github.com/longhorn/longhorn-manager/blob/3163c4508c672544658b6462e16fb1815485d78b/csi/node_server.go#L628
- https://github.com/longhorn/longhorn-manager/blob/3163c4508c672544658b6462e16fb1815485d78b/csi/util.go#L60

**Comment by R-Studio** [comment]
Unfortunately we are hitting the ext4 inodes limit and without the possibility to configure the inode_ration we are not able to use longhorn. 😢😭
I also changed  the `inode_ratio` in `/etc/mke2fs.conf` (under `[default]`), but no difference. I think longhorn has hardcoded the `inode_ratio`. 😔

**Comment by R-Studio** [comment]
We could minimize the issue, by using XFS instead of ext4. Maybe this helps someone.

**Comment by joshimoo** [comment]
@R-Studio did you try specifying the override for mkfs? then create a new PVC to check if it's correctly applied?
- https://github.com/longhorn/longhorn/issues/4129#issuecomment-1158466458
- https://longhorn.io/docs/1.3.0/references/settings/#custom-mkfsext4-parameters

the mkfs override isn't just for -o, please let us know if that solves your issue?
