### ISSUE TITLE
[IMPROVEMENT] Reduce read and write calls in liblonghorn (tgt <-> engine)

### ISSUE THREAD

**Issue by keithalucas** [longhorn/longhorn#4133]
## Is your improvement request related to a feature? Please describe

https://github.com/longhorn/longhorn/issues/4122 improves the reading and writing of longhorn messages in the longhorn-engine.  This issue aims to do something similar with liblonghorn.

## Describe the solution you'd like

Each field of the header of a longhorn message is individually read from and written to the unix domain socket.   We can assemble these fields in memory before writing and also read the fields as a block and extract the values.  This will reduce the amount of read and write system calls performed by liblonghorn when communicating with the longhorn-engine.  Also, we can investigate buffered I/O.   

Additionally, my change for https://github.com/longhorn/longhorn/issues/2206 in liblonghorn changed the timeout logic to timeout on the time between messages, but it continued to use the same `poll` and `timerfd` mechanism to do the timeout.   We can just used the timeout built into `poll` to determine the time between receiving any message.

**Comment by innobead** [comment]
cc @derekbit @joshimoo @shuo-wu

**Comment by innobead** [comment]
@derekbit will help with this. cc @keithalucas

**Comment by liyimeng** [comment]
Reading the code, it seem merge 6 write into a single one, should improve quite a bit. Do you have any benchmark number?

**Comment by innobead** [comment]
note: This will have less improvement when compared with https://github.com/longhorn/longhorn/issues/4122, and it just happens on the same host.

**Comment by derekbit** [comment]
I've run the performance benchmark.
The performance enhancement is mainly in read operations because the reused buffers.
Read IOPS is increased by 5% and bandwidth is increased by 2%.
As for the write operation, it's not enhanced in the ticket.

**Comment by innobead** [comment]
Decided to backport to 1.3.2 instead of 1.3.1, because we need more time for the testing. cc @derekbit

**Comment by innobead** [comment]
@derekbit is this ready for testing? all updated to longhorn-engine already?

**Comment by derekbit** [comment]
Yeah, read for testing. The PR in longhorn-engine is already merged.

**Comment by innobead** [comment]
Already finished.
