### ISSUE TITLE
[BUG] No new instance manager deployed on the node after v1.3.0 update if there are disks evicted 

### ISSUE THREAD

**Issue by jemand771** [longhorn/longhorn#4134]
## Describe the bug

After upgrading longhorn manager from v1.2.4 to v1.3.0, I tried to upgrade the engine image on my volumes as described in https://longhorn.io/docs/1.3.0/deploy/upgrade/
Those updates got "stuck" with a new replica being created but not started.
I've also noticed some other weird™ behaviour around the longhorn ui, and to me, it looks like the reason is that I'm missing an instance manager:
![image](https://user-images.githubusercontent.com/19669567/174409268-f0ba2c1a-1c19-4f6f-aa2f-51b305fb2e68.png)
I'd expect there to be at least one with the new version (20220611), but there isn't.

This also has some other side effects, e.g. when I click the backup tab, it shows me the error message in the longhorn ui
> failed to get engine client proxy: instance manager is in , not running state

## To Reproduce

I tried deploying the exact same v1.2.4 manifest I use in production to a test cluster and perform the upgrade there, again, using my v1.3.0 production manifest.
Sadly (?), everything worked correctly there and I couldn't reproduce it yet.
However, I'm not sure if this is a longhorn issue or related to my setup as I didn't touch any of the longhorn internals and it _should_ still work.

If this turns out to be a one-of-a-kind issue, I would be happy for any advice on how to fixup my current install to a regular, legal state (properly updated instance manager and everything that goes along with it)

## Expected behavior

Engine upgrade goes through successfully. This probably means that I'll have 3 instance managers for a short while (that's what I saw in my repro cluster)

## Log or Support bundle

There are *a lot* of logs. Some of those are about failing backups which might be unrelated (backups have been flaky for me in the past, but the issue is known (go's dns weirdness))
Here's a short snippet from the longhorn manager that I found interesting:
```
time="2022-06-17T22:31:10Z" level=warning msg="Error syncing Longhorn backup longhorn-system/backup-58eeb749e8bb40eb" controller=longhorn-backup error="longhorn-backup: fail to sync backup longhorn-system/backup-58eeb749e8bb40eb: failed to get engine client proxy:  instance manager is in , not running state" node=k3s-master-0
E0617 22:31:10.593036       1 volume_controller.go:216] fail to sync longhorn-system/pvc-f91e432a-950d-410c-9b9b-22ebe1d5bd92: fail to reconcile volume state for pvc-f91e432a-950d-410c-9b9b-22ebe1d5bd92: cannot find instance manager for replica pvc-f91e432a-950d-410c-9b9b-22ebe1d5bd92-r-8b1cb00a: cannot find the only available instance manager for instance pvc-f91e432a-950d-410c-9b9b-22ebe1d5bd92-r-8b1cb00a, node k3s-master-0, instance manager image longhornio/longhorn-instance-manager:v1_20220611, type replica
time="2022-06-17T22:31:10Z" level=warning msg="Dropping Longhorn volume longhorn-system/pvc-f91e432a-950d-410c-9b9b-22ebe1d5bd92 out of the queue" controller=longhorn-volume error="fail to sync longhorn-system/pvc-f91e432a-950d-410c-9b9b-22ebe1d5bd92: fail to reconcile volume state for pvc-f91e432a-950d-410c-9b9b-22ebe1d5bd92: cannot find instance manager for replica pvc-f91e432a-950d-410c-9b9b-22ebe1d5bd92-r-8b1cb00a: cannot find the only available instance manager for instance pvc-f91e432a-950d-410c-9b9b-22ebe1d5bd92-r-8b1cb00a, node k3s-master-0, instance manager image longhornio/longhorn-instance-manager:v1_20220611, type replica" node=k3s-master-0
E0617 22:31:10.593428       1 volume_controller.go:216] fail to sync longhorn-system/pvc-1bb36ccd-ae61-4851-bcb7-ff17d7358c08: fail to reconcile volume state for pvc-1bb36ccd-ae61-4851-bcb7-ff17d7358c08: cannot find instance manager for replica pvc-1bb36ccd-ae61-4851-bcb7-ff17d7358c08-r-04aaeaa3: cannot find the only available instance manager for instance pvc-1bb36ccd-ae61-4851-bcb7-ff17d7358c08-r-04aaeaa3, node k3s-master-0, instance manager image longhornio/longhorn-instance-manager:v1_20220611, type replica
E0617 22:31:10.593505       1 volume_controller.go:216] fail to sync longhorn-system/pvc-5a312624-be79-4c81-87c1-9fee008ccb36: fail to reconcile volume state for pvc-5a312624-be79-4c81-87c1-9fee008ccb36: cannot find instance manager for replica pvc-5a312624-be79-4c81-87c1-9fee008ccb36-r-94cdbcd1: cannot find the only available instance manager for instance pvc-5a312624-be79-4c81-87c1-9fee008ccb36-r-94cdbcd1, node k3s-master-0, instance manager image longhornio/longhorn-instance-manager:v1_20220611, type replica
E0617 22:31:10.595219       1 replica_controller.go:179] fail to sync replica for longhorn-system/pvc-efae068a-5d18-4eb8-8dc6-e827e334c794-r-61e6503f: failed to get instance manager for instance pvc-efae068a-5d18-4eb8-8dc6-e827e334c794-r-61e6503f: cannot find the only available instance manager for instance pvc-efae068a-5d18-4eb8-8dc6-e827e334c794-r-61e6503f, node k3s-master-0, instance manager image longhornio/longhorn-instance-manager:v1_20220611, type replica
time="2022-06-17T22:31:10Z" level=warning msg="Dropping Longhorn volume longhorn-system/pvc-1bb36ccd-ae61-4851-bcb7-ff17d7358c08 out of the queue" controller=longhorn-volume error="fail to sync longhorn-system/pvc-1bb36ccd-ae61-4851-bcb7-ff17d7358c08: fail to reconcile volume state for pvc-1bb36ccd-ae61-4851-bcb7-ff17d7358c08: cannot find instance manager for replica pvc-1bb36ccd-ae61-4851-bcb7-ff17d7358c08-r-04aaeaa3: cannot find the only available instance manager for instance pvc-1bb36ccd-ae61-4851-bcb7-ff17d7358c08-r-04aaeaa3, node k3s-master-0, instance manager image longhornio/longhorn-instance-manager:v1_20220611, type replica" node=k3s-master-0
time="2022-06-17T22:31:10Z" level=warning msg="syncBackupStatusWithSnapshotCreationTimeAndVolumeSize: couldn't find the snapshot backup-daily-c-651eedb0 in volume pvc-96836591-4725-461e-bf6e-e3ff776bee2e " controller=longhorn-backup node=k3s-master-0
time="2022-06-17T22:31:10Z" level=warning msg="syncBackupStatusWithSnapshotCreationTimeAndVolumeSize: couldn't find the snapshot backup-daily-c-f52dd30b in volume pvc-1abc39dc-2395-41d0-9dd5-ca41ef142f2d " controller=longhorn-backup node=k3s-master-0
time="2022-06-17T22:31:10Z" level=warning msg="Error syncing Longhorn backup longhorn-system/backup-df4f90caf93c46c7" controller=longhorn-backup error="longhorn-backup: fail to sync backup longhorn-system/backup-df4f90caf93c46c7: failed to get engine client proxy:  instance manager is in , not running state" node=k3s-master-0
time="2022-06-17T22:31:10Z" level=warning msg="Error syncing Longhorn backup longhorn-system/backup-f2614ad68d034fbf" controller=longhorn-backup error="longhorn-backup: fail to sync backup longhorn-system/backup-f2614ad68d034fbf: failed to get engine client proxy:  instance manager is in , not running state" node=k3s-master-0
```
This is repeated a lot, it looks like it's happening for each volume (which makes sense going from the reason I assumed above)

I've also noticed some lines like those on manager startup:
```
time="2022-06-17T22:44:01Z" level=warning msg="number of node disks 2 and collected disk info 0 are not equal"
time="2022-06-17T22:44:01Z" level=info msg="mismatching disks in node resource object and monitor collected data"
```
```
time="2022-06-17T22:44:01Z" level=warning msg="disk data {/mnt/disk1/ true false 0 []} is mismatched with collected data &{/mnt/disk1/ true 0xc0021e2600 f6fb0413-de8c-4e23-8a5e-be68ff1eae71 <nil> map[]} for disk disk-1"
```

From scrolling through the logs, those are the only "interesting" parts I could find. Nevertheless, I've attached a support bundle in case I've missed anything 
[longhorn-support-bundle_7bb6c93a-b585-4656-9515-b63f135bffec_2022-06-17T23-11-05Z.zip](https://github.com/longhorn/longhorn/files/8931712/longhorn-support-bundle_7bb6c93a-b585-4656-9515-b63f135bffec_2022-06-17T23-11-05Z.zip)

## Environment

 - Longhorn version: v1.3.0
 - Installation method: kubectl with only slight modifications:
   -  storageclass reclaimpolicy: retain
   - storageclass numberofreplicas: 1
   - longhorn manager: set env var GODEBUG="netdns=go"
   - driver deployer: set csi attacher, provisioner, resizer, and snapshotter replica counts to 1
 - Kubernetes distro and version: k3s version v1.22.7+k3s1 (8432d7f2)
   - Number of nodes in the cluster: 1 (shared management/worker)
 - Node config
   - OS type and version: ubuntu 22.04
   - CPU per node: 10
   - Memory per node: 40Gi
   - Disk type: nvme
   - Network bandwidth between the nodes: n/a (single-node)
 - Underlying Infrastructure: kvm via proxmox
 - Number of Longhorn volumes in the cluster: 21

disk setup: I've set the default disk to unschedulable and attached one (virtual) disk that's used only for longhorn.
It is mounted at /mnt/disk1 on the host and set up in longhorn accordingly.

I tried to reproduce the issue locally on a much smaller hyper-v vm, but I think the specific setup shouldn't matter

## Additional context

This is the part where the child starts admitting it ate all the candy.

The services on the production cluster aren't always needed, but "sometimes critical" (when they're needed).
When I initially did the upgrade and the engine upgrades didn't go through, I tried restarting the node. After it came back up, all volumes were either stuck attaching or detaching and nothing really seemed to work. no workloads could mount any longhorn volumes.
This is when I had to restore operations as quickly as possible due to an external request, so I tried reverting back to longhorn v1.2.4.
That fixed my issues and I was also able to switch the engine image back to v1.2.4. As far as I can see, the downgrade didn't have any significant impact. (my backup target got cleared in settings, but that was an easy fix)

While it's possible that the downgrade is related to my funky instance manager situation now, that doesn't explain why the upgrade failed back then (2 or 3 days ago). Since I don't have the logs from the upgrade anymore, I assume/hope the reason was the same.
I remember seeing the message about mismatching disk/node data, but that's about all.

Also, I tried deploying the v1.3.0 engine image and upgrading to that using longhorn manager v1.2.4, which worked. I know it's not the intended way, but technically I could upgrade all engine images to v1.3.0 using the old manager, then upgrade the rest of the longhorn components and pretend the issue doesn't exist.

I've seen the issues and docs page about remaining old instance managers, but this is kind of the opposite. I don't have the new instance manager that I think I should have.

**Comment by innobead** [comment]
cc @PhanLe1010 @c3y1huang

**Comment by jemand771** [comment]
minor additions that I either forgot or couldn't find when I opened the issue:
* I also get log messages like this one a lot. looks like they're printed for all volumes (I replaced spaces with newlines for easier reading)
```
time="2022-06-17T21:49:18Z"
level=error
msg="BUG: replica is running but storage IP is empty"
accessMode=rwo
controller=longhorn-volume
frontend=blockdev
migratable=false
node=k3s-master-0
owner=k3s-master-0
replica=pvc-5a312624-be79-4c81-87c1-9fee008ccb36-r-d507d810
state=attached
volume=pvc-5a312624-be79-4c81-87c1-9fee008ccb36
```
* my full upgrade path from installing longhorn to now is v1.2.3 -> v1.2.4 -> v1.3.0 -> v1.2.4 -> v1.3.0 (and a couple more iterations back and forth between v1.2.4 and v1.3.0)
* since I recognize some of your names and I've opened issues here in the past: This isn't the cluster with the broken network setup from before anymore. I haven't had any of the past issues on this cluster (running for about 2 months) and I think the networking is fine this time (ref: #3824)

**Comment by derekbit** [comment]
Can you **delete the evicted disk** or **disable the eviction disk**?
Related bug: https://github.com/longhorn/longhorn/issues/4143

**Comment by shuo-wu** [comment]
The below log is misleading:
```
time="2022-06-20T03:26:19Z" level=error msg="BUG: replica is running but storage IP is empty" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false n
```

It will be printed when the system containing volumes is upgraded to v1.3.0.

**Comment by innobead** [comment]
> The below log is misleading:
> 
> ```
> time="2022-06-20T03:26:19Z" level=error msg="BUG: replica is running but storage IP is empty" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false n
> ```
> 
> It will be printed when the system containing volumes is upgraded to v1.3.0.

the log level is wrong, @shuo-wu could you help with that improvement? @c3y1huang is out this week.

**Comment by shuo-wu** [comment]
Sure. Will create a separate ticket to track it.

**Comment by innobead** [comment]
@derekbit assigned this to you and also marked this as duplicated, because you already fixed this in https://github.com/longhorn/longhorn/issues/4143, but please also update the status of this issue afterward. Thanks.

**Comment by derekbit** [comment]
The bug is fixed in v1.3.1 (https://github.com/longhorn/longhorn/issues/4155) and master-head branch (https://github.com/longhorn/longhorn/issues/4143).

Before the v1.3.1 release, the temporary two workarounds are

1. Delete the evicted disk from the Longhorn node resource
Navigate to UI > Node page. Click the Edit node and disks and then delete the evicted disks from the node.

2. Disable the eviction of the disk from the Longhorn node resource
Navigate to UI > Node page. Click the Edit node and disks and then set the disk eviction to false.

**Comment by jemand771** [comment]
thanks for all the quick replies, just disabling eviction on the default disk did the trick :D
(no need to have eviction set anyway since the disk doesn't have scheduling disabled)
If you want to keep this issue open for tracking, feel free to do so - from my side this is resolved

**Comment by innobead** [comment]
Thanks, @jemand771 . Let's track the fix in https://github.com/longhorn/longhorn/issues/4143 instead.
