### ISSUE TITLE
[DOC] Document supported hardware architectures

### ISSUE THREAD

**Issue by zamazan4ik** [longhorn/longhorn#4135]
Hi!

Could you please put the information about supported architectures to the documentation please? E.e. about supported architectures for different operating systems, some specific requirements to the supported instructions, if you have any (e.g. maybe AVX is required - I do not know).

This kind of information is important for the end-users.

Thanks in advance!

**Comment by derekbit** [comment]
You can find the supported hardware and os information in Longhorn official document.

https://longhorn.io/docs/1.3.0/what-is-longhorn/
https://longhorn.io/docs/1.3.0/best-practices/

**Comment by zamazan4ik** [comment]
@derekbit Thank you a lot! Just a note from me. Maybe will be better to move/duplicate the information about supported architecture from "What is Longhorn" to "Best practices" page since "Best practices" page consists of different requirements to hardware/software. And an architecture fits good to this kind of information too.

**Comment by innobead** [comment]
@mantissahz Could you help with this update? Thanks.

**Comment by innobead** [comment]
The doc updated.
