### ISSUE TITLE
[IMPROVEMENT] Replace the GCC allocator in liblonghorn with a more efficient memory allocator

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4136]
## Is your improvement request related to a feature? Please describe

Replace the gcc allocator in liblonghorn with a more efficient memory allocator

## Describe the solution you'd like

The memory buffers are frequently allocated and freed in liblonghorn during sending and receiving requests. GCC's memory allocator is less efficient than other memory allocators such as [tcmalloc](https://github.com/google/tcmalloc), [jemalloc](https://github.com/jemalloc/jemalloc), [mimalloc](https://github.com/microsoft/mimalloc) and etc.

**Comment by shuo-wu** [comment]
Do you have a rough benchmark/estimation over the improvement after switching to `tcmalloc`?

**Comment by innobead** [comment]
We can just follow up on the e2e result to see if any outstanding impact for this introduction. 

@yangchiu Please verify this by running the benchmark pipeline to compare the result before and after introducing this memory allocator, tcmalloc. Close it afterward. Thanks.

**Comment by liyimeng** [comment]
> I did the test on Equinix m3.small.x86 machin. The read iops increases by 3%, and the read latency decreases by 10%.
> The value may differ in different platform.


What about write, any improvement?

**Comment by yangchiu** [comment]
**Test environment:**

machine: AWS c5d.2xlarge
test size: 80G
master-head longhorn-manager version: 70203d6

**Test Result:**

Bandwidth: KiB/s
Latency: ns

_(1) Replica count = 1_

  |   | IOPS |   | Bandwidth |   | Latency |  
-- | -- | -- | -- | -- | -- | -- | --
  |   | read | write | read | write | read | write
v1.3.0 | rand | 22,606 | 16,282 | 362,226 | 161,778 | 353,714 | 303,726
  | seq | 37,057 | 28,135 | 372,140 | 164,233 | 285,136 | 303,390
master-head | rand | 23,040 | 16,105 | 362,268 | 161,873 | 354,084 | 298,671
  | seq | 36,323 | 28,391 | 372,157 | 164,191 | 279,423 | 300,060
Improvement | rand | 1.92% | -1.09% | 0.01% | 0.06% | -0.1% | 1.66%
  | seq | -1.98% | 0.91% | 0% | -0.03% | 2% | 1.1%

_(2) Replica count = 2_

  |   | IOPS |   | Bandwidth |   | Latency |  
-- | -- | -- | -- | -- | -- | -- | --
  |   | read | write | read | write | read | write
v1.3.0 | rand | 21,139 | 14,010 | 741,368 | 161,961 | 521,577 | 537,988
  | seq | 33,339 | 24,269 | 442,312 | 164,405 | 506,907 | 505,782
master-head | rand | 22,744 | 14,136 | 722,910 | 161,967 | 459,487 | 532,098
  | seq | 36,966 | 20,655 | 563,698 | 164,393 | 461,432 | 511,503
Improvement | rand | 7.59% | 0.9% | -2.49% | 0% | 11.9% | 1.09%
  | seq | 10.88% | -14.89% | 27.44% | -0.01% | 8.97% | -1.13%

_(3) Replica count = 3_

  |   | IOPS |   | Bandwidth |   | Latency |  
-- | -- | -- | -- | -- | -- | -- | --
  |   | read | write | read | write | read | write
v1.3.0 | rand | 20,618 | 12,448 | 853,750 | 161,967 | 493,439 | 549,206
  | seq | 34,868 | 20,350 | 535,553 | 164,418 | 515,186 | 564,404
master-head | rand | 22,355 | 12,989 | 865,069 | 161,779 | 487,971 | 534,185
  | seq | 36,533 | 21,467 | 498,851 | 164,184 | 497,659 | 516,474
Improvement | rand | 8.42% | 4.35% | 1.33% | -0.12% | 1.11% | 2.74%
  | seq | 4.78% | 5.49% | -6.85% | -0.14% | 3.4% | 8.49%
