### ISSUE TITLE
[TEST] Volume Availability & Resilience: Volume corruption, read-only volume (SPOF engine <-> replicas)

### ISSUE THREAD

**Issue by rebeccazzzz** [longhorn/longhorn#4141]

**Comment by jingxu97** [comment]
@rebeccazzzz could you please share any plan related to this test improvement? We are interested in helping. Thank you!

**Comment by innobead** [comment]
@jingxu97 thanks for your interest, and we will have a new negative-testing plan in near future, so this will be covered later. Feel free to contribute to this later. 

cc @longhorn/qa
