### ISSUE TITLE
[BUG] Wrong nodeOrDiskEvicted collected in node monitor

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4143]
## Describe the bug

Wrong nodeOrDiskEvicted collected in node monitor.
https://github.com/longhorn/longhorn-manager/blob/master/controller/monitor/node_monitor.go#L135
The bug hinders the other tasks in the node monitor.

## To Reproduce

1. Add two disks in the longhorn node
2. Evict one of the disks
3. The log show
```
time="2022-06-17T22:44:01Z" level=warning msg="disk data {/mnt/disk1/ true false 0 []} is mismatched with collected data &{/mnt/disk1/ true 0xc0021e2600 f6fb0413-de8c-4e23-8a5e-be68ff1eae71 <nil> map[]} for disk disk-1"
```

## Expected behavior

No the related error message and node controller can finish its tasks sucessfully.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context
https://github.com/longhorn/longhorn/issues/4134

## Workaround
1. Delete the evicted disk from the Longhorn node resource
   Navigate to UI > Node page. Click the `Edit node and disks` and then delete the evicted disks from the node.

or

2. Disable the eviction of the disk from the Longhorn node resource
    Navigate to UI > Node page. Click the `Edit node and disks` and then set the disk eviction to false.

**Comment by innobead** [comment]
cc @longhorn/qa @shuo-wu

**Comment by shuo-wu** [comment]
Will this lead to the instance manager missing after the upgrade?

**Comment by derekbit** [comment]
It hinders the instance-manager sync.
https://github.com/longhorn/longhorn/issues/4134

**Comment by shuo-wu** [comment]
Yes. This is probably the root cause.

**Comment by innobead** [comment]
Don't we have disk eviction cases? if not, we need to add. cc @longhorn/qa

**Comment by derekbit** [comment]
Add e2e tests for the case for instance-manager sync if some of disks are evicted.

**Comment by innobead** [comment]
@derekbit In addition, please also update the workaround for users' reference as well. Thanks.

**Comment by derekbit** [comment]
> @derekbit In addition, please also update the workaround for users' reference as well. Thanks.

Workaround
https://github.com/longhorn/longhorn/issues/4143#issue-1276280630

**Comment by joshimoo** [comment]
@longhorn/maintainer  for V1.4  if we have time we should continue with more of the controller/monitor refactoring, so we can add unit tests for them.

This issue would have been caught during dev by a unit test, since we would have been able to add a comprehensive set of disk/node conditions for the tests, with very little effort once we have the initial refactoring/setup done.

That set of tests of the control plane should also help with reducing regressions, it also makes it easier to debug control plane code.

**Comment by yangchiu** [comment]
verified passed on master-head (longhorn-manager:ddf1b8d)

**Scenario I : fresh install master-head**
1. Install longhorn master-head
2. Create a statefulset with volumes to let every node have multiple replicas
3. Add a new disk to a node
4. For the node has 2 disks, set `Scheduling = False, Eviction Requested = True` for the old disk, and `Scheduling = True, Eviction Requested = False` for the new disk, to let replicas migrate from the old disk to the new disk
==> The migration can be done without problems. There are some logs shown in transient state but soon become quiet once the migration done:
`level=warning msg="disk data {/var/lib/longhorn/ false true 12432608870 []} is mismatched with collected data &{/var/lib/longhorn/ false 0xc0010b6780 32ad36be-83bd-4fb0-84ef-e6e573f41c9c <nil> map[]} for disk default-disk-e9ee3f25e482682"`
[longhorn-support-bundle_aa91ee1b-2848-473e-b299-46e2071338cb_2022-06-22T01-17-13Z.zip](https://github.com/longhorn/longhorn/files/8953984/longhorn-support-bundle_aa91ee1b-2848-473e-b299-46e2071338cb_2022-06-22T01-17-13Z.zip)

**Scenario II: on v1.2.4, leave a disk with Scheduling = False, Eviction Requested = True, and then upgrade to master-head**
1. Install longhorn v1.2.4
2. Create a statefulset with volumes to let every node have multiple replicas
3. Add a new disk to a node
4. For the node has 2 disks, set `Scheduling = False, Eviction Requested = True` for the old disk, and `Scheduling = True, Eviction Requested = False` for the new disk, to let replicas migrate from the old disk to the new disk
5. Keep the old disk `Scheduling = False, Eviction Requested = True`, and then upgrade to longhorn-manager to master-head, and then upgrade every volume's longhorn-engine to master-head
==> The upgrade can be done without problems, and there's no `level=warning msg="disk data {/mnt/disk1/ true false 0 []}` log shown in longhorn-manager
