### ISSUE TITLE
[BUG] Misleading log "BUG: replica is running but storage IP is empty"

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4153]
## Describe the bug

The below log is misleading:
```
time="2022-06-20T03:26:19Z" level=error msg="BUG: replica is running but storage IP is empty" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false n
```

It will be printed when the system containing volumes is upgraded to v1.3.0.

## To Reproduce

1. Deploy Longhorn v1.2.x
2. Create one volume
3. Upgrade Longhorn to v1.3.0
4. Check the longhorn manager pod logs and search the error message `BUG: replica is running but storage IP is empty`

## Expected behavior

There should not be this kind of logs

## Log or Support bundle

```
time="2022-06-20T03:26:19Z" level=error msg="BUG: replica is running but storage IP is empty" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false n
```

## Environment

 - Longhorn version: v1.2.x -> v1.3.0

## Additional context

This is reported in https://github.com/longhorn/longhorn/issues/4134

**Comment by cchien816** [comment]
Hi @shuo-wu ,

I tested with master-head, after upgrade LH from v1.2.4 to master-head, got log below
```
time="2022-06-21T04:15:32Z" level=debug msg="Replica is running but storage IP is empty, need to wait for update" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=worker4 owner=worker4 replica=vol2-r-79603e7a state=attached volume=vol
```
The content still present but log level changed from `error` to `debug`, reference to this [PR](https://github.com/longhorn/longhorn-manager/commit/801c85df00f0d7eebb3d9114b87a1ece4801ef73), I think this is correct behavior?

If it's OK I'll close thsi issue, thank you

**Comment by shuo-wu** [comment]
This message is the correct one. I can close this now.

**Comment by innobead** [comment]
@cchien816 We need to verify on 1.3.x as well. Please create a backport issue for that. Thanks.

**Comment by shuo-wu** [comment]
@innobead The backported issue ticket is already there: https://github.com/longhorn/longhorn/issues/4156
