### ISSUE TITLE
[FEATURE] S3/Object Gateway Support - Experimental

### ISSUE THREAD

**Issue by rebeccazzzz** [longhorn/longhorn#4154]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Longhorn will support provisioning and managing s3 object gateways over longhorn volume to become an opinionated storage solution for having block/fs/object interface/protocol support.  

## Describe the solution you'd like

Support vendor-neutral S3 backend integration based on COSI protocol, https://github.com/kubernetes-sigs/container-object-storage-interface-api/tree/v0.1.0/crds  (v1alpha1 has been released), so it's good for experimental integration.

The scope of COSI is only for bucket management, so for longhorn built in S3 backend, we need to have S3 instance management, bucket credentials management, etc. 

## Additional context

https://aquarist-labs.io/s3gw/
https://github.com/kubernetes/enhancements/pull/1383

**Comment by mathieudruart** [comment]
does this feature could be related to this project ? : https://aquarist-labs.io/s3gw/

**Comment by innobead** [comment]
> does this feature could be related to this project ? : https://aquarist-labs.io/s3gw/

Have u used that project? Any feedback?

**Comment by mathieudruart** [comment]
> > does this feature could be related to this project ? : https://aquarist-labs.io/s3gw/
> 
> Have u used that project? Any feedback?

Not yet, but we are planning to test it (not in production).

We already use Longhorn volumes for most of our PV/PVC and we are really interested for an S3 gateway on top of Longhorn. We found this feature request here and that existing project (that seems to use Ceph S3 gateway capabilities on top of Longhorn volumes), and we were just wondering if this project could not cover the need for this feature ?

**Comment by innobead** [comment]
Thanks for the info :+1: . Yes, it would be a choice for our object backend.
