### ISSUE TITLE
[BACKPORT][v1.3.1][BUG] [BUG] Wrong nodeOrDiskEvicted collected in node monitor

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4155]
## Describe the bug

https://github.com/longhorn/longhorn/issues/4143

## To Reproduce

3. Perform '....'

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by yangchiu** [comment]
verified passed on v1.3.x-head (longhorn-manager:90b5004)

**Scenario I : fresh install v1.3.x-head**
1. Install longhorn v1.3.x-head
2. Create a statefulset with volumes to let every node have multiple replicas
3. Add a new disk to a node
4. For the node has 2 disks, set `Scheduling = False, Eviction Requested = True` for the old disk, and `Scheduling = True, Eviction Requested = False` for the new disk, to let replicas migrate from the old disk to the new disk
==> The migration can be done without problems. There are some logs shown in transient state but soon become quiet once the migration done:
`level=warning msg="disk data {/var/lib/longhorn/ false true 12432608870 []} is mismatched with collected data &{/var/lib/longhorn/ false 0xc0010b6780 32ad36be-83bd-4fb0-84ef-e6e573f41c9c <nil> map[]} for disk default-disk-e9ee3f25e482682"`
[longhorn-support-bundle_7e6189a4-7664-4912-80e3-ad4e8178417a_2022-06-22T01-40-26Z.zip](https://github.com/longhorn/longhorn/files/8953995/longhorn-support-bundle_7e6189a4-7664-4912-80e3-ad4e8178417a_2022-06-22T01-40-26Z.zip)

**Scenario II: on v1.2.4, leave a disk with Scheduling = False, Eviction Requested = True, and then upgrade to v1.3.x-head**
1. Install longhorn v1.2.4
2. Create a statefulset with volumes to let every node have multiple replicas
3. Add a new disk to a node
4. For the node has 2 disks, set `Scheduling = False, Eviction Requested = True` for the old disk, and `Scheduling = True, Eviction Requested = False` for the new disk, to let replicas migrate from the old disk to the new disk
5. Keep the old disk `Scheduling = False, Eviction Requested = True`, and then upgrade to longhorn-manager to v1.3.x-head, and then upgrade every volume's longhorn-engine to v1.3.x-head
==> The upgrade can be done without problems, and there's no `level=warning msg="disk data {/mnt/disk1/ true false 0 []}` log shown in longhorn-manager
