### ISSUE TITLE
[BUG][BACKPORT][v1.3.x] Misleading log "BUG: replica is running but storage IP is empty"

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4156]
## Describe the bug

https://github.com/longhorn/longhorn/issues/4153

**Comment by cchien816** [comment]
**Verified on v1.3.x-head
Result Pass**
[Steps](https://github.com/longhorn/longhorn/issues/4153#issue-1276314288)

After upgrade LH from v1.2.4 to v1.3.x-head, can get correct level log(debug) in longhorn-manager pod as below shown
```
kubectl logs longhorn-manager-vcg2p -n longhorn-system | grep "Replica is running but storage IP"
time="2022-06-21T05:01:42Z" level=debug msg="Replica is running but storage IP is empty, need to wait for update" accessMode=rwo contro
```
