### ISSUE TITLE
[DOC] Update the doc of volume size after introducing snapshot prune

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4158]
## What's the task? Please describe

We have https://longhorn.io/docs/1.3.0/volumes-and-nodes/volume-size/#space-configuration-suggestions-for-volumes, but the current formula does not include the required space of the volume head, and furthermore, it does not consider different use cases like below.

a volume
- with a recurring job + n snapshots
- without a recurring job + n snapshots
- w/o a recurring job + 0 snapshots (especially for snapshot prune)
- some other extreme corner cases. 

Users usually will ask what space a volume requires when planning the storage for Longhorn, so we need to update the doc w/ more info for reference. 

## Describe the items of the task (DoD, definition of done) you'd like

- [ ] Update the current doc

## Additional context

cc @longhorn/dev

**Comment by shuo-wu** [comment]
Test is not required for the doc update ticket
