### ISSUE TITLE
[TASK] Automate issue management via issue status/attribution update

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4159]
## What's the task? Please describe

Automatically manage issues when some Github events happen as below tasks. 

Now, we have a longhorn bot integration but would suggest leveraging Github action to achieve the goals below. 
- https://github.com/longhorn/bot (you probably can still use the bot as a lib but the trigger point will be from Github action)
- https://docs.github.com/en/actions/managing-issues-and-pull-requests/using-github-actions-for-project-management

## Describe the items of the task (DoD, definition of done) you'd like

- [x] Create a backport issue when the source issues have `backport-needed/x.x.x` label
- [x] Create a test issue from the original issue when having `require/automation-e2e`
- [x] Add corresponding milestone to issues and create a new milestone on the Github if it doesn't exist
- [x] Add issues with a milestone to the corresponding Zenhub release (create a new release on the Zenhub board if it doesn't exist)
- [x] Close the previously automatically created issues when the related labels are removed from the source issues,

cc @longhorn/qa @longhorn/dev

**Comment by yangchiu** [comment]
Able to create backport/automation issues according to added labels.
Investigate how to add `milestone` now.

**Comment by yangchiu** [comment]
For a backport issue like `[BACKPORT][v1.2.5]`, the `v1.2.5` milestone needs to be added to this backport issue, but the creating new issue action only accept passing `milestone id` instead of `milestone name`, which means we need to get `milestone id` from `milestone name` and then use the returned `milestone id` to create new issue.
Currently there's [no existing action](https://github.com/marketplace?type=actions&query=milestone+) can let us get `milestone id` from `milestone name`, probably need to implement a new action by ourselves.

**Comment by yangchiu** [comment]
[Custom milestone action](https://github.com/yangchiu/milestone-action) in progress, but it seems useless. The `milestone` field in an issue is not related to Zenhub `release`.

Need a separate functionality to create new Zenhub release / add issues to a Zenhub release, which is out of the scope of github API. Investigate if it's possible to use Zenhub API and integrate it with Github Actions.

**Comment by yangchiu** [comment]
https://github.com/yangchiu/add-zenhub-release-action

Implemented custom action to add an issue to Zenhub release. If the release doesn't exist, it would be created automatically first and then add the issue to the created release.

But somehow [add an issue to a release](https://github.com/ZenHubIO/API#add-or-remove-issues-to-or-from-a-release-report) not working, the API returns the correct response
```
{
    "added": [
        {
            "repo_id": 462160322,
            "issue_number": 1359774406
        }
    ],
    "removed": []
}
```
, but the issue is actually not added to the release. More investigation needed.

**Comment by innobead** [comment]
> [yangchiu/add-zenhub-release-action](https://github.com/yangchiu/add-zenhub-release-action)
> 
> Implemented custom action to add an issue to Zenhub release. If the release doesn't exist, it would be created automatically first and then add the issue to the created release.
> 
> But somehow [add an issue to a release](https://github.com/ZenHubIO/API#add-or-remove-issues-to-or-from-a-release-report) not working, the API returns the correct response
> 
> ```
> {
>     "added": [
>         {
>             "repo_id": 462160322,
>             "issue_number": 1359774406
>         }
>     ],
>     "removed": []
> }
> ```
> 
> , but the issue is actually not added to the release. More investigation needed.

Suggest using longhorn/bot as a library for everything including any new action.

**Comment by yangchiu** [comment]
Even though directly use code from https://github.com/harvester/bot/blob/harvester/github-bot/harvester_github_bot/zenhub.py to test, still unable to add an issue to a release. 
Have checked with Chris He, this part works in Harvester bot. 
Need more time to figure out what's the difference...
```
if __name__ == '__main__':
    zenhub = Zenhub(ZENHUB_TOKEN)
    repo_id = 88298561 # from curl https://api.github.com/repos/longhorn/longhorn
    issue_number = 1355213447 # from curl https://api.github.com/repos/longhorn/longhorn/issues
    release_id, err = zenhub.get_release_id_by_version(repo_id, '1.4.0')
    print(release_id)
    res = zenhub.add_release_to_issue(repo_id, release_id, issue_number)
    print(res) # 200 OK, but the issue isn't added to release
```

**Comment by yangchiu** [comment]
> Even though directly use code from https://github.com/harvester/bot/blob/harvester/github-bot/harvester_github_bot/zenhub.py to test, and use token from David, still unable to add an issue to a release. Have checked with Chris He, this part works in Harvester bot. Need more time to figure out what's the difference...
> 
> ```
> if __name__ == '__main__':
>     zenhub = Zenhub(ZENHUB_TOKEN)
>     repo_id = 88298561 # from curl https://api.github.com/repos/longhorn/longhorn
>     issue_number = 1355213447 # from curl https://api.github.com/repos/longhorn/longhorn/issues
>     release_id, err = zenhub.get_release_id_by_version(repo_id, '1.4.0')
>     print(release_id)
>     res = zenhub.add_release_to_issue(repo_id, release_id, issue_number)
>     print(res) # 200 OK, but the issue isn't added to release
> ```

The issue_number is wrong. No need to get issue id from github api, just pass the literal issue number (for example, this issue's issue_number is 4159)

**Comment by yangchiu** [comment]
Reopen because need to implement "create a new milestone on the Github if it doesn't exist".
