### ISSUE TITLE
[BUG] longhorn-manager cannot start while upgrading if the configmap contains volume sensitive settings

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4160]
## Describe the bug

longhorn-manager cannot start while upgrading if the configmap contains volume sensitive settings

## To Reproduce

1. Fresh install v1.2.x with one of the settings
    - taint-toleration: ...
    - default-longhorn-static-storage-class: ...
    - system-managed-components-node-selector: ...
2. Create a volume and attach it to one node.
3. Upgrade v1.3.0 with one of the settings
    - taint-toleration: ...
    - default-longhorn-static-storage-class: ...
    - system-managed-components-node-selector: ...
4. longhorn-manager cannot start successfully and shows similar error like
    ```
    fail to set the setting taint-toleration ....
    ```
## Expected behavior

 longhorn-manager can start successfully

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Workaround
Remove the volume sensitive settings from the configmap
1. Edit the configmap `longhorn-default-setting`
`kubectl -n longhorn-system edit configmap longhorn-default-setting`
For example, 
```
...
data:
    default-setting.yaml: |-
    default-replica-count: 5
    taint-toleration: xyz.io/drain:NoSchedule
...
```
2. Remove `taint-toleration: xyz.io/drain:NoSchedule` and becomes
```
...
data:
    default-setting.yaml: |-
    default-replica-count: 5
...
```

3. Then save the configmap. Wait for a while, the longhorn-manager should start successfully

**Comment by cchien816** [comment]
**Verified on longhorn master head `1e8dd33`
Result Pass
Test [step](https://github.com/longhorn/longhorn/issues/4160#issue-1277807172)**

1. Can reproduce on v1.3.0
2. Longhorn can successfully upgrade from v1.2.x to master-head when `taint-toleration` was in `longhorn-default-setting`, no CrashLookbackOff observed from longhorn-manager
