### ISSUE TITLE
[BACKPORT][v1.2.5][BUG] longhorn-manager cannot start while upgrading if the configmap contains volume sensitive settings

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4163]
## Describe the bug

https://github.com/longhorn/longhorn/issues/4160

## To Reproduce

3. Perform '....'

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by cchien816** [comment]
**Verified on longhorn v1.2.x head 0ed376
Result Pass
Test [step](https://github.com/longhorn/longhorn/issues/4160#issue-1277807172)** 

Upgrade from v1.2.4 to v1.2.x head
Longhorn can successfully upgrade from v1.2.4 to v1.2.x-head when taint-toleration was in longhorn-default-setting, no CrashLookbackOff observed from longhorn-manager
