### ISSUE TITLE
[BACKPORT][v1.3.1][IMPROVEMENT] Reduce syscalls while reading and writing requests in longhorn-engine

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4169]
## Is your improvement request related to a feature? Please describe

https://github.com/longhorn/longhorn/issues/4122

**Comment by yangchiu** [comment]
**Test environment:**

machine: Equinix c3.small.x86
test size: 30G
v1.3.x-head longhorn-engine version: 4b37b4e

**Test Result:**

Bandwidth: KiB/s
Latency: ns

_(1) Replica count = 1_

  |   | IOPS |   | Bandwidth |   | Latency |  
-- | -- | -- | -- | -- | -- | -- | --
  |   | read | write | read | write | read | write
v1.3.0 | rand | 32,164 | 18,584 | 423,947 | 409,271 | 282,990 | 224,490
  | seq | 39,463 | 32,541 | 451,389 | 421,626 | 195,191 | 222,631
v1.3.x-head | rand | 32,321 | 18,900 | 422,329 | 402,893 | 280,051 | 220,118
  | seq | 39,858 | 33,153 | 450,913 | 417,993 | 192,458 | 220,072
Improvement | rand | 0.49% | 1.7% | -0.38% | -1.56% | 1.04% | 1.95%
  | seq | 1% | 1.88% | -0.11% | -0.86% | 1.4% | 1.15%

_(2) Replica count = 2_

  |   | IOPS |   | Bandwidth |   | Latency |  
-- | -- | -- | -- | -- | -- | -- | --
  |   | read | write | read | write | read | write
v1.3.0 | rand | 31,767 | 15,787 | 761,217 | 387,755 | 1,779,601 | 281,369
  | seq | 51,695 | 28,797 | 846,924 | 319,201 | 1,800,719 | 281,594
v1.3.x-head | rand | 33,200 | 15,826 | 763,925 | 385,508 | 1,724,051 | 609,781
  | seq | 52,172 | 29,141 | 846,631 | 311,104 | 1,603,614 | 319,162
Improvement | rand | 4.51% | 0.25% | 0.36% | -0.58% | 3.12% | -116.72%
  | seq | 0.92% | 1.19% | -0.03% | -2.54% | 10.95% | -13.34%

_(3) Replica count = 3_

  |   | IOPS |   | Bandwidth |   | Latency |  
-- | -- | -- | -- | -- | -- | -- | --
  |   | read | write | read | write | read | write
v1.3.0 | rand | 33,775 | 14,788 | 957,202 | 382,969 | 1,889,051 | 1,583,129
  | seq | 57,633 | 27,533 | 1,091,980 | 279,380 | 1,956,132 | 1,871,978
v1.3.x-head | rand | 33,471 | 15,467 | 952,345 | 376,135 | 1,829,784 | 502,484
  | seq | 56,045 | 27,330 | 1,088,035 | 281,299 | 1,859,578 | 739,770
Improvement | rand | -0.9% | 4.59% | -0.51% | -1.78% | 3.14% | 68.26%
  | seq | -2.76% | -0.74% | -0.36% | 0.69% | 4.94% | 60.48%
