### ISSUE TITLE
[TASK] Replace jobq lib with an alternative way for listing remote backup volumes and info

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4176]
## What's the task? Please describe

For now, we are using `github.com/honestbee/jobq` for queries backup volumes & each backup info, but that lib lacks an OSS license. So, we need to look for an alternative solution. 

## Describe the items of the task (DoD, definition of done) you'd like

Use https://github.com/gammazero/workerpool or similar.

## Additional context

N/A

**Comment by innobead** [comment]
This is about lib replacement, so we just need to make sure all e2e backup/restore/DR tests passed w/o issues, then can close this issue.

cc @longhorn/qa

**Comment by chriscchien** [comment]
Close this ticket for we did not see outstanding errors happening in e2e backup/restore/DR test cases
- [sles](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/test_results_analyzer/)
- [ubuntu](https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/test_results_analyzer/)
- [sle-micro](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/amd64/job/longhorn-tests-sle-micro-amd64/4/#showFailuresLink)
- [rocky-linux](https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/amd64/job/longhorn-tests-rockylinux-amd64/test_results_analyzer/)
- [rhel](https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/test_results_analyzer/)
- [oracle](https://ci.longhorn.io/job/public/job/master/job/oracle/job/amd64/job/longhorn-tests-oracle-amd64/14/testReport/)
- [centos](https://ci.longhorn.io/job/public/job/master/job/centos/job/amd64/job/longhorn-tests-centos-amd64/test_results_analyzer/)
