### ISSUE TITLE
[IMPROVEMENT] Purging a volume before rebuilding starts

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4183]
## Is your improvement request related to a feature? Please describe

If we can do snapshot purge before rebuilding, we would eliminate 1x space used by the system snapshots for the case we mentioned in https://longhorn.io/docs/1.3.0/volumes-and-nodes/volume-size/#space-configuration-suggestions-for-volumes

## Describe the solution you'd like

Before creating the system snapshot for the rebuilding replica, volume should do snapshot purge automatically

## Additional context

Some users/customers are complaining about the extra space used by Longhorn volumes in the worst case, this improvement would help reduce the overhead.

**Comment by innobead** [comment]
@shuo-wu any risk to backport to 1.2?

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 70203d6) by manually executing [the test steps](https://github.com/longhorn/longhorn-tests/pull/1017/files).
