### ISSUE TITLE
[BUG] Cannot create mount directory on NFS backup server if directory already exists

### ISSUE THREAD

**Issue by kclejeune** [longhorn/longhorn#4187]
## Describe the bug

I'm running several scheduled backups against an NFS server. These backups appear to be working and they show up correctly in the backups tab, but a toast pops up with an error:
```
error listing backup volume names: Failed to execute: /var/lib/longhorn/engine-binaries/rancher-mirrored-longhornio-longhorn-engine-v1.2.4/longhorn [backup ls --volume-only nfs://server.company.com:/data2/backups/k8s], output Cannot create mount directory /var/lib/longhorn-backupstore-mounts/server_company_com/data2/backups/k8s for NFS server: mkdir /var/lib/longhorn-backupstore-mounts/server_company_com/data2/backups/k8s: file exists , stderr, time="2022-06-29T12:46:55Z" level=error msg="Cannot create mount directory /var/lib/longhorn-backupstore-mounts/server_company_com/data2/backups/k8s for NFS server: mkdir /var/lib/longhorn-backupstore-mounts/server_company_com/data2/backups/k8s: file exists" , error exit status 1
```

## To Reproduce

1. Make a backup
2. Click on the backups tab
3. See error

## Expected behavior

The same thing but...without the error?

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.2.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): rancher catalog
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2 v1.23.7+rke2r2
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 6
 - Node config
   - OS type and version: RHEL 8
   - CPU per node: 64
   - Memory per node: 128G
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: at least 1GiB
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare on prem
 - Number of Longhorn volumes in the cluster: 11

## Additional context

n/a

**Comment by mantissahz** [comment]
@kclejeune Could you please also check about nfs server configuration for the sharing IP range, and all longhorn working nodes in the sharing IP range?

**Comment by kclejeune** [comment]
> @kclejeune Could you please also check about nfs server configuration for the sharing IP range, and all longhorn working nodes in the sharing IP range?

Yes, but it's not actually my NFS server, so I'm trying to track down that info. I'll send an update when I hear back with more info. Thanks!

**Comment by mantissahz** [comment]
@kclejeune could you please try to kill the longhorn-manager pods then see if a toast pops up with this error again?

**Comment by kclejeune** [comment]
Just following up on this -

> @kclejeune Could you please also check about nfs server configuration for the sharing IP range, and all longhorn working nodes in the sharing IP range?
Still don't have this info yet, sorry

> @kclejeune could you please try to kill the longhorn-manager pods then see if a toast pops up with this error again?

I redeployed the longhorn-manager deployment to kill all of the pods and it appears to have the same issue.

> ref issue: [issue 2242](https://github.com/longhorn/longhorn/issues/2242) @kclejeune If you want test you can kubectl exec into the longhorn-manager pod where the backup fails and try to rm -rf /var/lib/longhorn-backupstore-mounts/server_company_com/data2/backups/k8s manually. Could you please send us a support bundle to [longhorn-support-bundle@Suse.com](mailto:longhorn-support-bundle@Suse.com) so we can take a look at your Longhorn deployment configuration?

Tried manually removing the backup directory:

```
root@instance-manager-r-fcce647d:/# rm -rf /var/lib/longhorn-backupstore-mounts/backup_company_com/data2/backups/k8s 
rm: cannot remove '/var/lib/longhorn-backupstore-mounts/backup_company_com/data2/backups/k8s': Is a directory

root@instance-manager-r-fcce647d:/var/lib/longhorn-backupstore-mounts/backup_company_com/data2/backups# ls
ls: cannot access 'k8s': Stale file handle
k8s
```

I'm working under some security requirements so I'm not sure if I'm permitted to send the support bundle. I'll look through it to check if I need to scrub anything. Thanks for your help so far.

**Comment by mantissahz** [comment]
@kclejeune Did you also restart the instance-manager?

**Comment by Dudoleitor** [comment]
Hi, I'm having a similar issue.
In my cluster there is no way to have longhorn create backups: a snapshot is created but the backup is not. I tried to manually create a backup for a volume, running a cronjob from kubernetes and even waiting for a recurring job to happen but the result is the same.

In my case the problem appeared after updating the engine image to v1.3.0 from v1.2.4 (could be a coincidence though), backups were working before.

In the logs I have the same error message, which appears multiple times:
`mkdir /var/lib/longhorn-backupstore-mounts/nfs-server-redacted/k3s-cluster/longhorn-backup: file exists"`

If I try to access the folder manually (by opening a shell inside a longhorn-manager pod) I can successfully access the folder and create files inside it.

I re-deployed everything in the longhorn namespace (deployments and daemonsets) but the issue is still there. I tried to empty the destination folder (to avoid potential conflicts) but nothing changed.

**Comment by kclejeune** [comment]
> @kclejeune Did you also restart the instance-manager?

Yes, I redeployed all of the longhorn resources I could find and so far the issue is persisting.

**Comment by mantissahz** [comment]
@Dudoleitor Could you try to stop the cronjob and remove backup target temporarily then delete this /var/lib/longhorn-backupstore-mounts/nfs-server-redacted/k3s-cluster/longhorn-backup and re-depoly the pods, last add the backup target back and see if this situation happened again?
That would be great if there is the support bundle you could provide.
Thanks.

**Comment by kclejeune** [comment]
@mantissahz I've sent the support bundle - thanks for your patience!

**Comment by kclejeune** [comment]
Hi all - it seems like this was an NFS issue that didn't appear until trying to export the volume. Closing this since the issue has subsided. Thanks!
