### ISSUE TITLE
[TASK] Update CSI sidecar versions

### ISSUE THREAD

**Issue by luca-heitmann** [longhorn/longhorn#4189]
## What's the task? Please describe

Update the CSI sidecar images to their latest versions:

https://github.com/longhorn/longhorn/blob/fe5565dbcf30d26232a4ce9dfff43cc3fc7460e5/chart/values.yaml#L31-L43

## Describe the items of the task (DoD, definition of done) you'd like

- [ ] [attacher](https://github.com/kubernetes-csi/external-attacher/releases) (v3.4.0 -> v3.5.0)
- [ ] [provisioner](https://github.com/kubernetes-csi/external-provisioner) (v2.1.2 -> v3.2.1)
- [ ] [nodeDriverRegistrar](https://github.com/kubernetes-csi/node-driver-registrar/releases) (v2.5.0 -> v2.5.1)
- [ ] [resizer](https://github.com/kubernetes-csi/external-resizer/releases) (v1.2.0 -> v1.5.0)
- [ ] [snapshotter](https://github.com/kubernetes-csi/external-snapshotter/releases) (v3.0.3 -> v6.0.1)

## Additional context

I noticed it, when I tried to backup/restore Longhorn PVs with the Velero CSI plugin. This was not possible, because the restored PVC had only the "volume.kubernetes.io/storage-provisioner=driver.longhorn.io" annotation, but not "volume.**beta**.kubernetes.io/storage-provisioner=driver.longhorn.io". Support for the newer annotation was introduced in [this commit](https://github.com/kubernetes-csi/external-provisioner/commit/731e1cd5c76d87f430574207cf75a444881e61f7) respective v3.1.0 of the external-provisioner sidecar.

**Comment by mantissahz** [comment]
Hi @luca-heitmann,
Thanks for CSI updating information.
You could modify the repository(like k8s.gcr.io/sig-storage/csi-snapshotter) and tag you showed in chart/value.yaml or [here longhorn.yaml](https://github.com/longhorn/longhorn/blob/master/deploy/longhorn.yaml#L3582-L3591) to fit the version you need.

**Comment by innobead** [comment]
https://github.com/kubernetes/kubernetes/pull/104590

**Comment by luca-heitmann** [comment]
Hi, I was able to fix my problem by making a change in the Velero CSI plugin ([here](https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/115)). If both annotations are removed when restoring a backup, it also works (Kubernetes reattaches both annotations, Longhorn finds the beta annotation and provision the volume -> all good).

Nevertheless, I think it makes sense that current versions of the CSI plugin are used. Since I couldn't find a task for this, I created one.

K8s: v1.23.8+k3s2
Longhorn: v1.3.0
Velero CSI Plugin: velero-plugin-for-csi:v0.3.0

**Comment by innobead** [comment]
> Hi, I was able to fix my problem by making a change in the Velero CSI plugin ([here](https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/115)). If both annotations are removed when restoring a backup, it also works (Kubernetes reattaches both annotations, Longhorn finds the beta annotation and provision the volume -> all good).
> 
> 
> 
> Nevertheless, I think it makes sense that current versions of the CSI plugin are used. Since I couldn't find a task for this, I created one.
> 
> 
> 
> K8s: v1.23.8+k3s2
> 
> Longhorn: v1.3.0
> 
> Velero CSI Plugin: velero-plugin-for-csi:v0.3.0
> 
> 

Thanks @luca-heitmann . I believe Velero plug-in needs to ensure those annotations removed for the compatibility because the beta annotation is deprecated but not removed yet. Your fix looks good.

For longhorn, we will do the update in the next feature release 1.4.0, so the sidecars will be updated accordingly. Let's keep this issue open.

**Comment by innobead** [comment]
This will be resolved at https://github.com/longhorn/longhorn/issues/4239.
