### ISSUE TITLE
[QUESTION]  unable to create snapshots/backups using CSI 

### ISSUE THREAD

**Issue by rajeevpnair** [longhorn/longhorn#4190]
## Question
>   unable to create snapshots/backups using CSI 

## Environment

 - Longhorn version: 1.30
 - Kubernetes version: 1.22
 - Node config
   - OS type and version: redhat 8.4
   - CPU per node: 4
   - Memory per node: 8Gb
   - Disk type ext4
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

## Additional context

Unable to create CSI snapshots by following the official documentation , the readytouse field is never becomes true

steps followed: 
1. installed kuberentes 1.22
2. installed longhorn using https://staging--longhornio.netlify.app/docs/1.0.2/deploy/install/install-with-helm/
3. created a pvc and a pod attached to the pvc
4. installed the snapshot CRDs using https://longhorn.io/docs/1.2.4/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/ 
5. added a volumesnapshotclass as below.

kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn
driver: driver.longhorn.io
deletionPolicy: Delete

6. create a snapshot file as below.
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snap1
spec:
  volumeSnapshotClassName: longhorn
  source:
    persistentVolumeClaimName: test-pvc

when i describe the volumesnapshots, getting the below details.

  Bound Volume Snapshot Content Name:  snapcontent-7335d0fe-4c43-41e8-bca0-3379fde66241
  **Ready To Use:                        false**
Events:
  Type    Reason            Age   From                 Message
  **Normal  CreatingSnapshot  59s   snapshot-controller  Waiting for a snapshot default/snap1 to be created by the CSI driver.**

Note i have already added a external nfs backup target as below 

[root@devcpu04 eic]# kubectl get backuptargets.longhorn.io -n longhorn-system
NAME      URL                                    CREDENTIAL   LASTBACKUPAT   AVAILABLE   LASTSYNCEDAT
default   nfs://192.168.168.82:/tmp/nfs_shares                5m0s           true        2022-06-30T07:18:36Z
[root@devcpu04 eic]#

somebody please help with this issue or the latest documentation ?

**Comment by mantissahz** [comment]
@rajeevpnair Could you please provide the support bundle?
You could find the latest documents at [https://longhorn.io/docs/1.3.0/](https://longhorn.io/docs/1.3.0/).

**Comment by rajeevpnair** [comment]
@mantissahz Please find the attached bundle , I am referring  the latest documentation of longhorn,

Longhorn version: 1.3.0
Installation method: helm
Number of management node in the cluster: 1
Number of worker node in the cluster: 1
Node config
OS type and version: Red Hat Enterprise Linux Server 8.4
CPU per node: 4
Memory per node: 8GB
Disk type(e.g. SSD/NVMe): (Unsure, but can gather this info if needed)
Network bandwidth between the nodes: (Unsure, but can gather this info if needed)
Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): (baremetel)
Number of Longhorn volumes in the cluster: [1[](url)](url)[[](url)](url)

**Comment by mantissahz** [comment]
Hi @rajeevpnair Would you provide the longhorn support bundle as well? You could generate it from longhorn UI. Thanks.

**Comment by rajeevpnair** [comment]
@mantissahz  please find the attachment
[longhorn-support-bundle_efe841ad-6f7e-41d7-ae98-2157347894ff_2022-07-01T04-58-50Z.zip](https://github.com/longhorn/longhorn/files/9025191/longhorn-support-bundle_efe841ad-6f7e-41d7-ae98-2157347894ff_2022-07-01T04-58-50Z.zip)

**Comment by mantissahz** [comment]
I found this message `"Error creating backup: mkdir /var/lib/longhorn-backupstore-mounts/192_168_168_82/tmp/nfs_shares/backupstore: permission denied"` in the support bundle.
Could you help me check about the NFS server configuration? Ref: [nfs kb](https://longhorn.io/kb/troubleshooting-unable-to-mount-an-nfs-backup-target/)
or could you kubectl exec into the instance-manager pod to mount the remote nfs server?
Thanks.

**Comment by rajeevpnair** [comment]
thanks much @mantissahz, somehow the nfs filesharing was not allowing anybody to write in the folder even after with 777 permission, I created a new nfs file share and its started taking backups and snapshots... thanks again for your help :)

**Comment by rajeevpnair** [comment]
@mantissahz did you find this log in the snapshot controller logs ?

**Comment by mantissahz** [comment]
I found it in the longhorn support bundle, in the instance-manager log file.
