### ISSUE TITLE
[BUG] SLES15_SP3 is now 15.3 in opensuse devel:tools:scm

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4191]
## Describe the bug

Longhorn engine fails to build because the repo no longer exists [here](https://github.com/longhorn/longhorn-engine/blob/master/Dockerfile.dapper#L19). Should be the same for other components.

The [repo](https://download.opensuse.org/repositories/devel:/tools:/scm/) now has 15.3 instead of SLES15_SP3.
![Screenshot-2022-06-30-19:40:49](https://user-images.githubusercontent.com/22583541/176668811-2167d060-2166-4ad1-8267-6d3b5f14341f.png)

Ref [openSUSE BS](https://build.opensuse.org/repositories/devel:tools:scm).
![Screenshot-2022-06-30-19:00:57](https://user-images.githubusercontent.com/22583541/176667376-e80b1009-5eca-47a3-9925-1527b551d095.png)

## To Reproduce

1. Build image with make.

## Expected behavior

Build complete

## Log or Support bundle

`None`

## Environment

`N/A`

## Additional context

`None`

**Comment by c3y1huang** [comment]
cc @shuo-wu @innobead

**Comment by c3y1huang** [comment]
I've reached out to one of the maintainers, Dirk Mueller, and I believe this is an intended change.
```
this is that after closing the leap gap, both sle 15 sp3 and leap 15.3 are the same build environment. There has been a community voting and the outcome was to use 15.3 and 15.4 as the repository name.
This is the same in most other devel projects and should be the preferred naming
```

**Comment by shuo-wu** [comment]
Need to backport to v1.3.x for the engine repo.
