### ISSUE TITLE
[BUG] spec and status of disks on node are being syncing after delete node from cluster

### ISSUE THREAD

**Issue by vasyakrg** [longhorn/longhorn#4192]
## Describe the bug

After delete node of cluster longhorn don't delete node from config

## To Reproduce

delete node manually except error:

error: admission webhook "validator.longhorn.io" denied the request: spec and status of disks on node <nodename> are being syncing and please retry later.

all another resource with its node deleted.

from node status:
  conditions:
    - lastProbeTime: ''
      lastTransitionTime: '2022-06-25T11:03:47Z'
      message: >-
        Kubernetes node missing: node <nodename> has been
        removed from the cluster and there is no manager pod running on it
      reason: KubernetesNodeGone
      status: 'False'
      type: Ready

from  finalizers:
    - longhorn.io

del finalizer ([]) except error:
error: admission webhook "validator.longhorn.io" denied the request: spec and status of disks on node <nodename> are being syncing and please retry later.

## Environment

 - Longhorn version: 1.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Selectel (cloud) + Rancher (maintenance)
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.20.11
   - Number of management node in the cluster: 9
   - Number of worker node in the cluster: 6

![image](https://user-images.githubusercontent.com/3581271/176672003-26c30b28-60bc-4312-a4c7-0aae4a572fa3.png)
![image](https://user-images.githubusercontent.com/3581271/176672105-e879a77f-7a46-4dc9-a201-5d090f2d8c7f.png)

**Comment by derekbit** [comment]
It hits an issue we found in v1.3.0.
Before the upcoming release of v1.3.1 which will include the fix, you can use the workaround case 2 to fix it temporarily.
https://github.com/longhorn/longhorn/issues/4143

**Comment by vasyakrg** [comment]
> It hits an issue we found in v1.3.0.
> Before the upcoming release of v1.3.1 which will include the fix, you can use the workaround **case 2** to fix it temporarily.
> #4143

many thanks, issue done.
