### ISSUE TITLE
[BUG] Node exists in longhorn and shows as healthy even when offline

### ISSUE THREAD

**Issue by FireBall1725** [longhorn/longhorn#4193]
## Describe the bug

I was having issues with one of my nodes, so I took it offline and ended up replacing it, however the node still shows as healthy in longhorn, and i'm not able to delete it.

![image](https://user-images.githubusercontent.com/727458/176734364-adf1b748-a77c-44d4-a439-5fc72a473fdf.png)

## To Reproduce

1. Drain + Delete kubernetes node
2. Go to longhorn to delete

## Expected behavior

Expected to be able to delete the node, that it would show "down" and the delete button would be enabled.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.3.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s 1.21.5+k3s2
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: Ubuntu 20.04 LTS
   - CPU per node: 1
   - Memory per node: 32gib
   - Disk type(e.g. SSD/NVMe): 1x NVMe 1x magnetic
   - Network bandwidth between the nodes: gigabit ethernet
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Metal
 - Number of Longhorn volumes in the cluster: 4

## Additional context

N/A

**Comment by FireBall1725** [comment]
[longhorn-support-bundle_be1b73df-873b-494c-9d3f-5938c2c3d447_2022-06-30T16-59-13Z.zip](https://github.com/longhorn/longhorn/files/9021873/longhorn-support-bundle_be1b73df-873b-494c-9d3f-5938c2c3d447_2022-06-30T16-59-13Z.zip)

**Comment by FireBall1725** [comment]
also, if i try to disable scheduling in the UI i get this error: 
![image](https://user-images.githubusercontent.com/727458/176738023-4b484768-5b0e-4016-9b49-04aa61c9e2a3.png)

**Comment by derekbit** [comment]
It hits an issue we found in v1.3.0.
Before the upcoming release of v1.3.1 which will include the fix, you can use the workaround case 2 to fix it temporarily.
https://github.com/longhorn/longhorn/issues/4143

**Comment by FireBall1725** [comment]
@derekbit thanks for the link, that fixed the original issue, once i applied the change and went to disable the node it disappeared saying it didn't exist anymore. Everything was able to recover from there. 

Thanks!
