### ISSUE TITLE
[QUESTION] storageclasses.storage.k8s.io "longhorn-static" not found

### ISSUE THREAD

**Issue by sarce666** [longhorn/longhorn#4194]
hello 
longhorn version : 1.2.4

i m create pvc with web interface and attached the volume to a node
i can see that the storageclass is longhorn-static

mattermost       data-db-523050-mysql-0        Bound    pvc-63002a2f-fb47-4639-88cd-a0cffac3b3b2   50Gi       RWO            longhorn-static   52d

but 

> k get sc
NAME                 PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
longhorn             driver.longhorn.io   Delete          Immediate           true                   56d
standard (default)   driver.longhorn.io   Delete          Immediate           true                   56d

so i have no storage class like this , but everything is working
but when i try to do backups , i have this then 

ob failed to be executed
Failed to get cluster level resources: Storage Class
Storage Class referenced by PVC not found
storageclasses.storage.k8s.io "longhorn-static" not found

**Comment by mantissahz** [comment]
I think that is the normal setting of longhorn.
Did you try to do backups then failed?

**Comment by sarce666** [comment]
yes it fails because this storageclass does not exist in kubernetes , it must be a label ?

**Comment by joshimoo** [comment]
`longhorn-static` is a fake storage class used for preprovisioned PVC (static provisioning)
You want to use the dynamic provisioning via for example the default `longhorn` storage class.
You can just create a PVC directly referencing the `longhorn` storage class and it will be dynamically provisioned for you.

REF: https://longhorn.io/docs/1.3.0/volumes-and-nodes/create-volumes/#creating-longhorn-volumes-with-kubectl

**Comment by mantissahz** [comment]
Hi @sarce666,
Does the situation still happen? If yes, could you please provide the support bundle for us?
Document is here [troubleshooting-guide](https://longhorn.io/docs/1.3.0/advanced-resources/troubleshooting/#troubleshooting-guide).

**Comment by sarce666** [comment]
hello 

i m not sur i understand
ok this is fake storage class
but in my porduction kubernetes i see it running as a storage class longhorn-statics
should i then create a storageclass longhorn-static ( a copy of the existing storage class longhorn ?

**Comment by mantissahz** [comment]
@sarce666 you could modify the `Default Longhorn Static StorageClass Name` value on UI page `Setting> General`
ref: [default-longhorn-static-storageclass-name](https://longhorn.io/docs/1.3.0/references/settings/#default-longhorn-static-storageclass-name)

**Comment by mantissahz** [comment]
@sarce666 officially we don't encourage you to create the StorageClass 'longhorn-static' to fit the existing volumes.

**Comment by migs35323** [comment]
i am having a similair issue while using velero, it tries to call the snapshooter for longhorn-static, however it doesnt' find this storageclass

```
level=error msg="Error backing up item" backup=velero/cluster-full-backup error="error executing custom action (groupResource=persistentvolumeclaims, namespace=test, name=test): rpc error: code = Unknown desc = error getting storage class: storageclasses.storage.k8s.io \"longhorn-static\" not found" logSource="pkg/backup/backup.go:417" name=test-lrsk2

```
