### ISSUE TITLE
[TEST] Add version information on each regression test build

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#4204]
## What's the test to develop? Please describe

Currently there's no way to know the version (commit id) of longhorn-manager and longhorn-engine used in each regression test build.
These information need to be revealed so we are able to know this build includes a commit or not.

**Comment by innobead** [comment]
![Image](https://user-images.githubusercontent.com/899492/182304389-4a302d4d-0894-4ae3-8dd6-421dd61ce5e2.png)
