### ISSUE TITLE
[FEATURE] ARM64 GA

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4206]
## Is your feature request related to a problem? Please describe

We have ARM64 experimental support from 1.1. To graduate to GA, it's necessary to ensure the coverage and testing result of arm64 is consistent with amd64.

## Describe the solution you'd like

Figure out the gap in test results between arm64 and amd64, then fix it.

## Describe alternatives you've considered

N/A

cc @longhorn/qa

**Comment by innobead** [comment]
@cchien816 has implemented the automatic engine image build for arm64 about compatibility and upgrade testing. https://github.com/longhorn/longhorn-tests/pull/1012, after that, we can start tracking if the test coverage of arm64 is the same as amd64. 

@cchien816 Please help with this. Thanks.

**Comment by cchien816** [comment]
After build test images PR build, ARM64 pipeline now have no failures related to engine upgrade
Below are recent test results for reference:

AMD64

- Build [195](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/195/testReport/) - 6 fail, 228 pass
- Build [196](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/196/testReport/) - 6 fail, 229 pass

ARM64

- Build [181](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/181/testReport/)- 5 fail, 229 pass
- Build [182](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/182/testReport/) - 8 fail, 225 pass

**Comment by innobead** [comment]
> After build test images PR build, ARM64 pipeline now have no failures related to engine upgrade Below are recent test results for reference:
> 
> AMD64
> 
> * Build [195](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/195/testReport/) - 6 fail, 228 pass
> * Build [196](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/196/testReport/) - 6 fail, 229 pass
> 
> ARM64
> 
> * Build [181](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/181/testReport/)- 5 fail, 229 pass
> * Build [182](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/182/testReport/) - 8 fail, 225 pass

This is awesome. Let's keep this open until the number of failed cases is down close to 0 for both arches.

**Comment by innobead** [comment]
@chriscchien Let's update the below info before closing this issue. 

- The failed ratio and The performance benchmark are the same between amd64 and arm64.
- Update the doc to remove experimental from ARM64.

**Comment by chriscchien** [comment]
amd64 benchmark test - Build [32](https://ci.longhorn.io/job/private/job/longhorn-benchmark-test/32/)
arm64 benchmark test - Build [33](https://ci.longhorn.io/job/private/job/longhorn-benchmark-test/32/)

**Comment by chriscchien** [comment]
> @chriscchien Let's update the below info before closing this issue.
> 
> * The failed ratio of e2e testing and performance benchmark are the same between amd64 and arm64.
> * Update the doc to remove experimental from ARM64.
> 
> cc @longhorn/qa

- From latest master-head pipeline test result, distro [AMD64](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/306/) and [ARM64](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/290/) both have 2 failed test cases, 1 were known [issue](https://github.com/longhorn/longhorn/issues/4382) and another 1 was flaky test case

- For benchmark test, our pipeline current not support ARM, I am doing it manually now 

- About remove experimental from ARM64 in v1.4.0 doc, submitted [PR](https://github.com/longhorn/website/pull/608) for review

**Comment by chriscchien** [comment]
k8s distro : v1.23.1+k3s2
ADM64 instance type : c5d.2xlarge
ARM64 instance type : c6gd.2xlarge

**local-path-provisioner**
|            |      | IOPS    |        | Bandwidth |         | Latency |         |
|------------|------|---------|--------|-----------|---------|---------|---------|
|            |      | read    | write  | read      | write   | read    | write   |
| AMD64      | rand | 79,995  | 37,002 | 362,226   | 167,051 | 89,693  | 29,344  |
|            | seq  | 79,999  | 37,008 | 362,250   | 167,068 | 27,239  | 31,350  |
| ARM64      | rand | 107,497 | 45,000 | 546,253   | 256,345 | 84,710  | 25,692  |
|            | seq  | 107,502 | 45,007 | 546,308   | 256,384 | 23,211  | 26,748  |
| Difference | rand |  34.38% | 21.62% |    50.80% |  53.45% |  -5.56% | -12.45% |
|            | seq  |  34.38% | 21.61% |    50.81% |  53.46% | -14.79% | -14.68% |


**3 replicas**
|            |      | IOPS   |         | Bandwidth |         | Latency |         |
|------------|------|--------|---------|-----------|---------|---------|---------|
|            |      | read   | write   | read      | write   | read    | write   |
| AMD64      | rand | 23,108 | 6,211   | 911,417   | 161,975 | 490,022 | 531,919 |
|            | seq  | 38,097 | 12,118  | 724,788   | 164,463 | 475,805 | 547,574 |
| ARM64      | rand | 24,425 | 13,137  | 986,494   | 248,477 | 473,082 | 536,486 |
|            | seq  | 38,600 | 22,578  | 1,096,936 | 252,077 | 474,245 | 538,223 |
| Difference | rand |  5.70% | 111.51% |     8.24% |  53.40% |  -3.46% |   0.86% |
|            | seq  |  1.32% |  86.32% |    51.35% |  53.27% |  -0.33% |  -1.71% |

**2 replicas**
|            |      | IOPS   |        | Bandwidth |         | Latency |         |
|------------|------|--------|--------|-----------|---------|---------|---------|
|            |      | read   | write  | read      | write   | read    | write   |
| AMD64      | rand | 23,711 | 13,570 | 724,384   | 161,969 | 437,349 | 490,909 |
|            | seq  | 39,238 | 23,531 | 699,120   | 164,317 | 436,747 | 505,705 |
| ARM64      | rand | 23,883 | 13,739 | 982,260   | 248,540 | 478,948 | 516,369 |
|            | seq  | 36,843 | 24,036 | 1,017,531 | 252,153 | 477,218 | 533,714 |
| Difference | rand |  0.73% |  1.25% |    35.60% |  53.45% |   9.51% |   5.19% |
|            | seq  | -6.10% |  2.15% |    45.54% |  53.46% |   9.27% |   5.54% |


**1 replica** 
|            |      | IOPS   |        | Bandwidth |         | Latency |         |
|------------|------|--------|--------|-----------|---------|---------|---------|
|            |      | read   | write  | read      | write   | read    | write   |
| AMD64      | rand | 22,714 | 11,565 | 362,171   | 161,975 | 408,574 | 377,704 |
|            | seq  | 38,784 | 25,191 | 362,166   | 164,302 | 313,684 | 373,010 |
| ARM64      | rand | 20,752 | 19,169 | 562,631   | 248,252 | 506,091 | 472,841 |
|            | seq  | 36,934 | 31,903 | 562,230   | 251,968 | 440,637 | 472,649 |
| Difference | rand | -8.6%  | 65%    | 55%       | 53%     | 23%     | 25%     |
|            | seq  | -4.7%  | 26%    | 55.2%     | 53%     | 40%     | 26%     |

**Comment by derekbit** [comment]
From the local-path-provisioner tests' results, the SSDs specs in the AMD and ARM machines should be different.

**Comment by innobead** [comment]
It seems not easy to get the same testing baseline even the general spec similar.

**Comment by innobead** [comment]
Let's follow up with the ARM64 performance benchmark individually instead of trying to compare it with a different architecture. The goal is to see if the performance of each architecture gets improved consistently along with releases.

cc @longhorn/qa
