### ISSUE TITLE
[TEST] Remove "Your License Limit is Exceeded." message in drone-pr

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#4207]
## What's the test to develop? Please describe

https://www.sobyte.net/post/2022-05/drone-license/#free-to-use-open-source-or-enterprise-version

probably need to rebuild our own custom image

**Comment by innobead** [comment]
Do you mean right now we use a customized drone image?

**Comment by deersheep330** [comment]
> Do you mean right now we use a customized drone image?

No, currently we use official drone helm chart / docker image.
I mean this issue seems can only fixed by rebuild the image by ourselves with additional parameter.

**Comment by innobead** [comment]
I see, but why drone-push does not have this issue? Does it use a different way?

**Comment by yangchiu** [comment]
> I see, but why drone-push does not have this issue? Does it use a different way?

Probably because the total builds in drone-publish are < 5000.
In drone-pr, The total builds of longhorn-manager + longhorn-engine + longhorn-tests are already > 5000.

**Comment by innobead** [comment]
https://docs.drone.io/enterprise/#is-drone-enterprise-available-for-trial

**Comment by yangchiu** [comment]
Fixed by removing build records in drone database to make total # of builds < 5000.
https://gist.github.com/david-liu-950627/0bfc5520cce019c5b2d595236f141dd5

**Comment by yangchiu** [comment]
When this happens again:

(1) `ssh` into infra server
(2) `kubectl exec` into drone-pr pod
(3) if sqlite command not found, install it: `apk add sqlite`
(4) the default database path is `/data/database.sqlite`
(5) check # of builds first, it should > 5000
```
/data # sqlite3 database.sqlite 
sqlite> select count(*) from builds;
5019
sqlite> .exit
```
(6) execute the delete.sql
`/data # sqlite3 database.sqlite < delete.sql`
(7) check # of builds again, it should < 5000 now:
```
/data # sqlite3 database.sqlite 
sqlite> select count(*) from builds;
2522
sqlite> .exit

```

**Comment by briandowns** [comment]
Are purged builds available for review anywhere after purging?

**Comment by sviatoslav6** [comment]
> When this happens again:
> 
> (1) `ssh` into infra server (2) `kubectl exec` into drone-pr pod (3) if sqlite command not found, install it: `apk add sqlite` (4) the default database path is `/data/database.sqlite` (5) check # of builds first, it should > 5000
> 
> ```
> /data # sqlite3 database.sqlite 
> sqlite> select count(*) from builds;
> 5019
> sqlite> .exit
> ```
> 
> (6) execute the delete.sql `/data # sqlite3 database.sqlite < delete.sql` (7) check # of builds again, it should < 5000 now:
> 
> ```
> /data # sqlite3 database.sqlite 
> sqlite> select count(*) from builds;
> 2522
> sqlite> .exit
> ```

Can you show your "delete.sql"?

**Comment by yangchiu** [comment]
> Can you show your "delete.sql"?

It's here: https://gist.github.com/david-liu-950627/0bfc5520cce019c5b2d595236f141dd5

**Comment by devops-orderonline** [comment]
@yangchiu can you show delete.sql ? the file has not found thank you

**Comment by devops-orderonline** [comment]
hi @sviatoslav6 can u share what the inside delete.sql file ?

**Comment by sviatoslav6** [comment]
> hi @sviatoslav6 can u share what the inside delete.sql file ?

```
PRAGMA foreign_keys = ON;

WITH n_build_ids_per_repo as (
  SELECT build_id
  FROM (
    SELECT
      build_id,
      build_repo_id,
      DENSE_RANK() OVER (PARTITION BY build_repo_id ORDER BY build_id DESC) AS rank
    FROM builds
  ) AS t
  WHERE t.rank <= 100
)
DELETE FROM
  builds
WHERE
  builds.build_id NOT IN (SELECT build_id FROM n_build_ids_per_repo);
```
