### ISSUE TITLE
[IMPROVEMENT] Introduce checksum for snapshots

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4210]
## Is your improvement request related to a feature? Please describe

After creating a snapshot, Longhorn volume can calculate the checksum then store it in the metafile along with the modification time. Later on when the volume needs to rebuild/reuse a failed replica or somehow need to validate a replica, checking the checksum & modification time matching would help skip unnecessary snapshot syncing, which actually speeds up the whole progress.

## Describe the solution you'd like
- [ ] Store the modification time during snapshot creation
- [ ] Calculate the checksum with an async goroutine after snapshot creation.
- [ ] Check and match the checksum & modification time before syncing a snapshot file
- [ ] (Optional, maybe we can open another ticket for this if required) Verify the snapshot file consistency by checking the modification time & checksum during attachment.

## Additional context
This one is similar to what I have done for the backing image management.

**Comment by Martin-Weiss** [comment]
In case this helps for „delta-sync“ of data - this would be a really important feature! Especially in the area of Harvester it is really important to get a journal / delta-sync added! In the case of Harvester we have volumes with several hundreds of GB and we have node capacity of 4, 8 or more TB of data - and full re-replication of such an amount of data during node failures / maintenance / data-center failures etc. Is really a difficult challenge..

**Comment by shuo-wu** [comment]
cc @joshimoo

**Comment by derekbit** [comment]
> After creating a snapshot, Longhorn volume can calculate the checksum then store it in the metafile along with the modification time. 

Can the checksume be stored in the `snapshot.spec`?

**Comment by shuo-wu** [comment]
Probably it can be updated and stored in `snapshot.Status` but with an async way.

**Comment by derekbit** [comment]
### Benchmark

#### x86_64

|  --  | --  |
|  ----  | ----  |
| Kubernetes | v1.24.4+rke2r1 |
| Longhorn |  master-head with snapshot checksum feature |
| Host | AWS EC2 c5d.2xlarge |
| CPU | Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz |
| RAM | 16 GiB |
| Disk model | Amazon EC2 NVMe Instance Storage |

- Volume size: 100 GiB with random data
- Checksumming time: 325 seconds
- Checksumming throughput: 315 MiB/s
- CPU usage (`kubectl -n longhorn-system top instance-manager-r-xxx`):  900m (2m at idle state) 

cc @shuo-wu @joshimoo @innobead

**Comment by innobead** [comment]
This needs @longhorn/qa to update upgrade testing engine image. cc @chriscchien

**Comment by derekbit** [comment]
e2e
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2485/console

**Comment by khushboo-rancher** [comment]
@roger-ryao Could you add the test skeleton for https://github.com/longhorn/longhorn/issues/4845 while you test this?

**Comment by innobead** [comment]
@khushboo-rancher Should run our e2e pipeline when the checksum is enabled to see if there will be any e2e issues.

cc @longhorn/qa

**Comment by khushboo-rancher** [comment]
Just a suggestion about the UI, now that we have `Snapshot` section on the setting page, we should move the setting `Automatically Cleanup System Generated Snapshot` from `General` section to `Snapshot` section?
