### ISSUE TITLE
[BUG] After updating longhorn to version 1.3.0, only 1 node had problems and I can't even delete it

### ISSUE THREAD

**Issue by elton557** [longhorn/longhorn#4213]
Hello, I updated my longhorn to version 1.3.0, but 1 node was not healthy and crashed some volumes, they are degraded, what can I do?
<img width="1437" alt="Screen Shot 2022-07-07 at 22 00 22" src="https://user-images.githubusercontent.com/52458645/177988166-f607095a-8fe2-42eb-a446-e53b9140b9a8.png">

I tried to delete the node with problems, but it only has this state

<img width="1426" alt="Screen Shot 2022-07-07 at 22 30 53" src="https://user-images.githubusercontent.com/52458645/177988262-72d6642e-7a5a-4bd3-9ad2-83f07958f470.png">

**Comment by derekbit** [comment]
Any error message?

**Comment by elton557** [comment]
this command did not work see

<img width="1028" alt="Screen Shot 2022-07-08 at 09 27 10" src="https://user-images.githubusercontent.com/52458645/177992121-d9b1a1fe-51dd-4e04-a9bf-5864485ae261.png">

**Comment by elton557** [comment]
After the update, this node was the only one that didn't enter the longhorn-manager, see! looks like he was orphaned, that's when I thought about deleting him from the rancher, thinking it would unlock the volumes!

<img width="1430" alt="Screen Shot 2022-07-08 at 09 40 18" src="https://user-images.githubusercontent.com/52458645/177994427-a8a77a49-cf1e-4eee-ace3-3dbaaedcbe3e.png">

**Comment by elton557** [comment]
After the update, this node was the only one that didn't enter the onghorn-manager, see! looks like he was orphaned, that's when I thought about deleting him from the rancher, thinking it would unlock the volumes!



<img width="1440" alt="Screen Shot 2022-07-08 at 09 45 13" src="https://user-images.githubusercontent.com/52458645/177994661-6dffe935-f53f-4923-8eae-8a3f30c4f2e3.png">

**Comment by derekbit** [comment]
Weird. Could you send us the support bundle? We can check it.
Is any important data in your unlocked volume?

**Comment by derekbit** [comment]
I saw the longhorn node (rancher-k8s-dc-node01) is still in your longhorn-system.
`kubectl -n longhorn-system get nodes.longhorn.io rancher-k8s-dc-node01`
How did you delete the node from the longhorn/kubernetes cluster?

**Comment by elton557** [comment]
@derekbit  When I try to remove the node through the longhorn interface I get the print errors

<img width="1432" alt="Screen Shot 2022-07-08 at 12 46 32" src="https://user-images.githubusercontent.com/52458645/178026484-b5f843f5-4385-4da9-979a-3d15a068abd0.png">

**Comment by derekbit** [comment]
@elton557 Can you set disable the scheduling of the `rancher-k8s-dc-node01` before deleting the node?

**Comment by elton557** [comment]
![914FCC24-9A29-4215-AE17-FEBC88A78228](https://user-images.githubusercontent.com/52458645/178314642-b96e8480-0970-4580-bc79-edb7297bc3ad.png)

**Comment by innobead** [comment]
cc @PhanLe1010

**Comment by derekbit** [comment]
@elton557 Can you delete the longhorn node by command line?

**Comment by elton557** [comment]
would it be via kubectl? can you give me the instruction? this node has some replicas stuck on it will it work?

**Comment by derekbit** [comment]
@elton557 You can try `kubectl -n longhorn-system delete node.longhorn.io rancher-k8s-dc-node01`.

**Comment by elton557** [comment]
Hello I ran the command it is stuck like this and also does not remove the node

<img width="1026" alt="Screen Shot 2022-07-12 at 10 57 54" src="https://user-images.githubusercontent.com/52458645/178507998-bb471b8a-6e19-4c97-81b0-93f4420a00b8.png">

**Comment by derekbit** [comment]
Can you check your kubelet log to see if there is any error message?

**Comment by elton557** [comment]
doesn't show me any errors

**Comment by derekbit** [comment]
@PhanLe1010 Do you have any idea how to delete the longhorn node?

**Comment by innobead** [comment]
Blocked by the finalizer?

**Comment by elton557** [comment]
I can enter the edit, remove the lines and save, but it returns this error and does not save
<img width="1037" alt="Screen Shot 2022-07-12 at 13 14 12" src="https://user-images.githubusercontent.com/52458645/178542324-d3b60fe3-7859-4cf8-bf81-9953b4764b86.png">

**Comment by derekbit** [comment]
Weird, can you show the changes it mentioned in `/var/foldders/xm/vlrq....../T/kubectl-edit-9qawx.yaml`?

**Comment by elton557** [comment]
Follow the content of the directory!
<img width="1047" alt="Screen Shot 2022-07-12 at 21 38 42" src="https://user-images.githubusercontent.com/52458645/178624183-0c12e9b3-9263-4820-9921-857ab078bffe.png">

**Comment by PhanLe1010** [comment]
The original issue was that Longhorn manager pod didn't come up on the node https://github.com/longhorn/longhorn/issues/4213#issuecomment-1178949024. It could potentially due to some taint on this node. I the approach would be to try to get longhorn manager pods to be running on this node.

Now that you deleted the node from rancher UI, let's check to see why we cannot delete the Longhorn node.

From the support bundle, I see that the node already has the deletion timestamp set and also this event log is printed out repeatedly `2022-07-08T12:56:42.216468105Z time="2022-07-08T12:56:42Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"rancher-k8s-dc-node01\", UID:\"46a3640b-15f5-4ba5-998a-03ee0cc97e86\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"852068627\", FieldPath:\"\"}): type: 'Warning' reason: 'Delete' Deleting node rancher-k8s-dc-node01"
` . The event comes from [this code path](https://github.com/longhorn/longhorn-manager/blob/ae11ba8076abd679893fd2e790fed1e048dc8c6d/controller/node_controller.go#L285-L286). As you can see that the next step after Longhorn generating the event log is Longhorn to remove the finalizer. However, the finilzer wasn't removed as we still can see it inside the node yaml file:
```
  objectmeta:
    name: rancher-k8s-dc-node01
    generatename: ""
    namespace: longhorn-system
    creationtimestamp: "2021-03-25T14:16:36Z"
    deletiontimestamp: "2022-07-08T00:44:33Z"
    deletiongraceperiodseconds: 0
    finalizers:
    - longhorn.io
``` 
Another data point from [this picture](https://github.com/longhorn/longhorn/issues/4213#issuecomment-1179135582) when you deleting the node let to the root cause `the validation webhook prevent the removal of the finalizer when it cannot find the corresponding kubenetes node. Thus, the validation weekhook block deletion flow of Longhorn node`. This conclusion is further confirmed by the code [here](https://github.com/longhorn/longhorn-manager/blob/969ffd1dfc69985718f12cd00412680a7c8da05a/webhook/resources/node/validator.go#L86-L89). I think is a regression bug that Longhorn need to fix

**Comment by PhanLe1010** [comment]
Anyway to workaround the validation weekhook? @derekbit

**Comment by derekbit** [comment]
Yes. The node validation webhook can be removed temporary.

Step 1. User can disable the validating webhook of the node resources temporarily
```
# kubectl edit validatingwebhookconfigurations.admissionregistration.k8s.io longhorn-webhook-validator

... OMITTED ...

webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwakNDQVUyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQTdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoK
    service:
      name: longhorn-admission-webhook
      namespace: longhorn-system
      path: /v1/webhook/validaton
      port: 9443
  failurePolicy: Fail
  matchPolicy: Exact
  name: validator.longhorn.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - longhorn.io
    apiVersions:
    - v1beta2
    operations:
    - UPDATE
    resources:
    - nodes
    scope: Namespaced
  - apiGroups:
    - longhorn.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - settings
    scope: Namespaced

... OMITTED ...
```

Step 2. Remove the part (rule for node validation) and then save.
```
  - apiGroups:
    - longhorn.io
    apiVersions:
    - v1beta2
    operations:
    - UPDATE
    resources:
    - nodes
    scope: Namespaced
```
Step 3. Remove the node finalizers

Step 4. Delete the admission webhook pod, and then the pods are re-created and regenerate the rules

 kubectl -n longhorn-system delete pod -l app=longhorn-admission-webhook

**Comment by elton557** [comment]
hello, do i need to do something?

**Comment by derekbit** [comment]
Yes. You can follow the steps in https://github.com/longhorn/longhorn/issues/4213#issuecomment-1182648730

**Comment by derekbit** [comment]
If the kubernete node is gone, Longhorn doesn’t need to error out here.

https://github.com/longhorn/longhorn-manager/blob/969ffd1dfc69985718f12cd00412680a7c8da05a/webhook/resources/node/validator.go#L86-L89

**Comment by derekbit** [comment]
> @derekbit Sorry, a question the first step, do I have to do this? same in print? would it be this? or do I have to comment line by line with # equals in the shell?
> 
> <img alt="Screen Shot 2022-07-13 at 10 52 05" width="1015" src="https://user-images.githubusercontent.com/52458645/178750853-3906b509-2b55-415b-848e-fdeac3869ed0.png">

The first step is just open the resource manifest and don't need to do other things. Then, the seconds step is removing the content I mentioned.

**Comment by elton557** [comment]
Node has been removed, but volumes are still stuck like this

<img width="1440" alt="Screen Shot 2022-07-13 at 11 10 05" src="https://user-images.githubusercontent.com/52458645/178754520-df80e345-fa6d-49b4-b8ca-08abc9a39dd8.png">

**Comment by derekbit** [comment]
> Node has been removed, but volumes are still stuck like this
> 
> <img alt="Screen Shot 2022-07-13 at 11 10 05" width="1440" src="https://user-images.githubusercontent.com/52458645/178754520-df80e345-fa6d-49b4-b8ca-08abc9a39dd8.png">

Is the volume on which node?

**Comment by elton557** [comment]
Hello, I will not use these volumes that are in detaching status, but I try to remove the replica that is N/A, nothing happens, but there are volumes that are in disaggregated mode because of the node replica that I removed, which I can't remove and return to healthy status:

<img width="1428" alt="Screen Shot 2022-07-13 at 15 36 43" src="https://user-images.githubusercontent.com/52458645/178818715-08bd4ec9-aa07-4e9d-905b-92542204f9f0.png">


Here is the link to the support package: 
https://drive.google.com/file/d/1ip13fyHjwHngl7VzSMT511hmTdTCRDnT/view?usp=sharing

**Comment by PhanLe1010** [comment]
@derekbit 

We can check the code paths:
* Detaching a volume which was previously attached to non-existing node
* Deleting replicas that is to non-existing node

**Comment by derekbit** [comment]
The replica sync is hindered by
```
"fail to sync replica for longhorn-system/pvc-52b17e7a-e53d-47c6-8bf6-c8e0f180304d-r-3a695451: BUG: instance state and storage IP wasn't in sync &{TypeMeta:{Kind: APIVersion:}
```

**Comment by derekbit** [comment]
While the volume is at detaching state, the volume controller will check if all replicas are stopped ([code](https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go#L1370)).

But the replica, which is on the N/A node, cannot be synced by the replica controller because of the error ([code](https://github.com/longhorn/longhorn-manager/blob/master/datastore/longhorn.go#L1041))
```
"fail to sync replica for longhorn-system/pvc-52b17e7a-e53d-47c6-8bf6-c8e0f180304d-r-3a695451: BUG: instance state and storage IP wasn't in sync ...
```

The deletion of Replica should not be hindered [code](https://github.com/longhorn/longhorn-manager/blob/master/datastore/longhorn.go#L1132).

@elton557 
Can you delete the replica `pvc-52b17e7a-e53d-47c6-8bf6-c8e0f180304d-r-3a695451` of the volume `pvc-52b17e7a-e53d-47c6-8bf6-c8e0f180304d` on the UI page? I saw the replica was created `2022-06-06T12:01:27Z` and was not deleted. Deletion should work and longhorn-manager can continue the detaching job.

**Comment by innobead** [comment]
> The replica `spec.nodeid` and `status.ownerid` are both `rancher-k8s-dc-node01`. The `rancher-k8s-dc-node01` and its longhron-manager do not exist. However, the ownership of the replica cannot be transferred to another node because of the error ([code](https://github.com/longhorn/longhorn-manager/blob/master/datastore/longhorn.go?rgh-link-date=2022-07-14T04%3A02%3A03Z#L1041))
> 
> ```
> "fail to sync replica for longhorn-system/pvc-52b17e7a-e53d-47c6-8bf6-c8e0f180304d-r-3a695451: BUG: instance state and storage IP wasn't in sync
> ```

https://github.com/longhorn/longhorn-manager/blob/master/datastore/longhorn.go#L1037-L1042

I believe the user does not use the storage network, so the `r.Status.StorageIP` should be equal to `r.Status.IP`. 

Just a reference: there is a fix related to get storage IP recently (https://github.com/longhorn/longhorn-manager/pull/1398). 

cc @c3y1huang

**Comment by PhanLe1010** [comment]
For the workaround, we can use `kubectl edit replicas.longhorn.io pvc-52b17e7a-e53d-47c6-8bf6-c8e0f180304d-r-3a695451 -n longhorn-system` and remove the `longhorn.io` finalizer @derekbit

**Comment by elton557** [comment]
Thanks that worked!

**Comment by innobead** [comment]
@c3y1huang @derekbit Please provide the test steps to QA. Thanks. cc @cchien816

**Comment by derekbit** [comment]
I cannot reproduce the issue on my side and just knew the operation was stuck at the node's validating webhook from log.

**Comment by c3y1huang** [comment]
This one is probably hard to catch since in normal cases the storageIP gets updated even before the fix. @cchien816 suggested we do tests by steps mentioned in this issue.

**Comment by cchien816** [comment]
**Verified on longhorn-manager `dc17cf`
Result Pass**

Scenario 1
1. Install LH master-head with 3 nodes
2. Run command `kubectl delete node <node name>`
3. In LH UI, the node disappeared 

Scenario 2
1. Install LH v1.2.4 with 3 nodes
2. Upgrade LH to master-head
3. During upgrade, run command `kubectl delete node <node name>`
4. Observe upgrade completed and the deleted node disappear in Longhorn UI
