### ISSUE TITLE
[BUG] Unable to use a TTY error when running environment_check.sh

### ISSUE THREAD

**Issue by flkdnt** [longhorn/longhorn#4216]
## Describe the bug

Running environment_check as a suggested prereq to install throws an error: "Unable to use a TTY - input is not a terminal or the right kind of file"

## To Reproduce

On k8s cluster, run:

```curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.3.0/scripts/environment_check.sh | bash```

## Expected behavior

I'd start seeing checks being performed

## Log or Support bundle
```
curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.3.0/scripts/environment_check.sh | bash
[INFO]  Required dependencies are installed.
[INFO]  Waiting for longhorn-environment-check pods to become ready (0/5)...
[INFO]  All longhorn-environment-check pods are ready (5/5).
Unable to use a TTY - input is not a terminal or the right kind of file
Unable to use a TTY - input is not a terminal or the right kind of file
Unable to use a TTY - input is not a terminal or the right kind of file
Unable to use a TTY - input is not a terminal or the right kind of file
Unable to use a TTY - input is not a terminal or the right kind of file
[INFO]  Required packages are installed.
[INFO]  Cleaning up longhorn-environment-check pods...
[INFO]  Cleanup completed.
```

## Environment

 - Longhorn version: N/A, as this is a prereq
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): N/A
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version:  Ubuntu 21.10
   - CPU per node: 4
   - Memory per node: 2GB
   - Disk type(e.g. SSD/NVMe): HDD
   - Network bandwidth between the nodes: 1GB
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Raspberry Pi 4
 - Number of Longhorn volumes in the cluster: 4

## Additional context

This is how I fixed it on my system, but I don't know if this is the fix for all cases:

1. curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.3.0/scripts/environment_check.sh -O
2. chmod 733 environment_check.sh
3. Nano environment_check.sh
4. Find and replace -it with -i (as suggested here: https://stackoverflow.com/questions/60826194/kubectl-exec-fails-with-the-error-unable-to-use-a-tty-input-is-not-a-terminal)
5. save and exit
6. ./environment_check.sh

**Comment by derekbit** [comment]
@flkdnt  Thank you for raising the issue. Could you submit the PR fixing the TTY issue?

**Comment by flkdnt** [comment]
@derekbit will do

**Comment by innobead** [comment]
The PR was merged, but still needs QA to walk through the ready-for-testing flow. Assigned to @cchien816 .

**Comment by cchien816** [comment]
**Verified in longhorn `edc1b83`
Result Pass**

Can reproduce in v1.3.0
```
# curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.3.0/scripts/environment_check.sh | bash
[INFO]  Required dependencies are installed.
[INFO]  Waiting for longhorn-environment-check pods to become ready (0/3)...
[INFO]  All longhorn-environment-check pods are ready (3/3).
Unable to use a TTY - input is not a terminal or the right kind of file
Unable to use a TTY - input is not a terminal or the right kind of file
Unable to use a TTY - input is not a terminal or the right kind of file
[INFO]  Required packages are installed.
[INFO]  Cleaning up longhorn-environment-check pods...
[INFO]  Cleanup completed.
```

I longhorn master-head the environment check script will get below result which does not contain `Unable to use a TTY` error massage
```
curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/master/scripts/environment_check.sh | bash
[INFO]  Required dependencies are installed.
[INFO]  Waiting for longhorn-environment-check pods to become ready (0/3)...
[INFO]  All longhorn-environment-check pods are ready (3/3).
[INFO]  Required packages are installed.
[INFO]  Cleaning up longhorn-environment-check pods...
[INFO]  Cleanup completed.
```
