### ISSUE TITLE
[TEST] Create a pipeline or enrich the existing to run regression over storage network

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4218]
## What's the test to develop? Please describe

https://github.com/longhorn/longhorn-tests/pull/984#issuecomment-1180100078

## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] Create an individual pipeline or enrich the current pipeline to run the regression over the storage network 

cc @longhorn/qa @c3y1huang

**Comment by yangchiu** [comment]
Currently working on testing thick plugin then adding it to the pipeline.

**Comment by yangchiu** [comment]
> Currently working on testing thick plugin then adding it to the pipeline.

Have updated in the PRs.
