### ISSUE TITLE
Longhorm volumes cannot attach

### ISSUE THREAD

**Issue by Mafalda22** [longhorn/longhorn#4232]
I have a rancher cluster with rke2 and longhorm installed. I'm trying to deploy elastic cloud and the volumes are being attached and unattached all the time and eck isn't quite ready. In the logs I see the following:

Warning  FailedAttachVolume  10s   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-70a16c86-2e98-4a7e-a306-ef7238969f85" : rpc error: code = DeadlineExceeded desc = vol

**Comment by mantissahz** [comment]
Hi @Mafalda22
1. Could you please describe your more details about rancher, rke2, and longhorn environments?
2. Do you have all requirements https://longhorn.io/docs/1.3.0/deploy/install/#installation-requirements ?
3. Did you see any error or warning logs in longhorn-manager, instance-mananger or other longhorn pods?
That would be good if you could provide the support bundle for us.

**Comment by Mafalda22** [comment]
Hi @mantissahz I have an rke2 development cluster with 6 nodes, three workers and three nodes. Then three servers for rancher. I have installed longhorm in a development cluster namespace and when I create pods with volumes they attach and detach constantly. 
I have reviewed the requirements, I have installed open-iscsi and NFSv4 client. The check script tells me that everything is ok.
the csi attacher logs show this I don't know if it's an error
I0629 15:52:01.387767       1 main.go:96] Version: v3.2.1
I0629 15:52:01.398587       1 common.go:111] Probing CSI driver for readiness
I0629 15:52:01.402469       1 main.go:152] CSI driver name: "driver.longhorn.io"
I0629 15:52:01.413416       1 main.go:208] CSI driver supports ControllerPublishUnpublish, using real CSI handler
I0629 15:52:01.418338       1 leaderelection.go:243] attempting to acquire leader lease longhorn-system/external-attacher-leader-driver-longhorn-io...

**Comment by mantissahz** [comment]
@Mafalda22 Could you provide the support bundle for us to find out what happened? You could generate the support bundle on Longhorn UI.

**Comment by PhanLe1010** [comment]
@Mafalda22 Do you still have issue here?
@mantissahz Could you please put the slack link here? Thank you

**Comment by mantissahz** [comment]
Sure, here it is https://rancher-users.slack.com/archives/CC2UQM49Y/p1657740361696769
and it hit this issue https://github.com/longhorn/longhorn/issues/2319.
@Mafalda22 I think the issue had bean solved, WDYT?
