### ISSUE TITLE
Rancher chart migration script clarification

### ISSUE THREAD

**Issue by courcelm** [longhorn/longhorn#4235]
## Describe the bug

I get the following error when I run the migration script:

Looking up Rancher Project App 'longhorn-system' ...
error: the server doesn't have a resource type "apps"

## To Reproduce

./longhorn_rancher_chart_migration.sh -u PATH -d PATH -t migrate

## Expected behavior

No error

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

Rancher 2.6.6

 - Longhorn version: 1.2.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE 
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 9
 - Node config
   - OS type and version: Ubuntu 20.04 LTS
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Bare metal
 - Number of Longhorn volumes in the cluster: 10

**Comment by courcelm** [comment]
I confused the upstream kubeconfig file. In my case, the right upstream kubeconfig was from the local cluster. 

The upstream concept is not clear in the documentation (step 2 of https://longhorn.io/kb/how-to-migrate-longhorn-chart-installed-in-old-rancher-ui-to-the-chart-in-new-rancher-ui/) and I suggest it is clarified.

**Comment by innobead** [comment]
> I confused the upstream kubeconfig file. In my case, the right upstream kubeconfig was from the local cluster.
> 
> The upstream concept is not clear in the documentation (step 2 of [longhorn.io/kb/how-to-migrate-longhorn-chart-installed-in-old-rancher-ui-to-the-chart-in-new-rancher-ui](https://longhorn.io/kb/how-to-migrate-longhorn-chart-installed-in-old-rancher-ui-to-the-chart-in-new-rancher-ui/)) and I suggest it is clarified.

In the KB, the upstream means your rancher cluster, and the downstream is for the cluster Longhorn is running on. Any part you suggested to clarify?

```
Download the kubeconfig file for the upstream rancher cluster. Download the kubeconfig file for the downstream cluster where Longhorn is running on.
```

BTW, did the migration work after using the right kubeconfig? 

cc @PhanLe1010

**Comment by courcelm** [comment]
The first part would need clarification: Download the kubeconfig file for the upstream rancher cluster.

From my point of view, I installed Longhorn using the catalog in the same cluster as Longhorn is running. This is where I can see it in the Legacy/Project section. I did not expect it was referring to the local cluster. I don`t know if the Rancher is always named local but it could be added.

Yup the migration looks fine. Nothing broke yet. Hope the update to 1.3 will good smooth.

**Comment by innobead** [comment]
> The first part would need clarification: Download the kubeconfig file for the upstream rancher cluster.
> 
> From my point of view, I installed Longhorn using the catalog in the same cluster as Longhorn is running. This is where I can see it in the Legacy/Project section. I did not expect it was referring to the local cluster. I don`t know if the Rancher cluster is always named local but it could be added.

It seems your point is more about the cluster name on Rancher UI confusing you when the cluster is the same for upstream & downstream in your case. 

@PhanLe1010 What do you think @courcelm suggestion?

> 
> Yup the migration looks fine. Nothing broke yet. Hope the update to 1.3 will good smooth.

It's good to know it works well 👍

**Comment by PhanLe1010** [comment]
>  I don`t know if the Rancher cluster is always named local but it could be added.

It is not always local

> @PhanLe1010 What do you think @courcelm suggestion?

I modified the doc to mention that it is the kubeconfig file of the cluster on which the rancher instance is running on. Thank you
