### ISSUE TITLE
[FEATURE] Align with upstream K8s version support from Longhorn 1.4 and update component/pkg/build dependencies

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4239]
## What's the task? Please describe

For each feature release, we will revisit if need to bump the minimum support version of K8s and K8s dependent libraries based on different reasons like K8s support version cycle, the minimum versions of K8s used by CSI sidecar components planned to deliver/support, etc.  

https://kubernetes.io/releases/patch-releases/
At the moment, 1.25, 1.24, and 1.23 are actively maintained branches, and others will still have patch support except for [versions less and equal to 1.21, which are EOL](https://kubernetes.io/releases/patch-releases/#non-active-branch-history), so the base min version now is 1.22. 

## Describe the items of the task (DoD, definition of done) you'd like

- [x] Bump the recent versions of K8s-dependent libraries to the recently newer version given no backward compatibility concerns
- [x] Fix deprecated resources being used/removed from unsupported K8s versions https://github.com/longhorn/longhorn/issues/4003 (ex: https://github.com/longhorn/longhorn/issues/4490#issuecomment-1240400365)
- [x] Update the min version support of K8s
- [x] Update CSI sidecar versions
https://github.com/longhorn/longhorn-manager/pull/1518#discussion_r992824473 (release note required because snapshot API v1beta1 will be deprecated since 4.1. 
- [x] Update Golang version
- [x] Update the K8s version in e2e testing to the updated nearly K8s version @longhorn/qa

**Comment by innobead** [comment]
ref: #4003

**Comment by joshimoo** [comment]
Issues to solve for kubernetes 1.25 support:
PSP https://github.com/longhorn/longhorn/issues/4003
PDB https://github.com/longhorn/longhorn/issues/4689
Cronjob https://github.com/longhorn/longhorn/issues/3160#issuecomment-947007800

**Comment by innobead** [comment]
About removed deprecated versions, it will be tackled at https://github.com/longhorn/longhorn/issues/4003 together with PSP.

**Comment by PhanLe1010** [comment]
Test plan
(in-progress)

* Test generate support bundler generation 
* Test upgrade 
* Test zone and topology 
* Test uninstallation

**Comment by PhanLe1010** [comment]
Todo:
1. Upding docs:
    * github.com/container-storage-interface/spec v1.3.0
    * Min Kubernetes 1.21
    * User need to deploy new snapshot v1 CRD: `VolumeSnapshot v1beta1 is deprecated and will be removed in a future release. It is recommended for users to upgrade to VolumeSnapshot CRD version v1 as soon as possible. Any previously created invalid v1beta1 objects have to be deleted before upgrading to version 4.1.0. (https://github.com/kubernetes-csi/external-snapshotter/pull/493, @xing-yang)`
2. Verify CSI snapshot upgrade  
    * install Longhorn <= 1.3.2
    * Enable CSI Snapshot Support on a Cluster https://longhorn.io/docs/1.3.1/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/
    * Create some CSI snapshot https://longhorn.io/docs/1.3.1/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-snapshot/
    * Upgrade to Longhorn master
    * Upgrade the CSI snapshot CRDs to the version v5.0.1 here: https://github.com/kubernetes-csi/external-snapshotter/tree/v5.0.1/client/config/crd
    * Upgrade the CSI snapshot controller to the version v5.0.1 here: https://github.com/kubernetes-csi/external-snapshotter/tree/v5.0.1/deploy/kubernetes/snapshot-controller
    *  Create some new CSI snapshot https://longhorn.io/docs/1.3.1/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-snapshot/
    * Verify that everything is working as expected

**Comment by chriscchien** [comment]
**Case 1: within a Kubernetes version**
Verified on `v1.25.3+k3s1`

- [ ] Test basic recurring snapshot/backup jobs are working correctly
   - v1.25.3+k3s1  - Verified on local environment
   - [v1.24.7+k3s1](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2239/)
   - [v1.23.1+k3s2](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/292/testReport/tests/test_recurring_job/)
   - [v1.22.15+k3s1](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2238/)
   - [v1.21.10+k3s1](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2237/)

- [ ] Test generating support bundler generation. Make sure that the above jobs are in /yamls/kubernetes/cronjobs folder

  -  Verified manually
 
**Case 2: Test a Kubernetes version upgrade** - Pass

- [ ] Update from `v1.24.7+k3s1` to `v1.25.3+k3s1` and workload still working properly

1. Install Longhorn master in Kubernetes v1.24 cluster
2. Create some workload, Longhorn volumes, cronjobs, etc...
3. Upgrade Kubernetes to v.125
4. Verify that Longhorn is running ok. Basic functionality is working ok

**Comment by yangchiu** [comment]
Verified passed on master-head by following the [test plan](https://github.com/longhorn/longhorn/issues/4239#issuecomment-1272234979).

**(1-1) Test basic recurring snapshot/backup jobs are working correctly:** 
-   covered in (1-5) e2e test

**(1-2) Create recurring jobs and generate support bundle, make sure the corresponding recurring jobs are in /yamls/kubernetes/cronjobs folder:**

-   manually verified passed in [ v1.21.10+k3s1, v1.22.9+k3s1, v1.23.7+k3s1, v1.24.7+k3s1, v1.25.3+k3s1 ]

**(1-3) Test Longhorn upgrade from 1.2.x or 1.3.x to master + CSI snapshotter upgrade from release-4.0 to v5.0.1, make sure upgrade successfully, basic functionalities work, and CSI snapshot functionality works (following the test steps in the test plan):**

-   manually verified passed in [ v1.21.10+k3s1, v1.22.9+k3s1, v1.23.7+k3s1, v1.24.7+k3s1, v1.25.3+k3s1 ]

**(1-4) Test zone and topology (following the test steps in the test plan):**

-   manually verified passed in [ v1.21.10+k3s1, v1.22.9+k3s1, v1.23.7+k3s1, v1.24.7+k3s1, v1.25.3+k3s1 ]

**(1-5) Test uninstallation:**

-   manually verified passed in [ v1.21.10+k3s1, v1.22.9+k3s1, v1.23.7+k3s1, v1.24.7+k3s1, v1.25.3+k3s1 ]

**(1-6) e2e tests:**

-   [v1.21.10+k3s1](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2387/), [v1.22.9+k3s1](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2388/), [v1.23.7+k3s1](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2393/), [v1.24.7+k3s1](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2390/), [v1.25.3+k3s1](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2391/)

**(2) Test k8s version upgrade (following the test steps in the test plan):**

-   manually verified passed by upgrade k8s from v1.24 to v1.25
