### ISSUE TITLE
[QUESTION] longhorn-engine failing in k3s with error: "/data/longhorn: Permission denied"

### ISSUE THREAD

**Issue by meustrus** [longhorn/longhorn#4244]
## Question

I'm filing this as a question and not as a bug because this is my first time installing Longhorn so the most likely issue is user error, and I'm expecting I will need to add something to my setup to make it work.

I have installed longhorn by Helm chart in K3S using the Helm chart CRD (and I used Terraform to do it, but that probably isn't important). I have ingress configured and can see the nodes are up and running with `longhorn-manager`. However when I go to create a volume I get an error that there are no nodes running `longhorn-engine`. Looking at Kubernetes dashboard, the `engine` instances are failing to become `Ready` with the message: "Readiness probe failed: /data/longhorn sh: /data/longhorn: Permission denied". Pod logs just say "Installed".

What more can I look at to diagnose this issue? Is my volume configured incorrectly somehow? Did I miss a setup step somewhere?

## Environment

 - Longhorn version: Latest
 - Kubernetes version: K3S Latest
 - Node config
   - OS type and version: Debian 11
   - CPU per node: 2
   - Memory per node: 4gb
   - Disk type: XFS
   - Network bandwidth and latency between the nodes: I don't have numbers, but they are all running on the same physical server
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM

## Additional context

My basic setup is that I have multiple K3s nodes running inside KVM virtual machines provisioned with libvirt. The K3S nodes are running Debian 11. I have ensured that `nfs-common` and `open-iscsi` are both installed. Everything is running the latest version give or take a week. Each K3S VM has a 40gb XFS volume mounted at `/var/lib/longhorn`.

**Comment by mantissahz** [comment]
Hi @meustrus, what does getting pods of longhorn `kubectl -n longhorn-system get pod` show?
Are you running SELinux and firewalld?
Might be related to this [issue 1273](https://github.com/longhorn/longhorn/issues/1273).

**Comment by meustrus** [comment]
```
NAME                                           READY   STATUS    RESTARTS   AGE
longhorn-conversion-webhook-5dc58756b6-2rsjc   1/1     Running   0          24m
longhorn-ui-b7c844b49-tf4gv                    1/1     Running   0          24m
longhorn-conversion-webhook-5dc58756b6-nrxph   1/1     Running   0          24m
longhorn-admission-webhook-8b7f74576-l54c5     1/1     Running   0          24m
longhorn-admission-webhook-8b7f74576-mfcfs     1/1     Running   0          24m
longhorn-manager-j6r5r                         1/1     Running   0          24m
longhorn-manager-qcrmw                         1/1     Running   0          24m
engine-image-ei-df38d2e5-8c9tt                 0/1     Running   0          24m
instance-manager-e-4c7adf43                    1/1     Running   0          24m
engine-image-ei-df38d2e5-shcrx                 0/1     Running   0          24m
instance-manager-r-d017a1e9                    1/1     Running   0          24m
engine-image-ei-df38d2e5-ghv2c                 0/1     Running   0          24m
instance-manager-r-f5525b98                    1/1     Running   0          24m
instance-manager-e-8a701e38                    1/1     Running   0          24m
instance-manager-e-70b008c7                    1/1     Running   0          24m
instance-manager-r-57e84284                    1/1     Running   0          24m
longhorn-driver-deployer-6bd59c9f76-6gtml      1/1     Running   0          24m
longhorn-manager-nsdkk                         1/1     Running   0          24m
csi-attacher-7bf4b7f996-rr6q7                  1/1     Running   0          24m
csi-attacher-7bf4b7f996-zprmk                  1/1     Running   0          24m
csi-resizer-6d8cf5f99f-tj9vx                   1/1     Running   0          24m
csi-resizer-6d8cf5f99f-knlf5                   1/1     Running   0          24m
csi-provisioner-869bdc4b79-8z6db               1/1     Running   0          24m
csi-attacher-7bf4b7f996-kfftb                  1/1     Running   0          24m
csi-provisioner-869bdc4b79-vqxpg               1/1     Running   0          24m
csi-snapshotter-588457fcdf-k2wbf               1/1     Running   0          24m
csi-snapshotter-588457fcdf-d5cxf               1/1     Running   0          24m
csi-provisioner-869bdc4b79-rxg4g               1/1     Running   0          24m
csi-resizer-6d8cf5f99f-7kzlg                   1/1     Running   0          24m
csi-snapshotter-588457fcdf-drqpt               1/1     Running   0          24m
longhorn-csi-plugin-gjh6g                      2/2     Running   0          24m
longhorn-csi-plugin-bl4wh                      2/2     Running   0          24m
longhorn-csi-plugin-pjk4g                      2/2     Running   0          24m
longhorn-manager-jzzzd                         1/1     Running   0          22m
longhorn-csi-plugin-d5sb2                      2/2     Running   0          22m
engine-image-ei-df38d2e5-588vn                 0/1     Running   0          22m
instance-manager-e-93527ecc                    1/1     Running   0          22m
instance-manager-r-a712da67                    1/1     Running   0          22m
```

I'm not intentionally running SELinux or firewalld inside the k3s VM. I'm taking the default OpenStack release of Debian and using cloud-init to set up users, packages, volume mounts and file permissions, and start k3s. There is a firewall running on the physical host, but that's a layer removed from the network the VMs are actually connecting to.

**Comment by mantissahz** [comment]
It seams that all engine-image-ei pods are not ready, what are the output of `kubectl -n longhorn-system describe engine-image-ei-df38d2e5-ghv2c` and `kubectl -n longhorn-system logs engine-image-ei-df38d2e5-ghv2c`?

**Comment by meustrus** [comment]
I found my issue. I had `var/lib/longhorn` mounted with the `noexec` option, which is what was preventing it from running the engine binary. Longhorn appears to be working for me now. Thank you for your help!
