### ISSUE TITLE
[IMPROVEMENT] Recognize default toleration and node selector to allow Longhorn run on the RKE mixed cluster

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4246]
## Is your improvement request related to a feature? Please describe

When users install Longhorn on an RKE mixed cluster with Win nodes, users need to manually update the tolerations and node selector for user deployed components and the default settings for system-managed ones. 

However, RKE mixed clusters provisioned by Rancher will have some taint tolerations and node labels for Linux nodes, so it will be good to have an auto-recognized mechanism to allow Longhorn to install successfully w/o any manual intervention to provide a better user experience. 

## Describe the solution you'd like

https://github.com/rancher/rancher/issues/37030#issuecomment-1186876148

## Describe alternatives you've considered

As now, users just update those settings by themselves. 

## Additional context

https://github.com/rancher/rancher/issues/37030#issuecomment-1185787616

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by innobead** [comment]
@c3y1huang if having any questions, check with @PhanLe1010 . He has the whole context. Thanks.

**Comment by cchien816** [comment]
**Verified on longhorn `81a094`
Result Pass**

Steps
1. Deploy Rancher mixed cluster (1 Windows node, 3 Linux node)
2. Download kubeconfig from Rancher in exported to local
3. In local, clone https://github.com/longhorn/longhorn.git, create namespace `longhorn-system`
4. Change `windowsCluster` enable to `true` in chart/values.yaml
```
  windowsCluster:
      # Enable this to allow Longhorn to run on the Rancher deployed Windows cluster
      enabled: true
```
5. Run `helm install longhorn ./longhorn/chart -n longhorn-system`
6. Observed Longhorn deploy well

**Comment by c3y1huang** [comment]
@derekbit instead of reopening this, can you create another issue for the fix on the generated longhorn.yaml? 

cc @innobead

**Comment by innobead** [comment]
> @derekbit instead of reopening this, can you create another issue for the fix on the generated longhorn.yaml?
> 
> cc @innobead

Yeah, I think this is fair because this is not about function not working but rather a side-effect. Let's create an issue to track the fix and re-connect to this issue. @derekbit Could you help with that? Thanks!
