### ISSUE TITLE
Volumes take a long time to disconnect/connect so timeout errors

### ISSUE THREAD

**Issue by paulmorabito** [longhorn/longhorn#425]
Hi,

I'm using Longhorn 0.40 on Rancher 2.1.6. I also use Keel to update containers automatically.

Usually, any deployment with an attached Longhorn volume gives an error when Keel updates "REplicaSet has timed out progress..". When I look into the logs, there are timeout errors attaching the longhorn volume and sometimes volume not found errors. Within Longhorn, these volumes are listed as detached.

I sometimes get similar problems with restarting containers but as I am doing it manually, I can monitor these more closely.

I'm not running longhorn or my k8s cluster on fast hardware though this will soon change. However, is there any way to avoid these kinds of issues?

**Comment by yasker** [comment]
@paulmorabito Are you using Kubernetes 1.11 or 1.12? There was a bug in Kubernetes v1.11 and before can cause volume failed to attach (#267) if the workload changes quickly. If that's the case, you would see something like `MountVolume.WaitForAttach failed for volume "pvc-652a7f2a-aa56-11e8-ad33-001c42c2325f" : volumeattachments.storage.k8s.io "csi-ac63c8ac5d85e1e3347a4de29f9494490e5729518a7a83d55a48307c71acf7f7" not found` when `kubectl describe pod xxx`.

Otherwise, we would need to investigate what's going on. How long is the timeout normally?

**Comment by paulmorabito** [comment]
Yes, that's exactly what I am getting and I'm using Kubernetes 1.11.6.

How do I upgrade Kubernetes? does it upgrade alongside rancher?

**Comment by yasker** [comment]
See https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/editing-clusters/#upgrading-kubernetes

Also, remember to backup all Longhorn volumes in case something goes wrong during the upgrade. It's recommended to stop all the workloads (e.g. scale down to 0) using Longhorn before upgrading Kubernetes. After Kubernetes upgrade completed, you would need to delete the pod `longhorn-driver-deployer-xxx` in `longhorn-system` namespace to trigger the redeployment of the CSI driver, since CSI API changes between 1.11 and 1.12.

**Comment by paulmorabito** [comment]
I reduced the workloads to 0 and went to upgrade the cluster as described.
However, I don't have the option to upgrade the K8S version, I guess
because my cluster is listed as imported?

I followed the HA install so am a bit confused how this could be?

Is there any way to do this?

**Comment by paulmorabito** [comment]
I completed the upgrade using RKE. I deleted longhorn-driver-deployer and
now getting this:


Successfully assigned apps/beets-fcbcc7895-57x27 to 192.168.1.52 2 minutes
ago
Warning FailedAttachVolume AttachVolume.Attach failed for volume
"beets-config" : attachment timeout for volume beets-config 2 minutes ago
Warning FailedAttachVolume AttachVolume.Attach failed for volume
"beets-config" : rpc error: code = Aborted desc = The volume beets-config
is attaching 2 minutes ago
Normal SuccessfulAttachVolume AttachVolume.Attach succeeded for volume
"beets-config" 2 minutes ago
Warning FailedMount Unable to mount volumes for pod
"beets-fcbcc7895-57x27_apps(695cf9cf-3c91-11e9-a8e8-d050998bc684)": timeout
expired waiting for volumes to attach or mount for pod
"apps"/"beets-fcbcc7895-57x27". list of unmounted volumes=[beets-config].
list of unattached volumes=[beets-config beets-musiclibrary beets-downloads
default-token-wpfq7] a few seconds ago
Warning FailedMount MountVolume.MountDevice failed for volume
"beets-config" : driver name io.rancher.longhorn not found in the list of
registered CSI drivers a few seconds ago

**Comment by yasker** [comment]
Does the deployer pod recreated? You've deleted the pod, not the deployment, right?

**Comment by paulmorabito** [comment]
Yes and yes. I click on the pod, delete it and it redeploys a new pod
immediately. However, there is only one pod on one node. The other node
hasn't got a pod running on it. Is that ok?

**Comment by yasker** [comment]
Should be good. Can you send me a support bundles?

**Comment by paulmorabito** [comment]
How do I do that?

**Comment by yasker** [comment]
You can click `Generate Support Bundle` in the Longhorn UI, then send the zip file to my email listed on my profile.

**Comment by paulmorabito** [comment]
Sent to you now. Thanks.

**Comment by yasker** [comment]
@paulmorabito Alright, I think I know what's wrong.

Can you try following:
1. Scale down deployment `longhorn-driver-deployer` to 0. Wait for the pod to be shutdown. DO NOT delete this deployment.
2. Manually delete deployments `csi-attacher`, `csi-provisioner`, and daemonset `longhorn-csi-plugin`. Wait for them to complete deletion.
3. Scale up deployment `longhorn-driver-deployer` to 1 again.

The new mechanism we used in Longhorn v0.4.0 check for the driver's version for redeployment, but not Kubernetes version. So it didn't trigger the reconfiguration of the driver correctly. We will fix that in the next release. I've filed bug #426 to track this issue.

**Comment by paulmorabito** [comment]
That worked, thank you. Early indications are also that volumes are not timing out. I'll let you know if it occurs again.

**Comment by yasker** [comment]
@botzill can you show me the output of `kubectl describe pod xxxx`?

After that, you can try to scale down the deployment etc to 0 then scale back up to see if it works for you. 

Also, give examples a try https://github.com/rancher/longhorn#use-longhorn-with-kubernetes and let me know.

**Comment by botzill** [comment]
I did reinstall the longhorn, I try to install grafana with a single volume and here is what I get:

```
k describe po grafana-695fc8c659-46wzw
Name:               grafana-695fc8c659-46wzw
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               eloquent-bhaskara-c7r7/10.131.92.126
Start Time:         Tue, 12 Mar 2019 21:48:46 +0200
Labels:             app=grafana
                    pod-template-hash=695fc8c659
                    release=grafana
Annotations:        <none>
Status:             Pending
IP:
Controlled By:      ReplicaSet/grafana-695fc8c659
Init Containers:
  init-chown-data:
    Container ID:
    Image:         busybox:1.30.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      chown
      -R
      472:472
      /var/lib/grafana
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/lib/grafana from storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from grafana-token-xfztf (ro)
  download-dashboards:
    Container ID:
    Image:         appropriate/curl:latest
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      /etc/grafana/download_dashboards.sh
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/grafana/download_dashboards.sh from config (rw)
      /var/lib/grafana from storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from grafana-token-xfztf (ro)
  grafana-sc-datasources:
    Container ID:
    Image:          kiwigrid/k8s-sidecar:0.0.11
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:
      METHOD:  LIST
      LABEL:   grafana_datasource
      FOLDER:  /etc/grafana/provisioning/datasources
    Mounts:
      /etc/grafana/provisioning/datasources from sc-datasources-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from grafana-token-xfztf (ro)
Containers:
  grafana:
    Container ID:
    Image:          grafana/grafana:master
    Image ID:
    Ports:          80/TCP, 3000/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:3000/api/health delay=60s timeout=30s period=10s #success=1 #failure=10
    Readiness:      http-get http://:3000/api/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      GF_SECURITY_ADMIN_USER:      <set to the key 'admin-user' in secret 'grafana-secret'>      Optional: false
      GF_SECURITY_ADMIN_PASSWORD:  <set to the key 'admin-password' in secret 'grafana-secret'>  Optional: false
      GF_INSTALL_PLUGINS:          <set to the key 'plugins' of config map 'grafana'>            Optional: false
    Mounts:
      /etc/grafana/grafana.ini from config (rw)
      /etc/grafana/provisioning/dashboards/dashboardproviders.yaml from config (rw)
      /etc/grafana/provisioning/datasources from sc-datasources-volume (rw)
      /var/lib/grafana from storage (rw)
      /var/lib/grafana/dashboards/default from dashboards-default (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from grafana-token-xfztf (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      grafana
    Optional:  false
  dashboards-public:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      grafana-dashboards-public
    Optional:  false
  dashboards-default:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      grafana-dashboards-config
    Optional:  false
  storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  grafana
    ReadOnly:   false
  sc-datasources-volume:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  grafana-token-xfztf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  grafana-token-xfztf
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                    From                             Message
  ----     ------                  ----                   ----                             -------
  Warning  FailedScheduling        2m45s (x5 over 2m48s)  default-scheduler                pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
  Normal   Scheduled               2m45s                  default-scheduler                Successfully assigned default/grafana-695fc8c659-46wzw to eloquent-bhaskara-c7r7
  Normal   SuccessfulAttachVolume  2m31s                  attachdetach-controller          AttachVolume.Attach succeeded for volume "pvc-d7a52bc6-44ff-11e9-bd8d-3a4c59247849"
  Warning  FailedMount             109s (x2 over 2m11s)   kubelet, eloquent-bhaskara-c7r7  MountVolume.SetUp failed for volume "pvc-d7a52bc6-44ff-11e9-bd8d-3a4c59247849" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount             42s                    kubelet, eloquent-bhaskara-c7r7  Unable to mount volumes for pod "grafana-695fc8c659-46wzw_default(d7c0d595-44ff-11e9-bd8d-3a4c59247849)": timeout expired waiting for volumes to attach or mount for pod "default"/"grafana-695fc8c659-46wzw". list of unmounted volumes=[storage]. list of unattached volumes=[config dashboards-public dashboards-default storage sc-datasources-volume grafana-token-xfztf]
  Warning  FailedMount             33s (x6 over 96s)      kubelet, eloquent-bhaskara-c7r7  MountVolume.SetUp failed for volume "pvc-d7a52bc6-44ff-11e9-bd8d-3a4c59247849" : rpc error: code = Internal desc = exit status 1
```

**Comment by botzill** [comment]
And my volume is now in `Faulted` state:

![Screen Shot 2019-03-12 at 21 57 57](https://user-images.githubusercontent.com/4686040/54231816-ef1e1f00-4511-11e9-8665-d0684224ead0.png)

**Comment by yasker** [comment]
@botzill faulted state means the engine lost connections to all its replicas. 

What's the network connection between the nodes? You can send me the Support Bundle for checking. See my email in my profile.

**Comment by botzill** [comment]
@yasker I tried that example above and works OK, pods are created and PVC also created, nop with that. Not sure why grafana has isues with it.

**Comment by botzill** [comment]
@yasker I'm not using rancher service, it's my custom k8s cluster on DigitalOcean.

**Comment by yasker** [comment]
@botzill The support bundle generation link located at the bottom of the UI, you can use it as long as you're using Longhorn.

The failure of Grafana seems caused by the faulted volume, I can take a look at the support bundle (log) to check what the direct reason of volume became faulted.

**Comment by botzill** [comment]
OK, I removed grafana, installed again and now I see volume works OK. I did send you the bundle thought.

**Comment by botzill** [comment]
I did again, remove the pod and it was recreated and attached again. Seems that longhorn is behaving differently when you put your thought into it, maybe some kind of quantum behavior here?

**Comment by yasker** [comment]
@botzill 

lol... 

Btw, I got the bundle. From the log, it's just at the same moment, all three replicas reports error:

> 2019-03-12T19:49:50.913666058Z time="2019-03-12T19:49:50Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn\", Name:\"pvc-d7a52bc6-44ff-11e9-bd8d-3a4c59247849-e-b767df6f\", UID:\"d7df3653-44ff-11e9-bd8d-3a4c59247849\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"1085534\", FieldPath:\"\"}): type: 'Warning' reason: 'Faulted' Detected replica pvc-d7a52bc6-44ff-11e9-bd8d-3a4c59247849-r-153c1e72 (10.244.93.9) in error"
2019-03-12T19:49:50.997243259Z time="2019-03-12T19:49:50Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn\", Name:\"pvc-d7a52bc6-44ff-11e9-bd8d-3a4c59247849-e-b767df6f\", UID:\"d7df3653-44ff-11e9-bd8d-3a4c59247849\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"1085534\", FieldPath:\"\"}): type: 'Warning' reason: 'Faulted' Detected replica pvc-d7a52bc6-44ff-11e9-bd8d-3a4c59247849-r-f7195cce (10.244.62.17) in error"
2019-03-12T19:49:50.999821056Z time="2019-03-12T19:49:50Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn\", Name:\"pvc-d7a52bc6-44ff-11e9-bd8d-3a4c59247849-e-b767df6f\", UID:\"d7df3653-44ff-11e9-bd8d-3a4c59247849\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"1085534\", FieldPath:\"\"}): type: 'Warning' reason: 'Faulted' Detected replica pvc-d7a52bc6-44ff-11e9-bd8d-3a4c59247849-r-c4ff9b65 (10.244.91.2) in error"
2019-03-12T19:49:51.417949244Z time="2019-03-12T19:49:51Z" level=debug msg="Requeue longhorn/pvc-d7a52bc6-44ff-11e9-bd8d-3a4c59247849-r-153c1e72 due to conflict"
2019-03-12T19:49:51.41882289Z time="2019-03-12T19:49:51Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn\", Name:\"pvc-d7a52bc6-44ff-11e9-bd8d-3a4c59247849\", UID:\"d7c88bee-44ff-11e9-bd8d-3a4c59247849\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"1085539\", FieldPath:\"\"}): type: 'Warning' reason: 'Faulted' volume pvc-d7a52bc6-44ff-11e9-bd8d-3a4c59247849 became faulted"

The faulted state is normally caused by network interruption. We're working on v0.4.1 to add more logs to the error details.

Let me know if you encountered any other issues.

**Comment by botzill** [comment]
OK, great. Will keep an eye on next version. 

Thx!
