### ISSUE TITLE
[BUG] Volume detaching and attaching repeatedly while creating multiple snapshots with a same id

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4250]
## Describe the bug

Volume detaching and attaching repeatedly while creating multiple snapshots with a same id

## To Reproduce

1. Create a RWO volume
2. Create a snapshot via CSI
3. Somehow the external volume snapshot controller repeatedly request multiple snapshot creation with the same snapshot id
4. LH encounters error because the snapshot id is conflict with an existing snapshot, and then trigger error handling (rollback).
5. The rollback deleted the existing snapshot file and its meta file but didn't update the volume.meta.
6. The volume.meta is inconsistent with snapshot images/metas because of the error handling.

## Expected behavior

Volume should be still attached after rollback (error handling)

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
https://github.com/longhorn/longhorn/issues/3844

cc @PhanLe1010

**Comment by PhanLe1010** [comment]
Yeah, we might want to raise the priority for https://github.com/longhorn/longhorn/issues/3844 because this issue is also causing https://github.com/longhorn/longhorn/issues/4227

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-engine caf17d4) by following [the test steps](https://github.com/longhorn/longhorn/issues/3844#issue-1202627654).
