### ISSUE TITLE
[BACKPORT][v1.3.x][BUG] Replica stuck in buggy state with status.currentState is error and the spec.desireState is running

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4253]
Ref: https://github.com/longhorn/longhorn/issues/4197

**Comment by cchien816** [comment]
**Verified on longhorn v1.3.x head `eb186e`
Result Pass**

Test [steps](https://github.com/longhorn/longhorn/issues/4197#issuecomment-1193023991)
