### ISSUE TITLE
[BACKPORT][v1.2.x][BUG] Replica stuck in buggy state with status.currentState is error and the spec.desireState is running

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4254]
Ref: https://github.com/longhorn/longhorn/issues/4197

**Comment by yangchiu** [comment]
Verified passed on v1.2.x-head (longhorn-manager 5917653) by following https://github.com/longhorn/longhorn/issues/4197#issuecomment-1193023991.
