### ISSUE TITLE
[BACKPORT][v1.3.1][IMPROVEMENT] Replace the GCC allocator in liblonghorn with a more efficient memory allocator 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4265]
## What's the task? Please describe

https://github.com/longhorn/longhorn/issues/4136

**Comment by yangchiu** [comment]
**Test environment:**

machine: AWS c5d.2xlarge
test size: 80G
v1.3.x-head longhorn-manager version: 57c20a3

**Test Result:**

https://ci.longhorn.io/job/private/job/longhorn-benchmark-test/16/console

Bandwidth: KiB/s
Latency: ns

_(1) Replica count = 1_

  |   | IOPS |   | Bandwidth |   | Latency |  
-- | -- | -- | -- | -- | -- | -- | --
  |   | read | write | read | write | read | write
v1.3.0 | rand | 23,368 | 15,477 | 362,232 | 162,006 | 360,537 | 320,068
  | seq | 38,820 | 27,257 | 357,754 | 164,405 | 296,046 | 319,916
v1.3.x-head | rand | 24,275 | 15,638 | 362,238 | 161,390 | 343,980 | 304,498
  | seq | 40,081 | 27,575 | 399,427 | 163,796 | 279,971 | 303,989
Improvement | rand | 3.88% | 1.04% | 0% | -0.38% | 4.59% | 4.86%
  | seq | 3.25% | 1.17% | 11.65% | -0.37% | 5.43% | 4.98%

_(2) Replica count = 2_

  |   | IOPS |   | Bandwidth |   | Latency |  
-- | -- | -- | -- | -- | -- | -- | --
  |   | read | write | read | write | read | write
v1.3.0 | rand | 22,301 | 14,398 | 724,476 | 161,991 | 397,878 | 375,128
  | seq | 36,707 | 24,767 | 503,033 | 164,410 | 395,131 | 373,400
v1.3.x-head | rand | 23,760 | 14,556 | 724,526 | 161,999 | 381,960 | 352,950
  | seq | 37,742 | 25,202 | 532,462 | 164,420 | 380,859 | 352,385
Improvement | rand | 6.54% | 1.1% | 0.01% | 0% | 4% | 5.91%
  | seq | 2.82% | 1.76% | 5.85% | 0.01% | 3.61% | 5.63%

_(3) Replica count = 3_

  |   | IOPS |   | Bandwidth |   | Latency |  
-- | -- | -- | -- | -- | -- | -- | --
  |   | read | write | read | write | read | write
v1.3.0 | rand | 22,331 | 13,173 | 836,394 | 161,967 | 443,608 | 472,776
  | seq | 35,940 | 21,982 | 529,633 | 164,325 | 439,327 | 469,590
v1.3.x-head | rand | 22,927 | 13,297 | 878,596 | 161,754 | 421,266 | 427,169
  | seq | 36,415 | 21,766 | 474,454 | 164,215 | 421,265 | 431,184
Improvement | rand | 2.67% | 0.94% | 5.05% | -0.13% | 5.04% | 9.65%
  | seq | 1.32% | -0.98% | -10.42% | -0.07% | 4.11% | 8.18%

**Comment by innobead** [comment]
All looks (read/write) improved especially latency. Thanks, @yangchiu for the report. 

cc @derekbit @joshimoo
