### ISSUE TITLE
[BUG] longhorn-ui fails to start on RKE2 with cis-1.6 profile for Longhorn v1.3.0 with helm install

### ISSUE THREAD

**Issue by tannernt** [longhorn/longhorn#4266]
## Describe the bug

`longhorn-ui` pod fails to start when installing Longhorn v1.3.0 via helm with longhorn/longhorn:1.3.0 on RKE2 with cis-1.6 profile.

## To Reproduce

1. Create RKE2 cluster using the steps listed at https://docs.rke2.io/security/hardening_guide/
2. Install Longhorn v1.3.0 with longhorn/longhorn:1.3.0 helm chart
3. Pod for longhorn-ui stuck in `CreateContainerConfigError` status

Error
```
Error: container has runAsNonRoot and image has non-numeric user (nginx), cannot verify user is non-root (pod: "longhorn-ui-797b59f8c9-9vkbr_longhorn-system(b9235a2c-5ac7-401e-9203-72582198f214)", container: longhorn-ui)
```

## Expected behavior

Longhorn-ui for Longhorn v1.3.0 (using helm chart 1.3.0) should start up on RKE2 with cis-1.6 profile, just as it does for Longhorn v1.2.4  (using helm chart 1.2.4) .

## Log or Support bundle

N/A

## Environment

 - Longhorn version: v1.3.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: RHEL 7
   - CPU per node: 4
   - Memory per node: 16
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes: 5 Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS t3.xlarge
 - Number of Longhorn volumes in the cluster: 3

## Additional context

This appears to be a reoccurrence or at least similar to a previous [issue with RKE2 and cis-1.5 profile](https://github.com/longhorn/longhorn/issues/3658).

**Comment by innobead** [comment]
This is a regression caused by migrating the base image to BCI. 

@mantissahz Please help with this first and need to backport to 1.3.1. Thanks.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-ui 2059d38) by following [the test steps](https://github.com/longhorn/longhorn/issues/4266#issue-1313529953).
