### ISSUE TITLE
[BACKPORT][v1.3.x] upgrade: autofill replica storage IP 

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4268]
https://github.com/longhorn/longhorn-manager/pull/1411
https://github.com/longhorn/longhorn/issues/4213#issuecomment-1184955056

**Comment by cchien816** [comment]
**Verified on longhorn v1.3.x head `dbd99b`
Result Pass**

Steps

- Install LH v1.2.4 with 3 nodes
- Upgrade LH to v1.3.x head
- During upgrade, run command` kubectl delete node <node name>`
- Observe upgrade completed and the deleted node disappear in Longhorn UI
