### ISSUE TITLE
Can't connect to Scaleway Object Storage (S3) for backups

### ISSUE THREAD

**Issue by diegodorgam** [longhorn/longhorn#427]
Hi there, 

I'm trying to use Scaleway Object Storage as my S3 backup, but I keep getting some strange errors.
I've Followed the documentations about [Minio](https://github.com/rancher/longhorn/blob/master/docs/backup.md) and the result is this:

I've created a secret called `scaleway-secret`, like this:
```
apiVersion: v1
kind: Secret
metadata:
  name: scaleway-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: xxxx
  AWS_SECRET_ACCESS_KEY: xxxx
  AWS_ENDPOINTS: aHR0cHM6Ly9zMy5ubC1hbXMuc2N3LmNsb3Vk
  AWS_REGION: bmwtYW1z
```
which basically is the base64 to my configurations:
```
AWS_ACCESS_KEY_ID: xxxxx
AWS_SECRET_ACCESS_KEY: xxxxx
AWS_REGION: nl-ams
AWS_ENDPOINTS: https://s3.nl-ams.scw.cloud
```
> the keys were altered to preserve security

and with this secret created, I gave longhorn the following configs:
![captura de tela 2019-03-06 as 15 32 46](https://user-images.githubusercontent.com/12052193/53905693-ecaa5980-4027-11e9-9135-2678f814fc2b.png)

But when I click on the Backup menu it returns me this error:
```
error listing backups: error listing backup volumes: Failed to execute: /var/lib/rancher/longhorn/engine-binaries/rancher-longhorn-engine-v0.4.0/longhorn [backup ls --volume-only s3://bucket-name@nl-ams/], output time="2019-03-06T18:53:59Z" level=error msg="{\n\n}" pkg=s3 time="2019-03-06T18:53:59Z" level=error msg="Fail to list s3: AWS Error: InvalidURI Couldn't parse the specified URI. <nil>\n400 \n" pkg=s3 time="2019-03-06T18:53:59Z" level=error msg="AWS Error: InvalidURI Couldn't parse the specified URI. <nil>\n400 \n" AWS Error: InvalidURI Couldn't parse the specified URI. <nil> 400 , error exit status 1
```
![captura de tela 2019-03-06 as 15 56 46](https://user-images.githubusercontent.com/12052193/53905936-7bb77180-4028-11e9-9607-9d9663de611f.png)

 All configurations seems to be in order, I've even tried to take `https` off from the AWS_ENDPOINTS, but still got the same error.
Any ideas?

**Comment by yasker** [comment]
Can you try `s3://bucket-name@us-east-1/` ? I am not familiar with Scaleway but we're using standard AWS library to connect, so `nl-ams` in the URI may not be recognized by AWS.

**Comment by diegodorgam** [comment]
tryied,

got this: 
```
AWS Error: AuthorizationHeaderMalformed The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'nl-ams' <nil> 400 , error exit status 1
```
`nl-ams` is the region in scaleway s3 access.

**Comment by diegodorgam** [comment]
thanks @yasker 
will wait for further actions on this.

**Comment by yasker** [comment]
@diegodorgam is there a way we can get an access key/secret key pair for debugging purpose? You can contact me privately using the email listed on my profile.

**Comment by yasker** [comment]
@diegodorgam Can you try if `s3://bucket-name@nl-ams:/` works?

**Comment by roonie007** [comment]
@yasker `s3://bucket-name@nl-ams/longhorn/` it does not work, i tried it, we really need to fix this, we need it in our company.

**Comment by yasker** [comment]
@roonie007 Sorry we don't have access to Scaleway Object Storage. If it's possible, can you set up a test bucket for us and provide us with credentials so we can test and fix this? You can email the setup and credentials to `longhorn-support-bundle@rancher.com`.

**Comment by roonie007** [comment]
Yes I can, but the problem is that the same keys for the S3 gives you Full control over our account. since it's a support mail, many people can see and use the keys.

I can give them specifically to you, at least we know who is using them, is this ok for you ? or you can easily create an account and they will give you 500$ Credits .

**Comment by yasker** [comment]
@roonie007 Giving your original key to us wouldn't be a good idea if you cannot create another account/key pair. We can try to create an throwaway account instead if it's in fact free to do so.

**Comment by roonie007** [comment]
You have to signup using this Input

![image](https://user-images.githubusercontent.com/7860859/67158447-67ff1800-f338-11e9-8f96-53896e76fa75.png)

**Comment by roonie007** [comment]
@yasker Let me know if you need anything else.

**Comment by yasker** [comment]
@roonie007 It seems they require a mobile number and a credit card, which makes it hard for us to do. I've sent an email to `opensource@scaleway.com` to see if we can get a test account to help with this issue.

**Comment by roonie007** [comment]
@yasker okay, keep me updated, but i know they are super active on their slack : https://slack.online.net/ , and you can lookup for these 2 channels : 

* #object-storage
* #k8s

**Comment by roonie007** [comment]
@yasker , is there any news about the progress of this bug ?

**Comment by yasker** [comment]
@roonie007 I've reached out to them and Remy Leone replied. But they still require a credit card to open an account. This is just before the KubeCon last month, and I have no update since then.

I will try to follow up again.

**Comment by newtoncorp** [comment]
👋 
I've just tested a basic installation of longhorn to test the S3 integration, it works.

```
apiVersion: v1
kind: Secret
metadata:
  name: scw-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: XXX
  AWS_SECRET_ACCESS_KEY: XXX
  AWS_ENDPOINTS: aHR0cHM6Ly9zMy5mci1wYXIuc2N3LmNsb3Vk
  AWS_REGION: ZnItcGFy
```

```
aws s3 --profile par ls --recursive s3://zobity
2019-12-18 11:17:27        264 backupstore/volumes/10/e0/toto/backups/backup_backup-a0b7093f6e1c42b4.cfg
2019-12-18 11:17:27        171 backupstore/volumes/10/e0/toto/volume.cfg
```

```
backup target : s3://zobity@fr-par/
credential secret : scw-secret
```

I did this on the Paris region, but it should be the same for `nl-ams`.
The bucket has to be created in Scaleway's S3. Are you sure the bucket named `bucket-name` belongs to you ?

**Comment by yasker** [comment]
Thanks @newtoncorp ! Feel free to reopen the issue if it still doesn't work.
