### ISSUE TITLE
[BACKPORT][v1.3.x][IMPROVEMENT] Recognize default toleration and node selector to allow Longhorn run on the RKE mixed cluster

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4274]
https://github.com/longhorn/longhorn/issues/4246
https://github.com/longhorn/longhorn/pull/4262

**Comment by cchien816** [comment]
**Verified on longhorn v1.3.x head `190717`
Result Pass**

Steps

1. Deploy Rancher mixed cluster (1 Windows node, 3 Linux node)
2. Download kubeconfig from Rancher and exported to local
3. In local, clone https://github.com/longhorn/longhorn.git, switch to branch v1.3.x, create namespace `longhorn-system`
4. Change windowsCluster enable to `true` in chart/values.yaml
  ```
windowsCluster:
      # Enable this to allow Longhorn to run on the Rancher deployed Windows cluster
      enabled: true
```
5. Run helm install longhorn ./longhorn/chart -n longhorn-system
6. Observed Longhorn deploy well
7.  Run `helm uninstall longhorn -n longhorn-system`
