### ISSUE TITLE
[BUG] Longhorn volume stuck in deleting state

### ISSUE THREAD

**Issue by brianclemens** [longhorn/longhorn#4278]
## Describe the bug

I have a longhorn volume stuck in a "deleting" state , despite there being no references to it other than a volume.longhorn.io and snapshot.longhorn.io object for it. The PV / PVC for it no longer exists.

## To Reproduce

Unfortunately I can't be of help here. This issue occurred after rebooting the entire cluster.

## Expected behavior

The longhorn volume to finish deleting.

## Log or Support bundle

(support bundle sent to longhorn-support-bundle@rancher.com)

## Environment

 - Longhorn version: 1.3.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.24.2+k3s1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 0
 - Node config
   - OS type and version: Rocky Linux 8.6
   - CPU per node: AMD Ryzen 5 3600 6-Core Processor
   - Memory per node: 64 GB DDR4
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 1G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 22

**Comment by PhanLe1010** [comment]
We got the support bundle via email. Thanks

**Comment by PhanLe1010** [comment]
The existence of snapshot CR blocks the deletion of the volume CR.

Next question, why the snapshot CR was not deleted? Can you provide the snapshot name?

**Comment by PhanLe1010** [comment]
TODO for Longhorn team: the support bundle doesn't collect the snapshot yamls

**Comment by PhanLe1010** [comment]
Thanks @brianclemens 

You can unblock the flow by running `kubectl edit snapshots.longhorn.io -n longhorn-system dfc1e4ba-0ed5-4531-adb9-57909d8ecc97` and remove the finalizer 
```
  finalizers:
    - longhorn.io
```

**Comment by PhanLe1010** [comment]
This is a Longhorn bug. 

**Reproducing steps:**
1. Create a volume and attach it
2. Create a Longhorn snapshot, snap-xxx
3. Delete the snap-xxx by `kubectl delete snapshots.longhorn.io -n longhorn-system snap-xxx`
4. Detach the volume
5. Wait for 30s
6. Delete the volume
7. See that the volume is stuck in deleting forever

**Root cause:**
The snapshot controller doesn't enqueue the snapshot when volume is deleted

**Workaround:**
manually remove the Longhorn finallizer `longhorn.io` as the example https://github.com/longhorn/longhorn/issues/4278#issuecomment-1198707704

**Comment by innobead** [comment]
@PhanLe1010 We need to add this to https://github.com/longhorn/longhorn/wiki/Known-Issues-of-Feature-Releases for the post-release notice.

**Comment by PhanLe1010** [comment]
> @PhanLe1010 We need to add this to https://github.com/longhorn/longhorn/wiki/Known-Issues-of-Feature-Releases for the post-release notice.

Seems that you already updated it. Thanks

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager bd383f9) by following [the test steps](https://github.com/longhorn/longhorn/issues/4278#issuecomment-1198709378).

**Comment by 2fst4u** [comment]
I'm getting this too. I realise you've pushed a bug fix but just curious, will this fix retrospectively resolve this issue for volumes stuck deleting without needing to manually intervene? If the only issue is a UI annoyance then I might just leave it be on my cluster until the fix come out.
