### ISSUE TITLE
[BACKPORT][v1.3.1][BUG] Volume detaching and attaching repeatedly while creating multiple snapshots with a same id 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4279]
## Describe the bug

https://github.com/longhorn/longhorn/issues/4250

## To Reproduce

3. Perform '....'

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by yangchiu** [comment]
Verified passed on v1.3.x-head (longhorn-engine bae383f) by following https://github.com/longhorn/longhorn/issues/3844#issue-1202627654.

Try to create snapshots with the same id would be forbidden by server error instead cause volume detaching/attaching repeatedly.
