### ISSUE TITLE
[BUG]  the IP address is duplicate when using storage network and the second network is contronllerd by ovs-cni.

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#4281]
## Describe the bug

[PR176](https://github.com/longhorn/longhorn-engine/pull/716#issue-1299602110)

## To Reproduce

3. Perform '....'

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
This should be better covered in the unit tests. 

I don't think this is easier to test by QA and it's straightforward. Let's just close and follow up on the testing from the e2e.
