### ISSUE TITLE
[BUG] build longhorn-ui image error

### ISSUE THREAD

**Issue by smallteeths** [longhorn/longhorn#4283]
## Describe the bug

build longhorn-ui image error

## To Reproduce

1. git clone  longhorn-ui
2. make

<img width="1220" alt="截屏2022-07-26 下午1 47 41" src="https://user-images.githubusercontent.com/27733391/180932832-a9869748-24f4-4b4b-a397-55aa1123831c.png">

## Expected behavior

Build success

**Comment by innobead** [comment]
cc @mantissahz

**Comment by mantissahz** [comment]
Yeah, that's what I encountered.

**Comment by innobead** [comment]
ref: https://github.com/xtuc/webassemblyjs/issues/1132

**Comment by innobead** [comment]
ref: https://github.com/longhorn/longhorn-ui/pull/522#issuecomment-1197856037

**Comment by innobead** [comment]
How to reproduce this issue? Please delete your local `package-lock.json` for reproducing, then rebuild by npm. Otherwise, npm will pick the locked versions in `package-lock.json` instead of packag.json, so you probably are unable to reproduce this.

**Comment by innobead** [comment]
This is a dev issue, closing to follow up with the e2e regression instead.
