### ISSUE TITLE
[BACKPORT][v1.3.x][BUG] longhorn-ui fails to start on RKE2 with cis-1.6 profile for Longhorn v1.3.0 with helm install

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#4287]
## Describe the bug

https://github.com/longhorn/longhorn/issues/4266

## Expected behavior

Longhorn-ui for Longhorn v1.3.0 (using helm chart 1.3.0) should start up on RKE2 with cis-1.6 profile, just as it does for Longhorn v1.2.4 (using helm chart 1.2.4) .

**Comment by cchien816** [comment]
**Verified on longhron UI v1.3.x head `78c62a`
Result Pass**

Test [steps](https://github.com/longhorn/longhorn/issues/4266#issue-1313529953)
Longhorn UI can deploy success on RKE2 cluster ( with cis-1.6 profile)
