### ISSUE TITLE
authentication problem layer 7 load balance

### ISSUE THREAD

**Issue by fedeostrit** [longhorn/longhorn#429]
hello, 
I have installed rancher v2.2-rc2 with my F5 big IP as load balancer layer 7 in my cluster of kubernetes, I also have deployed the longhorn v0.4 and chose the option loadbalance layer 7 to install it, the problem is that I access the URL published without asking me for authentication.
if I change the Rancher-proxy option I access Rancher's URL but I have to be authenticated in UI rancher.
Is it possible to add authentication and use LB layer 7 as being F5?

**Comment by yasker** [comment]
@fedeostrit 

Currently, we only support authenticate through Rancher UI (using rancher-proxy option) if you want authentication in Longhorn UI.

If you want to expose Longhorn UI directly to the load balancer, then we would need to add authentication to the Longhorn itself to support that. Or you can configure your LB pointed to the Longhorn endpoint behind the Rancher-proxy for now.
