### ISSUE TITLE
[BACKPORT][v1.3.x][BUG] Backing image is not deleted and recreated correctly

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4297]
https://github.com/longhorn/longhorn/issues/4256

**Comment by cchien816** [comment]
**Verified on longhorn v1.3.x head `eb186e`
Result Pass**

[Steps](https://github.com/longhorn/longhorn/issues/4256#issuecomment-1195390939) 

1. Follow reproduce steps, this error not happened
2. Run e2e `test_exporting_backing_image_from_volume` twice, the error not happened as well
