### ISSUE TITLE
Create a network check tool to help troubleshooting intermittent network connectivity

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#430]
Longhorn has high requirement on network latency and bandwidth. The unstable underlying network will result in Longhorn volume failure and it would be hard for users to know it's the underlying network issue or Longhorn storage issue.

As a first step, the tool should be separate from Longhorn, and can be used by the users to determine if the underlying network caused volume failure or not.

**Comment by yasker** [comment]
@dnauck @botzill

**Comment by ainiml** [comment]
I'm running longhorn over an S3 bucket

It launches and installs, creates volumes, creates PVs, but never attaches

I'm suspecting the sensitivity of latency, and a very short timeout (since Longhorn is expecting locally attached disks and paths)
