### ISSUE TITLE
[BACKPORT][v1.2.x][BUG] Newly created backup stays in InProgress when the volume deleted before backup finished

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#4300]
## Describe the bug

https://github.com/longhorn/longhorn/issues/3122

## To Reproduce

1. Setup the backup target
2. Create the volume
3. Write some data into the volume
4. Create a backup
5. Delete the volume right away

## Expected behavior

The unfinished backup item should display a different state after certain time or automatically clean up itself after showing a warning message.

**Comment by cchien816** [comment]
**Verified on Longhorn v1.2.x `92d58f`
Result Pass**
Test [steps](https://github.com/longhorn/longhorn/issues/3122#issuecomment-1196347937)

Delete volume which just started backup, the backup progress will not stuck anymore, instead, the backup creation state will display error and have message tell user fail reason when mouse move over to error creation state
