### ISSUE TITLE
[BUG] longhorn-manager deletes same pod multi times when rebooting

### ISSUE THREAD

**Issue by w13915984028** [longhorn/longhorn#4302]
## Describe the bug

In Harvester mater-head version, from the log of `longhorn-manager`, it shows that `longhorn-manager deletes same pod multi times`

```
time="2022-07-27T09:33:11Z" level=info msg="Deleted pod prometheus-rancher-monitoring-prometheus-0 so that Kubernetes will handle remounting volume pvc-076c7e6b-dd8c-4e92-b1ae-33fd6a262584" controller=longhorn-kubernetes-pod node=harv1
time="2022-07-27T09:33:11Z" level=info msg="Deleted pod prometheus-rancher-monitoring-prometheus-0 so that Kubernetes will handle remounting volume pvc-076c7e6b-dd8c-4e92-b1ae-33fd6a262584" controller=longhorn-kubernetes-pod node=harv1
time="2022-07-27T09:33:41Z" level=info msg="Deleted pod prometheus-rancher-monitoring-prometheus-0 so that Kubernetes will handle remounting volume pvc-076c7e6b-dd8c-4e92-b1ae-33fd6a262584" controller=longhorn-kubernetes-pod node=harv1
time="2022-07-27T09:34:06Z" level=info msg="Deleted pod prometheus-rancher-monitoring-prometheus-0 so that Kubernetes will handle remounting volume pvc-076c7e6b-dd8c-4e92-b1ae-33fd6a262584" controller=longhorn-kubernetes-pod node=harv1
time="2022-07-27T09:34:06Z" level=info msg="Deleted pod prometheus-rancher-monitoring-prometheus-0 so that Kubernetes will handle remounting volume pvc-076c7e6b-dd8c-4e92-b1ae-33fd6a262584" controller=longhorn-kubernetes-pod node=harv1
```

When rebooting, LH set `RemountRequestedAt` in `ReconcileVolumeState`,  which leads to `handlePodDeletionIfVolumeRequestRemount` calls `kc.kubeClient.CoreV1().Pods(pod.Namespace).Delete`

## To Reproduce

1. Install single-node Harvester cluster 
2. When all are OK, reboot the cluster
3. Check longhorn-manager log
4. 

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: V1.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Harvester integrated
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 5

```
harv1:~ # kk get pvc -A
NAMESPACE                  NAME                                                                                             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS           AGE
cattle-monitoring-system   alertmanager-rancher-monitoring-alertmanager-db-alertmanager-rancher-monitoring-alertmanager-0   Bound    pvc-141559a1-4fac-45a7-9492-284d26db302c   4Gi        RWO            longhorn               19h
cattle-monitoring-system   prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0           Bound    pvc-076c7e6b-dd8c-4e92-b1ae-33fd6a262584   50Gi       RWO            longhorn               6d14h
cattle-monitoring-system   rancher-monitoring-grafana                                                                       Bound    pvc-5c83fc1b-0161-4800-8015-3439bfa5c02e   2Gi        RWO            longhorn               6d14h



default                    vm1-disk-0-pdaad                                                                                 Bound    pvc-0cb2a4f4-ace8-4e8b-98d2-e39d3f348407   1Gi        RWX            longhorn-image-mpn84   21h
default                    vol-image-cirros-1                                                                               Bound    pvc-82f23654-7414-4b1b-9c35-b95739677229   1Gi        RWX            longhorn-image-mpn84   21h
```

**Comment by w13915984028** [comment]
It could also be summarized with https://github.com/harvester/harvester/issues/2013

**Comment by shuo-wu** [comment]
Longhorn needs to check the deletion timestamp before sending deletion requests:
https://github.com/longhorn/longhorn-manager/blob/4b03a736c96fe870ae9db1bd0970191b796b2f63/controller/kubernetes_pod_controller.go#L310-L338

**Comment by PhanLe1010** [comment]
> Longhorn needs to check the deletion timestamp before sending deletion requests:
https://github.com/longhorn/longhorn-manager/blob/4b03a736c96fe870ae9db1bd0970191b796b2f63/controller/kubernetes_pod_controller.go#L310-L338

By checking the deletion timestamp, it will just fix the multiple deletion log messages. (I agree with this fix)

However, the flow will remain the same because multiple deletion requests are collapsed into the first deletion https://github.com/kubernetes/kubernetes/issues/71494. So the behavior when volume crashes will remain the same.

**Comment by shuo-wu** [comment]
Sending deletion requests to the API server is time-consuming. Avoiding this resource waste operation is another benefit of the fix.

**Comment by w13915984028** [comment]
@PhanLe1010 my local verify code is as such, it has an additional print with `...., skip....`, from the log, we know there are 4 times of duplicated deleting are skipped.

@shuo-wu As you said, an APIServer call is a `long` operation, check the `DeletionTimestamp` is the general practice.

```
+       if pod.DeletionTimestamp != nil {
+               kc.logger.Infof("pod %v is being deleting, %v, skip", pod.GetName(), *pod.DeletionTimestamp)  // removed in formal commit
+               return nil
+       }
```

```
harv1:~ # kk logs -n longhorn-system  longhorn-manager-lxfh5 | grep prometheus-rancher-monitoring-prometheus-0
time="2022-08-02T07:13:02Z" level=info msg="to be deleted pod prometheus-rancher-monitoring-prometheus-0 tm1:2022-08-01 18:11:48 +0000 UTC" controller=longhorn-kubernetes-pod node=harv1
time="2022-08-02T07:13:02Z" level=info msg="Deleted pod prometheus-rancher-monitoring-prometheus-0 so that Kubernetes will handle remounting volume pvc-076c7e6b-dd8c-4e92-b1ae-33fd6a262584" controller=longhorn-kubernetes-pod node=harv1

time="2022-08-02T07:13:02Z" level=info msg="pod prometheus-rancher-monitoring-prometheus-0 is being deleting, 2022-08-02 07:13:32 +0000 UTC, skip" controller=longhorn-kubernetes-pod node=harv1
time="2022-08-02T07:13:32Z" level=info msg="pod prometheus-rancher-monitoring-prometheus-0 is being deleting, 2022-08-02 07:13:32 +0000 UTC, skip" controller=longhorn-kubernetes-pod node=harv1
time="2022-08-02T07:13:39Z" level=info msg="pod prometheus-rancher-monitoring-prometheus-0 is being deleting, 2022-08-02 07:13:32 +0000 UTC, skip" controller=longhorn-kubernetes-pod node=harv1
time="2022-08-02T07:13:41Z" level=info msg="pod prometheus-rancher-monitoring-prometheus-0 is being deleting, 2022-08-02 07:13:02 +0000 UTC, skip" controller=longhorn-kubernetes-pod node=harv1
```

**Comment by innobead** [comment]
@mantissahz Please help to do the testing before closing this issue. Thanks. 

cc @longhorn/qa

**Comment by mantissahz** [comment]
Verified passed on the single-node Harvester cluster (20220803)
- master-head
- v1.3.x-head
- v1.2.x-head
