### ISSUE TITLE
[BUG] test_setting_backing_image_auto_cleanup failed because the backing image file isn't deleted on the corresponding node as expected

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#4308]
## Describe the bug

`test_setting_backing_image_auto_cleanup` failed because the backing image file isn't deleted on the corresponding node as expected.

In `step 7.2` of `test_settings.test_setting_backing_image_auto_cleanup`, after `disable scheduling` on the node and `all the replicas are removed from the node` and the `BackingImageCleanupWaitInterval` is set to 1, it expects that the backing image file on the node should be deleted from `/var/lib/longhorn/backing-images`, but it didn't. The backing image file remains untouched on the node.   

## To Reproduce

Run regression test with pytest options: -k test_setting_backing_image_auto_cleanup

## Expected behavior

The related backing image file is removed.

## Log or Support bundle

https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/199/testReport/junit/tests/test_settings/test_setting_backing_image_auto_cleanup/

## Environment

 - Longhorn version: master/1.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by shuo-wu** [comment]
There are 2 issues leading to the test case failure:
1. [The cascading deletion of the backing image manager](https://github.com/longhorn/longhorn-manager/blob/5f533ab84701834337e91990b8d94f54b25e00a4/datastore/longhorn.go#L1638) would lead to the pod being deleted before [the file cleanup complete](https://github.com/longhorn/longhorn-manager/blob/5f533ab84701834337e91990b8d94f54b25e00a4/controller/backing_image_manager_controller.go#L266-L268). In other words, [the pod should be deleted manually](https://github.com/longhorn/longhorn-manager/blob/5f533ab84701834337e91990b8d94f54b25e00a4/controller/backing_image_manager_controller.go#L355) by the controller [after the file cleanup complete](https://github.com/longhorn/longhorn-manager/blob/5f533ab84701834337e91990b8d94f54b25e00a4/controller/backing_image_manager_controller.go#L342-L347).
2. The [backing image files inside the backing image directory will be removed first](https://github.com/longhorn/backing-image-manager/blob/86aed13e70eb65df08ae60caf064661b00ef3793/pkg/sync/sync_file.go#L358-L367), then [the directory itself](https://github.com/longhorn/backing-image-manager/blob/86aed13e70eb65df08ae60caf064661b00ef3793/pkg/manager/service.go#L157-L159). This means the directory removal may be delayed for 1 or 2 seconds. Hence the test case should wait for a while or add retried for [the directory removal validation](https://github.com/longhorn/longhorn-tests/blob/b5a5ce9c5bf3d305888a216f32b664c94d4258d2/manager/integration/tests/test_settings.py#L741-L742).

**Comment by innobead** [comment]
Need to backport to 1.3.x & 1.2.x.

**Comment by cchien816** [comment]
**Verified on longhorn-manager master head `4fa1cc`
Result Pass**

Test case `test_setting_backing_image_auto_cleanup` passed and after test case completed, no backing images files remained in `/var/lib/longhorn/backing-images/` on each node
