### ISSUE TITLE
[TEST] Fix failed test case test_engine_crash_for_restore_volume

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#4309]
## What's the test to develop? Please describe

Fix failed test case [test_engine_crash_for_restore_volume](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/194/testReport/junit/tests/test_ha/test_engine_crash_for_restore_volume_s3_/)

Manually run test steps the result were passed, so test script logic need to be modified let script can test on current product.

## Describe the items of the test development (DoD, definition of done) you'd like

- [x] Modify script
- [ ] Script run well on pipeline

## Additional context

N/A

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by yangchiu** [comment]
In the following lines of this test case:
```
# Check if the restore volume is auto reattached then continue
# restoring data.
crash_engine_process_with_sigkill(client, core_api, res_name)
wait_for_volume_detached(client, res_name)
res_volume = wait_for_volume_healthy_no_frontend(client, res_name)
```
After the engine process crashed, the volume would go through `detaching -> detached -> attaching -> attached` state transition immediately, but the volume stay in `detached` state too little time so the test code is unable to catch this `detached` state.
What the `detached` state the test code is actually waiting in the above code snippet is the `detached` state the volume eventually achieved after the restoration completed, so the following `wait_for_volume_healthy_no_frontend` will never succeed, since the volume would stay in `detached` state after restoration.

Another failed test case `test_engine_crash_for_dr_volume` could have the same issue.

**Comment by innobead** [comment]
Recently, we had this change (https://github.com/longhorn/longhorn-tests/blob/d3fdad5b8d7cab9d7399cbd8712340a89b937bf3/manager/integration/tests/common.py#L59-L59), this will make `wait_` uses less time (150 seconds + 1 second interval for each) to wait until the state is correct. 

Will this factor cause the test case failed?

**Comment by innobead** [comment]
> Recently, we had this change ([longhorn/longhorn-tests@`d3fdad5`/manager/integration/tests/common.py#L59-L59](https://github.com/longhorn/longhorn-tests/blob/d3fdad5b8d7cab9d7399cbd8712340a89b937bf3/manager/integration/tests/common.py#L59-L59)), this will make `wait_` uses less time (150 seconds + 1 second interval for each) to wait until the state is correct.
> 
> Will this factor cause the test case failed?

From @yangchiu 

the complete state transition would be like:
`detaching -> detached -> attaching -> attached -> restore -> detached`
the wait_for_volume_detached got the final detached, there is no more state transition after the final detached, so wait_for_volume_healthy_no_frontend never get its desired state

**Comment by cchien816** [comment]
> > Recently, we had this change ([longhorn/longhorn-tests@`d3fdad5`/manager/integration/tests/common.py#L59-L59](https://github.com/longhorn/longhorn-tests/blob/d3fdad5b8d7cab9d7399cbd8712340a89b937bf3/manager/integration/tests/common.py#L59-L59)), this will make `wait_` uses less time (150 seconds + 1 second interval for each) to wait until the state is correct.
> > Will this factor cause the test case failed?
> 
> From @yangchiu
> 
> the complete state transition would be like: `detaching -> detached -> attaching -> attached -> restore -> detached` the wait_for_volume_detached got the final detached, there is no more state transition after the final detached, so wait_for_volume_healthy_no_frontend never get its desired state

Yes it's the same issue, I have submitted another [PR](https://github.com/longhorn/longhorn-tests/pull/1038) for review

**Comment by cchien816** [comment]
https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/207/testReport/tests/test_ha/test_engine_crash_for_restore_volume_nfs_/

https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/207/testReport/tests/test_ha/test_engine_crash_for_dr_volume_nfs_/
