### ISSUE TITLE
[IMPROVEMENT] Upgrade-responder doesn't automatically pick up the new configMap

### ISSUE THREAD

**Issue by williamlin-suse** [longhorn/longhorn#4312]
## Is your improvement request related to a feature? Please describe

I set up upgrade-responder on my local k8s env (including InfluxDB / Upgrade Responder / Grafana) successfully.
1. (for upgrade-responder) helm upgrade --install my-upgrade-responder ./upgrade-responder/chart -f ./upgrade-responder-my-values.yaml
2. configMap for this upgrade-responder is created in k8s.
3. Add a new entry to the Versions in configMap.responseConfig in my yaml file, save it as new-upgrade-responder-my-values.yaml & applied it:
helm upgrade --install my-upgrade-responder ./upgrade-responder/chart -f ./new-upgrade-responder-my-values.yaml
4. configMap for this upgrade-responder is updated in k8s.
5. However, POST(/v1/checkupgrade) still gets the old Versions value without the new entry added in step 3

## Describe the solution you'd like

Could the helm chart automatically re-deploy the deployment so the upgrade-responder pods automatically pick up the new configMap?

## Describe alternatives you've considered

Manually kill the upgrade-responder pods one by one to reload the content of the updated configMap

## Additional context

N/A

**Comment by PhanLe1010** [comment]
The current [helm chart](https://github.com/longhorn/upgrade-responder/tree/master/chart) doesn’t automatically re-deploy the deployment so the upgrade-responder pod doesn’t automatically pick up the new configMap.

**Workaround**:
kill the upgrade-responder pod one by one to reload the content of the configmap

**Todo**:
https://sanderknape.com/2019/03/kubernetes-helm-configmaps-changes-deployments/

**Comment by joshimoo** [comment]
Just to elaborate on todays meeting, you can deal with this on the application side.
Since if a config map changes and it's used in volume mount mode, kubernetes will update the exposed config map file.
So the way to deal with this conceptually is a watch on the file, which triggers 
- a reload of the application config (if this is possible in your application type)
- a graceful shutdown of the application which will lead to a new pod

**Comment by innobead** [comment]
> Just to elaborate on todays meeting, you can deal with this on the application side. Since if a config map changes and it's used in volume mount mode, kubernetes will update the exposed config map file. So the way to deal with this conceptually is a watch on the file, which triggers
> 
> * a reload of the application config (if this is possible in your application type)
> * a graceful shutdown of the application which will lead to a new pod

just ref: https://github.com/cri-o/cri-o/blob/main/pkg/config/reload.go similar purpose.

**Comment by PhanLe1010** [comment]
@williamlin-suse The fix has been pushed. Can you give a try again? 
* Pull the new chart changes
* Update the response config 
* Verify that it is automatically reloaded by the server
