### ISSUE TITLE
[BUG][BACKPORT][v1.3.x] The last healthy replica may be evicted or removed

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4313]
https://github.com/longhorn/longhorn/issues/4238

**Comment by yangchiu** [comment]
Verified passed on v1.3.x-head (longhorn-manager ea60591) by manually executing `test_disk_eviction_with_node_level_soft_anti_affinity_disabled` and if trying to delete the last healthy replica, error message would show and the deletion operation would be blocked.
