### ISSUE TITLE
[TEST] jenkins pipeline ubuntu 22.04 error

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#4320]
## What's the test to develop? Please describe

jenkins pipeline ubuntu 22.04 get the following error:

```
Error: remote-exec provisioner error

  with null_resource.rsync_kubeconfig_file[0],
  on k3s_instaces.tf line 104, in resource "null_resource" "rsync_kubeconfig_file":
 104:   provisioner "remote-exec" {

timeout - last error: SSH authentication failed (ubuntu@107.21.217.62:22):
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none
publickey], no supported methods remain
```

The AMI ID is `ami-051dcca84f1edfff1`
The Image name is `ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220712.1
`

**Comment by utegental** [comment]
@yangchiu that's probably just Ubuntu-related issue. Canonical planned and disabled old authentication methods for ssh in 22.04. You just need to reenable them, if You need.

**Comment by yangchiu** [comment]
@utegental Thank you for the information!

**Comment by yangchiu** [comment]
reference: https://github.com/hashicorp/packer/issues/11656

**Comment by innobead** [comment]
ref: https://askubuntu.com/a/1409528
