### ISSUE TITLE
[QUESTION] How to add new raw disk ?

### ISSUE THREAD

**Issue by esakarya** [longhorn/longhorn#4321]
## Question
i added to new disk to a node, its now raw. another CSI solutions see it and applying.
but longhorn doesnt see raw disks, what next after adding disk to node ?

## Environment

 - Longhorn version: 1.3
 - Kubernetes version: RKE2
 - Node config
   - OS type and version Ubuntu 20.4 LTS
   - Disk type RAW

**Comment by shuo-wu** [comment]
You can check this doc for more details: https://longhorn.io/docs/1.3.0/volumes-and-nodes/multidisk/
