### ISSUE TITLE
[BUG] ReadWriteMany migratable volume write permission error

### ISSUE THREAD

**Issue by esakarya** [longhorn/longhorn#4323]
## Describe the bug

I have created one  migratable volume with ReadWriteMany access mode,

and when i try write somethink to this volume from pod its generating following error, with all paths

but when i change access mode to ReadWriteOnce its write without any error.

`exit status 255: { stdout: \"\", stderr: \"error: could not lock config file /tmp/.gitconfig: Permission denied\" }"}`

**Comment by joshimoo** [comment]
cc @innobead don't use migratable rwx volumes, they are not build for general purpose usage. It's a specific feature for harvesters/kubevirts live virtual machine migration.

If you only need access on a single node at a time, you can use a regular RWO volume and it will do failover etc correctly.
If you require access from different nodes concurrently you will need to use a RWX volume which utilizes NFS under the hood to ensure consistency on the FS.

**Comment by esakarya** [comment]
My container replica is 3. its storing file data .  With rwo first replica can attach. Another ones stuck error.

And i need mount this volume multiple pods. i cant succes since 4 days, how can do it? Please suggest to me

**Comment by joshimoo** [comment]
@esakarya if you can ensure the replicas are on the same NODE you can use **RWO**.
If you need them on different NODES you will need to use **RWX** with migratable = false.

Ensure you have the nfs prereq installed/deployed, https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/prerequisite/longhorn-nfs-installation.yaml

**Comment by esakarya** [comment]
Replicas in different nodes, i understand, i will use nfs with migratable false but. i am really not sure how i can describe a nfs volume and add it to longhorn, and use for storagr class, can u share any docs to me? i am newbie

**Comment by joshimoo** [comment]
@esakarya no problem, the nfs part is handled automatically behind the scenes by longhorn.
https://longhorn.io/docs/1.3.0/advanced-resources/rwx-workloads/

1) `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/prerequisite/longhorn-nfs-installation.yaml`

2) Check your `longhorn` storage class to ensure that `migratable` is not set to true.
3) the rwx test below utilizes `longhorn` storage class if you have a specific one just rename the storage class in the pvc section of the example.
4) `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml`

**Comment by esakarya** [comment]
Thank you i will try morning. is need Part of nginx service ?
