### ISSUE TITLE
[IMPROVEMENT][BACKPORT][v1.3.x] Support bundle doesn't collect the snapshot yamls 

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4326]
Ref: https://github.com/longhorn/longhorn/issues/4285

**Comment by yangchiu** [comment]
Verified passed on v1.3.x-head (longhorn-manager 4d259d5) by following the test steps:

(1) Create/attach a 150 volumes
(2) Create a new recurring snapshot jobs that select all volume, take snapshot every minute, and retain 50 snapshots
(3) Wait for 51 minutes
(4) Generate a support bundle, and there is no errors when generating the support bundle
(5) Verify the content of snapshots.yaml in /yaml/longhorn
