### ISSUE TITLE
[QUESTION]  ReadWriteOnce mode attach failed, for new creating pod

### ISSUE THREAD

**Issue by esakarya** [longhorn/longhorn#4327]
I have one deployment working with 1 replica.
If pvc ReadWriteMany is running in access mode, it is using nfs, nfs is also affecting performance.
When I create it in ReadWriteOnce mode, there is no problem in speed, but when the pod fails and recreates, the volume does not connect again, it gives an error that was previously connected (terminating pod), and this cycle repeats constantly.

How can I avoid this error in ReadWriteOnce mode?

**Comment by esakarya** [comment]
if i set strategy:Recreate for deployment, its waiting node be ready, its doesnt work if node is down...
any suggestion ?

**Comment by joshimoo** [comment]
Read this part of the documentation and see if this helps for the down node case:
- https://longhorn.io/docs/1.3.0/high-availability/node-failure/
- https://longhorn.io/docs/1.3.0/references/settings/#pod-deletion-policy-when-node-is-down
