### ISSUE TITLE
[BUG] All volumes down since upgrade to 1.3.0

### ISSUE THREAD

**Issue by mateuszdrab** [longhorn/longhorn#4331]
## Describe the bug

After upgrading from 1.2.4 to 1.3.0, all volumes are failing to attach/detach.

On the longhorn-manager pod, the following type of errors repeatedly logged, not sure if this is why it fails.

```time="2022-07-31T15:21:39Z" level=warning msg="disk data {/mnt/docker/longhorn/ true false 5368709120 [dedicated ssd]} is mismatched with collected data &{/mnt/docker/longhorn/ true 0xc004ac07e0 5fdbf9d6-9c8b-486f-be36-eabebbca6777 <nil> map[pvc-137df5a3-a5fe-4913-bb47-af3845e3db4b-2d46a7a0: pvc-170948af-5a25-45b2-919a-a8cfc875f9a5-109f1658: pvc-df40afc8-b7b9-4139-ad7d-689789e58a3b-0d14b0fd: pvc-e0ab96fc-4887-446c-912e-43c835ff08e3-45dd3a6c:]} for disk docker-volume"```

I'm quite curious about the collected data mentioning 0xc004ac07e0 where I expected a false, and then returning nil where it looks it should have been the labels of the disk.

```Dropping Longhorn replica longhorn-system/pvc-52501a21-2046-4be3-a045-6ed0ae043146-r-ffb234a2 out of the queue" controller=longhorn-replica error="fail to sync replica for longhorn-system/pvc-52501a21-2046-4be3-a045-6ed0ae043146-r-ffb234a2: failed to get instance manager for instance pvc-52501a21-2046-4be3-a045-6ed0ae043146-r-ffb234a2: cannot find the only available instance manager for instance pvc-52501a21-2046-4be3-a045-6ed0ae043146-r-ffb234a2, node zz, instance manager image rancher/mirrored-longhornio-longhorn-instance-manager:v1_20220611, type replica" node=zz```

In the UI, all volume instance managers are stopped.

Some instance managers upgraded, some did not.

![image](https://user-images.githubusercontent.com/26556541/182033487-ecf425ba-6beb-472e-bb6a-64316d2060f6.png)

All of the 13 volumes I have are on non-default disks in longhorn.

I created a test PVC which was bound and the newly bound PV immediately failed to mount, was found in detaching state right after.

## Log or Support bundle

Please provide a secure link to upload.

## Environment

 - Longhorn version: 1.3.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):  Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 10
 - Node config
   - OS type and version: Ubuntu 20.04 latest patches
   - CPU per node: Varies
   - Memory per node: 4 - 16GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: N/A
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 13

**Comment by derekbit** [comment]
@mateuszdrab 
It hits the known issue, you can find the workaround from here https://github.com/longhorn/longhorn/issues/4143.
This issue will be fixed in upcoming v1.3.1 as well.

**Comment by mateuszdrab** [comment]
> @mateuszdrab 
> It hits the known issue, you can find the workaround from here https://github.com/longhorn/longhorn/issues/4143.
> This issue will be fixed in upcoming v1.3.1 as well.

Thanks, sounds like a critical bug.
Is there an ETA for v1.3.1?

**Comment by derekbit** [comment]
> Thanks, sounds like a critical bug.
> Is there an ETA for v1.3.1?

It will be released soon.
Currently, you can delete the evicted disks temporarily following the steps in the workaround.

**Comment by mateuszdrab** [comment]
I tried the workaround at https://github.com/longhorn/longhorn/issues/4143#issue-1276280630

Unfortunately, for me all disks are stuck in a transient state so I can't even click delete in the UI.

![image](https://user-images.githubusercontent.com/26556541/182038265-49cf00e6-09c5-4957-96b8-cd6d2463ba31.png)

**Comment by derekbit** [comment]
What does this `all disks are stuck in a transient state` mean?
I think you can follow the workaround.case2, and then wait for a while.
If the depoyment is finished, the longhorn will go back to normal.
If no, you can send us the support bundle and we will check it.

**Comment by mateuszdrab** [comment]
> What does this `all disks are stuck in a transient state` mean?
> I think you can follow the workaround.case2, and then wait for a while.
> If the depoyment is finished, the longhorn will go back to normal.
> If no, you can send us the support bundle and we will check it.
> 

I mean the disks are stuck in attaching/detaching mode so I can't even click delete in the web UI. I tried case 2 of the workaround but since I don't submit a delete it makes no difference.

Is there a dev image of the affected component that I can run with the fix included?

**Comment by derekbit** [comment]
@mateuszdrab 
I got your point. Looks you might misunderstand the volumes and disks.
The disks I mentioned in the workaround is the nodes' disks rather than the volumes. You don't have to delete the volumes in the workaround.

![image](https://user-images.githubusercontent.com/12527233/182104168-415c4489-bf6e-402b-a8c3-a71078270d7f.png)

![image](https://user-images.githubusercontent.com/12527233/182104253-146b3564-dc57-43e1-91e5-82e6f9c97e18.png)

**Comment by mateuszdrab** [comment]
Ahh, so delete the disk and re-add it? Got you.
My brain was not working well yesterday... 🤯

**Comment by derekbit** [comment]
Just follow the workaround and deleting the **evicted disks** rather than all disks. Hope it works ;)

**Comment by mateuszdrab** [comment]
> Just follow the workaround and delete the **evicted disks** (the disks whose `Eviction Requested` is `true`) rather than all disks. Hope it works ;)

I think it's all good now. I had all the default disks set to schedulable as false and eviction requested as true.
The moment I disabled eviction request for those, everything started to work. I was able to leave those disks disabled still.

**Comment by derekbit** [comment]
@mateuszdrab 
Thank you for the update.
Free to open it if there is any update.
