### ISSUE TITLE
[IMPROVEMENT] Avoid accidentally deleting engine images that are still in use

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4332]
## Is your improvement request related to a feature? Please describe

A engine image is protected from being accidentally deleted with `engineImage.status.refCount`. The `refCount` counts the volumes using the engine image, but it does not take the engines and replicas into account.

If the volume's engine image is updated to a new one, but the associated engines or replicas are still using the old one, the deletion of the old engine image is allowed because of the zero refcount. As a result of the deletion, the volume will enter an error state.

To prevent from the unexpected deletion, we can count the number of resources (volumes, engines and replicas) using the engine image rather than only the number of volumes.

## Describe the solution you'd like

Avoid accidentally deleting engine images that are still in use.
The engine image can't be deleted if there is resource, volume, engine or replica, using it. 

## Additional context

https://github.com/longhorn/longhorn/issues/4212

**Comment by derekbit** [comment]
Some test cases in the master-head branch failed because of the check of the refcount.
I will update the test cases first.
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1759/console

**Comment by innobead** [comment]
> Some test cases in the master-head branch failed because of the check of the refcount. I will update the test cases first. [ci.longhorn.io/job/private/job/longhorn-tests-regression/1759/console](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1759/console)

cc @longhorn/qa another good catch by our e2e

**Comment by innobead** [comment]
@derekbit remember to update longhorn/longhorn as well because the engineimage CRD have been changed.

**Comment by derekbit** [comment]
No prob. Thanks for the reminder.

**Comment by shuo-wu** [comment]
It seems that we need to update the integration tests as well. Some tests will check the refCount of engine images.

**Comment by innobead** [comment]
> It seems that we need to update the integration tests as well. Some tests will check the refCount of engine images.

@derekbit is working on that.

**Comment by cchien816** [comment]
**Verified on longhorn-manager master-head `4fa1cc`
Result Pass**

Steps
1. Deploy new engine image
2. Create 1 volume with 3 replicas by new engine image and attach it
3. Verify new engine image Reference Count = 5 (1 volume, 3 replica, 1 engine daemonset)
4. Modify volume replica count to 2, delete 1 replica from any node
5. Wait for a while, verify new engine image Reference Count = 4 (1 volume, 2 replica, 1 engine daemonset)
6. Delete new engine image, verify that this action failed `unable to delete engine image: unable to delete the engine image while being used`
7. Change engine image to default engine image
8. Verify new engine image Reference Count = 0
9. Verify new engine image can be deleted

Also e2e failed cases related to refCount change were all [fixed](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/206/#showFailuresLink)
