### ISSUE TITLE
[IMPROVEMENT] Show non-JSON error from backup store

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4336]
## Is your improvement request related to a feature? Please describe

Currently, we only show the JSON unmarshal error when it's not caused by the replica restore failure, We also need to show the non-JSON error from the backup store to get the complete cause.

```
[longhorn-manager-s9x7k longhorn-manager] time="2022-08-01T09:37:37Z" level=warning msg="failed to restore backup backup-3aca3032e7c1413b in engine monitor, will retry the restore later: proxyServer=10.42.0.214:8501 destination=10.42.0.214:10000: failed to restore backup s3://backupbucket@us-east-1/?backup=backup-3aca3032e7c1413b&volume=pvc-273ff3c9-7606-4ce6-a72f-c4b82302c1c8 to volume pvc-273ff3c9-7606-4ce6-a72f-c4b82302c1c8: cannot unmarshal the restore error, maybe it's not caused by the replica restore failure: invalid character 'v' looking for beginning of value" controller=longhorn-engine engine=pvc-273ff3c9-7606-4ce6-a72f-c4b82302c1c8-e-6c918c75 node=ip-10-0-1-113
```

## Describe the solution you'd like

Show non-JSON error when failed to unmarshal error from backupstore.

## Describe alternatives you've considered

`None`

## Additional context

`None`

**Comment by innobead** [comment]
This is an obvious internal fix, but remember to have a reason when closing the issue.
