### ISSUE TITLE
[BACKPORT][v1.3.1][IMPROVEMENT] Avoid accidentally deleting engine images that are still in use

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4338]
## Is your improvement request related to a feature? Please describe

https://github.com/longhorn/longhorn/issues/4332

**Comment by yangchiu** [comment]
Verified passed on v1.3.x-head (longhorn manager aaaf415) by following [the test steps](https://github.com/longhorn/longhorn/issues/4332#issuecomment-1204907125).
