### ISSUE TITLE
[BUG] Update to 1.3.0 failed after chart migration

### ISSUE THREAD

**Issue by courcelm** [longhorn/longhorn#4340]
## Describe the bug

Update to 1.3.0 is failing. Cannot patch CRD 

## To Reproduce

Update from 1.2.4 to 1.3.0 using the Rancher chart after the chart migration

## Expected behavior

Successful update.

## Log or Support bundle

helm upgrade --history-max=5 --install=true --namespace=longhorn-system --timeout=10m0s --values=/home/shell/helm/values-longhorn-crd-100.2.0-up1.3.0.yaml --version=100.2.0+up1.3.0 --wait=true longhorn-crd /home/shell/helm/longhorn-crd-100.2.0-up1.3.0.tgz
--
Mon, Aug 1 2022 10:00:04 am | checking 17 resources for changes
Mon, Aug 1 2022 10:00:04 am | Patch CustomResourceDefinition "backingimagedatasources.longhorn.io" in namespace
Mon, Aug 1 2022 10:00:04 am | Patch CustomResourceDefinition "backingimagemanagers.longhorn.io" in namespace
Mon, Aug 1 2022 10:00:04 am | Patch CustomResourceDefinition "backingimages.longhorn.io" in namespace
Mon, Aug 1 2022 10:00:04 am | Patch CustomResourceDefinition "backups.longhorn.io" in namespace
Mon, Aug 1 2022 10:00:04 am | Patch CustomResourceDefinition "backuptargets.longhorn.io" in namespace
Mon, Aug 1 2022 10:00:04 am | Patch CustomResourceDefinition "backupvolumes.longhorn.io" in namespace
Mon, Aug 1 2022 10:00:04 am | Patch CustomResourceDefinition "engineimages.longhorn.io" in namespace
Mon, Aug 1 2022 10:00:04 am | error updating the resource "engineimages.longhorn.io":
Mon, Aug 1 2022 10:00:04 am | cannot patch "engineimages.longhorn.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "engineimages.longhorn.io" is invalid: spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true
Mon, Aug 1 2022 10:00:04 am | Patch CustomResourceDefinition "engines.longhorn.io" in namespace
Mon, Aug 1 2022 10:00:04 am | Patch CustomResourceDefinition "instancemanagers.longhorn.io" in namespace
Mon, Aug 1 2022 10:00:04 am | Patch CustomResourceDefinition "nodes.longhorn.io" in namespace
Mon, Aug 1 2022 10:00:04 am | error updating the resource "nodes.longhorn.io":
Mon, Aug 1 2022 10:00:04 am | cannot patch "nodes.longhorn.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "nodes.longhorn.io" is invalid: spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true
Mon, Aug 1 2022 10:00:04 am | Patch CustomResourceDefinition "orphans.longhorn.io" in namespace
Mon, Aug 1 2022 10:00:04 am | Patch CustomResourceDefinition "recurringjobs.longhorn.io" in namespace
Mon, Aug 1 2022 10:00:04 am | Patch CustomResourceDefinition "replicas.longhorn.io" in namespace
Mon, Aug 1 2022 10:00:04 am | Patch CustomResourceDefinition "settings.longhorn.io" in namespace
Mon, Aug 1 2022 10:00:04 am | Patch CustomResourceDefinition "sharemanagers.longhorn.io" in namespace
Mon, Aug 1 2022 10:00:04 am | Patch CustomResourceDefinition "snapshots.longhorn.io" in namespace
Mon, Aug 1 2022 10:00:04 am | Patch CustomResourceDefinition "volumes.longhorn.io" in namespace
Mon, Aug 1 2022 10:00:04 am | error updating the resource "volumes.longhorn.io":
Mon, Aug 1 2022 10:00:04 am | cannot patch "volumes.longhorn.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "volumes.longhorn.io" is invalid: spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true
Mon, Aug 1 2022 10:00:04 am | Error: UPGRADE FAILED: cannot patch "engineimages.longhorn.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "engineimages.longhorn.io" is invalid: spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true && cannot patch "nodes.longhorn.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "nodes.longhorn.io" is invalid: spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true && cannot patch "volumes.longhorn.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "volumes.longhorn.io" is invalid: spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true

## Environment

 - Longhorn version: 1.3.0
 - Installation method Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE  1.21.9
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 9
 - Node config
   - OS type and version: Ubuntu 20.04 LTS
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 10

**Comment by derekbit** [comment]
@courcelm 
Please check the workaround in https://github.com/longhorn/longhorn/pull/4237#issue-1305563789.
This root cause is described in https://github.com/longhorn/longhorn/pull/4237#issuecomment-1195339461
Thanks.

**Comment by derekbit** [comment]
@courcelm 

You can try to edit the following CRDs and set spec.preserveUnknownFields to false.
kubectl -n longhorn-system edit crds nodes.longhorn.io -o yaml
kubectl -n longhorn-system edit crds volumes.longhorn.io -o yaml
kubectl -n longhorn-system edit crds engineimages.longhorn.io -o yaml

The root cause is described in https://github.com/longhorn/longhorn/pull/4237#issuecomment-1195339461.

**Comment by courcelm** [comment]
@derekbit 
Thanks for your assistance. This fixed errors and the update went well.

**Comment by PhanLe1010** [comment]
@derekbit @innobead Should we also update this file https://github.com/longhorn/longhorn-manager/blob/master/deploy/install/01-prerequisite/03-crd.yaml ? Is it still the source of Longhorn CRD?
