### ISSUE TITLE
[BACKPORT][v1.2.x][BUG] test_setting_backing_image_auto_cleanup failed because the backing image file isn't deleted on the corresponding node as expected

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4344]
https://github.com/longhorn/longhorn/issues/4308

**Comment by cchien816** [comment]
**Verified on longhorn v1.2.x head `5aa7a3`
Result Pass**

Test case `test_setting_backing_image_auto_cleanup` passed and after test case completed, no backing images files remained in `/var/lib/longhorn/backing-images/` on correspond node
