### ISSUE TITLE
Some volumes "stuck" in Detached state after failure of nodes

### ISSUE THREAD

**Issue by andrewheberle** [longhorn/longhorn#4353]
Longhorn Version: v1.3.0
K8s Version: v1.21.12 (RKE1)

We had an issue where all nodes in a particular zone crashed due to an underlying storage issue.

Unfortunately this problem didn't cause a total node failure for these two (2) worker nodes (this is 1/3 of the workers in the cluster), but triggered the node to remount it's filesystems read-only, so all sorts of things broke.

After resolving the underlying issue, one of the nodes came back fine, but the other would not boot so was removed from the cluster pending replacement.

At this point we now have seven (7) of the Longhorn volumes that seem to be stuck in a "Detached" state.

Each of these volumes is showing as having two replicas, instead of three, and will not attach manually to a node via the Longhorn UI and also will not attach in response to the workload being started.

All nodes in the cluster have been drained, rebooted and uncordoned again in case some Longhorn pod was crashed.

**Comment by derekbit** [comment]
@andrewheberle Can you check the longhorn-managers' log and provide us the error/warning messages?
