### ISSUE TITLE
[BUG] data corruption due to COW and block size not being aligned during rebuilding replicas 

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4354]
## Describe the bug

Data in the cloning volume sometime has mismatched checksum as the data in the source volume

## To Reproduce
Cloning a volume 100 times. Sometime, we can see this problem. Below is the steps to clone a volume 100 times

1. Deploy this [test pod](https://github.com/PhanLe1010/longhorn-tests/blob/4227/manager/integration/deploy/test.yaml) which contains [a function](https://github.com/PhanLe1010/longhorn-tests/blob/1ef3beb027f88d55c96026ee9ae92bef31861104/manager/integration/tests/test_csi_snapshotter.py#L780-L886) that repeatedly clone a volume 100 times and compare the checksum of data
2. exec into the test pod and run `pytest -svvl test_csi_snapshotter.py::test_csi_snapshot_snap_create_volume_from_snapshot_2`
    ```
    test_csi_snapshotter.py::test_csi_snapshot_snap_create_volume_from_snapshot_2 run number: 0
    run number: 1
    run number: 2
    run number: 3
    run number: 4
    run number: 5
    run number: 6
    run number: 7
    run number: 8
    run number: 9
    run number: 10
    run number: 11
    run number: 12
    run number: 13
    run number: 14
    run number: 15
    FAILED
    >           assert expected_md5sum == created_md5sum
    E           AssertionError: assert '4f4451eb7ed3915e9e7cecabdcb84b90\n' == 'e281b2d2b6de757c34bf5460de97ebb7\n'
    E             - 4f4451eb7ed3915e9e7cecabdcb84b90
    E             + e281b2d2b6de757c34bf5460de97ebb7
    ```

## Expected behavior

Checksum should always be the same

## Environment
Env was created by using this [terraform script](https://github.com/longhorn/longhorn-tests/tree/master/test_framework/terraform/aws/sles) with customized values:
```
use_hdd = true
arch = "amd64"
lh_aws_instance_type_controlplane = "t2.xlarge"
lh_aws_instance_type_worker = "t2.xlarge"
```
 - Longhorn version: master-head Aug 02, 2022

**Comment by innobead** [comment]
cc @shuo-wu @derekbit @joshimoo

**Comment by joshimoo** [comment]
@innobead @derekbit @shuo-wu this is the issue I was thinking about in regard to dereks snapshot data missmatch issue.
This might potentially be related if it's indeed true that different replicas snapshots might contain different data at point in time T.

**Comment by PhanLe1010** [comment]
Update from new rounds of testing: this issue doesn't happen for SSD (cloning 100 times ok). It happen for HDD (checksum mismatch at the 15-16th clone)

**Comment by PhanLe1010** [comment]
| OS  | Disk Type  | Result  | Additional Info  | 
|---|---|---|---|
| Ubuntu | SSD | ✅ | Cloning 200 times |  
| Ubuntu | HDD | ✅ |  Cloning 50 times since it take very long time on HDD |  
| Sles | SSD | ✅ | Cloning 200 times  |  
| Sles | HDD | ❌ | Cloning 2-16 times  |

**Comment by PhanLe1010** [comment]
cc @derekbit @shuo-wu @innobead  @joshimoo ^^

**Comment by shuo-wu** [comment]
Some suggestions for further testing and investigation:
1. Use version v1.2.4 to avoid the potential impact of feature snapshot pruning (which is available since v1.2.5).
2. Does Longhorn need to do a clone for the reproducing? As we discussed before, the direct cause is rebuilding.

**Comment by joshimoo** [comment]
Great job on the investigation and testing so far.
Below are some ideas to help narrow down the root cause.

- check if this is a regression by testing with prior version
- check the delta between the 2 head files 
-- off by one io/extent (either during merge of the snapshot files or read write modify)
-- continuously wrong over time
-- byte level error vs extent/io error
-- did the error happen at the beginning shortly after rebuild or at the end while flushing
- since the revision counter is identical one can assume that the replica.Write was called an equal amount
- try to reproduce this with a raw block dev, then write a known data pattern over it
-- this allows you to identify the exact point of failure via the diff

**Comment by PhanLe1010** [comment]
### Reproducing steps:

**Mounting script:**
```
DEV=/dev/longhorn/<volume-name>
for i in {1..20000}
  do
    echo $i
    date
    umount /mnt
    mount "$DEV" /mnt
    if [ $? != 0 ]; then
      exit 1
    fi
    sleep 0.1
  done
```

Deploy any Longhorn version < master

**Case 1:** ext4 filesystem with 1024 byte block size
1. Create a Longhorn volume of 1 replica 1GB.
1. Attach it to a node
1. Format the block device `mkfs.ext4 /dev/longhorn/<volume-name> -b 1024` 
1. Run the above `mounting script` with the correct block device
1. Scale up the number of replicas from 1 to 2
1. Verify that the filesystem is broken (if not, delete a replica to trigger rebuilding. It should happen after 2-3 rebuilding)

**Case 2:** xfs filesystem with 512 byte block size
1. Create a Longhorn volume of 1 replica 1GB.
1. Attach it to a node
1. Format the block device `mkfs.xfs /dev/longhorn/<volume-name>` 
1. Check the xfs filesystem and make sure that the meta data blocksize is 512 bytes. E.g.:
    ```
    ip-10-0-2-15:/ # xfs_info /dev/longhorn/testvol2
    meta-data=/dev/longhorn/testvol2 isize=512    agcount=4, agsize=32000 blks
             =                       sectsz=512   attr=2, projid32bit=1
             =                       crc=1        finobt=1, sparse=0, rmapbt=0
             =                       reflink=0
    data     =                       bsize=4096   blocks=128000, imaxpct=25
             =                       sunit=0      swidth=0 blks
    naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
    log      =internal log           bsize=4096   blocks=855, version=2
             =                       sectsz=512   sunit=0 blks, lazy-count=1
    realtime =none                   extsz=4096   blocks=0, rtextents=0
    ```
1. Run the above `mounting script` with the correct block device
1. Scale up the number of replicas from 1 to 2
1. Verify that the filesystem is broken (if not, delete a replica to trigger rebuilding. It should happen after 2-3 rebuilding)

**Case 3:** backing image with xfs filesystem with 512 byte block size
1. Create a backing image from URL `https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-2111.qcow2`
1. Create a Longhorn volume of 1 replica of 10GB with the above backing image
1. Attach it to a node
1. Find the major and minor version of the block device by `ls -l /dev/longhorn/<volume-name>`
1. Find the corresponding block device under `lsblk` with the same major and minor version. Then find the root partition of that block device
1. Check the xfs filesystem of the root partition and make sure that the meta data blocksize is 512 bytes. E.g.:
    ```
    ip-10-0-2-15:/ # xfs_info /dev/longhorn/testvol2
    meta-data=/dev/longhorn/testvol2 isize=512    agcount=4, agsize=32000 blks
             =                       sectsz=512   attr=2, projid32bit=1
             =                       crc=1        finobt=1, sparse=0, rmapbt=0
             =                       reflink=0
    data     =                       bsize=4096   blocks=128000, imaxpct=25
             =                       sunit=0      swidth=0 blks
    naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
    log      =internal log           bsize=4096   blocks=855, version=2
             =                       sectsz=512   sunit=0 blks, lazy-count=1
    realtime =none                   extsz=4096   blocks=0, rtextents=0
    ```
1. Run the above `mounting script` with the correct block device `/dev/.../<root-partition-name>`
1. Scale up the number of replicas from 1 to 2
1. Verify that the filesystem is broken (if not, delete a replica to trigger rebuilding. It should happen after 2-3 rebuilding)

### Testing steps:

Rerun the above steps with master-head and verify that you cannot corrupt the filesystem

**Comment by chriscchien** [comment]
Hi @PhanLe1010 , 

In case 3 step 6, when I try `xfs_info /dev/longhorn/<volume from backing image>`,  I got error `xfs_info: /dev/longhorn/vol4 is not a valid XFS filesystem (unexpected SB magic number 0xeb639010)`, did I miss something? thank you

**Comment by PhanLe1010** [comment]
@chriscchien For backing image volume, we need to check the root partition inside the block device as mentioned in the step 4 and 5:
```
4. Find the major and minor version of the block device by ls -l /dev/longhorn/<volume-name>
5. Find the corresponding block device under lsblk with the same major and minor version. Then find the root partition of that block device
```

For example:
```
Find the major and minor version of the block device by ls -l /dev/longhorn/<volume-name>
Find the corresponding block device under lsblk with the same major and minor version. Then find the root partition of that block device
```

**Comment by chriscchien** [comment]
**Verified on longhorn-manager master-head `350c92`
Result Pass**

Test [steps](https://github.com/longhorn/longhorn/issues/4354#issuecomment-1260174435) 

- I can reproduce the file system corruption error on Longhorn v1.3.1 by execute step 1, 2  and step 3
`mount: /mnt: wrong fs type, bad option, bad superblock on /dev/sdb1, missing codepage or helper program, or other error.`

-  In longhorn-manager master-head,  the file corruption error can not be reproduced

**Comment by innobead** [comment]
@chriscchien @PhanLe1010 has another PR to improve the fix and needs further testing later on. Reopened this to continue.

**Comment by PhanLe1010** [comment]
PR merged. Could you please help to retest @chriscchien Thank you very much

**Comment by chriscchien** [comment]
Verified on longhorn-manager master-head `a00bac`
Result Pass

Test [steps](https://github.com/longhorn/longhorn/issues/4354#issuecomment-1260174435)

- I can reproduce the file system corruption error on Longhorn v1.3.1 by execute step 1, 2 and step 3
   `mount: /mnt: wrong fs type, bad option, bad superblock on /dev/sdb1, missing codepage or helper program, or other error.`

- In longhorn-manager master-head, the file corruption error can not be reproduced
