### ISSUE TITLE
[QUESTION] Shutdown/Restart of all/some of the nodes

### ISSUE THREAD

**Issue by atropos112** [longhorn/longhorn#4355]
I am running a 3-node setup at home (a non-production environment, a hobby is all). In order to store data I have some number of harddrives/ssd's on each device, I am using longhorn for all my pvc's. I have noticed that if I restart a node (physically speaking) the replica's on that node turn red (corrupted ?), because I have replicas (on other nodes) it automatically rebuilds the replica using replicas from other nodes (that were not restarted), jolly good. I have read somewhere that this is because the replica falls behind other replicas and as such is considered "broken" hence the rebuild, that makes a lot of sense. Following this I have three questions

1. Is it possible to "catch" up a replica on the device that was restarted (instead of rebuilding it from other ones in its entirety) ?
2. If ALL the nodes go down (a power cut for example), does that mean all of my pvc will go red ? (I'd think not given that no replica falls behind)
3. If i scale down all the deployments using the PVC (as such it becomes detached) and then restart one node, will it still have to rebuild ?

Thank you for your time. I've learned a lot using longhorn, its a very good piece of software thank you for making it.

EDIT:
I have had to restart a node (nvidia, i hate u) and as a result i did get to try out point 3. in the above. In my experience the node did not go red, and all worked well (please don't take my word for this in prod envs etc, my stakes are low here)

**Comment by shuo-wu** [comment]
1. It's about how the rebuilding can be improved. Currently, Longhorn will try to reuse the failed replica if possible. But it will read and verify all existing data for the failed replica, which is time-consuming. We plan to enhance it in https://github.com/longhorn/longhorn/issues/4210
2. If all nodes go down, Yes all would be considered as failed, and the applications of the volumes cannot live either. Later on, when the cluster is restored, Longhorn will automatically pick up the latest replica as the available one. For more details, you can check the salvage or auto salvage feature.
3. No. The attachment will be pretty fast if the volume is detached correctly.
