### ISSUE TITLE
[FEATURE] Allow volume expansion while in bound state

### ISSUE THREAD

**Issue by getsomebread** [longhorn/longhorn#4359]
## Is your feature request related to a problem? Please describe
In order to expand a Longhorn volume, it cannot be bound to a running workload. A workload must be shutdown before the Expand Volume option isn't grayed-out.

## Describe the solution you'd like
Allow xfs or ext4 volumes to be grown 'live' while volumes are bound. The ability to grow live xfs or ext4 volumes on Linux servers has been available for years, so it is technically possible (barring some Longhorn limitation).

**Comment by shuo-wu** [comment]
This will be tracked in https://github.com/longhorn/longhorn/issues/1674
