### ISSUE TITLE
[IMPROVEMENT] Document downgrade process

### ISSUE THREAD

**Issue by zamazan4ik** [longhorn/longhorn#4367]
## Is your improvement request related to a feature? Please describe

After reading the documentation it is not clear for me, how the downgrade process should be performed over the solution.

## Describe the solution you'd like

Could you please describe somewhere in the documentation:

- How to downgrade Longhorn to the older version (hopefully with no downtime). Maybe near with a upgrade documentation?
- Maybe some compatibility policies and notes between versions

If you do not support downgrade, please mention it explicitly in the documentation and possibly provide some scenario, how it can be done. E.g via creation a new cluster with an older Longhorn version and exporting data into it.

## Describe alternatives you've considered

I see no feasible alternatives here.

## Additional context

No additional context.

**Comment by innobead** [comment]
ref: https://github.com/longhorn/longhorn/issues/1455
