### ISSUE TITLE
[IMPROVEMENT] Improve the backup restoring time for better RTO

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4379]
## Is your improvement request related to a feature? Please describe

Some examples (ex: https://github.com/longhorn/longhorn/issues/4310#issuecomment-1208017614) show that the backup restoring time is not efficient enough, so we should revisit the current implementation to improve data retrieval time from the remote backup target.  

## Describe the solution you'd like

Increase the throughput for data retrieval. 

## Additional context

N/A

**Comment by joshimoo** [comment]
Some good benchmarking done by @derekbit in regard to compression usage.
#1409

**Comment by derekbit** [comment]
Will be handled in https://github.com/longhorn/longhorn/issues/5189
