### ISSUE TITLE
[BUG] Engine binary cannot be recovered after being removed accidentally

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4380]
## Describe the bug

Then volumes can not be attached.

## To Reproduce

Delete the current engine binary for a node:
    - Check the corresponding engine image pod status
        - If the engine binary is removed in the host, the pod will become NotReady but no restart.
        - If the engine binary is removed in the pod, no status change happens.
    - Attach volumes:
        - The replicas on the node will fail

## Expected behavior
The engine image pod should restart automatically and bring the binary back.

## Log or Support bundle

N/A

## Environment

 - Longhorn version: v1.3.0-rc2

## Additional context

https://cloud-native.slack.com/archives/CNVPEL9U3/p1659451262517469

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 5f76d4f) with [the manual test plan](https://github.com/longhorn/longhorn-tests/pull/1204/files).
