### ISSUE TITLE
[BUG] Volume can not attach to node when engine image DaemonSet pods are not fully deployed

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#4386]
## Describe the bug

https://longhorn.github.io/longhorn-tests/manual/pre-release/ha/partial-engine-deployment/ case 2, step 9

## To Reproduce

1. 3 node Longhorn cluster
2. Create 1 volume with 3 replica
3. Taint node1 with the taint: `key=value:NoSchedule`
4. Delete the engine image DaemonSet and wait for Longhorn to automatically recreates it.
5. Attach the volume to any node
6. Volume will become in faulted status

## Expected behavior

Verify that volume can be attached to any nodes except tainted node

## Log or Support bundle

[longhorn-support-bundle_77c4e1a9-b223-483d-a095-f5042592628b_2022-08-09T09-55-12Z.zip](https://github.com/longhorn/longhorn/files/9289379/longhorn-support-bundle_77c4e1a9-b223-483d-a095-f5042592628b_2022-08-09T09-55-12Z.zip)

## Environment

v1.3.1-rc2

## Additional context

N/A

**Comment by innobead** [comment]
ref: https://github.com/longhorn/longhorn/issues/2935#issue-979741053

**Comment by cchien816** [comment]
**Verified on master-head `974601`
Result Pass** 

Steps https://github.com/longhorn/longhorn/issues/4386#issue-1333010193
Volume can not attach to tainted node, when attached to untainted nodes, volume status will become degraded as expected
