### ISSUE TITLE
Longhorn migration in Rancher

### ISSUE THREAD

**Issue by konstantin-921** [longhorn/longhorn#4387]
## Question
Hi Team!

We have a k8s cluster managed by Rancher. I am migrating Longhorn from old UI to new UI according to this guide - https://longhorn.io/kb/how-to-migrate-longhorn-chart-installed-in-old-rancher-ui-to-the-chart-in-new-rancher-ui/

On the test cluster the migration was successful and then I upgraded Longhorn to 1.3.0. 

The problem occurred on another cluster. The old UI had Longhorn 1.2.0. I successfully ran the `longhorn_rancher_chart_migration.sh` script. According to the instructions now I have to go to the new UI and install Longhorn the **SAME** version as in the old UI:
```
Successfully updated the annotations and labels for the resources!
Next step:
  1. Go to Rancher UI -> Go to the downstream cluster -> App&Marketplace -> Charts
  2. Find and select the Longhorn chart
  3. Select the chart version corresponding the Longhorn version 1.2.0
  4. Install the chart with the correct helm values. Here are the helm values of your old charts: 
enablePSP=true,image.defaultImage=true,ingress.enabled=false,longhorn.default_setting=false,persistence.backingImage.enable=false,persistence.defaultClass=true,persistence.defaultClassReplicaCount=3,persistence.reclaimPolicy=Delete,persistence.recurringJobSelector.enable=false,persistence.recurringJobs.enable=false,privateRegistry.registryPasswd=,privateRegistry.registrySecret=,privateRegistry.registryUrl=,privateRegistry.registryUser=,service.ui.type=Rancher-Proxy
  5. Verify that the migrated charts are working ok
  6. Run this script again with the flag --type=cleanup to remove the old chart from the legacy UI
```

But I can't find version 1.2.0 in the new UI (screenshot)
![Selection_016](https://user-images.githubusercontent.com/34741216/183621108-c012c98e-f765-446c-9963-75388e2f7f82.png)

I tried to install Longhorn via Helm:
`helm install longhorn longhorn/longhorn --namespace longhorn-system --version 1.2.0`

But this threw an error right away:
```
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "engines.longhorn.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "longhorn": current value is "longhorn-crd"
```

I understand that I should have upgrade to version 1.2.4 first and then started the migration. But I'm already here. Could you tell me how I should proceed next?

## Environment

 - Longhorn version: 1.2.0
 - Rancher version: 2.6.3
 - K8s Version: v1.21.8 (RKE1)
 
## Additional info

I use default repo and branch release-v2.6
![Selection_017](https://user-images.githubusercontent.com/34741216/183624110-fe73845b-ca4e-4dc3-9d34-f0f8b45ad764.png)

**Comment by PhanLe1010** [comment]
@konstantin-921 It is ok to upgrade to Longhorn 1.2.4 in the new UI. We have verified this upgrade path

**Comment by konstantin-921** [comment]
> @konstantin-921 It is ok to upgrade directly to `100.1.2+up1.2.4` in the new UI. We have verified this upgrade path
> 
> Please don't use Helm here, it will conflict

Thank you so much, @PhanLe1010! I can finally finish the upgrade!

**Comment by konstantin-921** [comment]
I am forced to reopen the issue.

I successfully installed Longhorn 1.2.4. Then I checked that all resources were created, did scale up/scale down replicas tests. Everything was working fine. Then I tried to upgrade to version 1.3.0. And got an error
![Selection_018](https://user-images.githubusercontent.com/34741216/184160815-eb1106e2-800f-478e-ad99-6f1cb3a5607c.png)

**Comment by innobead** [comment]
You encountered this when starting using Longhorn before 1.0. Check the workaround at https://github.com/longhorn/longhorn/issues/4340#issuecomment-1201287027 for 1.3.0, and this has been fixed in 1.3.1. 

cc @derekbit

**Comment by konstantin-921** [comment]
Thank you @innobead! That helped. I was able to update Longhorn to version 1.3.0. But now I can't upgrade engine for some (3 out of 10) of my volumes. Here is the error
![Selection_021](https://user-images.githubusercontent.com/34741216/184221873-81ef838d-ebd1-4716-92cc-612cb845c6db.png)

**Comment by konstantin-921** [comment]
I managed to fix it myself by changing the `spec.dataLocality` field with the command k edit `volume.longhorn.io pvc-a32ff376-ce29-4939-a968-124da3e7d332 -n longhorn-system -o yaml`

**Comment by PhanLe1010** [comment]
@konstantin-921 What do you set it to? is it `disable`?

**Comment by konstantin-921** [comment]
> @konstantin-921 What do you set it to? is it `disable`?

yes

**Comment by PhanLe1010** [comment]
Thank you! 
This might be related to the weekhook in Longhorn v1.3.0 version. I am investigating it. 

Please do report if you hit any other issue

**Comment by derekbit** [comment]
For DataLocality, We need to convert `""` to `disabled` in the conversion webhook.

**Comment by innobead** [comment]
> We need to convert `""` to `disabled` in the conversion webhook. v1.0 does not have the dataLocality parameter, and the value is not handled in the upgrade path (v1.0->v1.1 and v1.1->v1.2) and always keeps an empty sting, so users might hit this issue while upgrading to v1.3.x if they use v1.0 before.

We should tackle another ticket about this because the migration actually works. 

@derekbit Please help create a new ticket. Also, add that issue w/ the workaround to 1.3.0 https://github.com/longhorn/longhorn/wiki/Outstanding-Known-Issues-of-Releases. Thanks.
