### ISSUE TITLE
[IMPROVEMENT] Get tgtd log next to the engine process

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4389]
## Is your improvement request related to a feature? Please describe

The logs of the block frontend client (iscsi initiator) can be found in the system log (dmesg or var message/syslog), but for now, the log of each tgtd daemon is not collected together with the engine process. It will be helpful to collect together for troubleshooting purpose. 

## Describe the solution you'd like

log redirection to the same process stdout/stderr

## Describe alternatives you've considered

dump tgtd logs to some log location on the host, but this needs external log management 

## Additional context

N/A

cc @derekbit

**Comment by derekbit** [comment]
Already implemented.
