### ISSUE TITLE
[BACKPORT][1.2.x][BUG] Volume can not attach to node when engine image DaemonSet pods are not fully deployed

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4390]
ref: https://github.com/longhorn/longhorn/issues/4386

**Comment by cchien816** [comment]
**Verified on v1.2.x-head `06a53b`
Result Pass**

Steps https://github.com/longhorn/longhorn/issues/4386#issue-1333010193
Volume can not attach to tainted node which does not have engine image pod deployed, when attached to untainted nodes, volume status become degraded as expected
