### ISSUE TITLE
[BACKPORT][v1.3.x][BUG] Error/warning during uninstallation of Longhorn v1.3.1 via manifest

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4407]
ref: https://github.com/longhorn/longhorn/issues/4405

**Comment by Lichiehyao** [comment]
Verified on master-head 20220817

- longhorn master-head ([a44c828](https://github.com/longhorn/longhorn/commit/a44c828db659c67d3b6c9b9ca7c06dd4b42a4554)) 
- longhorn-manager master-head ( [1c1b359](https://github.com/longhorn/longhorn-manager/commit/1c1b3596987d0a5d7b294efc8444e87cf5bb8554))

Result Pass

1. The issue can be reproduced on v1.3.1
2. Follow the test steps in the [comment](https://github.com/longhorn/longhorn/issues/4004#issue-1241048070) and use  longhorn:v1.3.x-head longhorn-manager:v1.3.x-head in https://raw.githubusercontent.com/longhorn/longhorn/v1.3.x/deploy/longhorn.yaml 
3. After uninstalled Longhorn, we didn’t find out the error log in the uninstaller logs

**Comment by innobead** [comment]
Thanks, @Lichiehyao . This is good.
