### ISSUE TITLE
[BACKPORT][v1.2.x][BUG] Error/warning during uninstallation of Longhorn v1.2.x-head via manifest

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4409]
ref: https://github.com/longhorn/longhorn/issues/4405

**Comment by Lichiehyao** [comment]
**Verified on v1.2.x-head 20220817**

- longhorn v1.2.x-head ([70cacf0](https://github.com/longhorn/longhorn/commit/70cacf0ebe8f738f093e947781bb7fe36c11fbb9)) 
- longhorn-manager v1.2.x-head ( [b894827](https://github.com/longhorn/longhorn-manager/commit/b894827c5aabbe9a2d86de4cb228c5ff9dbecf2e))

**The test steps**

1. Install Longhorn v1.2.x Ref.([install-with-kubectl](https://longhorn.io/docs/1.2.4/deploy/install/install-with-kubectl/))
2. Create some volume and attach to pod. Ref.([create-volumes & attach to pod](https://longhorn.io/docs/1.2.4/volumes-and-nodes/create-volumes/))
```
kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/v1.2.x/examples/storageclass.yaml
kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/v1.2.x/examples/pod_with_pvc.yaml
```

3. Uninstall Longhorn. Ref.([uninstall-with-kubectl](https://longhorn.io/docs/1.2.4/deploy/uninstall/#uninstalling-longhorn-using-kubectl))
4. Check whether or not the error is printed in the longhorn-uninstall logs

**Result Pass**

1. The issue can be reproduced on v1.3.1, but can’t be reproduced on v1.2.4.
2. Follow the test steps in the [comment](https://github.com/longhorn/longhorn/issues/4405#issue-1336293340) and use longhorn:v1.2.x-head longhorn-manager:v1.2.x-head in https://raw.githubusercontent.com/longhorn/longhorn/v1.2.x/deploy/longhorn.yaml 
3. After uninstalled Longhorn, we didn’t find out the error log in the uninstaller logs
