### ISSUE TITLE
[BUG] NFS backups don't work 

### ISSUE THREAD

**Issue by konstantin-921** [longhorn/longhorn#4413]
## Describe the bug
Hi Team!

I am going to use an external (outside Kubernetes) NFS server to store backups. Its ip is `10.0.5.214`. Here are my steps:
- added a new directory `/mnt/nfs/backups` to the NFS server
- added a` /mnt/nfs/backups *(rw,async,no_subtree_check)` entry to /etc/exports
- updated the config `exportfs -a `
- went into the Longhorn UI and added a new Backup Target - `nfs://10.0.5.214:/mnt/nfs/backups` and saved
- went to the Backup tab and checked that the error `backup target url is empty` no more
- tried to create a new backup from the Grafana volume

I did not see a new backup in the Backup tab. At the same time I found the following error logs in one of the` longhorn-manager` pods:
![Selection_107](https://user-images.githubusercontent.com/34741216/184344381-066a8aaa-a65b-4f53-b5a5-838b87d78a9d.png)

It seems that Longhorn cannot create `/var/lib/longhorn-backupstore-mounts/10_0_5_214/mnt/nfs/backups/backupstore` folder inside the container for some reason.

Could anyone help me with this?

## Environment

 - Longhorn version: 1.2.0
 - Rancher version: 2.6.3
 - K8s Version: v1.21.8 (RKE1)

**Comment by derekbit** [comment]
Can you print the content of the server's `/etc/exports`? The read-only issue is usually caused by the server's configuration  .

**Comment by konstantin-921** [comment]
/mnt/nfs 10.0.7.70(rw,async,no_subtree_check)
/mnt/nfs 10.0.7.71(rw,async,no_subtree_check)
/mnt/nfs 10.0.7.72(rw,async,no_subtree_check)
/mnt/nfs 10.0.7.112(rw,async,no_subtree_check)
/mnt/nfs 10.0.7.120(rw,async,no_subtree_check)

/mnt/nfs 10.0.7.11(rw,async,no_subtree_check)
/mnt/nfs 10.0.7.16(rw,async,no_subtree_check)
/mnt/nfs 10.0.7.12(rw,async,no_subtree_check)
/mnt/nfs 10.0.7.26(rw,async,no_subtree_check)
/mnt/nfs 10.0.7.24(rw,async,no_subtree_check)
/mnt/nfs 10.0.7.25(rw,async,no_subtree_check)
/mnt/nfs 10.0.7.183(rw,async,no_subtree_check)
/mnt/nfs 10.0.7.219(rw,async,no_subtree_check)
/mnt/nfs 10.0.7.27(rw,async,no_subtree_check)
/mnt/nfs 10.0.7.28(rw,async,no_subtree_check)

/mnt/nfs 10.0.7.154(rw,async,no_subtree_check)
/mnt/nfs 10.0.7.139(rw,async,no_subtree_check)

/mnt/nfs/xxx/xxx/xxx 10.0.7.46(ro,async,no_subtree_check)
/mnt/nfs/xxx/xxx/xxx 10.0.7.43(ro,async,no_subtree_check)

/mnt/nfs 10.0.7.0/24(ro,async,no_subtree_check)
/mnt/nfs 10.0.5.222(ro,async,no_subtree_check)

/mnt/nfs/backups *(rw,async,no_subtree_check)

**Comment by derekbit** [comment]
The parent folder (/mnt/nfs) might override the child folder's permission (/mnt/nfs/backups). Thus, `/mnt/nfs/backups` is exported as an read-only filesystem.

```
/mnt/nfs 10.0.7.0/24(ro,async,no_subtree_check)
/mnt/nfs 10.0.5.222(ro,async,no_subtree_check)

/mnt/nfs/backups *(rw,async,no_subtree_check)
```

**Comment by konstantin-921** [comment]
You were absolutely right. It worked. I changed` /mnt/nfs/backups *(rw,async,no_subtree_check)` to` /mnt/backups *(rw,async,no_subtree_check)`. Then I changed the Backup Target. And in the Backup tab, new backups appeared immediately. Thank you @derekbit !
