### ISSUE TITLE
[BACKPORT][v1.3.2][BUG] can't upgrade engine if a volume was created in Longhorn v1.0 and the volume.spec.dataLocality is ""

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4419]
## Describe the bug

https://github.com/longhorn/longhorn/issues/4412

## To Reproduce

3. Perform '....'

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by cchien816** [comment]
**Verified on longhorn manager v1.3.x-head `1c1b35`
Result Pass**

Test [steps](https://github.com/longhorn/longhorn/issues/4412#issue-1336943469)
1. Can reproduced on v1.3.1
2. Volume engine image can upgrade to v1.3.x-head when volume was created in v1.0.0 and longhorn was upgraded from v1.0.0 -> v1.2.x(upgrade engine) -> v1.3.x
