### ISSUE TITLE
[BUG] Confusing description the label for replica delition

### ISSUE THREAD

**Issue by alekc** [longhorn/longhorn#4430]
## Describe the bug

happens for a detached volumes, as you can see from the screen

<img width="936" alt="image" src="https://user-images.githubusercontent.com/302807/184882915-da01366d-34c6-4e11-b1b5-6dff45907e9a.png">

The volume must be detached, but it must be either attached or detached 
## To Reproduce

Go to any detached volume, mouse over the replica delete button (which should be greyed out)

**Comment by derekbit** [comment]
cc @smallteeths

**Comment by yangchiu** [comment]
Currently unable to verify this because the latest image hasn't been published and blocked by fossa checking (https://drone-publish.longhorn.io/longhorn/longhorn-ui/644).

**Comment by yangchiu** [comment]
The latest longhorn-ui image for amd64 published, but still unable to fetch the latest image because the manifest is not updated due to s390 publish image failed (https://drone-publish.longhorn.io/longhorn/longhorn-ui/650/3/2).

**Comment by innobead** [comment]
> The latest longhorn-ui image for amd64 published, but still unable to fetch the latest image because the manifest is not updated due to s390 publish image failed ([drone-publish.longhorn.io/longhorn/longhorn-ui/650/3/2](https://drone-publish.longhorn.io/longhorn/longhorn-ui/650/3/2)).

This was temporarily fixed by https://github.com/longhorn/longhorn-ui/commit/a1af978036adb368ba1157306922958fe5a9de67 to move this verification forward.
