### ISSUE TITLE
[IMPROVEMENT] Add prep work for fixing the corrupted filesystem using fsck in KB

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4440]
## Is your improvement request related to a feature? Please describe

fsck usually needs to be run to fix a corrupted filesystem. It is possible, however, that the incorrect fsck fix might cause serious data loss and corruption.
To mitigate the risk, a snapshot of the corrupted filesystem should be taken before any fix attempts are made. In case of an accident, the user can recover the volume. We can suggest the prep work in the [KB](https://longhorn.io/kb/troubleshooting-volume-filesystem-corruption/#solution).

## Additional context

https://serverfault.com/questions/786648/when-is-fsck-dangerous
https://docs.portworx.com/reference/cli/volume-check/

**Comment by khushboo-rancher** [comment]
@derekbit Can you please help with the reproduction steps, so that we can test this?
