### ISSUE TITLE
[BACKPORT][v1.2.x][IMPROVEMENT] Support failed/obsolete orphaned backup cleanup 

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#4456]
ref: https://github.com/longhorn/longhorn/issues/3898

**Comment by chrisc1981** [comment]
Hi @mantissahz ,

Follow test steps https://github.com/longhorn/longhorn/issues/3898#issuecomment-1214773993, ( I set `Failed Backup Time to Live` to 5), after 5 minutes passed by, the error state backup will not cleanup until I create a snapshot or create a new backup, this behavior not found in master-head, could you help me to clarify this? thank you.

**Comment by mantissahz** [comment]
The failed backup deletion would be trigger when update the backup volume by polling backup target and it is 300 seconds now, and creating a new backup would update the backup volume as well.
https://github.com/longhorn/longhorn/blob/fba0c5c1673285d447b888acd18d96b14bb5e5a0/chart/questions.yml#L331
It might wait in 10 minutes if the polling backup target is not started. @chrisc1981 Could you shorten the `Backupstore Poll Interval` and try again?

**Comment by c3y1huang** [comment]
Suggest having an automation test case for consistent testing and results.
https://github.com/longhorn/longhorn/issues/4481

**Comment by chrisc1981** [comment]
**Verified on longhorn-manager v1.2.x-head 36a84d
Result Pass**

Test steps or (https://github.com/longhorn/longhorn/issues/3898#issuecomment-1214773993):

1. Deploy Longhron and backupstore
2. Set Failed Backup Time to Live to 5 (by default it's 1440 minutes)
3. Create a volume then attach to worker node and write some data
4. Create a backup to backup target then crash the instance-manager-r such as this command `kubectl delete pods -l longhorn.io/instance-manager-type=replica -n longhorn-system --wait`.
5. Then backup state should become Error in a few seconds.
6. Wait after Failed Backup Time to Live passed
7. Verify failed backup had been deleted from UI and command `kubectl get backups.longhorn.io -n longhorn-system`
8. Test on both S3 and nfs type of backupstore

**Comment by innobead** [comment]
> Suggest having an automation test case for consistent tests and results. #4481

Thanks @c3y1huang. 

@longhorn/qa QA should decide whether needs to add test cases before closing, even though the source ticket does not has `require/automation-e2e`. If needed, return back to `implementation`, then ask the Eng assignee to at least create the test case description/skeltion.
