### ISSUE TITLE
[BUG] Unable to search 1.3.1 doc by algolia

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4457]
## Describe the bug

Search is not working for https://longhorn.io/docs/1.3.1/

Need to check with the algolia support to see how to update the longhorn configuration at their side to do the indexing. Background: https://github.com/algolia/docsearch-configs/pull/4090/files, but this repo has been archived, so need to understand how it works now. 

Currently, the doc search of latest and x.x.x-dev will not work but others (x.x.x) do. 

<img width="227" alt="image" src="https://user-images.githubusercontent.com/899492/185777012-6077b3b6-e57d-4763-a2b0-afacae6fafb0.png">

**Comment by innobead** [comment]
@mantissahz Please check this. Thanks.

**Comment by mantissahz** [comment]
Algolia support team provided https://docsearch.algolia.com/docs/migrating-from-legacy/
and I moved the docsearch v2 to v3 in our code, it still can not search v1.3.1 doc.
I think we still need to get into the https://crawler.algolia.com/ and set the config `https://github.com/algolia/docsearch-configs/blob/master/configs/longhorn.json`.
and here is reference, https://docsearch.algolia.com/docs/crawler/#how-to-migrate
I also test this https://docsearch.algolia.com/docs/legacy/run-your-own/ and failed with `Index not allowed with this API key` by `docker run ... algolia/docsearch-scraper`

**Comment by innobead** [comment]
> Algolia support team provided [docsearch.algolia.com/docs/migrating-from-legacy](https://docsearch.algolia.com/docs/migrating-from-legacy/) and I tried to move the docsearch v2 to v3 in our codes, it still could not search v1.3.1 doc. I think we still need to get into the [crawler.algolia.com](https://crawler.algolia.com/) and set the config `https://github.com/algolia/docsearch-configs/blob/master/configs/longhorn.json`. and here is reference, [docsearch.algolia.com/docs/crawler/#how-to-migrate](https://docsearch.algolia.com/docs/crawler/#how-to-migrate) I also test this [docsearch.algolia.com/docs/legacy/run-your-own](https://docsearch.algolia.com/docs/legacy/run-your-own/) and failed with `Index not allowed with this API key` by `docker run ... algolia/docsearch-scraper`

Why did they suggest migration? Is there any wrong in our current setting?

**Comment by innobead** [comment]
I see. Probably want we should figure out if why the search not work, because I am not sure if this is about the deprecation or migration because others work.

**Comment by innobead** [comment]
> > The application BH4D9OD16A you are using is part of our old infrastructure.
> > DocSearch is now hosted on new infrastructure. If you'd like the service to continue, please follow the step here: [Migrating from the legacy scraper | DocSearch by Algolia](https://docsearch.algolia.com/docs/migrating-from-legacy)
> 
> I think they try to deprecate the v2 version as [docsearch.algolia.com/docs/crawler/#are-the-docsearch-scraper-and-docsearch-configs-repository-still-maintained](https://docsearch.algolia.com/docs/crawler/#are-the-docsearch-scraper-and-docsearch-configs-repository-still-maintained) and I'm still waiting for algolia support's response if we could still use v2 version.

Any update from their support?

**Comment by mantissahz** [comment]
>the Docsearch team on this you should have received an email from the Docsearch team directing to new credentials to use today. Can you use that and then let me know if the issue persists after re-indexing? You are correct that if 1) version exists as an attributeForFaceting and 2) records exist in your index with a version value of 1.3.1 then 3) you can use facetFilters on 1.3.1.

This is from their support.
It seams that new documents we recently added (ex. 1.3.1, 1.4.0-dev, 1.2.5-dev) are not indexed correctly and need to check with the credentials that were sent to the email we used to applied the service at first.
I also asked which the email we used to apply and wait for the response.

**Comment by Lichiehyao** [comment]
## Describe the items of the test development (DoD, definition of done) you'd like

- [X] v1.3.1
- [X] v1.3.0
- [ ] v1.2.5
- [ ] v1.2.4
- [ ] v1.2.3
- [ ] v1.2.2
- [ ] v1.2.1
- [ ] v1.2.0
- [ ] v1.1.3
- [ ] v1.1.2
- [ ] v1.1.1
- [ ] v1.1.0
- [X] v1.4.0-dev

**Comment by innobead** [comment]
@Lichiehyao Close?

**Comment by Lichiehyao** [comment]
I close it.
