### ISSUE TITLE
volume failed to attach to node

### ISSUE THREAD

**Issue by zhuw0312** [longhorn/longhorn#4460]
## Question
> when i deployed longhorn, the pod cannot use the pvc.

## Environment

 - Longhorn version: 1.3.1
 - Kubernetes version: v1.24.2
 - Node config
   - OS type ：centos7
   - CPU per node: 4
   - Memory per node: 8G
   - Disk type：hdd
   - Network bandwidth and latency between the nodes: inner network
 - Underlying Infrastructure: Baremetal

## logs

- csi-attach log

> Error processing "csi-eb0467592e57ad3f10ba2cc1aae84c15b350632a0425e4e5735767af8b4a76c6": failed to attach: rpc error: code = DeadlineExceeded desc = volume pv-test failed to attach to node
> 

- longhorn-pvc example  pod logs 

```
Warning  FailedScheduling    21m                  default-scheduler        0/3 nodes are available: 3 persistentvolumeclaim "pvc-test" not found. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.
Warning  FailedScheduling    20m                  default-scheduler        0/3 nodes are available: 3 persistentvolumeclaim "pvc-test" not found. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.
Normal   Scheduled           20m                  default-scheduler        Successfully assigned default/volume-pv-test to wf-dev-mid-k8s-m
Warning  FailedMount         13m                  kubelet                  Unable to attach or mount volumes: unmounted volumes=[vol], unattached volumes=[kube-api-access-vrwh8 vol]: timed out waiting for the condition
Warning  FailedMount         2m11s (x7 over 18m)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[vol], unattached volumes=[vol kube-api-access-vrwh8]: timed out waiting for the condition
Warning  FailedAttachVolume  3s (x17 over 18m)    attachdetach-controller  AttachVolume.Attach failed for volume "pv-test" : rpc error: code = DeadlineExceeded desc = volume pv-test failed to attach to node wf-dev-mid-k8s-m
```

## how to slove this question?
 please help me，tks a lot.

**Comment by derekbit** [comment]
` "pvc-test" not found`
Can you check if the PVC is already created or missing?

**Comment by zhuw0312** [comment]
> "pvc-test" not found

the pvc and pv existed.

```
[root@wf-dev-mid-k8s-m ~]# kubectl get pvc
NAME       STATUS   VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS      AGE
pvc-test   Bound    pv-test   10Gi       RWO            longhorn-static   93m

[root@wf-dev-mid-k8s-m ~]# kubectl get pv
NAME      CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM              STORAGECLASS      REASON   AGE
pv-test   10Gi       RWO            Retain           Bound    default/pvc-test   longhorn-static            94m
```

**Comment by zhuw0312** [comment]
yes .

is it wrong ?

**Comment by derekbit** [comment]
Can you provide the support bundle?

**Comment by zhuw0312** [comment]
please tell me how to get this。。。

**Comment by derekbit** [comment]
Please refer to https://www.suse.com/support/kb/doc/?id=000020145

You can also check longhorn-manager and see if there are related error messages.

**Comment by derekbit** [comment]
@zhuw0312 I cannot download the support bundle from the link. BTW, it's not related to the storage-network.

**Comment by zhuw0312** [comment]
[https://trumantaurus.oss-cn-hangzhou.aliyuncs.com/longhorn-support-bundle_ca737ab5-56b8-44ba-8fbc-d7d47bd45434_2022-08-22T12-22-44Z.zip](url)

please try again.

ok,got it.

**Comment by derekbit** [comment]
After investigating the support bundle, I found you change the `hostpath` of the daemonset during installation.
Can you check this ticket https://github.com/longhorn/longhorn/issues/4441?

**Comment by zhuw0312** [comment]
@derekbit it workerd after  changing daemonset hostpath config from /data/longhorn to /var/lib/longhorn.
thank u very much.
