### ISSUE TITLE
[FEATURE] Way to apply settings changes in CI

### ISSUE THREAD

**Issue by Starttoaster** [longhorn/longhorn#4464]
## Is your feature request related to a problem? Please describe

I would like my CI pipeline to configure my longhorn cluster. The configmap that comes with the longhorn deployment only configures settings the first time that longhorn is installed, but changing that configmap over time does not persist settings. To do that you need to edit the `longhorn.io/v1beta1` `Setting` kind associated for each individual setting.

However, there is piece of metadata that changes between each apply and cannot be omitted.

```
apiVersion: longhorn.io/v1beta1
kind: Setting
metadata:
  name: default-longhorn-static-storage-class
  namespace: longhorn-system
  resourceVersion: "9226261"
value: longhorn
```

If I change this yaml to:

```
apiVersion: longhorn.io/v1beta1
kind: Setting
metadata:
  name: default-longhorn-static-storage-class
  namespace: longhorn-system
  resourceVersion: "9226261"
value: longhorn-test
```

And then attempt to apply it, I will receive an error:

```
Error from server (Conflict): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"longhorn.io/v1beta1\",\"kind\":\"Setting\",\"metadata\":{\"annotations\":{},\"name\":\"default-longhorn-static-storage-class\",\"namespace\":\"longhorn-system\",\"resourceVersion\":\"9226261\"},\"value\":\"longhorn\"}\n"},"resourceVersion":"9226261"},"value":"longhorn"}
to:
Resource: "longhorn.io/v1beta1, Resource=settings", GroupVersionKind: "longhorn.io/v1beta1, Kind=Setting"
Name: "default-longhorn-static-storage-class", Namespace: "longhorn-system"
for: "./set.yaml": Operation cannot be fulfilled on settings.longhorn.io "default-longhorn-static-storage-class": the object has been modified; please apply your changes to the latest version and try again
```

This is because in between this apply and the previous apply, the `resourceVersion` metadata has changed.. And if you omit that field, the following error is produced instead:

```
The settings "default-longhorn-static-storage-class" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```

This essentially makes codifying longhorn settings in git impossible, as far as I'm aware.

## Describe the solution you'd like

I'm not trying to prescribe one way to fix this. Ideally, I'd just say to scrub the Settings CRD entirely and just configure the settings off of a configmap like how most other applications in k8s work. But there may be historical context as to why the extra effort was made to use the CRD.

Maybe instead of that there's a way to make it so `resourceVersion` can be omitted in yaml and gets bumped automagically.

## Describe alternatives you've considered

The alternative is pretty much configuring your settings in the GUI, where you can't `git blame` and find who made the change you disagreed with. It also makes it more difficult to keep your settings consistent across multiple clusters.

## Additional context

I tend to be pretty long-winded so hopefully this already speaks for itself.

**Comment by Starttoaster** [comment]
I did manage to work around this using server-side applies. `kubectl apply -f <settings> --server-side=true` gets the results I was after.

I'll leave the Issue up to gauge appetite for a different way to achieve settings changes in git. But feel free to close the Issue if that appetite is non-existent.

**Comment by derekbit** [comment]
From v1.3, you can directly update the configmap.
For example, if you'd like to change the replica count to 5 and don't want to change other settings, you can update the configmap like this
```
# kubectl -n longhorn-system edit cm longhorn-default-setting
apiVersion: v1
data:
  default-setting.yaml: |-
    default-replica-count: 5
```

BTW, while you are updating the configmap, don't the chage of the configmap's metadata hit the same issue?

**Comment by Starttoaster** [comment]
Oh neat! I'll check a bit later but I suppose I must be using a Longhorn version prior to this past June's release. Thanks!
