### ISSUE TITLE
[IMPROVEMENT] Don't validate the volume state if the taint-toleration hasn't changed

### ISSUE THREAD

**Issue by seumasdunlop** [longhorn/longhorn#4465]
## Is your improvement request related to a feature? Please describe

An error is returned when applying the `taint-toleration` setting if any volumes are attached even if the value hasn't changed and therefore doesn't need to be applied.

`Error from server (Invalid): admission webhook "validator.longhorn.io" denied the request: fail to set the setting taint-toleration with invalid value node-type.coralbay.tv=pipeline:NoSchedule: cannot modify toleration setting before all volumes are detached`

## Describe the solution you'd like

The webhook shouldn't check if the volumes are attached if the value hasn't changed.

## Describe alternatives you've considered

Ignore the error.

## Additional context

We use kustomize to install a customised longhorn installation and get this spurious error on each apply.

**Comment by derekbit** [comment]
@seumasdunlop 
What's your LH version? We recommand you upgrade to v1.3.1.
The error is printed but ignored in v1.3.1. I think we can reduce the amount of the error messages.

**Comment by seumasdunlop** [comment]
I'm using v1.3.0 so is there any change going to v1.3.1? Apart from the spurious error message being printed there are no actual issues afaik.

**Comment by derekbit** [comment]
Yes, v1.3.0 has a [bug](https://github.com/longhorn/longhorn/issues/4160) related this default setting feature. We've fixed in v1.3.1.
