### ISSUE TITLE
[BUG] test_exporting_backing_image_from_volume failed in HDD test

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#4471]
## Describe the bug

Using longhorn v1.2.5-rc1, the automated test case `test_backing_image.test_exporting_backing_image_from_volume` sometimes (>50%) failed in HDD regression test.

## To Reproduce

1. setup k8s cluster with 1 control plane and 3 workers in AWS, and attach an extra HDD volume with volume type "st1" in each worker
2. install longhorn v1.2.5-rc1
3. use HDD volumes as longhorn disks instead of the default SSD one
4. run automated test by editing test.yaml:
```
    args: [
           "-k", "test_exporting_backing_image_from_volume",
          ]
```
5. during the test running, the longhorn volume will stuck in `attaching` state, but it expects to be `attached`
6. check the disk status in backing image page, the status will never become `ready`, but stuck in `in progress -> 100% -> failed` loop, and the failed message says: `failed to finish file /data/tmp/test-bi2-28cd0cc7.tmp and /data/tmp/test-bi2-28cd0cc7 processing: timeout executing: qemu-img [convert -f raw -O qcow2 /data/tmp/test-bi2-28cd0cc7.tmp /data/tmp/test-bi2-28cd0cc7.tmp.qcow2tmp], output , stderr, , error <nil>`

## Expected behavior

test case passed

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.2.5-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.23.7+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe): aws ebs volume type "st1" 160GB
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
This will be tackled in later releases 1.3.x.

**Comment by ChanYiLin** [comment]
Discussed with @roger-ryao 
We haven't seen this issue in daily regression after v1.3.x
Closing the issue

**Comment by roger-ryao** [comment]
After triggering the HDD test on the master-head and confirming that the test has passed, we can close this issue.

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5135/testReport/tests/test_backing_image/
![Screenshot_20231025_121947](https://github.com/longhorn/longhorn/assets/104337648/8ee6de8a-2724-4c84-af7d-81cc7f079e04)
