### ISSUE TITLE
[BUG] Unable to use a TTY error when running environment_check.sh

### ISSUE THREAD

**Issue by Lichiehyao** [longhorn/longhorn#4472]
## Describe the bug

Running environment_check as a suggested prereq to install throws an error: "Unable to use a TTY - input is not a terminal or the right kind of file"

## To Reproduce

`curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.2.5-rc1/scripts/environment_check.sh | bash`

## Expected behavior

`[INFO]  Required dependencies are installed.`
`[INFO]Waiting for longhorn-environment-check pods to become ready (0/3)...`
`[INFO]  All longhorn-environment-check pods are ready (3/3).`
`[INFO]  Required packages are installed.`
`[INFO]  Cleaning up longhorn-environment-check pods...`
`[INFO]  Cleanup completed.`

## Log or Support bundle

`[INFO]  Required dependencies are installed.`
`[INFO]  Waiting for longhorn-environment-check pods to become ready (0/3)...`
`[INFO]  All longhorn-environment-check pods are ready (3/3).`
`Unable to use a TTY - input is not a terminal or the right kind of file`
`Unable to use a TTY - input is not a terminal or the right kind of file`
`Unable to use a TTY - input is not a terminal or the right kind of file`
`[INFO]  Required packages are installed.`
`[INFO]  Cleaning up longhorn-environment-check pods...`
`[INFO]  Cleanup completed.`

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): N/A
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:  N/A
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: ununtu 22.04
   - CPU per node: 4
   - Memory per node: 4GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 1GB
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): multipass
 - Number of Longhorn volumes in the cluster: 3

## Additional context

refer the issue https://github.com/longhorn/longhorn/issues/4216

**Comment by innobead** [comment]
@c3y1huang This seems out of sync. Please help backport this from the master. Thanks.

**Comment by Lichiehyao** [comment]
Verified on v1.2.x-head 20220828

longhorn v1.2.x-head ([cccabbf](https://github.com/longhorn/longhorn/commit/cccabbf89f02dde36de302c46456cd9cd0318dbb))

Result Pass
