### ISSUE TITLE
[BUG] Misleading message "The volume is in expansion progress from size 20Gi to 10Gi" if the expansion is invalid

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4475]
### Discussed in https://github.com/longhorn/longhorn/discussions/4459

<div type='discussions-op-text'>

<sup>Originally posted by **usma0118** August 22, 2022</sup>
No changes made to pod or longhorn, one of volumes is stuck in volume expansion in progress.

![image](https://user-images.githubusercontent.com/355154/185870007-4691b1e7-1701-4b9e-b96a-de2c4e04c793.png)

Any ideas how to fix this?

have tried scaling down workload to 0 and reattaching volume... no changes.

</div>

**Comment by innobead** [comment]
@derekbit Do we have any validation to avoid users request size reduction in the validation admission?

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-ui e3d280c). Unable to reduce volume size through ui or api.
