### ISSUE TITLE
[BACKPORT][v1.2.5][BUG]Somehow the Rebuilding field inside volume.meta is set to true causing the volume to stuck in attaching/detaching loop

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4484]
## Describe the bug

https://github.com/longhorn/longhorn/issues/4212

## To Reproduce

3. Perform '....'

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by yangchiu** [comment]
Verified passed on v1.2.x-head (longhorn-engine 274f0e6) by following [the test steps](https://github.com/longhorn/longhorn/issues/4212#issuecomment-1212736221).
