### ISSUE TITLE
AttachVolume.Attach failed despite all volumes being attached and healthy.

### ISSUE THREAD

**Issue by turowicz** [longhorn/longhorn#4486]
I have 3 nodes: small, medium and large.

I need my application to run fully on the large node (`bpknsvaifp01`), so the replicas only provision there. This is achieved via node selector for my deployments and data locality for replicas. The longhorn storage class has number of replicas set to `1` and data locality is `best-effort`.

When I install the deployment, the pods are created and longhorn provisions the PVCs correctly. The application has 3 volumes to mount and their singleton replicas are all living on `bpknsvaifp01` according to screenshot below:

![image](https://user-images.githubusercontent.com/1055391/186663731-ef284db0-aa05-4034-9596-68195ab07f59.png)

Unfortunately the pods that are looking to mount the `pvc-bf6acb45-1f4c-45a7-b0f5-482e58912182` are getting:

```
AttachVolume.Attach failed for volume "pvc-bf6acb45-1f4c-45a7-b0f5-482e58912182" : rpc error: code = DeadlineExceeded desc = volume pvc-bf6acb45-1f4c-45a7-b0f5-482e58912182 failed to attach to node bpknsvaifp01
```
The pod distribution is as follows:

1. Application pods are on all `bpknsvaifp01`
2. Replica instance manager is on `bpknsvaifp01`
3. Volume instance manager is on `bpknsvmonp01`.
4. Longhorn says the volume is mounted to `bpknsvmonp01`
 
What can I do to make it all run on `bpknsvaifp01`?

There are no errors in any logs of the Replica and Volume instance managers.

**Comment by turowicz** [comment]
It looks like the replica is being tunelled to the pod via the manager that is on the other machine. This should not be the case right?

**Comment by turowicz** [comment]
Also I can see that data locality makes the data local to the Volume manager, not the pods

**Comment by derekbit** [comment]
@turowicz 
Have you checked this doc https://longhorn.io/kb/tip-only-use-storage-on-a-set-of-nodes/ ?

**Comment by turowicz** [comment]
Interesting, I have not seen this. Thank you I will try that!

**Comment by turowicz** [comment]
@derekbit unfortunately the situation is the same even though I have created my storage class, tagged the node in Longhorn UI. It still puts attaches the Replica Instance to the Volume Manager that lives on a separate node. I cannot remove Longhorn from the "wrong" node as I need to put other replicas there.

**Comment by derekbit** [comment]
Can you send us the support bundle? I'd like to check the longhorn-manager logs.

**Comment by turowicz** [comment]
[longhorn-support-bundle_384d1fca-b254-4772-9beb-043660d24c2a_2022-08-25T13-23-55Z.zip](https://github.com/longhorn/longhorn/files/9425053/longhorn-support-bundle_384d1fca-b254-4772-9beb-043660d24c2a_2022-08-25T13-23-55Z.zip)

**Comment by turowicz** [comment]
@derekbit the pvc name in question has changed due to reinstall to `pvc-c1ab7578-1816-48fc-a95f-53e6bf54b83b`

**Comment by turowicz** [comment]
All other PVC are behaving as expected

**Comment by turowicz** [comment]
One more thing: the large node is in a different physical location than other nodes, separate building.

**Comment by turowicz** [comment]
I've noticed that share manager for that pvc fails with error `Readiness probe failed: cat: /var/run/ganesha.pid: No such file or directory`

**Comment by turowicz** [comment]
why do other pvc not have share managers?

**Comment by derekbit** [comment]
Because you've already deleted the pvc and the volume, I cannot not know the accessMode and the size of the volume.
But from the log,
1. The volume is a RWX (ReadWriteMany) volume
2. `bpknsvaifp01` didn't not have enough space holding the volume.
```
2022-08-25T14:57:32.962494434+02:00 time="2022-08-25T12:57:32Z" level=debug msg="Found 0 node has at least one schedulable disk" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=false node=bpknsvaifp01 owner=bpknsvaifp01 shareEndpoint= shareState=starting state=attached volume=pvc-bf6acb45-1f4c-45a7-b0f5-482e58912182
2022-08-25T14:57:32.962691509+02:00 time="2022-08-25T12:57:32Z" level=debug msg="Schedule replica pvc-bf6acb45-1f4c-45a7-b0f5-482e58912182-r-a4859817 to node bpknsvmonp01, disk 7f8abcad-e989-40e6-bb85-5913ea9a4e1e, diskPath /k8s/longhorn, dataDirectoryName pvc-bf6acb45-1f4c-45a7-b0f5-482e58912182-70012cac"
```

The storage space details of the node bpknsvaifp01
```
        storageavailable: 527328870400
        storagescheduled: 330712481792
        storagemaximum: 614220595200
```

**Comment by derekbit** [comment]
Can you try RWO volume with the size that's smaller than `storageavailable`?

**Comment by turowicz** [comment]
@derekbit there is 465GiB available on the `bpknsvaifp01` node, out of 573G total. The PVC is 200GB. How come that is not enough?

RWO will not work for this application unfortunately as I have multiple pods using it. I understand this requires the sharemanager, which fails to start due to ganesha.pid

**Comment by turowicz** [comment]
Maybe I need to fix how it reads the free space

**Comment by turowicz** [comment]
I tried reinstalling again, the pvc is now called `pvc-67f0fa5f-81d3-46db-af2c-33c607d95475`

Share Manager logs:
```
time="2022-08-25T14:01:48Z" level=info msg="starting RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
time="2022-08-25T14:01:48Z" level=info msg="ending RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
time="2022-08-25T14:09:19Z" level=debug msg="volume pvc-67f0fa5f-81d3-46db-af2c-33c607d95475 device /dev/longhorn/pvc-67f0fa5f-81d3-46db-af2c-33c607d95475 contains filesystem of format " encrypted=false volume=pvc-67f0fa5f-81d3-46db-af2c-33c607d95475
I0825 14:09:22.079592       1 mount_linux.go:449] Disk "/dev/longhorn/pvc-67f0fa5f-81d3-46db-af2c-33c607d95475" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/longhorn/pvc-67f0fa5f-81d3-46db-af2c-33c607d95475]
```

**Comment by turowicz** [comment]
Perhaps I just need to wait for it to finish formatting? It does kinda suck its on a different node tho.

**Comment by derekbit** [comment]
> 

Still checking `pvc-c1ab7578-1816-48fc-a95f-53e6bf54b83b`

**Comment by turowicz** [comment]
I also applied this (for 1.3.0) https://github.com/longhorn/longhorn/issues/2741#issuecomment-1119445672

**Comment by turowicz** [comment]
share manager is up!

```
time="2022-08-25T14:01:48Z" level=info msg="starting RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
time="2022-08-25T14:01:48Z" level=info msg="ending RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
time="2022-08-25T14:09:19Z" level=debug msg="volume pvc-67f0fa5f-81d3-46db-af2c-33c607d95475 device /dev/longhorn/pvc-67f0fa5f-81d3-46db-af2c-33c607d95475 contains filesystem of format " encrypted=false volume=pvc-67f0fa5f-81d3-46db-af2c-33c607d95475
I0825 14:09:22.079592       1 mount_linux.go:449] Disk "/dev/longhorn/pvc-67f0fa5f-81d3-46db-af2c-33c607d95475" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/longhorn/pvc-67f0fa5f-81d3-46db-af2c-33c607d95475]
I0825 14:39:42.477537       1 mount_linux.go:459] Disk successfully formatted (mkfs): ext4 - /dev/longhorn/pvc-67f0fa5f-81d3-46db-af2c-33c607d95475 /export/pvc-67f0fa5f-81d3-46db-af2c-33c607d95475
time="2022-08-25T14:39:44Z" level=info msg="starting nfs server, volume is ready for export" encrypted=false volume=pvc-67f0fa5f-81d3-46db-af2c-33c607d95475
time="2022-08-25T14:39:44Z" level=info msg="Running NFS server!"
time="2022-08-25T14:39:44Z" level=info msg="starting health check for volume" encrypted=false volume=pvc-67f0fa5f-81d3-46db-af2c-33c607d95475
```

**Comment by turowicz** [comment]
@derekbit it's up! The node running the sharemanager (different physical location from large node) needed a lot of time to format and spin up the replica.

**Comment by turowicz** [comment]
But a new problem arises: Does that mean all pod calls to this volume will go through the other node simply because thats where the share manager has been spun up?

**Comment by turowicz** [comment]
In short: both pods and replica files are on `bpknsvaifp01` but the Share Manager is on `bpknsvwebp02`. Does this mean all disk requests will be routed via remote node?

**Comment by derekbit** [comment]
> Does that mean all pod calls to this volume will go through the other node simply because thats where the share manager has been spun up?

The filesystem format procedure only takes much time at the first time.

> In short: both pods and replica files are on bpknsvaifp01 but the Share Manager is on bpknsvwebp02. Does this mean all disk requests will be routed via remote node?

You are right because of the design of the RWX volume unless the applications, volume and replica are all on the same node...

**Comment by turowicz** [comment]
@derekbit is it possible to tell Share Manager to spin up on a specific Node? I have 4 pods that are writing and reading from the volume. It should all be contained within this one Node.

**Comment by derekbit** [comment]
@turowicz 

According to the [spec](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) of `ReadWriteOnce` 
```
the volume can be mounted as read-write by a single node. ReadWriteOnce access mode still can allow
 multiple pods to access the volume when the pods are running on the same node.
```
In your use case, if all pods are the same node, you can use a RWO volume. Then, you don't have to suffer the extra latencies.

**Comment by turowicz** [comment]
> @turowicz 
> 
> 
> 
> According to the [spec](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) of `ReadWriteOnce` 
> 
> ```
> 
> the volume can be mounted as read-write by a single node. ReadWriteOnce access mode still can allow
> 
>  multiple pods to access the volume when the pods are running on the same node.
> 
> ```
> 
> In your use case, if all pods are the same node, you can use a RWO volume. Then, you don't have to suffer the extra latencies.

Will this allow all of them to write?

**Comment by derekbit** [comment]
> > @turowicz
> > According to the [spec](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) of `ReadWriteOnce`
> > ```
> > 
> > the volume can be mounted as read-write by a single node. ReadWriteOnce access mode still can allow
> > 
> >  multiple pods to access the volume when the pods are running on the same node.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In your use case, if all pods are the same node, you can use a RWO volume. Then, you don't have to suffer the extra latencies.
> 
> Will this allow all of them to write?

Yes. I did a quick test. It works if all pods are on the same node. You can give it a go. :)

**Comment by derekbit** [comment]
> @derekbit it's up! The node running the sharemanager (different physical location from large node) needed a lot of time to format and spin up the replica.

Is the storage SSD or HDD?
We probably need to investigate the slowness and have it improved.

**Comment by turowicz** [comment]
It's all SSD. I'll try setting RWO tomorrow but I need a confirmation that it will allow the pods on the same node to write?

**Comment by derekbit** [comment]
> It's all SSD. I'll try setting RWO tomorrow but I need a confirmation that it will allow the pods on the same node to write?

Yes. As the [spec](https://github.com/longhorn/longhorn/issues/4486#issuecomment-1227476700) stated.
