### ISSUE TITLE
[BUG] Deleted replica during volume restoration will not rebuild again during the restoration process

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#4488]
## Describe the bug

During volume restoration, delete one replica in restore volume, the deleted replica will not rebuild again during/after volume restoration

From test case [test_rebuild_with_restoration](https://github.com/longhorn/longhorn-tests/blob/db53b416c116dee43aae1e33f878f80c5f5b8c32/manager/integration/tests/test_ha.py#L767)

## To Reproduce

1. Setup a random backupstore.
2. Create a pod with a volume and wait for pod to start.
3. Write data to the volume and get the md5sum.
4. Create a backup for the volume.
5. Restore a volume from the backup.
6. Delete one replica during the restoration.
7. Wait for the restoration complete and the volume detached.

After step 7, restored volume in detached status have **2** replica and make test script fail

## Expected behavior

Need developer to identify the restored volume only have 2 replicas are correct behavior or not
(Because script think it should be 3 and this test case passed before)

If this behavior is correct, I will modify our test script

## Log or Support bundle

N/A

## Environment

 - Longhorn version: master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s

## Additional context

https://github.com/longhorn/longhorn/issues/4487
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1937/

**Comment by innobead** [comment]
@c3y1huang Please help check the behavior. I think during the restoration (still attached), it should be possibly rebuilt. However, after the restoration/detachment, there is no chance to trigger the rebuilding automatically.  (cc @shuo-wu )

@chrisc1981 Was there a new replica rebulilt successfully after the next attachment?

**Comment by innobead** [comment]
Thanks @chrisc1981 , then we need to clarify the behavior on the master.

**Comment by chrisc1981** [comment]
I found It was a timing issue not a product issue, because volume restoration process become more faster then before.
 
When our test script deleting replica in a restoring volume, actually the replica is already rebuild complete even in UI it still have a rebuild progress bar), so the replica won't rebuild and script raise error( expect 3 but 2)  
![Screenshot from 2022-08-26 20-21-53](https://user-images.githubusercontent.com/73337386/186924503-3c5ec8a1-aa35-412a-a8ff-cb1090e67bef.png)

I submit a [PR](https://github.com/longhorn/longhorn-tests/pull/1085) for review, thank you

**Comment by innobead** [comment]
@chrisc1981 Just remember moving the ticket to in-progress in the QA board next time.

**Comment by chriscchien** [comment]
Close thsi ticket, because after https://github.com/longhorn/longhorn-tests/pull/1085 merged, this error not happened in master-head pipeline
Will follow up backport test result when they merged
