### ISSUE TITLE
Kubernetes v1.25 support

### ISSUE THREAD

**Issue by opipenbe** [longhorn/longhorn#4490]
Kubernetes v1.25 released few days ago: https://kubernetes.io/blog/2022/08/23/kubernetes-v1-25-release/

PodSecurityPolicy is deprecated from v1.21 and is removed from v1.25 release. Unfortunately longhorn depends on it: 
`kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.3.1/deploy/longhorn.yaml
namespace/longhorn-system unchanged
serviceaccount/longhorn-service-account unchanged
configmap/longhorn-default-setting unchanged
configmap/longhorn-storageclass unchanged
customresourcedefinition.apiextensions.k8s.io/backingimagedatasources.longhorn.io configured
customresourcedefinition.apiextensions.k8s.io/backingimagemanagers.longhorn.io configured
customresourcedefinition.apiextensions.k8s.io/backingimages.longhorn.io configured
customresourcedefinition.apiextensions.k8s.io/backups.longhorn.io configured
customresourcedefinition.apiextensions.k8s.io/backuptargets.longhorn.io configured
customresourcedefinition.apiextensions.k8s.io/backupvolumes.longhorn.io configured
customresourcedefinition.apiextensions.k8s.io/engineimages.longhorn.io configured
customresourcedefinition.apiextensions.k8s.io/engines.longhorn.io configured
customresourcedefinition.apiextensions.k8s.io/instancemanagers.longhorn.io configured
customresourcedefinition.apiextensions.k8s.io/nodes.longhorn.io configured
customresourcedefinition.apiextensions.k8s.io/orphans.longhorn.io configured
customresourcedefinition.apiextensions.k8s.io/recurringjobs.longhorn.io configured
customresourcedefinition.apiextensions.k8s.io/replicas.longhorn.io configured
customresourcedefinition.apiextensions.k8s.io/settings.longhorn.io configured
customresourcedefinition.apiextensions.k8s.io/sharemanagers.longhorn.io configured
customresourcedefinition.apiextensions.k8s.io/snapshots.longhorn.io configured
customresourcedefinition.apiextensions.k8s.io/volumes.longhorn.io configured
clusterrole.rbac.authorization.k8s.io/longhorn-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/longhorn-bind unchanged
role.rbac.authorization.k8s.io/longhorn-psp-role unchanged
rolebinding.rbac.authorization.k8s.io/longhorn-psp-binding unchanged
service/longhorn-backend unchanged
service/longhorn-frontend configured
service/longhorn-conversion-webhook unchanged
service/longhorn-admission-webhook unchanged
service/longhorn-engine-manager unchanged
service/longhorn-replica-manager unchanged
daemonset.apps/longhorn-manager unchanged
deployment.apps/longhorn-driver-deployer unchanged
deployment.apps/longhorn-ui unchanged
deployment.apps/longhorn-conversion-webhook unchanged
deployment.apps/longhorn-admission-webhook unchanged
error: resource mapping not found for name: "longhorn-psp" namespace: "" from "https://raw.githubusercontent.com/longhorn/longhorn/v1.3.1/deploy/longhorn.yaml": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first`

Are there ETA for this fix?

**Comment by mantissahz** [comment]
Hi @opipenbe,
Yes, we are focusing on this now, and here is the related improvement https://github.com/longhorn/longhorn/issues/4003

**Comment by daimoniac** [comment]
Also cronjob batch/v1beta1 is deprecated and still in use for upgrade jobs CRD 1.1 to 1.2:

https://github.com/longhorn/longhorn-manager/blob/master/upgrade/v110to120/upgrade.go#L11

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125

had some fun with it already...

**Comment by joshimoo** [comment]
ref for PDB issue https://github.com/longhorn/longhorn/issues/4689#issuecomment-1271285060

**Comment by innobead** [comment]
Let's tackle this at https://github.com/longhorn/longhorn/issues/4003.

**Comment by derekbit** [comment]
@JohannesMerkt 

LH v1.3.2 does not support k8s v1.25. The support will start from LH v1.4.0

**Comment by zrml** [comment]
Using K3s; still happening; will wait for LH v1.4.0
Thanks
