### ISSUE TITLE
Progress report for backup

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#45]
Backup should report progress.

It's not straightforward in the current engine architecture when the backups are done out of band without the engine knowing it.

Design needed.

**Comment by vitobotta** [comment]
Hi, looking forward to seeing this implemented. At the moment I am backing up some volumes but I don't know if the backup has finished or not yet.

**Comment by shreesha21** [comment]
Usage for UI: 
The backup list could be seen in the JSON format with the following request:

`curl http://<longhorn-ui-ip>:<port>/v1/volumes`

Sample Response:

```
{
    "createTypes": {
        "volume": "http://206.189.69.105:32338/v1/volumes"
    },
    "data": [
        {
            "actions": {
                ...
            },
            "backupStatus": [
                {
                    "actions": null,
                    "backupError": "",
                    "backupURL": "s3://backupbucket@us-east-1/backupstore?backup=backup-cc0d6fbc1a7f4760&volume=btest",
                    "id": "backup-cc0d6fbc1a7f4760",
                    "links": null,
                    "progress": 100,
                    "snapshot": "6598a238-3c7e-4373-a74f-1d3e0ac6deef"
                },
                {
                    "actions": null,
                    "backupError": "",
                    "backupURL": "s3://backupbucket@us-east-1/backupstore?backup=backup-932d69f9ee4f4187&volume=btest",
                    "id": "backup-932d69f9ee4f4187",
                    "links": null,
                    "progress": 100,
                    "snapshot": "68403f2d-65d8-4a70-bf5e-4feedef348f0"
                }
            ],
            "baseImage": "",
            "conditions": {
               ...
                }
            },
          ...
```

**Comment by yasker** [comment]
@shreesha21 Also need to document the interaction between fields in backup status.

**Comment by shreesha21** [comment]
In BackupStatus, there are 4 important fields whose purpose is defined below:
```
`Snapshot`: This indicates the name of the snapshot being backed up.
`Progress`: This indicates the progress percentage of the backup. Value: 0 - 100
`BackupURL`: When the progress reaches 100, a backupURL is generated and populated here. This backupURL is required while restoring this backup in the future.
`BackupError`:  If there are any error thats encountered while creating the backup, it will be populated in this field.
```

**Comment by meldafrawi** [comment]
Steps to test:

- Create longhorn volume
- Attach the volume to a node
- Mount the volume on the node
- Write fairly large data into the mounted volume ~ 3 GB
- On volume details page, click `Create Backup`
  **Expected result:**  
    - In volume details page, Snapshots section you should see a new snapshot being created, and you should see backup progress.  
    - Hovering on the snapshot, a tool-tip will be appear, and it will contain backup information (backup URL, snapshot name, progress, .. )
