### ISSUE TITLE
[QUESTION] How to take snapshot without attached?

### ISSUE THREAD

**Issue by use-epoll** [longhorn/longhorn#4500]
As the title suggests.
I want to snapshot the longhorn volume without attaching it.

**Comment by derekbit** [comment]
Longhorn does not support it. But, why do you want to take a snapshot of a detached volume?

**Comment by use-epoll** [comment]
I use longhorn block storage in kvm in kubevirt system. I want to take a snapshot of an image. The image is not attached to any instance or node.

**Comment by derekbit** [comment]
cc @innobead @shuo-wu

**Comment by innobead** [comment]
> I use longhorn block storage in kvm in kubevirt system. I want to take a snapshot of an image. The image is not attached to any instance or node.

Your case should be related to VM snapshot w/ Kubevirt VirtualMachineSnapshot. Currently, Longhorn only supports live snapshot via CSI volume snapshot, but we will have an improvement for this offline snapshot for your case, https://github.com/longhorn/longhorn/issues/3715 which is planned for 1.4.

P.S. if just want to do a snapshot for a longhorn volume detached, probably can leverage the recurring job feature, but I don't think that fits your need.

**Comment by use-epoll** [comment]
Ok thanks, I'm looking forward to version 1.4, recurring jobs are not suitable for this scenario as snapshots are likely to be available at all times
