### ISSUE TITLE
[Question] Block volume with free space does not allow to write data -> No space left on device (insufficient inode number)

### ISSUE THREAD

**Issue by Brawcks** [longhorn/longhorn#4508]
## Describe the bug

Firstly, i'm sorry if i'm missing informations, i'm not an expert with filesystems / storages. I would be happy to add needed informations if asked. If i missed something, i apologize for it, i've read the documentation but wasn't able to fix the problem by myself.

Actually, i've setted up a kubernetes Cluster using RKE. I've installed longhorn through the UI and i'm now using longhorn to mount block volumes in my pods.

I actually have a block volume where i'm having this error when i try to write data inside : 

``` text
root@client-0:/opt/odoo/web# touch test.txt
touch: cannot touch 'test.txt': No space left on device
root@client-0:/opt/odoo/web# df
Filesystem                                             1K-blocks     Used Available Use% Mounted on
overlay                                                 51432064 31463028  17841140  64% /
tmpfs                                                      65536        0     65536   0% /dev
/dev/sda1                                               51432064 31463028  17841140  64% /etc/hosts
shm                                                        65536        0     65536   0% /dev/shm
10.43.154.39:/pvc-c61f583c-2fc3-48ac-a335-016f3e061322   1992704   537600   1438720  28% /opt/odoo/web
tmpfs                                                    1048576       12   1048564   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                    3977956        0   3977956   0% /proc/acpi
tmpfs                                                    3977956        0   3977956   0% /sys/firmware
```

Perhaps, i can see that i'm actually not using the full space available on this block storage. I've also checked in longhorn UI : 
**Size: 2 Gi
Actual Size: 721 Mi**

This problem arrived after some multiples tests i've done, deleting and recreating helm deployments. I guess previous data written on the disk is not fully removed from the disk when the pvc is deleted maybe ?

## To Reproduce

From what i've seen here, i guess it comes from old data which is not properly cleaned up between deployments (when deleting pvc).

1. Install Rancher using RKE
2. Provision cluster using Rancher UI and docker
3. Install Longhorn through UI in cluster
4. Install and delete a new deployement multiple times, with a block volume of 1Gi, and provision each time a 500MB file
5. Face the error randomly after some deployments.

## Expected behavior

I should be able to write data until the actual size is not >= to the block storage size.

## Environment

 - Longhorn version: v1.3.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher UI (Cluster tools) using helm.
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 3 (ETCD / Control plane)
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Debian 11
   - CPU per node: 4
   - Memory per node: 8G
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 500 Mbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): OVH Public Cloud Instances
 - Number of Longhorn volumes in the cluster: 6 volumes

## Additionnal informations

``` text
> kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:52:11Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:51:36Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.23) exceeds the supported minor version skew of +/-1
```

**Comment by derekbit** [comment]
Can you check the disks' space usage on each node?

**Comment by Brawcks** [comment]
Hi there, thanks for your answer :) 

I've checked both 3 nodes : 

``` text
debian@node1:~$ df -h
Filesystem           Size  Used Avail Use% Mounted on
udev                 3.8G  8.0K  3.8G   1% /dev
tmpfs                777M  3.3M  774M   1% /run
/dev/sda1             50G   31G   17G  64% /
tmpfs                3.8G     0  3.8G   0% /dev/shm
tmpfs                5.0M     0  5.0M   0% /run/lock
/dev/sda15           124M  5.9M  118M   5% /boot/efi
/dev/mapper/vg-home  196G  5.4G  181G   3% /mnt/longhorn-storage
tmpfs                777M     0  777M   0% /run/user/1000


debian@node2:~$ df -h
Filesystem           Size  Used Avail Use% Mounted on
udev                 3.8G  8.0K  3.8G   1% /dev
tmpfs                777M  3.3M  774M   1% /run
/dev/sdb1             50G   25G   23G  52% /
tmpfs                3.8G     0  3.8G   0% /dev/shm
tmpfs                5.0M     0  5.0M   0% /run/lock
/dev/sdb15           124M  5.9M  118M   5% /boot/efi
/dev/mapper/vg-home  196G  5.4G  181G   3% /mnt/longhorn-storage
tmpfs                777M     0  777M   0% /run/user/1000

debian@node3:~$ df -h
Filesystem           Size  Used Avail Use% Mounted on
udev                 3.8G  8.0K  3.8G   1% /dev
tmpfs                777M  6.2M  771M   1% /run
/dev/sda1             50G   21G   27G  43% /
tmpfs                3.8G     0  3.8G   0% /dev/shm
tmpfs                5.0M     0  5.0M   0% /run/lock
/dev/sda15           124M  5.9M  118M   5% /boot/efi
/dev/mapper/vg-home  196G  3.8G  183G   3% /mnt/longhorn-storage
tmpfs                777M     0  777M   0% /run/user/1000
```

All nodes seems OK here. Longhorn uses block storage provisionned by OVH.

Thanks !

**Comment by derekbit** [comment]
Looks the disk space is still enought. Can you check the indoe usage of the volume inside the container by `df -i /opt/odoo/web`?

**Comment by Brawcks** [comment]
Bruh, thats it ! It seems to be full : 

``` text
subteno@client-0:/opt/odoo/web$ df -i
Filesystem                                              Inodes   IUsed   IFree IUse% Mounted on
overlay                                                3268608 1108536 2160072   34% /
tmpfs                                                   994489      17  994472    1% /dev
/dev/sda1                                              3268608 1108536 2160072   34% /etc/hosts
shm                                                     994489       1  994488    1% /dev/shm
10.43.154.39:/pvc-c61f583c-2fc3-48ac-a335-016f3e061322  131072  131072       0  100% /opt/odoo/web
tmpfs                                                   994489       9  994480    1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                   994489       1  994488    1% /proc/acpi
tmpfs                                                   994489       1  994488    1% /sys/firmware
```

Is there a way to reclaim the space used here ?

**Comment by derekbit** [comment]
The total inode number is adjusted while formatting the filesystem. 
Please refer to `-N number-of-inodes` in https://linux.die.net/man/8/mkfs.ext4.

You can estimate the amount of the inodes and set the value as described in https://longhorn.io/docs/1.3.0/references/settings/#custom-mkfsext4-parameters.
Then, the indoe number of the newly created/formatted filesystem of the volume will follow the setting.

**Comment by Brawcks** [comment]
Thanks for theses informations, i did not know about it, gonna check now ! Thanks btw, topic can be closed :)

**Comment by derekbit** [comment]
Feel free to re-open it if there is any question. :)
