### ISSUE TITLE
[IMPROVEMENT] Prevent users from accidentally uninstalling Longhorn

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4509]
## Is your improvement request related to a feature? Please describe

To avoid any data loss by involuntary uninstall, so it's better to keep volume data after uninstalling longhorn. However, there will be a downside which is users need to clean up volume data on their own if they don't want them afterward.

Also, see whether when reinstalling longhorn after that, all things still go well, or if there are any compatibility concerns like installing different longhorn versions w/ previously kept data. 

## Describe the solution you'd like

Leverage `helm.sh/resource-policy` for chart part and need to update uninstall process accordingly to avoid deleting volume data before we can tackle https://github.com/longhorn/longhorn/pull/3224#issuecomment-986391892.

**Comment by innobead** [comment]
@PhanLe1010 Please help investigate this as a priority. 

This has been raised again due to a recent 3rd party gitops solution  issue like Rancher fleet would accidentally uninstall longhorn.

**Comment by PhanLe1010** [comment]
### Usecase:

1. keep the following resources
	1. Replicas
	1. Engines
	1. Volumes
	1. Snapshot
	1. Setting
1. Recover by installing the **same** Longhorn version 
1. Provide a `clean-up` deamonset that will read the `setting` CRs to determine the replica location and clean up all replica directories as well as the above CRs

### Implementation:
Creating a new setting, `keep-volume-data-when-uninstalling`. By default, this setting is `false` which is the current behavior. When the users turn on this setting, the uninstalling controller will not delete the above CRs. 

In addition, we have to keep the CRD as well
1. Helm
    1. Considering adding a new helm value, `keep-crds`, to specify the annotation `helm.sh/resource-policy` for CRDs
1. Rancher chart
    1. CRDs is a separate chart but will use the same helm value as above
1. Kubectl 
    1. There is no way to prevent users from deleting CRs using `kubectl`

**Comment by joshimoo** [comment]
Just leaving a note here, for 3. If I am not mistaken one can use a mutating admission webhook to prevent deletions, is my understanding correct on this @derekbit

**Comment by PhanLe1010** [comment]
Thanks @joshimoo for the design idea in the today's meeting (`Preferrable write some yaml data to the volumes on the disks and read it back when reinstalling Longhorn. `). Could you note it down here again?

**Comment by PhanLe1010** [comment]
Together with https://github.com/longhorn/longhorn/issues/4711, the flow is:
1. Longhorn has a custom resource definition called [settings.longhorn.io](http://settings.longhorn.io/)
1. Longhorn instantiates a boolean value CR of this CRD called deleting-confirmation-flag
1. When users uninstall Longhorn chart, there is a `pre-delete` helm hook which is a Kubernetes job [here](https://github.com/longhorn/longhorn/blob/master/chart/templates/uninstall-job.yaml) that run some checking logics including checking if the above flag is set to true ,[link](https://github.com/longhorn/longhorn-manager/blob/56e0584cac058bbeb101f33e82cd730f1c563f33/controller/uninstall_controller.go#L328-L336)
1. If the `deleting-confirmation-flag` is currently `false` the `pre-delete` hook will fail thus Helm uninstallation fail.
1. User will be given 2 options at this moment:
    * If the deletion is intended, just  `kubectl edit settings.longhorn.io deleting-confirmation-flag -n longhorn-system` to set the flag to true and retry `helm uninstall`
    * If the deletion is not intended (the Rancher Fleet bug), the user can cancel the uninstallation by `helm rollback` to latest revision.


Additional context:
I was trying to stream the uninstallation pod's logs to show users when they run `helm uninstall` for quicker feedback about the error but it is currently not possible yet. Ref: https://github.com/helm/helm/pull/10309

**Comment by PhanLe1010** [comment]
**Test step:**
> Note that this issue should be tested together with https://github.com/longhorn/longhorn/issues/4711

1. Install Longhorn using helm chart at master branch https://github.com/longhorn/longhorn/tree/master/chart
    1. `git clone https://github.com/longhorn/longhorn.git`
    1. `helm upgrade --install longhorn ./chart --namespace longhorn-system --create-namespace`
1. Case 1: the flag `deleting-confirmation-flag` is `false`
    1. Try to uninstall Longhorn `helm uninstall longhorn -n longhorn-system --debug`
    1. The uninstallation should fail
    1. Check the logs of the uninstallation pod inside `longhorn-system`, it should yelling that it failed because `deleting-confirmation-flag` is `false`
    1. If users want to cancel the uninstallation (a.k.a, this is an unexpected uninstallation). User can run `helm list -n longhorn-system -a` to list the latest revision of the release. Then `helm rollback longhorn <latest-revision> -n longhorn-system`
    1. If users want to retry uninstallation (a.k.a, this is an intended uninstallation), user can set `deleting-confirmation-flag` to  `true` by Longhorn UI or `kubectl edit settings.longhorn.io deleting-confirmation-flag -n longhorn-system`. Then retry `helm uninstall longhorn -n longhorn-system --debug`
1. Case 1: the flag `deleting-confirmation-flag` is `true`
    1. Try to uninstall Longhorn `helm uninstall longhorn -n longhorn-system --debug`
    1. The uninstallation should succeed

**Comment by PhanLe1010** [comment]
Should we put this one into the release note stating that users would need to set the lag `deleting-confirmation-flag` is `true` to be able to uninstall Longhorn @innobead?

**Comment by innobead** [comment]
YES, because it's a behavior change.

**Comment by PhanLe1010** [comment]
Thank you. May be we can point the release note to our doc https://github.com/longhorn/website/pull/595

**Comment by kladiv** [comment]
+1 totally required. In my opinion:
- Longhorn uninstall job should not have` --force` flag by default
- Longhorn uninstall should not proceed if there're Volumes in _attached_ status by default
- The --force behaviour should be configurable by the user (maybe using `deleting-confirmation-flag` you're talking about)

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn/longhorn 777bc5b) by following [the test steps](https://github.com/longhorn/longhorn/issues/4509#issuecomment-1278206383), the `deleting-confirmation-flag` flag works as expected.

**Comment by yangchiu** [comment]
> +1 totally required. In my opinion:
> 
>     * Longhorn uninstall job should not have` --force` flag by default
> 
>     * Longhorn uninstall job should not proceed if there're Volumes in _attached_ state by default
> 
>     * The `--force` behaviour should be configurable by the user (maybe using `deleting-confirmation-flag` you're talking about)

@PhanLe1010 @innobead what do you think?

**Comment by PhanLe1010** [comment]
I think `deleting-confirmation-flag` should be enough to prevent the accident. We don't need 3-step verification by allowing customization of the `--force` flag in the uninstallation job.
