### ISSUE TITLE
[BACKPORT][v1.2.x][TEST] Add automation test case for orphaned backup cleanup

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#4514]
ref: https://github.com/longhorn/longhorn/issues/4481

**Comment by chriscchien** [comment]
Test case `test_backup_failed_enable_auto_cleanup` and `test_backup_failed_disable_auto_cleanup` had consistent test result on[ v1.2.x](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/227/testReport/tests/test_basic/) pipeline

**Comment by chriscchien** [comment]
Close this ticket, test case passed consistent on v1.2.x [pipeline](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/236/testReport/tests/test_basic/)
