### ISSUE TITLE
[BACKPORT][v1.3.x][TEST] Add automation test case for orphaned backup cleanup

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#4515]
ref: https://github.com/longhorn/longhorn/issues/4481

**Comment by chriscchien** [comment]
Test case `test_backup_failed_enable_auto_cleanup` and `test_backup_failed_disable_auto_cleanup` had consistent test result on[ v1.3.x](https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-tests-sles-amd64/144/testReport/tests/test_basic/) pipeline

**Comment by chriscchien** [comment]
Close this ticket, test case passed consistent on v1.3.x [pipeline](https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-tests-sles-amd64/153/testReport/tests/test_basic/)
