### ISSUE TITLE
[BUG] After migration of Longhorn from Rancher old UI to dashboard, the csi-plugin doesn't update

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#4519]
## Describe the bug

Do a migration from Rancher old UI to dashboard using https://longhorn.io/kb/how-to-migrate-longhorn-chart-installed-in-old-rancher-ui-to-the-chart-in-new-rancher-ui/, the csi-plugin doesn't update and remains with the longhornio image instead of Rancher mirrored image.

## To Reproduce

1. Set up a cluster of Kubernetes 1.20.
1. Access old rancher UI by navigating to `<your-rancher-url>/g`.
1. Install Longhorn 1.0.2.
1. Create/attach some volumes. Create a few recurring snapshot/backup job that run every minutes.
1. Upgrade Longhorn to v1.2.4.
1. Migrate Longhorn to new chart in new rancher UI https://longhorn.io/kb/how-to-migrate-longhorn-chart-installed-in-old-rancher-ui-to-the-chart-in-new-rancher-ui/.
1. Check the csi plugin image

## Expected behavior

The CSI plugin image should also be updated to rancher mirrored image

## Log or Support bundle

<img width="1537" alt="Screen Shot 2022-09-01 at 3 10 54 PM" src="https://user-images.githubusercontent.com/60111667/188244752-1451fbf6-8b1c-4662-993c-1f7be0179dbb.png">

## Environment

 - Longhorn version: v1.2.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.20

**Comment by PhanLe1010** [comment]
The bug is because this logic only checks for the changes in the image of deployments (attacher/resizer/...) but forgets that longhorn-csi is a daemonset and its image also needs to be checked https://github.com/longhorn/longhorn-manager/blob/127a37f605b13e133a547dfc89470cf3670e2236/csi/deployment_util.go#L239-L247

**Comment by khushboo-rancher** [comment]
cc: @innobead

**Comment by innobead** [comment]
This should be a simple fix. @mantissahz Please help with this. Thanks.

**Comment by chriscchien** [comment]
Hi @khushboo-rancher, for now we did not have Rancher chart to install Longhorn master to verify this ticket, is it OK to wait until 1.4.2 Rancher chart release and then start test with that chart? thank you.

cc @innobead, @mantissahz

**Comment by khushboo-rancher** [comment]
@chriscchien From user perspective, I don't think we need to test this with 1.4.2. As this migration was for old Rancher UI and 1.2.x Longhorn.

@mantissahz Is there a way to test the code change without performing migration?

**Comment by khushboo-rancher** [comment]
Let's test a regular upgrade when 1.5-rc is available. They should be fine to verify this.
Thanks @mantissahz

**Comment by innobead** [comment]
@roger-ryao Please help test this instead. Thanks.

**Comment by roger-ryao** [comment]
**Verified on v1.5.x-head 20230613**

- longhorn v1.5.x-head https://github.com/longhorn/longhorn/commit/ea30dc3dcc5625f5cd83ab8ff1e2622c3d5e3b3e

**Verified on master-head 20230613**

- longhorn master-head https://github.com/longhorn/longhorn/commit/b8069c547ba1c53b5d4084cd63f6b80bc10b9a50

**The test steps**
https://github.com/longhorn/longhorn/issues/4519#issuecomment-1521021960
https://github.com/longhorn/longhorn/issues/4519#issuecomment-1556815568



**Result**

- [x] 1. Install Longhorn v1.4.1 by kubectl > Upgrade Longhorn to v1.5.x-head by kubectl
- [x] 2. Install Longhorn v1.4.1 by kubectl > Upgrade Longhorn to master-head by kubectl
- [x] 3. Install Longhorn v1.4.1 by helm > Upgrade Longhorn to v1.5.x-head by helm
- [x] 4. Install Longhorn v1.4.1 by helm > Upgrade Longhorn to master-head by helm
**Item 1-4: The Longhorn CSI plugin will be upgraded from v2.5.0 to v2.7.0.**

- [ ] 5. Install Longhorn v1.4.1 by Rancher > Upgrade Longhorn to v1.5.0 by Rancher
**Note: Rancher chart PR is not yet ready, so testing is pending**

**Comment by khushboo-rancher** [comment]
This should be good to close. Tanks @roger-ryao
