### ISSUE TITLE
[TASK] Disable doc search for archived versions < 1.1

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4524]
## What's the task? Please describe

Currently, users are still able to search docs from archived versions, so it will cause some confusion about the search result. Go disable versions before 1.1, and it's better to see if there is an automatic way to do that via docsearch configs in the website repo.  

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] Disable archived doc search

## Additional context

Add any other context or screenshots about the task request here.

**Comment by mantissahz** [comment]
Add a rule `exclusionPatterns: ["https://longhorn.io/docs/archives/**"]` to Algolia crawler to bypass the indexing of URLs with prefix `https://longhorn.io/docs/archives`.
And it should work now.
