### ISSUE TITLE
[BUG] Unable to delete namespace longhorn-system in Rancher version 2.6.0

### ISSUE THREAD

**Issue by afrozk** [longhorn/longhorn#4529]
## Describe the bug

Unable to delete longhorn-system namespace in Rancher version 2.6.0

## To Reproduce

1. Installed longhorn on Rancher Version 2.5.14 using helm chart using private registry. 
2. Created a storage class 'longhorn'
3. Added ingress to helm chart and upgraded
4. Upgraded Rancher server to 2.6.0
5. uninstalled loghorn using helm chart
6. delete longhorn-system namespace (k delete namespace longhorn-system)
7. Unable to delete longhorn-system namespace output of k delete namespace longhorn-system is "namespace "longhorn-system" deleted" and struck in terminating state since 2 days
8. Run 'kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found -n longhorn-system' returns
NAME                         READY   ALLOWSCHEDULING   SCHEDULABLE   AGE
node.longhorn.io/Host1   True    true              True          4d17h
node.longhorn.io/Host2   True    true              True          4d17h
node.longhorn.io/Host3   True    true              True          4d17h

## Expected behavior
namespace longhorn-system should be deleted successfully

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.3.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster: 2
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: RHEL Server 7.9
   - CPU per node: 4
   - Memory per node: 4GB
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 0

**Comment by c3y1huang** [comment]
This issue has been inactive for a long time, the information may be outdated. Please create a new issue if come across a similar situation.
