### ISSUE TITLE
[TEST] Add automated test items to check whether the backup access mode is stored and the correctness of restore.

### ISSUE THREAD

**Issue by weizhe0422** [longhorn/longhorn#4531]
## What's the test to develop? Please describe
Add test cases for #3444 to check whether the backup access mode is stored and the correctness of restore.

## Describe the items of the test development (DoD, definition of done) you'd like
 - [x] Add test skeleton.

   1. Create `ReadWriteMany (rwx)`  volume and attached to one node.
   2. Create a backup for the volume.
   3. Restore the backup without specific access mode
   4. Check the restored volume's access mode should be  `ReadWriteMany (rwx)`
   5. Restoring the backup using the `ReadWriteOnce (rwo)` access mode
   6. Check the restored volume's access mode should be `ReadWriteOnce (rwo)`

 - [x] Implement automation test case
   Add e2e test case to check: [Longhorn-test PR #1101](https://github.com/longhorn/longhorn-tests/pull/1101)

## Additional context
https://github.com/longhorn/longhorn/issues/3444#issuecomment-1237656060

**Comment by innobead** [comment]
https://github.com/longhorn/longhorn-tests/pull/1101#pullrequestreview-1126291394
