### ISSUE TITLE
[BUG] error listing backup volume names on S3

### ISSUE THREAD

**Issue by QJoly** [longhorn/longhorn#4533]
## Describe the bug
I'm using contabo S3 to keep my backup on a offsite. 
I have 2 K3S clusters : Homekube(longhorn v1.3.0) and Cloudkube(longhorn v1.3.1)

Homekube can connect to the s3 contabo server, but not Cloudkube. 
The error on Homekube is : 
```
error listing backup volume names: timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.3.1/longhorn [backup ls --volume-only s3://homekube@default/], output , stderr, , error <nil>
```
 
## To Reproduce

1. Configure secret to access s3 (and backup location ex: s3://homekube@default/) 
2. Check existing backup on "backups" page 
3. Be sad and see error

## Expected behavior

I should be able to see existing backups

## Log or Support bundle

I have my support Bundle, but can't upload it here (i'm not used to write bug report)

## Environment

 - Longhorn version: v.1.3.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Debian 11
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Debian 11
   - CPU per node: 4
   - Memory per node: 4Go
   - Disk type(e.g. SSD/NVMe): virtual hdd
   - Network bandwidth between the nodes: 100mb/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM on Proxmox
 - Number of Longhorn volumes in the cluster: 5 

## Additional context

Thanks for your amazing work

**Comment by QJoly** [comment]
[longhorn-support-bundle_1fa862c0-e853-4208-bb57-ade1dd187758_2022-09-07T13-51-38Z.zip](https://github.com/longhorn/longhorn/files/9506803/longhorn-support-bundle_1fa862c0-e853-4208-bb57-ade1dd187758_2022-09-07T13-51-38Z.zip)

**Comment by mantissahz** [comment]
Hi @QJoly,
Did you try another way to access the bucket `homekube` on the S3 server `default` and work normal?

**Comment by QJoly** [comment]
> Hi @QJoly, Did you try another way to access the bucket `homekube` on the S3 server `default` and work normal?

Hi,  
"default" is my region (according to contabo documentation), and the same configuration works on the k3s cluster "Homekube". 
(I would like the k3s Homekube cluster to use the bucket identical to its name (and the same for cloudkube, i configured the homekube bucket on the cloudkube cluster only for testing))

I can use the AWS default CLI to my s3 server: 
```bash
kiko@DESKTOP-QDUG9VC:~$ aws --profile eu2 --region default --endpoint-url https://eu2.contabostorage.com s3 ls
2022-09-07 12:39:13 cloudkube
2022-09-01 14:51:22 homekube
2022-07-20 15:31:54 terraform
```

**Comment by mantissahz** [comment]
Hi, @QJoly 
Could you check that it is working in the pod such as `longhorn-manager` as well?
and also try this change the backup target to `s3://homekube@eu2.contabostorage.com` then check "backups" page again.
