### ISSUE TITLE
[BUG] Backups got deleted, unclear wording of log message

### ISSUE THREAD

**Issue by danielb42** [longhorn/longhorn#4536]
Hi, at some random point last night (no Recurring Job running at that time) longhorn decided to remove all backups of one specific volume. In the logs of longhorn-manager there's this message:

`time="2022-09-07T23:14:41Z" level=info msg="Found 7 backups in the backup target that do not exist in the backup target and need to be deleted" backupVolume=pvc-3f.....`

Now, what is "Found x backups in the backup target that do not exist in the backup target" supposed to mean? (How can they simultaneously not exist and yet "be found"??) 

Did those backups vanish at my S3 storage provider, and then longhorn cleaned up the local side, or is it the other way round, that the backups got lost locally somehow and then longhorn cleaned up at the S3 provider? I cannot quite extract from the messages' wording on which side the issue originates.

Also, where could I look for the true cause of why those backups vanished in the first place?

Thank you!

// longhorn 1.3.1 on k3s 1.24

**Comment by mantissahz** [comment]
Hi @danielb42 
Sorry for the confusing the message.

This message means it found the backups in the cluster that were not existed in the backup target (S3 server)

Some quick question:
Volume size and size of data written into the volume.
Do you use the recurringJob to backup the volume?

That would be great if you could provide the support bundle to figure out the root cause.

**Comment by danielb42** [comment]
Hi @mantissahz, thanks for the quick reply. Unfortunately I won't be able to provide further data any time soon. Should this happen again, I'll open another issue with a support bundle. Maybe you can still see to fix the log message though..

Thank you!

**Comment by danielb42** [comment]
@mantissahz I received another hint on this matter.

```
time="2022-09-21T13:24:41Z" level=error msg="Error listing backups from backup target" backupVolume=pvc-d47c2002-a420-41d5-a8dc-ba8f697dbe36 controller=longhorn-backup-volume error="error listing volume pvc-d47c2002-a420-41d5-a8dc-ba8f697dbe36 backup: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.3.1/longhorn [backup ls --volume pvc-d47c2002-a420-41d5-a8dc-ba8f697dbe36 s3://backupbucket38493@nl-ams/], output failed to list objects with param: {\n  Bucket: \"backupbucket38493\",\n  Delimiter: \"/\",\n  Prefix: \"/\"\n} error: AWS Error:  RequestError send request failed Get \"https://s3.nl-ams.scw.cloud/backupbucket38493?delimiter=%!F(MISSING)&prefix=%!F(MISSING)\": read tcp 10.42.0.71:57658->163.172.208.8:443: read: connection reset by peer\n\n, stderr, time=\"2022-09-21T13:24:41Z\" level=error msg=\"Fail to list s3: failed to list objects with param: {\\n  Bucket: \\\"backupbucket38493\\\",\\n  Delimiter: \\\"/\\\",\\n  Prefix: \\\"/\\\"\\n} error: AWS Error:  RequestError send request failed Get \\\"https://s3.nl-ams.scw.cloud/backupbucket38493?delimiter=%!F(MISSING)&prefix=%!F(MISSING)\\\": read tcp 10.42.0.71:57658->163.172.208.8:443: read: connection reset by peer\\n\" pkg=s3\ntime=\"2022-09-21T13:24:41Z\" level=error msg=\"failed to list objects with param: {\\n  Bucket: \\\"backupbucket38493\\\",\\n  Delimiter: \\\"/\\\",\\n  Prefix: \\\"/\\\"\\n} error: AWS Error:  RequestError send request failed Get \\\"https://s3.nl-ams.scw.cloud/backupbucket38493?delimiter=%!F(MISSING)&prefix=%!F(MISSING)\\\": read tcp 10.42.0.71:57658->163.172.208.8:443: read: connection reset by peer\\n\"\n, error exit status 1" node=master

time="2022-09-21T13:24:41Z" level=info msg="Found 7 backups in the backup target that do not exist in the backup target and need to be deleted" backupVolume=pvc-32774b22-c83a-4290-994b-dc70e229be09 controller=longhorn-backup-volume node=master

time="2022-09-21T13:28:44Z" level=info msg="Complete deleting backup s3://backupbucket38493@nl-ams/?backup=backup-2bfeb8fbe3244ab1&volume=pvc-32774b22-c83a-4290-994b-dc70e229be09"
time="2022-09-21T13:28:44Z" level=info msg="Complete deleting backup s3://backupbucket38493@nl-ams/?backup=backup-b079d0351b734574&volume=pvc-32774b22-c83a-4290-994b-dc70e229be09"
time="2022-09-21T13:28:47Z" level=info msg="Complete deleting backup s3://backupbucket38493@nl-ams/?backup=backup-0088f09b33174063&volume=pvc-32774b22-c83a-4290-994b-dc70e229be09"
time="2022-09-21T13:28:50Z" level=info msg="Complete deleting backup s3://backupbucket38493@nl-ams/?backup=backup-ffccfd5b842b4544&volume=pvc-32774b22-c83a-4290-994b-dc70e229be09"
ti
(...)
```

So (having in mind that the second message means "7 backups found in cluster that do not exist in backup target"), the issue becomes quite clear. 

1) connection error prevents longhorn from seeing the backups in the remote
2) it immediately starts to clean up local snapshots (<--- that cannot be intended honestly)
3) now that the local snapshots are gone, the remote is "synced up", i.e. the remote snapshots are deleted

HTH.

**Comment by mantissahz** [comment]
@danielb42 Does this issue still happen?

**Comment by mantissahz** [comment]
Thank you @danielb42, I will keep track of this issue and try to reproduce it.
Another question is that could you list correct bucket's content in the manager pod or instance-manager-x pods?
And it will be great if you keep the support bundle when it happened again.
