### ISSUE TITLE
[BUG] Unable to attach volume, and pods are stuck in container creating state

### ISSUE THREAD

**Issue by psarvaiya** [longhorn/longhorn#4537]
## Describe the bug

I am doing assessment of the storage class on a single node k8s cluster. K8s version : 1.24.3
I have updated the longhorn system Config map and update the replica to 1. But, on UI volumes are stuck in attaching state.

From UI  I have updated the replica to 1 too.

I also tried this in latest version 1.3.1, facing the same issue. Please enable me with a work around for now. 

## Expected behavior

Volume should be attach successfully.

## Log or Support bundle

time="2022-09-08T11:54:17Z" level=warning msg="Error syncing Longhorn replica longhorn-system/pvc-bd8f9265-85dd-4130-93e7-0392a5e8285a-r-80d44514" controller=longhorn-replica error="fail to sync replica for longhorn-system/pvc-bd8f9265-85dd-4130-93e7-0392a5e8285a-r-80d44514: invalid Instance Manager instance-manager-r-82dae813, state: starting, IP: " node=migration-test-10-1-100-181.rcc.local
E0908 11:54:17.828606       1 replica_controller.go:179] fail to sync replica for longhorn-system/pvc-bd8f9265-85dd-4130-93e7-0392a5e8285a-r-80d44514: invalid Instance Manager instance-manager-r-82dae813, state: starting, IP:
time="2022-09-08T11:54:17Z" level=warning msg="Dropping Longhorn replica longhorn-system/pvc-bd8f9265-85dd-4130-93e7-0392a5e8285a-r-80d44514 out of the queue" controller=longhorn-replica error="fail to sync replica for longhorn-system/pvc-bd8f9265-85dd-4130-93e7-0392a5e8285a-r-80d44514: invalid Instance Manager instance-manager-r-82dae813, state: starting, IP: " node=migration-test-10-1-100-181.rcc.local
10.32.0.2 - - [08/Sep/2022:11:54:18 +0000] "GET /v1/nodes/migration-test-10-1-100-181.rcc.local HTTP/1.1" 200 1854 "" "Go-http-client/1.1"
10.32.0.2 - - [08/Sep/2022:11:54:18 +0000] "GET /v1/volumes/pvc-bd8f9265-85dd-4130-93e7-0392a5e8285a HTTP/1.1" 200 3313 "" "Go-http-client/1.1"
time="2022-09-08T11:54:18Z" level=debug msg="Volume pvc-bd8f9265-85dd-4130-93e7-0392a5e8285a is already attached to node migration-test-10-1-100-181.rcc.local"
10.32.0.2 - - [08/Sep/2022:11:54:18 +0000] "POST /v1/volumes/pvc-bd8f9265-85dd-4130-93e7-0392a5e8285a?action=attach HTTP/1.1" 200 2525 "" "Go-http-client/1.1"
time="2022-09-08T11:54:20Z" level=warning msg="Error syncing Longhorn instance manager longhorn-system/instance-manager-e-9086c964: fail to sync instance manager for longhorn-system/instance-manager-e-9086c964: failed to get Version of Instance Manager Client for instance-manager-e-9086c964, state: running, IP: 10.32.0.23, TLS: false, Error: failed to get version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.32.0.23:8500: i/o timeout\""
time="2022-09-08T11:54:20Z" level=info msg="Instance manager state is updated from starting to running after syncing with the pod" controller=longhorn-instance-manager instanceManager=instance-manager-e-9086c964 node=migration-test-10-1-100-181.rcc.local nodeID=migration-test-10-1-100-181.rcc.local
10.32.0.2 - - [08/Sep/2022:11:54:20 +0000] "GET /v1/volumes/pvc-bd8f9265-85dd-4130-93e7-0392a5e8285a HTTP/1.1" 200 3313 "" "Go-http-client/1.1"
10.32.0.2 - - [08/Sep/2022:11:54:22 +0000] "GET /v1/volumes/pvc-bd8f9265-85dd-4130-93e7-0392a5e8285a HTTP/1.1" 200 3313 "" "Go-http-client/1.1"
10.32.0.2 - - [08/Sep/2022:11:54:24 +0000] "GET /v1/volumes/pvc-bd8f9265-85dd-4130-93e7-0392a5e8285a HTTP/1.1" 200 3313 "" "Go-http-client/1.1"
10.32.0.2 - - [08/Sep/2022:11:54:26 +0000] "GET /v1/volumes/pvc-bd8f9265-85dd-4130-93e7-0392a5e8285a HTTP/1.1" 200 3313 "" "Go-http-client/1.1"
10.32.0.2 - - [08/Sep/2022:11:54:28 +0000] "GET /v1/volumes/pvc-bd8f9265-85dd-4130-93e7-0392a5e8285a HTTP/1.1" 200 3313 "" "Go-http-client/1.1"
10.32.0.2 - - [08/Sep/2022:11:54:30 +0000] "GET /v1/volumes/pvc-bd8f9265-85dd-4130-93e7-0392a5e8285a HTTP/1.1" 200 3313 "" "Go-http-client/1.1"
time="2022-09-08T11:54:31Z" level=warning msg="Error syncing Longhorn instance manager longhorn-system/instance-manager-r-82dae813: fail to sync ins

![image](https://user-images.githubusercontent.com/112694225/189116637-9d3a7f14-6a15-43db-ba49-db36030d96c4.png)

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.3.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 0
 - Node config
   - OS type and version: Centos
   - CPU per node:  4
   - Memory per node: 8
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Vmware
 - Number of Longhorn volumes in the cluster:

## Additional context

Please enable with workaround to enable with task

**Comment by psarvaiya** [comment]
Also, there is no taints on the node

**Comment by mantissahz** [comment]
Hi @psarvaiya 
Could you use this script [environment_check.sh](https://raw.githubusercontent.com/longhorn/longhorn/master/scripts/environment_check.sh) check the environment requirements and settings.
It would be great if you could provide the support bundle, thank you.
