### ISSUE TITLE
[TEST] Analyze failed e2e cases in 1.2.x-head pipeline

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#4541]
#### [v1.2.x-longhorn-tests-sles-amd64](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/test_results_analyzer/)

- ~~tests.test_cloning.test_cloning_interrupted~~
  - https://github.com/longhorn/longhorn-tests/pull/1089
    - [8cad8e](https://github.com/longhorn/longhorn-tests/commit/8cad8e3511b9daf4593b4e11cd2da896361ba03b) need to merge to v1.2.X
- tests.test_engine_upgrade.test_engine_live_upgrade_while_replica_concurrent_rebuild
  - https://github.com/longhorn/longhorn/issues/4547
- ~~tests.test_settings.test_setting_concurrent_rebuild_limit~~
  - ```pytest -v -k test_setting_concurrent_rebuild_limit --count 5 ```
  - 5 times on local and can not reproduce, need to check the test case flow
- tests.test_basic.test_allow_volume_creation_with_degraded_availability
  - ```pytest -v test_basic.py::test_allow_volume_creation_with_degraded_availability --count 20```
  - 20 times on local and can be reproduced 7 times, need to check the test case
- tests.test_ha.test_autosalvage_with_data_locality_enabled
  - https://github.com/longhorn/longhorn/issues/4489
- ~~tests.test_node.test_node_eviction_multiple_volume~~
  - ```pytest -v -k test_node_eviction_multiple_volume --count 5 ```
  - 5 times on local and can not reproduce, need to check the test case flow
---
#### [v1.2.x-longhorn-tests-sles-arm64](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/test_results_analyzer/)
---
#### [v1.2.x-longhorn-upgrade-tests-sles-amd64](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-upgrade-tests-sles-amd64/test_results_analyzer/)

---
## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] If any real issue found, create a bug for that.
- [ ] If any test case issue found, create a test task for that to fix it.

## Additional context

Add any other context or screenshots about the test request here.

**Comment by Lichiehyao** [comment]
`test_engine_live_upgrade_while_replica_concurrent_rebuild` failed case due to [4547](https://github.com/longhorn/longhorn/issues/4547)

**Comment by Lichiehyao** [comment]
The [#4547](https://github.com/longhorn/longhorn/issues/4547) PR was submitted yesterday.
We found out the new failed test case `test_migration_with_unscheduled_replica` failed since build 221 and create the ticket  [#4585](https://github.com/longhorn/longhorn/issues/4585)

**Comment by Lichiehyao** [comment]
#### [v1.2.x-longhorn-tests-sles-arm64 229 build 20220922](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/229/)
- [ ] [tests.test_backing_image.test_engine_offline_upgrade_with_backing_image](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/229/testReport/junit/tests/test_backing_image/test_engine_offline_upgrade_with_backing_image/)

- [ ] [tests.test_backing_image.test_engine_live_upgrade_with_backing_image](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/229/testReport/junit/tests/test_backing_image/test_engine_live_upgrade_with_backing_image/)
- [x] [tests.test_basic.test_allow_volume_creation_with_degraded_availability](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/229/testReport/junit/tests/test_basic/test_allow_volume_creation_with_degraded_availability/)
  - This case would be failed randomly, need to check the test case
- [ ] [tests.test_engine_upgrade.test_engine_offline_upgrade](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/229/testReport/junit/tests/test_engine_upgrade/test_engine_offline_upgrade/)
- [ ] [tests.test_engine_upgrade.test_engine_live_upgrade](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/229/testReport/junit/tests/test_engine_upgrade/test_engine_live_upgrade/)
- [ ] [tests.test_engine_upgrade.test_engine_live_upgrade_with_intensive_data_writing](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/229/testReport/junit/tests/test_engine_upgrade/test_engine_live_upgrade_with_intensive_data_writing/)
- [ ] [tests.test_engine_upgrade.test_engine_live_upgrade_while_replica_concurrent_rebuild](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/229/testReport/junit/tests/test_engine_upgrade/test_engine_live_upgrade_while_replica_concurrent_rebuild/)
- [x] [tests.test_node.test_node_eviction_multiple_volume](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/229/testReport/junit/tests/test_node/test_node_eviction_multiple_volume/)
  - rerun and can not reproduce, need to check the test case flow
- [x] [tests.test_ha.test_autosalvage_with_data_locality_enabled](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/229/testReport/junit/tests/test_ha/test_autosalvage_with_data_locality_enabled/)
  - https://github.com/longhorn/longhorn/issues/4382
- [ ] [tests.test_migration.test_migration_with_unscheduled_replica](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/229/testReport/junit/tests/test_migration/test_migration_with_unscheduled_replica/)
  - https://github.com/longhorn/longhorn/issues/4585

**Comment by Lichiehyao** [comment]
#### [v1.2.x-longhorn-tests-sles-amd64 257 build 20221018](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/257/#showFailuresLink)
- [ ] [tests.test_cloning.test_cloning_with_detached_source_volume](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/257/testReport/junit/tests/test_cloning/test_cloning_with_detached_source_volume/)
- [x] [tests.test_ha.test_autosalvage_with_data_locality_enabled](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/257/testReport/junit/tests/test_ha/test_autosalvage_with_data_locality_enabled/)
  - https://github.com/longhorn/longhorn/issues/4382
- [ ] [tests.test_settings.test_setting_concurrent_rebuild_limit](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/257/testReport/junit/tests/test_settings/test_setting_concurrent_rebuild_limit/)
- [x] [tests.test_basic.test_allow_volume_creation_with_degraded_availability_restore[s3]](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/257/testReport/junit/tests/test_basic/test_allow_volume_creation_with_degraded_availability_restore_s3_/)
    - We observed the same symptom on the master-head https://github.com/longhorn/longhorn/issues/4719
- [ ] [tests.test_basic.test_allow_volume_creation_with_degraded_availability](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/257/testReport/junit/tests/test_basic/test_allow_volume_creation_with_degraded_availability/)
- [x] [tests.test_migration.test_migration_with_unscheduled_replica](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/257/testReport/junit/tests/test_migration/test_migration_with_unscheduled_replica/)
    - https://github.com/longhorn/longhorn/issues/4585

**Comment by Lichiehyao** [comment]
[test_backing_image_auto_resync](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/265/testReport/junit/tests/test_backing_image/test_backing_image_auto_resync_https___longhorn_backing_image_s3_us_west_1_amazonaws_com_parrot_qcow2_/)
- https://github.com/longhorn/longhorn/issues/4738

**Comment by Lichiehyao** [comment]
[test_allow_volume_creation_with_degraded_availability](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-upgrade-tests-sles-arm64/264/testReport/junit/tests/test_basic/test_allow_volume_creation_with_degraded_availability/)
- https://github.com/longhorn/longhorn/issues/4787

**Comment by Lichiehyao** [comment]
[v1.2.x-longhorn-tests-sles-amd64 272 build 20221031](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/272/testReport/)
- [ ] test_node.py::test_node_eviction_multiple_volume
- [ ] test_rwx.py::test_rwx_parallel_writing

[v1.2.x-longhorn-upgrade-tests-sles-amd64 262 build 20221031](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-upgrade-tests-sles-amd64/262/testReport/)
- [ ] test_cloning.py::test_cloning_with_detached_source_volume
- [ ] test_node.py::test_node_eviction_multiple_volume

[v1.2.x-longhorn-tests-sles-arm64 271 build 20221031](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/271/testReport/)
- [ ] test_ha.py::test_extra_replica_cleanup

[v1.2.x-longhorn-upgrade-tests-sles-arm64 271 build 20221031](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-upgrade-tests-sles-arm64/268/testReport/)

---
- [x] test_allow_volume_creation_with_degraded_availability_restore[s3]
- https://github.com/longhorn/longhorn/issues/4791

- [x] tests.test_basic.test_allow_volume_creation_with_degraded_availability
- https://github.com/longhorn/longhorn/issues/4787

**Comment by Lichiehyao** [comment]
https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/275/
- [ ] test_settings.test_setting_concurrent_rebuild_limit
- [x] test_allow_volume_creation_with_degraded_availability_restore[s3]
  -  https://github.com/longhorn/longhorn-tests/pull/1164
- [x] test_migration_with_unscheduled_replica
  - https://github.com/longhorn/longhorn-tests/pull/1164
- [x] test_cloning_with_detached_source_volume
  - https://github.com/longhorn/longhorn/issues/4585
- [x] test_autosalvage_with_data_locality_enabled
  - https://github.com/longhorn/longhorn/issues/4382
  ---
https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-upgrade-tests-sles-arm64/271/
- [ ] test_setting_concurrent_rebuild_limit
- [ ] test_backup_lock_creation_during_deletion
- [x] test_allow_volume_creation_with_degraded_availability_restore[s3]
  -  https://github.com/longhorn/longhorn-tests/pull/1164
- [x] test_migration_with_unscheduled_replica
  - https://github.com/longhorn/longhorn-tests/pull/1164
- [x] test_cloning_with_detached_source_volume
  - https://github.com/longhorn/longhorn/issues/4585
- [x] test_autosalvage_with_data_locality_enabled
  - https://github.com/longhorn/longhorn/issues/4382
---
https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-upgrade-tests-sles-amd64/265/
- [x] test_allow_volume_creation_with_degraded_availability_restore[s3]
  -  https://github.com/longhorn/longhorn-tests/pull/1164
- [x] test_migration_with_unscheduled_replica
  - https://github.com/longhorn/longhorn-tests/pull/1164
---
https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/275/
- [x] test_allow_volume_creation_with_degraded_availability_restore[s3]
  -  https://github.com/longhorn/longhorn-tests/pull/1164
- [x] test_migration_with_unscheduled_replica
  - https://github.com/longhorn/longhorn-tests/pull/1164
- [x] test_autosalvage_with_data_locality_enabled
  - https://github.com/longhorn/longhorn/issues/4382
- [x] tests.test_node.test_node_eviction_multiple_volume
  - Flaky case: incidence rate = 20%  [Previous report](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2265/)

**Comment by roger-ryao** [comment]
Update the flaky cases 
https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/276/#showFailuresLink
- [ ] test_recurring_job_labels
  - https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2335/
- [ ] test_recurring_job_kubernetes_status
  - https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2336/
---
https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/276/
- [ ] test_data_locality_basic
  - https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2334/

---
https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-upgrade-tests-sles-amd64/266/
- [ ] test_backup_status_for_unavailable_replicas
  - https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2333/

**Comment by roger-ryao** [comment]
https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/279
- [ ] test_engine_live_upgrade_while_replica_concurrent_rebuild
  - https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2381/

**Comment by roger-ryao** [comment]
I observe this error first time on case [test_cloning_with_detached_source_volume](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/280/testReport/junit/tests/test_cloning/test_cloning_with_detached_source_volume/)

**Comment by yangchiu** [comment]
Probably spending time on investigating the root cause is more useful than measuring the reproducibility?

**Comment by roger-ryao** [comment]
> Probably spending time on investigating the root cause is more useful than measuring the reproducibility?

@yangchiu  Sure. I would start to investigate the root cause because I have finished the report collection on v1.2.x.

**Comment by roger-ryao** [comment]
Fix failed test case [test_offline_node](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-upgrade-tests-sles-arm64/291/testReport/junit/tests/test_infra/test_offline_node/)
  - https://github.com/longhorn/longhorn/issues/4921
    - https://github.com/longhorn/longhorn-tests/pull/1189

**Comment by roger-ryao** [comment]
We observed the new failed cases on 1.2.x CI daily-regression.
https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-upgrade-tests-sles-amd64/289/
  - [test_backup_lock_deletion_during_restoration](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-upgrade-tests-sles-amd64/289/testReport/junit/tests/test_basic/test_backup_lock_deletion_during_restoration_nfs_/)

https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-upgrade-tests-sles-arm64/
  - [test_rebuild_with_restoration](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-upgrade-tests-sles-arm64/294/testReport/junit/tests/test_ha/test_rebuild_with_restoration_nfs_/)

**Comment by roger-ryao** [comment]
Close it, because 1.2 daily EOL, 12/17
