### ISSUE TITLE
[BUG] Longhorn accidentally schedule all replicas onto a worker node eventhough the setting Replica Node Level Soft Anti-Affinity is currently disabled

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4546]
## Describe the bug

After a reboot a the worker node in a cluster that has 1 control node + 1 worker node, Longhorn accidentally schedules all replicas onto a worker node even though the setting `Replica Node Level Soft Anti-Affinity` is currently disabled

## To Reproduce

1. Create a cluster of 1 control node and 1 worker node. 
1. Deploy Longhorn 1.3.1. Keep every Longhorn settings has default
1. Deploy a test deployment that use pvc provisioned by Longhorn
1. Observe that there is currently only 1 replica of the volume is scheduled on the worker node. The other 2 replicas are unschedule
1. Restart the worker node
1. Observe that all replicas are scheduled onto the worker node.

## Expected behavior
The expectation is Longhorn doesn’t accidentally schedule all replicas onto the worker node as the setting Replica Node Level Soft Anti-Affinity is currently disabled

## Log or Support bundle
[longhorn-support-bundle_a84c2476-8a0f-4b1e-bdc2-10aae414f3c5_2022-09-12T22-08-15Z.zip](https://github.com/longhorn/longhorn/files/9552107/longhorn-support-bundle_a84c2476-8a0f-4b1e-bdc2-10aae414f3c5_2022-09-12T22-08-15Z.zip)

## Environment

 - Longhorn version: 1.3.1

**Comment by PhanLe1010** [comment]
@ w13915984028 is mentioning that this problem doesn't happen in Longhorn 1.3.0

However, I have not had time to test 1.3.0 yet.

**Comment by innobead** [comment]
@longhorn/qa this seems a regression, so please help check if this can be reproduced in 1.3.0 as well.

**Comment by khushboo-rancher** [comment]
@chriscchien Can you please help check this on 1.3.0?

**Comment by w13915984028** [comment]
FYI: It's reproducable in my ENV with LH v1.3.1;  in v1.3.0, I did not encounter this issue, but I also did not spend time to try to reproduce in v1.3.0.

Wait for QA's update about v1.3.0 . thanks.

also cc @guangbochen @bk201

**Comment by chriscchien** [comment]
I can reproduce in v1.3.1 but not in v1.3.0,
In v1.3.0, after reboot the only worker node ( which is worker 2 on my environment), only 1 replica will on worker node as below 
![Screenshot from 2022-09-21 13-39-18](https://user-images.githubusercontent.com/73337386/191423485-77d2f09c-fa46-4ffe-a59d-3a16b0d6bcf3.png)

cc @khushboo-rancher

**Comment by mantissahz** [comment]
@longhorn/qa 
I could reproduce this at v1.3.0 as the picture below
![v130](https://user-images.githubusercontent.com/14231257/192417730-e07a6eb9-03c5-4f76-bfd5-b308d43285e4.png)

**Comment by mantissahz** [comment]
https://github.com/longhorn/longhorn-manager/blob/master/scheduler/replica_scheduler.go#L172-L182
Rebooting only one work node in the cluster would make all replicas failed.
And `usedNodes` will be always empty therefore this work node will be schuedlable.

**Comment by chriscchien** [comment]
Thank @mantissahz ,
After retest this case on v1.3.0, I found I can reproduce error in my local environment, still need time to figure out why last time I can not reproduce.

Double checked on v1.2.5 and can be reproduced but not every time :
![Screenshot_20220927_120218](https://user-images.githubusercontent.com/73337386/192429221-8838fa5b-7ad6-4d5e-8909-3af46b831d6a.png)

**Comment by w13915984028** [comment]
I tried to reproduce in my ENV,  it happened right after system was rebooted:

an interesting log:

```
time="2022-09-27T13:11:31Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"harv2\", UID:\"570107d7-d044-4179-abb7-cebea913eb9c\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"15691\", FieldPath:\"\"}): type: 'Normal' reason: 'Ready' Node harv2 is ready"

time="2022-09-27T13:11:31Z" level=debug msg="Schedule replica to node harv2" dataDirectoryName=pvc-964246c3-c41a-4a16-a613-fb76a2e55d37-3b2e3db6 disk=65518063-0357-4430-802b-f2b78945fac2 diskPath=/var/lib/harvester/defaultdisk replica=pvc-964246c3-c41a-4a16-a613-fb76a2e55d37-r-1daf780a
time="2022-09-27T13:11:31Z" level=debug msg="Schedule replica to node harv2" dataDirectoryName=pvc-964246c3-c41a-4a16-a613-fb76a2e55d37-638bea8e disk=65518063-0357-4430-802b-f2b78945fac2 diskPath=/var/lib/harvester/defaultdisk replica=pvc-964246c3-c41a-4a16-a613-fb76a2e55d37-r-28b9d056
time="2022-09-27T13:11:31Z" level=debug msg="Schedule replica to node harv2" dataDirectoryName=pvc-866003f2-df97-4ecb-8ba7-adf0bf4df22a-1c8440ce disk=65518063-0357-4430-802b-f2b78945fac2 diskPath=/var/lib/harvester/defaultdisk replica=pvc-866003f2-df97-4ecb-8ba7-adf0bf4df22a-r-204aeae8
time="2022-09-27T13:11:31Z" level=debug msg="Schedule replica to node harv2" dataDirectoryName=pvc-866003f2-df97-4ecb-8ba7-adf0bf4df22a-6e4f11cb disk=65518063-0357-4430-802b-f2b78945fac2 diskPath=/var/lib/harvester/defaultdisk replica=pvc-866003f2-df97-4ecb-8ba7-adf0bf4df22a-r-8f270ccf
time="2022-09-27T13:11:31Z" level=debug msg="Schedule replica to node harv2" dataDirectoryName=pvc-5158098c-9918-4992-b119-9064ead183c1-f6552402 disk=65518063-0357-4430-802b-f2b78945fac2 diskPath=/var/lib/harvester/defaultdisk replica=pvc-5158098c-9918-4992-b119-9064ead183c1-r-8bb6dbb4
time="2022-09-27T13:11:31Z" level=debug msg="Schedule replica to node harv2" dataDirectoryName=pvc-5158098c-9918-4992-b119-9064ead183c1-bf830066 disk=65518063-0357-4430-802b-f2b78945fac2 diskPath=/var/lib/harvester/defaultdisk replica=pvc-5158098c-9918-4992-b119-9064ead183c1-r-5c6763da

```

And, at this moment, all replicas were scheduled in the only running `NODE`, same `DISK`:

```
harv2:~ # kk get replica -A
NAMESPACE         NAME                                                  STATE     NODE    DISK                                   INSTANCEMANAGER               IMAGE                               AGE
longhorn-system   pvc-5158098c-9918-4992-b119-9064ead183c1-r-5c6763da   stopped   harv2   65518063-0357-4430-802b-f2b78945fac2                                                                     14m
longhorn-system   pvc-5158098c-9918-4992-b119-9064ead183c1-r-8bb6dbb4   stopped   harv2   65518063-0357-4430-802b-f2b78945fac2                                                                     14m
longhorn-system   pvc-5158098c-9918-4992-b119-9064ead183c1-r-b35b74c2   running   harv2   65518063-0357-4430-802b-f2b78945fac2   instance-manager-r-8795b562   longhornio/longhorn-engine:v1.3.1   14m
longhorn-system   pvc-866003f2-df97-4ecb-8ba7-adf0bf4df22a-r-204aeae8   stopped   harv2   65518063-0357-4430-802b-f2b78945fac2                                                                     14m
longhorn-system   pvc-866003f2-df97-4ecb-8ba7-adf0bf4df22a-r-361cdfaf   running   harv2   65518063-0357-4430-802b-f2b78945fac2   instance-manager-r-8795b562   longhornio/longhorn-engine:v1.3.1   14m
longhorn-system   pvc-866003f2-df97-4ecb-8ba7-adf0bf4df22a-r-8f270ccf   stopped   harv2   65518063-0357-4430-802b-f2b78945fac2                                                                     14m
longhorn-system   pvc-964246c3-c41a-4a16-a613-fb76a2e55d37-r-1daf780a   stopped   harv2   65518063-0357-4430-802b-f2b78945fac2                                                                     14m
longhorn-system   pvc-964246c3-c41a-4a16-a613-fb76a2e55d37-r-2557d80b   running   harv2   65518063-0357-4430-802b-f2b78945fac2   instance-manager-r-8795b562   longhornio/longhorn-engine:v1.3.1   14m
longhorn-system   pvc-964246c3-c41a-4a16-a613-fb76a2e55d37-r-28b9d056   stopped   harv2   65518063-0357-4430-802b-f2b78945fac2                                                                     14m

```

**Comment by w13915984028** [comment]
The bug looks to be related to `ReconcileVolumeState`, which iterate all rs, but unfortunately, when 1st replica is set to some `NODE`, the 2rd replica may still select this `NODE`.  Because 1st selection does NOT update the occupied quota/label to the related `NODE`.

 @innobead @joshimoo @PhanLe1010 @mantissahz 
 
```
func (vc *VolumeController) ReconcileVolumeState(v *longhorn.Volume, es map[string]*longhorn.Engine, rs map[string]*longhorn.Replica) (err error) {
	for _, r := range rs {
...
		scheduledReplica, multiError, err := vc.scheduler.ScheduleReplica(r, rs, v)
		if err != nil {
			return err
		}
...
		} else {
			rs[r.Name] = scheduledReplica
		}
	}





// ScheduleReplica will return (nil, nil) for unschedulable replica
func (rcs *ReplicaScheduler) ScheduleReplica(replica *longhorn.Replica, replicas map[string]*longhorn.Replica, volume *longhorn.Volume) (*longhorn.Replica, util.MultiError, error) {

	// get all hosts
	nodesInfo, err := rcs.getNodeInfo()
..

	nodeCandidates, multiError := rcs.getNodeCandidates(nodesInfo, replica)
	if len(nodeCandidates) == 0 {
..
	}

	diskCandidates, multiError := rcs.getDiskCandidates(nodeCandidates, nodeDisksMap, replicas, volume, true)


	// schedule replica to disk
	rcs.scheduleReplicaToDisk(replica, diskCandidates)		
```

**Comment by w13915984028** [comment]
Suspect the BUG also has relationship with DISK size.


I used to test features in single-node Harvester, with LH default storageclass (3 replicas). This code logic seems to be there for a long time, but not all the time it is hitted.  This Harvester NODE is a KVM VM with 200Gb disk.  Harvester itself will occupy some spaces.

```
In the past, Harvester has only one build-in PVC before, prometheus 50Gb. The bug did not happen.

Now, there are 3 build-in PVCs, 50Gb, 5Gb, 2Gb. The bug comes.
```

When 3 replicas are scheduled into ONE node, ONE disk, but as long as the disk space is enough, LH can recover and remove those additional replicas silently.

But if all those replicas are over the space of disk, all replicas become `STOPPED`, and can not start anymore.


Please LH expert help confirm, thanks.

**Comment by mantissahz** [comment]
I think this issue will also happen at v1.2.5
Volume controller marks unused replicas failed after volume was detached to prevent the replica rebuilding. And it starts to schedule the failed/unused replica to the same node because all replicas are failed.

![v125](https://user-images.githubusercontent.com/14231257/193963914-d5206224-4439-4091-9d28-2bf7aeb79a1e.png)

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 15f850c) by following [the test steps](https://github.com/longhorn/longhorn/issues/4546#issue-1370576176).

In master-head, after instance reboot, the volume still only has 1 healthy replica + 2 unscheduled (N/A) replicas. 

But in v1.3.0, after instance reboot, the volume would have 3 replicas scheduled to the same single node, 1 with healthy state, and 2 with failed state.
