### ISSUE TITLE
[TEST] [v1.2.X] test_engine_live_upgrade_while_replica_concurrent_rebuild failed due to a missing backport commits

### ISSUE THREAD

**Issue by Lichiehyao** [longhorn/longhorn#4547]
## Describe the bug

After check [v1.2.x test_results_analyzer](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/test_results_analyzer/), `test_engine_live_upgrade_while_replica_concurrent_rebuild` failed case is due to missed commit.
The master commit is [0e3040ab](https://github.com/longhorn/longhorn-tests/commit/0e3040abe07120b7c46d7459b7f2b1cd313867ec). The v1.2.X `test_engine_live_upgrade_while_replica_concurrent_rebuild` [commit](https://github.com/longhorn/longhorn-tests/pull/1045/files) inconsistency.
![Screenshot_20220913_095649](https://user-images.githubusercontent.com/104337648/189805403-0841eb19-a5b8-4760-ba5f-a7bb61e55bbf.png)
![Screenshot_20220913_095710](https://user-images.githubusercontent.com/104337648/189805413-77410db4-0862-43a5-a770-5de7d8d64a65.png)

## To Reproduce

1. Go to '[v1.2.x test_results_analyzer](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/test_results_analyzer/)'
2. Click on '[test_engine_live_upgrade_while_replica_concurrent_rebuild](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/217/testReport/tests/test_engine_upgrade/test_engine_live_upgrade_while_replica_concurrent_rebuild/)'
3. See error

## Expected behavior

The master commit is [0e3040ab](https://github.com/longhorn/longhorn-tests/commit/0e3040abe07120b7c46d7459b7f2b1cd313867ec). The v1.2.X `test_engine_live_upgrade_while_replica_concurrent_rebuild` [commit](https://github.com/longhorn/longhorn-tests/pull/1045/files) should consistency.

## Log or Support bundle

N/A

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: ubuntu 20.04
   - CPU per node: 4 core
   - Memory per node: 16 GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS / KVM
 - Number of Longhorn volumes in the cluster:

## Additional context

Master [#4332](https://github.com/longhorn/longhorn/issues/4332) test case [PR-1043](https://github.com/longhorn/longhorn-tests/pull/1043)
v1.2.5 [#4339](https://github.com/longhorn/longhorn/issues/4339)  test case [PR-1045](https://github.com/longhorn/longhorn-tests/pull/1045)

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by Lichiehyao** [comment]
After checking the [1.2.X test_results_analyzer](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/test_results_analyzer/), we don't observe the failed since build 230+
