### ISSUE TITLE
[QUESTION]After modifying the [*Default Replica Count] parameter in LonghornUI, it does not take effect.

### ISSUE THREAD

**Issue by MagicFollower** [longhorn/longhorn#4564]
## Describe the bug

I am using the latest version of Longhorn 1.3.1 in Rancher. When modifying the default number of backups, this parameter value is not synchronized to the longhorn storage class, which leads to the number of backups per volume I set initially.

## To Reproduce

![image](https://user-images.githubusercontent.com/89330933/190180531-511d89cd-b6c4-41f5-aab0-db22a4216aa8.png)
👇👇👇
![image](https://user-images.githubusercontent.com/89330933/190180669-c17c3852-ba92-425e-b43a-ae5231420cac.png)

## Environment
![image](https://user-images.githubusercontent.com/89330933/190181073-445a5ef1-f13e-4016-833a-dd5df74b608e.png)

**Comment by derekbit** [comment]
This is expected. The change of the replica count setting won't apply to the existing storageclass.
The default replica count is only applied to the volume whose count is not specified.
