### ISSUE TITLE
[BUG] PodSecurityPolicy in the policy/v1beta1 API deprecated in Kubernetes v1.25

### ISSUE THREAD

**Issue by runbgp** [longhorn/longhorn#4569]
## Describe the bug

PodSecurityPolicy in the policy/v1beta1 API version is no longer served in v1.25, and the PodSecurityPolicy admission controller was removed. This causes the installation of Longhorn to fail.

`error: resource mapping not found for name: "longhorn-psp" namespace: "" from "https://raw.githubusercontent.com/longhorn/longhorn/v1.3.1/deploy/longhorn.yaml": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"`

## To Reproduce

1. Deploy new K3s v1.25.0+k3s1 cluster.
2. Complete prerequesites for cluster nodes (open-iscsi, nfs-common)
3. Attempt to install Longhorn via Helm or Kubectl.

## Expected behavior

Installation should proceed as normal.

## Environment

 - Longhorn version: 1.3.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl & Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: Ubuntu 22.04
   - CPU per node: 2
   - Memory per node: 4096
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 20Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 0

**Comment by mantissahz** [comment]
Hi @runbgp,
Thanks for your reporting
We are migrating the PodSecurityPolicy to support k8s v1.25 and after.
ref: https://github.com/longhorn/longhorn/issues/4003

**Comment by runbgp** [comment]
> #4003

Thank you! Apologies for the duplicate issue. Appreciate your efforts.
