### ISSUE TITLE
[IMPROVEMENT] Check if node schedulable condition is set before trying to read it

### ISSUE THREAD

**Issue by weizhe0422** [longhorn/longhorn#4581]
## Is your improvement request related to a feature? Please describe

One of my longhorn nodes is not currently schedulable due to kubernetes nonsense, and this has broken the whole UI as it throws an exception on page load due to one node being bad. Also a little formatting as those one-liners are getting out of control.
![image](https://user-images.githubusercontent.com/17548901/190987671-5eb8e80c-177e-45d2-96d7-f46dacfdd7e0.png)

## Describe the solution you'd like

Check whether the node's `Schedulable` and `Ready` condition is set or not to avoid access non exists property.  

## Additional context

Come from community PR: [Longhorn-ui  PR#541](https://github.com/longhorn/longhorn-ui/pull/541)

**Comment by innobead** [comment]
Moving back to the review pipeline, because the test steps have not been provided by. @weizhe0422

**Comment by Lichiehyao** [comment]
**Verified on master-head 20220928**

- longhorn master-head ([ff9b19b](https://github.com/longhorn/longhorn/commit/ff9b19bbf55233dae14e17306485b5c1a73d4457)) 
- longhorn-ui master-head( [f823fe6](https://github.com/longhorn/longhorn-ui/commit/f823fe6563657dedd825a84766a2e26e3d68152b))

	
**Pre-requisite**

1. Install Rancher
2. Create cluster
3. install Longhorn via kubectl

**The test steps**

1. https://github.com/longhorn/longhorn/issues/4581#issuecomment-1254541244



**Result Passed**
