### ISSUE TITLE
[TEST] [v1.2.x] Fix test_migration_with_unscheduled_replica failure

### ISSUE THREAD

**Issue by Lichiehyao** [longhorn/longhorn#4585]
## What's the test to develop? Please describe

After https://github.com/longhorn/longhorn-tests/commit/30cc2cb1c9e09144a69f60f31af92f6d597aa5ad merged
Test case `test_migration_with_unscheduled_replica` always failed. 
Longhorn-tests master-head could test case, we need to fix the 1.2.x-head script.

## Describe the items of the test development (DoD, definition of done) you'd like

- [x] Modify script
- [x] Verified on pipeline

## Additional context

[test_migration_with_unscheduled_replica](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/227/testReport/junit/tests/test_migration/test_migration_with_unscheduled_replica/)

**Comment by Lichiehyao** [comment]
1. modify script and build the private image
2. use the private image and execute v1.2.x regression 
- [x] executed test_migration_with_unscheduled_replica ([report](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2016/))
- [ ] v1.2.x regression ([In-progress](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2014/))

**Comment by Lichiehyao** [comment]
We could observe arm64 the different fail on the same test case.Ref [2043](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2043/testReport/junit/tests/test_engine_upgrade/test_engine_live_upgrade_while_replica_concurrent_rebuild/), [2042](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2042/testReport/junit/tests/test_engine_upgrade/test_engine_live_upgrade_while_replica_concurrent_rebuild/)
I need to build up the arm64 environment and execute the test case on the local.
![Screenshot_20220923_064747](https://user-images.githubusercontent.com/104337648/191865047-bb062965-e6d3-43f0-92cd-a76f26634f47.png)

**Comment by innobead** [comment]
cc @chriscchien

**Comment by Lichiehyao** [comment]
flake8 check failed, I would check it again.

**Comment by Lichiehyao** [comment]
use the private image and execute v1.2.x regression 20221002
- [x] v1.2.x regression amd64 ([report](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2091/))
- [x] [v1.2.x-longhorn-upgrade-tests-sles-amd64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2090/)
- [x] v1.2.x regression arm64 ([report](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2093/))
- [x] [v1.2.x-longhorn-upgrade-tests-sles-arm64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2092/)

**Comment by Lichiehyao** [comment]
The fixed is included in @chriscchien's [PR](https://github.com/longhorn/longhorn-tests/commit/f0e8257fd9f2a62e03c37b7bc54eebb93f8c5b28).
The test_migration_with_unscheduled_replica is passed.
