### ISSUE TITLE
[IMPROVEMENT] Reorganize longhorn-manager/k8s/patches and auto-generate preserveUnknownFields field

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4600]
## Is your improvement request related to a feature? Please describe

1. Reorganize longhorn-manager/k8s/patches
2. Auto-generate `preserveUnknownFields` field when executing ./k8s/generate_code.sh

**Comment by yangchiu** [comment]
Verified passed on longhorn-manager master-head (aa79220). The 03-crd.yaml file generated by ./k8s/generate_code.sh has corresponding `preserveUnknownFields: false` field in `engineimages`, `nodes` and `volumes`.
