### ISSUE TITLE
[BUG] the values.yaml in the longhorn helm chart contains values not used.

### ISSUE THREAD

**Issue by SweBarre** [longhorn/longhorn#4601]
## Describe the bug

The [values.yaml](https://github.com/longhorn/charts/blob/master/charts/longhorn/values.yaml#L172-L183) file contains the `resource: {}` block and description on how to set recourse limits and requests, however this field is not used or referenced in the chart templates.

## Expected behavior

To minimize confusion the values.yaml shouldn't specifies variables not used.

**Comment by Lichiehyao** [comment]
**Verified on master-head 20221003**

- longhorn master-head ([502dcb7](https://github.com/longhorn/longhorn/commit/502dcb72ed676cc19941fd5106f7ab1ddcd79cb4)) 

**The test steps**

1.[Test steps](https://github.com/longhorn/longhorn/issues/4601#issuecomment-1254718552)


**Result Passed**
