### ISSUE TITLE
[BACKPORT][v1.3.2][BUG] Backend sizes do not match 5368709120 != 10737418240 in the engine initiation phase 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4609]
## Describe the bug

https://github.com/longhorn/longhorn/issues/3601

## To Reproduce

3. Perform '....'

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by chriscchien** [comment]
**Verified on longhorn-manager v1.3.x-head `8075c6`
Result Pass**

Reproduce Steps:

1. create volume and attach to node
2. detach the volume
3. Select one node, enter folder /var/lb/longhorn/replicas/<replica name>
4. modify Size in volume.meta
5. Attach volume
6. Volume keep in attach, detach loop forever.

Expect behavior:

- Volume become healthy

Can be reproduced in v1.3.1.

In v1.3.x-head, the replica which volume.meta been modified in step 4 will become failed and then delete by Longhorn, after awhile new replica will create and volume become healthy
