### ISSUE TITLE
[TEST] Test image upgrade-test.5-3.3-3.1-1 not working properly on ARM64 pipeline

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#4616]
## What's the test to develop? Please describe

Test image upgrade-test.5-3.3-3.1-1 not working properly on ARM64 pipeline

## Describe the items of the test development (DoD, definition of done) you'd like

- [x] Build correct test images
- [ ] Verify test result

## Additional context

https://github.com/longhorn/longhorn/issues/4615

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by chriscchien** [comment]
After longhornio/longhorn-engine:v1.3.x-head updated (cliAPIVersion 6),  ARM64 engine upgrade test fail on v1.3.x [pipeline](https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-tests-sles-arm64/102/testReport/tests/test_engine_upgrade/) not happened again

As for v1.2.x test pipeline [result](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/235/#showFailuresLink), still need time to investigate

**Comment by chriscchien** [comment]
Engine upgrade test case on v1.2.x [ARM64](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/241/testReport/tests/test_engine_upgrade/), v1.2.x [AMD64](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/242/testReport/tests/test_engine_upgrade/)), v1.3.x [ARM64](https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-tests-sles-arm64/107/testReport/tests/test_engine_upgrade/), v1.3.x [AMD64](https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-tests-sles-amd64/159/testReport/tests/test_engine_upgrade/), master-head [ARM64](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/253/testReport/tests/test_engine_upgrade/), master-head [AMD64](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/267/testReport/tests/test_engine_upgrade/), are all working properly now
