### ISSUE TITLE
[TASK] Update base image of all components from BCI 15.3 to 15.4

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4617]
## What's the task? Please describe

Align with the latest BCI feature release version. 

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

Add any other context or screenshots about the task request here.

**Comment by innobead** [comment]
Added to the zenhub pipeline instead of the QA board, because its part of the 1.4 release. 

cc @longhorn/qa

**Comment by yangchiu** [comment]
There is no aarch64 and s390x folder in https://download.opensuse.org/repositories/network:/utilities/15.4/, so after update Dockerfile to use `zypper -n addrepo --refresh https://download.opensuse.org/repositories/network:utilities/15.4/network:utilities.repo`, build for arm64 and s390 will fail. Already post in `#proj-sle-bci` channel waiting for reply.

**Comment by yangchiu** [comment]
> There is no aarch64 and s390x folder in https://download.opensuse.org/repositories/network:/utilities/15.4/, so after update Dockerfile to use `zypper -n addrepo --refresh https://download.opensuse.org/repositories/network:utilities/15.4/network:utilities.repo`, build for arm64 and s390 will fail. Already post in `#proj-sle-bci` channel waiting for reply.

bci team doesn't take control of this. Asking maintainers of [/network:utilities](https://build.opensuse.org/project/users/network:utilities) now.

**Comment by yangchiu** [comment]
Still waiting for [SLE_15_SP4](https://build.opensuse.org/project/repository_state/network:utilities/SLE_15_SP4)/s390x build completed.
