### ISSUE TITLE
[TASK] Use SLES 15.4 as the default testing distro instead of 15.3

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4618]
## What's the task? Please describe

This change should apply to all active release pipelines now, including the master/1.4, 1.3 and 1.2.

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

cc @longhorn/qa

**Comment by yangchiu** [comment]
longhorn test is running in registry.suse.com/bci/python:3.9 instead of sles image. Do we still need to update anything?

**Comment by innobead** [comment]
> longhorn test is running in registry.suse.com/bci/python:3.9 instead of sles image. Do we still need to update anything?

I mean the nodes provisioned by terraform script for SLES, and we should use 15.4 by default.
