### ISSUE TITLE
[BACKPORT][v1.2.6][BUG] data corruption due to COW and block size not being aligned during rebuilding replicas

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4627]
backport https://github.com/longhorn/longhorn/issues/4354

**Comment by PhanLe1010** [comment]
Test steps: https://github.com/longhorn/longhorn/issues/4354#issuecomment-1260174435

**Comment by chriscchien** [comment]
**Verified on Longhorn manager v1.2.x `71ebe1`
Result Pass**

Test [steps](https://github.com/longhorn/longhorn/issues/4354#issuecomment-1260174435)

- I can reproduce the file system corruption error on Longhorn v1.2.5 by execute step 1, 2 and step 3

`mount: /mnt: wrong fs type, bad option, bad superblock on /dev/sdb1, missing codepage or helper program, or other error.`

- In longhorn-manager v1.2.x-head, the file corruption error can not be reproduced
