### ISSUE TITLE
[BUG] Can not pull a backup created by another Longhorn system from the remote backup target

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#4637]
## Describe the bug

When system try to pull a backup down to the system and create a CR, it would be block by admission webhook for getting the access mode of a non-existing volume.

https://github.com/longhorn/longhorn/issues/3444

## To Reproduce

1. Create a backup of volume `A` at cluster A.
2. Set the same backup target at cluster B without volume named `A`.
3. wait for backup target polling update at cluster B.

## Expected behavior

A backup that backup volume name does not exist can be pulled from the remote backup target. 

## Log or Support bundle

`time="2022-09-29T02:24:39Z" level=info msg="Found 1 backups in the backup target that do not exist in the cluster and need to be pulled" backupVolume=c001 controller=longhorn-backup-volume node=rancher60-worker1
time="2022-09-29T02:24:39Z" level=error msg="Error creating backup backup-0b6902f391e94b70 into cluster" backupVolume=c001 controller=longhorn-backup-volume error="admission webhook \"mutator.longhorn.io\" denied the request: failed to get volume c001: volume.longhorn.io \"c001\" not found" node=rancher60-worker1
time="2022-09-29T02:24:39Z" level=warning msg="Error syncing Longhorn backup volume longhorn-system/c001" controller=longhorn-backup-volume error="longhorn-backup-volume: failed to sync backup volume longhorn-system/c001: admission webhook \"mutator.longhorn.io\" denied the request: failed to get volume c001: volume.longhorn.io \"c001\" not found" node=rancher60-worker1`

## Environment

 - Longhorn version: v1.3.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.24.2+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04.4 LTS
   - CPU per node: 8
   - Memory per node: 8
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 1G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 1

**Comment by innobead** [comment]
@longhorn/qa For any backup creation change, we need to verify backup creation from the current cluster (in-cluster) or the backup target (out-of-cluster). This is important to review the test cases provided by engineers during ready-for-testing stage.

**Comment by khushboo-rancher** [comment]
> Create a backup of volume A at cluster A.
Set the same backup target at cluster B without volume named A.
wait for backup target polling update at cluster B.

@yangchiu Could you please add manual test cases for this and include some edge cases also like backups created with different versions of Longhorn, deletion etc

**Comment by yangchiu** [comment]
Verified pass on master-head (longhorn-manager a00bac7) by following [the steps](https://github.com/longhorn/longhorn/issues/4637#issue-1390220170) to reproduce:

1. Create a backup of volume A at cluster A.
2. Set the same backup target at cluster B without volume named A.
3. wait for backup target polling update at cluster B.

After the backup target polling update in cluster B, the backup created in cluster A can be seen in cluster B, and a new volume can be created from this backup, and the checksum of volume data is correct. On the other hand, delete a backup in cluster A, the backup in cluster B will also disappear in backup list after the backup target polling.

**Comment by khushboo-rancher** [comment]
@yangchiu Have we checked the backups already created in v1.3.1? Are those able to get pull in an another cluster?

**Comment by khushboo-rancher** [comment]
Reopening to check the [above](https://github.com/longhorn/longhorn/issues/4637#issuecomment-1269155966) scenario.

**Comment by Lichiehyao** [comment]
**Verified on v1.3.2-rc1 20221007**

- longhorn **v1.3.2-rc1**

**Pre-requisite**

1. Install Longhorn **1.3.1** via kubectl on **cluster A**
2. Install Longhorn **1.3.2-rc1** via kubectl on **cluster B**
3. Setup backup target on **longhorn A&B**
```   
kubectl create secret generic <aws-secret> \
    --from-literal=AWS_ACCESS_KEY_ID=<your-aws-access-key-id> \
    --from-literal=AWS_SECRET_ACCESS_KEY=<your-aws-secret-access-key> \
    -n longhorn-system
```

**The test steps**

1. Create volme **vol-0-ext4-131** and **vol-0-xfs-131**
2. Create volme **vol-0-ext4-131** PV/PVC with fsType **ext4**
3. Create volme **vol-0-xfs-131** PV/PVC with fsType **xfs**
4. Create a pod with pvc
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  namespace: default
spec:
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/data0/"
        name: vol-0-ext4-131
      - mountPath: "/data1/"
        name: vol-0-xfs-131
  volumes:
    - name: vol-0-ext4-131
      persistentVolumeClaim:
        claimName: vol-0-ext4-131
    - name: vol-0-xfs-131
      persistentVolumeClaim:
        claimName: vol-0-xfs-131

```
5. Access pod shell write data and check the file md5
```
kubectl exec -it mypod1 -- /bin/bash
dd if=/dev/urandom of=/data0/2G.txt count=2000 bs=1M conv=fsync status=progress
dd if=/dev/urandom of=/data1/2G.txt count=2000 bs=1M conv=fsync status=progress
md5sum /data0/2G.txt
md5sum /data1/2G.txt
```
6. backup up volume **vol-0-ext4-131** and **vol-0-xfs-131**
7. wait for backup target polling update at **cluster B**
8. Restore the volume on **cluster B**
9. Create the pod and mount volume on **cluster B** 
10. Verify the restored data.


**Result Passed** 

1. **cluster B** could poll backup data from backup target
2. The volume could be attached on **cluster B**. 
3. The volume was also accessible and the files in the volume were also correct (checked by the checksum)

**Comment by Lichiehyao** [comment]
**Verified on v1.3.2-rc2 20221011**

- longhorn **v1.3.2-rc2**

**The test steps**
- [Ref](https://github.com/longhorn/longhorn/issues/4637#issuecomment-1271068274)

**Result Passed** 

1. **cluster B** could poll backup data from backup target
2. The volume could be attached on **cluster B**. 
3. The volume was also accessible and the files in the volume were also correct (checked by the checksum)
