### ISSUE TITLE
[QUESTION] Volumes are stuck at attaching state

### ISSUE THREAD

**Issue by btdan** [longhorn/longhorn#4643]
Hello,
## Question
Attach  volume takes a long time. Just as follows:
![1664505559775](https://user-images.githubusercontent.com/5276480/193178325-94512e08-7a91-411c-b1e2-c7f1802fc12a.png)

## Environment

 - Longhorn version:1.3.1
 - Kubernetes version:1.24
 - Node config
   - OS type and version:ubuntu 22.04
   -

**Comment by derekbit** [comment]
Can you check the longhorn-managers' log?

**Comment by btdan** [comment]
Thanks very much for your reply. 
I found that the problem is the system error of operating system Ubuntu 22.04.
After I reboot the system， this question is solved.
Thanks again.
