### ISSUE TITLE
[IMPROVEMENT] Use of external-snapshotter release 6.1.0 instead of 4.0 as in Longhorn documentation

### ISSUE THREAD

**Issue by MrRedHead** [longhorn/longhorn#4646]
## Question
Is the documentation for external-snapshotter on page "the Enable CSI Snapshot Support on a Cluster" still valid?
> Ref: "https://longhorn.io/docs/1.3.1/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/"

There is on the Longhorn documentation a reference to release: 4.0 of external-snapshotter.
`https://github.com/kubernetes-csi/external-snapshotter/tree/release-4.0/client/config/crd`
`https://github.com/kubernetes-csi/external-snapshotter/tree/release-4.0/deploy/kubernetes/snapshot-controller`

The latest release is:  6.1.0 as referenced on the master branch
`https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd`
`https://github.com/kubernetes-csi/external-snapshotter/tree/master/deploy/kubernetes/csi-snapshotter`

## Additional context
Can the latest version (6.1.0) of the external-snapshotter used in conjunction of Longhorn?
Can the documentation on page:  `https://longhorn.io/docs/1.3.1/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/`
be updated to the (latest) master branch version?

**Comment by c3y1huang** [comment]
We haven't tested on the latest external-snapshotter. Any reason you want to have this upgraded?

**Comment by MrRedHead** [comment]
Right now we are running tests with external-snapshotter for Commvault (with version 6.1.0 of external-snapshotter with Longhorn 1.3.1), don't know of any issues (yet)

Main reason is to keep up with life-cycle for all of differente components.
If we install version 4.0 instead of 6.1.0 we are beginning with a backlog of life-cycle.

**Comment by c3y1huang** [comment]
cc @innobead

**Comment by sebastien-prudhomme** [comment]
@MrRedHead as I'm doing some tests in my own installation, it's not possible to use version 6.x as it removes support for deprecated v1beta snapshot storage API.

Unfortunately, Longhorn 1.3.x is still using that API. Version of the CSI snapshotter included in Longhorn is v3.0.3.

You can upgrade up to v5.0.1.

**Comment by sebastien-prudhomme** [comment]
Related to #4189

**Comment by joshimoo** [comment]
Right now we are planning on updating to v5.0.1 with the longhorn v1.4 release. 
ref #4490 

cc @PhanLe1010 I also saw that they readded the beta manifests so we might go up to v6.1.0 any concerns about that?
If I understood correctly this allows the controller to service existing v1beta snapshots while only allowing for creation of new v1 snapshots.
https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v6.1.0

**Comment by PhanLe1010** [comment]
> cc @PhanLe1010 I also saw that they readded the beta manifests so we might go up to v6.1.0 any concerns about that?
If I understood correctly this allows the controller to service existing v1beta snapshots while only allowing for creation of new v1 snapshots.

The fix in v6.1.0 was to allow the persisted v1beta1 object inside ETCD to be accessible via `v1` version. `snapshot-controller`, `csi-sidecar`, script, etc... must use `v1` to read/write new CSI snapshot CR.

We have some discussion here about why we picked v5.0.1 over v6.1.0 for Longhorn 1.4.0 https://github.com/longhorn/longhorn-manager/pull/1518#discussion_r991818681
