### ISSUE TITLE
[BUG] Test case test_backup_volume_restore_with_access_mode failed on pipeline

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#4653]
## Describe the bug

Test case test_backup_volume_restore_with_access_mode failed on [master-head](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/267/) pipeline

## To Reproduce

1. https://ci.longhorn.io/job/public/job/master/job/sles/
2. Verify test result of `test_backup_volume_restore_with_access_mode`

## Expected behavior

Have consistent test result

## Log or Support bundle

N/A

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

N/A

**Comment by chriscchien** [comment]
https://github.com/longhorn/longhorn/issues/4713
https://github.com/longhorn/longhorn/issues/4710

**Comment by innobead** [comment]
This is caused by the reason mentioned in https://github.com/longhorn/longhorn/issues/4710.

**Comment by khushboo-rancher** [comment]
@chriscchien Could you check if this is working on our pipelines and close this?

**Comment by chriscchien** [comment]
Hi @khushboo-rancher ,

Test case not passed in recent build ([289](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/289/testReport/junit/tests/test_basic/test_backup_volume_restore_with_access_mode_s3_rwx_rwo_/),  [290](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/290/testReport/junit/tests/test_basic/test_backup_volume_restore_with_access_mode_s3_rwx_rwo_/),  [291](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/291/testReport/junit/tests/test_basic/test_backup_volume_restore_with_access_mode_nfs_rwx_rwo_/))

I will move this ticket into implement phase

**Comment by weizhe0422** [comment]
I had noticed that it only happened when creating backup for RWX volume since the volume was lost. 

And I am looking into it and understand why it happened.

```
test_basic.py:4625: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common.py:345: in create_backup
    data = write_volume_random_data(volume)
common.py:2256: in write_volume_random_data
    return write_device_random_data(dev, position=position)
common.py:2270: in write_device_random_data
    data_len = dev_write(dev, data_pos, data)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

dev = '/dev/longhorn/longhorn-testvol-e2290o', start = 88601
data = b'xb1xyet6uz8a1aowdbkpniwg5zvhgk44au6avvyt2dbop4f4v5f7mi0sun04aop2kdtukv9m8gyrc1f861nyzdaf1yj7pvcathhqoeccy52kqk2ypyvx...vdh9uhoeiepkhym31igjo2uryfuvhsmfj0jq5yni3uxeve9e630q4tu7xevjpifqnuqhevb4qjqpdlpq89ynxel2i8kqfng7figui4kz4ystvccqckqqpc'

    def dev_write(dev, start, data):
        data = bytes(data, encoding='utf-8')
        w_length = 0
>       fdev = open(dev, 'rb+')
E       FileNotFoundError: [Errno 2] No such file or directory: '/dev/longhorn/longhorn-testvol-e2290o'
```

**Comment by weizhe0422** [comment]
share manager received terminated signal
 
```
time="2022-10-26T06:01:49Z" level=info msg="starting RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
time="2022-10-26T06:01:49Z" level=info msg="ending RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
time="2022-10-26T06:01:49Z" level=warning msg="waiting with nfs server start, volume is not attached" encrypted=false volume=longhorn-testvol-4iyjht
time="2022-10-26T06:01:54Z" level=debug msg="volume longhorn-testvol-4iyjht device /dev/longhorn/longhorn-testvol-4iyjht contains filesystem of format " encrypted=false volume=longhorn-testvol-4iyjht
I1026 06:01:54.780761       1 mount_linux.go:449] Disk "/dev/longhorn/longhorn-testvol-4iyjht" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/longhorn/longhorn-testvol-4iyjht]
I1026 06:02:00.159150       1 mount_linux.go:459] Disk successfully formatted (mkfs): ext4 - /dev/longhorn/longhorn-testvol-4iyjht /export/longhorn-testvol-4iyjht
time="2022-10-26T06:02:00Z" level=info msg="starting nfs server, volume is ready for export" encrypted=false volume=longhorn-testvol-4iyjht
time="2022-10-26T06:02:00Z" level=info msg="Running NFS server!"
time="2022-10-26T06:02:00Z" level=info msg="starting health check for volume" encrypted=false volume=longhorn-testvol-4iyjht
time="2022-10-26T06:02:45Z" level=info msg="share manager received signal terminated to exit"
time="2022-10-26T06:02:45Z" level=info msg="nfs server is shutting down" encrypted=false volume=longhorn-testvol-4iyjht
time="2022-10-26T06:02:45Z" level=error msg="nfs server exited with error" encrypted=false error="ganesha.nfsd failed with error: signal: killed, output: " volume=longhorn-testvol-4iyjht
W1026 06:03:01.283187       1 mount_helper_common.go:133] Warning: "/export/longhorn-testvol-4iyjht" is not a mountpoint, deleting
time="2022-10-26T06:03:01Z" level=debug msg="device /dev/mapper/longhorn-testvol-4iyjht is not an active LUKS device: failed to run cryptsetup args: [status longhorn-testvol-4iyjht] output:  error: exit status 4"
rpc error: code = NotFound desc = an error occurred when try to find container "9c4e41474d34ef7bda88ea80c2d489bc771204b8ec29b4156eac067ca10ad1cf": not found%
```

**Comment by derekbit** [comment]
I think the root cause is the volume device is on another node, so the "no such file or directory" poped up.

**Comment by derekbit** [comment]
I think the root cause is the volume device is on another node, so the "no such file or directory" poped up.

**Comment by weizhe0422** [comment]
After check the root cause and system behavior:
 - The reason for volume not found: 
   - the node of volume device (`/dev/longhorn/<vol-name>`) is not locate same as client (pod `longhorn-test`).
   
- plan to do
    - After reference [other functions](https://github.com/longhorn/longhorn-tests/blob/5673f228c4e6b306f1baa9b1c4a36808c1fc0986/manager/integration/tests/test_migration.py#L471-L491) and [docs](https://github.com/longhorn/longhorn/blob/master/enhancements/20210216-volume-live-migration.md#attach-changes), I think make the RWX volume as `migratable` could attach to specified node.
    - self test result:
<img width="1090" alt="截圖 2022-10-26 下午11 55 48" src="https://user-images.githubusercontent.com/17548901/198075533-98a0a5bd-3ede-41e7-81fc-d0069bcb4a59.png">

**Comment by weizhe0422** [comment]
Self-check e2e results on daily CI pipeline are pass.
longhorn-tests-sles-amd64: [#296](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/296/testReport/tests/test_basic/test_backup_volume_restore_with_access_mode_s3_rwx_rwo_/)、[#295](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/295/testReport/tests/test_basic/test_backup_volume_restore_with_access_mode_nfs_rwx_rwo_/)、[#294](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/294/testReport/tests/test_basic/test_backup_volume_restore_with_access_mode_s3_rwx_rwo_/)

**Comment by chriscchien** [comment]
As @weizhe0422 mentioned, test case passed on master-head pipeline, close this ticket, thank you
