### ISSUE TITLE
[BUG] Updating volume-scheduling-error failure for RWX volumes and expanding volumes

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4654]
## Describe the bug

Updating volume-scheduling-error failure for RWX volumes and expanding volumes

## To Reproduce

https://github.com/longhorn/longhorn/issues/3529#issuecomment-1263344696

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
**Root cause**
Case 1
If you create a PVC with size larger than 8589934591 GiB, an int64 (volume.size) overflow happens. Then, the csi driver will receive an zero-sized volume creation request. The size will be rounded up to 2iB in the mutating, so the scheduling is actually sucessful.
Additionally, for this case, the csi CreateVolume and DeleteVolume are called constantly, and the PCC status is Pending. Any volume creation failure can result in the Pending state.
In this case, Harvester should check the PVC status first rather than PV's longhorn.io/volume-scheduling-error.
Case 2
Works well in RWO volumes
But the longhorn.io/volume-scheduling-error is not set corectly in RWX volumes.
Case 3
The expansion is executed before the scheduling. In this case, the expansion failed, so volume-scheduling-error is not set.

**Comment by chriscchien** [comment]
**Verified on longhorn manager master-head `0eec02`
Result Pass**

Case 1 - create a PVC with size > 8589934591 GiB
- Deployment keep in pending status, RWO/RWX volume keep in a create -> delete loop same as description [here](https://github.com/longhorn/longhorn/issues/4654#issuecomment-1264870672)

Case 2 - Create a PVC with size <= 8589934591 GiB, but greater than the actual available space size.
- Both RWO/RWX volume have annotation `longhorn.io/volume-scheduling-error": "insufficient storage volume scheduling failure`

Case 3 - Create a PVC with size < the actual available space size，Resize the PVC to a not schedulable size
- After resize PVC to  not schedulable size,  both RWO/RWX were still in scheduling status, same as description [here](https://github.com/longhorn/longhorn/issues/4654#issuecomment-1264870672)
