### ISSUE TITLE
[BUG] Cannot resize PVC back to a smaller value after failing to resize a big value

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4658]
## Describe the bug

Cannot resize PVC back to a smaller value after failing to resize a large size

## To Reproduce

1. Create a PVC with size 1Gi
2. Expand the PVC to a big value (e.g. 9999999Gi)
3. Then, the error is expected in `kubectl describe pvc ...`
```
  Warning  VolumeResizeFailed     3s (x5 over 8s)    external-resizer driver.longhorn.io                                                       resize volume "pvc-a0495d54-a2b4-46b7-89b2-9da314b966c2" by resizer "driver.longhorn.io" failed: rpc error: code = OutOfRange desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to expand volume pvc-a0495d54-a2b4-46b7-89b2-9da314b966c2: error while CheckReplicasSizeExpansion for volume pvc-a0495d54-a2b4-46b7-89b2-9da314b966c2: cannot schedule 53686822764544 more bytes to disk 743cc97e-2a68-45cf-a73a-6f58effa8ea4 with &{StorageAvailable:121739673600 StorageMaximum:132161630208 StorageReserved:39648489062 StorageScheduled:268435456 OverProvisioningPercentage:200 MinimalAvailablePercentage:25}] from [http://longhorn-backend:9500/v1/volumes/pvc-a0495d54-a2b4-46b7-89b2-9da314b966c2?action=expand]
```
4. Resize back to a smaller value and then the error shows
```
# persistentvolumeclaims "longhorn-volv-pvc" was not valid:
# * spec.resources.requests.storage: Forbidden: field can not be less than previous value
```

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.3.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by derekbit** [comment]
Seems a upstream issue https://github.com/kubernetes-csi/external-resizer/issues/132

**Comment by chriscchien** [comment]
I can reproduce on v1.2.5

Steps 
1. kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml
2. Wait deployment ready
3. Update PVC to a larger size
4. Update PVC to origin size
5. Can see below error
```
The PersistentVolumeClaim "rwx-test" is invalid: spec.resources.requests.storage: Forbidden: field can not be less than previous value

```

**Comment by masifeddress** [comment]
I am also facing same issue. It has fixed?

**Comment by innobead** [comment]
cc @shuo-wu

**Comment by shuo-wu** [comment]
Can Longhorn do anything if users modify the PVC spec size to such an extremely large value (then decrease it)? The validation of PVC is out of Longhorn's control.

**Comment by innobead** [comment]
@shuo-wu is right. It seems we can't handle this part which is related to user-driven operation.
