### ISSUE TITLE
[BUG] charts/longhorn/questions.yaml include oudated csi-image tags

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4669]
charts/longhorn/questions.yaml include oudated csi-image tags : https://github.com/longhorn/longhorn/blob/502dcb72ed676cc19941fd5106f7ab1ddcd79cb4/chart/questions.yaml#L85-L144 vs correct ones https://github.com/longhorn/longhorn/blob/502dcb72ed676cc19941fd5106f7ab1ddcd79cb4/chart/values.yaml#L44-L60

**Comment by Lichiehyao** [comment]
**Verified on master-head 20221008**

- longhorn master-head ([97cb124](https://github.com/longhorn/longhorn/commit/97cb124f247e736a77c4e73e319cc4b5c2f1bb46)) 


**The test steps**

1. git clone longhorn master branch
`git clone -b master --single-branch https://github.com/longhorn/longhorn.git`
2. change the current working directory to **Longhorn Chart**
`cd ./longhorn/chart`
3. Install longhorn with Helm
`helm install longhorn . --namespace longhorn-system --create-namespace`

**Result Passed** 
1. **Longhorn Chart** validation is passed, Longhorn could be installed with Helm
