### ISSUE TITLE
[BUG] Check if the replica size is matched with volume size before running backup

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4679]
## Describe the bug

Current backup mechanism is randomly choosing a replica and then executing backup without any replica size check.

When a volume fails to expand and leaves some replicas with a mismatched size, Longhorn will potentialy back up the wrong replica to remote storage and is not aware of the size mismatch ([code](https://github.com/longhorn/longhorn-manager/blob/0eec020db8d889ba37318d9a4717268cd2daca74/controller/backup_controller.go#L492)).

To prevent from the issue, the size check and setting the wrong replica to ERR for triggering rebuilding will be implemented in this ticket.

## To Reproduce

Reproduce steps

1. Create a 2 GiB volume with 3 replicas
2. Go to one of the instance-manager-r
3. Download `[grpc-client-cli](https://github.com/vadimi/grpc-client-cli)` and execute `grpc-client-cli --address ${replicas process's replica server address}` to connect to replica server
     e.g: `grpc-client-cli --address localhost:10000`
4. `ptypes.ReplicaService` > `ReplicaExpand` >  `{"size": "4294967296"}` > enter
5. Create a tons of replica. The issue will be observed.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.2.x, v1.3.0 and v1.3.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
Normally, when creating a volume controller, the downstream replicas' sizes are compared to the input volume's `size` and `current size`. It means there shouldn't be a size mismatch between replicas.

If user **directly calls the `ReplicaExpand` to one of the replica servers via a gRPC client** rather via `UI` or `kubectl`, then it will lead to the size mismatches between volume resource and replicas. The engine cannot be aware of the unexpected downstream replica's expansion and results in this error.

Should we fix this issue? I feel no, because the user misoperated Longhorn. cc @innobead 

**Reproduce steps**

1. Create a 2 GiB volume with 3 replicas
2. Go to one of the instance-manager-r
3. Download `[grpc-client-cli](https://github.com/vadimi/grpc-client-cli)` and execute `grpc-client-cli --address ${replicas process's replica server address}` to connect to replica server
     ex: `grpc-client-cli --address localhost:10000`
4. `ptypes.ReplicaService` > `ReplicaExpand` >  `{"size": "4294967296"}` > enter
5. Create a tons of replica. The issue will be observed.

**Comment by innobead** [comment]
> Normally, when creating a volume controller, the downstream replicas' sizes are compared each other and are compared to the input volume's `size` and `current size`. It means there shouldn't be a size mismatch between replicas when executing backup.
> 

So, basically, the below case should not be a valid concern, because we will figure out the size for the controller and replicas, right?

> When a volume fails to expand and leaves some replicas with a mismatched size, Longhorn will potentialy back up the wrong replica to remote storage and is not aware of the size mismatch ([code](https://github.com/longhorn/longhorn-manager/blob/0eec020db8d889ba37318d9a4717268cd2daca74/controller/backup_controller.go#L492)).

**Comment by innobead** [comment]
oh, I forgot that. Any expansion failure will trigger the rollback, so the volume should be independently not impacted and continue running. 
https://github.com/longhorn/longhorn-engine/commit/6b26c16f

**Comment by innobead** [comment]
@derekbit I think I am OK with not continuing this fix. Let's close it.

**Comment by derekbit** [comment]
> So, basically, the below case should not be a valid concern, because longhorn will figure out the size for the controller and replicas, right?

Exactly.

> If failed to expand a volume, what will happen?

The steps to volume expansion is create a new disk and then update in-memory data (e.g. `diffDisk.localtion` and `diffDisk.size`). The second step won't error out. It will try to roll back if the error occurred in the first step. If the rollback failed, the failed replica will be marked as ERR and then be rebuilt.

**Comment by innobead** [comment]
> The steps to volume expansion is create a new disk and then update in-memory data (e.g. `diffDisk.localtion` and `diffDisk.size`). The second step won't error out. It will try to roll back if the error occurred in the first step. If the rollback failed, the failed replica will be marked as ERR and then be rebuilt.

Yeah, you are right! 
https://github.com/longhorn/longhorn-engine/blob/a32136397a0d5044cd2744080d4129c6943d738d/pkg/controller/control.go#L943-L946

cc @longhorn/dev for knowledge sharing.

**Comment by shuo-wu** [comment]
> the engine cannot be aware of the unexpected downstream replica's expansion and results in this error.

This can be applied to some other kind of field mismatching. For example, if users send some requests by themselves, some flags like `revisionCounterDisabled` or `unmapMarkDiskChainRemoved` in replicas can be different from those in the engine. Right now there is no way to detect the mismatchings and correct them... 

Back to the expansion failure, if there are some replica expansions getting failed, the [engine can handle it correctly](https://github.com/longhorn/longhorn-engine/blob/5be4a64b102f8d86bbdf9dc0028f64767dda426f/pkg/controller/control.go#L251-L266). Most of the time we don't need to worry about it except for one corner case. This corner case cannot be handled by the rollback mechanism or the engine itself: 
Users send an expansion request to an old engine or an engine in the old instance manager by themselves. In this case, all replica expansion should succeed but the engine frontend (iscsi) expansion will fail. Later, if users detach and re-attach this volume, Longhorn cannot process it correctly. (replicas are expanded but the volume & the engine are still using the old size.)
