### ISSUE TITLE
[BUG] Sometimes statefulset data gone after node(volume attached to) network reconnect

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#4680]
## Describe the bug

Sometimes statefulset data gone after node(volume attached to) network reconnect

Not every time but can reproduced

## To Reproduce
Disconnect [script](https://github.com/longhorn/longhorn/files/4864127/network_down.sh.zip
) 
1. Launch Longhorn.
2. Use statefulset launch a pod with the volume and write some data.
3. Disconnect the node that the volume attached to for 100 seconds.
4. Wait for the node back and the volume reattachment.
5. After the volume is reattached, the pod will be automatically deleted and recreate.
6. Verify the data and the pod still works fine.
7. Repeat step 2~6 for 3 times.
8. Create, Attach, and detach other volumes to the recovered node. All volumes should work fine.
9. Remove Longhorn and repeat step 1~9 for 3 times.

Sometimes after node reconnect, from UI can observe all replica change from failed to running, and pod data will gone ( in my case , file still exist)

## Expected behavior

Data should kept

## Log or Support bundle

[longhorn-support-bundle_5a3f78ed-079d-45b1-82e4-d56567ed73e2_2022-10-05T12-32-09Z.zip](https://github.com/longhorn/longhorn/files/9715593/longhorn-support-bundle_5a3f78ed-079d-45b1-82e4-d56567ed73e2_2022-10-05T12-32-09Z.zip)

## Environment

 - Longhorn version: v1.3.2-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s 
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config 
   - OS type and version: ubuntu 20.04
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 1

## Additional context

https://longhorn.github.io/longhorn-tests/manual/pre-release/node/node-disconnection/ case 3

**Comment by chriscchien** [comment]
Hi @derekbit ,

Data always retained if I run `sync` in container before network disconnect, even after reconnect all replica failed then become healthy, the data still kept, thank you

**Comment by PhanLe1010** [comment]
Yeah, seems like data has not flushed to disk yet in the original reproducing steps. Great observation, @derekbit

**Comment by innobead** [comment]
Clarified with Chris and Derek. What Chris did for each iteration is independent, so if encountering no flush, the file would be created but w/ empty data.

This is more about the application's responsibility to ensure data sync or rely on the system default setting, so it's intended.
