### ISSUE TITLE
[BUG/QUESTION] Microk8s: Longhorn not working after a couple of days

### ISSUE THREAD

**Issue by mattmeye** [longhorn/longhorn#4681]
## Bug/Question

I set up a RasperryPI4 cluster with microk8s. For storage, I installed Longhorn via Helm and now after a few days I have problems.
Does anyone have an idea what I could do to fix longorn. Unfortunately I haven't managed to set up the backup yet.
In addition, there is no alternative to longhorn. What caused the problem and how can I ensure that everything runs smoothly in the future?

```
instance-manager-r-a513fa52                    0/1     Terminating        0               4d3h    <none>         kube1   <none>           <none>
instance-manager-e-f56390ce                    0/1     Terminating        0               4d3h    <none>         kube1   <none>           <none>
csi-snapshotter-bc89d5b95-f4mwz                0/1     Error              347 (19m ago)   4d3h    10.1.2.101     kube2   <none>           <none>
csi-snapshotter-bc89d5b95-9kl5j                0/1     Error              340             4d3h    10.1.18.39     kube1   <none>           <none>
csi-provisioner-7db6466bd7-g2dph               0/1     Unknown            458             4d3h    <none>         kube2   <none>           <none>
csi-resizer-68f7dc67d7-kmv9d                   0/1     CrashLoopBackOff   453 (14m ago)   4d3h    10.1.2.114     kube2   <none>           <none>
csi-attacher-59df67f65b-dzcf2                  0/1     CrashLoopBackOff   359 (12m ago)   4d3h    10.1.2.98      kube2   <none>           <none>
instance-manager-r-b56705d7                    0/1     Unknown            0               19h     <none>         kube2   <none>           <none>
```

## Environment

 - Longhorn version: [v1.3.1](https://artifacthub.io/packages/helm/longhorn/longhorn/1.3.1)
 - Kubernetes version: v1.24.6-2+4d6cc142010b44
 - Node config
   - OS type and version: Ubuntu 22.04.1 LTS
   - CPU per node: 4
   - Memory per node: 8GB
   - Disk type (1TB m.2 SDD via USB - no sdcard)
   - Network bandwidth and latency between the nodes: ping -U <= 0.5ms
   - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal - RaspberryPi4B8GB

### bandwidth
```
------------------------------------------------------------
Client connecting to 192.168.178.200, TCP port 5001
TCP window size: 85.0 KByte (default)
------------------------------------------------------------
[  1] local 192.168.178.201 port 58512 connected with 192.168.178.200 port 5001
[ ID] Interval       Transfer     Bandwidth
[  1] 0.0000-10.0417 sec  1.07 GBytes   916 Mbits/sec
```

## Additional context

Helm Values
[longhorn.values.yaml.txt](https://github.com/longhorn/longhorn/files/9718488/longhorn.values.yaml.txt)
[kubectl-logs.txt](https://github.com/longhorn/longhorn/files/9718486/kubectl-logs.txt)

**Comment by uvulpos** [comment]
The current Version installed via Helm3 and I got a memory panic on all 3 Nodes. Was not even able to start the Kubernetes UI. This is concerning
