### ISSUE TITLE
[IMPROVEMENT] The node tags could be synchronized to node annotation.

### ISSUE THREAD

**Issue by weizhe0422** [longhorn/longhorn#4683]
## Is your improvement request related to a feature? Please describe

Since I want to add tags for the node to mount the volumes on specified nodes, so I try to add tags via UI.

There is only update the tags in CRD: `nodes.longhorn.io` but not with node annotation.

![image](https://user-images.githubusercontent.com/17548901/194362670-69ace324-15f8-4bf9-9230-6a9772514da8.png)

![image](https://user-images.githubusercontent.com/17548901/194364167-3d18fe68-e8d3-4da3-bdec-b3f4e4a9fb48.png)

## Describe the solution you'd like

After editing the node tags via UI, it will add/update to the node annotation.

## Describe alternatives you've considered

Type `kubectl annotate node <node-name> node.longhorn.io/default-node-tags='["medium"]'` to add annotation.

## Additional context

https://github.com/longhorn/longhorn/issues/4574

**Comment by derekbit** [comment]
IIUC, the node tag is sufficient for the [#4683](https://github.com/longhorn/longhorn/issues/4683).
Why do wee need annotate the node? Can you elaborate the improvement more?
