### ISSUE TITLE
[BUG] Master head chart not support K8s version v1.25

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#4690]
## Describe the bug

 Master head chart not support K8s version v1.25

## To Reproduce

1. Create k8s v1.25 environment
2. Install helm
3. Run command `git clone https://github.com/longhorn/longhorn.git` and `cd ./longhorn/chart`
4. Install Longhorn by `helm install longhorn . --namespace longhorn-system --create-namespace`
5. Installation won't start 
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "longhorn-psp" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```

## Expected behavior

Longhorn master-head support k8s v1.25 version 

## Log or Support bundle

N/A

## Environment

 - Longhorn version: master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

N/A

**Comment by innobead** [comment]
This is intended because 1.4 will support K8s 1.25.
