### ISSUE TITLE
[IMPROVEMENT] docs: s3

### ISSUE THREAD

**Issue by guettli** [longhorn/longhorn#4692]
## Is your improvement request related to a feature? Please describe

I guess many people are interested if Longhorn does provide a s3 like api.

I searched in your docs and found this:

https://longhorn.io/docs/1.4.0/terminology/#s3

## Describe the solution you'd like

It would be great if you could write two or three more sentences at above URL.

## Describe alternatives you've considered

I could find the answer myself and be happy, but I think updating the docs would be better.

Since I don't know the answer, I can't provide a good PR - sorry.

**Comment by weizhe0422** [comment]
@guettli 
Did you mean to set S3 as the backup destination? If so, you can refer this page: [Set up AWS S3 Backupstore](https://longhorn.io/docs/1.4.0/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-aws-s3-backupstore). 

Or you can give me more information that you want to know. Thanks a lot.

**Comment by weizhe0422** [comment]
Longhorn provide API to operate nodes, volumes and settings in [Python client](https://longhorn.io/docs/1.3.0/references/longhorn-client-python/). 

May I ask what kind of API you think Longhorn could provide to operate.

**Comment by weizhe0422** [comment]
After consult with @joshimoo, he advise to use [s3gw](https://aquarist-labs.io/s3gw/) to expose storage as S3 to use.

**Comment by guettli** [comment]
Thank you for your answer. I created a PR to the docs, to make this more obivous: https://github.com/longhorn/website/pull/594
