### ISSUE TITLE
[BUG] Longhorn volume filling up

### ISSUE THREAD

**Issue by megatr0n28** [longhorn/longhorn#4699]
## Describe the bug

Loki Longhorn volume actual size is way over the total size.
```
Size: 50 Gi
Actual Size: 58.1 Gi
No scheduled snapshots and backups
```
<img width="1517" alt="Screen Shot 2022-10-11 at 12 17 40 PM" src="https://user-images.githubusercontent.com/95495941/195148211-e342b949-87d9-46b6-b8a8-d6e0b3b310c5.png">

Loki filesystem shows the following:
```
/data/loki $ du -h -d 1
34.0M   ./boltdb-shipper-cache
4.6M    ./boltdb-shipper-active
556.0K  ./boltdb-shipper-compactor
2.3G    ./chunks
12.7M   ./wal
2.4G
```

On the node:
```
[root@ip-10-0-112-180 pvc-11de1b37-75e5-4528-b316-c00ccc863cba-b1e7fa2b]# ls -lah
total 59G
drwx------ 2 root root 4.0K Oct 10 21:13 .
drwxr-xr-x 3 root root 4.0K Oct 10 21:26 ..
-rw------- 1 root root 4.0K Oct 11 16:33 revision.counter
-rw-r--r-- 1 root root  50G Oct 11 16:33 volume-head-001.img
-rw-r--r-- 1 root root  178 Oct 10 21:02 volume-head-001.img.meta
-rw-r--r-- 1 root root  195 Oct 10 21:13 volume.meta
-rw-r--r-- 1 root root  50G Oct 10 21:13 volume-snap-a7ab4072-d099-4a81-b9b0-f472aece8cff.img
-rw-r--r-- 1 root root  158 Oct 10 21:13 volume-snap-a7ab4072-d099-4a81-b9b0-f472aece8cff.img.meta
```

```
[root@ip-10-0-112-180 pvc-11de1b37-75e5-4528-b316-c00ccc863cba-b1e7fa2b]# du -h -d 1
59G
```

## Environment

 - Longhorn version: 1.3.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: EKS 1.21
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 5
 - Node config
   - OS type and version: AmazonLinux2
   - CPU per node: 4
   - Memory per node: 15GB
   - Disk type(e.g. SSD/NVMe):NVMe
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 23~

**Comment by weizhe0422** [comment]
Hi @megatr0n28 , 

It is because the snapshots will take spaces to store history of volume, and the size will depends on how much data was in the snapshot. Therefore you will find the actual size is bigger than its normal size.

Ref. https://github.com/longhorn/longhorn/blob/v0.6.0/docs/volume.md#space-taken-by-the-snapshots

**Comment by joshimoo** [comment]
Here is a good page documenting the space values.
https://longhorn.io/docs/1.3.1/volumes-and-nodes/volume-size/#volume-actual-size

**Comment by megatr0n28** [comment]
Is there a way to shrink the actual size of the volume?

**Comment by weizhe0422** [comment]
Since Lognhorn use sparse file as the base, it is not easy to shrink the volume size. 

But we continue trying to do this, and the there is already a ticket for tracking: [Issue#836](https://github.com/longhorn/longhorn/issues/836).

**Comment by innobead** [comment]
Filesystem size reduction will not reflect back to the block level at the moment until https://github.com/longhorn/longhorn/issues/836 is introduced. 

Closing, but rather follow up https://github.com/longhorn/longhorn/issues/836. cc @shuo-wu
