### ISSUE TITLE
[BUG] rebuilding the replica failed after upgrading from 1.2.4 to 1.3.2-rc2

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#4705]
## Describe the bug

the replica keeps creating and deleting after upgrading from 1.2.4 to 1.3.2-rc2 and upgrading the volume engine.

## To Reproduce

1. Create a Longhorn v1.2.4 environment
2. Create 3 pvc volumes with Deployments.
3. Upgrade Longhorn from v1.2.4 to v1.3.2-rc2
4. Upgrade volume engines to the newest version.
5. Delete the replica on the node the pvc volume is not attached to.
6. Rebuild the replica failed and keep creating and deleting replenished replica.

## Expected behavior

Replica rebuilding works and volume is not at degraded state.

## Log or Support bundle

[longhorn-support-bundle_fb65171c-910f-4b83-a69c-0f968eaff8c3_2022-10-12T06-46-51Z.zip](https://github.com/longhorn/longhorn/files/9762388/longhorn-support-bundle_fb65171c-910f-4b83-a69c-0f968eaff8c3_2022-10-12T06-46-51Z.zip)

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.24.2+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04.4 LTS
   - CPU per node: 4
   - Memory per node: 8
   - Disk type(e.g. SSD/NVMe): 50
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 3

**Comment by innobead** [comment]
@longhorn/qa The daily upgrade testing doesn't verify upgrading from the previous branch release like 1.2.5 -> 1.3.2 but only 1.3.0 -> 1.3.2, so this issue did not be caught.

**Comment by innobead** [comment]
cc @longhorn/dev :point_down: 

> * From v1.4.0, we assume all Longhorn is upgrade from v1.3.x and all engines are already upgraded to v1.3.x. We don't need to maintain the engine binary command line.

**Comment by chriscchien** [comment]
**Verified on longhorn manager master-head `d0df36` with test [steps](https://github.com/longhorn/longhorn/issues/4705#issue-1405685731)
Result Pass**

- Can be reproduced by upgrade longhorn from `v1.2.5` to `v1.3.2-rc2`
- Upgrade longhorn `v1.2.5` to `master-head`, and upgrade engine image then delete one replica, the replica rebuild success.
