### ISSUE TITLE
[TEST] Add replica deletion and rebuilding case in the upgrade test.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#4709]
## What's the test to develop? Please describe

Add the case of replica deletion and rebuilding case to the upgrade test https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_upgrade.py

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [x] Come up with the test steps. Get it reviewed.
- [x] Implement the test.
- [x] Run tests with different upgrade paths on Jenkins and observe the test result.

## Related Issues
https://github.com/longhorn/longhorn/issues/4705

**Comment by Lichiehyao** [comment]
@longhorn/qa need to review test case steps first.
  - https://github.com/longhorn/longhorn-tests/pull/1168

**Comment by roger-ryao** [comment]
Modify test case and test private image
- [ ] `1.3.2` upgrade to `master-head` regression
  -  https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2428
- [ ] `1.2.5` upgrade to `1.3.2-rc2`
  - https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2426
- [ ] `1.2.5` upgrade to `1.3.x-head`
  - https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2425

**Comment by roger-ryao** [comment]
Update the upgrade test steps and make the test case readable. 
Waiting for review
  - https://github.com/longhorn/longhorn-tests/pull/1168

**Comment by roger-ryao** [comment]
https://github.com/longhorn/longhorn-tests/pull/1168 was merged
