### ISSUE TITLE
[TASK] Add/remove issues to/from the current sprint when Zenhub board pipeline changes

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4720]
## What's the task? Please describe

For now, all pipeline status change or sprint update relies on the assignee to help with the update, but somehow the status will become incorrect if the assignee forgets or misses the update. 

We would like to have some automation for adding/removing issues to the `current` sprint when the pipeline status changes.

## Describe the items of the task (DoD, definition of done) you'd like

- [x] Add issues to the current sprint if the pipeline changes from `Triage`, `IceBox`, and `Backlog` to another state
- [x] Remove issues from the current sprint if the pipeline changes to `Triage`, `IceBox`

cc @longhorn/qa @longhorn/dev

**Comment by yangchiu** [comment]
Zenhub REST API doesn't support manipulating sprint, need to study GraphQL now.

**Comment by innobead** [comment]
> Zenhub REST API doesn't support manipulating sprint, need to study GraphQL now.

Sounds good. GraphQL seems like a new de-facto API adopted by GitHub and Zenhub.

**Comment by yangchiu** [comment]
ref: https://github.com/longhorn/bot/pull/20
