### ISSUE TITLE
[TEST] Analyze master-head pipeline test result (build 282) 

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#4722]
## What's the test to develop? Please describe

Analyze master-head pipeline test result (build [282](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/282/#showFailuresLink)) 

test_ha.test_autosalvage_with_data_locality_enabled

- Issue [[BUG] test_autosalvage_with_data_locality_enabled failed in v1.3.1-rc2](https://github.com/longhorn/longhorn/issues/4382)

test_basic.test_allow_volume_creation_with_degraded_availability_restore

- Issue [[BUG] test_allow_volume_creation_with_degraded_availability_restore failed at master-head pipeline](https://github.com/longhorn/longhorn/issues/4719)

test_basic.test_backup_volume_restore_with_access_mode[s3-rwx-rwo]

- PR [bug: fix to create rwx volume with PV & PVC deployment #1147](https://github.com/longhorn/longhorn-tests/pull/1147)

test_csi_snapshotter.test_csi_snapshot_with_invalid_param

- Teardown fail on pipeline, can not reproduce on local

test_ha.test_auto_remount_with_subpath

- PR https://github.com/longhorn/longhorn-tests/pull/1159

test_scheduling.test_replica_auto_balance_node_best_effort

- Flaky, fixing

test_settings.test_setting_concurrent_rebuild_limit

- Flaky, fixing

## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] Analyze failed item, create related issue or fix test script 

## Additional context

N/A

**Comment by Lichiehyao** [comment]
Hi @chriscchien 
    If you have tasks about `test_ha.test_auto_remount_with_subpath`, `test_scheduling.test_replica_auto_balance_node_best_effort` & `test_settings.test_setting_concurrent_rebuild_limit`, could 
 you also tag me in the ticket? I need to reference that.

**Comment by chriscchien** [comment]
Currently master-head pipeline there few failed test case, distro [AMD64](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/306/) and [ARM64](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/290/) both only have 2 failed case, 1 was known issue [test_autosalvage_with_data_locality_enabled](https://github.com/longhorn/longhorn/issues/4382) and another 1 was flaky test case, close this ticket
