### ISSUE TITLE
[BUG] The old instance-manager-r Pods are not deleted after upgrade

### ISSUE THREAD

**Issue by starbops** [longhorn/longhorn#4726]
## Describe the bug

During an upgrade of Harvester, I occasionally encounter the issue that the upgrade waits for the number of LH `instance-manager-r` Pods to become 1 on a specific node after LH has been upgraded.

```
node-2:~ # k -n harvester-system logs hvst-upgrade-6z2mt-apply-manifests-nv2jf
...
instance-manager-r pod count is not 1 on node node-0, will retry...
instance-manager-r pod count is not 1 on node node-0, will retry...
instance-manager-r pod count is not 1 on node node-0, will retry...
```

Though the check is Harvester-specific, this reflects the situation that the old IM-r Pod is not deleted after a new one has spun up, and it lasts almost forever. Some of the replicas are managed by the old IM-r Pod, and some of them are managed by the new one.

The `instance-manager-r` Pods running on `node-0`:

```
node-2:~ # k -n longhorn-system get po -l longhorn.io/instance-manager-type=replica,longhorn.io/node=node-0 -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.spec.containers[0].image}{"\n"}{end}'
instance-manager-r-06d7a790     longhornio/longhorn-instance-manager:v1_20221003
instance-manager-r-d5acb311     longhornio/longhorn-instance-manager:v1_20220303
```

The replicas managed by the above `instance-manager-r` Pods on `node-0`:

```
node-2:~ # k get lhr -n longhorn-system -l longhornnode=node-0
NAME                                                  STATE     NODE     DISK                                   INSTANCEMANAGER               IMAGE                               AGE
pvc-1d923869-7b4c-4395-a5e8-ad9785417abd-r-85e55078   stopped   node-0   24e133ac-90bf-47ea-bf3f-0a519adda3ec                                                                     11d
pvc-6a4edb98-5e84-4550-92f8-eee461c3d02c-r-798f26e8   stopped   node-0   24e133ac-90bf-47ea-bf3f-0a519adda3ec                                                                     11d
pvc-bdf1cf10-99f4-4a60-869f-68b79453d1b6-r-3196d015   running   node-0   24e133ac-90bf-47ea-bf3f-0a519adda3ec   instance-manager-r-d5acb311   longhornio/longhorn-engine:v1.2.4   11d
pvc-bdf1cf10-99f4-4a60-869f-68b79453d1b6-r-b5b9fcae   stopped   node-0   24e133ac-90bf-47ea-bf3f-0a519adda3ec                                                                     91m
pvc-e63be9a3-e698-4be0-b104-d58d6b8d71cd-r-507976a7   running   node-0   24e133ac-90bf-47ea-bf3f-0a519adda3ec   instance-manager-r-06d7a790   longhornio/longhorn-engine:v1.3.2   154m
pvc-fdb1cda6-090c-4389-be78-23913f020b39-r-54f5cb14   stopped   node-0   24e133ac-90bf-47ea-bf3f-0a519adda3ec                                                                     91m
pvc-fdb1cda6-090c-4389-be78-23913f020b39-r-5a499dab   running   node-0   24e133ac-90bf-47ea-bf3f-0a519adda3ec   instance-manager-r-d5acb311   longhornio/longhorn-engine:v1.2.4   11d
```

All the attached volumes are healthy:

```
node-2:~ # k -n longhorn-system get lhv
NAME                                       STATE      ROBUSTNESS   SCHEDULED   SIZE          NODE     AGE
pvc-1d923869-7b4c-4395-a5e8-ad9785417abd   detached   unknown                  10737418240            11d
pvc-6a4edb98-5e84-4550-92f8-eee461c3d02c   detached   unknown                  10737418240            11d
pvc-94ddaff8-01e2-4048-8ce5-bdaec9a3a48c   detached   unknown                  10737418240            11d
pvc-bdf1cf10-99f4-4a60-869f-68b79453d1b6   attached   healthy                  53687091200   node-3   11d
pvc-e63be9a3-e698-4be0-b104-d58d6b8d71cd   attached   healthy                  10737418240   node-0   165m
pvc-fdb1cda6-090c-4389-be78-23913f020b39   attached   healthy                  10485760      node-3   11d
```

However, we found some of the volumes' engine images are not updated successfully:

```
node-2:~ # k -n longhorn-system get lhv pvc-bdf1cf10-99f4-4a60-869f-68b79453d1b6 -o jsonpath='[{.spec.engineImage}, {.status.currentImage}]'
[longhornio/longhorn-engine:v1.3.2, longhornio/longhorn-engine:v1.2.4]
node-2:~ # k -n longhorn-system get lhv pvc-fdb1cda6-090c-4389-be78-23913f020b39 -o jsonpath='[{.spec.engineImage}, {.status.currentImage}]'
[longhornio/longhorn-engine:v1.3.2, longhornio/longhorn-engine:v1.2.4]
```

Here are the suspicious logs found in the Longhorn Manager

```
node-2:~ # k -n longhorn-system logs longhorn-manager-z9pps
...
time="2022-10-17T02:56:54Z" level=warning msg="Error syncing Longhorn replica longhorn-system/pvc-bdf1cf10-99f4-4a60-869f-68b79453d1b6-r-007cf816" controller=longhorn-replica error="failed to sync replica for longhorn-system/pvc-bdf1cf10-99f4-4a60-869f-68
b79453d1b6-r-007cf816: invalid Instance Manager instance-manager-r-33e2295c, state: , IP: " node=node-1
time="2022-10-17T02:56:54Z" level=warning msg="Error syncing Longhorn replica longhorn-system/pvc-fdb1cda6-090c-4389-be78-23913f020b39-r-2aedd343" controller=longhorn-replica error="failed to sync replica for longhorn-system/pvc-fdb1cda6-090c-4389-be78-23
913f020b39-r-2aedd343: invalid Instance Manager instance-manager-r-33e2295c, state: , IP: " node=node-1
time="2022-10-17T02:56:54Z" level=warning msg="Error syncing Longhorn replica longhorn-system/pvc-bdf1cf10-99f4-4a60-869f-68b79453d1b6-r-007cf816" controller=longhorn-replica error="failed to sync replica for longhorn-system/pvc-bdf1cf10-99f4-4a60-869f-68
b79453d1b6-r-007cf816: invalid Instance Manager instance-manager-r-33e2295c, state: , IP: " node=node-1
time="2022-10-17T02:56:54Z" level=warning msg="Error syncing Longhorn replica longhorn-system/pvc-fdb1cda6-090c-4389-be78-23913f020b39-r-2aedd343" controller=longhorn-replica error="failed to sync replica for longhorn-system/pvc-fdb1cda6-090c-4389-be78-23
913f020b39-r-2aedd343: invalid Instance Manager instance-manager-r-33e2295c, state: , IP: " node=node-1
time="2022-10-17T02:56:54Z" level=warning msg="Error syncing Longhorn replica longhorn-system/pvc-bdf1cf10-99f4-4a60-869f-68b79453d1b6-r-007cf816" controller=longhorn-replica error="failed to sync replica for longhorn-system/pvc-bdf1cf10-99f4-4a60-869f-68
b79453d1b6-r-007cf816: invalid Instance Manager instance-manager-r-33e2295c, state: , IP: " node=node-1
time="2022-10-17T02:56:54Z" level=warning msg="Error syncing Longhorn replica longhorn-system/pvc-fdb1cda6-090c-4389-be78-23913f020b39-r-2aedd343" controller=longhorn-replica error="failed to sync replica for longhorn-system/pvc-fdb1cda6-090c-4389-be78-23
913f020b39-r-2aedd343: invalid Instance Manager instance-manager-r-33e2295c, state: , IP: " node=node-1
E1017 02:56:54.695340       1 replica_controller.go:179] failed to sync replica for longhorn-system/pvc-fdb1cda6-090c-4389-be78-23913f020b39-r-2aedd343: invalid Instance Manager instance-manager-r-33e2295c, state: , IP:
time="2022-10-17T02:56:54Z" level=warning msg="Dropping Longhorn replica longhorn-system/pvc-fdb1cda6-090c-4389-be78-23913f020b39-r-2aedd343 out of the queue" controller=longhorn-replica error="failed to sync replica for longhorn-system/pvc-fdb1cda6-090c-
4389-be78-23913f020b39-r-2aedd343: invalid Instance Manager instance-manager-r-33e2295c, state: , IP: " node=node-1
E1017 02:56:54.695919       1 replica_controller.go:179] failed to sync replica for longhorn-system/pvc-bdf1cf10-99f4-4a60-869f-68b79453d1b6-r-007cf816: invalid Instance Manager instance-manager-r-33e2295c, state: , IP:
time="2022-10-17T02:56:54Z" level=warning msg="Dropping Longhorn replica longhorn-system/pvc-bdf1cf10-99f4-4a60-869f-68b79453d1b6-r-007cf816 out of the queue" controller=longhorn-replica error="failed to sync replica for longhorn-system/pvc-bdf1cf10-99f4-4a60-869f-68b79453d1b6-r-007cf816: invalid Instance Manager instance-manager-r-33e2295c, state: , IP: " node=node-1
...
```

The replica failed to sync and the state and the IP address info are gone. This might be related to the issue.

## To Reproduce

Steps to reproduce the behavior (**not always reproducible**):

1. Prepare a 4-node Harvester cluster in v1.0.3 (with Longhorn v1.2.4)
2. Upgrade the cluster to master-head (with Longhorn v1.3.2)
3. The upgrade might be stuck waiting for the number of IM-r Pods to become 1 on a certain node

Note: I haven't tried deploying Longhorn without Harvester yet, don't know if that will also happen the same issue.

## Expected behavior

There should be only new IM-r Pods existing (eventually) after an LH upgrade.

## Log or Support bundle

[longhorn-support-bundle_023cfbdf-eb2f-4ca5-b38b-f73236c0f7e8_2022-10-17T10-19-37Z.zip](https://github.com/longhorn/longhorn/files/9802314/longhorn-support-bundle_023cfbdf-eb2f-4ca5-b38b-f73236c0f7e8_2022-10-17T10-19-37Z.zip)

## Environment

 - Longhorn version: v1.2.4 (upgrade to v1.3.2)
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2 v1.22.12+rke2r1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version:
   - CPU per node: 8 (first mgmt node) / 4 (remaining nodes)
   - Memory per node: 16GB (first mgmt node) / 8GB (remaining nodes)
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 6

## Additional context

The Harvester support bundle is provided here if that helps.

[supportbundle_ebe4b217-6355-4356-823a-f9e5f09e28b4_2022-10-17T15-48-16Z.zip](https://github.com/longhorn/longhorn/files/9802378/supportbundle_ebe4b217-6355-4356-823a-f9e5f09e28b4_2022-10-17T15-48-16Z.zip)

**Comment by innobead** [comment]
cc @shuo-wu @derekbit @PhanLe1010

**Comment by PhanLe1010** [comment]
The instance manager pods eventually get state & IP updated in the support bundle.
A weird observation is all new replicas of the volume  pvc-fdb1cda6-090c-4389-be78-23913f020b39 (pvc-fdb1cda6-090c-4389-be78-23913f020b39-r-6bfa3fb9, pvc-fdb1cda6-090c-4389-be78-23913f020b39-r-54f5cb14 , and pvc-fdb1cda6-090c-4389-be78-23913f020b39-r-2aedd343) have spec.desirestate: stopped . This prevent the volume from from being finish upgrading engine image. I am not sure why these replica has spec.desirestate: stopped . From the code, they should be set to running https://github.com/longhorn/longhorn-manager/blob/a9c9fe22395dd58a99e3d729a8d932daaa439eaf/controller/volume_controller.go#L3054-L3075

Oh looks like, we later stops the newly cloned replica [here](https://github.com/longhorn/longhorn-manager/blob/a9c9fe22395dd58a99e3d729a8d932daaa439eaf/controller/volume_controller.go#L1579-L1597) as the new IM pods have empty state at the beginning. Then when the IM pods has non empty state, we still don’t try to restart it.

So may be the reproduce step is trying to upgrade the volume when the default replica IM pod has empty Status.CurrentState


Yeah, looks like I triggered it:
1. Deploy Longhorn v1.3.1. Enable auto engine upgrade by setting `Concurrent Automatic Engine Upgrade Per Node Limit` to  > 0
1. Create a volume and attach it
1. Deploy `longhornio/longhorn-engine:v1.3.2` and wait for it to be deployed. This step is to make sure to expose the race condition that Longhorn tries auto engine upgrade while the new default IM is still starting
1. Upgrade Longhorn to v1.3.2
1. Observe that Volume is stuck in upgrading forever
<img width="1066" alt="Screen Shot 2022-10-17 at 4 46 44 PM" src="https://user-images.githubusercontent.com/22139961/196308086-9a3ce042-6fe4-4fdb-be64-8d0e5f45e70b.png">
<img width="900" alt="Screen Shot 2022-10-17 at 4 46 30 PM" src="https://user-images.githubusercontent.com/22139961/196308092-802f5aa2-314c-45cb-8501-9a8125e16b5b.png">

**Comment by PhanLe1010** [comment]
**Workaround**: Detach and reattach the problematic volumes

**Comment by starbops** [comment]
Verified that detaching and reattaching the problematic volumes in the original environment can get this over.

The problematic volume with the new engine image configured still remains with the old image after the upgrade:

```
node-2:~ # k -n longhorn-system get lhv pvc-fdb1cda6-090c-4389-be78-23913f020b39 -o jsonpath='{.spec.engineImage} {.status.currentImage}'
longhornio/longhorn-engine:v1.3.2 longhornio/longhorn-engine:v1.2.4
```

Detaching the volume by setting the workload replicas to 0:

```
node-2:~ # k -n cattle-monitoring-system edit deploy rancher-monitoring-grafana
deployment.apps/rancher-monitoring-grafana edited
node-2:~ # k -n longhorn-system get lhv pvc-fdb1cda6-090c-4389-be78-23913f020b39
NAME                                       STATE      ROBUSTNESS   SCHEDULED   SIZE       NODE   AGE
pvc-fdb1cda6-090c-4389-be78-23913f020b39   detached   unknown                  10485760          12d
```

Soon it'll become the new one, then change the workload replicas back.

```
node-2:~ # k -n longhorn-system get lhv pvc-fdb1cda6-090c-4389-be78-23913f020b39 -o jsonpath='{.spec.engineImage} {.status.currentImage}'
longhornio/longhorn-engine:v1.3.2 longhornio/longhorn-engine:v1.3.2
```

Thanks!

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by innobead** [comment]
@mantissahz Please remember update the above check-list comment.

**Comment by innobead** [comment]
This is a day 1 issue, so let's remove this from 1.2.6 because need some time for review.

**Comment by khushboo-rancher** [comment]
@chriscchien Remember to add the test skeleton for https://github.com/longhorn/longhorn/issues/4730 while you're testing it. Thanks

**Comment by chriscchien** [comment]
**Verified in longhorn master `a0a641` with [steps](https://github.com/longhorn/longhorn/issues/4726#issuecomment-1296663201)
Result Pass**

Volume not stuck at upgrading when upgrade Longhorn from v1.3.2(Concurrent Automatic Engine Upgrade Per Node Limit > 0 and longhornio/longhorn-engine:master-head deployed) to master-head .
