### ISSUE TITLE
[Bug] [1.2.x] Degraded volume generate failed replica make volume unschedulable

### ISSUE THREAD

**Issue by Lichiehyao** [longhorn/longhorn#4732]
## Describe the bug

After analized 1.2.x CI failed case [test_allow_volume_creation_with_degraded_availability](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/256/testReport/junit/tests/test_basic/test_allow_volume_creation_with_degraded_availability/), we found out the degraded volume generate failed replica make volume unschedulable.

## To Reproduce

We could reproduce it in the two ways.
---
> 1
1. Longhorn with 3 nodes
2. Set 'Allow Volume Creation with Degraded Availability' to True
3. Set 'Replica Node Level Soft Anti-Affinity' to False
4. Disable scheduling on node 3
5. Create volume with 3 replicas and attach to node 3
6. Detach volume and attach volume to node 3
7. Enable scheduling on node 3
![Screenshot_20221018_165339](https://user-images.githubusercontent.com/104337648/196384581-c1c6ee9b-24d6-4279-8de7-0f6007a4d9f1.png)
---
> 2
execute the test case `pytest -v test_basic.py::test_allow_volume_creation_with_degraded_availability`

## Expected behavior

1. Volume should become scheduled, but somehow there will an failed replica make volume unscheduled.

## Log or Support bundle

[longhorn-support-bundle_417080c4-d22a-433b-b37b-ecf52a02e276_2022-10-18T08-47-06Z.zip](https://github.com/longhorn/longhorn/files/9808666/longhorn-support-bundle_417080c4-d22a-433b-b37b-ecf52a02e276_2022-10-18T08-47-06Z.zip)

[longhorn-support-bundle_417080c4-d22a-433b-b37b-ecf52a02e276_2022-10-18T08-03-55Z.zip](https://github.com/longhorn/longhorn/files/9808669/longhorn-support-bundle_417080c4-d22a-433b-b37b-ecf52a02e276_2022-10-18T08-03-55Z.zip)

## Environment

 - Longhorn version: 1.2.x-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:K3s
   - Number of management node in the cluster: one
   - Number of worker node in the cluster: three
 - Node config
   - OS type and version: ubuntu
   - CPU per node: 4 
   - Memory per node: 16GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):AWS
 - Number of Longhorn volumes in the cluster: one

## Additional context

Similar issue on [master-head](https://github.com/longhorn/longhorn/issues/3220)

**Comment by Lichiehyao** [comment]
After checked the 1.2.x, 1.3.x & master-head CI test reports, we only observe failure on the build 1.2.x.
cc @longhorn/qa

**Comment by derekbit** [comment]
My bad. I forgot to backport https://github.com/longhorn/longhorn/issues/3220 to v1.2.x before...

**Comment by derekbit** [comment]
Duplicated
Fix in https://github.com/longhorn/longhorn/issues/4770
