### ISSUE TITLE
[TEST] Implement the test 'test_auto_upgrade_engine_to_default_version'

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#4737]
## What's the test to develop? Please describe

Implement the test 'test_auto_upgrade_engine_to_default_version'

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [x] Implementation of the test
- [x] Observing the test results on the Jenkins

## Additional context
https://github.com/longhorn/longhorn-tests/pull/1177

**Comment by chriscchien** [comment]
Verified on [amd64](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/327/testReport/tests/test_engine_upgrade/test_auto_upgrade_engine_to_default_version/) [arm64](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/311/testReport/tests/test_engine_upgrade/test_auto_upgrade_engine_to_default_version/) pipeline, close this ticket
