### ISSUE TITLE
[BUG] Backing image resync not work on v1.2.x

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#4738]
## Describe the bug

When backing image deleted no node, longhorn have feature to resync failed one, this feature worked on `master-head` and on `v1.3.x`, but not on `v1.2.x`

## To Reproduce

1. Create backing image
2. Create volume by backing image and attach to node
3. Wait volume healthy
4. In any node run `rm -rf /var/lib/longhorn/backing-images/`
5. In `v1.2.x` the backing image deleted not recover and show failed forever, but in master-head and `v1.3.x`, the backing image recover soon

## Expected behavior

Backing images resync feature should also work on `v1.2.x`

## Log or Support bundle

[longhorn-support-bundle_92a01615-54a9-4fa6-a9be-623e94b6171b_2022-10-19T03-47-39Z.zip](https://github.com/longhorn/longhorn/files/9816649/longhorn-support-bundle_92a01615-54a9-4fa6-a9be-623e94b6171b_2022-10-19T03-47-39Z.zip)

## Environment

 - Longhorn version: v1.2.x-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Node config
   - OS type and version: ubuntu 20.04
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): vmware
 - Number of Longhorn volumes in the cluster: 1

## Additional context

e2e failed [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2205/)
e2e [case](https://github.com/longhorn/longhorn-tests/blob/86ab23621c189b80a02cde7b89ecf6679c6241cc/manager/integration/tests/test_backing_image.py#L482)

**Comment by shuo-wu** [comment]
The cause of this issue: the work directory `<disk path>/backing-images/` will be created only at the starting stage of the backing image manager. Here the directory is removed when the backing image manager is running, there is no way to recreate it then the backing images in the corresponding disk cannot be resynced.

**Comment by chriscchien** [comment]
Passed in v1.2.x pipeline #[273](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/273/testReport/tests/test_backing_image/), #[272](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/272/testReport/tests/test_backing_image/), closes this ticket
