### ISSUE TITLE
[DOC] Update the Longhorn document in Install with Helm

### ISSUE THREAD

**Issue by Lichiehyao** [longhorn/longhorn#4745]
## Is your improvement request related to a feature? Please describe

The users follow the Longhorn document in [Install with Helm](https://longhorn.io/docs/1.3.0/deploy/install/install-with-helm/).They could not helm install previous releases version of Longhorn.

## Describe the solution you'd like

I want to update the Longhorn document in [Install with Helm](https://longhorn.io/docs/1.3.0/deploy/install/install-with-helm/).
After that, users could follow the Longhorn document in [Install with Helm](https://longhorn.io/docs/1.3.0/deploy/install/install-with-helm/) and helm install a specific version of Longhorn.

## Describe alternatives you've considered

NA

## Additional context

`helm install longhorn longhorn/charts/longhorn --namespace longhorn-system --create-namespace --version 1.2.4`

**Comment by innobead** [comment]
cc @longhorn/qa this is good to have QA contribute to the doc as well.

**Comment by Lichiehyao** [comment]
- [x] 1.1.0
- [x] 1.1.1
- [x] 1.1.2
- [x] 1.1.3
- [x] 1.2.0
- [x] 1.2.1
- [x] 1.2.2
- [x] 1.2.3
- [x] 1.2.4
- [x] 1.2.5 
- [x] 1.2.6
- [x] 1.3.0
- [x] 1.3.1
- [x] 1.3.2
- [x] 1.3.3
- [x] 1.4.0
**Result Passed**
