### ISSUE TITLE
[DOC] Add TOC for each doc parent page

### ISSUE THREAD

**Issue by weizhe0422** [longhorn/longhorn#4754]
## Describe the solution you'd like

Each subpost of the Lognhorn documentation should have a table of contents.

~~Automatically generated based on content to make keyword searches accurate.~~

## Additional context

https://longhorn.io/docs/1.3.2/snapshots-and-backups/

**Comment by innobead** [comment]
@weizhe0422 automation is nice to have, but not what I would expect. 

You can simply manually fix that for the current latest version like 1.3.2.
