### ISSUE TITLE
[BUG] logs spamming with messages `invalid customized default setting ...`

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4760]
## Describe the bug

Longhorn manager logs are full of messages like:
```
[longhorn-manager-6nv6p longhorn-manager] time="2022-10-20T22:45:27Z" level=error msg="invalid customized default setting priority-class with value system-cluster-critical, will continue applying other customized settings" error="fail to set the setting priority-class with invalid value system-cluster-critical: cannot modify priority class setting before all volumes are detached" 
...

[longhorn-manager-b5452 longhorn-manager] time="2022-10-20T22:45:55Z" level=error msg="invalid customized default setting taint-toleration with value task.mining/cpu=present:NoSchedule; nvidia.com/gpu=present:NoSchedule, will continue applying other customized settings" error="fail to set the setting taint-toleration with invalid value task.mining/cpu=present:NoSchedule; nvidia.com/gpu=present:NoSchedule: cannot modify toleration setting before all volumes are detached" 

```

It appears every 30s which is the same as the resync of the [kubernetes_configmap_controller](https://github.com/longhorn/longhorn-manager/blob/v1.3.1/controller/kubernetes_configmap_controller.go).

This error is misleading as the settings already took effect but Longhorn is still spamming the errors every 30s resync period [here](https://github.com/longhorn/longhorn-manager/blob/338782758fcf273d2c2a4481d39eaf4d84b3417b/controller/kubernetes_configmap_controller.go#L202-L206)

## To Reproduce (untested yet)
1. Install Longhorn v1.3.1
2. Changing `taint-toleration` setting
3. Create some volumes and attach them
4. What the log spamming every 30s

## Expected behavior

misleading errors shouldn't be there

## Environment

 - Longhorn version: Longhorn v1.3.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.22.12+rke2r1

**Comment by PhanLe1010** [comment]
cc @derekbit @shuo-wu

**Comment by derekbit** [comment]
Duplicate https://github.com/longhorn/longhorn/issues/4554
cc @weizhe0422
