### ISSUE TITLE
[BUG] Replica Auto Balance repeatedly delete the local replica and trigger rebuilding

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4761]
## Describe the bug

Replica Auto Balance repeatedly delete the local replica and trigger rebuilding

## To Reproduce

1. Install Longhorn 1.3.2
2. Set Replica Auto Balance to `best-effort` 
3. Create a volume of 1 replica with data-locality set to `best-effort`
4. Attach the volume to a node that doesn't have any replica  
5. Observer that Longhorn start rebuilding a local replica
6. If we are lucky, the new local replica has a name alphabetically smaller than the old replica. So Longhorn delete it
7. The cycle repeats again

## Expected behavior

Longhorn shouldn't repeatedly deleted the newly rebuilt local replica

## Log or Support bundle

[longhorn-support-bundle_7761b134-b8e6-4ce4-b178-1048f894641c_2022-10-21T00-14-13Z.zip](https://github.com/longhorn/longhorn/files/9834794/longhorn-support-bundle_7761b134-b8e6-4ce4-b178-1048f894641c_2022-10-21T00-14-13Z.zip)

## Environment

 - Longhorn version: Longhorn v1.3.2

## Additional context

It seems that we don't respect the local replica here https://github.com/longhorn/longhorn-manager/blob/c4e7942684cc1f8ece900854d09126a7b1f8c0b6/controller/volume_controller.go#L931-L958

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by c3y1huang** [comment]
The reproducing steps are clear, we should be able to validate with automation e2e. 

Replacing the `manual-test-plan` label with `automation-e2e`.

**Comment by innobead** [comment]
> The reproducing steps are clear, we can validate with automation e2e.
> 
> Replacing the `manual-test-plan` label with `automation-e2e`.

Sounds good :+1: !

**Comment by innobead** [comment]
@c3y1huang is this a day one issue?

**Comment by c3y1huang** [comment]
> @c3y1huang is this a day one issue?

Yes.

**Comment by Lichiehyao** [comment]
**Verified on master-head 20221026**

- longhorn master-head ([777bc5b](https://github.com/longhorn/longhorn/commit/777bc5b0c025ea2e8bf497bf22fc9d701db50bf9)) 
- longhorn-manager master-head ([76468fa](https://github.com/longhorn/longhorn-manager/commit/76468fa5013b70c5715977e6ba2dc35c3f024974)) 


**The test steps**

[Ref #4761 (To Reproduce)](https://github.com/longhorn/longhorn/issues/4761#issue-1417530673)

**Result Passed**
