### ISSUE TITLE
[BUG] [v1.2.6-rc1] In 1 node cluster, scale down/up deployment will cause failed replica  (allow-volume-creation-with-degraded-availability enabled)

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#4764]
## Describe the bug

https://longhorn.github.io/longhorn-tests/manual/pre-release/node/degraded-availability/

In 1 node cluster, create a deployment pod with a volume and three replicas, when pod is running, there will be 1 running replica and 2 stopped replicas, after scale down/up deployment let volume reattach, the 2 stopped replicas will become 2 failed replicas

If add 2 new nodes into cluster and wait rebuilding complete (3 running replica), the 2 failed replica still exist and UI will show volume unscheduled (pod I/O still working properly in this case) 

## To Reproduce

1. Deploy longhorn with 1 node cluster
2. Create a deployment pod with a volume and three replicas, write data into pod mount point
3. Can see 1 running replica, 2 stopped replicas
4. Scale down / up deployment let volume detach / attach
5. After pod running, the 2 stopped replicas become failed replica
6. Add 2 node into cluster and wait volume rebuild complete
7. Even volume have 3 running replicas as setting , in UI still shows `Scheduling Failure`

## Expected behavior

Volume should no show `Scheduling Failure`

## Log or Support bundle

[longhorn-support-bundle_7855570f-5a99-496d-b06d-93cf30b5171f_2022-10-21T06-58-50Z.zip](https://github.com/longhorn/longhorn/files/9836443/longhorn-support-bundle_7855570f-5a99-496d-b06d-93cf30b5171f_2022-10-21T06-58-50Z.zip)

## Environment

 - Longhorn version: v1.2.6-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.24.6+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: ubuntu 20.04
 - Number of Longhorn volumes in the cluster: 1

## Additional context
The screenshot after add 2 nodes into cluster and rebuild complete
![Screenshot from 2022-10-21 16-21-55](https://user-images.githubusercontent.com/73337386/197150051-eda611f8-c4c4-49fc-810b-b2acd2e29ae0.png)

**Comment by innobead** [comment]
@chriscchien does this also happen to 1.3?

**Comment by innobead** [comment]
I feel some fixes in 1.3 are not backported to 1.2 :thinking: . Thanks, @chriscchien , this is good info.

**Comment by chriscchien** [comment]
I updated screen shot of this issue https://github.com/longhorn/longhorn/issues/4764#issue-1417855286, for reference, thank you

**Comment by derekbit** [comment]
Duplicate 
Fix in https://github.com/longhorn/longhorn/issues/4732
