### ISSUE TITLE
[QUESTION] Add Longhorn UI and then lose all volumes

### ISSUE THREAD

**Issue by rabbagliettiandrea** [longhorn/longhorn#4766]
## Question
I'm (quiet happily) running Longhorn to host Stateful Services Persistent Volumes (PostgreSQL, MinIO, GitLab and so on).

Yesterday I was adding this code in order to setup Longhorn UI (highlighted in red):
![image (1)](https://user-images.githubusercontent.com/579861/197174818-df1758f9-167a-4cf4-8ecf-9e4be06e3f20.png)

Suddenly I realized that something terrible was going on after the apply - **the data Pods were in terminating state**!
![image (2)](https://user-images.githubusercontent.com/579861/197174832-32770e8c-197d-45b0-8a97-5f06456c93fb.png)

And then, `kubectl get events` said this:

![image](https://user-images.githubusercontent.com/579861/197174824-1cc5110e-df29-4387-849b-a283e6157669.png)

So few seconds after I've lost all of my volumes (and data).

Have you got any hints why this happened? I'm not feeling so safe with Longhorn right now but maybe is just a misconfiguration on my side.

Thank you so much for your work! Keep it up :)

## Environment

 - Longhorn version: longhorn-1.3.2
 - Kubernetes version: v1.24.4+k3s1
 - Node config
   - OS type and version:  Ubuntu 22.04.1 LTS
   - CPU per node: 12 CPU (physical)
   - Memory per node: 64 Gb
   - Disk type: SSD NVMe
   - Network bandwidth and latency between the nodes: 1Gbps, 0.3 ms
 - Underlying Infrastructure: Baremetal, worker nodes: 3 server, master nodes: 1 cloud server:

**Comment by PhanLe1010** [comment]
@rabbagliettiandrea Are you sure that you ran helm upgrade instead of helm uninstall? The uninstallation job is created as shown in the provided picture. That only happens during uninstallation.

**Comment by rabbagliettiandrea** [comment]
@PhanLe1010 thank you for your answer mate. Clearly I am sure that I ran `helm upgrade`

**Comment by PhanLe1010** [comment]
Could you please run helm history to see the history of the longhorn chart?

**Comment by rabbagliettiandrea** [comment]
<img width="702" alt="image" src="https://user-images.githubusercontent.com/579861/197969944-6c389def-9a2b-4ed3-a7a2-29fb964119ed.png">

Thank you so much @PhanLe1010 :)

**Comment by rabbagliettiandrea** [comment]
I think that I've just discovered the root-cause: https://github.com/k3s-io/helm-controller/issues/110

I was using Helm Controller from K3s that has this strange behavior (a bug maybe).

Thank you so much
