### ISSUE TITLE
[BUG] [v1.2.6-rc1] Test timeout on loss of network connectivity failed

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#4778]
## Describe the bug

Manual test case: https://longhorn.github.io/longhorn-tests/manual/pre-release/resiliency/timeout/

Longhorn controller should display/catch replica network disconnect status after 8 seconds of network disconnected  .
But in v1.2.6-rc1, the error message raised after 15 minutes (and the error message not the same with test case mentioned)

```
time="2022-10-25T06:11:22Z" level=info msg="Listening on gRPC Controller server: localhost:9501"


time="2022-10-25T06:27:15Z" level=error msg="Error reading from wire 192.168.22.2:9503: read tcp 192.168.22.4:54134->192.168.22.2:9503: rad: no route to host"
time="2022-10-25T06:27:15Z" level=error msg="Backend tcp://192.168.22.2:9502 monitoring failed, mark as ERR: read tcp 192.168.22.4:54134-192.168.22.2:9503: read: no route to host"
time="2022-10-25T06:27:15Z" level=info msg="Set replica tcp://192.168.22.2:9502 to mode ERR"
time="2022-10-25T06:27:15Z" level=info msg="Monitoring stopped tcp://192.168.22.2:9502"
```

## To Reproduce

From Manual test case: https://longhorn.github.io/longhorn-tests/manual/pre-release/resiliency/timeout/
1. Create a docker network `docker network create -d bridge --subnet 192.168.22.0/24 longhorn-network`
2. Start a replica:
```
docker run --net longhorn-network --ip 192.168.22.2 \
         -v /volume longhornio/longhorn-engine:v1.2.6-rc1 \
         longhorn replica --listen 192.168.22.2:9502 --size 10g /volume
```
3. Start another replica on another terminal
```
docker run --net longhorn-network --ip 192.168.22.3 \
         -v /volume longhornio/longhorn-engine:v1.2.6-rc1 \
         longhorn replica --listen 192.168.22.3:9502 --size 10g /volume
```
4. Start the controller on another terminal
```
docker run --net longhorn-network --ip 192.168.22.4 --privileged \
         -v /dev:/dev -v /proc:/host/proc \
         longhornio/longhorn-engine:v1.2.6-rc1 \
         longhorn controller --replica tcp://192.168.22.2:9502 \
         --replica tcp://192.168.22.3:9502 \
         --frontend tgt-blockdev timeout-test
```
5. In another terminal, find the name of the container running the first replica(`192.168.22.2`) with `docker ps`
6. Disconnect the replica container from the network `docker network disconnect longhorn-network <container id/name>`
7. Note that the controller output displays `Backend tcp://192.168.22.2:9502 monitoring failed, mark as ERR: ping timeout` after eight seconds. but the message actually displayed after 15 minutes
## Expected behavior

Controller should catch the network disconnect status of replica

## Log or Support bundle

N/A

## Environment

 - Longhorn version: v1.2.6-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 0

## Additional context

If we stopped replica container(`192.168.22.2`) which network disconnected, controller will not show anything
But if we  stopped replica container(`192.168.22.3`) which have internet connection, controller will catch and display
```
time="2022-10-25T03:09:18Z" level=error msg="Error reading from wire 192.168.22.3:9503: EOF"
time="2022-10-25T03:09:19Z" level=error msg="RemovePendingOp: OpID already removed0"
time="2022-10-25T03:09:19Z" level=error msg="Backend tcp://192.168.22.3:9502 monitoring failed, mark as ERR: EOF"
time="2022-10-25T03:09:19Z" level=info msg="Set replica tcp://192.168.22.3:9502 to mode ERR"
time="2022-10-25T03:09:19Z" level=info msg="Monitoring stopped tcp://192.168.22.3:9502"
```

**Comment by PhanLe1010** [comment]
> Note that the controller output displays Backend tcp://192.168.22.2:9502 monitoring failed, mark as ERR: ping timeout after eight seconds. but the message actually displayed after 15 minutes

Hi @chriscchien! Can I have a quick question? Could you double-check that you got the exact error message? From the code, it doesn't seem possible

**Comment by PhanLe1010** [comment]
This looks like a non-issue and we should remove this ping-timeout test case.

1. This issue is not a regression as if behave the same in 1.2.4 and 1.2.5
1. The reason the we don't see ping timeout error message is that we decided to remove the ping mechanism as described in this commit https://github.com/longhorn/longhorn-engine/commit/32cb7dfd0630c43c2af15c8127f706c83355aea0. We only start the timer for Read or Write message, not the Ping message (see https://github.com/longhorn/longhorn-engine/blob/f7c1938cb10a406d7d6d1bf382db47a2679d38f1/pkg/dataconn/client.go#L154-L159). If we issue a write IO (`dd if=/dev/urandom of=/dev/longhorn/timeout-test count=500 bs=1k`) to the block device after the step `Disconnect the replica container from the network docker network disconnect longhorn-network <container id/name>`, we should see that engine detects the failed replica after around 8s.

**Comment by chriscchien** [comment]
Close this issue because test case was outdated and test case updated [PR](https://github.com/longhorn/longhorn-tests/pull/1161) submitted for review,
