### ISSUE TITLE
[IMPROVEMENT] Speed up replica rebuilding by the metadata such as ctime of snapshot disk files

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4783]
## Is your improvement request related to a feature? Please describe

The replica rebuilding process in current Longhorn is time-consuming. It walks through all snapshot disk files. Each data block is hashed in the local and the remote disk files to determine if it needs to be sent to remote side. It is io-intensive and computing-intensive process, especially if the volume is large or contains tons of snapshot disk files.

ctime and checksum of snapshot disk files are already recorded in their extended attributes after introduing the [feature](https://github.com/longhorn/longhorn/issues/4210).  To speed up the rebuilding process, we can compare the file's current ctime and the ctime in the extended attribute. If they are identical, we can skip the synchronization of this disk file. Then, a reduction in the number of unnecessary computations can speed up the entire process as well as reduce the impact of the system performance.

**Comment by innobead** [comment]
Aggressively adding to 1.4.0, but do this by best efforts.

**Comment by yasker** [comment]
Do we have concern over just use checksum alone? How does create time work for the replica has been rebuilt once?

**Comment by derekbit** [comment]
The checksum of a snapshot disk file is calculated and is recorded in the extended attribute when checking the data integrity. The `ctime` of the disk file is recorded as well.

Then, we can simply use `ctime` or `checksum` for speeding up the rebuilding.

- ctime
  - No need to be couple with `checksum`, so it should work without `checksum`, but cannot detect silent corruption.
  - If the `ctime` in the extended attribute is same as the `ctime` of the file (got from `stat`), it means the disk file is not changed after calulating the checksum, and then the file can be directly sent to remote.
  - If the `ctime` in the extended attribute is different than the `ctime` of the file, the rebuilding will use the legacy method. The `ctime` and `checksum` will be recalculated  and set by the periodical data integrity checking later.

- checksum
  - The downside of the `ctime` method is unable to detect the silent corruption during rebuilding.
  - To detect the silent corruption during replica rebuilding, we can rely on the recorded checksum of each snapshot disk files. It means the disk files' checksumes should be calculated again and then compare with the recorded values.

**Comment by yasker** [comment]
@derekbit I see. Though, should it be ctime or mtime? Not sure if we care about the snapshot file's metadata change. 

Also, I assume once we confirm the file hasn't been changed (at least from the filesystem's point of view), we will still check the checksum and compare it with the remote snapshot's checksum to know if we can safely skip this snapshot? I am wondering if we should consider a malicious user that has access to one node may change the snapshot and metadata file to try to propagate the wrong snapshot to other healthy nodes.

**Comment by innobead** [comment]
We can let users decide what granularity they want by having two strategies as mentioned above.
- `ctime`, a loose strategy w/o coupling with checksum
- `checksum`, a strict strategy, so if users care about some implicit cases like potential silent corruption or malicious things

**Comment by derekbit** [comment]
> I see. Though, should it be ctime or mtime? Not sure if we care about the snapshot file's metadata change.

We should use `ctime`, because the change of metadata or data will update the ctime. Additionally, the ctime update is not allowed by users (ref: https://unix.stackexchange.com/questions/36021/how-can-i-change-change-date-of-file).

**Comment by yasker** [comment]
I feel the basic checksum (compare source and destination checksum) should be used in both cases. Otherwise if we have a situation that somehow one snapshot's data missed by a few bytes, it might get easily propagated to other replicas.

**Comment by innobead** [comment]
> I feel the basic checksum (compare source and destination checksum) should be used in both cases. Otherwise if we have a situation that somehow one snapshot's data missed by a few bytes, it might get easily propagated to other replicas.

Then, we can make `checksum` by default.

**Comment by innobead** [comment]
A further remote checksum confirmation is a good idea, but it's still the best effort due to some assumptions like other nodes not being compromised.

Let's let @derekbit investigate first to see how to consider all concerns together.

**Comment by derekbit** [comment]
In summary, the experiment shows the replica rebuilding is accelerated by 805 % in the 50 GiB volume test. The volume contains 1 volume-head and 8 snapshot disk files, and each disk file contains 45 GiB random data.

#### Experimental Setup
- Host
  Vendor: AWS EC2
  Machine: t2.2xlarge
  CPU: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
  RAM: 32 GB
  Storage: 800 GB SSD (gp2)

- Kubernetes
  Version: v1.24.7+rke2r1
  Nodes: 3 (master + worker)

- Longhorn
  master without rebuilding speedup
  master with rebuilding speedup

- Volume:
  Number of replicas: 3
  Nominal size: 50 GiB
  Actual size: 1 volume-head containing 45GiB random data + 8 snapshots (each one contains 45GiB random data)

#### Experimental Result
- master without rebuilding speedup
  Rebuilding time: 3329 seconds
  Sync 9 snapshot disk files (8 snapshot disk files  and 1 previous volume-head)

- master with rebuilding speedup
  Rebuilding time: 368 seconds
  Skip 8 snapshot disk files, and only sync 1 snapshot disk file (previous volume-head)

**Comment by derekbit** [comment]
Add a new option in ReplicaAdd command, need to update the engine upgrade test image.
cc @longhorn/qa

**Comment by chriscchien** [comment]
New test image build triggered [here](https://ci.longhorn.io/job/private/job/build-engine-test-images/13/)

**Comment by derekbit** [comment]
@dberardo-com 
live volumes' replicas?
If yes, the healthy replicas on other nodes and the replicas on the offline node are out of sync, so the replica rebuilding is inevitable.

**Comment by dberardo-com** [comment]
1. is there a way to set a timeout for that to happen or is it just based on the amount of data written on "the master" replica ?
2. I understand also, that longhorn automatically tries to rebuild replicas in a faster way, by looking at the last snapshot and the diffs with the currently changed blocks on the master (or something like that - "Fast Replica Rebuild Enabled"). does it means that having frequent snapshots should reduce the time needed for the replicas to get in-sync again ? and should the option "Immediate Snapshot Data Integrity Check After Creating a Snapshot:" be set to true for this to be happening ? 
3. btw: i could not find this info in the doc: is it necessary to have at least 3 replicas of a volume to reach high-availability of that volume, or is it enough to have just 2 of them, as long as the cluster is in HA mode (3 nodes) -- assuming of course, that replicas spread evenly across the nodes

thanks a lot, i am trying to optimize longhorn setup and i am missing some pieces
