### ISSUE TITLE
[IMPROVEMENT] Support FIPS encryption mode for Longhorn volume

### ISSUE THREAD

**Issue by coreylarew** [longhorn/longhorn#4784]
## Question
I have a requirement to run RHEL 7 in FIPS.  I am trying to encrypt volumes using Longhorn v1.2.4.  Volume mounts fail with the following error:

MountVolume.MountDevice failed for volume "pvc-025b6b62-10fc-473f-a57f-1659015e8c34" : rpc error: code = Internal desc = failed to encrypt device /dev/longhorn/pvc-025b6b62-10fc-473f-a57f-1659015e8c34 with LUKS: failed to run cryptsetup args: [-q luksFormat --type luks2 --hash sha256 /dev/longhorn/pvc-025b6b62-10fc-473f-a57f-1659015e8c34 -d /dev/stdin] output: error: exit status 1

When I try to run the command manually I get the following error:

argon2i key derivation function is not allowed in FIPS mode

Is there a way to not use argon for keys?

**Comment by innobead** [comment]
cc @mantissahz this is probably related to the cypher change capability in 1.4.0.

**Comment by joshimoo** [comment]
REF: this can be done together with https://github.com/longhorn/longhorn/issues/3353

**Comment by innobead** [comment]
Duplicated as https://github.com/longhorn/longhorn/issues/4829, but leave it for testing purposes. 

@mantissahz Even though this was reported by users, could you be able to provide the test steps to let QA verify this issue? or @coreylarew could you provide the steps? Thanks.

**Comment by mantissahz** [comment]
Hi @longhorn/qa,
Here are steps to enable FIPS mode on RHEL7/8

For RHEL7:
1. Install packages
`# yum -y install prelink dracut-fips`
2. Disable prelink:
`# cat /etc/sysconfig/prelink | grep PRELINKING`
`PRELINKING=no`
`# prelink -u -a`
3. Recreate the initramfs file:
`$ dracut -f`
4. Edit `/etc/default/grub` to add `fips=1`
```text
GRUB_CMDLINE_LINUX="fips=1 console=ttyS0,115200n8 console=tty0 net.ifnames=0 rd.blacklist=nouveau nvme_core.io_timeout=4294967295 crashkernel=auto"
```
5. Regenerate grub.cfg:
`# grub2-mkconfig -o /boot/grub2/grub.cfg`
6. reboot

For RHEL8:
`# fips-mode-setup --enable`
`# reboot`

Verify FIPS is enable
```text
# sysctl crypto.fips_enabled
crypto.fips_enabled = 1
```
or
```text
# cat /proc/sys/crypto/fips_enabled
1
```
or
```text
# fips-mode-setup --check
FIPS mode is enabled.
```

Ref: https://www.dogtagpki.org/wiki/Configuring_FIPS_on_RHEL

Then install the `cryptsetup` package
`# yum install -y cryptsetup`

Check default PBKDF:
`# cryptsetup --help|grep "Default PBKDF"`

RHEL7 Result:
```text
Default PBKDF for LUKS1: pbkdf2, iteration time: 2000 (ms)
Default PBKDF for LUKS2: argon2i
```
`argon2i` is not supported for FIPS mode and it caused our volume encryption steps failed.

RHEL8 Result:
```text
Default PBKDF for LUKS1: pbkdf2, iteration time: 2000 (ms)
Default PBKDF for LUKS2: pbkdf2
```

After these steps, you could setup a general Kubernetes cluster with longhorn system on nodes you enable the FIPS mode for.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 15badde) by following [the steps ](https://github.com/longhorn/longhorn/issues/4784#issuecomment-1316196306) to setup FIPS enabled environments, and then executing [the test steps](https://github.com/longhorn/longhorn/issues/4784#issuecomment-1301053355) to verify the encrypted volume works or not.

Tested on both FIPS enabled `RHEL 7.9` and `RHEL 8.6`, the workload using the encrypted volume can read/write the volume without problems.

**Comment by coreylarew** [comment]
can someone please provide an example for FIPS mode.  I am still having a problem getting the volumes to mount

**Comment by innobead** [comment]
cc @mantissahz @yangchiu

**Comment by yangchiu** [comment]
@mantissahz I notice @coreylarew use
`CRYPTO_KEY_CIPHER: "aes-xts-plain64"`
instead of 
`CRYPTO_KEY_CIPHER: "aes-cbc-essiv:sha256"`
provided in [the example](https://github.com/longhorn/longhorn/blob/master/examples/crypto/secret-crypto-customized-rhel-FIPS-enabled.yaml).

Will this affect the result?

**Comment by mantissahz** [comment]
@yangchiu 
I believe that `aes-xts-plain64` could be used in the FIPS environment because I just create a volume with this type in RHEL7 cluster that FIPS mode is enabled

@coreylarew 
Could you describe more about you environment? about LH version, and how did you create the volume and mount the volume?
Any abnormal log in longhorn-manager and maybe what does `kubectl describe po [your workload]` show?
And it would be great if you could provide the support bundle.
