### ISSUE TITLE
[TEST] [v1.2.x] Fix test_allow_volume_creation_with_degraded_availability failure

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#4787]
## What's the test to develop? Please describe

After https://github.com/longhorn/longhorn/issues/4770 was fixed
Test case test_allow_volume_creation_with_degraded_availability always failed.
Longhorn-tests 1.3.x and master-head could test case, we need to fix the 1.2.x-head script.

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [x] Modify script
- [x] Verified on pipeline

## Additional context

[test_allow_volume_creation_with_degraded_availability](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-upgrade-tests-sles-arm64/264/testReport/junit/tests/test_basic/test_allow_volume_creation_with_degraded_availability/)

**Comment by Lichiehyao** [comment]
private image [test result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2243/testReport/tests/test_basic/)

**Comment by Lichiehyao** [comment]
Wait for PR-1162 merge
- https://github.com/longhorn/longhorn-tests/pull/1162

**Comment by roger-ryao** [comment]
PR-1162 was merged, the case is passed in recent Jenkins builds
