### ISSUE TITLE
[IMPROVEMENT] share-manager pod bypasses the kubernetes scheduler

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#4789]
## Is your improvement request related to a feature? Please describe

Since we bypass the scheduler for pod placement of the RWX pods, if the users cluster already has hit the max 110 pod limit, the share-manager pods will fail over and over. More details here:
 
## Describe the solution you'd like

Uncouple share-manager ownership handling from pod placement for the share-manager pod, i.e. let the kubernetes scheduler place the share-manager pod instead. 

## Additional context
- https://cloud-native.slack.com/archives/CNVPEL9U3/p1666797996895439?thread_ts=1666760102.890179&cid=CNVPEL9U3

**Comment by abhishiekgowtham** [comment]
hey @joshimoo, thanks for the opening the GH issue. To which email address should i forward the support bundle to?

**Comment by joshimoo** [comment]
Line where we set the NodeName https://github.com/longhorn/longhorn-manager/blob/master/controller/share_manager_controller.go#L800

Removing that allows the kubernetes scheduler to decide pod placement.

**Comment by joshimoo** [comment]
You can test this in multiple ways:

A simple test is to check `kubectl get sharemanagers -n longhorn-system -o jsonpath="{.items[*].status.ownerID}"` this will print out the ownership of the sharemanager custom resource.

When you deploy an RWX volume to a node, the sharemanager pod will randomly be scheduled and the ownership of the cr will switch to the node of the sharemanager pod. Now if you cordon that node, the ownership should switch to a random node.

-------------------------------------------------------------

Now to test the users case you an make it so that a node is not a candidate for the kubernetes scheduler, for example via (cordon, noSchedule tag, 110 pods, etc) the simplest test is the cordon test, cordon all nodes expect 1. The scheduler will place the pod on that node indepent of who the sharemanager custom resource owner is.

**Comment by chriscchien** [comment]
**Verified in longhorn master `576a42` with [steps](https://cloud-native.slack.com/archives/CNVPEL9U3/p1666797996895439?thread_ts=1666760102.890179&cid=CNVPEL9U3)
Result Pass**

Share manager won't fail over when cluster hit 110 pods, it will restart but still worked properly

![Screenshot from 2022-11-22 09-46-37](https://user-images.githubusercontent.com/73337386/203196897-aa6c02bd-f786-4f58-82b9-5ecc83dee080.png)
