### ISSUE TITLE
[BUG] Unable to reuse existing failed replica causes test case test_allow_volume_creation_with_degraded_availability_restore failed

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#4791]
## Describe the bug

- This issue is about the test case `test_allow_volume_creation_with_degraded_availability_restore` failed on all longhorn branches (`master`, `v1.3.x`, `v1.2.x`)

- longhorn-manager `15f850c` (https://github.com/longhorn/longhorn-manager/commit/15f850c6937a1eedb5667dfc775c1b7037b45b9c) causes this problem, before this commit, the test case would pass, after this commit, the issue presents.

- The test steps of this test case are:

1. Disable scheduling for node 2 and 3.
2. Restore a volume from a backup with 3 replicas => expect only 1 replica scheduled, and 2 replicas failed.
3. Enable scheduling for node 2. => expect 2 replicas2 scheduled, and only 1 replica failed.

- Before commit `15f850c`, once node 2 scheduling enabled, the 2 failed replicas in previous step will be scheduled to node 2, and one of them will be reused and restore data on this replica, and the volume will have 2 scheduled replicas and 1 failed replica, as expected.

- After commit `15f850c`, although node 2 scheduling enabled, the 2 failed replicas in previous step remain unscheduled (N/A), and will not be reused to restore data, the volume has to create a new replica to schedule to node 2, so the volume will have 2 scheduled replicas and 2 failed replicas from the previous step, so assertion failed.

- No matter before or after commit `15f850c`, the failed replica seems will never be automatically deleted even though the `staleReplicaTimeout` is 0, not sure if it's the correct behavior.

## To Reproduce

Run automated test case `test_allow_volume_creation_with_degraded_availability_restore`

## Expected behavior

The failed replica can be reused.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: master, v1.3.x, v1.2.x
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
When this issue happens, unscheduled failed replicas will be left over but the volume will still have the right scheduled replicas and works fine. However, this causes some confusion. 
> After commit 15f850c, although node 2 scheduling enabled, the 2 failed replicas in previous step remain unscheduled (N/A), and will not be reused to restore data, the volume has to create a new replica to schedule to node 2, so the volume will have 2 scheduled replicas and 2 failed replicas from the previous step, so assertion failed.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 5a75273) by executing [the modified test case](https://github.com/longhorn/longhorn-tests/pull/1164). The modified test case can pass and the behavior is the same as the PR described.
