### ISSUE TITLE
[TEST] Flaky test case test_autosalvage_with_data_locality_enabled

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#4814]
## What's the test to develop? Please describe

Related to https://github.com/longhorn/longhorn/issues/4382.

This test case `test_autosalvage_with_data_locality_enabled` could fail on all longhorn branches (`master`, `v1.3.x`, `v1.2.x`) and there are 3 different kind of failed reasons:

**(1) kubernetes.client.rest.ApiException: (0) Reason: Handshake status 500 Internal Server Error:**

It is because the test code tries to execute commands in a `not-running` pod. The test code definitely already has logic to wait the old pod being deleted and tries to get the new pod, but this error still happens. It seems because the pod deleting/creating will occur `more than one time` like the following logs. The old pod `b8d22` will be deleted and the new pod `bbp9c` will be created, but somehow the new pod `bbp9c` will not become running state and will be deleted too, and there will be a third pod `xpdcl` being created and becoming running state, if the test code uses the second pod `bbp9c` to execute commands instead of the third pod `xpdcl`, it will encounter errors for sure.

```
NAME                                           READY   STATUS    RESTARTS   AGE
test-deployment-57f5668b89-b8d22               1/1     Running   0          59s
test-deployment-57f5668b89-b8d22               1/1     Terminating   0          82s
test-deployment-57f5668b89-bbp9c               0/1     Pending       0          0s
test-deployment-57f5668b89-bbp9c               0/1     Pending       0          0s
test-deployment-57f5668b89-bbp9c               0/1     ContainerCreating   0          0s
test-deployment-57f5668b89-b8d22               0/1     Terminating         0          82s
test-deployment-57f5668b89-b8d22               0/1     Terminating         0          83s
test-deployment-57f5668b89-b8d22               0/1     Terminating         0          83s
test-deployment-57f5668b89-bbp9c               0/1     Terminating         0          60s
test-deployment-57f5668b89-xpdcl               0/1     Pending             0          0s
test-deployment-57f5668b89-xpdcl               0/1     Pending             0          0s
test-deployment-57f5668b89-xpdcl               0/1     ContainerCreating   0          0s
test-deployment-57f5668b89-xpdcl               1/1     Running             0          6s
test-deployment-57f5668b89-bbp9c               1/1     Terminating         0          66s
test-deployment-57f5668b89-bbp9c               0/1     Terminating         0          67s
test-deployment-57f5668b89-bbp9c               0/1     Terminating         0          67s
test-deployment-57f5668b89-bbp9c               0/1     Terminating         0          67s
```

This kind of error happens on all longhorn branches (`master`, `v1.3.x`, `v1.2.x`) since it is due to the problematic test code implementation.

_For this problem, we need a way to really ensure the deployment pod is really ready before operating._

**(2) AssertionError: assert 'g14pwwmlwrvt...50dyh92vef1jg' == '':**

This is because `data loss` in the newly created pod. This can be reproduced by [manually executing the test case](https://github.com/longhorn/longhorn/issues/4382#issuecomment-1283655312). In step (10), although the file still exists, the file size becomes 0 and cat this file outputs nothing like the following log: 

In the old pod:
```
kubectl exec -it test-deployment-57f5668b89-cclzh -- /bin/sh
/ # cd data
/data # ls
lost+found
/data # echo ok > ok
/data # cat ok
ok
/data # ls -al
total 28
drwxr-xr-x    3 root     root          4096 Oct 31 03:51 .
drwxr-xr-x    1 root     root          4096 Oct 31 03:51 ..
drwx------    2 root     root         16384 Oct 31 03:51 lost+found
-rw-r--r--    1 root     root             3 Oct 31 03:51 ok
```

In the newly created pod:
```
kubectl exec -it test-deployment-57f5668b89-lr4gf -- /bin/sh
/ # cd data
/data # ls
lost+found  ok
/data # cat ok
/data # ls -al
total 24
drwxr-xr-x    3 root     root          4096 Oct 31 03:51 .
drwxr-xr-x    1 root     root          4096 Oct 31 03:53 ..
drwx------    2 root     root         16384 Oct 31 03:51 lost+found
-rw-r--r--    1 root     root             0 Oct 31 03:51 ok
```

This kind of error happens on all longhorn branches (`master`, `v1.3.x`, `v1.2.x`) too, and already exists for a long time, we didn't catch this before because this error is shielded by **(1)**, since **(1)** will happen first and fail the test case, so the chance we see this error would be reduced.

reference: [master](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/240/testReport/junit/tests/test_ha/test_autosalvage_with_data_locality_enabled/), [v1.3.x](https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-upgrade-tests-sles-arm64/128/testReport/tests/test_ha/test_autosalvage_with_data_locality_enabled/), [v1.2.x](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-arm64/265/testReport/junit/tests/test_ha/test_autosalvage_with_data_locality_enabled/)

_For this problem, we've confirmed it is caused by write fs buffer was not flushed to the disk. In the same [test scenario](https://github.com/longhorn/longhorn/issues/4382#issuecomment-1296604705), if I execute `sync` after `echo` data to the file, this issue will not present anymore. In our automated test case, it does almost the same thing by generating 512 Bytes random text and `echo` the generated data to the file, so it could suffer from the flush issue too. Probably write large size test data can trigger the flush process and avoid this issue._

**(3) AssertionError: assert 'qpmr8ujdg6jt...ik5c1i8az7vb8' == 'cat: read error: I/O error\n':**

Just like @chriscchien described in the [comment](https://github.com/longhorn/longhorn/issues/4382#issuecomment-1283655312).

_This problem seems a product issue and will not be visited in this ticket._

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `add mechanism to wait for a stable running pod when deployment restarts its workload`
- [ ] `use dd to write large size test data`

**Comment by innobead** [comment]
This is also something we need to investigate in longhorn-manager, why the pod is deleted couple times. 

>  The test code definitely already has logic to wait the old pod being deleted and tries to get the new pod, but this error still happens. It seems because the pod deleting/creating will occur more than one time like the following logs.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager a9d6289) and v1.5.x-head (longhorn-manager 60b5368). Running test case test_autosalvage_with_data_locality_enabled for more than **20** times, no failure occurred.
