### ISSUE TITLE
[QUESTION] should i change kubeletRootDir value?

### ISSUE THREAD

**Issue by kikyoulg** [longhorn/longhorn#4821]
## Qu
> Suggest to use https://github.com/longhorn/longhorn/discussions to ask questions.

## Environment

 - Longhorn version: v1.3.0
 - Kubernetes version: 1.20.2
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

## Additional context

Add any other context about the pr
oblem here.

my data  dir is /data/kubelet ，should i change this config?if master data dir  diffent with node ,how should i config this?

**Comment by PhanLe1010** [comment]
Not 100% understand you question. Do you mean that you created a cluster with customized kubelet root directory (like doing this https://www.suse.com/support/kb/doc/?id=000020058) and now you want to install Longhorn? If it is the case then you will need to set this setting in Longhorn https://github.com/longhorn/longhorn/blob/a425df9a8bfc209f48180a3792790d4917ed06d6/chart/values.yaml#L90

**Comment by joshimoo** [comment]
Just leaving a code reference for the detection of the kubelet root dir below. This is old and hasn't been touched in a while. 
https://github.com/longhorn/longhorn-manager/blob/24d07f134011e8ef2ad01d2d69427a59c43ed87c/app/get_proc_arg.go#L73
