### ISSUE TITLE
[FEATURE] Replace UI deprecated and outdated framework

### ISSUE THREAD

**Issue by smallteeths** [longhorn/longhorn#4824]
### Problems to be solved

1. longhorn-ui adopted dva framework. This Dva framework is no longer maintained in January 2020. The npm dependencies are relatively old. If the `react` dependencies cannot be upgraded, It will cause `antd` ui components not to be upgraded. And it may lead to more CVE vulnerabilities. 
2. The original code logic is a bit confusing, with a lot of redundant code.
3. The volume page lacks performance optimization. Large volumes may cause page lag.
4. Mobile area/ui support required.

### Refactoring steps

1. Remove dva framework.
2. User Create-React-App cli.
3. Upgrade react/react-router/react-redux/redux-saga
4. Simplify css by introducing the tailwind.css style package.
5. Upgrade Antd to version v4.x.x.
6. Use react hook to simplify the state parameters.
7. Support mobile browser.

**Comment by PhanLe1010** [comment]
Looks like a major UI update 🚀

**Comment by innobead** [comment]
@smallteeths is this feasible in 1.5?

**Comment by smallteeths** [comment]
> @smallteeths is this feasible in 1.5?

I will try my best to complete this issue before the release of version 1.5, but I cannot confirm the exact completion time.
