### ISSUE TITLE
[FEATURE] Change the replica selector behavior so that an absent selector is able to select nodes without a TAG

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4826]
### Discussed in https://github.com/longhorn/longhorn/discussions/4806

<div type='discussions-op-text'>

<sup>Originally posted by **lictw** November  1, 2022</sup>
Hi!

I added new hdd disk and set hdd label on it and now i want that only replicas of volumes with tag hdd can be scheduled on this disk, how can i achieve this without "default" tag on all others disks? Can disk selector of default SC locates to empty tag? Or some setting "dont create replicas without tags on tagged disks"? Btw strange behavior by default, it was unexpected..</div>

**Comment by joshimoo** [comment]
This also requires addition of a wildcard selector, it might just be good enough to use a soft mode for the empty selector in which the possible candidates are ordered by tags first :)

For the implementation we might need to keep both for the moment and have a feature flag to enable the new behavior for the first release then shortly after remove the old implementation.

**Comment by joshimoo** [comment]
From a user perspective the reason this is useful, assume that the cluster has 3 nodes with expensive storage and the other nodes are cheap storage. The user would want to prioritize specific workloads to be stored on the expensive storage via the storage class selector(think databases) and wouldn't want the regular default longhorn class to also store replicas on the expensive storage.

Currently the empty selector would lead to the expensive storage (tagged) also being a candidate for a replica that doesn't have a selector specified.

**Comment by joshimoo** [comment]
Estimate: very little uncertainty, implementation effort small/medium due to the replica scheduler enhancement and the backwards compatibility via the flag.

**Comment by ChanYiLin** [comment]
Hi @PhanLe1010 
For this issue, I plan to do following modification
- Add a new setting "TolerateEmptyTagReplica"
    - True(default): replica without tag can be scheduled on tagged node/disk
    - False: replica without tag can not be scheduled on tagged node/disk
- update the function [IsSelectorsInTags()](https://github.com/longhorn/longhorn-manager/blob/master/types/types.go#L998)
    - if `TolerateEmptyTagReplica` is false, then we return false if the "tags" of node/disk is  not empty but replica has no tag

WDYT?

**Comment by roger-ryao** [comment]
**Verified on master-head 20230904**

- longhorn master-head https://github.com/longhorn/longhorn/commit/67b4b38a1222d441f528907dcfbc89c4a6ce08d5
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/421da081cf870659e390dd6e08a5abad1f392af0


**The test steps**
https://github.com/longhorn/longhorn/issues/4826#issuecomment-1633577799

**Result Passed**

- [x] All 4 test cases scenarios passed successfully.
- [x] require/auto-e2e-test : Reviewed the test case skeleton in https://github.com/longhorn/longhorn-tests/pull/1519
- [x] require/chart :  Installed Longhorn using Helm chart and modified `allowEmptyNodeSelectorVolume` to `false` and `allowEmptyDiskSelectorVolume` to `false`, and it took effect.
- [x] require/doc : Checked documentation in https://github.com/longhorn/website/pull/770

**Comment by innobead** [comment]
@roger-ryao very good to have a checklist to ensure all items are ready before closing the issue.

cc @longhorn/qa
