### ISSUE TITLE
[BUG] Volume has 2 active engines at the same time that blocks the volume controller reconciliation loop 

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4827]
## Describe the bug

Volume has 2 active engines at the same time that block the volume controller reconciliation loop. The volume stuck in attached state even though `volume.Spec.NodeID` and `volume.Spec.MigrationNodeID` are empty

## Expected behavior

This buggy state should not happen. And even if this happens, the volume controller should be able to continue to reconcile the state

## Log or Support bundle

ref https://rancher-users.slack.com/archives/CC2UQM49Y/p1667518894172219?thread_ts=1667139859.252799&cid=CC2UQM49Y

**Comment by PhanLe1010** [comment]
cc @shuo-wu

**Comment by shuo-wu** [comment]
The similar issue ticket: https://github.com/longhorn/longhorn/issues/1755

**Comment by innobead** [comment]
cc @mantissahz

**Comment by oivindoh** [comment]
Hit this today and ended up deleting the extra engine as per slack thread mentioned in attached bundle metadata. This allowed me to recover the volume. Patching the bad engine's spec.active = false did not have a constructive effect.

[longhorn-support-bundle_6325ca27-ad51-4cf4-a84f-476d588f0c0c_2023-04-20T11-59-41Z.zip](https://github.com/longhorn/longhorn/files/11289249/longhorn-support-bundle_6325ca27-ad51-4cf4-a84f-476d588f0c0c_2023-04-20T11-59-41Z.zip)

**Comment by PhanLe1010** [comment]
Update: This PR has addressed this issue https://github.com/longhorn/longhorn-manager/pull/2180. 

Moving this one to ready-for-testing @longhorn/qa Can you help to re-test? 


Test plan could be https://github.com/longhorn/longhorn/issues/6131#issuecomment-1848082556

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `27101b`) with test [steps](https://github.com/longhorn/longhorn/issues/4827#issuecomment-1848082657)

- For [6131](https://github.com/longhorn/longhorn/issues/6131#issuecomment-1848082556), ref @yangchiu 's test [result](https://github.com/longhorn/longhorn/issues/6131#issuecomment-1853224444)
- For [6682](https://github.com/longhorn/longhorn/issues/6682#issuecomment-1736315211) tested below item on master head without any problem
   -  Case 2: Test the script with Longhorn master
   -  Case 3: Manually create duplicated engines
   -  Case 4: Manual migration and Upgrade test
