### ISSUE TITLE
[TEST] recurring job test cases fail on k8s v1.25

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#4830]
## What's the test to develop? Please describe

Like https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/299/testReport/, lots of recurring job test cases failed due to: 

`kubernetes.client.rest.ApiException: (404) Reason: Not Found HTTP response headers: HTTPHeaderDict({'Audit-Id': '3567f972-f64a-4fc1-927d-b879cebcde66', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'e1b58ac2-2f49-4876-9ddc-edcea59c5d5b', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'fca65759-317e-4244-8cbb-07a5fe616f2e', 'Date': 'Wed, 02 Nov 2022 21:30:01 GMT', 'Content-Length': '174'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}`

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

Add any other context or screenshots about the test request here.

**Comment by c3y1huang** [comment]
Relate to https://github.com/longhorn/longhorn-manager/commit/9ceb699f363a9f29ff2ef0aad6087ba97c87e7c5
