### ISSUE TITLE
[BUG] Unable to update to version 1.3.2 on a v1.24.2 k3s cluster

### ISSUE THREAD

**Issue by massimovec** [longhorn/longhorn#4837]
## Describe the bug
Unable to update to longhorn 1.3.2 on a v1.24.2+k3s2 cluster via Rancher Legacy Project App

![image](https://user-images.githubusercontent.com/94403892/200118272-7725e202-e221-487e-b1d5-abb0ea337583.png)

![image](https://user-images.githubusercontent.com/94403892/200118137-8f9a91bb-2145-4628-a060-0bd6ef2ae713.png)

## To Reproduce

1. Go to Legacy -> Project -> Apps
2. Click on Upgrade
3. Perform the upgrade to app version 1.3.2

## Expected behavior

Update to version 1.3.2 without error, it is not a 1.25 k8s cluster

## Environment

 - Longhorn version: 1.3.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.24.2+k3s2
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 7
 - Node config
   - OS type and version: Debian 10 
   - CPU per node: 4
   - Memory per node: 8 GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 1 Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster:

**Comment by shuo-wu** [comment]
Notice that you are using the lagacy APP page, you may need to take a look at this first: https://longhorn.io/kb/how-to-migrate-longhorn-chart-installed-in-old-rancher-ui-to-the-chart-in-new-rancher-ui/

**Comment by shuo-wu** [comment]
Close this for now. If you have any issue with the solution mentioned in the doc, feel free to reopen this.
