### ISSUE TITLE
[BUG] Backing image is stuck at `in-progress` status if the provided checksum is incorrect

### ISSUE THREAD

**Issue by bk201** [longhorn/longhorn#4852]
## Describe the bug (🐛 if you encounter this issue)

- Create a backing image with an incorrect checksum value.
- The backing image is stuck at 100% progress and `in-progress` state.

## To Reproduce

1. Go to the backing image page
2. Create a backing image from an URL and specify an incorrect checksum, for example:
    <img width="1016" alt="Screen Shot 2022-11-08 at 11 05 01 PM" src="https://user-images.githubusercontent.com/1691518/200601694-3328e777-e884-4cf2-818b-7f364c46afc6.png">
3. The backing image is stuck with `in-progress` status and 100%.
    <img width="770" alt="Screen Shot 2022-11-08 at 11 04 20 PM" src="https://user-images.githubusercontent.com/1691518/200601903-e66d82e3-a085-44ca-8554-f659623ed60d.png">

## Expected behavior

The status should be `failed`. For example:
<img width="755" alt="Screen Shot 2022-11-08 at 11 13 29 PM" src="https://user-images.githubusercontent.com/1691518/200602339-c2282db9-4dfb-4fb9-a410-dda0ed2b7c15.png">

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.3.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): HelmChart
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

This is spotted when testing the Harvester v1.1.0 upgrade. We can reproduce this with a fresh installation (Longhorn v1.3.2).
**NOTE**: we can't reproduce this in Longhorn v1.2.4.

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by FrankYang0529** [comment]
Although we check checksum in [backing-image-manager](https://github.com/longhorn/backing-image-manager/blob/0435b5f5853e8c33c8830ec26690f1a2d9a167a0/pkg/sync/sync_file.go#L655-L658), it looks like we [can't return that error](https://github.com/longhorn/backing-image-manager/blob/0435b5f5853e8c33c8830ec26690f1a2d9a167a0/pkg/sync/sync_file.go#L461-L486). I simplified the process and do a test on the playground and I can't get an error in the main function.

https://go.dev/play/p/LamaAu6jwWF?v=goprev

```go
package main

import "fmt"

func main() {
	if err := mockDownloadFromURL(); err != nil {
		fmt.Println("Get error")
	}
}

func mockDownloadFromURL() (err error) {
	ignoredVal, err := mockStateCheckBeforeProcessing()
	fmt.Println(ignoredVal) // just for no gofmt error
	mockFinishProcessing(err)
	fmt.Println(err)
	return
}

func mockStateCheckBeforeProcessing() (bool, error) {
	return false, nil
}

func mockFinishProcessing(err error) {
	err = fmt.Errorf("test")
	return
}
```

**Comment by shuo-wu** [comment]
Got it. The error input into a function cannot be updated by that function itself:
https://go.dev/play/p/wm28xw-CvmU?v=goprev

Here, [the function `finishProcessing`](https://github.com/longhorn/backing-image-manager/blob/0435b5f5853e8c33c8830ec26690f1a2d9a167a0/pkg/sync/sync_file.go#L537) should return an updated error since it cannot directly update the existing error.

**Comment by innobead** [comment]
cc @longhorn/qa added `reproduce` and `severity` labels which are required for any bug.

**Comment by chriscchien** [comment]
Verified in longhorn master `aa3998`
Result **Pass**

1. Download backing image from URL with wrong md5sum will end at failed status
![Screenshot from 2022-12-15 11-03-17](https://user-images.githubusercontent.com/73337386/207763559-11aaab46-fe50-4441-af3c-a03ccde4262b.png)

3. Upload backing image from local with wrong md5sum will end at failed status
![Screenshot from 2022-12-15 11-03-23](https://user-images.githubusercontent.com/73337386/207763579-f357868d-c218-481e-abb3-c1f65e54c961.png)

5. Create backing image with no expect md5sum will success
6. Create backing image with correct md5sum will success
