### ISSUE TITLE
[IMPROVEMENT] Support ARM64 benchmark test 

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#4854]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Our e2e pipeline can do benchmark test automatically in AMD64 instance but not in ARM64

## Describe the solution you'd like

If benchmark pipeline can support ARM64 that will be great

cc @yangchiu 

## Describe alternatives you've considered

N/A

## Additional context

Current in pipline if we choose instance type to ARM64 and

K8S_DISTRO_NAME = `rke`, will error at 
```
220 loader.go:223] Config not found: /src/longhorn-tests/benchmark_test/terraform/aws/sles/k3s.yaml
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

K8S_DISTRO_NAME = `k3s`, will error at 
```
Error: wait for kbench running timeout
```

**Comment by innobead** [comment]
@chriscchien This belongs to test task, so next time u can create a test task instead of improvement.

**Comment by yangchiu** [comment]
kbench arm64 image pushed on dockerhub: https://hub.docker.com/r/yangchiu/kbench/tags.

**Comment by yangchiu** [comment]
After 
`(1) fix aws permission issue `
`(2) push kbench arm64 image`
benchmark test can be run on arm64 instances now: https://ci.longhorn.io/job/private/job/longhorn-benchmark-test/39/,
but have to use k3s, since rke2 doesn't support arm64.
