### ISSUE TITLE
[FEATURE] no way to control share-manager pod placement (node tags, etc)

### ISSUE THREAD

**Issue by jaysonsantos** [longhorn/longhorn#4863]
## To Reproduce

1. Tag a few nodes with `local` tag
2. Create a RWX (RWO works fine) using the `local` node tag
3. Create a deployment that uses a pvc with that node
4. share-manager's pod will be created in a random node, not respecting the tag

## Expected behavior

I would assume that share-manager would only be scheduled on nodes that match those tags, maybe some config on the pvc would be possible?
## Environment

 - Longhorn version: 1.3.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.24.7+k3s1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 8
 - Node config
   - OS type and version: ubuntu 22.04
   - CPU per node: 6-16
   - Memory per node: 2-24GB
   - Disk type(e.g. SSD/NVMe): HDD and NVME
   - Network bandwidth between the nodes: 1Gb
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 20

**Comment by netwarex** [comment]
Yes please, this is important as even no data locality respected by the share-manager pod.

**Comment by tcoupin** [comment]
It would be nice to have a parameter such as defaultDataLocality to keep the share manager pod close to one of the replicas.
At least, a share manage pod should not be schedule on node without disk.

**Comment by netwarex** [comment]
For a quick solution, it would be nice, to at least make it possible to specify the nodeAffinity so only run share manager on nodes where defined.

A more sophisticated way is enough later.

**Comment by 93imagine** [comment]
I assumed the data locality option would take care of this but it does not.

**Comment by Danielss89** [comment]
Would love to see this implemented too. I currently have a cluster with nodes in different regions like Tokyo, USA, Europe and even though i can put my application pods and storage on the correct nodes, the share manager will run on wherever there is room.
This gives an error because of latency, and as such, if i'm unlucky and my pods in europe gets a share-manager in Tokyo, it will fail to mount the volume.

**Comment by derekbit** [comment]
@innobead 
I think it is worth being added in v1.7.0 if we have enough time.

**Comment by innobead** [comment]
@james-munson Please take care of the following when you start working on that. 

https://github.com/longhorn/longhorn/discussions/8255#discussioncomment-8912469

**Comment by james-munson** [comment]
It appears this will be covered by #7872.

**Comment by derekbit** [comment]
Implemented in https://github.com/longhorn/longhorn/issues/7872.
