### ISSUE TITLE
[IMPROVEMENT] Snapshot APIs rely on snapshot CRs rather than engine.status.snapshots

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4868]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Currently, the [snapshot APIs](https://github.com/longhorn/longhorn-manager/blob/master/api/router.go#L83) rely on `engine.status.snapshots` rather than `snapshot` CRs. To make the APIs consistent with other APIs and to reflect any new fields introduced in `snapshot` CRs, the APIs can operate the `snapshot` CRs directly.

**Comment by innobead** [comment]
@PhanLe1010 I noticed you have some tickets w/o the correct pipeline status, so please help update and move to ready-for-testing soon and QA can help with the testing. Thanks.

**Comment by PhanLe1010** [comment]
This ticket looks like a duplication of https://github.com/longhorn/longhorn/issues/3995. Suggesting to close this one. 

cc @innobead

**Comment by PhanLe1010** [comment]
Closing as discussed with @innobead
