### ISSUE TITLE
namespaces "longhorn-system" not found: undefined

### ISSUE THREAD

**Issue by ViceIce** [longhorn/longhorn#487]
Tried to deploy longhorn to a kubernetes custom v1.13.5 cluster (2 nodes) with rancher v2.2.2

`namespaces "longhorn-system" not found: undefined`

If i manually add the namespace `longhorn-system` it will deploy to that. It looks like it ignores the namespace setting.

I tried longhorn template version 0.4.0 and 0.4.1

**Comment by yasker** [comment]
It's a Rancher issue, we are tracking it at https://github.com/rancher/rancher/issues/19697

**Comment by yasker** [comment]
The issue can be workaround by manually set namespace to `longhorn-system` instead of `longhorn` or `longhorn-xxx`.

It will be fixed in the next Rancher release.

**Comment by gabrielcalderon** [comment]
@yasker I just ran into this same issue and changing the namespace to "longhorn-system" solved it. This doesn't happen if longhorn is created as a multi-cluster app.

**Comment by yasker** [comment]
@meldafrawi Can you check if this one impacts the multi-cluster app as well?

**Comment by meldafrawi** [comment]
I've tried to deploy longhorn as a multi-cluster app using rancher server v2.2.2
a new namespace is being created with a name longhorn-**prefix**,
all pods have been created successfully in that namespace.

**Comment by yasker** [comment]
@meldafrawi Seems we have an issue here since we need the multicluster app stick to our predefined `longhorn-system` namespace.

**Comment by yasker** [comment]
Fixed in Rancher 2.2.4

**Comment by meldafrawi** [comment]
**Rancher Version:** v2.2.4
**Longhorn Version:** v0.5.0

- `longhorn-system` namespace is created.
- Longhorn components get deployed to `longhorn-system` namespace successfully.

**Comment by shuo-wu** [comment]
Rancher Version: v2.2.7
Longhorn Version: v0.5.0

Now Longhorn cannot be installed correctly since it is not deployed in the predefined `longhorn-system` namespace. 

Rancher will add a random suffix for the project name then use that string as project namespace. There is no way to specify the namespace to predefined namespace `longhorn-system` for Longhorn system deployment.

**Comment by yasker** [comment]
@shuo-wu Is this about multi-cluster app or single cluster app?

**Comment by shuo-wu** [comment]
It happens in multi-cluster app deployment.

**Comment by yasker** [comment]
@shuo-wu Multi-cluster app is tracked in https://github.com/longhorn/longhorn/issues/633 .  This issue is about the single cluster app.
