### ISSUE TITLE
[REFACTORING] Move adding finalizer of resources to mutation webhooks as volume/engine/replica 

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4872]
## Is your improvement request related to a feature? Please describe

As https://github.com/longhorn/longhorn-manager/pull/1535, need to do it for other resources. This refactoring is only for finalizer addition, but keep removing finalizer as is.
![image](https://user-images.githubusercontent.com/899492/201598290-516271a9-f34d-4bf9-aacc-0339ec82a9eb.png)

## Additional context

Add any other context or screenshots about the refactoring request here.

**Comment by PhanLe1010** [comment]
For test plan, I have a small note https://github.com/longhorn/longhorn-manager/pull/2080#pullrequestreview-1541860512

**Comment by ejweber** [comment]
> For test plan, I have a small note [longhorn/longhorn-manager#2080 (review)](https://github.com/longhorn/longhorn-manager/pull/2080#pullrequestreview-1541860512)

Added this to the form as well.

**Comment by chriscchien** [comment]
Hi @ejweber, I followed test steps [here](https://github.com/longhorn/longhorn-manager/pull/2080#issuecomment-1636190352) to verify resource finalizer can not be deleted, below CR have finalizer `longhorn.io` and the finalizer can not removal while not deleting CR
- [x] `backingimage`
- [x] `backingimagedatasource`
- [x] `backingimagemanager`
- [x] `backup`
- [x] `backupvolume`
- [x] `engine`
- [x] `engineimage`
- [x] `node`
- [x] `replica`
- [x] `sharemanager`
- [x] `snapshot`
- [x] `systembackup`
- [x] `volume`

But `volumeattachment` have a different finalizer `external-attacher/driver-longhorn-io`, and this finalizer can directly remove by edit correspond CR.

Here is my environment
- longhorn master `23e2f2` install by kubectl
- v1.27.3+k3s1
- Ubuntu 22.04

[supportbundle_8990871e-050e-4cab-bfc3-4b4f11c50e8b_2023-08-14T07-14-41Z.zip](https://github.com/longhorn/longhorn/files/12332300/supportbundle_8990871e-050e-4cab-bfc3-4b4f11c50e8b_2023-08-14T07-14-41Z.zip)

**Comment by chriscchien** [comment]
In addition, when all CRs mentioned in the [steps](https://github.com/longhorn/longhorn-manager/pull/2080#issuecomment-1636190352) exist, Longhorn uninstallation will be successful, and the 'longhorn-system' namespace will terminate successfully.

**Comment by ejweber** [comment]
Sorry @chriscchien, missed this. I will evaluate ASAP.

**Comment by ejweber** [comment]
> But volumeattachment have a different finalizer external-attacher/driver-longhorn-io, and this finalizer can directly remove by edit correspond CR.

Sorry for the confusion @chriscchien. I have updated the test steps to be more specific.

All Kubernetes clusters have volumeattachment.storage.k8s.io resources. Executing `kubectl get volumeattachment` gets those type of resources.

The volume attachments I am referring to in my test steps are volumeattachment.longhorn.io resources. These can be evaluated with `kubectl get volumeattachment.longhorn.io` or `kubectl get lhva`. We expect volumeattachment.longhorn.io resources to have the `longhorn.io` finalizer, but not volumeattachment.storage.k8s.io resources.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `560a41`) with test [steps](https://github.com/longhorn/longhorn-manager/pull/2080#issuecomment-1636190352)

1. All CRs mention in test step have finalizer `longhorn.io` and the finalizer can not removal while not deleting CR
2. Longhorn uninstallation will be successful when all CRs mentioned in test step exist in cluster, the 'longhorn-system' namespace will terminate successfully.
