### ISSUE TITLE
[TEST] Have automation test case of backing image with invalid checksum

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#4879]
## What's the test to develop? Please describe

From https://github.com/longhorn/longhorn/issues/4852, we can have an e2e case to cover this scenario

## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] Implement script
- [ ] Verify on pipeline

## Additional context

Add any other context or screenshots about the test request here.

cc @khushboo-rancher

**Comment by innobead** [comment]
@chriscchien you don't need to create a test issue on your own if the source issue has `require/e2e-automation`, because the corresponding test issue will be created automatically. https://github.com/longhorn/longhorn/issues/4878

cc @longhorn/qa
