### ISSUE TITLE
[FEATURE] Support Encryption for VolumeMode Block

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#4883]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Currently we only support encryption for volume mode FS, we should also allow for encryption in block mode.
This is useful for harvester where we need to consider the impact on live migration.

## Describe the solution you'd like

Similiar to the FS encryption we can shadow the raw block dev and provide the encrypted block dev instead as part of the csi plugin.

## Additional context
- https://github.com/harvester/harvester/issues/3129

**Comment by innobead** [comment]
After discussing with @joshimoo , he needs more time on testing to ensure it works w/o any side effects, so moving this to 1.5.0 instead. 

cc @longhorn/qa

**Comment by innobead** [comment]
This issue will influence how online expansion support will be supported for encrypted volume. 

cc @shuo-wu

**Comment by shuo-wu** [comment]
> This issue will influence how online expansion support will be supported for encrypted volume.
> 
> cc @shuo-wu

Currently, there is no side effect. Due to the upstream issue, Longhorn CSI cannot support the encryption volume expansion. In the future, once the upstream feature is ready, we still need to do resizing for the encrypted device, which is a kind of regular handling.

**Comment by roger-ryao** [comment]
**Verified on master-head 20231124**

- longhorn master-head https://github.com/longhorn/longhorn/commit/57bf3edb1faa955ab077187a518d7be99ff38792
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/dd663887de73664ffc3296465a0a4b9d2ccbdfb6

**Result Passed**

- [x] require/auto-e2e-test
 - https://github.com/longhorn/longhorn/issues/5020
   - https://github.com/longhorn/longhorn-tests/pull/1443

- [ ] require/doc - https://github.com/longhorn/website/pull/775
 - @derekbit [Please check the review comment from](https://github.com/longhorn/website/pull/775#issuecomment-1785056403) @jillian-maroket.

- [x] ~require/manual-test-plan~ - https://github.com/longhorn/longhorn/issues/4883#issuecomment-1619514908
  - We have the PR https://github.com/longhorn/longhorn-tests/pull/1443 so we don't need to add manual-test-plan
