### ISSUE TITLE
[BUG] The node ID of backing image data source somehow get changed then lead to file handling failed

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4887]
## Describe the bug (🐛 if you encounter this issue)

As mentioned in the title, the node ID change of the backing image data source will lead to a mismatching with its running pod then fail the file downloading/uploading/exporting.

After checking the code, I found that the backing image controller may [wrongly update/modify the node ID](https://github.com/longhorn/longhorn-manager/blob/732f3c8392ca2f8a394ba001015153a649a31691/controller/backing_image_controller.go#L511-L537) when the file uploading/downloading is still in progress. 

Most of the time the first entry of [the iteration](https://github.com/longhorn/longhorn-manager/blob/732f3c8392ca2f8a394ba001015153a649a31691/controller/backing_image_controller.go#L513-L519) won't change hence the issue won't be triggered, but indeed it’s a bug.

## To Reproduce

Not sure how to reproduce it for now.

Maybe we can try to add some nodes during a large backing image file downloading/upload.

## Expected behavior

The node ID of the backing image data source shouldn't change during the file handling.

## Log or Support bundle

```
2022-11-07T21:03:30.772022890Z time="2022-11-07T21:03:30Z" level=error msg="Backing Image Data Source was state in-progress but the pod became not ready, the state will be updated to failed, message: pod spec node ID vsh01ha doesn't match the desired node ID vsh01hc" backingImageDataSource=default-image-zxgnk controller=longhorn-backing-image-data-source diskUUID=588588f4-1bec-41c8-9fde-936d5a7bf492 node=vsh01hc nodeID=vsh01hc parameters="map[url:http://10.89.4.53/wsp.raw]" sourceType=download
```

## Environment

 - Longhorn version: v1.3.2

## Additional context
This is reported by Harvester. @ibrokethecloud

**Comment by innobead** [comment]
@shuo-wu is the workaround to delete the data source pod to restart a new pod?

**Comment by shuo-wu** [comment]
Typically retrying the backing image creation should be enough.

**Comment by chriscchien** [comment]
Verified in longhorn master `207e74` with test [steps](https://github.com/longhorn/longhorn-tests/pull/1199/files?short_path=79792be#diff-79792be5fd189229b57fa9b01ca2940d03277bc80f7ad5ce5a63d53f4c4a0999)
Result **Pass**

1. Create backing images by upload 500m file into longhorn, while upload was in progress, sequentially added 2 nodes into cluster, the backing image uploaded and created successfully. In longhorn manager log did not find error log related to `doesn't match the desired node ID`. This step repeated 3 times.
2. Run `test_backing_image_basic_operation` in master head for 20 times, test case all [passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2637/), did not see backing image create failure error

**Comment by chriscchien** [comment]
Hi @shuo-wu,

I’m trying to implement an E2E test case related to this ticket(https://longhorn.github.io/longhorn-tests/manual/release-specific/v1.4.0/test-node-id-change-during-backing-image-creation/) , but I’m having issues creating a backing image with `sourceType` = `upload` from the test script directly. I’d like to confirm whether this ticket can also be tested by _download_ backing image, even though it was mentioned previously [here](https://github.com/longhorn/longhorn/issues/4887#issue-1450784267). Could you please clarify when you have time? Thank you!
