### ISSUE TITLE
[IMPROVEMENT] Recurring jobs create new snapshots while being not able to clean up old ones

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4898]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

During rebuilding, the recurring jobs cannot clean up old snapshots but will continue blindly creating new snapshots. Then the snapshot count may exceed the retain count even the max limit.

## Describe the solution you'd like

- Have a notification mechanism like events to inform the users when this case happens.
- check or directly clean up the old snapshot first.
- Have a new option that allows Longhorn to create new snapshots even if the cleanup is impossible

**Comment by innobead** [comment]
Why not just do the snapshot cleanup first, and if it is successful, then create a new snapshot? I don't think a new option would be helpful but probably it would cause some confusion. WDYT?  @shuo-wu @mantissahz @derekbit

**Comment by mantissahz** [comment]
> Why not just do the snapshot cleanup first as mentioned in item 2 above and then create a new snapshot only if it is successful?

@PhanLe1010 we might move the cleanup part of recurring job in AD controller here.

> Would the new setting be helpful? or it would probably cause some confusion.

The new setting would be helpful. In my opinion, some users would still want to create the snapshot whether the replica is rebuilding or not because the data might be important for users. WDYT? @shuo-wu @derekbit

**Comment by innobead** [comment]
If the snapshot is important because users set the recurring job, then we should just do it but ensure cleaning outdated snapshots beforehand, so no need to have an extra setting? WDYT?

**Comment by derekbit** [comment]
> If the snapshot is important because users set the recurring job, then we should just do it but ensure cleaning outdated snapshots beforehand

One scenairo is that the replica is being rebuilt and is taking for a long time. If the number of snapshots exceeds the number of retains, the deletion will be hindered. 

Some thoughts
1. A snapshot cannot be taken. It may, however, have a negative impact on mission-critical services that require periodic snapshots.
2. A snapshot cannot be taken without the new setting. The retain count is not respected, so the transient space consumption might be out of control.
3. Introduce the new setting. The user will be able to determine which option is acceptable, either 1 or 2.

**Comment by innobead** [comment]
> One scenairo is that the replica is being rebuilt and is taking for a long time. If the number of snapshots exceeds the number of retains, the deletion will be hindered.

How about `check or directly clean up the old snapshot first.` ? so the deletion will not be impacted by the long-running snapshot creation because it will be taken first.

**Comment by mantissahz** [comment]
I guess my naming for this setting misled the functionality, this setting is used to reject creating a snapshot when old snapshots can not be deleted by default.

> How about check or directly clean up the old snapshot first.

It still would be rejected by a rebuilding replica [Task.DeleteSnapshot](https://github.com/longhorn/longhorn-engine/blob/master/pkg/sync/sync.go#L132-L138) (for some reason it starts to rebuild a replica)

**Comment by innobead** [comment]
@mantissahz Do u mean the following? 
- creating snapshots is allowed no matter weather there is replica rebuilding
- deleting snapshots is disallowed while there is no replica rebuilding

**Comment by c3y1huang** [comment]
If we are introducing force snapshot creation, why not consider a new recurring job type(`snapshot-force`) instead of a global setting?

**Comment by derekbit** [comment]
> If we are introducing force snapshot creation, why not consider a new recurring job type(`snapshot-force`) instead of a global setting?

Or, can we add `recurringjob.spec.forceSnapshot` rather than a global setting?

**Comment by mantissahz** [comment]
> creating snapshots is allowed no matter weather there is replica rebuilding

@innobead Yes if the setting is set to allow creating a new snapshot

> deleting snapshots is disallowed while there is no replica rebuilding

No, the setting would not disallow the deleting old snapshots while there is no replica rebuilding

> If we are introducing force snapshot creation, why not consider a new recurring job type(snapshot-force) instead of a global setting?
Or, can we add recurringjob.spec.forceSnapshot rather than a global setting?

@c3y1huang @derekbit IMO `recurringjob.spec.forceSnapshot` might be more flexible

**Comment by c3y1huang** [comment]
> > If we are introducing force snapshot creation, why not consider a new recurring job type(snapshot-force) instead of a global setting?
> > Or, can we add recurringjob.spec.forceSnapshot rather than a global setting?
> 
> @c3y1huang @derekbit IMO `recurringjob.spec.forceSnapshot` might be more flexible

If this way, then we need to do some mutation for this spec for other recurring job types, ex `snapshot-clean`, `snapshot-delete`, `trim`, etc.

**Comment by shuo-wu** [comment]
I think we can have 2 mode for the snapshot job:
"delete-first" mode: Do cleanup before creation. Make sure the recurring snap count is no more than the retain number.
"creation-first" mode: The current design. Make sure the new snapshot will be created on time (typically creation won't be blocked unless the volume reaches the limit or there is a network issue) but the snap count can be greater than the retain number.

As for how we config the mode. I am fine with either relying on recurring job spec or using a setting.

**Comment by innobead** [comment]
It seems like there are tradeoffs for some cases, so having options seems reasonable now. Combing all feedback and I think @shuo-wu has a good summary of the proposal. Let's do recurring jobs with different modes. 

WDYT?

**Comment by mantissahz** [comment]
Now [the PR](https://github.com/longhorn/longhorn-manager/pull/1708) will start to clean up snapshots first if the number of old snapshots exceeds the retain number for recurring job type `snapshot`, and introduce the new recurring job type `snapshot-force-create` as original behavior - take a new snapshot first then clean up old snapshots.

**Comment by innobead** [comment]
@mantissahz Need to update doc as well.

**Comment by innobead** [comment]
This is actually a behavior change for the original recurring jobs type snapshot & backup, so need to update the important note in doc. Usually, we should not have behavior changes to any patch release, but this is indirectly fixing an issue related to encountering the maximum number of snapshots when doing snapshot or backup, so it's totally acceptable and reasonable.

**Comment by innobead** [comment]
@mantissahz We need to request UI update as well like https://github.com/longhorn/longhorn-ui/pull/595. 

Please work with @smallteeths to make this ready for 1.3.3-RC2. Create a UI task for that.

**Comment by innobead** [comment]
For @longhorn/qa can verify without doc PR, but after verifying, just return back to the assignee @mantissahz to finish the doc update before closing this. Thanks.

**Comment by chriscchien** [comment]
Verified in longhorn master `676485` with [steps](https://github.com/longhorn/longhorn/issues/4898#issuecomment-1435697791)
Result **Pass**

Below recurring job types work as expected when replica is rebuilding and the the snapshot/backup count reached retain number 
- `snapshot` : Clean up old 1 snapshot then take a new snapshot.
- `snapshot-force-create` : Take a new snapshot first then clean up old snapshot.
- `backup` : Clean up old 1 snapshot then take a new snapshot.
- `backup-force-create` : Take a new backup first then clean up old backup.
After replica  rebuild complete, all job type have retain number mated to their setting.  

cc @mantissahz

**Comment by mantissahz** [comment]
@chriscchien 
When replica is rebuilding, will these four task types still clean up old snapshot?

**Comment by chriscchien** [comment]
@mantissahz yes, when replica is rebuilding, the old snapshots still clean up

**Comment by mantissahz** [comment]
Closed because Verified at https://github.com/longhorn/longhorn/issues/4898#issuecomment-1480582908
