### ISSUE TITLE
Progress report for restore

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#49]
The restore process is different from rebuild/backup. The restore was done as a part of replica starting, so at that time the controller wasn't started yet. 

On the manager side, it should be reported as a part of replica status periodically, filled by the replica controller.

**Comment by yasker** [comment]
@smallteeths backend merged.

**Comment by yasker** [comment]
@shreesha21 Can you document the API reference for the restoration status for UI here?

**Comment by yasker** [comment]
@smallteeths for now you should able to refer to https://github.com/longhorn/longhorn-manager/blob/master///api/model.go#L584

**Comment by shreesha21** [comment]
Request: `curl http://172.104.18.252:30766/v1/volumes`
Response: The response contains all the fields of volume object along with `restoreStatus` as below:

```
   "data" : [
      {
         "restoreStatus" : [
            {
               "lastRestored" : "",
               "progress" : 0,
               "actions" : null,
               "replica" : "tcp://10.42.0.75:9502",
               "isRestoring" : false,
               "error" : "",
               "state" : "",
               "links" : null,
               "filename" : ""
            },
            {
               "replica" : "tcp://10.42.2.132:9502",
               "isRestoring" : true,
               "actions" : null,
               "progress" : 73,
               "lastRestored" : "",
               "filename" : "volume-snap-76cf801b-279e-4a0b-a36b-8c78cb279135.img",
               "links" : null,
               "error" : "",
               "state" : "incomplete"
            }
            ...
            ...
         ],
],
```

**Comment by yasker** [comment]
@shreesha21 We need to update the replica field in the manager API to report the replica name instead of IP, otherwise it's hard for UI to figure out which is which. Only need to update the manager API, no change needed for the engine.

**Comment by yasker** [comment]
@smallteeths https://github.com/longhorn/longhorn-manager/pull/355 has been merged, now API shows replica name instead of IP.

**Comment by yasker** [comment]
@smallteeths reports that the replica states during the restoration are switching between `RW` and ``(empty). @shreesha21 ^^

**Comment by meldafrawi** [comment]
Validattion: **PASSED**

Steps to test:
  - Create a volume, attach it to a node, format it, mount it to a directory on attached node, write some data to it.
  - In `Settings` page, make sure backup target is correctly configured.
  - In `Volume Details` page, Click `Create Backup`, and wait for backup to complete.
  - In `Backup` page, click on volume name
  - From the right drop down menu of the backup, click `Restore`.
  - Enter `Name`, and set `Number of replicas`, and click `OK`
  >> Expected result: Restoration should start, and restoration progress should be visible in 
  1 - `Volume Details` page at `Volume Details` section
  2 - `Volume Details` page at `Replicas` section for every volume replica.
  3 -  `Volume` page under volume status.
