### ISSUE TITLE
[TASK] Check Longhorn compatibility with more kind of Linux distros

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4900]
## What's the task? Please describe

Some distros may not support some system cmds Longhorn is using.

For example, [`-regextype posix-extended`](https://github.com/longhorn/longhorn-manager/blob/f1c71ea292a7bc9ad076f261ff05b93dd1d8bf05/util/util.go#L835) used in [the orphan detection feature](https://github.com/longhorn/longhorn-manager/blob/f1c71ea292a7bc9ad076f261ff05b93dd1d8bf05/controller/monitor/disk_monitor.go#L77) is not supported by alpine/busybox in Rancher Desktop.

## Describe the items of the task (DoD, definition of done) you'd like

~~- [ ] Test Longhorn with more kinds of Linux distros like Alpine~~ (will fix the issue with our own implementing to prevent unsupported options. @ChanYiLin )
- [ ] Replace the system cmds with Longhorn implementation in the future 

## Additional context

This issue is reported in [the Slack discussion](https://cloud-native.slack.com/archives/CNVPEL9U3/p1668696091797059).

cc @innobead

**Comment by innobead** [comment]
cc @derekbit

**Comment by derekbit** [comment]
This is pretty annoying. Should we use our customized binary utilities? Or, anything change in the distros will introduce new issues.

**Comment by innobead** [comment]
> This is pretty annoying. Should we prepare and use our customized binary utilities? Or, any change in the distros will introduce new issues.

Exactly, but the better solution is done by us instead of relying on external util commands. Let's figure out it in a later version.

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by lindhe** [comment]
I just ran into this, with `longhorn-manager` crashing because of `find: unrecognized: -regextype`.

A reasonable short-term/mid-term solution would be to just clarify the docs. It's not very clear from the [Installation requirements](https://longhorn.io/docs/1.5.3/deploy/install/#installation-requirements) that Busybox is not supported.

**Comment by ChanYiLin** [comment]
This was already fixed by @c3y1huang when working on supporting Talos
https://github.com/longhorn/longhorn-manager/pull/2103/files#diff-a61d5e39f45fb5ed2dc1ef71fa708c8db480e9a396adb8a5d9d17b8e6ba1e186R625-R651

We can move on testing.

**Comment by roger-ryao** [comment]
Hi @ChanYiLin 
      I installed K3s on an `Alpine Linux` VM, but when I tried to install Longhorn, I encountered an error: `longhorn-manager-tdggk  CreateContainerError`.  Our documentation doesn't mention support for `Alpine Linux`. Could you help confirm this?

```yaml
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  18m                   default-scheduler  Successfully assigned longhorn-system/longhorn-manager-tdggk to alpine
  Warning  Failed     18m                   kubelet            Error: failed to generate container "132e026139a553161231a081c64bf74dd4c6bf3957429a0793b1daa944d2cb0b" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Normal   Pulled     18m                   kubelet            Container image "longhornio/longhorn-share-manager:v1.8.0-dev-20240825" already present on machine
  Normal   Created    18m                   kubelet            Created container pre-pull-share-manager-image
  Normal   Started    18m                   kubelet            Started container pre-pull-share-manager-image
  Warning  Failed     18m                   kubelet            Error: failed to generate container "e89193aae8e4b07bd79572855275abb5c7fbb202eb6f6ab54b4369707ad7a3a9" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     17m                   kubelet            Error: failed to generate container "1beefaa29de53c24fed46e3e9113d633340f7c00e1aad14d43d281ee0bb0100e" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     17m                   kubelet            Error: failed to generate container "f4e244f08d5eb2bcef80789deef46d464bbfa7558f741909bac83c3fe8d5a63a" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     17m                   kubelet            Error: failed to generate container "921e585e1e26bedaab7848d47d164b7f06610a9f62f27ff476def6c48eeb0823" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     17m                   kubelet            Error: failed to generate container "bcb5601e3a3e6f5492c1d817a6fd9a5075ec6ccd2a9d76974189831323a5939a" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     17m                   kubelet            Error: failed to generate container "82591a9ac5525c53f8312bdc188cbc716108cfb9a2c43fb0cf59454ebb4030d9" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     16m                   kubelet            Error: failed to generate container "8360694cf3fd79e7e7a718c525b60d921e6b1be6a3c5398c01b7d3e7b48a4139" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     16m                   kubelet            Error: failed to generate container "e906c7ec797db6e7f03d1f926fcb837cdc00c5dc11d7210b124c5b74fd068d08" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     16m (x2 over 16m)     kubelet            (combined from similar events): Error: failed to generate container "0b2dc1e558fa0b5a23f2a296517d461f9ced6411e90af3cbcb9cdd818fddc084" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Normal   Pulled     2m59s (x72 over 18m)  kubelet            Container image "longhornio/longhorn-manager:v1.8.0-dev-20240825" already present on machine
```

**Comment by roger-ryao** [comment]
> I think we can test if the current Longhorn version can be run on Rancher Desktop on Alpine VM (This `GetPossibleReplicaDirectoryNames` function is executed periodically after the longhorn-managers start)

After discussing with @derekbit , I update [the user on the status](https://cloud-native.slack.com/archives/CNVPEL9U3/p1725442043111399?thread_ts=1668696091.797059&cid=CNVPEL9U3) of this ticket. 
We can close it for now. 
If the user encounters the same issue again, we kindly ask them to inform us through the ticket.
