### ISSUE TITLE
[TASK] Create longhornio support-bundle-kit image

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4911]
## What's the task? Please describe

We need a `longhornio` supoort-bundle-kit `v0.0.12` image.

## Describe the items of the task (DoD, definition of done) you'd like

- [ ] Mirror a [support-bundle-kit](https://github.com/rancher/support-bundle-kit) v0.0.12 image to a longhornio image

## Additional context

https://github.com/longhorn/longhorn/issues/2759

**Comment by innobead** [comment]
A general task but related to infra, so added to the QA board. 

cc @longhorn/qa

**Comment by yangchiu** [comment]
Is this the right image? https://hub.docker.com/r/rancher/support-bundle-kit/tags
It doesn't support arm64?

**Comment by bk201** [comment]
Harvester doesn't support arm64, so we never tested it before.

**Comment by innobead** [comment]
Then, we need to make support-bundle-kits support arm64.

@yangchiu @c3y1huang Please cooperate with the below items.
- Update https://github.com/rancher/support-bundle-kit/blob/master/.drone.yml to support arm64 pipeline w/ manifest (you can reference https://github.com/rancher/rancher/blob/release/v2.7/.drone.yml#L389-L394, the rancher has arm64 build support)
- Make sure arm64 image work well in longhorn arm64 install
- Mirror support-bundle-kits image

**Comment by yangchiu** [comment]
we need s390 image too, right?

**Comment by innobead** [comment]
> oesn't support arm64, so we never tested it before.

Exactly! rancher push CI also has that support, so we can leverage it as well.

**Comment by yangchiu** [comment]
Created PR https://github.com/rancher/support-bundle-kit/pull/54 to build images for arm64 and s390x: https://drone-publish.rancher.io/rancher/support-bundle-kit/92/4

But the build scripts need to be modified too, since currently it shows the following errors:
```
E: Package 'docker-ce' has no installation candidate
E: Package 'docker-ce-cli' has no installation candidate
E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'
```
cc @c3y1huang @innobead

**Comment by innobead** [comment]
@c3y1huang please help with the build change. Go discuss with @bk201 if needed.

**Comment by yangchiu** [comment]
@innobead @c3y1huang `rancher/support-bundle-kit` images for different platforms already published: https://hub.docker.com/r/rancher/support-bundle-kit/tags

**Comment by yangchiu** [comment]
@innobead I'm unable to publish `support-bundle-kit` to `longhornio`, no matter login as `longhornbot` or my own account, the error message shows:

```
DEBU[0006] Checking /v2/longhornio/support-bundle-kit/blobs/sha256:a36658c7e7f03cdc1975ff35e22ca9f96a3666860e1f41eb7d21f99d0138e7e4 
DEBU[0006] HEAD https://registry-1.docker.io/v2/longhornio/support-bundle-kit/blobs/sha256:a36658c7e7f03cdc1975ff35e22ca9f96a3666860e1f41eb7d21f99d0138e7e4 
DEBU[0006] ... not authorized                           
DEBU[0007] ... not authorized                           
DEBU[0007] ... not authorized                           
DEBU[0008] ... not authorized                           
DEBU[0008] ... not authorized    
```
The same script can publish `support-bundle-kit` image to my own dockerhub repo without any problem.

Not sure but probably due to only owners of this organization can create repositories.

**Comment by innobead** [comment]
@yangchiu try again, https://hub.docker.com/repository/docker/longhornio/support-bundle-kit.

**Comment by yangchiu** [comment]
@c3y1huang images mirrored to longhornio: https://hub.docker.com/repository/docker/longhornio/support-bundle-kit/general

**Comment by c3y1huang** [comment]
@yangchiu we need to mirror a v0.0.14 image that includes [this fix](https://github.com/rancher/support-bundle-kit/pull/56).

**Comment by yangchiu** [comment]
done!
