### ISSUE TITLE
[DOC] Add Recurring * Jobs History Limit to setting referenence

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4912]
## What's the task? Please describe

We need to add the new settings to the setting reference page.

## Describe the items of the task (DoD, definition of done) you'd like

- [x] settings added to the doc

## Additional context

https://github.com/longhorn/longhorn/issues/1711

**Comment by roger-ryao** [comment]
- [x] 1.4.0
**Result Passed**
