### ISSUE TITLE
[DOC] Add Failed Backup TTL to setting referenence

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4913]
## What's the task? Please describe

We need to add the new setting to the setting reference page.

## Describe the items of the task (DoD, definition of done) you'd like

- [x] setting added to the doc

## Additional context

https://github.com/longhorn/longhorn/issues/3898

**Comment by mantissahz** [comment]
Documents had been merged, closed this issue. Thank @c3y1huang.
