### ISSUE TITLE
Auto deattach/attach volumes

### ISSUE THREAD

**Issue by C0NO** [longhorn/longhorn#492]
I have 2 slave 1 master kubernetes cluster.I installed longhorn and i can access web ui succesfully.I am really interested in with handle node failure.When i create a pod with pv it starts and i can see the attached status on web ui.When i delete the pod the pv status is getting detached status on web ui.But if i poweroff the node (which has the pod) and wait 45 minutes it shows still attach that node(closed one) and can not switch and attach to other node automatically so the new pod can not start because of volume error(i tried it with --force delete, deletion was succesfull but it was still attached state).If i manually detach and attach it works and the new pod on the new node starts.So i can manually handle the node failure.But i want to do it automatically and it should spend as less time as possible .

Kubernetes version: 1.14
longhorn version : 0.4.1
docker version : 18.09.5
OS:debian 9
Cluster:on-premise bare metal with virtualbox vms.

**Comment by yasker** [comment]
Hi @C0NO, 

Please check if https://github.com/rancher/longhorn/blob/master/docs/node-failure.md applies to your setup. Currently we need user to delete the original pod to get volume reattached automatically to the new pod, for both statefulset and deployment.

**Comment by C0NO** [comment]
Thank you for reply.Even if i delete the pod (with --force) it is not deataching automatically.But if i do it manually via gui it is succesfully reattaching.

**Comment by C0NO** [comment]
I can also see that the longhorn controller can see the node status unknown on the event logs:
Kubernetes node slave2 not ready: NodeStatusUnknown

**Comment by yasker** [comment]
How long you had been waiting after pod was force deleted? Kubernetes took about 6 minutes to ask storage driver to detach the volume as we observed (see the doc). If it's still not working, we can investigate.

**Comment by C0NO** [comment]
Ok i tried to force deleteion deployment(nnot pod in the deployment) and it attached manually on the new pod.I tried only force delete the pod but it is worked when i delete deployment.Thank you for help.I am looking for reduce the auto recovery time now.Best regards.

**Comment by yasker** [comment]
We're improving the reattaching time in Longhorn v0.5.0.

It's a bit unclear to me what is the process working for you? Just force delete the pod should be good enough.

**Comment by C0NO** [comment]
I just try to migrate some classic server type application to a private cloud system.I have 1 edge 1 cloud server and i am working to setup a high availability which is literally zero downtime for applications.But 10 minutes quite good for me but at the future for some customer this time should  reduced.But it would be good if there is option about reattach time.Thank you for kind replies.
