### ISSUE TITLE
[IMPROVEMENT] Move all snapshot related settings at one place.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#4930]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Now that we have Snapshot section on the setting page ([ref 4210](https://github.com/longhorn/longhorn/issues/4210)), we should move the setting Automatically Cleanup System Generated Snapshot from General section to Snapshot section.

<img width="1283" alt="Screenshot 2022-11-23 at 3 41 00 PM" src="https://user-images.githubusercontent.com/60111667/203664355-1a8d0309-f8f8-4cce-b2ce-40bc809a3432.png">
<img width="1649" alt="Screenshot 2022-11-23 at 3 41 30 PM" src="https://user-images.githubusercontent.com/60111667/203664359-77e7be9f-7a4e-4ce5-9d4b-c86b026ab6bf.png">

**Comment by innobead** [comment]
@smallteeths Can you help with this? Thanks.

**Comment by smallteeths** [comment]
The Longhorn backend modifies the 'definition.category' of this setting to 'snapshot', causing the UI to place this setting item in the 'snapshot' category. I have checked and the latest backend has already made this modification as shown in the following image. @innobead 

<img width="803" alt="截屏2023-05-15 上午9 26 12" src="https://github.com/longhorn/longhorn/assets/27733391/044dae06-b099-4ad8-a2f2-676a3f0c23b3">

**Comment by innobead** [comment]
@roger-ryao Please help verify this then close if it's not an issue anymore.

**Comment by roger-ryao** [comment]
**Verified on master-head 20230515**

- longhorn master-head ([17ce9ec](https://github.com/longhorn/longhorn/commit/17ce9ec4452e2ccef4f91749ac449088411691a5))
- longhorn-manager master-head ([0ac0cc9](https://github.com/longhorn/longhorn-manager/commit/0ac0cc9931260b52a0cbe3c16040276a694012ac))


**Result Passed**

The setting `Automatically Cleanup System Generated Snapshot` has been moved to the `Snapshot` section.

![Screenshot_20230515_152925](https://github.com/longhorn/longhorn/assets/104337648/23632931-447f-43b1-876f-c1d7f64380a6)
