### ISSUE TITLE
[IMPROVEMENT] Replace the modTime (mtime) with ctime in snapshot hash

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4934]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The current implementation of snapshot hash records the `mtime` of a snapshot disk file and uses it to check the data integrity. A malicious user can change the `mtime` and result in the failure of the snapshot data integrity check. In Linux,`ctime` cannot be changed the ctime by ordinary means ([ref](https://unix.stackexchange.com/questions/36021/how-can-i-change-change-date-of-file)). Thus, we should use `ctime` for reducing the chance of the tempering.

The checksum and timestamp are both recorded in the exetending attribute. Setting extended attributes changes of the `ctime` and leads to the failure of the corruption detection algorithm. So, the imporvement will also save the `checksum` and `ctime` in a checksum file rather than a extended attribute.

**Comment by chriscchien** [comment]
Verified in longhorn master `91c0fa` with test [steps](https://github.com/longhorn/longhorn/issues/3198#issuecomment-1286534879)
Result  **Pass**

1. With Snapshot Data Integrity set to fast-check or enabled, after manually corrupted the snapshot, replica will rebuild and checksum after rebuild complete was the same with disk file , meta data file and value in CR `snapshots.longhorn.io`
2. In snapshot metadata file can observe field `ModTime` no longer exist and replaced by `changeTime`.
