### ISSUE TITLE
[BUG] Failed to attach volumes: with log "Error running controller command: size is required."

### ISSUE THREAD

**Issue by xinbinhuang** [longhorn/longhorn#4941]
## Describe the bug (🐛 if you encounter this issue)

In longhorn UI, volumes keep stuck in `attaching/detaching/detached` loop

## To Reproduce

Not sure how to reproduce

## Expected behavior

Longhorn attach volume successfully 

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.
[longhorn-support-bundle_7f2403be-2db3-4f3b-95c1-f4e851c30a28_2022-11-25T04-24-19Z.zip](https://github.com/longhorn/longhorn/files/10088593/longhorn-support-bundle_7f2403be-2db3-4f3b-95c1-f4e851c30a28_2022-11-25T04-24-19Z.zip)

## Environment

 - Longhorn version: 1.3.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.24.4+k3s1
   - Number of management node in the cluster: 3 
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version: 2 Ubuntu 22.04 + 2 Rasberry OS Lite
   - CPU per node: 2/4 cpu 
   - Memory per node: 8G
   - Disk type(e.g. SSD/NVMe): 3 SSD + 1 SD card
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): 
 - Number of Longhorn volumes in the cluster: 14

**Comment by derekbit** [comment]
@xinbinhuang 
Have you upgraded the longorn system to v1.3.2?

**Comment by xinbinhuang** [comment]
@derekbit  I don't think I can upgrade to v1.3.2 because the helm chart is incompatible with k8s 1.25 when I checked a few days ago. Has it changed?

**Comment by derekbit** [comment]
I see. I've checked your support bundle. longhorn-manager is using v1.3.1, but the engine of the volumes are using v1.3.2. Did you update the engine images of the volume? The old manager cannot guarantee to a support newer engine.
Two solutions to this case:
1. downgrade the engines of the volumes to v1.3.1
2. upgrade the longhorn-system to v1.3.2. Your kubernetes version v1.24.4 which should be compatible with LH v1.3.2.

**Comment by xinbinhuang** [comment]
Thank you for the help! It seems like the issue has resolved once I downgrade the engines of the volumes to v1.3.1.

> upgrade the longhorn-system to v1.3.2. Your kubernetes version v1.24.4 which should be compatible with LH v1.3.2.

Sorry, I forgot to mention that the blocker on upgrading longhorn is actually caused by the latest version of argocd that uses a helm version compiled for k8s v1.25. I'll probably wait till the v1.25 support come in before upgrading
