### ISSUE TITLE
[TASK] Create longhornio liveness probe image

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4945]
## What's the task? Please describe

We need a `longhornio` liveness probe v2.8.0 image, similar to other [csi images](https://github.com/longhorn/longhorn/blob/master/deploy/longhorn-images.txt#L1-L5).

## Describe the items of the task (DoD, definition of done) you'd like

- [ ] Mirror a [https://github.com/kubernetes-csi/livenessprobe](https://github.com/kubernetes-csi/livenessprobe) v2.8.0 image to a longhornio image

## Additional context

https://github.com/longhorn/longhorn/issues/3907

**Comment by yangchiu** [comment]
image published: https://hub.docker.com/r/longhornio/livenessprobe/tags
