### ISSUE TITLE
[TASK] Fix devel tools repo in all Longhorn component projects

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4949]
## What's the task? Please describe

See https://github.com/longhorn/longhorn/issues/4946

## Describe the items of the task (DoD, definition of done) you'd like

- [ ] Update the repo path in all Longhorn component projects.

## Additional context

https://github.com/longhorn/longhorn/issues/4617

**Comment by yangchiu** [comment]
longhorn-manager: doesn't use these packages
longhorn-engine: https://github.com/longhorn/longhorn-engine/pull/774
longhorn-instance-manager: already updated
longhorn-share-manager: doesn't use these packages
backing-image-manager: https://github.com/longhorn/backing-image-manager/pull/70
