### ISSUE TITLE
[BUG] volume is stuck in attaching/detaching loop with error `Failed to init frontend: device...`

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4959]
Volume stuck in attaching/detaching loop with the error:
```
2022-11-24T11:26:30.985743332Z tgtd: target_mgmt(147) Failed to unbind by address: ALL
Failed to init frontend: device pvc-3b45d723-d8fa-4c75-b334-0508faa92ea0: fail to delete target iqn.2019-10.io.longhorn:pvc-3b45d723-d8fa-4c75-b334-0508faa92ea0
```

From Longhorn engine, the error `tgtd: target_mgmt(147) Failed to unbind by address: ALL` comes from [this function call](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L236)

From the tgtadm, it comes from t[his line of code](https://github.com/fujita/tgt/blob/6bd8382ff69378e6e27860a1a0a147eef0b42e22/usr/mgmt.c#L147). Digging deeper we can see that it was probably there is no tgt target with the corresponding target id at [here](https://github.com/fujita/tgt/blob/6bd8382ff69378e6e27860a1a0a147eef0b42e22/usr/target.c#L1740-L1741)

@innobead and I feel like we shouldn't error out when trying to unbind while tgt target does not exist. However, we will need to investigate more and try to reproduce the issue

**Comment by innobead** [comment]
cc @shuo-wu @derekbit @joshimoo

**Comment by PhanLe1010** [comment]
```
root@instance-manager-e-6a2937ea:/# tgtadm --lld iscsi --op show --mode target
Target 1: iqn.2019-10.io.longhorn:pvc-3b45d723-d8fa-4c75-b334-0508faa92ea0
    System information:
        Driver: iscsi
        State: ready
    I_T nexus information:
        I_T nexus: 1
            Initiator: iqn.1994-05.com.redhat:84a88f6477d0 alias: si0vm06569
            Connection: 0
                IP Address: 10.134.4.233
        I_T nexus: 2
            Initiator: iqn.1994-05.com.redhat:84a88f6477d0 alias: si0vm06569
            Connection: 0
                IP Address: 10.134.4.233
        I_T nexus: 3
            Initiator: iqn.1994-05.com.redhat:84a88f6477d0 alias: si0vm06569
            Connection: 0
                IP Address: 10.134.4.233
        I_T nexus: 4
            Initiator: iqn.1994-05.com.redhat:84a88f6477d0 alias: si0vm06569
            Connection: 0
                IP Address: 10.134.4.233
        I_T nexus: 5
            Initiator: iqn.1994-05.com.redhat:84a88f6477d0 alias: si0vm06569
            Connection: 0
                IP Address: 10.134.4.233
        I_T nexus: 6
            Initiator: iqn.1994-05.com.redhat:84a88f6477d0 alias: si0vm06569
            Connection: 0
                IP Address: 10.134.4.233
        I_T nexus: 7
            Initiator: iqn.1994-05.com.redhat:84a88f6477d0 alias: si0vm06569
            Connection: 0
                IP Address: 10.134.4.233
        I_T nexus: 8
            Initiator: iqn.1994-05.com.redhat:84a88f6477d0 alias: si0vm06569
            Connection: 0
                IP Address: 10.134.4.233
        I_T nexus: 9
            Initiator: iqn.1994-05.com.redhat:84a88f6477d0 alias: si0vm06569
            Connection: 0
                IP Address: 10.134.4.233
    LUN information:
        LUN: 0
            Type: controller
            SCSI ID: IET     00010000
            SCSI SN: beaf10
            Size: 0 MB, Block size: 1
            Online: Yes
            Removable media: No
            Prevent removal: No
            Readonly: No
            SWP: No
            Thin-provisioning: No
            Backing store type: null
            Backing store path: None
            Backing store flags:
        LUN: 1
            Type: disk
            SCSI ID: IET     00010001
            SCSI SN: beaf11
            Size: 1074 MB, Block size: 512
            Online: Yes
            Removable media: No
            Prevent removal: No
            Readonly: No
            SWP: No
            Thin-provisioning: No
            Backing store type: longhorn
            Backing store path: /var/run/longhorn-pvc-3b45d723-d8fa-4c75-b334-0508faa92ea0.sock
            Backing store flags:
    Account information:
    ACL information:
root@instance-manager-e-6a2937ea:/#
```
---
The old TGT target is actually still here (with the id 1) as shown in the output.  One thing to notice is that the ACL information is already empty which means that this [UnbindInitiator](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L236) function call already succeeded once before. Now Longhorn retries the function call with the empty ACL information . This will always error out. I am able to reproduce this issue. This seems a bug in Longhorn volume shutdown/startup procedure.

---
**RCA:**
1. Before a new attachment, Longhorn tries to clean up the old TGT target with the same name.
2. Deleting the old TGT target means calling the function [DeleteTarget](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L230). Within this function, somehow [UnbindInitiator](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L236) function call succeeded (ACL information becomes empty) but then there is a transient error in [the rest of the shutdown flow](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L240-L258).
3. Because the first attachment failed, Longhorn retries the 2nd time. However, since the ACL information is already empty, [UnbindInitiator](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L236) function call always fails. This prevents the cleanup which then prevents the 2nd attachment. This cycle repeated again and again

---
**Reproduce steps:**
1. Create a Longhorn volume, `testvol`
2. Attach the Longhorn volume to a node, say `node-1`
3. Find the instance manager e pod on `node-1`
4. kubectl exec into the above instance manager e pod
5. List all the targets:
```
root@instance-manager-e-3382c653:/# tgtadm --lld iscsi --op show --mode target
Target 1: iqn.2019-10.io.longhorn:testvol
    System information:
        Driver: iscsi
        State: ready
    I_T nexus information:
        I_T nexus: 1
            Initiator: iqn.1993-08.org.debian:01:5e999e2fae73 alias: phan-v190-pool2-66ea5213-hjpfg
            Connection: 0
                IP Address: 164.92.123.217
    LUN information:
        LUN: 0
            Type: controller
            SCSI ID: IET     00010000
            SCSI SN: beaf10
            Size: 0 MB, Block size: 1
            Online: Yes
            Removable media: No
            Prevent removal: No
            Readonly: No
            SWP: No
            Thin-provisioning: No
            Backing store type: null
            Backing store path: None
            Backing store flags: 
        LUN: 1
            Type: disk
            SCSI ID: IET     00010001
            SCSI SN: beaf11
            Size: 5369 MB, Block size: 512
            Online: Yes
            Removable media: No
            Prevent removal: No
            Readonly: No
            SWP: No
            Thin-provisioning: No
            Backing store type: longhorn
            Backing store path: /var/run/longhorn-testvol.sock
            Backing store flags: 
    Account information:
    ACL information:
        ALL
```
6. Manually unbind the initiator from the access control list (which is a part of the shutdown flow)
```
root@instance-manager-e-3382c653:/# tgtadm --lld iscsi --op unbind --mode target --tid 1 -I ALL
```
7. List all the targets again, notice that `ACL information`  is empty this time
8. If we try to unbind again with empty `ACL information` , we will always get error:
```
root@instance-manager-e-3382c653:/# tgtadm --lld iscsi --op unbind --mode target --tid 1 -I ALL
tgtadm: this access control rule does not exist
root@instance-manager-e-3382c653:/# echo $?
22
```
9. Detach the volume
10. Attach the volume.
11. Observe that the volume is stuck in attaching/detaching loop. Same as what customers experiencing:
```
[instance-manager-e-3382c653] [testvol-e-7c714976] time="2022-11-29T20:34:16Z" level=info msg="Shutdown SCSI target iqn.2019-10.io.longhorn:testvol"
[instance-manager-e-3382c653] tgtd: target_mgmt(147) Failed to unbind by address: ALL
[instance-manager-e-3382c653] [testvol-e-7c714976] time="2022-11-29T20:34:16Z" level=error msg="Failed to init frontend: device testvol: fail to delete target iqn.2019-10.io.longhorn:testvol"
...
```

**---
Workaround:** 
1. Note down the current attaching NodeID
```
kubectl get volumes.longhorn.io <volume-name> -n longhorn-system
# note down the spec.nodeID
```
2. Detach the volume by scaling down the workload pods that are using the volume
3.  kubectl exec into the instance manager e pod on the `spec.nodeID` above
4. Find the TGT target id corresponding to the volume:
```
root@instance-manager-e-3382c653:/# tgtadm --lld iscsi --op show --mode target
Target 1: iqn.2019-10.io.longhorn:testvol
    System information:
        Driver: iscsi
        State: ready
...
# in this case, the TGT target id is 1
```
5. Try to bind the missing initiator:
```
tgtadm --lld iscsi --op bind --mode target --tid <TGT-ID-FROM_ABOVE-STEP> -I ALL
```
6. scale up the workload again. Volume should be able to attach

**Comment by innobead** [comment]
tgtadm return codes.
https://github.com/fujita/tgt/blob/master/usr/tgtadm.c#L56-L87

**Comment by innobead** [comment]
Assigned @PhanLe1010 here, because he was working on the analysis, but @derekbit will do the rest of the implementation. Thanks, both.

**Comment by chriscchien** [comment]
Verified in longhorn master `0e56cd` with test [steps](https://github.com/longhorn/longhorn/issues/4959#issuecomment-1331362213)
Result `Pass`

I can reproduce the detach attach loop by deploying previous version of engine image. After using latest engine image,  when `ACL information` become empty in instance manager e pod , do volume detach attach operation, volume can successfully attached and become healthy.

**Comment by qybf** [comment]
> Verified in longhorn master `0e56cd` with test [steps](https://github.com/longhorn/longhorn/issues/4959#issuecomment-1331362213) Result `Pass`
> 
> I can reproduce the detach attach loop by deploying previous version of engine image. After using latest engine image, when `ACL information` become empty in instance manager e pod , do volume detach attach operation, volume can successfully attached and become healthy.



> ```
> root@instance-manager-e-6a2937ea:/# tgtadm --lld iscsi --op show --mode target
> Target 1: iqn.2019-10.io.longhorn:pvc-3b45...a92ea0
>     System information:
>         Driver: iscsi
>         State: ready
>     I_T nexus information:
>         I_T nexus: 1
>            ...
>         I_T nexus: 2
>           ...
>         I_T nexus: 3
>            ...
>         I_T nexus: 4
>            ...
>         I_T nexus: 5
>            ...
>         I_T nexus: 6
>            ...
>         I_T nexus: 7
>           ...
>         I_T nexus: 8
>            ...
>         I_T nexus: 9
>             ...
>     LUN information:
>         LUN: 0
>             Type: controller
>             SCSI ID: IET     00010000
>             SCSI SN: beaf10
>             Size: 0 MB, Block size: 1
>             Online: Yes
>             Removable media: No
>             Prevent removal: No
>             Readonly: No
>             SWP: No
>             Thin-provisioning: No
>             Backing store type: null
>             Backing store path: None
>             Backing store flags:
>         LUN: 1
>             Type: disk
>             SCSI ID: IET     00010001
>             SCSI SN: beaf11
>             Size: 1074 MB, Block size: 512
>             Online: Yes
>             Removable media: No
>             Prevent removal: No
>             Readonly: No
>             SWP: No
>             Thin-provisioning: No
>             Backing store type: longhorn
>             Backing store path: /var/run/longhorn-pvc-3b45d...92ea0.sock
>             Backing store flags:
>     Account information:
>     ACL information:
> root@instance-manager-e-6a2937ea:/#
> ```
> 
> The old TGT target is actually still here (with the id 1) as shown in the output. One thing to notice is that the `ACL information` is already empty which means that this [UnbindInitiator](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L236) function call already succeeded once before. Now Longhorn retries the function call with the empty `ACL information` . This will always error out. I am able to reproduce this issue. This seems a bug in Longhorn volume shutdown/startup procedure.旧的TGT目标实际上仍然在这里（id为1），如输出所示。 需要注意的一点是，`ACL information`已经为空，这意味着这个[UnbindInitiator](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L236)函数调用已经成功过一次。现在Longhorn用空的`ACL information`重试函数调用。这将始终出错。我可以重现这个问题。这似乎是Longhorn卷关闭/启动过程中的一个错误。
> 
> **RCA:RCA：**
> 
>     1. Before a new attachment, Longhorn tries to clean up the old TGT target with the same name.在创建新的附件之前，Longhorn会尝试清除同名的旧TGT目标。
> 
>     2. Deleting the old TGT target means calling the function [DeleteTarget](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L230). Within this function, somehow [UnbindInitiator](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L236) function call succeeded (`ACL information` becomes empty) but then there is a transient error in [the rest of the shutdown flow](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L240-L258).删除旧的TGT目标意味着调用函数[DeleteTarget](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L230)。在此函数中，[UnbindInitiator](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L236)函数调用成功（`ACL information`变为空），但随后在关闭流的其余部分中出现暂时性错误。
> 
>     3. Because the first attachment failed, Longhorn retries the 2nd time. However, since the `ACL information` is already empty, [UnbindInitiator](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L236) function call always fails. This prevents the cleanup which then prevents the 2nd attachment. This cycle repeated again and again由于第一次连接失败，Longhorn重试第二次。但是，由于`ACL information`已经为空，因此[UnbindInitiator](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L236)函数调用总是失败。这阻止了清理，然后阻止了第二次附接。这样的循环周而复始
> 
> 
> **Reproduce steps:重现步骤：**
> 
>     1. Create a Longhorn volume, `testvol`创建Longhorn卷，`testvol`
> 
>     2. Attach the Longhorn volume to a node, say `node-1`将Longhorn卷连接到一个节点，例如`node-1`
> 
>     3. Find the instance manager e pod on `node-1`在`node-1`上找到实例管理器e pod
> 
>     4. kubectl exec into the above instance manager e podkubectl exec到上面的实例管理器e pod中
> 
>     5. List all the targets:列出所有目标：
> 
> 
> ```
> root@instance-manager-e-3382c653:/# tgtadm --lld iscsi --op show --mode target
> Target 1: iqn.2019-10.io.longhorn:testvol
>     System information:
>         Driver: iscsi
>         State: ready
>     I_T nexus information:
>         I_T nexus: 1
>             Initiator: iqn.1993-08.org.debian:01:5e999e2fae73 alias: phan-v190-pool2-66ea5213-hjpfg
>             Connection: 0
>                 IP Address: 164.92.123.217
>     LUN information:
>         LUN: 0
>             Type: controller
>             SCSI ID: IET     00010000
>             SCSI SN: beaf10
>             Size: 0 MB, Block size: 1
>             Online: Yes
>             Removable media: No
>             Prevent removal: No
>             Readonly: No
>             SWP: No
>             Thin-provisioning: No
>             Backing store type: null
>             Backing store path: None
>             Backing store flags: 
>         LUN: 1
>             Type: disk
>             SCSI ID: IET     00010001
>             SCSI SN: beaf11
>             Size: 5369 MB, Block size: 512
>             Online: Yes
>             Removable media: No
>             Prevent removal: No
>             Readonly: No
>             SWP: No
>             Thin-provisioning: No
>             Backing store type: longhorn
>             Backing store path: /var/run/longhorn-testvol.sock
>             Backing store flags: 
>     Account information:
>     ACL information:
>         ALL
> ```
> 
>     6. Manually unbind the initiator from the access control list (which is a part of the shutdown flow)手动解除启动器与访问控制列表的绑定（这是关闭流的一部分）
> 
> 
> ```
> root@instance-manager-e-3382c653:/# tgtadm --lld iscsi --op unbind --mode target --tid 1 -I ALL
> ```
> 
>     7. List all the targets again, notice that `ACL information`  is empty this time再次列出所有目标，注意这次`ACL information`为空
> 
>     8. If we try to unbind again with empty `ACL information` , we will always get error:如果我们再次尝试使用空的`ACL information`解除绑定，我们总是会得到错误：
> 
> 
> ```
> root@instance-manager-e-3382c653:/# tgtadm --lld iscsi --op unbind --mode target --tid 1 -I ALL
> tgtadm: this access control rule does not exist
> root@instance-manager-e-3382c653:/# echo $?
> 22
> ```
> 
>     9. Detach the volume分离卷
> 
>     10. Attach the volume.连接卷。
> 
>     11. Observe that the volume is stuck in attaching/detaching loop. Same as what customers experiencing:观察体积卡在连接/分离环中。与客户体验相同：
> 
> 
> ```
> [instance-manager-e-3382c653] [testvol-e-7c714976] time="2022-11-29T20:34:16Z" level=info msg="Shutdown SCSI target iqn.2019-10.io.longhorn:testvol"
> [instance-manager-e-3382c653] tgtd: target_mgmt(147) Failed to unbind by address: ALL
> [instance-manager-e-3382c653] [testvol-e-7c714976] time="2022-11-29T20:34:16Z" level=error msg="Failed to init frontend: device testvol: fail to delete target iqn.2019-10.io.longhorn:testvol"
> ...
> ```
> 
> **Workaround:解决方法：**
> 
>     1. Note down the current attaching NodeID记下当前附加的NodeID
> 
> 
> ```
> kubectl get volumes.longhorn.io <volume-name> -n longhorn-system
> # note down the spec.nodeID
> ```
> 
>     2. Detach the volume by scaling down the workload pods that are using the volume通过缩小正在使用卷的工作负载Pod来分离卷
> 
>     3. kubectl exec into the instance manager e pod on the `spec.nodeID` abovekubectl exec到上面`spec.nodeID`的实例管理器e pod中
> 
>     4. Find the TGT target id corresponding to the volume:查找与卷对应的TGT目标ID：
> 
> 
> ```
> root@instance-manager-e-3382c653:/# tgtadm --lld iscsi --op show --mode target
> Target 1: iqn.2019-10.io.longhorn:testvol
>     System information:
>         Driver: iscsi
>         State: ready
> ...
> # in this case, the TGT target id is 1
> ```
> 
>     5. Try to bind the missing initiator:尝试绑定缺少的启动器：
> 
> 
> ```
> tgtadm --lld iscsi --op bind --mode target --tid <TGT-TARGET-ID-FROM_ABOVE-STEP> -I ALL
> ```
> 
>     6. Scale up the workload again. Volume should be able to attach再次扩展工作负载。卷应该能够连接

I used the tgtadm -- lld iscsi -- op bind -- mode target -- tid 7- I ALL command to add ACL information, and then restarted the container. However, I still couldn't mount the volume or was in an infinite loop of connection separation

**Comment by qybf** [comment]
> > Verified in longhorn master `0e56cd` with test [steps](https://github.com/longhorn/longhorn/issues/4959#issuecomment-1331362213) Result `Pass`
> > I can reproduce the detach attach loop by deploying previous version of engine image. After using latest engine image, when `ACL information` become empty in instance manager e pod , do volume detach attach operation, volume can successfully attached and become healthy.
> 
> > ```
> > root@instance-manager-e-6a2937ea:/# tgtadm --lld iscsi --op show --mode target
> > Target 1: iqn.2019-10.io.longhorn:pvc-3b45...a92ea0
> >     System information:
> >         Driver: iscsi
> >         State: ready
> >     I_T nexus information:
> >         I_T nexus: 1
> >            ...
> >         I_T nexus: 2
> >           ...
> >         I_T nexus: 3
> >            ...
> >         I_T nexus: 4
> >            ...
> >         I_T nexus: 5
> >            ...
> >         I_T nexus: 6
> >            ...
> >         I_T nexus: 7
> >           ...
> >         I_T nexus: 8
> >            ...
> >         I_T nexus: 9
> >             ...
> >     LUN information:
> >         LUN: 0
> >             Type: controller
> >             SCSI ID: IET     00010000
> >             SCSI SN: beaf10
> >             Size: 0 MB, Block size: 1
> >             Online: Yes
> >             Removable media: No
> >             Prevent removal: No
> >             Readonly: No
> >             SWP: No
> >             Thin-provisioning: No
> >             Backing store type: null
> >             Backing store path: None
> >             Backing store flags:
> >         LUN: 1
> >             Type: disk
> >             SCSI ID: IET     00010001
> >             SCSI SN: beaf11
> >             Size: 1074 MB, Block size: 512
> >             Online: Yes
> >             Removable media: No
> >             Prevent removal: No
> >             Readonly: No
> >             SWP: No
> >             Thin-provisioning: No
> >             Backing store type: longhorn
> >             Backing store path: /var/run/longhorn-pvc-3b45d...92ea0.sock
> >             Backing store flags:
> >     Account information:
> >     ACL information:
> > root@instance-manager-e-6a2937ea:/#
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The old TGT target is actually still here (with the id 1) as shown in the output. One thing to notice is that the `ACL information` is already empty which means that this [UnbindInitiator](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L236) function call already succeeded once before. Now Longhorn retries the function call with the empty `ACL information` . This will always error out. I am able to reproduce this issue. This seems a bug in Longhorn volume shutdown/startup procedure.旧的TGT目标实际上仍然在这里（id为1），如输出所示。 需要注意的一点是，`ACL information`已经为空，这意味着这个[UnbindInitiator](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L236)函数调用已经成功过一次。现在Longhorn用空的`ACL information`重试函数调用。这将始终出错。我可以重现这个问题。这似乎是Longhorn卷关闭/启动过程中的一个错误。
> > **RCA:RCA：**
> > ```
> > 1. Before a new attachment, Longhorn tries to clean up the old TGT target with the same name.在创建新的附件之前，Longhorn会尝试清除同名的旧TGT目标。
> > 
> > 2. Deleting the old TGT target means calling the function [DeleteTarget](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L230). Within this function, somehow [UnbindInitiator](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L236) function call succeeded (`ACL information` becomes empty) but then there is a transient error in [the rest of the shutdown flow](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L240-L258).删除旧的TGT目标意味着调用函数[DeleteTarget](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L230)。在此函数中，[UnbindInitiator](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L236)函数调用成功（`ACL information`变为空），但随后在关闭流的其余部分中出现暂时性错误。
> > 
> > 3. Because the first attachment failed, Longhorn retries the 2nd time. However, since the `ACL information` is already empty, [UnbindInitiator](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L236) function call always fails. This prevents the cleanup which then prevents the 2nd attachment. This cycle repeated again and again由于第一次连接失败，Longhorn重试第二次。但是，由于`ACL information`已经为空，因此[UnbindInitiator](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/vendor/github.com/longhorn/go-iscsi-helper/iscsidev/iscsi.go#L236)函数调用总是失败。这阻止了清理，然后阻止了第二次附接。这样的循环周而复始
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Reproduce steps:重现步骤：**
> > ```
> > 1. Create a Longhorn volume, `testvol`创建Longhorn卷，`testvol`
> > 
> > 2. Attach the Longhorn volume to a node, say `node-1`将Longhorn卷连接到一个节点，例如`node-1`
> > 
> > 3. Find the instance manager e pod on `node-1`在`node-1`上找到实例管理器e pod
> > 
> > 4. kubectl exec into the above instance manager e podkubectl exec到上面的实例管理器e pod中
> > 
> > 5. List all the targets:列出所有目标：
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > root@instance-manager-e-3382c653:/# tgtadm --lld iscsi --op show --mode target
> > Target 1: iqn.2019-10.io.longhorn:testvol
> >     System information:
> >         Driver: iscsi
> >         State: ready
> >     I_T nexus information:
> >         I_T nexus: 1
> >             Initiator: iqn.1993-08.org.debian:01:5e999e2fae73 alias: phan-v190-pool2-66ea5213-hjpfg
> >             Connection: 0
> >                 IP Address: 164.92.123.217
> >     LUN information:
> >         LUN: 0
> >             Type: controller
> >             SCSI ID: IET     00010000
> >             SCSI SN: beaf10
> >             Size: 0 MB, Block size: 1
> >             Online: Yes
> >             Removable media: No
> >             Prevent removal: No
> >             Readonly: No
> >             SWP: No
> >             Thin-provisioning: No
> >             Backing store type: null
> >             Backing store path: None
> >             Backing store flags: 
> >         LUN: 1
> >             Type: disk
> >             SCSI ID: IET     00010001
> >             SCSI SN: beaf11
> >             Size: 5369 MB, Block size: 512
> >             Online: Yes
> >             Removable media: No
> >             Prevent removal: No
> >             Readonly: No
> >             SWP: No
> >             Thin-provisioning: No
> >             Backing store type: longhorn
> >             Backing store path: /var/run/longhorn-testvol.sock
> >             Backing store flags: 
> >     Account information:
> >     ACL information:
> >         ALL
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 6. Manually unbind the initiator from the access control list (which is a part of the shutdown flow)手动解除启动器与访问控制列表的绑定（这是关闭流的一部分）
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > root@instance-manager-e-3382c653:/# tgtadm --lld iscsi --op unbind --mode target --tid 1 -I ALL
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 7. List all the targets again, notice that `ACL information`  is empty this time再次列出所有目标，注意这次`ACL information`为空
> > 
> > 8. If we try to unbind again with empty `ACL information` , we will always get error:如果我们再次尝试使用空的`ACL information`解除绑定，我们总是会得到错误：
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > root@instance-manager-e-3382c653:/# tgtadm --lld iscsi --op unbind --mode target --tid 1 -I ALL
> > tgtadm: this access control rule does not exist
> > root@instance-manager-e-3382c653:/# echo $?
> > 22
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 9. Detach the volume分离卷
> > 
> > 10. Attach the volume.连接卷。
> > 
> > 11. Observe that the volume is stuck in attaching/detaching loop. Same as what customers experiencing:观察体积卡在连接/分离环中。与客户体验相同：
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > [instance-manager-e-3382c653] [testvol-e-7c714976] time="2022-11-29T20:34:16Z" level=info msg="Shutdown SCSI target iqn.2019-10.io.longhorn:testvol"
> > [instance-manager-e-3382c653] tgtd: target_mgmt(147) Failed to unbind by address: ALL
> > [instance-manager-e-3382c653] [testvol-e-7c714976] time="2022-11-29T20:34:16Z" level=error msg="Failed to init frontend: device testvol: fail to delete target iqn.2019-10.io.longhorn:testvol"
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Workaround:解决方法：**
> > ```
> > 1. Note down the current attaching NodeID记下当前附加的NodeID
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > kubectl get volumes.longhorn.io <volume-name> -n longhorn-system
> > # note down the spec.nodeID
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 2. Detach the volume by scaling down the workload pods that are using the volume通过缩小正在使用卷的工作负载Pod来分离卷
> > 
> > 3. kubectl exec into the instance manager e pod on the `spec.nodeID` abovekubectl exec到上面`spec.nodeID`的实例管理器e pod中
> > 
> > 4. Find the TGT target id corresponding to the volume:查找与卷对应的TGT目标ID：
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > root@instance-manager-e-3382c653:/# tgtadm --lld iscsi --op show --mode target
> > Target 1: iqn.2019-10.io.longhorn:testvol
> >     System information:
> >         Driver: iscsi
> >         State: ready
> > ...
> > # in this case, the TGT target id is 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 5. Try to bind the missing initiator:尝试绑定缺少的启动器：
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > tgtadm --lld iscsi --op bind --mode target --tid <TGT-TARGET-ID-FROM_ABOVE-STEP> -I ALL
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 6. Scale up the workload again. Volume should be able to attach再次扩展工作负载。卷应该能够连接
> > ```
> 
> I used the tgtadm -- lld iscsi -- op bind -- mode target -- tid 7- I ALL command to add ACL information, and then restarted the container. However, I still couldn't mount the volume or was in an infinite loop of connection separation

Can I directly delete this tgt ID information？

**Comment by ngoeddel-openi** [comment]
Why is this closed? The bug still persists.
