### ISSUE TITLE
Expose warning for too many snapshots

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#496]
Normally the user shouldn't have more than 100 snapshots. The engine limit is 250 but it definitely shouldn't reach to that number. Normally it's something wrong if more than 100 snapshots exist, e.g. recurring cleanup routine didn't clean up as expected. We need to warn the user about the issue before it becomes too serious, e.g. hitting 250 and replica rebuilt can be paused.

Design:
1. It should be added as a volume condition.
2. Engine controller should update the engine CRD about how many snapshots it had.
3. Volume controller should pick up that number from engine controller and reflect it as a volume condition.

**Comment by yasker** [comment]
Manager engine controller already have a list of snapshot available now, see https://github.com/longhorn/longhorn-manager/blob/master/types/resource.go#L182

**Comment by boknowswiki** [comment]
@yasker , do you think it will better if we expose this 'snapshots warning threshold' as a setting? Since different user may prefer different threshold, and we can set 100 as default? Thanks.

**Comment by yasker** [comment]
I don't see why the user wants to have more than 100 snapshots, and we can only have 255 snapshots in theory. We can add that later if needed.

**Comment by boknowswiki** [comment]
Test case, in my test case, I was setting the threshold to 5 in the code. After verify the condition got set to 'True' after 5 snapshots, I changed it back to 100. In the real world test, we may need to have a script to call take snapshot 100 times.

1. Create a volume and attached to a node.
2. Writing data to the volume and take 5 snapshots.
3. 'TooManySnapshots' Condition is set to 'True'.
4. Delete one snapshots, 'TooManySnapshots' Condition is set to 'False'.
5. Delete the volume.

**Comment by boknowswiki** [comment]
@smallteeths , from the UI side,  I think we need to have the following changes:

1. When 'TooManySnapshots' Condition is set to 'False', doesn't need to put red color on it, no color is good.
2. 'TooManySnapshots' Condition is set to 'True', need to put red color on it to warn the user about this.

Please let me know if there is any question. Thanks.

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master -10/30/2020 and longhorn-ui image -  wangsiye/longhorn-ui:4ea66dd

Validation - **Pass**

<img width="774" alt="Screen Shot 2020-10-30 at 6 09 12 PM" src="https://user-images.githubusercontent.com/60111667/97767850-2ae96c00-1adc-11eb-8d2b-3aaa68d99c68.png">

**Comment by khushboo-rancher** [comment]
Verified with longhorn-master - 11/2/2020

Validation - **Pass**

When the snapshot count has not crossed the threshold 100, UI appears as below.
<img width="588" alt="Screen Shot 2020-11-02 at 10 34 26 AM" src="https://user-images.githubusercontent.com/60111667/97906846-2fd73700-1cf9-11eb-9637-d09f41cc7210.png">

With more than 100 snapshots, UI appears as below.
<img width="590" alt="Screen Shot 2020-11-02 at 10 35 36 AM" src="https://user-images.githubusercontent.com/60111667/97906890-441b3400-1cf9-11eb-8c98-87a521f62b0b.png">
