### ISSUE TITLE
[BUG] Failed to create a replenished replica process because of the newly adding option

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4962]
## Describe the bug (🐛 if you encounter this issue)

 Failed to create a replenished replica process because of the newly adding option

## To Reproduce

1. Set up a LH v1.3.2 with 3 worker nodes
2. Create one volume with 3 replicas
3. Deploy longhorn/longhorn/example/pod_with_pvc.yaml
4. Upgrade LH to master-head branch
5. Delete one of the replicas
6. LH failed to create a replenished replica process because of the newly adding option
```
time="2022-11-29T13:31:59Z" level=warning msg="pvc-95002f0b-f8ba-4e93-8e72-d3ce6aa5d348-r-ad474f9a:    "
time="2022-11-29T13:31:59Z" level=warning msg="pvc-95002f0b-f8ba-4e93-8e72-d3ce6aa5d348-r-ad474f9a: time=\"2022-11-29T13:31:58Z\" level=fatal msg=\"Error when executing command: flag provided but not defined: -volume-name\""
```

## Expected behavior

Create a replica sucessfully

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by khushboo-rancher** [comment]
@roger-ryao is already working on this scenario - https://github.com/longhorn/longhorn-tests/pull/1168, The PR is in review status.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 5f76d4f) with [the test steps](https://github.com/longhorn/longhorn/issues/4962#issue-1468347141). 

After upgraded and randomly deleted replicas of a volume, the replica rebuilding can be triggered and completed, and the volume recovers to healthy state without problems.
