### ISSUE TITLE
[Question] Need to clean up failed deployment

### ISSUE THREAD

**Issue by junkiebev** [longhorn/longhorn#498]
I had a deployment, done through the app catalog, in Rancher v2.2.2, fail on me. I deleted it but it seems to have left api resources and maybe some other things. This, I believe, is resulting in the namespace being stuck `Terminating` with a `kubernetes` finalizer.

Is there some cleanup script which would remove all artifacts? Can I just run the one in the catalog's chart somehow?

**Comment by yasker** [comment]
The uninstallation tool has been improved to help with this situation. Though if the app was uninstalled using Rancher App page, this should be done automatically.

Some instructions on how to delete stuck namespace is at https://github.com/rancher/longhorn/blob/master/docs/upgrade.md#delete-crds-in-different-namespace

Alternative, if you want to give the unreleased uninstallation tool at try, use:
```
kubectl create -f https://raw.githubusercontent.com/rancher/longhorn-manager/master/deploy/uninstall/uninstall.yaml
```

See the full document (also unreleased) at https://github.com/rancher/longhorn/tree/v0.5.0#uninstall-longhorn
