### ISSUE TITLE
[IMPROVEMENT] Avoid the accident deletion of longhorn settings

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4984]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Longhorn settings can be deleted with the kubectl command. Deleting settings should be prohibited by the validating webhook for avoiding any potential errors in the controllers.

**Comment by innobead** [comment]
@derekbit What's the correct behavior? The deleted settings will be recovered from the setting config map?

**Comment by derekbit** [comment]
No, the settings cannot be recovered from confimap because
1. Some settings such as `default-engine-image` ae created when starting the longhorn-manager rather than reading from the configmap
2. The configmap controller resync period is 0 (infinite), so the recovery is not possible.

Although resync period is not 0, the error in 1 still lead to the failure of the recovery.

**Comment by innobead** [comment]
The workaround for users if this accident happens is just to recreate the deleted setting resource.

**Comment by ejweber** [comment]
So, does the behavior below meet our needs?

1. The validating webhook denies all delete operations for settings it knows about (a.k.a settings for this version of Longhorn).
1. The validating webhook allows delete operations for settings it doesn't know about (a.k.a. settings for the previous version of Longhorn).
1. Settings for this version of Longhorn simply cannot be deleted as long as the Longhorn validatingwebhookconfiguration is active.

It seems 2 is important for upgrades. We generally expect to be able to delete outdated settings during the upgrade process. However, we need to be sure the new version of the webhook is running before we walk the upgrade path.

**Comment by roger-ryao** [comment]
**Verified on master-head 20230919**

- longhorn master-head https://github.com/longhorn/longhorn/commit/963ccf68eb95286711a44a2e537c9f306eedd29e
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/714bc966d5e271e9f1159b9266578da7f8a27600

**The test steps**

1. Refer to the issue discussion at https://github.com/longhorn/longhorn/issues/4984#issuecomment-1723785518

**Result Passed**

1. Attempt to delete the `current-longhorn-version` setting using the following command:
```bash
kubectl -n longhorn-system delete setting current-longhorn-version
```
Expect an error message indicating that `The request is invalid: metadata.name: setting current-longhorn-version can be modified but not deleted`

2. Delete the `longhorn-webhook-validator` using the command:
```bash
kubectl delete validatingwebhookconfiguration longhorn-webhook-validator
```

3. Create a fake setting named fake-setting using the following command:

```bash
kubectl apply -f - <<EOF
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: fake-setting
  namespace: longhorn-system
value: "true"
EOF

```
NOTE : If we didn't delete `longhorn-webhook-validator` Expect an error message indicating that `The request is invalid: : failed to set the setting fake-setting with invalid value true: value true of settings fake-setting is invalid: setting fake-setting is not supported`

4.  Redeploy Longhorn and restart manager pods to re-enable the webhook:
```bash
k apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
kubectl -n longhorn-system delete pod -l app=longhorn-manager
```
