### ISSUE TITLE
[IMPROVEMENT] Allow users to change volume.spec.snapshotDataIntegrity on UI

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#4994]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Snapshot hash/check supports per-volume settings, so we can allow users to change volume.spec.snapshotDataIntegrity on UI.

Add `Update Snapshot Data Integrity`. The options can be "ignored", "disabled", "enabled" and "fast-check".

![image](https://user-images.githubusercontent.com/12527233/205593662-6c074551-f221-43d7-b782-32dda2de5e38.png)

## Additional context

https://github.com/longhorn/longhorn/issues/4210
https://github.com/longhorn/longhorn/issues/3198

**Comment by innobead** [comment]
@derekbit let's mention the original issue in the description as well to make the correlation.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager fe05edb, longhorn-ui a2c2f17). There is `Update Snapshot Data Integrity` options for each volume on the ui, and it can control whether the checksum file is generated without problem.

**Comment by innobead** [comment]
For @longhorn/qa for closing issues of milestone 1.4.0 after RC1 out, please verify in 1.4.x branch image instead.

**Comment by innobead** [comment]
@yangchiu Could you verify 1.4.x-head instead? Thanks.

**Comment by yangchiu** [comment]
Verified passed on v1.4.x-head (longhorn-manager 6d93e2d, longhorn-ui 2f43f07). There is `Update Snapshot Data Integrity` option for each volume on the ui, and it can control whether the checksum file is generated without problem.
