### ISSUE TITLE
[TASK] Remove a deprecated feature `disable-replica-rebuild` from longhorn-manager

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4997]
## What's the task? Please describe

`disable-replica-rebuild` has been deprecated for several feature releases. For any deprecated feature, it will only exist for one feature release, so it should be removed from the following feature release. 

## Additional context

N/A

cc @PhanLe1010

**Comment by weizhe0422** [comment]
I found that this setting is still be used [here](
https://github.com/longhorn/longhorn-manager/blob/4e7b9584a7ca258e8f1f977272a6a38ae8b0a5bb/upgrade/v120to121/upgrade.go#L34-L49) when upgrading from 1.2.0 to 1.2.1, and its default setting value is `false`.

**Comment by innobead** [comment]
ref: #5131

**Comment by ejweber** [comment]
- [x] Remove all traces from longhorn repo
- [x] Regenerate longhorn.yaml
- [x] Remove all traces from longhorn-manager repo (left local version in upgrade/v120to121 for now)
- [x] Check for traces in longhorn-tests repo (none found)
- [x] Run standard integration tests (used "-m coretest")
- [x] Run upgrade integration tests (upgraded from v1.4.1 and used "-m coretest"
- [x] Make changes to website

**Comment by ejweber** [comment]
Passed core tests: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3776/.
Passed upgrade tests: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3778/.

**Comment by yangchiu** [comment]
> - All existing integration and upgrade integration tests should pass.

This item is pending by https://github.com/longhorn/longhorn-tests/pull/1357. Currently upgrade test always fail on master-head.

**Comment by chriscchien** [comment]
Verified **pass** in longhon master(longhorn-manager `eb26ae`)

Setting `grep disable-replica-rebuild` no longer exist in below install scenario
- Fresh install longhorn master-head
- Upgrade longhorn from v1.4.2 to master-head
- Upgrade longhorn from v1.3.3 to v1.4.2 to master-head

Daily regression did not see cascading failure related to this deprecated setting value
- master-head build [497](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/497/)
- upgrade test pipeline build [478](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/478/#showFailuresLink)
- 2 stage upgrade build [187](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-2-stage-upgrade-tests-sles-amd64/187/)
