### ISSUE TITLE
[FEATURE] BackingImage Management via VolumeSnapshot

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5005]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

By leveraging CSI VolumeSnapshot protocol for backing image management (create/delete), backing-image based volume backup & restore by regarding each backing image as the source of a volume (ex: VolumeSnapshot with prebuilt VolumeSnapshotContent). 

When doing backing-image based volume snapshot, it can support in-cluster snapshot (another Backing Image) or out-of-cluster snapshot backup. Both all of them can support COW over each relative base image for delta data transfer for better space efficiency.

The goal is to use CSI snapshot as  the unified interface for users to do backing image management, backing-image based volume management and backup/restore.

## Describe the solution you'd like

CSI snapshot for backing image management, BI-based volume snapshot, backup & restore

## Additional context

#4165 

cc @shuo-wu @FrankYang0529 @ChanYiLin

**Comment by chriscchien** [comment]
HI @ChanYiLin ,

From test [plan](https://github.com/longhorn/longhorn/blob/master/enhancements/20230417-extend-csi-snapshot-to-support-backingimage.md#scenerios-4-restore-on-demand-provisioning-backingimage) scenerios 4: Restore on-demand provisioning BackingImage, type=export-from-volume, success scenario
Volume name in step a is `test-vol` not consistent with the name in yaml content in step b `vol-export-src`, could you update it or make the volume name not static in yaml? Thank you.

```
Events:
  Type     Reason                Age                   From                                                                                      Message
  ----     ------                ----                  ----                                                                                      -------
  Warning  ProvisioningFailed    6m55s                 driver.longhorn.io_csi-provisioner-6df8547696-fxg6n_709f40d7-dffe-4ff4-9186-5712c885324a  failed to provision volume with StorageClass "longhorn": rpc error: code = InvalidArgument desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=unable to create backing image test-bi from source type export-from-volume with parameters map[export-type:qcow2 volume-name:vol-export-src]: admission webhook "validator.longhorn.io" denied the request: failed to get volume vol-export-src before exporting backing image, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/backingimages]
  Normal   ExternalProvisioning  57s (x26 over 6m55s)  persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
  Normal   Provisioning          32s (x10 over 6m55s)  driver.longhorn.io_csi-provisioner-6df8547696-fxg6n_709f40d7-dffe-4ff4-9186-5712c885324a  External provisioner is provisioning volume for claim "default/test-restore-on-demand-backing"
  Warning  ProvisioningFailed    32s (x9 over 6m54s)   driver.longhorn.io_csi-provisioner-6df8547696-fxg6n_709f40d7-dffe-4ff4-9186-5712c885324a  failed to provision volume with StorageClass "longhorn": rpc error: code = InvalidArgument desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to create backing image test-bi from source type export-from-volume with parameters map[export-type:qcow2 volume-name:vol-export-src]: admission webhook "validator.longhorn.io" denied the request: failed to get volume vol-export-src before exporting backing image] from [http://longhorn-backend:9500/v1/backingimages]
```

**Comment by chriscchien** [comment]
Hi @ChanYiLin , regarding test steps, I have some confuse and update the test steps [here](https://github.com/longhorn/longhorn/pull/5912), could you help confirm then I can continue testing, thank you

**Comment by chriscchien** [comment]
Hi @ChanYiLin, 

Regarding to failed case in "Scenerios 4: Restore on-demand provisioning BackingImage", type `export-from-volume`, following the test [steps](https://github.com/longhorn/longhorn/blob/master/enhancements/20230417-extend-csi-snapshot-to-support-backingimage.md#scenerios-4-restore-on-demand-provisioning-backingimage), the backingimage can be created when volume is in detach state, which does not match behavior described in test plan, wondering if I missed something, thank you.

```
root@ip-172-31-81-136:/home/ubuntu# k get volumes -A
NAMESPACE         NAME                                       STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE   AGE
longhorn-system   pvc-a762135c-9991-4176-8bfc-bca23db34a82   detached   unknown                  5368709120          5m16s
longhorn-system   test-vol                                   detached   unknown                  5368709120          12m
root@ip-172-31-81-136:/home/ubuntu# k get backingimages -A
NAMESPACE         NAME      UUID       SOURCETYPE           SIZE         AGE
longhorn-system   test-bi   641ffdc2   export-from-volume   5368709120   5m37s
```
[supportbundle_67e252b8-3e99-49ec-a0d9-ece01a39cde4_2023-05-12T03-39-11Z.zip](https://github.com/longhorn/longhorn/files/11458661/supportbundle_67e252b8-3e99-49ec-a0d9-ece01a39cde4_2023-05-12T03-39-11Z.zip)

**Comment by ChanYiLin** [comment]
Hi @chriscchien I have confirmed that when creating BackingImage from a Volume, it is okay for Volume to be in detached state
We will do auto attachment and detachment for volume to be exported to the BackingImage
ref: https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go#L2845

I will 
1. Remove the failed test case in the **test plan 4 - failed case**, 
2. Remove the check if volume is in attached state when creating VolumeSnapshot in longhorn-manager/csi
3.  remove **test plan 1 - failed case**

**Comment by ChanYiLin** [comment]
UPDATE PR:
- https://github.com/longhorn/longhorn-manager/pull/1900
- https://github.com/longhorn/longhorn/pull/5923

**Comment by chriscchien** [comment]
Verified **pass** in longhorn master(longhorn-manager `565d33`) with test [steps](https://github.com/longhorn/longhorn/blob/master/enhancements/20230417-extend-csi-snapshot-to-support-backingimage.md)
