### ISSUE TITLE
[TASK] Create a UI issue when the source issue with `require/ui` label

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5007]
## What's the task? Please describe

This issue auto creation is similar to `require/automation-e2e`. After creation, add the issue with labels `area/ui` and `kind/task` to the same milestone and assign it to @smallteeths (UI engineer).

## Describe the items of the task (DoD, definition of done) you'd like

- [ ] `item 1`

## Additional context

Add any other context or screenshots about the task request here.

**Comment by yangchiu** [comment]
Duplicated with https://github.com/longhorn/longhorn/issues/7278.
