### ISSUE TITLE
[IMPROVEMENT] Check the hostname of each node in environment_check.sh

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5012]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

One requirement of the RWX volume feature is the hostname of of each node should be unique because of the recovery backend. `environment_check.sh` needs to support the check of the uniqueness.

**Comment by innobead** [comment]
@derekbit Could you also mention this notice to https://longhorn.io/docs/1.4.0/deploy/important-notes/ and https://longhorn.io/docs/1.4.0/deploy/install/#installation-requirements?

**Comment by derekbit** [comment]
Yes. I will update this on the these pages.

**Comment by innobead** [comment]
ref: https://github.com/longhorn/website/pull/634
