### ISSUE TITLE
[FEATURE] Create longhorn-debug-tool container/cli for troubleshooting or environment check

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5013]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Besides environment_check.sh, need to have a debug tool CLI for issue troubleshooting (volume/snapshot metadata consistent between replica snapshots, identify the broken snapshot chain, etc), simulating issues (crash engine/replica process to see engine/replica recovery, etc), and environment check (runtime check or monitoring).

Users can deploy a debug tool container to execute all functions provided by the CLI.

## Describe the solution you'd like

A clear and concise description of what you want to happen

## Additional context

cc @longhorn/qa

**Comment by innobead** [comment]
Also found `environment_check.sh` is not obvious to use, so a single entry point for everything should be helpful for users.

**Comment by derekbit** [comment]
The scope of the ticket is too big. Let's create the corresponding tickets for the functionalities of longhorn/cli.
- https://github.com/longhorn/longhorn/issues/9101
- https://github.com/longhorn/longhorn/issues/9102
