### ISSUE TITLE
[REFACTOR] Reformat logs consistently in each component

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5015]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Currently, logs in each longhorn component are quite messy with different letter cases, inconsistent message format (like starting with verb or noun, etc), string format with an error instead of wrapping, etc.  

Need to have a consistent way to define all logs for better troubleshooting.

## Describe the solution you'd like

- For log messages, need to try starting with a capitalized Verb word with different tenses (V+ing, V+ed). If there is an error, needs to wrap in the logger instead of string interpolation in the message directly.
- For errors, need to try starting with a lowercase Verb word with different tenses (V+ing, V+ed). If there is an error, need to wrap in the error instead of string interpolation in the message directly.
- Instead of just changing the format, need to review if any current log or error is not right as well.

---
## Note
- [Convention Page](https://github.com/longhorn/longhorn/wiki/Logging-Convention)

**Comment by ChanYiLin** [comment]
Hi @innobead 
I found most of the **error logs** in longhorn start with `uppercase` Verb
Do we have convention to use `lowercase` verb?

**Comment by innobead** [comment]
> Hi @innobead I found most of the **error logs** in longhorn start with `uppercase` Verb Do we have convention to use `lowercase` verb?
> 
> I am afraid if we don't have convention or guidance, after this issue, there might still have some wrong format in the future

Exactly, we need to ensure the convention. For logging, use uppercase, but for error message, use lowercase. This is a kind of passive convention but probably could leverage some tools like golint to ensure these conventions later.

**Comment by ChanYiLin** [comment]
Got it 
Let's apply the convention to PR review so the format can be consistent

**Comment by ChanYiLin** [comment]
Another issue is that I found some of the developers encourage
`fmt.Errorf("... %w", err)` instead of `errors.Wrapf(err, "...")`

https://stackoverflow.com/questions/61933650/whats-the-difference-between-errors-wrapf-errors-errorf-and-fmt-errorf

WDYT?

**Comment by innobead** [comment]
Thanks for the info :+1: . Just captured some important notes below. I am fine to switch to using `fmt.Errorf`, just need to make the consistency. 

> - If you want stack traces in your errors, use github.com/pkg/errors.Errorf to wrap errors.
> - If you don't care about stack traces, use fmt.Errorf from the standard library.
> - Never use errors.Wrapf any more. It's for backward compatibility.
> - One difference between Wrapf(err, "") and Errorf("%w", err) is that wrapf would return nil if err is nil, but errorf would return an error regardless.

**Comment by ChanYiLin** [comment]
handle the issue together in #5888
