### ISSUE TITLE
[IMPROVEMENT] Disable `Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly` for RWX volumes

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5017]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Longhorn has a feature `Automatically Delete Workload Pod when Volume is Detached Unexpectedly`, and it is enabled by default. For a RWX volume, when the volume is unexpectedly detached, it will be recreated on another node. Additionally, the NFS sever already has a dedicated recovery backend. Thus, there is no need to delete the workload pods using the volume, and IO should continue after the new volume is started.

**Comment by innobead** [comment]
So this is specific for RWX only. I feel we need to include it in 1.4.0? WDYT?

**Comment by derekbit** [comment]
Yes

**Comment by derekbit** [comment]
> So this is specific for RWX only. I feel we need to include it in 1.4.0? WDYT?

Yes. Should be in v1.4.0
Waiting for e2e https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2651/

**Comment by innobead** [comment]
I see. Also I know you would like to have a setting for fallback purpose. It's quite weird.

But I do feel this setting should originally be for RWO, because the volume/engine is next to the workload.

**Comment by derekbit** [comment]
Agree. Then, we can keep the current PR and see if there is any feedback from users. WDYT?

**Comment by innobead** [comment]
Sounds good. BTW, could you check the comment which introduced this setting to see the context of the feature? See if this was actually a concern for RWO or also RWX included.

**Comment by shuo-wu** [comment]
That setting is mainly for RWO volumes. I don't think we need a separate setting for RWX volumes after the improvement.
We can see if there are any community users/customers requesting it in the future.

**Comment by innobead** [comment]
Then let's do this improvement ;)

**Comment by derekbit** [comment]
e2e afte updating `test_rwx.py::test_rwx_delete_share_manager_pod updated`

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2657/

**Comment by chriscchien** [comment]
Verified in longhorn master `13ac2a` with test [steps](https://github.com/longhorn/longhorn-tests/pull/1221)
Result **Pass**

1. After delete share-manager pod then wait share-manager pod work again, write extra data into statesfulset pod mount point, those new added data can be seen in path `/export/'<pv_name>` in share-manager pod.
2. Test case [passed](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/334/testReport/tests/test_rwx/test_rwx_delete_share_manager_pod/) in master-head pipeline.
