### ISSUE TITLE
[IMPROVEMENT] Enable fast replica rebuilding by default

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5023]
## What's the task? Please describe

Enable fast replica rebuilding by default.
- Snapshot Data Integrity: fast-check
- Immediate Snapshot Data Integrity Check After Creating a Snapshot: false
- Fast Replica Rebuild Enabled: true

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

Add any other context or screenshots about the task request here.

**Comment by roger-ryao** [comment]
**Verified on master-head 20221209**

- longhorn master-head ([f30875a](https://github.com/longhorn/longhorn/commit/f30875aa58f0e64783cbe7bbd623b3c1e5ba030a)) 
- longhorn-manager master-head ([301e1e0](https://github.com/longhorn/longhorn-manager/commit/301e1e07160177f63a3e8c13fd98f24f0c79e13c)) 


**The test steps**

[Ref #5023 (To Reproduce)](https://github.com/longhorn/longhorn/issues/5023#issue-1483615079)

**Result Passed**
![Screenshot_20221209_154444](https://user-images.githubusercontent.com/104337648/206653455-cdec5313-a013-4878-9c1f-63f430bdd8ec.png)

![Screenshot_20221209_154514](https://user-images.githubusercontent.com/104337648/206653438-92db502a-88a6-4afe-bf77-027c34c50633.png)
