### ISSUE TITLE
[IMPROVEMENT] Remove system managed component image settings 

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5028]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Because we will adopt #5024 , need to remove the settings about the default image for system-managed components. 

![image](https://user-images.githubusercontent.com/899492/206612029-077412ef-ed57-4f11-a510-d902e37f4f4d.png)

**Comment by chriscchien** [comment]
Verified **pass** in longhorn master(longhorn-manager `c759f0`) with test [steps](https://github.com/longhorn/longhorn/issues/5028#issuecomment-1550660282)

In fresh install of v1.5.0-dev or upgrade from v1.4.2 to v1.5.0-dev, below options removed from UI.
- Default Instance Manager Image
- Default Share Manager Image
- Default Backing Image Manager Image

In CLI, can see below settings still exist, those values can be modified but already have https://github.com/longhorn/longhorn/issues/5989 for tracking
- `default-instance-manager-image `
- `default-backing-image-manager-image`
- ~`default-share-manager-image`~(no longer exist)

Also, in daily regression, did not observe fail case related to those deprecated value
- [mater branch pipeline](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/501/) 
- [upgrade](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/481/#showFailuresLink)
- [2 stage upgrade](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-2-stage-upgrade-tests-sles-amd64/190/)
