### ISSUE TITLE
[QUESTION] How to Repair XFS RWX Volumes

### ISSUE THREAD

**Issue by InoryS** [longhorn/longhorn#5037]
## Question
> Suggest to use https://github.com/longhorn/longhorn/discussions to ask questions.
> I know but I suspect it might have something to do with a bug or enhanced error reporting for RWX volumes. 

I created RWX volumes and PVCs using XFS through the Longhorn UI.
The pod was successfully created and populated with some data, then I deleted the pod and used
```
spec:
   securityContext:
      fsGroup: 50000
      fsGroupChangePolicy: "OnRootMismatch"
```
Then the pod is never ready,and longhorn useing high cpu,  the pod description says: 

```
Events:
  Type     Reason                  Age                   From                     Message
  ----     ------                  ----                  ----                     -------
  Normal   Scheduled               8m55s                 default-scheduler        Successfully assigned /static-temp to server2
  Normal   SuccessfulAttachVolume  8m45s                 attachdetach-controller  AttachVolume.Attach succeeded for volume "web-data"
  Warning  FailedMount             30s (x12 over 8m45s)  kubelet                  MountVolume.MountDevice failed for volume "web-data" : rpc error: code = Aborted desc = volume -web-data share not yet available
  Warning  FailedMount             5s (x4 over 6m53s)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[web-data], unattached volumes=[web-data kube-api-access-g8njc]: timed out waiting for the condition
```
The logs are perfectly fine in the UI, and the volume status is also completely fine, I'm a bit lost here.

Then `kubectl get pods -n longhorn-system -o wide` tole me `share-manager-web-data                    0/1     Error     0               4s`

So I did `kubectl logs -n longhorn-system share-manager-web-data` and get this:
```
time="2022-12-09T12:54:28Z" level=info msg="starting RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
time="2022-12-09T12:54:28Z" level=info msg="ending RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
time="2022-12-09T12:54:28Z" level=debug msg="volume web-data device /dev/longhorn/web-data contains filesystem of format xfs" encrypted=false volume=web-data
E1209 12:54:30.295449       1 mount_linux.go:195] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t xfs -o defaults /dev/longhorn/web-data /export/web-data
Output: mount: /export/web-data: cannot mount; probably corrupted filesystem on /dev/longhorn/web-data.

time="2022-12-09T12:54:30Z" level=warning msg="failed to mount volume" encrypted=false error="mount failed: exit status 32\nMounting command: mount\nMounting arguments: -t xfs -o defaults /dev/longhorn/web-data /export/web-data\nOutput: mount: /export/web-data: cannot mount; probably corrupted filesystem on /dev/longhorn/web-data.\n" volume=web-data
W1209 12:54:30.326291       1 mount_helper_common.go:133] Warning: "/export/web-data" is not a mountpoint, deleting
time="2022-12-09T12:54:30Z" level=debug msg="device /dev/mapper/web-data is not an active LUKS device: failed to run cryptsetup args: [status web-data] output:  error: exit status 4"
time="2022-12-09T12:54:30Z" level=fatal msg="Error running start command: mount failed: exit status 32\nMounting command: mount\nMounting arguments: -t xfs -o defaults /dev/longhorn/web-data /export/web-data\nOutput: mount: /export/web-data: cannot mount; probably corrupted filesystem on /dev/longhorn/web-data.\n."
```

I can see the block device on the host when the volume is mounted to the pod

```
xfs_info /dev/longhorn/web-data
meta-data=/dev/longhorn/web-data isize=512    agcount=4, agsize=1310720 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=0, rmapbt=0
         =                       reflink=0    bigtime=0 inobtcount=0
data     =                       bsize=4096   blocks=5242880, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=4096   blocks=2560, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0

```

I cannot run xfs_repair :

```
xfs_repair /dev/longhorn/web-data
Phase 1 - find and verify superblock...
Phase 2 - using internal log
        - zero log...
ERROR: The filesystem has valuable metadata changes in a log which needs to
be replayed.  Mount the filesystem to replay the log, and unmount it before
re-running xfs_repair.  If you are unable to mount the filesystem, then use
the -L option to destroy the log and attempt a repair.
Note that destroying the log may cause corruption -- please attempt a mount
of the filesystem before doing this.
```

If I delete the POD, and then try to attach to host, this won't work because RWX volumes cannot cancel maintenance mode, which as far as I know is equivalent to `spec.disabledFrontend = true`.

So how can I fix this volume, thanks.

## Environment

 - Longhorn version: v1.3.2
 - Kubernetes version: v1.24.8
 - Node config
   - OS type and version: RHEL 8.6
   - CPU per node: 12
   - Memory per node: 128G
   - Disk type: SSD
   - Network bandwidth and latency between the nodes: 10M
 - Underlying Infrastructure :Baremetal

**Comment by derekbit** [comment]
If you want to repair RWX volume, you can
1. detach the volume
2. change the volume to a RWO volume
Then, fix the volume https://longhorn.io/kb/troubleshooting-volume-filesystem-corruption/#solution

BTW, I'm curious why you volume is corrupted. Any node abnormal shutdown or unstable network?
If it is reproducile, can you provide us the steps to reproduce?

**Comment by InoryS** [comment]
> 1. Detach the volume
> 2. Change the volume to a RWO volume

I have read the docs, but no UI don't allow me change volume access type.
![image](https://user-images.githubusercontent.com/101243352/206888394-3ec70a93-98ea-4ec3-8608-5cdad99d41d4.png)





> BTW, I'm curious why you volume is corrupted. Any node abnormal shutdown or unstable network? If it is reproducile, can you provide us the steps to reproduce?

I'm also confused, I'm just testing data import, so I mounted a volume to import some data, created and deleted pods several times. Then I use fsgroup to change user group, it stuck in pod creation.
The nodes and network are completely normal, and the display in the UI is also completely normal.

**Comment by derekbit** [comment]
@InoryS 
Thank you for the update. Let's keep the ticket opened. We will update the KB.

**Comment by innobead** [comment]
The doc has been updated.

**Comment by InoryS** [comment]
Maybe you should state the log issue.
