### ISSUE TITLE
UI: Present an alternative form of recurring scheduling setup

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#504]
Users may want to set more complex schedulings, e.g. backup for every 4 hours.

We have a parser in the Rancher UI can show people what they've chosen for the cron job. We can reuse the logic (or find some other component to do it for us)

<img width="1320" alt="Screen Shot 2019-04-29 at 2 04 08 PM" src="https://user-images.githubusercontent.com/3344618/56926955-c1704380-6a87-11e9-8339-f7ad9558bffc.png">

**Comment by yasker** [comment]
@smallteeths 

- [ ] Edit Cron. `Cron` tab doesn't reflect the current setting.

**Comment by meldafrawi** [comment]
**Longhorn Version:** fc8ba32

**Comment by meldafrawi** [comment]
if cron syntax was wrong, and `save` failed to pass API validation, cron still have the wrong content, and it disappears when trying to `edit`

**Comment by yasker** [comment]
The order of some sequences are wrong too:

every X starting at hour n means, x is the interval, n is the starting time
so 
```
Every 3 minutes(s) starting at minutes 5
```
should mean `5, 8, 11,  etc`

but it’s `Every 3, 8, 13, 18, 23, 28, 33, 38, 43, 48, 53 and 58th minute past every hour`

**Comment by meldafrawi** [comment]
Scheduling recurring backups and snapshots can be done by either:

1. Specifying schedules using crontab format  
![Screenshot from 2019-07-09 22-06-04](https://user-images.githubusercontent.com/18232258/60919436-fd006880-a295-11e9-83ab-c02ec1cc0e60.png)


2. Generate schedules using `Generate Cron` tab
![Screenshot from 2019-07-09 22-09-30](https://user-images.githubusercontent.com/18232258/60919550-5b2d4b80-a296-11e9-8d36-f96c98d83b0f.png)
