### ISSUE TITLE
UI - Setting snapshot/backup configuration when creating a volume

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#505]
**As a UI user, I want to be able to set snapshot/backup configurations while creating Longhorn volume.**
‏
![Screenshot from 2019-04-30 01-19-26](https://user-images.githubusercontent.com/18232258/56932926-05923100-6ae6-11e9-8dc8-a424292796b3.png)

**Comment by yasker** [comment]
We should able to add an `advanced` option while creating the volume, which includes:
1. Base image option
2. Frontend selection
3. Recurring snapshot/backup

**Comment by smallteeths** [comment]
@meldafrawi I tried add an advanced option while creating the volume, But it doesn't look very friendly.
![Jietu20190502-125021](https://user-images.githubusercontent.com/27733391/57057316-4fdc0380-6cda-11e9-97ba-9988bc6663ba.jpg)

**Comment by yasker** [comment]
Remove the blocker. Move this issue to the next release.

**Comment by yasker** [comment]
We're going to use https://github.com/longhorn/longhorn/issues/467 to address this issue.
