### ISSUE TITLE
[IMPROVEMENT] Upgrade tcmalloc in longhorn-engine

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5050]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The tcmalloc in longhorn is too old. The task is to upgrade tcmalloc in longhorn-engine for avoiding any bugs and platform compatibility issues from the tcmalloc.

**Comment by derekbit** [comment]
e2e
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2676/console

**Comment by innobead** [comment]
Please remember to backport to 1.4.x which is for the upcoming 1.4.0 release.

**Comment by innobead** [comment]
Let's just follow up with the daily regression. 

cc @longhorn/qa
