### ISSUE TITLE
[BUG] System backup should validate empty backup target

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#5055]
## Describe the bug (🐛 if you encounter this issue)

Create a system backup when the backup target is empty succeed.

## To Reproduce

1. Set the backup target empty.
2. Create a system backup.
3. System backup created.

## Expected behavior

Should show an error.

## Log or Support bundle

`N/A`

## Environment

`N/A`

## Additional context

The issue was raised while testing for https://github.com/longhorn/longhorn/issues/5047.

**Comment by khushboo-rancher** [comment]
UI should also show the error as backup target is empty as it shows for volume backup creation.

**Comment by khushboo-rancher** [comment]
Validation - **Pass** on v1.4.x-head

<img width="1261" alt="Screenshot 2022-12-15 at 2 49 11 PM" src="https://user-images.githubusercontent.com/60111667/207984343-8d1bda6a-9c29-451c-a388-307e0b5187dd.png">
<img width="1277" alt="Screenshot 2022-12-15 at 2 53 23 PM" src="https://user-images.githubusercontent.com/60111667/207984351-4df18743-ff8e-4cc1-a08a-a2239bd47683.png">
