### ISSUE TITLE
[IMPROVEMENT] UI show error when backup target is empty for system backup

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#5056]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

UI system backup page doesn't show any error when the backup target is invalid.

## Describe the solution you'd like

See https://github.com/longhorn/longhorn/issues/5055#issuecomment-1350182125

## Describe alternatives you've considered

Let the validator return error from the backend when creating a system backup.

## Additional context

`None`

**Comment by smallteeths** [comment]
The ui does not need to be modified and will directly display the error message returned by the back-end.

<img width="1307" alt="截屏2022-12-14 下午2 24 20" src="https://user-images.githubusercontent.com/27733391/207522023-623604ca-1c8a-4976-8a5b-f51c8afbe17e.png"> @c3y1huang

**Comment by c3y1huang** [comment]
> The ui does not need to be modified and will directly display the error message returned by the back-end.

/cc @longhorn/qa

**Comment by innobead** [comment]
@khushboo-rancher let's check this together with https://github.com/longhorn/longhorn/issues/5056. 

cc @longhorn/qa

**Comment by khushboo-rancher** [comment]
Validation - **Pass**

Verified on v1.4.x-head
<img width="1261" alt="Screenshot 2022-12-15 at 2 49 11 PM" src="https://user-images.githubusercontent.com/60111667/207983856-ca54019d-20fa-4d96-9053-6f4ce51f7de3.png">
<img width="1277" alt="Screenshot 2022-12-15 at 2 53 23 PM" src="https://user-images.githubusercontent.com/60111667/207984057-f90e19ad-3e06-4346-b5ca-380da08752b4.png">
