### ISSUE TITLE
[IMPROVEMENT] System restore job name should be Longhorn prefixed

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#5057]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Longhorn system-restore job name is the SystemRestore name and the pod name is in format `<system-restore-name>-<random-uuid>`. This makes it hard to identify that they are from the Longhorn system restore job.

## Describe the solution you'd like

Have a `longhorn-system-rollout` prefix for the system restore created job and pod.

## Describe alternatives you've considered

`None`

## Additional context

`None`

**Comment by khushboo-rancher** [comment]
Validation - **Pass**

Verified with v1.4.x-head 

<img width="1324" alt="Screenshot 2022-12-15 at 3 04 50 PM" src="https://user-images.githubusercontent.com/60111667/207985727-849d1ab9-8e6f-488a-87ab-9769e3dd2c49.png">
