### ISSUE TITLE
[QUESTION] pvc 挂载失败超时 

### ISSUE THREAD

**Issue by justinmans** [longhorn/longhorn#5058]
Longhorn version:1.2.3
Kubernetes version:1.20.14
Node config
OS type and version redhat 7.9
CPU per node: 108
Memory per node: 313
Disk type 12T
Network bandwidth and latency between the nodes:
Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): 物理机直接部署

节点负载情况
![image](https://user-images.githubusercontent.com/42922475/207503611-0197cea6-2e8c-43b0-b252-d1d4a5f24359.png)

副本监控情况：
![image](https://user-images.githubusercontent.com/42922475/207503663-e83b0960-c975-4053-a1e3-f711d460820b.png)

挂载失败截图：
![image](https://user-images.githubusercontent.com/42922475/207503739-6830cdab-f962-4c09-af69-394117197d87.png)
我尝试过停止多次重建这个pod 依然存在这样的情况

**Comment by mantissahz** [comment]
Hi, could you provide the support bundle for further investigating please?
Does any other workloads have the same situation?
