### ISSUE TITLE
[BUG] missing the `restoreVolumeRecurringJob` parameter in the VolumeGet API

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#5062]
## Describe the bug (🐛 if you encounter this issue)

`restoreVolumeRecurringJob` always is a empty string "" returns by `VolumeGet` API

## To Reproduce

1. Setup the Longhorn system
2. Create a volume
3. Get Volume information by `VolumeGet` API or by Longhorn UI (check the response information)
4. `restoreVolumeRecurringJob` always is a empty string

## Expected behavior

`restoreVolumeRecurringJob` should be one of `ignored`, `enabled` and `disabled`

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: master-head, 20221214
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.24.2+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: ubuntu2204
   - CPU per node: 4
   - Memory per node: 4G
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 1G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 1

## Additional context

![Screenshot_20221214_162511](https://user-images.githubusercontent.com/14231257/207545818-f2850b8b-4401-4ac7-89ed-af9fd2105e03.png)

**Comment by roger-ryao** [comment]
**Verified on master-head 20221219**

- longhorn master-head ([6b53539](https://github.com/longhorn/longhorn/commit/6b5353973899c6204711ddd4cc157819901b8f80)) 
- longhorn-manager master-head ([e11c323](https://github.com/longhorn/longhorn-manager/commit/e11c32372ed72eb81ef2a5d60293eda85e9e4601)) 

**Verified on v1.4.x-head 20221219**
- longhorn v1.4.x-head ([ffca869](https://github.com/longhorn/longhorn/commit/ffca869ff329d8d53d0490add2d51b845209684b)) 
- longhorn-manager v1.4.x-head ([4d075b2](https://github.com/longhorn/longhorn-manager/commit/4d075b2afa5ebc783618e3e47c3d59c76371e32f)) 


**The test steps**

[Ref #5062 (To Reproduce)](https://github.com/longhorn/longhorn/issues/5062#issuecomment-1351545996)

**Result Passed**
1. We could get `restoreVolumeRecurringJob` value in the VolumeGet API  on the `master` | `v1.4.x`  branches
