### ISSUE TITLE
[IMPROVEMENT] Add warning message to when deleting the restoring backups

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#5065]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

When a restoring system backup is being deleted, we can add a warning like `deleting a restoring backup can mess up the Longhorn state`.  As of now system just ask for a general confirmation message.

<img width="685" alt="Screenshot 2022-12-14 at 12 37 47 AM" src="https://user-images.githubusercontent.com/60111667/207547793-d55f26cf-84a8-4aa2-82fd-11b2eb0935da.png">

**Comment by innobead** [comment]
@smallteeths Please help with this.

@c3y1huang Do we protect the restoring backup at backend?

**Comment by c3y1huang** [comment]
> @c3y1huang Do we protect the restoring backup at backend?

No, we do not protect restoring backup at the moment. Because we have a 24 hours timeout for the restore, this allows the user to terminate the restore and change the rollout skipped settings if the volume restore took too long.
- concurrent-volume-backup-restore-per-node-limit
- concurrent-replica-rebuild-per-node-limit

**Comment by smallteeths** [comment]
<img width="1140" alt="截屏2022-12-15 下午4 30 25" src="https://user-images.githubusercontent.com/27733391/207813562-4b48bc67-c1ab-4940-ab59-0f541ffbf7a2.png">

**Comment by khushboo-rancher** [comment]
Verified on v1.4.x-head - PASSED

<img width="643" alt="Screenshot 2022-12-19 at 5 43 03 PM" src="https://user-images.githubusercontent.com/60111667/208756785-fda47f63-51fc-4adb-9838-4e1b109642ff.png">
