### ISSUE TITLE
[TASK] Disable tcmalloc in longhorn-engine and longhorn-instance-manager

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5068]
## What's the task? Please describe

The latest tcmalloc version (v2.10) in longhorn-engine might lead to the failures in the integration test cases. Currently, the failure is not seen on the local dev environment but happen on the Longhorn CI environment.
Need to investigate it and check if it is a platform specific issue. Before figuring out the root cause and avoiding the failure and impact the CI flow, the tcmalloc is disabled temporarily.

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

Add any other context or screenshots about the task request here.

**Comment by derekbit** [comment]
Weird.  Hit the same error although the tcmalloc is disabled.

**Comment by derekbit** [comment]
The failures of longhorn-engine are caused by the `multipathd` of CI agent. After disabling the `multipathd` (thanks @yangchiu for helping configure it), the failures no longer happen.
https://drone-publish.longhorn.io/longhorn/longhorn-engine/521/1/3

Two ways that can avoid running into the failures.
1. Always disable the `multipathd` on the CI agent node.
2. Check the `multipathd` before running the integration test. That is, need to add a check logic in the longhorn-engine.

The tcmalloc is not the culprit, so close it.

**Comment by innobead** [comment]
Thanks @derekbit and @yangchiu :+1: 

I think the second one builtin in longhorn-engine seems helpful for both (production and testing), but in the short term, can we disable multipath for the agent node by default? @yangchiu

**Comment by yangchiu** [comment]
> Thanks @derekbit and @yangchiu +1
> 
> I think the second one builtin in longhorn-engine seems helpful for both (production and testing), but in the short term, can we disable multipath for the agent node by default? @yangchiu

Yes, we've configured the nodes of infra cluster according to the doc: https://longhorn.io/kb/troubleshooting-volume-with-multipath/. This should solve the problem permanently.

**Comment by innobead** [comment]
ref: #5045
