### ISSUE TITLE
[BUG] System restore missing services

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#5074]
## Describe the bug (🐛 if you encounter this issue)

Missing to restore Services.

## To Reproduce

1. Create a system backup.
2. Restore the system backup.
3. Check the rollout log and see `Unknown resource kind ServiceList`.

## Expected behavior

Should restore Services.

## Log or Support bundle

> time="2022-12-15T05:54:34Z" level=error msg="Unknown resource kind ServiceList" backupTargetURL="s3://c3y1huang-s3@ap-southeast-1/" controller=longhorn-system-rollout engineImage="longhornio/longhorn-engine:master-head" systemRestore=test2

## Environment

 `N/A`

## Additional context

`None`

**Comment by innobead** [comment]
cc @longhorn/qa
