### ISSUE TITLE
[BUG] The 'Allow snapshots removal during trim' option is not clear on the volume creation screen

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#5080]
## Describe the bug (🐛 if you encounter this issue)

Case 1:
The option to select for `Allow snapshots removal during trim` setting during creation of the volume is not visible on the volume creation screen.
<img width="817" alt="Screenshot 2022-12-15 at 10 57 44 AM" src="https://user-images.githubusercontent.com/60111667/207951865-a25baed4-cd7f-4db3-ac7a-9c54602b15aa.png">

Case 2:
The setting details doesn't look accurate. `Since Longhorn filesystem trim feature can be applied to the volume head and the followed continuous removed or system snapshots only.`
<img width="1333" alt="Screenshot 2022-12-15 at 11 36 38 AM" src="https://user-images.githubusercontent.com/60111667/207952193-1dd54cb9-1f1b-4a83-ac94-597737823c2c.png">

## To Reproduce

1. For case 1 - Go to volume page and create a volume
2. For case 2  - Go to setting page

## Expected behavior

Case 1 - Make the line wider.
Case 2 - 
```
Since Longhorn filesystem trim feature can be applied to the volume head and the followed continuous removed or system snapshots only, notice that trying to trim a removed files from a valid snapshot will do nothing but the filesystem will discard this kind of in-memory trimmable file info. Later on if you mark the snapshot as removed and want to retry the trim, you may need to unmount and remount the filesystem so that the filesystem can recollect the trimmable file info.

```

## Environment

 - Longhorn version: v1.4.0-rc1

**Comment by smallteeths** [comment]
The description of the setting is returned by the backend and needs to be changed by wushuo. thanks @shuo-wu

**Comment by roger-ryao** [comment]
**Verified on master-head 20241211**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/979eb98a950739d3a832100747fde2960a12ca7e
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/2838f94e5bb39bfe612cbc0a2d411d05df5f8d20
- longhorn-ui `master-head` https://github.com/longhorn/longhorn-ui/commit/1903b12799f31a4c010d6ca738724330cb31c634


**The test steps**
https://github.com/longhorn/longhorn/issues/5080#issue-1498994214


**Result Passed**
- [x] 1. case1
![Screenshot_20241211_124008](https://github.com/user-attachments/assets/34f4821f-04df-40be-a8a4-2a69c5205578)

- [x] 2. case2
![Screenshot_20241211_123949](https://github.com/user-attachments/assets/2f96d435-047e-4e3c-bb43-6f61dd3841b8)
