### ISSUE TITLE
[BUG] Delete share manager pod won't let wrokload pod restart

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#5082]
## Describe the bug (🐛 if you encounter this issue)

From master-head pipeline failed test case [test_rwx_delete_share_manager_pod](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/343/testReport/junit/tests/test_rwx/test_rwx_delete_share_manager_pod/), after delete share manager pod, workload pod won't restart cause test case fail.

Can reproduce in local environment , at that time I can still exec into workload pod and data in mount point still kept.

If this is not bug, need to modify test case. 

## To Reproduce

[Steps](https://github.com/longhorn/longhorn-tests/blob/f70fb0f545abc9549c15e4bd9a4fc35e96570e59/manager/integration/tests/test_rwx.py#L334) 

In step 5, workload pod should recreate but not

## Expected behavior

Match test steps or test steps need to be modified

## Log or Support bundle

N/A

## Environment

 - Longhorn version: master head 
 
## Additional context

Not seen in v.1.4.x pipeline

**Comment by derekbit** [comment]
https://github.com/longhorn/longhorn-tests/pull/1221
Not merged yet
cc @innobead

**Comment by innobead** [comment]
https://github.com/longhorn/longhorn-tests/pull/1229

**Comment by innobead** [comment]
@mantissahz The related test PRs have been merged. Please help close this if it works as expected.

**Comment by mantissahz** [comment]
Verified at master-head (20221223):
&nbsp;&nbsp; OS: ubuntu2204
&nbsp;&nbsp; Installation method: kubectl
&nbsp;&nbsp; Kubernetes version: v1.24.6+k3s1

Local testing 3 times PASSED
```text
============================= test session starts ==============================
platform linux -- Python 3.9.15, pytest-5.3.1, py-1.11.0, pluggy-0.13.1 -- /usr/bin/python3.9
cachedir: .pytest_cache
rootdir: /integration, inifile: pytest.ini
plugins: order-1.0.1, repeat-0.9.1
collecting ... collected 1 item

test_rwx.py::test_rwx_delete_share_manager_pod PASSED                    [100%]

============================== 1 passed in 48.10s ==============================
```
