### ISSUE TITLE
[TASK] Update longhorn-share-manager's nfs-ganesha to V4.2.1

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5083]
## What's the task? Please describe

The [nfs-ganesha](https://github.com/nfs-ganesha/nfs-ganesha) in share-manager is V4.0.7. The latest version is V4.2.1. There are many fixes from V4.0.7 to V4.2.1. To avoid accidents from nfs-ganesha, the task is to update it to the latest one.

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

e2e https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2717/console

**Comment by innobead** [comment]
@mantissahz Please help test this. Thanks.

cc @longhorn/qa

**Comment by innobead** [comment]
From the test result, looks good. But there is a regression failure with pod restart, and it probably is related to #5082 

https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-tests-sles-arm64/lastCompletedBuild/testReport/tests/test_rwx/test_rwx_delete_share_manager_pod/
