### ISSUE TITLE
[IMPROVEMENT] Support customized number of replicas of webhook and recovery-backend

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5087]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Support customized number of replicas of webhook and recovery-backend

**Comment by chriscchien** [comment]
Verified in longhorn master-head images and v1.4.x head images
Result **Pass**

In both v1.4.x and master-head :
1. Modify replica number of `longhornConversionWebhook`, `longhornAdmissionWebhook` and `longhornRecoveryBackend` in longhorn/chart/values.yaml (for example : 3, 4, 5)
2. Deploy Longhorn by helm, can see related pods have replicas matching setting in values.yaml
![Screenshot from 2022-12-20 16-23-23](https://user-images.githubusercontent.com/73337386/208622858-138c1484-eeba-4850-8d9c-9cb26fc15fe9.png)
3. Deploy workload then scale down/up, data kept consistent, no error happen.
4. Randomly delete replica, rebuild success
5. Uninstall successed.
