### ISSUE TITLE
[IMPROVEMENT] Simplify the page by placing some configuration items in the advanced configuration when creating the volume

### ISSUE THREAD

**Issue by smallteeths** [longhorn/longhorn#5090]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

There are more and more configuration items for creating volumes.  This is particularly inconvenient when creating volumes.

## Describe the solution you'd like

Put some non-critical configuration items into advanced options

<img width="1437" alt="截屏2022-12-16 下午3 56 19" src="https://user-images.githubusercontent.com/27733391/208054440-f9b728c1-b500-4085-8377-c73ce6b35625.png">

**Comment by yangchiu** [comment]
Verified passed on v1.4.x-head (longhorn-ui 2f43f07). The `advanced configurations` section can be found in ui.
