### ISSUE TITLE
[BUG] In a system restore, PV & PVC are not restored if PVC was created with 'longhorn-static' (created via Longhorn GUI)

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#5091]
## Describe the bug (🐛 if you encounter this issue)

In a system restore, PV & PVC are not restored if PVC was created with 'longhorn-static' (created via Longhorn GUI)

## To Reproduce

1. Create a volume using Longhorn UI.
2. Create PV/PVC using Longhorn UI.
3. Take a system backup and restore in a new cluster.
4. The PV/PVC are not created in the new cluster.

## Expected behavior

PV and PVC should be restored and created in the new cluster.

<img width="1759" alt="Screenshot 2022-12-16 at 12 03 54 AM" src="https://user-images.githubusercontent.com/60111667/208056277-c9213e0b-e608-4ae9-88ff-b9f50f87fb1a.png">

## Environment

 - Longhorn version: v1.4.x-head

## Additional context

PV and PVC are restored and created for the volumes using Longhorn storage class.

**Comment by innobead** [comment]
@c3y1huang What do you think the behavior should be? Should we silently delete the PVC w/ a different storage class, then restore the correct one?

**Comment by c3y1huang** [comment]
> @c3y1huang What do you think the behavior should be? Should we silently delete the PVC w/ a different storage class, then restore the correct one?

I've under-considered the PV created via the UI. Will fix this.

**Comment by khushboo-rancher** [comment]
Validation - PASS

Validated on master-head and v1.4.x-head, the PV and PVC created by UI get restored on restoring the system backup
