### ISSUE TITLE
[CI] Support SBOM for component images

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5099]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Integrate the following tasks to our build

- Leverage https://github.com/anchore/syft or a similar tool to generate an SBOM file for each delivered image including self-own and mirrored images to understand ingredients and lib dependencies in each image.

**Comment by yangchiu** [comment]
The image can be built and published with sbom attached by adding `--sbom=true` paramter:
```
docker buildx build --sbom=true -t <myorg>/<myimage> --push .
```

And the sbom content can be viewed by:
```
docker buildx imagetools inspect <image> --format "{{ json .SBOM }}" > sbom.spdx.json
```

ref:
https://www.docker.com/blog/generate-sboms-with-buildkit/
https://docs.docker.com/scout/sbom/#attest
https://github.com/docker/build-push-action?tab=readme-ov-file#customizing
https://docs.docker.com/scout/sbom/#remote-image

**Comment by innobead** [comment]
@yangchiu For mirrored images, are we able to do this as well? even though the mirror is not through GH action.

**Comment by yangchiu** [comment]
> @yangchiu For mirrored images, are we able to do this as well? even though the mirror is not through GH action.

No, for mirrored images, we just use `skopeo` to copy an image from one registry to another. The `sbom` file should be attached by other means. More investigation needed.

**Comment by innobead** [comment]
Then, what we should do are:
- For self-owned images, sbom included
- For all images including mirrored and self-owned, sbom file attached to the release note 

The second item needs to be improved in the release process `longhorn/release` which is outside of this scope.

**Comment by yangchiu** [comment]
> No, for mirrored images, we just use `skopeo` to copy an image from one registry to another. The `sbom` file should be attached by other means. More investigation needed.

Still investigate if it's possible to attach `sbom` files to an existing image manifest.

**Comment by yangchiu** [comment]
Both `oras attach --artifact-type "application/spdx+json" <IMAGE>:<TAG> toattach.spdx.json` and `cosign attach sbom --sbom toattach.spdx.json <IMAGE>:<TAG>` create extra artifacts (The `sha256-5c31e` in the screenshot) in the repo. Users have to pull this extra artifact to get the `sbom` file, instead of embedded `sbom` in the published image like what `docker buildx build --sbom=true` does. But how to achieve what `docker buildx build --sbom=true` does, and how/where it stores the `sbom` is still unknown. More investigation needed. 
![sbom](https://github.com/longhorn/longhorn/assets/5709208/15ba90c5-ddc9-41b4-a87f-957f864c6414)

ref:
https://learn.microsoft.com/en-us/azure/security/container-secure-supply-chain/articles/attach-sbom
https://edu.chainguard.dev/open-source/sigstore/cosign/how-to-sign-an-sbom-with-cosign/

**Comment by yangchiu** [comment]
Probably workable:
```
cosign attach sbom --sbom toattach.spdx.json docker.io/yangchiu/csi-snapshotter:v6.0.1-amd64
cosign download sbom docker.io/yangchiu/csi-snapshotter:v6.0.1 --platform=linux/amd64
```
But extra artifact will still be created in the repo like:
```
yangchiu/csi-snapshotter:sha256-994f83f6be2bacf89262c587b28352e5fce5be81c27d06a31c061d84dea2d33d.sbom
```
It seems unavoidable.

**Comment by innobead** [comment]
How does it know the extra snapshot related to the image? If having two platforms, does it mean pulling sbom twice is required?

**Comment by yangchiu** [comment]
> How does it know the sbom is related to the image? 

The `sbom` is associated with the image using its digest. For example:

```
$ cosign attach sbom --sbom toattach.spdx.json docker.io/yangchiu/csi-snapshotter:v4.0.1-amd64
Uploading SBOM file for [index.docker.io/yangchiu/csi-snapshotter:v4.0.1-amd64] to [index.docker.io/yangchiu/csi-snapshotter:sha256-3023fdbdee1b5d7119287d8e778b421e4623a578428795e794aac67657e70f6e.sbom] with mediaType [text/spdx+json].
```

It created an artifact for the `sbom` of `docker.io/yangchiu/csi-snapshotter:v4.0.1-amd64` with tag `sha256-3023fdbdee1b5d7119287d8e778b421e4623a578428795e794aac67657e70f6e.sbom`.

The `3023fdbdee1b5d7119287d8e778b421e4623a578428795e794aac67657e70f6e` part is the digest of `docker.io/yangchiu/csi-snapshotter:v4.0.1-amd64`:

```
$ docker buildx imagetools inspect yangchiu/csi-snapshotter:v4.0.1-amd64
Name:      docker.io/yangchiu/csi-snapshotter:v4.0.1-amd64
MediaType: application/vnd.docker.distribution.manifest.v2+json
Digest:    sha256:3023fdbdee1b5d7119287d8e778b421e4623a578428795e794aac67657e70f6e
```

> If having two platforms, does it mean pulling sbom twice is required?

Yes, we need to attach the sbom twice, and users must pull the corresponding sbom for their specific architecture.

> An additional artifact for the sbom will be created in the repository.

It looks like that's how it works now. A registry is no longer limited to just container images. Various types of artifacts, including Helm charts, SBOMs, and vulnerability reports, can now be stored in a registry.

In my opinion, this approach makes the repository cluttered. The only method that makes sense to me is what `docker buildx build --sbom=true` does, but unfortunately, it happens during the build time, and Kubernetes CSI components don’t implement it.

I think we should try switching to https://github.com/longhorn/longhorn/issues/8821 to attach sbom files to the release notes for now.

**Comment by innobead** [comment]
Sounds good. Good enough for our own images.

**Comment by derekbit** [comment]
Do we need to add a doc page for the feature? @innobead ?
