### ISSUE TITLE
[IMPROVEMENT] Check the compatibility of ZFS filesystem in longhorn volumes

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5106]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Longhorn officially supports ext4 and xfs. Besides of the two filesystems, ZFS is also a popular filesystem and provides many advanced functionalities such as inline compression and deduplication. The issue is to check the compatibility of ZFS filesystem in longhorn volumes.  

## Additional context

https://github.com/longhorn/longhorn/issues/5101

**Comment by Cloud-Mak** [comment]
Just curious. When will longhorn will support modern FS like ZFS (or btrfs). ZFS is so smooth and reliable FS (+Volume Manager) that is around for a long long time. 
In my case - I am running HA k8s (3M, 6 workers....k8s 1.30) on incus system containers. incsus storage pool is zfs so the k8s node have same. Using latest stable longhorn. All DS/Deployments in longhorn are working fine. pvc/pv gets created and in bound mode. Longhorn volume goes into faultd state as it can't be attached to the 1st mode node (replica creation fails)


```
time="2024-09-28T07:57:54Z" level=warning msg="pvc-fd1c1b56-327c-44ab-8179-c6e3a48b6ae5-r-eb5e224e: time=\"2024-09-28T07:57:53Z\" level=warning msg=\"Recovering volume metafile /host/var/lib/longhorn/replicas/pvc-fd1c1b56-327c-44ab-8179-c6e3a48b6ae5-7dac046c/volume.meta, and replica info: {Size:1073741824 Head: Dirty:false Rebuilding:false Error: Parent: SectorSize:512 BackingFilePath: BackingFile:<nil>}\" func=\"replica.(*Replica).tryRecoverVolumeMetaFile\" file=\"replica.go:1125\"" func="controller.(*InstanceHandler).printInstanceLogs" file="instance_handler.go:475"

time="2024-09-28T07:57:54Z" level=warning msg="pvc-fd1c1b56-327c-44ab-8179-c6e3a48b6ae5-r-eb5e224e: time=\"2024-09-28T07:57:53Z\" level=info msg=\"Starting to create disk\" func=\"replica.(*Replica).createDisk\" file=\"replica.go:898\" disk=000" func="controller.(*InstanceHandler).printInstanceLogs" file="instance_handler.go:475"
time="2024-09-28T07:57:54Z" level=warning msg="pvc-fd1c1b56-327c-44ab-8179-c6e3a48b6ae5-r-eb5e224e: time=\"2024-09-28T07:57:53Z\" level=info msg=\"Finished creating disk\" func=\"replica.(*Replica).createDisk\" file=\"replica.go:998\" disk=000" func="controller.(*InstanceHandler).printInstanceLogs" file="instance_handler.go:475"

time="2024-09-28T07:57:54Z" level=warning msg="pvc-fd1c1b56-327c-44ab-8179-c6e3a48b6ae5-r-eb5e224e: time=\"2024-09-28T07:57:53Z\" level=fatal msg=\"Error running start replica command\" func=cmd.ReplicaCmd.func1 file=\"replica.go:89\" error=\"file extent is unsupported: operation not supported\"" func="controller.(*InstanceHandler).printInstanceLogs" file="instance_handler.go:475"
```
