### ISSUE TITLE
[IMPROVEMENT] Set a newly created volume's data integrity from UI to `ignored` rather than `Fast-Check`.

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5126]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

- Rename `Update Snapshot Data Integrity` to `Snapshot Data Integrity`
- Set the value to `ignored` by default

![image](https://user-images.githubusercontent.com/12527233/209036621-c7138065-dc4d-44df-8a40-7784f201b524.png)

**Comment by derekbit** [comment]
cc @smallteeths

**Comment by yangchiu** [comment]
Verified passed on v1.4.x-head (longhorn-ui 20dbdf3). `Snapshot Data Integrity` is set to `ignored` by default as expected.
