### ISSUE TITLE
[BUG] Snapshot trim wrong label in the volume detail page.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#5127]
## Describe the bug (🐛 if you encounter this issue)

The label for the snapshot trim detail in the volume detail page seems wrong. Currently, it appears as `Allow snapshots removal during trim:ignored(false)`. It should be `Allow snapshots removal during trim:ignored`

## To Reproduce

1. Create a volume.
2. Go to volume detail page.
3. Check the right hand side details of the volume.
4. The snapshot trim detail appears as `Allow snapshots removal during trim:ignored(false)`

## Expected behavior

The info should displayed as `Allow snapshots removal during trim:ignored`

## Environment

 - Longhorn version: v1.4.0-rc2

**Comment by chriscchien** [comment]
Verified in longhorn master-head images and v1.4.x-head images
Result **Pass**

In both master-head UI `ea49e4` and v1.4.x-head UI `20dbdf` volume detail page, `Allow snapshots removal during trim` displayed correctly.

**Comment by shuo-wu** [comment]
The value enclosed in the bracket indicates the current state, while value `ignored` indicates the setting/spec. Should we remove the current state representation?

**Comment by innobead** [comment]
> The value enclosed in the bracket indicates the current state, while value `ignored` indicates the setting/spec. Should we remove the current state representation?

Yeah, we missed this part because the display way seems not quite clear and understandable. BTW, do we have any similar cases in this setting in the volume info panel?

**Comment by shuo-wu** [comment]
For other fields like `Replicas Auto Balance`, it seems that the UI will show the final result.

**Comment by innobead** [comment]
Because we introduced `ignored` for a few volume spec settings, users need to check the inherited value from the global setting instead. However, just displaying `true/false` next to `ignored` is helpful for development/troubleshooting, but it seems weird from the user experience. 

I would suggest let's add a tooltip first to display a message (`The is the default option that instructs Longhorn to inherit from the global setting.`) when the value is `ignored`. WDYT?

cc @smallteeths

**Comment by shuo-wu** [comment]
You mean directly showing the final result but with a tooltip (probably with an icon) explaining that this is inherited from the global setting?

**Comment by innobead** [comment]
> You mean directly showing the final result but with a tooltip (probably with an icon) explaining that this is inherited from the global setting?

yeah, how about it?

**Comment by shuo-wu** [comment]
Sure. It looks better than the current displaying.

**Comment by innobead** [comment]
@chriscchien Please help check the below cases. 

There will be a tooltip (`The is the default option that instructs Longhorn to inherit from the global setting.`) for `ReplicaAutoBalance`, `SnapshotDataIntegrity `, and `UnmapMarkSnapChainRemoved` if the value is `ignored` when your mouse is over, and vice versa. 

![image](https://user-images.githubusercontent.com/899492/209640768-854a033c-5686-4adc-8eec-4eae0bf62c2f.png)

**Comment by chriscchien** [comment]
Verified in longhorn UI master `f9ed1f` and longhorn UI v1.4.x `3109b5`
Result `Pass`

In both master head UI and v1.4.x head UI, no matter volume is attached or detached, when `Snapshot Data Integrity`, `Replicas Auto Balance` and `Allow Snapshot Removal During Trim` were set to ignore, there will be a tool tip  `The is the default option that instructs Longhorn to inherit from the global setting` displayed.

In addition, there were  **no** tool tip displayed when:  
- Snapshot Data Integrity : disabled, enabled, fast-check
- Replicas Auto Balance : disabled, least-effort, best-effort
- Allow Snapshot Removal During Trim : disabled, enabled
