### ISSUE TITLE
[IMPROVEMENT] Support trim operation on volumes with backing images

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5128]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Ater enable the `Remove Snapshots During Filesystem Trim`, trimmig a volume with backing image will lead to the error
```
[tstvol-r-8b1f825d] time="2022-12-22T02:16:40Z" level=error msg="Replica with dir /host/var/lib/longhorn/replicas/tstvol-d2f33b9b failed to do unmap with offset 135274496 and length 3137536" error="failed to mark snapshot disk /host/var/lib/longhorn/backing-images/bitest-450bd772/backing as removed before unmap: cannot find disk metafile /host/var/lib/longhorn/backing-images/bitest-450bd772/backing.meta"
```

The error message is shown and the trim cannot continue, but the snapshots are marked as deleted.

## Describe the solution you'd like

Support trim operation on volumes with backing images or reject the operation if not supported.

**Comment by innobead** [comment]
Add this limitation/known issue to 1.4.0 https://github.com/longhorn/longhorn/wiki/Outstanding-Known-Issues-of-Releases.

**Comment by derekbit** [comment]
The fix in https://github.com/longhorn/longhorn/issues/5129 make the feature already available.

**Comment by innobead** [comment]
After discussing with @derekbit , we think the backing image should be an immutable layer, so not supporting trim makes sense for the case. Won't fix.
