### ISSUE TITLE
[BUG] Filesystem on the volume with a backing image is corrupted after applying trim operation

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5129]
## Describe the bug (🐛 if you encounter this issue)

Filesystem on the volume with a backing image is corrupted after applying trim operation

## To Reproduce

1. Create and upload a backing image
2. Create a volume using the backing image and create PVC/PV
3. Create a pod using the PVC
4. Write some data and then take snapshots
5. Delete data
6. Trim filesystem
7. The operation fails silently (but can check the error message in the instance-manager-r/e log) (https://github.com/longhorn/longhorn/issues/5128)
8. Delete the pod and then create it using the volume again. The error in the instance-manager-r is
```
tgtd: bs_longhorn_request(210) io error 0xedf520 2a -14 4096 1136082944, Success
timeout_handler: Timeout request 1902 due to disconnection
tgtd: bs_longhorn_request(111) fail to read at 0 for 4096
tgtd: bs_longhorn_request(210) io error 0xec1570 28 -14 4096 0, Success
timeout_handler: Timeout request 1903 due to disconnection
tgtd: bs_longhorn_request(111) fail to read at 0 for 4096
tgtd: bs_longhorn_request(210) io error 0xec1570 28 -14 4096 0, Success
timeout_handler: Timeout request 1904 due to disconnection
tgtd: bs_longhorn_request(183) Failed to punch hole for UNMAP at offset:0 length:4096
tgtd: bs_longhorn_request(210) io error 0xec1570 42 0 16 0, Success
timeout_handler: Timeout request 1905 due to disconnection
tgtd: bs_longhorn_request(111) fail to read at 0 for 4096
tgtd: bs_longhorn_request(210) io error 0xed2b90 28 -14 4096 0, Success
timeout_handler: Timeout request 1906 due to disconnection
tgtd: bs_longhorn_request(111) fail to read at 0 for 4096
tgtd: bs_longhorn_request(210) io error 0xec1570 28 -14 4096 0, Success
timeout_handler: Timeout request 1907 due to disconnection
tgtd: bs_longhorn_request(111) fail to read at 0 for 4096
tgtd: bs_longhorn_request(210) io error 0xec1570 28 -14 4096 0, Success
timeout_handler: Timeout request 1908 due to disconnection
tgtd: bs_longhorn_request(111) fail to read at 0 for 4096
tgtd: bs_longhorn_request(210) io error 0xec1570 28 -14 4096 0, Success
``` 

## Expected behavior

trim is rejected if the volume is using a backing image and the filesystem is not corrupted.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
We need to have validation for that first in 1.4.0.

**Comment by chriscchien** [comment]
Verified in both longhorn master-head images and v1.4.x-head images with [steps](https://github.com/longhorn/longhorn/issues/5129#issue-1507311030) (enable `Allow snapshots removal during trim`)
Result **Pass**


1. Can reproduce the file system corruption by longhorn-engine `a38ed0` and can see error log in instance-manager below
`[vol2-r-da734a73] time="2022-12-27T06:55:53Z" level=error msg="Replica with dir /host/var/lib/longhorn/replicas/vol2-4beefc95 failed to do unmap with offset 21815296 and length 112402432" error="failed to mark snapshot disk /host/var/lib/longhorn/backing-images/vol1-a9775f08/backing as removed before unmap: cannot find disk metafile /host/var/lib/longhorn/backing-images/vol1-a9775f08/backing.meta"
`
2. In longhorn master-head and v1.4.x-head, the file corruption not happen and error log not observed
