### ISSUE TITLE
[IMPROVEMENT] Improve the speed of replica rebuilding if it is somehow stopped and re-started

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5130]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Improve the speed of replica rebuilding if it is somehow stopped (usually caused by unstable network or disk IO starvation) and re-started.

A disk file of the healthy replica is read by direct io ([code](https://github.com/longhorn/longhorn-engine/blob/master/pkg/sync/rpc/server.go#L328)) in current implementation. Hence, if the replica rebuilding somehow failed and restarted, the data will be read from disk again and cannot benefit from the host's page cache mechanism. Reading a disk file of the healthy replica should be not harmful, because the disk file is opened with RDONLY. 

After a quick test, the restarted replica rebuilding can be improved by 50% .

**Comment by derekbit** [comment]
On AWS EC2 machines, I cannot see the improvement as well. The improvement on Equinix machines is 35%.
After the rebuilding, the memory usage of the instance-manager-r is (`kubectl -n longhorn-system top pods)
```
instance-manager-r-78e63e75eb3bedb81a32e48d220dd6e8   5m           31192Mi
```

This might be scary to users. I plan to revert the improvement.
WDYT? @innobead

**Comment by yangchiu** [comment]
Verified on master-head (longhorn-engine 84da610). Following [the test steps](https://github.com/longhorn/longhorn/issues/5130#issuecomment-1376657804) and observing the memory usage on each step, high memory usage in instance-manager-r like https://github.com/longhorn/longhorn/issues/5130#issuecomment-1427372975 won't happen:

(1) Create a 15 GiB volume with 2 replicas. The original memory usage is:
```
instance-manager-r-0b165eb6a49550ac97473a12c0045a78   1m           7Mi             
instance-manager-r-790a4298a3ab3ecc966c0ab724302cbf   1m           7Mi             
instance-manager-r-b951cffeead0a3cbc0b8db8e27a43bac   1m           7Mi
```
(2) Write 15GiB data and delete one of the 2 replicas. The replica rebuilding is triggered and started.
(3) When the rebuilding progress is 80%, the memory usage is:
```
instance-manager-r-0b165eb6a49550ac97473a12c0045a78   1m           9Mi             
instance-manager-r-790a4298a3ab3ecc966c0ab724302cbf   724m         46Mi            
instance-manager-r-b951cffeead0a3cbc0b8db8e27a43bac   800m         62Mi  
```
(3) Delete the same replica again, the replica rebuilding is triggered and started again.
(4) When the rebuilding progress is 80% again, the memory usage is:
```
instance-manager-r-0b165eb6a49550ac97473a12c0045a78   1m           10Mi            
instance-manager-r-790a4298a3ab3ecc966c0ab724302cbf   718m         48Mi            
instance-manager-r-b951cffeead0a3cbc0b8db8e27a43bac   505m         61Mi   
```
(5) After rebuilding completed and wait for a while, the memory usage is:
```
instance-manager-r-0b165eb6a49550ac97473a12c0045a78   1m           9Mi             
instance-manager-r-790a4298a3ab3ecc966c0ab724302cbf   1m           35Mi            
instance-manager-r-b951cffeead0a3cbc0b8db8e27a43bac   2m           41Mi
```
