### ISSUE TITLE
[FEATURE] Upgrade path enforcement & downgrade prevention

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5131]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Currently, Longhorn does not enforce the upgrade path, even though we claim Longhorn only supports upgrading from the previous stable release, for example, upgrading to 1.4.x is only supported from 1.3.x or 1.4.0. 

Without upgrade enforcement, it allows users to upgrade from any previous version to a later version and it will cause deprecated features to be unable to remove from the later version.

## Describe the solution you'd like

- Enforce the upgrade path to disallow users to upgrade from an unsupported source version. After rejecting the user upgrade, the user longhorn setup should be intact w/o any impacts.
- Also not allow users to do the downgrade. 

## Additional context

#2865 

cc @longhorn/dev

**Comment by innobead** [comment]
@mantissahz Do we have LEP? We should LEP first to see the whole design.

**Comment by innobead** [comment]
Moved back to `implement` due to missing doc PR.

**Comment by ejweber** [comment]
I am working on https://github.com/longhorn/longhorn/issues/4997 to remove a deprecated setting that is still referenced in an [upgrade.go file](url). I can modify that file to remove the reference to the setting or make the setting name local to the file, but these approaches are kind of hacky. Now that we are enforcing an upgrade path, it makes more sense to me to entirely remove illegal upgrade paths from the upgrade folder/package. For example, in v1.5.x, remove `upgrade/v070to080` ... `upgrade/v120to121` and remove the corresponding `UpgradeResources` calls in `upgrade/upgrade.go`. This would make current and future dead code removal easier. WDYT?

https://github.com/longhorn/longhorn-manager/tree/master/upgrade

**Comment by innobead** [comment]
Exactly, we should remove unsupported paths from 1.5.0. @mantissahz Please help with that.

**Comment by mantissahz** [comment]
@innobead, @ejweber 
https://github.com/longhorn/longhorn-manager/pull/1902
Removed the upgrade patch codes older than upgrading from v1.4.x to v1.5.0

**Comment by derekbit** [comment]
> @innobead, @ejweber [longhorn/longhorn-manager#1902](https://github.com/longhorn/longhorn-manager/pull/1902) Removed the upgrade patch codes older than upgrading from v1.4.x to v1.5.0

There are some old codes 
```
if isCLIAPIVersionOne {
    ....
}
```
Is it possible to remove these codes after introducing the upgrade enforcement feature?

**Comment by innobead** [comment]
Sounds good. @mantissahz Can you help with this as well?

**Comment by ejweber** [comment]
> There are some old codes
> 
> ```
> if isCLIAPIVersionOne {
>     ....
> }
> ```
> 
> Is it possible to remove these codes after introducing the upgrade enforcement feature?

It isn't immediately clear to me why upgrade path enforcement allows us to get rid of these code paths (since newer versions of Longhorn can and do generally run with older engines until the user manually upgrades them). Is it related to the fact that `MinCliVersion = 3` [since Longhorn v1.1.0](https://github.com/longhorn/longhorn-manager/blob/278ff44085b967923d6f07dfb43a95a7b2974470/engineapi/types.go#L20), so we assume the user is definitely not running with an old engine by now?

**Comment by derekbit** [comment]
> > There are some old codes
> > ```
> > if isCLIAPIVersionOne {
> >     ....
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is it possible to remove these codes after introducing the upgrade enforcement feature?
> 
> It isn't immediately clear to me why upgrade path enforcement allows us to get rid of these code paths (since newer versions of Longhorn can and do generally run with older engines until the user manually upgrades them). Is it related to the fact that `MinCliVersion = 3` [since Longhorn v1.1.0](https://github.com/longhorn/longhorn-manager/blob/278ff44085b967923d6f07dfb43a95a7b2974470/engineapi/types.go#L20), so we assume the user is definitely not running with an old engine by now?

Yeah, you're right. `isCLIAPIVersionOne` is for the engine part rather than longhorn-manager, so they are independent.
I'm thinking when we can remove the logics`if isCLIAPIVersionOne {...}`  in longhorn-manager.

**Comment by ejweber** [comment]
> Yeah, you're right. `isCLIAPIVersionOne` is for the engine part rather than longhorn-manager, so they are independent.
> I'm thinking when we can remove the logics`if isCLIAPIVersionOne {...}` in longhorn-manager.

Would we need to add a check in `upgrade.go` at some point for engine images that use `cliAPIVersion = 1` and refuse to upgrade if any are found? I don't know that we have a clearly defined policy for what engines versions are allowed to be running in an up-to-date cluster.

**Comment by innobead** [comment]
Good point @ejweber !

We should only focus on longhorn/longhorn-manager part (upgrade path w/ migration path for CRs). Currently, there is no clear boundary for if the version of the engine should not be supported since we allow users to do so by themselves. (we can do some enforce check for that, but this is not what we should at the moment, especially it's related to volume directly)

The version support of different engines should be tackled well when we have a fully backward-compatible gRPC protocol between the manager/IM proxy and engine process instead of some still relying on CLI. (JFYI. for now, the new stack of data plane is purely relying on gRPC instead)

@mantissahz sorry for incomplete misleading info, I think we don't need to do any changes related to engine part.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 9cc40a4) following [the test steps](https://github.com/longhorn/longhorn/issues/5131#issuecomment-1512337859).
