### ISSUE TITLE
[BUG] Error in uninstall job

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#5132]
## Describe the bug (🐛 if you encounter this issue)

The below error appears in the logs for uninstall job for supportbundle api.
```
W1222 19:41:49.829202       1 reflector.go:324] github.com/longhorn/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:117: failed to list *v1beta2.SupportBundle: supportbundles.longhorn.io is forbidden: User "system:serviceaccount:longhorn-system:longhorn-uninstall-service-account" cannot list resource "supportbundles" in API group "longhorn.io" at the cluster scope
```

## To Reproduce

1. Install Longhorn v1.4.0-rc2
2. Uninstall Longhorn. using the manifest at https://github.com/longhorn/longhorn/blob/v1.4.0-rc2/uninstall/uninstall.yaml
3. Error appears in the logs as the `supportbundles` is missing from the apiGroups's resources

## Environment

 - Longhorn version: v1.4.0-rc2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

**Comment by chriscchien** [comment]
Verified in longhorn master head images and v1.4.x head images with test [steps](https://github.com/longhorn/longhorn/issues/5132#issue-1508459123)
Result **Pass**

In both master-head and v1.4.x head, after uninstall complete, did not see error log related to `supportbundles` in job longhorn-uninstall
