### ISSUE TITLE
[BUG] Uninstall job unable to delete the systembackup and systemrestore cr.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#5133]
## Describe the bug (🐛 if you encounter this issue)

Longhorn-system namespace stuck in terminating state as uninstallation fails for systembackup and systemrestore crs

## To Reproduce

1. Install Longhorn, create some systembackup & systemrestore.
2. Uninstall Longhorn
3. The systembackup & systemrestore cr don't get deleted.

## Expected behavior

All the Longhorn CR should get deleted.

## Environment

 - Longhorn version: v1.4.0-rc2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

**Comment by chriscchien** [comment]
Verified in longhorn master head images and v1.4.x head images with test [steps](https://github.com/longhorn/longhorn/issues/5133#issue-1508482910)
Result **Pass**

In both master-head and v1.4.x head, after uninstall complete, `systemrestores.longhorn.io` and `systembackups.longhorn.io` removed too.

**Comment by chriscchien** [comment]
In v1.4.0 master-head, CR `systembackups` will be deleted by uninstall job but CR `systemrestores` still kept and caused Longhorn-system namespace stuck in terminating and if execute k`ubectl delete systemrestores <resotrename> -n longhorn-system` the process will stuck too.

**Comment by innobead** [comment]
> In v1.4.0 master-head, CR `systembackups` will be deleted by uninstall job but CR `systemrestores` still kept and caused Longhorn-system namespace stuck in terminating and if execute k`ubectl delete systemrestores <resotrename> -n longhorn-system` the process will stuck too.

finalizier? @c3y1huang ?

**Comment by chriscchien** [comment]
After remove finalizer in CR systemrestores
```
finalizers:
  - longhorn.io
```
The CR systemrestores deleted and nsmespace longhorn-system deleted too

**Comment by innobead** [comment]
It seems like we didn't delete them in UninstallerController. Why it has not been noticed and reviewed :disappointed: . Well done @chriscchien

**Comment by innobead** [comment]
@chriscchien It seems I asked before, do we have a uninstall test case in our daily testing?

**Comment by chriscchien** [comment]
Yes in https://github.com/longhorn/longhorn/issues/4031, will start work on it

**Comment by innobead** [comment]
@chriscchien after @c3y1huang moves this to ready-for-testing, besides testing uninstall, please also revalidate system backup & restore (with volume backup) to ensure the new fix w/o any side effect. Thanks.

**Comment by chriscchien** [comment]
Verified in longhorn-manager master `07b3f7`
Result **Pass**

0. Prepare clusters A and clsuter B, each deployed longhorn master-head and have backing image with the same name, these 2 clusters using the same backup store
1. In cluster A, prepare below volumes and create volume backup then create system backup
   - Dynamic provision volumes by [statefulset](https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml), write data into pod mount point
   - RWX volume and PVC from UI with deployment pod, write data into pod mount point
   - Volume from backing image by UI, attach to node, write data to `/dev/longhorn/volume` and calaulate checksum
   - Encrypted volume by UI, attach to node, write data to /`dev/longhorn/volume` and calculate checksum
 2. Restore system in cluster B, after restore complete, verified that data were all correct (pod mount point data, checksum of /dev/longhon/volume)
 3. Uninstall longhorn, after uninstall job complete, `kubectl get crd | grep longhorn.io` get empty result and namespace `longhorn-system` terminated correctly.

**Comment by chriscchien** [comment]
For v1.4.x head verify, image seems not build success so I can still reproduce, will verify once image complete
![Screenshot from 2022-12-28 22-22-42](https://user-images.githubusercontent.com/73337386/209826476-ee5f6ba2-c892-4e3a-bf87-d31282e0d97b.png)

**Comment by innobead** [comment]
https://drone-publish.longhorn.io/longhorn/longhorn-manager/1114/1/1 retriggered.

**Comment by chriscchien** [comment]
Verified in longhorn-manager v1.4.x `36f30b` with [steps](https://github.com/longhorn/longhorn/issues/5133#issuecomment-1366688725)
Result **Pass**

1. Dynamic provisioned volume, RWX volume, Volume created from backing image, encrypted volumes all can be restore from 1 cluster to another cluster, all data kept consistent after system restore.
2. Uninstall longhorn on those 2 cluster all succeed, all CRD cleaned up (have many kind of volumes exist in cluster and system backup, system restore), namespace terminated succedd
