### ISSUE TITLE
[FEATURE] Support RWX volume trim

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5143]
For a RWX volume, the `/dev/longhorn/xxxx` is mounted to `/export/xxxx` in a share-manager pod, so you cannot see the mountpoint on the host and hence got the error message `No such file or directory`.
A NFS mountpoint doesn't support discard/trim operation as well. For the RWX volumes, need to figure out a way to do trim operation instead of `nsenter .... fstrim <mountpoint>`. Let me create a ticket for the RWX trim feature.

_Originally posted by @derekbit in https://github.com/longhorn/longhorn/issues/836#issuecomment-1363794746_

cc @shuo-wu @derekbit @tommy04062019 @longhorn/qa

**Comment by chriscchien** [comment]
Verified in longhorn master (longhorn-manager `7bdc99`, longhorn-share-manager `1729f0`) with test [steps](https://github.com/longhorn/longhorn/issues/5143#issuecomment-1475307800)
Result **Pass**

Dynamically provision rwx volume with deployment, after delete file in mount point then trim rwx volume from UI, `volume.status.actualSize` decreased, write data again into mount point and scale down/up deployment let volume reattach, data in mount point consistent
