### ISSUE TITLE
[BUG] Retention count doesn't seem to be honoured

### ISSUE THREAD

**Issue by rlipscombe** [longhorn/longhorn#5147]
## Describe the bug (🐛 if you encounter this issue)

I've got a recurring snapshot job set with retention 5. The Longhorn UI shows 9 snapshots.

## To Reproduce

Set up a recurring job to snapshot a volume. Configure it to run, say, once a day, and to retain 5 copies.

## Expected behavior

It should retain only 5 copies.

## Environment

 - Longhorn version: master, approx Oct 2022.
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s 1.25.4
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3 at the time, now 4.
 - Node config
   - OS type and version: Ubuntu 22.04.1
   - CPU per node: 2/4, mixture of i3/i5.
   - Memory per node: 16GiB+
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 1Gbit.
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal.
 - Number of Longhorn volumes in the cluster: 6

**Comment by innobead** [comment]
https://github.com/longhorn/longhorn/issues/5148#issuecomment-1365539963

**Comment by joshimoo** [comment]
@longhorn/qa I assume this is covered by our e2e tests but just in case is there any known issues with recurring jobs in the 1.4 Release candidates?

If not this can be closed and the user can upgrade to the official 1.4 release version, which is right around the corner :)

**Comment by innobead** [comment]
Let's close it first because issues reported from the ongoing development branch are not easy to figure out the cause. 

@khushboo-rancher can share if any test cases we have are related to retention count.  I believe @c3y1huang and @chriscchien added some test cases already.
