### ISSUE TITLE
[BUG] "Unimplemented" when attempting to delete snapshots in the UI

### ISSUE THREAD

**Issue by rlipscombe** [longhorn/longhorn#5148]
## Describe the bug (🐛 if you encounter this issue)

It doesn't seem to be possible to delete snapshots from the Longhorn UI.

## To Reproduce

Navigate to a volume.
Click on a snapshot.
Select "Delete".
It is not deleted. An error toast pops up at the top of the screen with "Unimplemented" ion it.

## Expected behavior

It should delete the snapshot.

## Environment

 - Longhorn version: master, approx Oct 2022.
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s 1.25.4
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3 at the time, now 4.
 - Node config
   - OS type and version: Ubuntu 22.04.1
   - CPU per node: 2/4, mixture of i3/i5.
   - Memory per node: 16GiB+
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 1Gbit.
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal.
 - Number of Longhorn volumes in the cluster: 6

**Comment by innobead** [comment]
Just noticed you are using `Longhorn version: master, approx Oct 2022`. Please use the official release version instead, because the master is under development and not for official usage.

**Comment by rlipscombe** [comment]
Can't. Waiting for a fix that's in 1.4.0.

**Comment by innobead** [comment]
Let's close this due to the issue reported by the ongoing development branch. @rlipscombe feel free to reopen this issue if you still encounter it from official releases. Thanks.
