### ISSUE TITLE
[BUG] System restore cannot roll out when volume name is different to the PV

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#5157]
## Describe the bug (🐛 if you encounter this issue)

system restore cannot roll out when volume name is different to the PV

## To Reproduce

1. Create volume(`test-volume`)
2. Create PV(`test-volume-pv`) and PVC(`test-volume-pvc`) from `test-volume`
3. Create a system backup
4. Delete the volume
4. Restore a system backup
5. System restore blocked

## Expected behavior

Should complete restore.

## Log or Support bundle

`N/A`

## Environment

`N/A`

## Additional context

`None`

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by yangchiu** [comment]
Verified passed on v1.4.x-head (longhorn-manager 2a65750). Create a volume and Create pv/pvc for this volume with different name from the volume name, the volume can be restored in a new cluster.
