### ISSUE TITLE
[DOC] Update the Longhorn document in Setting up Prometheus and Grafana

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#5158]
## What's the task? Please describe

After #2406 was verified, we also need to update the Longhorn document in [Setting up Prometheus and Grafana](https://longhorn.io/docs/1.4.0/monitoring/prometheus-and-grafana-setup/).

## Describe the items of the task (DoD, definition of done) you'd like

I want to update the Longhorn document in [Setting up Prometheus and Grafana](https://longhorn.io/docs/1.4.0/monitoring/prometheus-and-grafana-setup/).
After that, users could follow the Longhorn document in [Setting up Prometheus and Grafana](https://longhorn.io/docs/1.4.0/monitoring/prometheus-and-grafana-setup/) and import [Longhorn Example v1.4.0 grafana dashboard](https://grafana.com/grafana/dashboards/17626-longhorn-example-v1-4-0/)

## Additional context

N/A

**Comment by innobead** [comment]
Who created this, https://grafana.com/grafana/dashboards/17626-longhorn-example-v1-4-0/? What kind of info do you think we should add to https://longhorn.io/docs/1.4.0/monitoring/prometheus-and-grafana-setup/?

cc @PhanLe1010 @derekbit

**Comment by derekbit** [comment]
> Who created this, https://grafana.com/grafana/dashboards/17626-longhorn-example-v1-4-0/? It looks cool.

I created it and leveraged @PhanLe1010's [dashboard](https://grafana.com/grafana/dashboards/13032-longhorn-example-v1-1-0/). Just added some new metrics.

**Comment by innobead** [comment]
Thanks @derekbit and @roger-ryao :+1:

**Comment by roger-ryao** [comment]
https://github.com/longhorn/website/pull/653 was merged
