### ISSUE TITLE
[BUG] Online expansion doesn't succeed after a failed expansion

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#5169]
## Describe the bug (🐛 if you encounter this issue)

If a volume expansion fails due to failed replica, even after fixing the problem replica, the volume expansion doesn't succeed.

## To Reproduce

1. Create a volume and attach to a pod, write some data into it.
2. Expand the volume once.
3. Crash a replica: removing the volume head file and creating a directory with the volume head file name. Then the replica will go to failed state. e.g., rm volume-head-001.img && mkdir volume-head-001.img
4. Try expanding the volume, volume expansion fails.
5. Delete the failed replica and this triggers a replica rebuilding.
6. Expand volume.
7. Expansion fails

or 
1. Run the test `test_expansion_canceling` from https://github.com/longhorn/longhorn-tests/pull/1223/

## Expected behavior

Expansion at step 6 should succeed.

## Log or Support bundle

[supportbundle_bd495625-7ded-4c98-9ebb-4facfaf26008_2022-12-29T07-32-35Z.zip](https://github.com/longhorn/longhorn/files/10318163/supportbundle_bd495625-7ded-4c98-9ebb-4facfaf26008_2022-12-29T07-32-35Z.zip)

## Environment

 - Longhorn version: v1.4.x-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

**Comment by innobead** [comment]
lastExpansionError: 'the expansion succeeded, but some replica expansion failed:
      tcp://10.42.3.85:10000: error: code = FunctionFailedRollbackSucceeded, message
      = failed to expand replica 10.42.3.85:10000 from remote: failed to create new
      disk expand-9126805504: error: code = FunctionFailedRollbackFailed, message
      = link /host/var/lib/longhorn/replicas/volume-test-1-22abcf99/volume-head-003.img
      /host/var/lib/longhorn/replicas/volume-test-1-22abcf99/volume-snap-expand-9126805504.img:
      operation not permitted, rollbackMessage: remove /host/var/lib/longhorn/replicas/volume-test-1-22abcf99/volume-snap-expand-9126805504.img.meta:
      no such file or directory'

**Comment by derekbit** [comment]
Replica expansion failed at

```
2022-12-29T07:25:53.454017815Z time="2022-12-29T07:25:53Z" level=error msg="Failed to remove disk file /host/var/lib/longhorn/replicas/volume-test-1-22abcf99/volume-snap-expand-9126805504.img" error="remove /host/var/lib/longhorn/replicas/volume-test-1-22abcf99/volume-snap-expand-9126805504.img: no such file or directory"
2022-12-29T07:25:53.454023033Z time="2022-12-29T07:25:53Z" level=error msg="Failed to remove disk metadata file /host/var/lib/longhorn/replicas/volume-test-1-22abcf99/volume-snap-expand-9126805504.img.meta" error="remove /host/var/lib/longhorn/replicas/volume-test-1-22abcf99/volume-snap-expand-9126805504.img.meta: no such file or directory"
2022-12-29T07:25:53.454029651Z time="2022-12-29T07:25:53Z" level=error msg="failed to create disk expand-9126805504, will do rollback" disk=expand-9126805504 error="error: code = FunctionFailedRollbackFailed, message = link /host/var/lib/longhorn/replicas/volume-test-1-22abcf99/volume-head-003.img /host/var/lib/longhorn/replicas/volume-test-1-22abcf99/volume-snap-expand-9126805504.img: operation not permitted, rollbackMessage: remove /host/var/lib/longhorn/replicas/volume-test-1-22abcf99/volume-snap-expand-9126805504.img.meta: no such file or directory"
```

**Comment by innobead** [comment]
@shuo-wu will help test this issue for QA after the PRs merged.

**Comment by shuo-wu** [comment]
The error message caused by the previous partially succeeded expansion:
1. [blocks the upcoming expansion](https://github.com/longhorn/longhorn-manager/blob/3e27dc3561395dd9cab8c59c13618c564329fa59/controller/engine_controller.go#L875).
2. Wrongly inform users that the upcoming expansion already failed.

**Comment by shuo-wu** [comment]
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2819/

**Comment by innobead** [comment]
@khushboo-rancher this is ready for testing. @shuo-wu fix has been merged and verified.

**Comment by khushboo-rancher** [comment]
Validation - **Pass**

Verified on v1.4.x-head `12/29/2022` with the below steps, I observe the volume expansion worked fine.

1. Create a volume and attach to a pod, write some data into it.
2. Expand the volume once.
3. Crash a replica: removing the volume head file and creating a directory with the volume head file name. Then the replica will go to failed state. e.g., rm volume-head-001.img && mkdir volume-head-001.img
4. Try expanding the volume, volume expansion **PASSED**.
5. Delete the failed replica and this triggers a replica rebuilding.
6. Expand volume, volume Expansion **PASSED**

@shuo-wu I just want to confirm that at step number 4, the volume got expanded successfully. Longhorn UI doesn't show any error. Is this expected?

**Comment by shuo-wu** [comment]
As long as the volume becomes degraded and there is an event with message `Engine failed or partially failed to expand the size`, this should be fine.

**Comment by khushboo-rancher** [comment]
Thanks @shuo-wu
