### ISSUE TITLE
[TASK]  Update the distro matrix supports on Longhorn docs for 1.5

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#5177]
## What's the task? Please describe
Update the supported OS versions on our docs. https://longhorn.io/docs/1.3.2/best-practices/#operating-system

**Comment by yangchiu** [comment]
The distro matrix on Longhorn docs v1.5.0 has already been the latest: https://longhorn.io/docs/1.5.0/best-practices/#operating-system
There's nothing needed to be updated.
