### ISSUE TITLE
[TEST] Create a testing guidance for feature/regression testing

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5178]
## What's the test to develop? Please describe

Usually, QA will rely on the test cases provided by engineering to do the feature testing or bug regression testing. However, it's the potential to ignore unhappy paths. 

We should provide a non-programming framework or guidance to let QA members follow up on how to test a new feature or regression bug, not only rely on the test cases provided by engineering but also base on them and cover possible unhappy paths, especially involuntary factors/events like network partition, node reboot, node deletion, kubelet restart, etc. The framework and guidance can be like a cheat sheet. 

## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] Create a cheat sheet/framework/guidance doc for QA to guide them on how to test a feature or bug regression.

## Additional context

A good example when testing online volume expansion, https://github.com/longhorn/longhorn/issues/1674#issuecomment-1366969645

cc @longhorn/qa

**Comment by khushboo-rancher** [comment]
The doc is added https://github.com/longhorn/longhorn-tests/blob/master/qa_docs/testing_guidance.md

**Comment by innobead** [comment]
> The doc is added https://github.com/longhorn/longhorn-tests/blob/master/qa_docs/testing_guidance.md

cc @longhorn/qa
