### ISSUE TITLE
[BUG] With longhorn 1.4.0, k8s 1.25, and `enablePSP: false` in Helm chart, still getting `resource mapping not found for name: "longhorn-psp" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"`

### ISSUE THREAD

**Issue by sseneca** [longhorn/longhorn#5185]
## Describe the bug (🐛 if you encounter this issue)

With the latest Longhorn 1.4.0 (bumped from 1.2.3), the latest Helm chart (with `enablePSP: false` set), doing a Helm Upgrade (via Flux) still does not work:

```
► resuming helmrelease longhorn in longhorn-system namespace
✔ helmrelease resumed
◎ waiting for HelmRelease reconciliation
✗ Helm upgrade failed: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "longhorn-psp" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
```

## To Reproduce

1. Longorn running on 1.2.3
2. Update Flux manifests to 1.4.0
3. See above error

## Expected behavior

It should install correctly. My cluster does not have PSP anymore, but even with `enablePSP: false` it's complaining that it can't find PSP?

## Environment

 - Longhorn version: 1.2.3 -> 1.4.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Flux/HelmRelease
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 1 (main node is also the worker node)
 - Node config
   - OS type and version:Arch Linux
   - CPU per node:1
   - Memory per node:8gb
   - Disk type(e.g. SSD/NVMe):hdd
   - Network bandwidth between the nodes:n/a
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal
 - Number of Longhorn volumes in the cluster:9

**Comment by innobead** [comment]
cc @longhorn/qa see if we can reproduce this.

@yangchiu please help with this.

**Comment by yangchiu** [comment]
With `k8s v1.24.7`, I can upgrade Longhorn from `v1.2.3` to `v1.4.0` using `helm` without problems, all Longhorn components are running without errors after upgrade.

Steps:
(1) `helm install longhorn longhorn/longhorn --namespace longhorn-system --version 1.2.3`
(2) In longhorn/longhorn repository, `git checkout v1.4.0`, and check `enablePSP` value => It's disabled by default: `enablePSP: false`
(3) Upgrade Longhorn to `v1.4.0`: `helm upgrade longhorn ./longhorn/chart -n longhorn-system`

But the user mentioned `k8s v1.25` in the title. I'm not sure when did he upgrade the k8s version (since Longhorn `v1.2.3` doesn't support `k8s v1.25`). @sseneca Could you help to illustrate more about your (k8s) upgrade path?

**Comment by innobead** [comment]
Thanks, @sseneca update. 

The failure is caused by upgrading to Longhorn 1.4.0 from the crashed longhorn 1.2.x after you upgraded the K8s cluster to K8s 1.25, because the originally installed Longhorn PSP should be uninstalled first when doing helm upgrade, but it's can be found from the cluster which is 1.25 already.

```
Helm upgrade failed: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "longhorn-psp" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```

The right flow is to upgrade to 1.4.0 before upgrading the K8s cluster to 1.25. It's good to know everything is fine now. 

ref: https://github.com/longhorn/longhorn/issues/4003#issuecomment-1350574289

cc @longhorn/qa

**Comment by Michaelpalacce** [comment]
@innobead So when we've upgraded to longhorn 1.4.0 from 1.2.x after upgrading my cluster to 1.25, then the cluster can no longer be salvaged?

**Comment by gravufo** [comment]
> @innobead So when we've upgraded to longhorn 1.4.0 from 1.2.x after upgrading my cluster to 1.25, then the cluster can no longer be salvaged?

You can have fun with this: https://helm.sh/docs/topics/kubernetes_apis/#updating-api-versions-of-a-release-manifest
But instead of updating the API versions, you need to actually just remove the resources.

What I did on my side was just simply delete the helm secret/configmap to make helm think nothing was installed and simply installed the new version of longhorn on top of the existing resources.

It's really a shame that k8s/helm can't make this a little more elegant.

**Comment by luizjr** [comment]
> > @innobead So when we've upgraded to longhorn 1.4.0 from 1.2.x after upgrading my cluster to 1.25, then the cluster can no longer be salvaged?
> 
> You can have fun with this: https://helm.sh/docs/topics/kubernetes_apis/#updating-api-versions-of-a-release-manifest But instead of updating the API versions, you need to actually just remove the resources.
> 
> What I did on my side was just simply delete the helm secret/configmap to make helm think nothing was installed and simply installed the new version of longhorn on top of the existing resources.
> 
> It's really a shame that k8s/helm can't make this a little more elegant.

You saved my day!

No other way was working

**Comment by connde** [comment]
> > @innobead So when we've upgraded to longhorn 1.4.0 from 1.2.x after upgrading my cluster to 1.25, then the cluster can no longer be salvaged?
> 
> You can have fun with this: https://helm.sh/docs/topics/kubernetes_apis/#updating-api-versions-of-a-release-manifest But instead of updating the API versions, you need to actually just remove the resources.
> 
> What I did on my side was just simply delete the helm secret/configmap to make helm think nothing was installed and simply installed the new version of longhorn on top of the existing resources.
> 
> It's really a shame that k8s/helm can't make this a little more elegant.

Thanks, that solved my issue, was trying to upgrade from 1.4.0 to 1.4.1 and was getting this error.

**Comment by MrOwen** [comment]
Can't thank you enough for this. Thought my resources were going to double for a sec but all was taken care of and I was also successful upgrading the chart and engine updates.

**Comment by polds** [comment]
I attempted the same, but hit an issue with the new longhorn-manager crashing with the error:


>1 reflector.go:324] github.com/longhorn/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:117 Failed to watch *v1beta2.Snapshot: failed to list *v1beta2.Snapshot: the server could not find the requested resource (get snapshots.longhorn.io)
> 1 reflector.go:324] github.com/longhorn/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:117: failed to list *v1beta2.Snapshot: the server could not find the requested resource (get snapshots.longhorn.io)

I indeed do not appear to have a snapshots.longhorn.io CRD available, but am unsure why it wasn't installed.

**Comment by thomasherrle** [comment]
> > @innobead So when we've upgraded to longhorn 1.4.0 from 1.2.x after upgrading my cluster to 1.25, then the cluster can no longer be salvaged?
> 
> You can have fun with this: https://helm.sh/docs/topics/kubernetes_apis/#updating-api-versions-of-a-release-manifest But instead of updating the API versions, you need to actually just remove the resources.
> 
> What I did on my side was just simply delete the helm secret/configmap to make helm think nothing was installed and simply installed the new version of longhorn on top of the existing resources.
> 
> It's really a shame that k8s/helm can't make this a little more elegant.

Hello @gravufo,
I'm facing the same issue. Can you elaborate what exactly you deleted? Because in my mind secret is not equal configmap. 
If I understand correctly you didn't change or remove the psp resource from the release secret?

**Comment by gravufo** [comment]
> Hello @gravufo, I'm facing the same issue. Can you elaborate what exactly you deleted? Because in my mind secret is not equal configmap. If I understand correctly you didn't change or remove the psp resource from the release secret?

Helm creates secrets or configmaps to store the releases you install, their settings and history. They are called something similar to "sh.helm.release.v1.longhorn.v1". Simply delete this and reinstall fresh.

**Comment by Elsvent** [comment]
> > > Hello @gravufo, I'm facing the same issue. Can you elaborate what exactly you deleted? Because in my mind secret is not equal configmap. If I understand correctly you didn't change or remove the psp resource from the release secret?
> > 
> > 
> > Helm creates secrets or configmaps to store the releases you install, their settings and history. They are called something similar to "sh.helm.release.v1.longhorn.v1". Simply delete this and reinstall fresh.
> 
> Thanks for your quick reply. What I ended up doing is using the helm plugin _helm-mapkubeapis_ which maps deprecated or removed Kubernetes APIs in a release to supported APIs (https://github.com/helm/helm-mapkubeapis). In the end is was a single command and after that the helm upgrade was working again.
> 
> `helm mapkubeapis longhorn --namespace longhorn-system`

You saved my life thanks a lot

**Comment by csib** [comment]
I've got about the same problem, I've upgraded longhorn from helm.sh/chart=longhorn-101.1.0_up1.3.2 to 102.3.0+up1.5.1, but after that the Helm in Rancher's UI says error.

Tried the helm mapkubeapis longhorn --namespace longhorn-system solution, which not helped, after that I tried to delete the sh.helm.release.v1.longhorn-crd.v1 and v2, v3 from my cluster, then installed Longhorn again, with version 102.3.0+up1.5.1.

During the installing now I am receiving error like:
`Looks like there are no changes for Service "longhorn-backend"
2023-09-11T20:11:59.060926642Z Patch Service "longhorn-frontend" in namespace longhorn-system
Created a new Service called "longhorn-conversion-webhook" in longhorn-system

2023-09-11T20:11:59.110953775Z Created a new Service called "longhorn-admission-webhook" in longhorn-system
2023-09-11T20:11:59.111762052Z 
2023-09-11T20:11:59.128366662Z Looks like there are no changes for Service "longhorn-recovery-backend"
Looks like there are no changes for Service "longhorn-engine-manager"
2023-09-11T20:11:59.158249999Z Looks like there are no changes for Service "longhorn-replica-manager"
2023-09-11T20:11:59.188055349Z Patch DaemonSet "longhorn-manager" in namespace longhorn-system
2023-09-11T20:11:59.199823249Z error updating the resource "longhorn-manager":
2023-09-11T20:11:59.200053432Z 	 cannot patch "longhorn-manager" with kind DaemonSet: DaemonSet.apps "longhorn-manager" is invalid: spec.template.spec.containers[0].readinessProbe.tcpSocket: Forbidden: may not specify more than 1 handler type
Looks like there are no changes for Deployment "longhorn-driver-deployer"
2023-09-11T20:11:59.235284780Z Looks like there are no changes for Deployment "longhorn-ui"
2023-09-11T20:11:59.267563721Z Error: cannot patch "longhorn-manager" with kind DaemonSet: DaemonSet.apps "longhorn-manager" is invalid: spec.template.spec.containers[0].readinessProbe.tcpSocket: Forbidden: may not specify more than 1 handler type`


Any idea what I missed during the process? Now, the longhorn-crd chart is deployed properly, but the longhorn chart is in error state.

**Comment by csib** [comment]
I figured it out.
Those who also want to upgrade like this, a little side-note from here: https://longhorn.io/docs/1.5.1/deploy/upgrade/longhorn-manager/

> We only support upgrading to v1.5.1 from v1.4.x. For other versions, please upgrade to v1.4.x first.

I was able to do this unsupported thing, I think it should be visible on Rancher UI, because I've done an upgrade from 1.3 to 1.5.

**I was able to upgrade to 1.4 then to 1.5**
