### ISSUE TITLE
[FEATURE] Introduce faster compression and multiple threads for volume backup & restore 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5189]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The backup mechanism in Longhorn is not efficient as investigated in https://github.com/longhorn/longhorn/issues/1409.

Besides the refactoring, the task will cover 

**Backup**
- [x] Global backup compression setting
- [x] Per-volume backup compression setting (`volume.spec.backupCompressionMethod`)
- [x] Introduce faster compression algorithms, lz4 or zstd, into longhorn, but still need to handle backward compatibility, i.e. for the existing backups using gzip.
  - none: suitable for encoding data, e.g. encoded image and video
  - lz4: suitable for text data
  - gzip: a bit of higher compression ratio but slow. (not recommended)
- [x] Concurrent compression and transfer workers
  - Introduce producer-consumer pattern
  - Improve the compression and upload throughput

**Restore**
- [x] Concurrent decompression and transfer workers

## Additional context

https://github.com/longhorn/longhorn/issues/1409
https://github.com/longhorn/longhorn/issues/3900
https://github.com/longhorn/longhorn/issues/3175
https://github.com/longhorn/longhorn/issues/4379

**Comment by derekbit** [comment]
**Setup**
Platform: Equinix
Host: Japan-Tokyo/m3.small.x86
CPU: Intel(R) Xeon(R) E-2378G CPU @ 2.80GHz
RAM: 64 GiB
Disk: Micron_5300_MTFD
OS: Ubuntu 22.04.1 LTS(kernel 5.15.0-53-generic)
Kubernetes: v1.23.6+rke2r2
Longhorn: master-branch + backup improvement

Backupstore target: external MinIO S3 (m3.small.x86)


**Single-Thread Backup and Restore**
Volume: 50 GiB containing 10 GiB random data

![Single-Thread Backup and Restore](https://user-images.githubusercontent.com/12527233/210484515-3e7aff41-eab8-447e-b007-8c05e22c0364.svg)

**Comment by derekbit** [comment]
In summary, the backup throughput is increased by 15X using `lz4` and `5` concurrent threads.

**Setup**
Platform: Equinix
Host: Japan-Tokyo/m3.small.x86
CPU: Intel(R) Xeon(R) E-2378G CPU @ 2.80GHz
RAM: 64 GiB
Disk: Micron_5300_MTFD
OS: Ubuntu 22.04.1 LTS(kernel 5.15.0-53-generic)
Kubernetes: v1.23.6+rke2r2
Longhorn: master-branch + backup improvement

Backupstore target: external MinIO S3 (m3.small.x86)

**Single-Threaded Backup and Restore**
Volume: 50 GiB containing 10 GiB random data
![Single-Threaded Backup and Restore](https://user-images.githubusercontent.com/12527233/210503394-2038f238-47d2-4b99-9c4e-023badf485ad.svg)

**Multiple-Threaded Backup**

![Multi-Threaded Backup](https://user-images.githubusercontent.com/12527233/210503426-99c04193-e1ca-4963-aa75-fd012fa23393.svg)

**Comment by innobead** [comment]
This is wonderful :fireworks:

**Comment by innobead** [comment]
> In summary, the backup throughput is increased by 15X when using `lz4` and `10` concurrent threads in comparison with the backup in Longhorn v1.4.0.

This is wonderful and awesome :fireworks:

**Comment by joshimoo** [comment]
Make sure to introduce a backup format version, this way it's easy to implement the backwards compatibility.
We also want to use much larger blocks in the new version, consider going from current 2MB -> 16MB -> 64MB this will improve the compression but further also reduce the amount of block files, which will lower the cost for the S3 lookups. I am thinking 16MB could be a good middle ground. 

This is optional but for larger volumes it would be nice if we can dynamically switch to 64MB, perhaps a block size field in the new backup v2 version?

**Comment by innobead** [comment]
This feature is straightforward, but still, requires an LEP to make this feature cycle complete.

**Comment by derekbit** [comment]
Continue the test of https://github.com/longhorn/longhorn/issues/5189#issuecomment-1370564456

The restore throughput is increased by 140% when using` lz4` and `10` concurrent threads in comparison with the backup in Longhorn v1.4.0.

![Multi-Threaded Restore](https://user-images.githubusercontent.com/12527233/211040461-9f0177fc-fc3b-4a43-a8c0-c4e5b39b987a.svg)

**Comment by derekbit** [comment]
> Continue the test of [#5189 (comment)](https://github.com/longhorn/longhorn/issues/5189#issuecomment-1370564456)
> 
> The restore throughput is increased by 140% when using `lz4` and `10` concurrent threads in comparison with the backup in Longhorn v1.4.0.
> 
> ![Multi-Threaded Restore](https://user-images.githubusercontent.com/12527233/211040461-9f0177fc-fc3b-4a43-a8c0-c4e5b39b987a.svg)

Restore looks hit the IO bound, bacause the restore throught is saturated after 5 worker threads. Will re-test it using a RAID-0.

**Comment by zamazan4ik** [comment]
Could you please also add `zstd` to your tests? Thanks!

**Comment by derekbit** [comment]
> Could you please also add `zstd` to your tests? Thanks!

I tested zstd before, and you can refer to https://github.com/longhorn/longhorn/issues/1409#issuecomment-948693046.
If you would like to introduce zstd, please open a feature request. Thank you.

**Comment by derekbit** [comment]
> **Verified on master-head 20230213**
> 
> * longhorn master-head ([b1ed058](https://github.com/longhorn/longhorn/commit/b1ed0589b28a8dd510df6396267810fe6d6748a4))
> * longhorn-engine master-head ([58d75a7](https://github.com/longhorn/longhorn-engine/commit/58d75a751980b1960149dacf574d5f6904bacdd8))
> * longhorn-instance-manager master-head ([6636abe](https://github.com/longhorn/longhorn-instance-manager/commit/6636abe79ec9797c58612bd3ad1595c33f20c7a2))
> * longhorn-manager master-head ([37500d0](https://github.com/longhorn/longhorn-manager/commit/37500d090bd9147ce8b084584cb0d1cd192f6c8a))
> 
> **Pre-requisite** Backupstore target: external MinIO S3
> 
> **The test steps**
> 
> 1. Deploy Longhorn master-head
> 2. Create one 50GiB volume vol-0 and then write 20GiB data
> 3. Get the data md5sum
> 4. Setting > General >　`Backup Compression Method` > `none`
> 5. Backup vol-0
> 6. Restore vol-0 from the backup.
> 7. Create one 50GiB volume vol-2 and then write 20GiB data
> 8. Get the data md5sum
> 9. Setting > General >　`Backup Compression Method` > `lz4`
> 10. Backup vol-2
> 11. Restore vol-2 from the backup.
> 12. Create one 50GiB volume vol-3 and then write 20GiB data
> 13. Get the data md5sum
> 14. Setting > General >　`Backup Compression Method` > `gzip`
> 15. Backup vol-3
> 16. Restore vol-3 from the backup.
> 17. Download the support bundle and check `instance-manager-r-XXXX/replica-manager.log`
> 
> **Result Passed**
> 
> 1. The backup execution time is expected.
> 
> ![Screenshot_20230213_205427](https://user-images.githubusercontent.com/104337648/218467581-e107db67-659f-49a5-8e40-bf7ea34f928b.png)
> 
> ![Screenshot_20230213_205446](https://user-images.githubusercontent.com/104337648/218467667-44d3cba3-bbaf-4e1a-82f5-61bf8cdb00ef.png)
> 
> ```
> 2023-02-13T12:15:39.292064692Z [vol-3-r-00ffea28] time="2023-02-13T12:15:39Z" level=info msg="Starting backup for &{vol-3 53687091200 map[KubernetesStatus:{\"pvName\":\"vol-3\",\"pvStatus\":\"Bound\",\"namespace\":\"default\",\"pvcName\":\"vol-3\",\"lastPVCRefAt\":\"\",\"workloadsStatus\":[{\"podName\":\"ubuntu-mountvol3\",\"podStatus\":\"Running\",\"workloadName\":\"\",\"workloadType\":\"\"}],\"lastPodRefAt\":\"\"} VolumeRecurringJobInfo:{} longhorn.io/volume-access-mode:rwo] 2023-02-13T12:15:39Z   0   none}, snapshot &{f6422380-bbb3-425a-9c95-e1afeb3d9915 2023-02-13T12:15:39Z}, dest s3://backupbucket@us-east-1/" pkg=backup
> 2023-02-13T12:15:39.300818235Z [vol-3-r-00ffea28] time="2023-02-13T12:15:39Z" level=info msg="Loaded driver for s3://backupbucket@us-east-1/" pkg=s3
> 2023-02-13T12:15:41.323954291Z [vol-3-r-00ffea28] time="2023-02-13T12:15:41Z" level=info msg="Added backupstore volume vol-3" pkg=backupstore
> 2023-02-13T12:15:41.498046649Z [vol-3-r-00ffea28] time="2023-02-13T12:15:41Z" level=info msg="Done initiating backup creation, received backupID: backup-743b9e0b2f3b4b84"
> 2023-02-13T12:15:41.502717391Z [vol-3-r-00ffea28] time="2023-02-13T12:15:41Z" level=info msg="Volume vol-3 Snapshot f6422380-bbb3-425a-9c95-e1afeb3d9915 is consist of 10569 mappings and 10569 blocks"
> 2023-02-13T12:24:34.147623000Z [vol-3-r-00ffea28] time="2023-02-13T12:24:34Z" level=info msg="Created snapshot changed blocks: 10569 mappings, 10569 blocks and 10026 new blocks" event=backup object=snapshot pkg=backupstore reason=complete snapshot=f6422380-bbb3-425a-9c95-e1afeb3d9915
> ```
> 
> [supportbundle_6472c308-3572-4f24-98f4-402ad495a019_2023-02-13T12-41-39Z.zip](https://github.com/longhorn/longhorn/files/10722495/supportbundle_6472c308-3572-4f24-98f4-402ad495a019_2023-02-13T12-41-39Z.zip)

Weird. Why are the performances of the three compressions so closed?
Can you try set the compression method first and then create a new volume? Then, check if the `volume.spec.backupCompressionMethod` is expected.
Thank you.

**Comment by roger-ryao** [comment]
> Weird. Why are the performances of the three compressions so closed? Can you try set the compression method first and then create a new volume? Then, check if the `volume.spec.backupCompressionMethod` is expected. Thank you.

Hi @derekbit :
      I set the compression method first and then create volume. the `volume.spec.backupCompressionMethod` is expected. We create volume first and then set the different compression methods. When we backup volume, would the volume's compression method be changed?

**Threads = 1**
![Screenshot_20230213_234450](https://user-images.githubusercontent.com/104337648/218601968-d8171a69-4704-4d1f-ba5d-b3293b17740a.png)

**Threads = 5**
![Screenshot_20230213_234429](https://user-images.githubusercontent.com/104337648/218601994-742b114b-f7ab-4d36-a678-dd57150ffd3c.png)


**The test steps**

1. Deploy Longhorn master-head
2. Setting > General >　`Backup Compression Method` > `none`
3. Create one 50GiB volume vol-0 and then write 20GiB data
4. Backup vol-0
5. Setting > General >　`Backup Compression Method` > `lz4`
6. Create one 50GiB volume vol-2 and then write 20GiB data
7. Backup vol-2
8. Setting > General >　`Backup Compression Method` > `gzip`
9.  Create one 50GiB volume vol-3 and then write 20GiB data
10. Backup vol-3
11. Download support bundle and check `instance-manager-r-XXXX/replica-manager.log`
[supportbundle_6472c308-3572-4f24-98f4-402ad495a019_2023-02-13T15-45-13Z.zip](https://github.com/longhorn/longhorn/files/10727319/supportbundle_6472c308-3572-4f24-98f4-402ad495a019_2023-02-13T15-45-13Z.zip)

**Comment by derekbit** [comment]
> I test it on AWS and the instance type is t2.xlarge. I set the compression method first and then create volume. the volume.spec.backupCompressionMethod is expected.

Yeah, it's expected. Thank you.

**Comment by roger-ryao** [comment]
Hi @derekbit :
    I verified it again. The detail as below.
    
**Verified on master-head 20230214**

- longhorn master-head ([bb1bd7d](https://github.com/longhorn/longhorn/commit/bb1bd7d4db8d5fd6e0473f11b2d407563d80a5b2)) 
- longhorn-engine master-head ([a26f857](https://github.com/longhorn/longhorn-engine/commit/a26f8576aa9db2028d41fa9204fba60c5420bf48))
- longhorn-instance-manager master-head ([18affde](https://github.com/longhorn/longhorn-instance-manager/commit/18affde3bcdb30f7cbf8529dbded800af741d7b1))
- longhorn-manager master-head ([37500d0](https://github.com/longhorn/longhorn-manager/commit/37500d090bd9147ce8b084584cb0d1cd192f6c8a))

**Pre-requisite**
Backupstore target: external MinIO S3
instance type : **c5d.2xlarge**

**The test steps**

1. Deploy Longhorn master-head
2. Setting > General >　`Backup Compression Method` > `none`
3. Create one 50GiB volume vol-0 and then write 20GiB data
`dd if=/dev/urandom of=/data/20G count=20000 bs=1M conv=fsync status=progress`
4. Get the data md5sum and check vol-0 `volume.spec.backupCompressionMethod`
`kubectl -n longhorn-system describe volumes.longhorn.io vol-0 |grep "Backup Compression Method"`
5. Backup vol-0
6. Restore vol-0 from the backup.
7. Check md5sum of the data in the restored volume
8. Setting > General >　`Backup Compression Method` > `lz4`
9. Create one 50GiB volume vol-2 and then write 20GiB data
`dd if=/dev/urandom of=/data/20G count=20000 bs=1M conv=fsync status=progress`
1. Get the data md5sum and check vol-2 `volume.spec.backupCompressionMethod`
`kubectl -n longhorn-system describe volumes.longhorn.io vol-0 |grep "Backup Compression Method"`
1.  Backup vol-2
2.  Restore vol-2 from the backup.
3.  Check md5sum of the data in the restored volume
4.  Setting > General >　`Backup Compression Method` > `gzip`
5.  Create one 50GiB volume vol-3 and then write 20GiB data
`dd if=/dev/urandom of=/data/20G count=20000 bs=1M conv=fsync status=progress`
1.  Get the data md5sum and check vol-3 `volume.spec.backupCompressionMethod`
`kubectl -n longhorn-system describe volumes.longhorn.io vol-0 |grep "Backup Compression Method"`
1.  Backup vol-3
2.  Restore vol-3 from the backup.
3.  Check md5sum of the data in the restored volume
4.  Download support bundle and check `instance-manager-r-XXXX/replica-manager.log`


**The test steps**
1. the volume.spec.backupCompressionMethod is expected.
![Screenshot_20230214_105921](https://user-images.githubusercontent.com/104337648/218642310-df38749c-b665-455d-89b3-d0c35db78f37.png)
![Screenshot_20230214_112024](https://user-images.githubusercontent.com/104337648/218642318-dfb7db59-29f5-47fa-8b5f-56a5ecae75c4.png)
![Screenshot_20230214_114811](https://user-images.githubusercontent.com/104337648/218642329-9f10e6fc-8807-4567-a77e-b4052ea72599.png)

2. The performances of the three compressions is expected
![Screenshot_20230214_125140](https://user-images.githubusercontent.com/104337648/218642376-cbaf3e79-e5db-4089-ae00-54e624077900.png)
[supportbundle_50213bd3-9b2e-4bd1-92f5-02761334ffc7_2023-02-14T04-39-25Z.zip](https://github.com/longhorn/longhorn/files/10728875/supportbundle_50213bd3-9b2e-4bd1-92f5-02761334ffc7_2023-02-14T04-39-25Z.zip)
