### ISSUE TITLE
[BUG] Trim support for qemu backed VM k8s nodes

### ISSUE THREAD

**Issue by TheReal1604** [longhorn/longhorn#5203]
## Describe the bug (🐛 if you encounter this issue)

After upgrading to v1.4.0 I tried to use the trim support for longhorn volumes, there i noticed this error message in the webui:

```
unable to trim filesystem for volume data-postgresql-synapse-matrix: cannot find volume data-postgresql-synapse-matrix mount info on host: failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net fstrim /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/1bee2958ab800e3c45a85191b155e3558ebc12ac9c444f8b405c11e22e2382a9/globalmount], output , stderr fstrim: /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/1bee2958ab800e3c45a85191b155e3558ebc12ac9c444f8b405c11e22e2382a9/globalmount: the discard operation is not supported : exit status 1
```

For my k8s nodes, I use a public cloud provider which seems to host the VMs on qemu / kvm backed hypervisors. I guess this is a limitation from the qemu harddisk (not enabled trim support) which is kind of inherited by the longhorn volumes?

## To Reproduce

1. Create k8s workers on qemu / kvm backed hypervisors
2. Create a longhorn volume
3. Try the trim support feature on the webui in v1.4.0

## Expected behavior

Trim should work for the longhorn volumes. 

## Environment

 - Longhorn version: 1.4.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k8s 1.24.3
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: ubuntu 20.04 lts
   - CPU per node: 4
   - Memory per node: 16 GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 1Gbit/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Public Cloud (probably KVM)
 - Number of Longhorn volumes in the cluster: 10~

**Comment by innobead** [comment]
cc @shuo-wu

**Comment by shuo-wu** [comment]
Just in case, is `fstrim` applied to the new volumes created after Longhorn v1.4.0 launch? For the volumes that are live upgraded from the old versions (without experiencing re-attachment) or the volumes using old engine images, the Longhorn trim feature will not work.

You can test if `fstrim` is supported by your env via the below test steps:
1. Create a file in the worker node data path.
```
# touch test-blk
# truncate -s 5G test-blk
```
2. Directly make a filesystem and mount it without any extra flags.
```
# mkfs.ext4 blk
# mount blk <mount point>
```
3. Write some files into the mount point then delete them. And verify the block device file actual size is increased
```
# dd if=/dev/urandom of=<mount point>/data bs=1M count=500
# rm <mount point>/data
# du -h blk
```
4. Do `fstrim` for the mount point and see if there are any errors
```
# fstrim <mount point>
```

**Comment by innobead** [comment]
> Just in case, is `fstrim` applied to the new volumes created after Longhorn v1.4.0 launch? For the volumes that are live upgraded from the old versions (without experiencing re-attachment) or the volumes using old engine images, the Longhorn trim feature will not work.

We probably should empathize with this in general when any new volume functions are introduced to a new release, they will only take effect when volume reattachment. @shuo-wu WDYT?

**Comment by shuo-wu** [comment]
Sure. I will update the doc.

**Comment by TheReal1604** [comment]
That was the point! I didnt reattached the volumes. After recreating the pods and reattaching - the TRIM command now works. Thanks!
