### ISSUE TITLE
[FEATURE] Consolidate Instance Manager Engine & Replica for resource consumption reduction

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5208]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Currently, we will have an instance manager engine & replica pods on each node, and each of them will have a default 12% Guaranteed CPU request which is configurable. After upgrading Longhorn, there will be another two new instance manager pods running, so there will be four instance managers pods before all volumes are migrated to the new version. This causes high resource requirements for the fresh install and upgrade as well. 

Engine/Replica processes running in the instance manager are process-based, so they will not impact the instance manager container. To simplify the architecture to decrease resource usage, the goal here is to consolidate the instance manager engine & replica to one pod, but continue serving all data plane operations on each node without any change. For volume migration, the same flow is as usual. 

## Describe the solution you'd like

- [x] Introduce the new architecture of the instance manager
- [x] Revamp the current automatic engine upgrade implementation
- [ ] Benchmark the resource consumption based on the number/size of volume. Have a theoretical explanation for the resource usage by instance manager. 

## Additional context

https://github.com/rancher/image-mirror/pull/329#issuecomment-1376715530

cc @longhorn/dev

**Comment by c3y1huang** [comment]
Note: https://github.com/longhorn/longhorn/issues/1691#issuecomment-729633995

**Comment by c3y1huang** [comment]
Initial test results:
- core tests: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3112/
- WIP

**Comment by c3y1huang** [comment]
@longhorn/qa , please also do some tests using the UI, thanks!

**Comment by yangchiu** [comment]
Tested on master-head, although there are volumes created and attached, the `Ref Count Volume` in `Instance Manager Image` page is always `0`, and the `Volumes` modal of each instance manager is always empty:

![Screenshot from 2023-05-04 13-52-25](https://user-images.githubusercontent.com/5709208/236133046-f96e2456-5c42-4ba5-a746-b3fd042d071e.png)

![Screenshot from 2023-05-04 13-52-41](https://user-images.githubusercontent.com/5709208/236133066-e3096366-c589-4417-9398-7af364c21bd6.png)

Also the `Instance Manager Image` in `Components` modal of each node is `N/A`:

![Screenshot from 2023-05-04 13-51-53](https://user-images.githubusercontent.com/5709208/236133350-e91282a0-9e00-4517-a689-fd7f2048264d.png)

Not sure if it's normal. @c3y1huang

**Comment by innobead** [comment]
This is not right. 

@yangchiu btw, do you know if we have any e2e test cases related to the reference count of instance image?

**Comment by yangchiu** [comment]
> This is not right.
> 
> @yangchiu btw, do you know if we have any e2e test cases related to the reference count of instance image?

We only have test cases for engine image reference count, and there's no test case for instance manager reference count.

**Comment by c3y1huang** [comment]
> Tested on master-head, although there are volumes created and attached, the `Ref Count Volume` in `Instance Manager Image` page is always `0`, and the `Volumes` modal of each instance manager is always empty:
> 
> ![Screenshot from 2023-05-04 13-52-25](https://user-images.githubusercontent.com/5709208/236133046-f96e2456-5c42-4ba5-a746-b3fd042d071e.png)
> 
> ![Screenshot from 2023-05-04 13-52-41](https://user-images.githubusercontent.com/5709208/236133066-e3096366-c589-4417-9398-7af364c21bd6.png)
> 
> Also the `Instance Manager Image` in `Components` modal of each node is `N/A`:
> 
> ![Screenshot from 2023-05-04 13-51-53](https://user-images.githubusercontent.com/5709208/236133350-e91282a0-9e00-4517-a689-fd7f2048264d.png)
> 
> Not sure if it's normal. @c3y1huang

Thanks @yangchiu , this should be related to the UI as we have not yet implemented support for the new `aio` instance managers., for example: https://github.com/longhorn/longhorn-ui/blob/master/src/models/host.js#L122-L127.

Let's track the UI implementation in https://github.com/longhorn/longhorn/issues/5876

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 6631855, longhorn-ui 51e912d). Operations work well on Longhorn ui, and it presenta the correct information about the new `aio` type of instance manager. [The above mentioned ui issue](https://github.com/longhorn/longhorn/issues/5208#issuecomment-1534189713) has been corrected.
