### ISSUE TITLE
[BUG] Fresh 1.4.0 install never completes

### ISSUE THREAD

**Issue by samirski** [longhorn/longhorn#5212]
## Describe the bug (🐛 if you encounter this issue)

Trying to install 1.4.0 version on my cluster, installation never completes. Followed the instructions from the official documentation to make sure that all requirements are met which is the case. The only challenge that I face is regarding mount propagation. The documentation covers configuration based on Docker container runtime. Since my cluster leverages containerd as the runtime could not find any documentation on how to enable mount propagation in that case.

Anyway, running environment check script produces the following output:

    [INFO]  All longhorn-environment-check pods are ready (6/6).
    [WARN]  Unable to check kernel config CONFIG_NFS_V4_1 on node node1
    [WARN]  Unable to check kernel config CONFIG_NFS_V4_1 on node node3
    [WARN]  Unable to check kernel config CONFIG_NFS_V4_1 on node node2
    [WARN]  Unable to check kernel config CONFIG_NFS_V4_1 on node node5
    [WARN]  Unable to check kernel config CONFIG_NFS_V4_1 on node node4
    [WARN]  Unable to check kernel config CONFIG_NFS_V4_1 on node node6
    [WARN]  Unable to check kernel config CONFIG_NFS_V4_2 on node node1
    [WARN]  Unable to check kernel config CONFIG_NFS_V4_2 on node node3
    [WARN]  Unable to check kernel config CONFIG_NFS_V4_2 on node node2
    [WARN]  Unable to check kernel config CONFIG_NFS_V4_2 on node node5
    [WARN]  Unable to check kernel config CONFIG_NFS_V4_2 on node node4
    [WARN]  Unable to check kernel config CONFIG_NFS_V4_2 on node node6
    [WARN]  NFS client kernel support, CONFIG_NFS_V4_1 CONFIG_NFS_V4_2, is not enabled on Longhorn nodes. Please refer to https://longhorn.io/docs/1.4.0/deploy/install/#installing-nfsv4-client for more information.
    [INFO]  Required packages are installed.
    [INFO]  Cleaning up longhorn-environment-check pods...
    [INFO]  Cleanup completed.

NFSv4.1 check output:

    CONFIG_NFS_V4_1=y
    CONFIG_NFS_V4_1_IMPLEMENTATION_ID_DOMAIN="kernel.org"
    CONFIG_NFS_V4_1_MIGRATION=y

NFSv4.2 check output:

    CONFIG_NFS_V4_2=y
    # CONFIG_NFS_V4_2_READ_PLUS is not set
    CONFIG_NFS_V4_2_SSC_HELPER=y

Here are the pods in `longhorn-system` namespace:

    NAME                                           READY   STATUS             RESTARTS         AGE
    longhorn-admission-webhook-6489cc5747-6zbrs    0/1     Init:0/1           0                68m
    longhorn-admission-webhook-6489cc5747-7mnzf    0/1     Init:0/1           0                68m
    longhorn-conversion-webhook-58b5f48bbd-l994t   1/1     Running            0                68m
    longhorn-conversion-webhook-58b5f48bbd-mq59q   1/1     Running            0                68m
    longhorn-driver-deployer-7fdddb9f99-2fzvs      0/1     Init:0/1           0                68m
    longhorn-manager-9nsdl                         0/1     Init:0/1           0                68m
    longhorn-manager-fqr9q                         0/1     Init:0/1           0                68m
    longhorn-manager-hpgtm                         0/1     Init:0/1           0                68m
    longhorn-manager-jnnqw                         0/1     Init:0/1           0                68m
    longhorn-manager-mpz7x                         0/1     Init:0/1           0                68m
    longhorn-manager-qjzzn                         0/1     Init:0/1           0                68m
    longhorn-recovery-backend-d67444cf5-6p95w      1/1     Running            0                68m
    longhorn-recovery-backend-d67444cf5-mhk2l      1/1     Running            0                68m
    longhorn-ui-6768fbbc6c-x6k2q                   0/1     CrashLoopBackOff   17 (3m49s ago)   68m
    longhorn-ui-6768fbbc6c-xj89m                   0/1     CrashLoopBackOff   17 (3m26s ago)   68m

While checking the logs of the pending pods I see that Init Containers `waiting` on something: 

    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting
    waiting

Otherwise there are no errors in the logs. 

## To Reproduce

3. Perform '....'

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.4.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Kubespray 1.25.4
   - Number of management node in the cluster: 2
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: Ubuntu 22.04
   - CPU per node: 4
   - Memory per node: 8gb
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 1G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: n/a

**Comment by derekbit** [comment]
Can you provide your `/boot/config-$(uname -r)` for improving the nfs client checks? Thanks.

For the installation failure, can you check your coredns pods? or show `kubectl get pods -A`.

**Comment by samirski** [comment]
coredns pods are running fine:

    kube-system       coredns-588bb58b94-4fk4f                       1/1     Running            3 (9d ago)     26d
    kube-system       coredns-588bb58b94-pqpb5                       1/1     Running            3 (9d ago)     26d

Also as requested attaching /boot/config file:
[boot_config_5.15.zip](https://github.com/longhorn/longhorn/files/10350376/boot_config_5.15.zip)

**Comment by derekbit** [comment]
@samirski 
admission-webhook pods is waiting for the conversion webhook pods. It seems the  something wrong in network.  Can you check https://github.com/longhorn/longhorn/issues/4503#issuecomment-1239189136?

**Comment by samirski** [comment]
@derekbit 
Yeah, I can confirm that this is a network related issue. So closing this as it's not related to longhorn. Thanks for your help
