### ISSUE TITLE
[BUG] Updating option "Allow snapshots removal during trim" for old volumes failed 

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#5218]
## Describe the bug (🐛 if you encounter this issue)

If a volume is live upgraded from v1.3.2 or lower versions or the volume is not upgraded yet, updating volume option "Allow snapshots removal during trim" (which is actually field `volume.spec.unmapMarkSnapChainRemoved`) will error out.

This is similar to the case I mentioned in [this comment](https://github.com/longhorn/longhorn/issues/5203#issuecomment-1372015161).

## To Reproduce

1. Deploy Longhorn v1.3.2
2. Create and attach 2 volumes.
3. Upgrade Longhorn to v1.4.0.
4. Do live upgrade for one volume.
5. Update volume option "Allow snapshots removal during trim" for both volumes via UI.
6. See error logs in the longhorn manager pods

## Expected behavior

There should not be tons of errors in the longhorn manager. And the engine should work correctly.

## Log or Support bundle

```
[longhorn-manager-frcss longhorn-manager] E0105 12:39:17.861011       1 engine_controller.go:774] failed to update status for engine vol-e-c861dc7a: failed to correct flag UnmapMarkSnapChainRemoved from false to true: proxyServer=10.42.2.36:8501 destination=10.42.2.36:10000: failed to set UnmapMarkSnapChainRemoved: rpc error: code = Unknown desc = failed to set UnmapMarkSnapChainRemoved to true for volume 10.42.2.36:10000: rpc error: code = Unimplemented desc = unknown method VolumeUnmapMarkSnapChainRemovedSet for service ptypes.ControllerService
```

## Environment

 - Longhorn version: v1.3.2 -> v1.4.0

## Additional context

Need to update the trim doc

**Comment by roger-ryao** [comment]
**Verified on master-head 20230209**

- longhorn master-head ([b1ed058](https://github.com/longhorn/longhorn/commit/b1ed0589b28a8dd510df6396267810fe6d6748a4)) 
- longhorn-manager master-head ([3831c9c](https://github.com/longhorn/longhorn-manager/commit/3831c9c5d7183b5027085689d8bbdbbe947af4f1))

**The test steps**

1. Deploy Longhorn v1.3.2
2. Create and attach 2 volumes.
3. Upgrade Longhorn to master
4. Do live upgrade for one volume.
5. Setting > General >　enable `Remove Snapshots During Filesystem Trim`
6. Setting > General >　diable `Remove Snapshots During Filesystem Trim`
7. Enable volume option "Allow snapshots removal during trim" for both volumes via UI.
8. Disable volume option "Allow snapshots removal during trim" for both volumes via UI.
9. See logs in the longhorn manager pods


**Result Passed**

1. We could reproduce the issue on 1.4.0
2. We didn't see error logs in the support bundle.
