### ISSUE TITLE
[FEATURE] Cluster Autoscaler Support GA

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5238]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Since 1.3.0, we have successfully introduced #2203 (Cluster Autoscaler experimental support), so in general, we will try to make it GA in a later feature release by resolving the feedback from users.

To make experimental features GA, need to pass QA criteria, especially having automatic e2e coverage. 

## Describe the solution you'd like

- [ ] Have Cluster Autoscaler auto e2e coverage. https://github.com/longhorn/longhorn-tests/pull/936 @c3y1huang 
- [ ] Create specific pipelines for public cloud distros to test Cluster Autoscaler test cases. (EKS, AKS, and GKE) @yangchiu 

## Additional context

cc @longhorn/qa @longhorn/dev

**Comment by yangchiu** [comment]
need https://github.com/longhorn/longhorn/issues/4621

**Comment by yangchiu** [comment]
Run cluster autoscaler test cases on:

[aks](https://ci.longhorn.io/job/private/job/managed-k8s/job/longhorn-tests-aks/34/): 0 failure
[gke](https://ci.longhorn.io/job/private/job/managed-k8s/job/longhorn-tests-gke/28/): 0 failure
[eks](https://ci.longhorn.io/job/private/job/managed-k8s/job/longhorn-tests-eks/33/): All test cases failed as expected. The test cases need to be refined.
