### ISSUE TITLE
[IMPROVEMENT] Update uninstallation info to include the 'Deleting Confirmation Flag'  in chart

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#5250]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Update the uninstallation instructions in the chart with the 'Deleting Confirmation Flag' information.

<img width="951" alt="Screenshot 2023-01-10 at 5 08 55 PM" src="https://user-images.githubusercontent.com/60111667/211695567-08629f69-bf06-4366-9576-8cdeab4c7984.png">

**Comment by roger-ryao** [comment]
After verified the [PR-2304](https://github.com/rancher/charts/pull/2304) and [PR-2305](https://github.com/rancher/charts/pull/2305) , we could find out the uninstallation instructions in the chart with the 'Deleting Confirmation Flag' information.
![Screenshot_20230116_162135](https://user-images.githubusercontent.com/104337648/212631822-a5d06511-8f4b-461f-86a8-c115cf10e5f3.png)
![Screenshot_20230116_165528](https://user-images.githubusercontent.com/104337648/212637456-f353e0c2-d984-4a8a-9c5b-0b632ffd20e3.png)
