### ISSUE TITLE
[DOC] Update the readme of longhorn-spdk-engine about using new Longhorn (RAID1) bdev

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5256]
## What's the task? Please describe

https://github.com/longhorn/longhorn-spdk-engine has an outdated tutorial to guide people on how to prepare and set up the environment for using SPDK, run new Longhorn SPDK bdev, etc.

Need to update the tutorial because right now we already decide to use RAID1 bdev to achieve our new Longhorn SPDK volume. 

## Describe the items of the task (DoD, definition of done) you'd like

- [ ] Update readme to guide users on how to setup the environment for running RAID1

## Additional context

cc @longhorn/dev-data-plane

**Comment by innobead** [comment]
@DamiaSan When working on issues, please do:

- Mve to the right pipeline.
![image](https://user-images.githubusercontent.com/899492/212027472-9af48a88-c353-4b65-ad7c-1f0de8d5613d.png)
- Update the sprint and estimation (days)
![image](https://user-images.githubusercontent.com/899492/212027604-e33cca9b-8b1f-45a0-bd6d-e74cb73bc1e4.png)

cc @rebeccazzzz

**Comment by derekbit** [comment]
@DamiaSan 

Appreciated your detailed RAID1 doc.

Can you add a wiki doc for 

1. Prerequisites for the environment
   - What's the cloud vendor for the spdk test
   - Host OS
   - Kernel driver for SPDK
   - ....

2.  Build the longhorn spdk
  - Branch
  - Compile

Thank you.
