### ISSUE TITLE
[IMPROVEMENT] Disable Revision Counter for Strict-Local dataLocality

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#5257]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

No need revision counter since strict local only keeps a single replica.

## Describe the solution you'd like

- Disable Revision Counter by default when `dataLocality=Strict-Local`.

## Describe alternatives you've considered

- Improve document

## Additional context

https://cloud-native.slack.com/archives/CNVPEL9U3/p1673406587513549?thread_ts=1672827070.589069&cid=CNVPEL9U3

**Comment by innobead** [comment]
This is good to help create issues based on the community feedback.

cc @longhorn/dev
