### ISSUE TITLE
[BUG] Incorrect router retry mechanism

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5259]
## Describe the bug (🐛 if you encounter this issue).

The [router retry mechanism](https://github.com/longhorn/longhorn-manager/blob/25c572365ee242883c65524f5f0d1dd6af2eddae/recovery_backend/server/router.go#L14) will lead to repeatedly read from the request body, which actually does not work correctly. 
The body is already read, so the successive retries won't succeed and encounter EOF error.

## To Reproduce

3. Perform '....'

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

https://github.com/longhorn/longhorn-manager/pull/1671#issuecomment-1373600981

**Comment by chriscchien** [comment]
This ticket is hard to [reproduce](https://github.com/longhorn/longhorn/issues/5183#issuecomment-1378198068) in my environment and after the [fix](https://github.com/longhorn/longhorn-manager/pull/1700) merged, master-head pipeline does not have outstanding issue observed.

Close this ticket first, I will keep track if pipeline have error related to ConfigMap read, thank you
