### ISSUE TITLE
[TASK][UI] add new recurring job tasks

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#5272]
## What's the task? Please describe

2 new recurring job task types will be introduced:
- `snapshot-cleanup`
- `snapshot-delete`

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] Support `snapshot-cleanup` and `snapshot-delete` in UI.

## Additional context

- https://github.com/longhorn/longhorn/blob/master/enhancements/20230103-recurring-snapshot-cleanup.md#goals
- https://github.com/longhorn/longhorn/issues/3836

**Comment by c3y1huang** [comment]
cc @smallteeths

**Comment by chriscchien** [comment]
Verified in longhorn master `e1ea3d` and longhorn-ui master `d3795d`
Result **Pass**

Can create recurring job with type `snapshot-cleanup` and `snapshot-delete`, the functionality tested in  https://github.com/longhorn/longhorn/issues/3836 and those 2 new types of recurring job worked well in master-head
