### ISSUE TITLE
[TASK] Sync latest RAID1 code base at upstream to longhorn/spdk for development

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5280]
## What's the task? Please describe

Need to have a mechanism to sync upstream works to the longhorn/spdk::raid1 branch, and the downstream work will be in the longhorn branch. 

## Describe the items of the task (DoD, definition of done) you'd like

- [ ] Provide the sync process via a script, then it can be automated later (initially. manual update is fine)

## Additional context

ref: #https://github.com/longhorn/longhorn/issues/5256

cc @longhorn/dev-data-plane @yangchiu

**Comment by DamiaSan** [comment]
@innobead 

Are we sure that automatic sync is a good idea? When we will have downstream development this process will have to be made manually because we will have to resolve possible conflicts. And when we will be in production, maybe we want to sync with upstream only when nedded.

**Comment by innobead** [comment]
> @innobead
> 
> Are we sure that automatic sync is a good idea? When we will have downstream development this process will have to be made manually because we will have to resolve possible conflicts. And when we will be in production, maybe we want to sync with upstream only when needed.

As I mentioned, manual update is fine at the beginning, we just need a branch periodically updated to ensure it includes pending PRs included like rebalancing, error handling, etc, then our dev branch (`longhorn`) can base on it. WDYT?

**Comment by innobead** [comment]
@shuo-wu @derekbit :point_up:

**Comment by derekbit** [comment]
> Actually, SPDK development under review in Gerrit that will be necessary for us are:
> 
> * [ ]  RAID1 read balancing
> * [ ]  RAID1 degraded mode support
> * [ ]  RAID remove base bdev
> * [ ]  RAID suspend/resume I/O
> * [ ]  RAID how base bdev details in json

@DamiaSan Can you provide the relative Gerrit PR review links? Thank you.

**Comment by innobead** [comment]
We don't need this anymore. The code will be just based on longhorn/spdk longhorn branch.
