### ISSUE TITLE
[BUG] Sync up with backup target during DR volume activation

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#5292]
## Describe the bug (🐛 if you encounter this issue)

After introducing the backup CR in v1.2.0, Longhorn no longer forcibly sync-up the latest backup with the remote backup target anymore when UI tries to list backups or activate DR volumes.

The sync-up mechanism before v1.2.0 is [here](https://github.com/longhorn/longhorn-manager/blob/5011a18d53293126cafc0d60f3162ab31f3d122c/manager/volume.go#L568-L572).

## To Reproduce

1. Launch 2 clusters and both have Longhorn installed
2. Set up a backup target.
3. Create a volume and write data in the 1st cluster. Then create a backup.
4. Restore the backup as a DR volume in the 2nd cluster.
5. Modify the backup poll interval to a large value.
6. Write more data for the volume in the 1st cluster, and create the 2nd backup.
7. Activate the DR volume in the 2nd cluster. Then verify the data

## Expected behavior

The activated DR volume should contain the latest data.

## Log or Support bundle
N/A

## Environment

 - Longhorn version: v1.4.0

**Comment by chriscchien** [comment]
Reproduced in Loghorn manager master `b4695d` with [steps](https://github.com/longhorn/longhorn/issues/5292#issue-1534332677)
Activated DR volume's data was the latest one backup data synced by cluster, not really the newest backup data in backupstore.

**Comment by weizhe0422** [comment]
The sync-up mechanism was removed with [this commit](https://github.com/longhorn/longhorn-manager/commit/89250d4e52593c05d466cb5586a8f1e01c03a29a).

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manger 2976b0d) following [the test steps](https://github.com/longhorn/longhorn-manager/pull/1704#issue-1588044276).

DR volume can be synchronized when activation, and the data is intact, keeping the same as the latest backup.
