### ISSUE TITLE
[BUG] Memory leak in CSI plugin caused by stuck umount processes if the RWX volume is already gone

### ISSUE THREAD

**Issue by lazar-boradzhiev** [longhorn/longhorn#5296]
## Describe the bug (🐛 if you encounter this issue)

The memory usage of the CSI plugins has been growing steadily for the past few weeks after upgrading to version 1.4.0
![image](https://user-images.githubusercontent.com/73098389/212631603-93f7b860-90fd-4115-82ca-04c9d9f0ad2a.png)

## To Reproduce

No specific steps. It has been like that since upgrading to version Longhorn 1.4.0.

## Expected behavior

The CSI plugin memory usage should stay relatively small without growing steadily.

## Log or Support bundle

[supportbundle_413f9f8b-328c-47d2-a25d-4f7c903bf06f_2023-01-16T08-27-12Z.zip](https://github.com/longhorn/longhorn/files/10423824/supportbundle_413f9f8b-328c-47d2-a25d-4f7c903bf06f_2023-01-16T08-27-12Z.zip)

## Environment
Longhorn version: 1.4.0
Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.25.4+k3s1
    Number of management node in the cluster: 1
    Number of worker node in the cluster: 4
Node config
    OS type and version: Raspbian (5.15.76-v8) and Ubuntu server (22.04.1)
    CPU per node: 2-4
    Memory per node: 4-8G
    Disk type(e.g. SSD/NVMe): SSD
    Network bandwidth between the nodes: 1G
Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
Number of Longhorn volumes in the cluster: 15

## Workaround
Force umount the stuck umount process by `umoun -f`.

## Additional context

Initially discussed as part of another issue https://github.com/longhorn/longhorn/issues/5195#issuecomment-1383662401

**Comment by innobead** [comment]
@lazar-boradzhiev would probably need your cooperation when investigating this issue. Thanks first.

**Comment by lazar-boradzhiev** [comment]
> @lazar-boradzhiev would probably need your cooperation when investigating this issue. Thanks first.

Sure, I will stay available.

**Comment by derekbit** [comment]
There are 3 containers in the pod. `longhorn-csi-plugin` container eats lots of memory.
```
  containers:
  - name: longhorn-liveness-probe
    usage:
      cpu: 261554n
      memory: 8796Ki
  - name: node-driver-registrar
    usage:
      cpu: 16264n
      memory: 8848Ki
  - name: longhorn-csi-plugin
    usage:
      cpu: 205597n
      memory: 2105936Ki
```

**Comment by derekbit** [comment]
@lazar-boradzhiev Can you log into the `longhorn-csi-plugin` container of the `longhorn-csi-plugin` pod and check which process is using the big memory by `ps aux`?

**Comment by lazar-boradzhiev** [comment]
@derekbit Here is the file with the output
[ps-output.txt](https://github.com/longhorn/longhorn/files/10425125/ps-output.txt)

**Comment by derekbit** [comment]
The main culprit seems the k3s server.

```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         649 30.2 18.6 3162676 1494028 ?     Ssl  Jan03 5529:41 /usr/local/bin/k3s server
root     4183554  0.2  4.7 1369312 378676 ?      Ssl  Jan05  40:40 longhorn-manager -d csi --nodeid=amaterasu --endpoint=unix:///csi/csi.sock --drivername=driver.longhorn.io --manager-url=http://longhorn-backend:9500/v1
root     3964912  0.2  2.8 549476 226720 ?       Ssl  Jan05  38:51 python3 -m homeassistant --config /config
root     3945584  1.9  1.5 828328 125200 ?       Ssl  Jan05 318:13 longhorn-manager -d daemon --engine-image longhornio/longhorn-engine:v1.4.0 --instance-manager-image longhornio/longhorn-instance-manager:v1.4.0 --share-manager-image longhornio/longhorn-share-manager:v1.4.0 --backing-image-manager-image longhornio/backing-image-manager:v1.4.0 --support-bundle-manager-image longhornio/support-bundle-kit:v0.0.17 --manager-image longhornio/longhorn-manager:v1.4.0 --service-account longhorn-service-account
root         784  5.0  1.3 873752 109688 ?       Sl   Jan03 916:12 containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd
2000     3945786  0.2  1.3 825128 108348 ?       Ssl  Jan05  33:34 longhorn-manager admission-webhook --service-account longhorn-service-account
1000        5309  0.3  1.3 878068 104168 ?       Ssl  Jan03  56:13 /app/cmd/cainjector/cainjector --v=2 --leader-election-namespace=kube-system
```

**Comment by derekbit** [comment]
@lazar-boradzhiev 
Can you provide the `dmesg -T` of each Longhorn node and kubelet logs for further investigation? Thank you.

**Comment by lazar-boradzhiev** [comment]
> The main culprit seems the k3s server. BTW, a weird thing is that a tons of `umount` processes (~4000) are stuck on this node.
> 
> ```
> USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
> root         649 30.2 18.6 3162676 1494028 ?     Ssl  Jan03 5529:41 /usr/local/bin/k3s server
> root     4183554  0.2  4.7 1369312 378676 ?      Ssl  Jan05  40:40 longhorn-manager -d csi --nodeid=amaterasu --endpoint=unix:///csi/csi.sock --drivername=driver.longhorn.io --manager-url=http://longhorn-backend:9500/v1
> root     3964912  0.2  2.8 549476 226720 ?       Ssl  Jan05  38:51 python3 -m homeassistant --config /config
> root     3945584  1.9  1.5 828328 125200 ?       Ssl  Jan05 318:13 longhorn-manager -d daemon --engine-image longhornio/longhorn-engine:v1.4.0 --instance-manager-image longhornio/longhorn-instance-manager:v1.4.0 --share-manager-image longhornio/longhorn-share-manager:v1.4.0 --backing-image-manager-image longhornio/backing-image-manager:v1.4.0 --support-bundle-manager-image longhornio/support-bundle-kit:v0.0.17 --manager-image longhornio/longhorn-manager:v1.4.0 --service-account longhorn-service-account
> root         784  5.0  1.3 873752 109688 ?       Sl   Jan03 916:12 containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd
> 2000     3945786  0.2  1.3 825128 108348 ?       Ssl  Jan05  33:34 longhorn-manager admission-webhook --service-account longhorn-service-account
> 1000        5309  0.3  1.3 878068 104168 ?       Ssl  Jan03  56:13 /app/cmd/cainjector/cainjector --v=2 --leader-election-namespace=kube-system
> ...
> root     1238506  0.0  0.0   3992  1000 ?        D    08:55   0:00 umount /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount
> root     1311671  0.0  0.0   3992  1000 ?        D    09:47   0:00 umount /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount
> root      184201  0.0  0.0   3992   996 ?        D    Jan15   0:00 umount /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount
> root      201152  0.0  0.0   3992   996 ?        D    Jan15   0:00 umount /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount
> root      212443  0.0  0.0   3992   996 ?        D    Jan15   0:00 umount /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount
> root      330725  0.0  0.0   3992   996 ?        D    Jan15   0:00 umount /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount
> root      353236  0.0  0.0   3992   996 ?        D    Jan15   0:00 umount /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount
> root      578426  0.0  0.0   3992   996 ?        D    01:03   0:00 umount /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount
> root      617795  0.0  0.0   3992   996 ?        D    01:31   0:00 umount /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount
> ```

This volume `pvc-c2c40895-326b-4198-ac70-27f92b6ea62d` and the pod it belongs to  `e1cf9e16-b3eb-455c-ae64-887200d6f267` should be both long gone.

**Comment by lazar-boradzhiev** [comment]
> @lazar-boradzhiev Can you provide the `dmesg -T` of each Longhorn node and kubelet logs for further investigation? Thank you.

[dmesg_amaterasu.txt](https://github.com/longhorn/longhorn/files/10425673/dmesg_amaterasu.txt) - master
[dmesg_hermes.txt](https://github.com/longhorn/longhorn/files/10425674/dmesg_hermes.txt) - storage
[dmesg_horreum.txt](https://github.com/longhorn/longhorn/files/10425675/dmesg_horreum.txt) - storage


@derekbit The kubelet logs are quite big. For the last 1 week for total of around 250 MBs, which is not allowed by github. I could spend some time later to try and filter them out a bit or upload them elsewhere.

**Comment by derekbit** [comment]
> > @lazar-boradzhiev Can you provide the `dmesg -T` of each Longhorn node and kubelet logs for further investigation? Thank you.
> 
> [dmesg_amaterasu.txt](https://github.com/longhorn/longhorn/files/10425673/dmesg_amaterasu.txt) - master [dmesg_hermes.txt](https://github.com/longhorn/longhorn/files/10425674/dmesg_hermes.txt) - storage [dmesg_horreum.txt](https://github.com/longhorn/longhorn/files/10425675/dmesg_horreum.txt) - storage
> 

@lazar-boradzhiev  Thank you.
Didn't see any message related to the stuck unmount processes in the demsg.

**Comment by shuo-wu** [comment]
Tons of the below log in the longhorn-csi-plugin:
```
2023-01-16T08:26:58.785279117Z time="2023-01-16T08:26:58Z" level=info msg="NodeUnpublishVolume: req: {\"target_path\":\"/var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount\",\"volume_id\":\"pvc-c2c40895-326b-4198-ac70-27f92b6ea62d\"}"
2023-01-16T08:27:01.793205260Z time="2023-01-16T08:27:01Z" level=info msg="trying to cleanup mount point /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount"
2023-01-16T08:27:01.793287017Z time="2023-01-16T08:27:01Z" level=debug msg="trying to unmount potential mount point /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount"
```

The weird thing is, there is no error reported from [the unmount](https://github.com/longhorn/longhorn-manager/blob/1a200c0e126b50c70074c975e4c8949afc3e9bbd/csi/util.go#L249-L254). And [the actual unmount interface Kubernetes provides](https://github.com/longhorn/longhorn-manager/blob/1a200c0e126b50c70074c975e4c8949afc3e9bbd/vendor/k8s.io/mount-utils/mount_linux.go#L295-L296) does not contain a timeout mechanism.

Besides, Kubernetes still considers this volume is in use but actually the related Longhorn volume object is gone:
```
- apiVersion: v1
     kind: Node
     name: amaterasu
     resourceVersion: "43439969"
     uid: 704f5e1f-4707-40d0-95b0-3961a8e0bd4c
   status:
     volumesAttached:
     - devicePath: "null"
       name: kubernetes.io/csi/driver.longhorn.io^pvc-c2c40895-326b-4198-ac70-27f92b6ea62d
```

Probably we can get something from the kubelet log.

**Comment by lazar-boradzhiev** [comment]
@shuo-wu @derekbit Here are the logs from amaterasu (master) https://drive.google.com/file/d/162GPs3hFpCGmFcw1fYd1MJQsOlIKkyX8/view?usp=sharing. One of the storage nodes has no logs for some reason, while the other (hermes) seems to be having k3s related problems with token. The node strangely looks like it works as expected, but I will look further into it. Here is a section of the logs that seems to repeat for quite some time.
```
Jan 16 12:05:52 raspberrypi systemd[1]: Starting Lightweight Kubernetes...
Jan 16 12:05:52 raspberrypi sh[990099]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Jan 16 12:05:52 raspberrypi sh[990100]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Jan 16 12:05:52 raspberrypi k3s[990103]: time="2023-01-16T12:05:52Z" level=info msg="Starting k3s v1.25.4+k3s1 (0dc63334)"
Jan 16 12:05:52 raspberrypi k3s[990103]: time="2023-01-16T12:05:52Z" level=info msg="Configuring sqlite3 database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s"
Jan 16 12:05:52 raspberrypi k3s[990103]: time="2023-01-16T12:05:52Z" level=info msg="Configuring database table schema and indexes, this may take a moment..."
Jan 16 12:05:52 raspberrypi k3s[990103]: time="2023-01-16T12:05:52Z" level=info msg="Database tables and indexes are up to date"
Jan 16 12:05:52 raspberrypi k3s[990103]: time="2023-01-16T12:05:52Z" level=info msg="Kine available at unix://kine.sock"
Jan 16 12:05:52 raspberrypi k3s[990103]: time="2023-01-16T12:05:52Z" level=fatal msg="starting kubernetes: preparing server: failed to normalize token; must be in format K10<CA-HASH>::<USERNAME>:<PASSWORD> or <PASSWORD>"
Jan 16 12:05:52 raspberrypi systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Jan 16 12:05:52 raspberrypi systemd[1]: k3s.service: Failed with result 'exit-code'.
Jan 16 12:05:52 raspberrypi systemd[1]: Failed to start Lightweight Kubernetes.
Jan 16 12:05:57 raspberrypi systemd[1]: k3s.service: Scheduled restart job, restart counter is at 215411.
Jan 16 12:05:57 raspberrypi systemd[1]: Stopped Lightweight Kubernetes.
Jan 16 12:05:58 raspberrypi systemd[1]: Starting Lightweight Kubernetes...
Jan 16 12:05:58 raspberrypi sh[990295]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Jan 16 12:05:58 raspberrypi sh[990297]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Jan 16 12:05:58 raspberrypi k3s[990300]: time="2023-01-16T12:05:58Z" level=info msg="Starting k3s v1.25.4+k3s1 (0dc63334)"
Jan 16 12:05:58 raspberrypi k3s[990300]: time="2023-01-16T12:05:58Z" level=info msg="Configuring sqlite3 database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s"
Jan 16 12:05:58 raspberrypi k3s[990300]: time="2023-01-16T12:05:58Z" level=info msg="Configuring database table schema and indexes, this may take a moment..."
Jan 16 12:05:58 raspberrypi k3s[990300]: time="2023-01-16T12:05:58Z" level=info msg="Database tables and indexes are up to date"
Jan 16 12:05:58 raspberrypi k3s[990300]: time="2023-01-16T12:05:58Z" level=info msg="Kine available at unix://kine.sock"
Jan 16 12:05:58 raspberrypi k3s[990300]: time="2023-01-16T12:05:58Z" level=fatal msg="starting kubernetes: preparing server: failed to normalize token; must be in format K10<CA-HASH>::<USERNAME>:<PASSWORD> or <PASSWORD>"
Jan 16 12:05:58 raspberrypi systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Jan 16 12:05:58 raspberrypi systemd[1]: k3s.service: Failed with result 'exit-code'.
Jan 16 12:05:58 raspberrypi systemd[1]: Failed to start Lightweight Kubernetes.
```

**Comment by PhanLe1010** [comment]
Do you remember if `pvc-c2c40895-326b-4198-ac70-27f92b6ea62d` is ReadWriteMany volume or ReadWriteOnce volume? @lazar-boradzhiev

**Comment by derekbit** [comment]
> Do you remember if `pvc-c2c40895-326b-4198-ac70-27f92b6ea62d` is ReadWriteMany volume or ReadWriteOnce volume? @lazar-boradzhiev

@PhanLe1010 
The volume is a ReadWriteMany volume.
I saw `longhorn-csi-plugin` tries to clean up the mountpoint repeatedly. However, the volume and the share-manager are already gone.
```
2023-01-16T08:27:01.793205260Z time="2023-01-16T08:27:01Z" level=info msg="trying to cleanup mount point /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount"
2023-01-16T08:27:01.793287017Z time="2023-01-16T08:27:01Z" level=debug msg="trying to unmount potential mount point /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount"
```

@lazar-boradzhiev 
Can you check if `/var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount` is still on your Longhorn node? Can you try to force unmount the mountpoint by `umount -f`?

**Comment by PhanLe1010** [comment]
> Can you try to force unmount the mountpoint by umount -f?

Could we hold on to trying this one so that we can do more debugging? I am thinking of stucking NFS server make the umount hang?

**Comment by derekbit** [comment]
> > Can you try to force unmount the mountpoint by umount -f?
> 
> Could we hold on to trying this one so that we can do more debugging? I am thinking of stucking NFS server make the umount hang?

Sure. But the share-manager pod (NFS server) is sucessfully deleted.
Not sure if it is related to the issue https://github.com/longhorn/longhorn/issues/5224.

**Comment by joshimoo** [comment]
Some notes below:
- this is most likely the unmount calls getting stuck against a dead NFS mount, due to hard mode.
- we can look at https://github.com/longhorn/longhorn-manager/blob/fc07fe8e182a7426d56b4d98f63664b60a088e1c/vendor/k8s.io/mount-utils/mount_helper_common.go#L44 and https://github.com/longhorn/longhorn-manager/blob/fc07fe8e182a7426d56b4d98f63664b60a088e1c/vendor/k8s.io/mount-utils/mount.go which implements a force unmount with a timeout mechanism. This should reduce the severity of this issue.

**Comment by derekbit** [comment]
BTW, for the NFS mount is dead. Any possible ordering issue, for example, the share-manager resource is somehow deleted before volume detachement?

**Comment by lazar-boradzhiev** [comment]
> > Do you remember if `pvc-c2c40895-326b-4198-ac70-27f92b6ea62d` is ReadWriteMany volume or ReadWriteOnce volume? @lazar-boradzhiev
> 
> @PhanLe1010 The volume is a ReadWriteMany volume. I saw `longhorn-csi-plugin` tries to clean up the mountpoint repeatedly. However, the volume and the share-manager are already gone.
> 
> ```
> 2023-01-16T08:27:01.793205260Z time="2023-01-16T08:27:01Z" level=info msg="trying to cleanup mount point /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount"
> 2023-01-16T08:27:01.793287017Z time="2023-01-16T08:27:01Z" level=debug msg="trying to unmount potential mount point /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount"
> ```
> 
> @lazar-boradzhiev Can you check if `/var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount` is still on your Longhorn node? Can you try to force unmount the mountpoint by `umount -f`?

@derekbit Just checked to verify that `/var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount` still exists. Also during the night one of the CSI plugin containers has crashed, most likely due to OOM. The new container is still growing in memory and has plenty of logs related to the very same volume.
```
time="2023-01-18T08:26:11Z" level=info msg="NodeUnpublishVolume: req: {\"target_path\":\"/var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount\",\"volume_id\":\"pvc-c2c40895-326b-4198-ac70-27f92b6ea62d\"}"
time="2023-01-18T08:26:11Z" level=info msg="trying to cleanup mount point /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount"
time="2023-01-18T08:26:11Z" level=debug msg="trying to unmount potential mount point /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount"
```
![image](https://user-images.githubusercontent.com/73098389/213121001-bd3074b7-2fcf-4c64-b12e-62853f7d79e5.png)

**Comment by lazar-boradzhiev** [comment]
It executed successfully! 🚀 

Logs from container:
```
time="2023-01-18T08:46:21Z" level=info msg="no need for unmount not a mount point /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount"
time="2023-01-18T08:46:21Z" level=info msg="cleaned up mount point /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount"
W0118 08:46:21.784060  554181 mount_helper_common.go:34] Warning: Unmount skipped because path does not exist: /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount
time="2023-01-18T08:46:21Z" level=info msg="NodeUnpublishVolume: volume pvc-c2c40895-326b-4198-ac70-27f92b6ea62d unmounted from path /var/lib/kubelet/pods/e1cf9e16-b3eb-455c-ae64-887200d6f267/volumes/kubernetes.io~csi/pvc-c2c40895-326b-4198-ac70-27f92b6ea62d/mount"
time="2023-01-18T08:46:21Z" level=info msg="NodeUnpublishVolume: rsp: {}"
```

Memory usage is back to a healthy level
![image](https://user-images.githubusercontent.com/73098389/213125521-2a2d8e96-d61c-4bc8-ab3f-bc82f0e9569d.png)

**Comment by derekbit** [comment]
@lazar-boradzhiev 
Thank you for the update.
Do you have any idea how to trigger the issue? For example, how did you terminate the workload and the ReadWriteMany voluume?

**Comment by lazar-boradzhiev** [comment]
@derekbit I initially suspected that the problem might be caused by improperly migrating the k3s node to a newer version as described in another issue https://github.com/longhorn/longhorn/issues/5195#issuecomment-1383662401. Basically, I didn't scale down and detach all the workloads before the migration.

**Comment by derekbit** [comment]
> @derekbit Thanks for the help! I initially suspected that the problem might be caused by improperly migrating the k3s node to a newer version as described in another issue [#5195 (comment)](https://github.com/longhorn/longhorn/issues/5195#issuecomment-1383662401). Basically, I didn't scale down and detach all the workloads before the migration.

I see. I cannot reproduce it from my side. @PhanLe1010 Did you succeed to reproduce it?

For the resiliens, we can force umount the mountpoint in CSI plugin as @joshimoo mentioned https://github.com/longhorn/longhorn/issues/5296#issuecomment-1386347221.

**Comment by derekbit** [comment]
> Besides figuring out if it can be reproduced, need to use force umount as a fallback in general if graceful umount not working. WDYT or any concerns? @derekbit @joshimoo @PhanLe1010

Yeah, should follow this pattern.

**Comment by PhanLe1010** [comment]
I am able to reproduce the issue by:
1. Deploy Longhorn 1.4.0 and install prerequisite NFS client
2. Create a deployment that use RWX volume. Wait for the deployment to become running
3. Delete the Volume using Longhorn UI
4. Scale down the deployment
5. Observe that:
    1. the pod stuck in terminating. 
    2. Longhorn CSI plugin repeatedly has the logs 
        ```
        [longhorn-csi-plugin-pqmz9 longhorn-csi-plugin] time="2023-01-19T22:06:33Z" level=debug msg="trying to unmount potential mount point /var/lib/kubelet/pods/be80e2cc-b074-4223-b1c9-9d49c3ff416f/volumes/kubernetes.io~csi/pvc-be9dcbac-38fc-4754-8c12-4fb3f2572aa6/mount"
        ```
    4. There are many umount command stuck in `longhorn-csi-plugin`:
        ```
        longhorn-csi-plugin-pqmz9:/ # ps aux --sort -rss | grep umount 
        root       31502  0.0  0.0  16260  1268 ?        D    22:06   0:00 umount /var/lib/kubelet/pods/be80e2cc-b074-4223-b1c9-9d49c3ff416f/volumes/kubernetes.io~csi/pvc-be9dcbac-38fc-4754-8c12-4fb3f2572aa6/mount
        root       32954  0.0  0.0  16260  1240 ?        D    22:08   0:00 umount /var/lib/kubelet/pods/be80e2cc-b074-4223-b1c9-9d49c3ff416f/volumes/kubernetes.io~csi/pvc-be9dcbac-38fc-4754-8c12-4fb3f2572aa6/mount
        root       28483  0.0  0.0  16260  1208 ?        D    22:02   0:00 umount /var/lib/kubelet/pods/be80e2cc-b074-4223-b1c9-9d49c3ff416f/volumes/kubernetes.io~csi/pvc-be9dcbac-38fc-4754-8c12-4fb3f2572aa6/mount
        root       29991  0.0  0.0  16260  1204 ?        D    22:04   0:00 umount /var/lib/kubelet/pods/be80e2cc-b074-4223-b1c9-9d49c3ff416f/volumes/kubernetes.io~csi/pvc-be9dcbac-38fc-4754-8c12-4fb3f2572aa6/mount
        root       26874  0.0  0.0  16260  1180 ?        D    22:00   0:00 umount /var/lib/kubelet/pods/be80e2cc-b074-4223-b1c9-9d49c3ff416f/volumes/kubernetes.io~csi/pvc-be9dcbac-38fc-4754-8c12-4fb3f2572aa6/mount
        ```

cc @derekbit

**Comment by withinboredom** [comment]
Also running into this 😂

**Comment by derekbit** [comment]
We have a fix for the unmount stuck issue.
Before the release, you can try the workaround.

**Comment by roger-ryao** [comment]
**Verified on master-head 20230216**

- longhorn master-head ([bb1bd7d](https://github.com/longhorn/longhorn/commit/bb1bd7d4db8d5fd6e0473f11b2d407563d80a5b2)) 
- longhorn-engine master-head ([a35adb4](https://github.com/longhorn/longhorn-manager/commit/a35adb48d1bd8f010bb26fdbb2ef27fd66ad71e2))

**The test steps**

1. Create a deployment that use RWX volume via cli `kubectl apply -f deployment.yaml`

<details>
<summary>deployment.yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-dep-rwx
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dep-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany    
  storageClassName: longhorn
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep-rwx
  labels:
    app: mysql-dep-rwx
spec:
  selector:
    matchLabels:
      app: mysql-dep-rwx # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dep-rwx
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql-dep-rwx
        livenessProbe:
          exec:
            command:
              - ls
              - /var/lib/mysql/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql-dep-rwx
        volumeMounts:
        - name: mysql-dep-rwx-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-dep-rwx-volume
        persistentVolumeClaim:
          claimName: mysql-dep-rwx-pvc
```
</details>

2. Scale up the deployment to 5 via Rancher UI.
3. Delete the Volume using Longhorn UI
4. Scale down the deployment to 0 via Rancher UI.

**Result Passed**

1. We could reproduce the issue on v1.4.0.
![Screenshot_20230216_180304](https://user-images.githubusercontent.com/104337648/219344432-dc09d4d6-02d8-4217-ae01-d0a09b76c43c.png)
![Screenshot_20230216_184217](https://user-images.githubusercontent.com/104337648/219344538-85ea636a-b28c-4df7-b7d2-359272ee543e.png)

2. We don't find out umount command stuck in `longhorn-csi-plugin` on master-head
`kubectl -n longhorn-system exec -it longhorn-csi-plugin-xxxxx -c longhorn-csi-plugin -- /bin/bash`
`ps aux --sort -rss | grep umount`
![Screenshot_20230216_175910](https://user-images.githubusercontent.com/104337648/219344721-06ff3766-9edb-4b52-be75-4eafd60854cd.png)

3. The memory usage of the longhorn-csi-plugin pod less than v1.4.0
`kubectl top pods -n longhorn-system |grep longhorn-csi-plugin`
![Screenshot_20230216_180327](https://user-images.githubusercontent.com/104337648/219345524-18fe5d7b-f65e-4ade-9c3f-94e631244ff1.png)

**Comment by derekbit** [comment]
@roger-ryao 
Did you see CPU went high when you were validating the issue and the unmount processes were stuck?

**Comment by withinboredom** [comment]
FWIW, I see load (e.g., `cat /proc/loadavg` output) slowly skyrocket when unmount processes get stuck. I've seen it reach into the hundreds overnight.
