### ISSUE TITLE
[IMPROVEMENT] Add pvc name to longhorn_volume metrics

### ISSUE THREAD

**Issue by margau** [longhorn/longhorn#5297]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

PVC Volumes have a PVC Name, which is however not exposed to the longhorn_volume* metrics. This makes handling alerts difficult, as only the non human-readable pvcid is exposed as "volume" label, and its not clear which pvc and service is affected.

## Describe the solution you'd like

Add an "pvcname"-label to all longhorn_volume metrics, and fill it with the pvc name from `kubernetesStatus.pvcName` if set.

## Describe alternatives you've considered

n/a

## Additional context

n/a

**Comment by nitendra-suse** [comment]
**Verified** **pass** in longhorn master-head (longhorn-manager a66539f).

**Steps :** 

1. Create volume "vol-without-pvc"  without PVC
2. Create volume with pvc name"vol-with-pvc"
3. Observe metrics logs as below

**curl -sSL <Metric URL> /metrics | grep longhorn_volume | grep vol-without-pvc**

longhorn_volume_actual_size_bytes{node="rancher50-worker2",**pvc=""**,volume="vol-without-pvc"} 0
longhorn_volume_capacity_bytes{node="rancher50-worker2",**pvc=""**,volume="vol-without-pvc"} 2.147483648e+10
longhorn_volume_read_iops{node="rancher50-worker2",**pvc=""**,volume="vol-without-pvc"} 0
longhorn_volume_read_latency{node="rancher50-worker2",**pvc=""**,volume="vol-without-pvc"} 0
longhorn_volume_read_throughput{node="rancher50-worker2",**pvc=""**,volume="vol-without-pvc"} 0
longhorn_volume_robustness{node="rancher50-worker2",**pvc=""**,volume="vol-without-pvc"} 1
longhorn_volume_state{node="rancher50-worker2",**pvc=""**,volume="vol-without-pvc"} 2
longhorn_volume_write_iops{node="rancher50-worker2 ",**pvc=""**,volume="vol-without-pvc"} 0
longhorn_volume_write_latency{node="rancher50-worker2",**pvc=""**,volume="vol-without-pvc"} 0
longhorn_volume_write_throughput{node="rancher50-worker2",**pvc=""**,volume="vol-without-pvc"} 0

**curl -sSL <Metric URL> /metrics | grep longhorn_volume |  grep vol-with-pvc**

longhorn_volume_actual_size_bytes{node="rancher50-worker1",**pvc="vol-with-pvc"**,volume="pvc-eff4d803-04fd-4ef1-b60e-16dde9718974"} 4.7429632e+08
longhorn_volume_capacity_bytes{node="rancher50-worker1",**pvc="vol-with-pvc"**,volume="pvc-eff4d803-04fd-4ef1-b60e-16dde9718974"} 2.147483648e+10
longhorn_volume_read_iops{node="rancher50-worker1",**pvc="vol-with-pvc"**,volume="pvc-eff4d803-04fd-4ef1-b60e-16dde9718974"} 0
longhorn_volume_read_latency{node="rancher50-worker1",**pvc="vol-with-pvc"**,volume="pvc-eff4d803-04fd-4ef1-b60e-16dde9718974"} 0
longhorn_volume_read_throughput{node="rancher50-worker1",**pvc="vol-with-pvc"**,volume="pvc-eff4d803-04fd-4ef1-b60e-16dde9718974"} 0
longhorn_volume_robustness{node="rancher50-worker1",**pvc="vol-with-pvc"**,volume="pvc-eff4d803-04fd-4ef1-b60e-16dde9718974"} 1
longhorn_volume_state{node="rancher50-worker1",**pvc="vol-with-pvc"**,volume="pvc-eff4d803-04fd-4ef1-b60e-16dde9718974"} 2
longhorn_volume_write_iops{node="rancher50-worker1",**pvc="vol-with-pvc"**,volume="pvc-eff4d803-04fd-4ef1-b60e-16dde9718974"} 0
longhorn_volume_write_latency{node="rancher50-worker1",**pvc="vol-with-pvc"**,volume="pvc-eff4d803-04fd-4ef1-b60e-16dde9718974"} 0
longhorn_volume_write_throughput{node="rancher50-worker1",**pvc="vol-with-pvc"**,volume="pvc-eff4d803-04fd-4ef1-b60e-16dde9718974"} 0
