### ISSUE TITLE
[IMPROVEMENT] Resume download BackingImage when it failed 

### ISSUE THREAD

**Issue by bk201** [longhorn/longhorn#5307]
## Describe the bug (🐛 if you encounter this issue)

Sometimes a backing image creation fails with "connection reset by peer".

## To Reproduce

1. Create a backing image from an URL.
2. Sometimes, it fails with "connection reset by peer". Re-creating again succeeds.

## Expected behavior

The backing image should be created from the URL.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.3.0 and v1.2.4.
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

This is observed in some Harvester issues:
- https://github.com/harvester/harvester/issues/2535
   Longhorn version 1.3.0.    
   ![179716316-f0f50824-fc9c-42c9-a8b1-3303e259193e](https://user-images.githubusercontent.com/1691518/212861794-6a07862a-e625-4f4f-98bc-5cbe83c19e8c.png)

- https://github.com/harvester/harvester/issues/3167
   Longhorn version 1.2.4.
   
  ![202432511-8301a1ff-190f-4fee-9dfc-925475bf90be](https://user-images.githubusercontent.com/1691518/212861664-ced44e2a-aac0-4849-a76f-6ab88d821cdc.png)

**Comment by ChanYiLin** [comment]
Hi @bk201 
can you provide support bundle when this issue happens again

I am thinking this might not related to the external image source, 
since the error indicated reset by peer `10.52.1.25:46944 -> 10.84.128.164:8081` which were not external ip

**Comment by ChanYiLin** [comment]
oh `10.84.128.164:8081` is for harvester image
e.g. `http://10.84.128.164:8081/v1.1.1-rc1/harvester-amd64.iso`

**Comment by bk201** [comment]
@innobead Harvester now has a retry mechanism, so the priority of the feature is lower now. Please see https://github.com/harvester/harvester/issues/2535#issuecomment-1874930818
Feel free to close the issue.

**Comment by innobead** [comment]
https://github.com/harvester/harvester/pull/3148
