### ISSUE TITLE
[BUG] longhorn1.4.0 reinstall error

### ISSUE THREAD

**Issue by ilanni2460** [longhorn/longhorn#5311]
Longhorn version: 1.4.0
Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.24.8+RKE
Number of management node in the cluster: 1
Number of worker node in the cluster: 4
Node config
OS type and version: Centos7.6
CPU per node: 4
Memory per node: 8G

 longhorn1.4.0 reinstall error,error message:
`
Defaulted container "longhorn-manager" out of: longhorn-manager, wait-longhorn-admission-webhook (init)
W0119 14:50:38.751514       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2023-01-19T14:50:38Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr ls: cannot access /var/lib/rancher/longhorn/engine-binaries/*: No such file or directory\n: exit status 2"
time="2023-01-19T14:50:38Z" level=info msg="Skip the leader election for the upgrade since the current Longhorn system is already up to date"
W0119 14:50:38.766592       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0119 14:50:38.770443       1 shared_informer.go:240] Waiting for caches to sync for longhorn datastore
E0119 14:50:38.779440       1 kubernetes_node_controller.go:227] couldn't get kubernetes node 10.23.9.103: node "10.23.9.103" not found 
I0119 14:50:38.870612       1 shared_informer.go:247] Caches are synced for longhorn datastore 
time="2023-01-19T14:50:38Z" level=info msg="Initializing metrics collector system" node=10.23.9.103
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn Backup Target controller" controller=longhorn-backup-target node=10.23.9.103
I0119 14:50:38.870749       1 shared_informer.go:240] Waiting for caches to sync for longhorn-backup-target
I0119 14:50:38.870759       1 shared_informer.go:247] Caches are synced for longhorn-backup-target 
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn Support Bundle controller" controller=longhorn-support-bundle node=10.23.9.103
I0119 14:50:38.870775       1 shared_informer.go:240] Waiting for caches to sync for longhorn-support-bundle
W0119 14:50:38.870775       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn replica controller" controller=longhorn-replica node=10.23.9.103
I0119 14:50:38.870801       1 shared_informer.go:247] Caches are synced for longhorn-support-bundle 
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn Orphan controller" controller=longhorn-orphan node=10.23.9.103
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn Recurring Job controller"
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn engine controller" controller=longhorn-engine node=10.23.9.103
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn volume controller" controller=longhorn-volume node=10.23.9.103
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn Snapshot Controller" controller=longhorn-snapshot node=10.23.9.103
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn Engine Image controller" controller=longhorn-engine-image node=10.23.9.103
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn Backup controller" controller=longhorn-backup node=10.23.9.103
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn Backup Volume controller" controller=longhorn-backup-volume node=10.23.9.103
I0119 14:50:38.870830       1 shared_informer.go:240] Waiting for caches to sync for longhorn-orphan
I0119 14:50:38.870876       1 shared_informer.go:240] Waiting for caches to sync for longhorn-backup-volume
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn node controller"
I0119 14:50:38.870882       1 shared_informer.go:247] Caches are synced for longhorn-orphan 
I0119 14:50:38.870883       1 shared_informer.go:240] Waiting for caches to sync for longhorn node
I0119 14:50:38.870891       1 shared_informer.go:247] Caches are synced for longhorn node 
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn Kubernetes node controller"
I0119 14:50:38.870838       1 shared_informer.go:240] Waiting for caches to sync for longhorn recurring jobs
I0119 14:50:38.870910       1 shared_informer.go:240] Waiting for caches to sync for longhorn kubernetes node
I0119 14:50:38.870913       1 shared_informer.go:247] Caches are synced for longhorn recurring jobs 
I0119 14:50:38.870917       1 shared_informer.go:247] Caches are synced for longhorn kubernetes node 
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn websocket controller" controller=longhorn-websocket node=10.23.9.103
I0119 14:50:38.870925       1 shared_informer.go:240] Waiting for caches to sync for longhorn websocket
I0119 14:50:38.870846       1 shared_informer.go:240] Waiting for caches to sync for longhorn engines
I0119 14:50:38.870930       1 shared_informer.go:247] Caches are synced for longhorn engines 
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn Setting controller" controller=longhorn-setting node=10.23.9.103
I0119 14:50:38.870947       1 shared_informer.go:240] Waiting for caches to sync for longhorn settings
I0119 14:50:38.870951       1 shared_informer.go:247] Caches are synced for longhorn settings 
I0119 14:50:38.870858       1 shared_informer.go:240] Waiting for caches to sync for longhorn-snapshot
I0119 14:50:38.871053       1 shared_informer.go:247] Caches are synced for longhorn-snapshot 
I0119 14:50:38.870805       1 shared_informer.go:240] Waiting for caches to sync for longhorn replicas
I0119 14:50:38.870864       1 shared_informer.go:240] Waiting for caches to sync for longhorn engine images
I0119 14:50:38.871084       1 shared_informer.go:247] Caches are synced for longhorn engine images 
I0119 14:50:38.870931       1 shared_informer.go:247] Caches are synced for longhorn websocket 
I0119 14:50:38.871103       1 shared_informer.go:247] Caches are synced for longhorn replicas 
I0119 14:50:38.870874       1 shared_informer.go:240] Waiting for caches to sync for longhorn-backup
I0119 14:50:38.871116       1 shared_informer.go:247] Caches are synced for longhorn-backup 
I0119 14:50:38.870849       1 shared_informer.go:240] Waiting for caches to sync for longhorn engines
I0119 14:50:38.871178       1 shared_informer.go:247] Caches are synced for longhorn engines 
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn SystemBackup controller" controller=longhorn-system-backup node=10.23.9.103
I0119 14:50:38.871259       1 shared_informer.go:240] Waiting for caches to sync for longhorn-system-backup
I0119 14:50:38.871263       1 shared_informer.go:247] Caches are synced for longhorn-system-backup 
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn SystemRestore controller" controller=longhorn-system-restore node=10.23.9.103
I0119 14:50:38.871295       1 shared_informer.go:240] Waiting for caches to sync for longhorn-system-restore
I0119 14:50:38.871299       1 shared_informer.go:247] Caches are synced for longhorn-system-restore 
time="2023-01-19T14:50:38Z" level=info msg="Start kubernetes controller"
I0119 14:50:38.871349       1 shared_informer.go:240] Waiting for caches to sync for kubernetes
I0119 14:50:38.871354       1 shared_informer.go:247] Caches are synced for kubernetes 
I0119 14:50:38.870884       1 shared_informer.go:247] Caches are synced for longhorn-backup-volume 
time="2023-01-19T14:50:38Z" level=warning msg="Failed to select node for sync backup target" controller=longhorn-setting error="no ready nodes available" node=10.23.9.103
time="2023-01-19T14:50:38Z" level=warning msg="Error syncing Longhorn setting longhorn-system/backup-target-credential-secret" controller=longhorn-setting error="failed to sync setting for longhorn-system/backup-target-credential-secret: failed to sync backup target: no ready nodes available" node=10.23.9.103
time="2023-01-19T14:50:38Z" level=warning msg="Failed to select node for sync backup target" controller=longhorn-setting error="no ready nodes available" node=10.23.9.103
time="2023-01-19T14:50:38Z" level=warning msg="Error syncing Longhorn setting longhorn-system/backup-target" controller=longhorn-setting error="failed to sync setting for longhorn-system/backup-target: failed to sync backup target: no ready nodes available" node=10.23.9.103
time="2023-01-19T14:50:38Z" level=info msg=Start controller=longhorn-kubernetes-configmap-controller node=10.23.9.103
I0119 14:50:38.871527       1 shared_informer.go:240] Waiting for caches to sync for longhorn-kubernetes-configmap-controller
I0119 14:50:38.871532       1 shared_informer.go:247] Caches are synced for longhorn-kubernetes-configmap-controller 
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn instance manager controller"
I0119 14:50:38.871619       1 shared_informer.go:240] Waiting for caches to sync for longhorn instance manager
I0119 14:50:38.871628       1 shared_informer.go:247] Caches are synced for longhorn instance manager 
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn share manager controller" controller=longhorn-share-manager node=10.23.9.103
I0119 14:50:38.871654       1 shared_informer.go:240] Waiting for caches to sync for longhorn-share-manager-controller
I0119 14:50:38.871658       1 shared_informer.go:247] Caches are synced for longhorn-share-manager-controller 
time="2023-01-19T14:50:38Z" level=debug msg="Can't find share manager, may have been deleted" controller=longhorn-share-manager node=10.23.9.103 shareManager=pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598
time="2023-01-19T14:50:38Z" level=info msg="Start longhorn-kubernetes-pod-controller" controller=longhorn-kubernetes-pod node=10.23.9.103
I0119 14:50:38.871704       1 shared_informer.go:240] Waiting for caches to sync for longhorn-kubernetes-pod-controller
I0119 14:50:38.871712       1 shared_informer.go:247] Caches are synced for longhorn-kubernetes-pod-controller 
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn Backing Image controller"
I0119 14:50:38.871722       1 shared_informer.go:240] Waiting for caches to sync for longhorn backing images
I0119 14:50:38.871729       1 shared_informer.go:247] Caches are synced for longhorn backing images 
time="2023-01-19T14:50:38Z" level=warning msg="Error syncing Longhorn engine" controller=longhorn-engine engine=longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598-e-8663b2d2 error="failed to sync engine for longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598-e-8663b2d2: unable to get engine image longhornio/longhorn-engine:master-head: engineimage.longhorn.io \"ei-b907910b\" not found" node=10.23.9.103
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn backing image manager controller"
I0119 14:50:38.871799       1 shared_informer.go:240] Waiting for caches to sync for longhorn backing image manager
I0119 14:50:38.871804       1 shared_informer.go:247] Caches are synced for longhorn backing image manager 
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn Kubernetes secret controller" controller=longhorn-kubernetes-secret-controller node=10.23.9.103
I0119 14:50:38.871833       1 shared_informer.go:240] Waiting for caches to sync for longhorn-kubernetes-secret-controller
I0119 14:50:38.871846       1 shared_informer.go:247] Caches are synced for longhorn-kubernetes-secret-controller 
time="2023-01-19T14:50:38Z" level=info msg="Starting Longhorn backing image data source controller"
I0119 14:50:38.871890       1 shared_informer.go:240] Waiting for caches to sync for longhorn backing image data source
I0119 14:50:38.871898       1 shared_informer.go:247] Caches are synced for longhorn backing image data source 
time="2023-01-19T14:50:38Z" level=warning msg="Cannot found the default backup target" controller=longhorn-kubernetes-secret-controller node=10.23.9.103
time="2023-01-19T14:50:38Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598" controller=longhorn-volume error="failed to sync longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598: unable to get engine image longhornio/longhorn-engine:master-head: engineimage.longhorn.io \"ei-b907910b\" not found" node=10.23.9.103
time="2023-01-19T14:50:38Z" level=warning msg="Cannot found the default backup target" controller=longhorn-kubernetes-secret-controller node=10.23.9.103
time="2023-01-19T14:50:38Z" level=warning msg="Error syncing ConfigMap longhorn-system/longhorn-default-setting" controller=longhorn-kubernetes-configmap-controller error="longhorn-kubernetes-configmap-controller: failed to sync longhorn-system/longhorn-default-setting: failed to update built-in settings with customized values: admission webhook \"validator.longhorn.io\" denied the request: failed to set the setting taint-toleration with invalid value : cannot modify toleration setting before all volumes are detached" node=10.23.9.103
time="2023-01-19T14:50:38Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598" controller=longhorn-volume error="failed to sync longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598: unable to get engine image longhornio/longhorn-engine:master-head: engineimage.longhorn.io \"ei-b907910b\" not found" node=10.23.9.103
time="2023-01-19T14:50:38Z" level=warning msg="Error syncing Longhorn engine" controller=longhorn-engine engine=longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598-e-8663b2d2 error="failed to sync engine for longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598-e-8663b2d2: unable to get engine image longhornio/longhorn-engine:master-head: engineimage.longhorn.io \"ei-b907910b\" not found" node=10.23.9.103
time="2023-01-19T14:50:38Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598" controller=longhorn-volume error="failed to sync longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598: unable to get engine image longhornio/longhorn-engine:master-head: engineimage.longhorn.io \"ei-b907910b\" not found" node=10.23.9.103
E0119 14:50:38.881304       1 volume_controller.go:226] failed to sync longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598: unable to get engine image longhornio/longhorn-engine:master-head: engineimage.longhorn.io "ei-b907910b" not found
time="2023-01-19T14:50:38Z" level=warning msg="Dropping Longhorn volume longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598 out of the queue" controller=longhorn-volume error="failed to sync longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598: unable to get engine image longhornio/longhorn-engine:master-head: engineimage.longhorn.io \"ei-b907910b\" not found" node=10.23.9.103
time="2023-01-19T14:50:38Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598" controller=longhorn-volume error="failed to sync longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598: unable to get engine image longhornio/longhorn-engine:master-head: engineimage.longhorn.io \"ei-b907910b\" not found" node=10.23.9.103
time="2023-01-19T14:50:38Z" level=warning msg="Error syncing ConfigMap longhorn-system/longhorn-default-setting" controller=longhorn-kubernetes-configmap-controller error="longhorn-kubernetes-configmap-controller: failed to sync longhorn-system/longhorn-default-setting: failed to update built-in settings with customized values: admission webhook \"validator.longhorn.io\" denied the request: failed to set the setting taint-toleration with invalid value : cannot modify toleration setting before all volumes are detached" node=10.23.9.103
time="2023-01-19T14:50:38Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598" controller=longhorn-volume error="failed to sync longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598: unable to get engine image longhornio/longhorn-engine:master-head: engineimage.longhorn.io \"ei-b907910b\" not found" node=10.23.9.103
time="2023-01-19T14:50:38Z" level=warning msg="Error syncing Longhorn engine" controller=longhorn-engine engine=longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598-e-8663b2d2 error="failed to sync engine for longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598-e-8663b2d2: unable to get engine image longhornio/longhorn-engine:master-head: engineimage.longhorn.io \"ei-b907910b\" not found" node=10.23.9.103
time="2023-01-19T14:50:38Z" level=warning msg="Error syncing ConfigMap longhorn-system/longhorn-default-setting" controller=longhorn-kubernetes-configmap-controller error="longhorn-kubernetes-configmap-controller: failed to sync longhorn-system/longhorn-default-setting: failed to update built-in settings with customized values: admission webhook \"validator.longhorn.io\" denied the request: failed to set the setting taint-toleration with invalid value : cannot modify toleration setting before all volumes are detached" node=10.23.9.103
time="2023-01-19T14:50:38Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598" controller=longhorn-volume error="failed to sync longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598: unable to get engine image longhornio/longhorn-engine:master-head: engineimage.longhorn.io \"ei-b907910b\" not found" node=10.23.9.103
time="2023-01-19T14:50:38Z" level=fatal msg="Error starting manager: admission webhook \"validator.longhorn.io\" denied the request: failed to set the setting taint-toleration with invalid value : cannot modify toleration setting before all volumes are detached"

`

**Comment by PhanLe1010** [comment]
What was the exact command that you used to install Longhorn? 

Looks like there are some master-head images which shouldn't be possible if you are using the correct v1.4.0 yamls:
```
time="2023-01-19T14:50:38Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598" controller=longhorn-volume error="failed to sync longhorn-system/pvc-ab70a1f5-954d-45e8-91a0-ce1bf9e3c598: unable to get engine image longhornio/longhorn-engine:master-head: engineimage.longhorn.io "ei-b907910b" not found" node=10.23.9.103
```

**Comment by ilanni2460** [comment]
@PhanLe1010 I installed the latest version of longhorn before. After uninstalling, I installed the longhorn1.4.0 version and kept reporting this error message. I don’t know if it’s because I didn’t uninstall it cleanly.

This is the command I uninstalled:
`kubectl delete -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml

kubectl delete ns longhorn-system --grace-period=0 --force

kubectl patch crd/engines.longhorn.io -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/replicas.longhorn.io -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/volumes.longhorn.io -p '{"metadata":{"finalizers":[]}}' --type=merge`

Execute the delete command on the node node:
`rm -fr  /var/lib/longhorn/*`

**Comment by roger-ryao** [comment]
Hi @ilanni2460 :
     We introduce a new setting since Longhorn v1.4.0, [deleting-confirmation-flag](https://longhorn.io/docs/1.4.0/deploy/uninstall/#prerequisite).
     If you install Longhorn with the kubectl client, you can refer to [uninstalling-longhorn-using-kubectl](https://longhorn.io/docs/1.4.0/deploy/uninstall/#uninstalling-longhorn-using-kubectl).

**Comment by PhanLe1010** [comment]
@ilanni2460  Looks like you have not uninstall Longhorn correctly. Please follow [the doc](https://github.com/longhorn/longhorn/issues/5311#issuecomment-1399973514) mentioned by @roger-ryao above

**Comment by ilanni2460** [comment]
@PhanLe1010 @roger-ryao Thank you very much for your answers, but because I did not follow the official documentation when uninstalling the latest version, I don't know what other configurations or other configurations have not been uninstalled on the cluster or node.

**Comment by Flannigan** [comment]
@ilanni2460 I ended up in a similar situation due to an improper uninstall. In my case the following command (from [this stackoverflow post](https://stackoverflow.com/questions/47691479/listing-all-resources-in-a-namespace)) listed the resources I could not find:
`kubectl api-resources --verbs=list --namespaced -o name   | xargs -n 1 kubectl get --show-kind --ignore-not-found -n longhorn-system`
Deleting those resources evidently allowed a subsequent install (via helm, for unrelated reasons) to work.

**Comment by ilanni2460** [comment]
@Flannigan Thank you very much, this is the result of my execution of the above command, I installed and uninstalled longhorn through kubectl.
`kubectl api-resources --verbs=list --namespaced -o name   | xargs -n 1 kubectl get --show-kind --ignore-not-found -n longhorn-system`
![2023-01-31_134106](https://user-images.githubusercontent.com/5058391/215675590-3fdb9f82-f51b-4211-8e04-b894b65b8156.png)

**Comment by Naist4869** [comment]
> kubectl delete ns longhorn-system --grace-period=0 --force

有解决吗 我也是按照你这样卸载出现跟你一样的报错

**Comment by Naist4869** [comment]
> @Flannigan非常感谢，这是我执行上面命令的结果，我通过kubectl安装和卸载longhorn。 `kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found -n longhorn-system` ![2023-01-31_134106](https://user-images.githubusercontent.com/5058391/215675590-3fdb9f82-f51b-4211-8e04-b894b65b8156.png)

```bash
umount /var/lib/kubelet/plugins/kubernetes.io/driver.longhorn.io/074c28982de640b649034fcd5bbfd8a3c8de7b2a4afd6597e476e0c12b5757cb/globalmount
rm -rf /var/lib/kubelet/plugins/kubernetes.io/driver.longhorn.io
umount /var/lib/kubelet/pods/eb2bdf03-f3d9-49ee-8530-9f5584116569/volumes/kubernetes.io~csi/pvc-9b7f0822-9394-40ba-83cb-8bc048df0232/mount
rm -rf /var/lib/kubelet/pods/eb2bdf03-f3d9-49ee-8530-9f5584116569
```
