### ISSUE TITLE
[BUG] instance-manager-r high memory consumption

### ISSUE THREAD

**Issue by ArthurVardevanyan** [longhorn/longhorn#5312]
## Describe the bug (🐛 if you encounter this issue)

instance-manager-r high memory consumption after 1.4.0 upgrade

Note sure if this expected behavior or a bug.

## To Reproduce

**Note:** I do have  ```snapshotDataIntegrity: enabled``` on all volumes

## Log or Support bundle

Attached Support Bundle
[supportbundle_00e45f14-1554-4313-bb2b-27dbf74ab4c7_2023-01-22T03-05-13Z.zip](https://github.com/longhorn/longhorn/files/10473635/supportbundle_00e45f14-1554-4313-bb2b-27dbf74ab4c7_2023-01-22T03-05-13Z.zip)

## Environment
 - Kubernetes Distribution: OKD: 4.12.0-0.okd-2023-01-21-055900
 - Longhorn version: v1.4.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Number of management node in the cluster: 3
 - Number of worker node in the cluster: 6
 - Node config
   - OS type and version: Fedora CoreOS 37
   - CPU per node: 4
   - Memory per node: ~13GB
   - Disk type(e.g. SSD/NVMe): NVME
   - Network bandwidth between the nodes: 1Gigabit Across "Zones", NVME Disk Speed in Same "Zone"
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 50 

## ScreenShots
The Dips are from Reboots
![Screenshot from 2023-01-21 22-00-49](https://user-images.githubusercontent.com/21159051/213898835-4b95d907-502e-4048-a906-bbc3de2658da.png)
![Screenshot from 2023-01-21 22-07-56](https://user-images.githubusercontent.com/21159051/213898842-1876ff8d-75a1-4279-81ed-0790926be2c8.png)

**Comment by derekbit** [comment]
> ## Describe the bug (🐛 if you encounter this issue)
> instance-manager-r high memory consumption after 1.4.0 upgrade
> 
> Note sure if this expected behavior or a bug.
> 
> ## To Reproduce
> **Note:** I do have `snapshotDataIntegrity: enabled` on all volumes

@ArthurVardevanyan 
Is memory usage high only after `napshotDataIntegrity: enabled`?

**Comment by ArthurVardevanyan** [comment]
> > ## Describe the bug (bug if you encounter this issue)
> > instance-manager-r high memory consumption after 1.4.0 upgrade
> > Note sure if this expected behavior or a bug.
> > ## To Reproduce
> > **Note:** I do have `snapshotDataIntegrity: enabled` on all volumes
> 
> @ArthurVardevanyan Is memory usage high only after `snapshotDataIntegrity: enabled`?

I believe so.

1. While it is snapshotting /w snapshotDataIntegrity I have observed spikes.
    - "Immediate Snapshot Data Integrity Check After Creating a Snapshot"
    - Midnight (Every Night), is when my snapshot job triggers, it doesn't seem to release memory afterwords.
    - Yellow line is Memory Requests
    ![image](https://user-images.githubusercontent.com/21159051/213900380-52b5ba35-8bd2-4ac0-9a3a-1c12e030f05c.png)

2. I turned it back off to validate, I'll let it run like this for a day or so.
    - I turned off snapshotDataIntegrity, 
    - ran a snapshot, 
    - shut workload
    - deleted all longhorn pods
    - turned everything back on
    - ran a snapshot.

**Comment by ArthurVardevanyan** [comment]
> IIRC, the memory usage also includes the usage of cache memories. The hash calculation reads data from file and calculate the chcecksum by `io.Copy` and buffer io ([code](https://github.com/longhorn/longhorn-engine/blob/master/pkg/replica/hash.go#L373)). Hence, the memory usage becomes high because of the cache memories.

Good to know,  thanks for the info.

> You can drop cache one of the nodes by `echo 3 > /proc/sys/vm/drop_caches` and check the memory usage again. 

I'll give this is try, once I switch it back on.

>BTW, any OOM occured?

At a pod level, if it did, I didn't catch it. (No Limits, so technically shouldn't have)

At a node level, I did have one node lock up completely, because it ran out of memory, 
(since the usage far exceeded the requests), but that was only one time in the last couple weeks.

**Comment by derekbit** [comment]
> At a node level, I did have one node lock up completely, because it ran out of memory, (since the usage far exceeded the requests), but that was only one time in the last couple weeks.

I think the memory usage including cache memories might lead to confusion and unexpected behavior if the checks rely on the memory usage. Using direct IO instead can avoid the uncertainty and confusion.

**Comment by ArthurVardevanyan** [comment]
> > At a node level, I did have one node lock up completely, because it ran out of memory, (since the usage far exceeded the requests), but that was only one time in the last couple weeks.
> 
> I think the memory usage including cache memories might lead to confusion and unexpected behavior if the checks rely on the memory usage. Using direct IO instead can avoid the uncertainty and confusion.
> 
> 
If the memory usage of the pod doesn't include the cache memories, then wouldn't the the ram usage of the system become obsucated?


If memory increase is inevitable, then ideally:

Instance Memory Requests Customization: https://github.com/longhorn/longhorn/issues/4009

Or at the moment, I probably going to bump my system reserved to the worst case pod ~4-5Gigs, for pod scheduling.

**Comment by derekbit** [comment]
> If the memory usage of the pod doesn't include the cache memories, then wouldn't the the ram usage of the system become obsucated?

Theoretically, the non-dirty page cache can be automatically dropped if other applications need more memories. On Linux, we can observe difference memory usage numbers such VmSize, VmRSS and so on, and these are clear to users.
However, the memory usage exported by kubernetes is only a value including non-dirty page cache size. IMO, this is a bit of confusing...

> Instance Memory Requests Customization: https://github.com/longhorn/longhorn/issues/4009

Great idea. It is a way to limit the memory usage. 
In this case, we can simply bypass the page cache using direct io and keep the memory usage as a constant. Although, the performance might be sacrificed, but it is not a big deal for this feature.

**Comment by ArthurVardevanyan** [comment]
> echo 3 > /proc/sys/vm/drop_caches

This does reduce the memory consumption of the pod & node till the next checksum event.

Before
![Screenshot from 2023-01-22 13-56-21](https://user-images.githubusercontent.com/21159051/213934514-cbbdf898-758c-4603-829a-83f3010cb6c0.png)

After
![Screenshot from 2023-01-22 13-57-00](https://user-images.githubusercontent.com/21159051/213934507-146b0c15-4ab5-4b15-a473-258247bf842b.png)

Pod
![image](https://user-images.githubusercontent.com/21159051/213934541-edec640c-4aa4-4b5c-a028-1627ff37b369.png)

**Comment by roger-ryao** [comment]
**Verified on master-head 20230215**

- longhorn master-head ([bb1bd7d](https://github.com/longhorn/longhorn/commit/bb1bd7d4db8d5fd6e0473f11b2d407563d80a5b2)) 
- longhorn-engine master-head ([a26f857](https://github.com/longhorn/longhorn-engine/commit/a26f8576aa9db2028d41fa9204fba60c5420bf48))

**The test steps**

1. Enable `Immediate Snapshot Data Integrity Check After Creating a Snapshot`
2. Create one 40Gib volume "vol-0" on longhorn
3. Create volume's PV & PVC from longhorn UI
4. Deploy pod “mypod1” via cli `kubctl apply -f pod_mount_1vol.yaml`

<details>
<summary>pod_mount_1vol.yaml</summary>

```yaml
kind: Pod
apiVersion: v1
metadata:
  name: ubuntu-mountvol0
  namespace: default
spec:
#  nodeSelector:
#    kubernetes.io/hostname: ryao-master-w1-b97476c8-tgxrz  # worker node
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
      - mountPath: "/data/"
        name: vol-0
  volumes:
    - name: vol-0
      persistentVolumeClaim:
        claimName: vol-0
```
</details>

5. Write 20G data to volume
`kubectl exec -it ubuntu-mountvol0 -- /bin/bash`
`dd if=/dev/urandom of=/data/20G count=20000 bs=1M conv=fsync status=progress`
6. Take a snapshot
7. Wait for the finish of the checksum calculation
8. Repeat 3-5 and observe the memory usage of the instance-manager-r 
`kubectl -n longhorn-system top pods |grep 'instance-manager-r`

**Result Passed**

After repeat step 5~7 five times, the memory usage of instance-manager-r pod didn't be accumulated.

![Screenshot_20230215_130748](https://user-images.githubusercontent.com/104337648/218937435-09c75b6e-6588-47be-91cd-b57df2012812.png)

![Screenshot_20230215_130306](https://user-images.githubusercontent.com/104337648/218937491-d582d90e-aedc-4616-b936-8a8aa174f7ee.png)
