### ISSUE TITLE
[QUESTION] how do make longhorn name pvc using the app name by default?

### ISSUE THREAD

**Issue by migs35323** [longhorn/longhorn#5315]
## Question

I usually use helm to deploy stuff in k3s, point the storageClass to longhorn and it automatically creates the needed volumes by default.
my small issue is it creates anon volumes named "pvc-big-random-id" which is not very friendly
is there a way to configure longhorn to name them after the app, pvc claim name, namespace or other things by default if i am not manually choosing a name? 

not sure if this is a requested feature, if it is not, make it so <3

## Environment

 - Longhorn version: 1.3.6 (will upgrade later)
 - Kubernetes version: k3s 1.24
 - OS type and version  ubuntu 22
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Comment by PhanLe1010** [comment]
This is not controlled by Longhorn.

When you apply a PVC yaml that has the Longhorn StorageClass. [The CSI provisioner](https://github.com/kubernetes-csi/external-provisioner) (maintained by K8s team) will generate a name (pvc-xxxxxxxx) and then ask Longhorn system to create a volume under that name.

BTW, PVC has namespace scope, and the PV (same name as Longhorn volume)  has cluster scope. There might be multiple PVC with the same name on different namespaces. If the design is to create PV with the same name as PVC we would have name conflicting issue for PV.

**Comment by PhanLe1010** [comment]
Btw, you can always figure out which Longhorn volume corresponds to which PVC by looking at the yaml of the PVC:

For example, in this case, the PVC `test-pvc-2` is corresponding to Longhorn volume `pvc-62b8d0e6-15d5-403a-97b1-5405a27a4367`
```
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2023-01-11T06:19:18Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: test-pvc-2
    namespace: default
    resourceVersion: "34879747"
    uid: 62b8d0e6-15d5-403a-97b1-5405a27a4367
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    storageClassName: longhorn
    volumeMode: Filesystem
    volumeName: pvc-62b8d0e6-15d5-403a-97b1-5405a27a4367
```

**Comment by migs35323** [comment]
thank you for the explanation, i was not aware the csi provisioner was in charge of naming the unnamed volumes
