### ISSUE TITLE
Uninstalling Longhorn stuck in Terminating state after all options have failed

### ISSUE THREAD

**Issue by oheckmann** [longhorn/longhorn#5319]
I am running a K3s cluster with a stack of Grafana, Prometheus, and Longhorn for some measurements. However, I finished with the measurements that I needed to collect and I am attempting to uninstall longhorn - which was running on its own namespace. However, I botched the uninstallation process somehow, because the namespace is stuck in a terminating state.

Attempted Solutions: I tried all three methods on the longhorn documentation, of which all fail. I cannot uninstall longhorn using a helm chart as I never installed longhorn through helm in the first place. Uninstalling longhorn using the kubectl also fails to create job.batch/longhorn-uninstall because the namespace longhorn-system is in the Terminating state. Editing the CRDs and finalizers, as per the troubleshooting documentation and the following site (https://avasdream.engineer/kubernetes-longhorn-stuck-terminating) also do not fix the problem of the system terminating, as in both cases, there is no change. Using the script from https://github.com/longhorn/longhorn/blob/master/scripts/cleanup.sh also fails to terminate longhorn, as it fails to find any of the resources.

Debugging information: The query `kubectl get namespace longhorn-system -o json` gives the following results:

    {
        "apiVersion": "v1",
        "kind": "Namespace",
        "metadata": {
            "creationTimestamp": "2022-10-31T20:09:45Z",
            "deletionTimestamp": "2023-01-26T18:17:03Z",
            "labels": {
                "kubernetes.io/metadata.name": "longhorn-system",
                "name": "longhorn-system"
            },
            "name": "longhorn-system",
            "resourceVersion": "41929420",
            "uid": "f1c78184-4613-4f9d-939d-13947ac8befa"
        },
        "spec": {
            "finalizers": [
                "kubernetes"
            ]
        },
        "status": {
            "conditions": [
                {
                    "lastTransitionTime": "2023-01-26T18:29:35Z",
                    "message": "All resources successfully discovered",
                    "reason": "ResourcesDiscovered",
                    "status": "False",
                    "type": "NamespaceDeletionDiscoveryFailure"
                },
                {
                    "lastTransitionTime": "2023-01-26T18:17:27Z",
                    "message": "All legacy kube types successfully parsed",
                    "reason": "ParsedGroupVersions",
                    "status": "False",
                    "type": "NamespaceDeletionGroupVersionParsingFailure"
                },
                {
                    "lastTransitionTime": "2023-01-26T18:17:51Z",
                    "message": "All content successfully deleted, may be waiting on finalization",
                    "reason": "ContentDeleted",
                    "status": "False",
                    "type": "NamespaceDeletionContentFailure"
                },
                {
                    "lastTransitionTime": "2023-01-26T18:17:27Z",
                    "message": "Some resources are remaining: engines.longhorn.io has 2 resource instances, nodes.longhorn.io has 5 resource instances, orphans.longhorn.io has 1 resource instances, replicas.longhorn.io has 4 resource instances, snapshots.longhorn.io has 3 resource instances, volumes.longhorn.io has 2 resource instances",
                    "reason": "SomeResourcesRemain",
                    "status": "True",
                    "type": "NamespaceContentRemaining"
                },
                {
                    "lastTransitionTime": "2023-01-26T18:17:27Z",
                    "message": "Some content in the namespace has finalizers remaining: longhorn.io in 17 resource instances",
                    "reason": "SomeFinalizersRemain",
                    "status": "True",
                    "type": "NamespaceFinalizersRemaining"
                }
            ],
            "phase": "Terminating"
        }
    }

The query `kubectl api-resources --verbs=list --namespaced -o name   | xargs -n 1 kubectl get --show-kind --ignore-not-found -n longhorn-system` yields the following information.

    NAME                                                                     STATE     NODE   INSTANCEMANAGER   IMAGE   AGE
    engine.longhorn.io/pvc-1886524a-5ba0-459d-9d51-b8044fec3057-e-344e3d26   stopped                                    64d
    engine.longhorn.io/pvc-5aca06f9-adf1-45c8-b11d-6e79d9719001-e-79f24cb7   stopped                                    64d
    NAME                       READY   ALLOWSCHEDULING   SCHEDULABLE   AGE
    node.longhorn.io/master0   False   true              True          86d
    node.longhorn.io/master1   True    true              True          14d
    node.longhorn.io/master2   False   true              True          86d
    node.longhorn.io/worker0   False   true              True          70d
    node.longhorn.io/worker1   True    true              True          70d
    NAME                                                                                         TYPE      NODE
    orphan.longhorn.io/orphan-010ee0d16422c151e7e039e27fe2306815361596fa3f8b6cccc8a601b673e429   replica   master0
    NAME                                                                      STATE     NODE      DISK                                   INSTANCEMANAGER               IMAGE                               AGE
    replica.longhorn.io/pvc-1886524a-5ba0-459d-9d51-b8044fec3057-r-89dfabab   stopped   master2   c5a7e70d-09d8-43a2-9ba3-d5b65eb12b34                                                                     13d
    replica.longhorn.io/pvc-1886524a-5ba0-459d-9d51-b8044fec3057-r-a6881548   running   worker1   2d7f16e8-f11b-40e8-8935-7f0559f7674e   instance-manager-r-8ccf914f   longhornio/longhorn-engine:v1.3.2   16d
    replica.longhorn.io/pvc-5aca06f9-adf1-45c8-b11d-6e79d9719001-r-52b5a290   stopped   worker1   2d7f16e8-f11b-40e8-8935-7f0559f7674e                                                                     31d
    replica.longhorn.io/pvc-5aca06f9-adf1-45c8-b11d-6e79d9719001-r-8f0ae6c9   running   master2   c5a7e70d-09d8-43a2-9ba3-d5b65eb12b34   instance-manager-r-672003dc   longhornio/longhorn-engine:v1.3.2   13d
    NAME                                                        VOLUME                                     CREATIONTIME           READYTOUSE   RESTORESIZE   SIZE          AGE
    snapshot.longhorn.io/887f9621-5417-40b3-8999-c2695d5585d7   pvc-1886524a-5ba0-459d-9d51-b8044fec3057   2023-01-12T21:07:46Z   false        10737418240   312860672     13d
    snapshot.longhorn.io/8f11c48b-da51-4124-80b8-1316db88eb01   pvc-5aca06f9-adf1-45c8-b11d-6e79d9719001   2023-01-12T21:21:54Z   false        21474836480   20096512000   13d
    snapshot.longhorn.io/b4c31fe7-5ff5-4881-9cd8-b22fc73798bb   pvc-5aca06f9-adf1-45c8-b11d-6e79d9719001   2023-01-12T21:38:23Z   true         21474836480   102400        13d
    NAME                                                          STATE       ROBUSTNESS   SCHEDULED   SIZE          NODE      AGE
    volume.longhorn.io/pvc-1886524a-5ba0-459d-9d51-b8044fec3057   attaching   unknown                  10737418240   master0   64d
    volume.longhorn.io/pvc-5aca06f9-adf1-45c8-b11d-6e79d9719001   detaching   unknown                  21474836480             64d

Attempting to manually delete any of the items described also failed. All APIservices have Availability as TRUE.
What do I do to resolve this problem? I will provide any more information needed.

_Originally posted by @oheckmann in https://github.com/longhorn/longhorn/discussions/5318_

**Comment by joshimoo** [comment]
I am assuming that the `longhorn-system` namespace is in terminating state and all pods in that namespace have been removed. I also assume that each of the remaining longhorn custom resource has a deletion timestamp set.

To allow the namespace to be deleted you need to manually remove the finalizer from the remaining longhorn custom resources (this can be done via `kubectl edit`), so that they can be cleaned up. Afterwards ensure removal of the custom resource definitions if they are not taken care of automatically. This should allow the removal of the namespace and any existing longhorn custom resource.

The most likely cause for this state is the absence of the deletion confirmation flag plus then manual deletion operations that bypass the above checks, once a namespace is marked for deletions no further resources can be created in it so one ends up stuck in this scenario.

**Comment by oheckmann** [comment]
Yes, the longhorn-system is stuck in the terminating state. 
Also, when I use ` kubectl get -n longhorn-system all`, it tells me that there are no resources in the namespace. However, when I use the command `kubectl api-resources --verbs=list --namespaced -o name   | xargs -n 1 kubectl get --show-kind --ignore-not-found -n longhorn-system`, it gives me a whole list of resources that are in the namespace as seen above (at least, I think that this is what the command is retrieving). 

When I try to edit any resource in Longhorn, such as by using the command `kubectl edit replica.longhorn.io` (or any other resource), it tells me that no objects are found. Editing the deletion confirmation flag as per the link that you shared failed as well for the same reason.

**Comment by oheckmann** [comment]
Is there any way to tell which precise resource is the longhorn namespace is the sticking point?

**Comment by oheckmann** [comment]
Update: using the solution I found [here](https://stackoverflow.com/a/70662999), I managed to delete the namespace. However, I still have problems with orphaned resources in the deleted namespaces. How do I deleted these?

**Comment by weizhe0422** [comment]
@oheckmann After setting finalizer to the namespace object, could you help to check what kind of workloads are still exists?

**Comment by oheckmann** [comment]
@weizhe0422 When I check for the resources using the query `kubectl api-resources --verbs=list --namespaced -o name   | xargs -n 1 kubectl get --show-kind --ignore-not-found -n longhorn-system` , as in the original post it returns the exact same results as in the original post. In that, nothing has really changed.

**Comment by murech** [comment]
I have the same issue when uninstall the helm chart for longhorn v1.4.0. I can't delete Nodes (lhn). Removing finalizer does not work:

kubectl edit lhn ltc-4 -n longhorn-system
error: nodes.longhorn.io "ltc-4" could not be patched: Internal error occurred: failed calling webhook "validator.longhorn.io": failed to call webhook: Post "https://longhorn-admission-webhook.longhorn-storage.svc:9443/v1/webhook/validaton?timeout=10s": service "longhorn-admission-webhook" not found

Any idea how to resolve this?

**Comment by chr0n1x** [comment]
just a heads up that the linked doc doesnt exist

**Comment by adegoodyer** [comment]
For future reference this is how I managed to force delete the longhorn resources and crds.

In my particular use case I'd install Longhorn with Helm via an ArgoCD application and removed the application (so not following the correct Helm uninstall instructions).

This left the namespace in a terminating state due to finalizers being present and without the longhorn-admission-webhook service, manifests of orphaned resources could not be edited to manually remove the finalizers.

Attempting to recreate those resources in the longhorn-system namespace or any other namespace (e.g. longhorn-temp) didn't work.

```bash
# viewing manifest for longhorn-system namespace in terminating state will show resources that cannot be deleted
k get ns longhorn-system -o yaml
# status:
#   conditions:
#   - lastTransitionTime: "2025-01-13T10:31:42Z"
#     message: 'Failed to delete all resource types, 2 remaining: Internal error occurred:
#       failed calling webhook "validator.longhorn.io": failed to call webhook: Post
#       "https://longhorn-admission-webhook.longhorn-system.svc:9502/v1/webhook/validation?timeout=10s":
#       service "longhorn-admission-webhook" not found, Internal error occurred: failed
#       calling webhook "validator.longhorn.io": failed to call webhook: Post "https://longhorn-admission-webhook.longhorn-system.svc:9502/v1/webhook/validation?timeout=10s":
#       service "longhorn-admission-webhook" not found'
```

```bash
# when trying to edit crds to remove longhorn.io finalizers will get following error
# Failed to save resource: Internal error occurred: failed calling webhook "mutator.longhorn.io": failed to call webhook: Post "https://longhorn-admission-webhook.longhorn-system.svc:9502/v1/webhook/mutation?timeout=10s": service "longhorn-admission-webhook" not found

# remove validating and mutating webhooks
# (necessary due to "longhorn-admission-webhook" not found)
k delete validatingwebhookconfigurations.admissionregistration.k8s.io longhorn-admission-webhook && \
k delete mutatingwebhookconfigurations.admissionregistration.k8s.io longhorn-admission-webhook

# force remove resources and crds
# (will need to ctrl+c when halts and re-run multiple times)
for crd in $(kubectl get crd -o name | grep longhorn.io); do
  kubectl get $crd -n longhorn-system -o name | while read resource; do
    kubectl patch $resource -n longhorn-system --type=merge -p '{"metadata":{"finalizers":[]}}'
    kubectl delete $resource -n longhorn-system
  done
  kubectl delete $crd
done
```

```bash
# verify cleanup
k get ns
k get all -n longhorn-system
k get crd | grep longhorn.io
```
