### ISSUE TITLE
[IMPROVEMENT] faulty documentation of iscsi installer helper

### ISSUE THREAD

**Issue by anotherthomas** [longhorn/longhorn#5320]
## Describe the bug (🐛 if you encounter this issue)

The documentation describes a daemon set based installation of iscsi, but the file references an alpine image that is outdated.

## To Reproduce

1. run kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.4.0/deploy/prerequisite/longhorn-iscsi-installation.yaml
2. observe the pods downloading a really old image

## Expected behavior

A recent image should be downloaded and the code run.

## Environment

 - Longhorn version: documentation issue
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): 
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by joshimoo** [comment]
@anotherthomas @innobead I think we should probably move all the util / scripts / deployments to use the same suse image we now use for the other components. To make sure that these additional tooling would easily work with the offline/airgap setups.

**Comment by anotherthomas** [comment]
Using a full SuSE image to run apt sounds slightly excessive ;) 
But a single image does make offline setups easier. I'll update the PR. New ticket or do we recycle this one?
