### ISSUE TITLE
[BUG] Volume crashes frequently with longhorn 1.3.2 

### ISSUE THREAD

**Issue by aljabertareq** [longhorn/longhorn#5323]
## Describe the bug (🐛 if you encounter this issue)
**Problem:** on-prem Kubernetes volume crashes unexpectedly and takes down Kafka and other services with it. 

## To Reproduce

We have a on-prem solution with 

Longhorn 1.3.2, Kafka, Mongodb, sftpgo, and minio. Kubernete environment. The volume crashed a couple of days ago and today we had another crash that took Kafka and mongodb down. Here's the Kafka log: 

org.apache.kafka.common.errors.KafkaStorageException: Error while writing to checkpoint file /bitnami/kafka/data/replication-offset-checkpoint
[2023-01-29 05:58:47,900] ERROR [ReplicaManager broker=0] Error while writing to highwatermark file in directory /bitnami/kafka/data (kafka.server.ReplicaManager)
ERROR Error while writing to checkpoint file /bitnami/kafka/data/replication-offset-checkpoint (kafka.server.LogDirFailureChannel)

Here's also the system log file: 

[syslog.Jan.29.txt](https://github.com/longhorn/longhorn/files/10529318/syslog.Jan.29.txt)

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment
 - Longhorn version: 1.3.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 1 
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 
   - Memory per node:
   - Disk type(e.g. SSD/NVMe): Harddisk
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster: 8 volumes

**Comment by aljabertareq** [comment]
[](url)
[longhorn-support-bundle_641e11b3-d2f5-417c-8892-58b017d37635_2023-01-29T22-59-34Z.zip](https://github.com/longhorn/longhorn/files/10531086/longhorn-support-bundle_641e11b3-d2f5-417c-8892-58b017d37635_2023-01-29T22-59-34Z.zip)

**Comment by derekbit** [comment]
What's the problematic volume?
I assume the volume is `pvc-8fbefb5d-6a15-4b8b-be4f-c93d69b08ce3`. IO timed out between the engine and replicas. This might be due to the IO starvation of the HDD.

**Comment by derekbit** [comment]
> Yes. The pods are on hdd while the os is on a very small ssd.

We have a setting for increasing the timeout of a engine to replicas since v1.4.0 (https://longhorn.io/docs/1.4.0/references/settings/#engine-to-replica-timeout). It's expected to relieve the volume crash issue. 

You can try v1.4.0 or the incoming v1.4.1.

**Comment by derekbit** [comment]
We have a setting for increasing the timeout of a engine to replicas since v1.4.0 (https://longhorn.io/docs/1.4.0/references/settings/#engine-to-replica-timeout). It's expected to relieve the volume crash issue.

You can try v1.4.0 or the upcoming v1.4.1.

**Comment by aljabertareq** [comment]
Thanks we will try, but now we are seeing longhorn goes through an infinite loop attaching and detaching itself.

**Comment by derekbit** [comment]
@aljabertareq Can you send us the support bundle for figuring out the root cause of the infinite loop attaching and detaching?

**Comment by aljabertareq** [comment]
Here you go: 

[longhorn-support-bundle_641e11b3-d2f5-417c-8892-58b017d37635_2023-02-23T06-41-13Z.zip](https://github.com/longhorn/longhorn/files/10812175/longhorn-support-bundle_641e11b3-d2f5-417c-8892-58b017d37635_2023-02-23T06-41-13Z.zip)

**Comment by derekbit** [comment]
> Here you go:
> 
> [longhorn-support-bundle_641e11b3-d2f5-417c-8892-58b017d37635_2023-02-23T06-41-13Z.zip](https://github.com/longhorn/longhorn/files/10812175/longhorn-support-bundle_641e11b3-d2f5-417c-8892-58b017d37635_2023-02-23T06-41-13Z.zip)

Gosh. Sorry. I missed this ticket, because it was Chinese New Year vacation that time.
Will check the issue soon.

**Comment by derekbit** [comment]
Let's track the issue in https://github.com/longhorn/longhorn/issues/6188#issuecomment-1631840317
