### ISSUE TITLE
[BUG] cannot do online expansion for the old engine pvc-* with cli API version 6

### ISSUE THREAD

**Issue by dza89** [longhorn/longhorn#5324]
## Describe the bug

I'm trying to resize a couple of pvc's but running into the following error. I tried both;  longhorn gui and kube (different pvcs), but both give me the same error:

kubectl describe pvc: 
`
external-resizer driver.longhorn.io  resize volume "pvc-f21bdb95-bd6a-420d-bb6f-7ccd63dfa687" by resizer "driver.longhorn.io" failed: rpc error: code = DeadlineExceeded
`

longhorn gui:
`
Expansion Error: cannot do online expansion for the old engine pvc-f21bdb95-bd6a-420d-bb6f-7ccd63dfa687-e-6bf5313b with cli API version 6
Note: You can cancel the expansion to avoid volume crash
`

csi-resizer:
`
  1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"example-ns", Name:"example-pvc", UID:"f21bdb95-bd6a-420d-bb6f-7ccd63dfa687", APIVersion:"v1", ResourceVersion:"94821990", FieldPath:""}): type: 'Warning' reason: 'VolumeResizeFailed' resize volume "pvc-f21bdb95-bd6a-420d-bb6f-7ccd63dfa687" by resizer "driver.longhorn.io" failed: rpc error: code = DeadlineExceeded desc = volume pvc-f21bdb95-bd6a-420d-bb6f-7ccd63dfa687 expansion from existing capacity 786432000 to requested capacity 786432000 failed
`

Error message can be found [here](https://github.com/longhorn/longhorn-manager/blob/master/controller/engine_controller.go#L1171)

## To Reproduce

1. Scale down deployment
2. Click on pvc attached to deploy in the gui and resize it, or kubectl edit pvc.
3. Apply

## Expected behavior

Resizing would succeed.

## Log or Support bundle

See above

## Environment

 - Longhorn version: v1.4.0
 - Installation method: helm
 - Kubernetes distro: k0s/v1.25.4+k0s.0
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: arch linux
   - CPU per node: 4 on avg
   - Memory per node: 10GB on avg
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 1Gb
 - Underlying Infrastructure: Baremetal
 - Number of Longhorn volumes in the cluster: 21

## Additional context

I'm running pretty much vanilla longhorn v1.4.0 with default image tags so I'm not really sure where the api mismatch is coming from.

**Comment by innobead** [comment]
cc @shuo-wu

**Comment by shuo-wu** [comment]
As described in the error message, Longhorn cannot expand the volumes that are still using the old engine images and haven't been detached. To resolve it, you may need to: 
1. Scale down the workload using the old volume
2. Wait for the related volume in Longhorn GUI detached
3. Upgrade the volume.

Then you can expand the volume regardless of whether it's detached(offline) or attached(online).

**Comment by PhanLe1010** [comment]
@shuo-wu Should we add the note to the doc? It seems that user might endup in the bad state if they are not aware of this change

**Comment by shuo-wu** [comment]
@PhanLe1010 Sure, let me update the doc later.

**Comment by shuo-wu** [comment]
@dza89 Because Longhorn cannot shut down the workload or running volume without users' agreement. 
Longhorn has a setting that allows applying live upgrades for volumes automatically. But Longhorn live upgrade sometimes is not perfect then users need to do this kind of offline upgrade manually and when to do so.

**Comment by dza89** [comment]
Thanks for helping resolving the issues and the excellent product itself.
