### ISSUE TITLE
[BUG] Restoring backup fails when validating volume spec

### ISSUE THREAD

**Issue by Foritus** [longhorn/longhorn#5325]
## Describe the bug (🐛 if you encounter this issue)

I have periodic backups to S3. Today I thought I'd try restoring one today but it fails when trying to validate the volume spec:

```
unable to create volume: unable to create volume foo: Volume.longhorn.io "foo" is invalid: [spec.snapshotDataIntegrity: Unsupported value: "": supported values: "ignored", "disabled", "enabled", "fast-check", spec.unmapMarkSnapChainRemoved: Unsupported value: "": supported values: "ignored", "disabled", "enabled", spec.dataLocality: Unsupported value: "": supported values: "disabled", "best-effort", "strict-local", spec.replicaAutoBalance: Unsupported value: "": supported values: "ignored", "disabled", "least-effort", "best-effort"]
```

As far as I can tell I cannot control these values when restoring in the UI, so I'm assuming it is passing empty string to mean "inherit" but the validation is rejecting that.

## To Reproduce

1. Create a period backup job
![image](https://user-images.githubusercontent.com/601930/215336187-3ee3ef56-6895-4c14-8240-5a4f2f6a6511.png)

2. Go to the backups list for a volume and attempt to restore one
![image](https://user-images.githubusercontent.com/601930/215336207-20772c7b-c1cf-4f79-a91e-be83b2652106.png)

4. Restore config I used:
![image](https://user-images.githubusercontent.com/601930/215336266-c70b6f2d-b056-4785-b75e-ece6f2c49af6.png)

5. Observe backup restore failure
![image](https://user-images.githubusercontent.com/601930/215336286-abe41b93-2db8-485f-97b9-69c70035ed1f.png)

## Expected behavior

The backup to be restored.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.4.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: kubeadm cluster, selfhosted
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: Ubuntu 20.04.5 LTS
   - CPU per node: 10
   - Memory per node: 24GB
   - Disk type(e.g. SSD/NVMe): NVME
   - Network bandwidth between the nodes: 10gbit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 11

## Additional context

Backups are stored via Minio/S3.

**Comment by derekbit** [comment]
Is the volume created by an older LH version?

**Comment by Foritus** [comment]
Yes

**Comment by derekbit** [comment]
Got it. It looks the default values of the newly added spec fields in LH v1.4.0 are not set correctly.

```
spec.snapshotDataIntegrity
spec.unmapMarkSnapChainRemoved
spec.dataLocality
spec.replicaAutoBalance
```

**Comment by innobead** [comment]
@shuo-wu could you help with this one? thanks. 

I assume that restoring a backup via creating a volume CR would not encounter this issue, but UI does if the backup is created before 1.4.0. @derekbit @Foritus right?

**Comment by Foritus** [comment]
It fails even with backups created by 1.4.0, as in this case they are backups of a volume originally created by 1.3.2 (or possibly older, hard to verify)

**Comment by innobead** [comment]
@khushboo-rancher I believe we cover the cases about backup restore in the daily regression testing. Could help check any missing? Thanks. cc @longhorn/qa 

@Foritus Thanks for the info!

**Comment by innobead** [comment]
@derekbit I do remember we have default values covered in the mutating webhooks, so what's missing here?

**Comment by derekbit** [comment]
> @derekbit I do remember we have default values covered in the mutating webhooks, so what's missing here?

Yes, we mutate the values if they are empty strings.
https://github.com/longhorn/longhorn-manager/blob/v1.4.0/webhook/resources/volume/mutator.go#L101

**Comment by derekbit** [comment]
@Foritus
Did you disable the mutating/validating webhooks? Can you provide the result of `kubectl get MutatingWebhookConfiguration longhorn-webhook-mutator -o yaml`?

**Comment by roger-ryao** [comment]
> > @derekbit I do remember we have default values covered in the mutating webhooks, so what's missing here?
> 
> Yes, we mutate the values if they are empty strings. https://github.com/longhorn/longhorn-manager/blob/v1.4.0/webhook/resources/volume/mutator.go#L101
> 
> Update: I created a volume and backed up it in v1.3.2 and sucessfully restored it in v1.4.0.

I also tried to reproduce the issue, but I couldn't reproduce it either.

**The test steps**

1. Deploy Longhorn **v1.3.2**
2. Create and attach 1 volume.
3. Setup S3 backup target
4. Create volume backup
5. Create a period backup job 
6. Upgrade Longhorn to v1.4.0
7. Do live upgrade for volume.
8. restore the volume backup

**Comment by Foritus** [comment]
Oh wow, I think you're completely correct. I forgot that I had this problem last year:
https://github.com/longhorn/longhorn/issues/4143
and the workaround was to disable the webhook rule.

Here's the output:
[output.txt](https://github.com/longhorn/longhorn/files/10533963/output.txt)

**Comment by Foritus** [comment]
Yep, deleted the admission pods and they we recreated and now it works. Now I feel like an idiot :D sorry for the bother friends.

**Comment by derekbit** [comment]
@Foritus 
Thank you for the update.
How did you upgrade Longhorn to v1.4.0? I'm thinking why the webhook rules were not recreated during upgrade.

**Comment by Foritus** [comment]
Ah that I can tell you as I keep the upgrade script in version control

```
#!/bin/bash

# Deploy Longhorn
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.4.0/deploy/longhorn.yaml

# Set LongHorn as default storage class (Remember to do this on each upgrade too!)
kubectl patch storageclass longhorn -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

# Add a custom ingress to allow external prometheus to scrape metrics
kubectl apply -f metrics-ingress.yaml
```

**Comment by innobead** [comment]
It seems a false alarm. Removing this from the milestone.

**Comment by derekbit** [comment]
> Ah that I can tell you as I keep the upgrade script in version control
> 
> ```
> #!/bin/bash
> 
> # Deploy Longhorn
> kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.4.0/deploy/longhorn.yaml
> 
> # Set LongHorn as default storage class (Remember to do this on each upgrade too!)
> kubectl patch storageclass longhorn -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
> 
> # Add a custom ingress to allow external prometheus to scrape metrics
> kubectl apply -f metrics-ingress.yaml
> ```

Just did a quick test. The validatingWebhookConfiguration and mutatingWebhookConfiguration are regenerated after upgrade. Not sure why your environemtn didn't do the regeneration. 😕

**Comment by derekbit** [comment]
@Foritus 
Did you always re-apply the workaround mentioned in https://github.com/longhorn/longhorn/issues/4143 after upgrade?

**Comment by Foritus** [comment]
No, the last upgrade was only the kubectl apply script as above. Not sure why the pods were not regenerated honestly. Maybe it's time to rebuild my control plane.

**Comment by weizhe0422** [comment]
@Foritus Is this issue could be closed? According to previous discussion, the situation seems won't appear if the mutation webhook mechanism was enabled.
