### ISSUE TITLE
[FEATURE] Longhorn auto fstrim 

### ISSUE THREAD

**Issue by charris-ca** [longhorn/longhorn#5329]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

With the fstrim feature enabled in longhorn in 1.4 we know have the ability to trim filesystems, but this shouldn't be a manual process. 

## Describe the solution you'd like

I am requesting a feature to have an auto fstrim happening or the ability to set up a job through longhorn to trigger this fstrim.

## Describe alternatives you've considered

I've considered setting up a cronjob on the servers themselves to fstrim the longhorn mountpoints, but I prefer to have the jobs more kubernetes centric, and more tied into Longhorn.

**Comment by antonioua** [comment]
This feature would be helpful.
Currently we need to write custom bash script which grep longhorn mountpoints and run `fstrim` for them.

**Comment by c3y1huang** [comment]
Similar to https://github.com/longhorn/longhorn/issues/5186.

**Comment by innobead** [comment]
Let's track this on #5186
