### ISSUE TITLE
creating new volumes fails on custom paths

### ISSUE THREAD

**Issue by IsaackRasmussen** [longhorn/longhorn#533]
I've added a custom path and all my volume attachment fails. There is enough storage and I see Longhorn creating sub folders for the volumes but it still fails with this error:

time="2019-05-14T20:05:42Z" level=info msg="Creating volume /volume, size 1073741824000/512"
time="2019-05-14T20:05:42Z" level=fatal msg="Error running start replica command: open /volume/revision.counter: invalid argument"

That is kubectl logs for one of the pods. I run Kubernetes 1.14, baremetal on Ubuntu 18.04 and Longhorn 0.41

**Comment by yasker** [comment]
@IsaackRasmussen What file system you're using for the custom path?

**Comment by IsaackRasmussen** [comment]
I’m using ZFS

**Comment by yasker** [comment]
ZFS doesn't support DIRECT_IO until very recently. And it seems had problems with the sparse file as well. We recommended using either EXT4 or XFS instead.

**Comment by IsaackRasmussen** [comment]
I see, thanks @yasker
I will try again with a different setup

**Comment by nmaggioni** [comment]
I'm unable to attach volumes as well, with similiar pod log entries:

```
time="2019-09-15T13:35:51Z" level=info msg="Creating volume /volume, size 5368709120/512"
time="2019-09-15T13:35:51Z" level=fatal msg="Error running start replica command: file extent is unsupported: operation not supported"
```

The custom path points to a subfolder of an NFS mount (FreeNAS ZFS dataset). Only the `replicas` subfolder is created. Is there any way around this?

**Comment by yasker** [comment]
@nmaggioni Longhorn cannot use NFS for storing replica data. They don't support the file extent feature required by Longhorn. Currently, we recommended using ext4 as storage filesystem for Longhorn. XFS works too.

Btw, not sure why you want to Longhorn on top of NFS, which is already a distributed storage system.

**Comment by nmaggioni** [comment]
@yasker Thanks for the clarification, I must have missed that in the docs.

I'm migrating from Rancher v1.6 to 2.x, so I'm taking the chance to experiment with new capabilities along the road.

**Comment by yasker** [comment]
@nmaggioni Thanks for the reminder of the doc. We've added the host filesystem requirement in it.

**Comment by ainiml** [comment]
Mine is over an S3 (mainly because of storage limitations of the system design, and the storage needs to be separate, somewhere)
