### ISSUE TITLE
[IMPROVEMENT] Fix Guaranteed Engine Manager CPU recommendation forumula in UI

### ISSUE THREAD

**Issue by kourosh7** [longhorn/longhorn#5338]
The documentation for [Guaranteed Engine Manager CPU](https://longhorn.io/docs/1.4.0/references/settings/#guaranteed-engine-manager-cpu) has some formulas for engine/replica which show as:
`Guaranteed Engine Manager CPU = The estimated max Longhorn volume engine count on a node * 0.1 / The total allocatable CPUs on the node * 100.`

The Longhorn v1.3.2 UI shows this in the Settings page as well, except it is missing the multiplication asterisk in the first part of the formula, which could be confusing to users. This is what we see in the UI:
`Guaranteed Engine Manager CPU = The estimated max Longhorn volume engine count on a node 0.1 / The total allocatable CPUs on the node 100.`

**Comment by smallteeths** [comment]
The reason for the error is `*~*` Recognized by markdown syntax as <em></em>. I converted the * in guaranteed-engine-manager-cpu to `&times;` so that the browser would display it correctly. 

<img width="1002" alt="截屏2023-02-09 下午12 19 59" src="https://user-images.githubusercontent.com/27733391/217717274-e27cee2e-d10c-480c-9000-ab5f7a762c88.png">

**Comment by roger-ryao** [comment]
**Verified on master-head 20230210**

- longhorn master-head ([b1ed058](https://github.com/longhorn/longhorn/commit/b1ed0589b28a8dd510df6396267810fe6d6748a4)) 
- longhorn-manager master-head ([37500d0](https://github.com/longhorn/longhorn-manager/commit/37500d090bd9147ce8b084584cb0d1cd192f6c8a))

**The test steps**

1. Deploy Longhorn master-head
2. Setting > General >　Check `Guaranteed Engine Manager CPU`
3. Setting > General >　Check `Guaranteed Replica Manager CPU`

**Result Failed**

1. UI still missing asterisk in formulas

![Screenshot_20230210_150847](https://user-images.githubusercontent.com/104337648/218031474-65f8f05e-1f60-4a49-8587-d079f146fdb2.png)

CC @c3y1huang

**Comment by roger-ryao** [comment]
**Verified on master-head 20230210**

- longhorn master-head ([b1ed058](https://github.com/longhorn/longhorn/commit/b1ed0589b28a8dd510df6396267810fe6d6748a4)) 
- longhorn-manager master-head ([37500d0](https://github.com/longhorn/longhorn-manager/commit/37500d090bd9147ce8b084584cb0d1cd192f6c8a))

**The test steps**

1. Deploy Longhorn master-head
2. Setting > General >　Check `Guaranteed Engine Manager CPU`
3. Setting > General >　Check `Guaranteed Replica Manager CPU`

**Result Passed**
![Screenshot_20230210_160134](https://user-images.githubusercontent.com/104337648/218035766-edb1b0cf-f851-45a9-9320-d9e25c751d35.png)
