### ISSUE TITLE
[BUG] Replica rebuilding caused by rke2/kubelet restart

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5340]
## Describe the bug (🐛 if you encounter this issue)

rke2 restart makes the instance-manager becomes `unknown` but not restarted, and then triggered replica rebuilding.
The flow might be not necessary, because the data plan is still functional. In this case, the volume can keep running and no need to trigger replica rebuilding. The rebuilding should rely on the timeout mechanism in the data path.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
@derekbit @PhanLe1010 is there any workaround for this if the restarting kublete by rke2 agent is intended? 

https://longhorn.io/docs/1.4.0/references/settings/#replica-replenishment-wait-interval will be helpful here?

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by chriscchien** [comment]
Verified in longhorn-manager master `37500d`
Result **Pass**

Steps:
1. Deploy k3s cluster then deploy Longhorn master
2. Create a volume with 2 replicas
3. Run command `servies k3s-agent stop` on node containing one of the replica and the node doesn't have the volume engine
4. Wait node become not ready
5. Replica located on k3s-agent stopped node become stopped and status kept in healthy. (Before  this patch, replica located on k3s-agent stopped node will become failed and after `replica-replenishment-wait-interval` passed, there will be a replica rebuilding)
