### ISSUE TITLE
[IMPROVEMENT] Update ganesha nfs to 4.2.3

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5356]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Longhorn 1.4.0 uses 4.2.1 already, so for the upcoming 1.4, should update the used version to the latest patch of ganesha nfs 4.2.x including some critical fixes.

**Comment by roger-ryao** [comment]
**Verified on master-head 20230207**

- longhorn master-head ([a7119b5](https://github.com/longhorn/longhorn/commit/a7119b5bda64159316c063978cd3e7e2bfdc5bbe)) 



**The test steps**
1. Run e2e test test_rwx.py

**Result Passed**

1. https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2972/testReport/
![Screenshot_20230207_130734](https://user-images.githubusercontent.com/104337648/217156073-28019d6d-a8e3-4ce6-8a59-8d37e3406e92.png)
