### ISSUE TITLE
[FEATURE] Support replica-zone-soft-anti-affinity setting per volume

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5358]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Longhorn has several global volume settings; one example is replica zone soft anti-affinity. We should make this kind of global setting also volume-specific to override the global behavior.

UPDATE: also need to add replica soft anti-affinity setting

## Describe the solution you'd like

A clear and concise description of what you want to happen

## Describe alternatives you've considered

N/A

## Additional context

Adopt the same way from the recent volume-specific settings like `UnmapMarkSnapChainRemoved` which is also `bool`.

**Comment by innobead** [comment]
@ChanYiLin as discussed, let's create a ticket to make all volume-specific settings that have a corresponding global setting to follow the same value pattern.

**Comment by ChanYiLin** [comment]
@innobead 
I have created the ticket here: https://github.com/longhorn/longhorn/issues/5886

**Comment by ChanYiLin** [comment]
Hi @smallteeths
This issue needs UI support and the milestone is 1.5.0, thanks!

So we are adding two new fields to volume creation api
- `ReplicaSoftAntiAffinity`: string; value: `ignore`, `disabled`, `enabled` 
- `ReplicaZoneSoftAntiAffinity`: string; value: `ignore`, `disabled`, `enabled` 

Thanks!

**Comment by ChanYiLin** [comment]
Hi @smallteeths 
Sorry forgot to mention that
After volume creation, we also need to allow user to update this two field in this drop down menu
Thanks

![345496539_1952339021792947_1840873639963220889_n](https://github.com/longhorn/longhorn/assets/7100904/2b40f3d6-1cf3-4553-9aad-f618241d0797)

**Comment by chriscchien** [comment]
Hi @ChanYiLin,

I tested the setting value on both UI and CLI, they can be set and have distinctive value.

But can you help me to clarify below behavior is correct?

1. In a 3 nodes cluster, tag two nodes to `topology.kubernetes.io/zone: lh-zone1`,  the rest node to `topology.kubernetes.io/zone: lh-zone2`
2. Create a 1 replica volume which  `replicaSoftAntiAffinity: ignored`, `replicaZoneSoftAntiAffinity: enabled`
3. Attach volume to node, make sure replica is located on `lh-zone1`
4. Increase replica count to 2
5. In my environment, the new replica locate on node labeled with `lh-zone2`, follow instructions from UI the new replica should located on the same zone with the healthy replica? or it's not mendatory, thank you.  


![image](https://github.com/longhorn/longhorn/assets/73337386/e31b74f7-a998-4daa-aad9-f3704739668a)
![image](https://github.com/longhorn/longhorn/assets/73337386/ba9edbd8-eec5-4189-a4a0-1af1cd3d95ec)
![image](https://github.com/longhorn/longhorn/assets/73337386/36cda180-d044-46f2-a067-d27319aebaeb)
![image](https://github.com/longhorn/longhorn/assets/73337386/b14bf04a-01ca-430a-8414-ac444ee06916)
![image](https://github.com/longhorn/longhorn/assets/73337386/f4912662-caf6-4cfc-95d0-1c24c76030fe)


[supportbundle_94691f35-d2b4-42d6-bb59-26f1869772c6_2023-05-30T05-02-37Z.zip](https://github.com/longhorn/longhorn/files/11596112/supportbundle_94691f35-d2b4-42d6-bb59-26f1869772c6_2023-05-30T05-02-37Z.zip)

**Comment by ChanYiLin** [comment]
replicaZoneSoftAntiAffinity: enabled
enable only means they can be placed in the same zone
but not force them to be in the same zone

**Comment by chriscchien** [comment]
Verified **pass** in longhorn master (longhorn-manager `023dd3`, longhorn-ui `5219e4`) with test [steps](https://github.com/longhorn/longhorn/issues/5358#issuecomment-1541438854)

- Volumes have distinct setting value of `replicaSoftAntiAffinity` and `replicaZoneSoftAntiAffinity`, those values can be modify from both CLI and UI
- Functionality of `replicaSoftAntiAffinity`, `replicaZoneSoftAntiAffinity` on volume followed the setting value and worked properly
