### ISSUE TITLE
[BUG] DR volume become faulted when upgrade to compatible engine

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#5376]
## Describe the bug (🐛 if you encounter this issue)

From master-head [e2e](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/393/testReport/junit/tests/test_engine_upgrade/test_auto_upgrade_engine_to_default_version_dr_volume_s3_/) test case `test_auto_upgrade_engine_to_default_version_dr_volume` and can be reproduced manually.

DR volume become faulted when upgrade to compatible engine.

## To Reproduce

1. Deploy Longhorn master-head , setup backupstore
2. Deploy compatible engine image `longhornio/longhorn-test:upgrade-test.7-3.4-3.1-1`
3. Make sure setting 'concurrent-automatic-engine-upgrade-per-node-limit setting` = 0 (the defautl value)
4. Create volume, create backup, create DR volume from backup
5. Upgrade DR volume to compatible engine image
6. DR volume become faulted

## Expected behavior

DR volume should upgrade to compatible engine image without problem

## Log or Support bundle

[supportbundle_29693f80-58d6-4c10-bbf7-d1bf148ec091_2023-02-09T02-45-04Z.zip](https://github.com/longhorn/longhorn/files/10693020/supportbundle_29693f80-58d6-4c10-bbf7-d1bf148ec091_2023-02-09T02-45-04Z.zip)

## Environment

 - Longhorn version: master-head `1deb51`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.25.6+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3

## Additional context

N/A

**Comment by innobead** [comment]
@shuo-wu can u check this?

**Comment by shuo-wu** [comment]
Just checked the SB as well tried to reproduce it, I found that somehow some of replicas will encounter the following error during restore:
```
2023-02-09T02:38:31.278506579Z [vol1-r-dd1718ec] time="2023-02-09T02:38:31Z" level=info msg="Successfully initiated full restore for s3://chris816@us-east-1/backup/?backup=backup-261f9d4a3584478c&volume=vol1 to [volume-snap-f491d9b6-1dda-447b-adc5-56d9a82d0f19.img]"
2023-02-09T02:38:33.280138941Z [vol1-r-dd1718ec] time="2023-02-09T02:38:33Z" level=error msg="Backup data restore Error Found in Server[gzip: invalid header]"
```

This one is not related to the upgrade of DR volumes, it may be triggered as long as a replica starts to restore a backup, no matter if the replica is a newly created one during upgrade. And the reason why the upgrade can trigger this is, the upgrade for a DR volume will trigger a full restore for all upgraded replicas.

Currently I haven't figure out the root cause. It may be related to the recent backup compression method improvement https://github.com/longhorn/longhorn/issues/5189. @derekbit Do you have any hints?

**Comment by innobead** [comment]
It looks restoring using the wrong  compress method.

**Comment by innobead** [comment]
@chriscchien does this only happen in the master branch? Compression method is only introduced to 1.5/master.

**Comment by derekbit** [comment]
@chriscchien Can you regenerate the engine image `longhornio/longhorn-test:upgrade-test.7-3.4-3.1-1` and test it again? It seems the new compression logics are not in it.

**Comment by chriscchien** [comment]
After rebuild test engine image `longhornio/longhorn-test:upgrade-test.7-3.4-3.1-1`, this failed scenario passed on both pipeline test and manual test, if there is no concern I will close this issue, thank you.

**Comment by innobead** [comment]
Thanks @chriscchien and @derekbit
