### ISSUE TITLE
[IMPROVEMENT] Set write-cache of longhorn block device to off explicitly

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5382]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The Longhorn block device does not support write cache, but the below message confuses users.
```
[Fri Dec  9 11:43:44 2022] sd 9:0:0:1: [sdg] Write cache: enabled, read cache: enabled, supports DPO and FUA
```
To avoid confusion, the write-cache should be explicitly disabled and conform to SCSI specifications.

**Comment by chriscchien** [comment]
Verified in Longhorn master `4b17f8` with test [steps](https://github.com/longhorn/longhorn/issues/5382#issuecomment-1427380176)
Result **Pass**

In longhorn` master head`, after execute command `dmesg | grep "Write cache"` on node which volume attached to, can see below log indicated that write cache of longhorn block device was closed.
```
[ 2732.426024] sd 2:0:0:1: [sda] Write cache: disabled, read cache: enabled, supports DPO and FUA
```
In contrast, if the command was executed on `v1.4.0`, dmesg will show below log.
```
[ 3228.012493] sd 2:0:0:1: [sda] Write cache: enabled, read cache: enabled, supports DPO and FUA
```
