### ISSUE TITLE
[FEATURE] Add replica to RAID1 bdev

### ISSUE THREAD

**Issue by DamiaSan** [longhorn/longhorn#5387]
SPDK Raid1 bdev addition

We are waiting that this feature will be added in SPDK upstream. Developers are currently working on rebuild feature that should contain the capability to add a new bdev to an existing raid1 bdev.

**Comment by innobead** [comment]
This is for tracking some upstream work, but it's part of #5420

**Comment by innobead** [comment]
Let's track replica management at https://github.com/longhorn/longhorn/issues/5420 instead.
