### ISSUE TITLE
[IMPROVEMENT] Clean up unused backupstore mountpoint

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5391]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The backupstore mountpoint is created when listing backups at the first time. If the user changes the backup target setting, a new mountpoint for the backupstore is created while the old one remains and is unused. The unused mountpoints can be cleaned up for preventing potential issues, such as high CPU usage of the old NFS client with `hard` mode caused by the service outage of its NFS server.

```
# mount

....

(old and unused backupstore mountpoint)
10.20.90.100:/Longhorn on /var/lib/longhorn-backupstore-mounts/10_20_90_100/Longhorn type nfs4 (rw,relatime,vers=4.2,rsize=262144,wsize=262144,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.42.1.13,local_lock=none,addr=10.20.90.100)

(current backupstore mountpoint)
longhorn-test-nfs-svc.default.svc.cluster.local:/opt/backupstore on /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default_svc_cluster_local/opt/backupstore type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.42.1.13,local_lock=none,addr=10.42.1.37)
```

The issue is found in any Longhorn version.

**Comment by innobead** [comment]
@derekbit Do you remember why we decided not to backport to 1.4 and 1.3?

**Comment by derekbit** [comment]
> @derekbit Do you remember why we decided not to backport to 1.4 and 1.3?

I remember we don't want to create v1.3/v1.4 branches in backupstore that time.

**Comment by innobead** [comment]
> > @derekbit Do you remember why we decided not to backport to 1.4 and 1.3?
> 
> I remember we don't want to create v1.3/v1.4 branches in backupstore that time.

Thanks @derekbit . I think we need to backport this, it seems to have 1.3 and 1.4 branches now.

**Comment by chriscchien** [comment]
Verified in longhorn master `15701b`
Result **Pass**

Create 2 NFS backup store and switch them through UI. Observe mount point In `longhorn-manager` pod, in `master-head` the unused mount point clean up success.

Not clean up scenario can reproduce in `v1.4.1` and the mount point will look like below
```
longhorn-manager-kwvqj:/ # mount | grep nfs
longhorn-test-nfs-svc.default:/opt/backupstore on /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.42.4.18,local_lock=none,addr=10.42.4.14)
longhorn-test-nfs-svc2.default:/opt/backupstore on /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc2_default/opt/backupstore type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,acregmin=1,acregmax=1,acdirmin=1,acdirmax=1,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.42.4.18,local_lock=none,addr=10.42.6.10)

```
