### ISSUE TITLE
[IMPROVEMENT] Expect LH to clarify the uploading file specification

### ISSUE THREAD

**Issue by w13915984028** [longhorn/longhorn#5395]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

LH backing image uploading functionality

## Describe the solution you'd like

With the wide deployment of Harvester, users are trying to upload big image file, but there are some issues openning.

We expect LH has defined specification about:
```
  The supported biggest single-file image size.
  What will influence the uploading, how long will it timeout, is it possible to set this timeout ?
  When timeout happens, will LH clear related temp file ?
  Troubleshooting guide.
```

And also add those into auto test.

## Additional context

Already fixed issue: https://github.com/longhorn/longhorn/issues/4865

Other openning issue:
https://github.com/harvester/harvester/issues/3450, some POD crashed inbetween the uploading an 75Gb single-file image.

https://github.com/longhorn/longhorn/issues/4902 touchs more components, the vm-importer is an upper layer controller, which utilizes the uploading functionality.

Some discussions are left in https://github.com/longhorn/longhorn/issues/4865

**Comment by w13915984028** [comment]
The temp files are not cleaned ...

https://github.com/harvester/harvester/issues/3450#issuecomment-1431746258

```
ls -lah /var/lib/harvester/defaultdisk/tmp
total 172G
drw-r--r-- 2 root root 4.0K Feb 15 18:16 .
drwxr-xr-x 6 root root 4.0K Jan 17 15:15 ..
-rw-r--r-- 1 root root  71G Feb 13 19:53 tanngarden-image-8ml6t-da639078.tmp
-rw-r--r-- 1 root root  71G Feb 15 18:27 tanngarden-image-8n59l-8f1402ce.tmp
-rw-r--r-- 1 root root  43G Feb 12 15:54 tanngarden-image-twdv2-cc507605.tmp
```

**Comment by w13915984028** [comment]
I created https://github.com/longhorn/longhorn/issues/3682 for the left uncleaned temp file, but seems not solved yet. Lets track together.

**Comment by roger-ryao** [comment]
**Verified on v1.4.x-head 20230217**

- longhorn v1.4.x-head ([034d5a2](https://github.com/longhorn/longhorn/commit/034d5a2f316c30359411e1c3aaa5f2dd935136ba)) 

**The test steps**

1. Launch a 75G backing image
2. Create vol-0 with 75G backing image
3. Create PV and PVC
4. Create pod mount vol-0

**Result Passed**

1. We could upload 75G backing image to longhorn, the volume could be mounted

![Screenshot_20230217_172052](https://user-images.githubusercontent.com/104337648/219608843-14ff208c-0db8-448f-9628-8206c0bbb209.png)

![Screenshot_20230217_172622](https://user-images.githubusercontent.com/104337648/219608859-2e3aff0d-bbad-435e-9a33-62161f7463fb.png)

[supportbundle_2abd40a1-6c64-478e-9264-4808407b777b_2023-02-17T09-27-10Z.zip](https://github.com/longhorn/longhorn/files/10765302/supportbundle_2abd40a1-6c64-478e-9264-4808407b777b_2023-02-17T09-27-10Z.zip)

cc @longhorn/dev  @longhorn/qa

**Comment by w13915984028** [comment]
@roger-ryao That's good news.

Could you list your test settings: how many nodes, how is longhorn installed, the replica number, the roughly network topology and the estimated network speed from the uploading maching to LH node, and how is the disk size in your LH env.

Another question is about the `Actual Size` in your test, why a 75Gi image only occupy 599 Mi actual size, is this file simply filled with 0  for most of the content? I doubt this is different than an real converted image file.

Thanks.

**Comment by roger-ryao** [comment]
Hi @w13915984028 :
    My environment list is below. You could provide your 75Gi image to me. I could help to test my environment.

## Environment

 - Longhorn version: **v1.3.x-head**
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):**Kubectl**
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:**v1.24.9+k3s2**
   - Number of management node in the cluster: **1**
   - Number of worker node in the cluster: **3**
 - Node config
   - OS type and version: **Ubuntu 20.04.2 LTS**
   - CPU per node: **4 core**
   - Memory per node: **16GiB**
   - Disk Size: **400GB** 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): **AWS EC2 t2.xlarge**

**Comment by shuo-wu** [comment]
> Another question is about the Actual Size in your test, why a 75Gi image only occupy 599 Mi actual size,

The screenshot is the Volume page. And the volume actual size won't count the backing image.

**Comment by w13915984028** [comment]
@roger-ryao thanks for your test.

Please also take a look below discussion, I guess the Harvester installation with embedded LH, will have more potential bottlenecks.

https://github.com/harvester/harvester/issues/3450#issuecomment-1438183069

**Comment by w13915984028** [comment]
FYI: the big image uploading issue is reproduced in Harvester, and more infromation are attached in 
https://github.com/harvester/harvester/issues/3450, thanks.

cc @innobead @shuo-wu @roger-ryao

**Comment by innobead** [comment]
Jian has done the analysis for the root cause, https://github.com/harvester/harvester/issues/3450#issuecomment-1440849829. Basically, the uploading functionality works as expected in a synchronous way with streaming mode, so there is no size limitation given the underling space/memory allowed, but it would cause callers with some challenges to fail in the middle in the front if having some request timeout limitation. 

@ChanYiLin will create another issue to improve that, especially checksum calculation in an asynchronous mode, so we will track it there instead.
