### ISSUE TITLE
[TASK] Run build-engine-test-images automatically when having incompatible engine on master

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5400]
## What's the task? Please describe

Currently, it's necessary to update the test images for engine upgrade manually when longhorn-engine is incompatible with the previous version via the `build-engine-test-images` job on CI. However, this way would be prone to miss to cause a cascading effort to investigate why the test cases of engine upgrades could be failed.

Making it automatic instead of manual operation will improve this situation.

## Describe the items of the task (DoD, definition of done) you'd like

- [ ] Trigger `build-engine-test-images` automatically somehow (ex: periodical daily check should be enough) when longhorn-engine (engine/controller part) is incompatible from the previous version 

## Additional context

cc @longhorn/dev

**Comment by yangchiu** [comment]
ref: https://github.com/longhorn/longhorn/issues/4219 https://github.com/longhorn/longhorn-tests/pull/1012
