### ISSUE TITLE
NFS backup with kerberos authentication[BUG]

### ISSUE THREAD

**Issue by frit0-rb** [longhorn/longhorn#5402]
## Describe the bug (🐛 if you encounter this issue)

I got Longhorn in rancher rje2 install for 3 cluster, and the problem coming when I tried to enable backup target and backup target credential secret.
When the anonymous access is enabled and don't use a Secret, NFS backups work properly. But when I activate Kerberos authentication and disable anonymous access NFS never works.

The NFS is a shared folder in a Windows Machine with this feature:

![image](https://user-images.githubusercontent.com/56691791/219306881-46385434-a913-4afb-9be7-4f828020ded4.png)

Like the documentation show us is necessary to create a Secret, this is the secret we created:

kubectl create secret generic nfs-secret -n longhorn-system --from-literal=username=user@domain.lan --from-literal=password='passw@rd'

## To Reproduce

1. Go to 'Harbor UI --> Setting --> Backup'
3. Perform '.Backup Target and Backup Target Credential Secret'

error listing backup volume names: failed to execute: /var/lib/longhorn/engine-binaries/rancher-mirrored-longhornio-longhorn-engine-v1.3.2/longhorn [backup ls --volume-only nfs://server.domain.lan:/management], output Cannot mount nfs server.domain:/management: vers=4.0: Failed to execute: mount [-t nfs4 -o nfsvers=4.0 -o actimeo=1 server.domain.lan:/management /var/lib/longhorn-backupstore-mounts/server_domain_lan/management], output mount.nfs4: Protocol not supported , error exit status 32: vers=4.1: Failed to execute: mount [-t nfs4 -o nfsvers=4.1 -o actimeo=1 server.domain.lan:/management /var/lib/longhorn-backupstore-mounts/server_domain_lan/management], output mount.nfs4: Operation not permitted , error exit status 32: vers=4.2: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 -o actimeo=1 server.domain.lan:/management /var/lib/longhorn-backupstore-mounts/server_domain_lan/management], output mount.nfs4: Protocol not supported , error exit status 32: Cannot mount using NFSv4 , stderr, time="2023-02-16T08:20:44Z" level=error msg="Cannot mount nfs server.domain.lan:/management: vers=4.0: Failed to execute: mount [-t nfs4 -o nfsvers=4.0 -o actimeo=1 server.domain.lan:/management /var/lib/longhorn-backupstore-mounts/server_domain_lan/management], output mount.nfs4: Protocol not supported\n, error exit status 32: vers=4.1: Failed to execute: mount [-t nfs4 -o nfsvers=4.1 -o actimeo=1 server.domain.lan:/management /var/lib/longhorn-backupstore-mounts/server_domain_lan/management], output mount.nfs4: Operation not permitted\n, error exit status 32: vers=4.2: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 -o actimeo=1 server.domain.lan:/management /var/lib/longhorn-backupstore-mounts/server_domain_lan/management], output mount.nfs4: Protocol not supported\n, error exit status 32: Cannot mount using NFSv4" , error exit status 1

## Expected behavior

The Backups will do via Kerberos authentication

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.3.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 5
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 17

**Comment by weizhe0422** [comment]
I found there was a comment talking about this: https://github.com/longhorn/longhorn/issues/1388#issuecomment-661371338 


Longhorn needs to be re-architected to support secure backups using Kerberos.
