### ISSUE TITLE
[QUESTION] Optimize  backing image download 

### ISSUE THREAD

**Issue by liyimeng** [longhorn/longhorn#5405]
When download a longhorn backing image, which is sized with about 128G, but actually only contains 1GB data. It seem longhorn process It as 128G and comsue a lot of IO and CPU resource. Can this be optimized?

**Comment by innobead** [comment]
cc @shuo-wu

**Comment by shuo-wu** [comment]
For the downloading part, what Longhorn knows is the URL link only. This URL won't tell you how many zero blocks can be skipped. Currently, we haven't found an API or a straightforward way to get details of downloading sparse files, hence I don't think it can be optimized. 
What Longhorn has optimized is that, after receiving a data chunk, it will check if it's a zero chunk then skip the unnecessary data writing if YES.

**Comment by derekbit** [comment]
@shuo-wu 

Just curious.

>  it will check if it's a zero chunk

Do you mean check each byte in the chunk?

**Comment by shuo-wu** [comment]
In brief YES: https://github.com/longhorn/backing-image-manager/blob/3cb922d175822c1b9b22fc0573abf6a899468648/pkg/sync/handler.go#L151-L154

**Comment by innobead** [comment]
cc @ChanYiLin for context awareness

**Comment by liyimeng** [comment]
hmm， in my case, the backing image is another longhorn volume inside the cluster. i.e. longhorn itself have knowledge of the data on server size, would there be a way to optimize even further?

**Comment by shuo-wu** [comment]
The backing image file transfer inside Longhorn system is already optimized. And it's similar to the file syncing of replica rebuilding.

**Comment by liyimeng** [comment]
Thanks @shuo-wu  we continue to observe for a while to see how well it performs.

**Comment by liyimeng** [comment]
In cluster image seem work with acceptable performance, thank for the good work!
