### ISSUE TITLE
[Feature request] Ability to fetch backup information / restore from command line

### ISSUE THREAD

**Issue by vitobotta** [longhorn/longhorn#541]
Rather than using the Longhorn the UI at the moment I can also restore a volume by creating a storage class with the URL of the backup to restore, and then creating a PVC that uses that storage class. However I still need to use the Longhorn UI to find the URL of the backup. It would be great if I could fetch the backup information via kubectl or something.

Even better, it would be super awesome if I could restore a volume directly from command line like I can with Velero, by providing namespace and volume name. That would be immensely helpful in automating/scriptng restores. Thanks!

**Comment by yasker** [comment]
This would be implemented as a part of #613
