### ISSUE TITLE
[BUG] Volume rebuild ignores disk tags

### ISSUE THREAD

**Issue by albertkohl-monotek** [longhorn/longhorn#5413]
## Describe the bug (🐛 if you encounter this issue)
I have a 6-node harvester cluster. 3 nodes have a node-tag of lff, on each of those nodes, two of the disks have a hdd tag.
when i reboot a node, and longhorn has to rebuild replicas, it schedules them onto the hdd drives, rather then on the drives without tags. 

## To Reproduce

1. setup a 3 node cluster each with 3 disks.
   - two disks 1tb
   - one disk 4tb
2. tag each node with lef
3. tag 4tb disks with hdd
4. setup storage class
5. provision 2 disks onto default SC
6. provision 1 disk onto the custom SC created in step 4
7. once replicas are all built and health, delete one replica from a pvc on the default SC
8. that replica should get rescheduled onto the custom SC

## Expected behavior

Longhorn should schedule the deleted replica onto an untagged SC

## Log or Support bundle
[longhorn-support-bundle_b0b85b06-bd06-434b-95e8-c47b11be903f_2023-02-19T16-42-39Z.zip](https://github.com/longhorn/longhorn/files/10777406/longhorn-support-bundle_b0b85b06-bd06-434b-95e8-c47b11be903f_2023-02-19T16-42-39Z.zip)

## Environment

 - Longhorn version: 1.3.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Harvester HCI v1.1.1
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 1.24
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3+3
 - Node config
   - OS type and version: harvester HCI
   - CPU per node: 24+
   - Memory per node: 256+

   - Disk type(e.g. SSD/NVMe): mostly SSD, 6 HDDs spread accross 3 hosts
   - Network bandwidth between the nodes: 10G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 64

StorageClass:
![image](https://user-images.githubusercontent.com/60982735/219962418-e041348b-57c3-4fa2-a2e9-73610eaafb8e.png)

Node Tag:
![image](https://user-images.githubusercontent.com/60982735/219962851-838d82a1-83a0-4ae9-9a96-dbe1f162883a.png)

Volume Details:
State: Attached 
Health:
Healthy
Ready for workload:Ready
Conditions:
restore
scheduled
Frontend:Block Device
Attached Node & Endpoint:
harvester-06
/dev/longhorn/pvc-1cf7a2f7-f221-47d6-9bf3-d5b3ace834fd
Size:
100 Gi
Actual Size:53.4 Gi
Data Locality:disabled
Access Mode:ReadWriteMany
Engine Image:longhornio/longhorn-engine:v1.3.2
Created:25 days ago
Encrypted:False
Node Tags:
Disk Tags:
Last Backup:
Last Backup At:
Replicas Auto Balance:ignored
Instance Manager:
instance-manager-e-6667c1ae
Namespace:k8s
PVC Name:mk8s-win-02-rootdisk-0nzve
PV Name:pvc-1cf7a2f7-f221-47d6-9bf3-d5b3ace834fd
PV Status:Bound
Revision Counter Disabled:False
Pod Name:virt-launcher-mk8s-win-02-bvq2z
Pod Status:Running
Workload Name:mk8s-win-02
Workload Type:VirtualMachineInstance

replica schedule onto disk with tags, when it's an untagged volume: 
![image](https://user-images.githubusercontent.com/60982735/219962952-0d4c577b-5cac-43ec-b137-0ac04362c751.png)
![image](https://user-images.githubusercontent.com/60982735/219963017-7189e577-71fa-41ca-9d8b-78e487fc8918.png)

**Comment by weizhe0422** [comment]
Hi @albertkohl-monotek 

I checked the replica scheduler logic, and if I understood correctly, I found that if the volume label is empty, then all disks are candidates for scheduling. But I'll do some more to confirm it.

https://github.com/longhorn/longhorn-manager/blob/2976b0d7cd8f7d8d258f15bef90433f539a46483/scheduler/replica_scheduler.go#L355-L368
```golang
func (rcs *ReplicaScheduler) checkTagsAreFulfilled(itemTags, volumeTags []string) bool {
	if !sort.StringsAreSorted(itemTags) {
		logrus.Warnf("BUG: Tags are not sorted, sort now")
		sort.Strings(itemTags)
	}


	for _, tag := range volumeTags {
		if index := sort.SearchStrings(itemTags, tag); index >= len(itemTags) || itemTags[index] != tag {
			return false
		}
	}


	return true
}
```

**Comment by joshimoo** [comment]
Related improvement request https://github.com/longhorn/longhorn/issues/4826
