### ISSUE TITLE
[BUG] Modify engineManagerCPURequest and replicaManagerCPURequest won't raise resource request in instance-manager-e pod

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#5419]
## Describe the bug (🐛 if you encounter this issue)

From test case [test_instance_manager_cpu_reservation](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/405/testReport/junit/tests/test_settings/test_instance_manager_cpu_reservation/)

Modify `node.spec.engineManagerCPURequest` and `node.spec.replicaManagerCPURequest`, after instance-manager-e pod restart ready, instance-manager-e does not have cpu request. (`pod.spec.containers[0].resources`)
 
## To Reproduce

1. Run test case `test_instance_manager_cpu_reservation` or
2. Select 1 Longhorn node then `kubectl edit nodes.longhorn.io <node name> -n longhorn-system`
3. Set `node.spec.engineManagerCPURequest` to 150 and `node.spec.replicaManagerCPURequest` to 250
4. Wait instance-manager-e pod on modified node restart ready
5. Check` pod.spec.containers[0].resources.requests['cpu']` but get `pod.spec.containers[0].resources`={}

## Expected behavior

Should have cpu request in pod.sepc.containers[0].resources

## Log or Support bundle

N/A

## Environment

 - Longhorn version: master-head `2ea551`

## Additional context

 N/A

**Comment by innobead** [comment]
This is caused by https://github.com/longhorn/longhorn-manager/commit/627afcea22bba81d52e966e0cd2d9cf45cb3a794. 

[/controller/controller_manager.go#L191-L204](https://github.com/longhorn/longhorn-manager/blob/d5498b1dcf88f56ade7f9ce17a4c75cb3aae47a3/controller/controller_manager.go#L191-L204)
```go 
        // should fix as below
	if cpuRequest == 0 {
		guaranteedCPUSetting, err := ds.GetSetting(guaranteedCPUSettingName)
		if err != nil {
			return nil, err
		}
		guaranteedCPUPercentage, err := strconv.ParseFloat(guaranteedCPUSetting.Value, 64)
		if err != nil {
			return nil, err
		}
		allocatableMilliCPU := float64(kubeNode.Status.Allocatable.Cpu().MilliValue())
		cpuRequest = int(math.Round(allocatableMilliCPU * guaranteedCPUPercentage / 100.0))
	}
	return ParseResourceRequirement(fmt.Sprintf("%dm", cpuRequest))
```

**Comment by innobead** [comment]
@c3y1huang see if this needs to backport.

**Comment by c3y1huang** [comment]
> @c3y1huang see if this needs to backport.

Only on the master branch, no need to backport.

**Comment by chriscchien** [comment]
Test  case `test_instance_manager_cpu_reservation` passed on master-head  [AMD64](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/407/testReport/tests/test_settings/) and [ARM64](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/388/testReport/tests/test_settings/test_instance_manager_cpu_reservation/)  daily run, close this ticket.
