### ISSUE TITLE
[FEATURE] Manage replicas of RAID1 bdev

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5420]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Support managing replicas (add/remove/get/replace) of each RAID1 bdev and ensure non-disruptive IO during management if the volume is degraded. 

## Describe the solution you'd like

Have RPC commands for replica management. Each replica initialization still needs to manage by longhorn-spdk-engine. 

## Additional context

cc @longhorn/dev-data-plane

**Comment by DamiaSan** [comment]
There is a development under review to remove base bdev from RAID1:
https://review.spdk.io/gerrit/c/spdk/spdk/+/15267/35

**Comment by DamiaSan** [comment]
For the functionality to add a base bdev, we are waiting that the development will be put under code review: #5387

**Comment by innobead** [comment]
> For the functionality to add a base bdev, we are waiting that the development will be put under code review: #5387 If this development will not be ready soon, we will proceed on our own

I transfer this issue to EPIC and include https://github.com/longhorn/longhorn/issues/5387 in this EPIC. I only see https://review.spdk.io/gerrit/c/spdk/spdk/+/15267, anything else? It seems pending for a while, I believe we should start the downstream first. This is mandatory for us in 1.5.0. 

cc @shuo-wu @derekbit

**Comment by DamiaSan** [comment]
I agree, we will develop this functionality in downstream
