### ISSUE TITLE
[TASK] Update k8s.gcr.io to registry.k8s.io in repos

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5432]
## What's the task? Please describe

Need to check all repos using `k8s.grc.io` and replica it with `registry.k8s.io`. Need to verify those images available as well. 

## Describe the items of the task (DoD, definition of done) you'd like

- [x] The repos are longhorn, longhorn-test, and website. Need to fix the master, v1.4.x, and v1.3.x. 

## Additional context

ref: https://github.com/longhorn/longhorn/pull/5429

cc @longhorn/dev

**Comment by innobead** [comment]
@yangchiu Please prioritize this.

**Comment by yangchiu** [comment]
For `longhorn`:
- master: https://github.com/longhorn/longhorn/pull/5429
- v1.4.x: https://github.com/longhorn/longhorn/pull/5430
- v1.3.x: https://github.com/longhorn/longhorn/pull/5431

For `longhorn-test`:
- master: https://github.com/longhorn/longhorn-tests/pull/1256
- v1.4.x: https://github.com/longhorn/longhorn-tests/pull/1273
- v1.3.x: https://github.com/longhorn/longhorn-tests/pull/1274

For `website`:
- master: https://github.com/longhorn/website/pull/668
