### ISSUE TITLE
[IMPROVEMENT] Fix BackingImage uploading/downloading flow to prevent client timeout

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#5443]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

When creating BackingImage with upload type, data source pod will calculate the checksum of the image after it is uploaded. It is a synchronous call and may be time consuming. This could lead to the timeout of the client .

## Describe the solution you'd like

We can calculate checksum in a goroutine to prevent from blocking current go routine .

## Additional context

This improvement request is due to the issue: [harvester/harvester#3450](https://github.com/harvester/harvester/issues/3450)

**Comment by w13915984028** [comment]
@ChanYiLin 

After further analysis in https://github.com/harvester/harvester/issues/3555

The enhancement may need to consider:  move `finishProcessing` out of normal upload/download process, return OK to the client/server side first.

Further, add a new status to the image, it is `downloaded/uploaded` instead of `StateReady`,  after get & verify checksum,  set the image to be `StateReady`

```
func (sf *SyncingFile) finishProcessingNoLock(err error) (finalErr error) {
....
	sf.progress = 100
	sf.size = sf.processedSize
	sf.state = types.StateReady
	sf.log = sf.log.WithFields(logrus.Fields{
		"size":            sf.size,
		"currentChecksum": sf.currentChecksum,
	})
```


```
func (sf *SyncingFile) DownloadFromURL(url string) (written int64, err error) {
	sf.log.Infof("SyncingFile: start to download sync file from URL %v", url)

	needProcessing, err := sf.stateCheckBeforeProcessing()
	if err != nil {
		return 0, err
	}
	if !needProcessing {
		return 0, nil
	}

	defer func() {
		if finalErr := sf.finishProcessing(err); finalErr != nil {
			err = finalErr
		}
	}()

	size, err := sf.handler.GetSizeFromURL(url)
	if err != nil {
		return 0, err
	}
	sf.lock.Lock()
	sf.size = size
	sf.log.WithField("size", size)
	sf.lock.Unlock()

	return sf.handler.DownloadFromURL(sf.ctx, url, sf.tmpFilePath, sf)
}
```

**Comment by ChanYiLin** [comment]
Hi @innobead @w13915984028 
I am not familiar with Harvester implementation
But would like to know 
When the upload is finished and the connection from Harvester is broken due to timeout, I know there is a time that the page on Harvester will show `failed` with `context canceled`.

However, after the BackingImage finished calculating checksum and become ready, the BackingImage CR is also marked ready.

Would Harvester Controller reconcile the CR information from Longhorn and change the status back to ready?

Thanks!

**Comment by ChanYiLin** [comment]
After discussion with @FrankYang0529 to further understand Harvester system, there is more finding about 
Why Harvester UI still showed `Failed` with `context cancel` when BackingImage became ready in the end ?

It is because there is an defer function for error handling in Harvester api code 
https://github.com/harvester/harvester/blob/ce5aff93c04740723244f83c527d1297a97877e3/pkg/api/image/formatter.go#L143-L149
This line will update the `virtualMachineImage` Imported condition status to `False` with message `context cancel`

And in `virtualMachineImage` controller where it syncs status from `Backingimage`
https://github.com/harvester/harvester/blob/ce5aff93c04740723244f83c527d1297a97877e3/pkg/controller/master/image/backing_image_controller.go#L40
If the Imported condition status is `False` it will not sync with Backingimage and consider it as final status

So even BackingImage kept calculating the checksum and update status to ready after the timeout broke the connection,
Harvester had no chance to update the status back to ready because it already considered it failed when api broke.

cc @innobead @shuo-wu

**Comment by innobead** [comment]
I believe the imported condition of the VM image should be always based on the backing image as source of truth, even though this is beyond the scope.

Good analysis, thanks :+1:

**Comment by chriscchien** [comment]
Verified in longhorn master (longhorn-manager `8f89d6`, backing-image-manager `455f01`)
Result **Pass**

Before this patch, when uploading a large BackingImage which data source pod need more then 90s to get the checksum, `longhorn-manager` will raise timeout error. For example this behavior can reproduced in v1.4.1:
 
In data source pod the checksum calculate time was about 3 minutes
```
time="2023-03-20T07:36:54Z" level=debug msg="SyncingFile: failed to get the checksum from a valid config during processing wrap-up, will directly calculated it then"
2023/03/20 07:38:24 http: proxy error: context canceled
time="2023-03-20T07:39:44Z" level=debug msg="SyncingFile: writing config file when the file becomes ready" component=sync-file currentChecksum=e5095efa1ba5039c8cbc8c714722d1769dd8c707d416e47d45e34f517c2a087090d134f8267b2169e5a7cc2acfdc2c3033bdc042432ee06538dd93d1f68a5ce3 filePath=/data/tmp/vol1-629f78c2 size=94371840000 uuid=629f78c2
time="2023-03-20T07:39:44Z" level=info msg="SyncingFile: succeeded processing file" component=sync-file currentChecksum=e5095efa1ba5039c8cbc8c714722d1769dd8c707d416e47d45e34f517c2a087090d134f8267b2169e5a7cc2acfdc2c3033bdc042432ee06538dd93d1f68a5ce3 filePath=/data/tmp/vol1-629f78c2 size=94371840000 uuid=629f78c2
```
While the checksum was calculating, longhorn manager will raise timeout error:
```
ime="2023-03-20T07:33:55Z" level=info msg="Forwarding backing image upload request to URL http://10.42.0.68:8000/v1/file?action=upload&size=94371840000"
time="2023-03-20T07:37:06Z" level=error msg="failed to get vol1 info from backing image data source server: get failed, err: Get \"http://10.42.0.68:8000/v1/file\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" backingImageDataSource=vol1 controller=longhorn-backing-image-data-source diskUUID=d071fa74-7eea-4a34-80fc-d3e3b21d2985 node=worker1 nodeID=worker1 parameters="map[]" sourceType=upload
```

After this patch, upload the same BackingImage, it still need more than 90s to get checksum but `longhorn-manager` won't raise `Client.Timeout` error, close this ticket, thank you.
