### ISSUE TITLE
[QUESTION] /var/lib/longhorn file destroied，how to re install longhorn

### ISSUE THREAD

**Issue by WindKn** [longhorn/longhorn#5447]
after manually delete file from /var/lib/longhorn, then try to uninstall longhorn,then apply -f longhorn.yaml re install it,then get error for longhorn-manager:
time="2023-02-24T06:19:38Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-09a70348-9411-4226-b005-344cb1603d01" controller=longhorn-volume error="failed to sync longhorn-system/pvc-09a70348-9411-4226-b005-344cb1603d01: unable to get engine image longhornio/longhorn-engine:v1.4.0: engineimage.longhorn.io \"ei-fc06c6fb\" not found" node=kaihong-pubz-wxxxc
time="2023-02-24T06:19:38Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-8e4f15bd-9d50-4794-9008-5f7965b04113" controller=longhorn-volume error="failed to sync longhorn-system/pvc-8e4f15bd-9d50-4794-9008-5f7965b04113: unable to get engine image longhornio/longhorn-engine:v1.4.0: engineimage.longhorn.io \"ei-fc06c6fb\" not found" node=kaihong-pubz-wxxxc
time="2023-02-24T06:19:38Z" level=warning msg="Error syncing ConfigMap longhorn-system/longhorn-default-setting" controller=longhorn-kubernetes-configmap-controller error="longhorn-kubernetes-configmap-controller: failed to sync longhorn-system/longhorn-default-setting: failed to update built-in settings with customized values: admission webhook \"validator.longhorn.io\" denied the request: failed to set the setting taint-toleration with invalid value : cannot modify toleration setting before all volumes are detached" node=kaihong-pubz-wxxxc
time="2023-02-24T06:19:38Z" level=warning msg="Error syncing ConfigMap longhorn-system/longhorn-default-setting" controller=longhorn-kubernetes-configmap-controller error="longhorn-kubernetes-configmap-controller: failed to sync longhorn-system/longhorn-default-setting: failed to update built-in settings with customized values: admission webhook \"validator.longhorn.io\" denied the request: failed to set the setting taint-toleration with invalid value : cannot modify toleration setting before all volumes are detached" node=kaihong-pubz-wxxxc
E0224 

in this situation,what should do to re install this.How can I clean Longhorn volume, already clean pv and pvc in k3s.

**Comment by WindKn** [comment]
after change with new name space, start ok ,but create pvc get error:
driver.longhorn.io_csi-provisioner-5d8dd96b57-m4mmb_acb0de63-c838-448e-b4c7-28f413c77b87  failed to provision volume with StorageClass "longhorn": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to create volume: unable to create volume pvc-c5ae3837-0ab6-422d-84ae-56e3235b768c: create not allowed while custom resource definition is terminating] from [http://longhorn-backend:9500/v1/volumes]

**Comment by chriscchien** [comment]
Is it convenient for you to try uninstall Longhorn by instructions here https://longhorn.io/docs/1.4.0/deploy/uninstall/ ?
And see if namespace `longhorn-system` disappear after uninstall?

If namespace `longhorn-system` stuck at `Terminating` this means some longhorn resources not clean up.
(We should not see  any longhorn.io CRD after uninstall complete by command  `kubectl get crd`)
Thank you.

**Comment by shuo-wu** [comment]
It seems that things messed up...
You may need to manually clean up all Longhorn CRD first (by removing the finalizers via `k patch`). And you can get all Longhorn CRD with cmd `kubectl get crd | grep longhorn.io`
