### ISSUE TITLE
[BUG] Helm-Chart uninstallation impossible if longhorn-crd is removed first

### ISSUE THREAD

**Issue by Lennix** [longhorn/longhorn#5453]
## Describe the bug (🐛 if you encounter this issue)

If you remove longhorn via helm und uninstall longhorn and longhorn-crd at the same time, it might happen that the CRDs get removed first (or in case user removes crds manually first) and then deleting-confirmation-setting is missing and uninstallation of longhorn stalls.

## To Reproduce

1. Uninstall longhorn-crd
2. Uninstall longhorn

## Expected behavior

Either check if CRD is missing and uninstall as if flag was set to yes.
Or give clear instructions on how to re-install the flag to enable the user to continue with uninstallation.

## Additional Steps tried

1. `kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs deleting-confirmation-flag`
> Error from server (NotFound): the server could not find the requested resource (get settings.longhorn.io deleting-confirmation-flag)`

2. Create settings.longhorn.io from template and run 1.
> Error from server (NotFound): settings.longhorn.io "deleting-confirmation-flag" not found

## Environment

 - Longhorn version: 1.4
 - Installation method: helm

**Comment by shuo-wu** [comment]
How do you directly delete the CRDs via Helm... Typically the deletion will be blocked by the finalizers. It's better not to remove the finalizers manually.

**Comment by shuo-wu** [comment]
I knew. That's the normal way how Rancher installs projects. But I don't know if `longhorn-crd` can be uninstalled first... Typically we will uninstall `longhorn` then `longhorn-crd`

**Comment by roger-ryao** [comment]
> I knew. That's the normal way how Rancher installs projects. But I don't know if `longhorn-crd` can be uninstalled first... Typically we will uninstall `longhorn` then `longhorn-crd`
Hi @shuo-wu :
I'm aware of the note in the manual test case (https://github.com/longhorn/longhorn-tests/blame/master/docs/content/manual/pre-release/uninstallation/uninstallation-checks.md#L18), but I'm uncertain of the reason behind it, so I'm simply following the steps provided for uninstalling Longhorn.

**Comment by shuo-wu** [comment]
>  I'm uncertain of the reason behind it

@roger-ryao 
Checking and removing CRs are the main steps of the uninstallation job. But if the removing CRD before running the uninstallation job/starting the uninstallation, the job will get stuck in getting CR.
You can check [the uninstallation code](https://github.com/longhorn/longhorn-manager/blob/bb6dd1a312f0a032a87af81e38018c22153912c9/controller/uninstall_controller.go#L100) for details.

**Comment by Lennix** [comment]
Any ideas how I could re-install the longhorn-crds chart separately?

**Comment by Lennix** [comment]
For anyone else running into this issue:

`kubectl apply -f deploy/longhorn.yaml`

This deployed the CRDs for me and so I was able to run the uninstall routine.

**Comment by c3y1huang** [comment]
Closing as the issue seems to be resolved. Feel free to re-open.
