### ISSUE TITLE
[BUG] Backup never completes

### ISSUE THREAD

**Issue by cskwrd** [longhorn/longhorn#5454]
## Describe the bug (🐛 if you encounter this issue)

Neither clicking the `Create Backup` button nor "converting" a snapshot to a backup creates a completed backup.

## To Reproduce

1. Navigate to a bound volume.
2. Click on 'Create Backup'
3. Wait for some time.
4. No error, backup never appears in `Backups`, volume's 'Last Backup At' date is never filled, backup progress (on volume page) only shows

## Expected behavior

A backup is taken and stored at `<backup target>`.

## Log or Support bundle

[longhorn-supportbundle_6d10b550-6969-45c9-9be3-360ce69d224b_2023-02-28T14-28-11Z.zip](https://github.com/longhorn/longhorn/files/10851395/longhorn-supportbundle_6d10b550-6969-45c9-9be3-360ce69d224b_2023-02-28T14-28-11Z.zip)

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.25.6+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster: 1

## Additional context

The volume I am testing with was not created using the Longhorn UI.
I have tried both NFS and minIO backup targets.

**Comment by derekbit** [comment]
Can you provide the support bundle?

**Comment by shuo-wu** [comment]
BTW, can you access the backup target and check if the backup is being uploaded?

**Comment by cskwrd** [comment]
> Can you provide the support bundle?

Is there a way to obfuscate internal domain names from the logs?

**Comment by cskwrd** [comment]
> BTW, can you access the backup target and check if the backup is being uploaded?

When using NFS I did not see anything on the backup target. However in that case I think there might be a protocol version issue.

When using minIO, it appears that some backups might exist there however the size reported on what I think are the backup files are impossibly small. The volume I am trying to back up is approximately 140MB and minIO reports sizes less than 300 *bytes*.

**Comment by cskwrd** [comment]
@derekbit I have modified the original report to include a support bundle.
