### ISSUE TITLE
[IMPROVEMENT] List of Longhorn Helm Chart Flags

### ISSUE THREAD

**Issue by zackbradys** [longhorn/longhorn#5455]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Difficult to easily view a list of all possible helm chart flags. Of course, you are able to manually determine these using the helm chart values, but like other rancher products, there usually is a list of the flags within the docs or chart readme.

## Describe the solution you'd like

Add the list of helm chart flags to the [longhorn docs](https://longhorn.io/docs/) and [helm chart readme](https://github.com/longhorn/longhorn/tree/master/chart).

## Describe alternatives you've considered

Current alternative to this feature improvement request is to manually go through the helm chart values file to determine to helm install flags.

## Additional context

I'd be will to submit a draft of these changes/additions. No other additional context to provide to this request!

**Comment by zackbradys** [comment]
Yes, the helm values. Most helm chart repos have the values represented in a table within the readme. You are correct, you're able to view the values.yaml, but having the values in documentation.

It would be nice to have it implemented for longhorn to match the rest of the rancher products (MCM, NV, RKE2, etc..)

**Comment by zackbradys** [comment]
Hey @innobead / @ChanYiLin, are we still on track to complete this in the Longhorn `v1.6.0` release?

**Comment by ChanYiLin** [comment]
Hi @zackbradys 
Yes, this feature request will be in Longhorn v1.6.0 which will be released in December.
