### ISSUE TITLE
[QUESTION]  DS engine-image not Ready

### ISSUE THREAD

**Issue by Beastlex** [longhorn/longhorn#5462]
## Question

After fresh install pods of DS engine-image are not Ready. Readness probe failed. But if we run 
```
k exec -n longhorn-system engine-image-ei... -ti -- /bin/bash
```
and then run
```bash
sh -c ls /data/longhorn && /data/longhorn version --client-only
```
and recieve json output. 

## Environment

 - Longhorn version: 1.3.2
 - Kubernetes version: 1.24.5 (Cri-O)
 - Node config
   - OS type and version Ubuntu 22.04
   - CPU per node: 6
   - Memory per node: 8Gb
   - Disk type SSD
   - Network bandwidth and latency between the nodes: 10Gb
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Comment by shuo-wu** [comment]
it seems that something is wrong with the readiness probe for that pod. Can killing (and restarting) the pod resolve this?

**Comment by Beastlex** [comment]
Thanks. But restarting pods not work. Pods are in the same status

**Comment by shuo-wu** [comment]
Can you provide the kubelet log of the nodes the NotReady pods reside on? Need to check the error message of the readiness probe first and see what happened.

**Comment by shuo-wu** [comment]
Besides, Longhorn team needs to investigate if the engine image daemonset needs both the liveness probe and readiness probe. They seem to be redundant.
