### ISSUE TITLE
[BUG] [master] [v1.4.1-rc1] Volume restoration will never complete if attached node is down

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#5464]
## Describe the bug (🐛 if you encounter this issue)

From https://longhorn.github.io/longhorn-tests/manual/pre-release/backup-and-restore/restore-volume-node-down/

During volume restoration in progress, shutdown the attached node, volume restoration will never complete and volume will stuck at `attaching` state.

Happened in longhorn mastre-head `e1ea3d` and v1.4.1-rc1 but not in v1.4.0

## To Reproduce

1. Create a backup.
2. Restore the above backup.
3. Power off the volume attached node during the restoring.
4. Wait for the Longhorn node down.
5. Wait for the restore volume being reattached and starting restoring volume with state Degraded.
6. Volume stuck at `attaching` state and the restore will never complete 

## Expected behavior

Volume attached to another node then restore complete after awhile

## Log or Support bundle

[supportbundle_2c216df5-e12c-4b2e-8373-0833d6802812_2023-03-02T03-46-21Z.zip](https://github.com/longhorn/longhorn/files/10867339/supportbundle_2c216df5-e12c-4b2e-8373-0833d6802812_2023-03-02T03-46-21Z.zip)

## Environment

 - Longhorn version: master-head `e1ea3d` and v1.4.1-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:  v1.24.7+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 1

## Additional context

N/A

**Comment by weizhe0422** [comment]
I think this is related to this [change](https://github.com/longhorn/longhorn-manager/pull/1691); it will continue keep waiting without attach on the node since the status of replica on the stopped node  is `stopped`.

https://github.com/longhorn/longhorn-manager/blob/c29563ca46a476b4ebc52cdfe9e6b8126a31ec10/controller/volume_controller.go#L1609-L1611
```golang
if r.Status.CurrentState != longhorn.InstanceStateRunning {
          return nil
}
```

Before this modification, the time will be recorded in the `FailedAt` field of the replica on the stopped node
https://github.com/longhorn/longhorn-manager/blob/9e4630586a9484d63d0c6f6826d0568b10391afe/controller/volume_controller.go#L1498-L1500
```golang
if r.Spec.FailedAt == "" {
	r.Spec.FailedAt = vc.nowHandler()
}
```
so it will be skipped in the checking mechanism
https://github.com/longhorn/longhorn-manager/blob/9e4630586a9484d63d0c6f6826d0568b10391afe/controller/volume_controller.go#L1521-L1523
```golang
if r.Spec.FailedAt != "" {
	   continue
}
```
cc @innobead @derekbit

**Comment by derekbit** [comment]
```
if r.Status.CurrentState != longhorn.InstanceStateRunning {
          return nil
}
```
Probably need to check the nodeDownOrDeleted as well?

**Comment by weizhe0422** [comment]
you mean like this way, right?
```golang
	if r.Status.CurrentState != longhorn.InstanceStateRunning {
		nodeDown, err := vc.ds.IsNodeDownOrDeleted(r.Spec.NodeID)
		if err != nil || nodeDown {
			continue
		}
		return nil
	}
```

**Comment by derekbit** [comment]
Yeah.

**Comment by derekbit** [comment]
@weizhe0422 
If the node is down for a long time, will be replica become stopped? IIRC, it should become stopped.

**Comment by weizhe0422** [comment]
Yes, I noticed that the replica status will change to "Stopped".

**Comment by innobead** [comment]
@rayandas is the status of the engine also unknown? If yes, because `r.Status.CurrentState` is also unknown, there is no chance to make the replica fail. 

[/controller/volume_controller.go#L543-L566](https://github.com/longhorn/longhorn-manager/blob/c29563ca46a476b4ebc52cdfe9e6b8126a31ec10/controller/volume_controller.go#L543-L566)
```go
	if e.Status.CurrentState == longhorn.InstanceStateUnknown {
		if v.Status.Robustness != longhorn.VolumeRobustnessUnknown {
			v.Status.Robustness = longhorn.VolumeRobustnessUnknown
			vc.eventRecorder.Eventf(v, v1.EventTypeWarning, constant.EventReasonUnknown, "volume %v robustness is unknown", v.Name)
		}
		return nil
	}
	if e.Status.CurrentState != longhorn.InstanceStateRunning {
		// If a replica failed at attaching stage before engine become running,
		// there is no record in e.Status.ReplicaModeMap
		engineInstanceCreationCondition := types.GetCondition(e.Status.Conditions, longhorn.InstanceConditionTypeInstanceCreation)
		isNoAvailableBackend := strings.Contains(engineInstanceCreationCondition.Message, fmt.Sprintf("exit status %v", int(syscall.ENODATA)))
		for _, r := range rs {
			if isNoAvailableBackend || (r.Spec.FailedAt == "" && r.Status.CurrentState == longhorn.InstanceStateError) {
				log.Warnf("Replica %v that not in the engine mode map is marked as failed, current state %v, engine name %v, active %v",
					r.Name, r.Status.CurrentState, r.Spec.EngineName, r.Spec.Active)
				e.Spec.LogRequested = true
				r.Spec.LogRequested = true
				r.Spec.FailedAt = vc.nowHandler()
				r.Spec.DesireState = longhorn.InstanceStateStopped
			}
		}
		return nil
	}
```

**Comment by weizhe0422** [comment]
@innobead No, the engine state is `stopped`.  I think it is because when synchronize the im-e status to engine but the engine is not started ( `status.Started` == `false`)
![image](https://user-images.githubusercontent.com/17548901/222477176-417ef070-278a-4592-a991-3e868d0fa9ac.png)

And I think it might caused by the replica status is `stopped` not `error`, so it can't update the spec fields of replica and engine.

**Comment by innobead** [comment]
> you mean like this way, right?
> 
> ```go
> 	if r.Status.CurrentState != longhorn.InstanceStateRunning {
> 		nodeDown, err := vc.ds.IsNodeDownOrDeleted(r.Spec.NodeID)
> 		if err != nil || nodeDown {
> 			continue
> 		}
> 		return nil
> 	}
> ```

Will this cause https://github.com/longhorn/longhorn/issues/5340 not fixed? @derekbit @shuo-wu

**Comment by weizhe0422** [comment]
> > you mean like this way, right?
> > ```go
> > 	if r.Status.CurrentState != longhorn.InstanceStateRunning {
> > 		nodeDown, err := vc.ds.IsNodeDownOrDeleted(r.Spec.NodeID)
> > 		if err != nil || nodeDown {
> > 			continue
> > 		}
> > 		return nil
> > 	}
> > ```
> 
> Will this cause #5340 not fixed? because a new replica will be rebuilt. @derekbit @shuo-wu

@innobead Using the version that adding this logic to skip replica on the down node, I execute the test step as below:
 - premise: 
   - cluster spec: 1 master + 3 worker nodes 
   - os&k8s: v1.25.4+k3s1
   ![image](https://user-images.githubusercontent.com/17548901/222702072-fd8e8a54-245e-47fe-ab22-ea453aec3df8.png)
- steps
1. Restore a 2G backup with 2 replicas: `rep-a`, `rep-b`
2. During the restoring, run the command `service k3s-agent stop` on node containing one of the replica and the node doesn't have the volume engine: `rep-a`
![image](https://user-images.githubusercontent.com/17548901/222705026-c2636d4c-7ac5-4dc2-9b21-9c5461d7f6a1.png)
3. The replica: `rep_a` becomes `stopped` and the `rep_b` keeps restoring 
4. After the `rep_b` accomplish restoring, both two replicas becomes `stopped`
![image](https://user-images.githubusercontent.com/17548901/222705191-7125309b-fe95-4b0f-94ce-ca26e315729a.png)
5. Run the command `service k3s-agent start` to recover the k3s. There is no rebuilding for `rep_a`

**Comment by innobead** [comment]
What's the result after attaching the volume? The first striped one (not restored successfully) should be rebuilt from the healthy one.

**Comment by weizhe0422** [comment]
According to the order of the two steps of attaching the volume and recover the k3s state, there will be two display results:
 1. attaching the volume -> recover the k3s state: The volume will attach successfully, then the replica on the recovered node will start rebuilding. The data is complete and all replicas are running after the replica accomplish rebuilding.
![image](https://user-images.githubusercontent.com/17548901/222747678-45d021a2-3d8c-4469-85e6-924946d983f2.png)
![image](https://user-images.githubusercontent.com/17548901/222748819-057c41fc-be87-495c-971c-71b35302a0d0.png)

 2.  recover the k3s state -> attaching the volume: Both two replicas will become running. I also check the im-r log, it will try to sync the snapshot data. But the current revision counter equals to the latest one, so the replica become running. 
![image](https://user-images.githubusercontent.com/17548901/222758323-1d2492d7-d4be-44d3-acf6-cb54b6c15cfc.png)
 
So I think based on the 2nd case I tested above, IIUC, the result is still the same as the 5340 had been fixed.

**Comment by derekbit** [comment]
Well, after applying the patch, the unknown replica is deleted from the `engine.status.replicaModeMap`. That means the io cannot go to the unknown replica. It breaks the fix in 5340...

**Comment by weizhe0422** [comment]
Sorry, I may have misunderstood something originally.  
I think I should modify it to still add the replica on the abnormal node to the `engine.spec.replicaAddressmap` instead of filtering it out.  
I'll try again and see the revised test results

**Comment by derekbit** [comment]
I'm thinking if the [solution](https://github.com/derekbit/longhorn-manager/commit/66608540abeb1b742c2893cc094f137c6cf1fd63) is reasonable.

When the engine is not in `attached` mode, the replica can be marked as failed if the node is down directly. Except for the `attached` mode, we should not rely on the data plane's connectivity. Right?

**Comment by derekbit** [comment]
> I'm thinking if the [solution](https://github.com/derekbit/longhorn-manager/commit/66608540abeb1b742c2893cc094f137c6cf1fd63) is reasonable or not.
> 
> When the engine is not in `attached` mode, the replica can be marked as failed if the node is down directly. Except for the `attached` mode, we should not rely on the data plane's connectivity status. Does it make sense?

Update: the issue and https://github.com/longhorn/longhorn/issues/5477 are both passed after applying the solution.

@weizhe0422 @shuo-wu @innobead 
Can you help check if there is any concern? Thank you.

**Comment by weizhe0422** [comment]
> > I'm thinking if the [solution](https://github.com/derekbit/longhorn-manager/commit/66608540abeb1b742c2893cc094f137c6cf1fd63) is reasonable or not.
> 
> > 
> 
> > When the engine is not in `attached` mode, the replica can be marked as failed if the node is down directly. Except for the `attached` mode, we should not rely on the data plane's connectivity status. Does it make sense?
> 
> 
> 
> Update: the issue and https://github.com/longhorn/longhorn/issues/5477 are both passed after applying the solution.
> 
> 
> 
> @weizhe0422 @shuo-wu @innobead 
> 
> Can you help check if there is any concern? Thank you.
> 
> 

Is there still a need to check whether the node is abnormal when the replica state is not running?

**Comment by derekbit** [comment]
> > > I'm thinking if the [solution](https://github.com/derekbit/longhorn-manager/commit/66608540abeb1b742c2893cc094f137c6cf1fd63) is reasonable or not.
> > 
> > 
> > > 
> > 
> > 
> > > When the engine is not in `attached` mode, the replica can be marked as failed if the node is down directly. Except for the `attached` mode, we should not rely on the data plane's connectivity status. Does it make sense?
> > 
> > 
> > Update: the issue and #5477 are both passed after applying the solution.
> > @weizhe0422 @shuo-wu @innobead
> > Can you help check if there is any concern? Thank you.
> 
> I wanted to ask additionally if it is still necessary to check if the replica's node is abnormal when its status is not running?

The node down is detected [here](https://github.com/derekbit/longhorn-manager/commit/66608540abeb1b742c2893cc094f137c6cf1fd63#diff-3238708d588203a9b8f1360b6d4b391c0c7a628fb1b2fac36efbbafe930f5e79R1572) .

**Comment by innobead** [comment]
> > I'm thinking if the [solution](https://github.com/derekbit/longhorn-manager/commit/66608540abeb1b742c2893cc094f137c6cf1fd63) is reasonable or not.
> > When the engine is not in `attached` mode, the replica can be marked as failed if the node is down directly. Except for the `attached` mode, we should not rely on the data plane's connectivity status. Does it make sense?
> 
> Update: the issue and #5477 are both passed after applying the solution.
> 
> @weizhe0422 @shuo-wu @innobead Can you help check if there is any concern? Thank you.

No major concerns, but just one thought https://github.com/derekbit/longhorn-manager/commit/66608540abeb1b742c2893cc094f137c6cf1fd63#r103112369

**Comment by shuo-wu** [comment]
Actually, I am considering [case 1 mentioned in this ticket](https://github.com/longhorn/longhorn/issues/5476#issuecomment-1453010590): Will marking an unknown replica as Failed during detaching will lead to the data loss?

**Comment by derekbit** [comment]
> Actually, I am considering [case 1 mentioned in this ticket](https://github.com/longhorn/longhorn/issues/5476#issuecomment-1453010590): Will marking an unknown replica as Failed during detaching will lead to the data loss?

Do you mean previous implementation?

**Comment by shuo-wu** [comment]
No. I mean, after applying the PR you created for this ticket, the replica on the down node will be marked as failed then get deleted during detaching/reattaching. Will this be a risk?

**Comment by shuo-wu** [comment]
And there are serval extra questions before the fix:
1. If the node is really down and it's not the attached node, why won't the engine process mark the replica as mode ERR?
2. After stopping a node for a long time, the instance manager pods on the node will be evicted (IIRC the timeout is 5 min), will this lead to a replica state change?
3. Not the main issue of this unknown replica is, it blocks the restoration completion, right? For other cases, does it work fine? For example, does reattaching a regular volume that contains unknown replicas work? If YES, then can we fix this issue by introducing a timeout setting/option rather than changing the replica lifecycle to avoid restoring volume infinite wait?

**Comment by derekbit** [comment]
> If the node is really down and it's not the attached node, why won't the engine process mark the replica as mode ERR?

Do you mean letting engine mark the replica as mode ERR rather than setting faileAt here?

> No. I mean, after applying the PR you created for this ticket, the replica on the down node will be marked as failed then get deleted during detaching/reattaching. Will this be a risk?

Is it a concern in v1.3.2 as well? https://github.com/longhorn/longhorn-manager/blob/v1.3.2/controller/volume_controller.go

**Comment by weizhe0422** [comment]
I tried to use `longhornio/longhorn-manager:v1.4.x-head` to execute test steps as [here](https://github.com/longhorn/longhorn/issues/5464#issuecomment-1453368556)

 - I stopped the `k3s-agent` on the node that volume want to attached. And the replica is failed but the other replica keeps restoring.
![image](https://user-images.githubusercontent.com/17548901/223026759-c85bf5d8-1034-4602-935c-401f22db4e70.png)
![image](https://user-images.githubusercontent.com/17548901/223026922-8b329aaf-e4f3-48dc-b0aa-f2b86ceec4ec.png)

 - After one of the replica finish restoring, I recover the `k3s-agent` and re-attach the volume. I found the replica will start to rebuilding. 
![image](https://user-images.githubusercontent.com/17548901/223029572-950001cc-ee95-4c6c-9a1f-9fd61777ad95.png)
![image](https://user-images.githubusercontent.com/17548901/223029797-d58160de-1244-4080-8b23-53cf1390897a.png)

**Comment by derekbit** [comment]
> If the node is really down and it's not the attached node, why won't the engine process mark the replica as mode ERR?

In this case, engine process marks the replica as mode ERR, and it's later deleted as you mentioned.

**Comment by chriscchien** [comment]
Verified in longhorn-manager master `bb6dd1` with test [steps](https://github.com/longhorn/longhorn/issues/5464#issue-1606073056)
Result **Pass**

- When volume is restoring, shut down node which volume attached to, volume will attach to another node and restore success. 
- Can see replica located on shut down node have value recorded in field `spec.failedAt`. (in v1.4.1-rc1, this field was empty)
- In the UI, that replica displayed as Failed as well

**Comment by derekbit** [comment]
> After stopping a node for a long time, the instance manager pods on the node will be evicted (IIRC the timeout is 5 min), will this lead to a replica state change?

@shuo-wu For `stopping a node`, do you mean `stop it network`, `power down the node` or `stop the kubelet`?

**Comment by innobead** [comment]
> > No. I mean, after applying the PR you created for this ticket, the replica on the down node will be marked as failed then get deleted during detaching/reattaching. Will this be a risk?
> 
> Is it a concern in v1.3.2 as well? https://github.com/longhorn/longhorn-manager/blob/v1.3.2/controller/volume_controller.go#L1490

The new change is actually a more granular case if compared with the previous implementation, which will just mark the replica as failed and then stop it, but the new change will just mark the replica as failed only if the volume is obviously detached. Also, the failed replica should be reused for rebuilding, so everything should go healthy after volume reattachment.
 
If the volume is detached, also there are no ways to rely on the engine to determine the unknown replica failed, because there is no frontend anymore. Just directly marking it as failed seems reasonable to me. 

@shuo-wu @derekbit @weizhe0422 thoughts?

**Comment by shuo-wu** [comment]
My concern is: when the node is unknown (like kubelet down/network disconnection) but the workload & engine & replica are still storing new data, should we mark the replica as Failed rather than how can the replica be marked as Failed? At that moment, I am thinking if we could clean up the unknown replica when it really blocks the attachment. In brief, marking it as Failed then deleting it during attachment.

Then I just had a discussion with Derek. He mentioned that the cluster is messy when there are this kind of nodes then emphasizing data integrity at that moment may be meaningless. But with my idea, the risk of attachment flow would increase. We have to do a trade-off. Relying on the existing fix is good enough.
