### ISSUE TITLE
[BUG] Unable to create support bundle agent pod in air-gap environment

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#5467]
## Describe the bug (🐛 if you encounter this issue)

Install Longhorn `master-head` or `v1.4.x-head` in an air-gap environment (pull all required images from a private docker registry), Longhorn can be installed without error, but when try to generate support bundle, it stuck at progress 40%, and support bundle agent pod stuck in `ImagePullBackOff`:
```
longhorn-support-bundle-manager-support-bundle-2023-03-02t49b6k   1/1     Running            0          54m
backing-image-manager-7978-b7eb                                   1/1     Running            0          48m
share-manager-pvc-9bd22e50-8dd2-4da8-af40-14eab8a2d13b            1/1     Running            0          47m
supportbundle-agent-support-bundle-2023-03-02t04-54-22z-xntbt     0/1     ImagePullBackOff   0          54m
supportbundle-agent-support-bundle-2023-03-02t04-54-22z-b6pfv     0/1     ImagePullBackOff   0          54m
supportbundle-agent-support-bundle-2023-03-02t04-54-22z-st7n8     0/1     ImagePullBackOff   0          54m
supportbundle-agent-support-bundle-2023-03-02t04-54-22z-fgm9s     0/1     ImagePullBackOff   0          54m
```
with error: 
```
Failed to pull image "lh-registry-oqfa6kxs.ci-qa.rancher.space/longhornio/support-bundle-kit:v0.0.17": 
rpc error: code = Unknown 
desc = failed to pull and unpack image "lh-registry-oqfa6kxs.ci-qa.rancher.space/longhornio/support-bundle-kit:v0.0.17": 
failed to resolve reference "lh-registry-oqfa6kxs.ci-qa.rancher.space/longhornio/support-bundle-kit:v0.0.17": 
pulling from host lh-registry-oqfa6kxs.ci-qa.rancher.space failed with status code [manifests v0.0.17]: 
401 Unauthorized
```
but `share-manager` or `backing-image-manager` doesn't have this issue:
```
$ kubectl describe pod backing-image-manager-7978-b7eb -n longhorn-system
Events:
  Type    Reason   Age   From     Message
  ----    ------   ----  ----     -------
  Normal  Pulling  49m   kubelet  Pulling image "lh-registry-oqfa6kxs.ci-qa.rancher.space/longhornio/backing-image-manager:master-head"
  Normal  Pulled   49m   kubelet  Successfully pulled image "lh-registry-oqfa6kxs.ci-qa.rancher.space/longhornio/backing-image-manager:master-head" in 3.855532356s
  Normal  Created  49m   kubelet  Created container backing-image-manager
  Normal  Started  49m   kubelet  Started container backing-image-manager

$ kubectl describe pod share-manager-pvc-9bd22e50-8dd2-4da8-af40-14eab8a2d13b -n longhorn-system
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  48m   default-scheduler  Successfully assigned longhorn-system/share-manager-pvc-9bd22e50-8dd2-4da8-af40-14eab8a2d13b to ip-10-0-1-88
  Normal  Pulling    48m   kubelet            Pulling image "lh-registry-oqfa6kxs.ci-qa.rancher.space/longhornio/longhorn-share-manager:master-head"
  Normal  Pulled     48m   kubelet            Successfully pulled image "lh-registry-oqfa6kxs.ci-qa.rancher.space/longhornio/longhorn-share-manager:master-head" in 3.808941487s
  Normal  Created    48m   kubelet            Created container share-manager
  Normal  Started    48m   kubelet            Started container share-manager
```
and `support-bundle-kit:v0.0.17` exists in the private docker registry for sure:
```
$ docker pull lh-registry-oqfa6kxs.ci-qa.rancher.space/longhornio/support-bundle-kit:v0.0.17
v0.0.17: Pulling from longhornio/support-bundle-kit
3ff3c85f9ea7: Already exists 
9d3289b587ca: Pull complete 
7220c0dd31c6: Pull complete 
9adc021abc80: Pull complete 
4d2e585c6540: Pull complete 
8b3bd2bf5b73: Pull complete 
c8b21374118b: Pull complete 
feaa2287e1d4: Pull complete 
Digest: sha256:4bd76b1e0f1180d34d2ba73f211d1e6bff362e2c28585f0cb3b8aaae80e1327a
Status: Downloaded newer image for lh-registry-oqfa6kxs.ci-qa.rancher.space/longhornio/support-bundle-kit:v0.0.17
lh-registry-oqfa6kxs.ci-qa.rancher.space/longhornio/support-bundle-kit:v0.0.17
```

## To Reproduce

Install Longhorn in an air-gap environment, and generate support bundle.
It can be run automatically in jenkins like https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3058/parameters/

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
I thought we already respect the registry's secret. @c3y1huang Could you help check this? Thanks.

**Comment by c3y1huang** [comment]
This is a day 1 issue. The support bundle agent DaemonSet is created by the support bundle manager. So we also need to fix this on our side and also upstream to have the support bundle manager feed in the registry secret when DaemonSet gets created.

**Comment by c3y1huang** [comment]
@yangchiu can you help to mirror [rancher/support-bundle-kit:v0.0.19](https://hub.docker.com/layers/rancher/support-bundle-kit/v0.0.19/images/sha256-23bab65abd0ec9d8a4534bb9674555117896017568adc49f5b6a832174887b8c?context=explore) to `longhornio`. Thanks!

**Comment by c3y1huang** [comment]
Test result: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3077/

**Comment by yangchiu** [comment]
[manifest](https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml) of master-head (longhorn 5a3f8d7) can pass air-gap test pipeline without errors.
