### ISSUE TITLE
[IMPROVEMENT] deploy: driver deployer shouldn't cleanup previous deployment if Kubernetes version changes 

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#5474]
During Kubernetes upgrade, if the driver deployer restarts the csi deployments when the Kubernetes version changes, Kubernetes might not be able to detach the Longhorn volumes thus blocking the drain flow.

Suggesting to not restart the csi deployments when the Kubernetes version changes. 

This is the revert of https://github.com/longhorn/longhorn/issues/426. We no longer support the Kubernetes versions in that ticket. Also, when the Kubernetes version changes such that it uses a new CSI spec, most likely that we will deploy new CSI deployment images so this will force the csi deployments' restarts anyways.

**Comment by PhanLe1010** [comment]
Test plan:

Case 1:

1. Deploy Longhorn master-head
1. Upgrade Kubernetes
1. Crash longhorn-driver-deployer pod
1. Observer that the longhorn-driver-deployer does NOT clean up and redeploy csi-attacher/csi-provisioner/csi-resizer/csi-snapshotter/longhorn-csi-plugin/Longhorn csidrivers object.

Case 2:
1. Install Longhorn v1.5.3
1. Upgrade Longhorn to master-head
1. Observer that the longhorn-driver-deployer DOES clean up and redeploy csi-attacher/csi-provisioner/csi-resizer/csi-snapshotter/longhorn-csi-plugin/Longhorn csidrivers object.
1. Upgrade Kubernetes
1. Crash longhorn-driver-deployer pod
1. Observer that the longhorn-driver-deployer does NOT clean up and redeploy csi-attacher/csi-provisioner/csi-resizer/csi-snapshotter/longhorn-csi-plugin/Longhorn csidrivers object.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `856745`)

I can reproduce the csi deployments restart  when the Kubernetes version changes behavior on v1.5.3, but not on master head with test [steps](https://github.com/longhorn/longhorn/issues/5474#issuecomment-1857328816)
