### ISSUE TITLE
[BUG] [v1.4.1-rc1] Physical node down test failed

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#5477]
## Describe the bug (🐛 if you encounter this issue)

From https://longhorn.github.io/longhorn-tests/manual/pre-release/node/physical-node-down/

Set `node-down-pod-deletion-policy` = `delete-deployment-pod` and create deployment using PVC of 3 replicas volume, shutdown the node which pod attached to, the replaced pod will stuck at `ContainerCreating` status forever

Not see in v1.4.0

## To Reproduce

1. Deploy longhorn with 3 replicas
2. Set `node-down-pod-deletion-policy` = `delete-deployment-pod`
3. Create volume with 3 replicas then create PV and PVC of this volume
4. Create a deployment using the volume PVC
5. After pod running, shutdown the node which node attached to
6. Old pod terminated success but replaced pod stuck at `ContainerCreating`
7. And the volume stuck at `attaching` also

## Expected behavior

Volume attach to new node success and new pod running

## Log or Support bundle

[supportbundle_ec3950cf-3204-4890-b25e-3b073d005377_2023-03-03T04-08-28Z.zip](https://github.com/longhorn/longhorn/files/10878098/supportbundle_ec3950cf-3204-4890-b25e-3b073d005377_2023-03-03T04-08-28Z.zip)

## Environment

 - Longhorn version: v1.4.1-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:  v1.24.7+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 1

## Additional context

If the volume have **2** replicas which was the test [step](https://longhorn.github.io/longhorn-tests/manual/pre-release/node/physical-node-down/) in test case
- No replica located on shutdown node, the replaced pod will create success
- 1 replica located on shutdown node, the replaced pod will stuck at `ContainerCreating` and volume stuck at `attaching`

**Comment by innobead** [comment]
This should be duplicated at https://github.com/longhorn/longhorn/issues/5464. 

cc @weizhe0422 @longhorn/dev-data-plane

**Comment by chriscchien** [comment]
Verified in longhorn manager v1.4.x head `33359f` with test [steps](https://github.com/longhorn/longhorn/issues/5477#issue-1607924098)
Result **Pass**

After https://github.com/longhorn/longhorn-manager/pull/1737 merged,  set setting `node-down-pod-deletion-policy` = `delete-deployment-pod` then shutdown node which deployment pod attached to,  there will be a replaced pod running and volume will attach to another node success
