### ISSUE TITLE
[BUG] Backing image with sync failure

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#5481]
## Describe the bug (🐛 if you encounter this issue)

In [Backing image with sync failure](https://longhorn.github.io/longhorn-tests/manual/pre-release/ha/backing-image-error-reporting-and-retry/) , the desired behavior is: 

**into the host of a worker node. remove the content of the backing image work directory then set the directory as immutable.** 
**This operation should fail one file of the backing image as well as keeping failing the following sync retries.**

```
rm /var/lib/longhorn/backing-images/<backing image name>-<backing image UUID>/backing*
chattr +i /var/lib/longhorn/backing-images/<backing image name>-<backing image UUID>/
```

**Monitor the backing image manager pod log. Verify the backoff works for the sync retry as well**

After setting the directory as immutable, the backing-image-manager log indicates that the "Closing ssync server" and there are no sync retries.
This case was added in version `v1.2.0` and I have been verified in versions `v1.2.0`, `v1.2.4`, `v1.2.6`, `v1.3.1`, `v1.3.2`, and `v1.4.0` again. However, only versions `v1.2.0` and `v1.2.4` exhibited the expected behavior. 

It is necessary to confirm whether this change in behavior is intentional.

## To Reproduce

manually execute [Backing Image Error Reporting and Retry](https://longhorn.github.io/longhorn-tests/manual/pre-release/ha/backing-image-error-reporting-and-retry/) case `Backing image with sync failure`

## Log or Support bundle

[supportbundle_15a1a874-b08c-412d-bb79-e1e3f6f9d734_2023-03-03T07-38-43Z.zip](https://github.com/longhorn/longhorn/files/10879327/supportbundle_15a1a874-b08c-412d-bb79-e1e3f6f9d734_2023-03-03T07-38-43Z.zip)

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
cc @ChanYiLin @shuo-wu
