### ISSUE TITLE
[BUG] Example of data migration doesn't work for hidden/./dot-files)

### ISSUE THREAD

**Issue by hedefalk** [longhorn/longhorn#5484]
Used this without looking too deeply for migrating a home-assistant storage to longhorn. The db was under ".storage" which wasn't copied over:

https://github.com/longhorn/longhorn/blob/5a3f8d714bc135dfe06fee6e3f09075906dba3ea/examples/data_migration.yaml#L22

changing to

    args: [ "-c", "cp -r -v /mnt/old/. /mnt/new" ]

made my case work.

**Comment by shuo-wu** [comment]
Yes you are right! `cp ./*` ignores dot files and dot directory.

**Comment by shuo-wu** [comment]
Can you create a PR to repo `longhorn/longhorn` as well? The current PR is pointing to your private forked repo.

**Comment by hedefalk** [comment]
> The current PR is pointing to your private forked repo

Whoopsie

**Comment by innobead** [comment]
@chriscchien it seems the backport issues are unable to create for the external contributor, so please just verify together with other versions together here before closing this. Thanks. 

cc @longhorn/qa

**Comment by chriscchien** [comment]
Verified on longhorn master `cb6307`, v1.4.x `662fbb` and v1.3.x `39ce8a`
Result **Pass**

Steps:
1. Deploy specific version of Longhorn
2. Create 2 PVC `longhorn-volv-pvc`, `longhorn-volv-pvc2` with storage class `longhorn`
3. Create a deployment with  PVC `longhorn-volv-pvc`,  in the mount point create dot file and dot folder, write data to them. Scale down deployment to 0 after write complete.
4. Modify specific version of [data_migration.yaml](https://github.com/longhorn/longhorn/blob/master/examples/data_migration.yaml), change `data-source-pvc` to `longhorn-volv-pvc`, `data-target-pvc` to `longhorn-volv-pvc2`
5. Run the modified `data_migration.yaml` and wait until job `volume-migration` complete.
6. Use another deployment with PVC `longhorn-volv-pvc2`, can see all data transferred into this PVC, including dot files and dot folder.

**Comment by innobead** [comment]
Thanks @chriscchien :+1:
