### ISSUE TITLE
[BUG] test case test_dr_volume_with_backup_block_deletion failed

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#5489]
## Describe the bug (🐛 if you encounter this issue)

Test cases related to delete the backup associated to a DR volume will fail in both `master` and `v1.4.x`:
`test_dr_volume_with_backup_block_deletion`
`test_dr_volume_with_backup_block_deletion_abort_during_backup_in_progress`
`test_dr_volume_with_all_backup_blocks_deleted`
https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/419/

due to fail to delete the backup:
```
time="2023-03-06T03:30:40Z" level=warning msg="Unable to delete remote backup" 
backup=backup-f86c61b1167149bb 
controller=longhorn-backup 
error="backup backup-f86c61b1167149bb cannot be deleted due to the ongoing volume dr-longhorn-testvol-qt848e restoration" node=ip-10-0-1-37
```
Not sure if behavior changed and the test cases need to be refine.

## To Reproduce

Run test case `test_dr_volume_with_backup_block_deletion`

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
This should be related to https://github.com/longhorn/longhorn-manager/pull/1735.

**Comment by derekbit** [comment]
Already fixed in https://github.com/longhorn/longhorn/issues/5458

**Comment by yangchiu** [comment]
Affected test cases passed in master-head (longhorn-manager bb6dd1a): https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3113/
