### ISSUE TITLE
[BUG] test case test_inc_restoration_with_multiple_rebuild_and_expansion randomly failed

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#5496]
## Describe the bug (🐛 if you encounter this issue)

Test case `test_inc_restoration_with_multiple_rebuild_and_expansion` will randomly fail in both `master` and `v1.4.x` with reproducibility ~ 1/30

In step 16 of this test case:
```
# Step 16:
# Trigger the restoration for the DR volume.
# Then re-verify the snapshot info
```
It expects the DR volume only has **2** snapshots:
```
assert len(snapshots) == 2
```
But sometimes it actually has **3** snapshots in the first place:
```
{
	'data': [{
		'checksum': '',
		'children': {},
		'created': '2023-03-06T07:27:44Z',
		'labels': {},
		'name': 'volume-head',
		'parent': 'expand-3221225472',
		'removed': False,
		'size': '0',
		'usercreated': False
	}, {
		'checksum': '',
		'children': {
			'volume-head': True
		},
		'created': '2023-03-06T07:27:44Z',
		'labels': {
			'replica-expansion': '3221225472'
		},
		'name': 'expand-3221225472',
		'parent': 'expand-2147483648',
		'removed': False,
		'size': '0',
		'usercreated': False
	}, {
		'checksum': '',
		'children': {
			'expand-3221225472': True
		},
		'created': '2023-03-06T07:25:39Z',
		'labels': {
			'replica-expansion': '2147483648'
		},
		'name': 'expand-2147483648',
		'parent': '',
		'removed': True,
		'size': '1759551488',
		'usercreated': False
	}],
	'resourceType': 'snapshot'
}
```
And then wait for 1 second and fetch snapshots info again, we can get **2** snapshots:
```
{
	'data': [{
		'checksum': '',
		'children': {},
		'created': '2023-03-06T07:27:44Z',
		'labels': {},
		'name': 'volume-head',
		'parent': 'expand-3221225472',
		'removed': False,
		'size': '0',
		'usercreated': False
	}, {
		'checksum': '',
		'children': {
			'volume-head': True
		},
		'created': '2023-03-06T07:27:44Z',
		'labels': {
			'replica-expansion': '3221225472'
		},
		'name': 'expand-3221225472',
		'parent': '',
		'removed': True,
		'size': '1759551488',
		'usercreated': False
	}],
	'resourceType': 'snapshot'
}
```

Not sure this transient state is expected or not, but it fails the test case for sure.

## To Reproduce

Run test case `test_inc_restoration_with_multiple_rebuild_and_expansion` with `--count 30`

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by mantissahz** [comment]
IMO it is a timing issue, the backend does not complete deleting old snapshot, when the new restored snapshot is completed.
Modified test case to wait for the snapshot counts of DR volume to be expected.

**Comment by yangchiu** [comment]
Just curious. Where does this extra snapshot come from? Why does it be created and removed automatically? Just wondering what happened under the hood and caused this unexpected outcome. But many thanks for fixing this flaky test case!

**Comment by mantissahz** [comment]
> Where does this extra snapshot come from? Why does it be created and removed automatically? Just wondering what happened under the hood and caused this unexpected outcome

DR volume synchronized procedure is a restoration and as I mentioned, when controller starts to synchronize DR volume, it pulls the backup as a snapshot created by the system and it will be merged with the previous snapshot that previous restoration used.
At merge stage, it might have previous restoration snapshot, the restoration snapshot for this time and a volume-head snapshot. Then you got three snapshots not expected two (volume-head and a snapshot for the restoration this time) and wait couple seconds you might get the right the snapshot count

**Comment by yangchiu** [comment]
Test case `test_inc_restoration_with_multiple_rebuild_and_expansion` doesn't fail for this reason anymore. The current failure probably is related to https://github.com/longhorn/longhorn/issues/6089
