### ISSUE TITLE
[TEST] Create a test suit to cover Rancher Longhorn integration

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#5505]
## What's the test to develop? Please describe

We need to have a test plan which covers the Rancher Longhorn integration area. Currently we have test plan for basic installation, upgrade and airgap with Rancher. We want to cover more areas which are frequently used by customers.

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] Come up with the plan as in what functionalities/areas need to be included in the test.
- [ ] Add the detailed test cases in our manual and automation test suit.

## Additional context

To start with some of the possible areas that need to be cover in the test suit :

- air-gap (we have now)
- chart install & upgrade (we have now)
- drain operation for the local/downstream cluster via Rancher or SUC
- drain operation with K3s SUC
- Rancher proxy access to longhorn UI

**Comment by innobead** [comment]
The main point is **_we should have the corresponding test suite for the integration, especially cluster node maintenance/upgrade (longhorn itself and together with K8s) through valid interfaces like Rancher UI, SUC, fleet, etc._**

**Comment by innobead** [comment]
@chriscchien will also help with verifying all test case combinations based on the PR.

cc @longhorn/qa

**Comment by khushboo-rancher** [comment]
Test cases have been added - https://longhorn.github.io/longhorn-tests/manual/rancher-integration/
