### ISSUE TITLE
[BUG] Bulk backup deletion cause restoring volume to finish with attached state.

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#5506]
## Describe the bug (🐛 if you encounter this issue)

During volume restoration, bulk backup deletion by click `Delete All Backups` in UI will make volume to finished in attached state and `Ready for workload` = `Not Ready` 

## To Reproduce

1. Create volume, write data and create backup
2. Restore backup to volume
3. Click `Delete All Backups` while volume restoration in progress
4. Backup deleted soon, volume to finished in attached state and `Ready for workload` = `Not Ready` 

## Expected behavior

Backup deleted after restoration complete, volume in detached state.

## Log or Support bundle

https://github.com/longhorn/longhorn/issues/1867#issuecomment-1458220849

## Environment

 - Longhorn version: longhorn master head `5a3f8d`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:  v1.24.7+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 1

## Additional context

Related to https://github.com/longhorn/longhorn/issues/1867

**Comment by innobead** [comment]
@chriscchien I changed the severity to 3, because the restoring seems working but the issue is it will not be automatically detached at the end, correct?

cc @longhorn/qa

**Comment by chriscchien** [comment]
> @chriscchien I changed the severity to 3, because the restoring seems working but the issue is it will not be automatically detached at the end, correct?
> 
> cc @longhorn/qa

Yes the volume kept in attached and robustness = healthy after restoring.

**Comment by roger-ryao** [comment]
**Verified on master-head 20230515**

- longhorn master-head ([17ce9ec](https://github.com/longhorn/longhorn/commit/17ce9ec4452e2ccef4f91749ac449088411691a5))
- longhorn-manager master-head ([0ac0cc9](https://github.com/longhorn/longhorn-manager/commit/0ac0cc9931260b52a0cbe3c16040276a694012ac))

**The test steps**

https://github.com/longhorn/longhorn/issues/5506#issuecomment-1535992838

**Result Passed**

1. BackupVolume will not be deleted immediately. It will only be deleted after the restoration is complete.
![Screenshot_20230515_141359](https://github.com/longhorn/longhorn/assets/104337648/3d85caf4-991a-41c1-9f9b-3f2bdd68d366)
