### ISSUE TITLE
[IMPROVEMENT] Unify logs with extra static info like module/method/function/line

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5509]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Currently, in longhorn components' logs, there is no module, function, or line info to quickly identify the code. Usually, we will rely on the message to look up the potential code place. It's better to have logs with that info for troubleshooting purposes.

## Describe the solution you'd like

Can leverage `CallerPrettyfier` to achieve the goal, and apply to all components and libraries. 

```go
package log
import (
 "fmt"
 "runtime"
 "strings"
"github.com/sirupsen/logrus"
)
func init() {
 logrus.SetReportCaller(true)
 formatter := &logrus.TextFormatter{
  TimestampFormat:        "02-01-2006 15:04:05", // the "time" field configuratiom
  FullTimestamp:          true, 
  DisableLevelTruncation: true, // log level field configuration
  CallerPrettyfier: func(f *runtime.Frame) (string, string) { 
   return "", fmt.Sprintf("%s:%d", formatFilePath(f.File), f.Line)
  },
 }
 logrus.SetFormatter(formatter)
}
func formatFilePath(path string) string {
 arr := strings.Split(path, "/")
 return arr[len(arr)-1]
}
```

## Additional context

N/A

**Comment by innobead** [comment]
@ChanYiLin let's apply this to all components.

**Comment by roger-ryao** [comment]
**Verified on master-head 20231024**

- longhorn master-head https://github.com/longhorn/longhorn/commit/febfa7eef72076b3e41808d327f8e8b4d4276a57
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/5e0868b84aca3cc601ad00cc0e37f8bf01d3efd6

**The test steps**

https://github.com/longhorn/longhorn/issues/5509#issuecomment-1770327057


**Result Passed**

- [x] We can see that there are two additional fields in the log: `func`, `file`

![Screenshot_20231024_113633](https://github.com/longhorn/longhorn/assets/104337648/b71e8514-9890-43ed-a423-153392666359)
