### ISSUE TITLE
[BUG] Volume is not healthy, but reports that it is healthy

### ISSUE THREAD

**Issue by withinboredom** [longhorn/longhorn#5514]
## Describe the bug (🐛 if you encounter this issue)

![image](https://user-images.githubusercontent.com/1883296/223863362-1a4f632d-11bb-48b3-b515-154c0bbaff6c.png)

![image](https://user-images.githubusercontent.com/1883296/223863443-2d46c239-0aac-4b5c-ae43-ce405992e105.png)

## To Reproduce

1. Go to a datacenter
2. Open a rack
3. Trip while backing away from rack
1. Pull random optics/fibers out of servers in hopes to prevent yourself from falling?

## Expected behavior

A volume to report unhealthy when it isn't healthy

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.4.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 1-5
 - Node config
   - OS type and version: Ubuntu 22.04
   - CPU per node: at least 12
   - Memory per node: at least 32
   - Disk type(e.g. SSD/NVMe): nvme/ssd
   - Network bandwidth between the nodes: 1g
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal
 - Number of Longhorn volumes in the cluster: 16

## Additional context

Do not recommend reproducing.

**Comment by shuo-wu** [comment]
`Healthy` typically means that the **running replicas count** of a volume satisfies the requirement. 
Here the warning/error message means that Longhorn cannot launch a local replica for this volume hence the data locality requirement is not satisfied.
