### ISSUE TITLE
[TASK][UI] add new recurring job task - filesystem trim

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#5529]
## What's the task? Please describe

Introducing 1 new recurring job task type:
- filesystem-trim

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] Support `filesystem-trim` in UI.

## Additional context

- https://github.com/longhorn/longhorn/pull/5520
- https://github.com/longhorn/longhorn/issues/5186

**Comment by c3y1huang** [comment]
cc @smallteeths

**Comment by chriscchien** [comment]
Verified **pass** in longhorn master (longhorn-manager `023dd3`, longhorn-ui `5219e4`)

This ticket verified in https://github.com/longhorn/longhorn/issues/5186#issuecomment-1567700522, thank you
