### ISSUE TITLE
[TEST] Update CLI steps for verifying backing image sync failure test case

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#5539]
## What's the test to develop? Please describe

After `v1.4.1` release test `Backing Image Error Reporting and Retry`, the current steps lack clear CLI commands for verifying the sync retries and re-sync completion. I need to update [backing-image-error-reporting-and-retry](https://longhorn.github.io/longhorn-tests/manual/pre-release/ha/backing-image-error-reporting-and-retry/) test case and make it clear enough

## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] `update case. Get it reviewed.`

## Additional context

https://github.com/longhorn/longhorn/issues/5481
https://longhorn.github.io/longhorn-tests/manual/pre-release/ha/backing-image-error-reporting-and-retry/

**Comment by innobead** [comment]
@ChanYiLin please help review this.

**Comment by roger-ryao** [comment]
PR : https://github.com/longhorn/longhorn-tests/pull/1284

**Comment by roger-ryao** [comment]
Ticket closed as the https://github.com/longhorn/longhorn-tests/pull/1284 has been merged.
