### ISSUE TITLE
[BUG] Directly mark replica as failed if the node is deleted

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5542]
## Describe the bug (🐛 if you encounter this issue)

After deleting a node, vc.canInstanceManagerLaunchReplica ([code](https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go)) reports that the node is down and unable to launch a replica. However, the fix implemented in https://github.com/longhorn/longhorn/issues/5508 prevents the replica from being marked as failed.

To improve the handling of this situation, we should distinguish between two cases: node not found and node ready. For the node not found case, we can directly mark the replica as failed.

## To Reproduce

3. Perform '....'

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

https://github.com/longhorn/longhorn-tests/pull/1279
https://github.com/longhorn/longhorn-tests/pull/1279#issuecomment-1479004050

**Comment by weizhe0422** [comment]
Steps that I tried to reproduce:
 1. Having an attached volume w/ one replica
 2. Stop the VM that the volume attached and then delete it with `kubectl delete nodes.longhorn.io <node-name> -n longhorn-system` 
 3. In v1.4.1, both volume health status and replica status are `Unknown`.
![image](https://user-images.githubusercontent.com/17548901/225258074-2c39a031-b940-482c-b653-11f5a8e2920a.png)
![image](https://user-images.githubusercontent.com/17548901/225264531-00851e12-5389-4575-9846-188245941428.png)

**Comment by derekbit** [comment]
> @derekbit Is this issue only for one volume and one replica on the same node, correct? If yes, we need to make the description and title clear. That will be helpful to know the exact context.

No, not just for the single node case. I updated the title for clarification.

**Comment by roger-ryao** [comment]
**Verified on master-head 20230516**

- longhorn master-head ([7680931](https://github.com/longhorn/longhorn/commit/7680931f883845d0d3b517ee82a6292281d4932d))
- longhorn-manager master-head ([cd31ec6](https://github.com/longhorn/longhorn-manager/commit/cd31ec6e46ae76e56758382503d2ef5082f93ba1))


**The test steps**

https://github.com/longhorn/longhorn/issues/5542#issuecomment-1512334557


**Result Passed**

1. After deleting a node, the expected result for Scenario 1 and Scenario 2 can be verified by running the command `kubectl -n longhorn-system get replica -o json | jq -r '.items[] | {name: .metadata.name, failedAt: .spec.failedAt}'`. It has been confirmed that this issue has been resolved.

Scenario 1
![Screenshot_20230516_133430](https://github.com/longhorn/longhorn/assets/104337648/cb051a58-2db2-4dfa-8948-2ff79cdc5814)

Scenario 2

![Screenshot_20230516_142854](https://github.com/longhorn/longhorn/assets/104337648/7a0612df-b4db-43ea-91aa-2a1116d6e9a5)

![Screenshot_20230516_142836](https://github.com/longhorn/longhorn/assets/104337648/f14eb0c8-c1f9-4f63-ba9f-9ca48e0f8109)

**Comment by chriscchien** [comment]
Do we need also update our manual test [case](https://github.com/longhorn/longhorn-tests/blob/master/docs/content/manual/pre-release/node-not-ready/node-down/node-deletion.md) regarding this ticket?

cc @longhorn/qa
