### ISSUE TITLE
[BUG] cannot mount NFSv4 after update from master-head to v1.4.1

### ISSUE THREAD

**Issue by Razorbob** [longhorn/longhorn#5548]
## Describe the bug (🐛 if you encounter this issue)
![image](https://user-images.githubusercontent.com/8940098/224715606-1e9b76b6-2a3b-48e6-b71d-c5c201d60ad4.png)

I have a HA cluster running 2 Master 5 Worker.
I upgraded from longhorn-engine:master-head to longhorn-engine:v1.4.1 

After the upgrade I did the usual "Engine Upgrade" on the Volumes
than I saw some Volumes are stuck in either 
![image](https://user-images.githubusercontent.com/8940098/224716737-57990803-6aa5-4c1f-93f5-8024ce622e4e.png)
or
![image](https://user-images.githubusercontent.com/8940098/224716797-124a61c3-e297-48d0-a658-348d6757ea4c.png)

So I wanted to try and restore a Backup and there I saw the error message above

## Expected behavior

See and create Backups

## Log or Support bundle

[supportbundle_cf330071-3915-4950-a919-2a9294554885_2023-03-13T13-51-15Z.zip](https://github.com/longhorn/longhorn/files/10958148/supportbundle_cf330071-3915-4950-a919-2a9294554885_2023-03-13T13-51-15Z.zip)

## Environment

 - Longhorn version:
 1.4.1
 - Installation method (e.g. Rancher C
[supportbundle_cf330071-3915-4950-a919-2a9294554885_2023-03-13T13-51-15Z.zip](https://github.com/longhorn/longhorn/files/10958120/supportbundle_cf330071-3915-4950-a919-2a9294554885_2023-03-13T13-51-15Z.zip)
atalog App/Helm/Kubectl):
Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
 K8s with kubeadm - all 1.24.0
   - Number of management node in the cluster:
   2
   - Number of worker node in the cluster:
   5
 - Node config
   - OS type and version:
   Ubuntu 22.04 and Ubuntu 20.04
   - CPU per node:
   ~20-40 depends on the nodes
   - Memory per node:
   ~ 300GB
  - Disk type(e.g. SSD/NVMe):
   HDD over SAN
   - Network bandwidth between the nodes:
   ~4-10G

 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 Baremetal
 - Number of Longhorn volumes in the cluster:
14
## Additional context

I updated the control plane yesterday from 1.23.X to 1.24.0 and had some troubles, because I switched from Docker to containerd.

**Comment by derekbit** [comment]
> I upgraded from longhorn-engine:master-head to longhorn-engine:v1.4.1

Is your previous longhorn-engine version `master-head`?
`master-head` is for development. We cannot guarantee downgrade from master-head to v1.4.1 if safe.

For the backup error, you can mount the remote nfs folder in the longhorn-manager pod and check if it works.

**Comment by derekbit** [comment]
Can you check both server and client sides support NFSv4.0, v4.1 or v4.2?
Ref: https://longhorn.io/kb/troubleshooting-unable-to-mount-an-nfs-backup-target/

**Comment by derekbit** [comment]
You can try
1. Set backup target setting to empty
2. Enter each longhorn-manager pod and unmount the NFS backup target monntpoint by force unmount `umount -f`
3. Set backup target setting to your remote NFS server

**Comment by derekbit** [comment]
Sorry, in the Second step, can you login into each longhorn-manager pod and check the mountpoint by `mount | grep nfs`?

**Comment by derekbit** [comment]
Do you have any idea? @mantissahz @weizhe0422

**Comment by derekbit** [comment]
@Razorbob Can you provide the support bundle? Thank you.

**Comment by mantissahz** [comment]
@Razorbob had you run `curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.4.1/scripts/environment_check.sh | bash` this script before?

**Comment by derekbit** [comment]
Sorry, updated the command.

**Comment by derekbit** [comment]
> I think it was a typo -> Longhon instead of Longhorn

Oh, yeah. You're right.
Except for `mars4`, all nodes looks work well. Can you check `dmesg` of the `mars4` host and see if there is any clue?

**Comment by derekbit** [comment]
```
[1402749.847295] nfs: server 10.0.10.51 not responding, timed out
[1402749.847316] NFS: state manager: lease expired failed on NFSv4 server 10.0.10.51 with error 110
```

I think the next step we can troubleshooting why the sever is not responding.

**Comment by derekbit** [comment]
> Its a Qnap NAS with 3.4.6 Kernel

Do you mean the backup target is a QNAP NAS?
Will update if I have any idea.

**Comment by derekbit** [comment]
> Hey Guys any ideas? I don't know why, but I feel like the NAS is not the problem here - cause I can mount the share manually just fine.

I still have no idea why the NFS client is somehow stuck on the `mars4` node, but it looks not related to Longhorn itself. Would you mind trying to restart this node and see if the issue still remains?

**Comment by derekbit** [comment]
@Razorbob Everything is back to normal, right?
