### ISSUE TITLE
[IMPROVEMENT] Create a new setting so that Longhorn removes PDB for instance-manager-r that doesn't have any running instance inside it

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#5549]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Currently, the user can never finish draining a node if it contains a stopped replica of a volume and that replica is the only replica of the volume. 

In some cases, that behavior is desired. For example, the user is trying to drain the node before replacing it. In this case, we block the drain to signal the user that it is not OK to remove that node since there will be data loss. 

However, in some other cases, it is not desired. For example, the user is trying to drain a node and do an in-place node upgrade. In this case, we should not block the user's draining process because:
1. There is no harm to data integrity  
2. There would be no data loss because the node is not going to be removed

## Describe the solution you'd like

Create a new setting so that Longhorn removes PDB for instance-manager-r that doesn't have any running instance inside it

## Describe alternatives you've considered

Manually evict the replica from the node before draining. This one is costly and not possible in a single-node cluster

**Comment by innobead** [comment]
@shuo-wu @derekbit @c3y1huang  any thoughts on this? 

cc @longhorn/dev-control-plane

**Comment by c3y1huang** [comment]
Does https://github.com/longhorn/longhorn/issues/2238 solve this issue?

**Comment by innobead** [comment]
Good point @c3y1huang , but I feel the case is a different purpose. 

@PhanLe1010 provided is in-tact change but https://github.com/longhorn/longhorn/issues/2238 is for evicting replicas. These options probably are all helpful for users.

**Comment by c3y1huang** [comment]
> Good point @c3y1huang , but I feel the case is a different purpose.
> 
> @PhanLe1010 provided is in-tact no change (nothing to do) but #2238 is for evicting replicas. These options probably are all helpful for users.

I see. Doesn't set `allow-node-drain-with-last-healthy-replica` work for this case?

**Comment by PhanLe1010** [comment]
> I see. How about set allow-node-drain-with-last-healthy-replica, does it work for the case of a single node cluster?

Good idea! However, I think this one is problematic in the following draining scenario:
1. Replica instance manager is evicted while the volume is running
2. The volume crash -> potential filesystem corruption 
3. Workload pods are evicted

**Comment by innobead** [comment]
This new setting is actually for `detached volume` only, but `allow-node-drain-with-last-healthy-replica` does not matter if the volume is attached or detached, so it would cause the case @PhanLe1010 mentioned.

**Comment by c3y1huang** [comment]
I am curious if it is necessary to have a new setting since there is already `allow-node-drain-with-last-healthy-replica` to unblock the node drain.

Without the new setting, user can do this:
1. Single node cluster.
1. Drain blocked by PDB.
1. User checks if all replicas are stopped.
1. Enable `allow-node-drain-with-last-healthy-replica` setting.
1. Drain node.
1. In-place upgrade.
1. Disable `allow-node-drain-with-last-healthy-replica` setting.

**Comment by PhanLe1010** [comment]
> I am curious if it is necessary to have a new setting since there is already `allow-node-drain-with-last-healthy-replica` to unblock the node drain.
> 
> Without the new setting, user can do this:
> 
> 1. Single node cluster.
> 2. Drain blocked by PDB.
> 3. User checks if all replicas are stopped.
> 4. Enable `allow-node-drain-with-last-healthy-replica` setting.
> 5. Drain node.
> 6. In-place upgrade.
> 7. Disable `allow-node-drain-with-last-healthy-replica` setting.

I see. Yeah, the approach works. However, it requires manual intervention in steps 3 and 4. This is inconvenient in a fully automated upgrade process like [System Upgrade Controller ](https://github.com/rancher/system-upgrade-controller)

**Comment by innobead** [comment]
Removing from 1.3.3 first, because it seems to require some time.

**Comment by innobead** [comment]
memo from @PhanLe1010 

> Yes, it is correct. No protection is needed for stopped replica. User is allowed to drain the instance manager. (We are assuming that user doesn't remove the node after draining)

Besides in-place node drain, need to emphasize this setting is risky for node replacement because it will cause data loss like the Azure AKS upgrade. 

cc @c3y1huang

**Comment by PhanLe1010** [comment]
Test Plan: 

Perform the [test plan](https://github.com/longhorn/longhorn/issues/3304#issuecomment-1467174481) again. And verify that:
1.  With `allow-node-drain-with-last-healthy-replica` is `false` and `node-drain-policy` is `block-if-contains-last-replica` the test result is identical to the test plan
2. With `allow-node-drain-with-last-healthy-replica` is `false` and `node-drain-policy` is `allow-if-replica-is-stopped` the test `1.1 Single node cluster` is drained successfully. Other test cases in that test plan should be successful too.
3. Additionally, try out with different combinations of `allow-node-drain-with-last-healthy-replica` and `node-drain-policy` setting and verify that the behavior make sense

**Comment by innobead** [comment]
After updating the doc, let's move this to ready-for-testing for QA testing.

**Comment by innobead** [comment]
@khushboo-rancher Please help verify this after @PhanLe1010 moves this to ready-for-testing. cc @yangchiu will be back on Wed.

**Comment by khushboo-rancher** [comment]
As discussed with @innobead, @PhanLe1010 Can we make the default value for `node-drain-policy` adaptive based on the existing customer's `allow-node-drain-with-last-healthy-replica` setting?

Default value for `node-drain-policy`  can be as below
1. Fresh installation :
      a.  `node-drain-policy` : block-if-contains-last-replica
3. Upgrade :
      a.  `allow-node-drain-with-last-healthy-replica`: False -> `node-drain-policy`: block-if-contains-last-replica
      b.  `allow-node-drain-with-last-healthy-replica`: True -> `node-drain-policy`: always-allow

**Comment by PhanLe1010** [comment]
There would be a problem in the 2nd case:
* User install Longhorn v1.3.2 with `allow-node-drain-with-last-healthy-replica` set to `true`
* User upgrade Longhorn to 1.3.3 with `node-drain-policy` withset to `block-if-contains-last-replica`. If we follow the 2nd point above we would overwrite the user setting. 

IMO, no matter what we set, keeping 2 overlapping settings will introduce some confusion.

**Comment by innobead** [comment]
After discussing with @PhanLe1010 and @khushboo-rancher . Let's make a conclusion for this and this will apply for any deprecation case.

- Keep `node-drain-policy` and `allow-node-drain-with-last-healthy-replica` together for 1.3.3 and 1.4.2, because we will not prefer removing an existing function from any patch release. However, need to emphasize the below items:
    -  There is an overlapping between both. `allow-node-drain-with-last-healthy-replica` has been deprecated in 1.3.3 and 1.4.2, so encourage users to use `node-drain-policy`. 
    - `allow-node-drain-with-last-healthy-replica` will be respected first for compatibility.
- Any deprecated feature will be removed from the next feature release, so `allow-node-drain-with-last-healthy-replica` will be removed from 1.5.0.

**Comment by innobead** [comment]
@khushboo-rancher The state is pending in testing for a while. I believe we already finished the testing, right?

**Comment by khushboo-rancher** [comment]
Oh, I missed it. We finished the testing on 1.4 and 1.3. I'll work on the validation.

**Comment by khushboo-rancher** [comment]
I would like to test this once https://github.com/longhorn/longhorn/issues/5620 is delivered too because both impacts same area. Testing them separately is redundant effort. @innobead WDYT?

**Comment by innobead** [comment]
@khushboo-rancher sounds good to me.

**Comment by roger-ryao** [comment]
**Verified on master-head 20230523**

- longhorn master-head ([d6b1739](https://github.com/longhorn/longhorn/commit/d6b173977bf9f0a36ad12fb18fd93019fba1d5a4))
- longhorn-manager master-head ([565d335](https://github.com/longhorn/longhorn-manager/commit/565d335fcbb80b2e6522dc35a0d63cc389e27e88))

**The test steps**

https://github.com/longhorn/longhorn/issues/5549#issuecomment-1474476921

**Result Passed**
Scenario | allow-node-drain-with-last-healthy-replica | node-drain-policy | Outcome
-- | -- | -- | --
1.1 Single node cluster | false | block-if-contains-last-replica | instance-manager-r is not evicted
  | false | allow-if-replica-is-stopped | node can be drained successfully
  | false | always-allow | node can be drained successfully
  | true | block-if-contains-last-replica | node can be drained successfully
1.2 Multi-node cluster | false | block-if-contains-last-replica | node can be drained successfully
  | false | allow-if-replica-is-stopped | node can be drained successfully
  | false | always-allow | node can be drained successfully
  | true | block-if-contains-last-replica | node can be drained successfully
2.1 Upgrade Kubernetes for k3s cluster with System Upgrade Controller | false | block-if-contains-last-replica | node can be drained and k8s upgraded successfully   
  | | false | allow-if-replica-is-stopped | node can be drained and k8s upgraded successfully
  | false | always-allow | node can be drained and k8s upgraded successfully
  | true | block-if-contains-last-replica | node can be drained and k8s upgraded successfully
3.1 Upgrade Kubernetes for imported k3s cluster in Rancher | false | block-if-contains-last-replica | node can be drained and k8s upgraded successfully
  | false | allow-if-replica-is-stopped | node can be drained and k8s upgraded successfully
  | false | always-allow | node can be drained and k8s upgraded successfully
  | true | block-if-contains-last-replica | node can be drained and k8s upgraded successfully
4.1 Upgrade Kubernetes for provisioned k3s cluster in Rancher | false | block-if-contains-last-replica | node can be drained and k8s upgraded successfully
  | false | allow-if-replica-is-stopped | node can be drained and k8s upgraded successfully
  | false | always-allow | node can be drained and k8s upgraded successfully
  | true | block-if-contains-last-replica | node can be drained and k8s upgraded successfully

**Comment by roger-ryao** [comment]
Hi @PhanLe1010 :
I have reopened the ticket because @innobead  added the label `require/manual-test-plan` after you submitted https://github.com/longhorn/website/pull/677. Could you please add the manual test plan as requested?

cc @longhorn/qa

**Comment by innobead** [comment]
@longhorn/qa QA also can judge if this needs manual test plan or e2e cases instead. Just update the issue with the right labels. Thanks.

**Comment by PhanLe1010** [comment]
Manual test plan PR is created https://github.com/longhorn/longhorn-tests/pull/1395. Moving the ticket to ready for testing

**Comment by roger-ryao** [comment]
Close the issue because the manual test plan PR, longhorn/longhorn-tests#1395, is ready.
