### ISSUE TITLE
[TEST] Consolidate all the node down/reboot and kubelet restart manual test cases

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#5569]
## What's the test to develop? Please describe

We have test cases related to node down/restart & kubelet restart documented https://longhorn.github.io/longhorn-tests/manual/ , We want to consolidate those cases at one place, currently they are scenario based and we can make them better by making them more generalized.

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] Find all the related cases on https://longhorn.github.io/longhorn-tests/manual/
- [ ] Make them generic and move them at one place.

**Comment by roger-ryao** [comment]
Created https://github.com/longhorn/longhorn-tests/pull/1327 and waiting for review.

**Comment by roger-ryao** [comment]
https://github.com/longhorn/longhorn-tests/pull/1327 and https://github.com/longhorn/longhorn-tests/pull/1343 was merged
