### ISSUE TITLE
[BUG] Node shows all replicas as stopped

### ISSUE THREAD

**Issue by LilDrunkenSmurf** [longhorn/longhorn#5582]
## Describe the bug (🐛 if you encounter this issue)
I'm having replication issues in this env:
Intel NUC control plane (mini-node-1/SSD) - healthy replicas
pi-node-1 (8GB RAM/USB3.0 flash) - healthy replicas
pi-node-2 (4GB RAM/USB3.0 flash) - constantly fails replica rebuilds
pi-node-3 (4GB RAM/SSD) - shows all replicas as stopped, and all volumes with those stopped ones as `degraded`.

## To Reproduce
Click on pi-node-3, shows all replicas as stopped
![image](https://user-images.githubusercontent.com/46251616/225793400-22b9ba27-430a-4974-ac72-61b08b0c19e2.png)
![image](https://user-images.githubusercontent.com/46251616/225793826-b42a20d0-20e4-4900-80d1-1e7e4bbf130a.png)

## Expected behavior
Volumes are healthy, replicas are successfully build

## Log or Support bundle
[supportbundle_a33949f1-e247-4a26-a6cd-3dcac7397190_2023-03-17T02-01-06Z.zip](https://github.com/longhorn/longhorn/files/10997161/supportbundle_a33949f1-e247-4a26-a6cd-3dcac7397190_2023-03-17T02-01-06Z.zip)

## Environment

 - Longhorn version: v1.41
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 22.04 Control node /Raspbian 64bit (Debian 11) worker nodes
   - CPU per node: 4
   - Memory per node: 16GB Control, 8GB healthy pi, 4GB failing pis
   - Disk type(e.g. SSD/NVMe): SSD/USB3/USB3/SSD
   - Network bandwidth between the nodes: Gigabit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 11

## Additional context

I was previously having an [issue](https://github.com/longhorn/longhorn/issues/5579) where one of my nodes was showing as 100% allocation with no volumes on the node. Originally I solved this by removing and re-adding the disk, where this issue started. Now I've blown away the node, and completely set it up from scratch (fresh OS), and the issue is still there. I did reuse the node name.

**Comment by derekbit** [comment]
```
Replica rebuildings for map[pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-917b2d8a:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-bbdc5c38:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-c4846c4a:{}] are in progress on this node, which reaches or exceeds the concurrent limit value 3
```

Most of the stopped replicas are waiting to be rebuilt. You can check later.

**Comment by LilDrunkenSmurf** [comment]
So I left it overnight, and the node still shows all 10 as stopped. There's no longer any attempts to rebuild anything. Everything is just in a state of holding.

**Comment by derekbit** [comment]
@LilDrunkenSmurf 
Please provide the latest support bundle. Thanks.

**Comment by LilDrunkenSmurf** [comment]
```Failed rebuilding replica with Address 10.42.103.242:10015: proxyServer=10.42.134.199:8501 destination=10.42.134.199:10003: failed to add replica tcp://10.42.103.242:10015 for volume: rpc error: code = Unknown desc = failed to sync files [{FromFileName:volume-snap-619a3b94-da0e-401e-91a5-4d3860379151.img ToFileName:volume-snap-619a3b94-da0e-401e-91a5-4d3860379151.img ActualSize:80928768} {FromFileName:volume-snap-619a3b94-da0e-401e-91a5-4d3860379151.img.meta ToFileName:volume-snap-619a3b94-da0e-401e-91a5-4d3860379151.img.meta ActualSize:0} {FromFileName:volume-snap-daily-ba-23de824d-b504-4160-b787-49bfb955b714.img ToFileName:volume-snap-daily-ba-23de824d-b504-4160-b787-49bfb955b714.img ActualSize:956313600} {FromFileName:volume-snap-daily-ba-23de824d-b504-4160-b787-49bfb955b714.img.meta ToFileName:volume-snap-daily-ba-23de824d-b504-4160-b787-49bfb955b714.img.meta ActualSize:0} {FromFileName:volume-snap-daily-ba-608fdf89-2612-4302-84b8-641858f93c2c.img ToFileName:volume-snap-daily-ba-608fdf89-2612-4302-84b8-641858f93c2c.img ActualSize:99098624} {FromFileName:volume-snap-daily-ba-608fdf89-2612-4302-84b8-641858f93c2c.img.meta ToFileName:volume-snap-daily-ba-608fdf89-2612-4302-84b8-641858f93c2c.img.meta ActualSize:0} {FromFileName:volume-snap-daily-sn-73068d01-e282-48f7-9ea3-af94ff120da4.img ToFileName:volume-snap-daily-sn-73068d01-e282-48f7-9ea3-af94ff120da4.img ActualSize:119640064} {FromFileName:volume-snap-daily-sn-73068d01-e282-48f7-9ea3-af94ff120da4.img.meta ToFileName:volume-snap-daily-sn-73068d01-e282-48f7-9ea3-af94ff120da4.img.meta ActualSize:0} {FromFileName:volume-snap-daily-sn-694d40a9-eff2-477c-bbbe-136628e2d22d.img ToFileName:volume-snap-daily-sn-694d40a9-eff2-477c-bbbe-136628e2d22d.img ActualSize:68837376} {FromFileName:volume-snap-daily-sn-694d40a9-eff2-477c-bbbe-136628e2d22d.img.meta ToFileName:volume-snap-daily-sn-694d40a9-eff2-477c-bbbe-136628e2d22d.img.meta ActualSize:0}] from tcp://10.42.181.217:10000: rpc error: code = Unavailable desc = transport is closing```

**Comment by nobbs** [comment]
> So I don't know what's going on, but I set it to 100 replica rebuilds, and that made everything happy. I'm not sure what/where it was hung up, or if I can safely turn it back down to 5, but it's all synced and healthy now.

Thanks for posting your solution here - had the same issue on a small test cluster running v1.4.1. Even removed the affected nodes (somehow only 3 out of 6) from the cluster, and readded them without any change. Changing the rebuild limit up to 25 fixed it immediately...

**Comment by derekbit** [comment]
> [supportbundle_a33949f1-e247-4a26-a6cd-3dcac7397190_2023-03-17T12-57-32Z.zip](https://github.com/longhorn/longhorn/files/11001540/supportbundle_a33949f1-e247-4a26-a6cd-3dcac7397190_2023-03-17T12-57-32Z.zip)
> 
> The instance managers have very little information, from what I can see it's still showing the previous `are in progress on this node, which reaches or exceeds the concurrent limit value 3`
> 
> However, just for testing, I bumped the value to 20, and it looks like it's started to sort of work. I don't know if it got stuck on healthy replicas, or what the deal is?
> 
> `time="2023-03-17T13:04:44Z" level=debug msg="Replica rebuildings for map[pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-1e532abd:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-2efa5002:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-34aa10ab:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-4808da3e:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-4d8e9da8:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-7c9fe352:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-89512b28:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-8ea6c154:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-917b2d8a:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-92878365:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-988b8d6c:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-997013c8:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-a54e595b:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-bbdc5c38:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-c4846c4a:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-c5b183bf:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-cb4ffd83:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-d28d8f19:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-dee8462b:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-fa06047b:{}] are in progress on this node, which reaches or exceeds the concurrent limit value 20" controller=longhorn-replica dataPath= node=pi-node-3 nodeID=pi-node-3 ownerID=pi-node-3 replica=pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-00cdb404`
> 
> That being said, I only have 11 volumes, so I'm not sure how I can exceed 20 replicas rebuilding.

@LilDrunkenSmurf 
```
2023-03-17T12:57:46.776239623Z time="2023-03-17T12:57:46Z" level=debug msg="Replica rebuildings for map[pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-917b2d8a:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-bbdc5c38:{} pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-c4846c4a:{}] are in progress on this node, which reaches or exceeds the concurrent limit value 3" controller=longhorn-replica dataPath= node=pi-node-3 nodeID=pi-node-3 ownerID=pi-node-3 replica=pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-9a4274c1
```

The three running replicas `pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-917b2d8a`, `pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-bbdc5c38`, `pvc-02036d59-9a3b-474e-b90d-cce6b17c07a7-r-c4846c4a` and other stuck replicas are all
1. on node `pi-node-3`
2. rebuildRetryCount = 5
3. failedAt = ""
4. healthyAt = ""

A bit weird, the stuck replicas' labels are
```
      longhorn.io/backing-image: "null"
      longhorndiskuuid: 1b5448e0-106e-47a9-9533-7d3033f8a9a0
      longhornnode: pi-node-3
```

The `longhornvolume` label, which is added by the mutating webhook ([code](https://github.com/longhorn/longhorn-manager/blob/v1.4.1/webhook/resources/replica/mutator.go)), is missing. 

@nobbs 
Can you provide a support bundle if it happens? Thank you.


Any idea? @weizhe0422

**Comment by derekbit** [comment]
@LilDrunkenSmurf  Handled in https://github.com/longhorn/longhorn/issues/5762

**Comment by derekbit** [comment]
@LilDrunkenSmurf @nobbs
Please apply the workaround mentioned in https://github.com/longhorn/longhorn/issues/5762#issue-1669167403. Thank you.

**Comment by innobead** [comment]
This seems fixed in https://github.com/longhorn/longhorn/issues/5582#issuecomment-1509549649. Closing, feel free to reopen this. 

cc @derekbit
