### ISSUE TITLE
[BUG] Longhorn fails to salvage a volume when the volume uses most of the disk

### ISSUE THREAD

**Issue by samip5** [longhorn/longhorn#5592]
## Describe the bug (🐛 if you encounter this issue)

There seems to be issue with auto salvage when one uses a single replica of a volume, and that volume happens to use most of the available storage on the disk.

## To Reproduce

1. Create a volume with most of the actual disk size eg, 300GB volume on a 240GB disk
2. Actual usage of the volume is somewhere like 100GB
3. See it grow in Longorn UI
4. See it fail at some point.

## Expected behavior

I would expect auto salvage to be able to salvage it.

## Log or Support bundle

Support bundle was sent via email.

## Environment

 - Longhorn version: 1.4.0
 - Installation method: Helm with GitOps (https://github.com/samip5/k8s-cluster/blob/main/cluster/apps/storage/longhorn/helm-release.yaml)
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.25.6+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 5
 - Node config
   - OS type and version: Ubuntu 22.04 and Debian 11
   - CPU per node: 2 at least
   - Memory per node: 8GB or more
   - Disk type: SSD
   - Network bandwidth between the nodes: 1G
 - Underlying Infrastructure: One KVM vm and others are baremetal
 - Number of Longhorn volumes in the cluster: 12

## Additional context

Three workers are Raspberry Pis.

**Comment by derekbit** [comment]
Can you point out the problematic volume's name? Thanks.

**Comment by innobead** [comment]
ref: #4532

**Comment by samip5** [comment]
> Can you point out the problematic volume's name? Thanks.

That would be `pvc-11bdc123-0cf8-4401-8bbb-ccc23918cf62`.

**Comment by samip5** [comment]
I have since recovered it manually by mounting it and rsyncing it's content to another volume.
