### ISSUE TITLE
[FEATURE] Update K8s version support and component/pkg/build dependencies for Longhorn 1.5

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5595]
## What's the task? Please describe
For each feature release, we will revisit if need to bump the minimum support version of K8s and K8s dependent libraries based on different reasons like K8s support version cycle, the minimum versions of K8s used by CSI sidecar components planned to deliver/support, etc.  

https://kubernetes.io/releases/patch-releases/
At the moment, 1.26, 1.25, and 1.24 are actively maintained branches, and 1.23 EOL will be `2023-02-28`, so the expected min supported version will be bumped to 1.24. 

## Describe the items of the task (DoD, definition of done) you'd like

- [x] Bump the recent versions of K8s-dependent libraries to the recently newer version given no backward compatibility concerns
- [x] Fix deprecated resources being used/removed from unsupported K8s versions
- [x] Update the min version support of K8s
- [x] Update CSI sidecar versions
- [x] Update Golang version
- [x] Update the K8s version in e2e testing to the updated nearly K8s version @longhorn/qa

**Comment by innobead** [comment]
@ejweber try this, and cooperate with @PhanLe1010 .

**Comment by ejweber** [comment]
Given @PhanLe1010's strategy in https://github.com/longhorn/longhorn/issues/3891#issuecomment-1131258472.

1. The latest version of Kubernetes available is `v1.27`. Future API deprecations and removals are documented through `v1.29`.
2. Longhorn does not use any APIs removed between our current minimum Kubernetes version (`v1.21`) and `v1.29`. The exception is `PodSecurityPolicy`, but it is not being replaced, so there is no new version to upgrade to. Additionally, the `v0.27` version of client-go can still perform CRUD operations on `PodSecurityPolicy`, so backup and restore operations for `PodSecurityPolicy` can still work in older clusters.
3. Longhorn has not added any new APIs that didn't exist in `v1.21`.
4. There is no API-related reason to bump our minimum Kubernetes version.

If we want to arbitrarily bump our minimum Kubernetes version to remain in lockstep with the Kubernetes project itself, we can bump it to `v1.24` as suggested in the issue description.

Current plan:
- Keep minimum Kubernetes version at `v1.21`.
- Upgrade client-go dependency to `v0.27.1`.

WDYT @innobead @PhanLe1010 ?

**Comment by ejweber** [comment]
Additional TODO:
- [ ] Wait for the [backing-image-manager PR](https://github.com/longhorn/backing-image-manager/pull/125) to be merged.
- [ ] Update longhorn-manager PR with new import.

**Comment by PhanLe1010** [comment]
Since we can still support latest Kubernetes version, agree that we should keep the minimum version as v1.21

**Comment by innobead** [comment]
> Since we can still support latest Kubernetes version, agree that we should keep the minimum version as v1.21

Agreed. If nothing changes, there is no strong reasons to change the min version. Let's do this least breaking change.

**Comment by yangchiu** [comment]
- Update the K8s version in e2e testing to the updated nearly K8s version:
    - Already updated to the latest version `v1.27` in https://github.com/longhorn/infra/pull/124
