### ISSUE TITLE
[DOC] Document high availability quorum concepts

### ISSUE THREAD

**Issue by dberardo-com** [longhorn/longhorn#5608]
## What's the task? Please describe

It is not clear how longhorn mantains quorum and which algorithm is being used (like RAFT)

in particular the question i am trying to answer is:

is quorum reached on a replicas basis or on a node basis? i.e. can i have high availability with 3 nodes and 2 replicas only ? is there always only one replica mounted as a "primary" volume on a node or is it possible that multiple replicas are mounted on different nodes? if the latter, then how is HA ensured ?

**Comment by dberardo-com** [comment]
relates to:
* https://github.com/longhorn/longhorn/discussions/8101
* https://github.com/longhorn/longhorn/discussions/9741

**Comment by derekbit** [comment]
Longhorn is not running as a quorum system.
