### ISSUE TITLE
[IMPROVEMENT][UI] Recurring jobs create new snapshots while being not able to clean up old one

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5610]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Need to support UI for two new recurring jobs. https://github.com/longhorn/longhorn/issues/4898

**Comment by innobead** [comment]
@mantissahz Please provide the test steps.

**Comment by khushboo-rancher** [comment]
Just a suggestion instead of ` Backup Force Create` and `Snapshot Force Create` in the task, can we have a check box for `Force create` when user selects `Backup` or `Snapshot`?

cc: @innobead

**Comment by innobead** [comment]
> Just a suggestion instead of ` Backup Force Create` and `Snapshot Force Create` in the task, can we have a check box for `Force create` when user selects `Backup` or `Snapshot`?
> 
> cc: @innobead

@smallteeths Can we help with this? Probably need a tip for the checkbox. @mantissahz Could you help follow up with @smallteeths ? Thanks.

**Comment by smallteeths** [comment]
> > Just a suggestion instead of ` Backup Force Create` and `Snapshot Force Create` in the task, can we have a check box for `Force create` when user selects `Backup` or `Snapshot`?
> > cc: @innobead
> 
> @smallteeths Can we help with this? Probably need a tip for the checkbox. @mantissahz Could you help follow up with @smallteeths ? Thanks.

Sure, I'll make the modification. When the user selects "backup" and checks the "Force create" option, the type of recurring job will be "Force create backup". The same logic applies to snapshots as well.

**Comment by roger-ryao** [comment]
**Verified on master-head 20230414**

- longhorn master-head ([ccf9f3a](https://github.com/longhorn/longhorn/commit/ccf9f3a32d129c1f592c75613b9f316f1c2aaaf1))
- longhorn-manager master-head ([092eca2](https://github.com/longhorn/longhorn-manager/commit/092eca2ddad3d5628294959ed0b6f02b55d46a5f))
- longhorn-ui master-head ([3ddbe5d](https://github.com/longhorn/longhorn-ui/commit/3ddbe5d2fecea4ab4837f09fabbb126562a3e6be))

**The test steps**

1. In the Longhorn UI, go to the Recurring Job page.
2. Click on the Create Recurring Job button.
3. From the Task dropdown menu, select either `Backup` or `Snapshot`.
4. Check the `Force create` option.
5. Verify that the recurring job `task` has been updated to `Force create backup` or `Force create snapshot` accordingly.
6. Click OK to create the recurring job.
7. Repeat steps 1-6 on the Volume Details page in the Longhorn UI.

**Result Passed**

**Comment by khushboo-rancher** [comment]
@roger-ryao Could you please attach a screenshot here. Thanks
