### ISSUE TITLE
[BUG] Support bundle kit should respect node selector & taint toleration

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5614]
## Describe the bug (🐛 if you encounter this issue)

It seems there are no node selectors or taint toleration passed to the support bundle kit, so it will cause deploying a support bundle agent in any node in the cluster. Currently, the image only supports arm64/amd64/s390x, so any non-supported arch nodes will have a pending pod to cause the support bundle kit agent daemonset unable to start successfully. 

Need to respect the same node selector & taint toleration for system management components. 

## To Reproduce

https://github.com/longhorn/longhorn/issues/5613#issuecomment-1476209427

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.4.0/1.4.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

cc @longhorn/qa for any system management components (instance manager, share manager, backing image, support bundle kit manager), need to verify pod deployment use cases.

**Comment by c3y1huang** [comment]
WIP: testing

**Comment by yangchiu** [comment]
Verified passed on master-head (support-bundle-kit v0.0.24). The support bundle kit test cases for node selector and taint toleration can pass, and recently there's no support bundle downloading issue in daily regression.
