### ISSUE TITLE
[BUG] During volume live engine upgrage, if a newly migrating replica hit an error and stops, the volume stuck in upgrading forever

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#5618]
## Describe the bug (🐛 if you encounter this issue)

During volume live engine upgrage, if a newly migrating replica hit an error and stops, the volume stuck in upgrading forever even if the reason that causes the replica error already resolved

## To Reproduce

1. Install Longhorn v1.3.1 into a 3-nodes cluster
2. Create a volume and attach it to a node
3. Upgrade Longhorn to v1.3.2
4. Cordor a node
5. Kill the new instance-manager-r pod on the cordoned node (This manually triggers a instance-manager-r unavailable condition. A similar unavailable condition can happen when the new instance-manager-r has not been deployed yet and the user has enabled `Concurrent Automatic Engine Upgrade Per Node Limit`)
6. Upgrade the engine for the volume -> upgrade stuck because one of the newly migrating replica (the one on the cordoned node) hits error and stopped
7. Uncordoned the node, the instance-manager-r pod becomes running
8. However, the volume is stuck in the upgrading process forever

## Expected behavior

the volume should retry and finish upgrading or simply rollback. It shouldn't be stuck in the between

Affected Longhorn version: v1.3.2

**Comment by PhanLe1010** [comment]
## Workaround:
1. Rollback the engine upgrade to clean up the migrating replicas
2.  Retry the engine upgrade

**Comment by innobead** [comment]
> ## Workaround:
> 1. Rollback the engine upgrade to clean up the migrating replicas
> 2. Retry the engine upgrade

For a problematic volume, can do some retry and after that, if it's still unable to finish the engine upgrade successfully due to some env runtime issue somehow, can just cancel the upgrade for the volume, and then continue others like the best efforts. For users, there will be no interruption since they can still upgrade the current engine image when reattaching the volume. @PhanLe1010 WDYT?

**Comment by PhanLe1010** [comment]
Looks like we touch this issue at https://github.com/longhorn/longhorn-manager/pull/1533 So the fix should already exist in Longhorn v1.3.3-rc 

cc @innobead

**Comment by innobead** [comment]
Perfect. Have u validated this again?

**Comment by PhanLe1010** [comment]
> Perfect. Have u validated this again? @PhanLe1010
> 
> Cc @longhorn/qa

Yeah, I revalidated it. It doesn't stuck

**Comment by khushboo-rancher** [comment]
Closing this in favor of https://github.com/longhorn/longhorn/issues/4726

**Comment by innobead** [comment]
@khushboo-rancher can you help retest this again? Would like to ensure this has been fixed by #4726 Thanks.

cc @longhorn/qa

**Comment by innobead** [comment]
This issue has been fixed as expected, closing. For another issue, we will just focus on testing #5684 .

**Comment by khushboo-rancher** [comment]
While checking this I encountered a strange behavior, I logged a bug - https://github.com/longhorn/longhorn/issues/5729
