### ISSUE TITLE
UI: Restore seems to ignore replica count specified by user

### ISSUE THREAD

**Issue by vitobotta** [longhorn/longhorn#562]
Hi, I am currently testing backups with a single node (v0.5.0) so I specify 1 as the replica count when restoring a volume. However the restore creates two replicas instead, so I have to update the replica count and delete a replica manually. I would expect the restore to create a single replica in this case. Thanks

**Comment by vitobotta** [comment]
Just noticed that when I click the OK button to restore a volume after setting the replicas to 1, it reverts to 2 just before submitting the form.

**Comment by meldafrawi** [comment]
Steps to test:
  - Create volume with 3 replicas. attach it to a node.
  - Create backup
  - Restore the backup multiple times with different number of replica counts.
    _Expected result_: restored volumes replica counts should match the number at specified at restore action
