### ISSUE TITLE
[FEATURE] Remove deprecated `allow-node-drain-with-last-healthy-replica`

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5620]
After discussing with @PhanLe1010 and @khushboo-rancher . Let's make a conclusion for this and this will apply for any deprecation case.

- Keep `node-drain-policy` and `allow-node-drain-with-last-healthy-replica` together for 1.3.3 and 1.4.2, because we will not prefer removing an existing function from any patch release. However, need to emphasize the below items:
    -  There is an overlapping between both. `allow-node-drain-with-last-healthy-replica` has been deprecated in 1.3.3 and 1.4.2, so encourage users to use `node-drain-policy`. 
    - `allow-node-drain-with-last-healthy-replica` will be respected first for compatibility.
- Any deprecated feature will be removed from the next feature release, so `allow-node-drain-with-last-healthy-replica` will be removed from 1.5.0.

_Originally posted by @innobead in https://github.com/longhorn/longhorn/issues/5549#issuecomment-1477313619_

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by innobead** [comment]
@PhanLe1010 Need to update the doc or related test cases as well.

**Comment by PhanLe1010** [comment]
> @PhanLe1010 Need to update the doc or related test cases as well.

PR was created https://github.com/longhorn/website/pull/719 @innobead

**Comment by innobead** [comment]
@PhanLe1010 merged. Let's move to ready-for-testing if all ready. Thanks.

**Comment by weizhe0422** [comment]
# Under testing, will keep update the result in this comment
 ## Environment
  - Longhorn version: v1.5.0-rc1 
      ![image](https://github.com/longhorn/longhorn/assets/17548901/bb2608eb-b733-4905-8705-afb1fcd02804)
  - cluster info
    - K8S version: v1.25.9 +rke2r1
    - master*1 + worker*3
      ![image](https://github.com/longhorn/longhorn/assets/17548901/5ba9a654-71c6-40ad-84cb-ea07936d1a40)
 
 ## Test steps
 **Scenario 1: The setting `allow-node-drain-with-last-healthy-replica` is not exist**
   1. Fresh installation with Helm
     - [**PASS**, 20230606] verify the setting is gone
     ![image](https://github.com/longhorn/longhorn/assets/17548901/46e5ac68-d77d-4b2a-8ead-9b0b6ec3bcb6)
   2. Upgrade with kubectl command
     - [**PASS**, 20230606] verify the setting is gone
     ![image](https://github.com/longhorn/longhorn/assets/17548901/0da2bf9a-552d-41ea-b94b-b5549bfe93c5)
