### ISSUE TITLE
[BUG] Updated Rocky 9 (and others) can't attach due to SELinux

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5627]
IIRC, Fedora CoreOS, centos stream and fedora enable SELinux by default and are popular OSes. Although we have a KB for OKD (https://longhorn.io/kb/troubleshooting-volumes-stuck-in-attach-detach-loop-when-using-longhorn-on-okd/), it is worth investigating and figuring out a solution for SELinux enabled env.

cc @innobead @ChanYiLin

_Originally posted by @derekbit in https://github.com/longhorn/longhorn/discussions/5367#discussioncomment-5377112_

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by khushboo-rancher** [comment]
We support running e2e integration test RHEL/Cent OS with SELinux enabled on our CI. The latest versions we have tested with SELinux are RHEL 8.6 and CentOS 8.4.
I've triggered the test on RHEL 8.6 SELinux enabled and will share the result.

As far I know, SELinux enabled OS level works fine but SELinux enabled docker label has some problem.

**Comment by ejweber** [comment]
A number of users in various Slack channels and on GitHub are starting to raise SELinux related issues. In particular, it is being reported that updating the following packages on a RHEL-like distribution (which happens automatically in both el8 and el9) causes Longhorn failures:

```
container-selinux-2.205.0-1.el9_2.noarch
selinux-policy-38.1.11-2.el9_2.2.noarch
selinux-policy-targeted-38.1.11-2.el9_2.2.noarch
```

The issue manifests itself with the following SELinux violation:

```
type=SYSCALL msg=audit(1685655494.348:29035): arch=c000003e syscall=83 success=no exit=-13 a0=55b780fce620 a1=1f8 a2=ffffffffffffff00 a3=0 items=2 ppid=1062564 pid=1063465 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="iscsiadm" exe="/usr/sbin/iscsiadm" subj=system_u:system_r:iscsid_t:s0 key=(null)
type=AVC msg=audit(1685655494.348:29035): avc:  denied  { dac_override } for  pid=1063465 comm="iscsiadm" capability=1  scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:system_r:iscsid_t:s0 tclass=capability permissive=0
```

This looks similar to https://github.com/longhorn/longhorn/issues/4988.

**Comment by brandond** [comment]
`syscall=83` would be `mkdir`; this corresponds to the research at https://bugzilla.redhat.com/show_bug.cgi?id=1973683:

> The AVC dac_override denial is due to OpenISCI creating node directory permissions with 0660 (and additionally they call umask(0177) in both iscsiadm and iscsid).
> 
> Expected results:
> 
> Manually changing the directory permissions results in a successful run. Additionally, patching the mkdir() and umask() calls and rebuilding the RPM is confirmed to fix the issue as well.

also ref https://github.com/fedora-selinux/selinux-policy/pull/526 which was closed as a bug in open-iscsi.

**Comment by ejweber** [comment]
Practical steps to reproduce the issues users have recently been seeing:

1. Create a Rocky Linux 9 VM (I used a Digital Ocean droplet).
2. Follow the RKE2 Quick Snstall guide to get a single-node RKE2 cluster up and running (https://docs.rke2.io/install/quickstart),
3. Note that the following packages are included in the install (`container-linux v205` is likely the issue):

```
[root@selinux-recreate-rocky-9 ~]# curl -sfL https://get.rke2.io/ | sh -
[INFO]  finding release for channel stable
[INFO]  using 1.25 series from channel stable
DigitalOcean Droplet Agent                                                               29 kB/s | 3.3 kB     00:00
Rancher RKE2 Common (stable)                                                            1.7 kB/s | 1.0 kB     00:00
Rancher RKE2 1.25 (stable)                                                              2.3 kB/s | 1.5 kB     00:00
Dependencies resolved.
======================================================================================================================== Package                         Architecture   Version                        Repository                          Size
========================================================================================================================Installing:
 rke2-server                     x86_64         1.25.10~rke2r1-0.el9           rancher-rke2-1.25-stable           9.0 k
Upgrading:
 iptables-libs                   x86_64         1.8.8-6.el9_1                  baseos                             398 k
 selinux-policy                  noarch         38.1.11-2.el9_2.2              baseos                              54 k
 selinux-policy-targeted         noarch         38.1.11-2.el9_2.2              baseos                             6.4 M
Installing dependencies:
 container-selinux               noarch         3:2.205.0-1.el9_2              appstream                           50 k
 iptables-nft                    x86_64         1.8.8-6.el9_1                  baseos                             185 k
 libnftnl                        x86_64         1.2.2-1.el9                    baseos                              83 k
 rke2-common                     x86_64         1.25.10~rke2r1-0.el9           rancher-rke2-1.25-stable            19 M
 rke2-selinux                    noarch         0.12-1.el9                     rancher-rke2-common-stable          22 k
```

4. Clone the longhorn/longhorn v1.4.2.
5. `kubectl apply -f deploy/prerequisite/longhorn-iscsi-installation.yaml`
6. `kubectl apply -f deploy/longhorn.yaml`
7. Create and attach a Longhorn volume.
8. The volume never attaches.

```
eweber@laptop:~> kl get volume
NAME   STATE       ROBUSTNESS   SCHEDULED   SIZE         NODE                       AGE
test   attaching   unknown                  5368709120   selinux-recreate-rocky-9   9m46s
```

9. See iSCSI related failures in `instance-manager-e` logs.

```
[longhorn-instance-manager] time="2023-06-02T14:55:44Z" level=info msg="Process Manager: prepare to create process test-e-ebf4f7c9"
[longhorn-instance-manager] time="2023-06-02T14:55:44Z" level=debug msg="Process Manager: validate process path: /engine-binaries/longhornio-longhorn-engine-v1.4.2/longhorn dir: /engine-binaries/ image: longhornio-longhorn-engine-v1.4.2 binary: longhorn"
[longhorn-instance-manager] time="2023-06-02T14:55:44Z" level=info msg="Process Manager: created process test-e-ebf4f7c9"
[test-e-ebf4f7c9] time="2023-06-02T14:55:44Z" level=info msg="Creating volume test controller with iSCSI target request timeout 15s and engine to replica(s) timeout 8s"
[test-e-ebf4f7c9] time="2023-06-02T14:55:44Z" level=info msg="Starting with replicas [\"tcp://10.42.0.72:10000\"]"
time="2023-06-02T14:55:44Z" level=info msg="Connecting to remote: 10.42.0.72:10000 (tcp)"
[test-e-ebf4f7c9] time="2023-06-02T14:55:44Z" level=info msg="Opening remote: 10.42.0.72:10000"
[test-e-ebf4f7c9] time="2023-06-02T14:55:44Z" level=info msg="Adding backend: tcp://10.42.0.72:10000"
[test-e-ebf4f7c9] time="2023-06-02T14:55:44Z" level=info msg="Start monitoring tcp://10.42.0.72:10000"
[test-e-ebf4f7c9] time="2023-06-02T14:55:44Z" level=info msg="Got backend tcp://10.42.0.72:10000 UnmapMarkSnapChainRemoved false"
time="2023-06-02T14:55:44Z" level=info msg="Controller checked and corrected flag unmapMarkSnapChainRemoved=false for backend replicas"
[test-e-ebf4f7c9] time="2023-06-02T14:55:44Z" level=info msg="Got backend tcp://10.42.0.72:10000 revision counter 0"
[test-e-ebf4f7c9] time="2023-06-02T14:55:44Z" level=info msg="Shutting down iSCSI target iqn.2019-10.io.longhorn:test"
lh_client_close_conn: Closing connection
[test-e-ebf4f7c9] time="2023-06-02T14:55:44Z" level=info msg="device test: iSCSI device /dev/longhorn/test shutdown"
[test-e-ebf4f7c9] go-iscsi-helper: tgtd is already running
[test-e-ebf4f7c9] time="2023-06-02T14:55:45Z" level=info msg="go-iscsi-helper: found available target id 1"
tgtd: device_mgmt(246) sz:91 params:path=/var/run/longhorn-test.sock,bstype=longhorn,bsopts=size=5368709120;request_timeout=15
tgtd: bs_thread_open(409) 16
[test-e-ebf4f7c9] time="2023-06-02T14:55:45Z" level=info msg="New data socket connection established"
[longhorn-instance-manager] time="2023-06-02T14:55:45Z" level=info msg="Wait for gRPC service of process test-e-ebf4f7c9 to start at localhost:10000"
[test-e-ebf4f7c9] time="2023-06-02T14:55:45Z" level=warning msg="Failed to discover" error="<nil>"
[test-e-ebf4f7c9] time="2023-06-02T14:55:45Z" level=warning msg="Nodes cleaned up for iqn.2019-10.io.longhorn:test"
[longhorn-instance-manager] time="2023-06-02T14:55:46Z" level=info msg="Wait for gRPC service of process test-e-ebf4f7c9 to start at localhost:10000"
[longhorn-instance-manager] time="2023-06-02T14:55:47Z" level=info msg="Wait for gRPC service of process test-e-ebf4f7c9 to start at localhost:10000"
[longhorn-instance-manager] time="2023-06-02T14:55:48Z" level=info msg="Wait for gRPC service of process test-e-ebf4f7c9 to start at localhost:10000"
[test-e-ebf4f7c9] time="2023-06-02T14:55:48Z" level=warning msg="Failed to discover" error="<nil>"
[test-e-ebf4f7c9] time="2023-06-02T14:55:48Z" level=warning msg="Nodes cleaned up for iqn.2019-10.io.longhorn:test"
[longhorn-instance-manager] time="2023-06-02T14:55:49Z" level=info msg="Wait for gRPC service of process test-e-ebf4f7c9 to start at localhost:10000"
[longhorn-instance-manager] time="2023-06-02T14:55:50Z" level=info msg="Wait for gRPC service of process test-e-ebf4f7c9 to start at localhost:10000"
[longhorn-instance-manager] time="2023-06-02T14:55:51Z" level=info msg="Wait for gRPC service of process test-e-ebf4f7c9 to start at localhost:10000"
[test-e-ebf4f7c9] time="2023-06-02T14:55:51Z" level=warning msg="Failed to discover" error="<nil>"
[test-e-ebf4f7c9] time="2023-06-02T14:55:51Z" level=warning msg="Nodes cleaned up for iqn.2019-10.io.longhorn:test"
[longhorn-instance-manager] time="2023-06-02T14:55:52Z" level=info msg="Wait for gRPC service of process test-e-ebf4f7c9 to start at localhost:10000"
[longhorn-instance-manager] time="2023-06-02T14:55:53Z" level=info msg="Wait for gRPC service of process test-e-ebf4f7c9 to start at localhost:10000"
[longhorn-instance-manager] time="2023-06-02T14:55:54Z" level=info msg="Wait for gRPC service of process test-e-ebf4f7c9 to start at localhost:10000"
[test-e-ebf4f7c9] time="2023-06-02T14:55:54Z" level=warning msg="Failed to discover" error="<nil>"
[test-e-ebf4f7c9] time="2023-06-02T14:55:54Z" level=warning msg="Nodes cleaned up for iqn.2019-10.io.longhorn:test"
```

10. See denials in SELinux audit logs:

```
[root@selinux-recreate-rocky-9 ~]# ausearch -m AVC -ts recent
...
----
time->Fri Jun  2 14:58:17 2023
type=PROCTITLE msg=audit(1685717897.278:1612): proctitle=697363736961646D002D6D00646973636F76657279002D740073656E6474617267657473002D700031302E34322E302E3733
type=SYSCALL msg=audit(1685717897.278:1612): arch=c000003e syscall=83 success=no exit=-13 a0=55b0c1e7f590 a1=1f8 a2=ffffffffffffff00 a3=0 items=0 ppid=55197 pid=55730 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="iscsiadm" exe="/usr/sbin/iscsiadm" subj=system_u:system_r:iscsid_t:s0 key=(null)
type=AVC msg=audit(1685717897.278:1612): avc:  denied  { dac_override } for  pid=55730 comm="iscsiadm" capability=1  scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:system_r:iscsid_t:s0 tclass=capability permissive=0
```

**Comment by ejweber** [comment]
Following the instructions at https://www.redhat.com/sysadmin/selinux-denial2, I was able to get more complete information about our denial:

```
[root@selinux-recreate-rocky-9 ~]# ausearch -m AVC -ts recent
...
----
time->Fri Jun  2 15:51:32 2023
type=PROCTITLE msg=audit(1685721092.234:3026): proctitle=697363736961646D002D6D00646973636F76657279002D740073656E6474617267657473002D700031302E34322E302E3733
type=PATH msg=audit(1685721092.234:3026): item=1 name="/var/lib/iscsi/nodes/iqn.2019-10.io.longhorn:test/10.42.0.73,3260,1" nametype=CREATE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1685721092.234:3026): item=0 name="/var/lib/iscsi/nodes/iqn.2019-10.io.longhorn:test/" inode=4773183 dev=fc:01 mode=040600 ouid=0 ogid=0 rdev=00:00 obj=system_u:object_r:iscsi_var_lib_t:s0 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD msg=audit(1685721092.234:3026): cwd="/"
type=SYSCALL msg=audit(1685721092.234:3026): arch=c000003e syscall=83 success=no exit=-13 a0=56076778c590 a1=1f8 a2=ffffffffffffff00 a3=0 items=2 ppid=183514 pid=183836 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="iscsiadm" exe="/usr/sbin/iscsiadm" subj=system_u:system_r:iscsid_t:s0 key=(null)
type=AVC msg=audit(1685721092.234:3026): avc:  denied  { dac_override } for  pid=183836 comm="iscsiadm" capability=1  scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:system_r:iscsid_t:s0 tclass=capability permissive=0


[root@selinux-recreate-rocky-9 ~]# ausearch -m AVC -ts recent
Jun  2 15:53:13 selinux-recreate-rocky-9 setroubleshoot[22979]: SELinux is preventing /usr/sbin/iscsiadm from using the dac_override capability. For complete SELinux messages run: sealert -l 92f9ce68-1390-4994-845c-f7e968d4d04b
Jun  2 15:53:13 selinux-recreate-rocky-9 setroubleshoot[22979]: SELinux is preventing /usr/sbin/iscsiadm from using the dac_override capability.#012#012*****  Plugin dac_override (91.4 confidence) suggests   **********************#012#012If you want to help identify if domain needs this access or you have a file with the wrong permissions on your system#012Then turn on full auditing to get path information about the offending file and generate the error again.#012Do#012#012Turn on full auditing#012# auditctl -w /etc/shadow -p w#012Try to recreate AVC. Then execute#012# ausearch -m avc -ts recent#012If you see PATH record check ownership/permissions on file, and fix it,#012otherwise report as a bugzilla.#012#012*****  Plugin catchall (9.59 confidence) suggests   **************************#012#012If you believe that iscsiadm should have the dac_override capability by default.#012Then you should report this as a bug.#012You can generate a local policy module to allow this access.#012Do#012allow this access for now by executing:#012# ausearch -c 'iscsiadm' --raw | audit2allow -M my-iscsiadm#012# semodule -X 300 -i my-iscsiadm.pp#012


[root@selinux-recreate-rocky-9 ~]# sealert -l 92f9ce68-1390-4994-845c-f7e968d4d04b
SELinux is preventing /usr/sbin/iscsiadm from using the dac_override capability.

*****  Plugin dac_override (91.4 confidence) suggests   **********************

If you want to help identify if domain needs this access or you have a file with the wrong permissions on your system
Then turn on full auditing to get path information about the offending file and generate the error again.
Do

Turn on full auditing
# auditctl -w /etc/shadow -p w
Try to recreate AVC. Then execute
# ausearch -m avc -ts recent
If you see PATH record check ownership/permissions on file, and fix it,
otherwise report as a bugzilla.

*****  Plugin catchall (9.59 confidence) suggests   **************************

If you believe that iscsiadm should have the dac_override capability by default.
Then you should report this as a bug.
You can generate a local policy module to allow this access.
Do
allow this access for now by executing:
# ausearch -c 'iscsiadm' --raw | audit2allow -M my-iscsiadm
# semodule -X 300 -i my-iscsiadm.pp


Additional Information:
Source Context                system_u:system_r:iscsid_t:s0
Target Context                system_u:system_r:iscsid_t:s0
Target Objects                /var/lib/iscsi/nodes/iqn.2019-10.io.longhorn:test/
                              10.42.0.73,3260,1 [ capability ]
Source                        iscsiadm
Source Path                   /usr/sbin/iscsiadm
Port                          <Unknown>
Host                          selinux-recreate-rocky-9
Source RPM Packages           iscsi-initiator-
                              utils-6.2.1.4-3.git2a8f9d8.el9.x86_64
Target RPM Packages
SELinux Policy RPM            selinux-policy-targeted-38.1.11-2.el9_2.2.noarch
Local Policy RPM              selinux-policy-targeted-38.1.11-2.el9_2.2.noarch
Selinux Enabled               True
Policy Type                   targeted
Enforcing Mode                Enforcing
Host Name                     selinux-recreate-rocky-9
Platform                      Linux selinux-recreate-rocky-9
                              5.14.0-162.12.1.el9_1.0.2.x86_64 #1 SMP
                              PREEMPT_DYNAMIC Mon Jan 30 22:14:42 UTC 2023
                              x86_64 x86_64
Alert Count                   1030
First Seen                    2023-06-02 14:45:25 UTC
Last Seen                     2023-06-02 15:53:58 UTC
Local ID                      92f9ce68-1390-4994-845c-f7e968d4d04b

Raw Audit Messages
type=AVC msg=audit(1685721238.267:3099): avc:  denied  { dac_override } for  pid=189623 comm="iscsiadm" capability=1  scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:system_r:iscsid_t:s0 tclass=capability permissive=0


type=SYSCALL msg=audit(1685721238.267:3099): arch=x86_64 syscall=mkdir success=no exit=EACCES a0=565066f87590 a1=1f8 a2=ffffffffffffff00 a3=0 items=2 ppid=189090 pid=189623 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm=iscsiadm exe=/usr/sbin/iscsiadm subj=system_u:system_r:iscsid_t:s0 key=(null)

type=CWD msg=audit(1685721238.267:3099): cwd=/

type=PATH msg=audit(1685721238.267:3099): item=0 name=/var/lib/iscsi/nodes/iqn.2019-10.io.longhorn:test/ inode=4773183 dev=fc:01 mode=040600 ouid=0 ogid=0 rdev=00:00 obj=system_u:object_r:iscsi_var_lib_t:s0 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0

type=PATH msg=audit(1685721238.267:3099): item=1 name=/var/lib/iscsi/nodes/iqn.2019-10.io.longhorn:test/10.42.0.73,3260,1 nametype=CREATE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0

Hash: iscsiadm,iscsid_t,iscsid_t,capability,dac_override

```

**Comment by zackbradys** [comment]
Did you see this? @clemenko @galal-hussein

**Comment by ejweber** [comment]
The root cause here is a [bug in open-iscsi](https://github.com/open-iscsi/open-iscsi/pull/244/files), which @derekbit and others correctly identified in #4988. The [KB article we have for OKD](https://longhorn.io/kb/troubleshooting-volumes-stuck-in-attach-detach-loop-when-using-longhorn-on-okd/) lists three workarounds:

1. Upgrade your OKD to a newer version which is after 4.12.0-0.okd-2022-12-10.
2. Upgrade open-iscsi to a newer version including the fix of the permission issue if possible.
3. If in the existing non-working environment, applying dac_override using a local CIL via MachineConfig is also a workaround. 

1 and 3 actually both do the same thing: add the `dac_override` capability to the `iscsid_t` SElinux role.

2 is the "correct" solution, and requires no SELinux modifications.

Unfortunately, while the upstream Fedora `iscsi_initiator_utils` package [now](https://src.fedoraproject.org/rpms/iscsi-initiator-utils/c/8d83995df334ebd25b7ebd9d4f86192d504eeb86?branch=rawhide) points to a fixed version of `open-iscsi`, there is a patch within the RPM build that "undoes" the fix within a particular function. (The 0770 permissions from the fix are [changed back to 0660 permissions](https://src.fedoraproject.org/rpms/iscsi-initiator-utils/blob/rawhide/f/0003-idbm_rec_write-seperate-old-and-new-style-writes.patch#_158), so the execute permission is lost, and `dac_override` is required.) Modifying this patch and rebuilding the iscsi-initiator-utils fixes the issue without SELinux work, as does building and installing `open-iscsi` instead of `iscsi_initiator_utils`. In the long term, we can likely get `iscsi_initiator_utils` fixed more completely. In the short term, we will probably continue to require an SELinux workaround.

**Comment by PhanLe1010** [comment]
@ejweber I was seeing the same [problematic patch in upstream CentOS](https://gitlab.com/redhat/centos-stream/rpms/iscsi-initiator-utils/-/blob/c9s/0003-idbm_rec_write-seperate-old-and-new-style-writes.patch#L156-L174) yesterday too https://gitlab.com/redhat/centos-stream/rpms/iscsi-initiator-utils/-/blob/c9s/0003-idbm_rec_write-seperate-old-and-new-style-writes.patch#L156-L174

I am wondering how do we create PR/issue to these upstream RPM. Any idea @clemenko ?

**Comment by ejweber** [comment]
# Observations

I am not the best at reading SELinux policies themselves, but I believe I understand now why updated RHEL/Rocky is broken and why the `chcon -t container_file_t /usr/sbin/iscsiadm` workaround works.

On a non-updated Rocky/RHEL node, there is NO rule to transition from the `spc_t` domain to the `iscsid_t` domain. We execute `iscsiadm` in the `spc_t` context, which has `dac_override` capabilities.

```
[root@selinux-recreate-rocky-9-2 ~]# yum list installed | grep 'container-selinux\|selinux-policy'
container-selinux.noarch             3:2.189.0-1.el9              @@commandline
selinux-policy.noarch                34.1.43-1.el9_1.1            @anaconda
selinux-policy-targeted.noarch       34.1.43-1.el9_1.1            @anaconda

[root@selinux-recreate-rocky-9-2 ~]# sesearch -T -s spc_t | grep iscsid
# empty

[root@selinux-recreate-rocky-9-2 ~]# sesearch -A -s spc_t -c capability -p dac_override
allow spc_t spc_t:capability { audit_control audit_write chown dac_override dac_read_search fowner fsetid ipc_lock ipc_owner kill lease linux_immutable mknod net_admin net_bind_service net_broadcast net_raw setfcap setgid setpcap setuid sys_admin sys_boot sys_chroot sys_nice sys_pacct sys_ptrace sys_rawio sys_resource sys_time sys_tty_config };
```

On an updated Rocky/RHEL node, there IS a rule to transition from the `spc_t` domain to the `iscsid_t` domain. We execute `iscsiadm` in the `iscsid_t` context (as we rightfully should), which does not have `dac_override` capabilities (as is appropriate).

```
[root@selinux-recreate-rocky-9 bin]# yum list installed | grep 'container-selinux\|selinux-policy'
container-selinux.noarch                    3:2.205.0-1.el9_2                @appstream
selinux-policy.noarch                       38.1.11-2.el9_2.2                @baseos
selinux-policy-targeted.noarch              38.1.11-2.el9_2.2                @baseos

[root@selinux-recreate-rocky-9 bin]# sesearch -T -s spc_t | grep iscsid
type_transition spc_t iscsid_exec_t:process iscsid_t;

[root@selinux-recreate-rocky-9 bin]# sesearch -A -s iscsid_t -c capability
allow iscsid_t iscsid_t:capability { dac_read_search ipc_lock net_admin net_raw sys_admin sys_module sys_nice sys_resource };
```

The `chcon -t container_file_t /usr/sbin/iscsiadm` workaround words because changing the context of `/usr/sbin/iscsiadm` to `container_file_t` disables the transition to the `iscsid_t` domain (there are essentially no transitions). This allows us to execute `iscsiadm` in the `spc_t` context with our `dac_override` capabilities intact.

The root user on either node can execute `iscsiadm` without issue because there is no rule on either system to transition from the `unconfined_t` to `iscsiadm_t` domain. The root user executes `iscsiadm` in the `unconfined_t` context, which, of course, has `dac_override` capabilities.

```
[root@selinux-recreate-rocky-9 bin]# sesearch -T -s unconfined_t | grep iscsid
# empty

[root@selinux-recreate-rocky-9 bin]# sesearch -A -s unconfined_t -c capability
allow unconfined_t unconfined_t:capability sys_module; [ secure_mode_insmod ]:False
allow unconfined_t unconfined_t:capability { audit_control audit_write chown dac_override dac_read_search fowner fsetid ipc_lock ipc_owner kill lease linux_immutable mknod net_admin net_bind_service net_broadcast net_raw setfcap setgid setpcap setuid sys_admin sys_boot sys_chroot sys_nice sys_pacct sys_ptrace sys_rawio sys_resource sys_time sys_tty_config };
```

# Analysis

The updated `container-selinux` policies are correct. Unfortunately, they expose a bug in the RHEL/Rocky version of `iscsi-initiator-utils` and disable functionality that was working incorrectly before. As mentioned above, the long-term fix is to submit a patch to `iscsi-initiator-utils` upstream.

My preferred fix is actually the SELinux policy addition that grants `iscsid_t` the needed `dac_override` capability. It is clear what this does and why. OKD added an SELinux rule for this transition to its set of policies and it would be nice if RKE2 did as well to make Longhorn installation painless until the underlying issue is resolved.

The `chcon -t container_file_t /usr/sbin/iscsiadm` is not functionally different in my opinion. It still effectively grants us a `dac_override` capability (that we were always operating with before), but it obfuscates how exactly this is happening. It is also not necessarily permanent (a relabel operation will likely return the `iscsiadm` context to the "correct" one). However, we can likely add it to our iSCSI installation script and make it somewhat transparent.

**Comment by clemenko** [comment]
Would it make sense for the `rke2-selinux` policy to add the `dac_override` then? I asked them the same question.

**Comment by ejweber** [comment]
Since the Rocky 9 / RKE2 discussion has largely taken over this issue, I opened #6074 as a replacement for the original work.

@galal-hussein ended up making the change suggested by @clemenko to `rke2-selinux`. My analysis supports this decision, so we are good there. I want to accomplish the following things before we close this one out:

- [ ] Get an upstream patch in for iscsi-initiator-utils (we can create an issue to track and eventually test it in downstream distros once it is out there).
- [ ] Produce an updated KB.
- [ ] Provide a DaemonSet that can automatically make the necessary change in non-RKE deployments if users want.

**Comment by ejweber** [comment]
> Agree as well on all three points! Getting the upstream package fixed is the ultimate goal. Should we use #5627 or #6074 as we move forward? @ejweber

Lets use this one (#5627) please.

**Comment by yangchiu** [comment]
After applied the iscsi selinux workaround: https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/prerequisite/longhorn-iscsi-selinux-workaround.yaml, automated test cases can run and pass without a bunch of errors/failures.

`Oracle 9.1` + `k3s v1.27.1+k3s1` + `selinux mode = enforcing`: https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/111/
`Oracle 9.1` + `rke2 v1.27.2+rke2r1` + `selinux mode = enforcing`: https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/112/

`Rockylinux 9.2` + `k3s v1.27.1+k3s1` + `selinux mode = permissive`: https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/113/
`Rockylinux 9.2` + `k3s v1.27.1+k3s1` + `selinux mode = enforcing`: https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/114/
`Rockylinux 9.2` + `rke2 v1.27.2+rke2r1` + `selinux mode = permissive`: https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/115/
`Rockylinux 9.2` + `rke2 v1.27.2+rke2r1` + `selinux mode = enforcing`: https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/116/

`RHEL 9.1` + `k3s v1.27.1+k3s1` + `selinux mode = permissive`: https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/117/
`RHEL 9.1` + `k3s v1.27.1+k3s1` + `selinux mode = enforcing`: https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/118/
`RHEL 9.1` + `rke2 v1.27.2+rke2r1` + `selinux mode = permissive`: https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/119/
`RHEL 9.1` + `rke2 v1.27.2+rke2r1` + `selinux mode = enforcing`: https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/120/
