### ISSUE TITLE
[BUG] `mkdir` a same but dead mount point causes backup stuck

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5628]
## Describe the bug (🐛 if you encounter this issue)

The steps to create a backup are
1. creating a mount point on Longhorn node
2. mount the remote NFS target to the mount point
3. create a backup inside the mount point.

In 1 step, if the mountpoint is existing but dead. Because the nfs mount is using `hard` mode, trying to mkdir a same but dead mount point will be stuck at D state.

To avoid the D state operation, need to check the mount point's healthy first. If it is broken, force unmount and then remount.
## To Reproduce

1. Create a Longhorn v1.3.2 cluster
2. Create a Longhorn volume
3. Set NFS backup store
4. Back up the volume and go to Backup UI page. The backup is listed.
5. Shut down the NFS server
6. Back up the volume again. The backup should be stuck.
7. Wait for at least 5 minutes. Execute `ps aux | grep mkdir` inside one of the longhorn-manage pods, you can see
```
# ps aux | grep mkdir
root         371  0.0  0.0  11484   852 ?        D    11:32   0:00 mkdir -m 700 -p /var/lib/longhorn-backupstore-mounts/10_20_90_100/Longhorn
root         486  0.0  0.0      0     0 ?        Z    11:37   0:00 [mkdir] <defunct>
root         661  0.0  0.0  11484   924 ?        D    11:42   0:00 mkdir -m 700 -p /var/lib/longhorn-backupstore-mounts/10_20_90_100/Longhorn
root         749  0.0  0.0      0     0 ?        Z    11:47   0:00 [mkdir] <defunct>
``` 

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.2.x, <= v1.3.2 and <= v1.4.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Workaround

The workaround is force unmounting the dead NFS mount point in the longhorn-manager-r and longhorn-manager pods
```
umount -f -l <mountpoint> 
```

**Comment by derekbit** [comment]
Just finished backporting the nfs refacring and nfs `soft` mode to v1.4.2.
@innobead  Do you think we should backport to v1.3.3?

**Comment by innobead** [comment]
@derekbit I am lost in the commit history here. Where we are for this issue? Why we had this issue specific for 1.4.2 instead of 1.5.0? 

Is this issue resolved already? The ready-for-testing comment is empty w/o any update. https://github.com/longhorn/longhorn/issues/5628#issuecomment-1487850404

**Comment by derekbit** [comment]
This is a bug caused by the `hard` mode in v1.4.2.
The issue is fixed in https://github.com/longhorn/backupstore/pull/112 which introduces `soft` mode.

master branch introduces `soft` mode when implementing CIFS feature, so direct backport the feature to v1.4.x doesn't work. Hence, this ticket only focuses on the backport of the `soft` mode.

The fix is ready and can move to ready-for-testing.

**Comment by roger-ryao** [comment]
[supportbundle_81183726-5b70-4292-a359-3d41e96c9847_2023-05-04T09-29-55Z.zip](https://github.com/longhorn/longhorn/files/11396172/supportbundle_81183726-5b70-4292-a359-3d41e96c9847_2023-05-04T09-29-55Z.zip)
**Verified on v1.4.x-head 20230504**

- longhorn v1.4.x-head ([f841824](https://github.com/longhorn/longhorn/commit/f8418241e54618b2788d42a827b8d290118907f4))
- longhorn-manager v1.4.x-head ([1f86388](https://github.com/longhorn/longhorn-manager/commit/1f8638823eb56071d821b19cf623a29ffff5f3d5))

**Pre-requisite**
To set up an external NFS server for backup store, perform the following steps:

1. Install the nfs-kernel-server package using the following command:
`sudo zypper install nfs-kernel-server`
2. Enable and start the rpcbind.service and nfsserver.service services using the following commands:
```
systemctl enable rpcbind.service
systemctl start rpcbind.service
systemctl enable nfsserver.service
systemctl start nfsserver.service
```
3. Create a directory to export and change its ownership to nobody:nogroup using the following commands:
```
mkdir /var/nfs
chown nobody:nogroup /var/nfs
```
4. Edit the /etc/exports file and add the following line:
```
/var/nfs     *(rw,no_root_squash,no_subtree_check)
```
5. Run the following command to export the directory:
`exportfs -a`
6. In the Longhorn UI, go to Setting -> Backup Target, and set it as nfs://<NFS server ip>:/var/nfs

Note: To simulate network disconnection, download the `network_down.sh script` from the following link: https://github.com/longhorn/longhorn/files/4864127/network_down.sh.zip

**The test steps**


1. Create a Longhorn cluster
2. Create a Longhorn volume
3. Set NFS backup store
4. Backup the volume and go to Backup UI page. The backup is listed.
5. Disconnect NFS server 20 min
`nohup ./network_down.sh 1200`
6. Backup the volume again. The backup should be stuck.
7. Wait for at least 5 minutes. Execute `ps aux | grep mkdir` inside one of the `longhorn-manage` pods

**Result**

1. We observed `Z state` on `v1.3.2` & `v1.4.1`, but not on `v1.4.x.`
```
longhorn-manager-qlwp9:/ # ps aux | grep mkdir
root        2433  0.0  0.0      0     0 ?        Z    04:57   0:00 [mkdir] <defunct>
root        2589  0.0  0.0      0     0 ?        Z    05:02   0:00 [mkdir] <defunct>
root        2775  0.0  0.0      0     0 ?        Z    05:07   0:00 [mkdir] <defunct>
root        2942  0.0  0.0      0     0 ?        Z    05:12   0:00 [mkdir] <defunct>
root        3933  0.0  0.0   7308   848 pts/1    S+   05:38   0:00 grep mkdir
```

2. The `step 6`, the backup would be stuck on `v1.3.2` & `v1.4.1`, while it would fail on `v1.4.x`.
3. After the `NFS server` comes back, we can continue with the backup volume.
4. I tried to stop the NFS server VM instance on AWS EC2 and start it again. The VM instance IP changed to a new one. After changing the backup target to the new IP, the volume backup failed. The icon turned gray, and the backup page showed an error.
`error listing backup volume names: timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.4.x-head/longhorn [backup ls --volume-only nfs://52.38.4.3:/var/nfs], output , stderr, time="2023-05-04T09:30:23Z" level=warning msg="Trying reading mount point /var/lib/longhorn-backupstore-mounts/52_38_4_3/var/nfs to make sure it is healthy" pkg=nfs , error <nil>`

![Screenshot_20230504_172950](https://user-images.githubusercontent.com/104337648/236171100-83a04edd-eb62-45ca-9f67-fee5ba84dc43.png)

![Screenshot_20230504_172848](https://user-images.githubusercontent.com/104337648/236171260-02061bcd-3ff4-4f93-bf3a-fa43ff224986.png)


[supportbundle_81183726-5b70-4292-a359-3d41e96c9847_2023-05-04T09-29-55Z.zip](https://github.com/longhorn/longhorn/files/11396188/supportbundle_81183726-5b70-4292-a359-3d41e96c9847_2023-05-04T09-29-55Z.zip)


CC @derekbit
