### ISSUE TITLE
[Feature request] Add label/description to backups created manually from UI

### ISSUE THREAD

**Issue by vitobotta** [longhorn/longhorn#563]
At the moment when I click on the `Create backup` button, a backup is created but cannot be recognized easily from the backups list for the volume - apart from the date/time when the snapshot was taken. It would be nice if it were possible to add a description to backups taken manually. So for example if I want to take a backup before an upgrade or something, I can add a description that says that backup was before the upgrade, so I can revert to it later if needed. If the timestamp is the only information we can use to identify a backup, it may be more difficult if more backups have occurred in between. Thanks!

**Comment by yasker** [comment]
@vitobotta That's a good idea! Maybe we can add workload information automatically in addition to the user note if the volume is using by a workload.

**Comment by vitobotta** [comment]
Awesome :)

**Comment by yasker** [comment]
We will support two ways of adding a label to the backup: manually and automatically.

Whenever a backup was made, if we detect the pod information, we will store that information as backup label automatically. This is designed for recurring backups.

And when a backup was created manually, the user can specify multiple labels (except for the reserved keywords Longhorn used), in addition to the automatic stored Kubernetes Status.

Reserved keywords:
KubernetesStatus, RecurringJob

Information saved:
KubernetesStatus will be stored as a JSON in the label

When a volume was restored, KubernetesStatus will be restored to the volume's KuberneteStatus with LastPVCRefAt and LastPodRefAt set to the SnapshotCreated time.

**Comment by yasker** [comment]
UI: when creating PV/PVC with a volume has previous KubernetesStatus set, UI should provide two checkboxes to allow automatically fill PV or Namespace/PVC with previous KubernetesStatus setting. If there is no previous information available, the checkbox will be grey out and cannot be clicked.

**Comment by yasker** [comment]
@smallteeths Backend is merged.

**Comment by meldafrawi** [comment]
**Validation: PASSED**

Steps to test:
  - In `Settings` page, make sure backup target is defined.

  - Backup Tests
    1- volume attached to pod, manual backup
      - Create a pvc with longhorn volume using: 
      kubectl apply -f https://raw.githubusercontent.com/rancher/longhorn/master/examples/pvc.yaml
      - Write some data to `/data` directory, and compute its md5 checksum.
      - In volume page, Cick create a backup
        - In backup labels section, try to add with `KubernetesStatus` or `RecurringJob` key
        >> Expected Result: fail to backup snapshot: specified snapshot backup labels contain reserved keyword

        - In backup labels modal, Click `Add Lables for Baclup`, and fill labels keys and values, then click OK.
        - In volume Backup page, click on labels tooltip
        >> Expected Result: specified lables in backup creation step should exist along with `KubernetesStatus` labels.


    2- volume attached to pod, recurring backup
      - Create a pvc with longhorn volume using: 
      kubectl apply -f https://raw.githubusercontent.com/rancher/longhorn/master/examples/pvc.yaml
      - Write some data to volume, and compute its md5 checksum.
      - in `Recurring Snapshot and Backup Schedule` set a schedule to create a backup for the volume
        1- try to add a label with add with `KubernetesStatus` or `RecurringJob` key
        >> Expected result: Can't set recurring backup schedule for volume.
	   unable to update volume recurring jobs for PVC_NAME specified snapshot backup labels contain reserved keyword LABEL_KEY

        2- set some labels for backup and click OK
        >> Expected result: backup will be created with specified lables in schedule creation step should exist along with `KubernetesStatus` and `RecurringJob` labels.


    3- volume attached to node, manual backup
      - Create a pvc with longhorn volume using: 
      kubectl apply -f https://raw.githubusercontent.com/rancher/longhorn/master/examples/pvc.yaml
      - Write some data to volume, and compute its md5 checksum.
      - In volume page, Cick create a backup
        - In backup labels section, try to add with `KubernetesStatus` or `RecurringJob` key
        >> Expected Result: fail to backup snapshot: specified snapshot backup labels contain reserved keyword

        - In backup labels modal, Click `Add Lables for Baclup`, and fill labels keys and values, then click OK.
        - In volume Backup page, click on labels tooltip
        >> Expected Result: specified lables in backup creation step should exist without any extra lables.


    4- volume attached to node, recurring backup
      - Create a pvc with longhorn volume using: 
      kubectl apply -f https://raw.githubusercontent.com/rancher/longhorn/master/examples/pvc.yaml
      - Write some data to volume, and compute its md5 checksum.
      - in `Recurring Snapshot and Backup Schedule` set a schedule to create a backup for the volume
        1- try to add a label with add with `KubernetesStatus` or `RecurringJob` key
        >> Expected result: Can't set recurring backup schedule for volume.
	   unable to update volume recurring jobs for PVC_NAME specified snapshot backup labels contain reserved keyword LABEL_KEY

        2- set some labels for backup and click OK
        >> Expected result: backup will be created with specified lables in schedule creation step should exist along with `RecurringJob` labels.

- Restore Tests:
  - Delete volume created at backup setup 1, 
  - From volume backups, under Operations click restore, set the Name to the original volume name,
  - wait the restore to complete, attach the volume to the node pod is deployed to.
  >> Expected Result: volume will be restored, attached to the pod, and be in healthy state
  - force recreation of the pod container using: `kubectl get pod volume-test -o json  | kubectl replace --force -f -`
  - access the pod and check /data directory
  >> Expected Result: you should find data written to /data directory and its checksum should match the checksum in backup tests step (1)

**Comment by yasker** [comment]
@meldafrawi Can you check if the PVC can be automatically refilled after restoration?

**Comment by meldafrawi** [comment]
Comment updated with additional checks.
