### ISSUE TITLE
[IMPROVEMENT] Only activate replica if it doesn't have deletion timestamp during volume engine upgrade

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5632]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

https://github.com/longhorn/longhorn-manager/pull/1795#issue-1635035355
https://github.com/longhorn/longhorn/issues/5618

**Comment by innobead** [comment]
@PhanLe1010 Please provide test steps for QA testing.

**Comment by PhanLe1010** [comment]
Test plan:

This race condition is very hard to trigger. Just make sure that our e2e test pass. Thanks QA

**Comment by roger-ryao** [comment]
**Verified on master-head 20230417**

- longhorn master-head ([4af6f26](https://github.com/longhorn/longhorn/commit/4af6f26acca9fea3e5bf58807f9099eaf48fcfba))
- longhorn-manager master-head ([b1b4fc0](https://github.com/longhorn/longhorn-manager/commit/b1b4fc0515ac34c43601c3c6503ac603e6ba9b54))

**The test steps**

1. https://github.com/longhorn/longhorn/issues/5632#issuecomment-1480285200

**Result Passed**
The results of most failures have already been recorded in https://github.com/longhorn/longhorn/issues/5460 and no failures related to engine upgrades were observed.

- [amd64](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/457/#showFailuresLink) : 7 failures 
- [arm64](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/446/#showFailuresLink)  :  5 failures 
- [amd64 upgrade test](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-2-stage-upgrade-tests-sles-amd64/147/#showFailuresLink) : 6 failures
- [arm64 upgrade test ](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-2-stage-upgrade-tests-sles-arm64/144/#showFailuresLink) : 5 failures
