### ISSUE TITLE
[TEST] Automating manual regression test cases

### ISSUE THREAD

**Issue by weizhe0422** [longhorn/longhorn#5638]
## What's the test to develop? Please describe

To reduce manual test case execution load, we should have a roadmap plan to increase e2e testing converted from manual regression test cases.

## Additional context

cc @longhorn/qa

**Comment by innobead** [comment]
All new cases should be based on the new framework @yangchiu is working on. Please cooperate with @khushboo-rancher and @yangchiu .

**Comment by khushboo-rancher** [comment]
We are tracking this task categories wise in various ticket. This ticket is no longer needed.
