### ISSUE TITLE
[0.5.0] Volumes attach but timeout on mounting

### ISSUE THREAD

**Issue by vitobotta** [longhorn/longhorn#564]
This is a follow up to a conversation had recently on Slack. I am seeing this very often also with 0.5.0: when for example scaling the deployment, deleting/recreating a pod or restoring, volumes attach according to the UI and the events for the pod but then time out on mounting with something like this:

```
Unable to mount volumes for pod "nextcloud-8c6bd7756-gjdbq_nextcloud(a2e2f0da-7a33-11e9-8a6c-960000267e3a)": timeout expired waiting for volumes to attach or mount for pod "nextcloud"/"nextcloud-8c6bd7756-gjdbq". list of unmounted volumes=[nextcloud-html nextcloud-data]. list of unattached volumes=[nextcloud-html nextcloud-data default-token-xn6qq]
```

In the manager's log I see this, not sure if it's relevant:

```
time="2019-05-19T12:43:13Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"nextcloud-data\", UID:\"269b2508-7a19-11e9-8a6c-960000267e3a\", APIVersion:\"longhorn.rancher.io/v1alpha1\", ResourceVersion:\"104817\", FieldPath:\"\"}): type: 'Normal' reason: 'Attached' volume nextcloud-data has been attached to master1"
E0519 12:43:13.424891       1 engine_controller.go:596] fail to update status for engine nextcloud-data-e-52bdb3b1: Operation cannot be fulfilled on engines.longhorn.rancher.io "nextcloud-data-e-52bdb3b1": the object has been modified; please apply your changes to the latest version and try again
```

It takes a **very** long time for it to fix by itself until the volumes are correctly mounted. 

Thanks

**Comment by ByJacob** [comment]
I have the similar issue. After create volume from rancher i cannot attach it. 


[longhorn-support-bundle_0539ab84-3509-11e9-b754-0201507d0508_2019-06-24T12-51-03Z.zip](https://github.com/longhorn/longhorn/files/3320879/longhorn-support-bundle_0539ab84-3509-11e9-b754-0201507d0508_2019-06-24T12-51-03Z.zip)

**Comment by yasker** [comment]
@ByJacob Thanks for attaching the support bundle. Can you also list the reproduce steps here?

**Comment by ByJacob** [comment]
Ok, it is my stem for reproduce it:
Rancher	v2.2.4
User Interface	v2.2.70
Helm	v2.10.0-rancher11
Machine	v0.15.0-rancher8-1
Longhorn V0.5.0

1 example - run cassandra instance from docker image:
- click Deploy
- docker image: cassandra:3.11.4
- Workload Type: Scalable deployment of 1 pod
- Volumes: Add a new persistent volume
-- Use a Storage Class to provision a new persistent volume
-- Storage Class: longhorn-static
-- Capacity 33 GiB
-- Mount Point: /var/lib/cassandra

2 example
- set longhorn-static for default
- try run cassandra from apps

Can you reproduce it ?

**Comment by yasker** [comment]
@ByJacob you need to use storage class `longhorn` instead of `longhorn-static`. The later doesn't come with provisioner and was used by Longhorn when users want to create PV/PVC with UI.

**Comment by ByJacob** [comment]
@yasker 
I have defined 2 storage class
`{
   "annotations":{
      "storageclass.beta.kubernetes.io/is-default-class":"true",
      "storageclass.kubernetes.io/is-default-class":"true"
   },
   "baseType":"storageClass",
   "created":"2019-03-19T07:21:24Z",
   "createdTS":1552980084000,
   "creatorId":null,
   "id":"longhorn",
   "labels":{
      "io.cattle.field/appId":"longhorn"
   },
   "links":{
      "persistentVolumes":"…/v3/cluster/c-rqknm/persistentVolumes?storageClassId=longhorn",
      "remove":"…/v3/cluster/c-rqknm/storageClasses/longhorn",
      "self":"…/v3/cluster/c-rqknm/storageClasses/longhorn",
      "update":"…/v3/cluster/c-rqknm/storageClasses/longhorn"
   },
   "name":"longhorn",
   "parameters":{
      "baseImage":"",
      "fromBackup":"",
      "numberOfReplicas":"3",
      "staleReplicaTimeout":"30"
   },
   "provisioner":"rancher.io/longhorn",
   "reclaimPolicy":"Delete",
   "type":"storageClass",
   "uuid":"9a7631a9-4a17-11e9-a0c1-0201507d0508",
   "volumeBindingMode":"Immediate"
}`

`{
   "allowVolumeExpansion":false,
   "annotations":{
      "storageclass.beta.kubernetes.io/is-default-class":"false",
      "storageclass.kubernetes.io/is-default-class":"false"
   },
   "baseType":"storageClass",
   "created":"2019-06-24T21:15:36Z",
   "createdTS":1561410936000,
   "creatorId":"user-9mzkw",
   "id":"longhorn-static",
   "labels":{
      "cattle.io/creator":"norman"
   },
   "links":{
      "persistentVolumes":"…/v3/cluster/c-rqknm/persistentVolumes?storageClassId=longhorn-static",
      "remove":"…/v3/cluster/c-rqknm/storageClasses/longhorn-static",
      "self":"…/v3/cluster/c-rqknm/storageClasses/longhorn-static",
      "update":"…/v3/cluster/c-rqknm/storageClasses/longhorn-static"
   },
   "name":"longhorn-static",
   "provisioner":"rancher.io/longhorn",
   "reclaimPolicy":"Delete",
   "type":"storageClass",
   "uuid":"35f71d32-96c5-11e9-a0c1-0201507d0508",
   "volumeBindingMode":"Immediate"
}`

and when i change storage class to `longhorn` i have the same problem

**Comment by ByJacob** [comment]
@yasker 
And when downgrade to version v0.4.1 all works correctly.

**Comment by yasker** [comment]
@ByJacob I don't think we have many changes in the driver between v0.4.1 and v0.5.0. If you encounter the issue again, can you send me the support bundle?

**Comment by yasker** [comment]
This should be fixed as a part of https://github.com/longhorn/longhorn/issues/1058.

Feel free to reopen the issue if it's not the case.
