### ISSUE TITLE
[FEATURE] Add status APIs for shallow copy and IO pause/resume

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5647]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Add status APIs for shallow copy and IO pause/resume. The information will be exported to management components and users.

The responses might be like
- shallow copy status
  - status: pending/in-progress/completed/failed/unknown
  - progress: unit in percentage 
- subsystem status
  - io: running/paused/stopped/...

## Describe the solution you'd like

A clear and concise description of what you want to happen

## Additional context

cc @DamiaSan @shuo-wu @LLParse @innobead

**Comment by DamiaSan** [comment]
This issue addresses development made in https://github.com/longhorn/longhorn/issues/5217 and https://github.com/longhorn/longhorn/issues/5421, that have PR actually under review
