### ISSUE TITLE
[TASK] Check and update the networking doc & example YAMLs

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#5651]
## What's the task? Please describe

Some entries in [the networking doc](https://longhorn.io/docs/1.4.1/references/networking/) are out-of-date. We need to update the doc for reference.

## Describe the items of the task (DoD, definition of done) you'd like

- [x] Check and update the entries in the doc.
- [x] Check and update [the NetworkPolicy examples](https://github.com/longhorn/longhorn/tree/master/examples/network-policy).
- [x] ~~May need to add a pre-release test plan of NetworkPolicy~~ No extra test or no change needed for existing tests. Re-running existing backing image related tests with the network policy is enough

## Additional context

https://github.com/longhorn/longhorn/discussions/3031

**Comment by yangchiu** [comment]
Verified passed by following steps:

1. Create rke/rke2 cluster, which uses canal as CNI
2. Install Longhorn
3. Apply network policies in https://github.com/longhorn/longhorn/pull/5785
4. Run test cases in `test_backing_image.py`, there's no abnormal failed test case
