### ISSUE TITLE
[BUG] Environment Check Script Fails To Perform All Checks

### ISSUE THREAD

**Issue by cskwrd** [longhorn/longhorn#5653]
## Describe the bug (🐛 if you encounter this issue)

The Environment Check Script appears to exit early before all checks have been performed.

## To Reproduce

1. `curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.4.1/scripts/environment_check.sh | bash`
2. Actual output:
    ```
    [INFO]  Required dependencies 'kubectl jq mktemp' are installed.
    [INFO]  Hostname uniqueness check is passed.
    [INFO]  Waiting for longhorn-environment-check pods to become ready (0/3)...
    [INFO]  All longhorn-environment-check pods are ready (3/3).
    [INFO]  Cleaning up longhorn-environment-check pods...
    [INFO]  Cleanup completed.
    ```

## Expected behavior

All checks performed and output indicates actual environment state.

## Log or Support bundle

`N/A`

## Environment

 - Longhorn version: `v1.4.1`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): `N/A`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: `K3s` `v1.25.7+k3s1`
   - Number of management node in the cluster: `1`
   - Number of worker node in the cluster: `2`
 - Node config
   - OS type and version: Both latest snapshots, `openSUSE Tumbleweed` and `openSUSE Micro OS`
   - CPU per node: `N/A`
   - Memory per node: `N/A`
   - Disk type(e.g. SSD/NVMe): `N/A`
   - Network bandwidth between the nodes: `N/A`
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): `Baremetal`
 - Number of Longhorn volumes in the cluster: `N/A`

## Additional context

I spent some time trying to debug the script. All checks seem to run and produce output when I modify the script in the following ways:
* Insert `set -E` at line 2
* Add an error handling function before _Main logics_.
* Insert `trap  '__error_handing__ $? $LINENO' ERR` before `trap cleanup EXIT`
After the modifications above the script cannot be run successfully when piped into `bash` as done in the docs (because of the error handling code). When called directly (ex: `./check_script.sh`) errors are handled, and it appears that all checks are performed.

I am seeing the same results on a host where `iscsid` is not yet running, as well as, one where Longhorn is already operating without issue.

### Modified Script (extension changed because GitHub disallows `.sh`)
[modified_environment_check.txt](https://github.com/longhorn/longhorn/files/11052396/modified_environment_check.txt)

**Comment by cskwrd** [comment]
@derekbit 

I don't have a fix. I am not really sure what the problem is, nor do I know if the modifications I made really help in any way.

I provided my modifications in hopes that someone with more bash scripting experience can understand `environment_check.sh` and the modifications I made to the script, and discern what needs doing.

I could move my modifications into a PR, but like I said in the ticket, the inclusion of my modifications just results in errors related to the error handling code I added when the script is piped into `bash` so they wouldn't help when the script is used as documented on the docs site.

**Comment by PhanLe1010** [comment]
### Test steps:

Running the check script by `curl -sSfL <link to the script>` and verify that it performs all the check similar to the test at  https://github.com/longhorn/longhorn/pull/6909#issuecomment-1765357894

**Comment by khushboo-rancher** [comment]
The backported issue for 1.3.4 is not created by the bot. @roger-ryao Could you please take care of this when validating the issue?

**Comment by roger-ryao** [comment]
**Verified on master-head 20231020**

- longhorn master-head https://github.com/longhorn/longhorn/commit/15fae1ba47fa2d73bad045307cdb33ed3c25f233


**The test steps**

https://github.com/longhorn/longhorn/issues/5653#issuecomment-1765365063

**Result Passed**

- [x] All checks have been performed.
- [x] Update the example result messages for using the Environment Check Script on website
  - https://github.com/longhorn/website/pull/788


```console
> curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/master/scripts/environment_check.sh | bash
[INFO]  Required dependencies 'kubectl jq mktemp sort printf' are installed.
[INFO]  All nodes have unique hostnames.
[INFO]  Waiting for longhorn-environment-check pods to become ready (0/3)...
[INFO]  All longhorn-environment-check pods are ready (3/3).
[INFO]  MountPropagation is enabled
[INFO]  Checking kernel release...
[INFO]  Checking iscsid...
[INFO]  Checking multipathd...
[INFO]  Checking packages...
[INFO]  Checking nfs client...
[INFO]  Cleaning up longhorn-environment-check pods...
[INFO]  Cleanup completed.
```
