### ISSUE TITLE
[IMPROVEMENT] Clean up backup target if the backup target setting is unset

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5655]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The backup target should be cleaned up if the backup target setting is unset. The floating mount point might introduce system instability such as high CPU loading when the backup server is gone.

Although we have a ticket for cleaning up the unused mountpoints https://github.com/longhorn/longhorn/issues/5391, but the unset of backup target setting is not covered. Moreover, it is better to let the backup target controller handle the orphaned mount point cleanup.

## Additional context

cc @shuo-wu @innobead 

---

## Note

We handled longhorn-manager pod mount point in backup-target-controller in this ticket
For IM-R pod mount point, it will be handled in the next ticket.

**Comment by ChanYiLin** [comment]
We would also need a way for manager(controller) to ask IM-R to unmount the mount point as well

**Comment by ChanYiLin** [comment]
Hi @innobead 
Here is the current situation summary (with @derekbit and my PR)

First of all, **there will always be one mount point** 
Secondly, for unmounting, 
- longhorn-manager:
    - unmount when the URL is unset (my PR)
- IM-R:
    - unmount other mount points and mount the current setting when the replica builds backup (@derekbit PR)
        - if the mount point is the same, do nothing
    - mount point will still remain after the user unset the URL (not handled now)

To address IM-R mount point issue, we might need to
- add a grpc for the manager to ask IM-R to clean up the mount point

What do you think? Thanks!

**Comment by ChanYiLin** [comment]
I found it quite hard for adding a new grpc method

What we want is IM-R pod to unmount the mount point,
but I trace the grpc part, most scenarios need an engine first
longhorn-manager ->  get volume and its engineClientProxy -> send grpc request -> find replica for this engine -> ask replica to do the task
It might have the chance that users haven't created any volume and there is no engine running?

Personally, I think it requires lots of effort for a comparably small improvement, especially since we are assured there is only one mount point at a time.

cc @derekbit

**Comment by derekbit** [comment]
How about adding in the instance-manager grpc?

**Comment by innobead** [comment]
> I found it quite hard for adding a new grpc method
> 
> 
> 
> What we want is IM-R pod to unmount the mount point,
> 
> but I trace the grpc part, most scenarios need an engine first
> 
> longhorn-manager ->  get volume and its engineClientProxy -> send grpc request -> find replica for this engine -> ask replica to do the task
> 
> It might have the chance that users haven't created any volume and there is no engine running?
> 
> 
> 
> Personally, I think it requires lots of effort for a comparably small improvement, especially since we are assured there is only one mount point at a time.
> 
> 
> 
> cc @derekbit 

Thanks @ChanYiLin for the detailed  info.

The remaining only one mount point for instance manager r can be regarded as intended side effect, especially we only support one backup target now.

We can resolve this issue for now (probably need to update the subject to make it clear) but make this leftover case to tackle later when need to deal with multiple backup store support if needed. Let's create another issue for that. WDYT?

**Comment by derekbit** [comment]
> @derekbit Would the leftover one invalid mount point be resource usage concerns?

I think it is fine, because we already have a cleanup in backupstore.

**Comment by ChanYiLin** [comment]
Ok, then I will create another issue to track the issue of mount point remaining in IM-R after Target is unset.

**Comment by innobead** [comment]
https://github.com/longhorn/longhorn/issues/5411

**Comment by ChanYiLin** [comment]
I have create the issue: #5741
