### ISSUE TITLE
[BUG] Backup monitor gets stuck in an infinite loop if backup isn't found

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5662]
## Describe the bug (🐛 if you encounter this issue)

When creating a backup, backup controller issues a backup task to the engine. Since the backup store is mounted in `soft` mode, the backup task cannot be created and will not infinitely retry if the backup store is unreachable. Afterward, the backup monitor periodically gets the following information from the engine but the `err` is `nil`. As a result, the backup monitor is unaware of the error and keeps getting status. ([code](https://github.com/longhorn/longhorn-manager/blob/master/engineapi/backup_monitor.go#L236)).
```
backup=backup-3fdfaaf705084449 recv=&{0  Failed to get backup status on tcp://10.42.3.9:10000 for backup-3fdfaaf705084449: rpc error: code = Unknown desc = backup not found backup-3fdfaaf705084449   tcp://10.42.3.9:10000}, err=<nil>
```

## To Reproduce

3. Perform '....'

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.3.3, v1.4.2 and master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by derekbit** [comment]
Additionally, the error handling in backup monitor is somewhat messy, especially the mixing of `backupStatus.Error` and `err`. Need to refactor this part when refactoring backup monitor.

**Comment by derekbit** [comment]
e2e
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3398/

**Comment by chriscchien** [comment]
Verified in longhorn master (longhorn-manager `296116`, longhorn-engine `7f1c1a`, backupstore `f71b33`, longhorn-instance-manager `c6ea13`) with test [steps](https://github.com/longhorn/longhorn/issues/5662#issuecomment-1487846663)
Result **Pass**

Backup will change to error state within 5~30 minutes if backupstore is unreachable while backup is in progress
