### ISSUE TITLE
Performance issues with backup/restores

### ISSUE THREAD

**Issue by vitobotta** [longhorn/longhorn#567]
I have been testing the backup/restore functionality with 0.5.0, and while both backups and restores work as expected, both operations seem to run slower than expected. For example, backing up and restoring a volume with some 25 GB of data took around 18-20 minutes using Velero with Restic. Backing up and restoring exactly the same data and on the same server but with Longhorn took over 40 minutes. The backup target was the same Wasabi dc. I have repeated this a few times with similar results each time. In each case I configured one replica only, but when restoring with Longhorn it creates anyway two replicas (see #562). Also, if no much data has changed since the last backup, Velero/Restic backup does a very quick incremental backup. In the case of Longhorn, it still takes around 15 minutes with the same data.

I would expect both backups and restores to take more or less as long as Restic does when dealing with the same data, same server, same connection etc.

Thanks!

**Comment by yasker** [comment]
@vitobotta I think it's the two replica setup result in the longer restoration time. Also, as long as the snapshot used for the last backup still exists, Longhorn should perform an incremental backup as well,  which should be very fast.

I just double checked v0.5.0, seems there is a bug preventing the incremental backup from working properly. The replica reports `Cannot find the last snapshot in local storage, would process with full backup`, which shouldn't be the case.

**Comment by vitobotta** [comment]
Thanks @yasker :)
