### ISSUE TITLE
[IMPROVEMENT] Support the support bundle agent fault tolerant regardless of OS distro when collecting Longhorn logs

### ISSUE THREAD

**Issue by weizhe0422** [longhorn/longhorn#5670]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The [support bundle collector](https://github.com/rancher/support-bundle-kit/blob/master/hack/support-bundle-collector.sh) and the [`collector-longhorn.sh`](https://github.com/rancher/support-bundle-kit/blob/master/hack/collector-longhorn) should do their best to be fault-tolerant rather than terminating on exceptions, e.g. continue to the next collection of items even if the file doesn't exist.

## Additional context

https://github.com/longhorn/longhorn/issues/5513#issuecomment-1484472761

**Comment by chriscchien** [comment]
Verified in longhorn master `ccf9f3` and longhornio/support-bundle-kit:`v0.0.22` with test [steps](https://github.com/longhorn/longhorn/issues/5670#issuecomment-1486474327)
Result **Pass**

Follow test steps, support bundle download success
