### ISSUE TITLE
[BUG] Volumes are in attaching in lonhgorn forever and not mounting to the pods

### ISSUE THREAD

**Issue by rajeevpadinharepattu** [longhorn/longhorn#5676]
## Describe the bug (🐛 if you encounter this issue)

After installing longhorn in the cluster using helm, all volumes are getting in to attaching state in lonhgorn UI forever and not mounting to the pods. 

All longhorn pods are up and running.
[longhorn-support-bundle_8dc493c2-4f1c-41c4-a479-37565595c9ca_2023-03-28T11-26-15Z.zip](https://github.com/longhorn/longhorn/files/11088791/longhorn-support-bundle_8dc493c2-4f1c-41c4-a479-37565595c9ca_2023-03-28T11-26-15Z.zip)

adminlinux@jyoti-illustraai:~$ kubectl get pods -n longhorn-system
NAME                                        READY   STATUS    RESTARTS   AGE
csi-attacher-5f46994f7-5ghz5                1/1     Running   0          90m
csi-attacher-5f46994f7-79m86                1/1     Running   0          90m
csi-attacher-5f46994f7-vn68r                1/1     Running   0          90m
csi-provisioner-6ccbfbf86f-74jdj            1/1     Running   0          90m
csi-provisioner-6ccbfbf86f-jhj5q            1/1     Running   0          90m
csi-provisioner-6ccbfbf86f-m27cq            1/1     Running   0          90m
csi-resizer-6dd8bd4c97-6q96t                1/1     Running   0          90m
csi-resizer-6dd8bd4c97-8bf2v                1/1     Running   0          90m
csi-resizer-6dd8bd4c97-kd9h9                1/1     Running   0          90m
csi-snapshotter-86f65d8bc-6tvsw             1/1     Running   0          90m
csi-snapshotter-86f65d8bc-fqwwh             1/1     Running   0          90m
csi-snapshotter-86f65d8bc-jh97v             1/1     Running   0          90m
engine-image-ei-4dbdb778-p8pw6              1/1     Running   0          90m
instance-manager-e-e61ef47c                 1/1     Running   0          90m
instance-manager-r-b1d8eb2e                 1/1     Running   0          90m
longhorn-csi-plugin-b9cpj                   2/2     Running   0          90m
longhorn-driver-deployer-6bc898bc7b-scvlm   1/1     Running   0          90m
longhorn-manager-l56wt                      1/1     Running   0          90m
longhorn-ui-84f97cf569-sdlk2                1/1     Running   0          90m

## To Reproduce

Install longhorn 1.24 version in to kuberentes cluster

## Log or Support bundle

Attached the support bundle.

adminlinux@jyoti-illustraai:~$

## Environment
 - Longhorn version: Version: 1.2.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 0
 - Node config
   - OS type and version: Ubuntu
   - CPU per node: 20
   - Memory per node: 64G
   - Disk type(e.g. SSD/NVMe): NVMe
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetel
 - Number of Longhorn volumes in the cluster: 8

**Comment by mantissahz** [comment]
Hi @rajeevpadinharepattu 
I saw the logs of longhorn-manager in the support bundle
```txt
2023-03-28T11:26:00.481188209Z time="2023-03-28T11:26:00Z" level=warning msg="Error syncing Longhorn instance manager longhorn-system/instance-manager-e-e61ef47c: fail to sync instance manager for longhorn-system/instance-manager-e-e61ef47c: failed to get version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.244.0.14:8500: connect: no route to host\""
2023-03-28T11:26:02.497270830Z time="2023-03-28T11:26:02Z" level=warning msg="Error syncing Longhorn instance manager longhorn-system/instance-manager-r-b1d8eb2e: fail to sync instance manager for longhorn-system/instance-manager-r-b1d8eb2e: failed to get version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.244.0.15:8500: connect: no route to host\""
```

Could you check your network setting or turn off the `firewalld`?

**Comment by rajeevpadinharepattu** [comment]
@mantissahz  This was becouse of some network issues, and can be closed.

**Comment by derekbit** [comment]
To improve the debugging process and UX, it would be nice that the error is recorded in the `instancemanager.spec.conditions`.

cc @mantissahz @innobead
