### ISSUE TITLE
engine: Incremental backup wasn't working properly

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#568]
Version v0.5.0.

Reported by https://github.com/rancher/longhorn/issues/567

Reproduce steps:
1. Create a volume with 1 replica. Format and mounted to a node.
2. Write a 1G file to it.
3. Backup the volume.
4. Wait for volume backup to complete. Backup the volume again.
5. Check the replica log, it shows:
> time="2019-05-20T09:28:23Z" level=debug msg="Cannot find last snapshot in local storage, would process with full backup" object=snapshot pkg=backupstore reason=fallback snapshot= volume=test2

It shouldn't since the last snapshot still exists.

We also need to find a way to validate the incremental backup to the engine test and manager integration test.

**Comment by meldafrawi** [comment]
fixed.
