### ISSUE TITLE
[FEATURE] Introduce a new disk type, disk management and replica scheduler for SPDK volumes

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5683]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Current state-of-the-art volumes are based on sparse files on formatted filesystems, and the replica scheduler is designed accordingly. However, for SPDK volumes, which utilize dedicated block devices on hosts, a different disk type, disk management and replica scheduler are required.

## Describe the solution you'd like

A clear and concise description of what you want to happen

**Comment by innobead** [comment]
cc @shuo-wu @DamiaSan

**Comment by shuo-wu** [comment]
Yes. Besides, the way Longhorn monitors the disk should change as well.
Previously, Longhorn just needs to check the mount point. For SPDK, it needs to check the original block device + SPDK bdev aio + SPDK lvstore

**Comment by roger-ryao** [comment]
**Verified on v1.5.0-rc1 20230605**

- longhorn v1.5.0-rc1 https://github.com/longhorn/longhorn/commit/5adcc7fc6a7a4c95ab8b5df6e2ee690e64418e9f

**The test steps**
Check by the steps in https://longhorn.io/docs/1.5.0/spdk/quick-start/


**Result**
1. We can create a Pod that uses Longhorn volumes using the SPDK Data Engine.
2. We can create a volume on the Longhorn UI and then create a Pod using that volume.
3. SPDK volumes cannot have their replica number changed.
4. We can write data into the SPDK volume, but the Actual Size always shows 0 bytes.
5. After we delete a replica, it does not rebuild.
6. We need to configure [Huge Pages](https://longhorn.io/docs/1.5.0/spdk/quick-start/#configure-kernel-modules-and-huge-pages) on the `control node`. The symptom also described by @Yangchiu in the https://github.com/longhorn/longhorn/issues/5739#issuecomment-1576124269

We need confirmation from @Derek @shuo-wu  whether this behavior is expected or not.


[supportbundle_8b6c3787-3c94-45f5-9f0c-3d7524f7207c_2023-06-05T09-35-34Z.zip](https://github.com/longhorn/longhorn/files/11651017/supportbundle_8b6c3787-3c94-45f5-9f0c-3d7524f7207c_2023-06-05T09-35-34Z.zip)

**Comment by innobead** [comment]
> 3. SPDK volumes cannot have their replica number changed.
> 4. We can write data into the SPDK volume, but the Actual Size always shows 0 bytes.
> 5. After we delete a replica, it does not rebuild.
> 6. We need to configure [Huge Pages](https://longhorn.io/docs/1.5.0/spdk/quick-start/#configure-kernel-modules-and-huge-pages) on the `control node`. The symptom also described by @yangchiu in the [[FEATURE] Deployment manifests for helping install SPDK dependencies, utilities and libraries #5739 (comment)](https://github.com/longhorn/longhorn/issues/5739#issuecomment-1576124269)
> 
> We need confirmation from @derek @shuo-wu whether this behavior is expected or not.

@derekbit Suggest adding a limitation section to https://longhorn.io/docs/1.5.0/spdk/ to emphasize most of the volume operations not supported in this version but are planned to add in the next version, WDYT?

cc @shuo-wu

**Comment by derekbit** [comment]
Hmm，we have mentioned the functionalities that are supported. Do we still a negative list?

**Comment by innobead** [comment]
> Hmm, we have mentioned the functionalities that are supported. Do we still a negative list?

Yeah, this is what I think, or probably add a brief statement instead of a specific limitation section like `In addition to the supported items mentioned above, all other functions will be introduced in the future version like replica number change, replica online rebuilding, etc`. WDYT?

**Comment by derekbit** [comment]
> **Verified on v1.5.0-rc1 20230605**
> 
> 
> 
> - longhorn v1.5.0-rc1 https://github.com/longhorn/longhorn/commit/6b62e767b37792b65f553689514fa3f7f3a24186
> 
> 
> 
> **The test steps**
> 
> Check by the steps in https://longhorn.io/docs/1.5.0/spdk/quick-start/
> 
> 
> 
> 
> 
> **Result**
> 
> 1. We can create a Pod that uses Longhorn volumes using the SPDK Data Engine.
> 
> 2. We can create a volume on the Longhorn UI and then create a Pod using that volume.
> 
> 3. SPDK volumes cannot have their replica number changed.

Expected 

> 
> 4. We can write data into the SPDK volume, but the Actual Size always shows 0 bytes.

Expected. We cannot get the actual size for now.

cc @DamiaSan 

> 
> 5. After we delete a replica, it does not rebuild.

Expected
> 
> 6. We need to configure [Huge Pages](https://longhorn.io/docs/1.5.0/spdk/quick-start/#configure-kernel-modules-and-huge-pages) on the `control node`. The symptom also described by @Yangchiu in the https://github.com/longhorn/longhorn/issues/5739#issuecomment-1576124269


For this version, yes, huge pages are required in all nodes. 
> 
> 
> 
> We need confirmation from @Derek @shuo-wu  whether this behavior is expected or not.
> 
> 
> 
> 
> 
> [supportbundle_8b6c3787-3c94-45f5-9f0c-3d7524f7207c_2023-06-05T09-35-34Z.zip](https://github.com/longhorn/longhorn/files/11651017/supportbundle_8b6c3787-3c94-45f5-9f0c-3d7524f7207c_2023-06-05T09-35-34Z.zip)
> 
>

**Comment by derekbit** [comment]
@roger-ryao The doc is updated in https://github.com/longhorn/website/pull/723. Please help check it, thank you,

**Comment by roger-ryao** [comment]
After reviewing https://github.com/longhorn/website/pull/723, close this ticket.
