### ISSUE TITLE
dashboard 504 error[BUG]

### ISSUE THREAD

**Issue by fecet** [longhorn/longhorn#5685]
# Bug Report: Longhorn Dashboard Not Loading Content and Displaying HTTP Error

## Description
Longhorn dashboard fails to display any content and remains in the loading state. The error message indicates an HTTP error. Other components of Longhorn, including PV and PVC, are functioning normally.

## Steps to Reproduce
1. Access the Longhorn dashboard.
2. The dashboard remains in the loading state and does not display any content.
3. The HTTP error message is displayed.

## Expected Result
The Longhorn dashboard should display content without any errors.

## Actual Result
The Longhorn dashboard remains in the loading state and displays an HTTP error.

## System Information
- Longhorn version:latest (1.4.1)
- Operating system: Ubuntu 20.04

## Additional Information
- Other components of Longhorn, including PV and PVC, are functioning normally.
- The issue persists even after restarting Longhorn and the system.
- No changes were made to the system or Longhorn configuration before the issue occurred.

## Screenshot or Error Message
![image](https://user-images.githubusercontent.com/41792945/228877408-3e6591cf-749d-4295-9f7f-7d1dea44ff65.png)
![image](https://user-images.githubusercontent.com/41792945/228877574-d05d323c-c350-490e-9eef-5a978f667f77.png)
![image](https://user-images.githubusercontent.com/41792945/228877806-1235893d-8670-417d-a4c2-fbe7293d118b.png)
Note that those pvc with storage class name "longhorn" works well

## Impact
The inability to access the Longhorn dashboard limits the ability to manage and monitor Longhorn volumes and snapshots, which could impact the overall availability and reliability of the system.

**Comment by fecet** [comment]
Use calico as the cluster network plugin and no other special configuration

**Comment by mantissahz** [comment]
@fecet are all pages not accessible?
Could you help me check the logs of longhorn-ui or longhorn-manager if there is any abnormal log or provide the support bundle?

**Comment by fecet** [comment]
I'm having trouble locating logs in kubectl. Could you please provide me with instructions on how to find the relevant logs?

**Comment by fecet** [comment]
I have noticed some error messages in the log of longhorn-manager that I had previously overlooked. Specifically, messages such as:

time="2023-04-02T10:37:01Z" level=error msg="unable to schedule replica" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=weatherlight owner=weatherlight replica=pvc-8b69693a-b5c6-4946-85f1-08c4bd2d246e-r-9320f8ca state=attached volume=pvc-8b69693a-b5c6-4946-85f1-08c4bd2d246e

I apologize for not noticing these messages earlier. I am grateful for your assistance in helping me to resolve any issues that may be causing these errors.

At the same time, I have not seen any error messages in longhorn-ui, only this one:

nginx: [warn] duplicate MIME type "text/html" in /var/config/nginx/nginx.conf:7

Thank you for your help and sorry again for any inconvenience caused by these errors.

**Comment by fecet** [comment]
The full error message in longhorn-manager is like
time="2023-04-02T10:36:31Z" level=debug msg="Found 0 node has at least one schedulable disk" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=weatherlight owner=weatherlight state=attached volume=pvc-8b69693a-b5c6-4946-85f1-08c4bd2d246e
time="2023-04-02T10:36:31Z" level=error msg="There's no available disk for replica pvc-8b69693a-b5c6-4946-85f1-08c4bd2d246e-r-da2ac8a2, size 1073741824"
time="2023-04-02T10:36:31Z" level=error msg="unable to schedule replica" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=weatherlight owner=weatherlight replica=pvc-8b69693a-b5c6-4946-85f1-08c4bd2d246e-r-da2ac8a2 state=attached volume=pvc-8b69693a-b5c6-4946-85f1-08c4bd2d246e
time="2023-04-02T10:36:31Z" level=error msg="There's no available disk for replica pvc-8b69693a-b5c6-4946-85f1-08c4bd2d246e-r-9320f8ca, size 1073741824"
time="2023-04-02T10:36:31Z" level=error msg="unable to schedule replica" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=weatherlight owner=weatherlight replica=pvc-8b69693a-b5c6-4946-85f1-08c4bd2d246e-r-9320f8ca state=attached volume=pvc-8b69693a-b5c6-4946-85f1-08c4bd2d246e

**Comment by mantissahz** [comment]
Apologies for the late reply.
Is the firewall of your cluster nodes turned on?
Could you use this command `kubectl -n longhorn-system get endpoints| grep longhorn-backend'?
And use the first url ex: 10.42.0.10:9500 to test the backend APIs by this command `curl http://[url]/v1`

**Comment by fecet** [comment]
A complete reinstallation solved the problem.

**Comment by bono5150** [comment]
k3s cluster (1 control-plane, 3 agent nodes) with longhorn installed on node host disk (NVMe). A lot of 504 errors.
I can guess only it is useless without additional NVMe disks attached to host for longhorn usage only.

time="2025-02-11T17:56:40Z" level=warning msg="HTTP handling error" func=api.NewRouter.HandleError.func168 file="router.go:21" error="write tcp [fd0f:73c6:d3ae:1030:784d:67dd:1:79b3]:9500->[fd0f:73c6:d3ae:1030:784d:67dd:1:aecf]:51284: write: broken pipe"
2025/02/11 17:56:40 http: response.WriteHeader on hijacked connection from github.com/longhorn/longhorn-manager/api.writeErr (router.go:34)
2025/02/11 17:56:40 http: response.Write on hijacked connection from github.com/rancher/go-rancher/api.(*HtmlWriter).Write (html_writer.go:44)
time="2025-02-11T17:56:40Z" level=error msg="Failed to write error write tcp [fd0f:73c6:d3ae:1030:784d:67dd:1:79b3]:9500->[fd0f:73c6:d3ae:1030:784d:67dd:1:aecf]:51284: write: broken pipe" func=api.writeErr file="router.go:44" error="http: connection has been hijacked"
2025/02/11 17:57:57 http: proxy error: context canceled
127.0.0.1 - - [11/Feb/2025:17:56:27 +0000] "POST /v1/backuptargets/default?action=backupTargetUpdate HTTP/1.1" 502 0 "http://localhost:8083/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:134.0) Gecko/20100101 Firefox/134.0"
time="2025-02-11T18:01:28Z" level=info msg="Request (user: system:serviceaccount:longhorn-system:longhorn-service-account, longhorn.io/v1beta2, Kind=BackupTarget, namespace: longhorn-system, name: default, operation: UPDATE) patchOps: [{\"op\": \"replace\", \"path\": \"/metadata/finalizers\", \"value\": [\"longhorn.io\"]}]" func="admission.(*Handler).admit" file="admission.go:115" service=admissionWebhook
