### ISSUE TITLE
Longhorn-manager pod fails to start on a specific node with error "require support-bundle-manager-image"

### ISSUE THREAD

**Issue by tlymki** [longhorn/longhorn#5689]
**Describe the bug**
I have a Kubernetes cluster with Longhorn installed. Recently, I added a new node to the cluster, and the longhorn-manager pod fails to start on this node, showing the following error message:
`level=fatal msg="Error starting manager: require support-bundle-manager-image"`

The Longhorn manager is working fine on the other nodes in the cluster. I've set the `SUPPORT_BUNDLE_MANAGER_IMAGE` environment variable in the Longhorn manager DaemonSet, but the issue persists.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a new node to the existing Kubernetes cluster with Longhorn installed.
2. Wait for the longhorn-manager pod to start on the new node.
3. Check the logs of the longhorn-manager pod on the new node and observe the error message.

**Expected behaviour**
The longhorn-manager pod should start without errors on the new node.

**Log**
The only error message in the longhorn-manager pod logs is:
`level=fatal msg="Error starting manager: require support-bundle-manager-image"`

**Environment:**
 - Longhorn version: longhornio/longhorn-manager:master-head
 - Kubernetes version: 1.21.14
 - Node OS type and version:  Ubuntu 20.04 ( new node), Ubuntu 18.04 and Centos 7 ( old nodes )
 - Docker version: 20.10.21
 - CNI calico

**Additional context**
- No custom configurations for the Longhorn manager DaemonSet.
- The issue occurs only on the newly added node. Longhorn is working fine on the other nodes in the cluster.

I understand that the problem is related to the new node, but I cannot figure out the root cause of the error in longhorn-manager pod.

Please let me know if there's any additional information needed or if there are any other troubleshooting steps I should try. Thanks in advance for your help!

**Comment by mantissahz** [comment]
@tlymki could you show the `daemonset` information by `kl get daemonset longhorn-manager -o yaml`?
In spec.containers.command:
```txt
- --support-bundle-manager-image
- longhornio/support-bundle-kit:v0.0.20
```
Did you install Longhorn by `kubectl`?

**Comment by tlymki** [comment]
@mantissahz Thank you for your response.  Here is the part  spec.container of the current daemonset:
`    containers:
        - name: longhorn-manager
          image: longhornio/longhorn-manager:master-head
          command:
            - longhorn-manager
            - '-d'
            - daemon
            - '--engine-image'
            - longhornio/longhorn-engine:master-head
            - '--instance-manager-image'
            - longhornio/longhorn-instance-manager:v1_20220303
            - '--share-manager-image'
            - longhornio/longhorn-share-manager:v1_20211020
            - '--backing-image-manager-image'
            - longhornio/backing-image-manager:v2_20210820
            - '--manager-image'
            - longhornio/longhorn-manager:master-head
            - '--service-account'
            - longhorn-service-account
          ports:
            - name: manager
              containerPort: 9500
              protocol: TCP
`

Longhorn was install with helm longhorn-1.3.0-dev chart.

**Comment by mantissahz** [comment]
It seems the new node got the newest master-head image and it is the 1.5.0-dev and it contains some new features including 'support-bundle-kit' that 1.3.0-dev does not.
you might need to change the 'master-head' image to 'v1.3.2' or 'v1.3.x-head'.

**Comment by tlymki** [comment]
@mantissahz Thank you very much, indeed the problem was so simple and the new node just used the latest image ( with master-head tag ) that needed a bundle-kit.
