### ISSUE TITLE
Attach failed for volume

### ISSUE THREAD

**Issue by tiger0425** [longhorn/longhorn#569]
*Describe your issue here*
AttachVolume.Attach failed for volume "pvc-ea952885-707a-11e9-bfc0-005056b4b2af" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to attach volume pvc-ea952885-707a-11e9-bfc0-005056b4b2af to rancher016: Node to be attached rancher016 is different from previous spec rancher013] from [http://longhorn-backend:9500/v1/volumes/pvc-ea952885-707a-11e9-bfc0-005056b4b2af?action=attach]
---
Version: `v0.4.1`

**Comment by yasker** [comment]
@tiger0425 Can you describe the steps to reproduce the issue? It seems due to an attempt to attach already attached volume.

**Comment by tiger0425** [comment]
yes,  I migrated pods to other node,    volume no attached

**Comment by tiger0425** [comment]
Restart rancher cluster after power outage，volumn no attached

**Comment by tiger0425** [comment]
State:Detached
Health:
Frontend:Block Device
Attached Node & Endpoint :
Size:200 Gi
Actual Size:0 Bi
Base Image:
Engine Image:rancher/longhorn-engine:v0.4.1
Created:15 days ago
Latest Backup:

**Comment by yasker** [comment]
How did you migrate the pods? Can you list the steps that we may able to reproduce the issue?

**Comment by tiger0425** [comment]
Thank you. I've dealt with this myself. I moved the pod to the NODE where the storage is located.

**Comment by yasker** [comment]
@tiger0425 Glad that you get it solved.

Though I am still a little confused on how did you `move/migrate` the pod?
