### ISSUE TITLE
[FEATURE] Node replication throttling

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [longhorn/longhorn#5692]
The use-case here- I run a cluster with mixed 1G and 10GBe networking. I will assume, you will find lots of home users also using 1GBe networking.

The problem- when heavy replication occurs, say, when a node goes down and replicas are rebuilt- this traffic can completely saturate the network connection causing connectivity issues with kubernetes.

This will eventually result in the node being considered down, causing a snowball effect which makes the issue worse.

The ask- the ability to set a bandwidth limit on either the node level.

For anyone else having this issue, I have found a work-around which does seem to work very well.

```
// Nodes with 10GBe.
kubectl annotate pods -l longhorn.io/component=instance-manager -l longhorn.io/node=kube01 kubernetes.io/ingress-bandwidth=8G kubernetes.io/egress-bandwidth=8G
kubectl annotate pods -l longhorn.io/component=instance-manager -l longhorn.io/node=kube03 kubernetes.io/ingress-bandwidth=8G kubernetes.io/egress-bandwidth=8G
kubectl annotate pods -l longhorn.io/component=instance-manager -l longhorn.io/node=kube04 kubernetes.io/ingress-bandwidth=8G kubernetes.io/egress-bandwidth=8G

// Nodes with 1GBe.
kubectl annotate pods -l longhorn.io/component=instance-manager -l longhorn.io/node=kube05 kubernetes.io/ingress-bandwidth=500M kubernetes.io/egress-bandwidth=250M
kubectl annotate pods -l longhorn.io/component=instance-manager -l longhorn.io/node=kube06 kubernetes.io/ingress-bandwidth=500M kubernetes.io/egress-bandwidth=250M
```

Not a perfect solution- but, since implementing, I have not had an issue with nodes dropping from the cluster.

**Comment by robcaulk** [comment]
Would love to see this feature. We also see issues with replicas saturating bandwidth. But in addition to replicas, we would like to throttle scheduled backups.

**Comment by XtremeOwnageDotCom** [comment]
> @XtremeOwnageDotCom regarding your workaround, are you using Calico to enforce these labels?

Honestly, I cannot recall which CNI I was using at that time. I believe it was calico. But, I cannot confirm.

**Comment by jurgenweber** [comment]
Yeah, my problem isn't network bandwidth but DISK I/O or I/O wait. It sky rockets and eventually Longhorn times out and we just end up in an infinite loop of attempting to replicate replicas.

Setting Concurrent Replica Rebuild Per Node Limit to 3 (from 5) helped a little bit but I will try this and see if it helps. I don't need it to happen fast, just happen. I don't care how long it takes. One PVC seems to be a problem because its 25GB (the rest are quite small).

**Comment by innobead** [comment]
cc @ejweber @derekbit @shuo-wu

**Comment by jurgenweber** [comment]
IN the end I ended up removing these annotations and set Concurrent Replica Rebuild Per Node Limit to 1, got me out of my bind.

**Comment by derekbit** [comment]
Controlling the traffic during replica rebuilding involves two key factors:

1. The number of concurrent replica rebuilds.
2. The network bandwidth used by replica rebuilding.

The first factor is managed by the global setting `Concurrent Replica Rebuild Per Node Limit`, which limits the number of simultaneous rebuilds per node. The second factor involves throttling the total throughput of replica rebuilding on a node. All the background IO such as delta rebuilding, backup, restore, and snapshot hashing should be able to be throttled.
Related ticket: https://github.com/longhorn/longhorn/issues/4765

**Comment by derekbit** [comment]
related to https://github.com/longhorn/longhorn/issues/4765

**Comment by derekbit** [comment]
In favor of https://github.com/longhorn/longhorn/issues/4765
