### ISSUE TITLE
LONGHORN VOLUME REMAIN DEGRADED

### ISSUE THREAD

**Issue by Ronit1135** [longhorn/longhorn#5699]
## Describe the bug (🐛 if you encounter this issue)
so i created two cluster in aws and successfully able to launch longhorn , all pods are running and communication between two cluster also perfectly done , but i was trying to create a volume in longhorn attached to my nodes , my volumes are in degrade state even though its bound perfectly.

## To Reproduce

3. Perform '....'

## Expected behavior
Configure a backup target for Longhorn
Let’s access the Longhorn UI in both regions to configure a backup target by using port-forwarding:

ktx sydney
kubectl port-forward longhorn-ui-84f97cf569-z9t85 8000:8000
You should now be able to access the Longhorn UI in your browser at http://localhost:8000/:
Navigate to Setting > General and look for Backup Target. Enter the backup target and the name of the secret you created earlier:

and click Save. In the backup target above, longhorn is bucket name and “ap-sydney-1” is your [OCI region identifier](https://docs.oracle.com/en-us/iaas/Content/General/Concepts/regions.htm).

Repeat the above in the secondary cluster.

Let’s now test if the backup works. Create a Pod that uses [Longhorn volumes](https://longhorn.io/docs/1.2.4/volumes-and-nodes/create-volumes/) by running this command:

kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/v1.2.4/examples/pod_with_pvc.yaml
In the Longhorn UI, you should now be able to see a volume:
''''''
so this is a blog which i was following from oracle cloud , for mine aws cloud output should be like this 
so in aws 
1. i create s3 bucket and configure aws according to specific region i am
2.then backup and secrets 
3. launch longhorn ui using load balancer dns
4. but why my persistent volume is degraded
#####################################
my yaml file
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  restartPolicy: Always
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - ls
          - /data/lost+found
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-volv-pvc
####################################
Degraded	
[pvc-460190c8-5b45-42d8-8759-6049310c3434](http://longhorn2-66dd7d64a18c5695.elb.us-east-2.amazonaws.com:30992/#/volume/pvc-460190c8-5b45-42d8-8759-6049310c3434)
2 Gi
97.1 Mi
a minute ago
Bound
longhorn-system
volume-test
on ip-172-31-111-221.us-east-2.compute.internal
I WANT MY PERSISTENT VOLUME TO WORK HEALTHY WITH ATTCHED NODES IN AWS CLI OF EKS CLUSTER .
## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: LATEST
 - Installation method (e.g. Kubectl):
 - Kubernetes distro (e.g. EKS) and version:
   - Number of management node in the cluster: 2
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: UBUNTU
   - CPU per node:  80
   - Memory per node:t3a.xlarge
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/EKS):
 - Number of Longhorn volumes in the cluster:

**Comment by c3y1huang** [comment]
> Hi @Ronit1135,
default replica number of the default storage class storageClassName: longhorn is 3.
The cluster only have two nodes, so it will remain degraded.

Feel free to re-open if this is not the case.
