### ISSUE TITLE
Volume should be usable once restoration is done

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#571]
Now the real restoration happened during the first time of attaching.

It can be a huge delay in workload starting time.

We should make sure the restoration has been completed before the restoration call returned.

**Comment by yasker** [comment]
https://github.com/longhorn/longhorn-manager/pull/310

(@ywei88 Remember to add a reference to the issue in the PR next time)

**Comment by meldafrawi** [comment]
Steps to test:

- Create 2 K8S clusters (A & B), install longhorn, and create longhorn StorageClass
- Create an AWS S3 bucket, and configure backup target to use it for both clusters.
- On Cluster A: Create Longhorn volume `XA`, attach it to a node, and create a backup.
- On Cluster B, backup page, click `Create Disaster Recovery Volume` and create a DR volume `XA_DR`
**Expected result:**  `XA_DR` should be attached to a node by default.
 
- On Cluster A: Mount volume `XA`, and create a file with some data, compute its MD5 sum, and then create a backup.
 **Expected result:**  `XA_DR` should start restoration process from latest backup.
 
- On Cluster B: Before the restoration is done Activate DR volume 
**Expected result:** You should **NOT** be able to activate the DR volume while restoration process is in progress.  
 
- On Cluster B: After the restoration is done Activate DR volume 
**Expected result:** You should be able to activate the DR volume, and volume gets detached from the node, and ready to be used
 
- On Cluster B: Attach DR volume to a node mount it.
**Expected result:** you should be able to find the data file, and MD5 sum should match.
