### ISSUE TITLE
[FEATURE] Customize MaxRecurringJobRetain

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#5713]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Hardcoding the `MaxRecurringJobRetain` may be inadequate in [some cases](https://github.com/longhorn/longhorn/discussions/5710).

## Describe the solution you'd like

Introduce a setting or field to allow customizing the max retaining number.

## Describe alternatives you've considered

`None`

## Additional context

https://github.com/longhorn/longhorn-manager/pull/1827

**Comment by innobead** [comment]
https://github.com/longhorn/longhorn-manager/pull/1827#pullrequestreview-1375899590

**Comment by mantissahz** [comment]
Update:
When the number of snapshots for a volume is up to `250`, the recurring job pod will still try to create a new snapshot but it would be blocked about `30 minutes` and then fail, and after retrying 3 times, the job status would show it failed.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `88d986`) with test [steps](https://github.com/longhorn/longhorn/issues/5713#issuecomment-1860059880)

1. set `setting recurring-job-max-retention` to 10 and create recurring job with the retain number 15 failed
```
failed to create recurring job c-ru27cr: admission webhook "validator.longhorn.io" denied the request: retain value should be less than or equal to 10
```
2. set `setting recurring-job-max-retention` to 251 failed
```
failed to set the setting recurring-job-max-retention with invalid value 251: value 251 of settings recurring-job-max-retention is invalid: the value 251 should be between 1 and 250
```
3. Create recurring job with the retain number 8, the recurring job worked well.
4. test_recurring_job.py worked [well](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/764/testReport/tests/test_recurring_job/)
