### ISSUE TITLE
[IMPROVEMENT] Make the timeout value of a filesystem-based backup store configurable

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5723]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The current implementation of the filesystem-based backup store, such as NFS and CIFS, is mounted in soft mode with an unconfigurable timeout value. However, the backup store may be highly available, and the current timeout value may not be sufficient for waiting for failover. The purpose of this ticket is to make the timeout value of a filesystem-based backup store configurable by users and more adaptive to their environment.

## Additional context

https://github.com/longhorn/backupstore/pull/112#discussion_r1148726623

**Comment by ChanYiLin** [comment]
close this ticket since it is duplicated
https://github.com/longhorn/longhorn/issues/6608
