### ISSUE TITLE
Container image "harborcore.zuoshouyisheng.com/baseimages/mysql:8.0.28-debian-10-r0" already present on machine

### ISSUE THREAD

**Issue by liwenchao1995** [longhorn/longhorn#5746]
"I have installed Longhorn on Kubernetes with a replica count of three. Yesterday, I restarted two of the replicas and noticed in the Longhorn UI that their sizes decreased from 58G to 3G, and now there is only one replica with a size of 51G. I didn't make any backups. Can I synchronize the other two replicas based on this remaining replica of 51G? Thank you."

"Here is the error log of my pod."
```
kubectl  describe  pod mysql8-standalone-0  -n dev-base

...
Events:
  Type     Reason                  Age                     From                     Message
  ----     ------                  ----                    ----                     -------
  Normal   Scheduled               3m59s                   default-scheduler        Successfully assigned dev-base/mysql8-standalone-0 to idc-general-k8s-30
  Normal   SuccessfulAttachVolume  3m49s                   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-cb074d7b-542c-4e3c-9bd7-b00af53971bc"
  Warning  BackOff                 2m34s (x10 over 3m36s)  kubelet                  Back-off restarting failed container
  Normal   Pulled                  2m19s (x5 over 3m40s)   kubelet                  Container image "harborcore.zuoshouyisheng.com/baseimages/mysql:8.0.28-debian-10-r0" already present on machine
  Normal   Created                 2m19s (x5 over 3m40s)   kubelet                  Created container mysql
  Normal   Started                 2m18s (x5 over 3m39s)   kubelet                  Started container mysql
```

**Comment by innobead** [comment]
@liwenchao1995 what longhorn version you are using?

cc @shuo-wu @derekbit @PhanLe1010 @ejweber

**Comment by liwenchao1995** [comment]
version is v1.2.3

I tried switching my Pod to three replicas 28, 29, and 30 for testing, and found that only when the Pod was switched to machine 30 in Longhorn's UI page, the displayed database size was 51G, while the other two were 3G. Is my data corrupted? Now my pod is running on machine 30, what should I do to recover the data? Thank you.

**Comment by liwenchao1995** [comment]
I'm wondering if I can switch the pod to the 30GB machine, so that Longhorn's UI page shows 51GB. Then, if I delete one of the other two replicas, will it automatically create another one based on the 30GB replica, also with a size of 51GB, and so on until all replicas are 51GB? Is this feasible? Thank you.
