### ISSUE TITLE
UI: Support bundle download link doesn't work in the volume detail page

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#575]
Version: v0.5.0

404 returned if click Generate support bundle in the volume detail page.

It works in dashboard though.

**Comment by meldafrawi** [comment]
Longhorn-ui version: 57bd2a1

Scenarios tested:
 - on Volume Details page, click on Support bundle download link, Enter Issue URL, and description, and click OK

 - on Volume Details page, click on Support bundle download link  and click OK
