### ISSUE TITLE
[FEATURE] Support SPDK Data Engine - Preview

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5751]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Support SPDK data engine with fundamental functions for volume lifecycle and include below resilience capabilities.
- Volume lifecycle (create, delete, attach, detach)
- Replica rebuilding
- Degrade volume
- Snapshot

## Describe the solution you'd like

This is an EPIC issue, so there will be some dependent issues referenced here.

## Additional context

cc @longhorn/dev-data-plane

**Comment by derekbit** [comment]
- Environment
  Cloud provider: Equinix
  Machine: Japan/m3.small.x86
  Kubernetes: v1.23.6+rke2r2
  Nodes: 3 (each node is a master and also a worker)
  OS: Ubuntu 22.04 / 5.15.0-33-generic
  Storage: 1 SSD (Micron_5300_MTFD)
  Network throughput between nodes (tested by iperf over 60 seconds): 15.0 Gbits/sec

![image](https://user-images.githubusercontent.com/12527233/232117439-4bc34bf6-f1c1-461e-a864-421354db2475.png)

cc @innobead @shuo-wu @DamiaSan

**Comment by derekbit** [comment]
In the case of SPDK RAID1 with 3 lvols, the read bandwidth is relatively poor compared to a Longhorn volume due to the fact that the data is always being read from the same lvol rather than from multiple lvols. This can be improved in the future.

**Comment by DamiaSan** [comment]
> 

This [branch ](https://github.com/DamiaSan/spdk/tree/gerrit-16167) contains the read balancing feature.

**Comment by innobead** [comment]
> This [branch ](https://github.com/DamiaSan/spdk/tree/gerrit-16167) contains the read balancing feature.

Let's try to make this part of 1.5.0.

**Comment by innobead** [comment]
This issue will be closed if all 1.5.0 SPDK issues have been verified and closed. 

cc @longhorn/dev-data-plane

**Comment by innobead** [comment]
Closing this, because all SPDK issues are being verified by other issues. 

cc @longhorn/qa
