### ISSUE TITLE
[FEATURE] Support for SPDK RAID1 by setting the minimum number of base_bdevs to 1

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5758]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

SPDK RAID1's `base_bdevs_min` is 2, but the value should be 1 in longhorn’s use case.
https://github.com/longhorn/spdk/blob/longhorn/module/bdev/raid/raid1.c#L190

In order to better support this use case, the following improvements will be made:
1. `base_bdevs_min` will be modified to allow for a minimum value of 1.
2. The RAID1 setup will enable a single logical volume (lvol) to be located on either a local or remote node.

cc @DamiaSan 

## Describe the solution you'd like

A clear and concise description of what you want to happen

**Comment by DamiaSan** [comment]
Yes, I was looking at that and I think this can be the right solution.
In the new [branch](https://github.com/DamiaSan/spdk/tree/gerrit-16167) with last development about RAID, a  RAID1 is able to operate even in degraded mode, so with only one base bdev. But only if the raid lose a base bdev after successfully creation with 2 base bdevs. With this scenario, an alternative to modify the code can be create the raid1 with a dummy base bdev like [null bdev](https://spdk.io/doc/bdev.html) and then remove it from the raid with `bdev_raid_remove_base_bdev`
cc @shuo-wu

**Comment by derekbit** [comment]
I tried a quick patch by setting `base_bdevs_min` to 1.

Just found 
1. RAID 1 with a lvol on the local node: works
2. RAID1 with a lvol on a remote node:  spdk_tgt segfault 
```
  [2023-04-14 16:32:54.899006] tcp.c: 853:nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 127.0.0.1 port 4422 ***
  Segmentation fault (core dumped)
```

Not sure what your final solution is, so this is just for your reference.

**Comment by innobead** [comment]
> a RAID1 is able to operate even in degraded mode, so with only one base bdev. But only if the raid lose a base bdev after successfully creation with 2 base bdevs. With this scenario, an alternative to modify the code can be create the raid1 with a dummy base bdev like [null bdev](https://spdk.io/doc/bdev.html) and then remove it from the raid with `bdev_raid_remove_base_bdev` cc @shuo-wu

Do you know why having this limitation? I feel this is like a workaround instead of a real fix.

**Comment by DamiaSan** [comment]
Yes, I was looking at that and I think this can be the right solution.
In the new [branch](https://github.com/DamiaSan/spdk/tree/gerrit-16167) with last development about RAID, a  RAID1 is able to operate even in degraded mode, so with only one base bdev. But only if the raid lose a base bdev after successfully creation with 2 base bdevs. With this scenario, an alternative to modify the code can be create the raid1 with a dummy base bdev like [null bdev](https://spdk.io/doc/bdev.html) and then remove it from the raid with `bdev_raid_remove_base_bdev`
cc @shuo-wu

**Comment by DamiaSan** [comment]
> > a RAID1 is able to operate even in degraded mode, so with only one base bdev. But only if the raid lose a base bdev after successfully creation with 2 base bdevs. With this scenario, an alternative to modify the code can be create the raid1 with a dummy base bdev like [null bdev](https://spdk.io/doc/bdev.html) and then remove it from the raid with `bdev_raid_remove_base_bdev` cc @shuo-wu
> 
> @DamiaSan Do you know why having this limitation? I feel this is like a workaround instead of a real fix.

Yes, it is a workaround. Because RAID1 is designed to work with 2 base bdevs.
I will make some test with `base_bdevs_min` set to 1 to verify @derekbit 's issue

**Comment by DamiaSan** [comment]
> 

I just tried to reproduce this issue but all works fine for me. Can you describe the steps to reproduce it? I was able to create a raid1 bdev with only one base bdev that is a remote lvol exported via nvmf

**Comment by derekbit** [comment]
Do you mean you hack the spdk codes and change `base_bdevs_min` to `1`?

>  I was able to create a raid1 bdev with only one base bdev that is a remote lvol exported via nvmf

Did you discover and connect to the device?

**Comment by DamiaSan** [comment]
Yes, and I was able to write on it with `dd`

**Comment by derekbit** [comment]
> Yes, and I was able to write on it with `dd`

Got t. It may be due to my messy environment.

**Comment by DamiaSan** [comment]
On Gerrit I had a discussion with SPDK raid's module developer: we pointed out that maybe we will need an RPC to force a newly started raid bdev in degraded state (so with only one valid base bdev) to be registered and so to be usable for example by nvmf module. But still in that case we should create a raid1 bdev with an invalid base bdev (and after force it), so the better solution is to set the minimum number of base bdevs to 1.
If we have logical volume with only one replica, raid1 must be valid (and not degraded) with only one base bdev too.

**Comment by shuo-wu** [comment]
As long as we can start RAID1 with 1 replica, requiring all replicas/lvols valid during launching is acceptable. And is this the main requirement of that branch?

**Comment by innobead** [comment]
YES, we should.

Regards,
David
________________________________

**Comment by DamiaSan** [comment]
> 

What do you mean by main requirement of that branch?

**Comment by DamiaSan** [comment]
made the PR https://github.com/longhorn/spdk/pull/6

**Comment by shuo-wu** [comment]
> What do you mean by main requirement of that branch?

I mean, if **all replicas/lvols in the base bdev list should be valid during (RAID1) creation** is the main requirement

**Comment by shuo-wu** [comment]
BTW, this ticket is like a duplication of https://github.com/longhorn/longhorn/issues/5650

**Comment by derekbit** [comment]
> BTW, this ticket is like a duplication of #5650

This ticket is for single heathy replica (lvol).
I think they are different but are handled in the same PR.

**Comment by DamiaSan** [comment]
> > What do you mean by main requirement of that branch?
> 
> I mean, if **all replicas/lvols in the base bdev list should be valid during (RAID1) creation** is the main requirement.

Not all base bdev should be valid at creation time, but at least `base_bdevs_min`

**Comment by l-mb** [comment]
Makes sense to me. If we dynamically construct the raid1 bdev over time, starting with just one is required, both for degraded mode as well as the first time we start creating.

This limit should be reduced even upstream to 1. Good work!

**Comment by innobead** [comment]
This can be degraded volume testing.

**Comment by derekbit** [comment]
@DamiaSan Could you help update the https://github.com/longhorn/longhorn/issues/5758#issuecomment-1573441029, especially `The reproduce steps/test steps are at:` ? You can refer to https://longhorn.io/docs/1.5.0/spdk/quick-start/ for creating a LH volume. Thank you.

**Comment by DamiaSan** [comment]
@derekbit @innobead 
This task simply enable the creation of a raid1 bdev with only one base bdev. Before this, the operation returned an error.
 So you only have to call RPC `bdev_raid_create` with a `base_bdevs` list filled with only one base bdev.

**Comment by innobead** [comment]
> @derekbit @innobead This task simply enable the creation of a raid1 bdev with only one base bdev. Before this, the operation returned an error. So you only have to call RPC `bdev_raid_create` with a `base_bdevs` list filled with only one base bdev.

@chriscchien Please just check if it's able to create an SPDK volume with one replica.

**Comment by yangchiu** [comment]
@derekbit Do we support create PV/PVC for a SPDK volume from UI? I tried the following steps, the behavior is not desired:

1. Create SPDK Volume `test-1` from Longhorn UI
2. Create PV/PVC with storage class name `longhorn-spdk` from Longhorn UI
3. Create a pod to use this volume:
```
# pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
spec:
  containers:
    - name: sleep
      image: busybox
      imagePullPolicy: IfNotPresent
      args: ["/bin/sh", "-c", "while true;do date;sleep 5; done"]
      volumeMounts:
        - name: pod-data
          mountPath: /data
  volumes:
    - name: pod-data
      persistentVolumeClaim:
        claimName: test-1

# kubectl apply -f pod.yaml
```
4. Delete the pod:
```
# kubectl delete -f pod.yaml
```
5. After the pod deleted, volume `test-1` is still attached and healthy, not being detached.

**Comment by derekbit** [comment]
D

> @derekbit Do we support create PV/PVC for a SPDK volume from UI? I tried the following steps, the behavior is not desired:
> 
> 1. Create SPDK Volume `test-1` from Longhorn UI
> 2. Create PV/PVC with storage class name `longhorn-spdk` from Longhorn UI
> 3. Create a pod to use this volume:
> 
> ```
> # pod.yaml
> apiVersion: v1
> kind: Pod
> metadata:
>   name: test-pod-1
> spec:
>   containers:
>     - name: sleep
>       image: busybox
>       imagePullPolicy: IfNotPresent
>       args: ["/bin/sh", "-c", "while true;do date;sleep 5; done"]
>       volumeMounts:
>         - name: pod-data
>           mountPath: /data
>   volumes:
>     - name: pod-data
>       persistentVolumeClaim:
>         claimName: test-1
> 
> # kubectl apply -f pod.yaml
> ```
> 
> 4. Delete the pod:
> 
> ```
> # kubectl delete -f pod.yaml
> ```
> 
> 5. After the pod deleted, volume `test-1` is still attached and healthy, not being detached.

@yangchiu I didn't see the issue in master-head images. Did you get the result from master-head images?

**Comment by yangchiu** [comment]
Retested on master-head (longhorn-manager 3fb1815) and v1.5.x-head (longhorn-manager 98c2a4f).

SPDK volume with only one replica can be created, attached, written data, and detached without problems.
