### ISSUE TITLE
[FEATURE] Increase read bandwidth of SPDK volume from all downstream replicas

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5759]
In the case of SPDK RAID1 with 3 lvols, the read bandwidth is relatively poor compared to a Longhorn volume due to the fact that the data is always being read from the same lvol rather than from multiple lvols. This can be improved in the future.

_Originally posted by @derekbit in https://github.com/longhorn/longhorn/issues/5751#issuecomment-1509044895_
            

cc @longhorn/dev-data-plane

**Comment by innobead** [comment]
@derekbit will start helping the SPDK data plane part from 1.6.

**Comment by chriscchien** [comment]
Verified in longhorn master(longhorn `8146f3`)

- Machine: c5d.xlarge
- CPU: Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
- RAM: 8.0 GiB
- Kubernetes:v1.27.3+k3s1
- Nodes: 3 (each node is a master and also a worker)
- OS: Ubuntu 22.04.2 LTS
- Storage: 1 SSD (Amazon EC2 NVMe Instance Storage/Local NVMe Storage)

Utilize [kbench](https://github.com/yasker/kbench) as the benchmarking tool, a 3 replicas v2 engine volume read throughout( `219,636` KiB/sec) is better than a v2 data engine volume with one replica(`74,442` KiB/sec)

3 replicas v2 engine volume throughput
```
=========================
FIO Benchmark Summary
For: test_device
CPU Idleness Profiling: disabled
Size: 30G
Quick Mode: disabled
=========================
IOPS (Read/Write)
        Random:          29,925 / 23,364
    Sequential:          44,211 / 25,139

Bandwidth in KiB/sec (Read/Write)
        Random:         219,636 / 80,729
    Sequential:         207,746 / 81,487
                                        

Latency in ns (Read/Write)
        Random:        252,622 / 243,715
    Sequential:        181,117 / 240,302

```

1 replica v2 engine volume throughput
```
=========================
FIO Benchmark Summary
For: test_device
CPU Idleness Profiling: disabled
Size: 30G
Quick Mode: disabled
=========================
IOPS (Read/Write)
        Random:          10,586 / 20,391
    Sequential:          49,473 / 25,316

Bandwidth in KiB/sec (Read/Write)
        Random:          74,442 / 81,103
    Sequential:         200,877 / 81,004
                                        

Latency in ns (Read/Write)
        Random:         133,685 / 52,086
    Sequential:          48,683 / 49,759

```
