### ISSUE TITLE
[Feature request] Search volumes by namespace

### ISSUE THREAD

**Issue by vitobotta** [longhorn/longhorn#577]
This is a small one. It would be nice to be able to filter volumes by namespace in the volumes list, useful when there are many volumes and you want to perform some action on all the volumes within a namespace. Thanks

---
Version: `v0.5.0`

**Comment by yasker** [comment]
@smallteeths Let me know if you need backend's help.

**Comment by smallteeths** [comment]
@yasker Don't need backend and this is the frontend filtering

**Comment by meldafrawi** [comment]
Longhorn-ui version: 57bd2a1

Created multiple longhorn volumes in different namespaces, and filtered using namespace.
