### ISSUE TITLE
[FEATURE] Add a global setting for enabling and disabling SPDK feature

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5778]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Enabling the SPDK feature in Longhorn requires additional CPU and memory resources, making it unsuitable for all environments. To address this, Longhorn provides a global setting that enables or disables the SPDK feature, which is `disabled` by default.

When the feature is enabled, Longhorn attempts to prevent updates to this setting while there are volumes attached. When the setting is applied, Longhorn restarts all instance-manager pods to ensure that the SPDK feature is properly enabled or disabled.

- [x] Add a global setting `spdk` for enabling/disabling SPDK feature
- [x] Add a global setting `spdk-hugepage-limit` for configuring hugepage size used by SPDK
- [x] Validate node conditions such as `hugepage` and `kernel driver` before creating the instance-manager supporting spdk 

cc @shuo-wu @innobead 

## Describe the solution you'd like

A clear and concise description of what you want to happen

**Comment by liyimeng** [comment]
Would be nice to have resource calculation suggestion for spdk as well.

**Comment by yangchiu** [comment]
When testing on master-head (longhorn a5041e1), I encountered the following behavior:

1. Follow https://longhorn.io/docs/1.5.0/spdk/quick-start/, enable spdk by checking the `Enable SPDK Data Engine` setting
2. For each node, add block `type` disk `/dev/nvme1n1`, every block disk is `Schedulable` without problem 
3. Not create any volume, disable spdk by unchecking the `Enable SPDK Data Engine` setting, every block disk is still `Schedulable`
4. enable spdk again by checking the `Enable SPDK Data Engine` setting again **=> All block disks become `Unschedulable` with size 0 Gi**

Not sure if it would cause problems or not. Do we expect users toggle the `Enable SPDK Data Engine` setting?

cc @derekbit

**Comment by derekbit** [comment]
> Not sure if it would cause problems or not. Do we expect users toggle the Enable SPDK Data Engine setting?

Not sure. I prefer to check all block-type disk are removed before unchecking it.

**Comment by innobead** [comment]
> When testing on master-head (longhorn [a5041e1](https://github.com/longhorn/longhorn/commit/a5041e1cf3b0f4f10c0b843bcf9d72a9616d3a2a)), I encountered the following behavior:
> 
> 1. Follow https://longhorn.io/docs/1.5.0/spdk/quick-start/, enable spdk by checking the `Enable SPDK Data Engine` setting
> 2. For each node, add block `type` disk `/dev/nvme1n1`, every block disk is `Schedulable` without problem
> 3. Not create any volume, disable spdk by unchecking the `Enable SPDK Data Engine` setting, every block disk is still `Schedulable`
> 4. enable spdk again by checking the `Enable SPDK Data Engine` setting again **=> All block disks become `Unschedulable` with size 0 Gi**
> 
> Not sure if it would cause problems or not. Do we expect users toggle the `Enable SPDK Data Engine` setting?
> 
> cc @derekbit

@yangchiu good finding! cc @longhorn/qa

**Comment by derekbit** [comment]
@yangchiu The [fix](https://github.com/longhorn/longhorn-manager/pull/1959) is merged. Please help check it again, thank you.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 8bbf501). If there's any block type disk, disabling SPDK Data Engine is not allowed.
