### ISSUE TITLE
Restore won't allow you to activate DR in UI

### ISSUE THREAD

**Issue by wjimenez5271** [longhorn/longhorn#579]
I've created a DR volume from a backup, but I can't do anything further with it to make use of it in my cluster. I am told there should be a menu on the right side which is missing. 

![Screen Shot 2019-05-28 at 4 29 15 PM](https://user-images.githubusercontent.com/322834/58519494-be40a400-8168-11e9-930d-82de55a73263.png)

**Comment by yasker** [comment]
@smallteeths Seems it's better to fix the action menu? It's confusing to the user if they didn't see the menu on the right.

**Comment by meldafrawi** [comment]
Action menu now appears on the right of the DR volume.
