### ISSUE TITLE
[FEATURE] Set recurring jobs to PVCs

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5791]
### Discussed in https://github.com/longhorn/longhorn/discussions/5773

<div type='discussions-op-text'>

<sup>Originally posted by **cod-r** April 17, 2023</sup>
I have a recurring job that I want to apply to some PVCs, but not to all of them.
I'm creating my PVCs using Argo CD. 

From the official documentation it says that i should add a label to the PV to create backups:
```
kubectl -n longhorn-system label volume/pvc-8b9cd514-4572-4eb2-836a-ed311e804d2f recurring-job.longhorn.io/backup1=enabled
```
but the PV is created dynamically by longhorn. Because I'm using gitops and the configuration stays in git, I can't modify the PVs using kubectl.

Why can't we set the label to the PVC considering the PVs are created dynamically?
Is there any way to do what i'm looking for?</div>

**Comment by innobead** [comment]
As discussed with @c3y1huang , the source of truth of the recurring jobs label is still volume, but we can respect if any label change to PVC can update the volume recurring jobs labels accordingly. 

The same concept we did for the default setting configmap and setting resources.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manger 023dd3c).

The test cases `test_recurring_job_label_on_pvc` and `test_recurring_job_source_label` passed, and I can find snapshots created by the recurring jobs.
