### ISSUE TITLE
[BUG] [1.3.x] Test failure in `test_delete_backup_during_restoring_volume`.

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#5800]
## Describe the bug (🐛 if you encounter this issue)

When attempting to resolve conflicts in the https://github.com/longhorn/longhorn-tests/pull/1315 and executing the `test_delete_backup_during_restoring_volume` test case with a private image, I encountered a failure during the `wait_for_volume_faulted` step in the `v1.3.x` branch pipeline. I was not able to reproduce this issue on the `master-head` and `1.4.x` branches. Therefore, I believe that I should create a ticket to investigate whether this behavior is expected or not.

## To Reproduce

1. Run `test_delete_backup_during_restoring_volume` on `v1.3.x` branch pipeline.
2. Observe the failure at step 3,  `wait_for_volume_faulted`

Alternatively, the job can be rerun at https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3536/.

## Expected behavior

The volume should be `faulted`, and the test results should be consistent across all branches.

## Log or Support bundle

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3536/artifact/longhorn-tests-regression-3536-bundle.zip

## Environment

 - Longhorn version: 1.3.x
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
- Number of management node in the cluster: 1
- Number of worker node in the cluster:3
- Node config
- OS type and version:
- CPU per node:4
- Memory per node: 16g
- Disk type(e.g. SSD/NVMe): SSD
- Network bandwidth between the nodes:
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
- Number of Longhorn volumes in the cluster: 1

## Additional context

https://github.com/longhorn/longhorn-tests/pull/1315

**Comment by roger-ryao** [comment]
Close this issue as a duplicate of https://github.com/longhorn/longhorn/issues/4927.

**Comment by innobead** [comment]
@roger-ryao please add `duplicated` label and close as not planned next time.

**Comment by roger-ryao** [comment]
> @roger-ryao please add `duplicated` label and close as not planned next time.
> 
> cc @longhorn/qa

OK, I would keep in mind next time.
