### ISSUE TITLE
[BUG] Trying to TRIM on 1.4.1: the discard operation is not supported

### ISSUE THREAD

**Issue by haakonnessjoen** [longhorn/longhorn#5806]
## Describe the bug (🐛 if you encounter this issue)

I just upgraded from Longhorn Manager 1.2.4 to 1.4.1. The upgrade process was flawless. And upgrading the engine on the volumes was also done without any problems.

But i tried the new TRIM feature, since that was the reason I upgraded. But when I right click a volume, click "Trim Filesystem", it just says "Internal error".

I read the manual, and it said I could try to trim it manually by using fstrim. I tried that. I found my volume with df:
```
/dev/longhorn/pvc-1b8c696c-557d-4412-9e83-2b1dc910ad27                   -         -         -    - /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-1b8c696c-557d-4412-9e83-2b1dc910ad27/globalmount
/dev/longhorn/pvc-1b8c696c-557d-4412-9e83-2b1dc910ad27                   -         -         -    - /var/lib/kubelet/pods/f2c0ead1-5214-4b5e-9156-149a0f3a95fc/volumes/kubernetes.io~csi/pvc-1b8c696c-557d-4412-9e83-2b1dc910ad27/mount
```

So I tried:
```
fstrim /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-1b8c696c-557d-4412-9e83-2b1dc910ad27/globalmount
fstrim: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-1b8c696c-557d-4412-9e83-2b1dc910ad27/globalmount: the discard operation is not supported
```

But it just says `the discard operation is not supported`. I tried both the mountpoints that df mentioned. Neither the "globalmount" or "mount" mountpoints accepts fstrim.

Maybe it is because the filesystems was created in < 1.4.0 (1.2.4)? But the documentation says only that you need to be running >1.4.0, not that it only works with new volumes created after the upgrade.

## To Reproduce

1. Find a volume for trimming
2. Click on "Trim filesystem"
3. Click on "OK"

## Expected behavior

I would expect either the functionality to work. Or some informative error message if it is not possible with old volumes. And if so, it should be mentioned in the Prerequisites in the documentation for trim.

## Environment

 - Longhorn version: 1.4.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04.3 LTS
   - CPU per node: 1 cpu, 6 cores, (12 if you include ht)
   - Memory per node: 64GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 10GE
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 61

**Comment by derekbit** [comment]
Please check the concern of the `discard` mentioned in the [doc](https://longhorn.io/docs/1.4.1/volumes-and-nodes/trim-filesystem/).
If you want to enable to `discard`, you can add the `discard` the storageclass's mount options in the [doc](https://kubernetes.io/docs/concepts/storage/storage-classes/#mount-options).

**Comment by haakonnessjoen** [comment]
@derekbit Yes, I have read the doc about trim/discard. Thats the doc I was referring to. I don't feel that it says anything about my issue. I am not even using snapshots at the moment on this volume.

Do you manually need to add the discard mount option to be able to use this new feature? According to the documentation, it seems to be enough to be at version 1.4.0 or higher? But it also says that it would only trim the head unless you enable the extra "remove snapshots" option.

**Comment by derekbit** [comment]
> @derekbit Yes, I have read the doc about trim/discard. Thats the doc I was referring to. I don't feel that it says anything about my issue. I am not even using snapshots at the moment on this volume.
> 
> Do you manually need to add the discard mount option to be able to use this new feature? According to the documentation, it seems to be enough to be at version 1.4.0 or higher? But it also says that it would only trim the head unless you enable the extra "remove snapshots" option.

I mean the failure is caused by the lack of `discard` option in the mount point. You can add `discard` in storageclass' mount options and see if it can work.

**Comment by haakonnessjoen** [comment]
I will try with an updated StorageClass when I have resolved issue #5807 first. Since I am now unable to mount anything.

**Comment by haakonnessjoen** [comment]
For anyone looking back at this issue. This was now solved.

Either because I was able to fix the issue with pods not being able to mount any volumes at all.
Or by adding the following to my longhorn storage classes:

```yaml
mountOptions:
- discard
```

If the latter is the reason, it should maybe be mentioned in the doc, I think.

**Comment by c3y1huang** [comment]
> I have a similar problem after update from 1.3.1 to 1.4.1. When I try to do a trim I get the following error: `unable to trim filesystem for volume pvc-06043a16-9bd2-4d1a-83ad-38841f4c4602: cannot find volume pvc-06043a16-9bd2-4d1a-83ad-38841f4c4602 mount info on host: failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net fstrim /var/lib/kubelet/pods/7ed1a206-b91a-4cb1-9949-fcf4cf6ae1af/volume-subpaths/pvc-06043a16-9bd2-4d1a-83ad-38841f4c4602/postgres/0], output , stderr fstrim: /var/lib/kubelet/pods/7ed1a206-b91a-4cb1-9949-fcf4cf6ae1af/volume-subpaths/pvc-06043a16-9bd2-4d1a-83ad-38841f4c4602/postgres/0: the discard operation is not supported : exit status 1` Tried to add Storageclass "mountOptions:- discard", reattach volume, but no change. Can you please tell me how to solve this problem?

Have you tried trimming after reattaching the volumes?
https://github.com/longhorn/longhorn/issues/5203#issuecomment-1372015161
