### ISSUE TITLE
[BUG] -regextype parameter unrecognized on find command happening in longhorn-manager

### ISSUE THREAD

**Issue by greggameplayer** [longhorn/longhorn#5816]
## Describe the bug (🐛 if you encounter this issue)

On the longhorn-manager pod which is executed in a Alpine Linux VM, i get an error telling me that the -regextype parameter doesn't exist on find command, that prevents the listening of the replica directories in the folder /var/lib/longhorn.

## To Reproduce

On a Alpine Linux node, let the longhorn-manager pod start.

## Expected behavior

This kind of error are thrown : 
`
time="2023-04-26T14:45:04Z" level=error msg="unable to get possible replica directories in disk /var/lib/longhorn/ on node master3 since cannot list replica directories in the disk /var/lib/longhorn/: failed to execute: nsenter [--mount=/host/proc/1/ns//mnt sh -c find /var/lib/longhorn/replicas -type d -maxdepth 1 -mindepth 1 -regextype posix-extended -regex \".*-[a-zA-Z0-9]{8}$\" -exec basename {} \\;], output , stderr, find: unrecognized: -regextype\nBusyBox v1.36.0 (2023-04-24 17:51:26 UTC) multi-call binary.\n\nUsage: find [-HL] [PATH]... [OPTIONS] [ACTIONS]\n\nSearch for files and perform actions on them.\nFirst failed action stops processing of current file.\nDefaults: PATH is current directory, action is '-print'\n\n\t-L,-follow\tFollow symlinks\n\t-H\t\t...on command line only\n\t-xdev\t\tDon't descend directories on other filesystems\n\t-maxdepth N\tDescend at most N levels. -maxdepth 0 applies\n\t\t\tactions to command line arguments only\n\t-mindepth N\tDon't act on first N levels\n\t-depth\t\tAct on directory *after* traversing it\n\nActions:\n\t( ACTIONS )\tGroup actions for -o / -a\n\t! ACT\t\tInvert ACT's success/failure\n\tACT1 [-a] ACT2\tIf ACT1 fails, stop, else do ACT2\n\tACT1 -o ACT2\tIf ACT1 succeeds, stop, else do ACT2\n\t\t\tNote: -a has higher priority than -o\n\t-name PATTERN\tMatch file name (w/o directory name) to PATTERN\n\t-iname PATTERN\tCase insensitive -name\n\t-path PATTERN\tMatch path to PATTERN\n\t-ipath PATTERN\tCase insensitive -path\n\t-regex PATTERN\tMatch path to regex PATTERN\n\t-type X\t\tFile type is X (one of: f,d,l,b,c,s,p)\n\t-executable\tFile is executable\n\t-perm MASK\tAt least one mask bit (+MASK), all bits (-MASK),\n\t\t\tor exactly MASK bits are set in file's mode\n\t-mtime DAYS\tmtime is greater than (+N), less than (-N),\n\t\t\tor exactly N days in the past\n\t-atime DAYS\tatime +N/-N/N days in the past\n\t-ctime DAYS\tctime +N/-N/N days in the past\n\t-mmin MINS\tmtime is greater than (+N), less than (-N),\n\t\t\tor exactly N minutes in the past\n\t-newer FILE\tmtime is more recent than FILE's\n\t-inum N\t\tFile has inode number N\n\t-user NAME/ID\tFile is owned by given user\n\t-group NAME/ID\tFile is owned by given group\n\t-size N[bck]\tFile size is N (c:bytes,k:kbytes,b:512 bytes(def.))\n\t\t\t+/-N: file size is bigger/smaller than N\n\t-links N\tNumber of links is greater than (+N), less than (-N),\n\t\t\tor exactly N\n\t-empty\t\tMatch empty file/directory\n\t-prune\t\tIf current file is directory, don't descend into it\nIf none of the following actions is specified, -print is assumed\n\t-print\t\tPrint file name\n\t-print0\t\tPrint file name, NUL terminated\n\t-exec CMD ARG ;\tRun CMD with all instances of {} replaced by\n\t\t\tfile name. Fails if CMD exits with nonzero\n\t-exec CMD ARG + Run CMD with {} replaced by list of file names\n\t-delete\t\tDelete current file/directory. Turns on -depth option\n\t-quit\t\tExit\n, error exit status 1"`

## Environment

 - Longhorn version: v1.4.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 1
 - Problematic node
   - OS type and version: Alpine Linux 
   - CPU per node: 4
   - Memory per node: 12
   - Disk type(e.g. SSD/NVMe): HDD
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox

**Comment by greggameplayer** [comment]
Here is the support bundle :
[supportbundle_d7125f36-ceb2-40cf-86f8-520d428ec4b8_2023-04-26T15-02-32Z.zip](https://github.com/longhorn/longhorn/files/11334401/supportbundle_d7125f36-ceb2-40cf-86f8-520d428ec4b8_2023-04-26T15-02-32Z.zip)

PS : The problematic node is named master3

**Comment by derekbit** [comment]
Ref: https://github.com/longhorn/longhorn/issues/4900

**Comment by weizhe0422** [comment]
Hi @greggameplayer, as @derekbit said, there is an issue that was tracked to follow, which is suggested to generate customized binary utilities to support commands that Longhorn used. 

If you agree, then I'll close this to just track #4900. WDYT
