### ISSUE TITLE
The ability to specify the default data path on the host

### ISSUE THREAD

**Issue by paalkr** [longhorn/longhorn#582]
Ref: https://github.com/rancher/longhorn/issues/574

It must be possible to specify what mount path on the host that should be automatically included in Longhorn. In my case during node startup attached EBS volumes are striped together and mounted at /ebs/, which is where I would like Longhorn to store data. Currently Longhorn adds /var/lib/rancher/longhorn/ to the storage pool by default, which would be on the node root volume. Using the root volume for storage is not ideal.

![image](https://user-images.githubusercontent.com/9726307/58685685-da1c9380-837c-11e9-9144-9f280d6eff08.png)

**Comment by yasker** [comment]
Two things regarding the merged PR:
1. Change the new default setting to `/var/lib/longhorn/`. Remember it only applies to the new nodes after v0.6.0. For nodes/disks before v0.6.0, it still should be `/var/lib/rancher/longhorn`.
2. What if user set this field to empty? I think we can disable automatic disk creation in this case.

**Comment by ttpcodes** [comment]
1. So this would mean that the initially created default `Disks` from before `v0.6.0` should still be using `/var/lib/rancher/longhorn/`, and only any new `Nodes` added after the upgrade or installation of `v0.6.0` should use `/var/lib/longhorn/` for the default `Disk` right?
2. Yes, I think we can allow the user to set this field to empty and place a note in the settings that states that leaving the field empty will disable the initial `Disk` creation.

**Comment by yasker** [comment]
Per our discussion, it's not feasible to use the empty field as the indicator for if we need to create a new default disk for the new node. We will add a new setting for that purpose later.

**Comment by meldafrawi** [comment]
Steps to Test:
  - create a 3-node kubnernetes cluster, and install longhorn.
  - create longhorn storage class and create a pvc using: https://raw.githubusercontent.com/rancher/longhorn/master/examples/pvc.yaml
  - In `Settings/General` page, change `Default Data Path` field to `/var/lib/longhorn-data`
  - provision a 4th node, before adding the node to the cluster, create `/var/lib/longhorn-data` directory.
  - add the 4th node to the cluster.
  - in `Node` page, **Disable Scheduling** on one of the old nodes.
  - in `Voulme details page`,  delete one of the volume replicas.
  - a new replica should be created on the new 4th node, it's path should be `/var/lib/longhorn-data/replicas/xxxx`.

**Comment by meldafrawi** [comment]
Validation: PASSED 

Steps to Test:
  - create a 3-node kubnernetes cluster, and install longhorn.
  - create longhorn storage class and create a pvc using: https://raw.githubusercontent.com/rancher/longhorn/master/examples/pvc.yaml
  - In `Settings/General` page, change `Default Data Path` field to `/var/lib/longhorn-data`
  - provision a 4th node, before adding the node to the cluster
    > Expected Result: `/var/lib/longhorn-data` should be created on the new node.    (PASS)
  - add the 4th node to the cluster.
  - in `Node` page, **Disable Scheduling** on one of the old nodes.
  - in `Voulme details page`,  delete one of the volume replicas.
  >  Expected Result:  a new replica should be created on the new 4th node, it's path should be `/var/lib/longhorn-data/replicas/xxxx`.
