### ISSUE TITLE
[FEATURE] Support backing image backup & restore with delta data transfer

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#5821]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Currently, Longhorn BackingImage doesn't support delta data backup and restore. This makes users need to download the whole BackingImage file if it is updated. We would like to store BackingImage as Longhorn Volume which supports COW over each relative base image for delta data transfer for better space efficiency. Also, when the BackingImage is updated, users only need to download the new delta data.

## Describe the solution you'd like

A clear and concise description of what you want to happen

## Additional context

ref: https://github.com/longhorn/longhorn/issues/4165

## User story example
1. The central admin decides to deploy a new VM workload to the downstream clusters.
2. The image for the workload was built. Let's call it Image_v1.
3. The central admin asks the downstream cluster admins to download the image and run the workload based on Image_v1. Image_v1 itself won't be changed. All the workloads are running on a COW layer on top of Image_v1
4. After a few weeks, the VM needs to be updated due to e.g. service patch or CVE.
5. The central admin pulls in Image_v1, updates it by starting the VM, and changes the file inside, creating Image_v2.
6. The central admin notifies the downstream cluster admins to update the workload.
7. Downstream cluster admins download the Image_v2 (delta or not), then start using it for the new workloads, as well as migrating the old workloads to it.

And continue.

**Comment by innobead** [comment]
This has been superseded by https://github.com/longhorn/longhorn/issues/4165.
