### ISSUE TITLE
[IMPROVEMENT] Delete instance status when instance manager shuts down gracefully

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#5825]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Even when instance manager shuts down gracefully, the instance status (including the "running" state) continues to be stored in the InstanceManager resource's status indefinitely. This is confusing and may have contributed to some occurrences of #5709. It is likely because the instance-manager controller's monitor is responsible for updating this status, but instance manager goes down too quickly for this to happen.

## Describe the solution you'd like

The InstanceManager resource's status should show no running instances if the associated instance manager shut down gracefully. We could either accomplish this by assuming instances are down when we detect instance manager is down (fairly straightforward) or we can modify the instance manager shutdown sequence to allow time for the update (potentially difficult).

## Additional context

It looks like we also unintentionally log "Failed to clean up all processes for Instance Manager graceful shutdown" even if we actually have cleaned up all instance processes.

https://github.com/longhorn/longhorn-instance-manager/blob/34e6650fb5922b961e7bc06205ce33dfc6899e45/app/cmd/start.go#L81

```
[longhorn-instance-manager] time="2023-04-27T18:41:15Z" level=info msg="Shutdown all instance processes successfully"
[longhorn-instance-manager] time="2023-04-27T18:41:15Z" level=error msg="Failed to clean up all processes for Instance Manager graceful shutdown"
[longhorn-instance-manager] time="2023-04-27T18:41:15Z" level=info msg="Proxy Server is shutting down"
[longhorn-instance-manager] time="2023-04-27T18:41:15Z" level=info msg="Process Manager is shutting down"
eweber@laptop:~> kubectl logs -f instance-manager-r-b249ae2eae890b25c7539e87c0a907e3 -n longhorn-syste
```

**Comment by innobead** [comment]
@ejweber Hasn't this been fixed on https://github.com/longhorn/longhorn-manager/commit/216c43140ee00c355da2d224ab0d635523fcec37? If yes, let's close this.

**Comment by ejweber** [comment]
> @ejweber Hasn't this been fixed on https://github.com/longhorn/longhorn-manager/commit/216c43140ee00c355da2d224ab0d635523fcec37? If yes, let's close this.

Yes, I think so. Good catch. Closing.
