### ISSUE TITLE
[FEATURE] Identify and manage orphaned lvols and raid bdevs if the associated `Volume` resources are not existing

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5827]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

If the `Volume` resources are deleted, but their associated lvols and raid bdevs still exist (e.g. a user adds a disk containing these items), Longhorn should be capable of detecting these orphaned items and creating the corresponding `Orphan` resources which will help user manage them.

## Describe the solution you'd like

A clear and concise description of what you want to happen

**Comment by innobead** [comment]
@derekbit but why those lvol and raid bdev will still exist? I thought they will be deleted accordingly.

**Comment by derekbit** [comment]
For example, there is a spdk volume with 3 replicas. In case one of the nodes is somehow down, user removes as well as the replica. After the nodes comes back or the disk is moved to another node, the orphaned lvol still stays on the disk and is out of Longhorn's control.

**Comment by yangchiu** [comment]
Verified failed on master-head (longhorn-manager ) following the test steps:

1. Create a cluster for spdk following https://longhorn.io/docs/1.5.0/spdk/quick-start/ using machines with extra disk e.g. `c5d.2xlarge`
2. Add `/dev/nvme1n1` block disk to each Longhorn node
3. Create a SPDK volume with 2 replicas
4. Power down the non-attached node.
5. Delete the replica that is not on the attached node
6. Power up the non-attached node **=> The node becomes `Unschedulable`, and all disks on that node become `Unschedulable` with size `0 Gi` with error messages:**
```
$ kubectl logs longhorn-manager-4kb9n -n longhorn-system | grep spdk
time="2023-06-06T09:29:43Z" level=error msg="Failed to sync Longhorn setting longhorn-system/spdk" controller=longhorn-setting error="failed to sync setting for longhorn-system/spdk: cannot apply spdk setting to Longhorn workloads when there are attached volumes" node=ip-10-0-1-109
```
7. An orphan resource will be created and records the deleted replica. **=> There's no orphan resource being created**

Also, Create and attach a spdk volume, and then randomly delete a replica, there will be no replica rebuilding happening, the volume will stay in `degraded` state forever.

cc @derekbit

**Comment by yangchiu** [comment]
Tested again on master-head (longhorn-manager 8bbf501) following the steps below, the behavior is still not quite normal:

1. Create a cluster following https://longhorn.io/docs/1.5.0/spdk/quick-start/ using machines with extra disk e.g. `c5d.2xlarge`
2. Enable `SPDK Data Engine`
3. Add `/dev/nvme1n1` block disk to each Longhorn node and wait them becoming `Schedulable`
4. Not create any volume, reboot a node directly
5. After reboot, the block disk `/dev/nvme1n1` on that node becomes `Unschedulable` with size `0Gi`

Here is some suspicious logs:
```
$ kubectl logs longhorn-manager-khjk2 -n longhorn-system | grep /dev
time="2023-06-09T02:52:27Z" level=debug msg="Failed to get device type of /dev/nvme1n1" controller=longhorn-setting error="failed to get device path in [/proc/mounts /host/proc/1/mounts]: cannot find device path of /dev/nvme1n1" node=ip-10-0-1-11
time="2023-06-09T02:52:27Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"ip-10-0-1-11\", UID:\"fcb59be7-8f83-4791-9a70-bd2d6dceabcc\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"3434\", FieldPath:\"\"}): type: 'Warning' reason: 'Ready' Disk disk-2(/dev/nvme1n1) on node ip-10-0-1-11 is not ready: failed to get disk config: error: disk service client is nil"
time="2023-06-09T02:52:27Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"ip-10-0-1-11\", UID:\"fcb59be7-8f83-4791-9a70-bd2d6dceabcc\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"3434\", FieldPath:\"\"}): type: 'Warning' reason: 'Schedulable' the disk disk-2(/dev/nvme1n1) on the node ip-10-0-1-11 is not ready"
```

```
$ kubectl logs instance-manager-6d772c3fc26e7756e595b051d22da005 -n longhorn-system | grep disk-2
[longhorn-instance-manager] time="2023-06-09T02:52:57Z" level=info msg="Getting disk info" diskName=disk-2 diskPath=/dev/nvme1n1 diskType=block
[longhorn-instance-manager] time="2023-06-09T02:52:57Z" level=info msg="Getting disk info" diskName=disk-2
[2023-06-09 02:52:57.694800] bdev.c:7867:spdk_bdev_open_ext: *NOTICE*: Currently unable to find bdev with name: disk-2
[2023-06-09 02:52:57.694854] bdev_rpc.c: 867:rpc_bdev_get_bdevs: *ERROR*: bdev 'disk-2' does not exist
[longhorn-instance-manager] time="2023-06-09T02:52:57Z" level=error msg="Failed to get disk info" diskName=disk-2 error="rpc error: code = NotFound desc = cannot find AIO bdev with name disk-2"
[longhorn-instance-manager] time="2023-06-09T02:52:57Z" level=info msg="Creating disk" blockSize=4096 diskName=disk-2 diskPath=/dev/nvme1n1 diskType=block
[longhorn-instance-manager] time="2023-06-09T02:52:57Z" level=info msg="Creating disk" blockSize=4096 diskName=disk-2 diskPath=/dev/nvme1n1
[longhorn-instance-manager] time="2023-06-09T02:52:57Z" level=info msg="Creating AIO bdev disk-2 with block size 4096" blockSize=4096 diskName=disk-2 diskPath=/dev/nvme1n1
[longhorn-instance-manager] time="2023-06-09T02:52:57Z" level=info msg="Creating lvstore disk-2" blockSize=4096 diskName=disk-2 diskPath=/dev/nvme1n1
[longhorn-instance-manager] time="2023-06-09T02:53:13Z" level=info msg="Created disk" blockSize=4096 diskName=disk-2 diskPath=/dev/nvme1n1
[longhorn-instance-manager] time="2023-06-09T02:53:13Z" level=info msg="Getting disk info" diskName=disk-2 diskPath=/dev/nvme1n1 diskType=block
[longhorn-instance-manager] time="2023-06-09T02:53:13Z" level=info msg="Getting disk info" diskName=disk-2
[longhorn-instance-manager] time="2023-06-09T02:53:13Z" level=info msg="Got disk info" diskName=disk-2
[longhorn-instance-manager] time="2023-06-09T02:53:13Z" level=info msg="Listing disk replica instances" diskName=disk-2 diskType=block
[longhorn-instance-manager] time="2023-06-09T02:53:27Z" level=info msg="Getting disk info" diskName=disk-2 diskPath=/dev/nvme1n1 diskType=block
[longhorn-instance-manager] time="2023-06-09T02:53:27Z" level=info msg="Getting disk info" diskName=disk-2
[longhorn-instance-manager] time="2023-06-09T02:53:27Z" level=info msg="Got disk info" diskName=disk-2
[longhorn-instance-manager] time="2023-06-09T02:53:27Z" level=info msg="Getting disk info" diskName=disk-2 diskPath=/dev/nvme1n1 diskType=block
```

cc @derekbit

**Comment by derekbit** [comment]
Does `/dev/nvme1n1` exist after reboot?

**Comment by yangchiu** [comment]
> Does `/dev/nvme1n1` exist after reboot?

Yes.
```
# fdisk -l | grep nvme1n1
Disk /dev/nvme1n1: 160 GiB, 171798691840 bytes, 335544320 sectors
Disk model: Amazon Elastic Block Store              
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
```

And if I manually remove the `Unschedulable` one and re-add `/dev/nvme1n1` again, it works without problems.

> How did you create `/dev/nvme1n1`?

It's a local nvme storage attached to c5d instance by default.

**Comment by yangchiu** [comment]
I'll try to test in other environment later.

**Comment by derekbit** [comment]
I can check it first and will update it later.

**Comment by yangchiu** [comment]
Probably because there are 2 different storage on the machine and the device path will change randomly after reboot:

```
Disk /dev/nvme1n1: 186.26 GiB, 200000000000 bytes, 390625000 sectors
Disk model: Amazon EC2 NVMe Instance Storage        
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/nvme2n1: 160 GiB, 171798691840 bytes, 335544320 sectors
Disk model: Amazon Elastic Block Store              
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
```

I'll change to test on other environment then.

**Comment by derekbit** [comment]
> Probably because there are 2 different storage on the machine and the device path will change randomly after reboot

Interesting.
If the change doesn't happen, the issue is not seen.

So, the question should be how to make the disk naming perisstent.

**Comment by innobead** [comment]
https://serverfault.com/questions/1051326/what-is-the-proper-way-to-configure-etc-fstab-on-an-ec2-instance

**Comment by yangchiu** [comment]
Tested again on Equinix following [the test steps](https://github.com/longhorn/longhorn/issues/5827#issuecomment-1573215633).

Everything works as expected except the last step:
- Go to the instance-manage pod and execute the command `go-spdk-helper lvol get`. The replica should be deleted.

Got a command not found error:
```
# kubectl exec -it instance-manager-4ca1b1a1d37d72361bb7226bab957fcf -n longhorn-system -- /bin/sh
sh-4.4# go-spdk-helper lvol get
sh: go-spdk-helper: command not found
```

cc @derekbit

**Comment by derekbit** [comment]
Can you find `go-spdk-helper` in the pod?

**Comment by derekbit** [comment]
> > Does `/dev/nvme1n1` exist after reboot?
> 
> Yes.
> 
> ```
> # fdisk -l | grep nvme1n1
> Disk /dev/nvme1n1: 160 GiB, 171798691840 bytes, 335544320 sectors
> Disk model: Amazon Elastic Block Store              
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 4096 bytes / 4096 bytes
> ```
> 
> And if I manually remove the `Unschedulable` one and re-add `/dev/nvme1n1` again, it works without problems.
> 
> > How did you create `/dev/nvme1n1`?
> 
> It's a local nvme storage attached to c5d instance by default.

@yangchiu Can you help open a ticket for tracking the issue?
I will improve it. Currently, the workaround is removing the disk and adding it back.
Thank you.

**Comment by derekbit** [comment]
> go-spdk-helper

Just found I forgot to add `go-spdk-helper` (debugging too) after introducing multi-stage build...

**Comment by yangchiu** [comment]
Verified passed on v1.5.x-head (longhorn manager 42bb998, longhorn-instance-manager 3fc14de) following [the test steps](https://github.com/longhorn/longhorn/issues/5827#issuecomment-1573215633).
