### ISSUE TITLE
[REFACTOR] Move the construction of each backup store service to service constructor 

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5840]
## Is your improvement request related to a feature? Please describe

The below code should be moved to the service constructor instead of imperatively updating the properties of the backup store instance after initialization. 

This change can free the caller w/o any initialization for the backup store. 

[/s3/s3.go#L51-L57](https://github.com/longhorn/backupstore/blob/ac6d4e54d6324a4bb38ec64342e90037247a65f3/s3/s3.go#L51-L57)
```go
	if u.User != nil {
		b.service.Region = u.Host
		b.service.Bucket = u.User.Username()
	} else {
		//We would depends on AWS_REGION environment variable
		b.service.Bucket = u.Host
	}
```

## Describe the solution you'd like

Besides the above refactoring, also need to review all backup store implementations to conform to the correct common OO implementation. 

## Additional context

cc @longhorn/dev

**Comment by innobead** [comment]
Can use this issue for backup provider refactoring.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn maseter(backupstore `844286`) with test [steps](https://github.com/longhorn/longhorn/issues/5840#issuecomment-1976459802)

Volume can backup to backupstore(S3, NFS, CIFS), and after restoring, the data is correct.

I would like to test again after https://github.com/longhorn/longhorn/issues/8784 resolved then close it, thank you.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn maseter(backupstore **b19161**) with test [steps](https://github.com/longhorn/longhorn/issues/5840#issuecomment-1976459802)

Volume can backup to backupstore(S3, NFS, CIFS, AZURE), and after restoring, the data is correct.

**Comment by chriscchien** [comment]
Having a doc on how to setup test Azure backupstore [here](https://confluence.suse.com/display/LON/Setup+Azurite+Backupsotre+For+Testing)
