### ISSUE TITLE
[FEATURE] Longhorn UI for SPDK feature

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5846]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Some updates and changes to Longhorn UI for SPDK feature
- Dashboard
  - Separate storage information of `block` and `filesystem` disks
- Node
  - `hugepage` usage (`node.status.allocatable.hugepages-2Mi`) (nice to have)
  - disks
    - disk type (`node. Spec.disks[i].disktype`)
        - set disk type for newly added disk
        - show disk type of each disk 
    - Support sorting by disk type

## Describe the solution you'd like

A clear and concise description of what you want to happen

**Comment by smallteeths** [comment]
1. `hugepage` is not included in the returned data of the node, so I did not add it.
2. `Support sorting by disk type`  is not included, because the disk list is actually within the node and does not have a header for simplicity. (I think this can be implemented later on a separate page dedicated to disks.)

**Comment by chriscchien** [comment]
Verified **Pass** on longhorn master(longhorn-manager `64db91`, longhorn-ui `e6cc64`)

From UI I can
- Create SPDK volume
- Enable/Disable SPDK

`Storage Schedulable (Block)` in dashboard
![image](https://github.com/longhorn/longhorn/assets/73337386/48c8f681-f986-47f0-8700-954b3a5ad61a)

Different type of data engine(`longhorn`, `spdk`)
![image](https://github.com/longhorn/longhorn/assets/73337386/bbdab8c9-a580-4ac5-a12b-85d79bca938d)

SPDK orphaned replica
![image](https://github.com/longhorn/longhorn/assets/73337386/6d8a0901-8045-4c7f-9e98-500956c501d8)
