### ISSUE TITLE
[TEST] Removed setting mkfs-ext4-parameters causes test cases failed

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#5849]
## What's the test to develop? Please describe

Since setting `mkfs-ext4-parameters` has been removed, the related setup should be removed or modified in longhorn-tests too, otherwise lots of test cases would fail when trying to reference this value. Like: https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/475/testReport/junit/tests/test_node/test_node_disk_update/

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

Add any other context or screenshots about the test request here.

**Comment by innobead** [comment]
When removing some existing/deprecated features, need to run testing to ensure that any tests are broken. 

cc @longhorn/dev

**Comment by ejweber** [comment]
I broke this in #4914. I'll assign this one to myself and try to get things working again.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager a7dd20c). We can find daily regression is back to normal and isn't overwhelmed by `mkfs-ext4-parameters` related errors.

amd64: https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/484/
arm64: https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/472/
