### ISSUE TITLE
[BUG] Cant delete snapshots from the UI after upgrade to 1.4.1. "unknown method SnapshotHashCancel for service ptypes.SyncAgentService"

### ISSUE THREAD

**Issue by koshrf** [longhorn/longhorn#5859]
## Describe the bug (🐛 if you encounter this issue)

I have a job that creates a snapshot everyday of a volume and to retain 1, after upgrading from 1.2.4 to 1.4.1 I can't delete snapshots at all and the system isn't deleting the old ones and it just keep accumulating. I get an error when trying to manually delete old snapshots.

## To Reproduce

1. Go to the volume
2. Click on 'Snapshots and Backups'
3. Perform 'Delete on any of the snapshots'
4. Get this error: "failed to delete snapshot: proxyServer=10.42.114.52:8501 destination=10.42.114.52:10005: failed to remove snapshot [c-y0kehe-48a1e2e9-f0bc-4222-b142-24b4a12f7456]: rpc error: code = Unknown desc = failed to cancel snapshot c-y0kehe-48a1e2e9-f0bc-4222-b142-24b4a12f7456 hash task: rpc error: code = Unimplemented desc = unknown method SnapshotHashCancel for service ptypes.SyncAgentService"

## Expected behavior

Be able to delete snapshots.

## Log or Support bundle

```
[longhorn-instance-manager] time="2023-05-04T17:33:52Z" level=info msg="Removing snapshots [c-y0kehe-1971f0e5-b7a9-439f-bbdc-dd9e54dbaac1]" serviceURL="10.42.114.52:10005"
[longhorn-instance-manager] time="2023-05-04T17:33:52Z" level=warning msg="Failed to delete c-y0kehe-1971f0e5-b7a9-439f-bbdc-dd9e54dbaac1" error="failed to cancel snapshot c-y0kehe-1971f0e5-b7a9-439f-bbdc-dd9e54dbaac1 hash task: rpc error: code = Unimplemented desc = unknown method SnapshotHashCancel for service ptypes.SyncAgentService"
[longhorn-instance-manager] time="2023-05-04T17:33:52Z" level=info msg="Purging snapshots" serviceURL="10.42.114.52:10005"
[longhorn-instance-manager] time="2023-05-04T17:39:11Z" level=info msg="Purging snapshots" serviceURL="10.42.114.52:10005"
[longhorn-instance-manager] time="2023-05-04T17:39:29Z" level=info msg="Purging snapshots" serviceURL="10.42.114.52:10005"
[longhorn-instance-manager] time="2023-05-04T17:39:43Z" level=info msg="Purging snapshots" serviceURL="10.42.114.52:10005"
[longhorn-instance-manager] time="2023-05-04T17:40:16Z" level=info msg="Removing snapshots [c-y0kehe-1971f0e5-b7a9-439f-bbdc-dd9e54dbaac1]" serviceURL="10.42.114.52:10005"
[longhorn-instance-manager] time="2023-05-04T17:40:16Z" level=warning msg="Failed to delete c-y0kehe-1971f0e5-b7a9-439f-bbdc-dd9e54dbaac1" error="failed to cancel snapshot c-y0kehe-1971f0e5-b7a9-439f-bbdc-dd9e54dbaac1 hash task: rpc error: code = Unimplemented desc = unknown method SnapshotHashCancel for service ptypes.SyncAgentService"
[longhorn-instance-manager] time="2023-05-04T17:40:16Z" level=info msg="Purging snapshots" serviceURL="10.42.114.52:10005"
```

## Environment

 - Longhorn version: 1.4.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2 1.25.8
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: RedHat 8
   - CPU per node: 4
   - Memory per node: 16Gb
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 10Gb
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 10

## Additional context

There was also an upgrade from K8s 1.23 to 1.24 and then to 1.25 the same day after upgrading longhorn.

I deleted the job before the snapshots so it doesn't keep storing snapshots without deleting it.

Edit: Upgraded from 1.2.4 to 1.4.1

**Comment by derekbit** [comment]
Have you upgraded the engine of the volume to v1.4.1?

**Comment by koshrf** [comment]
> Have you upgraded the engine of the volume to v1.4.1?

Now that you mention it, I checked and for some reason I have 2 daemonset for the engine, the old one and the new one. The old one seems to be the one that uses the volume.  I upgraded using the rancher UI.

How can I delete or remove the old daemonset without losing the volume ? 

```
$> kubectl get daemonset                                                 
NAME                       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
engine-image-ei-d474e07c   3         3         3       3            3           <none>          309d
engine-image-ei-ef01bf86   3         3         3       3            3           <none>          8d

$> kubectl  get pods -l longhorn.io/component=engine-image -o yaml | grep image:
      longhorn.io/engine-image: ei-d474e07c
      image: rancher/mirrored-longhornio-longhorn-engine:v1.2.4
      image: docker.io/rancher/mirrored-longhornio-longhorn-engine:v1.2.4
      longhorn.io/engine-image: ei-d474e07c
      image: rancher/mirrored-longhornio-longhorn-engine:v1.2.4
      image: docker.io/rancher/mirrored-longhornio-longhorn-engine:v1.2.4
      longhorn.io/engine-image: ei-d474e07c
      image: rancher/mirrored-longhornio-longhorn-engine:v1.2.4
      image: docker.io/rancher/mirrored-longhornio-longhorn-engine:v1.2.4
      longhorn.io/engine-image: ei-ef01bf86
      image: rancher/mirrored-longhornio-longhorn-engine:v1.4.1
      image: docker.io/rancher/mirrored-longhornio-longhorn-engine:v1.4.1
      longhorn.io/engine-image: ei-ef01bf86
      image: rancher/mirrored-longhornio-longhorn-engine:v1.4.1
      image: docker.io/rancher/mirrored-longhornio-longhorn-engine:v1.4.1
      longhorn.io/engine-image: ei-ef01bf86
      image: rancher/mirrored-longhornio-longhorn-engine:v1.4.1
      image: docker.io/rancher/mirrored-longhornio-longhorn-engine:v1.4.1
```

**Comment by koshrf** [comment]
I upgraded the engine on the UI to use 1.4.1 and now it seems it is working as expected and I was able to delete the snapshot. But I'm not sure if I can delete the daemonset with the old version. Any suggestions ?

**Comment by derekbit** [comment]
Can you check if the old engine image is still used by other volumes on UI page > general > engine image?
If the reference count is 0, the daemonset will be automatically cleaned up later, or you can delete the engine image on the UI.

**Comment by koshrf** [comment]
> Can you check if the old engine image is still used by other volumes on UI page > general > engine image? If the reference count is 0, the daemonset will be automatically cleaned up later, or you can delete the engine image on the UI.

I upgraded all the volumes and waited few hours and now the old daemonset was deleted. Thank you very much for the help and support, it is all working now, I'm going to close the issue then.
