### ISSUE TITLE
Support scheduling replica with hard anti-affinity

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#586]
https://github.com/rancher/longhorn/issues/570

Currently, we're using `soft anti-affinity` rules for replica scheduling. Though for many, scheduling more than one replicas per node doesn't make sense. It helps with bit rot but that's only necessary when you're down to the last node, which shouldn't happen normally.

We will introduce a `Replica Hard Anti Affinity` option in the `Scheduling` setting section, which will prevent scheduler to schedule future replicas on the nodes that already runs a healthy replica of the same volume. With this option enabled, the volume should never have limited or no redundancy, but it's possible for volume to be degraded and unable to heal (since there can be no nodes available for scheduling a new replica).

**Comment by meldafrawi** [comment]
Steps to test:
  - Create a Kubernetes cluster with `N` worker nodes , install longhorn, and create Longhorn StorageClass.
  - On `Settings/General` page, check `Replica Hard Anti Affinity` and click save.
  - Create a longhorn volume with number of replicas = `N-1`, you should see on `Volume Details` page `Replica Scheduling Failure`.

  - [x] You should not be able to attach the volume to a Node and you should see an error indicating that:

    ```unable to attach volume **X** to **Node Y**: volume **X** not scheduled```

- Create a new worker node to the kubernetes cluster, longhorn should be able to schedule a new replica of the volume to this node, Volume state should be `Healty`

- [x]  You should be able now to attach the volume to a node.

**Comment by vistalba** [comment]
Is this now possible? I run into a major outage because of that behavior. Any ETA?

**Comment by yasker** [comment]
@vistalba It would be in v0.6.0. Coming in a few weeks.
