### ISSUE TITLE
[BUG] Unable to expand volume

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#5860]
## Describe the bug (🐛 if you encounter this issue)

Try to expand volume, the following error presents:
```
unable to expand volume test-1: persistentvolumeclaims "test-1" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize
```

## To Reproduce

1. Create a volume from Longhorn UI
2. Create PV/PVC fro this volume from Longhorn UI
3. Expand this volume from Longhorn UI
4. See error:
```
unable to expand volume test-1: persistentvolumeclaims "test-1" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize
```

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.4.x-head, master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by mantissahz** [comment]
@yangchiu the expansion behavior had be changed after this PR https://github.com/longhorn/longhorn-manager/pull/1847 merged
The default Longhorn Static StorageClass `longhorn-static` does not exist so it is not allowed to expand the volume (PVC should be expanded first)

**Comment by yangchiu** [comment]
OK! Then there are some test cases needed to be refined:

`test_basic.py::test_expansion_canceling`
`test_basic.py::test_expansion_with_scheduling_failure`

I'll close this and open another one for the test cases.

Thanks for the prompt reply!
