### ISSUE TITLE
[IMPROVEMENT] Remove privilege requirement from lifecycle jobs

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5862]
Good question. It was enabled by this commit https://github.com/longhorn/longhorn/commit/eb767033390cc31c2a01ec3f93dfd2eb3ff05b1a

But I just walked through the post-upgrade and uninstall job. They are just doing operations against kubeAPI. Not sure why we need them to be privileged

_Originally posted by @PhanLe1010 in https://github.com/longhorn/longhorn/pull/5567#discussion_r1185639986_

**Comment by innobead** [comment]
@mantissahz Try to fix this together with upgrade enforcement. Thanks.

cc @PhanLe1010

**Comment by innobead** [comment]
@mantissahz need to check if we need to update the doc.

**Comment by chriscchien** [comment]
Hi @mantissahz ,

From test [steps](https://github.com/longhorn/longhorn/issues/5862#issuecomment-1537864310), I can install/uninstall Longhorn by `kebectl`, but when I try upgrade Longhorn from v1.4.2-rc1 to master by `helm`, I got below error

```
it checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
root@ip-172-31-81-81:/home/ubuntu/k9s/longhorn# helm upgrade longhorn ./chart/ -n longhorn-system
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
Error: UPGRADE FAILED: pre-upgrade hooks failed: 1 error occurred:
	* job failed: BackoffLimitExceeded
```

pre upgrade pod log
```
│ panic: unrecognized command: pre-upgrade                                                                                                                                                                │
│                                                                                                                                                                                                         │
│ goroutine 1 [running]:                                                                                                                                                                                  │
│ main.cmdNotFound(0xc00065eba0?, {0x7ffd4ed1b0fc?, 0xc00065ebc8?})                                                                                                                                       │
│     /go/src/github.com/longhorn/longhorn-manager/main.go:15 +0x67                                                                                                                                       │
│ github.com/urfave/cli.ShowCommandHelp(0xc0000fdb80, {0x7ffd4ed1b0fc, 0xb})                                                                                                                              │
│     /go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/help.go:213 +0x404                                                                                                        │
│ github.com/urfave/cli.glob..func1(0x1?)                                                                                                                                                                 │
│     /go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/help.go:21 +0x34                                                                                                          │
│ github.com/urfave/cli.HandleAction({0x1d4a180?, 0x225bf18?}, 0xc00051fa40?)                                                                                                                             │
│     /go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:524 +0x50                                                                                                          │
│ github.com/urfave/cli.(*App).Run(0xc00051fa40, {0xc000136000, 0x2, 0x2})                                                                                                                                │
│     /go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:286 +0x7db                                                                                                         │
│ main.main()                                                                                                                                                                                             │
│     /go/src/github.com/longhorn/longhorn-manager/main.go:65 +0x83b                                                                                                                                      │
│ Stream closed EOF for longhorn-system/longhorn-pre-upgrade-mtbjp (longhorn-post-upgrade)

**Comment by mantissahz** [comment]
@chriscchien 
The command `pre-upgrade` is not really added into `longhorn-manager` image now.
https://github.com/longhorn/longhorn-manager/pull/1892 will do.

**Comment by chriscchien** [comment]
Verified in longhorn master (longhorn-manager `c05bf1`) with test [steps](https://github.com/longhorn/longhorn/issues/5862#issuecomment-1537864310)
Result **Pass**

- Install / uninstall Longhorn by `kubectl` success
- Upgrade Longhorn from v1.4.1 to master by `helm` success
- Upgrade Longhorn from v1.4.2-rc1 to master by `helm` success
- After upgrade, uninstall Longhorn by `helm` success

**Comment by innobead** [comment]
@chriscchien can we test failed case? like 1.3 to 1.5/master?

**Comment by chriscchien** [comment]
Hi @mantissahz , I tried upgrade Longhorn from v1.3.x to master-head by `kubectl`, I saw daemonset components(longhorn-manager, longhorn-csi-plugin, engine-image) not upgraded and not reboot. Images kept in v1.3.x.

But I saw below deployment components had upgraded to newer version as the setting in master-head [manifest](https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml)

- longhorn-ui
- longhorn-driver-deployer 
- csi-attacher
- csi-provisioner
- csi-resizer
- csi-snapshotter

I can recovery them by apply v1.3.x manifest again, not sure if this is the correct behavior? thank you.

**Comment by mantissahz** [comment]
@chriscchien
The deployment will be updated by manifest, but the new `longhorn-driver-deployer`  pod will be waiting for new `longhorn-manager` pod running successfully.
And old pods should be working as usual.

**Comment by chriscchien** [comment]
Hi @mantissahz, I can do

- [x] Upgrade fail from v.1.3.x to master and can roll back by `kubectl`
- [x] Upgrade fail from v.1.3.x to master and can roll back by `helm`

But when I try downgrade form master to v1.3.x by `kubectl`. I can not see block message from console and the longhorn-manger imagre changed to v1.3.x-head

**Comment by innobead** [comment]
> May need test again after code of `jamesluhz/lh-manager:v1.4.x-upgrade-path` and `jamesluhz/lh-manager:v1.3.x-upgrade-path` merged into related branch
> 

@mantissahz What else we need to update/fix? I assumed all changes have been merged, right?

**Comment by mantissahz** [comment]
Yes, there is nothing needed to fix or update. 
We could close it if verified.

**Comment by chriscchien** [comment]
After discussed with @mantissahz , we can follow test result [here](https://github.com/longhorn/longhorn/issues/5862#issuecomment-1545309093) and close this ticket, thank you.
