### ISSUE TITLE
[TASK] Rlease 1.4.2

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5864]
**What's the task? Please describe.**
Action items for releasing v1.4.2

**Describe the items of the task (DoD, definition of done) you'd like.**
  - Pre-Release
    - [x] Regression test plan (manual) - @khushboo-rancher 
    - [x] Run e2e regression for pre-GA milestones (`install`, `upgrade`) - @yangchiu 
    - [x] Run security testing of container images for pre-GA milestones - @yangchiu 
    - [x] Verify longhorn chart PR to ensure all artifacts are ready for GA (`install`, `upgrade`)  @yangchiu  
       - https://github.com/longhorn/longhorn/tree/v1.4.1-rc2 (`longhorn/longhorn`)
       - https://github.com/longhorn/charts/tree/v1.4.x (`longhorn/charts`)
    - [x] Run core testing (install, upgrade) for GA build from the previous patch and the last patch of the previous feature release (1.4.1 & 1.3.3). - @yangchiu 
  - Release
    - [x] Release longhorn/chart from the release branch to publish to ArtifactHub
    - [x] Release note
	     - [x] Deprecation note
	     - [x] Upgrade notes including highlighted notes, deprecation, compatible changes, and others impacting the current users
  - Post-Release
    - [ ] ~Create a new release branch of manager/ui/tests/engine/longhorn instance-manager/share-manager/backing-image-manager when creating the RC1~
    - [x] Update https://github.com/longhorn/longhorn/blob/master/deploy/upgrade_responder_server/chart-values.yaml @PhanLe1010 
    - [x] Add another request for the rancher charts for the next patch release (`1.4.3`) @rebeccazzzz  
  - Rancher charts: verify the chart is able to install & upgrade - @khushboo-rancher 
    - [x] rancher/image-mirrors update @weizhe0422 (@PhanLe1010 )
        - https://github.com/rancher/image-mirror/pull/391
    - [x] rancher/charts dev-2.6 & 2.7 branches for rancher marketplace @weizhe0422 (@PhanLe1010)
        - `dev-2.6`: https://github.com/rancher/charts/pull/2623
        - `dev-2.7`: https://github.com/rancher/charts/pull/2622

cc @longhorn/qa @longhorn/dev

**Comment by yangchiu** [comment]
Run e2e regression for pre-GA milestones (install, upgrade):

v1.4.2-rc1:
[amd64](https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-tests-sles-amd64/158/): 2 failures
[arm64](https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-tests-sles-arm64/151/): 2 failures
[amd64 upgrade](https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-upgrade-tests-sles-amd64/163/): 4 failures
[arm64 upgrade](https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-upgrade-tests-sles-arm64/155/): 2 failures

**Comment by yangchiu** [comment]
Verify longhorn chart PR to ensure all artifacts are ready for GA verified :

For both longhorn/longhorn v1.4.2-rc1 and longhorn/chart v1.4.2-rc1:

1. Fresh install - Pass
2. Upgrade from v1.3.3 to v1.4.2-rc1 - Pass
3. Upgrade from v1.4.1 to v1.4.2-rc1 - Pass
4. After install/upgrade to v1.4.2-rc1, below test items passed
   - Create a statefulset and write data
   - Upgrade to v1.4.2-rc1
   - Upgrade engine image
   - Scale down/up workload
   - Trigger replica rebuilding
   - Create system backup
   - Create volume backup and restored
   - Verify volume data
5. Uninstall

**Comment by yangchiu** [comment]
Run security testing of container images for pre-GA milestones:

[v1.4.2-rc1](https://ci.longhorn.io/job/private/job/image-security-scan/990/): 70 HIGH, 0 CRITICAL

**Comment by innobead** [comment]
@weizhe0422 Please help update the test result of the node-not-ready e2e test suite.

**Comment by yangchiu** [comment]
Run core testing (install, upgrade) for GA build from the previous patch and the last patch of the previous feature release (1.4.1 & 1.3.3)

[amd64](https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-tests-sles-amd64/163/): 0 failure
[arm64](https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-tests-sles-arm64/156/): 0 failure
[amd64 upgrade from v1.4.1](https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-upgrade-tests-sles-amd64/167/): 1 failure
[amd64 upgrade from v1.3.3](https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-upgrade-tests-sles-amd64/167/): 0 failure
[arm64 upgrade from v1.4.1](https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-upgrade-tests-sles-arm64/159/): 0 failure
[arm64 upgrade from v1.3.3](https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-upgrade-tests-sles-arm64/160/): 0 failure

Rerun the only failed test case of [amd64 upgrade from v1.4.1](https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-upgrade-tests-sles-amd64/167/) for 10 times, they all passed: https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-upgrade-tests-sles-amd64/168/

**Comment by innobead** [comment]
> * Post-Release
>   * [ ]  Add another request for the rancher charts for the next patch release (`1.4.3`) @rebeccazzzz
> * Rancher charts: verify the chart is able to install & upgrade - @khushboo-rancher
>   
>   * [ ]  rancher/image-mirrors update @weizhe0422 (@PhanLe1010 )
>     
>     * [docs(longhorn): Add longhorn 1.3.3 images rancher/image-mirror#377](https://github.com/rancher/image-mirror/pull/377)
>   * [ ]  rancher/charts dev-2.6 & 2.7 branches for rancher marketplace @weizhe0422 (@PhanLe1010)
>     
>     * `dev-2.6`: [Add Longhorn 1.3.3 chart with dev-2.6 rancher/charts#2558](https://github.com/rancher/charts/pull/2558)
>     * `dev-2.7`: [Add Longhorn 1.3.3 chart with dev-2.7 rancher/charts#2555](https://github.com/rancher/charts/pull/2555)
> 
> cc @longhorn/qa @longhorn/dev

@PhanLe1010 @weizhe0422 @rebeccazzzz Please start working on the post-release items. 

cc @khushboo-rancher

**Comment by weizhe0422** [comment]
UPDATE: All PRs which related to Rancher chart generation had been merged already.
