### ISSUE TITLE
[FEATURE] Add a brand new/empty bdev with WriteOnly mode to the RAID1 bdev

### ISSUE THREAD

**Issue by DamiaSan** [longhorn/longhorn#5865]
This feature is a step to implement the replica rebuilding without stopping the volume for all the time of the rebuild process

**Comment by innobead** [comment]
cc @longhorn/dev-data-plane

**Comment by DamiaSan** [comment]
Some implementations details:

- functionality check, only raid1 supports add
- function `raid_bdev_update` to manage incremented `num_base_bdevs`
- function `bdev_raid_add_base_bdev`
	- call `raid_bdev_add_base_device`
	- for each channel, call a function to get new channel `raid_ch->base_channel[i] = spdk_bdev_get_io_channel`

**Comment by DamiaSan** [comment]
Tests:

- [ ] add to non used raid in new slot
- [ ] add to non used raid in existing slot
- [ ] add to non used raid and after use it
- [ ] add to raid with superblock

**Comment by DamiaSan** [comment]
With the introduction of the external snapshot, write only mode is no more necessary
