### ISSUE TITLE
[FEATURE] Change parent of a logical volume for volume rebuild

### ISSUE THREAD

**Issue by DamiaSan** [longhorn/longhorn#5866]
This feature will be used at the end of the volume rebuild process: the just rebuilded snapshot stack must have as parent live data the volume added as read only bdev to the raid

**Comment by innobead** [comment]
cc @longhorn/dev-data-plane

**Comment by innobead** [comment]
@DamiaSan please don't add issues to the milestone directly, because PM will help with milestone assignment, but you can raise the priority of any issues you think we should add to which milestone. 

For the recent two issues you created, they are fine since we already discussed them in the sync call.

**Comment by DamiaSan** [comment]
I thought that this operation could simply consist in changing the reference of the backing device and of the parent id of the volume in such a way that they pointed to the snapshot we want, but it is not so simply. Because blobstore works on cluster basis: suppose that clusters at the same index has been allocated both in the snapshot and in the logical volume, but written in different blocks: in this case the blobstore read only the cluster of the volume and so we don't have the data of the snapshot. During "normal" write operation it works using Copy-on-write (see https://spdk.io/doc/blob.html for reference), so before to write the data into the cluster of the volume, blobstore read the data of the corresponding cluster of the snapshot. So, to perform the volume set parent, I have to merge the data of the clusters allocated both in the volume and in the snapshot. And the consequence is that the set parent operation is not simply a metadata operation but it involves data copy, so its duration can be longer

**Comment by DamiaSan** [comment]
Thinking better to the problem above, we can't solve it only looking and reading from the parent snapshot, we should involve in the operations all snapshots of the chain. Because a cluster could be allocated both by the head volume and by a older snapshot but not by snapshots in the middle ...

**Comment by shuo-wu** [comment]
> Because blobstore works on cluster basis

Does this mean that, each time we write a block (4096 Bytes for example) to a lvol, SPDK will read the whole cluster data (1MB for example), modify that block, then flush the whole cluster data into the disk (COW)? This looks inefficient for random IO performance. Not sure why SPDK prefers this design...

> Thinking better to the problem above, we can't solve it only looking and reading from the parent snapshot, we should involve in the operations all snapshots of the chain.
> Maybe we could simply copy the data from the write only volume in the raid1 to the head volume of the just rebuilt snapshot chain, and after change the replica in the raid1 ...

I didn't get the solution you mentioned but I understood the issue you were worried about...  
I am thinking if we can make the RAID IO more intelligent as an alternative solution: If there are WO bdevs in the list, the COW should happen in the RAID level. In other words, when a write request comes, the RAID should read the whole cluster from a RW base bdev, modify the block the write request is targeting, then issue the cluster-based write to all base bdevs. This idea is similar to [what we have already done in the legacy volume](https://github.com/longhorn/longhorn-engine/blob/d1d6d308d37a5b465bc1c2824da2e0702830de7d/pkg/controller/control.go#L863-L864).

**Comment by shuo-wu** [comment]
> the time the I/O is stopped can be greater because we have to wait the copy of lvol_temp

The IO pause time for this copy is unpredictable. If a RAID is used by a write-intensive applications, and the rebuilding over the existing snapshots would take hours, then the newly written data in `lvol_temp` may be pretty large. Copying this kind of `lvol_temp` may take minutes or even hours as well, which is unacceptable for users or online rebuilding scenarios.

> Because doing the COW in the RAID, we will read from the rw base bdev for every write operation.

In comparison, I think this cost is acceptable unless the performance is worse than the legacy volumes.

**Comment by shuo-wu** [comment]
BTW, the `lvol_temp` handling or removal mayh be a problem. As I mentioned in the snapshot feature ticket, directly deleting this (tmp) head lvol would lead to the whole snapshot chain cleanup. Will the upcoming API support connect a snapshot into a new head lvol (without removing the old head lvol `lvol_temp`)?

**Comment by DamiaSan** [comment]
In the example I described above, `lvol_temp` has no snapshots and there is no need of a new API to connect a snapshot to a new head lvol.
However, as I wrote in snapshot feature [ticket](https://github.com/longhorn/longhorn/issues/6137), deleting a head lvol doesn't cause the snapshots deletion.

**Comment by derekbit** [comment]
cc @james-munson

**Comment by shuo-wu** [comment]
> However, as I wrote in snapshot feature https://github.com/longhorn/longhorn/issues/6137, deleting a head lvol doesn't cause the snapshots deletion.

Got it. I just re-tried it. You are right. The snapshots won't be cleaned up after the head lvol deletion.

> In the example I described above, lvol_temp has no snapshots and there is no need of a new API to connect a snapshot to a new head lvol.

Sorry I mean `lvol2` in your example. But I think the API is for connecting a snapshot lvol with a regular lvol anyway.

**Comment by DamiaSan** [comment]
The right solution, to do what we want, can be to use external snapshot: in this way we can do COW in an efficient way, because it is done at blob layer. Let's make an example of volume rebuilding: we have `lvol1` on node1 that has one snapshot, `snap1_1`. We have to rebuild `lvol2` on node 2, and this can be done in two phases.

Phase1, create the volume to be added in WO mode to the RAID:
- pause I/O
- on node1,make a snapshot of `lvol1` called `snap1_2` (this is the snapshot at the top of the snapshot stack, below the head lvol)
- on node1, export `snap1_2` via nvme-of 
- on node2, attach to `snap1_2`
- on node2, create `lvol2` with `snap1_2` as external snapshot with RPC ` bdev_lvol_clone_bdev.` This means that `lvol2` is a clone of `snap1_2`, but they reside on different nodes
- on node2, export `lvol2` via nvme-of
- on node1, attach to to `lvol2`
- on controller node, add `lvol2` to the RAID1 in WO mode
- resume I/O

Phase2, rebuild the snapshot stack:
- on node2, create `lvol_temp`
- on node2, export `lvol_temp` via nvme-of
- on node1, attach to `lvol_temp`
- on node1, shallow copy of `snap1_1` into `lvol_temp`
- on node2, make a snapshot of `lvol_temp` called `snap2_1`
- on node1, shallow copy of `snap1_2` into `lvol_temp`
- on node2, make a snapshot of `lvol_temp` called `snap2_2`
- pause I/O
- on node2, change the parent of `snap2_2` from `lvol_temp` to `lvol2`
- on node1, put `lvol2` in RAID as RW
- resume I/O
- delete `lvol_temp`

**Comment by shuo-wu** [comment]
> - on node2, create lvol2 with snap1_2 as external snapshot with RPC  bdev_lvol_clone_bdev. This means that lvol2 is a clone of snap1_2, but they reside on different nodes
> - on node2, export lvol2 via nvme-of
> - on node1, attach to to lvol2
> - on controller node, add lvol2 to the RAID1 in WO mode

Do we still need to export `lvol2` and attach it on node1? Can we directly add this cloned `lvol2` to the RAID?

BTW, will exporting `snap1_2` affect `lvol1`?

**Comment by DamiaSan** [comment]
> Do we still need to export `lvol2` and attach it on node1? Can we directly add this cloned `lvol2` to the RAID?

I mean: add to the RAID the "exported" version of `lvol2`, sorry. `lvol2` is directly accessible only in the node where its lvolstore resides.


> BTW, will exporting snap1_2 affect lvol1?

No, exporting `snap1_2` should not affect `lvol1`: when you add the snapshot as namespace to a nvmf subsystem, the bdev relative to the snapshot is claimed with mode `SPDK_BDEV_CLAIM_EXCL_WRITE`, which means _exclusive writer, with allowances for legacy behavior_. This means that only the nvmf subsystem can make I/O over this bdev (in this case only read are allowed, because snapshot are read only), but the legacy behavior of the snapshot is preserved, so `lvol1` can continue to read from it.

**Comment by shuo-wu** [comment]
> the bdev relative to the snapshot is claimed with mode SPDK_BDEV_CLAIM_EXCL_WRITE

Which bdev do you mean? The attached nvme bdev `lvol2` of this exported snapshot `snap1_2`? And why is it a **writer**? And is writing data to `lvol2` allowed? Where/Which lvstore will be the data written to `lvol2` stored?

> the legacy behavior of the snapshot is preserved, so lvol1 can continue to read from it.

Is write allowed for `lvol1` as well?

**Comment by DamiaSan** [comment]
> Which bdev do you mean? The attached nvme bdev `lvol2` of this exported snapshot `snap1_2`? And why is it a **writer**? And is writing data to `lvol2` allowed? Where/Which lvstore will be the data written to `lvol2` stored?

When you create a lvol, a bdev is created on top of it. It is the bdev that you have in the response of `bdev_get_bdevs` RPC, for example:
```
    "name": "97538c3f-72ae-4091-b19b-e9fb144ed84a",
    "aliases": [
      "lvs2/snap2"
    ],
    "product_name": "Logical Volume",
    "block_size": 512,
    "num_blocks": 40960,
    "uuid": "97538c3f-72ae-4091-b19b-e9fb144ed84a",
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": false,
    "zoned": false,
    "supported_io_types": {
      "read": true,
      "write": false,
      "unmap": false,
      "write_zeroes": false,
      "flush": false,
      "reset": true,
      "compare": false,
      "compare_and_write": false,
      "abort": false,
      "nvme_admin": false,
      "nvme_io": false
    },
    "driver_specific": {
      "lvol": {
        "lvol_store_uuid": "0c7337e3-2add-4909-abd5-76275e2ed72f",
        "base_bdev": "Aio2",
        "thin_provision": true,
        "snapshot": true,
        "clone": false,
        "clones": [
          "lvol2"
        ],
        "esnap_clone": false
      }
    }
  }
```



> Is write allowed for `lvol1` as well?

Yes

**Comment by shuo-wu** [comment]
> When you create a lvol, a bdev is created on top of it. It is the bdev that you have in the response of bdev_get_bdevs RPC, for example:

I knew this part. 
OK you mean the snapshot bdev `snap1_2` will be claimed as mode `SPDK_BDEV_CLAIM_EXCL_WRITE`? I still don't understand what exclusive writer is. Does it just mean that the existing/old head lvol can still read data from it?

~~And I want to confirm, where the cloned `lvol2` based on this exported `snap1_2` store data. When creating a lvol via clone, ~~ I see, `bdev_lvol_clone_bdev` is different from API `bdev_lvol_clone`. The latter one is what we will use for regular volume clone and it's already in `go-spdk-helper`. The former one is a new API for **external** snapshot bdevs only.

**Comment by DamiaSan** [comment]
> Does it just mean that the existing/old head lvol can still read data from it?

The head lvol of `snap1_2`, `lvol1`, can continue to read from it; and this is the _legacy behavior_. The nvmf subsystem, to which `snap1_2` is added as namespace, is the unique actor that can make I/O over the bdev relative to `snap1_2`. In our case, due to the fact that `snap1_2` is a snapshot, only read operations can be done over it.

Before adding `snap1_2` to the nvmf subsystem, the situation is the following:
```
  {
    "name": "97538c3f-72ae-4091-b19b-e9fb144ed84a",
    "aliases": [
      "lvs2/snap1_2"
    ],
    "product_name": "Logical Volume",
    "block_size": 512,
    "num_blocks": 40960,
    "uuid": "97538c3f-72ae-4091-b19b-e9fb144ed84a",
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": false,
    "zoned": false,
    "supported_io_types": {
      "read": true,
      "write": false,
      "unmap": false,
      "write_zeroes": false,
      "flush": false,
      "reset": true,
      "compare": false,
      "compare_and_write": false,
      "abort": false,
      "nvme_admin": false,
      "nvme_io": false
    },
    "driver_specific": {
      "lvol": {
        "lvol_store_uuid": "0c7337e3-2add-4909-abd5-76275e2ed72f",
        "base_bdev": "Aio2",
        "thin_provision": true,
        "snapshot": true,
        "clone": false,
        "clones": [
          "lvol1"
        ],
        "esnap_clone": false
      }
    }
  },
  {
    "name": "1687d1a6-02ae-4386-9b2b-021562ffdbc9",
    "aliases": [
      "lvs2/lvol1"
    ],
    "product_name": "Logical Volume",
    "block_size": 512,
    "num_blocks": 40960,
    "uuid": "1687d1a6-02ae-4386-9b2b-021562ffdbc9",
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": false,
    "zoned": false,
    "supported_io_types": {
      "read": true,
      "write": true,
      "unmap": true,
      "write_zeroes": true,
      "flush": false,
      "reset": true,
      "compare": false,
      "compare_and_write": false,
      "abort": false,
      "nvme_admin": false,
      "nvme_io": false
    },
    "driver_specific": {
      "lvol": {
        "lvol_store_uuid": "0c7337e3-2add-4909-abd5-76275e2ed72f",
        "base_bdev": "Aio2",
        "thin_provision": true,
        "snapshot": false,
        "clone": true,
        "base_snapshot": "snap1_2",
        "esnap_clone": false
      }
    }
  }
```
After adding, it becomes:
```
  {
    "name": "97538c3f-72ae-4091-b19b-e9fb144ed84a",
    "aliases": [
      "lvs2/snap1_2"
    ],
    "product_name": "Logical Volume",
    "block_size": 512,
    "num_blocks": 40960,
    "uuid": "97538c3f-72ae-4091-b19b-e9fb144ed84a",
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": true,
    "claim_type": "exclusive_write",
    "zoned": false,
    "supported_io_types": {
      "read": true,
      "write": false,
      "unmap": false,
      "write_zeroes": false,
      "flush": false,
      "reset": true,
      "compare": false,
      "compare_and_write": false,
      "abort": false,
      "nvme_admin": false,
      "nvme_io": false
    },
    "driver_specific": {
      "lvol": {
        "lvol_store_uuid": "0c7337e3-2add-4909-abd5-76275e2ed72f",
        "base_bdev": "Aio2",
        "thin_provision": true,
        "snapshot": true,
        "clone": false,
        "clones": [
          "lvol1"
        ],
        "esnap_clone": false
      }
    }
  },
  {
    "name": "1687d1a6-02ae-4386-9b2b-021562ffdbc9",
    "aliases": [
      "lvs2/lvol1"
    ],
    "product_name": "Logical Volume",
    "block_size": 512,
    "num_blocks": 40960,
    "uuid": "1687d1a6-02ae-4386-9b2b-021562ffdbc9",
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": false,
    "zoned": false,
    "supported_io_types": {
      "read": true,
      "write": true,
      "unmap": true,
      "write_zeroes": true,
      "flush": false,
      "reset": true,
      "compare": false,
      "compare_and_write": false,
      "abort": false,
      "nvme_admin": false,
      "nvme_io": false
    },
    "driver_specific": {
      "lvol": {
        "lvol_store_uuid": "0c7337e3-2add-4909-abd5-76275e2ed72f",
        "base_bdev": "Aio2",
        "thin_provision": true,
        "snapshot": false,
        "clone": true,
        "base_snapshot": "snap1_2",
        "esnap_clone": false
      }
    }
  }
```
As you can see, `snap1_2` is still a snapshot of `lvol1`, but now it is claimed as `exclusive_write` (and write I/O is not supported)

**Comment by DamiaSan** [comment]
> I see, `bdev_lvol_clone_bdev` is different from API `bdev_lvol_clone`. The latter one is what we will use for regular volume clone and it's already in `go-spdk-helper`. The former one is a new API for **external** snapshot bdevs only.

We will use  `bdev_lvol_clone_bdev` only during the rebuild process. To revert a volume to a particular snapshot we will continue to use `bdev_lvol_clone` . `bdev_lvol_clone_bdev` creates a clone from an external snapshot, i.e. a snapshot that comes from another lvstore (in our case from another node).

**Comment by DamiaSan** [comment]
As needed by @derekbit for the backup restore operation, this functionality will be extended to set the parent of any kind of logical volume, not only of external snapshot's clone. So we can set the snapshot parent for a volume:

- clone of a snapshot
- clone of an external snapshot 
- not clone

This enhancement has already been done for upstream, so now I will port it back on our downstream repo and will update PR https://github.com/longhorn/spdk/pull/16. The API has been renamed to `bdev_lvol_set_parent` to distinguish it from a new enhancement I am doing directly on upstream to set an external snapshot as the parent of a lvol.
