### ISSUE TITLE
[IMPROVEMENT] Volumes: metrics for snapshots include (size and type: system vs user)

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5869]
Volumes: metrics for backups and snapshots include (count and size and type: system vs user), to better understand how the actual size is summed up.

_Originally posted by @ulikl in https://github.com/longhorn/longhorn/issues/5235#issuecomment-1536418495_

**Comment by c3y1huang** [comment]
We will be excluding the following:
- The total size and count of backups: [link to discussion](https://github.com/longhorn/longhorn-manager/pull/2377#discussion_r1429718330)
- The total size and count of snapshots: [link to discussion](https://github.com/longhorn/longhorn-manager/pull/2377#discussion_r1430718606)

What will be included:
- The actual size of the snapshot.

**Comment by chriscchien** [comment]
Hi @c3y1huang ,

In my test, metric `longhorn_snapshot_actual_size_bytes` represent sanpshot correctly when there is only 1 snapshot
```
k get snapshot -A
NAMESPACE         NAME                                   VOLUME                                     CREATIONTIME           READYTOUSE   RESTORESIZE   SIZE        AGE
longhorn-system   171e4299-2c9c-4ddb-a172-0473d24a8d14   pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020   2023-12-21T07:48:20Z   true         1073741824    103440384   4m10s
root@ip-172-31-37-229:/home# curl -sSL http://10.42.2.35:9500/metrics | grep longhorn_snapshot_actual_size_bytes
# HELP longhorn_snapshot_actual_size_bytes Actual size of this snapshot
# TYPE longhorn_snapshot_actual_size_bytes gauge
longhorn_snapshot_actual_size_bytes{user_created="true",volume="pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020"} 1.03440384e+08
```

But when there are multiple snapshots exist, there will be always 1 snapshot not appeared in metric `longhorn_snapshot_actual_size_bytes` result (the metric result will not always the same but always not display all snapshots ),  thank you.
```
k get snapshot -A
NAMESPACE         NAME                                   VOLUME                                     CREATIONTIME           READYTOUSE   RESTORESIZE   SIZE        AGE
longhorn-system   171e4299-2c9c-4ddb-a172-0473d24a8d14   pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020   2023-12-21T07:48:20Z   true         1073741824    103440384   10m
longhorn-system   7adfdf2b-7974-400a-adef-d3b79e0f22a5   pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020   2023-12-21T07:53:13Z   true         1073741824    62971904    5m58s
longhorn-system   0b7bc3c2-6f13-40a8-86f9-9ef8d3bc7b8f   pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020   2023-12-21T07:53:51Z   true         1073741824    73482240    5m18s
longhorn-system   22bcd321-476b-4a25-8de0-4446229bfec0   pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020   2023-12-21T07:54:44Z   true         1073741824    83947520    4m28s
root@ip-172-31-37-229:/home# curl -sSL http://10.42.2.35:9500/metrics | grep longhorn_snapshot_actual_size_bytes
* collected metric "longhorn_snapshot_actual_size_bytes" { label:{name:"user_created" value:"true"} label:{name:"volume" value:"pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020"} gauge:{value:7.348224e+07}} was collected before with the same name and label values
* collected metric "longhorn_snapshot_actual_size_bytes" { label:{name:"user_created" value:"true"} label:{name:"volume" value:"pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020"} gauge:{value:8.394752e+07}} was collected before with the same name and label values
* collected metric "longhorn_snapshot_actual_size_bytes" { label:{name:"user_created" value:"true"} label:{name:"volume" value:"pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020"} gauge:{value:1.03440384e+08}} was collected before with the same name and label values

```

**Comment by c3y1huang** [comment]
> Hi @c3y1huang ,
> 
> In my test, metric `longhorn_snapshot_actual_size_bytes` represent sanpshot correctly when there is only 1 snapshot
> 
> ```
> k get snapshot -A
> NAMESPACE         NAME                                   VOLUME                                     CREATIONTIME           READYTOUSE   RESTORESIZE   SIZE        AGE
> longhorn-system   171e4299-2c9c-4ddb-a172-0473d24a8d14   pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020   2023-12-21T07:48:20Z   true         1073741824    103440384   4m10s
> root@ip-172-31-37-229:/home# curl -sSL http://10.42.2.35:9500/metrics | grep longhorn_snapshot_actual_size_bytes
> # HELP longhorn_snapshot_actual_size_bytes Actual size of this snapshot
> # TYPE longhorn_snapshot_actual_size_bytes gauge
> longhorn_snapshot_actual_size_bytes{user_created="true",volume="pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020"} 1.03440384e+08
> ```
> 
> But when there are multiple snapshots exist, there will be always 1 snapshot not appeared in metric `longhorn_snapshot_actual_size_bytes` result (the metric result will not always the same but always not display all snapshots ), thank you.
> 
> ```
> k get snapshot -A
> NAMESPACE         NAME                                   VOLUME                                     CREATIONTIME           READYTOUSE   RESTORESIZE   SIZE        AGE
> longhorn-system   171e4299-2c9c-4ddb-a172-0473d24a8d14   pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020   2023-12-21T07:48:20Z   true         1073741824    103440384   10m
> longhorn-system   7adfdf2b-7974-400a-adef-d3b79e0f22a5   pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020   2023-12-21T07:53:13Z   true         1073741824    62971904    5m58s
> longhorn-system   0b7bc3c2-6f13-40a8-86f9-9ef8d3bc7b8f   pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020   2023-12-21T07:53:51Z   true         1073741824    73482240    5m18s
> longhorn-system   22bcd321-476b-4a25-8de0-4446229bfec0   pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020   2023-12-21T07:54:44Z   true         1073741824    83947520    4m28s
> root@ip-172-31-37-229:/home# curl -sSL http://10.42.2.35:9500/metrics | grep longhorn_snapshot_actual_size_bytes
> * collected metric "longhorn_snapshot_actual_size_bytes" { label:{name:"user_created" value:"true"} label:{name:"volume" value:"pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020"} gauge:{value:7.348224e+07}} was collected before with the same name and label values
> * collected metric "longhorn_snapshot_actual_size_bytes" { label:{name:"user_created" value:"true"} label:{name:"volume" value:"pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020"} gauge:{value:8.394752e+07}} was collected before with the same name and label values
> * collected metric "longhorn_snapshot_actual_size_bytes" { label:{name:"user_created" value:"true"} label:{name:"volume" value:"pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020"} gauge:{value:1.03440384e+08}} was collected before with the same name and label values
> ```

```
* collected metric "longhorn_snapshot_actual_size_bytes" { label:{name:"user_created" value:"true"} label:{name:"volume" value:"pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020"} gauge:{value:7.348224e+07}} was collected before with the same name and label values
* collected metric "longhorn_snapshot_actual_size_bytes" { label:{name:"user_created" value:"true"} label:{name:"volume" value:"pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020"} gauge:{value:8.394752e+07}} was collected before with the same name and label values
* collected metric "longhorn_snapshot_actual_size_bytes" { label:{name:"user_created" value:"true"} label:{name:"volume" value:"pvc-00bd3dcf-3980-4d7b-84dc-33496acf5020"} gauge:{value:1.03440384e+08}} was collected before with the same name and label values
```
I will fix this. Thank you!

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `c46a54`) with test [steps](https://longhorn.io/docs/1.6.0/monitoring/metrics/#snapshot)

Created 4 snapshots with different sizes, they all reflected in metric `longhorn_snapshot_actual_size_bytes` correctly
```bash
root@ip-172-31-34-115:/home/ubuntu# k get snapshot -A
NAMESPACE         NAME                                   VOLUME                                     CREATIONTIME           READYTOUSE   RESTORESIZE   SIZE        AGE
longhorn-system   ea91da09-2794-46f0-a2fa-54b03a28056a   pvc-5b9cbfd4-3b30-473f-b599-456f7261a8a0   2023-12-22T07:21:27Z   true         10737418240   352571392   2m26s
longhorn-system   7c5633bf-2081-4ca8-a451-23ead06163ea   pvc-5b9cbfd4-3b30-473f-b599-456f7261a8a0   2023-12-22T07:22:00Z   true         10737418240   341979136   116s
longhorn-system   d9a9f913-29b0-4187-9b52-2bf840b6a48b   pvc-5b9cbfd4-3b30-473f-b599-456f7261a8a0   2023-12-22T07:22:46Z   true         10737418240   457359360   71s
longhorn-system   e84096ca-f84e-440c-8e25-86d495b342ae   pvc-5b9cbfd4-3b30-473f-b599-456f7261a8a0   2023-12-22T07:23:45Z   true         10737418240   555945984   11s
root@ip-172-31-34-115:/home/ubuntu# 
root@ip-172-31-34-115:/home/ubuntu# curl -sSL http://10.42.0.9:9500/metrics | grep longhorn_snapshot_actual_size_bytes
# HELP longhorn_snapshot_actual_size_bytes Actual size of this snapshot
# TYPE longhorn_snapshot_actual_size_bytes gauge
longhorn_snapshot_actual_size_bytes{snapshot="7c5633bf-2081-4ca8-a451-23ead06163ea",user_created="true",volume="pvc-5b9cbfd4-3b30-473f-b599-456f7261a8a0"} 3.41979136e+08
longhorn_snapshot_actual_size_bytes{snapshot="d9a9f913-29b0-4187-9b52-2bf840b6a48b",user_created="true",volume="pvc-5b9cbfd4-3b30-473f-b599-456f7261a8a0"} 4.5735936e+08
longhorn_snapshot_actual_size_bytes{snapshot="e84096ca-f84e-440c-8e25-86d495b342ae",user_created="true",volume="pvc-5b9cbfd4-3b30-473f-b599-456f7261a8a0"} 5.55945984e+08
longhorn_snapshot_actual_size_bytes{snapshot="ea91da09-2794-46f0-a2fa-54b03a28056a",user_created="true",volume="pvc-5b9cbfd4-3b30-473f-b599-456f7261a8a0"} 3.52571392e+08
```
