### ISSUE TITLE
[BUG]  longhorn-ui cannot download SupportBundle

### ISSUE THREAD

**Issue by smallteeths** [longhorn/longhorn#5882]
## Describe the bug (🐛 if you encounter this issue)

When the SupportBundle CR is not cleaned up in a timely manner, the UI cannot generate and download a new SupportBundle.

## To Reproduce

1. Go to 'Dashboard'
2. Click on 'Generate Support Bundle'
3. Refresh the current page without waiting for the progress bar to reach 100% when generating a Support Bundle.
4. Go to 'Dashboard'
5. Click on 'Generate Support Bundle'
6. see the error `failed to create SupportBundle: admission webhook "validator.longhorn.io" denied the request: please try again later. Another support-bundle-2023-05-08t07-18-42z is in ReadyForDownload phase`

<img width="1008" alt="截屏2023-05-08 下午3 33 11" src="https://user-images.githubusercontent.com/27733391/236763369-a560791b-45d6-4137-bf5c-755996df7786.png">

## Expected behavior

Please help to clear existing Support Bundle before downloading each time to enable the UI to download the latest Support Bundle.

## Environment

 - Longhorn version:
 - 1.4.x

cc @c3y1huang

**Comment by c3y1huang** [comment]
Workaround: delete the SupportBundle CR using kubectl.

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by innobead** [comment]
@c3y1huang is this a valid issue? I thought the support bundle is still ongoing and it will be ready at the end.

**Comment by c3y1huang** [comment]
> @c3y1huang is this a valid issue? I thought the support bundle is still ongoing asynchronously and it will be ready at the end.

This is a valid issue. When the page is refreshed/closed before UI calls `/v1/supportbundles/{name}/{bundleName}/download`, the SupportBundle CR will not get cleaned up.

**Comment by roger-ryao** [comment]
**Verified on master-head 20230531**

- longhorn master-head ([7b3b230](https://github.com/longhorn/longhorn/commit/7b3b230f471071f08b9621a165fab7887e087491))
- longhorn-manager master-head ([023dd3c](https://github.com/longhorn/longhorn-manager/commit/023dd3cbd5009f390608ea9cdd9f31bd397cf8a2))


**The test steps**

1. Go to the `Dashboard`.
2. Click on `Generate Support Bundle`.
3. Refresh the current page without waiting for the progress bar to reach 100% while generating the Support Bundle.
4. Go back to the `Dashboard`.
5. Click on `Generate Support Bundle`.
6. Encounter the error message `failed to create SupportBundle: admission webhook 'validator.longhorn.io' denied the request: please try again later. Another support-bundle-2023-05-31t08-25-34z is in the Generating phase,` 
7. Refresh the current page and click on `Generate Support Bundle` again at a later time.
8. We would be able to download the SupportBundle from the UI.

**Result Passed**

- [ ] doc: https://github.com/longhorn/website/pull/710
  - Hi @c3y1huang  : @innobead requested the addition of 1.4.x in [this comment](https://github.com/longhorn/website/pull/710#pullrequestreview-1448990325).
  - After https://github.com/longhorn/website/pull/710 is merged, I will close this ticket.
- [x] require/auto-e2e-test: [PR #1362](https://github.com/longhorn/longhorn-tests/pull/1362)
- [x] After encountering an error, refresh the current page and click on 'Generate Support Bundle' again at a later time. You will be able to download the SupportBundle from the UI.
![Screenshot_20230531_160933](https://github.com/longhorn/longhorn/assets/104337648/66df3229-9518-4123-b9db-cd7ea77bba59)
