### ISSUE TITLE
[IMPROVEMENT] Consolidate the mounts in longhorn-manager and instance-manager

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5883]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

As per https://github.com/longhorn/longhorn/issues/5856#issuecomment-1535590047, there will be some potential leftover backup store mount points (nfs/cifs) which are built into the Kernel after resetting the backup store. 

Currently, the backup store will be mounted in the below two places:
- longhorn-manager: backup target controller to update backup status from the store
- replica process: backup & restore

How to detach unused mount points when updating the backup target should be consistent for different cases as mentioned in  https://github.com/longhorn/longhorn/issues/5856#issuecomment-1534985865, the solution is like https://github.com/longhorn/longhorn-manager/pull/1848

The current situation is if the nfs backup store is reset, there will be a leftover. Before v1.4, A nfs mount is a hard mount for the nfs backup store, so it would cause high CPU usage if there are some leftover mount points. After that, there will be leftover mount points but will not cause critical resource consumption until this issue is fixed. 

## Describe the solution you'd like

As above

## Additional context

After discussed with @derekbit 
We agree the scope of this issue is to see if we can move the backup related operation like `list`, `remove` from **longhorn-manager** to **longhorn-instance-manager**.
1. We can get rid of using binary to do such operation in **longhorn-manager**
2. We only need to take care of mount point in **longhorn-instance-manager**

cc @ChanYiLin @derekbit @longhorn/qa

**Comment by innobead** [comment]
@ChanYiLin go discuss with @derekbit when working on this in 1.6.

**Comment by ChanYiLin** [comment]
Update the conclusion of the discussion in the ticket.

**Comment by ChanYiLin** [comment]
Just found the previous discussion about why not put all backup operations to longhorn-instance-manager
https://github.com/longhorn/longhorn-manager/pull/1361#issuecomment-1147257498

**Comment by ChanYiLin** [comment]
Close the issue since it is duplicated to https://github.com/longhorn/longhorn/issues/5741
The goal is to unmount the mount point in **longhorn-instance-manager** when the target is unset
