### ISSUE TITLE
[IMPROVEMENT] Configure log level of Longhorn components

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5888]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Currently, in longhorn components, we use `debug` level by default and regard `debug` as `info` to use in the code, so it would cause lots of logs especially periodical running code like controllers or monitors in longhorn manager or other components. 

Need to improve a few things here:
- Make the log level configurable via longhorn setting to apply to all managed components and the default is info, also it can be applied by chart values.yaml
- Review and update the log and log level used in longhorn-manager
  - Prevent repeated logs happening in the resync reconciling loop or monitors
  - Move verbose logs to debug or trace
  - Move meaningful logs to info
  - Move unexpected warning info to warn
  - Move failed log to error

Make this issue as improvement instead of a feature, since it can be backported to the supported release branches w/ no backward-compatible concerns. 

## Additional context

ref: https://github.com/longhorn/longhorn/issues/4069#issue-1258561084

cc @longhorn/dev

**Comment by innobead** [comment]
One issue was reported by users, https://github.com/longhorn/longhorn/issues/4069#issue-1258561084.

**Comment by ChanYiLin** [comment]
Hi @innobead 
I think we can review and merge these two PRs first to add the global setting for log level
- https://github.com/longhorn/longhorn/pull/5953
- https://github.com/longhorn/longhorn/pull/5953

I will create another PR for review all log message and their level.
Thanks

**Comment by derekbit** [comment]
TBH, setting the default log level to `Info` may not be good at this moment, as several valuable log messages that ought to be classified as `Info` are currently classified as `Debug`. I would advise that we utilize `Debug` as the default log level.

cc @innobead @ChanYiLin

**Comment by innobead** [comment]
@derekbit The goal is not just changing the default level but also need to correct the log level used  for each log. For example , if a debug log should be info, then it should be corrected as well.

Uncertainty somehow we believe, but let's clarify it first.

**Comment by ChanYiLin** [comment]
Hi @derekbit 
I agree with you here
In the future, we might need to ask user to change to debug level first before generating support bundle
So we can get more information from it
But we also got the feedback that log size is too big. That's why we have this ticket here.

So maybe you can also take a look on my PR
https://github.com/longhorn/longhorn-manager/pull/1923
Let's figure out what are the better logging conventions.
Thanks!

**Comment by derekbit** [comment]
I would suggest keeping "debug" as the default value for now as before. After we revisit and correct the log level of each log, we can change it into "info" level. WDYT?  @ChanYiLin @innobead

**Comment by innobead** [comment]
> I would suggest keeping "debug" as the default value for now as before. After we revisit and correct the log level of each log in each component, we can change it into "info" level. WDYT? @ChanYiLin @innobead

Knowing your concern, and this is what @ChanYiLin is doing. The log level will be only changed in the longhorn-manager as the first phase.

To make things proceed well, what we can do is to make the setting to INFO until @ChanYiLin fixes logging with the right level in longhorn-manager. After all are done, we can change the default level to info. 

WDYT?

**Comment by derekbit** [comment]
> > I would suggest keeping "debug" as the default value for now as before. After we revisit and correct the log level of each log in each component, we can change it into "info" level. WDYT? @ChanYiLin @innobead
> 
> 
> 
> Knowing your concern, and this is what @ChanYiLin is doing. The log level will be only changed in the longhorn-manager as the first phase.
> 
> 
> 
> To make things proceed well, what we can do is to make the setting to INFO until @ChanYiLin fixes logging with the right level in longhorn-manager. After all are done, we can change the default level to info. 
> 
> 
> 
> WDYT?

Sounds good.
Correct the log level of each log first, and the change the setting. Then, it can reduce the impact of the debugging process.

**Comment by innobead** [comment]
yeah, I know you and others getting impacted now since we already merge the level change. Discussed with @ChanYiLin , and he will set the log level to debug first.

**Comment by ChanYiLin** [comment]
Or lets keep the log level to Debug
For those who feels Longhorn log size is too large, they can adjust it by change the log level

**Comment by innobead** [comment]
> Or lets keep the log level to Debug For those who feels Longhorn log size is too large, they can adjust it by change the log level

Using debug log by default is not usual. As discussed, let's change to info until we are ready, at least the new mechanism is ready.

**Comment by derekbit** [comment]
> > Or lets keep the log level to Debug For those who feels Longhorn log size is too large, they can adjust it by change the log level
> 
> Using debug log by default is unusual, so we should correct this. As discussed, let's change to info until we are ready, at least the new mechanism is introduced.

Agree. Once the log messages have been settled down to the appropriate level, the log level should be set to "Info".
Many thanks for the change. The change flow can minize the impact of the development and debugging/analyzing process for SB from users.

**Comment by derekbit** [comment]
Just had a discussion with @ChanYiLin about the recurring log messages mentioned in this GitHub issue: https://github.com/longhorn/longhorn/issues/4069.

It appears that changing the log level setting to "info" can resolve the problem. However, we are unable to know the status/error of the scheduler, for example, no available disks or nodes.

I'm thinking whether it would be better to record the error in node conditions instead in the future. By doing so, we can prevent the excessive log message flooding and know the scheduler's status.

WDYT? @innobead @ChanYiLin

**Comment by innobead** [comment]
Sounds good to me.

**Comment by ChanYiLin** [comment]
Hi @innobead 
During the refactor, I got a question for these two conventions
- if an error will be consumed w/o being returned back to the caller, using warning, since it has been handled.
- If an error will be returned/bubbled up, suggest no extra logging but can be enriched with another error wrapper to prevent a duplicated error log. This needs to check if there would be a chance to have duplicated error message.

For those error bubbled up, we only wrap them with logging error. But most of the time the top caller for controller is as following
```
func (ec *EngineController) processNextWorkItem() bool {
	key, quit := ec.queue.Get()

	if quit {
		return false
	}
	defer ec.queue.Done(key)

	err := ec.syncEngine(key.(string))
	ec.handleErr(err, key)

	return true
}

func (ec *EngineController) handleErr(err error, key interface{}) {
	if err == nil {
		ec.queue.Forget(key)
		return
	}

	log := ec.logger.WithField("engine", key)
	if ec.queue.NumRequeues(key) < maxRetries {
		log.WithError(err).Warn("Error syncing Longhorn engine")
		ec.queue.AddRateLimited(key)
		return
	}

	utilruntime.HandleError(err)
	log.WithError(err).Warn("Dropping Longhorn engine out of the queue")
	ec.queue.Forget(key)
}
```

For those errors return to the top we still Warn them with 
```
log.WithError(err).Warn("Error syncing Longhorn engine")
```

Then when should we use `Error()` logging ?

**Comment by ChanYiLin** [comment]
I found we tend to log error when it happens and then return the error to the caller
```
log.WithError(err).Error("xxxx")
return err
```
then the error will eventually be warned again with 
```
log.WithError(err).Warn("Error syncing Longhorn engine")
```

Or maybe we can still follow the convention, don't log error but wrap and return
But change the top caller warning to error because it is indeed not handled in this reconcile loop
```
log.WithError(err).Error("Error syncing Longhorn engine") # change to error
```

**Comment by innobead** [comment]
Sounds good to me.

**Comment by ChanYiLin** [comment]
TODO
- [ ] share_manager_controller
- [ ] snapshot_controller
- [ ] support_bundle_controller
- [ ] system_backup_controller
- [ ] system_restore_controller
- [ ] system_rollout_controller
- [ ] uninstall_controller
- [ ] volume_attachment_controller
- [ ] volume_clone_controller
- [ ] volume_controller
- [ ] volume_eviction_controller
- [ ] volume_expansion_controller
- [ ] volume_restore_controller
- [ ] websocket_controller
- [ ] longhorn api
- [ ] longhorn csi

**Comment by innobead** [comment]
@ChanYiLin We have the log level setting now, so let's keep the log level to debug still in 1.5.0. If everything goes well, we can further change to info in a later version. WDYT?

Also, let's move this issue to ready-for-testing, so @longhorn/qa can help with the following test. Thanks.

**Comment by ChanYiLin** [comment]
No problem!

**Comment by innobead** [comment]
@weizhe0422 Please help verify this.

**Comment by weizhe0422** [comment]
## Environment
  - Longhorn version: v1.5.0-rc1 
     ![image](https://github.com/longhorn/longhorn/assets/17548901/b8ce4a61-aeca-442c-98fd-967c21e4741f)
  - cluster info
    - K8S version: v1.25.3+k3s1
    - master*1 + worker*3
      ![image](https://github.com/longhorn/longhorn/assets/17548901/5675681e-52c6-4b10-8c61-544d8edc5a41)

## Test result
under verify

 ## Test steps (refer to https://github.com/longhorn/longhorn/issues/5888#issuecomment-1578077505)
  - log level: `trace` < `debug` < `info` < `warn` < `error` < `fatal` < `panic`

**Scenario 1**
  1. Install Longhorn and checking the global setting: `log-level` default value is `Debug`
     ![image](https://github.com/longhorn/longhorn/assets/17548901/e2484082-08c3-45cf-9a4f-f34734910a5c)
  2. Do some operation includes volume creation and attach it, then generate backups
     - check the log should only appears the level upper than `debug`
       ![image](https://github.com/longhorn/longhorn/assets/17548901/b2ac1330-d4c6-441c-9f6f-7fc9cfbfd934)
  3. Change the log level to `Warn`
     ![image](https://github.com/longhorn/longhorn/assets/17548901/435be15c-535a-48a9-837c-79dd75718b44)
  4. Repeat to do some operation includes volume creation and attach it, then generate backups
     - check the log level should upper than `warn` level
       - `warning` level
          ![image](https://github.com/longhorn/longhorn/assets/17548901/7017e738-fd8a-4c66-8396-57751cc662f8)
       - `error` level  
          ![image](https://github.com/longhorn/longhorn/assets/17548901/1c3a4c05-08e6-42ff-b0c7-889e9a9ad768)
