### ISSUE TITLE
Instance manager 1.4.0 can't be deleted

### ISSUE THREAD

**Issue by Floeig** [longhorn/longhorn#5902]
## Question
> Suggest to use https://github.com/longhorn/longhorn/discussions to ask questions.

## Environment

 - Longhorn version: 1.4.1 using helm chart
 - Kubernetes version: 1.25
 - Node config
   - OS type and version: Ubuntu 22.04.1 LTS
   - CPU per node: 4
   - Memory per node: 8gb
   - Disk type: ssd
   - Network bandwidth and latency between the nodes: -
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Exoscale (cloud provider)

## Additional context

I can't delete the engine 1.4.0 data as there's references
![image](https://github.com/longhorn/longhorn/assets/29572254/a4e9abd7-0ba0-47a5-9cf5-c7cf7e5b9f9f)

but that is what I see below, there's no 1.4.0 instances of this and all of my volumes seems to have been upgraded

![image](https://github.com/longhorn/longhorn/assets/29572254/5bcfbdee-91cf-4050-91b2-b17fcbb44aef)

Any idea/suggestion ?

**Comment by Floeig** [comment]
> Can you provide the support bundle?
> 
> cc @ChanYiLin

I've sent it to your email

**Comment by ChanYiLin** [comment]
Hi @Floeig, Can you post it to here, so other team members can also analysis it, thanks!

**Comment by ChanYiLin** [comment]
Hi @Floeig 
Have you manually upgraded each volume's engine in the volume's page?

**Comment by Floeig** [comment]
@ChanYiLin 
No I had the the "Concurrent Automatic Engine Upgrade Per Node Limit" to 2 if my memory was correct.
I probably did 1 or 2 manually that semed stuck (or I wasn't patient enought).
At this moment I have put it back "Concurrent Automatic Engine Upgrade Per Node Limit" to 0, to see if I was able to do anytning. But I can only go back to 1.4.0 then forward again.

Maybe I need to do that for each of them... I havent tried that on enought volumes to see if that can potentially solve anything.
I'll try some old test/dev volumes to see if the numer decrease.
I'll let you know

**Comment by Floeig** [comment]
I've tried to downgrade/upgrade 9 volumes. The number of volume using 1.4.0 increased. when I upgraded them it went back to 44.
There's not that much other volumes that I could try to downgrade/upgrade. It looks like the 44 is actually 0 but somehow had not been initialised correclty.
Let me know if you want me to try anything

**Comment by derekbit** [comment]
@ttyS0 @Floeig  Can you provide a support bundle for further check? Thank you.

**Comment by Floeig** [comment]
Sorry, I did get the support bundle but forgot to add it to my previous comment.
[support-bundle-2023-05-11t07-57-33z.zip](https://github.com/longhorn/longhorn/files/11465068/support-bundle-2023-05-11t07-57-33z.zip)

**Comment by derekbit** [comment]
@Floeig 
Thanks for the support bundle.
Many replicas are using `longhorn-engine:v1.4.0` because of the [bug](https://github.com/longhorn/longhorn/issues/5762).

Can you apply the workaround in this ticket?
For the replicas using `longhorn-engine:v1.4.0`, you can delete them by `kubectl -n longhorn-system delete replica <name>`.

**Comment by ttyS0** [comment]
Here's the support bundle. 

I don't see any replicas using 1.4.0. 

[supportbundle_77290834-bb7d-491d-a2e1-ad17dc2c3c6c_2023-05-12T14-10-15Z.zip](https://github.com/longhorn/longhorn/files/11465307/supportbundle_77290834-bb7d-491d-a2e1-ad17dc2c3c6c_2023-05-12T14-10-15Z.zip)

**Comment by derekbit** [comment]
@ttyS0 Same issue. Please apply the solution in https://github.com/longhorn/longhorn/issues/5902#issuecomment-1545849055. Thank you.

**Comment by ttyS0** [comment]
The mutating web hook is already set to Fail. 

Deleting the stopped replicas cleared them out. Thanks!

For others reference, I used `kubectl get replica -n longhorn-system | grep -v running` to get a list of the replicas.

**Comment by Floeig** [comment]
@derekbit It's working, 

The interesting part is that theses replicas don't seems they are linked to 1.4.0 and aren't visible in the ui. But they are as it's working. 
Even the nodes don't exists anymore. looking at the "date" I'm wondering if it have happended during my migration from kubernetes 1.24 to 1.25... 

ex:
```bash
❯ kubectl -n longhorn-system get replicas
NAME                                                  STATE     NODE                                      DISK                                   INSTANCEMANAGER                                       IMAGE                               AGE
pvc-a7590866-cabc-4455-be04-1d2f19e66b63-r-8857253d   stopped   node-medium-2cpu-4ram-100gb-1e6d0-mulrq   da9e8bf6-3563-49f7-813a-5defd9f0b471                                                                                             78d
pvc-a7590866-cabc-4455-be04-1d2f19e66b63-r-9c364130   stopped                                                                                                                                                                              78d
pvc-a7590866-cabc-4455-be04-1d2f19e66b63-r-9f6bb9d5   stopped                                                                                                                                                                              78d
pvc-a7590866-cabc-4455-be04-1d2f19e66b63-r-ace7b86f   stopped                                                                                                                                                                              78d
pvc-a7590866-cabc-4455-be04-1d2f19e66b63-r-b2df283e   stopped                                                                                                                                                                              78d
pvc-a7590866-cabc-4455-be04-1d2f19e66b63-r-cc6b6e8a   stopped                                                                                                                                                                              78d
pvc-a7590866-cabc-4455-be04-1d2f19e66b63-r-d4c64c54   unknown   node-medium-2cpu-4ram-100gb-1e6d0-mulrq   da9e8bf6-3563-49f7-813a-5defd9f0b471   instance-manager-r-6496cb9f79a65599bfe47d15a857078c                                       78d
```
I hope that could help

Thanks a lot

**Comment by Orhideous** [comment]
Same issue for upgrade 1.4.1 → 1.4.2.

**Comment by derekbit** [comment]
> Same issue for upgrade 1.4.1 → 1.4.2.

Can you provide us with the support bundle?
I think the replicas are generated in v1.4.1 and exists before the upgrade.

**Comment by derekbit** [comment]
> Same issue for upgrade 1.4.1 → 1.4.2.

@Orhideous 
Can you provide us with the support bundle?
I think the replicas are generated in v1.4.1 and exist before the upgrade.

**Comment by Orhideous** [comment]
@derekbit It's unrelated now. Error was caused due to unfortunate combinations of multiple factors: tight memory conditions (so some of 1.4.2 instance managers couldn't start — `Node didn't have enough resource: cpu, requested: 480, used: 3602, capacity: 4000`), degraded volumes — and it turns out that longhorn was desperately restore replicas AND upgrade itself in the same time.
Anyway, I temporary scaled most resource-hungry statefulsets down to get room for an upgrade, and then manually cleaned up orphaned, stopped and just outdated replicas from 1.4.1 engine.
And that worked :sweat_smile:

**Comment by Dunge** [comment]
Had the same surprise upgrading from 1.4.1 to 1.4.2. Realized I had 356 invalid replica reference count?!?! I have no idea how could it reach that amount since I only have 12 volumes.

Deleted them all with 
```
kubectl -n longhorn-system get replica | grep stopped | awk '{ print $1 }' | xargs kubectl -n longhorn-system delete replica
```

Then I managed to delete the old engine image via the UI.

But then I started to receive kubernetes error events:
```
Readiness probe failed: ls: cannot access '/data/longhorn': No such file or directory 
Failed to garbage collect required amount of images. Attempted to free 2133662105 bytes, but only found 613012623 bytes eligible to free.
```

**Comment by Dunge** [comment]
Deleting the old revision instance manager pod was NOT a good idea. All ym workloads crashed. Grafana fails to restart.
```
MountVolume.SetUp failed for volume "pvc-5adce447-de57-474b-95f0-bf3f2f04f228" : applyFSGroup failed for vol pvc-5adce447-de57-474b-95f0-bf3f2f04f228: lstat /var/snap/microk8s/common/var/lib/kubelet/pods/9e70eebc-912f-487a-b829-0b6ea86a9903/volumes/kubernetes.io~csi/pvc-5adce447-de57-474b-95f0-bf3f2f04f228/mount/file-collections: input/output error
```

**Comment by derekbit** [comment]
@Dunge 
Can you check who are still using the old engine image or provide us with a support bundle?

**Comment by Dunge** [comment]
@derekbit A bit too late for that unfortunately since I killed everything.
Few minutes later some 2 nodes began to transform into NodeStatusUnknown and went crazy, ended up power cycling them all. I fear support bundle would be filled with too much unrelated errors.

**Comment by derekbit** [comment]
From your description, it seems some volumes are still using the old instance managers, so the direct deletions of the IMs lead to the crash.

**Comment by Floeig** [comment]
This solved my issue: 
https://github.com/longhorn/longhorn/issues/5902#issuecomment-1545869057

Thank you all
