### ISSUE TITLE
[TEST] Upgrade test always failed in master-head

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#5907]
## What's the test to develop? Please describe

~~Like https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/458/ or https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-2-stage-upgrade-tests-sles-arm64/167/~~

~~Probably related to https://github.com/longhorn/longhorn-tests/pull/1277.~~

~~In that PR, the `wait_for_all_instance_manager_running` is changed to check `instance_manager` instead of `instance_manager-e/r`. But in upgrade test, the previous version of Longhorn is installed first and it still uses `instance_manager-e/r`.~~

Like https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-upgrade-tests-sles-arm64/485/console

Upgrade Longhorn from v1.4.0 to master-head, the following error occurred in `test_upgrade`:

```
>       check_volume_data(vol_revision_enabled,
                          vol_revision_enabled_data_before_sys_upgrade)

test_upgrade.py:245: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common.py:2395: in check_volume_data
    check_device_data(dev, data, check_checksum)
common.py:2404: in check_device_data
    r_data = dev_read(dev, data['pos'], data['len'])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

dev = '/dev/longhorn/vol-revision-enabled', start = 6825498, count = 512

    def dev_read(dev, start, count):
        r_data = ""
>       fdev = open(dev, 'rb')
E       FileNotFoundError: [Errno 2] No such file or directory: '/dev/longhorn/vol-revision-enabled'

common.py:2456: FileNotFoundError
```

More investigation needed.

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

Add any other context or screenshots about the test request here.

**Comment by innobead** [comment]
cc @c3y1huang

**Comment by yangchiu** [comment]
Fixed in https://github.com/longhorn/longhorn-manager/pull/1920.
