### ISSUE TITLE
[BUG] Test case test_replica_schedule_to_disk_with_most_usable_storage failed on`SLE Micro`.

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#5909]
## Describe the bug (🐛 if you encounter this issue)

We have been supporting `SLE Micro` regression since version `v1.3.3` and `v1.4.2`. However, I have observed that the test case `test_replica_schedule_to_disk_with_most_usable_storage` is failing on **SLE Micro**.

## To Reproduce

1. https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/amd64/job/longhorn-tests-sle-micro-amd64/
2. Verify test result of `test_replica_schedule_to_disk_with_most_usable_storage`

## Expected behavior

We should have consistent test results on all distro.

## Log or Support bundle

- https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3764/testReport/tests/test_scheduling/test_replica_schedule_to_disk_with_most_usable_storage/
- [longhorn-tests-regression-3764-bundle.zip](https://github.com/longhorn/longhorn/files/11439870/longhorn-tests-regression-3764-bundle.zip)

```python
client = <longhorn.Client object at 0xffff920d4490>
volume_name = 'longhorn-testvol-pqjj7c'
request = <FixtureRequest for <Function test_replica_schedule_to_disk_with_most_usable_storage>>

    def test_replica_schedule_to_disk_with_most_usable_storage(client, volume_name, request):  # NOQA
        """
        Scenario : test replica schedule to disk with the most usable storage
    
        Given default disk 3/4 storage is reserved on the current node.
        And disk-1 with 1/4 of default disk space + 50 Gi.
        And add disk-1 to the current node.
    
        When create and attach volume.
    
        Then volume replica     on the current node scheduled to disk-1.
             volume replica not on the current node scheduled to default disk.
        """
        default_disk_available = 0
        self_host_id = get_self_host_id()
        cleanup_node_disks(client, self_host_id)
        node = client.by_id_node(self_host_id)
        disks = node.disks
        update_disks = get_update_disks(disks)
        for disk in update_disks.values():
            if disk.path != DEFAULT_DISK_PATH:
                continue
    
            default_disk_available = int(disk.storageMaximum/4)
            disk.storageReserved = disk.storageMaximum-default_disk_available
            break
    
        node = update_node_disks(client, node.name, disks=update_disks,
                                 retry=True)
        disks = node.disks
        for name, disk in iter(disks.items()):
            wait_for_disk_status(client, node.name,
                                 name, "storageReserved",
                                 disk.storageMaximum-default_disk_available)
    
>       disk_path = create_host_disk(client, 'vol-disk-1',
                                     str(50 * Gi + default_disk_available),
                                     node.name)

test_scheduling.py:1470: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common.py:5470: in create_host_disk
    volume = create_volume(client, vol_name, size, node_id, 1)
common.py:5455: in create_volume
    volume.attach(hostId=node_id)
longhorn.py:262: in cb
    return self.action(_result, _link_name,
longhorn.py:457: in action
    return self._post_and_retry(url, *args, **kw)
longhorn.py:415: in _post_and_retry
    raise e
longhorn.py:409: in _post_and_retry
    return self._post(url, data=self._to_dict(*args, **kw))
longhorn.py:74: in wrapped
    return fn(*args, **kw)
longhorn.py:303: in _post
    self._error(r.text, r.status_code)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <longhorn.Client object at 0xffff920d4490>
text = '{"actions":{},"code":"Server Error","detail":"","links":{"self":"[http://10.42.3.6:9500/v1/volumes/vol-disk-1"},"messa...east](http://10.42.3.6:9500/v1/volumes/vol-disk-1) one of the the replicas\' nodes or the node that the volume is going to attach to","status":500,"type":"error"}\n'
status_code = 500

    def _error(self, text, status_code):
>       raise ApiError(self._unmarshall(text), status_code)
E       longhorn.ApiError: (ApiError(...), '500 : unable to attach volume vol-disk-1 to ip-10-0-1-148: cannot attach volume vol-disk-1 because the engine image longhornio/longhorn-engine:v1.4.2-rc1 is not deployed on at least one of the the replicas\' nodes or the node that the volume is going to attach to\n{\'code\': 500, \'detail\': \'\', \'message\': "unable to attach volume vol-disk-1 to ip-10-0-1-148: cannot attach volume vol-disk-1 because the engine image longhornio/longhorn-engine:v1.4.2-rc1 is not deployed on at least one of the the replicas\' nodes or the node that the volume is going to attach to", \'status\': 500}')

longhorn.py:283: ApiError
```

## Environment

 - Longhorn version: v1.4.2-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:K3s
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version: Micro-SLE
   - CPU per node: 4
   - Memory per node: 16G
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):AWS
 - Number of Longhorn volumes in the cluster: 

## Additional context

N/A

**Comment by roger-ryao** [comment]
> @roger-ryao Is this reproducible in 1.3.3? We did run e2e to 1.3.3, right?

Hi @innobead :
     Yes, it could be reproduced in 1.3.3 and master-head.

**Comment by innobead** [comment]
Thanks @roger-ryao , so this is not a regression.

cc @c3y1huang please take a look.

**Comment by c3y1huang** [comment]
Possibly caused by the SLE Micro running in the pipeline doesn't have enough space.
```
> df -lh
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        4.0M     0  4.0M   0% /dev
tmpfs           7.9G  4.0K  7.9G   1% /dev/shm
tmpfs           3.2G  592K  3.2G   1% /run
tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
/dev/xvda3      5.0G  1.6G  3.1G  33% /
/dev/xvda3      5.0G  1.6G  3.1G  33% /root
/dev/xvda4       36G  357M   35G   2% /var
overlay          36G  357M   35G   2% /etc
tmpfs           7.9G     0  7.9G   0% /tmp
/dev/xvda3      5.0G  1.6G  3.1G  33% /.snapshots
/dev/xvda3      5.0G  1.6G  3.1G  33% /boot/grub2/i386-pc
/dev/xvda3      5.0G  1.6G  3.1G  33% /boot/grub2/x86_64-efi
/dev/xvda3      5.0G  1.6G  3.1G  33% /boot/writable
/dev/xvda3      5.0G  1.6G  3.1G  33% /home
/dev/xvda3      5.0G  1.6G  3.1G  33% /opt
/dev/xvda3      5.0G  1.6G  3.1G  33% /srv
/dev/xvda3      5.0G  1.6G  3.1G  33% /usr/local
/dev/xvda2       20M  3.0M   17M  15% /boot/efi
tmpfs           1.6G     0  1.6G   0% /run/user/1000
```

**Comment by innobead** [comment]
@yangchiu can you help with increasing the root volume size for each instance? Thanks

**Comment by c3y1huang** [comment]
[Increase pipeline instance storage size](https://github.com/longhorn/longhorn/issues/5909#issuecomment-1543373809) should work for this issue.

We can close [this PR](https://github.com/longhorn/longhorn-tests/pull/1353) if it's not helpful.

**Comment by innobead** [comment]
Merged, but still need to increase the storage size if needed. @yangchiu

**Comment by c3y1huang** [comment]
> Merged, but still need to increase the storage size if needed. @yangchiu

https://github.com/longhorn/longhorn/issues/5913

**Comment by roger-ryao** [comment]
After https://github.com/longhorn/longhorn-tests/pull/1353 was merged, the test reports for both `arm64` and `amd64` platforms on `SLE Micro` showed that the tests passed. The links to the reports are:
https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/arm64/job/longhorn-tests-sle-micro-arm64/5/
https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/amd64/job/longhorn-tests-sle-micro-amd64/5/

**Comment by innobead** [comment]
Thanks @roger-ryao and @c3y1huang

**Comment by yangchiu** [comment]
All pipelines have the same storage size (40GB).

How much space can be used by Longhorn on each node depends on how much space is already used by the operating system.

For sles, it is: 
```
Allocated                Used                    Size 
0 / 55.95 Gi            9.01 / 39.97 Gi     28 Gi +12 Gi Reserved    
```
There are `55.95 Gi` available space because of the default `200%` storage over-provisioning.

For sle-micro, it is
```
Allocated                Used                    Size 
0 / 49.01 Gi            3.66 / 35.01 Gi     24.5 Gi +10.5 Gi Reserved
```
Even though the storage over-provisioning, there are just only `49.01 Gi` available space.

The original test case will try to allocate a volume with size `50 Gi`, that's why the test case failed.

But actually the original test case tries to allocate a volume with size `50 * Gi + default_disk_available`, why it only allocates a volume with size `50 Gi` in reality?

Because in https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_scheduling.py#L1450, after `cleanup_node_disks`, disks will be deleted from the node, so there's no disk on the node, so the following `for loop` in https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_scheduling.py#L1454 and https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_scheduling.py#L1465 take no effect. So actually this test case doesn't work as expected.

On the other hand, the storage over-provisioning has been decreased in master-head: https://github.com/longhorn/longhorn-manager/pull/1896, so there will be only `~ 28 Gi` available space on each node by default after this commit, but since we've decreased the volume size from `50 Gi` to `10 Gi` in https://github.com/longhorn/longhorn-tests/pull/1353, this test case is still safeto run!

**Comment by innobead** [comment]
@yangchiu very well analyzed. 

cc @longhorn/qa
