### ISSUE TITLE
[UI] Remove maxheight from ant-table-body in volume page

### ISSUE THREAD

**Issue by Angelinsky7** [longhorn/longhorn#591]
Hi,

is it possible to remove the maxheight attribute on the ant-table-body table in the volume page ?
now it looks like this :
![image](https://user-images.githubusercontent.com/13157968/59227344-704e8600-8bd5-11e9-99f7-a38edb46b9ae.png)

without it will look like that :
![image](https://user-images.githubusercontent.com/13157968/59227373-7f353880-8bd5-11e9-9436-6a024b4b0e16.png)

the `overflow: scroll` is also very strange... it should be `overflow-y: auto`
and if you want to have a full screen type of ui it would be better to use css flex all the way with 100% height everywhere instead of having a very strange max-height coming from nowhere...

thanks :-)

version : 0.5.0

**Comment by yasker** [comment]
Nice catch!

@smallteeths What do you think about this? I know we've been tweaking volume list page a lot, not sure if we're deliberately doing this for some reason.

**Comment by smallteeths** [comment]
@yasker The height of the page was designed to be supported by the content, but if the list is too long, you can't see the header, I want to have a full screen type of ui and I don't want to change the layout, so I use max-height. It will take some time to change the original layout

**Comment by smallteeths** [comment]
Recommended use Chrome or Firefox

**Comment by yasker** [comment]
Should be fixed in v0.6.0 by the above commit.
