### ISSUE TITLE
[IMPROVEMENT] Review and simplify longhorn component image build

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5911]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Need to review dockerfile and dockerfile.dapper of each component to clean up or simplify the build flow and content inside; one of the examples is https://github.com/longhorn/longhorn-instance-manager/blob/master/Dockerfile.dapper#L27-L61, the tgt and liblonghorn build are unnecessary in build image since they are already in https://github.com/longhorn/longhorn-instance-manager/blob/master/package/Dockerfile

## Additional context

cc @longhorn/dev

**Comment by ChanYiLin** [comment]
Hi @innobead 
I found we check grpc generated code in longhorn-engine but not in longhorn-instance-manager
- longhorn-engine: https://github.com/longhorn/longhorn-engine/blob/master/scripts/prebuild
- longhorn-instance-manager: https://github.com/longhorn/longhorn-instance-manager/tree/master/scripts
I think this is to prevent somebody from forgetting to regenerated the code after updating the proto.

**Comment by shuo-wu** [comment]
BTW, [the IM gRPC generating script](https://github.com/longhorn/longhorn-instance-manager/blob/f80354ec9a09e986f378017410891b26dddecc00/generate_grpc.sh#L27-L40) considered one grpc file/package naming issue while others do not. You can check the code for details.

**Comment by ChanYiLin** [comment]
@shuo-wu I think the reason is because there is "github.com" involved
Why not just followed the same script in longhorn-engine [here](https://github.com/longhorn/longhorn-engine/blob/master/generate_grpc.sh)
but copy the .proto to another tmp folder with "github.com" and then generate the python grpc client?
I think we can make it the same way?

cc @derekbit

**Comment by derekbit** [comment]
IIRC, `following the same script in longhorn-engine [here](https://github.com/longhorn/longhorn-engine/blob/master/generate_grpc.sh)` hits the combability issue.

**Comment by shuo-wu** [comment]
Yes. Somehow there was a pkg naming conflict error then we modified the script in the longhorn-instance-manager repo but I don't remember the details. @ejweber may know the context.

**Comment by ejweber** [comment]
[This change](https://github.com/longhorn/longhorn-instance-manager/commit/4c85ef9da9568c249694fdcaea1e46058393f21e) by @derekbit is similar to the one I made in https://github.com/longhorn/backing-image-manager/pull/125 for the backing image manager. I think the reasons for it are outlined pretty well in that PR. It's possible another implementation of the script will work fine, so long as the result (e.g. `proto.RegisterFile("github.com/longhorn/backing-image-manager/pkg/rpc/rpc.proto", fileDescriptor_cdf73a3350f27fd7`) is the same, but my experience with manipulating the arguments to `protoc` was that it was very difficult to achieve this result without some strange manipulation.

My change wasn't made for the Python gRPC implementation at all, but I can see how it can cause the Python generation script to need changes as well.

**Comment by w13915984028** [comment]
I filed https://github.com/longhorn/longhorn/issues/7072, but we can also discuss here:

Harvester is more sensitive to `Container Image Size`, both `ISO packing` and `system upgrading`.

Could we have a quick fix to deliver clean & smaller container image first? It also needs to be backported to old version, which Harvester is using/to use.

cc @bk201 @markhillgit
