### ISSUE TITLE
[TEST-INFRA] Increase storage size for the SLE Micro pipeline instances

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#5913]
## What's the test to develop? Please describe

The storage size for the SLE Micro pipeline instances should be consistent with other pipelines.

## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] Increase storage size for SLE Micro pipeline instances.

## Additional context

https://github.com/longhorn/longhorn/issues/5909

**Comment by yangchiu** [comment]
explained in https://github.com/longhorn/longhorn/issues/5909#issuecomment-1545084193.
