### ISSUE TITLE
[TASK] Remove `Guaranteed Engine Manager CPU`, `Guaranteed Replica Manager CPU`, and `Guaranteed Engine CPU` settings.

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#5917]
## Is your improvement request related to a feature? Please describe

After consolidating engine and replica instance managers, the `Guaranteed Engine Manager CPU` and `Guaranteed Replica Manager CPU` settings serve no other purpose than to trigger the instance manager pod deletion.

The `Guaranteed Engine CPU` is ineffective after introducing the above two settings.

## Describe the solution you'd like

Remove `Guaranteed Engine Manager CPU`, `Guaranteed Replica Manager CPU`, and `Guaranteed Engine CPU` settings.

## Describe alternatives you've considered

Handle setting removal in https://github.com/longhorn/longhorn/issues/5844.

## Additional context

https://github.com/longhorn/longhorn/issues/5208

**Comment by roger-ryao** [comment]
**Verified on master-head 20230530**

- longhorn master-head ([7b3b230](https://github.com/longhorn/longhorn/commit/7b3b230f471071f08b9621a165fab7887e087491))
- longhorn-manager master-head ([023dd3c](https://github.com/longhorn/longhorn-manager/commit/023dd3cbd5009f390608ea9cdd9f31bd397cf8a2))


**Result Passed**

- [x] - doc: https://github.com/longhorn/website/pull/671
- [x] The UI on the master branch no longer includes the options for `Guaranteed Engine Manager CPU` and `Guaranteed Replica Manager CPU`.
- [x] After upgrading Longhorn from version `1.4.x` to the `master` branch, the options for `Guaranteed Engine Manager CPU` and `Guaranteed Replica Manager CPU` were removed from the UI.
- [] We have a typo [in the PR](https://github.com/longhorn/website/pull/671/files#r1209705291). Once the typo is fixed, I will close this ticket.

**Comment by innobead** [comment]
I like the checklist which will prevent any missing criteria for closing the issue. 

cc @longhorn/qa
