### ISSUE TITLE
[BUG] Upgrade Engine in the drop down doesn't appear after updating v1.4.1 to v1.4.2

### ISSUE THREAD

**Issue by tommy04062019** [longhorn/longhorn#5929]
After updating longhorn to v1.4.2 without errors, I did a Live upgrade but I cant see `Update Engine` option on the volume's setting menu. What's wrong with this?
<img width="1424" alt="Screen Shot 2023-05-13 at 11 40 05" src="https://github.com/longhorn/longhorn/assets/8014325/5bf21c4c-e59f-4097-aaed-99003b4f8191">
<img width="477" alt="Screen Shot 2023-05-13 at 11 41 10" src="https://github.com/longhorn/longhorn/assets/8014325/2134b47c-a5fa-4722-81f3-4e33aca3aa50">

**Comment by ChanYiLin** [comment]
Hi @tommy04062019 
Can you provide support bundle for us to check the cluster situation
We doubt that maybe some nodes have no v1.4.2 image ready so the volume still can't be upgrade.
Thanks

**Comment by tommy04062019** [comment]
> Hi @tommy04062019 Can you provide support bundle for us to check the cluster situation We doubt that maybe some nodes have no v1.4.2 image ready so the volume still can't be upgrade. Thanks

Ahh, I found the problem, a node was under disk pressure while updating Longhorn. This issue should be closed now. Thanks.
