### ISSUE TITLE
Can we update storage reserve of each node at the of installation of longhorn on rke2 kubernetes cluster via helm chart

### ISSUE THREAD

**Issue by ravisingh-adeptia** [longhorn/longhorn#5951]
## Question
> Suggest to use https://github.com/longhorn/longhorn/discussions to ask questions.

## Environment

 - Longhorn version:
 - Kubernetes version:
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Comment by ChanYiLin** [comment]
Currently we don't have this setting in helm chart
Have created a issue to handle this, thanks!
https://github.com/longhorn/longhorn/issues/5958

**Comment by ChanYiLin** [comment]
Close this issue since we already have discussion thread and an issue to handle this
