### ISSUE TITLE
[IMPROVEMENT] Add reserve storage percentage of nodes setting in helm chart

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#5958]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

We have add `reserve storage percentage` global setting, but this setting currently can only be changed in UI after Longhorn is installed.
It's more convenient for user to set this setting during deploying

## Describe the solution you'd like

Add `reserve storage percentage` global setting to helm chart

## Additional context
previous issue: https://github.com/longhorn/longhorn/issues/4773

https://github.com/longhorn/longhorn/discussions/5957

**Comment by ChanYiLin** [comment]
cc @mantissahz

**Comment by innobead** [comment]
This is not a new feature but an improvement for the exiting feature.

**Comment by innobead** [comment]
Assigned to @mantissahz for this issue lifecycle, and this is being contributed by @aneyne

**Comment by roger-ryao** [comment]
**Verified on master-head 20230817**

- longhorn master-head https://github.com/longhorn/longhorn/commit/3b04fa8c023b871bc321b84cf9479ebb7215b5df


**Result Passed**

After [Helm installation](https://github.com/longhorn/longhorn/tree/master), I have checked the following items:

- [x]  The `storageReservedPercentageForDefaultDisk` parameter can be configured in the `values.yaml` file and will be reflected as `storage-reserved-percentage-for-default-disk`.
- [x]  The value of `storage-reserved-percentage-for-default-disk` can be modified.
- [x]  The default value of `storage-reserved-percentage-for-default-disk` is set to `30`.
