### ISSUE TITLE
How To Avoid Exceeding The Limit

### ISSUE THREAD

**Issue by HZMarico** [longhorn/longhorn#596]
# I don't know what happened.

> k8s version : v 1.14.0
> longhorn version : v0.5.0(icsi)

## longhorn ui
![image](https://user-images.githubusercontent.com/15900595/59561989-35c36e00-9059-11e9-9f12-b1caf0f82949.png)

## du -h
![image](https://user-images.githubusercontent.com/15900595/59561998-64414900-9059-11e9-8033-8262cd4d7853.png)

## rancher ui
![image](https://user-images.githubusercontent.com/15900595/59562016-a4083080-9059-11e9-840a-21ca5441ab94.png)

## pod
![image](https://user-images.githubusercontent.com/15900595/59562024-d87bec80-9059-11e9-8e80-54a653b594a9.png)

77G > 10G, What‘s happened?

**Comment by yasker** [comment]
Hi @HZMarico 

It seems you have snapshots made in the system, which contains the history so the volume can be bigger than the nominal size. See https://github.com/longhorn/longhorn/issues/478#issuecomment-482675743 and https://github.com/longhorn/longhorn/issues/478#issuecomment-485930147 on explaining why.

You can schedule a recurring snapshot or backup to avoid accumulate unnecessary history for the volume, see https://github.com/longhorn/longhorn/issues/478#issuecomment-486351521.

**Comment by HZMarico** [comment]
Thank you for your reply.
