### ISSUE TITLE
[BUG] Share manager pod will stay in IO error when the volume becomes read only

### ISSUE THREAD

**Issue by shaolila** [longhorn/longhorn#5961]
## Describe the bug (🐛 if you encounter this issue)
I use longhorn for RWX pv, I found pv in share-management pod change from RW to RO somehow, but share-manage- pod
still in Running status

if pv in share-management pod change from RW to RO ,share-manage- pod should restart automatically

## To Reproduce

share-manager-pvc-6f4444ac-eab0-4f13-a0b7-5dd915d1f922   1/1  Running  0   7d1h

the right thing is :
share-manager-pvc-6f4444ac-eab0-4f13-a0b7-5dd915d1f922:/tmp # mount |grep pvc
/dev/longhorn/pvc-6f4444ac-eab0-4f13-a0b7-5dd915d1f922 on /export/pvc-6f4444ac-eab0-4f13-a0b7-5dd915d1f922 type ext4 (rw,relatime)

the exceptions is:
share-manager-pvc-6f4444ac-eab0-4f13-a0b7-5dd915d1f922:/tmp # mount |grep pvc
/dev/longhorn/pvc-6f4444ac-eab0-4f13-a0b7-5dd915d1f922 on /export/pvc-6f4444ac-eab0-4f13-a0b7-5dd915d1f922 type ext4 (ro,relatime)

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.4.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 1.23.9
   - Number of management node in the cluster:
   - Number of worker node in the cluster:3
 - Node config
   - OS type and version:CentOS8
   - CPU per node:40
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 11

## Additional context

kernel.log show 
May 17 04:54:39 dmoc-fc73fb8e9abd kernel: [740588.274421] EXT4-fs (sdi): error count since last fsck: 6
May 17 04:54:39 dmoc-fc73fb8e9abd kernel: [740588.279910] EXT4-fs (sdi): initial error at time 1683918842: __ext4_new_inode:950
May 17 04:54:39 dmoc-fc73fb8e9abd kernel: [740588.287482] EXT4-fs (sdi): last error at time 1683918842: ext4_journal_check_start:61
May 17 06:00:07 dmoc-fc73fb8e9abd kernel: [744517.056619] nfs: Deprecated parameter 'intr'
May 17 07:00:06 dmoc-fc73fb8e9abd kernel: [748116.083687] nfs: Deprecated parameter 'intr'
May 17 07:33:10 dmoc-fc73fb8e9abd kernel: [750099.331576] sd 20:0:0:1: [sdh] tag#92 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE cmd_age=15s
May 17 07:33:10 dmoc-fc73fb8e9abd kernel: [750099.341156] sd 20:0:0:1: [sdh] tag#92 Sense Key : Medium Error [current]
May 17 07:33:10 dmoc-fc73fb8e9abd kernel: [750099.348058] sd 20:0:0:1: [sdh] tag#92 Add. Sense: Unrecovered read error
May 17 07:33:10 dmoc-fc73fb8e9abd kernel: [750099.354863] sd 20:0:0:1: [sdh] tag#92 CDB: Write(10) 2a 00 01 84 d2 48 00 00 88 00
May 17 07:33:10 dmoc-fc73fb8e9abd kernel: [750099.362519] blk_update_request: critical medium error, dev sdh, sector 25481800 op 0x1:(WRITE) flags 0x800 phys_seg 17 prio class 0
May 17 07:33:10 dmoc-fc73fb8e9abd kernel: [750099.374445] Buffer I/O error on dev sdh, logical block 3185225, lost sync page write
May 17 07:33:10 dmoc-fc73fb8e9abd kernel: [750099.382301] Aborting journal on device sdh-8.
May 17 07:33:10 dmoc-fc73fb8e9abd kernel: [750099.387059] sd 20:0:0:1: [sdh] tag#68 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE cmd_age=0s
May 17 07:33:10 dmoc-fc73fb8e9abd kernel: [750099.396542] sd 20:0:0:1: [sdh] tag#68 Sense Key : Medium Error [current]
May 17 07:33:10 dmoc-fc73fb8e9abd kernel: [750099.403418] sd 20:0:0:1: [sdh] tag#68 Add. Sense: Unrecovered read error
May 17 07:33:10 dmoc-fc73fb8e9abd kernel: [750099.410210] sd 20:0:0:1: [sdh] tag#68 CDB: Write(10) 2a 00 01 84 00 00 00 00 08 00
May 17 07:33:10 dmoc-fc73fb8e9abd kernel: [750099.417855] blk_update_request: critical medium error, dev sdh, sector 25427968 op 0x1:(WRITE) flags 0x800 phys_seg 1 prio class 0
May 17 07:33:10 dmoc-fc73fb8e9abd kernel: [750099.429654] Buffer I/O error on dev sdh, logical block 3178496, lost sync page write
May 17 07:33:10 dmoc-fc73fb8e9abd kernel: [750099.437474] JBD2: Error -5 detected when updating journal superblock for sdh-8.
May 17 07:34:48 dmoc-fc73fb8e9abd kernel: [750197.715727] sd 20:0:0:1: [sdh] tag#93 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE cmd_age=0s
May 17 07:34:48 dmoc-fc73fb8e9abd kernel: [750197.725259] sd 20:0:0:1: [sdh] tag#93 Sense Key : Medium Error [current]
May 17 07:34:48 dmoc-fc73fb8e9abd kernel: [750197.732143] sd 20:0:0:1: [sdh] tag#93 Add. Sense: Unrecovered read error
May 17 07:34:48 dmoc-fc73fb8e9abd kernel: [750197.738965] sd 20:0:0:1: [sdh] tag#93 CDB: Write(10) 2a 00 00 00 00 00 00 00 08 00
May 17 07:34:48 dmoc-fc73fb8e9abd kernel: [750197.746646] blk_update_request: critical medium error, dev sdh, sector 0 op 0x1:(WRITE) flags 0x800 phys_seg 1 prio class 0
May 17 07:34:48 dmoc-fc73fb8e9abd kernel: [750197.757844] Buffer I/O error on dev sdh, logical block 0, lost sync page write
May 17 07:34:48 dmoc-fc73fb8e9abd kernel: [750197.765175] EXT4-fs (sdh): I/O error while writing superblock
May 17 07:34:48 dmoc-fc73fb8e9abd kernel: [750197.771147] EXT4-fs error (device sdh): ext4_journal_check_start:61: Detected aborted journal
May 17 07:34:48 dmoc-fc73fb8e9abd kernel: [750197.779973] EXT4-fs (sdh): Remounting filesystem read-only
May 17 07:34:48 dmoc-fc73fb8e9abd kernel: [750197.785621] EXT4-fs (sdh): error: monitor devnum NULL, io err devnum:#8:112#
May 17 07:38:48 dmoc-fc73fb8e9abd kernel: [750437.920559] sd 20:0:0:1: [sdh] tag#94 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE cmd_age=0s
May 17 07:38:48 dmoc-fc73fb8e9abd kernel: [750437.930028] sd 20:0:0:1: [sdh] tag#94 Sense Key : Medium Error [current]
May 17 07:38:48 dmoc-fc73fb8e9abd kernel: [750437.936900] sd 20:0:0:1: [sdh] tag#94 Add. Sense: Unrecovered read error
May 17 07:38:48 dmoc-fc73fb8e9abd kernel: [750437.943680] sd 20:0:0:1: [sdh] tag#94 CDB: Read(10) 28 00 00 18 00 00 00 00 40 00
May 17 07:38:48 dmoc-fc73fb8e9abd kernel: [750437.951243] blk_update_request: critical medium error, dev sdh, sector 1572864 op 0x0:(READ) flags 0x80700 phys_seg 8 prio class 0

**Comment by innobead** [comment]
cc @derekbit

**Comment by innobead** [comment]
Probably can leverage the new gRPC service introduced for RWX trim to support this in-pod IO error detection, then recover the share manager pod. ref: https://github.com/longhorn/longhorn/issues/5143

**Comment by shaolila** [comment]
> Probably can leverage the new gRPC service introduced for RWX trim to support this in-pod IO error detection, then recover the share manager pod. ref: #5143

when a RO occur
the event in longhorn-system shows some information as :
Failed rebuilding replica with Address 184.30.72.139:10000: proxyServer=184.30.72.134:8501 destination=184.30.72.134:10004: failed to add replica tcp://184.30.72.139:10000 for volume: rpc error: code = Unknown desc = failed to set rebuilding to true for replica 184.30.72.139:10000: rpc error: code = Unknown desc = cannot set rebuilding=true from state rebuilding

**Comment by shaolila** [comment]
when a RO occur
the event in longhorn-system shows some information as :
10.30.10.134:8501 destination=10.30.10.134:10004: failed to add replica tcp://10.30.10.139:10000 for volume: rpc error: code = Unknown desc = failed to set rebuilding to true for replica 10.30.10.139:10000: rpc error: code = Unknown desc = cannot set rebuilding=true from state rebuilding

**Comment by shaolila** [comment]
> cc @derekbit @longhorn/qa

Thank you very much for including him in the development plan,
I wish it would be better if there was a quick solution or fix .

**Comment by ChanYiLin** [comment]
Hi @shaolila currently, the quick fix is to delete the share manager pod to force recreate the pod

**Comment by roger-ryao** [comment]
**Verified on master-head 20230901**

- longhorn master-head https://github.com/longhorn/longhorn/commit/67b4b38a1222d441f528907dcfbc89c4a6ce08d5
- longhorn-share-manager master-head https://github.com/longhorn/longhorn-share-manager/commit/48398b92ca4a63af4bc496d2e944f497a1d3db5e


**The test steps**
https://github.com/longhorn/longhorn/issues/5961#issuecomment-1619899407

**Result Passed**

After change the mount point to "ro", it has reverted to `rw` in within 10 secs.
