### ISSUE TITLE
[BUG] longhorn-manager: unable to get engine image longhornio/longhorn-engine:v1.4.2 after re-install

### ISSUE THREAD

**Issue by polds** [longhorn/longhorn#5963]
## Describe the bug (🐛 if you encounter this issue)

My RKE2 cluster recently self updated to k8s 1.25 while running an older Longhorn 1.3.2 install. This caused me to start hitting errors called out in https://github.com/longhorn/longhorn/issues/4003. Due to these errors I could not cleanly upgrade Longhorn to 1.4.x because it was missing some of the beta versions. So I found https://github.com/longhorn/longhorn/issues/5185#issuecomment-1396124624 which helped me force a helm upgrade to 1.4.2.

However, after the upgrade, none of the longhorn-manager pods go healthy and crash loop with the below errors (can share more if needed). I can't access the UI to upgrade the engine image as all of the UI elements throw 502's.

I'm trying to figure out a way forward.

```
time="2023-05-18T18:44:17Z" level=warning msg="Dropping Longhorn engine out of the queue" controller=longhorn-engine engine=longhorn-system/sys-0--23-03-20-e-e7a10a90 error="failed to sync engine for longhorn-system/sys-0--23-03-20-e-e7a10a90: unable to get engine image rancher/mirrored-longhornio-longhorn-engine:v1.3.2: engineimage.longhorn.io \"ei-881c42db\" not found" node=rke2-n-01
time="2023-05-18T18:44:17Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-abb1ac31-9f2d-4c5b-a6e8-7a38258d3a66" controller=longhorn-volume error="failed to sync longhorn-system/pvc-abb1ac31-9f2d-4c5b-a6e8-7a38258d3a66: unable to get engine image longhornio/longhorn-engine:v1.4.2: engineimage.longhorn.io \"ei-f9e7c473\" not found" node=rke2-n-01
time="2023-05-18T18:44:17Z" level=debug msg="Replica controller picked up" controller=longhorn-replica controllerID=rke2-n-01 dataPath= node=rke2-n-01 nodeID=rke2-s-03 ownerID=rke2-s-02 replica=pvc-abb1ac31-9f2d-4c5b-a6e8-7a38258d3a66-r-aef2e707
time="2023-05-18T18:44:17Z" level=warning msg="Error syncing Longhorn replica longhorn-system/pvc-abb1ac31-9f2d-4c5b-a6e8-7a38258d3a66-r-aef2e707" controller=longhorn-replica error="failed to sync replica for longhorn-system/pvc-abb1ac31-9f2d-4c5b-a6e8-7a38258d3a66-r-aef2e707: failed to cleanup the related replica process before deleting replica pvc-abb1ac31-9f2d-4c5b-a6e8-7a38258d3a66-r-aef2e707: failed to get engine image object based on image name rancher/mirrored-longhornio-longhorn-engine:v1.3.2: engineimage.longhorn.io \"ei-881c42db\" not found" node=rke2-n-01
time="2023-05-18T18:44:17Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-eb9d8d94-6cb3-46ed-9d4d-6627f5d1b693" controller=longhorn-volume error="failed to sync longhorn-system/pvc-eb9d8d94-6cb3-46ed-9d4d-6627f5d1b693: unable to get engine image longhornio/longhorn-engine:v1.4.2: engineimage.longhorn.io \"ei-f9e7c473\" not found" node=rke2-n-01
time="2023-05-18T18:44:17Z" level=warning msg="Error syncing Longhorn volume longhorn-system/sys-0--23-03-20" controller=longhorn-volume error="failed to sync longhorn-system/sys-0--23-03-20: unable to get engine image longhornio/longhorn-engine:v1.4.2: engineimage.longhorn.io \"ei-f9e7c473\" not found" node=rke2-n-01
time="2023-05-18T18:44:17Z" level=warning msg="Dropping Longhorn volume longhorn-system/pvc-c751ffd0-3d98-4702-9026-96bc4fc06b39 out of the queue" controller=longhorn-volume error="failed to sync longhorn-system/pvc-c751ffd0-3d98-4702-9026-96bc4fc06b39: unable to get engine image longhornio/longhorn-engine:v1.4.2: engineimage.longhorn.io \"ei-f9e7c473\" not found" node=rke2-n-01
time="2023-05-18T18:44:17Z" level=warning msg="Dropping Longhorn engine out of the queue" controller=longhorn-engine engine=longhorn-system/pvc-9d76bbf9-0bc3-42e9-ac54-098e67d65caf-e-b7c410a3 error="failed to sync engine for longhorn-system/pvc-9d76bbf9-0bc3-42e9-ac54-098e67d65caf-e-b7c410a3: unable to get engine image rancher/mirrored-longhornio-longhorn-engine:v1.3.2: engineimage.longhorn.io \"ei-881c42db\" not found" node=rke2-n-01
time="2023-05-18T18:44:17Z" level=warning msg="Dropping Longhorn volume longhorn-system/pvc-14005ca8-351d-4f5d-b3ab-2da4c243387a out of the queue" controller=longhorn-volume error="failed to sync longhorn-system/pvc-14005ca8-351d-4f5d-b3ab-2da4c243387a: unable to get engine image longhornio/longhorn-engine:v1.4.2: engineimage.longhorn.io \"ei-f9e7c473\" not found" node=rke2-n-01
time="2023-05-18T18:44:17Z" level=warning msg="Dropping Longhorn volume longhorn-system/pvc-709475f7-6504-49ce-995d-a16d3de29295 out of the queue" controller=longhorn-volume error="failed to sync longhorn-system/pvc-709475f7-6504-49ce-995d-a16d3de29295: unable to get engine image longhornio/longhorn-engine:v1.4.2: engineimage.longhorn.io \"ei-f9e7c473\" not found" node=rke2-n-01
time="2023-05-18T18:44:17Z" level=warning msg="Error syncing Longhorn volume longhorn-system/pvc-abb1ac31-9f2d-4c5b-a6e8-7a38258d3a66" controller=longhorn-volume error="failed to sync longhorn-system/pvc-abb1ac31-9f2d-4c5b-a6e8-7a38258d3a66: unable to get engine image longhornio/longhorn-engine:v1.4.2: engineimage.longhorn.io \"ei-f9e7c473\" not found" node=rke2-n-01
```

I can see the nodes referenced _DO_ have the longhornio/longhorn-engine:v1.3.2 images locally, but not the 1.4.2 image. 

## To Reproduce

1. Install Longhorn 1.3.2 on k8s 1.24
2. Upgrade k8s to 1.25
3. Maybe reproducible at this point?
4. Attempt to upgrade Longhorn to 1.4.2

## Expected behavior

Manually be able to import the engine image.

## Log or Support bundle

Unable to generate a bundle.

## Environment

 - Longhorn version: 1.4.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.25.9+rke2r1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: Ubuntu
   - CPU per node: 4
   - Memory per node: 8
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 10 Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal / Proxmox
 - Number of Longhorn volumes in the cluster: 10-20

## Additional context

I have stopped all pods that are attempting to mount volumes and killed all of the longhorn-manager pods to try and get it to notice, but without success.

I know Longhorn should have been updated before the k8s update, but the k8s updates were automatic and happened suddenly.

**Comment by ChanYiLin** [comment]
cc @longhorn/qa

**Comment by innobead** [comment]
Planning to have a general KB for this issue, handling in https://github.com/longhorn/longhorn/issues/5964.

**Comment by polds** [comment]
That's great there will be a KB for this. Can I know what the KB will suggest? I'm still trying to figure out how to work through this error. 

At this point, I think all I can do is uninstall Longhorn and reinstall. But from there I'm not sure how to import backups from an old install. Does the uninstall process leave those stranded resources?

**Comment by darktempla** [comment]
Not sure if this will help but I had a similar issue.

For me it seemed that docker hub was throttling the pulling of images because on the nodes kubelet/crio runtime was pulling them anonymously. Eventually the image was pulled and engine started on that node.

**Comment by roger-ryao** [comment]
Hi @polds :
     I tried to reproduce your issue on my side and want to confirm something. Based on my understanding, your Longhorn `1.3.2` is installed using [Install as a Rancher Apps & Marketplace](https://longhorn.io/docs/1.3.2/deploy/install/install-with-rancher/). After you upgraded your Kubernetes to **v1.25.9+rke2r1** ,  you attempted to upgrade Longhorn [with Helm](https://longhorn.io/docs/1.4.2/deploy/install/install-with-helm/). I tried to upgrade Longhorn using the CLI command `helm upgrade --install longhorn longhorn/longhorn --namespace longhorn-system --version 1.4.2`. Can you provide more details about the command you used to upgrade Longhorn to v1.4.2 using Helm? Are there any differences between my approach and yours?

**Comment by ChanYiLin** [comment]
> That's great there will be a KB for this. Can I know what the KB will suggest? I'm still trying to figure out how to work through this error.
> 
> At this point, I think all I can do is uninstall Longhorn and reinstall. But from there I'm not sure how to import backups from an old install. Does the uninstall process leave those stranded resources?

You can unset the backup target before uninstall the Longhorn
The backup remains in the remote store
After reinstall the Longhorn, you can set the backup target back, Longhorn will restore the backup automatically by scanning the remote backup

**Comment by polds** [comment]
> I tried to reproduce your issue on my side and want to confirm something. Based on my understanding, your Longhorn 1.3.2 is installed using [Install as a Rancher Apps & Marketplace](https://longhorn.io/docs/1.3.2/deploy/install/install-with-rancher/). After you upgraded your Kubernetes to v1.25.9+rke2r1 , you attempted to upgrade Longhorn [with Helm](https://longhorn.io/docs/1.4.2/deploy/install/install-with-helm/). I tried to upgrade Longhorn using the CLI command helm upgrade --install longhorn longhorn/longhorn --namespace longhorn-system --version 1.4.2

My 1.3.2 was also installed using helm - though I don't remember which invocation exactly was used for that. When I tried to upgrade to 1.4.2 using helm with the exact command you pasted I ran into issues stating things couldn't be found like PodSecurityPolicy and some of the beta1 resources (see https://github.com/longhorn/longhorn/issues/4003). To get around those I had to remove the Helm ConfigMap and Secret manually (from https://github.com/longhorn/longhorn/issues/5185#issuecomment-1396124624). Once I had removed them I did a `helm install --install longhorn longhorn/longhorn --namespace longhorn-system --version 1.4.2` - not upgrade. 

That's about where I'm at right now.

> You can unset the backup target before uninstall the Longhorn
> The backup remains in the remote store

My UI is totally unavailable, is this a setting that can be changed without using the UI?

**Comment by ejweber** [comment]
@polds, you can generally unset the backup target via kubectl by:

```bash
kubectl -n longhorn-system edit backup-target
# Set Value to "".
```

You can confirm with `kubectl -n longhorn-system describe backup-target`. In addition, `kubectl -n longhorn-system get backups` should no longer return any backups. However, if longhorn-manager pods are all crashing, this may not have this exact effect (e.g. the backup target setting will be empty but the backups won't disappear).

Are you able to provide a support bundle? It would be good to gain a full understanding of your exact situation for working on the KB @innobead mentioned.

Longhorn-manager should deploy a DaemonSet like `engine-image-ei-b907910b` that uses the image `<repo>/longhorn-engine:v1.4.2` pretty early on in its life, but again, this may not happen if it is crashing. Can you check whether this DaemonSet exists and its pods are healthy?

**Comment by polds** [comment]
> Are you able to provide a support bundle? It would be good to gain a full understanding of your exact situation for working on the KB @innobead mentioned.

I haven't been able to get the support bundle. The UI is unavailable and I tried following https://longhorn.io/kb/troubleshooting-create-support-bundle-with-curl/ but can't seem to connect, I see the service, but it just isn't responding.

> Longhorn-manager should deploy a DaemonSet like engine-image-ei-b907910b that uses the image <repo>/longhorn-engine:v1.4.2

It doesn't look like that DaemonSet is running.

**Comment by polds** [comment]
I totally uninstalled Longhorn, deleted the CRD and any associated resources I could, however when I reinstall Longhorn it seems like the etcd retained a lot of the resources and I hit the same issues trying to reinstall where the manager gets stuck:

> failed to sync longhorn-system/pvc-03343e4b-434a-4b39-a3f0-a366add0f397: unable to get engine image longhornio/longhorn-engine:v1.4.2: engineimage.longhorn.io "ei-f9e7c473" not found

I'm going to do my best to try and get a support bundle.

**Comment by polds** [comment]
I managed to get the instance managers running by removing the finalizers on all of the Backups which carried over from the previous install and deleting them.

As soon as those finalizers were removed everything went healthy again.

This is the script I used:
```
backups=$(kubectl get backups.longhorn.io -n longhorn-system -o json | jq -r ".items[].metadata.name")

for backup in $backups
do
  # Get the specific backup with finalizers
  backup_json=$(kubectl get backups.longhorn.io $backup -n longhorn-system -o json)

  # Remove the finalizer if it exists
  if echo "$backup_json" | jq -e 'has("metadata") and .metadata | has("finalizers")' > /dev/null; then
    modified_json=$(echo "$backup_json" | jq 'del(.metadata.finalizers)')
    echo "$modified_json" | kubectl replace --raw /apis/longhorn.io/v1/namespaces/longhorn-system/backups/$backup -f -
  fi
done
```

**Comment by polds** [comment]
Well, my original issue is now resolved. I have Longhorn back up and running, was successfully able to restore from a backup once I attached the backup location.

It's interesting to note that some of the backups when mounted would get totally stuck. I had to go and edit the yaml and remove the finalizers to remove some of the backups.

But I'll resolve this for now.

**Comment by ejweber** [comment]
Thanks for the update @polds. Sorry to hear you had to do a complete reinstall and that we weren't able to get to the bottom of exactly what was going wrong.

The uninstall issues you ran into aren't terribly unexpected. In order to fully uninstall Longhorn, we actually need a relatively healthy Longhorn system (to check for orphaned data, remove finalizers from resources, etc.). Otherwise, we leave behind resources that can't easily be deleted (like you discovered).

It seems to me that the most "root" cause we uncovered on this one is the longhorn-manager crash loop. If longhorn-manager can't stay up long enough, it won't install the engine-image DaemonSet that the logs you posted were complaining about. Unfortunately, none of the logs you provided indicated any reason for a longhorn-manager crash loop to have occurred (they were just reporting on the engine-image symptoms). If we hit this in the future, we need to figure out if longhorn-manager is panicking out itself or being killed by Kubernetes somehow.

**Comment by cyford** [comment]
> one of the manager tasks come up long enough to do anything with them.

I am having this same issue  ..  i beleive it was becuase the namespace was deleted..      when i reinstall i see the same issues.
I tryed ya backup script  no dice..   but i never took backups anyway
https://github.com/longhorn/longhorn/issues/7329
