### ISSUE TITLE
[BUG] Replica auto-rebalance doesn't respect node selector

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#5971]
## Describe the bug (🐛 if you encounter this issue)

Replica auto-balance doesn't respect the node selector and causes a re-balance loop. 

## To Reproduce

1. Have 3 node cluster (node-1, node-2, node-3)
2. Tag node-1, node-2 (select-tag)
2. Tag all nodes as different zones (zone-1, zone-2, zone-3)
4. Create volume with node-selector (select-tag)
5. Enable replica auto-rebalance
6. Replica auto-rebalance attempts to schedule a new replica to zone-3, but couldn't due to the volume node selector.

## Expected behavior

Rebalance should only check in zone-1 and zone-2 due to the node selector.

## Log or Support bundle

`None`

## Environment

 - Longhorn version: day-1 issue

## Additional context

https://github.com/longhorn/longhorn-manager/blob/cd31ec6e46ae76e56758382503d2ef5082f93ba1/controller/volume_controller.go#L2229

**Comment by roger-ryao** [comment]
**Verified on master-head 20230601**

- longhorn master-head https://github.com/longhorn/longhorn/commit/ffaa3d2113c2a47008e790df5bccf572f28025a3
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/2a83384208c88904bba67202c5d55b1d36dc6ea3

**The test steps**

https://github.com/longhorn/longhorn/issues/5971#issue-1718877226

**Result Passed**

- [x] Manual test passed
- [x] Automation E2E: [PR #1381](https://github.com/longhorn/longhorn-tests/pull/1381)
