### ISSUE TITLE
[BUG] Can't delete engineimage after upgrade from v1.3.2 to v1.4.1 (May 15, 2023)

### ISSUE THREAD

**Issue by shaolila** [longhorn/longhorn#5975]
## Describe the bug (🐛 if you encounter this issue)
Can't delete engineimage after upgrade from v1.3.2 to v1.4.1 (May 15, 2023) [BUG]

## To Reproduce

1. Install Longhorn v1.3.2
2. Upgrade to v1.4.1
3. try to delete v1.3.2 engine image
4. See error "unable to delete engine image: unable to delete engine image while being used"

## Expected behavior
all refCount is link to engine image v1.4.1 
can delete engine image v1.3.2
## Environment

 - Longhorn version: 1.3.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:1.23.9
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster:3
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
Please check the workaround in the ticket https://github.com/longhorn/longhorn/issues/5762.

**Comment by c3y1huang** [comment]
Closing because there hasn't been any activity after the provided workaround. Feel free to re-open.
