### ISSUE TITLE
backupstore: provide an option to delete all the backups of one volume

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#598]
https://github.com/longhorn/longhorn/issues/597

**Comment by yasker** [comment]
@smallteeths Backend merged.

**Comment by yasker** [comment]
@ywei88 Can you document the API here for UI engineer?

**Comment by ywei88** [comment]
r.Methods("DELETE").Path("/v1/backupvolumes/{volName}").Handler(f(schemas, s.BackupVolumeDelete))

________________________________

**Comment by meldafrawi** [comment]
Validation: PASSED

Steps to test:

- In `Settings` page, make sure backup target and backup secret is properly set.
- In `Volume` page, create a volume, attach the volume to a node, mount the volume, and write some data to the volume.
- Create multiple backups.
- In `Backup` page, from the drop down menu click `Delete All Backups`
>> Expected result: All volume backups should be deleted.

**Comment by yasker** [comment]
@meldafrawi Can you double-check that the volume and backups in the backup store have been removed?

**Comment by meldafrawi** [comment]
@yasker 
I double checked, and it is removed.
