### ISSUE TITLE
[BUG] longhorn-driver-deployer stuck in CrashLoopBackOff

### ISSUE THREAD

**Issue by abiancini** [longhorn/longhorn#5981]
## Describe the bug (🐛 if you encounter this issue)

After running
`kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.4.2/deploy/longhorn.yaml`
all containers deploy successfully except for the one in question:

`longhorn-system    engine-image-ei-f9e7c473-4zx6s                 1/1     Running            0                3h1m
longhorn-system    engine-image-ei-f9e7c473-dqvmk                 1/1     Running            0                3h1m
longhorn-system    engine-image-ei-f9e7c473-httnq                 1/1     Running            0                3h1m
longhorn-system    longhorn-admission-webhook-775657ffbf-2sl4x    1/1     Running            0                3h1m
longhorn-system    longhorn-admission-webhook-775657ffbf-h7kcr    1/1     Running            0                3h1m
longhorn-system    longhorn-conversion-webhook-7449f7fdb8-jm45h   1/1     Running            0                3h1m
longhorn-system    longhorn-conversion-webhook-7449f7fdb8-ld4jq   1/1     Running            0                3h1m
longhorn-system    longhorn-driver-deployer-79bcb6f5bc-r66qc      0/1     CrashLoopBackOff   34 (2m51s ago)   3h1m
longhorn-system    longhorn-manager-jlw5l                         1/1     Running            0                3h1m
longhorn-system    longhorn-manager-k4f9p                         1/1     Running            1 (3h1m ago)     3h1m
longhorn-system    longhorn-manager-s84nf                         1/1     Running            0                3h1m
longhorn-system    longhorn-recovery-backend-6c485b786c-skm8w     1/1     Running            0                3h1m
longhorn-system    longhorn-recovery-backend-6c485b786c-vh78r     1/1     Running            0                3h1m
longhorn-system    longhorn-ui-7989c5788c-bql7s                   1/1     Running            0                3h1m
longhorn-system    longhorn-ui-7989c5788c-r7fkv                   1/1     Running            0                3h1m`

## To Reproduce

1. `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.4.2/deploy/longhorn.yaml`

## Expected behavior

For all pods to show `1/1 Running`

## Log or Support bundle

Collected logs via `kubectl logs -n longhorn-system longhorn-driver-deployer-79bcb6f5bc-r66qc` and received the following output:
`Defaulted container "longhorn-driver-deployer" out of: longhorn-driver-deployer, wait-longhorn-manager (init)
W0522 17:47:11.701237       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2023-05-22T17:48:01Z" level=warning msg="Got an error when checking MountPropagation with node status, node dbkpvsvsk8sm01 is not support mount propagation"
time="2023-05-22T17:48:01Z" level=fatal msg="Error deploying driver: CSI cannot be deployed because MountPropagation is not set: node k8sm01 is not support mount [propagation"`]

## Environment

 - Longhorn version: 1.4.2
 - Installation method: Kubectl
 - Kubernetes version info:
   clientVersion:
   buildDate: "2023-04-14T13:21:19Z"
   compiler: gc
   gitCommit: 4c9411232e10168d7b050c49a1b59f6df9d7ea4b
   gitTreeState: clean
   gitVersion: v1.27.1
   goVersion: go1.20.3
   major: "1"
   minor: "27"
   platform: linux/amd64
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version:  Rocky Linux 8.7
   - CPU per node: 4
   - Memory per node: 16 gb
   - Disk type: NVMe
   - Network bandwidth between the nodes:
      `[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.04  sec  7.08 GBytes  6.06 Gbits/sec                  receiver`
 - Underlying Infrastructure: VMware
 - Number of Longhorn volumes in the cluster: 1

## Additional context

N/A

**Comment by l3nnartt** [comment]
facing the same issue

**Comment by ejweber** [comment]
Longhorn-manager is supposed to set a condition in the node.longhorn.io object, like:

```
- apiVersion: longhorn.io/v1beta2
  kind: Node
  ...
  status:
    conditions:
    ...
    - lastProbeTime: ""
      lastTransitionTime: "2023-05-23T13:59:06Z"
      message: ""
      reason: ""
      status: "True"
      type: MountPropagation
    ...
```

If it doesn't do so, we will fail at this step.

A full support bundle would be really helpful here in order to debug. If this is not possible, the complete spec of all longhorn-manager pods (e.g. `kubectl get pod -n longhorn-system -o yaml <longhorn-manager-pod>`) and the logs for each longhorn-manager pod (e.g. `kubectl logs -n longhorn-system <longhorn-manager-pod>`) should reveal why that condition is not being set (https://github.com/longhorn/longhorn-manager/blob/6856fd35ee1739f517b78be9e1c6df38171be458/controller/node_controller.go#L915-L921).

**Comment by abiancini** [comment]
> Longhorn-manager is supposed to set a condition in the node.longhorn.io object, like:
> 
> ```
> - apiVersion: longhorn.io/v1beta2
>   kind: Node
>   ...
>   status:
>     conditions:
>     ...
>     - lastProbeTime: ""
>       lastTransitionTime: "2023-05-23T13:59:06Z"
>       message: ""
>       reason: ""
>       status: "True"
>       type: MountPropagation
>     ...
> ```
> 
> If it doesn't do so, we will fail at this step.
> 
> A full support bundle would be really helpful here in order to debug. If this is not possible, the complete spec of all longhorn-manager pods (e.g. `kubectl get pod -n longhorn-system -o yaml <longhorn-manager-pod>`) and the logs for each longhorn-manager pod (e.g. `kubectl logs -n longhorn-system <longhorn-manager-pod>`) should reveal why that condition is not being set.
> 
> https://github.com/longhorn/longhorn-manager/blob/6856fd35ee1739f517b78be9e1c6df38171be458/controller/node_controller.go#L915-L921

Thanks for your response. I've gathered the logs you've requested and attached them.
[for_support.zip](https://github.com/longhorn/longhorn/files/11548370/for_support.zip)

**Comment by abiancini** [comment]
> We still set MountPropagation [here](https://github.com/longhorn/longhorn/blob/97887bd5c953515ddb31273bea8410ca59c5ed7c/deploy/longhorn.yaml#LL3919C1-L3921C42), and that is what longhorn-manager is looking for when setting the condition. Perhaps there a security feature enabled in your Kubernetes deployment that mutates this value without rejecting longhorn-manager outright?

I set this up as a fairly vanilla Kubernetes installation but I'm open to ideas of what that could be. The same setup worked in Fedora, but never worked when I rebuilt it on Rocky.

**Comment by abiancini** [comment]
Greetings @ejweber did you get a chance to look at this? Thanks.

**Comment by ejweber** [comment]
Unfortunately, it looks like this is still not enough information to fully uncover what's going wrong. Some additional things I notice:

- We log the error exactly 50s after the driver deployer starts. This indicates we are hitting the retry limit in [this loop](https://github.com/longhorn/longhorn-manager/blob/6856fd35ee1739f517b78be9e1c6df38171be458/csi/deployment_util.go#L433-L445) (we retry 10 times at 5 second intervals). This indicates we are not finding the MountPropagation condition we are looking for at all, or its status is "Unknown" (instead of finding that it is "False").
- The original error logs you posted look strange. They seem to reference both nodes dbkpvsvsk8sm01 and k8sm01 (which maybe doesn't exist?). I'm thinking this is just some kind of log formatting issue, but can you confirm what you posted is the full log?

I'm thinking we're going to need a full support bundle here so we can see all longhornNode objects and all node objects

**Comment by ejweber** [comment]
Sorry, should have looked at the logs you provided a bit closer. Actually, it appears that the deletion timestamp has been set on the following longhornNodes: dbkpvsvsk8sm01, dbkpvsvsk8sn01, and dbkpvsvsk8sn02. Since the deletion timestamp is set, no other reconciliation can occur (including the mount propagation condition reconciliation we have been discussing).

```
time="2023-05-23T20:47:58Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"dbkpvsvsk8sm01\", UID:\"1b42eb3e-7949-4c55-a671-b6fcce354b31\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"4393155\", FieldPath:\"\"}): type: 'Warning' reason: 'Delete' Deleting node dbkpvsvsk8sm01"
time="2023-05-23T20:47:58Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"dbkpvsvsk8sn02\", UID:\"b285054f-f344-40c0-ad20-4169f3db5465\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"4393161\", FieldPath:\"\"}): type: 'Warning' reason: 'Delete' Deleting node dbkpvsvsk8sn02"
time="2023-05-23T20:47:58Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"dbkpvsvsk8sn01\", UID:\"111422e3-9607-429c-b1e9-19e244df9452\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"4393159\", FieldPath:\"\"}): type: 'Warning' reason: 'Delete' Deleting node dbkpvsvsk8sn01"
```

My best guess is that you applied `https://raw.githubusercontent.com/longhorn/longhorn/v1.4.2/deploy/longhorn.yaml` after deleting a previous install (or deleting the longhorn namespace)? If these longhornNode objects were not properly cleaned up, Longhorn can not make new ones to modify and we are stuck.

**Comment by abiancini** [comment]
@ejweber my apologies on k8sm01: this was initially abbreviated for brevity's sake. The full server name is indeed dbkpvsvsk8sm01.

You are correct that `https://raw.githubusercontent.com/longhorn/longhorn/v1.4.2/deploy/longhorn.yaml` was the applied file. I previously deleted the deployment but had things permanently stuck in terminating states, so I ultimately ran this command:
`kubectl get namespace "longhorn-system" -o json \
  | tr -d "\n" | sed "s/\"finalizers\": \[[^]]\+\]/\"finalizers\": []/" \
  | kubectl replace --raw /api/v1/namespaces/longhorn-system/finalize -f -`

Unfortunately, I don't know how to generate a support bundle. I found this page: https://longhorn.io/kb/troubleshooting-create-support-bundle-with-curl/

Here's the result from step 1:
`kubectl -n longhorn-system get     svc/longhorn-backend
NAME               TYPE       CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE
longhorn-backend   NodePort   10.109.1.82   <none>        9500:30444/TCP   4d1h`

Then I ran the following based off of the above:
`#!/bin/sh

# Replace this block ====>
BACKEND_URL="10.109.1.82:30444"

ISSUE_URL="https://github.com/longhorn/longhorn/issues/5981"
ISSUE_DESCRIPTION="longhorn-driver-deployer stuck in CrashLoopBackOff"
# <==== Replace this block

# Request to create the support bundle
REQUEST_SUPPORT_BUNDLE=$( curl -sSX POST -H 'Content-Type: application/json' -d '{ "issueURL": "'"${ISSUE_URL}"'", "description": "'"${ISSUE_DESCRIPTION}"'" }' http://${BACKEND_URL}/v1/supportbundles )

ID=$( jq -r '.id' <<< ${REQUEST_SUPPORT_BUNDLE} )
SUPPORT_BUNDLE_NAME=$( jq -r '.name' <<< ${REQUEST_SUPPORT_BUNDLE} )
echo "Creating support bundle ${SUPPORT_BUNDLE_NAME} on Node ${ID}"

while [ $(curl -sSX GET http://${BACKEND_URL}/v1/supportbundles/${ID}/${SUPPORT_BUNDLE_NAME} | jq -r '.state' ) != "ReadyForDownload" ]; do
  echo "Progress: $(curl -sSX GET http://${BACKEND_URL}/v1/supportbundles/${ID}/${SUPPORT_BUNDLE_NAME} | jq -r '.progressPercentage' )%"
  sleep 1s
done

curl -X GET http://${BACKEND_URL}/v1/supportbundles/${ID}/${SUPPORT_BUNDLE_NAME}/download --output /tmp/${SUPPORT_BUNDLE_NAME}.zip
echo "Downloaded support bundle to /tmp/${SUPPORT_BUNDLE_NAME}.zip"`

This simply timed out. 

Thanks for your assistance.

**Comment by ejweber** [comment]
No worries on the support bundle. Generally we just ask you to hit the button for it in the bottom left of the UI, assuming your system is in a proper state to allow it: 

![image](https://github.com/longhorn/longhorn/assets/24213029/c220fb32-6801-4dd5-bd84-2167e56e0f5a)

In this case, I think we have enough information to figure out what went wrong.

It looks to me like your previous attempt to delete Longhorn was insufficent. We cannot remove Longhorn by simply reversing it's installation (e.g. `kubectl delete -f https://raw.githubusercontent.com/longhorn/longhorn/v1.4.2/deploy/longhorn.yaml`, as that removes longhorn-manager pods without giving them the opportunity to correctly clean up Longhorn resources. For future reference, a Longhorn system installed using the `kubectl apply` method should be uninstalled with `kubectl apply -f https://github.com/longhorn/longhorn/blob/master/uninstall/uninstall.yaml`. That uninstallation method may not work on your cluster in its current situation, however.

It looks like the extra uninstall command you ran removed a finalizer from the longhorn-system namespace, but not other Longhorn objects. To move forward, I recommend attempting to fully delete all Longhorn related components again before doing a fresh install (this is especially necessary for the Longhorn node objects, which appear to be deleting).

You can use a command like the following to identify any and all resources in the longhorn-system namespace that have failed to clean up (after making an initial attempt at deleting them all).

```
kubectl api-resources --verbs=list --namespaced -o name \
  | xargs -n 1 kubectl get --show-kind --ignore-not-found -n longhorn-system
```

**Comment by ejweber** [comment]
Sorry for the delayed response.

```
serviceaccount/longhorn-uninstall-service-account unchanged
clusterrole.rbac.authorization.k8s.io/longhorn-uninstall-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/longhorn-uninstall-bind unchanged
Warning: resource jobs/longhorn-uninstall is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
The Job "longhorn-uninstall" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"longhorn-uninstall", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"batch.kubernetes.io/controller-uid":"ffd463e1-c8e4-4303-b5af-85191509917d", "batch.kubernetes.io/job-name":"longhorn-uninstall", "controller-uid":"ffd463e1-c8e4-4303-b5af-85191509917d", "job-name":"longhorn-uninstall"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"longhorn-uninstall", Image:"longhornio/longhorn-manager:master-head", Command:[]string{"longhorn-manager", "uninstall", "--force"}, Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar{core.EnvVar{Name:"LONGHORN_NAMESPACE", Value:"longhorn-system", ValueFrom:(*core.EnvVarSource)(nil)}}, Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil), Claims:[]core.ResourceClaim(nil)}, ResizePolicy:[]core.ContainerResizePolicy(nil), VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(0xc034fa53e0), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:"Never", TerminationGracePeriodSeconds:(*int64)(0xc018a35f40), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"longhorn-uninstall-service-account", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc01e6173b0), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil), OS:(*core.PodOS)(nil), SchedulingGates:[]core.PodSchedulingGate(nil), ResourceClaims:[]core.PodResourceClaim(nil)}}: field is immutable
```

These errors typically appear when apply an `uninstall.yaml` to a cluster it has already been applied to. This can be overcome by doing a `kubectl delete -f uninstall.yaml` before applying again.

The node objects you found are stuck deleting because there is still a `longhorn.io` finalizer on them. When it works correctly, `uninstall.yaml` deletes resources in a particular order. These node objects should be deleted while `longhorn-manager` is still running so it can remove the finalizers (after doing some cleanup).

At this point, they can be deleted by `kubectl edit node -n longhorn-system <name>` and delete `longhorn.io` from the finalizer list.

**Comment by lindhe** [comment]
@abiancini Try using [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks) to make those multi-line strings easier to read!

**Comment by ejweber** [comment]
Looks like we haven't had an update on this issue since July. I'm going to go ahead and close it out. Please reopen it or create a new one if the problem still persists!
