### ISSUE TITLE
[BUG] Volume detached automatically after upgrade Longhorn

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#5983]
## Describe the bug (🐛 if you encounter this issue)

Create a volume and attach it to a node, and upgrade Longhorn, after Longhorn upgraded, the attached volume is detached automatically. Need to confirm if it's the expected behavior.

## To Reproduce

1. Install Longhorn v1.4.0
2. Create a volume from UI, and attach it to a node from UI
3. Upgrade Longhorn to master-head
4. The attached volume becomes detached

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by PhanLe1010** [comment]
This will be fix after the upgrade logic PR is finished https://github.com/longhorn/longhorn-manager/pull/1920

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 6631855).

e2e upgrade test results all pass:
upgrade from v1.4.2: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3977/
upgrade from v1.4.0: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3978/
