### ISSUE TITLE
[BUG] Longhorn Read-Only setting can be modified

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#5989]
## Describe the bug (🐛 if you encounter this issue)

Longhorn read-only setting can be modified e.g., `current-longhorn-version`

![2023-05-23](https://github.com/longhorn/longhorn/assets/14231257/33b71923-362e-4e40-af0e-0009d59ea310)

and [the setting definition](https://github.com/longhorn/longhorn-manager/blob/master/types/setting.go#L482-L490) is set to be read-only

## To Reproduce

1. New installed Longhorn
2. Modified `current-longhorn-version` by `kubectl edit setting`
3. `current-longhorn-version` will be modified

## Expected behavior

Read-only setting should not be modified.

## Environment

 - Longhorn version: master-head (20230523)
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.26.3+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: ubuntu 2202
   - CPU per node: 4
   - Memory per node: 4G
   - Disk type(e.g. SSD/NVMe): 30G
   - Network bandwidth between the nodes: 1G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 1

**Comment by mantissahz** [comment]
related: https://github.com/longhorn/longhorn/issues/5028

**Comment by mantissahz** [comment]
Notice:
We still are able to modify read-only settings by `Longhorn APIs` directly such as [a Longhorn Python client](https://longhorn.io/docs/1.5.1/references/longhorn-client-python/).

**Comment by innobead** [comment]
That's fine for now, because the rest API is not a formal interface. What we protected now is formal interfaces like CR and UI.

**Comment by mantissahz** [comment]
>IIRC, when updating a read only setting, it requires a Longhorn specific annotation. That means if users update it with adding the annotation, the setting will be updated even though using kubectl, right?
That means the protection here is just a best effort.

@innobead Yes, that's it, users can modify a read-only setting with adding the annotation

**Comment by roger-ryao** [comment]
**Verified on master-head 20231116**

- longhorn master-head https://github.com/longhorn/longhorn/commit/74d829d6e81c937baa25a6bc78041f27b361b5e5
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/483ef28241deeae04cb193d1fd22d1b213915835

**Tested Step Passed**

https://github.com/longhorn/longhorn/issues/5989#issuecomment-1747921042

**Result Passed**

1. `current-longhorn-version` could not be modified
![Screenshot_20231116_161940](https://github.com/longhorn/longhorn/assets/104337648/5cc25189-af88-4bd7-9f86-77371e47816e)
