### ISSUE TITLE
instance-manager-e and instance-manager-r R/W Timeout on the same node cause the pod to restart

### ISSUE THREAD

**Issue by lczcode** [longhorn/longhorn#5997]
I want to know why R/W times out occurs in the engine and replicas in the same node (replicas is 1).

This is pod information for the engine and replicas, both of which are on the worker2 node
![img_v2_1d2e9319-6203-45bb-b5b4-c4c90e2acb9g](https://github.com/longhorn/longhorn/assets/37427516/b4a05336-3231-4d15-bce1-e6b38313b387)

Below is the engine log（10.42.33.26 is the replicas ip mentioned above）
![img_v2_c0cc62ff-aa0f-4422-bc10-e018e4fa4f1g](https://github.com/longhorn/longhorn/assets/37427516/c7abcf3d-e6d4-4eae-b75d-e65ce7f3560c)
![img_v2_af57ad07-6134-40c2-9200-2d0e7e66596g](https://github.com/longhorn/longhorn/assets/37427516/ce249d02-85b0-4b22-a68e-498988ea5004)
![img_v2_939147a4-43f4-4b2e-a771-cc388c58bbbg](https://github.com/longhorn/longhorn/assets/37427516/c6d68a47-1fcb-4d8f-ba45-30f64401b33f)
![img_v2_ba7a9c44-f5b8-45d5-8356-eba87b023feg](https://github.com/longhorn/longhorn/assets/37427516/0dfbbc39-5dc1-4edb-9b75-985f99aeb540)
![img_v2_1eaa91d7-931c-4061-b1f2-bba207c6e5eg](https://github.com/longhorn/longhorn/assets/37427516/c8f660c6-4ef2-4d23-9b54-37a543e5ed66)

This is the instance - manager - e - c5d617785c172f4235c84611de20d969 complete log
[instance-manager-e-c5d617785c172f4235c84611de20d969.log](https://github.com/longhorn/longhorn/files/11554411/instance-manager-e-c5d617785c172f4235c84611de20d969.log)

**Comment by lczcode** [comment]
longhorn v1.4.1

**Comment by derekbit** [comment]
Can you please provide detailed specifications of your environment such as the type and model of CPU, the amount of memory, and the type and capacity of the underlying storage?
In addition, number of volumes/replicas and the workload type? Are they IO intensive?

**Comment by lczcode** [comment]
> Can you please provide detailed specifications of your environment such as the type and model of CPU, the amount of memory, and the type and capacity of the underlying storage? In addition, number of volumes/replicas and the workload type? Are they IO intensive?

A k3s cluster consists of three nodes, one master of which is two nodes. All nodes have the same specifications (system, cpu, memory, disk, and network)

cpu screenshot
![image](https://github.com/longhorn/longhorn/assets/37427516/4c82c233-8516-4793-a968-5d1110c7f5f2)

memory size 32Gi

disk screenshot
![image](https://github.com/longhorn/longhorn/assets/37427516/03bb6166-94ee-4ab6-a324-be09603140d9)
![image](https://github.com/longhorn/longhorn/assets/37427516/66293ee3-a0da-49de-8ea9-962653161a0d)

longhorn volume Replicas is 1, and services that use storage are not IO intensive
This is a screenshot of the configuration of longhorn
![image](https://github.com/longhorn/longhorn/assets/37427516/75ea589b-aa09-4af3-8842-d0a95580f546)
![image](https://github.com/longhorn/longhorn/assets/37427516/90ba1f8a-7216-407f-b8b4-fd8e1ee0da04)
![image](https://github.com/longhorn/longhorn/assets/37427516/cf065237-1219-4271-99c1-838a50ca3226)
![image](https://github.com/longhorn/longhorn/assets/37427516/876d0ac9-28dd-4e98-a932-f30b6fa5f8f2)
![image](https://github.com/longhorn/longhorn/assets/37427516/50f4c30a-c6d0-4d8c-90a1-2bc75d1d2ca3)

**Comment by lczcode** [comment]
> Can you provide the worker nodes' `dmesg` log? Thank you.

This is worker2 logs，`dmesg` logs not a lot of information
[dmesg.log](https://github.com/longhorn/longhorn/files/11563741/dmesg.log)
[journalctl_2023-05-24.log](https://github.com/longhorn/longhorn/files/11563743/journalctl_2023-05-24.log)

**Comment by lczcode** [comment]
A brief press test of the disk longhorn is using has the following information
```
test: (g=0): rw=randread, bs=(R) 512KiB-512KiB, (W) 512KiB-512KiB, (T) 512KiB-512KiB, ioengine=libaio, iodepth=1
fio-3.7
Starting 1 process
test: Laying out IO file (1 file / 1024MiB)
Jobs: 1 (f=1): [r(1)][100.0%][r=1352MiB/s,w=0KiB/s][r=2703,w=0 IOPS][eta 00m:00s]
test: (groupid=0, jobs=1): err= 0: pid=7603: Mon May 29 00:36:47 2023
   read: IOPS=2418, BW=1209MiB/s (1268MB/s)(11.8GiB/10001msec)
    slat (usec): min=26, max=1537, avg=27.82, stdev=10.30
    clat (usec): min=87, max=342318, avg=384.63, stdev=2345.53
     lat (usec): min=157, max=342345, avg=412.56, stdev=2345.54
    clat percentiles (usec):
     |  1.00th=[  137],  5.00th=[  139], 10.00th=[  143], 20.00th=[  157],
     | 30.00th=[  161], 40.00th=[  163], 50.00th=[  165], 60.00th=[  167],
     | 70.00th=[  169], 80.00th=[  693], 90.00th=[ 1074], 95.00th=[ 1254],
     | 99.00th=[ 1516], 99.50th=[ 2040], 99.90th=[ 2966], 99.95th=[ 3130],
     | 99.99th=[ 9634]
   bw (  MiB/s): min=  238, max= 1591, per=98.61%, avg=1192.48, stdev=311.43, samples=19
   iops        : min=  476, max= 3182, avg=2384.95, stdev=622.85, samples=19
  lat (usec)   : 100=0.01%, 250=76.11%, 500=0.93%, 750=3.83%, 1000=6.18%
  lat (msec)   : 2=12.41%, 4=0.52%, 10=0.01%, 250=0.01%, 500=0.01%
  cpu          : usr=0.49%, sys=7.71%, ctx=24316, majf=0, minf=162
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=24188,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=1209MiB/s (1268MB/s), 1209MiB/s-1209MiB/s (1268MB/s-1268MB/s), io=11.8GiB (12.7GB), run=10001-10001msec

Disk stats (read/write):
    dm-2: ios=23906/29, merge=0/0, ticks=9122/21, in_queue=9143, util=91.47%, aggrios=24194/27, aggrmerge=0/2, aggrticks=9235/19, aggrin_queue=9230, aggrutil=91.06%
  sdb: ios=24194/27, merge=0/2, ticks=9235/19, in_queue=9230, util=91.06%
```
