### ISSUE TITLE
[FEATURE] UI modification to work with new AD mechanism (Longhorn UI -> Longhorn API)

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#6004]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

With the new attachment detachment refactoring, the interface for detach and attach API has changed.

For attach API, there are 5 parameters:
```
type AttachInput struct {
	HostID          string `json:"hostId"`
	DisableFrontend bool   `json:"disableFrontend"`
	AttachedBy      string `json:"attachedBy"`
	AttacherType    string `json:"attacherType"`
	AttachmentID    string `json:"attachmentID"`
}
```
UI should set `AttachmentID` to `longhorn-ui` and `HostID` to corresponding node that user selected. The rest should be left empty.

For detach API, there are 3 parameters:
```
type DetachInput struct {
	AttachmentID string `json:"attachmentID"`
	HostID       string `json:"hostId"`
	ForceDetach  bool   `json:"forceDetach"`
}
```
UI should set `AttachmentID` to `longhorn-ui`, this will instruct Longhorn backend to clear the attachment ticket created by UI. Also, presenting the user with a check box for `ForceDetach`. If the user set this field Longhorn backend will clear out all attachment tickets including the system auto attachment tickets and workload tickets to force the volume to be detached. So display a warning when user set that checkbox. The rest should be left empty.

This is a part of the ticket longhorn/longhorn#3715

**Comment by PhanLe1010** [comment]
cc @smallteeths Could you please help? This will go to Longhorn v1.5.0

**Comment by smallteeths** [comment]
> cc @smallteeths Could you please help? This will go to Longhorn v1.5.0

Okay

**Comment by PhanLe1010** [comment]
Thank you very much

**Comment by innobead** [comment]
@PhanLe1010 need you to provide test plans for this UI change and move to ready-for-testing.

**Comment by PhanLe1010** [comment]
## Test plan

### Basic test
1. Test attach/detach volume using UI in normal/maintenance mode
1. Verify that
    1. For attach call, UI sends the attach request with `attachmentID` to `longhorn-ui` and `hostID` to the corresponding node that user selected, `disableFrontend` to the corresponding normal/maintenance mode. The rest should be left empty.
    1. For detach call, UI sends the detach request with `attachmentID` to `longhorn-ui`, `hostID` to empty, and `forceDetach` o the corresponding user-selected value
1. Create deployment using Longhorn volume. Force detach the volume using Longhorn UI. Verify that the volume is able to detach

### Upgrade test
1. Deploy Longhorn older version v1.4.x
1. Create a volume and attach it to a node using UI
1. Upgrade Longhorn to master-head
1. Verify that the Longhorn volume is NOT detached in during this process
1. Detach the volume using UI 
1. Verify that the volume is detached
1. Attached the volume using UI verify that the volume is attached
1. Detach/Attach volume in maintenance mode. Verify that things are working as expected

**Comment by yangchiu** [comment]
It seems has a bug when attaching a volume on the volume list page:
![Screenshot from 2023-06-05 09-15-49](https://github.com/longhorn/longhorn/assets/5709208/7ce96739-501d-4204-835e-2a4401b24453)
When the `attach` button clicked, it sent a request with `attachmentID = ""` instead of `attachmentID = "longhorn-ui"`, which causes `detach` failed. 

cc @smallteeths

**Comment by smallteeths** [comment]
> It seems has a bug on master-head (longhorn-ui 7073444) when attaching a volume on the volume list page: ![Screenshot from 2023-06-05 09-15-49](https://user-images.githubusercontent.com/5709208/243253126-7ce96739-501d-4204-835e-2a4401b24453.png) When the `attach` button clicked, it sent a request with `attachmentID = ""` instead of `attachmentID = "longhorn-ui"`, which causes `detach` failed.
> 
> cc @smallteeths

Thank you. I forgot to modify the bulk attach operation.
new image: `wangsiye/longhorn-ui:6975f03`

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 73dab70, longhorn-ui e6cc645) following [the test plan](https://github.com/longhorn/longhorn/issues/6004#issuecomment-1574164491).
