### ISSUE TITLE
[IMPROVEMENT] Implement/fix the unit tests of Volume Attachment and volume controller

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#6005]
Implement/fix unit tests of Volume Attachment and Volume controller

https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_attachment_controller_test.go
https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller_test.go

**Comment by innobead** [comment]
Also, need to backport this to 1.5.x even if its unit tests because it will help with the PR check.

**Comment by PhanLe1010** [comment]
**Test plan:**
Just make sure that longhorn-manager image is built successfully

**Comment by roger-ryao** [comment]
Referring to https://github.com/longhorn/longhorn/issues/6303#issuecomment-1636745861, it was confirmed through https://drone-pr.longhorn.io/longhorn/longhorn-manager/5596/1/3 that the issue has been resolved.
