### ISSUE TITLE
Accessing any route with the word `backup` in it attempts to list backups

### ISSUE THREAD

**Issue by ttpcodes** [longhorn/longhorn#601]
I've been able to reproduce this on `v0.5.0` of `longhorn` and on the `master` versions of all of the `longhorn` components.

The main way to encounter this issue is by creating a volume named `backup` and attempting to view its information. This will take you to the route `/volume/backup`, which triggers the logic that the `longhorn-ui` uses to attempt to list off `Backups`. This applies to other routes too, so appending `backup` to the dashboard route to obtain `/dashboard/backup`, while it returns the 404 page, still triggers the `Backup` list logic.

This means that if the `Backup Target` `Setting` is unset, the error notification for it being unset will pop up. If there's an issue accessing the `Backup Target` to list the `Backups`, that error notification will pop up. Nothing occurs on the page if accessing the `Backups` page would've been successful.

**Comment by yasker** [comment]
Nice catch @ttpcodes ! @smallteeths Can you take a look at what's happened?

**Comment by meldafrawi** [comment]
Steps to test:
- Make sure `Backup Target` `Setting` is unset. 
- Create a volume named `backup`
    - `/volume/backup` path in longhorn ui should go to volume details page.
    - `/dashboard/backup` should return 404 error.
    - in both cases, you should **NOT** be able to see `error listing backups: error listing backup volumes`  notification
