### ISSUE TITLE
[BUG] Volume become detach after upgrade from v1.4.2 to master-head

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#6012]
## Describe the bug (🐛 if you encounter this issue)

From pipeline upgrade test [case](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/481/testReport/junit/tests/test_upgrade/test_upgrade_from_stable_/)
Volume become detach after upgrade from v1.4.2 to master-head

## To Reproduce

1. Deploy Longhorn v1.4.2
2. Dynamic provision volume. Write data into volume.
3. Upgrade Longhorn to master-head
4. Volume become detached

## Expected behavior

Volume attached and data intact

## Log or Support bundle

```
test-deployment-568b845799-4qvht    1/1     Running   0          11m
test-deployment2-7b7fbc9fdd-dnwd5   1/1     Running   0          11m
root@ip-172-31-24-222:/home/ubuntu# 
root@ip-172-31-24-222:/home/ubuntu# k get volumes -A
NAMESPACE         NAME           STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE   AGE
longhorn-system   vol2-disable   detached   unknown                  1073741824          12m
longhorn-system   vol1-enable    detached   unknown                  1073741824          13m
```

![Screenshot from 2023-05-29 10-05-51](https://github.com/longhorn/longhorn/assets/73337386/20d1ca9f-48f6-40f1-aebb-f309a5c3d4a3)

[supportbundle_81efc952-e449-4281-900a-be7efe6d2a75_2023-05-29T02-02-47Z.zip](https://github.com/longhorn/longhorn/files/11587550/supportbundle_81efc952-e449-4281-900a-be7efe6d2a75_2023-05-29T02-02-47Z.zip)

## Environment

 - Longhorn version: master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.24.7+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3

## Additional context

N/A

**Comment by chriscchien** [comment]
Volume attached success after scale down/up deployment, data intact. Do engine upgrade, data still intact.

**Comment by derekbit** [comment]
After upgrading from v1.4.2 to master-head
- `VolumeAttachment` for the **already existing and attached** volume is created, but `AttachmentTickets` is empty. ([code](https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go#LL536C4-L536C4))
- The empty `AttachmentTickets` triggers the detachment of the volume. ([code](https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_attachment_controller.go#L411-L414))
- Volume is requested to be detached ([code](https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go#L1355-L1357))
- Engine is set to `stopped` ([code](https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go#L1760))
- Engine process is deleted
- ...
- All old instance-managers are cleaned up. ([code](https://github.com/longhorn/longhorn-manager/blob/master/controller/node_controller.go#L962-L989))


cc @PhanLe1010

**Comment by PhanLe1010** [comment]
This is a duplication of the https://github.com/longhorn/longhorn/issues/5983. It was because https://github.com/longhorn/longhorn-manager/pull/1920 had not been merged. Thanks @chriscchien for reporting and @derekbit for investigate

**Comment by chriscchien** [comment]
Duplicate and already verified in https://github.com/longhorn/longhorn/issues/5983.
