### ISSUE TITLE
[IMPROVEMENT]  Fix scheduling flooding logs

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6019]
Just had a discussion with @ChanYiLin about the recurring log messages mentioned in this GitHub issue: https://github.com/longhorn/longhorn/issues/4069.

It appears that changing the log level setting to "info" can resolve the problem. However, we are unable to know the status/error of the scheduler, for example, no available disks or nodes.

I'm thinking whether it would be better to record the scheduler status/error in node conditions instead. By doing so, we can prevent the excessive log message flooding and know the scheduler's status.

WDYT? @innobead @ChanYiLin

_Originally posted by @derekbit in https://github.com/longhorn/longhorn/issues/5888#issuecomment-1567875532_

**Comment by ChanYiLin** [comment]
Sounds good to me!

**Comment by ChanYiLin** [comment]
1. Most of the flooding logs can be changed to `Debug`
we just keep those important decision making message.

2. For the warning `log.Warn("Found 0 node has at least one schedulable disk")` in `getIsSchedulableToDiskNodes` function
we only trigger the function when we really need to do autobalance. We then prevent this logs from keeping showing up.

**Comment by roger-ryao** [comment]
**Verified on master-head 20230920**

- longhorn master-head https://github.com/longhorn/longhorn/commit/cb61e92a130f3bac2480197529bd5cc8b73b7fde
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/a66539f419ff3d2c68c04586b2d8df7211fca278

**The test steps**

1. Ref. https://github.com/longhorn/longhorn/issues/6019#issuecomment-1725046088


**Result Passed**

1. We didn't observe any `replica candidates for auto-balance` messages in the longhorn-manager pod.
