### ISSUE TITLE
[FEATURE] Support v2 volume on ARM64 platform

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6021]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

SPDK supports ARM64 platform, so Longhorn will support it as well.
For s390x platform, SPDK seems not available for now.

## Describe the solution you'd like

A clear and concise description of what you want to happen

**Comment by innobead** [comment]
@derekbit let's have a doc for that. https://longhorn.io/docs/1.6.0/spdk/features/

**Comment by chriscchien** [comment]
Hi @derekbit , I try deploy v2 volume on arm64 platform, encountered 2 issues below may need you help, thank you.

1. On one node, after block disk added, the instance-manager pod, kept in Running -> Error -> Terminating loop  and the disk can not be scheduled.
  
```
> k -n longhorn-system logs instance-manager-026a3faf7c2b016e2939d3b0c726c4e4 
Enabling tgtd
tgtd: work_timer_start(146) use timer_fd based scheduler
tgtd: bs_init(393) use pthread notification
Enabling spdk_tgt with options: 
[2023-12-29 08:46:11.397307] Starting SPDK v23.05-pre git sha1 700b93962 / DPDK 22.11.1 initialization...
[2023-12-29 08:46:11.397497] [ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --huge-unlink --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid16 ]
EAL: error allocating rte services array
EAL: FATAL: rte_service_init() failed
EAL: rte_service_init() failed
[2023-12-29 08:46:11.406271] init.c: 617:spdk_env_init: *ERROR*: Failed to initialize DPDK
[2023-12-29 08:46:11.406300] app.c: 352:app_setup_env: *ERROR*: Unable to initialize SPDK env
[2023-12-29 08:46:11.406330] app.c: 555:unclaim_cpu_cores: *ERROR*: Failed to unlink lock fd for core 0, errno: 2
```
2. Pod can not mount to dynamic provisioned v2 volume. perform below 2 commands, and the pod can not attach to volume
```
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/v2/storageclass.yaml
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/v2/pod_with_pvc.yaml
```

```
Events:
  Type     Reason              Age               From                     Message
  ----     ------              ----              ----                     -------
  Warning  FailedScheduling    2m20s             default-scheduler        0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling..
  Warning  FailedScheduling    2m18s             default-scheduler        0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling..
  Normal   Scheduled           2m16s             default-scheduler        Successfully assigned default/volume-test to ip-172-31-33-199
  Warning  FailedAttachVolume  7s (x7 over 42s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-d4e4d605-bd2e-4663-9dd0-f2579c0c2d3a" : rpc error: code = DeadlineExceeded desc = volume pvc-d4e4d605-bd2e-4663-9dd0-f2579c0c2d3a failed to attach to node ip-172-31-33-199 with attachmentID csi-d1161d9f15d84a671818928390d66f26ee122da41873d3da50074349e8de5ee3
```

[supportbundle_3ac218b9-9ebd-4e21-8135-3c85e0f0f535_2023-12-29T08-52-41Z.zip](https://github.com/longhorn/longhorn/files/13792148/supportbundle_3ac218b9-9ebd-4e21-8135-3c85e0f0f535_2023-12-29T08-52-41Z.zip)

**Comment by derekbit** [comment]
> Hi @derekbit , I try deploy v2 volume on arm64 platform, encountered 2 issues below may need you help, thank you.
> 
> 1. On one node, after block disk added, the instance-manager pod, kept in Running -> Error -> Terminating loop  and the disk can not be scheduled.
> 
> ```
> > k -n longhorn-system logs instance-manager-026a3faf7c2b016e2939d3b0c726c4e4 
> Enabling tgtd
> tgtd: work_timer_start(146) use timer_fd based scheduler
> tgtd: bs_init(393) use pthread notification
> Enabling spdk_tgt with options: 
> [2023-12-29 08:46:11.397307] Starting SPDK v23.05-pre git sha1 700b93962 / DPDK 22.11.1 initialization...
> [2023-12-29 08:46:11.397497] [ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --huge-unlink --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid16 ]
> EAL: error allocating rte services array
> EAL: FATAL: rte_service_init() failed
> EAL: rte_service_init() failed
> [2023-12-29 08:46:11.406271] init.c: 617:spdk_env_init: *ERROR*: Failed to initialize DPDK
> [2023-12-29 08:46:11.406300] app.c: 352:app_setup_env: *ERROR*: Unable to initialize SPDK env
> [2023-12-29 08:46:11.406330] app.c: 555:unclaim_cpu_cores: *ERROR*: Failed to unlink lock fd for core 0, errno: 2
> ```
> 
> 2. Pod can not mount to dynamic provisioned v2 volume. perform below 2 commands, and the pod can not attach to volume
> 
> ```
> kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/v2/storageclass.yaml
> kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/v2/pod_with_pvc.yaml
> ```
> 
> ```
> Events:
>   Type     Reason              Age               From                     Message
>   ----     ------              ----              ----                     -------
>   Warning  FailedScheduling    2m20s             default-scheduler        0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling..
>   Warning  FailedScheduling    2m18s             default-scheduler        0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling..
>   Normal   Scheduled           2m16s             default-scheduler        Successfully assigned default/volume-test to ip-172-31-33-199
>   Warning  FailedAttachVolume  7s (x7 over 42s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-d4e4d605-bd2e-4663-9dd0-f2579c0c2d3a" : rpc error: code = DeadlineExceeded desc = volume pvc-d4e4d605-bd2e-4663-9dd0-f2579c0c2d3a failed to attach to node ip-172-31-33-199 with attachmentID csi-d1161d9f15d84a671818928390d66f26ee122da41873d3da50074349e8de5ee3
> ```
> 
> [supportbundle_3ac218b9-9ebd-4e21-8135-3c85e0f0f535_2023-12-29T08-52-41Z.zip](https://github.com/longhorn/longhorn/files/13792148/supportbundle_3ac218b9-9ebd-4e21-8135-3c85e0f0f535_2023-12-29T08-52-41Z.zip)

Were's your arm64 platform? I tested it on Equinix machines.

**Comment by derekbit** [comment]
Thanks for the environment provided by @roger-ryao .
The cluster was bootstrapped on last Friday.
spdk_tgt works expectedly, but there are some invalid argument errors in longhorn-instance-manager pod. Because there are some PRs being merged on that day, I suggest creating a new env and testing it again.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `b63565`)

On ARM64 platform(ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-arm64-server-20231207) and v1.28.2+k3s1, below items worked well
- [x] Setup v2 volume environment
- [x] Dynamic provision v2 volume
- [x] Offline rebuilding
- [x] Attach/detach v2 volume by scaling worklod

I will close this ticket after the DOC mentioned [here](https://github.com/longhorn/longhorn/issues/6021#issuecomment-1871720203) ready, thank you.
