### ISSUE TITLE
[BUG] Webhook PDBs are not removed after upgrading to master-head

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#6026]
## To Reproduce
1. DeployLonghorn v1.4.2. Create and attach some Longhorn volumes
2. Update Longhorn to master-head. Delete all Longhorn volumes
3. Observe that `longhorn-admission-webhook` and `longhorn-conversion-webhook` PDBs are not removed

## Expected behavior

Observe that `longhorn-admission-webhook` and `longhorn-conversion-webhook` PDBs are removed

**Comment by weizhe0422** [comment]
**Verified on master-head 20230601**

- https://github.com/longhorn/longhorn-manager/commit/6e12760cb71727ee5901d4a472b7649e5e727a7c

Result: **PASSED**

Test steps:
 1. Install Longhorn V1.4.2, and create two volumes with writing some data into mount point
    ![image](https://github.com/longhorn/longhorn/assets/17548901/59ae296f-4f38-4012-95ed-c6886f004aae)
    - check that the PDBs for `longhorn-admission-webhook` and `longhorn-conversion-webhook` exist
    ![image](https://github.com/longhorn/longhorn/assets/17548901/2643e91b-90c8-45c9-9a20-518974e53b7b)
 2. Upgrade Longhorn to master branch build withing using `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml`
    - The PDBs for `longhorn-admission-webhook` and `longhorn-conversion-webhook` are gone after upgrading 
    ![image](https://github.com/longhorn/longhorn/assets/17548901/8c68da12-6f2d-4c1f-a7a3-ccdc2e09012e)
