### ISSUE TITLE
[IMPROVEMENT] the `if-not-present` volume backup policy should also check if the latest backup is up-to-date

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#6027]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Currently, the `if-not-present` policy only checks if the volume has an existing backup, it doesn't check if the latest backup reflects the most recent data.

## Describe the solution you'd like

Check if the latest backup data is up-to-date.

## Describe alternatives you've considered

`None`

## Additional context

https://github.com/longhorn/longhorn-tests/pull/1388#discussion_r1210663186

**Comment by c3y1huang** [comment]
Proposed change:

When the volume backup policy is set to if-not-present, verify that the last backup is up-to-date by:
1. Creating a new volume backup snapshot.
1. Counting snapshots created after the late backup snapshot that contain data.
1. Skipping backup creation if the count is zero.

**Comment by derekbit** [comment]
Let's add it to the important note of v1.8.0. Thank you,

**Comment by c3y1huang** [comment]
> Let's add it to the important note of v1.8.0. Thank you,

https://github.com/longhorn/website/pull/1009

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-manager/commit/a503949c751f8bb07d9835f3680b93d5bc807e30) by running test case `test_system_backup_with_volume_backup_policy_if_not_present` from this [PR](https://github.com/longhorn/longhorn-tests/pull/2154), if the PR changed before merge, I will reopen this ticket and test again.
