### ISSUE TITLE
[TASK][UI] Support volume backup policy

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#6028]
## What's the task? Please describe

Support volume backup policy (`if-not-present`, `always`, `disabled`) when creating the Longhorn system backup.

## Describe the items of the task (DoD, definition of done) you'd like
- [ ] User can select from a list of volume backup policies when creating the Longhorn system backup.

## Additional context

https://github.com/longhorn/longhorn/issues/5011

**Comment by c3y1huang** [comment]
cc @smallteeths

**Comment by chriscchien** [comment]
Verified **pass** in longhorn master (longhorn `985634`, longhorn-manager `663185`, longhorn-ui `51e912`)

Volume backup policy of UI verified in https://github.com/longhorn/longhorn/issues/5011#issuecomment-1573083532
