### ISSUE TITLE
[IMPROVEMENT] Collect v2 Data Engine related info for the usage metrics

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#6033]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Enhance the collections to include SPDK implementation.

## Describe the solution you'd like

- Add node disk type (filesystem, block) collection
- Add volume backend store driver (v1, v2)
- Collect device type when disk type is `block`

## Describe alternatives you've considered

`None`

## Additional context

https://github.com/longhorn/longhorn-manager/pull/1891#discussion_r1209295053
https://github.com/longhorn/longhorn-manager/pull/2346#issuecomment-1849378144

**Comment by innobead** [comment]
cc @derekbit @shuo-wu

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `c46a54`) with test [steps](https://github.com/longhorn/longhorn-tests/pull/1619/files?short_path=8a27a68#diff-8a27a68e39aad6869cd051642c496980760a3e541ad87d0201849d7f7ab35cc8)

Deploy Longhorn and create **3** v1 volumes and **2** v2 volumes:

`longhorn_disk_filesystem_Count`
```bash
> kubectl exec -it ${influxdb_pod} -- influx -execute 'SELECT "longhorn_disk_filesystem_count" FROM "upgrade_request"' -database="${app_name}_upgrade_responder"
name: upgrade_request
time                longhorn_disk_filesystem_count
----                ------------------------------
1703234426043451144 1
1703234426882845418 1
1703234426998184569 1
``` 
`longhorn_disk_block_count`
```bash
> kubectl exec -it ${influxdb_pod} -- influx -execute 'SELECT "longhorn_disk_block_count" FROM "upgrade_request"' -database="${app_name}_upgrade_responder"
name: upgrade_request
time                longhorn_disk_block_count
----                -------------------------
1703234426043451144 1
1703234426998184569 1
```
`longhorn_volume_backend_store_driver_v1_count`
```bash
> kubectl exec -it ${influxdb_pod} -- influx -execute 'SELECT "longhorn_volume_backend_store_driver_v1_count" FROM "upgrade_request"' -database="${app_name}_upgrade_responder"
name: upgrade_request
time                longhorn_volume_backend_store_driver_v1_count
----                ---------------------------------------------
1703234426043451144 3
```
`longhorn_volume_backend_store_driver_v2_count`
```bash
> kubectl exec -it ${influxdb_pod} -- influx -execute 'SELECT "longhorn_volume_backend_store_driver_v2_count" FROM "upgrade_request"' -database="${app_name}_upgrade_responder"
name: upgrade_request
time                longhorn_volume_backend_store_driver_v2_count
----                ---------------------------------------------
1703234426043451144 2

```
