### ISSUE TITLE
how to solve longhorn node not ready

### ISSUE THREAD

**Issue by shaolila** [longhorn/longhorn#6037]
## Question
my longhorn node show notready ,how can I restore node state

# kubectl get lhn -A
NAMESPACE               NAME               READY ALLOWSCHEDULING SCHEDULABLE AGE
longhorn-system master-b99de-1    False        true                            True                69m

on node master-b99de-1  ,I  have 4 disks ,but only one in describe :

# lsblk
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda 8:0 0 1.7T 0 disk
sdb 8:16 0 1.7T 0 disk /xos-disk
sdc 8:32 0 1.7T 0 disk /xos-disk2
sdd 8:48 0 1.7T 0 disk /xos-disk3

## Environment

 - Longhorn version:
 - Kubernetes version:
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

## Additional context

# kubectl get lhn -A
NAMESPACE NAME READY ALLOWSCHEDULING SCHEDULABLE AGE
longhorn-system master-60865-0 True true True 9d
longhorn-system master-b99de-1 False true True 69m
longhorn-system master-f714a-2 True true True 9d

# kubectl describe lhn -n longhorn-system master-b99de-1
Name: master-b99de-1
Namespace: longhorn-system
Labels: <none>
Annotations: <none>
API Version: [longhorn.io/v1beta2](http://longhorn.io/v1beta2)
Kind: Node
Metadata:
Creation Timestamp: 2023-06-01T10:57:03Z
Finalizers:
[longhorn.io](http://longhorn.io/)
Generation: 1
Managed Fields:
API Version: [longhorn.io/v1beta2](http://longhorn.io/v1beta2)
Fields Type: FieldsV1
fieldsV1:
f:spec:
.:
f:allowScheduling:
f:disks:
.:
f:default-disk-7e31d863af7d38e7:
.:
f:allowScheduling:
f:evictionRequested:
f:path:
f:storageReserved:
f:tags:
f:engineManagerCPURequest:
f:evictionRequested:
f:name:
f:replicaManagerCPURequest:
f:tags:
Manager: longhorn-manager
Operation: Update
Time: 2023-06-01T10:57:03Z
API Version: [longhorn.io/v1beta2](http://longhorn.io/v1beta2)
Fields Type: FieldsV1
fieldsV1:
f:status:
.:
f:conditions:
f:diskStatus:
.:
f:default-disk-7e31d863af7d38e7:
.:
f:conditions:
f:diskUUID:
f:scheduledReplica:
.:
f:pvc-3ecd481a-5db4-4648-976b-57853566720f-r-3ceb0a70:
f:pvc-629a85b9-3063-4006-9303-f95b9fe05ffa-r-4d243b68:
f:pvc-a6b4e385-bcc8-4c79-a815-103df854e211-r-4165488d:
f:storageAvailable:
f:storageMaximum:
f:storageScheduled:
f:region:
f:snapshotCheckStatus:
f:zone:
Manager: longhorn-manager
Operation: Update
Subresource: status
Time: 2023-06-01T10:57:32Z
Resource Version: 10734984
UID: ec9409db-f590-49eb-a1cb-a0102b1d7d0d
Spec:
Allow Scheduling: true
Disks:
default-disk-7e31d863af7d38e7:
Allow Scheduling: true
Eviction Requested: false
Path: /xos-storage/longhorn
Storage Reserved: 22033659494
Tags:
Engine Manager CPU Request: 0
Eviction Requested: false
Name: master-b99de-1
Replica Manager CPU Request: 0
Tags:
Status:
Conditions:
Last Probe Time:
Last Transition Time: 2023-06-01T11:05:46Z
Message: Kubernetes node master-b99de-1 has pressure: KubeletHasDiskPressure, kubelet has disk pressure
Reason: KubernetesNodePressure
Status: False
Type: Ready
Last Probe Time:
Last Transition Time: 2023-06-01T10:57:03Z
Message:
Reason:
Status: True
Type: Schedulable
Last Probe Time:
Last Transition Time: 2023-06-01T10:57:02Z
Message:
Reason:
Status: True
Type: MountPropagation
Disk Status:
default-disk-7e31d863af7d38e7:
Conditions:
Last Probe Time:
Last Transition Time: 2023-06-01T10:57:02Z
Message: Disk default-disk-7e31d863af7d38e7(/xos-storage/longhorn) on node master-b99de-1 is ready
Reason:
Status: True
Type: Ready
Last Probe Time:
Last Transition Time: 2023-06-01T10:57:30Z
Message: the disk default-disk-7e31d863af7d38e7(/xos-storage/longhorn) on the node master-b99de-1 has 15309209600 available, but requires reserved 22033659494, minimal 10% to schedule more replicas
Reason: DiskPressure
Status: False
Type: Schedulable
Disk UUID: d5f53ea5-4329-433d-8f17-e4c8751f66a5
Scheduled Replica:
pvc-3ecd481a-5db4-4648-976b-57853566720f-r-3ceb0a70: 107374182400
pvc-629a85b9-3063-4006-9303-f95b9fe05ffa-r-4d243b68: 107374182400
pvc-a6b4e385-bcc8-4c79-a815-103df854e211-r-4165488d: 107374182400
Storage Available: 15309209600
Storage Maximum: 73445531648
Storage Scheduled: 322122547200
Region:
Snapshot Check Status:
Zone:
Events: <none>

# kubectl get lhn -n longhorn-system master-b99de-1 -o yaml
apiVersion: [longhorn.io/v1beta2](http://longhorn.io/v1beta2)
kind: Node
metadata:
creationTimestamp: "2023-06-01T10:57:03Z"
finalizers:
- [longhorn.io](http://longhorn.io/)
generation: 1
name: master-b99de-1
namespace: longhorn-system
resourceVersion: "10734984"
uid: ec9409db-f590-49eb-a1cb-a0102b1d7d0d
spec:
allowScheduling: true
disks:
default-disk-7e31d863af7d38e7:
allowScheduling: true
evictionRequested: false
path: /xos-storage/longhorn
storageReserved: 22033659494
tags: []
engineManagerCPURequest: 0
evictionRequested: false
name: master-b99de-1
replicaManagerCPURequest: 0
tags: []
status:
conditions:
- lastProbeTime: ""
lastTransitionTime: "2023-06-01T11:05:46Z"
message: 'Kubernetes node master-b99de-1 has pressure: KubeletHasDiskPressure,
kubelet has disk pressure'
reason: KubernetesNodePressure
status: "False"
type: Ready
- lastProbeTime: ""
lastTransitionTime: "2023-06-01T10:57:03Z"
message: ""
reason: ""
status: "True"
type: Schedulable
- lastProbeTime: ""
lastTransitionTime: "2023-06-01T10:57:02Z"
message: ""
reason: ""
status: "True"
type: MountPropagation
diskStatus:
default-disk-7e31d863af7d38e7:
conditions:
- lastProbeTime: ""
lastTransitionTime: "2023-06-01T10:57:02Z"
message: Disk default-disk-7e31d863af7d38e7(/xos-storage/longhorn) on node
master-b99de-1 is ready
reason: ""
status: "True"
type: Ready
- lastProbeTime: ""
lastTransitionTime: "2023-06-01T10:57:30Z"
message: the disk default-disk-7e31d863af7d38e7(/xos-storage/longhorn) on
the node master-b99de-1 has 15309209600 available, but requires reserved
22033659494, minimal 10% to schedule more replicas
reason: DiskPressure
status: "False"
type: Schedulable
diskUUID: d5f53ea5-4329-433d-8f17-e4c8751f66a5
scheduledReplica:
pvc-3ecd481a-5db4-4648-976b-57853566720f-r-3ceb0a70: 107374182400
pvc-629a85b9-3063-4006-9303-f95b9fe05ffa-r-4d243b68: 107374182400
pvc-a6b4e385-bcc8-4c79-a815-103df854e211-r-4165488d: 107374182400
storageAvailable: 15309209600
storageMaximum: 73445531648
storageScheduled: 322122547200
region: ""
snapshotCheckStatus: {}
zone: ""

**Comment by ejweber** [comment]
Hello @shaolila. Longhorn is reporting that the `master-b99de-1` is under disk pressure.

```
Last Probe Time:
Last Transition Time: 2023-06-01T11:05:46Z
Message: Kubernetes node master-b99de-1 has pressure: KubeletHasDiskPressure, kubelet has disk pressure
Reason: KubernetesNodePressure
Status: False
Type: Ready
```

Longhorn is only re-reporting this information to you and acting on it. The source of truth for this condition is the Kubernetes node object itself (e.g. `kubectl describe node`). Longhorn will refuse to schedule replicas to this node, regardless of the status of individual disks, until the condition is resolved. The concern with this (and other pressure conditions) is that the kubelet will start to evict Longhorn (or workload) pods, causing unstable system behavior.

We are also reporting that the default disk is very nearly full.

```
Message: the disk default-disk-7e31d863af7d38e7(/xos-storage/longhorn) on the node master-b99de-1 has 15309209600 available, but requires reserved 22033659494, minimal 10% to schedule more replicas
```

This is a related message, though technically the kubelet itself reporting the first one and Longhorn has discovered the second one on its own.

If you want to use multiple disks with Longhorn, you must add the additional disks to Longhorn by following these instructions: https://longhorn.io/docs/1.4.2/volumes-and-nodes/multidisk/.

**Comment by ejweber** [comment]
Can you confirm whether it is Longhorn or another actor that is using up the space on your default disk? For example, look for `Actual Size` in the UI or `volume.status.actualSize` with `kubectl`. If the Longhorn volumes themselves are not taking up much space, you will have to look at what is. If they are, you may need to add the additional disks as mentioned above and then evict one or more replicas so that it is rescheduled.

**Comment by shaolila** [comment]
now lhn is:
  Disks:
    default-disk-7e31d863af7d38e7:
    Allow Scheduling: true
    Eviction Requested: false
    Path: /xos-storage/longhorn
    Storage Reserved: 22033659494
    Tags:
I expect is:
 Disks:
    default-disk-7e31d863af7d38e7:
      Allow Scheduling: true
      Eviction Requested: false
      Path: /xos-storage/longhorn
      Storage Reserved: 22033659494
      Tags:
    disk-3:
      Allow Scheduling: true
      Eviction Requested: false
      Path: /xos-disk
      Storage Reserved: 22033659494
      Tags:
    disk-4:
      Allow Scheduling: true
      Eviction Requested: false
      Path: /xos-disk2
      Storage Reserved: 22033659494
      Tags:
   disk-5:
      Allow Scheduling: true
      Eviction Requested: false
      Path: /xos-disk3
      Storage Reserved: 22033659494
      Tags:

**Comment by ejweber** [comment]
Have you followed the instructions outlined in https://longhorn.io/docs/1.4.2/volumes-and-nodes/multidisk/? If not, you must manually add the extra disks to Longhorn, generally using the UI.
