### ISSUE TITLE
[BUG] In some specific situation, system backup auto deleted when creating another one

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#6045]
## Describe the bug (🐛 if you encounter this issue)

This is a corner case

While testing system backup `volumeBackupPolicy`, encountered a strange behavior :  after performing some specific operations, a system backup will be deleted if volume backup not appear in backup store. Create this ticket for tracking.

## To Reproduce

1. Create 2 system backup `sys-back`, `sys-back2` with `volumeBackupPolicy` = always
2. Wait system backup creation complete
3. Delete volume backups in backup store
4. Delete `sys-back` and recreate again
5. After `sys-back` complete, `sys-back2` deleted automatically. 

## Expected behavior

System backup should not be deleted when creating a new 1 

## Log or Support bundle

[supportbundle_4b0bd336-cbd1-4239-bce6-627b23e1c9b2_2023-06-02T03-51-36Z.zip](https://github.com/longhorn/longhorn/files/11631716/supportbundle_4b0bd336-cbd1-4239-bce6-627b23e1c9b2_2023-06-02T03-51-36Z.zip)

## Environment

 - Longhorn version: longhorn-manager `663185`

## Additional context

https://github.com/longhorn/longhorn/issues/5011
Can not reporduce if system backup name does not contain `-`

**Comment by c3y1huang** [comment]
It appears that the issue is caused by the bulk deletion of objects with [prefix](https://github.com/longhorn/backupstore/blob/master/s3/s3_service.go#L167).
ref: https://github.com/longhorn/backupstore/pull/41

**Comment by c3y1huang** [comment]
It appears that the issue is caused by the bulk deletion of objects with [prefix](https://github.com/longhorn/backupstore/blob/master/s3/s3_service.go#L167).

**Comment by chriscchien** [comment]
Verified **pass** in longhorn master (longhorn-engine `a98afe`, backupstore `4cf315`)

The symptom in [description](https://github.com/longhorn/longhorn/issues/6045#issue-1737436536) can not reproduce in master head, in addition, all 3 types of `volumeBackupPolicy` worked properly as well.

**Comment by chriscchien** [comment]
Hi @innobead, I just find that this ticket not backport to v1.5.x and not sure if this is necessary, thank you.

**Comment by innobead** [comment]
@chriscchien it has been backported to 1.5.0, https://github.com/longhorn/longhorn-engine/pull/908.

**Comment by chriscchien** [comment]
Update:

**Comment by innobead** [comment]
Thanks @chriscchien this is good.

**Comment by innobead** [comment]
It's good. @c3y1huang also added the e2e test cases.
