### ISSUE TITLE
Required settings are not validated in longhorn-manager

### ISSUE THREAD

**Issue by ttpcodes** [longhorn/longhorn#605]
I was able to reproduce this issue on both `v0.5.0` and `master`.

Even though `longhorn-ui` will warn you that a required `Setting` has been left empty, if you still go through and submit the `Setting` form, the `longhorn-manager` will not validate that these `Settings` have been filled, and still attempt to save the `Setting` value on the back-end. 

For some `Settings`, this doesn't break anything, since the back-end attempts to do things such as cast the new value to an `int`, and the validation is able to fail there instead. Others, however, such as `storage-minimal-available-percentage`, aren't validated and will gladly take the empty value, which in this case completely breaks the logic that syncs `Node` status.

This applies to non-required `Settings` as well. Instead of defaulting to the default value of the `Setting`, the `Setting` will be read and return the empty value.

**Comment by meldafrawi** [comment]
Longhorn manager now returns status code: 500 in case of empty value.
