### ISSUE TITLE
Using Azure AKS PVCs(Existing PVCs) with Longhorn for Migration

### ISSUE THREAD

**Issue by zohebk8s** [longhorn/longhorn#6059]
Azure AKS 1.23 version.

We are having MongoDB, RabbitMQ, and a few other stateful sets with data in PVC.

Use-Case is Migrating AKS PVCs from One AKS CLuster to another AKS Cluster which is in a different region.

We have used Azure Storage Class for PVCs. Now we want to migrate our application+data by using Longhorn.

In this case, how I can make use of Longhorn? Will it support this case or is there a way? Why because in order for Longhorn to create a backup, PVCs should be created by using Longhorn CSI/Storage.

**Comment by PhanLe1010** [comment]
I am thinking about this plan:
1. First install Longhorn in the source cluster. Create PVCs using Longhorn storageclass and copy data from Azure Storage Class PVCs to the new PVCs (See example at https://github.com/longhorn/longhorn/blob/master/examples/data_migration.yaml)
2. Adjust the workload statefulset and deployment to use Longhorn PVCs
3. Now that the source cluster used Longhorn PVCs, you can setup backup target to backup Longhorn system of the source cluster. See https://longhorn.io/docs/1.4.2/advanced-resources/system-backup-restore/
4. In the new cluster, install Longhorn and do a system restore form the previous backup
5. Longhorn doesn't handle workload statefulset/deployment migration so you will have to use other tools such as velero

**Comment by zohebk8s** [comment]
> > From longhorn UI, we can create disaster recovery, activate it and create PVCs out of it
> > Then use this PVCs/PV in destination statefulsets like MongoDB/Kafka etc.
> 
> I think this is the story of disaster recovery provided by Longhorn. Please try to evaluate it and we would like to hear more about your feedback and experience.
"My Use-Case is:

Current MongoDB/Kafka/Logstash are running in Azure AKS with lots of data in PVC. Now I am looking to migrate/replicate the data from the west-Europe cluster to a new north-europe AKS cluster.

I am trying to acheive this with no downtime or minimal downtime with exact replica of data"

**Comment by PhanLe1010** [comment]
I see your point. Yeah, looks like it requires downtime when executing this migration plan https://github.com/longhorn/longhorn/issues/6059#issuecomment-1580640943

**Comment by PhanLe1010** [comment]
An other idea from @innobead is to check if your MongoDB/Kafka/Logstash have backup capability. If yes, maybe you can back them up from the source cluster, then install MongoDB/Kafka/Logstash (with Longhorn PVC) on the new cluster and store the backup of these applications?
