### ISSUE TITLE
Backup deletion may timeout

### ISSUE THREAD

**Issue by ywei88** [longhorn/longhorn#606]
When I was deleting a 7G backup for a volume on longhornUI, which was the only backup for that volume, it sometimes encountered timeout error. The error message was like this :

> error deleting backup backup-783c0eba462d4e55 of volume pvc-47a5d92b-984f-11e9-8f17-0eddc8954679: error deleting backup: Timeout executing: /var/lib/rancher/longhorn/engine-binaries/myusername-longhorn-engine-c52956d/longhorn [backup rm nfs://longhorn-test-nfs-svc.default:/opt/backupstore?backup=backup-783c0eba462d4e55&volume=pvc-47a5d92b-984f-11e9-8f17-0eddc8954679], output , stderr, , error <nil>

This interrupted the backup deletion process and cause data leftover in blocks, and the volume was still in the backup list with no backup behind it ( #597 ), also there was no option to delete that volume in the backup list on longhornUI as #598 mentioned.

**Comment by yasker** [comment]
We cannot use a timeout to determine if the deletion completed or not. We need to implement something similar to #49 and #45 and timeout based on the progress movement. If there is no progress at all (no timestamp change) for a certain period of time, we can say it's timed out.

**Comment by yasker** [comment]
Done
