### ISSUE TITLE
[IMPROVEMENT] Add test for longhorn-spdk-engine

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6060]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Implement integration test in longhorn-spdk-engine as longhorn-engine.

**Comment by shuo-wu** [comment]
For the repo `longhorn-spdk-engine` test, I tried lots of methods last week but finally had to put the unit test file under dir `pkg`. The test involves both the server part (pkg `spdk`) and the client part (pkg `client`). But for the Golang test framework, it seems there is no way/it’s better not to use other pkgs in one unit test file. 

On the other hand, launching (python) integration tests is too trivial. Before adding integration tests in this repo, we have to write a cmd for gRPC server launching, build the binary, set up python test env, generate python gRPC files, and so on. Besides, it may be overlapped with the instance manager test.

Hence, I plan to directly put the test file under `[pkg`](https://github.com/longhorn/longhorn-spdk-engine/tree/main/pkg), which is the parent dir of pkg `spdk` and pkg `client`.

**Comment by shuo-wu** [comment]
Notice that I implement unit tests rather than integration tests in https://github.com/longhorn/longhorn-spdk-engine/pull/54
