### ISSUE TITLE
[FEATURE] Replica offline rebuild over SPDK

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#6067]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Due to some SPDK API missing in Longhorn v1.5.0 release, we will launch the offline rebuild feature first.

## Describe the solution you'd like

When a degraded SPDK volume is attached with frontend disabled, Longhorn can do offline rebuild for the volume

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by innobead** [comment]
Let use https://github.com/longhorn/longhorn/issues/6071 to test instead. Closing first.
