### ISSUE TITLE
mapping values are not allowed in this context

### ISSUE THREAD

**Issue by zainul1114** [longhorn/longhorn#6073]
Hi All,
I am getting below error, need your help to resolve this issue.

K8s version : 1.22.3,  OS:RHEL7.9 
[root@kubem Longhorn]#
[root@kubem Longhorn]# kubectl apply -f https://github.com/longhorn/longhorn/blob/master/deploy/prerequisite/longhorn-iscsi-installation.yaml
error: error parsing https://github.com/longhorn/longhorn/blob/master/deploy/prerequisite/longhorn-iscsi-installation.yaml: error converting YAML to JSON: yaml: line 28: mapping values are not allowed in this context

[root@kubem Longhorn]# kubectl apply -f https://github.com/longhorn/longhorn/blob/master/deploy/prerequisite/longhorn-nfs-installation.yaml
error: error parsing https://github.com/longhorn/longhorn/blob/master/deploy/prerequisite/longhorn-nfs-installation.yaml: error converting YAML to JSON: yaml: line 28: mapping values are not allowed in this context
[root@kubem Longhorn]#

[root@kubem Longhorn]# curl -sSfL https://github.com/longhorn/longhorn/blob/v1.4.2/scripts/environment_check.sh | bash
bash: line 8: syntax error near unexpected token `newline'
bash: line 8: `<!DOCTYPE html>'
curl: (23) Failed writing body (1348 != 1370)
[root@kubem Longhorn]#

**Comment by PhanLe1010** [comment]
You should use the raw yaml instead.

For example, use this one `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/prerequisite/longhorn-iscsi-installation.yaml` instead of `https://github.com/longhorn/longhorn/blob/master/deploy/prerequisite/longhorn-iscsi-installation.yaml`

The later on has a bunch of HTML stuff in it when fetching

**Comment by zainul1114** [comment]
Thanks PhanLe, Its works!
# kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/prerequisite/longhorn-iscsi-installation.yaml
daemonset.apps/longhorn-iscsi-installation created
