### ISSUE TITLE
[TASK] Investigate SELinux enabled with Longhorn

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#6074]
This was originally #5627, but I took it over to help handle a specific SELinux issue users were seeing in Rocky 9. Creating this new duplicate to track the original work. To me, it seems like the most important thing to do (given https://github.com/longhorn/longhorn/issues/5627#issuecomment-1506068279) is ensure we are running a test bed RHEL/CentOS/Fedora/Rocky test bed with the latest patches, as the issue now handled by #5627 came to a head when users updated `container-selinux` as part of an RKE2 install.

Original issue description:

> IIRC, Fedora CoreOS, centos stream and fedora enable SELinux by default and are popular OSes. Although we have a KB for OKD (https://longhorn.io/kb/troubleshooting-volumes-stuck-in-attach-detach-loop-when-using-longhorn-on-okd/), it is worth investigating and figuring out a solution for SELinux enabled env.

cc @innobead @ChanYiLin @longhorn/qa 

_Originally posted by @derekbit in https://github.com/longhorn/longhorn/discussions/5367#discussioncomment-5377112_

**Comment by SaimonWoidig** [comment]
Encountered the same issue on Rocky 8. When I applied the workaround from the mentioned issue (https://github.com/longhorn/longhorn/issues/5627#issuecomment-1605876257), everything started working.

**Comment by innobead** [comment]
@ejweber @yangchiu has done https://github.com/longhorn/longhorn/issues/6168. Is there anything we still need?

**Comment by ejweber** [comment]
@innobead, I think that is up to @longhorn/qa process at this point. From the dev standpoint, with the workaround, I don't know of any outstanding SELinux issues. However, as I mentioned in [my comment](https://github.com/longhorn/longhorn/issues/6074#issue-1744421933), https://github.com/longhorn/longhorn/issues/5627 was discovered in the wild by users doing regular security patches on their OS distributions. In order to be confident, we need to do our best to ensure:

1. We are regularly testing the latest minor versions of supported distributions.
2. We are applying the latest patches within these minor versions.
3. We are testing with SELinux relatively frequently.

I think we generally do 2 in our terraform scripts already. But I'm not sure about 1 and 3. If @longhorn/qa feels that we are already doing as much as is practical, then lets close this issue out.

**Comment by ejweber** [comment]
I'm not sure what the original issue was in #5348 (could never reproduce), but one of the users updated with more recent symptoms. I have traced them to some upstream problem with either `k3s-selinux` or `container-selinux`. While working on that one, I wrote a KB that will hopefully serve as a good product to close out this issue with.
