### ISSUE TITLE
[IMPROVEMENT] Reduce replica process's number of allocated ports 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6079]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

A replica process allocates 15 ports ([codes](https://github.com/longhorn/longhorn-manager/blob/v1.5.x/engineapi/instance_manager.go#L32)). However, Longhorn doesn't utilize all of these ports even during the replica rebuilding process. Therefore, we can decrease the number of port numbers to 10 or lower.

**Comment by innobead** [comment]
@ChanYiLin Please help verify this. Thanks.

**Comment by ChanYiLin** [comment]
**Verified on longhorn master-head 20230612**

- longhorn master-head [34c07f](https://github.com/longhorn/longhorn/commit/34c07f3e5ce89745b1cd092870df8777ec3b416d)

follow the test [steps](https://github.com/longhorn/longhorn/issues/6079#issuecomment-1581865929)

**Result**
The port range for replica is 10003 - 100012 (which is 10 ports)
