### ISSUE TITLE
Pod Security Policy Should be used instead of privileged

### ISSUE THREAD

**Issue by maaztariq** [longhorn/longhorn#608]
Our cluster does not allow privilege mode, we should be able to run using POD Security policy with right permission instead of privilege = true https://github.com/longhorn/longhorn/blob/master/chart/templates/daemonset-sa.yaml#L22

**Comment by yasker** [comment]
Thanks for the reporting @maaztariq 

Internally Longhorn also deploys a few containers so we would need to look into PSP to find out what would be requirements and ways to address those issues.

**Comment by janeczku** [comment]
The Longhorn Helm Chart should install the correct PSP granting required privileges.

**Comment by janeczku** [comment]
Judging by the official Helm repo, it appears standard practice to include a custom PSP  when an application requires privileged pods: https://github.com/helm/charts/search?q=podsecuritypolicy&unscoped_q=podsecuritypolicy

**Comment by yasker** [comment]
We've shipped PSP with deployment since 1.0.2.

**Comment by yasker** [comment]
Close the issue since we've added PSP to Longhorn.
