### ISSUE TITLE
[TEST] Use different Rocky Linux AMI

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#6088]
## What's the test to develop? Please describe

The Rocky Linux AMI we use for testing does not have the latest versions and doesn't have ARM images. Use the official image instead.

**Comment by innobead** [comment]
@ejweber is this finished? It seems all PRs have been merged. If all good, let's close it directly. 

cc @longhorn/qa

**Comment by ejweber** [comment]
https://github.com/longhorn/longhorn-tests/pull/1426

**Comment by ejweber** [comment]
@innobead and @longhorn/qa:

We still need https://github.com/longhorn/longhorn-tests/pull/1426 to ensure Rocky testing with SELinux enabled works correctly. Since the issue that owned it was closed, I've tagged it here. We should close this directly as requested as soon as that one merged.

- [ ] https://github.com/longhorn/longhorn-tests/pull/1426
