### ISSUE TITLE
[Question] longhorn-conversion-webhook container not starting error, failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: eaccess /usr/local/sbin/longhorn-manager: permission denied: unknown

### ISSUE THREAD

**Issue by atul-devopswarriors** [longhorn/longhorn#6090]
**Question:**

I am open this as Question, because this is my first  Longhorn storage installation on Kubernetes cluster (Multi Master HA setup), Feels like issue with some container permission while accessing /usr/local/sbin/longhorn-manager while provisioning container.
after applying the longhorn.yaml version v1.3.2, non of pods are getting started throwing error "CrashLoopBackOff" for longhorn-manager and convention-webhook pods. Looking at Kubernetes pod logs, in longhorn-conventional-webhook container its showing with the message: " unable to start container process: eaccess /usr/local/sbin/longhorn-manager: permission denied: unknown"

What more can I look at to diagnose this issue? Is my volume configured incorrectly somehow? Did I miss a setup step somewhere?

Environment Setup
Longhorn version: v1.3.2
Kubernetes version: v1.24.0
Node config
OS type and version: Rhel 8
CPU per node: 4
Memory per node: 8gb & 16gb
Disk type: XFS
Network bandwidth and latency between the nodes: I don't have numbers, but they are all running on the same physical server
Underlying Infrastructure (e.g VMWare/KVM, Baremetal): KVM

**Additional context**
My basic setup is that I have multiple K8s nodes running inside KVM virtual machines provisioned with libvirt. The K8S nodes are running rhel8. I have ensured that nfs-common and open-iscsi are both installed. Everything is running the latest version give or take a week. Each K8S VM has a 300gb XFS volume mounted at /var/lib/longhorn.

**Comment by derekbit** [comment]
@atul-devopswarriors 
Could you please update the ticket with the below format and provide more information? Thank you.
```
## Describe the bug (🐛 if you encounter this issue)

A clear and concise description of what the bug is.

## To Reproduce

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Perform '....'
4. See error

## Expected behavior

A clear and concise description of what you expected to happen.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

Add any other context about the problem here.
```

**Comment by atul-devopswarriors** [comment]
> @atul-devopswarriors Could you please update the ticket with the below format and provide more information? Thank you.
> 
> ```
> ## Describe the bug (🐛 if you encounter this issue)
> 
> A clear and concise description of what the bug is.
> 
> ## To Reproduce
> 
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Perform '....'
> 4. See error
> 
> ## Expected behavior
> 
> A clear and concise description of what you expected to happen.
> 
> ## Log or Support bundle
> 
> If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
> You can generate a Support Bundle using the link at the footer of the Longhorn UI.
> 
> ## Environment
> 
>  - Longhorn version:
>  - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
>  - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
>    - Number of management node in the cluster:
>    - Number of worker node in the cluster:
>  - Node config
>    - OS type and version:
>    - CPU per node:
>    - Memory per node:
>    - Disk type(e.g. SSD/NVMe):
>    - Network bandwidth between the nodes:
>  - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
>  - Number of Longhorn volumes in the cluster:
> 
> ## Additional context
> 
> Add any other context about the problem here.
> ```

done

**Comment by PhanLe1010** [comment]
Do you have the logs from other pods (longhorn-manager, longhorn-driver-deployer, longhorn-ui). Do they share the same crashing error message above?

**Comment by PhanLe1010** [comment]
I am thinking if this error is related to Longhorn PSP not being enabled causing the problem in your cluster. 
By default, in Longhorn v1.3.2 we don't ship [Longhorn PSP](https://github.com/longhorn/longhorn/blob/master/deploy/podsecuritypolicy.yaml). If your cluster requires this to work, you will need to deploy it. 

Could you provide the output of `kubectl get psp` ?

**Comment by PhanLe1010** [comment]
Could also provide some audit logs to see if there is any issue with SELinux?
```
ausearch -m AVC -ts recent
```

**Comment by atul-devopswarriors** [comment]
> Do you have the logs from other pods (longhorn-manager, longhorn-driver-deployer, longhorn-ui). Do they share the same crashing error message above?

I am not able to fetch the long of any longhorn pod because non of pods are active or running state, However i can share describe logs.

**Comment by atul-devopswarriors** [comment]
**Please find "longhorn-conversion-webhook" pods log below.**

**Longhorn-conversion-webhook:**

`kubernetes_workspace xxxx$ kubectl describe pod longhorn-conversion-webhook-54468f8f48-2v8fx  -n longhorn-system
Name:         longhorn-conversion-webhook-54468f8f48-2v8fx
Namespace:    longhorn-system
Priority:     0
Node:         test1/xxx.xxx.xxx.xxx
Start Time:   Wed, 14 Jun 2023 16:28:46 +0400
Labels:       app=longhorn-conversion-webhook
              app.kubernetes.io/instance=longhorn
              app.kubernetes.io/name=longhorn
              app.kubernetes.io/version=v1.3.2
              pod-template-hash=54468f8f48
Annotations:  <none>
Status:       Running
IP:           xx.xxx.xx.xx
IPs:
  IP:           xx.xxx.xx.xx
Controlled By:  ReplicaSet/longhorn-conversion-webhook-54468f8f48
Containers:
  longhorn-conversion-webhook:
    Container ID:  containerd://bda34357b757bc08cb40c21bfe42fb4f0123d62ec32ede78d269bcaa2b98338d
    Image:         longhornio/longhorn-manager:v1.3.2
    Image ID:      longhorn-manager@sha256:c1bf0d7e8495b453b4e2f88e8f29d2ebf509a73989b7ab53b08e3cf8f35648cf
    Port:          9443/TCP
    Host Port:     0/TCP
    Command:
      longhorn-manager
      conversion-webhook
      --service-account
      longhorn-service-account
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: eaccess /usr/local/sbin/longhorn-manager: permission denied: unknown
      Exit Code:    128
      Started:      Thu, 01 Jan 1970 04:00:00 +0400
      Finished:     Wed, 14 Jun 2023 16:31:55 +0400
    Ready:          False
    Restart Count:  5
    Readiness:      tcp-socket :9443 delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAMESPACE:  longhorn-system (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-dx49p (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-dx49p:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  3m51s                   default-scheduler  Successfully assigned longhorn-system/longhorn-conversion-webhook-54468f8f48-2v8fx to t1-prm-wrk1
  Warning  BackOff    2m24s (x10 over 3m49s)  kubelet            Back-off restarting failed container
  Normal   Pulled     2m10s (x5 over 3m51s)   kubelet            Container image "longhornio/longhorn-manager:v1.3.2" already present on machine
  Normal   Created    2m10s (x5 over 3m51s)   kubelet            Created container longhorn-conversion-webhook
  Warning  Failed     2m9s (x5 over 3m50s)    kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: eaccess /usr/local/sbin/longhorn-manager: permission denied: unknown`

Longhorn-Manager Pod Logs.

`AEB-M1L0AHJGH5:kubernetes_workspace satu6780$ kubectl describe pod longhorn-manager-v7p8m  -n longhorn-system
Name:         longhorn-manager-v7p8m
Namespace:    longhorn-system
Priority:     0
Node:         /xx.xx.xx.xx
Start Time:   Wed, 14 Jun 2023 16:28:46 +0400
Labels:       app=longhorn-manager
              app.kubernetes.io/instance=longhorn
              app.kubernetes.io/name=longhorn
              app.kubernetes.io/version=v1.3.2
              controller-revision-hash=589bb776d7
              pod-template-generation=1
Annotations:  <none>
Status:       Pending
IP:           xx.xx.xx.xx
IPs:
  IP:          xx.xx.xx.xx
Controlled By:  DaemonSet/longhorn-manager
Init Containers:
  wait-longhorn-admission-webhook:
    Container ID:  containerd://bd93a5723ba5966c278d9f0de38b279f86bb9a44407b1e65ffa76c185f496d80
    Image:         longhornio/longhorn-manager:v1.3.2
    Image ID:      longhorn-manager@sha256:c1bf0d7e8495b453b4e2f88e8f29d2ebf509a73989b7ab53b08e3cf8f35648cf
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" -k https://longhorn-admission-webhook:9443/v1/healthz) != "200" ]; do echo waiting; sleep 2; done
    State:          Running
      Started:      Wed, 14 Jun 2023 16:28:46 +0400
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zn2q2 (ro)
Containers:
  longhorn-manager:
    Container ID:  
    Image:         longhornio/longhorn-manager:v1.3.2
    Image ID:      
    Port:          9500/TCP
    Host Port:     0/TCP
    Command:
      longhorn-manager
      -d
      daemon
      --engine-image
      longhornio/longhorn-engine:v1.3.2
      --instance-manager-image
      longhornio/longhorn-instance-manager:v1_20221003
      --share-manager-image
      longhornio/longhorn-share-manager:v1_20221003
      --backing-image-manager-image
      longhornio/backing-image-manager:v3_20221003
      --manager-image
      longhornio/longhorn-manager:v1.3.2
      --service-account
      longhorn-service-account
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Readiness:      tcp-socket :9500 delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAMESPACE:  longhorn-system (v1:metadata.namespace)
      POD_IP:          (v1:status.podIP)
      NODE_NAME:       (v1:spec.nodeName)
    Mounts:
      /host/dev/ from dev (rw)
      /host/proc/ from proc (rw)
      /tls-files/ from longhorn-grpc-tls (rw)
      /var/lib/longhorn/ from longhorn (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zn2q2 (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/
    HostPathType:  
  proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc/
    HostPathType:  
  longhorn:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/longhorn/
    HostPathType:  
  longhorn-grpc-tls:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  longhorn-grpc-tls
    Optional:    true
  kube-api-access-zn2q2:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  10m   default-scheduler  Successfully assigned longhorn-system/longhorn-manager-v7p8m to 
  Normal  Pulled     10m   kubelet            Container image "longhornio/longhorn-manager:v1.3.2" already present on machine
  Normal  Created    10m   kubelet            Created container wait-longhorn-admission-webhook
  Normal  Started    10m   kubelet            Started container wait-longhorn-admission-webhook`


Longhorn-Ui:

`AEB-M1L0AHJGH5:kubernetes_workspace satu6780$ kubectl describe pod longhorn-ui-85cc9fc45-pfl4q   -n longhorn-system
Name:         longhorn-ui-85cc9fc45-pfl4q
Namespace:    longhorn-system
Priority:     0
Node:         test2/xx.xx.xx.xx
Start Time:   Wed, 14 Jun 2023 16:28:46 +0400
Labels:       app=longhorn-ui
              app.kubernetes.io/instance=longhorn
              app.kubernetes.io/name=longhorn
              app.kubernetes.io/version=v1.3.2
              pod-template-hash=85cc9fc45
Annotations:  <none>
Status:       Running
IP:           xx.xx.xx.xx
IPs:
  IP:           xx.xx.xx.xx
Controlled By:  ReplicaSet/longhorn-ui-85cc9fc45
Containers:
  longhorn-ui:
    Container ID:   containerd://2c52446b83465687e5df2e85a4a10556fb3d4a81bb7ccb5dd3c0e5961dc803f0
    Image:          longhornio/longhorn-ui:v1.3.2
    Image ID:       longhornio/longhorn-ui@sha256:df514cefa7ed9c9da83703a789a340ea9775e96fc5f6e5f381ba31c650f6a103
    Port:           8000/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 14 Jun 2023 16:42:14 +0400
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 14 Jun 2023 16:36:43 +0400
      Finished:     Wed, 14 Jun 2023 16:37:03 +0400
    Ready:          True
    Restart Count:  7
    Environment:
      LONGHORN_MANAGER_IP:  http://longhorn-backend:9500
      LONGHORN_UI_PORT:     8000
    Mounts:
      /var/cache/nginx/ from nginx-cache (rw)
      /var/config/nginx/ from nginx-config (rw)
      /var/run/ from var-run (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-pzjds (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  nginx-cache:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  nginx-config:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  var-run:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kube-api-access-pzjds:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  13m                   default-scheduler  Successfully assigned longhorn-system/longhorn-ui-85cc9fc45-pfl4q to test2
  Normal   Pulled     10m (x5 over 13m)     kubelet            Container image "longhornio/longhorn-ui:v1.3.2" already present on machine
  Normal   Created    10m (x5 over 13m)     kubelet            Created container longhorn-ui
  Normal   Started    10m (x5 over 13m)     kubelet            Started container longhorn-ui
  Warning  BackOff    3m34s (x36 over 12m)  kubelet            Back-off restarting failed container`

**Comment by atul-devopswarriors** [comment]
> ausearch -m AVC -ts recent

Please check the below output from above command

` ausearch -m AVC -ts recent
<no matches>
`

**Comment by atul-devopswarriors** [comment]
> kubectl get psp
```
$ kubectl get psp
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME           PRIV   CAPS        SELINUX    RUNASUSER   FSGROUP    SUPGROUP   READONLYROOTFS   VOLUMES
longhorn-psp   true   SYS_ADMIN   RunAsAny   RunAsAny    RunAsAny   RunAsAny   false            configMap,downwardAPI,emptyDir,secret,projected,hostPath
```

**Comment by PhanLe1010** [comment]
Thanks @atul-devopswarriors !

The PSP looks good.

For audit logs, did you run `ausearch -m AVC -ts recent` on the node `t1-prm-wrk1` yet?

**Comment by atul-devopswarriors** [comment]
> Thanks @atul-devopswarriors !
> 
> The PSP looks good.
> 
> For audit logs, did you run `ausearch -m AVC -ts recent` on the node `t1-prm-wrk1` yet?

yeah its same in all worker node's
<no matches>

**Comment by atul-devopswarriors** [comment]
I have resolve the issue somehow after modifying following deployment configuration for longhorn-conventional-webhook
added permission to /usr/local/sbin/longhorn-system, After added below command it resolve the permission issue, However now i am facing connection refused issue on  **longhorn-conventional-webhook** container describe command, Apart from that i also see some DNS resolution failure to resolve the hostname while checking the side car container or init container health check, because  feels like from the coreDns pods logs.

containers:
      - name: longhorn-conversion-webhook
        image: t1-registry.kinfra.uae/katim2.0/longhornio/longhorn-manager:v1.3.2
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
        command:
        - '/bin/sh'
        - '-c'
        - 'chmod 0755 -R /usr/local/sbin/longhorn-manager'
        - longhorn-manager
        - conversion-webhook
        - --service-account
        - longhorn-service-account
        ports:
        - containerPort: 9443
          name: conversion-wh
        readinessProbe:
          tcpSocket:
            port: 9443
          initialDelaySeconds: 20
          timeoutSeconds: 250
          successThreshold: 5
          periodSeconds: 10
`
**Current Cluster Pods State:**
`
$ kubectl get pod -A
NAMESPACE         NAME                                           READY   STATUS             RESTARTS        AGE
kube-flannel      kube-flannel-ds-68mmt                          1/1     Running            0               9d
kube-flannel      kube-flannel-ds-79gpq                          1/1     Running            4 (44h ago)     9d
kube-flannel      kube-flannel-ds-d99rn                          1/1     Running            4 (44h ago)     9d
kube-flannel      kube-flannel-ds-frpkb                          1/1     Running            4 (44h ago)     9d
kube-flannel      kube-flannel-ds-lhhct                          1/1     Running            0               9d
kube-flannel      kube-flannel-ds-npbl8                          1/1     Running            4 (44h ago)     9d
kube-flannel      kube-flannel-ds-ssgnj                          1/1     Running            4 (44h ago)     9d
kube-flannel      kube-flannel-ds-tfw8x                          1/1     Running            0               9d
kube-flannel      kube-flannel-ds-zw7sw                          1/1     Running            4 (44h ago)     9d
kube-system       coredns-7f5676599b-6th5q                       1/1     Running            0               10h
kube-system       coredns-7f5676599b-f8xjh                       1/1     Running            0               10h
kube-system       etcd-1                                         1/1     Running            33              9d
kube-system       etcd-2                                         1/1     Running            4               9d
kube-system       etcd-3                                         1/1     Running            4               9d
kube-system       kube-apiserver-1                               1/1     Running            0               9d
kube-system       kube-apiserver-2                               1/1     Running            1 (9d ago)      9d
kube-system       kube-apiserver-3                               1/1     Running            0               9d
kube-system       kube-controller-manager-1                      1/1     Running            0               9d
kube-system       kube-controller-manager-2                      1/1     Running            0               9d
kube-system       kube-controller-manager-3                      1/1     Running            0               9d
kube-system       kube-proxy-54hlc                               1/1     Running            4 (44h ago)     9d
kube-system       kube-proxy-bl6td                               1/1     Running            4 (44h ago)     9d
kube-system       kube-proxy-ksnmd                               1/1     Running            4 (44h ago)     9d
kube-system       kube-proxy-lp4sf                               1/1     Running            0               9d
kube-system       kube-proxy-pnhms                               1/1     Running            4 (44h ago)     9d
kube-system       kube-proxy-q796f                               1/1     Running            4 (44h ago)     9d
kube-system       kube-proxy-r2gs4                               1/1     Running            4 (44h ago)     9d
kube-system       kube-proxy-s4d9z                               1/1     Running            0               9d
kube-system       kube-proxy-tt8jv                               1/1     Running            0               9d
kube-system       kube-scheduler-1                               1/1     Running            34              9d
kube-system       kube-scheduler-2                               1/1     Running            5               9d
kube-system       kube-scheduler-3                               1/1     Running            5               9d
longhorn-system   longhorn-admission-webhook-6b756f4597-22xtj    0/1     Init:0/1           0               5m55s
longhorn-system   longhorn-admission-webhook-6b756f4597-cx78m    0/1     Init:0/1           0               5m55s
longhorn-system   longhorn-conversion-webhook-754f8766d5-qvng9   0/1     CrashLoopBackOff   6 (18s ago)     5m55s
longhorn-system   longhorn-conversion-webhook-754f8766d5-x4jq2   0/1     CrashLoopBackOff   5 (2m45s ago)   5m55s
longhorn-system   longhorn-driver-deployer-567786d855-95rh6      0/1     Init:0/1           0               5m56s
longhorn-system   longhorn-manager-8jlxx                         0/1     Init:0/1           0               5m56s
longhorn-system   longhorn-manager-mbqv7                         0/1     Init:0/1           0               5m56s
longhorn-system   longhorn-manager-n6qpw                         0/1     Init:0/1           0               5m56s
longhorn-system   longhorn-manager-rxbcb                         0/1     Init:0/1           0               5m56s
longhorn-system   longhorn-manager-sn95d                         0/1     Init:0/1           0               5m56s
longhorn-system   longhorn-manager-vprdr                         0/1     Init:0/1           0               5m56s
longhorn-system   longhorn-ui-fbdb587c-2wgcr                     0/1     CrashLoopBackOff   5 (56s ago)     5m56s
`

Now i am able to see any error in any of the longhorn pods expect "waiting" for init container.

`$ kubectl logs  longhorn-manager-mbqv7 -n longhorn-system -c wait-longhorn-admission-webhook
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
waiting
$ `

**Comment by atul-devopswarriors** [comment]
Can i get help here please ?

**Comment by lenglet-k** [comment]
Related to: https://github.com/longhorn/longhorn/issues/8780 
It's maybe because /var/ is mounted with noexec options.
