### ISSUE TITLE
[TEST] Rework manual CIS tests

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#6092]
CIS-1.5 is no longer recommended or encouraged for use with RKE2.

- CIS-1.6 should be used with Kubernetes v1.24-
- CIS-1.23 should be used with Kubernetes v1.25+

Rework the tests as appropriate.

**Comment by yangchiu** [comment]
Now we have a pipeline supports running regression tests in a cis-1.23 hardened environment:

In https://ci.longhorn.io/job/private/job/longhorn-tests-regression/, set `DISTRO = sles`, `K8S_DISTRO_NAME = rke2`, `K8S_DISTRO_VERSION > v1.25` and `CIS_HARDENING = true`

But there's a known issue about running backup related test cases in cis-1.23 hardened env: https://github.com/longhorn/longhorn/issues/6342#issuecomment-1645349208

cc @longhorn/qa
