### ISSUE TITLE
[TASK] Move the longhorn test related S3 buckets to the new AWS account

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#6098]
## What's the task? Please describe

Some integration tests like backing image download using the S3 in the old AWS account. We need to migrate it to the new one.

## Describe the items of the task (DoD, definition of done) you'd like
- [x] Prepare the S3 bucket and files in the new account
~~- [ ] Update the test~~

## Additional context

N/A

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by shuo-wu** [comment]
It seems that AWS does now allow creating a new S3 bucket with the same name immediately after deleting the old one.
The recent backing image download related tests may fail.

**Comment by khushboo-rancher** [comment]
Implemented. Thanks @shuo-wu
