### ISSUE TITLE
Trigger Backup Manually

### ISSUE THREAD

**Issue by itmuckel** [longhorn/longhorn#610]
Hello again!
We now use a minio pod as backup target, so we can then backup the backup with our custom services. 

Here's the problem: We're a little paranoid and we don't want to rely on longhorn's recurring backup. Instead we want to have a script that we can trigger whenever we need to which
1. creates the backups
1. processes them with our internal tools.

For this to work we need to trigger the backups (optionally for specific volumes) by a command.

I couldn't find a volumesnapshot or a volumesnapshotclass in the longhorn-system namespace. So how would we do this?

**Comment by yasker** [comment]
Hi @itmuckel 

We don't have a dedicated CLI tool right now, but in our integration test, we communicate with Longhorn manager using cattle python client. You can see some examples here: https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_basic.py#L29

Cattle CLI is at https://github.com/rancher/cattle-cli

We will start working on Longhorn CLI soon.

**Comment by itmuckel** [comment]
@yasker 
Awesome, thank you for your quick response!
In the meantime I hacked something together.

We query the volumes that need to be backed up. Then a kubernetes job starts which accesses the frontend-service's API like `longhorn-frontend/v1/volumes/${volume}?action=snapshotCreate` to get a snapshot name and `*snapshotBackup`. That's enough to trigger backups automatically.

It is extremely hacky though and it would be much nicer to execute those commands over a stable cli interface. :laughing:

PS:
Maybe you know API endpoints from the longhorn-backend that achieve this? Would be a little nicer not to depend on the frontend.

**Comment by yasker** [comment]
@itmuckel I know... I've filed https://github.com/longhorn/longhorn/issues/613 to track Longhorn CLI.

And the backend service is named `longhorn-backend`. :)

**Comment by yasker** [comment]
Close the issue since it's resolved.

**Comment by joshimoo** [comment]
csi snapshot support could be useful for this #304
