### ISSUE TITLE
[BUG] A backup target backed by a Samba server is not recognized

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6100]
## Describe the bug (🐛 if you encounter this issue)

A backup target backed by a Samba server is not recognized. Due to the issue, the backups cannot be correctly listed.

## To Reproduce

1. Create a LH cluster
2. Set up a Samba server and export a folder
3. Set up the backup target with CIFS mount point
4. The backup page cannot list backups correctly.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.5.x and master
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
@derekbit Let's move this to ready-for-testing.

**Comment by weizhe0422** [comment]
## Environment
  - Longhorn version: `v1.5.0` with `master-branch`
    ![image](https://github.com/longhorn/longhorn/assets/17548901/f87e6dca-1c19-4e0b-a9b9-91da046727d3)
     - manager
       ![image](https://github.com/longhorn/longhorn/assets/17548901/30694c45-899f-4fdb-9eaf-2371c7a90f26)
     - engine
       ![image](https://github.com/longhorn/longhorn/assets/17548901/98281e21-0440-4597-b9a6-a3d9e739688d)
     - instance manager
       ![image](https://github.com/longhorn/longhorn/assets/17548901/5ec60ee9-cac7-4608-acbd-e5a6fb44edde)
  - cluster info
    - K8S version: v1.25.3+k3s1
    - master*1 + worker*3
      ![image](https://github.com/longhorn/longhorn/assets/17548901/2af3cc14-9be0-455b-8327-2921471a43f2)

  ## Test result
  **PASS**

  ## Test steps(refer to https://github.com/longhorn/longhorn/issues/6100#issue-1751979924)
  **Scenario 1**
  1. Having a cluster and a samba server with exposed folder
     ![image](https://github.com/longhorn/longhorn/assets/17548901/7b10016a-4a74-445b-a85f-08e1d03047dd)
     - `/etc/samba/smb.conf`
       ![image](https://github.com/longhorn/longhorn/assets/17548901/e1da6e37-e6aa-4d68-b184-a78f04c8c060)
  2. Follow [document](https://longhorn.io/docs/1.5.0/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-smbcifs-backupstore) to deploy cifs-secret
     ![image](https://github.com/longhorn/longhorn/assets/17548901/9e3f664b-69f9-4400-8565-908f505ad6c4)
  3. Setting backup target with the CIFS mount point
     ![image](https://github.com/longhorn/longhorn/assets/17548901/97ced134-d1dd-4d53-aca1-ab5f1bdc793c)
  4. Create a 10Gi attached volume with some data. Then, create a backup for the volume.
     ![image](https://github.com/longhorn/longhorn/assets/17548901/1510b7a3-5437-4b6a-8058-fe0b490a253e)
     ![image](https://github.com/longhorn/longhorn/assets/17548901/acaec204-fc20-4e34-bc5f-2b9396617f2a)
  5. Restore the backup
     ![image](https://github.com/longhorn/longhorn/assets/17548901/428213b8-7388-45f1-87ba-626762a9ec2c)
  6. Enter into the volume mount point of step 4 and step 5 separately. Calculate the checksum, make sure the data is intact.
     ![image](https://github.com/longhorn/longhorn/assets/17548901/689f2432-e8c4-45a0-90b8-a8c7139dd324)

**Comment by weizhe0422** [comment]
## Environment
  - Longhorn version: `v1.5.0` with `v1.5.x` branch
    ![image](https://github.com/longhorn/longhorn/assets/17548901/5572f6af-0293-4a5a-87e1-1bbc3d6a8e3d)
     - manager
       ![image](https://github.com/longhorn/longhorn/assets/17548901/ffe1669d-ee54-4102-b2f9-db9b3d3ce618)
       https://hub.docker.com/layers/longhornio/longhorn-manager/v1.5.x-head/images/sha256-ade0f76477afa34e621f72df4ede2c48e6293e9ee48b4405de806c3580a37062?context=explore
       ![image](https://github.com/longhorn/longhorn/assets/17548901/c1e1274b-23c1-4aea-89ae-47d2df1878dc)
     - engine
      ![image](https://github.com/longhorn/longhorn/assets/17548901/35e97621-e026-4811-89c2-c583cf6325f3)
     - instance manager
       ![image](https://github.com/longhorn/longhorn/assets/17548901/440d5de4-81d1-4cc4-b808-27d7bcacb80d)

  - cluster info
    - K8S version: v1.25.3+k3s1
    - master*1 + worker*3
    ![image](https://github.com/longhorn/longhorn/assets/17548901/dddf4479-c126-45bd-9f53-2256adad0f82)

  ## Test result: Wait check with engineer
  * With using CIFS mount point as backup target
    - Can list up the backups in Backup page
    - Can restore volume with intact data  

  ## Test steps(refer to https://github.com/longhorn/longhorn/issues/6100#issue-1751979924)
  **Scenario 1**
  1. Having a cluster and a samba server with exposed folder
     ![image](https://github.com/longhorn/longhorn/assets/17548901/7b10016a-4a74-445b-a85f-08e1d03047dd)
     - `/etc/samba/smb.conf`
       ![image](https://github.com/longhorn/longhorn/assets/17548901/e1da6e37-e6aa-4d68-b184-a78f04c8c060)
  2. Follow [document](https://longhorn.io/docs/1.5.0/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-smbcifs-backupstore) to deploy cifs-secret
     ![image](https://github.com/longhorn/longhorn/assets/17548901/5b8bb073-d756-473a-80e2-9401df1e77a1)
  3. Setting backup target with the CIFS mount point
     ![image](https://github.com/longhorn/longhorn/assets/17548901/26dab9e6-fc7c-400c-b17a-a3fc7e1b0678)
     ![image](https://github.com/longhorn/longhorn/assets/17548901/fec79143-aeb1-478b-805a-3d8ebd3ff576)
  4. Create a 10Gi attached volume with some data. Then, create a backup for the volume.
  5. Restore the backup
  6. Enter into the volume mount point of step 4 and step 5 separately. Calculate the checksum, make sure the data is intact.

**Comment by derekbit** [comment]
> ## Environment
> * Longhorn version: `v1.5.0` with `v1.5.x` branch
>   ![image](https://user-images.githubusercontent.com/17548901/245492580-5572f6af-0293-4a5a-87e1-1bbc3d6a8e3d.png)
>   
>   * manager
>     ![image](https://user-images.githubusercontent.com/17548901/245492703-ffe1669d-ee54-4102-b2f9-db9b3d3ce618.png)
>     https://hub.docker.com/layers/longhornio/longhorn-manager/v1.5.x-head/images/sha256-ade0f76477afa34e621f72df4ede2c48e6293e9ee48b4405de806c3580a37062?context=explore
>     ![image](https://user-images.githubusercontent.com/17548901/245493877-c1e1274b-23c1-4aea-89ae-47d2df1878dc.png)
>   * engine
>     ![image](https://user-images.githubusercontent.com/17548901/245493788-35e97621-e026-4811-89c2-c583cf6325f3.png)
>   * instance manager
>     ![image](https://user-images.githubusercontent.com/17548901/245494070-440d5de4-81d1-4cc4-b808-27d7bcacb80d.png)
> * cluster info
>   
>   * K8S version: v1.25.3+k3s1
>   * master_1 + worker_3
>     ![image](https://user-images.githubusercontent.com/17548901/245494157-dddf4479-c126-45bd-9f53-2256adad0f82.png)
> 
> ## Test result: Wait check with engineer
> * With using CIFS mount point as backup target
>   
>   * Can list up the backups in Backup page
>   * Can restore volume with intact data
> 
> ## Test steps(refer to [#6100 (comment)](https://github.com/longhorn/longhorn/issues/6100#issue-1751979924))
> **Scenario 1**
> 
> 1. Having a cluster and a samba server with exposed folder
>    ![image](https://user-images.githubusercontent.com/17548901/245435403-7b10016a-4a74-445b-a85f-08e1d03047dd.png)
>    
>    * `/etc/samba/smb.conf`
>      ![image](https://user-images.githubusercontent.com/17548901/245436567-e1da6e37-e6aa-4d68-b184-a78f04c8c060.png)
> 2. Follow [document](https://longhorn.io/docs/1.5.0/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-smbcifs-backupstore) to deploy cifs-secret
>    ![image](https://user-images.githubusercontent.com/17548901/245494638-5b8bb073-d756-473a-80e2-9401df1e77a1.png)
> 3. Setting backup target with the CIFS mount point
>    ![image](https://user-images.githubusercontent.com/17548901/245496283-26dab9e6-fc7c-400c-b17a-a3fc7e1b0678.png)
>    ![image](https://user-images.githubusercontent.com/17548901/245496367-fec79143-aeb1-478b-805a-3d8ebd3ff576.png)
> 4. Create a 10Gi attached volume with some data. Then, create a backup for the volume.
> 5. Restore the backup
> 6. Enter into the volume mount point of step 4 and step 5 separately. Calculate the checksum, make sure the data is intact.

Hello @weizhe0422 
Please use v1.5.x-head or v1.5.0-rc2

**Comment by weizhe0422** [comment]
@derekbit Thank you. I have re-deployed v1.5.0-rc2 to do testing.

According to the results of master-branch result ([Link](https://github.com/longhorn/longhorn/issues/6100#issuecomment-1588980934)) and v1.5.0-rc2 result ([Link](https://github.com/longhorn/longhorn/issues/6100#issuecomment-1589355472)), the results are passed, so I will close this issue.
