### ISSUE TITLE
[BUG] Longhorn Helm Chart doesn't have tolerations for CSI plugin and Engine image daemonsets

### ISSUE THREAD

**Issue by KostLinux** [longhorn/longhorn#6103]
### Description

After upgrading Longhorn from the Helm chart, the engine image and CSI plugin do not have tolerations, resulting in those components not being applied to storage nodes.

### Reproduction Steps

1. Create a few workers, with three of them labeled as Longhorn nodes.
2. Apply taints on the three Longhorn nodes.
3. Upgrade Longhorn using the Helm chart, ensuring to include tolerations.
4. Go to the Longhorn UI and navigate to Settings > Engine Image tab.
5. Click on the engine image.
6. Observe that the engine image is only deployed on untainted nodes.
7. Add tolerations to the engine image using `kubectl edit`.
8. Verify that the engine image is now deployed on the storage nodes.

### Expected Behavior

When upgrading Longhorn from the Helm chart, the engine images and CSI plugin daemonsets should be automatically deployed on storage nodes.

### Environment

- Longhorn version: v1.4.2
- Installation method: Rancher Catalog App
- Kubernetes distro and version: RKE / Kubernetes v1.24.8
  - Number of management nodes in the cluster: 3
  - Number of worker nodes in the cluster: 8
- Node Configuration:
  - OS type and version: Oracle Linux 8
  - CPU per node: 8
  - Memory per node: 16 GB
  - Disk type: 200 GB
  - Network bandwidth between the nodes: 1 Gbps
- Underlying Infrastructure: VMware
- Number of Longhorn volumes in the cluster: 500

### Additional Context

It is important to note that some PVCs may come from an older version of Longhorn. In such cases, the engine images for those PVCs will not be updated until the daemonsets are manually edited. Ensure that the engine image automatic update option is enabled.

**Comment by PhanLe1010** [comment]
Did you set the setting `defaultSettings.taintToleration` for system-managed components (csi plugin, engine image daemonsets, etc...)?

Please refer to the this doc for full details https://longhorn.io/docs/1.4.2/advanced-resources/deploy/taint-toleration/

**Comment by KostLinux** [comment]
Yhea, it could be an option. Thanks!

**Comment by KostLinux** [comment]
Can anyone please look at this issue? @andyjeffries @PhanLe1010 @dmayle @rbq
