### ISSUE TITLE
[BUG] ShareManager constantly restarting, seems to be on wrong Node

### ISSUE THREAD

**Issue by dasantonym** [longhorn/longhorn#6104]
## Describe the bug (🐛 if you encounter this issue)

The cluster contains a set of worker nodes that Longhorn is restricted to by using NodeSelectors. Otherwise, nothing custom is done on the configuration. I am using the default StorageClass. I have lots of ReadWriteOnce PVCs that have no problems and now added a single RWX PVC, which comes up fine, but when mounting I encounter a timeout waiting for the condition on the Pod.

I have noticed that while the ShareManager resource for the PVC is created on a worker node, the actual Pod for the ShareManager is constantly being restarted on a node outside the worker role.

I looked through existing issues regarding RWX and the ShareManager, but couldn't really figure this out based on what I read there.

## To Reproduce

Should be reproducible in the same environment as described above using NodeSelectors to constrain Longhorn's Pod placement.

## Expected behavior

The PVC should be created (works) and should be able to mount in a Pod (doesn't work).

## Log or Support bundle

I can of course generate a support bundle if needed. Otherwise, this is what the `longhorn-manager` says in a constant loop:

```
time="2023-06-09T15:27:14Z" level=debug msg="starting share manager" controller=longhorn-share-manager node=work-b owner=work-b shareManager=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39 state=error volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=info msg="Created pod for share manager" controller=longhorn-share-manager node=work-b owner=work-b pod=share-manager-pvc-474d9a5f-7a6b-416c-b578-755a21b18a39 shareManager=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39 state=starting volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=warning msg="cannot check IsNodeDownOrDeleted() when syncShareManagerPod" controller=longhorn-share-manager error="no node name provided to check node down or deleted" node=work-b owner=work-b shareManager=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39 state=starting volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=debug msg="Found 1 use zones []" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=false node=work-b owner=work-b replicaAutoBalanceType=zone shareEndpoint= shareState=error state=attached volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=debug msg="Found 3 use nodes [work-c work-e work-a]" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=false node=work-b owner=work-b replicaAutoBalanceType=zone shareEndpoint= shareState=error state=attached volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=debug msg="Balanced, all ready zones are used by this volume" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=false node=work-b owner=work-b replicaAutoBalanceType=zone shareEndpoint= shareState=error state=attached volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=debug msg="Found 0 replica candidate for auto-balance" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=false node=work-b owner=work-b replicaAutoBalanceOption=least-effort shareEndpoint= shareState=error state=attached volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=debug msg="Balanced, volume replicas are running on different nodes" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=false node=work-b owner=work-b replicaAutoBalanceType=node shareEndpoint= shareState=error state=attached volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=debug msg="Found 0 replica candidate for auto-balance" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=false node=work-b owner=work-b replicaAutoBalanceOption=least-effort shareEndpoint= shareState=error state=attached volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=debug msg="Found 0 node has at least one schedulable disk" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=false node=work-b owner=work-b shareEndpoint= shareState=error state=attached volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=debug msg="Found 1 use zones []" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=false node=work-b owner=work-b replicaAutoBalanceType=zone shareEndpoint= shareState=starting state=attached volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=debug msg="Found 3 use nodes [work-c work-e work-a]" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=false node=work-b owner=work-b replicaAutoBalanceType=zone shareEndpoint= shareState=starting state=attached volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=debug msg="Balanced, all ready zones are used by this volume" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=false node=work-b owner=work-b replicaAutoBalanceType=zone shareEndpoint= shareState=starting state=attached volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=debug msg="Found 0 replica candidate for auto-balance" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=false node=work-b owner=work-b replicaAutoBalanceOption=least-effort shareEndpoint= shareState=starting state=attached volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=debug msg="Balanced, volume replicas are running on different nodes" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=false node=work-b owner=work-b replicaAutoBalanceType=node shareEndpoint= shareState=starting state=attached volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=debug msg="Found 0 replica candidate for auto-balance" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=false node=work-b owner=work-b replicaAutoBalanceOption=least-effort shareEndpoint= shareState=starting state=attached volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=debug msg="Found 0 node has at least one schedulable disk" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=false node=work-b owner=work-b shareEndpoint= shareState=starting state=attached volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=debug msg="Share Manager pod requires cleanup with remount" controller=longhorn-share-manager node=work-b owner=work-b shareManager=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39 state=starting volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
time="2023-06-09T15:27:14Z" level=debug msg="node of share manager pod is down, force deleting pod to allow fail over" controller=longhorn-share-manager node=work-b owner=work-b shareManager=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39 state=error volume=pvc-474d9a5f-7a6b-416c-b578-755a21b18a39
```

I cannot get any logs for the failing ShareManager Pod.

## Environment

 - Longhorn version: 1.4.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 1.24.3
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: Ubuntu 22.04
   - CPU per node: 256
   - Memory per node: 2TB
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 10Gbit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 112

**Comment by derekbit** [comment]
@dasantonym 
Can you provide a support bundle? Thank you.

**Comment by dasantonym** [comment]
@derekbit Sorry, I tried but then the download of the bundle timed out and now it just says "Another support bundle is in the read to download phase" and neither lets me download the old one, nor reset and create a new one. How can I get to the bundle now?

**Comment by innobead** [comment]
> @derekbit Sorry, I tried but then the download of the bundle timed out and now it just says "Another support bundle is in the read to download phase" and neither lets me download the old one, nor reset and create a new one. How can I get to the bundle now?

Are you able to delete the old bundle, then create another support bundle to try again? It seems some orphaned downloading session. cc @c3y1huang

**Comment by dasantonym** [comment]
Sure, I should be able to do that, but in which pod should it I be looking for it?

**Comment by innobead** [comment]
you should be able to use kubectl to delete the support bundle resource to see if it works or use Longhorn UI to do that.

**Comment by dasantonym** [comment]
Thanks for all the help, I was finally able to do it with the cURL instructions in troubleshooting. So, finally, here's the support bundle (hooray).

https://drive.google.com/file/d/1KCXMEX5GWMOTErAS3yy3tIj8EhndSzMI/view?usp=sharing

**Comment by PhanLe1010** [comment]
From the support bundle, I saw that the setting `system-managed-components-node-selector`  is empty which indicate that you have not set the node selector for system managed component (share-manager is one of the system managed components). Please follow the document to set it https://longhorn.io/docs/1.4.2/advanced-resources/deploy/node-selector/#setting-up-node-selector-after-longhorn-has-been-installed. Note that:

> Make sure all Longhorn volumes are detached. If there are running Longhorn volumes in the system, this means the Longhorn system cannot restart its components and the request will be rejected.

**Comment by PhanLe1010** [comment]
Btw, did you install the NFS client? https://longhorn.io/docs/1.4.2/deploy/install/#installing-nfsv4-client

**Comment by dasantonym** [comment]
@PhanLe1010 Thanks a ton for figuring this out! So then we can probably safely say that this isn't a bug. 🙏 

I installed the NFS client on all nodes and if this doesn't sort it out, I'll reopen. Will need to schedule a system downtime so I can't immediately check. Thanks again!
