### ISSUE TITLE
[IMPROVEMENT] Error message recording in SPDK engine service

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#6105]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

If somehow a SPDK engine/replica becomes state error, the error info should be cached.

## Describe the solution you'd like

Same as the above description

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by innobead** [comment]
@shuo-wu can give more context on this issue? you can directly update the description.

**Comment by derekbit** [comment]
Should be fixed. Reopen if needed.
