### ISSUE TITLE
[IMPROVEMENT] UI supports automatic replica rebuilding for SPDK volumes

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6107]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

**SPDK volumes** support per-volume automatic replica rebuilding, so UI needs some updates

- Can specify `Volume.Spec.OfflineReplicaRebuilding` when creating a volume. The values are
  - ignored (default value)
  - disabled
  - enabled
- Volume page can change `volume.Spec.OfflineReplicaRebuilding`

- If a SPDK volume is `degraded`, should a warning message remaindering users that `replica rebuilding will be automatically triggered when the degraded volume is detached`

## Additional context

https://github.com/longhorn/longhorn/issues/6071

**Comment by derekbit** [comment]
Add a hint for offline replica building

![image](https://github.com/longhorn/longhorn/assets/12527233/0207cfd6-acdb-415a-b178-4ea65724b85c)

WDYT @innobead @shuo-wu

**Comment by shuo-wu** [comment]
BTW, when a SPDK volume is degraded, can we add a similar hint to inform users that, the rebuilding will be triggered when the volume is in maintenance mode?

**Comment by innobead** [comment]
UX LGTM

**Comment by derekbit** [comment]
> BTW, when a SPDK volume is degraded, can we add a similar hint to inform users that, the rebuilding will be triggered when the volume is in maintenance mode?

Hello @smallteeths
Can you help with the idea?
If a spdk volume is attached, degraded and disableFrontend=false, add a hint for users.
Thank you.

**Comment by smallteeths** [comment]
> > BTW, when a SPDK volume is degraded, can we add a similar hint to inform users that, the rebuilding will be triggered when the volume is in maintenance mode?
> 
> Hello @smallteeths Can you help with the idea? If a spdk volume is attached, degraded and disableFrontend=false, add a hint for users. Thank you.

Ok 

The UI condition for judgment is as follows.
```
!volume.disableFrontend && volume.backendStoreDriver === ‘spdk’ && volume.state === ‘attached’
```

Add alert `The volume rebuilding will be triggered`

**Comment by innobead** [comment]
Moving to ready for testing, QA can follow the description to verify the UI part.

**Comment by roger-ryao** [comment]
**Verified on v1.5.x-head 20230619**

- longhorn v1.5.x-head https://github.com/longhorn/longhorn/commit/428f1d54c1e4fad33b33782888f30125cf56c725
- longhorn-ui v1.5.x-head https://github.com/longhorn/longhorn-ui/commit/8fd8e1e3e9f93d587e5f6322776e4a67791adcf8



**Verified on master-head 20230619**

- longhorn master-head https://github.com/longhorn/longhorn/commit/27f482bd9b6e96ebff5b8f1eb4b62b49dda46553
- longhorn-ui master-head https://github.com/longhorn/longhorn-ui/commit/26c115f7656a58f255079cced41e3538b4eb2a1b


**Result Passed**

- [x] After creating a volume, we can verify that the `Offline Replica Rebuilding` option values `ignored (default value)`, `disabled`, and `enabled` are shown in the Longhorn UI.
- [x] We can update the `Offline Replica Rebuilding` on the volume page.
- [x] When a SPDK volume is degraded, a warning message will remind users that `The volume rebuilding will be automatically triggered after detachment`.
![Screenshot_20230619_131544](https://github.com/longhorn/longhorn/assets/104337648/95a17f71-169a-4112-a4ac-5091539a171f)

![Screenshot_20230619_135731](https://github.com/longhorn/longhorn/assets/104337648/94571017-1933-4736-8f1c-a3e80baaf7da)
