### ISSUE TITLE
Why Longhorn volume state is detached and Health unknown , but log show attached to a node?

### ISSUE THREAD

**Issue by shaolila** [longhorn/longhorn#6109]
## Question
![Longhorn_volume_detached_butlog_show_attached_to_a_node](https://github.com/longhorn/longhorn/assets/8872412/8c05efa3-5d62-47d6-b392-425b25070156)

(https://github.com/longhorn/longhorn/assets/8872412/894a0bb6-92f5-4a80-9363-4d94e7b434f0)

## Environment

 - Longhorn version:1.4.1
 - Kubernetes version:1.23.13
 - Node config
   - OS type and version:CentOS8
   - CPU per node:
   - Memory per node: 
   - Disk type: lvm
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Comment by lexfrei** [comment]
In my case, this fixed and issue:
The volume was 7.82/8Gi. I added +2Gi to it. After resizing, I recreated the pod and it started well.

**Comment by shaolila** [comment]
> In my case, this fixed and issue: The volume was 7.82/8Gi. I added +2Gi to it. After resizing, I recreated the pod and it started well.

You mean this error is because the volume is full ,expanding the capacity of the volume can solve the problem
right?

**Comment by lexfrei** [comment]
Welp, the last volume was in 7.98/8Gi. +2Gi did nothing, the recreation of the pod not fixed anything. +1Gi fixed the issue.

**Comment by mantissahz** [comment]
Hi @shaolila,
Is this issue still there?
Need more information for investigating.
How many nodes do you deploy? How many control nodes do you set? How many worker nodes do you set?
Before this issue happened, what did you do?

Hi @lexfrei,
Thanks for the testings.
Could you send us the support bundle if/after this happened again?
