### ISSUE TITLE
[BUG] Potential race condition between creating/restoring backup and deleting backup

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#612]
When deleting backups, we're checking the backup's block and scan all the other backups to decide which blocks can be discarded. If a new backup:
1. is created after the GC backup scanning was done
2. but before the GC process was done
3. and has reused one of the blocks in the old backup
4. and has checked the block exists already before GC process gets to it.

Then the block won't exist so that backup cannot be used for restoration since one block is missing. Though it's pretty much an "all the stars have aligned" situation, we need to address it.

**Comment by yasker** [comment]
Punt it to later.

1. We haven't seen this in real life yet.
2. If the user has scheduled recurring backup (which is very likely the case), even if this issue is triggered, the previous backup should still be intact.

**Comment by joshimoo** [comment]
I added some improvements in regard to the concurrency issues in longhorn/backupstore#37

**Comment by joshimoo** [comment]
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?
The LEP PR is at longhorn/longhorn#1546

* [ ] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The PR is at

* [ ] Is the reproduce steps/test steps documented?

* [ ] Which areas/issues this PR might have potential impacts on?
Area: backupstore, backup creation, backup deletion, backup restoration, recurring backups (longhorn manager)

* [x]~~ **If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?~~

* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~

* [x] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?~~

* [ ] **If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at

* [ ] **if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at

* [ ] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at

**Comment by yasker** [comment]
We had an issue with build backupstore after the merge, and the engine integration test become flakey. Move back to Review.

**Comment by yasker** [comment]
Move to v1.0.2 due to build failure and engine integration test failure.

**Comment by yasker** [comment]
@joshimoo Can you update the backupstore for manager and engine to get this issue to Merged?

**Comment by joshimoo** [comment]
All rebased and restore change fixed in longhorn/longhorn-engine#529.

**Comment by khushboo-rancher** [comment]
Verified with longhorn master - 10/02/2020

Validation - **Pass**

Validated the below scenarios:
1. Backup deletion during a backup restoration - Backup deletion prevented
2. Backup deletion while a backup is in progress - Backup deletion prevented
3. Backup creation during a backup deletion - Backup creation prevented
4. Backup restoration during a backup deletion - Backup volume became faulted.
5. Parallel backup creation - worked fine.
6. Some basic regression around backup creation and restoration.
