### ISSUE TITLE
[BUG] Can't delete engineimage after upgrade from v1.4.0 to v1.4.2

### ISSUE THREAD

**Issue by aureq** [longhorn/longhorn#6121]
## Describe the bug (🐛 if you encounter this issue)

I upgraded Longhorn from v1.4.0 to v1.4.2 using the latest Helm Chart (no customisation). Everything went fine.
This time, I opted for an online upgrade of the existing volumes. I set `concurrent-automatic-engine-upgrade-per-node-limit` to `1`.

All volumes appear to have upgraded correctly according to this command:

```bash
# get volumes -n longhorn-system  -o=custom-columns='NAME:.metadata.name,ENGINE_IMAGE:.spec.engineImage,CURRENT_IMAGE:.status.currentImage,STATE:.status.state,ROBUSTNESS:.status.robustness,PVC_NAMESPACE:.status.kubernetesStatus.namespace,PVC_NAME:.status.kubernetesStatus.pvcName'
NAME                                       ENGINE_IMAGE                        CURRENT_IMAGE                       STATE      ROBUSTNESS   PVC_NAMESPACE         PVC_NAME
pvc-06316119-4989-4dcc-a407-7ff169dd73ae   longhornio/longhorn-engine:v1.4.2   longhornio/longhorn-engine:v1.4.2   attached   healthy      identity-services     openldap-var-lib-ldap-pvc
pvc-3a1a084a-c2be-49c3-9d56-4e71186f0adf   longhornio/longhorn-engine:v1.4.2   longhornio/longhorn-engine:v1.4.2   attached   healthy      docs-services         minio-snsd-pvc
pvc-3aaee8f5-ef4b-4d98-82e6-f2a664bc809d   longhornio/longhorn-engine:v1.4.2   longhornio/longhorn-engine:v1.4.2   attached   healthy      registry-system       harbor-jobservice
pvc-4c71c035-d097-4c54-9c31-f9884c5fbbaf   longhornio/longhorn-engine:v1.4.2   longhornio/longhorn-engine:v1.4.2   attached   healthy      dev-services          gitlab-etc-gitlab-pvc
pvc-64d46873-c90c-4792-bbab-e3bd0d5a033e   longhornio/longhorn-engine:v1.4.2   longhornio/longhorn-engine:v1.4.2   attached   healthy      sandbox               devbox-root-work-pvc
pvc-66a21b01-69bd-4620-a8fb-d0776a3e86fa   longhornio/longhorn-engine:v1.4.2   longhornio/longhorn-engine:v1.4.2   attached   healthy      apt-services          minio-snsd-pvc
pvc-67dce9ac-0c0d-4171-87aa-e57762dfc59a   longhornio/longhorn-engine:v1.4.2   longhornio/longhorn-engine:v1.4.2   attached   healthy      registry-system       harbor-redis-pvc
pvc-6f205ae8-0cda-4586-9d33-a886a816b5f2   longhornio/longhorn-engine:v1.4.2   longhornio/longhorn-engine:v1.4.2   attached   healthy      registry-system       minio-snsd-pvc
pvc-82bd735f-2a06-490f-a5b6-930952a94cba   longhornio/longhorn-engine:v1.4.2   longhornio/longhorn-engine:v1.4.2   attached   healthy      home-services         minio-aurelien-snsd-pvc
pvc-8b6e47d5-368d-4743-bf4f-c262065d9ddd   longhornio/longhorn-engine:v1.4.2   longhornio/longhorn-engine:v1.4.2   attached   healthy      home-services         minio-home-snsd-pvc
pvc-ae189871-0f1b-407c-bcb5-187de1c1a481   longhornio/longhorn-engine:v1.4.2   longhornio/longhorn-engine:v1.4.2   attached   healthy      identity-services     openldap-etc-ldap-slapd-d-pvc
pvc-b741b003-23ac-461f-9d11-bab3cb5e08d1   longhornio/longhorn-engine:v1.4.2   longhornio/longhorn-engine:v1.4.2   attached   healthy      monitoring-services   prometheus-pvc
pvc-bc99c975-47ca-43d4-b5bd-b3201414896e   longhornio/longhorn-engine:v1.4.2   longhornio/longhorn-engine:v1.4.2   attached   healthy      registry-system       harbor-database-pvc
pvc-c858b8fc-8e84-40d9-8268-bcccabff369c   longhornio/longhorn-engine:v1.4.2   longhornio/longhorn-engine:v1.4.2   attached   healthy      sandbox               devbox-root-pulumi-pvc
pvc-f4905f67-ee2c-4994-8fcd-bb94630c88d0   longhornio/longhorn-engine:v1.4.2   longhornio/longhorn-engine:v1.4.2   attached   healthy      dev-services          gitlab-var-opt-gitlab-pvc
pvc-fb15c390-efae-4ba5-b376-863cc0f71a26   longhornio/longhorn-engine:v1.4.2   longhornio/longhorn-engine:v1.4.2   attached   healthy      identity-services     openldap-var-backups-slapd-pvc
pvc-fb873219-98e3-4393-81df-c6bfb08f4892   longhornio/longhorn-engine:v1.4.2   longhornio/longhorn-engine:v1.4.2   attached   healthy      sandbox               devbox-root-vscode-server-pvc
```

Though, when I try to delete the previous engine image (v1.4.o) I get the following error.

```
unable to delete engine image: unable to delete the engine image while being used
```

![image](https://github.com/longhorn/longhorn/assets/1161681/94faafb7-d612-41a7-8dfe-f0eb8c3db12d)

I also noticed the `Reference count` but it's unclear if I should be doing anything else. It initially increased a little from `0` to `85` and then it stopped increasing.

## To Reproduce

1. Install v1.4.0 using Helm
2. Create a few volumes
3. Create a few workloads using those volumes
4. Upgrade to v1.4.2
5. Run `get volumes -n longhorn-system  -o=custom-columns='NAME:.metadata.name,ENGINE_IMAGE:.spec.engineImage,CURRENT_IMAGE:.status.currentImage,STATE:.status.state,ROBUSTNESS:.status.robustness,PVC_NAMESPACE:.status.kubernetesStatus.namespace,PVC_NAME:.status.kubernetesStatus.pvcName'`
6. Note that v1.4.0 is in use for your listed volumes
7. Set `concurrent-automatic-engine-upgrade-per-node-limit` from `0` to `1`.
8. Run `get volumes -n longhorn-system  -o=custom-columns='NAME:.metadata.name,ENGINE_IMAGE:.spec.engineImage,CURRENT_IMAGE:.status.currentImage,STATE:.status.state,ROBUSTNESS:.status.robustness,PVC_NAMESPACE:.status.kubernetesStatus.namespace,PVC_NAME:.status.kubernetesStatus.pvcName'`
9. Note that v1.4.2 is in use for your listed volumes
10. Go to the Longhorn management console and try to delete the v1.4.0 engine image
11. Notice the error message.

## Expected behavior

I could be wrong, but my understanding is when the Current Image and the Engine Image are set to 1.4.2, then the migration is done and I could delete the previous Engine Image.

## Log or Support bundle

Support bundle: The bundle is larger than 25MB, so it's available [here](https://home.menfin.net/downloads/supportbundle_a6e276fe-521e-4350-9a81-2075f0eff4b3_2023-06-14T02-25-31Z.zip).

## Environment

 - Longhorn version: 1.4.0 / 1.4.2
 - Installation method: Helm
 - Kubernetes distro/version: K3s v1.25.6+k3s1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version: Debian 12 (control plane) and 11 (worker)
   - CPU per node: 4C8T (control plane) and 12C24T (worker)
   - Memory per node: 32GB (control plane) and 64GB (worker)
   - Disk type(e.g. SSD/NVMe): NVME (control plane) and VMWare disk (worker)
   - Network bandwidth between the nodes: 1Gbps
 - Underlying Infrastructure: Bare metal (control plane) and VMWare Workstation (worker)
 - Number of Longhorn volumes in the cluster: 17 volumes all healthy, as listed above

## Additional context

1. The day prior to the upgrade, one of the API Server client certificate expired which caused issues in the volume replications (I think) and forced me to manually rotate those certs and then restart the cluster.
2. The worker node doesn't replicate any volumes locally as it runs only when needed.

**Comment by derekbit** [comment]
@aureq 

Hit the known issue https://github.com/longhorn/longhorn/issues/5762
Please check the workaround. Thank you.

**Comment by derekbit** [comment]
@aureq

Hit the known issue https://github.com/longhorn/longhorn/issues/5762 
Please check the workaround in https://github.com/longhorn/longhorn/issues/5902#issuecomment-1545914627 and https://github.com/longhorn/longhorn/issues/5762 . Thank you.

**Comment by aureq** [comment]
@derekbit yes, I came across that issue before opening this one. However, when I ran

```bash
kubectl edit mutatingwebhookconfigurations longhorn-webhook-mutator
```
The value for `failurePolicy` was already at `Fail`.

**Comment by aureq** [comment]
@derekbit yes, I came across that issue before opening this one. However, when I ran

```bash
kubectl edit mutatingwebhookconfigurations longhorn-webhook-mutator
```
The value for `failurePolicy` was already at `Fail`.

Looking at https://github.com/longhorn/longhorn/issues/5902#issuecomment-1545914627 I do see a lot of `stopped` replica.
However, is it safe to delete the stopped replica as suggested here? https://github.com/longhorn/longhorn/issues/5902#issuecomment-1548687212

```bash
kubectl -n longhorn-system get replica | grep stopped | awk '{ print $1 }' | xargs kubectl -n longhorn-system delete replica
```

**Comment by derekbit** [comment]
> @derekbit yes, I came across that issue before opening this one. However, when I ran
> 
> ```shell
> kubectl edit mutatingwebhookconfigurations longhorn-webhook-mutator
> ```
> 
> The value for `failurePolicy` was already at `Fail`.
> 
> Looking at [#5902 (comment)](https://github.com/longhorn/longhorn/issues/5902#issuecomment-1545914627) I do see a lot of `stopped` replica. However, is it safe to delete the stopped replica as suggested here? [#5902 (comment)](https://github.com/longhorn/longhorn/issues/5902#issuecomment-1548687212)
> 
> From the look of it, it may not be safe. So what would be the alternative to address the issue?
> 
> ```shell
> kubectl -n longhorn-system get replica | grep stopped | awk '{ print $1 }' | xargs kubectl -n longhorn-system delete replica
> ```

I see. I know your concern.
Can you send a support bundle to `longhorn-support-bundle@suse.com`?
I can help check what replicas you can delete. WDYT?

**Comment by aureq** [comment]
@derekbit Thanks a lot.

The bundle is already available [here](https://home.menfin.net/downloads/supportbundle_a6e276fe-521e-4350-9a81-2075f0eff4b3_2023-06-14T02-25-31Z.zip) or would you prefer me to email it? I fear that 33MB may be too big for emails on my end (Gmail).

**Comment by derekbit** [comment]
> @derekbit Thanks a lot.
> 
> The bundle is already available [here](https://home.menfin.net/downloads/supportbundle_a6e276fe-521e-4350-9a81-2075f0eff4b3_2023-06-14T02-25-31Z.zip) or would you prefer me to email it? I fear that 33MB may be too big for emails on my end (Gmail).

I'm fine with it. I will check it soon. Thank you.

**Comment by derekbit** [comment]
@aureq 
You can delete the **`stopped`** replicas whose label contains **`longhornnode: "null"`** by `kubectl` command.
These stopped replicas are not managed by longhorn system because of  https://github.com/longhorn/longhorn/issues/5762. Due to the lack of the label, longhorn cannot recognize and delete them.

The stopped replica looks existing before. `v1.4.2` already fixes the issue, so you can see the `failurePolicy` is `Fail`.
The issue won't happen in the future.

**Comment by aureq** [comment]
@derekbit 

Thanks a lot for all the information and confirmation.

After more than 40 minutes to complete, all of the 8772 replicas have been delete and the cluster looks stable.
I was also able to remove the v1.4.0 engine image.
