### ISSUE TITLE
[BUG] SPDK Volume snapshotList API Error

### ISSUE THREAD

**Issue by smallteeths** [longhorn/longhorn#6123]
## Describe the bug (🐛 if you encounter this issue)

<img width="1030" alt="截屏2023-06-14 下午4 19 16" src="https://github.com/longhorn/longhorn/assets/27733391/ede86a07-d45e-4668-a1a1-43272855c7cc">

## To Reproduce

1. Create spdk volume (replica 3)
2. Perform attach node (The volume state is degraded)
3. Perform detach
4. Route to the  volume detail page

## Expected behavior

The "snapshotList" API returns successfully and returns an empty array.

## Environment

 - Longhorn version: master-header
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE2) and version: 1.24

**Comment by chriscchien** [comment]
Hi @smallteeths 
When I try create spdk volume from UI, I get error `failed to create volume: unable to create volume vol1: Volume.longhorn.io "vol1" is invalid: spec.backendStoreDriver: Unsupported value: "spdk": supported values: "v1", "v2"`

And I tried create spdk volume from manifest, the snapshotList API worked well, I will test again once spdk volume can create from UI, thank you.
![image](https://github.com/longhorn/longhorn/assets/73337386/a4743fec-3cec-4a8b-8e3e-e6ce55c018b2)

**Comment by derekbit** [comment]
@chriscchien 
The chage is not merged yet. I'm reviewing it.

**Comment by chriscchien** [comment]
Will test angin after https://github.com/longhorn/longhorn/issues/6128 complete, thank you

**Comment by chriscchien** [comment]
Verified **pass** in
- longhorn master(longhorn-ui `26c115`)
- longhorn v1.5.x (longhorn-ui `8fd8e1`)

Following test [steps](https://github.com/longhorn/longhorn/issues/6123#issue-1756351701), did not encouneter snapshotList API error in master-head and v1.5.x
