### ISSUE TITLE
[BUG] disk monitor cannot recognize disks if disk paths are somehow changed after reboot

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6125]
## Describe the bug (🐛 if you encounter this issue)

When a block-type disk is added, a lvstore is created, and its UUID is stored in node.Status.DiskStatus. If the underlying storage of the disk is replaced, such as changing the disk path after a reboot, spdk_tgt fails to recognize it and attempts to create a new lvstore on the disk. This operation leads to contamination of the wrong disk's contents.

To resolve this problem, we can send the recorded disk UUID to the disk grpc service to assist in checking if the disk is the expected one.

## To Reproduce

We can emulate the issue by the steps 

1. Create a block-type disk `test-block-1` on a node using a loop device
    ```
    dd if=/dev/zero of=blockfile1 bs=1M count=5120 && sudo losetup /dev/loop0 blockfile1
    ```
2. Restart the node
3. Create a new file for the loop device (`/dev/loop0`)
    ```
    dd if=/dev/zero of=blockfile2 bs=1M count=5120 && sudo losetup /dev/loop0 blockfile2
    ```
4. The disk is added to the node, and the blockfile2 is contaminated.
    ```
    grep -nr test-block-1 blockfile2
    ```

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
This should be fixed in 1.5.0 already, but it seems missing to validate by @longhorn/qa ?

**Comment by yangchiu** [comment]
Does this improvement try to solve [this issue](https://github.com/longhorn/longhorn/issues/5827#issuecomment-1584009213) in https://github.com/longhorn/longhorn/issues/5827? If so, I can still observe this issue in master-head (longhorn-manager 77ed1a7) by the following steps:

1. Create nodes with machine type `c5d.2xlarge`, and complete and spdk setup
2. Originally, the nvme device is on `/dev/nvme1n1`, so we create the block type disk with path `/dev/nvme1n1`:
```
$ fdisk -l
Disk /dev/nvme0n1: 300 GiB, 322122547200 bytes, 629145600 sectors
Disk model: Amazon Elastic Block Store              
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 4B464A1A-ABA0-49AF-8065-3030FA493F67

Disk /dev/nvme1n1: 186.26 GiB, 200000000000 bytes, 390625000 sectors
Disk model: Amazon EC2 NVMe Instance Storage        
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/nvme2n1: 160 GiB, 171798691840 bytes, 335544320 sectors
Disk model: Amazon Elastic Block Store              
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
```
3. And everything works well, spdk volume can be created, workload works well too, data can be write into/read from the spdk volume through the workload
4. After reboot the node, the nvme device is changed to `/dev/nvme2n1`, and the block type disk we just created in step 2 becomes `Unschedulable` with size `0 / 0 Gi`:
```
$ fdisk -l
Disk /dev/nvme2n1: 186.26 GiB, 200000000000 bytes, 390625000 sectors
Disk model: Amazon EC2 NVMe Instance Storage        
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/nvme0n1: 300 GiB, 322122547200 bytes, 629145600 sectors
Disk model: Amazon Elastic Block Store              
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 4B464A1A-ABA0-49AF-8065-3030FA493F67

Disk /dev/nvme1n1: 160 GiB, 171798691840 bytes, 335544320 sectors
Disk model: Amazon Elastic Block Store              
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
```
![Screenshot from 2023-07-17 17-35-03](https://github.com/longhorn/longhorn/assets/5709208/f4b4a4ee-673d-4093-b23a-3ff3e71af9c6)
[supportbundle_cfda4f6b-b95a-45db-9e96-9036892bb276_2023-07-17T09-35-48Z.zip](https://github.com/longhorn/longhorn/files/12067864/supportbundle_cfda4f6b-b95a-45db-9e96-9036892bb276_2023-07-17T09-35-48Z.zip)

**Comment by innobead** [comment]
> After reboot the node, the nvme device is changed to /dev/nvme2n1, and the block type disk we just created in step 2 becomes Unschedulable with size 0 / 0 Gi:

I think the fix here is to prevent the disk will not be initialized again after you update the disk with the new path. The fix is not to automatically correct the relationship between the new path of the block device and the Longhorn block disk.  @derekbit right?

I would be helpful to update the testing steps for QA.

**Comment by derekbit** [comment]
> Does this improvement try to solve [this issue](https://github.com/longhorn/longhorn/issues/5827#issuecomment-1584009213) in #5827? If so, I can still observe this issue in master-head (longhorn-manager 77ed1a7) by the following steps:
> 
> 1. Create nodes with machine type `c5d.2xlarge`, and complete and spdk setup
> 2. Originally, the nvme device is on `/dev/nvme1n1`, so we create the block type disk with path `/dev/nvme1n1`:
> 
> ```
> $ fdisk -l
> Disk /dev/nvme0n1: 300 GiB, 322122547200 bytes, 629145600 sectors
> Disk model: Amazon Elastic Block Store              
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 4096 bytes / 4096 bytes
> Disklabel type: gpt
> Disk identifier: 4B464A1A-ABA0-49AF-8065-3030FA493F67
> 
> Disk /dev/nvme1n1: 186.26 GiB, 200000000000 bytes, 390625000 sectors
> Disk model: Amazon EC2 NVMe Instance Storage        
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> 
> Disk /dev/nvme2n1: 160 GiB, 171798691840 bytes, 335544320 sectors
> Disk model: Amazon Elastic Block Store              
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 4096 bytes / 4096 bytes
> ```
> 
> 3. And everything works well, spdk volume can be created, workload works well too, data can be write into/read from the spdk volume through the workload
> 4. After reboot the node, the nvme device is changed to `/dev/nvme2n1`, and the block type disk we just created in step 2 becomes `Unschedulable` with size `0 / 0 Gi`:
> 
> ```
> $ fdisk -l
> Disk /dev/nvme2n1: 186.26 GiB, 200000000000 bytes, 390625000 sectors
> Disk model: Amazon EC2 NVMe Instance Storage        
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> 
> Disk /dev/nvme0n1: 300 GiB, 322122547200 bytes, 629145600 sectors
> Disk model: Amazon Elastic Block Store              
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 4096 bytes / 4096 bytes
> Disklabel type: gpt
> Disk identifier: 4B464A1A-ABA0-49AF-8065-3030FA493F67
> 
> Disk /dev/nvme1n1: 160 GiB, 171798691840 bytes, 335544320 sectors
> Disk model: Amazon Elastic Block Store              
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 4096 bytes / 4096 bytes
> ```
> 
> ![Screenshot from 2023-07-17 17-35-03](https://user-images.githubusercontent.com/5709208/253902903-f4b4a4ee-673d-4093-b23a-3ff3e71af9c6.png) [supportbundle_cfda4f6b-b95a-45db-9e96-9036892bb276_2023-07-17T09-35-48Z.zip](https://github.com/longhorn/longhorn/files/12067864/supportbundle_cfda4f6b-b95a-45db-9e96-9036892bb276_2023-07-17T09-35-48Z.zip)
> 
> cc @derekbit

Yes, this is expeceted.
The steps are updated in https://github.com/longhorn/longhorn/issues/6125#issuecomment-1591694243.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 77ed1a7) and v1.5.x-head (longhorn-manager 910081c) following [the test steps](https://github.com/longhorn/longhorn/issues/6125#issue-1757310951).
