### ISSUE TITLE
[BUG] Cron job triggered replica rebuilding keeps repeating itself after corrupting snapshot data

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6129]
## Describe the bug (🐛 if you encounter this issue)

On `master-head` and `v1.5.x-head`, the test case `test_snapshot_hash_detect_corruption_in_global_enabled_mode` and  `test_snapshot_hash_detect_corruption_in_global_fast_check_mode` failed because of waiting for replica rebuilding timeout:

```
    def wait_for_rebuild_complete(client, volume_name, retry_count=RETRY_COUNTS):
        completed = 0
        rebuild_statuses = {}
        for i in range(retry_count):
            completed = 0
            v = client.by_id_volume(volume_name)
            rebuild_statuses = v.rebuildStatus
            for status in rebuild_statuses:
                if status.state == "complete":
                    assert status.progress == 100
                    assert not status.error
                    assert not status.isRebuilding
                    completed += 1
                elif status.state == "":
                    assert not status.error
                    assert not status.isRebuilding
                    completed += 1
                elif status.state == "in_progress":
                    assert status.isRebuilding
                else:
                    assert status.state == "error"
                    assert status.error != ""
                    assert not status.isRebuilding
            if completed == len(rebuild_statuses):
                break
            time.sleep(RETRY_INTERVAL)
>       assert completed == len(rebuild_statuses)
E       AssertionError
```

If we extend the `retry_count` to avoid it from timeout (`yangchiu/test-local` can be used for testing) and run the test case, after setup cron job for snapshot integrity checking, and corrupt the snapshot data, we can observe the replica rebuilding keeps repeating itself:

1. it starts rebuilding
2. gets stuck in progress 66% or 99%
3. replica rebuilding failed
4. then it starts over. 

This cycle could repeat more than 3 times to make the replica rebuilding finally completed. 

## To Reproduce

Run test case `test_snapshot_hash_detect_corruption_in_global_enabled_mode` and  `test_snapshot_hash_detect_corruption_in_global_fast_check_mode`

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
cc @derekbit

**Comment by yangchiu** [comment]
Just for information. Like https://github.com/longhorn/longhorn/issues/6145, this issue could be introduced after v1.5.0-rc2, at least we didn't observe this in v1.5.0-rc1.

**Comment by mantissahz** [comment]
Hi @yangchiu,
According to [#6145](https://github.com/longhorn/longhorn/issues/6145), @derekbit should have solved this issue.
And I run the test cases `test_snapshot_hash_detect_corruption_in_global_enabled_mode` and `test_snapshot_hash_detect_corruption_in_global_fast_check_mode` by `master-head` several times and Passed.
Could you check about this and maybe we could close this issue?

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager a3b16b8) and v1.5.x-head (longhorn-manager 6f26265) by running the test case `test_snapshot_hash_detect_corruption_in_global_enabled_mode` and `test_snapshot_hash_detect_corruption_in_global_fast_check_mode`.

Run `test_snapshot_hash_detect_corruption_in_global_enabled_mode` **30** times on master-head, all passed:
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4264/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4265/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4266/

Run `test_snapshot_hash_detect_corruption_in_global_fast_check_mode` **30** times on master-head, all passed:
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4238/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4241/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4243/

Run `test_snapshot_hash_detect_corruption_in_global_enabled_mode` **30** times on v1.5.x-head, all passed:
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4267/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4269/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4270/

Run `test_snapshot_hash_detect_corruption_in_global_fast_check_mode` **30** times on v1.5.x-head, all passed:
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4268/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4271/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4272/
