### ISSUE TITLE
[FEATURE] Longhorn CLI

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#613]
We need Longhorn CLI as an alternative to the Longhorn UI for automation/scripting purpose.

**Comment by ffilippopoulos** [comment]
Hi, I do not know what is the progress on this one, but since we are using longhorn for an on-premises cluster and we needed a way to automate our nodes updating process we started writing a simple cli here:
https://github.com/utilitywarehouse/lhctl
I thought to share it here in case it can be of any help to anyone :)) It is really simple but enough to enable/disable nodes, scale volumes and drain replicas of nodes for the moment.

**Comment by yasker** [comment]
@ffilippopoulos Wow, that's great!

We haven't started working on the Longhorn CLI yet, and I would be very glad to help with any issues/questions you might have while working on your version of CLI.

Btw, nice name `lhctl`. It's exactly the name as we're planning to use with Longhorn CLI. 😄

**Comment by oxr463** [comment]
> Hi, I do not know what is the progress on this one, but since we are using longhorn for an on-premises cluster and we needed a way to automate our nodes updating process we started writing a simple cli here:
> https://github.com/utilitywarehouse/lhctl
> I thought to share it here in case it can be of any help to anyone :)) It is really simple but enough to enable/disable nodes, scale volumes and drain replicas of nodes for the moment.

This repository is now archived.

**Comment by WillNilges** [comment]
Don't mean to necrobump, but is anyone working on this still?

**Comment by yasker** [comment]
@WillNilges We're planning for Kubernetes native API for v1.3. So `kubectl` can be the CLI for Longhorn.

**Comment by WillNilges** [comment]
That is absolutely _sick_. Do you have any idea when that'll be ready? Super exciting!

**Comment by yasker** [comment]
@WillNilges v1.3 is scheduled for Q1 2022 at the moment.

**Comment by innobead** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Main-Board-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/613?planning-poker) with ZenHub @jenting @PhanLe1010 @shuo-wu @joshimoo

**Comment by anthony-maxar** [comment]
We have Rancher support and this would save our sanity!!!!!!!

**Comment by innobead** [comment]
prefer https://github.com/longhorn/longhorn/issues/7927. closing this.
