### ISSUE TITLE
[BUG] test_dr_volume_with_restore_command_error failed

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#6130]
## Describe the bug (🐛 if you encounter this issue)

The test case `test_dr_volume_with_restore_command_error` is intermittently failing on both `master-head` and `v1.5.x-head` branches. The DR volume status is being displayed as `Faulted`.

```python
>       wait_for_volume_restoration_start(client, dr_volume_name, b2.name)

test_ha.py:1689: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common.py:4350: in wait_for_volume_restoration_start
    wait_for_volume_status(client, volume_name,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

client = <longhorn.Client object at 0x7faccd4516a0>, name = 'longhorn-testvol-yawbqn-dr', key = 'state'
value = 'attached', retry_count = 150

    def wait_for_volume_status(client, name, key, value,
                               retry_count=RETRY_COUNTS):
        wait_for_volume_creation(client, name)
        for i in range(retry_count):
            volume = client.by_id_volume(name)
            if volume[key] == value:
                break
            time.sleep(RETRY_INTERVAL)
>       assert volume[key] == value, f" value={value}\n. \
                volume[key]={volume[key]}\n. volume={volume}"
E       AssertionError:  value=attached
E       .             volume[key]=detached
E       . volume={'accessMode': 'rwo', 'backendStoreDriver': 'longhorn', 'backingImage': '', 'backupCompressionMethod': 'lz4', 'backupStatus': [], 'cloneStatus': {'snapshot': '', 'sourceVolume': '', 'state': ''}, 'conditions': {'restore': {'lastProbeTime': '', 'lastTransitionTime': '2023-06-15T06:00:33Z', 'message': 'All replica restore failed and the volume became Faulted', 'reason': 'RestoreFailure', 'status': 'False'}, 'scheduled': {'lastProbeTime': '', 'lastTransitionTime': '2023-06-15T06:00:10Z', 'message': '', 'reason': '', 'status': 'True'}, 'toomanysnapshots': {'lastProbeTime': '', 'lastTransitionTime': '2023-06-15T06:00:10Z', 'message': '', 'reason': '', 'status': 'False'}}, 'controllers': [{'actualSize': '159383552', 'address': '', 'currentImage': '', 'endpoint': '', 'engineImage': 'longhornio/longhorn-engine:v1.5.0-rc2', 'hostId': '', 'instanceManagerName': '', 'isExpanding': False, 'lastExpansionError': '', 'lastExpansionFailedAt': '', 'lastRestoredBackup': '', 'name': 'longhorn-testvol-yawbqn-dr-e-6a691bda', 'requestedBackupRestore': 'backup-f8cd5acdedd249ac', 'running': False, 'size': '1073741824', 'unmapMarkSnapChainRemovedEnabled': False}], 'created': '2023-06-15 06:00:09 +0000 UTC', 'currentImage': 'longhornio/longhorn-engine:v1.5.0-rc2', 'dataLocality': 'disabled', 'dataSource': '', 'disableFrontend': False, 'diskSelector': [], 'encrypted': False, 'engineImage': 'longhornio/longhorn-engine:v1.5.0-rc2', 'fromBackup': 'nfs://longhorn-test-nfs-svc.default:/opt/backupstore?backup=backup-d7b5e622c7434813&volume=longhorn-testvol-yawbqn-std', 'frontend': '', 'kubernetesStatus': {'lastPVCRefAt': '2023-06-15T06:00:04Z', 'lastPodRefAt': '2023-06-15T06:00:04Z', 'namespace': 'default', 'pvName': '', 'pvStatus': '', 'pvcName': 'longhorn-testvol-yawbqn-std-pvc', 'workloadsStatus': [{'podName': 'longhorn-testvol-yawbqn-std-pod', 'podStatus': 'Running', 'workloadName': '', 'workloadType': ''}]}, 'lastAttachedBy': '', 'lastBackup': 'backup-f8cd5acdedd249ac', 'lastBackupAt': '2023-06-15T06:00:30Z', 'migratable': False, 'name': 'longhorn-testvol-yawbqn-dr', 'nodeSelector': [], 'numberOfReplicas': 3, 'offlineReplicaRebuilding': 'disabled', 'offlineReplicaRebuildingRequired': False, 'purgeStatus': None, 'ready': False, 'rebuildStatus': [], 'recurringJobSelector': None, 'replicaAutoBalance': 'ignored', 'replicaSoftAntiAffinity': 'ignored', 'replicaZoneSoftAntiAffinity': 'ignored', 'replicas': [{'address': '', 'backendStoreDriver': 'longhorn', 'currentImage': '', 'dataPath': '/var/lib/longhorn/replicas/longhorn-testvol-yawbqn-dr-841000ca', 'diskID': 'd433bb4e-1e0d-4309-ae21-a8843b497ea0', 'diskPath': '/var/lib/longhorn/', 'engineImage': 'longhornio/longhorn-engine:v1.5.0-rc2', 'failedAt': '2023-06-15T06:00:33Z', 'hostId': 'ip-10-0-2-134', 'instanceManagerName': '', 'mode': '', 'name': 'longhorn-testvol-yawbqn-dr-r-17e46904', 'running': False}, {'address': '', 'backendStoreDriver': 'longhorn', 'currentImage': '', 'dataPath': '/var/lib/longhorn/replicas/longhorn-testvol-yawbqn-dr-5a47bf71', 'diskID': '74124f91-977f-4413-adfd-93ba220f9141', 'diskPath': '/var/lib/longhorn/', 'engineImage': 'longhornio/longhorn-engine:v1.5.0-rc2', 'failedAt': '2023-06-15T06:00:33Z', 'hostId': 'ip-10-0-2-190', 'instanceManagerName': '', 'mode': '', 'name': 'longhorn-testvol-yawbqn-dr-r-28137cdb', 'running': False}, {'address': '', 'backendStoreDriver': 'longhorn', 'currentImage': '', 'dataPath': '/var/lib/longhorn/replicas/longhorn-testvol-yawbqn-dr-725f8ba7', 'diskID': '2bd94598-1fe2-47db-b95e-b52cd21d5edd', 'diskPath': '/var/lib/longhorn/', 'engineImage': 'longhornio/longhorn-engine:v1.5.0-rc2', 'failedAt': '2023-06-15T06:00:33Z', 'hostId': 'ip-10-0-2-252', 'instanceManagerName': '', 'mode': '', 'name': 'longhorn-testvol-yawbqn-dr-r-42d861ad', 'running': False}], 'restoreInitiated': True, 'restoreRequired': True, 'restoreStatus': [], 'restoreVolumeRecurringJob': 'ignored', 'revisionCounterDisabled': False, 'robustness': 'faulted', 'shareEndpoint': '', 'shareState': '', 'size': '1073741824', 'snapshotDataIntegrity': 'ignored', 'staleReplicaTimeout': 0, 'standby': True, 'state': 'detached', 'unmapMarkSnapChainRemoved': 'ignored', 'volumeAttachment': {'attachments': {'volume-restore-controller-longhorn-testvol-yawbqn-dr': {'attachmentID': 'volume-restore-controller-longhorn-testvol-yawbqn-dr', 'attachmentType': 'volume-restore-controller', 'conditions': [{'lastProbeTime': '', 'lastTransitionTime': '2023-06-15T06:00:33Z', 'message': '', 'reason': '', 'status': 'False'}], 'nodeID': 'ip-10-0-2-252', 'parameters': {'disableFrontend': 'true'}, 'satisfied': False}}, 'volume': 'longhorn-testvol-yawbqn-dr'}}

common.py:1844: AssertionError

```
![Screenshot_20230615_135925](https://github.com/longhorn/longhorn/assets/104337648/2852ab41-9124-487f-bfab-92735d878feb)
![Screenshot_20230615_135934](https://github.com/longhorn/longhorn/assets/104337648/4e4fb34d-abb9-4946-b290-59c02976c26a)

## To Reproduce

https://ci.longhorn.io/job/public/job/v1.5.x/job/v1.5.x-longhorn-tests-sles-amd64/
Verify test result of  `test_dr_volume_with_restore_command_error`

## Expected behavior

We should have consistent test results on all distro.

## Log or Support bundle

[c.zip](https://github.com/longhorn/longhorn/files/11753488/c.zip)

## Environment

 - Longhorn version: v1.5.0-rc2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:v1.25.9+k3s1
   - Number of management node in the cluster:1
   - Number of worker node in the cluster:3
 - Node config
   - OS type and version: SLES 15.4
   - CPU per node: 4
   - Memory per node: 16G
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):AWS
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
@roger-ryao do you mean this case is flaky?

**Comment by innobead** [comment]
@mantissahz remember to update the status correctly, since you are working on that.

**Comment by mantissahz** [comment]
@roger-ryao, @yangchiu Does this issue only happen at nfs/cifs type backup target?

**Comment by yangchiu** [comment]
> @roger-ryao, @yangchiu Does this issue only happen at nfs/cifs type backup target?

No, it happens at s3 backup store too. Like: https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/504/testReport/tests/test_ha/test_dr_volume_with_restore_command_error_s3_/ and https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/511/testReport/tests/test_ha/test_dr_volume_with_restore_command_error_s3_/

**Comment by mantissahz** [comment]
Analysis update:
1. When we try to back up a small size of a snapshot, the backup might be quickly completed.
And it will make the backup volume to set `backup.Spec.SyncRequestedAt` first and change the backup.
2. This backup would update its status for the first time but it would be conflicted for backup volume changing this backup and re-queue the backup.
3. Re-queueing the backup makes the second time to store the backup on the remote backup target.
4. The first time backup is quickly completed and trigger the DR volume to restore the backup.
5. The second time backup would make backup.cfg initialized again
6. Sometimes `backupstore.InspectBackup` would return it as a in-progress backup and the DR volume would be failed if backup.cfg was initializing.

**Comment by innobead** [comment]
The issue was passed in today's build? https://ci.longhorn.io/job/public/job/v1.5.x/job/v1.5.x-longhorn-tests-sles-amd64/lastCompletedBuild/testReport/tests/test_ha/test_dr_volume_with_restore_command_error_s3_/

**Comment by innobead** [comment]
> The issue was passed in today's build? https://ci.longhorn.io/job/public/job/v1.5.x/job/v1.5.x-longhorn-tests-sles-amd64/lastCompletedBuild/testReport/tests/test_ha/test_dr_volume_with_restore_command_error_s3_/

@mantissahz explained to me, this is a race issue, but it would have chances to hit.

**Comment by mantissahz** [comment]
Sure @innobead.

- on control plane side
1. When a new backup created, it would create a monitor and then sync the backup status in `syncWithMonitor` with [changing the backup volume CR](https://github.com/longhorn/longhorn-manager/blob/master/controller/backup_controller.go#L685-L688) if the backup is competed and `triggers the DR volume restoration`.
2. And backup volume controller will [change this backup CR](https://github.com/longhorn/longhorn-manager/blob/master/controller/backup_volume_controller.go#L384-L392)
3. After this backup finished the `reconcile`, it would try to update the backup status, and it causes a conflict and re-queue this backup
4. This backup will re-run the `reconcile` and [start a new monitor and a new SnapshotBackup](https://github.com/longhorn/longhorn-manager/blob/master/engineapi/backup_monitor.go#L77-L89) because last time update failed

- on engine side
1. DR volume restoration is starting and second time `SnapshotBackup` is starting concurrently
2. `SnapshotBackup` will finally [initialize backup.cfg again](https://github.com/longhorn/backupstore/blob/master/deltablock.go#L495-L509) and `CreateTime` will be empty
3.  DR volume restoration would be failed when [it check the backup.cfg and `CreateTime` is empty.](https://github.com/longhorn/backupstore/blob/master/inspect.go#L56-L58)

**Comment by roger-ryao** [comment]
**Verified on v1.5.x-head 20230620**

- longhorn v1.5.x-head https://github.com/longhorn/longhorn/commit/e651a6a368bc521c71b6383d0ba99cb54a973185
- longhorn-manager v1.5.x-head https://github.com/longhorn/longhorn-manager/commit/f9cecd8a33e38afb61a8c95479ad9ec93c1de6ae

**Verified on master-head 20230620**

- longhorn master-head https://github.com/longhorn/longhorn/commit/a601ecc4684435093a9d92dd05621b837d77a5ad
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/a3b16b886e5bb0ed9faac862c70042a06c19998f

**Result Passed**

The `test_dr_volume_with_restore_command_error` test has passed.
The v1.5.x-head test results : https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4263/
The master-head test results : https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4262/
![Uploading Screenshot_20230620_142533.png…]()
