### ISSUE TITLE
[BUG] Volume gets stuck in an unknown state forever if created in an engine not fully deployed environment

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6131]
## Describe the bug (🐛 if you encounter this issue)

Test case `test_engine_image_not_fully_deployed_perform_auto_upgrade_engine` randomly fails on `master-head` and `v1.5.x-head`. It can be reproduced within 5 times rerun.

The created volume gets stuck in an unknown state forever as following:
![Screenshot from 2023-06-15 14-35-08](https://github.com/longhorn/longhorn/assets/5709208/ce36c6d3-fde2-4bcf-9c98-47a68e7101b0)
```
$ kubectl get volume vol-1 -n longhorn-system -o yaml
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  creationTimestamp: "2023-06-15T06:32:31Z"
  finalizers:
  - longhorn.io
  generation: 1
  labels:
    longhornvolume: vol-1
    recurring-job-group.longhorn.io/default: enabled
    setting.longhorn.io/snapshot-data-integrity: ignored
  name: vol-1
  namespace: longhorn-system
  resourceVersion: "3278"
  uid: 9f460073-077c-4fe3-93d7-3756f2df4db0
spec:
  Standby: false
  accessMode: rwo
  backendStoreDriver: longhorn
  backingImage: ""
  backupCompressionMethod: lz4
  dataLocality: disabled
  dataSource: ""
  disableFrontend: false
  diskSelector: []
  encrypted: false
  engineImage: longhornio/longhorn-engine:master-head
  fromBackup: ""
  frontend: blockdev
  lastAttachedBy: ""
  migratable: false
  migrationNodeID: ""
  nodeID: ""
  nodeSelector: []
  numberOfReplicas: 2
  offlineReplicaRebuilding: disabled
  replicaAutoBalance: ignored
  replicaSoftAntiAffinity: ignored
  replicaZoneSoftAntiAffinity: ignored
  restoreVolumeRecurringJob: ignored
  revisionCounterDisabled: false
  size: "3221225472"
  snapshotDataIntegrity: ignored
  staleReplicaTimeout: 0
  unmapMarkSnapChainRemoved: ignored
status:
  actualSize: 0
  cloneStatus:
    snapshot: ""
    sourceVolume: ""
    state: ""
  conditions: null
  currentImage: ""
  currentMigrationNodeID: ""
  currentNodeID: ""
  expansionRequired: false
  frontendDisabled: false
  isStandby: false
  kubernetesStatus:
    lastPVCRefAt: ""
    lastPodRefAt: ""
    namespace: ""
    pvName: ""
    pvStatus: ""
    pvcName: ""
    workloadsStatus: null
  lastBackup: ""
  lastBackupAt: ""
  lastDegradedAt: ""
  offlineReplicaRebuildingRequired: false
  ownerID: ip-10-0-1-196
  pendingNodeID: ""
  remountRequestedAt: ""
  restoreInitiated: false
  restoreRequired: false
  robustness: ""
  shareEndpoint: ""
  shareState: ""
  state: ""
```

## To Reproduce

Run test case `test_engine_image_not_fully_deployed_perform_auto_upgrade_engine` 

## Log or Support bundle

[supportbundle_16bf4154-d3ec-49bf-8380-64502d188c24_2023-06-15T06-37-26Z.zip](https://github.com/longhorn/longhorn/files/11753704/supportbundle_16bf4154-d3ec-49bf-8380-64502d188c24_2023-06-15T06-37-26Z.zip)

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by PhanLe1010** [comment]
From the support bundle, the volume is stuck due to this error:

```
2023-06-15T06:32:32.462648537Z time="2023-06-15T06:32:32Z" level=error msg="Dropping Longhorn volume longhorn-system/vol-1 out of the queue" controller=longhorn-volume error="failed to sync longhorn-system/vol-1: failed to reconcile engine/replica state for vol-1: BUG: found the second active engine vol-1-e-bc054650 besides vol-1-e-489ca910" node=ip-10-0-1-196
```

Some how we created 2 engines for the volume and Longhorn volume-controller refused to process that volume

**Comment by PhanLe1010** [comment]
**Root cause analysis:**

I use longhorn-manager master-head with extra tracing logs added as https://github.com/PhanLe1010/longhorn-manager/commit/7edf9099e8bbaf745adea0893595da5379093503 . The rest is reproduced one out of ~12 runs in my case

Tracing the vol-1 when it is created the first time, I noticed that there are 2 Longhorn managers process vol-1 in the very first sync loop. The first manager sync the volume and create engine and replicas:
```
2023-06-15T23:11:47.985791094Z time="2023-06-15T23:11:47Z" level=info msg="Volume got new owner phan-v140-pool2-dfe0dac5-j4r2c" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=phan-v140-pool2-dfe0dac5-j4r2c owner=phan-v140-pool2-dfe0dac5-frncz state= volume=vol-1
2023-06-15T23:11:47.985866282Z time="2023-06-15T23:11:47Z" level=info msg="============> first time creation engine" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=phan-v140-pool2-dfe0dac5-j4r2c owner=phan-v140-pool2-dfe0dac5-j4r2c state= volume=vol-1
2023-06-15T23:11:47.985871957Z time="2023-06-15T23:11:47Z" level=info msg="============> creating engine vol-1-e-0c6a77c0 with isNewEngine true" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=phan-v140-pool2-dfe0dac5-j4r2c owner=phan-v140-pool2-dfe0dac5-j4r2c state= volume=vol-1
```
The second manager is also syncing this volume at the same time:
```
2023-06-15T23:11:47.909363133Z time="2023-06-15T23:11:47Z" level=info msg="Volume got new owner phan-v140-pool2-dfe0dac5-frncz" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=phan-v140-pool2-dfe0dac5-frncz owner= state= volume=vol-1
2023-06-15T23:11:48.060386302Z time="2023-06-15T23:11:48Z" level=info msg="============> first time creation engine" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=phan-v140-pool2-dfe0dac5-frncz owner=phan-v140-pool2-dfe0dac5-frncz state= volume=vol-1
2023-06-15T23:11:48.060524317Z time="2023-06-15T23:11:48Z" level=info msg="============> creating engine vol-1-e-a1061ee4 with isNewEngine true" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=phan-v140-pool2-dfe0dac5-frncz owner=phan-v140-pool2-dfe0dac5-frncz state= volume=vol-1
```

This race leads to the volume has 2 active engines thus hit a deadlock situation.

I think that with the current onwerID logic, it is possible to have 2 Longhorn managers to sync an object at the same time during the ownership transition period. I think that this problem is not a regression and it should appear in older Longhorn version as well. I will do some more testing to confirm

**Comment by PhanLe1010** [comment]
I am seeing a similar problem in 1.4.2 in which we create double the amount of replicas (the result of 2 sync runs on 2 Longhorn managers for a new volume). So this is not a regression.

Btw, fixing this one will be tough with the current onwerID logic

**Comment by innobead** [comment]
Not a regression. Let's handle this in 1.6.

**Comment by yangchiu** [comment]
Just for reference, there are several similar test cases:
`test_ha.test_engine_image_not_fully_deployed_perform_auto_upgrade_engine`
`test_ha.test_engine_image_not_fully_deployed_perform_engine_upgrade`
`test_ha.test_engine_image_not_fully_deployed_perform_replica_scheduling`
Probably failed for the same cause.

And they're all possible to happen in `master-head`, `v1.5.x-head` and `v1.4.x-head`.

**Comment by PhanLe1010** [comment]
Update: This PR has addressed this issue https://github.com/longhorn/longhorn-manager/pull/2180. 

Moving this one to ready-for-testing @longhorn/qa Can you help to re-test?

**Comment by PhanLe1010** [comment]
Test plan:

Run the following test 10 times:

* test_ha.test_engine_image_not_fully_deployed_perform_auto_upgrade_engine
* test_ha.test_engine_image_not_fully_deployed_perform_engine_upgrade
* test_ha.test_engine_image_not_fully_deployed_perform_replica_scheduling
* test_engine_image_not_fully_deployed_perform_auto_upgrade_engine

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 27101bb) by running test cases `test_ha.test_engine_image_not_fully_deployed_perform_auto_upgrade_engine`, `test_ha.test_engine_image_not_fully_deployed_perform_engine_upgrade` and `test_ha.test_engine_image_not_fully_deployed_perform_replica_scheduling` for `50` times.

Test results:
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5380/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5381/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5382/
