### ISSUE TITLE
[TASK] Reduce BackupConcurrentLimit and RestoreConcurrentLimit default values 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6135]
## What's the task? Please describe

To avoid consuming too much computation and storage resources using default values, reduce BackupConcurrentLimit and RestoreConcurrentLimit default values. Users can adjust them on demand.

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

Add any other context or screenshots about the task request here.

**Comment by chriscchien** [comment]
Verified **pass** in 
- longhorn master(longhorn `27f482`, website `bcbdec`)
- longhorn v1.5.x(longhorn `428f1d`)

Default value of `backup-concurrent-limit` and `restore-concurrent-limit` changed to 2, both of them can be modified.
After this change, did not observe outstanding error of backup, restore on [master](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/526/#showFailuresLink), [v1.5.x](https://ci.longhorn.io/job/public/job/v1.5.x/job/v1.5.x-longhorn-tests-sles-amd64/16/) pipeline
