### ISSUE TITLE
[FEATURE] v2 data engine volume snapshot and revert

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6137]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

SPDK volumes support volume snapshot

## Describe the solution you'd like

A clear and concise description of what you want to happen

**Comment by shuo-wu** [comment]
Currently, the key, or the main blocker, is the snapshot revert feature.

To implement the snapshot revert feature, we may need to rely on the existing SPDK API `bdev_lvol_clone`. But this clone API means creating a new head lvol behind the new snapshot and removing the old head. It is insufficient for the revert feature:
1. Each Longhorn replica uses **the head lvol UUID as the replica UUID.** This should be **immutable**. But in SPDK we cannot clone/create a new head lvol with a specified UUID.
2. In SPDK, removing the head lvol would lead to the whole snapshot chain cleanup. It's not acceptable.

Sorry for forgetting writing down the detail in this ticket. cc @DamiaSan

**Comment by DamiaSan** [comment]
It is not true that when you delete the head lvol all snapshots are deleted too, they remain and the reason is that you can always create a clone of them.
What about the UUID, could you explain better the reason why we can't use lvol name?
However, a possible solution is to pass an optional argument to `bdev_lvol_clone` with the wanted UUID. Obviously the old head lvol with that UUID must be delete before.
@l-mb What do You think?

**Comment by shuo-wu** [comment]
@derekbit How do think making the replica UUID mutable and relying on the replica name as the unique identifier instead?

**Comment by derekbit** [comment]
> Maybe use <user_name>/<volume_name> as lvol name?

@DamiaSan 
Sorry, what's user_name here?


> @derekbit How do think making the replica UUID mutable and relying on the replica name as the unique identifier instead?

Using replica name as UUID for the replica sounds good to me.

> Users can create volumes with the same name.

I think we can check the name in the validating webhook to avoid running into the issue.

**Comment by derekbit** [comment]
cc @james-munson

**Comment by DamiaSan** [comment]
> Sorry, what's user_name here?

The name, the identity or whatever identify the user that create the volume.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240111**

- longhorn master-head https://github.com/longhorn/longhorn/commit/1d755966981aab582afa978c739e04940172cbef
- longhorn-spdk-engine main https://github.com/longhorn/longhorn-spdk-engine/commit/64a2aeada8ee68cd13448e5e313aec56de7d5f75
- longhorn-instance-manager master-head https://github.com/longhorn/longhorn-instance-manager/commit/ae1b763c1f6d644bb37a43e1e23c435f14e555c2


**The test steps**

1. https://github.com/longhorn/longhorn/issues/6137#issuecomment-1884101011

**Result passed**
