### ISSUE TITLE
[FEATURE] v2 volume supports volume backup/restore

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6138]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

SPDK volumes support volume incremental/delta backup, and full/incremental (DR) restore. 

Sub-tasks
- [x] LEP
   - https://github.com/longhorn/longhorn/pull/6480
- [x] SPDK bdev_lvol_get_fragmap JSON-SPDK method
   - https://github.com/longhorn/spdk/pull/17
- [x] SPDK lvol get and set xattr operations and snapshot lvol creation timestamp
   - https://github.com/longhorn/longhorn/issues/6604
- [x] Move common functions for backup to backupstore lib
   - https://github.com/longhorn/longhorn/issues/6514
- [x] Abstract the disk/lvol file operations in backupstore
   - https://github.com/longhorn/longhorn/issues/6576 
- [x] Backup implementation
- [x] Restore implementation
    - [x] Full restore
    - ~~[ ] Incremental restore (not in the scope of the ticket)~~
- [x] UI improvement
    - https://github.com/longhorn/longhorn/issues/6597

## Describe the solution you'd like

A clear and concise description of what you want to happen

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 970ba44) following [the test plan](https://github.com/longhorn/longhorn/issues/6138#issuecomment-1708355748).

**Comment by khushboo-rancher** [comment]
@yangchiu Have we tested the below scenarios:
**Backup**:
1. Interrupting the v2 backup by deleting the replica responsible for backup when backup is in progress.
2. Taking two v2 volumes's backups together.
3. Triggering two v2 backups from two snapshots of same volume together.
4. v2 Backup creation and backup deletion at same time.
5. V2 Backup on S3 and NFS backupstore.
6. Corrupting the backups on backupstore and verifying the state in Longhorn.
7. Taking Backup after a failed backup creation.
8. Some similar edge cases as above.

**Restore**:
1. Restoring v1 volume backup crated in 1.5.x to v2 volume.
2. Interrupt v2 restore by crashing the IM or rebooting the attached node.
3. Restoring of v2 volume and deleting the same backup at same time.
4. Consequently restoring after the step3.
5. Restoring backup on another cluster.
6. Randomly delete some blocks on backup in backupstore and try to restore the corrupted backup and restoring of subsequent backup.

**Comment by yangchiu** [comment]
> **Backup**:
> 
>     1. Interrupting the v2 backup by deleting the replica responsible for backup when backup is in progress.

https://github.com/longhorn/longhorn/issues/7573 https://github.com/longhorn/longhorn/issues/7574 https://github.com/longhorn/longhorn/issues/7575

> 
>     2. Taking two v2 volumes's backups together.

**Pass**
> 
>     3. Triggering two v2 backups from two snapshots of same volume together.

**Pass**
> 
>     4. v2 Backup creation and backup deletion at same time.

**Pass**
> 
>     5. V2 Backup on S3 and NFS backupstore.

**Pass**
> 
>     6. Corrupting the backups on backupstore and verifying the state in Longhorn.

https://github.com/longhorn/longhorn/issues/7583
> 
>     7. Taking Backup after a failed backup creation.

**Pass**
> 
>     8. Some similar edge cases as above.
> 
> 
> **Restore**:
> 
>     1. Restoring v1 volume backup crated in 1.5.x to v2 volume.

**Pass**
> 
>     2. Interrupt v2 restore by crashing the IM or rebooting the attached node.

https://github.com/longhorn/longhorn/issues/7579 https://github.com/longhorn/longhorn/issues/7581 

> 
>     3. Restoring of v2 volume and deleting the same backup at same time.
>     4. Consequently restoring after the step3.

https://github.com/longhorn/longhorn/issues/7584
> 
>     5. Restoring backup on another cluster.

**Pass**
> 
>     6. Randomly delete some blocks on backup in backupstore and try to restore the corrupted backup and restoring of subsequent backup.

https://github.com/longhorn/longhorn/issues/7583

**Comment by innobead** [comment]
@yangchiu For the above tests, if not covered in automation yet, create a ticket for that.

**Comment by yangchiu** [comment]
Related issues tracked by https://github.com/longhorn/longhorn/issues/6138#issuecomment-1882182519. Close this for now.
