### ISSUE TITLE
Disk Pressure due to high allocation

### ISSUE THREAD

**Issue by wopl** [longhorn/longhorn#6144]
## Question
> Disk Pressure due to high allocation

## Environment

 - Longhorn version: 1.40
 - Kubernetes version: 1.26 (k3s)
 - Node config
   - Ubuntu 22.04

## Additional context

For some unknown reason I get some disk-pressure. For most applications I distribute 3 Replicas across the three nodes. Therefore Disk space should be sufficient (as seen on the other nodes).
The shown 309 allocations cannot be found on disk at /home/longhorn

Could anyone guide me to figure out the root reason and potentially garbage collect this issue?
![longhorn](https://github.com/longhorn/longhorn/assets/6441547/2f1bd081-364a-4e15-b5df-1f020a35ddb8)

**Comment by derekbit** [comment]
> Will upgrade to Longhorn 1.4.2 soon. So the issue will not re-occur?

If you apply the workaround in https://github.com/longhorn/longhorn/issues/5762#issue-1669167403, the issue should not happen when upgrading to v1.4.2.
