### ISSUE TITLE
[BUG] Volume can not attach on Oracle Linux

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#6150]
## Describe the bug (🐛 if you encounter this issue)

While doing v1.5.0 regression distor test on Oracle Linux 8.6, the instance setup up correctly but most test cases [failed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4122/). 
After manually reproduce success, figured out that Oracle Linux also hit issue [5990](https://github.com/longhorn/longhorn/issues/5990), and when applying the workaround mentioned [here](https://github.com/longhorn/longhorn/issues/5990#issuecomment-1582731394), issue of volume can not attach resolved.

However, when running core test on that Oracle Linux cluster, one cores test case `test_single_replica_failed_during_engine_start` can not pass, logged this issue for tracking. (Observed that replica rebuild will never complete make test case fail) 

Need verify again after issue [5990](https://github.com/longhorn/longhorn/issues/5990) resolved

![image](https://github.com/longhorn/longhorn/assets/73337386/9e13cdb5-3b5f-4c3a-a3ae-b9c15a22a621)

## To Reproduce

1. Setup Oracle Linux cluster
2. Setup Longhorhorn
3. Apply the work [around](https://github.com/longhorn/longhorn/issues/5990#issuecomment-1582731394) to reslove volume can not attach issue
4. Run regression on Oracle Linux

## Expected behavior

Core test all passed

## Log or Support bundle

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4122/

## Environment

 - Longhorn version: v1.5.0-rc2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.27.1+k3s1
   - OS type and version: Oracle Linux 8.6 ami-0c13f3910c11238bb
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster:

## Additional context

N/A

**Comment by innobead** [comment]
@ChanYiLin please check this with @chriscchien . It should be env issue. Thanks.

**Comment by innobead** [comment]
@chriscchien for any issue opened during the release testing, please add it to the release, currently, it's 1.5.0. I will see if we should fix it in 1.5.0 or a later version. 

cc @longhorn/qa

**Comment by innobead** [comment]
@chriscchien if it's related to the SELinux issue due to the recent container-selinux profile package update, please try the solution https://longhorn.io/kb/troubleshooting-volume-attachment-fails-due-to-selinux-denials/ instead.

**Comment by chriscchien** [comment]
Hi @innobead , yes I had tried the solution you mentioned. This solution solved the volume can not attach issue on Oracle Linux.

After I applied the solution, I run core tests on that cluster. All test case passed except `test_single_replica_failed_during_engine_start` and observed replica rebuilding fail, If necessary, I can setup environment for debug. thank you.

**Comment by innobead** [comment]
Ok, thanks. 

Then what you should is close this issue because it's an invalid and known issue. Validating `test_single_replica_failed_during_engine_start` instead. If it's a real issue, create a bug. If not but flaky, create a test issue to improve that. 

cc @longhorn/qa

**Comment by innobead** [comment]
However, this issue would make QA unable to run any testing pipeline of RHEL downstream distro if this known issue is not fixed before running test cases, right?
