### ISSUE TITLE
[IMPROVEMENT] Instance manager spdk_tgt resilience

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6155]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Somehow it's possible that `spdk_tgt` crashed and spdk volume gets stuck in `attaching` state:
```
Error starting pvc-1deb58b5-c8b8-4cf2-bb10-02c83877abd6-e-7b4b0d54: 
failed to create instance: 
rpc error: code = Unknown desc = failed to start SPDK engine: 
rpc error: code = Unknown desc = error sending message, id 70374, method bdev_raid_create, 
params {pvc-1deb58b5-c8b8-4cf2-bb10-02c83877abd6-e-7b4b0d54 1 0 [pvc-1deb58b5-c8b8-4cf2-bb10-02c83877abd6-r-8eb29e9bn1 disk-1/pvc-1deb58b5-c8b8-4cf2-bb10-02c83877abd6-r-b7cafc48]}: 
write unix @->/var/tmp/spdk.sock: write: broken pipe
```

It's hard to reproduce and currently unable to find a reliable way to reproduce it. The possible reproducing steps are:
1. Create a 3-nodes k3s cluster, enable spdk, and add block type disk for each node  
2. Create spdk volume from Longhorn UI, and create PV/PVC for this volume from Longhorn UI. But forget to fill in the right storage class name, leave it blank
3. Create a workload to use this volume, the volume will be stuck in `attaching` state:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
spec:
  containers:
    - name: sleep
      image: busybox
      imagePullPolicy: IfNotPresent
      args: ["/bin/sh", "-c", "while true;do date;sleep 5; done"]
      volumeMounts:
        - name: pod-data
          mountPath: /data
  volumes:
    - name: pod-data
      persistentVolumeClaim:
        claimName: test-1
```
4. Create spdk storageclass:
```
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/v2/storageclass.yaml
```
5. Create a statefulset using spdk volume:
```
# statefulset.yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: statefulset-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-v2-data-engine
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-statefulset
  namespace: default
spec:
  selector:
    matchLabels:
      app: test-statefulset
  serviceName: test-statefulset
  replicas: 1
  template:
    metadata:
      labels:
        app: test-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      nodeSelector:
        node-role.kubernetes.io/control-plane: 'true'
      containers:
        - image: busybox
          imagePullPolicy: IfNotPresent
          name: sleep
          args: ['/bin/sh', '-c', 'while true;do date;sleep 5; done']
          volumeMounts:
            - name: test-pod
              mountPath: /data
      volumes:
        - name: test-pod
          persistentVolumeClaim:
            claimName: statefulset-pvc

# kubectl apply -f statefulset.yaml
```
6. spdk volume can be created and attached, and the workload is running without problem, then write some data into the volume
7. Delete replicas of this volume from Longhorn UI
8. Scale down the statefulset to 0 to detach the volume
9. The volume can be attached automatically and replica rebuilding triggered
10. After all replicas rebuilt, the volume detached automatically
11. scale up the statefulset to 1 to attach the volume again => The volume gets stuck in attaching state forever with error message:
```
Error starting pvc-1deb58b5-c8b8-4cf2-bb10-02c83877abd6-e-7b4b0d54: 
failed to create instance: 
rpc error: code = Unknown desc = failed to start SPDK engine: 
rpc error: code = Unknown desc = error sending message, id 70374, method bdev_raid_create, 
params {pvc-1deb58b5-c8b8-4cf2-bb10-02c83877abd6-e-7b4b0d54 1 0 [pvc-1deb58b5-c8b8-4cf2-bb10-02c83877abd6-r-8eb29e9bn1 disk-1/pvc-1deb58b5-c8b8-4cf2-bb10-02c83877abd6-r-b7cafc48]}: 
write unix @->/var/tmp/spdk.sock: write: broken pipe
```

## Describe alternatives you've considered

Since it's hard to reproduce, we can improve the resilience of instance manager first instead of struggling to reproducing it.

## Additional context

Detailed support bundle and logs can be found in https://github.com/longhorn/longhorn/issues/6071

**Comment by derekbit** [comment]
To create "broken pipe" error, we can create and attach a volume with three replicas. Then, simply `kill -9 spdk_tgt` in one of instance manager pods. The SPDK service verify function will emit
```
[longhorn-instance-manager] time="2023-06-19T07:55:53Z" level=error msg="SPDK Server: failed to verify and update replica cache, will retry later" error="error sending message, id 70405, method bdev_lvol_get_lvstores, params { }: write unix @->/var/tmp/spdk.sock: write: broken pipe"
```

If running into `broken pipe` error, we can mark replicas and engines as `error`. Is it reasonable and feasible?

cc @shuo-wu @innobead

**Comment by DamiaSan** [comment]
Can you provide a coredump of `spdk_tgt` as suggested by @derekbit ? I need more details to understand the crash ...

**Comment by yangchiu** [comment]
> @yangchiu can you provide a coredump of `spdk_tgt` as suggested by @derekbit ? I need more details to understand the crash ...

The environment has been destroyed, but it would be appreciated if you can elaborate more on how/where can I get the coredump file so next time I encounter this I can keep it for you. Many thanks.

**Comment by DamiaSan** [comment]
To enable core dump on the machine, add following line to the file `/etc/security/limits.conf `:
```
* soft core unlimited
```
The path of the core dump file depends on the system you are using, but you can discover it reading the file `/proc/sys/kernel/core_pattern`. On my Tumbleweed (which uses `systemd`)  I have:
```
damiano@dhcppc11:~/Development/spdk> cat /proc/sys/kernel/core_pattern
|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h
```
and this means that core dump files will be stored in `/var/lib/systemd/coredump/`
However, if you read `man core` you can have all the details you need.

**Comment by yangchiu** [comment]
Tested on v1.5.x-head (longhorn-instance-manager 3cfa0eb). Hit volume stuck in `attaching` state issue again by following [the original test steps](https://github.com/longhorn/longhorn/issues/6155#issue-1763011758) 5 ~ 11. But I'm not sure if it's caused by the same condition we encountered before.

I followed [the steps](https://github.com/longhorn/longhorn/issues/6155#issuecomment-1597039912) to enable coredump before testing, but still not sure if it's generated correctly.

I keep the environment on `equinix`. The cluster is `yang-test-04` ~ `yang-test-06`. `yang-test-04` is the control plane. And Longhorn UI has a nodeport at 30007. @derekbit @DamiaSan I believe you can ssh access these machines if you can log into `equinix`.

Also left the support bundle here for reference:
[supportbundle_e8daae4a-108e-404b-8da6-8c9a0bed3bd1_2023-06-21T02-45-55Z.zip](https://github.com/longhorn/longhorn/files/11811825/supportbundle_e8daae4a-108e-404b-8da6-8c9a0bed3bd1_2023-06-21T02-45-55Z.zip)

**Comment by derekbit** [comment]
> Tested on v1.5.x-head (longhorn-instance-manager 3cfa0eb). Hit volume stuck in `attaching` state issue again by following [the original test steps](https://github.com/longhorn/longhorn/issues/6155#issue-1763011758) 5 ~ 11. But I'm not sure if it's caused by the same condition we encountered before.
> 
> I followed [the steps](https://github.com/longhorn/longhorn/issues/6155#issuecomment-1597039912) to enable coredump before testing, but still not sure if it's generated correctly.
> 
> I keep the environment on `equinix`. The cluster is `yang-test-04` ~ `yang-test-06`. `yang-test-04` is the control plane. And Longhorn UI has a nodeport at 30007. @derekbit @DamiaSan I believe you can ssh access these machines if you can log into `equinix`.
> 
> Also left the support bundle here for reference: [supportbundle_e8daae4a-108e-404b-8da6-8c9a0bed3bd1_2023-06-21T02-45-55Z.zip](https://github.com/longhorn/longhorn/files/11811825/supportbundle_e8daae4a-108e-404b-8da6-8c9a0bed3bd1_2023-06-21T02-45-55Z.zip)

Always hit the issue?

From the issue, the engine is in error state (which is expected as the implementation in the PR), but the volume is somehow   stuck at `attaching` state.
Need to check the logic in instance state transition.

**Comment by derekbit** [comment]
Before figuring out the root cause, the workaround is deleting the workload and recreate it.

**Comment by derekbit** [comment]
It looks longhorn-manager doesn't handle the case ([code](https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go#L1334))
```
e.Status.CurrentState == longhorn.InstanceStateError && v.Status.CurrentNodeID == "" 
```

From a resilience perspective, if a spdk volume is stuck in `attaching` state or the `spdk_tgt` is somehow broken. What a user can do for now is deleting the workload and detach the volume unlink the previous behavior (always undetachable). cc @yangchiu Can you help check this?

**Comment by yangchiu** [comment]
Somehow the original problematic statefulset/pod/volume is missing/disappeared. I repeat the same steps again ([original test steps](https://github.com/longhorn/longhorn/issues/6155#issue-1763011758) 5 ~ 11), hit the same issue.

**Comment by DamiaSan** [comment]
On all the 3 machines we don't have the correct value for the core dump creation:
```
root@yang-test-04:~# ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
...
```
The file `/etc/security/limits.conf` contains the right row, maybe haven't you rebooted the machine after having updated this file?
The correct value should be:
```
damiano@dhcppc11:~/Development/spdk> ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
...
```
We can also set this value with the command
```
ulimit -S -c unlimited
```
but it is related to the current session, it is not permanent

**Comment by innobead** [comment]
Let's focus on verifying if the crashed spdk tgt server can be restarted. For other resilience cases, create other issues to track instead if possible.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager deb1802) following [the test steps](https://github.com/longhorn/longhorn/issues/6155#issuecomment-1597374543). After killed the `spdk_tgt`, detach the volume can still trigger the offline rebuilding, and the data is intact.
