### ISSUE TITLE
Mount Failed in Kubernetes

### ISSUE THREAD

**Issue by arrowfeng** [longhorn/longhorn#616]
I create volume through longhorn UI, the state is detach before, I create PV/PVC based with the volume, now everything is ok, but when I create Deployment mounting this PVC in Kubernetes, then showing mount failed below, and volume's state become Faulted. 

![image](https://user-images.githubusercontent.com/20623365/60696657-490b8000-9f19-11e9-9059-cf38b15603e7.png)
![image](https://user-images.githubusercontent.com/20623365/60696648-43159f00-9f19-11e9-959c-d665c4bf4900.png)
![image](https://user-images.githubusercontent.com/20623365/60696635-35f8b000-9f19-11e9-88dc-e655654c9812.png)

![image](https://user-images.githubusercontent.com/20623365/60696563-d69aa000-9f18-11e9-9e31-4972ce7edbf1.png)

**Comment by arrowfeng** [comment]
I directively run doc's example,  and there is a samle problem.
kubectl create -f https://raw.githubusercontent.com/rancher/longhorn/master/examples/pvc.yaml
![image](https://user-images.githubusercontent.com/20623365/60701095-0a7fc080-9f2d-11e9-82d6-d8eba5a25ea9.png)
![image](https://user-images.githubusercontent.com/20623365/60701097-0eabde00-9f2d-11e9-981d-2116e9cf9b45.png)

**Comment by yasker** [comment]
What's the network connection between your Kubernetes nodes? Faulted volume normally because there is no way for the engine to connect to the replicas. You can check the manager log for details.

**Comment by arrowfeng** [comment]
the network is ok, I run a pod mounting pvc created by dynamic provisioner is right, but I firstly create static pvc/pv by longhorn ui, there is still a same  problem.
this is a manager's log below.
![image](https://user-images.githubusercontent.com/20623365/60763451-7b4ae800-a0a7-11e9-9a5e-743151ad1fd5.png)

**Comment by yasker** [comment]
@arrowfeng The replicas were disconnected from the engine very soon after it's started. Can you show the log a few lines earlier?

**Comment by arrowfeng** [comment]
![image](https://user-images.githubusercontent.com/20623365/60931381-01f00700-a2ec-11e9-80d1-087daf3b15f1.png)

![image](https://user-images.githubusercontent.com/20623365/60931444-395eb380-a2ec-11e9-9523-4bd681e804d1.png)

**Comment by yasker** [comment]
@arrowfeng Yeah, it's network connection error. The data cannot flow from the engine to replicas, caused timeout.

**Comment by arrowfeng** [comment]
thank you
