### ISSUE TITLE
[IMPROVEMENT] Determine number of replica/engine port count in longhorn-manager (control plane) instead

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6163]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Determine number of replica/engine port count in longhorn-manager (control plane) instead

**Comment by chriscchien** [comment]
Verified **pass** in 
- longhorn master(`ec130d`)
- lomghorn v1.5.x(`c8092b`)

`portStart` and `portEnd` appeared in `status.instanceReplicas` and `status.instanceEngines` on both v1, v2 volume
