### ISSUE TITLE
[BUG] When a v2 volume is attached in maintenance mode, removing a replica will lead to volume stuck in attaching-detaching loop 

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#6166]
## Describe the bug (🐛 if you encounter this issue)

This bug is triggered in v2 volume and under maintenance mode only.

## To Reproduce

1. Create a v2 volume
2. Attach it with maintenance mode
3. Delete one replica => The volume get stuck in attaching-detaching loop 

## Expected behavior

The rebuilding should be triggered instead.

## Environment

 - Longhorn version: v1.5.0-master-head (06/20/2023)
 - Number of Longhorn volumes in the cluster: 2

## Additional context

cc @derekbit

**Comment by innobead** [comment]
Is there any side effect from recent fixes?

**Comment by chriscchien** [comment]
Hi @derekbit,

Case 1 passed on master and v1.5.x. But in case 2, after I perform step 6, eventually the volume become healthy which not match the description in step8.

**Comment by derekbit** [comment]
That means the rebuilding is finished. Probably need a bigger data size.

**Comment by chriscchien** [comment]
Verified **pass** in below branches with test [steps](https://github.com/longhorn/longhorn/issues/6166#issuecomment-1598361340)
- longhorn master(longhorn-manager `deb180`)
- longhorn v1.5.x(longhorn-manager `c8092b`)

Case 1 and case 2(write 10GB data) all worked as expected in master and v1.5.x branches.
