### ISSUE TITLE
[TEST] Apply selinux workaround to RHEL, RockyLinux and Oracle

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6168]
## What's the test to develop? Please describe

Temporarily apply [this workaround](https://github.com/longhorn/longhorn/pull/6082) to RHEL, RockyLinux and Oracle to fix the potential issue https://longhorn.io/kb/troubleshooting-volume-attachment-fails-due-to-selinux-denials/#applicable-versions caused by iscsiadm permission issue.

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

https://github.com/longhorn/longhorn/issues/5627
https://github.com/longhorn/longhorn/issues/6074
https://github.com/longhorn/longhorn/issues/6150

https://github.com/longhorn/longhorn/pull/6082
https://github.com/longhorn/longhorn-tests/pull/1424

**Comment by yangchiu** [comment]
The `selinux` setup and the `rke2` setup never work correctly before. Need more time to check and set them right. cc @innobead

**Comment by innobead** [comment]
Surprising, NP. Then let's make it work later. 

cc @longhorn/qa
