### ISSUE TITLE
[BUG] Misleading offline rebuilding hint if offline rebuilding is not enabled

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6169]
## Describe the bug (🐛 if you encounter this issue)

If a `volume.Status.OfflineReplicaRebuildingRequired` is `false`, no need to show the hint
![image](https://github.com/longhorn/longhorn/assets/12527233/0f7a0596-d42d-482e-a5cf-0efde6c67e92)

Instead, we can show
`Offline Replica Rebuilding is disabled, the volume rebuilding will not be automatically triggered after detachment. ` 

## To Reproduce

1. Create a spdk volume with 2 replicas
2. Set `volume.Spec.OfflineReplicaRebuilding` to `disabled`
3. Delete one replica
4. The hint is shown on volume page

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by roger-ryao** [comment]
**Verified on v1.5.x-head 20230621**

- longhorn v1.5.x-head https://github.com/longhorn/longhorn/commit/47af77cee7e432f6b247e0b10c3769fe4d931b3f
- longhorn-ui v1.5.x-head https://github.com/longhorn/longhorn-ui/commit/8b7bcf05204a70d62825e1f8154977d1ad521c86



**Verified on master-head 20230621**

- longhorn master-head https://github.com/longhorn/longhorn/commit/c1d6d93374df63ecf5773e6268231636c6dd70b3
- longhorn-ui master-head https://github.com/longhorn/longhorn-ui/commit/8f2a04afb0ccf56c67267f4891eb687de39480a5


**Result Passed**

After disabling `Offline Replica Rebuilding` and deleting the replica, a hint is displayed on the volume page `Offline Rebuilding: Offline Replica Rebuilding is disabled, the volume rebuilding will not be automatically triggered after detachment.`

![Screenshot_20230621_150649](https://github.com/longhorn/longhorn/assets/104337648/6ce16f0f-93cc-439b-a63e-b12ae8a4a5bc)
![Screenshot_20230621_152316](https://github.com/longhorn/longhorn/assets/104337648/d751690f-4d80-451d-a036-1b295edc3bf2)
