### ISSUE TITLE
Node selector for storage provider pods

### ISSUE THREAD

**Issue by martinounap** [longhorn/longhorn#617]
Could you please guide me, if I can somehow deploy longhorn so, that we could use nodeSelector.

We would love to use selectro: storage = longhorn.

With pods, what need to use storage, I would use same selector. Or is it better then to let k8s select node (but then I need to have longhorn client on all nodes? Is it possible that storage is provisioned from nodes with nodeSelector, but used in all nodes.)?

**Comment by yasker** [comment]
@martinounap It's better to let Kubernetes select the node. The nodes that provide storage are not the same one that uses the storage, so you can use any Longhorn volume on all the nodes. You can allow only certain nodes to provide storage for Longhorn by disabling unneeded nodes.

We're tracking the enhancement #583 that can automatically detect the node labels for enabling/disabling storage usage purpose.
