### ISSUE TITLE
[QUESTION] Can we create a longhorn volume with other user then root?

### ISSUE THREAD

**Issue by mohamed-shahid-afrid** [longhorn/longhorn#6177]
## Question
> Suggest to use https://github.com/longhorn/longhorn/discussions to ask questions.

## Environment

 - Longhorn version:
 - Kubernetes version:
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

## Additional context

I have a path mounted from the pod which is having non-root privileges, I am not able to access the volume and data of it since the volume is created by the root user and my pod is not able to access the volume created by longhorn.

**Comment by shuo-wu** [comment]
Would you check if Kubernetes securityContext settings help?
