### ISSUE TITLE
[BUG] Backup function broken: failed to get engine client proxy

### ISSUE THREAD

**Issue by thomasherrle** [longhorn/longhorn#6180]
## Describe the bug 

After upgrading longhorn from 1.3.1 to 1.4.2 the backup function is somehow broken. All backup buttons are greyed out and show the following error when hovering over:
`failed to get engine client proxy: instance-manager-e-fd5d05402e3c6164c4f0bb8bef2c43db instance manager is in error, not running state`.

## To Reproduce

1. Go to any volume and try to perform any backup action
2. Click on "Create Backup": Button is greyed out
4. See screenshot

![image](https://github.com/longhorn/longhorn/assets/124277188/0fbfdf5e-65f5-4236-8a64-757b2ac221b6)
![image](https://github.com/longhorn/longhorn/assets/124277188/608bf043-caf9-4177-8b8e-2faa8b650e15)

What I already tried to fix this, is to completely remove the corresponding node from the cluster where the instance manager instance-manager-e-fd5d05402e3c6164c4f0bb8bef2c43db is running. But it didn't help. What's also strange is that when I rejoin the node after rke2-uninstall and rm -rf /var/lib/longhorn. The node joins and spawns the exact same named instance manager instance-manager-e-fd5d05402e3c6164c4f0bb8bef2c43db and with always the same volume again and again regardless of how often I delete the disk and reinstall the node.
![image](https://github.com/longhorn/longhorn/assets/124277188/c92a5f73-e1bb-46ea-b085-da2bf97466d7)

## Expected behavior

Backup functions work properly.

## Log or Support bundle

Longhorn-manager log: 
[longhorn-manager.zip](https://github.com/longhorn/longhorn/files/11819679/longhorn-manager.zip)

## Environment

 - Longhorn version: 1.4.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
   - Number of management node in the cluster: 5
   - Number of worker node in the cluster: 22
 - Node config
   - OS type and version: Ubuntu 22.04
   - CPU per node: 24
   - Memory per node: 60 GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 1 Gbit/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 645

**Comment by shuo-wu** [comment]
> The node joins and spawns the exact same named instance manager

The instance manager name of each node is a determinate value, hence this is expected.

As for `instance-manager-e-fd5d05402e3c6164c4f0bb8bef2c43db`, is it really in state `error` when you are blocked by this error? Would you directly generate and upload the whole support bundle?

BTW, there are tons of errors in the provided longhorn manager log:
1. Can you check if the engine image is ready? It seems that there is no engine image pod running on node `rke2agent18`.
```
time="2023-06-21T14:35:31Z" level=debug msg="CheckEngineImageReadiness: nodes [rke2agent18] don't have the engine image longhornio/longhorn-engine:v1.4.2"
```
2. Had the underlying disk of the data path `/var/lib/longhorn` be changed? Althrough the screenshot shows that the disk is ready but I am not sure if it still works after this error.
```
time="2023-06-21T14:36:14Z" level=warning msg="disk data {/var/lib/longhorn/ false true 15756155289 []} is mismatched with collected data &{/var/lib/longhorn/ false 0xc01e7d1620 68c8df37-3be3-4088-b01f-bc1d60bc0b4e <nil> map[]} for disk default-disk-9b38da291901bb2e"
```

**Comment by thomasherrle** [comment]
Thanks for the response Shuo Wu,
I managed to fix this problem myself by deleting a lot of stale old backups. Everything works fine again.
