### ISSUE TITLE
Installing longhorn on k3s cluster running on WSL-2

### ISSUE THREAD

**Issue by mwoodpatrick** [longhorn/longhorn#6181]
## Question
> Has anyone sucessfully installed longhorn on k3s cluster running on WSL-2, When running the install I'm seeing that the 
longhorn-manager pod is failing with a series of errors of the form:

`Error: failed to generate container "8663ea59f48794d4ec2053188ff0337a2313f9dc3e54343384130fc09745d9e8" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount`

## Environment

 - Longhorn version: latest
 - Kubernetes version: k3s  v1.26.5+k3s1
 - Node config
   - OS type and version Arch Linux 20230611.0.157136 under WSL-2
   - CPU per node:12
   - Memory per node:32GB
 - Underlying Infrastructure WSL-2 Baremetal 

## Additional context

Below is the install:

admin@westie_arch2.0_base:~$ curl -sfL https://get.k3s.io/ | K3S_KUBECONFIG_MODE="644" sudo sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.26.5+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.26.5+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.26.5+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
admin@westie_arch2.0_base:~$ kubectl get nodes
WARN[0000] Unable to read /etc/rancher/k3s/k3s.yaml, please start server with --write-kubeconfig-mode to modify kube config permissions
error: error loading config file "/etc/rancher/k3s/k3s.yaml": open /etc/rancher/k3s/k3s.yaml: permission denied
admin@westie_arch2.0_base:~$ sudo chmod uga+r /etc/rancher/k3s/k3s.yaml
admin@westie_arch2.0_base:~$ kubectl get nodes
E0622 05:18:32.067201    4830 memcache.go:287] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0622 05:18:32.071590    4830 memcache.go:121] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0622 05:18:32.075628    4830 memcache.go:121] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0622 05:18:32.077072    4830 memcache.go:121] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
NAME            STATUS   ROLES                  AGE   VERSION
mlwphpenvy360   Ready    control-plane,master   35s   v1.26.5+k3s1
admin@westie_arch2.0_base:~$ kubectl get nodes
NAME            STATUS   ROLES                  AGE   VERSION
mlwphpenvy360   Ready    control-plane,master   43s   v1.26.5+k3s1
admin@westie_arch2.0_base:~$ kubectl get storageclasses -A
NAME                   PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  98s
admin@westie_arch2.0_base:~$ kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
namespace/longhorn-system created
serviceaccount/longhorn-service-account created
serviceaccount/longhorn-support-bundle created
configmap/longhorn-default-setting created
configmap/longhorn-storageclass created
customresourcedefinition.apiextensions.k8s.io/backingimagedatasources.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/backingimagemanagers.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/backingimages.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/backups.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/backuptargets.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/backupvolumes.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/engineimages.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/engines.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/instancemanagers.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/nodes.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/orphans.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/recurringjobs.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/replicas.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/settings.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/sharemanagers.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/snapshots.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/supportbundles.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/systembackups.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/systemrestores.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/volumes.longhorn.io created
customresourcedefinition.apiextensions.k8s.io/volumeattachments.longhorn.io created
clusterrole.rbac.authorization.k8s.io/longhorn-role created
clusterrolebinding.rbac.authorization.k8s.io/longhorn-bind created
clusterrolebinding.rbac.authorization.k8s.io/longhorn-support-bundle created
service/longhorn-backend created
service/longhorn-frontend created
service/longhorn-conversion-webhook created
service/longhorn-admission-webhook created
service/longhorn-recovery-backend created
service/longhorn-engine-manager created
service/longhorn-replica-manager created
daemonset.apps/longhorn-manager created
deployment.apps/longhorn-driver-deployer created
deployment.apps/longhorn-ui created
admin@westie_arch2.0_base:~$ kubectl get storageclasses -A
NAME                   PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  2m15s
admin@westie_arch2.0_base:~$ kubectl -n longhorn-system get all
NAME                                            READY   STATUS                 RESTARTS   AGE
pod/longhorn-ui-7dcbf6bbdc-7n626                1/1     Running                0          34s
pod/longhorn-ui-7dcbf6bbdc-7pxrc                1/1     Running                0          34s
pod/longhorn-driver-deployer-7fc594ddbf-b5zdn   0/1     Init:0/1               0          34s
pod/longhorn-manager-2spvl                      0/1     CreateContainerError   0          34s

NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/longhorn-backend              ClusterIP   10.43.173.150   <none>        9500/TCP   34s
service/longhorn-frontend             ClusterIP   10.43.180.64    <none>        80/TCP     34s
service/longhorn-conversion-webhook   ClusterIP   10.43.91.139    <none>        9501/TCP   34s
service/longhorn-admission-webhook    ClusterIP   10.43.27.217    <none>        9502/TCP   34s
service/longhorn-recovery-backend     ClusterIP   10.43.209.158   <none>        9503/TCP   34s
service/longhorn-engine-manager       ClusterIP   None            <none>        <none>     34s
service/longhorn-replica-manager      ClusterIP   None            <none>        <none>     34s

NAME                              DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/longhorn-manager   1         1         0       1            0           <none>          34s

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/longhorn-driver-deployer   0/1     1            0           34s
deployment.apps/longhorn-ui                2/2     2            2           34s

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/longhorn-driver-deployer-7fc594ddbf   1         1         0       34s
replicaset.apps/longhorn-ui-7dcbf6bbdc                2         2         2       34s
admin@westie_arch2.0_base:~$ kubectl -n longhorn-system logs longhorn-manager-2spvl
Error from server (BadRequest): container "longhorn-manager" in pod "longhorn-manager-2spvl" is waiting to start: CreateContainerError
admin@westie_arch2.0_base:~$ kubectl -n longhorn-system describe longhorn-manager-2spvl
error: the server doesn't have a resource type "longhorn-manager-2spvl"
admin@westie_arch2.0_base:~$ kubectl -n longhorn-system describe pod/longhorn-manager-2spvl
Name:             longhorn-manager-2spvl
Namespace:        longhorn-system
Priority:         0
Service Account:  longhorn-service-account
Node:             mlwphpenvy360/172.19.216.155
Start Time:       Thu, 22 Jun 2023 05:20:08 -0700
Labels:           app=longhorn-manager
                  app.kubernetes.io/instance=longhorn
                  app.kubernetes.io/name=longhorn
                  app.kubernetes.io/version=v1.4.0-dev
                  controller-revision-hash=5fb888b956
                  pod-template-generation=1
Annotations:      <none>
Status:           Pending
IP:               10.42.0.9
IPs:
  IP:           10.42.0.9
Controlled By:  DaemonSet/longhorn-manager
Containers:
  longhorn-manager:
    Container ID:
    Image:         longhornio/longhorn-manager:master-head
    Image ID:
    Ports:         9500/TCP, 9501/TCP, 9502/TCP, 9503/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      longhorn-manager
      -d
      daemon
      --engine-image
      longhornio/longhorn-engine:master-head
      --instance-manager-image
      longhornio/longhorn-instance-manager:master-head
      --share-manager-image
      longhornio/longhorn-share-manager:master-head
      --backing-image-manager-image
      longhornio/backing-image-manager:master-head
      --support-bundle-manager-image
      longhornio/support-bundle-kit:v0.0.24
      --manager-image
      longhornio/longhorn-manager:master-head
      --service-account
      longhorn-service-account
    State:          Waiting
      Reason:       CreateContainerError
    Ready:          False
    Restart Count:  0
    Readiness:      http-get https://:9501/v1/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAMESPACE:  longhorn-system (v1:metadata.namespace)
      POD_IP:          (v1:status.podIP)
      NODE_NAME:       (v1:spec.nodeName)
    Mounts:
      /host/dev/ from dev (rw)
      /host/proc/ from proc (rw)
      /tls-files/ from longhorn-grpc-tls (rw)
      /var/lib/longhorn/ from longhorn (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xrmrc (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/
    HostPathType:
  proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc/
    HostPathType:
  longhorn:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/longhorn/
    HostPathType:
  longhorn-grpc-tls:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  longhorn-grpc-tls
    Optional:    true
  kube-api-access-xrmrc:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  114s               default-scheduler  Successfully assigned longhorn-system/longhorn-manager-2spvl to mlwphpenvy360
  Normal   Pulling    113s               kubelet            Pulling image "longhornio/longhorn-manager:master-head"
  Normal   Pulled     101s               kubelet            Successfully pulled image "longhornio/longhorn-manager:master-head" in 12.405628104s (12.40563604s including waiting)
  Warning  Failed     101s               kubelet            Error: failed to generate container "e7d14dc6971ef5d1fd8608137b8552b53f9e6009c46f541575f6401a058835cd" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     101s               kubelet            Error: failed to generate container "b5043e45510fa524663c071c83f6b9630371c0c7603f9c9bb52895094ecb4bd3" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     86s                kubelet            Error: failed to generate container "a28db0144944d206f60b69d0ad68fda3197e5a2cb0cd36fa11aa92ce9662096e" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     73s                kubelet            Error: failed to generate container "b7760ac6d5a80001de57a8c7f876eaf5298643616d2dfe1f81179c1bafda63bb" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     58s                kubelet            Error: failed to generate container "16ac91064f05272b8a0867fbd7b5703cd47a529143709654fa8b6c1b3703a8d0" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     47s                kubelet            Error: failed to generate container "75f74760a6235f31a58831a13043b070d55159d61c8e3820b0b1a24b13ed5c53" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     32s                kubelet            Error: failed to generate container "45dbbe7529b620408165db91c7c54a83f7474032947137252bca82dc9fba857a" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Warning  Failed     20s                kubelet            Error: failed to generate container "8663ea59f48794d4ec2053188ff0337a2313f9dc3e54343384130fc09745d9e8" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount
  Normal   Pulled     5s (x8 over 101s)  kubelet            Container image "longhornio/longhorn-manager:master-head" already present on machine
  Warning  Failed     5s                 kubelet            Error: failed to generate container "31cc39177bf8f68e25c913b6da19252506309b8ac1771919a8925cc5b36f7781" spec: failed to generate spec: path "/var/lib/longhorn/" is mounted on "/" but it is not a shared mount

**Comment by shuo-wu** [comment]
Based on the discussion in [this ticket](https://stackoverflow.com/questions/68273745/how-to-make-a-mount-shared-in-docker), Windows-related docker desktop somehow gets affected by the tailing `/`. You can try to remove it from the YAML/Chart manually then retry installation but I cannot guarantee it works or not. Longhorn now does not officially support WSL2.

**Comment by mwoodpatrick** [comment]
Many thanks for the information, much appreciated. I will do some more investigation on my end and update the issue with what I discover.
