### ISSUE TITLE
[FEATURE] longhorn-manager webook admission health check parameter

### ISSUE THREAD

**Issue by wolfdate25** [longhorn/longhorn#6184]
I know that longhorn reached version 1.5.0, which brought changes to the operator.
Previously, we could adjust the value of the timeout entry in the curl command by modifying the argument value in the chart, but now it's hardcoded and can no longer be changed.
I would suggest creating that option and making it available to set.

**Comment by shuo-wu** [comment]
Which chart value/curl command do you mean...? In v1.5.0, webhook services are merged into longhorn-manager pods.

**Comment by wolfdate25** [comment]
Your right. I need this to parameterize.
https://github.com/longhorn/longhorn-manager/blob/16895efa30532755539b70ceee9c82073dfb36fd/app/webhook.go#L52

**Comment by shuo-wu** [comment]
Hmm... This health check client is for probing the **local** webhook service, is it necessary to make it tunable...?
cc @derekbit

**Comment by derekbit** [comment]
> Hmm... This health check client is for probing the **local** webhook service, is it necessary to make it tunable...? cc @derekbit

I'm not sure.
@wolfdate25 Can you elaborate more on the issues when using a fixed timeout value?

**Comment by wolfdate25** [comment]
Distance between nodes in my cluster is at the continental level.
It's hard to get a response in just a second.
Of course, I know that my cluster is not an ideal situation.
I already use openebs' jiva as an alternative, but I like longhorn's interface.
I hope you'll consider my comments.

**Comment by shuo-wu** [comment]
Here, the destination of the client is https://**localhost**:<webhook port>/v1/healthz. Will the requests for this URL be forwarded to other nodes...?

**Comment by derekbit** [comment]
In the new implementation, it should not be. Right?

**Comment by wolfdate25** [comment]
Interestingly, the result is different than when we tried it before.
The issue I was experiencing with instance manager or longhorn manager not running on certain nodes seems to have been resolved. Based on 1.4.0, I thought the issue was related to request timeout.
There are no issues at this time, so we're closing the issue. Thank you for your attention.
