### ISSUE TITLE
[TEST] Unable to download support bundle: parse error

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6186]
## What's the test to develop? Please describe

Recently (likely has last more than **2** months) we are constantly encounter errors in daily regression all branches `master`, `v1.5.x`, `v1.4.x` when trying to download support bundle after test completed with the following error message:
```
parse error: Invalid numeric literal at line 1, column 7
```

Like in:
https://ci.longhorn.io/job/public/job/v1.5.x/job/v1.5.x-longhorn-tests-sles-arm64/25/
https://ci.longhorn.io/job/public/job/v1.5.x/job/v1.5.x-longhorn-tests-sles-arm64/24/

https://ci.longhorn.io/job/public/job/v1.5.x/job/v1.5.x-longhorn-tests-sles-amd64/13/

https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/505/
https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/509/

https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-upgrade-tests-sles-arm64/494/
https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-2-stage-upgrade-tests-sles-arm64/181/

What causes this happening is still unknown.

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

Add any other context or screenshots about the test request here.

**Comment by yangchiu** [comment]
It's highly possible that our regression test build encounters this issue and fails, and rerun is needed to get a normal completed build. cc @longhorn/qa @innobead

**Comment by c3y1huang** [comment]
Is it possible that the [timeout issue](https://github.com/longhorn/longhorn/issues/6256) is causing the problem?

**Comment by yangchiu** [comment]
Not sure. Since it randomly happens and unable to reproduce in local, I'm still trying to figure out a way to insert logs in daily regression to collect useful information.

**Comment by yangchiu** [comment]
```
++ kubectl get svc -n longhorn-system longhorn-frontend -o json
++ jq -r '.spec.clusterIP + ":" + (.spec.ports[0].port|tostring)'
+ LH_FRONTEND_ADDR=10.43.241.107:80
+ echo 10.43.241.107:80
10.43.241.107:80
+ JSON_PAYLOAD='{"issueURL": "Auto-generated support buundle", "description": "Auto-generated support buundle"}'
+ CURL_CMD='curl -s -XPOST [http://10.43.241.107:80/v1/supportbundles](http://10.43.241.107/v1/supportbundles) -H '\''Accept: application/json'\'' -H '\''Accept-Encoding: gzip, deflate'\'' -d '\''{"issueURL": "Auto-generated support buundle", "description": "Auto-generated support buundle"}'\'''
+ echo curl -s -XPOST [http://10.43.241.107:80/v1/supportbundles](http://10.43.241.107/v1/supportbundles) -H ''\''Accept:' 'application/json'\''' -H ''\''Accept-Encoding:' gzip, 'deflate'\''' -d ''\''{"issueURL":' '"Auto-generated' support 'buundle",' '"description":' '"Auto-generated' support 'buundle"}'\'''
curl -s -XPOST [http://10.43.241.107:80/v1/supportbundles](http://10.43.241.107/v1/supportbundles) -H 'Accept: application/json' -H 'Accept-Encoding: gzip, deflate' -d '{"issueURL": "Auto-generated support buundle", "description": "Auto-generated support buundle"}'
++ kubectl exec -n longhorn-system svc/longhorn-frontend -- bash -c 'curl -s -XPOST [http://10.43.241.107:80/v1/supportbundles](http://10.43.241.107/v1/supportbundles) -H '\''Accept: application/json'\'' -H '\''Accept-Encoding: gzip, deflate'\'' -d '\''{"issueURL": "Auto-generated support buundle", "description": "Auto-generated support buundle"}'\'''
+ SUPPORT_BUNDLE_RESP='<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.21.5</center>
</body>
</html>
'
+ echo '<html>
' '<head><title>502' Bad 'Gateway</title></head>
' '<body>
' '<center><h1>502' Bad 'Gateway</h1></center>
' '<hr><center>nginx/1.21.5</center>
' '</body>
' '</html>
'
<html>
 <head><title>502 Bad Gateway</title></head>
 <body>
 <center><h1>502 Bad Gateway</h1></center>
 <hr><center>nginx/1.21.5</center>
 </body>
 </html>
++ echo '<html>
' '<head><title>502' Bad 'Gateway</title></head>
' '<body>
' '<center><h1>502' Bad 'Gateway</h1></center>
' '<hr><center>nginx/1.21.5</center>
' '</body>
' '</html>
'
++ jq -r '.links.self + "/" + .name'
parse error: Invalid numeric literal at line 1, column 7
+ SUPPORT_BUNDLE_URL=
```

**Comment by yangchiu** [comment]
Fixed in https://github.com/longhorn/longhorn-tests/pull/1521.
