### ISSUE TITLE
[IMPROVEMENT] SPDK client should functions after encountering decoding error

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#6191]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

When issue #6190 is triggered, all following cmd responses will be failed by the invalid json error. This is probably caused by the cache of the reused decoder of the client (but we cannot confirm this).

## Describe the solution you'd like

- Use a brand new decoder for each cmd call
- In case using the separate decoder is not able to resilient this issue, the SPDK engine can re-init the client when encountering the error.

## Additional context

See issue #6190 for details. This is just a workaround.

**Comment by innobead** [comment]
@shuo-wu is this possible to verify by QA?

**Comment by shuo-wu** [comment]
Since we don't have a way to reproduce the issue, hence testing the fixes are hard.

BTW, there is no need to update the vendor for `longhorn-manager`

**Comment by innobead** [comment]
Moving to ready-for-testing, but pending before release to see if this will be reproduced again. 

cc @yangchiu Feel free to close this after 1.5.0 GA.

**Comment by yangchiu** [comment]
Installed Longhorn v1.5.0-rc3, and tried to trigger spdk volume offline replica rebuilding by deleting replicas or killing the `spdk_tgt` process in `instance-manager`. Everything works well without problem. Close this for now.
