### ISSUE TITLE
[BUG] Volume attachment related error logs in uninstaller pod

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#6197]
## To Reproduce

1. Install Longhorn 1.5.0-rc2
2. Create a volume and attach it.
3. Set deletion confirmation flag: `kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs deleting-confirmation-flag`
4. Uninstall Longhorn using [kubectl command](https://raw.githubusercontent.com/longhorn/longhorn/v1.5.0-rc3/uninstall/uninstall.yaml)
5. Check the uninstaller pod logs, they have error like below
```
W0626 20:39:03.417023       1 reflector.go:533] github.com/longhorn/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:117: failed to list *v1beta2.VolumeAttachment: volumeattachments.longhorn.io is forbidden: User "system:serviceaccount:longhorn-system:longhorn-uninstall-service-account" cannot list resource "volumeattachments" in API group "longhorn.io" at the cluster scope
E0626 20:39:03.417071       1 reflector.go:148] github.com/longhorn/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:117: Failed to watch *v1beta2.VolumeAttachment: failed to list *v1beta2.VolumeAttachment: volumeattachments.longhorn.io is forbidden: User "system:serviceaccount:longhorn-system:longhorn-uninstall-service-account" cannot list resource "volumeattachments" in API group "longhorn.io" at the cluster scope
```

## Expected behavior

Uninstaller should have problem in getting/reading the volumeAttachment

## Log or Support bundle

[uninstall.log](https://github.com/longhorn/longhorn/files/11874014/uninstall.log)

## Environment

 - Longhorn version: 1.5.0-rc2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

**Comment by PhanLe1010** [comment]
Looks like the yaml https://github.com/longhorn/longhorn/blob/master/uninstall/uninstall.yaml is missing the [volumes.attachment.longhorn.io](http://volumes.attachment.longhorn.io/) permission.

**Comment by innobead** [comment]
@yangchiu Please help with this testing.

**Comment by yangchiu** [comment]
Verified passed following [the test steps](https://github.com/longhorn/longhorn/issues/6197#issue-1775593267).

Install Longhorn v1.5.0-rc3, and create a volume and attach it, then uninstall Longhorn by:
```
kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/master/uninstall/uninstall.yaml
```
or
```
kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/v1.5.x/uninstall/uninstall.yaml
```

There's no `volumeattachments` related error logs and uninstallation can be done without problem.
