### ISSUE TITLE
storage reserved doesn't exists on rancher UI

### ISSUE THREAD

**Issue by shifeichen** [longhorn/longhorn#6201]
## Question
> Suggest to use https://github.com/longhorn/longhorn/discussions to ask questions.

## Environment

 - Longhorn version:
 - Kubernetes version:
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Comment by shuo-wu** [comment]
`reserved storage` is just one factor that affects the schedulable space of a disk. Longhorn won't reserve actual disk space and block IOs for this part.
