### ISSUE TITLE
[TASK] Add 1.5 performance benchmark to performance benchmark WIKI page

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6203]
## What's the task? Please describe

https://github.com/longhorn/longhorn/wiki/Performance-Benchmark

Need to verify v1 and v2, and do the comparison. 

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

cc @longhorn/dev-data-plane

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by derekbit** [comment]
We only measure the performance on high-level machines such as [Equinix m3.small.x86](https://deploy.equinix.com/product/servers/m3-small/).
As well as the high-level machines, we can benchmark on low- or medium-level machines like [AWS c5.xlarge (4 vCPU, 8GiB RAM)](https://aws.amazon.com/ec2/instance-types/?nc1=h_ls).

**Comment by derekbit** [comment]
> Note: For the low-spec especially no dedicated disk machines, the performance gain is limited. Based on our testing result, the bandwidth of v2 volumes may be worse than v1 volumes:

Similar results are observed on AWS platform. I've added a disk requirement in https://longhorn.io/docs/1.5.0/spdk/prerequisites/#disk.

**Comment by innobead** [comment]
@derekbit Let's update https://github.com/longhorn/longhorn/wiki/Performance-Benchmark first to include 1.5 performance v1 & v2.

**Comment by derekbit** [comment]
Updated. Thank you.
