### ISSUE TITLE
[TEST-INFRA] Migrate CI environment to the new cloud account

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6204]
## What's the test to develop? Please describe

After 1.5.0 out, need to replace the current cloud account with the new account to run the e2e automation. Ensure we can run regression testing for the following 1.4.3, https://github.com/longhorn/longhorn/milestone/46. 

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

cc @longhorn/qa

**Comment by yangchiu** [comment]
The migration has been done.
