### ISSUE TITLE
[BUG] Test case test_ha_backup_deletion_recovery failed in rhel or rockylinux arm64 environment

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6213]
## Describe the bug (🐛 if you encounter this issue)

In Longhorn `master-head` or `v1.5.0-rc3`, test case `test_backing_image.py::test_ha_backup_deletion_recovery` fails with a very high reproducibility in `rhel` or `rockylinux` `arm64` environment:
```
dev = '/dev/longhorn/longhorn-testvol-ofr922'
data = {'checksum': '04adcc37b49f1829ea534f10a03726252a4720267ac61ffa01b7f46e951ba1bdad0968c42668a950752119e2e8149ba494a934cf...5p97cj1v7m7eb058damciy6r9kscamttiloesyfkesu7jn0dohns04e7i8hen2yna54bzw8h6s9m1ggfyb48z3lj', 'len': 512, 'pos': 11784510}
check_checksum = True

    def check_device_data(dev, data, check_checksum=True):
        r_data = dev_read(dev, data['pos'], data['len'])
        assert r_data == bytes(data['content'], encoding='utf8')
        if check_checksum:
            r_checksum = get_device_checksum(dev)
>           assert r_checksum == data['checksum']
E           AssertionError
```

In `v1.5.0-rc2`, this high failure rate is not observed.

[rhel arm64 v1.5.0-rc2](https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/142/): 1/10 failures
[rhel arm64 v1.5.0-rc3](https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/141/): 9/10 failures

[rockylinux arm64 v1.5.0-rc2](https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/138/): 0/10 failures
[rockylinux arm64 v1.5.0-rc3](https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/137/): 6/10 failures

## To Reproduce

Run test case `test_backing_image.py::test_ha_backup_deletion_recovery` 

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
@ChanYiLin please help check this. Thanks.

cc @shuo-wu @derekbit

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by derekbit** [comment]
I found the snapshot disk files are restored and the checksums are correct, but the meta data is weird. One of disks's metadata content is `{"Parent":""}`. The disk chain is incomplete...

![image](https://github.com/longhorn/longhorn/assets/12527233/b97a97b7-be55-4326-b30a-d8c772834610)


![image](https://github.com/longhorn/longhorn/assets/12527233/81a4412a-c18a-4fc0-a74b-a4844756e56d)

**Comment by derekbit** [comment]
Any idea? cc @shuo-wu

**Comment by derekbit** [comment]
One difference is the `BackingFilePath` feild.

- metafiles of a passed case
```
root@dereksu-arm64-pool2-960b89a4-l6bz6:/var/lib/longhorn/replicas/longhorn-testvol-wwmdb9-a4e036b7# cat *meta
{"Name":"volume-head-001.img","Parent":"volume-snap-bc1959b9-1c25-4526-8523-df8928d8887d.img","Removed":false,"UserCreated":false,"Created":"2023-06-28T16:54:47Z","Labels":null}
{"Parent":""}
{"Size":33554432,"Head":"volume-head-001.img","Dirty":true,"Rebuilding":false,"Error":"","Parent":"volume-snap-bc1959b9-1c25-4526-8523-df8928d8887d.img","SectorSize":512,"BackingFilePath":"/host/var/lib/longhorn/backing-images/bi-test-fe394799/backing"}
```

- metafiles of a failed case
```
root@dereksu-arm64-pool2-960b89a4-l6bz6:/var/lib/longhorn/replicas/longhorn-testvol-hxdbd7-ffc8f106# cat *meta
{"Name":"volume-head-001.img","Parent":"volume-snap-876aaf0c-ea57-4955-a1af-3b8fe0f3d289.img","Removed":false,"UserCreated":false,"Created":"2023-06-28T17:00:09Z","Labels":null}
{"Parent":""}
{"Size":33554432,"Head":"volume-head-001.img","Dirty":true,"Rebuilding":false,"Error":"","Parent":"volume-snap-876aaf0c-ea57-4955-a1af-3b8fe0f3d289.img","SectorSize":512,"BackingFilePath":""}
```

**Comment by derekbit** [comment]
Log messages

The `BackingImage` of a failed restore is somehow a `""` string
```
time="2023-06-29T01:20:52Z" level=debug msg="Created volume longhorn-testvol-oodka6: {Size:33554432 Frontend:blockdev FromBackup:s3://backupbucket@us-east-1/backupstore?backup=backup-6239770575f1496f&volume=longhorn-testvol-ukmeq2 RestoreVolumeRecurringJob:ignored DataSource: DataLocality:disabled StaleReplicaTimeout:0 NodeID: MigrationNodeID: EngineImage:derekbit/longhorn-engine:backup01 BackingImage: Standby:false DiskSelector:[] NodeSelector:[] DisableFrontend:false RevisionCounterDisabled:false UnmapMarkSnapChainRemoved:ignored ReplicaSoftAntiAffinity:ignored ReplicaZoneSoftAntiAffinity:ignored LastAttachedBy: AccessMode:rwo Migratable:false Encrypted:false NumberOfReplicas:2 ReplicaAutoBalance:ignored SnapshotDataIntegrity:ignored BackupCompressionMethod:lz4 BackendStoreDriver:v1 OfflineReplicaRebuilding:disabled}"
```

Then, the associated replica's backing is `""` string as well.
```
...
spec:
  active: true
  backendStoreDriver: v1
  backingImage: ""
  dataDirectoryName: longhorn-testvol-oodka6-894e08b6
  desireState: running
  diskID: 676bb2f7-26d5-43ab-88e6-e99ffbdc4380
  diskPath: /var/lib/longhorn/
  engineImage: derekbit/longhorn-engine:backup01
  engineName: longhorn-testvol-oodka6-e-b5dbe704
...
```

**Comment by ChanYiLin** [comment]
Conclusion (From @innobead )

- Use the backup resource to determine the restoring volume is based on a backing image.
- Still use backup volume to do the mutation. If it does not exist, then mutation error. The restoring volume CR creation will fail.
- Users just need to retry

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager ) and v1.5.x-head (longhorn-manager ). 

Running test case `test_ha_backup_deletion_recovery` for **10** times, all test cases pass on these 2 branches.

master-head amd64: https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/150/
master-head arm64: https://ci.longhorn.io/job/public/job/master/job/rhel/job/arm64/job/longhorn-tests-rhel-arm64/54/

v1.5.x-head amd64: https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/151/
v1.5.x-head arm64: https://ci.longhorn.io/job/public/job/master/job/rhel/job/arm64/job/longhorn-tests-rhel-arm64/53/
