### ISSUE TITLE
[DOC] Clarify RWX volume expansion documentation

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#6216]
## What's the task? Please describe

Our [RWX volume expansion documentation](https://longhorn.io/docs/1.5.0/volumes-and-nodes/expansion/#rwx-volume) is confusing. We state:

> Currently, Longhorn is unable to expand the filesystem (NFS) for RWX volumes. - If you decide to expand a RWX volume manually, you can:
> 
> 1. Expand the block device of the RWX volume via PVC or UI.
> 2. Figure out the share manager pod of the RWX volume then execute the filesystem expansion command. The share manager pod is typically named as share-manager-<volume name>.

In my experience, offline expansion of a RWX volume works without intervention. If the RWX volume is detached, ControllerExpandVolume expands the Longhorn volume and the attaching process (probably when the share-manager pod is attaching the volume before exporting via NFS) expands the file system.

Online expansion IS problematic. It results in NodeExpandVolume being called on every node with the RWX volume mounted. NodeExpandVolume fails with the following (as expected):

```
time="2023-06-28T16:13:02Z" level=info msg="NodeExpandVolume: req: {\"capacity_range\":{\"required_bytes\":2684354560},\"staging_target_path\":\"/var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/686cae5cd920871e209c1ef2456fa20dce5bdd8118a49b2ef5c3a388c6077081/globalmount\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":5}},\"volume_id\":\"pvc-8dc48c4a-f983-4633-afc2-966c6802f1e1\",\"volume_path\":\"/var/lib/kubelet/pods/7843650a-8c14-428b-a6ca-28f9bb690522/volumes/kubernetes.io~csi/pvc-8dc48c4a-f983-4633-afc2-966c6802f1e1/mount\"}"
time="2023-06-28T16:13:02Z" level=error msg="NodeExpandVolume: err: unknown filesystem type for volume pvc-8dc48c4a-f983-4633-afc2-966c6802f1e1 node expansion"
```

An easy solution to this appears to be to scale the workload down and then back up again.

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [x] Confirm the actual behavior described above.
- [x] Confirm that online expansion can be achieved using the previously documented steps.
- [x] Clarify in the documentation that offline RWX expansion is supported, but online expansion requires following the previously documented steps.

## Additional context

Add any other context or screenshots about the document request here.

**Comment by iTaybb** [comment]
I also encounter this.

**Comment by iTaybb** [comment]
My workaround is as follows:
1. The two first steps, like the docs
2. Edit the PVC status directly, removing the FileSystemResizePending condition, and setting the status.capacity.storage to the new extended size.

That way, the `NodeExpandVolume` state will be removed, and everything will work correctly.

Of course, this is a workaround, until a proper bug will be introduced.

**Comment by innobead** [comment]
Currently, online volume expansion is not supported, so this is why we have this doc to allow users to do that though RWO way, but it turned out the doc was not well clarified in a multi-attached situation. As @ejweber mentioned, we need to clarify the doc. 

Also, need to evaluate the feasibility to see if we can delegate the node expansion to the right node (volume attached node) instead of doing this in all attached nodes. Ideally, the call should not be taken effect for RWX in our implementation. 

> Online expansion IS problematic. It results in NodeExpandVolume being called on every node with the RWX volume mounted. NodeExpandVolume fails with the following (as expected):

cc @james-munson @derekbit

**Comment by innobead** [comment]
@james-munson Where we are?

**Comment by derekbit** [comment]
@james-munson Could you update the status? Thanks.

**Comment by james-munson** [comment]
I will get this done for 1.7.0.

**Comment by james-munson** [comment]
In testing, I have found that RWX volumes based on ext4 fsType can be expanded with either workaround - that is, by doing a manual resize2fs in the share-manager pod while the workload is still attached, or by scaling down to zero before the expansion, and then back up.

For fsType of xfs, if the workload is scaled down, then it will fail to mount its containers after an expansion, leaving them in ContainerCreating state indefinitely.  If the expansion is done with the workload online, and then xfs_growfs is used manually inside the share-manager pod, it will appear to work, and the workload will see the larger size.  But if the workload is scaled down and back up some time after that, it will also fail to mount, with the error
```
 Warning   FailedMount                pod/rwx-xfs-84cd4d9644-9jj8n                                                          MountVolume.Setup failed while expanding volume for volume "pvc-260971f5-3a33-4aac-bd27-b946c557115e" : Expander.NodeExpand failed to expand the volume : rpc error: code = Internal desc = could not find block size of device /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/8b72ffc65537378cbcc42f3019da7e202ac3a741305db23ef2928d3a9ef5d5d1/globalmount
 ```

**Comment by ejweber** [comment]
Another finding:

The current behavior of NodeExpandVolume is pretty weird for RWX volumes.

1. We try to expand the volume using the DevicePath: https://github.com/longhorn/longhorn-manager/blob/ffd2152cce71a05758059fff66cea3b8abc1f5cf/csi/node_server.go#L762-L763.
2. But the device path is the engine endpoint: https://github.com/longhorn/longhorn-manager/blob/ffd2152cce71a05758059fff66cea3b8abc1f5cf/csi/node_server.go#L713.
3. So, if the underlying volume is attached to the same node as a kubelet that calls NodeExpandVolume, the expansion actually succeeds as a no-op.
   ```
   [longhorn-csi-plugin-lhfm2 longhorn-csi-plugin] time="2024-07-10T15:12:17Z" level=info msg="NodeNodeExpandVolume is called with req volume_id:\"pvc-b077e1a4-0771-498e-87aa-a4657058236d\" volume_path:\"/var/lib/kubelet/pods/202ecdcb-7d8d-4c23-837d-d9587e3cfb47/volumes/kubernetes.io~csi/pvc-b077e1a4-0771-498e-87aa-a4657058236d/mount\" capacity_range:<required_bytes:2147483648 > staging_target_path:\"/var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/e6414fe23fc07d575cd61c1168bb4df07010db42fd57a955425a4a6d69d8fe8d/globalmount\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > > " func="csi.(*NodeServer).NodeExpandVolume" file="node_server.go:696" component=csi-node-server function=NodeExpandVolume
   [longhorn-manager-w6chd longhorn-manager] 10.42.2.43 - - [10/Jul/2024:15:12:17 +0000] "GET /v1/volumes/pvc-b077e1a4-0771-498e-87aa-a4657058236d HTTP/1.1" 200 11561 "" "Go-http-client/1.1"
   [longhorn-csi-plugin-lhfm2 longhorn-csi-plugin] time="2024-07-10T15:12:17Z" level=info msg="Volume pvc-b077e1a4-0771-498e-87aa-a4657058236d on node eweber-v126-worker-9c1451b4-kgxdq does not require filesystem resize" func="csi.(*NodeServer).NodeExpandVolume" file="node_server.go:791" component=csi-node-server function=NodeExpandVolume
   ```
4. Otherwise, one of the above errors is returned.

I think in the long term, we need to ensure NodeExpandVolume is never called for RWX volumes, since it is nonsensical on any node that isn't running the share manager.

**Comment by james-munson** [comment]
I think you're right, @ejweber , I may have been jumping the gun on the manual expansion of offline XFS volume, not waiting long enough for the detachment to be fully complete before doing the PVC edit.

**Comment by james-munson** [comment]
Revised and re-pushed the PR.

**Comment by ejweber** [comment]
A last update in preparation for a potential follow-up:

Why is the current behavior of online expansion different for XFS and ext4 volumes?

https://github.com/longhorn/longhorn/issues/6216#issuecomment-2220861850 mentions that `NodeExpandVolume` can succeed as a no-op only on the node the underlying volume is actually attached to. Once it does on that one node, `pvc.status.conditions[FileSystemResizePending` is cleared. The other nodes still log the following messages until they unstage the volume during pod teardown. The logs are pretty ugly, but there is no functional issue.

```
[longhorn-csi-plugin-hxq5t longhorn-csi-plugin] time="2024-08-16T16:20:57Z" level=info msg="NodeNodeExpandVolume is called with req volume_id:\"pvc-dea16ba4-6e2f-4e1e-929e-6e437e92cb2f\" volume_path:\"/var/lib/kubelet/pods/2deb46b9-519b-480e-a7d3-a17b2223d5c6/volumes/kubernetes.io~csi/pvc-dea16ba4-6e2f-4e1e-929e-6e437e92cb2f/mount\" capacity_range:<required_bytes:2147483648 > staging_target_path:\"/var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/2d771baee38204151f154d7beec28f8ea7e73ade924b95d3449eff9f760cdec7/globalmount\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > > " func="csi.(*NodeServer).NodeExpandVolume" file="node_server.go:684" component=csi-node-server function=NodeExpandVolume
[longhorn-csi-plugin-hxq5t longhorn-csi-plugin] time="2024-08-16T16:20:57Z" level=error msg="NodeExpandVolume: err: unknown filesystem type for volume pvc-dea16ba4-6e2f-4e1e-929e-6e437e92cb2f node expansion" func=csi.logGRPC file="server.go:136"
```

A major caveat is that `NodeExpandVolume` actually can NOT succeed as a no-op even on the node the underlying volume is actually atached to. for XFS volumes. It always fails with:

```
[longhorn-csi-plugin-nbsv7] time="2024-08-16T16:39:00Z" level=error msg="NodeExpandVolume: err: rpc error: code = Internal desc = could not find block size of device /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/c36495d30166f75919c6e92fc141c7aec470073345c6bdd0834fcb70dd35e417/globalmount" func=csi.logGRPC file="server.go:136"
```

TBH, it's not clear why this is the case exactly, but the long-term solution probably involves ensuring the code that errors here is never called anyway. As a result, `pvc.status.conditions[FileSystemResizePending` is NEVER cleared. `NodeExpandVolume` is called on every node even after the volume is restaged and always fails.

**Comment by roger-ryao** [comment]
After reviewing this ticket, I realized that I had already verified the issue https://github.com/longhorn/longhorn/issues/6050 by referencing [the documentation from issue 6216](https://github.com/longhorn/website/pull/966). Therefore, we can close this issue.
