### ISSUE TITLE
Upgrade support from v0.5.0 to v0.6.0

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#622]

**Comment by yasker** [comment]
This may depend on https://github.com/longhorn/longhorn/issues/593

**Comment by yasker** [comment]
We will only support detaching the v0.5.0 volume gracefully in v0.6.0. No other operations would be supported.

**Comment by yasker** [comment]
Note: Live upgrade from v0.5.0 to v0.6.0 is not supported, so no need to test the live upgrade feature.

**Comment by meldafrawi** [comment]
Validation: **WIP**

**Steps to test:**
#### Install Longhorn **v0.5.0** 
1- using `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v0.5.0/deploy/longhorn.yaml`

2- Create volumes:
  - Create a volume, attach it to a node, and write data to it and calculate its md5 checksum.
  - Create a volume with pv/pvc attached to a pod using: `kubectl apply -f https://github.com/longhorn/longhorn/blob/master/examples/pvc.yaml`, write data to it and calculate its md5 checksum.
  - Create StatefulSet with attached volumes using "kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml" write data to the volumes attached to `web-0` & `web-1` pods, calculate its md5 checksum.

#### Upgrading Longhron to v0.6.0-rc1
3- Upgrade Longhorn manager using `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v0.6.0/deploy/longhorn.yaml`
>> Expected result:
>> - Longhorn components pods will be terminated and new pods will be started.
>> - In `Settings/Engine Image`, new Longhorn Engine Image will be available.
>> - In `Nodes` page, Longhorn components readiness should be `ready` on `Readiness` column
>>   - for `longhornio/longhorn-engine:v0.6.0-rc1`
>>     - Engine Image: ready
>>     - Instance Manager - Engine: running
>>     - Instance Manager - Replica: running
>>   - for `rancher/longhorn-engine:v0.5.0`
>>     - Engine Image: incompatible
>>     - Instance Manager - Engine: Unknown
>>     - Instance Manager - Replica: Unknown
>> - On `Volume` page, in `State` column, an `Up Arrow` will show up next to Volume state, Hovering over the arrow, a tool-tip will show up stating that 
>>   ```
>>    Current engine image: v0.5.0
>>    Engine image v0.6.0-rc1 is now available!
>>   ```

#### Upgrade Longhorn engine (offline) https://github.com/longhorn/longhorn/blob/master/docs/upgrade.md#offline-upgrade
4- Follow the detach procedure for relevant workloads
5- Select all the volumes using batch selection. Click batch operation button Upgrade Engine, choose v0.6.0 engine image
6- Attach the volume, and recreate the workloads
7- Verify the data integrity on volumes.
