### ISSUE TITLE
[BUG] Observed many supportbundle pods in terminating state.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#6221]
## Describe the bug (🐛 if you encounter this issue)

I observed many pods were in `terminating state`. Before observing that I downloaded 2 supportbundles in the system.

## To Reproduce

1. Have Rancher server to manage kubernetes cluster. Install Longhorn on a downstream cluster.
2. Run some integration test on it. (test_migration_with_unscheduled_replica)
3. Download supportbundle
4. Check the Rancher UI.
5. There are many supportbundle pod in terminating state. 

## Expected behavior
Only one supportbundle pod should get created while downloading it and get terminated successfully once done.

## Log or Support bundle
<img width="1108" alt="Screenshot 2023-06-28 at 2 51 27 PM" src="https://github.com/longhorn/longhorn/assets/60111667/029640e7-5677-42ff-b6ed-0655cb33300a">

<img width="1402" alt="Screenshot 2023-06-28 at 2 51 54 PM" src="https://github.com/longhorn/longhorn/assets/60111667/acf4813f-a1e0-401a-8bc5-6e056c1df1be">

## Environment

 - Longhorn version: v1.5.x-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

## Additional context

`k get pod -A | grep support` yields nothing

**Comment by khushboo-rancher** [comment]
I have support bundle from some intermittent state, not sure whether it will have some info.
[supportbundle_3baf9a96-7158-4879-8dd0-5224d1965dbc_2023-06-28T21-29-04Z.zip](https://github.com/longhorn/longhorn/files/11900442/supportbundle_3baf9a96-7158-4879-8dd0-5224d1965dbc_2023-06-28T21-29-04Z.zip)

**Comment by c3y1huang** [comment]
Based on the provided screenshot,  it seems they are all support-bundle agent pods. They belong to a DaemonSet created by the support bundle manager and responsible cor generating the node bundles.

ref: https://github.com/rancher/support-bundle-kit/tree/d5bb2ba66d660ff1ed1f45dff0cbce37219817dd#support-bundle-kit-
```
  - `manager`: start a support bundle kit manager. The manager does these works:
    - It collects the cluster bundle, including YAML manifests and pod logs.
    - It collects external bundles. e.g., Longhorn support bundle.
    - It starts a web server and waits for bundle downloading and uploading.
    - It starts a daemonset on each node. The agents in the daemonset collect node bundles and push them back to the manager.
```

**Comment by khushboo-rancher** [comment]
@c3y1huang so, if this is expected, we can close this?
