### ISSUE TITLE
Storage path change

### ISSUE THREAD

**Issue by sumanusk** [longhorn/longhorn#6227]
## Question
> Suggest to use https://github.com/longhorn/longhorn/discussions to ask questions.

**Need to change default path for data store from /var/lib/longhorn to my customized mounted path**

## Environment

 - Longhorn version: 1.4.2
 - Kubernetes version: v1.25.11
 - Node config
   - OS type and version ubuntu - 20.04.6
   - CPU per node: 4 
   - Memory per node: 8 
   - Disk type sda
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Comment by shuo-wu** [comment]
Basically, you can edit Longhorn nodes, add new disk paths, evict the old disk paths, wait for all replica being migrated from the old disks to the new disks, then remove the old disks.
If you are checking how to change the default disks at the beginning (when new nodes is added to the cluster/Longhorn), you can refer to this doc: https://longhorn.io/docs/1.4.2/advanced-resources/default-disk-and-node-config/

**Comment by sumanusk** [comment]
> Basically, you can edit Longhorn nodes, add new disk paths, evict the old disk paths, wait for all replica being migrated from the old disks to the new disks, then remove the old disks. If you are checking how to change the default disks at the beginning (when new nodes is added to the cluster/Longhorn), you can refer to this doc: https://longhorn.io/docs/1.4.2/advanced-resources/default-disk-and-node-config/


I added external disk, how to change default path now after installation.

**Comment by shuo-wu** [comment]
You can change this setting: https://longhorn.io/docs/1.5.0/references/settings/#default-data-path

**Comment by sumanusk** [comment]
> You can change this setting: https://longhorn.io/docs/1.5.0/references/settings/#default-data-path

below is the change you suggested

![image](https://github.com/longhorn/longhorn/assets/40730705/82edea5f-63dc-410c-9366-1981fab73661)

**Comment by sumanusk** [comment]
Instead of changing there, i changes the mount path to /var/lib/longhorn. it helped me
