### ISSUE TITLE
[BUG] Unable to delete snapshot due to code = Unimplemented desc = unknown method SnapshotHashCancel for service ptypes.SyncAgentService

### ISSUE THREAD

**Issue by Michael-Baylis** [longhorn/longhorn#6232]
## Describe the bug (🐛 if you encounter this issue)

Unable to delete snapshots since upgrading to 1.4.2.   When attempting to delete the snapshot within the UI, we receive the message:-
`failed to delete snapshot: proxyServer=10.40.128.7:8501 destination=10.40.128.7:10005: failed to remove snapshot [backup-all-c-9b20dda1]: rpc error: code = Unknown desc = failed to cancel snapshot backup-all-c-9b20dda1 hash task: rpc error: code = Unimplemented desc = unknown method SnapshotHashCancel for service ptypes.SyncAgentService
`
I did incorrectly upgrade from 1.2.x to 1.4.2, accidently skipped 1.3.x.   But snapshots created on 1.4.2 also receive the same message.

Even deleting the snapshot using kubectl does not work.

## To Reproduce

1. Locate a Volume
2. Click Take Snaphot
3. Wait for snapshot to be created
4. click on snapshot and select delete
5. receive the error message

## Expected behavior

I expect snapshots to be deleted.

## Log or Support bundle

Support bundle will be sent

## Environment

 - Longhorn version: 1.4.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl apply
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k8s
   - Number of management node in the cluster: 6
   - Number of worker node in the cluster: 6
 - Node config
   - OS type and version: Ubuntu 20.04 and 22.04
   - CPU per node: Normally 4
   - Memory per node: Normally 16gb
   - Disk type(e.g. SSD/NVMe): SAN
   - Network bandwidth between the nodes: 1GB
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare and Openstack
 - Number of Longhorn volumes in the cluster:106

**Comment by derekbit** [comment]
Is the engine of the problematic volume upgraded to v1.4.2?

**Comment by Michael-Baylis** [comment]
Yes,  everything is at 1.4.2

**Comment by Michael-Baylis** [comment]
Need to send support bundle,  but don't want to attach to public issue

**Comment by derekbit** [comment]
Sure. You can send it to longhorn-support-bundle@suse.com.

**Comment by Michael-Baylis** [comment]
support bundle too big to email,   so I have sent an email with a link to download it.

**Comment by derekbit** [comment]
@Michael-Baylis 
Thanks for the support bundle. I've checked the support bundle.
Most of volumes are still using `longhornio/longhorn-engine:v1.2.3` image, e.g. pvc-001e0476-d91a-4f78-b080-fd21a6dbdd36. You can scale down the workloads using these volumes, upgrade the engine image of the volumes to v1.4.2, and then scale up.

**Comment by Michael-Baylis** [comment]
Well,  don't I feel like I am an idiot!
I think I am missing a concept.   Will review ta.

**Comment by derekbit** [comment]
> Well, don't I feel like I am an idiot!
> I think I am missing a concept. Will review ta.

No worries.  Feel free to contact us if need any help. Thank you.

**Comment by Michael-Baylis** [comment]
I can confirm that when I upgrade the volume engine image,   I can now delete the snapshots.
Thank you for your assistance.
