### ISSUE TITLE
[BUG] Migration test case failed: unable to detach volume migration is not ready yet

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6238]
## Describe the bug (🐛 if you encounter this issue)

In Longhorn v1.4.x-head, run migration related test case like `test_migration_with_rebuilding_replica`, it's possible that test case failed due to `unable to detach volume longhorn-testvol-uubjv2: migration is not ready yet`.

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4422/

It's not a timeout issue. The volume gets stuck in the same state forever. No matter how long we wait, it's always unable to be detached. 

## To Reproduce

Run test case `test_migration_with_rebuilding_replica`

## Log or Support bundle

[supportbundle_ab283102-9396-48b1-a16f-e3d8a56e0225_2023-07-04T09-57-46Z.zip](https://github.com/longhorn/longhorn/files/11948813/supportbundle_ab283102-9396-48b1-a16f-e3d8a56e0225_2023-07-04T09-57-46Z.zip)

## Environment

 - Longhorn version: v1.4.x-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.27.1+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: sles 15-sp4
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by PhanLe1010** [comment]
Thanks for reporting. There is no new AD refactoring going to v1.4.x so perhaps this is not a regression. Will double check soon

**Comment by PhanLe1010** [comment]
Update: this is a regression that exist in 1.4.x-head and 1.3.x-head

**Comment by PhanLe1010** [comment]
## Test Plan

1. Test all migration test cases 10 times and make sure they are ok
2. Double check that this test plan still passed https://github.com/longhorn/longhorn/issues/5992#issuecomment-1563873360

**Comment by khushboo-rancher** [comment]
https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-tests-sles-amd64/225/

**Comment by innobead** [comment]
@yangchiu Please help verify this.

**Comment by khushboo-rancher** [comment]
Verification - LGTM

The [migration test ](https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-tests-sles-amd64/225/)passed on v1.4.x 10 times each. We can close this.

**Comment by khushboo-rancher** [comment]
Reopening this as I've not revalidated the scenario from https://github.com/longhorn/longhorn/issues/5992#issuecomment-1563873360 as @PhanLe1010 suggested https://github.com/longhorn/longhorn/issues/6238#issuecomment-1626005884.
@yangchiu Could you please help with that? Thanks

**Comment by yangchiu** [comment]
Verified passed on v1.4.x-head (longhorn-manager 3ea2dcd) following [the test steps](https://github.com/longhorn/longhorn/issues/5992#issuecomment-1563873360).
