### ISSUE TITLE
[BUG] Restored Volumes stuck in attaching state

### ISSUE THREAD

**Issue by epichb** [longhorn/longhorn#6239]
## Describe the bug 🐛 

After trying to restore a volume from a backup stored on a NFS target, volume is stuck in "Attaching" state, and no apparent progress occurs. 

View in the GUI:

![image](https://github.com/longhorn/longhorn/assets/7453793/d223dafa-1e67-4361-a29e-319b6faa26d1)

## To Reproduce

1. Go to 'Backup'
2. Click on any volume name
3. Perform 'Restore' operation
4. Choose any name for the volume (either the same as the original or different, doesn't seem to matter)
5. See error log/description

## Expected behavior

The volume restores correctly

## Log or Support bundle

Only one log message appears immediately relevant:

```
longhorn-manager-qt4td longhorn-manager time="2023-07-06T00:47:22Z" level=warning msg="Error syncing Longhorn volume longhorn-system/audiobookshel-restore" controller=longhorn-volume error="failed to sync longhorn-system/audiobookshel-restore: failed to reconcile volume state for audiobookshel-restore: no healthy or scheduled replica for starting" node=k3s-k3s-master.cluster.home.chb-online.de
```

This message repeats regularly.

[supportbundle_6352f3f6-e06b-4d70-936a-2cd775ce8c85_2023-07-06T00-50-43Z.zip](https://github.com/longhorn/longhorn/files/11963048/supportbundle_6352f3f6-e06b-4d70-936a-2cd775ce8c85_2023-07-06T00-50-43Z.zip)

## Environment

 - Longhorn version: 1.4.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: Debian 11
   - CPU per node: 4-6 Cores
   - Memory per node: ~ 12GB
   - Disk type(e.g. SSD/NVMe): HDD
   - Network bandwidth between the nodes: 1Gbit/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster:  7

## Additional context

-

**Comment by derekbit** [comment]
I saw an error log messages in
```
2023-07-06T00:42:12.379864065Z E0706 00:42:12.379663       1 share_manager_controller.go:250] failed to sync longhorn-system/jellyfin-media: admission webhook "validator.longhorn.io" denied the request: failed to check if strict-local volume jellyfin-media and its replica are on the same node: moving a strict-local volume jellyfin-media to another node is not supported
2023-07-06T00:42:33.914686265Z time="2023-07-06T00:42:33Z" level=debug msg="Replica controller picked up" controller=longhorn-replica controllerID=k3s-k3s-node-1.cluster.home.chb-online.de dataPath= node=k3s-k3s-node-1.cluster.home.chb-online.de nodeID= ownerID= replica=jellyfin-config-restore-r-e471295b
2023-07-06T00:42:33.914796253Z time="2023-07-06T00:42:33Z" level=debug msg="Instance handler updated instance jellyfin-config-restore-r-e471295b state, old state , new state stopped"
```

The volume validating webhook rejects the restore job of the strict-local volume.

Before fixing it, for a workaround. can you restore the volume using `dataLocality: best-effort` instead? After finishing the restore job, you can change it to `strict-local`?

**Comment by epichb** [comment]
`jellyfin-media` isn't actually one of the restored volumes, only `audiobookshel-restore`, `audiobookshel-drv and `jellyfin-config-restore` are. `jellyfin-media` fails because the pod is scheduled on another node, which, as far as I can tell, is unrelated to the restore jobs. 

Furthermore, I have no option to change to data locality for a restored backup, as far as I can see:

![image](https://github.com/longhorn/longhorn/assets/7453793/ef6f15c3-ce45-42e8-8247-b0b23799e2f9)

**Comment by derekbit** [comment]
> `jellyfin-media` isn't actually one of the restored volumes, only `audiobookshel-restore`, `audiobookshel-drv` and `jellyfin-config-restore` are. `jellyfin-media` fails because the pod is scheduled on another node, which, as far as I can tell, is unrelated to the restore jobs.
> 
> Furthermore, I have no option to change to data locality for a restored backup, as far as I can see:
> 
> ![image](https://user-images.githubusercontent.com/7453793/251321083-ef6f15c3-ce45-42e8-8247-b0b23799e2f9.png)

Can you change the setting `default-data-locality` to `disabled` or `best-effort` and try to restore them again?

**Comment by epichb** [comment]
That did the trick! Thank you so much!

Restore of the smaller volume already went through, and the larger volume seems to be progressing

**Comment by innobead** [comment]
Need this to 1.5.1 as well.

**Comment by innobead** [comment]
@derekbit Need to move to ready for testing?

**Comment by innobead** [comment]
@derekbit I just moved this to ready for testing since you forgot to do that. 

@roger-ryao Please help test that.

**Comment by derekbit** [comment]
> @derekbit Need to move to ready for testing?

oh... sorry, didn't notice the notification. Too much focus on community issues handling.

**Comment by roger-ryao** [comment]
**Verified on v1.4.3-rc2 20230713**

- longhorn v1.4.3-rc2 https://github.com/longhorn/longhorn/commit/d8b581988f672788163b3cb81a0806ca1b163e47
- longhorn-manager v1.4.3-rc2 https://github.com/longhorn/longhorn-manager/commit/995297b526b8797856f7f1c1fc6d4a0385a2b711

**The test steps**

https://github.com/longhorn/longhorn/issues/6239#issuecomment-1622943907
1. Create a volume and back up the volume
2. Set setting `default-data-locality` to `strict-local`
3. Restore a volume from the backup in step1

**Result Passed**

1. I was able to reproduce the issue on v1.4.2.
2. After setting `default-data-locality` to `strict-local` and restoring the volume from the backup, the volume no longer gets stuck in the attaching state.
