### ISSUE TITLE
[BUG]csi-provisioner pod restart with information :failed to update lock:etcdserver :request time out failed to renew lease longhorn-system/driver-longhorn-io: timed out waiting for the condition

### ISSUE THREAD

**Issue by shaolila** [longhorn/longhorn#6251]
## Describe the bug (🐛 if you encounter this issue)
csi-provisioner pod restart form time to time with information :
failed to update lock:etcdserver :request time out 
failed to renew lease longhorn-system/driver-longhorn-io: timed out waiting for the condition

## To Reproduce

3. Perform '....'

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.3.2
 - csi-provisioner version :v2.1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 
   - Number of management node in the cluster:3
   - Number of worker node in the cluster:3
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g
[Uploading csi-provisioner-error.log…]()
. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

[Uploading csi-provisioner-error.log…]()

**Comment by derekbit** [comment]
Looks related to https://github.com/longhorn/longhorn/issues/4061

**Comment by shaolila** [comment]
> @shaolila Can you provide log?

[Uploading csi-provisioner-error.log…]()

**Comment by shaolila** [comment]
[csi-provisioner-error.log](https://github.com/longhorn/longhorn/files/11980071/csi-provisioner-error.log)

**Comment by shaolila** [comment]
> @shaolila Can you provide log?

[csi-provisioner-error.log](https://github.com/longhorn/longhorn/files/11980076/csi-provisioner-error.log)

**Comment by derekbit** [comment]
Thanks for the log.
It is an upstream issue and fixed in v3.4.0.
https://github.com/kubernetes-csi/external-provisioner/issues/839

Currently, v1.3.x and v1.4.x are using v2.1.2 and v1.5.0 is using v3.4.1.

**Comment by shaolila** [comment]
> 

i wonder if i can solve it by update longhorn-csi-provisioner form  v2.1.2 to v3.4.1 without update longhorn1.3.2 ?
