### ISSUE TITLE
[BUG] upgrading from 1.4.2 to 1.5.0 (helm) panic: unrecognized command

### ISSUE THREAD

**Issue by harrytang** [longhorn/longhorn#6255]
## Describe the bug (🐛 if you encounter this issue)

I installed v1.4.2 using helm and followed the upgrade section from 1.5.0 doc for helm. After running helm upgrade, everthing seems OK except with the `longhorn-recover-backend` and `longhorn-conversion-webhook`

## To Reproduce

1. Install longhorn v1.4.2 using helm
2. Add a few vols
3. Upgrade to v1.5.0 using helm
4. Check logs
5. See error

## Expected behavior

All pods running normally.

## Log or Support bundle

Logs longhorn-recover-backend:
```longhorn-recover-backend
panic: unrecognized command: recovery-backend

goroutine 1 [running]:
main.cmdNotFound(0x40009b6a58?, {0xffffd17dc060?, 0x40009b6a78?})
	/go/src/github.com/longhorn/longhorn-manager/main.go:15 +0x64
github.com/urfave/cli.ShowCommandHelp(0x40006cbe40, {0xffffd17dc060, 0x10})
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/help.go:213 +0x31c
github.com/urfave/cli.glob..func1(0x2?)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/help.go:21 +0x3c
github.com/urfave/cli.HandleAction({0x1c98680?, 0x22e6cd8?}, 0x4000029880?)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:524 +0x58
github.com/urfave/cli.(*App).Run(0x4000029880, {0x4000134040, 0x4, 0x4})
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:286 +0x560
main.main()
	/go/src/github.com/longhorn/longhorn-manager/main.go:66 +0x6f0
```

Logs (longhorn-conversion-webhook)
```text
panic: unrecognized command: conversion-webhook

goroutine 1 [running]:
main.cmdNotFound(0x40008bea58?, {0xffffe4bf406c?, 0x40008bea78?})
	/go/src/github.com/longhorn/longhorn-manager/main.go:15 +0x64
github.com/urfave/cli.ShowCommandHelp(0x40006c8000, {0xffffe4bf406c, 0x12})
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/help.go:213 +0x31c
github.com/urfave/cli.glob..func1(0x2?)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/help.go:21 +0x3c
github.com/urfave/cli.HandleAction({0x1c98680?, 0x22e6cd8?}, 0x40007ba540?)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:524 +0x58
github.com/urfave/cli.(*App).Run(0x40007ba540, {0x400012e040, 0x4, 0x4})
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:286 +0x560
main.main()
	/go/src/github.com/longhorn/longhorn-manager/main.go:66 +0x6f0
```

## Environment

 - Longhorn version: 1.4.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Microk8s v1.26.5
   - Number of management node in the cluster: 5
   - Number of worker node in the cluster: 0
 - Node config
   - OS type and version: Ubuntu 22.04
   - CPU per node: 4
   - Memory per node: 32
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 10GB
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VPS
 - Number of Longhorn volumes in the cluster: 8

**Comment by derekbit** [comment]
Please refer to the workaround https://github.com/longhorn/longhorn/issues/6252.

**Comment by derekbit** [comment]
Duplicate https://github.com/longhorn/longhorn/issues/6252
