### ISSUE TITLE
[BUG] Unable to receive support bundle from UI when it's large (400MB+)

### ISSUE THREAD

**Issue by samip5** [longhorn/longhorn#6256]
## Describe the bug (🐛 if you encounter this issue)

support bundle manager is unable to give me the support bundle when it's large in size.

## To Reproduce

1. Deploy 1.5.0 longhorn with UI
2. Go to UI and click on generate support bundle
3. Wait for it to finnish
4. See that the download got interrupted.

## Expected behavior

It wouldn't get interrupted before I get the bundle.

## Log or Support bundle

```
time="2023-07-07T13:20:18Z" level=info msg="Support bundle /tmp/support-bundle-kit/supportbundle_6416b220-aa6b-4cde-aa3f-2d7f90963760_2023-07-07T13-19-24Z.zip ready to download"
time="2023-07-07T13:20:18Z" level=info msg="Succeed to run phase done. Progress (100)."
time="2023-07-07T13:20:49Z" level=error msg="readfrom tcp 10.244.2.194:8080->10.244.0.106:40992: i/o timeout"
2023/07/07 13:20:49 http: superfluous response.WriteHeader call from github.com/rancher/support-bundle-kit/pkg/utils.HttpResponseErrorMsg (http.go:36)
```

## Environment

 - Longhorn version: 1.5.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.26.3+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 6
 - Node config
   - OS type and version: Debian 12 & Ubuntu 22.04
   - CPU per node: Varies
   - Memory per node: 8-32GB
   - Disk type(e.g. SSD/NVMe): SSD/NVME
   - Network bandwidth between the nodes: 1G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 15

## Additional context

It seems that the support bundle pod is not running long enough to download the file.

**Comment by yangchiu** [comment]
Probably need @c3y1huang to help with this🙏

**Comment by innobead** [comment]
@c3y1huang Can you help check this? The timeout seems to be caused by the support bundle agent pod?

cc @weizhe0422

**Comment by c3y1huang** [comment]
Note:
- https://github.com/rancher/support-bundle-kit/blob/d5bb2ba66d660ff1ed1f45dff0cbce37219817dd/pkg/manager/httpserver.go#L99

**Comment by samip5** [comment]
> @samip5 I'm having difficulty preparing an environment to generate a support bundle large enough to trigger the timeout. 
> Are you able to help by using `c3y1huang/research:30-lh-support-bundle-kit` to generate the support bundle?
> 
> You can change the support-bundle image via the UI:
> ![Screenshot from 2023-07-10 15-27-55](https://github.com/longhorn/longhorn/assets/22583541/694eb7a3-ae0f-4e08-b52a-db1af2039fd0)
> 

It requires enough logs to copy eg a few gigs of syslogs to get large output.

**Comment by innobead** [comment]
@samip5 do you mean the bundle including the active log and archived logs?

@c3y1huang I feel copying `It requires enough logs to copy eg a few gigs of syslogs to get large output.` doesn't make sense. Can you help investigate this? or @weizhe0422 needs to clarify this as well since he was working on that.

**Comment by c3y1huang** [comment]
> The bundler takes active and archived logs (eg syslog.*), and if those are large in size, eg few gigabytes, the resulting archive is also large.

```
time="2023-07-07T13:20:18Z" level=info msg="Succeed to run phase done. Progress (100)."
time="2023-07-07T13:20:49Z" level=error msg="readfrom tcp 10.244.2.194:8080->10.244.0.106:40992: i/o timeout"
```
@samip5 , would you give `c3y1huang/research:30-lh-support-bundle-kit` a try to see if the download passes the 30-second timeout?

**Comment by innobead** [comment]
@c3y1huang @weizhe0422 https://github.com/longhorn/longhorn/issues/6278#issuecomment-1630110717 Please take this as a priority and go cooperate. Thanks.

**Comment by c3y1huang** [comment]
Test WIP

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn `a43faa`, longhorn-manager `a52328`)

Test case `test_support_bundle_should_not_timeout`(download 5GB support bundle) passed on [pipeline](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4552/testReport/tests/test_support_bundle/).
