### ISSUE TITLE
"The disk has changed file system" error when using a new machine

### ISSUE THREAD

**Issue by JRial95** [longhorn/longhorn#626]
As I changed one of my nodes to a new machine with the same name as the old machine (kubernode1), the ```longhorn-manager``` gives me this error when I try to edit disks:
```
level=warning msg="Update disk on node kubernode1 warning: The disk /var/lib/rancher/longhorn/ has changed file system, please mount it back or remove it"
```
The Longhorn UI displays the node as "Disabled" with a size of 0 Bi.

If I add nodes with a name that has not been used in the past, there is no problem.

Have you ever encountered this problem?

**Comment by yasker** [comment]
@JRial95 The error is expected since Longhorn used node name to identify the node. The node was changed so the filesystem wasn't the one recorded by Longhorn, thus the warning. You should able to remove the disk after removing all the replicas on it, then create a new disk for the node.

**Comment by JRial95** [comment]
@yasker Thank you for your answer. The problem is solved. It is not possible to remove and create a new disk with the same path at once with the UI. It is required to click "Save" and reopen the modal to create a new disk.
