### ISSUE TITLE
[BUG] Backup status is not updated by Longhorn

### ISSUE THREAD

**Issue by ttpcodes** [longhorn/longhorn#627]
Right now, the `longhorn-engine` does not conduct monitoring of the `BackupStore`, meaning that if a `Backup` for a `Volume` gets deleted, `longhorn-engine` will still report the `Backup` existing, even if it doesn't. This can be inconvenient when trying to restore a `Backup` that doesn't actually exist or trying to view the status of a `Backup` in `longhorn-ui` when the information is actually outdated.

We need to implement some way to monitor the status of the `BackupStore` so the `longhorn-engine` is aware that the `Backup` is deleted and can report accurate information about the status of any `Backups`.

**Comment by innobead** [comment]
This will be fixed by #1761 . cc @jenting

**Comment by jenting** [comment]
There is a backup monitor goroutine in `setting_controller` now https://github.com/longhorn/longhorn-manager/blob/254aa17/controller/setting_controller.go#L687-L693. The purpose is to read backup volume metadata and updates the last backup name and last backup time to the Volume CR.

**Comment by jenting** [comment]
The problem now is if the user deletes the latest backup in BackupTarget, the backup volume still shows the latest backup as the deleted backup one. For example, a volume (vol-A) has 3 backups (backup-1, backup-2, backup-3), and the backup-3 is the latest backup. If the user deletes the backup-3 in BackupTarget, the vol-A still shows the latest backup is backup-3, not backup-2.

**Comment by jenting** [comment]
The code is there, so the issue could be closed. cc @innobead

**Comment by joshimoo** [comment]
@jenting this feature was about the BackupStatus inside of the engine process, once your Backup Refactoring #1761 #2623 
lands we should be able to not have to rely on the engine in memory BackupStatus anymore after the backup has entered a terminal state (complete, error)

**Comment by innobead** [comment]
Duplicated of #3035
