### ISSUE TITLE
UI should prioritize displaying the progress of an uncompleted Backup

### ISSUE THREAD

**Issue by ttpcodes** [longhorn/longhorn#628]
Right now, there is no priority for the `longhorn-ui` to determine which `Backup`'s progress to display. That means that if there are two or more `Backups` which exist on the same `Snapshot`, the `longhorn-ui` will just randomly switch between the `Backups`, making it hard to view the `Backups` or track the progress of an uncompleted `Backup`.

We should have a way to prioritize which `Backup`'s progress gets displayed so it's easier for the user to look at the `Backup` progress of a `Snapshot`.

**Comment by yasker** [comment]
The merged PR shows the average of two or more progress, which is probably better than just show the latest.

**Comment by meldafrawi** [comment]
Validation: PASSED

Steps to test:
 - in Settings page, make sure backup target is defined.
 - Create a volume.
 - Attach the volume to a node.
 - format the volume, mount it to a directory on the attached node.
 - Write relatively big sized data files to the the volume
 - In volume details page, Create a snapshot
 - in Snapshot section click on the created snapshot, a drop down menu will appear, click backup.
 >> Expected result: backup progress will appear on the snapshot
 - before the backup completes create a new backup from the the same snapshot.
 >> Expected result: backup progress be adjusted to be the average of backup progresses.
