### ISSUE TITLE
[BUG] 1.5.0: AttachVolume.Attach failed for volume, the volume is currently attached to different node

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6287]
### Discussed in https://github.com/longhorn/longhorn/discussions/6281

<div type='discussions-op-text'>

<sup>Originally posted by **[PatrickHuetter](https://github.com/PatrickHuetter)** July 10, 2023</sup>
After upgrading to 1.5.0 it seems that I am seeing an increasing number of "AttachVolume.Attach failed for volume [...]:, the volume is currently attached to different node [...]" errors. Anybody else seeing that?</div>

The longhorn manager log shows
```
2023-07-11T00:58:21.954040163+02:00 W0710 22:58:21.953984       1 logging.go:59] [core] [Channel #436613 SubChannel #436614] grpc: addrConn.createTransport failed to connect to {
2023-07-11T00:58:21.954057356+02:00   "Addr": "10.42.1.96:8502",
2023-07-11T00:58:21.954059801+02:00   "ServerName": "10.42.1.96:8502",
2023-07-11T00:58:21.954061814+02:00   "Attributes": null,
2023-07-11T00:58:21.954063457+02:00   "BalancerAttributes": null,
2023-07-11T00:58:21.954065702+02:00   "Type": 0,
2023-07-11T00:58:21.954067385+02:00   "Metadata": null
2023-07-11T00:58:21.954069028+02:00 }. Err: connection error: desc = "transport: Error while dialing: dial tcp 10.42.1.96:8502: connect: cannot assign requested address"
2023-07-11T00:58:21.954202480+02:00 time="2023-07-10T22:58:21Z" level=error msg="Error syncing Longhorn engine" controller=longhorn-engine engine=longhorn-system/pvc-691c523a-20c7-4f90-a0a3-3a369dfeecb0-e-a3394e19 error="failed to sync engine for longhorn-system/pvc-691c523a-20c7-4f90-a0a3-3a369dfeecb0-e-a3394e19: failed to get Version of Instance Manager Disk Service Client for instance-manager-daec900e651b283e9d7a1c3e9e697855, state: running, IP: 10.42.1.96, TLS: false: failed to get disk service version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 10.42.1.96:8502: connect: cannot assign requested address\"" node=en360-k8s-ax2
2023-07-11T00:58:21.954257114+02:00 time="2023-07-10T22:58:21Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"pvc-691c523a-20c7-4f90-a0a3-3a369dfeecb0-e-a3394e19\", UID:\"cd4312cc-1618-49d2-b3e6-3b78e6cd7dab\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"606703948\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedStarting' Error starting pvc-691c523a-20c7-4f90-a0a3-3a369dfeecb0-e-a3394e19: failed to get Version of Instance Manager Disk Service Client for instance-manager-daec900e651b283e9d7a1c3e9e697855, state: running, IP: 10.42.1.96, TLS: false: failed to get disk service version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 10.42.1.96:8502: connect: cannot assign requested address\""
2023-07-11T00:58:21.973377802+02:00 W0710 22:58:21.973322       1 logging.go:59] [core] [Channel #436621 SubChannel #436622] grpc: addrConn.createTransport failed to connect to {
2023-07-11T00:58:21.973395685+02:00   "Addr": "10.42.1.96:8502",
2023-07-11T00:58:21.973399182+02:00   "ServerName": "10.42.1.96:8502",
2023-07-11T00:58:21.973402158+02:00   "Attributes": null,
2023-07-11T00:58:21.973404422+02:00   "BalancerAttributes": null,
```
## Workaround
The workaround is restart longhorn-manager pod that failed to attach/detach a volume.

**Comment by innobead** [comment]
@derekbit Please add this to the outstanding issue WIKI page for 1.5.0.

**Comment by derekbit** [comment]
> @derekbit Please add this to the outstanding issue WIKI page for 1.5.0.

Already added.

**Comment by innobead** [comment]
@derekbit `8502` is for the disk service port, so why it would impact the client connection issue even if the previous clients were not closed correctly? Did it mean running out of port usage for the client?

**Comment by innobead** [comment]
Also, I saw many places using instance manager client, so what other issues users could encounter?

**Comment by PhanLe1010** [comment]
I think the server side (disk service) on the instance manager run out of port so client (longhorn-manager) cannot open new connection to it. Restarting longhorn-manager or instance manager pod will close orphan connections. But restarting longhorn-manager pod is prefer since it not crashing the replicas

**Comment by innobead** [comment]
> I think the server side (disk service) on the instance-manager pod runs out of port so the client (longhorn-manager) cannot open a new connection to it. Either restarting longhorn-manager or instance-manager pod will close orphan connections. But restarting longhorn-manager pod is preferred since it doesn't crash the replicas

It makes sense, so it does mean this issue users would eventually encounter over time.

**Comment by innobead** [comment]
> ## Pre Ready-For-Testing Checklist
> * [x]  Where is the reproduce steps/test steps documented?
>   The reproduce steps/test steps are at:
> 
> 1. Create a pod with a volume
> 2. Check the port usage by `lsof -i -P -n`
> 3. Deltee the pod with a volume
> 4. Check the port usage by `lsof -i -P -n`. The port is still in use.

@derekbit Can you help describe this clearly where to check the port usage (as per the conversation in the source issue, it should be longhorn-manager pod)? so @longhorn/qa can help with the testing.

**Comment by PhanLe1010** [comment]
I think I was wrong in this comment https://github.com/longhorn/longhorn/issues/6287#issuecomment-1630102345. It should be:

I think the client side (longhorn-manager pod) runs out of port and cannot open a new connection to server-side (disk service) on the instance-manager pod. Either restarting longhorn-manager or instance-manager pod will close orphan connections. But restarting longhorn-manager pod is preferred since it doesn't crash the replicas. 

Server side is using a fixed port (8502) for TCP connection so it cannot run out of ports. 


> It makes sense, so it does mean this issue users would eventually encounter over time. So, for any engine operations, they would potentially have issues.

Yes, over time, longhorn-manager will run out of ports

**Comment by innobead** [comment]
Yeah, thanks for the re-clarification, then this was what I expected from the original comment.

**Comment by derekbit** [comment]
> @derekbit Can you help describe this clearly where to check the port usage (as per the conversation in the source issue, it should be longhorn-manager pod)? so @longhorn/qa can help with the testing.

Updated. The check can be done in longhorn-manager or instance-manager pods.

**Comment by innobead** [comment]
I see. They both are privileged pods, so we can check in either pod.

**Comment by yangchiu** [comment]
Tested on master-head (longhorn-manager a523288) following [the test steps](https://github.com/longhorn/longhorn/issues/6287#issuecomment-1630012738).

Before with a pod using a volume, the command returns:
```
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
longhorn-   1 root    3u  IPv6  41748      0t0  TCP *:9501 (LISTEN)
longhorn-   1 root    7u  IPv4  41752      0t0  TCP 10.42.1.8:56586->10.43.0.1:443 (ESTABLISHED)
longhorn-   1 root    8u  IPv6  42462      0t0  TCP [::1]:51944->[::1]:9501 (ESTABLISHED)
longhorn-   1 root    9u  IPv6  43414      0t0  TCP [::1]:9501->[::1]:51944 (ESTABLISHED)
longhorn-   1 root   10u  IPv6  45215      0t0  TCP *:9502 (LISTEN)
longhorn-   1 root   11u  IPv6  43636      0t0  TCP [::1]:34258->[::1]:9502 (ESTABLISHED)
longhorn-   1 root   12u  IPv6  44504      0t0  TCP [::1]:9502->[::1]:34258 (ESTABLISHED)
longhorn-   1 root   13u  IPv6  63347      0t0  TCP 10.42.1.8:9502->10.42.0.0:55184 (ESTABLISHED)
longhorn-   1 root   14u  IPv6  45224      0t0  TCP *:9503 (LISTEN)
longhorn-   1 root   15u  IPv4  43665      0t0  TCP 127.0.0.1:6060 (LISTEN)
longhorn-   1 root   16u  IPv4  45263      0t0  TCP 10.42.1.8:9500 (LISTEN)
longhorn-   1 root   17u  IPv4  47250      0t0  TCP 10.42.1.8:41784->10.42.1.10:8503 (ESTABLISHED)
longhorn-   1 root   19u  IPv4  47249      0t0  TCP 10.42.1.8:48396->10.42.1.10:8500 (ESTABLISHED)
longhorn-   1 root   20u  IPv4  48245      0t0  TCP 10.42.1.8:34770->10.42.1.10:8502 (ESTABLISHED)
``` 
After the pod and the volume deleted, the command returns:
```
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
longhorn-   1 root    3u  IPv6  41748      0t0  TCP *:9501 (LISTEN)
longhorn-   1 root    7u  IPv4  41752      0t0  TCP 10.42.1.8:56586->10.43.0.1:443 (ESTABLISHED)
longhorn-   1 root    8u  IPv6  42462      0t0  TCP [::1]:51944->[::1]:9501 (ESTABLISHED)
longhorn-   1 root    9u  IPv6  43414      0t0  TCP [::1]:9501->[::1]:51944 (ESTABLISHED)
longhorn-   1 root   10u  IPv6  45215      0t0  TCP *:9502 (LISTEN)
longhorn-   1 root   11u  IPv6  43636      0t0  TCP [::1]:34258->[::1]:9502 (ESTABLISHED)
longhorn-   1 root   12u  IPv6  44504      0t0  TCP [::1]:9502->[::1]:34258 (ESTABLISHED)
longhorn-   1 root   14u  IPv6  45224      0t0  TCP *:9503 (LISTEN)
longhorn-   1 root   15u  IPv4  43665      0t0  TCP 127.0.0.1:6060 (LISTEN)
longhorn-   1 root   16u  IPv4  45263      0t0  TCP 10.42.1.8:9500 (LISTEN)
longhorn-   1 root   17u  IPv4  47250      0t0  TCP 10.42.1.8:41784->10.42.1.10:8503 (ESTABLISHED)
longhorn-   1 root   19u  IPv4  47249      0t0  TCP 10.42.1.8:48396->10.42.1.10:8500 (ESTABLISHED)
longhorn-   1 root   20u  IPv4  48245      0t0  TCP 10.42.1.8:34770->10.42.1.10:8502 (ESTABLISHED)
```
The only difference is:
```
longhorn-   1 root   13u  IPv6  63347      0t0  TCP 10.42.1.8:9502->10.42.0.0:55184 (ESTABLISHED)
```
Is this what we expect to? @derekbit

**Comment by PhanLe1010** [comment]
@yangchiu No, the expectation is that with master-head, the connection `10.42.1.8:34770->10.42.1.10:8502` should disappear after pod is deleted

**Comment by derekbit** [comment]
Yes, as @PhanLe1010 said, you can create more volumes using `pod_with_pvc.yaml`, delete the volumes, and observe the leakage.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager a5b67e5). After created/attached/detached/deleted multiple volumes and check `longhorn-manager` by `lsof -i -P -n`, there's always only one connection to port `8502` like `10.42.3.6:42866->10.42.3.9:8502`

**Comment by PhanLe1010** [comment]
Do we see multiple connections in v1.5.0 with the same test steps? @yangchiu 

> Verified passed on master-head (longhorn-manager a5b67e5). After created/attached/detached/deleted multiple volumes and check `longhorn-manager` by `lsof -i -P -n`, there's always only one connection to port `8502` like `10.42.3.6:42866->10.42.3.9:8502`

**Comment by derekbit** [comment]
From my side, yes.

**Comment by Orabig** [comment]
Is this bug supposed to be fixed in 1.5.1 ?
We have Longhorn 1.5.1, and we still have this issue.

Pods are stuck in a "ContainerCreating" state, not on the same node than the PVC.

Latest events are like :

```
Events:
  Type     Reason              Age                    From                     Message
  ----     ------              ----                   ----                     -------
  Warning  FailedMount         4m57s (x525 over 25h)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data kube-api-access-wqzcx]: timed out waiting for the condition
  Warning  FailedAttachVolume  4m30s (x756 over 25h)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-caa9a39a-e480-490f-a601-dbf5d32e3cb5" : rpc error: code = Internal desc = volume pvc-caa9a39a-e480-490f-a601-dbf5d32e3cb5 failed to attach to node node01.xxxxx.net with attachmentID csi-7eeeb49a92e5831cdd21513da16f46a8ab60a3c98e28f8c6a91ce2b947459bcf: the volume is currently attached to different node gamora-node02.mrs.antidot.net
  Warning  FailedMount         26s (x152 over 25h)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[kube-api-access-wqzcx data]: timed out waiting for the condition
```

Corresponding Longhorn PVC and PV are bound and attached to another node

The only workaround we found is : 
- to go in longhorn interface and force "detach" on the corresponding volume
- delete the pod

Then, the pod schedules again correctly with the Longhorn volume.

**Comment by derekbit** [comment]
@Orabig 

Yeah, fixed. If you are still running into an issue, can you provide a support bundle for analysis? Thank you.

**Comment by derekbit** [comment]
@Orabig 
It looks the issue is different from the original issue. Can you help create a new ticket for it? Thank you.
Just checked the support bundle.

The volume `pvc-caa9a39a-e480-490f-a601-dbf5d32e3cb5` is already attached to `node01`.
There are two attachmentTickets for the volume.  One attachmentTicket's name `null` is weird.

cc @PhanLe1010 

```
  spec:
    attachmentTickets:
      csi-7eeeb49a92e5831cdd21513da16f46a8ab60a3c98e28f8c6a91ce2b947459bcf:
        generation: 0
        id: csi-7eeeb49a92e5831cdd21513da16f46a8ab60a3c98e28f8c6a91ce2b947459bcf
        nodeID: gamora-node01.mrs.antidot.net
        parameters:
          disableFrontend: "false"
          lastAttachedBy: "null"
        type: csi-attacher
      "null":
        generation: 0
        id: "null"
        nodeID: gamora-node02.mrs.antidot.net
        parameters:
          disableFrontend: "false"
          lastAttachedBy: "null"
        type: longhorn-api
    volume: pvc-caa9a39a-e480-490f-a601-dbf5d32e3cb5
```

**Comment by derekbit** [comment]
@Orabig 
What version of LH did you upgrade to 1.5.1 from?

**Comment by derekbit** [comment]
> @Orabig It looks like the issue is different from the original issue. Can you help create a new ticket for it? Thank you.
> 
> Just checked the support bundle. The volume `pvc-caa9a39a-e480-490f-a601-dbf5d32e3cb5` is already attached to `node01` There are two attachmentTickets for the volume, and the satisfied ticket's attach type is `longhorn-api` which means the volume was requested to attach from LH UI/API.
> 
> Since v1.5.0, each longhorn volume is associated with a `volumeAttachement` resource. Currently, the volume is already attached to node `gamora-node01` by the request from Longhorn UI/API, so the request to attach to `gamora-node02` from CSI is not allowed.
> 
> A weird point is the name of the ticket is `null`...
> 
> cc @PhanLe1010
> 
> ```
>   spec:
>     attachmentTickets:
>       csi-7eeeb49a92e5831cdd21513da16f46a8ab60a3c98e28f8c6a91ce2b947459bcf:
>         generation: 0
>         id: csi-7eeeb49a92e5831cdd21513da16f46a8ab60a3c98e28f8c6a91ce2b947459bcf
>         nodeID: gamora-node01.xxxxx
>         parameters:
>           disableFrontend: "false"
>           lastAttachedBy: "null"
>         type: csi-attacher
>       "null":
>         generation: 0
>         id: "null"
>         nodeID: gamora-node02.xxxxx
>         parameters:
>           disableFrontend: "false"
>           lastAttachedBy: "null"
>         type: longhorn-api
>     volume: pvc-caa9a39a-e480-490f-a601-dbf5d32e3cb5
> ```

@PhanLe1010 Please correct me if there is any misunderstanding, thank you. BTW, do you have idea why the name of the ticket is `null`?

**Comment by Orabig** [comment]
> It looks like the issue is different from the original issue. Can you help create a new ticket for it? Thank you.

Sure, but I need some explanation about your answer first : what is this attachmentTickets attribute and where can it be found ? I can't find it neither in my PersistentVolume nor my PersistentVolumeClaim object. Can you tell me how I can check this weird state by myself ?

Anyway, I will check for now on if I ever get more than one volumeAttachment objet for each volume. Thanks !

**Comment by Orabig** [comment]
(it's weird to answer my own message which has been edited with answers, but well :) )

Thanks for your note about **VolumeAttachment** @derekbit , but I was asking about **attachmentTickets**. I can't find them anywhere in my configuration (especially not in my VolumeAttachments)

**Comment by derekbit** [comment]
> (it's weird to answer my own message which has been edited with answers, but well :) )
> 
> Thanks for your note about **VolumeAttachment** @derekbit , but I was asking about **attachmentTickets**. I can't find them anywhere in my configuration (especially not in my VolumeAttachments)

The tickets are recorded in the longhorn `volumeAttachement.spec.attachmentTickets`. You can list them by
```
kubectl -n longhorn-system get volumeattachments -o yaml
```

**Comment by Orabig** [comment]
No, as I told you before, I really don't see any of this ! The following returns nothing :

```
$ kubectl -n longhorn-system get volumeattachments -o yaml | grep ticket -i
```

Here is what I get when I access some volumeAttachments : 

```
$ 
kubectl -n longhorn-system get volumeattachments csi-ffeaa30282a6d8a11b3e31ed368a6f71685b88e18c50d76a3399447f71e65e8f -o yaml
apiVersion: storage.k8s.io/v1
kind: VolumeAttachment
metadata:
  annotations:
    csi.alpha.kubernetes.io/node-id: gamora-node03.xxxx.net
  creationTimestamp: "2023-09-06T01:08:00Z"
  finalizers:
  - external-attacher/driver-longhorn-io
  name: csi-ffeaa30282a6d8a11b3e31ed368a6f71685b88e18c50d76a3399447f71e65e8f
  resourceVersion: "570706987"
  uid: f5f799b2-9903-4b93-8e0c-12ebfb2abb34
spec:
  attacher: driver.longhorn.io
  nodeName: gamora-node03.xxxx.net
  source:
    persistentVolumeName: pvc-eec020cb-9e94-462c-9a83-30cbab4d3a58
status:
  attached: true
```

**Comment by derekbit** [comment]
> No, as I told you before, I really don't see any of this ! The following returns nothing :
> 
> ```
> $ kubectl -n longhorn-system get volumeattachments -o yaml | grep ticket -i
> ```
> 
> Here is what I get when I access some volumeAttachments :
> 
> ```
> $ 
> kubectl -n longhorn-system get volumeattachments csi-ffeaa30282a6d8a11b3e31ed368a6f71685b88e18c50d76a3399447f71e65e8f -o yaml
> apiVersion: storage.k8s.io/v1
> kind: VolumeAttachment
> metadata:
>   annotations:
>     csi.alpha.kubernetes.io/node-id: gamora-node03.xxxx.net
>   creationTimestamp: "2023-09-06T01:08:00Z"
>   finalizers:
>   - external-attacher/driver-longhorn-io
>   name: csi-ffeaa30282a6d8a11b3e31ed368a6f71685b88e18c50d76a3399447f71e65e8f
>   resourceVersion: "570706987"
>   uid: f5f799b2-9903-4b93-8e0c-12ebfb2abb34
> spec:
>   attacher: driver.longhorn.io
>   nodeName: gamora-node03.xxxx.net
>   source:
>     persistentVolumeName: pvc-eec020cb-9e94-462c-9a83-30cbab4d3a58
> status:
>   attached: true
> ```

Oh! OK. Should use `volumeattachments.longhorn.io` (longhorn's volumeAttachement) rather thant `volumeattachments` (kubernetes volumeAttachments)
```
kubectl -n longhorn-system get volumeattachments.longhorn.io -o yaml
```

**Comment by Orabig** [comment]
Thanks you ! I had no idea that there were two different objects with the very same name !

**Comment by derekbit** [comment]
Just checked with my colleague @PhanLe1010 . The `null` name might be due to an user/application attached the volumes by Longhorn API or old longhorn-ui.
