### ISSUE TITLE
Failing to upgrade to 1.5.0 (from 1.4.2) - conversion webhooks

### ISSUE THREAD

**Issue by EugenMayer** [longhorn/longhorn#6297]
Applying the (official) helm chart to a 1.25.9 rke2 installation (3 node cluster).

Several pending pods:

pod `longhorn-conversion-webhook-6bb85f48f7-zl5xr`
```
panic: unrecognized command: conversion-webhook

goroutine 1 [running]:
main.cmdNotFound(0xc000ddca78?, {0x7ffeb398a0ac?, 0xc000ddcaa0?})
	/go/src/github.com/longhorn/longhorn-manager/main.go:15 +0x67
github.com/urfave/cli.ShowCommandHelp(0xc000e11b80, {0x7ffeb398a0ac, 0x12})
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/help.go:213 +0x404
github.com/urfave/cli.glob..func1(0x1?)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/help.go:21 +0x34
github.com/urfave/cli.HandleAction({0x230e860?, 0x295d000?}, 0xc000b70a80?)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:524 +0x50
github.com/urfave/cli.(*App).Run(0xc000b70a80, {0xc000050080, 0x4, 0x4})
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:286 +0x7db
main.main()
	/go/src/github.com/longhorn/longhorn-manager/main.go:66 +0x8db
```

pod `longhorn-recovery-backend-858f966d48-xkggz`

```
panic: unrecognized command: recovery-backend

goroutine 1 [running]:
main.cmdNotFound(0xc000d3ea78?, {0x7fffcbce2095?, 0xc000d3eaa0?})
	/go/src/github.com/longhorn/longhorn-manager/main.go:15 +0x67
github.com/urfave/cli.ShowCommandHelp(0xc00011c160, {0x7fffcbce2095, 0x10})
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/help.go:213 +0x404
github.com/urfave/cli.glob..func1(0x1?)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/help.go:21 +0x34
github.com/urfave/cli.HandleAction({0x230e860?, 0x295d000?}, 0xc0003c6380?)
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:524 +0x50
github.com/urfave/cli.(*App).Run(0xc0003c6380, {0xc000134040, 0x4, 0x4})
	/go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:286 +0x7db
main.main()
	/go/src/github.com/longhorn/longhorn-manager/main.go:66 +0x8db
```

3 pods `longhorn-admission-webhook-xxxx`

```
ailed to load logs: container "longhorn-admission-webhook" in pod "longhorn-admission-webhook-7c9b76b495-dqkcp" is waiting to start: PodInitializing
Reason: BadRequest (400)
```

## What i tried
- tried to go back to 1.4.2 - did not help
- removed all backup jobs
- finding related issue - maybe https://github.com/longhorn/longhorn/issues/6259 but i'am not sure.

## Urgency

Quiet high for me, backups are no longer working, seems like the pods are operational (i guess since the volumes are stil mounted).

Thanks!

**Comment by janpfischer** [comment]
Hi all, 
I have the exact same problem after upgrading from 1.4.2 to 1.5.0.
I am using the official helm chart.

**Comment by derekbit** [comment]
@EugenMayer @janpfischer 
This is a known issue. Please refer to the workaround in https://github.com/longhorn/longhorn/issues/6252.

**Comment by derekbit** [comment]
@EugenMayer 
Because you did a rollback that we don't support, the situation is more complicated. Can you provide us more information and symptoms?

**Comment by janpfischer** [comment]
While trying to fix this I also destroyed my whole longhorn installation. No volumes were able to be bound and unbound. I suspect this was my error by deleting "old" Instancemanager CRD from that longhorn could not recover at all. 

I had to recreate the whole helmrelease and restore all my volumes from backups. Now I am running on 1.5.0 as a complete fresh install and volumes are working again. 

However helmrelease can not finish with following error: 
`Helm install failed: deployments.apps "longhorn-recovery-backend" not found`

I've applied the workaround as follows: 
```
longhornConversionWebhook:
      replicas: 0
longhornAdmissionWebhook:
      replicas: 0
longhornRecoveryBackend:
      replicas: 0
```
with that I could get rid of the crashing pods before the cluster was completly stuck and I recreated it. 
This values are now present in my new fresh 1.5.0 installation, too.

**Comment by derekbit** [comment]
@janpfischer I don't think the crashloop webhooks or known issues can destroy whole cluster... I would suggest providing us more information before tearing down it.

**Comment by EugenMayer** [comment]
@derekbit arg. Well i of course have read about the limitation with the downgrade before upgrading. The reason why i tried is because i seemed the upgrade did not go through .. i guess i was wrong.

i got the bundle 13MB - how do hand it over and are there sensible information there? Let me know and thank you for helping

**Comment by derekbit** [comment]
Please send to [longhorn-support-bundle@suse.com](mailto:longhorn-support-bundle@suse.com). Thanks.

**Comment by derekbit** [comment]
@EugenMayer 
I've pinged you on Rancher Users slack channel. Let's have conversions there and speed up the process. Thank you.

**Comment by EugenMayer** [comment]
Thanks to the huge help of @derekbit i was able to fix it. There are 3 possible routes to go - i picked 3. and think 2. is also a good pick, i would avoid 1. due to it's unclean deployment state. (it works)

## 1 temporary delete the deployments
You manually delete the deployments
- longhorn-conversion-webhook
- longhorn-admission-webhook
- longhorn-recovery-backend

With this method, you cannot redeploy the helm chart without getting stuck again (and need to re-remove it). You will have to wait for 1.5.1 to get it any better

## 2 Remove deployments via the helm chart

add this to your helm chart values

```
longhornAdmissionWebhook:
  replicas: 0
longhornConversionWebhook:
  replicas: 0
longhornRecoveryBackend:
  replicas: 0
``` 
and redeploy the chart.

This will help you to be able to properly apply the helm chart again - but be sure to remove those when 1.5.1 has been release

# 3. Use the fixed "alpha" version for additional fixes

This basically combined 2 and adds further fixes

- You first remove the deployments manually using what is described in 1.

Then add this to your values.yaml

```
longhornAdmissionWebhook:
  replicas: 0
longhornConversionWebhook:
  replicas: 0
longhornRecoveryBackend:
  replicas: 0
image:
  longhorn:
    manager:
      repository: derekbit/longhorn-manager
      tag: v1.5.0-fix-socket
```

re-apply you helm chart
