### ISSUE TITLE
[IMPROVEMENT] Excessive IO Wait leads to high CPU load on the physical machine, affecting other process services

### ISSUE THREAD

**Issue by shaolila** [longhorn/longhorn#6314]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)
![longhorn-iotop3](https://github.com/longhorn/longhorn/assets/8872412/815519d8-840c-4a86-a7e3-479ee8997432)

![longhorn-iotop2](https://github.com/longhorn/longhorn/assets/8872412/63d0dbc2-5824-4cf8-8ebf-7237899da559)

![longhorn-iotop1](https://github.com/longhorn/longhorn/assets/8872412/91ef5eaa-57ab-4971-b240-122689bb414f)

![longhorn-top-cpuwait](https://github.com/longhorn/longhorn/assets/8872412/c6a01084-efa8-40db-97e2-5f47153ea056)

Excessive IO Wait leads to high CPU load on the physical machine, affecting other process services

**Comment by bmalynovytch** [comment]
Observing the same really high load (node with 40 vCPUs showing 1000+ load average), keeping growing.
The loadavg was stable for months, then it started raising constantly.
Rebooting the node makes it happy again and cluster stable again ... for a while.
The load increases randomly on nodes of the cluster, while they should have enough resources to work properly.

**Comment by bmalynovytch** [comment]
This issue shouldn't be closed.

**Comment by derekbit** [comment]
@bmalynovytch 
Please provide more information https://github.com/longhorn/longhorn/issues/6314#issuecomment-1633693795 and support bundle for further analysis. Thanks.

**Comment by bmalynovytch** [comment]
I'll try to provide you with more informations soon, but if I did a bet, it'd be on RWX volumes and NFS stale mounts.
Could be related to https://access.redhat.com/solutions/2142081

**Comment by bmalynovytch** [comment]
Still needs investigation.
Can't provide support bundle for now as none of our clusters is currently having the issue.
If it's due to NFS, it's often triggered by nodes failure or maintenances, removing NFS pods while clients still trying to connect.

**Comment by bmalynovytch** [comment]
This issue should remain open.

**Comment by dimovstanimir** [comment]
Same issue with me and I totally removed longhorn. One of my nodes was being forced to its limits every 10 to 15 mins. The load avarage jumped to around 40. The I/Os was crazy. My fans were spinnig so load that every time I've heard it I've got so mad and in the end I removed the longhorn completelly. And yes, this issue sgoud stay opened until the devoleprs see it and fix this damn issue.

**Comment by derekbit** [comment]
> Same issue with me and I totally removed longhorn. One of my nodes was being forced to its limits every 10 to 15 mins. The load avarage jumped to around 40. The I/Os was crazy. My fans were spinnig so load that every time I've heard it I've got so mad and in the end I removed the longhorn completelly. And yes, this issue shoud stay opened until the devoleprs see it and fix this damn issue.

@dimovstanimir 
Can you provide more information and your workloads?
