### ISSUE TITLE
[TASK]  Update or remove out-of-date cleanup script

### ISSUE THREAD

**Issue by james-munson** [longhorn/longhorn#6316]
## What's the task? Please describe
longhorn/scripts/cleanup.sh is out of date with respect to the resources that make up a Longhorn installation.

A clear and concise description of what the task is.
Either
  - Bring it up to date, including changes to the resource list and also ability to deal with pending finalizers
 Or
 - Remove it from the repo.

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

Add any other context or screenshots about the task request here.

**Comment by innobead** [comment]
@james-munson Please help update zenhub pipeline correctly. If having any questions, consult with @PhanLe1010 or @ejweber .

**Comment by james-munson** [comment]
How does this ticket get tested and closed?

**Comment by PhanLe1010** [comment]
cc @khushboo-rancher 

In this case, there is no testing needed. Maybe QA just directly close it?

**Comment by khushboo-rancher** [comment]
Thanks @james-munson @PhanLe1010
