### ISSUE TITLE
[BUG] Helm2 install error: 'lookup' function not defined in validate-psp-install.yaml

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#6318]
## Describe the bug (🐛 if you encounter this issue)

When attempting to install Longhorn using `Helm2`, the following error is encountered:

```bash
Error: parse error in "longhorn/templates/validate-psp-install.yaml": template: longhorn/templates/validate-psp-install.yaml:1: function "lookup" not defined
```
![Screenshot_20230713_231957](https://github.com/longhorn/longhorn/assets/104337648/a98682d1-a96c-45f7-995c-bf12ccad9ea2)

## To Reproduce

```
git clone -b v1.4.3-rc2 https://github.com/longhorn/longhorn.git
cd longhorn
```

1. Run the command `helm install --namespace longhorn-system --name longhorn ./chart` with Helm2.
2. Observe the error mentioned above.

## Expected behavior

The installation of Longhorn using Helm2 should not encounter any errors and should proceed successfully.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm 2
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster: 1 
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Possible Solution

One possible solution is to drop the support for Helm2 or remove the lookup function that is causing the error. This should be discussed further to determine the best course of action.

**Comment by innobead** [comment]
We probably need to remove helm 2 support.

**Comment by ejweber** [comment]
Discussed elsewhere as well, but for complete information in this issue:

I agree that we should remove Helm 2 support. If we do, we should declare support for Helm v3.1+ (excluding Helm v3.0, since it doesn't have the lookup function either).

- https://github.com/helm/helm/issues/9167
- https://github.com/helm/helm/commit/d564d4bf2d6c6a9781439db231c4aaa1d7a916f8

**Comment by PhanLe1010** [comment]
+1 for dropping Helm2 support.

**Comment by innobead** [comment]
@roger-ryao Please check if helm v2 support info has been removed from the release note of the installed chart and doc. If yes, close the issue.

**Comment by roger-ryao** [comment]
**Verified on master-head 20231225**

- longhorn master-head https://github.com/longhorn/longhorn/commit/fe9dc3c5530f58b80085686718e351a8e4634229
- website master-head https://github.com/longhorn/website/commit/d52be78467ecd57078df111ae33f30d392f5b261

**Result Passed**

1. require/doc : https://github.com/longhorn/longhorn/pull/7434 & https://github.com/longhorn/website/pull/822

Hi @innobead 
After reviewing the pull request, everything looks good. This issue has been highlighted since `v1.4.3`. I suggest backporting it to https://github.com/longhorn/longhorn/pull/7434 and https://github.com/longhorn/website/pull/822 for `v1.5.x` and `1.4.x`. This way, users won't mistakenly think that `v1.5.x` and `1.4.x` still support `Helm 2`. 
Do you think fixing the documentation from `v1.6.0` onward is sufficient?

**Comment by innobead** [comment]
Sounds good to me. This issue was introduced into 1.5.0 and 1.4.1, https://github.com/longhorn/longhorn/issues/5339, so let's update that doc as well. 

For the chart, let's update to 1.6.0, 1.5.x (1.5.4), and 1.4.x (1.4.5).

**Comment by roger-ryao** [comment]
For v1.6.0, we have two pull requests:

- [x] 1.  https://github.com/longhorn/longhorn/pull/7437
- [x] 2.  https://github.com/longhorn/website/pull/824

All related pull requests have been merged; close the ticket
