### ISSUE TITLE
[TEST] Test case test_support_bundle_purge failed due to json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#6320]
## What's the test to develop? Please describe

In master head and v1.5.x daily regression, test case `test_support_bundle_purge` has failed continuously for the past two builds.

Daily regression [result](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/551/testReport/junit/tests/test_support_bundle/test_support_bundle_purge/)

Test case failed at `create_failed_support_bundles(client, apps_api, number=1)` with below exception
```
        except StopIteration as err:
>           raise JSONDecodeError("Expecting value", s, err.value) from None
E           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] `item 1`

## Additional context

N/A

**Comment by yangchiu** [comment]
The `requests.get(support_bundle_url)` function can get correct response at first:
```
resp code = 200
resp = b'{"actions":{},"errorMessage":": ","id":"ip-10-0-1-14","links":{"self":"http://10.42.1.8:9500/v1/supportbundles/ip-10-0-1-14"},"name":"support-bundle-2023-07-14t02-52-22z","nodeID":"ip-10-0-1-14","progressPercentage":20,"state":"Generating","type":"supportBundle"}\n'
```
But eventually it got 404 error with empty response content:
```
resp code = 404
resp = b''
```
Not sure it's related to https://github.com/longhorn/longhorn-manager/commit/a5232884268215d2669cfd9bd0e51bfaa4bf69c2

**Comment by c3y1huang** [comment]
Unlikely related. It's caused by the intermediate state where getting the support bundle returns 404, meaning trying to decode using an empty response will fail.

**Comment by chriscchien** [comment]
Test case `test_support_bundle_purge` passed on master([AMD64](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/638/testReport/tests/test_support_bundle/), [ARM64](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/589/testReport/tests/test_support_bundle/)), v1.5.x([AMD64](https://ci.longhorn.io/job/public/job/v1.5.x/job/v1.5.x-longhorn-tests-sles-amd64/104/testReport/tests/test_support_bundle/), [ARM64](https://ci.longhorn.io/job/public/job/v1.5.x/job/v1.5.x-longhorn-tests-sles-arm64/100/testReport/tests/test_support_bundle/)) pipeline
