### ISSUE TITLE
[BUG] Webhook is never called for BackingImageManager

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#6328]
## Describe the bug (🐛 if you encounter this issue)

The webhook is never called for BackingImageManager CREATE or UPDATE events. This means a finalizer is never set and spec.backingImages is not set to {} (from nil).

## To Reproduce

1. Install Longhorn.
2. Create a backing image using the UI (I used https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.qcow2 as the URL).
3. Use `kubectl get -o yaml -n longhorn-system lhbim` to see that there is no finalizer set.
4. Use `kl logs -l app=longhorn-manager --tail=-1 | grep -e CREATE -e UPDATE | grep Kind=BackingImageManager` to observe that the webhook was never called.

## Expected behavior

The webhook should be called for a BackingImageManager and a finalizer should be set.
`kl logs -l app=longhorn-manager --tail=-1 | grep -e CREATE -e UPDATE | grep Kind=BackingImageManager` should show something like:

```
time="2023-07-14T17:55:00Z" level=info msg="Request (user: system:serviceaccount:longhorn-system:longhorn-service-account, longhorn.io/v1beta2, Kind=BackingImageManager, namespace: longhorn-system, name: backing-image-manager-b2c6-46d2, operation: CREATE) patchOps: [{\"op\": \"replace\", \"path\": \"/metadata/finalizers\", \"value\": [\"longhorn.io\"]}]" service=admissionWebhook
```

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: master, v1.5.x, v1.4.x, v1.3.x

## Additional context

The problem is [this line of code](https://github.com/longhorn/longhorn-manager/blob/a5b67e5ec57ec38be0d50cdbe77428d924f1b2fb/webhook/resources/backingimagemanager/mutator.go#L26). `backingImageManagers` must be lowercased like `backingimagemanagers` as is the case for the other resources.

**Comment by ejweber** [comment]
Discovered while working on https://github.com/longhorn/longhorn-manager/pull/2080 and fixed with https://github.com/longhorn/longhorn-manager/pull/2080/commits/3089b1cd9a6b3afaeb0668ef29102a7a96705962. We just need to cherry-pick that one back into previous releases.

**Comment by derekbit** [comment]
Did we encounter any issue caused by the lowercase issue? Or, not because the finalizer is still added in datastore?

**Comment by ejweber** [comment]
> Did we encounter any issue caused by this bug? Or, NOT because the finalizer was still added in datastore?

I am not aware of any issue. The webhook also does the following, but I am not sure it is necessary.

```go
if backingImageManager.Spec.BackingImages == nil {
	patchOps = append(patchOps, `{"op": "replace", "path": "/spec/backingImages", "value": {}}`)
}
```

**Comment by ejweber** [comment]
> Did we encounter any issue caused by this bug? Or, NOT because the finalizer was still added in datastore?

Looked into this again out of curiosity. I still don't know of any particular issue we have run into, but for clarity, it is quite common for the BackingImageManager to NOT have a finalizer. The datastore adds the finalizer when the BackingImageManager is updated, but NOT when BackingImageManagerStatus is updated. Most of the time, only status is updated. In my basic testing, I found that my BackingImageManager typically does not have a finalizer. 

Luckily, the backing image controller calls UpdateBackingImageManager before DeleteBackingImageManager, so the finalizer is usually set right before deletion.

https://github.com/longhorn/longhorn-manager/blob/8ce69c8f280a5a2715c528034e0274391ad761c0/controller/backing_image_controller.go#L339-L351

However, if BackingImageManager is ever deleted directly (e.g., by a user), there is a good chance cleanupBackingImageManager does not run and files are left on the node.

https://github.com/longhorn/longhorn-manager/blob/8ce69c8f280a5a2715c528034e0274391ad761c0/controller/backing_image_manager_controller.go#L329-L355

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `c4924b`) with test [steps](https://github.com/longhorn/longhorn/issues/6328#issue-1805308876)

- Can reproduce in v1.5.1
- In master-head, backing images have finalizer set. And can find below log in longhorn-manager
```
time="2023-08-04T06:21:49Z" level=info msg="Request (user: system:serviceaccount:longhorn-system:longhorn-service-account, longhorn.io/v1beta2, Kind=BackingImageManager, namespace: longhorn-system, name: backing-image-manager-b2c6-5570, operation: CREATE) patchOps: [{\"op\": \"replace\", \"path\": \"/metadata/finalizers\", \"value\": [\"longhorn.io\"]}]" service=admissionWebhook
```
- No backing images failed test case found in daily [regression](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/574/testReport/tests/test_backing_image/)
