### ISSUE TITLE
[BUG] Unable to list backup from a local backupstore in RKE2 CIS-1.23 environment

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6342]
## Describe the bug (🐛 if you encounter this issue)

In RKE2 v1.27.2+rke2r1 + CIS-1.23 hardened environment, setup test backupstore in local cluster like:
```
kubectl create -f "https://raw.githubusercontent.com/longhorn/longhorn-tests/master/manager/integration/deploy/backupstores/minio-backupstore.yaml"
kubectl create -f "https://raw.githubusercontent.com/longhorn/longhorn-tests/master/manager/integration/deploy/backupstores/nfs-backupstore.yaml"
```
And set backup target to use these test backupstores like:
```
Backup Target = s3://backupbucket@us-east-1/backupstore
Backup Target Credential Secret = minio-secret
or
Backup Target = nfs://longhorn-test-nfs-svc.default:/opt/backupstore
```
The backup target will remain unavailable:
```
$ kubectl get backuptargets.longhorn.io -n longhorn-system
NAME      URL                                                    CREDENTIAL   LASTBACKUPAT   AVAILABLE   LASTSYNCEDAT
default   nfs://longhorn-test-nfs-svc.default:/opt/backupstore                5m0s           false       <no value>
```
And there's error in longhorn-manager:
```
time="2023-07-18T03:19:42Z" level=error msg="Failed to list backup volumes from backup target" controller=longhorn-backup-target cred= error="error listing backup volume names: timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master-head/longhorn [backup ls --volume-only nfs://longhorn-test-nfs-svc.default:/opt/backupstore], output , stderr, time=\"2023-07-18T03:18:42Z\" level=info msg=\"Attempting mount for nfs path longhorn-test-nfs-svc.default:/opt/backupstore with nfsvers 4.2\" pkg=nfs\ntime=\"2023-07-18T03:18:42Z\" level=info msg=\"Mounting NFS share nfs://longhorn-test-nfs-svc.default:/opt/backupstore on mount point /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore with options [nfsvers=4.2 actimeo=1 soft timeo=300 retry=2]\" pkg=nfs\n, error <nil>" interval=5m0s node=ip-10-0-2-236 url="nfs://longhorn-test-nfs-svc.default:/opt/backupstore"
```
But if a real s3 remote backup target is used, everything works well and doesn't have any problem:
```
Backup Target = s3://yang-test-17@us-east-1/
Backup Target Credential Secret = aws-cred-secret

$ kubectl get backuptargets.longhorn.io -n longhorn-system
NAME      URL                            CREDENTIAL        LASTBACKUPAT   AVAILABLE   LASTSYNCEDAT
default   s3://yang-test-17@us-east-1/   aws-cred-secret   5m0s           true        2023-07-18T03:22:50Z

time="2023-07-18T03:22:50Z" level=info msg="Found 10 backup volumes in the backup target that do not exist in the cluster and need to be pulled" controller=longhorn-backup-target cred=aws-cred-secret interval=5m0s node=ip-10-0-2-236 url="s3://yang-test-17@us-east-1/"
```

Not sure if there's any extra setup/configuration is needed to make things work.

## To Reproduce

1. Follow https://longhorn.github.io/longhorn-tests/manual/pre-release/environment/rke2-cis-1.23-profile/ to setup CIS-1.23 hardened environment
2. In step 4 of https://longhorn.github.io/longhorn-tests/manual/pre-release/environment/rke2-cis-1.23-profile/, label `default` namespace too, otherwise backupstore pods will violate pod security and no pod will be created  
3. Create backupstore
```
kubectl create -f "https://raw.githubusercontent.com/longhorn/longhorn-tests/master/manager/integration/deploy/backupstores/minio-backupstore.yaml"
kubectl create -f "https://raw.githubusercontent.com/longhorn/longhorn-tests/master/manager/integration/deploy/backupstores/nfs-backupstore.yaml"
```
4. Install Longhorn 
6. Use the backupstore created in step 3 as the backup target and try to list/create backup 

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.27.2+rke2r1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: sles-15-sp4
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by yangchiu** [comment]
Related to https://github.com/longhorn/longhorn/issues/6092

**Comment by mantissahz** [comment]
@yangchiu Do you check the DNS is working well? Could you test to access `longhorn-test-nfs-svc.default` and `minio-service.default:9000` in the `longhorn-manager` pod and show the information about services and endpoints of the backup stores?

**Comment by yangchiu** [comment]
Yes, tested in cis hardened environment, `longhorn-manager` is unable to access `minio-service.default:9000`, but if I redeploy the minio service into `longhorn-system`, it works again. So it seems the default behavior of cis hardened environment that forbid the cross namespace communication, and Longhorn itself works without problems.

**Comment by innobead** [comment]
> Yes, tested in cis hardened environment, `longhorn-manager` is unable to access `minio-service.default:9000`, but if I redeploy the minio service into `longhorn-system`, it works again. So it seems the default behavior of cis hardened environment that forbid the cross namespace communication, and Longhorn itself works without problems.

Do we have any references for this?

**Comment by yangchiu** [comment]
No, I don't know which configuration causes this and didn't find out specific documents on this. It's just from observation.

**Comment by innobead** [comment]
Your observation is correct, as per https://docs.rke2.io/security/pod_security_standards#network-policies, there are denying ingress from other namespaces by default for the builtin namespaces including default.

**Comment by ejweber** [comment]
I am not sure how common it is to run the backup store inside Kubernetes in production. My guess is that backups are usually being done to an external system (e.g. AWS S3 or a dedicated filer). Maybe we have data on that?

To me it seems we should:

1. Rework the manual CIS-1.23 test to either specify that backupstores should be deployed into the longhorn-system namespace or add a network policy to the manual CIS-1.23 test that gets it working.
2. Provide documentation and an example network policy for customers intending to use CIS-1.23 in case they are running their backupstore in an alternate namespace.
