### ISSUE TITLE
[TASK] Add install/upgrade longhorn by gitops (flux) pipeline

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6343]
## What's the task? Please describe

Add install/upgrade longhorn by gitops (flux) pipeline

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

Add any other context or screenshots about the task request here.

**Comment by innobead** [comment]
Primarily focus on install and upgrade/update.

**Comment by derekbit** [comment]
Add a `doc` label for improving the official doc.
cc @yangchiu @innobead

**Comment by innobead** [comment]
Also added to 1.6 milestone, because we also want to update the doc.

**Comment by innobead** [comment]
@yangchiu if done, just close this issue.
