### ISSUE TITLE
[IMPROVEMENT] Helm chart readme outdated

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6352]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The readme of the chart is outdated, should update it and avoid duplicated efforts to add the same content already exist in the doc, so it's better to use longhorn doc referenced in the readme instead. 

Also, need to remove helm 2 tutorial from the note when working on #6318 . 

## Describe the solution you'd like

Update charts of the actively supported releases. Right now, it's master/1.6, 1.5, 1.4 and 1.3. 1.3 will be EOD in September.

**Comment by innobead** [comment]
@ChanYiLin is working on this. Let @ChanYiLin wrap it up together.

**Comment by derekbit** [comment]
@ChanYiLin Please resolve the ticket if it is invalid.

**Comment by ChanYiLin** [comment]
https://github.com/longhorn/longhorn/blob/master/chart/templates/NOTES.txt

the note looks good now, won't fix
