### ISSUE TITLE
[BUG] Failure to update backup status leads to infinite reconciliation

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#6358]
## Describe the bug (🐛 if you encounter this issue)

This issue was first discovered by a user experiencing high CPU load. They traced the issue to a large number of failed backups that were not proceeding. The backups had been kicked off by a daily recurring job. Longhorn-manager was logging approximately ~60 sets of messages like the following every second:

```
time="2023-07-10T09:55:20Z" level=warning msg="syncBackupStatusWithSnapshotCreationTimeAndVolumeSize: couldn't find the snapshot <snapshot_name> in volume <volume_name> " controller=longhorn-backup node=<node_name>
time="2023-07-10T09:55:20Z" level=warning msg="Cannot take snapshot backup" backup=<backup_name> controller=longhorn-backup error="could not find snapshot '<snapshot_name>' to backup, engine '<engine_name>'" node=<node_name>
time="2023-07-10T09:55:20Z" level=warning msg="Error syncing Longhorn backup longhorn-system/<backup_name>" controller=longhorn-backup error="longhorn-backup: failed to sync backup longhorn-system/<backup_name>: could not find snapshot '<snapshot_name>' to backup, engine '<engine-name>'" node=<node_name>

```

Unfortunately, the root cause is unknown (i.e. why was the snapshot deleted before the backup was started?). However, we should not be continually reconciling this backup and others.

## To Reproduce

https://github.com/longhorn/longhorn/issues/6358#issuecomment-1646229750

## Expected behavior

If the backup cannot be started because the snapshot no longer exists, we should quickly reach a stable state in which we no longer try to create a backup instead of infinitely rereconciling.

## Support bundle for troubleshooting

A single log file from a longhorn-manager experiencing this behavior is available internally. If you have seen experienced this issue and have a support bundle you don't mind sharing, please add it to this ticket.

## Environment
> Suggest checking the doc of the best practices of using Longhorn. [here](https://longhorn.io/docs/1.5.1/best-practices)

 - Longhorn version: v1.4.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): ?
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.23.17
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 5
 - Node config
   - OS type and version: ?
   - CPU per node: ?
   - Memory per node: ?
   - Disk type(e.g. SSD/NVMe/HDD): ?
   - Network bandwidth between the nodes: ?
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): ?
 - Number of Longhorn volumes in the cluster: 17

## Additional context

As far as I can tell, this is the problem:

A backup CR exits with `status.lastSyncedAt = nil` and `spec.snapshotName ~= nil`. This causes the backup controller to attempt to kick off a backup.

https://github.com/longhorn/longhorn-manager/blob/423513ad5838695c0b481a1c5309a0ecb73abbe9/controller/backup_controller.go#L361

The backup controller is not monitoring the backup, so it creates a new backup monitor and calls into the engine to backup the referenced snapshot. This operation fails (because the snapshot does not exist in the engine), so `NewBackupMonitor` returns an error.

https://github.com/longhorn/longhorn-manager/blob/423513ad5838695c0b481a1c5309a0ecb73abbe9/engineapi/backup_monitor.go#L88-L97

The error bubbles up through `enableBackupMonitor` to `checkMonitor`. `checkMonitor` tries to set `backup.Status.Error`, `backup.Status.State`, and `backup.Status.LastSyncedAt` before returning to reconcile. If it did so successfully, we would not attempt to back this snapshot up again.

https://github.com/longhorn/longhorn-manager/blob/423513ad5838695c0b481a1c5309a0ecb73abbe9/controller/backup_controller.go#L547-L554

reconcile returns immediately. There is a defer function responsible for reconciling the new backup status with the backup CR stored in the API server, but it returns without doing so if any error occurred. Now the backup controller has no way of knowing it has tried this operation before and continuously repeats it.

https://github.com/longhorn/longhorn-manager/blob/423513ad5838695c0b481a1c5309a0ecb73abbe9/controller/backup_controller.go#L340-L352

~Other similar defer functions update the status in the Kubernetes API server regardless of error, so this behavior should probably be changed in the backup controller.~

**Comment by ejweber** [comment]
Discussed with @PhanLe1010 and @james-munson. Other similar defer functions actually do NOT update the status in the Kubernetes API server (my mistake). We can use the snapshot controller as an example for how to handle special cases in which we DO need to update the status, regardless of error.

https://github.com/longhorn/longhorn-manager/blob/798bb8ecda35b7536c6f2dade30f58ac4e92808e/controller/snapshot_controller.go#L298-L311

**Comment by ejweber** [comment]
It was fairly easy to recreate the behavior by following these steps.

1. Install an affected Longhorn version.
2. Create a Longhorn volume called `test-volume`.
3. Create a Longhorn backup CR like the following. Note that test-snapshot does NOT exist.

```yaml
apiVersion: longhorn.io/v1beta2
kind: Backup
metadata:
  labels:
    backup-volume: test-volume
  name: test-backup-0
spec:
  snapshotName: test-snapshot
```

4. Watch Longhorn manager logs for repeats of the ones I opened the issue with.
5. Note that, from the backup CR's point of view, there is no error or evidence of progress of any kind.

```
Name:         test-backup-0
Namespace:    longhorn-system
Labels:       backup-volume=test-volume
Annotations:  <none>
API Version:  longhorn.io/v1beta2
Kind:         Backup
Metadata:
  Creation Timestamp:  2023-07-20T20:43:07Z
  Finalizers:
    longhorn.io
  Generation:        1
  Resource Version:  14198727
  UID:               01ef669f-7276-4d9d-b689-fad84d85dd93
Spec:
  Labels:
    longhorn.io/volume-access-mode:  rwo
  Snapshot Name:                     test-snapshot
Status:
  Backup Created At:          
  Labels:                     <nil>
  Last Synced At:             <nil>
  Messages:                   <nil>
  Owner ID:                   eweber-v125-worker-e472db53-9kz5b
  Progress:                   0
  Replica Address:            
  Size:                       
  Snapshot Created At:        
  Snapshot Name:              
  State:                      
  URL:                        
  Volume Backing Image Name:  
  Volume Created:             
  Volume Name:                
  Volume Size:                
Events:                       <none>
```

It looks like the original reporter had 168 failed backups in this state on their cluster (judging by unique backup names in the logs showing this churn). I created that many backups on my cluster to attempt to find a CPU usage issue. `instance-manager-e`  CPU utilization for the volume targeted by the backup did jump from ~5% to ~25% when I created the bad backups. `longhorn-manager` utilization also rose, but only from ~1% to ~3%. On a small machine, these increases could be significant, but they seem unlikely to have caused significant issues for competing workloads.

![image](https://github.com/longhorn/longhorn/assets/24213029/7ab9053b-0579-4812-9aa6-ff9e61f5b0ed)


I also experimented with smaller numbers of bad backups and the CPU utilization decreased relatively proportionally.

**Comment by PhanLe1010** [comment]
Can we check the RAM also?

**Comment by ejweber** [comment]
> Can we check the RAM also?

I glanced at it, but it didn't seem interesting. I'll run the test again here in a bit.

**Comment by PhanLe1010** [comment]
> I created that many backups on my cluster to attempt to find a CPU usage issue.

How many bad backups is it?

**Comment by PhanLe1010** [comment]
Would it be interesting to take a look at profiling data to determine which part of the controller is eating CPU? https://longhorn.io/kb/troubleshooting-generate-pprof-runtime-profiling-data/

**Comment by ejweber** [comment]
> How many bad backups is it?

168

> Would it be interesting to take a look at profiling data to determine which part of the controller is eating CPU? https://longhorn.io/kb/troubleshooting-generate-pprof-runtime-profiling-data/

This will definitely be useful to me going forward. Thanks for the call out. However, it looks like most of the CPU is eaten up by instance-manager, which we don't appear to have enabled pprof for.

**Comment by PhanLe1010** [comment]
It is interesting that the instance manager is eating CPU. Can it be the increase in gRPC calls and TCP connection because of these snapshotBackup calls? Should we double-check the socket counts?

**Comment by innobead** [comment]
> This will definitely be useful to me going forward. Thanks for the call out. However, it looks like most of the CPU is eaten up by instance-manager, which we don't appear to have enabled pprof for.

We need to have an improvement for this. 

cc @shuo-wu @derekbit

**Comment by ejweber** [comment]
@mantissahz's fix has been backported to previous versions of Longhorn already as well.

**Comment by chriscchien** [comment]
Verified **pass** in longhorn master (longhorn-manager `840dbf`)

With test steps [here](https://github.com/longhorn/longhorn/issues/6358#issuecomment-1646229750) , can not find logs related to `syncBackupStatusWithSnapshotCreationTimeAndVolumeSize` in longhorn-manager pod. After 30 minutes passed since the backup creation, no significant surge in node CPU usage was observed.

**Comment by ejweber** [comment]
The original reporter discovered that an unrelated workload was causing high CPU load in their cluster, and Longhorn was likely not responsible. This fits with my findings from https://github.com/longhorn/longhorn/issues/6358#issuecomment-1646229750, which showed that the issue causes an increase in CPU utilization, but not a huge one. I will not investigate the CPU usage component of this issue any longer.
