### ISSUE TITLE
[FEATURE] SPDK volume supports live migration

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6361]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

SPDK volume supports live migration as v1 volume

## Describe the solution you'd like

A clear and concise description of what you want to happen

**Comment by shuo-wu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Sprint-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/6361?planning-poker) with Zenhub @DamiaSan @derekbit @innobead

**Comment by DamiaSan** [comment]
For, volume live migration can we use the same procedure of [online volume rebuilding](https://github.com/longhorn/longhorn-spdk-engine/wiki/How-to-create-a-copy-of-a-volume-on-a-different-node-with-SPDK) right?

**Comment by PhanLe1010** [comment]
e2e test case ticket is https://github.com/longhorn/longhorn/issues/9905

TODO: We should design a test skeleton for https://github.com/longhorn/longhorn/issues/9905 as part of this ticket

**Comment by PhanLe1010** [comment]
## Test plan:

Case 1: Migration confirmation 

Case 2: Migration rollback

Case 3:Engine crash during migration 
1. Original engine crash
1. Migrating engine crash

Case 4: Replica crash during live migration:
1. Some replica crash
1. All replica crash: failed

Case 5: Run all e2e migration test cases with v2 volume
