### ISSUE TITLE
[IMPROVEMENT] Upgrade Longhorn upgrade-responder server and build new Grafana dashboard

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#6368]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Now that Longhorn manager v1.5.x is sending additional metrics, ref https://github.com/longhorn/longhorn/issues/5235, we can upgrade the Longhorn upgrade-responder server and build new Grafana dashboard to store and display the new data

Items:
- [x] Upgrade the Longhorn upgrade responder server 
    * https://github.com/longhorn/upgrade-responder/pull/49
    * https://github.com/longhorn/longhorn/pull/6384
- [ ] Build new Grafana dashboard 
    - [x] Design a new dashboard.
    - [ ] Migrate the Gafana chart in Longhorn infrastructure. The current Grafana (7.1.1) doesn't have `histogram` graph. Therefore we have to upgrade Grafana to 10.0.2. However, the current Grafana chart is from the old chart repo `https://charts.helm.sh/stable`. This repo is deprecated and there is no new Grafana version for us to update. As a result, we will have to deploy a new chart from `https://grafana.github.io/helm-charts` and migrate the data/authentication/etc,.. from the old chart to the new chart.

**Comment by PhanLe1010** [comment]
Demo Grafana dashboard http://143.198.135.54:31505/public-dashboards/2952b3e2ef3a4ebbb117f8b0d079fc73?orgId=1

**Comment by c3y1huang** [comment]
Summary per discussion with @PhanLe1010 :
1. Check if the average of cluster scope numbers shows differently when using the [NamespaceUID](https://github.com/longhorn/longhorn-manager/blob/v1.5.1/controller/setting_controller.go#L1167C2-L1167C25).
1. Clarify the meaning of `B` in the Average Volume Spec panel.
1. Ensure consistency in the display of percentages.
1. See if possible to have another panel showing the number of clusters (NamespaceUID) over the period.

**Comment by PhanLe1010** [comment]
> Check if the average of cluster scope numbers shows differently when using the [NamespaceUID](https://github.com/longhorn/longhorn-manager/blob/v1.5.1/controller/setting_controller.go#L1167C2-L1167C25).

I double-check by filter out empty NamespaceUID data point. The number is the same


> Clarify the meaning of `B` in the Average Volume Spec panel.

This is a typo. Fixed. Thank you

> Ensure consistency in the display of percentages.

Fixed. Thank you

> See if possible to have another panel showing the number of clusters (NamespaceUID) over the period.

I think we shouldn't do this because:
1. We have the graph number of nodes over time, and we have the average node count per cluster already. Using these data one can have a good view of how many clusters over time. So it is a bit redundant.
2. We cannot draw it immediately at the moment. If we want to draw this graph, we will have to create a new continuous query to reduce the number of data points.

**Comment by c3y1huang** [comment]
> > See if possible to have another panel showing the number of clusters (NamespaceUID) over the period.
> 
> I think we shouldn't do this because:
> 
> 1. We have the graph number of nodes over time, and we have the average node count per cluster already. Using these data one can have a good view of how many clusters over time. So it is a bit redundant.
> 2. We cannot draw it immediately at the moment. If we want to draw this graph, we will have to create a new continuous query to reduce the number of data points.

Need some feedback from @innobead about the cluster panel. Others LGTM.

**Comment by PhanLe1010** [comment]
For the Grafana dashboard, there are 2 working items:
1. Design a new dashboard. This is being reviewed by @c3y1huang and @innobead 
2. Migrate the Gafana chart in Longhorn infrastructure. 
The current Grafana (7.1.1) doesn't have `histogram` graph. Therefore we have to upgrade Grafana to 10.0.2.
However, the current Grafana chart is from the old chart repo `https://charts.helm.sh/stable`. This repo is deprecated and there is no new Grafana version for us to update. As a result, we will have to deploy a new chart from `https://grafana.github.io/helm-charts` and migrate the data/authentication/etc,.. from the old chart to the new chart. I have done the migration. Waiting for the approval from @innobead to switch over to the new running Grafana

**Comment by innobead** [comment]
@PhanLe1010 I assume this has been done. Closing first. Feel free to reopen. Also, it seems some future work needs to do like upgrading grafana, create another issue to track instead.
