### ISSUE TITLE
[FEATURE] RWX Share Manager support Locality

### ISSUE THREAD

**Issue by ysicing** [longhorn/longhorn#6370]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

multiple clouds, schedule the share-manager service to the node where the replicas reside as much as possible if the Data Locality function can be provided. it offers higher IOPS and lower latency performance.

多云或者跨云的环境下，如果能将share-manager-pvc调度到副本或者工作负载节点所在节点, 类似[Data Locality](https://longhorn.io/docs/1.5.1/high-availability/data-locality/), 可以提供更高的 IOPS 和更低的延迟性能

## Describe the solution you'd like

A clear and concise description of what you want to happen

## Additional context

cc @longhorn/dev

**Comment by lorenzo-w** [comment]
I'd be willing to make a PR for this feature, but I am new to the code base. Could one of the maintainers perhaps point me in the right direction for this? Or would it require a code change too large for a first issue?

**Comment by james-munson** [comment]
It seems this will be covered by #7872

**Comment by derekbit** [comment]
Addressed in https://github.com/longhorn/longhorn/issues/7872.
