### ISSUE TITLE
[TEST] 2 stage upgrade fail (from_transient)

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#6376]
## What's the test to develop? Please describe

In the 2 stage upgrade test, the upgrade from transient version failed due to system backup `test-system-backup` not being cleaned when upgrade from stable.
- AMD64 build [237](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-2-stage-upgrade-tests-sles-amd64/238/testReport/junit/tests/test_upgrade/), [238](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-2-stage-upgrade-tests-sles-amd64/238/testReport/junit/tests/test_upgrade/)
- ARM64 build [229](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-2-stage-upgrade-tests-sles-arm64/229/testReport/junit/tests/test_upgrade/test_upgrade_from_transient_/), [230](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-2-stage-upgrade-tests-sles-arm64/230/testReport/junit/tests/test_upgrade/test_upgrade_from_transient_/)

Failed at upgrade from transient
```
# system backup
        if system_backup_feature_supported(client):
            system_backup_name = "test-system-backup"
>           client.create_system_backup(Name=system_backup_name)
```
with error message
```
Error Message
longhorn.ApiError: (ApiError(...), '500 : failed to create SystemBackup: systembackups.longhorn.io "test-system-backup" already exists\n{\'code\': 500, \'detail\': \'\', \'message\': \'failed to create SystemBackup: systembackups.longhorn.io "test-system-backup" already exists\', \'status\': 500}')
```

## Additional context

N/A

**Comment by innobead** [comment]
@longhorn/qa feel free to self-assign if you are planning to work on it.

**Comment by yangchiu** [comment]
https://github.com/longhorn/longhorn-tests/pull/1474/files#diff-da673834a2c42a5795c3e88f9b8ec5c95ad275b7ba2bb2245406ffbe252a9a01R353

**Comment by chriscchien** [comment]
Test case `test_upgrade[from_transient]` in 2 stage upgrade test passed on [AMD64](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-2-stage-upgrade-tests-sles-amd64/330/testReport/tests/test_upgrade/) and [ARM64](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-2-stage-upgrade-tests-sles-arm64/324/testReport/tests/test_upgrade/) build now
