### ISSUE TITLE
[FEATURE] Enable resource profiling for IM

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6377]
> How many bad backups is it?

168

> Would it be interesting to take a look at profiling data to determine which part of the controller is eating CPU? https://longhorn.io/kb/troubleshooting-generate-pprof-runtime-profiling-data/

This will definitely be useful to me going forward. Thanks for the call out. However, it looks like most of the CPU is eaten up by instance-manager, which we don't appear to have enabled pprof for.

_Originally posted by @ejweber in https://github.com/longhorn/longhorn/issues/6358#issuecomment-1646253439_

**Comment by innobead** [comment]
Even though IM is system managed pod by Longhorn, but it still deserves profiling at runtime.

**Comment by innobead** [comment]
It seems @Vicente-Cheng is working on this.

**Comment by Vicente-Cheng** [comment]
Maybe we could make it related to https://github.com/longhorn/longhorn/issues/6282
These would be similar.

**Comment by innobead** [comment]
@derekbit is working on it.

**Comment by roger-ryao** [comment]
**Verified on master-head 20231229**

- longhorn master-head https://github.com/longhorn/longhorn/commit/07bdb419a968633059c24db35ec66d7d68d73f4c
- longhorn-instance-manager master-head https://github.com/longhorn/longhorn-instance-manager/commit/34c40f0a813cbcb83fc7c0f36089c29bb2deafc4


**The test steps**

1. Forward the port 6060 from the instance-manager pod to local port 6060:
    ```
    kubectl port-forward ${instance-manager-pod-name} -n longhorn-system 6060:6060
    ```
1. see the pprof debug web page: `http://localhost:6060/debug/pprof/`

**Result Passed**

1. pprof service works as expected.

![Screenshot_20231229_114532](https://github.com/longhorn/longhorn/assets/104337648/cbed64cb-c4d3-479c-b701-143fa318f860)
