### ISSUE TITLE
Volume restored with PersistentVolume information from Backup Label does not get updated

### ISSUE THREAD

**Issue by ttpcodes** [longhorn/longhorn#638]
The `Label: KubernetesStatus` is automatically applied to `Backups` to store the `KubernetesStatus` if it exists so that this data can be reused later once the `Backup` is restored. However, `PVName` on `KubernetesStatus` is supposed to only reflect the current status of a connected `PersistentVolume` and not hold historical data, unlike what `PVCName` and the other fields that have a `LastRefAt` attribute do.

When restoring a `Backup` that has the `PVName` and `PVStatus` fields set, the `longhorn-manager` will not only populate these fields on the new `Volume` even if the `PersistentVolume` doesn't actually exist, but also not update these fields to clear them despite the polling from the `KubernetesController`.

There are two fixes that need to be pursued here to fix these fields:
1. Fix the bug causing the `KubernetesController` to not clear the `PVName` or `PVStatus` of the `KubernetesStatus` on a restored `Volume`.
2. Either avoid storing these fields on the `Label: KubernetesStatus` of `Backups`, or avoid restoring these particular fields.

**Comment by yasker** [comment]
I think it's better to avoid restoring these fields. Maybe we don't want to store them at all, but no matter what the value was, we shouldn't restoring those.

**Comment by yasker** [comment]
Done.
