### ISSUE TITLE
[IMPROVEMENT] Automatically remount read-only RWO volume to read-write

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6386]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

In the current system, if a read-write volume was accidentally changed to a read-only state when there are IO errors, user must scale down the workload using the volume and then scale up to make the volume to a read-write state.

To address this issue, we have implemented RWX volume state monitoring and automatic remount functionality in https://github.com/longhorn/longhorn/issues/5961. We can introduce a similar logic for RWO volumes. This logic will periodically monitor the state of the volume, and if it gets stuck in a read-only state, the mechanism will automatically request a remount and restart the workload that uses the volume.

## Additional context

cc @james-munson @PhanLe1010 @shuo-wu  @innobead

**Comment by chriscchien** [comment]
Hi @ChanYiLin ,

Following [steps](https://github.com/longhorn/longhorn/issues/6386#issuecomment-1822340518), I can see the volume read only related infromation below , but the workload can not write data to volume, and did not observe remount after the read only happen.

According to the ticket title, the volume should remount and will be in read-write mode, could  your help to confirm if I misunderstand something? thank you.

(I set `auto-delete-pod-when-volume-detached-unexpectedly` to `false` when test with deployment. Tested on both `true` and `false` value when test with pod, the test result were all the same)

- deploymentr pod
```
root@test-deployment-754dd9fc66-lkn6d:/# echo 123123 >> /mnt/data/1
bash: /mnt/data/1: Read-only file system
```
- longhorn-manager log
```bash
time="2024-01-02T01:52:12Z" level=info msg="Volume request remount at 2024-01-02T01:52:12Z due to engine detected read-only filesystem" func="controller.(*VolumeController).requestRemountIfFileSystemReadOnly" file="volume_controller.go:1417" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=ip-172-31-40-139 owner=ip-172-31-40-139 state=attached volume=pvc-431e5599-d52d-4e82-b6b2-4f4d1d0c5617
```
- engine.longhorn.io
```bash
> k get engine.longhorn.io -A -o yaml  | grep FilesystemReadOnly -C 1
    status: "True"
    type: FilesystemReadOnly
  currentImage: longhornio/longhorn-engine:master-head
```
[supportbundle_cd6bef97-097e-4094-bac7-ce29913f2d8a_2024-01-02T02-24-32Z.zip](https://github.com/longhorn/longhorn/files/13806738/supportbundle_cd6bef97-097e-4094-bac7-ce29913f2d8a_2024-01-02T02-24-32Z.zip)

**Comment by ChanYiLin** [comment]
Note: By crashing the engine, longhorn will request remount already
so when testing we need to use another way to make volume into Read Only state.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `b63565`)

1. `Set auto-delete-pod-when-volume-detached-unexpectedly  = true`
2. Create pvc with worklad, wait volume healthy, writet data into mount point
3. Make the volume read only, in my case(k3s), I use below command
```
mount -o remount,ro /var/lib/kubelet/pods/92a1c306-8a6f-4147-a5db-44f4dee9db02/volumes/kubernetes.io~csi/${volume name}/mount
```
4. Write data into mount point, can see `bash: /mnt/data/file: Read-only file system` in pod
5. `engines.longhorn.io can` see status `FilesystemReadOnly=true`
6. Workload remout to volume, after volume healthy, data intact and can write data into mount point.

**Comment by derekbit** [comment]
@ChanYiLin 
Do you think if it is worth writing a doc `Recover Volume in Read-Only State` in the chapter https://longhorn.io/docs/1.6.0/high-availability/ for the mitigation?

**Comment by ChanYiLin** [comment]
Sure I can add a doc for it.
