### ISSUE TITLE
[TASK] Put Shallow copy over SPDK upstream

### ISSUE THREAD

**Issue by DamiaSan** [longhorn/longhorn#6388]
Our 3 commits have to be splitted in more commits, one for every single development for every single layer. Like upstream spdk request for the patch on Gerrit

**Comment by innobead** [comment]
cc @longhorn/dev-data-plane

**Comment by DamiaSan** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/19247

**Comment by innobead** [comment]
This is an upstream effort, which will not be tracked in our release milestone.

**Comment by DamiaSan** [comment]
https://github.com/spdk/spdk/commit/b269b0edc2ff25b93611df80c479e3f3eec70578

**Comment by DamiaSan** [comment]
The final implementation is a bit different from our version, now the shallow copy operation is asynchronous. It should be better for us too, right @shuo-wu ? I remember you asked me to do so ...
cc @derekbit

**Comment by innobead** [comment]
Do we use the async version in 1.7?
