### ISSUE TITLE
[DOC] Create a KB for incorrect replica expansion

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#6391]
I think we need a KB to explain the unexpected expansion and the workaround. WDYT? @ejweber @innobead

_Originally posted by @derekbit in https://github.com/longhorn/longhorn/issues/4181#issuecomment-1650062411_

We need a KB to explain the cause of, workarounds for, and development action being taken as a result of incorrect replica expansion.

**Comment by james-munson** [comment]
And possible symptoms.
