### ISSUE TITLE
[IMPROVEMENT] Minor log improvement

### ISSUE THREAD

**Issue by Vicente-Cheng** [longhorn/longhorn#6396]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

I would like to improve some log format and add some logs for engine/instance.
A clear and non-over-flooding log would be helpful because we can only check the final status in most scenarios.

## Describe the solution you'd like

Improve some logs format and add some logs.

## Describe alternatives you've considered
None

**Comment by innobead** [comment]
@Vicente-Cheng Please describe what flooding logs you have seen, so later it would be helpful for QA when validating the issue or paying more attention to similar issues later.  

cc @longhorn/qa

**Comment by innobead** [comment]
Moving to `review` pipeline. @Vicente-Cheng Please also update the Zenhub status correctly, because I believe you will have more contributions later :)

**Comment by Vicente-Cheng** [comment]
Hi @innobead,
Sorry, I thought my description would not be clear.
No flooding logs here. I just mean I will try to add/refine some logs to help the investigation and ensure that the new logs are not flooding.

Also, I will check the Zenhub status once it should be moved next stage.
And thanks for the reminder!

**Comment by derekbit** [comment]
@Vicente-Cheng Can you update the status of the ticket? https://github.com/longhorn/longhorn-manager/pull/2089 was closed before.

**Comment by Vicente-Cheng** [comment]
Hi @derekbit, sorry for the late.

I thought we could close it because the longhorn-manager greatly refactored and added various logs.

Close it as completed. Thanks!
