### ISSUE TITLE
[BUG] Error deploying driver: CSI cannot be deployed because MountPropagation is not set: node loshu-kube-airflow01 is not support mount propagation

### ISSUE THREAD

**Issue by ming12713** [longhorn/longhorn#6399]
**Desc**
Hi,  Install Longhorn 1.5.0 and 1.5.1, encountered an issue with loshu-kube-airflow01 showing a 'Mount propagation not supported' error. we used containerd not docker, airflow01 node same as airflow02/03. Used `environment_check.sh ` all nodes is ok 
![Screenshot from 2023-07-27 13-33-43](https://github.com/longhorn/longhorn/assets/5196113/22a885a6-97cd-4f9e-b485-dc406da37ee8)

![Screenshot from 2023-07-27 13-33-01](https://github.com/longhorn/longhorn/assets/5196113/3c9e3578-4053-4332-b486-e6a79997ae22)
![Screenshot from 2023-07-27 13-35-55](https://github.com/longhorn/longhorn/assets/5196113/f3532850-52ae-467b-af9e-52fce38f741f)

**ENV**
![Screenshot from 2023-07-27 13-31-50](https://github.com/longhorn/longhorn/assets/5196113/3cf270c8-16d1-49ed-9c19-e70a74399972)

**Comment by mantissahz** [comment]
@ming12713 could you please help check logs of `longhorn-manager` pods to see if there is the log like
```txt
“Dropping Longhorn node longhorn-system/loshu-kube-airflow01 out of the queue: fail to sync node for longhorn-system/loshu-kube-airflow01: InstanceManager.longhorn.io "instance-manager-xxxxxx" is invalid: metadata.labels: Invalid value: "PRIVATE_REGISTRY_URL-PREFIX-longhorn-instance-manager-xxxxxx": must be no more than 63 characters”
```

**Comment by ming12713** [comment]
> Not met name more than 63 characters issue;

downgraded to version 1.4.3, the issue still persists. 

`
root@loshu-k8s-master01:~# cat longhorn-manager-xhc52.log |grep -i -E "err|faile"
time="2023-07-27T08:49:49Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: failed to execute: nsenter [--mount=/host/proc/37570/ns/mnt --net=/host/proc/37570/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/*': No such file or directory\n: exit status 2"
time="2023-07-27T08:49:50Z" level=warning msg="Failed to select node for sync backup target" controller=longhorn-setting error="no ready nodes available" node=loshu-kube-airflow01
time="2023-07-27T08:49:50Z" level=warning msg="Error syncing Longhorn setting longhorn-system/backup-target" controller=longhorn-setting error="failed to sync setting for longhorn-system/backup-target: failed to sync backup target: no ready nodes available" node=loshu-kube-airflow01
time="2023-07-27T08:49:50Z" level=warning msg="Failed to select node for sync backup target" controller=longhorn-setting error="no ready nodes available" node=loshu-kube-airflow01
time="2023-07-27T08:49:50Z" level=warning msg="Error syncing Longhorn setting longhorn-system/backup-target-credential-secret" controller=longhorn-setting error="failed to sync setting for longhorn-system/backup-target-credential-secret: failed to sync backup target: no ready nodes available" node=loshu-kube-airflow01
time="2023-07-27T08:49:50Z" level=warning msg="Failed to select node for sync backup target" controller=longhorn-setting error="no ready nodes available" node=loshu-kube-airflow01
time="2023-07-27T08:49:50Z" level=warning msg="Error syncing Longhorn setting longhorn-system/backup-target" controller=longhorn-setting error="failed to sync setting for longhorn-system/backup-target: failed to sync backup target: no ready nodes available" node=loshu-kube-airflow01
time="2023-07-27T08:49:50Z" level=warning msg="Failed to select node for sync backup target" controller=longhorn-setting error="no ready nodes available" node=loshu-kube-airflow01
time="2023-07-27T08:49:50Z" level=warning msg="Error syncing Longhorn setting longhorn-system/backup-target-credential-secret" controller=longhorn-setting error="failed to sync setting for longhorn-system/backup-target-credential-secret: failed to sync backup target: no ready nodes available" node=loshu-kube-airflow01
time="2023-07-27T08:49:50Z" level=warning msg="Failed to select node for sync backup target" controller=longhorn-setting error="no ready nodes available" node=loshu-kube-airflow01
time="2023-07-27T08:49:50Z" level=warning msg="Error syncing Longhorn setting longhorn-system/backup-target" controller=longhorn-setting error="failed to sync setting for longhorn-system/backup-target: failed to sync backup target: no ready nodes available" node=loshu-kube-airflow01
time="2023-07-27T08:49:50Z" level=warning msg="Failed to select node for sync backup target" controller=longhorn-setting error="no ready nodes available" node=loshu-kube-airflow01
time="2023-07-27T08:49:50Z" level=warning msg="Error syncing Longhorn setting longhorn-system/backup-target-credential-secret" controller=longhorn-setting error="failed to sync setting for longhorn-system/backup-target-credential-secret: failed to sync backup target: no ready nodes available" node=loshu-kube-airflow01
time="2023-07-27T08:49:50Z" level=warning msg="Failed to select node for sync backup target" controller=longhorn-setting error="no ready nodes available" node=loshu-kube-airflow01
E0727 08:49:50.756779       1 setting_controller.go:191] failed to sync setting for longhorn-system/backup-target: failed to sync backup target: no ready nodes available
time="2023-07-27T08:49:50Z" level=warning msg="Dropping Longhorn setting longhorn-system/backup-target out of the queue" controller=longhorn-setting error="failed to sync setting for longhorn-system/backup-target: failed to sync backup target: no ready nodes available" node=loshu-kube-airflow01
time="2023-07-27T08:49:50Z" level=warning msg="Failed to select node for sync backup target" controller=longhorn-setting error="no ready nodes available" node=loshu-kube-airflow01
E0727 08:49:50.756882       1 setting_controller.go:191] failed to sync setting for longhorn-system/backup-target-credential-secret: failed to sync backup target: no ready nodes available
time="2023-07-27T08:49:50Z" level=warning msg="Dropping Longhorn setting longhorn-system/backup-target-credential-secret out of the queue" controller=longhorn-setting error="failed to sync setting for longhorn-system/backup-target-credential-secret: failed to sync backup target: no ready nodes available" node=loshu-kube-airflow01
time="2023-07-27T08:49:51Z" level=debug msg="Cannot update latest Longhorn version" controller=longhorn-setting error="settings.longhorn.io \"latest-longhorn-version\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update" node=loshu-kube-airflow01
time="2023-07-27T08:49:51Z" level=warning msg="Failed to clean up all mount points" controller=longhorn-backup-target cred= error="failed to get engine client proxy:  instance manager is in , not running state" interval=5m0s node=loshu-kube-airflow01 url=
time="2023-07-27T08:49:56Z" level=warning msg="Failed to clean up all mount points" controller=longhorn-backup-target cred= error="failed to get engine client proxy:  instance manager is in , not running state" interval=5m0s node=loshu-kube-airflow01 url=
time="2023-07-27T08:49:56Z" level=warning msg="Failed to clean up all mount points" controller=longhorn-backup-target cred= error="failed to get engine client proxy:  instance manager is in , not running state" interval=5m0s node=loshu-kube-airflow01 url=
time="2023-07-27T08:49:56Z" level=warning msg="Failed to clean up all mount points" controller=longhorn-backup-target cred= error="failed to get engine client proxy:  instance manager is in , not running state" interval=5m0s node=loshu-kube-airflow01 url=
time="2023-07-27T08:49:56Z" level=warning msg="Failed to clean up all mount points" controller=longhorn-backup-target cred= error="failed to get engine client proxy:  instance manager is in , not running state" 

`

**Comment by mantissahz** [comment]
Could you please check logs of all three `longhorn-manager` pods and grep `fail to sync node`? Thanks

**Comment by ming12713** [comment]
> Could you please check logs of all three `longhorn-manager` pods and grep `fail to sync node`? Thanks, or you could provide the support bundle for investigating? And could you show the information by `kubectl describe node loshu-kube-airflow01` and `kubectl -n longhorn-system describe nodes.longhorn.io loshu-kube-airflow01`?

thanks @mantissahz , i fixed 
```
root@loshu-k8s-master01:~# kubectl  get nodes.longhorn.io -n longhorn-system
NAME                   READY   ALLOWSCHEDULING   SCHEDULABLE   AGE
loshu-kube-airflow01   True    true                             26h
loshu-kube-airflow02   True    true              True          7m7s
loshu-kube-airflow03   True    true              True          7m6s
```
i thinks unistall not delete nodes.longhorn.io , i flush etcd with all longhorn key ,and reinstall again, node is ready now
![Screenshot from 2023-07-27 17-58-38](https://github.com/longhorn/longhorn/assets/5196113/c95d9d9b-3c1c-410f-acbe-d8ed88351b73)
![Screenshot from 2023-07-27 18-07-40](https://github.com/longhorn/longhorn/assets/5196113/d3882a83-7fe5-48b4-b39a-9f2cdcad1217)

**Comment by ming12713** [comment]
@mantissahz yes, running well at v1.4.3， Currently, there are no errors
![Screenshot from 2023-07-28 10-11-01](https://github.com/longhorn/longhorn/assets/5196113/1cbad530-ebc5-4f08-ae85-0c01fba73ba6)

**Comment by innobead** [comment]
@ming12713 do we know why the previous install 1.5.1 failed? was it also due to the unclean env?

**Comment by ming12713** [comment]
> @ming12713 Yes  1.5.1 failed because 'uninstall.yaml' did not completely clear the etcd record `/registry/apiextensions.k8s.io/customresourcedefinitions/nodes.longhorn.io`

**Comment by mantissahz** [comment]
@ming12713
How did you install Longhorn? by Rancher, Helm or manually applying deploy manifest?
And How did you uninstall Longhorn? Thanks.

**Comment by ming12713** [comment]
> @ming12713 How did you install Longhorn? by Rancher, Helm or manually applying deploy manifest? And How did you uninstall Longhorn? Thanks.

@mantissahz use helm follow [ offical doc](https://longhorn.io/docs/1.5.1/deploy/install/install-with-helm/), uinstall follow[ this](https://longhorn.io/docs/1.5.1/deploy/uninstall/), helm uninstall failed return` Error: job failed: BackoffLimitExceeded`

then tried to manually [cleanup](https://raw.githubusercontent.com/longhorn/longhorn/v1.5.1/scripts/cleanup.sh) object

manually delete object thant not delete
`for crd in $(kubectl get crd -o name | grep longhorn); do kubectl patch $crd -p '{"metadata":{"finalizers":[]}}' --type=merge; done;`

verify obj
`kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found -n longhorn-system`
