### ISSUE TITLE
[BUG] SettingNameSnapshotDataIntegrityCronJob should be sent as boolean value

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#6410]
## Describe the bug (🐛 if you encounter this issue)

[SettingNameSnapshotDataIntegrityCronJob](https://github.com/longhorn/longhorn-manager/blob/e278ba0c2d2591dfae8f79b069574bf2ede7e330/controller/setting_controller.go#L1363) is currently sent as raw tag value. This could potentially create a lot of tags in the InfluxDB which lead to performance degradation. 

This setting should be send as boolean which mean it should be in this [includeAsBoolean](https://github.com/longhorn/longhorn-manager/blob/e278ba0c2d2591dfae8f79b069574bf2ede7e330/controller/setting_controller.go#L1316) map

## Environment
> Suggest checking the doc of the best practices of using Longhorn. [here](https://longhorn.io/docs/1.5.1/best-practices)

 - Longhorn version: v1.5.1

**Comment by PhanLe1010** [comment]
cc @c3y1huang

**Comment by PhanLe1010** [comment]
**Test Steps:**
1. Deploy an upgrade responder using this script https://github.com/longhorn/longhorn/tree/master/dev/upgrade-responder
1. Edit the Longhorn manager 1.5.x to update the URL [here](https://github.com/longhorn/longhorn-manager/blob/e8cfdc828f6a575ad6b14e6216c984bcd4c2ac2a/controller/setting_controller.go#L52C2-L52C2) to the URL of your local upgrade responder
1. Build the Longhorn manager image and deploy Longhorn 1.5.x-head together with that Longhorn manager image
1. Exec into the influxdb pod.. Run the following to list the data points (Note that the details of the below command might be misspelling because I wrote this one out of my memory):
```
# Login
influx -username=root -password=root

# Show and select database
show database
use longhorn-upgrade-responder

# show all data points
select * from upgrade_request 
```
1. Verify that the `longhorn_setting_snapshot_dataIntegrity_cronjob` tag has true value.

**Comment by c3y1huang** [comment]
> **Verified on master-head 20230821**
> 
> * longhorn `master-head` [3b04fa8](https://github.com/longhorn/longhorn/commit/3b04fa8c023b871bc321b84cf9479ebb7215b5df)
> * longhorn-manager `master-head` [longhorn/longhorn-manager@59b4379](https://github.com/longhorn/longhorn-manager/commit/59b4379c22fd218fe827f5c7d48b90023509a1db)
> 
> **Test Steps:**
> 
> 1. Edit the Longhorn manager `master` to update the URL [here](https://github.com/longhorn/longhorn-manager/blob/e8cfdc828f6a575ad6b14e6216c984bcd4c2ac2a/controller/setting_controller.go#L52C2-L52C2) to the URL of local upgrade responder and patch build and deploy Longhorn.
> 
> ```shell
> --- a/controller/setting_controller.go
> +++ b/controller/setting_controller.go
> @@ -49,7 +49,7 @@ const (
>  var (
>         upgradeCheckInterval          = time.Hour
>         settingControllerResyncPeriod = time.Hour
> -       checkUpgradeURL               = "https://longhorn-upgrade-responder.rancher.io/v1/checkupgrade"
> +       checkUpgradeURL               = "http://longhorn-upgrade-responder.default.svc.cluster.local:8314/v1/checkupgrade"
>  )
> ```
> 
> 2. Deploy an upgrade responder using this script https://github.com/longhorn/longhorn/tree/master/dev/upgrade-responder
> 3. Wait 1~2 hours for collection data to send to the influxDB database.
> 4. Collect data and verify whether the `longhorn_setting_snapshot_data_integrity_cronjob` tag has a value of `true`.
> 
> ```shell
> app_name="longhorn"
> influxdb_pod=$(kubectl get pod | grep influxdb | awk '{print $1}' | head -n 1)
> 
> kubectl exec -it ${influxdb_pod} -- influx -execute 'SELECT * FROM upgrade_request' -database="${app_name}_upgrade_responder" -format=csv > output.csv
> ```
> 
> **Result** Hi @PhanLe1010:
> 
> We could retrieve the `longhorn_setting_snapshot_data_integrity_cronjob` tag, but the tag does not have a value of `true`. Could you please review my steps to see if there are any issues?
> 
> [master-output.csv](https://github.com/longhorn/longhorn/files/12394952/master-output.csv) ![Screenshot_20230821_180530](https://user-images.githubusercontent.com/104337648/261992398-63e7bb9a-eed7-4779-84cf-bf642cbf7e25.png)
> 
> cc @c3y1huang

The boolean is an indication of whether the setting value differs from the default value.
I've noticed that in your provided steps, there doesn't seem to be an update to the setting. So it should show as false. As reflected in the master-output.csv.

**Comment by c3y1huang** [comment]
> **Test Steps:**
> 
> 1. Deploy an upgrade responder using this script https://github.com/longhorn/longhorn/tree/master/dev/upgrade-responder
> 2. Edit the Longhorn manager 1.5.x to update the URL [here](https://github.com/longhorn/longhorn-manager/blob/e8cfdc828f6a575ad6b14e6216c984bcd4c2ac2a/controller/setting_controller.go#L52C2-L52C2) to the URL of your local upgrade responder
> 3. Build the Longhorn manager image and deploy Longhorn 1.5.x-head together with that Longhorn manager image
> 4. Exec into the `influxdb` pod. Run the following to list the data points (Note that the details of the below command might be misspelling because I wrote this one out of my memory):
> 
> # Login
> influx -username=root -password=root
> 
> # Show and select database
> show DATABASES use longhorn_upgrade_responder
> 
> # show all data points
> select * from upgrade_request
> 
> **1. Verify that the `longhorn_setting_snapshot_dataIntegrity_cronjob` tag has true value.**

@PhanLe1010 We are confused about the expected test result.

We are expecting the value to be false right? Because there is no setting value update.

**Comment by roger-ryao** [comment]
> @PhanLe1010 We are confused about the expected test result.
> 
> We are expecting the value to be false right? Because there is no setting value update. The value is expected to be true only when the setting has been updated.

**Verified on master-head 20230822**

- longhorn master-head https://github.com/longhorn/longhorn/commit/b5379ad6b76ddbce59cf7811949a12d87d520606
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/f3a3fb38a19222bc5be82adabd8ff2edaedbd79a

**Test Steps:**
1. Edit the Longhorn manager `master` to update the URL [here](https://github.com/longhorn/longhorn-manager/blob/e8cfdc828f6a575ad6b14e6216c984bcd4c2ac2a/controller/setting_controller.go#L52C2-L52C2) to the URL of local upgrade responder and patch build and deploy Longhorn.
```bash
--- a/controller/setting_controller.go
+++ b/controller/setting_controller.go
@@ -49,7 +49,7 @@ const (
 var (
        upgradeCheckInterval          = time.Hour
        settingControllerResyncPeriod = time.Hour
-       checkUpgradeURL               = "https://longhorn-upgrade-responder.rancher.io/v1/checkupgrade"
+       checkUpgradeURL               = "http://longhorn-upgrade-responder.default.svc.cluster.local:8314/v1/checkupgrade"
 )
```
2. Deploy an upgrade responder using this script https://github.com/longhorn/longhorn/tree/master/dev/upgrade-responder
3. Update `longhorn_setting_snapshot_data_integrity_cronjob` value
    - Modify `Snapshot Data Integrity Check CronJob` from `0 0 */7 * *` to `0 0 */5 * *`.
5. Wait 1~2 hours for collection data to send to the influxDB database.
6. Collection data and Verify that the `longhorn_setting_snapshot_data_integrity_cronjob` tag.
    - Use the following command to export the data to a `CSV` file named `output.csv`:
```bash
app_name="longhorn"
influxdb_pod=$(kubectl get pod | grep influxdb | awk '{print $1}' | head -n 1)

kubectl exec -it ${influxdb_pod} -- influx -execute 'SELECT * FROM upgrade_request' -database="${app_name}_upgrade_responder" -format=csv > output.csv
```

**Result**
After updating the `Snapshot Data Integrity Check CronJob` from `0 0 */7 * *` to `0 0 */5 * *`, the `longhorn_setting_snapshot_data_integrity_cronjob` tag is set to `true`. If we don't update the `Snapshot Data Integrity Check CronJob` and keep the configuration at `default`, the `longhorn_setting_snapshot_data_integrity_cronjob` tag remains `false`.

Hi @PhanLe1010 :
     If this behavior is as expected, I will close the issue.

**Comment by PhanLe1010** [comment]
Thanks @roger-ryao and @c3y1huang . Yes, you are right. The expected value should be false. Sorry, I made a mistake in the reproducing steps.
