### ISSUE TITLE
[IMPROVEMENT] Remove or Change Helm pre-upgrade hook to support ArgoCD

### ISSUE THREAD

**Issue by belmeopmenieuwesim** [longhorn/longhorn#6415]
As of now, longhorn stopped working with ArgoCD, due to ArgoCD implementing helms post-upgrade hooks as `PreSync` (and they have no plans to change this, since they believe Helm charts should not use any pre/post upgrade hooks), causing it to run even the first time during installation. This causes the pre-upgrade job of Longhorn to fail, since the service account is not yet created.

It would be nice if this helm chart would be working in ArgoCD.

Also see this issue: https://github.com/argoproj/argo-cd/issues/7536#issuecomment-1656763866

**Comment by acelinkio** [comment]
Relates to: https://github.com/longhorn/charts/pull/126

**Comment by c3y1huang** [comment]
@acelinkio can you also create a PR to [longhorn/longhorn](https://github.com/longhorn/longhorn/tree/master/chart)?

**Comment by acelinkio** [comment]
@c3y1huang
Additional pr opened https://github.com/longhorn/longhorn/pull/6421

**Comment by frg** [comment]
I can see that this was added to the v1.6.0 milestone. Are there any plans for a v1.15 release? or a workaround we can use until then?

Thanks

**Comment by acelinkio** [comment]
@frg there is a partial solution to just apply the manifests manually via helm template--which is unable to apply any hooks.  From there hooks will have the resources to run properly.

**Comment by frg** [comment]
@acelinkio Thanks for the suggestion but wouldn't this also disable the [pre delete hook](https://github.com/longhorn/charts/blob/3b57266ab050578a858b53b53c355eb3110e12c2/charts/longhorn/templates/uninstall-job.yaml#L5) making uninstallation risky?

I think we'll have to go for v1.4, then a volume migration when we upgrade to v1.6. Can't find simple ways we can go around this.

**Comment by acelinkio** [comment]
Yeah... preselected hook is not supported.   I really don't know why these hooks are being used because none of these capabilities are available when doing the kubectl apply install method.  https://longhorn.io/docs/1.5.1/deploy/install/install-with-kubectl/

**Comment by innobead** [comment]
This will be backported to 1.5.

**Comment by innobead** [comment]
The pre-upgrade hook is only for the helm to prevent any invalid upgrade after upgrading the Longhorn setup to the new version, so it can ensure the current setup with the old version is intact if the upgrade hook failed. 

If using kubectl apply to do the upgrade, the same behavior will be tackled but it's after the Longhorn manager pods have been upgraded, so if the upgrade failed due to an invalid upgrade path, users need to recover it w/ some little effort than the helm way. For more detail, go check https://longhorn.io/docs/1.5.1/deploy/upgrade/longhorn-manager/#upgrading-from-unsupported-versions. 

However, we should tackle it better for GitOps solutions indeed.

cc @mantissahz add more context if anything I missed here. 

cc @longhorn/qa

**Comment by mantissahz** [comment]
Without pre-upgrade hook, you need to take care of upgrade path by yourself. You would need to roll back to previous REVISION manually by the CLI command if upgrade failed.
Yes, having a switch to disable pre-upgrade hook is good.

I've tested the PR by `helm upgrade` with and without enabling `helmPreUpgradeCheckerJob` and it is fine but not tested for ArgoCD.

**Comment by acelinkio** [comment]
Any updates on having these merged?   Looks like everything passed review/testing

**Comment by mrclrchtr** [comment]
I have also encountered this problem and would be very happy to see a solution. Currently I install it by hand and only then activate ArgoCD to manage the app.

**Comment by QuinnBast** [comment]
Commenting to keep in the loop on this.

We exclusively deploy to clusters using ArgoCD so this is preventing us from installing Longhorn and I'll probably have to investigate Linstor or OpenEBS unless this gets through in the next few weeks.

**Comment by mantissahz** [comment]
https://github.com/longhorn/longhorn/pull/6421 the PR is not merged yet,
@QuinnBast @mrclrchtr you might be able to follow the PR to disable the pre-upgrade check.

**Comment by MohammedNoureldin** [comment]
Thank you guys for fixing it. Will be there any Docker image or Helm chart release soon to integrate this?

**Comment by QuinnBast** [comment]
Agreed, the 1.5.1 chart doesn't seem to have these updates applied yet.

**Comment by innobead** [comment]
> Thank you guys for fixing it. Will be there any Docker image or Helm chart release soon to integrate this?
> 
> Will disabling this job have any negative effect?

We are going to release 1.5.2 on 11/6 that week and it will include this fix. 

Disabling it will have some effects but not negative ones. Please check this comment, https://github.com/longhorn/longhorn/issues/6415#issuecomment-1667718648.

**Comment by QuinnBast** [comment]
This is still not working after pulling 1.5.2...

> waiting for completion of hook batch/Job/longhorn-pre-upgrade

> Error creating: pods "longhorn-pre-upgrade-" is forbidden: error looking up service account longhorn/longhorn-service-account: serviceaccount "longhorn-service-account" not found

**Comment by MohammedNoureldin** [comment]
Does this fix work with 1.6.0? For some reason with 1.6.0 I am again not able to install even with using the helmPreUpgradeCheckerJob.enabled: false

Have anyone tried it?

**Comment by MohammedNoureldin** [comment]
OK I see it was renamed.

**Comment by Skoucail** [comment]
> OK I see it was renamed to `preUpgradeChecker.jobEnabled`, this is actually a breaking change for the chart, which is not reflected by the chart version.

Thanks! I followed the official documentation, but this still shows the old name. (https://longhorn.io/docs/1.6.1/deploy/install/install-with-argocd/)
This helped me deploy with argocd!
