### ISSUE TITLE
Typo in GitHub description

### ISSUE THREAD

**Issue by alexellis** [longhorn/longhorn#642]
`Cloud native, distributed block storage buil*d* on and for Kubernetes` should probably be:

`Cloud native distributed block storage built on and for Kubernetes`

or

`Cloud native distributed block storage built for Kubernetes`

The GitHub README clone instructions also point at the old repo rancher/longhorn, but should be updated to reflect the new location/home. https://github.com/longhorn/longhorn/blob/master/README.md#install-longhorn-with-helm

**Comment by yasker** [comment]
Thanks for pointing those out. We've fixed the description as well as update the repository references. Please kindly let us know if we missed anything.

**Comment by alexellis** [comment]
No problems
