### ISSUE TITLE
[DOC] How to install on EKS with Calico

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#6426]
### Discussed in https://github.com/longhorn/longhorn/discussions/6335

<div type='discussions-op-text'>

<sup>Originally posted by **druchoo** July 17, 2023</sup>
Hello, I'm trying Longhorn (v1.5.0) on EKS 1.24 with Calico using the official Helm Chart with all default values. longhorn-manager pods throw the following error and restart:

```
time="2023-07-15T20:44:00Z" level=fatal msg="Error starting manager: Internal error occurred: failed calling webhook \"validator.longhorn.io\": failed to call webhook: Post \"https://longhorn-admission-webhook.longhorn-system.svc:9502/v1/webhook/validaton?timeout=10s\": Address is not allowed"
```

Editing the `longhorn-manager` DaemonSet and setting `hostNetwork: true` resolves the issue. I see no mention of this in the docs or any issues that I could find. It's also not possible to set hostNetwork from the Chart. 

Is this the correct approach? Are there any issues with running longhorn-manager with host networking?

Thanks</div>

**Comment by c3y1huang** [comment]
ref: https://github.com/longhorn/longhorn/discussions/6335#discussioncomment-6463352

**Comment by druchoo** [comment]
Please reopen
