### ISSUE TITLE
[DOC] `deploy/longhorn.yaml` out of date - causes all longhorn-manager instances to crash-loop

### ISSUE THREAD

**Issue by cloudymax** [longhorn/longhorn#6428]
## Describe the bug (🐛 if you encounter this issue)

When installing longhorn using the official K3s docs, the user is linked to [deploy/longhorn.yaml](https://github.com/longhorn/longhorn/blob/master/deploy/longhorn.yaml).

In this manifest, the version deployed is `v1.4.0-dev`, however the container image linked is `longhornio/longhorn-manager:master-head` which now reports using version `1.6.0-dev`.

This causes an un-recoverable crash-loop due to the version mismatch because downgrading was blocked beginning in version 1.5.0 - https://longhorn.io/docs/1.5.1/deploy/upgrade/.

```bash
time="2023-07-31T11:17:19Z" level=info msg="Recovery-backend server is running at :9503"
                                                                                                        
time="2023-07-31T11:17:19Z" level=info msg="Checking if the upgrade path from v1.6.0-dev to v1.4.0-dev is supported"
                                                                                
time="2023-07-31T11:17:19Z" level=fatal msg="Error starting manager: failed to upgrade since downgrading from v1.6.0-dev to v1.4.0-dev is not supported"
```

## To Reproduce

- Have installed Longhorn via the official K3s docs prior the the 1.6.0-dev tags lifetime

- Attempt to resize a ephemeral volume this morning

- See that the resize fails due to inability to mount

- Reboot the node

- See all management pods fail to start with the error above

## Expected behavior

definitely not that

## Support bundle for troubleshooting

Cannot, system is unrecoverable

## Environment

 - Longhorn version: 1.4.0-dev
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl using the official k3s docs
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 0
 - Node config
   - OS type and version: Debian12
   - Kernel version: 6.1
   - CPU per node: 16
   - Memory per node: 128
   - Disk type(e.g. SSD/NVMe/HDD): NVMe RAID1
   - Network bandwidth between the nodes: 1/Gb
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Bare-metal (Hetzner VPS)
 - Number of Longhorn volumes in the cluster: 21

**Comment by innobead** [comment]
The doc should be updated since the master versions should not be suggested to use. It's under development. However, the manifest on the master should be updated as well, because it's for 1.6 dev now.

**Comment by innobead** [comment]
@cloudymax Thanks for reporting this. Can you let me know where is the K3s doc?

**Comment by cloudymax** [comment]
> 

Sure, here's a link to the line: https://github.com/k3s-io/docs/blob/1b8e6fde4f93864a191a734b5a073f1235e32554/docs/storage/storage.md?plain=1#L110

**Comment by brandond** [comment]
Docs are updated, but since we're now pointing to a tag instead of master, it would be helpful if someone occasionally checked to see if we should update the docs again to point at a newer tag.
