### ISSUE TITLE
Adding nodes

### ISSUE THREAD

**Issue by thbeh** [longhorn/longhorn#643]
Hi, I have been testing with Longhorn for quite a while now and happy with the longhorn UI  adding new nodes functionality. My question is, apart from using Longhorn UI, are there any other ways that I could define the structure of my nodes (with raw device), maybe using yaml, adding the nodes and device when deploying longhorn?

**Comment by yasker** [comment]
Hi @thbeh ,

There are multiple features related here:
1. In the next release, users can choose which new nodes would be used automatically by Longhorn and which directory they would use as the default data path. See #582 and #583 .
2. The settings of the two options when deploying longhorn will be covered by #623 . But I guess what you want is to have node added automatically in the disabled state then update Longhorn configuration after you deployed Longhorn.
3. We will have a Longhorn CLI to help to configure Longhorn with the command line, we're tracking it at #613 . 
4. Longhorn currently doesn't support raw devices. Users need to format the device and mount it on the node before Longhorn can use it.

**Comment by thbeh** [comment]
Yes, I believe #623 make sense and something similar below (from glusterfs/heketi) would be good - 
        {
          "node": {
            "hostnames": {
              "manage": [
                "k8s-w3"
              ],
              "storage": [
                "192.168.34.13"
              ]
            },
            "zone": 1
          },
          "devices": [
            "/data1",
            "/data2",
            "/data3"
          ]
        }
And this config (json or yaml) could be pick up during longhorn deployment.

Thanks

**Comment by yasker** [comment]
@thbeh I think what you need is more than #623 . #623 only dealt with the global setting of Longhorn, not node configuration. And there is no way to configure node if the node is not there. So sounds like you would need #613 to help with the node configuration (which is a common feature request we've received recently).
