### ISSUE TITLE
[BUG] Permission denied when starting longhorn-ui container

### ISSUE THREAD

**Issue by thooooooomas** [longhorn/longhorn#6430]
## Describe the bug (🐛 if you encounter this issue)

After building longhorn-ui repo with `make` and then starting with `make run`, the container starts and immeadiately stops. `docker logs <container-id>` shows 

mkdir: cannot create directory '/var/config': Permission denied
/bin/bash: /etc/nginx/nginx.conf.template: Permission denied

## To Reproduce

Go to longhorn-ui repo
`make`
`make run`
`docker ps`
See that the longhorn-ui container is no longer running
`docker logs <container-id>`
See permission issue

## Expected behavior

Should be no permission issue

## Environment

 - Longhorn version: v1.5.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): N/A, just building image and running with docker
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 0

**Comment by thooooooomas** [comment]
I suspect it is this line?
https://github.com/longhorn/longhorn-ui/blob/master/Dockerfile#L30

Does this user have the necessary permissions to create dirs

**Comment by c3y1huang** [comment]
cc @mantissahz can you take a look at this issue?
ref: https://github.com/longhorn/longhorn-ui/pull/523

**Comment by mantissahz** [comment]
@thooooooomas yeah it is, but it works when it is deployed on k8s.
If you want to test the UI, you could remove `USER` first.
I would have a PR to fix this situation.
Thanks for reporting.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-ui `1b2b2d`) with test [steps](https://github.com/longhorn/longhorn/issues/6430#issue-1829709146)

- Can reproduce on v1.5.1 but can not reproduce on master
- Deploy Longhorn master on k8s cluster,  Longhorn UI can be accessed without problem
