### ISSUE TITLE
[FEATURE] V2 Data Engine supports ARM platform

### ISSUE THREAD

**Issue by zqzzq** [longhorn/longhorn#6439]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Currently, V2 Data Engine only supports x86_64 platform, but my longhorn is running in ARM platform, I also want to use V2 Data Engine to improve performance, so I want to know when the ARM platform will be supported? Or is there a way to use V2 Data Engine on the ARM platform.

## Describe the solution you'd like

V2 Data Engine supports ARM platform.

**Comment by c3y1huang** [comment]
Duplicated to https://github.com/longhorn/longhorn/issues/6021
