### ISSUE TITLE
engine: Remove the timeout mechanism for restoration

### ISSUE THREAD

**Issue by shreesha21** [longhorn/longhorn#644]
~~As backup creation is asynchronous, we should have a mechanism to check if there is some progress being made towards completion. Otherwise, the backup creation should timeout and fail.~~

We've decided to remove the timeout mechanism since if the process is still running without error, it should still working on it. We were worried about it may hang sometime but for restoration, user can see the progress and choose to retry; for backup, user can initiate another backup. Not really a blocking issue.

**Comment by yasker** [comment]
To be safe, let set it to 30 minutes instead. Also we can do the same with restoration.

**Comment by yasker** [comment]
Done.
