### ISSUE TITLE
[BUG] Backing image disk state unknown after unmount disk

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#6443]
## Describe the bug (🐛 if you encounter this issue)

It's a minor issue and come from test case `test_backing_image_with_disk_migration` [step 8](https://github.com/longhorn/longhorn-tests/blob/a2cfbebcecc583809917b98bf38be946becf879b/manager/integration/tests/test_backing_image.py#L402)

After unmount the disk, the backing image disk state will become `unknown` not `failed` as described in test skeleton
May need help to confirm if this is correct behavior.

```
Status:
  Checksum:  bd79ab9e6d45abf4f3f0adf552a868074dd235c4698ce7258d521160e0ad79ffe555b94e7d4007add6e1a25f4526885eb25c53ce38f7d344dd4925b9f2cb5d3b
  Disk File Status Map:
    13c46a83-62b0-4127-9a5c-38feee53445a:
      Last State Transition Time:  2023-08-02T07:05:15Z
      Message:                     
      Progress:                    100
      State:                       ready
    47c0d1ae-aad4-4116-8f21-29ca12524350:
      Last State Transition Time:  2023-08-02T07:05:25Z
      Message:                     
      Progress:                    100
      State:                       ready
    ff49c632-aacf-45ba-ac22-8fd8ea41493e:
      Last State Transition Time:  2023-08-02T07:06:32Z
      Message:                     
      Progress:                    100
      State:                       unknown
```
## To Reproduce

Perforrm [test_backing_image_with_disk_migration](https://github.com/longhorn/longhorn-tests/blob/a2cfbebcecc583809917b98bf38be946becf879b/manager/integration/tests/test_backing_image.py#L402) until step 8 or

1. Create a new host disk in a 3 nodes cluster
2. Disable the default disk and add the extra disk with scheduling enabled for the current node.
3. Create a backing image
4. Create and attach a 3-replica volume with the backing image set
   - There should have a replica scheduled to the new disk
   - There should have 3 entries in the backing image disk file status map, and each are state `ready`
5. Unmount the host disk. Verify
   - The disk state in the backing image will become `failed` 
   - The related download pod named `<Backing image name>-<First 8 characters of disk UUID>` is removed.

But actually the state is `unknown`, backing-image-manager pod on the disk fail node is still running

## Expected behavior

Backing image disk state on unmnut node should become failed and backing-image-manager pod on disk failed node removed. 
Or test skeleton need have update.

## Support bundle for troubleshooting

[supportbundle_b5ca39ef-141a-4ce9-be61-ce5a59790294_2023-08-02T07-17-15Z.zip](https://github.com/longhorn/longhorn/files/12237176/supportbundle_b5ca39ef-141a-4ce9-be61-ce5a59790294_2023-08-02T07-17-15Z.zip)

## Environment

 - Longhorn version: master-head `e1f1d3`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.27.3+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3

## Additional context

https://github.com/longhorn/longhorn/issues/6422

**Comment by ChanYiLin** [comment]
It should be unknown


When BackingImageManagerController finds that the disk is not ready, it marks the `bim.Status.CurrentState = longhorn.BackingImageManagerStateUnknown` then update all the BackingImages in this Manager to `Unknown` 

https://github.com/longhorn/longhorn-manager/blob/8cdf6820620161a0e2b1e71f2994a3c4f763917c/controller/backing_image_manager_controller.go#L291-L309

https://github.com/longhorn/longhorn-manager/blob/8cdf6820620161a0e2b1e71f2994a3c4f763917c/controller/backing_image_manager_controller.go#L369-L393

cc @shuo-wu

**Comment by ChanYiLin** [comment]
I think @shuo-wu have refactored the BackingImage after this test skeleton
I will verified the correct behavior and update the test.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `d88722`)

Following all steps in test [skeletons](https://github.com/longhorn/longhorn-tests/blob/58759d24505417ef0fb2d6e4baec199e6215fbf3/manager/integration/tests/test_backing_image.py#L409) to perform `test_backing_image_with_disk_migration`, Longhorn behaved as expected.
`
