### ISSUE TITLE
Backup Cluster

### ISSUE THREAD

**Issue by jocarren** [longhorn/longhorn#645]
I have a question regarding a concept mentioned in the docs:

https://github.com/longhorn/longhorn/blob/master/docs/dr-volume.md

What is a main and backup cluster? is it a Rancher feature? A Kubernetes practice? 

Where can I find info about it?

**Comment by yasker** [comment]
Hi @jocarren 

By backup cluster, we simply mean a Kubernetes cluster was set up for backup purpose. There is no extra configuration for it.

The idea is if the main cluster is done, the backup cluster can take over soon. It normally needs manual intervene like configure the global DNS to point to the new cluster etc.

**Comment by jocarren** [comment]
I see, thought it was some deployment filosophy or backup-o-matic feature. 

Thanks.
