### ISSUE TITLE
[IMPROVEMENT] Provide more information for volume scheduling failure

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6461]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

When a user encounters a volume scheduling failure, it can be challenging to pinpoint the specific cause of the issue from the UI message. We've already added the cause in the PV annotation `longhorn.io/volume-scheduling-error`. This can make the user experience better by showing the error along with the `Replica Scheduling Failure` message.

![image](https://github.com/longhorn/longhorn/assets/12527233/88b149de-0f3a-4ef0-b119-2eb8984eaaea)

**Comment by derekbit** [comment]
cc @smallteeths

**Comment by chriscchien** [comment]
Verified **pass** on longhorn-master(longhorn-ui `1b2b2d`)

When a volume scheduling failure, UI will show more information about the failure reason

 
![Screenshot from 2023-08-24 15-20-29](https://github.com/longhorn/longhorn/assets/73337386/cd3e5a2a-608e-4e75-bdfa-2b0d4418647f)
![Screenshot from 2023-08-24 15-19-57](https://github.com/longhorn/longhorn/assets/73337386/8cf6a11d-b22a-4000-8fe9-fcb72f38da4f)
