### ISSUE TITLE
[BUG] Removed IM CPU request settings still exists and new IM CPU request missed from chart settings

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6465]
## Describe the bug (🐛 if you encounter this issue)

The removed CPU settings of IM pods (guaranteedEngineManagerCPU, guaranteedReplicaManagerCPU) still exist in the chart setting but also missed the new CPU setting of the consolidated IM pod (guaranteedInstanceManagerCPU).

https://github.com/longhorn/longhorn/pull/6458#issue-1838158479

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

cc @yardenshoham @longhorn/qa @c3y1huang

**Comment by innobead** [comment]
@longhorn/qa this was missed from the testing.

**Comment by c3y1huang** [comment]
## Pre Ready-For-Testing Checklist
* [x] Where is the reproduce steps/test steps documented?
The reproduce steps/test steps are at: issue description

* [x] ~Is there a workaround for the issue? If so, where is it documented?~
The workaround is at:

* [x] Does the PR include the explanation for the fix or the feature?

* [x] ~Does the PR include deployment change (YAML/Chart)? If so, where are the PRs for both YAML file and Chart?~
The PR for the YAML change is at:
The PR for the chart change is at: https://github.com/longhorn/longhorn/pull/6458

* [x] Have the backend code been merged (Manager, Engine, Instance Manager, BackupStore etc) (including `backport-needed/*`)?
The PR is at:

* [x] Which areas/issues this PR might have potential impacts on?
Area system-backup, backupstore
Issues

* [x] ~**If labeled: require/LEP** Has the Longhorn Enhancement Proposal PR submitted?~
The LEP PR is at

* [x] ~**If labeled: area/ui** Has the UI issue filed or ready to be merged (including `backport-needed/*`)?~
The UI issue/PR is at

* [x] ~**If labeled: require/doc** Has the necessary document PR submitted or merged (including `backport-needed/*`)?~
The documentation issue/PR is at

* [x] ~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case? If only test case skeleton w/o implementation, have you created an implementation issue (including `backport-needed/*`)~
The automation skeleton PR is at
The automation test case PR is at
The issue of automation test case implementation is at (please create by [the template](https://github.com/longhorn/longhorn/issues/new?assignees=&labels=area%2Ftest&template=test.md&title=%5BTEST%5D))

* [x] ~**If labeled: require/automation-engine** Has the engine integration test been merged (including `backport-needed/*`)?~
The engine automation PR is at

* [x] ~**If labeled: require/manual-test-plan** Has the manual test plan been documented?~
The updated manual test plan is at

* [x] ~**If the fix introduces the code for backward compatibility** Has a separate issue been filed with the label `release/obsolete-compatibility`?~
The compatibility issue is filed at

**Comment by chriscchien** [comment]
Verified in longhorn master (longhorn `8146f3`)

- [x] `guaranteedInstanceManagerCPU` can set in values.yaml and will take effect on `guaranteed-instance-manager-cpu` after helm installation
- [x] Setting `guaranteed-instance-manager-cpu` can be modified after helm installation
- [x] Can not see `guaranteed-engine-manager-cpu` , `guaranteed-replica-manager-cpu` afert helm installation

I find that those new changes not synced to https://github.com/longhorn/charts and I need help to confirm if this is correct flow, thank you

cc @innobead
