### ISSUE TITLE
[BUG][v1.5.1] uninstall longhorn using kubectl meet problem

### ISSUE THREAD

**Issue by Zyh2333** [longhorn/longhorn#6470]
## Describe the bug (🐛 if you encounter this issue)

uninstall longhorn using kubectl meet:
E0807 15:17:39.843927       1 crd_finalizer.go:299] nodes.longhorn.io failed with: timed out waiting for the condition
E0807 15:17:54.024228       1 crd_finalizer.go:299] engineimages.longhorn.io failed with: timed out waiting for the condition
so the longhorn-system namespace is always being terminating status
when using "kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs deleting-confirmation-flag"
it shows that:
Error from server (NotFound): the server could not find the requested resource (get settings.longhorn.io deleting-confirmation-flag)

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by james-munson** [comment]
It would be good to know what the installed version of Longhorn is, as well as the version of uninstall.yaml used.  This was filed against 1.5.1, and it seems possible that the 1.5.1 uninstaller is running against a 1.4 installation, given that the symptom is the absence of the setting "settings.longhorn.io deleting-confirmation-flag", which was introduced in 1.5.

The uninstallers are meant to be run only against the version they belong to.  They don't support cleaning up previous versions.

Can we get a set of steps taken, and possibly a support bundle?

**Comment by Zyh2333** [comment]
> 
I just follow the v1.5.1 installation using kubectl https://longhorn.io/docs/1.5.1/deploy/install/install-with-kubectl.
When I want to uninstall it, I forget to set the setting "settings.longhorn.io deleting-confirmation-flag", using:
kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/v1.5.1/uninstall/uninstall.yaml
kubectl get job/longhorn-uninstall -n longhorn-system -w
but it can't work well, so i enter ctrl+c, and then using:
kubectl delete -f https://raw.githubusercontent.com/longhorn/longhorn/v1.5.1/deploy/longhorn.yaml
kubectl delete -f https://raw.githubusercontent.com/longhorn/longhorn/v1.5.1/uninstall/uninstall.yaml
finally, the longhorn-system namespace is always being terminating status.

**Comment by Zyh2333** [comment]
Finally, i try to modify the crd engineimages.longhorn.io's instance and the crd nodes.longhorn.io's instance to avoid finalizers' check.
For the engineimages.longhorn.io's instance:
using "kubectl edit engineimages.longhorn.io <instance name>", and modify the metadata.finalizers to [], it can be deleted successfully.
However, for the nodes.longhorn.io's instance:
when i use "kubectl edit nodes.longhorn.io <instance name>", and modify the metadata.finalizers to [], it raises two errors sequentially:
1. error: nodes.longhorn.io "<node name>" could not be patched: Internal error occurred: failed calling webhook "mutator.longhorn.io": failed to call webhook: Post "https://longhorn-admission-webhook.longhorn-system.svc:9502/v1/webhook/mutation?timeout=10s": service "longhorn-admission-webhook" not found.
2. error: nodes.longhorn.io "<node name>" could not be patched: Internal error occurred: failed calling webhook "validator.longhorn.io": Post "https://longhorn-admission-webhook.longhorn-system.svc:9502/v1/webhook/validaton?timeout=10s": service "longhorn-admission-webhook" not found.
At this time, i using "kubectl delete mutatingwebhookconfigurations longhorn-webhook-mutator" and "kubectl delete validatingwebhookconfigurations longhorn-webhook-validator" to unregister the webhooks.
Then i use "kubectl edit nodes.longhorn.io <instance name>", and modify the metadata.finalizers to [] again, it can be deleted successfully.
And the longhorn-system namespace can be deleted successfully.
Maybe this can help someone meeting the same problem, thanks a lot for the project manager.

**Comment by QuinnBast** [comment]
Hey there - I'm on 1.5.2 and also ran into this issue.

I didn't realize that Longhorn had a specific uninstall process and so to get rid of Longhorn, I instead just ran `kubectl delete namespace longhorn` to try to remove it. Then I realized there was an uninstaller but it was too late... I was fighting with finalizers, CRDs, and things not going away with similar logs to the ones shown above.

Specifically, this line solved it for me:

> At this time, i use `kubectl delete mutatingwebhookconfigurations longhorn-webhook-mutator` and `kubectl delete validatingwebhookconfigurations longhorn-webhook-validator` to unregister the webhooks.
Then I use `kubectl edit nodes.longhorn.io`, and modify the metadata.finalizers to [] again, it can be deleted successfully.
