### ISSUE TITLE
[BUG] Repeated failures creating new replicas (maybe: gRPC EOFs)

### ISSUE THREAD

**Issue by dnesting** [longhorn/longhorn#6471]
## Describe the bug (🐛 if you encounter this issue)

All (2) of my volumes are degraded with one good replica and endless cycles of failing to create the two missing replicas.  Logs report warnings about missing checksum files and gRPC EOF errors.

## To Reproduce

I don't know how specifically things got into this state.  I suspect it started after a power failure rebooted some of the nodes, but I can't really correlate anything since my Prometheus data is in one of those PVs.

## Expected behavior

Longhorn should recover or flag for human intervention whatever situation it's currently stuck in.

## Support bundle for troubleshooting

Support bundle is 114MB, so sharing via Google Drive:  
https://drive.google.com/file/d/1_aiZ3mblzjcvCgUhGEQ54UKX85hd_QOK/view?usp=sharing

## Environment

 - Longhorn version: 1.5.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm (fluxcd)
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: kubeadm 1.27.4
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 6
 - Node config
   - OS type and version: Ubuntu 22.04.2 LTS
   - Kernel version: 5.15.0-78-generic, 5.15.0-1034-raspi
   - CPU per node: 4, 2
   - Memory per node: 16GB, 4GB
   - Disk type(e.g. SSD/NVMe/HDD): SSD, HDD, SD
   - Network bandwidth between the nodes: 1Gbit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 2

## Additional context

Until the support bundle is done, these lines stick out as possibly problematic:

instance-manager trying to set up a new replica:

```
[pvc-c1ac82e3-d3a3-4b40-a50b-0943f08a70d5-r-c492c03e] time="2023-08-07T23:27:47Z" level=info msg="Ssync server is opened and ready for receiving file volume-snap-d022a6fb-1879-42e9-adc5-e90214fa13ab.img"                                         
[pvc-c1ac82e3-d3a3-4b40-a50b-0943f08a70d5-r-c492c03e] time="2023-08-07T23:29:02Z" level=error msg="sync agent gRPC server failed to rebuild replica/sync files" error="replica tcp://10.244.0.143:10000 failed to send file volume-snap-d022a6fb-18 
[pvc-c1ac82e3-d3a3-4b40-a50b-0943f08a70d5-r-c492c03e] 2023/08/07 23:29:02 ERROR: [core] [Server #1] grpc: server failed to encode response: rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil          
[longhorn-instance-manager] time="2023-08-07T23:29:02Z" level=info msg="Removing replica" engineName=pvc-c1ac82e3-d3a3-4b40-a50b-0943f08a70d5-e-116916c3 replicaAddress="tcp://10.244.1.119:10000" replicaName= serviceURL="10.244.1.119:10010"    
```

instance-manager with the good replica:

```
[pvc-c1ac82e3-d3a3-4b40-a50b-0943f08a70d5-r-7176ccee] time="2023-08-07T23:27:47Z" level=info msg="Syncing file volume-snap-d022a6fb-1879-42e9-adc5-e90214fa13ab.img to 10.244.1.119:10006"                                                          
[pvc-c1ac82e3-d3a3-4b40-a50b-0943f08a70d5-r-7176ccee] time="2023-08-07T23:27:47Z" level=info msg="Syncing file volume-snap-d022a6fb-1879-42e9-adc5-e90214fa13ab.img to 10.244.1.119:10006: size 10737418240, directIO true, fastSync false"        
[pvc-c1ac82e3-d3a3-4b40-a50b-0943f08a70d5-r-7176ccee] time="2023-08-07T23:27:47Z" level=warning msg="Failed to get change time and checksum of local file volume-snap-d022a6fb-1879-42e9-adc5-e90214fa13ab.img" error="failed to open checksum file 
```

**Comment by derekbit** [comment]
`missing checksum files` is a warning level message, so it is not related to the issue.
A support bundle is appreciated for further analysis.

**Comment by dnesting** [comment]
Just got it uploaded to Google Drive (114MB): https://drive.google.com/file/d/1_aiZ3mblzjcvCgUhGEQ54UKX85hd_QOK/view?usp=sharing

Thank you

**Comment by dnesting** [comment]
I was able to resolve this by rebooting all of the nodes in my cluster twice.  Either somewhere in the cordoning/uncordoning or just rebooting of things, the volumes started replicating correctly and my issues have disappeared.  I had a separate issue with one of the nodes having high CPU usage that may also have been contributing to the problem (maybe slow RPCs?), but I'm just guessing here.

**Comment by turowicz** [comment]
For me the solution was moving from a policy based IPSEC to a route based IPSEC.
