### ISSUE TITLE
[TEST] Execute the end-to-end pipeline on SLE Micro 5.4.

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#6474]
## What's the test to develop? Please describe

Execute the end-to-end pipeline on SLE Micro 5.4.

## Describe the items of the test development (DoD, definition of done) you'd like

- [x] Update the Latest Release information on https://github.com/longhorn/longhorn/wiki/Releases.
- [x] Execute the e2e pipelines for the following the Latest Release Longhorn versions on SLE Micro 5.4:
   - [x]  Longhorn 1.3.3
     - [x] [amd64](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/amd64/job/longhorn-upgrade-tests-sle-micro-amd64/2/) : 11 failures & [arm64](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/arm64/job/longhorn-upgrade-tests-sle-micro-arm64/3) : 9 failures
     - The failed test cases are either passed after rerun or known issues have tickets associated with them
        - https://github.com/longhorn/longhorn/issues/5815
        - https://github.com/longhorn/longhorn/issues/5972
   - [x]  Longhorn 1.4.3
     - [x] [amd64](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/amd64/job/longhorn-tests-sle-micro-amd64/21/) : 13 failures & [arm64](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/arm64/job/longhorn-tests-sle-micro-arm64/21/) : 14 failures
       -  The failed test cases are either passed after rerun or known issues have tickets associated with them.
           - https://github.com/longhorn/longhorn-tests/pull/1422
           - https://github.com/longhorn/longhorn/issues/6283
   - [x]  Longhorn 1.5.1
        - [x] [amd64](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/amd64/job/longhorn-tests-sle-micro-amd64/20/): 0 failures
        - [x]  [arm64](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/arm64/job/longhorn-tests-sle-micro-arm64/18/): 11 failures
          - [x] [Rerun the failed test case and pass](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/arm64/job/longhorn-tests-sle-micro-arm64/19/)

- [x] Update the content at https://longhorn.io/docs/1.5.1/best-practices/#operating-system.
  - https://github.com/longhorn/website/pull/764 

 
## Additional context

cc @longhorn/qa

**Comment by innobead** [comment]
Thanks @roger-ryao to drive this.

**Comment by roger-ryao** [comment]
- [x]  Longhorn 1.5.1 on SLE Micro 5.4.
        - [x] [amd64](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/amd64/job/longhorn-tests-sle-micro-amd64/20/): 0 failures
        - [x]  [arm64](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/arm64/job/longhorn-tests-sle-micro-arm64/18/): 11 failures
          - [x] [Rerun the failed test case and pass](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/arm64/job/longhorn-tests-sle-micro-arm64/19/)

**Comment by roger-ryao** [comment]
- [x]  Longhorn 1.4.3
     - [x] [amd64](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/amd64/job/longhorn-tests-sle-micro-amd64/21/) : 13 failures & [arm64](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/arm64/job/longhorn-tests-sle-micro-arm64/21/) : 14 failures
       -  The failed test cases are either passed after rerun or known issues have tickets associated with them.
           - https://github.com/longhorn/longhorn-tests/pull/1422
           - https://github.com/longhorn/longhorn/issues/6283
           
![Screenshot_20230811_103232](https://github.com/longhorn/longhorn/assets/104337648/5e73931f-199c-49ad-9f89-2c498c184b41)

**Comment by roger-ryao** [comment]
In Longhorn v1.3.3, the results of the following test cases were consistent, and we need to investigate further:
- `test_engine_image_not_fully_deployed_perform_volume_operations`
- `test_engine_image_not_fully_deployed_perform_dr_restoring_expanding_volume`
- `test_replica_auto_balance_should_respect_node_selector`
