### ISSUE TITLE
[TEST] Negative testing: Improve volume creation steps for scalability and ease of understanding

### ISSUE THREAD

**Issue by weizhe0422** [longhorn/longhorn#6478]
## What's the test to develop? Please describe

Currently, the volume creation steps will be as follows to allow for more scalability.
```robotframework
    ${number_of_replicas}=    Convert To Integer    3
    Set Test Variable    ${number_of_replicas}

    ${field1}=    Convert To String    {"spec": {"size": "${${volume_size_gb} * ${Gi}}"}}
    ${field2}=    Convert To String    {"spec": {"numberOfReplicas": ${number_of_replicas}}}
    ${field3}=    Convert To String    {"spec": {"accessMode": "${volume_type}"}}
    @{list_of_fields}=    Create List    ${field1}    ${field2}    ${field3}

    Given Create Volume With Fields    ${list_of_fields}
```
However, it may cause the test case to look more complicated. 

Therefore, we can further discuss how to balance scalability and comprehension.

## Describe the tasks for the test

- [ ] `item 1`
-->

## Additional context

https://github.com/longhorn/longhorn-tests/pull/1300#discussion_r1274344624
https://github.com/longhorn/longhorn-tests/pull/1300#issuecomment-1667447896

**Comment by yangchiu** [comment]
This will be refined in the next PR.
