### ISSUE TITLE
[BUG] The instance manager with state unknown will be cleaned up in the split-brain case

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#6479]
## Describe the bug (🐛 if you encounter this issue)

In some split-brain case, the **old** & **unknown** instance manager will be cleaned up by node controller unexpectedly, which then leads to all possible running engines crash.

Here the split-brain means that, A node **somehow** can fetch resources from the Kube API server but other nodes consider it as down or disconnected. Then all nodes (including the problematic node itself) will keep fighting for the ownership of the resources like InstanceManger or Engine or Replicas on that node, and the resources state will be marked as Unknown as well. Since the problematic node is still running and can get the resource from the API server, [its node controller will try to clean up the non-default unknown IMs in the reconcile loop](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/node_controller.go#L970-L985).

## To Reproduce

Not sure how to reach such a split-bran case...

## Expected behavior

The node controller should not do anything for the unknown IMs.

## Environment

 - Longhorn version: v1.4.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Harvester

## Additional context

We encountered this issue in a Harvester upgrade case. Here is the original ticket & flow: https://github.com/harvester/harvester/issues/4285#issuecomment-1668176509

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `dd6638`) with test [steps](https://github.com/longhorn/longhorn/issues/6479#issuecomment-1669936518) 

1. Below negative test cases [passed](https://ci.longhorn.io/job/private/job/longhorn-e2e-test/112/)
   - Reboot Volume Node While Workload Heavy Writing
   - Power Off Volume Node For More Than Pod Eviction Timeout While Workload Heavy Writing
   - Reboot Volume Node While Replica Rebuilding
2. Manual test case [Test kubelet restart on a node of the cluster](https://longhorn.github.io/longhorn-tests/manual/pre-release/node-not-ready/kubelet-restart/kubelet-restart-on-a-node/) passed
