### ISSUE TITLE
Data returned by websocket is inconsistent with the data returned by request

### ISSUE THREAD

**Issue by smallteeths** [longhorn/longhorn#648]
- longhorn ui
- On volume details page:
   - "Recurring Snapshot and Backup Schedule" section:
       - Click Edit > Click New > Click Save > Click Edit > Click New > Click Save > Cycle

This bug appears randomly,The main reason is that websocket’s data is older than what’s in the request sometime.

The request address is /v1/volumes
The ws address is /v1/ws/1s/volumes

![:Users:ouomouya:Downloads:Jietu20190724-143212](https://user-images.githubusercontent.com/27733391/61840218-0c50fa00-aec3-11e9-8a97-8235772cc045.jpg)

**Comment by yasker** [comment]
https://github.com/longhorn/longhorn-manager/pull/368 has added `timestamp` fields in the various resource and it should help the caller to know which status can be dropped if needed.

**Comment by yasker** [comment]
@smallteeths ^^

**Comment by yasker** [comment]
Done. Feel free to reopen if it happens again.
