### ISSUE TITLE
[IMPROVEMENT] Add missing volume settings to the default storage classs

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6496]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

https://github.com/longhorn/website/pull/762#discussion_r1287285770

## Describe the solution you'd like

Optionally add the missing settings to the default storage class for each installation way. Also, need to update the doc. 

## Additional context

cc @longhorn/qa @ejweber @james-munson

**Comment by ejweber** [comment]
Unless I'm mistaken, later versions of https://github.com/longhorn/website/pull/762/files actually already added all of these to the website, so we just need to do a quick check through there and update the default storage class.

**Comment by innobead** [comment]
@ejweber correct

**Comment by james-munson** [comment]
The sample storage class yaml in the docs page ./references/storage-class-parameters.md is complete in listing all the possible parameters and their defaults.

Does this issue ask to make sure that the sample yaml in ./references/examples should be the same?  Or is it targeting the actual sample yaml files in longhorn/longhorn/examples?  Or both?
