### ISSUE TITLE
Disable base image feature for now

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#650]
We need to disable base image for manager and manager integration test since the new deployment model doesn't support it currently.

We will reintroduce it later.

**Comment by yasker** [comment]
@smallteeths We also need to disable `base image` related fields in the UI.

**Comment by meldafrawi** [comment]
Base image disabled.

**Comment by meldafrawi** [comment]
`Base Image` need to be removed from `Create Disaster Recovery Volume` modal

![Screenshot from 2019-08-02 22-46-56](https://user-images.githubusercontent.com/18232258/62398051-e1783d00-b577-11e9-8565-5b136b6bbfcc.png)

**Comment by meldafrawi** [comment]
Fixed
