### ISSUE TITLE
[QUESTION] The longhorn node io surges, and the node appears NotReady status

### ISSUE THREAD

**Issue by yyzhou0811** [longhorn/longhorn#6501]
## Describe the bug (🐛 if you encounter this issue)

The shard suddenly became unavailable. Observed the status of the k8s node at that time, and found that the load of the k8s node was high due to the node io, and the node appeared NotReady

## LOG

W0809 06:40:14.045503 1 reflector.go:442] [k8s.io/client-go/informers/factory.go:134:](http://k8s.io/client-go/informers/factory.go:134:) watch of *v1.ConfigMap ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding

W0809 06:40:14.045549 1 reflector.go:442] [github.com/longhorn/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:117:](http://github.com/longhorn/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:117:) watch of *v1beta2.Node ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding

W0809 06:40:14.045568 1 reflector.go:442] [k8s.io/client-go/informers/factory.go:134:](http://k8s.io/client-go/informers/factory.go:134:) watch of *v1.Service ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding

W0809 06:40:14.045630 1 reflector.go:442] [k8s.io/client-go/informers/factory.go:134:](http://k8s.io/client-go/informers/factory.go:134:) watch of *v1.Node ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding

W0809 06:40:14.045639 1 reflector.go:442] [k8s.io/client-go/informers/factory.go:134:](http://k8s.io/client-go/informers/factory.go:134:) watch of *v1.CSIDriver ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding

W0809 06:40:14.045727 1 reflector.go:442] [k8s.io/client-go/informers/factory.go:134:](http://k8s.io/client-go/informers/factory.go:134:) watch of *v1.DaemonSet ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding

W0809 06:40:14.045750 1 reflector.go:442] [k8s.io/client-go/informers/factory.go:134:](http://k8s.io/client-go/informers/factory.go:134:) watch of *v1.Secret ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding

W0809 06:40:14.045756 1 reflector.go:442] [k8s.io/client-go/informers/factory.go:134:](http://k8s.io/client-go/informers/factory.go:134:) watch of *v1.Pod ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding

W0809 06:40:14.045809 1 reflector.go:442] [k8s.io/client-go/informers/factory.go:134:](http://k8s.io/client-go/informers/factory.go:134:) watch of *v1.Deployment ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding

I0809 06:40:14.155551 1 trace.go:205] Trace[376176241]: "DeltaFIFO Pop Process" ID:default/tw591-react-web-master,Depth:178,Reason:slow event handlers blocking the queue (09-Aug-2023 06:40:13.019) (total time: 1135ms):

Trace[376176241]: [1.135626684s] [1.135626684s] END

I0809 06:40:14.155567 1 trace.go:205] Trace[1216616799]: "DeltaFIFO Pop Process" ID:longhorn-system/longhorn-webhook-tls,Depth:49,Reason:slow event handlers blocking the queue (09-Aug-2023 06:40:13.019) (total time: 1135ms):

Trace[1216616799]: [1.135671162s] [1.135671162s] END

## Environment

Longhorn version:1.3.3
Kubernetes version:v1.19.9
Node config
OS type and version:CentOS Linux release 7.5.1804 (Core)
Kernel version:3.10.0
CPU per node: nolimit
Memory per node: nolimit
Disk type:480G SSD Single Disk（Read:85K,Write:35K）
Network bandwidth and latency between the nodes: 1000Mb/s
Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):Baremetal

## Additional context

abnormal iowaite
![image](https://github.com/longhorn/longhorn/assets/30650510/2422f524-7b34-4509-b437-9655e365f16d)
![image](https://github.com/longhorn/longhorn/assets/30650510/385cab12-f559-4ced-b6ae-c653067ec841)
![image](https://github.com/longhorn/longhorn/assets/30650510/0fbd177b-5310-4393-91a2-a56f43b1c26d)

We are useing Access Mode:ReadWriteMany with 2 Replicas

There is no problem with normal use and stress testing, but there will be occasional io exceptions, I hope everyone can help me investigate together

**Comment by c3y1huang** [comment]
Could you provide the support bundle?

There is another IO exception issue recently just raised [here](https://github.com/longhorn/longhorn/issues/6473).

**Comment by yyzhou0811** [comment]
> 您能提供支持包吗？
> 
> [最近刚刚在这里](https://github.com/longhorn/longhorn/issues/6473)提出了另一个IO异常问题。

No problem, this is our other set of clusters, I deleted some logs and uploaded them to you
[longhorn-support-bundle_03220242-27f0-4c37-b905-6d33eb5da3dc_2023-08-09T01-34-33Z 2.zip](https://github.com/longhorn/longhorn/files/12320026/longhorn-support-bundle_03220242-27f0-4c37-b905-6d33eb5da3dc_2023-08-09T01-34-33Z.2.zip)

**Comment by yyzhou0811** [comment]
> Could you provide the support bundle?
> 
> There is another IO exception issue recently just raised [here](https://github.com/longhorn/longhorn/issues/6473).

No problem, this is our other set of clusters, I deleted some logs and uploaded them to you
[longhorn-support-bundle_03220242-27f0-4c37-b905-6d33eb5da3dc_2023-08-09T01-34-33Z 2.zip](https://github.com/longhorn/longhorn/files/12320046/longhorn-support-bundle_03220242-27f0-4c37-b905-6d33eb5da3dc_2023-08-09T01-34-33Z.2.zip)

**Comment by derekbit** [comment]
@yyzhou0811 
Can you provide the UTC time when the high IO wait occurred?
I saw there are replica rebuilding around `2023-05-31T02:05:04`, but the rebuilding operations failed because 
```
2023-08-07T03:31:19.278509391Z time="2023-08-07T03:31:19Z" level=info msg="source file size: 5368709120, setting up directIO: true"
2023-08-07T03:31:44.270687448Z [pvc-8aebfbff-ed76-440e-93b7-47049d3c81f7-r-6766bd96] time="2023-08-07T03:31:44Z" level=error msg="getServerChecksum batchInterval:[  134208:  134240]( 32) failed, err: getChecksum failed, err: Get \"http://10.2.205.195:10009/v1-ssync/getChecksum?begin=549715968&end=549847040\": dial tcp 10.2.205.195:10009: connect: connection refused"
2023-08-07T03:31:44.270725967Z time="2023-08-07T03:31:44Z" level=error msg="getServerChecksum batchInterval:[  167995:  168027]( 32) failed, err: getChecksum failed, err: Get \"http://10.2.205.195:10009/v1-ssync/getChecksum?begin=688107520&end=688238592\": dial tcp 10.2.205.195:10009: connect: connection refused"
2023-08-07T03:31:44.271183587Z [pvc-8aebfbff-ed76-440e-93b7-47049d3c81f7-r-6766bd96] time="2023-08-07T03:31:44Z" level=error msg="getServerChecksum batchInterval:[  110688:  110720]( 32) failed, err: getChecksum failed, err: Get \"http://10.2.205.195:10009/v1-ssync/getChecksum?begin=453378048&end=453509120\": dial tcp 10.2.205.195:10009: connect: connection refused"
2023-08-07T03:31:44.271272123Z time="2023-08-07T03:31:44Z" level=error msg="getServerChecksum batchInterval:[  169620:  169652]( 32) failed, err: getChecksum failed, err: Get \"http://10.2.205.195:10009/v1-ssync/getChecksum?begin=694763520&end=694894592\": dial tcp 10.2.205.195:10009: connect: connection refused"
2023-08-07T03:31:56.813085007Z [pvc-8aebfbff-ed76-440e-93b7-47049d3c81f7-r-6766bd96] time="2023-08-07T03:31:56Z" level=info msg="Marking disk f6ba741f-3c8f-41b4-a5c6-b08dd7908c20 as removed"
```

**Comment by yyzhou0811** [comment]
> @yyzhou0811 Can you provide the UTC time when the high IO wait occurred? I saw there are replica rebuilding around `2023-05-31T02:05:04`, but the rebuilding operations failed because
> 
> ```
> 2023-08-07T03:31:19.278509391Z time="2023-08-07T03:31:19Z" level=info msg="source file size: 5368709120, setting up directIO: true"
> 2023-08-07T03:31:44.270687448Z [pvc-8aebfbff-ed76-440e-93b7-47049d3c81f7-r-6766bd96] time="2023-08-07T03:31:44Z" level=error msg="getServerChecksum batchInterval:[  134208:  134240]( 32) failed, err: getChecksum failed, err: Get \"http://10.2.205.195:10009/v1-ssync/getChecksum?begin=549715968&end=549847040\": dial tcp 10.2.205.195:10009: connect: connection refused"
> 2023-08-07T03:31:44.270725967Z time="2023-08-07T03:31:44Z" level=error msg="getServerChecksum batchInterval:[  167995:  168027]( 32) failed, err: getChecksum failed, err: Get \"http://10.2.205.195:10009/v1-ssync/getChecksum?begin=688107520&end=688238592\": dial tcp 10.2.205.195:10009: connect: connection refused"
> 2023-08-07T03:31:44.271183587Z [pvc-8aebfbff-ed76-440e-93b7-47049d3c81f7-r-6766bd96] time="2023-08-07T03:31:44Z" level=error msg="getServerChecksum batchInterval:[  110688:  110720]( 32) failed, err: getChecksum failed, err: Get \"http://10.2.205.195:10009/v1-ssync/getChecksum?begin=453378048&end=453509120\": dial tcp 10.2.205.195:10009: connect: connection refused"
> 2023-08-07T03:31:44.271272123Z time="2023-08-07T03:31:44Z" level=error msg="getServerChecksum batchInterval:[  169620:  169652]( 32) failed, err: getChecksum failed, err: Get \"http://10.2.205.195:10009/v1-ssync/getChecksum?begin=694763520&end=694894592\": dial tcp 10.2.205.195:10009: connect: connection refused"
> 2023-08-07T03:31:56.813085007Z [pvc-8aebfbff-ed76-440e-93b7-47049d3c81f7-r-6766bd96] time="2023-08-07T03:31:56Z" level=info msg="Marking disk f6ba741f-3c8f-41b4-a5c6-b08dd7908c20 as removed"
> ```
