### ISSUE TITLE
[TEST] build negative testing image and run as pod

### ISSUE THREAD

**Issue by weizhe0422** [longhorn/longhorn#6502]
## What's the test to develop? Please describe

The current design/PR(https://github.com/longhorn/longhorn-tests/pull/1300) method is run the testing in the local. It should support running as Pods in a cluster like current integration tests do.

## Describe the tasks for the test

- [ ] Dockerfile for having negative testing Pod 
- [ ] AWS access authority: credential and config file
- [ ] Add ClusterRole: `longhorn.io` in deployment manifest: https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/deploy/test.yaml
  ```yaml
  - apiGroups: ["longhorn.io"]
    resources: ["volumes", "volumes/status", "engines", "engines/status", "replicas", "replicas/status", "settings",
              "engineimages", "engineimages/status", "nodes", "nodes/status", "instancemanagers", "instancemanagers/status",
              "sharemanagers", "sharemanagers/status", "backingimages", "backingimages/status",
              "backingimagemanagers", "backingimagemanagers/status", "backingimagedatasources", "backingimagedatasources/status",
              "backuptargets", "backuptargets/status", "backupvolumes", "backupvolumes/status", "backups", "backups/status",
              "recurringjobs", "recurringjobs/status", "orphans", "orphans/status", "snapshots", "snapshots/status",
              "supportbundles", "supportbundles/status", "systembackups", "systembackups/status", "systemrestores", "systemrestores/status",
              "volumeattachments", "volumeattachments/status"]
  verbs: ["*"]
  ```

## Additional context

https://github.com/longhorn/longhorn-tests/pull/1300#discussion_r1289746044

**Comment by yangchiu** [comment]
According to @nitendra-suse, the negative testing execution used to work earlier, but now not working. Probably broken during PR review and modification. I'll try to fix this now.

**Comment by nitendra-suse** [comment]
> Setup failed:
> ConfigException: Service host/port is not set.

@yangchiu : I have fixed this issue by using 

```
try:
    config.load_incluster_config()
except config.ConfigException:
    try:
        config.load_kube_config()
     except config.ConfigException:
         raise Exception("Could not configure kubernetes python client")
```

instead of plain "config.load_incluster_config()" call in common_utils.py file

**Comment by yangchiu** [comment]
I'll refine this by adding `Dockerfile` and `test.yaml` and build new test image to run the test as a pod in k8s environment just like what we did in the existing test to make things simple.
cc @longhorn/qa @nitendra-suse @innobead

**Comment by yangchiu** [comment]
We've been able to run negative test in a pod now, but the build test image process hasn't been automated yet, currently we have to build test image manually.

But it could be not necessary anymore, since `rebooting all nodes` test cases prevent it from running in a pod.

Close this for now the the build test image process can be added in the future if it's needed.

**Comment by innobead** [comment]
@yangchiu create an issue to run test cases outside of the cluster.

**Comment by yangchiu** [comment]
> @yangchiu create an issue to run test cases outside of the cluster.

We've already been able to run test cases either in cluster or out of cluster.
