### ISSUE TITLE
[BUG] Support bundle url could be empty and cause unable to download support bundle 

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6503]
## Describe the bug (🐛 if you encounter this issue)

In [the download support bundle script](https://github.com/longhorn/longhorn-tests/blob/master/test_framework/scripts/download-support-bundle.sh), the `SUPPORT_BUNDLE_URL` could be empty, and cause following downloading support bundle code flow failed:
```
+ LH_FRONTEND_ADDR=10.43.99.4:80
+ JSON_PAYLOAD='{"issueURL": "Auto-generated support buundle", "description": "Auto-generated support buundle"}'
+ CURL_CMD='curl -XPOST [http://10.43.99.4:80/v1/supportbundles](http://10.43.99.4/v1/supportbundles) -H '\''Accept: application/json'\'' -H '\''Accept-Encoding: gzip, deflate'\'' -d '\''{"issueURL": "Auto-generated support buundle", "description": "Auto-generated support buundle"}'\'''
++ kubectl exec -n longhorn-system svc/longhorn-frontend -- bash -c 'curl -XPOST [http://10.43.99.4:80/v1/supportbundles](http://10.43.99.4/v1/supportbundles) -H '\''Accept: application/json'\'' -H '\''Accept-Encoding: gzip, deflate'\'' -d '\''{"issueURL": "Auto-generated support buundle", "description": "Auto-generated support buundle"}'\'''
++ jq -r '.links.self + "/" + .name'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   252  100   157  100    95  99116  59974 --:--:-- --:--:-- --:--:--  246k
parse error: Invalid numeric literal at line 1, column 7
+ SUPPORT_BUNDLE_URL=
```

https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-upgrade-tests-sles-arm64/564/console

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by c3y1huang** [comment]
This is related to the [the download support bundle script](https://github.com/longhorn/longhorn-tests/blob/master/test_framework/scripts/download-support-bundle.sh). I think this should be handled by the infra.
