### ISSUE TITLE
[TASK] Move common functions for backup to backupstore lib

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6514]
## What's the task? Please describe

The common functions for backup are used by longhorn-engine and longhorn-spdk-engine.
This is a subtask of https://github.com/longhorn/longhorn/issues/6138.

**Comment by shuo-wu** [comment]
Will we change [this](https://github.com/longhorn/longhorn-manager/blob/f3a3fb38a19222bc5be82adabd8ff2edaedbd79a/engineapi/backups.go#L76) either?

**Comment by derekbit** [comment]
> Will we change [this](https://github.com/longhorn/longhorn-manager/blob/f3a3fb38a19222bc5be82adabd8ff2edaedbd79a/engineapi/backups.go#L76) either?

Currently, no. 
The changes are progressive. I will create another PRs for other parts.
