### ISSUE TITLE
[BUG] test_engine_image_not_fully_deployed_perform_volume_operations failed on Longhorn v1.3.3 with SLE Micro

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#6516]
## Describe the bug (🐛 if you encounter this issue)

I have observed that the test case `test_engine_image_not_fully_deployed_perform_volume_operations` & `
test_engine_image_not_fully_deployed_perform_dr_restoring_expanding_volume`
are failing on Longhorn v1.3.3 and SLE Micro `5.3` & `5.4`.

## To Reproduce

1. Rerun the [test case ](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/arm64/job/longhorn-upgrade-tests-sle-micro-arm64/3/testReport/junit/tests/test_ha/test_engine_image_not_fully_deployed_perform_volume_operations_s3_/) on Longhorn `v1.3.3` and SLE Micro `5.3` & `5.4`.

## Expected behavior

We should have consistent test results on all distro.

## Support bundle for troubleshooting

[longhorn-upgrade-tests-sle-micro-arm64-3-bundle.zip](https://github.com/longhorn/longhorn/files/12331631/longhorn-upgrade-tests-sle-micro-arm64-3-bundle.zip)

## Environment

 - Longhorn version:`v1.3.3`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): `Kubectl`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: `v1.24.15+k3s1`
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: SLE Micro  `5.4`
   - Kernel version: 
   - CPU per node: 4 cores
   - Memory per node: 16G
   - Disk type(e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes: 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 1

## Additional context

N/A

**Comment by chriscchien** [comment]
Did the manual reproduction also fail at the same step as the test script?

**Comment by roger-ryao** [comment]
> Did the manual reproduction also fail at the same step as the test script?

Hi @chriscchien :
    I discovered that the issue is caused by https://github.com/longhorn/longhorn/issues/5815. 
    I will close the ticket.
