### ISSUE TITLE
[IMPROVEMENT] Add nvmecli to IM image

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6517]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Currently, go-spdk-helper is a wrapper of nvmecli, which means a dependency on host. Especially, there would be some compatibility issues between it's versions, and the command output would impact go-spdk-helper. 

The goal is to decouple this dependency from the host, but only general nvm-tcp and initiator are required on host.

## Describe the solution you'd like

Add nvmecli to IM pod. Use it instead of the one on host. 

## Additional context

cc @longhorn/dev-data-plane

**Comment by innobead** [comment]
cc @derekbit

**Comment by c3y1huang** [comment]
Close in favor of https://github.com/longhorn/longhorn/issues/6798.
