### ISSUE TITLE
UI: Require user to fill in support bundle's issue description

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#652]
It will help the developer to know what's wrong.

Also, let users know they can send support bundle to `longhorn-support-bundle@rancher.com`

**Comment by meldafrawi** [comment]
Validation: FAILED

Steps to test:
  - on UI footer, click on `Generate Support Bundle`
    (1) Leave `Description` empty, and click `OK`
    >> Expected result: an error message should appear state that:
         "Please fill in support bundle's issue description"

    (2) Enter a single white space, and click `OK`
    >> Expected result: an error message should appear  **(FAILED)**

    (3) Enter a description, and click `OK`
    >> Expected result: should be able to generate the support bundle, and description should exist in "metadata.yaml"

**Comment by yasker** [comment]
@meldafrawi Fix merged.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
