### ISSUE TITLE
[BUG] Make restore volume degrade cause the volume restoration never complete

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#6522]
## Describe the bug (🐛 if you encounter this issue)

From master pipeline test result(build [590](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/590/)). 

When a volume is in restoration, make this volume degraded(delete 1 replica or crash 1 replica process), will cause volume restoration never complete.(the rebuild of previous delete/crashed replica stuck at rebuilding state)

Below are test cases affected, they all failed at `wait_for_volume_restoration_completed` or `wait_for_volume_healthy_no_frontend` timeout:
- `test_single_replica_restore_failure`
- `test_rebuild_with_inc_restoration`
- `test_rebuild_with_restoration`
- `test_dr_volume_with_restore_command_error`
- `test_inc_restoration_with_multiple_rebuild_and_expansion`

longhorn-manager log
```
time="2023-08-15T01:58:52Z" level=info msg="Verifying the rebuild of replica tcp://10.42.0.11:10010 after restore completion" controller=longhorn-engine engine=werty-e-a93420c0 node=ip-172-31-40-45
time="2023-08-15T01:58:52Z" level=error msg="Failed to verify the rebuild of replica tcp://10.42.0.11:10010 after restore completion" controller=longhorn-engine engine=werty-e-a93420c0 error="failed to verify replica rebuild: missing required replicaName parameter" node=ip-172-31-40-45
time="2023-08-15T01:58:52Z" level=info msg="Skipped rebuilding of replica because there is another rebuild in progress" controller=longhorn-engine node=ip-172-31-40-45 volume=werty
time="2023-08-15T01:58:55Z" level=info msg="Skipped rebuilding of replica because there is another rebuild in progress" controller=longhorn-engine node=ip-172-31-40-45 volume=werty
time="2023-08-15T01:58:56Z" level=info msg="Skipped rebuilding of replica because there is another rebuild in progress" controller=longhorn-engine node=ip-172-31-40-45 volume=werty
time="2023-08-15T01:58:57Z" level=info msg="Verifying the rebuild of replica tcp://10.42.0.11:10010 after restore completion" controller=longhorn-engine engine=werty-e-a93420c0 node=ip-172-31-40-45
time="2023-08-15T01:58:57Z" level=error msg="Failed to verify the rebuild of replica tcp://10.42.0.11:10010 after restore completion" controller=longhorn-engine engine=werty-e-a93420c0 error="failed to verify replica rebuild: missing required replicaName parameter" node=ip-172-31-40-45
time="2023-08-15T01:58:57Z" level=info msg="Skipped rebuilding of replica because there is another rebuild in progress" controller=longhorn-engine node=ip-172-31-40-45 volume=werty
```
After 1 replica deleted/crashed, the new generated replica status
```
Status:
  Conditions:
    Last Probe Time:       
    Last Transition Time:  2023-08-15T01:42:27Z
    Message:               
    Reason:                
    Status:                True
    Type:                  InstanceCreation
    Last Probe Time:       
    Last Transition Time:  2023-08-15T01:42:37Z
    Message:               
    Reason:                
    Status:                False
    Type:                  RebuildFailed
  Current Image:           longhornio/longhorn-engine:master-head
  Current State:           running
```

## To Reproduce

1. Setup longhorn master(v1.6 dev) on a 3 nodes cluster
2. Setup a backup store
3. Create a 3 Gi volume with workload, write 2 Gi data into mount point
4. Create backup
5. Restore backup to a volume with 3 replicas
6. When restoration is in progress, delete 1 replica, the restore volume degraded
7. The volume restoration never complete. volume kept in degrade status

## Expected behavior

Volume restore complete success.

## Support bundle for troubleshooting

[supportbundle_2b7b0be7-2ac0-4172-bd09-93ccdbf16e24_2023-08-15T01-53-08Z.zip](https://github.com/longhorn/longhorn/files/12340629/supportbundle_2b7b0be7-2ac0-4172-bd09-93ccdbf16e24_2023-08-15T01-53-08Z.zip)

## Environment

 - Longhorn version: master `3b04fa` (1.6 dev)
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.27.3+k3s1
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS

## Additional context

Did not observe in v1.5.x
https://github.com/longhorn/longhorn/issues/5460

**Comment by mantissahz** [comment]
Looks like it is caused by https://github.com/longhorn/longhorn-manager/blob/master/engineapi/proxy_replica.go#L56, replicaName is "".
and https://github.com/longhorn/longhorn-instance-manager/blob/master/pkg/client/proxy_replica.go#L158 not allow replicaName is "".

cc @ejweber

**Comment by ejweber** [comment]
Assigned myself, as I think @mantissahz is correct. This is introduced by my engine-identity changes. I need to carefully consider the best way to fix it, so I'm going to backlog it for a few days until I get some other things taken care of. Let me know if I need to bump the priority up.

Note to myself: do not backport https://github.com/longhorn/longhorn/issues/5845 until a resolution is confirmed.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `aef322`,  longhorn-engine `3d0e51`) with test [steps](https://github.com/longhorn/longhorn/issues/6522#issue-1850836623)

- Make restore volume degrade will not cause the volume restoration never complete now
- Related test case passed on master [pipeline](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/636/testReport/)
   - `test_single_replica_restore_failure`
   - `test_rebuild_with_inc_restoration`
   - `test_rebuild_with_restoration`
   - `test_dr_volume_with_restore_command_error`
   - `test_inc_restoration_with_multiple_rebuild_and_expansion`
