### ISSUE TITLE
[TASK] Remove namespaceOverride from the chart values

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6527]
## What's the task? Please describe

Remove namespaceOverride from the chart value, since we don't officially support it can be installed in a different namespace. Enforce this to avoid any incorrect expectation. 

```
## Specify override namespace, specifically this is useful for using longhorn as sub-chart
## and its release namespace is not the `longhorn-system`
namespaceOverride: ""
```

## Describe the sub-tasks

Need to review the impact when removing this value.

**Comment by roger-ryao** [comment]
**Verified on master-head 20231211**

- longhorn master-head https://github.com/longhorn/longhorn/commit/69739d8a63231934c5f7bb0c70619130be25fe23

**The test steps**

https://github.com/longhorn/longhorn/issues/6527#issuecomment-1844875954

**Result Passed**

- [x] 1. Successfully installed Longhorn.
- [x] 2. Successfully created `workloads`, `volumes`, `snapshots`, `backups`, and `system backup`.
- [x] 3. Successfully upgraded Longhorn from version `1.5.3` to `1.6.0-dev`.
- [x] 4. Successfully uninstalled Longhorn.
- [x] 5. [helm-chart-coretest](https://ci.longhorn.io/job/private/job/longhorn-helm-chart-test/10/) passed

**Comment by mantissahz** [comment]
>Harvester needs the field to install LH in longhorn-system. Without it, LH will be in harvester-system . The root cause is that helm can't specify dependence chart in a different namespace, so we need a way to change it. ([ref](https://github.com/helm/helm/issues/10905))

Reopen this issue and add the field back.

cc @FrankYang0529

**Comment by innobead** [comment]
Marked this issue as invalid, as we decided to revert the previous change.

**Comment by roger-ryao** [comment]
**Verified on master-head/v1.6.x-head 20240125**
- longhorn `master-head` https://github.com/longhorn/longhorn/commit/c3a9f120e30287d5ba1b954a0227f637309dff81

- longhorn `v1.6.x-head` https://github.com/longhorn/longhorn/commit/b34b8735e0c98daa9e4d200d3f17c5cb6056e1f3

**The test steps**

https://github.com/longhorn/longhorn/issues/6527#issuecomment-1844875954


**Result Passed**

- [x] 1. Successfully installed Longhorn.
- [x] 2. Successfully created `workloads`, `volumes`, `snapshots`, `backups`, and `system backup`.
- [x] 3. Successfully upgraded Longhorn from version `1.5.3` to `1.6.x-head`.
- [x] 4. Successfully upgraded Longhorn from version `1.5.3` to `master-head`.
- [x] 5. Successfully uninstalled Longhorn.
- [x] 6. [master-head helm-chart-coretest](https://ci.longhorn.io/job/private/job/longhorn-helm-chart-test/14/) passed
- [x] 7. [1.6.x-head helm-chart-coretest](https://ci.longhorn.io/job/private/job/longhorn-helm-chart-test/15/) passed
- [x] 8. `require_doc` : The documentation is available at  [README.md](https://github.com/longhorn/longhorn/blob/master/chart/README.md?plain=1#L3)
