### ISSUE TITLE
[FEATURE] Have default priorityClass to prevent unexpected longhorn pods eviction

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6528]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Have a default priority class with the highest value to ensure longhorn pods have not been evicted when low system resources by the Kube scheduler.  Right now, the setting is optional.

https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/

## Additional context

cc @longhorn/dev

**Comment by harridu** [comment]
Will existing deployments be migrated to the new default priority class on the fly? I am not sure if this is possible.

**Comment by innobead** [comment]
> Will existing deployments be migrated to the new default priority class on the fly? I am not sure if this is possible.

In the current implementation, it's not possible. However, we should improve this part to have the following support to prevent any interruption for running volumes.

- When changing any volume-related Pod configuration (ex: IM pod, share manager pod, upcoming object storage/s3gw pod) like priority class, the change will only take effect when doing volume upgrade or volume reattachement. 

Extra info from @PhanLe1010 

![image](https://github.com/longhorn/longhorn/assets/899492/b34cb163-a8dc-401b-aafc-9c18e9efb057)

cc @shuo-wu @derekbit @c3y1huang

**Comment by chriscchien** [comment]
Verified **pass** on longhorn v1.6.0-rc1 with test [stpes](https://github.com/longhorn/longhorn/issues/6528#issuecomment-1840847320)

After install v1.6.0-rc1, can see priority class `longhorn-critical`  in all longhorn pods
```
> k get priorityclass
NAME                      VALUE        GLOBAL-DEFAULT   AGE
system-node-critical      2000001000   false            8m54s
system-cluster-critical   2000000000   false            8m54s
longhorn-critical         1000000000   false            8m4s
> k get setting -n longhorn-system | grep priority
priority-class                                                    longhorn-critical                                 8m4s
```
