### ISSUE TITLE
manage: Remove timeout in the time consuming engine command

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#653]
Backup, restore, backup remove, rebuild, snapshot purge shouldn't have a timeout in the manager.

**Comment by yasker** [comment]
Timeout for backup deletion removed by https://github.com/longhorn/longhorn-manager/pull/357

**Comment by yasker** [comment]
Wait for https://github.com/longhorn/longhorn/issues/644

**Comment by yasker** [comment]
@meldafrawi Old timeouts:
1. Purge (snapshot deletion): 15 minutes
2. Backup: 6 hours.
3. Rebuild: 3 hours.
4. Restoration: No limit, make sure it stays that way.

Best way to simulate purge is to create a few big snapshots, then use Longhorn command line to mark the snapshot as removed, then create a new snapshot in the UI, then delete it. The last step will trigger `snapshot purge` in Longhorn manager.

**Comment by meldafrawi** [comment]
Validation: **WIP**

Steps to test:

  (1) backup
  - In `Settings` page, make sure that backup target is correctly configured.
  - Create a volume with large size ~ 200 GB, attach it to a node, format it, mount it to a directory on attached node.
  - Write a large data file that consumes all/most of volume size ~198 GB
  - In `Volume Details` page, create a backup.
  >> Expected result: backup expected to take more than 6 hours (old backup timeout), and should continue progressing after that.
