### ISSUE TITLE
[IMPROVEMENT] Expose EngineImage CLIAPIVersion and ControllerAPIVersion

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#6531]
## What's the task? Please describe

After [engine upgrade enforcement](https://github.com/longhorn/longhorn/issues/5842) is introduced, Longhorn will prevent upgrades if there are existing incompatible engine images actively used by the engine.

For the helm upgrade, the incompatible versions are checked and blocked by the pre-hook. However, for users installed using the manifest, the block is done by the longhorn-manager, and reflected in the unsuccessful pod launch and in the pod error log. When such an error is encountered, users will be required to revert to the previous version and subsequently upgrade any engine currently utilizing the incompatible engine image. Ref: https://github.com/longhorn/longhorn/pull/6519#issuecomment-1679943473

To allow the user to self-check the compatibility, we need to expose the EngineImage `CLIAPIVersion` and `ControllerAPIVersion` so the user can check against the compatible version before upgrading Longhorn.

```bash
> curl http://10.0.1.119:30495/v1/engineimages/ei-74783864 | jq
{
  "actions": {},
  "buildDate": "2023-07-19T05:05:37+00:00",
  "cliAPIMinVersion": 3,
  "cliAPIVersion": 8,
  "conditions": [
    {
      "lastProbeTime": "",
      "lastTransitionTime": "2023-08-17T02:55:17Z",
      "message": "Engine image ei-74783864 (longhornio/longhorn-engine:v1.5.1) is fully deployed on all ready nodes",
      "reason": "",
      "status": "True",
      "type": "ready"
    }
  ],
  "controllerAPIMinVersion": 3,
  "controllerAPIVersion": 4,
  "dataFormatMinVersion": 1,
  "dataFormatVersion": 1,
  "default": false,
  "gitCommit": "0d8e42d0c74b1d0430e56efa1e8247c55f34cef3",
  "id": "ei-74783864",
  "image": "longhornio/longhorn-engine:v1.5.1",
  "links": {
    "self": "http://10.0.1.119:30495/v1/engineimages/ei-74783864"
  },
  "name": "ei-74783864",
  "noRefSince": "",
  "nodeDeploymentMap": {
    "ip-10-0-2-151": true,
    "ip-10-0-2-20": true,
    "ip-10-0-2-212": true
  },
  "ownerID": "ip-10-0-2-151",
  "refCount": 10,
  "state": "deployed",
  "type": "engineImage",
  "version": "v1.5.1"
}
```

## Describe the sub-tasks

`None`

## Additional context

https://github.com/longhorn/longhorn/pull/6519#issuecomment-1679951867

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-ui/commit/a31fc59cf025079be6b065804c6e084a6afd5d66)

`EngineImage CLIAPIVersion` and `ControllerAPIVersion` exposed correctly in UI

- mater-head engine image
![image](https://github.com/user-attachments/assets/bf840fb4-912b-4921-839d-ff0ac4efe8fc)


- v1.7.2 engine image
![image](https://github.com/user-attachments/assets/0e1b84f4-e1c8-4ac0-ad79-d820661d63b6)

-  Incompatible version
![image](https://github.com/user-attachments/assets/db877678-0a49-48bc-9c2e-d680e999a88c)
