### ISSUE TITLE
manager: allow user to adjust replica count even if the volume is not healthy

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#654]
It can be used as a workaround in some cases.

**Comment by meldafrawi** [comment]
Validation: PASSED

Steps to test:
  - In `Settings` page, **uncheck** `Replica Soft Anti-Affinity`
  - For k8s cluster with **n** longhorn schedulable nodes, create a volume with 
number of replicas = **n - 1**
  - Attach the volume to a node
  >> Expected result: volume state should be healthy.
  - In `Volume` page, from drop down menu on the right click on `Update Replica Count`, set the number of replicas equal to **n + 1**
   >> Expected result: volume state should be degraded.
  - In `Volume` page, from drop down menu on the right click on `Update Replica Count`, set the number of replicas equal to **n**
  - In `Volume Detail` page, delete the replica that failed to be scheduled.
 >> Expected result: volume state should go be to healthy.
