### ISSUE TITLE
[IMPROVEMENT] Include /var/log/messages during the support-bundle syslog collection

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#6544]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Currently, the support bundle only collects [syslog from /var/log/syslog](https://github.com/rancher/support-bundle-kit/blob/v0.0.26/hack/collector-longhorn#L27). However, different Linux distributions use different syslog daemons, which store log messages in different locations. The common locations are `/var/log/syslog` (e.g Ubuntu) and `/var/log/messages` (e.g SUSE). We should include syslog collection from /var/log/messages as well.

## Describe the solution you'd like

Include /var/log/messages during the support-bundle syslog collection.

## Describe alternatives you've considered

`None`

## Additional context

`None`

**Comment by c3y1huang** [comment]
@innobead I've added this to the v1.6.0 milestone since this is a small effort and could be done with https://github.com/longhorn/longhorn/issues/6338.

**Comment by roger-ryao** [comment]
**Verified on master-head 20230831**

- longhorn master-head https://github.com/longhorn/longhorn/commit/67b4b38a1222d441f528907dcfbc89c4a6ce08d5

**Result Passed**

After generating the support bundle, we can obtain the `/var/log/syslog` from the `Ubuntu` cluster and `/var/log/messages` from the `SLE` cluster.
