### ISSUE TITLE
instance manager: need a way to run longhorn engine command manually

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#655]
We need a way to run Longhorn engine command for individual volume while using the instance manager since it will help a lot on debugging the problem.

**Comment by shuo-wu** [comment]
Steps to run longhorn engine cmd manually:

1. Use `kubectl -n longhorn-system get lhe <engine-name> -o yaml`. Find engine process port in `status.port` and related instance manager in `status.instanceManagerName`.
2. Use `kubectl -n longhorn-system exec -it <instance-manager-name> bash` to enter instance manager pod.
3. Run longhorn engine cmd `longhorn --url localhost:<engine-process-port> ...`

**Comment by yasker** [comment]
Can we have a script or something easier to do this? It's way more complex than what we did before, which is `kubectl -n longhorn-system exec -it <volume-name>-e-<xxx> longhorn <cmd>`.

**Comment by meldafrawi** [comment]
Validation: **FAILED**

Steps to test:
  - Create a volume with `volume-test-01`, attach it to a node.
  - Use script `longhorn-engine-exec`, found in `https://github.com/longhorn/longhorn-manager/blob/master/deploy/scripts/longhorn-engine-exec` to execute longhorn command on `volume-test-01` with the correct number of parameters.
  >> Expected Result: script should detect volume instance manager instance and execute the specified command against it.

  - Use the script to execute longhorn command on `volume-test-01` with no arguments.
  >> Expected Result: script should output help message.

  - Use the script to execute longhorn command on `volume-test-01` with wrong number of arguments or wrong longhorn commands.
    >> Expected Result: script should output error message, instructs the use to run help message.

  - Use the script to execute longhorn command on non existing volume
  >> Expected Result: script should output error message, state the volume doesn't exist.

   - Script should not output the help message with every command execution **FAILED:**

**Comment by meldafrawi** [comment]
Validation: **FAILED**

Steps to reproduce:
  - Create a volume `volume-test` , DON'T attach it to a node.
  - execute `longhorn-engine-exec  volume-test snapshot list`
  >> Expected Result: script should handle the case if the volume is not attached.

  >> Actual Result:  
```
USAGE:
  # Must have Longhorn installed in "longhorn-system" namespace and have access to "kubectl" and the namespace
  ./longhorn-engine-exec [volume-name] [longhorn-command-args]

EXAMPLE:
  ./longhorn-engine-exec test-vol snapshot ls
  ./longhorn-engine-exec test-vol info

"longhorn" command output: 

Error from server (NotFound): pods "\"\"" not found

```

**Comment by meldafrawi** [comment]
Validation: **PASSED**
