### ISSUE TITLE
manager/UI: Show the status of instance managers

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#657]
We've added the instance manager as a part of Longhorn deployment now, but currently, there is no way to know if the instance manager is ready to serve. 

We can add a field in the node status: Readiness: Ready, Deploying. 

Ready means all the existing (compatible) engine images have been deployed on the node and instance manager of the related engine images are running.

Otherwise, it's deploying.

From UI, click `Readiness` column of the node to see a matrix of engine images and engine instance manager/replica instance manager to see which one is not ready. We can also show the readiness of the deployed engine image here.

E.g. it can look like this for one node:

| Engine  	| Engine Image 	| Instance Manager - Engine 	| Instance Manager - Replica 	|
|---------	|--------------	|---------------------------	|----------------------------	|
| v0.6.0  	| Ready        	| Running                   	| Starting                   	|
| v0.5.0  	| Incompatible 	| Unknown                   	| Unknown                    	|

In order for this to work, we need to expose the status of Instance Manager.

**Comment by yasker** [comment]
Backend merged at https://github.com/longhorn/longhorn-manager/pull/370

**Comment by yasker** [comment]
@smallteeths Now the backend shows up the `managerType` to be `replica` or `engine`.

UI needs to read from `InstanceManager` list and `EngineImage` list. The engine name will be used to match the two.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
  - Longhorn (master):
    - On `Settings/Engine Image` page, Click "Deploy New Image", Enter `longhornio/longhorn-engine:v0.5.0`
    - On `Node` page, `Readiness` column
    >> Expected Result:
    >> (1) Instance Manager State should be `Ready`
    >> (2) Clicking on Instance Manager State, a matrix of engine images and engine instance manager/replica should appear and should contain the following:

| Engine | Engine Image | Instance Manager - Engine | Instance Manager - Replica |
-- | -- | -- | --
| longhornio/longhorn-engine:v0.5.0 | Incompatible | Unknown | Unknown
| longhornio/longhorn-engine:master | ready | running | running

>> (3) If an instance manager engine/replica pod is not yet ready, its status should be `starting`
