### ISSUE TITLE
[REFACTOR] Abstract the disk/lvol file operations in backupstore

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6576]
## What's the task? Please describe

This is a subtask of #6138 

The backup store will serve the purpose of backing up and restoring both v1 and v2 volumes. File operations, such as [seek](https://github.com/longhorn/backupstore/blob/master/deltablock.go#L781), [create](https://github.com/longhorn/backupstore/blob/master/deltablock.go#L845C20-L845C26) and so on, for v1 volumes are conducted on sparse files. In contrast, disks files are represented as SPDK logical volumes. An abstraction for disk and logical volume (lvol) file operations is necessary.

**Comment by innobead** [comment]
@derekbit is there anything QA can test here? It seems backupstore refactored, so could run e2e tests related to backup & restore including system. WDYT?

**Comment by derekbit** [comment]
Yes. I think e2e is enough.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-engine `014125`,  backupstore `627369`)

E2e pipeline did not observe outstanding issue related to backup after the backupstore refactored.
- AMD64 build [745](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/745/#showFailuresLink) : 3 failures
- AMD64 upgrade build [678](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/678/#showFailuresLink) : 3 failures
- AMD64 2 stage upgrade build [377](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-2-stage-upgrade-tests-sles-amd64/377/#showFailuresLink) : 5 failures
- ARM64 build [692](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/692/#showFailuresLink) : 5 failures
- ARM64 upgrade build [684](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-upgrade-tests-sles-arm64/684/#showFailuresLink) : 3 failures
- ARM64 2 stage upgrade build [370](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-2-stage-upgrade-tests-sles-arm64/370/#showFailuresLink) : 6 failures

For the failures, most of them already recorded in https://github.com/longhorn/longhorn/issues/6659
