### ISSUE TITLE
[QUESTION] How to fix "Not ready for workload. Volume may be under maintenance or in the restore process."

### ISSUE THREAD

**Issue by ysicing** [longhorn/longhorn#6588]
## Environment

 - Longhorn version: 1.5.1
 - Kubernetes version: v1.24.12+k3s1
 - Node config
   - OS type and version  Rocky Linux 9.1 (Blue Onyx)      
   - Kernel version 6.2.11-1.el9.elrepo.x86_64
   - CPU per node: 12
   - Memory per node: 32g
   - Disk type SSD
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

## Additional context

Failed to mount the pvc during gitea upgrade.

```
msg="Device /dev/mapper/pvc-28fa9bea-20e7-453a-aef4-bd885b293015 is not an active LUKS device" error="failed to run cryptsetup args: [status pvc-28fa9bea-20e7-453a-aef4-bd885b293015] output:  error: exit status 4"
```

ui notice： Not ready for workload. Volume may be under maintenance or in the restore process.

pvc：

```
Name:          gitea-20230330134830-data-block
Namespace:     default
StorageClass:  longhorn
Status:        Bound
Volume:        pvc-28fa9bea-20e7-453a-aef4-bd885b293015
Labels:        release=gitea-20230330134830
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
               volume.kubernetes.io/storage-provisioner: driver.longhorn.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      100Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       <none>
Events:        <none>
```

**Comment by ysicing** [comment]
@derekbit  Hello, I've encountered this issue. How can I completely resolve it? I restarted the deploy, and then this message appeared.
![image](https://github.com/user-attachments/assets/46811714-7c86-4740-ac2b-025da0ee9583)

I tried the manual Force Detach operation, but it was not successful.

**Comment by ChanYiLin** [comment]
Hi @ysicing 
Can you provide more details 
A support bundle would be helpful.

From the message
"Device /dev/mapper/pvc-28fa9bea-20e7-453a-aef4-bd885b293015 is not an active LUKS device"
Are you trying to use encrypted volume?
Have you set the secret.
You can follow the example to use encrypted volume
https://longhorn.io/docs/1.7.2/advanced-resources/security/volume-encryption/
