### ISSUE TITLE
[IMPROVEMENT] UI backup restoration supports v1 and v2 `Data Engine`

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6597]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Currently, the backup restoration on UI page only supports v1. The v2 volume backup and restoration will be implemented in https://github.com/longhorn/longhorn/issues/6138, This enhancement will allow the inclusion of the Data Engine on the page, empowering users with the option to select either v1 or v2 as per their preference.

![image](https://github.com/longhorn/longhorn/assets/12527233/76bfa7fd-c1c2-4d20-8e2d-89528e5e6edb)

**Comment by roger-ryao** [comment]
**Verified on master-head 20240108**

- longhorn master-head https://github.com/longhorn/longhorn/commit/38fa709ec8476215cf938e9768b4ae67fac9e383
- longhorn-manager master-head https://github.com/longhorn/longhorn-ui/commit/95407604b815c6cd266bd0b1b77de14122794a6f


**The test steps**

1. https://github.com/longhorn/longhorn/issues/6597#issue-1868823309

**Result**


![Screenshot_20240108_155148](https://github.com/longhorn/longhorn/assets/104337648/5f029f30-fa37-48c4-87a4-af75cb65b301)

- [x] The UI on the master branch includes the `Data Engine` option for `v1` or `v2`.
- [ ] require/doc : https://github.com/longhorn/longhorn/pull/6480
    - We only see LEP PR on the tickets  https://github.com/longhorn/longhorn/issues/6138 & https://github.com/longhorn/longhorn/issues/7361. 
    - **For this feature, we may need to make a note on https://longhorn.io/docs/1.6.0/spdk/features/**
cc @derekbit

**Comment by derekbit** [comment]
Doc updated: https://github.com/longhorn/website/pull/836
