### ISSUE TITLE
[BUG] mount volume with rwx mode, frequent error output "kernel: nfs: Deprecated parameter 'intr'"

### ISSUE THREAD

**Issue by ming12713** [longhorn/longhorn#6599]
## Describe the bug (🐛 if you encounter this issue)
Mounting RWX (Read-Write-Many) volumes is causing frequent errors and often leading to restarts of the baremeta nodes where the pods with the mounts are located.

![Screenshot from 2023-08-28 10-42-19](https://github.com/longhorn/longhorn/assets/5196113/b10e546e-1679-4f08-ae9d-c6dbed1cf33b)
In the scenario, multiple (10-50) pods are simultaneously mounting RWX (Read-Write-Many) volumes as part of Airflow tasks. After running for 3-10 minutes, the tasks complete, and there's a bulk unmounting of volumes. This involves a significant number of mounting and unmounting operations.

Env
longhorn: v1.5.0
kube node : ubuntu 22.04
kubernetes: v1.26.6
Related issue:  https://github.com/longhorn/longhorn/issues/6570

**Comment by derekbit** [comment]
How do you know the node restarts were caused by mounting RWX volumes?

**Comment by ming12713** [comment]
> How do you know the node restarts were caused by mounting RWX volumes?

@derekbit 
i use kdump capature logs,  discovered that system restart are being caused by Calico` netatop exception  RIP　kmem_cache_alloc `. However, it's uncertain whether this issue is related to NFS. In tests where NFS 'rwx' volumes are not mounted, even with a significantly higher number of Airflow tasks, hang-ups or reboots do not occur. 
have you encountered such this issues before?
![Screenshot from 2023-08-30 11-22-50](https://github.com/longhorn/longhorn/assets/5196113/43a3a486-3e42-4cbd-b59e-fc7f57ffebab)

[dmesg.202308292304.txt](https://github.com/longhorn/longhorn/files/12471408/dmesg.202308292304.txt)

**Comment by derekbit** [comment]
It seems like a kernel bug, but I didn't see similar issues before.

**Comment by ming12713** [comment]
> It seems like a kernel bug, but I didn't see similar issues before.
ok,thanks. I'm looking to see if there are any other solutions available.

**Comment by ming12713** [comment]
@derekbit 
Is there a limitation on the number of mounted clients for the 'sharemanager rwx' volume?

**Comment by helletheone** [comment]
we have the same case. Is there any solutions for that?

**Comment by Isotop7** [comment]
> we have the same case. Is there any solutions for that?

Which kernel and OS are you using?

**Comment by derekbit** [comment]
The mount option `intr` is deprecated in newer kernels, but it is a warning message and doesn't lead to any error.
We can consider removing the mount option. cc @james-munson

**Comment by derekbit** [comment]
> @derekbit Is there a limitation on the number of mounted clients for the 'sharemanager rwx' volume?

Sorry, I missed the question.
Currently, we didn't have a number for the question. It depends on the CPU and memory consumptions of your workloads to the volumes.

**Comment by leadersnowy** [comment]
I got this question too.
ENV
Ubuntu 22.04 
kernel version 5.15.0-97

**Comment by leadersnowy** [comment]
I got this question too.
ENV
Longhorn 1.5.1
Ubuntu 22.04 
kernel version 5.15.0-97

**Comment by james-munson** [comment]
The `Protocol not supported` symptom on RWX pod mount failure is covered in #6857 (as mentioned above) and #7931.
Both Ubuntu kernels `5.15.0-94` and `5.15.0-97` have been seen to have the issue, and downgrading to `5.15.0-92` or upgrading to `5.15.0-100` or later seems to cure it.

**Comment by james-munson** [comment]
Also, the symptom tied to `Protocol not supported` kernel issue is simply a failure to mount the RWX volume on a workload pod, not the reboot of a cluster node.

**Comment by james-munson** [comment]
The calico issue itself was resolved in this issue: https://github.com/projectcalico/calico/issues/7974

Is there a reason not to close this one?

**Comment by ming12713** [comment]
> The calico issue itself was resolved in this issue: [projectcalico/calico#7974](https://github.com/projectcalico/calico/issues/7974)
> 
> Is there a reason not to close this one?
@james-munson  Thank you for your response. I don't check my email often
