### ISSUE TITLE
[TASK] Implement xattr get and set operations on SPDK logical volumes (lvol)

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6604]
## What's the task? Please describe

This is a subtask of https://github.com/longhorn/longhorn/issues/6138

Metadata such as a creation timestamp of a v1 volume are stored in a disk's meta file. For a v2 volume, we can store these information in the blob xattr instead.

**Comment by innobead** [comment]
This is a partial effort in v2. No QA is required until the v2 regression testing later.
