### ISSUE TITLE
[TASK] Investigate SPDK lvstore cluster size

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6612]
## What's the task? Please describe

Our current implementation uses a lvstore cluster size of 1 MiB. This may affect the IO performance when a volume has multiple snapshots. The task is to study how different cluster sizes influence the performance and tradeoffs.

With the results, we can optimize the lvstore cluster size configuration or provide a flexible setting for users to choose the cluster size for ~~each volume~~ each disk or for all volumes.

## Additional context

cc @shuo-wu @DamiaSan @james-munson

**Comment by DamiaSan** [comment]
Lvstore cluster size is 4MiB
https://github.com/longhorn/spdk/blob/4542f9b14010fc7192d42e05adaafc2ae863bac5/include/spdk_internal/lvolstore.h#L17

```
/* Default size of blobstore cluster */
#define SPDK_LVS_OPTS_CLUSTER_SZ (4 * 1024 * 1024)
```

Cluster size is the same for whole lvstore, how can you set a different cluster size for each volume?

**Comment by derekbit** [comment]
Oh, sorry

> Lvstore cluster size is 4MiB https://github.com/longhorn/spdk/blob/4542f9b14010fc7192d42e05adaafc2ae863bac5/include/spdk_internal/lvolstore.h#L17
> 
> ```
> /* Default size of blobstore cluster */
> #define SPDK_LVS_OPTS_CLUSTER_SZ (4 * 1024 * 1024)
> ```
> 
> Cluster size is the same for whole lvstore, how can you set a different cluster size for each volume?

Per-disk not per-volume.
