### ISSUE TITLE
UI: The detach button of standby volume should be removed

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#662]
Once a DR volume is attached, the only way to detach it is to activate it.

**Comment by meldafrawi** [comment]
Validation: **WIP**

> Requirements: 2 clusters A & B, with longhorn installed.

Steps to test:
  - Ensure that backup target is configured correctly on clusters A & B and points to the same backup target.
  - On Cluster A:
    - Create a volume, attach it to a node
    - In `Volume Details` page, create a backup.
  - On cluster B:
    - In `Backup` page, from drop down menu click `Create Disaster Recovery Volume`, wait until volume be in healthy state. 
    >> Expected result:
       (1) In `Volume` page, when selecting the volume, `detach` button should be deactivated.
       (2) In `Volume Details` page, upper right drop down menu, `detach` button should be deactivated.
