### ISSUE TITLE
[BUG] Invalid Helm default setting value in Longhorn v1.5.1

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#6620]
## Describe the bug (🐛 if you encounter this issue)

Starting from Longhorn v1.5.0, we moved the setting `guaranteedEngineManagerCPU` and `guaranteedReplicaManagerCPU`. However, the helm chart value still reference it https://github.com/longhorn/longhorn/blob/9e40b9db5d2c4f33bb80d8cc314ffe01dadd4a8c/chart/values.yaml#L151-L152C3

If the user accidentally set this value when installing Longhorn v1.5.x using helm, it will render all the whole defaultSettings file to be invalid . Therefore, Longhorn manager will ignore all settings (both valid and invalid ones)

## To Reproduce

1. Install Longhorn v1.5.x using Helm with this helm value file:
```
defaultSettings:
  defaultReplicaCount: 1
  guaranteedEngineManagerCPU: 20
  guaranteedReplicaManagerCPU: 50
```

2. See that both valid setting (`defaultReplicaCount`) and invalid settings (`guaranteedEngineManagerCPU`, `guaranteedReplicaManagerCPU`) are ignored 

## Expected behavior

Remove the invalid setting from helm chart

## Environment

 - Longhorn version: v1.5.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm

**Comment by c3y1huang** [comment]
Duplicated to https://github.com/longhorn/longhorn/issues/6465
