### ISSUE TITLE
[BUG] 1.5.0 and 1.5.1 longhorn-pre-upgrade Job fails due to missing ServiceAccount

### ISSUE THREAD

**Issue by theNewFlesh** [longhorn/longhorn#6623]
When deploying Longhorn via Helm on ArgoCD, sync fails because the longhorn-pre-upgrade Job tryies to run before the Longhorn ServiceAccount is created,

## To Reproduce

Deploy Longhorn Helm chart 1.5.0 or 1.5.1 via ArgoCD 2.8.2, with default values.

## Expected behavior

Longhorn 1.4.3 deploys with default values just fine.

## Environment

 - Longhorn version: 1.5.0, 1.5.1
 - Installation method ArgoCD Helm app
 - Kubernetes distro and version: MIcroK8s v1.27.4 revision 5643 
   - Number of management node in the cluster:
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 22.04.3 LTS
   - Kernel version: 5.15.0-79-generic
   - CPU per node: 4
   - Memory per node: 66
   - Disk type: NVMe
   - Network bandwidth between the nodes: 1 Gbps
 - Underlying Infrastructure: Baremetal
 - Number of Longhorn volumes in the cluster: 0

## Additional context
Helm deployment of Longhorn 1.5.1 appeared to have worked normally,

Adding these annotations to ServiceAccount should control the order ArgoCD deploys it in. Instead the ServiceAccount never showed up.

```
serviceAccount:
    annotations:
        argocd.argoproj.io/hook: Sync
        argocd.argoproj.io/sync-wave: "-1"
```
See https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/

**Comment by lolhax1337** [comment]
Same bug when using ArgoCD 2.7.11 and trying to deploy longhorn 1.5.1

**Comment by innobead** [comment]
cc @mantissahz

**Comment by tabnul** [comment]
same issue here, argocd 2.8, longhorn 1.5.1
fixed it by temporarily removing the pre-sync job , syncing, and re-adding it.
this is of course a no-go and blocks automation, but this is my home setup.

**Comment by mantissahz** [comment]
It's related to https://github.com/longhorn/longhorn/issues/6415
we will have an improvement by disabling the `pre-upgrade` hook for Argocd

> fixed it by temporarily removing the pre-sync job , syncing, and re-adding it.

@tabnul  thanks for this workaround.

**Comment by c3y1huang** [comment]
Track in https://github.com/longhorn/longhorn/issues/6415.

**Comment by mrclrchtr** [comment]
> same issue here, argocd 2.8, longhorn 1.5.1 fixed it by temporarily removing the pre-sync job , syncing, and re-adding it. this is of course a no-go and blocks automation, but this is my home setup.

@tabnul Could you tell me, how to remove it?

**Comment by PatrykPetryszen** [comment]
Are you able to pass this value from values when using wrapper? Seems it doesn't work for me. Thread:
https://www.reddit.com/r/ArgoCD/comments/1pqnajg/help_with_longhorn_deployment/
