### ISSUE TITLE
[BUG] Somehow the Rebuilding field inside volume.meta is set to true when one replica only, causing the volume into attaching/detaching loop 

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6626]
## Describe the bug (🐛 if you encounter this issue)

A duplicate of #4212 , but this issue is for the volume which has only one replica. 

https://github.com/longhorn/longhorn/issues/4212#issuecomment-1643456399
https://github.com/longhorn/longhorn/issues/4212#issuecomment-1560296082 (partially fixed) 

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
cc @derekbit

**Comment by innobead** [comment]
@james-munson Please help with this.

**Comment by c3y1huang** [comment]
Note:
The loop logs seem to be consistent.

```
2022-06-18T04:06:15.804771972Z [pvc-126d40e2-7bff-4679-a310-e444e84df267-e-f7e3192f] time="2022-06-18T04:06:15Z" level=info msg="Starting with replicas [\"tcp://10.42.13.251:10045\"]"
2022-06-18T04:06:15.808512632Z [pvc-126d40e2-7bff-4679-a310-e444e84df267-e-f7e3192f] time="2022-06-18T04:06:15Z" level=info msg="Opening: 10.42.13.251:10045"
```
The `Opening` log indicates that the replica's state is "closed" at this time because the function [checks the state](https://github.com/longhorn/longhorn-engine/blob/v1.2.4/pkg/backend/remote/remote.go#L263-L265) before invoking the [r.open](https://github.com/longhorn/longhorn-engine/blob/v1.2.4/pkg/backend/remote/remote.go#L275) operation.

```
2022-06-18T04:06:15.816136779Z [pvc-126d40e2-7bff-4679-a310-e444e84df267-e-f7e3192f] time="2022-06-18T04:06:15Z" level=info msg="Adding backend: tcp://10.42.13.251:10045"
2022-06-18T04:06:15.818154111Z [pvc-126d40e2-7bff-4679-a310-e444e84df267-e-f7e3192f] time="2022-06-18T04:06:15Z" level=info msg="Start monitoring tcp://10.42.13.251:10045"
2022-06-18T04:06:15.819866618Z [pvc-126d40e2-7bff-4679-a310-e444e84df267-e-f7e3192f] 2022/06/18 04:06:15 Invalid state rebuilding for getting revision counter
```
In that very same second, the replica is then interpreted as being in a [state of "rebuilding"](https://github.com/longhorn/longhorn-engine/blob/v1.2.4/pkg/backend/remote/remote.go#L219).

**Comment by c3y1huang** [comment]
I am unable to reproduce this issue.

However, given that we know [where it crashed](b42224518443d4134e5b7509cf7c6659e1441adf), we can try to replicate the behavior by patching longhorn-engine and updating to the longhorn-instance-manager.
```
diff --git a/pkg/sync/sync.go b/pkg/sync/sync.go
index b48ddd46..c4523f11 100644
--- a/pkg/sync/sync.go
+++ b/pkg/sync/sync.go
@@ -534,9 +534,9 @@ func (t *Task) reloadAndVerify(address, instanceName string, repClient *replicaC
                return err
        }
 
-       if err := repClient.SetRebuilding(false); err != nil {
-               return err
-       }
+       // if err := repClient.SetRebuilding(false); err != nil {
+       //      return err
+       // }
        return nil
 }
```

Patched images:
- engine-image: c3y1huang/research:2030-lh-ei
- instance-manager-image: c3y1huang/research:195-lh-im

To simulate the issue:
1. Update the settings:
   - `Data locality`: `disabled`
   - `Auto salvage`: `true`
1. Create a StorageClass:
   - `NumberOfReplicas`: `1`
1. Create a StatefulSet:
   - `Replicas`: `1`
1. Ensure that the node of the Pod and the node of the Replica are different. This is necessary to trigger the rebuilding in response to the data locality setting.
1. Write some data to the volume.
1. Update the setting to set `data locality` to `best-effort`.
1. Wait for the rebuild to start and complete.
1. Check the `volume.meta` file, Rebuilding should be true.
1. Delete the instance manager pod of the Replica.
1. Then should observe loops of error related to `invalid state rebuilding`.

The patch doesn't trigger the exact error, as it will not result in `Dirty` being set to `true` in the `volume.meta` file with the above steps. However, it should be sufficient for testing the fix.

**Comment by nitendra-suse** [comment]
Verified **pass** on longhorn master-07a87da  using    [steps](https://github.com/longhorn/longhorn-tests/pull/1550/files#diff-81f9aac4f6d934ec595c23359ea0077e573e3969329e63694caadb8669c5fffc)
