### ISSUE TITLE
UI: Setup CI

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#663]
Longhorn UI should have Drone enabled similar to Longhorn Manager and Longhorn Engine.

PR should enable building process.

The commits merged to master should automatically push the latest image to `longhornio/longhorn-ui:master`.

**Comment by yasker** [comment]
@cloudnautique PR CI cannot be enabled due to the number of repositories hits the limitation.

**Comment by yasker** [comment]
@drpebcak ^^

**Comment by drpebcak** [comment]
We are working through some issues with drone right now, and then we will be upgrading our drone installation to a newer version. That should resolve this!

**Comment by yasker** [comment]
Done.
