### ISSUE TITLE
[IMPROVEMENT] Replace `engineImage` field in CRDs with `image`

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6647]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

This is a subtask of https://github.com/longhorn/longhorn/issues/6001

v2 volumes use the instanceManagerImage instead of the engineImage concept.
In order to make the CRD more general, the task aims to replace the `engineImage` field in CRDs with `image`.

**Comment by derekbit** [comment]
e2e https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4904/

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn `cb61e9` longhorn-manager `a66539`)

- In Longhorn CR `volume`, `engine`, and `replica`, the field `spec.engineImage` has all become empty(""), and a new field `spec.image` has appeared with the value `longhornio/longhorn-engine:master-head`.
- In master head regression pipeline([AMD64](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/662/), [AMD64 2 stage upgrade](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-2-stage-upgrade-tests-sles-amd64/295/), [ARM64](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/612/), [ARM64 2 stage upgrade](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-2-stage-upgrade-tests-sles-arm64/289/#showFailuresLink)) did not observe cascading errors
