### ISSUE TITLE
longhorn-csi and instance-manager There is one more pod than the first, and it always displays 0/3

### ISSUE THREAD

**Issue by chunkushisan** [longhorn/longhorn#6649]
![e939a2f71e10943eee22e74b45df6a7](https://github.com/longhorn/longhorn/assets/118498980/9b6760f7-dee4-4cd8-8016-379a60bf5a41)
![438704d8a33a8098c60f871831154df](https://github.com/longhorn/longhorn/assets/118498980/25c1628e-33d1-45e4-a563-328d19131036)
![7a090733ddf845ed06a6202bf742fff](https://github.com/longhorn/longhorn/assets/118498980/06f1c848-c84a-4554-a6c9-ec23f763ec19)

**Comment by chunkushisan** [comment]
please help me

**Comment by ChanYiLin** [comment]
Can you `kubectl get po/XXX -n longhorn-system -oyaml`
to get the full information of the pod and paste it to here by using code block?
```
like this line
```
thanks!
