### ISSUE TITLE
Snapshot purge progress support

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#665]
In order to address https://github.com/longhorn/longhorn/issues/581 and provide better usability, we want to provide `snapshot purge` (snapshot rm from manager's POV) progress support.

1. Move the snapshot purge operation to the `sync agent server`.
2. Store the progress information in the sync agent server.
3. Report the progress using `longhorn snapshot purge-status` command.
4. Prevent multiple `snapshot purge` happens at the same time.

**Comment by yasker** [comment]
@smallteeths Backend merged.

**Comment by yasker** [comment]
@ttpcodes Can you document the API?

**Comment by ttpcodes** [comment]
I've already sent the API over Slack via DM.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
Create a volume with size 64 GB, attach it to a node, format it, and mount it to a directory on attached node.
Create a datafile with size 32 GB, and on Volume Detail page. create a snapshot
repeat previous step with volume sizes 16 GB & 8 GB
Use kubectl -n longhorn-system get lhe <engine-name> -o yaml Find engine process port in status.port and related instance manager in status.instanceManagerName
Use kubectl -n longhorn-system exec -it <instance-manager-name> bash to enter instance manager pod.
Run longhorn engine cmd longhorn --url localhost: snapshots`. Get snapshots IDs
Remove all snapshots using longhorn engine cmd longhorn --url localhost:<engine-process-port> snapshot rm <snapshot_id>
UI: on Volume Detail page. create a snapshot.
UI: on Volume Detail page. Delete last created snapshot.
>> Expected result: 
>>  - Purge progress should appear indicating if the purge process is completed.  
>>  - only one snapshot, the last one is shown in the system hidden.
