### ISSUE TITLE
[IMPROVEMENT] Environment setup and check tooling container

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6657]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Before installing Longhorn, users have to set up prerequisites and check the environment. The procedures are pretty handy and not friendly to uses. The purpose of this ticket is to integrate the environment setup and check procedures into a tool container and simplify the procedures.

**Comment by innobead** [comment]
Can be part of the story https://github.com/longhorn/longhorn/issues/5013.

**Comment by innobead** [comment]
@derekbit is this about preflight? If yes, refer to the PR here and update the status pipeline.

**Comment by derekbit** [comment]
@c3y1huang is working on tooling cli #7927
