### ISSUE TITLE
[BUG] cifs backup mount paths with dollar sign are not allowed

### ISSUE THREAD

**Issue by bakito** [longhorn/longhorn#6660]
## Describe the bug (🐛 if you encounter this issue)

Backup to hidden cifs share directories can not be configured, as the dollar sign is not allowed to be part of the path.
This is prevented by the longhorn-webhook-validator.

## To Reproduce

Create a hidden cifs share (with a dollar sign in the end of the share name) and use it as backup path for longhorn backups.

## Expected behavior

Cifs backup to hidden shares should be possible

## Environment
 - Longhorn version: 1.5.1
 - Installation method: Helm
 

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

**Comment by roger-ryao** [comment]
**Verified on master-head 20230913**

- longhorn master-head https://github.com/longhorn/longhorn/commit/9948983b15f7d82af44a45917c270313668c3b2c
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/a77b330ef8024b2f0eeb7d0341d1d3ba5b421e41


**The test steps**

1. Clone the Samba repository `git clone https://github.com/longhorn/samba.git`
2. Edit the `samba/start_samba.sh` file as follows:
```bash
index 6f641a3..064ff66 100755
--- a/start_samba.sh
+++ b/start_samba.sh
@@ -19,7 +19,7 @@ create_cifs_disk_image() {
 bootstrap_config() {
        echo "* Writing configuration"
 cat <<END >>/etc/samba/smb.conf
-[backupstore]
+[backupstore$]
```
3. Build the Samba image and push it to Docker Hub.`docker build -t samba .`
4. Edit the `https://github.com/longhorn/longhorn/blob/master/deploy/backupstores/cifs-backupstore.yaml` file as follows:
```bash
index 8ac586d..198e02a 100644
--- a/deploy/backupstores/cifs-backupstore.yaml
+++ b/deploy/backupstores/cifs-backupstore.yaml
@@ -40,7 +40,8 @@ spec:
         emptyDir: {}
       containers:
       - name: longhorn-test-cifs-container
-        image: derekbit/samba:latest
+        image: qazplo/samba:latest
         ports:
         - containerPort: 139
         - containerPort: 445
@@ -67,7 +68,7 @@ spec:
         volumeMounts:
         - name: cifs-volume
           mountPath: "/opt/backupstore"
-        args: ["-u", "$(CIFS_USERNAME);$(CIFS_PASSWORD)", "-s", "backupstore;$(EXPORT_PATH);yes;no;no;all;none"]
+        args: ["-u", "$(CIFS_USERNAME);$(CIFS_PASSWORD)", "-s", "backupstore$;$(EXPORT_PATH);yes;no;no;all;none"]
 ---
```
5. Deploy the CIFS service.
6. Set Backup Target to `cifs://longhorn-test-cifs-svc.default/backupstore$`
7. Set Backup Target Credential Secret to `cifs-secret`
8. test volume backup / restore

**Result Passed**

1. We can now set the Backup Target with `$` on `master-head`.
2. Volume backup and restore are working as expected.
