### ISSUE TITLE
[TASK] Develop a script to generate testing data

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#6665]
## What's the task? Please describe

 Develop a script to generate testing data based on following details. This will help speed up the manual testing, cover maximum kind of test data type. We can focus on thinking more cases including edge cases rather than spending time in data creation.

- Identify the types of data that you need to test your system. Like we have mentioned type of volume [here](https://github.com/longhorn/longhorn-tests/blob/master/qa_docs/testing_guidance.md#3-test-data-creation-to-test-the-feature).
e.g. Detached Volume, volume attached to pod, volume attached to a node, volume with backing image, encrypted volume, restored volume etc 
- Write data in these volume and get the md5sum as some report or log.
- We can have config file to set which all type of data we need.

**Comment by chriscchien** [comment]
Close this ticket as pull request merged.
