### ISSUE TITLE
[TASK] Update protoc to v24.3

### ISSUE THREAD

**Issue by FrankYang0529** [longhorn/longhorn#6666]
## What's the task? Please describe

The longhorn-engine uses [v3.18.0 protoc](https://github.com/longhorn/longhorn-engine/blob/8b4c80ab174b4f454a992ff998b6cb1041faf63d/Dockerfile.dapper#L7). The version was released in [Sep 2021](https://github.com/protocolbuffers/protobuf/releases/tag/v3.18.0) and it's not on [version support list](https://protobuf.dev/support/version-support/). It's good to update protoc to recently released version.

**Comment by innobead** [comment]
@FrankYang0529 Does backing image manager need to be updated?

**Comment by FrankYang0529** [comment]
> @FrankYang0529 Does backing image manager need to be updated?

Yeah, I miss it! And also share manager need to be updated.

* https://github.com/longhorn/backing-image-manager/tree/master/pkg/rpc
* https://github.com/longhorn/longhorn-share-manager/tree/master/pkg/rpc

**Comment by innobead** [comment]
@FrankYang0529 Don't forget https://github.com/longhorn/longhorn-spdk-engine

**Comment by innobead** [comment]
All merged.
