### ISSUE TITLE
[TEST] long-running cluster/nodes restart test to reproduce volume failure

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6667]
## What's the test to develop? Please describe

Users sometimes encounter volume attach-detach problem during node restart or cluster restart (not graceful).
For short term, we should have a dedicate cluster to rerun that to see if volume will not be stuck in attach-detach loop.

```
Users routinely restart the nodes or clusters, which often results in volume failure to attach and attaching/detaching loop.
One of the main reasons it happens so often is due to they weren't following the proper procedure in Longhorn doc to drain the node. It seems to result in the attaching problem. Though the problems seems slightly different every time.
However, after they improved the process to perform the proper drain, they claim they still see the failure to attach from time to time (they have a long-running QA cluster that's constantly performing rebooting to try to reproduce the problem).
```

We can consider all the restart cases (all nodes including control plane restart at a time, all worker nodes restart at a time, or worker nodes restart one by one), but they mentioned drain, so probably it should be one by one in this case.

We can repeat:
(1) have a deployment/statefulset workload dynamic provisioning with volumes (RWO and RWX) with 2 replicas, and with or without data locality
(2) IO intensive, keep writing into the volume
(3) reboot the node(s) or restart the whole cluster
(4) see if the volume is able to reattach on another node
(5) support bundle should be generated

## Additional context

* Run the test for 1.4.x first

* Need to consider pod eviction time in node reboot ( < pod eviction time or > pod eviction time) for deployment and statefulset

**Comment by yangchiu** [comment]
@innobead PR https://github.com/longhorn/longhorn-tests/pull/1526 can be merged to have IO intensive + single node reboot test case: 
https://github.com/longhorn/longhorn-tests/pull/1526/files#diff-cf5adc383e0fe295ca923eaaf3af8d6e67c539b5bfac6084c8aa4f1897c3f980

Or we can have modification based on that PR to have the required scenario.

**Comment by innobead** [comment]
Let me review the PR later.

**Comment by yangchiu** [comment]
And PR https://github.com/longhorn/longhorn-tests/pull/1526 is based on PR https://github.com/longhorn/longhorn-tests/pull/1520

So PR https://github.com/longhorn/longhorn-tests/pull/1520 should be merged first..

**Comment by yangchiu** [comment]
Operations need to be implemented:

- [X] restart cluster (all nodes including control plane)
- [ ] restart all worker nodes at a time
- [ ] restart worker nodes one by one
- [X] have deployment/statefulset workload dynamic provisioning with volumes (RWO and RWX)
- [ ] data locality disabled/enabled
- [X] IO intensive, keep writing into the volume

Working on `restart all worker nodes at a time`, `restart worker nodes one by one` and `data locality disabled/enabled` now.

**Comment by yangchiu** [comment]
Implementing `reboot volume node of workload` test cases now.
