### ISSUE TITLE
[BUG] Continuously auto-balancing replicas when zone does not have enough space

### ISSUE THREAD

**Issue by docbobo** [longhorn/longhorn#6671]
## Describe the bug (🐛 if you encounter this issue)

I currently have a somewhat unbalanced topology:

- Zone A: 4 instances
- Zone B: 4 instances
- Zone C: 1 instance

Replica Auto Balance is set to `best-effort`. 

At this moment I have multiple volumes alternating between 2xZone A, 1xZone B and 1xZone A, 2xZone B.

## To Reproduce

I believe the description is sufficient.

## Expected behavior

If even balancing isn't possible due to lack of available disk space, the current replica distribution should be kept stable instead of continuously copying data between nodes.

## Support bundle for troubleshooting

Will provide via email

## Environment

 - Longhorn version: 1.5.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): via ArgoCD based on Helm Chart.
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s 1.27.5
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 8
 - Node config
   - OS type and version: OpenSUSE MicroOS
   - Kernel version: 6.4.12
   - CPU per node: 4 Cores
   - Memory per node: 8GB
   - Disk type(e.g. SSD/NVMe/HDD): NVMe
   - Network bandwidth between the nodes: 1GBit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremental and KVM
 - Number of Longhorn volumes in the cluster: 42
 - Impacted Longhorn resources: 8
 -

**Comment by innobead** [comment]
cc @longhorn/qa this is related to resource exhaustion.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 27101bb) following https://github.com/longhorn/longhorn-tests/pull/1616.

Continuously replica auto-balancing can be observed in `v1.5.3`, but it remains stable in `master-head`.
