### ISSUE TITLE
Volumes are showing Replica Scheduling Failure

### ISSUE THREAD

**Issue by vr2388** [longhorn/longhorn#6678]
## Question
Volumes are showing **Replica Scheduling Failure**

## Environment

 - Longhorn version: 1.5.2
 - Kubernetes version: 1.26 and 1.27
 - Node config
   - OS type and version: ubuntu 22.04
   - Kernel version
   - CPU per node: 4core
   - Memory per node: 8GB
   - Disk type: 50GB
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

## Additional context

when i am deploying my app, I am getting **Replica Scheduling Failure** which is working fine with ubuntu 20.04 single-node and multi-node cluster and it is also working fine on ubuntu 22.04 singl-node cluster. But when i try same thing in ubuntu 22.04 multi-node cluster pvc are not attached to pods .

**Comment by james-munson** [comment]
Please capture a support bundle and attach it - that will be very helpful.

**Comment by vr2388** [comment]
In Longhorn ui i am getting this
<img width="1692" alt="image" src="https://github.com/longhorn/longhorn/assets/133762455/035fe082-ac75-4444-b200-e0f3059e533d">

pod events:

Events:
  Type     Reason                  Age                    From                     Message
  ----     ------                  ----                   ----                     -------
  Warning  FailedScheduling        8m55s                  default-scheduler        0/2 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod..
  Warning  FailedScheduling        8m54s                  default-scheduler        0/2 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod..
  Normal   Scheduled               8m52s                  default-scheduler        Successfully assigned default/nextgen-gw-0 to node2
  Normal   SuccessfulAttachVolume  8m42s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-91825c7a-fe95-412a-9f04-a29972f20cd2"
  Normal   SuccessfulAttachVolume  8m41s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-93b813f0-056d-449a-9255-455d6d88e058"
  Normal   SuccessfulAttachVolume  8m41s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-87cbbc6e-09de-4e01-a830-fe862fcd9658"
  Normal   SuccessfulAttachVolume  8m41s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-05965330-52a2-4012-9517-18291024e285"
  Warning  FailedMount             6m49s                  kubelet                  Unable to attach or mount volumes: unmounted volumes=[nmap-out vprobe-logs postgres-data content-home], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition
  Warning  FailedMount             4m41s (x2 over 6m41s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-93b813f0-056d-449a-9255-455d6d88e058" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount             4m40s (x2 over 6m41s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-87cbbc6e-09de-4e01-a830-fe862fcd9658" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount             4m40s (x2 over 6m40s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-05965330-52a2-4012-9517-18291024e285" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount             4m31s                  kubelet                  Unable to attach or mount volumes: unmounted volumes=[content-home nmap-out postgres-data], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition
  Warning  FailedMount             3m34s                  kubelet                  MountVolume.MountDevice failed for volume "pvc-93b813f0-056d-449a-9255-455d6d88e058" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-93b813f0-056d-449a-9255-455d6d88e058 /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/b5a618c37313a1504a00fd7d2ba761ecf2c19f43b7bcc59cb36c3f5ac4edf0bf/globalmount
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/b5a618c37313a1504a00fd7d2ba761ecf2c19f43b7bcc59cb36c3f5ac4edf0bf/globalmount: /dev/longhorn/pvc-93b813f0-056d-449a-9255-455d6d88e058 already mounted on /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/b5a618c37313a1504a00fd7d2ba761ecf2c19f43b7bcc59cb36c3f5ac4edf0bf/globalmount.

**Comment by james-munson** [comment]
That's helpful, but we're going to need a full support bundle.  On the UI, there should be a hot spot on the bottom left for that:
![image](https://github.com/longhorn/longhorn/assets/59452343/87222dd1-0572-411b-b47a-45bd2be100fc)
Thanks!

**Comment by vr2388** [comment]
In longhorn UI it is showing pvc are mounted properly but in pod events it is showing as below


Warning FailedScheduling 8m55s default-scheduler 0/2 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod..
Warning FailedScheduling 8m54s default-scheduler 0/2 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod..
Normal Scheduled 8m52s default-scheduler Successfully assigned default/nextgen-gw-0 to node2
Normal SuccessfulAttachVolume 8m42s attachdetach-controller AttachVolume.Attach succeeded for volume "pvc-91825c7a-fe95-412a-9f04-a29972f20cd2"
Normal SuccessfulAttachVolume 8m41s attachdetach-controller AttachVolume.Attach succeeded for volume "pvc-93b813f0-056d-449a-9255-455d6d88e058"
Normal SuccessfulAttachVolume 8m41s attachdetach-controller AttachVolume.Attach succeeded for volume "pvc-87cbbc6e-09de-4e01-a830-fe862fcd9658"
Normal SuccessfulAttachVolume 8m41s attachdetach-controller AttachVolume.Attach succeeded for volume "pvc-05965330-52a2-4012-9517-18291024e285"
Warning FailedMount 6m49s kubelet Unable to attach or mount volumes: unmounted volumes=[nmap-out vprobe-logs postgres-data content-home], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition
Warning FailedMount 4m41s (x2 over 6m41s) kubelet MountVolume.MountDevice failed for volume "pvc-93b813f0-056d-449a-9255-455d6d88e058" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
Warning FailedMount 4m40s (x2 over 6m41s) kubelet MountVolume.MountDevice failed for volume "pvc-87cbbc6e-09de-4e01-a830-fe862fcd9658" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
Warning FailedMount 4m40s (x2 over 6m40s) kubelet MountVolume.MountDevice failed for volume "pvc-05965330-52a2-4012-9517-18291024e285" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
Warning FailedMount 4m31s kubelet Unable to attach or mount volumes: unmounted volumes=[content-home nmap-out postgres-data], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition
Warning FailedMount 3m34s kubelet MountVolume.MountDevice failed for volume "pvc-93b813f0-056d-449a-9255-455d6d88e058" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-93b813f0-056d-449a-9255-455d6d88e058 /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/b5a618c37313a1504a00fd7d2ba761ecf2c19f43b7bcc59cb36c3f5ac4edf0bf/globalmount
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/b5a618c37313a1504a00fd7d2ba761ecf2c19f43b7bcc59cb36c3f5ac4edf0bf/globalmount: /dev/longhorn/pvc-93b813f0-056d-449a-9255-455d6d88e058 already mounted on /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/b5a618c37313a1504a00fd7d2ba761ecf2c19f43b7bcc59cb36c3f5ac4edf0bf/globalmount.
