### ISSUE TITLE
[TASK][UI] Replace `spec.engineImage` field in volume, engine and replica CRDs with `spec.image`

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6685]
## What's the task? Please describe

https://github.com/longhorn/longhorn/issues/6647

**Comment by PhanLe1010** [comment]
Small note: we need to check the engine upgrading flow online and offline using Longhorn UI. It is currently broken after the PR for #6647. I hit the problem and come to this ticket after digging into the code.

**Comment by derekbit** [comment]
@votdev Can you help this ticket?
