### ISSUE TITLE
[BUG] Longhorn-csi-plugin liveness probe container needs privileged to be able to mount the csi socket dir

### ISSUE THREAD

**Issue by Silvest89** [longhorn/longhorn#6693]
## Describe the bug (🐛 if you encounter this issue)

I updated to 1.27.5 and somehow my longhorn pods didn't come up (waiting for csi.sock)
The longhorn manager liveness proble failed. So I had to give the pod privileged: true to be able to mount the csi socket-dir.

Had to do the same for the csi-* replicasets where a socket-dir was mounted.

## Expected behavior

It's either intended or the replicasets/deployments are missing the `privileged: true`

## Environment

 - Longhorn version: 1.5.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s, 1.27.5
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: OpenSUSE MicroOS
   - Kernel version: 6.4.12
   - CPU per node: 4
   - Memory per node: 8GB
   - Disk type(e.g. SSD/NVMe/HDD): NVME
   - Network bandwidth between the nodes: 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Hetzner Cloud

**Comment by eiskasten** [comment]
Thank you very much your advised worked for me. I assume that you use https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner as well? Seems like a weird coincidence that it happens to the same deployment strategy. I think we should report that there as well.

**Comment by erendogan51** [comment]
Sorry to revive an old issue but have you solved your problem? I am experiencing the same issue with the most recent version of  longhorn. I assume its related to the use of OpenSuse  and/or SeLinux
