### ISSUE TITLE
[BUG] Longhorn manager process consuming 100% CPU

### ISSUE THREAD

**Issue by mike12806** [longhorn/longhorn#6695]
## Describe the bug (🐛 if you encounter this issue)

Longhorn instance manager process is consuming 100% CPU on one of my K8s nodes 

Oddly, although the process in linux is pegged at 100%+, the container / node in Rancher show minimal CPU usage... 

![Screenshot 2023-09-14 at 7 34 57 PM](https://github.com/longhorn/longhorn/assets/80599490/20c184ca-f8ee-4611-8340-e604fc4c9a58)

![Screenshot 2023-09-14 at 7 36 43 PM](https://github.com/longhorn/longhorn/assets/80599490/35330686-7334-4174-a593-3baf2dae3495)

![Screenshot 2023-09-14 at 7 36 17 PM](https://github.com/longhorn/longhorn/assets/80599490/537a25ef-40b4-4149-ac23-3b9491199578)

## To Reproduce

Unsure what's causing / how to re-produce

## Expected behavior

Would expect instance manager not to consume 100%+ CPU with almost no volumes running on that node. 

## Support bundle for troubleshooting

**_Not super comfortable sharing directly here, but happy to email a link to Support team (incl. container logs)_**

## Environment

 - Longhorn version:  v1.5.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher catalog app
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s 1.26.8
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 6 
 - Node config
   - OS type and version: Ubuntu 22.04.3 LTS
   - Kernel version: 6.2.0-32-generic
   - CPU per node: 4 vCPU (virtualized nodes) 
   - Memory per node: Varies; impacted note has 7 GB RAM 
   - Disk type(e.g. SSD/NVMe/HDD): NVMe
   - Network bandwidth between the nodes: Gigabit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Hyper-V
 - Number of Longhorn volumes in the cluster: 11
 - Impacted Longhorn resources:
   - Volume names: n/a

**Comment by mike12806** [comment]
Didn't realize "Instance Manager CPU Request" was a setting that was available; I tweaked that setting in the UI and that seems to have solved the issue? Still unsure why the instance manager was consuming so much CPU though...

**Comment by mike12806** [comment]
I was able to mitigate this by modifying the instance manager cpu request setting in the UI (didn't know this was configurable in the UI, which is pretty neat); but still think there's an underlying bug as to why longhorn process was consuming excess CPU, so will leave open

**Comment by derekbit** [comment]
Can you provide a support bundle?

**Comment by mike12806** [comment]
> Can you provide a support bundle?

Yea. Can you provide an email to send to? I’d prefer not to post here

**Comment by derekbit** [comment]
> > Can you provide a support bundle?
> 
> Yea. Can you provide an email to send to? I’d prefer not to post here

Sure. You can please send it send it to longhorn-support-bundle@suse.com.

**Comment by mike12806** [comment]
> > > Can you provide a support bundle?
> > 
> > 
> > Yea. Can you provide an email to send to? I’d prefer not to post here
> 
> Sure. You can please send it to [longhorn-support-bundle@suse.com](mailto:longhorn-support-bundle@suse.com).

Sent! Thanks

**Comment by derekbit** [comment]
Same issue https://github.com/longhorn/longhorn/issues/6578.
Please refer to the workaround https://github.com/longhorn/longhorn/issues/6578#issuecomment-1692545622.

I'm working on it. https://github.com/longhorn/longhorn-instance-manager/pull/284

**Comment by derekbit** [comment]
I would close the ticket and tracked the issue in https://github.com/longhorn/longhorn/issues/6578. Thank you.

**Comment by mike12806** [comment]
> I would close the ticket and tracked the issue in #6578. Thank you.

@derekbit  any idea when 1.5.2 will be ready for GA? I just hit this bug again. Thanks!
