### ISSUE TITLE
[IMPROVEMENT] Configure the log level of other system and user managed components via longhorn manager setting

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6702]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Currently, only the log level of longhorn manager is able to change at start time and runtime. Need to apply this change to all longhorn components including start and runtime.

[/controller/setting_controller.go#L695-L711](https://github.com/longhorn/longhorn-manager/blob/a77b330ef8024b2f0eeb7d0341d1d3ba5b421e41/controller/setting_controller.go#L695-L711)
```go
func (sc *SettingController) updateLogLevel() error {
	setting, err := sc.ds.GetSetting(types.SettingNameLogLevel)
	if err != nil {
		return err
	}
	oldLevel := logrus.GetLevel()
	newLevel, err := logrus.ParseLevel(setting.Value)
	if err != nil {
		return err
	}
	if oldLevel != newLevel {
		logrus.Infof("Updating log level from %v to %v", oldLevel, newLevel)
		logrus.SetLevel(newLevel)
	}

	return nil
}
```

## Describe the solution you'd like

Could use RPC way to apply the change at runtime. 

## Additional context

ref: #5888

**Comment by derekbit** [comment]
Move it to v1.8.0 cc @james-munson @innobead

**Comment by ChanYiLin** [comment]
Longhorn can adjust the longhorn-manager's log level, but there is currently no way to adjust the log level in runtime for other components like longhorn-instance-manager.

Moreover, the log level (debug) is hard coded for those components. 
https://github.com/longhorn/longhorn-manager/blob/v1.7.x/controller/instance_manager_controller.go#L1389

cc @derekbit @innobead @james-munson

**Comment by derekbit** [comment]
Just checked the issue with @ChanYiLin. The instance-manager’s log level is currently set to debug. The ticket aims to:

- Adjust the default log level to info
- Support adjusting the log level at runtime
- Update certain log messages to info level instead of debug, as this will help avoid difficulties in troubleshooting.

Besides of the instance-manager, also need to address longhorn-engine, backing-image-manager and share-manager.

**Comment by derekbit** [comment]
Just checked the issue with @ChanYiLin. The instance-manager’s log level is currently set to `debug`. The ticket aims to:

- Update some log messages to `info` level instead of `debug`, as this will help avoid difficulties in troubleshooting. 
  - Applied to v1.8.0, v1.7.3 and v1.6.4
- Adjust the default log level to `info`
  -  Applied to v1.8.0, v1.7.3 and v1.6.4
- Support adjusting the log level at runtime
  - Applied to v1.8.0
Besides the instance-manager, also need to address longhorn-engine, backing-image-manager and share-manager.

Please let me know if there is any concern.

cc @james-munson @ChanYiLin @innobead

**Comment by innobead** [comment]
>   * Applied to v1.8.0 (no need to backport the setting to v1.7 and v1.6)
>     Besides the instance-manager, also need to address longhorn-engine, backing-image-manager, and share-manager.

Sounds good. BTW, if changing at runtime is infeasible, the share manager pods could scale out along with the number of volumes. At least this can be achieved at the start time.

**Comment by james-munson** [comment]
Here is some data from the analysis of a recent escalation (support bundle not included) covering about two weeks of logs.  Only the instance-manager and longhorn-manager logs amounted to multiple megabytes.  All others were a few K.

```shell
$ ll * | grep M
total 24M
-rw-r--r--  1 jmunson jmunson  24M Sep 30 08:57 instance-manager.log
total 33M
-rw-r--r--  1 jmunson jmunson  33M Sep 30 08:57 instance-manager.log
total 25M
-rw-r--r--  1 jmunson jmunson  25M Sep 30 08:57 instance-manager.log
total 23M
-rw-r--r--  1 jmunson jmunson  23M Sep 30 08:57 instance-manager.log
total 27M
-rw-r--r--  1 jmunson jmunson  21M Sep 30 08:57 longhorn-manager.log
-rw-r--r--  1 jmunson jmunson 5.3M Sep 30 08:57 longhorn-manager.log.1
total 27M
-rw-r--r--  1 jmunson jmunson  21M Sep 30 08:57 longhorn-manager.log
-rw-r--r--  1 jmunson jmunson 5.4M Sep 30 08:57 longhorn-manager.log.1
total 51M
-rw-r--r--  1 jmunson jmunson  34M Sep 30 08:57 longhorn-manager.log
-rw-r--r--  1 jmunson jmunson  17M Sep 30 08:57 longhorn-manager.log.1
total 37M
-rw-r--r--  1 jmunson jmunson  18M Sep 30 08:57 longhorn-manager.log
-rw-r--r--  1 jmunson jmunson  19M Sep 30 08:57 longhorn-manager.log.1
```
Start with the instance-manager logs.  It's not a matter of debug logs flooding (these results are typical of all):
```shell
$ grep "level=debug" instance-manager.log | wc
    286    4916   95941
```
But rather, that a lot of debug output might logged as info:
```shell
$ grep "level=info" instance-manager.log | wc
  85050 1017526 25659306
```
That's out of a total of
```shell
$ wc instance-manager.log
   85587  1025418 25814581 instance-manager.log
```

Here's a script to count the most verbose loggers in the go code:
```shell
awk 'match($0, /regex/) {
    print substr($0, RSTART, RLENGTH)
} ' <file>
```
so
```shell
awk 'match($0,/file=".*go:[0-9]*"/) {print substr($0, RSTART, RLENGTH)}' instance_manager.log | sort | uniq -c | sort -rn
  10537 file="replica.go:803"
   5301 file="server.go:255"
   5275 file="server.go:243"
   5274 file="server.go:181"
   5274 file="replica.go:961"
   5274 file="replica.go:863"
   5274 file="replica.go:760"
   5274 file="replica.go:754"
   5274 file="replica.go:748"
   5263 file="server.go:231"
   5263 file="server.go:1339"
   5263 file="server.go:1327"
   5263 file="replica.go:407"
   5263 file="replica.go:366"
   5263 file="replica.go:360"
   4988 file="remote.go:87"
   4988 file="remote.go:108"
   2517 file="snapshot.go:268"
   2502 file="snapshot.go:358"
   2490 file="snapshot.go:24"
   2490 file="control.go:212"
   2490 file="control.go:191"
   2490 file="control.go:189"
    430 file="snapshot.go:399"
    189 file="server.go:342"
    189 file="client.go:110"
    188 file="server.go:346"
    186 file="client.go:171"
     80 file="client.go:149"
...
```

**Comment by james-munson** [comment]
@PhanLe1010 points me to `FilteredLoggingHandler` in https://github.com/longhorn/longhorn-manager/blob/e7db6e7adda61b684d4a2d4e247a83ac0935287c/app/daemon.go#L257-L265 for the place where that logging is set in place:
```go
	router = util.FilteredLoggingHandler(map[string]struct{}{
		"/v1/apiversions":  {},
		"/v1/schemas":      {},
		"/v1/settings":     {},
		"/v1/volumes":      {},
		"/v1/nodes":        {},
		"/v1/engineimages": {},
		"/v1/events":       {},
	}, os.Stdout, router)
```

The implementation is in https://github.com/longhorn/longhorn-manager/blob/e7db6e7adda61b684d4a2d4e247a83ac0935287c/util/util.go#L477-L486:
```go
func (h filteredLoggingHandler) ServeHTTP(w http.ResponseWriter, req *http.Request) {
	switch req.Method {
	case "GET":
		if _, exists := h.filteredPaths[req.URL.Path]; exists {
			h.handler.ServeHTTP(w, req)
			return
		}
	}
	h.loggingHandler.ServeHTTP(w, req)
}
```

And it appears to me that the intent was to exclude most GET operations, logging any others.  Unfortunately
- The `req.URL.Path` for a volume is `/v1/volumes/<volume-name>` so the map lookup doesn't catch specific volume queries, and
- Another frequent query is `/metrics`, which is not in the list.

There are a couple of ways to go here.  One simple thing would be to exclude any GET at all, dispensing with the filter list.  Another slightly more expensive way would be to look for anything in the map as the leading part of the `req.URL.Path` string, with string.HasPrefix().  That would remain truer to the intent of filtering out routine but not unusual GET requests.

**Comment by derekbit** [comment]
> There are a couple of ways to go here. One simple thing would be to exclude any GET at all, dispensing with the filter list.

Keeping it simple is good.
We can suppress GET log messages for log levels above DEBUG, and only print them when the log level is set to DEBUG.

**Comment by james-munson** [comment]
This is the list of items for this issue:

- [ ] - Reduce logging of REST calls:  
- [ ] - Demote noisy instance-manager calls from Info to Debug
- [ ] - Demote noisy longhorn-engine calls from Info to Debug
- [x] - ~Demote noisy share-manager calls from Info to Debug~  Not necessary.  There aren't any.
- [ ] - Remove default "--debug" flags from created pods.
- [ ] - Add RPC server methods to longhorn-engine V1 to get/set log level
- [x] - ~Add RPC server methods to share-manager to get/set log level~  Not necessary.
- [ ] - Add calls in longhorn-manager to RPC clients when global setting changes.

**Comment by james-munson** [comment]
> > Demote noisy share-manager calls from Info to Debug Not necessary. There aren't any.
> > Add RPC server methods to share-manager to get/set log level Not necessary.
> 
> Why are the two items unncecessary?

Perhaps I should say "low priority" rather than "Not necessary."

In longhorn-share-manager, there are no Info logs that should be demoted to Debug (there are only a couple of dozen log output lines at Info, and all are about "life changes" like mount and unmount, not recurring jobs such as snapshot with the potential to flood the logs.)  And there are only half a dozen logs at Debug level:
```
pkg/crypto/crypto.go:	logrus.Debugf("Encrypting device %s with LUKS", devicePath)
pkg/crypto/crypto.go:		logrus.Debugf("Device %s is already opened at %s", devicePath, devPath)
pkg/crypto/crypto.go:	logrus.Debugf("Opening device %s with LUKS on %s", devicePath, volume)
pkg/crypto/crypto.go:	logrus.Debugf("Closing LUKS device %s", volume)
pkg/crypto/crypto.go:		logrus.WithError(err).Debugf("Device %s is not an active LUKS device", devicePath)
```
If we continue to start share-manager pod with the "--debug" flag, those won't add very much to the log load.  If, on the other hand, we remove "--debug" from the pod command line options, then it is true that there is no other mechanism to turn those Debug logs on, in the absence of an RPC command to do so, or a watch by share-manager itself on the global setting.

**Comment by PhanLe1010** [comment]
I have some thoughts

Agree that share manager pods doesn't log much. In my experience, it usually only logs less than 100 lines. Together with the fact that there might be big number of share manager pods, maybe we can skip the share manager for now and focus on the:
* longhorn-manager 
* instance-manager (including engine/replica inside it)
* csi plugin
* csi side car pod

longhorn-manager and can be changed online when user changes the global log level setting. instance-manager pod need new grpc method 

csi plugin and csi sidecar pods might just be deleted and restarted with new logging level because:
* It doesn't hurt
* We don't own the csi sidecar code to add grpc server

**Comment by derekbit** [comment]
> > > Demote noisy share-manager calls from Info to Debug Not necessary. There aren't any.
> > > Add RPC server methods to share-manager to get/set log level Not necessary.
> > 
> > 
> > Why are the two items unncecessary?
> 
> Perhaps I should say "low priority" rather than "Not necessary."
> 
> In longhorn-share-manager, there are no Info logs that should be demoted to Debug (there are only a couple of dozen log output lines at Info, and all are about "life changes" like mount and unmount, not recurring jobs such as snapshot with the potential to flood the logs.) And there are only half a dozen logs at Debug level:
> 
> ```
> pkg/crypto/crypto.go:	logrus.Debugf("Encrypting device %s with LUKS", devicePath)
> pkg/crypto/crypto.go:		logrus.Debugf("Device %s is already opened at %s", devicePath, devPath)
> pkg/crypto/crypto.go:	logrus.Debugf("Opening device %s with LUKS on %s", devicePath, volume)
> pkg/crypto/crypto.go:	logrus.Debugf("Closing LUKS device %s", volume)
> pkg/crypto/crypto.go:		logrus.WithError(err).Debugf("Device %s is not an active LUKS device", devicePath)
> ```
> 
> If we continue to start share-manager pod with the "--debug" flag, those won't add very much to the log load. If, on the other hand, we remove "--debug" from the pod command line options, then it is true that there is no other mechanism to turn those Debug logs on, in the absence of an RPC command to do so, or a watch by share-manager itself on the global setting.

Got it. Thank you @james-munson. 

Agree with @PhanLe1010's proposal.

**Comment by james-munson** [comment]
To test, on a cluster with at least one volume, tail the instance-manager logs.  A command like 
```
kt 'instance-manager' -n longhorn-system
```
works well.

- Create or delete a snapshot.  Instance-manager and engine will log all the steps at `Info` level.
- Change the `log-level` setting from the default `Info` to `Warn`, either using the UI or kubectl.  After a minute or so, see that the change of level is logged.
- Create or delete another snapshot.  Instance-manager will be much quieter.
- Reset the log level setting, if desired.

**Comment by derekbit** [comment]
If we use INFO log for v2 data engine, the instance-manager pod log will be overwhelmed by info log messagess from spdk_tgt ... The default spdk_tgt log level is NOTICE. Therefore, we still need a separate setting for spdk_tgt.

```
[2024-11-26 05:07:03.170581] vbdev_lvol_rpc.c: 870:rpc_bdev_lvol_get_xattr: *INFO*: Getting lvol xattr
[2024-11-26 05:07:03.190605] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.190634] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.190645] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.190658] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.190670] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.190686] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.190703] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.190716] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.190744] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.190761] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.190779] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.190794] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.190811] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.190828] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.198585] vbdev_lvol_rpc.c: 870:rpc_bdev_lvol_get_xattr: *INFO*: Getting lvol xattr
[2024-11-26 05:07:03.210586] vbdev_lvol_rpc.c: 870:rpc_bdev_lvol_get_xattr: *INFO*: Getting lvol xattr
[2024-11-26 05:07:03.218582] vbdev_lvol_rpc.c: 870:rpc_bdev_lvol_get_xattr: *INFO*: Getting lvol xattr
[2024-11-26 05:07:03.230587] vbdev_lvol_rpc.c: 870:rpc_bdev_lvol_get_xattr: *INFO*: Getting lvol xattr
[2024-11-26 05:07:03.238583] vbdev_lvol_rpc.c: 870:rpc_bdev_lvol_get_xattr: *INFO*: Getting lvol xattr
[2024-11-26 05:07:03.250587] vbdev_lvol_rpc.c: 870:rpc_bdev_lvol_get_xattr: *INFO*: Getting lvol xattr
[2024-11-26 05:07:03.270606] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.270638] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.270652] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.270666] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.270681] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.270697] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.270715] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.270741] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.270755] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.270770] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.270788] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.270801] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.270818] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.270831] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2588a10
[2024-11-26 05:07:03.278589] vbdev_lvol_rpc.c: 870:rpc_bdev_lvol_get_xattr: *INFO*: Getting lvol xattr
[2024-11-26 05:07:03.290593] vbdev_lvol_rpc.c: 870:rpc_bdev_lvol_get_xattr: *INFO*: Getting lvol xattr
[2024-11-26 05:07:03.298585] vbdev_lvol_rpc.c: 870:rpc_bdev_lvol_get_xattr: *INFO*: Getting lvol xattr
[2024-11-26 05:07:03.310587] vbdev_lvol_rpc.c: 870:rpc_bdev_lvol_get_xattr: *INFO*: Getting lvol xattr
[2024-11-26 05:07:03.318586] vbdev_lvol_rpc.c: 870:rpc_bdev_lvol_get_xattr: *INFO*: Getting lvol xattr
[2024-11-26 05:07:03.330593] vbdev_lvol_rpc.c: 870:rpc_bdev_lvol_get_xattr: *INFO*: Getting lvol xattr
```

**Comment by james-munson** [comment]
In discussion, we agreed to keep the separate settings and control v2 engine logging independently.  There is too much disparity in the verbosity for the same nominal setting level.

**Comment by derekbit** [comment]
@james-munson All PR are merged. Please update the status of the ticket. Thank you.

**Comment by james-munson** [comment]
This solution has focused on the instance-manager/engine logs, which are the most verbose, and satisfy the current customer need.  For completeness, here is the status of Longhorn-created pods:

longhorn-manager
    - Created with --debug flag
    - Adjusts itself to `log-level` setting after startup and when setting changes

longhorn-instance-manager
    - Created with --debug flag
    - Adjusted to `log-level` setting after startup and when setting changes (via RPC)
    - Does little debug logging.  Mostly info level, which can be verbose

longhorn-share-manager
    - Created with --debug flag
    - No method to change level
    - Does little logging with either Debug or Info.

longhorn-csi-plugin
    - Created with no flag, so default log level is Info
    - No method to change level
    - Does little logging - mostly incoming CSI RPC calls logged at Info

longhorn-driver-deployer
    - Created with no flag, so default log level is Info
    - No method to change level
    - Does minimal logging - just about CSI deployments startup and shutdown

engine-image
    - Minimal logging

longhorn-ui
    - Minimal or no logging

backing-image-manager/backing-imaage-data-source
    - Created with --debug flag
    - No method to change level
    - Little logging at Debug except for unit tests

CSI sidecars
    - Currently started with default logging
    - Could be restarted with a -v <log-level> switch to change log level, according to README.
    - Not very verbose anyway, even at Info.  Next to nothing is logged at Debug

**Comment by roger-ryao** [comment]
**Verified on master-head 20241206**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/6cc47ec5e942f33b10f644a5eaf0970b650e27a7
- longhorn-instance-manager `master-head` https://github.com/longhorn/longhorn-instance-manager/commit/88b6f24e17a8f0618c597b2337b1a498ca0de90f

**The test steps**
https://github.com/longhorn/longhorn/issues/6702#issuecomment-2487023670

**Result Passed**
