### ISSUE TITLE
[TEST] Investigate CPU and Memory related operations for negative testing

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6705]
## What's the test to develop? Please describe

Investigate if it's possible to adopt [Litmus Chaos](https://litmuschaos.github.io/litmus/experiments/categories/contents/) to perform the following operations and satisfy the test scenarios and requirements in our negative testing.

For each item, follow the instructions in [Litmus Chaos](https://litmuschaos.github.io/litmus/experiments/categories/contents/) and do the experiment to see if we can use Litmus to implement our negative test cases.
If yes, write down the detailed steps like https://github.com/longhorn/longhorn/issues/6499#issuecomment-1674180185.
If no, elaborate more on what's the difficulty and try to have your own implementation.

The listed items are all from https://confluence.suse.com/pages/viewpage.action?spaceKey=LON&title=Negative+Testing.
Please reference this confluence page to view the details test steps and scenarios.

## Describe the tasks for the test

- [x] increase CPU load on a node
  - https://litmuschaos.github.io/litmus/experiments/categories/nodes/node-cpu-hog/
- [x] increase memory consumption on a node
  - https://litmuschaos.github.io/litmus/experiments/categories/nodes/node-memory-hog/

## Additional context

https://github.com/longhorn/longhorn/issues/6499

**Comment by c3y1huang** [comment]
I will pick up this one, discussed with @yangchiu .

**Comment by innobead** [comment]
> I will pick up this one, discussed with @yangchiu . [We won't adopt Litmus](https://github.com/longhorn/longhorn/issues/6704#issuecomment-1746039791) directly, however, we can still benefit from its implementation [node-cpu-hog](https://github.com/litmuschaos/litmus-go/blob/master/chaoslib/litmus/node-cpu-hog/lib/node-cpu-hog.go?rgh-link-date=2023-10-23T02%3A36%3A17Z) and [node-memory-hog](https://github.com/litmuschaos/litmus-go/blob/master/chaoslib/litmus/node-memory-hog/lib/node-memory-hog.go?rgh-link-date=2023-10-23T02%3A36%3A17Z).

Why decided to now use those experiments directly?

**Comment by c3y1huang** [comment]
> 
> Why decided not to use those experiments directly? To be flexible to extend more test cases by stress-ng?

The reasons are [here](https://github.com/longhorn/longhorn/issues/6704#issuecomment-1746039791) and [here](https://github.com/longhorn/longhorn/issues/6704#issuecomment-1754305375). Based on the discussion in the thread, a consensus seems to have been reached.

**Comment by innobead** [comment]
@c3y1huang the above reasons are related to networking, but here it's CPU/memory? have we seen if any chaos experiments are able to be reused? (if you have done the implementation, that's OK, but I would like to know if anything we can just reuse from any open-source solutions)

**Comment by c3y1huang** [comment]
> @c3y1huang the above reasons are related to networking, but here it's CPU/memory?

Based on my understanding, confirmed with @yangchiu, the consensus is that we won't directly use Litmus experiments for consistency.

Ref: https://github.com/longhorn/longhorn/issues/6704#issuecomment-1746039791
> Since we've had 2 topics won't adopt Litmus, I suggest, for consistency, not consider Litmus for all the other topics anymore. Just have our own implementation.

**Comment by c3y1huang** [comment]
>  have we seen if any chaos experiments are able to be reused? (if you have done the implementation, that's OK, but I would like to know if anything we can just reuse from any open-source solutions)

We're adopting the similar approach, leveraging the [Litmus image](https://github.com/longhorn/longhorn-tests/blob/188bf997a0606a939f72007863dbcaf5975596f2/e2e/libs/workload/constant.py#L2) to stress the node's CPU/memory.
