### ISSUE TITLE
[TEST] Investigate Cluster related operations for negative testing

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6707]
## What's the test to develop? Please describe

Investigate if it's possible to adopt [Litmus Chaos](https://litmuschaos.github.io/litmus/experiments/categories/contents/) to perform the following operations and satisfy the test scenarios and requirements in our negative testing.

For each item, follow the instructions in [Litmus Chaos](https://litmuschaos.github.io/litmus/experiments/categories/contents/) and do the experiment to see if we can use Litmus to implement our negative test cases.
If yes, write down the detailed steps like https://github.com/longhorn/longhorn/issues/6499#issuecomment-1674180185.
If no, elaborate more on what's the difficulty and try to have your own implementation.

The listed items are all from https://confluence.suse.com/pages/viewpage.action?spaceKey=LON&title=Negative+Testing.
Please reference this confluence page to view the details test steps and scenarios.

## Describe the tasks for the test

- [x] delete a node from current cluster, wait for a while, and then add it back
  - should be able to be done by `kubectl` and `ssh`
- [x] high latency K8S API server
  - https://litmuschaos.github.io/litmus/experiments/categories/pods/pod-network-latency/
- [x] force drain nodes
  - Use `kubectl`
- [x] kubelet restart
  - https://litmuschaos.github.io/litmus/experiments/categories/nodes/kubelet-service-kill/
  - Or `ssh` into the node

## Additional context

https://github.com/longhorn/longhorn/issues/6499

**Comment by yangchiu** [comment]
This isn't going to work too:
- [ ] kubelet restart
  - https://litmuschaos.github.io/litmus/experiments/categories/nodes/kubelet-service-kill/

Because it will restart the `kubelet` service which doesn't exist in `k3s` and `rke2`. In `k3s` and `rke2`, The service should be restarted is `k3s-agent` or `rke2-agent`.

So we won't adopt litmus in this topic too. cc @longhorn/qa @innobead

**Comment by innobead** [comment]
Agent just means kubelet including some other node components. It is still the same case.

https://docs.k3s.io/architecture

**Comment by yangchiu** [comment]
> Agent just means kubelet including some other node components. It is still the same case.
> 
> https://docs.k3s.io/architecture

Yes, I mean the command executed by litmus is systemctl start/stop kubelet.

**Comment by yangchiu** [comment]
Currently working on `kubelet restart`

**Comment by yangchiu** [comment]
Currently working `delete a node from current cluster, wait for a while, and then add it back`

**Comment by yangchiu** [comment]
Currently working on `force drain nodes`

**Comment by yangchiu** [comment]
For `delete a node from current cluster, wait for a while, and then add it back`: https://github.com/longhorn/longhorn-tests/pull/1586 has been created
For `force drain nodes`: https://github.com/longhorn/longhorn-tests/pull/1599 has been created

Close this for now.
