### ISSUE TITLE
[BUG] Scheduling Failure: Replica Scheduling Failure

### ISSUE THREAD

**Issue by rnik12** [longhorn/longhorn#6717]
<img width="1440" alt="Screenshot 2023-09-18 at 8 25 21 PM" src="https://github.com/longhorn/longhorn/assets/6128508/b4ee4a1f-dd4b-4a0a-b330-a2e3c2809cfa">
<img width="1440" alt="Screenshot 2023-09-18 at 8 25 31 PM" src="https://github.com/longhorn/longhorn/assets/6128508/b4e3e8ef-9808-4243-80fb-de9b7717f6eb">

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

**Comment by derekbit** [comment]
It looks like you hit the known issue https://github.com/longhorn/longhorn/issues/5762
Please apply the workaround https://github.com/longhorn/longhorn/issues/6121#issuecomment-1590441293
Is the longhorn upgraded from which version or a fresh installation?

**Comment by james-munson** [comment]
This is a continuation of https://github.com/longhorn/longhorn/issues/6678, which I will close since this one has the support bundle.

**Comment by derekbit** [comment]
@rnik12 
Just noticed you set `replica-zone-soft-anti-affinity` to `false`. Can you set it to `true` instead and see if all replicas are scheduled?

**Comment by james-munson** [comment]
To expand on that a bit, setting the "soft" anti-affinity to "false" means there should be "hard" anti-affinity:  that is, no replicas are to be scheduled in the same Zone setting, regardless.
None of the nodes in this cluster are labeled as belonging to a named zone.  Their zone settings are ""null", so they are treated for affinity purposes as if they are all in the same zone.  Hence a replica-zone-soft-anti-affinity of false allows only one of the nodes to be scheduled for any volume.

**Comment by derekbit** [comment]
@rnik12 
Thanks for the update. BTW, why did you `replica-zone-soft-anti-affinity` to `false` before? I'm thinking if we can improve the usage description in the official document and make it clear. Thank you.
