### ISSUE TITLE
[QUESTION] Longhorn takes 3-4 hours to fix degraded volumes of size 200GB

### ISSUE THREAD

**Issue by mayuresh-quartic** [longhorn/longhorn#6728]
## Question

We have 3 PVCs of size 200GB each
If they go in degraded state it takes 3-4 hours to create replica again and pods to function normally

## Environment

 - Longhorn version: 1.4.0
 - Kubernetes version: k3s 1.27.2+k3s
 - Node config
   - OS type and version: Ubuntu 20.04 AMD64
   - CPU per node: 8
   - Memory per node: 32
   - Disk type: SSD
   - Network bandwidth and latency between the nodes: Managed by Azure
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Azure VM

**Comment by mayuresh-quartic** [comment]
Longhorn Manager has 3 CPUs and replica manager has 3 CPU

**Comment by derekbit** [comment]
More inputs are appreciated for further analysis
- What's the actual size of the volume?
- The bandwidth between nodes

**Comment by mayuresh-quartic** [comment]
Actual Size of volumes:
154GB, 134GB, 112GB

Bandwidth between nodes:
Azure VMs
Type: Standard_D8_v3
Max Expected network bandwidth: 4000 MBps

Replicas of each PVC: 3

**Comment by mayuresh-quartic** [comment]
Kernel version: 5.15.0-1046-azure
Storage: XFS


Makes sense what speed you mentioned 37 MB/s
Its same now
If I calculate based upon storage then it matches 3-4 hours time

Any upgradation that will come to coming versions to increase speed?

**Comment by derekbit** [comment]
v1.4.0 supports the fast snapshot rebuilding https://longhorn.io/docs/1.4.0/advanced-resources/fast-replica-rebuild/.
Can you check if the settings are enabled?

**Comment by mayuresh-quartic** [comment]
So that setting was disabled as data-integrity was disbaled
Now I have enabled it with data-integrity as fast-check

I will monitor next time it rebuilds

**Comment by mayuresh-quartic** [comment]
ok 
We ere thinking of going to 1.5.0 to disable snapshot feature
It is breaking other things

I raised a issue also: https://github.com/longhorn/longhorn/issues/6727
This was also faced: https://github.com/longhorn/longhorn/discussions/6698

**Comment by derekbit** [comment]
If you are going to upgrade to v1.5+, you can wait for the upcoming `v1.5.2` which includes several fixes for stability.
