### ISSUE TITLE
[TASK] The development branch should reference to the head images in longhorn-image.txt

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#6737]
## What's the task? Please describe

The development branch such as v1.4.x, v1.5.x should align with the approach taken in the master branch [longhorn-image.txt](https://github.com/longhorn/longhorn/blob/master/deploy/longhorn-images.txt) file to reference the head images.

Without the correct reference, https://ci.longhorn.io/job/private/job/image-security-scan/ does not scan the latest images.

## Describe the sub-tasks

- [x] For the v1.4.x branch, update the [longhorn-image.txt](https://github.com/longhorn/longhorn/blob/v1.4.x/deploy/longhorn-images.txt) file to reference the head of longhorn component images, for example: `longhornio/longhorn-manager:v1.4.x-head`
- [x] For the v1.5.x branch, update the [longhorn-image.txt](https://github.com/longhorn/longhorn/blob/v1.5.x/deploy/longhorn-images.txt) file to reference the head of longhorn component images, for example: `longhornio/longhorn-manager:v1.5.x-head`

## Additional context

https://github.com/longhorn/security/issues/15#issuecomment-1727049905

**Comment by chriscchien** [comment]
Run [image-security-scan](https://ci.longhorn.io/job/private/job/image-security-scan/) pipeline with argument `TF_VAR_LONGHORN_VERSION` =`v1.4.x` and `v1.5.x`, I can find **docker run trivy** command on all images listed in longhorn-image.txt ([v1.5.x](https://github.com/longhorn/longhorn/blob/v1.5.x/deploy/longhorn-images.txt), [v1.4.x](https://github.com/longhorn/longhorn/blob/v1.4.x/deploy/longhorn-images.txt)) in the correspond pipeline console output 

[v1.5.x](https://ci.longhorn.io/job/private/job/image-security-scan/1154/)
- [X] longhornio/csi-attacher:v4.2.0
- [X] longhornio/csi-provisioner:v3.4.1
- [X] longhornio/csi-resizer:v1.7.0
- [X] longhornio/csi-snapshotter:v6.2.1
- [X] longhornio/csi-node-driver-registrar:v2.7.0
- [X] longhornio/livenessprobe:v2.9.0
- [X] longhornio/backing-image-manager:v1.5.x-head
- [X] longhornio/longhorn-engine:v1.5.x-head
- [X] longhornio/longhorn-instance-manager:v1.5.x-head
- [X] longhornio/longhorn-manager:v1.5.x-head
- [X] longhornio/longhorn-share-manager:v1.5.x-head
- [X] longhornio/longhorn-ui:v1.5.x-head
- [X] longhornio/support-bundle-kit:v0.0.27

[v1.4.x](https://ci.longhorn.io/job/private/job/image-security-scan/1153/)
- [X] longhornio/csi-attacher:v3.4.0
- [X] longhornio/csi-provisioner:v2.1.2
- [X] longhornio/csi-resizer:v1.3.0
- [X] longhornio/csi-snapshotter:v5.0.1
- [X] longhornio/csi-node-driver-registrar:v2.5.0
- [X] longhornio/livenessprobe:v2.8.0
- [X] longhornio/backing-image-manager:v1.4.x-head
- [X] longhornio/longhorn-engine:v1.4.x-head
- [X] longhornio/longhorn-instance-manager:v1.4.x-head
- [X] longhornio/longhorn-manager:v1.4.x-head
- [X] longhornio/longhorn-share-manager:v1.4.x-head
- [X] longhornio/longhorn-ui:v1.4.x-head
- [X] longhornio/support-bundle-kit:v0.0.27
