### ISSUE TITLE
[BUG] backupTargetCredentialSecret not applied from helm deployment

### ISSUE THREAD

**Issue by eqinox76** [longhorn/longhorn#6740]
## Describe the bug (🐛 if you encounter this issue)

Deploying longhorn 1.5.1 via helm with 
```
        defaultSettings:
          backupTarget: s3://longhorn-backup@EUROPE-WEST3/
          backupTargetCredentialSecret: longhorn-gcp-backups
```
Seems to ignore the backupTargetCredentialSecret

## To Reproduce

Install longhorn via helm. I use ansible but i think that has no impact:
```
  - name: longhorn
    kubernetes.core.helm:
      name: longhorn 
      chart_ref: longhorn/longhorn
      chart_version: 1.5.1
      release_namespace: longhorn
      create_namespace: true
      values: 
        defaultSettings:
          backupTarget: s3://longhorn-backup@EUROPE-WEST3/
          backupTargetCredentialSecret: longhorn-gcp-backups
```
I see the setting in the kubernetes cluster
```
$ kubectl -n longhorn get configmaps longhorn-default-setting -o yaml
apiVersion: v1
data:
  default-setting.yaml: |-
    backup-target: s3://longhorn-backup@EUROPE-WEST3/
    backup-target-credential-secret: longhorn-gcp-backups
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: longhorn
    meta.helm.sh/release-namespace: longhorn
  creationTimestamp: "2023-09-01T11:56:47Z"
  labels:
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.5.1
    helm.sh/chart: longhorn-1.5.1
  name: longhorn-default-setting
  namespace: longhorn
  resourceVersion: "8630418"
  uid: eb66e06b-0aa5-4f33-83b1-815fdb23501e
```
But the longhorn ui shows `failed to get default backup target client on longhornio/longhorn-engine:v1.5.1: could not access s3 without credential secret` and checking the setting i see:
![image](https://github.com/longhorn/longhorn/assets/5861557/3a084fde-237f-4c66-a2f1-6fb67eab07a4)

## Expected behavior

`longhorn-gcp-backups` should be applied as Backup Target Credential Secret.

## Environment

 - Longhorn version: 1.5.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: rke2 version v1.25.12+rke2r1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 22.04.3
   - Kernel version: 5.15.0-83-generic
   - CPU per node: 3
   - Memory per node: 8096
   - Disk type(e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 3
 - Impacted Longhorn resources: 0
   - Volume names: -

**Comment by roger-ryao** [comment]
Hi @eqinox76 :
   I tried to reproduce the issue on `v1.5.1` , and I made modifications to the https://github.com/longhorn/longhorn/blob/master/chart/values.yaml#L118 file.

Here are the steps I followed:

Cloned the Longhorn repository on the v1.5.1 branch:

```bash
git clone -b v1.5.1 https://github.com/longhorn/longhorn.git
```

Navigated to the Longhorn Helm chart directory:

```bash
cd ./longhorn/chart
```
Installed Longhorn using Helm:

```bash
helm install longhorn . --namespace longhorn-system --create-namespace
```

After Longhorn was installed, I verified that the `backupTarget` and `backupTargetCredentialSecret` were properly configured.
![Screenshot_20230921_142943](https://github.com/longhorn/longhorn/assets/104337648/98eab882-a70b-49bc-a3c2-d37a04fa6f9c)


![Screenshot_20230921_141831](https://github.com/longhorn/longhorn/assets/104337648/327bf5e6-a45f-4f70-b80a-0e22f3103aaf)


Are there any differences in my steps compared to yours?

**Comment by eqinox76** [comment]
Many thanks for you looking into this. Your steps are very similar and the only difference is that i used ansible.

But looking at helm i see the same status:
``` 
$ helm -n longhorn get values longhorn
USER-SUPPLIED VALUES:
defaultSettings:
  backupTarget: s3://longhorn-backup@EUROPE-WEST3/
  backupTargetCredentialSecret: longhorn-gcp-backups
```

Maybe you could have a look if the configmap you deployed looks the same `$ kubectl -n longhorn get configmaps longhorn-default-setting -o yaml`.
If that is also similar i have no good idea how to debug this further and would suggest to say its an user error.

**Comment by roger-ryao** [comment]
> Many thanks for you looking into this. Your steps are very similar and the only difference is that i used ansible.
> 
> But looking at helm i see the same status:
> 
> ```
> $ helm -n longhorn get values longhorn
> USER-SUPPLIED VALUES:
> defaultSettings:
>   backupTarget: s3://longhorn-backup@EUROPE-WEST3/
>   backupTargetCredentialSecret: longhorn-gcp-backups
> ```
> 
> Maybe you could have a look if the configmap you deployed looks the same `$ kubectl -n longhorn get configmaps longhorn-default-setting -o yaml`. If that is also similar i have no good idea how to debug this further and would suggest to say its an user error.

Hi @eqinox76 
    I executed the following CLI commands to retrieve data and captured a screenshot as shown below. However, I noticed that I couldn't retrieve the data using `helm -n longhorn-system get values longhorn`, even though I had already modified the `values.yaml` file when installing Longhorn using Helm
```bash
$  kubectl -n longhorn-system get configmaps longhorn-default-setting -o yaml |grep -H3 backup-target
$  helm -n longhorn-system get values longhorn
$  helm -n longhorn-system get all longhorn |grep -H3 backup-target
```


![Screenshot_20230922_114323](https://github.com/longhorn/longhorn/assets/104337648/67ae5ab4-0009-485e-9119-5ad6ece9ebf6)

**Comment by eqinox76** [comment]
Hmm looks more and more like a user error even though i have no idea where the difference is. I will recreate our cluster in the near future and let you know when i see this problem again.

Many thanks for investigating this.
