### ISSUE TITLE
[TASK] Support running robot test on in-house cloud provider 

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6742]
## What's the task? Please describe

@longhorn/qa is working on robot test implementation, especially for negative testing running on AWS infra. To improve development experience and reduce infra cost, need to make tests able to run locally or in-house cloud provider (like Harvester cluster).  This issue is for a Harvester cluster.

## Describe the sub-tasks

Can leverage Harvester API to provision a k3s/rke2 cluster, then run the test cases.  

## Additional context

cc @longhorn/qa

**Comment by innobead** [comment]
@yangchiu when you are going to implement this, you can let @Anarkis help with the development if you need some helps.

**Comment by khushboo-rancher** [comment]
Closing this as we support running robot test on HAL now.
