### ISSUE TITLE
[TASK] Collect all proto files in longhorn-types repo

### ISSUE THREAD

**Issue by FrankYang0529** [longhorn/longhorn#6744]
## What's the task? Please describe

We have proto files in longhorn-engine, longhorn-instance-manager, longhorn-share-manager, and backing-image-manager. There are some advantage to collect all proto files in one repo:

* Only need to maintain CI in one repo to validate generated code change.
* Don't need to copy proto files to other repos if there are some dependencies. The proto files in longhorn-instance-manager rely on longhorn-engine. Every time we change rpc in longhorn-engine, we need to copy files to longhorn-instance-manager and [update some lines manually](https://github.com/longhorn/longhorn-instance-manager/blob/5fe6bb57c1389d987656dff4bf15dac0592b8fb0/proto/vendor/github.com/longhorn/longhorn-engine/proto/ptypes/controller.proto#L6-L8). If we put them in one repo, we don't need this work.

## Additional context

ref: https://github.com/longhorn/longhorn/issues/6666

We will have a build image for all components when @FrankYang0529 is working on centralizing proto files in one repo.
The build image will be the base image for all dockerfile.dapper in all repos.

**Comment by innobead** [comment]
We can aggregate proto files to https://github.com/longhorn/types.

**Comment by FrankYang0529** [comment]
> We can aggregate proto files to https://github.com/longhorn/types.

Sounds good to me. Let me update it.

**Comment by FrankYang0529** [comment]
> @FrankYang0529 Can you help add a page for the maintenance of proto files ([repo](https://github.com/longhorn/types)) in the [WIKI](https://github.com/longhorn/longhorn/wiki/Development)? The page can include
> 
> * Version control policy of the toolchain such as protoc
> * How to update the proto files to other components such as longhorn-engine
> * gRPC proto message fields should follow an "append-only" approach for
>   
>   * Backward Compatibility
>   * ...
> * Others...
> 
> cc @c3y1huang @ChanYiLin

Add the document https://github.com/longhorn/longhorn/wiki/Longhorn-Protobuf. Thank you.
