### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by marcinsiembida** [longhorn/longhorn#6749]
## Describe the bug (🐛 if you encounter this issue)

I have longhorn on my dev environment and sometimes when I am restarting nodes or restoring from snapshot I get some strange error that I can not pass. I am assuming that there is some network error or something, but let me explain you what is happening.

After restore on Longhorn I see this:
![255b398e-994e-4a55-b446-75c0671830c5](https://github.com/longhorn/longhorn/assets/48014776/7c87d66a-f3cf-4822-a42f-d5670368e921)
![d69da810-75d4-4088-bd81-6d4af6bc4e4e](https://github.com/longhorn/longhorn/assets/48014776/eefc4bb7-7449-4a65-afb0-1438d1ecb6f5)
![0d8a75da-4d4d-436f-b099-623c1a4b74c4](https://github.com/longhorn/longhorn/assets/48014776/1832e2a9-46e9-426c-b86b-533b6433b0fd)

Number of repplicas was maximally 3 per colume and not some 813... I don't remember how much space was before bug, but it was not more than the space I have in allocated column. As you can see on worker-3 everything is fine, but specially second worker is not ok and I do not have snapshot to restore it to the point where it works fine.

When I was restoring (on Xen Orchestra), I have restored both my 3 control planes and 3 worker nodes at once (maybe that was a mistake) and after that this is happening.

I can not find how to delete those scheduledReplica and this is my main question. I found them in node settings, although even I am editing settings in "kubectl edit -n longhorn-system nodes.longhorn.io k8s-plrnd-worker-1" etc. it shows that settings were edited, but when I check again, replicas are still there. Any advise would be helpful.

## To Reproduce

Try to take snapshots of vm on hypervisor and then restore all nodes at once.

## Expected behavior

After restore it should work like it was before.

## Environment

 - Longhorn version: 1.4.1
 - Installation method: Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 22.04 LTS
   - Kernel version:
   - CPU per node: 8
   - Memory per node: 32gb
   - Disk type(e.g. SSD/NVMe/HDD): HDD
   - Network bandwidth between the nodes: 1Gb/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Xen Orchestra/XCP-ng
 - Number of Longhorn volumes in the cluster: 9
 - Impacted Longhorn resources: as on picture
  - Volume names: as on picture

**Comment by derekbit** [comment]
It looks like you hit the known issue https://github.com/longhorn/longhorn/issues/5762
Please apply the workaround https://github.com/longhorn/longhorn/issues/6121#issuecomment-1590441293
BTW, recommend upgrading to a newer version v1.4.3.

**Comment by marcinsiembida** [comment]
Thanks for fast response, I didn't see any blockers to upgrade to latest v1.5.1, so I did.
I have also followed your tip: changed failurePolicy from Ignored to Fail and...
Those steps went well, but now I have couple questions: 
- I still see those unwanted replicas in worker-2, I found some instruction here [https://harvesterhci.io/kb/evicting-replicas-from-a-disk-the-cli-way/] but it does not look like those replicas are going to be removed, if you have instruction for that, please send me this. Below I will paste how it looks like in longhorn and on the node. It seems like one volume is repeating 800 times
![image](https://github.com/longhorn/longhorn/assets/48014776/d09c893a-bd6b-4987-9cbf-ecac49c7c135)
- then I wanted to delete engine image, but i can't and I'm assuming that firstly i have to remove those replicas that are left
![image](https://github.com/longhorn/longhorn/assets/48014776/9be2486b-d06c-45be-85a4-71760a681ac4)
- I have some problems with my volumes, some of them I edited because they had in their yamls "failedAt", after that I changed number of replicas and it worked, but now some are ok and some not at all, but this is my last worry

**Comment by derekbit** [comment]
> Thanks for fast response, I didn't see any blockers to upgrade to latest v1.5.1, so I did. I have also followed your tip: changed failurePolicy from Ignored to Fail and... Those steps went well, but now I have couple questions:
> 
> * I still see those unwanted replicas in worker-2, I found some instruction here [https://harvesterhci.io/kb/evicting-replicas-from-a-disk-the-cli-way/] but it does not look like those replicas are going to be removed, if you have instruction for that, please send me this. Below I will paste how it looks like in longhorn and on the node. It seems like one volume is repeating 800 times

OK. Forgot to mention how to handle the stopped replica.
You have to delete them manually https://github.com/longhorn/longhorn/issues/6179#issuecomment-1600977098.
One user provides a [script](https://github.com/longhorn/longhorn/issues/6179#issuecomment-1660432656) for deleting them. You can check and use it.

>   ![image](https://user-images.githubusercontent.com/48014776/269651747-d09c893a-bd6b-4987-9cbf-ecac49c7c135.png)
> * then I wanted to delete engine image, but i can't and I'm assuming that firstly i have to remove those replicas that are left

After deleting the failed replicas and upgrade the engines of the volumes.
The engine image should be deleted.

>   ![image](https://user-images.githubusercontent.com/48014776/269649236-9be2486b-d06c-45be-85a4-71760a681ac4.png)
> * I have some problems with my volumes, some of them I edited because they had in their yamls "failedAt", after that I changed number of replicas and it worked, but now some are ok and some not at all, but this is my last worry

Let's handle the stopped replicas first and check the issue if you still run into it.

**Comment by marcinsiembida** [comment]
The in the issue that you gave me does not work, neither I can't list replicas:
so I either have to find a way or delete all replicas, but before I will do it I have one question. Can I delete all of the replicas that this output is giving me? I have 800 replicas and I am wondering if any of these is necessary and if I delete wrong one I will lose volume or something like that

kubectl get -n longhorn-system nodes.longhorn.io k8s-plrnd-worker-2 -o yaml | yq e '.status.diskStatus.default-disk-3f92ee4907ec93de.scheduledReplica'
pvc-23bee362-8192-45ee-8fc9-162811bfd207-r-000c9433: 68719476736
pvc-23bee362-8192-45ee-8fc9-162811bfd207-r-0a5b0930: 68719476736
pvc-23bee362-8192-45ee-8fc9-162811bfd207-r-0aebb6d6: 68719476736
pvc-23bee362-8192-45ee-8fc9-162811bfd207-r-0c5bdfb1: 68719476736
pvc-23bee362-8192-45ee-8fc9-162811bfd207-r-0c61b254: 68719476736....

**Comment by derekbit** [comment]
> Can I delete all of the replicas that this output is giving me?

**No, you cannot ALL replicas**. If the healthy replicas are deleted, you will lose your data.
Can we schedule a quick call tomorrow on Slack? Then, we can check the issue together and speed up the process.
In addition, can you send me a support bundle first?

**Comment by marcinsiembida** [comment]
I thought so...
About Slack, yes that is fine, but depends what time, I am from Poland. 
And one more question, where would you want me to send support bundle?

**Comment by derekbit** [comment]
> I thought so... About Slack, yes that is fine, but depends what time, I am from Poland. And one more question, where would you want me to send support bundle?

How about 10am your time (4pm my time)? Feel free to ping me (Derek Su) on the channel.
You can send it to `longhorn-support-bundle@suse.com`.
BTW, I would recommend backing up your volumes first.
