### ISSUE TITLE
A few cleanup needed for backup/restore progress

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#676]
1. Rename the state `incomplete` to `in_progress`. `incomplete` doesn't mean `in_progress`...
2. Rename `BackupProgressReply.backupError` in grpc to `error`

**Comment by shreesha21** [comment]
I have also changed the `BackupProgressReply` to `BackupStatusReply` to keep it consistent with `RestoreStatusReply`. Looks like there is no changes required in `longhorn-manager` and `longhorn-tests` as we are only relying on `complete` and not on `incomplete` earlier.

**Comment by yasker** [comment]
Done.
