### ISSUE TITLE
ISCSI configuration

### ISSUE THREAD

**Issue by AmirMohG** [longhorn/longhorn#6774]
I would like to know if there's an easy way of configuring ISCSI parameters in longhorn. If not, I'd appreciate it if anyone could only name the available methods of modifying ISCSI parameters. Thanks

**Comment by derekbit** [comment]
Could you elaborate more on the purpose?

**Comment by AmirMohG** [comment]
I'm getting about 1/6 to 1/10 of disk performance on non-replicated RWO volumes (with strict-local data locality). I assumed the lack of performance was due to the ISCSI misconfiguration. I would appreciate it if you could guide me on other possible misconfiguration on my part.

**Comment by derekbit** [comment]
@AmirMohG

Longhorn typically uses the default iSCSI configuration.
Please refer to https://github.com/longhorn/longhorn-engine/tree/master/vendor/github.com/longhorn/go-iscsi-helper

The v1 volume performance is mainly limited by the long data path implemented by iSCSI protocol, engine to replica, and replica to sparse file.

If you have any idea for performance improvement, we can try and work on it together.
