### ISSUE TITLE
[BUG] Cannot create a new volume after upgrade to 1.5.1

### ISSUE THREAD

**Issue by jvalskis** [longhorn/longhorn#6775]
## Describe the bug (🐛 if you encounter this issue)

When I was upgrading from `1.4.2` to `1.5.1` the upgrade failed due to some transient network issue. I then did a rollback to `1.4.2` again and then finally managed to upgrade to `1.5.1` successfully. All was fine until I needed to provision a new volume - longhorn never finishes creating new volumes. Everything else seems to work fine though.

Some logs from the manager that are related to the volume in question:
```
[longhorn-manager-gpsct] time="2023-09-24T22:20:20Z" level=error msg="Failed to sync Longhorn volume longhorn-system/pvc-c9119d8e-ae7f-4fc2-a4c6-328009b8b2e2" controller=longhorn-volume error="failed to sync longhorn-system/pvc-c9119d8e-ae7f-4fc2-a4c6-328009b8b2e2: create not allowed while custom resource definition is terminating" node=k3s-worker-21
[longhorn-manager-gpsct] time="2023-09-24T22:20:20Z" level=error msg="Failed to sync Longhorn volume longhorn-system/pvc-c9119d8e-ae7f-4fc2-a4c6-328009b8b2e2" controller=longhorn-volume error="failed to sync longhorn-system/pvc-c9119d8e-ae7f-4fc2-a4c6-328009b8b2e2: create not allowed while custom resource definition is terminating" node=k3s-worker-21
[longhorn-manager-gpsct] time="2023-09-24T22:20:20Z" level=error msg="Failed to sync Longhorn volume longhorn-system/pvc-c9119d8e-ae7f-4fc2-a4c6-328009b8b2e2" controller=longhorn-volume error="failed to sync longhorn-system/pvc-c9119d8e-ae7f-4fc2-a4c6-328009b8b2e2: create not allowed while custom resource definition is terminating" node=k3s-worker-21
[longhorn-manager-gpsct] E0924 22:20:20.688702       1 volume_controller.go:231] failed to sync longhorn-system/pvc-c9119d8e-ae7f-4fc2-a4c6-328009b8b2e2: create not allowed while custom resource definition is terminating
[longhorn-manager-gpsct] time="2023-09-24T22:20:20Z" level=error msg="Dropping Longhorn volume longhorn-system/pvc-c9119d8e-ae7f-4fc2-a4c6-328009b8b2e2 out of the queue" controller=longhorn-volume error="failed to sync longhorn-system/pvc-c9119d8e-ae7f-4fc2-a4c6-328009b8b2e2: create not allowed while custom resource definition is terminating" node=k3s-worker-21
```
This is what it looks like in the UI, it's mostly empty. I get an endless spinner on the `state` and it never gets ready:
![image](https://github.com/longhorn/longhorn/assets/4158759/c39a1f3d-d070-4d57-8e76-a765b2894dd7)

## To Reproduce

No clear steps to reproduce. See description.

## Support bundle for troubleshooting

[supportbundle_6e56908b-8b76-4608-bc8c-200948fae077_2023-09-24T22-37-53Z.zip](https://github.com/longhorn/longhorn/files/12709805/supportbundle_6e56908b-8b76-4608-bc8c-200948fae077_2023-09-24T22-37-53Z.zip)

## Environment

 - Longhorn version: `1.5.1`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): `Helm`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: `v1.27.6+k3s1`
   - Number of management node in the cluster: `3`
   - Number of worker node in the cluster: `3`
 - Node config
   - OS type and version: `Ubuntu 22.04.3 LTS`
   - Kernel version: `5.15.0-84-generic x86_64`
   - CPU per node: `10`
   - Memory per node: `22`
   - Disk type(e.g. SSD/NVMe/HDD): `nvme/hdd`
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): `Proxmox`
 - Number of Longhorn volumes in the cluster: `21`
 - Impacted Longhorn resources:
   - Volume names:

**Comment by c3y1huang** [comment]
https://github.com/longhorn/longhorn/issues/6264#issuecomment-1628387731 might help

**Comment by jvalskis** [comment]
@c3y1huang thanks! I had seen the thread but completely missed the workaround.
I applied the suggested changes and did `helmfile sync` - everything seems to be in order now.
