### ISSUE TITLE
unable to salvage volume pvc-714fdc28-5d7b-46ca-bce4-e360680ba74e: disk with UUID 8ea1f870-8d9d-4985-ad9f-710f00265483 on node cngb-hmaster-b10-1 is unschedulable for replica pvc-714fdc28-5d7b-46ca-bce4-e360680ba74e-r-367c2c69

### ISSUE THREAD

**Issue by chole888** [longhorn/longhorn#6800]
## Environment

 - Longhorn version:  v1.3.2
 - Kubernetes version:  v1.24.11+rke2r1
 - Node config
   - OS type and version：SLE Micro 5.3
   - Kernel version:  5.14.21-150400.24.60-default
   - CPU per node:  48C ，112C
   - Memory per node:  125GiB ， 504 GiB
   - Disk type:  ssd
   - Network bandwidth: 25G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

## Question

On the harvester platform, we configured overcommit on storage, and the maximum capacity of a single SSD disk mounted on k8s node is only 439 GB. We created a vm on harvester, which was allocated a volume with a storage request of 700GB. As data was written to the volume, the avalable space on the disk where the volume was located became insufficient, resulting in an failed state of the pvc. 
    
Subsequently, multiple  960GB SSD disks was added to the kubernetes cluster, and when attempting to salvage it on the Longhorn console, the error still occurred.

![p1](https://github.com/longhorn/longhorn/assets/55941394/0827d357-77d2-452f-8ea6-2082d42d4fcb)
![p2](https://github.com/longhorn/longhorn/assets/55941394/ad180064-d319-4a46-9c70-45a4f8747bde)
![p3](https://github.com/longhorn/longhorn/assets/55941394/b60040ce-a7b5-4d7c-9b12-6277bbd38f45)

**Comment by c3y1huang** [comment]
Have the new disks been added to the Longhorn nodes?
https://longhorn.io/docs/1.3.2/volumes-and-nodes/multidisk/#add-a-disk

**Comment by chole888** [comment]
Yes, the new disks have been successfully added to the Longhorn nodes. @c3y1huang 
![pic](https://github.com/longhorn/longhorn/assets/55941394/8f1dbdd9-175a-427a-993d-859afdab93a8)
