### ISSUE TITLE
[QUESTION] Pod restarts and PV rebuilds

### ISSUE THREAD

**Issue by delfilip** [longhorn/longhorn#6810]
## Question

Am I able to stop restarts on Pods with PV attached?

## Environment

 - Longhorn version: 1.5.1
 - Kubernetes version: v1.21.9+rke2r1
 - Node config: RKE installed, 
   - OS type and version: Ubuntu 20.04 LTS
   - Kernel version: 5.4.0-146-generic
   - CPU per node: 6vCPU on master nodes, 8vCPU on worker nodes
   - Memory per node: 10GB on master nodes, 16GB on worker nodes
   - Disk type: SSD
   - Network bandwidth and latency between the nodes: They are all located in the same site. 1000/1000, less than 5 ms
 - Underlying Infrastructure: VMWare, RKEv2

Longhorn config:
Timeout between Engine and Replica: 30
Default Replica Count: 1
Automatic salvage: yes
Timeout of HTTP Client to Replica File Sync Server: 120
Storage Minimal Available Percentage: 10
volumeBindingMode: WaitForFirstConsumer #changed in storageClass.
## Additional context

Hello guys. I've been testing Longhorn for months, but still facing the same problem:
Sometimes, on our environment happen situations like:
- Kubelet NodePressure,
- Temporary network disconnection. (less than 1 min, or even less than 30 s)

Then, the random Pod with PV managed by Longhorn is restarted. Some of the microservices are highly dependent on f.e postgres instance, which has a PV managed by Longhorn. So when the postgres Pod is restarted, it is not available for a moment, which causes partial service downtime.

PV goes to "Faulted" state, then the AutoSalvage process starts, Volume is detached and reattached again. What is more, when Pod after the restart is scheduled on a different node than it was before, the MultiAttach Error also comes up.

On the other environment, where the local-path-provisioner StorageClass is implemented, I do not face any problems of these. Environment is super-stable and no Pods restarts are happening.

I've started with longhorn version 1.3.2, then upgraded it to 1.4.1 and then 1.5.1. Cannot see any improvement here.

My question is, can I do something to improve the stability of my environment where the Longhorn is implemented?

Thank you
Filip

**Comment by derekbit** [comment]
Have you set the volume's data locality to best-effort or strict-local?

**Comment by innobead** [comment]
https://github.com/longhorn/longhorn/issues/6962
