### ISSUE TITLE
[IMPROVEMENT] Don't log about inability to change settings that didn't change.

### ISSUE THREAD

**Issue by james-munson** [longhorn/longhorn#6812]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

When changing an unrelated setting, each longhorn-manager logs this 
```
[longhorn-manager-bpnpc] time="2023-09-29T17:52:15Z" level=error msg="Failed to sync Longhorn setting longhorn-system/storage-network" controller=longhorn-setting error="failed to sync setting for longhorn-system/storage-network: failed to apply storage-network setting to Longhorn workloads when there are attached volumes" node=jbm-u20-rke2-pool2-b96bb8a4-l7b7n 
[longhorn-manager-bpnpc] time="2023-09-29T17:52:15Z" level=error msg="Failed to sync Longhorn setting longhorn-system/v2-data-engine" controller=longhorn-setting error="failed to sync setting for longhorn-system/v2-data-engine: cannot apply v2-data-engine setting to Longhorn workloads when there are attached volumes" node=jbm-u20-rke2-pool2-b96bb8a4-l7b7n 
[longhorn-manager-bpnpc] time="2023-09-29T17:52:15Z" level=error msg="Failed to sync Longhorn setting longhorn-system/storage-network" controller=longhorn-setting error="failed to sync setting for longhorn-system/storage-network: failed to apply storage-network setting to Longhorn workloads when there are attached volumes" node=jbm-u20-rke2-pool2-b96bb8a4-l7b7n 
[longhorn-manager-bpnpc] time="2023-09-29T17:52:15Z" level=error msg="Failed to sync Longhorn setting longhorn-system/v2-data-engine" controller=longhorn-setting error="failed to sync setting for longhorn-system/v2-data-engine: cannot apply v2-data-engine setting to Longhorn workloads when there are attached volumes" node=jbm-u20-rke2-pool2-b96bb8a4-l7b7n 
[longhorn-manager-bpnpc] time="2023-09-29T17:52:15Z" level=error msg="Failed to sync Longhorn setting longhorn-system/storage-network" controller=longhorn-setting error="failed to sync setting for longhorn-system/storage-network: failed to apply storage-network setting to Longhorn workloads when there are attached volumes" node=jbm-u20-rke2-pool2-b96bb8a4-l7b7n 
[longhorn-manager-bpnpc] E0929 17:52:15.616595       1 setting_controller.go:204] failed to sync setting for longhorn-system/v2-data-engine: cannot apply v2-data-engine setting to Longhorn workloads when there are attached volumes 
[longhorn-manager-bpnpc] time="2023-09-29T17:52:15Z" level=error msg="Dropping Longhorn setting longhorn-system/v2-data-engine out of the queue" controller=longhorn-setting error="failed to sync setting for longhorn-system/v2-data-engine: cannot apply v2-data-engine setting to Longhorn workloads when there are attached volumes" node=jbm-u20-rke2-pool2-b96bb8a4-l7b7n 
[longhorn-manager-bpnpc] E0929 17:52:15.623254       1 setting_controller.go:204] failed to sync setting for longhorn-system/storage-network: failed to apply storage-network setting to Longhorn workloads when there are attached volumes 
[longhorn-manager-bpnpc] time="2023-09-29T17:52:15Z" level=error msg="Dropping Longhorn setting longhorn-system/storage-network out of the queue" controller=longhorn-setting error="failed to sync setting for longhorn-system/storage-network: failed to apply storage-network setting to Longhorn workloads when there are attached volumes" node=jbm-u20-rke2-pool2-b96bb8a4-l7b7n 
```
That's 9 lines of pointless and distracting logging (at error level!) for a change that was not even requested.

## Describe the solution you'd like
Surely we can check that the value did change and log nothing, rather than supposing it might have and warning why we can't do it if it actually did.

**Comment by james-munson** [comment]
The settings logic requires the check be made and the error returned - otherwise the code will try to apply the setting.  So we can't just drop the error.  We need to find a way to squelch it within controller.handleReconcileErrorLogging.  Perhaps if we were to make that a derived Error type.

**Comment by james-munson** [comment]
Implemented and testing.  Looking at the code, though, why don't the settings for TaintToleration, SystemManagedComponentsNodeSelector, and PriorityClass behave the same way?  They also have a check for "all volumes detached" although they do a different implementation of the check using datastore.s.ListVolumesRO().  StorageNetwork and V2DataEngine use datastore.s.AreAllVolumesDetached instead.  What's the difference?

**Comment by derekbit** [comment]
感謝您!

________________________________________
寄件者: James Munson ***@***.***>
寄件日期: Tuesday, October 17, 2023 11:53:29 AM
收件者: longhorn/longhorn
副本: Subscribed
主旨: Re: [longhorn/longhorn] [IMPROVEMENT] Don't log about inability to change settings that didn't change. (Issue #6812)

Implemented and testing. Looking at the code, though, why don't the settings for TaintToleration, SystemManagedComponentsNodeSelector, and PriorityClass behave the same way? They also have a check for "all volumes detached" although they do a different implementation of the check using datastore.s.ListVolumesRO(). StorageNetwork and V2DataEngine use datastore.s.AreAllVolumesDetached instead. What's the difference?

**Comment by james-munson** [comment]
Hmm.  Check for error type by casting is defeated by wrapper errors.
Doh!  See https://stackoverflow.com/questions/23796543/go-checking-for-the-type-of-a-custom-error

**Comment by james-munson** [comment]
Fixed, and now logging is reduced to just the kubernetes-layer logging by "k8s.io/apimachinery/pkg/util/runtime" HandleError().  
  https://pkg.go.dev/k8s.io/apimachinery/pkg/util/runtime#HandleError
Leaving that one alone for now.
Still wondering why there are two methods for checking whether all volumes are detached in longhorn-manager/datastore/longhorn.go.
Also still wondering why storage-network and v2 engine settings behave differently from the other "only when detached" settings, like TaintToleration and PriorityClass.  I don't think the answer lies in the different implementations of "AreAllVolumesDetached" because those settings don't ever seem to be queued to even check.

**Comment by roger-ryao** [comment]
**Verified on master-head 20231113**

- longhorn master-head https://github.com/longhorn/longhorn/commit/e4e577275c89b6c6c7815fc5d5eee98f03348a99
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/d3673dfd8c55690c5ec8dd8686a79c46b5342ef8


**The test steps**

https://github.com/longhorn/longhorn/issues/6812#issuecomment-1768715835
https://github.com/longhorn/longhorn-manager/pull/2228#issue-1948410762


**Result Passed**

1. No error message logs were found regarding `Setting=longhorn-system/storage-network.`
2. Only Kubernetes-layer logs were recorded every hour

```console
2023-11-13T04:26:05.212779714Z E1113 04:26:05.212665       1 setting_controller.go:205] failed to sync setting for longhorn-system/storage-network: current state prevents this: failed to apply storage-network setting to Longhorn workloads when there are attached volumes
2023-11-13T04:26:05.212856823Z E1113 04:26:05.212809       1 setting_controller.go:205] failed to sync setting for longhorn-system/v2-data-engine: current state prevents this: cannot apply v2-data-engine setting to Longhorn workloads when there are attached volumes
---
2023-11-13T05:26:31.235316443Z E1113 05:26:31.235189       1 setting_controller.go:205] failed to sync setting for longhorn-system/v2-data-engine: current state prevents this: cannot apply v2-data-engine setting to Longhorn workloads when there are attached volumes
2023-11-13T05:26:31.240515077Z E1113 05:26:31.240405       1 setting_controller.go:205] failed to sync setting for longhorn-system/storage-network: current state prevents this: failed to apply storage-network setting to Longhorn workloads when there are attached volumes
```
[supportbundle_96cc8f66-c411-4fa7-ae56-249a3303cf3e_2023-11-13T07-13-16Z.zip](https://github.com/longhorn/longhorn/files/13331885/supportbundle_96cc8f66-c411-4fa7-ae56-249a3303cf3e_2023-11-13T07-13-16Z.zip)
