### ISSUE TITLE
Pre-upgrade and uninstall jobs never finish due to incompatibility with linkerd

### ISSUE THREAD

**Issue by NicoForce** [longhorn/longhorn#6814]
## Describe the bug (🐛 if you encounter this issue)
When using linkerd in the cluster, and then deploy longhorn, linkerd will inject it's containers into every resource, the jobs finish but linkerd stays awake, so technically the jobs never finish properly.

## To Reproduce

Install linkerd's helm chart. Then install longhorn's helm chart.

## Expected behavior

Everything to run without errors.

## Environment

 - Longhorn version: 1.5.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: EKS 1.24
   - Number of management node in the cluster: -
   - Number of worker node in the cluster: 9
 - Node config
   - OS type and version: Amazon Linux 2
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS EKS

## Additional context

There are 2 easy solutions for this, and solution 1 will temporarily solve the issue with #3809 as well, at least until 1.6.0 is out:

1. Add the .Values.annotations in all resources of the template, not just the DaemonSet (https://github.com/longhorn/longhorn/blob/v1.5.1/chart/values.yaml#L288-L289)

2. Give the option to edit the pre-upgrade, post-upgrade and uninstall jobs' command; this will allow it to run inside linkerd-await so linkerd knows when the job is finished. 

I'd like to work on this and submit a quick PR, so let me know if it's open for contribution.

**Comment by innobead** [comment]
@NicoForce Go ahead to contribute. @mantissahz will work with u for the following review.

**Comment by NicoForce** [comment]
Here's the initial PR: https://github.com/longhorn/longhorn/pull/6817.

Could you confirm which CRDs become pods that need annotation as well? I also don't know how to add annotations to internal resources of CRDs, so will have to look into that as well.

**Comment by mantissahz** [comment]
@NicoForce Thanks for the contribution.

>Here's the initial PR: https://github.com/longhorn/longhorn/pull/6817.
Could you confirm which CRDs become pods that need annotation as well? I also don't know how to add annotations to internal resources of CRDs, so will have to look into that as well.

Can you explain more about "which CRDs become pods that need annotation"? like CRD `engineimages.longhorn.io` and there is a pod created for the object of this CRD?
And will this kind of crds-to-pods affect `Pre-upgrade, Post-upgrade and uninstall jobs` or Longhorn working with linkerd?

**Comment by NicoForce** [comment]
@mantissahz , take for example the following image of my longhorn installation:

![image](https://github.com/longhorn/longhorn/assets/32383958/d0aba084-77ec-4131-ac14-0814c6e0099a)

You can see pods such as **engine-image-ei** and **instance-manager** with 2/2 containers, means linkerd is injected into them; however, I can't seem to find a yaml where these DaemonSet/Deployment is defined to add the option for annotations, I can only assume the pods are coming from CRDs. I haven't worked much with CRDs before so I'm having some trouble understanding where I need to do the changes to add the option for annotations. But I'd like to at least know which CRDs are responsible for creating those pods.

Let me know if that's clear.

**Comment by NicoForce** [comment]
Closing this issue as it's fixed by #3809 .
