### ISSUE TITLE
Access create snapshot api return timeout

### ISSUE THREAD

**Issue by smallteeths** [longhorn/longhorn#682]
- Write a 10 GB data file in the volume
- On volume details page:
   Create a snapshot when during file writing. The create snapshot api will return timeout
![Jietu20190814-131917](https://user-images.githubusercontent.com/27733391/63012083-2b3c1e00-bebc-11e9-9921-f8a5dbf17f8d.jpg)

**Comment by yasker** [comment]
We need to investigate since even we're writing the data, the snapshot should be still possible.

**Comment by yasker** [comment]
@smallteeths Just to clarify, how big is the timeout?

**Comment by smallteeths** [comment]
Server returns 500 doesn't returns 502.I don't know if timeout caused it
Steps to test:
 1. Create a volume with size 40 GB
 2. Create PVC and create pod bound this PVC
 3. exec -it this pod and Write a 10 GB data  `dd if=/dev/zero of=/var/tmp/test3 bs=10M count=1024`
 4. In Volume Details create snapshot

**Comment by yasker** [comment]
@meldafrawi Can you check if you can reproduce it?

**Comment by meldafrawi** [comment]
can't reproduced again. closing the issue.
