### ISSUE TITLE
[TEST] Using a dockerfile to run robot e2e test

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6824]
## What's the test to develop? Please describe

using a dockerfile to run robot e2e test, so users can just run docker instead. This can be environment independent.

## Additional context

https://github.com/longhorn/longhorn-tests/pull/1541#discussion_r1342227830

**Comment by innobead** [comment]
Another alternative is https://nixos.org/.

**Comment by yangchiu** [comment]
Achieved in https://github.com/longhorn/longhorn-tests/pull/1805 and https://github.com/longhorn/longhorn-tests/pull/1807.
