### ISSUE TITLE
[BUG] IO error occurs when detaching RWX volume

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6829]
## Describe the bug (🐛 if you encounter this issue)

IO errors when detaching RWX volume

```
[  630.729622] Buffer I/O error on dev sda, logical block 1081344, lost sync page write
[  630.729699] JBD2: Error -5 detected when updating journal superblock for sda-8.
[  630.729706] Aborting journal on device sda-8.
[  630.729743] Buffer I/O error on dev sda, logical block 1081344, lost sync page write
[  630.729778] JBD2: Error -5 detected when updating journal superblock for sda-8.
```

It looks like an ordering issue. The volume engine is deleted before cleaning up the share-manager pod. 

## To Reproduce

1. Create one RWX volume on Longhorn v1.3.3, v1.4.3 or v1.5.1 or master-head cluster 

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-test
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc-rwx
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-test
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-test-rwx
  labels:
    app: volume-test-rwx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volume-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: volume-test
    spec:
      restartPolicy: Always
      containers:
      - image: derekbit/dbbench:latest
        name: volume-test
        command: ["sleep", "3600000"]
        volumeMounts:
        - name: longhorn-volv
          mountPath: /data
      volumes:
      - name: longhorn-volv
        persistentVolumeClaim:
          claimName: longhorn-volv-pvc-rwx
```

2. Delete the Deployment
3. IO error messages are shown in dmesg
```
[  725.080587] sd 2:0:0:1: Attached scsi generic sg1 type 0
[  725.080897] sd 2:0:0:1: Power-on or device reset occurred
[  725.081035] sd 2:0:0:1: [sda] 20971520 512-byte logical blocks: (10.7 GB/10.0 GiB)
[  725.081049] sd 2:0:0:1: [sda] Write Protect is off
[  725.081049] sd 2:0:0:1: [sda] Mode Sense: 69 00 10 08
[  725.081075] sd 2:0:0:1: [sda] Write cache: disabled, read cache: enabled, supports DPO and FUA
[  726.109588] sd 2:0:0:1: [sda] Attached SCSI disk
[  729.573383] EXT4-fs (sda): mounted filesystem with ordered data mode. Opts: (null)
[  735.413695] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  735.413707] IPv6: ADDRCONF(NETDEV_CHANGE): calibb864c1e08a: link becomes ready
[  877.196035] blk_update_request: I/O error, dev sda, sector 8650752 op 0x1:(WRITE) flags 0x800 phys_seg 1 prio class 0
[  877.196055] Buffer I/O error on dev sda, logical block 1081344, lost sync page write
[  877.196532] JBD2: Error -5 detected when updating journal superblock for sda-8.
[  877.196542] Aborting journal on device sda-8.
[  877.196600] blk_update_request: I/O error, dev sda, sector 8650752 op 0x1:(WRITE) flags 0x800 phys_seg 1 prio class 0
[  877.196609] Buffer I/O error on dev sda, logical block 1081344, lost sync page write
[  877.196696] JBD2: Error -5 detected when updating journal superblock for sda-8.
[  877.196761] blk_update_request: I/O error, dev sda, sector 0 op 0x1:(WRITE) flags 0x800 phys_seg 1 prio class 0
[  877.196769] Buffer I/O error on dev sda, logical block 0, lost sync page write
[  877.196809] EXT4-fs (sda): I/O error while writing superblock
[  877.196815] EXT4-fs error (device sda): ext4_put_super:1125: Couldn't clean up the journal
[  877.196822] EXT4-fs (sda): Remounting filesystem read-only
```  

## Expected behavior

Successfully detach RWX volume without IO error.

## Environment

 - Longhorn version: v1.3.3, v1.4.3 or v1.5.1 or master-head 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

**Comment by innobead** [comment]
Discussoin with @derekbit 

> NFS cache is not able to flush to the volume?
yes, I think so. The volume is gone before tearing down the NFS server.
> It seems this would be easy to reproduce in one consumer pod case
We can sometimes see a similar io error in users’ support bundles.
Not sure if it is related, but the order is obviously wrong.

Attach:
Create a volume -> export volume via NFS

Detach should be:
unexport volume -> detach volume

**Comment by innobead** [comment]
The share manager is the last workload using the RWX volume, so the volume should be detached only when the share manager pod is deleted.

**Comment by innobead** [comment]
@derekbit Sounds good to me. Any risks or challenges to port Share manager gRPC service in 1.4?

**Comment by derekbit** [comment]
> @derekbit Sounds good to me. Any risks or challenges to port Share manager gRPC service in 1.4?

I think no for a newly added gRPC service.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `396605`) with test [steps](https://github.com/longhorn/longhorn/issues/6829#issue-1923356801) 

After repeating the test steps several times, I did not observe "I/O error "related log appeared in dmesg output, and the data in share manager is correct
