### ISSUE TITLE
[IMPROVEMENT] meaningful error description on LH uninstallation

### ISSUE THREAD

**Issue by giubacc** [longhorn/longhorn#6835]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

I needed to uninstall my Longhorn installation from my k8s cluster, so I simply executed:

```
vagrant@admin-1:~> helm uninstall -n longhorn-system longhorn
```

I was unaware of the Longhorn's security measure that blocks an uninstallation, so when I received the error message:

```
Error: job failed: BackoffLimitExceeded
```

I thought this was a technical issue.
After a while, with the help of the  Longhorn slack channel, I've been put on the right path:

https://longhorn.io/docs/1.5.1/deploy/uninstall/
"You need to set the delete confirmation flag" 

## Describe the solution you'd like

I think current error is too much technical, it would be better having something more meaningful such as:

```
vagrant@admin-1:~> helm uninstall -n longhorn-system longhorn
Error: To enable uninstall, follow the procedure described here: https://longhorn.io/docs/1.5.1/deploy/uninstall 
```

**Comment by ChanYiLin** [comment]
It seems there is no way to customize the helm command error message
- https://github.com/helm/helm/issues/12017
- https://github.com/helm/helm/issues/12002

During uninstallation,  Longhorn creates a `longhorn-uninstall` pod to clean up the resources.
If there is any error, it prints the error message in the log most of the time.

In this case, the log would indicate users to update the setting to allow uninstallation.
```
time="2024-08-28T07:48:43Z" level=fatal msg="cannot uninstall Longhorn because deleting-confirmation-flag is set to `false`. Please set it to `true` using Longhorn UI or kubectl -n longhorn-system edit settings.longhorn.io deleting-confirmation-flag " func=main.main.UninstallCmd.func7 file="uninstall.go:48"
```

We also provide the guideline of how to uninstall Longhorn in our helm readme
https://github.com/longhorn/longhorn/tree/master/chart#uninstallation

cc @derekbit @innobead
