### ISSUE TITLE
[TASK] Revert "Disable Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly for RWX volumes"

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6838]
## What's the task? Please describe

Revert https://github.com/longhorn/longhorn/issues/5017 since revert back to `softerr`/`soft` mode in https://github.com/longhorn/longhorn/issues/6655

**Comment by roger-ryao** [comment]
**Verified on master-head 20231006**

- longhorn master-head https://github.com/longhorn/longhorn/commit/8c6a3f5142749f10e5719cb7833a2a8519a84f4f
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/be4c3e4b2479743a93f1d40a5be7f31b3cd0adca

**The test steps**

1. Revert the https://github.com/longhorn/longhorn-tests/pull/1221
2. execute test case `test_rwx.py::test_rwx_delete_share_manager_pod`

**Result Passed**

- [x] 1. The test has passed successfully with private image. https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4992/
- [x] 2. Create the https://github.com/longhorn/longhorn-tests/pull/1549
