### ISSUE TITLE
[BUG] Unable to add a block-type disk with a new name

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6849]
## Describe the bug (🐛 if you encounter this issue)

If a block-type disk was added and removed, the disk cannot be added to node with a new name.

## To Reproduce

1. Add a block-type disk `disk-1`
2. Remove the disk
3. Add the block-type disk with a new name `disk-2`

## Environment

 - Longhorn version: v1.5.1 and master
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `396605`)

1. Remove a block disk, then add that block disk again with a new name was successful. 
2. After completing step 1, create  a workload with V2 engine, that workload worked properly
