### ISSUE TITLE
[FEATURE] Clean up orphaned unused volume replicas after node failure

### ISSUE THREAD

**Issue by vistalba** [longhorn/longhorn#685]
I run into a node failure agina... because of a connectivity issue (not related to longhorn).

Longhorn rebuilds the replica on the two remaining nodes.
I then manually rebalanced it after third node was avaiable again.

After all rebuilds I noticed a big bump at disk-space on node3 (that one that has failed before).

```
drwxr-xr-x  2 root root 4.0K Aug 17 04:45 k8s-vol1-data-1bb645c8
drwxr-xr-x  2 root root 4.0K Aug 16 21:18 k8s-vol2-data-ea61e796
drwxr-xr-x  2 root root 4.0K Aug 17 04:30 k8s-vol2-data-fc6ad090
drwxr-xr-x  2 root root 4.0K Aug 16 21:05 k8s-vol3-e72fde22
drwxr-xr-x  2 root root 4.0K Aug 17 07:35 k8s-vol3-ef30aa7f
drwxr-xr-x  2 root root 4.0K Aug 17 04:30 k8s-vol4-data-5d17716b
drwxr-xr-x  2 root root 4.0K Aug 17 04:15 k8s-vol5-data-150d08a3
drwxr-xr-x  2 root root 4.0K Aug 17 04:00 k8s-vol6-data-72eb9a67
drwxr-xr-x  2 root root 4.0K Aug 17 03:45 k8s-vol8-data-f8f3c7be
drwxr-xr-x  2 root root 4.0K Aug 16 23:05 pvc-cd235079-b057-11e9-a7a3-960000289ce9-b4dd5aab
```

As you can see, longhorn leave old folders on the node which are consuming the space. So I just deleted the old from `aug 16`. Longhorn should do that automaticly. Longhorn did not show any failed replica in any of the above volumes in the UI.

**Comment by yasker** [comment]
Currently, the faulted replica will be cleaned up after 30 minutes, and if the node isn't available for clean up, it will be simply skipped since it cannot wait for the node forever. Though it seems the default `staleReplicaTimeout` is too low (which is set for each volume now) and users may want to keep it a bit longer, and it also means if the node came back in time, the replicas would be cleaned up properly.

If we're going to integrate a tool to help clean up the disk space, we must be more careful to make sure it's indeed leftover of deleted replicas, since we don't have any information regarding this directory may be useful or not. I would want this tool to be manually triggered instead of automatically triggered then.

**Comment by vistalba** [comment]
@yasker For me it could be automaticly after the volume get `healty` state again. If volume isn't healty thant I suggest du leave all `failed` replicas just in case. (then we can trigger it manually if someone thinks it's safe to delete).

For me the case is:

- healthy volume with 3 replicas is running and mounted.
- one of three nodes with 1 replica goes down
- node comes back (after some time... minutes/houers - whatever ... more than 30 minutes - if I understand you right -> but then at least a notification about this should be sent)
- longhorn rebuilds the replica on the noda failed before (there are now two replicas. A running/healthy and a faild)
- because the replica is big (36GB) it uses 72GB of space on this node and reach the limit I definied to stop sheduling on this node. 

Problems:
- New Volumes with 3 replicas with 2 replicas on the same node
- No notification about this state (so I can check it manually)
- running out of space on this node slowly. -> because I didn't know anything about the this and I didn't check the UI

**Comment by yasker** [comment]
My initial thought would be we should scan the disk to see if there is any unknown replica directory, and give the user an option to delete those. The known vs unknown can be found by checking the replica crd for the data path. For all the unknown replica, we can guess what's the volume but we definitely don't want to use it or delete it without user's permission.

Also, if we start to detect the existing replicas automatically, it's possible we can restore the replica into volumes in this was. Even though the metadata of the volume has been lost, we should still recovery the data.

We need a LEP for this to define what we can do once we start to scan the disk for the data.

**Comment by joshimoo** [comment]
Some quick thoughts on this:
- we might want to consider not removing the finalizer on a marked for deletion Replica till we have cleaned up the data
- in that case we could still mark the replica for deletion and are free to ignore it for other processing
- we can remove the finalizer of deletion marked replicas once a node gets deleted from longhorn

My initial instinct is that we could assume that if a node is not deleted from kubernetes -> longhorn that the assumption is that the node is supposed to return eventually therefore it's correct to mark the crd (replica / others) for deletion but wait with removal of the finalizer till the `actual cleanup was verified`. That's what the purpose of the finalizer is for.

**Comment by Martin-Weiss** [comment]
We have been running into this issue, too - not due to node failures but probably due to rolling upgrade with drain using RKE2.. now the question is: how can we find out which are the "orphaned" directories we can delete?

**Comment by derekbit** [comment]
Before the release of v1.3.0, you can compare replica directories and replica resources' `replica.spec.dataDirectoryName` and then find out the orphaned directories which is not managed and used by Longhorn.

**Comment by Martin-Weiss** [comment]
> Before the release of v1.3.0, you can compare replica directories and replica resources' `replica.spec.dataDirectoryName` and then find out the orphaned directories which is not managed and used by Longhorn.

Any chance we can get a script to do that? We have many cluster nodes and doing this manually node by node is a bit of a challenge...

**Comment by WolfspiritM** [comment]
> Any chance we can get a script to do that? We have many cluster nodes and doing this manually node by node is a bit of a challenge...

As we have the same usecase I made a script for now. It's still not completly automated but I hope it helps a bit:
``` bash
#!/bin/bash
set -e
hostname=$1
namespace=longhorn-system
disks=$(kubectl -n $namespace get node.longhorn.io $hostname -o jsonpath='{.spec.disks..path}')
expected_dirs=$(kubectl -n $namespace get replica.longhorn.io -l longhornnode=$hostname -o jsonpath='{range .items[*]}{.spec.diskPath}{"replicas/"}{.spec.dataDirectoryName}{" "}{end}')

echo '
####START####
expected_dirs=('$expected_dirs')
disks=('$disks')
if [ ! -d "${expected_dirs[0]}" ]; then
  echo "Failsafe triggered. Expected directory does not exist"
else
  for disk in "${disks[@]}" ; do
    for dir in ${disk}replicas/* ; do
      found=0
      for g in "${expected_dirs[@]}" ; do
        [ "$dir" = "$g" ] && found=1
      done
      [ "$found" = 0 ] && echo "$dir: is NOT an active replica"
      [ "$found" = 1 ] && echo "$dir: IS an active replica"
    done
  done
fi
####END####
'
```

Make sure to run that script on a node with kubectl installed first then pass in the longhorn node as an argument:
./replicacheck.sh worker01

It will then generate a script including all the "known replica paths" which needs to be copied to the worker and executed there. It will check for any directory under the disk mount paths (we only use one disk per node so I wasn't able to test it with multiple disks) and figure out if the "known replica paths" contains that path.

It's not removing anything (yet) but you can modify the script output to not output if it's an active replica or not but instead just output something like "rm -rf $dir" which can then be executed.

Also it might be a good idea to disable scheduling on the node you're working on to prevent any new replica from being scheduled which is then missing in the array and (wrongly) detected as orphaned.

**Comment by yangchiu** [comment]
verified passed by running [orphan tests](https://github.com/longhorn/longhorn-tests/pull/940) on master-head
