### ISSUE TITLE
[FEATURE] Add disk status prometheus metrics

### ISSUE THREAD

**Issue by petertakacs** [longhorn/longhorn#6858]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

If a disk is not schedulable we would like to setup an alert with Prometheus. However condition metrics are not exposed today.

## Describe the solution you'd like

Add a new metric called `longhorn_disk_status` that describes each disk status by exposing its conditions.

Sample:

```
longhorn_disk_status{condition="ready",condition_reason="",disk="default-disk-c29ac79b6ed10a4b",node="ptakacs-localhost-1"} 1
longhorn_disk_status{condition="schedulable",condition_reason="DiskPressure",disk="default-disk-c29ac79b6ed10a4b",node="ptakacs-localhost-1"} 0
```

This metric is similar we have for nodes: `longhorn_node_status`

**Comment by chriscchien** [comment]
Verified on longhorn master (longhorn-manager `6dcbb2`)

Metric longhorn_disk_status reflected disk status with condition `ready` and `schedulable` as below, I will wait [PR](https://github.com/longhorn/website/pull/786) merged before closing this ticket

A ready and schedulable disk:
```bash
longhorn_disk_status{condition="ready",condition_reason="",disk="default-disk-7cd6c4cbd5f30027",node="ip-172-31-42-83"} 1
longhorn_disk_status{condition="schedulable",condition_reason="",disk="default-disk-7cd6c4cbd5f30027",node="ip-172-31-42-83"} 1
```
A ready and not schedulable disk(because disk pressure):
```bash
longhorn_disk_status{condition="ready",condition_reason="",disk="default-disk-7cd6c4cbd5f30027",node="ip-172-31-45-118"} 1
longhorn_disk_status{condition="schedulable",condition_reason="DiskPressure",disk="default-disk-7cd6c4cbd5f30027",node="ip-172-31-45-118"} 0
```
A not ready and not schedulable disk:
```bash
longhorn_disk_status{condition="ready",condition_reason="NoDiskInfo",disk="not-ready-disk",node="ip-172-31-45-118"} 0
longhorn_disk_status{condition="schedulable",condition_reason="DiskNotReady",disk="not-ready-disk",node="ip-172-31-45-118"} 0
```

**Comment by chriscchien** [comment]
Close this ticket as the documentation merged and the test results match the documentation.
