### ISSUE TITLE
[DOC] Run fsck.ext4 on newer Longhorn volume from older Linux distro

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#6859]
## What's the document you plan to update? Why? Please describe

It is not possible to run `fsck.ext4` on a Longhorn volume when it is manually attached to a RHEL 7 node. The below error is returned:

```
-> fsck.ext4 /dev/longhorn/pvc-c7152ef5-55c7-43ce-a35e-dac69d2be591 
e2fsck 1.42.9 (28-Dec-2013)
/dev/longhorn/pvc-c7152ef5-55c7-43ce-a35e-dac69d2be591 has unsupported feature(s): metadata_csum
e2fsck: Get a newer version of e2fsck!
```

RHEL 7, CentOS 7, etc. cannot update their `e2fsprogs` to a version that supports the `metadata_csum` feature. It may be possible to rework the Longhorn code to explicitly create filesystems without this feature, but this is undesirable, considering long-term-support for RHEL 7 is ending very soon. A workaround is to `kubectl exec` into an instance-manager pod and execute `fsck.ext4` there.

**Comment by roger-ryao** [comment]
**Verified on master-head 20231206**

- website master https://github.com/longhorn/website/commit/41f43dceb0b1c0dc1367a104a60384eb7ffb0b25

**The test steps**

https://github.com/longhorn/longhorn/issues/6859#issuecomment-1751390438

**Result Passed**

- [x] require/doc : Checked documentation in https://github.com/longhorn/website/pull/783.
