### ISSUE TITLE
[QUESTION] Resizing PVC crashed with nil pointer error

### ISSUE THREAD

**Issue by zhangsir1211** [longhorn/longhorn#6869]
## Environment

 - Longhorn version:v1.2.6
 - Kubernetes version:v1.22.10+rke2r2
 - Node config
   - OS type and version :Ubuntu 20.04.1 LTS
   - Kernel version Linux 5.4.0-159-generic x86_64
   - CPU per node:32
   - Memory per node:80
   - Disk type ssd
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

## Additional context

When I try to resize  pvc-d36e5cf8-0209-4c42-8670-c81890b9f242 from 10G to 30G, I encounter the following error.Other pv resize also failed .
![image](https://github.com/longhorn/longhorn/assets/65700806/06f95cdc-7c58-47b2-8b60-c3f4b7a0268c)
![image](https://github.com/longhorn/longhorn/assets/65700806/c9958f4b-a16e-4a39-815e-bc7eeaff7da5)

**Comment by DamiaSan** [comment]
I see the Longhorn version you are using is quite old, have you tried with a newer version?
Moreover, could you provide further details like reproducing steps?
