### ISSUE TITLE
[INFRA] s390x image build failed due to iscsiadm missing from the host

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6891]
## What's the test to develop? Please describe

Please check the details at https://github.com/longhorn/longhorn-engine/pull/942#issue-1943946321. 

## Describe the items of the test development (DoD, definition of done) you'd like

Fix the drone runner issue, then rollback https://github.com/longhorn/longhorn-engine/pull/942 and backport the rollbacks to v1.5.x and 1.4.x branches.

**Comment by innobead** [comment]
@Anarkis Please help with this.

**Comment by Anarkis** [comment]
`open-isci` has been installed in `drone-pr` and `drone-publish`
```
rpm -qa | grep open-iscsi
open-iscsi-2.1.8-150500.44.1.s390x
```

Please, check if it's solved

**Comment by Anarkis** [comment]
Working on `drone-pr` https://drone-pr.longhorn.io/Anarkis/longhorn-engine/4/1/3
Testing on `drone-publish` instance
