### ISSUE TITLE
[BUG] [v1.4.4-rc1] Wrong image name in uninstall manifest(uninstall job)

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#6895]
## Describe the bug (🐛 if you encounter this issue)

When attempting to uninstall Longhorn v1.4.4-rc1, the uninstall pod failed to create due to an incorrect image name : `longhornio/longhorn-manager:vv1.4.4-rc1`
```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  36s                default-scheduler  Successfully assigned longhorn-system/longhorn-uninstall-dhdxp to ip-172-31-85-220
  Normal   Pulling    22s (x2 over 36s)  kubelet            Pulling image "longhornio/longhorn-manager:vv1.4.4-rc1"
  Warning  Failed     22s (x2 over 36s)  kubelet            Failed to pull image "longhornio/longhorn-manager:vv1.4.4-rc1": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/longhornio/longhorn-manager:vv1.4.4-rc1": failed to resolve reference "docker.io/longhornio/longhorn-manager:vv1.4.4-rc1": docker.io/longhornio/longhorn-manager:vv1.4.4-rc1: not found
```

https://github.com/longhorn/longhorn/blob/730d156f0a7309fcba553f56768e18789dfaed42/uninstall/uninstall.yaml#L109C8-L109C57

## To Reproduce

N/A

## Expected behavior

Use a correct image name
 
## Support bundle for troubleshooting

N/A

## Environment

N/A

## Additional context

N/A

**Comment by innobead** [comment]
Let's verify this using RC2.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn v1.4.x (longhorn `4dc7df`)

1. Deploy Longhorn v1.4.x
2. Create deployment, statefulset, volume form UI and attached
3. Setup backup target, create recurring job for backup, wait backup completed.
4. Uninstall Longhorn v1.4.x
```
kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/v1.4.x/uninstall/uninstall.yaml
kubectl get job/longhorn-uninstall -n longhorn-system -w
```
```
kubectl delete -f https://raw.githubusercontent.com/longhorn/longhorn/v1.4.x/deploy/longhorn.yaml
kubectl delete -f https://raw.githubusercontent.com/longhorn/longhorn/v1.4.x/uninstall/uninstall.yaml
```
5. Uninstall job completed. In the end, namespace `longhorn-system` cleaned , no `longhorbn.io` CRD remained.
