### ISSUE TITLE
[TEST] tests.test_basic.test_default_storage_class_syncup failed on SLES on 1.4.x (ARM)

### ISSUE THREAD

**Issue by nitendra-suse** [longhorn/longhorn#6913]
## Describe the tasks for the test
Test case tests.test_basic.test_default_storage_class_syncup  on [v1.4.4-rc1](https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-tests-sles-arm64/324/testReport/)

```
Error Message
kubernetes.client.exceptions.ApiException: (404) Reason: Not Found HTTP response headers: HTTPHeaderDict({'Audit-Id': '455a93fe-0144-4dc6-a2db-e154ae86a02d', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'b2b0cfa2-4dd5-4c0e-912a-b75d365c2f5d', 'X-Kubernetes-Pf-Prioritylevel-Uid': '9bfb869f-7aef-425e-a266-2524ef955301', 'Date': 'Mon, 16 Oct 2023 12:42:38 GMT', 'Content-Length': '244'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"storageclasses.storage.k8s.io \"longhorn\" not found","reason":"NotFound","details":{"name":"longhorn","group":"storage.k8s.io","kind":"storageclasses"},"code":404}
Stacktrace
core_api = <kubernetes.client.api.core_v1_api.CoreV1Api object at 0xffff8a2ac310>
request = <FixtureRequest for <Function test_default_storage_class_syncup>>
```

## Additional context

NA

**Comment by yangchiu** [comment]
@nitendra-suse The content of this ticket is wrong. It's about `test_aws_iam_role_arn`. Could you help to correct it? 

Could you also help to do some investigation on why it failed? It would be more helpful since the error message doesn't provide much information.

**Comment by nitendra-suse** [comment]
> @nitendra-suse The content of this ticket is wrong. It's about `test_aws_iam_role_arn`. Could you help to correct it?

Corrected heading.
