### ISSUE TITLE
[BUG] The README.md in `longhorn-manager` is outdated

### ISSUE THREAD

**Issue by votdev** [longhorn/longhorn#6914]
## Describe the bug (🐛 if you encounter this issue)

The README.md is not up-to-date and contains information that are not helpful anymore.

E.g. the `Deployment` section contains is mentioning the `kubectl create -Rf deploy/install` command which points to a directory which does not exist in the GH repository. It seems it exist in the `longhorn` repository now.

But even then it is not helpful, because the subdirectory `/deploy/install/` does not exist. The same applies to the uninstallation, the directory `/deploy/uninstall/` does not exist either.

Additionally it would be helpful to mention what the outcome of the `make` in the `Build` section is.

## To Reproduce

Go to https://github.com/longhorn/longhorn-manager.

## Expected behavior

The documentation is up-to-date to support new users and give them the necessary information.

**Comment by innobead** [comment]
Suggest checking other repos as well and creating corresponding tickets for them.

**Comment by mantissahz** [comment]
README.md has been updated.

Hi @votdev,
Feel free to reopen if you have any concerns.
