### ISSUE TITLE
[QUESTION] volume degrade on same node

### ISSUE THREAD

**Issue by DamiaSan** [longhorn/longhorn#6925]
### Discussed in https://github.com/longhorn/longhorn/discussions/6885

<div type='discussions-op-text'>

<sup>Originally posted by **iamatulsingh** October 13, 2023</sup>
## Environment

 - Longhorn version: v1.5.1
 - Kubernetes version: 1.27
 - Node config
   - OS type and version Raspbian 
   - Kernel version 6.1.21
   - CPU per node: 4
   - Memory per node: 20 Gi
   - Disk type hdd
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal (Raspberry pi 4 8gb RAM)

## Additional context

I have k3s running on my Raspberry pi 4 (8gb memory and only 1 node cluster) . Whenever I'm trying to create a new volume with replicas more than 1, only 1 replicas is getting created and others are degraded and not creating. 

I have checked the cpu usage bit it was 20% only. 
Is it possible to have replicas on 1 node?
</div>

**Comment by c3y1huang** [comment]
Maybe related to [Replica Node Level Soft Anti-Affinity](https://longhorn.io/docs/1.5.3/references/settings/#replica-node-level-soft-anti-affinity) setting.
