### ISSUE TITLE
[BUG] longhorn-manager sometimes shows "connection error" messages

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6934]
## Describe the bug (🐛 if you encounter this issue)

longhorn-manager sometimes shows "connection error" messages. 8501 is the proxy server's port.
Not sure if it is a bug or it can introduce any impact, so create a ticket for tracking it. 
```
W1020 04:24:21.948080       1 logging.go:59] [core] [Channel #4063 SubChannel #4064] grpc: addrConn.createTransport failed to connect to {
  "Addr": "10.42.67.102:8501",
  "ServerName": "10.42.67.102:8501",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null
}. Err: connection error: desc = "error reading server preface: read tcp 10.42.67.99:42112->10.42.67.102:8501: use of closed network connection"
```

## Environment

 - Longhorn version: v1.5.1 and master
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

**Comment by derekbit** [comment]
The issue happens since https://github.com/longhorn/longhorn-manager/commit/467254b8821a3667dfb38b6e05deb8e6be53bfdb.
Don't see any issue currently. Will investigate it later.

**Comment by derekbit** [comment]
cc @ejweber

**Comment by ejweber** [comment]
No clue so far. The log is from google/golang..org/grpc, which did not itself change versions in the linked commit.

https://github.com/grpc/grpc-go/blob/2997e84fd8d18ddb000ac6736129b48b3c9773ec/clientconn.go#L1292
https://github.com/grpc/grpc-go/blob/2997e84fd8d18ddb000ac6736129b48b3c9773ec/internal/channelz/logging.go#L59

Maybe something about the way logging is wired up changed? It looks like those logs are somewhat outside of our control, as we do not output them directly and they do not follow any of our logging conventions.

How did you trace the issue back to https://github.com/longhorn/longhorn-manager/commit/467254b8821a3667dfb38b6e05deb8e6be53bfdb?

**Comment by derekbit** [comment]
> How did you trace the issue back to https://github.com/longhorn/longhorn-manager/commit/467254b8821a3667dfb38b6e05deb8e6be53bfdb?

Reverted the commit and tested it.

> It looks like those logs are somewhat outside of our control, as we do not output them directly and they do not follow any of our logging conventions.

You are right, the logs are not from longhorn-manager and, at least, I don't see any error in longhorn-manager when the message are printed. I don't have any clue for now.

**Comment by derekbit** [comment]
Close because the connection leak is fixed.

**Comment by Ripolin** [comment]
Hi @derekbit, on which version of longhorn this issue is fixed ?
