### ISSUE TITLE
[IMPROVEMENT] High memory consumption of longhorn-manager pods since Longhorn v1.5

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6936]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Since Longhorn v1.5, the conversion webhook, admission webhook and recovery backend services are merged into longhorn-manager pods because of the consideration of service availability https://github.com/longhorn/longhorn/issues/5590.

The memory usages of 1000 RWO volumes on a 3-node cluster before and after merging the services are  

- Before merging the services
   - longhorn-manger pod: 320 MiB
   - conversion webhook pod: 40 MiB
   - admission webhook pod: 150 MiB
   - recovery backend pod: 150 MiB
- After merging the services
   - longhorn-manger pod: 800 MiB (1.5 GiB ~ 2.0 GiB if there are 2000 RWO volumes)

The memory consumptions of longhorn-manager are significantly increased on **ALL Longhorn nodes** after the merge.

The ticket aims to reevaluate the tradeoff of the service availability and resources consumptions.

## Additional context

https://github.com/longhorn/longhorn/issues/6645
https://github.com/longhorn/longhorn/issues/6866

cc @shuo-wu @PhanLe1010  @ChanYiLin @innobead

**Comment by roger-ryao** [comment]
**Verified on master-head 20231127**

- longhorn master-head https://github.com/longhorn/longhorn/commit/57bf3edb1faa955ab077187a518d7be99ff38792
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/dd663887de73664ffc3296465a0a4b9d2ccbdfb6



**Test step**

https://github.com/longhorn/longhorn/issues/6936#issuecomment-1775396141

**Result Passed**

```console
NAME                                                CPU(cores)   MEMORY(bytes)  
longhorn-manager-6w82v                              1356m        249Mi           
longhorn-manager-dh9hm                              481m         135Mi           
longhorn-manager-mxphq                              818m         225Mi 

```
[supportbundle_8637bff4-b729-4e00-9a5d-4f57c1600079_2023-11-27T10-25-43Z.zip](https://github.com/longhorn/longhorn/files/13473930/supportbundle_8637bff4-b729-4e00-9a5d-4f57c1600079_2023-11-27T10-25-43Z.zip)
