### ISSUE TITLE
[INFRA] drone-pr|publish.longhorn.io has license issues

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6944]
## What's the test to develop? Please describe

See how to fix this. If having any issues, go check with @yangchiu . 

![image](https://github.com/longhorn/longhorn/assets/899492/f64b7cd6-7101-4b6e-a7a9-cd01629564e9)

**Comment by Anarkis** [comment]
Cleaned list of users for `drone-pr` and `drone-publish.longhorn.io`.

**Comment by innobead** [comment]
Why does this repeat happening?
