### ISSUE TITLE
[IMPROVEMENT] Add documents for Longhorn deployed with GitOps

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6948]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Currently, we only have documents for the installation using kubectl, helm and rancher in https://longhorn.io/docs/1.6.0/deploy/install/.

Longhorn Installation using GitOps such as **ArgoCD**, **Flux** and **Fleet** becomes popular. It would be nice if we could add documents for the GitOps tools.

**Comment by innobead** [comment]
It's better to have fleet as well.

**Comment by derekbit** [comment]
@yangchiu Please close the ticket if it is ready. Thanks.
