### ISSUE TITLE
[IMPROVEMENT] add build script to generate gRPC related code more convenient

### ISSUE THREAD

**Issue by Vicente-Cheng** [longhorn/longhorn#6973]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)
This is not associated with any feature.
Add some script to help develop more convenient.
Sometimes, we will modify/add rpc call, and we need to regenerate the RPC related code.
Like files under `integration/rpc/controller`, `integration/rpc/replica`, and `proto`
We have `generate_rpc.sh` to generate related code, but we need to install something required for it.
Doing that on the builder container (because we prepared all the requirements) would make the newcomer development more convenient.

## Describe the solution you'd like
Pass the related folder into the builder and add a script to call generate_rpc to get the result.

## Describe alternatives you've considered
None

## Additional context
After implementation, I could do something like the following.
(Do not require any gRPC packages on my local)
```
# After we add/modify gRPC call
$ make generate-rpc
... some build logs
integration/rpc/controller/controller_pb2.py | 200 ++++++++++---- integration/rpc/controller/controller_pb2_grpc.py | 17 ++ integration/rpc/replica/re
plica_pb2.py | 114 +++++++- integration/rpc/replica/replica_pb2_grpc.py | 17 ++ proto/ptypes/controller.pb.go | 317 ++++++++++++++++------ proto/ptype
s/replica.pb.go | 307 +++++++++++++++------
Please update GRPC generated code.

$ git status
On branch tmp-gen-rpc
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   integration/rpc/controller/controller_pb2.py
        modified:   integration/rpc/controller/controller_pb2_grpc.py
        modified:   integration/rpc/replica/replica_pb2.py
        modified:   integration/rpc/replica/replica_pb2_grpc.py
        modified:   proto/ptypes/controller.pb.go
        modified:   proto/ptypes/replica.pb.go

no changes added to commit (use "git add" and/or "git commit -a")
```
We could apply it easily w/o any extra package installed in the local environment.

**Comment by innobead** [comment]
ref: #7320 We need to review all gRPC & proto build in all repos later.
