### ISSUE TITLE
[BUG] [longhorn-engine] [s390x] intermittent fail pipeline on build step

### ISSUE THREAD

**Issue by Anarkis** [longhorn/longhorn#6975]
## Describe the bug (🐛 if you encounter this issue)

Multiple pipelines are randomly failing on `build` step in `drone-pr` and `drone-publish` ( `longhorn.io`)

Output of the error:

```
_________________________ ERROR at setup of test_close _________________________

process_manager_client = <rpc.instance_manager.process_manager_client.ProcessManagerClient object at 0x3ffad8a03c8>

    @pytest.fixture
    def grpc_replica_client(process_manager_client):
        r = create_replica_process(process_manager_client, REPLICA_NAME)
    
        listen = get_process_address(r)
        c = ReplicaClient(listen)
>       return cleanup_replica(c)

core/conftest.py:50: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common/core.py:197: in cleanup_replica
    r = get_replica(grpc_client)
common/core.py:183: in get_replica
    raise(grpc_err)
common/core.py:180: in get_replica
    r = grpc_client.replica_get()
rpc/replica/replica_client.py:28: in replica_get
    return self.stub.ReplicaGet(empty_pb2.Empty()).replica
.tox/py3/lib/python3.6/site-packages/grpc/_interceptor.py:222: in __call__
    compression=compression)
.tox/py3/lib/python3.6/site-packages/grpc/_interceptor.py:257: in _with_call
    return call.result(), call
.tox/py3/lib/python3.6/site-packages/grpc/_channel.py:482: in result
    raise self
.tox/py3/lib/python3.6/site-packages/grpc/_interceptor.py:248: in continuation
    compression=new_compression)
.tox/py3/lib/python3.6/site-packages/grpc/_channel.py:701: in with_call
    return _end_unary_response_blocking(state, call, True, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

state = <grpc._channel._RPCState object at 0x3ffad8ab8d0>
call = <grpc._cython.cygrpc.SegregatedCall object at 0x3ffadcc9a48>
with_call = True, deadline = None

    def _end_unary_response_blocking(state, call, with_call, deadline):
        if state.code is grpc.StatusCode.OK:
            if with_call:
                rendezvous = _Rendezvous(state, call, None, deadline)
                return state.response, rendezvous
            else:
                return state.response
        else:
>           raise _Rendezvous(state, None, None, deadline)
E           grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
E           	status = StatusCode.UNAVAILABLE
E           	details = "Connection reset by peer"
E           	debug_error_string = "{"created":"@1698156096.796140700","description":"Error received from peer ipv4:127.0.0.1:10000","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Connection reset by peer","grpc_status":14}"
E           >

.tox/py3/lib/python3.6/site-packages/grpc/_channel.py:592: _Rendezvous
```
### Drone publish
Failed executions:
- https://drone-publish.longhorn.io/Anarkis/longhorn-engine/9/1/3
- https://drone-publish.longhorn.io/Anarkis/longhorn-engine/8/1/3
Succeeded executions:
- https://drone-publish.longhorn.io/Anarkis/longhorn-engine/10/1/3
- https://drone-publish.longhorn.io/Anarkis/longhorn-engine/6/1/3 

### Drone pr
Failed executions:
- https://drone-pr.longhorn.io/Anarkis/longhorn-engine/11/1/3
- https://drone-pr.longhorn.io/Anarkis/longhorn-engine/9/1/3
Succeeded executions:
- https://drone-pr.longhorn.io/Anarkis/longhorn-engine/7/1/3
- https://drone-pr.longhorn.io/Anarkis/longhorn-engine/10/1/3

## To Reproduce
Repo forked from https://github.com/longhorn/longhorn-engine/commits/master `95b3fb85c9a415167e076a803964656e356a9f20`

commented out all the `archs` that are not `s390x`, together with `publish` steps (in order to being able to run under `drone-publish` without any problem )
In this fork you can find the `.drone.yaml` https://github.com/Anarkis/longhorn-engine/commit/c911bd88d19e1bf70c4e44e9b8688e6d84d0abed?diff=split

## Expected behavior
Successful execution on both environments `drone-pr` and `drone-publish`. Same behaviour than the other `archs`

## Environment
Internal drone runners.

## Additional context
Please, keep in mind that recently the `s390x` team performed a infrastructure change on the runners. We need to discard if it's an issue related to that change or it's a new one.

Related to: https://github.com/longhorn/longhorn/issues/6891

**Comment by Anarkis** [comment]
In case that the team responsible want to test the code in `s390x` machines, there are two ways to proceed:

### scenario 1 ( full flow )
- fork repo, sync it with `drone-pr` and `drone-publish`
- modify `.drone.yaml` as https://github.com/Anarkis/longhorn-engine/commit/c911bd88d19e1bf70c4e44e9b8688e6d84d0abed?diff=split
- ping me for admin settings to enable the proper execution

### scenario 2
- request a new s390x machine with `ssh` access
This scenario does not assure the same environment that we have on the normal building servers. Nevertheless, If it's needed I could on that to match the requirements

**Comment by innobead** [comment]
@Anarkis feel free to self assign next time.

**Comment by Anarkis** [comment]
Highly related to https://github.com/harvester/harvester/issues/4642
Working on the permanent solution

**Comment by Anarkis** [comment]
The config of the new `s390x` runners differed from the previous one
`cpuplugd` was set on. But it did not work as expected, the number of `cpus` was not populated to the runners, allocating less resources to the runners and for that reason, increasing the execution time of the pipelines

Some background:
- https://github.com/moby/moby/issues/27453
- https://github.com/moby/moby/issues/40041
