### ISSUE TITLE
[IMPROVEMENT] Add option to specify max backup .blk file size

### ISSUE THREAD

**Issue by artur9010** [longhorn/longhorn#6977]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Currently looks like backups block size is limited to 2MB (2097815 bytes according to `rclone ls`) - longhorn makes a lot of small requests to s3 server making bills higher.

5 largest files from `rclone ls`:
```
  2097815 homelab-longhorn/backupstore/volumes/3a/7c/pvc-8dcf3b56-d51d-40c1-a58f-d2dc56c0c970/blocks/3e/7d/3e7dbfdb2ce5fc1f70b285d82f64880c8448f923a6710280f50bdc0aea93e4b2.blk
  2097815 homelab-longhorn/backupstore/volumes/3a/7c/pvc-8dcf3b56-d51d-40c1-a58f-d2dc56c0c970/blocks/64/60/64606d2bb1af0725aefedc848ed6c5b8abd69244b6c7540d8352abfe273955c0.blk
  2097815 homelab-longhorn/backupstore/volumes/3a/7c/pvc-8dcf3b56-d51d-40c1-a58f-d2dc56c0c970/blocks/79/2f/792f0e8f1f938adb8b28b59da2a8dc4ad02243f0a5009bd8c77fac410ee6a6b4.blk
  2097815 homelab-longhorn/backupstore/volumes/3a/7c/pvc-8dcf3b56-d51d-40c1-a58f-d2dc56c0c970/blocks/7e/52/7e523657abd76d7125528ecbe495f4e51a6dac3a6c111c9d307636fd44c71e65.blk
  2097815 homelab-longhorn/backupstore/volumes/3a/7c/pvc-8dcf3b56-d51d-40c1-a58f-d2dc56c0c970/blocks/e8/68/e868b0598c843f21382075d64942e870f5ba4091f1531e1c609d74beea7f0ccd.blk
```

According to amazon s3 pricing 1000 PUT requests in Ohio costs 0.005$ - https://aws.amazon.com/s3/pricing/
Storj which I'm using does not charge for api requests, but it charges for number of files stored in object storage.

## Describe the solution you'd like

Add option to specify max file size

**Comment by derekbit** [comment]
cc @innobead

**Comment by joshimoo** [comment]
REF https://github.com/longhorn/longhorn/issues/5215

**Comment by derekbit** [comment]
> REF #5215

Let's track the issue in #5215
