### ISSUE TITLE
[FEATURE] Allow kubectl drain to stop manually attached volumes

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#6978]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Users in https://github.com/longhorn/longhorn/issues/6552 requested the ability for a `kubectl drain` to supersede a UI attachment. If implemented, even if a volume was attached manually via the UI, Longhorn would detach it during a drain operation. Otherwise, the drain can never complete and the user cannot understand why.

Currently, the drain proceeds because the workload pods consuming volumes are evicted from the node. This eventually results in all engines shutting down. This new behavior would require a mechanism by which Longhorn itself decided to detach manually attached volumes.

The Longhorn behavior has always been to disallow Kubernetes from detaching manually attached volumes, so we would likely need a setting that controlled this behavior.

## Additional context

See https://github.com/longhorn/longhorn/issues/6552 for additional context.

**Comment by jsalatiel** [comment]
One visual icon on the webUI showing which volumes have been manually attached would also be a nice addition.

**Comment by innobead** [comment]
ref: https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `ae6b6a`) with test [steps](https://github.com/longhorn/longhorn/issues/6978#issuecomment-1842601683)

Both dynamic provisioned volume and UI created volume will become detached when the attached node is cordoned and setting `Detach Manually Attached Volumes When Cordoned ` is `True`.
