### ISSUE TITLE
UI: Text overflow when the label of backup recurring jobs is too long

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#699]
![Screen Shot 2019-08-27 at 12 04 02 PM](https://user-images.githubusercontent.com/47542419/63800920-07b5a200-c8c4-11e9-8039-12805014e08d.png)

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
  - create a volume, attache it to a node
  - in `Volume Details` page, scheduled a backup.
  - add a label to backup with key: `label1` and value: Random 512 characters, and click `Save`
  >> Expected result: label text is not overflowed.
  
![Screenshot from 2019-09-09 23-03-34](https://user-images.githubusercontent.com/18232258/64566384-2735db80-d356-11e9-8838-a2436145ef3d.png)
