### ISSUE TITLE
[TASK] Performance benchmark when using Storage network with or without a customized MTU setting

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6996]
## What's the task? Please describe

Have a performance benchmark for the below setups to compare with the result without the storage network.
- Storage network with the default MTU setting of the CNI. 
- The same as above, but with a customized MTU conforming to the underlying interface. 

## Additional context

- https://rancher-users.slack.com/archives/C01GKHKAG0K/p1697475642866539
- https://github.com/flannel-io/flannel/issues/1011#issuecomment-1460417460

cc @derekbit @shuo-wu @c3y1huang @longhorn/qa @ibrokethecloud

**Comment by innobead** [comment]
@yangchiu when working on this item, please consult with @c3y1huang if you need any help or discussion.

**Comment by yangchiu** [comment]
Test steps:
1. Create storage network test environment according to https://longhorn.github.io/longhorn-tests/manual/release-specific/v1.6.0/test-storage-network/ with instance type =  `c5d.2xlarge`, os = `sles 15-sp5`, longhorn version = `master-head (longhorn-manager 0258c74)`
2. Check the `mtu` size of `eth1` for each node, it's `9001`:
```
ip-10-0-1-156:~ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether 02:46:6b:df:ca:29 brd ff:ff:ff:ff:ff:ff
    altname enp0s5
    altname ens5
    inet 10.0.1.156/24 brd 10.0.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::46:6bff:fedf:ca29/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether 02:3c:f8:3b:12:07 brd ff:ff:ff:ff:ff:ff
    altname enp0s6
    altname ens6
    inet 10.0.2.41/24 brd 10.0.2.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::3c:f8ff:fe3b:1207/64 scope link 
       valid_lft forever preferred_lft forever
```
3. Setup storage network according to https://longhorn.github.io/longhorn-tests/manual/release-specific/v1.6.0/test-storage-network/. The `flannel mtu` is set to `1472`, which is not matched with the `mtu` of `eth1`:
```
ip-10-0-1-156:~ # cat /run/flannel/multus-subnet-192.168.0.0.env 
FLANNEL_NETWORK=192.168.0.0/16
FLANNEL_SUBNET=192.168.1.0/24
FLANNEL_MTU=1472
FLANNEL_IPMASQ=true
```

```
$ kubectl exec -it instance-manager-653005c2b70bb88b25b4516b7c5aec51 -n longhorn-system -- ip a
3: lhnet1@if3: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1472 qdisc noqueue state UNKNOWN group default 
    link/ether 02:3c:f8:3b:12:07 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.1.6/24 brd 192.168.1.255 scope global lhnet1
       valid_lft forever preferred_lft forever
    inet6 fe80::23c:f800:13b:1207/64 scope link 
       valid_lft forever preferred_lft forever
```
4. Run benchmark test
5. Adjust the `flannel mtu` to `9001`, which is matched with the `mtu` of `eth1`:
```
ip-10-0-1-189:~ # cat /run/flannel/multus-subnet-192.168.0.0.env 
FLANNEL_NETWORK=192.168.0.0/16
FLANNEL_SUBNET=192.168.3.0/24
FLANNEL_MTU=9001
FLANNEL_IPMASQ=true  
```

```
$ kubectl exec -it instance-manager-2c9938263f38b4d2dc1f7755d7e12852 -n longhorn-system -- ip a  
3: lhnet1@if3: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 9001 qdisc noqueue state UNKNOWN group default 
    link/ether 02:e6:1c:8b:6d:6b brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.3.8/24 brd 192.168.3.255 scope global lhnet1
       valid_lft forever preferred_lft forever
    inet6 fe80::2e6:1c00:18b:6d6b/64 scope link 
       valid_lft forever preferred_lft forever
```
6. Run benchmark test again
7. Compare the results:

Replica = 3 |   | IOPS |   | Bandwidth |   | Latency |  
-- | -- | -- | -- | -- | -- | -- | --
  |   | read | write | read | write | read | write
mtu = 1472 | rand | 27,393 | 15,420 | 900,392 | 161,801 | 316,906 | 328,429
  | seq | 43,388 | 26,121 | 797,857 | 164,222 | 315,424 | 329,037
mtu = 9001 | rand | 28,010 | 15,474 | 1,041,221 | 161,981 | 312,643 | 315,822
  | seq | 44,970 | 26,374 | 655,093 | 164,316 | 312,004 | 315,139
difference | rand | 2.25% | 0.35% | 15.64% | 0.11% | 1.35% | 3.84%
  | seq | 3.65% | 0.97% | -17.89% | 0.06% | 1.08% | 4.22%

Replica = 2 |   | IOPS |   | Bandwidth |   | Latency |  
-- | -- | -- | -- | -- | -- | -- | --
  |   | read | write | read | write | read | write
mtu = 1472 | rand | 28,351 | 16,066 | 724,305 | 161,983 | 302,038 | 303,043
  | seq | 44,887 | 27,779 | 662,624 | 164,375 | 305,812 | 304,008
mtu = 9001 | rand | 28,880 | 16,004 | 724,282 | 161,421 | 301,083 | 292,228
  | seq | 46,558 | 28,105 | 708,574 | 163,785 | 299,297 | 291,450
difference | rand | 1.87% | -0.39% | 0% | -0.35% | 0.32% | 3.57%
  | seq | 3.72% | 1.17% | 6.93% | -0.36% | 2.13% | 4.13%

Replica = 1 |   | IOPS |   | Bandwidth |   | Latency |  
-- | -- | -- | -- | -- | -- | -- | --
  |   | read | write | read | write | read | write
mtu = 1472 | rand | 29,253 | 16,588 | 362,190 | 161,777 | 279,834 | 260,128
  | seq | 46,085 | 28,138 | 370,177 | 163,970 | 214,593 | 259,075
mtu = 9001 | rand | 29,788 | 16,824 | 362,171 | 161,983 | 277,138 | 257,948
  | seq | 46,989 | 28,213 | 362,209 | 164,388 | 211,903 | 255,899
difference | rand | 1.83% | 1.42% | -0.01% | 0.13% | 0.96% | 0.84%
  | seq | 1.96% | 0.27% | -2.15% | 0.25% | 1.25% | 1.23%

**Comment by c3y1huang** [comment]
> 5\. Setup storage network according to https://longhorn.github.io/longhorn-tests/manual/release-specific/v1.6.0/test-storage-network/. The `flannel mtu` is set to `1472`, which is not matched with the `mtu` of `eth1`:
> 
> ```
> ip-10-0-1-156:~ # cat /run/flannel/multus-subnet-192.168.0.0.env 
> FLANNEL_NETWORK=192.168.0.0/16
> FLANNEL_SUBNET=192.168.1.0/24
> FLANNEL_MTU=1472
> FLANNEL_IPMASQ=true
> ```
> 
> ```
> $ kubectl exec -it instance-manager-653005c2b70bb88b25b4516b7c5aec51 -n longhorn-system -- ip a
> 3: lhnet1@if3: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1472 qdisc noqueue state UNKNOWN group default 
>     link/ether 02:3c:f8:3b:12:07 brd ff:ff:ff:ff:ff:ff link-netnsid 0
>     inet 192.168.1.6/24 brd 192.168.1.255 scope global lhnet1
>        valid_lft forever preferred_lft forever
>     inet6 fe80::23c:f800:13b:1207/64 scope link 
>        valid_lft forever preferred_lft forever
> ```

If I understand correctly, we are benchmarking 2 scenarios:
1. Storage network same as the default Kubernetes CNI MTU.
1. Storage network same as the host network interface.

The `1472` found in `/run/flannel/multus-subnet-192.168.0.0.env` is a custom config created specifically for testing the storage-network. For scenario 1, the storage network's MTU should be aligned with the default Kubetnetes CNI config file, an example path would be `/run/flannel/subnet.env` (pipeline k3s cluster).

**Comment by yangchiu** [comment]
> > 5. Setup storage network according to https://longhorn.github.io/longhorn-tests/manual/release-specific/v1.6.0/test-storage-network/. The `flannel mtu` is set to `1472`, which is not matched with the `mtu` of `eth1`:
> > ```
> > ip-10-0-1-156:~ # cat /run/flannel/multus-subnet-192.168.0.0.env 
> > FLANNEL_NETWORK=192.168.0.0/16
> > FLANNEL_SUBNET=192.168.1.0/24
> > FLANNEL_MTU=1472
> > FLANNEL_IPMASQ=true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > $ kubectl exec -it instance-manager-653005c2b70bb88b25b4516b7c5aec51 -n longhorn-system -- ip a
> > 3: lhnet1@if3: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1472 qdisc noqueue state UNKNOWN group default 
> >     link/ether 02:3c:f8:3b:12:07 brd ff:ff:ff:ff:ff:ff link-netnsid 0
> >     inet 192.168.1.6/24 brd 192.168.1.255 scope global lhnet1
> >        valid_lft forever preferred_lft forever
> >     inet6 fe80::23c:f800:13b:1207/64 scope link 
> >        valid_lft forever preferred_lft forever
> > ```
> 
> If I understand correctly, we are benchmarking 2 scenarios:
> 
>     1. Storage network same as the default Kubernetes CNI MTU.
> 
>     2. Storage network same as the host network interface.
> 
> 
> The `1472` found in `/run/flannel/multus-subnet-192.168.0.0.env` is a custom config created specifically for testing the storage-network. When setting up for scenario 1, the storage network's MTU should be aligned with the default Kubetnetes CNI config file, an example path would be `/run/flannel/subnet.env` (pipeline k3s cluster).

Updated https://github.com/longhorn/longhorn/issues/6996#issuecomment-1822197680 to use value in `/run/flannel/subnet.env` instead of `1472`. Thanks for the clarification!

**Comment by yangchiu** [comment]
The corresponding network interface bandwidth is:
```
$ aws ec2 describe-instance-types --filters "Name=instance-type,Values=c5d.2xlarge" --query "InstanceTypes[].[InstanceType, NetworkInfo.NetworkPerformance]" --output table
-------------------------------------
|       DescribeInstanceTypes       |
+--------------+--------------------+
|  c5d.2xlarge |  Up to 10 Gigabit  |
+--------------+--------------------+
```
