### ISSUE TITLE
[BUG] missing description in support-bundle metadata.yaml

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#6997]
## Describe the bug (🐛 if you encounter this issue)

Missing description in support-bundle metadata.yaml

## To Reproduce

See https://github.com/harvester/harvester/issues/4630

## Expected behavior

See https://github.com/harvester/harvester/issues/4630

## Support bundle for troubleshooting

`None`

## Environment

`None`

## Additional context

https://github.com/longhorn/longhorn-manager/pull/2270#issuecomment-1784561292

**Comment by innobead** [comment]
@c3y1huang next time, go ahead to add to the milestone.

**Comment by roger-ryao** [comment]
**Verified on master-head 20231123**

- longhorn master-head https://github.com/longhorn/longhorn/commit/57bf3edb1faa955ab077187a518d7be99ff38792
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/3a66afaa7ec086f7f6ec6ebb10fd6797ac30830d
- support-bundle-kit master-head https://github.com/rancher/support-bundle-kit/commit/d8e9522dddecf543a6cc7bd3e970c4a2f53e298d

**Result Passed**

1. We could obtain the description in the support-bundle metadata.yaml.
![Screenshot_20231123_181201](https://github.com/longhorn/longhorn/assets/104337648/1c41642a-ac96-497c-b159-57935ae3943e)
