### ISSUE TITLE
[BUG] Errors found by static checker in volume controller

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7009]
## Describe the bug (🐛 if you encounter this issue)

Related to the scope of variable `err`

https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go#L3878
https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go#L3887

## Environment

 - Longhorn version: master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

**Comment by innobead** [comment]
@derekbit can you elaborate more info about this issue?

**Comment by derekbit** [comment]
The scope of the `err` is only in the defer function, so `errors.Wrapf(err, ...)` is unable to pass to the returned error of the funciton.

```
	defer func() {
		if !revertRequired {
			return
		}

		log.Warnf("The migration engine or all migration replicas crashed, will clean them up now")

		currentEngine, err := c.getCurrentEngineAndCleanupOthers(v, es)
		if err != nil {
			err = errors.Wrap(err, "failed to get the current engine and clean up others during the migration revert")
			return
		}

		for _, r := range rs {
			if r.Spec.EngineName == currentEngine.Name {
				continue
			}
			if err := c.deleteReplica(r, rs); err != nil {
				err = errors.Wrapf(err, "failed to delete the migration replica %v during the migration revert", r.Name)
				return
			}
		}
	}()
```

**Comment by innobead** [comment]
@m-ildefons Please help with this.

**Comment by m-ildefons** [comment]
Backport for v1.5.x is needed. v1.4.x does not have this problem.
I ran the static checker `staticcheck` (https://staticcheck.dev/docs/running-staticcheck/cli/) and it found more issues in various other places of the code.
Do we perhaps want to clean up our code base as a whole and run that checker against it as part of the CI pipeline?

**Comment by innobead** [comment]
> Backport for v1.5.x is needed. v1.4.x does not have this problem. I ran the static checker `staticcheck` ([staticcheck.dev/docs/running-staticcheck/cli](https://staticcheck.dev/docs/running-staticcheck/cli/)) and it found more issues in various other places of the code. Do we perhaps want to clean up our code base as a whole and run that checker against it as part of the CI pipeline?

Sounds good to me. Let's have another ticket for that.

**Comment by innobead** [comment]
This is about static checks, so there is no QA required.
