### ISSUE TITLE
[FEATURE] Support instance-manager pod for v2 volumes on selected nodes

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7015]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

In a large cluster, both powerful nodes and low-spec nodes exist, and there are lots of kinds of applications running inside it. Currently, the v2-data-engine enables the instance-manager pod for v2 volumes on all Longhorn nodes regardless of machines' specs. To address the issue, the v2 data engines can be activated through the global setting `v2-dat-engine` and per-node labels, annotations, or spec fields.

The ticket can be extended to instance-manager pod for v1 volumes in the future.

## Additional context

cc @shuo-wu @innobead

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `970ba4`) 

Following test [steps](https://github.com/longhorn/longhorn/issues/7015#issuecomment-1808553645), did not encounter problem, close this ticket, thank you.

**Comment by khushboo-rancher** [comment]
@chriscchien Some priority 1/2 scenarios that can be further tested:

Prerequisite: Have a v1 volume with three replicas and data checksum computed.
1. Disable all the node for v2 data engine, create a v2 volume. The volume should show unscheduling, Delete the `v2 disable` label. Verify the volume become schedulable.
2. Create a v2 volume, add `v2 disable` label to one of the replica node. Crash the IM on replica node. Check the replica behavior.
3. Create a v2 volume, add `v2 disable` label to one of the volume attached node. Crash the IM on attached node. Check the replica behavior.
4. Create a v2 volume with 2 replicas. Trigger the replica rebuilding. When the replica is progress, add the `v2 disable` label to the rebuilding replica node`. Verify that the replica finishes successfully.

v1 volume should not be impacted in any of the above scenarios.

**Comment by chriscchien** [comment]
> @chriscchien Some priority 1/2 scenarios that can be further tested:
> 
> Prerequisite: Have a v1 volume with three replicas and data checksum computed.
> 
> 1. Disable all the node for v2 data engine, create a v2 volume. The volume should show unscheduling, Delete the `v2 disable` label. Verify the volume become schedulable.
> 2. Create a v2 volume, add `v2 disable` label to one of the replica node. Crash the IM on replica node. Check the replica behavior.
> 3. Create a v2 volume, add `v2 disable` label to one of the volume attached node. Crash the IM on attached node. Check the replica behavior.
> 4. Create a v2 volume with 2 replicas. Trigger the replica rebuilding. When the replica is progress, add the `v2 disable` label to the rebuilding replica node`. Verify that the replica finishes successfully.
> 
> v1 volume should not be impacted in any of the above scenarios.

Hi @khushboo-rancher,
1. v2 volume become schedulable after remove the label or set label to false
2. The replica on crashed IM gone, volume become degraded, after remove label or set label to false then do offline rebuilding, all replicas ready and data intact.
3. The replica on crashed IM gone, volume try to reattach to the same node but stuck at attaching, after remove label or set label to false, volume attached, data intact.
4. Following steps, the replica rebuild success.

And after above tests complete, v1 volume healthy, data intact

**Comment by innobead** [comment]
@chriscchien let's automate these cases it they haven't been implemented. Create a ticket for it.
