### ISSUE TITLE
[BUG] UI: The action menu handler should stop event propagation

### ISSUE THREAD

**Issue by votdev** [longhorn/longhorn#7032]
## Describe the bug (🐛 if you encounter this issue)

Right now all handler that process action menu clicks do not stop the event propagation.

This has the consequence that this click is interpreted by the action menu and the table row below it. This means unnecessary and possibly incorrect work as in this case the click should only be processed by the action menu.

Examples:
- https://github.com/longhorn/longhorn-ui/blob/master/src/routes/host/HostActions.js#L9
- https://github.com/longhorn/longhorn-ui/blob/master/src/routes/volume/VolumeActions.js#L64
- https://github.com/longhorn/longhorn-ui/blob/master/src/routes/engineimage/EngineImageActions.js#L8

## Expected behavior

The handler should call `event.domEvent.stopPropagation()` to stop that event from being processed from other UI components.

## Environment
LH UI 1.6-dev

**Comment by innobead** [comment]
@votdev Remember to add issues to the upcoming feature release, it's 1.6.0 now.
