### ISSUE TITLE
[TEST] Implement a more efficient method for distinguishing items within the robot variable list

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#7034]
## What's the test to develop? Please describe

We currently access the test variables in the lists using the workload index. We need a more organized approach to distinguish between the individual items within these lists.

Also, we are passing variables around by setting them with robot keywords. After implementing the improvement should also reduce the need to use robot keyword for variable assignment.

## Describe the tasks for the test

- Introduce shared variable handling.

## Additional context

https://github.com/longhorn/longhorn-tests/pull/1577#discussion_r1380171801

**Comment by yangchiu** [comment]
@c3y1huang If not sure what should be taken into consideration. The following test cases can be referenced:

`test_settings.py::test_setting_concurrent_rebuild_limit`
`test_basic.py::test_snapshot`
`test_basic.py::test_restore_inc`
`test_basic.py::test_backup_volume_list`

**Comment by innobead** [comment]
cc @longhorn/qa
