### ISSUE TITLE
[IMPROVEMENT] Allow deployment of Prometheus ServiceMonitor with the Longhorn helm chart

### ISSUE THREAD

**Issue by yardenshoham** [longhorn/longhorn#7041]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

When deploying Longhorn with helm, to enable metric collection we have to manually apply a ServiceMonitor object. 

## Describe the solution you'd like

This object is fairly simple so we can add a value in the Longhorn helm chart to include it.

## Describe alternatives you've considered

Keep the current state, forcing helm users that want metrics using the Prometheus to manually apply the ServiceMonitor.

## Additional context

Bitnami uses this approach with their helm charts,

Pull request: https://github.com/longhorn/longhorn/pull/7042

**Comment by innobead** [comment]
@mantissahz Please update this issue correctly and move forward to QA. The related PR should be https://github.com/longhorn/longhorn/pull/6157.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn `bac644`)

Steps
1. Install [prometheus-operator](https://github.com/prometheus-operator/prometheus-operator) release-0.70
2. Enable `metrics.serviceMonitor.enabled` and then Fresh install by Helm.
3. Setup the Prometheus (https://longhorn.io/docs/1.5.3/monitoring/prometheus-and-grafana-setup) without `ServiceMonitor` section and use namesapce **longhorn-system**
4. Prometheus worked well
![image](https://github.com/longhorn/longhorn/assets/73337386/42c9c7d5-0130-41f4-8cc0-2b06631f7ae3)

**Comment by innobead** [comment]
@mantissahz let's backport this to 1.5 and 1.4.
