### ISSUE TITLE
[BUG] `allow-collecting-longhorn-usage-metrics` setting is missing from chart settings

### ISSUE THREAD

**Issue by yardenshoham** [longhorn/longhorn#7050]
## Describe the bug (🐛 if you encounter this issue)

The chart is missing the `allow-collecting-longhorn-usage-metrics` setting. We should add it.

- https://github.com/longhorn/longhorn/pull/7049

## Additional context
cc @innobead @longhorn/qa @c3y1huang

**Comment by ChanYiLin** [comment]
Hi @yardenshoham 
Thanks for your contribution
After the setting is added to the helm chart, we can then further update the content in our website.
Could you help to create a PR to this Repo: https://github.com/longhorn/website 
1. paste the helm values table you generated in README to this [page](https://github.com/longhorn/website/blob/master/content/docs/1.6.0/references/helm-values.md)
2. Add the description of the setting to this [page](https://github.com/longhorn/website/blob/master/content/docs/1.6.0/references/settings.md)

Thanks!

**Comment by yardenshoham** [comment]
I have a branch with 1 done, I'm not sure where exactly 2 should go because it's a default setting

**Comment by ChanYiLin** [comment]
yes now we have to update the content in our website so users will see the new setting when they refer to our website
you can go to this repo: https://github.com/longhorn/website
and create a PR to update the helm values table you generated to this place place:https://github.com/longhorn/website/blob/master/content/docs/1.6.0/references/helm-values.md

**Comment by yardenshoham** [comment]
Done https://github.com/longhorn/website/pull/806

**Comment by ChanYiLin** [comment]
Now our QA team will test the helm chart and close the issue if it all works fine.
Thanks for your contribution again!

**Comment by roger-ryao** [comment]
**Verified on master-head 20231205**

- longhorn master-head https://github.com/longhorn/longhorn/commit/6ad473c1b68da13da8337489eefcc5cab26dd891

**Result Passed**

- [x] require/chart :  Installed Longhorn using Helm chart and modified `allowCollectingLonghornUsageMetrics` to `false`, and it took effect.
- [x] require/doc : Checked documentation in https://github.com/longhorn/website/pull/806
