### ISSUE TITLE
[BUG] Adding a second node to longhorn fails.

### ISSUE THREAD

**Issue by aljabertareq** [longhorn/longhorn#7054]
## Describe the bug (🐛 if you encounter this issue)

Longhorn is not attaching workload to volumes after adding a second node.

## To Reproduce

1- Add a second node to an installed K8s cluster with longhorn 1.4.2.

Actual results:

Volume Attachment failure for both nodes 

## Environment

Ubuntu 20.04.0 LTS
K8s cluster 
Longhorn 1.4.2

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

**Comment by aljabertareq** [comment]
@derekbit can you please help?

**Comment by innobead** [comment]
@aljabertareq Please provide the support bundle. Thanks.

**Comment by aljabertareq** [comment]
@derekbit support bundle unable to download

**Comment by derekbit** [comment]
@aljabertareq Any error message when downloading the support bundle?

**Comment by aljabertareq** [comment]
@derekbit I will be uploading the support bundle but notice that we turned off the second node (NotReady) to make node 1 work. So "NotReady" or any flag you see there was put by us after trying multiple times to make both nodes work.

**Comment by Abdulrahman-Tayara** [comment]
@derekbit - Here is the Longhorn bundle, you will see in the bundle that the second node is down, we did that to stop the scheduling on the second node but you can see the history for the failures.
 
 [Longhorn Bundle](https://drive.google.com/file/d/1hSAwnEFCyLTvrER-DNOL9sy_fw3YORWa/view?usp=sharing)

**Comment by derekbit** [comment]
@andyjeffries @aljabertareq 
I saw the node1's longhorn-manager said "node node2 is not ready and couldn't attach volume ...".
Can you provide your steps of adding the node2?

**Comment by Abdulrahman-Tayara** [comment]
@derekbit  - Hi Derek, We're utilizing Ansible for the installation of Kubernetes (k8s). To add the second node, we made modifications to the 'nodes.yml' file by including the IP addresses of the new node and subsequently applied the changes. The second node functioned properly, and the k8s scheduler successfully assigned some workloads to it. However, we encountered an issue with Volume Mounting.

**Comment by derekbit** [comment]
@abhi1693 

I see. If you are available, could you help try
- Ensure **Kubernetes** node `node2` ready by `kubectl -n get nodes`
- Check the Longhorn node status by `kubectl -n longhorn-system get nodes.longhorn.io`. Make sure the two **Longhorn** nodes are ready.
- Check the **Longhorn** nodes' disk status (`node.status.diskStatus`)

If both the Kubernetes and Longhorn nodes and disks are ready, create a pod with a pvc ([manifest](https://raw.githubusercontent.com/longhorn/longhorn/master/examples/pod_with_pvc.yaml)) and see if it can succeed. If no, please send us the support bundle.

**Comment by abhi1693** [comment]
@derekbit I think you meant to tag someone else. I've no knowledge of the bug

**Comment by innobead** [comment]
This issue has been resolved by the reporter due to an env issue about swapoff enabled.

**Comment by derekbit** [comment]
@abhi1693 
Yes, sorry for the mistagging.
