### ISSUE TITLE
[BUG] `backing-image-manager-` hostPath selection exception

### ISSUE THREAD

**Issue by ElectroshockGuy** [longhorn/longhorn#7062]
## Describe the bug (🐛 if you encounter this issue)

Hi,team

I encountered an accidental situation where the backing-image-manager hostPath mount was incorrect. It selected a block device, and it also used the hostPath method to mount.

> `/dev/zvol/data/spdk` is used as the backend aio device for the v2 Data engine.
![image](https://github.com/longhorn/longhorn/assets/145109272/2448ffd1-ae9c-434c-9c78-60db2a0a17f3)

This situation can lead to the error "open /data/longhorn-disk.cfg: not a directory."

```shell
master01 [~]$ kubectl logs -f -n longhorn-system backing-image-manager-f22c-8619
time="2023-11-03105:44:56Z" level=fatal msg="Error running start command" error="cannot find disk config file /data/longhorn-disk.cfg: open /data/longhorn-disk.cfg: not a directory'
```

## To Reproduce

Not easy to reproduce.

## Expected behavior

In my cluster, the correct behavior is similar to this, using a disk with a "filesystem" diskType for hostPath usage.
> `/var/lib/longhorn` is of the "filesystem" type in disks configuration on Longhorn nodes.

![image](https://github.com/longhorn/longhorn/assets/145109272/288219a1-689e-4c91-a269-65ed35b5661d)

```shell
kubectl -n longhorn-system get nodes.longhorn.io  master02 -oyaml
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  creationTimestamp: "2023-08-18T08:54:48Z"
  finalizers:
  - longhorn.io
  generation: 35
  name: master02
  namespace: longhorn-system
  resourceVersion: "110407551"
  uid: 6bb7dd0e-4a7b-4851-bd46-5fdccf08d611
spec:
  allowScheduling: true
  disks:
    default-disk-1c6ba2de889247ea:
      allowScheduling: true
      diskType: filesystem
      evictionRequested: false
      path: /var/lib/longhorn/
      storageReserved: 3195479860838
      tags: []
    disk-spdk-zvol:
      allowScheduling: true
      diskType: block
      evictionRequested: false
      path: /dev/zvol/data/spdk
      storageReserved: 0
      tags:
      - spdk
```

## Environment

 - Longhorn version: 1.5.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 2
   - Number of worker node in the cluster: 0
 - Node config
   - OS type and version: k3os
   - Kernel version: 5.15.0-60-generic 
   - CPU per node:  16
   - Memory per node: 20
   - Disk type(e.g. SSD/NVMe/HDD): HDD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 42
 - Impacted Longhorn resources: 
   - Volume names:

## Additional context

The configuration of the "disks" for all Longhorn nodes.

<img width="662" alt="image" src="https://github.com/longhorn/longhorn/assets/145109272/26773ab0-f87e-4a31-af42-4618b9084c06">

`/dev/zvol/data/spdk` is used as the backend block storage for the v2 data engine.

```shell
instance-manager-b85b4301fc13bccc306d165f3e4f57c7:/ # go-spdk-helper aio get disk-spdk-zvol
{
        "id": 2405,
        "jsonrpc": "2.0",
        "method": "bdev_get_bdevs",
        "params": {
                "name": "disk-spdk-zvol"
        }
}
{
        "id": 2405,
        "jsonrpc": "2.0",
        "result": [
                {
                        "aliases": [
                                "b166c600-ceeb-44af-b8eb-55bdc0588b71"
                        ],
                        "assigned_rate_limits": {
                                "r_mbytes_per_sec": 0,
                                "rw_ios_per_sec": 0,
                                "rw_mbytes_per_sec": 0,
                                "w_mbytes_per_sec": 0
                        },
                        "block_size": 4096,
                        "claim_type": "read_many_write_one",
                        "claimed": true,
                        "driver_specific": {
                                "aio": {
                                        "block_size_override": true,
                                        "filename": "/host/dev/zvol/data/spdk",
                                        "readonly": false
                                }
                        },
                        "name": "disk-spdk-zvol",
                        "num_blocks": 268435456,
                        "product_name": "AIO disk",
                        "supported_io_types": {
                                "abort": false,
                                "compare": false,
                                "compare_and_write": false,
                                "flush": true,
                                "nvme_admin": false,
                                "nvme_io": false,
                                "read": true,
                                "reset": true,
                                "unmap": false,
                                "write": true,
                                "write_zeroes": true
                        },
                        "uuid": "b166c600-ceeb-44af-b8eb-55bdc0588b71",
                        "zoned": false
                }
        ]
}
```

```shell
instance-manager-b85b4301fc13bccc306d165f3e4f57c7:/ # ls -l $(readlink -f /host/dev/zvol/data/spdk)
brw-rw---- 1 root 6 230, 128 Nov  7 09:21 /host/dev/zd128
```

**Comment by derekbit** [comment]
cc @ChanYiLin

**Comment by innobead** [comment]
This should be related to the v2 data engine, so probably need to ignore block disk devices first? However, this also means we still need to have FS disks to save backing images, right?

**Comment by derekbit** [comment]
@innobead 
I think backing-image-manager needs to support both filesystem- and block-type disks.  backing images for v2 volumes are stored in block-type disk.

**Comment by innobead** [comment]
Does it mean we need to allocate a logical volume (thin-provisioning) in the logical volume group of that block device and save the image there? Then, when creating another logical volume, we will mount the logical volume storing the backing image to create a snapshot based on it? We need to create another feature issue for v2 implementation.

As you mentioned, we the backing imager should differentiate it or simply ignore the block disk in 1.5.x. WDYT?

**Comment by innobead** [comment]
ref: https://github.com/longhorn/longhorn/issues/6341

**Comment by derekbit** [comment]
> Does it mean we need to allocate a logical volume (thin-provisioning) in the logical volume group of that block device and save the image there? Then, when creating another logical volume, we will mount the logical volume storing the backing image to create a snapshot based on it? We need to create another feature issue for v2 implementation.

Yes.

> As you mentioned, we the backing imager should differentiate it or simply ignore the block disk in 1.5.x. WDYT?

I'm fine either simply ignoring block disks or differentiate it. We can push off the task and handle it when working on https://github.com/longhorn/longhorn/issues/6341.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `27101b`) with test [steps](https://github.com/longhorn/longhorn/issues/7062#issuecomment-1805491137)

When longhorn only have block disks available, create backing image(below 3 ways) will not success and can see  related logs in longhorn-manager pod.
- Download from URL
- Upload from local
- Exported from v2 volume
```
time="2023-12-13T02:42:29Z" level=error msg="Dropping Longhorn backing image out of the queue" func=controller.handleReconcileErrorLogging file="utils.go:72" BackingImage=longhorn-system/test-bi controller=longhorn-backing-image error="failed to sync backing image for longhorn-system/test-bi: unable to get a ready node disk" node=ip-172-31-34-92
```
