### ISSUE TITLE
[FEATURE] Support periodic or on-demand full backups to enhance backup reliability

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7070]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

In the existing Longhorn backup system, the initial backup is a full backup, while subsequent backups are incremental. If any block becomes corrupted, all backup revisions relying on that block will also be corrupted as well. An approach to address the issue might perform a full backup after every N incremental backups. This method can decreases the likelihood of backup corruption, enhancing the overall reliability of the backup process.

Current implementation
![image](https://github.com/longhorn/longhorn/assets/12527233/38aa9fd1-2dd5-4175-9460-8941c548eecc)

A possible solution
![image](https://github.com/longhorn/longhorn/assets/12527233/3b4350b1-7d4a-4812-ad39-358279242d71)

Ref: https://www.architecting.it/blog/incrementals-forever-or-synthetic-fulls/

**Comment by derekbit** [comment]
I would highlight the feature that can help improve the resilience to the silent corruption of a backup server. 
cc @innobead

**Comment by derekbit** [comment]
The current implementation is adding a `backup-mode` label within a recurring job. User must establish two separate recurring jobs for incremental and full backups to regulate the frequency of full backups. This method complicates management.

However, following discussions with @ChanYiLin and @c3y1huan, we can record the frequency, period, or count within recurring job or backup volume, and the solution could simplify the configuration, requiring only a single recurring job.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn `e5a1b5`) with test [steps](https://github.com/longhorn/longhorn/issues/7070#issuecomment-2008928608)

Waiting [doc](https://github.com/longhorn/website/pull/933) and UI [PR](https://github.com/longhorn/longhorn/issues/8291) mergerd then close this ticket.

**Comment by ChanYiLin** [comment]
Hi @chriscchien 
both doc and UI PR are merged.
Thanks

**Comment by derekbit** [comment]
Updated in https://github.com/longhorn/website/pull/951
