### ISSUE TITLE
[IMPROVEMENT] Add PVC namespace to longhorn_volume metrics

### ISSUE THREAD

**Issue by antoninferrand** [longhorn/longhorn#7077]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

In [[IMPROVEMENT] Add pvc name to longhorn_volume metrics](https://github.com/longhorn/longhorn/issues/5297) you added the PVC name to the volume metrics, however to entirely define a PVC we also need the namespace (multiple PVC can have the same name if they are in different namespaces).

## Describe the solution you'd like

Add a "namespace" label to all longhorn_volume metrics, and fill it with the PVC namespace from `v.Status.KubernetesStatus.Namespace`.

## Describe alternatives you've considered

n/a

## Additional context

n/a

## PRs

As the change is very similar to what you did a few months ago, I created the same PRs, let me know if this is a mistake.
- [feat(metrics): add pvc namespace to volume metrics](https://github.com/longhorn/longhorn-manager/pull/2284)
- [test(metrics): PVC namespace included in volume metrics](https://github.com/longhorn/longhorn-tests/pull/1585)
- [doc(metrics): add pvc namespace to volume metrics](https://github.com/longhorn/website/pull/796)

**Comment by roger-ryao** [comment]
**Verified on master-head 20231115**

- longhorn master-head https://github.com/longhorn/longhorn/commit/74d829d6e81c937baa25a6bc78041f27b361b5e5
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/d49f1f9eedbec1ac1337c486a4d46268126d7194


**Test Steps:**

1. Create `vol-0` with PV/PVC in the `longhorn-system` namespace.
2. Create `vol-1` with PV/PVC in the `local` namespace.
3. Create `vol-2` with PV/PVC in the `default` namespace.
4. Create `vol-3` without PV/PVC
5. Attach volumes to the node.
6. Execute the command `curl -sSL http://$longhorn_manager_ip:$longhorn_backend_service_port/metrics | grep longhorn_volume | grep pvc_namespace`

**Result Passed**

After executing the command, we observed the corresponding PVC value in the metrics.

![Screenshot_20231115_180404](https://github.com/longhorn/longhorn/assets/104337648/6012481f-7844-4acb-b62f-e69363392aed)
