### ISSUE TITLE
[QUESTION] Longhorn not seeing expanded volume size

### ISSUE THREAD

**Issue by joncy92** [longhorn/longhorn#7084]
## Question

I've expanded my disk by 15GiB and rebooted my node but longhorn is still seeing the old size and will not schedule new volumes due to limited disk space.
I'm also confused as to why only this node has issues with disk space - all three nodes have the exact same disk space and all volumes are configured to replicate on all nodes. 

![image](https://github.com/longhorn/longhorn/assets/34712810/12d0ffb6-5516-4422-a310-4c87455bf371)

## Environment

 - Longhorn version: v1.3.2
 - Kubernetes version: 
 - Node config
   - OS type and version Ubuntu Server 22.04.1
   - Kernel version 
   - CPU per node: 28
   - Memory per node: 16GiB
   - Disk type Proxmox Virtual disk
   - Network bandwidth and latency between the nodes: 0 latency 30Gbps virtual network
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox

**Comment by ChanYiLin** [comment]
You can refer to the document here: https://longhorn.io/docs/1.5.2/volumes-and-nodes/node-space-usage/#space-usage-of-each-node

> Allocated column: The left number is the size that has been used for volume scheduling, and it does not mean the space has been used for the Longhorn volume data store. The right number is the max size for volume scheduling, which the result of Size multiplying Storage Over Provisioning Percentage. (In the above illustration, Storage Over Provisioning Percentage is 500.) Hence, the difference between the 2 numbers (let’s call it as the allocable space) determines if a volume replica can be scheduled to this node.

> Used column: The left part indicates the currently used space of this node. The whole bar indicates the total space of the node.

It seems some of the disk space on `thor-02` has been used by other application? So there is no space much left on the node?

Longhorn periodically update the disk info
You may check if you correctly resize the LVM and filesystem if you are using VM and virtual disk. Ref: https://github.com/longhorn/longhorn/issues/2233

Thanks

**Comment by joncy92** [comment]
> You can refer to the document here: https://longhorn.io/docs/1.5.2/volumes-and-nodes/node-space-usage/#space-usage-of-each-node
> 
> > Allocated column: The left number is the size that has been used for volume scheduling, and it does not mean the space has been used for the Longhorn volume data store. The right number is the max size for volume scheduling, which the result of Size multiplying Storage Over Provisioning Percentage. (In the above illustration, Storage Over Provisioning Percentage is 500.) Hence, the difference between the 2 numbers (let’s call it as the allocable space) determines if a volume replica can be scheduled to this node.
> 
> > Used column: The left part indicates the currently used space of this node. The whole bar indicates the total space of the node.
> 
> It seems some of the disk space on `thor-02` has been used by other application? So there is no space much left on the node?
> 
> Longhorn periodically update the disk info You may check if you correctly resize the LVM and filesystem if you are using VM and virtual disk. Ref: #2233
> 
> Thanks

I will check if other apps are using space but this node is dedicated to k3s and the disk is also only used for longhorn volumes
Either way though the disk has been expanded from 100GiB to 115GiB and the additional space isn't visible in longhorn. How do I make longhorn realise there's more space available?

**Comment by ChanYiLin** [comment]
Can you help me to collect  and show the disk/filesystem information?
Note: Longhorn by default put the data in `/var/lib/longhorn`
