### ISSUE TITLE
[QUESTION] Disk schedule issue

### ISSUE THREAD

**Issue by J1a-wei** [longhorn/longhorn#7091]
We are planning to use Longhorn in our production environment soon, for deploying a large number of blockchain nodes. The underlying storage data will be substantial, with all PVs combined expected to exceed 100 TiB.

Our deployment environment consists of bare metal machines, each with about 2 NVME hard drives of 3.8 TiB, configured in Raid0 (although it's also possible not to set them up in RAID). There are 15 such machines in total. We plan to manage them using Longhorn.

I have a question regarding this setup:

Suppose there are two machines, each with only 100 GiB of space available for Longhorn to schedule. If I declare a PVC of 150 GiB, is it possible to use 100 GiB from Machine A and 50 GiB from Machine B to complete the PV allocation?

Is it recommended to configure Raid0, given that there are certain risks associated with it? If not setting up Raid0, would allowing Longhorn to automatically discover the hard drives be a better choice?

**Comment by ChanYiLin** [comment]
For the first question, sorry we don't support cross node volume allocation. For this feature request, you can follow this thread: https://github.com/longhorn/longhorn/issues/1061. We plan to implement this feature in our v2 data engine.

For the second question, I don't think there is any issue when using Longhorn with RAID0.

**Comment by J1a-wei** [comment]
Thanks  @ChanYiLin ! Is there a specific release schedule for v2's data engine? Looking forward to this feature?  I think we should be able to do a smooth upgrade with the V2 Engine at a later stage, right?

**Comment by ChanYiLin** [comment]
Sorry it might not happen in the near future.
V2 engine will still be flagged as experimental feature in v1.6 (Jan, 2024) with the goal of GA in v1.7(July, 2024)
For volume cross nodes feature, it may be in the release after v1.7.

We don't have a way to upgrade Volume of V1 engine to V2 engine directly. 
However there is still an informal way to do so, one can backup the Volume first and then restore it back with V2 engine.

I would suggest to play with Longhorn in testing environment first to see if it fits your needs
