### ISSUE TITLE
[BUG] Upgrade from v1.5.2 to v1.5.3-rc1 failed if there's an attached v1 volume and a detached v2 volume

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#7094]
## Describe the bug (🐛 if you encounter this issue)

Upgrade from `v1.5.2` to `v1.5.3-rc1` failed if there's an attached v1 volume and a detached v2 volume

`instance-managers` get stuck in `Pending -> OutOfhugepages-2Mi -> Terminating` loop forever and not possible to become Running:

According to v1.5.3 [website](https://longhorn.io/docs/1.5.3/deploy/important-notes/#detach-all-v2-volumes-before-upgrade), attached v1 volume should not impact the upgrade process.

```
longhorn-system   instance-manager-749a0b6289a7dcd13969be2694fa32e3   0/1     OutOfhugepages-2Mi   0          0s
longhorn-system   instance-manager-381b3cd27f3e4a0e4b02d634f29a503e   0/1     OutOfhugepages-2Mi   0          0s
longhorn-system   instance-manager-249758cbabcbc1f2d148a6d98bc97030   0/1     Terminating          0          0s
longhorn-system   instance-manager-249758cbabcbc1f2d148a6d98bc97030   0/1     Terminating          0          0s
longhorn-system   instance-manager-249758cbabcbc1f2d148a6d98bc97030   0/1     Pending              0          0s
longhorn-system   instance-manager-249758cbabcbc1f2d148a6d98bc97030   0/1     OutOfhugepages-2Mi   0          0s
```

## To Reproduce

1. Setup v2 engine environment with https://longhorn.io/docs/1.5.3/spdk/quick-start/
2. Install longhorn `v1.5.2` by `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.5.2/deploy/longhorn.yaml`
3. Create a v1 volume and PVC1, apply workload1 with the PVC1, write data into mount point
3. Create a v2 volume and PVC2, apply workload2 with the PVC2, write data into mount point
4. Scale down the workload2,  make sure v2 volume detached.
5. Upgrade longhorn to `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.5.3-rc1/deploy/longhorn.yaml`
6. `instance-managers` get stuck in `Pending -> OutOfhugepages-2Mi -> Terminating` loop

## Expected behavior

Upgrade success when v2 volume detached

## Support bundle for troubleshooting

[supportbundle_374b780d-fb7a-46a8-a30e-ef04354a62e6_2023-11-14T04-09-22Z.zip](https://github.com/longhorn/longhorn/files/13344355/supportbundle_374b780d-fb7a-46a8-a30e-ef04354a62e6_2023-11-14T04-09-22Z.zip)

## Environment

 - Longhorn version: v1.5.3-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl and helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:  v1.28.2+k3s1
 - Impacted Longhorn resources:
   - Volume names: vol2

## Additional context

Upgrade form `v1.5.2` to `v1.5.3-rc1` success if there only had a detached v2 volume.
https://github.com/longhorn/longhorn/issues/7025

**Comment by derekbit** [comment]
Ah, we should update the document. All v1 and v2 volumes should be detached.

**Comment by chriscchien** [comment]
Confirmed that the upgrade from `v1.5.2` to `v1.5.3-rc1` success when all v1 and v2 volumes were detached.
Waiting doc [PR](https://github.com/longhorn/website/pull/797) merged to close this ticket.

**Comment by chriscchien** [comment]
Close this ticket as the doc [PR](https://github.com/longhorn/website/pull/797) merged,  thanks
