### ISSUE TITLE
[IMPROVEMENT] Add global setting for enable v1 or v2 volume support

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7095]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Add global setting for enable v1 or v2 volume support.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager be08850) following [the test steps](https://github.com/longhorn/longhorn/issues/7095#issuecomment-1862830103).

**Comment by derekbit** [comment]
I think we can backport this improvement to v1.5.4. WDYT? @innobead
