### ISSUE TITLE
[BUG] longhorn-admission-webhook keeps crashing: Forbidden

### ISSUE THREAD

**Issue by T0jgli** [longhorn/longhorn#7100]
## Describe the bug (🐛 if you encounter this issue)

Hello,

I have tried to install longhorn via helm, but longhorn-manager keeps crashing. 

`Error starting manager: upgrade API version failed: cannot create CRDAPIVersionSetting: Internal error occurred: failed calling webhook \"validator.longhorn.io\": failed to call webhook: Post \"https://longhorn-admission-webhook.longhorn-system.svc:9502/v1/webhook/validaton?timeout=10s\": Forbidden" func=app.DaemonCmd.func1 file="daemon.go:83`

Below this line:
`"Listening on :9502" func=server.ListenAndServe.func2 file="server.go:75"`

If I exec into the UI pod:

```
nginx@longhorn-ui-5b47fd7f96-ssszr:/web> curl -vvvv https://longhorn-admission-webhook.longhorn-system.svc:9502
*   Trying 10.103.19.52:9502...
* connect to 10.103.19.52 port 9502 failed: Connection refused
* Failed to connect to longhorn-admission-webhook.longhorn-system.svc port 9502 after 1011 ms: Couldn't connect to server
* Closing connection 0
curl: (7) Failed to connect to longhorn-admission-webhook.longhorn-system.svc port 9502 after 1011 ms: Couldn't connect to server
```

The DNS resolution is working and I have about 50 pods running, so the networking is working fine.

**describe service longhorn-admission-webhook**
```
Name:              longhorn-admission-webhook
Namespace:         longhorn-system
Labels:            app=longhorn-admission-webhook
                   app.kubernetes.io/instance=longhorn
                   app.kubernetes.io/managed-by=Helm
                   app.kubernetes.io/name=longhorn
                   app.kubernetes.io/version=v1.5.2
                   helm.sh/chart=longhorn-1.5.2
Annotations:       meta.helm.sh/release-name: longhorn
                   meta.helm.sh/release-namespace: longhorn-system
Selector:          app=longhorn-manager
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.103.19.52
IPs:               10.103.19.52
Port:              admission-webhook  9502/TCP
TargetPort:        admission-wh/TCP
Endpoints:
Session Affinity:  ClientIP
Events:            <none>
```

**This enpointslice is pointing to the 3 created longhorn-manager pod**
```longhorn-admission-webhook-5dt6j    IPv4          9502      192.168.44.26,192.168.77.172,192.168.166.81   11m```

I have looked into these issues, and nothing helped:
https://github.com/longhorn/longhorn/issues/4462
https://github.com/longhorn/longhorn/discussions/5285

I am using corporate proxy, but only for pulling the images from the internet. Proxy environment variables inside the pods are not set. But added no_proxy env for the manager pod:
```
    Environment:
      POD_NAMESPACE:  longhorn-system (v1:metadata.namespace)
      POD_IP:          (v1:status.podIP)
      NODE_NAME:       (v1:spec.nodeName)
      NO_PROXY:       *.svc,*.longhorn-system.svc.cluster.local,*.longhorn-system.svc,10.0.0.0/8,192.168.0.0/16
```

## Environment

 - Longhorn version: v1.5.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K8s kubeadm
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 22.04
   - Kernel version: 5.4.0-166-generic
   - CPU per node: 8
   - Memory per node: 32
   - Disk type(e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes: 1 Gb/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

## Additional context

**Package versions:**

- kubelet -  1.26.5-00
- kubeadm - 1.26.5-00
- containerd.io - 1.6.24-1

**Comment by ChanYiLin** [comment]
If it is related to network connection issue, there is no much thing we can do from Longhorn's side
You may need to check if proxy setting is correct in the pod or in the cluster or even on the host

**Comment by T0jgli** [comment]
I have managed to fix.

Needed to add _longhorn-admission-webhook.longhorn-system.svc_ no_proxy to `/etc/kubernetes/manifests` files in the master nodes

**Comment by T0jgli** [comment]
So thanks, I don't know why it was needed.

**Comment by ct9915** [comment]
> I have managed to fix.
> 
> Needed to add _longhorn-admission-webhook.longhorn-system.svc_ no_proxy to `/etc/kubernetes/manifests` files in the master no_proxy setting SAVED/COMPLETED my life! 
my 1.9.1 version of longhorn not stuck on longhorn-manager pod continue crashing until I appended longhorn-admxxxx.svc in no_proxy setting at kubernetes manifest files.
