### ISSUE TITLE
[BUG] Environment check script claims success when kubectl fails.

### ISSUE THREAD

**Issue by james-munson** [longhorn/longhorn#7102]
## Describe the bug (🐛 if you encounter this issue)

Support was asked to re-run the (improved) 1.3.2 environment_check to ensure the iscsi install:

> curl -sSfL [https://raw.githubusercontent.com/longhorn/longhorn/v1.3.x/scripts/environment_check.sh](https://raw.githubusercontent.com/longhorn/longhorn/v1.3.x/scripts/environment_check.sh) | bash

The output:
```
[INFO] Required dependencies 'kubectl jq mktemp' are installed.
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[INFO] Hostname uniqueness check is passed.
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[INFO] All longhorn-environment-check pods are ready .
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[INFO] Required packages are installed.
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[INFO] MountPropagation is enabled.
[INFO] Cleaning up longhorn-environment-check pods...
error: unable to recognize "/tmp/tmp.6LAdpOy1uk/environment_check.yaml": Get "

http://localhost:8080/api?timeout=32s

": dial tcp 127.0.0.1:8080: connect: connection refused
[INFO] Cleanup completed.
```

## To Reproduce

Set KUBECONFIG to a bogus path to ensure that a call to `kubectl` will fail.  Run the environment check script as shown.

## Expected behavior

The script should have guard code first thing to ensure that the result of `kubect get pods` is a non-empty list of nodes with no failure.

## Environment

 - Longhorn version:  1.3.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

## Additional context

Reading through the checking script, it jumps out that most of the check functions have logic like this:

```
  ok = true
  kube_list = $(kubectl get somethings )
  for thing in ${kube_list}; do
    check thing, if not as hoped, set ok = false
  done
  if ok is true, print happy message.
````

Having looped through zero iterations of the empty list of somethings, ok is never set to false, so we check out.  But not really.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn `866f11`)

1. Set `KUBECONFIG` to a to a bogus path
2. Preform `curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/master/scripts/environment_check.sh | bash`
3. will see output `ERROR] kubectl get nodes failed - check KUBECONFIG setup`
```shell
[INFO]  Required dependencies 'kubectl jq mktemp sort printf' are installed.
E1130 06:56:26.768482  225179 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1130 06:56:26.768870  225179 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1130 06:56:26.770392  225179 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1130 06:56:26.771940  225179 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1130 06:56:26.773500  225179 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[ERROR] kubectl get nodes failed - check KUBECONFIG setup
```
