### ISSUE TITLE
[BUG] Fix RWX volume mount option typo in v1.5.x

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7104]
## Describe the bug (🐛 if you encounter this issue)

Should be `softerr` in https://github.com/longhorn/longhorn-manager/blob/v1.5.x/csi/node_server.go#L241.
The typo doesn't introduce negative impact, because CSI will fall back to `soft`.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

**Comment by yangchiu** [comment]
Verified passed on v1.5.x-head (longhorn-manager bd7750b).

Created a RWX volume on v1.5.2, the mount option is `soft`:
```
$ kubectl exec -it test-statefulset-rwx-0 -- /bin/sh -c "mount | grep data"
10.43.89.202:/pvc-633d95ed-a073-4b1f-9208-b42979b465bb on /data type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,
namlen=255,soft,noresvport,proto=tcp,timeo=600,retrans=5,sec=sys,
clientaddr=10.0.1.158,local_lock=none,addr=10.43.89.202)
```

Created a RWX volume on v1.5.x-head, the mount option is `softerr`:
```
$ kubectl exec -it test-statefulset-rwx-0 -- /bin/sh -c "mount | grep data
"10.43.215.34:/pvc-4e895643-45eb-4227-a38a-bcee762e77c5 on /data type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,
namlen=255,softerr,softreval,noresvport,proto=tcp,timeo=600,retrans=5,sec=sys,
clientaddr=10.0.1.225,local_lock=none,addr=10.43.215.34)
```

And rwx related automated test cases all passed:
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5229/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5230/
