### ISSUE TITLE
[BUG] Share manager unmount/unexport RWX volume timing issue

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7106]
## Describe the bug (🐛 if you encounter this issue)

The volume is requested to detach, so share-manager controller unmounts/unexports and detaches (remove the volume attachment ticket) the volume.
Afterwards, it is requested to attach right after, but the volume is already unmounted.

## To Reproduce

Repeat negative test case `Reboot RWX Volume Node While Workload Heavy Writing`

## Environment

 - Longhorn version: v1.5.x-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

## Additional context

https://suse.slack.com/archives/C02DR3N5T24/p1699951700806219

**Comment by derekbit** [comment]
Root cause
1. CSI requests the volume detachment
2. share manager controller set the unmount and unexport the volume and try to delete the volumeattachment ticket. sm.status.state is marked as stopping.
3. CSI requests the volume to attach.
4. sm.status.state  is marked as running.
5. The volume is already unexported and unmounted in the share manager pod.

**Comment by yangchiu** [comment]
Verified passed by running [negative test case](https://ci.longhorn.io/job/private/job/longhorn-e2e-test/104/) `Reboot RWX Volume Node While Workload Heavy Writing` repeatedly on master-head (longhorn-manager 83d3435).
