### ISSUE TITLE
[QUESTION] How is recurring-job label of PVCs getting synced?

### ISSUE THREAD

**Issue by harryzcy** [longhorn/longhorn#7109]
## Question

From the documentation

> By default, applying a recurring job to a Persistent Volume Claim (PVC) does not have any effect. You can enable or disable this feature using the recurring job source label.

Does Longhorn pick up the source label when it's added to an existing PVC? or does it only pick up when it's present when PVC is created?

> Once the PVC is labeled as the source, any recurring job labels added or removed from the PVC will be periodically synchronized by Longhorn to the associated Volume.

How does the synchronization get triggered? Is it interval based? What's the interval?

> ```
> kubectl -n <NAMESPACE> label pvc/<PVC-NAME> recurring-job.longhorn.io/source=enabled
> 
> # Example:
> # kubectl -n default label pvc/sample recurring-job-group.longhorn.io/source=enabled
> ```

Note on the first line, it says `recurring-job.longhorn.io`, but the example below shows `recurring-job-group.longhorn.io`. What's the correct label here?

## Environment

 - Longhorn version: 1.5.2
 - Kubernetes version: v1.28.3+k3s1
 - Node config
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

## Additional context

I'm trying to add recurring backups to existing PVCs managed by StatefulSet. But the volumes aren't picked up:

```
time="2023-11-15T05:55:02Z" level=info msg="Setting allow-recurring-job-while-volume-detached is false" func=app.recurringJob file="recurring_job.go:129"
time="2023-11-15T05:55:02Z" level=info msg="Got volumes from label recurring-job.longhorn.io/gitea-backup=enabled" func=app.getVolumesBySelector file="recurring_job.go:899"
time="2023-11-15T05:55:02Z" level=info msg="Got volumes from label recurring-job-group.longhorn.io/gitea=enabled" func=app.getVolumesBySelector file="recurring_job.go:899"
time="2023-11-15T05:55:02Z" level=info msg="Found 0 volumes with recurring job gitea-backup" func=app.recurringJob file="recurring_job.go:144"
```

**Comment by ChanYiLin** [comment]
> Does Longhorn pick up the source label when it's added to an existing PVC? or does it only pick up when it's present when PVC is created?


Once you enable the source label on the PVC, Longhorn starts to sync the recurring-job label from PVC to Longhorn Volume since Volume is the real resource that Longhorn managed. 
So Longhorn needs to sync the label from PVCs to Volumes and further use these labels to select Volumes to do recurring jobs.
```
kubectl -n <NAMESPACE> label pvc/<PVC-NAME> recurring-job.longhorn.io/source=enabled
```

> How does the synchronization get triggered? Is it interval based? What's the interval?

Longhorn periodically(30s, or when there is any update) sync all the Volumes. It will get the PVC of the Volume and then check if it is source enabled, if yes, it then sync other recurring job labels to the Volume itself.

> Note on the first line, it says recurring-job.longhorn.io, but the example below shows recurring-job-group.longhorn.io. What's the correct label here?

It is a typo, sorry about that.

> I'm trying to add recurring backups to existing PVCs managed by StatefulSet. But the volumes aren't picked up

You can first check 
1. If your PVC has label `recurring-job-group.longhorn.io/source=enabled`
2. Have you set the recurring job label in PVC
3. Have those labels been synced to the Longhorn Volume `kubectl get lhv/XXX -n longhorn-system`

**Comment by harryzcy** [comment]
> 1. If your PVC has label recurring-job-group.longhorn.io/source=enabled
> 2. Have you set the recurring job label in PVC
> 3. Have those labels been synced to the Longhorn Volume kubectl get lhv/XXX -n longhorn-system

I have the first two steps done. I can find the PVC using the labels (with `kubectl get pvc -l recurring-job-group.longhorn.io/source=enabled` and `kubectl get pvc -l recurring-job-group.longhorn.io/GROUP_NAME=enabled`).
But the labels are not synced to the Longhorn volumes for me.

How can I check why the sync is not working? Is there specific logs I can check?

**Comment by harryzcy** [comment]
@ejweber Thank you.

**Comment by ejweber** [comment]
Good to hear! Closing.
