### ISSUE TITLE
Deleted backups still exist in the backup status list

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#711]
![Screen Shot 2019-09-04 at 4 23 36 PM](https://user-images.githubusercontent.com/47542419/64300105-792ec980-cf30-11e9-888b-3c6086d7d24d.png)
![Screen Shot 2019-09-04 at 4 22 56 PM](https://user-images.githubusercontent.com/47542419/64300119-80ee6e00-cf30-11e9-905a-5fd250d70f81.png)

**Comment by yasker** [comment]
Move to v0.7.0 since it's no immediate impact of the issue.

**Comment by yasker** [comment]
Duplicate of #627
