### ISSUE TITLE
engine image: Reference count should count for live upgraded engine as well

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#712]
The live upgraded engine is running inside the old instance manager, which is using the old engine image.

Currently, once upgraded, the reference count of the old engine would be reduced. But since the updated engine is still running inside the old instance manager, we cannot allow removing the engine image thus remove the old instance manager for the engine.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
  - Deploy longhorn with engine image `longhornio/longhorn-engine:live-upgrade-2-2-1`
  - Create few volumes, attach them to nodes.
  - Deploy new image `longhornio/longhorn-engine:v0.6.0-rc1`
  - On `Volume` page select some volumes, and click `Upgrade Engine`, and select `v0.6.0-rc1` engine image.
  - On `Settings/Engine Image`, reference count should be updated with the number of upgraded volumes.
