### ISSUE TITLE
[BUG] supportbundle/kubelet.log empty in k3s environment

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7121]
## Describe the bug (🐛 if you encounter this issue)

`collect_kubelet_log` function in `support-bundle-kit` package doesn't support `k3s`, so the `kubelet.log` is always empty in `k3s` environment.

Since in our daily regression uses `k3s` by default, which makes it difficult to get `kubelet` related information in daily debugging. 

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

**Comment by c3y1huang** [comment]
@yangchiu please help to mirror [rancher/support-bundle-kit:v0.0.31](https://hub.docker.com/layers/rancher/support-bundle-kit/v0.0.31/images/sha256-7bc429dbc5577e34dcd09bb104326fa2840b71df1e2d8ee3ec23e3391bb0081a?context=explore) to longhornio, thank you.

**Comment by yangchiu** [comment]
> @yangchiu please help to mirror [rancher/support-bundle-kit:v0.0.31](https://hub.docker.com/layers/rancher/support-bundle-kit/v0.0.31/images/sha256-7bc429dbc5577e34dcd09bb104326fa2840b71df1e2d8ee3ec23e3391bb0081a?context=explore) to longhornio, thank you.

done.

**Comment by chriscchien** [comment]
Verified **pass** in longhorn master (longhorn `f67dd0`) with test [steps](https://github.com/longhorn/longhorn-tests/pull/1595/files)

Deploy Longhorn on k3s cluster and
- In `v1.5.3`, support bundle have only `kubelet.log` in each node and the content is empty as below
```
-- No entries --
``` 
- In longhorn master, support bundle has below file on each node as below
    - kubeket.log : `-- No entries --`
    - k3s-agent-service.log : Have `kubelet` log if the node is work node
    - k3s-service.log : Have `kubelet` log if the node is control plane node


I will close this ticket if the manual test [case](https://github.com/longhorn/longhorn-tests/pull/1595) merged, or test again if the test case updated, thank you

**Comment by chriscchien** [comment]
Close this ticket as the [doc](https://github.com/longhorn/longhorn-tests/pull/1595) merged without modify and test result [pass](https://github.com/longhorn/longhorn/issues/7121#issuecomment-1818124493), thank you.
