### ISSUE TITLE
Longhorn volume replicas reports healthy state after instance manager deleted and volume detached

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#713]
Steps to reproduce:

  - Create a longhorn volume.
  - Attach volume to node, and wait volume to be in Healthy state.
  - In `Volume Details` page, get instance Instance Manager name 
Using `kubectl delete pods INSTANCE_MANAGER_POD_NAME -n longhorn-system`
  - Longhorn Volume gets detached, but replicas states reports `Healthy`.

![Screenshot from 2019-09-09 22-48-41](https://user-images.githubusercontent.com/18232258/64567243-15edce80-d358-11e9-8194-dbcc30e2c6fe.png)

**Comment by yasker** [comment]
@meldafrawi Can you reproduce this issue now?

**Comment by meldafrawi** [comment]
Can't be reproduced.
Closing the issue.
