### ISSUE TITLE
[BUG] unable to install longhorn

### ISSUE THREAD

**Issue by mdelazza** [longhorn/longhorn#7138]
## Describe the bug (🐛 if you encounter this issue)

I'm trying to deploy longhorn via kubectl but longhorn-manager pods go in CrashLoopBackOff  state

NAME                                        READY   STATUS             RESTARTS         AGE
longhorn-driver-deployer-54d5cddccc-qq7dn   0/1     Init:0/1           0                136m
longhorn-manager-84dkm                      0/1     CrashLoopBackOff   35 (3m35s ago)   136m
longhorn-manager-kmh85                      0/1     CrashLoopBackOff   18 (4m13s ago)   73m
longhorn-manager-n7ctg                      0/1     CrashLoopBackOff   35 (2m43s ago)   136m
longhorn-manager-qp4nh                      0/1     CrashLoopBackOff   35 (3m1s ago)    136m
longhorn-manager-x5c7n                      0/1     CrashLoopBackOff   35 (3m55s ago)   136m
longhorn-ui-5b974686f-bxppf                 1/1     Running            0                136m
longhorn-ui-5b974686f-zpbcn                 1/1     Running            0                136m

kubectl logs -n longhorn-system longhorn-manager-84dkm
watching at log I find this fatal error:
time="2023-11-17T11:14:19Z" level=fatal msg="Error starting manager: upgrade resources failed: Internal error occurred: failed calling webhook \"validator.longhorn.io\": failed to call webhook: Post \"https://longhorn-admission-webhook.longhorn-system.svc:9502/v1/webhook/validaton?timeout=10s\": Forbidden" func=app.DaemonCmd.func1 file="daemon.go:83"

## To Reproduce
i downloaded yaml file 
wget https://raw.githubusercontent.com/longhorn/longhorn/v1.5.3/deploy/longhorn.yaml
and customize with the following settings
  default-setting.yaml: |-
    default-data-path: /mnt/longhorn/
    default-data-locality: best-effort
    orphan-auto-deletion: true
    allow-volume-creation-with-degraded-availability: false
    replica-auto-balance: best-effort
    storage-minimal-available-percentage: 10
    create-default-disk-labeled-nodes: true

Then i apply the yaml with
kubectl apply -f longhorn.yaml

## Expected behavior

Successfull deployment

## Support bundle for troubleshooting

n.a.

## Environment

 - Longhorn version: 1.5.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: vanilla k8s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 5
 - Node config
   - OS type and version: linux rocky 8 
   - Kernel version: 4.18.0-477.27.1.el8_8.x86_64
   - CPU per node: 4
   - Memory per node: 4 gb 
   - Disk type(e.g. SSD/NVMe/HDD): NVMe
   - Network bandwidth between the nodes: 1 Gb
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): vmware
 - Number of Longhorn volumes in the cluster:  n.a.
 - Impacted Longhorn resources: n.a.
   - Volume names: n.a.

**Comment by innobead** [comment]
This should be related to service name resolution, and it looks like the service endpoint is unable to reach out. 
Go check a similar issue reported by another community https://github.com/longhorn/longhorn/issues/7100 or debug it first https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/.

cc @ChanYiLin

**Comment by mdelazza** [comment]
You are the man! I forgot i was behind a corporate proxy. Thanks

**Comment by mdelazza** [comment]
all is fine thx
