### ISSUE TITLE
[BUG] unable to remove longhorn because flag needs to be set to true but flag does not exist

### ISSUE THREAD

**Issue by alexbospnw** [longhorn/longhorn#7139]
## Describe the bug (🐛 if you encounter this issue)

I ran an upgrade from longhorn 1.3.2 to 1.4.2 that seems to have failed. (https://github.com/longhorn/longhorn/issues/5963)  In an attempt to uninstall longhorn and reinstall it as suggested here the uninstall also fails with the error 

time="2023-11-17T21:46:16Z" level=fatal msg="cannot uninstall Longhorn because deleting-confirmation-flag is set to `false`. Please set it to `true` using Longhorn UI or kubectl -n longhorn-system edit settings.longhorn.io deleting-confirmation-flag "

If i follow the instructions as it mentions I get 

Error from server (NotFound): settings.longhorn.io "deleting-confirmation-flag" not found

## To Reproduce

Really not sure you can reliably recreate this one

## Expected behavior

I can uninstall longhorn

## Support bundle for troubleshooting

UI is inaccessible

## Environment

 - Longhorn version: 1.3.2 > 1.4.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: ADM launched
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 6
 - Node config
   - OS type and version: ubuntu 20.04
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): vmware
 - Number of Longhorn volumes in the cluster: 16 or so

**Comment by ChanYiLin** [comment]
Can you still access the UI?
In `Setting > General`, you can try update the flag by checking the `Deleting Confirmation Flag` option.

You can also `kubectl get lhs -n longhorn-system` to see if the `deleting-confirmation-flag` exists

**Comment by Miheyzt** [comment]
i am having the same issue, should i only destroy cluster again? 

> Can you still access the UI? In `Setting > General`, you can try update the flag by checking the `Deleting Confirmation Flag` option.
> 
> You can also `kubectl get lhs -n longhorn-system` to see if the `deleting-confirmation-flag` exists

this doesn;t work as soon as i started deletion. it never ends, deletions pods are failing, but when trying to update this flag it says - Error: Command failed: /Applications/Lens.app/Contents/Resources/x64/helm upgrade longhorn longhorn/longhorn --version 1.5.3 --values /var/folders/v2/crr6mjbd7ydf7jp11j8n635m0000gn/T/7d849133-6b4f-40ae-89a1-a2a8d484addc-values.yaml --namespace longhorn-system --kubeconfig /var/folders/v2/crr6mjbd7ydf7jp11j8n635m0000gn/T/kubeconfig-7bb14c3e6c104758b02095981483304a
Error: UPGRADE FAILED: "longhorn" has no deployed releases
but it has just in uninstalling status

**Comment by alexbospnw** [comment]
We hit this one too. It's because you technically did an uninstall but it failed. A rollback should clear that up. Follow the steps under "troubleshooting" and "Uninstalling using Rancher UI or Helm failed, I am not sure why" 

https://longhorn.io/docs/1.5.3/deploy/uninstall/
