### ISSUE TITLE
[QUESTION] When tried to upgrade 1.5.2 to 1.5.3 by helm, engine version fixed 1.6.0-dev

### ISSUE THREAD

**Issue by Leddly** [longhorn/longhorn#7141]
## Question

All volumes created by pvc with longhorn storageclass can't be attached to node.

The error was that the expected longhorn engine is "ei-cf83e135" but installed engine image was "ei-b907910b".

And on the longhorn ui in setting, "Current Longhorn Version" is also 1.6.0-dev.

If I installed longhorn with something wrong helm command, is the "1.6.0-dev" version possible to install?

## Environment

 - Longhorn version: 1.5.2
 - Kubernetes version: v1.26.9+k3s1 
 - Node config
   - OS type and version : Ubuntu 22.04
   - Kernel version : Linux 5.15.0-88-generic x86_64
   - CPU per node: 4
   - Memory per node: 16gb
   - Disk type: ssd
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Comment by ejweber** [comment]
If you are following the [official documentation for installing Longhorn via Helm](https://longhorn.io/docs/1.5.3/deploy/install/install-with-helm/), I can't think of a particularly easy way to do this. This index it leads to does not contain any trace of `v1.6.0`.

If you installed by a less official method, though, I think this is quite possible to do. One potential flow (that Longhorn developers might use frequently) is:

```
git clone https://github.com/longhorn/longhorn.git
cd longhorn
helm install --dry-run longhorn chart/
```

This would install Longhorn via the Helm chart in the master branch of the the main Longhorn repository. This version of the chart is always associated with the latest development version of Longhorn (currently `v1.6.-dev`).

https://github.com/longhorn/longhorn/blob/master/chart/Chart.yaml

Please let us know if you found documentation suggesting to install Longhorn in a production cluster using this or some other broken flow!

**Comment by ejweber** [comment]
Closing this as stale. Please reopen it if there is additional context you can provide!
