### ISSUE TITLE
[BUG] Test case `test_system_backup_and_restore` failed

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#7143]
## Describe the bug (🐛 if you encounter this issue)

Longhorn failed to create a system backup on the `master-head`.

![Screenshot_20231120_093110](https://github.com/longhorn/longhorn/assets/104337648/dec7fa9a-cb76-4df3-947d-d348d7130d47)
```console
status:
  conditions:
  - lastProbeTime: ""
    lastTransitionTime: "2023-11-20T01:31:37Z"
    message: 'failed to archive system backup file: exec: "zip": executable file not
      found in $PATH'
    reason: Generate
    status: "True"
    type: Error
  gitCommit: 0258c74e026a2ad65ea03f8fc9cb412597e53cdd
  lastSyncedAt: "2023-11-20T01:31:37Z"
  managerImage: ""
  ownerID: ip-10-0-2-102
  state: Error
  version: v1.6.0-dev
```

## To Reproduce

1. Create a system backup from the UI.
or 
1. Execute the test case https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/724/testReport/junit/tests/test_system_backup_restore/test_system_backup_and_restore_s3_/ from Jenkins Job.

## Expected behavior

We are able to create a system backup without any errors.

## Support bundle for troubleshooting

[supportbundle_38319cac-6498-4c8d-8b0f-f4964475d0d9_2023-11-20T01-40-03Z.zip](https://github.com/longhorn/longhorn/files/13405402/supportbundle_38319cac-6498-4c8d-8b0f-f4964475d0d9_2023-11-20T01-40-03Z.zip)

## Environment

 - Longhorn version: master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): `Kubectl`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: `v1.28.3+k3s1`
   - Number of management node in the cluster:`1`
   - Number of worker node in the cluster:`3`
 - Node config
   - OS type and version: `SLES 15-sp5`
   - Kernel version:
   - CPU per node: `4 cores`
   - Memory per node: `16GB`
   - Disk type(e.g. SSD/NVMe/HDD): `SSD`
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): `AWS`
 - Number of Longhorn volumes in the cluster:`1`
 - Impacted Longhorn resources:
   - Volume names:

## Additional context

[](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/724/)

**Comment by mantissahz** [comment]
Related: https://github.com/longhorn/longhorn-manager/pull/2299#issuecomment-1816952494

**Comment by roger-ryao** [comment]
**Verified on master-head 20231127**

- longhorn master-head https://github.com/longhorn/longhorn/commit/57bf3edb1faa955ab077187a518d7be99ff38792
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/dd663887de73664ffc3296465a0a4b9d2ccbdfb6

**Result Passed**

The test has successfully passed in [the regression pipeline]( 
https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/682/testReport/tests/test_system_backup_restore/)

**Comment by roger-ryao** [comment]
Verified on master-head 20231127

longhorn master-head https://github.com/longhorn/longhorn/commit/57bf3edb1faa955ab077187a518d7be99ff38792
longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/dd663887de73664ffc3296465a0a4b9d2ccbdfb6
Result Passed

The test has successfully passed in [the regression pipeline](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/682/testReport/tests/test_system_backup_restore/)
