### ISSUE TITLE
[BUG] Valid backup secret produces error message: "there is space or new line in AWS_CERT"

### ISSUE THREAD

**Issue by m-ildefons** [longhorn/longhorn#7159]
## Describe the bug (🐛 if you encounter this issue)

Valid backup secret produces error message: "there is space or new line in AWS_CERT"

## To Reproduce
The following backup secret can not be selected through the settings menu, even though the contents are valid and have worked in older versions of longhorn:
```
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: Zm9vYmFyZm9vYmFyZm9vYmFy
  AWS_CERT: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVJ5Z0F3SUJBZ0lRSEpLN3MyUFNiN1dxM3RoUm5CbFRQakFLQmdncWhrak9QUVFEQWpBYk1Sa3cKRndZRFZRUURFeEJzYjI1bmFHOXliaTEwWlhOMExXTmhNQjRYRFRJek1UQXpNVEUxTXpjek5Wb1hEVEkwTURFeQpPVEUxTXpjek5Wb3dHekVaTUJjR0ExVUVBeE1RYkc5dVoyaHZjbTR0ZEdWemRDMWpZVEJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkNjVGZJbjBRWkMrMXZVQVNoS3ZDY0pnKzRDOHRTRWpmbzZVWWJKTjFhT3IKVmVRRHRjMS9QeitlaHEyRmVudkIxd1liTi93WitNaEE4OU1OT0VFZExDZWpRakJBTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTSC96TXFSeThHM2Vrb25OOTNtZzFHCkRQUThQekFLQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBcmRDUUxDc0lVd0JTNXFDQ0FMTmd1VERPOXN4TnVBUXIKL3ZicDdUSDk2d0VDSVFEd2ZwdUExblhrVFdyZnhIU1BIUU5ZTVZibythWUtQeXVId1AzK0FVL2Z1dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNYRENDQWdLZ0F3SUJBZ0lSQU1LWGNxWVJKcUpyay9OK2g3K3dSSlF3Q2dZSUtvWkl6ajBFQXdJd0d6RVoKTUJjR0ExVUVBeE1RYkc5dVoyaHZjbTR0ZEdWemRDMWpZVEFlRncweU16RXhNRGt4TlRRMU1URmFGdzB5TkRBeQpNRGN4TlRRMU1URmFNQUF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRREdTRTh3CjMyQ0tWQ0VnWW1jWWRmeEFLaXBOd2lqNUdwMUJpWGxWaERYU3ZEbndhcmdRKy93Ry8zL01UZEdNbk5VTHdMaFQKKzB4RHRiVGFFd3hTclRKYjhCSFErb0ZMai9uT0RTTk9YS2dzMHZ1NWs5SUZXWnYvdS9ib3Z6ZGpYOHlnNXhxSAp4WmtrVDN0eEg2VlR5L2p2Kzc5cjFhaEdsekNyWCs2WlZRUlF5SEFKWDFjelRJT3N6aFhWMUFESjZ6QzJYNUU0CkJINmFZenZ2Mm1LWkdBRzVZcUI5Rk5EWTBwSDhGQ2hCdm8xR29SU2REbVpmL1FaeUExMkQ5aHA5NCsvU0ltVWYKZmY5ZzcrOXBvbEdvTmZLQzhTSjh5UTZYWVdUckxBR3RTNnIySDFKZkpsRlBHNTdjMlBENGRPc2s0azEzclFmcgowa2xJQWdKdXcyMWxkS0ZCQWdNQkFBR2pkekIxTUE0R0ExVWREd0VCL3dRRUF3SUZvREFNQmdOVkhSTUJBZjhFCkFqQUFNQjhHQTFVZEl3UVlNQmFBRklmL015cEhMd2JkNlNpYzMzZWFEVVlNOUR3L01EUUdBMVVkRVFFQi93UXEKTUNpQ0VXdHlZWFJ2Y3k1eFlTNXpkWE5sTG1ONmdoTXFMbXR5WVhSdmN5NXhZUzV6ZFhObExtTjZNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSVFEVlNkSE5CbTZYczhVSU9KVmNOenR3MVdVV3dMVlJjOW53Sng2ZHlaTHZwZ0lnClNwTStDam9pR2xNcVhMZDd4akVlUWo4STVPVnp5RzRTS0UwS3lXWTAvT009Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  AWS_ENDPOINTS: aHR0cHM6Ly9rcmF0b3MucWEuc3VzZS5jeg==
  AWS_SECRET_ACCESS_KEY: YmFyZm9vYmFyZm9vYmFyZm9v
  VIRTUAL_HOSTED_STYLE: ZmFsc2U=
kind: Secret
metadata:
  annotations:
    longhorn.io/backup-target: ""
  creationTimestamp: "2023-11-07T14:52:58Z"
  name: backup-credentials
  namespace: longhorn-system
  resourceVersion: "4488117"
  uid: 5c1e3317-69af-4d97-8f76-4c741ec1b2d4
type: Opaque
```
## Expected behavior
I should be able to use this secret as "Backup Target Credential Secret"
## Environment

 - Longhorn version: 1.6-dev
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
 ```
 Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.17", GitCommit:"22a9682c8fe855c321be75c5faacde343f909b04", GitTreeState:"clean", BuildDate:"2023-08-23T23:37:25Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
 ```
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: SLE 15 SP4
   - Kernel version: 5.14.21-150400.24.63-default
   - CPU per node: 16
   - Memory per node: 64Gi
   - Disk type(e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes: 1Gi
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 3
 - Impacted Longhorn resources:
   - Settings

**Comment by m-ildefons** [comment]
The workaround at the moment for me is to create the secret with the key `AWSCERT` instead, then configure the longhorn backup target to use that secret. At this point I'll be seeing errors about unknown certificate authorities (which is expected as the correct key hasn't been provided in the secret). But if I then modify the secret so it's `AWS_CERT` again, backups work perfectly fine.
The check in the [datastore](https://github.com/longhorn/longhorn-manager/blob/e2262936be6d5b0083d8383013c8d9b2e80f15bb/datastore/longhorn.go#L316) seems to be bogus.

**Comment by ejweber** [comment]
@m-ildefons, I don't see anything changed in or around that code section recently.

Digging in a bit, it appears that your AWS_CERT value is, in fact, encoded with an extra newline as discussed in https://github.com/longhorn/longhorn/issues/811 (which led to the validation being added).

When I decode your AWS_CERT value using an online decoder (e.g. https://www.base64decode.org/), I see a newline at the end.

When I reencode the decoded certificate with no newline and the `-n` flag, as suggested in https://github.com/longhorn/longhorn/issues/811#issuecomment-541905398, I get the changed (in the last encoded character):

LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVJ5Z0F3SUJBZ0lRSEpLN3MyUFNiN1dxM3RoUm5CbFRQakFLQmdncWhrak9QUVFEQWpBYk1Sa3cKRndZRFZRUURFeEJzYjI1bmFHOXliaTEwWlhOMExXTmhNQjRYRFRJek1UQXpNVEUxTXpjek5Wb1hEVEkwTURFeQpPVEUxTXpjek5Wb3dHekVaTUJjR0ExVUVBeE1RYkc5dVoyaHZjbTR0ZEdWemRDMWpZVEJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkNjVGZJbjBRWkMrMXZVQVNoS3ZDY0pnKzRDOHRTRWpmbzZVWWJKTjFhT3IKVmVRRHRjMS9QeitlaHEyRmVudkIxd1liTi93WitNaEE4OU1OT0VFZExDZWpRakJBTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTSC96TXFSeThHM2Vrb25OOTNtZzFHCkRQUThQekFLQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBcmRDUUxDc0lVd0JTNXFDQ0FMTmd1VERPOXN4TnVBUXIKL3ZicDdUSDk2d0VDSVFEd2ZwdUExblhrVFdyZnhIU1BIUU5ZTVZibythWUtQeXVId1AzK0FVL2Z1dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNYRENDQWdLZ0F3SUJBZ0lSQU1LWGNxWVJKcUpyay9OK2g3K3dSSlF3Q2dZSUtvWkl6ajBFQXdJd0d6RVoKTUJjR0ExVUVBeE1RYkc5dVoyaHZjbTR0ZEdWemRDMWpZVEFlRncweU16RXhNRGt4TlRRMU1URmFGdzB5TkRBeQpNRGN4TlRRMU1URmFNQUF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRREdTRTh3CjMyQ0tWQ0VnWW1jWWRmeEFLaXBOd2lqNUdwMUJpWGxWaERYU3ZEbndhcmdRKy93Ry8zL01UZEdNbk5VTHdMaFQKKzB4RHRiVGFFd3hTclRKYjhCSFErb0ZMai9uT0RTTk9YS2dzMHZ1NWs5SUZXWnYvdS9ib3Z6ZGpYOHlnNXhxSAp4WmtrVDN0eEg2VlR5L2p2Kzc5cjFhaEdsekNyWCs2WlZRUlF5SEFKWDFjelRJT3N6aFhWMUFESjZ6QzJYNUU0CkJINmFZenZ2Mm1LWkdBRzVZcUI5Rk5EWTBwSDhGQ2hCdm8xR29SU2REbVpmL1FaeUExMkQ5aHA5NCsvU0ltVWYKZmY5ZzcrOXBvbEdvTmZLQzhTSjh5UTZYWVdUckxBR3RTNnIySDFKZkpsRlBHNTdjMlBENGRPc2s0azEzclFmcgowa2xJQWdKdXcyMWxkS0ZCQWdNQkFBR2pkekIxTUE0R0ExVWREd0VCL3dRRUF3SUZvREFNQmdOVkhSTUJBZjhFCkFqQUFNQjhHQTFVZEl3UVlNQmFBRklmL015cEhMd2JkNlNpYzMzZWFEVVlNOUR3L01EUUdBMVVkRVFFQi93UXEKTUNpQ0VXdHlZWFJ2Y3k1eFlTNXpkWE5sTG1ONmdoTXFMbXR5WVhSdmN5NXhZUzV6ZFhObExtTjZNQW9HQ0NxRwpTTTQ5QkFNQ0EwZ0FNRVVDSVFEVlNkSE5CbTZYczhVSU9KVmNOenR3MVdVV3dMVlJjOW53Sng2ZHlaTHZwZ0lnClNwTStDam9pR2xNcVhMZDd4akVlUWo4STVPVnp5RzRTS0UwS3lXWTAvT009Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=

The same online decoder shows no newline at the end and a secret with this value passes Longhorn validation.

It looks like the underlying issue with the AWS SDK (https://github.com/aws/aws-sdk-go/issues/689) was fixed after we added the validation, so it is maybe not needed now. I'm guessing this is why the AWS_CERT value doesn't cause problems when you apply your workaround.

**Comment by m-ildefons** [comment]
Hi Eric, thanks for looking at this.

I see what you're on to, but I think this check is still bogus since it's producing a very confusing error message and it's quite hard to figure out the problem as the message suggests that the space or newline is not in the encoded string but in the secret itself.

In my opinion there are two bugs regardless:

1) Longhorn should be able to deal with the certificates regardless of a newline at the end. There is nothing stopping Longhorn from just stripping it off before forwarding the certificates to the aws-sdk-go client

2) The validation only seems to happen when the Longhorn setting for the backup target credentials secret is set, not when that secret changes.

**Comment by derekbit** [comment]
After discussing with @mantissahz, we think it is not a bug but we can improve the UX.

What we will do
- Validate the secret that user provided. Longhorn doesn't need to strip the newline because we don't know if it is intended. Providing a correct secret is user's responsibility.
- Longhorn needs to show appropriate an error or warning message

**Comment by derekbit** [comment]
After discussing with @mantissahz, we think it is not a bug but we can improve the UX.

What we will do
- Validate the secret that user provided. Longhorn doesn't need to strip the newline because we don't know if it is intended. Providing a correct secret is user's responsibility.
- Longhorn needs to show appropriate an error or warning message


cc @innobead

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `00a3b8`)

Apply **Backup Target Credential Secret** with `AWS_ACCESS_KEY_ID` having a leading or trailing white space will get below error message from UI
```
failed to set the setting backup-target-credential-secret with invalid value backup-credentials: invalid trailing new line in AWS_CERT
```
