### ISSUE TITLE
[IMPROVEMENT] please create a default priority class for longhorn

### ISSUE THREAD

**Issue by harridu** [longhorn/longhorn#7171]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Very often I have to reboot some nodes due to some NFS-server-not-responding-still-trying problem. AFAICT this comes up if a Longhorn pod is killed without looking at context. Workaround is to set a high priority class for Longhorn, reducing the risk of Longhorn pods being killed before others, but it is highly painful to establish a priority class for Longhorn after installation.

## Describe the solution you'd like

A dedicated "longhorn-critical" priority class could ease the pain, even if it is just preconfigured with 0. Point is being able to change the priority class **configuration** on the fly. 

Maybe it is reasonable to give the instance-manager an even higher priority class than other Longhorn pods to support a defined shutdown sequence within the node.

**Comment by innobead** [comment]
This will be implemented in 1.6.0, https://github.com/longhorn/longhorn/issues/6528.
