### ISSUE TITLE
[FEATURE]  Support eventual danger zone setting update

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#7173]
> Will existing deployments be migrated to the new default priority class on the fly? I am not sure if this is possible.

In the current implementation, it's not possible. However, we should improve this part to have the following support to prevent any interruption for running volumes.

- When changing any volume-related Pod configuration (ex: IM pod, share manager pod, upcoming object storage/s3gw pod) like priority class, the change will only take effect when doing volume upgrade or volume reattachement. 

Extra info from @PhanLe1010 

![image](https://github.com/longhorn/longhorn/assets/899492/b34cb163-a8dc-401b-aafc-9c18e9efb057)

cc @shuo-wu @derekbit @c3y1huang

_Originally posted by @innobead in https://github.com/longhorn/longhorn/issues/6528#issuecomment-1822414466_

**Comment by ejweber** [comment]
To me, it sounds like the issue description and @PhanLe1010's suggestion are different.

- The issue description implies a kind of lazy update. We will allow a setting (like priority-class) to be changed at any time, but we won't actually change the configuration of the running pods (like the instance-manager pods) until they are restarted "naturally".
- @PhanLe1010's comment implies that we will simply refuse to allow the setting change unless all volumes are safely detached.

@harridu was asking for the former in the Rancher Users Slack (https://rancher-users.slack.com/archives/CC2UQM49Y/p1700549015471709) and in https://github.com/longhorn/longhorn/issues/6528#issuecomment-1688736579.

Unless I am misunderstanding here, we must decide which of these two paths we will take.

**Comment by innobead** [comment]
Your understanding is correct, so this is why I said there is an extra info from Phan.

The goal here is to have lazy update to make settings eventually effective without interrupting any running volumes. 

If there are any obstacles to prevent achieving this, we should at least have a validation to disallow applying the above settings when there are still running volumes.

**Comment by innobead** [comment]
Assigned to @mantissahz because currently he is working on a related issue, https://github.com/longhorn/longhorn/issues/6528. This issue will be appropriate to handle by me together.

**Comment by innobead** [comment]
@mantissahz Where we are?

**Comment by mantissahz** [comment]
@innobead
I am testing not to delete pods for modifying the setting like `guaranteed-instance-manager-cpu` if there are volumes attached and start to prepare the LEP.

**Comment by chriscchien** [comment]
Test steps related to upgrade from v1.5.x need to wait https://github.com/longhorn/longhorn/issues/7642 reslove first.

**Comment by innobead** [comment]
Need to verify all danger zone settings worked as expected.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `a78c2a`)

Below danger zone settings will only update to instance-manager pod after volume detached.  (Fresh installed master-head and upgrade from v1.5.x to master-head)
- priority-class
- taint-toleration
- system-managed-components-node-selector
- storage-network
