### ISSUE TITLE
ERROR "none of the node candidates contains a ready engine image"

### ISSUE THREAD

**Issue by jpintoversia** [longhorn/longhorn#7182]
## Question

Don't understand how to address this error "none of the node candidates contains a ready engine image" every check seems fine, but when try to mount a pv into a pod, the pod  is waiting for this error "none of the node candidates contains a ready engine image", on web UI have this error (example...)

"unable to attach volume pvc-3292dcb4-e65f-4cb4-8f3e-79fe08ab010c to slx00011293: cannot attach volume pvc-3292dcb4-e65f-4cb4-8f3e-79fe08ab010c with image : failed to check engine image readiness of node slx00011293: unable to get engine image : engineimage.longhorn.io "ei-cf83e135" not found"

but exists
pod/engine-image-ei-9d364f7e-wmmz8                      1/1     Running   3 (132m ago)   3h29m
pod/engine-image-ei-9d364f7e-pxzc4                      1/1     Running   3 (132m ago)   3h29m
pod/engine-image-ei-9d364f7e-6v6tz                      1/1     Running   3 (132m ago)   159m

only is not the same id... 

I've installed longhorn useing helm with default values, and have a K3S cluster with 1 master and 2 workers recently installed.

## Environment

 - Longhorn version: 1.5.2
 - Kubernetes version: v1.28.3
 - Node config
   - OS type and version: SUSE Linux Enterprise Server 15 SP5
   - Kernel version: 5.14.21-150500.55.31-default
   - CPU per node: 4
   - Memory per node: 8 Gb
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure Baremetas (K3S)

## Additional context

k get nodes.longhorn.io -n longhorn-system
NAME          READY   ALLOWSCHEDULING   SCHEDULABLE   AGE
slx00011294   True    true              True          3h26m
slx00011293   True    true              True          3h26m
slx00011111   True    true              True          159m
--------------

# k describe pv pvc-3292dcb4-e65f-4cb4-8f3e-79fe08ab010c
Name:            pvc-3292dcb4-e65f-4cb4-8f3e-79fe08ab010c
Labels:          <none>
Annotations:     longhorn.io/volume-scheduling-error: none of the node candidates contains a ready engine image
                 pv.kubernetes.io/provisioned-by: driver.longhorn.io
                 volume.kubernetes.io/provisioner-deletion-secret-name:
                 volume.kubernetes.io/provisioner-deletion-secret-namespace:
Finalizers:      [kubernetes.io/pv-protection external-attacher/driver-longhorn-io]
StorageClass:    longhorn
Status:          Bound
Claim:           default/longhorn-vol-claim
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        2Gi
Node Affinity:   <none>
Message:
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            driver.longhorn.io
    FSType:            ext4
    VolumeHandle:      pvc-3292dcb4-e65f-4cb4-8f3e-79fe08ab010c
    ReadOnly:          false
    VolumeAttributes:      dataLocality=disabled
                           fromBackup=
                           fsType=ext4
                           numberOfReplicas=3
                           staleReplicaTimeout=30
                           storage.kubernetes.io/csiProvisionerIdentity=1700660801243-8081-driver.longhorn.io
Events:                <none>

**Comment by ejweber** [comment]
Are you able to upload a support bundle @jpintoversia?

To demystify this a bit, Longhorn creates a Daemonset named `engine-image-ei-<checksum>` when it is installed and any time the setting `default-engine-image` is updated. The checksum calculation can be reproduced on the command line with `echo -n longhornio/longhorn-engine:v1.4.4 | sha512sum | cut -c-8`. For example, in my `v1.4.4` environment, the name of the Daemonset is `engine-image-ei-40f95a18`.

```
eweber@laptop:~/longhorn-manager> kl get setting default-engine-image
NAME                   VALUE                               AGE
default-engine-image   longhornio/longhorn-engine:v1.4.4   5h6m

eweber@laptop:~/longhorn-manager> echo -n longhornio/longhorn-engine:v1.4.4 | sha512sum | cut -c-8
40f95a18

eweber@laptop:~/longhorn-manager> kl get ds
NAME                       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
engine-image-ei-40f95a18   3         3         3       3            3           <none>          5h7m
longhorn-csi-plugin        3         3         3       3            3           <none>          5h6m
longhorn-manager           3         3         3       3            3           <none>          5h7m
```

None of the checksums in the output you have provided thus far match what I would expect for `v1.5.2`.

```
eweber@laptop:~/longhorn-manager> echo -n longhornio/longhorn-engine:v1.5.2 | sha512sum | cut -c-8
65224a4b
```

Maybe this means you are using non-standard engine image names (e.g. from a private registry)?

If you cannot provide the support bundle, the output of the following commands may be helpful.

- `kubectl get volume -n longhorn-system -oyaml pvc-3292dcb4-e65f-4cb4-8f3e-79fe08ab010c`
- `kubectl get setting -n longhorn-system default-engine-image`
- `kubectl get daemonset -n longhorn-system -oyaml -l longhorn.io/component: engine-image`

**Comment by puffitos** [comment]
Hey, sorry to unearth this issue, but we're currently experiencing it in a 1.7.2 longhorn cluster.  We are also using a private registry for the image. Is this the reason why this is happening?

**Comment by puffitos** [comment]
[supportbundle_a1a9aa5a-6ddc-41c8-a413-c4522a547e47_2025-07-29T13-34-06Z.zip](https://github.com/user-attachments/files/21490606/supportbundle_a1a9aa5a-6ddc-41c8-a413-c4522a547e47_2025-07-29T13-34-06Z.zip)

A support bundle, in a cluster that's currently being upgraded to 1.8.2 and this issue is currently blocking engine images from automatically being upgraded in some volumes. The only working workaround is to actually scale down the workloads and do an offline upgrade of the image, after the volume has truly been detached. Please let me know if I can offer any more information.

**Comment by puffitos** [comment]
@ejweber @derekbit @mantissahz I'm sharing some new insights in the issue after 1 week of updating in production. This issue is still active in version 1.7.2 / 1.8.2.

The volumes, which aren’t updated, seem to have one logline in common (we activated debug logging for a cluster, which we were sure the problem would occcur).

```
time="2025-08-29T04:47:23Z" level=debug msg="Ignoring recurring job labels on Volume pvc-ce7df9dc-05c4-4c19-9673-9eacb624fb2c
 PVC bpp-elastic-index-data-long due to missing source label" func="controller.(*VolumeController).syncPVCRecurringJobLabels"
 file="volume_controller.go:4050" controller=longhorn-volume node=worker-ip-10-14-254-193-eu-de-03
```

After the update, the only thing that pops out is that some replicas couldn’t be scheduled during the `getNodeCandidates` function of the `ReplicaScheduler` in the `longhorn-manager` code base):

```sh
longhorn-manager-29qcs longhorn-manager time="2025-08-29T04:22:57Z" level=debug msg="Excluding node in node candidates because instance manager on node is not ready" func="scheduler.(*ReplicaScheduler).getNodeCandidates" file="replica_scheduler.go:165" node=worker-ip-10-14-254-216-eu-de-01
longhorn-manager-29qcs longhorn-manager time="2025-08-29T04:22:57Z" level=debug msg="Excluding node in node candidates because instance manager on node is not ready" func="scheduler.(*ReplicaScheduler).getNodeCandidates" file="replica_scheduler.go:165" node=worker-ip-10-14-254-190-eu-de-02
longhorn-manager-29qcs longhorn-manager time="2025-08-29T04:22:57Z" level=debug msg="Excluding node in node candidates because instance manager on node is not ready" func="scheduler.(*ReplicaScheduler).getNodeCandidates" file="replica_scheduler.go:165" node=worker-ip-10-14-254-175-eu-de-03
longhorn-manager-29qcs longhorn-manager time="2025-08-29T04:22:57Z" level=debug msg="Excluding node in node candidates because instance manager on node is not ready" func="scheduler.(*ReplicaScheduler).getNodeCandidates" file="replica_scheduler.go:165" node=worker-ip-10-14-254-159-eu-de-01
longhorn-manager-29qcs longhorn-manager time="2025-08-29T04:22:57Z" level=debug msg="Excluding node in node candidates because instance manager on node is not ready" func="scheduler.(*ReplicaScheduler).getNodeCandidates" file="replica_scheduler.go:165" node=worker-ip-10-14-254-187-eu-de-02
longhorn-manager-29qcs longhorn-manager time="2025-08-29T04:22:57Z" level=debug msg="Excluding node in node candidates because instance manager on node is not ready" func="scheduler.(*ReplicaScheduler).getNodeCandidates" file="replica_scheduler.go:165" node=worker-ip-10-14-254-172-eu-de-02
longhorn-manager-29qcs longhorn-manager time="2025-08-29T04:22:57Z" level=debug msg="Excluding node in node candidates because instance manager on node is not ready" func="scheduler.(*ReplicaScheduler).getNodeCandidates" file="replica_scheduler.go:165" node=worker-ip-10-14-254-193-eu-de-03
longhorn-manager-29qcs longhorn-manager time="2025-08-29T04:22:57Z" level=debug msg="Excluding node in node candidates because instance manager on node is not ready" func="scheduler.(*ReplicaScheduler).getNodeCandidates" file="replica_scheduler.go:165" node=worker-ip-10-14-254-200-eu-de-03
longhorn-manager-ddtbw longhorn-manager time="2025-08-29T04:23:53Z" level=debug msg="Excluding node in node candidates because instance manager on node is not ready" func="scheduler.(*ReplicaScheduler).getNodeCandidates" file="replica_scheduler.go:165" node=worker-ip-10-14-254-252-eu-de-02
longhorn-manager-ddtbw longhorn-manager time="2025-08-29T04:23:53Z" level=debug msg="Excluding node in node candidates because instance manager on node is not ready" func="scheduler.(*ReplicaScheduler).getNodeCandidates" file="replica_scheduler.go:165" node=worker-ip-10-14-254-152-eu-de-01
longhorn-manager-ddtbw longhorn-manager time="2025-08-29T04:23:53Z" level=debug msg="Excluding node in node candidates because instance manager on node is not ready" func="scheduler.(*ReplicaScheduler).getNodeCandidates" file="replica_scheduler.go:165" node=worker-ip-10-14-254-252-eu-de-02
longhorn-manager-ddtbw longhorn-manager time="2025-08-29T04:23:53Z" level=debug msg="Excluding node in node candidates because instance manager on node is not ready" func="scheduler.(*ReplicaScheduler).getNodeCandidates" file="replica_scheduler.go:165" node=worker-ip-10-14-254-152-eu-de-01
longhorn-manager-ddtbw longhorn-manager time="2025-08-29T04:23:53Z" level=debug msg="Excluding node in node candidates because instance manager on node is not ready" func="scheduler.(*ReplicaScheduler).getNodeCandidates" file="replica_scheduler.go:165" node=worker-ip-10-14-254-152-eu-de-01
longhorn-manager-ddtbw longhorn-manager time="2025-08-29T04:23:53Z" level=debug msg="Excluding node in node candidates because instance manager on node is not ready" func="scheduler.(*ReplicaScheduler).getNodeCandidates" file="replica_scheduler.go:165" node=worker-ip-10-14-254-252-eu-de-02
```

The error happens in both nodes where volumes couldn’t get updated and in nodes where the live engine upgrade took place without any complications. We noticed that the `instanceManager` pod takes a bit to start running, but I'm sure that isn't the issue here, as the replicas with the new longhorn volume do get created eventually.

The problematic volumes all have replicas with the newer longhorn version (1.8.2) scheduled and running. Their number matches the number of the old replicas. What’s weird, is that the volumes that are stuck in this update limbo all get one extra replica, which gets created with the old longhorn version shortly after the update. So if the original replica count was 3, we get stuck with 8 replicas, split evenly between the old and the new longhorn version. Example output:

```sh
❯ k get replicas.longhorn.io -n longhorn-system -l longhornvolume=pvc-91984055-fdc3-43dc-838a-62a5b6fd62ea
NAME                                                  DATA ENGINE   STATE     NODE                               DISK                                   INSTANCEMANAGER                                     IMAGE                                                     AGE
pvc-91984055-fdc3-43dc-838a-62a5b6fd62ea-r-0746a74d   v1            running   worker-ip-10-14-254-169-eu-de-03   1135fba4-793e-4e73-b00c-5a85dee9e686   instance-manager-d9502a81f40f5cd090fe16007b2bc8ba   mtr.devops.telekom.de/longhornio/longhorn-engine:v1.7.2   44m
pvc-91984055-fdc3-43dc-838a-62a5b6fd62ea-r-21007d26   v1            running   worker-ip-10-14-254-172-eu-de-02   c155e568-a37a-4133-abf9-169884ee045f   instance-manager-a337d2c207d212ba249d1f28a6067faa   mtr.devops.telekom.de/longhornio/longhorn-engine:v1.8.2   44m
pvc-91984055-fdc3-43dc-838a-62a5b6fd62ea-r-2791f3a4   v1            running   worker-ip-10-14-254-159-eu-de-01   addeb0a7-d68a-49ab-9376-65f20a1df3ad   instance-manager-5a2aa040f6b7805e0668ae13961d7041   mtr.devops.telekom.de/longhornio/longhorn-engine:v1.7.2   170d
pvc-91984055-fdc3-43dc-838a-62a5b6fd62ea-r-284b5766   v1            running   worker-ip-10-14-254-169-eu-de-03   1135fba4-793e-4e73-b00c-5a85dee9e686   instance-manager-6f9d8d1f8e45f00d504c533c578e0197   mtr.devops.telekom.de/longhornio/longhorn-engine:v1.7.2   115d
pvc-91984055-fdc3-43dc-838a-62a5b6fd62ea-r-3305cf5d   v1            running   worker-ip-10-14-254-159-eu-de-01   addeb0a7-d68a-49ab-9376-65f20a1df3ad   instance-manager-ae6b8e89fd057b7064fb77e8d5a970d1   mtr.devops.telekom.de/longhornio/longhorn-engine:v1.8.2   44m
pvc-91984055-fdc3-43dc-838a-62a5b6fd62ea-r-5531f8d7   v1            running   worker-ip-10-14-254-172-eu-de-02   c155e568-a37a-4133-abf9-169884ee045f   instance-manager-9875dbe8f334b8b95c30777802a44397   mtr.devops.telekom.de/longhornio/longhorn-engine:v1.7.2   178d
pvc-91984055-fdc3-43dc-838a-62a5b6fd62ea-r-9a925df8   v1            running   worker-ip-10-14-254-169-eu-de-03   1135fba4-793e-4e73-b00c-5a85dee9e686   instance-manager-d9502a81f40f5cd090fe16007b2bc8ba   mtr.devops.telekom.de/longhornio/longhorn-engine:v1.8.2   44m
pvc-91984055-fdc3-43dc-838a-62a5b6fd62ea-r-deacccb7   v1            running   worker-ip-10-14-254-169-eu-de-03   1135fba4-793e-4e73-b00c-5a85dee9e686   instance-manager-d9502a81f40f5cd090fe16007b2bc8ba   mtr.devops.telekom.de/longhornio/longhorn-engine:v1.8.2   43m
```

The longhorn-manager seems to just skip the last “push” to really update the volumes and throw the old 1.7.2 replicas away. We thought, that just deleting a 1.7.2 replica would do the trick, but that doesn’t work all the time, we only get a new replica created (command is for another volume, not the same as above):

```sh
❯ k get replicas.longhorn.io -n longhorn-system -l longhornvolume=pvc-22588e86-fc98-4a0f-aaab-ef6670d047a0
NAME                                                  DATA ENGINE   STATE     NODE                               DISK                                   INSTANCEMANAGER                                     IMAGE                                                     AGE
pvc-22588e86-fc98-4a0f-aaab-ef6670d047a0-r-0181564b   v1            running   worker-ip-10-14-254-187-eu-de-02   be64d8b9-9f33-484a-95c0-15c752dc962d   instance-manager-dde51cd84077ecbb0ac0a8db72afac02   mtr.devops.telekom.de/longhornio/longhorn-engine:v1.8.2   37m
pvc-22588e86-fc98-4a0f-aaab-ef6670d047a0-r-37be7915   v1            running   worker-ip-10-14-254-216-eu-de-01   6f8941cd-8224-456b-a52f-8bd92095136f   instance-manager-5a4834a238432b9780761d2fc22cf055   mtr.devops.telekom.de/longhornio/longhorn-engine:v1.7.2   2m22s
pvc-22588e86-fc98-4a0f-aaab-ef6670d047a0-r-588c4fba   v1            running   worker-ip-10-14-254-169-eu-de-03   1135fba4-793e-4e73-b00c-5a85dee9e686   instance-manager-d9502a81f40f5cd090fe16007b2bc8ba   mtr.devops.telekom.de/longhornio/longhorn-engine:v1.8.2   37m
pvc-22588e86-fc98-4a0f-aaab-ef6670d047a0-r-71dbe340   v1            running   worker-ip-10-14-254-169-eu-de-03   1135fba4-793e-4e73-b00c-5a85dee9e686   instance-manager-d9502a81f40f5cd090fe16007b2bc8ba   mtr.devops.telekom.de/longhornio/longhorn-engine:v1.8.2   35m
pvc-22588e86-fc98-4a0f-aaab-ef6670d047a0-r-78627489   v1            running   worker-ip-10-14-254-169-eu-de-03   1135fba4-793e-4e73-b00c-5a85dee9e686   instance-manager-d9502a81f40f5cd090fe16007b2bc8ba   mtr.devops.telekom.de/longhornio/longhorn-engine:v1.7.2   37m
pvc-22588e86-fc98-4a0f-aaab-ef6670d047a0-r-7af597ff   v1            running   worker-ip-10-14-254-169-eu-de-03   1135fba4-793e-4e73-b00c-5a85dee9e686   instance-manager-6f9d8d1f8e45f00d504c533c578e0197   mtr.devops.telekom.de/longhornio/longhorn-engine:v1.7.2   115d
pvc-22588e86-fc98-4a0f-aaab-ef6670d047a0-r-b4fe10d4   v1            running   worker-ip-10-14-254-216-eu-de-01   6f8941cd-8224-456b-a52f-8bd92095136f   instance-manager-5a4834a238432b9780761d2fc22cf055   mtr.devops.telekom.de/longhornio/longhorn-engine:v1.8.2   37m
pvc-22588e86-fc98-4a0f-aaab-ef6670d047a0-r-b7f57904   v1            running   worker-ip-10-14-254-216-eu-de-01   6f8941cd-8224-456b-a52f-8bd92095136f   instance-manager-5a4834a238432b9780761d2fc22cf055   mtr.devops.telekom.de/longhornio/longhorn-engine:v1.8.2   2m7s
pvc-22588e86-fc98-4a0f-aaab-ef6670d047a0-r-d997a7a5   v1            running   worker-ip-10-14-254-187-eu-de-02   be64d8b9-9f33-484a-95c0-15c752dc962d   instance-manager-89ac571d2b06c3512f5e350ca8709ee5   mtr.devops.telekom.de/longhornio/longhorn-engine:v1.7.2   202d
```

What seems to work is if we force the volume to become degraded, by deleting old replicas (with the 1.7.2 version) until there are only `spec.replicaCount - 1` (2 in our case). This seems to trigger the update flow, and since 3 1.8.2 replicas are already available, the update goes through in a couple of seconds.

An additional bundle, where we tried the aforementioned workaround, is available in [my dropbox](https://www.dropbox.com/scl/fi/m2spuehe377opv0yemaqg/supportbundle_04e36757-9f61-423a-9226-ea829e50eb2f_2025-08-29T05-23-40Z.zip?rlkey=fwhe00k236z48crofgsh61ypr&st=gntki194&dl=0). The upload to github fails immediately 🤷. 

The PVCs that got stuck during the upgrade are:

- pvc-22588e86-fc98-4a0f-aaab-ef6670d047a0  
- pvc-31bf8879-57fb-476c-a7b7-f5a533cc03aa  
- pvc-57abafd3-e9f6-4bef-b983-73458c3c110e  
- pvc-842e3814-220a-4aaa-886f-7a341741ef6f  
- pvc-91984055-fdc3-43dc-838a-62a5b6fd62ea 
- pvc-ce7df9dc-05c4-4c19-9673-9eacb624fb2c  
- pvc-f723ac84-e781-4398-89af-65de05a6b307
