### ISSUE TITLE
[IMPROVEMENT] Remove isCLIAPIVersionOne related codes 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7191]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Many codes (isCLIAPIVersionOne) in longhorn-manager are handling incompatible instances. The ticket aims to see if the codes can be removed and simplify the codes.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn v1.8.0-dev-20241006 (https://github.com/longhorn/longhorn-manager/commit/f3d710b4cfd4b3c4278eb0a78d8b52043f6a57d0)

Did not observe outstanding issue related to `longhorn-manager` in master pipeline after the change
- longhorn-tests-sles-amd64 build [1072](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/1072/) - 1 failure
- longhorn-upgrade-tests-sles-amd64 build [927](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/927/) - 2 failures
