### ISSUE TITLE
[BUG] I/O Errors in node journal during node shutdown

### ISSUE THREAD

**Issue by thedarkside** [longhorn/longhorn#7206]
## Describe the bug (🐛 if you encounter this issue)

Seeing plenty of those errors in the journal log right before node shutdown (and boot again). The reboot is also taking longer then expected. 

```
Nov 25 23:18:18 testing-cloud-k8s-master kernel: sd 11:0:0:1: [sdf] tag#78 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=15s
Nov 25 23:18:18 testing-cloud-k8s-master kernel: sd 11:0:0:1: [sdf] tag#78 Sense Key : Medium Error [current] 
Nov 25 23:18:18 testing-cloud-k8s-master kernel: sd 11:0:0:1: [sdf] tag#78 Add. Sense: Unrecovered read error
Nov 25 23:18:18 testing-cloud-k8s-master kernel: sd 11:0:0:1: [sdf] tag#78 CDB: Write(10) 2a 00 00 00 00 00 00 00 08 00
Nov 25 23:18:18 testing-cloud-k8s-master kernel: blk_update_request: critical medium error, dev sdf, sector 0 op 0x1:(WRITE) flags 0x3800 phys_seg 1 prio class 0
Nov 25 23:18:18 testing-cloud-k8s-master kernel: Buffer I/O error on dev sdf, logical block 0, lost sync page write
Nov 25 23:18:18 testing-cloud-k8s-master kernel: EXT4-fs (sdf): I/O error while writing superblock
Nov 25 23:18:18 testing-cloud-k8s-master kernel: EXT4-fs (sdf): Remounting filesystem read-only
Nov 25 23:18:18 testing-cloud-k8s-master kernel: EXT4-fs (sdf): failed to convert unwritten extents to written extents -- potential data loss!  (inode 393220, error -30)
Nov 25 23:18:18 testing-cloud-k8s-master kernel: Buffer I/O error on device sdf, logical block 34849
Nov 25 23:18:18 testing-cloud-k8s-master kernel: Buffer I/O error on device sdf, logical block 34850
Nov 25 23:18:18 testing-cloud-k8s-master kernel: Buffer I/O error on device sdf, logical block 34851
Nov 25 23:18:18 testing-cloud-k8s-master kernel: Buffer I/O error on device sdf, logical block 34852
Nov 25 23:18:18 testing-cloud-k8s-master kernel: Buffer I/O error on device sdf, logical block 34853
Nov 25 23:18:18 testing-cloud-k8s-master kernel: Buffer I/O error on device sdf, logical block 34854
Nov 25 23:18:18 testing-cloud-k8s-master kernel: Buffer I/O error on device sdf, logical block 34855
Nov 25 23:18:18 testing-cloud-k8s-master kernel: Buffer I/O error on device sdf, logical block 34856
Nov 25 23:18:18 testing-cloud-k8s-master kernel: Buffer I/O error on device sdf, logical block 34857
Nov 25 23:18:18 testing-cloud-k8s-master kernel: Buffer I/O error on device sdf, logical block 34858
Nov 25 23:18:18 testing-cloud-k8s-master kernel: EXT4-fs (sdf): failed to convert unwritten extents to written extents -- potential data loss!  (inode 393220, error -30)
Nov 25 23:18:18 testing-cloud-k8s-master kernel: sd 10:0:0:1: [sde] tag#87 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=15s
Nov 25 23:18:18 testing-cloud-k8s-master kernel: sd 10:0:0:1: [sde] tag#87 Sense Key : Medium Error [current] 
Nov 25 23:18:18 testing-cloud-k8s-master kernel: sd 10:0:0:1: [sde] tag#87 Add. Sense: Unrecovered read error
Nov 25 23:18:18 testing-cloud-k8s-master kernel: sd 10:0:0:1: [sde] tag#87 CDB: Write(10) 2a 00 00 00 00 00 00 00 08 00
```
Ive seen already some bug reports mentioning those kind of errors but thought those got fixed.
The whole log from issuing a shutdown till poweroff is attached: 
[longhorn-errors-journal.log](https://github.com/longhorn/longhorn/files/13465421/longhorn-errors-journal.log)

After the cluster comes up the workloads are running as expected. 

## To Reproduce

Running a single node k3s cluster with some testing workload utilizing some RWO persistent volumes (postgres,...) on ubuntu 22.04 and issuing a `reboot` always produced those errors in the nodes journal above.
Setup is pretty default. OS is freshly provisioned, k3s cluster too!

I have also tried invoking `/usr/local/bin/k3s-killall.sh` before issuing a reboot. Still similar log entries. The killing script also hung for a while on a umount of a longhorn volume.

Also tried configuring the following without luck:
```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
shutdownGracePeriod: 30s
shutdownGracePeriodCriticalPods: 10s
```

## Expected behavior

Rebooting a node should gracefully reboot without risking data corruption. No such log entries should pop up

## Support bundle for troubleshooting

Not possible right after issuing the reboot. 

## Environment

 - Longhorn version: 1.5.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm Chart
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.27.7 +k3s2
   - Number of nodes: only 1
 - Node config
   - OS type and version: Ubuntu 22.04.3 LTS
   - Kernel version: 5.15.0-89-generic
   - CPU per node: Intel(R) Xeon(R) E-2176G CPU @ 3.70GHz
   - Memory per node: 64GB
   - Disk type(e.g. SSD/NVMe/HDD): HDD
   - Network bandwidth between the nodes: -
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 5
 - Impacted Longhorn resources: most of them

**Comment by derekbit** [comment]
Shut down the node when the volumes are still attached?

**Comment by thedarkside** [comment]
@derekbit yes ive tried it but as i mentioned ive tried also `/usr/local/bin/k3s-killall.sh` before shutdown. The command ran for 2 minutes or so. My expectation is that this is graceful behavior. 

If not, what should be done to restart a single node k3s cluster including longhorn gracefully?

**Comment by derekbit** [comment]
Took a quick check at `/usr/local/bin/k3s-killall.sh`, I don't think it detaches volumes gracefully.
You can scale down all workloads and the detach all volumes before shutting a node down for ensuring dirty data are flushed and persistent to disks.

**Comment by thedarkside** [comment]
Ive tested it now with `kubectl drain test-cloud-k8s-master --ignore-daemonsets --delete-emptydir-data --disable-eviction --force` and reboot after that. I do not see those logs anymore!

This is a surprise to me because i always thought k3s does it automatically under the hood. 

Thank you @derekbit!
