### ISSUE TITLE
[BUG] after upgrade 1.5.2->1.5.3 some share-manager-pvc-xxxx are missing

### ISSUE THREAD

**Issue by eltorio** [longhorn/longhorn#7207]
## Describe the bug (🐛 if you encounter this issue)

I upgrade from 1.5.2 to 1.5.3 via helm chart with:
```sh
STORAGE_LOCATION="/storage"
STORAGE_REPLICAS=1
LONGHORN_VERSION="1.5.3"
helm upgrade longhorn longhorn/longhorn --namespace longhorn-system --create-namespace --version $LONGHORN_VERSION \
    --set persistence.defaultClassReplicaCount=$STORAGE_REPLICAS,defaultSettings.defaultReplicaCount=$STORAGE_REPLICAS,defaultSettings.defaultDataPath=$STORAGE_LOCATION

```
And now two replicasets with RWX volume are stucked in Container creating. With error:
### Pod 1
```log
Normal   Scheduled               17m                  default-scheduler        Successfully assigned sctg-gitea/gitea-687c56b848-b7529 to azure-gypaete.azure-oci.private
  Normal   SuccessfulAttachVolume  17m                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-8797b29f-579d-479d-86f0-44c179d155a8"
  Warning  FailedMount             9m42s (x6 over 16m)  kubelet                  MountVolume.MountDevice failed for volume "pvc-8797b29f-579d-479d-86f0-44c179d155a8" : rpc error: code = Internal desc = context deadline exceeded (Client.Timeout or context cancellation while reading body)
  Warning  FailedMount             5m17s (x3 over 16m)  kubelet                  MountVolume.MountDevice failed for volume "pvc-8797b29f-579d-479d-86f0-44c179d155a8" : rpc error: code = Internal desc = Get "http://longhorn-backend:9500/v1/volumes/pvc-8797b29f-579d-479d-86f0-44c179d155a8": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  FailedMount             75s (x3 over 13m)    kubelet                  MountVolume.MountDevice failed for volume "pvc-8797b29f-579d-479d-86f0-44c179d155a8" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
### Pod 2
```log
 Normal   Scheduled               25m                 default-scheduler        Successfully assigned weblate/weblate-78cd9c5764-b5d5g to oci-vautour.private.jovetoci.oraclevcn.com
  Normal   SuccessfulAttachVolume  24m                 attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-02469a33-f06d-4d53-baf6-fb77081d13b2"
  Warning  FailedMount             44s (x10 over 22m)  kubelet                  MountVolume.MountDevice failed for volume "pvc-02469a33-f06d-4d53-baf6-fb77081d13b2" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

### Missing share-manager
`share-manager-pvc-02469a33-f06d-4d53-baf6-fb77081d13b2` is missing
`share-manager-pvc-8797b29f-579d-479d-86f0-44c179d155a8`is missing

## To Reproduce

Cluster Kubernetes 1.28.4 with 10 worker runners, all runners have /storage as the longhorn storage path
deploy Longhorn 1.4.4 
create some 12 replicasets with RWO, and 3 replicasets with RWX volumes.  
Upgrade path 1.5.1, update all engine images, 1.5.2 (don't touch images), 1.5.3 (update all engine images).  
restart the cluster.  

## Expected behavior

All the 3 share-manager-pvc must be up and running.

## Support bundle for troubleshooting

https://e.pcloud.link/publink/show?code=XZ7TMDZoQEIyy1zhhQvj9RQW4NU7bSVrx9V

## Environment

 - Longhorn version: 1.5.3
 - Installation method: Bare metal using [my own scripts](https://github.com/eltorio/oci-manage)
 - Kubernetes distro and version: kubernetes.io on 11 arm64 ubuntu 22.0.4 LTS
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 10
 - Node config
   - OS type and version: Ubuntu 22.0.4
   - Kernel version: 5.15.0
   - CPU per node: 4
   - Memory per node: 24GB
   - Disk type(e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes: 4Gb/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal on OCI VMs
 - Number of Longhorn volumes in the cluster: 15 (12 RWO, 3 RWX)
 - Impacted Longhorn resources:
   - Volume names: 
      - pvc-8797b29f-579d-479d-86f0-44c179d155a8
      - pvc-02469a33-f06d-4d53-baf6-fb77081d13b2

**Comment by derekbit** [comment]
Can you provide a support bundle?

**Comment by eltorio** [comment]
Yes it is in progression, but I created the issue for having the URL to put in the support bundle

**Comment by derekbit** [comment]
BTW, can you show the result of `kubectl -n longhorn-system get lhsm`?

**Comment by eltorio** [comment]
`kubectl -n longhorn-system get lhsm`
```log
NAME                                       STATE     NODE                                         AGE
pvc-02469a33-f06d-4d53-baf6-fb77081d13b2   running   oci-chocard.private.tricot.oraclevcn.com     88d
pvc-8039a4dd-4378-433d-9327-38711e151a1b   running   oci-choucas.private.joly.oraclevcn.com       9d
pvc-8797b29f-579d-479d-86f0-44c179d155a8   running   oci-autour.private.berangere.oraclevcn.com   29d
```

**Comment by derekbit** [comment]
It seems to hit the known issue https://github.com/longhorn/longhorn/issues/7183.
Can you try the [workaround](https://github.com/longhorn/longhorn/issues/7183#issuecomment-1823715359)? 

BTW, how did you restart the cluster? without any volume detachment?

**Comment by eltorio** [comment]
Support bundle is here https://e.pcloud.link/publink/show?code=XZ7TMDZoQEIyy1zhhQvj9RQW4NU7bSVrx9V

I'll try the workaround soon

**Comment by derekbit** [comment]
@eltorio 
Thanks for the support bundle. It is the same issue as https://github.com/longhorn/longhorn/issues/7183. You can apply the workaround to `pvc-02469a33-f06d-4d53-baf6-fb77081d13b2` and `pvc-8797b29f-579d-479d-86f0-44c179d155a8`. The solution is included in the next release.

**Comment by eltorio** [comment]
Workaround #7183 work:
```sh
kubectl -n longhorn-system patch lhsm pvc-02469a33-f06d-4d53-baf6-fb77081d13b2 --type=merge --subresource status --patch 'status: {state: error}'
kubectl -n longhorn-system patch lhsm pvc-b08581d7-f48c-4b27-8083-7f24b89ba4ea --type=merge --subresource status --patch 'status: {state: error}'
```

@derekbit 

> BTW, how did you restart the cluster? without any volume detachment?
I simulate a massive power issue with a script on the OCI shell issuing a simultaneous hard reset on the 11 VMs…
I did it for QA testing on this test cluster.
