### ISSUE TITLE
BackupstorePollInterval minimal value 0 to disable the feature should be documented

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#721]
Steps to reproduce:
  - In Longhorn UI, `Settings/General` page, set `Backupstore Poll Interval` to `0` and click `Save`.

**Comment by yasker** [comment]
When interval is 0, the backup polling would be disabled. Need to add instruction in the setting description.

https://github.com/longhorn/longhorn-manager/commit/4060d2e6b078c35d7de80ff2784944ffa9f007d4

**Comment by yasker** [comment]
@meldafrawi Please make sure backupstore polling is disabled. Notice if one volume has a new backup, the last backup would be updated automatically.

The disable of the feature can be tested by:
1. Creating two clusters, sharing one e.g. AWS S3 as backup target
2. Create a volume with the same volume name. Create a backup
3. The last backup on the other cluster shouldn't update (as long as you don't click on backup page to list all the volumes, which will trigger LastBackup update as well.)

**Comment by meldafrawi** [comment]
Validation: **PASSED**
