### ISSUE TITLE
[BUG] Test case `test_node_eviction`  failed

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#7210]
## Describe the bug (🐛 if you encounter this issue)

Test cases `test_node_eviction`, `test_node_eviction_no_schedulable_node`, `test_node_eviction_soft_anti_affinity`, `test_node_eviction_multiple_volume`, `test_disk_eviction_with_node_level_soft_anti_affinity_disabled`, `test_replica_auto_balance_zone_best_effort_with_data_locality` failed on [master-haed](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/734/testReport/junit/tests/test_node/test_node_eviction/), 
The replica could not be scheduled successfully on the on on the specified nodes. 
We also could reproduce the issue manually.

```python
    def test_node_eviction(client, core_api, csi_pv, pvc, pod_make, volume_name): # NOQA
        """
        Test node eviction (assuming this is a 3 nodes cluster)
    
        Case: node 1, 3 to node 1, 2 eviction
        1. Disable scheduling on node 2.
        2. Create pv, pvc, pod with volume of 2 replicas.
        3. Write some data and get the checksum.
        4. Set 'Eviction Requested' to 'false' and enable scheduling on node 2.
        5. Set 'Eviction Requested' to 'true' and disable scheduling on node 3.
        6. Check volume 'healthy' and wait for replicas running on node 1 and 2.
        7. Check volume data checksum.
        """
        nodes = client.list_node()
        node1 = nodes[0]
        node2 = nodes[1]
        node3 = nodes[2]
    
        # schedule replicas to node 1, 3
        set_node_scheduling(client, node2, allowScheduling=False, retry=True)
    
        data_path = "/data/test"
        pod_name, _, _, created_md5sum = \
            common.prepare_pod_with_data_in_mb(client, core_api, csi_pv,
                                               pvc, pod_make, volume_name,
                                               num_of_replicas=2,
                                               data_path=data_path)
    
        common.wait_for_replica_scheduled(client, volume_name,
                                          to_nodes=[node1.name, node3.name])
    
        # replica now running on node 1, 3
        # enable node 2
        set_node_scheduling_eviction(client,
                                     node2,
                                     allowScheduling=True,
                                     evictionRequested=False,
                                     retry=True)
        # disable node 3 to have replica schedule to node 1, 2
        set_node_scheduling_eviction(client,
                                     node3,
                                     allowScheduling=False,
                                     evictionRequested=True,
                                     retry=True)
    
>       common.wait_for_replica_scheduled(client, volume_name,
                                          to_nodes=[node1.name, node2.name])

test_node.py:2288: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

client = <longhorn.Client object at 0x7f3dc2749be0>
volume_name = 'longhorn-testvol-j6809r'
to_nodes = ['ip-10-0-2-155', 'ip-10-0-2-181'], expect_success = 2
expect_fail = 0, anti_affinity = False, chk_vol_healthy = True
chk_replica_running = True
```

## To Reproduce

        Case: node 1, 3 to node 1, 2 eviction
        1. Disable scheduling on `node 2`.
        2. Create pv, pvc, pod with volume of 2 replicas.
        3. Write some data and get the checksum.
        4. Set `Eviction Requested` to `false` and enable scheduling on `node 2`.
        5. Set `Eviction Requested` to `true` and disable scheduling on `node 3`.
        6. Check volume `healthy` and wait for replicas running on `node 1` and `node 2`.

## Expected behavior

Have consistent tested result in all branches result

## Support bundle for troubleshooting

[longhorn-tests-sles-amd64-733-bundle.zip](https://github.com/longhorn/longhorn/files/13468988/longhorn-tests-sles-amd64-733-bundle.zip)

## Environment

  - Longhorn version: master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): `Kubectl`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: `v1.27.1+k3s1`
   - Number of management node in the cluster:`1`
   - Number of worker node in the cluster:`3`
 - Node config
   - OS type and version: `SLES 15-sp5`
   - Kernel version:
   - CPU per node: `4 cores`
   - Memory per node: `16GB`
   - Disk type(e.g. SSD/NVMe/HDD): `SSD`
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): `AWS`
 - Number of Longhorn volumes in the cluster:`1`
 - Impacted Longhorn resources:
   - Volume names: `longhorn-testvol-j6809r`

**Comment by innobead** [comment]
cc @ejweber 

@roger-ryao this should be related to the recent change https://github.com/longhorn/longhorn-manager/pull/2138 https://github.com/longhorn/longhorn-manager/pull/2138/files#diff-506ad0bb11fcd6c38b2fd57ef08bd8f322e0700a008f9e5bc4121016e69349afR50-R58

**Comment by ejweber** [comment]
Moving this to `Ready For Testing` to trigger a look from QA.

**Comment by roger-ryao** [comment]
**Verified on master-head 20231218**

- longhorn master-head https://github.com/longhorn/longhorn/commit/a91f7966185ae0d5e19e1c2946ac551163bb0ebc
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/51524e0ace25b472fd369a2f182b9b543586b5ae


**The test steps**

Rerun the [regression](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/734/testReport/) and check the test results. 

**Result Passed**

The below test cases passed, and no failures were observed.

- [x] 1. `test_node_eviction`
- [x] 2. `test_node_eviction_no_schedulable_node`
- [x] 3. `test_node_eviction_soft_anti_affinity`
- [x] 4. `test_node_eviction_multiple_volume`
- [x] 5. `test_disk_eviction_with_node_level_soft_anti_affinity_disabled`
- [x] 6. `test_replica_auto_balance_zone_best_effort_with_data_locality`
