### ISSUE TITLE
[TASK] Bump up the minimum supported Kubernetes version

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#7224]
## What's the task? Please describe

- Kubernetes version support, min 1.26 to align with upstream ([1.29 is planned to be released on 12/5](https://www.kubernetes.dev/resources/release/#summary), 1.28 and 1.27 are actively supported. 1.25 was EOS on 10/27.)
  - As per https://metrics.longhorn.io/, 1.25 and 1.24 are primary installed versions. 
  - Rancher supported downstream cluster is RKE/2 1.26
  - RKE2 is supporting 1.28 - 1.26 which is aligned with upstream.
  - For the current Longhorn-supported versions, we will not change the existing supported min version of Kubernetes. 

## Describe the sub-tasks

- [x] Run e2e tests to ensure all passed including installation and upgrade
- [x] Support the supported K8s versions without issues
- [x] Prevent upgrading from any unsupported K8s versions with notice info, especially for helm chart installation

## Additional context

- https://github.com/longhorn/longhorn/issues/7001
- https://github.com/longhorn/longhorn/issues/2757
- https://github.com/longhorn/longhorn/issues/3891
- https://kubernetes.io/docs/reference/using-api/deprecation-guide/
- https://endoflife.date/kubernetes

**Comment by innobead** [comment]
https://kubernetes.io/releases/patch-releases/#support-period

**Comment by c3y1huang** [comment]
Test unsupported Kubernetes version:
```shell
> helm install longhorn ./chart/ --namespace longhorn-system --create-namespace
Error: INSTALLATION FAILED: chart requires kubeVersion: >=1.26.0-0 which is incompatible with Kubernetes v1.25.15+k3s2
```

**Comment by innobead** [comment]
Extra info about Kubernetes version support in public cloud providers is below:

AKS/EKS/GKE 1.25 support will soon reach out to EOL. 

- https://endoflife.date/google-kubernetes-engine
- https://endoflife.date/amazon-eks
- https://endoflife.date/azure-kubernetes-service

Also, RKE2/K3s 1.25 already reached EOL. They cover over 50% of installation from Longhorn usage metrics.

**Comment by PhanLe1010** [comment]
Sorry for the late comment. Up until now, we usually follow the convention that we only raise min supported Kubernetes version if keeping the current min K8s version makes it impossible to support the newest K8s version. Reference https://github.com/longhorn/longhorn/issues/3891#issuecomment-1131258472

Is it the case here?

**Comment by c3y1huang** [comment]
> Sorry for the late comment. Up until now, we usually follow the convention that we only raise min supported Kubernetes version if keeping the current min K8s version makes it impossible to support the newest K8s version. Reference [#3891 (comment)](https://github.com/longhorn/longhorn/issues/3891#issuecomment-1131258472)
> 
> Is it the case here?

Sorry I wasn't aware of the usual conversion. However, for the upcoming v1.6.0 release, we are aiming to align with the upstream-supported version life cycle. Unlike this usual approach, I think the decision to adjust the minimal supported version is driven by the need to upgrade the Kubernetes dependency libraries for CVE fixes. 
 AFAIK Kubernetes maintains backward compatibility with the client, but this may not be true the other way around.

This approach is also observed with Rancher and RKE. If the expectation is for Longhorn to support all versions until it becomes impractical, then we should consider having full regression tests on all the supported versions to ensure compatibility.

**Comment by roger-ryao** [comment]
**Verified on master-head 20231211**

- longhorn master-head https://github.com/longhorn/longhorn/commit/722642abc5fc2cda610975c89a3464189addc5ac

**Result Passed**

- [x] 1. We cannot install Longhorn `v1.6.0-dev` on k3s `v1.25` using Helm; it throws an error: `chart requires kubeVersion: >=1.26.0-0`.

```console
ryao@ryao-laptop:~/Desktop/longhorn/chart> helm install longhorn . --namespace longhorn-system --create-namespace
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/ryao/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/ryao/.kube/config
Error: INSTALLATION FAILED: chart requires kubeVersion: >=1.26.0-0 which is incompatible with Kubernetes v1.25.15+k3s2
```

- [x] 2. Review the document : https://github.com/longhorn/website/pull/804
- [x] 3. Execute coretest on k3s `v1.26`, `v1.27`, and `v1.28`

| K3s Version  | Test Job                                           | Upgrade Job                                       |
|--------------|--------------------------------------------------------|--------------------------------------------------------|
| **v1.26.11**+k3s1 | [Passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5363/) | [Passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5366/) |
| **v1.27.8**+k3s1 | [Passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5364/) | [Passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5367/) |
| **v1.28.4**+k3s1 | [Passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5365/) | [Passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5368/) |

**Comment by c3y1huang** [comment]
Base on the [discussion](https://suse.slack.com/archives/C02DR3N5T24/p1702346524490839?thread_ts=1702085596.721209&cid=C02DR3N5T24), we will revert the minimum version enforcement, and update the document to include the tested versions.

**Comment by c3y1huang** [comment]
@roger-ryao the revert PR is merged. And you've tested the suggested version. So we just need another test to ensure the minimum Kubernetes enforcement is back to `v1.21`. Thank you.

**Comment by roger-ryao** [comment]
**Verified on master-head 20231212**
- longhorn master-head https://github.com/longhorn/longhorn/commit/69739d8a63231934c5f7bb0c70619130be25fe23

**Result Passed**

1. We cannot install Longhorn `v1.6.0-dev` on k3s `v1.20` using Helm; it throws an error: `chart requires kubeVersion: >=1.21.0-0`.
