### ISSUE TITLE
Can't mount on a node a volume created from a backup

### ISSUE THREAD

**Issue by supermario18b** [longhorn/longhorn#7231]
Hi everyone,

I created a volume (testvol1) from a backup and I tried to mount it on a node but I got this error:

`unable to attach volume testvol1 to k3s-node1: cannot attach volume testvol1 because the engine image longhornio/longhorn-engine:v1.5.3 is not deployed on at least one of the the replicas' nodes or the node that the volume is going to attach to`

I'm running a 3 nodes k3s cluster and the engine image v1.5.3 runs on all nodes. Here is some output, it seems ok to me:

`daemonset.apps/engine-image-ei-68f17757   3         3         3       3            3           <none>          42h   engine-image-ei-68f17757                                            longhornio/longhorn-engine:v1.5.3`

`kubectl get nodes.longhorn.io -n longhorn-system`
k3s-node1   True    true              True          42h
k3s-node2   True    true              True          42h
k3s-node3   True    true              True          42h

`kubectl get nodes`
k3s-node1   Ready    control-plane,etcd,master   44h   v1.27.7+k3s2
k3s-node2   Ready    control-plane,etcd,master   44h   v1.27.7+k3s2
k3s-node3   Ready    control-plane,etcd,master   44h   v1.27.7+k3s2

Could you please tell me, what I can try?

Thanks in advance,

supermario18b

P.S. Backup was saved on a s3 bucket

**Comment by ejweber** [comment]
Thanks for opening an issue @supermario18b!

A full support bundle would be very helpful here. Are you able to provide one?

If not, the output of `kubectl get engineimage -n longhorn-system -oyaml` might be helpful (no guarantees). It is actually this resource that we directly check (not the pods) to determine if the engine image is deployed.

**Comment by supermario18b** [comment]
Hi @ejweber,
thank you for the reply. I've generated a full support bundle on the ui with the url of this issue. A zip file was created, where do I have to upload that? here as an attachment?

In the meantime here is the output of `kubectl get engineimage -n longhorn-system -oyaml` (it seems ok to me). I use "longhorn-storage" as namespace, but I don't think it is a problem.

apiVersion: v1
items:
- apiVersion: longhorn.io/v1beta2
  kind: EngineImage
  metadata:
    creationTimestamp: "2023-11-28T19:44:30Z"
    finalizers:
    - longhorn.io
    generation: 1
    labels:
      longhorn.io/component: engine-image
      longhorn.io/engine-image: ei-68f17757
      longhorn.io/managed-by: longhorn-manager
    name: ei-68f17757
    namespace: longhorn-storage
    resourceVersion: "602685"
    uid: 392774fa-a635-4579-931b-e7a6a77cdccd
  spec:
    image: longhornio/longhorn-engine:v1.5.3
  status:
    buildDate: "2023-11-17T01:35:05+00:00"
    cliAPIMinVersion: 3
    cliAPIVersion: 9
    conditions:
    - lastProbeTime: ""
      lastTransitionTime: "2023-12-01T07:37:16Z"
      message: Engine image ei-68f17757 (longhornio/longhorn-engine:v1.5.3) is fully
        deployed on all ready nodes
      reason: ""
      status: "True"
      type: ready
    controllerAPIMinVersion: 3
    controllerAPIVersion: 5
    dataFormatMinVersion: 1
    dataFormatVersion: 1
    gitCommit: 0b4930a789063adc07e8d60f923b050a5e653029
    noRefSince: ""
    nodeDeploymentMap:
      k3s-node1: true
      k3s-node2: true
      k3s-node3: true
    ownerID: k3s-node3
    refCount: 23
    state: deployed
    version: v1.5.3
kind: List
metadata:
  resourceVersion: ""

**Comment by supermario18b** [comment]
here is the bundle as attachment. Thank you
[Uploading supportbundle_a9f7b626-a9ed-40d0-8aab-ecff2bc28fc7_2023-12-01T07-44-56Z.zip…]()

**Comment by supermario18b** [comment]
@ejweber I've just sent the file to longhorn-support-bundle@suse.com

Thank you!

**Comment by ejweber** [comment]
Got it. I'll take a look this morning!

**Comment by ejweber** [comment]
It looks like the actual problem is that there is no disk with space to schedule replicas for `testvol1`. The calculation you are running up against is:

```
(Size + Storage Scheduled) <= ((Storage Maximum - Storage Reserved) * Over Provisioning Percentage / 100)
```

- `testvol1` has a Size of `8.0 GiB`.
- `default-disk-<k3s-node1>` has a Storage Scheduled of `17.0 GiB`
- `default-disk-<k3s-node1>` has a Storage Maximum of `27.3 GiB`
- `default-disk-<k3s-node1>` has a Storage Reserved of `2.7 GiB`
- The cluster has an Over Provisioning Percentage of `100(%)`

`8.0 GiB + 17.0 GiB = 25.0GiB > 24.6 GiB = (27.3 GiB - 2.7 GiB) * (100 / 100)`

You can tweak the `storage-over-provisioning-percentage` setting or the `storageReserved` for each disk if you want to get this volume running.

This log message is quite misleading. I'll dive into the code a bit and see if I can figure out why it's being triggered (and if there's a way to trigger something better).

**Comment by ejweber** [comment]
`kubectl get volume -n longhorn-system testvol1` (or the UI) should show the following condition:

```
        - lastProbeTime: "null"
          lastTransitionTime: "2023-12-01T07:43:42Z"
          message: insufficient storage
          reason: ReplicaSchedulingFailure
          status: "False"
          type: Scheduled
```
