### ISSUE TITLE
Crashloop backoff with K3s 1.28

### ISSUE THREAD

**Issue by fabltd** [longhorn/longhorn#7233]
Hi All

I have this error:

```
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3+k3s2
```

All pods crash:

```
longhorn-driver-deployer-54d5cddccc-ckfd8   0/1     Init:0/1           0               25m
longhorn-manager-fhhkb                      0/1     CrashLoopBackOff   9 (4m31s ago)   25m
longhorn-manager-qnfqs                      0/1     CrashLoopBackOff   9 (4m45s ago)   25m
longhorn-manager-w6f9g                      0/1     CrashLoopBackOff   9 (4m54s ago)   25m
longhorn-ui-5b974686f-7684p                 1/1     Running            0               25m
longhorn-ui-5b974686f-mtmwh                 1/1     Running            0               25m

```

I have tried running:

curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/master/scripts/environment_check.sh | bash

Still fails. Where to debug next ?

This is running on K3s on a Raspberry PI cluster. Its a brand new cluster install so this makes no sense.

Thanks

**Comment by fabltd** [comment]
The fix for this is to SSH into each node and install:

sudo apt install open-iscsi

Then reboot.

**Comment by ejweber** [comment]
Thanks for the update @fabltd! The missing open-iscsi is something the environment check script you ran should have caught.

https://github.com/longhorn/longhorn/blob/866f1155f74037bb41bbaf3d4f8e3707f71b573f/scripts/environment_check.sh#L308-L320

> I have tried running:
>
> curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/master/scripts/environment_check.sh | bash
>
> Still fails. Where to debug next ?

Can you clarify? Did that script successfully identify the problem?

We also provide a helper iSCSI installer to help you avoid having to do it manually if you choose. See details [here](https://longhorn.io/docs/1.5.3/deploy/install/#installing-open-iscsi).
