### ISSUE TITLE
controller: engine: sometimes engines are slow to detach due to empty `NodeID`

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#724]
Version: v0.6.0-dev

When an instance manager's status changed, we are trying to find the related engine by using the engine's nodeID (https://github.com/longhorn/longhorn-manager/blob/946c027c43a1a6c3a7e7b6913e3e1d4624a186a0/controller/engine_controller.go#L309). But the engine's nodeID will be unset by the volume controller during the detach process (https://github.com/longhorn/longhorn-manager/blob/946c027c43a1a6c3a7e7b6913e3e1d4624a186a0/controller/volume_controller.go#L689), result in the engine won't be enqueued once instance manager found the engine has stopped running, then the engine state wouldn't be changed to `stopped` immediately, thus delay the detach process.

**Comment by yasker** [comment]
To reproduce, try attaching/detaching a volume 10 times. Both actions should take around 5 seconds. In the RC1, it may take more than 10 seconds for detaching to happen.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
