### ISSUE TITLE
[QUESTION] Where is the code of tgtd with bs_type longhorn ?

### ISSUE THREAD

**Issue by cocalele** [longhorn/longhorn#7257]
## Question
Hi, 
It seems you extend tgtd with new backend type 'longhorn'. 
where is the code of tgtd with that extension?

**Comment by mantissahz** [comment]
Hi @cocalele 
Here is https://github.com/rancher/tgt/blob/longhorn_oct2019/usr/bs_longhorn.c
We have our repo for developing `tgt`.
