### ISSUE TITLE
[BUG] After shutting down cluster, no volumes can attach anymore. Stuck on volume attachment is being deleted.

### ISSUE THREAD

**Issue by LP0101** [longhorn/longhorn#7258]
## Describe the bug (🐛 if you encounter this issue)

I had to shut down my Kubernetes cluster. In preparation, I scaled all workloads to 0 replicas first, which should have allowed longhorn volumes to detach. However, when starting it up, none of the volumes that were previously attached are working.
The errors are:
```
  ----     ------              ----               ----                     -------
  Normal   Scheduled           32s                default-scheduler        Successfully assigned media-management/radarr-0 to minas-tirith-1
  Warning  FailedAttachVolume  31s                attachdetach-controller  AttachVolume.Attach failed for volume "radarr-appdata" : volume attachment is being deleted
  Warning  FailedMount         11s (x6 over 27s)  kubelet                  MountVolume.WaitForAttach failed for volume "radarr-appdata" : volume attachment is being deleted
```
I had another volume that I tried to troubleshoot by manually deleting the volumeattachment, that one is instead giving this error now:
```
  ----     ------              ----                 ----                     -------
  Normal   Scheduled           7m46s                default-scheduler        Successfully assigned authentik/authentik-pgsql-0 to minas-tirith-1
  Warning  FailedAttachVolume  2m12s                attachdetach-controller  AttachVolume.Attach failed for volume "pvc-d2ebec96-9fa2-4173-81e7-72096cb7c041" : timed out waiting for external-attacher of driver.longhorn.io CSI driver to attach volume pvc-d2ebec96-9fa2-4173-81e7-72096cb7c041
  Warning  FailedMount         68s (x3 over 5m43s)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[pgdata], unattached volumes=[pgdata dshm kube-api-access-pzsvt]: timed out waiting for the condition
  Warning  FailedMount         23s (x4 over 6m29s)  kubelet                  MountVolume.WaitForAttach failed for volume "pvc-d2ebec96-9fa2-4173-81e7-72096cb7c041" : watch error:unknown (get volumeattachments.storage.k8s.io) for volume pvc-d2ebec96-9fa2-4173-81e7-72096cb7c041
```

Note: I manually removed the finalizer from that volumeattachment. Any time I try to delete a volumeattachment, it just hangs

## To Reproduce

Scale down all workloads, shut off the cluster, then turn it back on.

## Expected behavior

Volumes should recover properly after a clean shutdown and power on.

## Support bundle for troubleshooting

[supportbundle_f01063b4-0ae3-45ce-9171-daf80722b282_2023-12-05T04-44-17Z.zip](https://github.com/longhorn/longhorn/files/13555248/supportbundle_f01063b4-0ae3-45ce-9171-daf80722b282_2023-12-05T04-44-17Z.zip)

## Environment

 - Longhorn version: 1.4.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K8S (kubeadm)
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - Kernel version: 5.15.0-89-generic
   - CPU per node: 8
   - Memory per node: 16 GB
   - Disk type(e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes: 1 GB/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Comment by LP0101** [comment]
After scaling the workloads down to 0 and then back up, I'm getting this error now instead:
```
  ----     ------              ----                  ----                     -------
  Normal   Scheduled           6m                    default-scheduler        Successfully assigned authentik/authentik-pgsql-0 to minas-tirith-1
  Warning  FailedMount         100s (x2 over 3m57s)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[pgdata], unattached volumes=[pgdata dshm kube-api-access-fb6n7]: timed out waiting for the condition
  Warning  FailedAttachVolume  0s (x3 over 4m)       attachdetach-controller  AttachVolume.Attach failed for volume "pvc-d2ebec96-9fa2-4173-81e7-72096cb7c041" : timed out waiting for external-attacher of driver.longhorn.io CSI driver to attach volume pvc-d2ebec96-9fa2-4173-81e7-72096cb7c041
```

**Comment by LP0101** [comment]
Issue was fixed by scaling down all workloads again, waiting for every volume to detach, then scaling up again.

**Comment by mreiche** [comment]
Same issue here. Pods are inexistent, but Volume still beeing attached. Force detach in Longhorn UI won't help.

**Comment by rstoermer** [comment]
Same problem here, scaling down the workloads didn't help, I had to delete the volumeattachment manually via kubectl.

**Comment by derekbit** [comment]
> Same problem here, scaling down the workloads didn't help, I had to delete the volumeattachment manually via kubectl.

@rstoermer What's your Longhorn version?

**Comment by rstoermer** [comment]
> > Same problem here, scaling down the workloads didn't help, I had to delete the volumeattachment manually via kubectl.
> 
> @rstoermer What's your Longhorn version?

v1.8.0

**Comment by derekbit** [comment]
@rstoermer Please create a new ticket and provide a support bundle and required information for further investigation. Thank you.

**Comment by mehrdadpfg** [comment]
same here after a dns issue
