### ISSUE TITLE
[IMPROVEMENT] Gracefully shut down spdk_tgt

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7263]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

To avoid data corruption or data recovery in SPDK blobstore, instance-manager pod should gracefully shut down spdk_tgt.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-instance-manager `96446a`) with test [steps](https://github.com/longhorn/longhorn/issues/7263#issuecomment-1841167496)

Can reproduce in `v1.5.3`, the same [steps](https://github.com/longhorn/longhorn/issues/7263#issuecomment-1841167496) on master-head did not seen `Performing recovery on blobstore` related logs in instance-manager pod.
