### ISSUE TITLE
The replica state of restoration volume becomes RW or empty intermittently in UI

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#727]
The reason for this bug:
1. For longhorn manager api model, it will use `e.Spec.NodeID == v.Spec.NodeID` to find the matching engine. Since sometimes the volume **engine's** `NodeID` is different from the **restoration volume's**. The engine is nil then the replica state becomes empty.

2. This mismatch is caused by the volume controller. It will **repeatedly** find a random ready node and set `NodeID` for restoration volume  **even if the field has been set**. This means the restoration volume's `NodeID` will be modified then it's different from engine's `NodeID`.

**Comment by yasker** [comment]
...

And by mistake [the line](https://github.com/longhorn/longhorn-manager/blob/86ca7c6ebb9617dbaa881cee0350e6fb13acb4f0/controller/volume_controller.go#L829) should catch the changing nodeID failed because the engine is already set to running.

Filed #728 for it.

**Comment by shuo-wu** [comment]
The reproduce step is simple:
Create a restoration volume from backup, and it's better to choose a large backup.

For old version:
1. In the volume detail page of Longhorn UI, the replica background may suddenly gray out when the volume is restoring data.
2. In the HTTP response of the restoration volume, the replica state becomes RW or empty intermittently.
3. Check the `NodeID` of the volume via `kubectl -n longhorn-system get lhv <your-restoration-volume-name> -o yaml`,  the field may be changed.

For the new version:
1. In the volume detail page of Longhorn UI, the replica background keeps blue when the volume is restoring data.
2. In the HTTP response of the restoration volume, the replica state is always `RW`.
3. The `NodeID` of the volume is constant during restoration.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
