### ISSUE TITLE
[INFRA] Have a pipeline to mirror support-bundle-kit to longhornio

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#7286]
## What's the test to develop? Please describe

We are regularly updating the `support-bundle-kit` to resolve CVE fixes. It will improve the workflow to have a pipeline that enables self-triggering the mirroring from `rancher/support-bundle-kit` to `longhornio`.

## Describe the items of the test development (DoD, definition of done) you'd like

- [x] A pipeline for support-bundle-kit mirroring

## Additional context
`None`

**Comment by innobead** [comment]
@yangchiu aren't we able to do it right now?
