### ISSUE TITLE
[BUG] backingimage download server error

### ISSUE THREAD

**Issue by m-ildefons** [longhorn/longhorn#7288]
## Describe the bug (🐛 if you encounter this issue)

When creating a new backing image for a volume via the web UI, the UI shows a spinner for a few seconds and then updates the list with the new backing image. There is nothing indicating the status of the backing image and it would be reasonable to assume the backing image is ready. However this may not necessarily be the case, and immediately clicking on the download button results in a server error (status code 500, see screenshot).

## To Reproduce

Create a backing image by export from a longhorn volume of a few GB in size using `raw` format and immediately initiate download action.

## Expected behavior

- The backing image list should show a status of the respective backing images, indicating whether or not it's ready for download
- The download action should be inactive while the backing image is not ready for download yet
- It should be impossible to cause a server error while using the UI

Additional notes on UX:
- When (successfully) initiating the download of a backing image, the file name of the downloaded file is the uuid of the backing image. However it would probably be more user friendly to set this to the name of the backing image to make the identification later on easier.
- The list of backing images shows the creation method. In case of export from a volume, it would be user friendly to also show the name of the volume here. Right now this information is only available in the detailed view
- The search/filter bar should also be able to search/filter by uuid and other properties, not just the name of the backing image
- The detailed view shows the status of an individual backing image, but this has no coloration
- The cleanup dialogue is confusing and uses incorrect English, it's unclear why it exists since the only operation (delete) is also directly supported
- The backing image files seem to be uncompressed. This can lead to potentially long download/upload times. It would be nice to use compression at least while downloading.
- Bulk downloads of multiple images are not supported in the UI, this can be tedious when dealing with many images/volumes.
- The backing images view should have an action to directly create a volume from a backing image

## Environment

 - Longhorn version: 1.6-dev (docker.io/longhornio/longhorn-manager@sha256:16a45ba592814751061922ec3b45e5e6a2789aa73e1ededb00d96f5b6b8c4e8e)
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Vanilla K8s (kubeadm):
 ```
 Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.17", GitCommit:"22a9682c8fe855c321be75c5faacde343f909b04", GitTreeState:"clean", BuildDate:"2023-08-23T23:37:25Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
 ```
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: SLE 15 SP4
   - Kernel version: `Linux kratos 5.14.21-150400.24.63-default #1 SMP PREEMPT_DYNAMIC Tue May 2 15:49:04 UTC 2023 (fd0cc4f) x86_64 x86_64 x86_64 GNU/Linux`
   - CPU per node: 16
   - Memory per node: 64GiB
   - Disk type(e.g. SSD/NVMe/HDD): NVMe
   - Network bandwidth between the nodes: 1000Mb/s (1000baseT/Full)
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 1
 - Impacted Longhorn resources: backingimages
 
## Additional context
![Screenshot at 2023-12-07 11-46-12](https://github.com/longhorn/longhorn/assets/17141774/c6aea848-c6dd-4226-9a10-d6909253c50c)

**Comment by innobead** [comment]
cc @ChanYiLin

**Comment by ChanYiLin** [comment]
Hi @m-ildefons thanks for your feedbacks
Those are really helpful for use to improve the user experience!

Some ideas I think we can definitely create issues to improve them
1. BackingImage download server error:
    - You are right, we can disable `download` button when the BackingImage is not ready. And add status to the BackingImage list
    - Internal Server Error means Longhorn doesn't expect the operation. By applying above ideas I think we could prevent triggering Internal Server Error in this case.
  2. BackingImage file name: Yes we should use BackingImage instead of UUID
  3. BackingImage exported from Volume should show the volume name: agree
  4. Filter: agree
  5. Should apply compression method when download BackingImage: agree
  6. Bulk download: agree
  7. Create volumes from a BackingImage page: agree 


For the above ideas, I will create UI/Backend tickets for them.
There are also some topics I would like to further discuss with you and get more information.

> - The detailed view shows the status of an individual backing image, but this has no coloration
> - The cleanup dialogue is confusing and uses incorrect English, it's unclear why it exists since the only operation (delete) is also directly supported

BackingImage is not just stored in one place in Longhorn, in facts, it will be copied and stored on different disks of the nodes if the replicas on that nodes/disks need the BackingImage.

That's why we need to list the status of the BackingImage on the different disk.
`Cleanup` operation then allows users to delete the BackingImage on specific disks to save some space if they know there won't be any replicas on that disk requiring BackingImage. Users can't delete the last BackingImage in this operation or there won't have BackingImage file in the system.

`Delete` operations means Longhorn will delete the BackingImage on all disks and also delete the BackingImage CR.

**Comment by ChanYiLin** [comment]
I have created a ticket to improve the user experience.
We can focus on disabling download when BackingImage is not ready in this issue.

I think from the UI side, it can check the `diskFileStatusMap` in the json.
If there is no BackingImage is ready, we can disable the download.

**Comment by m-ildefons** [comment]
> - The detailed view shows the status of an individual backing image, but this has no coloration

What I mean by that is that the detailed view may show `ready` or `in progress`, but it's all in the same color:

![Screenshot at 2023-12-08 10-17-40](https://github.com/longhorn/longhorn/assets/17141774/86941347-7a13-4706-94e2-d71e8f80c156)

 I think we should use colors for the status text just like in other places of the UI. E.g. the nodes display their status with green when it's good or grey when they are unschedulable for some reason:
 
![Screenshot at 2023-12-08 10-18-23](https://github.com/longhorn/longhorn/assets/17141774/d816070b-517c-4231-a6d7-c36b0c0bf8a9)

> BackingImage is not just stored in one place in Longhorn, in facts, it will be copied and stored on different disks of the nodes if the replicas on that nodes/disks need the BackingImage.
>
> That's why we need to list the status of the BackingImage on the different disk.
Cleanup operation then allows users to delete the BackingImage on specific disks to save some space if they know there won't be any replicas on that disk requiring BackingImage. Users can't delete the last BackingImage in this operation or there won't have BackingImage file in the system.
>
> Delete operations means Longhorn will delete the BackingImage on all disks and also delete the BackingImage CR.

Thanks for explaining this. I still find it a bit convoluted from a UX perspective, but I understand why it is this way.
IMO, the user experience could be improved by merging the functionality of the cleanup dialogue in the detailed view and getting rid of the cleanup dialogue entirely. Also showing which node a copy of the backing image is stored on in the detailed view would be more helpful than showing the uuid of the disk.

> I think from the UI side, it can check the diskFileStatusMap in the json.
> If there is no BackingImage is ready, we can disable the download.

This sounds like a good approach to hide the error.

**Comment by ChanYiLin** [comment]
Hi @m-ildefons thanks for the details, 
I have updated the feature requests in issue #7293

**Comment by ChanYiLin** [comment]
> I have created a ticket to improve the user experience. We can focus on disabling download when BackingImage is not ready in this issue.
> 
> I think from the UI side, it can check the `diskFileStatusMap` in the json. If there is no BackingImage is ready, we can disable the download.

Hi @innobead 
This issue can also be fixed by from UI side

**Comment by ChanYiLin** [comment]
## Note

For this issue we can improve from the UI side
We can check the diskFileStatusMap in the json returned from the BackingImage API.
If there is no BackingImage is ready on any disk, we should disable the download button.

**Comment by innobead** [comment]
> ## Note
> For this issue we can improve from the UI side We can check the diskFileStatusMap in the json returned from the BackingImage API. If there is no BackingImage is ready on any disk, we should disable the download button.
> 
> cc @scures

@roger-ryao This is the info for testing.

**Comment by roger-ryao** [comment]
**Verified on master-head 20231228**

- longhorn master-head https://github.com/longhorn/longhorn/commit/07bdb419a968633059c24db35ec66d7d68d73f4c
- longhorn-ui master-head https://github.com/longhorn/longhorn-ui/commit/d916e44fe449e00a68cc0fb829c728a1ec5da97a

**The test steps**
https://github.com/longhorn/longhorn/issues/7288#issuecomment-1855262472

**Result Passed**

When the `state` in the `diskFileStatusMap` dictionary is not `ready`, the Download icon is grayed out. After the `state` becomes `ready`, we can download the `backing image` from the UI.

**Comment by roger-ryao** [comment]
Hi @scures :
     Please help backport https://github.com/longhorn/longhorn-ui/pull/670 to `v1.5.x `and `v1.4.x`. After that, I can assist in verifying issues https://github.com/longhorn/longhorn/issues/7381 and https://github.com/longhorn/longhorn/issues/7382.

Thank you!
