### ISSUE TITLE
[IMPROVEMENT] Replace deprecated grpc.WithInsecure

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#7291]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

https://pkg.go.dev/google.golang.org/grpc#WithInsecure

## Describe the solution you'd like

- [x] Replace the deprecated grpc.WithInsecure.

## Describe alternatives you've considered

`None`

## Additional context

None

**Comment by innobead** [comment]
@c3y1huang just add to the current milestone because u are working on it.
