### ISSUE TITLE
[BUG] all recurring jobs failing on detached volumes

### ISSUE THREAD

**Issue by akelge** [longhorn/longhorn#7292]
## Describe the bug

Since I upgraded to 1.5.3 from 1.5.1 the recurring trim job is failing. It is scheduled to run every two hours, and it fails on some RWX volumes that are detached.

One of these volumes lost the recurring job groups and adding them again in the UI, although the correct annotation was present in the `Volume` object, fixed the issue, but now there is another volume that make the trimmer job fail and it is in good state, has the annotation in the `Volume` job, in the UI I can see it is in the correct recurring jobs groups.

The error I get from the failing job is 
```
time="2023-12-08T08:19:01Z" level=fatal msg="Failed to do a recurring job" func=app.RecurringJobCmd.func1 file="recurring_job.go:76" error="failed to complete filesystem-trim for : Action [trimFilesystem] not available on [&{pvc-7453b44e-eb8d-470f-bcd6-c0cf82e07ac9 volume 
...
```
I have omitted some parts of the log line, as they are list of the API endpoints to manage the volume.

## To Reproduce

Run a recurring job of type `filesystem-trim`

## Expected behavior

The job should complete and trim all the attached volumes.

## Support bundle for troubleshooting

https://drive.google.com/file/d/146fP3xcElseEtCqwCJj3n9acWZTyZjYZ/view?usp=drive_link

## Environment

 - Longhorn version: 1.5.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm chart
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 6
 - Node config
   - OS type and version: Centos Stream 8
   - Kernel version: 5.4.210
   - CPU per node: 4
   - Memory per node: 16Gb
   - Disk type(e.g. SSD/NVMe/HDD): AWS EBS volumes
   - Network bandwidth between the nodes: 10Gb
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 121
 - Impacted Longhorn resources:
   - Volume names: pvc-7453b44e-eb8d-470f-bcd6-c0cf82e07ac9

## Additional context

Here is the definition of the recurring job
```
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  creationTimestamp: "2023-08-01T05:56:11Z"
  generation: 6
  name: fs-trimmer
  namespace: longhorn-system
  resourceVersion: "375212865"
  uid: 2d4ebd47-f6c3-46b4-8c3e-e3f4b08d6e72
spec:
  concurrency: 5
  cron: 20 */6 * * *
  groups:
  - default
  - retained-replicas
  - backup
  labels:
    job: fs-trimmer
  name: fs-trimmer
  retain: 0
  task: filesystem-trim
```

**Comment by derekbit** [comment]
From the support bundle, other RWX volumes can be trimmed except for this volume `pvc-7453b44e-eb8d-470f-bcd6-c0cf82e07ac9`. Is it correct?

**Comment by derekbit** [comment]
The pod of `pvc-7453b44e-eb8d-470f-bcd6-c0cf82e07ac9` is somehow missing. I think you hit the issue https://github.com/longhorn/longhorn/issues/7183, please try the workaround.

**Comment by akelge** [comment]
Regarding https://github.com/longhorn/longhorn/issues/7292#issuecomment-1846789873 I can't know, the trimming job was failing on other volumes that were no more needed, so I deleted them, but each time I fix a volume, another one fails.
So I am not sure if fixing volume `pvc-7453b44e-eb8d-470f-bcd6-c0cf82e07ac9` would solve the issue, or if I would find another volume failing.

**Comment by akelge** [comment]
I tried to delete all the LHSM ojects, they have been recreated, I also killed all the running `share-manager` pods and have the recreated, the job is still failing, here is a new support bundle
https://drive.google.com/file/d/15VOBaluJYKCBHTQV1EkQmxqNWHU3FgG8/view?usp=sharing

**Comment by akelge** [comment]
Well, one thing to add:
I have just found that the volume that is failing now has empty value under Recurring Job Schedule -> Group, while the others have `default` as group.
I checked all the `Volume` object on kubernetes and they have the correct label `recurring-job-group.longhorn.io/default: enabled`, but it seems this is not reflected in the UI.

I don't know if this is related, also because if they are not in `defautl` group the trimming job should skip them, cause the trimming job has
```
  groups:
  - default
  ```
  in its definition and I would expect it to skip volumes that are not in the default group.

**Comment by derekbit** [comment]
> I tried to delete all the LHSM ojects, they have been recreated, I also killed all the running `share-manager` pods and have the recreated, the job is still failing, here is a new support bundle https://drive.google.com/file/d/15VOBaluJYKCBHTQV1EkQmxqNWHU3FgG8/view?usp=sharing

What's the purpose of deleting share-manager pod...?
> 
> We didn't do changes from 1.5.1 to 1.5.3 to the volumes, they are the same, in the same status

**Comment by akelge** [comment]
> > I tried to delete all the LHSM ojects, they have been recreated, I also killed all the running `share-manager` pods and have the recreated, the job is still failing, here is a new support bundle https://drive.google.com/file/d/15VOBaluJYKCBHTQV1EkQmxqNWHU3FgG8/view?usp=sharing
> 
> What's the purpose of deleting share-manager pod...?
To be sure the changes have been picked up, given that changing manually the status to `error` didn't cause any change

**Comment by akelge** [comment]
More info: I think that the issue is happening if there are detached volumes (maybe only with RAX, at the moment I only have RWX volumes detached and I don't have time to test creating an RWO), on other clusters I have no problems, but I also don't have detached volumes

**Comment by akelge** [comment]
I fixed it, I had to change the setting `Allow Recurring Job While Volume Is Detached` and set it to `false`, other than that I had some volumes hung, they appeared to longhorn as attached, while they weren't. In the end I had to manually remove the related `volumeattachments.storage.k8s.io` and `volumeattachments.longhorn.io` to make them detached and I could restart the workload that uses them
