### ISSUE TITLE
[IMPROVEMENT] BackingImage UI improvement

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#7293]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

From this issue #7288  we would like to improve some user experiences of BackingImage
- In BackingImage page
  - [x] BackingIamge should show the **source** of it. This can be retrieved from the `parameters` in the json
    - For `export-from-volume`: `volume-name` 
    - For `download`: `url`
    - For `upload`: `` (empty)
    - ~~For `restore`: `backup-url`~~ (this feature will be released in v1.6.0)
  - [x] Add a filter so user can filter the BackingImage with other properties (e.g. `Created From`)
  - [x] Bulk download BackingImages
  - [ ] ~~Allow user to create Volume in BackingImage page~~
    - I think we can reuse the same form in Volume page but with `BackingImage` assigned
  - [x] BackingImages can show different colors for backing image status [here](https://github.com/longhorn/longhorn/issues/7288#issuecomment-1846868809).
  - [x]  Remove `cleanup` operation, instead, move the cleanup function in detail page [here](https://github.com/longhorn/longhorn/issues/7288#issuecomment-1846868809)
  - [x] Filter out `un-ready` status backing image in volume create modal dropdown.

cc @innobead @m-ildefons 

## Describe the solution you'd like

.

## Describe alternatives you've considered

.

## Additional context

.

**Comment by innobead** [comment]
@ChanYiLin a few questions

>   * [ ]  Bulk download BackingImages
Is this feasible? What does the behavior look like?

>   * [ ]  Allow user to create Volume in BackingImage page

Why do we want to have this? Don't users be able to create a volume based on a selected backing image?

**Comment by ChanYiLin** [comment]
Hi @innobead , I just summarized these improvements requests from the original user report https://github.com/longhorn/longhorn/issues/7288#issue-2030526469

> Bulk downloads of multiple images are not supported in the UI, this can be tedious when dealing with many images/volumes.
> The backing images view should have an action to directly create a volume from a backing image

We can still discuss if we really need this.

1.  Bulk download BackingImages
I think one simple way is user can pick multiple BackingImage at once, and from UI side, it will then send the download requests to the Backend at once.

2.  Allow user to create Volume in BackingImage page
Yes this seems duplicated.

**Comment by a110605** [comment]
Current longhorn-ui doesn't support `restore` type of backing image.
I can add it later after implementing https://github.com/longhorn/longhorn/issues/7541.

**Comment by a110605** [comment]
As per discussion with @ChanYiLin , change request below two items
- BackingImages' status on different disks could have colors -> show different colors for backing image status
- Allow user to create Volume in BackingImage page (won't need)

**Comment by roger-ryao** [comment]
**Verified on master-head 20240528**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/cd4d7235de3547e74ef6aeb71c6ba2c97ac8a9ba
- longhorn-ui `master-head` https://github.com/longhorn/longhorn-ui/commit/30c1e4127bfe8702aae97d85323a9520723ad682


**The test steps**
https://github.com/longhorn/longhorn/issues/7293#issuecomment-2119595328


**Result Passed**

  - [x] Columns can be sorted in backing image list
  - [x] Add UUID / Created fromfilter option options to filter in backing image list
  - [x] Bulk download backing images
  - [x] Show different colors for backing image status
  - [x] Move cleanup operation into detail page
- [x] require/doc : https://github.com/longhorn/website/pull/913



Hi @ChanYiLin @a110605 
  1. Could this [IMPROVEMENT](https://github.com/longhorn/longhorn/issues/7293) be backported to `v1.6.x`?

  2. According to [Bulk download : only has ready disk status image can be downloaded](https://github.com/longhorn/longhorn-ui/pull/729#issue-2304931231), I think we might need to create another ticket for when a volume with a backing image is created but the backing image is not ready. 
  In this case, we should also display a message to the user, instead of waiting until the volume is attached and its status remains at Attaching, to check the backing image status. WDYT?

**Comment by a110605** [comment]
> **Verified on master-head 20240528**
> 
> * longhorn `master-head` [cd4d723](https://github.com/longhorn/longhorn/commit/cd4d7235de3547e74ef6aeb71c6ba2c97ac8a9ba)
> * longhorn-ui `master-head` [longhorn/longhorn-ui@30c1e41](https://github.com/longhorn/longhorn-ui/commit/30c1e4127bfe8702aae97d85323a9520723ad682)
> 
> **The test steps** [#7293 (comment)](https://github.com/longhorn/longhorn/issues/7293#issuecomment-2119595328)
> 
> **Result Passed**
> 
> * [x]  Columns can be sorted in backing image list
> * [x]  Add UUID / Created fromfilter option options to filter in backing image list
> * [x]  Bulk download backing images
> * [x]  Show different colors for backing image status
> * [x]  Move cleanup operation into detail page
> * [x]  require/doc : [Update backing image clean up action according to latest UI change website#913](https://github.com/longhorn/website/pull/913)
> 
> Hi @ChanYiLin @a110605
> 
> 1. Could this [IMPROVEMENT](https://github.com/longhorn/longhorn/issues/7293) be backported to `v1.6.x`?
> 2. According to [Bulk download : only has ready disk status image can be downloaded](https://github.com/longhorn/longhorn-ui/pull/729#issue-2304931231), I think we might need to create another ticket for when a volume with a backing image is created but the backing image is not ready.
>    In this case, we should also display a message to the user, instead of waiting until the volume is attached and its status remains at Attaching, to check the backing image status. WDYT?

1. I can do the backport to v1.6.x. 
2. After testing, the backing image in `failed-and-clean-up` can still create volume but when attaching to node, it keeps `attaching`.  IMO, we should filter out those backing images not in `Ready` status when creating volume.  cc @ChanYiLin 

<img width="647" alt="Screenshot 2024-05-28 at 4 44 08 PM" src="https://github.com/longhorn/longhorn/assets/5744158/f36d48da-2b07-4306-bc82-bffcac50897f">
<img width="1494" alt="Screenshot 2024-05-28 at 4 47 30 PM" src="https://github.com/longhorn/longhorn/assets/5744158/5f24e1c2-86db-41a9-a5f9-21d8e39ee40f">

**Comment by ChanYiLin** [comment]
Hi @roger-ryao @a110605 
Thanks for the feedback
- Yes it can be backported to v1.6.x
- Yes we can filter out the non-ready BackingImage when creating the Volume from BackingImage to improve the UI user friendly

**Comment by a110605** [comment]
> Hi @roger-ryao @a110605 Thanks for the feedback
> 
> * Yes it can be backported to v1.6.x
> * Yes we can filter out the non-ready BackingImage when creating the Volume from BackingImage to improve the UI user friendly

Hi @roger-ryao , @ChanYiLin , 
Let me add this improvment in this ticket and have a PR for it.

**Comment by a110605** [comment]
Hi @roger-ryao ,
For extra enhancement : Filter out un-ready status backing image in volume create modal dropdown. 

The verifiy steps are as below 
1.  Create some backing images not in READY status
-  upload a image to create a (in progress status) 
-  download from invalid url
2. go to volume page - > create new volume
3. the backing image dropdown can only select READY backing image.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240531**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/6fd4b16d6f694efa222141792aec967d5d4186c5
- longhorn-ui `master-head` https://github.com/longhorn/longhorn-ui/commit/f07eb8e983e1ba5790a3f6615e8bdb5f2cc65aff

**The test steps**
https://github.com/longhorn/longhorn/issues/7293#issuecomment-2119595328

**Result Passed**

  - [x] Columns can be sorted in backing image list
  - [x] Add UUID / Created from filter option options to filter in backing image list
  - [x] Bulk download backing images
  - [x] Show different colors for backing image status
  - [x] Move `cleanup` operation into detail page
  - [x] Filter out un-ready status backing image in volume create modal dropdown.
- [x] require/doc : https://github.com/longhorn/website/pull/913
