### ISSUE TITLE
[IMPROVEMENT] BackingImage should be compressed when downloading and use the name as filename instead of UUID

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#7295]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

From this issue #7288 
BackingImage should be compressed when downloading and use the name as filename instead of UUID

cc @innobead @m-ildefons

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (backing-image-manager `a8bf86`) with test [steps](https://github.com/longhorn/longhorn/issues/7295#issuecomment-1857526105)

1. Downloaded backingimage now is in gzip format, the name of the download file is backingimage name, not UUID anymore.
2. After unzip file, the result of command `sha512sum` was the same from UI as well as from command(`kubectl describe backimgimage`)
3. Verified in raw and  qcow2(download and export-from-volume)
4. Upload the unzipped backingimage to Longhorn, create volume with that backingimage, data intact.
