### ISSUE TITLE
[IMPROVEMENT] Refactor the usage of timer reset in SPDK JSON-RPC read method

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#7297]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

https://github.com/longhorn/go-spdk-helper/pull/53#discussion_r1419150860

## Additional context

cc @longhorn/dev-data-plane

**Comment by shuo-wu** [comment]
This improvement is already implemented and merged: https://github.com/longhorn/go-spdk-helper/pull/54
