### ISSUE TITLE
[BUG] Failed RWX mount due to connection timeout still happening

### ISSUE THREAD

**Issue by ilbarone87** [longhorn/longhorn#7301]
Hello everyone,

Seems that this issue is still happening: Failed RWX mount due to connection timeout, described here https://longhorn.io/kb/troubleshooting-failed-rwx-mount-due-to-connection-timeout/
But is not just limited to Flannel since my CNI is Cilium.

Error for csi-plugin:
```
  "message": [
    "time=\"2023-12-08T12:07:38Z\" level=error msg=\"NodeStageVolume: err: rpc error: code = Internal desc = mount failed: exit status 32\\nMounting command: /usr/local/sbin/nsmounter\\nMounting arguments: mount -t nfs -o vers=4.1,noresvport,timeo=600,retrans=5,soft 10.43.117.98:/pvc-2d1b998d-634b-4df5-8b4a-ef6d63a57571 /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/a95c4a02add5275a15b642f5b113ca80af2a4b36b305198dfc2a063d40191eb1/globalmount\\nOutput: mount.nfs: mount system call failed\\n\" func=csi.logGRPC file=\"server.go:138\""
  ],
  "namespace": [
    "longhorn-system"
  ],
  "namespace.keyword": [
    "longhorn-system"
  ],
  "pod": [
    "longhorn-csi-plugin-9h776"
  ],
```
and this:
```
"time=\"2023-12-08T11:58:32Z\" level=warning msg=\"Failed to mount volume pvc-2d1b998d-634b-4df5-8b4a-ef6d63a57571 with default mount options, retrying with soft mount\" func=\"csi.(*NodeServer).nodeStageSharedVolume\" file=\"node_server.go:249\" component=csi-node-server error=\"mount failed: exit status 32\\nMounting command: /usr/local/sbin/nsmounter\\nMounting arguments: mount -t nfs -o vers=4.1,noresvport,timeo=600,retrans=5,sof 10.43.117.98:/pvc-2d1b998d-634b-4df5-8b4a-ef6d63a57571 /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/a95c4a02add5275a15b642f5b113ca80af2a4b36b305198dfc2a063d40191eb1/globalmount\\nOutput: mount.nfs: an incorrect mount option was specified\\n\""
    ],
```

## Environment

 - Longhorn version: 1.5.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.26.10+rke2r2
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 2
 - Cilium description: Bundled RKE2 version 1.14.4
 - Node config
   - OS type and version: Ubuntu 22.04.3
   - Kernel version: 5.18.0
   - CPU per node: 8 vCPUs
   - Memory per node: 16gb
   - Disk type(e.g. SSD/NVMe/HDD): SSD Intel s4610
   - Network bandwidth between the nodes: 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox
 - Number of Longhorn volumes in the cluster: 23
 - Impacted Longhorn resources: 1 (the only RWX that i have)
   - Volume names: pvc-2d1b998d-634b-4df5-8b4a-ef6d63a57571

**Comment by derekbit** [comment]
Don't care about this warning message. It will use `soft` mode instead.
```
"time=\"2023-12-08T11:58:32Z\" level=warning msg=\"Failed to mount volume pvc-2d1b998d-634b-4df5-8b4a-ef6d63a57571 with default mount options, retrying with soft mount\" func=\"csi.(*NodeServer).nodeStageSharedVolume\" file=\"node_server.go:249\" component=csi-node-server error=\"mount failed: exit status 32\\nMounting command: /usr/local/sbin/nsmounter\\nMounting arguments: mount -t nfs -o vers=4.1,noresvport,timeo=600,retrans=5,sof 10.43.117.98:/pvc-2d1b998d-634b-4df5-8b4a-ef6d63a57571 /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/a95c4a02add5275a15b642f5b113ca80af2a4b36b305198dfc2a063d40191eb1/globalmount\\nOutput: mount.nfs: an incorrect mount option was specified\\n\""
    ],
```

**Comment by mantissahz** [comment]
@derekbit 
Do you mean that `vers=4.1,noresvport,timeo=600,retrans=5,sof`, the wrong `sof` option will be substituted by `soft`?

**Comment by ilbarone87** [comment]
Apparently this is the issue https://github.com/cilium/cilium/issues/21541

**Comment by derekbit** [comment]
Will add a knowledge base doc for the issue.

**Comment by ilbarone87** [comment]
Happens when kube-proxy-replacement is enabled, and that falls in my case for sure. Weird that only happened after a couple of months I deployed the app with RWX volume. Also an update to 1.5.3 seems have fixed the problem.

**Comment by derekbit** [comment]
> Also an update to 1.5.3 seems have fixed the problem.

This is weird. There is no change related to the NFS mount of RWX volume.
Need a further investigation.

**Comment by urbaman** [comment]
Hi,

I'm probably having this issue with Calico and Multus+Whereabouts after an upgrade to 1.5.3, I have a lot of RWX pods in thsis state:

```
Events:
  Type     Reason                  Age    From                     Message
  ----     ------                  ----   ----                     -------
  Normal   Scheduled               2m16s  default-scheduler        Successfully assigned cloudbeaver/cloudbeaver-57ff587648-85qhz to k8w1
  Normal   SuccessfulAttachVolume  2m15s  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-94daa932-8c41-489f-b450-4658e0fec7b2"
  Warning  FailedMount             14s    kubelet                  MountVolume.MountDevice failed for volume "pvc-94daa932-8c41-489f-b450-4658e0fec7b2" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

**Comment by urbaman** [comment]
In my case, it was probably due to the [multipath problem](https://longhorn.io/kb/troubleshooting-volume-with-multipath/), as I solved it following the linked solution, then setting the pod replocas in afflicted deployments to 0, wait for the volumes to detach, then resetting the pod replicas to precedent value.

Thank you.

**Comment by janosmiko** [comment]
The same issue started to occur for me too on multiple clusters (I'm not using Cilium on these).

Please let me know if I can help with anything to determine the issue

**Comment by matthijsvdr** [comment]
I just updated longhorn on a cluster and now getting similar errors. I went from 1.5.1 to 1.53 and now mounting is messed up. Is there any solution to this? The cluster have extra drives that are only used for longhorn data.

`
MountVolume.MountDevice failed for volume "pvc-3e542f44-43ec-45e3-9d7a-35b8fe4db38b" : rpc error: code = Internal desc = mount failed: exit status 32 Mounting command: mount Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-3e542f44-43ec-45e3-9d7a-35b8fe4db38b /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/0a4cfc8adf23c85c87f2a5b9c6914c1e781aeb4d0481e285e7b9884406cb1e8e/globalmount Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/0a4cfc8adf23c85c87f2a5b9c6914c1e781aeb4d0481e285e7b9884406cb1e8e/globalmount: /dev/longhorn/pvc-3e542f44-43ec-45e3-9d7a-35b8fe4db38b already mounted or mount point busy. 
`

**Comment by derekbit** [comment]
@matthijsvdr 
Have you checked the multipathd issue?

**Comment by matthijsvdr** [comment]
@derekbit I found the page (https://longhorn.io/kb/troubleshooting-volume-with-multipath/) after I posted here, but given he time of day I left it to try for today :D. I just added the blacklist and now the volumes seem to mount again normally. 

The cluster us running k3s with the default flannel.

**Comment by jrife** [comment]
> Apparently this is the issue [cilium/cilium#21541](https://github.com/cilium/cilium/issues/21541)

This issue is fixed in newer kernel versions . RWX mounts should work with `kube-proxy-replacement` as long as you're running a kernel that hasthe fix ([context](https://github.com/cilium/cilium/issues/21541#issuecomment-1690161651)).

> Kernel version: 5.18.0

The fix should exist in all [LTS kernel versions](https://www.kernel.org/category/releases.html).

**Comment by james-munson** [comment]
Closing as complete.
