### ISSUE TITLE
[FEATURE]  A custom resource for recurring job/group selecting

### ISSUE THREAD

**Issue by atropos112** [longhorn/longhorn#7321]
## Is your feature request related to a problem? Please describe (👍 if you like this request)
Currently to best of my knowledge the workflow for me setting up a backup policy is to either do it through UI or to create a label on an PVC or the Volume resource itself.

It is my intent to set up a backups in a declarative way as much as possible, I often managed to get this done by using labels. Problem with this approach is that surprisingly often the helm charts many people rely on (e.g. Harbor) do not offer the ability of adding label's to the corresponding PVCs. 

## Describe the solution you'd like

Make a custom resource with selectors that could be used  to narrow down to which volumes should match which recurring jobs . Such custom resource would be composed of 
- means to locate the recurring job (name uniquely determines that so that should be easy i think)
- means to select the volumes intended for this recurring job.

## Describe alternatives you've considered
- One option is each time to create issues for each helm chart where label option is not present, it proves troublesome given how prevalent this is. 
- I could fork those charts, but then you are stuck in the "rebasing" game.
- I could use the fact that storageclass can be assigned to match a group/recurring job via the recurringJobSelector. This is however problematic because I must know i want application X to fall in that recurring job from its inception unless i want to do often expensive copy-across to attach it to a correct storageClass.
- I could make the pvc yaml myself, then use existingClaim, that way I have full control - This is what i am currently doing. This works for my intended purpose but does feel like a workaround.

## Additional context

This would superseded the current labels approach and provide a very flexible way for users to decoratively select their groups used for recurring jobs being declarative in its nature but also not requiring them to edit the charts/yamls that they may not be able to easily change (without falling off the supported path). 

I think this year has been a great year for longhorn, having seen how much this application has developed and the strong developers behind this project, I am very much looking forward to what is coming next year.

**Comment by PhanLe1010** [comment]
I just did a full read. A good writeup indeed! Thanks @atropos112 !

That being said, I feel it is a bit heavy to introduce a new CRD (and the controller for the CRD) to overcome the limitation that Habor helm chart (or similar chart) doesn't support a particular setting for the PVC. If we use this pattern, in the future, assume there is a particular PVC setting that the Habor helm chart doesn't support, would we need to create a new CRD? 

I am more inclined to the approach that:
1. Create an issue in Harbor Helm chart to support customization for the PVC's labels
2. Deploy the pvc yaml yourself, then use existingClaim in the Harbor chart. I think this one is a perfectly valid use-case. Comparing to the CRD approach, even if we implement that approach, you still need to deploy the CR right? So deploying the PVC here doesn't cost more user's effort than the CRD approach

cc @c3y1huang any thoughts?

**Comment by atropos112** [comment]
I must admit I am having doubts as to what I think the best way to deal with this problem is.

I have been wondering about it further. I think having a selector like outlined above is benefitial in clarity sense also. 

Seeing a resource that has the recuring job and a selector which outlines what to backup is clearer than having to look up each pvc and filter on label. Granted you can see it clearly in the ui but from gitops perspective this is clearly more natural to comprehend.

**Comment by PhanLe1010** [comment]
@c3y1huang @shuo-wu  @ejweber Any thoughts about this topic?
