### ISSUE TITLE
[REFACTOR] Node Controller Unit Tests

### ISSUE THREAD

**Issue by m-ildefons** [longhorn/longhorn#7332]
## Is your improvement request related to a feature? Please describe

The current unit tests for the node controller are utilizing the testing framework improperly. There is only one "test", which repeatedly sets up data structures and mock clients for the K8s  API and then iterates over a list of test cases (i.e. inputs and outcomes) and executes the same checks for each case. This makes it hard to modify and add new test cases, as existing test cases have to be modified to pass additional checks as well.
In addition to that, this makes the output hard to understand when a test case fails. It also makes it very hard to tell what the test expects as output on each test case.

## Describe the solution you'd like

- Break up the test cases into individual test functions
- Reduce the amount of involved resources in teach test case to a minimum
- Extend the test suite to additionally ensure the node controller emits K8s events only in desired situations

## Describe alternatives you've considered

1) Keep the current architecture and add test data for PR#2356 to each test case as well as an additional test case for PR#2356

2) Break up the test into individual test functions and add a new test function for PR#2356

**Comment by innobead** [comment]
@m-ildefons remember to add the issue to the current milestone when you are working on it.

**Comment by m-ildefons** [comment]
:+1: Sorry, I though it had, but it turned out I had just added it to the sprint but not the milestone as well.

**Comment by m-ildefons** [comment]
The changes are merged.
