### ISSUE TITLE
[QUESTION] I have a question about the default storage path in Longhorn，Can not take effect

### ISSUE THREAD

**Issue by linux-golang** [longhorn/longhorn#7333]
I have a question about the default storage path in Longhorn. I deployed it using the kubectl method, and I modified the "/var/lib/longhorn" path throughout the configuration. However, the changes didn't take effect after deployment.

Partial configuration
    spec:
      nodeSelector:
        app: longhorn
      containers:
      - name: longhorn-manager
        image: longhornio/longhorn-manager:v1.5.3
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command:
        - longhorn-manager
        - -d
        - daemon
        - --engine-image
        - "longhornio/longhorn-engine:v1.5.3"
        - --instance-manager-image
        - "longhornio/longhorn-instance-manager:v1.5.3"
        - --share-manager-image
        - "longhornio/longhorn-share-manager:v1.5.3"
        - --backing-image-manager-image
        - "longhornio/backing-image-manager:v1.5.3"
        - --support-bundle-manager-image
        - "longhornio/support-bundle-kit:v0.0.27"
        - --manager-image
        - "longhornio/longhorn-manager:v1.5.3"
        - --service-account
        - longhorn-service-account
        ports:
        - containerPort: 9500
          name: manager
        - containerPort: 9501
          name: conversion-wh
        - containerPort: 9502
          name: admission-wh
        - containerPort: 9503
          name: recov-backend
        readinessProbe:
          httpGet:
            path: /v1/healthz
            port: 9501
            scheme: HTTPS
        volumeMounts:
        - name: dev
          mountPath: /host/dev/
        - name: proc
          mountPath: /host/proc/
        - name: longhorn
          mountPath: /data/longhorn/ 
          mountPropagation: Bidirectional
        - name: longhorn-grpc-tls
          mountPath: /tls-files/
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: dev
        hostPath:
          path: /dev/
      - name: proc
        hostPath:
          path: /proc/
      - name: longhorn
        hostPath:
          path: /data/longhorn/
      - name: longhorn-grpc-tls
        secret:
          secretName: longhorn-grpc-tls
          optional: true
      serviceAccountName: longhorn-service-account
  updateStrategy:
    rollingUpdate:
      maxUnavailable: "100%"
------------------------
Can not take effect
I also try this way
https://longhorn.io/docs/1.5.3/advanced-resources/default-disk-and-node-config/   **Can not take effect**
Can you help me，thank you.

**Comment by linux-golang** [comment]
I use the latest

**Comment by mantissahz** [comment]
You should not modify the mountPath or hostPath directly.
IMO you should modify the ConfigMap `longhorn-default-setting` instead.
Such as the example in this section https://longhorn.io/docs/1.5.3/advanced-resources/deploy/customizing-default-settings/#using-the-longhorn-deployment-yaml-file.

**Comment by linux-golang** [comment]
thank you
