### ISSUE TITLE
[CI] Add CI for repo longhorn-spdk-engine

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#7336]
## What's the CI task to develop? Please describe

Need to add CI for [repo longhorn-spdk-engine](https://github.com/longhorn/longhorn-spdk-engine) so that the unit tests can be applied to each PR automatically before merge.

## Additional context

Notice that the test node host should set up huge pages and probably install `nvme` before running the unit tests.

**Comment by yangchiu** [comment]
Enabled `longhorn-spdk-engine` on `drone-pr`, but test failed on `amd64` and build failed on `arm64`: https://drone-pr.longhorn.io/longhorn/longhorn-spdk-engine/4/1/3

@shuo-wu Could you help to check?

**Comment by shuo-wu** [comment]
This `arm64` build failure is already fixed by this PR: https://github.com/longhorn/longhorn-spdk-engine/pull/79

**Comment by yangchiu** [comment]
`longhorn-spdk-engine` on `drone-pr` has been enabled. Let me know if it is needed to be enabled on `drone-publish` as well.
