### ISSUE TITLE
[BUG] Cant extend longhorn volume 1.15.3  in k3s v1.27.7+k3s2

### ISSUE THREAD

**Issue by rh363** [longhorn/longhorn#7340]
## cant extend my longhorn volume

hi guys,
i have a small local cluster for local pourpose, there are two debian machines.
i have installed longhorn following official docs.
i've already installed icsi and nfs and running the requirement check script it didn't show me any problem.

persistent volumes works but when i try to extend a volume via pvc i can see on the UI the volume tries to expand without success.
if i do `kubectl describe pvc pvcname` i see following events:

> Normal   Provisioning           2m45s                  driver.longhorn.io_csi-provisioner-65cb5cc4ff-8jx6d_ed2159bc-0ecf-4d42-b6a3-d245ab6bcf43  External provisioner is provisioning volume for claim "default/exserver"
> 
>   Normal   ExternalProvisioning   2m45s (x2 over 2m45s)  persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
> 
>   Normal   ProvisioningSucceeded  2m43s                  driver.longhorn.io_csi-provisioner-65cb5cc4ff-8jx6d_ed2159bc-0ecf-4d42-b6a3-d245ab6bcf43  Successfully provisioned volume pvc-ec6d1386-9be3-4b1d-bc62-e3a9ec088ce8
> 
>   Warning  ExternalExpanding      2m10s                  volume_expand                                                                             waiting for an external controller to expand this PVC
> 
>   Warning  VolumeResizeFailed     40s                    external-resizer driver.longhorn.io                                                       resize volume "pvc-ec6d1386-9be3-4b1d-bc62-e3a9ec088ce8" by resizer "driver.longhorn.io" failed: rpc error: code = DeadlineExceeded desc = volume pvc-ec6d1386-9be3-4b1d-bc62-e3a9ec088ce8 expansion from existing capacity 1073741824 to requested capacity 2147483648 failed
> 
>   Normal   Resizing               39s (x2 over 2m10s)    external-resizer driver.longhorn.io                                                       External resizer is resizing volume pvc-ec6d1386-9be3-4b1d-bc62-e3a9ec088ce8

this is my storage class:

> allowVolumeExpansion: true
> apiVersion: storage.k8s.io/v1
> kind: StorageClass
> metadata:
>   annotations:
>     longhorn.io/last-applied-configmap: |
>       kind: StorageClass
>       apiVersion: storage.k8s.io/v1
>       metadata:
>         name: longhorn
>         annotations:
>           storageclass.kubernetes.io/is-default-class: "true"
>       provisioner: driver.longhorn.io
>       allowVolumeExpansion: true
>       reclaimPolicy: "Delete"
>       volumeBindingMode: Immediate
>       parameters:
>         numberOfReplicas: "1"
>         staleReplicaTimeout: "30"
>         fromBackup: ""
>         fsType: "xfs"
>         dataLocality: "disabled"
>     storageclass.kubernetes.io/is-default-class: "true"
>   creationTimestamp: "2023-12-15T09:32:19Z"
>   name: longhorn
>   resourceVersion: "122323"
>   uid: 176f9161-0b6c-4756-bef0-a8ff25fdb66a
> parameters:
>   dataLocality: disabled
>   fromBackup: ""
>   fsType: xfs
>   numberOfReplicas: "1"
>   staleReplicaTimeout: "30"
> provisioner: driver.longhorn.io
> reclaimPolicy: Delete
> volumeBindingMode: Immediate

i've already tried to delete the pod who mount my volume , extend it and recreate the pod but it give me the same issue, it cant extend the volume.
i can extend my volume only if is detached and no pod has ever been connected to it.
please i need your help :(

## To Reproduce

-1 install k3s
-2 install longhorn requirement
-3 install longhorn via kubectl
-4 modify configmap/longhorn-storageclass field `fsType: ext4` to `fsType: xfs`
-5 modify configmap/longhorn-storageclass field `numberOfReplicas: "3"` to `numberOfReplicas: "1"`
-6 apply the following pvc:

> apiVersion: v1
> kind: PersistentVolumeClaim
> metadata:
>   name: exserver
> spec:
>   volumeMode: "Filesystem"
>   accessModes:
>     - ReadWriteOnce
>   storageClassName: longhorn
>   resources:
>     requests:
>       storage: 1Gi

 -7 apply the following deploy:

> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: exserver
> spec:
>   selector:
>     matchLabels:
>       app: exserver
>   template:
>     metadata:
>       labels:
>         app: exserver
>     spec:
>       containers:
>       - name: nfs-server
>         image: k8s.gcr.io/volume-nfs:0.8
>         ports:
>         - name: nfs
>           containerPort: 2049
>         - name: mountd
>           containerPort: 20048
>         - name: rpcbind
>           containerPort: 111
>         securityContext:
>           privileged: true
>         volumeMounts:
>         - name: storage
>           mountPath: /exports
>       volumes:
>       - name: storage
>         persistentVolumeClaim:
>           claimName: exserver

-8 apply the following pvc:

> apiVersion: v1
> kind: PersistentVolumeClaim
> metadata:
>   name: exserver
> spec:
>   volumeMode: "Filesystem"
>   accessModes:
>     - ReadWriteOnce
>   storageClassName: longhorn
>   resources:
>     requests:
>       storage: 2Gi

## Expected behavior

I expect that updating the pvc will increase the volume of the block and filesystem.

## Environment

 - Longhorn version: 1.5.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version: debian 11
   - Kernel version: 5.10.197-1
   - CPU per node: 2
   - RAM per node: 4GB
   - Memory per node: 20 GB
   - Disk type(e.g. SSD/NVMe/HDD): HDD
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Virtual Box VM

**Comment by mantissahz** [comment]
Hi @rh363, 

Could you provide the support bundle?

Could you show the Longhorn volume and Longhorn engine status by commands?:

```bash
kubectl -n longhorn-system get volume pvc-ec6d1386-9be3-4b1d-bc62-e3a9ec088ce8 -oyaml
```
and
```bash
kubectl -n longhorn-system get engine pvc-ec6d1386-9be3-4b1d-bc62-e3a9ec088ce8-e-0 -oyaml
```
And is there any abnormal log in the `longhorn-manager`, i`nstance-manager`, and `csi-plugin` pods?

**Comment by rh363** [comment]
hi @mantissahz,
thank you very much for your answer.
Unfortunately, I can't get a support bundle i'm sorry.
this is my volume yaml obtained with:  `kubectl -n longhorn-system get volume pvc-ec6d1386-9be3-4b1d-bc62-e3a9ec088ce8 -oyaml`

> apiVersion: longhorn.io/v1beta2
> kind: Volume
> metadata:
>   creationTimestamp: "2023-12-15T11:45:58Z"
>   finalizers:
>   - longhorn.io
>   generation: 3
>   labels:
>     longhornvolume: pvc-4219b930-f322-44de-ac12-44a608ce8ea7
>     recurring-job-group.longhorn.io/default: enabled
>     setting.longhorn.io/remove-snapshots-during-filesystem-trim: ignored
>     setting.longhorn.io/replica-auto-balance: ignored
>     setting.longhorn.io/snapshot-data-integrity: ignored
>   name: pvc-4219b930-f322-44de-ac12-44a608ce8ea7
>   namespace: longhorn-system
>   resourceVersion: "133201"
>   uid: 7bbf4eb9-df1e-45c3-a02f-3bf07c68f4c8
> spec:
>   Standby: false
>   accessMode: rwo
>   backendStoreDriver: v1
>   backingImage: ""
>   backupCompressionMethod: lz4
>   dataLocality: disabled
>   dataSource: ""
>   disableFrontend: false
>   diskSelector: []
>   encrypted: false
>   engineImage: longhornio/longhorn-engine:v1.5.3
>   fromBackup: ""
>   frontend: blockdev
>   lastAttachedBy: ""
>   migratable: false
>   migrationNodeID: ""
>   nodeID: masterpc
>   nodeSelector: []
>   numberOfReplicas: 1
>   offlineReplicaRebuilding: disabled
>   replicaAutoBalance: ignored
>   replicaSoftAntiAffinity: ignored
>   replicaZoneSoftAntiAffinity: ignored
>   restoreVolumeRecurringJob: ignored
>   revisionCounterDisabled: false
>   size: "2147483648"
>   snapshotDataIntegrity: ignored
>   staleReplicaTimeout: 30
>   unmapMarkSnapChainRemoved: ignored
> status:
>   actualSize: 10850304
>   cloneStatus:
>     snapshot: ""
>     sourceVolume: ""
>     state: ""
>   conditions:
>   - lastProbeTime: ""
>     lastTransitionTime: "2023-12-15T11:45:58Z"
>     message: ""
>     reason: ""
>     status: "False"
>     type: WaitForBackingImage
>   - lastProbeTime: ""
>     lastTransitionTime: "2023-12-15T11:45:58Z"
>     message: ""
>     reason: ""
>     status: "False"
>     type: TooManySnapshots
>   - lastProbeTime: ""
>     lastTransitionTime: "2023-12-15T11:45:58Z"
>     message: ""
>     reason: ""
>     status: "True"
>     type: Scheduled
>   - lastProbeTime: ""
>     lastTransitionTime: "2023-12-15T11:45:58Z"
>     message: ""
>     reason: ""
>     status: "False"
>     type: Restore
>   currentImage: longhornio/longhorn-engine:v1.5.3
>   currentMigrationNodeID: ""
>   currentNodeID: masterpc
>   expansionRequired: true
>   frontendDisabled: false
>   isStandby: false
>   kubernetesStatus:
>     lastPVCRefAt: ""
>     lastPodRefAt: ""
>     namespace: default
>     pvName: pvc-4219b930-f322-44de-ac12-44a608ce8ea7
>     pvStatus: Bound
>     pvcName: exserver
>     workloadsStatus:
>     - podName: exserver-7ddcfccd6-w4ggt
>       podStatus: Running
>       workloadName: exserver-7ddcfccd6
>       workloadType: ReplicaSet
>   lastBackup: ""
>   lastBackupAt: ""
>   lastDegradedAt: ""
>   offlineReplicaRebuildingRequired: false
>   ownerID: masterpc
>   pendingNodeID: ""
>   remountRequestedAt: ""
>   restoreInitiated: false
>   restoreRequired: false
>   robustness: healthy
>   shareEndpoint: ""
>   shareState: ""
>   state: attached

this is my engine yaml:

> 
> apiVersion: longhorn.io/v1beta2
> kind: Engine
> metadata:
>   creationTimestamp: "2023-12-15T11:45:58Z"
>   finalizers:
>   - longhorn.io
>   generation: 3
>   labels:
>     longhornnode: masterpc
>     longhornvolume: pvc-4219b930-f322-44de-ac12-44a608ce8ea7
>   name: pvc-4219b930-f322-44de-ac12-44a608ce8ea7-e-0
>   namespace: longhorn-system
>   ownerReferences:
>   - apiVersion: longhorn.io/v1beta2
>     kind: Volume
>     name: pvc-4219b930-f322-44de-ac12-44a608ce8ea7
>     uid: 7bbf4eb9-df1e-45c3-a02f-3bf07c68f4c8
>   resourceVersion: "133212"
>   uid: e8012b8d-09bf-4469-b65a-9457fabd4b39
> spec:
>   active: true
>   backendStoreDriver: v1
>   backupVolume: ""
>   desireState: running
>   disableFrontend: false
>   engineImage: longhornio/longhorn-engine:v1.5.3
>   frontend: blockdev
>   logRequested: false
>   nodeID: masterpc
>   replicaAddressMap:
>     pvc-4219b930-f322-44de-ac12-44a608ce8ea7-r-7bc8e44d: 10.42.1.8:10000
>   requestedBackupRestore: ""
>   requestedDataSource: ""
>   revisionCounterDisabled: false
>   salvageRequested: false
>   unmapMarkSnapChainRemovedEnabled: false
>   upgradedReplicaAddressMap: {}
>   volumeName: pvc-4219b930-f322-44de-ac12-44a608ce8ea7
>   volumeSize: "2147483648"
> status:
>   backupStatus: null
>   cloneStatus:
>     tcp://10.42.1.8:10000:
>       error: ""
>       fromReplicaAddress: ""
>       isCloning: false
>       progress: 0
>       snapshotName: ""
>       state: ""
>   conditions:
>   - lastProbeTime: ""
>     lastTransitionTime: "2023-12-15T11:45:58Z"
>     message: ""
>     reason: ""
>     status: "True"
>     type: InstanceCreation
>   currentImage: longhornio/longhorn-engine:v1.5.3
>   currentReplicaAddressMap:
>     pvc-4219b930-f322-44de-ac12-44a608ce8ea7-r-7bc8e44d: 10.42.1.8:10000
>   currentSize: "1073741824"
>   currentState: running
>   endpoint: /dev/longhorn/pvc-4219b930-f322-44de-ac12-44a608ce8ea7
>   instanceManagerName: instance-manager-060e1842137edfd6540be2f47ab38b64
>   ip: 10.42.0.14
>   isExpanding: true
>   lastExpansionError: ""
>   lastExpansionFailedAt: ""
>   lastRestoredBackup: ""
>   logFetched: false
>   ownerID: masterpc
>   port: 10000
>   purgeStatus:
>     tcp://10.42.1.8:10000:
>       error: ""
>       isPurging: false
>       progress: 0
>       state: ""
>   rebuildStatus: {}
>   replicaModeMap:
>     pvc-4219b930-f322-44de-ac12-44a608ce8ea7-r-7bc8e44d: RW
>   restoreStatus:
>     tcp://10.42.1.8:10000:
>       backupURL: ""
>       currentRestoringBackup: ""
>       isRestoring: false
>       lastRestored: ""
>       state: ""
>   salvageExecuted: false
>   snapshots:
>     volume-head:
>       children: {}
>       created: "2023-12-15T11:46:24Z"
>       labels: {}
>       name: volume-head
>       parent: ""
>       removed: false
>       size: "10850304"
>       usercreated: false
>   snapshotsError: ""
>   started: true
>   storageIP: 10.42.0.14
>   unmapMarkSnapChainRemovedEnabled: false

in longhorn manager i find this relevant line:

> time="2023-12-15T11:50:01Z" level=info msg="CSI plugin call to expand volume pvc-4219b930-f322-44de-ac12-44a608ce8ea7 to size 2147483648" func="manager.(*VolumeManager).Expand" file="volume.go:493"

> time="2023-12-15T11:50:01Z" level=info msg="Expanding volume pvc-4219b930-f322-44de-ac12-44a608ce8ea7 from 1073741824 to 2147483648 requested" func="manager.(*VolumeManager).Expand" file="volume.go:513"

> 10.42.0.22 - - [15/Dec/2023:11:50:01 +0000] "POST /v1/volumes/pvc-4219b930-f322-44de-ac12-44a608ce8ea7?action=expand HTTP/1.1" 200 7045 "" "Go-http-client/1.1"

> time="2023-12-15T11:51:31Z" level=info msg="CSI plugin call to expand volume pvc-4219b930-f322-44de-ac12-44a608ce8ea7 to size 2147483648" func="manager.(*VolumeManager).Expand" file="volume.go:493"

> time="2023-12-15T11:51:31Z" level=info msg="Volume pvc-4219b930-f322-44de-ac12-44a608ce8ea7 expansion is not necessary since current size 2147483648 >= 2147483648" func="manager.(*VolumeManager).Expand" file="volume.go:497"

csi resizer pod logs:

> E1215 11:51:09.927103       1 controller.go:286] Error syncing PVC: resize volume "pvc-4219b930-f322-44de-ac12-44a608ce8ea7" by resizer "driver.longhorn.io" failed: rpc error: code = DeadlineExceeded desc = volume pvc-4219b930-f322-44de-ac12-44a608ce8ea7 expansion from existing capacity 1073741824 to requested capacity 2147483648 failed

> I1215 11:51:09.962823       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"exserver", UID:"4219b930-f322-44de-ac12-44a608ce8ea7", APIVersion:"v1", ResourceVersion:"133312", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-4219b930-f322-44de-ac12-44a608ce8ea7

> E1215 11:52:39.982950       1 controller.go:286] Error syncing PVC: resize volume "pvc-4219b930-f322-44de-ac12-44a608ce8ea7" by resizer "driver.longhorn.io" failed: rpc error: code = DeadlineExceeded desc = volume pvc-4219b930-f322-44de-ac12-44a608ce8ea7 expansion from existing capacity 2147483648 to requested capacity 2147483648 failed

i dont find anything else..
is k3s compatible with longhorn expansion feature??
sorry to trouble you...

**Comment by mantissahz** [comment]
The engine shows
>isExpanding: true
size: "10850304"

These will be the conditions that block the expansion process.

cc @shuo-wu

**Comment by rh363** [comment]
i'm sorry but i dont understand...
the pvc size is 1 GB next i expand it to 2 GB where is my problem?
i'm sorry i'm new to k3s and longhorn system...

**Comment by PhanLe1010** [comment]
Hi @rh363 , could you search the log of the pod `longhorn-manager` and `instance-manager` pod for the keyword `pvc-4219b930-f322-44de-ac12-44a608ce8ea7` and provide the result here?

**Comment by rh363** [comment]
@PhanLe1010 i'm sorry i dont know why but now it work, i dont open it for a couple days and know it work...
i cant reproduce this error i'm sorry i cant help developer to patch it...
thanks for your help.
