### ISSUE TITLE
[TASK] Ensure the Go version in Dockerfile.dapper matches go.mod for all Longhorn components

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#7341]
## What's the task? Please describe

The `go.mod` files for most (if not all) Longhorn components references Go `1.21` on the `master`, `v1.5.x`, and `v1.4.x` branches. However, in many cases, the `Dockerfile.dapper` (which actually determines the version of the Go compiler we will use) references an older version of Go.

## Describe the sub-tasks

- [x] Update `longhorn-manager` `master`.
- [x] Update `longhorn-manager` `v1.5.x`.
- [ ] Update `longhorn-manager` `v1.4.x`.
- [x] Update `longhorn-instance-manager` `master`.
- [x] Update `longhorn-instance-manager` `v1.5.x`.
- [ ] Update `longhorn-instance-manager` `v1.4.x`.
- [x] Update `backing-image-manager` `master`.
- [x] Update `backing-image-manager` `v1.5.x`.
- [ ] Update `backing-image-manager` `v1.4.x`.
- [x] Update `share-manager` `master`.
- [x] Update `share-manager` `v1.5.x`.
- [ ] Update `share-manager` `v1.4.x`.

I checked the following components, which require no change:

- `longhorn-engine` `master`
- `longhorn-engine` `v1.5.x`
- `longhorn-engine` `v1.4.x`

**Comment by ejweber** [comment]
I created containers for all components with bumped versions and am running end-to-end tests on all three branches. If the tests pass, we should be safe to merge all the PRs.

**Comment by ejweber** [comment]
`master` results locations:

- https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5392/testReport/
- https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5385/testReport/

`master` results failures:

- [tests.test_node.test_node_default_disk_labeled](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5385/testReport/tests/test_node/test_node_default_disk_labeled/) failed both times, but it also regularly fails without the patch.
- [tests.test_metric.test_volume_metrics[default]](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5392/testReport/tests/test_metric/test_volume_metrics_default_/) failed once.
- [tests.test_ha.test_auto_remount_with_subpath](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5385/testReport/tests/test_ha/test_auto_remount_with_subpath/) failed once.

**Comment by ejweber** [comment]
`v1.5.x` results links:

- https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5386/testReport/
- https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5393/testReport/

`v1.5.x` results failures:

- [tests.test_csi.test_csi_minimal_volume_size](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5386/testReport/tests/test_csi/test_csi_minimal_volume_size/) failed both times, but it also regularly fails without the patch.
- [tests.test_settings.test_setting_concurrent_volume_backup_restore_limit_should_not_effect_dr_volumes[s3]](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5386/testReport/tests/test_settings/test_setting_concurrent_volume_backup_restore_limit_should_not_effect_dr_volumes_s3_/) failed once.
- [tests.test_basic.test_filesystem_trim[ext4]](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5393/testReport/tests/test_basic/test_filesystem_trim_ext4_/) failed once.
- [tests.test_metric.test_volume_metrics[default]](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5393/testReport/tests/test_metric/test_volume_metrics_default_/) failed once.

**Comment by ejweber** [comment]
`v1.4.x` results link:

- https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5387/testReport/

`v1.4.x` results failures:

- All 16 `test_csi_snapshotter` tests failed, but this also happened when I ran a regression unpatched. I do not think these failures are related to the changes.
- [tests.test_kubernetes.test_kubernetes_status](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5387/testReport/tests/test_kubernetes/test_kubernetes_status/), [tests.test_kubernetes.test_backup_kubernetes_status[s3]](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5387/testReport/tests/test_kubernetes/test_backup_kubernetes_status_s3_/), and [tests.test_kubernetes.test_backup_kubernetes_status[nfs]](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5387/testReport/tests/test_kubernetes/test_backup_kubernetes_status_nfs_/) are also regularly failing without the patch (https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-tests-sles-amd64/407/testReport/).

**Comment by innobead** [comment]
All merged.
