### ISSUE TITLE
Nonscheduled replica can result in volume stuck in `attaching` state

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#735]
To reproduce:
1. In a cluster with 3 nodes, set replica count to 3.
2. Disable `Replica Soft Antiaffinity` in the settings.
3. Create a volume, attach it to e.g. node 1.
4. Shutdown one node, waiting for the volume to report `scheduling failure`.
5. Detach the volume. Attach it to another node.
6. The volume may be stuck in `attaching state` forever.

It's due to when we waiting for all the replicas to be up, we didn't consider the replicas which cannot be scheduled won't be up (https://github.com/longhorn/longhorn-manager/blob/1a390af33b8939f73b0288ae3e3174bcbac91846/controller/volume_controller.go#L808).

There is another way to reproduce this:
1. In a cluster with 3 nodes, set replica count to 3.
2. Disable `Replica Soft Antiaffinity` in the settings.
3. Create a volume, attach it.
4. Once the volume is up, set the volume replica count to 4. It will fail scheduling.
5. Use `kubectl edit lhv <volume_name>` to manually set volume `Status.State` to `attaching`.
6. The volume will not able to reconcile back to the `attached` state.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

**Comment by yasker** [comment]
@meldafrawi Which reproduce step you've used for validation?
