### ISSUE TITLE
[FEATURE] Allow to set mount options for storageclass via values.yaml in helm chart

### ISSUE THREAD

**Issue by pfaelzerchen** [longhorn/longhorn#7351]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

By default, longhorn mounts RWX volumes with nfs 4.1. I wanted to expose an RWX volume with samba-operator for the local windows hosts. But samba-operator wants to set Extended Filesystem Attributes which do not work with nfs 4.1. So I have to specify a mount option nfsvers=4.2.

As far as I understood the helm chart, it will not make use of mountoptions specified under persistence. Because I deploy everything gitops-style with argocd patching the storageclass after installation is not straightforward (at least to me, I'm relatively new to this).

## Describe the solution you'd like

Allow to specify mount options for the storageclass under `persistence.mountOptions` in the helm chart's values.yaml.

## Describe alternatives you've considered

I wasn't really able to find one.

## Additional context

It is a K3s bare metal installation to replace an older home server.

**Comment by PhanLe1010** [comment]
Just to be clear, you are referring to this StorageClass field https://longhorn.io/docs/1.5.3/references/storage-class-parameters/#nfs-options-field-parametersnfsoptions right? @pfaelzerchen

**Comment by james-munson** [comment]
There's a description of how to use it in the testing notes for https://github.com/longhorn/longhorn/issues/6655#issuecomment-1735071816

**Comment by pfaelzerchen** [comment]
Yes, that is right. I refer to that field. @PhanLe1010. I'll try the description from the testing notes, thanks @james-munson. 

As far I understand this, I will not able to change this field. If it needs to be changed (e.g. because a future longhorn version will need it), I have to create a new storage class, create new pvcs and copy everything over. Right?

**Comment by PhanLe1010** [comment]
Thanks @pfaelzerchen for the confirmation.

We will add the field into Helm. I agree that it makes sense to add it.

**Comment by innobead** [comment]
@yardenshoham helped with the implementation. 

@ChanYiLin Please help with this issue to go through our issue workflow. Thanks.
