### ISSUE TITLE
[FEATURE] Add linear dm device on the top of v2 volume

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7357]
## What's the task? Please describe

This is the prerequisite for the [live upgrade feature](https://github.com/longhorn/longhorn/issues/6001).

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `b9e656`)

Perform testing with test [steps](https://github.com/longhorn/longhorn/issues/7357#issuecomment-1859215100) several times, the deployment and statefulset all recovered well and data intact.
