### ISSUE TITLE
[QUESTION] When I try to create a PersistentVolumeClaim (PVC) to use Longhorn, I encountered an issue. I have two nodes in Longhorn and the replication factor is set to 1. However, I found that the Pod is unable to bind successfully with the PVC.

### ISSUE THREAD

**Issue by linux-golang** [longhorn/longhorn#7369]
Hi：
     When I try to create a PersistentVolumeClaim (PVC) to use Longhorn, I encountered an issue. I have two nodes in Longhorn and the replication factor is set to 1. However, I found that the Pod is unable to bind successfully with the PVC.
```
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-storageclass
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.5.3
data:
  storageclass.yaml: |
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    reclaimPolicy: "Retain"
    volumeBindingMode: Immediate
    parameters:
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
      fromBackup: ""
      fsType: "ext4"
      dataLocality: "disabled"
----
# kubectl  logs -f -n longhorn-system   longhorn-manager-x6xrh 

172.20.107.239 - - [18/Dec/2023:09:49:50 +0000] "GET /v1/volumes/pvc-2eb660ef-7878-4f8c-9ec3-bb4bbc06aacb HTTP/1.1" 200 6572 "" "Go-http-client/1.1"
time="2023-12-18T09:49:50Z" level=warning msg="HTTP handling error" func=api.HandleError.func1 file="router.go:21" error="unable to attach volume pvc-2eb660ef-7878-4f8c-9ec3-bb4bbc06aacb to 192.168.0.233: node.longhorn.io \"192.168.0.233\" not found"
172.20.107.239 - - [18/Dec/2023:09:49:50 +0000] "POST /v1/volumes/pvc-2eb660ef-7878-4f8c-9ec3-bb4bbc06aacb?action=attach HTTP/1.1" 404 314 "" "Go-http-client/1.1"


----

attachdetach-controller@
Message
AttachVolume.Attach failed for volume "pvc-2eb660ef-7878-4f8c-9ec3-bb4bbc06aacb" : rpc error: code = Internal desc = Bad response statusCode [404]. Status [404 Not Found]. Body: [message=unable to attach volume pvc-2eb660ef-7878-4f8c-9ec3-bb4bbc06aacb to 192.168.0.233: node.longhorn.io "192.168.0.233" not found, code=Not Found, detail=] from [http://longhorn-backend:9500/v1/volumes/pvc-2eb660ef-7878-4f8c-9ec3-bb4bbc06aacb?action=attach]

```

Please help me. 
<img width="1101" alt="image" src="https://github.com/longhorn/longhorn/assets/65080394/59f40bbc-3658-463c-8e72-09f0322b0e3e">

**Comment by linux-golang** [comment]
Does it have anything to do with me changing the path below?

**Comment by PhanLe1010** [comment]
`error="unable to attach volume pvc-2eb660ef-7878-4f8c-9ec3-bb4bbc06aacb to 192.168.0.233: node.longhorn.io \"192.168.0.233\" not found"`

Looks like you are trying to start the workload on a node which doesn't Longhorn component running. Can you provide:
`kubectl get nodes` and `kubectl get nodes.longhorn.io -n longhorn-system`?

**Comment by linux-golang** [comment]
<img width="744" alt="image" src="https://github.com/longhorn/longhorn/assets/65080394/ab3e6fba-802d-4e28-818d-390558962476">
Yes, it seems that only two nodes are running, and the node 233 is missing. However, how should I proceed with this? My understanding is that the storage should be on nodes 234 and 235, but can other nodes still be used? I don't quite understand.

**Comment by PhanLe1010** [comment]
> seems that only two nodes are running, and the node 233 is missing. However, how should I proceed with this? My understanding is that the storage should be on nodes 234 and 235, but can other nodes still be used? I don't quite understand.

Hey, there are 2 parts:
1. If you want the workloads that use Longhorn volume on node 233, you must deploy Longhorn components on that node
2. Then, if you want Longhorn to use the disk on node 234 and 235 to store its data, you can add this label `node.longhorn.io/create-default-disk=true` to node 233, 235 AND Install Longhorn with the setting [Create Default Disk on Labeled Nodes](https://longhorn.io/docs/1.2.2/references/settings/#create-default-disk-on-labeled-nodes) set to true.

This is the instruction that fit your use-case: https://longhorn.io/kb/tip-only-use-storage-on-a-set-of-nodes/#tell-longhorn-to-create-a-default-disk-on-a-specific-set-of-nodes

![Screenshot from 2023-12-19 15-06-35](https://github.com/longhorn/longhorn/assets/22139961/1e2a332f-12dc-4d92-8372-5ac92c76f19a)
ots/Screenshot%20from%202023-12-19%2015-06-35.png

**Comment by linux-golang** [comment]
Yes, other nodes are functioning correctly. I just wanted to store data on nodes 234 and 235. I tried the solution you provided. However, I have some doubts. I set the option node.longhorn.io/create-default-disk=true for the nodes and then deleted the previous Longhorn configuration. After redeploying, I noticed that my defined storage paths became ineffective, and the default paths were being used instead."
![image](https://github.com/longhorn/longhorn/assets/65080394/ca284811-8bef-437a-bda6-7907ef5e0e6c)

**Comment by PhanLe1010** [comment]
@linux-golang 

The appoarch  https://longhorn.io/kb/tip-only-use-storage-on-a-set-of-nodes/#tell-longhorn-to-create-a-default-disk-on-a-specific-set-of-nodes required to full uninstall Longhorn then re-install Longhorn. Did you full uninstall Longhorn (https://longhorn.io/docs/1.5.3/deploy/uninstall/)?

**Comment by linux-golang** [comment]
Thank you very much for your support.
