### ISSUE TITLE
Backup to minio

### ISSUE THREAD

**Issue by nalakawula** [longhorn/longhorn#737]
any step by step to create backup using minio?

Thanks

Edit: I install minio and add to backup setting but got error:
```
error listing backups: error listing backup volumes: Failed to execute: /var/lib/rancher/longhorn/engine-binaries/rancher-longhorn-engine-v0.5.0/longhorn [backup ls --volume-only http://minio-service-ext.default:20000], output Driver http is not supported! , stderr, time="2019-09-19T10:53:47Z" level=error msg="Driver http is not supported!" , error exit status 1
```

**Comment by yasker** [comment]
Hi, please check https://github.com/longhorn/longhorn/blob/master/docs/snapshot-backup.md#setup-a-local-testing-backupstore

**Comment by nalakawula** [comment]
Ah, I need a cup of coffe. That was writen in readme and I not see that.
Thank you very much.
