### ISSUE TITLE
[IMPROVEMENT] Reject the last replica deletion if its volume.spec.deletionTimestamp is not set

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7372]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

To prevent accidentally from deleting the last replica regardless of it is healthy or faulty, reject the last replica deletion if `spec.deletionTimestamp` of its volume is not set in the validating webhook.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 859d438) following [test steps](https://github.com/longhorn/longhorn/issues/7372#issuecomment-1866244315). Try to remove the last replica, error message shown:
```
failed to remove replica: no other healthy replica available, cannot delete replica test-1-r-b9d4c389 since it may still contain data for recovery
```
