### ISSUE TITLE
[TASK] Synchronize version of CSI components in longhorn/longhorn and longhorn/longhorn-manager

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#7377]
## What's the task? Please describe

The fix for https://github.com/longhorn/longhorn/pull/6920 introduced new versions of many CSI components to the longhorn/longhorn repo. However, their [defaults in the longhorn/longhorn-manager repo](https://github.com/longhorn/longhorn-manager/blob/7aa262549f443166d63becf5f8a2ecd351e88c73/csi/deployment.go#L22-L27) (which are generally overridden by the values in the longhorn/longhorn repo) remain unchanged. This was confusing while investigating https://github.com/longhorn/longhorn/issues/7116, though it probably won't cause any particular bad behavior.

## Describe the sub-tasks

- [x] Update the CSI component versions in the longhorn/longhorn-manager repo.

**Comment by roger-ryao** [comment]
**Verified on master-head 20231228**

- longhorn master-head https://github.com/longhorn/longhorn/commit/07bdb419a968633059c24db35ec66d7d68d73f4c
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/f41d5b8fef567311a55656dd7590a35375ff61e1


**Result Passed**

1. Install with `Kubectl` & `Helm`:  CSI components were successfully installed with the updated version.
1. No outstanding issues observed in the `master-head` pipeline.
