### ISSUE TITLE
[BUG] Metric totalVolumeSize and totalVolumeActualSize incorrect due to v2 volume counts

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#7380]
## Describe the bug (🐛 if you encounter this issue)

Longhorn calculates sizes by dividing them by the volume count for both v1 and v2 engines. This is incorrect as it is skipping the sizes for v2 engine volumes.

## To Reproduce

1. Create v1 and v2 volumes.
1. Observe the `totalVolumeSize` and `totalVolumeActualSize`.

## Expected behavior

Should be the average of all volumes.

## Support bundle for troubleshooting

`N/A`

## Environment

`N/A`

## Additional context

https://github.com/longhorn/longhorn-manager/pull/2346#issuecomment-1858649541

**Comment by innobead** [comment]
@c3y1huang add this to the milestone when you are working on it.

**Comment by c3y1huang** [comment]
The actual size of the v2 volume is still a work in progress, so we cannot remove the condition that skips the v2 volumes. Hence, we will need to have a separate count for v1 volumes.

https://github.com/longhorn/longhorn/issues/5947

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `4e602f`) with test [steps](https://github.com/longhorn/longhorn-tests/pull/1633/files?short_path=f7df167#diff-f7df167048246d7bf91dd757a60a80dbcd55dc0d8b236b70c12aaeef34b9a25e)


Have 1 v2 volumes and 3 v1 volumes, the totalVolumeSize and totalVolumeActualSize. did not count v2 volume.

influxdb output
```
time                longhorn_volume_average_actual_size_bytes longhorn_volume_average_size_bytes
----                ----------------------------------------- ----------------------------------
1703152604477318132 419932842                                 2147483648
1703156204562104718 420507648                                 2147483648
1703159804652316616 421049685                                 2147483648
```
Actual volume statsus (3 v1 volumes, 1 v2 volume(`vol2`))
```bash
Number of V1 volumes: 3
Total size: 6442450944
Average size: 2147483648
Total actualSize: 1263783936
Average actual size: 421261312
root@ip-172-31-37-229:/home/ubuntu# k get volume -A
NAMESPACE         NAME                                       STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE               AGE
longhorn-system   vol1                                       attached   healthy                  2147483648   ip-172-31-37-229   3h12m
longhorn-system   vol2                                       attached   healthy                  5368709120   ip-172-31-33-122   3h12m
longhorn-system   pvc-712edd74-798c-4665-bd9d-83c7ebb9899b   attached   healthy                  2147483648   ip-172-31-37-229   3h12m
longhorn-system   pvc-3af61320-e429-412a-b102-2ffcb2bbfe56   attached   healthy                  2147483648   ip-172-31-43-195   3h13m

root@ip-172-31-37-229:/home/ubuntu# k get volume -n longhorn-system -o yaml | grep actual
    actualSize: 1048580096
    actualSize: 0
    actualSize: 108552192
    actualSize: 106725376

```
