### ISSUE TITLE
[IMPROVEMENT] Upgrade CSI components to the latest patch release

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#7384]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Upgrade CSI components to the latest patch release.

## Describe the solution you'd like

- [x] Create component images from upstream.
- [x] Update YAML/Chart
- [x] Update document

## Describe alternatives you've considered

`None`

## Additional context
https://github.com/longhorn/longhorn/issues/6916

**Comment by c3y1huang** [comment]
| component                 | current | update |
| --------------------------|---------|--------|
| CSI attacher              | v4.4.0  | ⭕ [v4.4.2](https://github.com/kubernetes-csi/external-attacher/blob/release-4.4/CHANGELOG/CHANGELOG-4.4.md)     |
| CSI node driver registrar | v2.9.0  | ⭕ [v2.9.2](https://github.com/kubernetes-csi/node-driver-registrar/blob/release-2.9/CHANGELOG/CHANGELOG-2.9.md) |
| CSI provisioner           | v3.6.0  | ⭕ [v3.6.2](https://github.com/kubernetes-csi/external-provisioner/blob/v3.6.2/CHANGELOG/CHANGELOG-3.6.md)       |
| CSI resizer               | v1.9.0  | ⭕ [v1.9.2](https://github.com/kubernetes-csi/external-resizer/blob/release-1.9/CHANGELOG/CHANGELOG-1.9.md)      |
| CSI snapshotter           | v6.3.0  | ⭕ [v6.3.2](https://github.com/kubernetes-csi/external-snapshotter/blob/v6.3.2/CHANGELOG/CHANGELOG-6.3.md)       |
| Livenessprobe             | v2.11.0 | ❌ [v2.11.0](https://github.com/kubernetes-csi/livenessprobe/blob/release-2.11/CHANGELOG/CHANGELOG-2.11.md)      |

**Comment by c3y1huang** [comment]
@yangchiu I was trying to mirror the images via https://ci.longhorn.io/job/private/job/mirror-csi-images/12/, but it doesn't seem to be working for me. The console output shows that they are on the current versions. 

Could you help? Thank you.

**Comment by c3y1huang** [comment]
> @yangchiu I was trying to mirror the images via https://ci.longhorn.io/job/private/job/mirror-csi-images/12/, but it doesn't seem to be working for me. The console output shows that they are on the current versions.
> 
> Could you help? Thank you.

I am not sure if it is trying to mirror the new upstream images to the image versions in the current code base. So I've trigger another with the current CSI component versions. 

https://ci.longhorn.io/job/private/job/mirror-csi-images/13/

**Comment by c3y1huang** [comment]
> @yangchiu I was trying to mirror the images via https://ci.longhorn.io/job/private/job/mirror-csi-images/12/, but it doesn't seem to be working for me. Something failed, and the console output shows that they are on the current versions.
> 
> Could you help? Thank you.

Confirmed images are mirrored to longhornio.

**Comment by c3y1huang** [comment]
Testing WIP.

**Comment by roger-ryao** [comment]
I will verify this issue after https://github.com/longhorn/longhorn-manager/pull/2413 has been merged.

**Comment by roger-ryao** [comment]
**Verified on master-head 20231228**

- longhorn master-head https://github.com/longhorn/longhorn/commit/07bdb419a968633059c24db35ec66d7d68d73f4c
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/f41d5b8fef567311a55656dd7590a35375ff61e1


**Result Passed**

1. `require/doc` : https://github.com/longhorn/website/pull/820
1. Install with `Kubectl` & `Helm`:  CSI components were successfully installed with the updated version.
1. No outstanding issues observed in the `master-head` pipeline.
