### ISSUE TITLE
[BUG] Test case `test_node_default_disk_labeled` failed

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#7385]
## Describe the bug (🐛 if you encounter this issue)

The test case `test_node_default_disk_labeled` failed on [master-head](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/758/)
The node didn't create the default disk on node-2. We also could reproduce the issue manually.
If we set the `default disk path` to a random disk path ( e.g. `/var/lib/longhorn-gqwxrc` ) and then set the `create default disk labeled node` setting to `true`, the node-1 could not create the default disk. When I revert the `default disk path` to `/var/lib/longhorn/` and set the create default disk labeled node setting to true, the disk would be created and work normally.

```python
        7. Check node 2. There is still no disks
        """
        # Set up cases.
        cases = {
            "disk_exists": None,
            "labeled": None,
            "unlabeled": None
        }
        nodes = client.list_node().data
        assert len(nodes) >= 3
    
        node = nodes[0]
        cases["disk_exists"] = node.id
        core_api.patch_node(node.id, {
            "metadata": {
                "labels": {
                    CREATE_DEFAULT_DISK_LABEL: "true"
                }
            }
        })
    
        node = nodes[1]
        cases["labeled"] = node.id
        core_api.patch_node(node.id, {
            "metadata": {
                "labels": {
                    CREATE_DEFAULT_DISK_LABEL: "true"
                }
            }
        })
        cleanup_node_disks(client, node.id)
    
        node = nodes[2]
        cases["unlabeled"] = node.id
        cleanup_node_disks(client, node.id)
    
        # Set disk creation and path Settings.
        setting = client.by_id_setting(SETTING_DEFAULT_DATA_PATH)
        client.update(setting, value=random_disk_path)
        setting = client.by_id_setting(SETTING_CREATE_DEFAULT_DISK_LABELED_NODES)
        client.update(setting, value="true")
>       wait_for_disk_update(client, cases["labeled"], 1)

test_node.py:1518: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

client = <longhorn.Client object at 0x7f15dc74d580>, name = 'ip-10-0-2-197'
disk_num = 1

    def wait_for_disk_update(client, name, disk_num):
        for i in range(RETRY_COUNTS):
            node = client.by_id_node(name)
            if len(node.disks) == disk_num:
                allUpdated = True
                disks = node.disks
                for d in disks:
                    if disks[d]["diskUUID"] == "":
                        allUpdated = False
                        break
                if allUpdated:
                    break
            time.sleep(RETRY_INTERVAL)
>       assert len(node.disks) == disk_num
E       AssertionError
```

## To Reproduce

1. Add labels to node 1 and 2, don't add label to node 3.

```
kubectl label nodes node-1 node.longhorn.io/create-default-disk=true
kubectl label nodes node-2 node.longhorn.io/create-default-disk=true
```
2. Remove all the disks on node 2 and 3.
3. Set setting `default disk path` to a random disk path
```bash
kubectl -n longhorn-system patch -p '{"value": "/var/lib/longhorn-gqwxrc"}' --type=merge lhs default-data-path
```
4.  Set setting `create default disk labeled node` to true.

```bash
kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs create-default-disk-labeled-nodes
```

5. Check node 1. It should still use the previous default disk path.
6. Check node 2. A new disk should be created at the random disk path.

## Expected behavior

Have consistent tested result in all branches result

## Support bundle for troubleshooting
[longhorn-tests-sles-amd64-758-bundle.zip](https://github.com/longhorn/longhorn/files/13712589/longhorn-tests-sles-amd64-758-bundle.zip)

**Comment by innobead** [comment]
This is not a regression for the master only, so there is no need to backport to other branches. cc @derekbit

**Comment by roger-ryao** [comment]
**Verified on master-head 20231227**

- longhorn master-head https://github.com/longhorn/longhorn/commit/07bdb419a968633059c24db35ec66d7d68d73f4c
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/a42748a41d2d79f3be58e78d808859e6456576cf


**The test steps**
https://github.com/longhorn/longhorn/issues/7385#issue-2048282916

1. Followed up on regression test results on `master-head`
1. Tested without configuring `Default Data Path`


**Result Passed**

1. Did not observe test failure `test_node_default_disk_labeled` on [master-head](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/766/)
1. Manual tests passed
