### ISSUE TITLE
Rancher v2.2.8 + LongHorn 0.50 / Volume Size Keeps Growing

### ISSUE THREAD

**Issue by narayaar** [longhorn/longhorn#739]
Hello Team:  In my org, we are currently evaluating LongHorn as the storage backend for non-critical applications, and have accordingly configured LongHorn 0.5.0 to communicate with Rancher v.2.2.8.

The infrastructure comprises of 2 physical nodes (32 CPUs / 64G mem), with each node playing the roles of both Rancher Cattle and LongHorn Nodes.  LongHorn has been configured to use a directory sitting on a 800G XFS-based filesystem, with volumes having 2 replicas (no snapshots/backups configured).

The problem we are facing is that the volume utilization does not reflect that actual data being utilized by the product that uses it.  When there's a data increase, the volume's size increases accordingly, but when the data decreases, the volume's size does not reflect that decrease.

I am therefore facing a scenario where the filesystem when viewed from within the pod is 90% free, while the actual volume itself when viewed from the OS is around ~50% utilized.

Could you please let me know what is needed from my side, to help resolve this?

Thanks,
Arun

**Comment by narayaar** [comment]
Hello Team:  Understanding you may be busy solving bigger problems, I was wondering if I can receive an invite to your slack channel, so that I may collaborate with you guys there.

Looking forward to your assistance.

Thanks,
Arun

**Comment by yasker** [comment]
@narayaar We've just added some documents to explain the volume size, please check https://github.com/longhorn/longhorn/blob/v0.6.0/docs/volume.md#volume-size

In short, even though Longhorn is thin-provisioned, the size of volume will only grow up. The size won't shrink down by itself. Block device is mostly blind to the filesystem changes.

But if you have some snapshots created, those take space too. You can clean them up to free up more spaces.

Our Slack channel is available at [longhorn-storage](https://rancher-users.slack.com/messages/CC2UQM49Y), as in https://github.com/longhorn/longhorn#community and our UI footer.

**Comment by narayaar** [comment]
Hello @yasker:  Thank you for getting back.

As there's no workaround currently, please consider this issue closed.

Thanks,
Arun
