### ISSUE TITLE
[REFACTOR] Build a method to differentiate process type instead of port number

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#7393]
## Is your improvement request related to a feature? Please describe

We currently use port number to differentiate the process type, we should use another more reliable method for it
https://github.com/longhorn/longhorn-manager/blob/master/engineapi/instance_manager.go#L290

cc @innobead

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager a4ebed9). No issues were found in [daily regression](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/948/), and the instance manager custom resource correctly reflect the status of the replica and engine:
```
instanceEngines:
    test-1-e-0:
      spec:
        backendStoreDriver: ""
        dataEngine: v1
        name: test-1-e-0
      status:
        conditions: null
        endpoint: ""
        errorMsg: ""
        listen: ""
        portEnd: 10000
        portStart: 10000
        resourceVersion: 0
        state: running
        type: engine
  instanceReplicas:
    test-2-r-499b71c3:
      spec:
        backendStoreDriver: ""
        dataEngine: v1
        name: test-2-r-499b71c3
      status:
        conditions: null
        endpoint: ""
        errorMsg: ""
        listen: ""
        portEnd: 10010
        portStart: 10001
        resourceVersion: 0
        state: running
        type: replica
  ip: 10.42.3.9
  ownerID: ip-10-0-1-190
  proxyApiMinVersion: 1
  proxyApiVersion: 5
```
