### ISSUE TITLE
[REFACTOR] move mount point check function to common lib

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#7394]
## Is your improvement request related to a feature? Please describe

We now check mount point state in share-manager and instance-manager
We should move the check function to a common lib to remove the duplicated code.

cc @innobead

**Comment by roger-ryao** [comment]
**Verified on master-head 20240611**

- longhorn master-head https://github.com/longhorn/longhorn/commit/9b18cacc622b4c95621c899efd827fa721edd0b6
- go-common-libs main https://github.com/longhorn/go-common-libs/commit/f37bf784b1dfa80d1cf859cc1f9b78a3989cd5f9
- longhorn-instance-manager master-head https://github.com/longhorn/longhorn-instance-manager/commit/b88bfcfbeda854b0623cbc28df3468ea1fdcaadf
- longhorn-share-manager master-head https://github.com/longhorn/longhorn-share-manager/commit/ade93e81dbbff5c1db430dbb0a6ff4465a690bea

**The test steps**
https://github.com/longhorn/longhorn/issues/7394#issuecomment-1978107543

**Result Passed**

The `volume's engine` condition would change back to `FailedSystemReadOnly: false`, and the IO would work in the workload.

```bash
> watch "kubectl -n longhorn-system describe engine vol-0-e-0 | grep -A12 Conditions"
  Conditions:
    Last Probe Time:       
    Last Transition Time:  2024-06-11T03:33:18Z
    Message:               
    Reason:                
    Status:                True
    Type:                  InstanceCreation
    Last Probe Time:       
    Last Transition Time:  2024-06-11T03:41:45Z
    Message:               
    Reason:                
    Status:                False
    Type:                  FilesystemReadOnly
```
