### ISSUE TITLE
Cannot set up Node Selector During installing Longhorn with Helm 

### ISSUE THREAD

**Issue by zhonghuali** [longhorn/longhorn#7407]
## Describe the bug (🐛 if you encounter this issue)

The pod of longhorn-driver-deployer deployment cannot start up due to a error in pod when setup node selector: 
level=fatal msg="Error deploying driver: failed to start CSI driver: failed to deploy deployment csi-attacher: Deployment.apps \"csi-attacher\" is invalid: [spec.template.spec.nodeSelector: Invalid value: \"map[tier\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.template.spec.nodeSelector: Invalid value: \"web]\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]" func=app.DeployDriverCmd.func1 file="driver.go:141"

 
## To Reproduce
1. setup k3s cluster with new installation ,the k3s version is v1.26.11+k3s2
2. setup a private registry in this cluster for airgap install longhorn
3. install longhorn with helm by below command,it will setup a nodeselector:

helm install longhorn longhorn/longhorn --version 1.5.3  --kube-context onpremise-lab  --namespace longhorn-system --create-namespace --set privateRegistry.registryUrl="privateRegistry:5000" --set defaultSettings.defaultDataPath="/mnt/data/k3s/longhorn" --set defaultSettings.systemManagedComponentsNodeSelector.tier="web" --set longhornManager.nodeSelector.tier="web" --set longhornUI.nodeSelector.tier="web" --set longhornDriver.nodeSelector.tier="web" --set csi.kubeletRootDir="/var/lib/rancher/k3s/agent/kubelet"

4. helm install succesfully ,but the csi-attacher cannot deployed ,The pod of longhorn-driver-deployer got the above error.

## Expected behavior

longhorn-driver-deployer can deploy successfully with given nodeSelector

## Environment

 - Longhorn version: 1.5.3 or 1.5.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:v1.26.11+k3s2
   - Number of management node in the cluster:2
   - Number of worker node in the cluster:0
 - Node config
   - OS type and version: Ubuntu 22.04
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 1
 - Impacted Longhorn resources:
   - Volume names:

## Additional context

the log in The pod of longhorn-driver-deployer
W1220 05:21:06.111012       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2023-12-20T05:21:06Z" level=info msg="Deploying CSI driver" func=app.deployDriver file="driver.go:181"
time="2023-12-20T05:21:06Z" level=info msg="User specified root dir: /var/lib/rancher/k3s/agent/kubelet" func=app.deployCSIDriver file="driver.go:276"
time="2023-12-20T05:21:06Z" level=info msg="Upgrading Longhorn related components for CSI v1.1.0" func=app.upgradeLonghornRelatedComponents file="upgrader.go:21"
time="2023-12-20T05:21:06Z" level=info msg="Detected CSI Driver driver.longhorn.io CSI Git commit 88c792f7df38383634c2c8401f96d999385458c1 version v1.5.3 Kubernetes version v1.26.11+k3s2 has already been deployed" func=csi.deploy file="deployment_util.go:187"
time="2023-12-20T05:21:06Z" level=info msg="Creating deployment csi-attacher" func=csi.deploy file="deployment_util.go:196"
time="2023-12-20T05:21:06Z" level=fatal msg="Error deploying driver: failed to start CSI driver: failed to deploy deployment csi-attacher: Deployment.apps \"csi-attacher\" is invalid: [spec.template.spec.nodeSelector: Invalid value: \"map[tier\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.template.spec.nodeSelector: Invalid value: \"web]\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]" func=app.DeployDriverCmd.func1 file="driver.go:141"

**Comment by PhanLe1010** [comment]
Looks like the correct command should be:

`
helm install longhorn longhorn/longhorn --version 1.5.3 --kube-context onpremise-lab --namespace longhorn-system --create-namespace --set privateRegistry.registryUrl="privateRegistry:5000" --set defaultSettings.defaultDataPath="/mnt/data/k3s/longhorn" --set defaultSettings.systemManagedComponentsNodeSelector="tier:web" --set longhornManager.nodeSelector.tier="web" --set longhornUI.nodeSelector.tier="web" --set longhornDriver.nodeSelector.tier="web" --set csi.kubeletRootDir="/var/lib/rancher/k3s/agent/kubelet"
`

**Comment by zhonghuali** [comment]
It work fine. Great! Thanks you!

**Comment by omidraha** [comment]
@PhanLe1010 

I have same issue, 
I'm using `Pulumi` and successfully deploy `longhorn` with `helm`,
But when I want to install `longhorn` on the specific node with `tier=log` label, it's not works and it installed on all nodes and I got errors for `longhorn-driver-deployer`

Source code:

https://github.com/omidraha/pulumi_example/blob/main/longhorn/longhorn.py#L157

### Info
```
kubectl describe node ip-10-10-1-130 
Name:               ip-10-10-1-130
Roles:              control-plane,etcd,master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=k3s
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=ip-10-10-1-130
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=true
                    node-role.kubernetes.io/etcd=true
                    node-role.kubernetes.io/master=true
                    node.kubernetes.io/instance-type=k3s
                    tier=log
```

### Info
```
kubectl logs -n longhorn-system longhorn-driver-deployer-7d69dfcd5b-l2zgx 
Defaulted container "longhorn-driver-deployer" out of: longhorn-driver-deployer, wait-longhorn-manager (init)
W0108 21:08:48.457279       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2024-01-08T21:08:48Z" level=info msg="Deploying CSI driver"
time="2024-01-08T21:08:48Z" level=error msg="failed to get arg root-dir. Need to specify \"--kubelet-root-dir\" in your Longhorn deployment yaml.: failed to get cmdline of proc kubelet: failed to deploy proc cmdline detection pod discover-proc-kubelet-cmdline: Pod \"discover-proc-kubelet-cmdline\" is invalid: [spec.nodeSelector: Invalid value: \"map[tier\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.nodeSelector: Invalid value: \"log]\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]"
time="2024-01-08T21:08:48Z" level=fatal msg="Error deploying driver: failed to start CSI driver: failed to get arg root-dir. Need to specify \"--kubelet-root-dir\" in your Longhorn deployment yaml.: failed to get cmdline of proc kubelet: failed to deploy proc cmdline detection pod discover-proc-kubelet-cmdline: Pod \"discover-proc-kubelet-cmdline\" is invalid: [spec.nodeSelector: Invalid value: \"map[tier\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.nodeSelector: Invalid value: \"log]\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]"
```

### Info
```
kubectl get events --sort-by=.metadata.creationTimestamp -A -w

longhorn-system   0s          Normal    Created                          pod/longhorn-driver-deployer-7d69dfcd5b-l2zgx                    Created container longhorn-driver-deployer
longhorn-system   0s          Normal    Started                          pod/longhorn-driver-deployer-7d69dfcd5b-l2zgx                    Started container longhorn-driver-deployer
longhorn-system   0s          Warning   UnknownNodeConditionTrue         node/ip-10-10-1-130                                              Unknown condition true of kubernetes node ip-10-10-1-130: condition type is EtcdIsVoter, reason is MemberNotLearner, message is Node is a voting member of the etcd cluster
longhorn-system   0s          Warning   UnknownNodeConditionTrue         node/ip-10-10-1-130                                              Unknown condition true of kubernetes node ip-10-10-1-130: condition type is EtcdIsVoter, reason is MemberNotLearner, message is Node is a voting member of the etcd cluster
longhorn-system   0s          Warning   UnknownNodeConditionTrue         node/ip-10-10-1-130                                              Unknown condition true of kubernetes node ip-10-10-1-130: condition type is EtcdIsVoter, reason is MemberNotLearner, message is Node is a voting member of the etcd cluster
longhorn-system   0s          Warning   UnknownNodeConditionTrue         node/ip-10-10-1-130                                              Unknown condition true of kubernetes node ip-10-10-1-130: condition type is EtcdIsVoter, reason is MemberNotLearner, message is Node is a voting member of the etcd cluster
longhorn-system   0s          Warning   UnknownNodeConditionTrue         node/ip-10-10-1-130                                              Unknown condition true of kubernetes node ip-10-10-1-130: condition type is EtcdIsVoter, reason is MemberNotLearner, message is Node is a voting member of the etcd cluster
longhorn-system   0s          Warning   UnknownNodeConditionTrue         node/ip-10-10-1-130                                              Unknown condition true of kubernetes node ip-10-10-1-130: condition type is EtcdIsVoter, reason is MemberNotLearner, message is Node is a voting member of the etcd cluster
```

**Comment by PhanLe1010** [comment]
The events are known issue you pointed to above
```
kubectl get events --sort-by=.metadata.creationTimestamp -A -w

Voter, reason is MemberNotLearner, message is Node is a voting member of the etcd cluster
longhorn-system   0s          Warning   UnknownNodeConditionTrue         node/ip-10-10-1-130                                     Unknown condition true of kubernetes node ip-10-10-1-130: condition type is EtcdIsVoter, reason is MemberNotLearner, message is Node is a voting member of the etcd cluster
longhorn-system   0s          Warning   UnknownNodeConditionTrue         node/ip-10-10-1-130                                     Unknown condition true of kubernetes node ip-10-10-1-130: condition type is EtcdIsVoter, reason is MemberNotLearner, message is Node is a voting member of the etcd cluster
longhorn-system   0s          Warning   UnknownNodeConditionTrue         node/ip-10-10-1-130                                     Unknown condition true of kubernetes node ip-10-10-1-130: condition type is EtcdIsVoter, reason is MemberNotLearner, message is Node is a voting member of the etcd cluster
longhorn-system   0s          Warning   UnknownNodeConditionTrue         node/ip-10-10-1-130                                     Unknown condition true of kubernetes node ip-10-10-1-130: condition type is EtcdIsVoter, reason is MemberNotLearner, message is Node is a voting member of the etcd cluster
longhorn-system   0s          Warning   UnknownNodeConditionTrue         node/ip-10-10-1-130                                     Unknown condition true of kubernetes node ip-10-10-1-130: condition type is EtcdIsVoter, reason is MemberNotLearner, message is Node is a voting member of the etcd cluster
```



Btw, I would recommend deploying latest stable version Longhorn 1.5.3 here https://github.com/omidraha/pulumi_example/blob/88b810d7dc5965de5726d0682df6772a78128018/longhorn/longhorn.py#L161 as we have fix multiple issues

**Comment by omidraha** [comment]
I upgraded `longhorn` from `1.5.1` to `1.5.3`, and now panel don't show any nodes or volumes. similar to this issue: 
https://github.com/longhorn/longhorn/issues/2118
