### ISSUE TITLE
[BUG] Creating volume randomly failed: failed to find a node that is ready and has the default engine image

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7413]
## Describe the bug (🐛 if you encounter this issue)

Run `test_basic.py::test_volume_basic` test case in a rke2 (`v1.28.4+rke2r1`) cluster. It randomly failed at `create volume` step with `~50%` reproducibility. Also `Found unknown instance manager` is detected at this moment.

```
Found unknown instance manager: {'currentState': 'error', 'image': 'longhornio/longhorn-instance-manager:master-head', 'instanceEngines': None, 'instanceReplicas': None, 'instances': None, 'managerType': 'aio', 'name': 'instance-manager-8e570aa43a32a4b72fec748db26567f8', 'nodeID': 'ip-10-0-2-171'}

Found unknown instance manager: {'currentState': 'error', 'image': 'longhornio/longhorn-instance-manager:master-head', 'instanceEngines': None, 'instanceReplicas': None, 'instances': None, 'managerType': 'aio', 'name': 'instance-manager-9b55759fb98e1d58c9624905c606f6af', 'nodeID': 'ip-10-0-2-223'}

Found unknown instance manager: {'currentState': 'error', 'image': 'longhornio/longhorn-instance-manager:master-head', 'instanceEngines': None, 'instanceReplicas': None, 'instances': None, 'managerType': 'aio', 'name': 'instance-manager-8a56b1546fbadade69476011865be295', 'nodeID': 'ip-10-0-2-74'}
```

```
    def _error(self, text, status_code):
>       raise ApiError(self._unmarshall(text), status_code)
E       longhorn.ApiError: (ApiError(...), "500 : failed to get the parameters: failed to get target node ID: failed to find a node that is ready and has the default engine image longhornio/longhorn-engine:master-head deployed\n{'code': 500, 'detail': '', 'message': 'failed to get the parameters: failed to get target node ID: failed to find a node that is ready and has the default engine image longhornio/longhorn-engine:master-head deployed', 'status': 500}")
```

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5492/

## To Reproduce

Create a `v1.28.4+rke2r1` cluster and run `test_basic.py::test_volume_basic` test case repeatedly.

## Support bundle for troubleshooting

[longhorn-tests-regression-5492-bundle.zip](https://github.com/longhorn/longhorn/files/13749331/longhorn-tests-regression-5492-bundle.zip)

## Environment

 - Longhorn version: master-head (longhorn-manager c87c7eb999e3f6ded087428c60cb8dd84962a5ee)
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.28.4+rke2r1
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version: sles
   - Kernel version: 15-sp5
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

**Comment by yangchiu** [comment]
It may not be a rke2-specific issue, since I observed this in a k3s cluster: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5567/testReport/junit/tests/test_ha/test_ha_salvage_1_10_/

**Comment by PhanLe1010** [comment]
### Test plan
1. Run a test pipeline with the pytest option `test_basic.py::test_volume_basic`
1. Verify that there is no `Found unknown instance manager` in the console output 
1. Verify that the test pass
1. Return repeat this process 5 times

**Comment by yangchiu** [comment]
The PR https://github.com/longhorn/longhorn-tests/pull/1643 skipped the instance manager waiting process and causes another error in the test: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5798/testReport/junit/tests/test_basic/test_volume_basic/, because the test expects there are 3 instance managers but the modified code doesn't wait for 3 instance managers ready before starts the test.

Also the original `failed to find a node that is ready and has the default engine image` issue is still presented: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5802/testReport/junit/tests/test_basic/test_volume_basic/

Tried to inspect Longhorn components status by inserted logs before the test creates volume: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5804/console, and found the engine images were terminating at that moment:
```
b'NAME                                                READY   STATUS              RESTARTS        AGE
csi-attacher-55cc7d8454-dttn6                       1/1     Running             0               11s
csi-attacher-55cc7d8454-n8khc                       1/1     Running             0               13s
csi-attacher-55cc7d8454-ww6ns                       1/1     Running             0               15s
csi-attacher-5c4bfdcf59-h9kkp                       1/1     Terminating         0               44s
csi-provisioner-6d769d8988-lhcbc                    1/1     Running             0               13s
csi-provisioner-6d769d8988-rxdk8                    1/1     Running             0               15s
csi-provisioner-6d769d8988-wcqg5                    1/1     Running             0               11s
csi-resizer-8b85f679f-9twgv                         1/1     Running             0               13s
csi-resizer-8b85f679f-mbtf2                         1/1     Running             0               15s
csi-resizer-8b85f679f-n7652                         1/1     Running             0               10s
csi-snapshotter-69bfd755b9-8qbz7                    1/1     Running             0               12s
csi-snapshotter-69bfd755b9-bpvz7                    1/1     Running             0               13s
csi-snapshotter-69bfd755b9-mxqxh                    1/1     Running             0               15s
csi-snapshotter-959b69d4b-tk8jn                     1/1     Terminating         0               44s
engine-image-ei-b907910b-p44sx                      0/1     Terminating         0               98s
engine-image-ei-b907910b-qtd6t                      0/1     Terminating         0               98s
engine-image-ei-b907910b-rjwqz                      0/1     Terminating         0               98s
instance-manager-0753e24adec21bd7abfae15161fdebb5   1/1     Running             0               5s
instance-manager-675e68df566ddb48215f415f106e2694   1/1     Running             0               5s
instance-manager-fdd63b150a7819a28b0099f105aa0d5f   1/1     Running             0               2s
longhorn-csi-plugin-hb727                           3/3     Running             0               44s
longhorn-csi-plugin-jcv8j                           3/3     Running             0               44s
longhorn-csi-plugin-jvgds                           0/3     ContainerCreating   0               2s
longhorn-driver-deployer-665cfb8d4b-vggpl           1/1     Running             0               2m34s
longhorn-manager-2wvdl                              1/1     Running             1 (2m22s ago)   2m34s
longhorn-manager-9twd6                              1/1     Running             2 (115s ago)    2m34s
longhorn-manager-pvhmg                              1/1     Running             1 (2m25s ago)   2m34s
longhorn-ui-594c5488d4-l2gqp                        1/1     Running             0               2m34s
longhorn-ui-594c5488d4-qkpkz                        1/1     Running             0               2m34s
'
FAILED
```

Look like more investigation needed to know what happened.

**Comment by yangchiu** [comment]
In daily regression, found another test case `test_setting_backing_image_auto_cleanup` failed due to the same error:
https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/770/testReport/tests/test_settings/test_setting_backing_image_auto_cleanup/.

When test case `test_setting_backing_image_auto_cleanup` executed, Longhorn has already installed and run for hours, so there must be another issue except for waiting for engine image components ready.

**Comment by PhanLe1010** [comment]
> The PR https://github.com/longhorn/longhorn-tests/pull/1643 skipped the instance manager waiting process and causes another error in the test: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5798/testReport/junit/tests/test_basic/test_volume_basic/, because the test expects there are 3 instance managers but the modified code doesn't wait for 3 instance managers ready before starts the test.

Hi @yangchiu ! Any evidence/log that proves `the modified code doesn't wait for 3 instance managers ready before starts the test`?

From the code, the test is:
1. Waiting for the number of instance manager equals to 3 https://github.com/longhorn/longhorn-tests/blob/93e1a11721010a9c3926740e9613a7e2ffdba831/manager/integration/tests/common.py#L3620-L3622
2. Then waiting for all instance manager to become running https://github.com/longhorn/longhorn-tests/blob/93e1a11721010a9c3926740e9613a7e2ffdba831/manager/integration/tests/common.py#L3624-L3627

**Comment by innobead** [comment]
FYI. @mantissahz when working on issues, need to see if any changes are needed for tests already.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-tests 8460141) by running test case `test_basic.py::test_volume_basic` repeatedly.

Test results: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5920/ ~ https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5929/
