### ISSUE TITLE
[IMPROVEMENT] Improve handling of 16TiB+ volumes with ext4 as the underlying file system

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#7423]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

`ext4` supports a [maximum file size of 16TiB](https://en.wikipedia.org/wiki/Ext4#Features). So Longhorn volumes greater than or equal to 16TiB cannot be created on an `ext4` disk and Longhorn volumes less than 16TiB cannot be expanded to greater than or equal to 16TiB on an `ext4` disk.

The Longhorn UI and control plane allows the creation of 16TiB volumes. These volumes fail during initial attachment due to a SIGSEGV for the replica process. The failure is confusing to users, as it is not clear why the volume fails to attach.

The Longhorn UI and control plane allows the expansion of existing volumes to 16TiB. Expansion of these volumes fails due to a SIGSEGV for the replica process. The SIGSEGV does not allow a rollback, so the replica is left broken. In https://github.com/longhorn/longhorn/issues/7174, the user lost data as a result.

## Describe the solution you'd like

Maybe we don't need all of these, but combined they seem like a complete solution. Perhaps we can backport the documentation and the SIGSEV prevention while doing the nodes.longhorn.io CR work only in the latest version?

- [ ] Clearly document that the maximum size of a Longhorn volume when using an `ext4` underlying file system is 16383 GiB (or less than 16 TiB).
- [ ] Figure out where exactly the replica process SIGSEGV occurs and prevent it. For example, (though I'm sure there's a better way), execute `truncate -s <new_size>` before doing any other operations and refuse to proceed if that command fails. This prevents corruption due to a failed rollback.
- [ ] Learn and record the file system type of each disk in its corresponding `nodes.longhorn.io`. Do not schedule replicas for 16TiB+ volumes to `ext4` disks. Refuse to expand volumes to 16TiB+ if they use `ext4` disks before the expansion request reaches longhorn-engine in the first place. (The user can evict their `ext4` replicas if they want to do the expansion.)

## Additional context

- https://github.com/longhorn/longhorn/issues/7174
- https://github.com/longhorn/longhorn/issues/4768
- https://github.com/longhorn/longhorn/issues/2509

**Comment by ejweber** [comment]
Instance manager logs from a 16TiB volume that fails on its initial attach:

```
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] [test-way-too-big-r-030f144e] time="2023-12-22T17:10:14Z" level=info msg="Starting to create disk" func="replica.(*Replica).createDisk" file="replica.go:863" disk=000
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] [test-way-too-big-r-030f144e] time="2023-12-22T17:10:14Z" level=error msg="Caught FATAL error:  runtime error: invalid memory address or nil pointer dereference" func=main.ResponseLogAndError file="main.go:50"
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] goroutine 1 [running]:
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] runtime/debug.Stack()
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] runtime/debug.PrintStack()
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /usr/local/go/src/runtime/debug/stack.go:16 +0x13
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] main.ResponseLogAndError({0xee5020?, 0x18e4e50?})
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/main.go:51 +0x30a
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] main.cleanup()
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/main.go:59 +0x54
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] panic({0xee5020?, 0x18e4e50?})
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /usr/local/go/src/runtime/panic.go:914 +0x21f
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/pkg/replica.(*Replica).createNewHead.func1.1()
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/pkg/replica/replica.go:698 +0x4b
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/pkg/replica.(*Replica).createNewHead.func1()
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/pkg/replica/replica.go:706 +0x11f
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/pkg/replica.(*Replica).createNewHead(0xc00051c000, {0x0, 0x0}, {0x0, 0x0}, {0xc000040030, 0x14}, 0x0?)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/pkg/replica/replica.go:712 +0x633
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/pkg/replica.(*Replica).createDisk(0xc00051c000, {0x1024b2d, 0x3}, 0x0, {0xc000040030, 0x14}, 0x0, 0x100000000000)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/pkg/replica/replica.go:905 +0x496
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/pkg/replica.construct(0x4?, 0x100000000000, 0x200, {0x7ffc84b54518, 0x39}, {0x0, 0x0}, 0x0, 0x0, 0x0)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/pkg/replica/replica.go:224 +0x557
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/pkg/replica.New(...)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/pkg/replica/replica.go:145
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/pkg/replica.(*Server).Create(0xc000090960, 0xe?)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/pkg/replica/server.go:53 +0x2cd
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/app/cmd.startReplica(0xc000470c60)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/app/cmd/replica.go:110 +0x26d
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/app/cmd.ReplicaCmd.func1(0xc000470c60?)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/app/cmd/replica.go:78 +0x1d
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/urfave/cli.HandleAction({0xe80c20?, 0x108dc78?}, 0x7?)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/app.go:526 +0x75
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/urfave/cli.Command.Run({{0x1027b1d, 0x7}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0}, {0x1047630, ...}, ...}, ...)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/command.go:173 +0x63e
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/urfave/cli.(*App).Run(0xc0000e9500, {0xc00012e1a0, 0xd, 0xd})
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/app.go:277 +0xb07
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] main.longhornCli()
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/main.go:153 +0x27ba
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] main.main()
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/main.go:34 +0xb6
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] Caught FATAL error:  runtime error: invalid memory address or nil pointer dereference
```

**Comment by innobead** [comment]
>Clearly document that the maximum size of a Longhorn volume when using an ext4 underlying file system is 16383 GiB (or less than 16 TiB).

@mantissahz Please also update the doc as well. Probably the good place will be https://longhorn.io/docs/1.6.0/volumes-and-nodes/volume-size/ and https://longhorn.io/docs/1.6.0/volumes-and-nodes/expansion/.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `be0885`) with test [steps](https://github.com/longhorn/longhorn/issues/7423#issuecomment-1870881309)

- Have a 17Tib disk. create volume on the disk:
  - Extend volume to 16384 GiB rejected with message 
```
admission webhook "validator.longhorn.io" denied the request: file system filesystem does not support volume size 17592186044416
```
  - Extend volume to 16383 GiB succss
```bash
> k get pvc -o yaml | grep -m 1 storage:
        storage: 16383Gi
```
- Create a 16 TiB (16384 GiB) volume success but no replica is scheduled to any disk.

I will close this after the doc mentioned [here](https://github.com/longhorn/longhorn/issues/7423#issuecomment-1870912945) ready, thank you.

**Comment by mantissahz** [comment]
Hi @chriscchien,
Here is the PR for documents, https://github.com/longhorn/website/pull/831.

**Comment by chriscchien** [comment]
Close this ticket as test [passed](https://github.com/longhorn/longhorn/issues/7423#issuecomment-1871783508) and [doc](https://github.com/longhorn/website/pull/831) ready, thank you.
