### ISSUE TITLE
[IMPROVEMENT] Remove startup probe of CSI driver after liveness probe conn fix ready

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#7428]
Ideas to fix (in order of preference?):

1. Patch upstream `livenessprobe` to restore previous behavior. Revert to `v2.10.0` (or `v2.9.0`, since we already have a Longhorn version of it) in the meantime.
2. Add a startup probe to the `longhorn-csi-plugin` container with a `5m` window or configure its `livenessProbe.initialDelaySeconds` to `5m`. Kubernetes will not kill this container for the first five minutes it is alive. This will keep it alive long enough for `livenessprobe` to connect with it whenever it comes back, but maintain the existing probe behavior after startup.
3. ~Rework `longhorn-csi-plugin` startup so that it does not crash if it cannot connect to the `longhorn-backend` service. This may prevent the offset CrashLoopBackoffs from occurring in the first place.~ Kubernetes liveness probes will still fail, since the container is not ready. This only works as a potential addendum to 2.

_Originally posted by @ejweber in https://github.com/longhorn/longhorn/issues/7116#issuecomment-1861835259_

**Comment by ejweber** [comment]
- [ ] Backport to v1.5.x as well.

I am holding off for now because I am not sure we can get the master PRs merged and backported in time for v1.5.4 testing. If things go quickly, we can aim for v1.5.4. Otherwise, I will hold off on the backport until it is released.
