### ISSUE TITLE
[IMPROVEMENT] Add setting value limits in `SettingDefinition`

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7441]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Currently, setting values undergo validation across several functions, with hardcoded limits such as maximum and minimum values. For instance, the validation of the guaranteed instance manager CPU value can be found in the following locations:

https://github.com/longhorn/longhorn-manager/blob/mater/types/setting.go#L1493
https://github.com/longhorn/longhorn-manager/blob/master/types/types.go#L1021

We can add setting value limits in `SettingDefinition`. This consolidation facilitates easier management of limits associated with specific settings.

Ref: some examples https://book.kubebuilder.io/reference/markers/crd-validation

**Comment by roger-ryao** [comment]
**Verified on master-head 20240611**

- longhorn master-head https://github.com/longhorn/longhorn/commit/9b18cacc622b4c95621c899efd827fa721edd0b6
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/9a5840051413a57fce466d932decff69c1a8b221

**The test steps**
https://github.com/longhorn/longhorn/issues/7441#issuecomment-1963570822

**Result Passed**

Regression test passed 
https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/941/testReport/tests/test_basic/test_settings/
