### ISSUE TITLE
[TASK][UI] v2 volume does not support engine image upgrade

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7445]
## What's the task? Please describe

v2 volume does not support engine image upgrade.
The `up arrow symbol` and `upgrade engine` should not be shown.

![image](https://github.com/longhorn/longhorn/assets/12527233/8d9c5ddc-8124-4105-9270-16d9ff77774e)

**Comment by innobead** [comment]
@scures please work on this work.

**Comment by innobead** [comment]
@roger-ryao Please check with @scures to see what issues he encountered.

**Comment by roger-ryao** [comment]
Hi @scures 
     I have prepared an environment where I can create `v2` volumes and attach them to nodes.
     If you need, I can share the `kubeconfig` file with you for access.
     Just let me know in the slack channel.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240104**

- longhorn master-head https://github.com/longhorn/longhorn/commit/b2ad63f0247d99091384695ca74842f552f51396
- longhorn-ui master-head https://github.com/longhorn/longhorn-ui/commit/636639616df5aff196208da0d1751938092fc654

**Result Passed**

1. The up arrow symbol is not being displayed.
1. The `upgrade engine` icon for `v2` volumes is grayed out.
![Screenshot_20240104_142421](https://github.com/longhorn/longhorn/assets/104337648/ffd19a1c-3dcc-4e2d-9deb-30f7323af0fa)
