### ISSUE TITLE
[IMPROVEMENT] Reject volume.spec.image update for v2 volumes before introducing live upgrade

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7446]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Reject volume.spec.image update for v2 volumes before introducing [live upgrade](https://github.com/longhorn/longhorn/issues/6001)．

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `b9e656`)

Currently V2 volume engine upgrade will be rejected with below message
```
cannot upgrade engine for volume test using image longhornio/longhorn-engine:master-head: admission webhook "validator.longhorn.io" denied the request: changing engine image for volume test is not supported for backend store driver v2
```

**Comment by derekbit** [comment]
We need to revert the ticket, because the upgrade path will modify the v2 volume spec.image to instance-manager image.
Unfortunately, we are unable to distinguish an update is from the upgrade path or an user.

I will revert it in https://github.com/longhorn/longhorn-manager/pull/2386.

**Comment by derekbit** [comment]
cc @chriscchien @innobead

**Comment by innobead** [comment]
That's OK since this issue is just for preventing users from trying the unsupported live upgrade. Added invalid label.
