### ISSUE TITLE
[IMPROVEMENT] Do not show the `Down` on the etcd only node

### ISSUE THREAD

**Issue by Vicente-Cheng** [longhorn/longhorn#7450]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)
Harvester will support the witness node (which means the node only acts as an `etcd` role).
We found that the Longhorn UI will show the following figure. (node2 is `etcd` node)
<img width="1880" alt="292483036-3be081a4-e4ce-4a7d-b66f-41adfdb3cc70" src="https://github.com/longhorn/longhorn/assets/1615081/adb04f88-92e0-4530-862a-b6efe97b6c61">

Could we have more checking mechanisms for this etcd role node?

## Describe the solution you'd like
Could we show `Unscheduled` instead of `Down` if this node is the etcd-only node?

## Describe alternatives you've considered
None

## Additional context
Related to Harvester issue: https://github.com/harvester/harvester/issues/4840

**Comment by innobead** [comment]
The context is that an original Longhorn node has been promoted to a Harvester witness node, so the node resource has been left over and the status was updated with a not-ready condition. 

If the node has been promoted and the role is different, can just follow the steps in https://longhorn.io/docs/1.5.3/volumes-and-nodes/maintenance/#removing-a-node to remove the longhorn node resource.  Let's check the feasibility first. @Vicente-Cheng 

[/controller/node_controller.go#L414-L420](https://github.com/longhorn/longhorn-manager/blob/b9e65693ee7c735d98513115a4c6990a9afdab73/controller/node_controller.go#L414-L420)
```go
	if !nodeManagerFound {
		node.Status.Conditions = types.SetConditionAndRecord(node.Status.Conditions,
			longhorn.NodeConditionTypeReady, longhorn.ConditionStatusFalse,
			string(longhorn.NodeConditionReasonManagerPodMissing),
			fmt.Sprintf("manager pod missing: node %v has no manager pod running on it", node.Name),
			nc.eventRecorder, node, corev1.EventTypeWarning)
	}
```

**Comment by Vicente-Cheng** [comment]
> The context is that an original Longhorn node has been promoted to a Harvester witness node, so the node resource has been left over and the status was updated with a not-ready condition.
> 
> If the node has been promoted and the role is different, can just follow the steps in https://longhorn.io/docs/1.5.3/volumes-and-nodes/maintenance/#removing-a-node to remove the longhorn node resource, so we don't need to handle this at frontend only. Let's check the feasibility first. @Vicente-Cheng
> 
> [/controller/node_controller.go#L414-L420](https://github.com/longhorn/longhorn-manager/blob/b9e65693ee7c735d98513115a4c6990a9afdab73/controller/node_controller.go#L414-L420)
> 
> ```go
> 	if !nodeManagerFound {
> 		node.Status.Conditions = types.SetConditionAndRecord(node.Status.Conditions,
> 			longhorn.NodeConditionTypeReady, longhorn.ConditionStatusFalse,
> 			string(longhorn.NodeConditionReasonManagerPodMissing),
> 			fmt.Sprintf("manager pod missing: node %v has no manager pod running on it", node.Name),
> 			nc.eventRecorder, node, corev1.EventTypeWarning)
> 	}
> ```

Thanks @innobead for giving some suggestions!
We have discussed and it looks like we could handle it first.

Close it.
