### ISSUE TITLE
[BUG] The wrong template in default-setting.yaml of the Longhorn chart in v1.5 and v1.4

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#7459]
## Describe the bug (🐛 if you encounter this issue)

The wrong template in the `default-setting.yaml` file such as https://github.com/longhorn/longhorn/blob/v1.5.x/chart/templates/default-setting.yaml#L49-L57.
That will make the field `data` of the ConfigMap `longhorn-default-setting` get the wrong data format.
Or get the unexpected result by running the script `longhorn/scripts/generate-longhorn-yaml.sh`.

## Expected behavior

Generate the correct data from `longhorn/chart/templates/default-setting.yaml` file

**Comment by innobead** [comment]
@mantissahz self assign and assign to the milestone directly next time.

**Comment by roger-ryao** [comment]
**Verified on v1.5.4-rc1 20240206**

- longhorn v1.5.4-rc1 https://github.com/longhorn/longhorn/commit/f838d7e87539269dd9b3e2779facde9a6b5b6f88

**The test steps**
https://github.com/longhorn/longhorn/issues/7459#issuecomment-1907430780

**Result Passed**
1. Install successfully and default settings as expected.
