### ISSUE TITLE
[IMPROVEMENT] Helm chart should allow for single instance of each deployment (for single-node cluster)

### ISSUE THREAD

**Issue by samip5** [longhorn/longhorn#7465]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

I'm frustrated when I'm running a single-node cluster and I cannot tell to only provision one of each component.

## Describe the solution you'd like

The chart should see that I'm running a single node cluster, and thus should only deploy single instances of csi things, and ui.

## Describe alternatives you've considered

N/A

**Comment by innobead** [comment]
Do u mean deploying an adaptive  replica of each component as per the number of nodes in the cluster?

You should be able to set the replica number of Longhorn components during the chart install. Which components you couldn't change the replica number? CSI sidecars?

**Comment by samip5** [comment]
Yes to adaptive as per nodes in the cluster.

Chart install doesn't allow me to specify replicas for eg csi-provisoner,csi-attcher, csi-resizer, csi-snapshotter.

**Comment by PhanLe1010** [comment]
Hi @samip5 The Longhorn chart does allow you to set the replica count for these components here https://github.com/longhorn/longhorn/blob/07bdb419a968633059c24db35ec66d7d68d73f4c/chart/values.yaml#L166-L176C29

**Comment by samip5** [comment]
> Hi @samip5 The Longhorn chart does allow you to set the replica count for these components here https://github.com/longhorn/longhorn/blob/07bdb419a968633059c24db35ec66d7d68d73f4c/chart/values.yaml#L166-L176C29

Somehow missed those when I was looking for them.. Closing. :)

**Comment by talkraghu** [comment]
It would be good if someone can share the configs that I can set at kubectl longhorn.yaml too? Basically I want to use k8s manifest file to deploy longhorn at single node k8s
