### ISSUE TITLE
[FEATURE] Turn-off the automatically rebuilding

### ISSUE THREAD

**Issue by ziippy** [longhorn/longhorn#7472]
I'm already configured longhorn cluster in 10 more servers.

Sometimes, we needs to turn-off the longhorn servers for Infra management.

When I turn off one server then -> The longhorn try to automatically rebuilding for the volume.

But,
This is planed turn off then I want to longhorn does not do the automatically rebuilding.

But, I cannot find how to turn-off autimatically rebuilding.

If you already provide that feature then Please let me know how to do that.
or Not, Pleaes add feature.

**Comment by innobead** [comment]
Did you try https://longhorn.io/docs/1.5.3/references/settings/#concurrent-replica-rebuild-per-node-limit? You can disable rebuilding by setting it to 0 for a specific purpose.

**Comment by PhanLe1010** [comment]
Hi @ziippy Btw, how many Longhorn server nodes are you planning to turn off at a time? I am worry that if your disable rebuild and turn off multiple servers at the same time then your Longhorn volume might be corrupted. Also, we you draining the server before turning it off?

**Comment by ziippy** [comment]
I operate a total of 32 servers, each equipped with disks integrated through Longhorn. 
Occasionally, there is a need to simultaneously power off all 32 servers. 

Recently, after powering off and restarting all servers, I encountered a situation where one Longhorn volume repeatedly failed, proving challenging to recover.

I am seeking advice on ensuring a safe shutdown to prevent such volume errors.
