### ISSUE TITLE
[IMPROVEMENT] Handle unused BackingImage in the disk

### ISSUE THREAD

**Issue by FrankYang0529** [longhorn/longhorn#7477]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

We download backing image to the disk when we create a volume from it. However, we don't delete it from the disk when we remove the volume. We should find a way to handle it.

## Describe the solution you'd like

Add a process to check whether backing image is used by any volume. If not, remove it from the disk.

## Additional context

https://github.com/longhorn/longhorn-engine/pull/933#discussion_r1437358333

**Comment by innobead** [comment]
@ChanYiLin do we have a clean-up mechanism in backing the image now if it's not being used? such as reducing to only one replica after a retention period.

**Comment by ChanYiLin** [comment]
No, we don't have such retention setting.
However, user can delete the BackingImage from the specific disk on UI

**Comment by ChanYiLin** [comment]
Hi @FrankYang0529 @innobead 

We do have BackingImage retention when no replica is using the BackingImage, default is 60min
https://longhorn.io/docs/1.5.3/advanced-resources/backing-image/#clean-up-backing-images
https://github.com/longhorn/longhorn-manager/blob/master/controller/node_controller.go#L1152

**Comment by innobead** [comment]
ref: `SettingNameBackingImageCleanupWaitInterval`
