### ISSUE TITLE
[DOC] Add missing descriptions for Helm 

### ISSUE THREAD

**Issue by jillian-maroket** [longhorn/longhorn#7485]
## What's the document you plan to update? Why? Please describe

File: `docs/1.6.0/references/helm-values.md`
Issue: Missing descriptions for the following:

            | helmPreUpgradeCheckerJob.enabled | `true` |  |
            | metrics.serviceMonitor.enabled | `false` |  |

## Additional context

I'm applying a new wording convention to all descriptions in this file. Please provide draft descriptions here so I can complete my review and create the PR.

**Comment by jillian-maroket** [comment]
@mantissahz GitHub isn't allowing me to select an assignee and a version. @innobead said you can help with this.

**Comment by mantissahz** [comment]
@jillian-maroket
No problem.
