### ISSUE TITLE
[IMPROVEMENT] Support backup list if there is only v2-data-engine enabled

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7486]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Support backup list if there is only v2-data-engine

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `86b573`) with test [steps](https://github.com/longhorn/longhorn/issues/7486#issuecomment-1871766954)

Backup UI page display backup lists correctly when there only v2 data engine enabled.
