### ISSUE TITLE
[BUG] v2 volume always displays engine upgrade available on UI

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7489]
## Describe the bug (🐛 if you encounter this issue)

Install Longhorn master-head (longhorn-manager be08850), and create a v2 volume,  always displays engine upgrade available on UI:

![vol-1](https://github.com/longhorn/longhorn/assets/5709208/febed637-3b38-496f-8864-a58fc019e80e)

But it's actually unable to be upgraded:

![vol-2](https://github.com/longhorn/longhorn/assets/5709208/29c614e5-e686-4cf1-9800-7e474d8c7a0e)

## To Reproduce

create a v2 volume on Longhorn master-head

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

**Comment by derekbit** [comment]
The task is https://github.com/longhorn/longhorn/issues/7445
cc @scures

**Comment by innobead** [comment]
Duplicated.
