### ISSUE TITLE
How Can I See Replica And Volume Status From Host CLI?

### ISSUE THREAD

**Issue by C0NO** [longhorn/longhorn#749]
We can see status of replicas,pvc,backups,snapshots etc. from ui.But how can i check this status from master's host cli ?For example i want to make an alarm sistem when one of the replicas failed with a bash script.

**Comment by yasker** [comment]
Hi @C0NO 

Currently, you can access the manager API point using manager API. We haven't documented that yet but you can find examples in longhorn-tests repo, e.g. [test_basic.py](https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_basic.py#L169).

The official CLI would be available once we implemented #613 .
