### ISSUE TITLE
[IMPROVEMENT] Saving Settings page changes 

### ISSUE THREAD

**Issue by scures** [longhorn/longhorn#7497]
## Describe the solution you'd like
When making changes to the Settings page, the `Save` (I had the impression that the changes are automatically saved) button is at the very bottom of the page, you won't see it unless you scroll all the way, moving away from the page will discard all changes and there's no indication that your changes were discarded.

## Describe alternatives you've considered
- For pages with this much content maybe it would be useful that the Save button is always visible
- A dialog should inform you about losing your changes if you change some configuration and then move away, as in the example below.

![image](https://github.com/longhorn/longhorn/assets/88777903/c0f3736d-b913-4f42-811c-b7938dae4e67)

**Comment by roger-ryao** [comment]
**Verified on master-head 20240509**

- longhorn master-head https://github.com/longhorn/longhorn/commit/8026d1a700e66f9254fad75ee1e39390a0172208
- longhorn-ui master-head https://github.com/longhorn/longhorn-ui/commit/638c9186dee206698b86446029d0b17d8f82354b

**Result**

Hi @a110605 
    After configuring the `Storage Network`, `Backup Target`, and `Backup Target Credential Secret` without saving the settings, the alert did not pop up. Is this the expected behavior?
    
    
![Recording 2024-05-09 at 16 30 09](https://github.com/longhorn/longhorn/assets/104337648/db3f3118-f603-4f8a-aa0e-121104d5d279)

**Comment by a110605** [comment]
> Storage Network

No, sorry let me fix them to test again.

**Comment by derekbit** [comment]
@roger-ryao @a110605 
Is the issue also hit in v1.6.x and v1.5.x?

**Comment by a110605** [comment]
@derekbit , v1.6x and v1.5x branch doesn't have this alert modal UI enhancement. 
It only added in master branch for now.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240520**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/5a3c410218e4152c6302ed12cde1cfa6ed1ec446
- longhorn-ui `master-head` https://github.com/longhorn/longhorn-ui/commit/21a0d48f3fa381be4ac1754cb0a4008e204913db

**Result Passed**

**Comment by roger-ryao** [comment]
Hi @a110605 
This improvement is good for users. Do you plan to backport it to v1.5.x and v1.6.x? Are there any concerns about backporting it?

CC @derekbit

**Comment by a110605** [comment]
Hi @roger-ryao , I think it's okay to backport to v1.6.x and v1.5.x.

But this improvement separated in 3 PRs. I may need to cherry-pick the commits to v1.5.x and v1.6.x and test locally to ensure every changes are expected. (don't want to use [mergify](https://github.com/apps/mergify) to have mulitple backport PRs)

@derekbit , WDYT?

**Comment by derekbit** [comment]
> d in 3 PRs. I may need to cherry-pick the commits to v1.5.x and v1.6.x and test locally to ensure every changes are expected

Sure. Let's backport to v1.6.2 and v1.5.2.

**Comment by derekbit** [comment]
@a110605 Can you help backport it?
@roger-ryao Please verify the PRs after they are merged.
