### ISSUE TITLE
[BUG] rwx volume mount failed 

### ISSUE THREAD

**Issue by ming12713** [longhorn/longhorn#7503]
## pod mount volume failed 
In our case, we have many pods are mounted at the same time, get errors as follow 
![img_v3_026k_7bdb0c71-f390-4ff4-b01a-878ebb1f105g](https://github.com/longhorn/longhorn/assets/5196113/e0018a1e-46ac-46fd-bca6-83825053b593)

rwx volume nfs server provisioner error 

![屏幕快照 2023-12-30 16 03 39](https://github.com/longhorn/longhorn/assets/5196113/ba39e35e-7021-4bbe-93eb-b3db5046d0fe)

**Comment by derekbit** [comment]
What's your Longhorn version?

**Comment by ming12713** [comment]
> What's your Longhorn version?

1.5.1

**Comment by james-munson** [comment]
Would it be possible to get a support bundle showing the failure?

**Comment by ming12713** [comment]
> Would it be possible to get a support bundle showing the failure?

restart cni plugin and fixed
