### ISSUE TITLE
[BUG] Minio crash randomly

### ISSUE THREAD

**Issue by aljabertareq** [longhorn/longhorn#7504]
Minio crash randomly 

December 30th 2023, 09:32:47.981	Error: open /storage/.minio.sys/tmp: input/output error (*fs.PathError)

	December 30th 2023, 09:32:47.981	       1: cmd/signals.go:82:cmd.handleSignals()

	December 30th 2023, 09:32:47.981	
	December 30th 2023, 09:32:47.981	       2: cmd/signals.go:65:cmd.handleSignals.func2()

December 30th 2023, 09:32:47.461	Error: stat /storage/avsftp: input/output error (*fs.PathError)

	December 30th 2023, 09:32:47.461	       5: cmd/api-errors.go:2112:cmd.toAPIErrorCode()

	December 30th 2023, 09:32:47.461	       4: cmd/api-errors.go:2137:cmd.toAPIError()

	December 30th 2023, 09:32:47.461	       2: cmd/object-handlers.go:823:cmd.objectAPIHandlers.HeadObjectHandler()

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

**Comment by 4mohamedalaa** [comment]
This Minio is deployed on an on-prem Kubernetes cluster as deployment with a single replica with image : minio/minio:RELEASE.2022-04-09T15-09-52Z

**Comment by 4mohamedalaa** [comment]
Kindly find the support bundle in the attached link as its size is treated than the allowed limit :https://drive.google.com/file/d/18vViNHGeRKD_BA_jrVCp7xrDl39cmfzY/view

**Comment by 4mohamedalaa** [comment]
- Longhorn version: longhornio/longhorn-engine:v1.4.2
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:k8s  v1.23.5
- Number of management node in the cluster: 1
- Number of worker node in the cluster: 2
 Node config
- OS type and version:Ubuntu 20.04.6 LTS
- Kernel version: 5.4.0-166-generic
- CPU per node:96 and 128 for 2 nodes
- Memory per node: 33 and 40 for 2 nodes
- Disk type(e.g. SSD/NVMe/HDD): hdd and ssd
- Network bandwidth between the nodes:
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):baremetal
- Number of Longhorn volumes in the cluster: 17
- Impacted Longhorn resources:
- Volume names:

**Comment by c3y1huang** [comment]
This doesn't look related to Longhorn. Suggest raising the issue over on the MinIO side.
