### ISSUE TITLE
[IMPROVEMENT][UI] Validate volume creation according to the enabled data engines

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7505]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The current validation in UI codes only handles v2 volumes. Longhorn starts supporting `v1-data-engine` setting, so the validation of v1 volume is required as well.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-ui `be2408`) with [steps](https://github.com/longhorn/longhorn/issues/7505#issuecomment-1873374927)

Can see prompt after try create v2 volume from UI if v2 data engine not enabled.
![image](https://github.com/longhorn/longhorn/assets/73337386/3669b8d7-a326-4526-bd73-b4c0ea7deea3)
