### ISSUE TITLE
[TEST] Implement drain related test case in test_node.py

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#7521]
## What's the test to develop? Please describe

Implement test case `test_drain_with_block_for_eviction_success`, currently it only have test [skeleton](https://github.com/longhorn/longhorn-tests/blob/6be914f28bdd32bb2de4b9fb661ca6520ec557ad/manager/integration/tests/test_node.py#L2683)

implement test case `test_drain_with_block_for_eviction_if_contains_last_replica_success`, currently it only have [skeleton](https://github.com/longhorn/longhorn-tests/blob/b3a6cd6b2572f38e5f1669a33df3d99bd49885f3/manager/integration/tests/test_node.py#L2708) 

implement test case  `test_drain_with_block_for_eviction_failure`

**Comment by yangchiu** [comment]
@chriscchien Test cases failed in upgrade test pipeline:
https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/767/testReport/
https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-2-stage-upgrade-tests-sles-amd64/468/testReport/
https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-upgrade-tests-sles-arm64/768/testReport/
https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-2-stage-upgrade-tests-sles-arm64/459/testReport/

Could you help check them? Thanks!

**Comment by chriscchien** [comment]
> test_drain_with_block

It's due to pod `default/longhorn-test-upgrade-from-transient` located the drain node after upgrade complete, so the drain can not complete.

Should we consider to delete the upgrade pod after upgrade [complete](https://github.com/longhorn/longhorn-tests/blob/c80a8c01ad55dbb7c227377cb104109b70b0f134/test_framework/scripts/longhorn-setup.sh#L337)? thank you. 
```
test_node.py::test_drain_with_block_for_eviction_success node/ip-10-0-2-164 already cordoned
error: unable to drain node "ip-10-0-2-164" due to error:cannot delete Pods declare no controller (use --force to override): default/longhorn-test-upgrade-
```

**Comment by yangchiu** [comment]
> It's due to pod `default/longhorn-test-upgrade-from-transient` located the drain node after upgrade complete, so the drain can not complete.
> 
> Should we consider to delete the upgrade pod after upgrade [complete](https://github.com/longhorn/longhorn-tests/blob/c80a8c01ad55dbb7c227377cb104109b70b0f134/test_framework/scripts/longhorn-setup.sh#L337)? thank you.
> 

You can test and see if there's any impact, and feel free to refine anything to make things work again.

**Comment by chriscchien** [comment]
Test cases running properly now.
