### ISSUE TITLE
[IMPROVEMENT][UI] Display v2 volume actual size

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7524]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

https://github.com/longhorn/longhorn/issues/5947

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-ui `954076`)

1. Create v2 volume, create 4 snapshots with diffenent size, from UI can see the actucal size is the sum of all snapshots.
![image](https://github.com/longhorn/longhorn/assets/73337386/ff7de1e6-c831-4841-a312-d8ef94153b8e)

2. Delete 1 of the snapshot, the volume actual size changed and equal to sum of all snapshots.
![image](https://github.com/longhorn/longhorn/assets/73337386/f1118364-eceb-46ed-bdcb-92a41bf6e187)
