### ISSUE TITLE
[IMPROVEMENT] Setting Tab rename in Longhorn Web UI

### ISSUE THREAD

**Issue by rehman0288** [longhorn/longhorn#7528]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

In the Longhorn Web UI, among the various tabs we have Setting tab, and in there multiple options are available so we should change it from Setting to Settings. 

## Describe the solution you'd like

Change the name of Setting to Settings.

## Additional context

Longhorn version: 102.3.1+up1.5.3
Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
Number of management node in the cluster: 1
Number of worker node in the cluster: 3

**Comment by james-munson** [comment]
This issue needs more detail.  It ought to specify which version is being run, what the problem is, and ideally, a proposed change.

**Comment by rehman0288** [comment]
The name of the Setting tab should be Settings, it should be plural as there are multiple types settings under the tab.
