### ISSUE TITLE
Error: Failed to get taint toleration setting before starting CSI driver

### ISSUE THREAD

**Issue by phobos-dthorga** [longhorn/longhorn#753]
Okay, I'm not very good with these issue reports, so please be kind :) My environment consists of the following:

- Kubernetes as deployed by Rancher (not HA) across three nodes.
  - Using version `1.14.6-rancher1-1`.
  - Two of the nodes are deployed under a `KVM` hypervisor whilst the other is on a bare-metal server, all of which are under my complete control (i.e. I own all three bare-metal servers which include the `KVM` hypervisors that are installed too).
  - This is a custom setup and **not deployed** on AWS, GKE, etc.
  - `Canal` is the network provider for Kubernetes in this instance.
- There are plentiful resources to go around, including 24 GB of free RAM and 12 x free CPU cores.

The issue that I'm encountering is that I upgraded to `0.6.0` of the available Longhorn library from the applications database, having had `0.5.9` previously installed which worked perfectly fine. But upon upgrading, I was greeted with this from `longhorn-driver-deployer`:

```
time="2019-09-22T10:04:35Z" level=fatal msg="Error deploying driver: failed to get taint toleration setting before starting CSI driver: settings.longhorn.rancher.io \"taint-toleration\" not found"
```

This is also displayed at the top when viewing details about the application:

```
Failed to install app longhorn-system. Error: UPGRADE FAILED: timed out waiting for the condition
```

You may see my settings for the application by [clicking here](https://imgur.com/a/XZXxPd8). I think that's it though! I will now begin the process of rolling back to the previous version, since this Kubernetes cluster is a production system.

--
Regards,
Christopher McGill
Proprietor / Lead System Administrator

https://gekkofyre.io/
GekkoFyre Networks

**Comment by yasker** [comment]
@phobos-dthorga Thanks for reporting, we're looking into this now. Have you collected any log we can take a look?

**Comment by yasker** [comment]
@phobos-dthorga We found the problem, fixing it.

**Comment by yasker** [comment]
@phobos-dthorga We cannot reproduce the issue in the lab. Was your Longhorn UI up? That means UI can connect to the Longhorn manager and we would know the manager is up. In your case, I think it might be something blocking Longhorn manager from starting up correctly. Once Longhorn manager is up, `taint toleration setting` should be set.

I am not sure what's the root cause of the issue, but there is a workaround:

Copy the following code snippet into `toleration.yaml`:
```
apiVersion: longhorn.rancher.io/v1alpha1
kind: Setting
metadata:
  name: taint-toleration
  namespace: longhorn-system
value: ""
```
Then run `kubectl create -f toleration.yaml`. This should add the missing toleration setting.

**Comment by courcelm** [comment]
I just updated from 0.5 and I am also experiencing this problem. Workaround fixed the problem.

**Comment by yasker** [comment]
@courcelm Can you check the Longhorn managers' log and see if it's due to #754 ?

**Comment by yasker** [comment]
Sound like #754 is the culprit!

**Comment by yasker** [comment]
This is the symptom of #754 . Once the manager is up, the setting should be set correctly and deployer should continue to work.

**Comment by yasker** [comment]
@phobos-dthorga No problem, glad it resolved!

Just one note: the settings on the app page only apply if there is no current setting in the Longhorn UI (e.g. new installation or upgrade to a new version with more settings), to prevent accidentally overridden the current Longhorn setting.
