### ISSUE TITLE
[BUG] Replica Auto Balance options under General Setting and under Volume section should have similar case 

### ISSUE THREAD

**Issue by rehman0288** [longhorn/longhorn#7530]
## Describe the bug (🐛 if you encounter this issue)

The Replica Auto Balance feature is configurable from Setting -> General and from Volume tab and then selecting the volume and clicking the operation button on top gives us the option of Replica Auto Balance. But in both the cases the options of Replica Auto balance have different case. In Setting -> General all the options are in small case and when we access it from Volume tab the first character is in caps for all the options.

## To Reproduce

1. Click on Setting -> General
2. Check the options of Replica Auto Balance from drop down menu (all in small case)
3. Click on Volume tab
4. Select any Volume
5. Click on the operation button and click on Replica Auto Balance
6.  Check the option from drop down menu (first character is in caps)

## Expected behavior

When we access the Replica Auto Balance from the Volume tab, then all the options shown in drop down menu should be in lower case similar to the General Setting.

Currently Shown  - Should be
Ignored                 -> ignored 
Disabled               -> disabled
Least-Effort          -> least-effort
Best-Effort           -> best-effort

## Environment

Longhorn version: 102.3.1+up1.5.3
Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
Number of management node in the cluster: 1
Number of worker node in the cluster: 3
Node config
OS type and version: SLES-15-SP5 15.5
Kernel version: 1 SMP PREEMPT_DYNAMIC Fri Jul 28 08:40:19 UTC 2023 (52c1db3)
CPU per node: 8
Memory per node: 8GB
Disk type(e.g. SSD/NVMe/HDD): SSD
Network bandwidth between the nodes:
Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
Number of Longhorn volumes in the cluster: 5
Impacted Longhorn resources:
Volume names: vol01

## Additional context

Attaching the Screenshots: 
![Replica Auto Balance - General Setting](https://github.com/longhorn/longhorn/assets/38204740/fe3e381c-c183-4cb0-a65f-875f67f6e0c8)
![93](https://github.com/longhorn/longhorn/assets/38204740/67e1b584-41b7-4194-92f6-739cee908eef)

**Comment by c3y1huang** [comment]
This is related to UI.

https://github.com/longhorn/longhorn-ui/blob/v1.5.x/src/routes/volume/UpdateReplicaAutoBalanceModal.js#L80-L83

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-ui a6816f3) following [the test steps](https://github.com/longhorn/longhorn/issues/7530#issuecomment-2178080250). All options name are in lowercase.
