### ISSUE TITLE
[BUG] test case test_metric_longhorn_snapshot_actual_size_bytes failed

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7532]
## Describe the bug (🐛 if you encounter this issue)

Test case `test_metric_longhorn_snapshot_actual_size_bytes` constantly fails on master-head:

```

client = <longhorn.Client object at 0x7f4788468a00>
core_api = <kubernetes.client.api.core_v1_api.CoreV1Api object at 0x7f4787f1caf0>
metric_name = 'longhorn_snapshot_actual_size_bytes'
metric_labels = {'user_created': 'true', 'volume': 'longhorn-testvol-582d1q'}
expected_count = 4

    def check_metric_count_all_nodes(client, core_api, metric_name, metric_labels, expected_count): # NOQA
        # Find the metrics based on the given labels.
        def filter_metrics_by_labels(metrics, labels):
            filtered_metrics = []
            for metric in metrics:
                is_matched = True
                for key, value in labels.items():
                    if type(value) in (float, int):
                        continue
    
                    if metric.labels[key] != value:
                        is_matched = False
                        break
    
                if is_matched:
                    filtered_metrics.append(metric)
    
            print(filtered_metrics)
            return filtered_metrics
    
        filtered_metrics = []
        for node in client.list_node():
            metric_data = get_metrics(core_api, node.name)
    
            metrics = find_metrics(metric_data, metric_name)
            if len(metrics) == 0:
                continue
    
            filtered_metrics.extend(
                filter_metrics_by_labels(metrics, metric_labels)
            )
    
>       assert len(filtered_metrics) == expected_count
E       assert 1 == 4
E         -1
E         +4

test_metric.py:193: AssertionError
```

https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/773/testReport/junit/tests/test_metric/test_metric_longhorn_snapshot_actual_size_bytes/

This test case is newly added from https://github.com/longhorn/longhorn-tests/pull/1626

## To Reproduce

Run test case `test_metric_longhorn_snapshot_actual_size_bytes`

## Environment

 - Longhorn version: master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

**Comment by yangchiu** [comment]
@c3y1huang Could you help to have a look at this? Thank you!

**Comment by c3y1huang** [comment]
Test case fails due to a slight delay in creating snapshots and collecting metrics.

**Comment by yangchiu** [comment]
This doesn't happen again on master-head daily regression:

https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/779/testReport/tests/test_metric/test_metric_longhorn_snapshot_actual_size_bytes/
https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/726/testReport/tests/test_metric/test_metric_longhorn_snapshot_actual_size_bytes/
