### ISSUE TITLE
[FEATURE] v2 volume supports filesystem trim 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7534]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

v2 volume supports filesystem trim 

## Describe the solution you'd like

The feature request includes the subtasks
- [x] https://github.com/longhorn/longhorn/issues/7925
- [x] Check the volume field `volume.Spec.UnmapMarkSnapChainRemove` and the related setting of https://longhorn.io/docs/1.6.0/nodes-and-volumes/volumes/trim-filesystem/#the-volume-spec-field-unmapmarksnapchainremoved for v2 volume.

**Comment by innobead** [comment]
@derekbit is this a duplicated one as you have worked on another issue related to unmap?

**Comment by derekbit** [comment]
> @derekbit is this a duplicated one as you have worked on another issue related to unmap?

There is a subtask https://github.com/longhorn/longhorn/issues/7925.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `ad7420`) with test [steps](https://github.com/longhorn/longhorn/issues/7534#issuecomment-1963372139)

Filesystem trim operation worked properly on V2 volume.

**Comment by derekbit** [comment]
Updated in https://github.com/longhorn/website/pull/951
