### ISSUE TITLE
[TASK] Introduce `upgradeVersionCheck` to decide version upgrade enforcement 

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#7539]
## What's the task? Please describe

Requesting to allow Harvester users to skip version 1.5 and upgrade directly from version 1.4 to 1.6. Upgrade version enforcement requires a new path to be created. Besides, having this new mechanism to bypass version performance in some specific user cases. 

## Describe the sub-tasks

- Add back 1.4 -> 1.5 upgrade path migration code
- Disable pre-upgrade check for Longhorn manager
- Change the values.yaml by adding `upgradeVersionCheck` value to decide to do the upgrade version check in the Longhorn manager. 

```yaml
helmPreUpgradeCheckerJob:
  enabled: true
```

```yaml
preUpgradeChecker:
  jobEnabled: true
  upgradeVersionCheck: true
```

When setting `upgradeVersionCheck` true, we will have a warning log and event to inform users this is not a recommended behavior. For Harvester, they can take this as a path for 1.4 -> 1.6. 

## Additional context

We need to maintain the upgrade paths of previous versions within the system, but this is a disadvantage.

cc @longhorn/qa

**Comment by mantissahz** [comment]
>When setting upgradeVersionCheck true, we will have a warning log and event to inform users this is not a recommended behavior. For Harvester, they can take this as a path for 1.4 -> 1.6.

@innobead 

Can it be that when setting upgradeVersionCheck `false`, we will skip the upgrade path check and have a warning log and event to inform users this is not a recommended behavior?

Because setting `preUpgradeChecker.jobEnabled` false does not exactly skip the upgrade path.

**Comment by mantissahz** [comment]
@chriscchien It's about the engine upgrade. I will check now.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `3a118a`)

Install longhorn v1.4.x by helm(have workload with volume), upgrade longhorn to v1.6.0-dev with below values in set values.yaml:

1. `preUpgradeChecker.jobEnabled=true` and `preUpgradeChecker.upgradeVersionCheck=true`, upgrade failed with below message
```
Error: UPGRADE FAILED: pre-upgrade hooks failed: 1 error occurred:
	* job failed: BackoffLimitExceeded
```
2. `preUpgradeChecker.jobEnabled=false` and `preUpgradeChecker.upgradeVersionCheck=true`, upgrade start but longhorn-manager crash with below log
```
time="2024-01-11T09:21:09Z" level=info msg="Checking if the upgrade path from v1.4.4 to v1.6.0-dev is supported" func=util.checkLHUpgradePath file="util.go:249"
time="2024-01-11T09:21:09Z" level=fatal msg="Error starting manager: failed to upgrade since upgrading from v1.4.4 to v1.6.0-dev for minor version is not supported" func=main.main.DaemonCmd.func3 file="daemon.go:92"
```
3. `preUpgradeChecker.jobEnabled=false` and `preUpgradeChecker.upgradeVersionCheck=false` upgrade success ane below operation worked well
   - [x] Upgrade engine
   - [x] Replica rebuilding
   - [x] Volume detach/attach by scale workload
   - [x] Restore volume from backup
   - [x]  V2volume create, offline rebuilding

**Comment by c3y1huang** [comment]
@mantissahz , we need to update the manual test case. https://github.com/longhorn/longhorn/issues/5842#issuecomment-1893007782

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `aaeae7`), longhor v1.6.x(longhorn-manager `43919c`)

Upgrade longhorn v1.4.x to master-head and v1.6.x-head by helm, the behavior were the same as previous test [result](https://github.com/longhorn/longhorn/issues/7539#issuecomment-1886721480)

In addition, after upgrade volume eninge image to master-head/v1.6.x-head, try change engine image back to v1.4.x-head again will be rejected.

And here is the eninge images status
```bash
> k get  engineimages -A
NAMESPACE         NAME          INCOMPATIBLE   STATE      IMAGE                                    REFCOUNT   BUILDDATE   AGE
longhorn-system   ei-4d51cf83   true           deployed   longhornio/longhorn-engine:v1.4.x-head   0          20h         27m
longhorn-system   ei-b907910b   false          deployed   longhornio/longhorn-engine:master-head   4          19h         21m
```
