### ISSUE TITLE
[FEATURE] Add BackupBackingImage UI

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#7541]
### Add UI for BackupBackingImage

This function can be a sub section in BackingImage page (just like `Snapshots` in Volume Page)
So in the BackingImage page
There will be a section listing all the BackupBackingImage with following columns
- Name
- State
- Size
- Created At
- Backup URL

### BackupBackingImage supports following operation
Operations
  - Delete (Can be put in the menu for each BackupBackingImage)
  - Restore (Can be put in the menu for each BackupBackingImage)

### Add new operation for BackingImage
- Create BackupBackingImage

## Describe the sub-tasks
- [x] Add a backupBackingImage table in backing image page
- [x] Backup backing image allow two operations : delete and restore 
- [x] Add `Backup` dropdown for each backing image to do backup
- [x] Add bulk `Delete` action on top of backup backing image table
- [x] Add bulk `Backup` action on top of backing image table
- [x] Add Search box for backup backing image table

## Additional context

Note. https://github.com/longhorn/longhorn/issues/8956 put in v1.8.0 to implement.

**Comment by ChanYiLin** [comment]
I have created another ticket to track the backend progress: https://github.com/longhorn/longhorn/issues/8068
Will try to finish the backend part this sprint.

cc @scures

**Comment by ChanYiLin** [comment]
Hi @scures 
The backend api PR has been created and might need some time to get it merged.
You can use my longhorn-manager image for the development.
`jackfantasy/longhorn-manager:backupbacking`

**Comment by ChanYiLin** [comment]
Here is a simple using flow of BackupBackingImage

1. Create BackingImage
```
name: parrot
downloadURL: https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.raw 
```
Note: keep the `checksum`

2. Test Create BackupBackingImage
```
curl -X POST http://localhost:8080/v1/backingimages/parrot?action=backupBackingImageCreate
```

3. Test Get BackupBackingImage
```
curl -X GET http://localhost:8080/v1/backupbackingimages/parrot
{"actions":{"backupBackingImageRestore":"http://localhost:8080/v1/backupbackingimages/parrot?action=backupBackingImageRestore"},"compressionMethod":"lz4","created":"2024-03-01T05:28:35Z","error":"","id":"parrot","labels":null,"links":{"self":"http://localhost:8080/v1/backupbackingimages/parrot"},"messages":null,"name":"parrot","progress":100,"size":33554432,"state":"Completed","type":"backupBackingImage","url":"nfs://longhorn-test-nfs-svc.default:/opt/backupstore?backingImage=parrot"}
```

4. Delete original BackingImage
```
$ kubectl delete lhbi/parrot -n longhorn-system
```

5. Restore BackingImage
```
curl -X POST http://localhost:8080/v1/backupbackingimages/parrot?action=backupBackingImageRestore
```

6. check the checksum is the same as original
7. Test Delete BackupBackingImage
```
curl -X DELETE http://localhost:8080/v1/backupbackingimages/parrot
```

**Comment by derekbit** [comment]
@mantissahz  Can you help verify the ticket? Feel free to check with @roger-ryao and @a110605. Thank you.

**Comment by mantissahz** [comment]
Verified **PASSED** on longhorn master(longhorn-manager 79f794) with [test steps](https://github.com/longhorn/longhorn/issues/7541#issuecomment-2217214705)
