### ISSUE TITLE
[BUG]Kafka re-create procedure has bug because of longhorn.

### ISSUE THREAD

**Issue by Vedooo** [longhorn/longhorn#7547]
## Describe the bug (🐛 if you encounter this issue)

I have a microservice architecture supported by longhorn storage in an on-prem k8s environment. Longhorn storage, which generally works smoothly, may cause problems in recreation situations in some 3rd party applications. One of them is Kafka. When I re-deploy, Kafka cannot remount to the paths I set as volumeMount, and a longhorn PVC does not appear as an error message, thats why The pod remains in the containerCreating state.

The problem here is that one pv of the kafka pod cannot be attached with another pvc. However, due to a situation that I don't know why, Kafka gets attached to a PVC and stands up after a long time after it is re-created, the time being variable. I cannot manage this situation. I'm wondering what the problem is here. I would appreciate it if you could clarify.

## Expected behavior

The created pod is attached to the longhorn PVC's in the required period and stands up.

## Environment

 - Longhorn version: v1.5.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 5
 - Node config
   - OS type and version: ubuntu

**Comment by innobead** [comment]
@Vedooo could you also provide the [support bundle](https://longhorn.io/docs/1.5.3/advanced-resources/support-bundle/)? also specify which volume (PV, also it's PVC) was impacted.
