### ISSUE TITLE
[BUG] volume engine failed to live upgrade

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#7548]
## Describe the bug (🐛 if you encounter this issue)

Test case `test_engine_live_upgrade_with_intensive_data_writing` failed on `master-head`.  From the console log, that the volume engine failed to perform a live upgrade. We were able to reproduce the issue manually. Not sure if it is the same issue as https://github.com/longhorn/longhorn/issues/7540.

```
>       wait_for_volume_current_image(client, volume_name, engine_upgrade_image)

test_engine_upgrade.py:712: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

client = <longhorn.Client object at 0x7f6ed02cdd00>
name = 'longhorn-testvol-yq34yo'
image = 'longhornio/longhorn-test:upgrade-test.9-8.5-4.1-1'

    def wait_for_volume_current_image(client, name, image):
        wait_for_volume_creation(client, name)
        for i in range(RETRY_COUNTS):
            volume = client.by_id_volume(name)
            if volume.currentImage == image:
                break
            time.sleep(RETRY_INTERVAL)
>       assert volume.currentImage == image
E       AssertionError

common.py:2016: AssertionError
```

## To Reproduce

Rerun [the job](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5851/) with private image

or

1. Create a volume using the UI.
1. Attach the volume to the node.
1. Create an engine image: `longhornio/longhorn-test:upgrade-test.9-8.5-4.1-1`.
1. Upgrade the volume engine to `longhornio/longhorn-test:upgrade-test.9-8.5-4.1-1`.

## Expected behavior

Have consistent tested result in all branches result

## Support bundle for troubleshooting

[longhorn-tests-regression-5851-bundle.zip](https://github.com/longhorn/longhorn/files/13828768/longhorn-tests-regression-5851-bundle.zip)

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

**Comment by derekbit** [comment]
`longhorn` utility in the test engine image (`longhornio/longhorn-test:version-test.9-8.5-4.1-1`) cannot work.
```
 # /engine-binaries/longhornio-longhorn-test-version-test.9-8.5-4.1-1/longhorn
{
	"clientVersion": {
		"version": "version-test.9-8.5-4.1-1",
		"gitCommit": "onlytestnogitcommit",
		"buildDate": "2018-06-11T00:00:00+00:00",
		"cliAPIVersion": 9,
		"cliAPIMinVersion": 8,
		"controllerAPIVersion": 5,
		"controllerAPIMinVersion": 4,
		"dataFormatVersion": 1,
		"dataFormatMinVersion": 1
	},
	"serverVersion": {
		"version": "version-test.9-8.5-4.1-1",
		"gitCommit": "onlytestnogitcommit",
		"buildDate": "2018-06-11T00:00:00+00:00",
		"cliAPIVersion": 9,
		"cliAPIMinVersion": 8,
		"controllerAPIVersion": 5,
		"controllerAPIMinVersion": 4,
		"dataFormatVersion": 1,
		"dataFormatMinVersion": 1
	}
}
```

An expected output should be
```
# /engine-binaries/longhornio-longhorn-engine-master-head/longhorn
warning: GOCOVERDIR not set, no coverage data emitted
NAME:
   longhorn - A new cli application

USAGE:
   longhorn [global options] command [command options] [arguments...]

VERSION:
   12e92e84

COMMANDS:
   controller
   replica
   sync-agent
   sync-agent-server-reset
   start-with-replicas, start
   add-replica, add
   verify-rebuild-replica, verify-rebuild
   ls-replica, ls
   rm-replica, rm
   update-replica, update
...
```

**Comment by derekbit** [comment]
The test upgrade image should be `longhornio/longhorn-test:upgrade-test.9-8.5-4.1-1`.

The issue is due to the image cannot support he newly introduced options  (`--snapshot-max-count` and `--snapshot-max-size`). @chriscchien Can you help rebuild a new test image? Thank you.

**Comment by chriscchien** [comment]
Because the longhorn-engine version not updated, so the build test engine pipeline think the target version exist, there is no need to build. Maybe delete `longhornio/longhorn-test:upgrade-test.9-8.5-4.1-1`  and build test engine image again can reslove this issue.

cc @yangchiu

**Comment by derekbit** [comment]
@roger-ryao 
Move to ready-for-testing. Need your help for testing it using the new image. Thank you.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-engine `f86f4a`)

test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5865/testReport/tests/test_engine_upgrade/) of `test_engine_upgrade ` passed

For the failed test case [test_engine_live_upgrade_with_intensive_data_writing](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5865/testReport/tests/test_engine_upgrade/test_engine_live_upgrade_with_intensive_data_writing/), it has been  logged in https://github.com/longhorn/longhorn/issues/7396
