### ISSUE TITLE
[IMPROVEMENT] Recreate instance manager pod for v2 volume when `spdk_tgt` is dead

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7551]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

spdk_tgt might be somehow dead due to
```
[ 6720.296447] reactor_0[11215]: segfault at 10 ip 00000000004fb2da sp 00007ffe5c445cb0 error 4 in spdk_tgt[400000+3d5000]
[ 6720.296466] Code: 48 8b b7 f8 02 00 00 48 8b 40 18 48 8b 18 48 85 f6 74 17 48 8b 97 00 03 00 00 e8 51 ff ff ff 48 c7 85 f8 02 00 00 00 00 00 00 <8b> 43 10 3b 43 14 0f 83 8a 00 00 00 83 c0 01 89 43 10 48 8b 03 48
```
Instance manager pod should detect it and terminate itself.

**Comment by innobead** [comment]
cc @DamiaSan

**Comment by derekbit** [comment]
segfault in `spdk_tgt` needs further investigation and @DamiaSan's help.

The PRs I submitted are improving the resilience.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `325252`) test [steps](https://github.com/longhorn/longhorn/issues/7551#issuecomment-1878112336)

After kill `spdk_tgt` in v2 volume instance-manager pod, the instance-manager pod will recreate and after pod ready, all volumes worked well. (tested on freash installed `v1.6.0-dev` and upgrade from `v1.5.3`)
