### ISSUE TITLE
[BUG] After upgrade to master-head, existing volume won't rebuild replica if one deleted, and the volume keeps healthy instead of degraded

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7555]
## Describe the bug

After upgrade Longhorn from `v1.5.3` to `master-head`, if deleting a replica of an existing volume, there's no replica rebuilding will be triggered, and the volume keeps in healthy state instead of degraded state.

## To Reproduce

1. Install Longhorn `v1.5.3`
2. Create a volume from UI and attach it to a node
3. Upgrade Longhorn to `master-head`
4. Upgrade the engine image of the created volume
5. Delete a replica of this volume from UI
6. No replica rebuilding triggered, and the volume remains healthy:
![Screenshot from 2024-01-05 09-46-28](https://github.com/longhorn/longhorn/assets/5709208/ecf91f43-a357-4d62-a8d9-3cdadb9a1ca9)

## Support bundle for troubleshooting

[supportbundle_36e80b72-82ff-4a37-aa9a-4cb77ad45ee0_2024-01-05T01-49-08Z.zip](https://github.com/longhorn/longhorn/files/13837066/supportbundle_36e80b72-82ff-4a37-aa9a-4cb77ad45ee0_2024-01-05T01-49-08Z.zip)

## Environment

 - Longhorn version: master-head (longhorn-manager e532739)
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

Related in upgrade test case in daily regression: https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-upgrade-tests-sles-arm64/713/testReport/junit/tests/test_upgrade/test_upgrade_from_stable_/

**Comment by derekbit** [comment]
A ton of the error messages in the longhorn-manager log

```
2024-01-05T01:45:49.071372041Z E0105 01:45:49.071250       1 engine_controller.go:839] failed to update status for engine test-2-e-0: failed to correct flag SnapshotMaxCount from 0 to 250: proxyServer=10.42.3.8:8501 destination=10.42.3.8:10023: failed to set SnapshotMaxCount: rpc error: code = Unimplemented desc = unknown method VolumeSnapshotMaxCountSet for service imrpc.ProxyEngineService
2024-01-05T01:45:49.071454188Z E0105 01:45:49.071391       1 engine_controller.go:839] failed to update status for engine test-1-e-0: failed to correct flag SnapshotMaxCount from 0 to 250: proxyServer=10.42.3.8:8501 destination=10.42.3.8:10022: failed to set SnapshotMaxCount: rpc error: code = Unimplemented desc = unknown method VolumeSnapshotMaxCountSet for service imrpc.ProxyEngineService
```

cc @FrankYang0529

**Comment by innobead** [comment]
Good catch. This part was missed. Need to fix.

**Comment by yangchiu** [comment]
Upgrade test case can pass on master-head in daily regression:

https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/710/testReport/tests/test_upgrade/test_upgrade_from_stable_/
https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-upgrade-tests-sles-arm64/717/testReport/tests/test_upgrade/test_upgrade_from_stable__2/
