### ISSUE TITLE
How re-install longhorn

### ISSUE THREAD

**Issue by matrixoneken** [longhorn/longhorn#7556]
I install longhorn with rancher web ui
I uninstall longhorn with kubeclt delete namespaces
I want to install longhorn again with rancher web ui
I get error  can not run  "helm-operation-9k8fn"
When I see the log about     "helm-operation-9k8fn" , I get following error

failed to create: secrets "sh.helm.release.v1.longhorn-crd.v1" is forbidden: unable to create new content in namespace longhorn-system because it is being terminated

Can you tell my how reinstall longhorn again. Thank you.

**Comment by chriscchien** [comment]
Hi @matrixoneken, the namespace `longhorn-system` is terminating, the installation can not proceed in this state.
Maybe delete all longhorn [CRD](https://longhorn.io/docs/1.6.0/deploy/uninstall/#problems-with-crds) can help, thank you.

**Comment by matrixoneken** [comment]
@chriscchien  Can tell me how to delete all longhorn CRD
your provided url can not work, I use "kubectl get crd |grep longhorn.io"
and get following list

backups.longhorn.io                                   2023-04-03T01:22:10Z
backupvolumes.longhorn.io                             2023-04-03T01:22:10Z
engineimages.longhorn.io                              2023-04-03T01:22:10Z
engines.longhorn.io                                   2023-04-03T01:22:10Z
replicas.longhorn.io                                  2023-04-03T01:22:10Z
systembackups.longhorn.io                             2023-04-03T01:22:10Z
volumeattachments.longhorn.io                         2024-01-05T03:44:53Z
volumes.longhorn.io                                   2023-04-03T01:22:10Z

I use  kubectl delete crd/backups.longhorn.io
It was keep waiting
<img width="456" alt="1704434776(1)" src="https://github.com/longhorn/longhorn/assets/41671830/b5515f7d-a9b7-4ee1-a7d4-bba003a71883">

**Comment by matrixoneken** [comment]
@chriscchien  I can delete crd with "kubectl patch crd/volumes.longhorn.io       -p '{"metadata":{"finalizers":[]}}' --type=merge"
but when I install longhorn again in rancher, I get following error:
![image](https://github.com/longhorn/longhorn/assets/41671830/300db037-4ed6-4609-8173-0007e7889ead)

 kubectl logs longhorn-manager-dvmbf  -n longhorn-system
<img width="712" alt="1704435949(1)" src="https://github.com/longhorn/longhorn/assets/41671830/4356b2b7-ed32-4e49-a04d-f9fbd75d75f2">

<img width="582" alt="1704435994(1)" src="https://github.com/longhorn/longhorn/assets/41671830/edbcd9d0-fb72-41d6-b536-fd2d3fadef54">

**Comment by matrixoneken** [comment]
@chriscchien  I can find the images on my server. Why the longhorn-manager can not find images
<img width="652" alt="1704436750(1)" src="https://github.com/longhorn/longhorn/assets/41671830/d0698c44-e4e8-4e4a-9c0f-7ecbf789e7c6">

**Comment by chriscchien** [comment]
Have you installed success before(could tell me the version)? and you may need use the correct images of each [compoment](https://raw.githubusercontent.com/longhorn/longhorn/v1.5.3/deploy/longhorn-images.txt)

**Comment by matrixoneken** [comment]
I have installed the old version 1.4.0 before.
I want to update to new version. I install with rancher web ui.

**Comment by chriscchien** [comment]
If you want to deploy v1.5.3, those images mentioned [here](https://raw.githubusercontent.com/longhorn/longhorn/v1.5.3/deploy/longhorn-images.txt) need to be prepared to your regristry first. From the pticure above, some components's version not compatible to v1.5.3.

**Comment by matrixoneken** [comment]
@chriscchien  I have run docker pull all images about v1.5.3
I also run kubeclt apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.5.3/deploy/longhorn.yaml
I still can not re-install longhorn，get error in  longhorn-manager pod , please see the following images


<img width="712" alt="1704955248(1)" src="https://github.com/longhorn/longhorn/assets/41671830/60e64ac1-9023-47d8-a02c-d9a071b79f5c">

**Comment by c3y1huang** [comment]
> I have run docker pull all images about v1.5.3 I also run kubeclt apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.5.3/deploy/longhorn.yaml I still can not re-install longhorn，get error in longhorn-manager pod , please see the following images
> 
> <img alt="1704955248(1)" width="712" src="https://private-user-images.githubusercontent.com/41671830/295814194-60e64ac1-9023-47d8-a02c-d9a071b79f5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2ODkzMTAsIm5iZiI6MTcwNjY4OTAxMCwicGF0aCI6Ii80MTY3MTgzMC8yOTU4MTQxOTQtNjBlNjRhYzEtOTAyMy00N2Q4LWEwMmMtZDlhMDcxYjc5ZjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA4MTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YmE1MjI3NzhiODQ1Njc3YTUwYTAwNWFjNDc5ZTE1OGRmN2I0ODVlOWIzYjNkODRmYjUxMWQ1ZDUxOTc4M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DE5Wd-UfPjGgSdi3XDJ0cTSCiPhwbQXEJIgyTkOAh3c">

Are you able to follow the [Uninstall Longhorn](https://longhorn.io/docs/1.5.3/deploy/uninstall/) process from this point?
