### ISSUE TITLE
[BUG] `spdk_tgt` is somehow crashed

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7559]
## Describe the bug

spdk_tgt might be somehow dead due to

```
[ 6720.296447] reactor_0[11215]: segfault at 10 ip 00000000004fb2da sp 00007ffe5c445cb0 error 4 in spdk_tgt[400000+3d5000]
[ 6720.296466] Code: 48 8b b7 f8 02 00 00 48 8b 40 18 48 8b 18 48 85 f6 74 17 48 8b 97 00 03 00 00 e8 51 ff ff ff 48 c7 85 f8 02 00 00 00 00 00 00 <8b> 43 10 3b 43 14 0f 83 8a 00 00 00 83 c0 01 89 43 10 48 8b 03 48
```

addr2line indicates the crash happened in [spdk_bdev_free_io()](https://github.com/longhorn/spdk/blob/longhorn/lib/bdev/bdev.c#L2414) 

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

https://github.com/longhorn/longhorn/issues/7551

cc @DamiaSan

**Comment by DamiaSan** [comment]
Could you add the steps to reproduce this bug?

**Comment by derekbit** [comment]
> Could you add the steps to reproduce this bug?

Well...I don't have concrete steps. 
You can remove the codes for resilience I added and repeat the steps in https://github.com/longhorn/longhorn/issues/7551#issuecomment-1878112336. It you are lucky, you can see the crash.

**Comment by DamiaSan** [comment]
> You can remove the [codes](https://github.com/longhorn/longhorn-manager/pull/2433) I added and repeat the steps in [#7551 (comment)](https://github.com/longhorn/longhorn/issues/7551#issuecomment-1878112336). It you are lucky, you can see the crash.

Sorry Derek bu in those list I don't see any particular steps that could cause a crash: spdk is inactive (there are no I/O running) and is simply killed .

**Comment by derekbit** [comment]
> > You can remove the [codes](https://github.com/longhorn/longhorn-manager/pull/2433) I added and repeat the steps in [#7551 (comment)](https://github.com/longhorn/longhorn/issues/7551#issuecomment-1878112336). It you are lucky, you can see the crash.
> 
> Sorry Derek bu in those list I don't see any particular steps that could cause a crash: spdk is inactive (there are no I/O running) and is simply killed .

Hmm, I'm not sure how it is triggered, but I just repeated the steps before and saw the crash. it is not really easy to reproduce.
IIRC, @shuo-wu ran into the similar crash before?

**Comment by shuo-wu** [comment]
No. Will these errors be printed in instance manager logs?

**Comment by derekbit** [comment]
> No. Will these errors be printed in instance manager logs?

No

**Comment by DamiaSan** [comment]
I suggest to try again with the last [version](https://github.com/longhorn/longhorn-instance-manager/commit/53446d898418f657d298102a447bfa1071ec7420) of `longhorn-instance-manager`, it includes:

- `SPDK` updated to the lastest upstream release 24.01
- `longhorn-spdk-engine` with the [sync fix](https://github.com/longhorn/longhorn-spdk-engine/commit/da2a02e86462fb4f3abac4d0f91f2380ff34053c) that is often the root cause of `SPDK` and `nvmecli`  crashes and of memory corruption inside nvme kernel driver. About this, kernel 6.7 has a better error handling inside nvme driver

**Comment by DamiaSan** [comment]
The code that originated this issue is quite obsolete, now we are ready to use upstream release 24.05.
Whar are we going to do with this issue?
@shuo-wu @innobead @derekbit

**Comment by DamiaSan** [comment]
Documentation update PR https://github.com/longhorn/website/pull/929

**Comment by derekbit** [comment]
Completed.
