### ISSUE TITLE
trying and failing to pull longhorn-manager:6.0 image 

### ISSUE THREAD

**Issue by thomasmodeneis** [longhorn/longhorn#756]
kubectl apply results in a hanging longhorn-manager due to the script longhorn.yaml being updated to 6.0 but the image is not yet released https://hub.docker.com/r/rancher/longhorn-manager/tags.

Shall I build the image myself or this is going to happen sometime soon ?
Cheers.

```
> kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml

--
> kubetail longhorn-manager -n longhorn-system
Error from server (BadRequest): container "longhorn-manager" in pod "longhorn-manager-v4qlm" is waiting to start: trying and failing to pull image
Error from server (BadRequest): container "longhorn-manager" in pod "longhorn-manager-lh9rp" is waiting to start: trying and failing to pull image
```

**Comment by yasker** [comment]
@thomasmodeneis 

We have an issue #754 for v0.6.0 release, so we pulled image temporarily. We will update the image with the fix soon.

**Comment by thomasmodeneis** [comment]
Great thanks.

**Comment by yasker** [comment]
@thomasmodeneis We've put back the image with a hotfix. It's not a standard procedure (since the tags would be wrong), but `longhornio/longhorn-manager:v0.6.0` should be fine for now.

We will release v0.6.1 with the official fix today.

**Comment by yasker** [comment]
Note: for the record, the current v0.6.0 image is generated by the commit:

```
commit 066de0dd585267857dc63754ad1b48b61e8d54b5
Author: Sheng Yang <sheng.yang@rancher.com>
Date:   Mon Sep 23 09:18:35 2019 -0700

    controller: Kubernetes: Fix NPE caused by CSI driver checking

    Longhorn #754

    Signed-off-by: Sheng Yang <sheng.yang@rancher.com>
```

**Comment by thomasmodeneis** [comment]
Great, thanks for the heads-up.
