### ISSUE TITLE
[IMPROVEMENT] Restore Latest Backup should be applied with BackingImage name value

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#7560]
## What's the task? Please describe

For the  `"Restore Latest Backup"` on the top right next to `"Create Disaster Recovery Volume"`, which is a bulk restore button 

<img width="1207" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMktmQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b685e5298ad908145f664fafd77460b2cb62270f/Screenshot%20from%202024-01-05%2017-01-49.png" alt="Screenshot from 2024-01-05 17-01-49.png" />

`"Backing Image"` Should like the `"Name: <Volume Name>"` which has been filled in with the BackingImageName from the return data for every BackupVolume

## Additional context
Every Backup Volume has different BackingImage so it should not be applied with the same value
API needs the BackingImage value so it can restore the BackingImage when it is not found in the system and is in backupstore.

**Comment by a110605** [comment]
@ChanYiLin , double confirm when user select multiple backups and click `Restore Latest Backup` , the **Backing Image** field  should auto filled with corrsponding backing image name.  

e.g. If select two backups, there should pop two restore modals.
<img width="1475" alt="Screenshot 2024-05-21 at 12 20 11 PM" src="https://github.com/longhorn/longhorn/assets/5744158/abf2c40b-46b8-436e-bbd1-99a859ecf08b">

**Comment by a110605** [comment]
BTW, the `Restore Latest Backup` in each backup row actually create new volume, not do the restore ? 
We should rename that button something like `create new volume from backup`?

![restore](https://github.com/longhorn/longhorn/assets/5744158/4e515acf-837a-46cc-875b-bc4f27017833)

**Comment by a110605** [comment]
Per discussed with @ChanYiLin , change items are
- When click bulk `Restore Latest Backup`, we should let user edit `name` and if this backup has backing image field, we should pre-filled `backing image` and mark as grey out (un-editable).
- Consider term `restore latest backup` -> `Create volume from latest backup` which is more closer  this button behavior. (will consult technique writer)

**Comment by roger-ryao** [comment]
**Verified on master-head 20240627**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/11a0f16963100e363dcb59bfbe8c4934e8784d60
- longhorn-ui `master-head` https://github.com/longhorn/longhorn-ui/commit/3c550816051cb1895bbd59c1c7c70de8779d8679

**The test steps**
https://github.com/longhorn/longhorn/issues/7560#issuecomment-2141559918

**Result Passed**

1. The backing image field is prefilled and disabled.
2. Users can configure each backup individually or click the **Apply All** button to apply the same configuration to all tabs.
3. Restoring and creating DR volumes are working normally.
