### ISSUE TITLE
[FEATURE] Support backing image metrics collection

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#7563]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

This is similar to what we have for volume and backup metrics.

## Describe the solution you'd like

- Metrics about backing image
- Metrics about backing image backup

**Comment by chriscchien** [comment]
Hi @ChanYiLin ,

I have a backing image `test-bak` and can not get related info through metrics
```bash
> k get pods -A -o wide | grep longhorn-manager
longhorn-system   longhorn-manager-kfwbv                              1/1     Running     1 (18m ago)   18m     10.42.0.49      ip-172-31-32-236   <none>           <none>
longhorn-system   longhorn-manager-mlhcb                              1/1     Running     1 (17m ago)   18m     10.42.2.61      ip-172-31-32-234   <none>           <none>
longhorn-system   longhorn-manager-wwm7w                              1/1     Running     1 (17m ago)   18m     10.42.1.61      ip-172-31-46-109   <none>           <none>
>
> k get backingimage -A
NAMESPACE         NAME       UUID       SOURCETYPE   SIZE       VIRTUALSIZE   AGE
longhorn-system   test       f0f35da8   download     1161728    33554432      10m
longhorn-system   test-bak   b8c4f347   download     33554432   33554432      2m15s
>
> curl -sSL http://10.42.0.49:9500/metrics | grep test-bak
> curl -sSL http://10.42.2.61:9500/metrics | grep test-bak
> curl -sSL http://10.42.1.61:9500/metrics | grep test-bak
>
```

In addition, there are no backingimage info in https://longhorn.io/docs/1.7.0/monitoring/metrics/ to validate, could youn help me on this? thank you.

**Comment by ChanYiLin** [comment]
Hi @chriscchien 
I have fixed the bug and add the documents.
Please test it again, thanks!

**Comment by ChanYiLin** [comment]
Hi @chriscchien 
Since there is no BackupBackingImage UI
You have to use yaml to create the BackupBackingImage
example:
```
apiVersion: longhorn.io/v1beta2
kind: BackupBackingImage
metadata:
  name: parrot  // the name should be the same as the BackingImage, it is 1-1 mapping
  namespace: longhorn-system
spec:
  userCreated: true
``` 
the CRD is `lhbbi`
```
$ kubectl get lhbbi -n longhorn-system
```

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `6d936d`) with test [steps](https://longhorn.io/docs/1.7.0/monitoring/metrics/)

BackingImage
- longhorn_backing_image_actual_size_bytes
- longhorn_backing_image_state
   -  [x] 0 = Pending
   -  [x] 1 = Starting
   -  [x] 2 = InProgress
   -  [x] 3 = ReadyForTransfer
   -  [x] 4 = Ready
   -  [x] 5 = Failed - performed by uploading backingimage then terminate the upload process
   -  [x] 6 = FailedAndCleanUp - performed  by uploadimg backingimage then terminate the upload process
   -  [x] 7 = Unknown - performed by delete the backing-image-manager pod

BackupBackingImage
- longhorn_backup_backing_image_actual_size_bytes
- longhorn_backup_backing_image_state
   -  [x] 0=New
   -  [x] 1=Pending - hard to perform, only happened when grpc timeout
   -  [x] 2=InProgress
   -  [x] 3=Completed
   -  [x] 4=Error -  by set empty backup target
   -  [x] 5=Unknown - Can not make it to unknow, but should keep it for align with backup (consulted with @ChanYiLin )
