### ISSUE TITLE
[IMPROVEMENT] Prevent from complains in spdk_tgt when deleting a v2 volume

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7568]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

spdk_tgt complains the improper sequence of deleting engines and replicas.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240109**

- longhorn master-head https://github.com/longhorn/longhorn/commit/96a0995708b4479bd29a55ee74fd36090dad9962
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/2931e5b7bbc88849f67e9eb9cdab32b3fa531da4


**The test steps**

1. https://github.com/longhorn/longhorn/issues/7568#issuecomment-1879991081

**Result**

- [ ] `require/doc` : No documentation needed for this improvement
- [ ] `require/auto-e2e-test` : Not applicable
- [ ] `require/backport` : Should this improvement be backported to Longhorn 1.5.x?

cc @derekbit

**Comment by derekbit** [comment]
>  require/backport

I think we don't need to backport it. WDYT? @innobead 

> require/doc

Internal improvement. doc is not needed.

> require/auto-e2e-test

The update is making spdk_tgt stop complain.  e2e-test is not needed as well.

**Comment by innobead** [comment]
Those labels are added by default for improvement tickets. Remove them next time if there is no needed.
