### ISSUE TITLE
[BUG] After v2 volume offline rebuilding, re-attached volume remains degraded

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7574]
## Describe the bug

Create a v2 volume with 3 replicas, and delete some replicas of a v2 volume, and detach it to trigger offline rebuilding. After the offline rebuilding completed, re-attach the volume, but the volume only has 2 replicas and is in `degraded` state.

## To Reproduce

1. Create v2 volume environment
2. Create a v2 volume `test-1` with 3 replicas from UI and also create PV/PVC for it from UI
3. Create a pod for it:
```
cat << EOF > pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: sleep
      image: busybox
      imagePullPolicy: IfNotPresent
      args: ["/bin/sh", "-c", "while true;do date;sleep 5; done"]
      volumeMounts:
        - name: pod-data
          mountPath: /data
  volumes:
    - name: pod-data
      persistentVolumeClaim:
        claimName: test-1
EOF
kubectl apply -f pod.yaml
```
4. Write some data to the volume:
```
dd if=/dev/urandom of=/data/test-1 bs=3M count=1024
```
5. Create backup from UI, and during the backup in progress, delete some replicas to make the backup be in `Error` state:
(Not sure if `Create backup` is necessary to reproduce this issue)
```
$ kubectl get backups -n longhorn-system backup-ae5264e951594c20 -oyaml
apiVersion: longhorn.io/v1beta2
kind: Backup
metadata:
  creationTimestamp: "2024-01-08T03:32:35Z"
  finalizers:
  - longhorn.io
  generation: 1
  labels:
    backup-volume: test-4
  name: backup-ae5264e951594c20
  namespace: longhorn-system
  resourceVersion: "26161"
  uid: f81b9dd2-7d32-46ec-b982-a3905599ecb7
spec:
  labels:
    KubernetesStatus: '{"pvName":"test-4","pvStatus":"Bound","namespace":"default","pvcName":"test-4","lastPVCRefAt":"","workloadsStatus":[{"podName":"test-pod-4","podStatus":"Running","workloadName":"","workloadType":""}],"lastPodRefAt":""}'
    longhorn.io/volume-access-mode: rwo
  snapshotName: fdc06fc9-89b7-4bb5-a958-032f51d75a2c
  syncRequestedAt: null
status:
  backupCreatedAt: ""
  compressionMethod: ""
  error: 'proxyServer=10.42.2.36:8501 destination=10.42.1.31:20013: failed to get
    backup-ae5264e951594c20 backup status: rpc error: code = Internal desc = failed
    to get backup status: rpc error: code = NotFound desc = replica address 10.42.3.34:20007
    is not found in engine test-4-e-0 for getting backup backup-ae5264e951594c20 status'
  labels: null
  lastSyncedAt: "2024-01-08T03:32:54Z"
  messages: null
  ownerID: ip-10-0-1-238
  progress: 10
  replicaAddress: ""
  size: ""
  snapshotCreatedAt: "2024-01-08T03:32:35Z"
  snapshotName: fdc06fc9-89b7-4bb5-a958-032f51d75a2c
  state: Error
  url: ""
  volumeBackingImageName: ""
  volumeCreated: ""
  volumeName: ""
  volumeSize: "21474836480"
``` 
6. Detach the volume to trigger offline rebuilding:
```
kubectl delete -f pod.yaml
```
7. After offline rebuilding completed, re-attach the volume:
```
kubectl apply -f pod.yaml
```
8. The volume only has 2 replicas and still in `degraded` state:
![test-4](https://github.com/longhorn/longhorn/assets/5709208/ebffb8d6-8443-4522-8d2b-b1b30dc1bc7d)

Please see volume `test-4` related logs in the support bundle for more details.

## Support bundle for troubleshooting
[supportbundle_43c90f10-cff2-486a-bf7b-dc91761bf1ea_2024-01-08T04-00-48Z.zip](https://github.com/longhorn/longhorn/files/13856127/supportbundle_43c90f10-cff2-486a-bf7b-dc91761bf1ea_2024-01-08T04-00-48Z.zip)

## Environment

 - Longhorn version: master-head (longhorn-manager a601b9b)
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.27.1+k3s1 
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: ubuntu 22.04
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

<!-Please add any other context about the problem here.-->

**Comment by innobead** [comment]
duplicate of https://github.com/longhorn/longhorn/issues/7596. 

Revalidate this when https://github.com/longhorn/longhorn/issues/7596 is fixed.

**Comment by yangchiu** [comment]
Tested on master-head (longhorn-spdk-engine 64886f5).

When I deleted two replicas in step 5:
> 5. Create backup from UI, and during the backup in progress, delete some replicas to make the backup be in Error state:

And then detach the volume to trigger offline rebuilding:

> 6. Detach the volume to trigger offline rebuilding:
> ```
> kubectl delete -f pod.yaml
> ```

I accidentally observed after the first replica rebuilding completed, the second replica rebuilding started but failed, and the volume detached and reattached itself again to trigger offline rebuilding another time, and then the second replica rebuilding completed:
![error-1](https://github.com/longhorn/longhorn/assets/5709208/eac39ced-1d24-4b77-9c02-d04bf9680b12)
![error-2](https://github.com/longhorn/longhorn/assets/5709208/9c59a0d7-532d-4ae3-9d81-0054f7bf9d06)
![error-3](https://github.com/longhorn/longhorn/assets/5709208/622cb199-627c-4c63-847e-b9634d2d2e6a)
![error-4](https://github.com/longhorn/longhorn/assets/5709208/f33ef91b-69cc-446a-98bd-db345d426830)

[supportbundle_ccb17c0e-68c1-40b4-bd3b-90bc122427e5_2024-01-11T07-33-36Z.zip](https://github.com/longhorn/longhorn/files/13898982/supportbundle_ccb17c0e-68c1-40b4-bd3b-90bc122427e5_2024-01-11T07-33-36Z.zip)

@shuo-wu Could you help to see if there's any potential issue here? Thank you!

**Comment by shuo-wu** [comment]
@yangchiu I cannot reproduce now. The recent fixes probably resolve this issue. Would you re-check it?

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager aaeae7e) and v1.6.x-head (longhorn-manager 43919ce). Unable to reproduce the mentioned issues: https://github.com/longhorn/longhorn/issues/7574#issue-2069597701 and https://github.com/longhorn/longhorn/issues/7574#issuecomment-1886527247. Close this for now.
