### ISSUE TITLE
[BUG] Correct the naming of v2 volume snapshot created after backup restoration 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7577]
## Describe the bug

Correct the naming of v2 volume snapshot created after backup restoration.
The wrong naming of snapshots leads to the unexpected snapshot deletion.

## To Reproduce

1. Create a v2 volume
2. Back up the v2 volume
3. Watch the snapshot resources
4. Restore the v2 volume
5. The snapshot with a wrong naming is created and automatically deleted later.

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

<!-Please add any other context about the problem here.-->

**Comment by innobead** [comment]
@derekbit Please update the checklist for QA following testing.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-spdk-engine `64a2ae`) with test [steps](https://github.com/longhorn/longhorn/issues/7577#issuecomment-1880400669)

After restore a v2 volume(restore-vol), a snapshot with correct naming created and kept.
```
k get snapshot -A -w
NAMESPACE         NAME                                   VOLUME                                     CREATIONTIME           READYTOUSE   RESTORESIZE   SIZE       AGE
longhorn-system   c11b099c-18e5-4bd6-9cf8-c0d253defd40   pvc-d57a6bf5-1985-42da-b26b-57f35cd65e9b   2024-01-11T03:12:41Z   true         1073741824    57671680   3m20s
longhorn-system   cff76e73-95b2-4632-bedd-b36ddaac0749   restore-vol                                2024-01-11T03:15:12Z   true         1073741824    65011712   50s
```
