### ISSUE TITLE
[BUG] Deleting instance-manager during restoring a v2 volume, the volume stuck in detaching state

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7581]
## Describe the bug

Restore a v2 volume from backup, during the restoration still in progress, deleting the instance-manager pod of the node which the volume attached to, the volume stuck in detaching state forever.

## To Reproduce

1. Restore a v2 volume from backup
2. During the restoration still in progress, deleting the instance-manager pod of the node which the volume attached to:
(Not sure why the deletion gets stuck too. The pod gets stuck in `Terminating` state.)
```
$ kubectl delete pod instance-manager-ce9d9463707040bdf1c560293b3463dc -n longhorn-system
```
3. The volume stuck in detaching state forever:
![restore](https://github.com/longhorn/longhorn/assets/5709208/8a16701f-716c-4fb1-96dd-a294dc2329e5)

## Support bundle for troubleshooting

[supportbundle_43c90f10-cff2-486a-bf7b-dc91761bf1ea_2024-01-08T06-06-14Z.zip](https://github.com/longhorn/longhorn/files/13856706/supportbundle_43c90f10-cff2-486a-bf7b-dc91761bf1ea_2024-01-08T06-06-14Z.zip)

## Environment

 - Longhorn version: master-head (longhorn-manager a601b9b)
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.27.1+k3s1 
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: ubuntu 22.04
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

<!-Please add any other context about the problem here.-->

**Comment by derekbit** [comment]
The error is triggered by the actual size mismatching error of replica lvols.

```
[longhorn-manager-dqzsx] time="2024-01-08T07:27:01Z" level=warning msg="Instance test-1-r-3fe7d78f is state error, error message: found mismatching lvol actual size 2750414848 with recorded prev lvol actual size 2097152 when validating lvol test-1-r-3fe7d78f-snap-rebuild-6d8f7e1c" func="controller.(*InstanceHandler).syncStatusWithInstanceManager" file="instance_handler.go:206
```

**Comment by derekbit** [comment]
> So the expected should be volume faulted and detached.

Ah, sorry. wrong ticket.

**Comment by derekbit** [comment]
This is issue seems related to NVMe `--ctrl-loss-tmo`. Need an investigation.

**Comment by shuo-wu** [comment]
Quick question, is there a similar issue for backup creation?

**Comment by roger-ryao** [comment]
**Verified on master-head 20240111**

- longhorn master-head https://github.com/longhorn/longhorn/commit/1d755966981aab582afa978c739e04940172cbef
- longhorn-spdk-engine main https://github.com/longhorn/longhorn-spdk-engine/commit/64886f5375d0cbdee4c58ad245255ea7de47492d
- go-spdk-helper main https://github.com/longhorn/go-spdk-helper/commit/3afa7627b1aa9df000c073b5579b92ddb2f093db
- longhorn-instance-manager master-head https://github.com/longhorn/longhorn-instance-manager/commit/2903e519a224b305cda169d096217d18c2eba244
- backupstore master-head https://github.com/longhorn/backupstore/commit/bd231cfb0c7b3b043fe06d64bcc8f90614b2315f


**The test steps**

1. https://github.com/longhorn/longhorn/issues/7581#issuecomment-1884173533

**Result passed**
