### ISSUE TITLE
[BUG] Restore v2 volume stuck in detaching/faulted state if the backup is corrupted

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7583]
## Describe the bug

Create a backup from a v2 volume, and corrupt the backup by randomly deleting a block on the backupstore. Then try to restore a v2 volume from the corrupted backup, the restore volume will get stuck in detaching/faulted state.

Need to confirm if it's the expected behavior.

## Support bundle for troubleshooting

[supportbundle_29556da2-c06d-40b9-9579-8e7f33988e53_2024-01-08T07-40-40Z.zip](https://github.com/longhorn/longhorn/files/13857417/supportbundle_29556da2-c06d-40b9-9579-8e7f33988e53_2024-01-08T07-40-40Z.zip)

## Environment

 - Longhorn version: master-head (longhorn-manager 1a206d9)
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

<!-Please add any other context about the problem here.-->

**Comment by innobead** [comment]
Should have the same handling. If the restore fails, the volume should be faulted and detached like v1.

**Comment by derekbit** [comment]
Expected behavior:

![image](https://github.com/longhorn/longhorn/assets/12527233/204759ee-f2ba-4185-afb2-d0f0942a40ee)

**Comment by derekbit** [comment]
> @derekbit is ☝️ behavior the same as v1?

Yes

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-instance-manager `117db8`)

Create a backup from a v2 volume, and corrupt the backup by randomly deleting a block on the backupstore. Then try to restore a v2 volume from the corrupted backup, the restore volume eventually become faulted detached
![image](https://github.com/longhorn/longhorn/assets/73337386/53d863f2-98cb-4a18-a830-16c9fbd63744)
