### ISSUE TITLE
[BUG] Delete the backup during restoring a v2 volume from the backup, the restore volume will be detached and faulted

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7584]
## Describe the bug

Restore a v2 volume from a backup. When the restoration is still in progress, deleting the corresponding backup, the restore volume will be detached and faulted.

Need to confirm if it's the expected behavior.

## Support bundle for troubleshooting

[supportbundle_29556da2-c06d-40b9-9579-8e7f33988e53_2024-01-08T08-12-47Z.zip](https://github.com/longhorn/longhorn/files/13857652/supportbundle_29556da2-c06d-40b9-9579-8e7f33988e53_2024-01-08T08-12-47Z.zip)

## Environment

 - Longhorn version: master-head (longhorn-manager 1a206d9)
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

<!-Please add any other context about the problem here.-->

**Comment by innobead** [comment]
@yangchiu What's the behavior of v1?

**Comment by roger-ryao** [comment]
> @yangchiu What's the behavior of v1?

Hi @innobead 
    We have two test cases for V1 
1. [test_delete_backup_during_restoring_volume](https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_basic.py#L5256-L5273)
1. [test_backup_lock_deletion_during_restoration](https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_basic.py#L3117-L3136)
    
    From @yangchiu  bug distribution, it looks like the volume behavior should be the same as the result of the `test_backup_lock_deletion_during_restoration` test.
    
```python
def test_delete_backup_during_restoring_volume(set_random_backupstore, client):  # NOQA
    Test delete backup during restoring volume
    Context:
    The volume robustness should be faulted if the backup was deleted during
    restoring the volume.

    1. Given create volume v1 and attach to a node
       And write data 150M to volume v1
    2. When create a backup of volume v1
       And wait for that backup is completed
       And restore a volume v2 from volume v1 backup
       And delete the backup immediately
    3. Then volume v2 "robustness" should be "faulted"
       And "status" of volume restore condition should be "False",
       And "reason" of volume restore condition should be "RestoreFailure"
       
 def test_backup_lock_deletion_during_restoration(set_random_backupstore, client, core_api, volume_name, csi_pv, pvc, pod_make):  # NOQA
    """
    Test backup locks
    Context:
    To test the locking mechanism that utilizes the backupstore,
    to prevent the following case of concurrent operations.
    - prevent backup deletion during backup restoration

    steps:
    1. Create a volume, then create the corresponding PV, PVC and Pod.
    2. Wait for the pod running and the volume healthy.
    3. Write data to the pod volume and get the md5sum.
    4. Take a backup.
    5. Wait for the backup to be completed.
    6. Start backup restoration for the backup creation.
    7. Wait for restoration to be in progress.
    8. Delete the backup from the backup store.
    9. Wait for the restoration to be completed.
    10. Assert the data from the restored volume with md5sum.
    11. Assert the backup count in the backup store with 0.
 ````

**Comment by derekbit** [comment]
> ```python
> test_delete_backup_during_restoring_volume
> ```

Thank you.
Weird. The two e2e tests for v2 volumes are passed.  Checking it.

**Comment by derekbit** [comment]
> When the restoration is still in progress, deleting the corresponding backup, the restore volume will be detached and faulted.

The steps to reproduce are not clear enough. I've checked the two scenarios

1. Delete backup when restoration progress is not 0.
   Expected behavior:
   1. backup deletion is deferred, and longhorn-manager emits the message
   ```
    [longhorn-manager-dv2d2] time="2024-01-08T15:02:32Z" level=warning msg="Failed to delete remote backup" func="controller.(*BackupController).reconcile" file="backup_controller.go:289" backup=backup-cb8de4a56549423f controller=longhorn-backup error="backup backup-cb8de4a56549423f cannot be deleted due to the ongoing volume abc001 restoration" node=rancher60-worker2
    ```
    2. The restoration should be successful in the end. After the restoration, the backup is deleted as well.

2. Delete backup right after creating a volume restoration. (same as `e2e test_basic.py:: test_delete_backup_during_restoring_volume`)
    Expected behavior: restoration should fail. Volume becomes faulted and detached.

    ![image](https://github.com/longhorn/longhorn/assets/12527233/25aed18a-50c0-4347-8fe5-d97789c29cd8).



@yangchiu Can you help re-verify the two scenarios? Thank you.

**Comment by yangchiu** [comment]
> > When the restoration is still in progress, deleting the corresponding backup, the restore volume will be detached and faulted.
> 
> The steps to reproduce are not clear enough. I've checked the two scenarios
> 
>     1. Delete backup when restoration progress is not 0.
>        Expected behavior:
>        
>        1. backup deletion is deferred, and longhorn-manager emits the message

> @yangchiu Can you help re-verify the two scenarios? Thank you.

What I've tested is scenario 1. Not sure backup deletion is deferred or not, but restore volume becomes faulted and detached

**Comment by derekbit** [comment]
> > > When the restoration is still in progress, deleting the corresponding backup, the restore volume will be detached and faulted.
> > 
> > 
> > The steps to reproduce are not clear enough. I've checked the two scenarios
> > ```
> > 1. Delete backup when restoration progress is not 0.
> >    Expected behavior:
> >    
> >    1. backup deletion is deferred, and longhorn-manager emits the message
> > ```
> 
> > @yangchiu Can you help re-verify the two scenarios? Thank you.
> 
> What I've tested is scenario 1. Not sure backup deletion is deferred or not, but restore volume becomes faulted and detached
 
Some bugs are fixed. Not sure if they are related.  Can you test it again? Thanks.

**Comment by yangchiu** [comment]
> Some bugs are fixed. Not sure if they are related. Can you test it using the latest images again? Thanks.

Verified passed on master-head (longhorn-instance-manager 117db87). Deleting the backup during restoration still in progress, the deletion will be blocked during the restoration, so the restoration will complete first, and then the backup can be deleted.
