### ISSUE TITLE
[BUG] Delete v2 volume snapshot make volume detaching faulted

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#7585]
## Describe the bug

Delete snapshot of v2 volume, after few minutes, the volume become detaching and faluted(2 replicas deleted, 1 failed in my environment)

```
time="2024-01-08T08:02:20Z" level=warning msg="Instance pvc-559d0819-e19b-405a-865c-ab4db90ad2d6-r-94de09d1 is state error, error message: found mismatching lvol actual size 24117248 with recorded prev lvol actual size 13631488 when validating lvol pvc-559d0819-e19b-405a-865c-ab4db90ad2d6-r-94de09d1-snap-5db9d231-0dd7-46a9-b3ac-7951d48151c0" func="controller.(*InstanceHandler).syncStatusWithInstanceManager" file="instance_handler.go:206"
time="2024-01-08T08:02:21Z" level=info msg="Deleting instance pvc-559d0819-e19b-405a-865c-ab4db90ad2d6-r-94de09d1" func="controller.(*InstanceHandler).deleteInstance" file="instance_handler.go:497"
time="2024-01-08T08:02:21Z" level=info msg="Deleting replica instance" func="controller.(*ReplicaController).DeleteInstance" file="replica_controller.go:554" controller=longhorn-replica node=ip-172-31-43-108 nodeID=ip-172-31-43-108 ownerID=ip-172-31-43-108 replica=pvc-559d0819-e19b-405a-865c-ab4db90ad2d6-r-94de09d1
time="2024-01-08T08:02:21Z" level=info msg="Event(v1.ObjectReference{Kind:\"Replica\", Namespace:\"longhorn-system\", Name:\"pvc-559d0819-e19b-405a-865c-ab4db90ad2d6-r-94de09d1\", UID:\"b2f51cd8-4689-436d-aec0-8790fc853527\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"2702\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops pvc-559d0819-e19b-405a-865c-ab4db90ad2d6-r-94de09d1" func="record.(*eventBroadcasterImpl).StartLogging.func1" file="event.go:298"
time="2024-01-08T08:02:21Z" level=info msg="Deleting instance pvc-559d0819-e19b-405a-865c-ab4db90ad2d6-r-94de09d1" func="controller.(*InstanceHandler).deleteInstance" file="instance_handler.go:497"
```

![image](https://github.com/longhorn/longhorn/assets/73337386/5acd4769-9f68-466d-a01f-5566d097d250)

## To Reproduce

1. Deploy longhorn, enable v2-data-engine, add block disks to each node
2. Create workload with v2 volume
3. Write data into mount point, create snapshot (repeat 3 times)
4. Delete 1 snapshot, wait 5 minutes.
5. Volume detaching Faulted

## Expected behavior

Volume healthy or block the snapshot deletion

## Support bundle for troubleshooting

[supportbundle_614d5c73-01a2-4f3b-b098-72a17c8a0d8a_2024-01-08T08-14-07Z.zip](https://github.com/longhorn/longhorn/files/13857651/supportbundle_614d5c73-01a2-4f3b-b098-72a17c8a0d8a_2024-01-08T08-14-07Z.zip)

## Environment

 - Longhorn version: v1.6.0-dev (longhorn-manager `1a206d`)
 - Impacted volume (PV):  pvc-559d0819-e19b-405a-865c-ab4db90ad2d6
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.28.2+k3s1
 - Number of Longhorn volumes in the cluster: 1
 
## Additional context

https://github.com/longhorn/longhorn/issues/5947

**Comment by derekbit** [comment]
The root cause is same as https://github.com/longhorn/longhorn/issues/7575.
