### ISSUE TITLE
[TASK] Update CLIAPIVersion in longhorn-manager

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#7588]
## What's the task? Please describe

https://github.com/longhorn/longhorn-engine/pull/983 bumped `CLIAPIVersion` for longhorn-engine: 9 -> 10.

When I tried to upgrade longhorn-manager from `master-head` to `some-custom-version`, I got the following error:

```
time="2024-01-08T17:17:54Z" level=info msg="Checking if the upgrade path from v1.6.0-dev to v1.6.0-dev is supported" func=util.checkLHUpgradePathSupported file="util.go:232"
time="2024-01-08T17:17:54Z" level=info msg="Checking if the engine upgrade path from map[ei-b907910b:{Version: GitCommit: BuildDate: CLIAPIVersion:10 CLIAPIMinVersion:0 ControllerAPIVersion:5 ControllerAPIMinVersion:0 DataFormatVersion:0 DataFormatMinVersion:0}] is supported" func=util.checkEngineUpgradePathSupported file="util.go:301" newEngineClientAPIMinVersion=8 newEngineClientAPIVersion=9 newEngineControllerAPIMinVersion=4 newEngineControllerAPIVersion=5
time="2024-01-08T17:17:54Z" level=fatal msg="Error starting manager: failed checking Engine upgrade path: incompatible Engine ei-b907910b client API version: downgrading from 10 to 9 is not supported" func=main.main.DaemonCmd.func3 file="daemon.go:87"
```

It is because the vendored version of longhorn-engine in longhorn-manager still uses `CLIAPIVersion = 9`.

https://github.com/longhorn/longhorn-manager/blob/2931e5b7bbc88849f67e9eb9cdab32b3fa531da4/vendor/github.com/longhorn/longhorn-engine/pkg/meta/version.go#L5

I THINK we just need to import the latest version of longhorn-engine in longhorn-manager. Creating this task and assigning it to @FrankYang0529 in case I am missing some context.

**Comment by innobead** [comment]
@FrankYang0529 Please help update the above comment, especially for the test steps for QA, which should be the same reproduction steps by Eric.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240109**

- longhorn master-head https://github.com/longhorn/longhorn/commit/96a0995708b4479bd29a55ee74fd36090dad9962
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/7a56d7103680ebb96e030a89a6e0a57abbbb5715
- longhorn-engine master-head https://github.com/longhorn/longhorn-engine/commit/3848d7ddd7fb563e070235bbbb8c33272b5b5f46


**The test steps**

1. https://github.com/longhorn/longhorn-engine/commit/3848d7ddd7fb563e070235bbbb8c33272b5b5f46

**Result passed**
