### ISSUE TITLE
[BUG] Fix and improve the offline rebuilding after introducing the SPDK snapshot feature

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#7596]
## Describe the bug

If a snapshot in the v2 volume contains multiple children, replica rebuilding won't work correctly

## To Reproduce

1. Create and attach a v2 volume
2. Create snapshots for the volume
3. Revert to a snapshot, then create more snapshots
4. Repeat step3
5. Delete one replica
6. Detach the volume to trigger the offline rebuilding

## Environment

 - Longhorn version: v1.6.0-dev
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

<!-Please add any other context about the problem here.-->

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-spdk-engine `64886f`) 

1. Dynamic provision workload with v2 volume
2. Write data into mount point then create snapshot, repeat several times
3. Scaledown workload to detach v2 volume
4. Attach v2 volume in maintance mode
5. Revert snapshot, then detach the v2 volume
6. Attach v2 volume with workload, data correct.
7. Delete 1 replica, do offline replica rebuilding
8. All replicas ready, data intact

Repeat above steps several times, after snapshot reverted, data match the content when taking snapshot, and offline rebuild all success.

![image](https://github.com/longhorn/longhorn/assets/73337386/20ee5882-8655-4ab5-95a4-c3466eadf011)
