### ISSUE TITLE
[BUG] v2 volume becomes faulted and detached after deleting one replica during full restoration

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7597]
## Describe the bug

v2 volume becomes faulted and detached after deleting one replica during full restoration.

## To Reproduce

1. Create a v2 volume with 3 replicas
2. Create a backup
3. Restore a v2 volume from the backup
4. Delete one replica during restoration.
5. The volume becomes faulted and detached after restoration.

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

<!-Please add any other context about the problem here.-->

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `2ac44e`) with test [stpes](https://github.com/longhorn/longhorn/issues/7597#issuecomment-1882953829)

Delete replica when v2 volume is restoring, the volume will finish restore first and then start offline rebuilding, volume become detached(ready for workload) in the end, the data intact.
