### ISSUE TITLE
[IMPROVEMENT] Reject DR volume creation for v2 volume

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7627]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Reject DR volume creation for v2 volume.
The rejection will be removed after supporting DR volume feature.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240111**

- longhorn master-head https://github.com/longhorn/longhorn/commit/1d755966981aab582afa978c739e04940172cbef
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/eeda02bea1f7529aedc6ad6f8ff3251b07a84405



**The test steps**

1. https://github.com/longhorn/longhorn/issues/7627#issuecomment-1886289982

**Result passed**

1. When updating `volume.spec.standby` to `true`, the request is rejected, and the following error is displayed

    ```
    # volumes.longhorn.io "vol-0" was not valid:
    # * : standby is not supported for data engine v2
    ```
1. When attempting to create a DR V2 volume from a backup using the UI, an error is shown:  `failed to create volume: unable to create volume vol-0-v2: admission webhook "validator.longhorn.io" denied the request: standby is not supported for data engine v2`

![Screenshot_20240111_143049](https://github.com/longhorn/longhorn/assets/104337648/8261cd17-29fb-4033-a2de-6332337a1783)
