### ISSUE TITLE
[IMPROVEMENT] Have a clear message when reverting the parent of a volume-head snapshot for a v2 volume

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#7630]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Create v2 volume in maintance mode, create mutiple snapshots. Try revert the parent of the volume-head snapshot will get below message
```
failed to revert snapshot: proxyServer=10.42.2.15:8501 destination=10.42.2.15:0: failed to revert volume to snapshot 9fd5dd79-ab0f-4527-ae6b-bcf0220d82fe: rpc error: code = Internal desc = failed to create snapshot 9fd5dd79-ab0f-4527-ae6b-bcf0220d82fe: failed to revert SPDK engine pvc-5a2c50cc-8da3-4c5a-b278-f939dd696a81-e-0 snapshot 9fd5dd79-ab0f-4527-ae6b-bcf0220d82fe: rpc error: code = Unknown desc = error sending message, id 17741, method bdev_raid_create, params {pvc-5a2c50cc-8da3-4c5a-b278-f939dd696a81-e-0 1 0 []}: {"code": -22,"message": "Failed to create RAID bdev pvc-5a2c50cc-8da3-4c5a-b278-f939dd696a81-e-0: Invalid argument"}
```

## Describe the solution you'd like

If possible, have a clear message

## Additional context

https://github.com/longhorn/longhorn/issues/7596

**Comment by derekbit** [comment]
cc @shuo-wu

**Comment by derekbit** [comment]
The behavior between v1 and v2 volumes are not consistent.

- v1 volume
   After the snapshot revert operation, the volume head size is 0
![image](https://github.com/longhorn/longhorn/assets/12527233/a24b5a72-46ff-4ce1-94a3-a4cc1039b5d0)

- v2 volume
  The volume head size is unchange after the failure of the snapshot revert
![image](https://github.com/longhorn/longhorn/assets/12527233/eb7112a7-555b-470e-bf02-12c0ae6084e5)

**Comment by innobead** [comment]
> The behavior between v1 and v2 volumes are not consistent.> * v2 volume
>   The volume head size is unchange after the failure of the snapshot revert
>   ![image](https://private-user-images.githubusercontent.com/12527233/295985240-eb7112a7-555b-470e-bf02-12c0ae6084e5.png?

@derekbit did you mean `after the successful snapshot revert`?

**Comment by derekbit** [comment]
> > The behavior between v1 and v2 volumes are not consistent.> * v2 volume
> > The volume head size is unchange after the failure of the snapshot revert
> > ![image](https://private-user-images.githubusercontent.com/12527233/295985240-eb7112a7-555b-470e-bf02-12c0ae6084e5.png?
> 
> @derekbit did you mean `after the successful snapshot revert`?

Update the words in https://github.com/longhorn/longhorn/issues/7630#issuecomment-1887545760

**Comment by chriscchien** [comment]
Hi @derekbit,

V1 and V2 volume snaptshot revert behavior not consistent:

In v1 volume, revert parent of volume-head snapthost
- The snapshot still exist
- No popup message
- Volume-head size become `0`

In v2 volume, revert parent of volume-head snapshost
- The snapshot still exist (observed volume reattach)
- Pop up message
```
failed to revert snapshot: proxyServer=10.42.2.50:8501 destination=10.42.2.50:0: failed to revert volume to snapshot c56b1e9f-1899-4cd4-8c22-e105c47f8953: rpc error: code = Internal desc = failed to create snapshot c56b1e9f-1899-4cd4-8c22-e105c47f8953: failed to revert SPDK engine pvc-eba05475-40db-4cd1-a51a-c24fb70555b1-e-0 snapshot c56b1e9f-1899-4cd4-8c22-e105c47f8953: rpc error: code = Unknown desc = error sending message, id 9974, method bdev_raid_create, params {pvc-eba05475-40db-4cd1-a51a-c24fb70555b1-e-0 1 0 []}: {"code": -22,"message": "Failed to create RAID bdev pvc-eba05475-40db-4cd1-a51a-c24fb70555b1-e-0: Invalid argument"}
```
- volume-head size not change

-- 
In addition, I can see after  v2 volume snapshot revert success, volume-head size become 0
![Screenshot from 2024-01-16 11-20-33](https://github.com/longhorn/longhorn/assets/73337386/b36358bd-a3ff-4d08-9bb1-8bd76dd6c06d)

**Comment by derekbit** [comment]
> failed to revert snapshot: proxyServer=10.42.2.50:8501 destination=10.42.2.50:0: failed to revert volume to snapshot

Ah, sorry. Forgot to update deps.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `d0cbdf`)

Revert parent of volume-head snapthost for a v2 volume, can observe below behavior which is identical to the behavior of v1 volume
- The snapshot still exist
- No popup message
- Volume-head size become 0
