### ISSUE TITLE
[BUG] replica not rebuild in v1.6.0-dev if engine image is v1.4.x

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#7631]
## Describe the bug

With https://github.com/longhorn/longhorn/issues/7539 implemented, we can upgrade longhorn from v1.4.x to v1.6.0-dev directly, but after upgrade complete, delete 1 replica in volume which uses the v1.4.x engine, the volume won't rebuild, scaledown workload, volume won't detach, and become not ready for workload

If upgrade engine image to master-head filst, basic volume operation will work well. Create this ticket for tracking, thank you

## To Reproduce

1. Install Longhorn v1.4.x by helm and create some workload. 
2. Upgrade to v1.6.0-dev with `preUpgradeChecker.jobEnabled=false` and `preUpgradeChecker.upgradeVersionCheck=false` in values.yaml
3. After upgrade complete, delete 1 replica
4. Volume kept degrade, scale down workload, volume won't detach and become not ready for workload

## Expected behavior

Volume act normal

## Support bundle for troubleshooting

[supportbundle_5118b97b-de78-4ecf-91cc-2e70418928ca_2024-01-11T09-52-48Z.zip](https://github.com/longhorn/longhorn/files/13901426/supportbundle_5118b97b-de78-4ecf-91cc-2e70418928ca_2024-01-11T09-52-48Z.zip)

## Environment

 - Longhorn version: v1.6.0-dev
 - Impacted volume (PV): pvc-cd6b28e1-95a2-4ab4-88fb-b8fc1c13be0e
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.28.2+k3s1

**Comment by mantissahz** [comment]
The v1.4.x engine images are incompatible with Longhorn v1.6.x ~ master-head environment.
When trying to create a new replica to rebuild, it will be blocked by the validator.

**Comment by innobead** [comment]
> The v1.4.x engine images are incompatible with Longhorn v1.6.x ~ master-head environments. When trying to create a new replica to rebuild, it will be blocked by the validator.

James, could you point out the code?

**Comment by mantissahz** [comment]
In `replenishReplicas` of the volume controller. https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go#L2170-L2172
Replica validation. https://github.com/longhorn/longhorn-manager/blob/master/webhook/resources/replica/validator.go#L55

It also blocks detaching because it will always try to replenish a new replica before it can do detaching process.

Workaround: 
Modify the replica number to be the number of healthy replicas the volume has now and then detach the volume, better to upgrade the volume engine as well.

**Comment by innobead** [comment]
This is a bug, and we need to fix it.

When creating a replica, we need to verify that its value matches the engine instead of blindly checking if the value should be compatible or not, as it could be from an existing volume, engine. 

cc @c3y1huang

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager **d0cbdf**)

After upgrade from v1.4.x to master-head, below RWO/RWX volume operations worked well
- Replica building (with v1.4.x engine)
- Volume reattach (with v1.4.x engine)
- Replica building (with master engine)
- Volume reattach (with master engine)
- Create v2 volume

And data intact after upgrade.
