### ISSUE TITLE
[FEATURE] RWX volume supports different NFS version (4.2) and mount options

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7638]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Currently, RWX volume is based on NFS v4.1 protocol. Some new features such as sparse files, file pre-allocation, server-side clone and copy and application data block (ADB) are introduced in v4.2.
The feature request aims to support both v4.1 and 4.2 as well as customized mount options.

## Additional context

cc @james-munson

**Comment by james-munson** [comment]
Varying the mount options is already an option, simply by using nfsOptions="vers=4.2,hard,etc..." in the parameters for the volume's storage class.

This seems as simple as changing the defaultOptions to use "vers=4.2" in csi/node_server.go".

Note that there is still the possibility of overriding with 4.1 in the nfsOptions if desired.

Note also that NFS backupstore, if not overridden in the settings, uses a default of nfs4.2 already, with fallback attempts at 4.1 and 4.0 if unsuccessful.  But there is no such fallback path for RWX volume mounts.

**Comment by derekbit** [comment]
I see. Can you help update the RWX doc https://longhorn.io/docs/1.6.0/advanced-resources/rwx-workloads/ for the mount options? Thank you.

**Comment by james-munson** [comment]
Base ticket for the feature change to NFS mounts for RWX volumes is https://github.com/longhorn/longhorn/issues/6655

**Comment by james-munson** [comment]
I created https://github.com/longhorn/longhorn/issues/7716 to cover the docs improvement, so this can be expedited on its own.

**Comment by james-munson** [comment]
This is reasonable to backport.  All current releases use nfs-ganesha that supports v4.2.

**Comment by derekbit** [comment]
@james-munson 
Can you test v4.2 by a different StorageClass as well in tests? Thank you.

https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_rwx.py

**Comment by derekbit** [comment]
> I do not understand what is being asked for here. Guessing that it is to add regression test cases with specific overrides.

If you check https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_rwx.py, you can find it only test NFS v4.1. You can add test v4.2 as well by a StorageClass with different mount options.

**Comment by innobead** [comment]
@james-munson Please do what @derekbit suggested. Need to have e2e tests in 4.2 as well.

**Comment by james-munson** [comment]
In fact, it now tests 4.2 when run on 1.6, master, or any release for which 4.2 is the default.  But I take your point that there should be some tests that test nfsOptions overrides explicitly, for non-default NFS versions.

**Comment by james-munson** [comment]
This issue has been superseded by [#7741] which reverts the default to vers=4.1.  It can be closed when that one is committed.
