### ISSUE TITLE
Empty backup list for some volumes

### ISSUE THREAD

**Issue by courcelm** [longhorn/longhorn#764]
In longhorn v0.6.1,  I can't see backup anymore for some volumes. The issue might be related to volume name.

Not ok:
matomo-mysql-volume

Ok (can see list):
matomo-backup-1
pvc-0cd9592d-54a0-11e9-a1b0-000c298019f4

**Comment by yasker** [comment]
@courcelm This is weird. I don't think it's volume name since the name you provided works fine for me.

Maybe it's related to the backup progress we've introduced in v0.6.0. Now making backups are asynchronized command and you can check the progress in the UI by looking at the related snapshot. Before the backup was completed, the backup won't show up in the backup store.

**Comment by yasker** [comment]
@smallteeths I think it's a UI bug. Can you check?

**Comment by yasker** [comment]
@smallteeths It looks like a UI bug. Backend returns the data correctly. Can you check?

**Comment by courcelm** [comment]
I don't see any error in Chrome console.

**Comment by courcelm** [comment]
I think a receive data from websocket. Not very familiar with this....

**Comment by yasker** [comment]
@courcelm It's probably got something to do with our UI dealing with Rancher proxy...

May due to this last-minute fix: https://github.com/longhorn/longhorn-ui/commit/927b2dc596d79bd22d195d38ab1d534a41826e00

**Comment by courcelm** [comment]
Ok, let me know if there is a workaround. I would appreciate restoring my backup.

**Comment by yasker** [comment]
@courcelm Can you try to upgrade UI deployment to use `longhornio/longhorn-ui:v0.6.1-patch1`? This image should fix the problem.

You can also repull `longhornio/longhorn-ui:v0.6.1` on the nodes, which also included the patch from https://github.com/longhorn/longhorn-ui/pull/200 .

**Comment by courcelm** [comment]
@yasker The patch is working fine. I can see all my backups now. Thank for the quick fix!

Unrelated question: what is the purpose of the new maintenance checkbox when attaching volume?

**Comment by yasker** [comment]
@courcelm I've added a [section](https://github.com/longhorn/longhorn/blob/master/docs/volume.md#maintenance-mode) in documents to explain the usage of `Maintenance mode`.

**Comment by yasker** [comment]
Fixed.
