### ISSUE TITLE
[BUG] Volume with v1.5.x engine not worked well in v1.6.0-rc1

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#7642]
## Describe the bug

Upgrade Longhorn from v1.5.x to v1.6.0-rc1, volume with v1.5.x engine have below symptom
- Replica rebuilding fail.  Can see repliuca created, but not in running state(loop in no state and state failed), volume kept degraded
- Reattach volume fail, volume kept in attaching -> Faulted loop. (all replica loop in no state and state failed)

longhorn-manager
```
time="2024-01-12T03:56:41Z" level=warning msg="pvc-cdcb2543-4f88-4f94-a53a-57192ad9e38d-r-3e260f9c: time=\"2024-01-12T03:45:05Z\" level=fatal msg=\"Error running start replica command\" func=cmd.ReplicaCmd.func1 file=\"replica.go:79\" error=\"directory name is required\"" func="controller.(*InstanceHandler).printInstanceLogs" file="instance_handler.go:467"
```

instance-manager
```
[longhorn-instance-manager] time="2024-01-12T03:48:51Z" level=error msg="Failed to receive log" func=instance.V1DataEngineInstanceOps.InstanceLog file="instance.go:412" error="rpc error: code = NotFound desc = cannot find process pvc-cdcb2543-4f88-4f94-a53a-57192ad9e38d-r-3e260f9c"
[longhorn-instance-manager] time="2024-01-12T03:48:51Z" level=info msg="Deleting instance" func="instance.(*Server).InstanceDelete" file="instance.go:172" cleanupRequired=true dataEngine=DATA_ENGINE_V1 diskUuid=f2171577-e829-4df6-ae19-51e66c3921da name=pvc-43743aa6-81ad-413c-a6ac-9b131e94bb17-r-d2af00a4 type=replica
[longhorn-instance-manager] time="2024-01-12T03:48:51Z" level=info msg="Process Manager: prepare to delete process pvc-43743aa6-81ad-413c-a6ac-9b131e94bb17-r-d2af00a4" func="process.(*Manager).ProcessDelete" file="process_manager.go:272"
[longhorn-instance-manager] time="2024-01-12T03:48:51Z" level=info msg="Deleting instance" func="instance.(*Server).InstanceDelete" file="instance.go:172" cleanupRequired=true dataEngine=DATA_ENGINE_V1 diskUuid=f2171577-e829-4df6-ae19-51e66c3921da name=pvc-cdcb2543-4f88-4f94-a53a-57192ad9e38d-r-3e260f9c type=replica
[longhorn-instance-manager] time="2024-01-12T03:48:51Z" level=info msg="Process Manager: prepare to delete process pvc-cdcb2543-4f88-4f94-a53a-57192ad9e38d-r-3e260f9c" func="process.(*Manager).ProcessDelete" file="process_manager.go:272"
[longhorn-instance-manager] time="2024-01-12T03:48:51Z" level=info msg="Getting instance log" func="instance.(*Server).InstanceLog" file="instance.go:387" dataEngine=DATA_ENGINE_V1 name=pvc-cdcb2543-4f88-4f94-a53a-57192ad9e38d-r-3e260f9c type=replica
```

## To Reproduce

1. Deploy longhorn v1.5.x
2. Create 2 volume with workloads, wite data into mount point
3. Upgrade to v1.6.0-rc1, don't perform engine upgrade
4. Delete 1 replica in workload1, the replica try rebuilding, but not success
5. Scale workload2, make volume detach/attach, the volume kept in loop attaching -> faulted

## Expected behavior

Volume with previous version of engine worked well

## Support bundle for troubleshooting

[supportbundle_83315abd-989a-4bba-9808-5fe7618db846_2024-01-12T03-42-50Z.zip](https://github.com/longhorn/longhorn/files/13911270/supportbundle_83315abd-989a-4bba-9808-5fe7618db846_2024-01-12T03-42-50Z.zip)

## Environment

 - Longhorn version: v1.6.0-rc1
 - Impacted volume (PV): 
   - pvc-43743aa6-81ad-413c-a6ac-9b131e94bb17, replica rebuild fail
   - pvc-cdcb2543-4f88-4f94-a53a-57192ad9e38d, volume can not reattach
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.28.2+k3s1

## Additional context

N/A

**Comment by derekbit** [comment]
```
2024-01-12T03:42:27.585902863Z time="2024-01-12T03:42:27Z" level=warning msg="pvc-cdcb2543-4f88-4f94-a53a-57192ad9e38d-r-3e260f9c: time=\"2024-01-12T03:37:57Z\" level=fatal msg=\"Error running start replica command\" func=cmd.ReplicaCmd.func1 file=\"replica.go:79\" error=\"directory name is required\"" func="controller.(*InstanceHandler).printInstanceLogs" file="instance_handler.go:467"
```

v1.5.3's engine CLIAPI version is 9, so the version check in v1.6.0 should be `if engineCLIAPIVersion >= 10 {...}`
https://github.com/longhorn/longhorn-manager/blame/master/engineapi/instance_manager.go#L356

cc @PhanLe1010

**Comment by derekbit** [comment]
```
2024-01-12T03:42:27.585902863Z time="2024-01-12T03:42:27Z" level=warning msg="pvc-cdcb2543-4f88-4f94-a53a-57192ad9e38d-r-3e260f9c: time=\"2024-01-12T03:37:57Z\" level=fatal msg=\"Error running start replica command\" func=cmd.ReplicaCmd.func1 file=\"replica.go:79\" error=\"directory name is required\"" func="controller.(*InstanceHandler).printInstanceLogs" file="instance_handler.go:467"
```

v1.5.3's engine CLIAPI version is 9, so the version check in v1.6.0 should be `if engineCLIAPIVersion >= 10 {...}`
https://github.com/longhorn/longhorn-manager/blame/master/engineapi/instance_manager.go#L356

cc @FrankYang0529

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn `a78c2a`)

Upgrade form v1.5.x to master-head, volume with v1.5.x-engine image worked well in below actions:
- Replica rebuilding
- Reattach volume by scale down/up workload
- Data read/write
- Create backup
- Concurrent upgrade engine image to master-head
