### ISSUE TITLE
[BUG][v1.6.0-rc1] Error message in longhorn-uninstall job logs

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7643]
## Describe the bug

When uninstall Longhorn v1.6.0-rc1 by:
```
kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/v1.6.0-rc1/uninstall/uninstall.yaml
```
There is an error message in longhorn-uninstall job logs:
```
E0112 03:41:51.660089       1 reflector.go:147] github.com/longhorn/longhorn-manager/k8s/pkg/client/informers/externalversions/factory.go:117: 
Failed to watch *v1beta2.BackupBackingImage: failed to list *v1beta2.BackupBackingImage: backupbackingimages.longhorn.io is forbidden: 
User "system:serviceaccount:longhorn-system:longhorn-uninstall-service-account" cannot list resource "backupbackingimages" in API group "longhorn.io" at the cluster scope
```

Not sure if it's expected.

## Environment

 - Longhorn version: v1.6.0-rc1
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

Related to manual test case https://longhorn.github.io/longhorn-tests/manual/pre-release/uninstallation/uninstallation-checks/.

**Comment by ChanYiLin** [comment]
Oh I think there is permission missing in the role
https://github.com/longhorn/longhorn/blob/dc1179a91c6f8cf829f9dfdd385b31f4090cb6fe/uninstall/uninstall.yaml#L69C19-L69C19

**Comment by ChanYiLin** [comment]
It won't effect the users
because when uninstalling, we unset the backuptarget first, that will remove all the backupbackingimage CR in the controller.
So the uninstallation would not be blocked

**Comment by yangchiu** [comment]
Verified passed in master-head (longhorn 2503414) and v1.6.x-head (longhorn 2a518b4). No error message about `failed to list *v1beta2.BackupBackingImage` found in uninstallation job logs.

**Comment by IsaackRasmussen** [comment]
I'm getting this error in an upgrade from 1.5.0 til 1.6.0 and Manager does not complete startup.
