### ISSUE TITLE
[TEST] Support latest Linux distributions for 1.6

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#7653]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Verify the following versions using our e2e pipeline and update https://longhorn.io/docs/1.6.0/best-practices/#operating-system. 

- Ubuntu 22.04
- SLES 15 SP5
- SLE Micro 5.5
- RHEL 9.3
- Oracle Linux 9.3
- Rocky Linux 9.3
- Talos Linux 1.6 (1.6.1 is the latest one, tested by @c3y1huang )

## Additional context

cc @longhorn/qa

**Comment by khushboo-rancher** [comment]
Tracking https://github.com/longhorn/longhorn/issues/7647 if we need to update the doc.

**Comment by innobead** [comment]
@chriscchien confirmed that 9.3 is OK, but 9.2 is missing on the AWS distro marketplace. Let's just update our pipeline to use 9.3 instead. Chris, please help with this. 

I am going to close this issue, as we already confirmed all versions have been verified.
