### ISSUE TITLE
[IMPROVEMENT] Flooding error messages `failed to sync setting for.....`

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7654]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Contex
https://github.com/longhorn/longhorn/issues/7649#issuecomment-1889282614

**Comment by innobead** [comment]
Can leverage this new effort introduced by @james-munson , so the error log will not be dumped.

[/types/types.go#L728-L731](https://github.com/longhorn/longhorn-manager/blob/98189bfad382f206c0a6ba13e1dbde6283707795/types/types.go#L728-L731)
```go
func ErrorIsInvalidState(err error) bool {
	var dummy *ErrorInvalidState
	return errors.As(err, &dummy)
}
```
[/controller/utils.go#L63-L74](https://github.com/longhorn/longhorn-manager/blob/98189bfad382f206c0a6ba13e1dbde6283707795/controller/utils.go#L63-L74)
```go
func handleReconcileErrorLogging(logger logrus.FieldLogger, err error, mesg string) {
	if types.ErrorIsInvalidState(err) {
		logger.WithError(err).Trace(mesg)
		return
	}

	if apierrors.IsConflict(err) {
		logger.WithError(err).Warn(mesg)
	} else {
		logger.WithError(err).Error(mesg)
	}
}
```

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `a78c2a`)

Upgrade longhorn from v1.5.x(with workload created) to master-head, after upgrade complete, perfom replica building, volume reattach, did not overve flooding error messages in longhorn-manager and instance-manager pods.
