### ISSUE TITLE
[BUG] Uninstallation job stuck forever if the MutatingWebhookConfigurations or ValidatingWebhookConfigurations already deleted

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#7657]
## Describe the bug

if the MutatingWebhookConfigurations or ValidatingWebhookConfigurations already deleted, Uninstallation job stuck forever with the error: `time="2024-01-12T23:35:46Z" level=warning msg="Failed to uninstall" func="controller.(*UninstallController).handleErr" file="uninstall_controller.go:254" controller=longhorn-uninstall error="validatingwebhookconfigurations.admissionregistration.k8s.io \"longhorn-webhook-validator\" not found"`

## To Reproduce

1. Deploy Longhorn v1.6.0-rc1: `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.6.0-rc1/deploy/longhorn.yaml`
1. Delete the MutatingWebhookConfigurations or ValidatingWebhookConfigurations: `kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io longhorn-webhook-validator`
1. Enable deletion confirmation flag `kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs deleting-confirmation-flag` and uninstall Longhorn `kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/v1.6.0-rc1/uninstall/uninstall.yaml`
1. Unintallation stuck forever and user cannot uninstall Longhorn cleanly:
    ```
    time="2024-01-12T23:45:52Z" level=warning msg="Failed to uninstall" func="controller.(*UninstallController).handleErr" file="uninstall_controller.go:253" controller=longhorn-uninstall error="validatingwebhookconfigurations.admissionregistration.k8s.io \"longhorn-webhook-validator\" not found"
    ```

## Expected behavior

Uninstallation job does not stuck.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240115**

- longhorn master-head https://github.com/longhorn/longhorn/commit/2503414115ce422ee4d0f8fe17e8bc5939770873
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/a78c2a41defc1f0c093062b597c94ae17213f750

**Verified on v1.6.x-head 20240115**

- longhorn v1.6.x-head https://github.com/longhorn/longhorn/commit/2a518b4d6ed334e941543715bb7a876f9bc1a336
- longhorn-manager v1.6.x-head https://github.com/longhorn/longhorn-manager/commit/7bcef10ef02e5200cc80e5631908383bda3c807e


**The test steps**

1. https://github.com/longhorn/longhorn/issues/7657#issue-2079892564

**Result passed**
