### ISSUE TITLE
[BUG] File system freeze impossible

### ISSUE THREAD

**Issue by max06** [longhorn/longhorn#7669]
## Describe the bug

Since installing longhorn on a single node k3s in a ubuntu 22.04 hyper-v virtual machine, I can no longer create machine snapshots.

## To Reproduce

- Have a hyper-v enabled machine (windows server, windows 10/11 pro or higher)
- Create a virtual machine
- Install Ubuntu 22.04
- Install azure-kernel (`sudo apt update && sudo apt install linux-azure nfs-common`) and reboot
- (Create and delete snapshot in hyper-v manager to see it working)
- Install k3s (`curl -sfL https://get.k3s.io | sh -`)
- Install longhorn
- (It's probably helpful to have a deployment with a pv/pvc)
- Create snapshot and see error message

## Expected behavior

- Snapshot triggers file system freeze using hyper-v kernel communication channels
- Snapshot is created successfully

## Support bundle for troubleshooting

... uhm... I think I need advice. What UI?

## Environment

 - Longhorn version: v1.5.1
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.28.4+k3s2
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 1
 - Node config
   - OS type and version: Ubuntu 22.04
   - Kernel version: 6.2.0-1014-azure
   - CPU per node: 8
   - Memory per node: 16GB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Hyper-V
 - Number of Longhorn volumes in the cluster: 4

## Additional context

`/var/log/syslog` says:

```text
Jan 13 18:54:36 docker1 Hyper-V VSS: VSS: op=CHECK HOT BACKUP
Jan 13 18:54:36 docker1 kernel: [8744699.899210] VFS:Filesystem freeze failed
Jan 13 18:54:36 docker1 Hyper-V VSS: FREEZE of /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/c975b852d71be89749b5433946a5956e799e8eeb795f1f22c51908c65d44a506/globalmount failed; error:5 Input/output error
Jan 13 18:54:36 docker1 Hyper-V VSS: VSS: op=FREEZE: failed
Jan 13 18:54:36 docker1 Hyper-V VSS: op=5 failed!
Jan 13 18:54:36 docker1 Hyper-V VSS: report it with these files:
Jan 13 18:54:36 docker1 Hyper-V VSS: /etc/fstab and /proc/mounts
```

I am familiar with linux, k8s/longhorn is... new territory. I can live share my environment for debugging if necessary - drop me a gpg encrypted link in that case.

**Comment by shuo-wu** [comment]
Hi, to investigate the cause, would you help clarify the below issues?
1. Which snapshot do you mean? Longhorn volume snapshot or VM snapshot? Or other kinds of snapshot like ETCD/cluster snapshot
2. Notice that you are using `azure-kernel` Are the Windows servers Azure machines? Or they are in the personal lab?

**Comment by max06** [comment]
Hello @shuo-wu!

1. It's about vm snapshots, for backup. 
2. It's running in my personal lab, on a hyper-v host. Since azure is built on the same tech, that kernel enables the communication with the hypervisor.

**Comment by c3y1huang** [comment]
> 1. It's about vm snapshots, for backup.
> 2. It's running in my personal lab, on a hyper-v host. Since azure is built on the same tech, that kernel enables the communication with the hypervisor.

Unfortunately, we don't have too much experience with hyper-V instances. 

However this path `/var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/c975b852d71be89749b5433946a5956e799e8eeb795f1f22c51908c65d44a506/globalmount` looks a bit strange to me. Have you created any Longhorn volumes? Could you try [accessing the UI](https://longhorn.io/docs/1.5.3/deploy/accessing-the-ui/) and provide the [support-bundle](https://longhorn.io/docs/1.5.3/troubleshoot/support-bundle/)? The support-bundle might be able to provide some insights.
