### ISSUE TITLE
[TASK] Explore the correlation between the quantity of v2 volumes and the utilization of memory

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7674]
## What's the task? Please describe

Explore the correlation between the quantity of v2 volumes and the utilization of memory. The goal aims to help users optimize the environment for v2 volumes configuration.

**Comment by innobead** [comment]
Let's have an initial study good enough, but it will not mean the exact correlation in between.

**Comment by derekbit** [comment]
In favor of https://github.com/longhorn/longhorn/issues/5777.
