### ISSUE TITLE
[BUG] Update settings GuaranteedInstanceManagerCPU and V2DataEngineGuaranteedInstanceManagerCPU separately

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7676]
## Describe the bug

`GuaranteedInstanceManagerCPU` is for v1 volumes, and `V2DataEngineGuaranteedInstanceManagerCPU` is for v2 volumes.

We should check v1 and v2 volumes detachment separately.

https://github.com/longhorn/longhorn-manager/blob/master/controller/setting_controller.go#L282

## To Reproduce

1. Create one v1 volume
2. Update V2DataEngineGuaranteedInstanceManagerCPU
3. The setting update is hindered 

or 

1. Create one v2 volume
2. Update GuaranteedInstanceManagerCPU
3. The setting update is hindered 

## Environment

 - Longhorn version: 1.6.0 and master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `d0cbdf`)

1. Update `v2-data-engine-guaranteed-instance-manager-cpu` won't make v1 volume instance-manager pod restart
2. When no V2 volume attached
   - all v2 volume instance-manager pod restart and applied the setting
3. When V2 volume attached
   - the setting will apply to v2 volume instance-manager pod until v2 volume detached.
