### ISSUE TITLE
[BUG] Crypt device mapper of RWX volume with `migratable=true` is not cleaned up

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7678]
## Describe the bug

Crypto device mapper of a block device is not cleaned up.

## To Reproduce

1. Create an encrypted RWX volume with `migratable=true` as the steps in https://github.com/longhorn/longhorn/issues/4883#issuecomment-1619514908
2. Delete workload and the volume
3. Check the dm device is deleted on the attached node by `dmsetup info`

## Environment

 - Longhorn version: v1.6.0 and master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
Does this mean the encrypted migratable volume doesn't work correctly in the existing versions?

**Comment by derekbit** [comment]
> Does this mean the encrypted migratable volume doesn't work correctly in the existing versions?

It is a new feature since v1.6.0 and doesn't impact v1.5 or v1.4.

**Comment by innobead** [comment]
Exactly! https://github.com/longhorn/longhorn/issues/4883

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `d0cbdf`) with test [steps](https://github.com/longhorn/longhorn/issues/7678#issuecomment-1891393194)

Before delete RWX volume with migratable=true, on the volume attached node:
```
> dmsetup info
Name:              pvc-3c26a218-aae8-4aed-b524-14e97d627870
State:             ACTIVE
Read Ahead:        256
Tables present:    LIVE
Open count:        2
Event number:      0
Major, minor:      253, 0
Number of targets: 1
UUID: CRYPT-LUKS2-d2799a96eda94339b291513e4c665bb5-pvc-3c26a218-aae8-4aed-b524-14e97d627870

```
After delete the volume, device mapper cleaned up.
```
> dmsetup info
No devices found
```

In addition, test case `test_csi_encrypted_block_volume` worked well on master [pipeline](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/786/testReport/tests/test_csi/test_csi_encrypted_block_volume/)
