### ISSUE TITLE
Delete all backups of one volume sometime fails, left empty volume

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#768]
Error message: 

>error deleting backup volume pvc-d4ec5581-dcb8-11e9-8d8a-f23c91ea81c2: error deleting backup volume: failed to execute: /var/lib/rancher/longhorn/engine-binaries/longhornio-longhorn-engine-v0.6.0/longhorn [backup rm --volume pvc-d4ec5581-dcb8-11e9-8d8a-f23c91ea81c2 s3://longhorn-backupstore@us-west-1/], output failed to remove all the backups for volume pvc-d4ec5581-dcb8-11e9-8d8a-f23c91ea81c2 , stderr, time="2019-09-25T23:01:16Z" level=error msg="{\n\n}" pkg=s3 time="2019-09-25T23:01:16Z" level=error msg="failed to remove all the backups for volume pvc-d4ec5581-dcb8-11e9-8d8a-f23c91ea81c2" , error exit status 1

Driver: S3.

During the error case, all the backups are gone but the backup volume remains.

The empty backup volume cannot be deleted.

The only file remains inside the backupstore directory:

>{"Name":"aa-volume","Size":"21474836480","CreatedTime":"2019-09-25T03:53:03Z","LastBackupName":"backup-7cdccc3ec64a407a","LastBackupAt":"2019-09-25T03:53:03Z","BlockCount":"0"}

**Comment by shuo-wu** [comment]
Cannot reproduce this issue.
But I found that the returned error message doesn't contain the actual error info.

**Comment by yasker** [comment]
[backupstore.tar.gz](https://github.com/longhorn/longhorn/files/3673887/backupstore.tar.gz)

One example of the content of a failed deletion.

**Comment by yasker** [comment]
More details after exposing the error information
```
error deleting backup volume pvc-d4ec5581-dcb8-11e9-8d8a-f23c91ea81c2: error deleting backup volume: failed to execute: /var/lib/rancher/longhorn/engine-binaries/yasker-longhorn-engine-4c0954f/longhorn [backup rm --volume pvc-d4ec5581-dcb8-11e9-8d8a-f23c91ea81c2 s3://longhorn-backupstore@us-west-1/], output failed to remove all the backups for volume pvc-d4ec5581-dcb8-11e9-8d8a-f23c91ea81c2: AWS Error: MalformedXML The XML you provided was not well-formed or did not validate against our published schema <nil> 400 , stderr, time="2019-10-03T17:26:05Z" level=error msg="{\n\n}" pkg=s3 time="2019-10-03T17:26:05Z" level=error msg="failed to remove all the backups for volume pvc-d4ec5581-dcb8-11e9-8d8a-f23c91ea81c2: AWS Error: MalformedXML The XML you provided was not well-formed or did not validate against our published schema <nil>\n400 \n" , error exit status 1
```

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
1. Launch an online s3 instance and set it as Longhorn backup target
2. Create a backup volume
3. Manually delete the backup directory of the backup volume in s3 instance. e.g. /storage/backupbucket/backupstore/backupstore/volumes/3d/32/longhorn-testvol-00oae2/backups/
4. before fix: Deleting the backup volume on UI page will fail with error message reported in the issue
   after fix: Deleting the backup volume will succeed
