### ISSUE TITLE
[BUG] Incompatible engine image kept in "deploying" state on master-head

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#7683]
## Describe the bug

From test case [test_engine_image_incompatible](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/785/testReport/junit/tests/test_engine_upgrade/test_engine_image_incompatible/)

Deploy incompatible engine image then the state kept in state deploying. In v1.5.3, the state will be `incompatible`
```
k get engineimage -A
NAMESPACE         NAME          STATE       IMAGE                                               REFCOUNT   BUILDDATE   AGE
longhorn-system   ei-b907910b   deployed    longhornio/longhorn-engine:master-head              0          4d23h       6m41s
longhorn-system   ei-d66d84cb   deploying   longhornio/longhorn-test:version-test.2-2.5-3.1-1   0          5y219d      8m3s
```

master
![image](https://github.com/longhorn/longhorn/assets/73337386/3841aaf1-1f28-49a9-95c8-957f4c08a090)

v1.5.3
![Screenshot from 2024-01-15 17-36-55](https://github.com/longhorn/longhorn/assets/73337386/631cd01b-0806-46d8-ab07-8313496e9520)

## To Reproduce

1. Deploy Longhorn master-head
2. Deploy engine image `longhornio/longhorn-test:version-test.2-2.5-3.1-1`
3. State kept in deploying
## Expected behavior

In state incompatible or update test case

## Support bundle for troubleshooting

N/A

## Environment

 - Longhorn version:  master-head

## Additional context

N/A

**Comment by innobead** [comment]
cc @mantissahz

**Comment by mantissahz** [comment]
https://github.com/longhorn/longhorn-ui/blob/master/src/routes/engineimage/detail/EngineImageInfo.js#L29-L30
Here we need to check if `selectedEngineImage.incompatible` is true or not because we deprecated the incompatible state.

**Comment by innobead** [comment]
> [longhorn/longhorn-ui@`master`/src/routes/engineimage/detail/EngineImageInfo.js#L29-L30](https://github.com/longhorn/longhorn-ui/blob/master/src/routes/engineimage/detail/EngineImageInfo.js?rgh-link-date=2024-01-15T10%3A52%3A05Z#L29-L30) Here we need to check if `selectedEngineImage.incompatible` is true or not because we deprecated the incompatible state.

@mantissahz can you make this change directly?

**Comment by innobead** [comment]
Besides, also add a new column for the compatibility for engine image. 

[/k8s/pkg/apis/longhorn/v1beta2/engineimage.go#L70-L79](https://github.com/longhorn/longhorn-manager/blob/98189bfad382f206c0a6ba13e1dbde6283707795/k8s/pkg/apis/longhorn/v1beta2/engineimage.go#L70-L79)
```go
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:resource:shortName=lhei
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
// +kubebuilder:printcolumn:name="State",type=string,JSONPath=`.status.state`,description="State of the engine image"
// +kubebuilder:printcolumn:name="Image",type=string,JSONPath=`.spec.image`,description="The Longhorn engine image"
// +kubebuilder:printcolumn:name="RefCount",type=integer,JSONPath=`.status.refCount`,description="Number of resources using the engine image"
// +kubebuilder:printcolumn:name="BuildDate",type=date,JSONPath=`.status.buildDate`,description="The build date of the engine image"
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

```

**Comment by chriscchien** [comment]
Hi @mantissahz, 

I deployed `longhornio/longhorn-test:version-test.7-7.5-4.1-1`, `longhornio/longhorn-test:version-test.2-2.5-3.1-1` on master-head and v1.6.x-head, UI all display Incompatible for those two images.
But when I get engine images CRD in v1.6.x, it does not display incompatible column (can see they all have field incompatible in yaml format), could you help to confirm if it's OK, thank you.

master-head
```bash
> k get engineimage -A
NAMESPACE         NAME          INCOMPATIBLE   STATE       IMAGE                                                REFCOUNT   BUILDDATE   AGE
longhorn-system   ei-b907910b   false          deployed    longhornio/longhorn-engine:master-head               0          7d16h       7m37s
longhorn-system   ei-4885181d   true           deploying   longhornio/longhorn-test:version-test.7-7.5-4.1-1    0          5y222d      5m5s
longhorn-system   ei-d66d84cb   true           deploying   longhornio/longhorn-test:version-test.2-2.5-3.1-1    0          5y222d      4m45s
longhorn-system   ei-06373e02   false          deployed    longhornio/longhorn-test:version-test.10-8.5-4.1-1   0          5y222d      19s
```

v1.6.x-head
```bash
> k get engineimage -A
NAMESPACE         NAME          STATE       IMAGE                                                REFCOUNT   BUILDDATE   AGE
longhorn-system   ei-80775a90   deployed    longhornio/longhorn-engine:v1.6.x-head               0          6d12h       5m19s
longhorn-system   ei-06373e02   deployed    longhornio/longhorn-test:version-test.10-8.5-4.1-1   0          5y222d      3m
longhorn-system   ei-4885181d   deploying   longhornio/longhorn-test:version-test.7-7.5-4.1-1    0          5y222d      2m35s
longhorn-system   ei-d66d84cb   deploying   longhornio/longhorn-test:version-test.2-2.5-3.1-1    0          5y222d      2m10s
```

v1.6.x-head engine image detail (can see they all have field incompatible)
```bash
k get engineimage -A  -o yaml | grep incompatible
    incompatible: false
    incompatible: false
      message: incompatible
    incompatible: true
      message: incompatible
    incompatible: true
```

**Comment by chriscchien** [comment]
Verified **pass** on longhor master (longhorn-manager `aaeae7`, longhonr-ui `c9ab68`), longhorn v1.6.x(longhorn-manager `43919c`, longhorn-ui `23fa00`)

Deploym incompatible engine image, longhorn-ui will display Incompatible, in crd engineimage.longhorn.io, the incompatible image will get `INCOMPATIBLE=true`, `STATE=deploying`

master-head
```bash
> k get engineimage -A
NAMESPACE         NAME          INCOMPATIBLE   STATE       IMAGE                                                REFCOUNT   BUILDDATE   AGE
longhorn-system   ei-b907910b   false          deployed    longhornio/longhorn-engine:master-head               0          7d16h       7m37s
longhorn-system   ei-4885181d   true           deploying   longhornio/longhorn-test:version-test.7-7.5-4.1-1    0          5y222d      5m5s
longhorn-system   ei-d66d84cb   true           deploying   longhornio/longhorn-test:version-test.2-2.5-3.1-1    0          5y222d      4m45s
longhorn-system   ei-06373e02   false          deployed    longhornio/longhorn-test:version-test.10-8.5-4.1-1   0          5y222d      19s
```

v1.6.x-head
```bash
> k get engineimage -A
NAMESPACE         NAME          INCOMPATIBLE   STATE       IMAGE                                                REFCOUNT   BUILDDATE   AGE
longhorn-system   ei-80775a90   false          deployed    longhornio/longhorn-engine:v1.6.x-head               0          6d13h       2m51s
longhorn-system   ei-4885181d   true           deploying   longhornio/longhorn-test:version-test.7-7.5-4.1-1    0          5y222d      2m2s
longhorn-system   ei-06373e02   false          deployed    longhornio/longhorn-test:version-test.10-8.5-4.1-1   0          5y222d      73s
longhorn-system   ei-d66d84cb   true           deploying   longhornio/longhorn-test:version-test.2-2.5-3.1-1    0          5y222d      14s
```

For this problem mention [here](https://github.com/longhorn/longhorn/issues/7683#issuecomment-1897689632) is setup issue, I should use v1.6.x-head yaml not v1.6.0-rc1 yaml to deploy  all v1.6.x-head images.
