### ISSUE TITLE
[BUG] pod share-manager-pvc-... for share manager not found

### ISSUE THREAD

**Issue by chris922** [longhorn/longhorn#7684]
## Describe the bug

My RWX volume was not able to attach to the nodes. One longhorn-manager pod contains the following info:

```
longhorn-manager time="2024-01-15T09:51:04Z" level=error msg="Dropping Longhorn share manager out of the queue" func=controller.handleReconcileErrorLogging file="utils.go:72" ShareManager=longhorn-system/pvc-50f53342-b484-4ccd-a709-cac0a7bfecbe controller=longhorn-share-manager error="failed to sync longhorn-system/pvc-50f53342-b484-4ccd-a709-cac0a7bfecbe: pod share-manager-pvc-50f53342-b484-4ccd-a709-cac0a7bfecbe for share manager not found" node=...
```

The mentioned pod was indeed not running and also the manifest/resource was not available within the cluster.

I was able to fix this issue by deleting the corresponding ShareManager resource. It was automatically recreated and share-manager pod was started afterwards.
Thus it looks for me that according to the ShareManager resource (manifest see below) the state of the share-manager was still "running", even if the pod was not available. Therefore the longhorn-manager was expecting to find the pod and failed.

Possible solution ideas:
* Ensure that the ShareManager resource status will be updated - if pod is not running the ShareManager resource shouldn't have the "running" state
* Re-create ShareManager resource automatically
* If pod couldn't be found start it

## To Reproduce

Unfortunately I don't know how to reproduce the error. My guess is that it occurred, because I restarted all K8s nodes at the same time.

## Expected behavior

Share Manager is running and volume can be attached.

## Environment

 - Longhorn version: 1.5.3
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm via ArgoCD
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Rancher using K3s
   - Number of control plane nodes in the cluster: 2
   - Number of worker nodes in the cluster: 4
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster: > 20

## Additional context

Share Manager manifest:

```yaml
apiVersion: longhorn.io/v1beta2
kind: ShareManager
metadata:
  creationTimestamp: "2024-01-02T14:19:57Z"
  finalizers:
  - longhorn.io
  generation: 1
  labels:
    longhorn.io/component: share-manager
    longhorn.io/managed-by: longhorn-manager
    longhorn.io/share-manager: pvc-50f53342-b484-4ccd-a709-cac0a7bfecbe
    longhorn.io/share-manager-image: smi-3cf0d119
  name: pvc-50f53342-b484-4ccd-a709-cac0a7bfecbe
  namespace: longhorn-system
  ownerReferences:
  - apiVersion: longhorn.io/v1beta2
    kind: Volume
    name: pvc-50f53342-b484-4ccd-a709-cac0a7bfecbe
    uid: 181fbeb1-09ad-46cd-991d-bf4413ebf85d
  resourceVersion: "35896653"
  uid: 56772162-6f91-4149-92d5-787d999849fe
spec:
  image: longhornio/longhorn-share-manager:v1.5.3
status:
  endpoint: nfs://10.43.53.218/pvc-50f53342-b484-4ccd-a709-cac0a7bfecbe
  ownerID: ...
  state: running
```

**Comment by derekbit** [comment]
Please check the known issue https://github.com/longhorn/longhorn/issues/7183.

**Comment by chris922** [comment]
It could indeed be the same problem, as I don't know how to reproduce the issue I had I can't verify if the fix there will fix the issue I had as well

**Comment by mdsina** [comment]
I faced same issue on longhorn 1.7.2.
In my case I updated my k8s cluster. Due network issues etcd on two cp nodes stays in semi-faulted state, that causes some errors. I restarted that nodes and all looks fine except share manager for rwx volumes never coming back.
Also after failure of etcd, that rwx volumes becoming fault and shows that all replicas being stopped. I salvage that replicas, they are turning back and replicated to all desired nodes, but that's all.
Currently I have only two pvc with rwx access mode.
```
❯ kubectl -n longhorn-system get lhsm
NAME                                       STATE     NODE          AGE
pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb   stopped   talos-cp-01   52d
pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b   stopped   talos-cp-02   41d
```

I've tried workaround from https://github.com/longhorn/longhorn/issues/7183#issuecomment-1823715359 but no luck.
```
> kubectl -n longhorn-system patch lhsm pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb --type=merge --subresource status --patch 'status: {state: error}'
sharemanager.longhorn.io/pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb patched

> kubectl -n longhorn-system patch lhsm pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b --type=merge --subresource status --patch 'status: {state: error}'
sharemanager.longhorn.io/pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b patched
```

```
Volume pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b requested remount at 2024-11-16T14:08:37Z
Volume pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb requested remount at 2024-11-16T14:08:07Z
```

nothing happens.
support-bundle: https://drive.google.com/file/d/1a89cVUfjQNwqek_dLgdBkSXT_vZoNSOQ/view?usp=sharing

**Comment by derekbit** [comment]
> I faced same issue on longhorn 1.7.2. In my case I updated my k8s cluster. Due network issues etcd on two cp nodes stays in semi-faulted state, that causes some errors. I restarted that nodes and all looks fine except share manager for rwx volumes never coming back. Also after failure of etcd, rwx volumes becoming fault and shows that all replicas being stopped. I salvage that replicas, they are turning back and replicated to all desired nodes, but that's all. Currently I have only two pvc with rwx access mode.
> 
> ```
> ❯ kubectl -n longhorn-system get lhsm
> NAME                                       STATE     NODE          AGE
> pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb   stopped   talos-cp-01   52d
> pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b   stopped   talos-cp-02   41d
> ```
> 
> I've tried workaround from [#7183 (comment)](https://github.com/longhorn/longhorn/issues/7183#issuecomment-1823715359) but no luck.
> 
> ```
> > kubectl -n longhorn-system patch lhsm pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb --type=merge --subresource status --patch 'status: {state: error}'
> sharemanager.longhorn.io/pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb patched
> 
> > kubectl -n longhorn-system patch lhsm pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b --type=merge --subresource status --patch 'status: {state: error}'
> sharemanager.longhorn.io/pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b patched
> ```
> 
> ```
> Volume pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b requested remount at 2024-11-16T14:08:37Z
> Volume pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb requested remount at 2024-11-16T14:08:07Z
> ```
> 
> nothing happens. support-bundle: [drive.google.com/file/d/1a89cVUfjQNwqek_dLgdBkSXT_vZoNSOQ/view?usp=sharing](https://drive.google.com/file/d/1a89cVUfjQNwqek_dLgdBkSXT_vZoNSOQ/view?usp=sharing)

@james-munson Can you help check the support bundle? Thanks.

**Comment by derekbit** [comment]
> I faced same issue on longhorn 1.7.2. In my case I updated my k8s cluster. Due network issues etcd on two cp nodes stays in semi-faulted state, that causes some errors. I restarted that nodes and all looks fine except share manager for rwx volumes never coming back. Also after failure of etcd, rwx volumes becoming fault and shows that all replicas being stopped. I salvage that replicas, they are turning back and replicated to all desired nodes, but that's all. Currently I have only two pvc with rwx access mode.
> 
> ```
> ❯ kubectl -n longhorn-system get lhsm
> NAME                                       STATE     NODE          AGE
> pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb   stopped   talos-cp-01   52d
> pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b   stopped   talos-cp-02   41d
> ```
> 
> I've tried workaround from [#7183 (comment)](https://github.com/longhorn/longhorn/issues/7183#issuecomment-1823715359) but no luck.
> 
> ```
> > kubectl -n longhorn-system patch lhsm pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb --type=merge --subresource status --patch 'status: {state: error}'
> sharemanager.longhorn.io/pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb patched
> 
> > kubectl -n longhorn-system patch lhsm pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b --type=merge --subresource status --patch 'status: {state: error}'
> sharemanager.longhorn.io/pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b patched
> ```
> 
> ```
> Volume pvc-e98c5f11-c9cf-4e5e-9e9c-def666d2896b requested remount at 2024-11-16T14:08:37Z
> Volume pvc-2fffbc6e-5a02-4930-8322-2e2d1e27f8bb requested remount at 2024-11-16T14:08:07Z
> ```
> 
> nothing happens. support-bundle: [drive.google.com/file/d/1a89cVUfjQNwqek_dLgdBkSXT_vZoNSOQ/view?usp=sharing](https://drive.google.com/file/d/1a89cVUfjQNwqek_dLgdBkSXT_vZoNSOQ/view?usp=sharing)

@mdsina It might be not the same issue as the original prob. Could you create a new ticket for your issue?

**Comment by mdsina** [comment]
@derekbit Ok, thanks. Created https://github.com/longhorn/longhorn/issues/9828
