### ISSUE TITLE
[QUESTION] I lost all my data ! What can we learn from my case ?

### ISSUE THREAD

**Issue by Asteb612** [longhorn/longhorn#7692]
## Question

I'm creating this issue to explain what led me to the loss of data that I suffered.
In the following events you will see that I made some mistakes due to fatigue and lack of knowledge.
I couldn't provide a log of this incident because all the data was lost.

On Saturday I started an upgrade of longhorn from version 1.4.3 to version 1.5.3 as this was marked as stable.
The helm update was successful and I restarted my services. I notice that some volumes no longer attach.
I look and it seems that this only applies to shared volumes. The error seems to come from this [issue](https://github.com/longhorn/longhorn/issues/4689).
After reading it does not seem to come from the [dns](https://longhorn.io/kb/troubleshooting-dns-resolution-failed/) I correct that.
The next problem is that the disks are unschedulable. I look for a solution but can't find one, so I tell myself that this version isn't so stable and decide to go back to version 1.4.3.

To downgrade I start by trying helm, which doesn't work. I think I'll just delete the helm deployment.
This leads me to an unstable state because deleting the namespace is blocked. I remember the problem with the finalizer blocking namespace deletion.
So I delete the finalizer and delete the namespace. Here I change my mind and install version 1.5.2 which doesn't install correctly and all the pods are in error.
So I delete all the namespaces. I go back to 1.4.3 but I can't install it. I therefore cleaned up all the crd and associated objects.

Installing 1.4.3 works but there are only a few backups available. I stress and go to look at the s3 and almost all the backups have disappeared. I look at the remaining backups and they are the most important for my postgresql. I mainly have personal projects on this server. I restore them but the pods fail. I tell myself that a reboot should solve the problem. After this reboot no more backups.

I go to the disks to copy the remaining pvc and try to boot them via [this method](https://longhorn.io/docs/1.5.3/advanced-resources/data-recovery/export-from-replica/).
But impossible to mount the volume I meet the message `missing codepage or helper program or other error` according to my research the volume is corrupted.

Well my data is irrecoverable, I made myself a reason, I know that in this process I committed errors. I think my mistakes can help improve longhorn.

First of all I don't understand why the backup data on the s3 was deleted. I have a guess that uninstalling longhorn deletes the backups from k8s and reinstalling deletes them from s3.
Do you have any idea why? Because all my wild uninstallations or not were based on the principle that the backup on the s3 allowed me to restore everything.

My second question is how do you set up your backups? Because even with a versioning of the bucket, which I didn't have, I'm not sure that would have prevented this.
To avoid this happening again I am open to any suggestions.

## Environment

 - Longhorn version: 1.4.3 & 1.5.1 & 1.5.3
 - Kubernetes version: 1.23.7
 - Node config
   - OS type and: debian 11
   - Kernel version
   - CPU per node: 12000
   - Memory per node: 14500
   - Disk type: SSD + HDD
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal (Intel NUC)

**Comment by shuo-wu** [comment]
We are sorry to hear that all of your data is lost... Here are some things that may help:
1. Longhorn does not support downgrade. If you encounter any issues during upgrade, it's better to create a ticket here. Since there is no error log, I cannot investigate the cause.
2. Cleaning up all the crd and associated objects is a dangerous operation, which leads to further backup disappearing. When the backup target is set and valid, deleting backup objects means removing the corresponding data from the backup bucket. 
3. You can try to recover the data from orphans even if Longhorn system is corrupted. You can try to enter into the directory recorded in the orphan then [export the volume from the replica directory](https://longhorn.io/docs/1.5.3/advanced-resources/data-recovery/export-from-replica/). But due to the aggressive object removal, I am afraid that there is no orphan in your system.

**Comment by shuo-wu** [comment]
Longhorn supports system backup which stores all resources into the backup target. You can check [this](https://longhorn.io/docs/1.5.3/advanced-resources/system-backup-restore/) for details. 

> I think it is necessary to warn of this possibility in the documentation concerning the uninstallation of longhorn.

To be honest, I am not sure if it would work. If users will check the doc before starting uninstalling, they should see the instructions and clean up Longhorn correctly. Otherwise, some bad things already happen when they wrongly uninstall Longhorn by themselves and try to check the doc for help. 
Anyway, we can update the doc first. cc @innobead

**Comment by derekbit** [comment]
> Longhorn supports system backup which stores all resources into the backup target. You can check [this](https://longhorn.io/docs/1.5.3/advanced-resources/system-backup-restore/) for details.
> 
> > I think it is necessary to warn of this possibility in the documentation concerning the uninstallation of longhorn.
> 
> To be honest, I am not sure if it would work. If users will check the doc before starting uninstalling, they should see the instructions and clean up Longhorn correctly. Otherwise, some bad things already happen when they wrongly uninstall Longhorn by themselves and try to check the doc for help. Anyway, we can update the doc first. cc @innobead

I think the description in [the uninstallation doc](https://longhorn.io/docs/1.6.0/deploy/uninstall/) is clear.
Anything we can improve?

**Comment by shuo-wu** [comment]
Mention that wrongly delete CRD or CR may lead to unexpected data loss

**Comment by Asteb612** [comment]
I think on the oldest version of longhorn that using velero to backup the config. It did mention how to detach the backup from longhorn and protect backup from deletion. If this action is still possible this can be an improvement.

Also it's my mistake to not have see the warning about the data loss. But i think it can be also an improvement to make it more visible maybe in red.

Another part of my question is about how to perform full backup that can be stored on any device. Currently i only have see the disaster recovery volume solution. But if i'm not wrong it only work if you have multiple cluster. In my case it's a small home server with only 3 small nodes.

**Comment by shuo-wu** [comment]
> I think on the oldest version of longhorn that using velero to backup the config. It did mention how to detach the backup from longhorn and protect backup from deletion. If this action is still possible this can be an improvement.

The velero solution is too complicated hence we implement the built-in system backup feature. 
If you just want to clean up the backup CRs without affecting the actual backup data, you can directly remove the backup target.

> Another part of my question is about how to perform full backup that can be stored on any device. Currently i only have see the disaster recovery volume solution.

Longhorn backups can be restored to any Longhorn system no matter if it's a disaster recovery cluster or how many clusters the backups serve for.

**Comment by Asteb612** [comment]
> The velero solution is too complicated hence we implement the built-in system backup feature. If you just want to clean up the backup CRs without affecting the actual backup data, you can directly remove the backup target.
Ok so this can be a useful advice to remove the backup target before uninstalling. With this it's possible to downgrade by uninstalling.

> Longhorn backups can be restored to any Longhorn system no matter if it's a disaster recovery cluster or how many clusters the backups serve for.
If i'm understood correctly the disaster recovery backup can be stored on s3. And the disaster recovery backup is a full backup ? Why i'm trying to do that is to do a full backup on a separate folder that can be copied to another place.
How longhorn user usually backup the backup target ?

Thank you for the time you passing to respond to my questions.
