### ISSUE TITLE
[BUG] spdk_tgt somehow ran into an internal error.

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7703]
## Describe the bug

When working on https://github.com/longhorn/longhorn/issues/7697 and https://github.com/longhorn/longhorn/issues/7693, spdk_tgt somehow ran into an internal error.

```
instance-manager-c1ee3220ded762e290e2435e3b570b07:/spdk # ./scripts/rpc.py nvmf_subsystem_get_listeners nqn.2023-01.io.longhorn.spdk:pvc-af249ad8-7e20-415d-807a-47008ab581c1-e-0
request:
{
  "nqn": "nqn.2023-01.io.longhorn.spdk:pvc-af249ad8-7e20-415d-807a-47008ab581c1-e-0",
  "method": "nvmf_subsystem_get_listeners",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32603,
  "message": "Internal error"
}
```

## To Reproduce

Steps in https://github.com/longhorn/longhorn/issues/7697#issue-2083424454 and use kernel 5.19.0-50-generic.

Not sure if it is kernel related.

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

[supportbundle_2663dcc2-948e-4a52-b9a3-3d9b3491c592_2024-01-16T15-06-13Z.zip](https://github.com/longhorn/longhorn/files/13952041/supportbundle_2663dcc2-948e-4a52-b9a3-3d9b3491c592_2024-01-16T15-06-13Z.zip)

**Comment by derekbit** [comment]
cc @DamiaSan

**Comment by DamiaSan** [comment]
Do you have SPDK logs?

**Comment by derekbit** [comment]
Sorry. I don't keep the environment and log. But the spdk_tgt only constant emits

```
[2024-01-16 06:45:25.210261] ctrlr.c: 178:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2014-08.org.nvmexpress:uuid:00000000-0000-0000-0000-ac1f6be298ca from subsystem nqn..............
```

**Comment by innobead** [comment]
Just a side request: we need to have SPDK tgt log in the support bundle or even be able to monitor at runtime.

**Comment by derekbit** [comment]
When running into the issue, problematic volumes are unable to be deleted

```
╰─$ kl get volumes
NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE              AGE
pvc-2c181828-451f-4e5a-8423-57b2bb51eb1c   v2            deleting   faulted                  4294967296   c3-small-x86-01   17m
pvc-32c2a5f3-4ffd-457c-8633-02397aabae03   v2            deleting   faulted                  4294967296   c3-small-x86-01   17m
pvc-49aaa930-dbcb-49fb-8804-c27ada3a6e08   v2            deleting   faulted                  4294967296   c3-small-x86-01   17m
pvc-c61eb69e-8dc1-4852-9deb-fce50b915007   v2            deleting   faulted                  4294967296   c3-small-x86-01   17m
pvc-fead3001-9a23-40fd-be1f-c899fe54806b   v2            deleting   faulted                  4294967296   c3-small-x86-01   17m
```

I also added support bundle in https://github.com/longhorn/longhorn/issues/7703#issue-2083781792

cc @DamiaSan

**Comment by shuo-wu** [comment]
Encounter the error once when testing [this issue](https://github.com/longhorn/longhorn/issues/7573).

```
[longhorn-instance-manager] time="2024-01-17T09:42:01Z" level=error msg="Failed to delete replica with cleanupRequired flag false" func="spdk.(*Replica).Delete.func1" file="replica.go:682" error="error sending message, id 7606, method nvmf_subsystem_remove_listener, params {nqn.2023-01.io.longhorn.spdk:vol-r-1c41559a {TCP IPv4 10.42.1.237 20001} }: {\"code\": -32603,\"message\": \"subsystem busy, retry later.\n\"}" lvsName=disk-2 lvsUUID=14821ea5-b73e-45de-9574-3d4628637986 replicaName=vol-r-1c41559a
```

**Comment by DamiaSan** [comment]
> In addition, `nvmf_subsystem_remove_listener` showed `subsystem busy, retry later.` error.

Something similar happens here: https://github.com/spdk/spdk/issues/3079

**Comment by DamiaSan** [comment]
I suggest to try again with the last [version](https://github.com/longhorn/longhorn-instance-manager/commit/53446d898418f657d298102a447bfa1071ec7420) of `longhorn-instance-manager`, it includes:

- `SPDK` updated to the lastest upstream release 24.01
- `longhorn-spdk-engine` with the [sync fix](https://github.com/longhorn/longhorn-spdk-engine/commit/da2a02e86462fb4f3abac4d0f91f2380ff34053c) that is often the root cause of `SPDK` and `nvmecli`  crashes and of memory corruption inside nvme kernel driver. About this, kernel 6.7 has a better error handling inside nvme driver

**Comment by DamiaSan** [comment]
The code that originated this issue is quite obsolete, now we are ready to use upstream release 24.05.
Whar are we going to do with this issue?
@shuo-wu @innobead @derekbit

**Comment by derekbit** [comment]
@DamiaSan 
Can you revalidate it using 24.05 and see if the issue is gone?

**Comment by DamiaSan** [comment]
> @DamiaSan Can you revalidate it using 24.05 and see if the issue is gone?

It was a random issue, not a systematic one. Maybe it should be better if the finder of this issue would try to validate it.
The same is for all other crash issues found with that old version of SPDK.

**Comment by derekbit** [comment]
BTW, if it is identified as a linux kernel issue as you mentioned in https://github.com/longhorn/longhorn/issues/7703#issuecomment-2017414834, please create a PR for updating the official doc as well.

cc @innobead

**Comment by innobead** [comment]
If this could be identified, then should be moved back to 1.7.0?

**Comment by derekbit** [comment]
> If this could be identified, then should be moved back to 1.7.0?

Yes.

**Comment by DamiaSan** [comment]
Documentation update PR https://github.com/longhorn/website/pull/929

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager ce53ab1) and ubuntu 24.04 (kernel version 6.8.0-1009-aws) following [the test plan](https://github.com/longhorn/longhorn/issues/7697#issue-2083424454). After running the `stress-ng` pods for over 3 hours, no issues were observed. The volumes remained healthy, the workloads continued running, and there were no node or pod crashes.

Also ran the robot test v2 volume test case repeatedly. By continuously creating, attaching, writing, detaching and deleting a v2 volume 100 times, didn't observe any issues: https://ci.longhorn.io/job/private/job/longhorn-e2e-test/676/
