### ISSUE TITLE
[BUG] Pod with volume stuck in status ContainerCreating

### ISSUE THREAD

**Issue by isay89** [longhorn/longhorn#7710]
## Describe the bug

I installed longhorn by helm using the official doc, before install I made all steps from Installation Requirements, the check script showed that everything is ok. All longhorn pods has status "Running" after install. I created StorageClass, pvc using the official doc.

When I try to create pod from official doc(https://longhorn.io/docs/1.5.3/volumes-and-nodes/create-volumes/#creating-longhorn-volumes-with-kubectl) with volume, pod stuck in status ContainerCreating and I saw error message in the longhorn-manager pods:

`level=warning msg="Failed to get device type of /var/lib/longhorn/" func="controller.(*ClusterInfo).collectNodeDiskCount" file="setting_controller.go:1713" controller=longhorn-setting error="lstat /sys/class/block/vg.YD0UyAwkZJ-root: no such file or directory" node=10.26.69.244`

and in the kubelet log:
`or syncing pod, skipping" err="unmounted volumes=[volv], unattached volumes=[volv], failed to process volumes=[]: context deadline exceeded" pod="default/volume-test" podUID="e771f640-c49b-4ba9-a1cd-20be1f5d1d21"`

There are no more errors in longhorn pods, on the worker nodes, master nodes, iscsid and etc. I see volume in the longhorn UI with status "Detached". I can attache volume to worker host only via UI, but pod still has status "ContainerCreating".

Pods without volume created and work as well. 

## To Reproduce

Longhorn has been installed using official docs https://longhorn.io/docs/1.5.3/deploy/install/

## Expected behavior

Create and use volume in the pod.

## Support bundle for troubleshooting
[supportbundle_43dfc155-7ffc-4596-9bba-395e56fe4029_2024-01-17T12-14-08Z.zip](https://github.com/longhorn/longhorn/files/13963011/supportbundle_43dfc155-7ffc-4596-9bba-395e56fe4029_2024-01-17T12-14-08Z.zip)

## Environment

 - Longhorn version: 1.5.3
 - Impacted volume (PV): pvc-b4d3c3a7-9e9d-41ea-ae2d-e162fe960398
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.28.3
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: Debian GNU/Linux 12 (bookworm)
   - Kernel version: 6.1.0-17-amd64
   - CPU per node: 
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD): 
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster:

**Comment by ThaiDangFr** [comment]
I have the same messages spamming in the logs of longhorn-manager container too :

time="2024-09-06T20:46:25Z" level=warning msg="Failed to get device type of /var/lib/longhorn/" func="controller.(*ClusterInfo).collectNodeDiskCount" file="setting_controller.go:1728" controller=longhorn-setting error="lstat /sys/class/block/fedora-root: no such file or directory" node=proxmox-k3s-node2

root@proxmox-k3s-node2:~# ls /sys/class/block/
dm-0  sda  sda1  sda2  sda3  sdb  sr0  zram0

root@proxmox-k3s-node2:~# cat /etc/redhat-release 
Fedora release 40 (Forty)

root@proxmox-k3s-node2:~# lvscan 
  ACTIVE            '/dev/fedora/root' [<84,00 GiB] inherit

**Comment by derekbit** [comment]
@isay89 does the issue remain?

**Comment by isay89** [comment]
> @isay89 does the issue remain?

Hello. The issue has been resolved by added annotation "volumes.kubernetes.io/controller-managed-attach-detach: true" to the worker nodes.

Thank you!
