### ISSUE TITLE
[DOC] Mention recurring jobs for filesystem trim 

### ISSUE THREAD

**Issue by dgiebert** [longhorn/longhorn#7712]
## What needs to updated in the documentation

On the page for filesystem trim, it is not mentioned that it is possible to create a recurring job for it.

A link to [this page](https://longhorn.io/docs/1.5.3/snapshots-and-backups/scheduling-backups-and-snapshots/#set-up-recurring-jobs) should be therefore added, maybe even give an example on the fstrim page.

**Comment by c3y1huang** [comment]
PR merged, closing issue.
