### ISSUE TITLE
[BUG] Volume stuck in Attaching after Attached Node Fail

### ISSUE THREAD

**Issue by proligde** [longhorn/longhorn#7713]
## Describe the bug

I have an RWX volume that is consumed by several pods across my cluster. When the node fails where the virtual iscsi device is attached to, the workloads stops working and the cluster does not recover.

The Volume is stuck in State "Attaching"

## To Reproduce

1. Set up a Cluster with three nodes
2. Create a volume with three replicas
3. Create a RWX PV and PVC and create pods mounting it.
4. Look at the node the Longhorn UI mentions to be attached to
5. Shutdown that node without prior draining.
6. Let the Node turned off

## Expected behavior

The Workloads recover

## Actual behaviour

The Volume is stuck in State "Attaching" (not detaching), still showing the down node under the Tab "Attached to", as well as the terminated/stuck in terminating workloads.

New workloads on other nodes are started by Kubernetes, but can't mount the volume and are thus also stuck in initializing/ever getting ready.

## Support bundle for troubleshooting

I have sent it to longhorn-support-bundle@suse.com

## Environment

 - Longhorn version: 1.5.3
 - Impacted volume (PV): pv-durable-live
 - Installation method via Helm chart
 - Kubernetes distro Rancher RKE2 v1.24.17+rke2r1
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 3 (the same)
 - Node config
   - OS type and version: ubuntu 22.04
   - Kernel version: 5.15.0-91-generic
   - CPU per node: 1
   - Memory per node: 64 GB
   - Disk type (e.g. SSD/NVMe/HDD): nvme
   - Network bandwidth between the nodes (Gbps): 1Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 3

I tried scaling down all workloads consuming the volume, and scaling them up, but the situation did not change. It is just stuck on "Attaching" forever. We waited 3 hours now, so I assume this is not a timeout issue.

Everything else on the cluster works - all other workloads recovered successfully. Just longhorn or at least its consumers are hanging indefinitely.

We didn't configure the longhorn helm chart in any way. It was installed "as is" from your repo.

What I found is, that the share manager that was on the same node, is stuck in Terminating.

`share-manager-pv-durable-live                       1/1     Terminating   0             19h`

This is true for the other pods on the shutdown node, too - but they have been rescheduled on the other nodes. This one has not.

I have force-deleted it, but that also didn't lead to a new one spinning up on the other nodes.

**Comment by james-munson** [comment]
This sounds very much like https://github.com/longhorn/longhorn/issues/7183

**Comment by proligde** [comment]
@james-munson I also stumbled across that Issue and at least after restarting the shutdown node I could bring it back to life by manually patching the sharemanager-crd's status to "Error"

However, I'm not sure if I really tried that while the node was shutdown. I'll try that and report any findings here.

**Comment by proligde** [comment]
@james-munson I shutdown the node again and you're right. It's the same issue - at least it's fixed with the same patch. I was confused as the sharemanager's state "running" seemed ok as this time it was located on one of the nodes that were still runing. Forcing it to error state fixed the problem, though.

Guess I'll wait for 1.6.0 release now - thanks for the support! I close this ticket.
