### ISSUE TITLE
[BUG] When disabling revision counter, salvaging a faulty volume not work as expected

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#7714]
## Describe the bug

The code is not right. This is a day 1 issue instead of a regression. 

[/pkg/controller/control.go#L552-L560](https://github.com/longhorn/longhorn-engine/blob/deb8b18a1558ddf4f359146b289d5469bef7cc6d/pkg/controller/control.go#L552-L560)
```go
		repLastModifyTime, err := c.backend.backends[r.Address].backend.GetLastModifyTime()
		if err != nil {
			return err
		}

		repHeadFileSize, err := c.backend.backends[r.Address].backend.GetLastModifyTime() // this is incorrect
		if err != nil {
			return err
		}
```

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

cc @longhorn/qa

**Comment by james-munson** [comment]
Clear copy/paste error.

But it also seems that it doesn't make sense to punt on one unhappy replica.  Skip it and go on.  If there are none that can even report a last modify time or head file size, we will fail the test for "there are no replica candidates."

**Comment by james-munson** [comment]
I'll build and put up a PR for the first point for possible fast-tracking, and we can talk about the second one.

**Comment by innobead** [comment]
@james-munson have you tested the fix?

**Comment by james-munson** [comment]
Not directly.  Just built and run unit tests.  No regressions or manual tests yet.  I will start a regression run with "-k salvage" to begin with.

**Comment by james-munson** [comment]
Salvage tests passed as well.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240123**

- longhorn v1.6.0-rc2 https://github.com/longhorn/longhorn/commit/7a40621dee1408bd90cf9bf92e41ed626f3d0221


**The test steps**

Referencing the documentation [node-disconnection](https://longhorn.github.io/longhorn-tests/manual/pre-release/node-not-ready/node-disconnection/node-disconnection/) and the enhancement related to revision counter disable support PR: [20200821-add-revision-counter-disable-support](https://github.com/longhorn/longhorn/blob/11e1a1659c4287bbbd570c190b19822a7dad0279/enhancements/20200821-add-revision-counter-disable-support.md):


1. Enable `auto-salvage` + `DisableRevisionCounter`.
    1. Disable the Revision Counter via the Longhorn UI.
    2. Deploy a new storage class: `longhorn-test` with `disableRevisionCounter` set to `true` in the parameters.
      ```yaml
      parameters:
        numberOfReplicas: "3"
        disableRevisionCounter: "true"
        staleReplicaTimeout: "2880"
        fromBackup: ""
        fsType: "ext4"
      ```

1. Deploy a PVC and POD using the [pod_with_pvc.yaml example](https://raw.githubusercontent.com/longhorn/longhorn/master/examples/pod_with_pvc.yaml), replacing the storageClassName value with `longhorn-test`.
1. Create a StatefulSet using a new storage class named `longhorn-test` and write data.
1. Execute [test case 3](https://longhorn.github.io/longhorn-tests/manual/pre-release/node-not-ready/node-disconnection/node-disconnection/) under specific conditions.


**Result Passed**

1. After enabling `auto-salvage` + `DisableRevisionCounter`, create, attach, and detach other volumes to the recovered node. All volumes should function correctly.
