### ISSUE TITLE
UI: show `System Hidden` snapshot doesn't work

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#773]
<img width="1265" alt="Screen Shot 2019-09-27 at 10 42 41 AM" src="https://user-images.githubusercontent.com/3344618/65790058-93b12880-e113-11e9-9131-42d32176401a.png">

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to reproduce:
  - Create a volume with size 20 GB, attach it to a node, format it, and mount it to a directory on attached node.
  - Create a data file with size 8GB, and on `Volume Detail` page. create a snapshot
  - Repeat previous step with volume sizes 4 GB & 2 GB data files.
  - Using `lhexec`,  list and remove volume snapshots.
  - UI: on `Volume Detail` page. create a snapshot.
  - UI: on `Volume Detail` page. Delete last created snapshot.
  > Expected result: only one snapshot is shown in the system hidden, and should be displayed/hidden using `Show System Hidden` button.
