### ISSUE TITLE
engine: Recurring backup with retain number leaves a huge list of `Failed to get backup status` in the status

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#774]
E.g.

```
      backup-dd57dbe8a25c4e95:
        error: 'Failed to get backup status on tcp://10.42.0.181:10000 for backup-dd57dbe8a25c4e95:
          rpc error: code = Unknown desc = backup not found backup-dd57dbe8a25c4e95'
        progress: 0
        snapshotName: ""
        state: ""
      backup-dd88bea7c3ca4228:
        error: 'Failed to get backup status on tcp://10.42.0.181:10000 for backup-dd88bea7c3ca4228:
          rpc error: code = Unknown desc = backup not found backup-dd88bea7c3ca4228'
        progress: 0
        snapshotName: ""
        state: ""
```

We need to set a limitation on how many backup errors we should preserve in the engine.

**Comment by yasker** [comment]
@shuo-wu need the reproduce steps

**Comment by shuo-wu** [comment]
Reproduce step:
1. Create and attach a volume with a recurring backup job set (the schedule is `*/1 * * * *`). 
2. Wait for more than 10 minutes. Then check the `backupStatus` in the engine object

**Comment by meldafrawi** [comment]
Validation: **PASSED**

**Comment by tommy04062019** [comment]
> Reproduce step:
> 
> 1. Create and attach a volume with a recurring backup job set (the schedule is `*/1 * * * *`).
> 2. Wait for more than 10 minutes. Then check the `backupStatus` in the engine object
> 
> Before fix: You will see some backup staus contains the error message`'Failed to get backup status on <address> for <backup name>: rpc error: code = Unknown desc = backup not found <backup name>'` After fix: There is no backup status containing an error message. And there are at most 5 `completed` backup status

How to fix??
