### ISSUE TITLE
[IMPROVEMENT] Prevent unsupported volume operations in v2

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#7745]
No, that is not supported in v2. 

Currently, what v2 can support are white list listed in https://longhorn.io/docs/1.6.0/v2-data-engine/features/. However, we should do the following items later after 1.6.

- Mention what features are supported in v1 or v2 in the existing feature pages by reviewing all existing feature pages later
- Prevent unsupported volume operations in the validator webhook instead of handling in controller or IM proxy calls, as when an unsupported operation happens, users would not notice that unless we will update the impacted resources (volume, engine, replica) with extra conditions. 

cc @longhorn/dev-data-plane

_Originally posted by @innobead in https://github.com/longhorn/longhorn/issues/6563#issuecomment-1903374134_

**Comment by shuo-wu** [comment]
It seems that [the validator webhook already blocks unsupported operations for v2 volumes](https://github.com/longhorn/longhorn-manager/blob/5fbee1338dc10a15f633afa39742f0eaa5bf70ef/webhook/resources/volume/validator.go#L245-L317).

**Comment by derekbit** [comment]
> It seems that [the validator webhook already blocks unsupported operations for v2 volumes](https://github.com/longhorn/longhorn-manager/blob/5fbee1338dc10a15f633afa39742f0eaa5bf70ef/webhook/resources/volume/validator.go#L245-L317).

Yes. Do we need to validate engine resources as well? Ideally, users should not touch the fields in engine resources, right?

**Comment by innobead** [comment]
The validator is for updating, but how about volume creation? Which was missed.

**Comment by innobead** [comment]
@derekbit if we don't need this anymore, just close and add label `won't fix`.
