### ISSUE TITLE
[BUG] Protect spdkClient in ReplicaCreate

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7752]
## Describe the bug

Protect spdkClient in ReplicaCreate when replacing the client when there is a connection issue.

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-instance-manager `52decf`), v1.6.x(longhorn-instance-manager `c100da`)

Below v2 volume operations worked well on master-head and v1.6.x-head
- Attach / detach
- Offline replica rebuilding
- Crash instance-manger pod when replica offline rebuilding, rebuild success.
- Create backup
- Restore the backup to v1 and v2 volume
