### ISSUE TITLE
The replica subdirectory of data path won't be created when Longhorn is upgrade from v0.5.0 to v0.6.0

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#776]
When Longhorn is upgraded from v0.5.0 to v0.6.0, the replica subdirectory of data path `/host/var/lib/rancher/longhorn/replicas` somehow doesn't exist then fails volume attach.

The cause of this issue:
In v0.5.0, the subdirectory will be created automatically when there is a Longhorn volume being attached (I haven’t checked the implementation detail for the feature).
In v0.6.0, the replica subdirectory and disk path will be created only when the default nodes don’t exist or `create-default-disk-labeled-nodes` is set.
When the Longhorn is upgraded from v0.5.0 to v0.6.1, the default nodes already exists and they won’t be re-created by v0.6.1 Longhorn manager pods. Then if the replica subdirectory of the data path hasn’t been created by v0.5.0 Longhorn, it cannot be created by the new Longhorn (v0.6.1).

The key point for this issue is that Longhorn v0.5.0 won't create the replica subdirectory of the disk path when adding the default disk to the node.

```
[instance-manager-r-8a4c54fc] [test1-r-da744d57] time="2019-09-27T22:34:24Z" level=fatal msg="Error running start replica command: mkdir /host/var/lib/rancher/longhorn/replicas/test1-5e718a22: no such file or directory"
[instance-manager-r-8a4c54fc] [longhorn-instance-manager] time="2019-09-27T22:34:24Z" level=info msg="Process Manager: process test1-r-da744d57 error out, error msg: exit status 1"
[instance-manager-r-8a4c54fc] [longhorn-instance-manager] time="2019-09-27T22:34:24Z" level=info msg="Process Manager: prepare to create process test1-r-da744d57"
```

**Comment by shuo-wu** [comment]
The steps to reproduce it:
1. Deploy a new cluster. Or clean up the longhorn directory `/var/lib/rancher/longhorn` for the existing cluster nodes.
2. Deploy Longhorn v0.5.0
3. Do nothing on Longhorn v0.5.0, directly upgrade it to v0.6.1
4. Create and attach a volume. The volume will get stuck in `attaching` and the replicas are always in state `Stopped`

**Comment by meldafrawi** [comment]
Validation: **PASSED**
