### ISSUE TITLE
[TEST] ADD v2 volume sanity check test cases for pre-release test suite

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#7763]
## What's the test to develop? Please describe

ADD v2 volume sanity check test cases for pre-release test suite

## Describe the tasks for the test

As V2 volume related test cases are not automated, we need to add in the prerelease manual test cases. For now, just the basic testing is enough.
1. Creation and operation on V2 volume
2. Backup and restore
3. Upgrade with V2 volume

**Comment by yangchiu** [comment]
Supported features for v2 volume are listed here: https://longhorn.io/docs/1.6.0/v2-data-engine/features/
