### ISSUE TITLE
[BUG][v1.6.0-rc2] rwx volume failed to execute trim filesystem

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#7768]
## Describe the bug

The rwx volume failed to execute trim filesystem and received an error as shown in the message and screenshot.
```console
unable to trim filesystem for volume pvc-156966f3-daab-4e2e-a1f8-3531c8e233c8: rpc error: code = Internal desc = failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/1446380/ns/mnt --net=/host/proc/1446380/ns/net fstrim /export/pvc-156966f3-daab-4e2e-a1f8-3531c8e233c8], output , stderr fstrim: cannot get realpath: /export/pvc-156966f3-daab-4e2e-a1f8-3531c8e233c8: No such file or directory : exit status 1
```
![Screenshot_20240124_124627](https://github.com/longhorn/longhorn/assets/104337648/49486610-fa7e-4dde-a5e1-8572abd9b0b9)

## To Reproduce

1. create rwx volume and deploy POD
1. rwx volume execute `trim filesystem`

## Expected behavior

rwx volume should be executed `trim filesystem` without error.

## Support bundle for troubleshooting

[supportbundle_afef4354-d6b0-4877-b5c7-0bcb93bb31b4_2024-01-24T04-46-52Z.zip](https://github.com/longhorn/longhorn/files/14033236/supportbundle_afef4354-d6b0-4877-b5c7-0bcb93bb31b4_2024-01-24T04-46-52Z.zip)

**Comment by derekbit** [comment]
cc @c3y1huang

**Comment by innobead** [comment]
Good catch @roger-ryao

**Comment by roger-ryao** [comment]
**Verified on master-head 20240125**

  - longhorn `master-head `https://github.com/longhorn/longhorn/commit/c3a9f120e30287d5ba1b954a0227f637309dff81
  - longhorn-share-manager `master-head` https://github.com/longhorn/longhorn-share-manager/commit/3168f43cad72c25cec704494064f3f58e28b7210

  - longhorn `v1.6.x-head` https://github.com/longhorn/longhorn/commit/b34b8735e0c98daa9e4d200d3f17c5cb6056e1f3
  - longhorn-share-manager `v1.6.x-head` https://github.com/longhorn/longhorn-share-manager/commit/1ca74f4c166d958c2dc4e38d278324956326e0af

**The test steps**
https://github.com/longhorn/longhorn/issues/7768#issue-2097433844

**Result Passed**
