### ISSUE TITLE
[IMPROVEMENT] Remove unused process manager connection in longhorn-manager

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7783]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The longhorn-manager communicates with the process manager gRPC service in an older instance-manager (apiVersion < 4). For a newer instance-manager, however, the longhorn-manager only needs to interact with the instance gRPC service. As a result, there is no requirement for the longhorn-manager to establish a connection to the process manager.

**Comment by chriscchien** [comment]
Verifed **pass** on longhorn master(longhorn-manager `c7d9d7`), longhorn v1.6.x(longhorn-manager `1640c5`)

After upgrade from v1.4.x to master-head and to v1.6.x
- The volume with old engine can perform detach and reattach operations without any problem.
- Create/Attach/Detach new v1 and v2 volumes success.
