### ISSUE TITLE
engine: deadlock in `snapshot purge` result in `Too many snapshots`

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#779]
Observed the stuck of purge snapshot during the recurring scheduled backup. With one minute snapshot running for a couple of days.

It results in `Too many snapshots` in the end.

Found the snapshot purge cannot proceed.

Manual testing reveals that the snapshot purge cannot proceed due to cannot get snapshot purge-status from one of the replica:

```
$ ./deploy/scripts/lhexec pvc-e7aa3b1e-dff1-11e9-8d8a-f23c91ea81c2 snapshot purge
FATA[0060] Error running purge snapshot command: Failed to purge snapshots: failed to get snapshot purge status: rpc error: code = DeadlineExceeded desc = context deadline exceeded
command terminated with exit code 1


$ ./deploy/scripts/lhexec pvc-e7aa3b1e-dff1-11e9-8d8a-f23c91ea81c2 snapshot purge-status
{
	"tcp://10.42.0.181:10015": {
		"error": "",
		"isPurging": false,
		"progress": 100,
		"state": "complete"
	},
	"tcp://10.42.1.181:10015": {
		"error": "",
		"isPurging": false,
		"progress": 100,
		"state": "complete"
	},
	"tcp://10.42.2.208:10015": {
		"error": "failed to get snapshot purge status of tcp://10.42.2.208:10015: failed to get snapshot purge status: rpc error: code = DeadlineExceeded desc = context deadline exceeded",
		"isPurging": false,
		"progress": 0,
		"state": ""
	}
}
```

Looking at the code, found a deadlock caused by the wrong lock order:

[Here](https://github.com/longhorn/longhorn-engine/blob/edfea2c87843cc23a7b6c2f0acdca3c968f3c37b/sync/rpc/server.go#L892) `s.Lock()` was acquired first, then `PurgeStatus.Lock()`. But the order is reversed [here](https://github.com/longhorn/longhorn-engine/blob/edfea2c87843cc23a7b6c2f0acdca3c968f3c37b/sync/rpc/server.go#L885).

**Comment by yasker** [comment]
Maybe related to https://github.com/longhorn/longhorn/issues/766

**Comment by yasker** [comment]
The following script can reproduce the deadlock in the pre-fix version in a Longhorn engine setup.

```
#!/bin/bash

function purge(){
	./bin/longhorn snapshot purge
}

function query(){
	./bin/longhorn snapshot purge-status
}

for i in $(seq 1000)
do
	echo $i
	purge &
	query &
done
```

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
  - Pull the latest engine master, make build && make package
  - Run the engine using docker run -it --privileged -v /volume -v /proc:/host/proc -v /dev:/host/dev longhornio/longhorn-engine:<version> /bin/bash
  - inside the engine container run
  `longhorn replica /tmp/replica1 --size 10G &`, then
  `longhorn controller --replica tcp://localhost:9502 volumetest`
  - Use the script to trigger the deadlock.
  > Expected result: deadlock shouldn't be triggered after the fix is applied.
