### ISSUE TITLE
[FEATURE] Talos support for v2 data engine

### ISSUE THREAD

**Issue by pl4nty** [longhorn/longhorn#7791]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Talos support was recently added in #3161, but [doesn't include the v2 data engine due to its preview status](https://github.com/longhorn/longhorn/pull/6325#discussion_r1292904665).

## Describe the solution you'd like

Track the implementation of v2 data engine support on Talos. It might be too early to start planning, but these are some known options:
- [ ] Move dependencies to pods eg #6798
- [ ] Remove unsupported host dependencies eg `bash`
- [ ] Add host dependencies via Talos extensions. I'm happy to help implement this

## Additional context

I've tested v1.6.0-rc2 via https://pl4nty.github.io/longhorn-charts and succeeded until the following error when attaching a PVC.

> 2024-01-26T03:16:46.412777662Z [longhorn-instance-manager] time="2024-01-26T03:16:46Z" level=error
msg="Failed to create engine pvc-c864947e-5fda-4d26-9f56-d949c9beeb0d-e-0"
func="spdk.(*Engine).Create.func2" file="engine.go:114" engineName=pvc-c864947e-5fda-4d26-9f56-d949c9beeb0d-e-0

> error="failed to start NVMe initiator pvc-c864947e-5fda-4d26-9f56-d949c9beeb0d:
failed to get file lock for initiator pvc-c864947e-5fda-4d26-9f56-d949c9beeb0d:
Failed to lock, response:
nsenter: failed to execute bash, expected NSFileLock LOCKED"

> frontend=spdk-tcp-blockdev ip=10.244.3.11 port=20006 replicaAddressMap="map[pvc-c864947e-5fda-4d26-9f56-d949c9beeb0d-r-ee59f025:10.244.3.11:20001]" volumeName=pvc-c864947e-5fda-4d26-9f56-d949c9beeb0d

This appears to be caused by a dependancy on bash via nsfilelock:
https://github.com/longhorn/nsfilelock/blob/fa7c83ad0003bbfffc0014f79ec09efef7dcc869/nsfilelock.go#L64-L70

https://github.com/longhorn/go-spdk-helper/blob/4f19a2cd0e085141083d3014d753b67e5c64f39b/pkg/nvme/initiator.go#L126-L129

**Comment by c3y1huang** [comment]
ref: https://github.com/siderolabs/pkgs/pull/1015

**Comment by pl4nty** [comment]
Thanks, I'm looking forward to testing this! Are there any plans to run verification against Talos v1.8.0 (latest as of Sep 24th)? Nothing worries me from the [changelog](https://github.com/siderolabs/talos/releases/tag/v1.8.0), but it'd be nice to be sure
