### ISSUE TITLE
[TEST] Resources stress test to check cpu or memory consumption

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7808]
## What's the test to develop? Please describe

Resources stress test to check cpu or memory consumption
- Secrets
- ConfigMaps
- Volumes

**Comment by derekbit** [comment]
Memory usage in v1.6.0-rc3 with multiple Secrets, ConfigMaps and Pos is expected and less than v1.5.1.
| API object | Namespace | Number of objects | Memory usage increased (1.6.0-rc3) | Memory usage increased (1.5.1) |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| Secret       |  default | 5000 | 76 MiB | 323 MiB |
| Secret       |  longhorn-system  | 5000 | 150 MiB      |  353 MiB
| ConfigMap       |  default |    5000           |   0 MiB        |        124 MiB  |
| ConfigMap       |  longhorn-system  |    5000           |   78 MiB       |      137 MiB    |
| Pod       |  default |    500           |    51 MiB      |  275 MiB         |

cc @innobead @longhorn/qa 

- Secret
  ```
  #!/bin/bash
  
  for i in {1..5000}; do
    filename="mysecret-$i.yaml"
    password=$(openssl rand -base64 4096 | tr -d '\n')
  
    cat <<EOF >"$filename"
  apiVersion: v1
  kind: Secret
  metadata:
    name: mysecret-$i
    namespace: longhorn-system
  type: Opaque
  data:
    password: "$password"
  EOF
    echo "Generated $filename"
    kubectl apply -f $filename
  done
  ```

- ConfigMap
  ```
  #!/bin/bash
  
  for i in {1..5000}; do
    filename="myconfigmap-$i.yaml"
    password=$(openssl rand -base64 4096 | tr -d '\n')
  
    cat <<EOF >"$filename"
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: myconfigmap-$i
    namespace: longhorn-system
  data:
    password: "$password"
  EOF
  
    echo "Generated $filename"
    kubectl apply -f $filename
  done
  ```

- Pod
  ```
  #!/bin/bash
  
  for i in {1..500}; do
    filename="myvolume-$i.yaml"
  
    cat <<EOF >"$filename"
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: myvolume-$i
    namespace: default
  spec:
    accessModes:
      - ReadWriteOnce
    storageClassName: longhorn
    resources:
      requests:
        storage: 100Mi
  EOF
  
    echo "Generated $filename"
    kubectl apply -f $filename
  done
  ```

**Comment by roger-ryao** [comment]
**Verified on v1.6.0-rc3 20240131**

- longhorn v1.6.0-rc3 https://github.com/longhorn/longhorn/commit/06b094c2892c850e2b4f2a55a572c2ba6d1d3aca


**The test steps**

1. https://github.com/longhorn/longhorn/issues/7808#issuecomment-1916149250
1. Ref. https://github.com/longhorn/longhorn/issues/6936#issuecomment-1775396141

**Result**

CPU Comparison:
|                            | v1.6.0 RC3 CPU(cores) | v1.5.1 CPU(cores) | v1.5.3 CPU(cores) |
|----------------------------|-----------------------|-------------------|-------------------|
| `500 volumes attach to node` + `5000 secret`+`5000 config map`  |                       |                   |                   |
| instance-manager-1   | 1429m                 | 2557m             | 1373m             |
| instance-manager-2   | 1371m                 | 2460m             | 1358m             |
| instance-manager-3   | 1451m                 | 2604m             | 1400m             |
| longhorn-manager-1      | 142m                  | 653m              | 661m              |
| longhorn-manager-2      | 209m                  | 1079m             | 1308m             |
| longhorn-manager-3      | 148m                  | 449m              | 325m              |
|                            |                       |                   |                   |
| `500 detach volumes` + `5000 secret` + `5000 config map`          |                       |                   |                   |
| instance-manager-1   | 8m                    | 1024m             | 1m                |
| instance-manager-2   | 8m                    | 1m                | 1m                |
| instance-manager-3   | 8m                    | 1m                | 1m                |
| longhorn-manager-1      | 6m                    | 19m               | 59m               |
| longhorn-manager-2      | 3m                    | 115m              | 27m               |
| longhorn-manager-3      | 4m                    | 56m               | 41m               |


MEMORY Comparison:
|                            | v1.6.0 RC3 MEMORY(bytes) | v1.5.1 MEMORY(bytes) | v1.5.3 MEMORY(bytes) |
|----------------------------|--------------------------|----------------------|----------------------|
| `500 volumes attach to node` + `5000 secret`+`5000 config map`  |                          |                      |                      |
| instance-manager-1   | 12489Mi                  | 12509Mi              | 13033Mi              |
| instance-manager-2   | 13326Mi                  | 4168Mi               | 13088Mi              |
| instance-manager-3   | 13254Mi                  | 12587Mi              | 13158Mi              |
| longhorn-manager-1      | 629Mi                    | 1654Mi               | 602Mi                |
| longhorn-manager-2      | 683Mi                    | 1713Mi               | 639Mi                |
| longhorn-manager-3      | 594Mi                    | 1475Mi               | 604Mi                |
|                            |                          |                      |                      |
| `500 detach volumes` + `5000 secret` + `5000 config map`          |                          |                      |                      |
| instance-manager-1   | 136Mi                    | 1378Mi               | 22Mi                 |
| instance-manager-2   | 129Mi                    | 137Mi                | 20Mi                 |
| instance-manager-3   | 129Mi                    | 125Mi                | 29Mi                 |
| longhorn-manager-1      | 365Mi                    | 2424Mi               | 585Mi                |
| longhorn-manager-2      | 435Mi                    | 1998Mi               | 601Mi                |
| longhorn-manager-3      | 406Mi                    | 1738Mi               | 602Mi                |

cc @derekbit
