### ISSUE TITLE
UI: volume-head disappeared at recurring snapshot create. 

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#781]
Steps to reproduce:

  - Create a volume, attach it to a node.
  - Create a recurring snapshot every 1 min.
  - Wait for snapshot to be created, **Do Not** refresh the page.
![Screenshot from 2019-10-01 00-12-03](https://user-images.githubusercontent.com/18232258/65920907-cba0c000-e3e0-11e9-9fe4-06c09999719a.png)

**Comment by yasker** [comment]
Move to 0.7.0 since China team is on holiday

**Comment by meldafrawi** [comment]
Validation: **PASSED**
