### ISSUE TITLE
[TASK] Sync longohorn/spdk codes with upstream codes

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7812]
## What's the task? Please describe

The most recent synchronization for [longhorn/spdk](https://github.com/longhorn/spdk) occurred eight months ago, resulting in the current codes being out of sync.

> This branch is [314 commits ahead of](https://github.com/longhorn/spdk/compare/spdk%3Aspdk%3Amaster...longhorn), [1478 commits behind](https://github.com/longhorn/spdk/compare/longhorn...spdk%3Aspdk%3Amaster) spdk/spdk:master.

To maintain code consistency and leverage the bug fixes introduced in upstream codes, we should perform regular syncs, and each feature owner is responsible for maintaining or porting the codes associated with the feature.

| Task | Owner | Status|
| -- | -- | -- | 
| Code base regular sync | @DamiaSan  |
| Raid | @DamiaSan  |
| Lvol flush | @DamiaSan  |
| Lvol actual size | @DamiaSan  |
| Lvol shallow copy | @DamiaSan  |
| Lvol xattr | @derekbit |
| Lvol fragmap | @derekbit |

**Comment by derekbit** [comment]
cc @shuo-wu @innobead

**Comment by innobead** [comment]
@derekbit @shuo-wu @DamiaSan need to make sure downstream cherry-picks all to the new spdk branch. Please update the status here individually. Thanks.

**Comment by DamiaSan** [comment]
I am already working on it, for this first time I wanted to cherry picks all our downstream commits, also Shuo's and Derek's ones. Is this fine for you?

**Comment by DamiaSan** [comment]
Subtask #7578

**Comment by DamiaSan** [comment]
New branch created: https://github.com/longhorn/spdk/tree/longhorn-v24.01

**Comment by derekbit** [comment]
@DamiaSan Please update the pipeline status of the issue.

**Comment by DamiaSan** [comment]
> @DamiaSan Please update the pipeline status of the issue.

It is Closed
