### ISSUE TITLE
investigate: why uninstaller get involved in the Longhorn app upgrade/rollback process

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#783]
There are two reports that the uninstaller get involved: https://github.com/longhorn/longhorn/issues/782#issuecomment-536805285 and https://github.com/longhorn/longhorn/issues/755#issuecomment-535363241

We don't expect the uninstaller to get involved during upgrade/rollback, since it will clean up the user volume data if triggered. If it's the mechanism of Helm chart rollback, we need to stop it from happening.

**Comment by rbq** [comment]
@yasker Regarding [my comment from #755](https://github.com/longhorn/longhorn/issues/755#issuecomment-535363241): I saw the uninstaller running at least once, but don't remember if it was when I created a 0.5 release following a 0.6.1 one, or later when rolling back to a previous revision. Sorry, I wish I could be of more help.

**Comment by shuo-wu** [comment]
Steps to reproduce this issue:
1. Deploy Longhorn v0.5.0 and wait for it to becomes `active`
2. Upgrade Longhorn to v0.6.1 and wait for it to becomes `active` 
3. Roll back or upgrade Longhorn to v0.5.0 and wait for it to becomes `active` 
4. Re-upgrade Longhorn to v0.6.1 --> error message `failed to install app longhorn-system. Error: UPGRADE FAILED: no CustomResourceDefinition with the name "instancemanagers.longhorn.rancher.io" found` errors
5. Upgrade Longhorn to v0.5.0 --> The uninstaller is triggered

**Comment by shuo-wu** [comment]
The causes for this issue:
1. The upgrade failure of step 4 is due to [the helm bug](https://github.com/helm/helm/issues/6031)

**Comment by shuo-wu** [comment]
The key point for this issue is to avoid upgrade failure (error in step 4) in old Rancher. For the details, see: https://github.com/longhorn/longhorn/wiki/Longhorn-v0.6.0-Upgrade:-caveats-about-rolling-back-to-v0.5.0

**Comment by meldafrawi** [comment]
Validation: **WIP**

**Comment by meldafrawi** [comment]
Validation: **Failed**


Steps to test
0- Rancher v2.2.7; Kubernetes v1.13.9; 3-node cluster.
1. Deploy Longhorn v0.5.0 and wait for it to becomes active
2. Upgrade Longhorn to v0.6.1 and wait for it to becomes active
3. Roll back or upgrade Longhorn to v0.5.0 and wait for it to becomes active
4.
    - Scenario 1:
      - No cleanup before Re-upgrading Longhorn to v0.6.1 --> error message failed to install app longhorn-system. Error: UPGRADE FAILED: no CustomResourceDefinition with the name "instancemanagers.longhorn.rancher.io" found occurs.
       - Then upgrade Longhorn to v0.5.0 after the error message occurs --> The uninstaller is triggered
    - Scenario 2:
      - Do cleanup before Re-upgrading Longhorn to v0.6.1. The re-upgrade should succeed.

In Scenario 2, after upgrade to v0.6.1 succeeds:
5. Create a volume `volume-1`, attach it to a node.
> Expected Result: Volume is attached  (**FAILED**)
> Failure: Volume is stuck in attaching state.

6. detach the stuck volume, and upgrade to use `master` images.
7. retry to attach `volume-1` to a node.
> Expected Result: Volume is attached  (**FAILED**)
> Failure: Volume is stuck in attaching state.

8. Create another volume `volume-2`, attach it to a node, volume get attached successfully.

**Comment by shuo-wu** [comment]
The above failure is actually caused by these two issues:
https://github.com/longhorn/longhorn/issues/776
https://github.com/longhorn/longhorn/issues/789

@meldafrawi Could you directly use the latest version(`v0.6.2` in the private test chart) to test this issue?

**Comment by meldafrawi** [comment]
Validation: **PASSED**


Steps to test
Using Rancher v2.2.7; Kubernetes v1.13.9; 3-node cluster.
1. Deploy Longhorn v0.5.0 and wait for it to becomes active
2. Upgrade Longhorn to v0.6.2 (master) and wait for it to becomes active
3. Roll back or upgrade Longhorn to v0.5.0 and wait for it to becomes active
4.
    - Scenario 1:
      - No cleanup before Re-upgrading Longhorn to v0.6.2 (master) --> error message failed to install app longhorn-system. Error: UPGRADE FAILED: no CustomResourceDefinition with the name "instancemanagers.longhorn.rancher.io" found occurs.
       - Then upgrade Longhorn to v0.5.0 after the error message occurs --> The uninstaller is triggered
    - Scenario 2:
      - Do cleanup before Re-upgrading Longhorn to v0.6.2 (master). The re-upgrade should succeed.

In Scenario 2, after upgrade to v0.6.2 (master) succeeds:
5. Create a volume `volume-1`, attach it to a node.
> Expected Result: Volume is attached
