### ISSUE TITLE
[IMPROVEMENT] Make environment_check look for a global default K8s priority class in those releases that it affects.

### ISSUE THREAD

**Issue by james-munson** [longhorn/longhorn#7831]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Setting a global default priority class can cause issues in releases that don't create a `longhorn-critical` priority for longhorn-system pods to use.  See https://github.com/longhorn/longhorn/issues/2820.

That behavior is fixed in v1.6.0 and later by adding and defaulting to priority `longhorn-critical`, see https://github.com/longhorn/longhorn/issues/6528

## Describe the solution you'd like

For releases before that, it would be good to have that checked and warned about in the pre-install `environment_check` script.

## Additional context

This is strictly a change for releases before v1.6.0.  The milestone is set appropriately.

**Comment by james-munson** [comment]
To test, apply this yaml to create a global default priority class on a cluster:
```yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: problematic-default-priority
value: 1000000
globalDefault: true
description: "This priority class will cause problems with Longhorn."
```

Then run the `environment_check` script.  With this change, there should be a warning:
>[WARN]  Cluster has a global default priority class. See potential issue and solution at https://longhorn.io/kb/troubleshooting-instance-manager-pods-are-restarted-every-hour/#reason

If the priority class is edited to remove the globalDefault flag or deleted entirely, the script's warning will not show.

**Comment by innobead** [comment]
@mantissahz Please help verify this issue as QA. Close it if it passes the testing. Thanks. 

cc @longhorn/qa

**Comment by mantissahz** [comment]
Verified `PASSED` with Longhorn v1.5.x ([9c286a1](https://github.com/longhorn/longhorn/commit/9c286a166388a0b43a8b2efdc1a1281a0b539a4a))

Created a global PriorityClass by 
```yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: problematic-default-priority
value: 1000000
globalDefault: true
description: "This priority class will cause problems with Longhorn."
```

1. Created a PriorityClass with `globalDefault` enabled

```txt
root@rancher70-master:~/longhorn# ./scripts/environment_check.sh
[INFO]  Required dependencies 'kubectl jq mktemp sort printf' are installed.
[INFO]  All nodes have unique hostnames.
[WARN]  Cluster has a global default priority class. See potential issue and solution at https://longhorn.io/kb/troubleshooting-instance-manager-pods-are-restarted-every-hour/#reason
[INFO]  Waiting for longhorn-environment-check pods to become ready (0/3)...
[INFO]  Waiting for longhorn-environment-check pods to become ready (0/3)...
[INFO]  All longhorn-environment-check pods are ready (3/3).
[INFO]  MountPropagation is enabled
[INFO]  Checking kernel release...
[INFO]  Checking iscsid...
[INFO]  Checking multipathd...
[WARN]  multipathd is running on rancher70-worker2
[WARN]  multipathd is running on rancher70-worker1
[WARN]  multipathd is running on rancher70-worker3
[INFO]  Checking packages...
[INFO]  Checking nfs client...
[INFO]  Cleaning up longhorn-environment-check pods...
[INFO]  Cleanup completed.
```

2. Created a PriorityClass with `globalDefault` disabled

```txt
root@rancher70-master:~/longhorn# ./scripts/environment_check.sh
[INFO]  Required dependencies 'kubectl jq mktemp sort printf' are installed.
[INFO]  All nodes have unique hostnames.
[INFO]  Waiting for longhorn-environment-check pods to become ready (0/3)...
[INFO]  All longhorn-environment-check pods are ready (3/3).
[INFO]  MountPropagation is enabled
[INFO]  Checking kernel release...
[INFO]  Checking iscsid...
[INFO]  Checking multipathd...
[WARN]  multipathd is running on rancher70-worker2
[WARN]  multipathd is running on rancher70-worker3
[WARN]  multipathd is running on rancher70-worker1
[INFO]  Checking packages...
[INFO]  Checking nfs client...
[INFO]  Cleaning up longhorn-environment-check pods...
[INFO]  Cleanup completed.
```

**Comment by james-munson** [comment]
Simple to backport to 1.4.5, so let's.
