### ISSUE TITLE
[BUG] Trim dose not work on Talos based systems

### ISSUE THREAD

**Issue by boixu** [longhorn/longhorn#7836]
## Describe the bug
Hi
I have installed longhorn v1.6.0 on a Talos based system and the trim functionality dose not work.

The following error is seen when trying to use the trim function via UI.

`unable to trim filesystem for volume pvc-8f44060d-9db2-4671-b32b-5c4a34f6bd2d: cannot find volume pvc-8f44060d-9db2-4671-b32b-5c4a34f6bd2d mount info on host: failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/60369/ns/mnt --net=/host/proc/60369/ns/net fstrim /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/27077305d4af8da5d7347a03588d5e47c1385d87f8b1e5d785e0c76e27a26a4c/globalmount], output , stderr fstrim: /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/27077305d4af8da5d7347a03588d5e47c1385d87f8b1e5d785e0c76e27a26a4c/globalmount: the discard operation is not supported : exit status 1`

Help is much appreciated! 

## To Reproduce
Install longhorn v1.6.0 on a Talos based system. Create Volume and try to trim it.

## Expected behavior
Trim on volume works

## Environment

 - Longhorn version: v1.6.0
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Talos
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 8
 - Node config
   - OS type and version: Talos v1.6.1
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 15

**Comment by 5olu7ion** [comment]
Yep, it's the same on my installation:
- Proxmox 8.1.3 (nvme ssd's)
- Talos 1.6.3
- Longhorn 1.6.0

Disks are attached with ssd emulation, util-linux extension is installed.

**Comment by c3y1huang** [comment]
So far I've not been able to replicate the issue on Talos version 1.6.0, 1.6.1, and 1.6.3 using Longhorn v1.6.0 for both RWO and RWX volumes.

@boixu , @5olu7ion ,

Here are a couple of things you could consider to try for further investigation:
1. Manually test the `fstrim` to ensure it is working in your environment, ref https://github.com/longhorn/longhorn/issues/5203#issuecomment-1372015161. You need to run the `fstrim` command in the `kubelet` namespace with `nsenter`. Similar to `nsenter --mount=/host/proc/<KUBELET>/ns/mnt --net=/host/proc/<KUBELET_PID>/ns/net fstrim <MOUNT_POINT>`. You can leverage the command specified in your error log
1. Consider experimenting with adding the discard opiton to the mountOptions, ref: https://github.com/longhorn/longhorn/issues/5806#issuecomment-1522259157

If you could provide the support bundle, we might have better insights.

Additionally, in the past, Longhorn has been reported with similar errors with older Kernel versions, it seems unlikely to be the case here. Talos v1.6.0 was released on 2023-12-15, and both itself and the subsequent minor versions would have been packaged with more recent Kernel versions.

**Comment by 5olu7ion** [comment]
@c3y1huang I can help investigating. Can you give me a hint, how I can execute commandos in the kubelet in talos? If it helps, my cluster is brandnew, and 1.6.0 is my first longhorn installation. I did not restore or upgrade from another longhorn installation.

**Comment by boixu** [comment]
@c3y1huang Thanks for the suggestions! 
Sadly the suggested solution from https://github.com/longhorn/longhorn/issues/5806#issuecomment-1522259157 did not help. Added the 
`mountOptions:
- discard`
Detached and re-attached the volume and still same error.

For the first suggestion I am also unaware as to how you can run commands on a Talos based system. Would appreciate any tips!

I quickly went over the support bundle contents and I do not feel safe about sharing it with others(for example it exported my cert-manager issuer info that includes my private email etc, so would like to avoid going over the whole bundle and obfuscating the data.) Or if you specify some specific part that is needed I would happily share it(storage class config etc).

**Comment by c3y1huang** [comment]
> how I can execute commandos in the kubelet in talos?

> For the first suggestion I am also unaware as to how you can run commands on a Talos based system. 

Using the error from the issue description as an example:
> unable to trim filesystem for volume pvc-8f44060d-9db2-4671-b32b-5c4a34f6bd2d: cannot find volume pvc-8f44060d-9db2-4671-b32b-5c4a34f6bd2d mount info on host: failed to execute: /usr/bin/nsenter [**nsenter --mount=/host/proc/60369/ns/mnt --net=/host/proc/60369/ns/net** fstrim /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/27077305d4af8da5d7347a03588d5e47c1385d87f8b1e5d785e0c76e27a26a4c/globalmount], output , stderr fstrim: /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/27077305d4af8da5d7347a03588d5e47c1385d87f8b1e5d785e0c76e27a26a4c/globalmount: the discard operation is not supported : exit status 1

You can switch to the Kubelet namespace from the longhorn-manager pod (where the log is located). For example:
```bash
LONGHORN_MANAGER_POD="longhorn-manager-xxxxx"
KUBELET_PID=60369

kubectl -n longhorn-system exec -it $LONGHORN_MANAGER_POD -- bash

nsenter --mount=/host/proc/$KUBELET_PID/ns/mnt --net=/host/proc/$KUBELET_PID/ns/net bash
```

Note that the Kubelet PID would vary for every node, so the most straightforward approach is to utilize the logs in the longhorn-manager pod.

Once within the Kubelet namespace, you should be able to test the `fstrim` command.

**Comment by 5olu7ion** [comment]
Error in Longhorn ui and log:
```unable to trim filesystem for volume portainer-ee-data: cannot find volume portainer-ee-data mount info on host: failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/4687/ns/mnt --net=/host/proc/4687/ns/net fstrim /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/13e8e22cd62038c0c88a8e5c92c24d127a2c293734a5ffb0b83665147dba45fd/globalmount], output , stderr fstrim: /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/13e8e22cd62038c0c88a8e5c92c24d127a2c293734a5ffb0b83665147dba45fd/globalmount: the discard operation is not supported : exit status 1```

fstrim -an:
```longhorn-manager-lx2t7:/ # nsenter --mount=/host/proc/4687/ns/mnt --net=/host/proc/4687/ns/net fstrim -na
/var/mnt/longhorn: 0 B (dry run) trimmed on /dev/sdb1
/var: 0 B (dry run) trimmed on /dev/sda6
/system/state: 0 B (dry run) trimmed on /dev/sda5
```

fstrim -n (specific volume):
```longhorn-manager-lx2t7:/ # nsenter --mount=/host/proc/4687/ns/mnt --net=/host/proc/4687/ns/net fstrim -n /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/13e8e22cd62038c0c88a8e5c92c24d127a2c293734a5ffb0b83665147dba45fd/globalmount
/var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/13e8e22cd62038c0c88a8e5c92c24d127a2c293734a5ffb0b83665147dba45fd/globalmount: 0 B (dry run) trimmed
```

fstrim -v (specific colume):
```
longhorn-manager-lx2t7:/ # nsenter --mount=/host/proc/4687/ns/mnt --net=/host/proc/4687/ns/net fstrim -v /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/13e8e22cd62038c0c88a8e5c92c24d127a2c293734a5ffb0b83665147dba45fd/globalmount
fstrim: /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/13e8e22cd62038c0c88a8e5c92c24d127a2c293734a5ffb0b83665147dba45fd/globalmount: the discard operation is not supported
```

I added the disk to talos with the following options:
```
        extraMounts:
            - destination: /var/mnt/longhorn
              type: bind
              source: /var/mnt/longhorn
              options:
                - rbind
                - rshared
                - rw
```

proxmox disks are attached via virtio scsi: https://forum.proxmox.com/threads/fstrim-fstrim-the-discard-operation-is-not-supported.31955/ and I installed proxmox on zfs. @boixu Do you have any similarities or differences?

**Comment by boixu** [comment]
I get the same as @5olu7ion 

```
root@longhorn-manager-99v6x:/# fstrim /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/27077305d4af8da5d7347a03588d5e47c1385d87f8b1e5d785e0c76e27a26a4c/globalmount/
fstrim: /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/27077305d4af8da5d7347a03588d5e47c1385d87f8b1e5d785e0c76e27a26a4c/globalmount/: the discard operation is not supported
```

**Comment by boixu** [comment]
Updated talos to 1.7.0 and longhorn to 1.6.1 and issue still the same

**Comment by boixu** [comment]
I have identified the cause of the issue.
It's because I use encrypted volumes. Trim works on non encrypted volumes.
As I understand I need to enable `allow-discards` for dm_crypt since that should be the kernel module used
Currently the encryption dose not allow TRIM.

**Comment by boixu** [comment]
Dose not seems like Talos support passing any arguments for this and might not even be a Talos side thing to fix.
@c3y1huang Could we pass this `cryptsetup --allow-discards --persistent refresh <Longhorn volume name>` Somehow or enable the `--allow-discards` from longhorn side?
As I understand longhorn is the one doing the encryption anyway so makes sense if this could be passed from longhorn side.
For clarification on my Talos node there is no encryption present, only longhorn volumes are encrypted.

Thanks!

**Comment by c3y1huang** [comment]
Longhorn doesn't support trimming an encrypted volume. You can try manually trimming it.

Ref:
- https://longhorn.io/docs/1.6.1/nodes-and-volumes/volumes/trim-filesystem/#encrypted-volumes
- https://github.com/longhorn/longhorn/issues/836

cc @shuo-wu

**Comment by boixu** [comment]
Thanks for the clarification! Since it's not supported I have no other option but to migrate over to non encrypted volumes(Trim is more important in my case and I did not notice that encrypted volumes don't support trim initially).

This ticket can then be closed.

Thanks for the assistance!
