### ISSUE TITLE
[BUG] Volumes fail to degraded state almost instantly

### ISSUE THREAD

**Issue by QuinnyPig** [longhorn/longhorn#7838]
## Describe the bug

After creating volumes on Longhorn, they immediately degrade. The logs aren't particularly helpful here; it seems this happens more with volumes under heavy use (Prometheus, I'm looking at tou here).

## To Reproduce

I'm unsure; it's happened consistently for me on the k3s Raspberry Pi cluster I've built out. All nodes have SSDs attached via either USB or NVME / SATA. It's worth noting that the node that works properly (technicaldebtor) is an x86 Mac Mini running Ubuntu, and has only its internal SSD.

## Expected behavior

I'd sort of expect volumes to "just work" and replicas update in the background without degrading. 

## Support bundle for troubleshooting

[Support bundle!](https://shitposting.pictures/GX86xkrJSLw)

## Environment

 - Longhorn version: 
 - Impacted volume (PV): pvc-cdc7add6-3fda-424f-9897-ce7f46f79972
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 6
 - Node config
   - OS type and version: Debian 12 (raspian) and Ubuntu
   - Kernel version:
   - CPU per node: Raspberry PI 4s
   - Memory per node: 8GB on all Pi nodes, 16GB on Mac Mini
   - Disk type (e.g. SSD/NVMe/HDD): All SSDs, some attached via NVME except for aforementioned internal NVME disk on repurposed x86 Mac Mini
   - Network bandwidth between the nodes (Gbps): 1 Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 4

## Additional context

Storage disks are bind mounted since symlinks dislike Longhorn, apparently.

**Comment by QuinnyPig** [comment]
Found the problem; two nodes had /var/lib on a symlink instead of a bind mount. That... should probably be in the environment check somewhere.

**Comment by innobead** [comment]
> Found the problem; two nodes had /var/lib on a symlink instead of a bind mount. That... should probably be in the environment check somewhere.

@james-munson Please help check this to see if we need to update the env check.
