### ISSUE TITLE
Actual size of the volume is bigger than max size

### ISSUE THREAD

**Issue by Angelinsky7** [longhorn/longhorn#784]
Hi,
I discover that one of my volume is bigger that the size maximum size allowed. Is this normal ?
What can i do about it ? How is this even possible ?

Here some informations :
```
State: attached
Health:No node redundancy: all the healthy replicas are running on the same node healthy
Frontend:Block Device
Attached Node & Endpoint :
node01
/dev/longhorn/pvc-77d0fdfc0ab611e9
Size:8 Gi
Actual Size:37.6 Gi
Base Image:
Engine Image:rancher/longhorn-engine:v0.5.0
Created:9 months ago
Last Backup:
Last Backup At:
Namespace:prometheus
PVC Name:prometheus-server
PV Name:pvc-77d0fdfc0ab611e9
PV Status:Bound
Pod Name:prometheus-server-74b4655c7d-8x8jp
Pod Status:Running
Workload Name:prometheus-server-74b4655c7d
Workload Type:ReplicaSet
```
```
root@node01:/var/lib/rancher/longhorn/replicas# ls -l | grep pvc-77d0fdfc0ab611e9
drwxr-xr-x 2 root root 4096 Oct  1 03:15 pvc-77d0fdfc0ab611e9-4121b00b
drwxr-xr-x 2 root root 4096 Oct  1 03:26 pvc-77d0fdfc0ab611e9-cd981b3e
drwxr-xr-x 2 root root 4096 Oct  1 03:15 pvc-77d0fdfc0ab611e9-eaac43fb
```
```
root@node01:/var/lib/rancher/longhorn/replicas# du -h | grep pvc-77d0fdfc0ab611e9
38G     ./pvc-77d0fdfc0ab611e9-cd981b3e
38G     ./pvc-77d0fdfc0ab611e9-4121b00b
38G     ./pvc-77d0fdfc0ab611e9-eaac43fb
```

if you need more info or a bundle i will be happy to help.
Thanks for your amazing support

**Comment by yasker** [comment]
@Angelinsky7 There was a bug in v0.5.0 which prevents the snapshot purging from completion. You can try again later after upgrade to the upcoming v0.6.2 release.

One side note: if you only have one node in the cluster, it's unnecessary to have 3 replicas. Two would be enough even for the potential replica disk failure. But it's recommended to backup the volume to the outside of the cluster, just in case the disk failure.

**Comment by Angelinsky7** [comment]
@yasker ok, perfect, i'll update the issue when i'll go to 0.6.2
great thanks, i'll update to 2 replicas.
I backup with nfs every day my volume that hold data...

**Comment by yasker** [comment]
@Angelinsky7 Is the NFS server running inside the cluster or outside the cluster? I just want to make sure if the node's disk is gone then the NFS server still have the data.

**Comment by Angelinsky7** [comment]
@yasker :-)
outside :-) different machine, different hdd
thanks for your concern :-)
