### ISSUE TITLE
[BUG] Data Loss when Recreating Pods on ARM64

### ISSUE THREAD

**Issue by jroose** [longhorn/longhorn#7851]
## Describe the bug

When the pods for my postfix container are terminated and recreated on my arm64 nodes, the volume loses all data.    Works fine on x86-64.  This happens consistently on my cluster.  The disk faults and gets recreated.

## To Reproduce

1. Create a statefulset using a longhorn volume and have it run on an arm64 node
2. Write data to the volume
3. Delete a pod from the statefulset
4. Wait for volume to fault
5. Wait for pod to spin back up
6. Data is gone

## Expected behavior

Haz dataz

## Support bundle for troubleshooting

Will be emailed, if it ever completes

## Environment

K8s controller running on an athanaric node, other nodes are raspberry pi's.  

Longhorn version 1.6.0 (also an issue on 1.5.3), installed via kubectl with minimal customization
13 Longhorn volumes
Each node has a longhorn disk

```
(venv) c4a-admin@c4a-1:~/projects/src$ kubectl get nodes
NAME        STATUS   ROLES           AGE    VERSION
athanaric   Ready    control-plane   380d   v1.25.5 # AMD Ryzen 5 5600G with 16 GB of memory, zfs pool on NVME SSD's at /safe-2
c4a-1       Ready    <none>          380d   v1.25.5 # RPI 4 with 4 GB of memory and USB->SATA HDD mounted at /media/hdd
c4a-2       Ready    <none>          380d   v1.25.5 # RPI 4 with 4 GB of memory and USB->SATA HDD mounted at /media/hdd
c4a-3       Ready    <none>          380d   v1.25.5 # RPI 4 with 4 GB of memory and USB->SATA HDD mounted at /media/hdd
c4a-4       Ready    <none>          380d   v1.25.5 # RPI 4 with 4 GB of memory and USB->SATA HDD mounted at /media/hdd
c4a-5       Ready    <none>          380d   v1.25.5 # RPI 4 with 8 GB of memory and USB->SATA SSD mounted at /media/hdd
c4a-6       Ready    <none>          380d   v1.25.5 # RPI 4 with 8 GB of memory and USB->SATA SSD mounted at /media/hdd
c4a-7       Ready    <none>          380d   v1.25.5 # RPI 4 with 8 GB of memory and USB->SATA SSD mounted at /media/hdd
c4a-8       Ready    <none>          380d   v1.25.5 # RPI 4 with 8 GB of memory and USB->SATA SSD mounted at /media/hdd
scribe      Ready    <none>          336d   v1.25.5 # AMD Ryzen 7 3700X with 32 GB of memory, NVME SSD at /
```

c4a-*: Ubuntu 22.04.1, Linux c4a-1 5.15.0-1044-raspi,  Note: /var is a symlink to /media/hdd/var
athanaric: Ubuntu 20.04.6, Linux athanaric 5.4.0-170-generic
scribe: Ubuntu 20.04.6, Linux scribe 6.5.0-14-generic

Network bandwidth: c4a-* nodes have 1gbps links, athanaric and scribe and 10gbps links

Impacted volumes: pvc-c778c60f-9495-4a5c-b30b-53d69ee68b74, pvc-fc8162b5-fe8e-46db-84ab-1e7a7f0098a0

## Additional context
```
(venv) c4a-admin@c4a-1:~/projects/src/kubernetes-configs/longhorn$ diff 1.6.0/longhorn.yaml.1 longhorn.yaml
2,7d1
< # Builtin: "helm template" does not respect --create-namespace
< apiVersion: v1
< kind: Namespace
< metadata:
<   name: longhorn-system
< ---
4227c4221
<   name: longhorn-frontend
---
>   name: public
4230c4224
<   type: ClusterIP
---
>   type: LoadBalancer
4237c4231,4233
<     nodePort: null
---
>   - name: https
>     port: 443
>     targetPort: https
4560a4557,4568
>       - name: nginx-https
>         image: nginx
>         ports:
>         - containerPort: 80
>           name: http
>         - containerPort: 443
>           name: https
>         volumeMounts:
>         - name: nginx-config-https
>           mountPath: /etc/nginx
>         - name: nginx-certs
>           mountPath: /etc/nginx-tls
4567a4576,4581
>       - name: nginx-config-https
>         configMap:
>           name: longhorn-https-nginx-config
>       - name: nginx-certs
>         secret:
>           secretName: longhorn-https
```

**Comment by innobead** [comment]
@PhanLe1010 please follow up with this.

**Comment by jroose** [comment]
Partial event log posted above.  Faulted volume replicas were stored on the c4a Raspberry Pi nodes before and after build.

**Comment by jroose** [comment]
Actually, deleting pods on arm64 and recreating on arm64 also tends to hang for a long time, and eventually I give up and force delete the pods.  That's probably a separate issue though.

**Comment by jroose** [comment]
Support bundle completed, but it's ~400MB.  How should I get it to you?

**Comment by jroose** [comment]
I've uploaded the support bundle to my s3 bucket and emailed you a link to it.

**Comment by PhanLe1010** [comment]
Thanks @jroose 

Sorry for the delay. I am checking this ticket tomorrow PST time

**Comment by jroose** [comment]
Any luck?

**Comment by PhanLe1010** [comment]
Sorry @jroose I have not check this yet as busy on other task. I will be on this by end of today or tomorrow

**Comment by PhanLe1010** [comment]
Is it correct that `c4a` is ARM-64 while `athanaric` and `scribe` nodes are x86-64 ?

**Comment by jroose** [comment]
No worries!  I just wanted to make sure it didn't fall through the cracks.  Yes, you are correct that all 8 c4a nodes are arm64, while athanaric and scribe are x86-64.

**Comment by jroose** [comment]
@PhanLe1010 -- is there more information I can provide?
