### ISSUE TITLE
[BUG][v1.5.4-rc1] V2 volume have engine upgrade option on UI after upgrade from v1.5.3 to v1.5.4-rc1

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#7863]
## Describe the bug

After upgrade from v1.5.3 to v1.5.4-rc1, v2 volume displays engine upgrade available on UI.
![image](https://github.com/longhorn/longhorn/assets/73337386/51b95356-db9b-4dd2-84cb-bb4cc86a0d52)

The attached v2 volume(`pvc-c125e5d6-8313-4e40-b40a-61644c22180c`) will never complete engine upgrade, but detached volume(`test-v2`) can upgrade then attach to node success
![image](https://github.com/longhorn/longhorn/assets/73337386/17c9d71c-a721-4fed-820c-cec7bdcefcba)

## To Reproduce

1. Deploy Longhorn v1.5.3 setup v2 data engine environment
2. Have 1 attached v2 volume. 1 detached v2 volume.
3. Upgrade Longhorn to v1.5.4-rc1
4. UI displays engine upgrade available.

## Expected behavior

UI not displays engine upgrade on v2 volumes.

## Support bundle for troubleshooting

N/A

## Environment

 - Longhorn version: v1.5.4-rc1
 - Impacted volume (PV): pvc-c125e5d6-8313-4e40-b40a-61644c22180c
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.28.5+k3s1

## Additional context

https://github.com/longhorn/longhorn/issues/7445
https://github.com/longhorn/longhorn/issues/7489

**Comment by derekbit** [comment]
Related to https://github.com/longhorn/longhorn-ui/pull/677

**Comment by innobead** [comment]
@scures Please help with this. Thanks.

**Comment by innobead** [comment]
@scures In 1.5, the attribute is not `dataEngine` but still `backendStoreDriver`.

**Comment by innobead** [comment]
> > backendStoreDriver
> 
> What's the value of that? I have no environment (trying to get one up) to test it.

Can you setup the env as what you did for 1.6.0? How you tested it before in 1.6.0?

**Comment by innobead** [comment]
If need any help, drop a message to the team channel.

**Comment by innobead** [comment]
Any updates @scures ?

**Comment by innobead** [comment]
Thanks @scures

**Comment by chriscchien** [comment]
Verified **pass** on longhorn v1.5.x (longhorn-ui `82d88a`)

Upgrade from v1.5.3 to v1.5.x-head, v2 volume does not have engine upgrade icon and the "Upgrade Engine" option is grayed out.

![image](https://github.com/longhorn/longhorn/assets/73337386/7102086c-97b9-4083-8991-adf342f109ce)
