### ISSUE TITLE
[BUG] Unable to drain a node

### ISSUE THREAD

**Issue by Heracles31** [longhorn/longhorn#7873]
## Describe the bug

When trying to drain a node, the process loops indefinitely saying that :
error when evicting pods/"instance-manager-0c5def90bc053d1f0f1c42165eb76338" -n "longhorn-system" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.

I searched and found a few infos but nothing to help me handle this.

In this debug :
https://docs.harvesterhci.io/v1.2/upgrade/v1-1-to-v1-1-2/

I did not match the case at step 6.5 ; the output returned the same node that can not drain.

I also found this :
https://github.com/longhorn/longhorn/issues/2639

But that refers to old stuff that should be fixed in the latest version that I use (1.5.3)

There was also reference to volume associated with more than 1 process. Here, indeed I have such a pvc but it is meant to be. It is ReadWriteMany and for my PI-Hole setup. First PI-Hole pod is single replica and mounts it as RW. The second pod has 3 replicas and they mount the volume as RO.

The only thing different that I did recently is that I accidently deleted the PVC associated with a POD instead of just the POD. As such, I had to restore a backup Longhorn took 12 hours sooner in the morning. The restored process went well but there was some problems re-attaching the volume to the re-created pod. I ended up doing it with a few trial and errors and that restored pod / restored volume are working perferctly since that. (A single replica pod mounting the PVC as ReadWriteOnce and RW).

Every volume exist in 3 replicas. The ones mounted by PI-Hole are from node 1, 3 and 4 while the node that can not drain is node 5.

The volume that has been restored and re-mounted is indeed present in node 5, but is also healthy and in nodes 1 and 4. The corresponding pod is running from node 1 as of now.

I tried to uncordon the node, let it rest a little while and re-cordon it. No progress.

I evicted myself as many pods as possible from that node, again without success.

## To Reproduce

Not sure what exactly caused that because I managed to drain all my nodes (one by one of course!) in the past.

kubectl drain --ignore-daemonsets --delete-emptydir-data kube-w5

The activity related to the RWX and the backup / restore / re-attached are the main suspect.

## Expected behavior

To be able to drain all my nodes or at least, an error message that would be explicit enough for me to fix...

## Support bundle for troubleshooting

Bundle sent by email as requested

## Environment

 - Longhorn version: 
 1.5.3
 - Impacted volume (PV): 
 problem is about instancemanager pod that can not be evicted. Not a specific volume or PVC...

 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
kubectl

 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
1.29.1

   - Number of control plane nodes in the cluster:
3
   - Number of worker nodes in the cluster:
6

 - Node config
   - OS type and version:
 Ubuntu 22.04

   - Kernel version:
root@kube-w5:~# uname -a
Linux kube-w5 5.15.0-92-generic #102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
   - CPU per node:
8
   - Memory per node:
16
   - Disk type (e.g. SSD/NVMe/HDD):
Virtual drives from ESXi 6.7 U3 ; ESXi datastore itself is from standard spinning drives
   - Network bandwidth between the nodes (Gbps):
ESXi internal virtual network (in theory, 1000Mbps)
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
ESXi 6.7U3 latest patch relase 
- Number of Longhorn volumes in the cluster:
10

## Additional context

A single RWX pvc that seems to be completely unrelated.
kubectl get -n longhorn-system -o yaml lhim | grep 'name:.*-e-' | sort | uniq -c
      1           name: pvc-14a648e2-3a2e-4656-9227-33abe3a2d77a-e-0
      1           name: pvc-17d303ba-6bf4-44b0-af58-04524241358f-e-0
      1           name: pvc-52b28c56-4491-470d-bb91-001a63bdca49-e-0
      1           name: pvc-57c0eacd-a383-4810-b256-8c221d30e429-e-0
      1           name: pvc-5adbfa3b-a51c-4df2-aa5a-ded9bd776229-e-0
      1           name: pvc-66804b8f-cd24-4f37-9b13-2245043ab1f4-e-0
      1           name: pvc-6cd0c245-f755-4400-8035-44c3a8e96053-e-0
      1           name: pvc-ad3256bf-e3ac-413e-b4ca-787ec491617b-e-0
      1           name: pvc-e8712eae-f498-4fe9-a7e5-d11131b9b2b1-e-0
      2           name: pvc-f45913d3-f07b-494a-83e5-a8d66aa03284-e-0

A restored volume that is working and has 1 of its 3 replicas in the problematic node but again, seems unrelated.
State: Attached
Health:
Healthy
Ready for workload:Ready
Conditions:
Frontend:Block Device
Backend Data Engine:v1
Offline Replica Rebuilding:disabled
Attached Node & Endpoint:
kube-w4
/dev/longhorn/pvc-ad3256bf-e3ac-413e-b4ca-787ec491617b
Size:
35 Gi
Actual Size:10.4 Gi
Data Locality:best-effort
Access Mode:ReadWriteMany
Engine Image:longhornio/longhorn-engine:v1.5.3
Created:a day ago
Encrypted:False
Node Tags:
Disk Tags:
Last Backup:backup-1fa398974c3c4874
Last Backup At:16 hours ago
Replicas Auto Balance:ignored
Snapshot Data Integrity:ignored
Instance Manager:
instance-manager-91b5f39fff6515f409a8c671741f82b4
Allow snapshots removal during trim:ignored
Replica Soft Anti Affinity:ignored
Replica Zone Soft Anti Affinity:ignored
Namespace:prod-services
PVC Name:lh-pvc-posteio
PV Name:pvc-ad3256bf-e3ac-413e-b4ca-787ec491617b
PV Status:Bound
Revision Counter Disabled:False
Pod Name:posteio-b7bffbc5f-2m6cz
Pod Status:Running
Workload Name:posteio-b7bffbc5f
Workload Type:ReplicaSet

**Comment by Heracles31** [comment]
I went with my upgrade and did the last of my worker (w6). It went well like all other nodes. I came back to Worker 5 and tried to drain it again. No luck. I then decided that kicking out the pod myself manually in the actual state would already be much less risky than a power failure. Node was drained to the lowest minimum, all volumes were replicated to 3 copies and healthy. All other nodes were up and running, all other processes and instances were up and running....

It worked. I did a kubectl delete pod -n longhorn-system **instance-manager's pod name** and it worked. The node being cordoned, it was not re-created. I did my upgrade, rebooted, uncordoned the node and everything seems Ok.

One more note is that I was doing that to add some disk space in the nodes. They were up to around 80% of used space in the root file system. Node 5 was not the worst of them (around 78 while 6 and 4 were over 80% each) but still, that condition was sub-optimal. It would not justify the problem but we never know...

**Comment by SPodjasek** [comment]
I've had the same issue on one of the worker nodes during cluster upgrade with Longhorn 1.5.5.
Instance manager eviction was blocked by PDB, despite that no 'last healthy replica' was located on this node. After forcefully killing the pod and restarting the node (OS updates) it started fine after reboot and replicas rebuilt as expected.
