### ISSUE TITLE
The instance manager's log is flooded by the error message when it fails to start a process

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#788]
```
[instance-manager-r-ed1b4b33] [longhorn-instance-manager] time="2019-10-03T22:44:15Z" level=info msg="wait for gRPC service of process test1-r-4660f6e2 to start"
[instance-manager-r-ed1b4b33] [longhorn-instance-manager] time="2019-10-03T22:44:16Z" level=info msg="wait for gRPC service of process test1-r-4660f6e2 to start"
[instance-manager-r-ed1b4b33] [longhorn-instance-manager] time="2019-10-03T22:44:17Z" level=info msg="wait for gRPC service of process test1-r-4660f6e2 to start"
[instance-manager-r-ed1b4b33] [longhorn-instance-manager] time="2019-10-03T22:44:18Z" level=info msg="wait for gRPC service of process test1-r-4660f6e2 to start"
[instance-manager-r-ed1b4b33] [longhorn-instance-manager] time="2019-10-03T22:44:19Z" level=info msg="wait for gRPC service of process test1-r-4660f6e2 to start"
```

May need to adjust the wait interval: https://github.com/longhorn/longhorn-instance-manager/blob/f83d29eee6b9451fe5aae1843fa0c2907fd31ffa/process/healthchecker.go#L28

**Comment by yasker** [comment]
Weird, it shouldn't take more than a couple of seconds to start the replica. 5 seconds is long.

**Comment by shuo-wu** [comment]
In this case, instance manager cannot launch replica processes due to some issues. e.g.: https://github.com/longhorn/longhorn/issues/776. Then the log is flooded by this message.

**Comment by yasker** [comment]
In fact, the log is useful since it indicates there is a problem. We can move it to the debug level. Increase the wait interval won't solve the problem: there is little difference between 1 second or 10 seconds if you run it for days but the later can cause 10 seconds delay in starting the process.

**Comment by yasker** [comment]
The solution, for now, would be moving the log to the debug level.

**Comment by yasker** [comment]
If the process is already stopped, `waiting for GRPC` should be stopped as well.

**Comment by yasker** [comment]
Should be fixed by https://github.com/longhorn/longhorn-engine/commit/06d8188ebbf054de39a727bb89ad53fdf2678223 .

Feel free to reopen if it happens again.
