### ISSUE TITLE
[IMPROVEMENT] Helm Chart: Support Gateway API and improve Ingress

### ISSUE THREAD

**Issue by e3b0c442** [longhorn/longhorn#7889]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)
The Ingress implementation in the Helm chart is lacking. The ability to set multiple hosts with different parameters is absent, and the pathType field is hardcoded to `ImplementationSpecific` when it should be configurable. This causes problems with certain Ingress implementations such as Cilium.

Additionally, Gateway API has achieved 1.0, it would be prudent to add Gateway/HTTPRoute support as well given the stated intent that the Gateway API will replace Ingress as the preferred cluster ingress API.

## Describe the solution you'd like
Improve the Ingress implementation to allow full customization of the Ingress, and add support for HTTPRoute resources as well.

## Describe alternatives you've considered
The resources can be created manually, but the ergonomics of having them included in the Helm chart are superior.

## Additional context
n/a

**Comment by roger-ryao** [comment]
**Verified on master-head 20240422**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/1ec78ab56dfa029bef67e1565abb33b7be26d0f5

**The test steps**
https://github.com/longhorn/longhorn/issues/7889#issuecomment-2062795902

**Result Passed**

1. Install Longhorn by modifying the parameter `ingress.pathType` to `Exact` in the `values.yaml` file with Helm. Longhorn components are working well.
2. Upgrade Longhorn by modifying the parameter `ingress.pathType` to `Prefix` in the `values.yaml` file with Helm. Longhorn components are working well.
3. require/doc : 
    - https://github.com/longhorn/longhorn/pull/8398
    - https://github.com/longhorn/website/pull/897
