### ISSUE TITLE
The crashed processes in instance manager cannot be cleaned up

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#789]
```
[longhorn-manager-hsr25] time="2019-10-03T23:17:18Z" level=warning msg="instance test1-r-23a45ddf state is error, error message exit status 1"
[longhorn-manager-hsr25] time="2019-10-03T23:17:18Z" level=warning msg="Instance test1-r-23a45ddf crashed on Instance Manager instance-manager-r-ecbae79b at shuo-longhorn-cluster-2-node-3, try to get log"
[longhorn-manager-hsr25] time="2019-10-03T23:17:18Z" level=warning msg="cannot get crash log for instance test1-r-23a45ddf on Instance Manager instance-manager-r-ecbae79b at shuo-longhorn-cluster-2-node-3, error cannot find Instance Manager "
```

The key point of this issue: 
The `instanceManagerName` will be unset when the engine/replica becomes state `error`. Then when we detach this errored volume, the instance handler will directly mark the engine/replicas as state `stopped` without sending a request to clean up the errored processes. 
Later if we want to re-attach the volume, the instance manager will find that there is already an existing errored process hence it will do nothing for the re-attach. This volume cannot become `attached` anymore.

**Comment by shuo-wu** [comment]
Reproduce steps:
0. Newly created cluster(or remove directory `/var/lib/rancher/longhorn/replicas/` for each nodes); 3 nodes cluster
1. Deploy Longhorn v0.5.0 and wait for `active`
2. Upgrade to v0.6.1 and wait for `active`
3. Create and attach a volume. This volume will get stuck in `attaching` state since issue #776 is triggered. Detach this stuck volume
4. Upgrade to 
  4.1. the version that doesn't fix this issue. Scenario 1:
      4.1.1 Check instance manager with command `kubectl -n longhorn-system get instancemanager instance-manager-r-<xxxxxxx> -o yaml`. Then you will see `status.instances` contains `error` instance
      4.1.2 Re-attach the volume. The volume still get stuck in `attaching` state
  4.2 the version that fixs this issue. Scenario 2:
      4.2.1 No `error` instance in the instance manager
      4.2.2 The volume should be able to attach

**Comment by shuo-wu** [comment]
The fix for this issue may have huge potential impacts. We need to test all kinds of cases for it. e.g. online upgrade, offline upgrade, node down, etc.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Additional tests:
  - Engine image upgrade scenario (online & offlline).  **PASSED**
  - Node down scenario. **PASSED**
