### ISSUE TITLE
[IMPROVEMENT] Use HEAD instead of a GET to fetch the `Content-Length` of an resource via URL

### ISSUE THREAD

**Issue by votdev** [longhorn/longhorn#7892]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The function [GetSizeFromURL](https://github.com/longhorn/backing-image-manager/blob/b3275a8e7c12f66d6450c4430b854916623046f9/pkg/sync/handler.go#L37) is used to get the size of file that is accessible via a specific URL. The current implementation is using a GET request to only get the `Content-Length` header. This is too expensive because the whole content body is downloaded, which is really huge in case of an ISO image for example.

## Describe the solution you'd like

Use a HEAD request which retrieves only the headers of the resource without the body. This will save bandwidth and time.

## Describe alternatives you've considered

n/a

## Additional context

n/a

**Comment by votdev** [comment]
Even if Go only downloads the body for a GET request when the body-reader is used; it is still wrong and a HEAD request should be used instead.

**Comment by innobead** [comment]
@votdev Please update the zenhub status to ready for testing and provide the test steps for QA.

**Comment by innobead** [comment]
@votdev please update this comment, https://github.com/longhorn/longhorn/issues/7892#issuecomment-1953580230, so QA will know how to test it.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (backing-image-manager `5c9b6e`)

Following test [steps](https://github.com/longhorn/backing-image-manager/pull/180#issuecomment-1954241342), the bcaking image can download without problem.
