### ISSUE TITLE
[BUG] Add Snapshot Maximum Count to the Settings

### ISSUE THREAD

**Issue by yardenshoham** [longhorn/longhorn#7906]
## Describe the bug

This setting is missing

## Additional context

https://github.com/longhorn/longhorn/pull/7896
https://github.com/longhorn/longhorn/issues/7894

**Comment by innobead** [comment]
@FrankYang0529 Please help drive this to ready for testing. Thanks.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240312**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/88c49e7416c9da25f1c125780e7de2026e92d7d8


**The test steps**

https://github.com/longhorn/longhorn/issues/7906#issuecomment-1953861910

**Result Passed**

- [x] Install LH via helm chart without error.
- [x] require/chart :  Installed Longhorn using Helm chart and modified `snapshotMaxCount` to `10`, and it took effect.
![Screenshot_20240312_121304](https://github.com/longhorn/longhorn/assets/104337648/1b9ae192-81bd-48cf-bd87-5885d0421a59)
