### ISSUE TITLE
[BUG] persistence.removeSnapshotsDuringFilesystemTrim Helm variable is unreferenced

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#7909]
## Describe the bug

https://github.com/longhorn/longhorn/pull/4919/files added two new Helm variables related to filesystem trim:

- `defaultSettings.removeSnapshotsDuringFilesystemTrim` is referenced in `chart/templates/default-setting.yaml`.
- `persistence.removeSnapshotsDuringFilesystemTrim` should probably be referenced in `chart/templates/storageclass.yaml`, but actually isn't referenced anywhere.

## Expected behavior

Either `persistence.removeSnapshotsDuringFilesystemTrim` should be referenced or it should be removed.

To be honest, I'm not sure of the value it provides. It makes sense to be able to specify `unmapMarkSnapChainRemoved` in user-created StorageClasses, since that setting may or may not be desired for different workloads. However, if a user just wants to enable or disable the behavior by default, the default setting should suffice.

**Comment by ejweber** [comment]
Thanks @yardenshoham for the submission. I reviewed and approved the PR, but will need another maintainer to merge it. I'll help shepherd it through the QA and backport process.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240417**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/cb95df3760984bbfeb18e1c4b7d5c2f7a405800d

**The test steps**

https://github.com/longhorn/longhorn/issues/7909#issuecomment-1948634684

**Result Passed**

Default case
1. `master-head`
2. `v1.6.1` upgrade to `master-head`

Non-default case
1. `master-head`
2. `v1.6.1` upgrade to `master-head`
