### ISSUE TITLE
[REFACTOR] Longhorn CRD structural schema

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#791]
We're considering adopting OpenAPI v3 with Kubernetes CRD, transiting from the current Rancher API framework.

The main motivation is to support editing CRD. In order to do so, we might need to implement the validation hook as well as find ways to replace snapshot/backup creation calls - since those are actions, not declarations. 

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] CRD structural schema https://kubernetes.io/blog/2019/06/20/crd-structural-schema/
- [x] Update the auto-gen script (auto-install the specific tool version)
- [x] Validating/Mutating Webhook #3241

**Comment by shuo-wu** [comment]
Need to consider the node selector and disk selector during the refactoring: https://github.com/longhorn/longhorn/issues/2179

**Comment by innobead** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Main-Board-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/791?planning-poker) with ZenHub @jenting @PhanLe1010 @shuo-wu @joshimoo

**Comment by jenting** [comment]
I'll implement the CRD structural schema first by leveraging controller-gen.

**Comment by jenting** [comment]
The controller-gen is working with adding the kubebuilder marker, also we change to use [generate-group.sh](https://github.com/kubernetes/code-generator/blob/v0.18.0/generate-groups.sh) script instead of manually installing the binaries `deepcopy-gen`, `client-gen`, `lister-gen`, `informer-gen`.

**Comment by innobead** [comment]
> The controller-gen is working with adding the kubebuilder marker, also we change to use [generate-group.sh](https://github.com/kubernetes/code-generator/blob/v0.18.0/generate-groups.sh) script instead of manually installing the binaries `deepcopy-gen`, `client-gen`, `lister-gen`, `informer-gen`.
> 
> It's now under basic E2E test.

So longhorn-manager/k8s/generate_code.sh will be updated accordingly?

**Comment by jenting** [comment]
Yes, you could check the draft PR if you're interested https://github.com/longhorn/longhorn-manager/blob/7f0ccd7452a4f27c0acdbce8946a511376bd351d/k8s/generate_code.sh

**Comment by jenting** [comment]
@yung reminds me that it's better to make `kubectl explain <crd>` work to explain have a description of each field.

**Comment by jenting** [comment]
Run the E2E `coretest`, all good.

**Comment by jenting** [comment]
The test steps are to make sure after the Longhorn CRD structural schema, it won't trigger any E2E test case test result from PASS to FAILED.

**Comment by kaxing** [comment]
Validating in progress, with master-head

Now `kubectl explain CR-name` will show the relevant information:
```console
$ kubectl explain volume -n longhorn-sysytem
KIND:     Volume
VERSION:  longhorn.io/v1beta2

DESCRIPTION:
     Volume is where Longhorn stores volume object.

FIELDS:
   apiVersion	<string>
     APIVersion defines the versioned schema of this representation of an
     object. Servers should convert recognized schemas to the latest internal
     value, and may reject unrecognized values. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources

   kind	<string>
     Kind is a string value representing the REST resource this object
     represents. Servers may infer this from the endpoint the client submits
     requests to. Cannot be updated. In CamelCase. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

   metadata	<Object>
     Standard object's metadata. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata

   spec	<Object>
     VolumeSpec defines the desired state of the Longhorn volume

   status	<Object>
     VolumeStatus defines the observed state of the Longhorn volume
```

Also editing the CR directly with invalid value will give hints, for example:
```yaml
# nodes.longhorn.io "c1-control" was not valid:
# * status.conditions: Invalid value: "object": status.conditions in body must be of type array: "object"
# * status.diskStatus.default-disk-b68a3c1e46694a56.conditions: Invalid value: "object": status.diskStatus.default-disk-b68a3c1e46694a56.conditions in body must be of type array: "object"
# * spec.disks.default-disk-b68a3c1e46694a56.tags: Invalid value: "null": spec.disks.default-disk-b68a3c1e46694a56.tags in body must be of type array: "null"
#
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  creationTimestamp: "2022-01-07T05:40:43Z"
  finalizers:
  - longhorn.io
  generation: 1
  name: c1-control
  namespace: longhorn-system
  resourceVersion: "42118"
  selfLink: /apis/longhorn.io/v1beta2/namespaces/longhorn-system/nodes/c1-control
  uid: e6bede72-156e-4b90-bcf1-ac9b68a0c627
…
```

**Comment by jenting** [comment]
> Now kubectl explain CR-name will show the relevant information:

To be honest, you could explain more detailed fields, for example:
```shell
kubectl explain recurringjobs.longhorn.io.spec.retain
```
