### ISSUE TITLE
[BUG] One host cannot mount volumes

### ISSUE THREAD

**Issue by dlford** [longhorn/longhorn#7913]
## Describe the bug

I have a running 8 node cluster with 5 storage/worker nodes and 3 control plane nodes. One worker/storage node is unable to attach volumes.

## To Reproduce

Unsure on this one, the affected node is running mostly different hardware, not sure if that could be the cause though.

Majority of nodes (kube1-7):

- HP ProDesk 700g3 mini
- Intel i5-7500t
- 4 threads
- 32Gi RAM
- No GPU

Affected node (jack):

- Custom built PC
- AMD Threadripper 1950x
- 32 threads
- 94Gi RAM
- NVIDIA 1080ti GPU running NVIDIA Container Toolkit and GPU Operator

## Expected behavior

All nodes able to mount volumes.

## Support bundle for troubleshooting

https://drive.google.com/file/d/1ygoRUfQpKNWUXaEQU25b37puM3k3Wzgo/view?usp=sharing

## Environment

 - Longhorn version: 1.6.0
 - Impacted volume (PV): pvc-eeb3dea6-66ce-4886-afcb-641c3a7855d4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K8s v1.29.1, containerd 1.6.28
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 5
 - Node config
   - OS type and version: Ubuntu 22.04
   - Kernel version: 5.15.0-94-generic
   - CPU per node: 1 (4 thread), (32 thread on affected node)
   - Memory per node: 32Gi (94Gi on affected node)
   - Disk type (e.g. SSD/NVMe/HDD): 2.5" SSD
   - Network bandwidth between the nodes (Gbps): 1
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 28

## Additional context

Here is the output of the `share-manager-pvc-eeb3dea6-66ce-4886-afcb-641c3a7855d4` pod on the affected node, which continues to restart and fail in the same way:

```
time="2024-02-11T21:40:41Z" level=info msg="starting RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
time="2024-02-11T21:40:41Z" level=info msg="Ending RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
time="2024-02-11T21:40:41Z" level=info msg="Listening on share manager gRPC server :9600" func=cmd.start.func2 file="server.go:134"
time="2024-02-11T21:40:41Z" level=info msg="Volume pvc-eeb3dea6-66ce-4886-afcb-641c3a7855d4 device /dev/longhorn/pvc-eeb3dea6-66ce-4886-afcb-641c3a7855d4 contains filesystem of format crypto_LUKS" encrypted=true volume=pvc-eeb3dea6-66ce-4886-afcb-641c3a7855d4
time="2024-02-11T21:40:41Z" level=info msg="Volume pvc-eeb3dea6-66ce-4886-afcb-641c3a7855d4 requires crypto device /dev/mapper/pvc-eeb3dea6-66ce-4886-afcb-641c3a7855d4" encrypted=true volume=pvc-eeb3dea6-66ce-4886-afcb-641c3a7855d4
time="2024-02-11T21:40:41Z" level=debug msg="Device /dev/mapper/pvc-eeb3dea6-66ce-4886-afcb-641c3a7855d4 is not an active LUKS device" func=crypto.DeviceEncryptionStatus file="crypto.go:89" error="failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/2926984/ns/mnt --ipc=/host/proc/2926984/ns/ipc cryptsetup status pvc-eeb3dea6-66ce-4886-afcb-641c3a7855d4], output /dev/mapper/pvc-eeb3dea6-66ce-4886-afcb-641c3a7855d4 is inactive.\n, stderr : exit status 4"
time="2024-02-11T21:40:41Z" level=debug msg="Opening device /dev/longhorn/pvc-eeb3dea6-66ce-4886-afcb-641c3a7855d4 with LUKS on pvc-eeb3dea6-66ce-4886-afcb-641c3a7855d4" func=crypto.OpenVolume file="crypto.go:45"
```

**Comment by Isotop7** [comment]
Can you reproduce it on kernel 5.15.0-92? -94 seems to have a regression which makes detecting attached drives buggy.

**Comment by dlford** [comment]
@Isotop7 I'm not sure that's related as all hosts are running -94 and only the one host is affected, but I'll see if I can try to downgrade this weekend and re-test.

**Comment by ArthurVardevanyan** [comment]
Are you using network policies?

I ran into the same issue and had to update my network policies after looking at network traffic logs: https://github.com/ArthurVardevanyan/HomeLab/commit/6a491dfacbc57985c7cf097aa08eb66dce03f089

Regardless I think both my policies and the official policies may be out of date:
Mine: https://github.com/ArthurVardevanyan/HomeLab/tree/main/kubernetes/longhorn/base/network-policy
Official: https://github.com/longhorn/longhorn/tree/master/examples/network-policy

I saw/seeing the same issue post 1.6.0 Upgrade.

Kubernetes ```v1.28.6+f1618d5```
Distribution: ```4.15.0-0.okd-2024-02-10-035534```
Kernel: ```6.6.9-200.fc39.x86_64```
OS: ```Fedora CoreOS 39.20240112.3.0```
Cluster Type: Hypervised on KVM with NVME Drives Passed into the VM. 



![Screenshot from 2024-02-24 09-51-42](https://github.com/longhorn/longhorn/assets/21159051/7161eb57-7001-404a-b1ed-524c241cba3d)
![image](https://github.com/longhorn/longhorn/assets/21159051/761a7f71-1601-4037-9932-9735223f563f)

**Comment by dlford** [comment]
I have network policies disabled.

I Haven't had a chance to look at this again, sorry about that. I'll be upgrading to the latest kernel next week on all nodes and will report back.
