### ISSUE TITLE
[BUG] Deadlock is possible in v1.6.0 instance manager

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#7919]
## Describe the bug

This issue was originally reported by @eilyre in https://github.com/longhorn/longhorn/issues/7915. I am distilling it down to the root cause here.

It is possible for the v1.6.0 instance manager to experience a deadlock.

Every 10 seconds, `checkMountPointStatusForEngine` obtains the `pm.lock`. It may not give it up until it sends to `p.UpdateCh`.

https://github.com/longhorn/longhorn-instance-manager/blob/6372baca91084d36461ea860f8e7b45115a1a858/pkg/process/process_manager.go#L138-L151

`p.UpdateCh` is actually just `pm.processUpdateCh`.

https://github.com/longhorn/longhorn-instance-manager/blob/6372baca91084d36461ea860f8e7b45115a1a858/pkg/process/process_manager.go#L303

Each time it receives from `pm.processUpdateCh`, ProcessManager must obtain `pm.lock`. 

https://github.com/longhorn/longhorn-instance-manager/blob/6372baca91084d36461ea860f8e7b45115a1a858/pkg/process/process_manager.go#L102-L104

We cannot receive from `pm.processUpdateCh` without obtaining `pm.lock`, but we cannot relinquish `pm.lock` until `pm.processUpdateCh` is clear.

@eilyre provided a goroutine dump that demonstrated the deadlock. There were thousands of goroutines waiting for the `pm.Lock` and the following two goroutines stuck as described above:

```
goroutine 185 [chan send, 5653 minutes]:
github.com/longhorn/longhorn-instance-manager/pkg/process.(*Manager).checkMountPointStatusForEngine(0xc0005cc700)
	/go/src/github.com/longhorn/longhorn-instance-manager/pkg/process/process_manager.go:149 +0x13b
github.com/longhorn/longhorn-instance-manager/pkg/process.(*Manager).startInstanceConditionCheck(0xc0005cc700)
	/go/src/github.com/longhorn/longhorn-instance-manager/pkg/process/process_manager.go:130 +0xe6
created by github.com/longhorn/longhorn-instance-manager/pkg/process.NewManager in goroutine 1
	/go/src/github.com/longhorn/longhorn-instance-manager/pkg/process/process_manager.go:90 +0x365

goroutine 184 [sync.RWMutex.RLock, 5653 minutes]:
sync.runtime_SemacquireRWMutexR(0xc0008d29a0?, 0x58?, 0xc003518340?)
	/usr/local/go/src/runtime/sema.go:82 +0x25
sync.(*RWMutex).RLock(...)
	/usr/local/go/src/sync/rwmutex.go:71
github.com/longhorn/longhorn-instance-manager/pkg/process.(*Manager).startMonitoring(0xc0005cc700)
	/go/src/github.com/longhorn/longhorn-instance-manager/pkg/process/process_manager.go:104 +0xf3
created by github.com/longhorn/longhorn-instance-manager/pkg/process.NewManager in goroutine 1
	/go/src/github.com/longhorn/longhorn-instance-manager/pkg/process/process_manager.go:89 +0x325
```

## To Reproduce

I couldn't easily reproduce it without modifying instance-manager code to make it more likely.

1. Deploy Longhorn with the following. The custom instance-manager changes `MountCheckInterval` to `250 ms` (from `10 s`).

```
helm upgrade --namespace longhorn-system longhorn ./chart --set image.longhorn.instanceManager.repository=webericjames/longhorn-instance-manager,image.longhorn.instanceManager.tag=v5_20240213_short_mountCheckInterval_logging,preUpgradeChecker.upgradeVersionCheck=false,image.pullPolicy=Always
```

2. Modify `examples/statefulset.yaml with the following. This hammers a single node with parallel pod creations and deletions.

```
  replicas: 20 # default is 1
  podManagementPolicy: Parallel

      nodeSelector: 
        kubernetes.io/hostname: eweber-v126-worker-9c1451b4-kgxdq # some node in the cluster
```

3. Apply `examples/statefulset.yaml`.
4. Run the following script.

```
i=1; while true; echo $i; i=$((i+1)); do kubectl delete -f examples/statefulset.yaml; sleep 15; kubectl apply -f examples/statefulset.yaml; sleep 15; done
```

5. Watch the Longhorn UI. Eventually, all volumes will be stuck detaching. It can take many iterations. In my most recent attempt, it took eight.

```
...
8
service "nginx" deleted
statefulset.apps "web" deleted
service/nginx created
statefulset.apps/web created
```

6. Set up a port forward to the instance manager's pprof endpoint.

```
eweber@laptop:~/longhorn> kl port-forward instance-manager-95b4f71659737f4e85d565d375f3fca1 6060:6060
Forwarding from 127.0.0.1:6060 -> 6060
Forwarding from [::1]:6060 -> 6060
```

7. Confirm the symptoms at http://localhost:6060/debug/pprof/goroutine?debug=2.

```
goroutine 364724 [sync.Mutex.Lock, 9 minutes]:
sync.runtime_SemacquireMutex(0x7fc438589a68?, 0x30?, 0xc0000fc000?)
	/usr/local/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00003e270)
	/usr/local/go/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0xa707e2?)
	/usr/local/go/src/sync/rwmutex.go:147 +0x31
github.com/longhorn/longhorn-instance-manager/pkg/process.(*Manager).unregisterProcess.func1.1(0xc000528780, 0xc0008f40e0)
	/go/src/github.com/longhorn/longhorn-instance-manager/pkg/process/process_manager.go:334 +0x3e
github.com/longhorn/longhorn-instance-manager/pkg/process.(*Manager).unregisterProcess.func1()
	/go/src/github.com/longhorn/longhorn-instance-manager/pkg/process/process_manager.go:342 +0x13d
created by github.com/longhorn/longhorn-instance-manager/pkg/process.(*Manager).unregisterProcess in goroutine 364697
	/go/src/github.com/longhorn/longhorn-instance-manager/pkg/process/process_manager.go:319 +0x147

goroutine 12 [chan send, 9 minutes]:
github.com/longhorn/longhorn-instance-manager/pkg/process.(*Manager).checkMountPointStatusForEngine(0xc000528780)
	/go/src/github.com/longhorn/longhorn-instance-manager/pkg/process/process_manager.go:149 +0x189
github.com/longhorn/longhorn-instance-manager/pkg/process.(*Manager).startInstanceConditionCheck(0xc000528780)
	/go/src/github.com/longhorn/longhorn-instance-manager/pkg/process/process_manager.go:130 +0x11c
created by github.com/longhorn/longhorn-instance-manager/pkg/process.NewManager in goroutine 1
	/go/src/github.com/longhorn/longhorn-instance-manager/pkg/process/process_manager.go:90 +0x3a5

goroutine 11 [sync.RWMutex.RLock, 9 minutes]:
sync.runtime_SemacquireRWMutexR(0xc0000227e0?, 0x58?, 0xc00003cdb0?)
	/usr/local/go/src/runtime/sema.go:82 +0x25
sync.(*RWMutex).RLock(...)
	/usr/local/go/src/sync/rwmutex.go:71
github.com/longhorn/longhorn-instance-manager/pkg/process.(*Manager).startMonitoring(0xc000528780)
	/go/src/github.com/longhorn/longhorn-instance-manager/pkg/process/process_manager.go:104 +0x133
created by github.com/longhorn/longhorn-instance-manager/pkg/process.NewManager in goroutine 1
	/go/src/github.com/longhorn/longhorn-instance-manager/pkg/process/process_manager.go:89 +0x365
```

## Expected behavior

No deadlock occurs. This is the only bit of code that sends to the update channel under a lock. It's likely we can just modify that behavior.

## Support bundle for troubleshooting

See https://github.com/longhorn/longhorn/issues/7915.

## Environment

Longhorn version: v1.6.0

See https://github.com/longhorn/longhorn/issues/7915.

## Additional context

The locking issue is a bit more complicated in the details than I initially supposed. In both of the code locations I identified above, we need to obtain a read lock with `sync.RWMutex.RLock`. Usually, two readers should both be able to obtain the lock simultaneously, leading to no deadlocking issue. However, in the goroutine dump, we also see the following goroutine:

```
goroutine 174521414 [sync.RWMutex.Lock, 5653 minutes]:
sync.runtime_SemacquireRWMutex(0x44674b?, 0x78?, 0x446780?)
	/usr/local/go/src/runtime/sema.go:87 +0x25
sync.(*RWMutex).Lock(0xc003f067c8?)
	/usr/local/go/src/sync/rwmutex.go:152 +0x6a
github.com/longhorn/longhorn-instance-manager/pkg/process.(*Manager).unregisterProcess(0xc0005cc700, 0xc0008d29a0)
	/go/src/github.com/longhorn/longhorn-instance-manager/pkg/process/process_manager.go:310 +0x34
github.com/longhorn/longhorn-instance-manager/pkg/process.(*Manager).ProcessDelete(0x1029e80?, {0xc00350c340?, 0x508886?}, 0xc00350c340)
	/go/src/github.com/longhorn/longhorn-instance-manager/pkg/process/process_manager.go:284 +0xce
github.com/longhorn/longhorn-instance-manager/pkg/imrpc._ProcessManagerService_ProcessDelete_Handler({0x10db360?, 0xc0005cc700}, {0x1511968, 0xc00230dd10}, 0xc0043b7680, 0x0)
	/go/src/github.com/longhorn/longhorn-instance-manager/pkg/imrpc/imrpc.pb.go:1302 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005ec800, {0x1511968, 0xc00230dc80}, {0x15167a0, 0xc002784680}, 0xc0014c9320, 0xc0006ec600, 0x1cb6df8, 0x0)
	/go/src/github.com/longhorn/longhorn-instance-manager/vendor/google.golang.org/grpc/server.go:1372 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc0005ec800, {0x15167a0, 0xc002784680}, 0xc0014c9320)
	/go/src/github.com/longhorn/longhorn-instance-manager/vendor/google.golang.org/grpc/server.go:1783 +0xfec
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	/go/src/github.com/longhorn/longhorn-instance-manager/vendor/google.golang.org/grpc/server.go:1016 +0x59
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 174521376
	/go/src/github.com/longhorn/longhorn-instance-manager/vendor/google.golang.org/grpc/server.go:1027 +0x115
```

At the exact wrong moment, we tried to unregister a process. This requires a write lock. According to the RWMutex documentation, if a call to `sync.RWMutex.Lock` is blocked, no call to  `sync.RWMutex.RLock` can succeed. This probably contributes to the rarity of the observed deadlock. It can only occur if ProcessManager is actively registering/unregistering a process AND `checkMountPointStatusForEngine` is running at the exact same time.

```
// If a goroutine holds a RWMutex for reading and another goroutine might
// call Lock, no goroutine should expect to be able to acquire a read lock
// until the initial read lock is released. In particular, this prohibits
// recursive read locking. This is to ensure that the lock eventually becomes
// available; a blocked Lock call excludes new readers from acquiring the
// lock.
```

**Comment by PhanLe1010** [comment]
A side question, do we observe memory and CPU high consumption once there are many go routine stuck in this case? Maybe it could be triggered if we leave the deadlock for a long time and the go routine starts building up.

**Comment by innobead** [comment]
`checkMountPointStatusForEngine` was backported to 1.5 and 1.4 as well, so need to backport the fix accordingly. cc @ChanYiLin

**Comment by innobead** [comment]
Added this to https://github.com/longhorn/longhorn/wiki/Release-Known-Issues#v160.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-instance-manager `d9b06ab9`) with test [steps](https://github.com/longhorn/longhorn/issues/7919#issue-2132920716)

1. Can reproduce with the custom instance-manager image mentioned in test step, after change instance-manager image to master-head, the issue can not be reproduced.
2. Did not observe outstanding issue on master-head [pipeline](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/840/)
