### ISSUE TITLE
Support bundle missing instance managers and config map yamls

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#792]
Version v0.6.2.

**Comment by yasker** [comment]
Before the fix, instance manager and config maps are missing from the support bundle.

After the fix, instance manager is at `yamls/longhorn/instancemanagers.yaml`, config maps are at `yamls/kubernetes/configmaps.yaml`.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
