### ISSUE TITLE
[IMPROVEMENT] Expose virtual size of qcow2 backing images

### ISSUE THREAD

**Issue by tserong** [longhorn/longhorn#7923]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Backing images can be created from either raw or qcow2 files. In both cases, the size of the image listed in the backing image's status is the physical size of the original image file. For raw images, this is fine, but qcow2 images have a separate virtual size, which can be much larger than the original image file.

It would be helpful if the virtual size could also be exposed, because this would allow Harvester to query the virtual size of a backing image when creating VMs, in order to automatically set the correct size for the volume created from that image, rather than just defaulting to 10GiB. The problem here is that if the virtual size of an image is greater than that default, and if the user doesn't realize they need to manually change the volume size, they end up with a corrupt/useless volume image attached to their VM.

## Describe the solution you'd like

Longhorn would add a virtualSize field to backing image status, so for example if we start with this qcow2 image:

```
> qemu-img info SLE-Micro.x86_64-5.5.0-Default-qcow-GM.qcow2
image: SLE-Micro.x86_64-5.5.0-Default-qcow-GM.qcow2
file format: qcow2
virtual size: 20 GiB (21474836480 bytes)
disk size: 955 MiB
cluster_size: 65536
Format specific information:
    compat: 1.1
    compression type: zlib
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
    extended l2: false
```

...we would then later be able to see something like this:

```
> kubectl -n longhorn-system get lhbi/default-image-87dw7 -o yaml
apiVersion: longhorn.io/v1beta2
kind: BackingImage
[...]
spec:
  [...]
  sourceParameters:
    url: http://192.168.0.1/SLE-Micro.x86_64-5.5.0-Default-qcow-GM.qcow2
status:
  [...]
  size: 1001652224             # <-- physical size, equal to the original 955MiB
  virtualSize: 21474836480     # <-- virtual size, in this example 20GiB
```

Longhorn already appears to use `qemu-img info` internally to figure out what format images are, so hopefully it's mostly a matter of extending that parsing a little bit.

## Describe alternatives you've considered

We could change the size value in the status to return whichever is greater of the underlying image size or virtual size (if the latter is present), but then we lose the ability to know what the original image size was, so that doesn't seem like a very good choice to me.

## Additional context

For more detail on the Harvester side of this issue, see https://github.com/harvester/harvester/issues/4905

If it's agreed that this looks viable and nobody else has spare cycles, I'm happy to attempt to implement it, as aside from being a useful feature, I think it'd be a good learning experience :-)

**Comment by tserong** [comment]
This would also presumably allow the Longhorn Create Volume page to pre-fill the size of a volume created from a backing image, rather than defaulting to 20GiB

**Comment by tserong** [comment]
I've got some WIP on this against v1.6.0, so that I can test against our current Harvester release. At this point, I've got backing-image-manager exposing image virtual size (see https://github.com/longhorn/backing-image-manager/compare/v1.6.x...tserong:backing-image-manager:tserong-v1.6.0-dev?expand=1)

**Comment by tserong** [comment]
I've also now got longhorn-manager exposing virtualSize from my fork of backing-image-manager (see https://github.com/longhorn/longhorn-manager/compare/v1.6.x...tserong:longhorn-manager:tserong-v1.6.0-dev?expand=1)

This gives, for example:

```
# kubectl get -n longhorn-system lhbi/default-image-gjm5l -o yaml
apiVersion: longhorn.io/v1beta2
kind: BackingImage
metadata:
  annotations:
    harvesterhci.io/imageId: default/image-gjm5l
  creationTimestamp: "2024-02-23T08:42:39Z"
  finalizers:
  - longhorn.io
  generation: 2
  labels:
    longhorn.io/component: backing-image
    longhorn.io/managed-by: longhorn-manager
  name: default-image-gjm5l
  namespace: longhorn-system
  resourceVersion: "1416026"
  uid: 4b02a17f-6e3a-42ca-9770-4caffe2f429f
spec:
  checksum: ""
  disks:
    b302b305-d156-4ac8-956d-cc8d5a981272: ""
  sourceParameters:
    url: http://192.168.0.1/SLE-Micro.x86_64-5.5.0-Default-qcow-GM.qcow2
  sourceType: download
status:
  checksum: 1bbfc258229011fc4be34d35e823dab72431f577de5027d88f9236bbb8b786f25ca976422dfb55a02194215b0b717fbba033516c2b8c32b46c6587a580aaa748
  diskFileStatusMap:
    b302b305-d156-4ac8-956d-cc8d5a981272:
      lastStateTransitionTime: "2024-02-23T10:00:37Z"
      message: ""
      progress: 100
      state: ready
  diskLastRefAtMap:
    b302b305-d156-4ac8-956d-cc8d5a981272: "2024-02-23T08:42:40Z"
  ownerID: harvester-node-2
  size: 1001652224
  uuid: c5ba7ef9
  virtualSize: 21474836480
```

Some notes on my implementation:

- virtualSize will be zero if the backing image file isn't ready yet. Once the backing image is ready, virtualSize should either be equal to size (in the case of a raw image), or potentially greater than size (in the case of a qcow2 image).
- I'm reasonably confident in what I've done to backing-image-manager.
- I don't know if I've done everything necessary in longhorn-manager, as I'm not yet familiar enough with the code.
- I have not looked at any UI stuff at all (i.e. I haven't tried to expose virtualSize in the longhorn GUI, nor is it listed if you run `kubectl get -n longhorn-system lhbi`)
- My commit messages are very terse, largely because I was working through this as a learning experience and figured I might have to change or rewrite things :-)

I see this issue is now assigned to @ChanYiLin, so I apologise if I'm stepping on anyone's toes. I just thought I should let you know what I've been up to - I hope it at least provides a reasonable start.

**Comment by innobead** [comment]
@tserong would like you like to take this move forward as discussed?

**Comment by innobead** [comment]
@shuo-wu noticed you backported this, so remember to add backport labels next time.

**Comment by shuo-wu** [comment]
Probably we need to add a new column `VirtualSize` on the UI page.
cc @innobead

**Comment by tserong** [comment]
> Probably we need to add a new column `VirtualSize` on the UI page.

@shuo-wu @innobead do you want me to have a go at doing that piece too?

**Comment by roger-ryao** [comment]
**Verified on master-head 20240528**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/cd4d7235de3547e74ef6aeb71c6ba2c97ac8a9ba
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/aebb5a8a1c5d5b9463c0c39b7ad4ae0766795477
- backing-image-manager `master-head` https://github.com/longhorn/backing-image-manager/commit/901c2170abd2b38c352d9a75184f6775cb1870f1

**The test steps**
https://github.com/longhorn/longhorn/issues/7923#issuecomment-2045820544

**Result Passed**

Create a `raw` backing image where `Size` is equal to `VirtualSize` and create a `qcow2` backing image where `Size` is different from `VirtualSize`.
```
ryao@ryao-laptop:~/Desktop/note/longhorn-tool> kubectl -n longhorn-system get lhbi
NAME    UUID       SOURCETYPE           SIZE         VIRTUALSIZE   AGE
vol-0   bbbdc486   download             1161728      33554432      4h10m
vol-1   e4758435   export-from-volume   268435456    268435456     3h49m
vol-3   88662aaa   upload               268435456    268435456     3h47m
vol-5   311209b3   download             0            0             3h18m
vol-6   b48a64bb   upload               5368709120   5368709120    3h18m
```
