### ISSUE TITLE
[BUG] Large volume replica cannot be scheduled

### ISSUE THREAD

**Issue by bauerjs1** [longhorn/longhorn#7924]
## Describe the bug

When trying to provision a `strict-local` volume of 30 tebibytes, Longhorn fails to schedule the replica on the desired node. The PVC is created successfully and bound successfully when the first consumer is started on the desired node. However, Longhorn fails to provision with
```
level=error msg="There's no available disk for replica pvc-20ce336f-3e8f-445b-aa12-517bca7a64be-r-d1b803dd, size 32985348833280" func="scheduler.(*ReplicaScheduler).ScheduleReplica" file="replica_scheduler.go:95"
level=warning msg="Failed to schedule replica of volume with HardNodeAffinity = srv-ap-dizk8s3d" func="controller.(*VolumeController).reconcileVolumeCondition" file="volume_controller.go:1699" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=srv-ap-dizk8s3d owner=srv-ap-dizk8s3d replica=pvc-20ce336f-3e8f-445b-aa12-517bca7a64be-r-d1b803dd state=detached volume=pvc-20ce336f-3e8f-445b-aa12-517bca7a64be
```

## Expected behavior

The volume should be provisioned as expected, since there is plenty of space on this node (40Ti disk size, 37Ti available, 150% overprovisioning allowed)

## Support bundle for troubleshooting

Sent per mail. I've truncated the kubelet logs, because they were huge.

## Environment

 - Longhorn version: `1.6.0`
 - Impacted volume (PV): `pvc-20ce336f-3e8f-445b-aa12-517bca7a64be`
 - Installation method: Helm
 - Kubernetes distro and version: `1.25.12` via Kubespray/Kubeadm
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 5
 - Node config
   - OS type and version: Ubuntu 20.04
   - Kernel version: `5.15.0`
   - CPU per node: 64
   - Memory per node: 512Gi
   - Disk type: HDD (hardware RAID5)
   - Network bandwidth between the nodes (Gbps): 10G
 - Underlying Infrastructure: bare-metal
 - Number of Longhorn volumes in the cluster: 12

## Additional context

No errors in `dmesg`

**Comment by PhanLe1010** [comment]
Ok. Looks like it is `filesystemType: ext2/ext3` from the support bundle. You can not create a volume bigger than 4TB if the host filesystem is ext2/ext3 https://longhorn.io/docs/1.6.0/nodes-and-volumes/volumes/volume-size/#:~:text=The%20maximum%20volume%20size%20is%20based%20on%20the%20disk%E2%80%99s%20file%20system%20(for%20example%2C%2016383%20GiB%20for%20ext4). You can use xfs instead

**Comment by derekbit** [comment]
@PhanLe1010 Do you think we should mention and explain https://github.com/longhorn/longhorn/issues/7924#issuecomment-1944541060 in the [volume creation doc](https://longhorn.io/docs/1.6.0/nodes-and-volumes/volumes/create-volumes/)?

**Comment by PhanLe1010** [comment]
> @PhanLe1010 Do you think we should mention and explain [#7924 (comment)](https://github.com/longhorn/longhorn/issues/7924#issuecomment-1944541060) in the [volume creation doc](https://longhorn.io/docs/1.6.0/nodes-and-volumes/volumes/create-volumes/)?

I agree, it would be great. Also, maybe we can turn the log level up for this log https://github.com/longhorn/longhorn-manager/blob/9f4442f657e022db3144b1a73b8b463c4f95d713/scheduler/replica_scheduler.go#L335C1-L336C1 to make it easier for user to spot the root cause

**Comment by derekbit** [comment]
cc @mantissahz for the feature owner

**Comment by mantissahz** [comment]
We have mentioned the volume maximum size in [volume size section](https://longhorn.io/docs/1.6.0/nodes-and-volumes/volumes/volume-size/).

Do we need to mention it in creating volumes section?
Will it be flooding if we turn the log level up for this log?

**Comment by PhanLe1010** [comment]
Hi @mantissahz , 
> Will it be flooding if we turn the log level up for this log?
we already flush the log `level=error msg="There's no available disk for replica pvc-20ce336f-3e8f-445b-aa12-517bca7a64be-r-d1b803dd, size 32985348833280" func="scheduler.(*ReplicaScheduler).ScheduleReplica" file="replica_scheduler.go:95"` when replica is failed to scheduled. I think it doesn't hurt to add one more log to indicate exactly why it failed. Right now, we are still flushing logs but without the details. On the other hand, I think this error is important to user and should not be silent.

> Do we need to mention it in creating volumes section?
I think we can mentioned at both places but I am not feeling strong so will be ok with either yes or no

**Comment by bauerjs1** [comment]
Thank you for the quick replies!

> Looks like it is `filesystemType: ext2/ext3` from the support bundle.

The underlying file system is ext4. Partial output of `lsblk -f`:
```
NAME                      FSTYPE      LABEL FSAVAIL FSUSE% MOUNTPOINT
sda
└─sda1                    LVM2_member
  └─data--vg-data--lv     ext4                36,1T     0% /var/lib
```

**Comment by bauerjs1** [comment]
I just found out the same thing... thanks for pointing that out! I agree it would be very useful to have this in the docs and error messages.

So the host file system would need to be xfs, right? Would it also help making longhorn use the raw disk instead?

**Comment by bauerjs1** [comment]
I've changed the `/var/lib` filesystem to XFS and provisioning works like a charm now. Thank you everybody for the quick support!

**Comment by bauerjs1** [comment]
@mantissahz can this issue be closed or should I leave it open for you for the documentation/error message improvements?

**Comment by PhanLe1010** [comment]
Thanks @bauerjs1 We can keep this one for the documentation/error message improvements
