### ISSUE TITLE
[FEATURE] Create Longhorn CLI focusing on non CR resource operations

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#7927]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Create a Longhorn CLI focusing on non-custom-resource operations, as users can operate resources via Kubectl or similar tools, K8s user experience. However, some operations like install prerequisites, preflight check before installation/upgrade, runtime periodical check, headless support bundle download, check known issue mentioned in the knowledge pages, etc. are only partially operated through UI. 

We should provide a CLI to help with these headless operations for general functions, debugging, benchmarking, troubleshooting, etc. 

Change https://github.com/longhorn/longhorn-preflight to longhorn/cli and implement the corresponding functions.

**Comment by shuo-wu** [comment]
We can leverage this CLI to guide users understand & config Longhorn systems on demands:
1. Use an interactive way to help config Longhorn nodes, disks, settings, backups, and so on.
2. Step by Step. In each step, we will explain what's for and list all options.

For example:
```
$ longhorn-cli guide

Do you need to launch v1 volumes in your clusters? v1 volumes are low-spec friendly but have limited performance.
yes/no: yes

How many CPUs you wish to reserve for the component (longhorn-instance-manger pod) that runs v1 volumes on each node?
Please input the reserved CPU percentage:

......

======

Do you need to add extra disks for the below nodes?
  1. Node 1: default disk
  2. Node 2: default disk
  3. Node 2: default disk
Please input the nodes we want to add disks: 1, 2, 3

The available disk type is:
  1. Block device (for v2 volumes)
  2. Filesystem (for v1 volumes)
Please select the disk type: 2

Please input the disk path: /var/lib/longhorn-extra

......
======

Do you have a backupstore?
  Currently, Longhorn supports:
  1. NFS. nfs://xxxxxx
  2. S3. xxx
  3. CIFS. xxx
If YES, please input the backup target: s3://xxxxx

What's the credential of the backup target?
Please input the secret name: minio-secret 
......

```

------

Besides, this CLI can handle some complicated operations such as recurring-job creation and configuration. Without this, users have to get a template YAML, check all fields and the corresponding options, modify it, create CRs, and bind it to some volumes. It's too trivial. An interactive CLI definitely helps.

**Comment by derekbit** [comment]
Some functionalities of the CLI
- Installation
  - Environment check (https://github.com/longhorn/longhorn/issues/6657)
- Filesystem
  - Manual trim
   - Filesystem check 
- Snapshot 
  - Snapshot integrity check (https://github.com/longhorn/longhorn/issues/5035)
- Backup and Restore
  - Restore backup without Longhorn system (https://longhorn.io/docs/1.6.0/advanced-resources/data-recovery/export-from-replica/)
  - Backup integrity check (https://github.com/longhorn/longhorn/issues/4571)

**Comment by c3y1huang** [comment]
> Filesystem
> * Filesystem check

@derekbit , could you help to create an issue for the filesystem check with some context?

**Comment by c3y1huang** [comment]
@derekbit The CLI is at the alpha phase and I am not sure how it will be delivered. Should we enhance the document later? cc @innobead

**Comment by derekbit** [comment]
I think just like v2 volume, mark it as alpha version. WDYT @c3y1huang @innobead

**Comment by c3y1huang** [comment]
> I think just like v2 volume, mark it as alpha version. WDYT @c3y1huang @innobead

Got it.

**Comment by innobead** [comment]
@c3y1huang May I understand why it will be alpha/preview? All commands we have now should work as expected. For others, we can add them over phases.

**Comment by c3y1huang** [comment]
> @c3y1huang May I understand why it will be alpha/preview? All commands we have now should work as expected and independent. For others, we can add them over the following releases.

I mentioned the alpha phase because I wasn't clear on the CLI delivery and release process. It is much clearer now. Thank you.

**Comment by chriscchien** [comment]
Hi @c3y1huang, 

Using longhorn cli to export replica result in fail by below information, I tesed on v1.7.x(`0d9255`) and master(`c39a2d`) custom image on ubuntu 22.04 and on SLES15 SP6, could you take a look on this? thank you.
```bash
> ls /var/lib/longhorn/replicas/pvc-7ae4a869-ae6e-4f6e-ace6-1e178b8500cd-1876445f
volume-head-000.img  volume-head-000.img.meta  volume.meta
>
> ./longhornctl --image='chanow/longhorncli:17x' export replica --name='pvc-7ae4a869-ae6e-4f6e-ace6-1e178b8500cd-1876445f' --target-dir='/home/ec2-user/cli/export'
INFO[2024-07-12T08:52:13Z] Initializing replica exporter                
INFO[2024-07-12T08:52:13Z] Running replica exporter                     
INFO[2024-07-12T08:52:13Z] Waiting for DaemonSet container to exit       container=init-longhornctl kind=DaemonSet name=longhorn-replica-exporter namespace=default
INFO[2024-07-12T08:52:14Z] Waiting for DaemonSet container to be ready   container=engine kind=DaemonSet name=longhorn-replica-exporter namespace=default
INFO[2024-07-12T08:52:34Z] Exported replica:
 volumes:
    pvc-7ae4a869-ae6e-4f6e-ace6-1e178b8500cd:
        - replicas:
            - node: ip-10-0-1-46
              error: jq is not installed.
            - node: ip-10-0-1-225
              error: jq is not installed. 
INFO[2024-07-12T08:52:34Z] Completed replica exporter. Use 'longhornctl export replica stop' to stop exporting replica. 
>
> jq --version
jq-1.6
```

**Comment by c3y1huang** [comment]
> ```shell
> ERROR: jq is not installed.
> ```

By default, the exporter uses the `--engine-image='longhornio/longhorn-engine:v1.7.0-dev'`. It seems that `jq` is not included in the v1.7.0-dev engine image yet. Could you please try manually building the engine image using the `longhorn/engine` repo's `v1.7.x` branch? And use that with the export replica command like:
```
./bin/longhornctl export replica --engine-image="<custom-image>" --name="xxx" --target-dir="xxx"
```

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(cli `e3aed7`, longhorn-engine `756827`), v1.7.x(cli `47bd23`, longhorn-engine 756827 `84a222`)

Following test [steps](https://github.com/longhorn/longhorn-tests/pull/1947), below clonghorn cli actions worked well
- Install preflight
- Volume trim by name (and combine with other options)
- Replica export
- Replica unexport
- Get replica
- Check preflight (and combine with other options)
- Change log level

**Comment by innobead** [comment]
@c3y1huang Do we have a doc already for each command usage?

**Comment by c3y1huang** [comment]
> @c3y1huang Do we have a doc already for each command usage?

Its WIP. I will update to https://github.com/longhorn/longhorn/issues/8992.

**Comment by derekbit** [comment]
Updated in https://github.com/longhorn/website/pull/951
