### ISSUE TITLE
[BUG] The activated DR volume do not contain the latest data.

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#7945]
## Describe the bug

According to https://github.com/longhorn/longhorn/issues/5292 , the activated DR volume should contain the latest data.
After activated the DR volume, the backup is synchronized with the `2nd backup` in the backup list on `cluster 2`, but the volume data doesn't sync up with the latest data from the `2nd backup`.

## To Reproduce

1. Launch `2 clusters` and both have Longhorn installed
2. Set up a backup target.
3. Create a volume and write data in the `1st cluster`. Then create a backup.
4. Restore the backup as a DR volume in the `2nd cluster`.
5. Modify the backup poll interval to a large value.
6. Write more data for the volume in the `1st cluster`, and create the `2nd backup`.
7. Activate the DR volume in the `2nd cluster`. Then verify the data

## Expected behavior

The activated DR volume should contain the latest data.

## Support bundle for troubleshooting

[supportbundle_9d0f8761-79c7-49dd-b56e-f402607586f0_2024-02-16T08-43-54Z.zip](https://github.com/longhorn/longhorn/files/14308556/supportbundle_9d0f8761-79c7-49dd-b56e-f402607586f0_2024-02-16T08-43-54Z.zip)

## Environment

 - Longhorn version: `v1.5.0` ~ `v1.6.0`

## Additional context

- https://github.com/longhorn/longhorn/issues/5292
- require/manual-test-plan : https://github.com/longhorn/longhorn-tests/pull/1732

**Comment by innobead** [comment]
@shuo-wu please check this.

**Comment by innobead** [comment]
@roger-ryao plesee add the severity label.

cc @longhorn/qa

**Comment by shuo-wu** [comment]
The root cause:
The volume controller won't check and wait for the backup volume to update its latest backup. Instead, it directly activates the DR volumes.

It's a regression for the first version of introducing BackupVolume and Backup CRD but not for v1.5.x or v1.6.x. 

Notice that there is one more issue related: The 2nd cluster cannot ask the backup volume to check and update its latest backup via UI. However, before introducing BackupVolume CRD, Longhorn will forcibly pull the info from the remote backup target when users click Backup Page via UI.

**Comment by innobead** [comment]
> Notice that there is one more issue related: The 2nd cluster cannot ask the backup volume to check and update its latest backup via UI. However, before introducing BackupVolume CRD, Longhorn will forcibly pull the info from the remote backup target when users click Backup Page via UI.

So we should ask to update BackupVolume CR again before doing the restoration + your fix at https://github.com/longhorn/longhorn-manager/pull/2611, right? 

Let's create an improvement for it

**Comment by shuo-wu** [comment]
Here is the improvement ticket: https://github.com/longhorn/longhorn/issues/7982

**Comment by roger-ryao** [comment]
**Verified on master-head 20240312**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/88c49e7416c9da25f1c125780e7de2026e92d7d8
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/65bdc09182d4e7c7803f54542ef48f6ac0bdc463



**The test steps**


Test Method 1 : https://github.com/longhorn/longhorn/issues/7945#issue-2138151676
  1. Launch `2 clusters` and both have Longhorn installed
  2. Set up a backup target.
  3. Create two volumes and write data in the `1st cluster`. Then create volumes' backups.
  4. Restore two backup files as DR volumes in the `2nd cluster`.
  5. Modify the backup poll interval to a large value.
  6. Write more data for the volumes in the `1st cluster`, and create the `2nd backup`.
  7. Activate one of the DR volumes in the `2nd cluster`. Then verify the data

Test Method 2 refer:https://github.com/longhorn/longhorn/issues/7947#issuecomment-1956146993


**Result Passed**

- [x] 1. Test Method 1.
- [x] 2. Test Method 2
- [x] 3. require/manual-test-plan : https://github.com/longhorn/longhorn-tests/pull/1732
