### ISSUE TITLE
[TEST] Using more cost-effective ec2 instance type to run regression tests

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7957]
## What's the test to develop? Please describe

Using more cost-effective ec2 instance type to run regression tests.

**Comment by yangchiu** [comment]
https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/824/
https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/755/

**Comment by innobead** [comment]
If it's not feasible and dramatically impacts our execution, we just keep the original instance type we use.

What instance types are we using currently? t2.xlarge or t3.xlarge?

**Comment by yangchiu** [comment]
> What instance types are we using currently? t2.xlarge or t3.xlarge?

Currently `t2.xlarge`. I can try `t3.xlarge` later.

**Comment by innobead** [comment]
Let's OK, if the price is similar, we can keep using t2.xlarge.

**Comment by yangchiu** [comment]
Hourly rate comparisons for some similar instance types are listed below:

amd64 machines:
	
Instance name | On-Demand hourly rate for SLES | vCPU | Memory | Storage | Network performance
-- | -- | -- | -- | -- | --
t2.xlarge | 0.2856 | 4 | 16 GiB | EBS Only | Moderate ***
t3.xlarge | 0.2227 | 4 | 16 GiB | EBS Only | Up to 5 Gigabit
t3a.xlarge | 0.2067 | 4 | 16 GiB | EBS Only | Up to 5 Gigabit

*** According to https://cloudonaut.io/ec2-network-performance-cheat-sheet/, it's ~ 0.89 Gigabit

arm64 machines:

Instance name | On-Demand hourly rate for SLES | vCPU | Memory | Storage | Network performance
-- | -- | -- | -- | -- | --
a1.2xlarge | 0.3290 | 8 | 16 GiB | EBS Only | Up to 10 Gigabit
t4g.xlarge | 0.1907 | 4 | 16 GiB | EBS Only | Up to 5 Gigabit

Currently we are using `t2.xlarge` for amd64 and `a1.2xlarge` for arm64.
`t3a.xlarge` is the cheapest one for amd64 but why the cluster setup is unstable still needs time to investigate. I will manage to use `t3.xlarge` first.

And `t4g.xlarge` is much cheaper than `a1.2xlarge`. I will definitely try to see if it works for us.

**Comment by yangchiu** [comment]
Test results:

[sles 15-sp5 / amd64 / t3.xlarge](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/825/)
[sles 15-sp5 / arm64 / t4g.xlarge](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/768/)

[sle micro 5.5 / amd64 / t3.xlarge](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/amd64/job/longhorn-tests-sle-micro-amd64/138/)
[sle micro 5.5 / arm64 / t4g.xlarge](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/arm64/job/longhorn-tests-sle-micro-arm64/36/)

[ubuntu 22.04 / amd64 / t3.xlarge](https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/589/)
[ubuntu 22.04 / arm64 / t4g.xlarge](https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/arm64/job/longhorn-tests-ubuntu-arm64/482)

[oracle 9.1 / amd64 / t3.xlarge](https://ci.longhorn.io/job/public/job/master/job/oracle/job/amd64/job/longhorn-tests-oracle-amd64/20/)

[rhel 9.1.0 / amd64 / t3.xlarge](https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/171/)
rhel 9.1.0 / arm64 / t4g.xlarge

[rockylinux 9.3 / amd64 / t3.xlarge](https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/amd64/job/longhorn-tests-rockylinux-amd64/32/)
[rockylinux 9.3 / arm64 / t4g.xlarge](https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/arm64/job/longhorn-tests-rockylinux-arm64/20/): test case `test_space_usage_for_rebuilding_only_volume` failed, rerun and investigate

**Comment by yangchiu** [comment]
> [rockylinux 9.3 / arm64 / t4g.xlarge](https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/arm64/job/longhorn-tests-rockylinux-arm64/20/): test case `test_space_usage_for_rebuilding_only_volume` failed, rerun and investigate

`test_space_usage_for_rebuilding_only_volume` is flaky even in `a1.2xlarge`, so this failure is not related to the `t4g.xlarge` instance type change. https://github.com/longhorn/longhorn/issues/7988 is created for it.

**Comment by innobead** [comment]
Well done @yangchiu

**Comment by yangchiu** [comment]
> `test_space_usage_for_rebuilding_only_volume` is flaky even in `a1.2xlarge`, so this failure is not related to the `t4g.xlarge` instance type change. https://github.com/longhorn/longhorn/issues/7988 is created for it.

This issue is about IO performance, so I'll also record the EBS performance of each instance type here:


Instance size | Baseline bandwidth(Mbps) | Maximum bandwidth(Mbps) | Baseline throughput(MB/s, 128 KiB I/O) | Maximum throughput(MB/s, 128 KiB I/O) | Baseline IOPS(16 KiB I/O) | Maximum IOPS(16 KiB I/O)
-- | -- | -- | -- | -- | -- | --
t2.xlarge | N/A | N/A | N/A | N/A | N/A | N/A
t3.xlarge | 695 | 2780 | 86.88 | 347.5 | 4000 | 15700
t3a.xlarge | 695 | 2780 | 86.88 | 347.5 | 4000 | 15700


Instance size | Baseline bandwidth(Mbps) | Maximum bandwidth(Mbps) | Baseline throughput(MB/s, 128 KiB I/O) | Maximum throughput(MB/s, 128 KiB I/O) | Baseline IOPS(16 KiB I/O) | Maximum IOPS(16 KiB I/O)
-- | -- | -- | -- | -- | -- | --
a1.xlarge | 800 | 3500 | 100 | 437.5 | 6000 | 20000
a1.2xlarge | 1750 | 3500 | 218.75 | 437.5 | 10000 | 20000
t4g.xlarge | 695 | 2780 | 86.88 | 347.5 | 4000 | 15700


ref: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-optimized.html

**Comment by yangchiu** [comment]
Even though `t3.xlarge` and `t4g.xlarge` are cheaper than `t2.xlarge` and `a1.2xlarge` according to [the pricing table](https://aws.amazon.com/ec2/pricing/on-demand/), it seems not the case for us according to AWS cost explorer:

![cost_report](https://github.com/longhorn/longhorn/assets/5709208/c6d1799c-4546-44fb-ad89-f035817c37cd)

As you can see it looks like the cost increased after we adopting new instance types at around Feb 20th.

After adopting new instance types, we can see extra cost for `t3.xlarge` (in red) and `t4g.xlarge` (in green) make the daily cost increased, but before the change, the `t2.xlarge` and `a1.2xlarge` instances (seem to be categorized into `No Instance type` have a significant lower daily cost.

I'm not sure if AWS has any special policies or we have any special contract with it to make `t2.xlarge` and `a1.2xlarge` cheaper than we expected.

But seems we need to rollback the change and use the original instance type to be cost-effective.

cc @innobead
