### ISSUE TITLE
[TASK] update go-iscsi-helper and go-common-lib in v1.5.x

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#7960]
## What's the task? Please describe

Some of our components repo like longhorn-manager, longhorn-engine,..., depends on `go-iscsi-helper` `go-common-lib`
we did some changes and refactor in `go-iscsi-helper` and `go-common-lib` like move the function from `go-iscsi-helper` to `go-common-lib` 

However, in v1.5.x, some of our components' repo still using old  `go-iscsi-helper` and `go-common-lib` package
It would fails when backporting some PRs or updating the package version, since some of the functions/types are not in the `go-iscsi-helper` anymore

For example, https://github.com/longhorn/longhorn-manager/pull/2602
It failed to update the vendor because some function couldn't be found from `go-iscsi-helper`

We need to update the `go-iscsi-helper` and `go-common-lib` version in v1.5.x
and make sure all the changes have been updated.

## Describe the sub-tasks

- [ ] `longhorn-manager`
- [ ] `longhorn-instance-manager`
- [ ] `longhorn-engine`
- [ ] ~~`backing-image-manager`~~
- [ ] `longhorn-share-manager`

**Comment by ChanYiLin** [comment]
cc @longhorn/dev

**Comment by innobead** [comment]
Disabled renovate for go-iscsi-helper for 1.5 and 1.4 until this issue has been fixed.

https://github.com/longhorn/release/blob/main/renovate-default.json#L43-L46

**Comment by innobead** [comment]
@ChanYiLin already merged all PRs.
