### ISSUE TITLE
[IMPROVEMENT] Allow users to request backup volume update

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#7982]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Typically Longhorn will pull and update all backup volumes with a fixed interval `Backupstore Poll Interval`. There is no way for users to trigger the update manually. This is actually a regression for the first version of introducing Backup CRD (v1.2.0 IIRC).

## Describe the solution you'd like

Updating `BackupVolume.Spec.SyncRequestedAt` when receiving [Backup get/list](https://github.com/longhorn/longhorn-manager/blob/12d41cc519e10943e0e8904cf7320c57a369e698/api/router.go#L123-L124) requests

**Comment by innobead** [comment]
Similar to https://github.com/longhorn/longhorn/issues/5035.

**Comment by derekbit** [comment]
@mantissahz 
Don't forget to update the official doc v1.6.2 and v1.7.0-dev. Thank you :)

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `00a3b8`) with test [steps](https://github.com/longhorn/longhorn/issues/7982#issuecomment-1972722201)

Below API will trigger the value of backupvolume.spec.syncRequestedAt updating.
```
curl -X PUT -H "Content-Type: application/json" -d '{"syncAllBackupVolumes": true}' http://3.82.9.123/v1/backupvolumes
```

**Comment by derekbit** [comment]
@mantissahz Can you help update the doc for v1.6.2 and v1.7.0-dev?
