### ISSUE TITLE
[CI] longhorn-spdk-engine CI doesn't return error

### ISSUE THREAD

**Issue by FrankYang0529** [longhorn/longhorn#7985]
## What's the CI task to develop? Please describe

In following CI Builds, we can see there are error for `go vet` and `go test`, but CI doesn't return error.

* https://drone-pr.longhorn.io/longhorn/longhorn-spdk-engine/180/1/3
* https://drone-pr.longhorn.io/longhorn/longhorn-spdk-engine/187/1/3
* https://drone-pr.longhorn.io/longhorn/longhorn-spdk-engine/188/1/3

However, in some CI Builds, it returns error.

* https://drone-pr.longhorn.io/longhorn/longhorn-spdk-engine/194/1/3

**Comment by derekbit** [comment]
Already addressed in https://github.com/longhorn/longhorn-spdk-engine/pull/158

**Comment by derekbit** [comment]
Close it because the CI is fixed.
