### ISSUE TITLE
Is It Possible to Do'nt Install Longhorn to a Node?

### ISSUE THREAD

**Issue by akuscu-smartpulse** [longhorn/longhorn#799]
I have a mini node and i do not want to consume resources on that node.If i install longhorn the container will run in that node.I want to install longhorn only specific nodes.Is it  possible? If i add node affinity in https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml file would it run properly ?

I have one more question.Is it possible to take our files from /var/lib/longhorn/replicas/..... directory ? If my system crush i want to take my files back on the replica.

**Comment by yasker** [comment]
@akuscu-smartpulse

Longhorn manager and engine will need to run on the node to support the workload running on the node. You can use:
1. Kubernetes taint to disable the node, but the workload running on that node won't be able to access the Longhorn volume.
2. You can disable the node scheduling in Longhorn UI for the node, so Longhorn will not use that node for storage, but still able to provide the access to the volume used by the workload on the node.

And you can copy the directory and back it up. You can also use Longhorn's backup mechanism to make backups for the volume to a S3 or NFS server, e.g. you can schedule a backup at 3am in the morning everyday and retain last 10 backups.

**Comment by C0NO** [comment]
No i mean for example if my system crushed and i can only reach /var/lib/rancher/replicas... directory.This directories have .img , snapshots etc...
How can i take back my files from that .img?
I know backup and snapshot options available but i want to take files from that .img files.

**Comment by yasker** [comment]
See https://github.com/longhorn/longhorn/issues/469#issuecomment-480963593

**Comment by akuscu-smartpulse** [comment]
Thank you it is worked for me.More clear information  below for newbies like me :

- If you can reach /var/lib/rancher/longhorn/replicas directory copy replicas from crushed system to your new system.On new system you need only docker installed.

- Start below command.Name volume name whatever you want and volume-path to your new replica location.volume size should fit your actual volume size.

`docker run -it -v /dev:/host/dev -v /proc:/host/proc -v <volume-path>:/volume --privileged rancher/longhorn-engine:v0.4.1 launch-simple-longhorn <volume-name> <volume-size>`
Here is my example docker command:
`docker run -it -v /dev:/host/dev -v /proc:/host/proc -v /volume/pvc-ce9ca6d1-5466-49b7-8ff2-fc35a6e81422-20b340e3:/volume --privileged rancher/longhorn-engine:v0.6.2 launch-simple-longhorn test 2g`

- After container created succesfully you can see your device on /dev/longhorn directory.(It's name is test on my example)

-After that mount that device to a directory:
`mount /dev/longhorn/test /mnt `

-Now you can reach your files inside /mnt directory.
