### ISSUE TITLE
[BUG] Volume cannot attach because of the leftover non-empty volume.status.PendingNodeID after upgrading Longhorn

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#7994]
## Describe the bug

If the `volume.status.PendingNodeID` is set in v.1.4.x, Longhorn v1.5.x will not clean it up (thanks @james-munson for checking) and will not be able to attach the volume again as:

1. Volume attachment controller check if volume is fully detached https://github.com/longhorn/longhorn-manager/blob/8ce69c8f280a5a2715c528034e0274391ad761c0/controller/volume_attachment_controller.go#L550-L552
1. Volume attachment controller think that the volume is not fully detached because of the non-empty .status.PendingNodeID field https://github.com/longhorn/longhorn-manager/blob/50acc8136199f5042afcf2b5b3c7285edb9b7820/controller/utils.go#L33-L38

## To Reproduce
1. Deploy Longhorn v1.4.x
1. Create a volume
1. Delete Longhorn manager daemonset 
1. Artificially set `volume.status.PendingNodeID` to a node name in the cluster by  `kubectl edit volumes -n longhorn-system VOLUME-NAME --subresource=status`
1. Upgrade Longhorn to v1.5.x
1. Try to attach the volume
1. See that it cannot finish attaching

## Expected behavior

Volume is able to attach after upgrade

## Additional context

This will happen when upgrading Longhorn from v1.4.x to v1.5.x/v1.6.x

## Proposal
Handle the clean-up of `volume.status.PendingNodeID` in upgrade path

**Comment by PhanLe1010** [comment]
### Workaround:

The workaround for this volume is run `kubectl edit volumes -n longhorn-system VOLUME-NAME --subresource=status` and set empty .status.PendingNodeID to empty string `""`

**Comment by james-munson** [comment]
In addition to clearing any non-null value in upgrade, it's also necessary to remove the code that checks pendingNodeID, since there are upgrades that have already happened.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `3f99a6`)

Follow test [steps](https://github.com/longhorn/longhorn/issues/7994#issue-2147443270) to upgrade from v1.6.1-rc2 to master, after upgrade completed, the volume can attach success and data correct.
