### ISSUE TITLE
[IMPROVEMENT] Change support-bundle-manager image pull policy to PullIfNotPresent

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#7998]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Having the support-bundle-manager image pull policy to [Always](https://github.com/longhorn/longhorn-manager/blob/v1.6.0/controller/support_bundle_controller.go#L683) is unnecessary and can result in excessive resource consumption and potential network congestion.

## Describe the solution you'd like

Modify the support-bundle image pull policy to "PullIfNotPresent".

## Describe alternatives you've considered

`None`

## Additional context

`None`

**Comment by c3y1huang** [comment]
@ChanYiLin could you help with this? Thank you.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240312**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/88c49e7416c9da25f1c125780e7de2026e92d7d8
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/65bdc09182d4e7c7803f54542ef48f6ac0bdc463

**The test steps**
https://github.com/longhorn/longhorn/issues/7998#issuecomment-1958605641

**Result Passed**


When creating support bundles twice, you can see in the pod description for the second support bundle creation that the image is reused, as indicated by the `Container image already present on machine` event message.

```yaml
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  10s   default-scheduler  Successfully assigned longhorn-system/longhorn-support-bundle-manager-support-bundle-2024-03-12tj9t2c to ip-10-0-2-212
  Normal  Pulled     10s   kubelet            Container image "longhornio/support-bundle-kit:v0.0.33" already present on machine
  Normal  Created    10s   kubelet            Created container manager
  Normal  Started    10s   kubelet            Started container manager
```
