### ISSUE TITLE
[CI] Automatically relate a backport PR to the backport issue

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#8002]
## What's the CI task to develop? Please describe

Usually, engineering will comment in a backport PR to refer to the backport issue. To avoid this tedious and error-prone action, automate it when the backport PR is created. 

The criteria is the PR should have the source issue, so there is a way to figure out the corresponding backport PR.

**Comment by derekbit** [comment]
@yangchiu Finished. Let's close it.
