### ISSUE TITLE
[BUG] Snapshot volume is bigger than used space and can't be cleaned up nor deleted

### ISSUE THREAD

**Issue by Siradjedd** [longhorn/longhorn#8008]
## Describe the bug
I'am using longhorn for prometheus, i see that prometheus is only using 13.00Gb but the snapshot size is 60.8Gb, even when i do trim the size of the snapshot does not decrease, and i couldn't delete or cleanup it. is there any doc that explains how snapshots work and how they get deleted and cleaned ?
![longhorn #1](https://github.com/longhorn/longhorn/assets/125685289/70570779-4691-42b8-b546-e66421b556c2)
![longhorn #2](https://github.com/longhorn/longhorn/assets/125685289/cbeda9bd-6a46-458f-88a9-0655120eea9b)
![longhorn #3](https://github.com/longhorn/longhorn/assets/125685289/6223ef20-645b-4137-b2cc-bb0e2aedbe6e)

**Comment by derekbit** [comment]
Can you execute trim operation and then generate a support bundle for us?

**Comment by Siradjedd** [comment]
[Uploading supportbundle_65860638-2d63-4077-b7ad-4f9d1134d0b6_2024-02-22T15-35-08Z.zip…]()

**Comment by dfaltum** [comment]
Yeah, there it is: https://longhorn.io/docs/1.6.0/concepts/#24-snapshots

**Comment by derekbit** [comment]
Hello @Siradjedd 
The link of the support bundle doesn't work. Can you upload it again? Thank you.

**Comment by Siradjedd** [comment]
Now when i do the trim the available space decrease by 2Gi but the snapshot is still 58Gi and the actual space used by prometheus is just 13Gi ! 
[Uploading supportbundle_65860638-2d63-4077-b7ad-4f9d1134d0b6_2024-02-23T08-37-57Z.zip…]()
@derekbit

**Comment by derekbit** [comment]
@Siradjedd 
The link still doesn't work. You can directly pull the zip file to the comment box and wait for a while util it is fully uploaded.

**Comment by derekbit** [comment]
@Siradjedd 
Thanks for the support bundle. To trim the snapshot marked as `remove: false`, you need to enable the global setting `remove-snapshots-during-filesystem-trim` or update the volume resource `volume.Spec.UnmapMarkSnapChainRemoved`.

Please see the [official doc](https://longhorn.io/docs/1.5.3/volumes-and-nodes/trim-filesystem/#automatically-remove-snapshots-during-filesystem-trim).

**Comment by derekbit** [comment]
@Siradjedd I haven't received your support bundle yet. Can you send again? Thanks.

**Comment by derekbit** [comment]
@Siradjedd Can you send the support bundle to [longhorn-support-bundle@suse.com](mailto:longhorn-support-bundle@suse.com) again? Thanks.
