### ISSUE TITLE
[BUG]Unable to attach or mount volumes after restarting vms: timed out waiting for the condition

### ISSUE THREAD

**Issue by Siradjedd** [longhorn/longhorn#8018]
## Describe the bug
The volumes were not able to attached after restarting the vms (baremetal)

`Unable to attach or mount volumes: unmounted volumes=[nfspv], unattached volumes=[kube-api-access-bdjm2 nfspv]: timed out waiting for the condition`

## Expected behavior
The volume gets attached normally

## Environment

 - Longhorn version: 1.4.1
 - Impacted volume (PV): nfspv
 - Installation method : Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Kubeadm in baremetal
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
   - ubuntu :
   - Kernel version: 20.04

**Comment by derekbit** [comment]
@Siradjedd 
Please provide a support bundle for investigation. Thanks.

**Comment by Siradjedd** [comment]
@derekbit  do you need the whole bundle or just the files/directories related to longhorn-system ?

**Comment by derekbit** [comment]
A whole bundle is appreciated. If you have any concern, you can send it to longhorn-support-bundle@suse.com.

**Comment by Siradjedd** [comment]
@derekbit  i just sent it to the email, Thanks.

**Comment by derekbit** [comment]
@Siradjedd I haven't received your support bundle yet. Can you send again? Thanks.

**Comment by Siradjedd** [comment]
@derekbit can you check rn ? thanks.

**Comment by derekbit** [comment]
Received. `nfspv` is attached and works well. Anything wrong?

**Comment by Siradjedd** [comment]
@derekbit everytime we restart the vms we get an error:  
`MountVolume.MountDevice failed for volume "nfspv" : rpc error: code = Internal desc = mount failed: exit status 32 Mounting command: /usr/local/sbin/nsmounter Mounting arguments: mount -t nfs -o vers=4.1,noresvport,timeo=600,retrans=5,softerr 10.103.142.147:/nfspv /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/f57d30ba19d70a88ef089c06dc4b665858b58a5df6b88e94d84912db30d967c8/globalmount Output: mount.nfs: Protocol not supported`

and it happens only with RWM !
Longhorn version: 1.5.4
Ubuntu 20.04

**Comment by derekbit** [comment]
> @derekbit everytime we restart the vms we get an error: `MountVolume.MountDevice failed for volume "nfspv" : rpc error: code = Internal desc = mount failed: exit status 32 Mounting command: /usr/local/sbin/nsmounter Mounting arguments: mount -t nfs -o vers=4.1,noresvport,timeo=600,retrans=5,softerr 10.103.142.147:/nfspv /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/f57d30ba19d70a88ef089c06dc4b665858b58a5df6b88e94d84912db30d967c8/globalmount Output: mount.nfs: Protocol not supported`
> 
> and it happens only with RWM ! Longhorn version: 1.5.4 Ubuntu 20.04

Can you provide the output of `uname -a` of the worker nodes?

**Comment by Siradjedd** [comment]
@derekbit 
`Linux darjeqaworker1 5.15.0-97-generic #107~20.04.1-Ubuntu SMP Fri Feb 9 14:20:11 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by vincentkelleher** [comment]
> @derekbit `Linux darjeqaworker1 5.15.0-97-generic #107~20.04.1-Ubuntu SMP Fri Feb 9 14:20:11 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

Isn't the fix only starting from kernel version `5.15.0-100` ?

![image](https://github.com/longhorn/longhorn/assets/4272277/16fa681e-8bf2-456c-834c-2934d6cd0a91)

**Comment by derekbit** [comment]
> > @derekbit `Linux darjeqaworker1 5.15.0-97-generic #107~20.04.1-Ubuntu SMP Fri Feb 9 14:20:11 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
> 
> Isn't the fix only starting from kernel version `5.15.0-100` ?
> 
> ![image](https://private-user-images.githubusercontent.com/4272277/308682964-16fa681e-8bf2-456c-834c-2934d6cd0a91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNjQ2MjEsIm5iZiI6MTcwOTE2NDMyMSwicGF0aCI6Ii80MjcyMjc3LzMwODY4Mjk2NC0xNmZhNjgxZS04YmYyLTQ1NmMtODM0Yy0yOTM0ZDZjZDBhOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMjM1MjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWUxNGRiMGJmYzE3M2I3MDg4YTA2M2IzMmZjMWY0NTVjMmI5OWY4OGIzMDhkODBkZTU1NGQ4NmM1MmZiNDFiOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DdxRrsAUA6bAwqSxZEefF-LPMsH8K77p1hOxHOgjlkw)

Yes. 5.15.0-97-generic is still broken.

**Comment by Siradjedd** [comment]
@derekbit  I updated the kernel to 6.7.6 and everything is working fine unitll now thanks.

**Comment by AndrStnz** [comment]
We can confirm - 5.15.0-92-generic and 5.15.0-97-generic **broken**.
5.15.0-100-generic works fine.
