### ISSUE TITLE
[BUG] There's no available disk for ...

### ISSUE THREAD

**Issue by runningman84** [longhorn/longhorn#8020]
## Describe the bug

I had some ssd failure so I had to reinstall one node with a new ssd. The system is the same as before because I just ran the same ansible playbooks as before. The k3s node looks good and a lot of workloads are running. Unfortunately the node is unschedubale in longorn. I get errors like this
````
There's no available disk for
````
the disk looks fine:
`````
root@cubi001:/var/lib/rancher/longhorn# df -h .
Filesystem                           Size  Used Avail Use% Mounted on
/dev/mapper/ubuntu--vg-longhorn--lv   98G   32K   93G   1% /var/lib/rancher/longhorn
root@cubi001:/var/lib/rancher/longhorn# ls -la
total 32
drwxr-xr-x 4 root root  4096 Feb 25 13:28 .
drwxr-xr-x 4 root root  4096 Feb 25 12:46 ..
-rw-r--r-- 1 root root    51 Feb 25 12:49 longhorn-disk.cfg
drwx------ 2 root root 16384 Feb 25 12:46 lost+found
drwxr-xr-x 2 root root  4096 Feb 25 12:49 replicas
root@cubi001:/var/lib/rancher/longhorn# cat longhorn-disk.cfg 
{"diskUUID":"8d1cb368-b860-4b9a-be80-e0061852ddc7"}
`````

The manager is complaining about this
```
time="2024-02-25T13:21:01Z" level=info msg="CheckEngineImageReadiness: nodes [cubi001] don't have the engine image longhornio/longhorn-engine:v1.6.0" func="datastore.(*DataStore).CheckEngineImageReadiness" file="longhorn.go:1764"
I0225 13:21:01.642052       1 shared_informer.go:311] Waiting for caches to sync for longhorn recurring jobs
I0225 13:21:01.678019       1 shared_informer.go:318] Caches are synced for longhorn recurring jobs
time="2024-02-25T13:21:01Z" level=warning msg="Failed to get filesystem device type of /var/lib/rancher/longhorn" func="controller.(*ClusterInfo).collectNodeDiskCount" file="setting_controller.go:1853" controller=longhorn-setting error="lstat /sys/class/block/ubuntu--vg-longhorn--lv: no such file or directory" node=cubi001
I0225 13:21:01.642250       1 shared_informer.go:311] Waiting for caches to sync for longhorn-system-restore
I0225 13:21:01.682516       1 shared_informer.go:318] Caches are synced for longhorn-system-restore
I0225 13:21:01.648086       1 shared_informer.go:311] Waiting for caches to sync for longhorn instance manager
I0225 13:21:01.648241       1 shared_informer.go:311] Waiting for caches to sync for longhorn-share-manager-controller
I0225 13:21:01.648348       1 shared_informer.go:311] Waiting for caches to sync for longhorn backing image data source
I0225 13:21:01.703616       1 shared_informer.go:318] Caches are synced for longhorn instance manager
I0225 13:21:01.703965       1 shared_informer.go:318] Caches are synced for longhorn-share-manager-controller
time="2024-02-25T13:21:01Z" level=info msg="Listening on 10.42.0.43:9500" func=app.startManager file="daemon.go:220" node=cubi001
````

## To Reproduce

Reinstall some node

## Expected behavior

The node should receive replicas/volumes from other nodes.

## Environment

 - Longhorn version:  1.6.0
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: ubuntu 22.04
   - Kernel version: 5.15.0-97-generic
   - CPU per node: 4
   - Memory per node: 16
   - Disk type (e.g. SSD/NVMe/HDD): samsung 980 500gb
   - Network bandwidth between the nodes (Gbps): 1 gbit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 20

**Comment by runningman84** [comment]
the disk uuid changed I had to remove the longhorn node object to recreate it

**Comment by derekbit** [comment]
@runningman84 
Do you remember the disk status of the problematic node?
The log messages are nothing to do with the disk configuration.
