### ISSUE TITLE
[IMPROVEMENT] Recreate node if the disk uuid changed with condition reason

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#8021]
the disk uuid changed I had to remove the longhorn node object to recreate it

_Originally posted by @runningman84 in https://github.com/longhorn/longhorn/issues/8020#issuecomment-1963035021_

**Comment by runningman84** [comment]
Btw. There is also no documentation how an uuid can be calculated and how you could fix such issue without just deleting the node object.
