### ISSUE TITLE
[FEATURE] v2 data engine volume migration

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#8029]
## Additional context

cc @longhorn/dev-data-plane

**Comment by shuo-wu** [comment]
v1.6.x test:
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6458/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6459/

**Comment by shuo-wu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Sprint-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/8029?planning-poker) with Zenhub @DamiaSan @innobead @derekbit

**Comment by shuo-wu** [comment]
It's a duplicate of https://github.com/longhorn/longhorn/issues/6361. Let's close this.
