### ISSUE TITLE
Set recurring Snapshots config as annotation

### ISSUE THREAD

**Issue by KuroObi** [longhorn/longhorn#803]
Is there a plan to set a Snapshot/Backup Schedule with annotations at volume creation.

It would be nice to set a daily Snapshot for a Database to daily reduce volume size.

**Comment by yasker** [comment]
@KuroObi You can already do that using storage class settings. See https://github.com/longhorn/longhorn/blob/master/examples/storageclass.yaml#L12

From UI is a different story though. It's a bit too much to put in and we haven't decided if we want it or not. See https://github.com/longhorn/longhorn/issues/505
