### ISSUE TITLE
[CI] Move CI builds to Github Action

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#8039]
## Additional context

cc @yangchiu

**Comment by innobead** [comment]
cc @rebeccazzzz

**Comment by innobead** [comment]
@FrankYang0529 It is necessary to backport to 1.6.x and 1.5.x. Otherwise, PRs for those branches will keep using drone-pr.

**Comment by derekbit** [comment]
Close the ticket because it is finished.

cc @FrankYang0529
