### ISSUE TITLE
[IMPROVEMENT] Move volume trim operation into volume controller

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8050]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

This is an open discussion on improvement.

Currently, the implementation of trimming a volume lies outside of the volume controller ([codes](https://github.com/longhorn/longhorn-manager/blob/master/manager/volume.go#L592-L612)). Users can trigger it via an HTTP call. However, this design is contrary to the current design pattern, which typically involves initiating operations by modifying custom resources.

**Comment by derekbit** [comment]
WDYT cc @innobead @shuo-wu @c3y1huang

**Comment by derekbit** [comment]
Close the ticket, becasue it is a subtask of https://github.com/longhorn/longhorn/issues/8052

**Comment by innobead** [comment]
> WDYT cc @innobead @shuo-wu @c3y1huang

Sounds good.
