### ISSUE TITLE
[TASK] Fix errors when upgrading K8s lib to 0.30

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#8056]
## What's the task? Please describe

https://github.com/longhorn/longhorn-manager/pull/2592#issuecomment-1966288524

**Comment by derekbit** [comment]
Test compatibility old k8s <-> new k8s (system backup/restore)

**Comment by ejweber** [comment]
> Test compatibility old k8s <-> new k8s (system backup/restore)

I agree with @derekbit. I think the focus of this issue should be on ensuring system backup/restore is working appropriately after the changes.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `63cf8e`)

[test_system_backup_restore](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6993/testReport/tests/test_system_backup_restore/) related test cases all passed(both s3 and nfs)
