### ISSUE TITLE
[IMPROVEMENT] Docker build of instance-manager should error out if the execution of SPDK pkgdep.sh fails

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8063]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Docker build of instance-manager should error out if the execution of SPDK pkgdep.sh fails.
Related to https://github.com/longhorn/longhorn/issues/8059

**Comment by roger-ryao** [comment]
**Verified on master-head 20240619**

- longhorn-instance-manager `master-head` https://github.com/longhorn/longhorn-instance-manager/commit/23380ad90d25951c30739b2ebce822b41bda10dc

**The test steps**
https://github.com/longhorn/longhorn/issues/8063#issuecomment-2153801490

**Result Passed**
