### ISSUE TITLE
add new node pool 

### ISSUE THREAD

**Issue by cometta** [longhorn/longhorn#8065]
My existing k8s cluster is working well with longhorn. After added a new node pool into the existing k8s cluster. i spun up a new pod on the new node pool, i get error 

```
Warning  FailedAttachVolume  74s (x14 over 13m)    attachdetach-controller  AttachVolume.Attach failed for volume "pvc-c7040375-9663-4a3e-9fea-fdde7ef27d4f" : CSINode cluster-name-masked -bf7ed2c8-gvlh does not contain driver driver.longhorn.io
```
how to add longhorn support on the new nodepool ? do i need to re-run any command?

csi-attacher-*** pod show below error on the new node pool
```
 I0228 11:48:05.284251       1 csi_handler.go:234] Error processing "csi-32d229529e507ee7ce9790c79df88f1a92bc502e7a0e893837829be8287b6a21": failed to attach: CSINode clsuter-name-masked
│ ed2c8-gvlh does not contain driver driver.longhorn.io
```

**Comment by derekbit** [comment]
Do you have any taints or tolerations on these nodes?
A support bundle is appreciated.

**Comment by derekbit** [comment]
Can you send us a support bundle?

**Comment by derekbit** [comment]
OK. The node `gke-dataops-gpu-cluster-gpu-np0-bf7ed2c8-9pxd` is tainted with `nvidia.com/gpu=present:NoSchedule`, but the longhorn components cannot tolerate it.
Please check the document https://longhorn.io/docs/1.6.0/advanced-resources/deploy/taint-toleration/ and set appropriate tolerations for the components.

**Comment by derekbit** [comment]
`disks are unavailable`-> Can you check the spec.diskStatus of the newly added node by `kubectl -n longhorn-system get nodes.longhorn.io -o yaml`?

**Comment by derekbit** [comment]
Can you try 
- Delete the disk from the node gke-test-gpu-cluster-cpu-np0-3228fc14-9h19
- Delete `/var/lib/longhorn/longhorn-disk.cfg` on the node
- Add the disk /var/lib/longhorn back

**Comment by derekbit** [comment]
Please check https://longhorn.io/docs/1.6.0/nodes-and-volumes/nodes/multidisk/.
Can you provide a new support bundle? I'd like to checkh how the error is triggered. 

```
          message: 'Disk default-disk-d1568ee2a91a8a33(/var/lib/longhorn/) on node
            gke-test-gpu-cluster-cpu-np0-3228fc14-9h19 is not ready: record diskUUID
            doesn''t match the one on the disk '
```

**Comment by derekbit** [comment]
```
AttachVolume.Attach failed for volume "pvc-5d4bc87d-b1bd-404f-a9fe-cc66fb811300" : CSINode gke-something 0-bf7ed2c8-m2wc does not contain driver driver.longhorn.io
```

You don't set the correct key. Isn't key `nvidia.com/gpu=present`?

**Comment by derekbit** [comment]
To avoid being confused. Let's focus on the CSINode first.
Can you fix the key of the tolerations and try longhorn.io/docs/1.6.0/advanced-resources/deploy/taint-toleration/?

**Comment by derekbit** [comment]
I mean why you set `key: key` rather than `key: nvidia.com/gpu=present`.

**Comment by derekbit** [comment]
You can follow the steps in longhorn.io/docs/1.6.0/advanced-resources/deploy/taint-toleration. 
You need to update tolerations in the `longhorn_values.yaml`, and the key should be `key: nvidia.com/gpu=present` rather than `key`.
Then, run `helm upgrade longhorn longhorn/longhorn --namespace longhorn-system --values ./longhorn_values.yaml`.
If you still run into the issue, please provide the content of `longhorn_values`.

**Comment by derekbit** [comment]
Sorry, should be (key is "nvidia.com/gpu" and value is "present").
Let's try it.
```
longhornManager:
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Equal"
    value: "present"
    effect: "NoSchedule"
longhornDriver:
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Equal"
    value: "present"
    effect: "NoSchedule"
longhornUI:
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Equal"
    value: "present"
    effect: "NoSchedule"
```

**Comment by derekbit** [comment]
A support bundle is appreciated. BTW, you can ping me on Rancher or CNCF Slack channel for speeding up the process.

**Comment by derekbit** [comment]
@cometta 
BTW, have you execute the step 2 in https://longhorn.io/docs/1.6.0/advanced-resources/deploy/taint-toleration/?
```
defaultSettings:
  taintToleration: "nvidia.com/gpu=present:NoSchedule"
```
