### ISSUE TITLE
[TASK] Generate BackupBackingImage Backend API

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#8068]
## What's the task? Please describe

To support BackupBackingImage on UI
We need to generate BackupBackingImage related API

1. Get `BackupBackingImages (list)`
2. Get `BackupBackingImage`
3. Delete `BackupBackingImage`
4. For each BackupBackingImage, we have action `backupBackingImageRestore`
5. For each BackingImage, we have new action `backupBackingImageCreate`

## Additional context

ref: UI ticket: https://github.com/longhorn/longhorn/issues/7541

**Comment by innobead** [comment]
cc @scures

**Comment by innobead** [comment]
@ChanYiLin let's add related labels as well for better context.

**Comment by ChanYiLin** [comment]
I have linked the task with the UI ticket.

**Comment by chriscchien** [comment]
Verified `pass` on longhorn master(longhorn-manager `340c10`) with test [steps](https://github.com/longhorn/longhorn/issues/8068#issuecomment-1972751649)

I can use backend API to perform below action without problem :
- Create BackupBackingImage
- Get BackupBackingImage
- Restore BackingImage from BackupBackingImage
- Delete BackupBackingImage
