### ISSUE TITLE
[BUG] no Pending workload pods for volume xxx to be mounted

### ISSUE THREAD

**Issue by Pionerd** [longhorn/longhorn#8072]
## Describe the bug

On two separate clusters I noticed that **all** my pods running Longhorn volumes showed the following warning (also described by someone else [here](https://serverfault.com/questions/1153631/what-does-failedmount-no-pending-workload-pods-for-volume-mean)). My biggest worry is that in Prometheus (since the start of the issue a few days ago) there is no data, even though the pods do seem to be functioning fine. So the main issue is with observability, even though I can't really explain why the pods function fine otherwise. No alerts (Longhorn related or otherwise) pointed me to this behaviour. Restarting the pod removes the issue (for now).

## To Reproduce

Unknown.

## Expected behavior

No warning. Prometheus observability.

## Support bundle for troubleshooting

I still have some pods running with the issue. I will email it to you.

## Environment

 - Longhorn version: v1.6.0
 - Impacted volume (PV): among others, pvc-fac8fb79-0194-469f-a111-6abf802ddc04
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2 v1.28.6+rke2r1
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 22.04.3 LTS
   - Kernel version: 5.15.0-97-generic
   - CPU per node: 2
   - Memory per node: master 4 GiB, worker 8 GiB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): enough
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Hyper-V
 - Number of Longhorn volumes in the cluster: 6

## Additional context

Edited later: other observed symptoms:
- When restarting the affected pods with PVs, I also got a separate: `The pod csi-attacher-5c4bfdcf59-pd6lx was killed because it was in Error state for too long. Please investigate.` The termination message: `Lost connection to CSI driver, exiting`. 

`csi-plugin` pods show same error: `time="2024-02-29T09:42:01Z" level=error msg="NodePublishVolume: err: rpc error: code = Aborted desc = no Pending workload pods for volume pvc-fac8fb79-0194-469f-a111-6abf802ddc04 to be mounted: map[Running:[oauth2-proxy-redis-master-0]]" func=csi.logGRPC file="server.go:138"`

The issue seems to have started after a rolling restart of the RKE nodes (which we do more often without any issue.

**Comment by Pionerd** [comment]
I sent it to the mentioned email address this morning (I suspect it contains identifying information).

**Comment by derekbit** [comment]
@c3y1huang Would you be able to take a look? Thanks.

Ref: https://github.com/longhorn/longhorn-manager/pull/2494/files

**Comment by c3y1huang** [comment]
1. Seems like somehow Kubelet dispatched another NodePublishVolume despite the Pod being already in the running state. Could you verify that is the state of those pods?
1. I cannot find related events in the support-bundle, I guess because they get cleared out after an hour. Is the `no Pending workload pods for volume xxx to be mounted` recurring?

**Comment by derekbit** [comment]
I can reproduce the issue by the following steps

1. Create a LH v1.6.0 2-nodes cluster 
2. Deploy a [deployment](https://github.com/longhorn/longhorn/blob/master/examples/deployment.yaml)
3. Restart kubelet on the attached node
4. Then, the `no Pending workload pods for volume xxx to be mounted` message is repeatedly emited

cc @c3y1huang

**Comment by innobead** [comment]
@c3y1huang Please also add this issue to the known issue wiki page for the impacted versions.

**Comment by tibeer** [comment]
Adding myself here to get notified about updates.

**Comment by ggogel** [comment]
I ran into this issue after rebooting a node. Except for one pod, all pods successfully started and attached the volume despite throwing the error event. Deleting the affected pods stopped the error events.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240325**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/83532b73437e2743716d65527a2ffcfd6ea05157
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/3f99a66d07a5fc15081b24fc885941b7d0b49cbc

**The test steps**

https://github.com/longhorn/longhorn/issues/8072#issuecomment-1972508954

**Result Passed**

. We do not see the warning in the longhorn-csi-plugin.log on `master-head`.

**Comment by roger-ryao** [comment]
> I ran into this issue after rebooting a node. Except for one pod, all pods successfully started and attached the volume despite throwing the error event. Deleting the affected pods stopped the error events.
> 
> Version v1.5.4

The fix will be included in `v1.5.5` for the issue https://github.com/longhorn/longhorn/issues/8082.
