### ISSUE TITLE
[TASK] SPDK raid merge with upstream

### ISSUE THREAD

**Issue by DamiaSan** [longhorn/longhorn#8074]
## What's the task? Please describe

We need to recreate the development made to grow the number of base bdevs of a raid1. To have raid1 support, last year we started from a version of spdk still under review in Gerrit: after having imported this version in our repo, some great changes have been made on the version under review. So we need to adapt our development to this new code base.

## Describe the sub-tasks

- [x] `Replace raid suspend/resume with bdev quiesce/unquiesce`
- [x] `Make sure the rebuild does not start when growing a raid`
- [x] `Add raid grow e2e test`

**Comment by innobead** [comment]
cc @derekbit @shuo-wu
