### ISSUE TITLE
[IMPROVEMENT] Update sizes in Engine and Volume resources less frequently

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#8076]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Per the investigation in https://github.com/longhorn/website/pull/875/files, an individual `Engine` or `Volume` under constant write I/O may cause the creation of millions of etcd revisions in a matter of months due to changes in its used space. While it is important to keep these size values updated, it may not be necessary to track them quite so closely.

The user who prompted the investigation reported seeing regular etcd defragmentations as a result. While defragmentations aren't generally problematic, they temporarily reduce etcd cluster availability and are better avoided when possible.

## Describe the solution you'd like

The node controller already truncates the usable storage it reports to the nearest 100 MiB. This prevents it from prompting a `Node` resource update (and etcd revision) when the change is relatively small.

It looks like we can do the same thing for `Engine` and `Volume` space consumption (which is already potentially updated much more frequently than `Node` space anyway). 100 MiB is likely not the right value for truncation since these objects only consider a single volume and not an entire node, but some smaller value probably makes sense.

## Describe alternatives you've considered

We could do nothing. The user did not report actual problems in their cluster as a result of the defragmentation, so this is a minor optimization.

**Comment by PhanLe1010** [comment]
We might need to modify the e2e test to have bigger write to observe the size change if we truncates the usable storage it reports to the nearest 100 MiB

**Comment by ejweber** [comment]
The current plan is to change the approach used and create a new PR. See https://github.com/longhorn/longhorn-manager/pull/2817#issuecomment-2140632472 for details.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `2f4628`) with test [steps](https://github.com/longhorn/longhorn-manager/pull/2837#issuecomment-2142544566)

- Write 1 MiB/s to longhorn volume, the enging controller will update size every 30 sec. following the value of [sizeUpdateLimit](https://github.com/longhorn/longhorn-manager/blob/2f46282b8735cfaa3bf5420b7cea75d78aa4c906/controller/engine_controller.go#L68C2-L68C17)
- Write 12 MiB/s to longhorn volume, the enging controller will update size about every 5 secs.
