### ISSUE TITLE
[BUG] Replica rebuild failed

### ISSUE THREAD

**Issue by CC007** [longhorn/longhorn#8091]
## Describe the bug
I have 4 storage nodes, each with a 700GBish volume attached, located on a CIFS mounted network drive.
One of my nodes needed to be restarted, but after doing so, the replica showed issues. Even worse: the other replicas also started having issues, so the PV couldn't be restored.

## To Reproduce

 - have a k8s cluster with at least 4 raspberry pi worker nodes (Aarch64) with individual CIFS storage network drives mounted on each of the nodes
 - setup longhorn and specify volumes to (a subfolder of) each of those network drives. 
 - Setup a nexus deployment with persistent storage (as an example for using the longhorn storage). Make sure that this PV has replicas set to 3.
 - restart one of the nodes that hosts one of the replicas

## Expected behavior

The downed node and it's unavailable replica gets detected and a new replica is created on the one node that doesn't have one yet. 
Once the restarted node becomes available again, the extra replica (that is probably stale) will be deleted, since there are already 3 healthy replicas.

## Support bundle for troubleshooting
https://we.tl/t-wvf0Lermpx

## Environment

 - Longhorn version: v1.5.3
 - Impacted volume (PV): pvc-31beb8d6-d966-4859-97e8-6840ef520210 and pvc-c8e00294-f5d7-479b-8e45-276e2013b193
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher (using chart longhorn:102.3.1+up1.5.3 )
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s v1.26.10+k3s1 
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 5
 - Node config
   - OS type and version: Ubuntu 22.04.3 LTS
   - Kernel version: 5.15.0-1047-raspi aarch64
   - CPU per node: 4 cores
   - Memory per node: 8GB
   - Disk type (e.g. SSD/NVMe/HDD): NVMe SSD in a NAS, connected with a CIFS mount.
   - Network bandwidth between the nodes (Gbps): 1Gb
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): 8x Raspberry PI 4B (for nodes) and QNAP TBS-464 (for NAS)
 - Number of Longhorn volumes in the cluster: 2

## Additional context

![afbeelding](https://github.com/longhorn/longhorn/assets/5381337/d5166a75-b56d-43be-b48a-067040c4faef)
![afbeelding](https://github.com/longhorn/longhorn/assets/5381337/d8a433ad-d5d1-43de-a342-7d539b1dfcaa)
![afbeelding](https://github.com/longhorn/longhorn/assets/5381337/eb8aaae3-8385-42a7-ac17-09801d5e1a21)
![afbeelding](https://github.com/longhorn/longhorn/assets/5381337/d15cb8b0-55e7-4549-a3b8-53652ab1158d)

**Comment by derekbit** [comment]
Found errror 
```
2024-03-02T14:44:06.656578495+01:00 time="2024-03-02T13:44:06Z" level=error msg="Failed to coalesce volume-snap-3410a691-16ce-45fb-903f-e2458b84e1f0.img to volume-snap-97e42d0c-0eef-4297-a841-18a10abae480.img" func="rpc.(*SyncAgentServer).processRemoveSnapshot" file="server.go:1328" error="file sizes are not equal and the parent file is larger than the child file"
```

Can you list the files in each replica directory of the volume `pvc-31beb8d6-d966-4859-97e8-6840ef520210` by `ls -al /path/to/replica/directory`?

**Comment by CC007** [comment]
Extra info:
I have 2 rows of 5 RPIs (node 1-1 to node 1-5 and node 2-1 to node 2-5), of which node 1-1 and node 2-1 aren't part of the cluster (they are part of a separate Rancher management cluster). 
My storage-connected nodes are node 1-3, 1-4, 2-3 and 2-4.

This is my mount setup in `/etc/fstab` to connect to my nas:
![afbeelding](https://github.com/longhorn/longhorn/assets/5381337/7015c629-6c33-4e64-8fcc-5fa40c9f48c4)

However one of the mounts seems to be down:
![afbeelding](https://github.com/longhorn/longhorn/assets/5381337/98bc4dde-c5e8-43a6-82da-f6897fb2fb98)

That should still leave enough nodes for 3 replicas though.
If I look at the files though, I only see `pvc-31beb8d6-d966-4859-97e8-6840ef520210` on node 2-4 and `pvc-c8e00294-f5d7-479b-8e45-276e2013b193-202cf3b4` on node 2-3. The other pvc's I think are from earlier attempts to use Longhorn where I ran into similar issues.
![afbeelding](https://github.com/longhorn/longhorn/assets/5381337/28e04216-4349-42b5-b620-4f30cd3c65cc)

A couple of days ago when the issues started, I could still see 2 of the 3 replicas for each pvc, but the other replicas seem to have deleted themselves.

The drive that wasn't mounted does still contain `pvc-31beb8d6-d966-4859-97e8-6840ef520210`, but not `pvc-c8e00294-f5d7-479b-8e45-276e2013b193-202cf3b4`
![afbeelding](https://github.com/longhorn/longhorn/assets/5381337/917dc5b8-9a27-4e16-8f84-1b5f07499d01)

**Comment by CC007** [comment]
After restarting node 1-4, the mount is connected again:
![afbeelding](https://github.com/longhorn/longhorn/assets/5381337/5e31bfb3-7c7b-485f-abf6-fb0a40328e71)

But Longhorn doesn't seem to have noticed that:
![afbeelding](https://github.com/longhorn/longhorn/assets/5381337/d8709f54-e8a2-40ad-a204-c010443320fa)

As you can see, 1-4 is not listed in replicas

**Comment by CC007** [comment]
![afbeelding](https://github.com/longhorn/longhorn/assets/5381337/ba6d6243-f5f0-4705-9821-8b765f940956)

**Comment by derekbit** [comment]
Thanks @CC007 
The size of the snapshot file `volume-snap-3410a691-16ce-45fb-903f-e2458b84e1f0.img` is somehow 0.
Did you expand the volume `pvc-31beb8d6-d966-4859-97e8-6840ef520210` before?
Can you dump the content of `*.meta`? Let's try to manual fix it.

**Comment by CC007** [comment]
Actually, no. It was 50GB since the start. I did expand `pvc-c8e00294-f5d7-479b-8e45-276e2013b193` however from 16 to 160GB. That's also the most important one for me, containing Nexus data. `pvc-31beb8d6-d966-4859-97e8-6840ef520210` only contains grafana metrics that are out of date now anyway.

I'll download the nexus pvc it and keep you updated.

**Comment by derekbit** [comment]
> Actually, no. It was 50GB since the start. I did expand `pvc-c8e00294-f5d7-479b-8e45-276e2013b193` however from 16 to 160GB. That's also the most important one for me, containing Nexus data. `pvc-31beb8d6-d966-4859-97e8-6840ef520210` only contains grafana metrics that are out of date now anyway.
> 
> I'll download the nexus pvc it and keep you updated.

It might be somehow caused by the failure of expansion, but I didn't find any clue in the support bundle.
You can back up (copy out) the replica directory of the volume `pvc-c8e00294-f5d7-479b-8e45-276e2013b193` and `pvc-31beb8d6-d966-4859-97e8-6840ef520210` before manually fixing them.
Then, as I mentioned above, dump the content of `*.meta` (`cat *meta) and list the files (`ls -al *) inside the two directories. I can check how to manual fix them.

**Comment by CC007** [comment]
Here's the metafiles of `pvc-c8e00294-f5d7-479b-8e45-276e2013b193`
[meta files.zip](https://github.com/longhorn/longhorn/files/14499640/meta.files.zip)

What is the easiest way to drop `pvc-31beb8d6-d966-4859-97e8-6840ef520210` and let grafana work again? I don't care about the contents of those. I only need my Nexus data back. (I can still provide the meta files for diagnosis purposes before doing this).

**Comment by CC007** [comment]
Here are the meta files for `pvc-31beb8d6-d966-4859-97e8-6840ef520210`
[pvc-31beb8d6-d966-4859-97e8-6840ef520210 on node 1-4.zip](https://github.com/longhorn/longhorn/files/14499784/pvc-31beb8d6-d966-4859-97e8-6840ef520210.on.node.1-4.zip)
[pvc-31beb8d6-d966-4859-97e8-6840ef520210 on node 2-4.zip](https://github.com/longhorn/longhorn/files/14499785/pvc-31beb8d6-d966-4859-97e8-6840ef520210.on.node.2-4.zip)

**Comment by derekbit** [comment]
@CC007 
Let's focus pvc-c8e00294-f5d7-479b-8e45-276e2013b193 first.
Except for the metafiles, can you provide the file list (`ls -al`) of the replica directories of `pvc-c8e00294-f5d7-479b-8e45-276e2013b193`? Thanks.

**Comment by derekbit** [comment]
@CC007 Can you provide the list the files in the replica directory of `pvc-c8e00294-f5d7-479b-8e45-276e2013b193` by `ls -al`?

**Comment by derekbit** [comment]
For volume `pvc-31beb8d6-d966-4859-97e8-6840ef520210`, the disk `img` and `img.meta` files on `node 1-4` looks good. 
```
// volume-head-002.img.meta
{
   "Name":"volume-head-002.img",
   "Parent":"volume-snap-97e42d0c-0eef-4297-a841-18a10abae480.img",
   "Removed":false,
   "UserCreated":false,
   "Created":"2024-02-25T23:10:17Z",
   "Labels":null
}

// volume-snap-97e42d0c-0eef-4297-a841-18a10abae480.img.meta
{
   "Name":"volume-head-001.img",
   "Parent":"volume-snap-6191ca28-4f46-46db-81ec-9fd429e41806.img",
   "Removed":false,
   "UserCreated":false,
   "Created":"2024-02-25T23:10:17Z",
   "Labels":null
}

// volume-snap-6191ca28-4f46-46db-81ec-9fd429e41806.img.meta
{
   "Name":"volume-snap-6191ca28-4f46-46db-81ec-9fd429e41806.img",
   "Parent":"",
   "Removed":true,
   "UserCreated":false,
   "Created":"2024-02-25T23:04:23Z",
   "Labels":null
}


```

![image](https://github.com/longhorn/longhorn/assets/12527233/1e5b2dc6-b62d-48a7-ae81-e1fe505865f5)


You can try the steps to bring the volume back
1. Detach the volume by scaling down the workload
2. Temporarily back up (copy) the replica directory of `pvc-31beb8d6-d966-4859-97e8-6840ef520210` on `node 2-4`
3. Delete the replica resource on `node 2-4` via UI or kubectl command
4. Attach the volume by scaling up the workload

If the volume can be successfully attached, the backup of step 2 can be deleted.

If you are interested in the disk chain (*img and *img.meta), please see https://github.com/longhorn/website/blob/4f9d70a6384c663556103c2933362c20fc85d533/content/docs/1.6.0/nodes-and-volumes/internal-data-structures.md.

**Comment by CC007** [comment]
> For volume `pvc-31beb8d6-d966-4859-97e8-6840ef520210`, the disk `img` and `img.meta` files on `node 1-4` looks good.
> 
> ```
> // volume-head-002.img.meta
> {
>    "Name":"volume-head-002.img",
>    "Parent":"volume-snap-97e42d0c-0eef-4297-a841-18a10abae480.img",
>    "Removed":false,
>    "UserCreated":false,
>    "Created":"2024-02-25T23:10:17Z",
>    "Labels":null
> }
> 
> // volume-snap-97e42d0c-0eef-4297-a841-18a10abae480.img.meta
> {
>    "Name":"volume-head-001.img",
>    "Parent":"volume-snap-6191ca28-4f46-46db-81ec-9fd429e41806.img",
>    "Removed":false,
>    "UserCreated":false,
>    "Created":"2024-02-25T23:10:17Z",
>    "Labels":null
> }
> 
> // volume-snap-6191ca28-4f46-46db-81ec-9fd429e41806.img.meta
> {
>    "Name":"volume-snap-6191ca28-4f46-46db-81ec-9fd429e41806.img",
>    "Parent":"",
>    "Removed":true,
>    "UserCreated":false,
>    "Created":"2024-02-25T23:04:23Z",
>    "Labels":null
> }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/12527233/311426913-1e5b2dc6-b62d-48a7-ae81-e1fe505865f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5ODE4NDgsIm5iZiI6MTcwOTk4MTU0OCwicGF0aCI6Ii8xMjUyNzIzMy8zMTE0MjY5MTMtMWU1YjJkYzYtYjYyZC00OGE3LWFlODEtZTFmZTUwNTg2NWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDEwNTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYzc5Zjg1NjIwZmNiMmM3MjNjMTEyYzhjNjIxOWIyMmI4NWFkNDA2YmRhNmNhY2E3OWZmMjY1OWYwODUxMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bGrTWGX060XMbwk4uPDsR1oyc9M8IjOkcS-3O6vENJo)
> 
> You can try the steps to bring the volume back
> 
> 1. Detach the volume by scaling down the workload
> 2. Temporarily back up (copy) the replica directory of `pvc-31beb8d6-d966-4859-97e8-6840ef520210` on `node 2-4`
> 3. Delete the replica resource on `node 2-4` via UI or kubectl command
> 4. Attach the volume by scaling up the workload
> 
> If the volume can be successfully attached, the backup of step 2 can be deleted.
> 
> If you are interested in the disk chain (*img and *img.meta), please see https://github.com/longhorn/website/blob/4f9d70a6384c663556103c2933362c20fc85d533/content/docs/1.6.0/nodes-and-volumes/internal-data-structures.md.

I noticed `volume-snap97e42...`  has a name that points to a non-existent file. Could that be part of the issue?

**Comment by derekbit** [comment]
Sorry, which volume and node?

**Comment by CC007** [comment]
The middle meta file you posted from 1-4 which has volume-head-001.img as name

**Comment by derekbit** [comment]
> The middle meta file you posted from 1-4 which has volume-head-001.img as name

Got it.  The `Name` field in `*.img.meta` is not used. Instead, the `Parent` field means image file name.

**Comment by CC007** [comment]
Hmm ok. It is a bit confusing how it does sometimes refer to the old head and somtimes refers to its own shapshot id.

Btw here is the folder contents of `pvc-c8e00294-f5d7-479b-8e45-276e2013b193`:
![afbeelding](https://github.com/longhorn/longhorn/assets/5381337/66c039e3-f091-4847-b644-29037334ec15)

**Comment by derekbit** [comment]
> Hmm ok. It is a bit confusing how it does sometimes refer to the old head and somtimes refers to its own shapshot id.
> 

Well, as I mentioned above, this [doc](https://news.cnyes.com/news/id/5482118) will help you understand the meta files.

**Comment by derekbit** [comment]
@CC007 Can you try to attach `pvc-c8e00294-f5d7-479b-8e45-276e2013b193` and generate a new support bundle? Thank you.

**Comment by CC007** [comment]
Support bundle: https://we.tl/t-AlA14HZeG6
`pvc-c8e00294-f5d7-479b-8e45-276e2013b193-202cf3b4` folder on node 2-3 (excl. *.img files): [pvc.zip](https://github.com/longhorn/longhorn/files/14552735/pvc-c8e00294-f5d7-479b-8e45-276e2013b193-202cf3b4.on.node.2-3.zip)

**Comment by derekbit** [comment]
According to the latest support bundle, the volume `pvc-c8e00294-f5d7-479b-8e45-276e2013b193-202cf3b4` is stuck in the `detaching` state
```
2024-03-11T02:50:54.774626366+01:00 [longhorn-instance-manager] time="2024-03-11T01:50:54Z" level=debug msg="Process Manager: wait for process pvc-c8e00294-f5d7-479b-8e45-276e2013b193-e-0 to shutdown before unregistering process" func="process.(*Manager).unregisterProcess.func1" file="process_manager.go:260"
```

Can you enter the instance-manager pod on node `pirack1-node3` and show the results of `ps aux -www`? Thank you.

---

BTW, if you want to rescue the data in `pvc-c8e00294-f5d7-479b-8e45-276e2013b193-202cf3b4` first, you can
1. Copy the replica directory first (`cp -a pvc-c8e00294-f5d7-479b-8e45-276e2013b193-202cf3b4 ${temporary directory}`)
2. Rescue the data by the https://longhorn.io/docs/1.5.3/advanced-resources/data-recovery/export-from-replica/

**Comment by CC007** [comment]
![afbeelding](https://github.com/longhorn/longhorn/assets/5381337/c639c348-121d-481f-a3ea-4bcc4b96e2a2)

**Comment by CC007** [comment]
I don't need the files recovered. I have a copy of those already. I just preferrably need the replica recovered (it was a pain to load some large files into nexus), but thanks for that resource. It might be handy in the future.

What I mainly want is to know why replica rebuilding failed (and what to do to prevent this in the future).
Things I'd expect to happen:
 - given a cluster with 4 storage nodes
 - and a pvc with 3 running replicas
 - when a replica goes down (due to a node going down), longer than a configured timeout
 - then that replica gets marked for deletion (to prevent split brain)
 - and a new replica gets created, by cloning one of the 2 remaining replicas (during this time the pvc is read-only to prevent data corruption, alternatively, to keep the storage read-write, changes during the clone get logged and applied to the new replica after the clone ended).
 - the pvc is fully healthy again
 - when the old replica comes back up, it gets deleted, since it was marked for deletion.
 
If the recovery fails, I should always be able to restore to a previous snapshot, which would take down the current replicas and replace them with new replicas that are clones of the snapshot.

This would need to be stably working as a bare minimum for data integrity in my cluster

**Comment by ejweber** [comment]
For the stuck issue, I think we can refer to https://github.com/longhorn/longhorn/issues/7919. The vulnerability also exists in `v1.5.3`. We could confirm with the output of the following command (taken from https://github.com/longhorn/longhorn/issues/7915#issuecomment-1939633987) modified with the name of the instance-manager from the affected node.

```
kubectl port-forward -n longhorn-system <instance manager name> 6060:6060

# In another terminal:
curl --output goroutine.out http://localhost:6060/debug/pprof/goroutine?debug=1
```

**Comment by shuo-wu** [comment]
@ejweber The problematic code that leads to the deadlock lock issue https://github.com/longhorn/longhorn/issues/7919 is for https://github.com/longhorn/longhorn/issues/6386. And it is not in v1.5.3.

**Comment by PhanLe1010** [comment]
> @ejweber The problematic code that leads to the deadlock lock issue #7919 is for #6386. And it is not in v1.5.3.

Looks like you are right. I am sorry for overlooking it in the meeting! Maybe we can get mutex profiling like what @ejweber did at https://github.com/longhorn/longhorn/issues/7915#issuecomment-1939633987 to see if we can find any clue:

```
kubectl port-forward -n longhorn-system <instance manager name> 6060:6060

# In another terminal:
curl --output goroutine.out http://localhost:6060/debug/pprof/goroutine?debug=1
curl --output profile.out http://localhost:6060/debug/pprof/profile?debug=1
curl --output mutex.out http://localhost:6060/debug/pprof/mutex?debug=1
```

**Comment by shuo-wu** [comment]
@PhanLe1010 Unfortunately, the IM pod profiling is introduced in v1.6.0. The command you provide does not work either... https://github.com/longhorn/longhorn/issues/6377

**Comment by ejweber** [comment]
> @ejweber The problematic code that leads to the deadlock lock issue https://github.com/longhorn/longhorn/issues/7919 is for https://github.com/longhorn/longhorn/issues/6386. And it is not in v1.5.3. Would you explain a little bit more about The vulnerability also exists in v1.5.3?

> Looks like you are right. I am sorry for overlooking it in the meeting! Maybe we can get mutex profiling like what @ejweber did at https://github.com/longhorn/longhorn/issues/7915#issuecomment-1939633987 to see if we can find any clue:

Yes, sorry. I saw we backported to `v1.5.4` and assumed the vulnerability was in `v1.5.3`. However, it turns out the vulnerability was never released on the `v1.5.x` branch.

**Comment by CC007** [comment]
So would the backport resolve the issue I'm having?

**Comment by shuo-wu** [comment]
Currently, we are still investigating the reproducing step and the root cause of this issue. If this issue can be triggered in v1.6.x, the profiling tools introduced in v1.6.x should help debug. But it does not mean that v1.6.x should or shouldn't encounter the bug.

And the workaround is, killing the problematic instance manager pod `instance-manager-8a1fdf0ab37e55cb3db9439486dd0a29` and waiting for the restart. Before doing that, would you verify the following 2 issues?
1. Try to attach a new test volume to the node `pirack1-node3` the problematic instance manager pod resides on
2. Make sure no other volumes are running on that node before the killing

**Comment by innobead** [comment]
@shuo-wu can you summarize the final context for this issue? are we fixing a potential stuck process deletion to cause rebuild failure?

**Comment by shuo-wu** [comment]
The summary:
1. An unknown expansion failure after node reboot led to the messing up of the replica data file. Derek checked the support bundle but had no clue about this part. (And I didn't take effort on this either.)
2. When we tried to manually recover the volume, we found that the volume somehow got stuck in `detaching` state. The instance manager pod log indicated that the process record cached in the instance manager was stuck in state `stopping` but the actual process was already gone. We expect [this part](https://github.com/longhorn/longhorn-instance-manager/blob/7cd3a54ccf183e711928eb775a912f2222549609/pkg/process/process.go#L65-L79) should be executed after the actual process gone but No. Hence I introduced a timeout mechanism that allows the deletion call to continue handling/cleaning up the `stopping` process after a timeout. It's a **best-effort** fix since I cannot reproduce it.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-instance-manager e667fd0) following [the test plan](https://github.com/longhorn/longhorn/issues/8091#issuecomment-2019376012), and there is no related issue found on master branch daily regression.

**Comment by CC007** [comment]
I updated to 1.6.1, but got the same error. What I did:

- I uninstalled longhorn, along with ALL resources (making sure to not leave anything behind)
- I installed longhorn v1.6.1 (through rancher's chart: 103.3.0+up1.6.1)
- I set up the storage nodes (like before)
- I reinstalled nexus
- I checked if the replicas were all healthy (they were)
- I restarted one of my cluster nodes (making sure that that one contained one of the replicas)

I noticed the node becoming unhealthy (showing red or gray). This was expected, since it doesn't surprise me that it would first try to wait to see if the node comes back.

When the node comes back I see this message:
```
Start rebuilding replica pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-r-51bf25ab with Address 10.42.2.195:10000 for normal engine pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-e-0 and volume pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490
```
But then I get this error:
```
Failed rebuilding replica with Address 10.42.2.195:10000: proxyServer=10.42.0.156:8501 destination=10.42.0.156:10000: failed to add replica tcp://10.42.2.195:10000 for volume: rpc error: code = Unavailable desc = failed to get replica 10.42.2.195:10000: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 10.42.2.195:10000: i/o timeout"
```
Followed by a couple of:
```
Node pirack2-node4 is ready
```
And then
```
Engine image ei-ad735e4a (rancher/mirrored-longhornio-longhorn-engine:v1.6.1) is fully deployed on all ready nodes

Failed rebuilding replica with Address 10.42.2.213:10000: proxyServer=10.42.0.156:8501 destination=10.42.0.156:10000: failed to add replica tcp://10.42.2.213:10000 for volume: rpc error: code = Unknown desc = failed to sync files [{FromFileName:volume-snap-66c47248-5ddc-4e38-990e-4d57cd9f5615.img ToFileName:volume-snap-66c47248-5ddc-4e38-990e-4d57cd9f5615.img ActualSize:512} {FromFileName:volume-snap-66c47248-5ddc-4e38-990e-4d57cd9f5615.img.meta ToFileName:volume-snap-66c47248-5ddc-4e38-990e-4d57cd9f5615.img.meta ActualSize:0}] from tcp://10.42.7.226:10000: rpc error: code = Unknown desc = replica tcp://10.42.7.226:10000 failed to send file volume-snap-66c47248-5ddc-4e38-990e-4d57cd9f5615.img to 10.42.2.213:10004: failed to send file volume-snap-66c47248-5ddc-4e38-990e-4d57cd9f5615.img to 10.42.2.213:10004: rpc error: code = Unknown desc = open volume-snap-66c47248-5ddc-4e38-990e-4d57cd9f5615.img: invalid argument

Start rebuilding replica pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-r-51bf25ab with Address 10.42.2.213:10000 for normal engine pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-e-0 and volume pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490

snapshot becomes ready to use

replica pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-r-31aac936 failed the snapshot purge: failed to open parent file volume-snap-66c47248-5ddc-4e38-990e-4d57cd9f5615.img: open volume-snap-66c47248-5ddc-4e38-990e-4d57cd9f5615.img: invalid argument

snapshot becomes not ready to use

snapshot is marked as removed

replica pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-r-b2ff7e06 failed the restore: Failed to get restoring status on tcp://10.42.7.226:10000: failed to get restore status: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 10.42.7.226:10002: connect: connection refused"

replica pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-r-b2ff7e06 failed the snapshot purge: failed to open parent file volume-snap-66c47248-5ddc-4e38-990e-4d57cd9f5615.img: open volume-snap-66c47248-5ddc-4e38-990e-4d57cd9f5615.img: invalid argument

Detected replica pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-r-31aac936 (10.42.1.194:10000) in error

Detected replica pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-r-b2ff7e06 (10.42.7.226:10000) in error

lost track of the corresponding snapshot info inside volume engine

Volume pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490 requested remount at 2024-04-21T01:01:15Z after automatically salvaging replicas

Replica pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-r-31aac936 of volume pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490 will be automatically salvaged

Replica pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-r-b2ff7e06 of volume pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490 will be automatically salvaged

snapshot is marked as removed

Stops pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-e-0

Start rebuilding replica pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-r-51bf25ab with Address 10.42.2.213:10000 for normal engine pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-e-0 and volume pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490

Detected rebuilding replica pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-r-51bf25ab (10.42.2.213:10000)

snapshot becomes ready to use

Failed rebuilding replica with Address 10.42.2.213:10000: proxyServer=10.42.3.188:8501 destination=10.42.3.188:10000: failed to add replica tcp://10.42.2.213:10000 for volume: rpc error: code = Unknown desc = failed to sync files [{FromFileName:volume-snap-66c47248-5ddc-4e38-990e-4d57cd9f5615.img ToFileName:volume-snap-66c47248-5ddc-4e38-990e-4d57cd9f5615.img ActualSize:2343993344} {FromFileName:volume-snap-66c47248-5ddc-4e38-990e-4d57cd9f5615.img.meta ToFileName:volume-snap-66c47248-5ddc-4e38-990e-4d57cd9f5615.img.meta ActualSize:0} {FromFileName:volume-snap-4478c436-a23c-47de-a4b2-f89bc82ae501.img ToFileName:volume-snap-4478c436-a23c-47de-a4b2-f89bc82ae501.img ActualSize:162422784} {FromFileName:volume-snap-4478c436-a23c-47de-a4b2-f89bc82ae501.img.meta ToFileName:volume-snap-4478c436-a23c-47de-a4b2-f89bc82ae501.img.meta ActualSize:0}] from tcp://10.42.1.194:10000: rpc error: code = Unknown desc = replica tcp://10.42.1.194:10000 failed to send file volume-snap-4478c436-a23c-47de-a4b2-f89bc82ae501.img to 10.42.2.213:10006: failed to send file volume-snap-4478c436-a23c-47de-a4b2-f89bc82ae501.img to 10.42.2.213:10006: rpc error: code = Unknown desc = open volume-snap-4478c436-a23c-47de-a4b2-f89bc82ae501.img: invalid argument

replica pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-r-31aac936 failed the snapshot purge: failed to open childFile: open volume-snap-4478c436-a23c-47de-a4b2-f89bc82ae501.img: invalid argument

replica pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-r-b2ff7e06 failed the snapshot purge: failed to open childFile: open volume-snap-4478c436-a23c-47de-a4b2-f89bc82ae501.img: invalid argument

snapshot becomes not ready to use

snapshot is marked as removed

volume pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490 became degraded

Detected replica pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-r-b2ff7e06 (10.42.7.226:10000) in error

Detected replica pvc-31540f93-f81a-4864-a5bb-7e9d6bd5d490-r-31aac936 (10.42.1.194:10000) in error

...
```
Etc.

The one that stands out is the `invalid argument`

**Comment by derekbit** [comment]
@CC007 According to the logs you provided, the issue seems different from the original issue. Can you create a new ticket with the information you mentioned and a support bundle for further investigation? Thank you.

**Comment by CC007** [comment]
> @CC007 According to the logs you provided, the issue seems different from the original issue. Can you create a new ticket with the information you mentioned and a support bundle for further investigation? Thank you.

Done
