### ISSUE TITLE
[BUG] Deploying longhorn via helm results in manager pod fail

### ISSUE THREAD

**Issue by refuse2speak** [longhorn/longhorn#8093]
## Describe the bug

Installing Longhorn on k3s single node cluster via helm. Using values.yaml from GitHub (as linked in official installation guide on longhorn website) and adjusting Default Replica Count to 1 results in error.

<img width="861" alt="image" src="https://github.com/longhorn/longhorn/assets/96352231/6124927a-9ea2-4830-b8c5-226bc8b26fea">

Error:

```
k logs pods/longhorn-manager-8hn57                                                                           base at 󱃾 default/longhorn-system at   14:03:31
Incorrect Usage: flag provided but not defined: -upgrade-version-check
```

## To Reproduce

clean k3s running single master node

get values.yaml from longhorn GitHub repo as described in official installation guideline

adjust default replica count to 1

`helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace --values ./values.yaml --version 1.6.0
`

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
Please provide the content of `values.yaml`. It might be caused by incorrect images.

**Comment by bono5150** [comment]
The same issue for 1.8.0 version.

helm install longhorn longhorn/longhorn --namespace longhorn-system --version 1.8.0 --values values.yaml

K3s cluster, one control plane and three agents
Client Version: v1.31.4+k3s1
Kustomize Version: v5.4.2
Server Version: v1.31.4+k3s1

CNI: cilium
cilium-cli: v0.16.22 compiled with go1.23.4 on linux/amd64
cilium image (default): v1.16.4
cilium image (stable): v1.17.0
cilium image (running): 1.16.5

[values.txt](https://github.com/user-attachments/files/18738686/values.txt)

**Comment by bono5150** [comment]
I suspect that the problem is the example in the documentation that points to any values.yaml file and not specifically to the indicated longhorn version.

curl -Lo values.yaml https://raw.githubusercontent.com/longhorn/charts/master/charts/longhorn/values.yaml
vs.
https://github.com/longhorn/longhorn/blob/v1.8.x/chart/values.yaml
