### ISSUE TITLE
[TEST] Failed to execute `Longhorn-Rancher-chart-test` in test pipeline

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#8095]
## What's the test to develop? Please describe

I tried to trigger the `Longhorn Rancher chart test`, but they started failing after we switched AWS accounts. Rebuilding the last successful job also now fails during install. We need to investigate why the AWS account change broke the test.

## Additional context

The last successful job:  https://ci.longhorn.io/job/private/job/longhorn-rancher-chart-test/10/

**Comment by yangchiu** [comment]
@roger-ryao Please try again and see if there's still any issue. Many thanks.

**Comment by roger-ryao** [comment]
> @roger-ryao Please try again and see if there's still any issue. Many thanks.

Hi @yangchiu :
     When testing @mantissahz's Rancher v1.5.4 PR (https://ci.longhorn.io/job/private/job/longhorn-rancher-chart-test/35/consoleText), I found that when `LONGHORN_REPO` is set to `longhornio`, we didn't update the `livenessProbe.repository` value to `longhornio/livenessprobe`, which caused the `longhorn-csi-plugin` pod to enter a CrashLoopBackOff state.
     
Could you update the `livenessProbe.repository` value after the following lines in the main.tf file:
https://github.com/longhorn/longhorn-tests/blob/master/pipelines/utilities/rancher/terraform_install/main.tf#L54C1-L55C139

**Comment by yangchiu** [comment]
> Could you update the `livenessProbe.repository` value after the following lines in the main.tf file: https://github.com/longhorn/longhorn-tests/blob/master/pipelines/utilities/rancher/terraform_install/main.tf#L54C1-L55C139

Feel free to create any PR to improve our test pipelines. Thank you!

**Comment by roger-ryao** [comment]
> > Could you update the `livenessProbe.repository` value after the following lines in the main.tf file: https://github.com/longhorn/longhorn-tests/blob/master/pipelines/utilities/rancher/terraform_install/main.tf#L54C1-L55C139
> 
> Feel free to create any PR to improve our test pipelines. Thank you!

Hi @yangchiu 
    https://github.com/longhorn/longhorn-tests/pull/1808 is ready.
