### ISSUE TITLE
[BUG] manual restore of backup leads to error

### ISSUE THREAD

**Issue by adampetrovic** [longhorn/longhorn#8097]
## Describe the bug

Following the instructions from https://longhorn.io/docs/1.6.0/advanced-resources/data-recovery/recover-without-system/ leads to the following error.

```
./restore-backup-to-file.sh --aws-access-key <redacted> --aws-secret-access-key <redacted> --backup-url 's3://longhorn@us-east-1/backupstore?backup=backup-d9a4222aba314f6f&volume=pvc-5c31c54c-4315-46d9-a0b2-2a1113db8ce4' --output-file volume.raw --output-format raw --version v1.6.0
```

```
msg="Error running restore to file command" func=cmd.BackupCmd.RestoreToFileCmd.func4 file="restore_to_file.go:68" error="Volume doesn't exist in backupstore: cannot find backupstore/volumes/17/f1/pvc-5c31c54c-4315-46d9-a0b2-2a1113db8ce4/volume.cfg in backupstore"
```

I can see that this path is a directory, not a file (if that matters?)

```
# stat backupstore/volumes/17/f1/pvc-5c31c54c-4315-46d9-a0b2-2a1113db8ce4/volume.cfg/
  File: backupstore/volumes/17/f1/pvc-5c31c54c-4315-46d9-a0b2-2a1113db8ce4/volume.cfg/
  Size: 14        	Blocks: 0          IO Block: 4096   directory
Device: 4bh/75d	Inode: 70731       Links: 1
Access: (0770/drwxrwx---)  Uid: ( 1028/  docker)   Gid: (  100/   users)
Access: 2024-03-04 10:59:33.049346188 +1100
Modify: 2024-03-01 02:39:20.168681366 +1100
Change: 2024-03-01 02:39:20.168681366 +1100
 Birth: -

```

The same error happens when I use an NFS url directly too.

## To Reproduce

N/A (possibly user specific)

## Expected behavior

The backup restore process succeeds

## Support bundle for troubleshooting

Not relevant (no running longhorn system)

## Environment

 - Longhorn version: v1.6.0
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
`volume.cfg` is a regular file. Why is it a directory in your backupstore?

**Comment by derekbit** [comment]
`volume.cfg` is a regular file. Why is it a directory in your backupstore? 
Can you list all volume.cfg in the backupstore by `find ./ -name volume.cfg`?

**Comment by adampetrovic** [comment]
Apologies, circling back on this one. I was using NFS to directly access a Minio (self hosted S3 solution) volume. The way Minio works is that it stores metadata about files as a special file under a directory that has the same name as the file. When you access it via it's S3 endpoint it's exposed as a regular file.

Switching to use S3 instead of NFS fixed the issue.
