### ISSUE TITLE
During heavy network traffic, manager may lost connection to k8s api server, result in `end of watch`

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#81]
Need to investigate this issue. At least we should retry to reestablish the watch.

Got follow from a user's log.

```
reflector.go:334] github.com/rancher/longhorn-manager/vendor/k8s.io/client-go/informers/factory.go:73: watch of *v1.Pod ended with: too old resource version: 1552462 (1557439)
```

**Comment by yasker** [comment]
@TehTotalPwnage Can you find a way to reproduce the issue?

**Comment by yasker** [comment]
Push to v0.4. Cannot find a way to reproduce it.

**Comment by dnauck** [comment]
@yasker i think this issue was due too high cpu usage on the vms( 3 nodes with etcd, worker and control) (etcd is eating nearly 80% of a single core)

**Comment by yasker** [comment]
@dnauck Thanks, we will give high CPU workload a try.
