### ISSUE TITLE
Pod Affinity and Data Locality

### ISSUE THREAD

**Issue by HuxyUK** [longhorn/longhorn#810]
**Given the following scenario**

Three hyper-converged nodes and default settings with:
```default-replica-count: 2```

Is it possible to schedule pods to only run on nodes that have replicas stored on them? I'm assuming ensuring a pod always runs with at least one local replica would reduce the amount of network traffic needed to keep the data in sync? 

I ask as there are three nodes, of which two have active replicas at any time and there does not appear to be an obvious way for me to schedule the pod using affinities

**Comment by yasker** [comment]
I don't think there is a way to do that now. Kubernetes controls the scheduling of the pods, and the workload pods are started earlier than the Longhorn. The information about where are the replicas are not directly accessible by Kubernetes.

Maybe we can provide more replica information to Kubernetes by aggressively tag the nodes, but it can get messy easily. Not sure it's worth doing.

**Comment by HuxyUK** [comment]
Okay, thanks for the response. Yeah I was thinking "tagging" and pod affinities would be a possible solution, but the number of tags etc might make it undesirable. I think I will manually create the volumes and then set the pod affinity to be the same nodes. That should ensure data is local to the pod and save on my limited bandwidth.

**Comment by michaelandrepearce** [comment]
Could an approach with an extended scheduler thats aware of data location work here?

**Comment by debjitk** [comment]
@michaelandrepearce Any roadmap for `async` replication?
