### ISSUE TITLE
[FEATURE] Automatic online RWX volume expansion

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#8118]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Now we could only do expansion manually for RWX volume. https://longhorn.io/docs/1.5.4/volumes-and-nodes/expansion/#rwx-volume

## Describe the solution you'd like

When doing an RWX volume expansion by applying a modified manifest of the PVC or Longhorn UI, it could also automatically expand the volume filesystem on the shared manager pod.

We might be able to add a new `ShareManagerClient` API `FilesystemExpand` as [FilesystemTrim](https://github.com/longhorn/longhorn-share-manager/blob/master/pkg/client/share_manager_client.go#L41-L47), 
https://github.com/longhorn/longhorn-share-manager/blob/master/pkg/rpc/smrpc.proto#L7-L11

**Comment by ejweber** [comment]
Per the investigation at https://github.com/longhorn/longhorn/issues/6216#issuecomment-2220812095, https://github.com/longhorn/longhorn/issues/6216#issuecomment-2220861850, and https://github.com/longhorn/longhorn/issues/6216#issuecomment-2293835724, we should also make `NodeExpandVolume` a no-op for RWX volumes to avoid weird behaviors.

**Comment by james-munson** [comment]
This is accomplished by the changes in https://github.com/longhorn/longhorn/issues/9736

**Comment by james-munson** [comment]
Closing in favor of #9736
