### ISSUE TITLE
Longhorn Air Gap installation

### ISSUE THREAD

**Issue by martinounap** [longhorn/longhorn#812]
Hi

Could you please provide steps, how to set up longhorn in Air Gap enviroment.

We managed to do it with one of the old versions (if I rember it was 0.4.X)
But now we can not understand, hoe to do it.

I would be really thankful, if it is possible :)

**Comment by yasker** [comment]
@martinounap It should be possible. Normally the air gap installation requires the user to pull images beforehand on all the nodes and the image pull policy for the workload should be `IfNotPresent`. I can see there is [one line of code](https://github.com/longhorn/longhorn-manager/blob/74b92aa65f69ba0db11d2b05805f6b5f64a35e5d/controller/engine_image_controller.go#L663) which set one part of Longhorn image pull policy to `Always` can get in the way of air gap installation. We will try to figure out and document the process for air gap installation in the next release.

**Comment by martinounap** [comment]
@yasker 

We have managed to pull and push all imagaes to our private registy.
Then we have managed to provide yaml with registry secret creation. 

Then we upated yaml so, that it would use registry secret:
```yaml
spec:
      imagePullSecrets:
      - name: {secretName}
      containers:
      - name: longhorn-manager
        image: {regisryUrl}/longhornio/longhorn-manager:v0.6.2
```

We have problem with csi-attacher, csi-provisioner, engine-image-ei-XXXXXX, instance-manager-x-xxxx, longhorn-csi-plugin.

I will make suggestion that there would be variables in default-setting.yaml like:
  private-registry: {regisryUrl}
  private-registry-secret: {secretName}

And images should be in private registry:
  {regisryUrl}/longhornio/longhorn-manager:v0.6.2
  {regisryUrl}/longhornio/longhorn-ui:v0.6.2
  {regisryUrl}/longhornio/longhorn-engine:v0.6.2
  {regisryUrl}/quay.io/k8scsi/csi-attacher:v0.4.2
  {regisryUrl}/quay.io/k8scsi/csi-provisioner:v0.4.2
  {regisryUrl}/quay.io/k8scsi/driver-registrar:v0.4.1

And if those settings are provided, generated workloads would use private registry and secret.

**Comment by yasker** [comment]
@martinounap You can change the images in those lines to use the private repo:
1. https://github.com/longhorn/longhorn/blob/8385749346df76231ad357b9e120f36f59db3994/deploy/longhorn.yaml#L232
2. https://github.com/longhorn/longhorn/blob/8385749346df76231ad357b9e120f36f59db3994/deploy/longhorn.yaml#L234
3. https://github.com/longhorn/longhorn/blob/8385749346df76231ad357b9e120f36f59db3994/deploy/longhorn.yaml#L370

You can also specify the images to be used for drivers in the [driver-deployer](https://github.com/longhorn/longhorn/blob/8385749346df76231ad357b9e120f36f59db3994/deploy/longhorn.yaml#L362) using either parameters or environment variables:
```
	FlagCSIAttacherImage        = "csi-attacher-image"
	FlagCSIProvisionerImage     = "csi-provisioner-image"
	FlagCSIDriverRegistrarImage = "csi-driver-registrar-image"
	EnvCSIAttacherImage         = "CSI_ATTACHER_IMAGE"
	EnvCSIProvisionerImage      = "CSI_PROVISIONER_IMAGE"
	EnvCSIDriverRegistrarImage  = "CSI_DRIVER_REGISTRAR_IMAGE"
```
E.g.
```
    env:
    - name: CSI_ATTACHER_IMAGE
       value: {regisryUrl}/quay.io/k8scsi/csi-attacher:v0.4.2
```

**Comment by martinounap** [comment]
Hi...

...we managed to install it from private register. But we had couple of problmes, we needed to edit deployments/dameonsets manually after autocreate, because they did not have imagePullSecret set.

Maybe it would be good idea to add this settings to variables or to add possible to add it through longhorn-manager command.

**Comment by yasker** [comment]
@martinounap Yeah, we can add image pull secret as an option as well.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
  - [Airgap docs](https://github.com/longhorn/longhorn/blob/v0.8.1/docs/longhorn-airgap.md)
