### ISSUE TITLE
[BUG] longhorn-driver-deployer fail due to MountPropagation but environment_check.sh does not show any error

### ISSUE THREAD

**Issue by eltorio** [longhorn/longhorn#8148]
## Describe the bug

longhorn-driver-deployer refuse to deploy log show:
```log
W0311 08:41:51.506261       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2024-03-11T08:42:41Z" level=warning msg="Got an error when checking MountPropagation with node status, node oci-autour.private.berangere.oraclevcn.com is not support mount propagation" func=app.deployDriver file="driver.go:177"
time="2024-03-11T08:42:41Z" level=fatal msg="Error deploying driver: CSI cannot be deployed because MountPropagation is not set: node oci-autour.private.berangere.oraclevcn.com is not support mount propagation" func=app.DeployDriverCmd.func1 file="driver.go:141"
```
but `curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.6.0/scripts/environment_check.sh | bash`:  
```log
[INFO]  Required dependencies 'kubectl jq mktemp sort printf' are installed.
[INFO]  All nodes have unique hostnames.
[INFO]  Waiting for longhorn-environment-check pods to become ready (0/0)...
[INFO]  All longhorn-environment-check pods are ready (7/7).
[INFO]  MountPropagation is enabled
[INFO]  Checking kernel release...
[INFO]  Checking iscsid...
[INFO]  Checking multipathd...
[INFO]  Checking packages...
[INFO]  Checking nfs client...
[INFO]  Cleaning up longhorn-environment-check pods...
[INFO]  Cleanup completed.
```

## To Reproduce

On a 1.29.1 kubernetes cluster with longhorn 1.5.2, update to k8s 1.29.2 next update to longhorn 1.6.0

## Support bundle for troubleshooting

[Uploading supportbundle_5398826c-9de3-4845-88cb-691097e941ce_2024-03-11T09-00-31Z.zip…]()

## Environment

 - Longhorn version: 1.6.0
 - Impacted volume (PV): 
 - Installation method : helm chart
 - Kubernetes distro : bare metal
   - Number of control plane nodes in the cluster: 2
   - Number of worker nodes in the cluster: 5
 - Node config
   - OS type and version: Linux Ubuntu 22.0.4 LTS
   - Kernel version: 6.5.0
   - CPU per node: 6
   - Memory per node: 24 GB
   - Disk type : SSD
   - Network bandwidth between the nodes (Gbps): 1GBps
 - Underlying Infrastructure : Baremetal
 - Number of Longhorn volumes in the cluster: 10

**Comment by eltorio** [comment]
[supportbundle_5398826c-9de3-4845-88cb-691097e941ce_2024-03-11T09-00-31Z.zip](https://github.com/longhorn/longhorn/files/14556326/supportbundle_5398826c-9de3-4845-88cb-691097e941ce_2024-03-11T09-00-31Z.zip)

**Comment by ejweber** [comment]
Hello @eltorio.

The environment check script runs its own set of containers and verifies that they successfully run with mount propagation enabled.

The check that is failing works in two steps:

1. The node controller running with longhorn-manager on each node determines whether the longhorn-manager pod on that node is running with mount propagation. If it is, a MountPropagation condition is added to the corresponding node.longhorn.io CR.
2. The driver deployer checks that all node.longhorn.io objects have the condition.

The support bundle your provided only includes logs from the longhorn.io namespace, but no YAML files. Because of this, I cannot verify if the node.longhorn.io CR's have the expected status. Please consider attaching the missing files or sending them to longhorn-support-bundle@suse.com.

A couple of your longhorn-manager pods appear to be having extreme difficulty communicating with your Kubernetes API server. It is possible that these pods are unable to correctly sync the expected condition to the corresponding node.longhorn.io CR.

- longhorn-manager-gp56w is repeatedly failing to sync autour.
- longhorn-manager-42thj is repeatedly failing to sync both autour and bartevelle.

Perhaps the in-cluster KUBECONFIG these two pods rely on to communicate with the API server is broken? If so, deleting them may allow them to be correctly recreated and get things moving.

**Comment by eltorio** [comment]
Dear @ejweber ,
Thank you for your help, this cluster is a lab, so I deleted it and recreates from scratch. it stills have problem…
But on the new cluster (with same nodes) the support bundle fail with a 502 error.
 alll my other services are working.
 For investigating my cluster is a poor man HA cluster :), let me explain
there is two control planes (azure-gypaete and mikado), 
6 workers (all names are oci-[alpin bird names in french]).  (circaete,autour,bartavelle, tetraslyre, choucas, chocard)
on all nodes there is an haproxy listening on 127.43.43.43:6443 and distributing to 192.168.2.8:6443 (mikado) or 10.254.0.4 (azure-gypaete)

**Comment by ejweber** [comment]
Do your other workloads require the ability to communicate with the Kubernetes API server? It seems that this is problematic in the pods mentioned above, with every log being something like:

```
2024-03-11T08:21:52.716681200Z time="2024-03-11T08:21:52Z" level=error msg="Failed to sync Longhorn node" func=controller.handleReconcileErrorLogging file="utils.go:72" LonghornNode=longhorn-system/oci-autour.private.berangere.oraclevcn.com controller=longhorn-node error="failed to sync node for longhorn-system/oci-autour.private.berangere.oraclevcn.com: Put \"https://172.24.0.1:443/apis/longhorn.io/v1beta2/namespaces/longhorn-system/nodes/oci-autour.private.berangere.oraclevcn.com/status\": http2: client connection lost" node=oci-bartavelle.private.voza.oraclevcn.com

```

I am not sure why, but it seems either the HA configuration itself, the Kubernetes v1.29.2, or some combination is a likely culprit.

From the Longhorn side, we probably can't help much to fix the issue until the communication problems are resolved. In case it is some incompatibility between the version of the Kubernetes Go client we use and the v1.29.2 API server, I can try to get a small v1.29.2 cluster up and do a spot check, as only versions up to `v1.28` were tested for Longhorn `v1.6.0` (https://longhorn.io/docs/1.6.0/best-practices/#kubernetes-version).

**Comment by ejweber** [comment]
> In case it is some incompatibility between the version of the Kubernetes Go client we use and the v1.29.2 API server, I can try to get a small v1.29.2 cluster up and do a spot check, as only versions up to v1.28 were tested for Longhorn v1.6.0 (https://longhorn.io/docs/1.6.0/best-practices/#kubernetes-version).

I did run a single node v1.29.2 k3s cluster and was able to install and run Longhorn on it without issue. For now, this issue still looks related to the specific cluster networking.

**Comment by eltorio** [comment]
Rather to directly installing 1.6.0,
I revert to longhorn 1.5.4 everything is working, I'll try to upgrade for reproducing it.  
Only the "oci-*" nodes have sync problems. All this nodes are VM at Oracle OCI. They use a "special" Oracle kernel. Perhaps the MountPropagation fail is comming from this kernel ?

**Comment by eltorio** [comment]
investigations continue:  
I deleted many times the Cluster and tested with different CNI and longhorn versions
| CNI         | Longhorn      | Test               |
|-------------|---------------|--------------------|
| Cilium 1.14.1 | Longhorn 1.5.4 | :heavy_check_mark: |
| Cilium 1.14.8 | Longhorn 1.6.0 | :heavy_check_mark: |
| Cilium 1.15.1 | Longhorn 1.5.4 | :heavy_check_mark: |
| Cilium 1.15.1 | Longhorn 1.6.0 | :x: |

**Comment by ejweber** [comment]
Interesting. I'll give that failing combo of Cilium and Longhorn a shot.

Did you upgrade Cilium to `v1.15.1` alongside the upgrade to Kubernetes `v1.29.2`?

**Comment by eltorio** [comment]
@ejweber 
Dear Eric,
No I didn't tried to upgrade (yet) to Cilium 1.15.1. I'll try soon.
