### ISSUE TITLE
[IMPROVEMENT] Unregister the process when it fails to start in creation

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#8155]
## What's the task? Please describe

https://github.com/longhorn/longhorn-instance-manager/blob/6372baca91084d36461ea860f8e7b45115a1a858/pkg/process/process_manager.go#L252-L262

When process fails to start in creation, we should unregister the process

## Additional context
Need to make sure there is no regression issue.

**Comment by innobead** [comment]
Also, add the invalid label.
