### ISSUE TITLE
can't edit the node

### ISSUE THREAD

**Issue by yizhishang** [longhorn/longhorn#817]
*After i installed the longhorn from the catalog ,i can't edit the node.*

---
Version: `v0.6.2`

**Comment by yasker** [comment]
Can you elaborate the reproduce steps?

**Comment by yizhishang** [comment]
![图片](https://user-images.githubusercontent.com/12756407/66792595-0f8cdc80-ef2c-11e9-98ee-77a9be021e70.png)
![图片](https://user-images.githubusercontent.com/12756407/66792606-174c8100-ef2c-11e9-984c-35c6041cd819.png)
![图片](https://user-images.githubusercontent.com/12756407/66792615-216e7f80-ef2c-11e9-9bdc-5bb5dafa538f.png)

 i installed the longhorn from the catalog, and this is my settings

**Comment by yasker** [comment]
I meant, when you said `can't edit the node`, what operation you've taken and what's the response of the UI? For example, did you mean clicking `node` page has no response inside Longhorn UI? or clicking `edit node` has no response inside Longhorn UI? Or edit node has no response for Rancher UI?

**Comment by yizhishang** [comment]
![image](https://user-images.githubusercontent.com/12756407/67059099-35172180-f18a-11e9-90ff-e62da0bc5cca.png)

i found no button in the page to edit
