### ISSUE TITLE
[DOC] Typo on Longhorn-specific StorageClass parameters

### ISSUE THREAD

**Issue by Hazmi35** [longhorn/longhorn#8170]
## What's the document you plan to update? Why? Please describe

Based on https://longhorn.io/docs/1.6.0/snapshots-and-backups/scheduling-backups-and-snapshots/#with-storageclass-parameters, configuring a Longhorn-provided StorageClass with a Recurring Job selector parameters is done via `parameters.recurringJobSelector` key, but not on https://longhorn.io/docs/1.6.0/references/storage-class-parameters/#recurring-jobs-selector-field-parametersrecurringjobsselector which is `parameters.recurringJobsSelector`

I believe this is a typo on the latter part.

## Additional context

Was configuring StorageClass with a recurring job selector, followed the second page, turns out didn't work because of the extra is in parameters.recurringJob**s**Selector.

Created a PR in longhorn/website#883

**Comment by ejweber** [comment]
Thanks for the contribution @Hazmi35!
