### ISSUE TITLE
Docusaurus site acceptance testing

### ISSUE THREAD

**Issue by jhkrug** [longhorn/longhorn#8179]
Reviews needed of the new DS site, looking for problems in the DS static site. Anything identified can have an issue created? Or reported to me?

- [ ] Visual content reviews
- [ ] Visual styling reviews
- [ ] Search testing

- [ ] Various issues picked up in testing are [on this Confluence page](https://confluence.suse.com/x/KQQbWQ) and need addressing

- [ ] Any issues raised, prior to freeze, at [website-docusaurus](https://github.com/longhorn/website-docusaurus/issues)

New site is at: https://main--longhornio-docusaurus.netlify.app/

**Comment by innobead** [comment]
@jhkrug remember to add the doc label and add it to the current milestone which is 1.7.0.

**Comment by jhkrug** [comment]
Thank you.
