### ISSUE TITLE
DS requires an `authors.yml` file for the KB.

### ISSUE THREAD

**Issue by jhkrug** [longhorn/longhorn#8182]
The format of the authors tag is different between the blog posts and the knowledge base. The format used in the KB needs a `authors.yml` to act as a database of authors. The slightly different (an older?) form used in the blog posts does not. 

For now, I've added a basic `authors.yml` to the migration for the KB. Standardization between the two may be advisable for the future.

- [ ] KB and blog authors standardization

**Comment by innobead** [comment]
@jhkrug you can add issues to the current sprint (zenhub) if you start working on them.
