### ISSUE TITLE
[BUG] RWX test passes even when share-manager's ganesha process can't run.

### ISSUE THREAD

**Issue by james-munson** [longhorn/longhorn#8183]
## Describe the bug

As documented in https://github.com/longhorn/longhorn/issues/8166, we had a brief spell where the share-manager build made an nfs-ganesha image that failed at startup because it could not find a dynamic library.

In that interim, the regression tests ran in https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/848/ and every RWX test failed, except for one:  `test_encrypted_rwx_volume` passed. anyway.  How did it do that?

## To Reproduce

Update longhorn-share-manager's Dockerfile with a pointer to SLES 15.6 (beta), as was done by accident in #8166, and run the test case.  (I'm not sure that build is saved as a tagged image.)
Or inject any equivalent error that causes `ganesha.nfsd` process to fail at startup.

## Expected behavior

The test might be expected to fail, if the volume can't be attached because there is no nfs server.

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by khushboo-rancher** [comment]
Test is supposed to pass when the pod with PVC attached is running that means the volume should be attached and running.

```
    """
    Test creating encrypted rwx volume and use the secret in
    non longhorn-system namespace.

    1. Create crypto secret in non longhorn-system namespace.
    2. Create a storage class.
    3. Create a deployment with a PVC and the pods should be able to running.
    """
```

**Comment by james-munson** [comment]
Agreed.  @ejweber and I discussed this, and noted that the test calls `create_and_wait_deployment` which looks like it should wait until the pods are running (:
https://github.com/longhorn/longhorn-tests/blob/40cb77d35cf03f3fc5bc38fccfbbe79b94ace1b7/manager/integration/tests/common.py#L4798-L4810
Ultimately, 
> deployment.status.ready_replicas == desired_replica_count
So this is kind of a mystery.

**Comment by james-munson** [comment]
Although now that I look at `wait_deployment_replica_ready`
https://github.com/longhorn/longhorn-tests/blob/40cb77d35cf03f3fc5bc38fccfbbe79b94ace1b7/manager/integration/tests/common.py#L4783-L4795
It looks like it can return early if the criterion is met, or after DEFAULT_DEPLOYMENT_TIMEOUT = 240 seconds anyway, and there is no checking that the pods actually came ready if it times out.

**Comment by ejweber** [comment]
> It looks like it can return early if the criterion is met, or after DEFAULT_DEPLOYMENT_TIMEOUT = 240 seconds anyway, and there is no checking that the pods actually came ready if it times out.

Good find @james-munson. I thought that looked a bit suspicious when we were discussing it earlier, but assumed I was missing something.

**Comment by derekbit** [comment]
IIRC, I have fixed the issue in https://github.com/longhorn/longhorn-tests/pull/1672/files
BTW, can you help review it? Thank you.
