### ISSUE TITLE
[QUESTION]  Backups.longhorn.io "backup-4603c5338ee242e1" not found

### ISSUE THREAD

**Issue by DYYQ-SA** [longhorn/longhorn#8189]
## Question
source node backup one VM machine to target node, NFS error
my test like this
source 10.64.9.41
target   10.64.41.10
nfs storge: 10.64.50.254

first ,i backup one VM machine on the source to NFS storge,at that time ,i config the target with the same nfs storge.
when the source backup over,i restore the backup file to the target ,has error like the picture .

my question is when the same storge between above two longhorn cluster is not allow at the same time. if there has refresh mechanism at the target.

## Environment

 - Longhorn version:1.3.2
 - Kubernetes version:v1.24.6
 - Node config
   - OS type and version   Kylin Linux Advanced Server release V10 (Sword)  4.19.90-24.4.v2101.ky10.x86_64
   - Kernel version 
   - CPU per node:28c
   - Memory per node: 512G
   - Disk type nfs
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

## Additional context
![图片_0880c4c80710aebda618](https://github.com/longhorn/longhorn/assets/20239092/6b7031e8-7ea6-4d06-b56e-bc137b392494)
![图片_0880c4c80710aebdd71b](https://github.com/longhorn/longhorn/assets/20239092/6ca01e77-4ce9-4c41-abfb-d10725431101)
![图片_0880c4c80710aefdfe19](https://github.com/longhorn/longhorn/assets/20239092/5d6791a2-c502-47a2-995c-d98fbed2fa50)

**Comment by ejweber** [comment]
If I understand the question correctly you:

- Pointed ClusterA and ClusterB at the same BackupTarget.
- Created a backup in ClusterA.
- Expected the backup to be accessible from ClusterB, but it wasn't.

It is expected that backups from ClusterA will eventually be accessible in ClusterB. The setting [Backupstore Poll Interval](https://longhorn.io/docs/archives/1.3.2/references/settings/#backupstore-poll-interval) determines how long Longhorn in ClusterB will wait between attempts to check the backupstore (referenced by BackupTarget) for new backups. By default, it is `300 s / 5 min`.

Please check this setting and wait for at least as long as is configured. Then, check the Longhorn UI (or `kubectl get backup`) in both clusters to confirm the same backups appear in both clusters. If they do not, please upload a support bundle for some additional analysis.

**Comment by DYYQ-SA** [comment]
> If I understand the question correctly you:
> 
> * Pointed ClusterA and ClusterB at the same BackupTarget.
> * Created a backup in ClusterA.
> * Expected the backup to be accessible from ClusterB, but it wasn't.
> 
> It is expected that backups from ClusterA will eventually be accessible in ClusterB. The setting [Backupstore Poll Interval](https://longhorn.io/docs/archives/1.3.2/references/settings/#backupstore-poll-interval) determines how long Longhorn in ClusterB will wait between attempts to check the backupstore (referenced by BackupTarget) for new backups. By default, it is `300 s / 5 min`.
> 
> Please check this setting and wait for at least as long as is configured. Then, check the Longhorn UI (or `kubectl get backup`) in both clusters to confirm the same backups appear in both clusters. If they do not, please upload a support bundle for some additional analysis.

Thank you for your reply ,In deed like you understand, two more questions to discuss with you  
* it takes 40 min to backup cluster A,and more than 5 hours to restore cluterB,which parameter i need to setting on longhorn UI interface.
*  I have had such a problem before，when i backup clusterA has error,i need to delete including the job from UI interface,command on kubectl at the virtual machine，and delete the data from nfs storage. if there has a best way to drop backup job to clean all i mentioned automatic

**Comment by ejweber** [comment]
You may want to check the setting `failed-backup-time-to-live` to see if adjusting it helps your cleanup situation.

https://longhorn.io/docs/archives/1.3.2/references/settings/#failed-backup-time-to-live
