### ISSUE TITLE
[QUESTION] How to fix instance manager that is not running

### ISSUE THREAD

**Issue by ysicing** [longhorn/longhorn#8194]
k3s 1.28 & longhorn 1.6

```
kubectl get instancemanagers -n longhorn-system
NAME                                                DATA ENGINE   STATE     TYPE   NODE     AGE
instance-manager-3ff86cfc85c3971cedd90f5fdd99820b                           aio    ds1600   12h
instance-manager-6a6b039e2c1ad0d56c45bd81af77586c   v1            running   aio    ds1644   12h
instance-manager-7cda719f1c4c913697b83eac7926e886   v1            running   aio    ds1599   12h
```

ds1600

![image](https://github.com/longhorn/longhorn/assets/8605565/a145d67d-1bd1-463f-9bb6-457e05ce51d3)

**Comment by chriscchien** [comment]
Hi @ysicing , v1.6.1-rc is still in testing, perhaps using v1.6.0 would be a better idea and hope below options can assist you:

- run the environment check script on your cluster `bash -c "$(curl -sfL https://raw.githubusercontent.com/longhorn/longhorn/v1.6.0/scripts/environment_check.sh)" -s -s`
- check the state of node ds1600
- describe pod `instance-manager-3ff86cfc85c3971cedd90f5fdd99820b`

**Comment by ysicing** [comment]
thx, fixed
delete instance-manager pods, rebuild instance-manager.
