### ISSUE TITLE
[QUESTION] failed to list snapshot: cannot get client for volume pvc-*: more than one engine exists

### ISSUE THREAD

**Issue by DYYQ-SA** [longhorn/longhorn#8197]
## Environment

 - Longhorn version: longhorn 1.3.2
 - Kubernetes version: 1.24.6
 - Node config
   - OS type and version  kylin v10
   - Kernel version  4.19.90-24.4.v2101.ky10.x86_64
   - CPU per node: 28c
   - Memory per node: 512Gb
   - Disk type 
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

## Additional context
purpose: backup virtual machine 10.64.16.39
error:  when i start the backup ,no response to snapshot and no data to the nfs storge
question: Is it related to  two engine？and if i cut down one engine,how to make sure the  virtual machine sucess
Specific details：

virt-launcher-budsc-vm-1639-w24fl  on two of master (hg-clueser-2-master02 and hg-clueser-2-master03)

![WeChat截图_20240318165042](https://github.com/longhorn/longhorn/assets/20239092/20e69055-c0c9-4846-8c00-615251d2c802)
![WeChat截图_20240318164559](https://github.com/longhorn/longhorn/assets/20239092/d805e7fe-5cde-4421-965f-8063c54e0830)

**Comment by ejweber** [comment]
This behavior is improved in later versions of Harvester/Longhorn. Closing since the discussion has ended.
