### ISSUE TITLE
[UI] add some more details about storage to webui/dashboard

### ISSUE THREAD

**Issue by dnauck** [longhorn/longhorn#82]
Hello,

some more info about volumes and the storage would help a lot:

1. show k8n claim name (or even the associated deployments) side by side with the volume name if possible (volume names are just a guid)
2. ~shows used storage/space per volume~ **(implemented in v0.3.0)**
3. ~show used storage/space for snapshots and backups per volume~ **(implemented in v0.3.0)**
4. ~show used storage/space by node (do i run out of disk space? maybe show storage growth and calculate day when storage runs out of space)~ **(implemented in v0.3.0)**
5. show info about scheduled backups (everything green and healthy?)
6. show info about too large/old snapshots that impact performance (like vmware does)
7. show storage latency and i/o wait/queue, etc (by volume?!)

**Comment by yasker** [comment]
1. The associated K8S resource may not be a information available to the storage vendor. We can look into it
2. Yeah, we should do it
3. We have the real size shown for the backup. We have snapshot size in the backend. Need to show that in the UI.
4. Will be in the upcoming multiple disk support.
5. This one is missing. We should able to get some information from k8s CronJob.
6. Um, large snapshots don't impact much of Longhorn performance currently. But I got what you meant. We will help the user to achieve the optimal performance.

**Comment by yasker** [comment]
2, 3, 4 has been implemented in v0.3.0.

**Comment by yasker** [comment]
Item 1 and 5 have been implemented in v0.5.0

**Comment by yasker** [comment]
Only remain item is 7, which is tracked by https://github.com/longhorn/longhorn/issues/368
