### ISSUE TITLE
[IMPROVEMENT] Add dmsetup and dmcrypt utilities check in cli

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8217]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Ensure that the necessary packages are installed on the host for volume encryption and device mapper devices in front of v2 volumes.

**Comment by migs35323** [comment]
can it be a warning instead of an error if it doesn't affect normal longhorn functionality? 
i believe these utilities are only used when one enables\uses encryption?
so if users are not using that functionality they can still understand that their enviroment is ok, they just won't get that feature

**Comment by derekbit** [comment]
We can add this in longhorn/cli instead.

**Comment by derekbit** [comment]
cc @mantissahz

**Comment by innobead** [comment]
@derekbit I added the description to the issue. Please correct if it's wrong or any context has been missing.

**Comment by COLDTURNIP** [comment]
# Test Steps

- Step 1. a node that ready to deploy Longhorn, but is lack of device mapper package.
  - deb-based distros: `apt remove dmsetup`
  - rpm-based distros: `yum remove device-mapper`
  - SUSE: `zypper remove device-mapper`
  - pacman-based distros: `pacman -R device-mapper`
- Step 2. `longhornctl check preflight`, then it complains some package is missing.
- Step 3. install the above device mapper package back.
- Step 4. `longhornctl check preflight`, the package missing error disappear.

**Comment by roger-ryao** [comment]
**Verified on master-head 20241212**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/64afdec9c9827956bf9097b7db8e22ce9bd75731
- cli `master-head` https://github.com/longhorn/cli/commit/c0261653cab5ccb58ebb269689e0d80afad0e263

**The test steps**
https://github.com/longhorn/longhorn/issues/8217#issuecomment-2530765013

**Result Passed**

- [x] `lobghorn-cli` : The Longhorn CLI can successfully detect if `dm_crypt` is not loaded.
  - [x] `Ubuntu` distros :Passed
  - [x] `RedHat` distros : Passed
  - [x] `SLES` : Passed
- [ ]  `Arch Linux`: Encountered issues during execution. After discussion with @COLDTURNIP, it appears related to https://github.com/longhorn/longhorn/issues/5679. As `Arch Linux` is not currently supported, we will close this ticket for now.
