### ISSUE TITLE
The OwnerReferences in Longhorn system is wrong

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#822]
The schema of the field `Kind` should be like `EngineImage` rather than `longhorn.rancher.io/v1alpha1, Kind=EngineImage`.

**Comment by shuo-wu** [comment]
Test case 1:
1. Launch v0.6.2 Longhorn system. Create a volume with recurring jobs and deploy a compatible engine image. --> For the engine image DaemonSet and instance manager objects, the field `ownerReferences[0].kind` is `longhorn.rancher.io/v1alpha1, Kind=EngineImage`. For the engine/replica manager pods, the field is `longhorn.rancher.io/v1alpha1, Kind=InstanceManager`. For the engine, replicas and recurring jobs, the field is `longhorn.rancher.io/v1alpha1, Kind=Volume`
2. Upgrade to the version containing this PR. --> the field `kind` of all the above components will be like `EngineImage` rather than `longhorn.rancher.io/v1alpha1, Kind=EngineImage`.
3. Delete the volume. --> The related engine, replicas, recurring jobs will be removed.
4. Delete the deployed engine image. --> The related instance managers, instance manager pods, engine image DaemonSet will be removed. The engine image will be cleaned up after all of the above components are gone. Check the manager's log to see if there are tons of errors during engine image deletion.
5. Use uninstaller to uninstall this Longhorn system. --> Uninstallation will succeed.

Test case 2:
1. Launch the Longhorn containing this PR. Create a volume with recurring jobs and deploy a compatible engine image. --> The field `ownerReferences[0].kind` will be like `EngineImage`, `InstanceManager`, or `Volume`.
2. Use uninstaller to uninstall this Longhorn system. --> Uninstallation will succeed.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

**Comment by meldafrawi** [comment]
Notes: the following one-liners will help checking owner reference for all mentioned components. 

```
for INST_MGR in `kubectl get instancemanager --no-headers -n longhorn-system | awk '{print $1}'`; do 
  echo -n "${INST_MGR}:   "
  kubectl get instancemanager -n longhorn-system -o json ${INST_MGR}  | jq ".metadata.ownerReferences[0].kind" 
done
```

```
for REPLICA in `kubectl get replicas --no-headers -n longhorn-system | awk '{print $1}'`; do
  echo -n "${REPLICA}:   "
  kubectl get replicas -n longhorn-system -o json ${REPLICA}  | jq ".metadata.ownerReferences[0].kind"
done
```

for ENGINE in `kubectl get engine --no-headers -n longhorn-system | awk '{print $1}'`; do
  echo -n "${ENGINE}:   "
  kubectl get engine -n longhorn-system -o json ${ENGINE}  | jq ".metadata.ownerReferences[0].kind"
done
