### ISSUE TITLE
Update Ubuntu version to 18.04 for NFSv4.1 support

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#823]
Steps to reproduce:
  - Create an NFS server (Using CentOS 7 instance is recommended)
  - Enable only NFSv4.1.
  - In settings page, set the backup store to point to NFS share.

> error listing backups: error listing backup volumes: Failed to execute: /var/lib/rancher/longhorn/engine-binaries/longhornio-longhorn-engine-master/longhorn [backup ls --volume-only nfs://X.X.X.X:/mnt/new-backups], output Cannot mount nfs X.X.X.X:/mnt/new-backups: Failed to execute: mount [-t nfs4 X.X.X.X:/mnt/new-backups /var/lib/longhorn/mounts/X_X_X_X/mnt/new-backups], output mount.nfs4: Protocol not supported , error exit status 32 , stderr, time="2019-10-16T22:22:55Z" level=error msg="Cannot mount nfs X.X.X.X:/mnt/new-backups: Failed to execute: mount [-t nfs4 X.X.X.X:/mnt/new-backups /var/lib/longhorn/mounts/X_X_X_X/mnt/new-backups], output mount.nfs4: Protocol not supported\n, error exit status 32" , error exit status 1 

#### Note:
Enable NFSv4.1only in CentOS 7:
  - in `/etc/nfs.conf`, make sure the following lines exists under `[nfsd]` section:

```
vers2=n
vers3=n
vers4=y
vers4.0=n
vers4.1=y
vers4.2=n
```

**Comment by shuo-wu** [comment]
The cause of this issue: the `mount` version in Ubuntu 16.04 is too old. Need to update the Ubuntu version to 18.04

**Comment by shuo-wu** [comment]
There is one issue caused by NFS v4.1: #832, which will lead to the failure of some integration test cases.

For now, it's better to **manually** test the backup related features with a real NFS v4.1 server.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
