### ISSUE TITLE
Kubernetes added a new node, but Longhorn didn't detect the addition of the new node. How can I make Longhorn recognize the addition as well? I deployed using the kubectl method.

### ISSUE THREAD

**Issue by linux-golang** [longhorn/longhorn#8238]
Kubernetes added a new node, but Longhorn didn't detect the addition of the new node. How can I make Longhorn recognize the addition as well? I deployed using the kubectl method.

longhorn： 1.5.3
kubernetes: 1.29
![CleanShot 2024-03-22 at 09 58 42@2x](https://github.com/longhorn/longhorn/assets/65080394/3f02674a-4115-4663-a593-f022b3d3493c)
![CleanShot 2024-03-22 at 09 59 10@2x](https://github.com/longhorn/longhorn/assets/65080394/60d93c1f-4a3b-45fb-965a-25a022e40753)

**Comment by chriscchien** [comment]
Hi @linux-golang , could you run the environment check scipt `curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.5.3/scripts/environment_check.sh | bash` to see if the new node is ready to deploy longhorn? Furthurmore, could you check `longhorn-manager` pod applied to node `192.168.100.243` and it's state? thank you.

**Comment by linux-golang** [comment]
longhorn-manager: logs

time="2024-03-24T12:32:58Z" level=fatal msg="Error starting manager: Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host: failed to execute: nsenter [--mount=/host/proc/22329/ns/mnt --net=/host/proc/22329/ns/net iscsiadm --version], output , stderr nsenter: failed to execute iscsiadm: No such file or directory\n: exit status 127" func=app.DaemonCmd.func1 file="daemon.go:83"

**Comment by linux-golang** [comment]
apt-get install -y open-iscsi   ，  solved ，thank you
