### ISSUE TITLE
[IMPROVEMENT] Longhor Manager Flood with "Failed to get engine proxy of ... cannot get client for engine" Message

### ISSUE THREAD

**Issue by WebberHuang1118** [longhorn/longhorn#8266]
## Describe the solution you'd like
The volume collector keeps trying to get metrics even when the volume is detached
and get a warning message like the following:

`2024-03-20T08:55:06.403603975Z time="2024-03-20T08:55:06Z" level=warning msg="Failed to get engine proxy of pvc-44cb0fa7-c419-4e2e-af04-ef2a9306b898-e-3ed66e35 for volume pvc-xxxx" collector=volume error="failed to get binary client for engine xxx: cannot get client for engine xxxx: engine is not running" node=lp02edge03004`

## Describe alternatives you've considered
Volume collector only retrieves the metrics while the engine is running

**Comment by ChanYiLin** [comment]
cc @PhanLe1010

**Comment by c3y1huang** [comment]
This looks like a bug. Could you please fill in some context @WebberHuang1118 ? Thank you.
```
## Describe the bug

<!--A clear and concise description of the bug.-->

## To Reproduce

<!--Please provide the steps to reproduce the case-->

## Expected behavior

<!--A clear and concise description of what you expected to happen.-->

## Support bundle for troubleshooting

<!--PLEASE provide a support bundle when the issue happens. You can generate a support bundle using the link at the footer of the Longhorn UI. Check [here](https://longhorn.io/docs/latest/troubleshoot/support-bundle/). Then, attach to the issue or send to longhorn-support-bundle@suse.com -->

## Environment

<!-- Suggest checking the doc of the best practices of using Longhorn. [here](https://longhorn.io/docs/latest/best-practices)-->

 - Longhorn version: 
 - Impacted volume (PV): <!-- PLEASE specify the volume name to better identify the cause -->
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

<!-- Please add any other context about the problem here. -->

```

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `1cda0e`)

Have detached and attached volume s and then get metirc several times, did not see `Failed to get engine proxy` logs in longhorn-manager master-head. (The same steps, I can see `Failed to get engine proxy` logs in v1.6.2)
