### ISSUE TITLE
[TASK] Bump base images to SLES 15.6

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#8273]
## What's the task? Please describe

Bump the base image version from SLES 15.5 to 15.6

## Describe the sub-tasks

- [ ] `instance-manager`: https://github.com/longhorn/longhorn-instance-manager/pull/432
- [ ] `engine`: https://github.com/longhorn/longhorn-engine/pull/1047

**Comment by innobead** [comment]
15.6 is not GA yet.

```console
➜  ~ skopeo inspect docker://registry.suse.com/bci/bci-base:15.6 | jq '.Labels."com.suse.bci.base.release-stage"'
"beta"
➜  ~ skopeo inspect docker://registry.suse.com/bci/bci-base:15.5 | jq '.Labels."com.suse.bci.base.release-stage"'
"released"
```

Let's update the base image until it's released.

**Comment by mantissahz** [comment]
Base images to SLES 15.6
