### ISSUE TITLE
[BUG] Volume bigger than it's given size and increasing exponentially

### ISSUE THREAD

**Issue by simonebenati** [longhorn/longhorn#8285]
## Describe the bug

I have a prometheus volume that keeps increasing in size even if I set the size to be 30Gi

## To Reproduce

Install kube prometheus stack set the volume size and then wait for metrics

## Expected behavior

Not go above 30Gi especially if the prometheus retention set is very low (1d)

## Support bundle for troubleshooting

- https://www.dropbox.com/scl/fi/mx7e9ikzk6ipmcben9k9n/supportbundle_7c3711cf-f0d3-41bf-b079-5fa1373a02f7_2024-03-31T18-42-12Z.zip?rlkey=uffw0lcev4nacvnnog4dybo16&dl=0

## Environment

 - Longhorn version: 1.4.3
 - Impacted volume (PV): pvc-635e7a7a-50a4-4613-905d-08b7586d4046
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: rke2 1.26.11
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

I know there's other issues like this but none of the issues I checked fixed my issue.

**Comment by bpedersen2** [comment]
Try running `trim filesystem` regularly . At least in 1.5.3+ it doing its job.

**Comment by simonebenati** [comment]
Thank you @bpedersen2 but i am on 1.4.3..

**Comment by bpedersen2** [comment]
> Thank you @bpedersen2 but i am on 1.4.3.. and i don't have that as a recurring job..

It should be available on that version, you just need to create the job yourself.

**Comment by simonebenati** [comment]
@bpedersen2 Hello, I actually had the chance to try and it works! the volume went from 50Gi to 7Gi.
How do I set it up via crd so that it comes up in the Longhorn UI?
Also what exactly does the "trim filesystem" is it risky to run it against data? Might it happen that some data goes lost or is it a safe operation to perform?

**Comment by simonebenati** [comment]
Actually nevermind, you cannot create trim filesystem operation as recurring job in 1.4.3

`The RecurringJob "filesystem-trim" is invalid: spec.task: Unsupported value: "filesystem-trim": supported values: "snapshot", "snapshot-force-create", "snapshot-cleanup", "snapshot-delete", "backup", "backup-force-create"`

Are there any workarounds?

**Comment by mfyuce** [comment]
`apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: trim-1
  namespace: longhorn-system
spec:
  cron: "29,59 * * * ?"
  task: "filesystem-trim" 
  retain: 1
  concurrency: 1 `

And then, it seems, from the UI, from the volumes, clieck `schedule` and then set `trim-1` as the job


![image](https://github.com/longhorn/longhorn/assets/41781/8cbaa00a-5eb3-4f40-803c-501e6608ddea)

**Comment by simonebenati** [comment]
@mfyuce thank you, like this it works!

Is trimming the volume completely a safe thing to do? It won't delete any data that might be useful?

**Comment by simonebenati** [comment]
hello @mfyuce , it indeed adds it to the recurring job list but it doesn't trim volumes at all..

**Comment by derekbit** [comment]
@simonebenati 
v1.4.3 doesn't support filesystem-trim recurring job. Please try the newer versions. Thank you.

**Comment by mfyuce** [comment]
I can confirm that, trim jobs works on `v1.6.2` version. Thanks
