### ISSUE TITLE
[FEATURE][UI] Add parameters support to the Backup and RecurringJob

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#8291]
## Is your feature request related to a problem? Please describe (👍 if you like this request)
 - [x] add `Full Backup` checkbox in create backup modal
 - [x] add parameters with key (dropdown) and value (inputBox) fields in create recurring backup task
 - [x] add backup mode column in backup table

### Volume Page
In "Create Backup" Box
![Screenshot from 2024-04-02 17-03-17](https://github.com/longhorn/longhorn/assets/7100904/f98ba854-afdc-4b34-a2d8-3e9869663f31)

- Add a new checkbox: `"Full Backup"`
    - When it is checked => the `"backupMode"` in the request body should be `"full"`
    - Otherwise => the `"backupMode"` in the request body should be `"incremental"`
- When sending to the API, the payload should look like below and to the endpoint `/v1/volumes/${VOLUME}?action=snapshotBackup`
```
{
    "backupMode": "incremental",
    "name": "test-snapshot",
}
```

### Recurring Job

![Screenshot from 2024-04-02 17-07-15](https://github.com/longhorn/longhorn/assets/7100904/2dbcae58-6753-471a-badc-d23ca78b45af)

Only for backup operation
- Add a new field for user to fill "parameters"
- For the key we only support "full-backup-interval". And the value should be number in string type
- Better use drop down menu for the parameters so there is no need for user to type the key(avoid typo.)

### Backup Page

- Get the `"BackupMode"` for each backup and show it as one of the fields

cc @derekbit

**Comment by a110605** [comment]
Waiting for backend PRs to be merged.
https://github.com/longhorn/longhorn/issues/7070#issuecomment-2008928608

**Comment by derekbit** [comment]
@a110605 https://github.com/longhorn/longhorn/issues/7070 is ready.

**Comment by a110605** [comment]
> @a110605 #7070 is ready.

Thanks let me know. I will start implement this UI ticket

**Comment by a110605** [comment]
Update checklist and move to READY FOR TESTNG

**Comment by chriscchien** [comment]
Hello @a110605 

The `Create Recurring Job` page in volume deatil page did not support `full-backup-interval` input , could you take a look on that? thank you.

**Comment by a110605** [comment]
> Hello @a110605
> 
> The `Create Recurring Job` page in volume deatil page did not support `full-backup-interval` input , could you take a look on that? thank you.

Yeah, I will have a new PR to add it in volume details page. Thanks for report.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-ui `aa896b`) 

Following  test [steps](https://github.com/longhorn/longhorn/issues/8291#issuecomment-2207930853) to create `Backup` and  `RecurringJob` from UI, did not encounter any problems.
