### ISSUE TITLE
[BUG] Secret for backup not found

### ISSUE THREAD

**Issue by didlawowo** [longhorn/longhorn#8299]
## Describe the bug

Hi,
i'm trying to enable backup on minion
with this guide
https://www.suse.com/c/rancher_blog/using-minio-as-backup-target-for-rancher-longhorn-2/

i have create the secret but longhorn don't see him

failed to get default backup target client on longhornio/longhorn-engine:v1.6.1: could not access s3 without credential secret

<img width="364" alt="image" src="https://github.com/longhorn/longhorn/assets/12622760/2a862fe3-8d8d-470f-83e0-546619dffc45">

<img width="1106" alt="image" src="https://github.com/longhorn/longhorn/assets/12622760/ee3c4251-ccfc-4925-b6ce-2746a5a574b5">

<img width="710" alt="image" src="https://github.com/longhorn/longhorn/assets/12622760/5b2f1ed0-3402-42df-bb38-c0f602634da8">

## To Reproduce

create secret and give path to backup minio in longhorn backup config

## Expected behavior

find secret and enable backup feature 

## Environment

RKE2 

 - Longhorn version:  1.6.1
 - Installation method helm 
 - Kubernetes distro v1.27.12+rke2r1
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 1
 - Node config
   - OS type and version: ubuntu 22.04
   - Kernel version: 5.15
   - CPU per node: 16
   - Memory per node: 32
   - Disk type (e.g. SSD/NVMe/HDD): nvme
   - Network bandwidth between the nodes (Gbps): 10
 - Number of Longhorn volumes in the cluster: 24

**Comment by madawa-wso2** [comment]
same issue with longhorn version longhorn-engine:v1.6.0. Is there any solution?

**Comment by derekbit** [comment]
@didlawowo 
The secret is found, but the `backupTarget.Spec.CredentialSecret` is somehow empty. Can you show the content of the backupTarget CR?

@madawa-wso2 
Same error message?

**Comment by derekbit** [comment]
cc @mantissahz

**Comment by madawa-wso2** [comment]
> @didlawowo The `backupTarget.Spec.CredentialSecret` seems somehow empty. Can you show the content of the backupTarget CR? You can try to manually set `backupTarget.Spec.CredentialSecret`.
> 
> @madawa-wso2 Same error message?

Not the same error message for v1.6.0. Please refer to the following.

![image](https://github.com/longhorn/longhorn/assets/118790853/0d73b8af-af06-4ed8-8302-dc88596ad030)

But I have tried the v1.6.1 in my local env and got the same error as @didlawowo mentioned.

**Comment by derekbit** [comment]
@madawa-wso2 Can you provide a support bundle for checking the issue?

**Comment by madawa-wso2** [comment]
Thanks for the prompt response @derekbit. What do you mean by the support bundle. I just installed the longhorn v1.6.0 using Helm3 in to my kubernetes 1.26.10 cluster. 

Ref : https://longhorn.io/docs/1.6.0/deploy/install/install-with-helm/

**Comment by madawa-wso2** [comment]
Hi @derekbit I was able to sort out the issue the generated support bindle. The issue was with my s3 access user policy. After giving full access to the restricted bucket, Issue was disappeared. Now Im having a different issue. Thanks for looking to this appreciate your help.

**Comment by derekbit** [comment]
> After giving full access to the restricted bucket

@madawa-wso2 Thanks for the update. Can you elaborate more on the required permission? We can improve it in the backup document.

cc @mantissahz @ChanYiLin @longhorn/qa

**Comment by madawa-wso2** [comment]
Im using a S3 bucket policy along with IAM policy that your documentation provides,

My previous bucket policy was.

```
{
	"Version": "2012-10-17",
	"Id": "Policy1712657454176",
	"Statement": [
		{
			"Sid": "Stmt1712657428177",
			"Effect": "Allow",
			"Principal": "*",
			"Action": "s3:*",
			"Resource": [
				"arn:aws:s3:::<My-bucket>"
			],
			"Condition": {
				"ArnEquals": {
					"aws:SourceArn": "arn:aws:iam::2521234432012:user/MyUser"
				}
			}
		}
	]
}
```

That causes the **secret not found** error.

So I just needed give permissions to all the content inside the bucket as follows and the error was disappered.

```
{
	"Version": "2012-10-17",
	"Id": "Policy1712657454176",
	"Statement": [
		{
			"Sid": "Stmt1712657428177",
			"Effect": "Allow",
			"Principal": "*",
			"Action": "s3:*",
			"Resource": [
				"arn:aws:s3:::<My-bucket>",
				"arn:aws:s3:::<My-bucket>/*"
			],
			"Condition": {
				"ArnEquals": {
					"aws:SourceArn": "arn:aws:iam::2521234432012:user/MyUser"
				}
			}
		}
	]
}

```

**Comment by didlawowo** [comment]
i'm sorry for late answer but on my side policy was

    - resources:
              - "arn:aws:s3:::longhorn-backups/*"
              effect: "Allow"

so i don't thinks its that the problem

**Comment by derekbit** [comment]
> i'm sorry for late answer but on my side policy was
> 
> ```
> - resources:
>           - "arn:aws:s3:::longhorn-backups/*"
>           effect: "Allow"
> ```
> 
> so i don't thinks its that the problem

@didlawowo 
can you send a support bundle to "[longhorn-support-bundle@suse.com](mailto:longhorn-support-bundle@suse.com)"?
After sending the support bundle, can you try to remove the backup target and then add it back?

**Comment by Lite5h4dow** [comment]
Im also having this issue, message: 
`failed to get default backup target client on longhornio/longhorn-engine:v1.6.1: could not access s3 without credential secret`

the secret is correctly set, the secret does have values and it is set in both the helm values and I set it via the web UI
![image](https://github.com/longhorn/longhorn/assets/18059545/ce30063c-058c-48e2-a9ed-c910cd0eeb52)
![image](https://github.com/longhorn/longhorn/assets/18059545/40d433f0-b28c-4927-a932-27ac42eb0a49)

**Comment by Lite5h4dow** [comment]
i fixed it by editing the longhorn.io/backupTarget/default file, and saving it, longhorn then seemed to pick it up. i didn't change anything, but it did show up as available all of a sudden, so maybe that's the issue?

**Comment by derekbit** [comment]
> i fixed it by editing the longhorn.io/backupTarget/default file, and saving it, longhorn then seemed to pick it up. i didn't change anything, but it did show up as available all of a sudden, so maybe that's the issue?

cc @mantissahz

**Comment by derekbit** [comment]
After discussing with @mantissahz, we found `backuptarget.status.lastSyncedAt` is somehow `null` [in an environment user provided](https://github.com/longhorn/longhorn/discussions/8474#discussioncomment-9275766). @mantissahz will investigate it. 

cc @c3y1huang if having any idea.

**Comment by mantissahz** [comment]
@derekbit
Yeah, it is possible. 
If it always failed here https://github.com/longhorn/longhorn-manager/blob/v1.6.1/controller/backup_target_controller.go#L380 with `can not access s3 without credential secret`, it would not update the `LastSyncedAt` because `syncTimeRequired` is always `false`.

**Comment by mantissahz** [comment]
Updated:
After some tests, I can reproduce the `can not access s3 without credential secret` like
```txt
root@rancher60-master:~/longhorn/chart# kl get lhbt default -oyaml
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  creationTimestamp: "2024-05-09T08:12:08Z"
  generation: 74
  name: default
  namespace: longhorn-system
  resourceVersion: "173007"
  uid: 9e9532c6-85db-46e8-9394-b4b8e205ada4
spec:
  backupTargetURL: s3://backupbucket@dsg/backupstore/
  credentialSecret: minio-secret
  pollInterval: 5m0s
  syncRequestedAt: "2024-05-09T12:17:31Z"
status:
  available: false
  conditions:
  - lastProbeTime: ""
    lastTransitionTime: "2024-05-09T12:15:37Z"
    message: 'failed to get default backup target client on longhornio/longhorn-engine:v1.6.1:
      could not access s3 without credential secret'
    reason: Unavailable
    status: "True"
    type: Unavailable
  lastSyncedAt: "2024-05-09T12:14:36Z"
  ownerID: rancher60-worker3
```

1. Empty settings `backup-target` and `backup-target-credential-secret`
2. Setup the setting `backup-target` with an s3 driver type URL like `s3://backupbucket@dsg/backupstore/` and then you will get the error message
```txt
failed to get default backup target client on longhornio/longhorn-engine:v1.6.1: could not access s3 without credential secret
```
3. Setup the setting `backup-target-credential-secret` with an existing secret but the contents corresponding to the `backup-target` URL are incorrect.
4. `syncSystemBackup` failed, `syncBackupBackingImage` failed, and `syncSystemBackup` failed when the backup target controller reconciles the backup target.

There are many ways to get the result: 
- Any settings of data in the secret do not correctly correspond to the remote backup target
- Backup target URL is invalid like `s3://bk@region`

Because we did not verify the clients after calling `getBackupTarget`, it will only return the error when calling `syncSystemBackup` and it will not update the condition status:

https://github.com/longhorn/longhorn-manager/blob/v1.6.1/controller/backup_target_controller.go#L380-L397

At the head of master and v1.6.x, we have changed the code flow and it will verify the client in function `getInfoFromBackupStore`, and set the correct condition message if it fails:

https://github.com/longhorn/longhorn-manager/blob/v1.6.x/controller/backup_target_controller.go#L430-L455

**Comment by derekbit** [comment]
@mantissahz We don't need any fix in v1.6.x, right?

**Comment by mantissahz** [comment]
>@mantissahz We don't need any fix in v1.6.x, right?

Yes, we don't need any fixes and check if this will happen again in v1.6.2.

**Comment by crazyelectron-io** [comment]
I specified a CIFS backup target and get the same `failed to get default backup target client on longhornio/longhorn-engine:v1.6.1: secret "longhorn-backup-secret" not found` error.
The secret _does_ exist:
```yaml
$ kubectl describe secrets -n longhorn-system longhorn-backup-secret
Name:         longhorn-backup-secret
Namespace:    longhorn-system
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
CIFS_PASSWORD:  11 bytes
CIFS_USERNAME:  6 bytes
```
It is not S3 related in my case, but Longhorn v1.6.1 does not pickup the secret somehow.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240528**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/cd4d7235de3547e74ef6aeb71c6ba2c97ac8a9ba
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/aebb5a8a1c5d5b9463c0c39b7ad4ae0766795477

**The test steps**
https://github.com/longhorn/longhorn/issues/8299#issuecomment-2103760063


**Result Passed**


1. Setup the setting backup-target with an s3 driver type URL like s3://backupbucket@dsg/backupstore/ and then you will get the error message
`failed to init backup target clients: failed to get default backup target client on longhornio/longhorn-engine:master-head: could not access s3 without credential secret`
![Screenshot_20240528_144342](https://github.com/longhorn/longhorn/assets/104337648/41902763-febd-4989-8967-ce7144acfe5b)


2. Set up the setting backup-target-credential-secret with an existing secret but the contents corresponding to the backup-target URL are incorrect.
The condition of the backup target will show the correct error message as to why it failed.
![Screenshot_20240528_152341](https://github.com/longhorn/longhorn/assets/104337648/ec4848c0-a15a-49af-a974-164fd56b2cac)
