### ISSUE TITLE
Longhorn backup not complite

### ISSUE THREAD

**Issue by aleksey005** [longhorn/longhorn#830]
Longhonrt backup in S3 (MINIO) not complite.
Longhorn 0.6.2, Rancher 2.3.1, Minio Mount volume over NFS PVC.

![image](https://user-images.githubusercontent.com/6145279/67503252-facce900-f68f-11e9-8459-bfe0979f57c5.png)

**Comment by aleksey005** [comment]
Please, close, not problem Longhorn - i set ingress
nginx.ingress.kubernetes.io/proxy-body-size: "0" in minio
and backups is done,

**Comment by yasker** [comment]
No problem, glad everything is fine.
