### ISSUE TITLE
[BUG] Stability issues on XCP-ng VMs

### ISSUE THREAD

**Issue by cyford** [longhorn/longhorn#8303]
## Describe the bug
I am having the weiredest issues.   I am unable to use kubernetes  longhorn on XCPng  vms with stability.
some how when trying it seems the host trys to spin up with /dev/sda   and sdb sdc sdd      which the host only uses that format..   the  vms's themselves /dev/xvda   ect  .    I only experience this  when pods / containers are actually running on the vm  and it is usually within 5-10%   of the vm host.   Restarting the vm  wiith shutdown -rf now,   usually  removes the uneeded /dev/sda  drives  and work as it needs to..     is there any scanning or devices  that longhorn does ..

Also  i never see the issue happen if i get lucky an all containers come up correctly.    I only starts happening  while deplying statefulset,    

also while it is happening  the command df hangs
![console_host](https://github.com/longhorn/longhorn/assets/25903490/ca64c6ec-2121-47a6-be45-fd672b3f60ed)
![po-no](https://github.com/longhorn/longhorn/assets/25903490/d1eb64de-3b62-4bb3-857c-297d6a51746f)
![Screenshot 2024-04-04 100114](https://github.com/longhorn/longhorn/assets/25903490/4acf78b3-534a-4fd3-a400-a5be4141eef6)
![top](https://github.com/longhorn/longhorn/assets/25903490/51857012-41b4-4282-9ca1-29d6d14b3015)

longhorn produces  fake drives and stops working in xcpng vm's  
## To Reproduce
i use  kubernetes ,   antnas networking,    longhorn,    and mariadb-operator      spinning up a statefulset  usually gets stuck  when it reaches an effected host..        the effect host usually whos all errors which is attached to this case

## Expected behavior

i should use its own mapped  root partition or var/lib/longhorn  or what ever  and not give me issues

i should use its own mapped  root partition or var/lib/longhorn  or what ever  and not give me issues

## Environment

 - Longhorn version: **v1.5.1**
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):**Kubectl**
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:**3**
   - Number of worker nodes in the cluster:**15**
 - Node config
   - OS type and version: rocky os
   - Kernel version: **6.1.0-17-amd64**
   - CPU per node: **4-16**
   - Memory per node: 15G
   - Disk type (e.g. SSD/NVMe/HDD):**SSD/SAS**
   - Network bandwidth between the nodes (Gbps):**1G+**
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal)**:XENSERVER/XCPng**
 - Number of Longhorn volumes in the cluster:**39**

**Comment by derekbit** [comment]
> Network bandwidth between the nodes (Gbps):1G+

The bandwidth is not big enough.
Are the applications IO intensive in your cluster? What are the CPU models of the longhorn nodes?

**Comment by cyford** [comment]
![image](https://github.com/longhorn/longhorn/assets/25903490/e9f3bf5e-1b21-4b55-b8cd-3984680c4966)
![image](https://github.com/longhorn/longhorn/assets/25903490/bab768f7-823e-43ae-82bc-c9e5b89dfc86)
![image](https://github.com/longhorn/longhorn/assets/25903490/3b7d23d4-5ebf-4bc5-8f7b-acc832d5cfcc)
![image](https://github.com/longhorn/longhorn/assets/25903490/a694f2bb-e338-43d0-928e-50e4eb147e93)

my speedtest is 1GPS    4 cpus,  anf 8GB memory
This usually happens during deployment  inconsistantly.     
The containers are databases 
i have deployed 6 containers  successfully  
usually when it is successful  i have a hard time dumping data into the databases..  
i seen the fireall was blocking port 8080 going out ...    so ill will test again

**Comment by cyford** [comment]
![image](https://github.com/longhorn/longhorn/assets/25903490/920c3d2a-9a53-46f4-af11-0dfb66879c2e)
![image](https://github.com/longhorn/longhorn/assets/25903490/e63ef840-e0e7-4b36-85a6-63dae9894286)
![image](https://github.com/longhorn/longhorn/assets/25903490/f2e4914f-de26-49c7-b36f-dba52bbe7bb2)


What i do not understand,   why is  my top / (root) dir  so much faster than my pvc on the same disk   both /  and /var/lib/mysql is on the same server 

/root  is on a differnt server  an i can understand why that is slow
![image](https://github.com/longhorn/longhorn/assets/25903490/ced94058-95d8-4803-8704-4941af912a01)

i am no longer getting filesystem errors.     but my mariadb dumps  halt  at Freeing items    which  in research  is low i/o  somewhere

**Comment by cyford** [comment]
ok   ,    when i deploy with a new image,  i get this error again..    i guess it only happens  if it downloads a image.

![image](https://github.com/longhorn/longhorn/assets/25903490/77ebbe4b-5880-4336-b349-8f5305a158b2)
![image](https://github.com/longhorn/longhorn/assets/25903490/26bdfa0f-90ef-4929-ad6f-0df3e61a8c5c)

**Comment by cyford** [comment]
> ## Describe the bug

all vms  are insdide the same hypervisor.    im sure bandwith is alot higher than 1gb my internet connection is 1gb  and from a vm i can speedtest at around 900mbs.   hdd speed test are around 350MBs  ==   2.8 gbs
