### ISSUE TITLE
[IMPROVEMENT] alllow to not creating default disks with label node.longhorn.io/create-default-disk=false

### ISSUE THREAD

**Issue by migs35323** [longhorn/longhorn#8308]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

I would like to suggest a "small improvement", we have the ability to choose that longhorn creates default disks or to not create default disks and specify the ones we want to create using the label node.longhorn.io/create-default-disk=true

i'd like to suggest that we could specify the opposite, to provide even more flexibility
default being create disks unless we label a node with "node.longhorn.io/create-default-disk=false" then this specific node doesn't have the default disk created

## Explanation:

i have an old cluster where i usually let longhorn create disks in new nodes by default and add them "to the pool" for convenience
however i added a node that i am testing with different hardware, and longhorn by default added this disk to the pool even tough i tried to apply the label and thus, replicas started to schedule on it when this node joined.
i didn't want to mess with taints or settings that require me to change with the already existent nodes
i still want to use longhorn in this node but in a different storage class/disk pool where only specific workloads schedule

**Comment by Vicente-Cheng** [comment]
Hi @migs35323, sorry for the late reply.

Did you mean you wouldn't want to add the default disk with some specific hardware?
