### ISSUE TITLE
Add badge for public CI build

### ISSUE THREAD

**Issue by caniszczyk** [longhorn/longhorn#831]
don't see anything on README

**Comment by yasker** [comment]
Added badges from different components in https://github.com/longhorn/longhorn/commit/e537197ed5422e46000a4021d9b6d359865abaa8

We also have a nightly integration test. The code is open source at https://github.com/longhorn/longhorn-tests . But it's current running on Jenkins and Digital Ocean using an internal Rancher's infrastructure. I would prefer it to be moved to CNCF if possible. The test would require spinning up/down VMs and Kubernetes cluster dynamically, so it probably needs to be rewired to fit CNCF's CI the framework, so I can imagine that would need some work.

**Comment by yasker** [comment]
Done for Longhorn drone build.
