### ISSUE TITLE
[BUG] Cannot replicate large volume

### ISSUE THREAD

**Issue by nicleary** [longhorn/longhorn#8311]
## Describe the bug

I have rotated out all of the nodes in my cluster, and in doing so replaces all volumes with new replicas. However, one replica (one of the largest) is unable to replicate to a third node. It fails to rebuild the third replica with this error:

`Failed rebuilding replica with Address 10.42.12.7:10493: proxyServer=10.42.17.27:8501 destination=10.42.17.27:10106: failed to add replica tcp://10.42.12.7:10493 for volume: rpc error: code = Unavailable desc = failed to sync files [{FromFileName:volume-snap-backups--3c583f0a-b206-4443-84ed-13de9f68115f.img ToFileName:volume-snap-backups--3c583f0a-b206-4443-84ed-13de9f68115f.img ActualSize:61693829120} {FromFileName:volume-snap-backups--3c583f0a-b206-4443-84ed-13de9f68115f.img.meta ToFileName:volume-snap-backups--3c583f0a-b206-4443-84ed-13de9f68115f.img.meta ActualSize:0} {FromFileName:volume-snap-f1f92e98-67bc-49ed-9ff3-4dcc0adaf6b9.img ToFileName:volume-snap-f1f92e98-67bc-49ed-9ff3-4dcc0adaf6b9.img ActualSize:0} {FromFileName:volume-snap-f1f92e98-67bc-49ed-9ff3-4dcc0adaf6b9.img.meta ToFileName:volume-snap-f1f92e98-67bc-49ed-9ff3-4dcc0adaf6b9.img.meta ActualSize:0} {FromFileName:volume-snap-2102eb82-b80f-474c-a346-0cc7642e5855.img ToFileName:volume-snap-2102eb82-b80f-474c-a346-0cc7642e5855.img ActualSize:0} {FromFileName:volume-snap-2102eb82-b80f-474c-a346-0cc7642e5855.img.meta ToFileName:volume-snap-2102eb82-b80f-474c-a346-0cc7642e5855.img.meta ActualSize:0}] from tcp://10.42.16.46:10181: rpc error: code = Unavailable desc = replica tcp://10.42.16.46:10181 failed to send file volume-snap-backups--3c583f0a-b206-4443-84ed-13de9f68115f.img to 10.42.12.7:10497: failed to send file volume-snap-backups--3c583f0a-b206-4443-84ed-13de9f68115f.img to 10.42.12.7:10497: rpc error: code = Unavailable desc = error reading from server: read tcp 10.42.12.7:52158->10.42.16.46:10183: read: connection reset by peer`

## To Reproduce

Replace all nodes in the cluster slowly, ensuring that all volumes have at least one replica at all time. Notice that a 100Gi volume is unable to replicate to a third replica.

## Expected behavior

Three replicas are present.

## Environment

 - Longhorn version: v1.6.0
 - Impacted volume (PV): pvc-5f4a4b30-fa28-4d52-9217-6e735ff90afa
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE v1.27.12+rke2r1
   - Number of control plane nodes in the cluster: 4
   - Number of worker nodes in the cluster: 8
 - Node config
   - OS type and version: Ubuntu 22.04
   - Kernel version:
   - CPU per node: 2-8
   - Memory per node: 4GB - 32GB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 1Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): XCP-NG VMs
 - Number of Longhorn volumes in the cluster: 51

**Comment by nicleary** [comment]
I could not attach a source bundle or email it, as it is over 25MB, please let me know the best way to send it

**Comment by maximemoreillon** [comment]
I am having the same issue. Rebuilding a 500GB replica never gets past about 60% and fails with a `connection reset by peer` error

**Comment by derekbit** [comment]
@maximemoreillon Can you provide a support bundle as well? Thanks.

**Comment by maximemoreillon** [comment]
Sure! Just created one but the bundle is 420Mb. How should I send it?

**Comment by derekbit** [comment]
> Sure! Just created one but the bundle is 450Mb. How should I send it?

If you don't want to make it public, you can put it in a cloud drive and send the link to longhorn-support-bundle@suse.com.

**Comment by maximemoreillon** [comment]
Thank you for your reply!

here is a link to the bundle: https://nextcloud.home.maximemoreillon.com/s/kcbtaPoAxcmapjL

Please let me know once you have downloaded it so I can remove it from my drive
