### ISSUE TITLE
[BUG] Old backups are not cleaned up after timeout

### ISSUE THREAD

**Issue by gothka** [longhorn/longhorn#8319]
## Describe the bug
We've about 20,000+ old backups that are stale and using up resources on the cluster and could potentially blow up the cluster anytime due to this. We believe there's a few reasons on why this is happening: 

the default timeout for backup is hardcoded to 1 minute here https://github.com/longhorn/go-common-libs/blob/3993c59084471a20ccd863282a0af1757b7a9fbf/types/exec.go#L14 due to this when backup is failed during backing up to s3 in our case, all the stale/old backups are left on the cluster without LH engine cleaning them. 

https://github.com/longhorn/longhorn-manager/blob/91bc9cb701ac3116d37311fb8c732ac049a560f4/engineapi/backups.go#L169

We've to clean this up manually, the command below shows all the old backups and these object don't have `BackupVolume` set to them so they can't be restored unless manually created on the cluster

`k get backups.longhorn.io -n longhorn-system -o json | jq '.items[]|select(.status.state!="")|select(.metadata.creationTimestamp | fromdateiso8601 < 1711554025)|.metadata.name'` 

This command roughly outputs 26,000+ old backups that are stale and worth mentioning that deleting is easy but it'll incur s3 api costs which isn't quite cheap given num of api calls the client has to make to the s3 bucket.

This is happening on one of the cluster where manage more than 700 volumes in the cluster.

## To Reproduce

Run a cluster with 700+, and set the backup target with s3 and let the backups fail and eventually you'll old backups piling up without being deleted.

## Expected behavior
All old backups whether they're backed up or not should be deleted from the cluster.

## Support bundle for troubleshooting

Sent via email

## Environment

 - Longhorn version: v1.4.3
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher catalog
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: EKS
   - Number of control plane nodes in the cluster: EKS managed
   - Number of worker nodes in the cluster: 60+
 - Node config
   - OS type and version: Amazon linux 2
   - Kernel version:
   - CPU per node: 2 to 4
   - Memory per node: 8+ Gi
   - Disk type (e.g. SSD/NVMe/HDD): NVMe/SSD
   - Network bandwidth between the nodes (Gbps): 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 700+

## Additional context

I've looked through latest bugs but couldn't find that closely related to this. if it's been fixed in one of the latest releases please let me know so we can upgrade to that version.

**Comment by derekbit** [comment]
cc @mantissahz

**Comment by mantissahz** [comment]
Hi @gothka,
Is it the first time that `longhorn-manger` lists the backup volume with the timeout? Not sure about that the s3 server is busy or not?
Could you help me try this command 
```bash
/var/lib/longhorn/engine-binaries/rancher-mirrored-longhornio-longhorn-engine-v1.4.3/longhorn backup ls --volume-only s3://ara-prod-use1-longhorn-backup@us-east-1/
```
in several `longhorn-manager` pods especially `longhorn-manager-zbgh8`?

**Comment by gothka** [comment]
Hey @mantissahz, Not really timeout happens mostly across different cluster operating at our scale so doing operations using UI is generally not suitable for us.

Another thing to note is that LH doesn't create the backupvolume record that associates the backup with the volume. It happens as reconciliation of backups doesn't complete due to the hardcoded timeout.

```
ERRO[0120] Failed to list s3                             error="failed to list objects with param: {\n  Bucket: \"ara-prod-use1-longhorn-backup\",\n  Delimiter: \"/\",\n  Prefix: \"/\"\n} error: AWS Error:  AccessDenied Access Denied <nil>\n403 
3SA3X\n" pkg=s3
ERRO[0120] failed to list objects with param: {
  Bucket: "longhorn-backup",
  Delimiter: "/",
  Prefix: "/"
} error: AWS Error:  AccessDenied Access Denied <nil>
403 3SA3X1P34V6TNKNS
failed to list objects with param: {
  Bucket: "longhorn-backup",
  Delimiter: "/",
  Prefix: "/"
} error: AWS Error:  AccessDenied Access Denied <nil>
403 3SA3X
``` 

Looking at this, using the s3 creds that were provided, can't access the bucket? let me check that rerun the command again. 

could you please delete the reference to our environment/bucket name in the above comment?

**Comment by mantissahz** [comment]
Sorry about referencing our environment/bucket name, just delete the comment.

>Another thing to note is that LH doesn't create the backupvolume record that associates the backup with the volume. It happens as reconciliation of backups doesn't complete due to the hardcoded timeout

Could you test to create a backup without recurring jobs running and check if the backup volume synchronization is working well?

>error: AWS Error:  AccessDenied Access Denied

Can you try again after exporting the ENVs in the pods?
```bash
AWS_ACCESS_KEY_ID=<your-aws-access-key-id>
AWS_SECRET_ACCESS_KEY=<your-aws-secret-access-key>
... 
```

We will consider that to increase the timeout or make it tunable.

**Comment by gothka** [comment]
I've shared the out of that command for `longhorn-manager-zbgh8` via email since it's too big to share here.

> We will consider that to increase the timeout or make it tunable.
Tunable is more suitable for our use-case and hopefully can be back ported to v1.4.x

> Could you test to create a backup without recurring jobs running and check if the backup volume synchronization is working well?
I'll give this a try now and get back to you. I expect it to work well when done manually.

**Comment by gothka** [comment]
Hey @mantissahz, 

just an update, so i did delete all the old backups over the last week and the number went from 26432 to 3509, and can see the longhorn-manager cpu usage went significantly down (if not will blow up our cluster sooner or later) and costed about $400+ on s3 api calls alone.

I'm assuming this may happen quite frequently for us, is there a way to workaround this so the old backup doesn't grow overtime until this bug is fixed? I did try setting `failed-backup-ttl` but didn't work as expected as none of the 26,000+ volumes are in failed state.

**Comment by derekbit** [comment]
I'm considering ways to enhance scanning performance. Currently, we list all backups and compare them with the local Configuration Repository, which is time-intensive and costly. Instead of syncing backups between S3 and local resources repeatedly, we can utilize S3's [event notification APIs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/EventNotifications.html) after the initial sync. This approach would significantly reduce computing resource consumption.

If a remote storage such as NFS and CIFS doesn't provide the notification APIs, we can fall back to the legacy method.

**Comment by derekbit** [comment]
cc @ChanYiLin @shuo-wu @PhanLe1010 @c3y1huang

**Comment by shuo-wu** [comment]
Using S3 event notification APIs, let's say via Amazon SNS, requires extra configurations for AWS S3. And Longhorn needs to expose an endpoint for each S3 backupstore, right?

**Comment by derekbit** [comment]
> Using S3 event notification APIs, let's say via Amazon SNS, requires extra configurations for AWS S3. And Longhorn needs to expose an endpoint for each S3 backupstore, right?

Yes, more details in https://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.subscribe.html

**Comment by gothka** [comment]
hey @mantissahz! 

To give you an update, we've created a custom image with timeout set to `20m` and started running the custom image on our clusters. I'll monitor the lh-manager over the weekend and report back in any case.

> I did not see why the setting `failed-backup-ttl` did not work, it should have some logs in longhorn-manager and could you create the support bundle when this scenario (failed backups and `failed-backup-ttl` does not work) happens again?

Sorry, i can send the bundle but i've restarter the lh-manager few times and don't have a way to get the logs. I think those backups are not in failed state but rather old that weren't cleaned up. Also, enabling this setting requires polling s3 which could be an expensive operation, see: https://github.com/longhorn/longhorn/issues/1547

> You might need to delete the recurring job backup-2-7404cf1e-77074ba4 created on "2022-04-02T03:12:42Z", and it seems a duplicated one for the recurring job backup created on "2024-02-12T12:43:56Z".

Yes, i've deleted the duplicate backup recurring job across our fleet. 

Also, can i know why aren't the old backups being cleaned up the lh-manager consistently?

**Comment by derekbit** [comment]
> hey @mantissahz!
> 
> To give you an update, since we can't upgrade longhorn atm and this bug will fixed in a future release (not sure whether it'll be backported etc.) we've decided to created a custom image with timeout set to `20m` and started running the custom image on our cluster. I'll monitor the lh-manager over the weekend and report back in any case.

@gothka Any updates for the increase of timeout?

**Comment by gothka** [comment]
Hey @derekbit, everything seems to be working fine after bumping the timeouts. We no longer see any staled backups on the clusters nor high resource usage on longhorn-managers.

**Comment by derekbit** [comment]
> Hey @derekbit, everything seems to be working fine after bumping the timeouts. We no longer see any staled backups on the clusters nor high resource usage on longhorn-managers.

@gothka 
Thanks for the update. We will introduce the configurable timeout in the newer versions.

**Comment by derekbit** [comment]
Doc update is required.

**Comment by yangchiu** [comment]
>       The reproduce steps/test steps are at:
> 
> 
>     1. Fresh install Longhorn.
> 
>     2. The global setting `backup-engine-binary-timeout` is configurable.
> 
>     3. Check if the timeout works correctly.
> 

@mantissahz Is it possible to have a more detailed explanation of how this timeout functions? How can we trigger this timeout during the testing? Should we write large amount of data to the volume so that the backup creation time exceeds the timeout? Or should we make the backup store service unavailable to prevent the backup from being created? It would be appreciated if detailed test steps can be provided. Thank you!

**Comment by mantissahz** [comment]
Hi @yangchiu, 

This timeout configuration is used with the backup target/volume controller to execute some commands, for example, the command `longhorn backup ls --volume-only` is to get the backup volume list from the remote backup target server so it would be difficult to get the breakpoint that the command is executing.

Something we can try:
- Slow down the network speed of the remote backup target server.
- A large number of the backup volumes 
- Or I can build an image that will take 90 seconds to execute the command `longhorn backup ls --volume-only` and then you can see the error message is about the timeout in `status.conditions` of the `default` backup target.

**Comment by yangchiu** [comment]
Test steps:

1. With a custom longhorn engine image that `longhorn backup ls --volume-only` will sleep `90s` to simulate slow backup store server
2. Set a normal backup target and set `Backup Execution Timeout` to `1` 
3. The `Backup` UI tab will show timeout message after `1` minute:
```
failed to list backup volumes in nfs://longhorn-test-nfs-svc.default:/opt/backupstore: error listing backup volume names: timeout executing: /var/lib/longhorn/engine-binaries/jamesluhz-lh-engine-v09108319timeout90b01/longhorn [/var/lib/longhorn/engine-binaries/jamesluhz-lh-engine-v09108319timeout90b01/longhorn backup ls --volume-only nfs://longhorn-test-nfs-svc.default:/opt/backupstore]
```
4. The timeout message can also be found in `longhorn-manager` logs:
```
$ kubectl logs longhorn-manager-fsqp8 -n longhorn-system -c longhorn-manager | grep timeout
time="2024-09-10T05:44:28Z" level=error msg="Failed to get info from backup store" func="controller.(*BackupTargetController).reconcile" file="backup_target_controller.go:396" controller=longhorn-backup-target cred= error="failed to list backup volumes in nfs://longhorn-test-nfs-svc.default:/opt/backupstore: error listing backup volume names: timeout executing: /var/lib/longhorn/engine-binaries/jamesluhz-lh-engine-v09108319timeout90b01/longhorn [/var/lib/longhorn/engine-binaries/jamesluhz-lh-engine-v09108319timeout90b01/longhorn backup ls --volume-only nfs://longhorn-test-nfs-svc.default:/opt/backupstore]" interval=1m30s node=ip-10-0-1-186 url="nfs://longhorn-test-nfs-svc.default:/opt/backupstore"
```
5. Adjust `Backup Execution Timeout` to `2`, the `Backup` UI tab should work without problems, backup volumes can be listed and there is no error message shown on UI.

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-manager 6867e52) following [the test steps](https://github.com/longhorn/longhorn/issues/8319#issuecomment-2339690018).
