### ISSUE TITLE
The backup volumes listed by longhorn manager pods may be out of sync due to the cache of NFS v4.1

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#832]
This issue also leads to the failure of test `test_listing_backup_volume`

Reproduce steps:
1. Launch a NFS v4.1 server in the integration test. (The value of env `LONGHORN_BACKUPSTORES` in the `integration/deploy/test.yaml` will be like `"s3://backupbucket@us-east-1/backupstore$minio-secret,  nfs://<Server IP>:<Export Directory>"`.)
2. Run the test `test_listing_backup_volume` --> The test should fail in this line: `assert found1 & found2 & found3`. And one backup volume (alias: BV 1) should become invalid on the UI page.
3. Use `exec` to get into each longhorn manager pod, run backup volume list command: `/var/lib/rancher/longhorn/engine-binaries/<Engine Image Name>/longhorn backup ls --volume-only nfs://<Server IP>:<Export Directory>`
--> 
There is one manager pod (alias: Pod A) using the expired info/cache for the list command (The BV 1 info in the list result is wrong. it should contain error message like `cannot find backupstore/volumes/b1/6e/test1/volume.cfg in backupstore`) and two pods (Pod B, C) using the latest files for the command. 
-->
This means Pod A is using the expired NFS cache. Then you cannot find this `volume.cfg` file in the result of `ls /var/lib/longhorn/<Server IP with dots being replaced by underscores>/<Export Directory>/backupstore/volumes/<Random string>/<Random string>/<Volume Name>` but you can directly read the file with command `cat`.
4. Get into Pod B or C, rename one more `volume.cfg` file to `volume.cfg.tmp`. Then the corresponding backup volume (BV 2) will contain the similar error message.
5. Get into Pod A and run the backup volume list command. The Pod A will detect the renaming in step 2 and show the error message for BV 2 but it still won’t show the error message for BV 1.
-->
This means Pod A is still using the expired NFS cache for BV 1 but using the latest file for BV2.

Notice:
1. Longhorn manager/engine version: `longhornio/longhorn-xxxx:master`
2. The OS version of longhorn manager pods: 
```
# uname -srm
Linux 4.4.0-142-generic x86_64

# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
```
3. The `mount` version of the longhorn manager pods:
```
# mount --version
mount from util-linux 2.31.1 (libmount 2.31.1: selinux, btrfs, assert, debug)

# mount.nfs4 --version
mount.nfs4: (linux nfs-utils 1.3.3)
```
4. Kubernetes version v1.14.8

How to set up a NFS v4.1 server:
1. Launch a CentOS 7 instance
2. `yum install nfs-utils -y`
3. Create an export directory for the NFS server. e.g.`mkdir /opt/backupstore && chmod 755 /opt/backupstore`
4. Uncomment and modify `nfsd` setting in `/etc/nfs.conf` to enable NFS v4.1 only:
```
[nfsd]
vers2=n
vers3=n
vers4=y
vers4.0=n
vers4.1=y
vers4.2=n
```
5. 
```
systemctl enable rpcbind
systemctl enable nfs-server
systemctl enable nfs-lock
systemctl enable nfs-idmap
systemctl start rpcbind
systemctl start nfs-server
systemctl start nfs-lock
systemctl start nfs-idmap
```
6. Modify `/etc/exports` to export the directory. e.g. Add line `/opt/backupstore    *(rw,sync,no_root_squash,no_all_squash)` in `/etc/exports`
7. Restart NFS server then wait for 90 seconds. `systemctl restart nfs-server`
8. Check if only NFSv4.1 is enabled:
```
# cat /proc/fs/nfsd/versions
-2 -3 +4 -4.0 +4.1 -4.2
```

How to mount the NFS file system in NFS clients:
```
mount -t nfs4 <NFS Server IP>:<Export Directory> <Mount Directory>
```

**Comment by yasker** [comment]
@shuo-wu Can you add the steps to manually reproduce this problem without backup store? So we know for sure something is up with the NFS server or client.

**Comment by shuo-wu** [comment]
How to set up a NFS v4.1 server:
1. Launch a CentOS 7 instance
2. `yum install nfs-utils -y`
3. Create an export directory for the NFS server. e.g.`mkdir /opt/backupstore && chmod 755 /opt/backupstore`
4. Uncomment and modify `nfsd` setting in `/etc/nfs.conf` to enable NFS v4.1 only:
```
[nfsd]
vers2=n
vers3=n
vers4=y
vers4.0=n
vers4.1=y
vers4.2=n
```
5. 
```
systemctl enable rpcbind
systemctl enable nfs-server
systemctl enable nfs-lock
systemctl enable nfs-idmap
systemctl start rpcbind
systemctl start nfs-server
systemctl start nfs-lock
systemctl start nfs-idmap
```
6. Add line `/opt/backupstore    *(rw,sync,no_root_squash,no_all_squash)` in `/etc/exports`
7. Restart NFS server then wait for 90 seconds. `systemctl restart nfs-server`
8. Check if only NFSv4.1 is enabled:
```
# cat /proc/fs/nfsd/versions
-2 -3 +4 -4.0 +4.1 -4.2
```

How to mount the NFS file system in NFS clients:
```
mount -t nfs4 <NFS Server IP>:<Export Directory> <Mount Directory>
```

**Comment by shuo-wu** [comment]
Cannot reproduce this issue with a brand new NFS v4.1 server.
