### ISSUE TITLE
[BUG] Can not add block disk on longhorn node

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#8320]
## Describe the bug

Can not add block disk to node on longhorn master-head, this symptom did **not** observe in v1.6.x and v1.5.x branches

instance-manager log :
```
[2024-04-09 03:58:03.390455] bdev.c:8020:bdev_open_ext: *NOTICE*: Currently unable to find bdev with name: disk-1
[longhorn-instance-manager] time="2024-04-09T03:58:03Z" level=error msg="Failed to get disk info" func=spdk.svcDiskGet.func1 file="disk.go:130" diskDriver= diskName=disk-1 diskPath=/dev/loop3 error="rpc error: code = NotFound desc = cannot find disk bdev with name disk-1"
[longhorn-instance-manager] time="2024-04-09T03:58:03Z" level=info msg="Disk Server: Creating disk" func="disk.(*Server).DiskCreate" file="disk.go:121" blockSize=4096 diskDriver= diskName=disk-1 diskPath=/dev/loop3 diskType=block
[longhorn-instance-manager] time="2024-04-09T03:58:03Z" level=info msg="Creating disk" func=spdk.svcDiskCreate file="disk.go:45" blockSize=4096 diskDriver= diskName=disk-1 diskPath=/dev/loop3 diskUUID=
[longhorn-instance-manager] time="2024-04-09T03:58:03Z" level=error msg="Failed to create disk" func=spdk.svcDiskCreate.func1 file="disk.go:48" blockSize=4096 diskDriver= diskName=disk-1 diskPath=/dev/loop3 diskUUID= error="failed to get disk driver for disk disk-1: unsupported disk driver  for disk path /dev/loop3"
```

Not sure if this is due to some reviewing PRs, create this ticket for tracking.

## To Reproduce

Add block disk to Longhorn master, the disk stuck at unschedulable

## Expected behavior

Add block disk to Longhorn master success

## Support bundle for troubleshooting

[supportbundle_7dd7a80c-0211-4fa9-8bd2-870722164cec_2024-04-09T04-01-20Z.zip](https://github.com/longhorn/longhorn/files/14913221/supportbundle_7dd7a80c-0211-4fa9-8bd2-870722164cec_2024-04-09T04-01-20Z.zip)

## Environment

 - Longhorn version: master

## Additional context

N/A

**Comment by derekbit** [comment]
The PR in longhorn-manager is still under review.
https://github.com/longhorn/longhorn-manager/pull/2642

**Comment by innobead** [comment]
> The PR in longhorn-manager is still under review. [longhorn/longhorn-manager#2642](https://github.com/longhorn/longhorn-manager/pull/2642)

The PR has been merged.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `09633d`), block disk add success and create workload with v2 volume success.
