### ISSUE TITLE
[IMPROVEMENT] Setting Controller May Have Race Condition From Different Node

### ISSUE THREAD

**Issue by WebberHuang1118** [longhorn/longhorn#8324]
## Description
IIUC, LH setting controller tends to [sync setting CRs per hour,](https://github.com/longhorn/longhorn-manager/blob/88c792f7df38383634c2c8401f96d999385458c1/controller/setting_controller.go#L51) however, after adding some trace in setting controller, I found all LH manager ds would try to do the reconcile in an interleaving manner, as a result, the reconcile period is much shorter than the defined value, as I change the `settingControllerResyncPeriod` as one minute, I found following setting controller traces on different nodes (from two-node Harvester):

on node 0
```
2024-04-09T07:01:51Z
2024-04-09T07:03:19Z
2024-04-09T07:04:19Z
2024-04-09T07:05:19Z
2024-04-09T07:06:19Z
```
on node1
```
2024-04-09T07:02:03Z
2024-04-09T07:03:29Z
2024-04-09T07:04:29Z
2024-04-09T07:05:29Z
2024-04-09T07:06:29Z
```
The real resync period would be much shorter as the number of nodes grows, maybe there should be only one node is responsible to reconcile CR setting at a time

## Additional context
Envionment:
- Harvester version: v1.2-head
- LH version: v1.5.3

**Comment by innobead** [comment]
@derekbit IIRC, we have a plan to make setting controller only available in one node (leader election?), right? If yes, do we already have an issue for that?

**Comment by innobead** [comment]
Let's use the issue mentioned by @derekbit instead.
