### ISSUE TITLE
[TASK] Mirror the `quay.io/openshift/origin-oauth-proxy` image to Longhorn repo similar to what we are doing for CSI sidecar images

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#8329]
Mirror the `quay.io/openshift/origin-oauth-proxy` image to the Longhorn repo similar to what we are doing for CSI sidecar images. This will make the image management become uniform and improve the user experience for airgap installation https://longhorn.io/docs/1.7.0/deploy/install/airgap/

## Additional context

This is issue is the blocker for the Rancher chart release https://github.com/rancher/charts/pull/3753#issuecomment-2046001557

**Comment by PhanLe1010** [comment]
Plan:
- [ ] Add the image to https://github.com/longhorn/longhorn/blob/master/deploy/longhorn-images.txt under the name `longhornio/origin-oauth-proxy:4.14` @PhanLe1010 
- [ ] Run the CI to mirror and upload `quay.io/openshift/origin-oauth-proxy:4.14` to `longhornio/origin-oauth-proxy:4.14` cc @yangchiu @khushboo-rancher This image seems not a multi-arch image
- [ ] Mirror the image `longhornio/origin-oauth-proxy:4.14` to rancher repo https://github.com/rancher/image-mirror/blob/master/images-list @PhanLe1010 
- [ ] Update the Rancher chart to the Rancher mirror image to avoid this failed check https://github.com/rancher/charts/pull/3753#issuecomment-2046001557 @mantissahz

**Comment by PhanLe1010** [comment]
Test Plan:

Rerun the test at https://github.com/longhorn/longhorn/issues/1831#issuecomment-1710266194

**Comment by roger-ryao** [comment]
**Verified on master-head 20240506**

- longhorn master-head https://github.com/longhorn/longhorn/commit/ea1d18a62699b7fd1ba70af1951f190dafdbb094

**The test steps**
https://github.com/longhorn/longhorn/issues/1831#issuecomment-1352487615

**Result Passed**

- [x] OKD cluster new installed.
- [x] Follow the steps in [longhorn/chart/ocp-readme.md](https://github.com/longhorn/longhorn/blob/master/chart/ocp-readme.md)
- [x] Functionalities of Longhorn work well.
    1.   Fresh install 
    2.   Create a statefulset and write data
    3.   Scale down/up workload
    4.   Trigger replica rebuilding
    5.   Create volume backup and restored
    6.   Verify volume data
    7.   Uninstall

**Comment by innobead** [comment]
@roger-ryao which OKD version you tested? 

@mantissahz IIRC, some users had feedback about Longhorn having issues to deploy on newer versions , right?

**Comment by roger-ryao** [comment]
> which OKD version you tested

Hi @innobead 
    I tested it on `4.10.0-0.okd-2022-07-09-073606`
