### ISSUE TITLE
[IMPROVEMENT] Add the ability to add custom labels to workloads

### ISSUE THREAD

**Issue by gauravngandhi** [longhorn/longhorn#8340]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The existing helm charts don't have a way for us to add custom labels to each workload and related configurations. We could use custom labels to help us easily filter on metrics etc

## Describe the solution you'd like

Add custom labels to each workload. We can have two things. Global custom labels which applies to all manifests and then a workload specific custom label 
Eg: 
```yaml
engine:
  customLabel:
manager:
  customLabel:
...
```

**Comment by derekbit** [comment]
Can you elaborate more on the purpose of the custoLabel?
All Longhorn pods have corresponding lables such as `app: longhorn-manager`. Are they not enough for your use case?

**Comment by gauravngandhi** [comment]
When we deploy these helm charts to our clusters, we would like to add more information to the workloads being deployed as part of the helm chart. If we get the ability to add custom labels we would be able to add the extra information we would like to the resources being deployed as part of the helm chart.

Our use case is, we have an umbrella helm chart dependent on longhorn's helm chart. We would like to have umbrella helm chart's details like name and version to be added as labels in the resources to help us identify the resources. Eg: we could have prometheus add these as labels to the metric for us to view our inventory(things we have deployed to the cluster, their version etc)
