### ISSUE TITLE
[QUESTION] longhorn-manager pods in CrashLoopBackOff state and longhorn-uninstall pods in Error state

### ISSUE THREAD

**Issue by raphael10-collab** [longhorn/longhorn#8349]
## Environment

 - Longhorn version: 1.6.1.
 - Kubernetes version: 
       root@k8s-eu-1-control-plane-node-1:~# kubectl version
       Client Version: v1.28.8
       Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
       Server Version: v1.28.8
 - Node config
   - OS type and version : Ubuntu 22.04
   - Kernel version : 
    root@k8s-eu-1-control-plane-node-1:~# uname -r
    5.15.0-102-generic
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes
 
    root@k8s-eu-1-control-plane-node-1:~# kubectl get nodes
    NAME                            STATUS   ROLES           AGE    VERSION
    k8s-eu-1-control-plane-node-1   Ready    control-plane   2d1h   v1.28.8
    k8s-eu-1-control-plane-node-2   Ready    control-plane   2d     v1.28.8
    k8s-eu-1-control-plane-node-3   Ready    control-plane   2d     v1.28.8
    k8s-eu-1-worker-1               Ready    <none>          2d     v1.28.8
    k8s-eu-1-worker-2               Ready    <none>          47h    v1.28.8
    k8s-eu-1-worker-3               Ready    <none>          47h    v1.28.8
    k8s-eu-1-worker-4               Ready    <none>          47h    v1.28.8

    k8s-eu-1-control-plane-node-1/2/3 +  k8s-eu-1-worker-4:  Cloud VPS-S each : 
        4 vCPU cores
        8 GB RAM
        400 GB SSD
        32 TB Traffic (unlimited incoming)

    k8s-eu-1-worker-1/2/3: Cloud VPS-XL each:
        10 vCPU cores
        60 GB RAM
        1.6 TB SSD
        32 TB Traffic (unlimited incoming)
        

 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): 
    Baremetal Cloud VPS Provider: Contabo

I installed Longhorn through helm:

    root@k8s-eu-1-control-plane-node-1:~# helm repo add longhorn https://charts.longhorn.io
    "longhorn" has been added to your repositories
    root@k8s-eu-1-control-plane-node-1:~# helm repo update
    Hang tight while we grab the latest from your chart repositories...
    ...Successfully got an update from the "longhorn" chart repository
    ...Successfully got an update from the "cilium" chart repository
    ...Successfully got an update from the "prometheus-community" chart repository
    Update Complete. ⎈Happy Helming!⎈
    root@k8s-eu-1-control-plane-node-1:~# helm repo ls
    NAME                	URL                                               
    cilium              	https://helm.cilium.io/                           
    prometheus-community	https://prometheus-community.github.io/helm-charts
    longhorn            	https://charts.longhorn.io                        

    root@k8s-eu-1-control-plane-node-1:~# helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace --version 1.6.1
    NAME: longhorn
    LAST DEPLOYED: Thu Apr 11 18:16:24 2024
    NAMESPACE: longhorn-system
    STATUS: deployed
    REVISION: 1
    TEST SUITE: None
    NOTES:
    Longhorn is now installed on the cluster!
    
    Please wait a few minutes for other Longhorn components such as CSI deployments, Engine Images, and Instance Managers to be initialized.
    
    Visit our documentation at https://longhorn.io/docs/

But the `longhorn-manager` pods remain in `CrashLoopBackOff` state , and the `longhorn-uninstall` pods in `Error` state:
    
    root@k8s-eu-1-control-plane-node-1:~# kubectl get pods -n longhorn-system
    NAME                                     READY   STATUS             RESTARTS        AGE
    longhorn-driver-deployer-9f4fc86-mtnv8   0/1     Init:0/1           0               13m
    longhorn-manager-88dsx                   0/1     CrashLoopBackOff   7 (2m24s ago)   13m
    longhorn-manager-khxnr                   0/1     CrashLoopBackOff   7 (2m37s ago)   13m
    longhorn-manager-q4xlz                   0/1     CrashLoopBackOff   7 (2m20s ago)   13m
    longhorn-manager-wp559                   0/1     CrashLoopBackOff   7 (2m32s ago)   13m
    longhorn-manager-z9r8m                   0/1     CrashLoopBackOff   7 (2m36s ago)   13m
    longhorn-ui-5f4b7bbf69-gvsnc             1/1     Running            0               13m
    longhorn-ui-5f4b7bbf69-v8w9x             1/1     Running            0               13m
    longhorn-uninstall-hd4qz                 0/1     Error              0               9m55s
    longhorn-uninstall-wx8tp                 0/1     Error              0               9m41s

Example of `longhorn-manager` pod in `CrashLoopBackOff` state : 

    root@k8s-eu-1-control-plane-node-1:~# kubectl describe pod longhorn-manager-88dsx -n longhorn-system
    Name:                 longhorn-manager-88dsx
    Namespace:            longhorn-system
    Priority:             1000000000
    Priority Class Name:  longhorn-critical
    Service Account:      longhorn-service-account
    Node:                 k8s-eu-1-control-plane-node-1/38.242.250.38
    Start Time:           Thu, 11 Apr 2024 18:16:27 +0200
    Labels:               app=longhorn-manager
                          app.kubernetes.io/instance=longhorn
                          app.kubernetes.io/managed-by=Helm
                          app.kubernetes.io/name=longhorn
                          app.kubernetes.io/version=v1.6.1
                          controller-revision-hash=758dbbd69b
                          helm.sh/chart=longhorn-1.6.1
                          pod-template-generation=1
    Annotations:          <none>
    Status:               Running
    IP:                   10.0.0.160
    IPs:
      IP:           10.0.0.160
    Controlled By:  DaemonSet/longhorn-manager
    Containers:
      longhorn-manager:
        Container ID:  cri-o://4eeb64b7c18fb6b566203d4a4112a8871332c783473b5ec751100b13764260e3
        Image:         longhornio/longhorn-manager:v1.6.1
        Image ID:      docker.io/longhornio/longhorn-manager@sha256:69a4dde599ab9fb2e506ea2eeed4f939b8c282fd7a073f8ba2ddccf3f844089e
        Ports:         9500/TCP, 9501/TCP, 9502/TCP, 9503/TCP
        Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
        Command:
          longhorn-manager
          -d
          daemon
          --engine-image
          longhornio/longhorn-engine:v1.6.1
          --instance-manager-image
          longhornio/longhorn-instance-manager:v1.6.1
          --share-manager-image
          longhornio/longhorn-share-manager:v1.6.1
          --backing-image-manager-image
          longhornio/backing-image-manager:v1.6.1
          --support-bundle-manager-image
          longhornio/support-bundle-kit:v0.0.36
          --manager-image
          longhornio/longhorn-manager:v1.6.1
          --service-account
          longhorn-service-account
          --upgrade-version-check
        State:          Waiting
          Reason:       CrashLoopBackOff
        Last State:     Terminated
          Reason:       Error
          Exit Code:    1
          Started:      Thu, 11 Apr 2024 18:27:39 +0200
          Finished:     Thu, 11 Apr 2024 18:27:40 +0200
        Ready:          False
        Restart Count:  7
        Readiness:      http-get https://:9501/v1/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
        Environment:
          POD_NAMESPACE:  longhorn-system (v1:metadata.namespace)
          POD_IP:          (v1:status.podIP)
          NODE_NAME:       (v1:spec.nodeName)
        Mounts:
          /host/dev/ from dev (rw)
          /host/proc/ from proc (rw)
          /tls-files/ from longhorn-grpc-tls (rw)
          /var/lib/longhorn/ from longhorn (rw)
          /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jzll2 (ro)
    Conditions:
      Type              Status
      Initialized       True 
      Ready             False 
      ContainersReady   False 
      PodScheduled      True 
    Volumes:
      dev:
        Type:          HostPath (bare host directory volume)
        Path:          /dev/
        HostPathType:  
      proc:
        Type:          HostPath (bare host directory volume)
        Path:          /proc/
        HostPathType:  
      longhorn:
        Type:          HostPath (bare host directory volume)
        Path:          /var/lib/longhorn/
        HostPathType:  
      longhorn-grpc-tls:
        Type:        Secret (a volume populated by a Secret)
        SecretName:  longhorn-grpc-tls
        Optional:    true
      kube-api-access-jzll2:
        Type:                    Projected (a volume that contains injected data from multiple sources)
        TokenExpirationSeconds:  3607
        ConfigMapName:           kube-root-ca.crt
        ConfigMapOptional:       <nil>
        DownwardAPI:             true
    QoS Class:                   BestEffort
    Node-Selectors:              <none>
    Tolerations:                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                                 node.kubernetes.io/not-ready:NoExecute op=Exists
                                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                                 node.kubernetes.io/unreachable:NoExecute op=Exists
                                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
    Events:
      Type     Reason     Age                 From               Message
      ----     ------     ----                ----               -------
      Normal   Scheduled  16m                 default-scheduler  Successfully assigned longhorn-system/longhorn-manager-88dsx to k8s-eu-1-control-plane-node-1
      Normal   Pulling    16m                 kubelet            Pulling image "longhornio/longhorn-manager:v1.6.1"
      Normal   Pulled     15m                 kubelet            Successfully pulled image "longhornio/longhorn-manager:v1.6.1" in 13.329s (13.329s including waiting)
      Normal   Created    14m (x5 over 15m)   kubelet            Created container longhorn-manager
      Normal   Started    14m (x5 over 15m)   kubelet            Started container longhorn-manager
      Normal   Pulled     14m (x4 over 15m)   kubelet            Container image "longhornio/longhorn-manager:v1.6.1" already present on machine
      Warning  BackOff    59s (x75 over 15m)  kubelet            Back-off restarting failed container longhorn-manager in pod longhorn-manager-88dsx_longhorn-system(cdc601a6-4b7f-41ff-8752-9551a7f80228)

And, example of `longhorn-uninstall` pod in `Error` state : 

    root@k8s-eu-1-control-plane-node-1:~# kubectl describe pod longhorn-uninstall-hd4qz -n longhorn-system
    Name:                 longhorn-uninstall-hd4qz
    Namespace:            longhorn-system
    Priority:             1000000000
    Priority Class Name:  longhorn-critical
    Service Account:      longhorn-service-account
    Node:                 k8s-eu-1-worker-2/38.242.249.121
    Start Time:           Thu, 11 Apr 2024 18:20:09 +0200
    Labels:               app.kubernetes.io/instance=longhorn
                          app.kubernetes.io/managed-by=Helm
                          app.kubernetes.io/name=longhorn
                          app.kubernetes.io/version=v1.6.1
                          batch.kubernetes.io/controller-uid=5da939b0-4101-4926-83a1-6101cfe98965
                          batch.kubernetes.io/job-name=longhorn-uninstall
                          controller-uid=5da939b0-4101-4926-83a1-6101cfe98965
                          helm.sh/chart=longhorn-1.6.1
                          job-name=longhorn-uninstall
    Annotations:          <none>
    Status:               Failed
    IP:                   10.0.4.119
    IPs:
      IP:           10.0.4.119
    Controlled By:  Job/longhorn-uninstall
    Containers:
      longhorn-uninstall:
        Container ID:  cri-o://c3642973e07a155bcb6c69eeb3b46c0eb8cceb460583af8aadcd69d6996d5758
        Image:         longhornio/longhorn-manager:v1.6.1
        Image ID:      docker.io/longhornio/longhorn-manager@sha256:69a4dde599ab9fb2e506ea2eeed4f939b8c282fd7a073f8ba2ddccf3f844089e
        Port:          <none>
        Host Port:     <none>
        Command:
          longhorn-manager
          uninstall
          --force
        State:          Terminated
          Reason:       Error
          Exit Code:    1
          Started:      Thu, 11 Apr 2024 18:20:09 +0200
          Finished:     Thu, 11 Apr 2024 18:20:13 +0200
        Ready:          False
        Restart Count:  0
        Environment:
          LONGHORN_NAMESPACE:  longhorn-system (v1:metadata.namespace)
        Mounts:
          /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-pvtrr (ro)
    Conditions:
      Type              Status
      Initialized       True 
      Ready             False 
      ContainersReady   False 
      PodScheduled      True 
    Volumes:
      kube-api-access-pvtrr:
        Type:                    Projected (a volume that contains injected data from multiple sources)
        TokenExpirationSeconds:  3607
        ConfigMapName:           kube-root-ca.crt
        ConfigMapOptional:       <nil>
        DownwardAPI:             true
    QoS Class:                   BestEffort
    Node-Selectors:              <none>
    Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
    Events:
      Type    Reason     Age   From               Message
      ----    ------     ----  ----               -------
      Normal  Scheduled  14m   default-scheduler  Successfully assigned longhorn-system/longhorn-uninstall-hd4qz to k8s-eu-1-worker-2
      Normal  Pulled     14m   kubelet            Container image "longhornio/longhorn-manager:v1.6.1" already present on machine
      Normal  Created    14m   kubelet            Created container longhorn-uninstall
      Normal  Started    14m   kubelet            Started container longhorn-uninstall

What do I have to do to make all the longhorn-system pods become in `Running` state?

**Comment by derekbit** [comment]
Do you see error log messages in the longhorn-uninstall pod?

**Comment by raphael10-collab** [comment]
Hi @derekbit 

Yesterday I had issues also during the un-installation process, and I had to clean everything up through these steps:
https://longhorn.io/docs/1.6.1/deploy/uninstall/#uninstalling-longhorn-using-kubectl

**Comment by derekbit** [comment]
Can you check the log messages of the longhorn-manager pods?
For example
`kubectl -n longhorn-system logs longhorn-manager-9tnbl -f`
`kubectl -n longhorn-system logs longhorn-manager-9tnbl --previous`

**Comment by raphael10-collab** [comment]
` logs longhorn-manager-9tnbl` : 

    root@k8s-eu-1-control-plane-node-1:~# kubectl -n longhorn-system logs longhorn-manager-9tnbl -f
    time="2024-04-12T08:38:20Z" level=fatal msg="Error starting manager: Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host: failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm --version], output , stderr nsenter: failed to execute iscsiadm: No such file or directory\n: exit status 127" func=main.main.DaemonCmd.func3 file="daemon.go:92"
    
    root@k8s-eu-1-control-plane-node-1:~# kubectl -n longhorn-system logs longhorn-manager-9tnbl --previous
    time="2024-04-12T08:38:20Z" level=fatal msg="Error starting manager: Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host: failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm --version], output , stderr nsenter: failed to execute iscsiadm: No such file or directory\n: exit status 127" func=main.main.DaemonCmd.func3 file="daemon.go:92"

**Comment by derekbit** [comment]
OK. You need to install iSCSI utility and some dependencies. Please see https://longhorn.io/docs/1.6.1/deploy/install/.

**Comment by raphael10-collab** [comment]
I read that iscsid daemon has to be running on all the nodes.

Does it mean that I have to install in all nodes both the Ubuntu package open-iscsi and the longhorn-iscsi  : https://raw.githubusercontent.com/longhorn/longhorn/v1.6.1/deploy/prerequisite/longhorn-iscsi-installation.yaml  ?

**Comment by raphael10-collab** [comment]
I've installed iscsi tools in all the nodes apart from one, which I'm not able to connect to today, and for which I've contacted the Contabo Cloud Support Team

So, I guess, it will take a while for the whole process today

**Comment by derekbit** [comment]
> , which I'm not able to connect to today, and for which I've contacted the Contabo Cloud Support Team
> 
> So, I guess, it will take a while for the whole process today

OK! Take your time. Hope we can get good news soon! :)

**Comment by raphael10-collab** [comment]
It seems that now all the requirements are fulfilled for all kubernetes nodes:

    root@k8s-eu-1-control-plane-node-1:~# curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.6.1/scripts/environment_check.sh | bash
    [INFO]  Required dependencies 'kubectl jq mktemp sort printf' are installed.
    [INFO]  All nodes have unique hostnames.
    [INFO]  Waiting for longhorn-environment-check pods to become ready (0/5)...
    [INFO]  All longhorn-environment-check pods are ready (5/5).
    [INFO]  MountPropagation is enabled
    [INFO]  Checking kernel release...
    [INFO]  Checking iscsid...
    [INFO]  Checking multipathd...
    [INFO]  Checking packages...
    [INFO]  Checking nfs client...
    [INFO]  Cleaning up longhorn-environment-check pods...
    [INFO]  Cleanup completed.
    
    root@k8s-eu-1-control-plane-node-1:~# kubectl version
    Client Version: v1.28.8
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    Server Version: v1.28.8

I re-installed longhorn

    root@k8s-eu-1-control-plane-node-1:~# helm repo add longhorn https://charts.longhorn.io
    "longhorn" already exists with the same configuration, skipping
    root@k8s-eu-1-control-plane-node-1:~# helm repo update
    Hang tight while we grab the latest from your chart repositories...
    ...Successfully got an update from the "longhorn" chart repository
    ...Successfully got an update from the "cilium" chart repository
    ...Successfully got an update from the "prometheus-community" chart repository
    Update Complete. ⎈Happy Helming!⎈
    root@k8s-eu-1-control-plane-node-1:~# helm repo ls
    NAME                	URL                                               
    cilium              	https://helm.cilium.io/                           
    prometheus-community	https://prometheus-community.github.io/helm-charts
    longhorn            	https://charts.longhorn.io 

    root@k8s-eu-1-control-plane-node-1:~# helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace --version 1.6.1
    NAME: longhorn
    LAST DEPLOYED: Mon Apr 15 09:39:06 2024
    NAMESPACE: longhorn-system
    STATUS: deployed
    REVISION: 1
    TEST SUITE: None
    NOTES:
    Longhorn is now installed on the cluster!
    
    Please wait a few minutes for other Longhorn components such as CSI deployments, Engine Images, and Instance Managers to be initialized.
    
    Visit our documentation at https://longhorn.io/docs/


And now the pods are all in Running state : 

    root@k8s-eu-1-control-plane-node-1:~# kubectl -n longhorn-system get pod
    NAME                                                READY   STATUS    RESTARTS   AGE
    csi-attacher-5c4bfdcf59-bdggn                       1/1     Running   0          4m3s
    csi-attacher-5c4bfdcf59-glr9c                       1/1     Running   0          4m3s
    csi-attacher-5c4bfdcf59-wbn9d                       1/1     Running   0          4m3s
    csi-provisioner-667796df57-bkxgf                    1/1     Running   0          4m3s
    csi-provisioner-667796df57-g2d57                    1/1     Running   0          4m3s
    csi-provisioner-667796df57-p99tm                    1/1     Running   0          4m3s
    csi-resizer-694f8f5f64-48h6q                        1/1     Running   0          4m3s
    csi-resizer-694f8f5f64-4wtt2                        1/1     Running   0          4m3s
    csi-resizer-694f8f5f64-n8m6w                        1/1     Running   0          4m3s
    csi-snapshotter-959b69d4b-8v2nz                     1/1     Running   0          4m3s
    csi-snapshotter-959b69d4b-dxvvz                     1/1     Running   0          4m3s
    csi-snapshotter-959b69d4b-rmwxg                     1/1     Running   0          4m3s
    engine-image-ei-5cefaf2b-2r7td                      1/1     Running   0          4m10s
    engine-image-ei-5cefaf2b-7v899                      1/1     Running   0          4m10s
    engine-image-ei-5cefaf2b-b5fnm                      1/1     Running   0          4m10s
    engine-image-ei-5cefaf2b-jdwd6                      1/1     Running   0          4m10s
    engine-image-ei-5cefaf2b-tbwm2                      1/1     Running   0          4m10s
    instance-manager-350386a73f401a602f1783938be991c0   1/1     Running   0          4m10s
    instance-manager-4f65765c001f2b941bc5d728b65d4a32   1/1     Running   0          4m10s
    instance-manager-51492326327041ac5956619303cd25e7   1/1     Running   0          4m6s
    instance-manager-58ba023cfd09576814ec35835c1d718f   1/1     Running   0          4m10s
    instance-manager-df0e119506168285bcc61fb5bbe710ae   1/1     Running   0          4m10s
    longhorn-csi-plugin-8gcz2                           3/3     Running   0          4m3s
    longhorn-csi-plugin-8gpgr                           3/3     Running   0          4m3s
    longhorn-csi-plugin-jkshn                           3/3     Running   0          4m3s
    longhorn-csi-plugin-lnr9q                           3/3     Running   0          4m3s
    longhorn-csi-plugin-wshnd                           3/3     Running   0          4m3s
    longhorn-driver-deployer-9f4fc86-w2x6f              1/1     Running   0          4m18s
    longhorn-manager-9rr2c                              1/1     Running   0          4m18s
    longhorn-manager-b4wk6                              1/1     Running   0          4m18s
    longhorn-manager-b9b4r                              1/1     Running   0          4m18s
    longhorn-manager-r7zgs                              1/1     Running   0          4m18s
    longhorn-manager-wbgv2                              1/1     Running   0          4m18s
    longhorn-ui-5f4b7bbf69-f6zsz                        1/1     Running   0          4m18s
    longhorn-ui-5f4b7bbf69-r7m5w                        1/1     Running   0          4m17s

Thank you @derekbit for your kind help
