### ISSUE TITLE
[BUG]cannot mount a PV into a pods

### ISSUE THREAD

**Issue by sarce666** [longhorn/longhorn#8360]
hello 

i have a pv bound to a PVC in longhorn 1.4
every thing perfect
when i try to mound it in m y pods i
it is sutkced in pending : 
Unable to attach or mount volumes: unmounted volumes=[volv], unattached volumes=[kube-api-access-h7bqw volv]: timed out waiting for the condition
Source
kubelet pool-18f82-krhyi
Count
2
Sub-object
Last seen
2024-04-15T16:34:23+02:00
AttachVolume.Attach failed for volume "pvc-backup-metis" : timed out waiting for external-attacher of driver.longhorn.io CSI driver to attach volume pvc-backup-metis
Source
attachdetach-controller

and this to every pv from longhorn 
thanks so much

**Comment by sarce666** [comment]
for your info 
all the replicas of the volume are OK

**Comment by mantissahz** [comment]
Hi @sarce666,
Could you provide the way you mounted the volumes with workload and the support bundle for investigating (we might find the root cause in the logs of Longhorn CSI attacher)?
