### ISSUE TITLE
[IMPROVEMENT] Auto cleanup related Snapshot when removing Backup

### ISSUE THREAD

**Issue by FrankYang0529** [longhorn/longhorn#8365]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

When users create a Bakcup, LH automatically creates a related Snapshot. However, when users delete the Bakcup, LH doesn't cleanup the Snapshot.

## Describe the solution you'd like

Add a controller to watch LH Backup event. If there is a deletion event and related Snapshot exists, removing the Snapshot.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240626**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/7e01ba13b41dd74689da8ec9e474baaf91363acc
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/77ac26d09a1bc18e743efa2e6bb94efc7d0fa4da

**The test steps**
https://github.com/longhorn/longhorn-manager/pull/2783#issue-2285011948

**Result Passed**

- [x] UI test passed : `Automatically Cleanup Snapshot When Deleting Backup` 
    
![Screenshot_20240626_190629](https://github.com/longhorn/longhorn/assets/104337648/0d10a194-208d-429b-a450-fb53deff3004)
 
- [x] kubectl test passed : `kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs auto-cleanup-when-delete-backup ` 
- [x] require/backport : backport/1.5.6, backport/1.6.3 
- [x] require/doc : https://github.com/longhorn/website/pull/928
- [x] require/manual-test-plan: https://github.com/longhorn/longhorn-manager/pull/2783#issue-2285011948 ( We can refer to these test steps to implement the auto-e2e-test )

**Comment by derekbit** [comment]
The improvement introduces a new setting, so we don't need to backport to v1.5.x and v1.6.x.

cc @innobead
