### ISSUE TITLE
Security issues in latest longhorn docker images

### ISSUE THREAD

**Issue by vr2388** [longhorn/longhorn#8372]
## Describe the bug

We have scanned the latest longhorn docker images and found few **high** and **critical** security issues. 

## To Reproduce

Scan the images with any security scanning tool.

## Expected behavior

All the security issues should be fixed as we have high and critical issues.

## Security Issues 
We found security issues in following images 
**Longhorn-manager**:
<img width="1412" alt="Screenshot 2024-04-16 at 4 26 48 PM" src="https://github.com/longhorn/longhorn/assets/133762455/965

**longhorn-engine**:
<img width="1441" alt="Screenshot 2024-04-16 at 4 29 43 PM" src="https://github.com/longhorn/longhorn/assets/133762455/23af6312-aa01-4df5-82f6-3cbc8702d6e3">
<img width="1392" alt="Screenshot 2024-04-16 at 4 30 03 PM" src="https://github.com/longhorn/longhorn/assets/133762455/0c330e3c-1576-4a78-be6d-85a5b73f21a2">
8021f-4e3e-4ba2-b7a4-fc2caf8eaf93">

**longhorn-instance-manager**:
<img width="1423" alt="Screenshot 2024-04-16 at 4 40 47 PM" src="https://github.com/longhorn/longhorn/assets/133762455/8cb468b4-1b5b-4c41-ba59-18278ab7a14a">
<img width="1367" alt="Screenshot 2024-04-16 at 4 41 21 PM" src="https://github.com/longhorn/longhorn/assets/133762455/a28ac734-faea-4216-b47e-0b21182c292b">

**longhorn-share-manager**:
<img width="1404" alt="Screenshot 2024-04-16 at 4 42 44 PM" src="https://github.com/longhorn/longhorn/assets/133762455/c4833048-d987-4652-83b7-ff6d61598de2">

**csi-node-driver-registrar**:
<img width="1375" alt="Screenshot 2024-04-16 at 4 45 45 PM" src="https://github.com/longhorn/longhorn/assets/133762455/34e34296-16a0-4409-bfbf-7a36a46ed1b3">

**support-bundle-kit**:
<img width="1140" alt="Screenshot 2024-04-16 at 4 47 28 PM" src="https://github.com/longhorn/longhorn/assets/133762455/3b4fbfab-ebf1-4ac2-910c-8fa325e26c39">
<img width="907" alt="Screenshot 2024-04-16 at 4 47 46 PM" src="https://github.com/longhorn/longhorn/assets/133762455/a2df451d-5455-4273-aa55-822656331fe2">

**csi-snapshotter**:
<img width="1394" alt="Screenshot 2024-04-16 at 4 48 51 PM" src="https://github.com/longhorn/longhorn/assets/133762455/70f674f3-02d7-43ef-9c3a-75a8b3ad3f9a">

**csi-resizer**:
<img width="1359" alt="Screenshot 2024-04-16 at 4 49 53 PM" src="https://github.com/longhorn/longhorn/assets/133762455/960d93f5-98aa-4fe4-8ff8-5abcf983642a">

**csi-provisioner**:
<img width="1411" alt="Screenshot 2024-04-16 at 4 51 01 PM" src="https://github.com/longhorn/longhorn/assets/133762455/b5e5cdc9-d716-44aa-b85d-14afbca29aa3">

**csi-attacher**:
<img width="1417" alt="Screenshot 2024-04-16 at 4 51 32 PM" src="https://github.com/longhorn/longhorn/assets/133762455/262ac156-e5f2-4239-a460-35acc3482944">

**Comment by derekbit** [comment]
cc @c3y1huang

**Comment by derekbit** [comment]
@innobead @c3y1huang  Should we address the security issue in the upcoming v1.5.5?

**Comment by innobead** [comment]
I believe most critical issues have been fixed by renovate update and base image. Have we checked the tricky report by QA when testing 1.5.5 RCs? 

For each release, package update and host package update in container images should mostly naturally happen when building a new image.

Python host packages relying on BCI. IIRC, no fixes yet. But for golang dependencies, anything we didn’t fix yet by renovate?

@c3y1huang for this report, see what we miss and still can fix in 1.5.5.

**Comment by chriscchien** [comment]
Yes, we have v1.5.5 RC security test results [here](https://github.com/longhorn/longhorn/issues/8356#issuecomment-2060182319) and not found cititcal issues.

- [v1.5.5-rc1](https://ci.longhorn.io/job/private/job/image-security-scan/1399/): 81 HIGH, 0 CRITICAL
- [v1.5.5-rc2 ](https://ci.longhorn.io/job/private/job/image-security-scan/1397/#showFailuresLink): 33 HIGH, 0 CRITICAL

**Comment by c3y1huang** [comment]
No CSI component image requires update:
```
longhornio/csi-attacher:v4.4.2 (debian 11.8)
============================================
Total: 0 (HIGH: 0, CRITICAL: 0)

longhornio/csi-provisioner:v3.6.2 (debian 11.8)
===============================================
Total: 0 (HIGH: 0, CRITICAL: 0)

longhornio/csi-resizer:v1.9.2 (debian 11.8)
===========================================
Total: 0 (HIGH: 0, CRITICAL: 0)

longhornio/csi-snapshotter:v6.3.2 (debian 11.8)
===============================================
Total: 0 (HIGH: 0, CRITICAL: 0)

longhornio/csi-node-driver-registrar:v2.9.2 (debian 11.8)
=========================================================
Total: 0 (HIGH: 0, CRITICAL: 0)

longhornio/livenessprobe:v2.12.0 (debian 11.8)
==============================================
Total: 0 (HIGH: 0, CRITICAL: 0)
```

**Comment by c3y1huang** [comment]
The backing image manager does not require an update.
```
longhornio/backing-image-manager:v1.5.x-head (suse linux enterprise server 15.5)
================================================================================
Total: 0 (HIGH: 0, CRITICAL: 0)
```

**Comment by innobead** [comment]
Ideally renovate should automatically update the dependencies of maintained branches if there is any patch update. However it's set to run on the weekend only.

**Comment by c3y1huang** [comment]
Releasing support-bundle v0.0.37
... WIP

**Comment by derekbit** [comment]
@c3y1huang All are merged. 

cc @innobead  @longhorn/qa

**Comment by c3y1huang** [comment]
@longhorn/qa we need a full regression before closing this issue. Thank you!

**Comment by chriscchien** [comment]
Full regression with v1.5.x-head images test results listed in below and did not observe outstand issue, if there is no other concern, I would like to close this ticket, thank you.

Regression and Upgrade
- https://ci.longhorn.io/job/public/job/v1.5.x/job/v1.5.x-longhorn-tests-sles-amd64/377/ 1 flaky
- https://ci.longhorn.io/job/public/job/v1.5.x/job/v1.5.x-longhorn-tests-sles-arm64/372/ 1 flaky
- https://ci.longhorn.io/job/public/job/v1.5.x/job/v1.5.x-longhorn-upgrade-tests-sles-amd64/371/ 3 flaky
- https://ci.longhorn.io/job/public/job/v1.5.x/job/v1.5.x-longhorn-upgrade-tests-sles-arm64/368/: all passed

2 stage upgrade (AMD64 ARM64)
- https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6735/ - 1 flaky
- https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6736/ - 1 flaky

Security test: 25 HIGH, 0 CRITICAL ([v1.5.5-rc2 ](https://ci.longhorn.io/job/private/job/image-security-scan/1397/#showFailuresLink): 33 HIGH, 0 CRITICAL )
- https://ci.longhorn.io/job/private/job/image-security-scan/1403/#showFailuresLink

**Comment by chriscchien** [comment]
Verified **pass** with longhorn v1.5.x (longhorn `974236`)

Did not observe outstand issue in regression and the counts of security scan HIGH issue reduced(test [result](https://github.com/longhorn/longhorn/issues/8372#issuecomment-2065691231))
