### ISSUE TITLE
[BUG] Volume has multiple instance managers

### ISSUE THREAD

**Issue by codot-fr** [longhorn/longhorn#8374]
## Describe the bug

A volume is stuck with multiple instance manager registred. It is marked as healthy but not ready for workload.

![image](https://github.com/longhorn/longhorn/assets/39614999/ec685cc1-e05a-4e16-a73b-7636ce86bb16)

## Environment

 - Longhorn version: 1.4.3 (bundled with harvester 1.2.1)
 - Impacted volume (PV): pvc-3e779637-4ea1-4469-a304-4fd88c040c2a

**Comment by derekbit** [comment]
cc @ejweber @PhanLe1010

**Comment by derekbit** [comment]
Ref: https://github.com/longhorn/longhorn/issues/8197#issuecomment-2005116550

**Comment by derekbit** [comment]
cc @Vicente-Cheng as well
