### ISSUE TITLE
Allow the disk disappear from the host to be removed

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#838]
Version: v0.6.2-dev

Reproduce steps:
1. Add a new disk to a node of Longhorn
2. Unmount the disk from the node.
3. Try to delete the disk from Longhorn

Result:
1. Cannot disable the scheduling for the disk, warning in the log:
```
[longhorn-manager-mzhw7] time="2019-10-29T17:33:13Z" level=warning msg="Update disk on node yasker-longhorn-dev-2 warning: The disk /tmp/longhorn-test/vol-disk-1 has changed file system, please mount it back or remove it"
```
2. Cannot remove the disk since the scheduling cannot be disabled.

Expect result:
1. The disabling of scheduling should be allowed then the disk can be removed.

**Comment by yasker** [comment]
We only need to check the system now functions as described here.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
