### ISSUE TITLE
UI: Snapshot revert tree doesn't show vertical line

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#839]
<img width="1006" alt="Screen Shot 2019-10-29 at 1 13 30 PM" src="https://user-images.githubusercontent.com/3344618/67805279-ee5cdd80-fa4d-11e9-8b91-735b2f38e5f0.png">

**Comment by meldafrawi** [comment]
affected by #848

**Comment by meldafrawi** [comment]
Validation: **FAILED**

Steps to reproduce:
1. take 3 snapshots (**snap-1.1** , **snap-1.2**,  **snap-1.3**)
2. revert to snapshot **snap-1.2**
3. take 2 more snapshots (**snap-2.1** , **snap-2.2**)
4. revert to *snap-1.1*  (screenshot-1)
5. take few more snapshots (screenshot-2)

**screenshot-1**
![image](https://user-images.githubusercontent.com/18232258/68506296-01538700-0272-11ea-9493-802d6517ef00.png)


**screenshot-2**
![image](https://user-images.githubusercontent.com/18232258/68506409-42e43200-0272-11ea-8db7-ed6384ff46f4.png)

**Comment by meldafrawi** [comment]
Sorry, moved to review by mistake, 
Moved it back to implement.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
