### ISSUE TITLE
[BUG] Longhorn Helm uninstall times out.

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#8408]
## Describe the bug

Longhorn with backing images, Helm uninstall times out.

```console
> helm uninstall longhorn -n longhorn-system
Error: timed out waiting for the condition
```

## To Reproduce

1. Install Longhorn `v1.5.5` with Helm
2. Create a `BackingImage` from UI
3. Edit the setting `deleting-confirmation-flag` to be true
4. Uninstalling Longhorn using Helm

## Expected behavior

 Helm uninstall  should not time out.

## Support bundle for troubleshooting

[supportbundle_fde8003a-32ea-4211-9630-3f1b36ad70e5_2024-04-22T01-11-32Z.zip](https://github.com/longhorn/longhorn/files/15056670/supportbundle_fde8003a-32ea-4211-9630-3f1b36ad70e5_2024-04-22T01-11-32Z.zip)
[longhorn-uninstall-srxd4.log](https://github.com/longhorn/longhorn/files/15056671/longhorn-uninstall-srxd4.log)

## Environment

 - Longhorn version: v1.5.5
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.28.3+k3s1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: SLES 15SP5
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 0 

## Additional context

N/A

**Comment by derekbit** [comment]
cc @ChanYiLin

**Comment by yangchiu** [comment]
We lack uninstall related test cases from the very beginning. https://github.com/longhorn/longhorn/issues/4031 can be set as a priority.

**Comment by ChanYiLin** [comment]
From the uninstallation log
It seems the root cause was that it took too much deleting backuptarget
From `time="2024-04-22T01:05:42Z"` to `2024-04-22T01:13:53Z` which trigger the timeout (5 mins)

**Comment by ChanYiLin** [comment]
hmmm I think I found the root cause
The logic stays there for 5 year and so is the bug. This is a flaky issue

https://github.com/longhorn/longhorn-manager/blob/50acc8136199f5042afcf2b5b3c7285edb9b7820/controller/uninstall_controller.go#L274-L300

```
func (c *UninstallController) uninstall() error {
	if ready, err := c.managerReady(); err != nil {
		return err
	} else if ready {
		if waitForUpdate, err := c.deleteCRDs(); err != nil || waitForUpdate {
			return err
		}
	}

	// A race condition exists where manager may attempt to recreate certain
	// CRDs after their deletion. We must delete manager and do a final check
	// for CRDs, just in case.
	if waitForUpdate, err := c.deleteManager(); err != nil || waitForUpdate {
		return err
	}

	if waitForUpdate, err := c.deleteDriver(); err != nil || waitForUpdate {
		return err
	}

	// We set gracePeriod=0s because there is no possibility of graceful
	// cleanup without a running manager.
	gracePeriod = 0 * time.Second
	if waitForUpdate, err := c.deleteCRDs(); err != nil || waitForUpdate {
		return err
	}
```

- In `deleteCRDs` we delete the `BackupTarget` if it is found
- We return and wait for the next reconcile to see if the resource is truly deleted by checking `len(BackupTarget) == 0`
- We only start to delete manager when we make sure all the CRs are deleted.
- But there is a large chance that the BackupTarget just got recreated between two reconciliation

Just like the comment mentions
> 	// A race condition exists where manager may attempt to recreate certain
	// CRDs after their deletion. We must delete manager and do a final check
	// for CRDs, just in case.

But actually, the logic won't work
because if the BackupTarget gets recreated fast enough then 
there is no chance for the `uninstall()` function to execute `deleteManager()`. It will stuck in the `deleteCRDs()` forever until it happens to get `len(BackupTarget) == 0` "accidentally".

cc @innobead @derekbit @c3y1huang

**Comment by ChanYiLin** [comment]
We can move the `"BackupTarget CR deletion"` after the `"manager deletion"` 
The order would be like
1. deleteCRDs()
    a. unset the BackupTarget
    b. check BackupVolumes and Backups are all cleaned up
2. deleteManager()
3. delete BackupTarget

BackupTarget has no DeletionTimestamp handling, it can be deleted directly and no need to wait.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240508**

- longhorn master-head https://github.com/longhorn/longhorn/commit/8026d1a700e66f9254fad75ee1e39390a0172208
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/f7e2d5363978081477cfa6ee46436c0244a1482a

**The test steps**
https://github.com/longhorn/longhorn/issues/8408#issuecomment-2097796928

**Result Passed**
