### ISSUE TITLE
[BUG] Upgrades from v1.5.3 to v1.5.4 do not immediately set lastHealthyAt and lastFailedAt

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#8417]
## Describe the bug

When upgrading from `v1.5.3` to `v1.5.4`, we should set `lastHealthyAt` and `lastFailedAt` directly. However, a mistake in the upgrade logic causes this behavior to only trigger when upgrading from <= `v1.5.2`.

https://github.com/longhorn/longhorn-manager/blob/88074ee747e60d8edcd98072a793c8614d7bff86/upgrade/upgrade.go#L243-L252

The issue was not detected because longhorn-manager typically sets these fields during its normal course of operation (`lastHealthyAt` in particular is typically set very quickly, as soon as a replica is detected read/write in an engine).

This is probably a very minor issue, but in at least one cluster, it has led to log messages like the one below. This message was in no way related to the actual issue in the cluster, but it made debugging more confusing.

```
2024-04-18T08:51:08.958274593Z time="2024-04-18T08:51:08Z" level=error msg="Failed to verify if safe as last replica: cannot parse timestamp : parsing time \"\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"\" as \"2006\"" func=controller.isSafeAsLastReplica file="volume_controller.go:894" replica=<volume_name>-r-b26e6d75
```

## To Reproduce

1. Install Longhorn `v1.5.3`.
2. Create a volume.
3. Attach the volume.
4. Detach the volume (so its replicas aren't read/write in an engine during the upgrade).
5. Upgrade to Longhorn `v1.5.4`.
6. Notice that the replica `lastHealthyAt` fields are not set.

## Expected behavior

If the replica `healthyAt` and `failedAt` fields are set before an upgrade to `v1.5.4`, the corresponding `lastHealthyAt` and `lastFailedAt` should also be set.

**Comment by derekbit** [comment]
v1.5.x is EOL.
