### ISSUE TITLE
The feature have issue --- Longhorn Pod Deletion Policy When Node is Down

### ISSUE THREAD

**Issue by haiouc** [longhorn/longhorn#8418]
I created a k8s cluster(30 nodes) on openstack, and then install longhorn on it.

I had tested the feature "Longhorn Pod Deletion Policy When Node is Down" in Longhorn helm chart v1.6.0 / v1.6.1
I used the example for testing "kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml", 

NodeDownPodDeletionPolicy is set to do-nothing
```
#kubectl -n longhorn-system get setting node-down-pod-deletion-policy
NAME                                                 VALUE            AGE
node-down-pod-deletion-policy     do-nothing    17d
```

I powered off a node, it will create a new pod on another nodes.
The result is different from  document, please help to check.

```
[root@haiouc longhorn]# k get pod -o wide | grep web 
web-0      1/1     Running     0   3m26s   172.21.70.212   k8s-med-worker-6    <none>           <none>
web-1      1/1     Running     0   3m13s   172.21.7.213    k8s-med-worker-2    <none>           <none>

[root@haiouc longhorn]# k get pod -o wide | grep web 
web-0      1/1     Running       0     19m     172.21.70.212   k8s-med-worker-6    <none>           <none>
web-1      1/1     Running       0     7m47s   172.21.9.99     k8s-med-worker-3    <none>           <none>

```

```
#document
if NodeDownPodDeletionPolicy is set to do-nothing | delete-deployment-pod
#wait till the pod.deletionTimestamp has passed
#verify no replacement pod generated, the pod is stuck at terminating forever.
```

**Comment by mantissahz** [comment]
duplicate issue as https://github.com/longhorn/longhorn/issues/8275,
Would you mind updating the information on this ticket [8275](https://github.com/longhorn/longhorn/issues/8275)?

**Comment by haiouc** [comment]
@mantissahz  Which one to close, 8275? (close as not planned )

**Comment by mantissahz** [comment]
I prefer to close this one and update the status on #8275 
duplicated.
