### ISSUE TITLE
[FEATURE] v2 volume supports auto salvage 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8430]
## Additional context

Some discussions
https://suse.slack.com/archives/C02DR3N5T24/p1713926457976349

**Comment by DamiaSan** [comment]
See `data consistency` in https://github.com/longhorn/longhorn/pull/7031

**Comment by chriscchien** [comment]
Verified **pass** on longhorn v1.8.0-dev(https://github.com/longhorn/longhorn-manager/commit/a503949c751f8bb07d9835f3680b93d5bc807e30)

Test steps:

1. Dynamic provision a v2 volume, having data in the mount point.
2. Set `auto-salvage` to `false`
3. Force delete all v2 volume instance-manager pod.
4. V2 volume become faulted and remains in that state.
5. Set `auto-salvage` to `true`
6. The faulted v2 volume become healthy and data in the workload is correct.
7. Force delete all v2 volume instance-manager pod again.
8. V2 olume become faulted then healthy again.
9. After volume healthy, data in workload correct.

In v1.7.2, set `auto-salvage` to `true` and force delete all v2 volume instance-manager pod, the v2 volume will loop from faulted -> attaching -> faulted.
