### ISSUE TITLE
[BUG] could not get correct branch name from longhorn/spdk

### ISSUE THREAD

**Issue by a110605** [longhorn/longhorn#8432]
## Describe the bug
`Longhorn` branch could not be found when apply `longhorn-spdk-setup` yaml.

## To Reproduce

Follow [prerequisites](https://longhorn.io/docs/1.5.3/v2-data-engine/quick-start/#prerequisites) docs, applying `longhorn-spdk-setup` yaml should git clone correct setup script from https://github.com/longhorn/spdk/tree/longhorn-1.6.  
```
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.6.1/deploy/prerequisite/longhorn-spdk-setup.yaml
```

But got

`fatal: Remote branch longhorn not found in upstream origin. Failed to configure SPDK environment error code 1`

<img width="1147" alt="image" src="https://github.com/longhorn/longhorn/assets/5744158/9679e4b4-7f76-4376-b660-6b8ec7b33d71">

## Expected behavior

Should git clone script from spdk repo without any problem.

## Environment

 - Longhorn version: 1.6.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of control plane nodes in the cluster:  1
   - Number of worker nodes in the cluster: 1
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): digital ocean
 - Number of Longhorn volumes in the cluster: 0

**Comment by derekbit** [comment]
@a110605 I
