### ISSUE TITLE
[BUG] Can't list anymore on s3-compatible storage 1.4.3

### ISSUE THREAD

**Issue by simonebenati** [longhorn/longhorn#8435]
## Describe the bug

I encounter this error while I try to list the backup page 

`error listing backup volume names: timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.4.3/longhorn [backup ls --volume-only s3://evo-stage@default/backup-longhorn/], output , stderr, , error <nil>
`
## To Reproduce

Add an s3 compatible type of storage like ceph

## Expected behavior

I expect the to be able to list the backups in the backup page.

## Support bundle for troubleshooting

[supportbundle_0e2fe36f-873b-4027-bc13-635cc8f1d41c_2024-04-24T17-57-08Z.zip](https://github.com/longhorn/longhorn/files/15098535/supportbundle_0e2fe36f-873b-4027-bc13-635cc8f1d41c_2024-04-24T17-57-08Z.zip)

## Environment

 - Longhorn version: 1.4.3
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: rke2:1.26.11+rke2r1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: ubuntu22
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal
 - Number of Longhorn volumes in the cluster: 3

## Additional context

I am sure this function worked with our ceph cluster but also it's giving issues with an amazon s3 backed bucket.

**Comment by james-munson** [comment]
@mantissahz

**Comment by mantissahz** [comment]
Hi @simonebenati, 

Found the error log `dial tcp 84.240.179.99:443: connect: no route to
host` in the bundle:

```txt
"Error listing backup volumes from backup target" controller=longhorn-backup-target cred=s3-credentials error="error listing backup volume names: failed to ex
ecute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.4.3/longhorn [backup ls --volume-only s3://sicraweb-evo-stage@it-mi1/backup-longhorn/], output failed to list objects with param: {\n  Bucket: \"sicraweb-evo-stag
e\",\n  Delimiter: \"/\",\n  Prefix: \"backup-longhorn/\"\n} error: AWS Error:  RequestError send request failed Get \"https://s3.nivolapiemonte.it/sicraweb-evo-stage?delimiter=%!F(MISSING)&prefix=backup-longhorn%!F(MISSING)\": dial
tcp 84.240.179.99:443: connect: no route to host\n\n, stderr, time=\"2024-04-24T15:06:50Z\" level=error msg=\"Failed to list s3\" error=\"failed to list objects with param: {\\n  Bucket: \\\"sicraweb-evo-stage\\\",\\n  Delimiter: \\\
"/\\\",\\n  Prefix: \\\"backup-longhorn/\\\"\\n} error: AWS Error:  RequestError send request failed Get \\\"https://s3.nivolapiemonte.it/sicraweb-evo-stage?delimiter=%!F(MISSING)&prefix=backup-longhorn%!F(MISSING)\\\": dial tcp 84.2
40.179.99:443: connect: no route to host\\n\" pkg=s3\ntime=\"2024-04-24T15:06:50Z\" level=error msg=\"failed to list objects with param: {\\n  Bucket: \\\"sicraweb-evo-stage\\\",\\n  Delimiter: \\\"/\\\",\\n  Prefix: \\\"backup-longh
orn/\\\"\\n} error: AWS Error:  RequestError send request failed Get \\\"https://s3.nivolapiemonte.it/sicraweb-evo-stage?delimiter=%!F(MISSING)&prefix=backup-longhorn%!F(MISSING)\\\": dial tcp 84.240.179.99:443: connect: no route to
host\\n\"\n, error exit status 1" interval=5m0s node=database01-stage url="s3://sicraweb-evo-stage@it-mi1/backup-longhorn/"
```

Is your system behind the proxy or is it an air-gap system?
Could you show the content of the secret `s3-credentials` especially `AWS_ENDPOINTS `?
ref: https://longhorn.io/docs/1.7.0/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-a-local-testing-backupstore

**Comment by simonebenati** [comment]
Hello, this was the first error I encountered and then shortly after the provider opened the connection from our ip to their bucket.

If you scroll down around the 17/18 timestamp hour you'll notice the error i was discussing about.
If it helps, I am able to backup to s3 the configuration. so therefore the s3-credentials secret is working correctly. And I'm pretty sure of this because I've been using longhorn for months. And to this day I'm still able to backup but not list my backups anymore here's a screenshot from one of my many environments:

<img width="1578" alt="image" src="https://github.com/longhorn/longhorn/assets/102557087/773fec86-9de5-4057-af34-6fe6eb7f3a06"> these backups were taken exactly as it says 11h ago

**Comment by simonebenati** [comment]
<img width="1147" alt="image" src="https://github.com/longhorn/longhorn/assets/102557087/4afe1246-528d-4a9f-99ee-b52b7088c79b">

As you see even from here this is a different cluster from the previous screenshot. Backup taken 5h ago via recurring job but can't list anything anymore and neither backup manually..

**Comment by mantissahz** [comment]
Hi @simonebenati, 

Thanks for the updates.
Could you provide the latest support bundle that created the new backup manually and the listing backup volume is still timeout?
And Could you help log in the `longhorn-manager-bgcbq` pod and test the command?

```bash
## export AWS credentials corresponding to the secret `s3-credentials` and they should be clear texts not encoded in the secret.
export AWS_ACCESS_KEY_ID="xxxxx"
export AWS_SECRET_ACCESS_KEY="xxxxx"
export AWS_ENDPOINTS="xxxxx"
export AWS_CERT="xxxxx"
/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.4.3/longhorn backup ls --volume-only s3://sicraweb-evo-stage@default/backup-longhorn/
```

**Comment by derekbit** [comment]
TODO: add a troubleshooting page in Longhorn's official doc.
cc @mantissahz @innobead

**Comment by simonebenati** [comment]
Hi the only backup I'm manually able to perform is the longhorn configuration one:

<img width="1147" alt="image" src="https://github.com/longhorn/longhorn/assets/102557087/eeea2b67-ff70-425b-971d-9bd72e8130aa">

The manual backup on a volume is grayed out as shown in the above screenshots..

From the manager-bgcbq pod: ->

```
/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.4.3/longhorn backup ls --volume-only s3://sicraweb-evo-stage@it-mi1/backup-longhorn/
ERRO[0120] Failed to list s3                             error="failed to list objects with param: {\n  Bucket: \"sicraweb-evo-stage\",\n  Delimiter: \"/\",\n  Prefix: \"backup-longhorn/\"\n} error: AWS Error:  RequestError send request failed Get \"https://s3.endpoint.it/sicraweb-evo-stage?delimiter=%!F(MISSING)&prefix=backup-longhorn%!F(MISSING)\": dial tcp publicip443: i/o timeout\n" pkg=s3
ERRO[0120] failed to list objects with param: {
  Bucket: "sicraweb-evo-stage",
  Delimiter: "/",
  Prefix: "backup-longhorn/"
} error: AWS Error:  RequestError send request failed Get "https://s3.endpoint.it/sicraweb-evo-stage?delimiter=%!F(MISSING)&prefix=backup-longhorn%!F(MISSING)": dial tcp publicip:443: i/o timeout 
failed to list objects with param: {
  Bucket: "sicraweb-evo-stage",
  Delimiter: "/",
  Prefix: "backup-longhorn/"
} error: AWS Error:  RequestError send request failed Get "https://s3.endpoint.it/sicraweb-evo-stage?delimiter=%!F(MISSING)&prefix=backup-longhorn%!F(MISSING)": dial tcp publicip:443: i/o timeout
```

Also now the system configuration is failing:

<img width="1620" alt="image" src="https://github.com/longhorn/longhorn/assets/102557087/5467c2ec-3db8-4266-99d2-caaf8c4cd915">

Bundle:

[supportbundle_0e2fe36f-873b-4027-bc13-635cc8f1d41c_2024-04-25T11-11-34Z.zip](https://github.com/longhorn/longhorn/files/15108689/supportbundle_0e2fe36f-873b-4027-bc13-635cc8f1d41c_2024-04-25T11-11-34Z.zip) 

check around the 11th hour of 25-04 in the logs


p.s. i checked also in another environment and it fails like this environment:

<img width="1620" alt="image" src="https://github.com/longhorn/longhorn/assets/102557087/3930868f-69a9-4014-97fb-9dd42cbfb58d">

**Comment by simonebenati** [comment]
yeah s3.endpoint.it is translated to a public ip correctly:

i'll just paste the whole thing, for you and if you can please edit it out after you have it it'd be better..

```
dig s3.nivolapiemonte.it

; <<>> DiG 9.10.6 <<>> s3.nivolapiemonte.it
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47639
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;s3.nivolapiemonte.it.		IN	A

;; ANSWER SECTION:
s3.nivolapiemonte.it.	5643	IN	CNAME	s3.glb.nivolapiemonte.it.
s3.glb.nivolapiemonte.it. 60	IN	A	84.240.178.100
```

it's a s3-compatible server (also all our other environments are s3-compatible)
No it isn't a proxy, and no our environments don't use proxies.

**Comment by derekbit** [comment]
@simonebenati Is it resolved?

cc @mantissahz

**Comment by simonebenati** [comment]
Hello yes, it is resolved. It was an internal issue related to networking.
