### ISSUE TITLE
[IMPROVEMENT] Investigate performance bottleneck in v1 data path 

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#8436]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Investigate performance bottleneck in v1 data path. So far we have identified 2 bottlenecks:
1. Number of engine-replica connections
1. Revision counter inefficient logic

We are still investigating if there are more bottlenecks

## Describe the solution you'd like

Resolve the bottleneck and increase the performance of v1 data path 

## Additional Context:
This is the test result on equinix metal m3.small.x86, ubuntu 22.04, 5.15.0-101-generic:

<img src="https://github.com/longhorn/longhorn/assets/22139961/5840bcfc-4888-4d2f-a357-a9f115dba4cb" alt="Example Image" width="400">

<img src="https://github.com/longhorn/longhorn/assets/22139961/da5c1c01-711d-4720-80d4-5b4c0c851418" alt="Example Image" width="400">

<img src="https://github.com/longhorn/longhorn/assets/22139961/478178b0-89ab-4e37-9caf-36d3c15bef03" alt="Example Image" width="400">

**Comment by PhanLe1010** [comment]
This is potentially the 3rd bottleneck:
* For some reason, we always have to do an alignment for each read requests which means go through this code path https://github.com/longhorn/longhorn-engine/blob/be5e072e02cd959ab371a04264957624223b01fb/vendor/github.com/longhorn/sparse-tools/sparse/file.go#L120-L123
* This doesn't happen for the write request. I.e., write request doesn't have to go through this code path https://github.com/longhorn/longhorn-engine/blob/be5e072e02cd959ab371a04264957624223b01fb/vendor/github.com/longhorn/sparse-tools/sparse/file.go#L133-L136

cc @shuo-wu @ejweber @derekbit

**Comment by PhanLe1010** [comment]
> We already know the input data []byte needs to be aligned for direct IO.
Can we always allocate an aligned buffer for data in the caller end for preventing extra data copy in the two functions?

Agree with this idea. I will give it a try to see if it can improve the read speed

**Comment by PhanLe1010** [comment]
Side track a little bit. Do you think there is a danger with integer overflow when we keep increasing the counter over here https://github.com/longhorn/longhorn-engine/blob/be5e072e02cd959ab371a04264957624223b01fb/pkg/replica/revision_counter.go#L143 ?

If we keep  writing long enough, it might become nagative?

**Comment by derekbit** [comment]
> Side track a little bit. Do you think there is a danger with integer overflow when we keep increasing the counter over here https://github.com/longhorn/longhorn-engine/blob/be5e072e02cd959ab371a04264957624223b01fb/pkg/replica/revision_counter.go#L143 ?
> 
> If we keep writing long enough, it might become negative

It is `int64`. Probably no danger?

**Comment by PhanLe1010** [comment]
> It is int64. Probably no danger?

you are right, if we are writing with speed 50k IOPs, it would take 5849424 years to go overflow. None of us can see that day :)))

**Comment by PhanLe1010** [comment]
Update:  a tiny small improvement to the revision counter logic

#### Current implementation
We are converting the int64 to a string then a slice of bytes https://github.com/longhorn/longhorn-engine/blob/be5e072e02cd959ab371a04264957624223b01fb/pkg/replica/revision_counter.go#L45-L46

The `strconv.FormatInt` function seems to eat noticeable CPU time in profiling 

#### Modification:
Using LittleEndian to encode and decode the int64:
```go
func (r *Replica) writeRevisionCounter(counter int64) error {
	if r.revisionFile == nil {
		return fmt.Errorf("BUG: revision file wasn't initialized")
	}

	copy(revisionCounterBuf, int64ToBytes(counter))
	_, err := r.revisionFile.WriteAt(revisionCounterBuf, 0)
	if err != nil {
		return errors.Wrap(err, "failed to write to revision counter file")
	}
	return nil
}

func int64ToBytes(n int64) []byte {
	bytes := make([]byte, 8)
	binary.LittleEndian.PutUint64(bytes, uint64(n))
	return bytes
}

func bytesToInt64(bytes []byte) int64 {
	return int64(binary.LittleEndian.Uint64(bytes))
}
```

#### Result 
A small improvement in the write performance maybe 1-2%.
However, the implementation cost is big: we need to migrate and update from old decoding to new decoding. 
I think this is not a good idea

**Comment by PhanLe1010** [comment]
> > We already know the input data []byte needs to be aligned for direct IO.
> > Can we always allocate an aligned buffer for data in the caller end for preventing extra data copy in the two functions?
> 
> Agree with this idea. I will give it a try to see if it can improve the read speed

Looks like the performance gets worse. So we will not do this:
```
IOPS (Read/Write)
        Random:          45,395 / 19,553
    Sequential:          62,778 / 33,106

Bandwidth in KiB/sec (Read/Write)
        Random:        714,421 / 348,190
    Sequential:        976,918 / 353,571
                                        

Latency in ns (Read/Write)
        Random:        821,898 / 455,709
    Sequential:        814,332 / 456,455

```

**Comment by PhanLe1010** [comment]
@shuo-wu This is the CPU usage of `strconv.FormatInt` that we were talking about in the sync up. It is small but noticeable
 
![Screenshot from 2024-04-25 12-25-24](https://github.com/longhorn/longhorn/assets/22139961/2fd10860-e35d-4a51-ae82-e34c1cac0129)

**Comment by PhanLe1010** [comment]
As dissed with @shuo-wu in the sync up. We rerun some of the Broadcom tests. The setup is the same setup in our initial Broadcom report in SUSE data center 

Case 1: In a CPU/RAM limited constraints
1. Random read IOPs test
    * IOPs: similar 
    * CPU usage: similar 
1. Sequential read IOPs test
    * IOPs: Testing 
    * CPU usage: Testing 
1. Random write IOPs test
    * IOPs: Testing 
    * CPU usage: Testing 
1. Sequential write IOPs test
    * IOPs: Testing 
    * CPU usage: Testing 

Case 2: In no CPU/RAM constraint
1. Random read IOPs test
    * IOPs: Testing 
    * CPU usage: Testing 
1. Sequential read IOPs test
    * IOPs: Testing 
    * CPU usage: Testing 
1. Random write IOPs test
    * IOPs: Testing 
    * CPU usage: Testing 
1. Sequential write IOPs test
    * IOPs: Testing 
    * CPU usage: Testing

**Comment by PhanLe1010** [comment]
Btw, this article is very helpful in understand a common mistake in go concurrency https://eli.thegreenplace.net/2019/go-internals-capturing-loop-variables-in-closures/

**Comment by PhanLe1010** [comment]
Update: 

There is potentially another bottleneck in the read flow in the replica. For every read, we have to make a systemcall `os.(*File).Stat` to get the size of the snaoshot file [here](https://github.com/longhorn/longhorn-engine/blob/be5e072e02cd959ab371a04264957624223b01fb/pkg/replica/diff_disk.go#L232). This systemcall is eating noticeable CPU. Do you think we can cache this snapshot size value and don't have to issue a systemcall for every read? @shuo-wu @derekbit @ejweber 

![image](https://github.com/longhorn/longhorn/assets/22139961/f89a579f-1bde-4b5a-ae30-7d3e204827b8)

**Comment by shuo-wu** [comment]
> For every read, we have to make a systemcall os.(*File).Stat to get the size of the snaoshot file [here](https://github.com/longhorn/longhorn-engine/blob/be5e072e02cd959ab371a04264957624223b01fb/pkg/replica/diff_disk.go#L232).

Good catch! I am fine with using the cached size. The snapshot immutability should be guaranteed by the ctime/checksum mechanism

**Comment by PhanLe1010** [comment]
After testing, the snapshot file caching idea doesn't seem to improve performance in practice even though sounds good in theory. CPU usage is also relatively the same. Let's abandon it. Sorry for the noise.

**Comment by PhanLe1010** [comment]
Do you think we should backport this to v1.6.x and v1.5.x? @shuo-wu @ejweber @derekbit

**Comment by ejweber** [comment]
> Do you think we should backport this to v1.6.x and v1.5.x? @shuo-wu @ejweber @derekbit

I don't think there is much danger here, especially around compatibility, as the changes are all self-contained within the engine. On the other hand, connection count will increase (and possible CPU utilization as well) as a tradeoff for the performance. Maybe that's surprising in a patch update?

I lean slightly towards backporting, but I'm also fine with the gains being associated with a new minor version of Longhorn. I'll defer to whatever you decide.

**Comment by PhanLe1010** [comment]
Test Plan:
1. Create a cluster of 3 worker nodes with similar big spec like `equinix metal m3.small.x86, ubuntu 22.04, 5.15.0-101-generic, 20Gbps network`
2.  deploy Longhorn 1.6.1
3. Run kbench 
4. Upgrade Longhorn to master-head and upgrade the engine to master-head
5. Run Kbench again
6. Verify the you see better IOPs result
7. See the issue description for example

**Comment by roger-ryao** [comment]
**Verified on master-head 20240508**

- longhorn master-head https://github.com/longhorn/longhorn/commit/8026d1a700e66f9254fad75ee1e39390a0172208
- longhorn-engine master-head https://github.com/longhorn/longhorn-engine/commit/

**The test steps**
https://github.com/longhorn/longhorn/issues/8436#issuecomment-2098977274

**Result Passed**

1. In the AWS EC2 t2.xlarge environment, I did not observe significant differences in IOPS. 
    Therefore, I have decided to build up a cluster in a local virtual machine to conduct this test. 
    The test result is as follows.

**v1.6.1**
```console
=========================
FIO Benchmark Summary
For: test_device
CPU Idleness Profiling: disabled
Size: 30G
Quick Mode: disabled
=========================
IOPS (Read/Write)
        Random:           10,329 / 4,684
    Sequential:          17,677 / 10,204

Bandwidth in KiB/sec (Read/Write)
        Random:        413,252 / 141,958
    Sequential:        461,723 / 170,358
                                        

Latency in ns (Read/Write)
        Random:        431,773 / 553,568
    Sequential:        357,682 / 547,949
```

**master-head**

```console
=========================
FIO Benchmark Summary
For: test_device
CPU Idleness Profiling: disabled
Size: 30G
Quick Mode: disabled
=========================
IOPS (Read/Write)
        Random:           11,024 / 5,082
    Sequential:          18,149 / 10,672

Bandwidth in KiB/sec (Read/Write)
        Random:        415,402 / 137,600
    Sequential:        445,611 / 167,325
                                        

Latency in ns (Read/Write)
        Random:        409,800 / 525,464
    Sequential:        342,326 / 525,112
```

**Here is the summary table**

|                   | IOPS (Random Read/Write) | IOPS (Sequential Read/Write) |
|-------------------|--------------------------|-------------------------------|
| v1.6.1-1st             | 10,329 / 4,684           | 17,677 / 10,204               |
| master-head-1st          | 11,024 / 5,082           | 18,149 / 10,672               |

|                   | Bandwidth KiB/sec (Random Read/Write) | Bandwidth KiB/sec (Sequential Read/Write) |
|-------------------|----------------------------------------|--------------------------------------------|
| v1.6.1-1st             | 413,252 / 141,958                      | 461,723 / 170,358                         |
| master-head-1st          | 415,402 / 137,600                      | 445,611 / 167,325                         |

|                   | Latency ns (Random Read/Write) | Latency ns (Sequential Read/Write) |
|-------------------|--------------------------------|-------------------------------------|
| v1.6.1-1st             | 431,773 / 553,568              | 357,682 / 547,949                   |
| master-head-1st          | 409,800 / 525,464              | 342,326 / 525,112                   |

Hi @PhanLe1010 
    I think we can close this ticket. If there are any concerns regarding the test results, please let me know.

**Comment by innobead** [comment]
ref: https://github.com/longhorn/longhorn/issues/8563, disabling RC by default is also part of this issue.
