### ISSUE TITLE
controller: Move LastBackup/LastBackupAt update into the volume controller

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#844]
Volume controller should responsible for the volume status change.

**Comment by yasker** [comment]
Would be a part of https://github.com/longhorn/longhorn/issues/304

**Comment by jenting** [comment]
It changes updating the volume status LastBackup/LastBackupAt from HTTP API level to volume_controller, so no need QAs to manually verify this.
The automation integration test covers it already https://github.com/longhorn/longhorn-tests/blob/a059f0a/manager/integration/tests/common.py#L354.

Close it.
