### ISSUE TITLE
[DOC] Add uninstall and upgrade doc for GitOps solutions

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#8441]
## What's the document you plan to update? Why? Please describe

Currently, we only have installation doc for GitOps solutions we supported including flex, argocd, and fleet. Need to improve the doc to include uninstallation and upgrade, which are frequently asked.

**Comment by yangchiu** [comment]
https://github.com/longhorn/website/pull/902 https://github.com/longhorn/website/pull/888
