### ISSUE TITLE
[TASK] Remove v2 volume offline rebuilding in Longhorn v1.7

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8442]
## What's the task? Please describe

After discussing with @shuo-wu , there are some changes in the rebuilding related SPDK APIs. To make the integration of delta rebuilding simpler, we will remove v2 volume offline rebuilding in v1.7.0.

Offline rebuilding is still useful for some scenarios. We can add it back after settling down the design and the implementation of delta rebuilding.

**Comment by derekbit** [comment]
cc @shuo-wu @DamiaSan

**Comment by innobead** [comment]
Let's have another issue for adding offline rebuilding back and add it to 1.8.0.

**Comment by DamiaSan** [comment]
> To make the integration of delta rebuilding simpler, we will remove v2 volume offline rebuilding in v1.7.0.

Do you mean _online rebuilding_ instead _delta rebuilding_?

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `ad7420`) with test [steps](https://github.com/longhorn/longhorn/issues/8442#issuecomment-2078597019) - did not see outstanding issue from daily regression.
