### ISSUE TITLE
[CI] Remove the Broken Link Check workflow for website

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#8446]
## What's the CI task to develop? Please describe

Remove the "Broken Link Check" workflow for https://github.com/longhorn/website.

## Describe the items of the task development (DoD, definition of done) you'd like

Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] Confirm with team members that the workflow is not useful.
- [ ] Remove the workflow.

## Additional context

The "Broken Link Check" workflow has failed regularly for the past week. Is has failed for two different reasons:

- It detected "broken" links that are actually just slight redirects of working links. In https://github.com/longhorn/website/actions/runs/8824959597, it detected https://resources.github.com/devops/fundamentals/devsecops and https://resources.github.com/learn/pathways as broken. On further inspection in the output, these are actually just redirects of https://resources.github.com/devops/fundamentals/devsecops/ and https://resources.github.com/learn/pathways/ (with the added /). We don't actually have any ability to change these links as:
  - They exist somewhere in the GitHub interface, completely outside of our control.
  - I can't actually find them even when viewing the page source. Maybe they are detected recursively?
- It made too many requests to GitHub (as in https://github.com/longhorn/website/actions/runs/8669392214/job/23776053004).

The workflow was add in https://github.com/longhorn/website/pull/99 with reference to an issue we can no longer access. I originally thought it search http://longhorn.io for broken links, but instead it appears to search https://github.com/longhorn/website. This doesn't seem to be particularly useful to me. WDYT?

**Comment by james-munson** [comment]
And it spams similarly on private forks.

**Comment by ejweber** [comment]
I forgot to mention that its repo is read-only since November 30, 2022.

https://github.com/technote-space/broken-link-checker-action/tree/main

**Comment by ejweber** [comment]
> And it spams similarly on private forks. Understanding the motivation for the check, which has been handy sometimes, is there a better version of the link checker tool?

Can you elaborate @james-munson? I think it would make sense to check https://longhorn.io for broken links, but I'm not sure I understand why we check https://github.com/longhorn/website. It looks like [we could have configured it](https://github.com/technote-space/broken-link-checker-action/tree/main?tab=readme-ov-file#options) to point to the former instead if that was intended.

**Comment by innobead** [comment]
Sounds good to me.
