### ISSUE TITLE
Upgrade CRDs from `longhorn.rancher.io/v1alpha1` to `longhorn.io/v1beta1`

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#845]
Need to upgrade the old CRDs for v0.6.2 to v0.7.0.

- [x] v.Status.RestoreInitated need to be set to true for v1alpha1 by default
- [x] Change finalizer from `longhorn.rancher.io` to `longhorn.io`

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Test volume created by kubernetes on the old longhorn works on new longhorn, also you can create and use new volumes by kubernetes in new longhorn.
