### ISSUE TITLE
[BUG] instance-manager is stuck at starting state

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8455]
## Describe the bug

instance-manager is stuck at starting state due to the connection timeout

```
E0427 04:07:26.116782       1 instance_manager_controller.go:268] failed to sync instance manager for longhorn-system/instance-manager-3fa84f895e631b8f7e2f830d7ae820c6: failed to check Instance Manager Process Manager Service Client connection for instance-manager-3fa84f895e631b8f7e2f830d7ae820c6 IP 10.42.1.18: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 10.42.1.18:8500: i/o timeout"
time="2024-04-27T04:07:26Z" level=error msg="Dropping Longhorn instance manager out of the queue" func=controller.handleReconcileErrorLogging file="utils.go:67" InstanceManager=longhorn-system/instance-manager-3fa84f895e631b8f7e2f830d7ae820c6 controller=longhorn-instance-manager error="failed to sync instance manager for longhorn-system/instance-manager-3fa84f895e631b8f7e2f830d7ae820c6: failed to check Instance Manager Process Manager Service Client connection for instance-manager-3fa84f895e631b8f7e2f830d7ae820c6 IP 10.42.1.18: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 10.42.1.18:8500: i/o timeout\"" node=rancher60-worker1
```

It is a regression caused by https://github.com/longhorn/longhorn-instance-manager/pull/478/files#diff-be5264f89ae1624f664256427f500d03075146ca25b4dc701366589a225e7e9b

## To Reproduce

1. Create a Longhorn master-head cluster
2. instance-managers are stuck at starting statt

## Expected behavior

instance-managers should become running

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
cc @FrankYang0529

**Comment by chriscchien** [comment]
Verifed **pass** on longhorn master (longhorn-instance-manager `790d82`)

Instance manager pod all running and daily regression running well
```bash
> k get pods -A | grep instance-manager
longhorn-system       instance-manager-036817c465ec0392ad5f7492024d4bd3       1/1     Running     0               3h7m
longhorn-system       instance-manager-ec2c553d397920913e16c40187f97b48       1/1     Running     0               3h7m
longhorn-system       instance-manager-ee45a31b18d1b3086efa5b77a6e35e43       1/1     Running     0               164m
```
