### ISSUE TITLE
[IMPROVEMENT] Do not start any instance-manager pods for the v2 data engine on a node if one is already running

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8456]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

This is an improvement as well as a subtask of longhorn#6001.

Do not start any instance-manager pods for the v2 data engine on a node if one is already running because:
- Block-type disks are exclusively managed by a single instance-manager pod (specifically, spdk_tgt).
- A running instance-manager pod requires 2 GiB of huge pages. Additional pods cannot be launched due to the lack of available huge pages.

**Comment by innobead** [comment]
This behavior should be documented as it's different from v1 IM pods which are allowed to have more than one running.

**Comment by derekbit** [comment]
> This behavior should be documented as it's different from v1 IM pods which are allowed to have more than one running.

We will update the different behaviors in https://github.com/longhorn/longhorn/issues/7624

**Comment by roger-ryao** [comment]
**Verified on master-head 20240703**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/c3e1f66bd67f5eeec837a5ee6522ac17391031ff
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/369be1a74cafa9fd84492ca30507ff81df0906f9


**The test steps**

1. Fresh install Longhorn `v1.6.2`
2. Create V2 volume and pod with v2 volume
3. Check the instance-manager pod status
4. `v1.6.2` upgrade to `master-head`
5. After upgrade to `master-head`, Check the instance-manager pod status
6. the v2 instance-manager pod should not be create on the `master-head`

**Result Passed**

1. After upgrading the longhorn from `v1.6.2` to `master-head`, the `master-head`'s v2 instance-manager pod was not created 
2. If I delete the pod and wait for the volume to detach, the `v1.6.2`'s v2 instance-manager pod will be Terminated, and the `master-head`'s v2 instance-manager pod will be created
