### ISSUE TITLE
[IMPROVEMENT] Record instance-manager name for a block disksin `node.spec.diskStatus`

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8458]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

This is an improvement as well as a subtask of https://github.com/longhorn/longhorn/issues/6001.

For a block-type disk, which is managed by an instance-manager pod (specifically, the spdk_tgt component), the proposed improvement is to record the name of the instance-manager pod that is currently managing the disk in the `node.spec.diskStatus[i].instanceManagerName` field. This information will help identify which instance-manager pod is responsible for a particular disk and determine if the disk is already is transferred to a new instance-manager during upgrade.

For a filesystem-type disk, the `node.spec.diskStatus[i].instanceManagerName` field is left empty because this type of disk is not exclusively managed by any instance-manager.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn-manger (`00a3b8`) with [steps](https://github.com/longhorn/longhorn/issues/8458#issuecomment-2081533898)

In `nodes.longhorn.io`,  `diskStatus.instanceManagerName` will will be represented by the correspond instance-manager name
