### ISSUE TITLE
[IMPROVEMENT] Fall back to a running instance-manager if a default is not available

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8464]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

This is an improvement as well as a subtask of https://github.com/longhorn/longhorn/issues/6001.

Some operations in controllers, such as deleting disks and reconciling backup targets, initially fetch the default instance-manager. However, these operations are not restricted to the default instance-manager; they can use any running instance-manager. To enhance resilience, if the default instance-manager is unable to start before an upgrade of the v2 data engine or for any other reason, the controller can switch to any running instance-manager as a fallback.

**Comment by innobead** [comment]
This should be specific to the v2 data engine. Added the v2 label.

**Comment by derekbit** [comment]
> This should be specific to the v2 data engine. Added the v2 label.

It is more for v2 data engine, but it can also be applied to v1 data engine.

**Comment by innobead** [comment]
I see. Removed the v2 label, since we want to do it for both.

**Comment by innobead** [comment]
This seems to involve v2. @derekbit see if you would like to backport this to 1.6 and 1.5.

**Comment by derekbit** [comment]
@innobead I think we don't need to backport to v1.6.2. It is more related to v2 upgrade.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `ebace7`)

Using longhorn-instance-manager `846c2f` build test image and perform test [steps](https://github.com/longhorn/longhorn/issues/8464#issuecomment-2081910997), old instance-managers running well and create backup of v2 volume success.
