### ISSUE TITLE
[IMPROVEMENT] Only sync log settings to running instance manager pod

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8466]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

No need to sync log settings to non-running instance manager pod for avoiding flooding warning messages.

**Comment by derekbit** [comment]
@innobead 
No need to backport to 1.5.6 and 1.6.2. This is a new functionality in v1.7.

**Comment by innobead** [comment]
@derekbit is it based on https://github.com/longhorn/longhorn/issues/7939? 7939 has no milestone assigned.

**Comment by derekbit** [comment]
> @derekbit is it based on #7939? 7939 has no milestone assigned.

Yes, based #7939

**Comment by derekbit** [comment]
This improvement and fix can be tested in https://github.com/longhorn/longhorn/issues/7939 together.

**Comment by innobead** [comment]
I thought this log setting was already in 1.6.0.. bad memory.

**Comment by derekbit** [comment]
> I thought this log setting was already in 1.6.0.. bad memory.

IIRC, there is a general log-level setting for longhorn-manager.
https://github.com/longhorn/longhorn/blob/v1.6.x/chart/values.yaml#L297
