### ISSUE TITLE
Strategy for archived versions

### ISSUE THREAD

**Issue by jhkrug** [longhorn/longhorn#8470]
Longhorn has many archived versions. How to manage these within Docusaurus? Perhaps to try avoid building them, and just reference a link in a Netlify build that previous contained them?

**Comment by derekbit** [comment]
What's the rebuilding time for an archived version?

**Comment by derekbit** [comment]
cc @innobead

**Comment by PhanLe1010** [comment]
Perhaps we should rebuild in Docusaurus because we will have more archived versions in the future when there are more EOL version. Figureout how to build in Docusaurus may save work in future? 

Do you know what is the blocker for rebuilding archived versions in Docusaurus?
