### ISSUE TITLE
[FEATURE] Backup supports retention days

### ISSUE THREAD

**Issue by ammirator-administrator** [longhorn/longhorn#8475]
I did read the documentation but didn't found a mention about this feature (If even this exists)
I have a backup job, which creates the backups and everything is fine
But what I'm interested in is if there is a way to retain only lets say 10 backups, this way If I do a backup every day then in the s3 storage I always will have only last 10 backups for last 10 days not for the whole period

Is that something possible and built in longhorn or we should implement this manually?

**Comment by derekbit** [comment]
Just did a quick survey. Most backup products offer support for setting retention days. It may be beneficial for Longhorn to include this feature. WDYT @c3y1huang @ChanYiLin @innobead 

Before supporting the feature, you set the retention number in terms of the retention days.

**Comment by ammirator-administrator** [comment]
@derekbit 
On the recurring jobs I see a option `retain`

If I have a job type `backup` and retain 10 will that mean that it will keep lat 10 backups and delete the older ones??

cc. @c3y1huang @ChanYiLin @innobead

**Comment by derekbit** [comment]
> @derekbit On the recurring jobs I see a option `retain`
> 
> If I have a job type `backup` and retain 10 will that mean that it will keep lat 10 backups and delete the older ones??
> 
> cc. @c3y1huang @ChanYiLin @innobead

Yes, but it is different than your request for the `retention days`. Or, are you fine with retention number?

**Comment by ammirator-administrator** [comment]
yes in my case this should be enough
Since I will run the job every day no more just once a day and with retention 10 it should mean that I will keep only last 10 from last 10 days

If running it offten like 2 times a day the yes `retention days is needed`
But so far from what I understand the current implimentation should fit my needs 

Thanks

**Comment by derekbit** [comment]
Close. Let's collect more feedback from users.
