### ISSUE TITLE
UI: Take Snapshot button is disabled for attached volumes

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#848]
**UI Version:** `ef2757ab`

Steps to reproduce:
  - Deploy Longhorn components from  `master` images
   `https://github.com/longhorn/longhorn-manager/tree/master/deploy/install`
  - Create a volume
  - Attach volume to node
  - In volume details page, `Take Snapshot` button is disabled.

![image](https://user-images.githubusercontent.com/18232258/68052032-70b8fc00-fcf1-11e9-92f5-5dfc27404706.png)

**Comment by yasker** [comment]
In the backend, we've removed `MigrationNodeID` field. Not sure if it's related.

**Comment by yasker** [comment]
Seems GitHub bugged out. The commit has been merged.

**Comment by yasker** [comment]
Seems GitHub bugged out. The commit has been merged.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
