### ISSUE TITLE
snapshotMaxCount should support a smaller nr than 2

### ISSUE THREAD

**Issue by ammirator-administrator** [longhorn/longhorn#8480]
I do not understand why snapshotMaxCount is minimum 2 for normal usage and why 1 is not acceptable in case you use a s3 target for backups

Let's say I have a database with 10 TB of data.. to create a backup I need 20TB of data on same node because 10 TB at this point will get the snapshot and that is still ok but when trying to create the second backup then I cant because nodes with 30TB usually you cant buy :) not even in aws there 16 TB is maximum for a volume... now because of this setting the recurring backups cant be used properly because it wont be possible to create the snapshot

So I consider this as a bug mostly to not be able to set the max snapshots to 1, I don't see why 1 is not allowed and why we have to keep old snapshots if we still upload them to s3??
Can someone explain?
Also is there a option to auto remove snapshot after it was uploaded to s3 and keep the number to 0? as I understand if I set it to 0 it just uses the max allowed value

Or my understanding of backups is not correct and in s3 is uploaded only the config files and not the volumes data itself??

**Comment by PhanLe1010** [comment]
In Longhorn design, it cannot delete the snapshot right next to volume-head. Therefore there must be minimum 2 snapshots for Longhorn to be able to delete the oldest snapshot. If we allow the snapshotMaxCount to be set to 1, we will not be able to create more than 1 snapshot which lead to the issue that we will also not be able to cleanup any snapshot.

> Let's say I have a database with 10 TB of data.. to create a backup I need 20TB of data on same node because 10 TB at this point will get the snapshot and that is still ok but when trying to create the second backup then I cant because nodes with 30TB usually you cant buy :) not even in aws there 16 TB is maximum for a volume... now because of this setting the recurring backups cant be used properly because it wont be possible to create the snapshot


When you creat a new snapshot, it does not require 10TB immediately. It is a sparse file and will have 0 byte initially. This allow you to do cleanup before it is full


> Also is there a option to auto remove snapshot after it was uploaded to s3 and keep the number to 0? as I understand if I set it to 0 it just uses the max allowed value

Which Longhorn version are you using, In latest Longhorn version, Longhorn will automatically delete and only keep 1 snapshot for recurring backup job: https://longhorn.io/docs/1.6.1/references/settings/#automatically-clean-up-outdated-snapshots-of-recurring-backup-jobs. You can read about recurring backup job at https://longhorn.io/docs/1.6.1/snapshots-and-backups/scheduling-backups-and-snapshots/

**Comment by ammirator-administrator** [comment]
Thanks @PhanLe1010 
Yes I already added the automatically delete snapshots after recurring job option
Thanks for your answer

**Comment by ammirator-administrator** [comment]
@PhanLe1010 
I do have one more question
Why a snapshot needs to be created at all, why not to use Streams and upload to s3 direcltly using multipart

This way no space at all will be taken from the machine for backups, I still do not uderstand why to make a backup you need at least double the space on the machine as the database size for example

**Comment by PhanLe1010** [comment]
> I do have one more question Why a snapshot needs to be created at all, why not to use Streams and upload to s3 direcltly using multipart
> 
> This way no space at all will be taken from the machine for backups, I still do not uderstand why to make a backup you need at least double the space on the machine as the database size for example

Longhorn operate at the block device level. When Longhorn take a backup it needs to create a new snapshot instead of uploading the volume-head directly. If Longhorn upload the volume-head directly while workload is still read/write to it, the backup will be inconsistent
