### ISSUE TITLE
[UI][FEATURE] Add Fields to Backing Image Creation and Update

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#8485]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

With this feature: https://github.com/longhorn/longhorn/issues/2856
BackingImage now support following new fields
- `MinNumberOfCopies`
- `DiskSelector`
- `NodeSelector`

## Describe the solution you'd like

1. User can fill in these fields when creating BackingImage
2. User can update the `MinNumberOfCopies` after creation

update `MinNumberOfCopies` API
```
HTTP/1.1 POST /v1/backingimages/parrot?action=updateMinNumberOfCopies
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Content-Length: 23

{
"minNumberOfCopies": 2,
}
```

## Describe sub tasks
- [x] add minNumberOfCopies / DiskSelector / NodeSelector in creating backing image modal
- [x] allow edit backing image minNumberOfCopies 
- [x] show minNumberOfCopies / DiskSelector / NodeSelector in backing image table
- [x] allow search for minNumberOfCopies / DiskSelector / NodeSelector in filter

**Comment by ChanYiLin** [comment]
Hi @a110605 
Just discuss with me for more details or if you have any question, thanks!

**Comment by a110605** [comment]
> Hi @a110605 Just discuss with me for more details or if you have any question, thanks!

Sure, I will consult to you once I start this ticket.

**Comment by derekbit** [comment]
@a110605 Please update the checklist and the status if it is ready or testing. Thank you.

**Comment by a110605** [comment]
> @a110605 Please update the checklist and the status if it is ready or testing. Thank you.

Updated

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-ui `2079df`) with test [steps](https://github.com/longhorn/longhorn/issues/8485#issuecomment-2210287431)

From UI, I can create backing image with `minNumberOfCopies` / `DiskSelector` / `NodeSelector` set.
And I can clean backing file on disk throufh UI if current file counts it greater than `minNumberOfCopies
