### ISSUE TITLE
[BUG] Longhorn can no longer create XFS volumes smaller than 300 MiB

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#8488]
## Describe the bug

test_csi.text_xfs_pv has failed in the [last eight builds](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/test_results_analyzer/).

Analyzing a failure that occurred in a private build, I see the following logs:

```
2024-05-01T22:11:11.441646508Z I0501 22:11:11.441532   14424 mount_linux.go:515] Disk "/dev/longhorn/longhorn-testvol-pgbaei" appears to be unformatted, attempting to format as type: "xfs" with options: [-f /dev/longhorn/longhorn-testvol-pgbaei]
2024-05-01T22:11:11.447402309Z E0501 22:11:11.447331   14424 mount_linux.go:522] format of disk "/dev/longhorn/longhorn-testvol-pgbaei" failed: type:("xfs") target:("/var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/c3fd6a649dc2c88fa6601a1a3c588aee2df8ddf83570e66ea6b6298e6bbb330c/globalmount") options:("defaults") errcode:(exit status 1) output:(Filesystem must be larger than 300MB.
2024-05-01T22:11:11.447415856Z Usage: mkfs.xfs
2024-05-01T22:11:11.447419962Z /* blocksize */		[-b size=num]
2024-05-01T22:11:11.447423394Z /* config file */	[-c options=xxx]
2024-05-01T22:11:11.447427637Z /* metadata */		[-m crc=0|1,finobt=0|1,uuid=xxx,rmapbt=0|1,reflink=0|1,
2024-05-01T22:11:11.447431005Z 			    inobtcount=0|1,bigtime=0|1]
2024-05-01T22:11:11.447434335Z /* data subvol */	[-d agcount=n,agsize=n,file,name=xxx,size=num,
2024-05-01T22:11:11.447437392Z 			    (sunit=value,swidth=value|su=num,sw=num|noalign),
2024-05-01T22:11:11.447440836Z 			    sectsize=num
2024-05-01T22:11:11.447444000Z /* force overwrite */	[-f]
2024-05-01T22:11:11.447447161Z /* inode size */	[-i perblock=n|size=num,maxpct=n,attr=0|1|2,
2024-05-01T22:11:11.447450245Z 			    projid32bit=0|1,sparse=0|1,nrext64=0|1]
2024-05-01T22:11:11.447453251Z /* no discard */	[-K]
2024-05-01T22:11:11.447456349Z /* log subvol */	[-l agnum=n,internal,size=num,logdev=xxx,version=n
2024-05-01T22:11:11.447459462Z 			    sunit=value|su=num,sectsize=num,lazy-count=0|1]
2024-05-01T22:11:11.447462499Z /* label */		[-L label (maximum 12 characters)]
2024-05-01T22:11:11.447465614Z /* naming */		[-n size=num,version=2|ci,ftype=0|1]
2024-05-01T22:11:11.447468774Z /* no-op info only */	[-N]
2024-05-01T22:11:11.447487309Z /* prototype file */	[-p fname]
2024-05-01T22:11:11.447490710Z /* quiet */		[-q]
2024-05-01T22:11:11.447493909Z /* realtime subvol */	[-r extsize=num,size=num,rtdev=xxx]
2024-05-01T22:11:11.447496940Z /* sectorsize */	[-s size=num]
2024-05-01T22:11:11.447500085Z /* version */		[-V]
2024-05-01T22:11:11.447503183Z 			devicename
2024-05-01T22:11:11.447506280Z <devicename> is required unless -d name=xxx is given.
2024-05-01T22:11:11.447509595Z <num> is xxx (bytes), xxxs (sectors), xxxb (fs blocks), xxxk (xxx KiB),
2024-05-01T22:11:11.447512645Z       xxxm (xxx MiB), xxxg (xxx GiB), xxxt (xxx TiB) or xxxp (xxx PiB).
2024-05-01T22:11:11.447515872Z <value> is xxx (512 byte blocks).
2024-05-01T22:11:11.447518910Z ) 
```

A similar issue was discussed by the Fedora team in https://github.com/coreos/fedora-coreos-tracker/issues/1443 and attributed to [this commit](https://git.kernel.org/pub/scm/fs/xfs/xfsprogs-dev.git/commit/?id=6e0ed3d19c54603f0f7d628ea04b550151d8a262) to xfsprogs, which was incorporated in `v5.19.0` ([CHANGELOG](https://git.kernel.org/pub/scm/fs/xfs/xfsprogs-dev.git/tree/doc/CHANGES)). The commit disallows the creation of XFS file systems smaller than 300 MiB. Apparently, there are performance and redundancy problems with XFS file systems smaller than this.

It looks like `v1.6.x-head` and `v1.5.x-head` of `longhorn-manager` use xfsprogs `v5.13.0` (before the change), but `master-head` uses xfsprogs `v6.6.0`. It is the result of our transition from SLES 15 SP5 to SLES 15 SP6.

```
eweber@laptop:~/longhorn-manager> docker run --rm -it --entrypoint mkfs.xfs longhornio/longhorn-manager:v1.6.x-head -V
mkfs.xfs version 5.13.0
eweber@laptop:~/longhorn-manager> docker run --rm -it --entrypoint mkfs.xfs longhornio/longhorn-manager:v1.5.x-head -V
mkfs.xfs version 5.13.0
eweber@laptop:~/longhorn-manager> docker run --rm -it --entrypoint mkfs.xfs longhornio/longhorn-manager:master-head -V
mkfs.xfs version 6.6.0
```

```
eweber@laptop:~/longhorn-manager> docker run --rm -it --entrypoint cat longhornio/longhorn-manager:v1.5.x-head /etc/os-release
NAME="SLES"
VERSION="15-SP5"
VERSION_ID="15.5"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp5"
DOCUMENTATION_URL="https://documentation.suse.com/"
eweber@laptop:~/longhorn-manager> docker run --rm -it --entrypoint cat longhornio/longhorn-manager:v1.6.x-head /etc/os-release
NAME="SLES"
VERSION="15-SP5"
VERSION_ID="15.5"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp5"
DOCUMENTATION_URL="https://documentation.suse.com/"
eweber@laptop:~/longhorn-manager> docker run --rm -it --entrypoint cat longhornio/longhorn-manager:master-head /etc/os-release
NAME="SLES"
VERSION="15-SP6"
VERSION_ID="15.6"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP6"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp6"
DOCUMENTATION_URL="https://documentation.suse.com/"
```

## To Reproduce

Run the test mentioned above.

## Expected behavior

I think this is more a documentation and test fixing issue than anything. We could theoretically downgrade xfsprogs in the container or help users add the `--unsupported` flag to the mount command, but I don't think we should. Instead, we should:

- Ensure our end-to-end tests use XFS volumes that are larger than 300 MiB so tests don't accidentally fail.
- Document that the minimum size Longhorn supports for an XFS file system is 300 MiB.
- Probably fail sooner with a clear message if a user creates such a file system. (The logs above are from `NodeStageVolume`. Maybe we should fail in `ControllerCreateVolume`.

**Comment by ejweber** [comment]
I wanted to confirm that `v1.6.x` and `v1.5.x` would not be updated similarly before proceeding. This appears to be correct per:

- [Renovate configuration](https://github.com/longhorn/release/blob/e68d758cf9f86ddc3ca216d7cc77d5cefca2af28/renovate-default.json)
- [Policy](https://github.com/longhorn/longhorn/wiki/Dependency-Update-Policy)

**Comment by ejweber** [comment]
Per https://github.com/longhorn/longhorn/issues/8488#issuecomment-2096448479, I don't think we need the backports because we will not update the longhorn-manager base container (https://github.com/longhorn/longhorn-manager/blob/ca7e8a10c0516ff6adbb5a24bc9b7db4614b3782/package/Dockerfile#L1). Do you disagree @innobead?

**Comment by derekbit** [comment]
@ejweber Do you think we can put it into v1.6.2?

**Comment by ejweber** [comment]
@derekbit, I think we do not need the backports at all, actually. v1.6.x and v1.5.x use a version of xfsprogs that still allows < 300 MiB volume sizes.

**Comment by derekbit** [comment]
> I think we do not need the backports at all, actually. v1.6.x and v1.5.x use a version of xfsprogs that still allows < 300 MiB volume sizes.

One question, master, v1.6.x and v1.5.x use the same BCI image 15.5. Why are their xfsprogs different?

**Comment by derekbit** [comment]
> > One question, master, v1.6.x and v1.5.x use the same BCI image 15.5. Why are their xfsprogs different?
> 
> Master actually uses 15.6.
> 
> https://github.com/longhorn/longhorn-manager/blob/7e3b690713eb75fce1d386d0d6803324ecf88cdf/package/Dockerfile#L3

I see. BCI image 15.6 is currently in [TechPreview](https://registry.suse.com/categories/beta/repositories/bci-bci-base-15sp6) state. Once it reaches Stable state, we will update the BCI image of Longhorn v1.6.x and v1.5.x to version 1.5.6, in accordance with our [policy](https://github.com/longhorn/longhorn/wiki/Dependency-Update-Policy). Then, the PR needs to backport as well.

You can backport them after the update or to versions 1.6.3 and 1.5.6. I'm fine with either option.

**Comment by ejweber** [comment]
- [ ] Create a website PR that covers v1.6.3 and v1.5.6 as well.
- [ ] Merge v1.6.x longhorn-manager PR after v1.6.2 release.

**Comment by chriscchien** [comment]
Hi @ejweber ,

In the **Snapshots and clones section** of test [steps](https://github.com/longhorn/longhorn-manager/pull/2785#issuecomment-2100964293)

I created the xfs storageclass, pvc and pod in v1.6.x then upgrade Longhorn to master-head, after upgrade complete, the 200mb xfs PVC(`test-too-small`) can be restored from volumesnapshot and restored from PVC clone and the correspond 200mb xfs PV all created, could you help confirm if this is correct behavior? thank you.


```bash
> k get pvc
NAME                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     VOLUMEATTRIBUTESCLASS   AGE
test-too-small           Bound    pvc-b97968ff-1c64-46a9-bfbc-f7de507db156   200Mi      RWO            test-too-small   <unset>                 16m
test-too-small-restore   Bound    pvc-5195ed5e-18bd-434c-853f-4a6f144f2d49   200Mi      RWO            test-too-small   <unset>                 13m
test-too-small-clone     Bound    pvc-24b99af3-c4ae-4691-befb-1f214c22b52c   200Mi      RWO            test-too-small   <unset>                 13m 
>
> k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                            STORAGECLASS     VOLUMEATTRIBUTESCLASS   REASON   AGE
pvc-b97968ff-1c64-46a9-bfbc-f7de507db156   200Mi      RWO            Delete           Bound    default/test-too-small           test-too-small   <unset>                          10m
pvc-5195ed5e-18bd-434c-853f-4a6f144f2d49   200Mi      RWO            Delete           Bound    default/test-too-small-restore   test-too-small   <unset>                          6m30s
pvc-24b99af3-c4ae-4691-befb-1f214c22b52c   200Mi      RWO            Delete           Bound    default/test-too-small-clone     test-too-small   <unset>                          6m30s
>
> k describe pv | grep FSType
    FSType:            xfs
    FSType:            xfs
    FSType:            xfs
>
> k get storageclass test-too-small -o yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"test-too-small"},"parameters":{"fsType":"xfs"},"provisioner":"driver.longhorn.io","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}
  creationTimestamp: "2024-05-21T07:12:53Z"
  name: test-too-small
  resourceVersion: "10350"
  uid: 41823d6d-411f-4177-82e8-e7961f84918c
parameters:
  fsType: xfs
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate

```

[supportbundle_08a1c026-f9a5-4961-8318-cfee2225d03d_2024-05-21T07-20-57Z.zip](https://github.com/longhorn/longhorn/files/15386046/supportbundle_08a1c026-f9a5-4961-8318-cfee2225d03d_2024-05-21T07-20-57Z.zip)

**Comment by ejweber** [comment]
This is correct behavior @chriscchien.

In general, if the XFS file system was created BEFORE we added the restrictions, we expect to be able to restore/clone it. We only wish to prevent the creation of NEW Longhorn volumes with XFS file systems.

This was what I was intending to convey with:

```
6. The new logic does not prevent the restore.

...

8. The new logic does not prevent the clone.
```

Please let me know if it is still unclear!

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `23ccdd`) with test [steps](https://github.com/longhorn/longhorn-manager/pull/2785#issuecomment-2100964293)

In master-head, we can not create an XFS volume smaller than 300 MiB through UI and kubectl
