### ISSUE TITLE
[BUG] Instance manager pod consumes high CPU usage 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8496]
## Describe the bug

Instance manager pod consumes high CPU usage 
```
csi-provisioner-7b95bf4b87-sp2sv                    1m           8Mi
csi-resizer-6df9886858-5tdck                        1m           7Mi
csi-resizer-6df9886858-fj965                        2m           9Mi
csi-resizer-6df9886858-zq44v                        1m           7Mi
csi-snapshotter-5d84585dd4-d84c5                    1m           7Mi
csi-snapshotter-5d84585dd4-dkcbc                    2m           8Mi
csi-snapshotter-5d84585dd4-nm52v                    1m           7Mi
engine-image-ei-5cefaf2b-cnph7                      6m           14Mi
engine-image-ei-5cefaf2b-fj4np                      6m           13Mi
instance-manager-9d7fe156725e88cd906edc19bdba6679   2984m        11Mi
instance-manager-cb58fdb9e283c040126c32220b224e3c   2982m        11Mi
longhorn-csi-plugin-798wn                           1m           27Mi
longhorn-csi-plugin-mcwf4                           1m           26Mi
longhorn-driver-deployer-6f9d655cc8-wsxzx           1m           12Mi
longhorn-manager-v9xsk                              4m           41Mi
longhorn-manager-w8mkv                              3m           40Mi
longhorn-ui-7cc8f4b459-6vb9z                        0m           2Mi
longhorn-ui-7cc8f4b459-bntgw                        0m           2Mi
```

The CPU profiling shows the `startMonitoring()` are the culprits.
![image](https://github.com/longhorn/longhorn/assets/12527233/09319a50-041f-4d65-90ff-b914690cde3e)

The issue is due to the changes in https://github.com/longhorn/longhorn-instance-manager/pull/478

- https://github.com/longhorn/longhorn-instance-manager/commit/5ae373f1c4d781bce22287a158d9c80b5343f0f5#diff-b6f89e6a0f9f9116890c525856b9fef8ef4a1e7863810e8ef23c417cf35291e6
- https://github.com/longhorn/longhorn-instance-manager/commit/5ae373f1c4d781bce22287a158d9c80b5343f0f5#diff-4c99a0b428478e1d40c93b0420b35b22b3456df418b4dd7edbb7e813a9c36a4b
- https://github.com/longhorn/longhorn-instance-manager/commit/5ae373f1c4d781bce22287a158d9c80b5343f0f5#diff-b41d02f71c670ff801d99892d32ef6dd36e43fcdf4c12c044cd34a073cc18200

## Environment

 - Longhorn version: master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
cc @FrankYang0529

**Comment by roger-ryao** [comment]
**Verified on master-head 20240509**

- longhorn `master-head `https://github.com/longhorn/longhorn/commit/8026d1a700e66f9254fad75ee1e39390a0172208
- longhorn-instance-manager `master-head` https://github.com/longhorn/longhorn-instance-manager/commit/7e13b69c99f066a103b47a072774f2cadf6f1d8f

**The test steps**

https://github.com/longhorn/longhorn/issues/8496#issuecomment-2098524952

**Result Passed**

```console
NAME                                                CPU(cores)   MEMORY(bytes)
csi-attacher-5579f877b5-9znqv                       1m           9Mi
csi-attacher-5579f877b5-qkphx                       1m           9Mi
csi-attacher-5579f877b5-s9mfw                       1m           11Mi
csi-provisioner-56fd5b67ff-clk47                    1m           9Mi
csi-provisioner-56fd5b67ff-mmdl5                    2m           10Mi
csi-provisioner-56fd5b67ff-tl5bm                    2m           13Mi
csi-resizer-5dc4d54cb7-f7psf                        1m           9Mi
csi-resizer-5dc4d54cb7-lthb9                        1m           9Mi
csi-resizer-5dc4d54cb7-pvwgq                        1m           11Mi
csi-snapshotter-9b947f9f6-nhdd2                     1m           8Mi
csi-snapshotter-9b947f9f6-sj5w5                     3m           10Mi
csi-snapshotter-9b947f9f6-v7wtv                     1m           9Mi
engine-image-ei-b907910b-9kqrz                      7m           22Mi
engine-image-ei-b907910b-nnc5w                      7m           22Mi
engine-image-ei-b907910b-vtbl8                      8m           22Mi
instance-manager-7a132c76300fce78b362996dc1cd4c1e   9m           43Mi
instance-manager-bb96ae55302772053bf621a82f34feb5   20m          55Mi
instance-manager-c3bc7a4eaaa07214b006b3689cfe29bc   10m          38Mi
longhorn-csi-plugin-hmh6v                           1m           31Mi
longhorn-csi-plugin-kdwsc                           1m           32Mi
longhorn-csi-plugin-px4dl                           1m           31Mi
longhorn-driver-deployer-5ff69894cd-mrd9f           1m           13Mi
longhorn-manager-fdwhn                              10m          58Mi
longhorn-manager-qps7j                              6m           51Mi
longhorn-manager-vcmrl                              7m           48Mi
longhorn-ui-594c5488d4-4g2jg                        1m           4Mi
longhorn-ui-594c5488d4-tbwbt                        0m           4Mi
```
