### ISSUE TITLE
[BUG] Unable to join new node - Longhorn v1.7.0-dev

### ISSUE THREAD

**Issue by irjohn** [longhorn/longhorn#8497]
Issue:
When I join a new node to my cluster, all the Longhorn images are raised successfully, and the node is registered in the UI. Sometimes the disk is shown with the amount of space it has, sometimes it does not. The instance-manager image eventually consumes all of the cpu though and the disk is unable to schedule replicas, even manually. 

To Reproduce:
Create a clone of a ubuntu 22.04 with 1 cpu, 2 Gb Memory, 20Gb Hard Drive. Install containerd version 1.7.14, install kernel 6.5.0-28, install runc version 1.1.2, install kubelet, kubeadm, kubectl version 1.29, join the cluster 

Expected behavior:
I expected the node to setup the /longhorn directory and become usable.

## Support bundle for troubleshooting

 - Longhorn version: 1.7.0-dev
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 7
   - OS type and version: Ubuntu-22.04.4 LTS
   - Kernel version: 6.5.0-28-generic
   - CPU per node: 4-8
   - Memory per node: 4-8Gb
   - Disk type: NVMe
   - Network bandwidth between the nodes (Gbps): 1
 - Underlying Infrastructure: Baremetal
 - Number of Longhorn volumes in the cluster: 7 

## Additional context
I have a cluster with 4 Raspberry pi 5's, several VMware VMs and my desktop computer, I have flannel, metalLB and prometheus installed

**Comment by derekbit** [comment]
> Issue: When I join a new node to my cluster, all the Longhorn images are raised successfully, and the node is registered in the UI. Sometimes the disk is shown with the amount of space it has, sometimes it does not. The instance-manager image eventually consumes all of the cpu though and the disk is unable to schedule replicas, even manually.
> 
> To Reproduce: Create a clone of a ubuntu 22.04 with 1 cpu, 2 Gb Memory, 20Gb Hard Drive. Install containerd version 1.7.14, install kernel 6.5.0-28, install runc version 1.1.2, install kubelet, kubeadm, kubectl version 1.29, join the cluster
> 
> Expected behavior: I expected the node to setup the /longhorn directory and become usable.
> 
> ## Support bundle for troubleshooting
> * Longhorn version: 1.7.0-dev
> * Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
>   
>   * Number of control plane nodes in the cluster: 3
>   * Number of worker nodes in the cluster: 7
>   * OS type and version: Ubuntu-22.04.4 LTS
>   * Kernel version: 6.5.0-28-generic
>   * CPU per node: 4-8
>   * Memory per node: 4-8Gb
>   * Disk type: NVMe
>   * Network bandwidth between the nodes (Gbps): 1
> * Underlying Infrastructure: Baremetal
> * Number of Longhorn volumes in the cluster: 7
> 
> ## Additional context
> I have a cluster with 4 Raspberry pi 5's, several VMware VMs and my desktop computer, I have flannel, metalLB and prometheus installed

The high CPU usage is due to https://github.com/longhorn/longhorn/issues/8496.
What not use v1.6.1 instead? v1.7.0-dev is for development.

**Comment by irjohn** [comment]
> The high CPU usage is due to #8496. What not use v1.6.1 instead? v1.7.0-dev is for development.

I installed with helm and didnt realize it was v1.7.0-dev until it was installed and I already deployed a bunch of things on it, I dont want to tear the cluster down. How can i downgrade to v1.6.1 safely? It took a lot of troubleshooting to setup my multimaster cluster and Im afraid of having to tear it down again

**Comment by derekbit** [comment]
> > The high CPU usage is due to #8496. What not use v1.6.1 instead? v1.7.0-dev is for development.
> 
> I installed with helm and didnt realize it was v1.7.0-dev until it was installed and I already deployed a bunch of things on it, I dont want to tear the cluster down. How can i downgrade to v1.6.1 safely? It took a lot of troubleshooting to setup my multimaster cluster and Im afraid of having to tear it down again. Also this is my first issue I've ever posted to Github, sorry if I didnt format correctly.

Hello @irjohn,
Longhorn doesn't support downgrade for now. You can just uninstall the Longhorn system (no need to tear down the entire kubernetes cluster) and reinstall v1.6.1 or v1.5.5.
Please see the uninstallation method in https://longhorn.io/docs/1.6.1/deploy/uninstall/.

**Comment by irjohn** [comment]
> > > The high CPU usage is due to #8496. What not use v1.6.1 instead? v1.7.0-dev is for development.
> > 
> > 
> > I installed with helm and didnt realize it was v1.7.0-dev until it was installed and I already deployed a bunch of things on it, I dont want to tear the cluster down. How can i downgrade to v1.6.1 safely? It took a lot of troubleshooting to setup my multimaster cluster and Im afraid of having to tear it down again. Also this is my first issue I've ever posted to Github, sorry if I didnt format correctly.
> 
> Hello @irjohn, Longhorn doesn't support downgrade for now. You can just uninstall the Longhorn system (no need to tear down the entire kubernetes cluster) and reinstall v1.6.1 or v1.5.5. Please see the uninstallation method in https://longhorn.io/docs/1.6.1/deploy/uninstall/.

Thanks for your quick replies! I will consult this documentation and follow it, one last thing, if I make a system backup with the UI can i restore from it once I reinstall? I know its in the documentation, but Im wondering if since the backups are made with v1.7.0-dev if they are backwards compatible with a downgraded version also?

**Comment by derekbit** [comment]
> mentation, but Im wondering if since the backups are made with v1.7.0-dev if they are backwards compatible with a downgra

@c3y1huang @ChanYiLin  Do you know if there is any compatibility issue in system backup/restore here?

**Comment by irjohn** [comment]
> > mentation, but Im wondering if since the backups are made with v1.7.0-dev if they are backwards compatible with a downgra
> 
> @c3y1huang @ChanYiLin Do you know if there is any compatibility issue in system backup/restore here?

I was able to uninstall and restore from backups. Thanks so much for your help :)

**Comment by derekbit** [comment]
> > > mentation, but Im wondering if since the backups are made with v1.7.0-dev if they are backwards compatible with a downgra
> > 
> > 
> > @c3y1huang @ChanYiLin Do you know if there is any compatibility issue in system backup/restore here?
> 
> I was able to uninstall, restore from backups and add a new node with no issues to the cluster. Thanks so much for your help :)

Thanks for the update @irjohn.
