### ISSUE TITLE
Issue with volume size mounting longhorn claim on pod's sidecar

### ISSUE THREAD

**Issue by dnauck** [longhorn/longhorn#85]
How to reproduce:

1.) new Project in rancher
2.) install Wordpress Helm Chart from Rancher library
3.) enable persistent volumes for maridb and wordpress
4.) edit the Wordpress workload (after successful deployment) and add a sidecar:
	- image: atmoz/sftp
	- bind docker port 22 to some other (e.g. host port)
	- mount wordpress-data volume to this sidecar to /home/your-user/wordpress
	- add command: your-user:yourpassword

Error message with longhorn v0.2:

````
Events:
 Type     Reason                 Age               From                     Message
 ----     ------                 ----              ----                     -------
 Warning  FailedScheduling       1m                default-scheduler        AssumePod failed: pod 1fabb23e-6b62-11e8-aa62-005056a736d2 is in the cache, so can't be assumed
 Normal   Scheduled              1m                default-scheduler        Successfully assigned diva-yachts-net-wordpress-867b64bdfd-nb4pc to dmz-cl1-node-3
 Normal   SuccessfulMountVolume  1m                kubelet, dmz-cl1-node-3  MountVolume.SetUp succeeded for volume "default-token-c4sd5"
 Warning  FailedMount            30s (x7 over 1m)  kubelet, dmz-cl1-node-3  MountVolume.SetUp failed for volume "pvc-dcd6b679-68d4-11e8-bfec-005056a739a9" : mount command failed, status: Failure, reason: create volume fail: fail to parse size error parsing size 'null': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
````

Error message with longhorn v0.2.1:

````
Events:
  Type     Reason                 Age               From                     Message
  ----     ------                 ----              ----                     -------
  Warning  FailedScheduling       4m                default-scheduler        AssumePod failed: pod 81c90008-6dae-11e8-aa62-005056a736d2 is in the cache, so can't be assumed
  Normal   Scheduled              4m                default-scheduler        Successfully assigned wordpress-wordpress-7df97dfcbf-lkglp to dmz-cl1-node-3
  Normal   SuccessfulMountVolume  4m                kubelet, dmz-cl1-node-3  MountVolume.SetUp succeeded for volume "default-token-nntr7"
  Warning  FailedMount            14s (x2 over 2m)  kubelet, dmz-cl1-node-3  Unable to mount volumes for pod "wordpress-wordpress-7df97dfcbf-lkglp_wordpress(81c90008-6dae-11e8-aa62-005056a736d2)": timeout expired waiting for volumes to attach or mount for pod "wordpress"/"wordpress-wordpress-7df97dfcbf-lkglp". list of unmounted volumes=[wordpress-data]. list of unattached volumes=[wordpress-data default-token-nntr7]
  Warning  FailedMount            9s (x10 over 4m)  kubelet, dmz-cl1-node-3  MountVolume.SetUp failed for volume "pvc-93b77b6b-6dad-11e8-aad9-005056a739a9" : mount command failed, status: Failure, reason: cannot create volume without size
````

With Rancher 2.02, longhorn v0.2 via rancher helm, K8n v1.10.1-rancher-2-1, rke/custom cluster with 3 nodes

**Comment by morgoved** [comment]
i have some problem.
[https://github.com/rancher/rancher/issues/22173](url)

**Comment by yasker** [comment]
@morgoved I noticed that you're using flex volume driver, can you try CSI? Which version of Kubernetes you're using?

**Comment by morgoved** [comment]
> @morgoved I noticed that you're using flex volume driver, can you try CSI? Which version of Kubernetes you're using?

because i have ubuntu 18.04 and have problem with running open-iscsi
` systemctl status open-iscsi
● open-iscsi.service - Login to default iSCSI targets
   Loaded: loaded (/lib/systemd/system/open-iscsi.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Tue 2019-08-13 23:49:48 UTC; 1 day 8h ago
           ├─ ConditionDirectoryNotEmpty=|/etc/iscsi/nodes was not met
           └─ ConditionDirectoryNotEmpty=|/sys/class/iscsi_session was not met
     Docs: man:iscsiadm(8)
           man:iscsid(8)
`
But i solved my problem - i try used the other version for harbor and it's works good.
p.s. k8s 1.15 harbor now 1.8.2 (default tag for images in chart it is dev)
