### ISSUE TITLE
Upgrading from v0.5.0 to v0.6.2 all volumes disappeared

### ISSUE THREAD

**Issue by NchemIcaLS** [longhorn/longhorn#850]
I have longhorn installed under apps in rancher. Before upgrading I made sure to detach all volumes. Then I upgraded the chart from 0.5.0 to 0.6.2. After the upgrade I noticed that the longhorn-system namespace no longer had any pods corresponding to volumes and the longhorn UI shows no volumes as well. I checked /var/lib/rancher/longhorn on the nodes and some replicas are still there.

I tried a rollback to 0.5.0 but that didn't fix it. I tried reupgrading to 0.6.2 but had issues with the driver deployer. I followed #755 to fix this. In the ended, I completeley removed longhorn and reinstalled in order to restore from backups.

I guess I already fixed my issue by restoring from backups but just thought I'd report it anyway.

---
Version: `v0.5.0`
Version: `v0.6.2`

**Comment by shuo-wu** [comment]
1. What's your Rancher version when you upgrade your Longhorn?
2. Did you experience the upgrade/rollback failure like #755 before the volume disappeared?

I am suspecting you may trigger the bug #783: the Longhorn uninstaller is launched and all Longhorn volumes will be deleted.

**Comment by NchemIcaLS** [comment]
1. I was on Rancher v2.2.4
2. The first time there was no issue with the upgrade itself. #775 happened after the volumes disappeared and I attempted to rollback.

The volumes definitely disappeared during the upgrade. That somehow the uninstaller got triggered would explain it. I wish I could provide more debug information but I needed the cluster back and running so I reset everything and restored from backups.
