### ISSUE TITLE
[BUG][V1.5.5] fs trim job fails on RWX volume

### ISSUE THREAD

**Issue by solarvm** [longhorn/longhorn#8502]
## Describe the bug

FS Trim failing on one of the volumes with the following error msg:
`unable to trim filesystem for volume pvc-664fda10-cc1e-4da0-a2eb-cfce1ddb6216: rpc error: code = Internal desc = failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/2375832/ns/mnt --net=/host/proc/2375832/ns/net fstrim /export/pvc-664fda10-cc1e-4da0-a2eb-cfce1ddb6216], output , stderr fstrim: stat of /export/pvc-664fda10-cc1e-4da0-a2eb-cfce1ddb6216 failed: No such file or directory : exit status 1
`
## To Reproduce

Unfortunately i don't have any similar env to try to reproduce this exact issue, sorry

## Expected behavior

Expected to get fstrim job to complete normally, like it had been doing before the issues started to occur shortly after upgrading to v.1.5.5

## Support bundle for troubleshooting

[Support bundle](https://drive.google.com/file/d/1Rl40JRHs8zRSAb6iA-_4r6fcsGpsjbqj/view?usp=sharing)

## Environment

 - Longhorn version: v1.5.5
 - Impacted volume (PV):  pvc-664fda10-cc1e-4da0-a2eb-cfce1ddb6216
 - Installation method:  Rancher app catalog
 - Kubernetes distro: RKE2 v1.26.11
   - Number of control plane nodes in the cluster: 3 
   - Number of worker nodes in the cluster: 5
 - Node config
   - OS type and version: Ubunto 22.04 LTS
   - Kernel version:  5.15.0
   - CPU per node: 48
   - Memory per node: 256Gb
   - Disk type: SSD @ softraid mirror mode
   - Network bandwidth between the nodes (Gbps): 25Gbps
 - Underlying Infrastructure: baremetal
 - Number of Longhorn volumes in the cluster: 31

## Additional context
N/A at the moment

**Comment by solarvm** [comment]
Tried to re-deploy the affected pod to another node. It started fine on node5, attached the vol successfuly, however Longhorn UI still shows it connected/mounted on node4
`Attached Node & Endpoint:
trw-pr4
/dev/longhorn/pvc-664fda10-cc1e-4da0-a2eb-cfce1ddb6216`

and fstrim is still failing with the same error message

**Comment by james-munson** [comment]
Sounds very much like https://github.com/longhorn/longhorn/issues/7768.  Looking.

**Comment by james-munson** [comment]
I think that's it.  Looking at the v1.5.x source code, it seems like https://github.com/longhorn/longhorn-share-manager/pull/116 should have been backported to 1.5 as well, and we missed that.

**Comment by derekbit** [comment]
cc @c3y1huang

**Comment by james-munson** [comment]
We didn't miss it at the time of the fix in January.  The mistaken code was introduced into v1.5.x in March as part of a "vendor" update in commit https://github.com/longhorn/longhorn-share-manager/commit/c311e1238a31c5870eb4d7647d55d57297a12475

**Comment by innobead** [comment]
@james-munson please elaborate more about the issue.

**Comment by james-munson** [comment]
https://github.com/longhorn/longhorn-share-manager/commit/c311e1238a31c5870eb4d7647d55d57297a12475#diff-2cc75656fee7d4deb7895198d108bf8aa70a5809d5c97a2dd93ed86c64d0f5b8 added code that was the problem in #7768 and had already been fixed in master and 1.6.x.

**Comment by roger-ryao** [comment]
**Verified on v1.5.x-head 20240510**

- longhorn v1.5.x-head https://github.com/longhorn/longhorn/commit/b21a93873ac92755a8308387456cb9c5792a34e2
- longhorn-share-manager v1.5.x-head https://github.com/longhorn/longhorn-share-manager/commit/7cde7f5f07b176fc2a2202087999b8d35e40119b


**The test steps**

https://github.com/longhorn/longhorn/issues/7768#issue-2097433844


**Result Passed**


Manually tested and passed.
