### ISSUE TITLE
[Bug] DaemonSet longhorn-manager has too much RBAC permission which may leads the whole cluster being hijacked

### ISSUE THREAD

**Issue by Yseona** [longhorn/longhorn#8506]
Hi Community!
Our team just found a possible security issue when reading the code. And we have reported to [longhorn-security](mailto:longhorn-security@suse.com) via email , but have not received a reply yet. The title of the email is the same as the title of this issuse, and at the end of the email we attached detailed information about the issue.
Looking forward to your reply.
Kind regards,
Seona

**Comment by ejweber** [comment]
Hello @Yseona. Could you please send the e-mail again and reference this issue so the Longhorn team can confirm we have all of the details? Thanks!

**Comment by Yseona** [comment]
@ejweber Okay, I've resent the e-mail.

**Comment by ejweber** [comment]
Thanks again @Yseona for raising your concerns. We made changes to our IT infrastructure recently at SUSE, and it appears that the longhorn-security@suse.com address is not currently working as intended. While we attempt to resolve the issue, can you please send the email to one or more Longhorn maintainers? You can find the list of active maintainers at https://github.com/longhorn/longhorn/blob/master/MAINTAINERS. You will find my address (eric.weber@suse.com) on the list. I would be happy to redistribute the e-mail internally if you send it along.

**Comment by PhanLe1010** [comment]
Did we recived the email @ejweber ?

**Comment by ejweber** [comment]
Thanks for bumping this @PhanLe1010. Not to my knowledge.

**Comment by kaaass** [comment]
Hi, I'm also the reporter of this issue. I had resent the email to you @ejweber @PhanLe1010.
