### ISSUE TITLE
[BUG] Test case test_support_bundle_should_not_timeout timed out

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#8507]
## Describe the bug

Test case `test_support_bundle_should_not_timeout` timed out on master-head:

```
kubernetes.client.exceptions.ApiException: (0)
Reason: Timeout on executing command

        cmd = [
            "bash", "-c",
            f"bundle=`ls /tmp/support-bundle-kit/ | grep zip` &&\
            rm -f /tmp/support-bundle-kit/$bundle &&\
            dd if=/dev/urandom of={bundle} bs=1G count=5 > /dev/null 2>&1 &&\
            zip /tmp/support-bundle-kit/$bundle {bundle} > /dev/null 2>&1 &&\
            rm -f {bundle} &&\
            stat -c \"%s\" /tmp/support-bundle-kit/$bundle",
        ]
        with timeout(seconds=600, error_message='Timeout on executing command'):
>           zip_size = stream(core_api.connect_get_namespaced_pod_exec,
                              pod_name, LONGHORN_NAMESPACE,
                              command=cmd, stderr=True, stdin=False, stdout=True,
                              tty=False)
```

https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/906/testReport/junit/tests/test_support_bundle/test_support_bundle_should_not_timeout/

## To Reproduce

Run test case `test_support_bundle_should_not_timeout`

## Environment

 - Longhorn version: master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:  v1.29.3+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: sles 15-sp5
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): aws
 - Number of Longhorn volumes in the cluster:

**Comment by c3y1huang** [comment]
I cannot reproduce this: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7046/

@yangchiu is this issue still valid?

**Comment by yangchiu** [comment]
This issue is no longer present. The test case `test_support_bundle_should_not_timeout` passed in the recent [10 test builds](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/test_results_analyzer/).
