### ISSUE TITLE
what is forntend?

### ISSUE THREAD

**Issue by yuchunyun** [longhorn/longhorn#852]
Hello, I have some questions that I don't understand. Can you help me?

I've seen multiple references to the frontend in the document

-    "Longhorn supports iscsi target frontend mode as stated" in the file docs/iscsi.md

-    "The frontend (either open-iscsi/TGT are supported at this moment)"  in the file longhorn-engine/readme.md 

-    When I create volume on the UI, the Frontend has two choices, Block device and iscsi

-    The processes parameters in the pod instance-manager-e-xxxx are all “frontend sockets”

So, I don't understand this frontend, it seems to be inconsistent, are they wrong?

**Comment by yasker** [comment]
@yuchunyun The frontend in the Longhorn indicates the way how Longhorn present the volume to the user.

To the end-user, we have two frontends available now: iscsi or block device. Both of them are implemented using TGT as an iSCSI target in the back. Block device frontend will also involve open-iscsi on the host to create the device. To Longhorn engine, those two frontends are `tgt-iscsi` and `tgt-blockdev`.

We used to have another frontend called `tcmu` in the engine, but we recently deprecated that. I've replaced the `either` with `only` in the Longhorn engine README.md.

Regarding the `frontend-socket`, it's another frontend setup for the engine and related to how we implemented the frontend based on TGT.

**Comment by yuchunyun** [comment]
@yasker   Thank you very much for your explanation.

As an end user, can I understand it this way?

The block device frontend is something I can use directly to format the mount (Longhorn has done the target for me), and ISCSI is something I need to manually use opern-iscsi to log in and find before I can format and mount it.

**Comment by yasker** [comment]
@yuchunyun That's correct.

**Comment by yuchunyun** [comment]
@yasker  I also have a problem that I see disk /dev/sdh on the host using the fdisk command, but I see /dev/longhorn/pvc-e2fe33a6-ffa0-11e9-9ec4-5254008c3f4d mounted using the mount command. Shouldn't it be /dev/sdh

**Comment by yasker** [comment]
@yuchunyun They're the same since they have the same major and minor number. We created `/dev/longhorn/xxx` to make it easier for the user to access the block device since the block device name is the same as the Longhorn volume's name.

**Comment by yuchunyun** [comment]
@yasker   Yes, I saw their major:minor device number, how to map /dev/sdh to /dev/longhorn/volumeName?

**Comment by yasker** [comment]
We used `mknod` to do that.

**Comment by yuchunyun** [comment]
@yasker   thanks
