### ISSUE TITLE
[IMPROVEMENT] Apply taint-toleration to instance-manager and share-manager with best effort

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#8524]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

I'm open to disagreements on this one. It seems like a nice improvement to me, but maybe there's a reason it's more complicated than I think.

Previously, Longhorn would automatically crash all instance-manager and share-manager pods when the setting `taint-toleration` was updated. After https://github.com/longhorn/longhorn/issues/7173, we will wait to update the setting until all volumes are detached (an improvement in safety). However, it is still inconvenient for users.

For DaemonSets and Deployments, it makes sense to wait to update the `tolerations` field until volumes are detached because updating any aspect of a DaemonSet will cause all pods governed by that DaemonSet to restart. We want to control when this behavior occurs.

For instance-manager and share-manager, pods are individually managed by longhorn-manager. We can choose NOT to crash instance-manager and share-manager pods by [removing this code](https://github.com/longhorn/longhorn-manager/blob/f7e2d5363978081477cfa6ee46436c0244a1482a/controller/setting_controller.go#L609-L614) and making some additional modifications. Then, newly created instance-managers and share-managers will get the new toleration, but existing instance-managers and share-managers will still run.

### Why not do this with all similar settings?

Maybe there are other settings that can also benefit from an improvement like this, but some obviously can't. For example, it wouldn't make sense to respond in a best-effort fashion to the `storage-network` setting. All engines and replicas need to agree on that setting's value.

### Why is it safe to do for the taint-toleration setting?

- If the user wants to make an instance-manager or share-manager to run somewhere it couldn't run before by updating the setting, the corresponding pod already doesn't exist. Now longhorn-manager can create it.
- If user want to make it impossible to run an instance-manager or share-manager pod on a node it is currently running on, they can simply delete offending pods manually. It's a bit of work to do, but the benefits outweigh the drawbacks.

## Additional context

- Potentially related to: https://github.com/longhorn/longhorn/pull/7455.
- Many users have expressed concern over the current behavior. On example is in this [Rancher Users Slack thread](https://rancher-users.slack.com/archives/CC2UQM49Y/p1715026041648979).

**Comment by ejweber** [comment]
> Actually, I think this is already handled by https://github.com/longhorn/longhorn/pull/7455 and I simply misunderstood it. I will confirm and close it directly if correct.

It is. Sorry for the confusion and thanks for the implentation @mantissahz.

**Comment by innobead** [comment]
Added `duplicated` label.
