### ISSUE TITLE
volumes disappeared on upgrade 

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#853]
Reproduce steps:

- Install Longhorn v0.6.2 using yaml files:
`kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml`

- Create 3 volumes `volume-test-{1,2,3}`
  - Attach `volume-test-1` to a node, keep it attached
  - Keep `volume-test-2` detached
  - Attach `volume-test-3`, and then detach it

- Create StorageClass using:
`kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/storageclass.yaml`

 - Create a pod using Longhorn volume as persistent storage using:
`kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/pvc.yaml`

- Update Longhorn to use images with `master`  tag using:
`kubectl apply -Rf ` to install files on longhorn-manager repo: `https://github.com/longhorn/longhorn-manager/tree/master/deploy/install`

- Wait for longhorn components to be in running state `kubectl get pods -n longhorn-system  -w`
- Refresh Longhorn UI, you will not find any of the created volumes before.
**> All created volumes disappeared from UI**

**Comment by meldafrawi** [comment]
Longhorn Manager logs:

```
time="2019-11-05T19:25:53Z" level=warning msg="Can't find instance manager for pod instance-manager-r-dc4c4abe, may be deleted"
time="2019-11-05T19:25:53Z" level=warning msg="Can't find instance manager for pod instance-manager-r-46d8a417, may be deleted"
time="2019-11-05T19:25:53Z" level=warning msg="Can't find instance manager for pod instance-manager-e-f251bd2a, may be deleted"
time="2019-11-05T19:25:53Z" level=warning msg="Can't find instance manager for pod instance-manager-e-63dca920, may be deleted"
time="2019-11-05T19:25:53Z" level=warning msg="Can't find instance manager for pod instance-manager-e-6d0ae2fc, may be deleted"
time="2019-11-05T19:25:53Z" level=warning msg="Can't find instance manager for pod instance-manager-r-64d5c75e, may be deleted"
```

**Comment by yasker** [comment]
@meldafrawi Upgrade path is not available yet. https://github.com/longhorn/longhorn/issues/850

**Comment by yasker** [comment]
Close this in favor of #845
