### ISSUE TITLE
[BUG] Longhorn volume backups pods not autodeleted

### ISSUE THREAD

**Issue by ammirator-administrator** [longhorn/longhorn#8544]
Maybe there is a option for that but I did read the docs and could not find
SO every time a backup is done a new pod is spin up, now it does the job and there is no problem
But when I do `kubectl get pods -A` I see these pods and if you have a lot of backups there will be a lot of such pods `volumes-backup-cron-job-...` in complete state, is there a option to delete these from that list automatically, because once you have a lot of  backups it just getting hard to find all your pods because a lot of them are from volume backups but I'm not interested in them these just get in the way and spam the list

**Comment by derekbit** [comment]
cc @c3y1huang

**Comment by ammirator-administrator** [comment]
@derekbit @c3y1huang 
Any idea on how to fix that?

**Comment by ammirator-administrator** [comment]
Actually sorry there is a field for that in helm chart
```
  recurringSuccessfulJobsHistoryLimit: 10
  recurringFailedJobsHistoryLimit: 10
```
