### ISSUE TITLE
[BUG][v1.6.2-rc1] Workload pod got stuck in ContainerStatusUnknown after node shutdown and reboot

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#8550]
## Describe the bug

When running negative test case `Power Off Node One By Once For More Than Pod Eviction Timeout While Workload Heavy Writing`, accidentally encountered a deployment pod got stuck in `ContainerStatusUnknown` forever.

The test case steps are like:
1. Create a deployment 0 with rwo volume
2. Create a deployment 1 with rwx volume
3. Create a deployment 2 with rwo strict-local volume
4. Create a statefulset 0 with rwo volume
5. Create a statefulset 1 with rwx volume
6. Create a statefulset 2 with rwo strict-local volume
7. Keep writing data to deployment 0 ~2 and statefulset 0 ~ 2
8. Power off node 0 for 6 minutes, and then power on
9. Power off node 1 for 6 minutes, and then power on
10. Power off node 2 for 6 minutes, and then power on
11. Check deployment 0 ~2 and statefulset 0 ~ 2 pods running and able to read/write without problems

In https://ci.longhorn.io/job/private/job/longhorn-e2e-test/557/, accidentally encountered after nodes rebooted in step 7 ~ 9, the pod of deployment with rwo strict-local volume got stuck in `ContainerStatusUnknown` forever:
```
# kubectl get pods -owide
NAME                                     READY   STATUS                   RESTARTS        AGE     IP            NODE            NOMINATED NODE   READINESS GATES
longhorn-test-minio-f4bbdc54d-lhddt      1/1     Running                  0               5h27m   10.42.4.130   ip-10-0-2-198   <none>           <none>
e2e-test-deployment-2-7ddccb49f4-5fxcp   0/1     ContainerStatusUnknown   0               5h26m   <none>        ip-10-0-2-198   <none>           <none>
e2e-test-deployment-2-7ddccb49f4-lx7gv   1/1     Running                  0               5h24m   10.42.4.136   ip-10-0-2-198   <none>           <none>
e2e-test-deployment-0-b957b9f54-x7t82    1/1     Running                  0               5h18m   10.42.1.146   ip-10-0-2-53    <none>           <none>
e2e-test-deployment-1-dbc678584-8sq9k    1/1     Running                  0               5h18m   10.42.1.147   ip-10-0-2-53    <none>           <none>
e2e-test-statefulset-1-0                 1/1     Running                  0               5h15m   10.42.3.194   ip-10-0-2-78    <none>           <none>
e2e-test-statefulset-0-0                 1/1     Running                  0               5h15m   10.42.3.196   ip-10-0-2-78    <none>           <none>
e2e-test-statefulset-2-0                 1/1     Running                  0               5h14m   10.42.3.198   ip-10-0-2-78    <none>           <none>
```

```
# kubectl describe pod e2e-test-deployment-2-7ddccb49f4-5fxcp 
Name:           e2e-test-deployment-2-7ddccb49f4-5fxcp
Namespace:      default
Priority:       0
Node:           ip-10-0-2-198/10.0.2.198
Start Time:     Sat, 11 May 2024 21:05:04 +0000
Labels:         app=e2e-test-deployment-2
                pod-template-hash=7ddccb49f4
                test.longhorn.io=e2e
Annotations:    <none>
Status:         Failed
Reason:         Evicted
Message:        The node was low on resource: ephemeral-storage. Threshold quantity: 2145752505, available: 1470928Ki. 
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/e2e-test-deployment-2-7ddccb49f4
Containers:
  sleep:
    Container ID:  
    Image:         busybox
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      /bin/sh
      -c
      while true;do date;sleep 5; done
    State:          Terminated
      Reason:       ContainerStatusUnknown
      Message:      The container could not be located when the pod was terminated
      Exit Code:    137
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from pod-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-t8j6t (ro)
Conditions:
  Type                        Status
  DisruptionTarget            True 
  PodReadyToStartContainers   False 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  pod-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  e2e-test-claim-2
    ReadOnly:   false
  kube-api-access-t8j6t:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute for 300s
                             node.kubernetes.io/unreachable:NoExecute for 300s
Events:                      <none>
```

![unknown_pod1](https://github.com/longhorn/longhorn/assets/5709208/7f40fda3-2561-432a-852a-eac3a21055ea)

![unknown_pod2](https://github.com/longhorn/longhorn/assets/5709208/0b6d012a-64bb-44a0-abb7-857a9648f791)

## Expected behavior

Running negative test case `Power Off Node One By Once For More Than Pod Eviction Timeout While Workload Heavy Writing` repeatedly.

## Support bundle for troubleshooting

[supportbundle_26ac5094-4709-4ab5-bb99-867e4b13cb8f_2024-05-12T02-28-45Z.zip](https://github.com/longhorn/longhorn/files/15284907/supportbundle_26ac5094-4709-4ab5-bb99-867e4b13cb8f_2024-05-12T02-28-45Z.zip)

## Environment

 - Longhorn version: v1.6.2.-rc1
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.29.3+k3s1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: sles 15-sp5
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): aws
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
cc @c3y1huang

**Comment by c3y1huang** [comment]
`The node was low on resource: ephemeral-storage. Threshold quantity: 2145752505, available: 1470928Ki.`

**Comment by c3y1huang** [comment]
1. The test was given a pause while hanging with the error: `Waiting for e2e-test-deployment-2 pods ['e2e-test-deployment-2-7ddccb49f4-5fxcp'] stable, retry (58495) `
1. The test given the deployment `e2e-test-deployment-2` 1 replicaSet.
1. During the test, the Kubelet detected low resource on node `ip-10-0-2-198`, it initiated eviction of pod `e2e-test-deployment-2-7ddccb49f4-5fxcp`.
    ```  
          reason: TerminationByKubelet
          status: "True"
          type: DisruptionTarget
    ```
1. Then, a new deployment pod `e2e-test-deployment-2-7ddccb49f4-lx7gv` was created and reached the Running state.
4. However, despite the new pod being successfully deployed and running, the Kubelet failed to clean up the evicted pod (e2e-test-deployment-2-7ddccb49f4-5fxcp).

This issue doesn't look like a Longhorn's bug, as the deployment pod eviction was initiated by the Kubelet and it's expected that the Kubelet would handle the cleanup as well.

There's an ongoing upstream discussion that seems to be related: https://github.com/kubernetes/kubernetes/issues/122160

We could consider enhancing the test case, filtering out pods terminated by the Kubelet.

**Comment by c3y1huang** [comment]
Closing as this has been tested. https://github.com/longhorn/longhorn-tests/pull/1902#pullrequestreview-2059231761
