### ISSUE TITLE
[IMPROVEMENT] Expose local logical volume and attach it to local node

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8551]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Expose local logical volume and attach it to local node
    
1. Expose local logical volume and attach it to local nodes
2. To expose a logical volume and attach it to the local node, NGUID should be provided.

## Additional context

cc @DamiaSan @shuo-wu

**Comment by DamiaSan** [comment]
This feature is needed by:

- raid superblock, for data consistency handling
- multiple attach to nvme-of exported lvol, for live upgrade

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn-manager `ebace7`) with test [steps](https://github.com/longhorn/longhorn/issues/8551#issuecomment-2106720457)

V2 volume attach, detach, create backup, restore from backup worked well.
