### ISSUE TITLE
[BUG] Attach failed for volume 

### ISSUE THREAD

**Issue by ambujjain** [longhorn/longhorn#8581]
I need some guidance to overcome an issue we are facing. We are attempting to deploy Longhorn in Ubuntu 22.04 with k3s, but we are encountering issues where volume attachment is timing out. We are unsure of the exact issue, but when we check the syslog, we see the following errors.

Events:
  Type     Reason              Age                  From                     Message
  ----     ------              ----                 ----                     -------
  Normal   Scheduled           34m                  default-scheduler        Successfully assigned default/psql-postgresql-0 to vm3
  Warning  FailedAttachVolume  2m1s (x24 over 34m)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-f4ce40f3-27b4-41dc-961b-184a5es

**Comment by ambujjain** [comment]
Attching support bundle 
[Uploading supportbundle_b7f5b89b-7a71-41fb-aff3-0a148037c8c1_2024-05-16T03-01-46Z.zip…]()

**Comment by PhanLe1010** [comment]
> Attching support bundle Uploading supportbundle_b7f5b89b-7a71-41fb-aff3-0a148037c8c1_2024-05-16T03-01-46Z.zip…

The support bundle link seems broken. Could you double check @ambujjain

**Comment by PhanLe1010** [comment]
Btw, you can also look into the longhorn-csi and longhorn-manager logs for more clue

**Comment by ambujjain** [comment]
I tried to upload bundle with longhorn portal.. and it was completed successfully. 
how can i check  longhorn-csi and longhorn-manager logs.. could you please guide us.

**Comment by ambujjain** [comment]
@PhanLe1010 Any clue with updated support bundled ?

**Comment by ambujjain** [comment]
Can someone help us here?

**Comment by derekbit** [comment]
@ambujjain If the issue remains, please provide more information as https://github.com/longhorn/longhorn/blob/master/.github/ISSUE_TEMPLATE/bug.md for investigation. Thanks.
