### ISSUE TITLE
[BUG][CI] Coverage profiles consume a large amount of disk space on Jenkins

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#8588]
## Describe the bug

The coverage profile html reports consume a large amount of disk space on Jenkins, each build consumes about 100MB:

```
$ du -h --max-depth=1 | sort -hr
3.9G	.
106M	./905
103M	./906
100M	./908
100M	./904
99M	./907
99M	./900
99M	./885
98M	./890
98M	./889
98M	./882
97M	./903
97M	./901
97M	./887
97M	./886
97M	./883
95M	./910
95M	./909
95M	./888
95M	./884
94M	./919
94M	./918
94M	./911
94M	./898
93M	./916
92M	./917
91M	./920
91M	./912
91M	./902
91M	./899
91M	./897
70M	./881
7.4M	./701
7.2M	./848
7.2M	./795
6.7M	./786
6.4M	./798
6.3M	./858
6.3M	./807
6.2M	./847
6.2M	./690
6.1M	./764
6.1M	./695
6.0M	./783
6.0M	./780
6.0M	./779
6.0M	./725
5.9M	./803
5.9M	./777
5.9M	./776
5.9M	./774
5.9M	./709
5.8M	./880
5.8M	./851
5.8M	./830
5.8M	./804
5.8M	./769
5.8M	./728
```

```
$ du -h --max-depth=1 | sort -hr
88M	.
18M	./longhorn-share-manager_20coverage_20profile
18M	./longhorn-manager_20coverage_20profile
18M	./longhorn-instance-manager_20coverage_20profile
18M	./longhorn-engine_20coverage_20profile
18M	./backing-image-manager_20coverage_20profile
```

Without coverage profiles, each build only consumes about 5MB for the support bundle file.

Consider only generating coverage profiles for a specific pipeline, deleting old coverage profiles if there is a newer one, or any possible solutions to avoid them eating up all disk space.

cc @longhorn/qa @FrankYang0529 @innobead 

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by FrankYang0529** [comment]
Reassign to @yangchiu. I think his PR already fix the issue. Thank you.
