### ISSUE TITLE
Longhorn UI: filtering with node redundancy should be activated on click

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#859]
In **Volume page**, user should be able to filter volumes by node redundancy (**Yes, Limited, No**) on click, and doesn't need to click on `Go` button to activate the filter.

**Comment by smallteeths** [comment]
I made two ui different designs,But they all look strange.Therefore, the current operation is recommended @meldafrawi 
![Uploading Jietu20191109-105316.jpg…]()
![Uploading Jietu20191109-112126.jpg…]()

**Comment by yasker** [comment]
@meldafrawi I think the problem is it's hard to be both consistent with the current filter and allow a shortcut for the user to skip the `Go` button. I am fine with the extra click if it's needed to keep the consistency of the filter.

**Comment by meldafrawi** [comment]
closing the issue.
