### ISSUE TITLE
[IMPROVEMENT] Make gRPC service timeout configurable

### ISSUE THREAD

**Issue by fab-sgnct** [longhorn/longhorn#8590]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

We are using longhorn 1.5.x in various environments.
One of them has PVC getting close to 1TB. It also has slower network than others.
From time to time we have network issues that will cause replica issues and cause longhorn to [salvage a volume](https://longhorn.io/docs/1.6.1/terminology/#salvage-a-volume). Then longhorn will try to rebuild a replica from remaining sane ones: with the slower network and that amount of data, this operation takes hours and at some point timeouts when reaching 24h which might be frustrating if you've spent those hours looking at rebuild percentage going up slowly to 90+% before going back to 0%.

## Describe the solution you'd like

As making the rebuild operation faster might be challenging and limited by network speed vs data size, the alternative would be to be able to give it more time i.e., from my understanding, be able to [configure the gRPC service long timeout
](https://github.com/longhorn/longhorn-engine/blob/e39b7f0313b22d5c435ce57d1442800999a0f4ac/pkg/replica/client/client.go#L21-L24)

## Describe alternatives you've considered

Alternatives:
- Reduce amount of data for rebuild operation (not always possible)
  - move data to other system
  - trim
  - rebuild replica with low data size
  - copy data back
- Recreate PVC, move data to new one and switch from old to new one (blue/green kindof)

**Comment by PhanLe1010** [comment]
Related to the ticket https://github.com/longhorn/longhorn/issues/2765

**Comment by PhanLe1010** [comment]
Btw, if it takes longer than 24h to rebuild the replica, it is singling that the current infrastructure is not quite suitable for this big size volume. The cluster would busy doing rebuilding for a long time here. Would it be better to?
1. Reduce the size of the volume 
2. Increase the network bandwidth in this cluster

**Comment by derekbit** [comment]
@fab-sgnct 
Can you briefly introduce how you use the volume, e.g. if the volume data is overwritten very frequently? Do you have any snapshots of the big volume? v1.5.x has introduced the [fast replica rebuilding](https://longhorn.io/docs/1.5.5/advanced-resources/fast-replica-rebuild/), but it sounds not working in your case.
