### ISSUE TITLE
[TASK] Creation of longhorn-v24.05 branch

### ISSUE THREAD

**Issue by DamiaSan** [longhorn/longhorn#8595]
## What's the task? Please describe

Update to upcoming 24.05 SPDK release

**Comment by DamiaSan** [comment]
PR for spdk branch https://github.com/longhorn/spdk/pull/32 merged

**Comment by DamiaSan** [comment]
`go-spdk-helper` must be updated to use this branch, do I open another ticket?
@innobead

**Comment by innobead** [comment]
Sorry, I missed that. Reopened and please continue on this ticket.

**Comment by DamiaSan** [comment]
PR for `go-spdk-helper` https://github.com/longhorn/go-spdk-helper/pull/114

**Comment by derekbit** [comment]
> PR for go-spdk-helper https://github.com/longhorn/go-spdk-helper/pull/114
@DamiaSan 
Can you separate the v24.05 update and shallow feature into two tickets?

**Comment by DamiaSan** [comment]
> PR for `go-spdk-helper` [longhorn/go-spdk-helper#114](https://github.com/longhorn/go-spdk-helper/pull/114)

#8772
