### ISSUE TITLE
[BUG] system restore stuck because of the volume/PV/PVC restoration

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#8601]
## Describe the bug

in our code https://github.com/longhorn/longhorn-manager/blob/ebace7b56389b017c97876f15b5298d07095b745/controller/system_rollout_controller.go#L1264-L1290
PV restoration will tried to find the Volume first
PVC restoration will tried to find the PV first
But I have moved the Volume restoration out of the parallel restoration
So all 3 resources won't be able to restored and because of the deadlock

## To Reproduce

Create a Volume/PV/PVC and do the system backup and restore

## Expected behavior

All 3 resources should be restored successfully

**Comment by c3y1huang** [comment]
@ChanYiLin , should we have an automation test case to cover this?

**Comment by ChanYiLin** [comment]
Hi @c3y1huang Yes, I will modify the origin test case to include PV and PVC
here: https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_system_backup_restore.py#L121

**Comment by roger-ryao** [comment]
**Verified on master-head 20240530**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/f79dc9bb2bc7907955e8174f774b593b62775640
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/ad7420087dd5e9c706d8462c62cb756812544c55

**The test steps**
https://github.com/longhorn/longhorn/issues/8601#issuecomment-2128506471

**Result Passed**
