### ISSUE TITLE
[BUG] V2 volume offline rebuilding not start

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#8609]
## Describe the bug

Setting `offline-replica-rebuilding`= `enabled` but UI shows disanbled and detach the degraded v2 volume, offline rebuld not started

```bash
> k get setting -A | grep off
longhorn-system   offline-replica-rebuilding                                        enabled                                            true      27m
```

![image](https://github.com/longhorn/longhorn/assets/73337386/765de5fe-1ccd-40d7-86cf-59cec34f191a)

## To Reproduce

1. Install Longhonr and enable v2 data engine , add block disk
2. Make sure setting `offline-replica-rebuilding` = `enabled`
3. Make a v2 volume degrade
4. Detach the v2 volume, offline rebuilding not happen

## Expected behavior

v2 voluime offline rebuilding worked well

## Support bundle for troubleshooting

[supportbundle_d5999747-297b-4a97-a189-846919c7113a_2024-05-21T08-22-30Z.zip](https://github.com/longhorn/longhorn/files/15386821/supportbundle_d5999747-297b-4a97-a189-846919c7113a_2024-05-21T08-22-30Z.zip)

## Environment

 - Longhorn version: master
 - Node config
   - OS type and version: sles sp15
 

## Additional context

N/A

**Comment by derekbit** [comment]
Offline rebuilding is removed in https://github.com/longhorn/longhorn/issues/8442, because @shuo-wu will introduce online rebuilding in v1.7.0.

**Comment by chriscchien** [comment]
Close this ticket as the feature will remove in next feature release
