### ISSUE TITLE
Longhorn System-backup is not working.

### ISSUE THREAD

**Issue by BankarAkanksha17** [longhorn/longhorn#8614]
Hello @Team,

I am taking longhorn system backup through UI every monday but this time its stucked in CreatingVolumeBackups state otherwise it goes in ready state after successfully completing system backup why this is happening can anyone tell?

<img width="938" alt="image" src="https://github.com/longhorn/longhorn/assets/170407001/6d0052b0-990b-4e67-a09e-048c4fa8b75f">

**Comment by c3y1huang** [comment]
It might be hanging at the actual volume backup process.

@BankarAkanksha17 , could you provide the following information?
1. What is the system backup's volume backup policy?
1. Any there any errors in the logs?
1. Is this reproducible?
1. Can you provide the support bundle?

**Comment by BankarAkanksha17** [comment]
System backup's volume backup policy: Always
describe the systembackups.longhorn.io 22-05-2024
<img width="601" alt="image" src="https://github.com/longhorn/longhorn/assets/170407001/647cfa8e-4196-4016-a593-f52e5326d2e8">

3 and 4 point I didn't understand can you bit elaborate.

Thanks,
Akanksha

**Comment by c3y1huang** [comment]
> 3 and 4 point I didn't understand can you bit elaborate.

> 3. Is this reproducible?

Have you tried creating a new system backup to see if the process gets stuck again?

> Can you provide the support bundle?

Support bundle can be created following https://longhorn.io/docs/1.6.1/troubleshoot/support-bundle/.

BTW, you can also check the logs in the longhorn-manager pods to see if there are any errors.

**Comment by BankarAkanksha17** [comment]
> > 3 and 4 point I didn't understand can you bit elaborate.
> 
> > 3. Is this reproducible?
> 
> Have you tried creating a new system backup to see if the process gets stuck again?
> 
> > Can you provide the support bundle?
> 
> Support bundle can be created following https://longhorn.io/docs/1.6.1/troubleshoot/support-bundle/.
> 
> BTW, you can also check the logs in the longhorn-manager pods to see if there are any errors.

I have already check the logs in the longhorn-manager pods so there is nothing and yesterday I took the system backup again and after some time it is successfully completed and now its state is ready.

But, now I want root cause of this sudden abnormal behavior of longhorn. So please guide me to find the reason behind this issue.

Thanks,
Akanksha

**Comment by c3y1huang** [comment]
> I have already check the logs in the longhorn-manager pods so there is nothing and yesterday I took the system backup again and after some time it is successfully completed and now its state is ready.
> But, now I want root cause of this sudden abnormal behavior of longhorn. So please guide me to find the reason behind this issue.

During the _CreatingVolumeBackups_ phase of the system backup, a snapshot is taken and backed up to the remote storage for all volumes (https://github.com/longhorn/longhorn-manager/blob/v1.6.2/controller/system_backup_controller.go#L811-L842). Without the support bundle or logs, its hard to determine the cause of the hiccup.

**Comment by BankarAkanksha17** [comment]
> > I have already check the logs in the longhorn-manager pods so there is nothing and yesterday I took the system backup again and after some time it is successfully completed and now its state is ready.
> > But, now I want root cause of this sudden abnormal behavior of longhorn. So please guide me to find the reason behind this issue.
> 
> During the [_CreatingVolumeBackups_ phase](https://github.com/longhorn/longhorn-manager/blob/v1.6.2/controller/system_backup_controller.go#L423-L433) of the system backup, a snapshot is taken and backed up to the remote storage for all volumes (https://github.com/longhorn/longhorn-manager/blob/v1.6.2/controller/system_backup_controller.go#L811-L842). And then the controller will wait for the volume backups to complete or fail before proceed to the next phase (https://github.com/longhorn/longhorn-manager/blob/v1.6.2/controller/system_backup_controller.go#L753-L809). Without the support bundle, logs or further details, it's hard to determine the cause of the hiccup.
> 
> Do you remember what was the state of the backups? Also, how long was it stuck in this state? And what is your Longhorn version?

the system backup is stuck in this state almost 24 hours and next day morning I again try to take backup but I was facing the same issue and longhorn version that I have been using is 1.5.1 it is just showing in longhorn UI that CreatingVolumeBackups state else nothing is showing.

**Comment by c3y1huang** [comment]
> the system backup is stuck in this state almost 24 hours and next day morning I again try to take backup but I was facing the same issue and longhorn version that I have been using is 1.5.1 it is just showing in longhorn UI that CreatingVolumeBackups state else nothing is showing.

I see. Does the system backup eventually fail with some error? Here are a few things we can check for clues:
1. Check the volume backup status using commands: `kubectl -n longhorn-system get backup`, `kubectl -n longhorn-system describe backup`.
1. Set the log level to _Debug_ and review the logs in ALL longhorn-manager pods for any clues related to the volume backup.

Or, you can provide the support bundle, and we can try to analyze it.

**Comment by BankarAkanksha17** [comment]
> 2\. Set the log level to _Debug_ and review the logs in ALL longhorn-manager pods for any clues related to the volume backup.
<img width="936" alt="image" src="https://github.com/longhorn/longhorn/assets/170407001/fc09d2a1-2667-4cf8-af0e-eaa2799056d4">

today I am facing the same issue and this is the logs from longhorn-manager pod
