### ISSUE TITLE
[IMPROVEMENT] Add setting to configure support bundle timeout for node bundle collection

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#8623]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Following the merge of https://github.com/rancher/support-bundle-kit/pull/109, the support bundle now has a default timeout of 30 minutes for the node bundle collection. However, this duration may not always be sufficient for Longhorn. Therefore, it would be beneficial for Longhorn to offer a setting that allows user to configure this timeout according to their needs.

## Describe the solution you'd like

- A setting to configure support bundle timeout for the node bundle collection

## Describe alternatives you've considered

`None`

## Additional context

`None`

**Comment by c3y1huang** [comment]
We need this to be in v1.7.0 because there will be a version bump for the support-bundle image. And this also needs to be backported.

cc @derekbit @innobead

**Comment by c3y1huang** [comment]
@PhanLe1010 @ejweber @james-munson @shuo-wu @derekbit , do we have an idea of what a reasonable timeout for the node bundle collection would be? Should we keep the default at 30 minutes, or consider extending it?

**Comment by roger-ryao** [comment]
**Verified on master-head 20240529**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/f79dc9bb2bc7907955e8174f774b593b62775640
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/ad7420087dd5e9c706d8462c62cb756812544c55

**The test steps**
https://github.com/longhorn/longhorn-tests/pull/1920


**Result Passed**

- [x] manual test passed
- [x] require/doc : https://github.com/longhorn/website/pull/916/files
- [x] require/manual-test-plan : https://github.com/longhorn/longhorn-tests/pull/1920
