### ISSUE TITLE
[UI][IMPROVEMENT] Tweak some minor UI issues

### ISSUE THREAD

**Issue by a110605** [longhorn/longhorn#8646]
## Describe the improvement you'd like
List some minor UI issues can quickly be improved
1. Add some space bw setting text and icon
<img width="1496" alt="Screenshot 2024-05-27 at 12 54 32 PM" src="https://github.com/longhorn/longhorn/assets/5744158/5dc7a619-dcc5-4e41-9f9b-14c64e3ae3c5">

2. fix strange overlay in orphaned/system backup pages (only happen when no row data)
<img width="1484" alt="Screenshot 2024-05-27 at 12 49 31 PM" src="https://github.com/longhorn/longhorn/assets/5744158/0df34492-b8a1-4179-9f4a-89bb15ca9780">
<img width="1496" alt="Screenshot 2024-05-27 at 1 08 24 PM" src="https://github.com/longhorn/longhorn/assets/5744158/114d58dd-d960-4f1e-b3bd-b012e058c259">

3. Make text in the center of tabs
<img width="1491" alt="Screenshot 2024-05-27 at 12 29 35 PM" src="https://github.com/longhorn/longhorn/assets/5744158/ed325dc7-b241-4b87-b67b-1d3a5c9478da">
<img width="1495" alt="Screenshot 2024-05-27 at 1 05 03 PM" src="https://github.com/longhorn/longhorn/assets/5744158/7e035570-d598-4e8e-9b4b-832974249037">

4. Expand modal context to 100% in backup page
<img width="1490" alt="Screenshot 2024-05-27 at 12 36 22 PM" src="https://github.com/longhorn/longhorn/assets/5744158/b045490b-8942-4320-a9d3-358b90da4516">

5. Align host page operation button to other pages  
<img width="1491" alt="Screenshot 2024-05-27 at 1 07 16 PM" src="https://github.com/longhorn/longhorn/assets/5744158/d5c5fe83-362e-4244-8713-02ed790c3cf7">

6. Improve copy/paste context for backup URL 
<img width="1483" alt="Screenshot 2024-05-27 at 12 40 02 PM" src="https://github.com/longhorn/longhorn/assets/5744158/47270cfe-5f99-4a8a-aa6c-91e71e820281">

7. Add some space bw `attaching` and `spinning icon` in volume page
<img width="175" alt="Screenshot 2024-05-28 at 4 45 46 PM" src="https://github.com/longhorn/longhorn/assets/5744158/0a19d560-f7b1-4bee-bb49-558a3937ef13">

Feel free to add more UI issue in this ticket.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240624**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/7899d66c8633e9cb717049cc12cc1df9be629b7f
- longhorn-ui `master-head` https://github.com/longhorn/longhorn-ui/commit/a6816f3f2926614da62b58735771e171e24516aa


**The test steps**
https://github.com/longhorn/longhorn/issues/8646#issue-2318246077

**Result Passed**
- [x] 1. Add some space bw setting text and icon
- [x] 2. fix strange overlay in orphaned/system backup pages (only happen when no row data)
- [x] 3. Make text in the center of tabs
- [x] 4. Expand modal context to 100% in backup page
- [x] 5. Align host page operation button to other pages  
- [x] 6. Improve copy/paste context for backup URL 
- [x] 7. Add some space bw `attaching` and `spinning icon` in volume page
