### ISSUE TITLE
[BUG] Request for a guide to the longhorn metric

### ISSUE THREAD

**Issue by ZUNOXI** [longhorn/longhorn#8649]
## Describe the bug

Some metrics are not exposed at the endpoint of the manager pod in the longhorn.

## To Reproduce

execute a curl http://longhorn-manager pod ip:port/metrics command

## Expected behavior

We hope to collect all metrics, but the usage figures such as cpu/memory are not exposed at all

- metrics that cannot be collected
```
longhorn_node_cpu_usage_millicpu
longhorn_node_memory_usage_bytes
longhorn_manager_cpu_usage_millicpu
longhorn_manager_memory_usage_bytes
longhorn_instance_manager_cpu_usage_millicpu
longhorn_instance_manager_memory_usage_bytes
```
It seems that only certain metrics are not exposed, so I would like to ask if there are any factors that can affect them.

## Support bundle for troubleshooting

I created longhorn components by creating other namespaces instead of longhorn-system namespaces. I wonder if this affects them.

## Environment

 - Longhorn version: 1.6.1 ver
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Physical Servers 13ea
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 12
 - Node config
   - OS type and version: rhel 8.8
   - Kernel version: 5.15.27 (custom kernel)
   - CPU per node: 48
   - Memory per node: 128GB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 10G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 8 ea

## Additional context

I would like to build a longhorn monitoring system using victoria-metrics and grafana. Metrics in the above example are not being exposed in the longhorn-manager pod. Is there anything I need to check?

**Comment by derekbit** [comment]
cc @PhanLe1010 @c3y1huang

**Comment by c3y1huang** [comment]
So far I haven't been able to reproduce this.
```
> k -n longhorn-system get daemonset longhorn-manager -o yaml | grep image:
        image: longhornio/longhorn-manager:v1.6.1

> k -n longhorn-system get pod -l app=longhorn-manager -o wide
NAME                     READY   STATUS    RESTARTS        AGE     IP          NODE            NOMINATED NODE   READINESS GATES
longhorn-manager-dztsz   1/1     Running   1 (5m56s ago)   6m12s   10.42.3.3   ip-10-0-2-155   <none>           <none>
longhorn-manager-m8tbt   1/1     Running   1 (5m56s ago)   6m12s   10.42.2.5   ip-10-0-2-202   <none>           <none>
longhorn-manager-z2hjs   1/1     Running   1 (5m58s ago)   6m12s   10.42.1.8   ip-10-0-2-242   <none>           <none>

> curl http://10.42.3.3:9500/metrics | grep usage | grep node=
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  409k    0  409k    0     0  14.4M      0 --:--:-- --:--:-- --:--:-- 14.8M
longhorn_disk_usage_bytes{disk="default-disk-ca0300000000",node="ip-10-0-2-155"} 5.627686912e+09
longhorn_instance_manager_cpu_usage_millicpu{instance_manager="instance-manager-87cee96bad122243b3809c6f6e9044a0",instance_manager_type="aio",node="ip-10-0-2-155"} 9
longhorn_instance_manager_memory_usage_bytes{instance_manager="instance-manager-87cee96bad122243b3809c6f6e9044a0",instance_manager_type="aio",node="ip-10-0-2-155"} 1.8210816e+07
longhorn_manager_cpu_usage_millicpu{manager="longhorn-manager-dztsz",node="ip-10-0-2-155"} 4
longhorn_manager_memory_usage_bytes{manager="longhorn-manager-dztsz",node="ip-10-0-2-155"} 4.9676288e+07
longhorn_node_cpu_usage_millicpu{node="ip-10-0-2-155"} 71
longhorn_node_memory_usage_bytes{node="ip-10-0-2-155"} 7.9468544e+08
longhorn_node_storage_usage_bytes{node="ip-10-0-2-155"} 5.627686912e+09
```

@ZUNOXI can you provide the support bundle?
