### ISSUE TITLE
[BUG] System backup failed because backup creation failed.

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#8650]
## Describe the bug
ref: https://github.com/longhorn/longhorn/issues/8601

In system backup e2e tests
Some tests failed because the backup creation failed due to snapshot missing.
We should wait until snapshot is ready before create backup, cause backup creation is one time shot.

ref: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6979/console

in the support bundle, the backup creation failed because of snapshot missing
```
  spec:
    labels:
      longhorn.io/volume-access-mode: rwo
    snapshotName: system-backup-49d05cf04e624d85
    syncRequestedAt: null
  status:
    backupCreatedAt: "null"
    compressionMethod: "null"
    error: could not find snapshot 'system-backup-49d05cf04e624d85' to backup, engine
      'longhorn-testvol-jway75-e-0'
    labels: "null"
```

**Comment by ChanYiLin** [comment]
backport will be put together with ticket: https://github.com/longhorn/longhorn/issues/8629

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `83cd31`) with test [steps](https://github.com/longhorn/longhorn/issues/8650#issuecomment-2139014411)

- Create the Backup, before snapshot is created and readyToUse, the Backup status is Pending with the corresponding information in the .Status.Message
- Run test_system_backup_and_restore_volume_with_backingimage 30 times all [passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7044/).
