### ISSUE TITLE
[BUG] When revision counter is disabled, the engine might choose a replica with a smaller head size to be the source of truth for auto-salvage

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#8659]
## Describe the bug

When the revision counter is disabled, the engine might choose a replica with a smaller head size to be the source of truth for auto-salvage. By design, engine should choose a replica with a bigger head size because that replica might contain the most up-to-date data.

The intended design from [the original LEP](https://github.com/longhorn/longhorn/blob/master/enhancements/20200821-add-revision-counter-disable-support.md#:~:text=Based%20on%20%27volume,as%20%27ERR%27%20mode.):

> 1. Based on 'volume-head-xxx.img' last modified time, to get the latest one and any one within 5 second can be put in the candidate replicas for now.
> 2. Compare the head file size for all the candidate replicas, pick the one with the most block numbers as the 'Source of Truth'.
> 3. Only mark one candidate replica to 'RW' mode, the rest of replicas would be marked as 'ERR' mode.

The actual implementation: 
1. Based on 'volume-head-xxx.img' last modified time, to get the latest one and any one within 5 second can be put in the candidate replicas for now.
2. Mark a random replica from that list as RW and the rest as ERR. This is a bug due to we forget to update the `largestSize` in this [for loop](https://github.com/longhorn/longhorn-engine/blob/e39b7f0313b22d5c435ce57d1442800999a0f4ac/pkg/controller/control.go#L649-L650) 

## To Reproduce

1. Create a cluster of 3 nodes
1. In Longhorn UI, disable scheduling for node-1 so that Longhorn doesn't schedule replicas to node-1
1. Create a volume of the name `testvol` with 2 replicas, 2GB, disable revision counter set to true. Note that the replica will be scheduled to node-2 and node-3
1. Attach the volume to node-1
1. SSH into node-2 and node-3
1. Write 4K to volume-head of replica on node-2 : `dd if=/dev/random of=volume-head-000.img bs=4k count=1 oflag=direct conv=notrunc`
1. Within 5s of the previous step, write 8K to volume-head of replica on node-3 : `dd if=/dev/random of=volume-head-000.img bs=4k count=2 oflag=direct conv=notrunc`
1. Note that the 2 writes must be within 5s
1. Crash instance-manager on node-2 and node-3
1. Observer that sometimes Longhorn uses the replica with the smaller head size (replica on node-1) as the source of truth and rebuilds the other replica from it. If this does not happen repeat the test a few times. 

## Expected behavior

By design, engine should always choose a replica with a bigger head size because that replica might contain the most up-to-date data.

## Environment

 - Longhorn version: all Longhorn < v1.7.0

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-engine `15c1e8`)

Repeat test [steps](https://github.com/longhorn/longhorn/issues/8659#issue-2322103209) 10 times,the voume always choose a replica with a bigger head size to rebuild it's all replicas.

**Comment by shuo-wu** [comment]
The issue fix based on the original LEP is good. But what I want to notice is that we introduced filesystem trim after this LEP, which means the head file with a smaller size may be the latest one. 
For now I don't have a better solution for it. Let's just keep the current implementation.
