### ISSUE TITLE
[FEATURE] v2 volume supports snapshot checksum

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8666]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

v2 volume supports snapshot checksum as v1 volume.
This is part of the delta rebuilding for v2 volume.

## Describe the solution you'd like

- Asynchronous snapshot checksum calculation does not block the snapshot creation.
- Add checksum info to the snapshot metadata. (ex: immutable/mutable metadata)

**Comment by derekbit** [comment]
Move it to v1.8.0 but best effort in v1.7.0.

cc @DamiaSan @innobead

**Comment by DamiaSan** [comment]
Blob layer development steps:
- [ ] add `spdk_crc64_snapshot` function in `include/spdk/crc64.h`; the type will be crc64 iso reflected that should be the same actually used in Longhorn v1
- [ ] refactor shallow copy functions for iterating over snapshot clusters for usage in checksum computing
- [ ] compute checksum
- [ ] store checksum

**Comment by DamiaSan** [comment]
PR https://github.com/longhorn/spdk/pull/35

**Comment by DamiaSan** [comment]
subtask #9709 for go-spdk-helper implementation

**Comment by DamiaSan** [comment]
New PR for SPDK https://github.com/longhorn/spdk/pull/38 to be merged in the new `longhorn-v24.09` branch

**Comment by derekbit** [comment]
@DamiaSan Don't forget to move it to `Review`

**Comment by derekbit** [comment]
https://github.com/longhorn/spdk/pull/35

**Comment by derekbit** [comment]
@DamiaSan 
Thanks for the correction.
Please update the PR links in https://github.com/longhorn/longhorn/issues/8666#issuecomment-2236937867. Thank you.

**Comment by derekbit** [comment]
@DamiaSan 
Let's close this one, use https://github.com/longhorn/longhorn/issues/5573 instead.
