### ISSUE TITLE
[BUG] `toomanysnapshots` UI message displays incorrect snapshot count

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#8668]
## Describe the bug

When I test https://github.com/longhorn/longhorn/issues/6560 . I found a minor issue where I created only 100 snapshots, but the UI displays the message: "Snapshots count is 101, over the warning threshold of 100." 
After discussing with Andy, we need to check the backend to determine why the snapshot number is reported as one extra. 

## To Reproduce

1. Create 100 snapshot
2. See `toomanysnapshots UI message`

## Expected behavior

The snapshot count should match the number of snapshots created.

## Support bundle for troubleshooting

[supportbundle_c2c056ed-e625-4da1-bf61-336f4ecb746e_2024-05-30T04-01-30Z.zip](https://github.com/longhorn/longhorn/files/15494123/supportbundle_c2c056ed-e625-4da1-bf61-336f4ecb746e_2024-05-30T04-01-30Z.zip)

## Environment

 - Longhorn version: `master-head`
 - Impacted volume (PV): `pvc-9c781422-5821-4c5d-99e8-4ecd1f4cd5c1`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): `Kubectl`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: `v1.28.9+k3s1`
   - Number of control plane nodes in the cluster: `1`
   - Number of worker nodes in the cluster: `3`
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): `AWS`
 - Number of Longhorn volumes in the cluster: `1`

## Additional context

https://github.com/longhorn/longhorn/issues/6560

cc @a110605 @longhorn/dev

**Comment by ejweber** [comment]
The line that generates the condition is here:

https://github.com/longhorn/longhorn-manager/blob/7296f4603847bcdbb231b86973ad191c50b15e20/controller/volume_controller.go#L1720

Looks like we just count the number of snapshots in `engine.Status.Snapshots`, but that includes `volume-head`. So you created 100 snapshots, but there are 101 by the reckoning of this code (100 + `volume-head`). This is probably pretty quick to fix up, but we need to confirm the context:

- For this purpose, should `volume-head` be considered a snapshot? Probably not.
- Is there any other place we use this calculation?

**Comment by ejweber** [comment]
The replicas do a similar calculation when checking for adherence to snapshot-max-count. They ignore `volume-head`. We should probably do the same here. (It's only a warning anyway, so really, we just need to display whatever number seems most natural.)

https://github.com/longhorn/longhorn-engine/blob/15c1e891387ba650b4a8b5a6398c7426e8d7ebff/pkg/replica/replica.go#L1407-L1425

**Comment by roger-ryao** [comment]
**Verified on master-head 20240617**

- longhorn master-head https://github.com/longhorn/longhorn/commit/9bdd9ccc191df987e51946acad9eac0327e4f414
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/1cda0e761f01f8a933f77474a30df22796d25342

**The test steps**
https://github.com/longhorn/longhorn/issues/8668#issuecomment-2150256851

**Result Passed**

1. Manual test passed
2. Regression test passed 
https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/946/testReport/tests/test_basic/test_settings/
