### ISSUE TITLE
[BUG] Volume stuck in attaching/detaching loop forever, no revert or restore allow, you will lost the entire volume! 

### ISSUE THREAD

**Issue by liyimeng** [longhorn/longhorn#8669]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

It is very frustrated that a workload stuck in pending state because the underneath storage is unavailable when a SINGLE node failed. This is not longhorn is supposed to work. 

Not sure if this is a bug or an improvement request. In my cluster, I have a RWX volume scheduled to a node, which happen to be problematic and causing the instance-manager failed to start up.  For this reason, the volume never get attached.  I would expect longhorn will re-schedule and re-attach the volume to another node after a couple of failing attempts. However, it is not the case. Longhorn keep trying on the same node perseveringly, and my workload never get online :(

What even worse is that the bad behaviour instance manager might screw the volume and cause data lost, which is unfortunately one of the case in my cluster.
   
## Describe the solution you'd like

I suggest update the scheduler, after a setting number of failure, longhorn should rescheduling volume to mount on anther node, if user has not set data locality explicitly.   

 Longhorn should be more tolerate on node failure, able to make a another schedule and bring back use workload.
## Describe alternatives you've considered

Manually invention, for volume rescheduling

**Comment by liyimeng** [comment]
I would consider this as a serious bug. When a volume stuck in attaching/detaching loop. It is almost 100% that you lost your data, you entire volume, and user have no chance to revert to an old snap or recovery from backup. Longhorn refuse doing anything except keep it crazy trying.

**Comment by liyimeng** [comment]
@innobead @shuo-wu @joshimoo @PhanLe1010 I suggest to take a look into this one. This is probably worst ever scenario you can have to a storage system.

**Comment by PhanLe1010** [comment]
Could you send us a support bundle to `longhorn-support-bundle@suse.com` with the name of the RWX volume @liyimeng ? 

cc @c3y1huang, our community coordinator for this sprint

**Comment by shuo-wu** [comment]
Not sure why the RWX volume won't be restarted on another node automatically. We need to check the support bundle. And this issue should be improved by https://github.com/longhorn/longhorn/issues/6205, which is already in progress.

As for the data lost, it depends on if the replica directory is still available. As long as the directory is there, you can still launch a volume manually without Longhorn system in the worst case: https://longhorn.io/docs/1.6.2/advanced-resources/data-recovery/export-from-replica/

**Comment by derekbit** [comment]
> Not sure why the RWX volume won't be restarted on another node automatically. We need to check the support bundle. And this issue should be improved by #6205, which is already in progress.

`problematic and causing the instance-manager failed to start up` -> Does it cause the RWX volume is unable to restart?

**Comment by liyimeng** [comment]
> Could you send us a support bundle to `longhorn-support-bundle@suse.com` with the name of the RWX volume @liyimeng ?
> 
> cc @c3y1huang, our community coordinator for this sprint



> Could you send us a support bundle to `longhorn-support-bundle@suse.com` with the name of the RWX volume @liyimeng ?
> 
> cc @c3y1huang, our community coordinator for this sprint

Unfortunately, we were under pressure in recovery the workload, missing the chance to collect the bundle.  However, I believe it will be reproducible, will setup a lab environment to re-produce the problem, and collect bundle from there. 

Will update when it is available.

**Comment by liyimeng** [comment]
> Not sure why the RWX volume won't be restarted on another node automatically. We need to check the support bundle. And this issue should be improved by #6205, which is already in progress.
> 
> As for the data lost, it depends on if the replica directory is still available. As long as the directory is there, you can still launch a volume manually without Longhorn system in the worst case: https://longhorn.io/docs/1.6.2/advanced-resources/data-recovery/export-from-replica/

@shuo-wu thanks, good to know this. Will try it if I can re-produce the problem.
