### ISSUE TITLE
Change default-setting directory inside the container to /var/lib/longhorn-setting

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#868]
If it uses `/var/lib/longhorn/setting`, since we will move the default to `/var/lib/longhorn`, the recurring mount would happen and containerd will report error like following:

>Error: failed to start container "longhorn-manager": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/ae9afc3f-04ee-11ea-9ca3-f23c91575520/volumes/kubernetes.io~configmap/longhorn-default-setting\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/f95f6f4a240e24e2ca9f4913dc71f564ffbfcdf577e3d1367427152495c340b1\\\" at \\\"/var/lib/docker/aufs/mnt/f95f6f4a240e24e2ca9f4913dc71f564ffbfcdf577e3d1367427152495c340b1/var/lib/longhorn/setting\\\" caused \\\"no such file or directory\\\"\"": unknown

**Comment by yasker** [comment]
Need to test default setting feature to make sure it works.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Default setting feature works.
