### ISSUE TITLE
[BUG] Unable to attach or mount volumes after systemctl restart k3s

### ISSUE THREAD

**Issue by paf91** [longhorn/longhorn#8680]
## Describe the bug

Pods with mounted pvc get stuck and cant start after the kubelet is restarted and longhorn is helm chart v1.4.2 version.
Pods stuck in longhorn-system also:
share-manager-pvc

![image](https://github.com/longhorn/longhorn/assets/12195041/3b26fbd3-8fb5-4e99-8f21-08f861447271)

Can't update helm to 1.5.x because of this, probably

## To Reproduce

systemctl restart k3s

try to restart start pod and mount a pvc

## Expected behavior

Pod succesfully starts and pvc mounts

## Support bundle for troubleshooting
Can't create support bundle since pod cant start longhorn-support-bundle-manager-support-bundle
```
Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    12m                default-scheduler  Successfully assigned longhorn-system/longhorn-support-bundle-manager-support-bundle-2024-05-31ts2vh5
  Warning  FailedMount  81s (x5 over 10m)  kubelet            Unable to attach or mount volumes: unmounted volumes=[kube-api-access-jnbv6], unattached volumes=[kube-api-access-jnbv6]: timed out waiting for the condition
```

## Environment

 - Longhorn version: helm chart v1.4.2
 - Impacted volume (PV): unmounted volumes=[host-proc lib-modules kube-api-access-nh4h8 host-dev host-sys]
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.26.4+k3s1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 1 (same node as control)
 - Node config
   - OS type and version: Ubuntu 22.04.2 LTS (Jammy Jellyfish)
   - Kernel version: 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
   - CPU per node: 32
   - Memory per node: 64Gb
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 10Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 13

**Comment by derekbit** [comment]
A support bundle is appriciated.

**Comment by paf91** [comment]
@derekbit

Can't create support bundle since pod cant start longhorn-support-bundle-manager-support-bundle

```
Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    12m                default-scheduler  Successfully assigned longhorn-system/longhorn-support-bundle-manager-support-bundle-2024-05-31ts2vh5
  Warning  FailedMount  81s (x5 over 10m)  kubelet            Unable to attach or mount volumes: unmounted volumes=[kube-api-access-jnbv6], unattached volumes=[kube-api-access-jnbv6]: timed out waiting for the condition
```
