### ISSUE TITLE
[BUG]Upgrade from 1.4.2 to 1.5.5 fails. longhorn-manager pods are stuck at init

### ISSUE THREAD

**Issue by gcyre** [longhorn/longhorn#8681]
## Describe the bug

We tried to upgrade Longhorn to 1.5.5 from 1.4.2 and the longhorn-manager pods are stuck in init. 

Kubernetes version: v1.25.20+rke2r1

## To Reproduce

Our instance has been upgraded several times and we needed to follow a couple of workarounds to get the upgrade to work. 
[6246](https://github.com/longhorn/longhorn/issues/6246#issuecomment-1624944396)
[6246](https://github.com/longhorn/longhorn/issues/6246#issuecomment-1625065311)

```
helm upgrade longhorn longhorn/longhorn --namespace longhorn-system --version 1.5.5 --set global.cattle.psp.enabled=false
helm mapkubeapis longhorn --namespace longhorn-system
helm repo update
helm template longhorn longhorn/longhorn --version 1.5.5
```

After all this the Helm upgrade succeeded but the longhorn-manager pods are sitting in `Init:0/1`
```
longhorn-manager-5nm62                                            0/1     Init:0/1    0              41h
longhorn-manager-7rllw                                            0/1     Init:0/1    0              41h
longhorn-manager-bdzpb                                            0/1     Init:0/1    0              41h
longhorn-manager-hcsp7                                            0/1     Init:0/1    0              41h
longhorn-manager-q2jct                                            0/1     Init:0/1    0              41h
longhorn-manager-qc4gq                                            0/1     Init:0/1    0              41h
longhorn-manager-v8v4m                                            0/1     Init:0/1    0              41h
longhorn-manager-w575p                                            0/1     Init:0/1    0              41h
longhorn-manager-xkm9z                                            0/1     Init:0/1    0              41h
longhorn-manager-zsfnl                                            0/1     Init:0/1    0              41h
```

logs from one of the pods 

```
kubectl -n longhorn-system logs longhorn-manager-zsfnl  -c wait-longhorn-admission-webhook
waiting
waiting
...
```

from on of the longhorn-manager pods

```
kubectl -n longhorn-system exec -it longhorn-manager-zsfnl  -c wait-longhorn-admission-webhook -- /bin/bash
root           1       0  0 May29 ?        00:00:40 sh -c while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" -k https://longhorn-admission-webhook:9443/v1/healthz) != "200" ]; do echo waiting; sleep 2; done
```

From longhorn-manager daemonset

```
  Init Containers:
   wait-longhorn-admission-webhook:
    Image:      longhornio/longhorn-manager:v1.4.2
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
      while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" -k https://longhorn-admission-webhook:9443/v1/healthz) != "200" ]; do echo waiting; sleep 2; done
    Environment:  <none>
    Mounts:       <none>
```

## Expected behavior

Clean upgrade to 1.5.5 

## Environment

 - Longhorn version:  1.4.2
 - Impacted volume (PV): Volumes are functioning but cannot add any volumes
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:v1.25.10+rke2r1
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 10
 - Node config
   - OS type and version: Ubuntu 20.04
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by gcyre** [comment]
I've also asked about this in the Slack community

**Comment by derekbit** [comment]
Can you show us the log of the webhook pods?

**Comment by gcyre** [comment]
hi @derekbit the only thing in the logs is `waiting` see attached
```kubectl -n longhorn-system logs longhorn-manager-5nm62  -c wait-longhorn-admission-webhook```
[admission-webhook.txt](https://github.com/user-attachments/files/15521404/admission-webhook.txt)

**Comment by gcyre** [comment]
I don't know why its still using 1.4.2, this was the state after the helm upgrade finished. I tried to update the daemonset to use 1.5.5 but it did not make any difference. 

The manager pods were still stuck at `Init:0/1` and the `wait-longhorn-admission-webhook` pods were still just logging `waiting`

**Comment by gcyre** [comment]
@derekbit do you have any suggestions for getting the longhorn-manager pods out of the init state? Our cluster is in a weird state and we can't perform any operations on the volumes

**Comment by derekbit** [comment]
@gcyre Sorry. I missed the issue before. Does the issue remain?
