### ISSUE TITLE
[BUG] test_csi_encrypted_block_volume failed on master pipeline

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#8688]
## Describe the bug

`test_csi_encrypted_block_volume`, `test_csi_encrypted_migratable_block_volume` failed on master [pipeline](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/934/)

probably related to https://github.com/longhorn/longhorn-tests/pull/1672 because use longhorn-test v1.6.x image on longhorn master-head images, test case [test_csi_encrypted_block_volume](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6998/testReport/tests/test_csi/test_csi_encrypted_block_volume) passed.

## To Reproduce

Run `test_csi_encrypted_block_volume`, `test_csi_encrypted_migratable_block_volume` on master pipeline.

## Expected behavior

Test case passed

## Additional context

N/A

**Comment by ChanYiLin** [comment]
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7028/testReport/tests/test_csi/
run the test `test_csi_encrypted_block_volume` , it passed.
I am guessing the e2e was affected when running with other tests

**Comment by ChanYiLin** [comment]
Run `test_csi_encrypted_block_volume` 10 times, all PASSED 
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7029/testReport/tests/test_csi/

**Comment by ChanYiLin** [comment]
Run test_csi.py all PASSED.
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7034/

**Comment by yangchiu** [comment]
This issue should already been fixed by https://github.com/longhorn/longhorn-tests/pull/1945. Close it for now.
