### ISSUE TITLE
[CI] fail to build 1.6.0 longhorn engine images

### ISSUE THREAD

**Issue by hchyue** [longhorn/longhorn#8694]
Removing intermediate container 9badfa2b0064
 ---> 4532d3f1e212
Step 43/47 : RUN cd /go/src/github.com/longhorn &&     git clone https://github.com/longhorn/longhorn-instance-manager.git &&     cd longhorn-instance-manager &&     go build -o ./longhorn-instance-manager &&     cp -r integration/rpc/ ${DAPPER_SOURCE}/integration/rpc/ &&     install longhorn-instance-manager /usr/local/bin
 ---> Running in 9bd7fbe5a844
Cloning into 'longhorn-instance-manager'...
go: downloading go1.22.2 (linux/arm64)
**cp: cannot stat 'integration/rpc/': No such file or directory**
The command '/bin/sh -c cd /go/src/github.com/longhorn &&     git clone https://github.com/longhorn/longhorn-instance-manager.git &&     cd longhorn-instance-manager &&     go build -o ./longhorn-instance-manager &&     cp -r integration/rpc/ ${DAPPER_SOURCE}/integration/rpc/ &&     install longhorn-instance-manager /usr/local/bin' returned a non-zero code: 1
FATA[0728] exit status 1
make: *** [Makefile:11：ci] 错误 1

![image](https://github.com/longhorn/longhorn/assets/69490488/55f77dbe-601e-40f9-b25d-6069a6a5db6c)

longhorn engine version: v1.6.0
Docker version 19.03.15, build 99e3ed8
os: Linux localhost.localdomain 4.19.90-24.4.v2101.ky10.aarch64 #1 SMP Mon May 24 14:45:37 CST 2021 aarch64 aarch64 aarch64 GNU/Linux

how to fix it ?

**Comment by derekbit** [comment]
cc @FrankYang0529

**Comment by FrankYang0529** [comment]
The reason is that we already collect rpc files to https://github.com/longhorn/types. We may need to update [this line](https://github.com/longhorn/longhorn-engine/blob/b083139b6d4daffb27c85f2e52ad6430267db558/Dockerfile.dapper#L139) as following:

```
    git clone https://github.com/longhorn/longhorn-instance-manager.git -b v1.6.0 && \
```
