### ISSUE TITLE
[IMPROVEMENT] environment_check.sh should check for the iscsi_tcp kernel module

### ISSUE THREAD

**Issue by tserong** [longhorn/longhorn#8697]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

It would be helpful if the Environment Check Script mentioned in the docs (https://longhorn.io/docs/1.6.2/deploy/install/#using-the-environment-check-script) checked for the `iscsi_tcp` kernel module, because even if `open-iscsi` is installed, it's possible for that module to not be present. For example:

```
master:~ # curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/scripts/environment_check.sh | bash
[INFO]  Required dependencies 'kubectl jq mktemp sort printf' are installed.
[INFO]  All nodes have unique hostnames.
[INFO]  Waiting for longhorn-environment-check pods to become ready (0/1)...
[INFO]  All longhorn-environment-check pods are ready (1/1).
[INFO]  MountPropagation is enabled
[INFO]  Checking kernel release...
[INFO]  Checking iscsid...
[INFO]  Checking multipathd...
[INFO]  Checking packages...
[INFO]  Checking nfs client...
[INFO]  Cleaning up longhorn-environment-check pods...
[INFO]  Cleanup completed.

master:~ # lsmod|grep iscsi
scsi_transport_iscsi   192512  1
iscsi_ibft             12288  0
iscsi_boot_sysfs       20480  1 iscsi_ibft
scsi_mod              344064  4 sd_mod,scsi_transport_iscsi,libata,sg

master:~ # modprobe iscsi_tcp
modprobe: FATAL: Module iscsi_tcp not found in directory /usr/lib/modules/6.9.3-1-default
```

This can happen on SLES and openSUSE systems when using minimal VM images where the `kernel-default-base` package is installed as opposed to `kernel-default` (see https://www.suse.com/support/kb/doc/?id=000021147).

## Describe the solution you'd like

This should do it:

```diff -u environment_check.sh.orig environment_check.sh
--- environment_check.sh.orig	2024-06-04 07:48:37.743329009 +0200
+++ environment_check.sh	2024-06-04 07:47:59.136662354 +0200
@@ -332,6 +332,7 @@
       return 1
     fi
   fi
+  check_kernel_module ${pod} CONFIG_ISCSI_TCP iscsi_tcp
 }
 
 check_multipathd() {
```

It's probably worth also adding a note to the docs that on SUSE-based distros you want `kernel-default` installed, not `kernel-default-base`.

## Describe alternatives you've considered

Update longhorn-iscsi-installation.yaml to install `kernel-default` on SUSE-based distros to make sure the module is actually present. I'm somewhat wary of this though, because installing a different kernel package requires a reboot. I think it's better to leave installing/updating kernel packages for the user to do manually.

## Additional context

N/A

**Comment by tserong** [comment]
## Pre Ready-For-Testing Checklist
* [x] Where is the reproduce steps/test steps documented?
The reproduce steps/test steps are at:
1. Install a SLES or openSUSE system (can be a VM) with `kernel-default-base` instead of `kernel-default`. Verify that `modprobe iscsi_tcp` _fails_ with "Module iscsi_tcp not found"
2. Run the old version of `environment_check.sh` on the system, note that it succeeds.
3. Run the new version of `environment_check.sh` on the system, verify that it flags "[ERROR] kernel module iscsi_tcp is not enabled on master"
4. Install `kernel-default` on the system, re-run the new version of environment_check.sh and verify that it succeeds.

* [x] Does the PR include the explanation for the fix or the feature?

* [x] Have the backend code been merged (Manager, Engine, Instance Manager, BackupStore etc) (including `backport-needed/*`)?
The PR is at https://github.com/longhorn/longhorn/pull/8705

* [x] **If labeled: require/doc** Has the necessary document PR submitted or merged (including `backport-needed/*`)?
The documentation issue/PR is at https://github.com/longhorn/website/pull/920

* [x] **If labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at
See reproduce/test steps above.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240620**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/f5109e31d29f0ad0dbcdab6870afa1916796908e

**The test steps**
https://github.com/longhorn/longhorn/issues/8697#issuecomment-2167325572

**Result Passed**

1. Create a cluster via https://github.com/longhorn/longhorn-tests/tree/master/test_framework/terraform/aws/sles
2. Check `iscsi_tcp` via CLI `sudo lsmod|grep iscsi`
3. By default `iscsi_tcp` is not enabled
4. Enable it using CLI `sudo modprobe iscsi_tcp`
5. The new version of `environment_check.sh` will verify whether `iscsi_tcp` is enabled or not.

Miscellaneous
1. If you want to use a system with `kernel-default-base`, follow these steps:
    1. Run `sudo zypper refresh`
    2. Search for the kernel package: `sudo zypper search kernel-default`
    3. Install the kernel package: `sudo zypper install kernel-default-base`
    4. Reboot the system: `sudo reboot`
    6. After installing `kernel-default-base`, if you run `sudo modprobe iscsi_tcp`, you will encounter the following error:

       ```console
       modprobe: FATAL: Module iscsi_tcp not found in directory /lib/modules/5.14.21-150500.55.65-default
       ```
