### ISSUE TITLE
[IMPROVEMENT] Informative warning message for the failed backup/restore lock acquisition

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8713]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

When a backup or restore process fails to acquire a lock, user can see the error message 
```
rpc error: code = Unknown desc = failed lock backupstore/volumes/97/d4/pvc-3f3bd369-2ab6-43ea-aff5-c8455a1dca9a/locks/lock-dae2f8ef7539448d.lck type 1 acquisition
```

The backup or restore is doable after the lock is expired. However, the message is not informative, so user is unable to figure out the next step and clearly understand status of the backup/restore.

The purpose of the ticket is to make the message clearer to users.

## Additional context

https://suse.slack.com/archives/C02BW9KEJHG/p1717599567217309

**Comment by derekbit** [comment]
cc @ChanYiLin

**Comment by ChanYiLin** [comment]
Will need to update vendor
- longhorn-engine
- backing-image-manager
- longhorn-instance-manager
- longhorn-manager

**Comment by roger-ryao** [comment]
- longhorn v1.8.0-dev-20240922 https://github.com/longhorn/longhorn/commit/ddfda37472d9b4d877c2a60663bb176ae3828825

**The test steps**
https://github.com/longhorn/longhorn/issues/8713#issuecomment-2326482937

**Result**

When following the steps, the expected error message is returned:

```bash
proxyServer=10.42.1.59:8501 destination=10.42.2.27:10001: failed to backup snapshot d17037bb-c087-447a-a77a-a24a48958b74 to backup-9931f332d6aa4877: rpc error: code = Internal desc = failed to create backup: failed to create backup to nfs://longhorn-test-nfs-svc.default:/opt/backupstore for volume vol-0: rpc error: code = Unknown desc = failed to acquire lock backupstore/volumes/9e/c7/vol-0/locks/lock-75a99354dc9d4801.lck when performing backup create/restore, please try again later.
```
