### ISSUE TITLE
Systembackup restore fail - FailedCreating: Job 

### ISSUE THREAD

**Issue by n00bsi** [longhorn/longhorn#8716]
## Describe the bug

Restore of Systembackup fail

the Backup Target is a CIFS share

found there:  system-backup.zip and system-backup.cfg

## To Reproduce

Created a systembackup ( Settings -> Systembackup -> create )
Deteach all Volumes
Restore ( Settings -> Systembackup -> select backup -> restore )

![image](https://github.com/longhorn/longhorn/assets/66995098/926fd072-6ca5-4576-82cf-ed7ab70e2a56)

## Expected behavior

Target is mariadb pod, create backup, destry the db
then be able to restore the DB from Backup

## Environment

 - Longhorn version: 1.6.2 
 - Impacted volume (PV):  pvc-af8b99dd-506a-4be0-a000-b109c425adc9
 - Installation method: Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: OpenShift 4.15.5
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: Red Hat Enterprise Linux CoreOS 415.92.202405201956-0
   - Kernel version: 5.14.0-284.67.1.el9_2.x86_64
   - CPU per node: 4
   - Memory per node: 16GB ControlPlane / 8 GB Worker
   - Disk type (e.g. SSD/NVMe/HDD): vDisk
   - Network bandwidth between the nodes (Gbps): 10
 - Underlying Infrastructure: VMWare
 - Number of Longhorn volumes in the cluster: 3

**Comment by c3y1huang** [comment]
Looks like there is a permission issue. Could you check [forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can’t set finalizers on: …”?](https://sdk.operatorframework.io/docs/faqs/#after-deploying-my-operator-why-do-i-see-errors-like-is-forbidden-cannot-set-blockownerdeletion-if-an-ownerreference-refers-to-a-resource-you-cant-set-finalizers-on-)

- https://docs.openshift.com/container-platform/4.15/architecture/admission-plug-ins.html
- https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement
- https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/gc/gc_admission.go#L149
