### ISSUE TITLE
[IMPROVEMENT] Always update the built-in installed system packages when building component images

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#8721]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Let's make sure the builtin installed system packages will be always up to date when we are building the component images. This can prevent any unnecessary vulnerability reports which are not relevant.

```shell
zypper ref
zypper update -y
```

**Comment by c3y1huang** [comment]
TODO:
- [ ] longhorn-cli
- [ ] longhorn-engine
- [ ] longhorn-instance-manager
- [ ] longhorn-manager
- [ ] longhorn-share-manager
- [ ] longhorn-ui

**Comment by roger-ryao** [comment]
**Verified on master-head 20240618**

- longhorn-engine `master-head` https://github.com/longhorn/longhorn-engine/commit/0326a55ae2a61b67f21cb14664fe1467d6b6f786
- longhorn-instance-manager `master-head` https://github.com/longhorn/longhorn-instance-manager/commit/23380ad90d25951c30739b2ebce822b41bda10dc
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/58185109614f31649b4ec0c709a699ff325564c9
- longhorn-share-manager `master-head` https://github.com/longhorn/longhorn-share-manager/commit/383540409dcbb2153fbcacedc814d3220065c0c3
- longhorn-ui `master-head` https://github.com/longhorn/longhorn-ui/commit/ea50c84bd2a133873d63dc793322f481fb45f29c
- backing-image-manager `master-head` https://github.com/longhorn/backing-image-manager/commit/2ab49b9fce282fc0f8e0a0e95d8eedff994dc3f0

**The test steps**
https://github.com/c3y1huang/longhorn-tests/blob/master/docs/content/manual/release-specific/v1.7.0/test-build-image-package-up-to-date.md

**Result Passed**

- [x] longhorn-cli: test pr : https://github.com/longhorn/cli/pull/14
- [x] longhorn-engine : `docker run --entrypoint bash --user root -it longhornio/longhorn-engine:master-head`
- [x] longhorn-instance-manager : `docker run --entrypoint bash --user root -it longhornio/longhorn-instance-manager:master-head`
- [x] longhorn-manager : `docker run --entrypoint bash --user root -it longhornio/longhorn-manager:master-head`
- [x] longhorn-share-manager : `docker run --entrypoint bash --user root -it longhornio/longhorn-share-manager:master-head`
- [x] longhorn-ui : `docker run --entrypoint bash --user root -it longhornio/longhorn-ui:master-head`
- [x] backing-image-manager : `docker run --entrypoint bash --user root -it longhornio/backing-image-manager:master-head`
