### ISSUE TITLE
Longhorn stuck on Removing

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#873]
Error: `Longhorn-ui; waiting on helm-controller_c-pcr64`

1. Launched Longhorn App
2. Longhorn Running
3. Deleted Longhorn App

Rancher | v2.2.9
-- | --
User Interface | v2.2.98
Helm | v2.10.0-rancher11
Machine | v0.15.0-rancher8-1

The easiest way is to just rebuild the cluster

**Comment by yasker** [comment]
We cannot reproduce this issue, but many Helm related fixes have been added to Rancher 2.3. Can you try to upgrade the Rancher to v2.3.2 and try again?

**Comment by ainiml** [comment]
I just redeployed the cluster and deployments. Can't reproduce this anymore.
