### ISSUE TITLE
[UI][TASK]  Support volume cloning using UI

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#8741]
This is a part of the ticket [[FEATURE] Volume cloning enhancement #2907](https://github.com/longhorn/longhorn/issues/2907)

Some ideas:
- [x] In the create volume UI, users should be able to create a volume with the data source pointing to another volume or a Longhorn snapshot
- [x]  Users can click on any volume and select clone a new volume from that volume
- [x]  Users can click mutliple volumes to clone them (bulk action for volume clone)
- [x] Users can click on any snapshot and select clone a new volume from that snapshot 

cc @a110605

**Comment by a110605** [comment]
Based on above idea, requirements are
- Add `data source` field with dropdown let user choose create this volume from backing image / snapshot / other volumes 
- Add new option named `Clone Volume` in volume table operation dropdown.
- Add new option named `Clone` in snapshot dropdown.
<img width="876" alt="Screenshot 2024-06-13 at 10 13 38 AM" src="https://github.com/longhorn/longhorn/assets/5744158/9c3f68ed-6939-4311-bddb-2fbe05b6dfb2">
 
@PhanLe1010 create volume from `backing image / snapshot / other volumes` are mutually exclusive(), right?

**Comment by PhanLe1010** [comment]
Adding `highlight` label because this is part of the highlighted ticket https://github.com/longhorn/longhorn/issues/2907

Please correct me if this is wrong @innobead @derekbit

**Comment by PhanLe1010** [comment]
> In create volume modal, add data source field with two dropdowns for user to choose source types (backing image, snapshot or other volumes) and the source items.
> @PhanLe1010 create volume from backing image / snapshot / other volumes sources are mutually exclusive (can only choose one), right?

@a110605  A volume can set both:
1. Backing Image
2. Datasource (another volume/a snapshot)

So can we keep the `backing image` field the same and create a dropdown for Datasource (another volume/a snapshot) ?


> Add new option named Clone Volume in volume table operation dropdown.

Yes, this one looks good!

> Add new option named Clone in snapshot dropdown.

Yes, this one looks good

**Comment by a110605** [comment]
> > In create volume modal, add data source field with two dropdowns for user to choose source types (backing image, snapshot or other volumes) and the source items.
> > @PhanLe1010 create volume from backing image / snapshot / other volumes sources are mutually exclusive (can only choose one), right?
> 
> @a110605 A volume can set both:
> 
> 1. Backing Image
> 2. Datasource (another volume/a snapshot)
> 
> So can we keep the `backing image` field the same and create a dropdown for Datasource (another volume/a snapshot) ?

Sure, let's keep original backing image field and add another data source dropdowns to choose volume or snapshot.

Could you also provide the API change for above three actions that I can know how to call them from UI?

**Comment by PhanLe1010** [comment]
> Could you also provide the API spec for above three UI changes that I can know how to call API?

Surely, you can use this volumeCreate API https://github.com/longhorn/longhorn-manager/blob/6d936dc7e190110a8c9b216e0b4455e730456467/api/router.go#L70-L71 and pass in the parameter volume.DataSource https://github.com/longhorn/longhorn-manager/blob/6d936dc7e190110a8c9b216e0b4455e730456467/api/model.go#L38-L39 . This is an example of how Longhorn CSI plugin use the API:
1. Set the parameter in the json payload https://github.com/longhorn/longhorn-manager/blob/6d936dc7e190110a8c9b216e0b4455e730456467/csi/util.go#L207-L214
2. Make the call https://github.com/longhorn/longhorn-manager/blob/6d936dc7e190110a8c9b216e0b4455e730456467/csi/controller_server.go#L237

**Comment by a110605** [comment]
> 2\. https://github.com/longhorn/longhorn-manager/blob/6d936dc7e190110a8c9b216e0b4455e730456467/csi/controller_server.go#L237

@PhanLe1010 , double confirm to just pass snapshot name or volume name in `dataSource` field in `POST /v1/volumes` API.
```
{
...params
"dataSource": [snapshot name or volume name] 
```

**Comment by PhanLe1010** [comment]
> > 2. https://github.com/longhorn/longhorn-manager/blob/6d936dc7e190110a8c9b216e0b4455e730456467/csi/controller_server.go#L237
> 
> @PhanLe1010 , double confirm to clone volume or create volume from snapshot, just pass snapshot name or volume name in `dataSource` field in `POST /v1/volumes` API?
> 
> ```
> {
>    ...params
>    "dataSource": [snapshot name or volume name] 
> }
> ```

Hi @a110605 

1. If it is created from another volume, pass this `"dataSource": "vol://<source-volume-name>`
1. If it is created from a snapshot of another volume, pass this `"dataSource": "snap://<source-volume-name>/<snapshot-name>`

**Comment by derekbit** [comment]
@a110605 Please update `Pre Ready-For-Testing Checklist` and update the status. Thank you.

**Comment by chriscchien** [comment]
This ticket currently is blocked by [#3692](https://github.com/longhorn/longhorn/issues/3692#issuecomment-2216338679) for some clone action failure need to be solved first then verify UI.

**Comment by PhanLe1010** [comment]
Thanks @chriscchien . FIxed. We can resume testing

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-ui `8d6025`)

Following test [steps](https://github.com/longhorn/longhorn/issues/8741#issue-2349477114), did not encounter any problems on volume cloning through UI, in addition, below colne path on attathed and detached source volume worked well too.
- RWO to RWO
- RWO to RWX
- RWX to RWO
- RWX to RWX
