### ISSUE TITLE
[IMPROVEMENT] Building longhorn-manager takes long time

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8744]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The[ longhorn-manager script/build](https://github.com/longhorn/longhorn-manager/blob/master/scripts/build#L23-L24) process now builds binaries for both amd64 and arm64 simultaneously, as part of the migration to GitHub Actions for CI. However, this method significantly slows down local image building due to the cross-compilation required for the arm64 platform. The proposed improvement aims to reduce the build time.

**Comment by derekbit** [comment]
cc @FrankYang0529

**Comment by derekbit** [comment]
longhorn-manager binaries are also rebuilt twice.
https://github.com/longhorn/longhorn-manager/blob/master/scripts/package#L12-L14

**Comment by chriscchien** [comment]
Verified **pass** on  longhorn v1.8.0-dev-20241103(https://github.com/longhorn/longhorn-manager/commit/aad527c707fbbc2f40a391895e8b7551f8b1000d)

After the build script change, no outstanding issue observed on daily regression(build [1087](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/1087/testReport/tests/) : 1 fail)
