### ISSUE TITLE
[IMPROVEMENT] Make backup deletion async and force backup creation wait until there is no backup being delete

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#8746]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

- Make backup deletion async
    - Currently, backup deletion is blocking call by using binary to delete the backup in the backupstore
    - This is time consuming and not follow the eventual consistency convention in K8s
    - By making it async, we can add `"Deleting"` status to postpone other backups creation to prevent deletion lock issue. 
- Wait for backup deletion to be finished
    - Backup creation will fail when there is another backup being delete. We can improve it by making backup wait until there is no backup being deleted before triggering the backup process.

~~- Monitor progress time
    - We can help users to record the progress time of the backup. This can help users to adjust the interval time of Recurring Job to prevent two jobs running at the same time.~~ => we disable recurring job overlap, so two jobs won't run at the same tmie.

## Describe the solution you'd like

.

## Describe alternatives you've considered
.

## Additional context
.

cc @derekbit

**Comment by derekbit** [comment]
Can we move it to v1.8.0? WDYT? @ChanYiLin @innobead

**Comment by derekbit** [comment]
@ChanYiLin Let's add it into v1.8.0 important note.

**Comment by roger-ryao** [comment]
**Verified on v1.8.0-dev-20241103 20241113**

- longhorn v1.8.0-dev-20241103 https://github.com/longhorn/longhorn/commit/8265d91c74e0d4d83608d6210628215315a6fab9

**The test steps**
https://github.com/longhorn/longhorn/pull/9152

Cases:
1. Normal Case
2. Error Case (use nfs)
3. Controller Crashes Case (use nfs)


**Result Passed**

- [x] 1. Normal Case
- [x] 2. Error Case (use nfs)
- [x] 3. Controller Crashes Case (use nfs)
- [ ] 4. require/manual-test-plan ❌


Hi @ChanYiLin 
I suggest we reference the following documents for manual test planning in v1.8.0:
- https://github.com/longhorn/longhorn-tests/blob/master/docs/content/manual/release-specific/v1.7.0/test-storage-network-support-for-rwx-volume.md
- https://longhorn.github.io/longhorn-tests/manual/release-specific/v1.7.0/test-rwx-fast-failover/

**Comment by derekbit** [comment]
@ChanYiLin What's the status of the ticket?

**Comment by derekbit** [comment]
@ChanYiLin Let's move this forward.

**Comment by ChanYiLin** [comment]
Current: require/manual-test-plan

**Comment by ChanYiLin** [comment]
@roger-ryao 
manual test plan added: https://github.com/longhorn/longhorn-tests/pull/2223

**Comment by roger-ryao** [comment]
> **Verified on v1.8.0-dev-20241103 20241113**
> 
> * longhorn v1.8.0-dev-20241103 [8265d91](https://github.com/longhorn/longhorn/commit/8265d91c74e0d4d83608d6210628215315a6fab9)
> 
> **The test steps** [#9152](https://github.com/longhorn/longhorn/pull/9152)
> 
> Cases:
> 
> 1. Normal Case
> 2. Error Case (use nfs)
> 3. Controller Crashes Case (use nfs)
> 
> **Result Passed**
> 
> * [x]  1. Normal Case[x]  2. Error Case (use nfs)[x]  3. Controller Crashes Case (use nfs)[ ]  4. require/manual-test-plan ❌
> 
> Hi [@ChanYiLin](https://github.com/ChanYiLin) I suggest we reference the following documents for manual test planning in v1.8.0:
> 
> * https://github.com/longhorn/longhorn-tests/blob/master/docs/content/manual/release-specific/v1.7.0/test-storage-network-support-for-rwx-volume.md
> * https://longhorn.github.io/longhorn-tests/manual/release-specific/v1.7.0/test-rwx-fast-failover/

- [x]  4. require/manual-test-plan : https://github.com/longhorn/longhorn-tests/pull/2223 was merged
