### ISSUE TITLE
[IMPROVEMENT] v2 volume supports delta replica rebuilding based on snapshot checksum

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8771]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

https://github.com/longhorn/longhorn/issues/5573
https://github.com/longhorn/longhorn/issues/8666

**Comment by DamiaSan** [comment]
Working on #5573

**Comment by DamiaSan** [comment]
Working on #8666

**Comment by DamiaSan** [comment]
This is the [LEP](https://github.com/longhorn/longhorn/pull/7031)

**Comment by derekbit** [comment]
@DamiaSan Sorry. I'm a bit confused. The LEP of the ticket includes the snapshot checksum and bitmap. What's the main issue that will be addressed in the ticket? Because there is ticket for snapshot checksum, can we close this one?

**Comment by DamiaSan** [comment]
Yes, we can close this.
