### ISSUE TITLE
[TASK] Manage Shallow copy async in go-spdk-helper

### ISSUE THREAD

**Issue by DamiaSan** [longhorn/longhorn#8772]
## What's the task? Please describe

In the new SPDK `longhorn-v24.05` branch the shallow copy API is now async, must handle this in `go-spdk-helper`

**Comment by DamiaSan** [comment]
PR https://github.com/longhorn/go-spdk-helper/pull/114

**Comment by innobead** [comment]
The milestone was missed. Need to ensure the item we are working to assign to the current milestone. 

cc @derekbit
