### ISSUE TITLE
[BUG] the engine image controller has to deploy the engine images with the linux node selector

### ISSUE THREAD

**Issue by doctorpangloss** [longhorn/longhorn#8774]
## Describe the bug

the engine image controller tries to deploy images onto windows nodes, which can't run them

the daemonset (along with the csi-attacher, csi-provisioner, csi-snapshotter and csi-resizer deployments) need to have the proper node selectors for linux instead of windows

## To Reproduce

1. deploy longhorn onto a windows & linux cluster
2. observe failures to deploy the engine image on windows nodes, which shouldn't be scheduled in the first place

## Expected behavior

these resources need to have configurable node selectors, affinity, tolerations, etc.

## Support bundle for troubleshooting

N/A

## Environment

 - Longhorn version: v1.6.2
 - Installation method: flux
 - Kubernetes distro: k02
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 20
 - Node config
   - OS type and version: Windows 2022, Ubuntu 22
   - Kernel version: 6.5.0-35-generic
   - CPU per node: ~16-64 Zen4 class
   - Memory per node: 32-128GB typical
   - Disk type (e.g. SSD/NVMe/HDD): NVMe
   - Network bandwidth between the nodes (Gbps): 2.5gbps-10gbps typical
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 40

**Comment by derekbit** [comment]
cc @c3y1huang

**Comment by doctorpangloss** [comment]
The `longhorn-support-bundle-manager-support-bundle` pods also need a linux nodeselector.

**Comment by PhanLe1010** [comment]
Hi @doctorpangloss Have you tried to set the nodeselector and toleration for Longhorn as mentioned at https://longhorn.io/docs/1.8.0/advanced-resources/deploy/rancher_windows_cluster/#setup-longhorn-components-for-existing-longhorn ?

**Comment by doctorpangloss** [comment]
Yes.

```
Name:                 longhorn-support-bundle-manager-support-bundle-2024-06-17twqjcq
Namespace:            longhorn-system
Priority:             1000000000
Priority Class Name:  longhorn-critical
Service Account:      longhorn-support-bundle
Node:                 appmana-008/10.3.64.2
Start Time:           Wed, 18 Sep 2024 08:46:01 -0700
Labels:               app=support-bundle-manager
                      pod-template-hash=7d7c885d5d
                      rancher/supportbundle=support-bundle-2024-06-17t20-39-23z
Annotations:          cni.projectcalico.org/containerID: 2ea43aeef6f4d5977f86bb02f25d099fa08cd3c89f76ab639863c5f4fb1a4458
                      cni.projectcalico.org/podIP: 10.3.64.43/32
                      cni.projectcalico.org/podIPs: 10.3.64.43/32
Status:               Pending
IP:                   10.3.64.43
IPs:
  IP:           10.3.64.43
Controlled By:  ReplicaSet/longhorn-support-bundle-manager-support-bundle-2024-06-17t20-39-23z-7d7c885d5d

```
observe that this and other pods are not controlled by deployments that are in the helm chart.

```
kubectl describe deployment.apps/longhorn-support-bundle-manager-support-bundle-2024-06-17t20-39-23z -n longhorn-system
Name:                   longhorn-support-bundle-manager-support-bundle-2024-06-17t20-39-23z
Namespace:              longhorn-system
CreationTimestamp:      Mon, 17 Jun 2024 13:39:23 -0700
Labels:                 app=support-bundle-manager
                        rancher/supportbundle=support-bundle-2024-06-17t20-39-23z
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=support-bundle-manager
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=support-bundle-manager
                    rancher/supportbundle=support-bundle-2024-06-17t20-39-23z
  Service Account:  longhorn-support-bundle
  Containers:
   manager:
    Image:      longhornio/support-bundle-kit:v0.0.37
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      /usr/bin/support-bundle-kit
      manager
    Environment:
      POD_NAMESPACE:                      (v1:metadata.namespace)
      SUPPORT_BUNDLE_TARGET_NAMESPACES:  longhorn-system
      SUPPORT_BUNDLE_NAME:               support-bundle-2024-06-17t20-39-23z
      SUPPORT_BUNDLE_ISSUE_URL:          
      SUPPORT_BUNDLE_DESCRIPTION:        describes a healthy cluster
      SUPPORT_BUNDLE_DEBUG:              true
      SUPPORT_BUNDLE_MANAGER_POD_IP:      (v1:status.podIP)
      SUPPORT_BUNDLE_IMAGE:              longhornio/support-bundle-kit:v0.0.37
      SUPPORT_BUNDLE_IMAGE_PULL_POLICY:  IfNotPresent
      SUPPORT_BUNDLE_REGISTRY_SECRET:    
      SUPPORT_BUNDLE_COLLECTOR:          longhorn
      SUPPORT_BUNDLE_NODE_SELECTOR:      
      SUPPORT_BUNDLE_TAINT_TOLERATION:   
    Mounts:                              <none>
  Volumes:                               <none>
  Priority Class Name:                   longhorn-critical
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      False   MinimumReplicasUnavailable
OldReplicaSets:  <none>

```

This and other deployments / resources need node selectors but do not have them.

**Comment by PhanLe1010** [comment]
@doctorpangloss 

The support bundle pod and other deployments / resources created by whatever controller in longhorn will have the correct nodeselector and toleration if you follow the plan https://longhorn.io/docs/1.8.0/advanced-resources/deploy/rancher_windows_cluster/#setup-longhorn-components-for-existing-longhorn . Specifically, this section will make them having correct nodeselector and toleration https://longhorn.io/docs/1.8.0/advanced-resources/deploy/node-selector/#:~:text=Follow%20the%20Customize,For%20example%3A

By default, there is no nodeselector/toleration for Longhorn pods. But they should have it if user fully follow the https://longhorn.io/docs/1.8.0/advanced-resources/deploy/rancher_windows_cluster/#setup-longhorn-components-for-existing-longhorn

Please let us know if you still see problem after applying https://longhorn.io/docs/1.8.0/advanced-resources/deploy/rancher_windows_cluster/#setup-longhorn-components-for-existing-longhorn

**Comment by PhanLe1010** [comment]
Additional context:

The reason that we don't automatically set the nodeselector/toleration for windows cluster by default is that if we do so, when user upgrading Longhorn from older version (without default nodeselector/toleration) to newer version (with nodeselector/toleration), the instance-manager pods would have to be restarted and all volumes would need to be detached.
