### ISSUE TITLE
[BUG] longhorn-manager /usr/local/sbin/ volume and noexec configuration

### ISSUE THREAD

**Issue by lenglet-k** [longhorn/longhorn#8780]
## Describe the bug

We want to use longhorn on CIS Benchmark Linux servers. In the CIS rules, the /var/ volume must have the noexec option enabled, this volume is propagated by containerd when a container mounts a volume, this is the case of longhorn-manager [here](https://github.com/longhorn/longhorn-manager/blob/master/package/Dockerfile#L23).

In my case, longhorn-manager gets the permission denied error because the noexec option is propagated to the container automatically. 

![image](https://github.com/longhorn/longhorn/assets/107568487/e4defde2-5f85-4473-ac46-0362d2f09c69)

My question is: why did you create a volume in longhorn-manager on /usr/local/sbin? is it useful?
## To Reproduce

1. Create a mountpoint with noexec options on /var. 
2. Install Kubernetes and install containerd on /var/lib/containerd
3. Deploy longhorn.
4. See crashloopback state

## Expected behavior

Have the possibility to run longhorn-manager on hardening system from scratch and without error

**Comment by derekbit** [comment]
> My question is: why did you create a volume in longhorn-manager on /usr/local/sbin? is it useful?

`launch-manager`, `longhorn-manager` and `nsmounter` are put in `/usr/local/sbin`. Some utilities such as `engine-binaries` are in `/var/lib/longhorn`.
I'm not familiar with CIS benchmark Linux. Can you provide a support bundle for checking what the error is? Thank you.

BTW, @innobead `/var/lib/longhorn` is hard-coded path. Do you think we should make it configurable in the future?

**Comment by lenglet-k** [comment]
There is a possibilty to hide private information with a support bundle ? In state, i can't send you this file with sensitive information.

**Comment by derekbit** [comment]
> There is a possibilty to hide private information with a support bundle ? In state, i can't send you this file with sensitive information.

You can manually hide the private information, or you can send the support bundle to longhorn-support-bundle@suse.com which is only accessible by Longhorn members.

**Comment by lenglet-k** [comment]
@derekbit I have just sent this file by mail. WIth anonymous data

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `77ac26`, longhorn-engine `004f20`, longhorn-instance-manager `4dd756`)

From daily regression, did not observe new outstanding issue.
