### ISSUE TITLE
[UI][FEATURE] Add backing image encryption and clone support 

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#8789]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

- [x] When Create Backing Image, when the `Created From` is `clone`, add following fields
    - `Backing Image`: the source BackingImage.
    - `Encryption`: 3 options for selection, `ignore`, `encrypt` and `decrypt`.
    - `Secret`: the secret name for the encryption or decryption.
    - `Secret Namespace`: the namespace of the secret.
- [x] If the BackingImage has `Secret` and `Secret Namespace` is not empty, show a "lock" icon besides it like encrypted volume.
- [x] When restore BackupBackingImage, user can specified the `Secret` and `SecretNamespace` for the restored BackingImage

### Call APi
```
HTTP/1.1 POST /v1/backingimages
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Content-Length: 197

{
"expectedChecksum": "",
"name": "parrot-encrypted",
"parameters": {
     "backing-image": "parrot",
     "encryption": "encrypt",
     "secret": "longhorn-crypto",
     "secret-namespace": "longhorn-system",
},
"sourceType": "clone",
}
```

## Additional context

ref: https://github.com/longhorn/longhorn/issues/7051

**Comment by a110605** [comment]
The third point is blocked by [[FEATURE] Add BackupBackingImage UI](https://github.com/longhorn/longhorn/issues/7541). I will add `Secret` and `SecretNamespace` after we have back backing image table. cc @ChanYiLin

**Comment by derekbit** [comment]
@a110605 Can it be moved to ready for testing?

**Comment by a110605** [comment]
Will move once https://github.com/longhorn/longhorn-ui/pull/763 is approved and merged. The third point is implement in that PR.

**Comment by derekbit** [comment]
@mantissahz  Can you help verify the ticket? Feel free to check with @roger-ryao and @a110605. Thank you.

**Comment by mantissahz** [comment]
Verified PASSED on longhorn master(longhorn-manager 79f794) with [test steps](https://github.com/longhorn/longhorn/issues/8789#issuecomment-2213019863)
