### ISSUE TITLE
Volume in maintenance mode and DR mode stuck in live upgrade

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#879]
Steps to reproduce:

Using rancher managed k8s cluster:
  - rancher: `v2.3.2`
  - k8s: `v1.14.8`

- Install Longhorn `v0.6.2`
- Create a volume, attach it to a node in `maintenance mode`
- Upgrade Longhorn to `v0.7.0-rc2`, and wait for it to be `active`
- Clean old CRD using `curl -s https://raw.githubusercontent.com/longhorn/longhorn-manager/master/hack/cleancrds.sh | bash -s v062`
- Upgrade engine-image for attached volume.
- Try to detach the volume
> Result: Volume stuck in `detaching` state.

**Comment by shuo-wu** [comment]
```
......
[instance-manager-e-49b13480] [longhorn-instance-manager] time="2019-11-14T01:27:56Z" level=info msg="device test1: waiting for socket /var/run/longhorn-test1.sock to show up"
[instance-manager-e-49b13480] [longhorn-instance-manager] time="2019-11-14T01:27:57Z" level=info msg="device test1: waiting for socket /var/run/longhorn-test1.sock to show up"
[instance-manager-e-49b13480] [longhorn-instance-manager] time="2019-11-14T01:27:58Z" level=info msg="device test1: waiting for socket /var/run/longhorn-test1.sock to show up"
[instance-manager-e-49b13480] [longhorn-instance-manager] time="2019-11-14T01:27:59Z" level=info msg="device test1: waiting for socket /var/run/longhorn-test1.sock to show up"
[instance-manager-e-49b13480] [longhorn-instance-manager] time="2019-11-14T01:28:00Z" level=info msg="device test1: waiting for socket /var/run/longhorn-test1.sock to show up"
[instance-manager-e-49b13480] [longhorn-instance-manager] time="2019-11-14T01:28:01Z" level=info msg="device test1: waiting for socket /var/run/longhorn-test1.sock to show up"
[instance-manager-e-49b13480] [longhorn-instance-manager] time="2019-11-14T01:28:02Z" level=info msg="device test1: waiting for socket /var/run/longhorn-test1.sock to show up"
[instance-manager-e-49b13480] [longhorn-instance-manager] time="2019-11-14T01:28:02Z" level=error msg="error waiting for the socket device test1: wait for socket /var/run/longhorn-test1.sock timed out"
[instance-manager-e-49b13480] [longhorn-instance-manager] time="2019-11-14T01:28:02Z" level=info msg="device test1: stop wait for socket routine"
```

The instance manager should check if the volume is a DR volume. When it upgrades the DR volume, It cannot blindly wait for the socket file which is used for the frontend-enabled volume only.

**Comment by shuo-wu** [comment]
Test Step:
1. Create a volume using `longhornio/longhron-engine:master`:
  1.1. Create and attach a Longhorn volume
  1.2. Write data in the Longhorn volume
  1.3. Live upgrade the volume to `longhornio/longhron-engine:master`
  1.4. Detach the volume
2. Attach the volume with maintenance mode
3. Live upgrade to `longhornio/longhron-engine:v0.7.0-rc2` --> Should succeed
4. Detach and Reattach the volume. Verify the data

Notice: Upgrading from `v0.7.0-rc2` to `master` won't succeed.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
