### ISSUE TITLE
Upgrade: Live upgrade v2: reuse the instance manager for upgrade

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#880]
We don't want to start multiple instance managers just for multiple engine images.

**Comment by yasker** [comment]
We don't need to change the instance manager for Longhorn engine. We only need to change the manager logic to:
- [ ] Only create instance manager if there is no instance manager available. No need to create instance managers per engine image.
- [ ] Instance manager call to the specified version of the engine binary instead of always call the default one when creating the instance.
- [ ] Allow users to offline upgrade instance manager if all volumes are detached (basically delete the instance manager then recreated it using specified version of engine image)

So we will need to move the instance manager control logic out of the engine image controller. Probably back to the node controller.

**Comment by yasker** [comment]
There are multiple things blocking this from getting into v0.8.0.
- The live upgrade experience needs a redesign. Since we have introduced instance managers, now Longhorn manager will need to be compatible with instance managers as well as engines, which means small changes in the instance manager's API (e.g. adding a new API for extending the volume) will result in an API version bump, which will render live upgrade feature useless even the feature won't affect the existing volumes.
- When the new manager wasn't compatible with the old engine, users need to perform an offline upgrade. However, the instance manager on the node cannot be restarted/recreated unless all the engines/replicas are stopped on the node. It makes upgrade process more cumbersome than before: instead of "upgrade manager, then upgrade volume (online or offline)", user need to "upgrade manager, then either upgrade volume (if live upgrade is supported), or detach all the volumes (if live upgrade is not supported), wait for instance managers to be upgraded, then upgrade the volume, finally start using the volume". It's much more work than before.

Also, issue #984 needs to be fixed, which might cause a compatibility issue.

Some thoughts for the next try:
- Only keep the essential APIs in the instance manager. It's better if the manager calls to the engine for upgrade, expand, and frontend operations directly. Engine instance manager can still start tgt but don't actively operating on it.
- In the same version, have a feature list supplied so any new features will not result in an API version bump as long as there is no change for the existing APIs.

**Comment by yasker** [comment]
The next step is to introduce the instance manager upgrade. So if the instance manager version is compatible, we don't need to start new instance managers. Otherwise, an offline upgrade is required for existing volumes.

A live upgrade is not available if the new engine's InstanceManagerMinVersion is higher than the current instance manager's version.

InstanceManagers with the same InstanceManagerMinVersion can be used interchangeably, though the higher version of InstanceManager will be more stable and contain bug fixes for the previous version. Users can upgrade the instance manager (in v0.8.1) with the same MinVersion if needed. The upgrade can be achieved by deleting the instance manager when there is no process running. The new instance manager will be created using the default engine image.

We will start an instance manager for different versions of InstanceManagerVersion.
Engines have the same 

```
const (
	// CLIAPIVersion used to communicate with user e.g. longhorn-manager
	CLIAPIVersion    = 3
	CLIAPIMinVersion = 3

	ControllerAPIVersion    = 3
	// ControllerAPIMinVersion defines the minimal version of engine can be live upgraded from
	// Always increase ControllerAPIVersion/ControllerAPIMinVersion if the InstanceManagerMinVersion increased
	ControllerAPIMinVersion = 3

	// DataFormatVersion used by the Replica to store data
	DataFormatVersion    = 1
	DataFormatMinVersion = 1

	InstanceManagerVersion = 1
	// InstanceManagerMinVersion defines the compatible instance manager for the engine
	// Always increase ControllerAPIVersion/ControllerAPIMinVersion if the InstanceManagerMinVersion increased
	InstanceManagerMinVersion = 1
)
```

We can implement feature flags later when needed.

@shuo-wu What do you think?

**Comment by shuo-wu** [comment]
Sounds good.

But there are still several issues we need to clarify or be careful with:
1. When can we bump up the MinVerison or Verison for ControllerAPI or InstanceManagerAPI? Are the following right?
  1.1. Modify/Delete the existing fields/API --> Bump up the MinVersion.
  1.2. Add new fields/APIs --> Bump up the Version.

2. One volume(engine image) can be compatible with multiple instance managers now. We need to make sure that manager pods are always able to find the correct instance managers for detached/detaching/attached/attaching volumes.

3. If there are multiple engine images compatible with the latest instance manager, how do manager pods talk with those engine images? Newer engine images may contain new APIs. (Feature gate implementation)

**Comment by yasker** [comment]
2. I don't think one engine cannot be compatible with multiple instance managers on the same node for the same role (engine or replica), since we will bump ControllerAPIMinVersion when the InstanceManagerMinVersion is bumped.

**Comment by yasker** [comment]
Check the latest design doc for the feature at https://docs.google.com/document/d/1ttLE3bRXMdCBdgK39z17VmOTEwH36Z5nrmt_YcE4GLk/edit?usp=sharing

**Comment by shuo-wu** [comment]
Test Case 1:
1. Launch latest Longhorn system.
--> For all instance managers, `Status.MajorVersion` and `Status.MinorVersion` are 1; `Status.Image` is `longhornio/longhorn-instance-manager:master`; the label value is the same as Spec and Status.
2. Launch a pod. Write data into the corresponding Longhorn volume and record the md5sum.
3. Upgrade the system with `shuowu/longhorn-instance-manager:imtest-v3`, which has higher APIVersion. (You can create this image by bumping up the `InstanceManagerAPIVersion` in the longhorn-instance-manager.) 
--> All old engine managers except for the one being used by the volume will be removed.
    For all new instance managers, `Status.MajorVersion` and `Status.MinorVersion` are 1 and 2; `Status.Image` is `shuowu/longhorn-instance-manager:imtest-v3`; the labels value are the same as Spec and Status.
    The md5sum of the pod data keep unchanged.
4. Deploy engine image `shuowu/longhorn-engine:imtest-v3`, which is actually the same as `longhornio/longhorn-engine:master`.
5. Apply live upgrade for the volume. --> All old replica managers will be removed and replica processes will be in the new replica managers.
6. Log in the pod, then check md5sum for the existing data, and write more data. --> The md5sum of the existing data keeps unchanged. R/W works fine.
7. Delete and recreate the pod. (Do not delete the PVC) Then check the md5sum. --> All old engine managers will be deleted. The md5sum of the pod data keeps unchanged.

Test Case 2:
1. Launch Longhorn system v0.7.0.
2. Launch a pod. Write data into the corresponding Longhorn volume and record the md5sum.
3. Upgrade the system to the latest. 
--> All old engine managers except for the one being used by the volume will be removed. 
    For all old existing instance managers, `Status.MajorVersion` and `Status.MinorVersion` are -1; `Status.Image` is `longhornio/longhorn-instance-manager:v0.7.0`; the labels value are the same as Spec and Status.
    For all new instance managers, `Status.MajorVersion` and `Status.MinorVersion` are 1; `Status.Image` is `longhornio/longhorn-instance-manager:master`; the label value is the same as Spec and Status.
4. Log in the pod, check the existing data then write new data. --> The md5sum of the existing data keeps unchanged. R/W works fine.
5. Delete one replica. --> Rebuild will be triggered. Then volume can become healthy after rebuilding complete and one old replica manager will be deleted. The rebuilt replica should be in the new replica manager.
6. Log in the pod, check the existing data then write new data. --> The md5sum of the existing data keeps unchanged. R/W works fine.
7. Apply live upgrade for the volume. --> Live upgrade won't be triggered. 
8. Delete and recreate the pod. (Do not delete the PVC) Then check the md5sum. --> All old engine managers will be deleted. The md5sum of the pod data keeps unchanged.

Test Case 3 (corner case):
1. Launch Longhorn system v0.7.0.
2. Launch a pod. Write data into the corresponding Longhorn volume and record the md5sum.
3. Upgrade the system to the latest. Check old and new instance managers.
4. Log in the pod, check the existing data then write new data. --> The md5sum of the existing data keeps unchanged. R/W works fine.
5. Apply live upgrade for the volume. --> Live upgrade won't be triggered. 
6. Delete the only old engine manager. --> Reattach and remount (with offline upgrade) are triggered. All the old instance managers will be cleaned up.
7. Log in the pod, check the existing data then write new data. --> The md5sum of the existing data keeps unchanged. R/W works fine.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
