### ISSUE TITLE
[BUG] The state of System Backup is pending

### ISSUE THREAD

**Issue by bkkoli** [longhorn/longhorn#8800]
## Describe the bug
I created a system backup, removed Longhorn with Helm, and installed Longhorn with Helm again. And I ran System Backup Restore as a system backup on NFS. The system backup did not restore normally and stuck in the Pending state.

I attached the image related to the error below.

![image](https://github.com/longhorn/longhorn/assets/41296400/a0ec17b8-06d8-404d-8bc0-0e2c470067d3)
![image](https://github.com/longhorn/longhorn/assets/41296400/4790e098-c17e-4fda-9106-cf31ce3f6494)
![image](https://github.com/longhorn/longhorn/assets/41296400/7327027c-fe9b-4626-abc6-8912dbbfb6f0)
![image](https://github.com/longhorn/longhorn/assets/41296400/aecc6945-55cb-45d6-9504-7ed2b68ba762)

## To Reproduce
1. Create a System Backup to NFS Server
2. Remove a Longhorn Cluster with Helm 
3. Create a Longhorn Cluster with Helm
4. Restore System Backup

## Expected behavior
The process of system backup is completed with success state.

## Environment

 - Longhorn version: `1.6.2`
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): `Helm`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: `k3s`, `v1.30.1+k3s1`
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 0
 - Node config
   - OS type and version: `Debian 12.5`
   - Kernel version: `6.1.0-21-amd64`
   - CPU per node: `2Core`
   - Memory per node: `4GB`
   - Disk type (e.g. SSD/NVMe/HDD): `HDD`
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): `Qemu`
 - Number of Longhorn volumes in the cluster: `1 of each node`

**Comment by c3y1huang** [comment]
https://github.com/longhorn/longhorn-manager/blob/v1.6.2/controller/system_rollout_controller.go#L591

It looks like the rollout created the `EngineImage`  but it isn't reaching the `deployed` state. Have you tried checking the `EngineImage` custom resource or Longhorn manager logs?

BTW, what is the Longhorn version in the system backup?

**Comment by bkkoli** [comment]
@c3y1huang 
`what is the Longhorn version in the system backup?`

The Longhorn version of the system backup is `1.6.2`. It is currently the same as the Longhorn version.

**Comment by bkkoli** [comment]
@c3y1huang 

`EngineImage` Custom Resource is as follows.
![image](https://github.com/longhorn/longhorn/assets/41296400/63cfef11-3d0a-4d39-9518-ce7484186f45)

![image](https://github.com/longhorn/longhorn/assets/41296400/e0635c51-d5dc-4eff-8f71-f35990571b31)

As you advised, I looked at the Longhorn Manager's log and found the following.

```
time="2024-06-21T04:27:49Z" level=info msg="Starting Longhorn restore controller" func="controller.(*VolumeRestoreController).Run" file="volume_restore_controller.go:100" controller=longhorn-volume-restore node=k3s-06
I0621 04:27:49.874302       1 shared_informer.go:311] Waiting for caches to sync for longhorn-volume-restore
I0621 04:27:49.874313       1 shared_informer.go:318] Caches are synced for longhorn-volume-restore
time="2024-06-21T04:27:49Z" level=info msg="Starting Longhorn eviction controller" func="controller.(*VolumeEvictionController).Run" file="volume_eviction_controller.go:102" controller=longhorn-volume-eviction node=k3s-06
I0621 04:27:49.874352       1 shared_informer.go:311] Waiting for caches to sync for longhorn-volume-eviction
I0621 04:27:49.874359       1 shared_informer.go:318] Caches are synced for longhorn-volume-eviction
time="2024-06-21T04:27:49Z" level=info msg="Starting Longhorn Kubernetes config map controller" func="controller.(*KubernetesConfigMapController).Run" file="kubernetes_configmap_controller.go:97" controller=longhorn-kubernetes-configmap-controller node=k3s-06
I0621 04:27:49.874429       1 shared_informer.go:311] Waiting for caches to sync for longhorn-kubernetes-configmap-controller
I0621 04:27:49.874441       1 shared_informer.go:318] Caches are synced for longhorn-kubernetes-configmap-controller
time="2024-06-21T04:27:49Z" level=info msg="Starting Longhorn SystemRestore controller" func="controller.(*SystemRestoreController).Run" file="system_restore_controller.go:127" controller=longhorn-system-restore node=k3s-06
I0621 04:27:49.875189       1 shared_informer.go:311] Waiting for caches to sync for longhorn-system-restore
I0621 04:27:49.875377       1 shared_informer.go:318] Caches are synced for longhorn-system-restore
time="2024-06-21T04:27:49Z" level=error msg="Failed to sync Longhorn setting" func=controller.handleReconcileErrorLogging file="utils.go:67" Setting=longhorn-system/backup-target-credential-secret controller=longhorn-setting error="failed to sync setting for longhorn-system/backup-target-credential-secret: failed to sync backup target: failed to select node for sync backup target: no ready nodes available" node=k3s-06

```

**Comment by bkkoli** [comment]
@c3y1huang 

Sorry, 
As the version has changed, it seems that I accidentally left out the '--version 1.6.2' option and installed it as helm after looking at the master branch at the first installation.

**Comment by c3y1huang** [comment]
> Sorry, As the version has changed, it seems that I accidentally left out the '--version 1.6.2' option and installed it as helm after looking at the master branch at the first installation.

Got it. I will close this. Feel free to re-open if needed.

**Comment by bkkoli** [comment]
@c3y1huang 
The version of Helm Chart that created System Backup was Github's Master Branch. As I reinstalled Longhorn with Master Branch and proceeded with System Restore, it was restored normally.
Thank you for kindness.
