### ISSUE TITLE
[BUG] pod can't start, and pv keep attaching / deattaching status, there is enough free space

### ISSUE THREAD

**Issue by superwangnan** [longhorn/longhorn#8806]
My Pod can't start, pod error
<img width="1109" alt="image" src="https://github.com/longhorn/longhorn/assets/20192234/f6b4736b-df41-47e4-8e6e-fd116a562bd4">

Please refer to following screenshot for longhorn
<img width="1420" alt="image" src="https://github.com/longhorn/longhorn/assets/20192234/b4b77766-21ac-4b15-9c83-ad599d24f8bf">
<img width="1410" alt="image" src="https://github.com/longhorn/longhorn/assets/20192234/9115feaa-b86a-48cc-a395-5521d64589a6">
<img width="1432" alt="image" src="https://github.com/longhorn/longhorn/assets/20192234/ab2329d8-6dd1-4abc-b6aa-38085df63576">

---------
This is the log for longhorn-manager

`time="2024-06-22T11:33:16Z" level=error msg="There's no available disk for replica pvc-8268fcc6-755f-40d7-8245-28869ee69f55-r-0e335488, size 2147483648" func="scheduler.(*ReplicaScheduler).ScheduleReplica" file="replica_scheduler.go:101"
time="2024-06-22T11:33:16Z" level=warning msg="Failed to schedule replica" func="controller.(*VolumeController).reconcileVolumeCondition" file="volume_controller.go:1769" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=cnsthana247 owner=cnsthana247 replica=pvc-8268fcc6-755f-40d7-8245-28869ee69f55-r-0e335488 state=attaching volume=pvc-8268fcc6-755f-40d7-8245-28869ee69f55
time="2024-06-22T11:33:16Z" level=error msg="There's no available disk for replica pvc-8268fcc6-755f-40d7-8245-28869ee69f55-r-80418418, size 2147483648" func="scheduler.(*ReplicaScheduler).ScheduleReplica" file="replica_scheduler.go:101"
time="2024-06-22T11:33:16Z" level=warning msg="Failed to schedule replica" func="controller.(*VolumeController).reconcileVolumeCondition" file="volume_controller.go:1769" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=cnsthana247 owner=cnsthana247 replica=pvc-8268fcc6-755f-40d7-8245-28869ee69f55-r-80418418 state=attaching volume=pvc-8268fcc6-755f-40d7-8245-28869ee69f55
time="2024-06-22T11:33:17Z" level=error msg="There's no available disk for replica pvc-8268fcc6-755f-40d7-8245-28869ee69f55-r-80418418, size 2147483648" func="scheduler.(*ReplicaScheduler).ScheduleReplica" file="replica_scheduler.go:101"
time="2024-06-22T11:33:17Z" level=warning msg="Failed to schedule replica" func="controller.(*VolumeController).reconcileVolumeCondition" file="volume_controller.go:1769" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=cnsthana247 owner=cnsthana247 replica=pvc-8268fcc6-755f-40d7-8245-28869ee69f55-r-80418418 state=attaching volume=pvc-8268fcc6-755f-40d7-8245-28869ee69f55
time="2024-06-22T11:33:17Z" level=error msg="There's no available disk for replica pvc-8268fcc6-755f-40d7-8245-28869ee69f55-r-0e335488, size 2147483648" func="scheduler.(*ReplicaScheduler).ScheduleReplica" file="replica_scheduler.go:101"
time="2024-06-22T11:33:17Z" level=warning msg="Failed to schedule replica" func="controller.(*VolumeController).reconcileVolumeCondition" file="volume_controller.go:1769" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=cnsthana247 owner=cnsthana247 replica=pvc-8268fcc6-755f-40d7-8245-28869ee69f55-r-0e335488 state=attaching volume=pvc-8268fcc6-755f-40d7-8245-28869ee69f55
time="2024-06-22T11:33:25Z" level=error msg="There's no available disk for replica pvc-8268fcc6-755f-40d7-8245-28869ee69f55-r-80418418, size 2147483648" func="scheduler.(*ReplicaScheduler).ScheduleReplica" file="replica_scheduler.go:101"
time="2024-06-22T11:33:25Z" level=warning msg="Failed to schedule replica" func="controller.(*VolumeController).reconcileVolumeCondition" file="volume_controller.go:1769" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=cnsthana247 owner=cnsthana247 replica=pvc-8268fcc6-755f-40d7-8245-28869ee69f55-r-80418418 state=attaching volume=pvc-8268fcc6-755f-40d7-8245-28869ee69f55
time="2024-06-22T11:33:25Z" level=error msg="There's no available disk for replica pvc-8268fcc6-755f-40d7-8245-28869ee69f55-r-0e335488, size 2147483648" func="scheduler.(*ReplicaScheduler).ScheduleReplica" file="replica_scheduler.go:101"
time="2024-06-22T11:33:25Z" level=warning msg="Failed to schedule replica" func="controller.(*VolumeController).reconcileVolumeCondition" file="volume_controller.go:1769" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=cnsthana247 owner=cnsthana247 replica=pvc-8268fcc6-755f-40d7-8245-28869ee69f55-r-0e335488 state=attaching volume=pvc-8268fcc6-755f-40d7-8245-28869ee69f55`

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by superwangnan** [comment]
add some more information, when the error happen, I can see there is much error apprear in longhorn-manager pod's log as attachment:
<img width="1922" alt="image" src="https://github.com/longhorn/longhorn/assets/20192234/8bff40c3-4076-4058-b208-a259fe511632">

**Comment by liyimeng** [comment]
seem we have similar problem  https://github.com/longhorn/longhorn/issues/8669

**Comment by derekbit** [comment]
@superwangnan Can you provide a support bundle for investigation?

cc @DamiaSan for the community issue coordinator

**Comment by superwangnan** [comment]
Hi I fixed the issue. In my case, iscsid service is stopped ~. so, maybe we can improve the error message.
