### ISSUE TITLE
[BUG] instance-manager pod for v2 volume is killed due to a failed liveness probe.

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8807]
## Describe the bug

The instance-manager pod for V2 volume is being terminated due to a failed liveness probe. This failure is caused by the removal of the ps utility (procps package) in the recent BCI 15.5 and 15.6 images.

https://registry.suse.com/categories/bci/repositories/bci-bci-base-15sp5?tag=latest

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
cc @FrankYang0529 @innobead

**Comment by innobead** [comment]
@derekbit does this mean v2 is not working in 1.6.2? cc @longhorn/qa

**Comment by derekbit** [comment]
> @derekbit does this mean v2 is not working in 1.6.2? cc @longhorn/qa

No. The BCI image used by Longhorn 1.6.2 works well because the ps component is not removed in the old BCI 15.5 patch release. Only newer BCI 15.5 patch releases don't include `ps`.

![image](https://github.com/longhorn/longhorn/assets/12527233/74f0513e-27f6-41e4-8b42-58f18423b5b9)

**Comment by innobead** [comment]
It's interesting to see things removed from any patches, as it should not have breaking changes..

**Comment by derekbit** [comment]
> It's interesting to see things removed from any patches, as it should not have breaking changes..

Agree!

**Comment by derekbit** [comment]
> It's interesting to see things removed from any patches, as it should not have breaking changes..

Some contextes in https://suse.slack.com/archives/C02AF8LALDA/p1718948937919709

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-instance-manager `6b9dfd`) with test [steps](https://github.com/longhorn/longhorn/issues/8807#issuecomment-2185007784)

V2 engine instance-manager wroked well, did not exhibit the behavior of repeatedly create and deleted.
