### ISSUE TITLE
[FEATURE] Missing option to modify backup-task retain value from UI while editing recurring job

### ISSUE THREAD

**Issue by artur9010** [longhorn/longhorn#8810]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

 Missing option to modify backup-task retain value from UI while editing recurring job

## Describe the solution you'd like

Enable text field in "Retain", this value can be easily edited using kubectl but not from webUI.

![Screenshot 2024-06-23 at 19 53 18](https://github.com/longhorn/longhorn/assets/4835677/358e8822-9b34-4de1-a94d-b61dc8edfed8)

**Comment by derekbit** [comment]
cc @c3y1huang @a110605

**Comment by derekbit** [comment]
@c3y1huang Do we have any limitation for the change of Retain?

**Comment by c3y1huang** [comment]
> @c3y1huang Do we have any limitation for the change of Retain?

I don't see any issues with making this field editable in the UI.

Original feature request: https://github.com/longhorn/longhorn/issues/5713
cc @mantissahz

**Comment by a110605** [comment]
Hi @c3y1huang , @derekbit ,

Current retain parameter [disabled logic](https://github.com/a110605/longhorn-ui/blob/17e03c942267eb4522f95a3cd639ecd83004c628/src/routes/recurringJob/CreateRecurringJob.js#L321) is when in edit mode (can remove this rule) or recurring task is `snapshot-cleanup` or `filesystem-trim`.

Are we sure to always let user edit this parameter?

**Comment by derekbit** [comment]
> Hi @c3y1huang , @derekbit ,
> 
> Current retain parameter [disabled logic](https://github.com/a110605/longhorn-ui/blob/17e03c942267eb4522f95a3cd639ecd83004c628/src/routes/recurringJob/CreateRecurringJob.js#L321) is when in edit mode or recurring task is `snapshot-cleanup` or `filesystem-trim`.
> 
> Are we sure to always let user edit this parameter?

IIUC, `retain` is meaningless for `snapshot-cleanup` or `filesystem-trim`, so we can grey it out when the type is either of these.

**Comment by innobead** [comment]
So that means we don't need to do any changes as the behavior is expected?

**Comment by derekbit** [comment]
> So that means we don't need to do any changes as the behavior is expected?

But, why is the `Backup` recurring job's `Retain` greyed out? cc @a110605

**Comment by a110605** [comment]
> snapshot-cleanup
Hi @derekbit 
I think above screenshot is `editing` a recurring job and according to disabled [logic](https://github.com/a110605/longhorn-ui/blob/17e03c942267eb4522f95a3cd639ecd83004c628/src/routes/recurringJob/CreateRecurringJob.js#L321) here.

In edit mode, the retain is always disabled.

**Comment by a110605** [comment]
> > Hi @c3y1huang , @derekbit ,
> > Current retain parameter [disabled logic](https://github.com/a110605/longhorn-ui/blob/17e03c942267eb4522f95a3cd639ecd83004c628/src/routes/recurringJob/CreateRecurringJob.js#L321) is when in edit mode or recurring task is `snapshot-cleanup` or `filesystem-trim`.
> > Are we sure to always let user edit this parameter?
> 
> IIUC, `retain` is meaningless for `snapshot-cleanup` or `filesystem-trim`, so we can grey it out when the type is either of these.

Hi @derekbit , if `retain` is meaningless for `snapshot-cleanup` or `filesystem-trim`, how about hide this parameter when user choose `snapshot-cleanup` or `filesystem-trim` task.
Same in edit mode.
<img width="683" alt="Screenshot 2024-06-24 at 4 21 26 PM" src="https://github.com/longhorn/longhorn/assets/5744158/ebde978d-9a34-407e-aec7-4a22d8fe7e86">

**Comment by derekbit** [comment]
@houhoucoop remember to update `Sprint` field. Thank you.

![image](https://github.com/user-attachments/assets/93fcdcda-51ed-4c77-82fa-6318ea4a5e67)

**Comment by roger-ryao** [comment]
**Verified on master-head 20241211**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/979eb98a950739d3a832100747fde2960a12ca7e
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/2838f94e5bb39bfe612cbc0a2d411d05df5f8d20
- longhorn-ui `master-head` https://github.com/longhorn/longhorn-ui/commit/1903b12799f31a4c010d6ca738724330cb31c634

**The test steps**
https://github.com/longhorn/longhorn/issues/8810#issuecomment-2521980857

**Result Passed**
