### ISSUE TITLE
[BUG] SPDK NVMe bdev is unable to create on some NVMe disks (on Equinix platform)

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8813]
## Describe the bug

SPDK NVMe bdev is unable to create on some NVMe disks (on Equinix platform).
```
[longhorn-instance-manager] time="2024-06-24T02:22:25Z" level=info msg="Creating disk bdev" func=spdk.addBlockDevice file="disk.go:244" blockSize=4096 diskDriver=nvme diskName=default-disk-nvme diskPath="0000:46:00.0" diskUUID=
[2024-06-24 02:22:58.696382] nvme_ctrlr.c:4079:nvme_ctrlr_process_init: *ERROR*: [0000:46:00.0] Initialization timed out in state 22 (wait for identify controller)
[2024-06-24 02:22:58.696453] nvme.c: 708:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 0000:46:00.0
[2024-06-24 02:22:58.696465] nvme_ctrlr.c:1028:nvme_ctrlr_fail: *ERROR*: [0000:46:00.0] in failed state.
```

Ref: https://github.com/spdk/spdk/issues/2254

No issues on AWS machines.

## To Reproduce

1. Create a Longhorn cluster on Equinix machines `m3-large-x86`
2. Enable v2-data-engine
3. Add NVMe disk to node
```
    default-disk-nvme:
      allowScheduling: false
      diskDriver: auto
      diskType: block
      evictionRequested: false
      path: "0000:45:00.0" <--- BDF of the NVMe disk
      storageReserved: 0
      tags: []
```

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
cc @DamiaSan

**Comment by innobead** [comment]
Added to 1.8.0 first, but it seems like a regression in SPDK. @derekbit did you encounter this before or just this time?

**Comment by derekbit** [comment]
> Added to 1.8.0 first, but it seems like a regression in SPDK. @derekbit did you encounter this before or just this time?

Only this time.
BTW, no issues on AWS machines. I'm thinking if it is a SSD specific issue.

**Comment by derekbit** [comment]
More information

SPDK NVMe bdev is successfully created on Equinix machine `n2-xlarge-x86`'s NVMe disk. The SSD model is different than the SSD on `m3-large-x86`.

**Comment by DamiaSan** [comment]
Do we have error in dmsg? SPDK version is longhorn-v24.01 right?

**Comment by derekbit** [comment]
> Do we have error in dmsg?

Didn't see any related error messages.

> SPDK version is longhorn-v24.01 right?

Yes

No worries. We can check this issue later.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240730**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/caf599e44fbc8cccbbc3bd4dbc2ad19247ef400c
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/76191bed70b0ef912df18b028a4469cd91568b53
- go-common-libs `main` https://github.com/longhorn/go-common-libs/commit/9e1e0e6045c66490caf17229f4d202f69fc9f573
- go-spdk-helper `main` https://github.com/longhorn/go-spdk-helper/commit/ca31a064ce91a007c33a3abe3e094002cb609afb
- longhorn-spdk-engine `main` https://github.com/longhorn/longhorn-spdk-engine/commit/2cd42bd51ee5c35e31bd045e210c90137e8dbe12
- longhorn-instance-manager `master-head` https://github.com/longhorn/longhorn-instance-manager/commit/64d480f67570813e883974aa279aecf3a11e6b8a
- cli `master-head` https://github.com/longhorn/cli/commit/c382670ace085d84e0f9626687a2e61fbea9a0ba

**Verified on v1.7.x-head 20240730**

- longhorn `v1.7.x-head` https://github.com/longhorn/longhorn/commit/000e9249019c6cf61f81891c103195e13e7561a7
- longhorn-manager `v1.7.x-head` https://github.com/longhorn/longhorn-manager/commit/654b411f2713c68c49bb8c49fd94f5579a46ed33
- go-common-libs `main` https://github.com/longhorn/go-common-libs/commit/9e1e0e6045c66490caf17229f4d202f69fc9f573
- go-spdk-helper `main` https://github.com/longhorn/go-spdk-helper/commit/ca31a064ce91a007c33a3abe3e094002cb609afb
- longhorn-spdk-engine `main` https://github.com/longhorn/longhorn-spdk-engine/commit/2cd42bd51ee5c35e31bd045e210c90137e8dbe12
- longhorn-instance-manager `v1.7.x` https://github.com/longhorn/longhorn-instance-manager/commit/dfc562467c7ee772d3da6a2e06868f7a35e01547
- cli `v1.7.x-head` https://github.com/longhorn/cli/commit/22abbc73afc63ceb0749c937a7a7a922747c2377

**The test steps**
https://github.com/longhorn/longhorn/issues/8813#issuecomment-2252407817

Verify the detection of NVMe disk

```bash
    # lsblk
    NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
    sda       8:0    0 223.6G  0 disk 
    ├─sda1    8:1    0     2M  0 part 
    ├─sda2    8:2    0   1.9G  0 part [SWAP]
    └─sda3    8:3    0 221.7G  0 part /
    sdb       8:16   0 223.6G  0 disk 
    nvme0n1 259:0    0   3.5T  0 disk 
    nvme1n1 259:1    0   3.5T  0 disk 
```
```bash
    # ls -al /sys/block/
    total 0
    drwxr-xr-x  2 root root 0 Jul 30 07:20 .
    dr-xr-xr-x 13 root root 0 Jul 30 07:20 ..
    lrwxrwxrwx  1 root root 0 Jul 30 06:43 loop0 -> ../devices/virtual/block/loop0
    lrwxrwxrwx  1 root root 0 Jul 30 06:43 loop1 -> ../devices/virtual/block/loop1
    lrwxrwxrwx  1 root root 0 Jul 30 06:43 loop2 -> ../devices/virtual/block/loop2
    lrwxrwxrwx  1 root root 0 Jul 30 06:43 loop3 -> ../devices/virtual/block/loop3
    lrwxrwxrwx  1 root root 0 Jul 30 06:43 loop4 -> ../devices/virtual/block/loop4
    lrwxrwxrwx  1 root root 0 Jul 30 06:43 loop5 -> ../devices/virtual/block/loop5
    lrwxrwxrwx  1 root root 0 Jul 30 06:43 loop6 -> ../devices/virtual/block/loop6
    lrwxrwxrwx  1 root root 0 Jul 30 06:43 loop7 -> ../devices/virtual/block/loop7
    lrwxrwxrwx  1 root root 0 Jul 30 06:43 nvme0n1 -> ../devices/pci0000:40/0000:40:03.3/0000:45:00.0/nvme/nvme0/nvme0n1
    lrwxrwxrwx  1 root root 0 Jul 30 06:43 nvme1n1 -> ../devices/pci0000:40/0000:40:03.4/0000:46:00.0/nvme/nvme1/nvme1n1
    lrwxrwxrwx  1 root root 0 Jul 30 06:43 sda -> ../devices/pci0000:c0/0000:c0:01.1/0000:c3:00.0/ata1/host0/target0:0:0/0:0:0:0/block/sda
    lrwxrwxrwx  1 root root 0 Jul 30 06:43 sdb -> ../devices/pci0000:c0/0000:c0:01.1/0000:c3:00.0/ata2/host1/target1:0:0/1:0:0:0/block/sdb
```


**Result Passed**

 - [x] 1. Verify Fresh Installation on Equinix Baremetal Machine
   - [x] master-head
   - [x] v1.7.x-head
 - [x] 2. Verify Fresh Installation on AWS EC2 Machine
   - [x] master-head
   - [x] v1.7.x-head
 - [x] 3. Verify Upgrade from `v1.6.2` to `v1.7.x-head`

**Comment by derekbit** [comment]
Ref: https://github.com/spdk/spdk/issues/399

**Comment by innobead** [comment]
> Ref: [spdk/spdk#399](https://github.com/spdk/spdk/issues/399)

Does this mean a higher version of Kernel will not have this issue?

**Comment by derekbit** [comment]
> > Ref: [spdk/spdk#399](https://github.com/spdk/spdk/issues/399)
> 
> Does this mean a higher version of Kernel will not have this issue?

In my test, the issue still exists in newer kernels.
