### ISSUE TITLE
[BUG] Receiving "backup target URL is empty" even if there is a backup target URL

### ISSUE THREAD

**Issue by vfouqueron** [longhorn/longhorn#8816]
## Describe the bug

The Backet Target is set to cifs://<URL>/volume1/BackupLonghorn with a secret associated. When I access to Backup section, I receive a "backup target URL is empty" error.

## To Reproduce

I installed a brand new longhorn with Helm in version 1.6.2 with the following settings 👍 
```
ingress:
  annotations:
    cert-manager\\.io/cluster-issuer: <my issuer>
    cert-manager\\.io/common-name: <my common name>
    nginx\\.ingress\\.kubernetes\\.io/auth-response-headers: Authorization
    nginx\\.ingress\\.kubernetes\\.io/auth-signin: "https://<My auth url>/oauth2/start?rd=$escaped_request_uri"
    nginx\\.ingress\\.kubernetes\\.io/auth-url: "https://<My auth url>/oauth2/auth"
    nginx\\.ingress\\.kubernetes\\.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie_name_1;

      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
        ngx.header["Set-Cookie"] = "name_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
    nginx\\.ingress\\.kubernetes\\.io/proxy-buffer-size: "16k"
  enabled: true
  host: <My host>
  ingressClassName: "nginx"
  tls: true
persistence:
  defaultClassReplicaCount: 4
```

When I set the url through the interface, I can see in logs : 
`time="2024-06-24T13:58:19Z" level=info msg="Updated setting backup-target to cifs://<URL>/volume1/BackupLonghorn" func="manager.(*VolumeManager).CreateOrUpdateSetting" file="setting.go:55"`

## Expected behavior

I access the Backup section withour error and an empty list of backup

## Environment

 - Longhorn version: 1.6.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): OVH
 - Number of Longhorn volumes in the cluster: 2

**Comment by derekbit** [comment]
cc @DamiaSan for the community issue coordinator

**Comment by vfouqueron** [comment]
@derekbit I’ve emailed it yesterday to longhorn-support-bundle@suse.com

**Comment by derekbit** [comment]
> @derekbit I’ve emailed it yesterday to [longhorn-support-bundle@suse.com](mailto:longhorn-support-bundle@suse.com)

Thank you. I got the mail and will check it soon.

**Comment by vfouqueron** [comment]
> ogs/cattle-system/rancher-6b57df599f-kmqtx/rancher.log



> Found this error in `logs/cattle-system/rancher-6b57df599f-kmqtx/rancher.log` :
> 
> ```
> 2024-06-24T13:50:09.875146853Z 2024/06/24 13:50:09 [ERROR] Unknown error: failed to create longhorn-system/cifs-secret /v1, Kind=Secret for 9916e367-0f91-4103-a954-972bf697c158: Secret in version "v1" cannot be handled as a Secret: illegal base64 data at input byte 2
> ```
> 
> It seems that the secret is not valid.

I don't know what I've done exactly at this time, but my current secret seems valid. I've tried to update the current secret (it is visible in rancher UI with good value and I do not get such log in rancher anymore. But still get the "backup target URL is empty"
