### ISSUE TITLE
[CI] Add SBOM files for container images to release note

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#8821]
Then, what we should do are:
- For self-owned images, sbom included
- For all images including mirrored and self-owned, sbom file attached to the release note 

The second item needs to be improved in the release process `longhorn/release` which is outside of this scope.

_Originally posted by @innobead in https://github.com/longhorn/longhorn/issues/5099#issuecomment-2188178296_

**Comment by yangchiu** [comment]
Generate sbom:
```
syft longhornio/support-bundle-kit:v0.0.33 -o json --platform=linux/amd64 > support-bundle-kit-v0.0.33-amd64.sbom
```

Sign sbom:
```
cosign sign-blob backing-image-manager-v1.6.0-amd64.sbom --output-certificate backing-image-manager-v1.6.0-amd64.pem --output-signature backing-image-manager-v1.6.0-amd64.sig -y
```

Verify signed sbom:
```
cosign verify-blob backing-image-manager-v1.6.0-amd64.sbom --cert backing-image-manager-v1.6.0-amd64.pem --signature backing-image-manager-v1.6.0-amd64.sig --certificate-identity-regexp ".*" --certificate-oidc-issuer-regexp ".*"
```

**Comment by derekbit** [comment]
@yangchiu the feature is completed. Please update the status. Thank you.
