### ISSUE TITLE
[FEATURE] I wish I could check the Log for Recurring Job events in the Longhorn UI.

### ISSUE THREAD

**Issue by bkkoli** [longhorn/longhorn#8823]
## Is your feature request related to a problem? Please describe (👍 if you like this request)
Unable to check the log for Recurring Job.

## Describe the solution you'd like
I wish I could check the Log for Recurring Job events in the Longhorn UI.
For example, when I click Longhorn Volume, I think it's good to have a screen below that shows the log for Recurring Job like Event Log.
![image](https://github.com/longhorn/longhorn/assets/41296400/744752ca-4b1e-45dd-ac57-ac9aa6c6577c)

**Comment by DamiaSan** [comment]
Maybe it could be done together with https://github.com/longhorn/longhorn/issues/8404
cc @derekbit @innobead

**Comment by bkkoli** [comment]
@DamiaSan 
> Maybe it could be done together with https://github.com/longhorn/longhorn/issues/8404
Thank you for your kind reply.
