### ISSUE TITLE
UI: Show latest backup's workload info in the backup list

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#883]
We have the information displayed in the volume list page. It would be good for user to see it in the backup volume and backup page directly as well.

**Comment by yasker** [comment]
#218 fixed the backup page. I am not sure if backend provides information for the `backup volume` page. If not, we should add it and make it possibe for the backup volume page to show more Kubernetes information as well.

**Comment by meldafrawi** [comment]
Validation: **PASS**

Steps to test:
  - Create a volume used by some workload
  - Create a backup for volume.
  - In backup list page, workload info should be found backup **(PASS)**
