### ISSUE TITLE
[TASK] Update nvme-cli to v2.9.1 for v2 data engine

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8836]
## What's the task? Please describe

v2.7.1 is outdated. Update it to the latest version.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240701**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/765a34927cc54f3af5a0c6d0acb2690ed053fa03
- longhorn-instance-manager `master-head` https://github.com/longhorn/longhorn-instance-manager/commit/73cc005a5a22204486c4522606a16daaee7137d4
- longhorn-spdk-engine `main` https://github.com/longhorn/longhorn-spdk-engine/commit/c2002ae0216ff14f4b54cb2ba9649dd2ac41396a
- go-spdk-helper `main` https://github.com/longhorn/go-spdk-helper/commit/99b2a18336b501ab46bcf47772e568965b6d0b2c

**The test steps**
https://github.com/longhorn/longhorn/issues/8836#issuecomment-2192183576

**Result Passed**

V2 volume attachment and detachment are working normally.
