### ISSUE TITLE
[BUG] Can not add block disk - Failed to initialize OpenSSL

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#8846]
## Describe the bug

Add block disk failed and in the instance-manager pod can see below log:
```
> kl logs instance-manager-f38348e85d928834eb1da0d027d055bf
Enabling tgtd
tgtd: work_timer_start(146) use timer_fd based scheduler
tgtd: bs_init(387) use signalfd notification
Enabling spdk_tgt with options: -L all
Failed to initialize OpenSSL
139693425674688:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/etc/ssl/openssl-1_1.cnf','rb')
139693425674688:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
139693425674688:error:0E078072:configuration file routines:def_load:no such file:crypto/conf/conf_def.c:168:
[2024-06-28 02:29:21.516564] app.c: 393:app_setup_env: *ERROR*: Unable to initialize SPDK env
[2024-06-28 02:29:21.516685] app.c: 605:unclaim_cpu_cores: *ERROR*: Failed to unlink lock fd for core 0, errno: 2
```

environment check all passed
```bash
> bash -c "$(curl -sfL https://raw.githubusercontent.com/longhorn/longhorn/master/scripts/environment_check.sh)" -s -s
[INFO]  Required dependencies 'kubectl jq mktemp sort printf' are installed.
[INFO]  All nodes have unique hostnames.
[INFO]  Waiting for longhorn-environment-check pods to become ready (0/3)...
[INFO]  All longhorn-environment-check pods are ready (3/3).
[INFO]  MountPropagation is enabled
[INFO]  Checking kernel release...
[INFO]  Checking iscsid...
[INFO]  Checking multipathd...
[INFO]  Checking packages...
[INFO]  Checking nfs client...
[INFO]  Checking x86-64 SSE4.2 instruction set...
[INFO]  Checking kernel module nvme_tcp...
[INFO]  Checking kernel module uio_pci_generic...
[INFO]  Checking hugepage...
[INFO]  Cleaning up longhorn-environment-check pods...
[INFO]  Cleanup completed.
```

## To Reproduce

Setup v2 data engine environment then add block disk.
The block disk kept in Unschedulable state.

## Expected behavior

The block disks all schedulable

## Support bundle for troubleshooting

[supportbundle_5eac64ee-9482-4a4a-a3e3-5bdef19421c1_2024-06-28T02-31-20Z.zip](https://github.com/user-attachments/files/16023437/supportbundle_5eac64ee-9482-4a4a-a3e3-5bdef19421c1_2024-06-28T02-31-20Z.zip)

## Environment

 - Longhorn version: v1.7.0-dev
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.29.2+k3s1
 - Node config
   - OS type and version: SLES15 SP6
   - Kernel version: 6.4.0-150600.23.7-default

## Additional context

N/A

**Comment by derekbit** [comment]
cc @DamiaSan

**Comment by dfaltum** [comment]
https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP6/index.html#bsc-1220091

**Comment by derekbit** [comment]
> https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP6/index.html#bsc-1220091
> 
> There are some changes with openssl in SP6...

Yes, some dependencies are broken. I'm working on it...

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-instance-manager `73cc00`)

Add block disk and create workload with v2 volume scceed.
