### ISSUE TITLE
[BUG] Failed to backup snapshot: Internal error occurred: invalid character 'i' looking for beginning of value

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#8861]
## Describe the bug

Encounter error when creating backup:
```
Failed to backup snapshot: Internal error occurred: invalid character 'i' looking for beginning of value
```

```
{"actions":{},"code":"Internal Server Error","detail":"","links":{"self":"http://10.42.1.8:9500/v1/volumes/test-1"},"message":"failed to backup snapshot: Internal error occurred: invalid character 'i' looking for beginning of value","status":500,"type":"error"}
```

## To Reproduce

1. Create and attach a volume through Longhorn UI
2. Create a backup through Longhorn UI

## Support bundle for troubleshooting

[supportbundle_2355afcd-2c77-4fd0-9717-dc292510985f_2024-07-01T00-57-07Z.zip](https://github.com/user-attachments/files/16046893/supportbundle_2355afcd-2c77-4fd0-9717-dc292510985f_2024-07-01T00-57-07Z.zip)

## Environment

 - Longhorn version: master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:v1.30.0+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: sles 15-sp5
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by ChanYiLin** [comment]
The root cause is that the UI didn't support `backupMode` now
so the string is empty
I did add the webhook to patch the `backupMode` when it is empty
But I mistakenly used `%s` instead `"%s"` for the string, so it failed to parse the patch.

**Comment by ChanYiLin** [comment]
Hi @yangchiu 
Good catch!
Fixed the issues and tested in my local env.
Please check again, thanks

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 369be1a). Backups can be created and restored without problems.
