### ISSUE TITLE
[BUG] v2 volume snapshot invalid date

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#8862]
## Describe the bug

Create a snapshot for a v2 volume, the creation date displayed on the Longhorn UI is invalid:
![v2-snapshot](https://github.com/longhorn/longhorn/assets/5709208/8fbbdb0f-d6b2-4aac-8d04-d1fab7d9edf8)

```
$ kubectl get snapshots.longhorn.io -n longhorn-system
NAME                                   VOLUME   CREATIONTIME                                               READYTOUSE   RESTORESIZE   SIZE   AGE
0fc5d30b-a393-4dd4-8fc6-5118d1a9ded0   test-2   2024-07-01 01:46:03.736068555 +0000 UTC m=+116.286386614   true         2147483648    0      48s
```

## To Reproduce

Create a snapshot for a v2 volume.

## Environment

 - Longhorn version: master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: ubuntu 24.04
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by DamiaSan** [comment]
The creation time of the first snapshot, `b8f1f437`, is correctly displayed?
If so, is there a difference on how you created the 2 snapshots? Because I see that the `CREATIONTIME` have little differences.

**Comment by yangchiu** [comment]
> The creation time of the first snapshot, b8f1f437, is correctly displayed?

Snapshot `b8f1f437` is for a v1 volume. I've removed it from the description to avoid misleading.

**Comment by DamiaSan** [comment]
> > The creation time of the first snapshot, b8f1f437, is correctly displayed?
> 
> Snapshot `b8f1f437` is for a v1 volume. I've removed it from the description to avoid misleading.

It could be useful to understand what is the correct format accepted. For that v1 snapshot, the creation date displayed in the ui is the same returned by `kubectl get snapshots.longhorn.io -n longhorn-system`? I want to uderstand if the problem is only a formatting issue.

**Comment by derekbit** [comment]
@DamiaSan Any update for the issue?

**Comment by DamiaSan** [comment]
> @DamiaSan Any update for the issue?

I am waiting the response to the question of the previous comment:
For that v1 snapshot, the creation date displayed in the ui is the same returned by `kubectl get snapshots.longhorn.io -n longhorn-system`?
Could you reply @yangchiu? Thanks.

**Comment by roger-ryao** [comment]
Hi @DamiaSan 
     The `vol-0` is a `v2` volume and `vol-1` is a `v1` volume., the outpot as below.
```
ryao@ryao-laptop:~/Downloads/test-record> kubectl get snapshots.longhorn.io -n longhorn-system
NAME                                   VOLUME   CREATIONTIME                                               READYTOUSE   RESTORESIZE   SIZE        AGE
373e1839-23d3-4be6-ac8c-7c6b1cf040a0   vol-1    2024-07-03T03:25:32Z                                       true         2147483648    122847232   60s
c40445f6-9308-45ec-9e95-2e31cf53da3d   vol-0    2024-07-03 03:21:01.332717566 +0000 UTC m=+425.813353684   true         2147483648    130023424   5m29s
dc343c7b-7062-42cc-a3d0-5b22c4b0c8cc   vol-0    2024-07-03 03:21:05.985458188 +0000 UTC m=+430.466094368   true         2147483648    0           5m24s

```

**Comment by DamiaSan** [comment]
This PR https://github.com/longhorn/longhorn-spdk-engine/pull/171 shoudl fix the issue

**Comment by DamiaSan** [comment]
Hi @yangchiu and @roger-ryao ,
the PR with the fix has been merged, could you try again to see if the problem is solved?
Thanks

**Comment by derekbit** [comment]
@DamiaSan Don't forget to fill in the form of `Pre Ready-For-Testing Checklist` and update the status to `ready for testing`. Thank you.

**Comment by roger-ryao** [comment]
Hi @DamiaSan 
     We still observe the issue on `master-head`
     
![Screenshot_20240704_181811](https://github.com/longhorn/longhorn/assets/104337648/64c3460a-6d57-46ff-a67d-70ff501a999a)
[supportbundle_37e653c8-a49d-4a5e-9bc7-bc4da94633db_2024-07-04T10-15-36Z.zip](https://github.com/user-attachments/files/16097166/supportbundle_37e653c8-a49d-4a5e-9bc7-bc4da94633db_2024-07-04T10-15-36Z.zip)

**Comment by roger-ryao** [comment]
> kubectl get snapshots.longhorn.io -n longhorn-system
```
ryao@ryao-laptop:~/Downloads/test-record> kubectl get snapshots.longhorn.io -n longhorn-system
NAME                                   VOLUME   CREATIONTIME                                               READYTOUSE   RESTORESIZE   SIZE        AGE
b2bfcd9c-b71b-41bd-965c-086ad9b5b54a   vol-0    2024-07-04 10:13:56.081794351 +0000 UTC m=+115.025379249   true         2147483648    130023424   3h5m
```

**Comment by DamiaSan** [comment]
It seems that the [commit](https://github.com/longhorn/longhorn-spdk-engine/commit/5eb75317dcf9699a1f4a6b2058f48bb28f76ba24) which have fixed the issue is not in this environment, because the creation time is in the same format as before. Now instead it should be in the format `2006-01-02T15:04:05Z07:00` .
Could you check please before to go further in the investigation?
Thanks

**Comment by roger-ryao** [comment]
> It seems that the [commit](https://github.com/longhorn/longhorn-spdk-engine/commit/5eb75317dcf9699a1f4a6b2058f48bb28f76ba24) which have fixed the issue is not in this environment, because the creation time is in the same format as before. Now instead it should be in the format `2006-01-02T15:04:05Z07:00` . Could you check please before to go further in the investigation? Thanks

I think it is due to https://github.com/longhorn/longhorn-spdk-engine/actions/runs/9790569706 longhorn-spdk-engine build image failing. You could change the status to ready for testing again. I will test it later.

**Comment by DamiaSan** [comment]
> I think it is due to https://github.com/longhorn/longhorn-spdk-engine/actions/runs/9790569706 longhorn-spdk-engine build image failing. You could change the status to ready for testing again. I will test it later.

Done thanks.

**Comment by derekbit** [comment]
@roger-ryao is taking a leave today. Reassign to @yangchiu.

**Comment by yangchiu** [comment]
@derekbit How can we know the version of `longhorn-spdk-engine` used in `longhorn-instance-manager`? Is the dependency update like https://github.com/longhorn/longhorn-instance-manager/commit/60f01352c792909df67d79b117842cf6a069d2ab required to use the latest `longhorn-spdk-engine`?

**Comment by derekbit** [comment]
We don't have version control in longhorn-spdk-engine or now.

> Is the dependency update like https://github.com/longhorn/longhorn-instance-manager/commit/60f01352c792909df67d79b117842cf6a069d2ab required to use the latest longhorn-spdk-engine?

Yes, it is required. Any concern?

**Comment by DamiaSan** [comment]
Actually `longhorn-instance-manager` is usign the previos commit of `longhorn-spdk-engine` of the one with the fix. So, to test the fix, we should update it. @derekbit, in this case, who should do it, me or @yangchiu ? Just to understand the flow ...

**Comment by derekbit** [comment]
> Actually `longhorn-instance-manager` is usign the previos commit of `longhorn-spdk-engine` of the one with the fix. So, to test the fix, we should update it. @derekbit, in this case, who should do it, me or @yangchiu ? Just to understand the flow ...

Although renovate can automatically update them, it only works within the weekend.
Therefore, the feature owner needs to update the dependencies.
In this case, @DamiaSan needs to update `longhorn-spdk-engine` and then `longhorn-instance-manager`.

**Comment by DamiaSan** [comment]
PR for `longhorn-instance-manager` https://github.com/longhorn/longhorn-instance-manager/pull/544 with the `longhorn-spdk-engine` fixed

**Comment by DamiaSan** [comment]
The PR has been merged, now the `longhorn-instance-manager` contains the fix

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-instance-manager d68881c). Snapshot date is correctly displayed.

![snapshot](https://github.com/longhorn/longhorn/assets/5709208/171dd0b6-7d07-4e5e-aa38-e2f2e3961339)
