### ISSUE TITLE
[BUG] Helm upgrade from v1.6.2 to v1.7.0-dev failed due to the longhorn-post-upgrade job exceeding the BackoffLimit.

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#8866]
## Describe the bug

Upgrade longhorn from v1.6.2 to master(v1.7.0-dev) by helm will result in `longhorn-post-upgrade failed: BackoffLimitExceeded`

## To Reproduce

1. Install Longhorn v1.6.2 by helm
2. Upgrade Longhorn to v1.7.0-dev by helm
3. Longhorn pods image updated and running, but job longhorn-post-upgrade failed
```
> helm upgrade longhorn ./chart/ -n longhorn-system
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
Error: UPGRADE FAILED: post-upgrade hooks failed: 1 error occurred:
	* job longhorn-post-upgrade failed: BackoffLimitExceeded
```
```
> kl describe job longhorn-post-upgrade | grep Events -A20
Events:
  Type     Reason                Age   From            Message
  ----     ------                ----  ----            -------
  Normal   SuccessfulCreate      11m   job-controller  Created pod: longhorn-post-upgrade-p8ccf
  Normal   SuccessfulDelete      10m   job-controller  Deleted pod: longhorn-post-upgrade-p8ccf
  Warning  BackoffLimitExceeded  10m   job-controller  Job has reached the specified backoff limit
```

## Expected behavior

 Job longhorn-post-upgrade complete without problem.

## Support bundle for troubleshooting

[supportbundle_dbccdb65-497a-4251-bfa9-d362f3829be4_2024-07-02T03-01-53Z.zip](https://github.com/user-attachments/files/16061075/supportbundle_dbccdb65-497a-4251-bfa9-d362f3829be4_2024-07-02T03-01-53Z.zip)

## Environment

 - Longhorn version: v1.7.0-dev
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.29.2+k3s1
 - Node config
   - OS type and version: SLES 15 SP6
   - Kernel version: 6.4.0-150600.23.7-default

## Additional context

https://github.com/longhorn/longhorn/issues/8844

**Comment by derekbit** [comment]
cc @PhanLe1010 @c3y1huang

**Comment by chriscchien** [comment]
Verified  **pass** on longhorn master `c3e1f6`

Use helm upgrade Longhorn from v1.6.2 to master-head succeed. After the upgrade completed, volume attach/detach, read/write worked properly.
