### ISSUE TITLE
[BUG] Unable to create backup recurring job with label

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#8868]
## Describe the bug

On master-head, unable to create backup recurring job with label:

![recurring](https://github.com/longhorn/longhorn/assets/5709208/42211764-bdd5-4829-b33f-c5475a1bfec9)

![recurring01](https://github.com/longhorn/longhorn/assets/5709208/59f5d5ba-0ce4-4f98-8ffb-b10b63e789e5)

```
failed to create recurring job c-sz7neh: admission webhook "validator.longhorn.io" denied the request: failed to validate recurring job backup task parameters: key:value is not a valid parameter
```

https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/961/testReport/tests/test_recurring_job/test_recurring_job_labels_s3_/

## To Reproduce

Create backup recurring job with label through Longhorn UI

## Environment

 - Longhorn version: master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: sles 15-sp5
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
cc @ChanYiLin

**Comment by ChanYiLin** [comment]
The root cause of the bug is a typo

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 15a769a). Backup recurring job can be created with label.
