### ISSUE TITLE
[BUG] No replica is created after increased replica count

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#8871]
## Describe the bug

Test case `test_extra_replica_cleanup` fails on master-head because it expects a unschedulable replica will be created after updated the volume replica count from `3` to `4`:

https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/961/testReport/tests/test_ha/test_extra_replica_cleanup/

```
client = <longhorn.Client object at 0x7f7d0d77b150>
volume_name = 'longhorn-testvol-ojrmht', settings_reset = None

    def test_extra_replica_cleanup(client, volume_name, settings_reset): # NOQA
        """
        Test extra failed to scheduled replica cleanup
        when no eviction requested
    
        1. Make sure 'Replica Node Level Soft Anti-Affinity' is disabled.
        2. Create a volume with 3 replicas.
        3. Attach the volume to a node and write some data to it and
        save the checksum.
        4. Increase the volume replica number to 4.
        5. Volume should show failed to schedule and an extra stop replica.
        6. Decrease the volume replica number to 3.
        7. Volume should show healthy and the extra failed to scheduled replica
        should be removed.
        8. Check the data in the volume and make sure it's same as the checksum.
        """
        replica_node_soft_anti_affinity_setting = \
            client.by_id_setting(SETTING_REPLICA_NODE_SOFT_ANTI_AFFINITY)
        try:
            client.update(replica_node_soft_anti_affinity_setting,
                          value="false")
        except Exception as e:
            print("\nException when update "
                  "Replica Node Level Soft Anti-Affinity setting",
                  replica_node_soft_anti_affinity_setting)
            print(e)
    
        host_id = get_self_host_id()
        volume = create_and_check_volume(client, volume_name, num_of_replicas=3)
    
        volume = volume.attach(hostId=host_id)
        volume = wait_for_volume_healthy(client, volume_name)
        data = write_volume_random_data(volume)
        volume = volume.updateReplicaCount(replicaCount=4)
>       wait_for_volume_replica_count(client, volume_name, 4)

test_ha.py:1969: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

client = <longhorn.Client object at 0x7f7d0d77b150>
name = 'longhorn-testvol-ojrmht', count = 4

    def wait_for_volume_replica_count(client, name, count):
        wait_for_volume_creation(client, name)
        for i in range(RETRY_COUNTS):
            volume = client.by_id_volume(name)
            if len(volume.replicas) == count:
                break
            time.sleep(RETRY_INTERVAL)
>       assert len(volume.replicas) == count
E       AssertionError

common.py:2044: AssertionError
``` 

But on master-head, no extra replica will be created after the update:
![extra](https://github.com/longhorn/longhorn/assets/5709208/f3c2fa5e-e042-47c2-8e08-60118a7f9480)

## To Reproduce

Run test case `test_extra_replica_cleanup`.

## Environment

 - Longhorn version: master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1 
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: sles 15-sp5
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by c3y1huang** [comment]
This behavior is expected following the changes in https://github.com/longhorn/longhorn-manager/pull/2918. We implemented a precheck before creating a new Replica CR, so no new Replica will be created is no suitable node and disk are available.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-test `d3a059`) by run `test_replica_should_not_be_created_when_no_suitable_node_found` 5 times all [passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7112/testReport/tests/test_ha/).
