### ISSUE TITLE
[BUG] Failed to create a new replica after an existing replica node becomes unschedulable

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#8872]
## Describe the bug

Test case `test_node_eviction_no_schedulable_node` fails on master-head:

https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/961/testReport/tests/test_node/test_node_eviction_no_schedulable_node/

```
client = <longhorn.Client object at 0x7f7cfcb94650>
core_api = <kubernetes.client.api.core_v1_api.CoreV1Api object at 0x7f7d0cdb8c10>
csi_pv = {'apiVersion': 'v1', 'kind': 'PersistentVolume', 'metadata': {'name': 'longhorn-testvol-ojl4wd'}, 'spec': {'accessMode...aleReplicaTimeout': '30'}, 'volumeHandle': 'longhorn-testvol-ojl4wd'}, 'persistentVolumeReclaimPolicy': 'Delete', ...}}
pvc = {'apiVersion': 'v1', 'kind': 'PersistentVolumeClaim', 'metadata': {'name': 'longhorn-testvol-ojl4wd-pvc'}, 'spec': {'a...'resources': {'requests': {'storage': '1073741824'}}, 'storageClassName': '', 'volumeName': 'longhorn-testvol-ojl4wd'}}
pod_make = <function pod_make.<locals>.make_pod at 0x7f7cfd2abba0>
volume_name = 'longhorn-testvol-ojl4wd', settings_reset = None

    def test_node_eviction_no_schedulable_node(client, core_api, csi_pv, pvc, pod_make, volume_name, settings_reset): # NOQA
        """
        Test node eviction (assuming this is a 3 nodes cluster)
    
        1. Disable scheduling on node 3.
        2. Create pv, pvc, pod with volume of 2 replicas.
        3. Write some data and get the checksum.
        4. Disable scheduling and set 'Eviction Requested' to 'true' on node 1.
        5. Volume should be failed to schedule new replica.
        6. Set 'Eviction Requested' to 'false' to cancel node 1 eviction.
        7. Check replica has the same hostID.
        8. Check volume data checksum.
        """
        nodes = client.list_node()
        node1 = nodes[0]
        node3 = nodes[2]
    
        # schedule replicas to node 1, 2
        set_node_scheduling(client, node3, allowScheduling=False, retry=True)
    
        data_path = "/data/test"
        pod_name, _, _, created_md5sum = \
            common.prepare_pod_with_data_in_mb(client, core_api, csi_pv,
                                               pvc, pod_make, volume_name,
                                               data_path=data_path,
                                               num_of_replicas=2)
    
        volume = wait_for_volume_healthy(client, volume_name)
        assert len(volume.replicas) == 2
    
        created_replicas = {}
        for r in volume.replicas:
            assert r.mode == "RW"
            assert r.running is True
            created_replicas[r.name] = r["hostId"]
    
        set_node_scheduling_eviction(client,
                                     node1,
                                     allowScheduling=False,
                                     evictionRequested=True,
                                     retry=True)
>       wait_for_volume_replica_count(client, volume_name, 3)

test_node.py:2345: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

client = <longhorn.Client object at 0x7f7cfcb94650>
name = 'longhorn-testvol-ojl4wd', count = 3

    def wait_for_volume_replica_count(client, name, count):
        wait_for_volume_creation(client, name)
        for i in range(RETRY_COUNTS):
            volume = client.by_id_volume(name)
            if len(volume.replicas) == count:
                break
            time.sleep(RETRY_INTERVAL)
>       assert len(volume.replicas) == count
E       AssertionError

common.py:2044: AssertionError
```

Because it expects the volume tries to schedule a new replica after an existing replica node becomes unschedulable.

On master-head, nothing happened after disabled an existing replica node scheduling and requested eviction:
![master](https://github.com/longhorn/longhorn/assets/5709208/0a064f97-1bee-4263-af22-d481fb1b86f2)

On v1.6.2, a new replica will be created after disabled an existing replica node scheduling and requested eviction:
![v162](https://github.com/longhorn/longhorn/assets/5709208/c0d36745-fb79-4892-acb3-a8cc87def4b2)

## To Reproduce

Run test case `test_node_eviction_no_schedulable_node`.

## Environment

 - Longhorn version: master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1 
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: sles 15-sp5
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by c3y1huang** [comment]
Need to fix the test case, same reason as https://github.com/longhorn/longhorn/issues/8871#issuecomment-2202226046.

I will fix the volume condition in https://github.com/longhorn/longhorn-manager/pull/2939.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240703**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/c3e1f66bd67f5eeec837a5ee6522ac17391031ff
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/369be1a74cafa9fd84492ca30507ff81df0906f9


**Result Passed**

The `test_node_eviction_no_schedulable_node` test passed 10 times : https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7135/
