### ISSUE TITLE
[BUG] sparse-tools ci test is failed due to race condition 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8880]
## Describe the bug

https://github.com/longhorn/sparse-tools/actions/runs/9755401075

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by chriscchien** [comment]
Close this ticket as the issue resolved after fix merged
- https://github.com/longhorn/sparse-tools/actions/runs/9770054062
- https://github.com/longhorn/sparse-tools/actions/runs/9770195279
