### ISSUE TITLE
[TASK] Update the best practice page to mention some broken kernels

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#8881]
Broken kernels are mentioned at https://longhorn.io/kb/troubleshooting-rwx-volume-fails-to-attached-caused-by-protocol-not-supported/

**Comment by PhanLe1010** [comment]
## Test plan:

No test plan is needed for this ticket

**Comment by yangchiu** [comment]
Verification passed. The updated information can be found at https://longhorn.io/docs/1.7.0/best-practices/#operating-system.
