### ISSUE TITLE
UPGRADE FAILED: updates to provisioner are forbidden.

### ISSUE THREAD

**Issue by pucojazu** [longhorn/longhorn#889]
Hello,

I tried to upgrade from 0.6.2 to 0.7.0 on my Rancher v2.3.2 cluster.

Now the app has the following error:
`Failed to install app longhorn. Error: UPGRADE FAILED: StorageClass.storage.k8s.io "longhorn" is invalid: provisioner: Forbidden: updates to provisioner are forbidden.`

The longhorn-driver-deployer workload is stuck in "Initializing".

**Comment by shuo-wu** [comment]
Please refer to [the upgrade doc](https://github.com/longhorn/longhorn/blob/v0.7.0/docs/upgrade-from-v0.6.2-to-v0.7.0.md#error-longhorn-is-invalid-provisioner-forbidden-updates-to-provisioner-are-forbidden) for this issue.

For the `longhorn-driver-deployer`, you can delete the related pending/error **pod** and wait for recreation after the upgrade success.

**Comment by pucojazu** [comment]
Ah, that helped. Thank you! :)
