### ISSUE TITLE
[BUG] [INFRA] IMPORTANT: Longhorn Chart URL is not found 404

### ISSUE THREAD

**Issue by sjafarli** [longhorn/longhorn#8897]
## Describe the bug

The website is not working since yesterday at least https://charts.longhorn.io

## To Reproduce

Go to https://charts.longhorn.io

## Expected behavior

Should show the chart

**Comment by derekbit** [comment]
@innobead What we can do for this?

**Comment by leonardo-gomes-oceaneering** [comment]
We are currently blocked, since we cannot get the charts from [charts.longhorn.io](https://charts.longhorn.io/).

**Comment by derekbit** [comment]
Feel free to reopen this if it's valid. Thanks.
