### ISSUE TITLE
How to view data mounted to longhorn

### ISSUE THREAD

**Issue by yl-yue** [longhorn/longhorn#890]
When I found that I couldn't see the container-mounted data in the longhorn UI, I was puzzled that if the container was wrong and needed to directly manipulate the mounted data, the problem would be uncontrollable.

I also tried to find a way to see the mount data in longhorn, but it didn't work out very well

Hope to get help here, thank you

**Comment by yl-yue** [comment]
Now I find a way to identify the host by looking at the details of the volume and then executing the LSBLK command to find the mount point.

But it is not clear whether this is the right approach, or whether longhorn should provide a similar functional UI.

**Comment by yasker** [comment]
@yl-yue Longhorn provides the block device. You can find the device in the volume details page. The block device is not necessarily already mounted on the node, so use `lsblk -f` or `mount` to find the mount point is recommended if needed.

**Comment by yl-yue** [comment]
Thanks for dispelling doubts @yasker

**Comment by yl-yue** [comment]
`df -h` looks at all mount points and finds the `pv` volume mount directory
