### ISSUE TITLE
[BUG] Volume faluted when multiple nodeSelector or nodeSelector set.

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#8903]
## Describe the bug

Volume faluted when multiple nodeSelector set.

## To Reproduce

1. Set node1 with nodeTag: [node1], diskTag:[disk1]
2. Set node2 with nodeTag: [node2], diskTag:[disk2]
3. Create volume from UI , set Node Tag field to node1 and node2, the volume faulted
4. Create volume from UI , set Disk Tag field to node2 and disk2, the volume faulted
5. Create volume from kubectl with multiple diskSelector set, the volume faluted
```
  diskSelector:
  - disk1
  - disk2
```

## Expected behavior

- Block multiple value of `nodeSelector` and `diskSelector` set to volume from kubectl or UI
- Or replica schedule by set of tags

## Support bundle for troubleshooting

N/A

## Environment

 - Longhorn version:  v1.7.0-dev
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.29.2+k3s1
 - Node config
   - OS type and version: SLES 15 SP6
   - Kernel version: 6.4.0-150600.23.7-default

## Additional context

N/A

**Comment by chriscchien** [comment]
Consulted with @ChanYiLin , from our [doc](https://longhorn.io/docs/1.6.2/nodes-and-volumes/nodes/storage-tags/#usage), this ticket ls a false alarm because all tags should on a single node or disk 
```
When multiple tags are specified for a volume, the disk and the node (the disk belong to) must have all the specified tags to become usable.
```

**Comment by ChanYiLin** [comment]
Discussed with @chriscchien and @derekbit 
The tags here is for setting the characteristic for a set of disks
for example: 
- users may label all the ssd disks with the tags: ["ssd"]
- users may label all the fast disks with the tags: ["fast"]
so there are three set of disks
1. tags: []
2. tags: ["ssd"]
3. tags: ["ssd", "fast"]

so if users want to schedule the volume to such ssd and fast disks, they should add the selectors: ["ssd", "fast"], then the disks will only be scheduled to `set3`
But if users only want to schedule to the ssd volume and don't care if it is slow, they should add the selectors: ["ssd"], then the disks will be scheduled to `set2` and `set3`

> When multiple tags are specified for a volume, the disk and the node (the disk belong to) must have all the specified tags to become usable.

In other words, the selectors of a volume **need to be a subset of** the tags of the nodes/disks can it be scheduled on that nodes/disks
