### ISSUE TITLE
Display issue - S3 backup target

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#892]
The colons in the url aren't shown

![image](https://user-images.githubusercontent.com/28725423/69002627-fd9eb080-08c0-11ea-9579-a2f834099a80.png)

**Comment by yasker** [comment]
Looking at this issue and https://github.com/longhorn/longhorn/issues/904 , I am wondering if there is something wrong with the font by the browser? Obviously we won't remove/replace ":" or "9" from the string. And this one is even a user input.
