### ISSUE TITLE
Longhorn Backup Target not changed when upgraded

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#893]
Upgrading to a different `Backup Target`, the UI still shows the old Target

**Comment by yasker** [comment]
Can you share the reproduce steps? Make sure you click the `Save` in the bottom of settings.

**Comment by ainiml** [comment]
> Can you share the reproduce steps? Make sure you click the `Save` in the bottom of settings.

Sure!

1. Deploy Longhorn
2. Upgrade Longhorn from Rancher UI
3. Longhorn UI doesn't reflect changes to replica count

**Comment by shuo-wu** [comment]
The Longhorn settings in the Rancher UI are only for the new Longhorn and don't work for the existing Longhorn (during the upgrade). 

If you want to update the settings, you can modify them in Longhorn UI.

**Comment by ainiml** [comment]
> The Longhorn settings in the Rancher UI are only for the new Longhorn and don't work for the existing Longhorn (during the upgrade).
> 
> If you want to update the settings, you can modify them in Longhorn UI.

Is there a reason for the disconnect between the two? Or will that be fixed before the GA release?
