### ISSUE TITLE
[BUG] Can't retrieve data stored on volume using directions in the documentation

### ISSUE THREAD

**Issue by DerPhysikeR** [longhorn/longhorn#8939]
## Describe the bug

I want to offline retrieve the data stored in a longhorn volume, because the cluster doesn't exist any more.
I tried to use the directions in the documentation https://longhorn.io/docs/1.6.2/advanced-resources/data-recovery/export-from-replica/ but they don't seem to work.

## To Reproduce

 1. Copy `replicas` directory from offline cluster to local machine
 2. Look at meta data of volume using:

```sh
❯ cat pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d/volume.meta
{"Size":8589934592,"Head":"volume-head-001.img","Dirty":true,"Rebuilding":false,"Error":"","Parent":"volume-snap-15d8c57a-eebd-4f53-922b-1e53d570303a.img","SectorSize":512,"BackingFilePath":""}
```
 3. Run the docker command described in the documentation, to get a new device under `/dev/longhorn`.

```
docker run -v /dev:/host/dev -v /proc:/host/proc -v pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d:/volume --privileged longhornio/longhorn-engine:v1.6.2 launch-simple-longhorn pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d 8589934592 
```
 4. Get the following output, indicating a missing executable called `iscsiadm` inside the container.

```
+ set -e
+ mount --rbind /host/dev /dev
+ volume=pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d
+ size=8589934592
+ frontend=
+ '[' -z pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d ']'
+ '[' -z 8589934592 ']'
+ '[' -z ']'
+ echo Use default frontend TGT block device
Use default frontend TGT block device
+ frontend=tgt-blockdev
+ exec longhorn-instance-manager daemon
+ start
+ set +e
+ true
+ /usr/local/bin/grpc_health_probe -addr localhost:8500
time="2024-07-05T15:09:26Z" level=info msg="Storing process logs at path: /var/log/instances"
[longhorn-instance-manager] time="2024-07-05T15:09:26Z" level=info msg="Instance Manager listening to localhost:8500"
status: SERVING
+ [[ 0 -eq 0 ]]
+ echo longhorn instance manager is ready
+ break
+ set -e
longhorn instance manager is ready
+ tgtd -f
+ longhorn-instance-manager process create --name pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-r --binary /usr/local/bin/longhorn --port-count 15 --port-args --listen,localhost: -- replica /volume/ --size 8589934592
+ tee /var/log/tgtd.log
[longhorn-instance-manager] time="2024-07-05T15:09:26Z" level=info msg="Process Manager: prepare to create process pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-r"
[longhorn-instance-manager] time="2024-07-05T15:09:26Z" level=info msg="Process Manager: created process pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-r"
{
	"name": "pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-r",
	"binary": "/usr/local/bin/longhorn",
	"args": [
		"replica",
		"/volume/",
		"--size",
		"8589934592",
		"--listen",
		"localhost:10000"
	],
	"portCount": 15,
	"portArgs": [
		"--listen,localhost:"
	],
	"processStatus": {
		"state": "starting",
		"errorMsg": "",
		"portStart": 10000,
		"portEnd": 10014
	},
	"deleted": false
}
+ sleep 5
tgtd: iser_ib_init(3431) Failed to initialize RDMA; load kernel modules?
tgtd: work_timer_start(146) use timer_fd based scheduler
tgtd: bs_init(387) use signalfd notification
[pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-r] time="2024-07-05T15:09:26Z" level=info msg="Listening on data server localhost:10001"
[pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-r] time="2024-07-05T15:09:26Z" level=info msg="Listening on gRPC Replica server localhost:10000"
time="2024-07-05T15:09:26Z" level=info msg="Listening on sync agent server localhost:10002"
[pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-r] time="2024-07-05T15:09:26Z" level=info msg="Listening on sync localhost:10002"
[longhorn-instance-manager] time="2024-07-05T15:09:26Z" level=info msg="Process pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-r has started at localhost:10000"
+ longhorn-instance-manager process create --name pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-e --binary /usr/local/bin/longhorn --port-count 1 --port-args --listen,localhost: -- controller pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d --frontend tgt-blockdev --replica tcp://localhost:10000
[longhorn-instance-manager] time="2024-07-05T15:09:31Z" level=info msg="Process Manager: prepare to create process pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-e"
[longhorn-instance-manager] time="2024-07-05T15:09:31Z" level=info msg="Process Manager: created process pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-e"
{
	"name": "pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-e",
	"binary": "/usr/local/bin/longhorn",
	"args": [
		"controller",
		"pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d",
		"--frontend",
		"tgt-blockdev",
		"--replica",
		"tcp://localhost:10000",
		"--listen",
		"localhost:10015"
	],
	"portCount": 1,
	"portArgs": [
		"--listen,localhost:"
	],
	"processStatus": {
		"state": "starting",
		"errorMsg": "",
		"portStart": 10015,
		"portEnd": 10015
	},
	"deleted": false
}
[pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-e] time="2024-07-05T15:09:31Z" level=info msg="Starting with replicas [\"tcp://localhost:10000\"]"
time="2024-07-05T15:09:31Z" level=info msg="Connecting to remote: localhost:10000"
[pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-r] time="2024-07-05T15:09:31Z" level=info msg="New connection from: 127.0.0.1:59972"
time="2024-07-05T15:09:31Z" level=info msg="Opening volume /volume/, size 8589934592/512"
[pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-e] time="2024-07-05T15:09:31Z" level=info msg="Opening: localhost:10000"
[pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-e] time="2024-07-05T15:09:31Z" level=info msg="Adding backend: tcp://localhost:10000"
time="2024-07-05T15:09:31Z" level=info msg="Start monitoring tcp://localhost:10000"
time="2024-07-05T15:09:31Z" level=info msg="Get backend tcp://localhost:10000 revision counter 0"
[pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-e] time="2024-07-05T15:09:31Z" level=error msg="Failed to init frontend: device pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d: fail to stop SCSI device: Fail to logout target: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm --version], output , stderr, nsenter: failed to execute iscsiadm: No such file or directory\n, error exit status 1"
[pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-e] 2024/07/05 15:09:31 failed to init frontend: device pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d: fail to stop SCSI device: Fail to logout target: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm --version], output , stderr, nsenter: failed to execute iscsiadm: No such file or directory
, error exit status 1
[longhorn-instance-manager] time="2024-07-05T15:09:31Z" level=info msg="Process Manager: process pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-e error out, error msg: exit status 1"
[longhorn-instance-manager] time="2024-07-05T15:09:31Z" level=info msg="stop waiting for gRPC service of process pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d-e to start at localhost:10015"
```
## Expected behavior

A mountable device should appear under `/dev/longhorn/` from which I can retrieve the data stored on the volume.

## Support bundle for troubleshooting

Sorry, the cluster doesn't exist any more, but it ran v1.6.0 if that helps.

## Environment

 - Longhorn version: v1.6.0
 - Impacted volume (PV): pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d and two more
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): ArgoCD using this manifest https://raw.githubusercontent.com/longhorn/longhorn/v1.6.0/deploy/longhorn.yaml
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 0
 - Node config
   - OS type and version: -
   - Kernel version: -
   - CPU per node: 2
   - Memory per node: 4GB
   - Disk type (e.g. SSD/NVMe/HDD): -
   - Network bandwidth between the nodes (Gbps): -
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 3

## Additional context

After the cluster entered a failing state, because it ran out of resources, we decided to start over instead of trying to fix it.
It was essentially a playground, to gain experience, but the content of this image would still be very useful to retrieve.

**Comment by derekbit** [comment]
`failed to execute iscsiadm: No such file or directory`

Have you installed open-iscsi on your host?

**Comment by DerPhysikeR** [comment]
Thank you for your help. I didn't realize that this program, which is installed to `/usr/bin/iscsiadm` (which is not mounted into the container), has to be installed on the host, but installing `open-iscsi` and starting its associated service with `systemctl start iscsid.service` on my Arch Linux host system, made the creation of the device succeed.

Unfortunately, I still can't access the content, because I can't mount it.

When I try to run `mount -o ro /dev/longhorn/pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d /mnt` I get the error:

```
mount: /mnt: wrong fs type, bad option, bad superblock on /dev/longhorn/pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
```

and dmesg says

```
[31769.344872] FAT-fs (sdd): bogus number of reserved sectors
[31769.344880] FAT-fs (sdd): Can't find a valid FAT filesystem
```

Running a file system check with `fsck /dev/longhorn/pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d` returns:

```
fsck from util-linux 2.40.2
e2fsck 1.47.1 (20-May-2024)
ext2fs_open2: Bad magic number in super-block
fsck.ext2: Superblock invalid, trying backup blocks...
fsck.ext2: Bad magic number in super-block while trying to open /dev/longhorn/pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d

The superblock could not be read or does not describe a valid ext2/ext3/ext4
filesystem.  If the device is valid and it really contains an ext2/ext3/ext4
filesystem (and not swap or ufs or something else), then the superblock
is corrupt, and you might try running e2fsck with an alternate superblock:
    e2fsck -b 8193 <device>
 or
    e2fsck -b 32768 <device>

```

Am I still doing something wrong?

**Comment by derekbit** [comment]
Is it an ext4 filesystem or xfs?

**Comment by DerPhysikeR** [comment]
I didn't change the default set in https://raw.githubusercontent.com/longhorn/longhorn/v1.6.0/deploy/longhorn.yaml so it should be an ext4 file system, but when I run a few of the these commands https://unix.stackexchange.com/questions/53542/how-to-determine-the-filesystem-of-an-unmounted-device , none of them are able to detect the file system that is actually used.

blkid ignores the device and parted only outputs this for the longhorn device.

```
Error: /dev/sdd: unrecognised disk label
Model: IET VIRTUAL-DISK (scsi)                                            
Disk /dev/sdd: 1074MB
Sector size (logical/physical): 512B/512B
Partition Table: unknown
Disk Flags: 
```

Also, explicitly passing the file system to the mount command with `-t ext4` also doesn't work:

```
mount -t ext4 -o ro /dev/longhorn/pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d /mnt
mount: /mnt: wrong fs type, bad option, bad superblock on /dev/longhorn/pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
```

and the dmesg output is:

```
[76955.196452] EXT4-fs (sdd): VFS: Can't find ext4 filesystem
```

So it seems that the content of the disk image is completely broken or I am still doing something wrong.

**Comment by derekbit** [comment]
> So it seems that the content of the disk image is completely broken or I am still doing something wrong.

It seems yes. Do you have other replicas?

**Comment by DerPhysikeR** [comment]
On my local machine I have 3 images of 3 different volumes, if I am doing everything correctly, it seems all of them are broken.

There should still be the replicas from the other nodes, which I could retrieve to try the same. I will try that and come back to you.

I am just wondering, what's the probability that 3 out of 3 volumes from one node are broken as opposed to me still messing something up.

Anyway, thank you for your help so far.

**Comment by DerPhysikeR** [comment]
Ok, now I am sure I am doing something wrong. We were able to spin up the old cluster on another machine, with the same IP addresses, even rolled back to a working state. So I even have access to the longhorn dashboard. I checked the application relying on the volume, and it works, so I know the data is ok, although the dashboard tells me the volume is degraded, because the replica on one node seems to be broken.

So now I copied the volume directory to my local machine using scp from one of the good nodes. I even created a snapshot of the volume before doing that, to ensure I have a consistent state, because during the copying, the data could change, because I didn't shut down the pods.

And again, I get the exact same error.

Is it possible the filesystem of the volume got corrupted, because I didn't shut down the pod accessing it? If yes, is it possible to directly mount a snapshot of the volume instead of the current state of the volume to avoid that? When I look into the snapshots metadata information I don't get information about size, which is necessary for the docker command.

Now that the cluster is up again, maybe there is a way to circumvent longhorn altogether to rescue the data.

**Comment by DerPhysikeR** [comment]
Ok, I finally got it.

I mounted the volume on one working node of the restored cluster with `sudo mount /dev/longhorn/pvc-b7be9fee-a85a-4443-a938-232adf2cc3fa-6f3f286d /mnt` and then I rsynced the data to the new cluster.

Unfortunately, I was never able to mount a downloaded volume on my local machine, given the manual in the documentation.

Thank you for your help anyway!
