### ISSUE TITLE
[BUG] Create backup from UI volume page failed

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#8947]
## Describe the bug

Create backup from UI failed

![image](https://github.com/longhorn/longhorn/assets/73337386/324a818f-b06a-427f-9703-dbd18a3e507e)

longhorn-manager log
```
time="2024-07-08T03:54:17Z" level=info msg="Created snapshot c5d15f4d-19f8-4695-94e3-7deaa0590259 with labels map[] for volume pvc-33a6e312-5c9d-45e3-a4c4-6fab34442804" func="manager.(*VolumeManager).CreateSnapshot" file="engine.go:131"
10.42.0.1 - - [08/Jul/2024:03:54:17 +0000] "POST /v1/volumes/pvc-33a6e312-5c9d-45e3-a4c4-6fab34442804?action=snapshotCreate HTTP/1.1" 200 370 "https://54.85.75.150/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
time="2024-07-08T03:54:17Z" level=info msg="Forwarding request to 10.42.2.3:9500" func="api.(*Fwd).HandleProxyRequestByNodeID" file="forwarder.go:136"
time="2024-07-08T03:54:17Z" level=warning msg="HTTP handling error" func=api.NewRouter.HandleError.func39 file="router.go:21" error="failed to backup snapshot: json: cannot unmarshal object into Go struct field SnapshotInput.labels of type string"
```

## To Reproduce

0. Create volume backup from UI Volume Details page suceed. (https://{longorn IP}/#/volume/{volume name})
1. Create volume backup from UI Volume page, snapshot created but backup not and see error message pops(https://{longorn IP}/#/volume)

## Expected behavior

Create backup success

## Support bundle for troubleshooting

[supportbundle_444b7217-efd0-47e1-9d74-8e021eb88391_2024-07-08T03-56-52Z.zip](https://github.com/user-attachments/files/16122483/supportbundle_444b7217-efd0-47e1-9d74-8e021eb88391_2024-07-08T03-56-52Z.zip)

## Environment

 - Longhorn version: v1.7.0-dev
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.29.2+k3s1
 - Node config
   - OS type and version: SELS 15 SP6 
   - Kernel version: 6.4.0-150600.23.7-default

## Additional context

test_basic.py::test_backup passed on local

**Comment by derekbit** [comment]
cc @ChanYiLin @a110605

**Comment by chriscchien** [comment]
Hi @a110605 ,

I found the backup create fail can be reproduce from below steps

1. Create volume and attach to node
2. Nevigate to volume detail page
3. Create snapshot
4. Click the new create snaphost icon, click Backup on the drop down menu and then click OK
5. Backup can not create.

**Comment by a110605** [comment]
> Hi @a110605 ,
> 
> I found the backup creation fail can be reproduced from below steps
> 
> 1. Create volume and attach to node
> 2. Nevigate to volume detail page
> 3. Create snapshot
> 4. Click the new create snaphost icon, click Backup on the drop down menu and then click OK
> 5. Backup can not create.

Thanks for finding the bug, the reason is same as https://github.com/longhorn/longhorn-ui/pull/768

Fixed in https://github.com/longhorn/longhorn-ui/pull/769

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-ui **2079df**)

Full / incremental backup create success through below actions
- Create backup from http://${longhorn IP}/volume `Create Backup` icon
- Create backup from http://${longhorn IP}/volume/${volume name} `Create Backup` icon
- Create backup from http://${longhorn IP}/volume/${volume name} `Take Sanpshot` -> `Backup` icon
