### ISSUE TITLE
Node unscheduable after reboot

### ISSUE THREAD

**Issue by chrisbulgaria** [longhorn/longhorn#895]
Lonhorn 0.7.0 - latest and greatest. Kubernetes 1.15.5. rancher RKE.

After a reboot of the node (a VM) it became unscheduable - showing size 0.
All longhorn pods up and healthy. 
Tried to restart manager, engine, csi attacher - no effect.
What helped in the end is moving replicas to healthy node, deleting disk from longhorn UI and recreating it (same path).

I created support bundle, will send it.

**Comment by shuo-wu** [comment]
The log in the support bundle indicates that the file system ID of your data path somehow gets changed or Longhorn cannot get the fs info, then the Longhorn set the available size of the disk to 0. 
Longhorn uses the following command to get the fs info. You can try it on your that host.
```
"stat" "-fc" "{\"path\":\"%n\",\"fsid\":\"%i\",\"type\":\"%T\",\"freeBlock\":%f,\"totalBlock\":%b,\"blockSize\":%S}" "<Your data path>"
``` 

And I cannot reproduce it by simply rebooting a node. Could you provide me the reproduce step?

**Comment by chrisbulgaria** [comment]
Works now perfectly fine
stat -fc '%n %i %T %T %b %S'   /data/longhorn
/data/longhorn fd0500000000 xfs xfs 13099777 4096

(but works as well from longhorn after recreating the disk in longhorn UI).

As I cant easily reboot nodes now - will wait for the next occurrence and then try to gather more information.
Thanks.

**Comment by chrisbulgaria** [comment]
forgot free block - as well fine:
stat -fc '%n %i %T %T %f %b %S'   /data/longhorn
/data/longhorn fd0500000000 xfs xfs 11748654 13099777 4096

**Comment by shuo-wu** [comment]
OK. You can try this command if you encounter the same issue in the future to see what happens.
