### ISSUE TITLE
[IMPROVEMENT][UI] Add backupBackingImage table in backup page with tabs 

### ISSUE THREAD

**Issue by a110605** [longhorn/longhorn#8956]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

From https://github.com/longhorn/longhorn/issues/7541 demo feedback, it's nice to add backupBackingImage table in backup page that user can see all types of backups in the backup page .

We could consider implement it in v1.8.0

## Describe the solution you'd like

Tasks
- [ ] using [tabs](https://ant.design/components/tabs) to separate `volume backup` and `backing image backup`
- [ ] add backup backing image table in the second tabs

**Comment by a110605** [comment]
cc @derekbit , @shuo-wu

**Comment by houhoucoop** [comment]
Should we consider if the tab can be accessed via URL?
just wondering if the table gets more complex or many buttons, would it be better to split it into two pages?

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-ui/commit/944339c2d6deea41bb7e3d778757376fd9aa7f4e) with test [steps](https://github.com/longhorn/longhorn/issues/8956#issuecomment-2540439913)

**Comment by a110605** [comment]
Search in volume tab has some problem, open the ticket to fix the bug. https://github.com/longhorn/longhorn/issues/9974
cc @chriscchien
