### ISSUE TITLE
[DOC] Upgrading Kubernetes: Re-provisioning

### ISSUE THREAD

**Issue by guettli** [longhorn/longhorn#8961]
## What's the document you plan to update? Why? Please describe

The current docs about upgrading Kubernetes only explain [in-place upgrade](https://longhorn.io/docs/1.6.2/maintenance/maintenance/#upgrading-kubernetes)

## Additional context

We would like to know how to handle the re-provisioning of a node. The node-name stays constant, but it gets removed and added to the cluster again.

We use Cluster-API with baremetal servers.

Does re-provisioning of bare-meta servers need manual action, or is there an automated way, so that Longhorn detects the disks again?

Example: The server has two disks. One for Kubernetes and one for the data.

During an upgrade the first disk gets re-installed completely:  a new OS and new Kubernetes gets installed.

After that the second disk (data-disk) should be usable again.

How do you handle that?

**Comment by c3y1huang** [comment]
https://longhorn.io/docs/1.6.2/maintenance/maintenance/#reusing-the-node-name

**Comment by guettli** [comment]
@c3y1huang Thank you for looking into that issue.

From the docs [re-using node name](https://longhorn.io/docs/1.6.2/maintenance/maintenance/#reusing-the-node-name)

> These steps also apply if you’ve replaced a node using the same node name. Longhorn will recognize that the disks are different once the new node is up. You will need to remove the original disks first and add them back for the new node if it uses the same name as the previous node.

Our hard requirements are 100% automation. A manual action in the Longhorn UI does not solve that.

I created a feature request: https://github.com/longhorn/longhorn/issues/8962

I am looking for your feedback. What do you think about that?
