### ISSUE TITLE
[BUG][UI] Snapshots and Backups content not alignment in volume detail page of a restored v2 volume 

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#8964]
## Describe the bug

`Snapshots and Backups` content not alignment in detail page of restored v2 volume 

![image](https://github.com/longhorn/longhorn/assets/73337386/4be3e35c-c076-4228-a243-977e4e96d747)

## To Reproduce

1. From backup, restore a v2 volume to v2 volume `res-vol`
2. Create PVC `res-vol` of volume `res-vol`
3. Create a workload to mount PVC `res-vol`
4. After volume `res-vol` healthy, nevigate to volume detail page
5. Snapshots and Backups content not alignment

## Expected behavior

Snapshots and Backups content alignment as usual.

## Support bundle for troubleshooting

N/A

## Environment

 - Longhorn version: v1.7.0-dev (longhorn-ui `aa896b`)

## Additional context

N/A

**Comment by derekbit** [comment]
cc @a110605

**Comment by a110605** [comment]
The `created` is empty from `/v1/volumes/?action=snapshotList` causes UI render the line not on the same horizontal line. @derekbit ,could you help check why that created is empty?

![Uploading Screenshot 2024-07-10 at 5.35.40 PM.png…]()

**Comment by derekbit** [comment]
@DamiaSan The created flag lag is not set. Can you help check it? Thank you.

**Comment by DamiaSan** [comment]
I haven't still found anything that could cause this issue.
What version of `longhorn-instance-manager ` are you using? There was a bug about the creation date that has been resolved in this commit https://github.com/longhorn/longhorn-instance-manager/commit/63a153fa618b924a9c1d406ffcf6999cc42faa56

**Comment by derekbit** [comment]
> I haven't still found anything that could cause this issue. What version of `longhorn-instance-manager ` are you using? There was a bug about the creation date that has been resolved in this commit [longhorn/longhorn-instance-manager@63a153f](https://github.com/longhorn/longhorn-instance-manager/commit/63a153fa618b924a9c1d406ffcf6999cc42faa56)

Hello @DamiaSan 
Found the issue. It is due to the [missing timestamp and userCreated](https://github.com/longhorn/longhorn-spdk-engine/pull/176).

**Comment by roger-ryao** [comment]
**Verified on master-head 20240712**

- longhorn master-head https://github.com/longhorn/longhorn/commit/11066751cf818ddd93a4df0c457004e0fc95894c
- longhorn-spdk-engine main https://github.com/longhorn/longhorn-spdk-engine/commit/10fe17ff7e0d0434d135812b360cb1d02b897fbd
- longhorn-instance-manager master-head https://github.com/longhorn/longhorn-instance-manager/commit/f06a7b59038bea2611017d05ea86b4a464da6b72


**The test steps**

https://github.com/longhorn/longhorn/issues/8964#issue-2399652199


**Result Passed**

After restoring the v2 volume to a healthy state, the snapshots and backups content are all aligned on the volume detail page.
![Screenshot_20240712_153618](https://github.com/user-attachments/assets/1d32b197-a901-44b4-bca5-6ebef5a1f6f1)
