### ISSUE TITLE
Error deploying Longhorn on k3s: "invalid mount config for type 'bind'"

### ISSUE THREAD

**Issue by Yorny2101** [longhorn/longhorn#8966]
## Describe the bug

**Description:**
I encountered an error while deploying Longhorn on my k3s cluster. Some of the pods are failing to start due to an invalid mount configuration error. Below are the details of the environment and the errors observed.

**Error Details:**

`  kubectl get pods -n longhorn-system:`

```

csi-attacher-57689cc84b-hs9md                            1/1     Running              
csi-attacher-57689cc84b-ks5zx                               1/1     Running               
csi-attacher-57689cc84b-xwk46                              1/1     Running                
csi-provisioner-6c78dcb664-g57sj                           1/1     Running                
csi-provisioner-6c78dcb664-p96jx                           1/1     Running              
csi-provisioner-6c78dcb664-xsqlp                           1/1     Running               
csi-resizer-7466f7b45f-9dt4w                                  1/1     Running                
csi-resizer-7466f7b45f-bm2wg                                1/1     Running               
csi-resizer-7466f7b45f-g6mf2                                 1/1     Running               
csi-snapshotter-58bf69fbd5-tvhkj                           1/1     Running               
csi-snapshotter-58bf69fbd5-x96s2                         1/1     Running                
csi-snapshotter-58bf69fbd5-xd4v6                         1/1     Running                
engine-image-ei-acb7590c-snth5                           0/1     CreateContainerError  
engine-image-ei-acb7590c-tfsr8                            0/1     CreateContainerError   
engine-image-ei-acb7590c-wddkj                          0/1     CreateContainerError  
engine-image-ei-acb7590c-zjbjr                             0/1     CreateContainerError   
instance-manager-1                                               0/1     CreateContainerError  
instance-manager-f                                                0/1     CreateContainerError   
longhorn-csi-plugin-8kzsr                                      3/3     Running                
longhorn-csi-plugin-dkkdl                                      3/3     Running              
longhorn-csi-plugin-njsg5                                      3/3     Running           
longhorn-csi-plugin-wl789                                     3/3     Running              
longhorn-driver-deployer-576                                1/1     Running               
longhorn-driver-deployer-c7cc7                             0/1     Init:0/1            
longhorn-manager-56vxq                                      1/1     Running                
longhorn-manager-bnfn7                                      1/1     Running                
longhorn-manager-lt5mr                                       1/1     Running               
longhorn-manager-nfxtv                                       1/1     Running                
longhorn-ui-788ccbdc4c-hszc5                            1/1     Running               
longhorn-ui-788ccbdc4c-ztkfb                              1/1     Running               

```
Output of `kubectl describe pod instance-manager-f756536f9ab93dcf67fb4e3d8caefbea`:
_**Error: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.6.2**_

### Steps to Reproduce:

-     Deploy Longhorn on a k3s cluster using the provided manifests.
-     Observe the status of the pods in the longhorn-system namespace.
-     Check the detailed description of the failing pods.

### Expected Behavior:
All Longhorn pods should start successfully without any errors.

### Actual Behavior:
Several Longhorn pods fail to start with the error: `invalid mount config for type "bind": bind source path does not exist: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.6.2.`

 - Longhorn version: 1.6.2
 - Impacted volume (PV): 
 - Installation method : kubectl
 - Kubernetes distro and version: k3s, version: v1.29.5+k3s1
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 4
 - Node config
   - OS type and version: Ubuntu Server 22.04
   - CPU per node: 4
   - Memory per node: 4 GB
   - Disk type : HDD
 

## Additional context
I verified that the directory /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.6.2 does not exist on the node. I manually created this directory, but the issue persists. When I check again, the readiness probe fails, indicating there is still a problem.

**Comment by derekbit** [comment]
`/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.6.2/` is missing. 
Did you change anything inside the provided manifests?

**Comment by Yorny2101** [comment]
I did not modify the manifest. I attempted the installation with the following command:
`kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/deploy/longhorn.yaml`

**Comment by derekbit** [comment]
OK. It is due to the engine-image pod error 
```
engine-image-ei-acb7590c-snth5                           0/1     CreateContainerError  
engine-image-ei-acb7590c-tfsr8                            0/1     CreateContainerError   
engine-image-ei-acb7590c-wddkj                          0/1     CreateContainerError  
engine-image-ei-acb7590c-zjbjr                             0/1     CreateContainerError   
instance-manager-1                                               0/1     CreateContainerError  
instance-manager-f                                                0/1     CreateContainerError   
```

Can you describe the pods by 
```
kubectl -n longhorn-system describe <pod name>
```

**Comment by Yorny2101** [comment]
The output of that command is:

`invalid mount config for type "bind": bind source path does not exist: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.6.2.`

**Comment by derekbit** [comment]
Sorry, I mean **engine-image-ei** pod.

**Comment by GermanUribeB** [comment]
I'm experiencing the same issue ("/var/lib/longhorn/engine-binaries/ and /var/lib/longhorn/unix-domain-socket/ directories are missing"). Do you know why this is happening? When I manually create the missing directories, it works properly, but I want to understand why Longhorn is unable to create these directories during the installation? i have discarded folder permissions, host path permissions, cluster Nw policies and checking logs i couldn't find any error/event mentioning folder creation error. Please advice
