### ISSUE TITLE
UI: Fix the snapshot reverting message

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#897]
When a volume is attached and frontend enabled (e.g. not in the maintenance mode), the revert wouldn't be allowed. UI should prompt the user: `Cannot revert with frontend enabled. Please reattach the volume in maintenance mode to revert the volume. Workload shutdown might be needed`.

Now it prompts: "Volume may not be mounted on the host when reverting, otherwise it may cause filesystem error."

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
  - Create a volume, attach it to a node
  - Create snapshot
  - in volume details page, click on the snapshot
  > Expected result: Revert button is disabled & a tool tip contains the message `Cannot revert with frontend enabled. Please reattach the volume in maintenance mode to revert the volume. Workload shutdown might be needed` is displayed when hover on the button.  **(PASS)**
