### ISSUE TITLE
[BUG] Cannot do a Helm upgrade after PR 2763

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#8974]
## Describe the bug

It looks like the original plan for https://github.com/longhorn/longhorn/issues/7571 included modifying the Helm pre-upgrade check. Later, https://github.com/longhorn/longhorn-manager/pull/2763 moved the check to the node controller, but accidentally (I think) retained the environment check in `app/pre_upgrade.go`. This check doesn't work without the closed https://github.com/longhorn/longhorn/pull/8463, so Helm upgrades currently fail with the following message:

```
time="2024-07-10T20:24:53Z" level=info msg="Checking if the engine upgrade path from map[ei-b907910b:{Version: GitCommit: BuildDate: CLIAPIVersion:10 CLIAPIMinVersion:0 ControllerAPIVersion:5 ControllerAPIMinVersion:0 DataFormatVersion:0 DataFormatMinVersion:0}] is supported" func=util.checkEngineUpgradePath file="util.go:318" newEngineClientAPIMinVersion=8 newEngineClientAPIVersion=10 newEngineControllerAPIMinVersion=4 newEngineControllerAPIVersion=5
time="2024-07-10T20:24:53Z" level=fatal msg="Failed to run pre-upgrade" func=main.main.PreUpgradeCmd.func5 file="pre_upgrade.go:36" error="failed to check environment, please make sure you have iscsiadm/open-iscsi installed on the host: open /host/proc: no such file or directory"
```

## To Reproduce

Try to run `helm upgrade -n longhorn-system longhorn ./chart`.

## Expected behavior

The upgrade succeeds.

## Additional context

cc @mantissahz

**Comment by derekbit** [comment]
https://github.com/longhorn/longhorn-manager/pull/2763 does
1. check environment while starting daemon
2. check environment while pre-upgrade
3. periodically check environment and update to conditions

We should merge https://github.com/longhorn/longhorn/pull/8463 for the second check. Isn't it? @mantissahz

**Comment by mantissahz** [comment]
>We should merge https://github.com/longhorn/longhorn/pull/8463 for the second check. Isn't it? Accidentally closed? @mantissahz

Yes, I forgot that checking the iscsi iscsiadm/open-iscsi installed will use the shell command.
We

**Comment by mantissahz** [comment]
Update:
 
Tested the PR https://github.com/longhorn/longhorn/pull/8463, and it works to update Longhorn from 1.6.2 to 1.7.0-dev

**Comment by roger-ryao** [comment]
**Verified on master-head 20240711**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/40b4207c14fe95a6fc084c8600e90e7a9d947620


**The test steps**

https://github.com/longhorn/longhorn/issues/8974#issuecomment-2221421404


**Result Passed**

- [x] Successfully installed Longhorn.
- [x] Successfully created `workloads`, `volumes`, `snapshots`, `backups`, and `system backup`.
- [x] Successfully upgraded Longhorn from version `1.6.2` to `master-head`.
