### ISSUE TITLE
[TASK] Fix CVE issues for v1.7.0 (RC1)

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#8976]
## What's the task? Please describe

Investigate CVE issues of the Longhorn component images to see if there are outstanding CVE issues that need to be fixed.

## Describe the sub-tasks

https://github.com/longhorn/longhorn/blob/v1.7.x/deploy/longhorn-images.txt

## Additional context

`None`

**Comment by c3y1huang** [comment]
This is a general task. Not a blocker for RC releases.
cc @derekbit

**Comment by c3y1huang** [comment]
Analyse (WIP)

**Comment by mantissahz** [comment]
>longhornio/openshift-origin-oauth-proxy:4.14
longhornio/openshift-origin-oauth-proxy:4.14 (redhat 8.6)
=========================================================
Total: 25 (HIGH: 25, CRITICAL: 0)
@derekbit , @mantissahz , is this within our scope for CVE?

We just mirrored it from https://quay.io/repository/openshift/origin-oauth-proxy?tab=tags and I think we can update it to 4.15. And we had some tests on OKD 4.15 (https://github.com/longhorn/longhorn/issues/8300)

**Comment by c3y1huang** [comment]
## Action Plan

- **longhornio/longhorn-engine:** Update dependencies.
    - grpc_health_probe v0.4.28
- **longhornio/longhorn-instance-manager:** Update dependencies.
    - grpc_health_probe v0.4.28
- **longhornio/support-bundle-kit** Update base image.
    - Release v0.0.40
- **longhornio/csi-attacher:** Update version.
    - Current highest available minor version: `v4.6.1`
- **longhornio/csi-resizer:** Update version.
    - Current highest available minor version: `v1.11.1`.
- **longhornio/csi-node-driver-registrar:** Update version.
    - Current highest available minor version: `v2.10.1`.
- **longhornio/openshift-origin-oauth-proxy:** Update version.
    - This is not in scope, however, we can still update to the suggested version: `4.15`. Ref: https://github.com/longhorn/longhorn/issues/8976#issuecomment-2230147085
#### Won't Fix
- **longhornio/backing-image-manager:**
    - No CVE vulnerability detected.
- **longhornio/longhorn-manager:**
    - `go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc` is an indirect dependency, and the fixed version is not included in the current latest Kubernetes [v1.30.3](https://github.com/kubernetes/kubernetes/blob/v1.30.3/go.mod#L68) release. Its included in the incoming [v1.31.0](https://github.com/kubernetes/kubernetes/blob/v1.31.0-beta.0/go.mod#L206) release.
- **longhornio/longhorn-share-manager:**
    - No CVE vulnerability detected.
- **longhornio/longhorn-ui:**
    - No CVE vulnerability detected.
- **longhornio/csi-provisioner:**
    - The current version is the same as the highest available minor version: `v4.0.1`.
- **longhornio/csi-snapshotter:**
    - The current version is the same as the highest available minor version: `v7.0.2`.
- **longhornio/livenessprobe:**
    - The current version is the same as the highest available minor version: `v2.12.0`.

**Comment by c3y1huang** [comment]
All PRs have been merged. This doesn't require effort from @longhorn/qa , any issues introduced should be detected in the daily regression run. Closing.
