### ISSUE TITLE
[BUG] v2 volume data are not sync before taking a snapshot

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8977]
## Describe the bug

The [commit](https://github.com/longhorn/longhorn-spdk-engine/commit/da2a02e86462fb4f3abac4d0f91f2380ff34053c) results in a regression that v2 volume data are not sync before taking a snapshot.
[Using `sync` directly with a block device path](https://github.com/longhorn/longhorn-spdk-engine/commit/da2a02e86462fb4f3abac4d0f91f2380ff34053c) does not work as expected. 

According to the doc of the `sync` command, what it does is to synchronize the filesystem which contains the specified file. 

```
Usage: sync [OPTION] [FILE]...
Synchronize cached writes to persistent storage

If one or more files are specified, sync only them,
or their containing file systems.

  -d, --data             sync only file data, no unneeded metadata
  -f, --file-system      sync the file systems that contain the files
      --help     display this help and exit
      --version  output version information and exit

GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
Report any translation bugs to <https://translationproject.org/team/>
Full documentation <https://www.gnu.org/software/coreutils/sync>
or available locally via: info '(coreutils) sync invocation'
```
## To Reproduce

1. Create a v2 volume
2. dd 1G file without sync
3. Back up the volume immediately
4. Restore the volume
5. The data checksum is wrong

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
Hello @mantissahz 
Can you help the verification? Thanks.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-spdk-engine `10fe17`) with test [steps](https://github.com/longhorn/longhorn/issues/8977#issue-2402256367).
