### ISSUE TITLE
[BUG] Can not change `storage-network-for-rwx-volume-enabled` when RWX volume attached

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#8979]
## Describe the bug

Have storage network enabled,  `auto-delete-pod-when-volume-detached-unexpectedly` = `true` and RWX volume attached
Change setting `storage-network-for-rwx-volume-enabled`, the value will not applied
```
> kl get setting storage-network-for-rwx-volume-enabled
NAME                                     VALUE   APPLIED   AGE
storage-network-for-rwx-volume-enabled   false   false      9m1s
```
```
time="2024-07-11T08:58:31Z" level=warning msg="Failed to update setting: storage-network-for-rwx-volume-enabled" func="controller.(*SettingController).syncSetting.func2" file="setting_controller.go:246" controller=longhorn-setting error="Operation cannot be fulfilled on settings.longhorn.io \"storage-network-for-rwx-volume-enabled\": the object has been modified; please apply your changes to the latest version and try again" node=ip-10-0-1-113
E0711 08:58:31.151056       1 setting_controller.go:217] failed to sync setting for longhorn-system/storage-network-for-rwx-volume-enabled: current state prevents this: failed to apply storage-network setting to Longhorn components when there are attached volumes. It will be eventually applied
10.42.1.1 - - [11/Jul/2024:08:59:52 +0000] "GET /v1/volumes/pvc-28bf84b4-43ac-461d-8b50-30a9b996ab2a HTTP/1.1" 200 12771 "" "Go-http-client/1.1"
10.42.0.1 - - [11/Jul/2024:08:59:58 +0000] "GET /v1/backingimages HTTP/1.1" 200 120 "https://100.26.94.217/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
time="2024-07-11T09:00:27Z" level=warning msg="websocket: close 1000 (normal)" func=api.NewRouter.NewStreamHandlerFunc.func145.1 file="stream.go:55" id=7645663154217872197 type=nodes
10.42.0.1 - - [11/Jul/2024:09:00:01 +0000] "GET /v1/ws/1s/nodes HTTP/1.1" 200 0 "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
10.42.0.1 - - [11/Jul/2024:09:00:01 +0000] "GET /v1/ws/1s/volumes HTTP/1.1" 200 0 "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
time="2024-07-11T09:00:27Z" level=warning msg="websocket: close 1000 (normal)" func=api.NewRouter.NewStreamHandlerFunc.func136.1 file="stream.go:55" id=6065809181947449043 type=volumes
time="2024-07-11T09:00:27Z" level=warning msg="websocket: close 1000 (normal)" func=api.NewRouter.NewStreamHandlerFunc.func139.1 file="stream.go:55" id=4469470021390332315 type=recurringjobs
10.42.0.1 - - [11/Jul/2024:09:00:03 +0000] "GET /v1/ws/1s/recurringjobs HTTP/1.1" 200 0 "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
time="2024-07-11T09:00:34Z" level=warning msg="Failed to update setting: storage-network-for-rwx-volume-enabled" func="controller.(*SettingController).syncSetting.func2" file="setting_controller.go:246" controller=longhorn-setting error="Operation cannot be fulfilled on settings.longhorn.io \"storage-network-for-rwx-volume-enabled\": the object has been modified; please apply your changes to the latest version and try again" node=ip-10-0-1-113
10.42.1.1 - - [11/Jul/2024:09:01:20 +0000] "GET /v1/volumes/pvc-28bf84b4-43ac-461d-8b50-30a9b996ab2a HTTP/1.1" 200 12771 "" "Go-http-client/1.1"
```

But from UI description `Alternatively, you can enable the 'Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly' setting.`, to detach RWX volume seems not mendantory.
![image](https://github.com/longhorn/longhorn/assets/73337386/0d85191f-8950-43a7-ba17-37dafc1c0a15)

## To Reproduce

1. Install v1.7.0-dev, make sure `auto-delete-pod-when-volume-detached-unexpectedly` = `true`
2. Seup storage network ([step](https://longhorn.github.io/longhorn-tests/manual/release-specific/v1.6.0/test-storage-network/))
3. Create and attch RWX volume with workload
4. Change setting `storage-network-for-rwx-volume-enabled` from false to true several times
5. The setting not applied `Operation cannot be fulfilled on settings.longhorn.io "storage-network-for-rwx-volume-enabled": the object has been modified; please apply your changes to the latest version and try again`

## Expected behavior

Setting value should change or we sould update the description in UI

## Support bundle for troubleshooting

[supportbundle_d615568c-bac5-4fa6-b5cf-00a3d72c940b_2024-07-11T09-02-49Z.zip](https://github.com/user-attachments/files/16174109/supportbundle_d615568c-bac5-4fa6-b5cf-00a3d72c940b_2024-07-11T09-02-49Z.zip)

## Environment

 - Longhorn version: longhorn master(longhorn-manager `81d46a`)
 - Impacted volume (PV): pvc-28bf84b4-43ac-461d-8b50-30a9b996ab2a

## Additional context

N/A

**Comment by derekbit** [comment]
cc @c3y1huang

**Comment by c3y1huang** [comment]
The `storage-network-for-rwx-volume-enabled` setting can only be applied when no RWX volumes are attached. This is necessary because Longhorn needs to apply the CNI annotations to the associated components. This is the same as the RWO volumes.

Enabling the `auto-delete-pod-when-volume-detached-unexpectedly` setting is to handle the scenario where an RWX volume associated CSI plugin pod is restarted unexpectedly. More explanation can be found [here](https://github.com/longhorn/longhorn/blob/master/enhancements/20240522-storage-network-for-rwx-volumes.md#share-manager-process-namespaces). Without this setting enabled, Longhorn will not restart the workload pod, and the dangling mount point would likely resulting the data path to become unresponsive. In such cases, users would need to manually restart the workload pods.

**Comment by c3y1huang** [comment]
Let me update the setting descriptions.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `88d414`)

The setting description updated and it is clear to known  that `storage-network-for-rwx-volume-enabled` setting can only be applied when no RWX volumes are attached.
![image](https://github.com/user-attachments/assets/0a612b8c-8092-493b-8fba-090497bc7672)
