### ISSUE TITLE
[TASK] Move longhorn/[samba,nfs-ganesha] to rancher/[samba,nfs-ganesha] before v1.7.0-rc2

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8991]
## What's the task? Please describe

~~To follow the CNCF license policy, we need to move longhorn/spdk to rancher/spdk before v1.7.0-rc2.~~
~~The task is currently blocked by https://github.com/rancherlabs/eio/issues/2460.~~

`longhorn-2024-03-17.zip/spdk/examples/bdev/fio_plugin/README.md` is removed in the default longhorn/spdk branch.

## Additional context

cc @innobead @DamiaSan @shuo-wu

**Comment by innobead** [comment]
SPDK should be fine. Let's move out samba and nfs-ganesha as per CNCf suggested.

**Comment by derekbit** [comment]
Close because the task is finished.
