### ISSUE TITLE
[DOC] Improve the usage and official doc for Longhorn CLI

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8992]
## What's the document you plan to update? Why? Please describe

After discussing with @innobead, we agree with that we can add CLI usages and examples in README.md of https://github.com/longhorn/cli and Longhorn's official document.

**Comment by derekbit** [comment]
@c3y1huang @innobead 
I played around the cobra/doc a bit and came up with the PR https://github.com/longhorn/cli/pull/34.
Can you check if the idea makes sense for you? If not, feel free to close the PR.
Thank you.

**Comment by c3y1huang** [comment]
> @c3y1huang @innobead I played around the cobra/doc a bit and came up with the PR [longhorn/cli#34](https://github.com/longhorn/cli/pull/34). Can you check if the idea makes sense for you? If not, feel free to close the PR. Thank you.

I believe it would make sense for users to be able to check the document without executing the `longhornctl` command, as you mentioned in the PR description.

Would it also make sense to link these documents from the official Longhorn documentation to avoid duplicating context? @derekbit , @innobead , what are your thoughts on this?

**Comment by derekbit** [comment]
> Would it also make sense to link these documents from the official Longhorn documentation to avoid duplicating context? @derekbit , @innobead , what are your thoughts on this?

Sounds good to me.

**Comment by c3y1huang** [comment]
All PRs are merged. This issue is related to the document change and does not require effort from @longhorn/qa . Closing.

**Comment by innobead** [comment]
Discussed with @derekbit . Suggest adding the command examples and output in each command.

**Comment by c3y1huang** [comment]
Reopen to add example to doc.

**Comment by c3y1huang** [comment]
All PRs are merged. Closing.
