### ISSUE TITLE
[BUG] allow-collecting-longhorn-usage-metrics: false not respected

### ISSUE THREAD

**Issue by elaurensx** [longhorn/longhorn#8993]
## Describe the bug

Hubble shows that the longhorn-manager pods are trying to connect to longhorn-upgrade-responder.rancher.io:443 while the parameter allow-collecting-longhorn-usage-metrics has been set to false.

**ConfigMap**
`kubectl describe cm longhorn-default-setting | egrep collecting`
`allow-collecting-longhorn-usage-metrics: false`

**Hubble logs**
`hubble observe -f -l app=longhorn-manager`
`Jul 14: longhorn-manager-h29jf:48414 <> longhorn-upgrade-responder.rancher.io:443 (world) policy-verdict:none EGRESS DENIED (TCP Flags: SYN)`

**UPDATE:** longhorn-ui/Settings/Allow Collecting Longhorn Usage Metrics is checked.

## To Reproduce

`helm install longhorn . --set allowCollectingLonghornUsageMetrics=false`

## Expected behavior

longhorn-ui/Settings/Allow Collecting Longhorn Usage Metrics is unchecked and no egress attempts to rancher.io.

## Environment

 - Longhorn version: v1.6.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.29.6+k3s1
   - Number of control plane nodes in the cluster: 3 
   - Number of worker nodes in the cluster: 2
 - Node config
   - OS type and version: AlmaLinux release 9.4 (Seafoam Ocelot)
   - Kernel version: 5.14.0-427.22.1.el9_4.x86_64
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 0

**Comment by ejweber** [comment]
In case others come across the issue, there are two relevant settings.

- `upgrade-checker` can completely enable or disable Longhorn's ability to reach out to `rancher.io`.
  https://longhorn.io/docs/1.6.2/references/settings/#enable-upgrade-checker
- `allow-collecting-longhorn-usage-metrics` can enable or disable the collection of usage metrics.
  https://longhorn.io/docs/1.6.2/references/settings/#allow-collecting-longhorn-usage-metrics

Setting `allow-collecting-longhorn-usage-metrics = false` prevents all but the most basic of data collection, but you must set `upgrade-checker = false` to prevent all external communication attempts.
