### ISSUE TITLE
[BUG] The check of longhorn-cli for spdk environment is set to 1024 MiB

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8994]
## Describe the bug

The value should be 2048 MiB instead.

## To Reproduce

Run `longhornctl-linux-amd64 --kube-config /root/.kube/config --image derekbit/longhorn-cli:master-head52 install preflight --enable-spdk`

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
@mantissahz Can you help verify this ticket? Thanks.

**Comment by mantissahz** [comment]
Verified **PASSED** by `master-head` [b3dbf2db8ecc](https://hub.docker.com/layers/longhornio/longhorn-cli/master-head/images/sha256-b3dbf2db8ecc9e9b8a0d9d277b34aec1198cec19292004abade7c01ab11feaec?context=explore) and `v1.7.x-head` [ad7f25f56d6d](https://hub.docker.com/layers/longhornio/longhorn-cli/v1.7.x-head/images/sha256-ad7f25f56d6dbfd27be2ec4a3db9a7395793ad5965f83858290cfb97e901f2a4?context=explore)

```shell
master:~# ./longhornctl --kube-config /root/.kube/config --image longhornio/longhorn-cli:v1.7.0-rc1 install preflight --enable-spdk
INFO[2024-07-16T02:43:43Z] Initializing preflight installer
INFO[2024-07-16T02:43:43Z] Cleaning up preflight installer
INFO[2024-07-16T02:43:43Z] Running preflight installer
INFO[2024-07-16T02:43:43Z] Installing dependencies with package manager
INFO[2024-07-16T02:43:43Z] Waiting for DaemonSet container to exit       container=init-longhornctl kind=DaemonSet name=longhorn-preflight-installer namespace=default
INFO[2024-07-16T02:43:49Z] Installed dependencies with package manager
INFO[2024-07-16T02:43:49Z] Cleaning up preflight installer
INFO[2024-07-16T02:43:49Z] Completed preflight installer. Use 'longhornctl check preflight' to check the result.
root@rancher60-master:~# ./longhornctl --kube-config /root/.kube/config --image longhornio/longhorn-cli:v1.7.0-rc1 check preflight --enable-spdk
INFO[2024-07-16T02:43:57Z] Initializing preflight checker
INFO[2024-07-16T02:43:57Z] Cleaning up preflight checker
INFO[2024-07-16T02:43:57Z] Running preflight checker
INFO[2024-07-16T02:43:57Z] Waiting for DaemonSet container to exit       container=init-longhornctl kind=DaemonSet name=longhorn-preflight-checker namespace=default
INFO[2024-07-16T02:43:59Z] Waiting for DaemonSet container to exit       container=output-longhornctl kind=DaemonSet name=longhorn-preflight-checker namespace=default
INFO[2024-07-16T02:44:01Z] Retrieved preflight checker result:
rancher60-worker1:
  info:
  - Service iscsid is running
  - NFS4 is supported
  - Package nfs-common is installed
  - Package open-iscsi is installed
  - CPU instruction set sse4_2 is supported
  - HugePages is enabled
  - Module nvme_tcp is loaded
  - Module uio_pci_generic is loaded
  warn:
  - multipathd.service is running. Please refer to https://longhorn.io/kb/troubleshooting-volume-with-multipath/ for more information.
INFO[2024-07-16T02:44:01Z] Cleaning up preflight checker
INFO[2024-07-16T02:44:01Z] Completed preflight checker
```
