### ISSUE TITLE
Failed to install app longhorn-system. Error: UPGRADE FAILED: kind CustomResourceDefinition

### ISSUE THREAD

**Issue by honzasima** [longhorn/longhorn#900]
Hello,
i upgrdae longhorn from 6.2 to 7.0 and working on Rancher with App catalogs, but stuck in installing and write me:

Failed to install app longhorn-system. Error: UPGRADE FAILED: kind CustomResourceDefinition with the name "settings.longhorn.io" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart

<img width="1438" alt="Snímek obrazovky 2019-11-19 v 12 58 18" src="https://user-images.githubusercontent.com/423929/69144755-568e6480-0acc-11ea-8eb5-611318dd0e2d.png">

Rollback and upgrade again not help me.

Can I ask you how repair it? without lost data please :-D

longhor: 6.2 -> 7.0
Rancher: v2.3.2

Thank you very much

**Comment by shuo-wu** [comment]
Please refer to [this doc](https://github.com/longhorn/longhorn/blob/master/docs/upgrade-from-v0.6.2-to-v0.7.0.md#error-kind-customresourcedefinition-with-the-name-xxx-already-exists-in-the-cluster-and-wasnt-defined-in-the-previous-release)

**Comment by honzasima** [comment]
Oh, sorry for your time. My bad I  did not find it. 

Thank you very much
