### ISSUE TITLE
[BUG][v1.7.0-rc1] Test case `test_csi_encrypted_block_volume` failed even though `cryptsetup` has been installed

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9000]
## Describe the bug

Test case `test_csi_encrypted_block_volume` failed on `v1.7.0-rc1` even though `cryptsetup` has been installed:

```
$ kubectl describe pods csi-block-volume-test
Name:             csi-block-volume-test
Namespace:        default
Priority:         0
Service Account:  default
Node:             ip-10-0-1-105/10.0.1.105
Start Time:       Mon, 15 Jul 2024 12:22:13 +0800
Labels:           <none>
Annotations:      <none>
Status:           Pending
IP:
IPs:              <none>
Containers:
  sleep:
    Container ID:
    Image:         busybox:1.34.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Args:
      /bin/sh
      -c
      while true;do date;sleep 5; done
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-stdqg (ro)
    Devices:
      /dev/longhorn/longhorn-test-blk from longhorn-blk
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  longhorn-blk:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  csi-block-volume-test-pvc
    ReadOnly:   false
  kube-api-access-stdqg:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                 From                     Message
  ----     ------                  ----                ----                     -------
  Normal   Scheduled               11m                 default-scheduler        Successfully assigned default/csi-block-volume-test to ip-10-0-1-105
  Normal   SuccessfulAttachVolume  11m                 attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-a3050465-449f-4814-89aa-407cc33943a8"
  Warning  FailedMapVolume         51s (x13 over 11m)  kubelet                  MapVolume.SetUpDevice failed for volume "pvc-a3050465-449f-4814-89aa-407cc33943a8" : rpc error: code = Internal desc = failed to encrypt device /dev/longhorn/pvc-a3050465-449f-4814-89aa-407cc33943a8 with LUKS: failed to execute: /usr/bin/nsenter [nsenter --mount=/proc/1/ns/mnt --ipc=/proc/1/ns/ipc cryptsetup -q luksFormat --type luks2 --cipher aes-xts-plain64 --hash sha256 --key-size 256 --pbkdf argon2i /dev/longhorn/pvc-a3050465-449f-4814-89aa-407cc33943a8 -d /dev/stdin], output , stderr nsenter: failed to execute cryptsetup: No such file or directory
: exit status 127
```

```
ec2-user@ip-10-0-1-105:~>  zypper search -i cryptsetup
Repository                                    : Time since last refresh
SLE-Module-Basesystem15-SP5-Pool              : 18 min 2 s
SLE-Module-Basesystem15-SP5-Updates           : 17 min 59 s
SLE-Module-Containers15-SP5-Pool              : 17 min 55 s
SLE-Module-Containers15-SP5-Updates           : 17 min 52 s
SLE-Module-Desktop-Applications15-SP5-Pool    : 17 min 49 s
SLE-Module-Desktop-Applications15-SP5-Updates : 17 min 46 s
SLE-Module-DevTools15-SP5-Pool                : 17 min 43 s
SLE-Module-DevTools15-SP5-Updates             : 17 min 41 s
SLE-Module-Public-Cloud15-SP5-Pool            : 17 min 39 s
SLE-Module-Public-Cloud15-SP5-Updates         : 17 min 37 s
SLE-Module-Python3-15-SP5-Pool                : 17 min 34 s
SLE-Module-Python3-15-SP5-Updates             : 17 min 31 s
SLE-Product-SLES15-SP5-Pool                   : 17 min 30 s
SLE-Product-SLES15-SP5-Updates                : 17 min 28 s
SLE-Module-Server-Applications15-SP5-Pool     : 17 min 26 s
SLE-Module-Server-Applications15-SP5-Updates  : 17 min 23 s
SLE-Module-Web-Scripting15-SP5-Pool           : 17 min 21 s
SLE-Module-Web-Scripting15-SP5-Updates        : 17 min 19 s


    Note: Running with user privileges. From time to time run 'zypper refresh' as root to make sure
    the repository metadata are complete and up-to-date.

Loading repository data...
Reading installed packages...

S  | Name            | Summary                                                       | Type
---+-----------------+---------------------------------------------------------------+--------
i+ | cryptsetup      | Setup program for dm-crypt Based Encrypted Block Devices      | package
i  | cryptsetup-lang | Translations for package cryptsetup                           | package
i  | libcryptsetup12 | Library for setting up dm-crypt Based Encrypted Block Devices | package

    Note: For an extended search including not yet activated remote resources please use 'zypper
    search-packages'.
```

## To Reproduce

Run test case `test_csi_encrypted_block_volume`

## Support bundle for troubleshooting

[supportbundle_b92a36b6-1534-4b8a-a458-e7110705d435_2024-07-15T04-39-06Z.zip](https://github.com/user-attachments/files/16230080/supportbundle_b92a36b6-1534-4b8a-a458-e7110705d435_2024-07-15T04-39-06Z.zip)

## Environment

 - Longhorn version: v1.7.0-rc1
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.28.4+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: sles 15-sp6
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
The bug can be easily reproduced by https://github.com/longhorn/longhorn/tree/master/examples/block/crypto, and it is not observed in v1.6.x.

**Comment by derekbit** [comment]
After a quick investigation, the regression is introduced by [the removal of HostPID in RWX storage network feature ](https://github.com/longhorn/longhorn-manager/pull/2815/files#diff-d4f309d528674353f3e6e803a8b0653e5e8c19913fa5de4af1414795bb3a53d4). @c3y1huang Can you help check it?

**Comment by derekbit** [comment]
After a quick investigation, the regression is introduced by [the removal of HostPID in RWX storage network feature ](https://github.com/longhorn/longhorn-manager/pull/2815/files#diff-d4f309d528674353f3e6e803a8b0653e5e8c19913fa5de4af1414795bb3a53d4). @ejweber  Can you help check it? Thank you.

**Comment by ejweber** [comment]
### Probable root cause

When the CSI plugin sets up the `NamespaceExecutor` to execute `cryptsetup` commands, it uses process ID 1 from `/proc`. When we ran it with `hostPID = true`, this executed `cryptsetup` in the appropriate host namespaces.

https://github.com/longhorn/longhorn-manager/blob/06abbf365711197302e724da484e00c08a7518da/csi/crypto/crypto.go#L79

With `hostPID = false`, using process ID 1 from `/proc` causes the command to run in the container's own namespaces (which is pointless).

Other callers of `NamespaceExecutor` use `/host/proc` instead.

https://github.com/longhorn/longhorn-manager/blob/55edd76ed2b604912c93a61bb08b8b803cdfceba/app/daemon.go#L259

We can't do this directly, since https://github.com/longhorn/longhorn-manager/pull/2815 removed the `/:/host` bind mount. However, I think it can be added back in without breaking the RWX changes.

### Plan of action

1. Add a limited `/proc:/host/proc` bind mount back to the CSI plugin.
2. Use `/host/proc` with `NamespaceExecutor`.
3. Run crypto integration tests.
4. Run RWX storage network tests.

**Comment by roger-ryao** [comment]
**Verified on master-head/v1.7.x 20230723**
- longhorn master-head https://github.com/longhorn/longhorn/commit/905339c1de4eb54ab24c0d641c8392b7aa367db7
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/6fc75afd54aa532f34b8322e268afc91cc1ee952

- longhorn v1.7.x-head https://github.com/longhorn/longhorn/commit/7d91157e86fdfe20db34af3001991f00e7b64def
- longhorn-manager v1.7.x-head https://github.com/longhorn/longhorn-manager/commit/99de802dbfa18664a7d967ae963b428d67d5245d

**The test steps**
https://github.com/longhorn/longhorn/issues/9000#issuecomment-2228852364

1. Deploy /examples/block/crypto without issue.
```
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/block/crypto/secret-crypto-global.yaml
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/block/crypto/storageclass-crypto-global.yaml
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/block/crypto/deployment_with_pvc.yaml
```
2. Ensure integration end-to-end tests pass, especially `test_csi_encrypted_block_volume`, `test_csi_encrypted_migratable_block_volume`, and `test_encrypted_rwx_volume`.
master-head https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/980/ 
3. Retest [FEATURE] Support storage network for RWX volumes #8184.

**Result passed**


- [x] 1. Deploy /examples/block/crypto without issue.
- [x] 2. The `test_csi_encrypted_block_volume`, `test_csi_encrypted_migratable_block_volume`, and `test_encrypted_rwx_volume` test passed in regression.

    - master-head : 
        - https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/980/
        - https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/911/

    - v1.7.x-head : 
        - https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-tests-sles-amd64/7/
        - https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-tests-sles-arm64/7/

- [x] 3. Retest [FEATURE] Support storage network for RWX volumes #8184.
