### ISSUE TITLE
[TEST] Sle-micro pipeline not work on v1.7.x

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#9001]
## What's the test to develop? Please describe

Longhorn v1.7.0-rc1 install timeout on sle-micro pipeline(public build [#145](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/amd64/job/longhorn-tests-sle-micro-amd64/145/consoleFull), private build [#7219](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7219/))

SSH into control plane node on the private pipeline, find that `longhorn-driver-deployer` not running then other compoments not started.
```
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    4m29s                 default-scheduler  Successfully assigned longhorn-system/longhorn-driver-deployer-5bbd6f9c8-z25qk to ip-10-0-1-188
  Warning  FailedMount  4m29s                 kubelet            MountVolume.SetUp failed for volume "kube-api-access-hqvqm" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedMount  20s (x10 over 4m30s)  kubelet            MountVolume.SetUp failed for volume "go-cover-dir" : mkdir /go-cover-dir/: read-only file system
```

Manually create cluster using the same ami (`ami-06f4274886145d73f)` to install Longhorn, the installation completed without any problems.

## Describe the tasks for the test

N/A

## Additional context

Upgrade v1.6.2 to v1.7.0-rc1 sle-micro worked well [amd64](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/amd64/job/longhorn-upgrade-tests-sle-micro-amd64/6/) [arm64](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/arm64/job/longhorn-upgrade-tests-sle-micro-arm64/8/)

**Comment by chriscchien** [comment]
v1.7.0-rc2 can not ready on below sle-micro pipeline (master [AMD](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/amd64/job/longhorn-tests-sle-micro-amd64/153/) encounter the same issue as well)

- [AMD](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/amd64/job/longhorn-tests-sle-micro-amd64/152/)
- [AMD upgrade](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/amd64/job/longhorn-upgrade-tests-sle-micro-amd64/8/)
- [ARM](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/arm64/job/longhorn-tests-sle-micro-arm64/44/)
- [ARM upgrade](https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/arm64/job/longhorn-upgrade-tests-sle-micro-arm64/10/)

```
null_resource.cluster_setup_controlplane_k3s[0]: Still creating... [4m50s elapsed]

Error: remote-exec provisioner error

  with null_resource.cluster_setup_controlplane_k3s[0],
  on k3s_instaces.tf line 222, in resource "null_resource" "cluster_setup_controlplane_k3s":
 222:   provisioner "remote-exec" {

timeout - last error: dial tcp 34.206.243.124:22: i/o timeout
+ [[ k3s == \r\k\e ]]
+ [[ k3s == \a\k\s ]]
+ [[ k3s == \e\k\s ]]
+ [[ false == true ]]
+ set_kubeconfig
+ [[ k3s == \r\k\e ]]
+ [[ k3s == \r\k\e\2 ]]
+ [[ k3s == \k\3\s ]]
+ export KUBECONFIG=test_framework/terraform/aws/sle-micro/k3s.yaml
+ KUBECONFIG=test_framework/terraform/aws/sle-micro/k3s.yaml
+ kubectl get pods -A
+ grep -q Running
E0726 03:37:26.048999    3047 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0726 03:37:26.049313    3047 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0726 03:37:26.050731    3047 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0726 03:37:26.051091    3047 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0726 03:37:26.052388    3047 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
+ cleanup
```

**Comment by yangchiu** [comment]
@chriscchien Could you do some more analysis on this? Is it the same issue described in the ticket? Can it be reproduced locally?

**Comment by chriscchien** [comment]
@yangchiu , the ami `ami-08dfe1f7e893ae0e1`(previous we r using `ami-06f4274886145d73f`) have issue when reboot 

- `sudo shutdown -r now`, the instance stopped, manually start the instance, the instance will change to pending -> stopping -> stopped
- `sudo reboot`, the instance stopped, manuallt start the instance, the instance stuck at `Running` wtih status check`Initializing` , ssh will timeout

![Screenshot from 2024-07-26 15-08-17](https://github.com/user-attachments/assets/db4bdb25-4a2c-4463-987d-ce3c46db935b)
![image](https://github.com/user-attachments/assets/c8a07422-0fd2-44eb-b708-b7c51f8ef622)
