### ISSUE TITLE
[BUG] Longhorn v.1.7.0-rc1 on ARM, the v2-data-engine failed to enable the instance-manager pod 

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#9004]
## Describe the bug

Longhorn v.1.7.0-rc1 on ARM, the v2-data-engine failed to enables the instance-manager pod

```
instance-manager-8306dc3c074955035261ab2b042af6f6                 0/1     Terminating         0          17s   <none>         ryao-arm64-w3-56e0d12e-g8rvs   <none>           <none>
instance-manager-8306dc3c074955035261ab2b042af6f6                 0/1     Terminating         0          17s   <none>         ryao-arm64-w3-56e0d12e-g8rvs   <none>           <none>
instance-manager-8306dc3c074955035261ab2b042af6f6                 0/1     Pending             0          0s    <none>         ryao-arm64-w3-56e0d12e-g8rvs   <none>           <none>
instance-manager-8306dc3c074955035261ab2b042af6f6                 0/1     ContainerCreating   0          0s    <none>         ryao-arm64-w3-56e0d12e-g8rvs   <none>           <none>
instance-manager-3221697e54c160c846ffd80e1bd1c933                 0/1     Error               0          17s   <none>         ryao-arm64-w2-1f3f32e8-27ktm   <none>           <none>
instance-manager-3221697e54c160c846ffd80e1bd1c933                 0/1     Terminating         0          17s   <none>         ryao-arm64-w2-1f3f32e8-27ktm   <none>           <none>
instance-manager-3221697e54c160c846ffd80e1bd1c933                 0/1     Terminating         0          17s   <none>         ryao-arm64-w2-1f3f32e8-27ktm   <none>           <none>
instance-manager-3221697e54c160c846ffd80e1bd1c933                 0/1     Pending             0          0s    <none>         ryao-arm64-w2-1f3f32e8-27ktm   <none>           <none>
instance-manager-3221697e54c160c846ffd80e1bd1c933                 0/1     ContainerCreating   0          0s    <none>         ryao-arm64-w2-1f3f32e8-27ktm   <none>           <none>
instance-manager-8306dc3c074955035261ab2b042af6f6                 1/1     Running             0          1s    10.42.1.156    ryao-arm64-w3-56e0d12e-g8rvs   <none>           <none>
instance-manager-3221697e54c160c846ffd80e1bd1c933                 1/1     Running             0          1s    10.42.3.157    ryao-arm64-w2-1f3f32e8-27ktm   <none>           <none>

```

## To Reproduce

1. Prepare ARM64 cluster
2. Enable v2 data engine
3. Check the V2 instance-manager pod

## Expected behavior

the v2-data-engine enables the instance-manager pod without error on ARM cluster.

## Support bundle for troubleshooting

[supportbundle_d6fad975-6c73-4ca0-9ce8-1c42e1704adf_2024-07-15T11-36-44Z.zip](https://github.com/user-attachments/files/16233835/supportbundle_d6fad975-6c73-4ca0-9ce8-1c42e1704adf_2024-07-15T11-36-44Z.zip)
[armsupportbundle_6e0e928a-28a9-4300-87fe-446e4e2f2cf5_2024-07-15T10-54-47Z.zip](https://github.com/user-attachments/files/16233845/armsupportbundle_6e0e928a-28a9-4300-87fe-446e4e2f2cf5_2024-07-15T10-54-47Z.zip)

## Environment

 - Longhorn version: `v1.7.0-rc1`
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):Kubectl 
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:k3s
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: ubuntu 24.04
   - Kernel version: 
   - CPU per node: 4
   - Memory per node: 16
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 

## Additional context
https://longhorn.github.io/longhorn-tests/manual/pre-release/v2-volume/sanity-check/

**Comment by derekbit** [comment]
@roger-ryao 
The instance-manager pods are still starting. Can you check it again?
I also tried to deploy v2 data engine in my arm64 env, and no issue is found.

**Comment by roger-ryao** [comment]
**Verified on master-head/v1.7.x 20230722**

- longhorn-instance-manager master-head https://github.com/longhorn/longhorn-instance-manager/commit/49de3ef60d4b946337ae220d9a9c07688356b752
- longhorn-instance-manager v1.7.x https://github.com/longhorn/longhorn-instance-manager/commit/c62fa08c11fc96f5cd3bcff8bf31ac0dccf67f73

**The test steps**
https://github.com/longhorn/longhorn/issues/9004#issue-2408523042

**Result passed**
