### ISSUE TITLE
[IMPROVEMENT] Update nfs-ganesha to v5.9

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9008]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

According to the [dependency update policy](https://github.com/longhorn/longhorn/wiki/Dependency-Update-Policy), nfs-ganesha can be updated to v5.9 in v1.7.0 feature release.

**Comment by derekbit** [comment]
Longhorn is using nfs-ganesha v5.7.
Many fixes are introduced into v5.8 and v5.9, so I plan to update it for Longhorn v1.7.0.
WDYT @james-munson  @innobead

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-share-manager `9555b7`)

rwx cases all passed on master pipeline [amd64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7245/testReport/tests/), [arm64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7246/testReport/tests/test_rwx/)


Hi @derekbit , does this [PR](https://github.com/longhorn/longhorn-share-manager/pull/257) need to backport to v1.7.x? thank you.

**Comment by derekbit** [comment]
> Verified **pass** on longhorn master(longhorn-share-manager `9555b7`)
> 
> rwx cases all passed on master pipeline [amd64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7245/testReport/tests/), [arm64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7246/testReport/tests/test_rwx/)
> 
> Hi @derekbit , does this [PR](https://github.com/longhorn/longhorn-share-manager/pull/257) need to backport to v1.7.x? thank you.

@chriscchien merged. you can verify v1.7.x-head. Thank you.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-share-manager `9555b7`) longhorn v1,7.x(longhorn-share-manager `787f6d`)

rwx cases all passed with master images [amd64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7245/testReport/tests/), [arm64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7246/testReport/tests/test_rwx/) and v17x images([amd64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7309/), [arm64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7310/))
