### ISSUE TITLE
[BUG][UI][v1.7.0-rc1] Instance manager image search by state not work properly

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#9010]
## Describe the bug

In instance manager page, search state `Running` will get empty result, the behavior is not consistent with other pages
![image](https://github.com/user-attachments/assets/da89a126-2d93-42e0-8ff6-b7ee6c713340)
Instead, search state `running` will get result
![image](https://github.com/user-attachments/assets/63294be3-fe2d-421e-a791-985d72aace13)

## To Reproduce

In instance manager page, search state `Running` will get empty result, the behavior is not consistent with other pages

## Expected behavior

Use the state displayed on UI to search; should get the corresponding results like other pages.

## Support bundle for troubleshooting

N/A

## Environment

 - Longhorn version:  v1.7.0-rc1

## Additional context

N/A

**Comment by derekbit** [comment]
@a110605 Please fill in the check list and update the status. Thank you.

**Comment by a110605** [comment]
Fixed push to [master-head](https://hub.docker.com/layers/longhornio/longhorn-ui/master-head/images/sha256-1f720277417b828121710b2e361dfc98c1cd4dca514e80bcb78da1b45f8bba68?context=explore), [v1.7.x-head](https://hub.docker.com/layers/longhornio/longhorn-ui/v1.7.x-head/images/sha256-012cb8101ca8edd5e041419212bd2bfda58b6a2134d29804459ad173a31bbe5f?context=explore)

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-ui `1a660b`), longhorn v1.7.x(longhorn-ui `1408d8`) with test [steps](https://github.com/longhorn/longhorn/issues/9010#issuecomment-2232212961)
