### ISSUE TITLE
[BUG][v1.7.0-rc1] Clone DR volume result in fail

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#9016]
## Describe the bug

Clone DR volume result in fail : the DR volume will loop from Restoring -> Attached -> Healthy -> Detached , the clone volume will created with no state and no events.

In above state, activate the DR volume, the volume clone succeed without problem.

## To Reproduce

1. Create a DR volume, do not activate this volume
2. Clone DR volume through UI
3. The Cloned volume will created with no state and no events. The DR volume will loop from Restoring -> Attached -> Healthy -> Detached 

## Expected behavior

Have doc or block the atcion to clone non activate DR volume from UI if it's not supported.

## Support bundle for troubleshooting

[supportbundle_ba0d10fb-11d4-4529-926a-2d8ee1dbb99b_2024-07-17T04-00-39Z.zip](https://github.com/user-attachments/files/16259097/supportbundle_ba0d10fb-11d4-4529-926a-2d8ee1dbb99b_2024-07-17T04-00-39Z.zip)

## Environment

 - Longhorn version: v1.7.0-rc1

## Additional context

N/A

**Comment by derekbit** [comment]
cc @PhanLe1010

**Comment by derekbit** [comment]
Hello @PhanLe1010 Can you help check the issue? Thank you.

**Comment by chriscchien** [comment]
The UI options did not consistnet, maybe need to clarify first

From v1.7.x-head UI, I can clone DR volume from the global `Clone Volume` button on the left up side of UI, but in 3 dots menu form DR volume right side, the `Clone Volume` option is gray out.

![Screenshot from 2024-07-22 11-01-59](https://github.com/user-attachments/assets/84971936-578b-46e9-8412-76ccd66af9a9)

**Comment by a110605** [comment]
> The UI options did not consistnet, maybe need to clarify first
> 
> From v1.7.x-head UI, I can clone DR volume from the global `Clone Volume` button on the left up side of UI, but in 3 dots menu form DR volume right side, the `Clone Volume` option is gray out.
> 
> ![Screenshot from 2024-07-22 11-01-59](https://private-user-images.githubusercontent.com/73337386/350825419-84971936-578b-46e9-8412-76ccd66af9a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MTgyMDIsIm5iZiI6MTcyMTYxNzkwMiwicGF0aCI6Ii83MzMzNzM4Ni8zNTA4MjU0MTktODQ5NzE5MzYtNTc4Yi00NmU5LTg0MTItNzZjY2Q2NmFmOWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDAzMTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNTkzNTRkMTdkNTUxODg2ZjQ4ZmYxMTlhNDhiMGEyNTY1ZjAwZGZlMDYyNGE5MmZjZmFmMWNiYWViMWNkYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KZMf8WhuRTMQ0l8cm5HZJ6A97y24wm1AEFkznx0ebI8)

Hi @derekbit , @PhanLe1010 , 
For the disabled clone volume in three dot menu, it's due to dr-volume is still in`standy` status. And I didn't add that [logic](https://github.com/a110605/longhorn-ui/blob/1a660bed0ecaab6e643134d1c6c8801f43cd1083/src/routes/volume/VolumeActions.js#L250) for bulk clone volume. 

Should we allow user to clone volume in standy or in restoring status ? 

<img width="1491" alt="Screenshot 2024-07-22 at 11 46 00 AM" src="https://github.com/user-attachments/assets/4e636fd0-896f-4f7f-8efd-d7b95ad801ac">

**Comment by derekbit** [comment]
> Should we allow user to clone volume in standy or in restoring status ?

IMO, no. WDYT? @PhanLe1010 @innobead

**Comment by PhanLe1010** [comment]
> > Should we allow user to clone volume in standy or in restoring status ?
> 
> IMO, no. WDYT? @PhanLe1010 @innobead

Agree with @derekbit that we don't need to allow the user to clone standby or restoring volume. This usecase is a bit weird. User can just restore a new volume from backup instead of they want to have volume with identical data as the standby/restoring volume

**Comment by PhanLe1010** [comment]
Btw, is it correct that this is not a regression @chriscchien ?

**Comment by chriscchien** [comment]
> Btw, is it correct that this is not a regression @chriscchien ?

Because colne DR volume is not work in previous version, I think this issue is not a regression.

**Comment by a110605** [comment]
> The UI options did not consistnet, maybe need to clarify first
> 
> From v1.7.x-head UI, I can clone DR volume from the global `Clone Volume` button on the left up side of UI, but in 3 dots menu form DR volume right side, the `Clone Volume` option is gray out.
> 
> ![Screenshot from 2024-07-22 11-01-59](https://private-user-images.githubusercontent.com/73337386/350825419-84971936-578b-46e9-8412-76ccd66af9a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MDY2NzcsIm5iZiI6MTcyMTcwNjM3NywicGF0aCI6Ii83MzMzNzM4Ni8zNTA4MjU0MTktODQ5NzE5MzYtNTc4Yi00NmU5LTg0MTItNzZjY2Q2NmFmOWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDAzNDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNTUwOWUxNjQ0Y2YxZjA5MDg3ODBiZGVhZWVkZmFjNmQxMDU5YmI5MWZlNzhhMTllZDk1MzIzZTEzMGNiMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YE8vjlL_zyFv005HyMkLPjHAJihHyGHscMNXpIK58pg)

I've disabled the `bulk clone volume` button if DR volume is not ready or under restoring. So DR volume won't have loop status.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn v1.7.x(longhorn-ui `47bbcd`), longhorn master(longhorn-ui `a2b2b3`) with test [steps](https://github.com/longhorn/longhorn/issues/9016#issuecomment-2244195416)

The UI bulk clone action cannot clone a non-activated DR volume now. After the DR volume is activated, the data on the DR volume is up-to-date, and cloning the activated DR volume works well.
