### ISSUE TITLE
[FEATURE] Support backup encryption

### ISSUE THREAD

**Issue by milkowski** [longhorn/longhorn#902]
It would be desirable to have possibility to encrypt replica files before sending them to backup target. It may be done on the VFS level also but it adds overhead to priceless I/O performance.

**Comment by carpenike** [comment]
Checking in to see if this is being prioritized at all? Looking to move from Ceph + Stash/Restic which has encrypted backups in box.

**Comment by yasker** [comment]
If we implement `dm-crypt` on volume level, backup encryption will also be done automatically. #1859

**Comment by yasker** [comment]
This should be included in #1859.

**Comment by innobead** [comment]
Leave this open for obvious feature view but actually, this should naturally happen when enabling volume encryption and we need to verify this together w/ #1859 .

cc @longhorn/qa

**Comment by meldafrawi** [comment]
Validation effort will be tracked as part of #1859 validation.
