### ISSUE TITLE
[BUG] RWX pod stuck in hanging forever after a node shutdown/reboot

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#9022]
## Describe the bug

This ticket is related to https://github.com/longhorn/longhorn/issues/8999 . In that ticket, @c3y1huang attempted to fix the RWX service cleanup logic. 

However, looks like the latest master-head still delete the rwx service. It will do it whenever there is no share-manager pod https://github.com/longhorn/longhorn-manager/blob/b615732bc75d5513a7f3289a667af1f06a55af1d/controller/setting_controller.go#L342-L355

This is problematic because during node reboot there is a moment there is no share-manager pod -> Longhorn manager delete the service -> Then it create a new service one -> share-manager pod is recreated -> existing clients still use old service ip -> client is hang forever -> kubelet might also hang and no new RWX pod can be created on the same node

@ejweber @james-munson and I discussed and have some ideas on top of our heads:
1. Don't cleanup RWX service if the setting `SettingNameStorageNetworkForRWXVolumeEnabled` has not changed 
1. The cleanup logic here
    ```
			    // Perform cleanup of the share manager Service
			    // This is to allow the creation of the correct Service
			    // and Endpoint when switching between cluster network
			    // and storage network.
			    if err := sc.cleanupShareManagerServiceAndEndpoints(); err != nil {
				    return err
			    }
    ```
    should only be executed conditionally if
    ```
			    if err := sc.updateCNI(sc.ds.AreAllRWXVolumesDetached); err != nil {
				    return err
			    }
    ```
    actually did anything.
1. Or it may be better to change the RWX detachment check? We want to verify that there are no remaining NFS clients. If there are no more Kubernetes VolumeAttachments, then this is the case. Simply checking if the underlying Longhorn volume is detached doesn't necessarily help.

## Environment

 - Longhorn version: master-head

**Comment by ejweber** [comment]
To further clarify, the issue affects RWX volumes that DON'T use a storage network. Clients for these volumes still reference the ClusterIP of the service, which changes when the service is deleted.

The fix to https://github.com/longhorn/longhorn/issues/8999 assumes it is safe to delete the service when there are no more share manager pods, but this is not a good indicator that there are no NFS clients. In @PhanLe1010's example, killing a node leads Longhorn to delete a share manager pod and detach its underlying volume. However, from a Kubernetes perspective, the RWX volumes is still attached to many nodes/workloads and NFS clients are still running. As a result, this is NOT a safe time to delete the service.

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-manager 2697ea5) and v1.7.x-head (longhorn-manager 3bc35a5). RWX workload pods can recover after a node reboot.
