### ISSUE TITLE
Update from 0.6.4 -> 0.7.0 completed with error message

### ISSUE THREAD

**Issue by zeppelinux** [longhorn/longhorn#903]
Update was triggered from the Apps page and seems to be completed successfully - everything is working and all the pods are green, but the App is still in 'Installing' state and App: longhorn-system page has following message on top in red:
 
'Failed to install app longhorn-system. Error: UPGRADE FAILED: StorageClass.storage.k8s.io "longhorn" is invalid: provisioner: Forbidden: updates to provisioner are forbidden.'

Kubernetes Version: v1.16.3
Rancher Version: 2.3.2

**Comment by shuo-wu** [comment]
This error is caused by the Longhorn StorageClass upgrade failure, see [here](https://github.com/longhorn/longhorn/blob/v0.7.0/docs/upgrade-from-v0.6.2-to-v0.7.0.md#error-longhorn-is-invalid-provisioner-forbidden-updates-to-provisioner-are-forbidden) for details.

**Comment by zeppelinux** [comment]
It helped, all is good now!
