### ISSUE TITLE
[BUG] After experiencing high processing, replicas get corrupted

### ISSUE THREAD

**Issue by jonasmuller98** [longhorn/longhorn#9036]
## Describe the bug

I am running a cluster with Kafka, MinIO and Spark. 

When running Spark jobs, processing go high and has prety intense I/O, and my pvc got corrupt. This should not be a problem by itself as I have 3 replicas of each, but instead of discarding the bad ones and rebuilding with the good one, it got stuck and must run fsck manually. After running fsck manually (and solving the underlying problems) it works good again.

## To Reproduce

Not sure if it is reproducible everywhere.

When having Spark Cluster reading from MinIO in the same cluster, create 3 spark jobs and trying to read a big amount of data on each job, it starts breaking.

## Expected behavior

Expected Longhorn to discard corrupted replicas and a good one takeover.

## Support bundle for troubleshooting
Sent to email

## Environment

 - Longhorn version: 1.6.2
 - Impacted volume (PV): pvc-d06857d4-21bc-4177-bec1-26327145dd52 (and others)
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2 and 1.28.8+rke2r1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 2
 - Node config
   - OS type and version: Oracle Linux 9.3
   - Kernel version: 5.15.0-205.149.5.1.el9uek.x86_64
   - CPU per node: 12 vCPU
   - Memory per node: 48GB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 1Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare virtual machines
 - Number of Longhorn volumes in the cluster: 25

## Additional context

This is going to be a production environment eventually with more resources available, but, still, cant afford to go down by one replica going corrupt.

**Comment by derekbit** [comment]
@jonasmuller98 Can you provide a support bundle with the issue for investigation?

**Comment by jonasmuller98** [comment]
Hi @derekbit thanks for the reply. I've sent it to the email. Should i send it again?

**Comment by derekbit** [comment]
> Hi @derekbit thanks for the reply. I've sent it to the email. Should i send it again?

Sorry, I missed it earlier. I've found it in my mailbox now, and I will check it. Thank you.

**Comment by derekbit** [comment]
Filesystem corruption is expected under these circumstances. If a Longhorn volume consists of one engine and two replicas, IO requests from applications are sent to the engine and then issued to the two downstream replicas. If the engine times out while communicating with each replica (the default timeout is 8 seconds), the replicas are marked as failed. In your case, both replicas were marked as failed, which likely led to the filesystem falling into an inconsistent state, resulting in filesystem corruption.

**Comment by jonasmuller98** [comment]
I changed the setting you've mentioned and we'll see if it helps, thanks for now!

**Comment by hitsub2** [comment]
@jonasmuller98 May I know your scenario with running Spark on top of longhorn? Why do you use longhorn for shuffling?
