### ISSUE TITLE
[BUG] HA Volume Migration: Volume does not auto-attach to another node after turning off the original node

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#9039]
## Describe the bug

HA Volume Migration: Volume does not auto-attach to another node after turning off the original node

## To Reproduce

1. Follow up [Basic instructions step 1-5](https://longhorn.github.io/longhorn-tests/manual/pre-release/ha/ha-volume-migration/)
2. Check the migration status of the volume.
```bash
> kubectl -n longhorn-system get volume -oyaml -w | grep -i nodeid
  migrationNodeID: ryao-test-w2-f9382298-rcjsm
  nodeID: ryao-test-w1-81bb3f48-xp76n
  currentMigrationNodeID: ryao-test-w2-f9382298-rcjsm
  currentNodeID: ryao-test-w1-81bb3f48-xp76n
  pendingNodeID: ""
```
3. Shutdown the Node 1 `ryao-test-w1-81bb3f48-xp76n`
4. Wait until Kubernetes recognizes the node is down and the `instance-manager` pod on the `ryao-test-w1-81bb3f48-xp76n` is terminated.
5. Check the migration status of the volume again. The related values were empty. 
```
  currentNodeID: ""
  pendingNodeID: ""
  migrationNodeID: ""
  nodeID: ""
  currentMigrationNodeID: ""
```
6. I expected volumn attach to `ryao-test-w2-f9382298-rcjsm`. but it didn't.
7. Even after turning on the Node 1 `ryao-test-w1-81bb3f48-xp76n` ,the volume does not auto-attach to any node, we must execute one of following commands make volume attach.

```bash
# Attempt to confirm the migration by detaching from <old_node>.
kubectl -n longhorn-system delete -f va-1.yaml

# Attempt to roll back the migration by detaching from <new_node>.
kubectl -n longhorn-system delete -f va-2.yaml
```

## Expected behavior

Hi @ejweber 
      I am unsure if this is the expected behavior or a real issue, or if there might be a problem with the testing method. 
      Could you please provide some clarification or guidance?

## Support bundle for troubleshooting

[supportbundle_366c0e8c-1495-4e38-bf15-4bc26039fd51_2024-07-18T12-48-22Z.zip](https://github.com/user-attachments/files/16283429/supportbundle_366c0e8c-1495-4e38-bf15-4bc26039fd51_2024-07-18T12-48-22Z.zip)

## Environment

 - Longhorn version: 
 - Impacted volume (PV): `pvc-79a3d75a-14ca-4057-a85f-e4fdbc13381a`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):  `Kubectl`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: `v1.27.14+k3s1`
   - Number of control plane nodes in the cluster: 1 
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 24.04
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD): 
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): `Harvester Access Lab`
 - Number of Longhorn volumes in the cluster: 1 

## Additional context

https://longhorn.github.io/longhorn-tests/manual/pre-release/ha/ha-volume-migration/

**Comment by ejweber** [comment]
Thanks for the report @roger-ryao. It is expected. 

> 6\. I expected volumn attach to `ryao-test-w2-f9382298-rcjsm`. but it didn't.

In this state, the volume is faulted and two VolumeAttachments still exist for it. We have an intuitive idea that it would be best for the volume to attach to the new node and start running on it, but we do not allow Longhorn to decide to do that with the information it has. If we did, it would attach to the new node, then later start migrating to the old node when it came back online. This would put the cluster in a confusing state.

The new behavior requires Longhorn do nothing until the faulted volume is explicitly detached from one of the two nodes (via a confirmation or rollback).

I was attempting to imply that with the instructions for the case you are describing.

```
6. Old engine node down
   1. Hard shut down the node running the old engine.
   2. Wait until Kubernetes recognizes the node is down. (This is IMPORTANT! Otherwise, it is a different test case.)
   3. Attempt a confirmation or rollback.
```

However, I'm definitely open to an explicit mention like the following if you think it is helpful:

```
Attempt a confirmation or rollback. NOTE: The volume will remain detached until one of these two actions is performed.
```

**Comment by ejweber** [comment]
Opened https://github.com/longhorn/longhorn-tests/pull/1986 to help clarify. If the explanation makes sense, I think we can close this one. Let me know what you think!
