### ISSUE TITLE
Longhorn UI doesn't show the number 9

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#904]
`pvc-49ed245d-f56d-4f5d-92aa-242f6fc7a649` is shown as 

`pvc-4-ed245d-f56d-4f5d--2aa-242f6fc7a64-`

![image](https://user-images.githubusercontent.com/28725423/69318687-b63f5980-0c0b-11ea-93a9-1b2e26b51a56.png)

**Comment by yasker** [comment]
@ainiml this is interesting. I haven't seen an issue like this, and we cannot reproduce it. It seems have something to do with your browser encoding? I saw search works with `9`, but it just doesn't show up in the UI. 

@smallteeths Any ideas?

**Comment by ainiml** [comment]
> @ainiml this is interesting. I haven't seen an issue like this, and we cannot reproduce it. It seems have something to do with your browser encoding? I saw search works with `9`, but it just doesn't show up in the UI.
> 
> @smallteeths Any ideas?

Just straight up Linux Chrome
