### ISSUE TITLE
[BUG] V2 volume snapshot creation time disappear after upgrade from v1.6.2 to v1.7.0-dev

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#9045]
## Describe the bug

V2 volume snapshot creation time disappear after upgrade from v1.6.2 to v1.7.0-dev.

The v2 volume pvc is `pvc-01dc0f12-8740-4b52-b1bf-6b565d53c514`
```bash
> k get  pvc
NAME   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS              VOLUMEATTRIBUTESCLASS   AGE
vol1   Bound    pvc-de21bfb9-3f0d-4915-a151-a115e2753cc6   1Gi        RWO            longhorn                  <unset>                 13m
vol2   Bound    pvc-01dc0f12-8740-4b52-b1bf-6b565d53c514   1Gi        RWO            longhorn-v2-data-engine   <unset>                 12m
```

before upgrade
```bash
> kl get snapshot
NAME                                   VOLUME                                     CREATIONTIME           READYTOUSE   RESTORESIZE   SIZE       AGE
be094221-d3e5-4f8e-9000-3cd62fceab52   pvc-de21bfb9-3f0d-4915-a151-a115e2753cc6   2024-07-19T07:55:32Z   true         1073741824    51015680   4m12s
cdd418e5-c1eb-4ec0-a9c7-9746e3dbfc81   pvc-de21bfb9-3f0d-4915-a151-a115e2753cc6   2024-07-19T07:55:43Z   true         1073741824    20480      3m57s
ffd70875-dafb-4223-ace1-3cb1dd1f38c0   pvc-01dc0f12-8740-4b52-b1bf-6b565d53c514   2024-07-19T07:56:08Z   true         1073741824    57671680   3m34s
b012037f-5300-441d-80cd-44a80ac33c09   pvc-01dc0f12-8740-4b52-b1bf-6b565d53c514   2024-07-19T07:56:23Z   true         1073741824    3145728    3m19s
```

after upgrade complete, reattach the v2 volume, can see snapshto of pvc-01dc0f12-8740-4b52-b1bf-6b565d53c514 CREATIONTIME disappeared
```bash
> kl get snapshot
NAME                                   VOLUME                                     CREATIONTIME           READYTOUSE   RESTORESIZE   SIZE       AGE
be094221-d3e5-4f8e-9000-3cd62fceab52   pvc-de21bfb9-3f0d-4915-a151-a115e2753cc6   2024-07-19T07:55:32Z   true         1073741824    51015680   6m55s
cdd418e5-c1eb-4ec0-a9c7-9746e3dbfc81   pvc-de21bfb9-3f0d-4915-a151-a115e2753cc6   2024-07-19T07:55:43Z   true         1073741824    20480      6m40s
b012037f-5300-441d-80cd-44a80ac33c09   pvc-01dc0f12-8740-4b52-b1bf-6b565d53c514                          true         1073741824    3145728    6m2s
ffd70875-dafb-4223-ace1-3cb1dd1f38c0   pvc-01dc0f12-8740-4b52-b1bf-6b565d53c514                          true         1073741824    57671680   6m17s
```

![image](https://github.com/user-attachments/assets/892b4e80-f192-48e9-a519-5d5280b9de98)

In above state(upgraded to v1.7.0-dev), create a new v2 volume snapshot succeed without any problems
![image](https://github.com/user-attachments/assets/6cb8176a-bc54-4f64-8785-cebf491ef292)

## To Reproduce

1. Install v1.6.2 and enable v2 data engine
2. Create workload with v2 volume.
3. Write data into mount point and then take snapshot, repeat severl times
4. Scale workload to detach the v2 volume
5. Upgrade to v1.7.0-dev, and reattach the v2 volume,  snapshots of v2 volume creation time disappear

## Expected behavior

After upgrade, v2 volume snapshto creation time not disappear

## Support bundle for troubleshooting

[supportbundle_c21f1f34-e856-42a2-a1ee-f01ddb51b33a_2024-07-19T08-06-39Z.zip](https://github.com/user-attachments/files/16309181/supportbundle_c21f1f34-e856-42a2-a1ee-f01ddb51b33a_2024-07-19T08-06-39Z.zip)

## Environment

 - Longhorn version: v1.7.0-dev
 - Impacted volume (PV): pvc-01dc0f12-8740-4b52-b1bf-6b565d53c514
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: SLES15 SP6
   - Kernel version: 6.4.0-150600.23.7-default

## Additional context

N/A

**Comment by derekbit** [comment]
@DamiaSan 
It might be due to that the snapshot created before v1.7.0 doesn't have snapshot timestamp xattr.
Might need to fallback to old xattr if the new xattr is not found?
Could you help handle it? Thank you.

**Comment by DamiaSan** [comment]
> @DamiaSan It might be due to that the snapshot created before v1.7.0 doesn't have snapshot timestamp xattr. Might need to fallback to old xattr if the new xattr is not found? Could you help handle it? Thank you.

Yes, it should be the right solution.

**Comment by DamiaSan** [comment]
PR to fix the issue
https://github.com/longhorn/longhorn-instance-manager/pull/559

**Comment by derekbit** [comment]
@DamiaSan 
The PR is merged. You can move the PR to `review` and generate the check list. After finishing the check list, please move it to `ready for testing`. Thank you.

**Comment by chriscchien** [comment]
Verffied **pass** on longhorn v1.7.x(longhorn-instance-manager `b6bf4a`) with test [steps](https://github.com/longhorn/longhorn/issues/9045#issue-2418329527)


v2 volume snapshot have creation time after upgrade from v1.6.2 to v1.7.x-head
```bash
>kl get snapshot | grep pvc-4f36f5df-a28a-4801-a394-acf40ed894b4
07a38bdd-9984-4b16-9952-29940b41f981   pvc-4f36f5df-a28a-4801-a394-acf40ed894b4   2024-07-22T01:10:42Z   true         1073741824    3145728    17m
51311882-a2b6-475f-8382-228ae9f1682b   pvc-4f36f5df-a28a-4801-a394-acf40ed894b4   2024-07-22T01:10:35Z   true         1073741824    57671680   17m
db197088-1db3-4755-964a-6d368bcca886   pvc-4f36f5df-a28a-4801-a394-acf40ed894b4   2024-07-22T01:10:49Z   true         1073741824    3145728    17m
```
