### ISSUE TITLE
longhorn-driver-deployer crashes

### ISSUE THREAD

**Issue by yujunz** [longhorn/longhorn#905]
```
time="2019-11-21T08:12:58Z" level=debug msg="Deploying CSI driver"
time="2019-11-21T08:12:58Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"
time="2019-11-21T08:12:59Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"
time="2019-11-21T08:13:00Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"
time="2019-11-21T08:13:01Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Running"
time="2019-11-21T08:13:02Z" level=info msg="Proc found: kubelet"
time="2019-11-21T08:13:02Z" level=info msg="Try to find arg [--root-dir] in cmdline: [/usr/local/bin/kubelet --logtostderr=true --v=2 --node-ip=10.0.1.211 --hostname-override=i-0215eb277cfdece28 --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --config=/etc/kubernetes/kubelet-config.yaml --kubeconfig=/etc/kubernetes/kubelet.conf --pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.1 --runtime-cgroups=/systemd/system.slice --node-labels= --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin ]"
time="2019-11-21T08:13:02Z" level=warning msg="Cmdline of proc kubelet found: \"/usr/local/bin/kubelet\x00--logtostderr=true\x00--v=2\x00--node-ip=10.0.1.211\x00--hostname-override=i-0215eb277cfdece28\x00--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf\x00--config=/etc/kubernetes/kubelet-config.yaml\x00--kubeconfig=/etc/kubernetes/kubelet.conf\x00--pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.1\x00--runtime-cgroups=/systemd/system.slice\x00--node-labels=\x00--network-plugin=cni\x00--cni-conf-dir=/etc/cni/net.d\x00--cni-bin-dir=/opt/cni/bin\x00\". But arg \"--root-dir\" not found. Hence default value will be used: \"/var/lib/kubelet\""
time="2019-11-21T08:13:02Z" level=info msg="Detected root dir path: /var/lib/kubelet"
time="2019-11-21T08:13:02Z" level=info msg="Upgrading Longhorn related components for CSI v1.1.0"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1480fb2]
goroutine 1 [running]:
github.com/longhorn/longhorn-manager/app.upgradeLonghornRelatedComponents(0xc00048c8c0, 0xc00004200e, 0xa,
0x0, 0x0)
        /go/src/github.com/longhorn/longhorn-manager/app/upgrader.go:33 +0x252
github.com/longhorn/longhorn-manager/app.deployCSIDriver(0xc00048c8c0, 0xc00048fc00, 0xc00044b760, 0x7ffd48
96d7d7, 0x22, 0x7ffd4896d808, 0x1f, 0x184cc13, 0x9)
        /go/src/github.com/longhorn/longhorn-manager/app/driver.go:193 +0x575
github.com/longhorn/longhorn-manager/app.deployDriver(0xc00044b760, 0x5, 0x0)
        /go/src/github.com/longhorn/longhorn-manager/app/driver.go:142 +0x38b
github.com/longhorn/longhorn-manager/app.DeployDriverCmd.func1(0xc00044b760)
        /go/src/github.com/longhorn/longhorn-manager/app/driver.go:98 +0x2f
github.com/urfave/cli.HandleAction(0x158b0c0, 0x18f3b58, 0xc00044b760, 0xc00044b760, 0x0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:525 +0x127
github.com/urfave/cli.Command.Run(0x1851197, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/command.go:174 +0x51c
github.com/urfave/cli.(*App).Run(0xc000143880, 0xc00003a070, 0x7, 0x7, 0x0, 0x0)
        /go/src/github.com/longhorn/longhorn-manager/vendor/github.com/urfave/cli/app.go:276 +0x718
main.main()
        /go/src/github.com/longhorn/longhorn-manager/main.go:57 +0x521
```

**Comment by shuo-wu** [comment]
Thank you for your report. I will fix it soon.

**Comment by shuo-wu** [comment]
Test Steps:
1. Launch Longhorn v0.6.2
2. Create some workloads using Longhorn volumes via the StorageClass
3. Create one volume with its PV:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rancher.io/longhorn
  finalizers:
    - kubernetes.io/pv-protection
  name: test1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: <Your Volume Name>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem
```
4. Upgrade to v0.7.0.
--> Check the log of the longhorn-driver-deployer pod. 
--> Check if all Longhorn related PVs are not using the annotation `pv.kubernetes.io/provisioned-by: rancher.io/longhorn`
--> Check if all Longhorn related PVCs are using the annotation `volume.beta.kubernetes.io/storage-provisioner: rancher.io/longhorn`

**Comment by tquang89** [comment]
I'm stucking at deploy driver for first time, too.
`
longhorn-system   longhorn-driver-deployer-5558df9859-6cg6f   0/1     Init:0/1
`

Just 1 line log:
`
[root@k1 ~]# kubectl -n longhorn-system logs pods/longhorn-driver-deployer-5558df9859-6cg6f
Error from server (BadRequest): container "longhorn-driver-deployer" in pod "longhorn-driver-deployer-5558df9859-6cg6f" is waiting to start: PodInitializing
`

And describe:
`
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  20m   default-scheduler  Successfully assigned longhorn-system/longhorn-driver-deployer-5558df9859-6cg6f to k3
  Normal  Pulled     20m   kubelet, k3        Container image "longhornio/longhorn-manager:v0.7.0" already present on machine
  Normal  Created    20m   kubelet, k3        Created container wait-longhorn-manager
  Normal  Started    20m   kubelet, k3        Started container wait-longhorn-manager
`

All of nodes are installed iscsi:
`
[root@k1 ~]# rpm -qa | grep iscsi
iscsi-initiator-utils-6.2.0.874-11.el7.x86_64
iscsi-initiator-utils-iscsiuio-6.2.0.874-11.el7.x86_64
iscsi-initiator-utils-devel-6.2.0.874-11.el7.x86_64
`

**Comment by shuo-wu** [comment]
> e

Could you provide your environment info? It seems that your Kubernetes cluster cannot launch pods correctly. 

And I found there are many similar issues by searching the event info of the longhorn-ui pod `open /run/flannel/subnet.env: no such file or directory`. e.g.:
https://stackoverflow.com/questions/52506248/kubernetes-open-run-flannel-subnet-env-no-such-file-or-directory

**Comment by tquang89** [comment]
Here are basic of enviroment:
```
[root@k1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

[root@k1 ~]# cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)

[root@k1 ~]# rpm -qa | grep docker
docker-ce-18.06.2.ce-3.el7.x86_64

[root@k1 ~]# kubectl get pods -n kube-system -o=wide
NAME                          READY   STATUS    RESTARTS   AGE     IP               NODE   NOMINATED NODE   READINESS GATES
coredns-5644d7b6d9-5zmb6      1/1     Running   4          4d22h   10.244.0.10      k1     <none>           <none>
coredns-5644d7b6d9-6pnvg      1/1     Running   4          4d22h   10.244.0.11      k1     <none>           <none>
kube-apiserver-k1             1/1     Running   4          4d22h   192.168.56.101   k1     <none>           <none>
kube-controller-manager-k1    1/1     Running   4          4d22h   192.168.56.101   k1     <none>           <none>
kube-flannel-ds-amd64-f6x8b   1/1     Running   4          4d22h   192.168.56.103   k3     <none>           <none>
kube-flannel-ds-amd64-fxz66   1/1     Running   4          4d22h   192.168.56.101   k1     <none>           <none>
kube-flannel-ds-amd64-xpq8g   1/1     Running   5          4d22h   192.168.56.102   k2     <none>           <none>
kube-proxy-7z44r              1/1     Running   4          4d22h   192.168.56.101   k1     <none>           <none>
kube-proxy-r5x9l              1/1     Running   4          4d22h   192.168.56.102   k2     <none>           <none>
kube-proxy-x8d9r              1/1     Running   4          4d22h   192.168.56.103   k3     <none>           <none>
kube-scheduler-k1             1/1     Running   4          4d22h   192.168.56.101   k1     <none>           <none>
```

**Comment by yujunz** [comment]
Built a custom image from https://github.com/longhorn/longhorn-manager/pull/477 and the problem seems no longer exists.

Thank you @shuo-wu

**Comment by shuo-wu** [comment]
The cause of this issue:
The Longhorn v0.7.0 will try to find the corresponding PVCs for all old Longhorn related PVs. Then the NPE will be triggered if the PV doesn't somehow have an existing PVC.

The workaround for this issue (without building the image):
1. Clean up all orphaned Longhorn related PVs (have no corresponding PVCs and Longhorn volumes)
2. Create PVCs for all the PVs which have no PVCs via Longhorn UI.
3. Delete the crashed longhorn-driver-deployer pod and wait for new pod launching

**Comment by shuo-wu** [comment]
@yujunz Could you check if there is a PV with annotation `pv.kubernetes.io/provisioned-by` not containing the field `spec.claimRef` and tell us how to trigger that?

**Comment by yujunz** [comment]
There were three PV created by local volume provisioner but I have just deleted them yesterday. I don't remember any PVC created for them as they are kind of pre-provisioned PVs.

**Comment by yasker** [comment]
@yujunz 

A little bit of background.

We found this issue will be triggered if:
1. The PV was provisioned using a storage class. So the annotation `pv.kubernetes.io/provisioned-by` is set.
2. The PV doesn't have `spec.claimRef` which is a reference to the PVC that created the PV.

The NPE was triggered by `spec.claimRef == nil`.

The problem is, normally if a PV was created using the storage class, PV's `spec.claimRef` will be set. When the PVC was deleted, the field won't be cleaned up automatically (some discussions can be found in https://github.com/kubernetes/kubernetes/issues/65581 ). 

That's why we're wondering, is there anything else that happened to the PV which results in the empty `spec.claimRef`?

Longhorn has the logic to clean up `spec.claimRef` when creating a PVC for an existing PV in the Longhorn UI. But it's in the process of binding the PV to another PVC, and it won't leave the field empty for long if everything went well. So we're not sure if it's one triggered the bug.

**Comment by yujunz** [comment]
I just tried with a simple directory as local volume. It has ` pv.kubernetes.io/provisioned-by` but no `spec.claimRef`.

Is it something that can trigger this condition?

```
❯ kubectl get pv local-pv-304618f -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: local-volume-provisioner-i-0767462c2408d155d-28ab04ea-b676-4363-8537-345a0198fcfd
  creationTimestamp: "2019-11-28T02:48:06Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: local-pv-304618f
  resourceVersion: "10499798"
  selfLink: /api/v1/persistentvolumes/local-pv-304618f
  uid: 7315b7e6-7eba-444d-a028-a5541af05c20
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 48Gi
  local:
    fsType: ext4
    path: /mnt/disks/tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - i-0767462c2408d155d
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  volumeMode: Filesystem
status:
  phase: Available
```
Refer to 

See https://github.com/kubernetes-sigs/kubespray/blob/master/roles/kubernetes-apps/external_provisioner/local_volume_provisioner/README.md#simple-directories

**Comment by yujunz** [comment]
And the storage class

```
❯ kubectl get storageclass local-storage -o yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"local-storage"},"provisioner":"kubernetes.io/no-provisioner","volumeBindingMode":"WaitForFirstConsumer"}
  creationTimestamp: "2019-11-19T08:49:20Z"
  name: local-storage
  resourceVersion: "7143967"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/local-storage
  uid: 988b0dd3-f070-4d01-ad5a-dd0f0d71df99
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

**Comment by shuo-wu** [comment]
Interesting. This local storage provisioner is different from the normal storage provisioner. It will create the available local volumes and PVs first then wait for PVC consumption. Then this issue can be triggered:
https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/getting-started.md#step-3-creating-local-persistent-volumes

We need to be careful about this case and check the `claimRef` field next time when we operate PVs.

**Comment by yujunz** [comment]
Isn't this local storage provisioner **static** as named ?

**Comment by shuo-wu** [comment]
Yes. I forget to consider this corner case. The PV created by this static provisioner contains the annotation, which causes this issue.

**Comment by meldafrawi** [comment]
Validation: **PASS**

Steps to test:
  - Deploy Local Path Provisioner (https://github.com/rancher/local-path-provisioner)
  - Create a hostPath backed Persistent Volume and a pod uses it:
`kubectl create -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/examples/pvc.yaml`
`kubectl create -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/examples/pod.yaml`

  - Deploy Longhorn v0.6.2
  - Create some workloads using Longhorn volumes via the StorageClass.
  - write data to Longhorn volume and compute its checksum.
  - Create one volume with its PV:
  ```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rancher.io/longhorn
  finalizers:
    - kubernetes.io/pv-protection
  name: test1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: <Your Volume Name>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem
```
- Upgrade to Longhorn `master`:
> Check the log of the longhorn-driver-deployer pod.
> Check if all Longhorn related PVs are not using the annotation `pv.kubernetes.io/provisioned-by: rancher.io/longhorn`
>  Check if all Longhorn related PVCs are not using the annotation `volume.beta.kubernetes.io/storage-provisioner: rancher.io/longhorn`
> Check data checksum.
