### ISSUE TITLE
[BUG] replicas infinitely rebuilding 

### ISSUE THREAD

**Issue by khumps** [longhorn/longhorn#9051]
## Describe the bug

replicas trying to rebuild will get part way through rebuilding then error out and restart. replicas will continue to try to rebuild but will never converge

## To Reproduce

anything that causes a replica to need to rebuild:
- reboot node
- delete instance-manager pod
- drain node with kubectl

## Expected behavior

volume should eventually rebuild withou failing multiple times

## Support bundle for troubleshooting

File was too big for github, uploaded to google drive
https://drive.google.com/file/d/1xmtxt59kCe558WIJ3vaf-WWtsqerJPo7/view?usp=sharing

## Environment

4 node microk8s cluster
2 nodes bare-metal
2 nodes vms on different bare-metal hosts

 - Longhorn version: 1.6.2
 - Impacted volume (PV): 
       - pvc-401857da-52cf-40ee-add5-60c6f5514e76
       - pvc-0e09fefb-6fcc-4c04-9974-2269fc1ae455
       - pvc-be77de06-ede7-489b-bc54-5c6faaeadb98
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: microk8s 1.28
   - Number of control plane nodes in the cluster: 4 (3  active, 1 standby)
   - Number of worker nodes in the cluster: 0
 - Node config
   - OS type and version: ubuntu 22.04
   - Kernel version: pvc-be77de06-ede7-489b-bc54-5c6faaeadb98
   - CPU per node: 4C/8T and 6C/12T
   - Memory per node: 32GB and 64GB
   - Disk type (e.g. SSD/NVMe/HDD): boot drive NVMe, volumes SSD
   - Network bandwidth between the nodes (Gbps): 2x1Gps in 802.3ad LAGG w/layer3+4 hashing 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal, kvm
 - Number of Longhorn volumes in the cluster:17

## Additional context

- ethtool was showing rx_discards on the node receiving data to rebuild which I thought was the issue, I increased the rx ring buffer size from 200->1000 and the discards stopped but the errors are still happening. There are no tx_discards/errors on any of the sending nodes
- small volumes don't tend to have any issues, the issues all seem to be in larger (400GB and 600GB) volumes
- all devices are connected to the same switch, the switch shows no network errors and ample processing to do line-rate switching

**Comment by khumps** [comment]
to test, I tried setting all replica counts to their current value except for one to see if the behavior occurs with just a single volume rebuilding at a time. It got a lot farther but ultimately failed with the same errors

**Comment by derekbit** [comment]
There are many **r/w timeout** and **read: connection reset by peer** errors. The network status seems not stable, and in addition, the network interface is only 2x1Gps. Are the workload IO intensive?

**Comment by khumps** [comment]
the workloads are not very intensive, I see approximately 5 Mbps of continuous traffic between nodes, far from saturated when not rebuilding. During rebuilds it caps out a little under 1G per interface (2Gbps if it can make use of the 802.3ad talking to two nodes together). I'll continue troubleshooting for network issues, but it would be really nice if longhorn had a way to gracefully recover and resume rebuilding without losing all the progress made.

**Comment by derekbit** [comment]
Longhorn does not support IO throttling for replica rebuilding. As a result, when one replica is being rebuilt, it increases the IO latency for other volumes and may increase the likelihood of replica failures for those volumes in a low bandwidth environment. Can you observe the IO throughput between nodes when there is one replica is being rebuilt?

**Comment by khumps** [comment]
It was sustaining around 960-980 Mbps (basically full saturation of the gigabit link). The SSDs were sustaining a consistent 115 MB/s at 50% io time. The cluster actually seems to have recovered of 5 hours ago.

**Comment by derekbit** [comment]
> It was sustaining around 960-980 Mbps (basically full saturation of the gigabit link). The SSDs were sustaining a consistent 115 MB/s at 50% io time. The cluster actually seems to have recovered of 5 hours ago. Nothing seems to suggest a change in network conditions.

Thanks for the update. I think the saturation might introduce instability.
We will have [IO throttle for the background](https://github.com/longhorn/longhorn/issues/4765), and it might be helpful.

cc @innobead

**Comment by khumps** [comment]
@derekbit that looks like an exciting improvement!

**Comment by derekbit** [comment]
> Should I close this for now and re-open if I find something more concrete?

Sure! Thanks for your update. :)
