### ISSUE TITLE
[BUG] Can not revert V2 volume snapshot after upgrade from v1.6.2 to v1.7.0-dev

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#9054]
## Describe the bug

Can not revert V2 volume snapshot after upgrade from v1.6.2 to v1.7.0-dev

Snapshot created in v1.6.2 become hidden in UI after upgrade to v1.7.0-dev, click `Show System Hidden`, the snapsthos can not revert.
![image](https://github.com/user-attachments/assets/40ab461b-1a0f-40b4-845e-93e171176865)

## To Reproduce

1. Install v1.6.2 and enable v2 data engine
2. Create workload with v2 volume.
3. Write data into mount point and then take snapshot, repeat several times
4. Scale workload to detach the v2 volume
5. Upgrade to v1.7.0-dev
6. Attach the v2 volume in maintance mode
7. Can not see snapshot in UI in volume detail page
8. Enable `Show System Hidden` in volume detail page
9. Can see snapshots created in v1.6.2, but no option to revert them

## Expected behavior

Can revert v2 volume sanpshot created in v1.6.2 after upgrade to v1.7.x-head

## Support bundle for troubleshooting

[supportbundle_be5211d1-36a6-4989-94a5-88a8f61e7351_2024-07-22T01-47-47Z.zip](https://github.com/user-attachments/files/16326909/supportbundle_be5211d1-36a6-4989-94a5-88a8f61e7351_2024-07-22T01-47-47Z.zip)

## Environment

 - Longhorn version: v1.7.x-head
 - Impacted volume (PV): pvc-d8dc0ac9-81b4-4c44-8702-b407d81e16d3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1
 - Node config
   - OS type and version: SLES15 SP6

## Additional context

https://github.com/longhorn/longhorn/issues/9045

**Comment by chriscchien** [comment]
Update, this is UI issue, I can success revert a V2 snapshot in specific [state](https://github.com/longhorn/longhorn/issues/9054#issue-2421736464) through API

![image](https://github.com/user-attachments/assets/1859ca34-8089-450b-b6e8-0a382697af65)

**Comment by derekbit** [comment]
@a110605 Can you help resolve the UI issue? Thank you.

**Comment by a110605** [comment]
The revert option will not shown up if snapshot [data[x].usercreated](https://github.com/a110605/longhorn-ui/blob/1a660bed0ecaab6e643134d1c6c8801f43cd1083/src/components/Snapshot/Snapshot.js#L99) is false or undefined.

Check response from `POST /v1/volumes/pvc-e1b53d2c-7ad3-44e6-b53f-9230b0768855?action=snapshotList`
<img width="1494" alt="Screenshot 2024-07-22 at 2 40 52 PM" src="https://github.com/user-attachments/assets/e0a32be1-04ee-4e0e-8303-9a7a42cb558c">

From above screenshot, user created in hover tooltip is `False`.

**Comment by derekbit** [comment]
cc @DamiaSan 👆

**Comment by derekbit** [comment]
@a110605 If the longhorn-system is a fresh installation, does it work exectededly?

**Comment by DamiaSan** [comment]
Before to update to 1.7.0, could you revert the snapshot? Because the user created flag has been implemented recently in v2 engine, so I think that this flag wasn't present in 1.6.2 too, causing the snapshot to be non revertable.

**Comment by a110605** [comment]
> Before to update to 1.7.0, could you revert the snapshot? Because the user created flag has been implemented recently in v2 engine, so I think that this flag wasn't present in 1.6.2 too, causing the snapshot to be non revertable.

Yes, I can revert the snapshot in v1.6.2. And the usercreated flag exists in `/v1/volumes/pvc-e1b53d2c-7ad3-44e6-b53f-9230b0768855?action=snapshotList` response. 

Did we backport this flag to v1.6.2 ?
<img width="1496" alt="Screenshot 2024-07-22 at 3 35 09 PM" src="https://github.com/user-attachments/assets/0b05a862-6841-46c7-89fc-5d7c05e108b6">

**Comment by derekbit** [comment]
> > Before to update to 1.7.0, could you revert the snapshot? Because the user created flag has been implemented recently in v2 engine, so I think that this flag wasn't present in 1.6.2 too, causing the snapshot to be non revertable.
> 
> I can revert the snapshot in v1.6.2 and `usercreated` flag exists in `/v1/volumes/pvc-e1b53d2c-7ad3-44e6-b53f-9230b0768855?action=snapshotList` response.
> 

How about the v1.7.0-rc1 fresh installation?

**Comment by DamiaSan** [comment]
> Did we backport this flag to v1.6.2 ?

I don't think so.
Maybe the 1.6.2 has the user created flag in memory? I f so, if we restart the `longhorn-instance-manager` and the replicas, it should disapper because it is not stored on disk.
What do you think @derekbit ?

**Comment by derekbit** [comment]
The UserCreated flag is from xattr in v1.7.0. In v1.6.2, it is always `true` because we don't persistent the information. Therefore, we can fall back to `true` if the xattr is not found. WDYT? @DamiaSan 

In addition, @a110605 need to make sure the revert works well in v1.7.0.

**Comment by DamiaSan** [comment]
> The UserCreated flag is from xattr in v1.7.0. In v1.6.2, it is always `true` because we don't persistent the information. Therefore, we can fall back to `true` if the xattr is not found. WDYT? @DamiaSan
> 
> In addition, @a110605 need to make sure the revert works well in v1.7.0.

You're right, I think this is the only way to let the user created snapshot to be listed by the UI.
I am going to make the change in `go-spdk-helper`, if no `user_creatdd` xattr is found, the snapshot flag will be set to true.

**Comment by derekbit** [comment]
> > The UserCreated flag is from xattr in v1.7.0. In v1.6.2, it is always `true` because we don't persistent the information. Therefore, we can fall back to `true` if the xattr is not found. WDYT? @DamiaSan
> > In addition, @a110605 need to make sure the revert works well in v1.7.0.
> 
> You're right, I think this is the only way to let the user created snapshot to be listed by the UI. I am going to make the change in `go-spdk-helper`, if no `user_creatdd` xattr is found, the snapshot flag will be set to true.

Thank you @DamiaSan @a110605.

**Comment by DamiaSan** [comment]
PR to fix the issue: https://github.com/longhorn/go-spdk-helper/pull/131

**Comment by DamiaSan** [comment]
`go-spdk-helper` fixed, going to update `longhorn-spdk-engine`

**Comment by DamiaSan** [comment]
PR for `longhorn-spdk-engine` https://github.com/longhorn/longhorn-spdk-engine/pull/185

**Comment by DamiaSan** [comment]
PR for `longhorn-instance-manager` https://github.com/longhorn/longhorn-instance-manager/pull/572

**Comment by DamiaSan** [comment]
All PRs for the fix have been merged

**Comment by derekbit** [comment]
@DamiaSan 
Don't forget to move the ticket to `review` and generate a pre-check list. After filling in the list, move it to `ready for testing`.

**Comment by chriscchien** [comment]
Hi @DamiaSan 

In a fresh installed cluster, I still can not revert snapshot through UI, could you take a look on this? thank you.
![image](https://github.com/user-attachments/assets/df58ce93-ade4-475f-959b-4019783ae62a)

the user created flag is false after upgrade from v1.6.2 to v1.7.x-head
```bash
> kl get snapshot e9e8dc2b-c05d-4452-9d7d-44aecca0089f -o yaml | grep userCreated
  userCreated: false
```

images
```bash
> kl get pods -o yaml | grep "image: longhornio"
      image: longhornio/longhorn-engine:v1.6.2
      image: longhornio/longhorn-engine:v1.6.2
      image: longhornio/longhorn-engine:v1.6.2
      image: longhornio/longhorn-ui:v1.7.x-head
      image: longhornio/longhorn-manager:v1.7.x-head
      image: longhornio/longhorn-share-manager:v1.7.x-head
      image: longhornio/longhorn-manager:v1.7.x-head
      image: longhornio/longhorn-share-manager:v1.7.x-head
      image: longhornio/longhorn-ui:v1.7.x-head
      image: longhornio/longhorn-manager:v1.7.x-head
      image: longhornio/longhorn-share-manager:v1.7.x-head
      image: longhornio/longhorn-manager:v1.7.x-head
      image: longhornio/longhorn-manager:v1.7.x-head
      image: longhornio/longhorn-engine:v1.7.x-head
      image: longhornio/longhorn-engine:v1.7.x-head
      image: longhornio/longhorn-engine:v1.7.x-head
      image: longhornio/longhorn-instance-manager:v1.7.x-head
      image: longhornio/longhorn-instance-manager:v1.7.x-head
      image: longhornio/longhorn-instance-manager:v1.7.x-head
      image: longhornio/longhorn-instance-manager:v1.7.x-head
      image: longhornio/longhorn-instance-manager:v1.7.x-head
      image: longhornio/longhorn-instance-manager:v1.7.x-head
      image: longhornio/csi-attacher:v4.6.1
      image: longhornio/csi-attacher:v4.6.1
      image: longhornio/csi-attacher:v4.6.1
      image: longhornio/csi-provisioner:v4.0.1
      image: longhornio/csi-provisioner:v4.0.1
      image: longhornio/csi-provisioner:v4.0.1
      image: longhornio/csi-resizer:v1.11.1
      image: longhornio/csi-resizer:v1.11.1
      image: longhornio/csi-resizer:v1.11.1
      image: longhornio/csi-snapshotter:v7.0.2
      image: longhornio/csi-snapshotter:v7.0.2
      image: longhornio/csi-snapshotter:v7.0.2
      image: longhornio/csi-node-driver-registrar:v2.10.1
      image: longhornio/livenessprobe:v2.12.0
      image: longhornio/longhorn-manager:v1.7.x-head
      image: longhornio/csi-node-driver-registrar:v2.10.1
      image: longhornio/livenessprobe:v2.12.0
      image: longhornio/longhorn-manager:v1.7.x-head
      image: longhornio/csi-node-driver-registrar:v2.10.1
      image: longhornio/livenessprobe:v2.12.0
      image: longhornio/longhorn-manager:v1.7.x-head
```

from docker hub I can see longhorn-instance-manager [dbfb765937a1](https://hub.docker.com/layers/longhornio/longhorn-instance-manager/v1.7.x-head/images/sha256-dbfb765937a138c598a4c16c627f10cbbf706d395a8c701154f58856832c1b81?context=explore) were built 11 hours ago but longhorn-manager image [30499bbcaa95](https://hub.docker.com/layers/longhornio/longhorn-manager/v1.7.x-head/images/sha256-30499bbcaa9538e478b20dcaecca3970f83533b58bce220c82ae4405e74ae476?context=explore)  were 2 days ago. not sure if this is related.

**Comment by chriscchien** [comment]
longhorn-manager v1.7.x image updated then I tested again, find that a v2 volume snapshot `userCreated` wiil become `false` after v2 volume attached. the test result still fail as previous [test](https://github.com/longhorn/longhorn/issues/9054#issuecomment-2244102717)

Snapshot in v1.6.2
```bash
> kl get snapshot 654224b2-73d0-47f5-a9ce-0673ff45ee45 -o yaml | grep userCreated
  userCreated: true

```
Snapshot after upfraded to v1.7.x (volume detached)
```bash
>kl get volume
NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE   AGE
pvc-18d41831-63c4-4706-8ac4-477766166469   v2            detached   unknown                  1073741824          3m45s
>
> kl get snapshot 654224b2-73d0-47f5-a9ce-0673ff45ee45 -o yaml | grep userCreated
  userCreated: true
```
Snapshot after upfraded to v1.7.x (volume attached)
```bash
> kl get volume
NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE           AGE
pvc-18d41831-63c4-4706-8ac4-477766166469   v2            attached   healthy                  1073741824   ip-10-0-1-45   4m33s
>
> kl get snapshot 654224b2-73d0-47f5-a9ce-0673ff45ee45 -o yaml | grep userCreated
  userCreated: false
```

**Comment by derekbit** [comment]
cc @DamiaSan

**Comment by DamiaSan** [comment]
The commit of `longhorn-instance-manager` with the fix is this: https://github.com/longhorn/longhorn-instance-manager/commit/309ac90430aa6dc93fde656feccee73d6cee58d7
What commit does it contain the version you are using from docker hub?

**Comment by chriscchien** [comment]
Hi @DamiaSan 

https://hub.docker.com/layers/longhornio/longhorn-instance-manager/v1.7.x-head/images/sha256-dbfb765937a138c598a4c16c627f10cbbf706d395a8c701154f58856832c1b81?context=explore
```bash
> crictl inspecti docker.io/longhornio/longhorn-instance-manager:v1.7.x-head
{
  "status": {
    "id": "sha256:b7f488f32ed54dd04fea0043d2a57398effdfe4d50988428ab78359f8efc3c66",
    "repoTags": [
      "docker.io/longhornio/longhorn-instance-manager:v1.7.x-head"
    ],
    "repoDigests": [
      "docker.io/longhornio/longhorn-instance-manager@sha256:71fc64fd7e89d53d0fa52c64d1f4d67c16b74d21cd96c3795e7fdaec5bc63576"
    ],
    "size": "356858218",
    "uid": null,
    "username": "",
    "spec": null,
    "pinned": false
  },
  "info": {
    "chainID": "sha256:6c72c8f1a5f18ac96ffaca7458e35da6dc15bbf5c6e50cdc3d48bf9323a389c7",
    "imageSpec": {
      "created": "2024-07-22T14:50:31.795291024Z",
      "author": "SUSE LLC (https://www.suse.com/)",
      "architecture": "amd64",
      "os": "linux",
      "config": {
        "Env": [
          "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
          "TINI_VERSION=v0.19.0"
        ],
        "Entrypoint": [
          "/tini",
          "--"
        ],
        "Cmd": [
          "longhorn"
        ],
        "Labels": {
          "com.suse.bci.base.created": "2024-07-11T10:31:49.098397435Z",
          "com.suse.bci.base.description": "Image for containers based on SUSE Linux Enterprise Server 15 SP6.",
          "com.suse.bci.base.disturl": "obs://build.suse.de/SUSE:SLE-15-SP6:Update:CR/images/d84452b8ed9fb6cd35609d0718c6b282-sles15-image",
          "com.suse.bci.base.eula": "sle-bci",
          "com.suse.bci.base.image-type": "sle-bci",
          "com.suse.bci.base.lifecycle-url": "https://www.suse.com/lifecycle#suse-linux-enterprise-server-15",
          "com.suse.bci.base.reference": "registry.suse.com/suse/sle15:15.6.47.5.15",
          "com.suse.bci.base.release-stage": "released",
          "com.suse.bci.base.source": "https://sources.suse.com/SUSE:SLE-15-SP6:Update:CR/sles15-image/d84452b8ed9fb6cd35609d0718c6b282/",
          "com.suse.bci.base.supportlevel": "l3",
          "com.suse.bci.base.title": "SLE BCI 15 SP6 Base Container Image",
          "com.suse.bci.base.url": "https://www.suse.com/products/base-container-images/",
          "com.suse.bci.base.vendor": "SUSE LLC",
          "com.suse.bci.base.version": "15.6.47.5.15",
          "com.suse.eula": "sle-bci",
          "com.suse.image-type": "sle-bci",
          "com.suse.lifecycle-url": "https://www.suse.com/lifecycle#suse-linux-enterprise-server-15",
          "com.suse.release-stage": "released",
          "com.suse.supportlevel": "l3",
          "io.artifacthub.package.logo-url": "https://opensource.suse.com/bci/SLE_BCI_logomark_green.svg",
          "io.artifacthub.package.readme-url": "https://sources.suse.com/SUSE:SLE-15-SP6:Update:CR/sles15-image/d84452b8ed9fb6cd35609d0718c6b282//README.md",
          "org.openbuildservice.disturl": "obs://build.suse.de/SUSE:SLE-15-SP6:Update:CR/images/d84452b8ed9fb6cd35609d0718c6b282-sles15-image",
          "org.opencontainers.image.created": "2024-07-11T10:31:49.098397435Z",
          "org.opencontainers.image.description": "Image for containers based on SUSE Linux Enterprise Server 15 SP6.",
          "org.opencontainers.image.source": "https://sources.suse.com/SUSE:SLE-15-SP6:Update:CR/sles15-image/d84452b8ed9fb6cd35609d0718c6b282/",
          "org.opencontainers.image.title": "SLE BCI 15 SP6 Base Container Image",
          "org.opencontainers.image.url": "https://www.suse.com/products/base-container-images/",
          "org.opencontainers.image.vendor": "SUSE LLC",
          "org.opencontainers.image.version": "15.6.47.5.15",
          "org.opensuse.reference": "registry.suse.com/suse/sle15:15.6.47.5.15"
        },
        "ArgsEscaped": true
      },
      "rootfs": {
        "type": "layers",
        "diff_ids": [
          "sha256:af3b0a719a67204a34a48bb76230f776d5947a8e82a30f0530c2a833f1bef49f",
          "sha256:c79d59291894a438c4759da7a0bc4fc732a15223ed39f8652695ec71238c1220",
          "sha256:db2bac9b8e8bbeac2d6125b4988711bec449b02fb8e183396e0c4e31d1699a9a",
          "sha256:8f6579f49dc116aeb3a7073e972624db3dc96ba3d0ac41fb3900669e2f03793c",
          "sha256:4edae16c882dc3617b1e4dad5332241d4f42c483598d5dc36777bbb070c49882",
          "sha256:d7fd5cd4acbd2ffb2fc5cb9425c04d46ec9dc2db8d993204c95e39dfdd0dcf63",
          "sha256:7ce1b51b59226a3a6783c4988839e01ddad1a4139dbc0591c6af6261c90ffa1f",
          "sha256:d00272e6ae17ee4228f9e6189a6f5c90f433bfa21537a17dae70a8faee4b64d7",
          "sha256:26a5226e3c20bf709ee729bbfc07f62153fffcd66f929dcd77452aa01e958a9d",
          "sha256:d4f00e4247b5982ccce5225df2b7af6a5fed5bd98e18192dc7fb6e0c77d1a7cf",
          "sha256:9e6ab1e558c55371e55ec32cddb0cd0c863205283b05f51f132791f5e1053ad2",
          "sha256:7cac7e01d0ad248abc58700c870f0e33cdb93ee482bbbf6a5425455556dde5e7",
          "sha256:6dd42140a267f3d8776f1fb40987a02c8e6b910bca7788c6265f269a0e0d8435",
          "sha256:0dfd2c5d9177fc9f975ac79c9c64e558ef7b56215e84edc1d158eae468838241",
          "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
          "sha256:f5ba333679fde238d0ad161d1326623c9ed4ce9476b582275fa83a057c349c5c",
          "sha256:969568a5a38ff6aaafcb8777e51d5252c21b29151fc922b59e37109165b2e94f"
        ]
      },
      "history": [
        {
          "created": "2024-07-11T10:31:59Z",
          "created_by": "KIWI 9.24.43",
          "author": "SUSE LLC \u003chttps://www.suse.com/\u003e"
        },
        {
          "created": "2024-07-22T14:45:30.732608968Z",
          "created_by": "ARG ARCH=amd64",
          "comment": "buildkit.dockerfile.v0",
          "empty_layer": true
        },
        {
          "created": "2024-07-22T14:45:30.732608968Z",
          "created_by": "RUN |1 ARCH=amd64 /bin/sh -c zypper -n addrepo --refresh https://download.opensuse.org/repositories/system:/snappy/SLE_15/system:snappy.repo \u0026\u0026     zypper -n addrepo --refresh https://download.opensuse.org/repositories/network:/utilities/SLE_15/network:utilities.repo \u0026\u0026     zypper -n addrepo --refresh https://download.opensuse.org/repositories/devel:libraries:c_c++/15.6/devel:libraries:c_c++.repo \u0026\u0026     zypper -n addrepo --refresh https://download.opensuse.org/repositories/devel:languages:python:Factory/15.6/devel:languages:python:Factory.repo \u0026\u0026     zypper -n addrepo --refresh https://download.opensuse.org/repositories/devel:languages:python:backports/SLE_15/devel:languages:python:backports.repo \u0026\u0026     zypper --gpg-auto-import-keys ref # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2024-07-22T14:45:54.907194659Z",
          "created_by": "RUN |1 ARCH=amd64 /bin/sh -c zypper -n install nfs-client nfs4-acl-tools cifs-utils sg3_utils     iproute2 qemu-tools e2fsprogs xfsprogs util-linux-systemd python311-base libcmocka-devel device-mapper netcat kmod jq util-linux procps fuse3-devel \u0026\u0026     rm -rf /var/cache/zypp/* # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2024-07-22T14:49:56.879452971Z",
          "created_by": "COPY /usr/src/spdk/scripts /usr/src/spdk/scripts # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2024-07-22T14:49:56.907041624Z",
          "created_by": "COPY /usr/src/spdk/include /usr/src/spdk/include # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2024-07-22T14:50:29.398934133Z",
          "created_by": "RUN |1 ARCH=amd64 /bin/sh -c bash /usr/src/spdk/scripts/pkgdep.sh # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2024-07-22T14:50:29.491452829Z",
          "created_by": "COPY /usr/local/bin/grpc_health_probe /usr/local/bin/go-spdk-helper /usr/local/bin/ # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2024-07-22T14:50:29.629630459Z",
          "created_by": "COPY /usr/local/bin/spdk_* /usr/local/bin/ # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2024-07-22T14:50:29.654888781Z",
          "created_by": "COPY /usr/local/sbin/nvme /usr/local/sbin/ # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2024-07-22T14:50:29.678785056Z",
          "created_by": "COPY /usr/sbin/tgt-admin /usr/sbin/tgt-setup-lun /usr/sbin/tgtadm /usr/sbin/tgtd /usr/sbin/tgtimg /usr/sbin/ # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2024-07-22T14:50:30.752932861Z",
          "created_by": "COPY /usr/local/lib64 /usr/local/lib64 # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2024-07-22T14:50:30.875236911Z",
          "created_by": "RUN |1 ARCH=amd64 /bin/sh -c ldconfig # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2024-07-22T14:50:31.032030548Z",
          "created_by": "COPY package/bin/longhorn-instance-manager /usr/local/bin/ # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2024-07-22T14:50:31.044287592Z",
          "created_by": "COPY package/instance-manager /usr/local/bin/ # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2024-07-22T14:50:31.662368363Z",
          "created_by": "RUN |1 ARCH=amd64 /bin/sh -c ldd /usr/local/bin/* /usr/local/sbin/* /usr/sbin/* | grep \"not found\" \u0026\u0026 exit 1 || true # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2024-07-22T14:50:31.662368363Z",
          "created_by": "ENV TINI_VERSION=v0.19.0",
          "comment": "buildkit.dockerfile.v0",
          "empty_layer": true
        },
        {
          "created": "2024-07-22T14:50:31.728620329Z",
          "created_by": "ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini-amd64 /tini # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2024-07-22T14:50:31.795291024Z",
          "created_by": "RUN |1 ARCH=amd64 /bin/sh -c chmod +x /tini # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2024-07-22T14:50:31.795291024Z",
          "created_by": "ENTRYPOINT [\"/tini\" \"--\"]",
          "comment": "buildkit.dockerfile.v0",
          "empty_layer": true
        },
        {
          "created": "2024-07-22T14:50:31.795291024Z",
          "created_by": "CMD [\"longhorn\"]",
          "comment": "buildkit.dockerfile.v0",
          "empty_layer": true
        }
      ]
    }
  }
}
```

**Comment by derekbit** [comment]
@DamiaSan I just found `get_xattr` won't return error if a lvol doesn't have `user_created` xattr.

```
instance-manager-e026a7bc17f0cfe4f59893cfc69a8237:/ # go-spdk-helper lvol get-xattr --alias default-disk-98cec9c8/pvc-138652ac-b2e6-4947-b5cf-33ebc15933f5-r-1cbc5708-snap-77e5dcde-aba0-41e9-9680-56f5e96cfe34 --xattr-name user_created
"false"
```

**Comment by DamiaSan** [comment]
@derekbit 
As you found, if the `user_created` returned is false, it means that this xattr is present. When you ask for an xattr that is not present, you get an error:
```
damiano@dhcppc11:~/Development/go-spdk-helper> sudo ./go-spdk-helper lvol get-xattr --alias lvs1/lvol1 --xattr-name name
"lvol1"
damiano@dhcppc11:~/Development/go-spdk-helper> sudo ./go-spdk-helper lvol get-xattr --alias lvs1/lvol1 --xattr-name pippo
FATA[0000] Failed to run get bdev lvol xattr command     error="error sending message, id 1736, method bdev_lvol_get_xattr, params {lvs1/lvol1 pippo}: {\"code\": -32603,\"message\": \"No such file or directory\"}"
```
So, coming back to this issue, I see from the [info](https://github.com/longhorn/longhorn/issues/9054#issuecomment-2244429538) posted by Chris:

- Snapshot in v1.6.2, `user_created` is true
- Snapshot after upfraded to v1.7.x (volume detached), `user_created` is true
- Snapshot after upfraded to v1.7.x (volume attached), `user_created` is false

What can happen when the volume is being attached?

**Comment by derekbit** [comment]
> What can happen when the volume is being attached?

Can you check if user_created is true for a v2 volume's snapshot in v1.6.2? We expect it is true, right?
Then, upgrade to v1.7.x-head and check it again.

**Comment by DamiaSan** [comment]
In 1.6.2, if the `user_created` flag is true, it means that the `user_created` xattr is present in spdk's snapshot. Because in `go-spdk-helper` the code was this (`user_created` is a string):
```
		user_created, err := c.BdevLvolGetXattr(name, UserCreated)
		if err == nil {
			b.DriverSpecific.Lvol.Xattrs[UserCreated] = user_created
		}
```
and in `longhorn-spdk-engine`  (`UserCreated` is a bool):
```
UserCreated:       bdev.DriverSpecific.Lvol.Xattrs[spdkclient.UserCreated] == strconv.FormatBool(true),
```

**Comment by derekbit** [comment]
@DamiaSan 
FYR, always false in v1.6.2
```
# go-spdk-helper lvol get-xattr --alias default-disk-115b9545/pvc-7d284d35-8db4-45f3-abc4-2ee1be130d85-r-6d721c02-snap-5336c835-b4dc-4050-837e-4d9643b54345 --xattr-name user_created
"false"
```

**Comment by derekbit** [comment]
Checking the codes with @DamiaSan. The UserCreated is always set to `false` in v1.6.2, and it is due to
```
VolumeSnapshot(opt==nil)
-> EngineSnapshotCreate (opt is nil, so create a opt with usercreated==false)
-> e.SnapshotCreate (...)
->  ...
-> replica snapshot is created with usercreated==false
```

The `UserCreated` xattr is implemented in the longhorn-spdk-engine for v1.7.0. However, the longhorn-instance-manager v1.6.2 mistakenly introduces this feature but doesn't set an appropriate opt.
We don't have any better workaround for this issue because xattr in a snapshot lvol is immutable. One feasible workaround is to back up snapshots for v2 volumes and restore them. Can we create an important note or KB to address this issue?

The action items will be 
1. Fix the bug in v1.6.3
2. Make sure the issue is already fixed in v1.7.3 
3. Add an important note or KB to address this issue

WDYT? @innobead @DamiaSan @shuo-wu

**Comment by innobead** [comment]
Added `important-note` label. Let's add a notice to inform users about this known issue.

**Comment by derekbit** [comment]
> Added `important-note` label. Let's add a notice to inform users about this known issue.

Updated in https://github.com/longhorn/website/pull/951

**Comment by DamiaSan** [comment]
backport for 1.6.3 done

**Comment by chriscchien** [comment]
The behavior describe in this ticket is expected and had [doc](https://longhorn.io/docs/1.7.0/deploy/important-notes/#unable-to-revert-a-volume-to-a-snapshot-created-before-longhorn-v170) for user to reference, close this ticket.
