### ISSUE TITLE
[BUG][v1.7.x-head] Test case `test_support_bundle_should_not_timeout` support bundle cleanup failed

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9055]
## Describe the bug

Test case `test_support_bundle_should_not_timeout` could fail on `v1.7.x-head` in support bundle cleanup function:

https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-tests-sles-amd64/8/testReport/junit/tests/test_support_bundle/test_support_bundle_should_not_timeout/
https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-tests-sles-amd64/7/testReport/junit/tests/test_support_bundle/test_support_bundle_should_not_timeout/
https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-upgrade-tests-sles-amd64/7/testReport/junit/tests/test_support_bundle/test_support_bundle_should_not_timeout/

The cleanup seems to never completed:

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7302/consoleFull

```
test_support_bundle.py::test_support_bundle_should_not_timeout[66-100] download_url = http://10.42.4.6:9500/v1/supportbundles/ip-10-0-2-54/support-bundle-2024-07-22t06-07-14z/download
wait for supoort bundle cleanup {'data': [{'errorMessage': ': ', 'name': 'support-bundle-2024-07-22t06-07-14z', 'nodeID': 'ip-10-0-2-88', 'progressPercentage': 100, 'state': 'ReadyForDownload'}], 'resourceType': 'supportBundle'} ... (0)
wait for supoort bundle cleanup {'data': [{'errorMessage': ': ', 'name': 'support-bundle-2024-07-22t06-07-14z', 'nodeID': 'ip-10-0-2-88', 'progressPercentage': 100, 'state': 'ReadyForDownload'}], 'resourceType': 'supportBundle'} ... (1)
wait for supoort bundle cleanup {'data': [{'errorMessage': ': ', 'name': 'support-bundle-2024-07-22t06-07-14z', 'nodeID': 'ip-10-0-2-88', 'progressPercentage': 100, 'state': 'ReadyForDownload'}], 'resourceType': 'supportBundle'} ... (2)
wait for supoort bundle cleanup {'data': [{'errorMessage': ': ', 'name': 'support-bundle-2024-07-22t06-07-14z', 'nodeID': 'ip-10-0-2-88', 'progressPercentage': 100, 'state': 'ReadyForDownload'}], 'resourceType': 'supportBundle'} ... (3)
.........
.........
.........
wait for supoort bundle cleanup {'data': [{'errorMessage': ': ', 'name': 'support-bundle-2024-07-22t06-07-14z', 'nodeID': 'ip-10-0-2-88', 'progressPercentage': 100, 'state': 'ReadyForDownload'}], 'resourceType': 'supportBundle'} ... (4041)
wait for supoort bundle cleanup {'data': [{'errorMessage': ': ', 'name': 'support-bundle-2024-07-22t06-07-14z', 'nodeID': 'ip-10-0-2-88', 'progressPercentage': 100, 'state': 'ReadyForDownload'}], 'resourceType': 'supportBundle'} ... (4042)
wait for supoort bundle cleanup {'data': [{'errorMessage': ': ', 'name': 'support-bundle-2024-07-22t06-07-14z', 'nodeID': 'ip-10-0-2-88', 'progressPercentage': 100, 'state': 'ReadyForDownload'}], 'resourceType': 'supportBundle'} ... (4043)
```

## To Reproduce

Run test case `test_support_bundle_should_not_timeout` repeatedly

## Environment

 - Longhorn version: v1.7.x-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: sles 15-sp6
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
cc @mantissahz @c3y1huang

**Comment by mantissahz** [comment]
Here is the root cause:

https://github.com/longhorn/longhorn-tests/blob/29246e32ed354f41bf0bbc95b68374b60b4261b5/manager/integration/tests/test_support_bundle.py#L392-L402

We change the support bundle size manually but we don't wait for the support bundle size updated.

https://github.com/longhorn/longhorn-manager/blob/720380539f3ce13eb4a2b08e676f3a7a57d12cbf/api/supportbundle.go#L82-L87

Then we might set the response header `Content-Length` with the old support bundle size, and it will cause the error `http: wrote more than the declared Content-Length`.

Therefore deleting the support bundle will not start, and `wait_for_support_bundle_cleanup` will not get the result the test case wants.

Running the modified test case `test_support_bundle_should_not_timeout` to wait for the size updated:
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7323/

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-tests 0e783f6). Ran test case `test_support_bundle_should_not_timeout` [100 times](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7327/). All tests passed.
