### ISSUE TITLE
[BUG] StorageClass parameters not saved when editing longhorn-storageclass configMap

### ISSUE THREAD

**Issue by elaurensx** [longhorn/longhorn#9060]
## Describe the bug

Since the longhorn's Helm chart/values.yaml persistence section doesn't include options related to volume encryption, and since it's not possible to [deploy longhorn without it defining a (default) storageClass resource](https://github.com/longhorn/longhorn/issues/2119#issuecomment-748260299), I'm trying to edit the storageClass post-deployment.

After having edited the longhorn-storageclass configMap, the api-server returns `configmap/longhorn-storageclass edited`, but querying the resource confirms that none of the changes have been stored in the configMap.

## To Reproduce

`kubectl edit cm longhorn-storageclass -n <ns>`

Add to data.storageclass.yaml.parameters:

encrypted: true
csi.storage.k8s.io/provisioner-secret-name: "<secret>"
csi.storage.k8s.io/provisioner-secret-namespace: "<ns>"
csi.storage.k8s.io/node-publish-secret-name: "<secret>"
csi.storage.k8s.io/node-publish-secret-namespace: "<ns>"
csi.storage.k8s.io/node-stage-secret-name: "<secret>"
csi.storage.k8s.io/node-stage-secret-namespace: "<ns>"

## Expected behavior

Additional parameters stored in the configMap and (default) storageClass updated (after resource recreation). 

## Environment

 - Longhorn version: v1.6.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): ArgoCD (Helm)
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3S
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 2
 - Node config
   - OS type and version: AlmaLinux 9.4 (Seafoam Ocelot)
   - Kernel version: 5.14.0-427.22.1.el9_4.x86_64
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 0

**Comment by innobead** [comment]
Did you see any logs related to this in longhorn-manager pods while updating the config map?

**Comment by elaurensx** [comment]
I did see a `cannot unmarshal bool into Go struct field StorageClass.parameters of type string` msg appear in the longhorn-manager pods' log so changed encrypted: true to encrypted: "true" (my bad).

Tried to edit the configMap again and this time seeing two entries, first one to indicate that the default storageClass has been updated with the additional parameters..

_time="2024-07-22T12:13:45+02:00" level=info msg="**Updated the default Longhorn StorageClass**: &StorageClass{ObjectMeta:{longhorn    0f3f9965-aa70-47ab-a55e-5c0b81221069 7290302 0 2024-07-22 12:13:45 +0200 CEST <nil> <nil> map[] map[longhorn.io/last-applied-configmap:kind: StorageClass\napiVersion: storage.k8s.io/v1\nmetadata:\n  name: longhorn\n  annotations:\n    storageclass.kubernetes.io/is-default-class: \"false\"\nprovisioner: driver.longhorn.io\nallowVolumeExpansion: true\nreclaimPolicy: \"Retain\"\nvolumeBindingMode: Immediate\nparameters:\n  numberOfReplicas: \"3\"\n  staleReplicaTimeout: \"30\"\n  fromBackup: \"\"\n  fsType: \"ext4\"\n  dataLocality: \"best-effort\"\n  unmapMarkSnapChainRemoved: \"ignored\"\n  **encrypted: \"true\"\n  csi.storage.k8s.io/provisioner-secret-name: \"<secret>\"\n  csi.storage.k8s.io/provisioner-secret-namespace: \"<ns>"\n  csi.storage.k8s.io/node-publish-secret-name: \"<secret>\"\n  csi.storage.k8s.io/node-publish-secret-namespace: \"<ns>\"\n  csi.storage.k8s.io/node-stage-secret-name: \"<secret>\"\n  csi.storage.k8s.io/node-stage-secret-namespace: \"<ns>\"**\n storageclass.kubernetes.io/is-default-class:false] [] [] [{longhorn-manager Update storage.k8s.io/v1 2024-07-22 12:13:45
..._

Immediately followed by what seems to be a revert action..

_time="2024-07-22T12:13:46+02:00" level=info msg="**Updated the default Longhorn StorageClass**: &StorageClass{ObjectMeta:{longhorn    4b7f4d74-43f6-44ae-9ebe-8ccc328f35f4 7290316 0 2024-07-22 12:13:46 +0200 CEST <nil> <nil> map[] map[longhorn.io/last-applied-configmap:kind: StorageClass\napiVersion: storage.k8s.io/v1\nmetadata:\n  name: longhorn\n  annotations:\n    storageclass.kubernetes.io/is-default-class: \"false\"\nprovisioner: driver.longhorn.io\nallowVolumeExpansion: true\nreclaimPolicy: \"Retain\"\nvolumeBindingMode: Immediate\nparameters:\n  numberOfReplicas: \"3\"\n  staleReplicaTimeout: \"30\"\n  fromBackup: \"\"\n  fsType: \"ext4\"\n  dataLocality: \"best-effort\"\n  unmapMarkSnapChainRemoved: \"ignored\"\n storageclass.kubernetes.io/is-default-class:false] [] [] [{longhorn-manager Update storage.k8s.io/v1 2024-07-22 12:13:46
..._

Managed to create a separate longhorn storageClass with the encryption-related parameters and will be using that as the default one as a workaround.

**Comment by derekbit** [comment]
@elaurensx 
Is the content of the configmap reverted as well?

**Comment by elaurensx** [comment]
@derekbit Yes, the configMap is back in its pre-edited state.

**Comment by derekbit** [comment]
I've gone through longhorn-manager v1.6.2 codes, the configMap `longhorn-storageclas` seems not updated by longhorn-manager itself. Does the issue always happen?
