### ISSUE TITLE
[DOC] Update `Quick Installation` document for `longhornctl`

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9075]
## What's the document you plan to update? Why? Please describe

The command-line tool `longhornctl` has been supported since v1.7.0. We can update the [Quick Installation](https://longhorn.io/docs/1.7.0/deploy/install/) and [Quick Start for v2 data engine](https://longhorn.io/docs/1.7.0/v2-data-engine/quick-start/) documentsto include instructions for checking the environment and installing prerequisites.

**Comment by derekbit** [comment]
@mantissahz 
Can you help it and get familiar with the command-line tool?
This is not a blocker for RC2. Only need to finish the update before 1.7.0 GA. Thank you.

**Comment by derekbit** [comment]
Also update environment_check.sh. The script will download and execute `longhornctl` command instead.

**Comment by derekbit** [comment]
@mantissahz Any obstacle? Will it be ready before RC3?

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (website `030930`)

Following instructions in below page to perform command `longhornctl check preflight`, `longhornctl check preflight --enable-spdk` and `longhornctl install preflight`did not encounter any problems.
- https://longhorn.io/docs/1.7.0/deploy/install/#using-the-longhorn-command-line-tool
- https://longhorn.io/docs/1.7.0/v2-data-engine/quick-start/#using-the-longhorn-command-line-tool
