### ISSUE TITLE
[BUG] Test case test_rwx_delete_share_manager_pod fails after changes for RWX HA.

### ISSUE THREAD

**Issue by james-munson** [longhorn/longhorn#9081]
## Describe the bug

Regression run of `test_rwx_delete_share_manager_pod` fails after changes for #6205, even with `rwx-volume-fast-failover` turned off.

## To Reproduce

Nightly run https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/985/ failed that test, and it has failed on private runs as well.

## Expected behavior

Test should pass.

## Environment

 - Longhorn version: 1.7.0 RC and 1.8.0-dev

Environment is as created by the test.

 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by james-munson** [comment]
In my run, the error output was
```
        pod_name = statefulset_name + '-' + '0'
        pvc_name = \
            statefulset['spec']['volumeClaimTemplates'][0]['metadata']['name'] \
            + '-' + statefulset_name + '-0'
        pv_name = get_volume_name(core_api, pvc_name)
        share_manager_name = 'share-manager-' + pv_name
    
        test_data = generate_random_data(VOLUME_RWTEST_SIZE)
        write_pod_volume_data(core_api, pod_name, test_data, filename='test1')
    
        delete_and_wait_pod(core_api, share_manager_name,
                            namespace=LONGHORN_NAMESPACE)
    
        target_pod = core_api.read_namespaced_pod(name=pod_name,
                                                  namespace='default')
>       wait_delete_pod(core_api, target_pod.metadata.uid)

test_rwx.py:387: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

api = <kubernetes.client.api.core_v1_api.CoreV1Api object at 0x7f73f345bd90>
pod_uid = 'ee68ab7b-335d-4334-98ac-8229f2c17727', namespace = 'default'

    def wait_delete_pod(api, pod_uid, namespace='default'):
        for i in range(POD_DELETION_TIMEOUT):
            ret = api.list_namespaced_pod(namespace=namespace)
            found = False
            for item in ret.items:
                if item.metadata.uid == pod_uid:
                    found = True
                    break
            if not found:
                break
            time.sleep(DEFAULT_POD_INTERVAL)
>       assert not found
E       AssertionError

common.py:986: AssertionError
```
Note that it is not the share-manager pod whose restart is being looked for; it is the workload pod.  The test expects a workload restart, which is not happening.

**Comment by james-munson** [comment]
This issue has already been noted and a proposed test change in https://github.com/longhorn/longhorn-tests/pull/2008

**Comment by james-munson** [comment]
Closing this issue, since the failure has been dealt with.

**Comment by derekbit** [comment]
It is behavior change. @james-munson Can you explain in https://longhorn.io/docs/1.7.0/nodes-and-volumes/volumes/rwx-volumes/ as well as https://longhorn.io/docs/1.7.0/deploy/important-notes/? Thank you.

**Comment by innobead** [comment]
added `behavior change` label.

**Comment by ejweber** [comment]
This behavioral change seems unintended. We have been discussing it in relation with https://github.com/longhorn/longhorn-manager/pull/2811#issuecomment-2244142848.

In the current implementation with the swapped functions, the share manager never reaches an error state when its pod is deleted.

```
eweber@laptop:~/longhorn-manager> kl get sharemanager -w --output-watch-events | TZ=UTC0 ts '[%Y-%m-%dT%H:%M:%SZ]'
[2024-07-25T15:48:17Z] EVENT      NAME                                       STATE     NODE                                AGE
[2024-07-25T15:48:17Z] ADDED      pvc-781870d7-26e5-4a11-907a-f51d12acb2e8   running   eweber-v126-worker-9c1451b4-kgxdq   18h
[2024-07-25T15:48:36Z] MODIFIED   pvc-781870d7-26e5-4a11-907a-f51d12acb2e8   starting   eweber-v126-worker-9c1451b4-kgxdq   18h
[2024-07-25T15:48:43Z] MODIFIED   pvc-781870d7-26e5-4a11-907a-f51d12acb2e8   running    eweber-v126-worker-9c1451b4-kgxdq   18h
```

Without the error state, the volume controller cannot request remount.

https://github.com/longhorn/longhorn-manager/blob/7e0957a220c4718c3280ac3ee67dd22a9a8dcd1b/controller/volume_controller.go#L4503-L4510

This is happening because `syncShareManagerPod` sets the state to error, but `syncShareManagerVolume` immediately reverses it.

```
[longhorn-manager-lndt9 longhorn-manager] time="2024-07-25T15:48:36Z" level=warning msg="-----> In syncShareManager with state running" func="controller.(*ShareManagerController).syncShareManager" file="share_manager_controller.go:333" controller=longhorn-share-manager node=eweber-v126-worker-9c1451b4-kgxdq owner=eweber-v126-worker-9c1451b4-kgxdq shareManager=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8 state=running volume=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8
[longhorn-manager-lndt9 longhorn-manager] time="2024-07-25T15:48:36Z" level=info msg="Updating share manager to error state, requires cleanup with remount" func="controller.(*ShareManagerController).syncShareManagerPod" file="share_manager_controller.go:894" controller=longhorn-share-manager node=eweber-v126-worker-9c1451b4-kgxdq owner=eweber-v126-worker-9c1451b4-kgxdq shareManager=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8 state=running volume=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8
[longhorn-manager-lndt9 longhorn-manager] time="2024-07-25T15:48:36Z" level=warning msg="-----> ShareManager state change from running to error" func="controller.(*ShareManagerController).syncShareManagerPod" file="share_manager_controller.go:895" controller=longhorn-share-manager node=eweber-v126-worker-9c1451b4-kgxdq owner=eweber-v126-worker-9c1451b4-kgxdq shareManager=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8 state=running volume=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8
[longhorn-manager-lndt9 longhorn-manager] time="2024-07-25T15:48:36Z" level=info msg="Deleting share manager pod" func="controller.(*ShareManagerController).cleanupShareManagerPod" file="share_manager_controller.go:781" controller=longhorn-share-manager node=eweber-v126-worker-9c1451b4-kgxdq owner=eweber-v126-worker-9c1451b4-kgxdq shareManager=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8 state=error volume=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8
[longhorn-manager-lndt9 longhorn-manager] time="2024-07-25T15:48:36Z" level=info msg="Starting share manager" func="controller.(*ShareManagerController).syncShareManagerVolume" file="share_manager_controller.go:688" controller=longhorn-share-manager node=eweber-v126-worker-9c1451b4-kgxdq owner=eweber-v126-worker-9c1451b4-kgxdq shareManager=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8 state=error volume=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8
[longhorn-manager-lndt9 longhorn-manager] time="2024-07-25T15:48:36Z" level=warning msg="-----> ShareManager state change from error to starting" func="controller.(*ShareManagerController).syncShareManagerVolume" file="share_manager_controller.go:689" controller=longhorn-share-manager node=eweber-v126-worker-9c1451b4-kgxdq owner=eweber-v126-worker-9c1451b4-kgxdq shareManager=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8 state=error volume=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8
```

I tested the behavior with the functions switched back, and it reverts to what was previously expected. IMO we still need to determine if we can/should switch the order back before closing this one.

**Comment by james-munson** [comment]
It is worth mentioning, however, that the reason for the restart is not well documented and it doesn't seem to be needed.  The workloads do not hang after pod recreation, and I/O continues after the grace period.  If we do resolve the sequence issue, I would argue that we should eliminate the forced restart anyway.

**Comment by PhanLe1010** [comment]
I agree that we should keep the previous behavior. This PR maintains the previous behavior while still achieving the fast failover goal https://github.com/longhorn/longhorn-manager/pull/3008

**Comment by derekbit** [comment]
@james-munson don't forget to update the status of the issue. Thanks.

**Comment by james-munson** [comment]
Phan's PR makes the share-manager sync sequence step through the state that will cause workload to restart, so the test can go back to how it was for the moment.

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-manager 76191be) and v1.7.x-head (longhorn-manager 654b411). Test case `test_rwx_delete_share_manager_pod` passed.
