### ISSUE TITLE
[BUG] Share manager controller reconciles tens of thousands of times

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#9086]
## Describe the bug

While a share manager pod is starting, the share manager controller reconciles tens of thousands of times. There is no particular bad effect, other than potentially wasted CPU, etc.

As far as I can tell, this has been silently happening since the share manager controller was originally introduced, but I only noticed it when augmenting the share manager with logging to investigate issues related to https://github.com/longhorn/longhorn/issues/9081.

## To Reproduce

1. Add logging to the share manager controller so that we know every time it reconciles.
2. Delete a share manager pod for a running RWX volume.
3. Observe tens of thousands of logs.

## Expected behavior

It's reasonable to expect dozens of reconciliations after a share manager pod deletion, since it will reconcile every time the state of the old and new pods change. However, tens of thousands of times is excessive.

## Additional context

It happens because we manually enqueue the share manager while waiting for the share manager pod's containers to become ready. There is nothing to slow us down, so we enqueue tens of thousands of times in the few seconds this takes.

https://github.com/longhorn/longhorn-manager/blob/7e0957a220c4718c3280ac3ee67dd22a9a8dcd1b/controller/share_manager_controller.go#L912-L913

Example log output from a modified longhorn-manager image:

```
...
[longhorn-manager-lndt9 longhorn-manager] time="2024-07-25T15:48:43Z" level=warning msg="-----> In syncShareManager with state starting" func="controller.(*ShareManagerController).syncShareManager" file="share_manager_controller.go:333" controller=longhorn-share-manager node=eweber-v126-worker-9c1451b4-kgxdq owner=eweber-v126-worker-9c1451b4-kgxdq shareManager=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8 state=starting volume=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8
[longhorn-manager-lndt9 longhorn-manager] time="2024-07-25T15:48:43Z" level=warning msg="-----> In syncShareManager with state starting" func="controller.(*ShareManagerController).syncShareManager" file="share_manager_controller.go:333" controller=longhorn-share-manager node=eweber-v126-worker-9c1451b4-kgxdq owner=eweber-v126-worker-9c1451b4-kgxdq shareManager=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8 state=starting volume=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8
[longhorn-manager-lndt9 longhorn-manager] time="2024-07-25T15:48:43Z" level=warning msg="-----> In syncShareManager with state starting" func="controller.(*ShareManagerController).syncShareManager" file="share_manager_controller.go:333" controller=longhorn-share-manager node=eweber-v126-worker-9c1451b4-kgxdq owner=eweber-v126-worker-9c1451b4-kgxdq shareManager=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8 state=starting volume=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8
[longhorn-manager-lndt9 longhorn-manager] time="2024-07-25T15:48:43Z" level=warning msg="-----> In syncShareManager with state starting" func="controller.(*ShareManagerController).syncShareManager" file="share_manager_controller.go:333" controller=longhorn-share-manager node=eweber-v126-worker-9c1451b4-kgxdq owner=eweber-v126-worker-9c1451b4-kgxdq shareManager=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8 state=starting volume=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8
[longhorn-manager-lndt9 longhorn-manager] time="2024-07-25T15:48:43Z" level=warning msg="-----> In syncShareManager with state starting" func="controller.(*ShareManagerController).syncShareManager" file="share_manager_controller.go:333" controller=longhorn-share-manager node=eweber-v126-worker-9c1451b4-kgxdq owner=eweber-v126-worker-9c1451b4-kgxdq shareManager=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8 state=starting volume=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8
[longhorn-manager-lndt9 longhorn-manager] time="2024-07-25T15:48:43Z" level=warning msg="-----> In syncShareManager with state starting" func="controller.(*ShareManagerController).syncShareManager" file="share_manager_controller.go:333" controller=longhorn-share-manager node=eweber-v126-worker-9c1451b4-kgxdq owner=eweber-v126-worker-9c1451b4-kgxdq shareManager=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8 state=starting volume=pvc-781870d7-26e5-4a11-907a-f51d12acb2e8
...
# ~27000 lines
```

**Comment by ejweber** [comment]
Please check the competing PRs when you get a chance @james-munson and @PhanLe1010. I prefer https://github.com/longhorn/longhorn-manager/pull/3009, but am open to either approach.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240728**
- longhorn `master-head` https://github.com/longhorn/longhorn/commit/d5e8a44104f5e03c310870b47da7c8ab55f671b3
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/a05002c662885d0b8381b219593fdb2083c0232d

**Verified on v1.7.x-head 20240728**
- longhorn `v1.7.x-head` https://github.com/longhorn/longhorn/commit/a94f6fe44b923d07475f87d8e80bc3981c709b06
- longhorn-manager `v1.7.x-head` https://github.com/longhorn/longhorn-manager/commit/3dc6ecc0941dd7df0d027d3c65ce2d798b1af90f

**The test steps**
https://github.com/longhorn/longhorn/issues/9086#issuecomment-2251481249

**Result Passed**

The regression RWX test passed:

- [x] `master-head` : https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/989/testReport/tests/test_rwx/

- [x] `v1.7.x-head` : https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-tests-sles-amd64/15/testReport/tests/test_rwx/
