### ISSUE TITLE
[IMPROVEMENT] Remove Offline Rebuilding from UI on master and v1.7.0

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#9090]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

V2 volume online replica ebuilding will intoduce on v1.7.0, maybe offline replica rebuilding information can removed form UI to avoid furthur questions

---

When perform V2 volume online replica rebuilding:
![image](https://github.com/user-attachments/assets/c35b2d2a-f87f-4ed4-b573-6ee1ac36d9ba)

Setting page:
![image](https://github.com/user-attachments/assets/b32f46bd-a8c0-479e-8a9e-243c50d51cd0)

## Describe the solution you'd like

Suggest remove those information

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by derekbit** [comment]
@a110605 Can you help remove it? The offline rebuilding is removed in v1.7.0. 
Thanks.

**Comment by a110605** [comment]
Hi @derekbit , the v2 `offline replica rebuilding` setting is given by `/v1/settings` API. 
We can remove this setting from backend.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn v1.7.x(longhorn-ui `9332ed`) and longhorn master(longhorn-ui `ed85b7`) 

Offline Rebuilding information removed when V2 volume is rebuilding and can not see in setting page.
