### ISSUE TITLE
[BUG] Remove unnecessary restart of RWX workload.

### ISSUE THREAD

**Issue by james-munson** [longhorn/longhorn#9095]
## Describe the bug

In volume_controller, this code uses share-manager state `Error` as a signal to do a blanket restart of the RWX volume's workload:
https://github.com/longhorn/longhorn-manager/blob/e1b006fd4c203a12dc24c3ef5f3f27543fa31e7b/controller/volume_controller.go#L4524C2-L4531C3

There is no comment or blame indication to say why it is necessary, and testing in the RWX fast-failover feature indicated that it is not.  Up until @PhanLe1010 correction of the state sequence in https://github.com/longhorn/longhorn-manager/pull/3008, RWX fast failover was bypassing the state altogether by syncing the pod first, and then the volume in share_manager_controller.  Even so, without the restart, workload pods reconnected and resumed I/O after the replacement pod was created.  That was observed with NFS client mount options of "soft", "softerr", and "hard".

## To Reproduce

Make an RWX volume for a deployment workload and drive I/O to it.  Fail the node that owns the share-manager and share-manager pod.  See that after the pod is recreated and the NFS client grace period elapses, the deployment pods are not restarted, except for the one that is on the failed node.

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
If the share-manager does not recover and remains in the Error state for an extended period, is it required to request a remount before deleting the workload?

**Comment by james-munson** [comment]
See also #2096

**Comment by james-munson** [comment]
If it is an issue for any given customer, one approach is just to recommend setting `auto-delete-pod-when-volume-detached-unexpectedly` to false.  
What else would that have an impact on?  Well, besides here, in the remount requested path: https://github.com/longhorn/longhorn-manager/blob/d4ab0495f8572be2940f64a0b34099aab91b4ce3/controller/kubernetes_pod_controller.go#L455-L467
starting in 1.7.0, there is another path used by RWX storage network feature:  https://github.com/longhorn/longhorn-manager/blob/d4ab0495f8572be2940f64a0b34099aab91b4ce3/controller/kubernetes_pod_controller.go#L202-L238

**Comment by james-munson** [comment]
After discussion with @ejweber, @PhanLe1010, and @shuo-wu, the consensus was that we don't want to make a recommendation for how to set `auto-delete-pod-when-volume-detached-unexpectedly` just to control how RWX volumes behave.  Nor do we want to just remove the remount code from volume_controller, because it may be necessary in some situations.

Rather, we should refine the check that already exists in kubernetes_pod_controller, and skip the workload restart if 
- `auto-delete-pod-when-volume-detached-unexpectedly` is false, OR
- if the volume that has requested remount is RWX and `rwx-volume-fast-failover` is true and `storage-network-for-rwx-volume-enabled` is set to false.

**Comment by PhanLe1010** [comment]
> Rather, we should refine the check that already exists in kubernetes_pod_controller, and skip the workload restart if 
> - `auto-delete-pod-when-volume-detached-unexpectedly` is false, OR
> - if the volume that has requested remount is RWX and `rwx-volume-fast-failover` is true and `storage-network-for-rwx-volume-enabled` is set to false.

WDYT about this slightly different alternative?

> Rather, we should refine the check that already exists in kubernetes_pod_controller, and skip the workload restart if 
> - `auto-delete-pod-when-volume-detached-unexpectedly` is false, OR
> - if the volume that has requested remount is RWX and `storage-network-for-rwx-volume-enabled` is set to false.

**Comment by james-munson** [comment]
> if the volume that has requested remount is RWX and storage-network-for-rwx-volume-enabled is set to false.
So, regardless of the RWX fast-failover setting.  Works for me.  It is critical for fast failover, but reasonable to do even without it.

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-manager 8bc7575). Test case `test_rwx_delete_share_manager_pod` passed: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7626/
