### ISSUE TITLE
[DOC] Last-ditch uninstall cleanup instructions are out of date.

### ISSUE THREAD

**Issue by james-munson** [longhorn/longhorn#9116]
## What's the document you plan to update? Why? Please describe

https://longhorn.io/docs/1.7.0/deploy/uninstall/#problems-with-crds

## Additional context

The namespace scope and finalizer `longhorn.rancher.io` in the script are out of date:
```shell
# Delete CRD finalizers, instances and definitions
for crd in $(kubectl get crd -o jsonpath={.items[*].metadata.name} | tr ' ' '\n' | grep longhorn.rancher.io); do
  kubectl -n ${NAMESPACE} get $crd -o yaml | sed "s/\- longhorn.rancher.io//g" | kubectl apply -f -
  kubectl -n ${NAMESPACE} delete $crd --all
  kubectl delete crd/$crd
done
```
Further, some CRDs will not respond or deletion will hang.

**Comment by james-munson** [comment]
Added a further tip: https://github.com/longhorn/website/pull/964

**Comment by innobead** [comment]
Closing, as this is just doc update only.
