### ISSUE TITLE
No volumes listed since the update to 0.7.0

### ISSUE THREAD

**Issue by JRial95** [longhorn/longhorn#912]
Since I updated longhorn from Rancher UI from version 0.6.2 to 0.7.0, no more volumes are listed in Longhorn.

On the other hand, there are still the `instance-manager-r-***` and `instance-manager-e-***` pods of version 0.6.2 (in addition to those of version 0.7.0).

How to import volumes from the previous version? Have I forgotten a step for the update?

**Comment by shuo-wu** [comment]
We update our API group version from `alpha` to `beta`, but we also have an upgrader to migrate all Longhorn related resources automatically during the upgrade. Can you check if those Longhorn volumes are migrated to the new version via the command:
```
kubectl -n longhorn-system get volumes.longhorn.io
``` 

You can also check if the old Longhorn volumes are still there:
```
kubectl -n longhorn-system get volumes.longhorn.rancher.io
```

**Comment by JRial95** [comment]
Volumes do not seem to have been migrated.

First command returns:
```
No resources found.
```

Second command returns:
```
pvc-10912e5b-a2ea-11e9-a3b6-e41f13804639   138d
pvc-1174f0ef-a2ea-11e9-a3b6-e41f13804639   138d
pvc-14fe5f5b-c298-11e9-a3b6-e41f13804639   98d
pvc-2eb7abc4-9c11-11e9-a3b6-e41f13804639   147d
pvc-7f5bf0a9-9e39-11e9-a3b6-e41f13804639   144d
pvc-a79597712b8911e9                       290d
pvc-a8be48c52b8911e9                       290d
pvc-eeb881dd-9c08-11e9-a3b6-e41f13804639   147d
```

How to manually execute the upgrader?

**Comment by yasker** [comment]
@JRial95 The upgrader should run automatically. Can you take a look at manager logs to see if you can see things related to the `Upgrade` at the beginning of the log?

**Comment by JRial95** [comment]
The `longhorn-manager` has nothing specific to the update in its logs. However, they contain these warnings:
```
time="2019-11-26T08:16:00Z" level=warning msg="Can't find instance manager for pod instance-manager-r-*, may be deleted"
time="2019-11-26T08:16:00Z" level=warning msg="Can't find instance manager for pod instance-manager-e-*, may be deleted"
```

During the update, I had the following problem:
```
Error starting manager: settings.longhorn.io \"crd-api-version\" is forbidden: User \"system:serviceaccount:longhorn-system:longhorn-service-account\" cannot get resource \"settings\" in API group
```

I solved it by manually updating the `ClusterRole` according to this file: [longhorn/deploy/longhorn.yaml](https://github.com/longhorn/longhorn/blob/master/deploy/longhorn.yaml).

**Comment by yasker** [comment]
@JRial95 `crd-api-version` is the field used for upgrade, so unable to access it is the reason the upgrade process wasn't started. There is something wrong with your upgrade since Helm should update the permission for `settings.longhorn.io` (and other CRDs).

I am not sure what went wrong in the upgrade stopped the right RBAC to be deployed, but maybe worth a double-check.

After you update the `ClusterRole`, you can delete all Longhorn Manager pods (not the daemonset) and they should be recreated and the upgrade process should be triggered.

Let me know if you figured out what's happened to the RBAC rules.

**Comment by JRial95** [comment]
I deleted all `longhorn-manager` pods but nothing new happened. There are always these warnings:
```
time="2019-11-26T08:16:00Z" level=warning msg="Can't find instance manager for pod instance-manager-r-*, may be deleted"
time="2019-11-26T08:16:00Z" level=warning msg="Can't find instance manager for pod instance-manager-e-*, may be deleted"
```

Here are the messages displayed when the pod is launched:
```
time="2019-11-26T18:10:39Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"k8s\", UID:\"8167be7c-e1b9-4a56-9155-8a5f0ca2f38d\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"106531828\", FieldPath:\"\"}): type: 'Normal' reason: 'Ready' Node k8s is ready"
time="2019-11-26T18:10:39Z" level=debug msg="Requeue longhorn-system/k8s due to conflict: Operation cannot be fulfilled on nodes.longhorn.io \"k8s\": the object has been modified; please apply your changes to the latest version and try again"
time="2019-11-26T18:10:40Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"kubernode4\", UID:\"014a7520-a177-48d3-850a-4bfc3493cdee\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"106531801\", FieldPath:\"\"}): type: 'Normal' reason: 'Ready' Node kubernode4 is ready"
time="2019-11-26T18:10:40Z" level=debug msg="Requeue longhorn-system/kubernode4 due to conflict: Operation cannot be fulfilled on nodes.longhorn.io \"kubernode4\": the object has been modified; please apply your changes to the latest version and try again"
time="2019-11-26T18:10:41Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"kubernode3\", UID:\"2db0e3f7-4d00-4ce3-8d9c-1d0ab37edf85\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"106531867\", FieldPath:\"\"}): type: 'Normal' reason: 'Ready' Node kubernode3 is ready"
time="2019-11-26T18:10:41Z" level=debug msg="Requeue longhorn-system/kubernode3 due to conflict: Operation cannot be fulfilled on nodes.longhorn.io \"kubernode3\": the object has been modified; please apply your changes to the latest version and try again"
```

**NOTE:** After the update, the `longhorn-engine` version 0.6.2 was not recognized by Longhorn. So I tried to create a new one (also version 0.6.2) from the Longhorn GUI hoping that the volumes would be bound to the new engine. Unfortunately, it didn't work, so I deleted the engine (also from the Longhorn GUI) but it also deleted the engine that worked with the old Longhorn version. Have I lost my data?

**Comment by yasker** [comment]
@JRial95 I don't think you lost your data since according to your description, Longhorn v0.7.0 hasn't recognized the old volume yet.

That error information shouldn't cause any trouble. 

To check if old CRDs are still there, run
```
kubectl -n longhorn-system get volumes.longhorn.rancher.io
```

You should see if the old CRDs are still there.

And
```
kubectl -n longhorn-system get replicas.longhorn.rancher.io
```
Should give you the location of your replica data in the field at `NodeID` with `DiskPath`.

We can try the upgrade process again once you verified your v0.6.2 CRDs are intact.
1. Remove the manager daemonset 
```
kubectl delete -f https://raw.githubusercontent.com/longhorn/longhorn-manager/master/deploy/install/02-components/01-manager.yaml
```
2. Clear the setting to retrigger the upgrade process
```
kubectl -n longhorn-system delete settings.longhorn.io crd-api-version
```
3. Re-create the manager daemonset
```
kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn-manager/master/deploy/install/02-components/01-manager.yaml
```

Monitor the log, it should say something like `Upgrade from v1alpha1`

**Comment by JRial95** [comment]
I checked and my old CRDs are still there.

I followed your steps but the logs say that an update is not needed:
```
time="2019-11-26T20:11:10Z" level=info msg="Start overwriting built-in settings with customized values"
time="2019-11-26T20:11:10Z" level=info msg="New upgrade leader elected: kubernode1"
time="2019-11-26T20:11:36Z" level=info msg="Start the upgrade process"
time="2019-11-26T20:11:36Z" level=info msg="No upgrade is needed"
time="2019-11-26T20:11:36Z" level=info msg="Upgrade completed"
```

Unfortunately, it didn't work and the logs still display these messages:
```
time="2019-11-26T20:11:36Z" level=warning msg="Can't find instance manager for pod instance-manager-e-***, may be deleted"
time="2019-11-26T20:11:36Z" level=warning msg="Can't find instance manager for pod instance-manager-r-***, may be deleted"
```

**Comment by yasker** [comment]
Those logs are fine.

How many nodes/managers are there? Can you check the log of all of them?

The following command should at least retriggered the upgrade process in one of them.
```
kubectl -n longhorn-system delete settings.longhorn.io crd-api-version
```

**Comment by JRial95** [comment]
I restarted the update again with the steps you described and found in the logs this warning:
```
level=warning msg="Cannot verify current CRD version, assume it's not v1alpha1: unable to verify if version matches v1alpha1: settings.longhorn.rancher.io \"default-engine-image\" is forbidden: User \"system:serviceaccount:longhorn-system:longhorn-service-account\" cannot get resource \"settings\" in API group \"longhorn.rancher.io\" in the namespace \"longhorn-system\""
```

So I certainly didn't copy the whole `ClusterRole` configuration when I did the update manually 🤦‍♂

After correctly applying the `ClusterRole` configuration, the update was successfully completed.

@yasker Thank you for your help.

**Comment by ColonelBundy** [comment]
@yasker I have the same issues except neither my new or old crd's are there and I ran into an issue before hand where I had to run this: https://github.com/longhorn/longhorn/blob/master/docs/upgrade-from-v0.6.2-to-v0.7.0.md#error-kind-customresourcedefinition-with-the-name-xxx-already-exists-in-the-cluster-and-wasnt-defined-in-the-previous-release

My volumes and pvc's still exist and they have the new "volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io" but I cannot see them in the UI and I get this when trying to restart one of my containers:
> AttachVolume.Attach failed for volume "pvc-f522a0b9-b919-11e9-ac62-005056ac7a40" : rpc error: code = NotFound desc = ControllerPublishVolume: the volume pvc-f522a0b9-b919-11e9-ac62-005056ac7a40 not exists

That claim exists though

**Comment by yasker** [comment]
@ColonelBundy You cannot find old CRDs according to https://github.com/longhorn/longhorn/issues/912#issuecomment-558782473 ? That's weird. Those must be removed manually using the steps in https://github.com/longhorn/longhorn/blob/master/docs/upgrade-from-v0.6.2-to-v0.7.0.md#post-upgrade

**Comment by ColonelBundy** [comment]
@yasker I figured out i accidently removed the old crd's so I ran restore of my nodes and redid the upgrade and it worked.
