### ISSUE TITLE
[BUG] Detaching a degraded v2 volume results in replica failure

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#9122]
## Describe the bug

Detach a drgraded v2 volume then attacth the v2 volume again, results in the replica fail, volume remain degraded and orphan replicas are created over time.

volume
```bash
> kl get volume -w
NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE            AGE
pvc-725e4765-9590-4c78-a594-f5fce4f12020   v2            attached   degraded                 2147483648   ip-10-0-1-143   15m
```

orphan replicas created over time
```bash
> kl get  orphans.longhorn.io -o yaml | grep DataName
      DataName: pvc-725e4765-9590-4c78-a594-f5fce4f12020-r-0b5bb6c9-rebuilding
      DataName: pvc-725e4765-9590-4c78-a594-f5fce4f12020-r-c87bbc5f-rebuilding
      DataName: pvc-725e4765-9590-4c78-a594-f5fce4f12020-r-8489c342-rebuilding
      DataName: pvc-725e4765-9590-4c78-a594-f5fce4f12020-r-c2b0b184-rebuilding
      DataName: pvc-725e4765-9590-4c78-a594-f5fce4f12020-r-e7926857-rebuilding
      DataName: pvc-725e4765-9590-4c78-a594-f5fce4f12020-r-88d25d2c-rebuilding
      DataName: pvc-725e4765-9590-4c78-a594-f5fce4f12020-r-ec5474a9-rebuilding
      DataName: pvc-725e4765-9590-4c78-a594-f5fce4f12020-r-21390d70-rebuilding
      DataName: pvc-725e4765-9590-4c78-a594-f5fce4f12020-r-064c8807-rebuilding
      DataName: pvc-725e4765-9590-4c78-a594-f5fce4f12020-r-a311dd1a-rebuilding
      DataName: pvc-725e4765-9590-4c78-a594-f5fce4f12020-r-b6152cca-rebuilding
      DataName: pvc-725e4765-9590-4c78-a594-f5fce4f12020-r-fc1628c9-rebuilding
      DataName: pvc-725e4765-9590-4c78-a594-f5fce4f12020-r-4b055e44-rebuilding
      DataName: pvc-725e4765-9590-4c78-a594-f5fce4f12020-r-e9a7fe62-rebuilding
```

## To Reproduce

1. Create a 2 Gi V2 volume with workload, write 1 Gi data into mount point
2. Delete 1 replica
3. When new replica created(From UI, the replica running, but not healthy), detach the volume.
4. Wait volume detached
5. Attach the volume again
6. Volume remains in degraded state, the replica loops through the cycle of create -> failed state -> deleted, orphan replicas created over time.

## Expected behavior

Have a note to record the behavior or volume healthy after step 5

## Support bundle for troubleshooting

[supportbundle_9d5ea3bf-c7ee-4fcb-995e-2c988604c7f0_2024-07-30T06-49-53Z.zip](https://github.com/user-attachments/files/16423352/supportbundle_9d5ea3bf-c7ee-4fcb-995e-2c988604c7f0_2024-07-30T06-49-53Z.zip)

## Environment

 - Longhorn version: v1.7.x
 - Impacted volume (PV): pvc-725e4765-9590-4c78-a594-f5fce4f12020
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1
 - Node config
   - OS type and version: SLES 15-SP6
   - Kernel version: 6.4.0-150600.23.7-default

## Additional context

N/A

**Comment by derekbit** [comment]
Falling into the failed cleanup loop
```
2024-07-30T06:49:54.864516803Z [longhorn-instance-manager] time="2024-07-30T06:49:54Z" level=error msg="Failed to disconnect the external src snapshot bdev pvc-725e4765-9590-4c78-a594-f5fce4f12020-r-cc56ef03-snap-rebuild-ae55d7a0n1 for rebuilding dst cleanup, will continue" func="spdk.(*Replica).doCleanupForRebuildingDst" file="replica.go:1547" error="error sending message, id 17904, method bdev_nvme_detach_controller, params {pvc-725e4765-9590-4c78-a594-f5fce4f12020-r-cc56ef03-snap-rebuild-ae55d7a0 {    }  }: {\"code\": -110,\"message\": \"Connection timed out\"}" lvsName=disk-3 lvsUUID=19cf1f92-1079-46fe-883f-eec7f5cebb6e 
```

cc @shuo-wu

**Comment by shuo-wu** [comment]
All replicas has mismatching actual size hence the engine cannot work correctly as well:
```
2024-07-30T06:49:59.661650656Z [longhorn-instance-manager] time="2024-07-30T06:49:59Z" level=warning msg="Found mismatching lvol actual size 1157627904 with recorded prev lvol actual size 0 when validating lvol pvc-725e4765-9590-4c78-a594-f5fce4f12020-r-e6d71412-snap-rebuild-ae55d7a0" func=spdk.compareSvcLvols file="replica.go:405"
```

In other words, this issue is caused by [the actual size bug after purge](https://github.com/longhorn/longhorn/issues/7199#issuecomment-2252306057). And the fix is already in https://github.com/longhorn/longhorn-spdk-engine/pull/190

**Comment by shuo-wu** [comment]
@chriscchien, Would you try to re-test the issue by using this instance manager image `shuowu/longhorn-instance-manager:v6_20240730`? With this image containing the fix, I cannot reproduce it anymore.

**Comment by chriscchien** [comment]
Hi @shuo-wu, yes this issue can not be reproduced on image `shuowu/longhorn-instance-manager:v6_20240730`, after voume reattached, the replica rebuild success, volume become healthy and can read/write without any problems.

I would like to test again on v1.7.x after https://github.com/longhorn/longhorn-spdk-engine/pull/190 merged, thank you.

**Comment by derekbit** [comment]
Duplicate https://github.com/longhorn/longhorn/issues/7199#issuecomment-2252306057

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-instance-manager `3f53e2`), longhorn v1.7.x(longhorn-inatance-manager `b27902`) and longhorn-spdk-engine main `19f91e` with test [steps](https://github.com/longhorn/longhorn/issues/9122#issue-2437068127)
