### ISSUE TITLE
[BUG]csi-resizer： Error syncing PVC and failed to resize volume

### ISSUE THREAD

**Issue by jeven2016** [longhorn/longhorn#9125]
## Describe the bug
the  csi-resizer failed to resize volume while I try to create a vm with longhorn through Kubevirt, :

I0726 03:18:14.438232       1 event.go:376] "Event occurred" object="zfcloud-vm-system/tmp-pvc-a3e358c5-844b-441a-87eb-e5229567eea2" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Warning" reason="VolumeResizeFailed" message="resize volume \"pvc-c14fb749-8bb9-497b-a55e-d8f7ab370d2d\" by resizer \"driver.longhorn.io\" failed: rpc error: code = DeadlineExceeded desc = volume pvc-c14fb749-8bb9-497b-a55e-d8f7ab370d2d expansion from existing capacity 26000490496 to requested capacity 27917287424 failed"
E0725 04:32:12.559175       1 leaderelection.go:336] error initially creating leader election record: leases.coordination.k8s.io "external-resizer-driver-longhorn-io" already exists
I0726 03:18:14.520492       1 event.go:376] "Event occurred" object="zfcloud-vm-system/tmp-pvc-a3e358c5-844b-441a-87eb-e5229567eea2" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="Resizing" message="External resizer is resizing volume pvc-c14fb749-8bb9-497b-a55e-d8f7ab370d2d"
E0726 03:19:44.526485       1 controller.go:274] "Error syncing PVC" err="resize volume \"pvc-c14fb749-8bb9-497b-a55e-d8f7ab370d2d\" by resizer \"driver.longhorn.io\" failed: rpc error: code = DeadlineExceeded desc = volume pvc-c14fb749-8bb9-497b-a55e-d8f7ab370d2d expansion from existing capacity 27917287424 to requested capacity 27917287424 failed"

E0731 00:26:21.910061       1 controller.go:274] "Error syncing PVC" err="resize volume \"pvc-fa203b22-4252-490c-a772-355cb254403b\" by resizer \"driver.longhorn.io\" failed: rpc error: code = FailedPrecondition desc = volume pvc-fa203b22-4252-490c-a772-355cb254403b invalid state attaching for controller volume expansion"
I0731 00:26:21.910109       1 event.go:376] "Event occurred" object="zfcloud-vm-system/tmp-pvc-f4f76464-7723-48de-b3d8-d374527fa6bb" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Warning" reason="VolumeResizeFailed" message="resize volume \"pvc-fa203b22-4252-490c-a772-355cb254403b\" by resizer \"driver.longhorn.io\" failed: rpc error: code = FailedPrecondition desc = volume pvc-fa203b22-4252-490c-a772-355cb254403b invalid state attaching for controller volume expansion"

Does anyone know how to solve it ? thanks.

## To Reproduce

1. create a vm using kubevirt and configure the dataVolumeTemplates part with a volumeSnapshot, and the ExpandDisk feature is enabled for kubevirt  
2. kubevirt will create corresponding pvc by the volumesnapshot  
3. csi-resizer will print the errors above  for multiple times 

## Expected behavior

No errors occurred during volume resizing
 
## Support bundle for troubleshooting
the yaml file of kubevirt vm I'd like to apply: 

apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: win7
  name: win7
  namespace: vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: win7
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - disk:
              bus: virtio
            name: win7-disk1
          interfaces:
          - masquerade: {}
            model: e1000 
            name: default
        resources:
          requests:
            memory: 8Gi
      networks:
      - name: default
        pod: {}            
      volumes:
      - dataVolume:
          name: win7-dv
        name: win7-disk1
  dataVolumeTemplates:
  - metadata:
      name: win7-dv
    spec:
      pvc:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: longhorn
      source:
        snapshot:
          name: win7-template-snapshot  # 您之前创建的快照名称
          namespace: vm  # 快照所在的命名空间

## Environment
Kernel: 5.14
longhorn: 1.6.2
docker: 24.0.9
kubevirt: v1.2.2
kubevirt CDI:  v1.59.0

**Comment by morganchenjp** [comment]
Just had similar issue, so thumb_up and subscribe the notification. 
thanks.

**Comment by derekbit** [comment]
cc @ChanYiLin

**Comment by AbhishekKandoi314e** [comment]
Hi, I'm also encountering this issue. When I attempt to perform a live expansion of a PVC, it sometimes succeeds without any problems, but other times it gets stuck retrying with the following error:

```
I0804 06:48:02.060948       1 event.go:389] "Event occurred" object="<>" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="Resizing" message="External resizer is resizing volume pvc-507eaa3b-ab42-433e-a69b-fd9e23341753"
E0804 06:49:32.174394       1 controller.go:316] "Error syncing PVC" err="resize volume \"pvc-507eaa3b-ab42-433e-a69b-fd9e23341753\" by resizer \"driver.longhorn.io\" failed: rpc error: code = DeadlineExceeded desc = volume pvc-507eaa3b-ab42-433e-a69b-fd9e23341753 expansion from existing capacity 64424509440 to requested capacity 161061273600 failed"
```

I’ve confirmed that there is sufficient available capacity. As a workaround, I’ve found that scaling down the pod using the PVC allows the expansion to complete successfully. Has this issue been addressed?

**Comment by govbetrieb** [comment]
This is still an issue. although the workaround with scaling the pod is working. Thansk @AbhishekKandoi314e

**Comment by atmaniak** [comment]
I have the same issue here with kubevirt 1.7.0 & csi-operator 1.64.0
