### ISSUE TITLE
[BUG]LH volumes stuck in degraded status.

### ISSUE THREAD

**Issue by alexshencn** [longhorn/longhorn#9128]
[supportbundle_78a1a2fc-e067-490c-a13a-efc7404ba35d_2024-07-31T03-21-10Z.zip](https://github.com/user-attachments/files/16435822/supportbundle_78a1a2fc-e067-490c-a13a-efc7404ba35d_2024-07-31T03-21-10Z.zip)
## Describe the bug

LH volumes stuck in degraded status.
![image](https://github.com/user-attachments/assets/2e7d97f6-0f9b-46c8-80a3-594707923725)

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) [and]() version:KK, a standard k8s
   - Number of control plane nodes in the cluster:3
   - Number of worker nodes in the cluster:7
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):SSD
   - Network bandwidth between the nodes (Gbps):10GE
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):bare-metal
 - Number of Longhorn volumes in the cluster:100+

**Comment by derekbit** [comment]
@alexshencn Have you check the longhorn-manager log and see if there is any clue?

**Comment by alexshencn** [comment]
[pvc-29987eb5-b61e-400a-bbcc-f7d6f7622d99-r-045d2022] runtime/cgo: pthread_create failed: Resource temporarily unavailable

I guess it is.
