### ISSUE TITLE
Directory "lost+found"

### ISSUE THREAD

**Issue by guludo** [longhorn/longhorn#913]
Hi, there.

I'm using longhorn as storage provider for an application deployed on `k3s`. The application scans the directories in the volume in order to populate application data. Each directory found is assumed to contain files in the format required by the application. The problem is that ext4 creates the directory `lost+found` and that makes the application try to read specific files in that directory and it obviously fails.

I could work around that by changing the application to receive a list of directory names to be ignored or adding an `initCointainer` just to remove the directory. However I do not like such solutions because (i) technically, the volumes are supposed to be actually empty (I guess :slightly_smiling_face:) and my application shouldn't worry about it; and (ii) creating a blacklist of directory names is very specific to this case - there isn't another reason for my application to ignore some directories in the foreseeable future.

I think it would be great if longhorn could guarantee that the volume is really empty when it is created, so that users wouldn't run into cases like mine.

**Comment by yasker** [comment]
@guludo `lost+found` is generated by the `mkfs.ext4`, so it really not up to Longhorn to remove it. What if the filesystem somehow gets corrupted and you want to repair it? You cannot do it without that directory. It's expected if you format a device with `ext4`.

What we can do is to support formatting to `xfs` as well, which doesn't have the directory. And I think it makes sense to do that.

**Comment by guludo** [comment]
Hm.. I see. Well, I'm closing this then. Thank you!
