### ISSUE TITLE
[BUG] `longhornctl` doesn't work on `amazon linux` and `sle-micro`

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9139]
## Describe the bug

`longhornctl` doesn't work on `amazon linux` and `sle-micro`. Got the following error:

```
msg="failed to get package manager" error="operating systems (amzn, sl-micro) are not supported"
```

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
Update doc https://github.com/longhorn/cli/pull/59#issuecomment-2272401718

**Comment by chriscchien** [comment]
Verified **pass** on longhorn/cil master(`df6c8c`) and v1.7.x(`1bd6ff)`

`longhornctl` worked well on sle-micro `suse-sle-micro-6-0` and amazon linux `Amazon Linux 2023.5.20240805`
