### ISSUE TITLE
[IMPROVEMENT] Improving Longhorn-Manager's Metric Collection: Alternatives to Metrics Server

### ISSUE THREAD

**Issue by hookak** [longhorn/longhorn#9143]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)
Hello

I would like to ask about the implementation of the metric_collector in longhorn-manager (https://github.com/longhorn/longhorn-manager/tree/master/metrics_collector).

The metric_collector currently fetches kubelet metrics collected by the [metrics server](https://github.com/kubernetes-sigs/metrics-server) via the kube-api. While this is convenient, it seems to have two main drawbacks:

- Increased load on the kube-api when the number of nodes scales up.
- The requirement to always deploy the metrics server.

## Describe the solution you'd like

I am wondering if there are any plans to change the structure of longhorn-manager to collect metrics directly from kubelets. However, this approach may have the issue of needing to obtain the kubelet token.

Lastly, if neither method is ideal, I think it would be beneficial to add a feature to disable metric collection. I would appreciate any feedback on this.

Thank you.

**Comment by derekbit** [comment]
> add a feature to disable metric collection. 

The request sounds fair. WDYT? @longhorn/dev @innobead

**Comment by hookak** [comment]
I'll reopen this issue when I find a good solution.
Thanks for looking into this
