### ISSUE TITLE
[TASK] 有没有为Volume设置副本数量跟着集群节点数量自动伸缩

### ISSUE THREAD

**Issue by w7team** [longhorn/longhorn#9150]
现在副本数量只能设置固定的，节点少的话，会自动降级。这种情况对于节点自动伸缩的场景下不太友好，有没有办法可以让副本跟着打标签的节点来自动伸缩数量，不需要给一个固定的值

**Comment by derekbit** [comment]
cc @c3y1huang

**Comment by c3y1huang** [comment]
If I understand your issue correctly, you would like the number of replicas to scale according to the number of nodes with a specific label. 

In my opinion, this approach could be problematic. For instance, if the number of nodes scales down to 1, the replica would also scale down to 1, which is not recommended. Conversely, if the number of nodes scaled up beyond 3, the replicas would increase accordingly, potentially exceeding the desired number of replicas for data protection, and resulting in excess resource usage.

I recommend setting a minimum node count for the auto-scaler to match the replica count. This way, the nodes won't scale below the required number of replicas.

**Comment by w7team** [comment]
我们这边是一家为用户提供集群环境部署方案的公司，目前想把底层存储服务默认换成longhorn，所以我们不知道用户的初始环境是用几个节点，假如我们默认让卷拥有3个副本，那么当一些用户仅有1个或者2个节点时，卷此时会是降级状态，会带来一些不好的影响。
所以我们提这个问题的真实意图是，能否新增一种策略，如果节点数量小于默认副本数量时，实际副本可以自动缩容到跟节点数量对齐的数量，如果节点大于或者等于默认设置副本数量时，实际副本数量再等于默认设置的数量。
这种策略可以对默认想使用longhorn作为底层存储服务的集群方案更友好，也符合轻量级的定位。


Our company specializes in providing users with cluster environment deployment solutions. Currently, we are looking to switch the default underlying storage service to Longhorn. However, we are unaware of the number of nodes in the users' initial environment. If we set the default volume replica count to three, then for some users who only have one or two nodes, the volume would be in a degraded state, which could lead to some adverse effects.
The real intention behind raising this question is to inquire if it is possible to introduce a new strategy. If the number of nodes is less than the default replica count, the actual number of replicas could automatically scale down to match the number of nodes. If the number of nodes is greater than or equal to the default replica count, then the actual number of replicas would equal the default setting.
This strategy would be more user-friendly for cluster solutions that default to using Longhorn as the underlying storage service, and it would also align with the lightweight positioning of our solution.






------------------ 原始邮件 ------------------
发件人: c3y1huang ***@***.***&gt;
发送时间: 2024年8月2日 08:16
收件人: longhorn/longhorn ***@***.***&gt;
抄送: 微擎团队 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [longhorn/longhorn] [TASK] 有没有为Volume设置副本数量跟着集群节点数量自动伸缩 (Issue #9150)





 
If I understand your issue correctly, you would like the number of replicas to scale according to the number of nodes with a specific label.
 
In my opinion, this approach could be problematic. For instance, if the number of nodes scales down to 1, the replica would also scale down to 1, which is not recommended. Conversely, if the number of nodes scaled up beyond 3, the replicas would increase accordingly, potentially exceeding the desired number of replicas for data protection, and resulting in excess resource usage.
 
I recommend setting a minimum node count for the auto-scaler to match the replica count. This way, the nodes won't scale below the required number of replicas.

**Comment by c3y1huang** [comment]
The purpose of keeping the replica count above 1 is to ensure volume data is protected. Having the replica count automatically scale down to 1 contradicts this protection and is very risky, hence not recommenced. In your case, have you checked out the [Replica Node Level Soft Anti-Affinity](https://longhorn.io/docs/1.6.2/references/settings/#replica-node-level-soft-anti-affinity) setting to resolve the volume degraded state issue?

>  If we set the default volume replica count to three, then for some users who only have one or two nodes, the volume would be in a degraded state, which could lead to some adverse effects.

Could you elaborate on what those adverse effects might be?

**Comment by c3y1huang** [comment]
I see, have you checked out the [Replica Node Level Soft Anti-Affinity](https://longhorn.io/docs/1.6.2/references/settings/#replica-node-level-soft-anti-affinity) setting to resolve the volume degraded state issue?

**Comment by w7team** [comment]
我看一下文档，也就是说这个设置只能解决在降级状态下对其中健康副本的调度问题，并不能解决降级状态本身是吧？我提的那种副本设置策略是否会在以后的更新计划中有考虑？


After reviewing the documentation, it seems that this setting can only address the scheduling of healthy replicas in a degraded state, but it does not resolve the degraded state itself, correct? Regarding the replica setting strategy I proposed, is it something that will be considered in future update plans?





------------------ 原始邮件 ------------------
发件人: c3y1huang ***@***.***&gt;
发送时间: 2024年8月2日 09:00
收件人: longhorn/longhorn ***@***.***&gt;
抄送: 微擎团队 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [longhorn/longhorn] [TASK] 有没有为Volume设置副本数量跟着集群节点数量自动伸缩 (Issue #9150)





 
I see, have you checked out the Replica Node Level Soft Anti-Affinity setting to resolve the volume degraded state issue?

**Comment by c3y1huang** [comment]
> After reviewing the documentation, it seems that this setting can only address the scheduling of healthy replicas in a degraded state, but it does not resolve the degraded state itself, correct?

It will allow scaling replicas onto the same node which resolves the degraded state.

> Regarding the replica setting strategy I proposed, is it something that will be considered in future update plans?

cc @derekbit 

> Our company specializes in providing users with cluster environment deployment solutions.

Alternatively, you could ensure that users start with at least 3 worker nodes in the cluster. In my opinion, it's not worth risking losing valuable volume data by relying on a single replica.

**Comment by derekbit** [comment]
@w7team 
Thanks for the feature request. I agree with what @c3y1huang mentioned.

If a volume becomes degraded after auto-scaling, it means the volume has lost high availability (HA) and is in an unprotected state. If the volume can be protected, why not directly use a single-replica volume?

Increasing the number of replicas along with the nodes has some drawbacks:
- Wasted storage space
- Decreased write I/O performance due to the increased number of replicas

Therefore, the best practice is to set the minimum number of nodes to be equal to the maximum number of replicas in the cluster. Then, the volumes will not fall into degraded state. This approach ensures a balance between HA, resource consumption, and performance.

**Comment by c3y1huang** [comment]
Closing issue because the feature request conflicts with the purpose of having replicas for data protection.
