### ISSUE TITLE
[BUG] Accidentally encountered a single replica volume backup stuck at progress 17% indefinitely after a node rebooted 

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9168]
## Describe the bug

When running negative test case `Reboot Replica Node While Heavy Writing And Recurring Jobs Exist` on `v1.7.0-rc3`, accidentally encountered the single replica volume backup stuck at progress `17%` indefinitely after a node rebooted:

https://ci.longhorn.io/job/private/job/longhorn-e2e-test/908/

http://3.226.95.9:30000/

![backup-stuck2](https://github.com/user-attachments/assets/26cefbeb-3ab6-436a-813a-ba6d7c085104)

![backup-stuck4](https://github.com/user-attachments/assets/8757a283-75fb-404e-bdfa-a3a2b37c9f89)

But another 3-replicas volume's backup worked without problems:

![backup-stuck3](https://github.com/user-attachments/assets/dc682fe1-6254-4f4c-adde-7a694aae1aa2)

The backup pod has been running for more than `7 hours`:

```
# kubectl get pods -n longhorn-system
NAME                                                READY   STATUS      RESTARTS         AGE
longhorn-manager-dwfrl                              2/2     Running     0                17h
engine-image-ei-b2ab8286-nsrzd                      1/1     Running     0                17h
instance-manager-8e73d4635f8f25b8df9e1dc086fe559e   1/1     Running     0                17h
csi-snapshotter-68b686dc4-sxr4s                     1/1     Running     0                17h
csi-attacher-644c7b7568-pf7lz                       1/1     Running     0                17h
longhorn-csi-plugin-v8hg4                           3/3     Running     0                17h
csi-provisioner-58cc84b487-jnxts                    1/1     Running     0                17h
csi-resizer-6d5c898684-59pdd                        1/1     Running     0                17h
instance-manager-63149eb3e3db5d15d3861133c96b5cfb   1/1     Running     0                17h
csi-attacher-644c7b7568-86dhp                       1/1     Running     20 (13h ago)     17h
longhorn-ui-545c77b46b-ctfql                        1/1     Running     20 (13h ago)     17h
csi-resizer-6d5c898684-7s9p7                        1/1     Running     20 (13h ago)     17h
longhorn-csi-plugin-sd45v                           3/3     Running     60 (13h ago)     17h
csi-provisioner-58cc84b487-pxnmw                    1/1     Running     20 (13h ago)     17h
csi-snapshotter-68b686dc4-5wkwf                     1/1     Running     20 (13h ago)     17h
engine-image-ei-b2ab8286-9zrwx                      1/1     Running     20 (13h ago)     17h
longhorn-manager-fnkpt                              2/2     Running     40 (13h ago)     17h
instance-manager-d6ac77e60e6e4f2dd8d23fa5df7aebea   1/1     Running     0                13h
instance-manager-8edd2164ce87977aac567f696c4d8c69   1/1     Running     0                13h
e2e-test-volume-0-bak-28710360-kls4g                1/1     Running     0                7h56m
e2e-test-volume-0-bak-28710358-qms29                0/1     Completed   0                7h58m
csi-resizer-6d5c898684-k5x9x                        1/1     Running     13 (7h52m ago)   17h
csi-snapshotter-68b686dc4-5gq4r                     1/1     Running     13 (7h52m ago)   17h
csi-provisioner-58cc84b487-sx5xf                    1/1     Running     13 (7h52m ago)   17h
longhorn-ui-545c77b46b-55jft                        1/1     Running     13 (7h52m ago)   17h
longhorn-csi-plugin-8gx48                           3/3     Running     39 (7h52m ago)   17h
csi-attacher-644c7b7568-zj82c                       1/1     Running     13 (7h52m ago)   17h
longhorn-driver-deployer-7dc6bb676-gqpqm            1/1     Running     14 (7h52m ago)   17h
engine-image-ei-b2ab8286-zmjvz                      1/1     Running     13 (7h52m ago)   17h
longhorn-manager-49ccq                              2/2     Running     26 (7h52m ago)   17h
instance-manager-733129818a84b4d12b84ac8f6273bd16   1/1     Running     0                7h52m
instance-manager-b5ac722da1c3e708e90693eae38a595c   1/1     Running     0                7h52m
e2e-test-volume-1-bak-28710824-g4hcq                0/1     Completed   1                12m
e2e-test-volume-1-bak-28710832-k5pdr                1/1     Running     0                3m39s
e2e-test-volume-1-snap-28710836-xq5l9               0/1     Completed   0                47s
e2e-test-volume-0-snap-28710836-qn5tb               0/1     Completed   0                47s
```

It keeps reporting progress but showing no errors:

```
time="2024-08-03T01:55:20Z" level=info msg="Creating backup backup-3b787922bfe249e7, current progress 17" func="app.(*Job).doRecurringBackup" file="recurring_job.go:676" executionCount=130 labels="map[RecurringJob:e2e-test-volume-0-bak]" namespace=longhorn-system retain=1 snapshotName=e2e-test-5e26c87b-128f-4fa9-a4f9-6fedab125ad8 task=backup volumeName=e2e-test-volume-0
time="2024-08-03T01:55:25Z" level=info msg="Creating backup backup-3b787922bfe249e7, current progress 17" func="app.(*Job).doRecurringBackup" file="recurring_job.go:676" executionCount=130 labels="map[RecurringJob:e2e-test-volume-0-bak]" namespace=longhorn-system retain=1 snapshotName=e2e-test-5e26c87b-128f-4fa9-a4f9-6fedab125ad8 task=backup volumeName=e2e-test-volume-0
time="2024-08-03T01:55:30Z" level=info msg="Creating backup backup-3b787922bfe249e7, current progress 17" func="app.(*Job).doRecurringBackup" file="recurring_job.go:676" executionCount=130 labels="map[RecurringJob:e2e-test-volume-0-bak]" namespace=longhorn-system retain=1 snapshotName=e2e-test-5e26c87b-128f-4fa9-a4f9-6fedab125ad8 task=backup volumeName=e2e-test-volume-0
time="2024-08-03T01:55:35Z" level=info msg="Creating backup backup-3b787922bfe249e7, current progress 17" func="app.(*Job).doRecurringBackup" file="recurring_job.go:676" executionCount=130 labels="map[RecurringJob:e2e-test-volume-0-bak]" namespace=longhorn-system retain=1 snapshotName=e2e-test-5e26c87b-128f-4fa9-a4f9-6fedab125ad8 task=backup volumeName=e2e-test-volume-0
```

The test case is like:

```
Reboot Replica Node While Heavy Writing And Recurring Jobs Exist
    [Tags]    recurring_job
    Given Create volume 0 with    size=2Gi    numberOfReplicas=1
    And Create volume 1 with    size=2Gi    numberOfReplicas=3
    And Attach volume 0
    And Attach volume 1
    And Keep writing data to volume 0
    And Keep writing data to volume 1
    And Create snapshot and backup recurringjob for volume 0
    And Create snapshot and backup recurringjob for volume 1

    FOR    ${i}    IN RANGE    ${LOOP_COUNT}
        When Reboot volume 1 replica node
        And Wait for volume 1 healthy

        Then Check recurringjobs for volume 0 work
        And Check recurringjobs for volume 1 work
        And Check volume 0 works
        And Check volume 1 works
    END
```

In this test run, 2 volumes are all attached to the same node `ip-10-0-2-14`:

```
Waiting for e2e-test-volume-1 detached (1) ...
Waiting for e2e-test-volume-1 detached (2) ...
Attaching volume e2e-test-volume-0 to node ip-10-0-2-14
Waiting for e2e-test-volume-0 attached (0) ...
Waiting for e2e-test-volume-0 attached (1) ...
Waiting for e2e-test-volume-0 attached (2) ...
Waiting for e2e-test-volume-0 attached (3) ...
Waiting for e2e-test-volume-0 attached (4) ...
Attaching volume e2e-test-volume-1 to node ip-10-0-2-14
Waiting for e2e-test-volume-1 attached (0) ...
Waiting for e2e-test-volume-1 attached (1) ...
Waiting for e2e-test-volume-1 attached (2) ...
Waiting for e2e-test-volume-1 attached (3) ...
Waiting for e2e-test-volume-1 attached (4) ...
Waiting for e2e-test-volume-1 attached (5) ...
```

The node to be rebooted is always `ip-10-0-2-198 `:

```
Rebooting node ip-10-0-2-198 with downtime 60 seconds
```

Detailed log: 
[backup-stuck.log](https://github.com/user-attachments/files/16477782/backup-stuck.log)

## To Reproduce

Run test case `Reboot Replica Node While Heavy Writing And Recurring Jobs Exist` repeatedly.

## Support bundle for troubleshooting

[supportbundle_ee57e124-41c6-4693-b88b-aa75dd254e95_2024-08-03T01-55-30Z.zip](https://github.com/user-attachments/files/16477787/supportbundle_ee57e124-41c6-4693-b88b-aa75dd254e95_2024-08-03T01-55-30Z.zip)

## Environment

 - Longhorn version: v1.7.0-rc3
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: sles 15-sp6
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
@yangchiu 
What's the reproduce rate?

**Comment by derekbit** [comment]
@yangchiu 
In addition, can you check if the issue is reproducible in v1.6.2? Thank you.

**Comment by yangchiu** [comment]
> @yangchiu What's the reproduce rate?

I can expect all issues related to negative test cases are often difficult to reproduce. However, it's also the purpose of negative test cases to identify issues in edge cases and to preserve the environments for developers to debug, rather than spending excessive time on reproducing them.

**Comment by innobead** [comment]
@yangchiu Was the backup running on a volume replica where the node was rebooted?

@derekbit is it possibly related to the support of backup failover? or do we support that?

**Comment by derekbit** [comment]
> @derekbit is it possibly related to the support of backup failover? or do we support that? cc @ChanYiLin

IIRC, we don't support the backup failover. @ChanYiLin Do you know it?

**Comment by yangchiu** [comment]
> @yangchiu Was the backup running on a volume replica where the node was rebooted?


No. The backup is running on `ip-10-0-2-14`:

```
e2e-test-volume-0-bak-28710360-kls4g                1/1     Running     0               44h    10.42.2.21    ip-10-0-2-14    <none>           <none>
```

The volume is attached to `ip-10-0-2-14`

```
e2e-test-volume-0   v1            attached   healthy                  2147483648   ip-10-0-2-14   2d1h
```

But the node being rebooted is `ip-10-0-2-198`:

```
Rebooting node ip-10-0-2-198 with downtime 60 seconds
```

**Comment by derekbit** [comment]
Also found a false alarm in the instance-manager pod on `ip-10-0-2-14`
```
2024-08-03T01:54:08.453947507Z time="2024-08-03T01:54:08Z" level=error msg="Failed to remove old head volume-head-002.img" func="replica.(*Replica).createDisk.func1" file="replica.go:924" error="<nil>"
```

Shoud not print error message if there is no error. It is introduced by the [commit](https://github.com/longhorn/longhorn-engine/commit/737bf77b6e0f01e68dbb340e4b3421bb0c7417b6#diff-b54af9ffed94a317525bc7609415261b623020d2aa410c124e9fe3b871d2d2bdR918).

**Comment by derekbit** [comment]
The backuptarget `minio` server is on the rebooted node `10.0.2.198`.  After a quick check, I don't see clues related to the stuck backup.

The issue should be very rare. @ChanYiLin Can you help check?

BTW, we need to fix https://github.com/longhorn/longhorn/issues/9168#issuecomment-2267596512 in v1.7.0 first.

**Comment by ChanYiLin** [comment]
@innobead 
No we don't have **backup failover**, once there is a block failed to upload, 

Another `e2e-test-volume-1` doesn't work either
From the log the backup also failed due to failing to write block to the s3
 ```
2024-08-02T17:07:32.791929485Z [e2e-test-volume-1-r-0f27b169] time="2024-08-02T17:07:32Z" level=error msg="Failed to back up volume e2e-test-volume-1 snapshot e2e-test-9a19340c-f7a3-49d4-aa7f-b11a0f207ead block at offset 58720256 size 2097152" func=backupstore.backupMapping file="deltablock.go:481" error="failed to write data during saving blocks: failed to put object: backupstore/backupstore/volumes/83/1b/e2e-test-volume-1/blocks/7f/ac/7facb3e19d5ad31afaa07425d11d37a5331f2783fdef343cddf3b20862f19f49.blk response: {\n\n} error: AWS Error:  RequestError send request failed Put \"https://minio-service.default:9000/backupbucket/backupstore/backupstore/volumes/83/1b/e2e-test-volume-1/blocks/7f/ac/7facb3e19d5ad31afaa07425d11d37a5331f2783fdef343cddf3b20862f19f49.blk\": dial tcp 10.43.2.151:9000: connect: connection refused\n"
2024-08-02T17:07:32.791968428Z time="2024-08-02T17:07:32Z" level=error msg="Failed to backup volume e2e-test-volume-1 snapshot e2e-test-9a19340c-f7a3-49d4-aa7f-b11a0f207ead" func=backupstore.performBackup file="deltablock.go:591" error="failed to write data during saving blocks: failed to put object: backupstore/backupstore/volumes/83/1b/e2e-test-volume-1/blocks/7f/ac/7facb3e19d5ad31afaa07425d11d37a5331f2783fdef343cddf3b20862f19f49.blk response: {\n\n} error: AWS Error:  RequestError send request failed Put \"https://minio-service.default:9000/backupbucket/backupstore/backupstore/volumes/83/1b/e2e-test-volume-1/blocks/7f/ac/7facb3e19d5ad31afaa07425d11d37a5331f2783fdef343cddf3b20862f19f49.blk\": dial tcp 10.43.2.151:9000: connect: connection refused\n"
2024-08-02T17:07:32.791973680Z time="2024-08-02T17:07:32Z" level=error msg="Failed to perform backup for volume e2e-test-volume-1 snapshot e2e-test-9a19340c-f7a3-49d4-aa7f-b11a0f207ead" func=backupstore.CreateDeltaBlockBackup.func3 file="deltablock.go:297" error="failed to write data during saving blocks: failed to put object: backupstore/backupstore/volumes/83/1b/e2e-test-volume-1/blocks/7f/ac/7facb3e19d5ad31afaa07425d11d37a5331f2783fdef343cddf3b20862f19f49.blk response: {\n\n} error: AWS Error:  RequestError send request failed Put \"https://minio-service.default:9000/backupbucket/backupstore/backupstore/volumes/83/1b/e2e-test-volume-1/blocks/7f/ac/7facb3e19d5ad31afaa07425d11d37a5331f2783fdef343cddf3b20862f19f49.blk\": dial tcp 10.43.2.151:9000: connect: connection refused\n"
2024-08-02T17:07:32.988392264Z [e2e-test-volume-1-r-0f27b169] time="2024-08-02T17:07:32Z" level=error msg="Failed to back up volume e2e-test-volume-1 snapshot e2e-test-9a19340c-f7a3-49d4-aa7f-b11a0f207ead block at offset 60817408 size 2097152" func=backupstore.backupMapping file="deltablock.go:481" error="failed to write data during saving blocks: failed to put object: backupstore/backupstore/volumes/83/1b/e2e-test-volume-1/blocks/b9/f3/b9f3f0036bea26eff7ea0bfb40dda64fd374412bd20eaa6391c642c4411c9823.blk response: {\n\n} error: AWS Error:  RequestError send request failed Put \"https://minio-service.default:9000/backupbucket/backupstore/backupstore/volumes/83/1b/e2e-test-volume-1/blocks/b9/f3/b9f3f0036bea26eff7ea0bfb40dda64fd374412bd20eaa6391c642c4411c9823.blk\": dial tcp 10.43.2.151:9000: connect: connection refused\n"
2024-08-02T17:07:33.481245918Z [e2e-test-volume-1-r-0f27b169] time="2024-08-02T17:07:33Z" level=warning msg="Failed to unlock" func=backupstore.CreateDeltaBlockBackup.func3.2 file="deltablock.go:286" error="failed to list objects with prefix backupstore/backupstore/volumes/83/1b/e2e-test-volume-1/locks/lock-b19fc938f0dd4a78.lck before removing them: failed to list objects with param: {\n  Bucket: \"backupbucket\",\n  Delimiter: \"\",\n  Prefix: \"backupstore/backupstore/volumes/83/1b/e2e-test-volume-1/locks/lock-b19fc938f0dd4a78.lck\"\n} error: AWS Error:  RequestError send request failed Get \"https://minio-service.default:9000/backupbucket?delimiter=&prefix=backupstore%!F(MISSING)backupstore%!F(MISSING)volumes%!F(MISSING)83%!F(MISSING)1b%!F(MISSING)e2e-test-volume-1%!F(MISSING)locks%!F(MISSING)lock-b19fc938f0dd4a78.lck\": dial tcp 10.43.2.151:9000: connect: connection refused\n"
```

And the backup also stuck at 5%
```
- apiVersion: longhorn.io/v1beta2
  kind: Backup
  metadata:
    creationTimestamp: "2024-08-02T17:07:19Z"
    finalizers:
    - longhorn.io
    generation: 1
    labels:
      backup-volume: e2e-test-volume-1
    name: backup-71cd31de9e204214
    namespace: longhorn-system
    resourceVersion: "137196"
    uid: 32a82737-3b80-48ef-a000-7714f2747a43
  spec:
    backupMode: incremental
    labels:
      RecurringJob: e2e-test-volume-1-bak
      longhorn.io/volume-access-mode: rwo
    snapshotName: e2e-test-9a19340c-f7a3-49d4-aa7f-b11a0f207ead
    syncRequestedAt: null
  status:
    backupCreatedAt: "null"
    compressionMethod: "null"
    labels: "null"
    lastSyncedAt: "null"
    messages: {}
    newlyUploadDataSize: "null"
    ownerID: ip-10-0-2-14
    progress: 5
    reUploadedDataSize: "null"
    replicaAddress: tcp://10.42.2.132:10001
    size: "null"
    snapshotCreatedAt: "2024-08-02T17:07:15Z"
    snapshotName: e2e-test-9a19340c-f7a3-49d4-aa7f-b11a0f207ead
    state: InProgress
    url: "null"
    volumeBackingImageName: "null"
    volumeCreated: "null"
    volumeName: "null"
    volumeSize: "2147483648"
```

The recurring job is set to every 2 mins
After that, some backups successfully uploaded
for example, `time=2024-08-02T17:12:18Z` and `backup=backup-7d10405ed2104120`
```
2024-08-02T17:12:18.116775688Z time="2024-08-02T17:12:18Z" level=info msg="Done initiating backup creation, received backupID: backup-7d10405ed2104120" func="rpc.(*SyncAgentServer).BackupCreate" file="server.go:798"
2024-08-02T17:12:18.116780144Z time="2024-08-02T17:12:18Z" level=info msg="Performing delta block backup" func=backupstore.CreateDeltaBlockBackup.func3 file="deltablock.go:294" compressionMethod=lz4
2024-08-02T17:12:18.116784451Z time="2024-08-02T17:12:18Z" level=info msg="Saving config in backupstore" func=backupstore.SaveConfigInBackupStore file="config.go:81" filepath=backupstore/volumes/83/1b/e2e-test-volume-1/backups/backup_backup-7d10405ed2104120.cfg kind=s3 object=config pkg=backupstore reason=start
2024-08-02T17:12:18.190036856Z [e2e-test-volume-1-r-0f27b169] time="2024-08-02T17:12:18Z" level=info msg="Saved config in backupstore" func=backupstore.SaveConfigInBackupStore file="config.go:92" filepath=backupstore/volumes/83/1b/e2e-test-volume-1/backups/backup_backup-7d10405ed2104120.cfg kind=s3 object=config pkg=backupstore reason=complete
```
but because the retain was set to 1, so these backups were deleted.

Some recurring job failed to create the backup due to deletion lock issue as we can see lots of Error backups in the UI page.
Maybe it was because the recurring jobs are so frequent, the previous backup was just being cleaned up, the next backup was created.
But these all happened after we stop the e2e tests, and let the recurring jobs kept running.

**Comment by ChanYiLin** [comment]
The questions here are
For `e2e-test-volume-0` (single replica)
1. When the s3 got deleted due to reboot, the backup should failed with error message, why was it stuck
2. The recurring job stuck was expected, because the backup was still `inProgress`. Our recurring job don't allow overlap job, so the next recurring job will never start.

That brings questions to  `e2e-test-volume-1` (3 replicas)
1. Same as `e2e-test-volume-0`. When the s3 got deleted due to reboot, the backup should failed with error message, why was it stuck (`backup-71cd31de9e204214`)
2. Different from `e2e-test-volume-0`. Why was the recurring job of that stuck backup gone without being stuck like the `e2e-test-volume-0` recurring job (maybe got deleted by the reboot as well?)
3. Since the previous recurring job was gone, the next recurring job successfully started and since we allow concurrent backup creation, there was no lock issue. So the following backup created successfully (let's ignore the deletion lock failure here.)

**Comment by ChanYiLin** [comment]
I tried to reproduce the issue but failed to make the backup stuck in `inProgress` state

### delete the minio and the longhorn-manager when doing back up
1. Upload resumed because we have retry for s3 client: https://github.com/longhorn/backupstore/pull/143
2. longhorn-manager resumed the backup monitor  
3. But it eventually failed, because minio was just a pod without persistent volume, the volume.cfg was gone when the minio was deleted.
4. It failed due to the error when saving the volume.cfg after uploading all the blocks [code](https://github.com/longhorn/backupstore/blob/master/deltablock.go#L620)
```
nginx-r-eb874d18] time="2024-08-05T05:33:11Z" level=info msg="Created snapshot changed blocks: 1536 mappings, 1536 blocks and 1536 new blocks" func=backupstore.performBackup file="deltablock.go:600" event=backup object=snapshot pkg=backupstore reason=complete snapshot=c-i1ztn9-59deeb30-8295-4591-aec8-5f8a296cd028
[nginx-r-eb874d18] time="2024-08-05T05:33:11Z" level=info msg="Saving config in backupstore" func=backupstore.SaveConfigInBackupStore file="config.go:81" filepath=backupstore/volumes/5b/d5/nginx/backups/backup_backup-e69937dc0a064e37.cfg kind=s3 object=config pkg=backupstore reason=start
[nginx-r-eb874d18] time="2024-08-05T05:33:11Z" level=info msg="Saved config in backupstore" func=backupstore.SaveConfigInBackupStore file="config.go:92" filepath=backupstore/volumes/5b/d5/nginx/backups/backup_backup-e69937dc0a064e37.cfg kind=s3 object=config pkg=backupstore reason=complete
[nginx-r-eb874d18] time="2024-08-05T05:33:11Z" level=error msg="Failed to perform backup for volume nginx snapshot c-i1ztn9-59deeb30-8295-4591-aec8-5f8a296cd028" func=backupstore.CreateDeltaBlockBackup.func3 file="deltablock.go:297" error="cannot find backupstore/volumes/5b/d5/nginx/volume.cfg in backupstore"
```

### delete the minio and instance-manager when doing back up
1. it failed here when the instance-manager was back, and the replica restarted
```
	if engineBackupStatus.SnapshotName != m.snapshotName {
		err = fmt.Errorf("cannot find matched snapshot %s/%s of backup %s status in longhorn engine", engineBackupStatus.SnapshotName, m.snapshotName, m.backupName)
		return currentBackupStatus, err
	}
```

cc @derekbit

**Comment by ChanYiLin** [comment]
I will keep investigating the issue.

From my perspective,
If we want to test negative effect on backup, we don't need recurring job here
because it doesn't make any different when doing backup, it only triggers the backup and we can do that in the code as well.
It makes the debug quite hard cause it keeps running after stopping the e2e tests 

We can focus on the test of following example
Put the backuptarget server to the outside of the Longhorn cluster (because the file in the backupstore will be deleted if the pod is deleted. Besides, putting backupstore as a pod in the local cluster without PVC is not production setting.)
- Case 1: Stop external backuptarget server 
- Case 2: Stop non-replica/non-engine node
- Case 3: Stop replica node
- Case 4: Stop engine node 
The backup should fail in these 4 cases.

**Comment by yangchiu** [comment]
Reproduced in https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1011/:

The backup creation got stuck in progress `20%` over `9` hours.

![reproduced](https://github.com/user-attachments/assets/c2b96ba3-a5cf-406a-998f-d6508ff8054b)

[supportbundle_9a794b71-631d-42a7-96ed-2f09a5614538_2024-08-06T01-16-38Z.zip](https://github.com/user-attachments/files/16504065/supportbundle_9a794b71-631d-42a7-96ed-2f09a5614538_2024-08-06T01-16-38Z.zip)

The corresponding `kubeconfig` file has been sent to @ChanYiLin for debugging.

**Comment by ChanYiLin** [comment]
So it doesn't related to single replicas or multiple replicas
We reboot one node
On that node, there could have
1. minio
2. replica which was requested by the engine to do the backup
3. engine which was doing the backup
4. longhorn-manager which was the owner of that backup

We have to find out what circumstances will lead to the backup being stuck in progress

**Comment by innobead** [comment]
Fix in 1.7.0 instead. See whether we need to backport to 1.6.3 if the lint change was backported.

**Comment by ChanYiLin** [comment]
@innobead 
We haven't found the root cause of this issue
The PR @derekbit created is not the fix for this issue, but just refactor another error handling minor issue found in the log.

**Comment by ChanYiLin** [comment]
I can reproduce the issue now, need to spend some time investigating

1. Create a 3Gi Volume (I use 1 replica, but it doesn't matter) and write 3Gi data
2. Create recurring snapshot job 
    - every 2 mins, retain=1
3. Create recurring backup job
    - every 2 mins, retain=1, full-backup-interval=1 (every time)
4. Wait for the first time two jobs completed
    - you will got 1 snapshot and 1 snapshot + backup
5. Then when the second time two recurring jobs start
    - wait for snapshot job completed (~5 secs)
    - wait for backup being created and inprogress
    - when the backup is uploading and ~10% progress, delete the minio pod
        - `$ k delete po/longhorn-test-minio --force`
        - you can log the backup job 
```
time="2024-08-06T09:16:16Z" level=info msg="Creating backup backup-591660f26fec42b6, current progress 14" func="app.(*Job).doRecurringBackup" file="recurring_job.go:676" executionCount=2 labels="map[RecurringJob:c-wvbndu]" namespace=longhorn-system retain=1 snapshotName=c-wvbndu-7880174d-fc35-46f4-8857-df3896aa028d task=backup volumeName=nginx
````
6. Wait until the third time snapshot recurring job start and complete
7. apply backup the minio `$ k apply -f ./manager/integration/deploy/backupstores/`


Then the previous backup job  will stuck in current progress 14  forever

**Comment by ChanYiLin** [comment]
The reproduce steps are not correct
After a while(~17mins, after the s3 put retry backoff) the backup resumed and failed due to
```
cannot find backupstore/volumes/5b/d5/nginx/volume.cfg in backupstore
```

Still need to find how to reproduce the issue

cc @derekbit @innobead

**Comment by derekbit** [comment]
Refine the test case with external backup store cc @longhorn/qa

**Comment by yangchiu** [comment]
Change reproducibility from `rare` to `often` since it's happened frequently.

It causes Longhorn v1.7.x not capable to run test case `Reboot Volume Node While Heavy Writing And Recurring Jobs Exist` and `Reboot Replica Node While Heavy Writing And Recurring Jobs Exist`. I'll stop running these test case in our release testing. cc @longhorn/qa 

Longhorn v1.6.x doesn't have this issue. Just for reference.

**Comment by derekbit** [comment]
cc @ChanYiLin 👆

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-engine d3898b1).


e2e test cases `Reboot Volume Node While Heavy Writing And Recurring Jobs Exist` and `Reboot Replica Node While Heavy Writing And Recurring Jobs Exist` passed 20 consecutive times:
https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1269/
https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1271/
