### ISSUE TITLE
UI: incomplete display of event log message

### ISSUE THREAD

**Issue by yujunz** [longhorn/longhorn#917]
The messages are sometimes too long to display and there is no scrollbar. See screenshot for example.

<img width="243" alt="Screen Shot 2019-11-27 at 3 28 31 PM" src="https://user-images.githubusercontent.com/6813397/69702617-98ea1e00-112a-11ea-9f2c-4741e0dc8187.png">

Browser: Safari Version 13.0.3 (15608.3.10.1.4) on Catalina

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI version: `wangsiye/longhorn-ui:c36c682`

Steps to test:
  - Create a volume attached to a pod using:
   `kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/pvc.yaml`
  - Create volume backup
  - Delete pod along with volume, PV/PVC, 
  - Restore volume using its original volume name.
  - In Dashboard page, Events logs should be scrollable and fully displayed.  **(PASS)**
