### ISSUE TITLE
Question: Is it possible to mount volume from replicas directory on host

### ISSUE THREAD

**Issue by courcelm** [longhorn/longhorn#918]
Is it possible to mount volume from replicas directory on host manually?

**Comment by liogate** [comment]
Hello @courcelm,

Here is a tips to get things working:

First, checkout on longhorn UI the name of your PVC volume: (eg. `pvc-22b7...`)
In the terminal, run the following command: `lsblk -f`

You should see this kind of output:
```
sdc  /var/lib/kubelet/pods/4bf6fb06-0dff-11ea-b57b-0cc47a8687b8/volume-subpaths/pvc-cb6b0...
sdd  /var/lib/kubelet/pods/22b81899-0f10-11ea-b57b-0cc47a8687b8/volumes/kubernetes.io~csi/pvc-22b7...
sde  /var/lib/kubelet/pods/9e10b739-0f10-11ea-b57b-0cc47a8687b8/volumes/kubernetes.io~csi/pvc-9e10....
```
Identify your associated PVC volume name, for example we want to mount `sdc`.
Then create a directory: `mkdir my-longhorn-volume` and mount it: `mount /dev/sdc my-longhorn-volume` 🎉 

Hope this helps,

Regards.

**Comment by courcelm** [comment]
Hello @liogate ,
Thanks for your answer. It is not exactly what I am looking for. I'm looking to recover files from a volume when longhorn is not running. How can I create a block device from a  volume from the  /var/lib/rancher/longhorn/replicas directory?

**Comment by shuo-wu** [comment]
Do you mean you want to recover a volume from the data of the Longhorn volume then use it even if the Longhorn system is not running? 
If this is what you want, the answer is NO. Since the data is stored in a bunch of sparse files rather than a simple file, we need the longhorn engine to help us read/write data from/to those sparse files.

**Comment by courcelm** [comment]
I found the following solution: https://github.com/longhorn/longhorn/issues/469

docker run -it -v /dev:/host/dev -v /proc:/host/proc -v /var/lib/rancher/longhorn/replicas/test-43ae3e3d:/volume --privileged rancher/longhorn-engine:v0.4.1 launch-simple-longhorn test 20g

Is it still functional with v7?

**Comment by shuo-wu** [comment]
Yes. 
```
docker run -it -v /dev:/host/dev -v /proc:/host/proc -v <The replica data path on host>:/volume --privileged longhornio/longhorn-engine:v0.7.0 launch-simple-longhorn <volume name> <volume size> &
```

**Comment by courcelm** [comment]
Thanks!

**Comment by Nemer-Naamneh** [comment]
is this supported in v1.1.0?

**Comment by shuo-wu** [comment]
> is this supported in v1.1.0?

YES. You can refer to this doc for more details: https://longhorn.io/docs/1.1.0/advanced-resources/data-recovery/export-from-replica/
