### ISSUE TITLE
[BUG] v2 Volume Filesystem Trim doesn't work without enabling `uio_pci_generic`

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#9182]
## Describe the bug

Following the implementation of changes in [longhorn/longhorn#9126](https://github.com/longhorn/longhorn/issues/9126) and [longhorn/longhorn#8813](https://github.com/longhorn/longhorn/issues/8813), the usage of `uio_pci_generic` has been deprecated starting from `Longhorn v1.7.0`. However, it has been observed that v2 volumes fail to trim the filesystem if `uio_pci_generic` is not enabled. 

## To Reproduce

1. Go to the Longhorn node.
2. Remove `uio_pci_generic` by `rmmod uio_pci_generic`
3. Remove `uio` by `rmmod uio`
4. Check the modules are removed by `lsmod | grep uio`
5. Add `vfio_pci` by `modprobe vfio_pci`
6. Install the prerequisites and install Longhorn v1.7.0-rc3
7. Enable v2-data-engine
8. Create a pod with a pvc (v2 volume)
9. Write 300 MiB data to the v2 volume and sync twice. 
10. Trim the  v2 volume filesystem ,but volume actual size not change

## Expected behavior

Further investigation is required to ensure filesystem trimming functions correctly without relying on the `uio_pci_generic `module.

## Support bundle for troubleshooting

[supportbundle_820c7dd1-3e92-412a-80c6-cd135c4031cc_2024-08-05T04-21-19Z.zip](https://github.com/user-attachments/files/16492314/supportbundle_820c7dd1-3e92-412a-80c6-cd135c4031cc_2024-08-05T04-21-19Z.zip)

## Environment

 - Longhorn version:  v1.7.0-rc1~rc3
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 
   - Number of control plane nodes in the cluster:1 
   - Number of worker nodes in the cluster:3
 - Node config
   - OS type and version: ubuntu24.04
   - Kernel version:
   - CPU per node:4
   - Memory per node:16GB
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS / KVM
 - Number of Longhorn volumes in the cluster: 1

**Comment by derekbit** [comment]
`unmap` (`discard`) doesn't work while using `vfio_pci` kernel driver. No idea for now. @DamiaSan Do you have any thought?

**Comment by derekbit** [comment]
After discussing with @innobead and @roger-ryao, the issue is due to the `vfio_pci` driver, so we need to investigate it.
Before figuring out the root cause, what we can do for v1.7.0
- longhornctl support `vfio_pci` by default but can be overrode by `uio_pci_generic`
- Add a notice in official document
- QA need to verify the volume attachment and detachment while
  - upgrade v2 volumes using  `uio_pci_generic` in v1.6.2 to using `vfio_pci` in v1.7.0
  - upgrade v2 volumes using  `uio_pci_generic` in v1.6.2 to using `uio_pci_generic` in v1.7.0

**Comment by innobead** [comment]
@derekbit as discussed, we also need to add a notice to the 1.7.0 doc as well for this known issue.

**Comment by derekbit** [comment]
Weird. @roger-ryao and @innobead cannot reproduce the issue anymore.

longhornctl enables `vfio_pci` and `uio_pci_generic`

- Add a notice in official document
  - No need to mention trim issue for now
  - Enable both `vfio_pci` and `uio_pci_generic` kernel modules. SPDK setup.sh can automatically select a correct kernel module.
- longhornctl enables `vfio_pci` and `uio_pci_generic`
- Update the installation scripts in https://github.com/longhorn/longhorn/tree/master/deploy/prerequisite

**Comment by derekbit** [comment]
cc @innobead @roger-ryao 👆

**Comment by DamiaSan** [comment]
Just to understand better: does the issue happen if `uio_pci_generic` is not enabled also if only `vfio_pci` is used?

**Comment by roger-ryao** [comment]
> Just to understand better: does the issue happen if `uio_pci_generic` is not enabled also if only `vfio_pci` is used?

We initially discovered the issue when `uio_pci_generic` was not enabled and only `vfio_pci` was used under these conditions. However, the next day, Derek and I were unable to reproduce the issue.

**Comment by derekbit** [comment]
@roger-ryao Can you help verify if the cli can install both vfio_pci and uio_pci_generic kernel modules? If they can, we can close the ticket.

**Comment by roger-ryao** [comment]
> @roger-ryao Can you help verify if the cli can install both vfio_pci and uio_pci_generic kernel modules? If they can, we can close the ticket.

I enabled both the `vfio_pci` and `uio_pci_generic` kernel modules and tested `v1.7.0-rc4`. However, I didn't use the CLI to install these modules, so I think I still need to test that tomorrow.

**Comment by roger-ryao** [comment]
> vfio_pci and uio_pci_generic
Hi @derekbit 
1. Follow up https://github.com/longhorn/cli, I downloaded `https://github.com/longhorn/cli/releases/download/v1.7.0-rc4/longhornctl-linux-amd64`
2. Install the necessary components using longhornctl with SPDK enabled:
  - After execute `longhornctl install preflight --enable-spdk`, the required kernel modules `vfio_pci` and `uio_pci_generic` were automatically installed on the `Ubuntu 24.04` node.
