### ISSUE TITLE
[BUG] LH fails silently when node has attached volumes

### ISSUE THREAD

**Issue by w13915984028** [longhorn/longhorn#9183]
## Describe the bug

https://github.com/harvester/harvester/issues/6264

## To Reproduce

https://github.com/harvester/harvester/issues/6264

## Expected behavior

Print helpful logs 

LH uses pdb to protect instance-manager, but `canDeleteInstanceManagerPDB` doesn't print log when there are volumes attached

https://github.com/longhorn/longhorn-manager/blob/1286504e6f61b6ad0122aaf817ba5952debbb6d6/controller/instance_manager_controller.go#L1021

https://github.com/longhorn/longhorn-manager/blob/1286504e6f61b6ad0122aaf817ba5952debbb6d6/controller/instance_manager_controller.go#L947

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

also refer https://github.com/longhorn/longhorn/issues/5910

**Comment by yangchiu** [comment]
Tested on master-head (longhorn-manager eddb7e9) following [the test plan](https://github.com/longhorn/longhorn/issues/9183#issuecomment-2273568455).

In scenario 1 `To test drain behavior`, after detaching the manually attached volume, the drain process still fails to complete. The `longhorn-manager` log shows `replica test-1-r-28486904 has no pdb on another node`:

```
$ kubectl logs longhorn-manager-92zm9 -n longhorn-system -c longhorn-manager
time="2024-09-06T03:41:52Z" level=info msg="Node instance-manager-1c5fea66b35b9b7431bc97d8ac03207a is marked unschedulable but removing ip-10-0-1-7 PDB is blocked: replica test-1-r-28486904 has no pdb on another node " func="controller.(*InstanceManagerController).syncInstanceManagerPDB" file="instance_manager_controller.go:850" controller=longhorn-instance-manager node=ip-10-0-1-7
```

Here are the detailed test steps:

1. Create a volume with `1` replica through Longhorn UI
2. Create PV/PVC for it through Longhorn UI
3. Create a pod to use the volume:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
spec:
  containers:
    - name: sleep
      image: busybox
      imagePullPolicy: IfNotPresent
      args: ["/bin/sh", "-c", "while true;do date;sleep 5; done"]
      volumeMounts:
        - name: pod-data
          mountPath: /data
  volumes:
    - name: pod-data
      persistentVolumeClaim:
        claimName: test-1
```
4. Create another volume and manually attach it to the same node where the pod is running
5. Drain the node:
```
$ kubectl drain ip-10-0-1-7 --ignore-daemonsets --delete-emptydir-data --force
```
6. The drain will not complete, and `longhorn-manager` log shows:
```
$ kubectl logs longhorn-manager-92zm9 -n longhorn-system -c longhorn-manager
time="2024-09-06T03:36:13Z" level=info msg="Node instance-manager-1c5fea66b35b9b7431bc97d8ac03207a is marked unschedulable but removing ip-10-0-1-7 PDB is blocked: some volumes are still attached InstanceEngines count 1 test-2-e-0 " func="controller.(*InstanceManagerController).syncInstanceManagerPDB" file="instance_manager_controller.go:850" controller=longhorn-instance-manager node=ip-10-0-1-7
```
7. Detach the manually attached volume
8. The drain still won't complete, and `longhorn-manager` log shows:
```
$ kubectl logs longhorn-manager-92zm9 -n longhorn-system -c longhorn-manager
time="2024-09-06T03:41:52Z" level=info msg="Node instance-manager-1c5fea66b35b9b7431bc97d8ac03207a is marked unschedulable but removing ip-10-0-1-7 PDB is blocked: replica test-1-r-28486904 has no pdb on another node " func="controller.(*InstanceManagerController).syncInstanceManagerPDB" file="instance_manager_controller.go:850" controller=longhorn-instance-manager node=ip-10-0-1-7
```

[supportbundle_33f2628d-398e-4940-bd64-1e2c74144c35_2024-09-06T03-41-02Z.zip](https://github.com/user-attachments/files/16902551/supportbundle_33f2628d-398e-4940-bd64-1e2c74144c35_2024-09-06T03-41-02Z.zip)

@ejweber Could you help check if there's anything wrong with the test steps? Thank you!
