### ISSUE TITLE
[BUG] When node is cordoned LH checks peer pdb but does not skip single-replica volume

### ISSUE THREAD

**Issue by w13915984028** [longhorn/longhorn#9188]
## Describe the bug

https://github.com/harvester/harvester/issues/6266
## To Reproduce

https://github.com/harvester/harvester/issues/6266
## Expected behavior

When checking peer pdb, it should skip those single-replica volumes, the global setting can't solve all situations, e.g. when single-repica and multi-repica volumes are existing in parallel, user needs the setting `block-if-contains-last-replica`.

```
harv41:/home/rancher # kk get settings.longhorn.io -A | grep drain -i
longhorn-system   node-drain-policy                                                 block-if-contains-last-replica                47d
longhorn-system   taint-toleration                                                  kubevirt.io/drain:NoSchedule                  47d
```

PR https://github.com/longhorn/longhorn-manager/pull/3045 tries to fix it.

## Environment

 - Longhorn version: v1.6.1
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

https://github.com/longhorn/longhorn/issues/5910#issuecomment-2269316423
https://github.com/harvester/harvester/issues/6266
https://github.com/harvester/harvester/issues/6264
https://github.com/longhorn/longhorn/issues/9183

**Comment by ejweber** [comment]
As we have been discussing, I do not think we should change the behavior of `block-if-contains-last-replica`. The comment you added to the Harvester docs is a good justification for why: https://github.com/harvester/docs/pull/619#discussion_r1707059172.

The Longhorn user should intentionally allow for their nodes containing "unprotected" replicas to drain by changing the setting (or Harvester team can make that decision for their users by default if they choose).

I recommend we close this one, but I'll give @w13915984028 a chance to respond. Please feel free to close it directly or continue the discussion!

**Comment by w13915984028** [comment]
@ejweber 

LH has global options which can meet maybe >=90% scenarios.

From Harvester's pespective, the global options are not fully flexible for big deployments. User may have VM which requires strong data consistency and can also have VM which can be lost at any time. Then the best options will be control it at namespace/project level.

Back to this, if LH allows user to label/annotate Volume/Replica to overrun the global option. Or LH has another option `block-if-contains-last-replica-skip-single-replica-volume`. That will be more flexible for Harvester to adapt.

Last, I don't mind to close this ticket. Thanks.
