### ISSUE TITLE
Recurring jobs are not set when restoring backup or creating new volume from UI

### ISSUE THREAD

**Issue by courcelm** [longhorn/longhorn#919]
It seems that recurring jobs are not set when restoring a backup or creating a new volume from UI. It doesn't consider recuring jobs of the storageclass when PV/PVC are created manually. I also tried to add recurringJobs volume attributes in PV without success.

recurringJobs seems only set when a new volume claim is done from a statefulset.

Is this feature available?

Thanks

**Comment by shuo-wu** [comment]
1. The volume created by Kubernetes will contain the parameters of the StorageClass. In this case, the recurring jobs will be created as long as the recurring jobs are set in the StorageClass.
2. The volume created by users via Longhorn UI won't set recurring jobs by default. In this case, it means users want to config everything for the volume, including recurring jobs. And the storage class is meaningless for this kind of volume.

3. The curring job is a parameter of the Longhorn volume. We won't set it in the PV or PVC, which are the Kubernetes native resources.

**Comment by courcelm** [comment]
Thanks for your answer @shuo-wu . Currently, I prefer to create volume from the UI to give it a clear name. It is just painful to re-enter multiple recurring jobs every time. It would be nice to have template that I can re-apply quickly like the storageclass.

**Comment by shuo-wu** [comment]
Yes. Actually, someone had filed a request for this feature. But it is still in the planning phase and we have not decided when we will implement it:
https://github.com/longhorn/longhorn/issues/467

**Comment by courcelm** [comment]
@shuo-wu , alright I will follow that issue. Thanks!
