### ISSUE TITLE
[BUG] v2 volume size could become 0 if deleting replica while replica rebuilding

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9191]
## Describe the bug

When running negative test case Delete Replica While Replica Rebuilding on a v2 volume (need longhorn-tests [PR#2003](https://github.com/longhorn/longhorn-tests/pull/2033/files#diff-9e5ba18a9ec016220c9c0010a6dc377044268c42055eb16dd83bac84d0391b60R20)) on v1.7.x-head. which repeatedly deletes a replica while another replica is still rebuilding. The v2 volume size could become 0 and fail the md5sum checking.

https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1015/console

The test case is like:

```
Delete Replica While Replica Rebuilding
    Given Create volume 0 with    size=2Gi    numberOfReplicas=3    dataEngine=${DATA_ENGINE}
    And Attach volume 0
    And Wait for volume 0 healthy
    And Write data to volume 0

    FOR    ${i}    IN RANGE    ${LOOP_COUNT}
        When Delete volume 0 replica on node 0
        And Wait until volume 0 replica rebuilding started on node 0
        And Delete volume 0 replica on node 1
        And Wait until volume 0 replica rebuilding completed on node 0
        And Delete volume 0 replica on node 2

        Then Wait until volume 0 replicas rebuilding completed
        And Wait for volume 0 healthy
        And Check volume 0 data is intact
    END
```

From the log, the test case initially writes `2GB` data to the volume `/dev/longhorn/e2e-test-volume-0`, and records the checksum as `b7e9a9ce7dc8192e2b9280fa2f021cc1`:

```
Got volume e2e-test-volume-0 endpoint = /dev/longhorn/e2e-test-volume-0
Issuing command: dd if=/dev/urandom of=/dev/longhorn/e2e-test-volume-0 bs=1M count=2048 status=none;              sync;              md5sum /dev/longhorn/e2e-test-volume-0 | awk '{print $1}' on ip-10-0-1-230
Issued command: dd if=/dev/urandom of=/dev/longhorn/e2e-test-volume-0 bs=1M count=2048 status=none;              sync;              md5sum /dev/longhorn/e2e-test-volume-0 | awk '{print $1}' on ip-10-0-1-230 with result b7e9a9ce7dc8192e2b9280fa2f021cc1

Storing volume e2e-test-volume-0 data 0 checksum = b7e9a9ce7dc8192e2b9280fa2f021cc1
```

In the first few test runs, the md5sum checks all pass. The calculated checksum matches the recorded checksum:

```
Issuing command: md5sum /dev/longhorn/e2e-test-volume-0 | awk '{print $1}' on ip-10-0-1-230
Issued command: md5sum /dev/longhorn/e2e-test-volume-0 | awk '{print $1}' on ip-10-0-1-230 with result b7e9a9ce7dc8192e2b9280fa2f021cc1

Calculated volume e2e-test-volume-0 checksum b7e9a9ce7dc8192e2b9280fa2f021cc1

Checked volume e2e-test-volume-0 data 0. Expected checksum = b7e9a9ce7dc8192e2b9280fa2f021cc1
. Actual checksum = b7e9a9ce7dc8192e2b9280fa2f021cc1
```

But after a few test runs, the check eventually fails, and the volume size becomes 0:

```
Issuing command: md5sum /dev/longhorn/e2e-test-volume-0 | awk '{print $1}' on ip-10-0-1-230
Issued command: md5sum /dev/longhorn/e2e-test-volume-0 | awk '{print $1}' on ip-10-0-1-230 with result a981130cf2b7e09f4686dc273cf7187e

Calculated volume e2e-test-volume-0 checksum a981130cf2b7e09f4686dc273cf7187e

Checked volume e2e-test-volume-0 data 0. Expected checksum = b7e9a9ce7dc8192e2b9280fa2f021cc1
. Actual checksum = a981130cf2b7e09f4686dc273cf7187e

Checked volume e2e-test-volume-0 data 0 failed. Expected checksum = b7e9a9ce7dc8192e2b9280fa2f021cc1
. Actual checksum = a981130cf2b7e09f4686dc273cf7187e
```

```
~> ls -lah /dev/longhorn/e2e-test-volume-0
brw-rw---- 1 root 6 254, 0 Aug  5 13:55 /dev/longhorn/e2e-test-volume-0

:~> du -sh /dev/longhorn/e2e-test-volume-0
0	/dev/longhorn/e2e-test-volume-0
```

## To Reproduce

Run test case Delete Replica While Replica Rebuilding with [PR#2023](https://github.com/longhorn/longhorn-tests/pull/2033/files#diff-9e5ba18a9ec016220c9c0010a6dc377044268c42055eb16dd83bac84d0391b60R20)

## Support bundle for troubleshooting

[supportbundle_4840f5c7-fc93-4fe2-bd25-f63b1f615432_2024-08-06T01-43-20Z.zip](https://github.com/user-attachments/files/16504201/supportbundle_4840f5c7-fc93-4fe2-bd25-f63b1f615432_2024-08-06T01-43-20Z.zip)

## Environment

 - Longhorn version: v1.7.0-rc3
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1 
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: sles 15-sp6
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
## Pre Ready-For-Testing Checklist
* [ ] Where is the reproduce steps/test steps documented?
The reproduce steps/test steps are at:

* [ ] Does the PR include the explanation for the fix or the feature?

* [ ] Have the backend code been merged (Manager, Engine, Instance Manager, BackupStore etc) (including `backport-needed/*`)?
The PR is at

[fix(engine): mark replica as ERROR if it is not found by derekbit · Pull Request #195 · longhorn/longhorn-spdk-engine (github.com)](https://github.com/longhorn/longhorn-spdk-engine/pull/195)

* [ ] Which areas/issues this PR might have potential impacts on?
Area: v2 volume, online rebuilding
Issues

**Comment by chriscchien** [comment]
Verified **pass** on longhorn-spdk-engine `3b8b22`

Manually perform test [steps](https://github.com/longhorn/longhorn/issues/9191#issue-2449761152) several times, the data intact and volume eventually become healthy.
