### ISSUE TITLE
Volumes are not replicating

### ISSUE THREAD

**Issue by C0NO** [longhorn/longhorn#920]
I have 2 nodes and volumes are not replicating.It is stucking degraded state and after a while snapshot of volumes are deleting on node which is rebuilding state.And replication is restarting.So it is not replicating.But if i try to replicate on same node it is succesfull.Here are logs

manager :
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:42.025829: ->192.168.3.165:10031 W[764kB]     8744us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:41.924933: ->192.168.1.203:10016 W[  4kB]   110145us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:42.028063: ->192.168.3.165:10031 W[1280kB]    12200us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:41.924947: ->192.168.1.203:10016 W[  8kB]   122353us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:41.924985: ->192.168.1.203:10016 W[  4kB]   125411us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:41.925009: ->192.168.1.203:10016 W[  4kB]   134530us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:41.950159: ->192.168.1.203:10016 W[  4kB]   208009us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:41.952674: ->192.168.1.203:10016 W[  4kB]   230226us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:41.962861: ->192.168.1.203:10016 W[  4kB]   220760us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:41.975704: ->192.168.1.203:10016 W[  4kB]   219851us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:41.977330: ->192.168.1.203:10016 W[  4kB]   219676us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:41.987667: ->192.168.1.203:10016 W[  4kB]   220966us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:41.996887: ->192.168.1.203:10016 W[  4kB]   212800us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:42.005891: ->192.168.1.203:10016 W[ 12kB]   227643us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:42.015484: ->192.168.1.203:10016 W[500kB]  1262048us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:43.893434: ->192.168.3.165:10031 P[  0kB]      290us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:42.024409: ->192.168.1.203:10016 W[384kB]  2429255us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:45.893373: ->192.168.3.165:10031 P[  0kB]      438us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:42.025816: ->192.168.1.203:10016 W[764kB]  5015955us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:47.893407: ->192.168.3.165:10031 P[  0kB]      388us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:47.939264: ->192.168.3.165:10031 W[ 12kB]     1532us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:49.893398: ->192.168.3.165:10031 P[  0kB]      448us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:43.890724: ->192.168.1.203:10016 P[  0kB]  7408203us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:42.027956: ->192.168.1.203:10016 W[1280kB]  9274249us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:51.893410: ->192.168.3.165:10031 P[  0kB]      315us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:53.893377: ->192.168.3.165:10031 P[  0kB]      446us"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:46.028132: ->192.168.1.203:10016 W[1280kB]  7998702us failed"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:50.028327: ->192.168.1.203:10016 W[1280kB]  3999289us failed"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:46.026142: ->192.168.1.203:10016 W[764kB]  8001493us failed"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:47.939231: ->192.168.1.203:10016 W[ 12kB]  6088407us failed"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:50.026432: ->192.168.1.203:10016 W[764kB]  4001206us failed"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:51.939547: ->192.168.1.203:10016 W[ 12kB]  2088093us failed"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:51.298942: ->192.168.1.203:10016 P[  0kB]  2728699us failed"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:50.028327: ->192.168.1.203:10016 W[1280kB] pending"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:51.298942: ->192.168.1.203:10016 P[  0kB] pending"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:51.939547: ->192.168.1.203:10016 W[ 12kB] pending"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:47.939231: ->192.168.1.203:10016 W[ 12kB] pending"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:46.028132: ->192.168.1.203:10016 W[1280kB] pending"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:50.026432: ->192.168.1.203:10016 W[764kB] pending"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: Nov 30 21:00:46.026142: ->192.168.1.203:10016 W[764kB] pending"
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: time=\"2019-11-30T21:00:59Z\" level=error msg=\"Error reading from wire: EOF\""
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: time=\"2019-11-30T21:00:59Z\" level=info msg=\"Removing backend: tcp://192.168.1.203:10015\""
time="2019-11-30T21:00:59Z" level=warning msg="pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3: time=\"2019-11-30T21:00:59Z\" level=info msg=\"Closing: 192.168.1.203:10015\""
time="2019-11-30T21:01:04Z" level=debug msg="Requeue longhorn-system/pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 due to conflict: fail to reconcile volume state for pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6: Operation cannot be fulfilled on replicas.longhorn.io \"pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-r-c0a47103\": the object has been modified; please apply your changes to the latest version and try again"
time="2019-11-30T21:01:04Z" level=debug msg="Schedule replica pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-r-c0a47103 to node slave-edge, disk e6f8b2c40d36d0d3, datapath /var/lib/rancher/longhorn/replicas/pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-d4fa143d"
time="2019-11-30T21:01:05Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3\", UID:\"c4fe3aa2-0b0f-11ea-b729-000c2909d2c6\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"40981524\", FieldPath:\"\"}): type: 'Normal' reason: 'Rebuilding' Start rebuilding replica pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-r-c0a47103 with Address 192.168.1.203:10015 for pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6"
time="2019-11-30T21:01:09Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3\", UID:\"c4fe3aa2-0b0f-11ea-b729-000c2909d2c6\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"40981524\", FieldPath:\"\"}): type: 'Normal' reason: 'Rebuilding' Detected rebuilding replica pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-r-c0a47103 (192.168.1.203:10015)"
time="2019-11-30T21:01:10Z" level=debug msg="Requeue longhorn-system/pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3 due to conflict: Operation cannot be fulfilled on engines.longhorn.io \"pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6-e-787bd8b3\": the object has been modified; please apply your changes to the latest version and try again"
time="2019-11-30T21:01:10Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:01:10Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:01:24Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:01:24Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:01:24Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:01:24Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:01:54Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:01:54Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:01:54Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:01:54Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:02:24Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:02:24Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:02:24Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:02:24Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:02:54Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:02:54Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:02:54Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:02:54Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:03:24Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:03:24Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:03:24Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:03:24Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:03:54Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:03:54Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:03:54Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:03:54Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:04:24Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:04:24Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:04:24Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:04:24Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:04:54Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:04:54Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:04:54Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:04:54Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:05:24Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:05:24Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:05:24Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:05:24Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:05:54Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:05:54Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:05:54Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:05:54Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:06:24Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:06:24Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:06:24Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:06:24Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:06:54Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:06:54Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:06:54Z" level=debug msg="Skip rebuilding for volume pvc-c4efa50e-0b0f-11ea-b729-000c2909d2c6 because there is rebuilding in process"
time="2019-11-30T21:06:54Z" level=debug msg="Skip rebuilding for volume pvc-3bc5bcbe-08b3-11ea-b729-000c2909d2c6 because there is rebuilding in process"

**Comment by yasker** [comment]
@C0NO What's the network connecting two nodes? When `Skip rebuilding` shown it meant there is a replica rebuilding in the engine, so I am wondering if the previous rebuilding failed. 

Can you try to delete the rebuilding replica (the one is yellow state) to see if it fixes the problem?
