### ISSUE TITLE
Restoring backup should strip whitespace/tabs in Name field

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#921]
![Screenshot from 2019-12-03 15-47-41](https://user-images.githubusercontent.com/28725423/70088563-79e50380-15e4-11ea-900b-07604eb82d5f.png)

Triple clicking to highlight will copy extra characters

```

pvc-5f6b68fc-1194-4580-abfe-3b0e4cc0e007
--


```

![image](https://user-images.githubusercontent.com/28725423/70088640-a6991b00-15e4-11ea-8d8b-f091846cf416.png)

Error message:

![Screenshot from 2019-12-03 15-52-29](https://user-images.githubusercontent.com/28725423/70088860-16a7a100-15e5-11ea-9320-8a699ad9a3b1.png)

**Comment by ainiml** [comment]
Or, better yet, pre-populate with the Volume name instead @yasker

**Comment by yasker** [comment]
@ainiml original claim name can be chosen when creating PV/PVC for the volume. Just click `use previous PVC` checkbox.

**Comment by ainiml** [comment]
> @ainiml original claim name can be chosen when creating PV/PVC for the volume. Just click `use previous PVC` checkbox.

I don't think the option comes up if you are mass selecting

**Comment by yasker** [comment]
@ainiml yeah, though that's another issue.

**Comment by smallteeths** [comment]
Thanks for reminding me. Pr has been amended @ainiml

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI version: `wangsiye/longhorn-ui:c36c682`

Steps to test:
  - Create a volume, attach it to a node
  - Create a backup
  - Restore backup, Enter volume name that contains trailing spaces/tabs
  - Volume should be created successfully, trailing spaces/tabs should be removed. **(PASS)**
