### ISSUE TITLE
[BUG] After Detach and Re-Attach Following Upgrade to v1.7.0, v2 Volume Snapshots Not Displayed in Longhorn UI 

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#9215]
## Describe the bug

After upgrading Longhorn from `v1.6.2` to `v1.7.0-rc3`, snapshots created for v2 volumes are not displayed in the Longhorn UI if the volume is detached and then re-attached. However , the snapshots are visible when queried via kubectl.

## To Reproduce

1. Install the prerequisites and install Longhorn `v1.6.2`
2. Enable v2-data-engine
3. Create a pod with a pvc (v2 volume)
4. Write 100 MiB data to the v2 volume and sync. Calculate the checksum
5. Create snapshot by `Longhorn-ui`
6. Upgrade longhorn system to `v1.7.0-rc3`
7. Detach v2 volume
8. Re-attach the v2 volume.
9.  The previously created snapshot should be visible in the Longhorn UI, but it is not. However, the snapshot is visible when queried using kubectl.
```bash
> k -n longhorn-system get snapshot
NAME                                   VOLUME       CREATIONTIME           READYTOUSE   RESTORESIZE   SIZE        AGE
8cc8c25f-baa4-4c3d-bb31-8d2fcf09d0ca   vol-162-v2   2024-08-08T07:37:51Z   true         5368709120    36700160    35m
9141352d-7a19-4b5e-9e9e-f2479bc85eae   vol-1        2024-08-08T06:09:24Z   true         2147483648    21045248    123m
ad113419-2039-4e1d-85e0-d096c5d81a8b   vol-162-v2   2024-08-08T06:03:49Z   true         5368709120    175112192   129m
b1b4dd44-86dd-4c31-9ac5-48efb8dc1645   vol-162-v2   2024-08-08T06:05:04Z   true         5368709120    26214400    128m
d5f55cdb-fe10-49cb-b438-24d0c63512a9   vol-1        2024-08-08T06:08:36Z   true         2147483648    112361472   124m
```
![Screenshot_20240808_164502](https://github.com/user-attachments/assets/1bf8d7e7-33b0-4766-b351-5365d54b8fb1)

## Expected behavior

The snapshot created before detaching the v2 volume should remain visible in the Longhorn UI after the v2 volume is re-attached, following an upgrade to v1.7.x-head.

## Support bundle for troubleshooting

[supportbundle_b9eac7b7-752b-4738-b43b-d53c1a758248_2024-08-08T08-44-32Z.zip](https://github.com/user-attachments/files/16540353/supportbundle_b9eac7b7-752b-4738-b43b-d53c1a758248_2024-08-08T08-44-32Z.zip)

## Environment

 - Longhorn version: `1.6.2` upgrade to `v1.7.0-rc3`
 - Impacted volume (PV): `vol-162-v2`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):`Kubectl`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: `v1.25.16+k3s4`
   - Number of control plane nodes in the cluster: `1`
   - Number of worker nodes in the cluster: `3`
 - Node config
   - OS type and version: `ubuntu 24.04`
   - Kernel version:
   - CPU per node: `4`
   - Memory per node: `16GB`
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): HAL lab
 - Number of Longhorn volumes in the cluster:

## Additional context

N/A

**Comment by derekbit** [comment]
cc @DamiaSan

**Comment by derekbit** [comment]
It is a known issue https://github.com/longhorn/longhorn/issues/9054.
