### ISSUE TITLE
[TEST] Bump OS distro version for v1.7.0

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9217]
## What's the test to develop? Please describe

* SLES 15 SP6
* SLE Micro 6
* Rocky, 9.4
* RHEL 9.4
* Oracle 9.4
* Ubuntu LTS 24.04
* Talos, 1.7
* Container-Optimized OS 113

**Comment by yangchiu** [comment]
In GKE, the version of Container-Optimized OS used by the node group is tied to the Kubernetes version.

Ref: https://cloud.google.com/kubernetes-engine/docs/release-notes#current_versions

**Comment by yangchiu** [comment]
* SLES 15 SP6
  - [x] amd64: https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-tests-sles-amd64/26/
  - [x] arm64: https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-tests-sles-arm64/25/
* SLE Micro 6
  - [x] amd64: https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/amd64/job/longhorn-tests-sle-micro-amd64/181/
  - [x] arm64: https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/arm64/job/longhorn-tests-sle-micro-arm64/59/
* Rocky, 9.4
  - [x] amd64: https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/amd64/job/longhorn-tests-rockylinux-amd64/41/
  - [ ] arm64: no suitable image was found. [Rocky-9-EC2-Base-9.4-20240509.0.aarch64](https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/arm64/job/longhorn-tests-rockylinux-arm64/65/) failed to setup the k8s cluster. More investigation needed.
* RHEL 9.4
  - [x] amd64: https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/179/
  - [ ] arm64: no suitable image was found. Both [RHEL-9.4.0_HVM-20240718-arm64-2-Hourly2-GP3](https://ci.longhorn.io/job/public/job/master/job/rhel/job/arm64/job/longhorn-tests-rhel-arm64/92/) and [(SupportedImages) - RHEL 9 ARM64 LATEST - 20240610-69b70f26-9f08-432b-a47e-9d582f69e916](https://ci.longhorn.io/job/public/job/master/job/rhel/job/arm64/job/longhorn-tests-rhel-arm64/97/) failed to setup the k8s cluster. More investigation needed.
* Oracle 9.4
  - [x] amd64: https://ci.longhorn.io/job/public/job/master/job/oracle/job/amd64/job/longhorn-tests-oracle-amd64/34/
  - [ ] arm64: no image is available on AWS
* Ubuntu LTS 24.04
  - [x] amd64: https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/
  - [x] arm64: https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/arm64/job/longhorn-tests-ubuntu-arm64/497/
* Talos, 1.7
  - [x] amd64: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7454/ Longhorn installation without problems and Longhorn basic tests run without problems, but the k8s cluster reboots all its worker nodes automatically every hour for no reason:
```
Events:
  Type     Reason                   Age                From        Message
  ----     ------                   ----               ----        -------
  Normal   Starting                 19m                kube-proxy  
  Normal   Starting                 19m                kubelet     Starting kubelet.
  Warning  InvalidDiskCapacity      19m                kubelet     invalid capacity 0 on image filesystem
  Normal   NodeHasSufficientMemory  19m (x3 over 19m)  kubelet     Node ip-10-0-1-132 status is now: NodeHasSufficientMemory
  Normal   NodeHasSufficientPID     19m (x3 over 19m)  kubelet     Node ip-10-0-1-132 status is now: NodeHasSufficientPID
  Normal   NodeAllocatableEnforced  19m                kubelet     Updated Node Allocatable limit across pods
  Warning  Rebooted                 19m                kubelet     Node ip-10-0-1-132 has been rebooted, boot id: dc7c57d4-926f-4b93-9238-5a4b585a0359
  Normal   NodeNotReady             19m                kubelet     Node ip-10-0-1-132 status is now: NodeNotReady
  Normal   NodeHasNoDiskPressure    19m (x3 over 19m)  kubelet     Node ip-10-0-1-132 status is now: NodeHasNoDiskPressure
  Normal   NodeReady                19m                kubelet     Node ip-10-0-1-132 status is now: NodeReady
```
This problem is not related to Longhorn, since a clean k8s cluster, with no Longhorn installed, experience the same hourly reboots as well. Further investigation needed.
* Container-Optimized OS 113
  - [x] amd64: https://ci.longhorn.io/job/private/job/managed-k8s/job/longhorn-tests-gke/78/

cc @derekbit

**Comment by innobead** [comment]
> * Rocky, 9.4
>   
>   * [x]  amd64: [ci.longhorn.io/job/public/job/master/job/rockylinux/job/amd64/job/longhorn-tests-rockylinux-amd64/41](https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/amd64/job/longhorn-tests-rockylinux-amd64/41/)
>   * [ ]  arm64: no suitable image was found. [Rocky-9-EC2-Base-9.4-20240509.0.aarch64](https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/arm64/job/longhorn-tests-rockylinux-arm64/65/) failed to setup the k8s cluster. More investigation needed.

If no available images, let's just stick to the latest version we have tested. Revisit it in the next feature release (1.8.0)

**Comment by yangchiu** [comment]
> > * Rocky, 9.4
> >   
> >   * [x]   amd64: [ci.longhorn.io/job/public/job/master/job/rockylinux/job/amd64/job/longhorn-tests-rockylinux-amd64/41](https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/amd64/job/longhorn-tests-rockylinux-amd64/41/)
> >   * [ ]   arm64: no suitable image was found. [Rocky-9-EC2-Base-9.4-20240509.0.aarch64](https://ci.longhorn.io/job/public/job/master/job/rockylinux/job/arm64/job/longhorn-tests-rockylinux-arm64/65/) failed to setup the k8s cluster. More investigation needed.
> 
> If no available images, let's just stick to the latest version we have tested. Revisit it in the next feature release (1.8.0)

cc @derekbit
