### ISSUE TITLE
[TASK] Generate `Pre Ready-For-Testing Checklist` while moving ticket status to `review`

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9219]
## What's the task? Please describe

Github bot doesn't create "Pre Ready-For-Testing Checklist" after moving ticket status to `review`
We already replace zenhub board with github project, so the github bot need to update as well.

**Comment by yangchiu** [comment]
It can't be achieved with GitHub Actions: https://github.com/orgs/community/discussions/17405#discussioncomment-4813900

Further investigation needed.

**Comment by yangchiu** [comment]
Currently unable to get issue number from project v2 item node id:

```
query_issue_number response 200 {'data': {'node': None}, 'errors': [{'type': 'NOT_FOUND', 'path': ['node'], 'locations': [{'line': 3, 'column': 3}], 'message': "Could not resolve to a node with the global id of 'PVTI_lADOBumno84AHUtEzgDPiJQ'."}]}

[2024-08-14 08:44:58,799] ERROR in app: Exception on /project [POST]
```

Still have no idea.

**Comment by derekbit** [comment]
> Currently unable to get issue number from project v2 item node id:
> 
> ```
> query_issue_number response 200 {'data': {'node': None}, 'errors': [{'type': 'NOT_FOUND', 'path': ['node'], 'locations': [{'line': 3, 'column': 3}], 'message': "Could not resolve to a node with the global id of 'PVTI_lADOBumno84AHUtEzgDPiJQ'."}]}
> 
> [2024-08-14 08:44:58,799] ERROR in app: Exception on /project [POST]
> ```
> 
> Still have no idea.

How did you get the node ids of the project v2 items?

**Comment by yangchiu** [comment]
> How did you get the node ids of the project v2 items?

The webhook will send it to us:

```
{'action': 'edited', 'projects_v2_item': {'id': 73179001, 'node_id': 'PVTI_lADOAw9Qxs4AldmMzgRcn3k', 'project_node_id': 'PVT_kwDOAw9Qxs4AldmM', 'content_node_id': 'I_kwDOBUNUQc6ACd27', 'content_type': 'Issue', 'creator': {'login': 'longhorn-io-github-bot', 'id': 67932897, 'node_id': 'MDQ6VXNlcjY3OTMyODk3', 'avatar_url': 'https://avatars.githubusercontent.com/u/67932897?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/longhorn-io-github-bot', 'html_url': 'https://github.com/longhorn-io-github-bot', 'followers_url': 'https://api.github.com/users/longhorn-io-github-bot/followers', 'following_url': 'https://api.github.com/users/longhorn-io-github-bot/following{/other_user}', 'gists_url': 'https://api.github.com/users/longhorn-io-github-bot/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/longhorn-io-github-bot/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/longhorn-io-github-bot/subscriptions', 'organizations_url': 'https://api.github.com/users/longhorn-io-github-bot/orgs', 'repos_url': 'https://api.github.com/users/longhorn-io-github-bot/repos', 'events_url': 'https://api.github.com/users/longhorn-io-github-bot/events{/privacy}', 'received_events_url': 'https://api.github.com/users/longhorn-io-github-bot/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2024-08-02T08:22:44Z', 'updated_at': '2024-08-14T08:44:55Z', 'archived_at': None}, 'changes': {'field_value': {'field_node_id': 'PVTSSF_lADOAw9Qxs4AldmMzgdgwuI', 'field_type': 'single_select', 'field_name': 'Status', 'project_number': 8, 'from': {'id': '9c2c1576', 'name': 'Review', 'color': 'GRAY', 'description': ''}, 'to': {'id': '2f1e2eb8', 'name': 'Implement', 'color': 'GRAY', 'description': ''}}}, 'organization': {'login': 'longhorn', 'id': 51335366, 'node_id': 'MDEyOk9yZ2FuaXphdGlvbjUxMzM1MzY2', 'url': 'https://api.github.com/orgs/longhorn', 'repos_url': 'https://api.github.com/orgs/longhorn/repos', 'events_url': 'https://api.github.com/orgs/longhorn/event
s', 'hooks_url': 'https://api.github.com/orgs/longhorn/hooks', 'issues_url': 'https://api.github.com/orgs/longhorn/issues', 'members_url': 'https://api.github.com/orgs/longhorn/members{/member}', 'public_members_url': 'https://api.github.com/orgs/longhorn/public_members{/member}', 'avatar_url': 'https://avatars.githubusercontent.com/u/51335366?v=4', 'description': 'Cloud native distributed block storage built on and for Kubernetes'}, 'enterprise': {'id': 9995, 'slug': 'cncf', 'name': 'Cloud Native Computing Foundation', 'node_id': 'E_kgDNJws', 'avatar_url': 'https://avatars.githubusercontent.com/b/9995?v=4', 'description': '', 'website_url': 'https://cncf.io', 'html_url': 'https://github.com/enterprises/cncf', 'created_at': '2021-11-03T14:57:36Z', 'updated_at': '2024-07-17T11:49:18Z'}, 'sender': {'login': 'yangchiu', 'id': 5709208, 'node_id': 'MDQ6VXNlcjU3MDkyMDg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/5709208?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/yangchiu', 'html_url': 'https://github.com/yangchiu', 'followers_url': 'https://api.github.com/users/yangchiu/followers', 'following_url': 'https://api.github.com/users/yangchiu/following{/other_user}', 'gists_url': 'https://api.github.com/users/yangchiu/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/yangchiu/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/yangchiu/subscriptions', 'organizations_url': 'https://api.github.com/users/yangchiu/orgs', 'repos_url': 'https://api.github.com/users/yangchiu/repos', 'events_url': 'https://api.github.com/users/yangchiu/events{/privacy}', 'received_events_url': 'https://api.github.com/users/yangchiu/received_events', 'type': 'User', 'site_admin': False}}
```

**Comment by derekbit** [comment]
> > How did you get the node ids of the project v2 items?
> 
> The webhook will send it to us:
> 
> ```
> {'action': 'edited', 'projects_v2_item': {'id': 73179001, 'node_id': 'PVTI_lADOAw9Qxs4AldmMzgRcn3k', 'project_node_id': 'PVT_kwDOAw9Qxs4AldmM', 'content_node_id': 'I_kwDOBUNUQc6ACd27', 'content_type': 'Issue', 'creator': {'login': 'longhorn-io-github-bot', 'id': 67932897, 'node_id': 'MDQ6VXNlcjY3OTMyODk3', 'avatar_url': 'https://avatars.githubusercontent.com/u/67932897?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/longhorn-io-github-bot', 'html_url': 'https://github.com/longhorn-io-github-bot', 'followers_url': 'https://api.github.com/users/longhorn-io-github-bot/followers', 'following_url': 'https://api.github.com/users/longhorn-io-github-bot/following{/other_user}', 'gists_url': 'https://api.github.com/users/longhorn-io-github-bot/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/longhorn-io-github-bot/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/longhorn-io-github-bot/subscriptions', 'organizations_url': 'https://api.github.com/users/longhorn-io-github-bot/orgs', 'repos_url': 'https://api.github.com/users/longhorn-io-github-bot/repos', 'events_url': 'https://api.github.com/users/longhorn-io-github-bot/events{/privacy}', 'received_events_url': 'https://api.github.com/users/longhorn-io-github-bot/received_events', 'type': 'User', 'site_admin': False}, 'created_at': '2024-08-02T08:22:44Z', 'updated_at': '2024-08-14T08:44:55Z', 'archived_at': None}, 'changes': {'field_value': {'field_node_id': 'PVTSSF_lADOAw9Qxs4AldmMzgdgwuI', 'field_type': 'single_select', 'field_name': 'Status', 'project_number': 8, 'from': {'id': '9c2c1576', 'name': 'Review', 'color': 'GRAY', 'description': ''}, 'to': {'id': '2f1e2eb8', 'name': 'Implement', 'color': 'GRAY', 'description': ''}}}, 'organization': {'login': 'longhorn', 'id': 51335366, 'node_id': 'MDEyOk9yZ2FuaXphdGlvbjUxMzM1MzY2', 'url': 'https://api.github.com/orgs/longhorn', 'repos_url': 'https://api.github.com/orgs/longhorn/repos', 'events_url': 'https://api.github.com/orgs/longhorn/event
> s', 'hooks_url': 'https://api.github.com/orgs/longhorn/hooks', 'issues_url': 'https://api.github.com/orgs/longhorn/issues', 'members_url': 'https://api.github.com/orgs/longhorn/members{/member}', 'public_members_url': 'https://api.github.com/orgs/longhorn/public_members{/member}', 'avatar_url': 'https://avatars.githubusercontent.com/u/51335366?v=4', 'description': 'Cloud native distributed block storage built on and for Kubernetes'}, 'enterprise': {'id': 9995, 'slug': 'cncf', 'name': 'Cloud Native Computing Foundation', 'node_id': 'E_kgDNJws', 'avatar_url': 'https://avatars.githubusercontent.com/b/9995?v=4', 'description': '', 'website_url': 'https://cncf.io', 'html_url': 'https://github.com/enterprises/cncf', 'created_at': '2021-11-03T14:57:36Z', 'updated_at': '2024-07-17T11:49:18Z'}, 'sender': {'login': 'yangchiu', 'id': 5709208, 'node_id': 'MDQ6VXNlcjU3MDkyMDg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/5709208?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/yangchiu', 'html_url': 'https://github.com/yangchiu', 'followers_url': 'https://api.github.com/users/yangchiu/followers', 'following_url': 'https://api.github.com/users/yangchiu/following{/other_user}', 'gists_url': 'https://api.github.com/users/yangchiu/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/yangchiu/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/yangchiu/subscriptions', 'organizations_url': 'https://api.github.com/users/yangchiu/orgs', 'repos_url': 'https://api.github.com/users/yangchiu/repos', 'events_url': 'https://api.github.com/users/yangchiu/events{/privacy}', 'received_events_url': 'https://api.github.com/users/yangchiu/received_events', 'type': 'User', 'site_admin': False}}
> ```

I don't why the test on Jenkins always creates an engine before adding a disk. I ran the test using local environment, Equinix and AWS ec2 and didn't encounter the issue.
It seems to be an environmental issue on Jenkins. Can you fix it?
