### ISSUE TITLE
[BUG] Longhorn is unable to provision volumes larger than 20TB

### ISSUE THREAD

**Issue by n43o** [longhorn/longhorn#9221]
## Describe the bug

Longhorn (v2) with a 20TB disk request is not properly being provisioned.

`[longhorn-instance-manager] time="2024-07-16T08:35:48Z" level=error msg="Failed to create engine pvc-463a4373-3501-448a-ac5c-3a534c40a9d6-e-0" func="spdk.(*Engine).Create.func2" file="engine.go:114" engineName=pvc-463a4373-3501-448a-ac5c-3a534c40a9d6-e-0 error="failed to start NVMe initiator pvc-463a4373-3501-448a-ac5c-3a534c40a9d6: failed to stop the mismatching NVMe initiator pvc-463a4373-3501-448a-ac5c-3a534c40a9d6 before starting: failed to logout target: failed to execute: /usr/bin/nsenter [nsenter --mount=/proc/1/ns/mnt --ipc=/proc/1/ns/ipc --net=/proc/1/ns/net nvme disconnect --nqn nqn.2023-01.io.longhorn.spdk:pvc-463a4373-3501-448a-ac5c-3a534c40a9d6-e-0], output , stderr malloc(): unsorted double linked list corrupted\n: signal: aborted (core dumped)" frontend=spdk-tcp-blockdev `

## To Reproduce

Provision a Longhorn volume with a 20TB size request.
 
## Expected behavior

Longhorn volume should be provisioned. 
## Environment

 - Longhorn version: 1.6.2
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: EKS
   - Number of control plane nodes in the cluster: EKS Managed
   - Number of worker nodes in the cluster: 10+
 - Node config
   - OS type and version: Ubuntu
   - Kernel version: 6.7
   - CPU per node: 
   - Memory per node: 
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 1 (We are still PoCing)

## Additional context

Hi - We've been debugging internally an issue with Longhorn not being able to provision large volumes (20TB+). We are using Ubuntu instances in EKS running on Kernel 6.7. FWIW, provisioning volumes up to 16TB works just fine, and anything after that is met with the error I posted above.

**Comment by mantissahz** [comment]
cc @DamiaSan, @shuo-wu, @derekbit.

**Comment by derekbit** [comment]
@n43o Can you log into each instance-manager pods and dump the logs in `/tmp/spdk_tgt.log`? Thanks.

**Comment by n43o** [comment]
Hi Derekbit, 

Here are the logs as requested. 

[spdk_tgt.log](https://github.com/user-attachments/files/16625437/spdk_tgt.log)

**Comment by derekbit** [comment]
> Hi Derekbit,
> 
> Here are the logs as requested.
> 
> [spdk_tgt.log](https://github.com/user-attachments/files/16625437/spdk_tgt.log)

@n43o Thanks for the log. I didn't find any clue in the log. I will try to create 20T+ disk and see if it is reproducible in our lab.

**Comment by n43o** [comment]
awesome, tyvm @derekbit

**Comment by n43o** [comment]
Hi @derekbit, any luck trying it out in your lab? Thanks!

**Comment by bluecarpincho** [comment]
Facing a similar issue on our cluster, is there an update available?

**Comment by n43o** [comment]
Hi @derekbit - I'm using https://github.com/brunsgaard/eks-nvme-ssd-provisioner/blob/master/eks-nvme-ssd-provisioner.sh to create the disks (running as a daemonset)

**Comment by DamiaSan** [comment]
@derekbit  On SPDK, I have correctly created a logical volume of 20T, added it to a raid1, exported via nvmf and then connected to it with nvme command. The only issue I found is that the default RPC timeout of 60 seconds was not sufficient to receive the response to the call to create the lvstore. I think SPDK have to fetch all LBAs of the disk, so 60 seconds are not enough to complete this operation.

The disk I used is a ~29TB disk (multiple 7300GB SSDs grouped with `vgcreate`), on a `s3.xlarge.x86` Equinix Metal instance.

**Comment by pvf4HQM6dn** [comment]
@DamiaSan would it be possible for this timeout to be configured on longhorn deployment or is this setting something we don't have access to change?

**Comment by DamiaSan** [comment]
> would it be possible for this timeout to be configured on longhorn deployment or is this setting something we don't have access to change?

It is a setting not configurable and so that you can't change. 


Maybe in `BdevLvolCreateLvstore` we should replace `SendCommand` with `SendCommandWithLongTimeout`, we already use this last one in other RPCs. What do you think @derekbit ?

**Comment by DamiaSan** [comment]
> How many seconds are required in your provision?

118 seconds to create a lvstore over a 29T disk

> I'm fine with either the Long gRPC timeout or a new setting for the value, but I prefer the later one which is more specific. BTW, what will happens after reaching a timeout? Can user delete the problematic volume? We can put the insufficient timeout issue in the negative test cases.

The timeout occur when creating the lvstore, not a volume. What happen is that the RPC call returns with error, so for Longhorn the operation was not completed. But SPDK continue to perform the operation, so when it finish the lvstore is correctly created.

**Comment by DamiaSan** [comment]
> > The disk I used is a ~29TB disk (multiple 7300GB SSDs grouped with `vgcreate`), on a `s3.xlarge.x86` Equinix Metal instance.
> 
> Interesting. Can Equinix machine allocate multiple disks?

The machine has 12 7,3T HDD disks (`sda`->`sdl`), I created a 29T virtual disk (`vg0-disk0`) with 4 of them:
```
root@s3-xlarge-x86-01:~# lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
loop0         7:0    0  63.9M  1 loop  /snap/core20/2318
loop1         7:1    0    87M  1 loop  /snap/lxd/29351
loop2         7:2    0  38.8M  1 loop  /snap/snapd/21759
sda           8:0    0   7.3T  0 disk  
└─vg0-disk0 253:0    0    29T  0 lvm   
sdb           8:16   0   7.3T  0 disk  
└─vg0-disk0 253:0    0    29T  0 lvm   
sdc           8:32   0   7.3T  0 disk  
└─vg0-disk0 253:0    0    29T  0 lvm   
sdd           8:48   0   7.3T  0 disk  
└─vg0-disk0 253:0    0    29T  0 lvm   
sde           8:64   0   7.3T  0 disk  
sdf           8:80   0   7.3T  0 disk  
sdg           8:96   0   7.3T  0 disk  
sdh           8:112  0   7.3T  0 disk  
sdi           8:128  0   7.3T  0 disk  
sdj           8:144  0   7.3T  0 disk  
sdk           8:160  0   7.3T  0 disk  
sdl           8:176  0   7.3T  0 disk  
sdm           8:192  0 894.3G  0 disk  
├─sdm1        8:193  0     2M  0 part  
├─sdm2        8:194  0   1.9G  0 part  [SWAP]
└─sdm3        8:195  0 892.3G  0 part  /
sdn           8:208  0 894.3G  0 disk  
nvme0n1     259:0    0 223.6G  0 disk  
└─mpatha    253:1    0 223.6G  0 mpath 
nvme1n1     259:1    0 223.6G  0 disk  
└─mpatha    253:1    0 223.6G  0 mpath 
```

**Comment by derekbit** [comment]
@DamiaSan 
What's the status of the pending ticket?
IIUC, Longhorn needs to increase the timeout value, right?

**Comment by DamiaSan** [comment]
> IIUC, Longhorn needs to increase the timeout value, right?

Yes, but I still have to do that.

**Comment by derekbit** [comment]
@DamiaSan 
I will pick the ticket. Are you fine with it?

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/go-spdk-helper/commit/92898a88395593dee958635ebb9d3fbfba3aa195)

Successfully added a 20 TB block disk and created a v2 volume on the large disk without any issues.

**Comment by derekbit** [comment]
> Verified **pass** on longhorn master([longhorn/go-spdk-helper@92898a8](https://github.com/longhorn/go-spdk-helper/commit/92898a88395593dee958635ebb9d3fbfba3aa195))
> 
> Successfully added a 20 TB block disk and created a v2 volume on the large disk without any issues.

@chriscchien Can you elaborate more on how you validated the issue? Thank you.
