### ISSUE TITLE
[TEST] Implement manual test case Uninstallation Checks on robot framework

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#9222]
## What's the test to develop? Please describe

Implement manual test case Uninstallation Checks on robot framework

## Describe the tasks for the test

Implement manual test case Uninstallation Checks on robot framework

## Additional context

https://github.com/longhorn/longhorn/issues/7211

**Comment by yangchiu** [comment]
@chriscchien It would be ideal to consider different installation and uninstallation methods, such as kubectl, helm, and rancher.

**Comment by chriscchien** [comment]
Close this ticket as test case merged.
