### ISSUE TITLE
[BUG] Allowing uninstallation with Helm on Terraform doesn't work

### ISSUE THREAD

**Issue by colans** [longhorn/longhorn#9230]
## Describe the bug

When installing Longhorn via Helm on Terraform, I set the flag to allow uninstallation, but it doesn't work.

```terraform
resource "helm_release" "longhorn" {
  name       = "longhorn"
  repository = "https://charts.longhorn.io"
  chart      = "longhorn"
  namespace  = var.kubernetes_longhorn_namespace
  version    = var.kubernetes_longhorn_version
  depends_on = [kubernetes_namespace.longhorn_storage]

  # Helm chart settings.
  # See https://github.com/longhorn/charts/tree/v1.6.x/charts/longhorn#values
  # and https://github.com/longhorn/charts/blob/v1.6.x/charts/longhorn/values.yaml
  set {
    name  = "defaultSettings.deletingconfirmationflag"
    value = true
  }
}
```

## To Reproduce

1. `terraform apply`
2. `terraform destroy`

## Expected behavior

`terraform destroy` should complete with Longhorn uninstalled.  Instead I see this, as if the flag wasn't set:

```
│ Error: 1 error occurred:
│ 	* job longhorn-uninstall failed: BackoffLimitExceeded
```

## Support bundle for troubleshooting

Haven't been able to bring up the UI yet; sorry.

## Environment

 - Longhorn version: 1.6.2
 - Impacted volume (PV): *No PVs yet*
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm via Terraform
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s via Civo
   - Number of control plane nodes in the cluster:  Not sure as managed
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: *Not sure as managed*
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Civo
 - Number of Longhorn volumes in the cluster: 0 so far; haven't got there yet.

## Workaround

Manually setting the flag works, but it shouldn't be necessary if set in advance.

* `kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs deleting-confirmation-flag --kubeconfig ../kubernetes/credentials-generated.yaml`

**Comment by mantissahz** [comment]
Hi @colans,

```terraform
set {
  name  = "defaultSettings.deletingconfirmationflag"
  value = true
}
```

Did you try the name `defaultSettings.deletingConfirmationFlag`?
Because it is the correct parameter name in the values.yaml.

**Comment by colans** [comment]
That was it; I did all lower instead of sentence case.  That's strange, because I normally copy & paste from somewhere, but I can't find the source now.  The lesson is that these are case sensitive.

Anyway, thanks for catching my mistake!
