### ISSUE TITLE
[IMPROVEMENT] Refactor condition icon and text in edit node and disk modal

### ISSUE THREAD

**Issue by a110605** [longhorn/longhorn#9238]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)
Current condition in edit node and disk modal are all in the same row.

<img width="1489" alt="Screenshot 2024-08-15 at 3 40 29 PM" src="https://github.com/user-attachments/assets/5fbafdee-c780-4bf9-b076-06c72745e496">

As we will have more different conditions in the future, the UI layout need to refine.

## Describe the solution you'd like

1. Each row should have only 3 ~ 4 conditions and with multiple rows.
2. Condition icon and text should be horizontal

## Additional context
Related to https://github.com/longhorn/longhorn/issues/9017

**Comment by derekbit** [comment]
cc @mantissahz

**Comment by derekbit** [comment]
Duplicated and fixed in v1.7.2+.
