### ISSUE TITLE
Create PV/PVC in Namespace of restored volume for batch operation

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#924]
If the restored volume already has a namespace, restore it to that namespace.

![image](https://user-images.githubusercontent.com/28725423/70095870-c97efb80-15f3-11ea-9cce-a4c150176551.png)

**Comment by shuo-wu** [comment]
The `Namespace` field is already restored with volume. We can use it as the default value here.

**Comment by ainiml** [comment]
> The `Namespace` field is already restored with volume.
> 
> Actually we already have this feature. You are using batch operation (the button on the top) hence there won't contain a default value here. If you create PV/PVC via the button on the right of the volume then check `Use Previous PVC`, the restored `Namespace` value will be applied to this blank automatically.
> <img alt="Screen Shot 2019-12-04 at 12 17 31 PM" width="2000" src="https://user-images.githubusercontent.com/47542419/70178049-60999100-1690-11ea-8db9-8f8ee5001b9b.png">

It would have to be individually done to a few hundred volumes?

**Comment by yasker** [comment]
@ainiml We will support it in the batch operation too.

**Comment by meldafrawi** [comment]
Validation: **Partially Failed**

- Longhorn UI image: `wangsiye/longhorn-ui:661911d`

Steps to test:
  - Create a namespace using `kubectl create ns ns1`
  - Create a StatefulSet in `ns1` namespace using: 
`kubectl apply -n ns1 -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml`
  - Scale StatefulSet up to `3` using `kubectl scale statefulset -n ns1 web  --replicas=3`
  - Create backup for each Longhorn volume.
  - Scale StatefulSet down to `0`  using `kubectl scale statefulset -n ns1 web  --replicas=0`
  - Delete all 3 Longhorn volumes.
  - In Backup page, restore each volume using the original volume name.
  > Expected Result:  volumes should be restored successfully, `PV/PVC` field should be `Bound`, and `Namespace` field should be `ns1`   **(PASS)**
  - Scale StatefulSet back to `3`
  > Expected Result: volumes gets attached to newly created StatefulSet pods.  **(PASS)**
  - In Backup page, restore each volume using the different volume name than its original volume name.
  - In volume page, select 2 volumes, and click `Create PV/PVC` button.
  - check `Use Previous PVC` and click `OK`.
  > Expected Result: a new PV/PVC will be created for each volume in `ns1` namespace.  **(PASS)**
  - for the 3rd restored volume, using the `Operation` menu on the right, click `Create PV/PVC`

  >> **An empty page with the following error on console  (FAILED)**

![image](https://user-images.githubusercontent.com/18232258/71207586-e2ec9c80-22af-11ea-9246-d033de47856e.png)

**Comment by meldafrawi** [comment]
Validation: **Partially Failed**

- Longhorn UI image: `wangsiye/longhorn-ui:9787bfb`

Steps to test:
  - Create a namespace using `kubectl create ns ns1`
  - Create a StatefulSet in `ns1` namespace using: 
`kubectl apply -n ns1 -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml`
  - Scale StatefulSet up to `3` using `kubectl scale statefulset -n ns1 web  --replicas=3`
  - Create backup for each Longhorn volume.
  - Scale StatefulSet down to `0`  using `kubectl scale statefulset -n ns1 web  --replicas=0`
  - Delete all 3 Longhorn volumes.
  - Delete created PVs and PVCs.
  - In Backup page, click `Restore Latest Backup` for each volume using a **different** volume name than its original volume name.
  - In volume page, for one volume, using the  `Operation` menu on the right, click `Create PV/PVC`
  - Check `Use Previous PVC`, and clic `OK`
  > Expected Result: a new PV will be created, and a new PVC will be created using the old PVC name.  (PASS)
  - Select other two volumes, and click on `Create PV/PVC` button.
  - Check `Use Previous PVC`, and clic `OK`
  >  Expected Result: a new PV for each volume will be created, and a new PVC will be created using the old PVC name  **(FAILED)**
      **Error**: a new PVC is created with different name than the original PVC.

**Comment by meldafrawi** [comment]
Validation: **Passed**

Longhorn UI version: `wangsiye/longhorn-ui:d629ffe`
