### ISSUE TITLE
[BUG] Listing Backups in "Backup" tab fails S3

### ISSUE THREAD

**Issue by megatr0n28** [longhorn/longhorn#9246]
## Describe the bug

When I click on "Backup" in the Longhorn dashboard.  I get the following error message:
`error listing backup volume names: timeout executing: /var/lib/longhorn/engine-binaries/prod.harbor.keysight.digital-cache-dockerhub-longhornio-longhorn-engine-v1.5.3/longhorn [backup ls --volume-only s3://MY-S3-BUCKET@us-east-2/], output , stderr, time="2024-08-16T18:27:49Z" level=info msg="Loaded driver for s3://MY-S3-BUCKET@us-east-2/" func=s3.initFunc file="s3.go:85" pkg=s3 , error <nil`

## To Reproduce

1. Go to 'Backup' tab
2. See error displayed at the top banner

## Expected behavior

All created backups should be listed

## Environment

 - Longhorn version: 1.5.3
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro EKS and version: 1.29
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 13
 - Node config
   - OS type and version: Amazon Linux 2
   - Kernel version: 5.10.220-209.869.amzn2.x86_64
   - CPU per node: 8
   - Memory per node: 30 GB
   - Disk type (e.g. SSD/NVMe/HDD): EBS
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS EKS
 - Number of Longhorn volumes in the cluster: 1 with 3 replicas

**Comment by derekbit** [comment]
cc @mantissahz

**Comment by mantissahz** [comment]
Hi @megatr0n28,

Could you provide the support bundle?
And could you try to use the command in the longhorn-manager pod to check if the error still occurs?

```shell
export AWS_ACCESS_KEY_ID=xxxxxxx AWS_SECRET_ACCESS_KEY=xxxxxxx
/var/lib/longhorn/engine-binaries/prod.harbor.keysight.digital-cache-dockerhub-longhornio-longhorn-engine-v1.5.3/longhorn backup ls --volume-only s3://MY-S3-BUCKET@us-east-2/
```

**Comment by derekbit** [comment]
@mantissahz Let's add the troubleshooting steps and command in `longhornctl`. Can you create a ticket it for it? Thank you.

**Comment by megatr0n28** [comment]
@mantissahz I emailed the Support Bundle.

I was able to list the volumes in the S3 bucket in the longhorn-manager pod using the longhornctl cmd

**Comment by mantissahz** [comment]
Hi @megatr0n28,

Looks like the default timeout `1 minute` to get the backup volume list is not enough.
Would you mind using the Longhorn v1.5.3 customized image `jamesluhz/lh-manager:v153-customized-timeout` to check if this occurred by the short timeout?

After applying the customized image `jamesluhz/lh-manager:v153-customized-timeout`, there is a new setting `backup-execution-timeout` (minutes), and you could set it to a bigger value by the kubectl command.

```shell
kubectl -n longhorn-system patch setting backup-execution-timeout -p '{"value": "10"}'
```

**Comment by megatr0n28** [comment]
When applying the customized image `jamesluhz/lh-manager:v153-customized-timeout` to the longhorn-manager DaemonSet, I am getting `Request failed with status code 502` in the Longhorn UI.
![Screenshot 2024-08-20 at 9 50 44 AM](https://github.com/user-attachments/assets/30417864-3e5e-40c4-8b9a-879d0923acf0)

**Comment by mantissahz** [comment]
Hi @megatr0n28,

Could upgrade the `longhorn-manager` image by Helm?
There are some other components involved.

**Comment by megatr0n28** [comment]
Hi @mantissahz,
The customized image: `jamesluhz/lh-manager:v153-customized-timeout` and backup-execution-timeout:`10` are working

**Comment by mantissahz** [comment]
duplicated with https://github.com/longhorn/longhorn/issues/8954

**Comment by megatr0n28** [comment]
@mantissahz Can I get a new custom image for Longhorn v1.6.3 for the backup-execution-timeout:10

**Comment by mantissahz** [comment]
Hi @megatr0n28,

Here `jamesluhz/lh-manager:v163-customized-timeout` is the custom image for Longhorn v1.6.3, but I have not tested it yet. I just cherry-picked it from the master.

**Comment by derekbit** [comment]
@megatr0n28 Why not upgrade to v1.7.2?

**Comment by mantissahz** [comment]
>@megatr0n28 Why not upgrade to v1.7.2?

Yeah, we suggest upgrading to v1.6.3 and then to v1.7.2.

**Comment by megatr0n28** [comment]
@derekbit @mantissahz Thank you.  The 1.6.3 custom image worked.

Do you know if v1.7.2 has the permanent fix for `backup-execution-timeout`?  If so, we will upgrade to v1.7.2 later this year.

**Comment by mantissahz** [comment]
>@derekbit @mantissahz Thank you. The 1.6.3 custom image worked.
Do you know if v1.7.2 has the permanent fix for backup-execution-timeout? If so, we will upgrade to v1.7.2 later this year.

It's only from v1.8.0, https://github.com/longhorn/longhorn/issues/8319

**Comment by derekbit** [comment]
> > @derekbit @mantissahz Thank you. The 1.6.3 custom image worked.
> > Do you know if v1.7.2 has the permanent fix for backup-execution-timeout? If so, we will upgrade to v1.7.2 later this year.
> 
> It's only from v1.8.0, #8319

Oh, I thought it is in v1.7 as well.
@mantissahz Should we increase the value in v1.6.x and v1.7.x?

**Comment by mantissahz** [comment]
>Oh, I thought it is in v1.7 as well.
@mantissahz Should we increase the value in v1.6.x and v1.7.x?

@derekbit, I think this improvement can be back-ported to v1.7.x and v1.6.x.

**Comment by innobead** [comment]
> > @derekbit @mantissahz Thank you. The 1.6.3 custom image worked.
> > Do you know if v1.7.2 has the permanent fix for backup-execution-timeout? If so, we will upgrade to v1.7.2 later this year.
> 
> It's only from v1.8.0, #8319

For any bug fix, it's feasible w/o breaching or incompatible changes. we should try to backport.

**Comment by derekbit** [comment]
@mantissahz Could you create ticket for increasing the default timeout? Thank you.
