### ISSUE TITLE
Improvement of OpenSSF Scorecard Score

### ISSUE THREAD

**Issue by harshitasao** [longhorn/longhorn#9247]
Hi, I'm Harshita. I’m working with [CNCF and the Google Open Source Security Team for the GSoC 2024 term](https://github.com/cncf/mentoring/issues/1196). We are collaborating to enhance security practices across various CNCF projects. The goal is to improve security for all CNCF projects by both using OpenSSF Scorecards and implementing its security improvements.

As this project already has scorecard action, I'm here to increase the final score by going over each check. I've listed all of the checks where work needs to be done, in order of its criticality. I plan to submit each PR for each fix. Please let me know what you think and for which ones a PR is welcome that I will submit it ASAP.

**Current Score:** 6.5

**Scorecard report:** https://scorecard.dev/viewer/?uri=github.com/longhorn/longhorn

Here's a few checks we can work on to improve the project's security posture:

- [ ] [Signed-Releases](https://github.com/ossf/scorecard/blob/main/docs/checks.md#signed-releases): Score = 0
    - The releases need to be signed; we can use [cosign using github actions ](https://github.com/avisi-cloud/cosign-tutorial#using-github-actions) for that, and it will increase the score to 8. Additionally, [SLSA provenance](https://slsa.dev/spec/v0.1/index) also needs to be added, which can be done using [this](https://github.com/slsa-framework/slsa-github-generator), increasing the overall score to 10.

- [X] [Token-Permissions](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions): Score = 0
    - The issue here is that many workflows doesn’t have a top-level read-only permissions block like present in the other workflows. Scorecard is quite severe in this check: a single workflow without top-level permissions gets a 0/10 for the check.
    - PR: https://github.com/longhorn/longhorn/pull/9250

- [ ] [Fuzzing](https://github.com/ossf/scorecard/blob/main/docs/checks.md#fuzzing): Score = 0
    - Integrating the project with OSS-Fuzz by following the instructions [here](https://google.github.io/oss-fuzz/). The most difficult one on the list, maintainers help, is highly appreciated. For example, helping in identifying the components where fuzz testing will be added.

- [X] [Pinned-Dependencies](https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies): Score = 0
    - Github actions are not pinned by hash, which results in a low score.
    - Pinning dependencies to a specific hash rather than allowing mutable versions or ranges of versions improves supply chain security.
    - PR: https://github.com/longhorn/longhorn/pull/9250
   
- [ ] [SAST](https://github.com/ossf/scorecard/blob/a8eae2d833553e93021a22f5641661cb6ad3e24c/docs/checks.md#sast): Score = 0
    - Running the CodeQL checks in the CI/CD by following the instructions [here](https://github.com/github/codeql-action#usage).

- [ ] [CII-Best Practices](https://github.com/ossf/scorecard/blob/main/docs/checks.md#cii-best-practices): Score = 0
     - This check determines whether the project has earned an [OpenSSF (formerly CII) Best Practices Badge](https://www.bestpractices.dev/) at the passing, silver, or gold level. The OpenSSF Best Practices badge indicates whether or not that the project uses a set of security-focused best development practices for open source software.
     - To remediate the check, sign up for the [OpenSSF Best Practices program](https://www.bestpractices.dev/). 
     - NOTE: This can only be done by mainatiner of the project.

/cc @joycebrum @diogoteles08 @pnacht @nate-double-u

**Comment by derekbit** [comment]
Thanks @harshitasao.
Do you need add the OpenSSF Scorecard Score to each component in Longhorn org?

cc @innobead

**Comment by innobead** [comment]
I would suggest starting from longhorn/longhorn first as it's the entry point of repo. See the effect, and then introduce to other tier repos.

**Comment by innobead** [comment]
Any updates @harshitasao

**Comment by nate-double-u** [comment]
Hi @innobead, just a note: @harshitasao was a Google Summer of Code mentee. Since the term is over, she may have less availability than when she opened this issue.
