### ISSUE TITLE
[BUG]Environment_check.sh not running on QNAp Server with QTS 5.0.1.2425

### ISSUE THREAD

**Issue by trebur** [longhorn/longhorn#9251]
After stert nvironment_check.sh (NVME_CLI_VERSION="1.12") hangs the sript in in waiting of building longhorn-environment-check pod.
 with 
_kubectl describe pod longhorn-environment-check__    
I got following output

_Name:         longhorn-environment-check-f2h2c
Namespace:    default
Priority:     0
Node:         qnap-k3s-q154i18548/10.0.3.2
Start Time:   Sun, 18 Aug 2024 13:21:14 +0200
Labels:       app=longhorn-environment-check
              controller-revision-hash=658788ddcd
              pod-template-generation=1
Annotations:  <none>
Status:       Pending
IP:           10.42.0.224
IPs:
  IP:           10.42.0.224
Controlled By:  DaemonSet/longhorn-environment-check
Containers:
  longhorn-environment-check:
    Container ID:
    Image:         alpine:3.12
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Args:
      /bin/sh
      -c
      sleep 1000000000
    State:          Waiting
      Reason:       CreateContainerError
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /tmp/longhorn-environment-check from mountpoint (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-n9pg8 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  mountpoint:
    Type:          HostPath (bare host directory volume)
    Path:          /tmp/longhorn-environment-check
    HostPathType:
  kube-api-access-n9pg8:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  33s                default-scheduler  Successfully assigned default/longhorn-environment-check-f2h2c to qnap-k3s-q154i18548
  Warning  Failed     32s                kubelet            Error: failed to generate container "5f0da441fe9aa2dc05f5f24828f4b85cd4185f9cb6dc8efeb1865ffc50634c46" spec: failed to generate spec: path "/tmp/longhorn-environment-check" is mounted on "/" but it is not a shared mount
  Warning  Failed     32s                kubelet            Error: failed to generate container "4b5d97535bf8a2fbcd2c3839a2de24739035572991cc7e8ccf6ed736e4f8c6e7" spec: failed to generate spec: path "/tmp/longhorn-environment-check" is mounted on "/" but it is not a shared mount
  Warning  Failed     21s                kubelet            Error: failed to generate container "4eee631bba81dd77f7adde03bba0d7e22b246b2c59a58809fc34e2ded974cbbb" spec: failed to generate spec: path "/tmp/longhorn-environment-check" is mounted on "/" but it is not a shared mount
  Normal   Pulled     10s (x4 over 32s)  kubelet            Container image "alpine:3.12" already present on machine
  Warning  Failed     10s                kubelet            Error: failed to generate container "ef63e7e3b28798e57d2f779b54f822ae8b5c8b702716f31a4f43ce823ccc2c38" spec: failed to generate spec: path "/tmp/longhorn-environment-check" is mounted on "/" but it is not a shared mount_

any suggestion how to solve this problem  ?

**Comment by derekbit** [comment]
Our environment doesn't support QNAP OS. I would suggest you check the steps and requirements in https://longhorn.io/docs/1.6.2/deploy/install/ and https://github.com/longhorn/longhorn/blob/master/scripts/environment_check.sh.
