### ISSUE TITLE
[BUG] Backup CR Stuck in Deletion if the Source PVC is already removed

### ISSUE THREAD

**Issue by WebberHuang1118** [longhorn/longhorn#9252]
## Describe the bug
LH Backup CR will be stuck in deletion if the source PVC is already gone

## To Reproduce
1. Setting the backup target
2. Create a PVC with LH as the provider
3. Attaching LH volume and creating a backup
4. Deleting the PVC
5. Deleting the backup CR
6. The backup CR will be stuck in deletion

## Expected behavior
The backup CR could be removed

## Environment
 - Longhorn version: v1.7.0-rc4
 - Harvester version: master-head (commit `4e94f46e2f40fcf1cd6efd4530e63870b6945a5f`)

## Additional context
https://github.com/longhorn/longhorn-manager/blob/65bbe0b497847738f4dc3a2f2caebdbfa0952d41/controller/backup_controller.go#L326-L344
Backup controller doesn't remove the finalizer if the related LH snapshot not exist

## Workaround and Mitigation
Manually remove Backup CR's finalizer

**Comment by mantissahz** [comment]
cc @FrankYang0529

**Comment by mantissahz** [comment]
@WebberHuang1118, 
Could you try to disable the setting auto-cleanup-when-delete-backup to check if the backup still can not be deleted?

**Comment by derekbit** [comment]
Assigned to @mantissahz instead and check if it is a regression.

**Comment by FrankYang0529** [comment]
@WebberHuang1118, thanks for raising the issue. I think you point out the question. We should not return nil if snapshot is not existent. We should replace L336 with `return bc.ds.RemoveFinalizerForBackup(backup)`.

**Comment by WebberHuang1118** [comment]
> @WebberHuang1118, Could you try to disable the setting `auto-cleanup-when-delete-backup` to check if the backup still can not be deleted?

No, the Backup CR could be deleted if setting `auto-cleanup-when-delete-backup` is disabled

**Comment by derekbit** [comment]
After discussing with @mantissahz, we can blindly remove the finalizer of the backup even though failed to delete the snapshot. Any concerns? @FrankYang0529 @WebberHuang1118 

cc @mantissahz

**Comment by WebberHuang1118** [comment]
> After discussing with @mantissahz, we can blindly remove the finalizer of the backup even though failed to delete the snapshot. Any concerns? @FrankYang0529 @WebberHuang1118
> 
> cc @mantissahz

Just a Nit, `we can blindly remove the finalizer of the backup even though failed to delete the snapshot` possibly should be `we can blindly remove the finalizer of the backup if the related snapshot is already gone`, WDYT? @FrankYang0529 

Except theabove, it sounds good to me

**Comment by FrankYang0529** [comment]
I think we can do best effort to remove snapshot. If there is any error, we can just skip it, or it may block removing backup.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-manager/commit/19ba220756a5a4ad7ee8b62b96573b9328fea234), v1.7.x(https://github.com/longhorn/longhorn-manager/commit/c72014c550375afc0c0601436604114df22c764c) 

Following test [steps](https://github.com/longhorn/longhorn/issues/9252#issuecomment-2295873209), backup CR can be deleted without any problems
