### ISSUE TITLE
[Bug?] Volumes deleted in K8s remain detached but not deleted in Longhorn

### ISSUE THREAD

**Issue by vitobotta** [longhorn/longhorn#926]
Sometimes when I delete a volume from Rancher, the pvc and pv are gone but the volume remains detached and is not deleted in Longhorn according to its UI. Bug? It only happens sometimes.

**Comment by yasker** [comment]
Are the volume created using Storage Class or Longhorn UI? Longhorn will not delete the volume when PV/PVC was created using Longhorn UI for existing volumes.

**Comment by vitobotta** [comment]
Storage class :)

**Comment by yasker** [comment]
Can you send us the support bundle? We'd like to take a look.

You can send it to `longhorn-support-bundle@rancher.com`.

**Comment by vitobotta** [comment]
Sent. I have been testing many things today so hopefully you can find the info you need :)

**Comment by yasker** [comment]
@vitobotta I've check the log, but cannot find a volume that wasn't deleted correctly.

I've checked the CSI provisioner log (csi-provisioner-75dddf86b9-z4chb). Kubernetes would ask the provisioner to delete a volume when it's releasing from Kubernetes. I've checked log and compare it to the existing volume list, but cannot find any volume mentioned in CSI provisioner still remained in the Longhorn.

Next time if the same thing happened again, can you send us a new bundle with the name of volume? I think the volume name would help a lot on debugging this issue.

**Comment by vitobotta** [comment]
Hi @yasker 

Uhm... perhaps there isn't a bug there. It happened today again, I was testing some postgres operator so I created and deleted volumes several times, and sometimes the Longhorn UI, which usually updates automatically (I guess with web sockets or something), doesn't reflect the change when a volume is deleted. If I refresh then the volumes disappear. So it looks it may just be a UI thing? Thanks

**Comment by yasker** [comment]
@vitobotta 

Websocket can be delayed a bit or lost events when the network condition is not optimal. You can take a look at down-right corner, which shows the current WebSocket status. If it's not all full green, the refresh of the information might be delayed.

**Comment by vitobotta** [comment]
@yasker Gotcha. I guess we can close this. Thanks :)
