### ISSUE TITLE
[BUG] Incorrect NFS endpoint after enable/disable storage network for RWX volume

### ISSUE THREAD

**Issue by Vicente-Cheng** [longhorn/longhorn#9272]
## Describe the bug

When we disable the storage network for RWX volume, the existing RWX volume would not get the correct NFS endpoint.
This means the CSI driver cannot mount the NFS correctly.

## To Reproduce

1. Create Harvester cluster (maybe not necessary)
2. make sure the longhorn version v1.7.0
3. **(No Need)** create RWX volume and create a pod using this RWX volume
4. **(No Need)** delete the pod and make sure RWX volume is unused

Update: seems we could directly enable storage network for RWX volume and then disable as below steps

5. create storage network and enable storage network for the RWX volume
6. create a pod using previous RWX volume
7. delete the pod and make sure RWX volume is unused
8. delete storage network then disable storage network for RWX volume
9. create a pod using previous RWX volume again

This time the pod would not be created.
And we found the endpoint on the SM would be:
```
endpoint: nfs://None/pvc-e1b386d5-6b19-483c-9ca2-ae025a8cc247
```

## Expected behavior

The pod should be created successfully, and RWX volume could be used.

## Environment

 - Longhorn version: v1.7.0
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

### Root cause analysis
For non-storage-network-enabled RWX volume, we should use service cluster IP as the endpoint.
(Refer to recently fix PR: https://github.com/longhorn/longhorn-manager/pull/3064)

The service CR when the issue happened:
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-08-21T11:35:47Z"
  labels:
    longhorn.io/managed-by: longhorn-manager
    longhorn.io/share-manager: pvc-e1b386d5-6b19-483c-9ca2-ae025a8cc247
  name: pvc-e1b386d5-6b19-483c-9ca2-ae025a8cc247
  namespace: longhorn-system
  ownerReferences:
  - apiVersion: longhorn.io/v1beta2
    controller: false
    kind: ShareManager
    name: pvc-e1b386d5-6b19-483c-9ca2-ae025a8cc247
    uid: f29f7a04-3d37-4ee5-8395-90242638daa1
  resourceVersion: "2005783"
  uid: 8d914cea-9006-48d0-8733-32df50400847
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
    targetPort: 2049
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

We could see the ClusterIP is `None`.
It is set up when the storage network is enabled for RWX volume.
Checked here https://github.com/longhorn/longhorn-manager/blob/v1.7.0/controller/share_manager_controller.go#L1055-L1066

Only the `Service` creation will consider whether the situation with the Storage Network is enabled or not.
In most cases when the user enable/disable the `StorageNetworkForRWXVolumeEnabled`, the service and endpoint will be cleaned up.

However, the following steps will not clean up the service and endpoint. 
1. disable storage network
Calling https://github.com/longhorn/longhorn-manager/blob/master/controller/setting_controller.go#L339
but `funcPreupdate` did not cleanup the service/endpoint here

2. disable storage network for rwx volume
Calling https://github.com/longhorn/longhorn-manager/blob/master/controller/setting_controller.go#L373
but early return on https://github.com/longhorn/longhorn-manager/blob/master/controller/setting_controller.go#L1006
so the service/endpoint cleanup skip

It causes the ClusterIP of service to keep `None` and the nfs endpoint of sharemanager to be incorrect.

## Workaround and Mitigation

Delete the PVC related service.

## Possible Solution

It looks like we are not easy to ensure the cleanup is called each time `StorageNetworkForRWXVolumeEnabled` disabled/enabled.
We could try to check the current service status, and then we will know whether this service file is cleaned up or not.
If cleanup is needed, we do the cleanup. Then everything will go through as usual. WDYT?

A draft PR here:  https://github.com/longhorn/longhorn-manager/pull/3078

**Comment by derekbit** [comment]
cc @c3y1huang @james-munson  @ejweber

**Comment by james-munson** [comment]
It also seems reasonable to me to constrain the setting/clearing of storage network for RWX, since it depends on storage network already being enabled.  It should not be legal for SN/RWX to be enabled when SN is not.  That would imply checking for SN first before enabling SN/RWX, and likewise checking SN/RWX already disabled when disabling SN (or automatically disabling it as well.)

If the constraint could be guaranteed, then a method like https://github.com/longhorn/longhorn-manager/blob/555af1ed5603b2d1afe889ade722f497d5fc6750/types/types.go#L1242 would not need to exist.

**Comment by derekbit** [comment]
@Vicente-Cheng Could you update https://github.com/longhorn/longhorn/issues/9272#issuecomment-2306929579 before moving it to Ready For Testing? Thanks.

**Comment by Vicente-Cheng** [comment]
> @Vicente-Cheng Could you update [#9272 (comment)](https://github.com/longhorn/longhorn/issues/9272#issuecomment-2306929579) before moving it to Ready For Testing? Thanks.

Thanks for the reminder. Updated!

**Comment by roger-ryao** [comment]
**Verified on master-head 20230827**

- longhorn master-head https://github.com/longhorn/longhorn/commit/ecd107cf1e4f799df639ee63bd48f1d1c2292242
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/c05390b40d0610df8c1c875f0e607dbd5aced34e

**The test steps**
https://github.com/longhorn/longhorn/issues/9272#issuecomment-2306929579

**Result passed**

The endpoint of the share manager is correct. This can be verified through the following steps:

1. Describing the ShareManager resource
`kubectl describe sharemanager vol-0 -n longhorn-system`
```yaml
Spec:
  Image:  longhornio/longhorn-share-manager:master-head
Status:
  Endpoint:  nfs://10.43.252.6/vol-0
  Owner ID:  ip-10-0-1-120
  State:     running
Events:      <none>
```
2. Examining the Service details
`kubectl get services vol-0 -n longhorn-system -oyaml`
```yaml
spec:
  clusterIP: 10.43.252.6
  clusterIPs:
  - 10.43.252.6
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
    targetPort: 2049
  selector:
    longhorn.io/managed-by: longhorn-manager
    longhorn.io/share-manager: vol-0
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
