### ISSUE TITLE
[BUG] [Backupstore] Need to close the reader after downloading files for the Azure backup store driver.

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#9281]
## Describe the bug

https://github.com/longhorn/backupstore/blob/ffeeac71ef8169bb644769533649cd6bc6903af6/azblob/azblob.go#L193-L199

After `io.Copy`, it should close the reader.

```suggestion
rc, err := s.service.getBlob(path)
    if err != nil {
    return err
}
defer rc.Close()
```

### Sub Tasks: update dependency

- [x] `longhorn-engine`
- [x] `backing-image-manager`
- [x] `longhorn-instance-manager`
- [x] `longhorn-manger`

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-manager 52b7383) following [the test steps](https://github.com/longhorn/longhorn/issues/9281#issuecomment-2305989959).
