### ISSUE TITLE
Support k8s zone and region tags for replica placement

### ISSUE THREAD

**Issue by dsargent3220** [longhorn/longhorn#929]
We are currently using Rook / Ceph and use the support for auto building the crush maps based off the failure-domain.beta.kubernetes.io/region and failure-domain.beta.kubernetes.io/zone labels we add to our nodes.
Docs for these can be found here
https://kubernetes.io/docs/setup/best-practices/multiple-zones/

We use this to tell Rook which of our nodes are in which fault zones on our campus.  We have four fault zones and want it to spread the four replicas out to these two fault zones evenly, this way we never have two replicas in the same fault zone.

Simplified Example: 
NODE:       ZONE LABEL:
node 1            rack 1
node 2            rack 2
node 3            rack 3
node 4            rack 4
node 5            rack 1
node 6            rack 2
etc.

@yasker   I was at your Longhorn presentation at Kubecon and mentioned these, you asked me to create an issue here.

**Comment by yasker** [comment]
@dsargent3220 Thanks for following up. Longhorn should able to make use of the fault zones as well since it's a Kubernetes concept.

**Comment by yasker** [comment]
Seems `failure-domain.beta.kubernetes.io` has been replaced by `topology.kubernetes.io` in Kubernetes v1.17. https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#topologykubernetesioregion

**Comment by yasker** [comment]
@smallteeths We will need UI to display the zone and region information in the UI as well.

**Comment by meldafrawi** [comment]
Validation: 

Longhorn UI version: `wangsiye/longhorn-ui:c97c05a`

**Steps to test:**
_1.1. Case (k8s < v1.17):_
- Create 3 node k8s v1.16 cluster 
- Deploy Longhorn
- Label node01 & node03 with `failure-domain.beta.kubernetes.io/zone=lh-zone1`
- Label node02 with `failure-domain.beta.kubernetes.io/zone=lh-zone2`
- Label node01, node02 & node03 with `failure-domain.beta.kubernetes.io/region=lh-region1`

_1.2. Case (k8s  >= v1.17):_
- Create 3 node k8s > v1.17 cluster 
- Deploy Longhorn
- Label node01 & node03 with `topology.kubernetes.io/zone=lh-zone1`
- Label node02 with `topology.kubernetes.io/zone=lh-zone2`
- Label node01, node02 & node03 with `topology.kubernetes.io/region=lh-region1`

> In Node page, a geo icon next to node name will appear, hovering on the icon, a tooltip will appear indicate region name and zone name. **(PASS)**

2. Create a volume with 2 replicas, and attach it to a node.
> In Volume details page, Replicas section a geo icon next to replica name will appear, hovering on the icon, a tooltip will appear indicate region name and zone name. **(PASS)**
> Replicas should be scheduled to nodes in different zones

3. Delete a replica in `lh-zone2`, repeat it few times
> New replica should be scheduled only to node02, since it's only node in `lh-zone2` **(PASS)**


4. Delete a replica in `lh-zone1`, repeat it few times
> New replica should be scheduled only to node01 or node03  **(PASS)**


5. Scale volume replicas = 3
> Replicas should be scheduled to both 3 nodes **(PASS)**

6. Scale volume replicas to 4
> Replicas should be scheduled without issues (soft anti-affinity)
