### ISSUE TITLE
[BUG] Longhorn not upgrade volume to 1.7.0 from 1.6.2

### ISSUE THREAD

**Issue by baptiste-fourmont** [longhorn/longhorn#9293]
## Describe the bug

Longhorn not upgrade volume to 1.7.0

## To Reproduce

Update with helm to 1.7.0 (helm upgrade)

Engine image is fully deployed on all ready noded to longhorn v1.7.0:
- Latest Longhorn Version: 1.6.2
- Stable Longhorn Versions: v1.3.3,v1.4.4,v1.5.5,v1.6.2
- Current Longhorn Version: v1.7.0
- Default Engine Image: longhornio/longhorn-engine:v1.7.0

## Expected behavior

PV  should upgrade to 1.7.0 by Upgrade Checker automatically

## Environment

 - Longhorn version: 
 - Impacted volume (PV): All
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K8 Legacy
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: RHEL
   - Kernel version: 
   - CPU per node: 8
   - Memory per node: 16
   - Disk type (e.g. SSD/NVMe/HDD): NVME
   - Network bandwidth between the nodes (Gbps): 1Gi
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 30

**Comment by derekbit** [comment]
cc @mantissahz

**Comment by derekbit** [comment]
According to the [document](https://longhorn.io/docs/1.7.0/references/settings/#enable-upgrade-checker), it only periodically checks latest version and notifies users. Anything I missed?  @mantissahz 
```
Upgrade Checker will check for a new Longhorn version periodically. When there is a new version available, it will notify the user in the Longhorn UI.
```

**Comment by mantissahz** [comment]
Hi @baptiste-fourmont,

As @derekbit mentioned, the Upgrade Checker is responsible only for determining whether a new version exists.

I believe what you want is the [automatic engine upgrade](https://longhorn.io/docs/1.7.0/deploy/upgrade/auto-upgrade-engine/).

**Comment by baptiste-fourmont** [comment]
Thanks you. 

I have just changed automatic engine upgrade to 1.

Its worked.

Thanks you

**Comment by derekbit** [comment]
Thanks @mantissahz
