### ISSUE TITLE
[BUG] Longhorn RWX performance suddenly significantly degraded

### ISSUE THREAD

**Issue by CyanCode** [longhorn/longhorn#9297]
## Describe the bug

Over the past few days performance of longhorn on RWX volumes on our cluster have been _significantly_ degraded without anything changing. I've tested the network speed between nodes and everything looks normal there but for some reason reads/writes to the RWX longhorn volume are very slow.

Here are some metrics collected by prometheus. As you can see the read/write throughput and iops are staggeringly low (e.g. `10.24 kb/s` read throughput at its _maximum_)
![image](https://github.com/user-attachments/assets/2be0226a-667f-4ed3-ac02-ab512b290993)

Longhorn is mounted on a Hetzner volume and this PVC has only one replica. Here are some performance test:

`time dd if=/dev/zero of=/mnt/HC_Volume_36503336/test_file count=1000`
```
1000+0 records in
1000+0 records out
512000 bytes (512 kB, 500 KiB) copied, 0.00140682 s, 364 MB/s

real 0m0.004s
user 0m0.003s
sys 0m0.000s
```

I also ran a test against 1GB of data

`time dd if=/dev/zero of=/mnt/HC_Volume_36503336/test_file bs=1M count=1024 conv=fdatasync`
```
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 5.73744 s, 187 MB/s

real 0m5.739s
user 0m0.000s
sys 0m0.809s
```

And here's a test against iozone which provides more detailed metrics

```
Record Size 1 kB
        File size set to 1048576 kB
        Command line used: iozone -t1 -i0 -i2 -r1k -s1g /mnt/HC_Volume_36503336/tmp
        Output is in kBytes/sec
        Time Resolution = 0.000001 seconds.
        Processor cache size set to 1024 kBytes.
        Processor cache line size set to 32 bytes.
        File stride size set to 17 * record size.
        Throughput test with 1 process
        Each process writes a 1048576 kByte file in 1 kByte records

        Children see throughput for  1 initial writers  =  688389.31 kB/sec
        Parent sees throughput for  1 initial writers   =  137047.24 kB/sec
        Min throughput per process                      =  688389.31 kB/sec
        Max throughput per process                      =  688389.31 kB/sec
        Avg throughput per process                      =  688389.31 kB/sec
        Min xfer                                        = 1048576.00 kB
```

## Expected behavior

RWX volumes continue operating as they usually have before the degraded performance.

## Support bundle for troubleshooting

[supportbundle_923d21e3-f45c-43c2-a12d-a852ca4553e2_2024-08-24T19-02-27Z.zip](https://github.com/user-attachments/files/16737735/supportbundle_923d21e3-f45c-43c2-a12d-a852ca4553e2_2024-08-24T19-02-27Z.zip)

## Environment

Longhorn version:
Impacted volume (PV): pvc-3deb18f2-2fca-43c4-8f75-d5b83ab79c9d
Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher catalog app
Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
Number of control plane nodes in the cluster: 2
Number of worker nodes in the cluster: 2
Node config
OS type and version: Ubuntu 20.04.6 LTS
Kernel version: 5.15.0-88-generic
CPU per node: 8
Memory per node: 16
Disk type (e.g. SSD/NVMe/HDD): SSD
Network bandwidth between the nodes (Gbps):
Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Hetzner
Number of Longhorn volumes in the cluster: 8

**Comment by derekbit** [comment]
The data locality of the RWX volume `pvc-3deb18f2-2fca-43c4-8f75-d5b83ab79c9d` is not an issue, because the engine and replica are both on `worker1` node. 

Can you
- Access the share-manager pod `share-manager-pvc-3deb18f2-2fca-43c4-8f75-d5b83ab79c9d`
  - check the CPU and memory consumption of the nfs-ganesha and other processes
- Access the instance-manager pod `instance-manager-71ab8c16cd572950a7d2783d60292f96`
  - check the CPU and memory consumption of the replica and engine processes

**Comment by derekbit** [comment]
cc @james-munson  @PhanLe1010 @ejweber @shuo-wu

**Comment by derekbit** [comment]
Also cc @Vicente-Cheng

**Comment by PhanLe1010** [comment]
@CyanCode  Is it RKE1 or RKE2?

**Comment by CyanCode** [comment]
> @CyanCode Is it RKE1 or RKE2?

RKE1

**Comment by PhanLe1010** [comment]
Thanks @CyanCode 

May I ask if you are using Rancher monitoring to collect this graph. If yes, which dashboard inside Rancher monitoring is that? 
![image](https://github.com/user-attachments/assets/22834d6a-245e-4aeb-882f-355e93c803ff)

**Comment by CyanCode** [comment]
Its a graph I imported from here https://grafana.com/grafana/dashboards/16888-longhorn/
Those 4 panels you see are custom panels I created that have the following queries:

- `sum(rate(longhorn_volume_write_throughput[5m]) / (1024 * 1024))  by (pvc)`
- `sum(rate(longhorn_volume_read_throughput[5m]) / (1024 * 1024))  by (pvc)`
-  `sum(rate(longhorn_volume_write_iops[5m]))  by (pvc)`
- `sum(rate(longhorn_volume_read_iops[5m])) by (pvc)`

**Comment by PhanLe1010** [comment]
OK. Thanks @CyanCode 

I think have an idea of a potential misunderstanding about these graphs. Doing some some more testing in my lab evn. Will post a follow up soon

**Comment by CyanCode** [comment]
Thanks @PhanLe1010 I appreciate it

**Comment by PhanLe1010** [comment]
Not too slow. It looks good enough. 

Now can you try to intensify the nodes of mc-server pods by matching the pod yaml when you trigger a FTP transfer? Then repeat the test https://github.com/longhorn/longhorn/issues/9297#issuecomment-2309028040 on these nodes?

**Comment by CyanCode** [comment]
In other words repeat the test on one of the nodes that is running an mc-server pod while simultaneously running an FTP transfer?

**Comment by PhanLe1010** [comment]
Yes, I am thinking so

**Comment by CyanCode** [comment]
So this is odd the pod won't even start. Its pending before switching to terminating

![image](https://github.com/user-attachments/assets/472ca53b-b631-4ffe-92ff-117d098f0b32)

**Comment by PhanLe1010** [comment]
Is there a taint on the node `worker-hyssagx1`?

**Comment by CyanCode** [comment]
Nope, no taints on the node. I can exec into one of the other pods thats currently running (e.g. the mc-server pod) and run the dd command if that helps?

**Comment by PhanLe1010** [comment]
I think that works too

**Comment by PhanLe1010** [comment]
> Nope, no taints on the node. I can exec into one of the other pods thats currently running (e.g. the mc-server pod) and run the dd command if that helps?

Oh. Did you delete the pod test pod before recreate a new one with the same name? If not, it might be the cause

**Comment by CyanCode** [comment]
> > Nope, no taints on the node. I can exec into one of the other pods thats currently running (e.g. the mc-server pod) and run the dd command if that helps?
> 
> Oh. Did you delete the test pod before recreate a new one with the same name? If not, it might be the cause

I did, yep

And heres the results

dd if=/data/testfile of=/dev/null bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 4.12989 s, 260 MB/s

**Comment by PhanLe1010** [comment]
It looks good! So far, I don't see any signal that this is related to Longhorn.


When you do the FTP transfer, we you downloading the file to your local machine? If yes, is there any chance of the connection between you and the cluster being slow?

**Comment by CyanCode** [comment]
> It looks good! So far, I don't see any signal that this is related to Longhorn.
> 
> When you do the FTP transfer, we you downloading the file to your local machine? If yes, is there any chance of the connection between you and the cluster being slow?

I am but I tested my upload/download from that same host and have pretty good download speeds from there

![image](https://github.com/user-attachments/assets/b62563ca-e6c7-4724-8b81-6d9065b69845)

**Comment by PhanLe1010** [comment]
So looks like the FTP transfer speed should be capped at 11.5 MB/s (cannot reach the 100x MiB/s as expected at [link](https://github.com/longhorn/longhorn/issues/9297#issuecomment-2309022292)) ?

That being said, yeah 11.5MB/s is still much bigger than the 25KB/s.

Can you try to download a random file from a `mc-server pod` by `kubectl cp <namespace>/<pod-name>:<path-in-pod> <local-destination-path>` to see how long it takes?

**Comment by CyanCode** [comment]
> So looks like the FTP transfer speed should be capped at 11.5 MB/s (cannot reach the 100x MiB/s as expected at [link](https://github.com/longhorn/longhorn/issues/9297#issuecomment-2309022292)) ?
> 
> That being said, yeah 11.5MB/s is still much bigger than the 25KB/s.
> 
> Can you try to download a random file from a `mc-server pod` by `kubectl cp <namespace>/<pod-name>:<path-in-pod> <local-destination-path>` to see how long it takes?

Sure, one moment

**Comment by CyanCode** [comment]
So the file I'm trying to copy is 85 mb but kubectl continues to fail the copy with

```
Dropping out copy after 0 retries
error: unexpected EOF
```

after a few seconds. Interestingly I saw similar behavior with the FTP server where it would attempt to download, lose connection, retry the connection, start, fail, until finally it was able to "stick" after a few attempts.

**Comment by PhanLe1010** [comment]
So looks like there is a network issue from k8s to the local machine indeed. Do you have a VM on Hetzner which is outside of the cluster and try to do `kubectl cp` test again?

**Comment by CyanCode** [comment]
I don't but I can spin one up, one moment

**Comment by PhanLe1010** [comment]
cc @Vicente-Cheng @ejweber @derekbit any idea to troubleshooting outbound network from K8s cluster (CNI layer, loadbalacing , ingress controller, ...)?

**Comment by CyanCode** [comment]
Alright I tested the download command from a VPS in hetzner that's outside the cluster and it succeeded every time ~1-3s. I'm going to try unlinking it from the private network incase its communicating that way.

**Comment by PhanLe1010** [comment]
Can you also try to install the FTP client on the newly created VPS and try to trigger an FTP transfer to see if it is fast?

**Comment by CyanCode** [comment]
Unlinked the private network and its taking 2-3 seconds longer but every download is succeeding just fine.

**Comment by PhanLe1010** [comment]
Thank you! 

Can you also try to install the FTP client on the newly created VPS and try to trigger an FTP transfer to see if it is fast?

**Comment by PhanLe1010** [comment]
Or maybe something like `wget ftp://username:password@SERVERNAME/directory/file` on the new VPS

**Comment by CyanCode** [comment]
> Or maybe something like `wget ftp://username:password@SERVERNAME/directory/file` on the new VPS

SFTP download on the new VPS was super fast 

![image](https://github.com/user-attachments/assets/181d1771-9439-44b8-a2a1-77955ffb1b68)

**Comment by PhanLe1010** [comment]
Cool. So the root cause is the networking between the local machine and Hetzner datacenter. 

Maybe buying a new router or switching the internet provider would help :)))) (Just kidding on this part)

**Comment by CyanCode** [comment]
> Cool. So the root cause is the networking between the local machine and Hetzner datacenter.
> 
> Maybe buying a new router or switching the internet provider would help :)))) (Just kidding on this part)

Haha yeah what's odd is all customers are experiencing something similar but I'm hearing its worse for some than others. Maybe something weird going on in Hetzner's edge services?? At this point though its clear that its time to reach out to Hetzner. Thank you so much for your help here its been a mess trying to figure out where this is coming from and you've helped narrow my search.

**Comment by derekbit** [comment]
@CyanCode 
Feel free to reopen the issue if needed. Thank you.

**Comment by CyanCode** [comment]
> @CyanCode Feel free to reopen the issue if needed. Thank you.

Thanks again for the help here, I've responded to that original reddit thread and have updated the description to point out that this wasn't Longhorn's fault (I would update the title if I could but I'm sure people will read the first line of the description and understand).

Also the issue was identified as a [bug in Hetzner's infrastructure](https://www.reddit.com/r/hetzner/comments/1eydzlv/comment/ljdpapu/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button), thanks for helping me solve the mystery.

![image](https://github.com/user-attachments/assets/1d939435-17f5-4019-9444-69acf1694b69)
