### ISSUE TITLE
[BUG] error logs appeared in uninstallation job

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#9303]
## Describe the bug

According to manual test case [Uninstallation Checks](https://longhorn.github.io/longhorn-tests/manual/pre-release/uninstallation/uninstallation-checks/), there should be no error in uninstallation job(pod)

```
2. Check the logs of the job longhorn-uninstall, make sure there is no error.
```
However there are error logs in the uninstall pod below:
- master
```bash
> kl logs longhorn-uninstall-s88ft | grep error
time="2024-08-26T01:10:31Z" level=warning msg="Failed to uninstall" func="controller.(*UninstallController).handleErr" file="uninstall_controller.go:293" controller=longhorn-uninstall error="failed to delete nodes: failed to mark for deletion: nodes.longhorn.io \"ip-172-31-83-204\" not found"
time="2024-08-26T01:10:31Z" level=warning msg="Failed to uninstall" func="controller.(*UninstallController).handleErr" file="uninstall_controller.go:293" controller=longhorn-uninstall error="failed to delete instance managers: failed to mark for deletion: instancemanagers.longhorn.io \"instance-manager-08f869dd142b1d51da0d3df74f8aaddb\" not found"
```
- v1.7.0
```bash
> kl logs longhorn-uninstall-ffqln | grep error
time="2024-08-26T01:26:11Z" level=warning msg="Failed to uninstall" func="controller.(*UninstallController).handleErr" file="uninstall_controller.go:293" controller=longhorn-uninstall error="failed to delete instance managers: failed to mark for deletion: instancemanagers.longhorn.io \"instance-manager-1d6ccaba55264b58f0789471999c929f\" not found"
```

In the end, the uninstall complete, longhorn CRDs all removed, namesapce terminated successfully.

## To Reproduce

Use kubectl to uninstall longhorn master, v1.7.0

## Expected behavior

No error appeared in uninstall job log or modify the test plan

## Support bundle for troubleshooting

N/A

## Environment

 - Longhorn version:  master, v1.7.0
 - Impacted volume (PV): N/A
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: SUSE Linux Enterprise Server 15 SP6
   - Kernel version: 6.4.0-150600.23.17-default  
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS

## Additional context

N/A

## Workaround and Mitigation

N/A

**Comment by derekbit** [comment]
@ChanYiLin Can you help check the error log? Thanks.

**Comment by ChanYiLin** [comment]
This is actually not a bug. The logs are quite misleading.
The installation process keeps reconciling and deleting all the resources by
1. listing all the CRs
2. delete all the CRs
```
failed to delete instance managers: failed to mark for deletion: instancemanagers.longhorn.io \"instance-manager-08f869dd142b1d51da0d3df74f8aaddb\" not found 
```
The log indicates that the process failed to delete the CR because it could not be found.
Take the instance-manager CR as an example: it has an ownerReference to a Node. This means that when the Node is deleted, the instance-manager CR will also be deleted. Consequently, a race condition may occur where the installation process lists the instance-managers but fails to call the deletion API due to a "not found" error. In reality, these instance-managers are deleted immediately afterward by Kubernetes garbage collection, as the Nodes are already deleted.

For this issue, we don't need to fix any bug
but just ignore the not found error when printing the error.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn `v1.8.0-dev-20240825`, perform below command to uninstall longhorn, did not find word `error` appeared in uninstallation job logs

```bash
kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/master/uninstall/uninstall.yaml
kubectl get job/longhorn-uninstall -n longhorn-system -w
```
logs
```bash
> kl get pods
NAME                          READY   STATUS      RESTARTS   AGE
longhorn-ui-9d7b4bfc6-8zw55   1/1     Running     0          25m
longhorn-ui-9d7b4bfc6-7kpvm   1/1     Running     0          25m
longhorn-uninstall-msrx7      0/1     Completed   0          113s
>
> kl logs longhorn-uninstall-msrx7 | grep error
>
```

**Comment by chriscchien** [comment]
Reopen this ticket as using master-head images test again, still can see error log appered in uninstall pod.
```bash
> kl get pods
NAME                           READY   STATUS      RESTARTS   AGE
longhorn-ui-77757fcdfb-p5llz   1/1     Running     0          2m59s
longhorn-ui-77757fcdfb-bmvkc   1/1     Running     0          2m59s
longhorn-uninstall-hwbxp       0/1     Completed   0          83s
>
> kl logs longhorn-uninstall-hwbxp | grep error
time="2024-08-26T12:07:11Z" level=warning msg="Failed to uninstall" func="controller.(*UninstallController).handleErr" file="uninstall_controller.go:293" controller=longhorn-uninstall error="failed to delete instance managers: instancemanagers.longhorn.io \"instance-manager-6d195cf9767afe0ae413a88033cc21bf\" not found"
```

**Comment by derekbit** [comment]
I see.
@ChanYiLin Nee to clean up `err`.

https://github.com/longhorn/longhorn-manager/blob/master/controller/uninstall_controller.go#L912

This might be better.
```
			if errDelete = c.ds.DeleteInstanceManager(im.Name); errDelete != nil {
				if datastore.ErrorIsNotFound(errDelete) {
					log.Info("InstanceManager is not found")
				} else {
					err = errors.Wrap(errDelete, "failed to mark for deletion")
					return
				}
			} else {
				log.Info("Marked for deletion")
			}
```

**Comment by ChanYiLin** [comment]
## Pre Ready-For-Testing Checklist
* [ ] Where is the reproduce steps/test steps documented?
The reproduce steps/test steps are at:
     - Steps:
         - should not have not found error in the installation logs (try 10 times, it is a flaky issue)

PRs:
- https://github.com/longhorn/longhorn-manager/pull/3107

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-manager/commit/1bbd143608bd3c875b28c11779fd4cb5ec812868)

Uninstall longhorn master several times, did not find `error` appeared in uninstall job log.
