### ISSUE TITLE
[BUG] longhorn manager tries to connect to a non-existing pod address. 

### ISSUE THREAD

**Issue by batulziiy** [longhorn/longhorn#9308]
## Describe the bug

 I have a k3s cluster consists of 5 node and this morning I had to restart one (node5) of the nodes since it became unresponsive. Before I did restart, noticed that the node1 had a quite high cpu consumption (100%), though even after restart cpu consumption was still at 100%. So I made a quick investigation and found that longhorn-manager ran on the node1 was still trying to communicate with the longhorn-manager of the node4, which had already been deleted during the restart. 
Is there anyway to safely fix the issue? I saw the same issue was reported by someone [here](https://github.com/longhorn/longhorn/issues/5580)

## Expected behavior

 Expect the longhorn-manager to establish connection with the new address. 

## Environment

 - Longhorn version: 1.4
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.25.4+k3s1
   - Number of control plane nodes in the cluster: 5
   - Number of worker nodes in the cluster: 5
 - Node config
   - OS type and version: OEL 9
   - Kernel version: 5.15.0-5.76.5.1.el9uek.x86_64
   - CPU per node: 48
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD): NVMe
   - Network bandwidth between the nodes (Gbps): 10G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 58

## Workaround and Mitigation

![longhorn-manager](https://github.com/user-attachments/assets/0515b266-5dc3-4d25-9ce9-fe6bba30aee5)

**Comment by james-munson** [comment]
Looks the same, as the image shows frequent traffic to port 8500.  
As a quick workaround, it should be safe to restart the longhorn-manager pod on node1.

**Comment by james-munson** [comment]
Please grab a support bundle before restarting, if that is possible.

**Comment by batulziiy** [comment]
Thanks for your help, after reboot the cpu consumption dropped back to normal level and still working normal after 8 hours. I forgot to grab the support bundle before restarting, sorry. Everything is good for now, thanks a million.
