### ISSUE TITLE
Use Previous PVC by default

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#932]
The original PVC is very likely to be used when restoring from a backup. At least, for the few hundred volumes that we are using. Unless restored volumes are usually _not_ using the same PVC?

![image](https://user-images.githubusercontent.com/28725423/70225829-ca13b100-171d-11ea-8fc3-367769cd333c.png)

**Comment by yasker** [comment]
It makes sense. We can default to `Use previous PVC` if possible. Of course the user can still uncheck the box.

**Comment by ainiml** [comment]
> It makes sense. We can default to `Use previous PVC` if possible. Of course the user can still uncheck the box.

and they can change the name in the text box as well. Pre-populating is mostly for user experience

**Comment by meldafrawi** [comment]
Validation: **Partially Failed**

- Longhorn UI image: `wangsiye/longhorn-ui:9787bfb`

Steps to test:
  - Create a pod using a volume using:
`kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/pvc.yaml`
  - Record PVC name.
  - Create a volume backup.
  - Delete pod and volume along with PV/PVC using:
`kubectl delete -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/pvc.yaml`
  - Restore the volume from backup, click `Use Previous Name`, and click `OK`
  - In volume page, for one volume, using the Operation menu on the right, click `Create PV/PVC`
  > Expected result: `Use Previous PVC` checkbox should be marked by default. **(PASS)**
  > Expected result: PVC name in `PVC Name` field should match the recorded PVC name
  - Uncheck `Use Previous PVC` checkbox.
  >  Expected result: `PVC Name` and `Namespace` fields should be cleared.  **(FAILED)**
   Error: `Namespace` field only is cleared
  - Click OK.
  > Expected result: a new PV/PVC will be created with specified names, In volume page `PV/PVC` field status will be `Bound`  **(PASS)**

**Comment by meldafrawi** [comment]
Validation: **Passed**

Longhorn UI version: `wangsiye/longhorn-ui:d629ffe`
