### ISSUE TITLE
Allow restore all backups - UI 

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#933]
A `select all` option, and a big `Restore` button.

This restores the latest backup with the Volume Name as the name of the restored volume

![image](https://user-images.githubusercontent.com/28725423/70295159-f4b04900-17b3-11ea-989c-388426110aa3.png)

Coupled with Batch PVC creation, this will make restoring a cluster only 4 clicks.

**Comment by yasker** [comment]
Batch operation is a good idea.

Two things we need to add:
1. Add `Restore Latest Backup` option to each backup volume, which should pick up the latest backup and restore it.
2. Add batch operation `Restore Latest Backup` button and multiselection

**Comment by meldafrawi** [comment]
Validation: **PASSED**

- Longhorn UI image: `wangsiye/longhorn-ui:9787bfb`

Steps to test:
  - Create a StatefulSet using
`kubectl apply  -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml`
  - Scale StatefulSet up to `3` using `kubectl scale statefulset  web  --replicas=3`
  - Write some data to each volume
  - Compute checksum data check some (md5sum-1)
  - Create backup for each Longhorn volume. (backup-1)
  - Write some data to each volume
  - Compute checksum data check some (md5sum-2)
  - Create backup for each Longhorn volume. (backup-2)
  - Scale StatefulSet down to `0`  using `kubectl scale statefulset  web  --replicas=0`
  - Delete all 3 Longhorn volumes.
  - In Backup page,  Select two volumes, and click `Restore Latest Backup`, and check `Use Previous Name` checkbox
  - for the third volume, click `Restore Latest Backup` from the right menus, and check `Use Previous Name` checkbox
  > Expected Results: volumes will be restored and `PV/PVC` field will be `Bound`.
  - Scale StatefulSet up to `3` using `kubectl scale statefulset  web  --replicas=3`
  - Check the data inside the 3 volumes,
  > Expected Results: volumes should be restored from the latest backup `backup-2`data check sum should match `md5sum-2`.
