### ISSUE TITLE
Allow opening backups in new tabs - UI

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#934]
There's no way to remember which backup you just restored (unless we had https://github.com/longhorn/longhorn/issues/933 and could just let it restore all of it, if it doesn't exist)

![Screenshot from 2019-12-05 23-39-01](https://user-images.githubusercontent.com/28725423/70296442-ab162d00-17b8-11ea-8df1-4f1676e73dfd.png)

Opening them in tabs, allows you to know which backups you have already restored. You can just close the tab, and move on to the next tab open with another backup to restore.

**Comment by yasker** [comment]
I didn't realize that link cannot be opened in another tab. Yeah, we should support that.

**Comment by meldafrawi** [comment]
Validation: **Partially Failed**

- Longhorn UI image: `wangsiye/longhorn-ui:9787bfb`

> Expected result: clicking on backup link will open it in the same tab, and links can be opened in a new tab using right click.
> Error: clicking on backup link will always open in a new tab.

**Comment by meldafrawi** [comment]
Validation: **Passed**

Longhorn UI version: `wangsiye/longhorn-ui:d629ffe`
