### ISSUE TITLE
Default to Volume Name when restoring backup - UI

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#935]
Restoring a backup usually is restoring it to the state it was in when it was created. Using the original Volume Name make sense if you're restoring a system to what was running before.

Pre-populating the Name field with Volume Name would be immensely helpful 

![image](https://user-images.githubusercontent.com/28725423/70296828-ad2cbb80-17b9-11ea-8329-7685b2404609.png)

**Comment by yasker** [comment]
Many people might want to use a different name rather than `pvc-uuid` for easy recognition. We can add a checkbox to use the old name still if that's preferred.

**Comment by ainiml** [comment]
> Many people might want to use a different name rather than `pvc-uuid` for easy recognition. We can add a checkbox to use the old name still if that's preferred.

Longhorn storage class created the volume name, and backed it up as such.

While restoring everything Longhorn has backed up and getting the system running again, once the PVC is created, Rancher deployment will bind to it, and the system is restored. 

The only custom naming part happens in Rancher, when a new PVC is created

![image](https://user-images.githubusercontent.com/28725423/70360944-f3cbf580-184d-11ea-9928-6bfed9869f40.png)

The only part Longhorn is used, is to Select All -> Backup (the backup scheduling doesn't seem to work)

And for restoring:

1. Select All Backups -> Restore
2. Select all Volumes -> Attach
3. Select All Volumes -> Create PV/PVC

Anything more than just clicking, feels to be additional work to restore a backup

**Comment by ainiml** [comment]
@yasker 

This is what the backup view looks like (backed up by Longhorn)

![image](https://user-images.githubusercontent.com/28725423/70361483-b5cfd100-184f-11ea-939b-203cb23f3dfe.png)

and the backup detail

![image](https://user-images.githubusercontent.com/28725423/70361517-caac6480-184f-11ea-9a7c-b3dd2a520cae.png)

How does anyone know what any of these volumes used to be? 

The details are buried in the information tag

![image](https://user-images.githubusercontent.com/28725423/70361543-e7489c80-184f-11ea-94cb-b12efdd29ee9.png)

It seems the most important details is `PVC Name` and maybe `Workload Name`, which aren't shown in the UI

**Comment by yasker** [comment]
@ainiml yeah, we're adding more details about workload for backups in #883

**Comment by meldafrawi** [comment]
Validation:  **PASSED**

- Longhorn UI image: `wangsiye/longhorn-ui:9787bfb`

Steps to test:
  - Create a volume attach it to a node.
  - Create a backup
  - Delete the volume.
  - In volume details page, Restore the volume from backup.
  - Check `Use Previous Name` checkbox.
  > Expected Result: volume original will be populated to `Name` field.
  - Click `OK`.
  > Expected Result: volume will be restored with original volume name.
