### ISSUE TITLE
Allow clicking on ID, Volume, or Snapshot Name to copy

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#936]
If you could click on the strings, and it'll copy to clipboard, that would make copy and pasting easier, instead of having to highlight the name every time (unless we had https://github.com/longhorn/longhorn/issues/935 or https://github.com/longhorn/longhorn/issues/933 and it would already be populated)

![image](https://user-images.githubusercontent.com/28725423/70296593-38598180-17b9-11ea-8ac7-622ecd6b9064.png)

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI version: `wangsiye/longhorn-ui:c36c682`

Steps to test:
  - Create a volume, attach it to a node
  - Create volume backup
  - In volume backup page, Click on volume name
  - Volume name should be copied to clipboard. **(PASS)**
