### ISSUE TITLE
[BUG] new deployment fails to start longhorn-manager's

### ISSUE THREAD

**Issue by Bartman0** [longhorn/longhorn#9360]
## Describe the bug

After applying the longhorn kubectl config, the longhorn-manager's fails to start after CrashLoopBackoff

## To Reproduce

kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.7.0/deploy/longhorn.yaml

## Expected behavior

all services start running

## Environment

 - Longhorn version: 1.7.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
Client Version: v1.28.8+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8+k3s1

   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
Linux controller 5.10.0-odroid-arm64 #1 SMP Ubuntu 5.10.198-202408201246~focal (2024-08-20) aarch64 aarch64 aarch64 GNU/Linux
   - CPU per node:
   - Memory per node: 4GB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 1
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal odroid m1s

## Additional context

longhorn-manager-98hjg                      1/2     CrashLoopBackOff   5 (2m15s ago)   5m49s
longhorn-manager-jnzwr                      1/2     CrashLoopBackOff   5 (119s ago)    5m49s
longhorn-manager-rjrlp                      1/2     CrashLoopBackOff   5 (2m3s ago)    5m48s
longhorn-manager-7tp7f                      1/2     CrashLoopBackOff   5 (2m7s ago)    5m49s

last bit of log of longhorn-manager pod:

time="2024-08-31T20:33:54Z" level=info msg="Updating TLS secret for longhorn-system/longhorn-webhook-tls (count: 2): map[listener.cattle.io/cn-longhorn-admission-webhook.longhor-59584d:longhorn-admission-webhook.longhorn-system.svc listener.cattle.io/cn-longhorn-conversion-webhook.longho-6a0089:longhorn-conversion-webhook.longhorn-system.svc listener.cattle.io/fingerprint:SHA1=FDB02DEDE9F0BD9320C85469289B6D20BE27B5F5]" func="kubernetes.(*storage).saveInK8s" file="controller.go:225"
time="2024-08-31T20:33:54Z" level=debug msg="DesiredSet - No change(2) admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration /longhorn-webhook-validator for  longhorn-system/longhorn-webhook-ca" func="apply.(*desiredSet).compareObjects" file="desiredset_compare.go:262"
time="2024-08-31T20:33:54Z" level=debug msg="DesiredSet - No change(2) admissionregistration.k8s.io/v1, Kind=MutatingWebhookConfiguration /longhorn-webhook-mutator for  longhorn-system/longhorn-webhook-ca" func="apply.(*desiredSet).compareObjects" file="desiredset_compare.go:262"
time="2024-08-31T20:33:55Z" level=info msg="Started longhorn admission webhook server on localhost" func=webhook.StartWebhook file="webhook.go:47"
time="2024-08-31T20:33:55Z" level=warning msg="Failed to check endpoint https://longhorn-admission-webhook.longhorn-system.svc:9502/v1/healthz" func=webhook.isServiceAvailable file="webhook.go:78" error="Get \"https://longhorn-admission-webhook.longhorn-system.svc:9502/v1/healthz\": dial tcp 10.43.85.245:9502: connect: connection refused"
time="2024-08-31T20:33:57Z" level=info msg="admission webhook service is now accessible" func=webhook.CheckWebhookServiceAvailability file="webhook.go:63"
time="2024-08-31T20:33:57Z" level=info msg="Starting longhorn recovery-backend server" func=recovery_backend.StartRecoveryBackend file="recovery_backend.go:13"
time="2024-08-31T20:33:57Z" level=info msg="Started longhorn recovery-backend server" func=recovery_backend.StartRecoveryBackend file="recovery_backend.go:22"
time="2024-08-31T20:33:57Z" level=info msg="Recovery-backend server is running at :9503" func="server.(*RecoveryBackendServer).ListenAndServe" file="server.go:36"
W0831 20:33:57.800241       1 client_config.go:659] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2024-08-31T20:33:57Z" level=info msg="Checking if the engine upgrade path from map[ei-b0369a5d:{Version: GitCommit: BuildDate: CLIAPIVersion:0 CLIAPIMinVersion:0 ControllerAPIVersion:0 ControllerAPIMinVersion:0 DataFormatVersion:0 DataFormatMinVersion:0}] is supported" func=util.checkEngineUpgradePath file="util.go:307" newEngineClientAPIMinVersion=8 newEngineClientAPIVersion=10 newEngineControllerAPIMinVersion=4 newEngineControllerAPIVersion=5
time="2024-08-31T20:33:57Z" level=fatal msg="Error starting manager: failed checking Engine upgrade path: incompatible Engine ei-b0369a5d controller API version: found version 0 is below required minimal version 4" func=main.main.DaemonCmd.func3 file="daemon.go:94"

I tried reinstalling after deleting longhorn and deleing the name-space.
I tried regular kubectl delete commands to do that, but deleting never ends executing.

to resolve this I needed to use some modified config for deletion. which I found on the web:

sudo kubectl get namespace longhorn-system -o json > del_ns.json
# then edit del_ns.json so finalizers are removed
# run a proxy:
sudo kubectl proxy
# execute from different terminal:
curl -k -H "Content-Type: application/json" -X PUT --data-binary @del_ns.json http://127.0.0.1:8001/api/v1/namespaces/longhorn-system/finalize

the results I get when doing deletes, are:

    "status": {
        "conditions": [
            {
                "lastTransitionTime": "2024-08-31T20:45:55Z",
                "message": "All resources successfully discovered",
                "reason": "ResourcesDiscovered",
                "status": "False",
                "type": "NamespaceDeletionDiscoveryFailure"
            },
            {
                "lastTransitionTime": "2024-08-31T20:45:55Z",
                "message": "All legacy kube types successfully parsed",
                "reason": "ParsedGroupVersions",
                "status": "False",
                "type": "NamespaceDeletionGroupVersionParsingFailure"
            },
            {
                "lastTransitionTime": "2024-08-31T20:45:55Z",
                "message": "Failed to delete all resource types, 1 remaining: Internal error occurred: failed calling webhook \"validator.longhorn.io\": failed to call webhook: Post \"https://longhorn-admission-webhook.longhorn-system.svc:9502/v1/webhook/validation?timeout=10s\": service \"longhorn-admission-webhook\" not found",
                "reason": "ContentDeletionFailed",
                "status": "True",
                "type": "NamespaceDeletionContentFailure"
            },
            {
                "lastTransitionTime": "2024-08-31T20:45:55Z",
                "message": "Some resources are remaining: engineimages.longhorn.io has 1 resource instances, engines.longhorn.io has 1 resource instances, nodes.longhorn.io has 4 resource instances, volumeattachments.longhorn.io has 1 resource instances, volumes.longhorn.io has 1 resource instances",
                "reason": "SomeResourcesRemain",
                "status": "True",
                "type": "NamespaceContentRemaining"
            },
            {
                "lastTransitionTime": "2024-08-31T20:45:55Z",
                "message": "Some content in the namespace has finalizers remaining: longhorn.io in 8 resource instances",
                "reason": "SomeFinalizersRemain",
                "status": "True",
                "type": "NamespaceFinalizersRemaining"
            }
        ],
        "phase": "Terminating"
    }

what to try or do next?

**Comment by derekbit** [comment]
I cannot reproduce the issue. Can you show the results `kubectl -n longhorn-system get engineimage -o yaml`?

**Comment by Bartman0** [comment]
certainly, here it is. 
it seems some residue from v1.6.2 has been left there?
I am afraid I did some courses on k8s admin, but I can't remember seeing anything on how to really cleanup.

I attached two results, one before applying 1.7.0 again, and one after applying it again.

[engine_images.zip](https://github.com/user-attachments/files/16829743/engine_images.zip)

**Comment by Bartman0** [comment]
some additional info after looking at #5902 :

# first let's delete all of longhorn
sudo kubectl delete -f https://raw.githubusercontent.com/longhorn/longhorn/v1.7.0/deploy/longhorn.yaml
# this never ends, and keeps waiting

# the replica delete results in this:
sudo kubectl -n longhorn-system get replica | grep stopped | awk '{ print $1 }' | xargs sudo kubectl -n longhorn-system delete replica

Error from server (InternalError): Internal error occurred: failed calling webhook "validator.longhorn.io": failed to call webhook: Post "https://longhorn-admission-webhook.longhorn-system.svc:9502/v1/webhook/validation?timeout=10s": service "longhorn-admission-webhook" not found
Error from server (InternalError): Internal error occurred: failed calling webhook "validator.longhorn.io": failed to call webhook: Post "https://longhorn-admission-webhook.longhorn-system.svc:9502/v1/webhook/validation?timeout=10s": service "longhorn-admission-webhook" not found
Error from server (InternalError): Internal error occurred: failed calling webhook "validator.longhorn.io": failed to call webhook: Post "https://longhorn-admission-webhook.longhorn-system.svc:9502/v1/webhook/validation?timeout=10s": service "longhorn-admission-webhook" not found

**Comment by derekbit** [comment]
@Bartman0 
Yes, there are some v1.6.2 engine images.
Isn't it a fresh installation according to the description?

**Comment by Bartman0** [comment]
I had v1.6.2 before and removed that after experiencing problems with volumes. I removed that using the same steps but could never reinstall it. reinstalling resulted in the same issues I have now. I was hoping that a v1.7.0 install would overwrite and/or reset some stuff.

**Comment by derekbit** [comment]
> I had v1.6.2 before and removed that after experiencing problems with volumes. I removed that using the same steps but could never reinstall it. 

Do you remember how to remove it? There are some old components in your environment.
I will suggest you clean up the environment first as the doc https://longhorn.io/docs/1.6.2/deploy/uninstall/.

**Comment by Bartman0** [comment]
following the uninstall didn't work for me, either the namespace was not available or the delete processes hung just like the install. anyway, at lot of hassles, too.

at this point it was easier just to scratch the whole k3s install and redo everything.
