### ISSUE TITLE
[BUG] TooManySnapshots as soon as volume is created, Faulty status from then

### ISSUE THREAD

**Issue by Bartman0** [longhorn/longhorn#9367]
## Describe the bug

as soon as I create a volume, it gets a TooManySnapshots, and a message saying "The snapshot number threshold (100) has not been exceeded".

## To Reproduce

prepare disks and mount on /mnt/longhorn, link /var/lib/longhorn to /mnt/longhorn, install longhorn, create volume with default settings (so 250 max count for snapshots)

## Expected behavior

new empty volume without any issues

## Support bundle for troubleshooting

will add it later when this issue has been registered.

## Environment

 - Longhorn version: 1.7.0
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
 Client Version: v1.30.4+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.4+k3s1
 
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version:
   - Kernel version:
Linux controller 5.10.0-odroid-arm64 #1 SMP Ubuntu 5.10.198-202408201246~focal (2024-08-20) aarch64 aarch64 aarch64 GNU/Linux

   - CPU per node:
   - Memory per node: 4GB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 1
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal
 - Number of Longhorn volumes in the cluster: 1

**Comment by Bartman0** [comment]
support bundle is too big to upload here.

link to zip: https://we.tl/t-pDRjBeJ9u5
no secrets in there that can do any harm.

**Comment by derekbit** [comment]
> The snapshot number threshold (100) has not been exceeded

It means the number of snapshots of the volume doesn't exceed the snapshot number threshold and without any issue.

**Comment by derekbit** [comment]
`Faulted` is related to 
```
2024-09-02T23:06:11.638932210+02:00 [longhorn-instance-manager] time="2024-09-02T21:06:11Z" level=info msg="Process Manager: prepare to delete process test-r-7eb5fb93" func="process.(*Manager).ProcessDelete" file="process_manager.go:229"
2024-09-02T23:06:11.639099638+02:00 [longhorn-instance-manager] time="2024-09-02T21:06:11Z" level=warning msg="Process update: test-r-7eb5fb93: state error: errorMsg: exec: \"/host/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.7.0/longhorn\": stat /host/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.7.0/longhorn: no such file or directory" func="process.(*Process).RPCResponse" file="process.go:115"
```
Can you check if the file `/host/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.7.0/longhorn` is in your instance-manager pods?

BTW, how did you install Longhorn system?

**Comment by Bartman0** [comment]
I install using the 'kubectl apply' command

I'll check the existence of the file. 
the '/host/...' part of the path is weird, tough, '/var/lib/longhorn' is a known path, but the /host part???

**Comment by Bartman0** [comment]
all nodes show this:

$ ll /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.7.0/longhorn
-rwxr-xr-x 1 root root 30M Aug 20 06:28 /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.7.0/longhorn

seems OK, I think.

as I expected, /host/ is not something that exists on the nodes.

**Comment by Bartman0** [comment]
@derekbit any thoughts on this findings?
