### ISSUE TITLE
UI: Filter by PV or PVC Name

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#937]
There doesn't seem to be a way to see what the PV/PVC name is in Longhorn

The search function also doesn't help very much.

![image](https://user-images.githubusercontent.com/28725423/70297704-1661fe00-17bd-11ea-9d2f-d02fe508e65c.png)

![image](https://user-images.githubusercontent.com/28725423/70297660-fcc0b680-17bc-11ea-8770-683186017fef.png)

**Comment by yasker** [comment]
PV/PVC name is too long to show in the UI list. We need to keep users focus on the most important informations in the list. That's why we decided to hide it.

We can implement a filter based on both fields in #938

**Comment by yasker** [comment]
Use this issue to track filtering by PV/PVC feature.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI version: `wangsiye/longhorn-ui:c36c682`

Steps to test:
  - Create multiple volumes with PV/PVC
  - Filter using full/part of PV name  **(PASS)**
  - Filter using full/part of PVC name  **(PASS)**
