### ISSUE TITLE
[IMPROVEMENT] v2 volume supports data locality

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9371]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

We've introduced online replica rebuilding in v1.7.0, so the data locality such as `best effort` can be enabled in v1.8.0.

**Comment by derekbit** [comment]
cc @hookak @shuo-wu @c3y1huang @innobead

**Comment by derekbit** [comment]
Thanks the contribution of @hookak in https://github.com/longhorn/longhorn-manager/pull/3133

**Comment by shuo-wu** [comment]
Some discussions regarding the v2 volume data locality feature:
1. Currently, Longhorn blindly exposes a replica (head lvol) as a nvmf before adding it to an engine (RAID).
2. Compared with directly using the head lvol in an engine RAID, the nvmf introduces a significant performance drop. The drop can be 40%-50% based on @derekbit benchmark result.
3. The reason why Longhorn blindly exposes a replica as a nvmf regardless of the localness is that, Longhorn needs to launch a temp RAID on another node during live upgrade. 
4. Then the question is, do strict-local volumes need live upgrade? If NO, it means that Longhorn can bypass the nvmf layer when adding the only local replica to the engine RAID then get a huge performance gain. 
    - For v1, due to issue #9389, we disable the live upgrade as the short-term fix.
    - For v2, TBD

**Comment by DamiaSan** [comment]
> 2. Compared with directly using the head lvol in an engine RAID, the nvmf introduces a significant performance drop. The drop can be 40%-50% based on @derekbit benchmark result.

Making a brief test running fio directly over the linux block device connected to spdk, I confirm a performance drop of about 40-50%.

**Comment by DamiaSan** [comment]
> > > 2. Compared with directly using the head lvol in an engine RAID, the nvmf introduces a significant performance drop. The drop can be 40%-50% based on @derekbit benchmark result.
> > 
> > 
> > Making a brief test running fio directly over the linux block device connected to spdk, I confirm a performance drop of about 40-50%.
> 
> @DamiaSan Can you check with the upstream and see if they have any thoughts for the performance drop?

https://spdk-team.slack.com/archives/CPQCY1XCL/p1726742494543539

**Comment by roger-ryao** [comment]
**Verified on v1.8.0-dev-20241006 20231007**

- longhorn v1.8.0-dev-20241006 https://github.com/longhorn/longhorn/commit/c8d1df4ef61d62b6ba3e58b9bff332d8a1b01611


**The test steps**
https://github.com/longhorn/longhorn/issues/9371#issuecomment-2325472520
1. Enable `Replica Node Level Soft Anti-Affinity`
2. Create `v2` volume with the `best-effort` data locality setting and 3 replicas. 
3. Attach the volume to `node-2`
4. Drain `node-1` using the command `kubectl drain ryao-180-241007-w1-daedf370-d6pwt --ignore-daemonsets --delete-local-data`

**Result**

1. After drain the node, we could observed that 2 replicas are placed on the same node.

Hi @derekbit 
         I want to confirm one thing. According to https://github.com/longhorn/longhorn/issues/9585#issuecomment-2397096516, it's not allowed to create a `Strict-Local` v2 volume, right?

**Comment by roger-ryao** [comment]
After discussing with @derekbit , we identified another issue. I have created a ticket: https://github.com/longhorn/longhorn/issues/9591.

**Comment by roger-ryao** [comment]
Here is a brief summary of the issues discovered after verifying this ticket:
1. https://github.com/longhorn/longhorn/issues/9591
2. https://github.com/longhorn/longhorn/issues/9585
