### ISSUE TITLE
Search function to search everything - UI

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#938]
One of these is related to a PV called `registry`

![image](https://user-images.githubusercontent.com/28725423/70298079-69888080-17be-11ea-87fc-f4ca6e97d57f.png)

Searching `registry`, should show anything that has "registry" in the volume details.

![image](https://user-images.githubusercontent.com/28725423/70297788-588b3f80-17bd-11ea-8c58-09978306a3e0.png)

Or there should be a search option for every option (e.g. search for PV Name, PVC Name, etc.)

![image](https://user-images.githubusercontent.com/28725423/70297866-b4ee5f00-17bd-11ea-960f-25b7674535be.png)
 
The screenshot above is for `gitlab`, I have several other ones to click through to find the volume I'm looking for

**Comment by yasker** [comment]
We can implement a filter for every field. I feel it's more useful for an organized struct than search.

**Comment by ainiml** [comment]
> We can implement a filter for every field. I feel it's more useful for an organized struct than search.

Best example I think think of is similar to Android Settings Search. Instead of looking through a dozen menus and nested windows one by one, just searching for it will show what might be most relevant. 

That might be an ideal search use case

**Comment by yasker** [comment]
It's might not as useful as you might think. For example, if you want to search for `prod` in the workload name and only apply filter to that, but with search on everything you will get `prod` in the volume name, in the pvc/pv name, and in the label, etc. That why I don't think it's a good experience if you just want to have multi selections using the search. For Google or Settings in Android, you're always going to choose one of them, then that search works. But if you want to apply batch operation, search is not precise enough to help.

**Comment by ainiml** [comment]
> It's might not as useful as you might think. For example, if you want to search for `prod` in the workload name and only apply filter to that, but with search on everything you will get `prod` in the volume name, in the pvc/pv name, and in the label, etc. That why I don't think it's a good experience if you just want to have multi selections using the search. For Google or Settings in Android, you're always going to choose one of them, then that search works. But if you want to apply batch operation, search is not precise enough to help.

Perhaps

I suppose we're used to search recommendations to "just work" in the user's best interest for what they're likely looking for

(E.g. we'll throw in as many keywords needed until we find what we're looking for, instead of selecting filters from a drop down menu, because maybe we don't even know where the information is kept under)

**Comment by yasker** [comment]
I agree it's useful to search for all the fields. But I think the priority is lower than filtering the fields since the filters are needed for batch operation.

I'd like to keep this open and use #937 to track the PV/PVC filter feature.
