### ISSUE TITLE
[BUG] Can't open blockdev on pvc

### ISSUE THREAD

**Issue by wirwolf** [longhorn/longhorn#9381]
## Describe the bug

Kubernetes can not mount PVC to the pod. 
```
MountVolume.MountDevice failed for volume "pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b" : rpc error: code = Internal desc = mount failed: exit status 32 Mounting command: mount Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/2aee5e3168ae66ffb6370f8c2327cfa99670f20799afc2d02734e18ab89fd687/globalmount Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/2aee5e3168ae66ffb6370f8c2327cfa99670f20799afc2d02734e18ab89fd687/globalmount: /dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b already mounted or mount point busy. dmesg(1) may have more information after failed mount system call.

```

## To Reproduce
Deplom mrometeus operanor with pvc for grafana, prometeus and alertmanager. 
And sometimes this error happens.
I can fix this error only by removing PVC and creating a new

## Expected behavior

PVC attached to the pod normally and the pod started

## Environment

 - Longhorn version: 1.7.0
 - Impacted volume (PV): pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Vanilla Kubernetes v1.28.10
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 24.04.1 LTS
   - Kernel version: 6.8.0-41-generic
   - CPU per node: 8
   - Memory per node: 16G
   - Disk type (e.g. SSD/NVMe/HDD): SSD or NVMe(hetzner cloud vps)
   - Network bandwidth between the nodes (Gbps): 1Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal Kubespray
 - Number of Longhorn volumes in the cluster: 4

## Additional context
On dmesg log i see this error
```
[55156.642229] /dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b: Can't open blockdev
[55278.756608] /dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b: Can't open blockdev
[55400.920058] /dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b: Can't open blockdev
[55523.040555] /dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b: Can't open blockdev
[55645.189481] /dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b: Can't open blockdev
[55767.341775] /dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b: Can't open blockdev
[55889.445965] /dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b: Can't open blockdev
[56011.582131] /dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b: Can't open blockdev
[56133.715999] /dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b: Can't open blockdev
[56255.859577] /dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b: Can't open blockdev
```

Other tests
```
root@worker3:~# sfdisk  -l -- /dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b
Disk /dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b: 5 GiB, 5368709120 bytes, 10485760 sectors
Disk model: VIRTUAL-DISK    
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

also, i see the error in the UI: 
![image](https://github.com/user-attachments/assets/4c70b4ba-ec54-42b1-950c-878a29bb6cd1)

```
failed to list snapshot: cannot get client for volume pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b on node worker3.k8s: engine is not running
```

PS. I try to attach pvc in maintenance mode and i can do this only with these commands:
```
# udevadm info --name=/dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b
# udevadm trigger --action=remove /dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b
# udevadm info --name=/dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b
# fsck.ext4 /dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b
e2fsck 1.47.0 (5-Feb-2023)
/dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b: recovering journal
Setting free inodes count to 327660 (was 327669)
Setting free blocks count to 1267939 (was 1268642)
/dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b: clean, 20/327680 files, 42781/1310720 blocks
# mount /dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b /mnt
```
but after detachment, the problem not fixed

**Comment by derekbit** [comment]
Have you checked https://longhorn.io/docs/1.7.0/important-notes/#unable-to-attach-volumes-created-before-v152-and-v144?

**Comment by wirwolf** [comment]
Command output: Safe to upgrade to v1.7.0.

```
kubectl -n longhorn-system get engines.longhorn.io
```

```
pvc-4b323020-99a9-4ee1-8ad1-5de7673fc2d2-e-0   v1            running   worker3   instance-manager-b903b8ccc9c9ea7995838647bff301f3   longhornio/longhorn-engine:v1.7.0   21h
pvc-9110c94f-de6d-489c-9e64-bdc500dffce6-e-0   v1            running   worker3   instance-manager-b903b8ccc9c9ea7995838647bff301f3   longhornio/longhorn-engine:v1.7.0   87m
pvc-91f76d1b-d48b-402a-b97c-edb55f0ff8a6-e-0   v1            running   worker2   instance-manager-b82f0ab4097a85d8d396e69854864fbb   longhornio/longhorn-engine:v1.7.0   21h
pvc-9a0f12da-e1ea-4f5a-85c5-aed0e24c39ef-e-0   v1            running   worker3   instance-manager-b903b8ccc9c9ea7995838647bff301f3   longhornio/longhorn-engine:v1.7.0   18h
```

**Comment by derekbit** [comment]
OK. 
```
/dev/longhorn/pvc-7eaecbeb-ae6b-4776-97a9-c8fcaa3b7e0b already mounted or mount point busy. 
```
Please check https://longhorn.io/kb/troubleshooting-volume-with-multipath/

**Comment by wirwolf** [comment]
I apply this manual always before installing Longhorn on cluster

**Comment by derekbit** [comment]
> I apply this manual always before installing Longhorn on the cluster.

All Longhorn nodes?

> Can I try updating to 1.7.1 and check?

Sure.

**Comment by derekbit** [comment]
> I apply this manual always before installing Longhorn on the cluster. Can I try updating to 1.7.1 and check?

Do you mean https://longhorn.io/kb/troubleshooting-volume-with-multipath/?

**Comment by wirwolf** [comment]
Yes, in all worker nodes I add block ```blacklist``` before install Longhorn.

PS. On 1.7.1, the problem was reproduced.

**Comment by derekbit** [comment]
Can you provide a support bundle?

**Comment by wirwolf** [comment]
Yes. 
[supportbundle_a6c697e9-2f98-4e07-8916-d3193715ff24_2024-09-05T06-22-09Z.zip](https://github.com/user-attachments/files/16884882/supportbundle_a6c697e9-2f98-4e07-8916-d3193715ff24_2024-09-05T06-22-09Z.zip)

**Comment by wirwolf** [comment]
I Provided a support bundle and removed the comment because he has private information about the cluster

**Comment by wirwolf** [comment]
Hey, @derekbit. Do you have any news on my issue?

**Comment by derekbit** [comment]
Didn't receive the support bundle.

BTW, can you check which process is using the block device with the error message `...already mounted or mount point busy..`

**Comment by wirwolf** [comment]
@derekbit I send you an email with a support bundle in the attachment.

**Comment by PhanLe1010** [comment]
What is the name of the problematic volume @wirwolf ?

**Comment by wirwolf** [comment]
Hello @PhanLe1010. I send a support bundle to email @derekbit because bundle have many personal information(node name, ips and other)
![image](https://github.com/user-attachments/assets/ada1d188-c1cd-447e-b139-c041ae9915c3)

**Comment by PhanLe1010** [comment]
Can you also forward it to `	longhorn-support-bundle@suse.com` @wirwolf ?

**Comment by wirwolf** [comment]
@PhanLe1010 done

**Comment by grizo** [comment]
Experiencing the same issue. Also on Ubuntu 24.04.1 LTS but with Longhorn 1.7.1 and microk8s v1.30.4:
```
MountVolume.MountDevice failed for volume "authelia-v1" : rpc error: code = Internal desc = mount failed: exit status 32 Mounting command: mount Mounting arguments: -t ext4 -o defaults /dev/longhorn/authelia-v1 /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/afc5e74b435c62a943ca116a0c8cccea603c635bb21f019896b0bd703c721314/globalmount Output: mount: /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/afc5e74b435c62a943ca116a0c8cccea603c635bb21f019896b0bd703c721314/globalmount: /dev/longhorn/authelia-v1 already mounted or mount point busy. dmesg(1) may have more information after failed mount system call. 
```
dmesg:
```
[ 1920.231582] /dev/longhorn/authelia-v1: Can't open blockdev
```
No such issue on two other hosts running Ubuntu 22.04.5 LTS in my homelab once I cordon the Ubuntu 24.04.1 node.

**Comment by PeterSR** [comment]
Sorry to revive this, but I have experienced this problem many times now. Somehow it recovers by some of our frantic attempts to fix it - without it ever clearly makes sense what fixes it and with long downtime in production. 

Our nodes run Ubuntu 24.04 LTS and we have seen this happen with both Longhorn 1.7.1 and 1.8.2.

What are the actual cause and potential remedy?

**Comment by derekbit** [comment]
> Sorry to revive this, but I have experienced this problem many times now. Somehow it recovers by some of our frantic attempts to fix it - without it ever clearly makes sense what fixes it and with long downtime in production.
> 
> Our nodes run Ubuntu 24.04 LTS and we have seen this happen with both Longhorn 1.7.1 and 1.8.2.
> 
> What are the actual cause and potential remedy?

What's error message you encountered?

**Comment by PeterSR** [comment]
Same as already reported here. Describing a pod that doesn't start and I see these events:

```
Events:
  Type     Reason       Age                      From     Message
  ----     ------       ----                     ----     -------
  Warning  FailedMount  2m57s (x102 over 3h28m)  kubelet  MountVolume.MountDevice failed for volume "pvc-807b955e-532f-4cd7-b4d2-3afc4631a71f" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-807b955e-532f-4cd7-b4d2-3afc4631a71f /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/b6f758d75c8fa237e026dd2943ab43739f46cd5de533274bbe10ff81dc397914/globalmount
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/b6f758d75c8fa237e026dd2943ab43739f46cd5de533274bbe10ff81dc397914/globalmount: /dev/longhorn/pvc-807b955e-532f-4cd7-b4d2-3afc4631a71f already mounted or mount point busy.
       dmesg(1) may have more information after failed mount system call.
```

The cluster consists of 3 master nodes (no workloads) and 1 worker node. If I go to the worker and run `dmesg` I see messages like

```
[15466714.179473] /dev/longhorn/pvc-807b955e-532f-4cd7-b4d2-3afc4631a71f: Can't open blockdev
```

And I don't know where to dig from there.

**Comment by zeddD1abl0** [comment]
I am seeing a similar problem. I've been updating my cluster, and after the last set of restarts, when I upgraded Longhorn to 1.10.0, it's taking a VERY long time to recover storage, and I'm seeing the `Can't open blockdev` quite a lot. Happy to try and troubleshoot it, if I get some guidance on what you'd need.

**Comment by PeterSR** [comment]
We never really figured out what the problem was nor did we solve it directly. We suspect that it is due to `multipathd` but this [fix](https://longhorn.io/kb/troubleshooting-volume-with-multipath/) did not help on our Ubuntu 24.04 workers. What we instead did was to install Debian 13 (+ `nfs-common` and `dm-crypt`) (still using Longhorn `v1.7.2`) and now all checkmarks in Longhorn UI for each node are green:

<img width="266" height="325" alt="Image" src="https://github.com/user-attachments/assets/f4d592ca-a78f-428a-acd2-ff12659a9e51" />

We also made sure to check "Detach Manually Attached Volumes When Cordoned" in settings.

It is too early to tell if the problem is actually gone, but we haven't had any problems so far.

**Comment by derekbit** [comment]
> I am seeing a similar problem. I've been updating my cluster, and after the last set of restarts, when I upgraded Longhorn to 1.10.0, it's taking a VERY long time to recover storage, and I'm seeing the `Can't open blockdev` quite a lot. Happy to try and troubleshoot it, if I get some guidance on what you'd need.

@zeddD1abl0 Can you provide a support bundle with the issue?
