### ISSUE TITLE
[IMPROVEMENT] Restored volume or other operations should be allowed on the old and running instance-manager pods

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9383]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Currently, the v2 volumes should be detached before upgrading Longhorn as we mentioned in the official doc https://longhorn.io/docs/1.7.0/important-notes/#longhorn-system-upgrade. After upgrade, the new instance manager pods will be created, and the restored volume should be created on the new instance manager pods as well.

After supporting v2 volume live upgrade, the restored volume or other operations should be allowed on the old and running instance-manager pods.

## Additional context

https://github.com/longhorn/longhorn/issues/9380

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-manager/commit/568284782740cd840d7ed350119ca94f4733c339)

Following test [steps](https://github.com/longhorn/longhorn/issues/9383#issuecomment-2400086104), v2 volume retoration success and data intact.
