### ISSUE TITLE
Can't sort by PV/PVC

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#940]
I need to batch create PV/PVC's that are not bound

![image](https://user-images.githubusercontent.com/28725423/70318643-7d4bdb00-17ee-11ea-8ba2-dcd3148b6ef3.png)

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI version: `wangsiye/longhorn-ui:c36c682`

Steps to test:
  - Create multiple volumes.
  - Create PV/PVC for some volumes
  - Sort by PV/PVC **(PASS)**
