### ISSUE TITLE
Longhorn instance manager is leaving zombie processes

### ISSUE THREAD

**Issue by namuch** [longhorn/longhorn#941]
Longhorn 0.7.0 leaves zombie procs when volumes are attached/detached.

The following example can be observed on nodes running the longhorn instance manager.

The PPID of each proc belongs to ```longhorn-instance-manager --debug daemon --listen 0.0.0.0:8500```

```4     0  4236 24127  20   0      0     0 -      Z    ?          0:00 [sleep] <defunct>
4     0  5407 24127  20   0      0     0 -      Z    ?          0:00 [sleep] <defunct>
4     0  5872 24127  20   0      0     0 -      Z    ?          0:00 [sleep] <defunct>
4     0  8646 24127  20   0      0     0 -      Z    ?          0:00 [sleep] <defunct>
4     0  9679 24127  20   0      0     0 -      Z    ?          0:00 [sleep] <defunct>
4     0 11014 24127  20   0      0     0 -      Z    ?          0:00 [sleep] <defunct>
4     0 11718 24127  20   0      0     0 -      Z    ?          0:00 [sleep] <defunct>
4     0 14331 24127  20   0      0     0 -      Z    ?          0:00 [sleep] <defunct>
4     0 14384 24127  20   0      0     0 -      Z    ?          0:00 [sleep] <defunct>
4     0 16206 24127  20   0      0     0 -      Z    ?          0:00 [sleep] <defunct>
4     0 16233 24127  20   0      0     0 -      Z    ?          0:00 [sleep] <defunct>
4     0 17187 24127  20   0      0     0 -      Z    ?          0:00 [sleep] <defunct>
4     0 19897 24127  20   0      0     0 -      Z    ?          0:00 [sleep] <defunct>
4     0 21617 24127  20   0      0     0 -      Z    ?          0:00 [sleep] <defunct>
4     0 24606 24127  20   0      0     0 -      Z    ?          0:00 [sleep] <defunct>
4     0 25391 24127  20   0      0     0 -      Z    ?          0:00 [sleep] <defunct>
4     0 28978 24127  20   0      0     0 -      Z    ?          0:00 [sleep] <defunct>```

**Comment by yasker** [comment]
It should have been fixed in v0.7.0 engine as #795 . We've introduced `tini` as pid 1 to reap the process properly. Can you describe the reproduce steps?

**Comment by namuch** [comment]
I saw the original bug, so I was surprised when all these zombies started turning up.

In our specific test case, they are happening when workloads in Rancher are redeployed frequently to test startup container functionality.

During redeployment, the pods hang for a few minutes with `multi-attach` errors, before eventually restarting.  I don't know if this has any bearing on the matter.

**Comment by yasker** [comment]
@namuch I know there might be a lot going on, but can you briefly describe the steps? Also, are you running the command on the host or inside the instance manager container? And what command you ran?

**Comment by namuch** [comment]
To reproduce: 

- Count zombie procs on node where workload is deployed: `ps axl | grep defunct` is what I use.

- Redeploy the workload in rancher ui by either upgrading or just a simple redeploy from menu.

- Count zombie procs again on both the node the workload was originally on, and the node that workload got re-assigned to (if it was different)

In my test cases, all nodes involved in the upgrade/redeploy leaves at one (sometimes 2, but appears to be random), new zombie proc each time.

**Comment by yasker** [comment]
Thanks @namuch . I am able to reproduce the issue.

**Comment by yasker** [comment]
Fixed as a side effect of https://github.com/longhorn/longhorn/issues/880 .

Can be verified using the reproduce steps above.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

**Comment by wopl** [comment]
Running Longhorn v0.8.1 i as well get a lot of zombie processes. Running k3s on a single node.

The parent process looks as follows:
`root      6992  6402  1 05:59 ?        00:02:18 longhorn-manager -d daemon --engine-image longhornio/longhorn-engine:v0.8.1 --instance-manager-image longhornio/longhorn-instance-manager:v1_20200301 --manager-image longhornio/longhorn-manager:v0.8.1 --service-account longhorn-service-account
`
No specific action has been done... just wait to get more and more of them.
