### ISSUE TITLE
[DOC] Fix RWX no-restart claim in References/Settings

### ISSUE THREAD

**Issue by james-munson** [longhorn/longhorn#9415]
## What's the document you plan to update? Why? Please describe

The description of setting `Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly` mistakenly claims that RWX volumes will not be restarted.  For instance, to pick one, https://longhorn.io/docs/1.5.5/references/settings/#automatically-delete-workload-pod-when-the-volume-is-detached-unexpectedly.

## Additional context

In fact, when the share-manager state goes to `Error`, as it does after a share-manager pod restart or the death of the node it is running on, the volume_controller will request a remount, and the workload is restarted by kubenetes_pod_controller.

This is true in 1.5.x, 1.6.x, 1.7.0, and 1.7.1.  Auto restart of RWX workoads will no longer happen in 1.7.2 and 1.8.x after #9095 and #9290.

**Comment by chriscchien** [comment]
Hi @james-munson, 

In [v1.6.4-dev](https://longhorn.io/docs/1.6.4/references/settings/#automatically-delete-workload-pod-when-the-volume-is-detached-unexpectedly), [v1.7.2-dev](https://longhorn.io/docs/1.7.2/references/settings/#automatically-delete-workload-pod-when-the-volume-is-detached-unexpectedly) and [v1.8.0-dev](https://longhorn.io/docs/1.8.0/references/settings/#automatically-delete-workload-pod-when-the-volume-is-detached-unexpectedly) website, the conext below is still exist, do they need to be removed as well? thank you.

![image](https://github.com/user-attachments/assets/3e1b4e06-cfd1-434a-8e1f-ac87d8ce001c)

**Comment by chriscchien** [comment]
Closse this ticket as the doc updated to v1.6.4-dev
