### ISSUE TITLE
[BUG] IO on the storage pool crashes Longhorn volumes one by one

### ISSUE THREAD

**Issue by Arno500** [longhorn/longhorn#9418]
## Describe the bug

I noticed that when I was doing IO on the HDD BTRFS storage pool where Longhorn has volumes located, all the volumes will crash sooner or later (usually really fast).

## To Reproduce

1. Have a BTRFS RAID 5 pool of HDD (I would not expect the fact that is it BTRFS to break things but well)
2. Run FIO on it to easily generate IO. I used this cmdline: `fio --filename=/mnt/pool/test.deleteme --size=500GB --direct=1 --rw=randrw --bs=512k --ioengine=libaio --iodepth=8 --runtime=120 --numjobs=4 --time_based --group_reporting --name=throughput-test-job --eta-newline=1`
3. Observe all volumes failing, pods being forcefully stopped and possibly data getting corrupted due to the forced unmount
3 bis. Also observe iSCSI errors everywhere in your host logs, but of course, the pool should stay healthy and FIO should not report any write error

## Expected behavior

Even if the latency is naturally increasing and the bandwidth decreasing because of the slow nature of HDDs when doing outside IO (even sequential stuff like copying files), Longhorn/iSCSI should not unmount and break everything.

## Support bundle for troubleshooting

Sent through email: https://cloud.arnodubo.is/s/mJixtNQdXALieHr

## Environment

 - Longhorn version: 1.7.1
 - Impacted volume (PV): all
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k0s 1.29.4
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 1
 - Node config
   - OS type and version: Fedora 40 Server Edition
   - Kernel version: 6.10.7
   - CPU per node: 1 (8 cores, 16 threads)
   - Memory per node: 32GiB
   - Disk type (e.g. SSD/NVMe/HDD): HDD (system SSD)
   - Network bandwidth between the nodes (Gbps): 10Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 16

## Additional context

As said before, it is a BTRFS HDD pool (comprising 3 high-end 16TB HGST Helium drives). I, of course, checked that there was no file system corruption nor SMART or SAS errors. When not using the pool outside of Longhorn, everything is fine.
The issue has been here since the installation of Longhorn on this system (around 1.6.something) and did not improve at all with 1.7.1

I tried changing the IO scheduler on the drives of the pool from `bfq` to `kyber` without improvements.

## Workaround and Mitigation

None identified as of today.

**Comment by derekbit** [comment]
Could you provide a support bundle with the issue? Thanks.

**Comment by Arno500** [comment]
I apologize for my forgetfulness!
Sent through email and the link is this one if needed: https://cloud.arnodubo.is/s/mJixtNQdXALieHr

**Comment by PhanLe1010** [comment]
I saw many logs indicating that engine marking replica as ERR and crash it due to IO timeout like
`2024-09-07T02:21:14.695552506+02:00 [pvc-802bea5b-416d-4504-840c-845f030ad64d-e-0] time="2024-09-07T00:21:14Z" level=error msg="Setting replica tcp://10.244.0.40:10030 to ERR" func="controller.(*Controller).handleErrorNoLock" file="control.go:1175" error="tcp://10.244.0.40:10030: r/w timeout"`

It could be due to the fact that you stress testing the disk pool by using fio so it makes the HDD disks (which is already slow comparing to SSD) take a long time to complete Longhorn IO. 

Can you change this to setting to bigger value to see if it helps:
1. Engine Replica Timeout https://longhorn.io/docs/1.7.1/references/settings/#engine-replica-timeout
2. Timeout of HTTP Client to Replica File Sync Server https://longhorn.io/docs/1.7.1/references/settings/#timeout-of-http-client-to-replica-file-sync-server

**Comment by Arno500** [comment]
Hello @PhanLe1010 ,
Thanks for the suggestion. I indeed implemented those changes (`Timeout between Engine and Replica` to 20 secs and `Timeout of HTTP Client to Replica File Sync Server` to 60 seconds). It indeed took more time to Longhorn to shutdown the volume, but it still did not manage to handle even basic IO (in my case, there was only one database doing simple background reads, no intense IO nor anything). I would expect Longhorn to be able to still proceed and execute the required IOs.

I suppose this may be related to some host settings scheduling/prioritizing some IOs over others and aware that it may be outside of the scope of Longhorn, but I definitely have no idea of which mechanism could cause this. Even a simple sequential file copy blocks Longhorn, knowing that it is a pool of multiple hard drives, so it can definitely execute more than one instruction in parallel especially on a scale of 20 seconds with not too many IOs pilling up.

**Comment by PhanLe1010** [comment]
Sorry, I am not familiar with BTRFS HDD pool so couldn't help much. Is it possible to do a test to:
1. Create a LVM to group the HDD together
2. Create an ext4/xfs filesystem on top of the LVM and mount it
3. Give the mount point for Longhorn 
4. Try see if Longhorn still crash if you run fio on the mount point

**Comment by Arno500** [comment]
No worries. I did some test yesterday by switching the scheduling of the drives to "mq-deadline" and I could do some operations without crash! I did not test FIO yet though.

I will also try to switch back to "bfq" and adjust the tuning to test a bit more.

**Comment by Arno500** [comment]
I did not manage to fix `bfq` behavior by tuning the parameters. But I stumbled upon this bug report on the kernel Bugzilla: https://bugzilla.kernel.org/show_bug.cgi?id=216961
If I understand correctly, this is either a BTRFS or a BFQ bug, and nothing related to Longhorn in any way. I will let you close this bug report unless you want to add something!

**Comment by PhanLe1010** [comment]
Thanks @Arno500 . I am closing the ticket now. Feel free to reopen it if needed
