### ISSUE TITLE
Enter Key hits OK - UI

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#942]
The OK button has to be clicked, or tabbed over to

![image](https://user-images.githubusercontent.com/28725423/70362476-14e31500-1853-11ea-9c45-daf11fbb0be2.png)

**Comment by yasker** [comment]
Allow `enter key to OK` may result in user accidentally hit `enter key` after only fill one field, e.g. filled only PVC name or Namespace.

**Comment by ainiml** [comment]
> Allow `enter key to OK` may result in user accidentally hit `enter key` after only fill one field, e.g. filled only PVC name or Namespace.

The validation error already keeps the OK button from being clicked as well. I think it would work fine

![image](https://user-images.githubusercontent.com/28725423/70363043-e9612a00-1854-11ea-995b-46302c52ce48.png)

**Comment by yasker** [comment]
@ainiml Make sense. We can support that then.

**Comment by meldafrawi** [comment]
Validation: **Partially Failed**

Reproduce steps:
  - Create a volume, attach it to a node
  - In Volume Details page, click `Create Backup` and Press `Enter` Key
  > A new backup should start to be created **(FAILED)**
  - In Volume Details page, in `Recurring Snapshot and Backup Schedule` section, click `Edit`, and then click `New`
  - Click on Schedule, and `Edit Cron/use Generate Cron` Press `Enter` Key
  > new created Cron should be created **(FAILED)**

**Comment by meldafrawi** [comment]
Validation: **PASSED**

longhorn ui version: `longhornio/longhorn-ui:master`
