### ISSUE TITLE
[TEST] e2e test case `Node Disconnect And Keep Data Writing And No Replica On The Disconnected Node` expects volume to be detached after node comes back, but it remained attached

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9422]
## Describe the bug

e2e test case `Node Disconnect And Keep Data Writing And No Replica On The Disconnected Node` fails on master-head.

v1.6.x-head: https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1289/
master-head: https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1266/

According to the test steps:

```
[Documentation]    -- Manual test plan --
    ...                Disable auto-salvage.
    ...                Create a volume with 2 replicas on the 1st and the 2nd node.
    ...                Attach the volume to the 3rd node.
    ...                Keep writing data directly to the volume. (sudo dd if=/dev/urandom of=/dev/longhorn/test-1 bs=2M count=2048)
    ...                Disconnect the network of the node that the volume attached to for 100 seconds during the data writing. (sudo nohup ./network_down.sh 100)
    ...                Wait for the node back.
    ...                The volume should remain detached, and all replicas remain in ERROR state.
```

With auto-salvage disabled, after the node network is disconnected and reconnected, the volume should detach and remain in that state. However, on master-head, it transitions from `attached/unknown` to `attached/healthy` and doesn't be detached.

Need to confirm if it's the expected behavior change.

## To Reproduce

Run robot test case `-t \"Node Disconnect And Keep Data Writing And No Replica On The Disconnected Node\" -v LOOP_COUNT:1 -v RETRY_COUNT:259200`

## Support bundle for troubleshooting

v1.6.x-head: [longhorn-e2e-test-1289-bundle.zip](https://github.com/user-attachments/files/16963284/longhorn-e2e-test-1289-bundle.zip)
master-head: [supportbundle_4e274688-fabe-4b66-a95d-29d486350c45_2024-09-09T06-01-01Z.zip](https://github.com/user-attachments/files/16926063/supportbundle_4e274688-fabe-4b66-a95d-29d486350c45_2024-09-09T06-01-01Z.zip)

## Environment

 - Longhorn version: master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: sles 15-sp6
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by yangchiu** [comment]
Changed milestone to `v1.6.3` since `v1.6.x-head` has the same issue.

**Comment by derekbit** [comment]
@james-munson Could you investigate the issue? If possible, we can pu it into v1.6.3.

**Comment by derekbit** [comment]
@mantissahz  Could you investigate the issue? If possible, we can put it into v1.6.3. Thank you.

**Comment by yangchiu** [comment]
> @yangchiu Does v1.6.2 and v1.7.x have the same issue?

`v1.6.2` has the same issue.

@chriscchien Could you help quick check if anything might be affecting this test case or if the test case needs to be updated?

**Comment by chriscchien** [comment]
Manually test pass on v1.6.3-rc1 and master-head, my OS is ubuntu 24.04, I am now trying ssh into pipeline nodes to see if any thing strange.

![image](https://github.com/user-attachments/assets/c0aaf32d-97d5-4d57-bd41-643204f2e70e)

**Comment by mantissahz** [comment]
Quick updates:
1. I don't see the volumes.yaml in the SB [longhorn-e2e-test-1289-bundle.zip](https://github.com/user-attachments/files/16963284/longhorn-e2e-test-1289-bundle.zip)
2. There are six instance-manager pods in the SB [longhorn-e2e-test-1289-bundle.zip](https://github.com/user-attachments/files/16963284/longhorn-e2e-test-1289-bundle.zip)

Are these expected, @yangchiu, @chriscchien?

**Comment by chriscchien** [comment]
> Quick updates:
> 
> 1. I don't see the volumes.yaml in the SB [longhorn-e2e-test-1289-bundle.zip](https://github.com/user-attachments/files/16963284/longhorn-e2e-test-1289-bundle.zip)
> 2. There are six instance-manager pods in the SB [longhorn-e2e-test-1289-bundle.zip](https://github.com/user-attachments/files/16963284/longhorn-e2e-test-1289-bundle.zip)
> 
> Are these expected, @yangchiu, @chriscchien?

Hi @mantissahz, for question2, we will enable v2 data engine and add block device in the start of test, 6 instance-manager pod is expected

**Comment by chriscchien** [comment]
This is test case issue: 
- Manual test passed on v1.6.3-rc1 and master-head
- When running test cases, data is not wirte into volume correctly make volume behalf not expected :

In test case, looks like the `keep_writing_data` now issue `sh -c while true; do dd if=/dev/urandom of=/rootfs/dev/longhorn/e2e-test-volume-0` which `rootfs` is not exist and it may related https://github.com/longhorn/longhorn-tests/commit/68ad6ee05fe2e536bb18c377763ceea5ae486143

```bash
root     2287271  0.7  0.0   2800   768 ?        R    02:08   0:00 sh -c while true; do dd if=/dev/urandom of=/rootfs/dev/longhorn/e2e-test-volume-0 
root     2303539  0.0  0.0      0     0 ?        I    02:10   0:00 [kworker/1:0-events]
root     2304732  0.0  0.0      0     0 ?        I    02:10   0:00 [kworker/u30:2]
root     2304733  0.0  0.0      0     0 ?        I    02:10   0:00 [kworker/u30:3-events_unbound]
root     2304921  0.0  0.0      0     0 ?        I    02:10   0:00 [kworker/2:3]
root     2304972  0.0  0.0      0     0 ?        I    02:10   0:00 [kworker/1:3]
root     2307920  0.0  0.0 1406488 5120 ?        Rsl  02:10   0:00 /data/longhorn version --client-only
root     2307933  0.0  0.0      0     0 ?        Z    02:10   0:00 [dd] <defunct>
root     2307934  0.0  0.0  12928  5120 pts/1    R+   02:10   0:00 ps aux
root@ip-172-31-37-104:/home/ubuntu# dd if=/dev/urandom of=/rootfs/dev/longhorn/e2e-test-volume-0
dd: failed to open '/rootfs/dev/longhorn/e2e-test-volume-0': No such file or directory
```

**Comment by chriscchien** [comment]
Hello @c3y1huang , could you take a look on this since the 'rootfs' devuce path add in this [pr](https://github.com/longhorn/longhorn-tests/commit/68ad6ee05fe2e536bb18c377763ceea5ae486143), thank you.

Hello @yangchiu, result of negative test case which contains `Keep writing data to volume ${volume_id}` may not reliable because the data did not really written into volume

cc @roger-ryao @derekbit

**Comment by chriscchien** [comment]
Verified **pass** on longhorn-test https://github.com/longhorn/longhorn-tests/commit/2e4b3b9136b6a221ede74aa2db5967846c43c865 as test case `Node Disconnect And Keep Data Writing And No Replica On The Disconnected Node` passed on [v1.6.3-rc1](https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1371/) and [master-head images](https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1372/).
