### ISSUE TITLE
[BUG] driver name driver.longhorn.io not found in the list of registered CSI drivers

### ISSUE THREAD

**Issue by qww-ygg** [longhorn/longhorn#9424]
## Describe the bug

 driver name driver.longhorn.io not found in the list of registered CSI drivers

The triggering reason may be related to the restart of the node

k8s v1.19.4
longhorn v1.6.1

Currently, this issue only exists on the Risc-verse-k8sw-02 node

Sep 09 16:47:11 risc-verse-k8sw-02 kubelet[3240779]: I0909 16:47:11.121692 3240779 operation_generator.go:622] "MountVolume.WaitForAttach entering for volume \"pvc-e43dde24-fb36-4b0d-b59e-e09c52d94015\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-e43dde24-fb36-4b0d-b59e-e09c52d94015\") pod \"my-pod\" (UID: \"82b92b9e-b770-4122-b662-fd5824282e33\") DevicePath \"\"" pod="default/my-pod"
Sep 09 16:47:11 risc-verse-k8sw-02 kubelet[3240779]: I0909 16:47:11.124724 3240779 operation_generator.go:632] "MountVolume.WaitForAttach succeeded for volume \"pvc-e43dde24-fb36-4b0d-b59e-e09c52d94015\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-e43dde24-fb36-4b0d-b59e-e09c52d94015\") pod \"my-pod\" (UID: \"82b92b9e-b770-4122-b662-fd5824282e33\") DevicePath \"csi-d92e28e3baf54e983b41251882fc605f20e1223b9d1e8186f27e802602fa7d06\"" pod="default/my-pod"
Sep 09 16:47:11 risc-verse-k8sw-02 kubelet[3240779]: E0909 16:47:11.124948 3240779 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/csi/driver.longhorn.io^pvc-e43dde24-fb36-4b0d-b59e-e09c52d94015 podName: nodeName:}" failed. No retries permitted until 2024-09-09 16:47:43.124933662 +0800 CST m=+1504181.615999143 (durationBeforeRetry 32s). Error: MountVolume.MountDevice failed for volume "pvc-e43dde24-fb36-4b0d-b59e-e09c52d94015" (UniqueName: "kubernetes.io/csi/driver.longhorn.io^pvc-e43dde24-fb36-4b0d-b59e-e09c52d94015") pod "my-pod" (UID: "82b92b9e-b770-4122-b662-fd5824282e33") : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name driver.longhorn.io not found in the list of registered CSI drivers

**Comment by PhanLe1010** [comment]
@qww-ygg 

Can you check the health of longhorn-csi-plugin pod in the namespace longhorn-system?

It is the responsibility of that pod to register `driver.longhorn.io` CSI drivers with kubelet. The error `driver name driver.longhorn.io not found in the list of registered CSI drivers` might related to the healthy of that pods. Kubectl describe it or getting the logs from it will be useful to troubleshooting

**Comment by qww-ygg** [comment]
> @qww-ygg
> 
> Can you check the health of longhorn-csi-plugin pod in the namespace longhorn-system?
> 
> It is the responsibility of that pod to register `driver.longhorn.io` CSI drivers with kubelet. The error `driver name driver.longhorn.io not found in the list of registered CSI drivers` might related to the healthy of that pods. Kubectl describe it or getting the logs from it will be useful to troubleshooting


The service status looks fine


```
# kubectl get pod -n longhorn-system -owide

longhorn-csi-plugin-78mqt                           3/3     Running   0             15h   10.244.34.240    risc-verse-k8sw-02   <none>           <none>
longhorn-csi-plugin-8764c                           3/3     Running   0             15h   10.244.249.20    risc-verse-k8sm-01   <none>           <none>
longhorn-csi-plugin-9mrp5                           3/3     Running   0             15h   10.244.4.130     risc-verse-k8sm-03   <none>           <none>
longhorn-csi-plugin-bh5tz                           3/3     Running   0             15h   10.244.176.191   risc-verse-k8sw-03   <none>           <none>
longhorn-csi-plugin-htzpx                           3/3     Running   0             15h   10.244.121.173   risc-verse-k8sw-05   <none>           <none>
longhorn-csi-plugin-lxbmr                           3/3     Running   0             15h   10.244.160.48    risc-verse-k8sw-04   <none>           <none>
longhorn-csi-plugin-vtgfl                           3/3     Running   0             15h   10.244.93.69     risc-verse-k8sm-02   <none>           <none>
longhorn-csi-plugin-x276q                           3/3     Running   0             15h   10.244.127.147   risc-verse-k8sw-01   <none>           <none>




# kubectl logs -n longhorn-system longhorn-csi-plugin-78mqt 
Defaulted container "node-driver-registrar" out of: node-driver-registrar, longhorn-liveness-probe, longhorn-csi-plugin
I0909 08:33:58.607063       1 main.go:150] "Version" version="v1.12.0"
I0909 08:33:58.607245       1 main.go:151] "Running node-driver-registrar" mode=""
I0909 08:33:58.607250       1 main.go:172] "Attempting to open a gRPC connection" csiAddress="/csi/csi.sock"
I0909 08:34:08.608252       1 connection.go:253] "Still connecting" address="unix:///csi/csi.sock"
I0909 08:34:13.863643       1 main.go:180] "Calling CSI driver to discover driver name"
I0909 08:34:13.869204       1 main.go:189] "CSI driver name" csiDriverName="driver.longhorn.io"
I0909 08:34:13.869285       1 node_register.go:56] "Starting Registration Server" socketPath="/registration/driver.longhorn.io-reg.sock"
I0909 08:34:13.869562       1 node_register.go:66] "Registration Server started" socketPath="/registration/driver.longhorn.io-reg.sock"
I0909 08:34:13.869676       1 node_register.go:96] "Skipping HTTP server"
```

**Comment by PhanLe1010** [comment]
From the logs, looks like the registration has not been completed. This is an example when it is completed in my cluster:
```
I0828 22:59:33.540224       1 main.go:150] "Version" version="v2.11.1"
I0828 22:59:33.540334       1 main.go:151] "Running node-driver-registrar" mode=""
I0828 22:59:33.540342       1 main.go:172] "Attempting to open a gRPC connection" csiAddress="/csi/csi.sock"
2024-08-28T22:59:34.543174530Z I0828 22:59:34.542972       1 main.go:180] "Calling CSI driver to discover driver name"
2024-08-28T22:59:34.547456823Z I0828 22:59:34.547305       1 main.go:189] "CSI driver name" csiDriverName="driver.longhorn.io"
2024-08-28T22:59:34.547493814Z I0828 22:59:34.547366       1 node_register.go:56] "Starting Registration Server" socketPath="/registration/driver.longhorn.io-reg.sock"
2024-08-28T22:59:34.547690435Z I0828 22:59:34.547604       1 node_register.go:66] "Registration Server started" socketPath="/registration/driver.longhorn.io-reg.sock"
2024-08-28T22:59:34.547824226Z I0828 22:59:34.547777       1 node_register.go:96] "Skipping HTTP server"
2024-08-28T22:59:35.471963522Z I0828 22:59:35.471827       1 main.go:96] "Received GetInfo call" request="&InfoRequest{}"
2024-08-28T22:59:35.509345118Z I0828 22:59:35.509172       1 main.go:108] "Received NotifyRegistrationStatus call" status="&RegistrationStatus{PluginRegistered:true,Error:,}"
```

**Comment by ejweber** [comment]
It seems that one of the following must be happening:

- The node-driver-registrar container fails to create the registration socket at `/var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock`. (This seems unlikely, since it would probably yield an obvious error in the logs we've already seen.)
- Somehow the container and host don't share the same view of `/var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock`, so kubelet doesn't see the registration socket.
- The kubelet is looking in a different location than expected for device plugin registration sockets.
- There is some kubelet error preventing it from attempting to communicate with the Longhorn node-driver-registrar over the socket. (Probably this one would be seen in the kubelet logs.)

Can we check for `/var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock` from the host's perspective?

**Comment by qww-ygg** [comment]
> It seems that one of the following must be happening:
> 
> * The node-driver-registrar container fails to create the registration socket at `/var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock`. (This seems unlikely, since it would probably yield an obvious error in the logs we've already seen.)
> * Somehow the container and host don't share the same view of `/var/lib/kubelet/plugins_registry/`, so kubelet doesn't see the registration socket.
> * The kubelet is looking in a different location than expected for device plugin registration sockets.
> * There is some kubelet error preventing it from attempting to communicate with the Longhorn node-driver-registrar over the socket. For example, a permissions issues, etc. (Probably this one would be seen in the kubelet logs.)
> 
> Can we check for `/var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock` from the host's perspective?

Thank you, I just restarted kubelet and the service has been restored to normal
