### ISSUE TITLE
Restore Latest Backup - UI

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#943]
From the Backup view, allow an Operation option to restore the latest backup.

The saves having to go into each backup individually, when many pick the latest backup typically

![Screenshot from 2019-12-06 18-27-19](https://user-images.githubusercontent.com/28725423/70363434-59bc7b00-1856-11ea-9b0f-c90c50058863.png)

**Comment by yasker** [comment]
Yeah, this will be addressed as a part of https://github.com/longhorn/longhorn/issues/933

**Comment by ainiml** [comment]
<3
