### ISSUE TITLE
[BUG] Regression in 1.6.x-head, significant increase in execution time

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#9439]
## Describe the bug

After executing regression tests for the `1.6.3-rc1` build, we discovered that since [jenkins v1.6.x-head amd64 build 164](https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-tests-sles-amd64/164/#showFailuresLink), it has been taking approximately 20 hours to complete execution. The estimated time for completion should be 16 hours. Upon checking the test results, we noticed a significant increase in execution time for the tests `test_restore_basic` and `test_allow_volume_creation_with_degraded_availability_restore`.

|Version|  execution time |   |   |   |
|---|---|---|---|---|
|[v1.6.3-rc1 test_restore_basic](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7551/testReport/tests/test_basic/test_restore_basic_nfs_/)   | 12 min  |    |   |   |
| [v1.6.2 test_restore_basic](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7550/testReport/tests/test_basic/test_restore_basic_nfs_/)  |  7 min |    |   |   |

## To Reproduce

Rerun the jenkins job https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7559/

## Expected behavior

We need to investigate whether this is a performance issue.

## Support bundle for troubleshooting

[longhorn-tests-regression-7559-bundle.zip](https://github.com/user-attachments/files/16957834/longhorn-tests-regression-7559-bundle.zip)

## Environment

 - Longhorn version: v1.6.3-rc1
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: SLES 15-sp6
   - Kernel version:
   - CPU per node: 4
   - Memory per node: 16 
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: 1 

## Additional context

N/A

## Workaround and Mitigation

N/A

**Comment by derekbit** [comment]
@ChanYiLin Can you help investigate the slowness of the test cases? Thank you.

**Comment by yangchiu** [comment]
Based on the debug console log for https://github.com/longhorn/longhorn/issues/9455 on `v1.6.x-head` for `amd64`, a replica restoration could take more than `10` minutes to start:

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7568/consoleFull

```
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = , r.progress = 0 ... (870)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = , r.progress = 0 ... (871)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = , r.progress = 0 ... (872)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = , r.progress = 0 ... (873)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = , r.progress = 0 ... (874)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = , r.progress = 0 ... (875)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = , r.progress = 0 ... (876)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = , r.progress = 0 ... (877)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = in_progress, r.progress = 9 ... (878)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = in_progress, r.progress = 9 ... (879)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = in_progress, r.progress = 9 ... (880)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = in_progress, r.progress = 9 ... (881)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = in_progress, r.progress = 9 ... (882)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = in_progress, r.progress = 25 ... (883)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = in_progress, r.progress = 25 ... (884)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = in_progress, r.progress = 25 ... (885)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = in_progress, r.progress = 25 ... (886)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = in_progress, r.progress = 25 ... (887)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = in_progress, r.progress = 44 ... (888)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = in_progress, r.progress = 44 ... (889)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = in_progress, r.progress = 44 ... (890)
wait for volume longhorn-testvol-20ngs4-restore-14 restored r.state = in_progress, r.progress = 44 ... (891)
```

This is likely not what we expected.

**Comment by roger-ryao** [comment]
**Verified on v1.6.3-rc2 20240918**

- longhorn `v1.6.3-rc2` https://github.com/longhorn/longhorn/commit/6486816ee71ef77e660ab8538bf99031ecf452f4
- longhorn-manager `v1.6.3-rc2` https://github.com/longhorn/longhorn-manager/commit/fb8ec9ed80cd1b04f8d9fdba263e282645273957
- longhorn-manager `v1.6.3-rc2` https://github.com/longhorn/longhorn-instance-manager/commit/e50638219b9377b37e36390a318049a4ebe18b8e


**The test steps**
https://github.com/longhorn/longhorn/issues/9439#issue-2518421715

**Result Passed**

**Comment by roger-ryao** [comment]
Remove the `require/qa-review-coverage` label because the review is complete and no further action is required for this ticket.
