### ISSUE TITLE
[DOC] Add an important note about checking items before upgrade

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#9440]
## What's the document you plan to update? Why? Please describe

We should an important note about checking items before upgrade for version after v1.5.5, v1.6.2
- If there is any faulted Volume or failed Replica
- If there is any failed BackingImage

## Additional context

After v1.5.5 , we add two new fields to Replicas `LastHealthyAt` and `LastFailedAt`.
If the Volume is in failed state and all the Replicas have already failed, there is a chance that Longhorn would try to delete all Replicas after the upgrade with the following condition.

> an unintended consequence of https://github.com/longhorn/longhorn-manager/pull/2432 and the upgrade. Because healthyAt == ""  for all the replicas before the upgrade, lastHealthyAt == "" for all the replicas after the upgrade, and the new logic allows deleting replicas with lastHealthyAt == "", since this indicates they have never before been healthy. I'm not inclined to make changes here, since all of the replicas that were cleaned up were truly failed (and we have no way of knowing during the upgrade if any of these replicas had any valuable data on them.)

cc @derekbit

**Comment by derekbit** [comment]
Ref: https://github.com/longhorn/longhorn/issues/8343

**Comment by derekbit** [comment]
@COLDTURNIP Assign the issue to you. I think this ticket can help you understand the replica health and upgrade more. Feel free to reach out to @ChanYiLin or me if you need help or discussion.

cc @innobead

**Comment by chriscchien** [comment]
Verified **pass** on longhorn website master(https://github.com/longhorn/website/commit/14ad10091a259afb74f5be950273f23538a98e9d)

Below links are available on longhorn website:
- https://longhorn.io/docs/1.8.0/important-notes/#manual-checks-before-upgrade
- https://longhorn.io/docs/1.7.3/important-notes/#manual-checks-before-upgrade
- https://longhorn.io/docs/1.7.2/important-notes/#manual-checks-before-upgrade
- https://longhorn.io/docs/1.7.1/important-notes/#manual-checks-before-upgrade
- https://longhorn.io/docs/1.7.0/important-notes/#manual-checks-before-upgrade
- https://longhorn.io/docs/1.6.3/deploy/important-notes/#manual-checks-before-upgrade
- https://longhorn.io/docs/1.6.2/deploy/important-notes/#manual-checks-before-upgrade
- https://longhorn.io/docs/1.6.1/deploy/important-notes/#manual-checks-before-upgrade
- https://longhorn.io/docs/1.6.0/deploy/important-notes/#manual-checks-before-upgrade
