### ISSUE TITLE
[BUG] test case `test_support_bundle_should_not_timeout` timeout on `v1.6.x-head` for `amd64`

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9452]
## Describe the bug

Test case `test_support_bundle_should_not_timeout` timeout on `v1.6.x-head` `amd64`:

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7572/

```
kubernetes.client.exceptions.ApiException: (0)
Reason: Timeout on executing command
```
The issue doesn't occur on `v1.6.x-head` for `arm64`.

And it's also not present on `master-head`: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7573/

## Environment

 - Longhorn version: v1.6.x-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: sles 15-sp6 amd64
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
The bug is caused by the high CPU usages of instance-manager pods, and it is fixed in https://github.com/longhorn/longhorn/issues/9438.

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7596/console

**Comment by yangchiu** [comment]
Verification passed on v1.6.x-head (longhorn-instance-manage 6657d24, longhorn-engine 3bc537b). Test case `test_support_bundle_should_not_timeout` passed consecutively 5 times: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7610/
