### ISSUE TITLE
[BUG] test case `test_recurring_job` the backup recurring job's retain is not working on `v1.6.x-head` for `amd64`

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#9454]
## Describe the bug

In the test case `test_recurring_job`, the backup recurring job's retain is not working, and the expected count does not match on v1.6.x-head (amd64).

https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-tests-sles-amd64/239/testReport/junit/tests/test_recurring_job/test_recurring_job_nfs_/
```python
        # 1 completed backups from backup1
        # 2 completed backups from backup2
        # NOTE: NFS backup can be slow sometimes and error prone
        assert complete_backup_1_count == 1
>       assert complete_backup_2_count == 2
E       assert 3 == 2
E         -3
E         +2
```

https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-upgrade-tests-sles-amd64/196/testReport/junit/tests/test_recurring_job/test_recurring_job_nfs_/
```python
        # 2 from job_snap, 1 from job_backup, 1 from job_backup2, 1 volume-head
>       wait_for_snapshot_count(volume, 5)
```
## To Reproduce

execute test case `test_recurring_job`

## Expected behavior

test passed and without error

## Support bundle for troubleshooting

https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-upgrade-tests-sles-amd64/196/artifact/v1.6.x-longhorn-upgrade-tests-sles-amd64-196-bundle.zip

https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-tests-sles-amd64/239/artifact/v1.6.x-longhorn-tests-sles-amd64-239-bundle.zip

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by roger-ryao** [comment]
According to https://github.com/longhorn/longhorn/issues/8521#issuecomment-2114290605, I think there's also a chance that this situation could occur in `master-head` and `v1.7.x`, just with a lower probability of occurrence.

**Comment by mantissahz** [comment]
In [SB-196](https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-upgrade-tests-sles-amd64/196/artifact/v1.6.x-longhorn-upgrade-tests-sles-amd64-196-bundle.zip), the snapshot `backup2--6aa5acf4-130d-4b63-bb34-a2a39d271212` was not deleted after the snapshot `backup2--a5adbfa7-6064-41fa-a59e-9f15deb11da2` was created, and it might have some errors in the recurring job that created the snapshot `backup2--a5adbfa7-6064-41fa-a59e-9f15deb11da2` but we don't have the logs of the recurring job.

There are several error logs like below, but it should not block the process after I did some tests.

```txt
2024-09-10T21:44:12.521843998Z time="2024-09-10T21:44:12Z" level=warning msg="Failed to sync Longhorn snapshot" func=controller.handleReconcileErrorLogging file="utils.go:65" Snapshot=longhorn-system/backup2--a5adbfa7-6064-41fa-a59e-9f15deb11da2 controller=longhorn-snapshot error="longhorn-snapshot: failed to sync snapshot longhorn-system/backup2--a5adbfa7-6064-41fa-a59e-9f15deb11da2: handleAttachmentTicketDeletion: failed to clean up attachment: Operation cannot be fulfilled on volumeattachments.longhorn.io \"longhorn-testvol-xr91cr\": the object has been modified; please apply your changes to the latest version and try again" node=ip-10-0-2-129
```

The [PR-2105](https://github.com/longhorn/longhorn-tests/pull/2105) should fix the error.

```python
        # 1 completed backups from backup1
        # 2 completed backups from backup2
        # NOTE: NFS backup can be slow sometimes and error prone
        assert complete_backup_1_count == 1
>       assert complete_backup_2_count == 2
E       assert 3 == 2
E         -3
E         +2
```

And I can not hit another error using `longhorn-manager` 1.6.x-head image for some test runs.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-tests/commit/76b07284fde392909a63353087664880e7d6c4f7) v1.6.x(https://github.com/longhorn/longhorn-tests/commit/1400bdd949398609e195b1678871c7221fbade67)

Run test case `test_recurring_job` 40 times with both master and v1.6.x images, test result all passed.
- [master](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7608/)
- [v1.6.x](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7609/)

**Comment by roger-ryao** [comment]
Remove the `require/qa-review-coverage` label since we have related automated test cases.
