### ISSUE TITLE
docs - does restoring a backup, restore the volume schedule?

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#947]
I wasn't able to find this answer in the documentation. But saving and restoring a backup should save and restore the volume schedule too.

**Comment by yasker** [comment]
No, it doesn't.

I don't think the user would always want to stick to the same recurring policy as when volume was backed up. I think something like #467 would be more helpful.

**Comment by ainiml** [comment]
> No, it doesn't.
> 
> I don't think the user would always want to stick to the same recurring policy as when volume was backed up. I think something like #467 would be more helpful.

Argument being, "if someone did the work once before, restore it, so it doesn't have to be done again."

But we'll go with the default scheduling for now, and see how that works when it comes out.
