### ISSUE TITLE
[BUG] longhorn-manager is unable to initialize after upgrade

### ISSUE THREAD

**Issue by dopic** [longhorn/longhorn#9477]
## Describe the bug

After upgrading from version 1.4.4 to version 1.5.5, the longhorn-manager was unable to initialize, reporting errors related to the mutation webhook.

## To Reproduce

Upgrade from version 1.4.4 to version 1.5.5. Nothing else was done.

## Expected behavior

The expectation was that the Longhorn-manager would start successfully.

## Support bundle for troubleshooting

I can't generate the Support Bundle because the longhorn-manager doesn't start. Error 502 when I trying to generate it.

## Environment

 - Longhorn version: 1.4.4 
 - Impacted volume (PV): None
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Vanilla k8s - 1.28.10
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: Rocky Linux 8.10
   - Kernel version: 4.18.0-513.24.1.el8_9.x86_64
   - CPU per node: 12
   - Memory per node: 32
   - Disk type (e.g. SSD/NVMe/HDD): HDD
   - Network bandwidth between the nodes (Gbps): 1 Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 15

## Additional context

Apparently, it fails the HealthCheck:

![Captura de Tela 2024-09-16 às 17 28 50](https://github.com/user-attachments/assets/bf7c0ab8-d783-4e4e-be77-1d615a7fa7e9)

But we can see in the logs that the webhook started:

![Captura de Tela 2024-09-16 às 17 27 32](https://github.com/user-attachments/assets/39da4475-7191-44ea-87fd-fc93d0be5ed8)

Then we find this failure message when accessing the webhook:

![Captura de Tela 2024-09-16 às 17 27 45](https://github.com/user-attachments/assets/a6576cb0-5981-4d00-b3a2-d20a5eb512d9)

And longhorn-manager keeps restarting:

![Captura de Tela 2024-09-16 às 17 27 56](https://github.com/user-attachments/assets/ae4adfad-fd9c-480b-a2b4-5cd382034d7b)

We also tried to increase webhook timeout to 30s, but we had the same problem.

## Workaround and Mitigation

None

**Comment by PhanLe1010** [comment]
Hi @dopic Can you upload the logs from the 3 longhorn-manager pods?

**Comment by PhanLe1010** [comment]
Thanks @dopic 

I checked the code base and looks like the logs message `Webhook admission is ready` is doesn't not exsit in Longhorn v1.5.5 version. 

![image](https://github.com/user-attachments/assets/02bc8d21-b881-4197-882b-b09e12b4fea5)

I am wondering if the images of Longhorn components are up to date. For example, this user discovered that the image is not uptodate due to old Helm value https://rancher-users.slack.com/archives/CC2UQM49Y/p1726088763371659. Can you provide:
1. `kubectl get ds longhorn-manager -n longhorn-system -oyaml`
2. `kubectl get svc -n longhorn-system -oyaml`

**Comment by dopic** [comment]
Thank you, @PhanLe1010!

To keep things working here, we had to roll back longhorn to 1.4.4, but we updated again to get this information.

I haven't seen this message again, but the problem persists.

I'm sending the DaemonSet and Service configuration, and also new logs.

**Configuration**
[ds-config.yml](https://github.com/user-attachments/files/17059063/ds-config.txt)
[svc-config.yml](https://github.com/user-attachments/files/17059064/svc-config.txt)


**Logs**
[longhorn-manager-w01.log](https://github.com/user-attachments/files/17059020/longhorn-manager-w01.log)
[longhorn-manager-w02.log](https://github.com/user-attachments/files/17059021/longhorn-manager-w02.log)
[longhorn-manager-w03.log](https://github.com/user-attachments/files/17059022/longhorn-manager-w03.log)
[longhorn-manager-w04.log](https://github.com/user-attachments/files/17059024/longhorn-manager-w04.log)

**Comment by PhanLe1010** [comment]
Thanks @dopic 

I think this logs `{"file":"/go/src/github.com/longhorn/longhorn-manager/upgrade/upgrade.go:126","func":"github.com/longhorn/longhorn-manager/upgrade.upgrade.func1.1","level":"error","msg":"Upgrade failed: upgrade resources failed: Internal error occurred: failed calling webhook \"mutator.longhorn.io\": failed to call webhook: Post \"https://longhorn-admission-webhook.longhorn-system.svc:9502/v1/webhook/mutation?timeout=30s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)","time":"2024-09-19T12:11:39Z"}` is indicating that the kubernetes API server cannot talk to Longhorn admission webhook (which is longhorn-manager pods). Is there any network policy or firewall in your cluster which prevent this communication?

**Comment by dopic** [comment]
Hi, @PhanLe1010. You were right.

We had a network policy that was blocking access from the API Server. It was applied to the longhorn-manager pods, allowing access only from the same namespace. When the Webhooks were moved to the manager, the problem started.

Thank you for your help!
