### ISSUE TITLE
docs - node-to-node encryption

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#948]
Looking to find documentation if Longhorn traffic between nodes are encrypted, or it's all handled through Rancher

**Comment by yasker** [comment]
Current Longhorn is running on top of the overlay networking of Kubernetes, so it depends on the CNI to provide node to node encryption.

**Comment by ainiml** [comment]
> Current Longhorn is running on top of the overlay networking of Kubernetes, so it depends on the CNI to provide node to node encryption.

Does the CNI in a default Rancher `docker run` deployment provide encryption? 

Trying to find this on Rancher docs now.
