### ISSUE TITLE
UI: Perform the necessary steps to delete the node automatically

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#949]
After reinstalling Longhorn, old nodes are still shown and need to be removed. But there isn't an option to force remove the node.

![image](https://user-images.githubusercontent.com/28725423/70390246-3cdb9100-1997-11ea-9086-fa91defa2ee1.png)

**Comment by yasker** [comment]
Can you see if the following steps work for you?

https://longhorn.io/docs/multidisk/#remove-a-disk

**Comment by ainiml** [comment]
> Can you see if the following steps work for you?
> 
> https://longhorn.io/docs/multidisk/#remove-a-disk

I think individually having to disable scheduling is a taxing to UX (had about a dozen or so volumes attached the the various nodes)

I end up wiping everything to get rid of the nodes

**Comment by yasker** [comment]
We can add a batch operation on the UI with the following options if those can help:

```
Disable scheduling
Delete Replicas
Delete Node
```

**Comment by ainiml** [comment]
> We can add a batch operation on the UI with the following options if those can help:
> 
> ```
> Disable scheduling
> Delete Replicas
> Delete Node
> ```

Would these be the options under Nodes? 

I think these batch operations certainly would help.

**Comment by yasker** [comment]
In fact, we can add incorporate more logic into delete the node. Basically, it would:
1. Disable the node scheduling
2. Delete all the replicas on the node.
3. Delete the node.

Previously we want to make sure the user understands what's the system is doing. But you're right, it seems an unnecessary burden for the user to execute those steps. Those can be done by UI automatically. If any of the steps failed, we can error out and let the user try again.

**Comment by ainiml** [comment]
> In fact, we can add incorporate more logic into delete the node. Basically, it would:
> 
> 1. Disable the node scheduling
> 2. Delete all the replicas on the node.
> 3. Delete the node.
> 
> Previously we want to make sure the user understands what's the system is doing. But you're right, it seems an unnecessary burden for the user to execute those steps. Those can be done by UI automatically. If any of the steps failed, we can error out and let the user try again.

And just have a little status update of what stage and step the operation is doing and on

So if the user is watching it complete, they'll indirectly gain the knowledge of how it works

**Comment by yasker** [comment]
Introducing a status update will require more changes from the backend. For the next release, I think we can settle on performing the steps automatically until error or success.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI version: `wangsiye/longhorn-ui:ddfe8dd`

Steps to test:
  - Create a volume, attach it to a node
  - In Node page, select a node, Click `Delete`, a confirmation modal will pop up, click `OK`
  >  - Volume replicas drained from selected node, and replica count = 0
  > - Scheduling is disabled on selected node Node
  > - An error message appears state that:
 `unable to delete node: Could not delete node <NODE_NAME> with node ready condition is True ...`
  - Delete a node from Kubernetes using `kubectl delete node  <NODE_NAME>`
  - In Node page, deleted node status is Down
  - In Node page, select a node, Click `Delete`, a confirmation modal will pop up, click `OK`
  > Node should be removed.  **(PASS)**

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Longhorn UI version: `wangsiye/longhorn-ui:81d49f5`
