### ISSUE TITLE
[FEATURE][UI] Fill in the secret and secret namespace when restoring the BackupBackingImage

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#9490]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

After this feature is closed: https://github.com/longhorn/longhorn/issues/8884
Longhorn stores the encryption secret and secret namespace information in the BackupBackingImage now, so we can help users to fill in the information when they restore the BackupBackingImage. 

## Describe the solution you'd like

Previously, we let users to fill in the  secret and secret namespace when they want to restore the BackupBackingImage.
But now we should help users to fill in the secret and secret namespace to improve the user experience.

## Describe alternatives you've considered

.

## Additional context

cc @a110605

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-ui/commit/944339c2d6deea41bb7e3d778757376fd9aa7f4e) with test [steps](https://github.com/longhorn/longhorn/issues/9490#issuecomment-2522243221)
