### ISSUE TITLE
[BUG] robot test case `Single Replica Node Down Deletion Policy do-nothing With RWO Volume Replica Locate On Replica Node` fails to wait for the volume getting stuck in attaching state

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9498]
## What's the test to develop? Please describe

Robot test case `Single Replica Node Down Deletion Policy do-nothing With RWO Volume Replica Locate On Replica Node` fails at the step `Then Wait for volume of deployment 0 stuck in state attaching`:

```
Single Replica Node Down Deletion Policy do-nothing With RWO Volume Replica Locate On Replica Node
    Given Create storageclass longhorn-test with    dataEngine=${DATA_ENGINE}
    And Set setting node-down-pod-deletion-policy to do-nothing
    When Create persistentvolumeclaim 0 using RWO volume with longhorn-test storageclass
    And Create deployment 0 with persistentvolumeclaim 0
    And Wait for volume of deployment 0 healthy
    And Write 100 MB data to file data in deployment 0

    # Delete replicas to have the volume with its only replica located on different nodes.
    And Update volume of deployment 0 replica count to 1
    And Delete replica of deployment 0 volume on replica node
    And Delete replica of deployment 0 volume on volume node
    And Power off volume node of deployment 0
    Then Wait for volume of deployment 0 stuck in state attaching
    And Wait for deployment 0 pod stuck in Terminating on the original node

    When Power on off node
    And Wait for deployment 0 pods stable
    And Check deployment 0 pod is Running on another node
    Then Check deployment 0 data in file data is intact
```

After the volume node powered off, the expectation is for the volume to get stuck in `attaching` state, but in `master-head`, it remains in `attached` state:

![image](https://github.com/user-attachments/assets/db700e08-5bc4-4359-a3f9-86f9e6a8c847)

![image](https://github.com/user-attachments/assets/11198729-e5b2-4876-8c1b-58573f4ccdb1)
 
@chriscchien Could you help confirm if it's an issue or if the test case needs to be refined? Thank you!

**Comment by chriscchien** [comment]
Double checked on v1.7.1 and the result of test case `Single Replica Node Down Deletion Policy do-nothing With RWO Volume Replica Locate On Replica Node` [passed](https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1417/), hence this is more like a regression otherwise we should change test case to match new behavior.

**Comment by yangchiu** [comment]
Moved milestone to v1.7.2 since it also happens in v1.7.x-head: https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1561/

**Comment by derekbit** [comment]
@c3y1huang Could you check it? Thank you.

**Comment by derekbit** [comment]
It might be not a regression in v1.7.2, because https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1417/ only tested once.

All the test cases are passed.
https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1568 v1.7.1
https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1570 v1.7.1 (N times)

https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1569 v1.7.1
https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1571 v1.7.1 (N times)

@c3y1huang let me know if we need more time and can put off the issue to the next release. Thanks.

**Comment by c3y1huang** [comment]
I am actually a bit confused about this test case. 
```
And Set setting node-down-pod-deletion-policy to do-nothing
```
Longhorn shouldn't actively delete a workload pod in this case, hence there might not be a reattaching behavior. I think we can simply remove the check for the volume's attaching state and ensure that the workload pod is in a terminating state, which is expected.
https://github.com/longhorn/longhorn-manager/blob/v1.7.2-rc1/controller/kubernetes_pod_controller.go#L327-L328

What do you think @derekbit ?

**Comment by derekbit** [comment]
> I am actually a bit confused about this test case regarding the checking of volume attaching state.
> 
> ```
> And Set setting node-down-pod-deletion-policy to do-nothing
> ```
> 
> Longhorn shouldn't actively delete a workload pod in this case, hence there might not be a reattaching behavior. This case depends on how the Kubernetes reacts. I think we can simply remove the check for the volume's attaching state and just ensure that the workload pod is in a terminating state, which is expected. [longhorn/longhorn-manager@`v1.7.2-rc1`/controller/kubernetes_pod_controller.go#L327-L328](https://github.com/longhorn/longhorn-manager/blob/v1.7.2-rc1/controller/kubernetes_pod_controller.go?rgh-link-date=2024-10-11T04%3A35%3A57Z#L327-L328)
> 
> What do you think @derekbit ?

Yeah, agree with removing the check.

**Comment by yangchiu** [comment]
@c3y1huang There are 5 other similar test cases:

```
Single Replica Node Down Deletion Policy do-nothing With RWO Volume Replica Locate On Volume Node
Single Replica Node Down Deletion Policy delete-deployment-pod With RWO Volume Replica Locate On Replica Node
Single Replica Node Down Deletion Policy delete-deployment-pod With RWO Volume Replica Locate On Volume Node
Single Replica Node Down Deletion Policy delete-both-statefulset-and-deployment-pod With RWO Volume Replica Locate On Replica Node
Single Replica Node Down Deletion Policy delete-both-statefulset-and-deployment-pod With RWO Volume Replica Locate On Volume Node
```

that fail for the same reason:

```
KEYWORD volume_keywords . Wait For Volume Faulted ${volume_name}
Start / End / Elapsed: 	20241011 16:54:19.505 / 20241011 17:14:24.750 / 00:20:05.245
17:14:24.749 	FAIL 	AssertionError
```

```
KEYWORD volume_keywords . Wait For Volume Attaching ${volume_name}
Start / End / Elapsed: 	20241011 17:19:20.743 / 20241011 17:39:26.018 / 00:20:05.275
17:39:26.017 	FAIL 	AssertionError
```

https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1609/robot/report/log.html

Could you help review whether the `Wait For Volume Faulted` and `Wait For Volume Attaching` are also safe to remove?

Thank you! 

cc @chriscchien

**Comment by c3y1huang** [comment]
> @c3y1huang There are 5 other similar test cases:
> 
> ```
> Single Replica Node Down Deletion Policy do-nothing With RWO Volume Replica Locate On Volume Node
> Single Replica Node Down Deletion Policy delete-deployment-pod With RWO Volume Replica Locate On Replica Node
> Single Replica Node Down Deletion Policy delete-deployment-pod With RWO Volume Replica Locate On Volume Node
> Single Replica Node Down Deletion Policy delete-both-statefulset-and-deployment-pod With RWO Volume Replica Locate On Replica Node
> Single Replica Node Down Deletion Policy delete-both-statefulset-and-deployment-pod With RWO Volume Replica Locate On Volume Node
> ```
> 
> that fail for the same reason:
> 
> ```
> KEYWORD volume_keywords . Wait For Volume Faulted ${volume_name}
> Start / End / Elapsed: 	20241011 16:54:19.505 / 20241011 17:14:24.750 / 00:20:05.245
> 17:14:24.749 	FAIL 	AssertionError
> ```
> 
> ```
> KEYWORD volume_keywords . Wait For Volume Attaching ${volume_name}
> Start / End / Elapsed: 	20241011 17:19:20.743 / 20241011 17:39:26.018 / 00:20:05.275
> 17:39:26.017 	FAIL 	AssertionError
> ```
> 
> https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1609/robot/report/log.html
> 
> Could you help review whether the `Wait For Volume Faulted` and `Wait For Volume Attaching` are also safe to remove?
> 
> Thank you!
> 
> cc @chriscchien

I think the test cases should either remove or improve the handling of the intermediate condition check. Could you create a new issue to address them? Thanks!

cc @derekbit

**Comment by yangchiu** [comment]
> 
> I think the test cases should either remove or improve the handling of the intermediate condition check. I prefer not to expand on this issue. Could you creat new issues to address them? Thanks!
> 
> cc @derekbit

Created https://github.com/longhorn/longhorn/issues/9622 for it.

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-tests 8677389). Test case `Single Replica Node Down Deletion Policy do-nothing With RWO Volume Replica Locate On Replica Node` passed: https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1672/
