### ISSUE TITLE
[BUG] Fix test case test_rwx_delete_share_manager_pod failure after changes to RWX workload restart.

### ISSUE THREAD

**Issue by james-munson** [longhorn/longhorn#9504]
## Describe the bug

After the change in #9095, the workload won't restart even if the share manager pod is deleted. 

## To Reproduce

Nightly run https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/1049/ failed on that test, which one would expect as the first run after the commit.

## Expected behavior

Test should pass.

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

Fix would be to restore the changes made in https://github.com/longhorn/longhorn-tests/pull/2008 and reverted in https://github.com/longhorn/longhorn-tests/pull/2011

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-manager 8bc7575). Test case `test_rwx_delete_share_manager_pod` passed: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7626/
