### ISSUE TITLE
My node goes down when disk size increased

### ISSUE THREAD

**Issue by akuscu-smartpulse** [longhorn/longhorn#952]
i have 400 gb ssd disk on my node.I set my storage reserved to 1 GB.My disk size increased  to 350GB in time and my node down.After that my images were deleted.Is it a bug or my config is wrong ?

**Comment by yasker** [comment]
I think you said your disk was 400GB then you shrink it to 350GB? Can you describe the steps you've taken in detail?  For example,  how do you resize the disk, what's deleted?

**Comment by akuscu-smartpulse** [comment]
I have 400 gb pyhsical disk.
I created a longhron volume with 500 Gi PVC.
My pyhsical disk got bigger consumed and its space used 350 Gi.
After that my node shut down and all of the docker images on the disk was deleted.
I tried with another node and result is the same.
