### ISSUE TITLE
[TEST] Update robot test `README` and `test.yaml`

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9521]
## What's the test to develop? Please describe

Update robot test `README ` and `test.yaml`

(1) Add `HOST_PROVIDER` in `README.md`
(2) Add `HOST_PROVIDER` in `test.yaml`
(3) Add `nodeAffinity` in `test.yaml` to ensure the test pod is scheduled on the control plane.

**Comment by khushboo-rancher** [comment]
@yangchiu Looks like this task is completed?
