### ISSUE TITLE
[IMPROVEMENT] longhorn-manager stops reporting sprint release <version>-dev-<date> 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9522]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Sprint releases in the format `<version>-dev-<date>` might overwhelm the metrics server in the future.

## Describe the solution you'd like

To prevent overwhelming the Active Node Longhorn Versions in the Longhorn metrics server, the longhorn-manager can stop reporting sprint releases with the format <version>-dev-<date>.

## Describe alternatives you've considered

N/A

## Additional context
N/A

**Comment by innobead** [comment]
Can we just aggregate them to `dev` instead of ignoring them?

**Comment by PhanLe1010** [comment]
## Test plan:
1. Go to https://metrics.longhorn.io/
2. Make sure that in the panel `Active Node Longhorn Versions`, there is no version like `v1.8.0-dev-20240922`, `v1.7.1-dev-20240922`, `v1.6.3-dev-20240922`. They should be aggregated into single `dev` version like this 
   ![image](https://github.com/user-attachments/assets/4cf349c2-a1fc-442a-ab48-82c13fd0880b)

**Comment by roger-ryao** [comment]
The related MR was merged on 2024/09/25. We will wait until the next spring image release and check the results on https://metrics.longhorn.io/ one week later.

**Comment by roger-ryao** [comment]
After the release of `longhorn-dev-20241006`, we observed that all metrics were aggregated into a single `dev` version on
https://metrics.longhorn.io/d/tsrvoC-mz/longhorn?orgId=2&viewPanel=12 

![Image](https://github.com/user-attachments/assets/4444ebac-e9cd-4fa0-b27f-958818c5c5ce)
