### ISSUE TITLE
High CPU usage by longhorn-instance-manager pod in 1.6.2 version

### ISSUE THREAD

**Issue by vr2388** [longhorn/longhorn#9527]
## Describe the bug

Longhorn instance manager pod is consuming more cpu.

## To Reproduce

Install longhorn 1.6.2 helm chart and observe the cpu consumption by the longhorn-instance-manager pod.

## Expected behavior

It shouldn't consume more cpu

## Environment

 - Longhorn version: 1.6.2
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of control plane nodes in the cluster: 3(all 3 nodes are master)
   - Number of worker nodes in the cluster: 
 - Node config
   - OS type and version: ubuntu 22.04/ ubuntu 20.04
   - Kernel version:
   - CPU per node: 4core
   - Memory per node: 8GB
   - Disk type (e.g. SSD/NVMe/HDD): 60GB
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster:

**Comment by shuo-wu** [comment]
And if you can provide Grafana monitoring results against the cluster resources, that would be better. Thanks.
