### ISSUE TITLE
[FEATURE] Longhorn CLI supports darwin platform

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9532]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Longhorn CLI supports darwin platform

**Comment by chriscchien** [comment]
Verified **pass** on longhorn/cli v1.8.0-dev-20241020 (https://github.com/longhorn/cli/commit/772b4917a633ee49e1bcb58a4d166e4f4d489182)

longhorn cli worked well on macOS 12.0.1(Monterey) ([ref](https://github.com/longhorn/cli/blob/v1.8.0-dev-20241020/docs/longhornctl.md))
