### ISSUE TITLE
[BUG] All my longhorn dependent pods are stuck in ContainerCreating after upgrade to 1.6.2 and 1.7.1

### ISSUE THREAD

**Issue by Mithul** [longhorn/longhorn#9535]
## Describe the bug

Almost all my longhorn dependent pods are stuck in ContainerCreating after upgrade to 1.6.2 and 1.7.1 . Prior to upgrade everything was working fine. Post upgrade all my pods eventually all landed in ContainerCreating state 
```
~ kubectl get pods --all-namespaces --watch | grep ContainerCreating
default           authelia-0                                          0/1     ContainerCreating   0                  44m
default           postgres-785974ff96-ppvzh                           0/1     ContainerCreating   0                  45m
home-automation   home-assistant-68db59cf55-mjnxf                     0/1     ContainerCreating   0                  45m
home-automation   mealie-645949997c-b6fdj                             0/1     ContainerCreating   0                  45m
media-system      jellyseerr-5f5b5445f5-pfbrm                         0/1     ContainerCreating   0                  9m13s
media-system      prowlarr-67c4689cc9-4rccs                           0/1     ContainerCreating   0                  9m13s

```

All of them have similar errors 
```
Events:
  Type     Reason              Age                  From                     Message
  ----     ------              ----                 ----                     -------
  Normal   Scheduled           11m                  default-scheduler        Successfully assigned media-system/prowlarr-67c4689cc9-4rccs to gohan
  Warning  FailedMount         5m19s                kubelet                  Unable to attach or mount volumes: unmounted volumes=[prowlarr-config], unattached volumes=[kube-api-access-8x528 prowlarr-config]: timed out waiting for the condition
  Warning  FailedAttachVolume  62s (x3 over 9m2s)   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-7a9f5d09-a855-4814-a20a-7325c1799956" : timed out waiting for external-attacher of driver.longhorn.io CSI driver to attach volume pvc-7a9f5d09-a855-4814-a20a-7325c1799956
  Warning  FailedMount         49s (x4 over 9m52s)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[prowlarr-config], unattached volumes=[prowlarr-config kube-api-access-8x528]: timed out waiting for the condition

```

## To Reproduce
I have not tried redoing these steps to see if the error always happens, however this is what was done on my system:
1. Run 1.5.x longhorn
2. Start a few deployments using longhorn volumes (with automatic volume creation for pvcs)
3. Upgrade to 1.6.2

I later tried upgrading to 1.7.1 in hopes that something might fix the issue, but the same issue still exists

## Expected behavior
I would expect all pods to continue working and be able to attach the existing(upgraded) volumes

## Support bundle for troubleshooting
File is 203MB , too big. Sent email

## Environment

 - Longhorn version: 1.7.1
 - Impacted volume (PV): pvc-7a9f5d09-a855-4814-a20a-7325c1799956
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s / v1,24,11+k3s1
   - Number of control plane nodes in the cluster: 3 
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 22.04.2
   - Kernel version: 5.15.0-122-generic
   - CPU per node: 4-6
   - Memory per node: 6GB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 1Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox VMs
 - Number of Longhorn volumes in the cluster: 31

## Additional context

I have tried deleting the pod for deployment to spin a new one up, I have tried scaling down to 0 and bringing them back up. I have tried rebooting all nodes 1 at a time but nothing has seemed to work

## Workaround and Mitigation
 None. I am stuck

**Comment by Mithul** [comment]
After the containerCreating issue started, I did try force detaching the volume (since it stayed attached to a non-existent pod even after 10 minutes). After scaling replicas back up I saw the volume was not getting attached and attached it through UI to the same node the pod was on in hopes that it would work. This might have been the reason its showing as already attached.

However all of these steps were an attempt to recover the volumes and the issue was already present so I don't think this is the cause.

How do I safely remove the attachment so longhorn can auto attach to the pod. Note: The UI shows attached to the right pods, but the pod `describe` shows that's it is still waiting to attach

**Comment by Mithul** [comment]
I am also now seeing on some pods, but not others
```
MountVolume.WaitForAttach failed for volume "pvc-f4a87d40-0989-4b3a-a150-465d612bb65e" : volume pvc-f4a87d40-0989-4b3a-a150-465d612bb65e has GET error for volume attachment csi-52797d6e8104ca8ef5eb3011863ae9f7e897fa2232058e43865bcf29d2cd729b: volumeattachments.storage.k8s.io "csi-52797d6e8104ca8ef5eb3011863ae9f7e897fa2232058e43865bcf29d2cd729b" is forbidden: User "system:node:trunks" cannot get resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope: no relationship found between node 'trunks' and this object
```

**Comment by Mithul** [comment]
I was able to solve an issue with one of the pods, where the csi logs showed that it was unable to attach a volume to the node with the pod since it was already attached to a different node. Manually detaching the volume and attaching it to the node the pod was in solved this issue . However when trying this for other pods its not working

**Comment by Mithul** [comment]
Deleting the longhorn-ui attachment has worked for my case. Thanks for the pointer. 

However, I am still unsure what caused it and how it can be prevented.

**Comment by ChanYiLin** [comment]
I don't think this has the same root cause as this one https://github.com/longhorn/longhorn/issues/8339
That only happens when users update the version from v1.4.x to v1.5.x.
And it happens because we try to add longhorn-ui attachment ticket when we find the volume is attached to a node but can't find the `volumeattachments.storage.k8s.io` in the k8s.

But in your case, you started from v1.5.x, all the volume should already have valid Longhorn VolumeAttachment CRs
We may still need to find out the root cause.

For now, as you said, 
> where the csi logs showed that it was unable to attach a volume to the node with the pod since it was already attached to a different node
you can check the Longhorn VolumeAttachment CRs
 by `$kubectl get lhva -n longhorn-system` to see if the volume's VA CR has `longhorn-ui` ticket and you can manually delete it.
