### ISSUE TITLE
Backup Schedule does not remove existing backups - UI

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#954]
Scheduled backups are set to retain 5, but there are more than 5 backups.

I think the manual backups are retained and not deleted?

If so, maybe the manual backups should have a visible icon to know it was a manual backup and will not be affected by the scheduling

![image](https://user-images.githubusercontent.com/28725423/70535421-10f11480-1b2b-11ea-9419-4b0123adb19d.png)

![image](https://user-images.githubusercontent.com/28725423/70535460-22d2b780-1b2b-11ea-9e19-3d5f0bb86e2e.png)

**Comment by yasker** [comment]
Retain only apply to THAT backup scheduling. Since you can have multiple backup scheduling, e.g. once per hour + once per day + once per month. You won't want them to delete the backups created by other schedulings.

**Comment by ainiml** [comment]
> Retain only apply to THAT backup scheduling. Since you can have multiple backup scheduling, e.g. once per hour + once per day + once per month. You won't want them to delete the backups created by other schedulings.

That makes sense
