### ISSUE TITLE
[TASK] An Investigation for Future Longhorn performance

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#9552]
After discussing with @innobead, I am opening this ticket to research the existing and future directions for Longhorn performance so that Longhorn team can make informative decisions. The goal is to come out with a comparison report between 4 candidates:
1. v1 volume
2. UBLK + v1 engine
3. v2 engine (including different setup of v2 like @derekbit did)
4. UBLK + v2 engine (including different setup of v2)

Comparing metrics:
1. Performance 
2. CPU consumption
3. RAM consumption
4. Suitable real-world use-case (e.g., small machine/big machine, new kernel/popular kernel)
5. (Optional) Which part is the bottle neck of each candidate

## Additional context

Related tickets:
1. https://github.com/longhorn/longhorn/issues/5159
1. https://github.com/longhorn/longhorn/issues/9456

**Comment by PhanLe1010** [comment]
TODO: Maybe we can try to enble blk-mq for scsi system to see if the performance of v1 stack can be improve. cc

**Comment by PhanLe1010** [comment]
I posted the completed report at https://github.com/longhorn/longhorn/wiki/A-Survey-about-Longhorn-Performance#v2-engine

Looking forward to your feedback @innobead @derekbit @shuo-wu @DamiaSan

**Comment by PhanLe1010** [comment]
Test plan:

There is no test plan for this ticket. QA is welcome to read the report https://github.com/longhorn/longhorn/wiki/Longhorn-Performance-Investigation

**Comment by derekbit** [comment]
Completed. Great job! Thanks @PhanLe1010.

cc @longhorn/dev @innobead
