### ISSUE TITLE
[IMPROVEMENT] Talos support for environment check in longhorn manager

### ISSUE THREAD

**Issue by dimidevops** [longhorn/longhorn#9558]
## Describe the bug

After upgrading Longhorn from 1.6.2 to 1.7.1 on Talos OS, RWX volumes are not working and there are several errors about detecting NFS ver kernel settings and OS packages.

![Screenshot 2024-10-01 131643](https://github.com/user-attachments/assets/d0803f0e-5382-4d4a-a817-fed079239ee4)
![Screenshot 2024-10-01 132013](https://github.com/user-attachments/assets/9ab17625-8568-45b3-bc6b-7949969854a4)

## To Reproduce
Deploy latest Longhorn release on Talos OS 1.7.7

## Expected behavior
RWX volumes to work out of the box 

## Support bundle for troubleshooting
[supportbundle_5bb5caf5-13b3-479d-b5fd-4ae2cedbe8d3_2024-10-01T16-22-20Z.zip](https://github.com/user-attachments/files/17213067/supportbundle_5bb5caf5-13b3-479d-b5fd-4ae2cedbe8d3_2024-10-01T16-22-20Z.zip)

## Environment

 - Longhorn version: **1.7.1**
 - Impacted volume (PV): All RWX volumes 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm chart deployed via ArgoCD
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Talos OS 1.7.7, k8s 1.30.5
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 6
 - Node config
   - OS type and version: Talos OS 1.7.7
   - Kernel version: 6.6.52-talos
   - CPU per node: 8
   - Memory per node: 16 GB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 1gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox VMs
 - Number of Longhorn volumes in the cluster: 30+

## Additional context
Helm chart values: 

![image](https://github.com/user-attachments/assets/56a96d17-f49f-4586-856d-3eec8d61f077)

## Workaround and Mitigation

This should be used to detect kernel config settings for Talos OS: `cat /proc/config.gz | zless`

**Comment by innobead** [comment]
cc @c3y1huang

**Comment by mantissahz** [comment]
>This should be used to detect kernel config settings for Talos OS: cat /proc/config.gz | zless

I will test this config file to check if it can get the kernel configs.

**Comment by c3y1huang** [comment]
> After upgrading Longhorn from 1.6.2 to 1.7.1 on Talos OS, RWX volumes are not working

So far, I haven't been able to reproduce this issue when upgrading Longhorn from 1.6.2 to 1.7.1 on the Talos v1.7.7 cluster. Interestingly, there is no ShareManager CR or pod in the support bundle. @dimidevops could you try reattaching one of the RWX volumes and observe the behavior of the ShareManager CR or pod?

> there are several errors about detecting NFS ver kernel settings and OS packages.

As @derekbit mentioned, these are not harmful. To my knowledge, Talos Linux was not within the scope when implementing the node controller environment check in v1.7.x. @mantissahz may have more context on this.

1. NFSClient issue:
    - The error `ls: No such file or directory`: the environment check depends on the `ls` binary from the host namespace, which isn't available on Talos Linux. We can try using Kubelet namespace instead.
    - This doesn't look like the cause of the disappearance of the share managers.
1. RequiredPackages issue:
    - The required packages check relies on OS package managers, which Talos Linux does not use. We will need to tailor these checks for each of the immutable systems.

**Comment by dimidevops** [comment]
After deleting the old PV and PVC and creating new ones under the 1.7.1 version they seem to attach to the pods. 
So far so good, but I noticed that some pods get "permission denied" when trying to write on the RWX volumes. This is strange because the same pods can read/write to RWO volumes with no issues. **Privileged pods that run as root do not get this error**

**Comment by c3y1huang** [comment]
> So far so good, but I noticed that some pods get "permission denied" when trying to write on the RWX volumes. This is strange because the same pods can read/write to RWO volumes with no issues. Privileged pods that run as root do not get this error

Could you provide some sample YAML files to help us reproduce the issue?

**Comment by dimidevops** [comment]
I've noticed this with Harbor HELM deployment. The Database and Registry pods fail to write data on the RWX volumes. I can provide you with the Helm values so you can deploy it.

`helm repo add harbor https://helm.goharbor.io`
`helm install harbor harbor/harbor --namespace harbor -f harbor.yaml`

[harbor.yaml.txt](https://github.com/user-attachments/files/17539775/harbor.yaml.txt)

**Comment by c3y1huang** [comment]
> I've noticed this with Harbor HELM deployment. The Database and Registry pods fail to write data on the RWX volumes. I can provide you with the Helm values so you can deploy it.
> 
> `helm repo add harbor https://helm.goharbor.io` `helm install harbor harbor/harbor --namespace harbor -f harbor.yaml`
> 
> [harbor.yaml.txt](https://github.com/user-attachments/files/17539775/harbor.yaml.txt)

Got it. I'm actually looking for something minimal, like [this example](https://github.com/longhorn/longhorn/blob/master/examples/rwx/rwx-nginx-deployment.yaml). If you could provide minimal YAMLs for reproduction, that would be great.

**Comment by dimidevops** [comment]
This part controls the provisioning of PVC/PV for the different components. You can change the access modes to "ReadWriteOnce (RWO)" or "ReadWriteMany (RWX)"

persistence:
  persistentVolumeClaim:
    registry:
      size: 20Gi
      accessMode: ReadWriteMany
    jobservice:
      jobLog:
        size: 1Gi
        accessMode: ReadWriteMany
    database:
      size: 1Gi
      accessMode: ReadWriteMany
    redis:
      size: 1Gi
      accessMode: ReadWriteMany
    trivy:
      size: 10Gi
      accessMode: ReadWriteMany

I'm afraid I don't have anything simple to provide you.

**Comment by c3y1huang** [comment]
It seems to be functioning for me. Here is my values.yaml and the commands executed:
```
persistence:
  persistentVolumeClaim:
    registry:
      size: 20Gi
      accessMode: ReadWriteMany
    jobservice:
      jobLog:
        size: 1Gi
        accessMode: ReadWriteMany
    database:
      size: 1Gi
      accessMode: ReadWriteMany
    redis:
      size: 1Gi
      accessMode: ReadWriteMany
    trivy:
      size: 10Gi
      accessMode: ReadWriteMany
```
```
> k -n harbor get pod
NAME                                 READY   STATUS    RESTARTS       AGE
harbor-core-77444474c7-bqqln         1/1     Running   0              4m21s
harbor-database-0                    1/1     Running   0              4m21s
harbor-jobservice-5ccbdddfb9-4mwqg   1/1     Running   4 (3m1s ago)   4m21s
harbor-portal-d6c99f896-gmvx8        1/1     Running   0              4m21s
harbor-redis-0                       1/1     Running   0              4m21s
harbor-registry-5d44ff5b46-hs97s     2/2     Running   0              4m21s
harbor-trivy-0                       1/1     Running   0              4m21s
```
```
> k -n harbor get pvc
NAME                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
data-harbor-redis-0               Bound    pvc-cd08ccff-bede-4620-a891-368240c1b204   1Gi        RWX            longhorn       <unset>                 4m43s
data-harbor-trivy-0               Bound    pvc-27a18497-12bd-432a-bbcb-1587a5dfed01   10Gi       RWX            longhorn       <unset>                 4m43s
database-data-harbor-database-0   Bound    pvc-6d1fcc40-c037-482d-b48c-5318262430fb   1Gi        RWX            longhorn       <unset>                 4m43s
harbor-jobservice                 Bound    pvc-b4e1ed94-f960-45c3-a27f-b1842c842358   1Gi        RWX            longhorn       <unset>                 4m43s
harbor-registry                   Bound    pvc-dfcd3273-f58a-4091-9e1d-294544f13fae   20Gi       RWX            longhorn       <unset>                 4m43s
```
```
k -n longhorn-system get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                    STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE
pvc-27a18497-12bd-432a-bbcb-1587a5dfed01   10Gi       RWX            Delete           Bound    harbor/data-harbor-trivy-0               longhorn       <unset>                          5m4s
pvc-6d1fcc40-c037-482d-b48c-5318262430fb   1Gi        RWX            Delete           Bound    harbor/database-data-harbor-database-0   longhorn       <unset>                          5m4s
pvc-b4e1ed94-f960-45c3-a27f-b1842c842358   1Gi        RWX            Delete           Bound    harbor/harbor-jobservice                 longhorn       <unset>                          5m4s
pvc-cd08ccff-bede-4620-a891-368240c1b204   1Gi        RWX            Delete           Bound    harbor/data-harbor-redis-0               longhorn       <unset>                          5m4s
pvc-dfcd3273-f58a-4091-9e1d-294544f13fae   20Gi       RWX            Delete           Bound    harbor/harbor-registry                   longhorn       <unset>                          5m4s
```
```
k -n longhorn-system get volume
NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE          NODE             AGE
pvc-27a18497-12bd-432a-bbcb-1587a5dfed01   v1            attached   healthy                  10737418240   ip-10-0-28-197   5m18s
pvc-6d1fcc40-c037-482d-b48c-5318262430fb   v1            attached   healthy                  1073741824    ip-10-0-28-138   5m18s
pvc-b4e1ed94-f960-45c3-a27f-b1842c842358   v1            attached   healthy                  1073741824    ip-10-0-28-197   5m18s
pvc-cd08ccff-bede-4620-a891-368240c1b204   v1            attached   healthy                  1073741824    ip-10-0-28-180   5m18s
pvc-dfcd3273-f58a-4091-9e1d-294544f13fae   v1            attached   healthy                  21474836480   ip-10-0-28-180   5m18s
```

**Comment by dimidevops** [comment]
Yes, the Pod Security and Extra Mounts are set. I've spin up a new cluster and it's working there with no issues. On old DEV cluster it's giving issues. I guess this might be a cluster issue on my end. I still see the messages about missing components but everything seems to be working.

**Comment by c3y1huang** [comment]
Proposed change:
1. NFSClient issue: Check the `/proc/config.gz` in the kubelet namespace if the kernel config file path not exist.
1. RequiredPackages issue: Validate with commands when the OS image is Talos.

    | package    | namespace | validate command   |
    |------------|-----------|--------------------|
    | iscsi      | iscsi     | iscsiadm --verison |
    | cryptsetup | host      | cryptsetup --version |
    | dmsetup    | host      | dmsetup --version  |
    | nfs-common | kubelet   | dpkg -s nfs-common |

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-manager 1925819).

![talos-master](https://github.com/user-attachments/assets/0d24a20c-0b91-48eb-9364-88e5778638b9)
