### ISSUE TITLE
Longhorn not deploying across multiple nodes

### ISSUE THREAD

**Issue by ikethecoder** [longhorn/longhorn#956]
I have a three node cluster across 3 physical machines running Debian 10.

Node 1 - etcd / control / worker
Node 2 - worker
Node 3 - worker

K8S version: `v1.15.5-rancher1-2`
Rancher version: `v2.3.2`
Longhorn version: `0.7.0`
Docker version: `19.3.1` on Node 1, `19.3.5` on Nodes 2 & 3
O/S: Debian 4.19.67-2+deb10u2

The Rancher cluster is configured with `Canal` network provider and starts fine without any errors.  There is no firewall or restrictions on traffic between the three nodes.

Using Longhorn's 0.7.0 tagged Helm chart to deploy with all its defaults.

Longhorn deploys fine on Node 1, but when Nodes 2 and 3 are introduced I am seeing the following errors on these pods for nodes 2 and 3:

`longhorn-csi-plugin`:
```
I1210 23:58:22.820107 1 main.go:110] Version: v1.2.0-0-g6ef000ae
I1210 23:58:22.820170 1 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
I1210 23:58:22.820711 1 connection.go:151] Connecting to unix:///csi/csi.sock
W1210 23:58:32.821003 1 connection.go:170] Still connecting to unix:///csi/csi.sock
W1210 23:58:42.820985 1 connection.go:170] Still connecting to unix:///csi/csi.sock
W1210 23:58:52.821001 1 connection.go:170] Still connecting to unix:///csi/csi.sock
W1210 23:59:02.821000 1 connection.go:170] Still connecting to unix:///csi/csi.sock
```

`csi-provisioner`:
```
I1211 00:23:54.497407 1 feature_gate.go:216] feature gates: &{map[]}
I1211 00:23:54.498144 1 csi-provisioner.go:98] Version: v1.4.0-0-g1d9bad3
I1211 00:23:54.498172 1 csi-provisioner.go:112] Building kube configs for running in cluster...
F1211 00:24:24.503982 1 csi-provisioner.go:132] Error getting server version: Get https://10.43.0.1:443/version?timeout=32s: dial tcp 10.43.0.1:443: i/o timeout
```

On Node 1, the `csi.sock` resides under `/var/lib/kubelet/plugins/driver.longhorn.io`.  But on Nodes 2 and 3 the socket file does not exist anywhere under `/var/lib`.

**Comment by yasker** [comment]
According to
```
F1211 00:24:24.503982 1 csi-provisioner.go:132] Error getting server version: Get https://10.43.0.1:443/version?timeout=32s: dial tcp 10.43.0.1:443: i/o timeout
```

It sounds like a network issue. CSI provisioner cannot reach the Kubernetes service (which is located at `10.43.0.1`) on node 2 or 3.

**Comment by ikethecoder** [comment]
If I go to a `shell` on a different pod, such as `nginx-ingress-controller` on Node 2 and run `curl -v -k https://10.43.0.1:443/version` I get a 401 response, so it does reach on Node 2.  Although if I do the same from the `engine-image-ei` shell, I get the timeout error similar to what I see in `csi-provisioner`.

**Comment by ikethecoder** [comment]
The `calico-node` log on all 3 nodes has the following - in case there is something there that looks problematic - it is happily in `running` so don't expect the errors mentioned at the end to be a cause:
```
2019-12-11 01:51:11.830 [INFO][8] startup.go 256: Early log level set to info
2019-12-11 01:51:11.836 [INFO][8] startup.go 272: Using NODENAME environment for node name
2019-12-11 01:51:11.836 [INFO][8] startup.go 284: Determined node name: metal-node-8
2019-12-11 01:51:11.838 [INFO][8] k8s.go 219: Using host-local IPAM
2019-12-11 01:51:11.839 [INFO][8] startup.go 316: Checking datastore connection
2019-12-11 01:51:11.861 [INFO][8] startup.go 340: Datastore connection verified
2019-12-11 01:51:11.861 [INFO][8] startup.go 95: Datastore is ready
2019-12-11 01:51:11.895 [INFO][8] startup.go 530: FELIX_IPV6SUPPORT is false through environment variable
2019-12-11 01:51:11.902 [INFO][8] startup.go 181: Using node name: metal-node-8
2019-12-11 01:51:11.943 [INFO][30] k8s.go 219: Using host-local IPAM
CALICO_NETWORKING_BACKEND is none - no BGP daemon running
Calico node started successfully
2019-12-11 01:51:13.040 [WARNING][62] int_dataplane.go 354: Failed to query VXLAN device error=Link not found
2019-12-11 01:51:13.129 [WARNING][62] int_dataplane.go 384: Failed to cleanup preexisting XDP state error=failed to load XDP program (/tmp/felix-xdp-631268784): stat /sys/fs/bpf/calico/xdp/prefilter_v1_calico_tmp_A: no such file or directory
libbpf: failed to get EHDR from /tmp/felix-xdp-631268784
Error: failed to open object file
```

**Comment by ikethecoder** [comment]
@yasker thanks for your quick response.  Looking further, found this issue (https://github.com/rancher/k3s/issues/1114) that indicated a problem with Debian 10 iptables-legacy and a workaround for it.  Which, when I applied it, fixed my issue!
