### ISSUE TITLE
[BUG] longhorn volume be reinitialized

### ISSUE THREAD

**Issue by rolay** [longhorn/longhorn#9560]
## Describe the bug

After I switched the k8s network from flannel to calico, I restarted the server hosts one by one. After restarting, I found that the data in individual volume was missing, but the state and attributes of volume were correct, as if it had been reformatted. Can the data be retrieved?

## To Reproduce

The cluster has three nodes, restart the machines in turn, and restart the next one after the nodes are ready.

## Expected behavior

Individual volume data is cleared

## Environment

 - Longhorn version: v1.4.2
 - Impacted volume (PV): pvc-4189e8dd-bb48-45cc-9037-ac5c91d9b48b / pvc-dcc2ca0d-af9c-4deb-b6eb-9efd22a887c1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k8s v1.22.17
   - Number of control plane nodes in the cluster: 3
 - Node config
   - OS type and version: openEuler 22.03 (LTS-SP3)
   - Kernel version: 5.10.0-182.0.0.95.oe2203sp3.aarch64
   - CPU per node: 64
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD): SSD/HDD
   - Network bandwidth between the nodes (Gbps): 10000
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Bare Metal

**Comment by rolay** [comment]
[supportbundle_1ddb3b5f-9943-47cc-b458-258cc90db463_2024-10-02T02-04-15Z.zip](https://github.com/user-attachments/files/17218922/supportbundle_1ddb3b5f-9943-47cc-b458-258cc90db463_2024-10-02T02-04-15Z.zip)
This is the support pac

**Comment by rolay** [comment]
Is there any way to recover data? help, plz

**Comment by c3y1huang** [comment]
I don't think Longhorn can revert a snapshot when its marked as removed. https://github.com/longhorn/longhorn/issues/3748

According to the support-bundle, the share-manage is encountering issue with  vfs_check_handle:
```
2024-10-01T20:39:32.863135881+08:00 01/10/2024 12:39:32 : epoch 66fbed09 : share-manager-pvc-4189e8dd-bb48-45cc-9037-ac5c91d9b48b : nfs-ganesha-95[svc_14] vfs_check_handle :FSAL :INFO :Could not map fsid=0xcd44f856d96d4b98.0x567b36eb88e4a388 to filesystem
```

Maybe you could try [exporting a volume from a single replica](https://longhorn.io/docs/archives/1.4.2/advanced-resources/data-recovery/export-from-replica/) if the data is still intact.

> I switched the k8s network from flannel to calico

Could you provide more details on this? Specifically, the steps you've taken?

**Comment by rolay** [comment]
I found the reason: the path of the disk changed when the system was started, and the contents of sdc1 and sdb1 were switched.

**Comment by derekbit** [comment]
> I found the reason: the path of the disk changed when the system was started, and the contents of sdc1 and sdb1 were switched.

How will you handle the swap?

**Comment by rolay** [comment]
> > I found the reason: the path of the disk changed when the system was started, and the contents of sdc1 and sdb1 were switched.
> 
> How will you handle the swap?

it is drive letters have changed，I will  use the drive uuid.
