### ISSUE TITLE
[IMPROVEMENT] Remove the default CSI component images in longhorn-manager

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#9580]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

We have already defined the default images in the YAML and chart. To prevent confusion, we should remove these duplicated definitions.

## Describe the solution you'd like

Remove the [default CSI component images](https://github.com/longhorn/longhorn-manager/blob/master/csi/deployment.go#L23-L28) in longhorn-manager.

## Additional context

https://github.com/longhorn/longhorn/pull/9564#issuecomment-2395819747

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-manager 70ac3bc). Daily regression test passed without CSI-related test case failures: https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/1093/
