### ISSUE TITLE
[IMPROVEMENT] Allow specify data engine version for the default storageclass during Helm installation

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#9584]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

It's better to explicitly provide option `dataEngine` for the default storageclass during Helm installation so that users don't need to 
manually modify it later

**Comment by chriscchien** [comment]
Verified **pass** on longhorn v1.8.0-dev-20241020 (https://github.com/longhorn/longhorn/commit/a1ddba33ba4ecb1b3835a0d2364cafd3c155e829)

Floowing test [steps](https://github.com/longhorn/longhorn/issues/9584#issuecomment-2396317373), default storageclass `longhorn` has parameter `dataEngine: v2`. After install complete, dynamic provision v2 volume using starageclass `longhorn` success without any problems.
