### ISSUE TITLE
UI: edit node modal requires 1300px width

### ISSUE THREAD

**Issue by tedder** [longhorn/longhorn#959]
It'd be nice if the 'edit node' modal degraded gracefully. Anything less than 1300px means horizontal scrolling is required, and under about 1180px the "add disk" and "save" buttons are past the fold, which makes the UI very difficult to use.

The 'node' screen degrades poorly under 1020px, it seems the modal should at work at that pixel width.

I'm on Chrome, Ubuntu, HiDPI, using the v0.7.0 release of Longhorn. Some quick testing gives this matrix:

browser, OS, main 'node' width minimum, node modal width minimum
Chrome, Linux: 1020px, 1300px
Firefox, Linux: 1700px, 1300px
Chrome, MacOS: 1020px, 1300px
Firefox, MacOS: 1520px, 1180px
Safari, MacOS: 1040px, 1315px

Obviously the Firefox experience is less than ideal. In fact on the MacOS version it is wider than my laptop (Mac Air 13", retina) can display.

I didn't see an issue for this though it is tangentially related to #197.

**Comment by tedder** [comment]
![ubuntu chrome edit node modal showing hidden buttons](https://user-images.githubusercontent.com/97914/70657523-d2ce2080-1c10-11ea-9619-77d5e0dcf41d.png)
![ubuntu chrome edit node modal showing minimum usable width](https://user-images.githubusercontent.com/97914/70657524-d2ce2080-1c10-11ea-82e9-3dca28032a3b.png)

**Comment by yasker** [comment]
@smallteeths can you check? I am not sure what would be the implications.

**Comment by meldafrawi** [comment]
Validation: **Partially Failed**

OS: `Ubuntu 16.04`

Steps to test:
  - Adjust screen resolution to `1280*800`
  - In node page, Click on `Edit nodes and disks`
  - `Edit nodes and disks` modal  width has been adjusted to 850px.

Browser: `Firefox v71.0`  **(Failed)**
![image](https://user-images.githubusercontent.com/18232258/71634183-8891fb00-2c22-11ea-83cb-4a12517d7c27.png)

Browser: `Google Chrome v79.0.3945.88 (Official Build)`  **(PASS)**

**Comment by meldafrawi** [comment]
Validation: **PASSED**
