### ISSUE TITLE
[BUG] v2 Volume Data Locality `Disabled` Behavior Incorrectly (Switches to `Best-Effort` After Node Drain)

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#9591]
## Describe the bug

In Longhorn `v1.8.0`, when using a v2 volume with `data locality` `disabled`, draining one of the nodes and attaching the volume to another node should result in the volume being degraded. However, the current behavior shows that the data locality is automatically set to `best-effort`.

## To Reproduce

1. Enable `Replica Node Level Soft Anti-Affinity`
2. Create `v2` volume with the `disabled` data locality setting and 3 replicas. 
3. Attach the volume to `node-2`
4. Drain `node-1` using the command `kubectl drain ryao-180-241007-w1-daedf370-d6pwt --ignore-daemonsets --delete-local-data`
5. Observe the data locality behavior.

## Expected behavior

The volume should be in a `degraded` state after draining the node, without switching to "best-effort" data locality.

## Support bundle for troubleshooting
[supportbundle_c66ac0d9-561a-4995-851e-da981b29a01a_2024-10-08T03-56-07Z.zip](https://github.com/user-attachments/files/17287158/supportbundle_c66ac0d9-561a-4995-851e-da981b29a01a_2024-10-08T03-56-07Z.zip)

## Environment

 - Longhorn version: v1.8.0-dev-20241006

## Additional context

https://github.com/longhorn/longhorn/issues/9371

**Comment by roger-ryao** [comment]
I attempted to replicate the issue multiple times but was unable to reproduce it on `v1.8.0-dev-20241103`. 
Both `v1` and `v2` volumes exhibited consistent behavior, and in the end, both volumes maintained a `healthy` status. However, the `v1` volume took longer to achieve a healthy state compared to the `v2` volume.

Additionally, after draining `node-1`, the `v2` volume replica on `node-1` was directly deleted, while the `v1` volume replica on `node-1` was marked as failed and retained for a period of time. I am unsure if this behavior difference is expected. I have attached screenshots and a support bundle for your reference.

cc @mantissahz @derekbit 

![Screenshot_20241129_095143](https://github.com/user-attachments/assets/37e04789-8ab4-4ace-ba7f-42f5d167eb0c)
![Screenshot_20241129_095158](https://github.com/user-attachments/assets/91f913fd-8aa4-4b60-b6bd-09b38cdcbd05)
[supportbundle_16a09ade-e877-408f-b271-b1a0ff0d8e05_2024-11-29T02-02-24Z.zip](https://github.com/user-attachments/files/17953571/supportbundle_16a09ade-e877-408f-b271-b1a0ff0d8e05_2024-11-29T02-02-24Z.zip)

**Comment by derekbit** [comment]
> Additionally, after draining node-1, the v2 volume replica on node-1 was directly deleted

This is expected, because the failed replica reuse is not supported yet. Thus, longhorn-manager directly deletes it for now.
cc @shuo-wu

**Comment by derekbit** [comment]
@mantissahz Let's revisit the ticket after merging failed replica reuse feature.

**Comment by derekbit** [comment]
> I attempted to replicate the issue multiple times but was unable to reproduce it on `v1.8.0-dev-20241103`. Both `v1` and `v2` volumes exhibited consistent behavior, and in the end, both volumes maintained a `healthy` status. However, the `v1` volume took longer to achieve a healthy state compared to the `v2` volume.
> 
> Additionally, after draining `node-1`, the `v2` volume replica on `node-1` was directly deleted, while the `v1` volume replica on `node-1` was marked as failed and retained for a period of time. I am unsure if this behavior difference is expected. I have attached screenshots and a support bundle for your reference.
> 
> cc [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/14231257?s=64&amp;u=9dacfda31f34292e044fa1899294499c19a47b09&amp;v=4">@mantissahz](https://github.com/mantissahz) [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/12527233?s=64&amp;u=060e8b49cee0c17182c3338cb31a5422c0f1ab1d&amp;v=4">@derekbit](https://github.com/derekbit)
> 
> ![Screenshot_20241129_095143](https://github.com/user-attachments/assets/37e04789-8ab4-4ace-ba7f-42f5d167eb0c) ![Screenshot_20241129_095158](https://github.com/user-attachments/assets/91f913fd-8aa4-4b60-b6bd-09b38cdcbd05) [supportbundle_16a09ade-e877-408f-b271-b1a0ff0d8e05_2024-11-29T02-02-24Z.zip](https://github.com/user-attachments/files/17953571/supportbundle_16a09ade-e877-408f-b271-b1a0ff0d8e05_2024-11-29T02-02-24Z.zip)

@roger-ryao are v2 volume data locality `disabled` and `best-effort` correct for now?

**Comment by roger-ryao** [comment]
> > I attempted to replicate the issue multiple times but was unable to reproduce it on `v1.8.0-dev-20241103`. Both `v1` and `v2` volumes exhibited consistent behavior, and in the end, both volumes maintained a `healthy` status. However, the `v1` volume took longer to achieve a healthy state compared to the `v2` volume.
> > Additionally, after draining `node-1`, the `v2` volume replica on `node-1` was directly deleted, while the `v1` volume replica on `node-1` was marked as failed and retained for a period of time. I am unsure if this behavior difference is expected. I have attached screenshots and a support bundle for your reference.
> > cc [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/14231257?s=64&amp;u=9dacfda31f34292e044fa1899294499c19a47b09&amp;v=4">@mantissahz](https://github.com/mantissahz) [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/12527233?s=64&amp;u=060e8b49cee0c17182c3338cb31a5422c0f1ab1d&amp;v=4">@derekbit](https://github.com/derekbit)
> > ![Screenshot_20241129_095143](https://private-user-images.githubusercontent.com/104337648/390940604-37e04789-8ab4-4ace-ba7f-42f5d167eb0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMDY5MDgsIm5iZiI6MTczNTEwNjYwOCwicGF0aCI6Ii8xMDQzMzc2NDgvMzkwOTQwNjA0LTM3ZTA0Nzg5LThhYjQtNGFjZS1iYTdmLTQyZjVkMTY3ZWIwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQwNjAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzYxZjEyOTI1MDExMDA2ZjNmMTAyODhhNjNiNGRlOTNmZWE0MTkxMGM2MjMyNjMxNTg2MjY4MjkyYTI3MzJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aBdkj3M4KF70cm9mV3xyzO-x1sIm0NyRli1de46FsgY) ![Screenshot_20241129_095158](https://private-user-images.githubusercontent.com/104337648/390940608-91f913fd-8aa4-4b60-b6bd-09b38cdcbd05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMDY5MDgsIm5iZiI6MTczNTEwNjYwOCwicGF0aCI6Ii8xMDQzMzc2NDgvMzkwOTQwNjA4LTkxZjkxM2ZkLThhYTQtNGI2MC1iNmJkLTA5YjM4Y2RjYmQwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQwNjAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWE0YzVlZmI5ZGM2MGE2M2U5NTEzOGJlMGVhMTY2OGE5NzkwOWE5M2Q0MGJkMmM2NDI1MTRhYzQwMjU4MGUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4MMJOfSdmz1pHBf2yVOmfCe1GKNdrpXY3Y_FV6QjdOA) [supportbundle_16a09ade-e877-408f-b271-b1a0ff0d8e05_2024-11-29T02-02-24Z.zip](https://github.com/user-attachments/files/17953571/supportbundle_16a09ade-e877-408f-b271-b1a0ff0d8e05_2024-11-29T02-02-24Z.zip)
> 
> @roger-ryao are v2 volume data locality `disabled` and `best-effort` correct for now?
Hi @derekbit 
   Yes, v2 volume data locality set to  `disabled` and `best-effort` is correct for now

**Comment by derekbit** [comment]
Thanks @roger-ryao 
Then, are you fine with closing the issue?
