### ISSUE TITLE
[BUG] defaultSettings.backupExecutionTimeout does not take effect

### ISSUE THREAD

**Issue by vladimirsmrekar** [longhorn/longhorn#9593]
## Describe the bug

The variable `defaultSettings.backupExecutionTimeout` does not take effect.  
There is no corresponding variable in the GUI, and if it is added to `values.yaml`, it doesn't map to the Longhorn ConfigMap `longhorn-default-setting`.

## To Reproduce

Add the following variable to the Longhorn Helm release:
```
values:
    defaultSettings:
      backupExecutionTimeout: 10
```
It doesn't affect the Longhorn ConfigMap `longhorn-default-setting`, additionally, there are no such options available in the GUI.

## Expected behavior

According to the documentation, it should be possible to set the `backupExecutionTimeout` variable.

Documented: https://github.com/longhorn/longhorn/blob/99122c72d51eb154d1cc96f01cc1e380eaf39a13/chart/README.md?plain=1#L287C4-L287C41

## Support bundle for troubleshooting

/

## Environment

 - Longhorn version: 1.7.1
 - Impacted volume (PV): /
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 9
 - Node config
   - OS type and version: Linux, Ubuntu 22.04
   - Kernel version: Linux node0 5.15.0-119-generic
   - CPU per node: 8
   - Memory per node: 16/32
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 1-10G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox
 - Number of Longhorn volumes in the cluster: 100

## Additional context

/

## Workaround and Mitigation

/

**Comment by c3y1huang** [comment]
This setting will be introduced in Longhorn v1.8.0 and is not available in v1.7.1.
