### ISSUE TITLE
[IMPROVEMENT] Remove mirrored openshift image from Longhorn

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9597]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

- [x]  Use the upstream image (openshift-origin-oauth-proxy) for openshift (https://github.com/longhorn/longhorn/pull/9600)
- [x] Update  `image.openshift.oauthProxy.repository` to `""` and `image.openshift.oauthProxy.tag` to `""`. Users can specify one which they want to use when installing/updating the chart release. Further, add a comment mentioning that Longhorn team has verified `openshift-origin-oauth-proxy:4.15`. (https://github.com/longhorn/longhorn/pull/9600)
- [x] Remove that image from longhorn-image.txt, as it's not required for air-gap. (https://github.com/longhorn/longhorn/pull/9600)
- [x] Update the doc to ask users to use an upstream image. (https://github.com/longhorn/website/pull/997)

**Comment by chriscchien** [comment]
Verified **pass** on longhorn v1.8.0-dev-20241020 (https://github.com/longhorn/longhorn/commit/7fe15fce9f69914278ecb57249a007bdea3772b9)

Longhorn v1.8.0-dev-20241020  was successfully deployed on OpenShift 4.10.0-0.okd-2022-07-09-073606 using Helm and command `oc` ([ref](https://longhorn.io/docs/1.8.0/advanced-resources/os-distro-specific/okd-support/#install-with-oc-command)).
![image](https://github.com/user-attachments/assets/88744702-f80c-43c8-9219-536e3fde5e17)
