### ISSUE TITLE
Storageclasses.storage.k8s.io is forbidden: User Cannot create resource "storageclasses" in api group storage.k8s.io at the cluster scope

### ISSUE THREAD

**Issue by majerus1223** [longhorn/longhorn#960]
Rancher OS version 1.5.4
Ran through the steps as outlined https://github.com/longhorn/longhorn/blob/master/docs/csi-config.md
Installing via catalog from Rancher Management interface. Anything I should specifically provide for this?

"annotations": {
"lifecycle.cattle.io/create.helm-controller_c-gpqwj": "true"
},
"answers": {
"csi.attacherImage": "",
"csi.attacherReplicaCount": "",
"csi.driverRegistrarImage": "",
"csi.kubeletRootDir": "",
"csi.provisionerImage": "",
"csi.provisionerReplicaCount": "",
"defaultSettings.backupTarget": "",
"defaultSettings.backupTargetCredentialSecret": "",
"defaultSettings.backupstorePollInterval": "300",
"defaultSettings.createDefaultDiskLabeledNodes": "false",
"defaultSettings.defaultDataPath": "/var/lib/rancher/longhorn/",
"defaultSettings.defaultLonghornStaticStorageClass": "longhorn-static",
"defaultSettings.defaultReplicaCount": "3",
"defaultSettings.guaranteedEngineCPU": "0",
"defaultSettings.replicaSoftAntiAffinity": "true",
"defaultSettings.storageMinimalAvailablePercentage": "5",
"defaultSettings.storageOverProvisioningPercentage": "500",
"defaultSettings.taintToleration": "",
"defaultSettings.upgradeChecker": "true",
"ingress.enabled": "false",
"persistence.defaultClass": "true",
"persistence.defaultClassReplicaCount": "3",
"service.ui.type": "Rancher-Proxy"
},
"appRevisionId": "apprevision-2j6vf",
"baseType": "app",
"conditions": [ 4 items
{
"lastUpdateTime": "2019-12-12T04:00:17Z",
"status": "True",
"type": "Migrated"
},
{
"status": "Unknown",
"type": "UserTriggeredAction"
},
{
"lastUpdateTime": "2019-12-12T04:00:20Z",
"message": "failed to install app longhornstorage-p-qs6z8. Error: release longhornstorage-p-qs6z8 failed: storageclasses.storage.k8s.io is forbidden: User \"u-dp4hnbvpzk\" cannot create resource \"storageclasses\" in API group \"storage.k8s.io\" at the cluster scope\n",
"reason": "Error",
"status": "False",
"type": "Installed"
},
{
"lastUpdateTime": "2019-12-12T04:00:20Z",
"status": "True",
"type": "ForceUpgrade"
}
],
"created": "2019-12-12T04:00:17Z",
"createdTS": 1576123217000,
"creatorId": "u-dp4hnbvpzk",
"externalId": "catalog://?catalog=library&template=longhorn&version=0.7.0",
"id": "p-qs6z8:longhornstorage-p-qs6z8",
"labels": {
"cattle.io/creator": "norman",
"mcapp": "longhornstorage"
},
"links": {
"revision": "…/v3/project/c-gpqwj:p-qs6z8/apps/p-qs6z8:longhornstorage-p-qs6z8/revision",
"self": "…/v3/project/c-gpqwj:p-qs6z8/apps/p-qs6z8:longhornstorage-p-qs6z8",
"update": "…/v3/project/c-gpqwj:p-qs6z8/apps/p-qs6z8:longhornstorage-p-qs6z8"
},
"multiClusterAppId": "longhornstorage",
"name": "longhornstorage-p-qs6z8",
"namespaceId": null,
"notes": "---\n# Source: longhorn/templates/NOTES.txt\n1. Get the application URL by running these commands:\n  kubectl get po -n $release_namespace\n\n",
"projectId": "c-gpqwj:p-qs6z8",
"prune": false,
"state": "installing",
"targetNamespace": "longhornstorage-p-qs6z8",
"timeout": 300,
"transitioning": "error",
"transitioningMessage": "failed to install app longhornstorage-p-qs6z8. Error: release longhornstorage-p-qs6z8 failed: storageclasses.storage.k8s.io is forbidden: User \"u-dp4hnbvpzk\" cannot create resource \"storageclasses\" in API group \"storage.k8s.io\" at the cluster scope\n",
"type": "app",
"uuid": "e84d05eb-1c93-11ea-9438-0242ac1a0002",
"wait": false

**Comment by shuo-wu** [comment]
The error you provide means you haven't launched [this cluster role](https://github.com/longhorn/longhorn/blob/71427c97c1343048ff46b6d9b88483036549b12b/deploy/longhorn.yaml#L35) correctly. Could you check the RABC config for Longhorn?

**Comment by majerus1223** [comment]
I suppose I dont understand. Rancher was configured using a docker command, a cluster was then built with the UI. From there I manually configured each worker as defined in the docks, then followed the ui in rancher to deploy longhorn. How would I check the cluster role?

**Comment by majerus1223** [comment]
I installed version 0.6.1 instead of 0.7 and it worked. Maybe an issue with 0.7?

**Comment by majerus1223** [comment]
Tried to build another new cluster, using the UI same problems when installing with 0.6.1

**Comment by shuo-wu** [comment]
1. Previously, I missed some important info `failed to install app longhornstorage-p-qs6z8....User "u-dp4hnbvpzk" cannot create resource`. This means that the **Rancher user/account** you used doesn't have the permission to deploy StorageClass **for app Longhorn**.

2. For the upgrade from v0.6.1 to v.07.0, you can refer to [this doc](https://github.com/longhorn/longhorn/blob/master/docs/upgrade-from-v0.6.2-to-v0.7.0.md)

**Comment by majerus1223** [comment]
@shuo-wu This is an out of the box install of rancher, with a cluster deployed by rancher and I am logged in as admin. According to the doc https://github.com/longhorn/longhorn seems like all i should do is press install from the app catalog? Is there something I an run to test this? 

I have built 4 different clusters, deployed rancher management twice (one with nginx in front, one by itself) each time except on the installer fails. 

Latest message: Failed to install app longhorn-p-h8ktm. Error: release longhorn-p-h8ktm failed: storageclasses.storage.k8s.io is forbidden: User "u-tpwqefki6x" cannot create resource "storageclasses" in API group "storage.k8s.io" at the cluster scope

**Comment by majerus1223** [comment]
If i deploy using

**Comment by yasker** [comment]
The StorageClass indeed requires a Kubernetes cluster level permission. Longhorn is a system-level software, provides the storage to whole cluster, and one cluster can only have one installation. So we suggest installing Longhorn as a cluster-admin.

**Comment by majerus1223** [comment]
Got ya, maybe it should default to that role? As it is in rancher it has project role default, and no mention doc I saw . Could have missed it but man frustrating for something that was a checkbox.

**Comment by yasker** [comment]
@majerus1223 You're using multiple clusters app deployment? That's the only place I saw with selection of `cluster role` and `project role`. Not sure if Rancher allows any application to change the default role there, you might want to check with Rancher.

**Comment by majerus1223** [comment]
Just a single cluster, maybe add it to the deployment notes or something for rancher? Not sure what I am going to check with Rancher on really.

**Comment by yasker** [comment]
@majerus1223 Can you describe the reproduce steps, e.g. when did you click on the Rancher UI step by step?

**Comment by majerus1223** [comment]
Yep for sure..

Built a cluster with Rancher.
Created a project named "Longhornstorage"
Navigated back to main cluster page
Clicked "Apps" on the top bar
Pressed "Launch" in the upper right hand corner
Selected "longhorn"
In the long horn configuration options
Typed in name "longhornstorage"
Selected the target "Longhornstorage"
Did not modify "available roles" default is "project"
Scrolled to the bottom and pressed "launch"

**Comment by yasker** [comment]
@majerus1223 I think you're using the multicluster app.

On step `Navigated back to main cluster page`, if you see a list of clusters instead of what's inside the cluster, then you're at global page (instead of cluster's main page). After clicking `apps`, if you see `Multi-Cluster Apps` on the top left corner of the page, it means you're using multicluster app feature. Single cluster app doesn't need to select `target`.

To access the cluster's main page, hover over `Global`, and click the name of the cluster.

**Comment by majerus1223** [comment]
Just redeployed by clicking
Cluster Name
Selected 'Default' project
Clicked 'Apps'
Deployed longhorn with defaults. Waiting to see what that does. I honestly didnt know there was a difference between apps when selecting from the local cluster and global. If there is a difference does that mean longhorn isnt a multi cluster app?

**Comment by majerus1223** [comment]
Looks like that deployment failed.

**Comment by northway** [comment]
@yasker thanks for clearing this up, I had the same issue.

Deployment were successful btw.

**Comment by yasker** [comment]
@majerus1223 For the multicluster app, you need to manually select the role. And you still need to keep `longhorn-system` as the namespace.

Any error message from the failed deployment?

**Comment by majerus1223** [comment]
Failed to create new replica set "longhorn-driver-deployer-584b7bf585": replicasets.apps "longhorn-driver-deployer-584b7bf585" is forbidden: unable to create new content in namespace longhorn-p-85sc2 because it is being terminated; Deployment does not have minimum availability.

**Comment by majerus1223** [comment]
ReplicaSet "longhorn-driver-deployer-584b7bf585" has timed out progressing.; Deployment does not have minimum availability.

**Comment by qeternity** [comment]
There is definitely an issue with 0.7 on a clean install. 0.6.2 installs just fine, but upon upgrade the warning in OP is triggered, and then the the driver deployer image has a segfault. Or if you try to go straight to 0.7 you just hit the segfault. This is on stock Ubuntu 18.04.

**Comment by yasker** [comment]
@qeternity I think your issue is different. Which segment fault you're hitting?
