### ISSUE TITLE
[RELEASE] Release v1.7.2

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9603]
## What's the task? Please describe.
Action items for releasing v1.7.2

## Roles
- Release captain: @derekbit 
- QA captain: @yangchiu 

### Pre-Release

**The Release Captain needs to finish the following items.**

- [ ] Before creating RC1, create a new release branch for the following component repositories, and then create RC1 from the new branch. Leave the master branch for the next feature release development (This task is only needed when doing a feature release such as x.y.0).
  - longhorn-manager
  - longhorn-ui
  - longhorn-tests
  - longhorn-engine
  - longhorn-instance-manager
  - longhorn-share-manager
  - backing-image-manager
  - longhorn-spdk-engine (needed after GA)
- [x] Update `Best Practices>Operating System` in Longhorn official document.
- [x] Trigger the GA release build by [longhorn/longhorn Actions](https://github.com/longhorn/longhorn)

**The QA captain needs to coordinate the following items before the GA release.**

- [x] Regression test plan (manual)
- [x] Run e2e regression for pre-GA milestones (`install`, `upgrade`) 
- [x] Run security testing of container images for pre-GA milestones
  - [] Create security issues at upstream for unresolved CVEs in CSI sidecar images
- [x] Verify longhorn chart PR to ensure all artifacts are ready for GA (`install`, `upgrade`)
- [x] Run core testing (install, upgrade) for the GA build
  - Upgrade from the previous patch of the same feature release. 
  - Upgrade from the last patch of the previous feature release.
 
### Release

**The Release Captain needs to finish the following items.**

- [x] Release note - Release Captain (https://github.com/longhorn/longhorn/pull/9680)
  - [x] Deprecation note
  - [x] Upgrade notes including highlighted notes, deprecation, compatible changes, and others impacting the current users
- [x] Publish the new version of doc and add a next patch version of dev doc. (https://github.com/longhorn/website/pull/1005)
- [x] Release longhorn/chart from the release branch to publish to [ArtifactHub](https://artifacthub.io/packages/helm/longhorn/longhorn) by [longhorn/charts Actions](https://github.com/longhorn/charts)
- [x] Mark the release as `latest` release in longhorn/longhorn [README.md](https://github.com/longhorn/longhorn) (https://github.com/longhorn/longhorn/pull/9675)
- [x] Mark the release as `stable` release and update stable versions in https://github.com/longhorn/longhorn/blob/master/support-versions.txt
  - For the first stable release, we need to consider several factors and reach a consensus by maintainers before claiming it stable. 
  - For any patch release after a stable release, we need to wait 1-2 weeks for user feedback.
### Post-Release

**After marking the release as a `stable` release, Release Captain needs to coordinate the following items**

- [ ] Update https://github.com/longhorn/longhorn/blob/master/deploy/upgrade_responder_server/chart-values.yaml  - @PhanLe1010 
- [ ] Add another request for the rancher charts for the next patch release - @rebeccazzzz  
- [x] Update the [support matrix](https://www.suse.com/suse-longhorn/support-matrix/) - @asettle

### Rancher Charts

**The Release Captain needs to coordinate the following items.**

- [x] Verify the chart can be installed & upgraded - QA captain
- [x] rancher/image-mirrors update - @mantissahz @PhanLe1010
- [x] rancher/charts active branches for Rancher App Marketplace - @mantissahz @PhanLe1010 

cc @longhorn/qa @longhorn/dev

**Comment by derekbit** [comment]
cc @innobead

**Comment by yangchiu** [comment]
Run e2e regression for pre-GA milestones (install, upgrade):

[v1.7.2-rc1 amd64](https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-tests-sles-amd64/89/): 0 failure
[v1.7.2-rc1 arm64](https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-tests-sles-arm64/89/): 0 failure
[v1.7.2-rc1 amd64 upgrade](https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-upgrade-tests-sles-amd64/80/): 0 failure
[v1.7.2-rc1 arm64 upgrade](https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-upgrade-tests-sles-arm64/74/): 0 failure

Run security testing of container images for pre-GA milestones:

[v1.7.2-rc1](https://ci.longhorn.io/job/private/job/image-security-scan/1597/): 13 HIGH, 0 CRITICAL
[v1.7.2-rc2](https://ci.longhorn.io/job/private/job/image-security-scan/1603/): 13 HIGH, 0 CRITICAL

**Comment by yangchiu** [comment]
Verify longhorn chart PR to ensure all artifacts are ready for GA (install, upgrade):

Verification passed for the following actions:

* Fresh install / upgrade from v1.6.3/v1.7.1 / uninstall by chart
* v1(RWX/RWO) / v2 volume replica rebuilding
* v1(RWX/RWO) / v2 volume detachment and reattachment
* Volume backup and restoration

**Comment by yangchiu** [comment]
Run core testing (install, upgrade) for the GA build:

[v1.7.2 amd64](https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-tests-sles-amd64/100/): 0 failure
[v1.7.2 arm64](https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-tests-sles-arm64/101/): 0 failure
[v1.7.2 amd64 upgrade](https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-upgrade-tests-sles-amd64/92/): 0 failure
[v1.7.2 arm64 upgrade](https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-upgrade-tests-sles-arm64/84/): 0 failure
[v1.7.2 amd64 2 stage upgrade](https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-upgrade-tests-sles-amd64/93/): 0 failure
[v1.7.2 arm64 2 stage upgrade](https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-upgrade-tests-sles-arm64/85/): 0 failure

**Comment by derekbit** [comment]
@longhorn/dev @longhorn/qa  
v1.7.2 is released. Thanks everyone's effort. Let's keep an eye on the feedback of v1.7.2.

@PhanLe1010 @mantissahz @rebeccazzzz @aspettl Let's continue the post-release after v1.7.2 is marked as `stable` version. Thank you.


cc @innobead

**Comment by derekbit** [comment]
@PhanLe1010 @mantissahz @rebeccazzzz @asettle v1.7.2 is marked as stable. You can start the post release tasks. Thank you.

**Comment by mantissahz** [comment]
The chart release PRs for Rancher were created.
https://github.com/rancher/charts/pull/4650
https://github.com/rancher/charts/pull/4651
https://github.com/rancher/charts/pull/4652

Hi @PhanLe1010,
Please review them when you are available.

cc @innobead, @derekbit, @rebeccazzzz

**Comment by yangchiu** [comment]
> The chart release PRs for Rancher were created. [rancher/charts#4650](https://github.com/rancher/charts/pull/4650) [rancher/charts#4651](https://github.com/rancher/charts/pull/4651) [rancher/charts#4652](https://github.com/rancher/charts/pull/4652)
> 
> Hi @PhanLe1010, Please review them when you are available.
> 
> cc @innobead, @derekbit, @rebeccazzzz

- [x] Verify the chart can be installed & upgraded - QA captain

**Comment by derekbit** [comment]
Hello @PhanLe1010 
We can update [master/deploy/upgrade_responder_server/chart-values.yaml](https://github.com/longhorn/longhorn/blob/master/deploy/upgrade_responder_server/chart-values.yaml). Thank you.

**Comment by derekbit** [comment]
> Hello @PhanLe1010 We can update [master/deploy/upgrade_responder_server/chart-values.yaml](https://github.com/longhorn/longhorn/blob/master/deploy/upgrade_responder_server/chart-values.yaml). Thank you.

cc @PhanLe1010

**Comment by PhanLe1010** [comment]
Sorry for the delay. I updated the server and push the PR https://github.com/longhorn/longhorn/pull/9753

**Comment by derekbit** [comment]
Thank you @PhanLe1010 @mantissahz @rebeccazzzz
