### ISSUE TITLE
[BUG] IO Saturation

### ISSUE THREAD

**Issue by frit0-rb** [longhorn/longhorn#9608]
## Describe the bug

We are running a RKE2 cluster with Longhorn 1.5.5, in any moment or case one process try to write o read from a volume, create a saturation in the worker is running the pod.

## To Reproduce

One cluster RKE2 with RHEL virtual machines hosted in Hyper-V with HDD disks

## Expected behavior

No saturation IO disks

## Environment

 - Longhorn version: 1.5.5
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 5
 - Node config
   - OS type and version: RHEL 8.10
   - Kernel version:
   - CPU per node: 110
   - Memory per node: 120 GB
   - Disk type (e.g. SSD/NVMe/HDD): HDD
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Hyper-V Baremetal
 - Number of Longhorn volumes in the cluster:  43

**Comment by derekbit** [comment]
Currently, Longhorn doesn't support QoS. The feature is in our feature plan. Please follow up https://github.com/longhorn/longhorn/issues/750.

What you can do is to limit the IO requests in the application level.

**Comment by derekbit** [comment]
cc @PhanLe1010 @shuo-wu @c3y1huang @innobead

**Comment by frit0-rb** [comment]
> QoS

Hi @derekbit How can I Limit the IO request in the application level? Dou you have any idea?
