### ISSUE TITLE
[DOC] Document tested version of csi-snapshotter

### ISSUE THREAD

**Issue by jeidsath** [longhorn/longhorn#9609]
## What's the document you plan to update? Why? Please describe

The [csi-snapshot-support](https://longhorn.io/docs/1.7.1/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/) document states

> Longhorn v1.7.1 uses CSI external-snapshotter v6.3.2

However, it appears that the [testing framework](https://github.com/longhorn/longhorn/blob/v1.7.1/deploy/longhorn-images.txt#L4) uses v7.0.2

Is there a way to keep the tested version and this document in better sync?

**Comment by derekbit** [comment]
Completed.
