### ISSUE TITLE
[IMPROVEMENT] Update longhorn-share-manager's nfs-ganesha to v6.2

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9614]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Update longhorn-share-manager's nfs-ganesha to v6.2 #9614

**Comment by derekbit** [comment]
cc @james-munson

**Comment by chriscchien** [comment]
Verified **pass** on longhron master(https://github.com/longhorn/longhorn-share-manager/commit/dc1e4209ae2669a6da9439dc55564988535317cc)

- Perform test cases in test_rwx.py the [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7735/testReport/tests/) all passed
- e2e  case `Disconnect Volume Node Network While Workload Heavy Writing` [passed](https://ci.longhorn.io/job/private/job/longhorn-e2e-test/2011/)
