### ISSUE TITLE
[BUG] environment_check script does not work with aliased kubectl

### ISSUE THREAD

**Issue by MaKraMc** [longhorn/longhorn#9620]
## Describe the bug

https://github.com/longhorn/longhorn/blob/fae17df8076a8b8630394f283b556cf17d2a720e/scripts/environment_check.sh#L132

I have my kubectl in directory `/var/lib/rancher/rke2/bin/kubectl` and setup an alias to that path.
`which` is not able to find aliased commands and the function `check_local_dependencies` therefore fails.

## To Reproduce

Have kubectl not on path. Create alias to kubectl

## Expected behavior

check_local_dependencies finds /var/lib/rancher/rke2/bin/kubectl and returns true.

## Support bundle for troubleshooting

*Not applicable*

## Environment

 - Longhorn version: v1.6.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 24.04
   - Kernel version: 6.8.0-45-generic
   - CPU per node: 2
   - Memory per node: 8GB
   - Disk type (e.g. SSD/NVMe/HDD): VMWare Virtual Disk
   - Network bandwidth between the nodes (Gbps): 10Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 2

## Additional context

I think a fix would be beneficial to other rke2 users aswell since a standard rke2 installation usually does not involve symlinking or editing of $PATH.

## Workaround and Mitigation

A workaround I found is adding this directory to $PATH: `export PATH=$PATH:/var/lib/rancher/rke2/bin`
Another thing that should work is symlinking kubectl into a directory on $PATH.

## Possible Fix

Instead of using `which`, using bash command `type` or `type -t` returns a string that should satisfy the condition even when using alias.

**Comment by derekbit** [comment]
I don't think this is bug, because environment_check or longhorn commandline (longhornctl) doesn't know the kubernetes distro in the cluster and doesn't find the kubectl in the system. Users need to add this directory containing the kubectl binary to $PATH by themselves.
