### ISSUE TITLE
[IMPROVEMENT] Reorganize `QA/DevOps Sprint` project board and define the workflow for QA/DevOps task tickets.

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9624]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The ticket aims to:
- Reorganize [`QA/DevOps Sprint`](https://github.com/orgs/longhorn/projects/4) project board to manage the QA/DevOps sprint tasks more effectively and make them easier to visualize.
- Define the workflow for QA/DevOps task tickets.

### Labels
Tickets labeled with kind/test can be categorized into three groups:

- Automation e2e tests for issue tickets
- Automation e2e tests converted from existing manual test cases
- Negative tests

The latter two groups currently have higher priority and will be labeled as `area/manual-to-automation-testing` and `area/negative-testing`, respectively. This will allow us to quickly identify and manage these tickets by using the corresponding labels.

### Status of an QA/DevOps Ticket

- The status of an QA/DevOps ticket will be like a ticket in the `Longhorn Sprint` board but without `Ready For Testing` 
  - New Issues 
  - Icebox
  - Analysis and Design
  - Implement
  - Review

QA needs to update `Status` field accordingly.

### Sprint

- QA needs to update the `Sprint` field accordingly.
- The Sprint field of any non-closed ticket will be cleared when starting a new sprint. QA needs to set the `Sprint` and clearly understand and manage the status of the ticket.

**Comment by derekbit** [comment]
cc @longhorn/qa @khushboo-rancher @innobead

**Comment by derekbit** [comment]
Update the [Issue Management](https://github.com/longhorn/longhorn/wiki/Issue-Management) .
cc @longhorn/dev @longhorn/qa @khushboo-rancher @innobead

**Comment by derekbit** [comment]
Completed.

**Comment by innobead** [comment]
cc @bk201 @Yu-Jack
