### ISSUE TITLE
[BUG][v1.7.x] Disks modal broken layout

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9629]
## Describe the bug

Disks modal broken layout:

![broken](https://github.com/user-attachments/assets/bf26d244-a80d-4fca-b36f-74aef2449714)

## Environment

 - Longhorn version: v1.7.x-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: ubuntu 22.04
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by mantissahz** [comment]
cc @a110605

**Comment by derekbit** [comment]
@a110605 This will block the v1.7.2 release. Please help resolve it. Thank you.

**Comment by a110605** [comment]
I will handle it soon.

**Comment by roger-ryao** [comment]
**Verified on master-head 20241015**

- longhorn-ui master-head https://github.com/longhorn/longhorn-ui/commit/05d8d9145d8093747000dd9b5d8956e86ef244c9

**Verified on v1.7.x-head 20241015**

- longhorn-ui v1.7.x-head https://github.com/longhorn/longhorn-ui/commit/7b0306e2fcdf129dd2b581653bca8164ac123126


**Result passed**

![Screenshot_20241015_150921](https://github.com/user-attachments/assets/e19ac472-8856-4393-8dee-f4e99fbcab0b)
![Screenshot_20241015_145829](https://github.com/user-attachments/assets/2479efde-542c-40e6-8338-6422cb9cfdf9)
