### ISSUE TITLE
[BUG][v1.7.x] nvme diskDriver detected auto not nvme

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#9630]
## Describe the bug

According to https://github.com/longhorn/longhorn/issues/7672#issuecomment-1956174494, diskDriver of a nvme disk should be `nvme` not `auto`, but in v1.7.2-rc1, it is `auto`, it may need to calrify if this is correct behavior

![image](https://github.com/user-attachments/assets/1dec72d8-a9a9-409b-9e3c-62eaa43200b4)

diskDriver = `auto`
![image](https://github.com/user-attachments/assets/0a243fbb-cc24-43d6-a68b-95af53f10a6f)

## To Reproduce

1. Create a LH clusters using AWS EC2 c5d.2xlarge machines with a NVMe disk
2. enable v2 data engine
3. Get the BDF of the disk by checking ls -al /sys/block
4. Add the disk to node.disks
5. diskDriver = `auto`

## Expected behavior

Should diskDriver = `nvme` or the test steps need to be updated.

## Support bundle for troubleshooting

[supportbundle_46b183b3-17dc-4f60-bd5b-d0066d8ddbe4_2024-10-14T03-38-30Z.zip](https://github.com/user-attachments/files/17359061/supportbundle_46b183b3-17dc-4f60-bd5b-d0066d8ddbe4_2024-10-14T03-38-30Z.zip)

## Environment

 - Longhorn version: v1.7.2-rc1
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS EC2 c5d.2xlarge

**Comment by derekbit** [comment]
@chriscchien The behavior is expected and doesn't differ the steps. Anything wrong?


![Image](https://github.com/user-attachments/assets/1cb38e7a-77df-412f-a223-a124c73f9cc4)

**Comment by chriscchien** [comment]
Close as this is not a issue, it should check `status.diskStatus` not `spec` field. I am sorry for any inconvenience.
