### ISSUE TITLE
Longhorn Engine shoing incompatible - Isues Upgrading Longhorn Volumes After EKS Upgrade

### ISSUE THREAD

**Issue by othapall** [longhorn/longhorn#9635]
### Discussed in https://github.com/longhorn/longhorn/discussions/9634

<div type='discussions-op-text'>

<sup>Originally posted by **othapall** October 14, 2024</sup>
Hi everyone,

I've recently upgraded my AWS EKS cluster from version 1.29 to 1.30 and also upgraded Longhorn from version 1.5.3 to 1.6.2. However, I'm encountering an issue where I'm unable to upgrade the Longhorn volumes to the new engine version (1.6.2). The engine status shows as "incompatible."

Details:
EKS Version: 1.30
Longhorn Version: 1.6.2
Previous Longhorn Version: 1.5.3

Steps Taken:
Upgraded EKS cluster to 1.30.
Upgraded Longhorn to 1.6.2 via the Longhorn UI.
Attempted to upgrade existing Longhorn volumes to use the new engine.

Observations:
The Longhorn UI indicates that the engine version is incompatible with the current volumes.
UI Showing error failed to get the parameters: failed to get target node ID: failed to find a node that is ready and has the default engine image dockerhub/longhornio/longhorn-engine:v1.6.2 deployed.

All the pods running fine on longhorn namesapce.

Questions:
Is there a known issue with upgrading Longhorn volumes from 1.5.3 to 1.6.2 after an EKS upgrade?
Are there any recommended steps to resolve the incompatibility and successfully upgrade the volumes?
Should I consider any specific settings or configurations during the upgrade process?
Any insights or guidance would be greatly appreciated!

Thanks in advance!

</div>

**Comment by c3y1huang** [comment]
Can you provide the support bundle?

**Comment by othapall** [comment]
There is no orphaned replicas. Cluster was detroyed to provide support bundle.  I have built new cluster directly from eks 1.30 with  lh 1.6.1.

It also reporting Volume provison failed 

  Warning  ProvisioningFailed    48m                   driver.longhorn.io_csi-provisioner-6db56ff5bb-js44v_fd9e0734-24fb-452a-b0b3-e7aa796e9728  failed to provision volume with StorageClass "default-rwo": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [detail=, message=failed to get the parameters: failed to get target node ID: failed to find a node that is ready and has the default engine image prod.harbor.keysight.digital/cache-dockerhub/longhornio/longhorn-engine:v1.6.1 deployed, code=Internal Server Error] from [http://longhorn-backend:9500/v1/volumes]

**Comment by c3y1huang** [comment]
>There is no orphaned replicas. Cluster was detroyed to provide support bundle. 

Are you able to provide the support bundle?

>I have built new cluster directly from eks 1.30 with lh 1.6.1.
>
>It also reporting Volume provison failed

So far, I've not been able to reproduce this issue on EKS with the same Longhorn version. I also tried the upgrade path provided in the issue description, but I did not encounter the problem.

```
> k get nodes
NAME                                            STATUS   ROLES    AGE     VERSION
ip-10-0-1-122.ap-southeast-1.compute.internal   Ready    <none>   7m1s    v1.30.4-eks-a737599
ip-10-0-1-225.ap-southeast-1.compute.internal   Ready    <none>   6m58s   v1.30.4-eks-a737599
ip-10-0-2-232.ap-southeast-1.compute.internal   Ready    <none>   7m7s    v1.30.4-eks-a737599

> k -n longhorn-system get daemonset longhorn-manager -o yaml | grep image:
        image: longhornio/longhorn-manager:v1.6.1

> k -n longhorn-system get volume
NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE          NODE                                            AGE
pvc-6abc5993-55bd-4ada-9f4a-676937116c73   v1            attached   healthy                  21474836480   ip-10-0-1-225.ap-southeast-1.compute.internal   40s

> k get pod
NAME     READY   STATUS    RESTARTS   AGE
demo-0   1/1     Running   0          42s
```

> Warning ProvisioningFailed 48m driver.longhorn.io_csi-provisioner-6db56ff5bb-js44v_fd9e0734-24fb-452a-b0b3-e7aa796e9728 failed to provision volume with StorageClass "default-rwo": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [detail=, message=failed to get the parameters: failed to get target node ID: failed to find a node that is ready and has the default engine image dockerhub/longhornio/longhorn-engine:v1.6.1 deployed, code=Internal Server Error] from [http://longhorn-backend:9500/v1/volumes]

BTW, I noticed that you are using a non-default StorageClass. Could you provide the exact steps to reproduce this issue?

**Comment by othapall** [comment]
we are attaching support bundle. We are using custom Vaules and Upgradeing via Terraform.

Values
=========
#
# Copyright Keysight Technologies, All Rights Reserved
# Keysight Confidential
#
persistence:
  defaultClass: false
  defaultClassReplicaCount: 1

defaultSettings:
  backupTarget: ${longhorn-backup-target}
  backupTargetCredentialSecret: ${longhorn-creds}
  # this is deprecated in v1.1.1. this means reserve 5% of any given Node's CPU 
  guaranteedEngineCPU: 0.05
  defaultDataPath: "/data/longhorn"
  defaultDataLocality: best-effort

resources: 
  requests: 
    cpu: 20m

ingress:
  enabled: true

  host: ${longhorn-host}
  tls: true
  tlsSecret: ${wildcard-cert-secret}

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-url: "https://${oauth2-proxy-host}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://${oauth2-proxy-host}/oauth2/start?rd=https%3A%2F%2F$host$escaped_request_uri"

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: ${roleArn}

image:
  longhorn:
    manager:
      # TODO: Revisit when Longhorn Support have a permanent fix for CLOUD-5521
      repository: ${longhorn_mgr_image_repo}
      tag: ${longhorn_mgr_image_tag}
preUpgradeChecker:
  jobEnabled: false
  upgradeVersionCheck: false

**Comment by othapall** [comment]
[supportbundle_6ced9fa7-c2e8-4586-ab8f-d8a9ed51bd22_2024-10-16T15-45-42Z.zip](https://github.com/user-attachments/files/17398660/supportbundle_6ced9fa7-c2e8-4586-ab8f-d8a9ed51bd22_2024-10-16T15-45-42Z.zip)

**Comment by othapall** [comment]
what needs to be done to correct the inconsistency.

**Comment by c3y1huang** [comment]
> what needs to be done to correct the inconsistency.

You could try to update the longhorn-manger to version 1.6.3. It looks like other components are somehow up-to-date, except the manager.
```
          - longhorn-manager
          - -d
          - daemon
          - --engine-image
          - prod.harbor.keysight.digital/cache-dockerhub/longhornio/longhorn-engine:v1.6.3
          - --instance-manager-image
          - prod.harbor.keysight.digital/cache-dockerhub/longhornio/longhorn-instance-manager:v1.6.3
          - --share-manager-image
          - prod.harbor.keysight.digital/cache-dockerhub/longhornio/longhorn-share-manager:v1.6.3
          - --backing-image-manager-image
          - prod.harbor.keysight.digital/cache-dockerhub/longhornio/backing-image-manager:v1.6.3
          - --support-bundle-manager-image
          - prod.harbor.keysight.digital/cache-dockerhub/longhornio/support-bundle-kit:v0.0.43
          - --manager-image
          - prod.harbor.keysight.digital/cache-dockerhub/longhornio/longhorn-manager:v1.5.3
          - --service-account
          - longhorn-service-account
```

> image:
longhorn:
manager:
repository: ${longhorn_mgr_image_repo}
tag: ${longhorn_mgr_image_tag}
preUpgradeChecker:
jobEnabled: false
upgradeVersionCheck: false

I don't know if it's possible that `${longhorn_mgr_image_tag}` in your Terraform config is contributing to this issue. I'd suggest verifying that this variable is set to v1.6.3.

**Comment by othapall** [comment]
Thank you ..Its helped to resolve the issue.
