### ISSUE TITLE
[TEST] Volumes could become faulted after all worker nodes are rebooted

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9637]
## Describe the bug

When running all negative test cases with the following options:

```
-i \"negative\" --exclude \"cluster\" --exclude \"storage-network\" -v LOOP_COUNT:1 -v RETRY_COUNT:259200
```

During the execution of test case `Reboot Node One By One While Workload Heavy Writing`, after all worker nodes are rebooted, volumes will be  in `faulted` state indefinitely and cannot recover:

![faulted0](https://github.com/user-attachments/assets/28794b4d-0ff3-48eb-a8c5-49b4ef91278a)

But all worker nodes are back online and schedulable without any issues:

![faulted1](https://github.com/user-attachments/assets/d7581984-4e5c-4a2d-ad60-dbfaae65104a)

https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1722/console

http://44.218.163.191:30000/

## To Reproduce

Run robot test with the following options

```
-i \"negative\" --exclude \"cluster\" --exclude \"storage-network\" -v LOOP_COUNT:1 -v RETRY_COUNT:259200
```

can consistently reproduce this issue.

However, if running `Reboot Node One By One While Workload Heavy Writing` solely, it passes consistently and cannot reproduce this issue.

## Support bundle for troubleshooting

[supportbundle_cacc858f-5b9f-4d53-8093-1e633e63c1d7_2024-10-15T04-53-05Z.zip](https://github.com/user-attachments/files/17372865/supportbundle_cacc858f-5b9f-4d53-8093-1e633e63c1d7_2024-10-15T04-53-05Z.zip)

## Environment

 - Longhorn version: v1.7.x-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: sles 15-sp6
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by ChanYiLin** [comment]
Hi @yangchiu 
Did we encounter this issue before?

**Comment by derekbit** [comment]
> Run robot test with the following options
> ```
> -i \"negative\" --exclude \"cluster\" --exclude \"storage-network\" -v LOOP_COUNT:1 -v RETRY_COUNT:259200
> can consistently reproduce this issue.
> ```
> However, if running Reboot Node One By One While Workload Heavy Writing solely, it passes consistently and cannot reproduce this issue.

What's the difference after introducing -i \"negative\" --exclude \"cluster\" --exclude \"storage-network\" -v LOOP_COUNT:1 -v RETRY_COUNT:259200? Which option caused the issue?

**Comment by innobead** [comment]
@derekbit Let's remember to change the milestone to 1.8.0 with a backport label for 1.7.2 if needed later.

**Comment by derekbit** [comment]
@yangchiu 
The auto-salvage setting is set to `false`, so `cannot recover` is expected.
Can you check if it is intended? If NO, need to check the test steps.

**Comment by innobead** [comment]
If there is a workaround, for example, the volumes are eventually recovered by auto salvage, we can make this as P1 instead 0 after discussing with @derekbit .

**Comment by yangchiu** [comment]
Require https://github.com/longhorn/longhorn-tests/pull/2080 to reset settings. cc @longhorn/qa
