### ISSUE TITLE
namespace "longhorn-system" not delete (long\10h)

### ISSUE THREAD

**Issue by pomazanbohdan** [longhorn/longhorn#964]
```
- Checking for namespaces in Terminating status... found!

  -- Cheking resources in namespace longhorn-system... found!

     --- engineimage.longhorn.io/ei-ec95b5ad
     --- instancemanager.longhorn.io/instance-manager-r-ecdc4a80
     --- instancemanager.longhorn.io/instance-manager-e-dba148c3
     --- instancemanager.longhorn.io/instance-manager-r-f2ac0d62
     --- instancemanager.longhorn.io/instance-manager-e-77531120
     --- instancemanager.longhorn.io/instance-manager-e-703a1654
     --- instancemanager.longhorn.io/instance-manager-r-77a1318c

```
Longhorn - v0.7.0
v1.16.3-k3s.2

**Comment by Pomazan-Bogdan** [comment]
If i put "kubectl delete crd --namespace longhorn-system --all" command delete and data from rio-system.

**Comment by Pomazan-Bogdan** [comment]
`apiVersion: longhorn.io/v1beta1
kind: InstanceManager
metadata:
  creationTimestamp: "2019-12-15T20:32:12Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2019-12-15T20:42:07Z"
  finalizers:
  - longhorn.io
  generation: 2
  labels:
    longhorn.io/component: instance-manager
    longhorn.io/engine-image: ei-ec95b5ad
    longhorn.io/instance-manager-type: engine
    longhorn.io/node: node3.pomazan.xyz
  name: instance-manager-e-703a1654
  namespace: longhorn-system
  ownerReferences:
  - apiVersion: longhorn.io/v1beta1
    blockOwnerDeletion: true
    kind: EngineImage
    name: ei-ec95b5ad
    uid: 82fe11d8-5875-455d-bd71-782fbfaf9607
  resourceVersion: "54794"
  selfLink: /apis/longhorn.io/v1beta1/namespaces/longhorn-system/instancemanagers/instance-manager-e-703a1654
  uid: 587dd94d-e317-4f00-92cb-c4bb914c7c13
spec:
  engineImage: ei-ec95b5ad
  nodeID: node3.pomazan.xyz
  type: engine
status:
  currentState: running
  instances: {}
  ip: 10.42.2.15
  ownerID: node1.pomazan.xyz
`

**Comment by shuo-wu** [comment]
1. The CRD resource is cluster-level resource hence `-n longhorn-system` doesn't work
2. The Longhorn related CRDs have the suffix `longhorn.io` or `longhorn.rancher.io`. 
3. How to delete those CRDs:
```
kubectl patch -p '{"metadata":{"finalizers": null}}' <Longhorn related CRDs>
kubectl delete crd <Longhorn related CRDs>
```

**Comment by Pomazan-Bogdan** [comment]
kubectl patch -p '{"metadata":{"finalizers": null}}' instancemanager.longhorn.io/instance-manager-r-ecdc4a80
Error from server (NotFound): instancemanagers.longhorn.io "instance-manager-r-ecdc4a80" not found

**Comment by shuo-wu** [comment]
1. The deletion of the objects was blocked by the finalizers. Once the finalizers were removed, the objects can be cleaned up immediately.

2. You can directly delete the CRD itself. e.g.:
```
kubectl patch -p '{"metadata":{"finalizers": null}}' instancemanager.longhorn.io
kubectl delete crd instancemanager.longhorn.io
```
