### ISSUE TITLE
[TEST] Node network disconnection test case failed, volume is expected to auto-reattach but it remains faulted

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9649]
## Describe the bug

When running network disconnection related robot test with options:

```
-s \"network_disconnect\" --exclude \"cluster\" --exclude \"storage-network\" -v LOOP_COUNT:1 -v RETRY_COUNT:259200
```

There is a chance (`reproducibility ~ 1/3`) that test case `Node Disconnect And No Replica On Disconnected Node` fails to reattach the volume after the networking recovers, leaving the volume in faulted state:

![network0](https://github.com/user-attachments/assets/06a9262f-8217-4ec1-be17-d5ed8ca4308a)

![network1](https://github.com/user-attachments/assets/f9e81048-32f1-402f-b584-b392c84bf668)

https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1785/console

http://54.242.240.154:30000/#/dashboard

The test case is like:

```
Node Disconnect And No Replica On Disconnected Node
    [Documentation]    -- Manual test plan --
    ...                Disable auto-salvage.
    ...                Create a volume with 2 replicas on the 1st and the 2nd node.
    ...                Attach the volume to the 3rd node.
    ...                No need to write data to the volume. Directly disconnect the network of the node that the volume attached to for 100 seconds. (sudo nohup ./network_down.sh 100)
    ...                Wait for the node back.
    ...                The volume will be in an attached state with its robustness unknown at first, then the volume become healthy.
    Given Set setting auto-salvage to false

    When Create volume 0 with 10 GB and no replicas on the attached node
    And Disconnect volume 0 node network for 100 seconds without waiting for completion

    Then Wait for disconnected node back
    And Wait for volume 0 attached
    And Wait for volume 0 healthy
```

The test case is derived from case 2-1 of manual test case https://github.com/longhorn/longhorn-tests/blob/v1.5.x/docs/content/manual/pre-release/node-not-ready/node-disconnection/node-disconnection.md

## To Reproduce

Run robot test cases with options:

```
-s \"network_disconnect\" --exclude \"cluster\" --exclude \"storage-network\" -v LOOP_COUNT:1 -v RETRY_COUNT:259200
```

## Support bundle for troubleshooting

[supportbundle_95434e4a-5b3d-473c-9031-09573b89fd60_2024-10-16T09-47-18Z.zip](https://github.com/user-attachments/files/17393421/supportbundle_95434e4a-5b3d-473c-9031-09573b89fd60_2024-10-16T09-47-18Z.zip)

## Environment

 - Longhorn version: v1.7.x-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: sles 15-sp6
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Workaround and Mitigation

Set `auto-salvage` to true

**Comment by derekbit** [comment]
@ChanYiLin Can you help check the issue? BTW, the auto-salvage is still `false`

**Comment by ChanYiLin** [comment]
ref: https://github.com/longhorn/longhorn-tests/blob/v1.5.x/docs/content/manual/pre-release/node-not-ready/node-disconnection/node-disconnection.md

**Comment by ChanYiLin** [comment]
ref: https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1810/parameters/
This is a successful `network_disconnect` test

**Comment by yangchiu** [comment]
> I wonder if it was because we didn't cancel the IO from the previous test

@ChanYiLin Thanks for the great finding! That’s a very reasonable assumption. I’ll work on improving this part and see if it helps the test pass. Really appreciate your efforts!

**Comment by derekbit** [comment]
@yangchiu We can spend more effort on addressing similar improper test steps that have recently caused some false alarms and ensure the environment is correct for each test case.

cc @longhorn/qa

**Comment by ChanYiLin** [comment]
I suggest we can use different volume/pod/resource name in each test
To reduce the chance of interference and also make the debug easy
It is hard to look up the logs when every test use the same resources name
cc @yangchiu

**Comment by derekbit** [comment]
@yangchiu We can spend more effort on addressing similar improper test steps ,that have recently caused some false alarms and interruptions, and ensure the environment is correct for each test case.

Besides @ChanYiLin's [suggesgtion](https://github.com/longhorn/longhorn/issues/9649#issuecomment-2421038157), QA or reporter need to check all settings and environment configuration are set as expected before creating a BUG ticket. Then, this will reduce the possibility of these kinds of false alarms.

cc @longhorn/qa @khushboo-rancher @innobead

**Comment by innobead** [comment]
Sounds good. However, from the test case implementation perspective, we still need to figure out why those resources are not cleaned up successfully. @longhorn/qa
