### ISSUE TITLE
docs - creating new identical backup schedule

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#966]
When creating a new backup schedule for a volume that was restored, will existing backups be taken into account by the `Retain` policy?

For example:

Old schedule `Schedule: 00:00 every day`
New schedule `Schedule: 00:00 every day`

**Comment by yasker** [comment]
Not likely, since the `retain` policy is determined by the recurring job name. The new volume likely has a new recurring job name.

**Comment by ainiml** [comment]
> Not likely, since the `retain` policy is determined by the recurring job name. The new volume likely has a new recurring job name.

I've kept the volume name exactly the same. Are the recurring job names seeded from some some sort of volume information, or randomly generated?

**Comment by yasker** [comment]
The recurring job name is random since you can have multiple jobs for one volume.

**Comment by ainiml** [comment]
> The recurring job name is random since you can have multiple jobs for one volume.

We can see this creating extra UX effort to clean out the old backups created by the old recurring schedule

**Comment by yasker** [comment]
We can provide an option to accept the predefined recurring job name, so you can put the old recurring job name there.

But if you're concerned about the storage space used in the backup store, since it's incremental, the extra space used by the old backups are minimal.

**Comment by ainiml** [comment]
> We can provide an option to accept the predefined recurring job name, so you can put the old recurring job name there.
> 
> But if you're concerned about the storage space used in the backup store, since it's incremental, the extra space used by the old backups are minimal.

Manually inputting the old recurring name might bring us back to the same to this issue https://github.com/longhorn/longhorn/issues/946 and https://github.com/longhorn/longhorn/issues/883 and https://github.com/longhorn/longhorn/issues/935

Where manual inputting works when there are edge cases. But where it might not do so well, is when we have a few hundred volumes we'll have to individually restore their schedules
