### ISSUE TITLE
[BUG] longhornctl install preflight --operating-system=cos failed on COS_CONTAINERD

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#9664]
## Describe the bug

```
> k logs longhorn-gke-cos-node-agent-6wnxs
ERROR: Operating system ("sles") is not Container Optimized OS (cos)
```

## To Reproduce

```
longhornctl install preflight --operating-system=cos
```

## Expected behavior

```
INFO[2024-10-17T09:28:01+08:00] Initializing preflight installer             
INFO[2024-10-17T09:28:01+08:00] Cleaning up preflight installer              
INFO[2024-10-17T09:28:01+08:00] Running preflight installer                  
INFO[2024-10-17T09:28:01+08:00] Installing dependencies on Container Optimized OS (cos) 
INFO[2024-10-17T09:28:52+08:00] Installed dependencies on Container Optimized OS (cos) 
INFO[2024-10-17T09:28:52+08:00] Cleaning up preflight installer              
INFO[2024-10-17T09:28:52+08:00] Completed preflight installer. Use 'longhornctl check preflight' to check the result. 
```

## Support bundle for troubleshooting

`N/A`

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by chriscchien** [comment]
Verified **pass** on cli v1.8.0-dev-20241020(https://github.com/longhorn/cli/commit/3715dba1dfac31c0a4df0b542ba9ed6e65da9ca5)

Command ./longhornctl-linux-amd64 install preflight --operating-system=cos completed on gke node with out any problems

![image](https://github.com/user-attachments/assets/80c3405a-b7d4-4643-ab3a-c0c8ecd67b9f)
