### ISSUE TITLE
[Feature] Log level is not applied to instance manager

### ISSUE THREAD

**Issue by didlawowo** [longhorn/longhorn#9669]
## Describe the bug

when i set log level in default setting like warn, instance manager does not take effect

## To Reproduce

helm install with value. 
defaultSettings:
  logLevel: Warn

and log from instance manager: 
 [pvc-5ddf5de3-5fb1-41df-925e-c6d5da4f83a6-e-0] time="2024-10-17T05:35:24Z" level=info msg="Creating device /dev/longhorn/pvc-5ddf5de3-5fb1-41df-925e-c6d5da4f83a6 8:0" func=u 

## Expected behavior

all pod from longhorn should be set to warn log level 

 
## Environment 

 - Longhorn version:  1.6.3
 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): argocd
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3S
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: debian
   - Kernel version: 
   - CPU per node: 4
   - Memory per node: 8
   - Disk type (e.g. SSD/NVMe/HDD): nvme
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): on prem
 - Number of Longhorn volumes in the cluster: 22

**Comment by derekbit** [comment]
@james-munson will handle the log level configuration in https://github.com/longhorn/longhorn/issues/6702.
It will be included in v1.8.0.

Let's close this and use https://github.com/longhorn/longhorn/issues/6702 instead.
