### ISSUE TITLE
Disk Delete is not removing PVC from cluster 

### ISSUE THREAD

**Issue by WoodProgrammer** [longhorn/longhorn#969]
Hi all,
Longhorn is not removing pvc from at Kubernetes side, when I detach and remove the volume from the UI of longhorn .

Is that delete process executing on ISCSI side or is there a bug on kubernetes connectivity . 

Longhorn Version : 0.7.0

![Screen Shot 2019-12-18 at 6 01 17 PM](https://user-images.githubusercontent.com/16826090/71099329-279b0980-21c4-11ea-974e-317990ff49c8.png)

These are the results shown as below regarding to PVC based application . 
```
> kubectl get pvc -n rabbitmq
NAME              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-rabbitmq-0   Bound    pvc-3d6b5cb0-db41-4a8d-baf3-c3dc06c12fa3   8Gi        RWO            longhorn       38m
data-rabbitmq-1   Bound    pvc-c6790bf3-96b5-4f24-b2d3-825405452aa2   8Gi        RWO            longhorn       37m
data-rabbitmq-2   Bound    pvc-c9499cba-d276-47fe-af8b-9bd73db11b47   8Gi        RWO            longhorn       36m
data-rabbitmq-3   Bound    pvc-20543dd4-27b5-4f61-b3a1-7e33b5003184   8Gi        RWO            longhorn       35m
```

PVC's are still in there after than, that some times create circular dependecy with pods and volumes .  I do not clear undestand that situation ?

**Comment by shuo-wu** [comment]
1. Longhorn won't deleted any PVCs and PVs for the related Longhorn volume, even if the PVC is manually created by users.
2. Actually there are 2 typical ways to use Longhorn volumes:
- Manually create Longhorn volumes, PVC and PV via Longhorn UI. This means users need to **clean up all of these resource manually** later.
- Create PVC via `kubectl` with Longhorn StorageClass specified. Then the Kubernetes will provision a Longhorn volume for the PVC automatically. In the case, the Longhorn volume will be deleted automatically once the **PVC are deleted by users** (as long as the reclaim policy is the Retain).
- But in both cases, it's users' responsibility to clean up PVCs. If users need to delete the Longhorn volumes manually is decided by if the volumes are provisioned by the Kubernetes.

**Comment by WoodProgrammer** [comment]
Thanks for your information @shuo-wu but I did not understand one point what is happening, when I delete the volume which created by `kubectl` from Longhorn UI ??

**Comment by shuo-wu** [comment]
In that case, you need to clean up PVC and PV manually. It won't cause any other issues but is not recommended.
