### ISSUE TITLE
[BUG] Snapshot refuses to get pruned, no apparent info to understand why

### ISSUE THREAD

**Issue by davidfrickert** [longhorn/longhorn#9690]
## Describe the bug

I have a specific snapshot that I want to delete so it gets merged into the "main" snapshot, thus saving actual disk usage, but attempting to delete it via UI or kubectl does nothing. No errors, just nothing happens.

## To Reproduce

I have no idea how to reproduce this.

## Expected behavior

Snapshot gets deleted and data merged into parent snapshot.

## Support bundle for troubleshooting

Support bundle link sent via e-mail.

## Environment

 - Longhorn version: 1.7.2 (but i already saw this was being an issue on 1.6.x before upgrading)
 - Impacted volume (PV): pvc-60602325-d2e0-41bd-8776-c34ebcde0351
 - Impacted snapshot: volume-snap-hdd-c-d8aca792-5cdf-40d8-bb3f-0d3dac24fe43.img
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): ArgoCD Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s 1.30.5
   - Number of control plane nodes in the cluster:3
   - Number of worker nodes in the cluster: 0
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: >10

## Additional context

Some logs of instance-manager, every time i click on the delete button via UI there are these 2 logs but nothing else:

```
[pvc-60602325-d2e0-41bd-8776-c34ebcde0351-r-e917ee13] time="2024-10-21T13:08:09Z" level=info msg="Prepare removing disk hdd-c-d8aca792-5cdf-40d8-bb3f-0d3dac24fe43" func="replica.(*Server).PrepareRemoveDisk" file="server.go:280"
[pvc-60602325-d2e0-41bd-8776-c34ebcde0351-r-e917ee13] time="2024-10-21T13:08:09Z" level=info msg="Pruning overlapping chunks from volume-snap-hdd-c-d8aca792-5cdf-40d8-bb3f-0d3dac24fe43.img based on volume-head-010.img" func="rpc.(*SyncAgentServer).processRemoveSnapshot" file="server.go:1418"
[pvc-60602325-d2e0-41bd-8776-c34ebcde0351-r-e917ee13] time="2024-10-21T13:11:46Z" level=info msg="Prepare removing disk hdd-c-d8aca792-5cdf-40d8-bb3f-0d3dac24fe43" func="replica.(*Server).PrepareRemoveDisk" file="server.go:280"
[pvc-60602325-d2e0-41bd-8776-c34ebcde0351-r-e917ee13] time="2024-10-21T13:11:46Z" level=info msg="Pruning overlapping chunks from volume-snap-hdd-c-d8aca792-5cdf-40d8-bb3f-0d3dac24fe43.img based on volume-head-010.img" func="rpc.(*SyncAgentServer).processRemoveSnapshot" file="server.go:1418"
[pvc-60602325-d2e0-41bd-8776-c34ebcde0351-r-e917ee13] time="2024-10-21T13:11:49Z" level=info msg="Prepare removing disk hdd-c-d8aca792-5cdf-40d8-bb3f-0d3dac24fe43" func="replica.(*Server).PrepareRemoveDisk" file="server.go:280"
[pvc-60602325-d2e0-41bd-8776-c34ebcde0351-r-e917ee13] time="2024-10-21T13:11:49Z" level=info msg="Pruning overlapping chunks from volume-snap-hdd-c-d8aca792-5cdf-40d8-bb3f-0d3dac24fe43.img based on volume-head-010.img" func="rpc.(*SyncAgentServer).processRemoveSnapshot" file="server.go:1418"
[pvc-60602325-d2e0-41bd-8776-c34ebcde0351-r-e917ee13] time="2024-10-21T13:14:30Z" level=info msg="Prepare removing disk hdd-c-d8aca792-5cdf-40d8-bb3f-0d3dac24fe43" func="replica.(*Server).PrepareRemoveDisk" file="server.go:280"
[pvc-60602325-d2e0-41bd-8776-c34ebcde0351-r-e917ee13] time="2024-10-21T13:14:30Z" level=info msg="Pruning overlapping chunks from volume-snap-hdd-c-d8aca792-5cdf-40d8-bb3f-0d3dac24fe43.img based on volume-head-010.img" func="rpc.(*SyncAgentServer).processRemoveSnapshot" file="server.go:1418"
[pvc-60602325-d2e0-41bd-8776-c34ebcde0351-r-e917ee13] time="2024-10-21T13:16:33Z" level=info msg="Prepare removing disk hdd-c-d8aca792-5cdf-40d8-bb3f-0d3dac24fe43" func="replica.(*Server).PrepareRemoveDisk" file="server.go:280"
[pvc-60602325-d2e0-41bd-8776-c34ebcde0351-r-e917ee13] time="2024-10-21T13:16:33Z" level=info msg="Pruning overlapping chunks from volume-snap-hdd-c-d8aca792-5cdf-40d8-bb3f-0d3dac24fe43.img based on volume-head-010.img" func="rpc.(*SyncAgentServer).processRemoveSnapshot" file="server.go:1418"
[pvc-60602325-d2e0-41bd-8776-c34ebcde0351-r-e917ee13] time="2024-10-21T13:16:36Z" level=info msg="Prepare removing disk hdd-c-d8aca792-5cdf-40d8-bb3f-0d3dac24fe43" func="replica.(*Server).PrepareRemoveDisk" file="server.go:280"
[pvc-60602325-d2e0-41bd-8776-c34ebcde0351-r-e917ee13] time="2024-10-21T13:16:36Z" level=info msg="Pruning overlapping chunks from volume-snap-hdd-c-d8aca792-5cdf-40d8-bb3f-0d3dac24fe43.img based on volume-head-010.img" func="rpc.(*SyncAgentServer).processRemoveSnapshot" file="server.go:1418"
```

**Comment by derekbit** [comment]
cc @shuo-wu

**Comment by derekbit** [comment]
cc @DamiaSan @shuo-wu

**Comment by shuo-wu** [comment]
Snapshot prune is a special case of snapshot deletion. It will be triggered automatically when users try to delete the snapshot that directly stands behind the volume head. In this case, **due to the design, this snapshot cannot be removed** and coalesced with others, Longhorn will prune overlapping chunks inside the snapshot instead.

**Comment by davidfrickert** [comment]
Oh okay, didn't know that. So in this case, disk space is not wasted since the overlapping data is removed by Longhorn yes?
Is there any reason why the snapshot cannot be removed? Just wondering, since I haven't experienced this before.

**Comment by shuo-wu** [comment]
> Oh okay, didn't know that. So in this case, disk space is not wasted since the overlapping data is removed by Longhorn yes?

YES

> Is there any reason why the snapshot cannot be removed? Just wondering, since I haven't experienced this before.

It involves the Longhorn design. In Longhorn, deleting a snapshot means coalescing this snapshot with its only child. But for the prune case, the volume head data can be operated by applications/users only hence there is no way for Longhorn to coalesce the snap with the head.

**Comment by davidfrickert** [comment]
I think maybe you're describing a different scenario than mine, I have two snapshots plus volume head and one of them i wanted to delete but it didn't work (at the time of opening the issue).
Since then though I've enabled a recurrent job of snapshot-delete and it the deletion seems to be going well. Unsure why.

**Comment by DamiaSan** [comment]
Hi David, which is the snapshot do you want to delete? The oldest one or the newer one? Following what Shuo said, you can delete the older, which is at the bottom of the stack, but you can't delete the newer because it would be coalesced into the head volume.

**Comment by davidfrickert** [comment]
> Hi David, which is the snapshot do you want to delete? The oldest one or the newer one? Following what Shuo said, you can delete the older, which is at the bottom of the stack, but you can't delete the newer because it would be coalesced into the head volume.

Hmm i thought the snapshots got merged backwards? So i have an older 25TB snapshot and want to delete a 3TB newer snapshot, so i thought this would get merged into the 25TB one, or is that not how it works?

**Comment by DamiaSan** [comment]
> Hmm i thought the snapshots got merged backwards? So i have an older 25TB snapshot and want to delete a 3TB newer snapshot, so i thought this would get merged into the 25TB one, or is that not how it works?

It works int the opposite way, if you delete the 25TB snapshot it will be coalesced into the 3TB one, if you delete the 3TB one it will be coalesced in the head volume.

**Comment by davidfrickert** [comment]
Ah okay then I had the wrong idea, many thanks for the explanations! :smile:  @shuo-wu @DamiaSan
