### ISSUE TITLE
[TEST] Support CIFS and Azurite backupstore on pytest and e2e test

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#9699]
## What's the test to develop? Please describe

We already have CIFS and Azurite backupstore [manifests](https://github.com/longhorn/longhorn/tree/master/deploy/backupstores),  utilize them into our test framework, include pytest and e2e test framework.

## Describe the tasks for the test

- [x] Support CIFS backupstore on pytest
- [x] Support Azurite backupstore on pytest
- [x] Support CIFS backupstore on e2e test framework
- [x] Support Azurite backupstore on e2e test framework

## Additional context

https://github.com/longhorn/longhorn/issues/6016
https://github.com/longhorn/longhorn/issues/5283

**Comment by derekbit** [comment]
cc @longhorn/qa @khushboo-rancher

**Comment by khushboo-rancher** [comment]
Thanks for creating this ticket.
Thinking about how to run the tests with CIFS and Azurite backupstore. Currently, daily CI runs test with s3 & NFS on alternate days. We can schedule to run the test with CIFS & Azurite once per week.

|M|T|W|Th|F|S|S|
|---|---|---|---|---|---|---|
|NFS|S3|NFS|S3|NFS|CIFS|Azurite

Does it look ok?

**Comment by chriscchien** [comment]
Currently azurtize suporrted on sles. For other distros, it may need more time for implementation.

**Comment by chriscchien** [comment]
Close this ticket as test passed on pipeline after merge
- test_basic.py::test_backup : backupstore cifs [passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7746/testReport/tests/test_basic/)
- test_basic.py::test_backup : backupstore azurite [passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7747/testReport/tests/test_basic/)

**Comment by chriscchien** [comment]
- e2e case `Test Incremental Restore`  : backupstore `cifs` [passed](https://ci.longhorn.io/job/private/job/longhorn-e2e-test/2030/)
- e2e case `Test Incremental Restore` : backupstore `azurite` [passed](https://ci.longhorn.io/job/private/job/longhorn-e2e-test/2031/)
