### ISSUE TITLE
[TASK] Creation of longhorn-v24.09 branch

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9700]
## What's the task? Please describe

Update to upcoming 24.09 SPDK release

**Comment by DamiaSan** [comment]
SPDK PR https://github.com/longhorn/spdk/pull/37
go-spdk-helper updated in this PR https://github.com/longhorn/go-spdk-helper/pull/163
longhorn-spdk-engine updated in this PR https://github.com/longhorn/go-spdk-helper/pull/163
longhorn-instance-manager will be updated as soon as SPDK PR will be merged

**Comment by derekbit** [comment]
> SPDK PR [longhorn/spdk#37](https://github.com/longhorn/spdk/pull/37) go-spdk-helper PR [longhorn/go-spdk-helper#165](https://github.com/longhorn/go-spdk-helper/pull/165) longhorn-spdk-engine PR [longhorn/longhorn-spdk-engine#239](https://github.com/longhorn/longhorn-spdk-engine/pull/239) longhorn-instance-manager PR [longhorn/longhorn-instance-manager#710](https://github.com/longhorn/longhorn-instance-manager/pull/710)

Just a reminder: move the PRs link to https://github.com/longhorn/longhorn/issues/9700#issuecomment-2470377057 and fill out the list. QAs can check the list while they are going to verify it.

```
Have the backend code been merged (Manager, Engine, Instance Manager, BackupStore etc) (including backport-needed/*)?
The PR is at
```

**Comment by roger-ryao** [comment]
Hi @derekbit 
We previously had a similar ticket https://github.com/longhorn/longhorn/issues/8595, so I think we can directly close this issue. Or am I missing something?

**Comment by derekbit** [comment]
@roger-ryao Sure. Let's close this thicket.
