### ISSUE TITLE
[BUG] Failed to inspect the backup backing image information if NFS backup target URL with options

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#9702]
## Describe the bug

If the backup target URL is assigned with options like `nfs://longhorn-test-nfs-svc.default:/opt/backupstore?nfsOptions=soft,timeo=330,retrans=3`
it will fail to get the backup backing image information with the inspect API.

```txt

time="2024-10-24T02:19:22Z" level=error msg="Error inspecting backup config" func="controller.(*BackupBackingImageCo
ntroller).reconcile" file="backup_backing_image_controller.go:322" backupbackingimage=parrot001 controller=longhorn-
backup-backing-image error="failed to get backup backing image config nfs://longhorn-test-nfs-svc.default:/opt/backu
pstore?nfsOptions=soft,timeo=330,retrans=3?backingImage=parrot001: failed to execute: /var/lib/longhorn/engine-binar
ies/longhornio-longhorn-engine-master-head/longhorn [/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-ma
ster-head/longhorn backup inspect-backing-image nfs://longhorn-test-nfs-svc.default:/opt/backupstore?nfsOptions=soft
,timeo=330,retrans=3?backingImage=parrot001], output , stderr warning: GOCOVERDIR not set, no coverage data emitted\
ntime=\"2024-10-24T02:19:22Z\" level=fatal msg=\"Failed to run inspect-backing-image command\" func=cmd.BackupCmd.In
spectBackingImageCmd.func6 file=\"backup_backing_image.go:62\" error=\"invalid backing image name parsed: \"\n: exit
 status 1" node=rancher80-worker2
```

```txt
NAME        BACKINGIMAGE   SIZE      BACKUPCREATEDAT   STATE       LASTSYNCEDAT
parrot001   parrot001      1161728                     Completed   <no value>
```

## To Reproduce

1. Set up the backup target URL to `nfs://[nfs-server]:[path]?nfsOptions=soft,timeo=330,retrans=3`
2. Backup a backing image to this backup target
3. The backup backing image information will never be synchronized.
4. The backup backing image can not be deleted.

## Expected behavior

1. The backup backing image information will be synchronized.
2. The backup backing image can be deleted.

## Environment

 - Longhorn version: master-head, 1.7.x, 1.6.x
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.1+k3s1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 2
 - Node config
   - OS type and version: ubuntu 2204
   - Kernel version: 5.15.0-91-generic
   - CPU per node: 4
   - Memory per node: 4096
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 1G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 1

## Workaround and Mitigation

Temporarily change the backup target URL to the one without the NFS options as

`nfs://longhorn-test-nfs-svc.default:/opt/backupstore?nfsOptions=soft,timeo=330,retrans=3`
to
`nfs://longhorn-test-nfs-svc.default:/opt/backupstore`

**Comment by derekbit** [comment]
Great catch!

**Comment by derekbit** [comment]
cc @james-munson @ChanYiLin

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-manager 1925819) following [the test plan](https://github.com/longhorn/longhorn/issues/9702#issuecomment-2434101567).

The issue can be reproduced in `v1.7.1`.

```
$ kubectl get backupbackingimages.longhorn.io -n longhorn-system
NAME     BACKINGIMAGE   SIZE      BACKUPCREATEDAT   STATE       LASTSYNCEDAT
test                    0                                       <no value>
test-1   test-1         1161728                     Completed   <no value>

$ kubectl logs longhorn-manager-29gnf -c longhorn-manager -n longhorn-system | grep "Error inspecting backup config"
time="2024-11-04T02:52:30Z" level=error msg="Error inspecting backup config" func="controller.(*BackupBackingImageController).reconcile" file="backup_backing_image_controller.go:318" backupbackingimage=test controller=longhorn-backup-backing-image error="failed to get backup backing image config nfs://longhorn-test-nfs-svc.default:/opt/backupstore?nfsOptions=soft,timeo=330,retrans=3?backingImage=test: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.7.1/longhorn [/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.7.1/longhorn backup inspect-backing-image nfs://longhorn-test-nfs-svc.default:/opt/backupstore?nfsOptions=soft,timeo=330,retrans=3?backingImage=test], output , stderr time=\"2024-11-04T02:52:30Z\" level=fatal msg=\"Failed to run inspect-backing-image command\" func=cmd.BackupCmd.InspectBackingImageCmd.func6 file=\"backup_backing_image.go:62\" error=\"invalid backing image name parsed: \"\n: exit status 1" node=ip-10-0-1-127
```

And it's fixed in `master-head`:

```
$ kubectl get backupbackingimages.longhorn.io -n longhorn-system
NAME     BACKINGIMAGE   SIZE      BACKUPCREATEDAT        STATE       LASTSYNCEDAT
test     test           1161728   2024-11-04T02:46:05Z   Completed   2024-11-04T03:05:58Z
test-1   test-1         1161728   2024-11-04T02:53:56Z   Completed   2024-11-04T03:05:58Z
test-2   test-2         1161728   2024-11-04T03:07:12Z   Completed   2024-11-04T03:07:14Z

$ kubectl logs -l app=longhorn-manager -c longhorn-manager -n longhorn-system | grep "Error inspecting backup config"
# Empty
```
