### ISSUE TITLE
[FEATURE] implement snapshot checksum in go-spdk-helper

### ISSUE THREAD

**Issue by DamiaSan** [longhorn/longhorn#9709]

**Comment by derekbit** [comment]
This is sub-task of https://github.com/longhorn/longhorn/issues/8666, so you can add this ticket in the https://github.com/longhorn/longhorn/issues/8666#issue-2324602685. Then, QA can directly validate https://github.com/longhorn/longhorn/issues/8666.

**Comment by derekbit** [comment]
Let's close this is ticket. To reduce the burden of validation and issue management, `spdk` and `go-spdk-helper` codes should be implemented and verified together in https://github.com/longhorn/longhorn/issues/8666.

cc @DamiaSan @innobead
