### ISSUE TITLE
All nodes unschedulable after full shutdown

### ISSUE THREAD

**Issue by CaptainRedHat** [longhorn/longhorn#971]
I have a home lab with a single physical server and 2 VM's running on it for my k8s cluster one node has all roles and the other has just the worker role. I installed longhorn on my cluster through the Rancher App catalog and everything seemed to be working fine. I then needed to do some maintenance on the physical hardware, so i powered down the VM's and then the host. After I brought everything back up, Longhorn is now showing both of my nodes as unschedulable and it's showing that i have no storage space schedulable even though I have plenty of space on both the nodes. The VM's are running Ubuntu 18.04 LTS with Docker CE 19.03.5. I'm running Rancher 2.3.3, k8s 1.16.3, and longhorn 0.7.0. What can I do? The data is still there, as my pods were able to come up, but how do I get everything back to a healthy state?

**Comment by CaptainRedHat** [comment]
Additionally, I've noticed that longhorn is reporting Allocated as "50 / -749.63 Gi", used as "0 / 0 Gi", and the size as "0 Bi +150 Gi Reserved", even though I have plenty of disk space on the nodes:

`Filesystem                  Size  Used Avail Use% Mounted on
/dev/mapper/vgdata00-lvol1  500G   20G  481G   4% /var/lib/docker`

Longhorn is configured to use /var/lib/docker/longhorn as its storage location.

**Comment by CaptainRedHat** [comment]
I believe that might be the issue.
kubectl -n longhorn-system describe nodes.longhorn.io dank-memez
```
  Disk Status:
    fd0100000000:
      Conditions:
        Ready:
          Last Probe Time:
          Last Transition Time:  2019-12-18T23:03:50Z
          Message:               disk /var/lib/docker/longhorn/ on node dank-memez has changed file system
          Reason:                DiskFilesystemChanged
          Status:                False
          Type:                  Ready
        Schedulable:
          Last Probe Time:
          Last Transition Time:  2019-12-18T23:03:50Z
          Message:               the disk /var/lib/docker/longhorn/ on the node dank-memez has 0 available, but requires reserved 160981373337, minimal 10% to schedule more replicas
          Reason:                DiskPressure
          Status:                False
          Type:                  Schedulable
```
```
root@dank-memez:~# stat -fc "{\"path\":\"%n\",\"fsid\":\"%i\",\"type\":\"%T\",\"freeBlock\":%f,\"totalBlock\":%b,\"blockSize\":%S}" /var/lib/docker/longhorn
{"path":"/var/lib/docker/longhorn","fsid":"fd0000000000","type":"xfs","freeBlock":125906282,"totalBlock":131006977,"blockSize":4096}
```

How do I correct this?

**Comment by yasker** [comment]
@CaptainRedHat Here is the steps that should help to correct this issue.

1. Run `kubectl -n longhorn-system edit nodes.longhorn.io dank-memez`
2. Found `fd0100000000` in the `spec.disks` section of each node, replace it with `fd0000000000`
3. Save and exit.

**Comment by CaptainRedHat** [comment]
@yasker Thank you so much! That looks like it worked :)
