### ISSUE TITLE
[TASK] Install the latest grpc_health_probe at build time

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#9714]
## What's the task? Please describe

We use a static version of `grpc_health_probe` in the longhorn-instance-manager and ;onghorn-engine images. This could lead to missing security updates before releasing a new Longhorn version, as it is not eligible for automatic package updates via renovate. Consequently, this may result in delayed security fixes after the release.

Since `grpc_health_probe` is a mature project and has remained at version 0.4 for some time, it is still actively maintained and receives security updates. I suggest installing the latest version of `grpc_health_probe` when building a new component image to avoid any known security issues that may not be resolved before the release.

```bash
curl -s https://api.github.com/repos/grpc-ecosystem/grpc-health-probe/releases/latest | jq -r '.assets[] | select(.name | test("linux.*amd64"; "i")) | .browser_download_url'

curl -s https://api.github.com/repos/grpc-ecosystem/grpc-health-probe/releases/latest | jq -r '.assets[] | select(.name | test("linux.*arm64"; "i")) | .browser_download_url'
```

## Additional context

cc @derekbit @c3y1huang

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-engine 1f1d31a, longhorn-instance-manager 69d73aa). The latest version of `grpc_health_probe` is installed:

```
$ docker run -it longhornio/longhorn-engine:master-head grpc_health_probe -version
0.4.35; commit 0d66e8ae39ccdf7a5c22f584560692ca5cf930af


$ docker run -it longhornio/longhorn-instance-manager:master-head grpc_health_probe -version
0.4.35; commit 0d66e8ae39ccdf7a5c22f584560692ca5cf930af
```
