### ISSUE TITLE
XFS's FSID might change after reboot/remount

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#972]
E.g. https://github.com/longhorn/longhorn/issues/971

We probably need to find another way of identifying a filesystem.

**Comment by y2kenny** [comment]
I just ran into this (#971) on one of the node that got rebooted.  4 out of 6 partition fsid changed.  The kubectl edit workaround was able to fix it.

**Comment by yasker** [comment]
We might want to stop identify disks using FSID. FSID can be used when checking the disk to prevent double accounting, but it's not stable in e.g. XFS case.

**Comment by yasker** [comment]
Another usage of FSID is to prevent wrongly mounted directory. For example, if the extra disk wasn't mounted on the node when manager starts, manager will know and prevent further operation on that disk. So we also need a way to make sure the path is indeed pointed to the intended disk if we're going to replace FSID.

**Comment by yasker** [comment]
API change:
1. DiskUpdate input is now a `map[string]DiskSpec` instead of `[]DiskSpec`

UI changes:
1. Show the disk name in the UI (read-only)
2. For new disks, generate disk names like `disk-0/1/2/3` and use it as the key.
3. When passing parameters to `diskUpdate` API call, passing `map[string]DiskSpec` instead of `[]DiskSpec`.

@smallteeths ^^

**Comment by yasker** [comment]
Now LEP is available at https://github.com/longhorn/longhorn/blob/master/enhancements/20200331-replace-filesystem-id-key-in-disk-map.md

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test (1/2):
- Deploy Longhorn, root disk on each node should be schedulable on `/var/lib/longhorn`
- Add a disk to the node, where the new disk path is on existing node disk e.g `/home` or `/mnt`
- Check longhorn events, should see the following event

```
Disk disk-1(/mnt/) on node meldafrawi-x2-longhorn-01 is not ready: disk has same file system ID 58fe937c58377e45 as other disks [58fe937c58377e45 disk-1] 
```


Steps to test (1/2):
- Create 2 disks with same size, format `disk1` with ext4, and `disk2` with xfs
- Mount `disk2` to a directory  `/mnt`
- Ensure Replica Soft Anti-Affinity is enabled
- Disable scheduling on all nodes
- Add `/mnt` as new disk, now `/mnt` points to `disk2`, and enable scheduling
- Create a volume, attach it to a node, replicas should be scheduled on `disk2`
- Write data to volume and compute it's checksum checksum#1
- Detach the volume, and disable scheduling on `disk2`
- Mount `disk1` to another directory
- Copy all contents of `disk2` to `disk1`, including `longhorn-disk.cfg` file
- Unmount `/mnt`
- Ummount `disk1`
- Mount `disk1`  `/mnt`
- Enable scheduling on `/mnt`, now `/mnt` points to `disk1`
- Attach the volume, volume should be attached, , R/W operations should work.
- check data checksum, checksum should match checksum#1
- Create a new volume, replicas should be scheduled to the disk without issues
- Attach the new volume to a node, volume should be attached, R/W operations should work.
