### ISSUE TITLE
[BUG] DR volume fails to reattach and faulted after node stop and start during incremental restore

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#9752]
## Describe the bug
When I was working on the [[TEST] [ROBOT] implementation of the manual test case for 'The node the DR volume is attached to is rebooted' (#8425)](https://github.com/longhorn/longhorn/issues/8425), I discovered the issue. When the node with the attached DR volume is stopped during the incremental restore, we expect the DR volume to reattach to another available node. However, the DR volume goes into a `Faulted` state. Even after restarting the previously stopped node, the DR volume remains in a `Faulted` state and does not recover as expected.

## To Reproduce

https://longhorn.github.io/longhorn-tests/manual/pre-release/node-not-ready/node-restart/dr-volume-node-rebooted/ 
- Scenario 2
1. Create a pod with a Longhorn volume.
2. Write data to the volume and get its MD5 checksum.
3. Create the first backup for the volume.
4. Create a DR (Disaster Recovery) volume from this backup.
5. Wait for the DR volume to complete the initial restore.
6. Write more data to the original volume and get the new MD5 checksum.
7. Create a second backup for the volume.
8. During the incremental restore of the DR volume, immediately `stop` the node to which the DR volume is attached.
9. Wait for the instance status change to `stopped` and then `start` the node
10. Wait for the DR volume to detach and then reattach itself to the node.
11. Wait for the DR volume to complete the restore after reattachment.
12. Activate the DR volume and check the MD5 checksum of the data.

## Expected behavior

The DR volume should reattach to an available node and continue the restore process without entering a faulted state, even after a node reboot.

## Support bundle for troubleshooting

[supportbundle_295c69fd-6ae1-4b69-a7be-8b0b023fbf84_2024-11-04T04-08-10Z.zip](https://github.com/user-attachments/files/17613810/supportbundle_295c69fd-6ae1-4b69-a7be-8b0b023fbf84_2024-11-04T04-08-10Z.zip)

## Environment

 - Longhorn version: `master-head`
 - Impacted volume (PV): `vol-1`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: `v1.31.1+k3s1`
   - Number of control plane nodes in the cluster: `1`
   - Number of worker nodes in the cluster: `3`
 - Node config
   - OS type and version:  SLES 15-sp5 
   - Kernel version:
   - CPU per node:
   - Memory per node: 
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS
 - Number of Longhorn volumes in the cluster: `2`

## Additional context

https://github.com/longhorn/longhorn/issues/8425

## Workaround and Mitigation

N/A

**Comment by derekbit** [comment]
@roger-ryao Can you check v1.6.x and 1.7.x as well? Thanks.

**Comment by roger-ryao** [comment]
> @roger-ryao Can you check v1.6.3 and 1.7.2 as well? Thanks.

Hi @derekbit @c3y1huang 
     I tried a few more times and found that if the `DR volume` is attached to the same node as the `longhorn-test-minio pod`’s node, the issue can be reproduced. This seems to be an environment-related issue, and I still need to think about how to prevent this from happening.
     
cc @longhorn/qa

**Comment by roger-ryao** [comment]
> > @roger-ryao Can you check v1.6.3 and 1.7.2 as well? Thanks.
> 
> Hi @derekbit @c3y1huang I tried a few more times and found that if the `DR volume` is attached to the same node as the `longhorn-test-minio pod`’s node, the issue can be reproduced. This seems to be an environment-related issue, and I still need to think about how to prevent this from happening.
> 
> cc @longhorn/qa

After consulting with @yangchiu & @chriscchien , we should use a customized backup store YAML to deploy the backup store on the `control node` instead of `worker nodes`, so it won't be affected by node reboot operations.

**Comment by derekbit** [comment]
> After consulting with @yangchiu & @chriscchien , we should use a customized backup store YAML to deploy the backup store on the `control node` instead of `worker nodes`, so it won't be affected by node reboot operations.

@roger-ryao  Let's check if the issue remains after re-testing it by an external backup target.

**Comment by c3y1huang** [comment]
@roger-ryao could you also share the robot case? I cannot find in https://github.com/longhorn/longhorn/issues/8425.

**Comment by roger-ryao** [comment]
> @roger-ryao could you share the robot case? I cannot find it in #8425.

Hi @c3y1huang 
    I submitted the case at https://github.com/roger-ryao/longhorn-tests/tree/issue9752.
I haven’t submitted a PR yet since I’m still verifying the stability of the case, but it should help you clarify the issue.

**Comment by roger-ryao** [comment]
>> @roger-ryao Can you check v1.6.3 and 1.7.2 as well? Thanks.
> 
> I was able to reproduce the issue using an external backup target and will test it on v1.7.x and v1.6.x next week.
> 

I was able to reproduce the issue on `longhorn-v1.7.3-dev-20241103` using the test case (reproduced once out of four attempts), but I haven’t observed it yet on `longhorn-v1.6.4-dev-20241103` (the case is still running; no failures observed in eight attempts, will continue for four more).

For reference, the issue reproduction rate is around 25-50%.

**Comment by roger-ryao** [comment]
> > > @roger-ryao Can you check v1.6.3 and 1.7.2 as well? Thanks.
> > 
> > 
> > I was able to reproduce the issue using an external backup target and will test it on v1.7.x and v1.6.x next week.
> I was able to reproduce the issue on `longhorn-v1.7.3-dev-20241103` using the test case (reproduced once out of four attempts), but I haven’t observed any failures in 12 attempts on `longhorn-v1.6.4-dev-20241103`. I’ll continue testing on `v1.6.4` and `v1.7.2`.
> 
I haven’t observed any failures in 15 attempts on `v1.6.3`, while on `v1.7.2`, I observed only one failure in 15 attempts.

**Comment by roger-ryao** [comment]
Discussed with @c3y1huang  and assisted in replicating the issue. 
Here is a brief summary of the current test results:

We observed the issue on versions `v1.7.0`, `v1.7.2`, `v1.7.3-dev-20241103`, and `v1.8.0-dev-20241103` (We did not test `v1.7.1`, but we infer that it likely has the same issue.). However, when running the same case on `v1.6.3`, we did not observe any failures.

The support bundle for v1.7.0 ( volume `e2e-test-volume-1` ). : 
[170-supportbundle_c022ef54-5c0f-47df-acd3-2dffce86cadb_2024-11-12T05-28-01Z.zip](https://github.com/user-attachments/files/17711650/170-supportbundle_c022ef54-5c0f-47df-acd3-2dffce86cadb_2024-11-12T05-28-01Z.zip)

![Screenshot_20241112_133142](https://github.com/user-attachments/assets/d5023cb8-57b9-4733-8e91-d1ac2a94071a)

**Comment by c3y1huang** [comment]
Check with conditions (WIP):
- [ ] NFS as backup storage, cc @roger-ryao 
- [ ] Scale-up CoreDNS

**Comment by roger-ryao** [comment]
> Check with conditions (WIP):
> 
> * [ ]  Using NFS as backup storage to check if this issue is specific to S3, cc @roger-ryao

So far, after a total of 9 attempts, no failures have been observed.
I was not successful in changing the NFS backup server on the control node through the file at https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/backupstores/nfs-backupstore.yaml.
I used my external NFS server as the backup target, but the server uses the IP directory `nfs://<nfs_server_ip>:/opt/nfs`.
This might be why I couldn't replicate the issue with NFS. 

Let me try to see how I can configure my NFS server to connect using a domain name. 
Perhaps this way, I can replicate the issue when the backup target is NFS.

**Comment by c3y1huang** [comment]
After checking with @roger-ryao , we found that this issue is not reproducible when using NFS as backup storage.

The NFS list operation doesn't depend on CoreDNS because it verifies the local path directly.
https://github.com/longhorn/backupstore/blob/master/fsops/fsops.go#L113-L126

The S3 list operation checks the backup store object, which relies on the DNS resolution 
https://github.com/longhorn/backupstore/blob/master/s3/s3.go#L114

This means this issue is specific to the cloud provider storage.

**Comment by roger-ryao** [comment]
> Check with conditions (WIP):
> 
> * [ ]  Using NFS as backup storage to check if this issue is specific to S3, cc @roger-ryao
> * [ ]  Scale-up CoreDNS to check if this is a DNS resolution issue, @c3y1huang

After running it 20 times, I did not observe the volume becoming faulted when the backup target was the NFS server

**Comment by c3y1huang** [comment]
I am able to reproduce this issue with v1.6.2 by scaling down CoreDNS during the node reboot, while the other 2 replicas are rebuilding.

**Comment by roger-ryao** [comment]
**Verified on v1.8.0-dev-20241201 20241205**

- longhorn `v1.8.0-dev-20241201` https://github.com/longhorn/longhorn/commit/9e8a84bdc8b3cfc2e0cf53415ee2bc3f2d8753e2


**Result Passed**

- [x] `require/doc` : Checked documentation in https://github.com/longhorn/website/pull/1011
- [x] `DR Volume Node Reboot During Initial Restoration` & `DR Volume Node Reboot During Incremental Restoration` tested and passed.
![Screenshot_20241205_150509](https://github.com/user-attachments/assets/9f302e6c-1e78-448b-ba9c-5b2e3aee319a)
[issue9757_passed_report.tar.gz](https://github.com/user-attachments/files/18018899/issue9757_passed_report.tar.gz)
