### ISSUE TITLE
[TEST] longhorn-spdk-engine unit tests are failing

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#9761]
## What's the test to develop? Please describe

The current unit tests in [longhorn-spdk-engine](https://github.com/longhorn/longhorn-spdk-engine) are failing and need to be fixed.

## Describe the tasks for the test

- Resolve the failures.
- Ensures all tests pass in CI runs.

**Comment by c3y1huang** [comment]
@shuo-wu could you take a look?

cc @derekbit

**Comment by derekbit** [comment]
@shuo-wu Let's put in v1.8.0 and see if we can resolve it. Thank you.

cc @c3y1huang @innobead

**Comment by shuo-wu** [comment]
[This map consolidation PR](https://github.com/longhorn/longhorn-spdk-engine/pull/208) had not been updated for a long time. It breaks the repo.

I will fix it at https://github.com/longhorn/longhorn-spdk-engine/pull/234. Before the fix, I am resolving the conflicts introduced by the v2 salvage feature hence it will take some time.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn-spdk-engine `114edf`

From ci build [433](https://github.com/longhorn/longhorn-spdk-engine/actions/runs/11995558655/job/33440677644) , the unit test passed

![image](https://github.com/user-attachments/assets/9f10d557-fba0-4147-876e-807bbf2f0d46)
