### ISSUE TITLE
[BUG] Failing to decompress blocks

### ISSUE THREAD

**Issue by DizzieNight** [longhorn/longhorn#9765]
## Describe the bug

Jellyfin.db was corrupted so I decided to restore the whole volume from backup and now I cannot restore from backup, I am getting the following error:

`replica jellyfin-config-r-0fbdcc2e failed the restore: failed to wait for restore complete: failed to decompress and verify block backupstore/volumes/ca/ea/jellyfin-config/blocks/cb/6f/cb6fb12c98d4e3b271bfaadeb86813203c70f97e17d543b330a8aaec5f65b630.blk with checksum cb6fb12c98d4e3b271bfaadeb86813203c70f97e17d543b330a8aaec5f65b630: decompression verification failed for block backupstore/volumes/ca/ea/jellyfin-config/blocks/cb/6f/cb6fb12c98d4e3b271bfaadeb86813203c70f97e17d543b330a8aaec5f65b630.blk: checksum verification failed for block: failed to decompress and verify block backupstore/volumes/ca/ea/jellyfin-config/blocks/cb/6f/cb6fb12c98d4e3b271bfaadeb86813203c70f97e17d543b330a8aaec5f65b630.blk with checksum cb6fb12c98d4e3b271bfaadeb86813203c70f97e17d543b330a8aaec5f65b630: decompression verification failed for block backupstore/volumes/ca/ea/jellyfin-config/blocks/cb/6f/cb6fb12c98d4e3b271bfaadeb86813203c70f97e17d543b330a8aaec5f65b630.blk: checksum verification failed for block`

## To Reproduce

N/A

## Expected behavior

To be able to restore volume from backup.

## Support bundle for troubleshooting
https://drive.google.com/file/d/1f6jLDlykAgoT3Okcw7kQnYbemKnoZnDa/view?usp=drive_link

## Environment

 - Longhorn version: 1.7.2
 - Impacted volume (PV): jellyfin-config
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of control plane nodes in the cluster: 2
   - Number of worker nodes in the cluster: 2
 - Node config
   - OS type and version: Ubuntu 24.04 LTS
   - Kernel version: 6.8
   - CPU per node: 8
   - Memory per node: 12GB
   - Disk type (e.g. SSD/NVMe/HDD): NVMe
   - Network bandwidth between the nodes (Gbps): 1Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox
 - Number of Longhorn volumes in the cluster: 31

## Additional context

I have the backups sent to my Unraid server using NFS.

## Workaround and Mitigation

Currently nothing, Jellyfin is down.

**Comment by derekbit** [comment]
If possible, can you send the block file `backupstore/volumes/ca/ea/jellyfin-config/blocks/cb/6f/cb6fb12c98d4e3b271bfaadeb86813203c70f97e17d543b330a8aaec5f65b630.blk` to longhorn-support-bundle@suse.com for troubleshooting?

**Comment by DizzieNight** [comment]
I've sent the file through now

**Comment by derekbit** [comment]
Weird, I decompressed the block file by 
```
# lz4 -dv cb6fb12c98d4e3b271bfaadeb86813203c70f97e17d543b330a8aaec5f65b630.blk blockfile
*** LZ4 command line interface 64-bits v1.9.4, by Yann Collet ***
blockfile: decoded 2097152 bytes

# shasum -a 512 blockfile
cb6fb12c98d4e3b271bfaadeb86813203c70f97e17d543b330a8aaec5f65b630b190288081eebffeb66e4d1ea5fa200cc61061bbeb2fb1b326ccf236ae5604e7  blockfile
```

The checksum (`cb6fb12c98d4e3b271bfaadeb86813203c70f97e17d543b330`) of the file is correct...
Do you know which Longhorn version created the backup?


BTW, can you send us the file `backupstore/volumes/ca/ea/jellyfin-config/blocks/99/71/99719a6e9ad21c0e68a9c8e004609feff2924d5bf70cfb552db1e86064651263.blk`?

**Comment by DizzieNight** [comment]
1.6.2 was the version that created it. I just upgraded to 1.7.2 hoping it would help but it did nothing. I'll send that file through now

**Comment by derekbit** [comment]
> 1.6.2 was the version that created it. I just upgraded to 1.7.2 hoping it would help but it did nothing. I'll send that file through now

While decompressing the file `9719a6e9ad21c0e68a9c8e004609feff2924d5bf70cfb552db1e86064651263.blk` by `lz4` command. The file is lz4-compressed file, but the checksum is incorrect.

```
Error 66 : Decompression error : ERROR_contentChecksum_invalid
```

This might be caused by the filesystem silent corruption. All backups using the backup file will be impacted.

Would you want to check if there are other files having the same checksum error?

**Comment by DizzieNight** [comment]
Yeah I might do. Would you be able to show me the process on how to? I'm very new to all of this.

Also does that mean the backup is not recoverable at all?

**Comment by derekbit** [comment]
> Also does that mean the backup is not recoverable at all?

Yes. The [integrity check of backup ](https://github.com/longhorn/longhorn/issues/4571)is not supported yet...

> Yeah I might do. Would you be able to show me the process on how to? I'm very new to all of this.

You can write a shell script like
```
iterate all blockfile
  decompress blockfile by `lz4 -d blockfile tmpfile`
  if failed to decompress, print the blockfile path
  remove tmpfile
```

**Comment by shikanime** [comment]
I'm not sure about the version created, it was also around 1.6.x, but I also had a similar error when trying to restore a backup of around 500gb on 1.7.x.
```[sync-r-76a14b73] time="2024-11-10T23:55:53Z" level=error msg="Failed to delta restore volume sync backup backup-4a9b39a97fe54d91" func=backupstore.RestoreDeltaBlockBackup.func3 file="deltablock.go:818" error="failed to decompress and verify block backupstore/volumes/5c/4b/sync/blocks/f8/43/f843ffea950c47214d0335dfd620325ff4c46c453a488261354fb09d24b1236d.blk with checksum f843ffea950c47214d0335dfd620325ff4c46c453a488261354fb09d24b1236d: decompression verification failed for block backupstore/volumes/5c/4b/sync/blocks/f8/43/f843ffea950c47214d0335dfd620325ff4c46c453a488261354fb09d24b1236d.blk: failed to read decompressed data: lz4: invalid source or destination buffer too short"```

**Comment by derekbit** [comment]
@shikanime 
According to the error `failed to read decompressed data: lz4: invalid source or destination buffer too short`, it looks like a bug in pierrec/lz4. Could you post the issue in https://github.com/pierrec/lz4/issues/195? BTW, can you share the block file f843ffea950c47214d0335dfd620325ff4c46c453a488261354fb09d24b1236d.blk?

**Comment by shikanime** [comment]
@derekbit here's the block https://drive.google.com/file/d/1ikCTGzfjbN188Qi_iPDq8GqGTaqcKvlx/view?usp=sharing

**Comment by derekbit** [comment]
> @derekbit here's the block [drive.google.com/file/d/1ikCTGzfjbN188Qi_iPDq8GqGTaqcKvlx/view?usp=sharing](https://drive.google.com/file/d/1ikCTGzfjbN188Qi_iPDq8GqGTaqcKvlx/view?usp=sharing)

Thanks for the update. I can decompress it by lz4 
```
# lz4 -d ~/Downloads/f843ffea950c47214d0335dfd620325ff4c46c453a488261354fb09d24b1236d.blk ~/Downloads/testfile
/Users/dereksu/Downl : decoded 2097152 bytes
```

The data is intact. It might be an issue of the package https://github.com/pierrec/lz4. Can you open a ticket there?

**Comment by DizzieNight** [comment]
Update: I rebuilt my cluster and reinstalled longhorn, the affected block was deleted but the one to replace it also has issues now. Weirdly enough I had a volume for plex that was broken but then overnight it restored, even though it had the same error that the affected block storage has.

There is 1 volume for sonarr that is broken now and is very important to me as the tuning I did on it took me ages (especially for anime). If I somehow am able to decompress the block file how do I then mount that on my local machine to grab the files? Sorry if it's a simple question

**Comment by derekbit** [comment]
> Update: I rebuilt my cluster and reinstalled longhorn, the affected block was deleted but the one to replace it also has issues now. Weirdly enough I had a volume for plex that was broken but then overnight it restored, even though it had the same error that the affected block storage has.
> 
> There is 1 volume for sonarr that is broken now and is very important to me as the tuning I did on it took me ages (especially for anime). If I somehow am able to decompress the block file how do I then mount that on my local machine to grab the files? Sorry if it's a simple question

I can create a cusomized engine image for helping skip the block file with incorrect checksum. WDYT?
BTW, what's the backupstore you are using?

**Comment by shikanime** [comment]
@derekbit I'm getting the exact same error even though I'm using the 1.6.3 engine. I traced back the source code a couple of days ago, just to confirm, the longhorn manager is acting as the api entry point and passing the backup restore request through gRPC to the engine? So the bug is really coming from the engine and not the manager? As the manager is still using the 1.7.3 Helm chart release.

I think it would be interesting, I'm trying to recover the same data as @DizzieNight along with other work related digital art assets. A small corrupted block on a media file can be found by ffmpeg and restored later, but as for the Sonarr database. I'm hoping it's just some random cache or config files 🙏 It's a bit of a pain to rebuild, but the database itself isn't really important.

I'm a regular OSS contributor to several projects I use, if I can be of any help.

**Comment by derekbit** [comment]
Hello @shikanime @DizzieNight 

Can you try the image `derekbit/longhorn-engine:v1.7.2-skip-decompression-error`? The engine image ignores the LZ4 errors and just logs them. Can you share the log after restoring the volume?

I'm not sure if the issues are caused by silent corruption such as memory and underlying disk or lz4 package that seems problematic in some environments. I'm wondering if disabling compression by default is a better way.

cc @shuo-wu @ChanYiLin @PhanLe1010 @innobead

**Comment by shikanime** [comment]
@derekbit Unfortunately, I'm currently running on the AArch64 platform.

**Comment by derekbit** [comment]
> @derekbit Unfortunately, I'm currently running on the AArch64 platform.

@shikanime Try this `derekbit/longhorn-engine:v1.7.2-skip-decompression-error-arm64`

**Comment by shikanime** [comment]
> > @derekbit Unfortunately, I'm currently running on the AArch64 platform.
> 
> @shikanime Try this `derekbit/longhorn-engine:v1.7.2-skip-decompression-error-arm64`

I inspected the image, it's still an amd64 image. I tried to build the image from your branch, but it seems to be broken.

**Comment by derekbit** [comment]
@shikanime Please try again. Thank you.

**Comment by shikanime** [comment]
@derekbit Thank you, everything seems to work with your image. I haven't found any corruption in my data, it could be a bug in the lz4 check, but I forgot to snapshot more logs when it happened.

**Comment by innobead** [comment]
> Hello @shikanime @DizzieNight
> 
> Can you try the image `derekbit/longhorn-engine:v1.7.2-skip-decompression-error`? The engine image ignores the LZ4 errors and just logs them. Can you share the log after restoring the volume?
> 
> I'm not sure if the issues are caused by silent corruption such as memory and underlying disk or lz4 package that seems problematic in some environments. I'm wondering if disabling compression by default is a better way.
> 
> cc @shuo-wu @ChanYiLin @PhanLe1010 @innobead

We can document this to guide how they can validate the case or even disable the compression if they encounter any compression/decompression issues.

**Comment by DizzieNight** [comment]
Hey @derekbit sorry it's taken me so long to reply back. But holy fucking shit you are a certified legend mate. I used your custom image and I have restored Sonarr. Seriously you have saved me hours of work. Thank you so much

**Comment by derekbit** [comment]
> Hey @derekbit sorry it's taken me so long to reply back. But holy fucking shit you are a certified legend mate. I used your custom image and I have restored Sonarr. Seriously you have saved me hours of work. Thank you so much

Thanks @shikanime @DizzieNight for your update and great idea.
Longhorn should introduce a setting for ignoring the checksum as @shikanime mentioned in https://github.com/longhorn/longhorn/issues/9765#issuecomment-2470617656.

cc @innobead @ChanYiLin

**Comment by innobead** [comment]
It should be this comment. https://github.com/longhorn/longhorn/issues/9765#issuecomment-2468301820

I agreed with the idea. Users can opt-out of the checksum check but still need to log it to make the integrity check visible.

**Comment by digrouz** [comment]
Hi, I'm experiencing something similar with 1.10.1. Was the setting implement?

**Comment by derekbit** [comment]
> Hi, I'm experiencing something similar with 1.10.1. Was the setting implement?

What error you are encountering?

**Comment by digrouz** [comment]
I'm trying to restore a backup from a volume and I get the following:

`replica pvc-4f66e334-b56e-4d4f-a90e-daa9e64fbcd1-r-937413b5 failed the restore: failed to decompress and verify block backupstore/volumes/1c/48/pvc-4f66e334-b56e-4d4f-a90e-daa9e64fbcd1/blocks/bf/64/bf6467101d27f90e21593fdccf0f396b0d9a13b9735be48bc2998825887f937b.blk with checksum bf6467101d27f90e21593fdccf0f396b0d9a13b9735be48bc2998825887f937b: decompression verification failed for block backupstore/volumes/1c/48/pvc-4f66e334-b56e-4d4f-a90e-daa9e64fbcd1/blocks/bf/64/bf6467101d27f90e21593fdccf0f396b0d9a13b9735be48bc2998825887f937b.blk: checksum verification failed for block`
