### ISSUE TITLE
[FEATURE] implement delta bitmap in go-spdk-helper

### ISSUE THREAD

**Issue by DamiaSan** [longhorn/longhorn#9766]
We have to implement in `go-spdk-helper` the new SPDK APIs to handle the delta bitmap of raid faulty base bdevs.
The original issue for the development of delta bitmap inside SPDK is https://github.com/longhorn/longhorn/issues/5573, which led to the PR https://github.com/longhorn/spdk/pull/33

**Comment by DamiaSan** [comment]
Also longhorn-spdk-engine must be changed because the function BdevRaidCreate has additional parameters

**Comment by DamiaSan** [comment]
Draft PR for go-spdk-helper: https://github.com/longhorn/go-spdk-helper/pull/163
Draft PR for longhorn-spdk-engine: https://github.com/longhorn/longhorn-spdk-engine/pull/238
When the [PR](https://github.com/longhorn/spdk/pull/37) for the new SPDK `longhorn-v24.09` branch will be merged, will convert the drafts into real PRs.

**Comment by innobead** [comment]
@DamiaSan Please include a description for this feature instead of leaving it blank.

**Comment by derekbit** [comment]
@DamiaSan Will the bitmap be addressed in v1.9.0 instead?

**Comment by derekbit** [comment]
Let's close this ticket. To reduce the burden of validation and issue management, the `spdk` and `go-spdk-helper` codes should be implemented and verified together in https://github.com/longhorn/longhorn/issues/5573.

**Comment by DamiaSan** [comment]
> @DamiaSan Will the bitmap be addressed in v1.9.0 instead?

It depends on what Shuo wants to do. I have developed the delta bitmap as discussed in the [LEP](https://github.com/longhorn/longhorn/pull/7031), but now he says that this development is unusable for him.

**Comment by innobead** [comment]
> > @DamiaSan Will the bitmap be addressed in v1.9.0 instead?
> 
> It depends on what Shuo wants to do. I have developed the delta bitmap as discussed in the [LEP](https://github.com/longhorn/longhorn/pull/7031), but now he says that this development is unusable for him.

This is another topic that needs to be discussed after you both wrap up the snapshot checksum and replica rebuilding w/ snapshot checksum. We need to ensure delta happens in 1.9 to complete the complete function of replica rebuilding. 

cc @shuo-wu
