### ISSUE TITLE
UI: volume expansion feature

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#977]
1. Add one more operation `Expand` for the volume. And the related batch operation is not needed:
- The API is `/v1/volumes/{volume name}?action=expand`
- The input is `Size`. The format is the same as the `Size` of `Create volume` API: it's a number in bytes or a string like `1Gi`. 
- The input `Size` should be larger than `volume.size`.
- The operation is available only when the volume is in `attached` or `detached` state.
- If `volume.kubernetesStatus.pvName != ""`, put a warning on the top of the input: `The capacity of related PV will not be updated`; else if `volume.kubernetesStatus.pvName != "" && volume.kubernetesStatus.pvcName != "" && volume.kubernetesStatus.lastPVCRefAt == ""`, put warning: `The capacity of related PV and PVC will not be updated`
- Put one more warning for the volume whose `disableFrontend` is `true`: `Longhorn will not expand the filesystem for the volume in maintenance mode. There is no available frontend for filesystem expansion`

2. If `volume.state == attached` and `volume.size != volume.controllers[0].size`, it means the volume is being expanded. In this case, show the follow line in the `Size` field: `The volume is in expansion progress from size "volume.controllers[0].size" to size "volume.size"`

**Comment by funkydorian** [comment]
Is there any progress on that? Has it been accepted for the next release?

**Comment by yasker** [comment]
@funkydorian Currently the backend code has been accepted and merged, we're working on the UI now. It will be available in the next release.

**Comment by smallteeths** [comment]
I changed the API in the UI to `/v1/volumes/{ volumeName }?action=expand` @shuo-wu

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test: #17
