### ISSUE TITLE
Rollback/Recover the volume if the expansion of all replicas failed

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#978]
If all replica expansion failed and the volume became `Faulted` state, we don't know the salvage works fine and there is no way to roll back the expansion.

**Comment by yasker** [comment]
Backend merged. Need instruction for UI.

**Comment by shuo-wu** [comment]
Prerequisites of the API:
1. `volume.controllers[0].isExpanding == false`
2. `volume.controllers[0].size != 0 && volume.controllers[0].size != volume.size`

Need to add tips when users try to call this API:
If the in-progress expansion you want to cancel is triggered by the **PVC size update**, this API won't help revert the PVC. Since the PVC size can not be shrink, users need to clean up then recreate the PVC and PV after the expansion canceling success:
1. Update the field `spec.persistentVolumeReclaimPolicy` to `Retain` for the related PV. Otherwise, the volume will be removed when the PVC/PV is gone.
2. Delete PVC and PV.
3. Recreate PVC and PV via yaml file or Longhorn UI

**Comment by yasker** [comment]
@smallteeths Can you help with the UI? Thanks.

**Comment by shuo-wu** [comment]
The way to prevent the expansion from success so that the expansion will keep retry:
1. Create a volume and attach it.
2. Enter the replica data directory and run the following command for each replica:
```
echo "while true; do if [ ! -e \"volume-snap-expand-4294967296.img.meta.tmp\" ]; then mkdir volume-snap-expand-<PLEASE INPUT THE EXPANSION SIZE>.img.meta.tmp; fi; sleep 1; done;" > test.sh && chmod +x test.sh && ./test.sh &
```
e.g., If I want to make sure the volume`v1` fails to expand to 4Gi, and the only replica of the volume is in `instance-manager-r-894f8e3b`:
```
~ kubectl -n longhorn-system exec -it instance-manager-r-894f8e3b bash
root@instance-manager-r-894f8e3b:/# cd /host/var/lib/longhorn/replicas/v1-d482cb0c/
root@instance-manager-r-894f8e3b:/host/var/lib/longhorn/replicas/v1-d482cb0c# echo "while true; do if [ ! -e \"volume-snap-expand-4294967296.img.meta.tmp\" ]; then mkdir volume-snap-expand-4294967296.img.meta.tmp; fi; sleep 1; done;" > test.sh && chmod +x test.sh && ./test.sh &
[1] 25183
```
3. Detach the volume
4. Expand the volume. The size should be the same as that is used in step2.

**Comment by meldafrawi** [comment]
Validation: **Partially Failed**

Steps to test:
1. Create a 1GB volume and attach it.
2. Format the volume, mount it to a directory
3. Write data to volume, and compute its checksum
4. Enter the replica data directory and run the following command for each replica:
` echo "while true; do if [ ! -e \"volume-snap-expand-2147483648.img.meta.tmp\" ]; then mkdir volume-snap-expand-2147483648.img.meta.tmp; fi; sleep 1; done;" > test.sh && chmod +x test.sh && ./test.sh &` 
5. Detach the volume
6. Expand the volume to be 2GB, (volume expansion should be suspending)
7.In Volume list page, click on `Cancel Expansion`
8. A warning message state should appear  (**PASS**)
```
This operation is used to cancel the expansion if the volume cannot complete the expansion and gets stuck there. Once the expansion is complete, it cannot be rolled back or canceled
```
9. Cancel volume expansion, expansion should work, volume should be attached and size should match the original volume size `1GB` (**PASS**)
10. Attach the volume again, and check data checksum, data checksum should match. (**PASS**)

**Failed tests**
- After volume create, in Volume list page and Volume Details page, should be **disabled** by default

![image](https://user-images.githubusercontent.com/18232258/79914865-420d1a00-8426-11ea-8b44-53de684bbb56.png)

- Volume Details page `Cancel Expansion` button don't work

![image](https://user-images.githubusercontent.com/18232258/79915107-a92ace80-8426-11ea-95d9-7ff22fee3165.png)


- Cancel Expansion button should exist on 
![image](https://user-images.githubusercontent.com/18232258/79915149-be076200-8426-11ea-9805-7513cc753def.png)

**Comment by yasker** [comment]
We don't need batch cancel button for now, it's not a commonly used the button. We can add it later if necessary.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
