### ISSUE TITLE
longhorn not working on rancher 2.3.3

### ISSUE THREAD

**Issue by edunix** [longhorn/longhorn#979]
Hi, Longhorn is not creating PV, i upgraded to version 0.7.0, but rancher Apps still states Upgrade available (0.7.0) (It still thinks 0.6.2 is current) . I created the namespace longhorn-system prior to upgrade, but everything is running in namespace longhorn-p-5s717. When i try to upgrade rancher states: Upgrade error: Unknown action: upgrade
When i do a test like in https://rancher.com/project-longhorn-now-available-kubernetes/ i get the warning  pod has unbound immediate PersistentVolumeClaims
Volume is pending, and there is no Persistent volume.
I can get it to work by manualy creating the PV in the longhorn interface (but only after i delete the volume in the volumes workload on rancher.

Any advice on how to solve this?
[longhorn-support-bundle_3be8e68f-cb2f-11e9-8893-ac162db3c6e8_2019-12-23T13-10-50Z.zip](https://github.com/longhorn/longhorn/files/3997778/longhorn-support-bundle_3be8e68f-cb2f-11e9-8893-ac162db3c6e8_2019-12-23T13-10-50Z.zip)

**Comment by shuo-wu** [comment]
Longhorn should be installed in namespace `longhorn-manager`. Otherwise, it won't work correctly. 
For the v0.7.0 upgrade, you can check [this doc](https://github.com/longhorn/longhorn/blob/v0.7.0/docs/upgrade-from-v0.6.2-to-v0.7.0.md#upgrade)
