### ISSUE TITLE
[BUG] Backup progress should not add block failed to upload to successful count

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9791]
## Describe the bug

The failure of block file upload is not captured by the `err` ([source code](https://github.com/longhorn/backupstore/blob/master/deltablock.go#L428-L430)), so the failed block will be added  to successful count. 

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
cc @ChanYiLin

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/backupstore/commit/2b482603a2c64912f02b1a79be8bbd3df0258521)

Following test [steps](https://github.com/longhorn/longhorn/issues/9791#issuecomment-2470875111), backup creation and restoration all worked well.
