### ISSUE TITLE
[DOC] Emphasize the backupstore cannot set retention policy

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9795]
## What's the document you plan to update? Why? Please describe

The lifecycle of backups' block and config files in the backupstore should be fully controlled by Longhorn. Any retention policy cannot be set to the backupstore.

**Comment by derekbit** [comment]
cc @ChanYiLin @mantissahz @innobead

**Comment by roger-ryao** [comment]
**Verified on master-head 20241127**

- website master-head https://github.com/longhorn/website/commit/e0a33384e57bcd36c0f18d14abd6fc976c9c64aa

**Result Passed**

- [x] require/doc : Checked documentation in https://github.com/longhorn/website/pull/1010
