### ISSUE TITLE
Can't scale WordPress catalog service with persistent volumes

### ISSUE THREAD

**Issue by andymelichar** [longhorn/longhorn#98]
- Set up new Rancher 2.0 Install running in container on jumpbox behind nginx reverse proxy
- Create an Ubuntu 16.04 cluster on Digital Ocean via UI
- Cluster builds successfully
- Launch Longhorn from Catalog, installs successfully
- Launch new WordPress library app
  - Select persistent storage for MariaDB and WordPress, select Longhorn as volume driver
- WordPress and Maria pods start up on a single node successfully, can reach it via ingress just fine, persistent volumes for the initial pods show up in Longhorn UI
- Scale up either the Maria or WordPress pod to more than 1 replica
- Original pods stays functional
- Scaled up/new pods don't create
- Describe failed pod and see that the volume didn't mount:
```
  Type     Reason                 Age                From               Message
  ----     ------                 ----               ----               -------
  Normal   Scheduled              54m                default-scheduler  Successfully assigned wordpress-wordpress-75c7bf fb99-hn4g6 to nyc3
  Normal   SuccessfulMountVolume  54m                kubelet, nyc3      MountVolume.SetUp succeeded for volume "default-token-pshjl"
  Warning  FailedMount            9m (x22 over 52m)  kubelet, nyc3      Unable to mount volumes for pod "wordpress-wordpress-75c7bffb99-hn4g6_wordpress(94340e79-7a5b-11e8-bb78-4ebac54d06b5)": timeout expired waiting for volumes to attach or mount for pod "wordpress"/"wordpress-wordpress-75c7bffb99-hn4g6". list of unmounted volumes=[wordpress-data]. list of unattached volumes=[wordpress-data default-token-pshjl]
  Warning  FailedMount            3m (x33 over 54m)  kubelet, nyc3      MountVolume.SetUp failed for volume "pvc-05f1359a-7a5b-11e8-bbba-aa10d9557ea4" : mount command failed, status: Failure, reason: create volume fail: fail to parse size error parsing size 'null': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```

**Comment by dnauck** [comment]
Reported the same here: https://github.com/rancher/charts/issues/10 and here https://github.com/kubernetes/charts/issues/1863
