### ISSUE TITLE
UI: Volume link doesn't work

### ISSUE THREAD

**Issue by wsaca** [longhorn/longhorn#980]
Hello, I found a problem with the volume link, when I click on this the volume list is not displayed.

![imagen](https://user-images.githubusercontent.com/3788624/71427755-e4400f80-2689-11ea-8ee6-035026f2d4d3.png)

**Comment by yasker** [comment]
@smallteeths Seems it wasn't updated behind the proxy.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

- Links fixed, work as expected.
