### ISSUE TITLE
[BUG] Why is it not possible to change the replica count in v2 longhorn volume?

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9805]
### Discussed in https://github.com/longhorn/longhorn/discussions/9804

<div type='discussions-op-text'>

<sup>Originally posted by **hookak** November 14, 2024</sup>
Hello,
I'd like to manually adjust the replica count for each v2 LHV, but it prevented by a [wehbook](https://github.com/longhorn/longhorn-manager/blob/70ac3bcf10ab37e05bbb6c5d23d4bbf89794d16f/webhook/resources/volume/validator.go#L254)
To change the replica count for v2 LHV is already possible during node eviction. 
The replica count of v2 LHV changes in the sequence n->n+1->n.
What is the reason for this restriction?</div>

**Comment by derekbit** [comment]
cc @hookak

**Comment by derekbit** [comment]
@hookak Can I assign the ticket to you? Then, you will be the contributor of the ticket and its associated PRs. Thank you.

**Comment by hookak** [comment]
Of course, it’s my pleasure. Thanks @derekbit

**Comment by chriscchien** [comment]
Verified **pass** on longhorn` v1.8.0-dev-20241117` (https://github.com/longhorn/longhorn-manager/commit/470b53c4959875af185590bbe8bd5d221fcfecc8)

V2 volume `numberOfReplicas` can be updated, replica rebuilding worked well after the replica count change.
