### ISSUE TITLE
[IMPROVEMENT] Decrease the reconnect delay of v2 volume nvme initiator

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9818]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

To accelerate volume IO resumption during v2 data engine live upgrades, we can decrease the reconnect delay of v2 volume NVMe initiators.

## Describe the solution you'd like

The current default value for `--reconnect-delay` is 10 seconds. We can reduce this value to 2 seconds. 
Advantages: Faster IO resumption post-upgrade
Disadvantages: Increased frequency of retries

**Comment by chriscchien** [comment]
Verified **pass** on longhorn v1.8.0-dev-20241117(longhorn-spdk-helper `c396ae`)

Following test [steps](https://github.com/longhorn/longhorn/issues/9818#issuecomment-2478218497) , can see log `starting error recovery in 2 seconds` in dmesg on replica deleted node.
```bash
[ 7551.011531] nvme nvme1: starting error recovery in 2 seconds
[ 7551.079207] nvme nvme1: Removing ctrl: NQN "nqn.2023-01.io.longhorn.spdk:pvc-d0045486-4477-4634-90f7-8536d81eafdd-e-0"
[ 7551.086536] nvme nvme1: Property Set error: 880, offset 0x14
[ 7551.107590] nvme nvme1: new ctrl: NQN "nqn.2014-08.org.nvmexpress.discovery", addr 10.42.1.56:20042
[ 7551.120796] nvme nvme1: Removing ctrl: NQN "nqn.2014-08.org.nvmexpress.discovery"
[ 7551.132607] EXT4-fs (dm-0): unmounting filesystem c47b4611-aa73-4a6b-8e74-22bc727f3890.
[ 7551.138016] umount: attempt to access beyond end of device
               nvme0n2: rw=133121, sector=2883584, nr_sectors = 8 limit=0
[ 7551.146085] Buffer I/O error on dev dm-0, logical block 360448, lost sync page write
[ 7551.151411] JBD2: I/O error when updating journal superblock for dm-0-8.
[ 7551.151413] Aborting journal on device dm-0-8.
[ 7551.151421] umount: attempt to access beyond end of device
               nvme0n2: rw=133121, sector=2883584, nr_sectors = 8 limit=0

```
