### ISSUE TITLE
Remount all kinds of filesystem

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#982]
Right now Longhorn supports `ext4` only for the remount feature and it's hardcoded in the implementation

**Comment by yasker** [comment]
@shuo-wu do we need to actually detect the filesystem? as long as it's mounted on the node, we should be ok to remount the fs.

**Comment by shuo-wu** [comment]
As long as we can find all mount records for the volume, detecting the filesystem is unnecessary.

**Comment by shuo-wu** [comment]
I still prefer to detect the filesystem before remount and we already have util function for filesystem detection. Otherwise, we cannot handle the following case:
1. Attach the volume
2. Create `ext4` filesystem for the volume and mount it.
3. Forget to umount the volume and detach it. --> It will retain an invalid mount record
4. Reattach the volume
5.  Re-create `xfs` filesystem for the volume and mount it. --> The volume has 2 mount records and the filesystem in the records are different.

**Comment by yasker** [comment]
It doesn't make much difference IMO. The behavior for the old mount point can be undefined in this case.

**Comment by shuo-wu** [comment]
This issue can be tested with #950.
Test steps:
1. Launch a Kubernetes cluster with CentOS distro. Launch Longhorn.
2. Create 2 volumes and attach them to a random node.
3. Format and mount the volumes with `xfs` and `btrfs` filesystems.
4. Delete the engine processes for the volumes in the instance manager pod. Then auto reattachment will be triggered.
5. Check the longhorn manager logs. The following logs should be found:
```
Longhorn doesn't support remount filesystem xfs for volume <the volume using xfs>

Volume <the volume using btrfs> has been remounted on node <node id>
```
6. Manually `umount` the `mount` the volume using `xfs`.
7. Check if both filesystem work fine

**Comment by meldafrawi** [comment]
Validation: **PASSED**

**Comment by meldafrawi** [comment]
Validation: **PASSED**
