### ISSUE TITLE
[BUG] Test case `Test Longhorn dynamic provisioned RWX volume recovery` failed:  Got /data/data.txt checksum = md5sum: can't open '/data/data.txt': Connection timed out

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9822]
## Describe the bug

Robot test case `Test Longhorn dynamic provisioned RWX volume recovery` failed with error: 

```
Checked e2e-test-deployment-0-db6496856-w7fkr file data.txt checksum:                 
Got /data/data.txt checksum = md5sum: can't open '/data/data.txt': Connection timed out
 Expected checksum = 6dae5b70561d3899fa6196e9b9db5f0f
```

The workload pod's IO got stuck after the share manager pod was deleted and recreated.

@chriscchien Need your help to confirm if it's a real issue or the test case needs to be refined.

## To Reproduce

Run robot test case: `-t "Test Longhorn dynamic provisioned RWX volume recovery"`

## Environment

 - Longhorn version: master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.31.1+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: sles 15-sp6
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
cc @james-munson

**Comment by derekbit** [comment]
@chriscchien please help confirm the issue first. Thank you.

**Comment by chriscchien** [comment]
Close this ticket as test case `Test Longhorn dynamic provisioned RWX volume recovery` passed on e2e pipeline after the fix merged, [test result](https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1972/)
