### ISSUE TITLE
[BUG]Unable to mount win10's qcow2 as a backing image

### ISSUE THREAD

**Issue by lcax200000** [longhorn/longhorn#9824]
I am running the Windows system on the KVM of Docker and deploying it on K3S (https://github.com/dockur/windows). The disk file uses the qcow2 format(Use backing files to map child disk files to the same parent disk file to implement multi-pod copy-on-write).  

Now I am having difficulties when trying to deploy the qcow2 file as a backing image on Longhorn. After uploading the qcow2 file in the dashboard, when creating a PV through volume, I must specify the fstype, and there are only two options, "ext4" or "xfs", and both have failed.

```
Found a PMBR partition table in /dev/longhorn/testp1
E1116 09:15:27.233168       1 mount_linux.go:230] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t xfs -o defaults /dev/longhorn/testp1 /export/testp1
Output: mount: /export/testp1: wrong fs type, bad option, bad superblock on /dev/longhorn/testp1, missing codepage or helper program, or other error.

time="2024-11-16T09:15:27Z" level=warning msg="Failed to mount volume" encrypted=false error="mount failed: exit status 32\nMounting command: mount\nMounting arguments: -t xfs -o defaults /dev/longhorn/testp1 /export/testp1\nOutput: mount: /export/testp1: wrong fs type, bad option, bad superblock on /dev/longhorn/testp1, missing codepage or helper program, or other error.\n" volume=testp1
time="2024-11-16T09:15:27Z" level=debug msg="Device /dev/mapper/testp1 is not an active LUKS device" func=crypto.DeviceEncryptionStatus file="crypto.go:89" error="failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/2379729/ns/mnt --ipc=/host/proc/2379729/ns/ipc cryptsetup status testp1], output /dev/mapper/testp1 is inactive.\n, stderr : exit status 4"
time="2024-11-16T09:15:27Z" level=fatal msg="Error running start command: mount failed: exit status 32\nMounting command: mount\nMounting arguments: -t xfs -o defaults /dev/longhorn/testp1 /export/testp1\nOutput: mount: /export/testp1: wrong fs type, bad option, bad superblock on /dev/longhorn/testp1, missing codepage or helper program, or other error.\n." func=cmd.ServerCmd.func1 file="server.go:100"
```

## To Reproduce
Use the qcow2 file generated by the kvm installed on Windows as the backing image

## Expected behavior

Use qcow2 file as backing image to implement multi-pod quick start system similar to backing file

 - Longhorn version: v1.6.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:k3s
 - Number of Longhorn volumes in the cluster:1

**Comment by derekbit** [comment]
@bk201 @Vicente-Cheng @WebberHuang1118 did you encounter the similar issue?

cc @ChanYiLin

**Comment by derekbit** [comment]
Wait
@lcax200000 is the backing image's original file system xfs?

**Comment by lcax200000** [comment]
> Wait @lcax200000 is the backing image's original file system xfs?

I'm not sure what the file system is. The qcow2 is installed with Windows, maybe NTFS?
The only options are "ext4" and "xfs", I don't know which one to choose
I checked the qemu-docker script, it should be created with a method similar to "qemu-img create -f "$DISK_FMT" "

**Comment by derekbit** [comment]
> > Wait @lcax200000 is the backing image's original file system xfs?
> 
> I'm uncertain about what the file system is. There's a Windows system installed in the qcow2 image, and perhaps it's NTFS? However, the only available options are "ext4" and "xfs", and I don't know which one I should choose. I've checked the qemu-docker script, and the qcow2 image should have been created in a way similar to "qemu-img create -f "$DISK_FMT"".


@lcax200000 You need to choose the correct filesystem.

> I've checked the qemu-docker script, and the qcow2 image should have been created in a way similar to "qemu-img create -f "$DISK_FMT"".


Can you provide the steps and the script that generated the backing image?

**Comment by lcax200000** [comment]
> Member

Deploy disk script:
https://github.com/qemus/qemu-docker/blob/master/src/disk.sh

I restarted the installation process and added the log "generate disk log:"
Here is the process output:

`windows  | ❯ Extracting downloaded ISO image...
windows  | ❯ Detecting version from ISO image...
windows  | ❯ Detected: Windows 10 Pro (Chinese)
windows  | ❯ Adding drivers to image...
windows  | ❯ Adding win10x64.xml for automatic installation...
windows  | ❯ Building Windows 10 image...
windows  | ❯ Creating a 32G growable disk image in qcow2 format...
windows  |  **generate disk log:   qemu-img create -f qcow2 -o preallocation=off -- /storage/data.qcow2 34359738368**
windows  | disk.sh: line 153: local: `**generate disk log:   qemu-img create -f qcow2 -o preallocation=off -- /storage/data.qcow2** 34359738368': not a valid identifier
windows  | disk.sh: line 154: **generate disk log:   qemu-img create -f qcow2 -o preallocation=off -- /storage/data.qcow2** 34359738368: No such file or directory
windows  | Formatting '/storage/data.qcow2', fmt=qcow2 cluster_size=65536 extended_l2=off preallocation=off compression_type=zlib size=34359738368 lazy_refcounts=off refcount_bits=16
windows  | ❯ Host: e82b99d1eeee  IP: 172.18.0.3  Gateway: 172.18.0.1  Interface: eth0  MAC: 02:D3:54:85:E6:DE
windows  | nameserver 127.0.0.11
windows  | 
windows  | Arguments:
windows  | 
windows  | -nodefaults
windows  | -cpu host,kvm=on,l3-cache=on,+hypervisor,migratable=no,-vmx,+invtsc,hv_passthrough
windows  | -smp 8,sockets=1,dies=1,cores=8,threads=1
windows  | -m 8G
windows  | -machine type=q35,smm=off,graphics=off,vmport=off,dump-guest-core=off,hpet=off,accel=kvm
windows  | -enable-kvm
windows  | -global kvm-pit.lost_tick_policy=discard
windows  | -display vnc=:0,websocket=5700
windows  | -vga virtio
windows  | -monitor telnet:localhost:7100,server,nowait,nodelay
windows  | -daemonize
windows  | -D /run/shm/qemu.log
windows  | -pidfile /run/shm/qemu.pid
windows  | -name windows,process=windows,debug-threads=on
windows  | -serial pty
windows  | -device qemu-xhci,id=xhci
windows  | -device usb-tablet
windows  | -netdev tap,id=hostnet0,ifname=qemu,vhost=on,vhostfd=40,script=no,downscript=no
windows  | -device virtio-net-pci,romfile=,netdev=hostnet0,mac=02:D3:54:85:E6:DE,id=net0
windows  | -drive file=/storage/win10.iso,id=cdrom9,format=raw,cache=unsafe,readonly=on,media=cdrom,if=none
windows  | -device ich9-ahci,id=ahci9,addr=0x5
windows  | -device ide-cd,drive=cdrom9,bus=ahci9.0,bootindex=9
windows  | -drive file=/storage/data.qcow2,id=data3,format=qcow2,cache=none,aio=native,discard=on,detect-zeroes=on,if=none
windows  | -device virtio-scsi-pci,id=data3b,bus=pcie.0,addr=0xa,iothread=io2
windows  | -device scsi-hd,drive=data3,bus=data3b.0,channel=0,scsi-id=0,lun=0,rotation_rate=1,bootindex=3
windows  | -object iothread,id=io2
windows  | -rtc base=localtime
windows  | -global ICH9-LPC.disable_s3=1
windows  | -global ICH9-LPC.disable_s4=1
windows  | -drive file=/storage/windows.rom,if=pflash,unit=0,format=raw,readonly=on
windows  | -drive file=/storage/windows.vars,if=pflash,unit=1,format=raw
windows  | -object rng-random,id=objrng0,filename=/dev/urandom
windows  | -device virtio-rng-pci,rng=objrng0,id=rng0,bus=pcie.0,addr=0x1c 
windows  | ❯ Booting Windows using QEMU v9.1.1...
windows  | 

BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
windows  | BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
windows  | BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
windows  | 

❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
`


After that, the data.qcow2 file will be generated. 
I regard it as the "master disk" and upload it to the dashboard as the backing image.

**Comment by derekbit** [comment]
@lcax200000 Thanks. As I mentioned, you need to check the correct filesystem and choose correct filesystem, or Longhorn cannot read the data correctly.

**Comment by derekbit** [comment]
> > filesystem
> 
> I think the filesystem is NTFS

Then, please set the filesystem to NTFS.
