### ISSUE TITLE
[BUG] UnknowOS Message in Longhorn Node Condition on RHEL

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9829]
### Discussed in https://github.com/longhorn/longhorn/discussions/9823

<div type='discussions-op-text'>

<sup>Originally posted by **jangseon-ryu** November 16, 2024</sup>
Hello Longhorn community,

I encountered an issue during testing for the adoption of Longhorn. The Longhorn Node Condition displayed a message stating UnknowOS.
```
  - lastProbeTime: ""
    lastTransitionTime: "2024-08-29T06:35:03Z"
    message: Unable to verify the required packages because the OS image 'red hat
      enterprise linux 8.8 (ootpa)' is unknown to the Longhorn system. Please ensure
      the required packages are installed.
    reason: UnknownOS
    status: "False"
    type: RequiredPackages
```

I’m wondering if this means RHEL is not officially supported by Longhorn. If it is supported, would it be acceptable for me to attempt modifying the code and contributing the changes back to the project?

Any guidance or clarification would be greatly appreciated.

Best regards,
Jason</div>

**Comment by derekbit** [comment]
@jangseon-ryu can I assign the ticket to you?

**Comment by jangseon-ryu** [comment]
Sure, please assign it to me. Thanks @derekbit

**Comment by derekbit** [comment]
@mantissahz Please help guide @jangseon-ryu to finish the pre-check list and move the ticket forward. Thanks.

**Comment by mantissahz** [comment]
Hi @jangseon-ryu,
Are you able to edit the [Pre Ready-For-Testing Checklist](https://github.com/longhorn/longhorn/issues/9829#issuecomment-2481756951) to provide the necessary information on the list?
If not, could you provide the reproducing steps (and any necessary information on the list) so that Longhorn QA can verify your fix?
Thanks.

**Comment by jangseon-ryu** [comment]
Hi @mantissahz 

Unfortunately, I don't have the necessary permissions to edit the [Pre Ready-For-Testing Checklist](https://github.com/longhorn/longhorn/issues/9829#issuecomment-2481756951) directly. 
However, here are the reproducing steps and the relevant information to help Longhorn QA verify the fix:

### Reproducing Steps
1. Deploy Longhorn on a RHEL environment (e.g., Red Hat Enterprise Linux 8.8).
2. Run the following command to check the node status:
   ```bash
   kubectl describe lhn {node}
   ```
3. In the output, navigate to Status > Conditions > RequiredPackages and observe Status: False with UnknownOS event.
4. After the fix, Status > Conditions > RequiredPackages should show Status: True.

### Have the backend code been merged
- The PR is at
https://github.com/longhorn/longhorn-manager/pull/3278

If there's anything else needed or if the checklist permissions can be updated, I'd be happy to assist further. Let me know how I can help.

Thanks.

**Comment by derekbit** [comment]
@mantissahz https://github.com/longhorn/cli/blob/46610824ba5c6610a5a713d00ec152e684a58fbb/pkg/utils/os.go#L26 seems need an update as well?

**Comment by yangchiu** [comment]
The `longhornctl` cli works on `rhel` as well:

```
$ ./longhornctl version
v1.7.2
$ ./longhornctl check preflight
INFO[2024-11-26T15:00:41+08:00] Initializing preflight checker               
INFO[2024-11-26T15:00:41+08:00] Cleaning up preflight checker                
INFO[2024-11-26T15:00:42+08:00] Running preflight checker                    
INFO[2024-11-26T15:00:48+08:00] Retrieved preflight checker result:
ip-10-0-2-10.ec2.internal:
  info:
  - Service iscsid is running
  - NFS4 is supported
  - Package nfs-utils is installed
  - Package iscsi-initiator-utils is installed
  - Package cryptsetup is installed
  - Module dm_crypt is loaded
ip-10-0-2-119.ec2.internal:
  info:
  - Service iscsid is running
  - NFS4 is supported
  - Package nfs-utils is installed
  - Package iscsi-initiator-utils is installed
  - Package cryptsetup is installed
  - Module dm_crypt is loaded
ip-10-0-2-124.ec2.internal:
  info:
  - Service iscsid is running
  - NFS4 is supported
  - Package nfs-utils is installed
  - Package iscsi-initiator-utils is installed
  - Package cryptsetup is installed
  - Module dm_crypt is loaded 
INFO[2024-11-26T15:00:48+08:00] Cleaning up preflight checker                
INFO[2024-11-26T15:00:49+08:00] Completed preflight checker
```

`longhorn-manager` gets os info from `kubeNode.Status.NodeInfo.OSImage`, but `longhornctl` gets it from `ID` in `/etc/os-release` or `/usr/lib/os-release`.
