### ISSUE TITLE
Unset `disableFrontend` when detaching a volume

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#983]
It will lead to a minor issue with volume expansion feature:
1. Attach a volume in maintenance node
2. Detach it
3. Expand the volume. --> The warning message `Longhorn will not expand the filesystem for the volume in maintenance mode. There is no available frontend for filesystem expansion` shouldn't be triggered

**Comment by meldafrawi** [comment]
Validation: **PASSED**
