### ISSUE TITLE
[IMPROVEMENT] Check NFS versions in /etc/nfsmount.conf instead

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9830]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

```
https://longhorn.io/docs/1.5.4/deploy/install/#installing-nfsv4-client
only checks that the kernel is able to use nfs4, NOT that it is actually in use!
The documentation on that page should be updated to check (at laest) /etc/nfsmount.conf instead of just checking the kernel.
```

## Describe the solution you'd like

- [ ] Update the official document
- [ ] Update the longhorn-manager node condition check  @mantissahz 
- [ ] Update the longhorn cli cc @mantissahz

**Comment by COLDTURNIP** [comment]
## PR
- longhorn/cli#129

**Comment by c3y1huang** [comment]
We also need to ensure this works on a Talos Linux cluster. cc @longhorn/qa

**Comment by COLDTURNIP** [comment]
PR for node controller: longhorn/longhorn-manager/#3335

**Comment by mantissahz** [comment]
>PR for node controller: https://github.com/longhorn/longhorn-manager/pull/3335

@COLDTURNIP could you update the PR and necessary information like reproduce steps on the `Pre Ready-For-Testing Checklist`?

**Comment by COLDTURNIP** [comment]
# Test Steps

- Step 1. a Longhorn ready cluster, ensure the following changes are applied:
  - latest char (longhorn/longhorn#9910)
  - the longhornctl is updated (longhorn/cli#129)
  - the longhorn-manager is updated (longhorn/longhorn-manager#3335)
  - Ensure `longhornctl check preflight` all green.
- Step 2. enter the shell of each `longhorn-manager` daemonset containers. The host's `/etc` should be mounted at container's `/host/etc`
- Step 3. backup host's `/host/etc/nfsmount.conf` if present
- Step 4. create/modify host's `/host/etc/nfsmount.conf`, change the `Defaultvers` to specific version (see below)
- Step 5. check the nodes using `longhornctl check preflight`. If the `Defaultvers` is not acceptable, a warning item will be attached: `NFS4 is supported, but default protocol version is not 4, 4.1, or 4.2. Please refer to the NFS mount configuration manual page for more information: man 5 nfsmount.conf`
- Step 6. wait for Longhorn node update, and check Longhorn node for given host (`kubectl describe -n longhorn-system lhn tested-host-name`). For `NFSClientInstalled` item In the `Status.Conditions` list, if the `Defaultvers` is not acceptable, it will indicate that NFS is misconfigured:
  - `Status: false`
  - `Message: NFS clients default protocol version is 4.3, which is not supported`
  - `Reason: NFSClientIsMisconfigured` 
- Step 7. change `Defaultvers` to another version, and back to Step 5.
- Step 8. After test, restore the `/host/etc/nfsmount.conf` which is backup at Step 3.


A minimal `/host/etc/nfsmount.conf` sample:

```
[ NFSMount_Global_Options ]
Defaultvers=4
```

The acceptable `Defaultvers`:

- `Defaultvers=4` -> acceptable
- `Defaultvers=4.0` -> acceptable
- `Defaultvers=4.1` -> acceptable
- `Defaultvers=4.2` -> acceptable
- `Defaultvers=4.3` -> NOT acceptable
- `Defaultvers=5` -> NOT acceptable
- `Defaultvers=3` -> NOT acceptable
- any other `Defaultvers` are NOT acceptable
- `/host/etc/nfsmount.conf` absent -> acceptable
- `/host/etc/nfsmount.conf` present without `Defaultvers` definded -> acceptable
- - `/host/etc/nfsmount.conf` present and `Defaultvers` is commented (e.g. `# Defaultvers=4.3`) -> acceptable

**Comment by derekbit** [comment]
@COLDTURNIP Please move it to `Ready For Testing` if all PRs are ready and merged. Thank you.

**Comment by roger-ryao** [comment]
**Verified on v1.8.0-dev-20241215 20241212**

- longhorn `v1.8.0-dev-20241215` https://github.com/longhorn/longhorn/commit/7cd5936abde0f177d9ae85492ec60aab0f115181
- cli `v1.8.0-dev-20241215` https://github.com/longhorn/cli/commit/0f3067177c4081e914a3e067611829a392f95d87

**The test steps**
https://github.com/longhorn/longhorn/issues/9830#issuecomment-2530704625

**Result Passed**

- [x] `lobghorn-cli` can successfully detect the host's `/etc/nfsmount.conf`.
- [x] `longhorn-manager` can verify the NFS versions in `/etc/nfsmount.conf`.
