### ISSUE TITLE
[BUG][Longhorn V1.7.1] current engine image version 0 doesn't support disable revision counter

### ISSUE THREAD

**Issue by 13675139195** [longhorn/longhorn#9840]
Events:
  Type     Reason                Age                   From                                                                                      Message
  ----     ------                ----                  ----                                                                                      -------
  Warning  ProvisioningFailed    5m48s                 driver.longhorn.io_csi-provisioner-857f49bc44-r95nn_9d01ad19-2bcb-4074-bef9-dfc60ba64d80  failed to provision volume with StorageClass "longhorn": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [detail=, message=failed to create volume: unable to create volume pvc-31be9827-c279-43a9-a33a-2ea624de9349: admission webhook "validator.longhorn.io" denied the request: can not create volume with current engine image that doesn't support disable revision counter: current engine image version 0 doesn't support disable revision counter, code=Internal Server Error] from [http://longhorn-backend:9500/v1/volumes]
  Warning  ProvisioningFailed    93s (x3 over 5m33s)   driver.longhorn.io_csi-provisioner-857f49bc44-r95nn_9d01ad19-2bcb-4074-bef9-dfc60ba64d80  failed to provision volume with StorageClass "longhorn": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=failed to create volume: unable to create volume pvc-31be9827-c279-43a9-a33a-2ea624de9349: admission webhook "validator.longhorn.io" denied the request: can not create volume with current engine image that doesn't support disable revision counter: current engine image version 0 doesn't support disable revision counter, code=Internal Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes]
  Normal   Provisioning          65s (x10 over 5m48s)  driver.longhorn.io_csi-provisioner-857f49bc44-r95nn_9d01ad19-2bcb-4074-bef9-dfc60ba64d80  External provisioner is provisioning volume for claim "mysql-operator/mysql-pvc"
  Warning  ProvisioningFailed    65s (x6 over 5m47s)   driver.longhorn.io_csi-provisioner-857f49bc44-r95nn_9d01ad19-2bcb-4074-bef9-dfc60ba64d80  failed to provision volume with StorageClass "longhorn": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Internal Server Error, detail=, message=failed to create volume: unable to create volume pvc-31be9827-c279-43a9-a33a-2ea624de9349: admission webhook "validator.longhorn.io" denied the request: can not create volume with current engine image that doesn't support disable revision counter: current engine image version 0 doesn't support disable revision counter] from [http://longhorn-backend:9500/v1/volumes]
  Normal   ExternalProvisioning  14s (x25 over 5m48s)  persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator

**Comment by derekbit** [comment]
Are you using v2 volume?

**Comment by abhi0698** [comment]
I've installed longhorn 1.7.2 recently using kubectl install method with default configs but i'm also getting the same issue while creating pvc.

Please help

**Comment by derekbit** [comment]
@13675139195 @abhi0698 Please provide a support bundle. Thanks.

**Comment by abhi0698** [comment]
Sharing a snip which i got while creating volume through longhorn ui and able to manage it by unchecking the option of "Disable Revision Counter".

But not able to resolve while creating through yaml
![image001.png](https://github.com/user-attachments/assets/f067b7e2-3853-4595-b970-7ffc01b1fe47)

**Comment by derekbit** [comment]
> > @13675139195 @abhi0698 Please provide a support bundle. Thanks.
> 
> where can i upload the logs, will you share your mail or upload link?

longhorn-support-bundle@suse.com

**Comment by abhi0698** [comment]
Hi @derekbit , I've managed to resolve that issue by creating a new Storage class by keeping "disableRevisionCounter" to false.

**Comment by abhi0698** [comment]
Hi @derekbit,

When trying to attach an PVC to an pod its getting attached and de-attached continuously in a loop.

Can you please provide any resolution by checking longhorn logs.
[longhorn-system.zip](https://github.com/user-attachments/files/17867911/longhorn-system.zip)

Also I've tried to run the environment_check.sh script and got an error that "kernel module iscsi_iscsi is not enabled on". I'm running a ubuntu server of 24 version.

**Comment by innobead** [comment]
@abhi0698 Is this a fresh install? Please refer to the document for the installation instructions.

https://longhorn.io/docs/1.7.2/deploy/install/

For generating a support bundle, please refer to https://longhorn.io/docs/1.7.2/troubleshoot/support-bundle/ instead of just collecting logs only.

**Comment by abhi0698** [comment]
> @abhi0698 Is this a fresh install? Please refer to the document for the installation instructions.
> 
> https://longhorn.io/docs/1.7.2/deploy/install/
> 
> For generating a support bundle, please refer to https://longhorn.io/docs/1.7.2/troubleshoot/support-bundle/ instead of just collecting logs only.

not able to upload entire bundle as github showing the file size limit as 25MB

**Comment by derekbit** [comment]
> > @abhi0698 Is this a fresh install? Please refer to the document for the installation instructions.
> > [longhorn.io/docs/1.7.2/deploy/install](https://longhorn.io/docs/1.7.2/deploy/install/)
> > For generating a support bundle, please refer to [longhorn.io/docs/1.7.2/troubleshoot/support-bundle](https://longhorn.io/docs/1.7.2/troubleshoot/support-bundle/) instead of just collecting logs only.
> 
> not able to upload entire bundle as github showing the file size limit as 25MB

[longhorn-support-bundle@suse.com](mailto:longhorn-support-bundle@suse.com)

**Comment by derekbit** [comment]
> Hi @derekbit,
> 
> When trying to attach an PVC to an pod its getting attached and de-attached continuously in a loop.
> 
> Can you please provide any resolution by checking longhorn logs. [longhorn-system.zip](https://github.com/user-attachments/files/17867911/longhorn-system.zip)
> 
> Also I've tried to run the environment_check.sh script and got an error that "kernel module iscsi_iscsi is not enabled on". I'm running a ubuntu server of 24 version.

According to the result of the environment_check.sh, please check the iSCSI installation in the official doc.
https://github.com/longhorn/longhorn/issues/9840

**Comment by abhi0698** [comment]
> > > @abhi0698 Is this a fresh install? Please refer to the document for the installation instructions.
> > > [longhorn.io/docs/1.7.2/deploy/install](https://longhorn.io/docs/1.7.2/deploy/install/)
> > > For generating a support bundle, please refer to [longhorn.io/docs/1.7.2/troubleshoot/support-bundle](https://longhorn.io/docs/1.7.2/troubleshoot/support-bundle/) instead of just collecting logs only.
> > 
> > 
> > not able to upload entire bundle as github showing the file size limit as 25MB
> 
> [longhorn-support-bundle@suse.com](mailto:longhorn-support-bundle@suse.com)

I've sent a we transfer link to the support mail please check once.

**Comment by derekbit** [comment]
> > > > @abhi0698 Is this a fresh install? Please refer to the document for the installation instructions.
> > > > [longhorn.io/docs/1.7.2/deploy/install](https://longhorn.io/docs/1.7.2/deploy/install/)
> > > > For generating a support bundle, please refer to [longhorn.io/docs/1.7.2/troubleshoot/support-bundle](https://longhorn.io/docs/1.7.2/troubleshoot/support-bundle/) instead of just collecting logs only.
> > > 
> > > 
> > > not able to upload entire bundle as github showing the file size limit as 25MB
> > 
> > 
> > [longhorn-support-bundle@suse.com](mailto:longhorn-support-bundle@suse.com)
> 
> I've sent a we transfer link to the support mail please check once.

Please provide of output of `lsmod | grep iscsi` on each node.

**Comment by abhi0698** [comment]
got the same output in both vms

icssi_tcp                    24576   0
libiscsi_tcp                32768  1  iscsi_tcp
libiscsi_tcp                77824   2  libiscsi_tcp,iscsi_tcp
scsi_transport_iscsi   172032  3   libiscsi_tcp,iscsi_tcp,libiscsi

**Comment by abhi0698** [comment]
Thanks a lot for debugging into the issue.
1. able to list the directories at given path in the vm ---> longhornio-longhorn-engine-v1.7.2
2. not able to list the directory longhorn in manager pods

**Comment by derekbit** [comment]
> not able to list the directory longhorn in manager pods

Got it
I found you replace
```
        - name: longhorn
          mountPath: /var/lib/longhorn/
          mountPropagation: Bidirectional
```
with
```
          - mountPath: /data/longhorn/
            mountPropagation: Bidirectional
            name: longhorn
```
in the `longhorn-manager` daemonset ([code](https://github.com/longhorn/longhorn/blob/v1.7.2/chart/templates/daemonset-sa.yaml#L72-L74)).

Please don't change the setting. Longhorn needs to read the binaries from `/var/lib/longhorn/` in the pod.

**Comment by derekbit** [comment]
`engine binary check failed` is not clear for troubleshooting and need to improve it.

**Comment by derekbit** [comment]
@abhi0698 @13675139195 
Feel free to reopen the issue if https://github.com/longhorn/longhorn/issues/9840#issuecomment-2493700207 cannot fix the problem.
