### ISSUE TITLE
[FEATURE] Inquiry: Storage Reserved Change for Block Type Disks in Engine v2

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9842]
### Discussed in https://github.com/longhorn/longhorn/discussions/9838

<div type='discussions-op-text'>

<sup>Originally posted by **jangseon-ryu** November 20, 2024</sup>
Hello Longhorn Community,

I have a question regarding the Storage Reserved setting for block type disks in Longhorn Engine v2. When I attempt to modify the Storage Reserved value for a block type disk, the change is not applied, and an unsupported operation event is triggered.
```
    enginev2-disk1:
      Allow Scheduling:    true
      Disk Driver:         auto
      Disk Type:           block
      Eviction Requested:  false
      Path:                /dev/disk/by-id/scsi-3600508b1001c95d27f513bddea3acc4b
      Storage Reserved:    0  <-- 
      Tags:
```
Log Message:
```
admission webhook "validator.longhorn.io" denied the request: disk enginev2-disk1 type block is not supported to reserve storage
```

Questions:

Does this mean that block type disks do not support changes to the Storage Reserved setting?
If this is the case, are there any plans to support this feature in the future?

Thank you for your assistance. Your guidance would be greatly appreciated.

Best regards,
Jason
</div>

**Comment by derekbit** [comment]
cc @jangseon-ryu

**Comment by jangseon-ryu** [comment]
For reference, I tested this in my environment by modifying the validator code.
I confirmed that modifying Storage Reserved worked correctly after commenting out the following lines in validator.go
https://github.com/longhorn/longhorn-manager/blob/master/webhook/resources/node/validator.go#L70
https://github.com/longhorn/longhorn-manager/blob/master/webhook/resources/node/validator.go#L180

( cc @derekbit )

**Comment by derekbit** [comment]
@jangseon-ryu Thank you. Would you like to submit a PR for the feature?

**Comment by jangseon-ryu** [comment]
@derekbit Of course, I will go ahead and submit a PR for the feature soon.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn v1.8.0-dev-20241117 (https://github.com/longhorn/longhorn-manager/commit/612db957e339ee8964d4b6a65afa1f45896c18c8)

Steps
1. Have 3 nodes cluster with 120Gi block disk added.
2. In node1, edit the block disk to `storageReserved: 53687091200`
3. From UI dashboard and kubectl, can see the reserved size of block device is correct.
![image](https://github.com/user-attachments/assets/8831f0ef-b400-467c-b036-e915175e32bd) 
![image](https://github.com/user-attachments/assets/fda83836-f327-4b60-926d-4380e99e3866)

**Comment by innobead** [comment]
Does v2 respect the reservation setting? I assume any volume creation won't happen when the available storage space is less than or equal to the reserved space?

https://github.com/longhorn/longhorn/discussions/9838#discussioncomment-11347677

**Comment by derekbit** [comment]
> Does v2 respect the reservation setting? I assume any volume creation won't happen when the available storage space is less than or equal to the reserved space?
> 
> [#9838 (comment)](https://github.com/longhorn/longhorn/discussions/9838#discussioncomment-11347677)

Yes after merging the PR https://github.com/longhorn/longhorn-manager/pull/3281.
