### ISSUE TITLE
[QUESTION] Longhorn backup: Failed to list backup volumes

### ISSUE THREAD

**Issue by fmunteanu** [longhorn/longhorn#9847]
## Describe the bug

I'm currently using Longhorn deployed in a K3s cluster. When I try to configure the NFS backup, I get the following error message:

> failed to list backup volumes in nfs://192.168.1.8:/mnt/default/opt/backup: error listing backup volume names: timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.7.2/longhorn [/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.7.2/longhorn backup ls --volume-only nfs://192.168.1.8:/mnt/default/opt/backup]

The NFS share is present on a TrueNAS appliance. I'm not sure how to troubleshoot the issue, I could not find anything relevant into Longhorn documentation.

![image](https://github.com/user-attachments/assets/c3cf1174-1e7f-46b6-a16c-80ebba05ec8e)

## Environment

 - Longhorn version:  1.7.2
 - Impacted volume (PV): N/A
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s v1.30.6+k3s1
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 5
 - Node config
   - OS type and version: Ubuntu 24.04.1 LTS
   - Kernel version: 6.8.0-1015-raspi
   - CPU per node: 4
   - Memory per node: 8GB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): 1GB
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 2

Current Helm chart custom settings:

```
$ helm get values longhorn -n kube-system
USER-SUPPLIED VALUES:
defaultSettings:
  allowCollectingLonghornUsageMetrics: false
  autoCleanupRecurringJobBackupSnapshot: true
  autoCleanupSnapshotWhenDeleteBackup: true
  autoCleanupSystemGeneratedSnapshot: true
  autoDeletePodWhenVolumeDetachedUnexpectedly: true
  backupTarget: nfs://192.168.1.8:/mnt/default/opt/backup
  defaultDataLocality: strict-local
  defaultReplicaCount: 2
  disableSchedulingOnCordonedNode: true
  logLevel: Warn
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  orphanAutoDeletion: true
  removeSnapshotsDuringFilesystemTrim: true
  replicaAutoBalance: least-effort
  taintToleration: node-role.kubernetes.io/control-plane:NoSchedule
longhornDriver:
  tolerations:
  - effect: NoExecute
    key: node.cilium.io/agent-not-ready
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
longhornManager:
  tolerations:
  - effect: NoExecute
    key: node.cilium.io/agent-not-ready
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
metrics:
  serviceMonitor:
    enabled: true
persistence:
  dataEngine: v1
  defaultClassReplicaCount: 2
  defaultDataLocality: disabled
  removeSnapshotsDuringFilesystemTrim: enabled
```

**Comment by fmunteanu** [comment]
This is related to Cilium masquerade, which also breaks the support bundle generator.

**Comment by FawenYo** [comment]
Hi @fmunteanu, I encountered the same issue recently.

However, I also tried to disable Cilum masquerade using Cilium config `enableIPv4Masquerade: false`, but the issue is still not fixed. May I know how you fix this?
