### ISSUE TITLE
[BUG] v2 volume faulted during degraded availability restore

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#9852]
## Describe the bug

Restore of a v2 volume with degraded availability has potential to become faulted when node scheduling is dynamically changing during the restore process.

```bash
> kl get nodes.longhorn.io
NAME               READY   ALLOWSCHEDULING   SCHEDULABLE   AGE
ip-172-31-38-37    True    false             True          52m
ip-172-31-40-208   True    true              True          52m
ip-172-31-46-43    True    true              True          52m
>
> kl get volume
NAME   DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE   AGE
vol2   v2            detached   faulted                  2147483648          112s
>
> kl get replica
NAME              DATA ENGINE   STATE     NODE               DISK                                   INSTANCEMANAGER   IMAGE   AGE
vol2-r-b90bfc66   v2            stopped   ip-172-31-40-208   dcf469d7-3e65-45f2-971d-73adb5f8cc4e                             2m38s
```

## To Reproduce

Precondition:
 1. Set `allow-volume-creation-with-degraded-availability` to true.
 2. Set `replica-soft-anti-affinity` to false.
 3. `replica-replenishment-wait-interval` to 0.
 4. Create a V2 volume backup of 800MB.

Steps:
1. Disable scheduling for node 2 and 3 on a 3 nodes cluster.
2. Restore a v2 volume with 3 replicas.
3. Enable scheduling for node 2 while restore in progress
4. Volum2 become faulted (repeat step 1~3 if volume not faulted)

## Expected behavior

The v2 volume restore success and data correct.

## Support bundle for troubleshooting

[supportbundle_a44f0d99-6cea-4a65-afe4-c847ba848059_2024-11-25T08-39-32Z.zip](https://github.com/user-attachments/files/17899897/supportbundle_a44f0d99-6cea-4a65-afe4-c847ba848059_2024-11-25T08-39-32Z.zip)

## Environment

 - Longhorn version: v1.8.0-dev
 - Impacted volume (PV): vol2
 - Installation method: kubectl
 - Kubernetes distro : v1.31.1+k3s1

## Additional context

From test case [test_allow_volume_creation_with_degraded_availability_restore](https://github.com/longhorn/longhorn-tests/blob/1e777ba5bb00c628ec46c002262fba23644ac823/manager/integration/tests/test_basic.py#L3683)

## Workaround and Mitigation

N/A

**Comment by chriscchien** [comment]
The same step for a v1 volume

1. only `ip-172-31-38-133` is schedulable
2. restore backup to vol2
3. enable schedule of `ip-172-31-39-34` when restore is inprogress
4. restore complete, vol2(v1) volume detached

[supportbundle_72c1e8db-ee53-4cd8-a9df-8fb9375d18b6_2024-11-26T03-20-14Z.zip](https://github.com/user-attachments/files/17912215/supportbundle_72c1e8db-ee53-4cd8-a9df-8fb9375d18b6_2024-11-26T03-20-14Z.zip)

```bash
> kl get nodes
NAME               STATUS   ROLES                  AGE    VERSION
ip-172-31-38-133   Ready    <none>                 108m   v1.30.0+k3s1
ip-172-31-39-34    Ready    control-plane,master   110m   v1.31.1+k3s1
ip-172-31-46-243   Ready    <none>                 108m   v1.30.0+k3s1
> 
>  kl get volume
NAME   DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE   AGE
vol2   v1            detached   unknown                  3221225472          2m32s
> 
>  kl get replica
NAME              DATA ENGINE   STATE     NODE               DISK                                   INSTANCEMANAGER   IMAGE   AGE
vol2-r-52c3206d   v1            stopped   ip-172-31-38-133   52052c70-eab2-4f1b-bb42-997dd3338d6d                             2m34s
vol2-r-cfba3372   v1            stopped   ip-172-31-39-34    44e5d1e7-d137-4a08-9089-6353902507a1                             2m34s
```

![image](https://github.com/user-attachments/assets/7bb0f01f-ac41-4ef8-baee-0f56840815e7)

**Comment by c3y1huang** [comment]
> The same step for a v1 volume
> 
> 1. only `ip-172-31-38-133` is schedulable
> 2. restore backup to vol2
> 3. enable schedule of `ip-172-31-39-34` when restore is inprogress
> 4. restore complete, vol2(v1) volume detached
> 
> [supportbundle_72c1e8db-ee53-4cd8-a9df-8fb9375d18b6_2024-11-26T03-20-14Z.zip](https://github.com/user-attachments/files/17912215/supportbundle_72c1e8db-ee53-4cd8-a9df-8fb9375d18b6_2024-11-26T03-20-14Z.zip)
> 
> ```shell
> > kl get nodes.longhorn.io
> NAME               READY   ALLOWSCHEDULING   SCHEDULABLE   AGE
> ip-172-31-38-133   True    true              True          16m
> ip-172-31-39-34    True    true              True          16m
> ip-172-31-46-243   True    false             True          16m
> 
> > 
> >  kl get volume
> NAME   DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE   AGE
> vol2   v1            detached   unknown                  3221225472          2m32s
> > 
> >  kl get replica
> NAME              DATA ENGINE   STATE     NODE               DISK                                   INSTANCEMANAGER   IMAGE   AGE
> vol2-r-52c3206d   v1            stopped   ip-172-31-38-133   52052c70-eab2-4f1b-bb42-997dd3338d6d                             2m34s
> vol2-r-cfba3372   v1            stopped   ip-172-31-39-34    44e5d1e7-d137-4a08-9089-6353902507a1                             2m34s
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/73337386/389780810-7bb0f01f-ac41-4ef8-baee-0f56840815e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMDI2MDAsIm5iZiI6MTczMzEwMjMwMCwicGF0aCI6Ii83MzMzNzM4Ni8zODk3ODA4MTAtN2JiMGYwMWYtYWM0MS00ZWY4LWJhZWUtMGY1Njg0MDgxNWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDAxMTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MmFjMjRkZTM3OTM0YjRjMzRhYmM0YTAwMzc3NjEyMTU5ZjY0Y2Y1ZTlkMDhmODRmZTllNzA0Y2ViMDU2MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q6h1RGe7pkSWuTLVmzvFuMHz7ReqgYOUKHSF_KinB1I)

@chriscchien 

> 4. restore complete, vol2(v1) volume detached

Could you provide more details on how you confirmed the restore was complete?

**Comment by chriscchien** [comment]
I am using UI to see the restored volume get detached successfully or not. After that, attach the restored volume to check data or perform [test_allow_volume_creation_with_degraded_availability_restore](https://github.com/longhorn/longhorn-tests/blob/1e777ba5bb00c628ec46c002262fba23644ac823/manager/integration/tests/test_basic.py#L3683)

**Comment by c3y1huang** [comment]
After talking to @chriscchien , we can use https://github.com/longhorn/longhorn-tests/pull/2170 for issue reproduction.

**Comment by derekbit** [comment]
> Note:
> 
> ```
> 2024-12-02T09:40:53.663324511Z time="2024-12-02T09:40:53Z" level=warning msg="Marking the instance as state ERROR since the starting instance manager instance-manager-66d65f7ac81bbec741a30f3251b7aa9c shouldn't contain the running instance longhorn-testvol-ff8rf3-r-d639cfbe" func="controller.(*InstanceHandler).syncStatusWithInstanceManager" file="instance_handler.go:103"
> 2024-12-02T09:40:53.663492403Z time="2024-12-02T09:40:53Z" level=warning msg="Marking the instance as state ERROR since the starting instance manager instance-manager-66d65f7ac81bbec741a30f3251b7aa9c shouldn't contain the running instance longhorn-testvol-xywst7-r-283881eb" func="controller.(*InstanceHandler).syncStatusWithInstanceManager" file="instance_handler.go:103"
> ```

Seems a race condition?

**Comment by c3y1huang** [comment]
> Seems a race condition?

Seems that a random instance manager pod gets restarted when scheduling is enabled on a node. Any idea?

**Comment by c3y1huang** [comment]
Found NPE before the restart.
```
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c] panic: runtime error: invalid memory address or nil pointer derefe
rence
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c] [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb3
12ab]
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c] 
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c] goroutine 12896 [running]:
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c] github.com/longhorn/longhorn-spdk-engine/pkg/spdk.(*Engine).Replic
aAdd.func2()
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c]     /go/src/github.com/longhorn/longhorn-instance-manager/vendor/g
ithub.com/longhorn/longhorn-spdk-engine/pkg/spdk/engine.go:999 +0x1eb
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c] github.com/longhorn/longhorn-spdk-engine/pkg/spdk.(*Engine).Replic
aAdd(0xc001a21180, 0xc0007340a8, {0xc000d70480, 0x22}, {0xc000c1a9d0, 0x10})
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c]     /go/src/github.com/longhorn/longhorn-instance-manager/vendor/g
ithub.com/longhorn/longhorn-spdk-engine/pkg/spdk/engine.go:1095 +0xeea
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c] github.com/longhorn/longhorn-spdk-engine/pkg/spdk.(*Server).Engine
ReplicaAdd(0xc0004a45b0, {0x1dd06a0?, 0xc000513900?}, 0xc000a69920)
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c]     /go/src/github.com/longhorn/longhorn-instance-manager/vendor/g
ithub.com/longhorn/longhorn-spdk-engine/pkg/spdk/server.go:1086 +0x259
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c] github.com/longhorn/types/pkg/generated/spdkrpc._SPDKService_Engin
eReplicaAdd_Handler({0x1dd06a0, 0xc0004a45b0}, {0x21fe2e0, 0xc0007b7b00}, 0xc0017f8800, 0x0)
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c]     /go/src/github.com/longhorn/longhorn-instance-manager/vendor/g
ithub.com/longhorn/types/pkg/generated/spdkrpc/spdk_grpc.pb.go:1633 +0x1a6
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c] google.golang.org/grpc.(*Server).processUnaryRPC(0xc000702a00, {0x
21fe2e0, 0xc0007b7a70}, {0x22061c0, 0xc0007949c0}, 0xc0006c6c60, 0xc000705860, 0x3137158, 0x0)
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c]     /go/src/github.com/longhorn/longhorn-instance-manager/vendor/g
oogle.golang.org/grpc/server.go:1394 +0xe2b
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c] google.golang.org/grpc.(*Server).handleStream(0xc000702a00, {0x220
61c0, 0xc0007949c0}, 0xc0006c6c60)
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c]     /go/src/github.com/longhorn/longhorn-instance-manager/vendor/g
oogle.golang.org/grpc/server.go:1805 +0xe8b
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c] google.golang.org/grpc.(*Server).serveStreams.func2.1()
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c]     /go/src/github.com/longhorn/longhorn-instance-manager/vendor/g
oogle.golang.org/grpc/server.go:1029 +0x7f
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c] created by google.golang.org/grpc.(*Server).serveStreams.func2 in 
goroutine 12894
[instance-manager-66d65f7ac81bbec741a30f3251b7aa9c]     /go/src/github.com/longhorn/longhorn-instance-manager/vendor/g
oogle.golang.org/grpc/server.go:1040 +0x125
```

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-instance-manager/commit/c36f64c66b4fefe7f5e7943f27273af51a62c6db)

- manually perforn test [steps](https://github.com/longhorn/longhorn/issues/9852#issue-2689788761), v2 volume restored success.
- test case `test_allow_volume_creation_with_degraded_availability_restore` passed on v2 scenario.
