### ISSUE TITLE
[BUG] Test case test_node_eviction_multiple_volume failed to reschedule replicas after volume detached

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9857]
## Describe the bug

Test case test_node_eviction_multiple_volume failed to reschedule replicas after volume detached:

https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/1104/testReport/junit/tests/test_node/test_node_eviction_multiple_volume/

## To Reproduce

1. Disable scheduling on node 1.
2. Create pv, pvc, pod with volume 1 of 2 replicas.
3. Set 'Eviction Requested' to 'true' and disable scheduling on node 2.
4. Set 'Eviction Requested' to 'false' and enable scheduling on node 1.
5. Check volume 'healthy' and wait for replicas running on node 1 and 3.
7. delete pods to detach volume 1.
8. Set 'Eviction Requested' to 'false' and enable scheduling on node 2.
9. Set 'Eviction Requested' to 'true' and disable scheduling on node 1.
10. Wait for replicas running on node 2 and 3.

In `v1.7.2`, the detached volume will automatically re-attach in step 9 to reschedule replicas from node 1 to node 2.

But in `master-head`, the re-attachment and rescheduling never happen.

## Environment

 - Longhorn version: master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.31.1+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: sles 15-sp6
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
@mantissahz Please help investigate the issue. Thank you.

**Comment by yangchiu** [comment]
Could be related to https://github.com/longhorn/longhorn/issues/9781

**Comment by c3y1huang** [comment]
> Could this be related to #9781?

Yes, it seems to be a regression failure caused by it.

**Comment by innobead** [comment]
> > Could this be related to #9781?
> 
> Yes, it seems to be a regression failure caused by it. I will handle this at #9781.
> 
> cc @derekbit @mantissahz

so this is not a regression in the existing versions but caused by the recent fix for #9781 ?

**Comment by c3y1huang** [comment]
> so this is not a regression in the existing versions but caused by the recent fix for #9781 ?

Yes, this is caused by a recently merged PR. https://github.com/longhorn/longhorn-manager/pull/3270

**Comment by derekbit** [comment]
Merged. We can update the status. Thank you.

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-manager 6da14ea). Test case `test_node_eviction_multiple_volume` passed: https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/1121/testReport/tests/test_node/test_node_eviction_multiple_volume/
