### ISSUE TITLE
docs - migrating volumes (with only 1 replica configured)

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#986]
If I want to migrate volumes to another disk path, do I just disable the path?

Or do I need to do more work?

E.g.:
1. increase replica to 2
2. wait for replica to replicate on new disk
3. decrease replica to 1
4. delete replica from old disk

![image](https://user-images.githubusercontent.com/28725423/71537346-b278b400-28e8-11ea-895e-9b66d1b585d3.png)

![image](https://user-images.githubusercontent.com/28725423/71537362-e2c05280-28e8-11ea-8730-178ab0d3a84c.png)

**Comment by yasker** [comment]
Yeah, that would work.

**Comment by ainiml** [comment]
> Yeah, that would work.

Can't migrate the replica without running those steps. Just disabling the path doesn't work. Disabling the path just marks it unschedulable, but the replica remains on the disabled path

![image](https://user-images.githubusercontent.com/28725423/71539751-1615d800-290f-11ea-9a9d-fe5cb62d0c9a.png)

**Comment by yasker** [comment]
I was referring your steps. The steps would work.
