### ISSUE TITLE
[BUG] v2 volume failed attach/delete if a replica can not scheduled due to no enough disk space

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#9861]
## Describe the bug

In a 3 nodes cluster, v2 volume failed attach/delete if a replica can not scheduled due to not enough disk space

```
time="2024-11-26T09:23:43Z" level=error msg="There's no available disk for replica test-vol-r-788bc3bb, size 107374182400" func="scheduler.(*ReplicaScheduler).ScheduleReplica" file="replica_scheduler.go:74"
time="2024-11-26T09:23:43Z" level=warning msg="Failed to schedule replica" func="controller.(*VolumeController).reconcileVolumeCondition" file="volume_controller.go:1731" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=ip-172-31-39-34 owner=ip-172-31-39-34 replica=test-vol-r-788bc3bb state=attaching volume=test-vol
```

delete the v2 volume, volume stuck at deleteing, a v1 volume can be attached at the same scenario
![image](https://github.com/user-attachments/assets/43147e1e-a808-4fb0-8179-12cccc037e36)

## To Reproduce

1. Have 3 nodes cluster with 120Gi block disk added.
2. In node1, edit the block disk to `storageReserved: 32212254720` (30 Gi), available size should near 90 Gi
3. Create a three replicas v2 volume with size=100Gi
4. Attach the volume, volume stuck at attaching state.
5. Try delete the volume, volume stuck at deleting state.

## Expected behavior

Volume should attach degraded like v1 volume.

## Support bundle for troubleshooting

[supportbundle_4bb0cd41-0f9b-4c8a-9a3d-88aab298b88c_2024-11-26T09-20-55Z.zip](https://github.com/user-attachments/files/17917039/supportbundle_4bb0cd41-0f9b-4c8a-9a3d-88aab298b88c_2024-11-26T09-20-55Z.zip)

## Environment

 - Longhorn version:  v1.8.0 dev
 - Impacted volume (PV): test-vol
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl 
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.31.1+k3s1
   
## Additional context

https://github.com/longhorn/longhorn/issues/9842

## Workaround and Mitigation

N/A

**Comment by derekbit** [comment]
@PhanLe1010 Can you help this?

**Comment by chriscchien** [comment]
Colse this tickt as it can not be reproduced now.
