### ISSUE TITLE
[CI] Run security scanning for actively supported branches

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#9869]
## What's the CI task to develop? Please describe

We currently only perform security scans for the master branch. We need to ensure that all actively supported branches are monitored.

https://ci.longhorn.io/job/private/job/image-security-scan/1646/parameters/

## Additional context

cc @derekbit @c3y1huang @longhorn/qa

**Comment by innobead** [comment]
We can run security scans using GitHub Actions instead of Jenkins in the future to facilitate easy integration with future actions and simplify checking build results.

**Comment by derekbit** [comment]
@innobead Should we move the ticket to QA Sprint board?

**Comment by innobead** [comment]
Yeah sounds good.
