### ISSUE TITLE
[BUG] Default disk registration sets Storage Reserved to 0 instead of using storage-reserved-percentage-for-default-disk value (Engine v2 block type only)

### ISSUE THREAD

**Issue by jangseon-ryu** [longhorn/longhorn#9871]
## Describe the bug
Following the [Configuring Defaults for Nodes and Disks](https://longhorn.io/docs/1.7.2/nodes-and-volumes/nodes/default-disk-and-node-config/), the automatic disk registration functionality works as expected when adding a new node to a Longhorn cluster.
However, when using Engine v2 block type, the Storage Reserved value for the automatically registered disk is incorrectly set to 0, rather than being calculated based on the storage-reserved-percentage-for-default-disk setting.
```
    enginev2-disk1:
      Allow Scheduling:    true
      Disk Driver:         auto
      Disk Type:           block
      Eviction Requested:  false
      Path:                /dev/disk/by-id/scsi-3600508b1001c95d27f513bddea3acc4b
      Storage Reserved:    0  <-- always 0
      Tags:
```

## To Reproduce
1. Configure automatic disk registration as described in the [Default Disk and Node Config Guide](https://longhorn.io/docs/1.7.2/nodes-and-volumes/nodes/default-disk-and-node-config/).
2. Add a new node to the Longhorn cluster.
3. Verify that the default disk is automatically registered.
4. Check the Storage Reserved value for the newly registered disk.

## Expected behavior
The Storage Reserved value should be automatically calculated based on the storage-reserved-percentage-for-default-disk setting (default: 30%). For example, if the disk has a total capacity of 1TB, the reserved storage should be set to 300GB (30%).
```
storage-reserved-percentage-for-default-disk                      30
```

## Environment

 - Longhorn version: v1.7.2
 - Impacted volume (PV):
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:v1.23.15
   - Number of control plane nodes in the cluster:1
   - Number of worker nodes in the cluster:12
 - Node config
   - OS type and version:RHEL 8.8
   - Kernel version:5.15.27
   - CPU per node:48
   - Memory per node:128G
   - Disk type (e.g. SSD/NVMe/HDD):SSD
   - Network bandwidth between the nodes (Gbps):10Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):Baremetal
 - Number of Longhorn volumes in the cluster:2 

## Workaround and Mitigation
Manually updating the Storage Reserved value via the UI.
For the workaround to function correctly, ensure that [longhorn/longhorn#9842](https://github.com/longhorn/longhorn/issues/9842) is applied beforehand. This ensures that necessary webhook validations are properly handled, avoiding errors during manual updates.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-manager/commit/ea698235173162b388c11c95c689bdd0fc886aa8)

1. Create a 3 nodes cluster
2. Taint node1 with NoSchedule
3. On tainted node, perform below command (chagne the node name accordingly)
```
kubectl label nodes ip-172-31-37-151 node.longhorn.io/create-default-disk=config
kubectl annotate nodes ip-172-31-37-151 node.longhorn.io/default-disks-config='[{"name":"fast-ssd-disk","path":"/dev/xvdb","allowScheduling":true,"storageReserved":1048576, "diskType": "block"}]'
```
4. Deploy longhorn, enable v2 data engine.
5. Set `create-default-disk-labeled-nodes` to true
6. Untaint the node in step 2
7. New `nodes.longhorn.io` will added, and the disk added accorgindly. storageReserved value is corrent on block disk.
![image](https://github.com/user-attachments/assets/b5f24769-0245-4417-99e2-80ef9ad529a5)

**Comment by innobead** [comment]
@derekbit do we need storage reservation for v2? I thought 0 was originally intended. It should be just for v1, as Longhorn disks for v1 are file system based instead of block device.

**Comment by derekbit** [comment]
> @derekbit do we need storage reservation for v2? I thought 0 was originally intended. It should be just for v1, as Longhorn disks for v1 are file system based instead of block device.

Originally, we intentionally set it to 0, but [there are some use cases for non-zero storage reservation](https://github.com/longhorn/longhorn/discussions/9838#discussioncomment-11323353).

**Comment by innobead** [comment]
I see. However, we might need to explain how it works for v2 to clarify the right expectations from users. For example, Whats the expected behavior when disk space usage for V2 is reach the storage availability (-storage reservation)? Is it the same as V1? Or does Longhorn still allow replica operations (related to size) work as usual until using up the whole disk space?

**Comment by derekbit** [comment]
> Is it the same as V1? 

It is same as v1, because v1 and v2 are using the same replica scheduling logic.
