### ISSUE TITLE
[BUG] v2 volume may enter ERROR state after deleting an instance manager containing a replica

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9874]
## Describe the bug

After deleting an instance manager containing a replica of a v2 volume on a non-attached node, the v2 volume may enter ERROR state.

![image](https://github.com/user-attachments/assets/e657f764-f035-49a4-8460-780b3a923210)

The `ctrlr_loss_timeout_sec` setting applies to the base bdev's NVMe controller and defines the timeout duration (30 seconds) for SPDK to attempt reconnecting to the controller after losing connection. 

When an instance manager containing a replica is deleted, SPDK starts to reconnect to the base bdev's controller. If the connection cannot be reestablished within the `ctrlr_loss_timeout_sec` period, the base bdev is removed from the RAID bdev. Since the `ctrl-loss-tmo` for the NVMe-oF initiator connecting to the RAID target is also set to 30 seconds, there is a risk of a race condition: the initiator may prematurely conclude that the target has failed. 

## To Reproduce

1. Create a 3-replica v2 volume
2. Delete a replica of a v2 volume on a non-attached node
3. Wait for the finish of the replica rebuilding
4. Repeat 2 and 3. The v2 volume may enter an ERROR state

## Expected behavior

The v2 volume shouldn't enter ERROR state

## Environment

 - Longhorn version: 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by roger-ryao** [comment]
**Verified on master-head 20241206**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/6cc47ec5e942f33b10f644a5eaf0970b650e27a7
- longhorn-instance-manager `master-head` https://github.com/longhorn/longhorn-instance-manager/commit/88b6f24e17a8f0618c597b2337b1a498ca0de90f

**The test steps**
https://github.com/longhorn/longhorn/issues/9874#issuecomment-2506007100

1. Create a 3-replica v2 volume and attach it to node-1.
2. Delete a replica of the v2 volume located on a non-attached node (`node-2`).
3. Wait for the replica rebuild to complete.
4. Verify that the v2 volume's `robustness` returns to `Healthy`.
5. Repeat steps 2 and 4, but delete a replica on another non-attached node (`node-3`).
6. Continue repeating steps 2–5 for 50 iterations using `delete_replica.sh`.

<details>
<summary>delete_replica.sh</summary>

```bash
#!/bin/bash

NAMESPACE="longhorn-system"
TARGET_NODES=("node-2" "node-3")
DELETE_COUNT=50

get_replicas() {
    kubectl -n $NAMESPACE get replica -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.spec.nodeID}{"\n"}{end}'
}

check_replica_status() {
    local node=$1
    kubectl -n $NAMESPACE get replica | grep "$node" | awk '{print $1 "\t" $3}'
}

get_volume_name() {
    local replica_name=$1
    kubectl -n $NAMESPACE get replica "$replica_name" -o jsonpath='{.spec.volumeName}'
}

check_volume_health() {
    local volume_name=$1
    kubectl -n $NAMESPACE get volume "$volume_name" -o jsonpath='{.status.robustness}'
}

for ((i=1; i<=DELETE_COUNT; i++)); do
  for NODE in "${TARGET_NODES[@]}"; do
    echo "Processing node: $NODE (Iteration: $i)"
    
    REPLICA=$(get_replicas | grep "$NODE" | cut -f1)
    
    if [[ -n "$REPLICA" ]]; then
      VOLUME_NAME=$(get_volume_name "$REPLICA")
      echo "Found replica $REPLICA for volume: $VOLUME_NAME"
      
      echo "Deleting replica: $REPLICA on node: $NODE"
      kubectl -n $NAMESPACE delete replica $REPLICA

      echo "Waiting for new replica to be created and running..."
      while true; do
        echo "Current replicas status:"
        kubectl -n $NAMESPACE get replica

        REPLICA_STATUS=$(check_replica_status "$NODE")
        if [[ -n "$REPLICA_STATUS" ]]; then
          NAME=$(echo "$REPLICA_STATUS" | cut -f1)
          STATUS=$(echo "$REPLICA_STATUS" | cut -f2)
          
          if [[ "$STATUS" == "running" ]]; then
            echo "New replica $NAME on node $NODE is now running."
            break
          else
            echo "New replica $NAME on node $NODE is in $STATUS state."
          fi
        else
          echo "No replica found on node $NODE yet."
        fi
        
        sleep 5
      done

      echo "Checking volume health status..."
      while true; do
        HEALTH_STATUS=$(check_volume_health "$VOLUME_NAME")
        echo "Current volume $VOLUME_NAME health status: $HEALTH_STATUS"
        
        if [[ "$HEALTH_STATUS" == "healthy" ]]; then
          echo "Volume is healthy, proceeding to next replica..."
          break
        else
          echo "Volume is not healthy yet, waiting..."
          sleep 5
        fi
      done

    else
      echo "No replica found on node: $NODE"
    fi
    sleep 5
  done
done
```
</details>



**Result Passed**

After executing the script, the v2 volume won't enter an `ERROR` state
