### ISSUE TITLE
Unable to delete replica from detached volume

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#988]
I'm suspecting the replica is corrupted when the backend crashed when replica was increased from `1` to `2`, and was rebuilding the new replica

Steps:
1. Add new block device (s3backer)
2. Mount block device
3. Add new disk to node
4. Increase replica count from `1` to `2`
5. Interrupt replica rebuild process (reboot, disconnect disk)

![image](https://user-images.githubusercontent.com/28725423/71540037-2d56c480-2913-11ea-9f98-d65641966829.png)

**Comment by ainiml** [comment]
I had to manually remove the volume from the backend

**Comment by yasker** [comment]
It looks like a UI bug

**Comment by ainiml** [comment]
> It looks like a UI bug.
> 
> Can you describe the reproduce steps?

updated with the possible steps

**Comment by meldafrawi** [comment]
Validation: **PASSED**
