### ISSUE TITLE
[UI][FEATURE] Support V2 Backing Image in UI

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#9880]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

1. When creating backing image, users should be able to select if the `"Data Engine"` is `v1` or `v2` backing image 
    - refer to the `"Data Engine"` in the volume creation 
2. In the backing image UI page, we should have a new field `"Data Engine"`
3. In the backing Image UI page, if the backing image is v2, we should not allow users to download it (currently not support)

![Screenshot from 2024-11-29 15-40-51](https://github.com/user-attachments/assets/b629d2d1-b06a-423e-9278-ee266c8cd6db)
![Screenshot from 2024-11-29 15-40-39](https://github.com/user-attachments/assets/c4856af8-204c-476c-a1c4-5f9f196ae3ed)

Note:
The `"DataEngine"` should be supported in the API after this PR merged: https://github.com/longhorn/longhorn-manager/pull/3295 
```
e.g.
CREATE
HTTP/1.1 POST /v1/backingimages
Host: localhost:8080
Accept: application/json
Content-Type: application/json
Content-Length: 49

{
"expectedChecksum": "",
"name": "",
"sourceType": "",
"dataEngine": "v1",
}


GET
{
    "data": [
        {
          ...
            "dataEngine": "v2",
            "deletionTimestamp": "",
            "diskFileStatusMap": {
                "c13bbeb6-815a-439a-bb80-2fa4820b62c8": {
                    "dataEngine": "v2",
                    "lastStateTransitionTime": "2024-11-29T07:41:17Z",
                    "message": "",
                    "progress": 100,
                    "state": "ready"
                }
            },
          ...
            "minNumberOfCopies": 1,
            "name": "parrot-qcow2",
            "nodeSelector": null,
            "parameters": {
                "url": "https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.qcow2"
            },
...
            "size": 33554432,
            "sourceType": "download",
            "type": "backingImage",
            "uuid": "43a479a3"
        }
    ],
    "links": {
        "self": "http://localhost:8080/v1/backingimages"
    },
    "resourceType": "backingImage",
    "type": "collection"
}
```

**Comment by ChanYiLin** [comment]
Hi @houhoucoop 
Sorry for late update
But for this ticket, may I add one new spec ?
- When `Restore BackupBackingImage`, can you help to add a new option `DataEngine` which has `v1`, `v2` option? Just like creating backing image.

![Uploading Screenshot from 2024-12-23 19-24-04.png…]()


The API request payload Example
```
{
"dataEngine": "v1", // or "v2"
"secret": "",
"secretNamespace": "",
}
```

You can use this image for development: `jackfantasy/longhorn-manager:update_restore_api`

Thanks!

**Comment by yangchiu** [comment]
Move back to `Implement` since we need https://github.com/longhorn/longhorn/issues/9880#issuecomment-2559501498.

**Comment by chriscchien** [comment]
Verified pass on longhorn master(https://github.com/longhorn/longhorn-ui/commit/f903b6a4b724a7e05cce1509d5465e48d98c6967), v1.8.x(https://github.com/longhorn/longhorn-ui/commit/47c97e0dc42f0431909e6992ccb42884332bd648) with test [steps](https://github.com/longhorn/longhorn/issues/10047#issuecomment-2560742353)

- [x] User are able to select Data Engine when create a backing image
- [x] Show Data Engine info on the table
- [x] Disable Download options for v2 backing image
- [x] Disable bulk action Download if user select one of v2 backing image
- [x] Selective data engine option when restore backing image
