### ISSUE TITLE
[BUG] Raw format backing image unable to transfer to other nodes to maintain minumum number of copies in Talos v1.8.3

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9882]
## Describe the bug

Setting up `Talos v1.8.3` by [the refined terraform script](https://github.com/longhorn/longhorn-tests/pull/2172), and install Longhorn and try to create a backing image with `minimum number of copies = 3` using a `raw` format image from the url `https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.raw`:

![bi0](https://github.com/user-attachments/assets/4dac9e83-c8c2-4e7c-872d-04ef4facb77a)

It fails to transfer the backing image to other nodes to maintain minimum number of copies: 

![bi](https://github.com/user-attachments/assets/18c8a6b2-bb65-42cb-86ed-d9f978163977)

The error message encountered is:

```
found mismatching realSize 1773568 reported by backing image manager backing-image-manager-b2c6-c910 
in disk c9103764-6323-4a5a-9d3c-87087408ae76, the realSize recorded in status is 1777664
```

- `qcow2` format doesn't have this issue:

![bi1](https://github.com/user-attachments/assets/411fe916-1b24-403d-8737-5ae43df91b0c)

- `Talos v1.7.6` doesn't have this issue: 

https://ci.longhorn.io/job/public/job/master/job/talos/job/amd64/job/longhorn-tests-talos-amd64/14/testReport/

## To Reproduce

Create a backing image from the url `https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.raw`.

Or run test case `test_backing_image_basic_operation`.

## Support bundle for troubleshooting

[supportbundle_4db44568-eea6-4a67-8284-b2f0f942804e_2024-12-02T06-24-44Z.zip](https://github.com/user-attachments/files/17973559/supportbundle_4db44568-eea6-4a67-8284-b2f0f942804e_2024-12-02T06-24-44Z.zip)

## Environment

 - Longhorn version: master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.31.1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: talos v1.8.3
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
cc @ChanYiLin

**Comment by ChanYiLin** [comment]
Fix together in https://github.com/longhorn/longhorn/issues/9882

**Comment by ChanYiLin** [comment]
Hi @yangchiu 
Can you help to verify if this is fixed in Talos, thanks!

**Comment by yangchiu** [comment]
Verification passed on master-head (longhorn-manager ) and v1.8.x-head (longhorn-manager ). Backing images can be created without any issues, and corresponding test cases passed.

master-head: https://ci.longhorn.io/job/public/job/master/job/talos/job/amd64/job/longhorn-tests-talos-amd64/45/
v1.8.x-head: https://ci.longhorn.io/job/public/job/master/job/talos/job/amd64/job/longhorn-tests-talos-amd64/46/
