### ISSUE TITLE
[IMPROVEMENT] Logging the reason why the instance manager pod is going to be deleted.

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#9886]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

For the IM pods are going to be restarted, from my code reading, it seems [LH proactively restarts the IM pod only if there is no running instance in the IM](https://github.com/longhorn/longhorn-manager/blob/dcd5164185d7130732f72bb2e978dfdc0338acd1/controller/instance_manager_controller.go#L450-L487).

The method `cleanupInstanceManager` will be called for multiple reasons and Longhorn needs to record the reason for investigating.

## Describe the solution you'd like

Add a log to record why Longhorn needs to clean up the instance manager pods.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (https://github.com/longhorn/longhorn-manager/commit/6da14ea7d571c7e73b6eae663fc11154d346de1e)


Following test [steps](https://github.com/longhorn/longhorn/issues/9886#issuecomment-2520551338), can see below logs mention instance manager pod deletion.
```log
time="2024-12-10T06:28:55Z" level=warning msg="Deleting instance manager pod instance-manager-91a4cb88c75b874697f7ac924a9bda2f since one of the following conditions is met: setting is not synced (true) or data engine CPU mask is not applied (false), instances are running in the pod (false), or the pod is deleted or not running (true)" func="controller.(*InstanceManagerController).handlePod" file="instance_manager_controller.go:606" controller=longhorn-instance-manager instanceManager=instance-manager-91a4cb88c75b874697f7ac924a9bda2f node=ip-172-31-43-213 nodeID=ip-172-31-43-213
time="2024-12-10T06:28:55Z" level=info msg="Creating instance manager pod" func="controller.(*InstanceManagerController).createInstanceManagerPod" file="instance_manager_controller.go:1310" controller=longhorn-instance-manager instanceManager=instance-manager-91a4cb88c75b874697f7ac924a9bda2f node=ip-172-31-43-213 nodeID=ip-172-31-43-213
```
