### ISSUE TITLE
Show volume related events in the volume details

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#990]
In Kubernetes, events provide a clue on what's happening and what went wrong, helps debug immensely. We already have the event mechanism hooked up in Longhorn, but we still rely on the manager's log mostly for troubleshooting.

We should record and show the major events for the volume/node, which make it easier for user to see what went wrong without diving into the manager's log every time.

**Comment by yasker** [comment]
We want to include objects: volume(use volume name), engine (use engine name), replicas (use replica names). Those can be found in the `v1/events` API call's. We can use events' `involvedObject` to find the object. 

<img width="898" alt="Screen Shot 2020-05-03 at 6 41 49 PM" src="https://user-images.githubusercontent.com/3344618/80931487-fab05300-8d6e-11ea-8ca9-83381b7219f2.png">

**Comment by yasker** [comment]
- [ ] It seems not sorted by the Last time occurred. 

<img width="1537" alt="Screen Shot 2020-05-07 at 11 31 10 AM" src="https://user-images.githubusercontent.com/3344618/81331333-48220e00-9056-11ea-8d9c-1cfcf570518c.png">

- [ ] Can we make it expandable? We can hide it by default since it took quite some space.
- [ ] How often are we refreshing it? It seems a bit late compare to the volume state. I saw there is WebSocket API for events as well.

**Comment by yasker** [comment]
- [ ] Can we make clicking the `+` to expand, instead of clicking the `Expand` button? It's consistent with our node page.

**Comment by sowmyav27** [comment]
Verified on master - 05/18/2020

@yasker The event log has the "expand" button also along with `+` on the UI.
Do we want it like this? 
<img width="1873" alt="Screen Shot 2020-05-18 at 2 30 14 PM" src="https://user-images.githubusercontent.com/26032343/82261680-586aa080-9914-11ea-957b-576a3464e775.png">

**Comment by yasker** [comment]
@sowmyav27 Good question. How about removing the `Expand` button on the right? And add a tooltip to the `+` say `Click to expand`/`Click to Collapse`

**Comment by sowmyav27** [comment]
@yasker This https://github.com/longhorn/longhorn/issues/990#issuecomment-630448029 sounds good.

**Comment by yasker** [comment]
@smallteeths ^^

**Comment by sowmyav27** [comment]
**Verified using image tag: `wangsiye/longhorn-ui:7bb2f43`**

Validation: **`PASSED`**
<img width="1629" alt="Screen Shot 2020-05-19 at 3 45 32 PM" src="https://user-images.githubusercontent.com/26032343/82385810-cb911700-99e7-11ea-9f74-444ae34252e1.png">

**Comment by sowmyav27** [comment]
**Verified on master - 05/21/2020**

Validation: **`PASSED`**
<img width="1889" alt="Screen Shot 2020-05-21 at 3 56 45 PM" src="https://user-images.githubusercontent.com/26032343/82614048-bbaa3c00-9b7b-11ea-876b-5830b6be9dba.png">
