### ISSUE TITLE
[FEATURE] Add kernel module check for data engine v2

### ISSUE THREAD

**Issue by jangseon-ryu** [longhorn/longhorn#9915]
## Is your feature request related to a problem? Please describe (👍 if you like this request)
Currently, the kernel module check only verifies dm_crypt. It would be beneficial to also check the kernel modules used by Longhorn Engine v2 (vfio_pci, uio_pci_generic, nvme_tcp) to ensure accurate node status reporting.

This enhancement would help validate that the required kernel modules for v2 environments are properly loaded, improving overall reliability and stability.

## Describe the solution you'd like
1. Common Modules: Always checks common kernel modules applicable to all engine versions.
2. v2 Modules: Includes additional v2-specific kernel modules (vfio_pci, uio_pci_generic, nvme_tcp) when the v2-data-engine setting is enabled.
3. Error Handling: Ensures that if the v2-data-engine setting check fails, common kernel modules are still verified without interrupting operations.

**Comment by derekbit** [comment]
cc @COLDTURNIP @c3y1huang

**Comment by c3y1huang** [comment]
This is already included in the CLI, removing `area/cli` label.
https://github.com/longhorn/cli/blob/v1.8.0-dev-20241201/pkg/local/preflight/checker.go#L130-L132
cc @derekbit

**Comment by roger-ryao** [comment]
**Verified on v1.8.0-dev-20241201 20241209**

- longhorn `v1.8.0-dev-20241201` https://github.com/longhorn/longhorn/commit/9e8a84bdc8b3cfc2e0cf53415ee2bc3f2d8753e2
- cli `v1.8.0-dev-20241201` https://github.com/longhorn/cli/commit/cd47aee9b2c0feb7dfa9e637cd9b89531cc675d9

**Result Passed**

- [x] `longhorn-cli` : The Longhorn CLI can successfully support checking `vfio_pci`, `uio_pci_generic`, `nvme_tcp`.

```bash
# ./longhornctl-linux-amd64 check preflight --enable-spdk
...
  warn:
  - Kube DNS "coredns" is set with fewer than 2 replicas; consider increasing replica count for high availability
ip-10-0-2-205:
  info:
  - Service iscsid is running
  - NFS4 is supported
  - Package nfs-client is installed
  - Package open-iscsi is installed
  - Package cryptsetup is installed
  - Module dm_crypt is loaded
  - CPU instruction set sse4_2 is supported
  - HugePages is enabled
  - Module nvme_tcp is loaded
  - Module uio_pci_generic is loaded
  - Module vfio_pci is loaded
  warn:
  - Kube DNS "coredns" is set with fewer than 2 replicas; consider increasing replica count for high availability 
INFO[2024-12-09T11:44:56Z] Cleaning up preflight checker                
INFO[2024-12-09T11:44:57Z] Completed preflight checker

```
