### ISSUE TITLE
[IMPROVEMENT] No need to redirect `spdk_tgt` log to `/var/log/spdk_tgt.log`

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9926]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

No need to redirect `spdk_tgt` log to `/var/log/spdk_tgt.log`, because the log messages are already redirected to longhorn-instance-manager pod.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn  master(https://github.com/longhorn/longhorn-instance-manager/commit/a809870091964ac9175ed39d66ec3dfe523b0955)

There is no `/var/log/spdk_tgt.log` file in a v2 instance-manager pod.
```bash
> kl exec -it instance-manager-2e51568d1f69f3e64bb58e3112c3dc34 -- /bin/bash -c "ls -l /var/log/spdk_tgt.log"
ls: cannot access '/var/log/spdk_tgt.log': No such file or directory
command terminated with exit code 2
````
