### ISSUE TITLE
UI: Show rebuild progress

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#993]
1)  The rebuild status/progress is stored in the `volume.rebuildStatus`
2) Show the rebuild status if:
  2.1) The volume is attached
  2.2) There is a matching replica for the entry in the `volume.rebuildStatus`
  2.3) Show the progress `volume.rebuildStatus[replicaName].progress` for the rebuilding replica if `volume.rebuildStatus[replicaName].isRebuilding == true && volume.rebuildStatus[replicaName].state == "in_progress"` 
  2.4) Show the error `volume.rebuildStatus[replicaName].error` if rebuild fails

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
  - Create a volume, attach it to a node
  - Mount volume to directory, write some data to it.
  - In Volume Details page, delete a replica.
  - New replicas should be created, volume state should be `Degraded`
  - Hovering on new replica progress bar, a tooltip should appear contains rebuild progress percentage. **(PASS)**
  - In Volume page, a progress bar should appear over volume state which should be `Degraded` in that case, Hovering on the progress bar, a tooltip should appear contains rebuild progress percentage.  **(PASS)**

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test:
  - Create a volume, attach it to a node
  - Mount volume to directory, write some data to it.
  - In Volume Details page, delete a replica.
  - New replicas should be created, volume state should be `Degraded`
  - Hovering on new replica progress bar, a tooltip should appear contains rebuild progress percentage. **(PASS)**
  - In Volume page, a progress bar should appear over volume state which should be `Degraded` in that case, Hovering on the progress bar, a tooltip should appear contains rebuild progress percentage.  **(PASS)**
