### ISSUE TITLE
[BUG] v2 volume cannot be attach after upgrading

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#9943]
## Describe the bug

v2 volume cannot be attach after upgrading

## To Reproduce

1. Deploy Longhorn v1.7.2, create a v2 volume
1. Attach volume, detach it.
1. Update longhorn system to master-head
1. Wait for Longhorn manager to delete old IM pods and create new IM pods
1. Attach the volume -> Failed to attach
    `
    time="2024-12-10T06:23:29Z" level=error msg="Failed to sync Longhorn volume" func=controller.handleReconcileErrorLogging file="utils.go:79" Volume=longhorn-system/pvc-d402c4d3-788e-4d20-8ab3-9bce947e6d8d controller=longhorn-volume error="failed to sync longhorn-system/pvc-d402c4d3-788e-4d20-8ab3-9bce947e6d8d: failed to reconcile volume state for pvc-d402c4d3-788e-4d20-8ab3-9bce947e6d8d: failed to find instance manager for replica pvc-d402c4d3-788e-4d20-8ab3-9bce947e6d8d-r-21baaab4: cannot find the only available instance manager for instance pvc-d402c4d3-788e-4d20-8ab3-9bce947e6d8d-r-21baaab4, node phan-v701-pool2-dzrts-wtsnb, instance manager image longhornio/longhorn-instance-manager:master-head, type aio" node=phan-v701-pool2-dzrts-k86fv
    `

## Expected behavior

Volume should able to attach 

## Additional context 

Looks like we don't use the default IM for replica launching for v2 volume. It is will be selected based on replica.Spec.Image. Ref code https://github.com/longhorn/longhorn-manager/blob/6da14ea7d571c7e73b6eae663fc11154d346de1e/datastore/longhorn.go#L3781-L3790

**Comment by roger-ryao** [comment]
**Verified on master-head 20241211**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/979eb98a950739d3a832100747fde2960a12ca7e
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/2838f94e5bb39bfe612cbc0a2d411d05df5f8d20

**The test steps**
https://github.com/longhorn/longhorn/issues/9943#issue-2729190475

**Result Passed**
