### ISSUE TITLE
Find a better way to figure out if the replica directory in the data path exists

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#996]
Refer to https://github.com/longhorn/longhorn/issues/989

Right now Longhorn just relies on the command `ls <data path>/replicas/` to check if the directory exists. If the command errors out, Longhorn simply considers the directory as not existing and tries to create it. See [here ](https://github.com/longhorn/longhorn-manager/blob/9002e28138476a4ff7c997710f154722bed57566/util/util.go#L581) for details.

Actually, the error can be triggered by some other issues, e.g., the data path is not accessible.

**Comment by yasker** [comment]
The issue doesn't apply anymore after https://github.com/longhorn/longhorn-manager/commit/147bc6cfff391e63647ecc7959086c08da024e67
