### ISSUE TITLE
Longhorn system backup runs weekly

### ISSUE THREAD

**Issue by surendra-ta** [longhorn/longhorn#9973]
apiVersion: longhorn.io/v1beta2
kind: SystemBackup
metadata:
  name: demo-backup
  namespace: longhorn-system
spec:
  volumeBackupPolicy: if-not-present
 hello guys, can you help me to  run this SystemBackup job weekly.

**Comment by derekbit** [comment]
Please follow up https://github.com/longhorn/longhorn/issues/6534
