### ISSUE TITLE
[IMPROVEMENT][UI] Attach table search keyword to URL on Backup pages

### ISSUE THREAD

**Issue by houhoucoop** [longhorn/longhorn#9974]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Currently, the search keyword is not reflected in the URL for tables on the Backup page, unlike other pages.

## Describe the solution you'd like

The search keyword should append to the URL as a query parameter, allowing direct access to filtered results, e.g.
- http://localhost:8080/#/backup#backing-image?field=name&value=qwe
- http://localhost:8080/#/backup#volume?field=name&value=qwe

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by derekbit** [comment]
@houhoucoop ready for testing?

**Comment by houhoucoop** [comment]
The issue becomes invalid after multiple backup target backend PRs are merged. 
Andy addressed it in [PR #755](https://github.com/longhorn/longhorn-ui/pull/755), but the query parameters will be different.
e.g. `?field=name&value=pvc#volume` becomes `?field=volumeName&value=pvc#volume`.
I'm not sure how to proceed in this case, any suggestions? cc @a110605

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-ui/commit/ddfa9ddd99c407e0a8f97736438200d1486e1169) v1.8.x(https://github.com/longhorn/longhorn-ui/commit/ebcf89e35715f6daac43b6db8f32b71ae7a3c03a)

Search keyword appeared on Backup pages URL correctly.
