### ISSUE TITLE
[BUG] Backup does not appear on the backup page

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9985]
## Describe the bug

Install Longhorn master-head (longhorn-manager `601b04b`, longhorn-ui `944339c`).

Create a volume and create a backup for it. The backup does not appear on the backup page.

## To Reproduce

1. Create a volume and attach it to a node, then create a backup for it:

![backup0](https://github.com/user-attachments/assets/9053e5ce-df1e-436a-9f09-4cafec6f4928)

```
$ kubectl get backupvolumes -n longhorn-system
NAME                CREATEDAT              LASTBACKUPNAME            LASTBACKUPAT           LASTSYNCEDAT
18926f94-d6acb09c   2024-12-16T12:19:07Z   backup-75df12e87ac94d45   2024-12-16T12:19:07Z   2024-12-16T12:19:12Z

$ kubectl get backups -n longhorn-system
NAME                      SNAPSHOTNAME                           SNAPSHOTSIZE   SNAPSHOTCREATEDAT      BACKUPTARGET   STATE       LASTSYNCEDAT
backup-75df12e87ac94d45   5111de03-f8aa-44df-8b28-584e53fcbd6c   0              2024-12-16T12:19:07Z                  Completed   2024-12-16T12:19:12Z
```

2. Navigate to the backup page. The backup appears for about 1 second, and then disappears:

![backup1](https://github.com/user-attachments/assets/a74a9b0c-0a7f-4a72-a5a0-bcdf3317bbbf)

After 1 second:

![backup2](https://github.com/user-attachments/assets/c0680c93-17ca-4378-8cfd-03143b4994f7)

## Expected behavior

[supportbundle_9be831a4-6586-476d-bd2f-2575060214ad_2024-12-16T12-31-02Z.zip](https://github.com/user-attachments/files/18149994/supportbundle_9be831a4-6586-476d-bd2f-2575060214ad_2024-12-16T12-31-02Z.zip)

## Environment

 - Longhorn version: master-head 
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.31.1+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: ubuntu 22.04
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
@mantissahz Please help check this if UI needs any update after merging the multiple backupstore feature.

**Comment by derekbit** [comment]
cc @a110605

**Comment by mantissahz** [comment]
> @mantissahz Please help check this if UI needs any update after merging the multiple backupstore feature.

Yes, it needs UI updates after multiple backup stores is merged.

**Comment by derekbit** [comment]
Let's speed up the UI part @a110605 @mantissahz

**Comment by yangchiu** [comment]
The backup volume created is named `18926f94-d6acb09c`, but the actual volume is named `test-1`, which is inconsistent.

**Comment by derekbit** [comment]
> The backup volume created is named `18926f94-d6acb09c`, but the actual volume is named `test-1`, which is inconsistent.

After discussing with @mantissahz , the backup volume naming is expected, but it is not friendly to users. Using `<volume name>-<random id>` as a BV name is better.

**Comment by yangchiu** [comment]
Verification passed on v1.8.x-head (longhorn-manager e945524) and master-head (longhorn-manager def8a3b) following [the test plan](https://github.com/longhorn/longhorn/issues/9985#issuecomment-2550202264).

Backups are displayed on the backup page without any issues:

![backup-new](https://github.com/user-attachments/assets/c8eb4e7a-6cc8-46be-b7ec-dc2a0a043ef3)
